### ISSUE TITLE
[Release-1.28] - Unable to provision K3S downstream cluster in Rancher

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10007]
Backport fix for Unable to provision K3S downstream cluster in Rancher

* #10004

**Comment by mdrahman-suse** [comment]
# Validation with RC v1.28.9-rc2+k3s1

Followed similar setup and steps to replicate and validate the issue: https://github.com/k3s-io/k3s/issues/10004#issuecomment-2073845201. Also validated split roles cluster got provisioned successfully on Rancher v2.8.3 and k3s v1.28.9-rc2+k3s1
