### ISSUE TITLE
Add Ubuntu 24.04 Support to k3s

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#10028]
**K3s Versions to be Validated**

TBD

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

Internal reference: SURE-8314

**Comment by rancher-max** [comment]
Validated with April releases:
v1.29.4+k3s1
v1.28.9+k3s1
v1.27.13+k3s1
