### ISSUE TITLE
Embedded helm controller does not track owner references properly

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10051]
The helm-controller refactor in in https://github.com/k3s-io/helm-controller/pull/157 added a `WithSetOwnerReference(false, false)` to the desiredset/apply controller, but that was missed when we pulled in the refactor into k3s in https://github.com/k3s-io/k3s/pull/6294.

As a result, the helm controller has been failing to properly track resource ownership, and owned objects are sometimes orphaned instead of being properly deleted.

**Comment by brandond** [comment]
@huangzynn do you have any specific steps to reproduce incorrect behavior that this omission was causing? While not technically correct, I am not aware of any easy-to-reproduce problems that this fixes.

**Comment by fmoral2** [comment]
@huangzynn any thoughts here ?

**Comment by fmoral2** [comment]
Trying to replicate the issue with no success

always getting 
```
in both versions am testing we do have the
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mynginx-5d8b585d74
    uid: 180b0817-7926-41d1-95b8-21d13219ce2f
  resourceVersion: "881"
```

and no deletion jobs or orphans left behind.
