### ISSUE TITLE
Expose k3s metrics over http

### ISSUE THREAD

**Issue by AkankshaHegde** [k3s-io/k3s#10059]
I want to get k3s metrics like pods and services, nodes and node health, then all the resources (e.g. secrets, pvcs, deployments, etc) and resource utilization and expose it over http which I can utilize later. Please do let me know how this can be acheived.

**Comment by brandond** [comment]
You can scrape those metrics from any of the normal Kubernetes metrics endpoints. Note that these are available over https, not http, and require authentication with a RBAC role that has access to /metrics, as in vanilla Kubernetes.

**Comment by AkankshaHegde** [comment]
May I know how this can be done. Can you please point me to some resources to do the same.
