### ISSUE TITLE
Update minio-go to `v7.0.70` or newer

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10050]
We are still on [v7.0.33](https://github.com/minio/minio-go/releases/tag/v7.0.33), which is from August 2022. There have been many bugfixes, including fixes for intermittent issues with multipart uploads against S3 "compatible" storage services that don't behave exactly like AWS.

We should update to the latest version.

**Comment by cwayne18** [comment]
Let's make sure to have either dependabot or updatecli do these in the future automatically

**Comment by brandond** [comment]
@cwayne18 back to PTO with you!

**Comment by rancher-max** [comment]
minio-go version looks correct in all go.mod files. General regression tests should catch any issues that arise from this, so closing out this issue without explicit testing beyond that.
