### ISSUE TITLE
k3s warning "Unable to fetch coredns config map" even with --no-deploy coredns

### ISSUE THREAD

**Issue by xiaosuiba** [k3s-io/k3s#1006]
**Version:**

k3s version v0.9.1 (755bd1c6)

**Describe the bug**

We use a custom coredns instead of the k3s provided one. After deployed, our coredns works fine, but k3s server continues warning `"level=warning msg="Unable to fetch coredns config map: configmap \"coredns\" not found"`.

**To Reproduce**

Run k3s server without coredns
``k3s server --no-deploy coredns``
then check logs.

**Expected behavior**

no warnings about coredns configmap.

**Actual behavior**

k3s server continues warning `"level=warning msg="Unable to fetch coredns config map: configmap \"coredns\" not found"`.

**Additional context**

https://github.com/rancher/k3s/blob/16da9edf45c58080097d5208b9d9e09013cd6fe6/pkg/node/controller.go#L59
```go
configMapCache, err := h.configCache.Get("kube-system", "coredns")
	if err != nil || configMapCache == nil {
		logrus.Warn(errors.Wrap(err, "Unable to fetch coredns config map"))
		return nil, nil
	}
```

**Comment by caroline-suse-rancher** [comment]
Closing due to age and inactivity
