### ISSUE TITLE
Update etcd to >= v3.5.13

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10076]
We need to pull in https://github.com/etcd-io/etcd/pull/17566, the fix for 
* https://github.com/etcd-io/etcd/issues/17507

This breaks watch progress requests - use of this is currently locked behind the `WatchList` FeatureGate but it will be enabled soon.

**Comment by VestigeJ** [comment]
Verified via go.mod here https://github.com/rancher/distros-test-framework/actions/runs/9471069323/attempts/1#summary-26093408016
