### ISSUE TITLE
unable to get REST mapping for extensions

### ISSUE THREAD

**Issue by BlackTurtle123** [k3s-io/k3s#10107]
**Environmental Info:**
K3s Version: 
k3s version v1.29.2+k3s1 (86f10213)
go version go1.21.7

Node(s) CPU architecture, OS, and Version: 
Linux node 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

Cluster Configuration:
Single system

**Describe the bug:**
Logs are being spammed with; 

`12990 garbagecollector.go:406] "error syncing item" err="unable to get REST mapping for extensions`

**Expected behavior:**
No error logs being spammed

**Actual behavior:**
Constant spamming of logs that are similar but different api versions

**Additional context / logs:**
```
12990 garbagecollector.go:406] "error syncing item" err="unable to get REST mapping for extensions/v1beta1/Ingress
garbagecollector.go:406] "error syncing item" err="unable to get REST mapping for cert-manager.io/v1alpha2/CertificateRequest."
```

**Comment by brandond** [comment]
This is a Kubernetes issue, not K3s. 
* https://github.com/kubernetes/kubernetes/issues/102641
