### ISSUE TITLE
Path /usr/local/bin missing while running sudo

### ISSUE THREAD

**Issue by x86Since8088** [k3s-io/k3s#10175]
**Environmental Info:**
K3s Version: 

go version go1.21.9

Node(s) CPU architecture, OS, and Version: 

Linux k3s.ds.skarke.net 5.14.0-427.16.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 8 17:48:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 node fresh install

**Describe the bug:**

Path /usr/local/bin missing while running sudo
This is resolved by running visudo and editing this line

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin

Add  :/usr/local/bin

**Steps To Reproduce:**

- added a new user
- added user to wheel group
- edited wheel to allow sudo without pw prompt
- Installed K3s: on Rocky Linux
- sudo k3s kubectl get nodes
- the k3s command could not be found 

**Expected behavior:**

[k3suser@k3s ~]$ sudo k3s kubectl get nodes
NAME                STATUS   ROLES                  AGE     VERSION
k3s.domain.net   Ready    control-plane,master   3h38m   v1.29.4+k3s1

**Actual behavior:**

the k3s command could not be found 

**Additional context / logs:**

**Comment by x86Since8088** [comment]
The install script could provide a warning and instructions to resolve.

**Comment by brandond** [comment]
Validating sudo's path is somewhat outside the realm of what k3s is expected to manage.
