### ISSUE TITLE
Certificates of Controller Manager and Scheduler should be rotated when --cert-dir arg is specified

### ISSUE THREAD

**Issue by orangedeng** [k3s-io/k3s#10176]
**Is your feature request related to a problem? Please describe.**
When k3s is provisioned with Rancher, the cert-dir args of cm/scheduler is specified. The certificate are used for `rancher-system-agent` to do health check for cm/scheduler.

When rotating cert which k3s command, those certs are not rotated for now. And When those certs are expired, cm/scheduler probes will fail and not be able to recover by itself.

**Describe the solution you'd like**
`k3s certificate rotate` should also rotate cm/scheduler certs. Just deleting the certs when rotating them and cm/scheduler will generate a new one on boot time.

**Describe alternatives you've considered**
It can also be done in Rancher side but kubeadm do the certificate rotation in the same logic so k3s should also take care of it.

**Additional context**
N/A

**Comment by brandond** [comment]
These certificates are not manager by k3s and are not signed by the k3s cluster CA. Since they are only enabled when the components are instructed by Rancher to generate these certs, Rancher is responsible for rotating them.
