### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by johnsmzr** [k3s-io/k3s#10207]
**Describe the bug:**
Installation is broken:
```
curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
[ERROR]  Download failed
```

And that page is `not found`.

Please check it.

Node(s) CPU architecture, OS, and Version: Intel-x86, Ubuntu 22.04

**Comment by brandond** [comment]
I can't reproduce this.

```console
root@systemd-node-1:/# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.29.4+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.29.4+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.29.4+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
```

Please make sure there isn't anything blocking your access to the k3s channel server. You could also try specifying which specific K3s version to install via the INSTALL_K3S_VERSION environment variable.

**Comment by cwayne18** [comment]
Are you using the curl snap? Sometimes we've seen this happen when it doesn't have permissions

**Comment by johnsmzr** [comment]
@cwayne18 @brandond 

Thanks for the reply! 😉

> You could also try specifying which specific K3s version to install via the INSTALL_K3S_VERSION environment variable.
Yes, this is how I bypass the problem.

> Are you using the curl snap? Sometimes we've seen this happen when it doesn't have permissions
No, I'm not using snap.
```
# which curl
/usr/bin/curl
```
