### ISSUE TITLE
Request to upgrade to kube-router upstream

### ISSUE THREAD

**Issue by shouya** [k3s-io/k3s#10205]
**Environmental Info:**
K3s Version: v1.30.0+k3s1

----

Hi, I was using k3s in my home cluster and noticed the `ipset` set by my own firewall script gets reverted back periodically. For detail please look into my bug report to kube-router: https://github.com/cloudnativelabs/kube-router/issues/1677.

After a long discussion and troubleshooting with the developer, we found that the kube-router version k3s uses is not in sync with the upstream. More specifically, despite [the import statements](https://github.com/k3s-io/k3s/blob/release-1.29/pkg/agent/netpol/netpol.go#L20) and [go.mod](https://github.com/k3s-io/k3s/blob/release-1.29/go.mod#L8) imply using kube-router from the upstream, the actual logs and other hints suggest it's likely still using [k3s's fork](https://github.com/k3s-io/kube-router), which falls behind the upstream by [many commits](https://github.com/k3s-io/kube-router/compare/master...cloudnativelabs%3Akube-router%3Amaster).

The developer of kube-router suggested the bug has been fixed in their v2.1.2 release, but apparently still present in the latest k3s. Could you please help update the code to keep up with the upstream?

**Comment by brandond** [comment]
cc @manuelbuil

**Comment by manuelbuil** [comment]
kube-router will be using v2.1.2 release in the K3s June release: https://github.com/k3s-io/k3s/pull/10177
