### ISSUE TITLE
Request for loongarch version

### ISSUE THREAD

**Issue by Qinka** [k3s-io/k3s#10216]
Request for loongarch64 version k3s.

I tried to compile k3s on loongarch64, but I cannot install dapper.

**Comment by brandond** [comment]
Highly unlikely, however we can leave it in the backlog.

Note that besides k3s itself you'll also need images to run on this architecture, and i don't think I've seen any common base images (alpine, etc) that support it yet.

**Comment by ysicing** [comment]
@yzewei https://github.com/Loongson-Cloud-Community/k3s 
Could you please synchronize with the upstream 🤔?

**Comment by cwayne18** [comment]
We do not have plans to support this
