### ISSUE TITLE
Pod cannot establish a connection

### ISSUE THREAD

**Issue by rhizoet** [k3s-io/k3s#10223]
**Environmental Info:**
K3s Version: 
1.29.4

Node(s) CPU architecture, OS, and Version: 
AMD64, Ubuntu 22.04

Cluster Configuration:
3 servers, 2 agents

**Describe the bug:**
After the classic installation of k3s, without further configuration, we wanted to install the netbird client. This should actually establish a connection to the netbird server.
Unfortunately, no connection can be established to this server, as the domain netbird.example.com cannot be reached. On the node itself as well as on k0s and other Kubernetes installations it works without any further problems.

We have also already tried to use calico. However, this also makes no difference.

Is it possible that there are some routes set up in k3s that prevent wireguard or a connection to such a server? It seems that this is a DNS problem. However, I cannot determine what it could be.

netbird is basically a server with a UI for Wireguard. Comparable to tailscale.

**Steps To Reproduce:**
- Install K3s
- have a self-hosted netbird-server
- setup the client with a kubernetes deployment

**Expected behavior:**
The deployment should be applied to the cluster and the client should be able to connect directly to the server.

**Actual behavior:**
The netbird pod cannot connect to the server. The connection is aborted.

**Additional context / logs:**

**Comment by brandond** [comment]
I don't know what netbird is or how to suggest troubleshooting it, but this doesn't sound like a problem with K3s itself.

Have you tried execing into the pod and confirming that the server address can be resolved, and tried using curl or another command-line client to make a test request to see if it works? If these tests fail, what specific errors do you get?
