### ISSUE TITLE
sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported

### ISSUE THREAD

**Issue by hanzhc** [k3s-io/k3s#10281]
1. k3s:1.23.17+k3s
2. mysql: 8.0
3. The script for installation:

INSTALL_K3S_SKIP_DOWNLOAD=true \
K3S_NODE_NAME=k3s-server1 \
K3S_TOKEN=SECRET \
INSTALL_K3S_EXEC="--node-ip 10.10.115.76 \
--log /var/log/k3s-log.log \
--flannel-backend=none \
--cluster-cidr=192.168.200.0/24 \
--service-cidr=10.244.0.0/16 \
--disable=traefik \
--disable=metrics-server \
--disable-cloud-controller \
--disable-helm-controller \
--kube-proxy-arg=proxy-mode=ipvs" \
sh /root/k3s-install.sh server --cluster-init \
--datastore-endpoint="mysql://root:root123@tcp(10.10.115.71:3306)/k3s" \
--tls-san=10.10.115.109 \
--write-kubeconfig ~/.kube/config

4. The error message:
time="2024-06-04T11:20:48+08:00" level=info msg="Starting k3s v1.23.17+k3s1 (abb8d7d4)"
time="2024-06-04T11:20:48+08:00" level=info msg="Configuring mysql database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
time="2024-06-04T11:20:48+08:00" level=info msg="Configuring database table schema and indexes, this may take a moment..."
time="2024-06-04T11:20:48+08:00" level=info msg="Database tables and indexes are up to date"
time="2024-06-04T11:20:48+08:00" level=info msg="Kine available at unix://kine.sock"
time="2024-06-04T11:20:48+08:00" level=error msg="error while range on /bootstrap /bootstrap: sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"
{"level":"warn","ts":"2024-06-04T11:20:48.409+0800","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00147e1c0/kine.sock","attempt":0,"error":"rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"}
time="2024-06-04T11:20:48+08:00" level=fatal msg="starting kubernetes: preparing server: rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"

**Comment by brandond** [comment]
> `v1.23.17+k3s`

This is a 15 month old release of k3s. Please use a version that is not end of life.

**Comment by MinvenX** [comment]
k3s 1.29.4 repeat the same issue

**Comment by brandond** [comment]
K3s v1.29.4 is currently 18 months old (Apr 25 2024).

I am going to lock this. If anyone can ever reproduce this on a version that is not well over a year old at the time of their report, please open a new issue, and provide specific steps to reproduce.
