### ISSUE TITLE
K3S server doesn't start on RHEL9

### ISSUE THREAD

**Issue by ju55i** [k3s-io/k3s#10294]
**Environmental Info:**
K3s Version: 

k3s version v1.29.5+k3s1 (4e53a323)
go version go1.21.9

Node(s) CPU architecture, OS, and Version: 

Linux myserver 5.14.0-427.18.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 13 10:47:09 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

k3s service doesn't start

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://get.k3s.io | sh -

**Expected behavior:**

k3s service to start

**Actual behavior:**

Output from the end of the install:
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xeu k3s.service" for details.
Journald:
 time="2024-06-05T13:09:45+03:00" level=fatal msg="exec: \"k3s-server\": executable file not found in $PATH"

Same error when running from command line:
$ k3s server
FATA[0000] exec: "k3s-server": executable file not found in $PATH

**Comment by brandond** [comment]
The k3s binary is actually a self-extracting multicall binary, that unpacks the various bundled binaries out and then re-execs them. Something has prevented k3s from extracting its content to /var/lib/rancher/k3s/data. You can try deleting that folder and then restarting the service, but if this continues I would recommend  verifying that /var/lib/rancher/k3s is not on a read-only filesystem, and checking for any active security modules (ie selinux) that might be preventing content from being written to that path.

**Comment by lpb313** [comment]
Check if you do not have the _noexec_ attribute to the /var partition. Check the /etc/fstab file.
