### ISSUE TITLE
Remove `DisableCCM` from `CriticalControlArgs`

### ISSUE THREAD

**Issue by rassie** [k3s-io/k3s#10304]
**Is your feature request related to a problem? Please describe.**
We are building on-premise clusters on vSphere with additional bare-metal machines. In such scenarios, vSphere nodes need to use the vSphere Cloud Provider, while the bare-metal machines require the `cloud-controller-manager` to receive a `ProviderID`. This configuration, with `disable-cloud-controller` being set to different values (`true`/`false`) for different nodes, is [denied during join](https://github.com/k3s-io/k3s/blob/df5db28a687f5fb6fd0f5cb68873d2184974e953/pkg/cluster/bootstrap.go#L457). However, if we work around the config comparison, this configuration works perfectly well and as intended. 

**Describe the solution you'd like**
We'd like to argue that having `disable-cloud-controller` set to different values, while not being an officially supported configuration, is a legitimate use-case in mixed environments and as such, `DisableCCM` should not be part of [`CriticalControlArgs`](https://github.com/k3s-io/k3s/blob/df5db28a687f5fb6fd0f5cb68873d2184974e953/pkg/daemons/config/types.go#L148). This would allow bare-metal machines to join the cluster without tinkering. Judging by the intention of the `CriticalControlArgs` introduction, it's meant to be used for potentially cluster-breaking things like CIDRs, which `DisableCCM` in our opinion is not.  

**Describe alternatives you've considered**
Replacing bare-metal machines with vSphere VMs was not possible.

**Additional context**
We are actually not running K3s straight, but Rancher Manager with RKE2 clusters and we use `machineSelectorConfig` to provide different configurations to different node types. This results in correct configuration, with bare-metal nodes running with the default CCM and vSphere nodes running with vSphere CPI without conflicts. The configuration comparison at join is the only thing holding us back here.

**Comment by brandond** [comment]
We are not going to do this. All servers in the cluster should have the CCM enabled or disabled. CCMs are not designed for hybrid use cases where some nodes are managed by once cloud provider, and other nodes are managed by a different one. If some servers have it enabled and others do not, inconsistent behavior will be observed depending on which server holds the lease for various internal controllers.
