### ISSUE TITLE
Validate SUSE Liberty Linux 8.9

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#10366]
**K3s Versions to be Validated**

- v1.30.2+k3s1
- v1.29.6+k3s1
- v1.28.11+k3s1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

Please validate with Selinux enabled in the operating system and the config:
```
# /etc/rancher/k3s/config.yaml
selinux: true
```

SURE-8122

**Comment by aganesh-suse** [comment]
Verified k3s install/upgrade successfully with builds: 

    v1.30.2+k3s1
    v1.29.6+k3s1
    v1.28.11+k3s1
    v1.27.15+k3s1

Tests Run: 

    Install and run sonobuoy conformance tests on a hardened cluster
    Validate SUC upgrade
    Install Rancher Manager
    Validate snapshot restore via cluster-reset-restore-path

with selinux set to true.
