### ISSUE TITLE
Procedure for changing server one of a etcd cluster

### ISSUE THREAD

**Issue by SeaRoll** [k3s-io/k3s#10362]
Hi!

I'd like to know if someone has ever changed the location (IP address) of the first server in a cluster that uses etcd.

The first master server has the `--cluster-init`, but I'd like to move it to another master server in a data center.

Is there anyone here who has done this?

**Comment by brandond** [comment]
1. Ensure that no other nodes in the cluster are pointed directly at that node as the `server:` in their config.
2. `kubectl delete node` to remove the node from the cluster
3. Stop the service on the node, update the IP address, and remove the etcd db files from disk
4. Rejoin it to the cluster as if it was a new node.

**Comment by SeaRoll** [comment]
Thank you so much! tried this way and it worked
