### ISSUE TITLE
v1.30.2-rc3 Images missing

### ISSUE THREAD

**Issue by Xeroxxx** [k3s-io/k3s#10382]
**Environmental Info:**
K3s Version: 1.30.2-rc3

**Describe the bug:**
Code has been tagged with 1.30.2-rc3 without docker images test being successful.

System Upgrade controller already pulls latest testing but not able to pull  rancher/k3s-upgrade:v1.30.2-rc3-k3s1 as images havent been successfully tested and pushed.

**Steps To Reproduce:**
Install system upgrade jobs with testing channel.

- Installed K3s: 1.30.2-rc2

**Expected behavior:**
Images are present when promotion happens.

**Actual behavior:**
System upgrade fails.

`Warning  Failed     8m35s (x4 over 10m)  kubelet            Failed to pull image "rancher/k3s-upgrade:v1.30.2-rc3-k3s1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/ra ││ ncher/k3s-upgrade:v1.30.2-rc3-k3s1": failed to resolve reference "docker.io/rancher/k3s-upgrade:v1.30.2-rc3-k3s1": docker.io/rancher/k3s-upgrade:v1.30.2-rc3-k3s1: not found`

Latest commit for 1.30.2-rc3 E2E Tests:
https://github.com/k3s-io/k3s/actions/runs/9585998197/job/26433299829

**Comment by brandond** [comment]
Tags are what cause the image to be built; tags by definition exist before the images and other artifacts are built.

The channel server does not serve RC releases (or any other tag with a hyphen in it); can you confirm exactly what you're seeing?

https://github.com/k3s-io/k3s/blob/aa4794b37223156c5f651d94e23670bd7e581607/channel.yaml#L7

**Comment by brandond** [comment]
Oh I see, you're intentionally pulled from the testing channel. That's a footgun you've intentionally loaded, if you use that you might end up using things before they're done cooking.

**Comment by Xeroxxx** [comment]
> Oh I see, you're intentionally pulling from the testing channel. That's a footgun you've intentionally loaded, if you use that you might end up using things before they're done cooking.

Was already typing. Thanks for clarificaiton. Going to wait for build to finish. Thought I saw E2E Test for Push fail and this will result in no images.

Thanks!

**Comment by Xeroxxx** [comment]
@brandond 
Fun thing, even when the upgrade image can't be pulled. system update controller, already tainted the server node with "SchedulinDisabled" taint and does not reverse.
