### ISSUE TITLE
kubectl logs selectively timing out based on the host CIDR range

### ISSUE THREAD

**Issue by christian-schlichtherle** [k3s-io/k3s#10380]
**Environmental Info:**

K3s Versions: 
- v1.30.1+k3s1
- v1.26.15+k3s1

Node(s) CPU architecture, OS, and Version: 
```
$ ansible k3s -a 'uname -a'
beta-d0 | CHANGED | rc=0 >>
Linux beta-d0 6.1.43-vendor-rk35xx #1 SMP Mon May 20 12:26:58 UTC 2024 aarch64 GNU/Linux
beta-d1 | CHANGED | rc=0 >>
Linux beta-d1 6.1.43-vendor-rk35xx #1 SMP Mon May 20 12:26:58 UTC 2024 aarch64 GNU/Linux
[...]
```

Cluster Configuration:
```
$ kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE    VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION               CONTAINER-RUNTIME
beta-d1    Ready    control-plane,master   115m   v1.30.1+k3s1   10.91.0.9     <none>        Armbian 24.5.1 bookworm   6.1.43-vendor-rk35xx         containerd://1.7.15-k3s1
beta-d0    Ready    <none>                 115m   v1.30.1+k3s1   10.91.0.3     <none>        Armbian 24.5.1 bookworm   6.1.43-vendor-rk35xx         containerd://1.7.15-k3s1
[...]
```

Note the internal IPs are assigned from the OpenVPN interface `tun0` and belong to the CIDR range 10.91/16.

**Describe the bug:**

My company is running an IoT project where we integrate all IoT devices into a single large, distributed K3s cluster. Therefore we have some K3s nodes installed at customer premises, usually in a SOHO LAN with NAT, and some are running in the cloud (currently AWS). To make this work, we use Ansible to install OpenVPN on each node first and then install K3s and join the cluster. When installing K3s, we assign the OpenVPN interface `tun0` to flannel. Here's an example K3s configuration from the master node:

```
$ ansible k3s_server -b -a 'cat /etc/rancher/k3s/config.yaml'
beta-d1 | CHANGED | rc=0 >>
---
#
# Ansible managed
#
cluster-cidr: 10.52.0.0/16
cluster-dns: 10.53.0.10
flannel-backend: host-gw
flannel-iface: tun0
node-taint:
- node-role.kubernetes.io/control-plane=:NoSchedule
service-cidr: 10.53.0.0/16
```

This is working fine for over two years already. Recently however, we were evaluating netbird and tailscale for the many advantages they offer over OpenVPN like performance, topology and access control. We have been installing netbird and tailscale successfully on all nodes and verified the configuration of a fully working mesh VPN, like every node can ping every other node, iperf can run between all nodes in both directions etc.

Then we rebuild the cluster several times using "wt0" or "tailscale0" instead of "tun0" as the flannel interface for netbird and tailscale respectively. At first, everything seemed to work: Nodes would join the new cluster, pods were running etc. However, we figured that `kubectl logs` always runs into a timeout. Here's an example:

```
$ kubectl logs -n kube-system -l k8s-app=kube-dns
Error from server: Get "https://100.91.0.5:10250/containerLogs/kube-system/coredns-576bfc4dc7-9scw7/coredns?tailLines=10": Service Unavailable
```

However, when running `ansible k3s -a 'curl --include --insecure --silent $URL_FROM_ABOVE` we could see that all nodes were able to access the exact same URL without problems.

Finally, we ran another experiment and rebuilt the OpenVPN with a different CIDR. Before, OpenVPN was using the CIDR 10.91/16 as shown above and everything was working fine. After the change, OpenVPN was using the CIDR 100.91/16 and the result was... the exact same situation as with netbird and tailscale. Note that netbird and tailscale use similar looking CIDRs from the range of 100.64/10, which is intended to be used by network providers running CGNAT.

We were also checking the output of `sysctl net.ipv4.ip_forward` and `iptables --list` on all nodes and nothing out-of-the ordinary popped up.

PS: The K3s service on the master node shows the following log entry:

```
Jun 18 20:09:31 gamma-d1 k3s[15144]: E0618 20:09:31.111091   15144 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://100.91.0.5:10250/containerLogs/kube-system/coredns-576bfc4dc7-9scw7/coredns?tailLines=10", Err:(*errors.errorString)(0x400d66fef0)}: Get "https://10.91.0.5:10250/containerLogs/kube-system/coredns-576bfc4dc7-9scw7/coredns?tailLines=10": Service Unavailable
```

**Steps To Reproduce:**

1. Install K3s v1.30.1+k3s1 with at least two nodes (one node has not been tested) and assign them a flannel interface with an IP address from the CIDR range 100.91/16 or smaller.
2. Run `kubectl logs -n kube-system -l k8s-app=kube-dns` and watch for the timeout.

**Expected behavior:**

`kubectl logs` should not time out, regardless of the host CIDR.

**Actual behavior:**

`kubectl logs` times out when the host CIDR is set to `100.91/16`, but it works when the host CIDR is set to `10.91/16`.

**Additional context / logs:**

I can provide `iptables --list` output, but as said, there is no noticeable difference between a working CIDR range (10.91/16) and a non-working CIDR range (100.91/16).

**Comment by brandond** [comment]
> `Jun 18 20:09:31 gamma-d1 k3s[15144]: E0618 20:09:31.111091   15144 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://100.91.0.5:10250/containerLogs/kube-system/coredns-576bfc4dc7-9scw7/coredns?tailLines=10", Err:(*errors.errorString)(0x400d66fef0)}: Get "https://10.91.0.5:10250/containerLogs/kube-system/coredns-576bfc4dc7-9scw7/coredns?tailLines=10": Service Unavailable`

1. Can you show the output of `kubectl get node -o wide` when nodes are joined to the cluster with the `100.91/16` addresses?
2. Are you using a proxy? IF so can you confirm that `100.91/16` is included in your NO_PROXY env var?

**Comment by christian-schlichtherle** [comment]
Nevermind, I found the root cause: The `NO_PROXY` environment variable was set to this:

    NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local,localhost

Note that it's missing the 100.X CIDR range. So the fix is:

    NO_PROXY=127.0.0.0/8,10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16,.local,localhost

... and then it's working.

**Comment by brandond** [comment]
I will note that 100.64.0.0/10 is reserved for use on routing equipment as per RFC6598 and probably shouldn't be used on hosts as extension of RFC1918 addresses space...

> Shared Address Space is distinct from [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private address space
   because it is intended for use on Service Provider networks.
   However, it may be used in a manner similar to [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private
   address space on routing equipment that is able to do address
   translation across router interfaces when the addresses are identical
   on two different interfaces.  Details are provided in the text of
   this document.

**Comment by christian-schlichtherle** [comment]
> I will note that 100.64.0.0/10 is reserved for use on routing equipment as per RFC6598 and probably shouldn't be used on hosts as extension of RFC1918 addresses space...
> 
> > Shared Address Space is distinct from [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private address space
> > because it is intended for use on Service Provider networks.
> > However, it may be used in a manner similar to [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private
> > address space on routing equipment that is able to do address
> > translation across router interfaces when the addresses are identical
> > on two different interfaces.  Details are provided in the text of
> > this document.

Yes, but I have no choice here. The CIDR range 100.64/12 is selected by both Netbird and Tailscale and they don't support choosing another range.
