### ISSUE TITLE
Pod on remote worker could not resolve hostnames

### ISSUE THREAD

**Issue by jayturchi** [k3s-io/k3s#1039]
**Version:**

0.9.1

**Describe the bug**
With a fresh installation of k3s, one master and one worker, dns works only on master node.

To try it, I run a pod on each node and trying to ping google.com:

kubectl run -it --rm --restart=Never alpine_one --image=busybox sh
ping google.com

**To Reproduce**
on my local machine:

export SERVER_IP=my_master_ip
k3sup install --ip $SERVER_IP --user k3s --local-path=./kubeconfig --k3s-extra-args '--docker'
export IP=my_worker_ip
k3sup join --ip $IP --server-ip $SERVER_IP --user k3s --k3s-extra-args '--docker'

**Expected behavior**
On both pods ( one scheduled on master and one on worker ):
/ # ping google.com
PING google.com (172.217.18.206): 56 data bytes
64 bytes from 172.217.18.206: seq=0 ttl=52 time=6.515 ms
64 bytes from 172.217.18.206: seq=1 ttl=52 time=6.542 ms
64 bytes from 172.217.18.206: seq=2 ttl=52 time=6.734 ms

**Actual behavior**
**On master:**
/ # ping google.com
PING google.com (172.217.18.206): 56 data bytes
64 bytes from 172.217.18.206: seq=0 ttl=52 time=6.515 ms
64 bytes from 172.217.18.206: seq=1 ttl=52 time=6.542 ms
64 bytes from 172.217.18.206: seq=2 ttl=52 time=6.734 ms
**On worker:**
/ # ping google.com
ping: bad address 'google.com'

> kubectl get node -o wide

```
NAME                                  STATUS   ROLES    AGE   VERSION         INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION                  CONTAINER-RUNTIME
vpsxxx                                Ready    master   13m   v1.15.4-k3s.1   XX.XX.XX.XX   <none>        Ubuntu 18.04.3 LTS   4.15.0-58-generic               docker://19.3.4
ip-yyyyy.eu-west-1.compute.internal   Ready    worker   11m   v1.15.4-k3s.1   YY.YY.YY.YY   <none>        Amazon Linux 2       4.14.146-120.181.amzn2.x86_64   docker://18.6.1
```

**Comment by galal-hussein** [comment]
@jayturchi I can't reproduce the issue with 0.10.2 version, I started a master and two workers, all of them can reach the dns normally

**Comment by BlackTurtle123** [comment]
I have DNS issues, where resultion works very very very slow.
It works one in the 10 times. Without changing settings.
I reinstalled the k3s master from scratch and had the same issue again.
