### ISSUE TITLE
How can I stop k3s apiserver listening  {IP}:6443/static/charts directory?

### ISSUE THREAD

**Issue by xiaosaxu** [k3s-io/k3s#10391]
After deploying k3s, the security scan indicates that I have exposed the 6443/static/charts port. Does k3s have any configuration to support shutting down the listening of this address? Also, I am not using the traefik component in the charts directory.

```console
[root@linkone ~]# ls /var/lib/rancher/k3s/server/static/charts/
traefik-25.0.3+up25.0.0.tgz  traefik-crd-25.0.3+up25.0.0.tgz
[root@linkone ~]#
[root@linkone ~]# curl -k -v https://172.17.7.110:6443/static/charts/
* About to connect() to 172.17.7.110 port 6443 (#0)
*   Trying 172.17.7.110...
* Connected to 172.17.7.110 (172.17.7.110) port 6443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=k3s,O=k3s
*       start date: Dec 31 16:05:13 1999 GMT
*       expire date: Jun 22 07:31:00 2025 GMT
*       common name: k3s
*       issuer: CN=k3s-server-ca@946656312
> GET /static/charts/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.17.7.110:6443
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Last-Modified: Sat, 22 Jun 2024 08:51:04 GMT
< Date: Sat, 22 Jun 2024 09:19:47 GMT
< Content-Length: 161
<
<pre>
<a href="traefik-25.0.3+up25.0.0.tgz">traefik-25.0.3+up25.0.0.tgz</a>
<a href="traefik-crd-25.0.3+up25.0.0.tgz">traefik-crd-25.0.3+up25.0.0.tgz</a>
</pre>
* Connection #0 to host 172.17.7.110 left intact
[root@linkone ~]#
```

**Comment by brandond** [comment]
There is not currently any option to disable this functionality. Is it causing some problem? 

fwiw this is covered in the docs: https://docs.k3s.io/helm
> Content placed in /var/lib/rancher/k3s/server/static/ can be accessed anonymously via the Kubernetes APIServer from within the cluster. This URL can be templated using the special variable `%{KUBERNETES_API}%` in the spec.chart field. For example, the packaged Traefik component loads its chart from `https://%{KUBERNETES_API}%/static/charts/traefik-12.0.000.tgz`.

**Comment by xiaosaxu** [comment]
Thank you for your reply.The security scanning software has detected a security vulnerability on the node where I installed k3s, so I'm asking if there are any related configurations that can disable the listening of this path.
