### ISSUE TITLE
I can't curl through http proxy, but why?

### ISSUE THREAD

**Issue by andyzheung** [k3s-io/k3s#1040]
I want to use kubectl proxy to visit k8s api:

kubectl proxy --port=8080 &
![image](https://user-images.githubusercontent.com/22912347/68560326-98d7f600-047b-11ea-81d0-a563b4c85d11.png)

but I can't access it by:
![image](https://user-images.githubusercontent.com/22912347/68560362-be64ff80-047b-11ea-8bbd-445ada6f7f00.png)

**Comment by cjellick** [comment]
I can't reproduce
```
$ ps -ef | grep proxy
...
  501 38175 38138   0 10:55AM ttys008    0:00.11 kubectl proxy --port=8080
```

```
$ curl http://localhost:8080/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "172.18.0.2:6443"
    }
  ]
}
```
Any more useful details you can share about reproducing?
