### ISSUE TITLE
Validate RHEL/Rocky/Oracle 9.4

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#10413]
**K3s Versions to be Validated**

v1.30.2+k3s1
v1.29.6+k3s1
v1.28.11+k3s1
v1.27.15+k3s1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

```yaml
# /etc/rancher/rke2/config.yaml
selinux: true
```

**Comment by rancher-max** [comment]
RHEL validations completed.

**Comment by ShylajaDevadiga** [comment]
Rocky 9.4 validations completed.

**Comment by VestigeJ** [comment]
Oralce 9.4 validations completed for k3s but an issue remains for RKE2

**Comment by ShylajaDevadiga** [comment]
Closing as completed https://github.com/rancher/rke2/issues/6264
