### ISSUE TITLE
Impossible to start in server mode

### ISSUE THREAD

**Issue by arthur25000** [k3s-io/k3s#10449]
**Environmental Info:**
K3s Version: 3s version v1.29.6+k3s1

Node(s) CPU architecture, OS, and Version: Linux MCSWKS01345 6.5.0-1025-oem #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 12:35:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: single node server

**Describe the bug:**

When installing k3s, it's impossible to make it start in server mode, it only starts as agent.The same command with foring version v1.29.5+k3s1 works as expected.

**Steps To Reproduce:**

- Installed K3s: 
Tried with 
`curl -sfL https://get.k3s.io | sh -s - --node-ip=172.17.0.1 --resolv-conf /etc/resolv.conf --cluster-domain=cluster.priv --write-kubeconfig-mode=644`
and 
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --node-ip=172.17.0.1 --resolv-conf /etc/resolv.conf --cluster-domain=cluster.priv --write-kubeconfig-mode=644`

But after installing, the process show "k3s agent"

When forcing the version to v1.29.5+k3s1 with the command 
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.29.5+k3s1" sh -s - --node-ip=172.17.0.1 --resolv-conf /etc/resolv.conf --cluster-domain=cluster.priv --write-kubeconfig-mode=644`

it starts in server mode as expected

**Expected behavior:**

k3s should start in server mode

**Actual behavior:**

k3s starts in agent mode

**Additional context / logs:**

**Comment by brandond** [comment]
Are you sure you don't have `K3S_URL` exported in your environment? If you have that set, the script assumes you want an agent - since you're providing the address of an existing server.

 Both of your examples give me servers:
 ```console
root@systemd-node-1:/# curl -sfL https://get.k3s.io | sh -s - --node-ip=172.17.0.1 --resolv-conf /etc/resolv.conf --cluster-domain=cluster.priv --write-kubeconfig-mode=644
[INFO]  Finding release for channel stable
[INFO]  Using v1.29.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
```
 
```console
root@systemd-node-1:/# curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --node-ip=172.17.0.1 --resolv-conf /etc/resolv.conf --cluster-domain=cluster.priv --write-kubeconfig-mode=644
[INFO]  Finding release for channel stable
[INFO]  Using v1.29.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
```

**Comment by arthur25000** [comment]
Hi @brandond 

Yes, it was a new machine and I'm sure the environment variable K3S_URL wasn't set. Did you check the process ? Because I had the same installer output but when I checked the process I could see "k3s agent" rather than "k3s server"

**Comment by brandond** [comment]
Please show the full output from your install script, as well as the contents of the resulting systemd unit.
