### ISSUE TITLE
How to increase NODE podCIDR than `10.42.0.0/24`

### ISSUE THREAD

**Issue by forcemeter** [k3s-io/k3s#10442]
i have one metal server with 80 Cores, 256G memory and without VM, run k3s version `v1.29.6+k3s1`

`kubectl get nodes -ojsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.podCIDR}{'\n'}{end}"`

as default the node podCIDR is `10.42.0.0/24`, the Pods size limit is up to 256.

I want to run more pods like 512 per server, and i tried args `--kube-controller-manager-arg=node-cidr-mask-size=22` and `--kube-controller-manager-arg=node-cidr-mask-size-ipv4=22` but no expected result.

Can k3s support this feature, or any other solution can meets this feature?

**Comment by brandond** [comment]
You can't change the cidr mask after the fact, as it is assigned when the node joins the cluster. You can try deleting and rejoining the node after setting that, or just build a new cluster with that set correctly from the start.
