### ISSUE TITLE
Not able to connect to kubelet when using bind-address flag

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#10444]
**Environmental Info:**
K3s Version: 

Any

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

When deploying k3s using bind-address flag in the nodes, kubelet starts listening to $bind-address:$port, where normally port=10250. When executing `kubectl exec ...` or `kubectl logs ...`, kube-api contacts the supervisor and the HTTP CONNECT request is forwarded to the agent's kubelet via the websocket tunnel.

The problem is that the supervisor is always using the [loopback address](https://github.com/k3s-io/k3s/blob/master/pkg/daemons/control/tunnel.go#L228-L230), which means it is expecting kubelet process to listen to 127.0.0.1:$port (or [::1]:$port). However, when bind-address flag is used, that's not the case anymore. As a consequence, we get a `connection refused` error.

Kubectl output:
```
Error from server: Get "https://10.10.10.100:10250/containerLogs/kube-system/cilium-b4v6m/cilium-agent": proxy error from 10.10.10.100:9345 while dialing 10.10.10.100:10250, code 502: 502 Bad Gateway
```
journalctl output:
```
Jul 02 09:08:57 server-0 rke2[15069]: time="2024-07-02T09:08:57Z" level=error msg="Sending HTTP 502 response to 10.10.10.100:35608: dial tcp 127.0.0.1:10250: connect: connection refused"
```

**Steps To Reproduce:**

- Installed K3s:

1 - Deploy k3s with bind-address flag
2 - Check `sudo ss -lpn 'sport = :10250'` and see that `10250` port is bound to a specific IP address
3 - Deploy a pod and try to `kubectl logs ...` or `kubectl exec ...`. You'll get the above error

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
If we can get https://github.com/rancher/remotedialer/pull/80 merged, we could shim in a custom Dialer that grabs the request to dial `localhost:10250` (or whatever the kubelet port is), and replaces it with the configured bind address. The server knows the kubelet port from checking the Node object, but there is unfortunately no way for the server to know what address the kubelet's listener is bound to so we always dial it via loopback - but the agent DOES know and can make sure it ends up connected to the right place.

**Comment by manuelbuil** [comment]
Thanks Brad! I tested it this morning and `kubectl exec ...` and `kubectl logs...` works with a harmless "Error on socket receive" which we could investigate further. There is one thing though, the connection kube-api ==> metrics-server fails:
```
k3s[15348]: E0703 10:39:49.017827   15348 available_controller.go:460] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.42.1.2:10250/apis/metrics.k8s.io/v1beta1: bad status from https://10.42.1.2:10250/apis/metrics.k8s.io/v1beta1: 404
```
Probably it is using the supervisor via the egressSelector too and hence the localDialer address I set instead of `10.42.1.2:10250`. Tricky

**Comment by brandond** [comment]
yes, you'd need to be sure to redirect the dialer connection only if the connection is to localhost:kubeletport; everything else should be allowed through as-is

**Comment by brandond** [comment]
The underlying behavior change here comes from https://github.com/k3s-io/k3s/pull/10019 which now passes the bind-address flag through to the kubelet's `address` flag:
https://github.com/k3s-io/k3s/blob/4204248bc337e87fe94cf93b06f22495f6c7f2b8/pkg/agent/config/config.go#L612-L620


Previously the bind-address was not passed through to the kubelet, but instead set to a wildcard address appropriate for the node-ip's address family:
https://github.com/k3s-io/k3s/blob/f24ba9d3a9d7965fee4e9a9c44541356c14dc6a1/pkg/agent/config/config.go#L596-L601
https://github.com/k3s-io/k3s/blob/f24ba9d3a9d7965fee4e9a9c44541356c14dc6a1/pkg/util/net.go#L208-L222

**Comment by mdartmann** [comment]
Hi everyone, thank you for your great work on this project! 

Would it be possible to get an ETA for fixing this? Missing logs cause various things to break, such as log stashing with Grafana Alloy and GitLab CI.

**Comment by mdartmann** [comment]
Thank you so much for the update, @brandond !

**Comment by aganesh-suse** [comment]
Refer https://github.com/k3s-io/k3s/issues/10476


 
### Validated on master branch with commit 37830fe170fa994caea8fe337ee30173f82acbe7
 
## Environment Details

 
*Infrastructure*
- [x] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
 
*Cluster Configuration:*

```
HA: 3 server/ 1 agent
```
 
*Config.yaml:*

```
token: xxxx
cluster-init: true
bind-address: 172.31.22.180
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
node-label:
- k3s-upgrade=server
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
```
curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT='37830fe170fa994caea8fe337ee30173f82acbe7' sh -s - server
```
3. Verify Cluster Status: 
```
kubectl get nodes -o wide
kubectl get pods -A
```
4. Verify we can perform 'kubectl logs' and 'kubectl exec actions'
 
 
**Validation Results:**
- k3s version used for validation:

```
$ k3s -v 
k3s version v1.30.2+k3s-37830fe1 (37830fe1)
go version go1.22.4
```
 

```
$ sudo ss -lpn 'sport = :10250' 
Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:PortProcess
tcp   LISTEN 0      4096   172.31.22.180:10250      0.0.0.0:*    users:(("k3s-server",pid=18326,fd=178))
```
```
$ sudo /usr/local/bin/kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml logs pod/metrics-server-557ff575fb-8rh6v -n kube-system | grep 'v1beta1.metrics.k8s.io failed' 
```
```
$ sudo /usr/local/bin/kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml exec --namespace=kube-system local-path-provisioner-6795b5f9d8-95675 -- sh -c 'ls' 
bin
dev
etc
home
lib
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```

**Comment by yorkfly** [comment]
k3s_get_log.sh

**Comment by yajo** [comment]
I was having the same symptoms but not the same cause (I was not using `bind-address` nor nothing similar).

Finally I found out that the pod was faulty somehow. Other pods yielded logs; this one didn't. I re-deployed the pod and the problem went away.

I hope it helps the next one. It would have saved me a few hours.

Edit: today after some redeploys, it was failing again. Forget what I said.
