### ISSUE TITLE
ETCD Restoration issue in rke2 v1.28.8+rke2r1

### ISSUE THREAD

**Issue by shindebshekhar** [k3s-io/k3s#10459]
Hello, 
We are trying to restore snapshot on existing cluster nodes but we are facing error while restoring snapshot. 

### Below are the details -
**Cluster** - 3Master 3worker nodes
**rke2 version** - v1.28.8+rke2r1
**Config file details -**
```
write-kubeconfig-mode: "0644"
token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
server: https://abcapi.net:9345
tls-san:
- "abcapi.net"
cni: "calico"
profile: "cis-1.23"
cluster-cidr: 192.168.128.0/17
service-cidr: 192.168.64.0/18
node-taint:
- "node-role.kubernetes.io/control-plane=true:NoSchedule"
```
**Snapshot name** - pre-upgrade-snapshot--HOSTNAME-1720438816
**Command to reset the cluster and ERROR logs-**
`rke2 server --cluster-reset --cluster-reset-restore-path=pre-upgrade-snapshot--HOSTNAME-1720438816`
WARN[0000] cis-1.23 profile is deprecated and will be removed in v1.29. Please us e cis instead.
INFO[0000] Static pod cleanup in progress
INFO[0000] Logging temporary containerd to /var/lib/rancher/rke2/agent/containerd /containerd.log
INFO[0000] Running temporary containerd /var/lib/rancher/rke2/bin/containerd -c / var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/cont ainerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/contai nerd
INFO[0010] Removing pod kube-controller-manager-hostname
INFO[0010] Removing pod kube-scheduler-hostname
INFO[0020] Static pod cleanup completed successfully
WARN[0020] cis-1.23 profile is deprecated and will be removed in v1.29. Please use cis instead.
**FATA[0020] cannot perform cluster-reset while server URL is set - remove server from configuration before resetting**

**Comment by brandond** [comment]
> `server: https://abcapi.net:9345`
>
> `FATA[0020] cannot perform cluster-reset while server URL is set - remove server from configuration before resetting`

Have you tried following the instructions in the error message?
