### ISSUE TITLE
K3s etcd snapshot reconcile consumes excessive memory when a large number of snapshots are present

### ISSUE THREAD

**Issue by purha** [k3s-io/k3s#10450]
**Environmental Info:**
K3s Version: v1.28.10+k3s1 (a4c5612e)
go version go1.21.9

but also affects some earlier versions.

Node(s) CPU architecture, OS, and Version:  Linux kubernetes-worker-f-1 6.1.0-22-arm64 #1 SMP Debian 6.1.94-1 (2024-06-21) aarch64 GNU/Linux

Issue exists also atleast on ubuntu 22.04 arm64.

Cluster Configuration: 3 servers with all roles in all of them

**Describe the bug:**

In case when there's lots of snapshots in s3, at some point k3s will consume all memory available, and then oom killer will kick in.
Normally snapshots get cleaned, but because of bug https://github.com/k3s-io/k3s/issues/10292 they dont.
This will only affect single node in cluster.

**Steps To Reproduce:**

- Installed K3s: enabled snapshots to S3 (AWS) as snapshots gets piled up the memory will run out faster and faster.

**Expected behavior:**

Memory should not run out.

**Actual behavior:**

Memory runs out on node, causing oom killer to start killing processes, restarting k3s service will fix the issue for some time until memory runs out again.

**Additional context / logs:**

Memory consumption example graph attached.
<img width="1141" alt="Screenshot 2024-07-04 at 20 08 10" src="https://github.com/k3s-io/k3s/assets/814124/dbbb0ffc-3d9a-4b5b-a2b0-b9cc0a914f34">

**Comment by brandond** [comment]
> In case when there's lots of snapshots in s3, at some point k3s will consume all memory available, and then oom killer will kick in.

Is there actually a cumulative memory leak, or is the memory required to manage the snapshots directly proportional to the number of snapshots found on disk and in S3?

If there is a cumulative memory leak, this should show up as increasing memory usage over time despite a static number of etcd snapshots.

**Comment by purha** [comment]
> > In case when there's lots of snapshots in s3, at some point k3s will consume all memory available, and then oom killer will kick in.
> 
> Is there actually a cumulative memory leak, or is the memory required to manage the snapshots directly proportional to the number of snapshots found on disk and in S3?
> 
> If there is a cumulative memory leak, this should show up as increasing memory usage over time despite a static number of etcd snapshots.

Seems like cumulative, amount of snapshots contribute to the time that it takes the memory to run out. By disabling S3 snapshots the issue is gone and the memory usage is stable.

**Comment by brandond** [comment]
What are the units on your graph? Can you show the actual memory utilization of the k3s process in bytes? How many snapshots did you have in the cluster when you saw the memory utilization growing?

I'm trying to reproduce this by profiling k3s with s3 enabled, retention set to 120, and snapshots taken 1 per minute, but I'm not quite sure that I'm seeing the exact same thing as you.

**Comment by brandond** [comment]
I am also curious if you've tried adding a memory limit to the k3s systemd unit. By default the k3s systemd unit does not have a memory limit on it, and without any external memory pressure, golang will not free memory back to the operating system. So you could just be seeing secondary effects of k3s requiring more memory to reconcile a large number of snapshots, and golang not freeing memory until it absolutely needs to.

**Comment by brandond** [comment]
Just to share what I'm seeing: I do see k3s allocating a lot of memory while reconciling snapshots, but this memory is freed at the end of each snapshot save cycle. Note that the memory is allocated but no longer in use, which means that it is available to be recovered by golang garbage collection. This is NOT a leak.

`alloc_space`
<img width="1306" alt="image" src="https://github.com/k3s-io/k3s/assets/370103/5bfb28a4-6b14-41c2-be19-9ca4e781b78b">


`inuse_space`
<img width="1306" alt="image" src="https://github.com/k3s-io/k3s/assets/370103/cd8b3b3c-9e1d-4db3-9613-c4fa219f57a4">

**Comment by brandond** [comment]
Just from glancing at this, I suspect that just adding some pagination to the various list operations would take the memory utilization down a lot. The current code pulls a full list into memory on every pass, which will be expensive with hundreds of snapshots.

The profiling also makes it clear that this is NOT a leak, and is not related to minio. So I am going to edit the issue title to better reflect the root of the problem.

![image](https://github.com/k3s-io/k3s/assets/370103/56520287-7494-4c5f-add6-22d095b2dded)

**Comment by purha** [comment]
I dont have the data anymore, but I think there was around 300 snapshots or more, from 60 days or so, and few on-demand snapshots, I deleted all but the last 14 days and you can see the from the graph that it slightly helped. And you can also see when I disabled the snapshots all together. Attached also the heap profile that I took, however at that point the k3s was already consuming gigabytes of memory. I didn't try to set memory limits for the service.

![profile008](https://github.com/k3s-io/k3s/assets/814124/2a7684fc-ac7a-4627-9704-f363d8278616)

<img width="1454" alt="Screenshot 2024-07-09 at 10 05 50" src="https://github.com/k3s-io/k3s/assets/814124/9b6e76fa-0e0e-42ad-b16d-d30fde9a61d7">

**Comment by purha** [comment]
The usage is in percents and that's a node with 8Gb of memory

**Comment by aganesh-suse** [comment]
Closing based on release-1.30 results here: https://github.com/k3s-io/k3s/issues/10559
