### ISSUE TITLE
The pod persists Terminating status and can't be operated anymore

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#10483]
**Environmental Info:**
K3s Version: 

k3s version v1.25.16+k3s4 (ddda2476)
go version go1.20.10

Node(s) CPU architecture, OS, and Version: 

Linux k3s-release-master1 5.4.211-1.el7.elrepo.x86_64 #1 SMP Wed Aug 24 08:48:49 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 servers, 5 agents

**Describe the bug:**

look this：https://github.com/istio/istio/issues/51447#issuecomment-2219299717

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

follow this issue：https://github.com/istio/istio/issues/51447

**Comment by brandond** [comment]
Kubernetes 1.25 is end of life. Please try with a more recent release of K3s, and confirm if the issue persists.
