### ISSUE TITLE
Need documentation to show how to run k3s with an external cloud-controller-manager

### ISSUE THREAD

**Issue by deitch** [k3s-io/k3s#1049]
**Version:**

```
k3s version v0.10.2 (8833bfd9)
```

**Describe the bug**

When running with a cloud-controller-manager (which one should do, since everything is out of tree), at various calls, it is expected to pass the node provider ID to the ccm as `<provider>://<id>`. 

k3s, though, passes it as `k3s://<hostname>`. This makes a CCM reject it.

**To Reproduce**

1. Deploy k3s (which is so nice and easy :-) )
1. Deploy a ccm for whatever provider you are in (I have been working on Packet's)
1. Look at the logs, see a message like: `provider name from providerID should be packet: k3s://ccm01` (replace for your provider)

**Expected behavior**

The provider ID passed should be composed of `<provider>://<id>`

**Actual behavior**

It gives `k3s://<hostname>`

**Additional context**

**Comment by galal-hussein** [comment]
By default k3s will run internal cloud provider, this will add k3s:// as provider and add node name as id, to disable this default cloud provider and run your own, you can pass --disable-cloud-controller to the server and run your own ccm.

**Comment by deitch** [comment]
Thanks. Are there docs somewhere? And do I need to do anything else to enable it, set up `—cloud-provider=external`?

**Comment by davidnuzik** [comment]
It's enabled (our own cloud provider for external ip capability) if you pass the `--node-external-ip` flag with value. e.g. `--node-external-ip=x.x.x.x` That's all you should have to do.
Docs aren't great (trying to improve that) but it's listed here as a flag and also listed in --help in cli
https://rancher.com/docs/k3s/latest/en/installation/single-server/

**Comment by davidnuzik** [comment]
If you pass `--disable-cloud-controller` then our cloud controller will be completely disabled.

**Comment by galal-hussein** [comment]
@deitch Just to clarify, --disable-cloud-controller will disable our own implementation of ccm, so if you still need to run an external ccm you need to pass cloud-provider=external to kubelet extra_args, and start the ccm as a pod in the system

**Comment by deitch** [comment]
Yup. I’ve got the starting it separately. How do I tell k3s to pass the extra commands? Is it documented?

**Comment by galal-hussein** [comment]
yeah its documented, its:
```
--kubelet-arg value                        (agent/flags) Customized flag for kubelet process
```

**Comment by deitch** [comment]
So `—disable-cloud-controller —kubelet-arg —cloud-provider=external` ?

**Comment by galal-hussein** [comment]
yup, and pass kube-arg for workers as well

**Comment by deitch** [comment]
Is there any way to put this in some bootstrap config file, so I can run the usual `k3s` installation but it will pick it up?

**Comment by deitch** [comment]
Hmm, apparently args passed to `--kubelet-arg` add on their own `--` at the beginning, so my line above:

```
k3s server --disable-cloud-controller --kubelet-arg --cloud-provider=external
```

Resulted in kubelet running as 

```
----cloud-provider=external
```

Apparently, I need to do it as:

```
k3s server --disable-cloud-controller --kubelet-arg cloud-provider=external
```

Is that documented?

**Comment by deitch** [comment]
I can confirm that this works. I think if the documents somewhere showed, "how to run k3s with your own cloud-controller-manager" (or similar), we can close this issue out. It is just a documentation issue, not a code issue.

I will rename it. :-)

**Comment by cjellick** [comment]
Turned this into a documentation issue

**Comment by alexanderkjeldaas** [comment]
> @deitch Just to clarify, --disable-cloud-controller will disable our own implementation of ccm, so if you still need to run an external ccm you need to pass cloud-provider=external to kubelet extra_args, and start the ccm as a pod in the system

This is inconsistent with the documentation PR that closed this issue.  It just mentions `--disable-cloud-controller` 

See https://github.com/k3s-io/docs/pull/98/files#diff-1a7a1207c35dc4e390f7a6ebcd2e0b5f6fa9f8ebab16c1c409179ca6d69d65ecR86

Is the documentation correct?

**Comment by medoedoff** [comment]
Greetings!

I have done everything what mentioned above, but it's not worked for me.

I have only one server and it is run with command:
```
ExecStart=/usr/bin/k3s server --disable=servicelb --disable=traefik --disable-cloud-controller --kubelet-arg="cloud-provider=external"
```

bit my providerID is not changed: `providerID: k3s://`

what am I doing wrong?

**Comment by brandond** [comment]
You cannot change the providerID once the node has been added to the cluster. Changing the providerID can only be done by deleting the node and re-joining it. This is partly why we do not support changing the cloud provider on a running cluster.

**Comment by medoedoff** [comment]
Thanks for your reply, tell me please, how to do it _Changing the providerID can only be done by deleting the node and re-joining it_ ? I have only one node:
```
➜  ~ kubectl get nodes
NAME            STATUS   ROLES                        AGE    VERSION
kub-00          Ready    control-plane,master   23d    v1.27.4+k3s1
```
I added this flags `--disable-cloud-controller --kubelet-arg="cloud-provider=external"` and restarted the k3s server, it is not helped.

**Comment by brandond** [comment]
Delete the node with kubectl, then restart k3s?
