### ISSUE TITLE
k3s fails to start on netbooted devices

### ISSUE THREAD

**Issue by NCLI** [k3s-io/k3s#10512]
**Environmental Info:**
K3s Version: 
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11

Node(s) CPU architecture, OS, and Version: 
NA

Cluster Configuration:
NA

**Describe the bug:**
When installing k3s from scratch on a device with a root directory mounted using NFS, k3s will fail to start. This is the relevant part of the log:

> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: upper fs does not support tmpfile.
> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: upper fs does not support RENAME_WHITEOUT.
> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: failed to set xattr on upper
> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: ...falling back to redirect_dir=nofollow.
> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: ...falling back to uuid=null.
> Jul 13 13:51:25 rpi5-0 kernel: overlayfs: upper fs missing required features.

**Steps To Reproduce:**
Mount and NFS drive as root.
Install K3s using `curl -sfL https://get.k3s.io | sh -

**Expected behavior:**
k3s starting normally.

**Actual behavior:**
k3s does not start.

**Additional context / logs:**

**Comment by brandond** [comment]
As the message indicates, overlayfs does not work on top of NFS.
