### ISSUE TITLE
Containerd not installed by startup script - invalid capacity 0 on image filesystem warning when starting k3s node

### ISSUE THREAD

**Issue by runxc1** [k3s-io/k3s#10535]
I'm not sure if this is a bug or something that simply needs to be documented on the setup page.   I was adding an additional k3 agent to a cluster on a new Ubuntu 24 VM that I had just spun up using the script below.

curl -sfL https://get.k3s.io | K3S_URL=https://my.stuff.io:6443  sh -s - agent --token 1234  --vpn-auth="name=tailscale,joinKey=1234"

It joined the cluster but I couldn't deploy anything to it and saw the following error message

"invalid capacity 0 on image filesystem warning when starting k3s node"

I'd seen elsewhere a recommendation to restart containerd but when I ran the command to re-start it I received the error.

"Failed to restart containerd.service: Unit containerd.service not found."

After installing docker and restarting everything worked as expected. 

**Environmental Info:**
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11

Node(s) CPU architecture, OS, and Version: 
Ubuntu 24

**Comment by brandond** [comment]
> "invalid capacity 0 on image filesystem warning when starting k3s node"

This isn't an error. The kubelet logs this message every time it starts up. Ref: https://github.com/k3s-io/k3s/issues/1857

> "Failed to restart containerd.service: Unit containerd.service not found."
> After installing docker and restarting everything worked as expected.

K3s doesn't install containerd as a separate service, it is built into k3s.
K3s also doesn't use docker, so that's not doing anything for you;  I'd recommend uninstalling it.

Probably just restarting k3s was the only thing that made any difference.

**Comment by runxc1** [comment]
I installed on two separate servers and both gave the issue which made me think it wasn't a one off issue.   I also restarted both of them and waited and the issue was not resolved.   Perhaps there was a dependency that was installed at the same time that docker.io was installed?

**Comment by brandond** [comment]
You shouldn't have either docker or containerd installed and running alongside k3s. Can you share logs?
