### ISSUE TITLE
SyncLoadBalancerFailed when using a very long (yet valid) service name

### ISSUE THREAD

**Issue by dprunier** [k3s-io/k3s#10537]
**Environmental Info:**
K3s Version:

```
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11
```

Node(s) CPU architecture, OS, and Version: 

```
Linux localhost.localdomain 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Tue Aug 10 10:49:54 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

Straight installation with `curl -sfL https://get.k3s.io | sh -`, no configuration whatsoever

**Describe the bug:**

Because of the way the klipper-lb daemon set name is generated, if the service name is already flirting with the 63 character limit, it may be invalid as a label. When this happens, the deamon set doesn't get created and the service reports an event:
```
  Warning  SyncLoadBalancerFailed  7s (x3 over 22s)  service-controller  Error syncing load balancer: failed to ensure load balancer: failed to create kube-system/svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a apps/v1, Kind=DaemonSet for  default/a-service-with-a-very-veeeeeery-long-yet-valid-name: DaemonSet.apps "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a" is invalid: [spec.selector.matchLabels: Invalid value: "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a": must be no more than 63 characters, spec.template.labels: Invalid value: "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a": must be no more than 63 characters]
```

**Steps To Reproduce:**

- Installed K3s with `curl -sfL https://get.k3s.io | sh -`, no configuration whatsoever
- Create a service with a very long, yet valid name (longer than 48 characters but less than 63), e.g.
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: a-service-with-a-very-veeeeeery-long-yet-valid-name
  spec:
    selector:
      app.kubernetes.io/name: MyApp
    ports:
      - protocol: TCP
        port: 80
    type: LoadBalancer
  ```

**Expected behavior:**

The name generation logic should take the 63 character limit into  account for the `app` label and truncate the service name such that `svclb-<svc name>-<uid[:8]>` remains under 63 characters. In my example above, instead of generating `svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-0f84b96e`, it should have generated `svclb-a-service-with-a-very-veeeeeery-long-yet-valid-n-0f84b96e`.

**Actual behavior:**

The generated name being invalid as a label, the klipper daemon set never gets created as it fails with the error:
```
  Warning  SyncLoadBalancerFailed  7s (x3 over 22s)  service-controller  Error syncing load balancer: failed to ensure load balancer: failed to create kube-system/svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a apps/v1, Kind=DaemonSet for  default/a-service-with-a-very-veeeeeery-long-yet-valid-name: DaemonSet.apps "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a" is invalid: [spec.selector.matchLabels: Invalid value: "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a": must be no more than 63 characters, spec.template.labels: Invalid value: "svclb-a-service-with-a-very-veeeeeery-long-yet-valid-name-f246494a": must be no more than 63 characters]
```

**Additional context / logs:**

**Comment by fmoral2** [comment]
validate on 

https://github.com/k3s-io/k3s/issues/10565#issuecomment-2277932056
https://github.com/k3s-io/k3s/issues/10564#issuecomment-2277935255
https://github.com/k3s-io/k3s/issues/10563#issuecomment-2277935477
https://github.com/k3s-io/k3s/issues/10566#issuecomment-2277938468
