### ISSUE TITLE
Logging of kube-scheduler 

### ISSUE THREAD

**Issue by dvasudha** [k3s-io/k3s#10533]
Can someone direct me to the steps to view the logs of default kube-scheduler in k3s ?

**Comment by brandond** [comment]
K3s runs all the Kubernetes components in the main k3s process, so their logs are all mixed together in the k3s journald log.

**Comment by dvasudha** [comment]
I tried looking for kube-scheduler using k3s journald with v=10 set for entire server configuration. However, I am not able to see any logs

**Comment by brandond** [comment]
It's all in there together. It can be hard to tell which logs are from what component, since they don't have anything uniquely identifying the source.

**Comment by dvasudha** [comment]
Are logs from k8s default scheduler by default imported to k3s component logging as well ?

**Comment by brandond** [comment]
We don't import anything. They just all run in one process, and are output to stdout/stderr same as everything else. If you're running k3s under systemd, they go in the journald log.
