### ISSUE TITLE
Allow duplication of keys in containerd config.toml.tmpl

### ISSUE THREAD

**Issue by schlichtanders** [k3s-io/k3s#10551]
**Is your feature request related to a problem? Please describe.**

Hi there, I want to enable `MountFlags=shared` for containerd in k3s and found that the option `plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options.MountFlags="shared"` inside the containerd config is probably the thing to set. Hence I tried the following

```bash
cat > /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl <<END
{{ template "base" . }}

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  MountFlags = "shared"
END
```

However, this fails with the following error
```
containerd: failed to load TOML: /var/lib/rancher/k3s/agent/etc/containerd/config.toml: (47, 2): duplicated tables
```

**Describe the solution you'd like**
As toml itself does not process duplicated keys, it would be awesome if k3s templating system could aggregate keys before-hand.

**Describe alternatives you've considered**

I only know of the alternative to copy paste the default config.toml and edit it, but this is discouraged by k3s documentation.

**Comment by brandond** [comment]
We are not going to write our own toml parsing library just to handle merging duplicate toml table keys, which is something that is disallowed by the toml spec. If you need to override something that is in the base template, then you should provide a replacement for the full base template, instead of just trying to append to it.

**Comment by schlichtanders** [comment]
Thanks and sorry for inconveniences. That would be a helpful recommendation inside the documentation. I by now realized that the actual default config is actually linked in the docs, but the point that this is the actual default and can be taken securily as baseline is not mentioned.

**Comment by brandond** [comment]
I agree it's more work, and potentially more fragile, to provide your own full template, but we don't have the cycles to maintain a library that would handle merging arbitrary toml data structures.
