### ISSUE TITLE
Bump helm and plugins in klipper-helm image

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10556]
There is a new release of helm v3 available, and some of the plugins in the klipper-helm image have deps that are showing up on scanners. We should bump them.

* Related: https://github.com/k3s-io/k3s/issues/10627
  Since the version bump got rolled in with the drop of helm v2 support, we will not be backporting this to v1.30 or earlier.

**Comment by fmoral2** [comment]
```console 
k3s version v1.30.3+k3s1 (f6466040)
 
```
``` 
$ helm version
version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}
 
```
