### ISSUE TITLE
Update docs site release notes as part of release process

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10572]
> The release notes on the docs site are never as up to date as the GH release page, or the channel server. I would not recommend using the docs site as an authoritative list of available releases.

@brandond 
If the docs aren't part of the release process I'd consider that a process deficiency, otherwise why have release note docs?  Not everyone wants to sift through fifty rcX releases in a github to find the stable tree they're on amongst the noise, especially if there's a website that identifies itself as the properly-collated release notes.  To be clear, I get what you're saying but am politely replying that it might be an improvement to ensure the release notes docs get updated when a release is cut.

Regardless, I have upgraded to k3s2 and the issue has not recurred -- thank you for setting me on the right track.

_Originally posted by @PeterGrace in https://github.com/k3s-io/k3s/issues/10557#issuecomment-2249133612_

**Comment by dereknola** [comment]
This has largely been addressed by https://github.com/k3s-io/docs/pull/310, with the Release Notes workflow running weekly.
