### ISSUE TITLE
IPv6 only Problems

### ISSUE THREAD

**Issue by RJGhugo** [k3s-io/k3s#10575]
**Environmental Info:**
`kubectl version`
`Client Version: v1.29.6+k3s2`
`Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3`
`Server Version: v1.29.6+k3s2`

Node(s) CPU architecture, OS, and Version: 
`uname -a`
`Linux XXXX 6.10.0-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000 x86_64 GNU/Linux`

Cluster Configuration:

`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --disable=servicelb --disable=traefik --disable-helm-controller --default-local-storage-path /mnt/daten --cluster-cidr=2001:cafe:42::/56 --service-cidr=2001:cafe:43::/112" sh -`

`kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.7/config/manifests/metallb-native.yaml`

`---`
`apiVersion: metallb.io/v1beta1`
`kind: IPAddressPool`
`metadata:`
`  name: ip-adressen`
`  namespace: metallb-system`
`spec:`
`  addresses:`
`  - xxxx:xxxx:xxxx:6000:900d::/112`
`---`
`apiVersion: metallb.io/v1beta1`
`kind: L2Advertisement`
`metadata:`
`  name: meine-services`
`  namespace: metallb-system`
`spec:`
`  ipAddressPools:`
`  - ip-adressen`
`---`

**Describe the bug:**

works: nginx

error: pihole/pihole
up and running, but not able to download **blocklists**

error: libretranslate/libretranslate:latest
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)

It seems, that the dns resolution inside the pods is not working.

**Steps To Reproduce:**
Start pod.
kubectl logs POD
--> errors

The IPv6 is 100% working (https://internet.nl/connection).

**Comment by brandond** [comment]
Did you need to set `--flannel-ipv6-masq`? Unless your pod IPs are routable, you probably want to do so.

https://docs.k3s.io/networking/basic-network-options#flannel-options

**Comment by RJGhugo** [comment]
Thank you!

It is working...

curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --disable servicelb --disable traefik --default-local-storage-path /mnt/daten --cluster-cidr=2001:cafe:42::/56 --service-cidr=2001:cafe:43::/112 **--flannel-ipv6-masq**" sh -
