### ISSUE TITLE
pprof statistics cannot be access when running server with `--disable-agent`

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#10582]
**Environmental Info:**
K3s Version: 

Master branch

Cluster Configuration:

1 server

**Describe the bug:**

You cannot pull pprof data if no agent is running on a server. You will see:
```
$ go tool pprof --seconds=70 -top http://localhost:8001/debug/pprof/profile 
Fetching profile over HTTP from http://localhost:8001/debug/pprof/profile?seconds=70
Please wait... (1m10s)
http://localhost:8001/debug/pprof/profile: server response: 404 Not Found
```
**Steps To Reproduce:**

- Run K3s server with `--disable-agent  --enable-pprof`
- Open kube proxy to handle credentials `kubectl proxy`
- Attempt to capture pprof profile data from proxy port `go tool pprof --seconds=70 -top http://localhost:8001/debug/pprof/profile `

**Expected behavior:**

pprof capture should complete

**Actual behavior:**

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
Closing issue as validated on backports 1.27-1.30 branches
