### ISSUE TITLE
K3s does not respect `data-dir` set via config file drop-in, or via env var

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10589]
1. The multicall wrapper script does not honor config file drop-ins for the `--data-dir` flag. The flag will be found if set in the CLI args, or in /etc/rancher/k3s/config.yaml, but not if it is set in any file in /etc/rancher/k3s/config.yaml.d (or the equivalent drop-in dir if the `--config` flag is used to change the path to config.yaml).

1. The K3S_DATA_DIR env var does not map to the --data-dir CLI flag. It probably should. The multicall wrapper sets the K3S_DATA_DIR env var when it runs wrapped commands, but it appears that this is no longer used for anything - as there are no references to it anywhere else in the code base: 
    https://github.com/k3s-io/k3s/blob/59e07610431588a35aa535de4bf909721fa7111c/cmd/k3s/main.go#L196

To reproduce:
* Install k3s with `mkdir -p /etc/rancher/k3s; echo "data-dir: /k8s" >> /etc/rancher/k3s/config.yaml; curl -sL get.k3s.io | sh -s - server`
    - note that data-dir is used
* Install k3s with `curl -sL get.k3s.io | sh -s - server --data-dir=/k8s`
    - note that data-dir is used
* Install k3s with `mkdir -p /etc/rancher/k3s/config.yaml.d; echo "data-dir: /k8s" >> /etc/rancher/k3s/config.yaml.d/99-data-dir.yaml; curl -sL get.k3s.io | sh -s - server`
    - note that data-dir is NOT used
* Install k3s with `curl -sL get.k3s.io | K3S_DATA_DIR=/k8s sh -s - server`
    - note that data-dir is NOT used

Note that for the case where `data-dir` is set in /etc/rancher/k3s/config.yaml.d/, the value is PARTIALLY respected. The stage 2 `k3s server` command honors the setting, but the binaries and packaged manifests are extracted out to the default path by the stage 1 multicall wrapper.

**Comment by ShylajaDevadiga** [comment]
Closing this issue as validated
https://github.com/k3s-io/k3s/issues/10592#issuecomment-2258907482
