### ISSUE TITLE
Expose rancher/lasso controller metrics

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10606]
Lasso has some internal metrics around controller execution counts and durations, cache sizes, and so on. We should expose these so that we can better evaluate the performance of wrangler(lasso) controllers embedded in the K3s supervisor.

Ref: https://github.com/rancher/lasso/blob/f16ff2c25dc3291877b17af086fbcad7607fb390/pkg/metrics/metrics.go#L26-L49

**Comment by endawkins** [comment]
All versions have been validated. Closing issue.
