### ISSUE TITLE
Stable version 404 error

### ISSUE THREAD

**Issue by Aias00** [k3s-io/k3s#10607]
**Environmental Info:**
K3s Version:  stable

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Run curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE=777 sh -
installing stable version, but i got this error
<img width="988" alt="image" src="https://github.com/user-attachments/assets/117ead72-11a9-4761-81f1-8085dcda122c">

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Likely duplicate of https://github.com/k3s-io/k3s/issues/10578
