### ISSUE TITLE
Setup private registry with k3s &containerd

### ISSUE THREAD

**Issue by cthumuluru** [k3s-io/k3s#10613]
I've trouble setting up my local private registry to work in k3s. Can someone take a look and let me know what I'm missing?

# /etc/rancher/k3s/registries.yaml
$ /etc/rancher/k3s $ cat registries.yaml
mirrors:
[private-registry.com](http://private-registry.com/):
endpoint:
- "http://192.168.86.25:5000/"

# k3s version
$ k3s --version
k3s version v1.27.7+k3s2 ([575bce7](https://github.com/k3s-io/k3s/commit/575bce7689f4be112bd0099362fb8d5f2e39398e))
go version go1.20.10

# Pod creation command
kubectl run crdb-pod --image [private-registry.com:5000/crdb:v24.1.2](http://private-registry.com:5000/crdb:v24.1.2)

# Error Message
Failed to pull image "[private-registry.com:5000/crdb:v24.1.2](http://private-registry.com:5000/crdb:v24.1.2)": failed to pull and unpack image "[private-registry.com:5000/crdb:v24.1.2](http://private-registry.com:5000/crdb:v24.1.2)": failed to resolve reference "[private-registry.com:5000/crdb:v24.1.2](http://private-registry.com:5000/crdb:v24.1.2)": failed to do request: Head "https://private-registry.com:5000/v2/crdb/manifests/v24.1.2": dial tcp: lookup [private-registry.com](http://private-registry.com/): no such host

# Images from private registry
$ docker images | grep private
[private-registry.com:5000/crdb](http://private-registry.com:5000/crdb) v24.1.2 c3b7cf301fe1 4 days ago 761MB

Registry is not running on the k3s node.

**Comment by brandond** [comment]
It's really hard to tell based on the formatting of the text in your post if your registries.yaml is correct. However, I do see that you're trying to pull images from `private-registry.com:5000` but you added a mirrors entry for `private-registry.com` - without the port. You need to be consistent about this if you want it to work.

**Comment by cthumuluru** [comment]
Thanks, @brandond for the quick response. I verified the 

> It's really hard to tell based on the formatting of the text in your post if your registries.yaml is correct. 

I verified the yaml to make sure it is valid. Sorry about the formatting issues in the original post. 

> However, I do see that you're trying to pull images from private-registry.com:5000 but you added a mirrors entry for private-registry.com - without the port.

I added the port to the mirror entry and tried again. Restarted `k3s-agent` on all worker nodes and `k3s` on the mater node. I still see the agent fails to pull the image with error message `Failed to pull image "private-registry.com:5000/crdb:v24.1.2": failed to pull and unpack image "private-registry.com:5000/crdb:v24.1.2": failed to resolve reference "private-registry.com:5000/crdb:v24.1.2": failed to do request: Head "https://private-registry.com:5000/v2/crdb/manifests/v24.1.2": dial tcp: lookup private-registry.com: no such host`. 

Updated yaml file for your reference:

```
mirrors:
  private-registry.com:5000:
    endpoint:
      - http://192.168.86.25:5000
```

**Comment by brandond** [comment]
Check the containerd log. The kubelet logs don't show all the logs from attempts to pull via the configured mirror endpoints. 

I also see that you are using `v1.27.7+k3s2`. That version is from last November, I would recommend upgrading ASAP.

**Comment by cthumuluru** [comment]
Containerd logs were helpful to identify the issue. From the container logs I could see the right endpoint was used to pull the image. I didn't realize my private registry was down resulting in the pull failures. Once I brought up the registry I was able to use my private registry to pull the images. Thanks @brandond for your help. Closing this thread now.
