### ISSUE TITLE
v1.30.2+k3s2: 502 bad gateway when trying to get pod logs or exec

### ISSUE THREAD

**Issue by svscorp** [k3s-io/k3s#10653]
**Environmental Info:**
K3s Version: 
k3s version v1.30.2+k3s2 (faeaf1b0)
go version go1.22.4

Node(s) CPU architecture, OS, and Version: 
Linux prd-server 5.4.0-190-generic #210-Ubuntu SMP Fri Jul 5 17:03:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 1 control node, 2 agent nodes

**Describe the bug:**
After changing binding address from default and switching to using internal network addresses, can't use logs/exec commands it results with 502 Bad Gateway error. After reading multiple threads, considered it is related to the proxy settings, that I didn't change. However, even applying NO_PROXY configuration, the issue persisted.

**Steps To Reproduce:**
- Recently upgraded from 1.22.2 to 1.30.2
- Decided to make stricter networking rules in my cluster and allow only internal communication. In particular:
1. On control node in `/etc/systemd/system/k3s.service` added to ExecStart `--bind-address 10.20.20.1 --tls-san PUBLIC_IP --kubelet-arg="address=10.20.20.1"`
... later during troubleshooting, additionally added `--kubelet-arg "node-ip=10.20.20.1"`
2. On agent nodes in `/etc/systemd/system/k3s-agent.service` added `Environment="K3S_URL=https://10.20.20.1:6443"` before ExecStart and argoments to ExecStart `--kubelet-arg "address=10.20.20.2"  --kubelet-arg="node-ip=10.20.20.2"` (and .3 for the third node)
3. Added firewall to restrict traffic to 10.20.20.0/24 for 6443 and 10250 (on control) and 10250 (on agent nodes)
Communication on this ports from different nodes checked - this is the first thing I considered when got the error.
4. Reloaded daemon and k3s (on control) and daemon + k3s-agent (on agents)

(after several attempts to troubleshoot, found a similarity to #10547, #10444 and #6123 and attempted the following)
5. Added into `/etc/systemd/system/k3s.service.env` (on control) and `/etc/systemd/system/k3s-agent.service.env` (on agent nodes):
`NO_PROXY='localhost,127.0.0.1,10.20.20.0/24'`
_Also tried to add into a non-existent before /etc/systemd/system/k3s.env_ 
6. Reloaded, Restarted. No effect.

**Expected behavior:**
Logs and exec into a pod working as it was working right before changing bind-address and making configuration stricter to inter-cluster comms only. It worked on 1.30.2

**Actual behavior:**
Trying to get logs, i.e.: *kubectl logs -l app.kubernetes.io/name=traefik -n kube-system*
`Error from server: Get "https://10.20.20.1:10250/containerLogs/kube-system/traefik-68f9c8f94b-gjpgq/traefik?tailLines=10": proxy error from 10.20.20.1:6443 while dialing 10.20.20.1:10250, code 502: 502 Bad Gateway`

Or trying to get into a pod container: *kubectl exec -n product --stdin --tty -c front front-8698f4b8fd-nfbnj -- /bin/bash
error: Internal error occurred: error sending request: Post "https://10.20.20.1:10250/exec/product/front-8698f4b8fd-nfbnj/front?command=%!F(MISSING)bin%!F(MISSING)bash&input=1&output=1&tty=1": proxy error from 10.20.20.1:6443 while dialing 10.20.20.1:10250, code 502: 502 Bad Gateway

**Additional context / logs:**
`k describe nodes` no challenges, besides these warnings.
```
Events:
  Type     Reason               Age    From     Message
  ----     ------               ----   ----     -------
  Warning  FreeDiskSpaceFailed  8m40s  kubelet  Failed to garbage collect required amount of images. Attempted to free 20502900736 bytes, but only found 66083171 bytes eligible to free.
  Warning  FreeDiskSpaceFailed  3m40s  kubelet  Failed to garbage collect required amount of images. Attempted to free 28881944576 bytes, but only found 0 bytes eligible to free.
  Warning  ImageGCFailed        3m40s  kubelet  Failed to garbage collect required amount of images. Attempted to free 28881944576 bytes, but only found 0 bytes eligible to free.
```

In journalctl, no other errors besides the one I described in the beginning.

**Comment by brandond** [comment]
> Recently upgraded from 1.22.2 to 1.30.2

You stepped through the intermediate minor versions, right? It is not supported to skip minor versions when upgrading.

> On agent nodes in /etc/systemd/system/k3s-agent.service added Environment="K3S_URL=https://10.20.20.1:6443" before ExecStart and argoments to ExecStart --kubelet-arg "address=10.20.20.2"  --kubelet-arg="node-ip=10.20.20.2" (and .3 for the third node)

Don't do that. K3s expects the kubelet to be available on the loopback address as well as the node IP. If you explicitly bind it to only the IP, communication between the apiserver and the kubelet will not function properly.

**Comment by svscorp** [comment]
Thanks for not removing the comments from the thread this time @brandond. At least I can report that I've just updated to `v1.30.3+k3s1` and confirming that the issue is resolved ;)

Great work! Thank you.

**Comment by svscorp** [comment]
> You stepped through the intermediate minor versions, right? It is not supported to skip minor versions when upgrading.

No I haven't @brandond. I did the RTFM, and updated minor by minor version, testing everything after each upgrade.

**Comment by brandond** [comment]
Use the k3s --bind-address flag instead of hardcoding it via a kubelet arg. If you poke at the kubelet args directly, k3s won't know what address the kubelet is listening on.

**Comment by svscorp** [comment]
@brandond can you please advise whether I need to open another issue or it's still relevant? What I noticed, if a pod is scheduled on another node (in this case - agent node), when I try to get logs executing it on the control node, I am getting this:

`Get "https://10.20.20.2:10250/containerLogs/myservice/myservice-8698f4b8fd-sbg28/mycontainer?follow=true&tailLines=1000&timestamps=true": net/http: TLS handshake timeout`
