### ISSUE TITLE
Inacuracy in documentation?

### ISSUE THREAD

**Issue by edthrn** [k3s-io/k3s#10696]
I just created a cluster using this command:

```bash
curl -sfL https://get.k3s.io | sh -s - \
  --node-ip 10.35.1.10 \
  --flannel-iface ens6 \
  --advertise-address <redacted: my public IP> \
  --tls-san <redacted: my public IP>
```
**It works good.**

However, the docs states that the `--advertise-address` must be of the same address family as the main service CIDR.

![image](https://github.com/user-attachments/assets/9645aee2-9a8d-4c8e-a043-ff9acae5ced4)

I wonder if there this documentation is misleading... 

Since the services communicate using the Flannel interface (and since I explicitly asked Flannel to use the network interface that uses the private ip `10.35.1.10`) it seems OK to declare a public IP address for "advertising".

---

Please, don't hesitate to close this issue if irrelevant: I don't have any problem with my configuration.

**Comment by brandond** [comment]
Address family means ipv4 or ipv6. It doesn't mean public or private.

https://en.wikipedia.org/wiki/Address_family_identifier
