### ISSUE TITLE
Allow users to use letsencript certificates when they install k3s

### ISSUE THREAD

**Issue by joaquinCaceres** [k3s-io/k3s#10711]
Hi everyone!

I'm trying to install k3s using my own let's Encrypt certificates, but I cannot find any documentation. What I want is to be able to connect to the k3s cluster through kubectl using valid certificates. In addition, I want to automate the process of renewing these certificates, in the same way as it is done in the data plane. Has anyone achieved something similar? It would be interesting to document the process to stop using certificates auto-generated by k3s. 

In this link we can find information about this problem, but I would like that the certificates could be generated once the k3s is up through cert-manager or something like that. 

Thanks in advance!

**Comment by brandond** [comment]
> What I want is to be able to connect to the k3s cluster through kubectl using valid certificates.

Kubernetes clusters usually use their own CA, as there are a large number of components that need their own client and/or server certificates. You can't get a CA certificate or client certs from LetsEncrypt, so using LE as your cluster CA is not going to be possible.

I would recommend that you take a look at the custom CA docs: https://docs.k3s.io/cli/certificate#using-custom-ca-certificates

**Comment by joaquinCaceres** [comment]
hi @brandond!

I understand everything you say, the problem is that in my organisation, for security reasons, it is not possible to expose certificates that are not valid for browsers. I have followed the steps in the link you mention, generating my own certificates with openssl, but these are not valid either. When I connect to the cluster via https, the browser does not recognise the certificate as valid and throws an error. Is there any way to cancel the exposure of these certificates so that the cluster can only be accessed via http? Is there another way to generate secure certificates?

I have achieved all this at the application level, exposing let's encrypt certificates through ingress.

**Comment by brandond** [comment]
> in my organisation, for security reasons, it is not possible to expose certificates that are not valid for browsers. 

This is not how Kubernetes is designed. You're not supposed to connect to any of these things with browsers. They are for internal communication between Kubernetes components. The only thing that you might access with a browser is the ingress, and for that you can provide your owns cert as part of the Ingress resource.

If your organization has its own PKI, you can follow the docs to sign the cluster CAs with your internal root or intermediate CA. You are not going to be able to manually issue all of the various leaf (client and server) certificates ahead of time.

**Comment by joaquinCaceres** [comment]
Thank @brandond  for the quick response! 

The thing is that when you start k3s you can access the cluster through the browser, both via http (port 80) and https (port 443). I guess this is because an Ingress is deployed by default when installing k3s. It is just these certificates that I want to stop using, as they are self-signed. Can the solution be to deploy k3s without the traefik service? 

Subsequently, I would configure my own Ingress (nginx or traefik) with cert-manager to serve the let's encripts certificates, which would allow access to my cluster applications through the browser.

**Comment by brandond** [comment]
The ingress certs have nothing to do with the cluster certs. Traefik comes with a self-signed default cert that is not even signed by the cluster CA. 

If all you're concerned about is the ingress on 443, you could do many things:
* Disable traefik
* Replace the self-signed traefik default certificate with a valid certificate.
* Deploy ingress resources that use a valid certificate.
