### ISSUE TITLE
[k3s-upgrade] MODIFIED_VERSION is undefined

### ISSUE THREAD

**Issue by janpieper** [k3s-io/k3s#10750]
I cannot create an issue in https://github.com/k3s-io/k3s-upgrade, so I try it here :wink:

---

The commit https://github.com/k3s-io/k3s-upgrade/commit/243b18c3c0f6f36668d989790a59e5d5e388621f (~4 years old) has introduced a variable called `MODIFIED_VERSION` which is undefined, so the script only outputs

```
[INFO] Waiting for all master nodes to be upgraded to version
```

instead of e.g.

```
[INFO] Waiting for all master nodes to be upgraded to version v1.29.8+k3s1
```

This variable is still used in the latest version: [scripts/upgrade.sh @ k3s-upgrade](https://github.com/k3s-io/k3s-upgrade/blob/dffa07e13006bad9527e8ba603eb44febdcb1d45/scripts/upgrade.sh#L169), but it is still undefined :wink:

**Comment by brandond** [comment]
Yeah, that var was mostly nixed in code review on that PR, but it appears that one use of it was left in.

**Comment by brandond** [comment]
thanks for the report! Should be fixed for next month's releases.

**Comment by endawkins** [comment]
### Validated on master with 452dbbc / v1.31
  
## Environment Details

  
*Infrastructure*
- [X] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-0-190 6.8.0-1012-aws #13-Ubuntu SMP Mon Jul 15 15:42:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
  
*Cluster Configuration:*

```
HA
```
  
*Config.yaml:*

```
N/A
```
  
*Additional files*

```
N/A
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install K3s
3. Run SUC
4. Pull pod logs of agent-apply

**Validation Results:**
- k3s version used for validation:

```
k3s -v
k3s version v1.31.1-rc2+k3s1 (452dbbc1)
go version go1.22.6
```
 

```
[INFO]  Waiting for all control-plane nodes to be upgraded to version v1.31.1-rc2-k3s1
```
 
**Additional context / logs:**
```
N/A
```
