### ISSUE TITLE
K3s uses socket file path instead of localhost as the authorization header for UDS communication

### ISSUE THREAD

**Issue by Ruddickmg** [k3s-io/k3s#10754]
**Environmental Info:**
K3s Version: v1.30.4+k3s1

Cluster Configuration:
1 server

**Describe the bug:**
[Identical to this issue](https://github.com/k3s-io/k3s/issues/5346), however it appears that the solution was not applied to the socket communication required for [encryption at rest](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#implementing-a-kms-plugin).

**Steps To Reproduce:**

Set up grpc server [using this proto](https://github.com/kubernetes/kms/blob/release-1.31/apis/v1beta1/api.proto) that communicates via UDS (Unix domain socket) as instructed in the documentation, [docs here](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#implementing-a-kms-plugin), and run it. All communication will be rejected because of invalid headers being sent by k3s to the kms provider. The current (invalid) authority header is the path to the UDS socket file `/path/to/socket.sock`. The previous solution to this problem was apparently replacing the invalid authority header with `localhost` when a UDS socket connection was used.

**Expected behavior:**
a valid authority header is sent by k3s during UDS communication

**Actual behavior:**
an invalid authority header (the file path to the socket file) is being sent instead and preventing communication.

**Additional context / logs:**
K3s logs of failed communication

> Aug 26 05:08:23 ip-10-0-38-111 k3s[3233]: E0826 12:08:23.997856    3233 controller.go:179] error processing encryption config file /tmp/encryption/configuration.yaml: health check for new transformers failed, polling error timed out waiting for the condition: kms-provider-0: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

App logs of failed communication

```
{
  "timestamp": "2024-08-26T12:08:13.996957Z",
  "level": "DEBUG",
  "fields": {
    "message": "malformed headers: malformed authority (b\"%2Fmnt%2Fkms-provider.sock\"): invalid authority"
  },
  "target": "h2::server",
  "span": {
    "peer": "Server",
    "name": "Connection"
  },
  "spans": [
    {
      "peer": "Server",
      "name": "Connection"
    }
  ]
}
```

**Comment by brandond** [comment]
This is a core Kubernetes feature. The code in question does not live here in K3s.

See https://github.com/kubernetes/kubernetes/issues/109081 where the CSI issue you linked was fixed upstream.
