### ISSUE TITLE
k3s certs we generate should include hostname in the SAN by default

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1076]
**Version:**
v1.0.0-rc3

**Describe the enhancement**
Today, if I want to utilize a hostname as my server url for joining worker nodes, it's not in the SAN for certs. I think we should make this default so I don't have to utilize the `--tls-san` flag in this case.

It would be nice if we could include the FQDN too but we've found that getting thus such as via `hostname -f` is not reliable.

**Comment by brandond** [comment]
Pretty sure we've been doing this for a while now.
