### ISSUE TITLE
servicelb daemonset resurrects after a node restarted even if it is manually disabled and removed.

### ISSUE THREAD

**Issue by genki** [k3s-io/k3s#10793]
**Environmental Info:**
K3s Version: 

```
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11
```

Node(s) CPU architecture, OS, and Version: 

```
Linux leader-prod.us-west1-c.c.s21g-twpro.internal 6.8.0-1013-gcp #14-Ubuntu SMP Thu Aug  8 23:18:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

3 servers.

**Describe the bug:**

I have been running a k3s cluster with 3 server nodes that is installed using the `https://get.k3s.io` with default options.
After the installation, I deleted the servicelb daemonset and make the traefik being in charge for there.
I have changed `/etc/systemd/system/k3s.service` file to have an option `--disable=servicelb` and changed `/var/lib/rancher/k3s/server/manifests/traefik.yaml` at every nodes to be acting as daemonsets. 
But once a node rebooted, the configuration of the cluster is getting back to the state with the servicelb.
Looking into the `/etc/systemd/system/k3s.service`, it is lost its change I wrote.
Is it impossible to remove the servicelb after the installation?
Further investigation, I have found a file that may memory the initialization option in it, that is `/var/lib/rancher/k3s/server/etc/cloud-config.yaml`.

```
{"lbDefaultPriorityClassName":"system-node-critical","lbEnabled":true,"lbImage":"rancher/klipper-lb:v0.4.7","lbNamespace":"kube-system","nodeEnabled":true,"rootless":false}
```
Though this is not documented, I have to change the value `lbEnabled` from `true` to `false`?

**Steps To Reproduce:**

- Installed K3s: 
- remove the servicelb daemonset
- make the traefik to be a daemonset by changing the `/var/lib/rancher/k3s/server/manifests/traefik.yaml`
- added `--disable=servicelb` to the startup option at `/etc/systemd/system/k3s.service`
- `systemctl daemon-reload`
- reboot one of the node.

**Expected behavior:**

The traefik stay being daemonset and there's no servicelb after the reboot.

**Actual behavior:**

The servicelb daemonset resurrects and configuration of the cluster is getting back to the initial state with abandon of my changes.

**Additional context / logs:**

**Comment by brandond** [comment]
>  have changed /etc/systemd/system/k3s.service file to have an option --disable=servicelb and changed /var/lib/rancher/k3s/server/manifests/traefik.yaml at every nodes to be acting as daemonsets.

Don't edit those files. See https://docs.k3s.io/helm#customizing-packaged-components-with-helmchartconfig for information on how to modify the Traefik chart configuration.
