### ISSUE TITLE
Questions about using pprof to obtain information related to k3s

### ISSUE THREAD

**Issue by YYM0093** [k3s-io/k3s#10827]
**Is your feature request related to a problem? Please describe.**

I am exploring the performance of the k3s cluster, and I use the pprof tool for data collection. My work steps are as follows:

Start the proxy:

`kubectl proxy --address='0.0.0.0' --accept-hosts='^*$'`

Obtain performance metrics (I used the following two commands and got almost identical results):

`go tool pprof http://127.0.0.1:8001/debug/pprof/heap`

`go tool pprof http://127.0.0.1:8001/api/v1/nodes/${NODENAME}/proxy/debug/pprof/heap`

![image](https://github.com/user-attachments/assets/1dd27a7a-0448-43d7-9b21-292818b2cb88)

![image](https://github.com/user-attachments/assets/894835e6-d5df-4367-afdf-1675731d0126)

**Describe the solution you'd like**

I use the top command to obtain the memory usage of the entire k3s cluster, and I want to further analyze the memory usage of the internal components of k3s.
![image](https://github.com/user-attachments/assets/d70ddd84-6e17-420c-aff3-fa9de0d3a46b)

I would like to know the answers to the following questions:

1. Why do I get similar memory usage information through two different methods? If I want to analyze the performance of kubelet specifically, what is the correct approach?
2. If possible, could you please tell me the correct method to obtain pprof data for each component in k3s?
3. The above data was obtained on the server node; how can I obtain data on the agent nodes

**Describe alternatives you've considered**

**Additional context**

k3s version:
`k3s version 1.28.2+k3s1`
go version 
`go1.21.9`

Node(s) CPU architecture, OS, and Version:
`Linux 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by brandond** [comment]
You can't get info for separate components, because k3s runs all the components - including the kubelet - in a single process. This is the entire value proposition of k3s and is covered in the docs.

**Comment by YYM0093** [comment]
> You can't get individual info for separate components, because k3s runs all the Kubernetes components - including the kubelet - in a single process. This is the entire value proposition of k3s and is covered in the docs.
> 
> You can get it from agent in the same way you do on the server - by enabling pprof on the command line and hitting the pprof debug endpoint on the supervisor port.

Thank you very much for your reply. I understand that I cannot directly obtain the pprof data for each component, but theoretically, the pprof data I obtained in the manner described should reflect the overall memory usage of k3s. However, the actual values are significantly lower than those reported by the 'top' command. Could you please explain what the data I access at /debug/pprof represents?

**Comment by brandond** [comment]
The standard golang profiling data: https://pkg.go.dev/net/http/pprof
