### ISSUE TITLE
Validate Amazon Linux 2

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#10830]
**K3s Versions to be Validated**

v1.30.2+k3s1
v1.29.6+k3s1
v1.28.11+k3s1
v1.27.15+k3s1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

```yaml
# /etc/rancher/k3s/config.yaml
selinux: true
```

**Comment by aganesh-suse** [comment]
Verified the install/upgrade/rancher and other tests mentioned in the description for the following versions: 
v1.30.2+k3s1
v1.29.6+k3s1
v1.28.11+k3s1
v1.27.15+k3s1

**Comment by aganesh-suse** [comment]
https://github.com/k3s-io/k3s/issues/10837

**Comment by dereknola** [comment]
This was noted as fine when I added support for AL2 in https://github.com/k3s-io/k3s/pull/10680

**Comment by ShylajaDevadiga** [comment]
Talked to Product Manager. We need to validate this only on rke2. Therefore closing this issue. Same on AL2023 https://github.com/k3s-io/k3s/issues/10411
