### ISSUE TITLE
Bump helm-controller to add support for skip-verify/plain-http and updated tolerations

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10831]
Bump helm-controller to add support for skip-verify/plain-http and updated tolerations
* https://github.com/k3s-io/helm-controller/issues/248
* https://github.com/k3s-io/helm-controller/issues/247

Backporting this to older releases will also remove support for helm v2 charts, as per 
* https://github.com/k3s-io/k3s/discussions/10763

**Comment by aganesh-suse** [comment]
Closing based on 1.31 results: https://github.com/k3s-io/k3s/issues/10833
