### ISSUE TITLE
Support for NodeExternalDNS

### ISSUE THREAD

**Issue by arnemileswinter** [k3s-io/k3s#10848]
**Is your feature request related to a problem? Please describe.**
I am using Agones in my cluster and the GameServer resources can resolve their address to NodeExternalDNS as seen here:
https://github.com/googleforgames/agones/blob/02e57babccab6489b18d956286152174fe9a1eaa/pkg/gameservers/gameservers.go#L46

however, the entry on k3s is unpopulated - only NodeExternalIP can be resolved with the --node-external-ip flag when launching k3s server.

**Describe the solution you'd like**
A cli option like `k3s server --node-external-dns example.com` similar to --node-external-ip

**Describe alternatives you've considered**
I am currently using --node-external-ip and look up the server domains by comparing with that ip in a local configuration.

**Additional context**
It seems undocumented that NodeExternalDNS is a valid status entry on node types. I opened a PR there https://github.com/kubernetes/api/pull/77 on k8s core v1 API Node Address type.

**Comment by brandond** [comment]
It's not undocumented, it is covered here : https://pkg.go.dev/k8s.io/api/core/v1#NodeAddressType
```
	// NodeInternalDNS identifies a DNS name which resolves to an IP address which has
	// the characteristics of a NodeInternalIP. The IP it resolves to may or may not
	// be a listed NodeInternalIP address.
	NodeInternalDNS [NodeAddressType](https://pkg.go.dev/k8s.io/api/core/v1#NodeAddressType) = "InternalDNS"

	// NodeExternalDNS identifies a DNS name which resolves to an IP address which has
	// the characteristics of a NodeExternalIP. The IP it resolves to may or may not
	// be a listed NodeExternalIP address.
	NodeExternalDNS [NodeAddressType](https://pkg.go.dev/k8s.io/api/core/v1#NodeAddressType) = "ExternalDNS"
```

We don't currently support setting either of the DNS types, just hostname and internal/external IPs.

**Comment by brandond** [comment]
@VestigeJ I haven't backported this yet, please reopen the backports. On the release branches, I suspect that the config file entry is being ignored and the external lookups you're testing with are returning public lookups instead of resolving to the node address as you would expect if this was working.
