### ISSUE TITLE
ImageVolume broken

### ISSUE THREAD

**Issue by laurivosandi** [k3s-io/k3s#10877]
**Environmental Info:**
K3s Version: 
k3s version v1.31.0+k3s1 (34be6d96)
go version go1.22.5

Node(s) CPU architecture, OS, and Version: 
Linux kubetest 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node

**Describe the bug:**
The freshly arrived [ImageVolume](https://kubernetes.io/docs/tasks/configure-pod-container/image-volumes/#create-pod) feature seems broken

**Steps To Reproduce:**

Deployed k3s 1.31 with:

```
INSTALL_K3S_EXEC="--kubelet-arg feature-gates=ImageVolume=true --kube-apiserver-arg feature-gates=ImageVolume=true"
INSTALL_K3S_CHANNEL=latest
```

Applied manifest:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: model
              mountPath: /model
      volumes:
        - name: model
          image:
            pullPolicy: IfNotPresent
            reference: registry.k8s.io/conformance:v1.31.0
```

**Expected behavior:**

Pod starts with  registry.k8s.io/conformance:v1.31.0 image contents mounted at /model

**Actual behavior:**

In Kubernetes Lens following error message is shown

```
Error: failed to generate container "558bb3f947d9e1a70c697143ba10b2795c58ee7bde9c4fa0e3b317acb02dbe7b" spec: failed to generate spec: failed to mkdir "": mkdir : no such file or directory
```

**Additional context / logs:**
```
Sep 12 07:33:18 kubetest k3s[2270]: E0912 07:33:18.926553    2270 log.go:32] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate container \"536ef130eb99ae8a9f69c175a410b6400a576c514f07ea5faf68b6dc638a8860\" spec: failed to generate spec: failed to mkdir \"\": mkdir : no such file or directory" podSandboxID="f785734aa1099aa8557e8d4e6cabe4de5d889901d31880caf2a3f972946d7f78"
Sep 12 07:33:18 kubetest k3s[2270]: E0912 07:33:18.926664    2270 kuberuntime_manager.go:1272] "Unhandled Error" err="container &Container{Name:nginx,Image:nginx:1.14.2,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:,HostPort:0,ContainerPort:80,Protocol:TCP,HostIP:,},},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:model,ReadOnly:false,MountPath:/model,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-rjk5r,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod ai-test-67984f78cd-n8xqd_default(e55f166a-1f0f-4728-96e2-fde67da551e3): CreateContainerError: failed to generate container \"536ef130eb99ae8a9f69c175a410b6400a576c514f07ea5faf68b6dc638a8860\" spec: failed to generate spec: failed to mkdir \"\": mkdir : no such file or directory"
Sep 12 07:33:18 kubetest k3s[2270]: E0912 07:33:18.927733    2270 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"nginx\" with CreateContainerError: \"failed to generate container \\\"536ef130eb99ae8a9f69c175a410b6400a576c514f07ea5faf68b6dc638a8860\\\" spec: failed to generate spec: failed to mkdir \\\"\\\": mkdir : no such file or directory\"" pod="default/ai-test-67984f78cd-n8xqd" podUID="e55f166a-1f0f-4728-96e2-fde67da551e3"
```

**Comment by brandond** [comment]
I don't know where this error is coming from, but it is not code that lives within this repo. I suspect that the problem is either in the kubelet, or containerd.

**Comment by brandond** [comment]
Have you tried this with any other distro or container runtime?

**Comment by brandond** [comment]
As I asked above, are you sure containerd even supports this? It's still alpha, and the upstream announcement only mentions it working with the latest releases of cri-o.
https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/

I suspect you'll need to wait for containerd to support this, or install and use cri-o instead of the containerd bundled with k3s.

**Comment by rotty3000** [comment]
Ok, That's fair. I misunderstood. thanks for checking :)

**Comment by rotty3000** [comment]
containerd issue for this:

https://github.com/containerd/containerd/issues/10496

**Comment by rotty3000** [comment]
Question. Is k3s using this repo as the source of its containerd?

**Comment by rotty3000** [comment]
sorry, --> https://github.com/k3s-io/containerd

**Comment by rotty3000** [comment]
I think this answers my question https://github.com/k3s-io/k3s/blob/master/go.mod#L12

**Comment by brandond** [comment]
We maintain a small number of patches on top of containerd to allow embedding it within k3s. Our rewrite support has also not been accepted by upstream.

https://github.com/k3s-io/containerd/compare/v1.7.23...v1.7.23-k3s1

**Comment by rotty3000** [comment]
@brandond could you point me to the rewrite support so I can see what exactly that is? I'm trying to look to get my hands dirty. Sometimes a solution to an upstream project not accepting a particular feature is offering a change instead that enables the feature to be implemented through some form of extensibility.

**Comment by brandond** [comment]
Did you look at the commits in the link in the message you just replied to?

**Comment by rotty3000** [comment]
.. right, sorry. long day! 😓

**Comment by scrapoxy** [comment]
Hi, it is now implemented in containerd and should come in containerd 2.1.0 (actually in beta): https://github.com/containerd/containerd/pull/11510

**Comment by fabienvauchelles** [comment]
Hi, it is now implemented in containerd and should come in containerd 2.1.0 (actually in beta): https://github.com/containerd/containerd/pull/11510

**Comment by LaurentGoderre** [comment]
This PR should address this:
* https://github.com/k3s-io/k3s/pull/12788

**Comment by laurivosandi** [comment]
Seems to be working with k3s 1.33.5 by enabling the gate flags
