### ISSUE TITLE
K3s log showing certificate expired error, no old certificates found

### ISSUE THREAD

**Issue by chrisarnott86** [k3s-io/k3s#10893]
**Environmental Info:**
K3s Version: v1.30.4+k3s1

Node(s) CPU architecture, OS, and Version:  amd64, Debian 11

Cluster Configuration: 4 servers

**Describe the bug:**
I've noticed log entries from k3s which give the following error:

```
k3s[1493080]: E0913 16:19:10.516785 1493080 authentication.go:73] "Unable to authenticate the request" err="[x509:
certificate has expired or is not yet valid: current time 2024-09-13T16:19:10+01:00 is after 2024-09-07T17:36:59Z, 
verifying certificate SN=5728476382960040447, SKID=, AKID=A0:E6:C1:22:CF:07:C2:14:64:39:5D:6F:82:45:61:E8:79:47:7B:06 failed: x509: certificate has expired or is not yet 
valid: current time 2024-09-13T16:19:10+01:00 is after 2024-09-07T17:36:59Z]
```

The certificates have recently updated (the cluster is approaching two years old), but checking all the certificates and running `k3s certificate check` shows everything to be fine. I'm seeing the error on 3 out of the 4 nodes, and it always refers to the same certificate (i.e. SN=5728476382960040447). This seems similar to the bug reported in #8762, but that was from a few versions ago.

**Steps To Reproduce:**
Have certificates autorenew within the cluster (i.e. approach n years of cluster running).

**Expected behavior:**
No lingering errors with certificate expirations.

**Actual behavior:**
Errors showing with certificate expired.

**Comment by brandond** [comment]
This error is not about any of the rotatable server certificates. As the error says, this regarding the certificate used to authenticate a **request**, which means that a **client** somewhere is using an expired certificate. This could be in a pod somewhere, or it could be an external system that you loaded a kubeconfig into. Check your pod logs, and the logs of any external systems that you've integrated into this cluster.

**Comment by chrisarnott86** [comment]
Thanks very much @brandond, that's got it fixed. Sorry for the red herring!
