### ISSUE TITLE
kubernetes cluster fails to serve request if 1 of node out of 2 servers node goes down.

### ISSUE THREAD

**Issue by yjagdale** [k3s-io/k3s#10902]
**Environmental Info:**
K3s Version: 
k3s version v1.30.4+k3s1 (98262b5d)
go version go1.22.5

Node(s) CPU architecture, OS, and Version: 
amazon linux 2023

Cluster Configuration:
2 servers
2 agents 

**Describe the bug:**
I have cluster with 2 servers(controlplane) 2 agents. When one of the master goes down cluster fails to serve kubectl commands which leads not to schedule any pod in the cluster. 

**Steps To Reproduce:**
- create 2 servers 
- create 2 agents
- Installed K3s: 
- stop/delete 1 server
- validate `kubectl get pods` on server 1

**Expected behavior:**
server 1 should serve request and should provision containers

**Actual behavior:**
k3s fails to serve request

**Comment by brandond** [comment]
You must have at least three nodes for a HA server cluster when using etcd. Please read the docs: https://docs.k3s.io/datastore/ha-embedded
