### ISSUE TITLE
 When I do compile k3s-arm64 binary it doesn't work

### ISSUE THREAD

**Issue by xrwang8** [k3s-io/k3s#10915]
When I compile the k3s binary by myself,
## build k3s
```
./scripts/download
./scripts/package
```
I get the binaries for k3s-arm64 from dist/artifacts/k3s-arm64,

## deploy k3s
```
chmod +x k3s
cp k3s /usr/local/bin/
curl -o install.sh https://get.k3s.io
export INSTALL_K3S_SKIP_DOWNLOAD=true
./install.sh
```
go version go1.22.2 linux/arm64
k3s tag  :v1.30.1+k3s1

**Environmental Info:**
K3s Version:  v1.30.1+k3s1 

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/a536b80d-2c04-4af8-a8be-fed8ba00f5ad">

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by dereknola** [comment]
Also, any reason why you are compiling K3s yourself? We publish arm64 releases.

**Comment by brandond** [comment]
It looks like it's starting, but runc is failing to start containers for some reason... what exactly did you change in k3s that caused you to need to rebuild it? I don't see that there's anything wrong with how you're installing or running it, so I suspect you've broken something else.

**Comment by brandond** [comment]
... why? Does k3s work properly if you download one of the binaries from our release page? If it does, then the problem is your build. If it does not, then the problem is your node.

**Comment by brandond** [comment]
I'm sorry, I can't help you debug why your specific build environment doesn't work.
