### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [k3s-io/k3s#10919]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing K3s as shown [here](https://elest.io/open-source/k3s). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/k3s)

**Comment by brandond** [comment]
We are not interested in suggesting use of 3rd party commercial products or managed service offerings at this time.

**Comment by kaiwalyakoparkar** [comment]
Hey @brandond, I understand! Thanks for the comment 🙌
