### ISSUE TITLE
Add support for Alibaba Cloud Linux

### ISSUE THREAD

**Issue by clcc2019** [k3s-io/k3s#10913]
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/9d53a2ef-2baf-45b0-ac66-9b6c86abaa68">
Alibaba Cloud Linux use el8，I modified the VERSION_ID to temporarily solve the installation problem

**Comment by cwayne18** [comment]
We have no plans currently to support Alibaba Cloud Linux at this time
