### ISSUE TITLE
k3s can't utilize tls option with mysql external database

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#1093]
**Version:**
v1.0.0-rc5

**Describe the bug**
Right now when passing tls flags to k3s with mysql, kine sets a custom tls config with the name kine, which always verify server certificate.

**To Reproduce**
- start mysql database with tls 
- start k3s server with dsn that have tls=skip-verify and pass only cert/key and not the cacrt

**Expected behavior**
k3s should start without verifying the server cert

**Actual behavior**
k3s will fail with message: `x509: certificate signed by unknown authority`

**Additional context**
https://github.com/rancher/kine/blob/master/pkg/drivers/mysql/mysql.go#L142-L146

this can be solved by passing a custom parameter to the dsn to skip server cert verification and parsing it from kine library

**Comment by cjellick** [comment]
This is referenced in our documentation. So when we fix this bug, we need to update the docs.

**Comment by caroline-suse-rancher** [comment]
Closing due to age

**Comment by tuxillo** [comment]
Is this still the case? Why close and then remove it from Dev?
