### ISSUE TITLE
Kubectl not working when 2 node are down if we setup 3 node cluster

### ISSUE THREAD

**Issue by ashok-mariyala** [k3s-io/k3s#10942]
**Environmental Info:**
K3s Version: 

```
ubuntu@ashok:~$ k3s -v
k3s version v1.30.3+k3s1 (f6466040)
go version go1.22.5
```

Node(s) CPU architecture, OS, and Version: 

`Ubuntu 22 AMD64`

Cluster Configuration:

`3 Nodes with all masters`

**Describe the bug:**

`I have done k3s cluster setup with 3 master nodes. When 2 nodes are down then kubectl is not working in available node. As available node also master node then why kubectl commands not working?`

**Steps To Reproduce:**

`- Installed K3s with 3 node cluster. Shutdown the 2 nodes and run kubectl commands in another active node. Then kubectl commands are not working. 
`
**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Yes, that is how quorum works. 
https://docs.k3s.io/datastore/ha-embedded
> HA embedded etcd cluster must be comprised of an odd number of server nodes for etcd to maintain quorum. **For a cluster with n servers, quorum is (n/2)+1.** For any odd-sized cluster, adding one node will always increase the number of nodes necessary for quorum. Although adding a node to an odd-sized cluster appears better since there are more machines, the fault tolerance is worse since exactly the same number of nodes may fail without losing quorum but there are more nodes that can fail.
