### ISSUE TITLE
How to override CoreDNS forward?

### ISSUE THREAD

**Issue by mreiche** [k3s-io/k3s#10951]
Hi. I'm having trouble using my private DNS for *coredns* as described here: https://github.com/k3s-io/k3s/discussions/7822

My host's `/etc/resolv.conf` contains only one nameserver
```
nameserver <My-Private-DNS-Server>
```
DNS resolving on the host works fine but not in CoreDNS.

What I tried:

### Create a custom-dns configmap (not working)
```
forward.override: |
    forward . <My-Private-DNS-Server>
```

### Using resolv.conf (not working)
```
forward.override: |
    forward . /etc/resolv.conf {
      policy sequential
    }
```

### Hacking the coredns ConfigMap

What works is the following in `Corefile`:
```
forward . <My-Private-DNS-Server>
```

But I don't want to override `/var/lib/rancher/k3s/server/manifests/coredns.yaml` or `coredns` ConfigMap.

### Creating an own zone
What also works is creating a custom zone.
```
  custom.server: |
    example.com {
      forward . <My-Private-DNS-Server>
    }
```

But I don't want to create a specified zone but using the forward for all requests not known to the cluster.  I want either to add `coredns-custom` to override the default forward or get *coredns* using the host's DNS (`/etc/resolv.conf`)

References:
- https://github.com/k3s-io/k3s/discussions/7822
- https://github.com/k3d-io/k3d/issues/816
- https://github.com/k3s-io/k3s/issues/462

**Comment by brandond** [comment]
You can't use a local resolver on 127.0.0.1 with pods, as each pod has its own loopback address within the pod's network namespace - it will not reach the host's loopback interface.

You should give your local resolver an actual IP on your network, and either put that in the host's resolv.conf, or create another resolv.conf with the preferred configuration, and point k3s at that file with the --resolv-conf flag.

**Comment by morooshka** [comment]
@brandond Does this section `forward.override` in `coredns-custom` configmap:
~~~
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
forward.override: |
    forward . /etc/resolv.conf {
      policy sequential
    }
~~~

supported in k3s and the forward line in the original config map:
~~~
forward . /etc/resolv.conf
~~~

Would be overwritten with:
~~~
    forward . /etc/resolv.conf {
      policy sequential
    }
~~~

?
I can see my `custom.server` patches applied, but the `forward.override` seems not (?)
Thanks in advance

**Comment by engnatha** [comment]
I think it's because the import overrides statement comes at the end of the default settings. I think this means you can only add new settings, but you are not allowed to modify existing ones. "override" seems to be a bit misleading by name, though it looks like this is coming from coredns instead of k3s ([ref](https://learn.microsoft.com/en-us/azure/aks/coredns-custom))

**Comment by morooshka** [comment]
Thank you for explanations!
