### ISSUE TITLE
Sub components used in K3s

### ISSUE THREAD

**Issue by sivanandasubbiah** [k3s-io/k3s#1098]
**Is your feature request related to a problem? Please describe.**
No, we are trying to build a feature using K3s

**Describe the solution you'd like**
We need few micro service in our system to be hosted and run on Kubernetes. We prefer to have the micro service on top of k3s rather than k8s as they are light weight. I hope we can run the K3s in BM/VM machines on top of RHEL environment. What are the sub components been used in K3s, where can I find more details on them?

**Comment by cjellick** [comment]
I'll be merging a documentation PR later today that may help explain this. Or, it may still be missing the detail you need. I'll drop another note here once these doc changes are live. You can then review and we can discuss more from there.

**Comment by sivanandasubbiah** [comment]
Hi, Is this been merged or in which documents can I refer the details now.

**Comment by cwayne18** [comment]
This should have been closed some time ago, as we list the components in docs as well as release ntoes
