### ISSUE TITLE
Bump wharfie

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10990]
We should bump wharfie to latest
* Update go-containerregistry to remove old github.com/docker/cli
* Fix https://github.com/rancher/wharfie/issues/25#issuecomment-2289099654
  K3s doesn't actually use Wharfie for any image pulls, but RKE2 does

**Comment by fmoral2** [comment]
https://github.com/rancher/distros-test-framework/actions/runs/11241324291
