### ISSUE TITLE
[updatecli] Bump Local Path Provisioner version

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#11036]
> Update rancher/local-path-provisioner image version
> 2 file(s) updated with "rancher/local-path-provisioner:v0.0.29": * manifests/local-storage.yaml * scripts/airgap/image-list.txt

**Comment by fmoral2** [comment]
validate at
https://github.com/k3s-io/k3s/issues/11037#issuecomment-2407032316
https://github.com/k3s-io/k3s/issues/11038#issuecomment-2407033268
https://github.com/k3s-io/k3s/issues/11039#issuecomment-2407034038
https://github.com/k3s-io/k3s/issues/11040#issuecomment-2407035001
