### ISSUE TITLE
Flannel CNI Not Deploying and All Pods Failing Readiness Probes Despite Open Firewall and Proper Setup Scripts

### ISSUE THREAD

**Issue by wanGiB** [k3s-io/k3s#11106]
I have set up a K3s Kubernetes cluster on Hetzner Cloud using Ubuntu 24.04 for all nodes. Despite following the provided setup scripts and ensuring that firewalls are properly configured to allow all necessary traffic, the Cluster Network Interface (CNI) **Flannel** is not deploying. Consequently, **all pods in the cluster are failing their readiness probes**, indicating a networking issue within the cluster.

### **Environment**

- **K3s Version:** (v1.30.5+k3s1
- **Operating System:** Ubuntu 24.04
- **Cloud Provider:** Hetzner Cloud
- **Firewall Provider:** Hetzner Cloud Firewalls

### **Setup Scripts**

**1. `server-setup.sh`:**

```bash
#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

ufw disable

echo "Creating First Server..."
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik --disable=servicelb --disable-cloud-controller --prefer-bundled-bin" sh -s - server --cluster-init
```

**2. `agent-setup.sh`:**

```bash
#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root." 1>&2
    exit 1
fi

ufw disable

FIRST_SERVER_IP="redacted"
FIRST_SERVER_JOIN_SECRET="redacted"

curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--prefer-bundled-bin" K3S_TOKEN="$FIRST_SERVER_JOIN_SECRET" sh -s - agent --server https://${FIRST_SERVER_IP}:6443

```

### **Firewall Configuration**

All nodes are protected by the following Hetzner Cloud Firewall rules:

```terraform
resource "hcloud_firewall" "k8s_firewall" {
  name = "k8s-firewall"

  # Allow all incoming TCP traffic on all ports
  rule {
    description    = "Allow all incoming TCP traffic"
    direction      = "in"
    protocol       = "tcp"
    port           = "1-65535"
    source_ips     = ["0.0.0.0/0", "::/0"]
  }

  # Allow all incoming UDP traffic on all ports
  rule {
    description    = "Allow all incoming UDP traffic"
    direction      = "in"
    protocol       = "udp"
    port           = "1-65535"
    source_ips     = ["0.0.0.0/0", "::/0"]
  }

  # Allow all outgoing TCP traffic on all ports
  rule {
    description       = "Allow all outgoing TCP traffic"
    direction         = "out"
    protocol          = "tcp"
    port              = "1-65535"
    destination_ips    = ["0.0.0.0/0", "::/0"]
  }

  # Allow all outgoing UDP traffic on all ports
  rule {
    description       = "Allow all outgoing UDP traffic"
    direction         = "out"
    protocol          = "udp"
    port              = "1-65535"
    destination_ips    = ["0.0.0.0/0", "::/0"]
  }
}

```

**Note**: UFW is disabled on all nodes prior to K3s installation.

### **Current Cluster State**

Only the following pods are running in the cluster:

```
NAMESPACE     NAME                                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-7b98449c4-9g44d                            1/1     Running   0          22m
kube-system   hcloud-cloud-controller-manager-78dfd7bf6f-5th6k   1/1     Running   0          19m
kube-system   local-path-provisioner-6795b5f9d8-zwq5p            1/1     Running   0          22m
kube-system   metrics-server-cdcc87586-g69lr                     1/1     Running   0          22m
traefik       traefik-zbl96                                      1/1     Running   0          17m

```

As you can see above, no CNI-related pods (e.g., Flannel) are present in the kube-system namespace, and all application pods are failing their readiness probes, likely due to networking issues. This indicates a significant networking problem within the cluster, which I am unsure how to resolve, as I expected Flannel to be installed by default.

Any suggestions on where I may have gone wrong would be greatly appreciated.

**Comment by brandond** [comment]
K3s doesn't run flannel in a pod. It is built into the K3s binary alongside everything else.

Where do you see that things are failing their health checks? All the pods you've listed are ready (1/1) with no restarts.

**Comment by wanGiB** [comment]
Thank you @brandond for your response but below is the output from the description of one of the pods deployed to the cluster:

```
 Warning  Unhealthy  6s (x12 over 106s)  kubelet            Readiness probe failed: Get "http://10.42.0.7:8080/health": dial tcp 10.42.0.7:8080: connect: connection refused

```

And this is happening even for test pods I deployed to the cluster using busy-box.

**Comment by brandond** [comment]
Readiness probes don't run across the container network overlay, they are executed locally within the node, between the kubelet process and the pod's network namespace. Either you have a local firewall blocking the connection, or the pod itself is not listening on that port.
