### ISSUE TITLE
flannel exited: failed to register flannel network: could not create wireguard interface: operation not supported

### ISSUE THREAD

**Issue by DokiDoki1103** [k3s-io/k3s#11166]
**Environmental Info:**
K3s Version: v1.28.7+k3s1

Node(s) CPU architecture, OS, and Version: Linux pt796eib 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:1 servers 2agents

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

ct 24 21:37:47 pt796eib k3s[14946]: I1024 21:37:47.181722   14946 desired_state_of_world_populator.go:159] "Finished populating initial desired state of world"
Oct 24 21:37:47 pt796eib k3s[14946]: I1024 21:37:47.416241   14946 kube.go:146] Node controller sync successful
Oct 24 21:37:47 pt796eib k3s[14946]: time="2024-10-24T21:37:47+08:00" level=error msg="flannel exited: failed to register flannel network: could not create wireguard interface: operation not supported"
Oct 24 21:37:47 pt796eib systemd[1]: k3s-agent.service: main process exited, code=exited, status=1/FAILURE
Oct 24 21:37:47 pt796eib systemd[1]: Unit k3s-agent.service entered failed state.
Oct 24 21:37:47 pt796eib systemd[1]: k3s-agent.service failed.
Oct 24 21:37:52 pt796eib systemd[1]: k3s-agent.service holdoff time over, scheduling restart.
Oct 24 21:37:52 pt796eib systemd[1]: Stopped Lightweight Kubernetes.
Oct 24 21:37:52 pt796eib systemd[1]: Starting Lightweight Kubernetes...

**Comment by DokiDoki1103** [comment]
centos not work
ubuntu is work

**Comment by brandond** [comment]
Do you have the wireguard kernel module installed? Isuspect it is not available out of the box on a distro as old as Centos 7.
