### ISSUE TITLE
Does High Availability Embedded etcd support changing the default ports 2379 and 2380

### ISSUE THREAD

**Issue by zhaileilei123** [k3s-io/k3s#11203]
Hi.
We found during our internal security testing that the etcd ports 2379 and 2380 are considered low ports and are not allowed for use. Is there a way to change them? I have checked the documentation, but there is no explanation on this. Can someone help me?

**Comment by brandond** [comment]
No, they are not configurable. These are their IANA assigned porte, see 
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=etcd

They are not allowed for use according by what? Are you also not allowed to use the correct ports for other things like HTTP (80) or HTTPS (443)?
