### ISSUE TITLE
Kine emulated etcd version is not set correctly

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#11220]
**Environmental Info:**
K3s Version: 
`v1.31.2+k3s1`

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
kine

**Describe the bug:**
Kine returns an emuated etcd version, to satisfy checks that the apiserver makes to enable features.

When run standalone, kine sets the version properly via CLI defaults - however the kine embedded in k3s is not setting the version properly because it does not use the kine CLI.

**Steps To Reproduce:**
Start k3s with kine

**Expected behavior:**

No errors, RequestWatchProgress feature is enabled (or at least there's no error message saying it's not supported)

**Actual behavior:**

Errors in logs:
```
E1104 21:36:49.575568      55 feature_support_checker.go:165] "Failed to parse etcd version" err="could not parse \"\" as version" version=""
I1104 21:36:49.575589      55 feature_support_checker.go:133] RequestWatchProgress feature is not supported by "unix://kine.sock" endpoint
```

There's a similar warning in the etcd logs when using embedded etcd that indicates we're setting the GitSHA build var incorrectly, but this doesn't affect anything:
```
"msg":"starting an etcd server","etcd-version":"3.5.13","git-sha":"Not provided (use ./build instead of go build)"
```

**Additional context / logs:**
* https://github.com/k3s-io/kine/pull/316

**Comment by endawkins** [comment]
### Validated on branch master with commit 9c32f83 / version v1.31.2
 
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-23-250 6.8.0-1016-aws #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
config.yaml 1:

write-kubeconfig-mode: 644
```
```
config.yaml 2:

write-kubeconfig-mode: 644
cluster-init: true
```
 
*Additional files*

```
N/A
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s with kine
3. Check etcd logs ```journalctl -u k3s | grep feature_support_checker``` and (```cluster-init: true```) ```journalctl -u k3s | grep etcd-version```
 
 
**Replication Results:**
- k3s version used for replication:

```
$ k3s -v
k3s version v1.31.2+k3s1 (6da20424)
go version go1.22.8
```
 

```
$ sudo journalctl -u k3s.service | grep feature_support_checker
Nov 07 22:28:03 ip-172-31-23-250 k3s[1973]: E1107 22:28:03.308090    1973 feature_support_checker.go:165] "Failed to parse etcd version" err="could not parse \"\" as version" version=""
Nov 07 22:28:03 ip-172-31-23-250 k3s[1973]: I1107 22:28:03.308120    1973 feature_support_checker.go:133] RequestWatchProgress feature is not supported by "unix://kine.sock" endpoint

with config.yaml cluster-init: true
$ sudo journalctl -u k3s.service | grep etcd-version
"msg":"starting an etcd server","etcd-version":"3.5.13","git-sha":"Not provided (use ./build instead of go build)"
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s -v
k3s version v1.31.2+k3s-9c32f838 (9c32f838)
go version go1.22.8
```
 

```
$ sudo journalctl -u k3s.service | grep feature_support_checker
ubuntu@ip-<IP_ADDRESS>:~$
```
 
**Additional context / logs:**
With config.yaml containing ```cluster-init: true```
```
$ sudo journalctl -u k3s.service | grep etcd-version
"msg":"starting an etcd server","etcd-version":"3.5.16","git-sha":"HEAD"
```
