### ISSUE TITLE
Add `nft` to k3s-root userspace bundle

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#11267]
The `NFTablesProxyMode` feature-gate is beta and on by default in Kubernetes v1.31:
* https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#nftables-backend-for-kube-proxy
* https://kubernetes.io/docs/reference/networking/virtual-ips/#proxy-mode-nftables

When started with `--kube-proxy-arg=proxy-mode=nftables`, kube-proxy will look for the `nft` binary. If it is not found, kube-proxy will exit and k3s will fail to start:
> `ERRO[0003] kube-proxy exited: unable to create proxier: unable to create ipv4 proxier: could not find nftables binary: exec: "nft": executable file not found in $PATH`

We should include `nft` in the k3s-root bundle, so that this works out of the box.

Note: the kube-proxy docs still don't cover the new mode, ref:
* https://github.com/kubernetes/enhancements/pull/4663#issuecomment-2463118426

**Comment by fmoral2** [comment]
validate
https://github.com/k3s-io/k3s/issues/11291#issuecomment-2474810959
https://github.com/k3s-io/k3s/issues/11292#issuecomment-2474810864
https://github.com/k3s-io/k3s/issues/11293#issuecomment-2474810788
