### ISSUE TITLE
 Issue with DNS Resolution in Airgapped K3s Cluster Due to UDP Block on Port 53

### ISSUE THREAD

**Issue by mahesh-kore** [k3s-io/k3s#11270]
**Environmental Info:**
K3s Version:  k3s version v1.31.1+k3s1 (452dbbc1)
go version go1.22.6

Node(s) CPU architecture, OS, and Version: 
x86_64, NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"

Cluster Configuration:
1 master and 1 agent

**Describe the bug:**
 Issue with DNS Resolution in Airgapped K3s Cluster Due to UDP Block on Port 53

**Steps To Reproduce:**
We have set up an airgapped K3s multi-node cluster, and due to network restrictions, traffic on UDP port 53 is blocked, preventing CoreDNS from resolving hostnames. However, TCP traffic is allowed.

Is there a way to configure or force CoreDNS to use TCP instead of UDP for DNS queries? Additionally, can this configuration be applied to all pods to ensure they query DNS using TCP?

- Installed K3s: 

**Expected behavior:**
We modified the kube-dns entry point and service to use TCP.
Pods should be able to resolve svc names over TCP instead of UDP

**Actual behavior:**
Despite these changes, ping and nslookup commands continue to use UDP for DNS queries.

**Additional context / logs:**

**Comment by brandond** [comment]
> Is there a way to configure or force CoreDNS to use TCP instead of UDP for DNS queries? Additionally, can this configuration be applied to all pods to ensure they query DNS using TCP?

We should cover this in the docs, but yes you can customize the coredns settings via configmap:
https://github.com/k3s-io/k3s/pull/4397

**Comment by mahesh-kore** [comment]
@brandond thanks for the wuick update.

The current resolv.conf file contains the following configuration:
```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5 use-vc
```


I would like to add custom options to this configuration. For example:
```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5 use-vc
```


How can I add additional options to resolv.conf?

**Comment by brandond** [comment]
That's not the correct thing to do. You don't need to change the resolver options in pods, since pods only talk to coredns. You need to change the coredns settings, as coredns is what is actually querying external resolvers. You need to configure coredns to use TCP instead of UDP.

**Comment by mahesh-kore** [comment]
The actual issue is that traffic on port 53 UDP is not allowed in the current environment. To bypass this, we want to configure all pods to use TCP instead of UDP for DNS queries.

**Comment by brandond** [comment]
You can try setting resolver options in the pod DNS config, but you'll need to do this for **every pod in your cluster**.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

**Comment by mahesh-kore** [comment]
Yes, that's correct. We are not allowed to connect to any IP addresses, including internal IPs, except for 127.0.0.1, which is has downstream to communicate with the enterprise DNS server. Therefore, we're trying this workaround. Do you see any other options to make it work in such a restricted environment?

**Comment by mahesh-kore** [comment]
> You can try setting resolver options in the pod DNS config, but you'll need to do this for **every pod in your cluster**.
> 
> https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
> 
> > options: an optional list of objects where each object may have a name property (required) and a value property (optional). The contents in this property will be merged to the options generated from the specified DNS policy. Duplicate entries are removed.

Yes, I tried this at the pod level, but I'm looking for a solution that applies cluster-wide.

**Comment by brandond** [comment]
There is no way to alter default DNS options at the cluster level. You could take a look at using something like this to automatically modify pod specs at creation time: https://github.com/redhat-cop/podpreset-webhook

Whatever policy your working with here doesn't really make any sense for use with Kubernetes or containerized workloads in general though. You need to ensure that you don't have anything blocking traffic within the cluster or other things are going to break as well.

**Comment by mahesh-kore** [comment]
I completely agree with you. Given the current restrictions, we’re exploring a workaround. 

Manually editing resolv.conf inside the container works, so now we’re looking for a way to automate this configuration consistently for all pods.

**Comment by mahesh-kore** [comment]
@brandond can we use --resolv-conf or the $K3S_RESOLV_CONF environment variable to achieve this

**Comment by brandond** [comment]
I don't believe so, I don't think the options from the host's resolv.conf have any impact on the resolv.conf in the pods. You need to use spec.dnsConfig for that.
