### ISSUE TITLE
setting tailscale's login-server with controlServerURL doesn't work as force-reauth is required with recent version of tailscale

### ISSUE THREAD

**Issue by proof-llc** [k3s-io/k3s#11279]
**Environmental Info:**
K3s Version: 
1.29 and 1.30

Cluster Configuration:
single server

**Describe the bug:**
setting tailscale's login-server with controlServerURL doesn't work as force-reauth is required with recent version of tailscale

**Steps To Reproduce:**
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.29 K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s - --disable=traefik --tls-san="node.example.com" --vpn-auth="name=tailscale,joinKey=asdfsadfasdfasdfsadfasdfsadfas,controlServerURL=https://example.com,forceReauth=true,extraArgs=--ssh" --node-external-ip=100.64.0.1

**Expected behavior:**
server should start

**Actual behavior:**
i get a message in the logs from tailscale that you can't run tailscale up and change login-server without `--force-reauth`.

**Comment by brandond** [comment]
Are you actually trying to change the control server, or have you had it set to this same URL the whole time?

If the tailscale CLI is making you force-reauth even when not actually changing the URL, that seems like a bug in tailscale.

**Comment by proof-llc** [comment]
i figured out the issue after reading your comment - thank you! k3s runs tailscale commands on the node itself, not some k8s pod or something similar - given i already had a working tailscale client on the node, it would interfere with its config. one thing, i wonder is: what does the integration do on top of "tailscale login" - is it configuring `--flannel-iface tailscale0` or os it something i still have to do?

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/blob/2441e469502faac6287d4cec0f72a67aac455eab/pkg/agent/flannel/setup.go#L41-L45
