### ISSUE TITLE
ip routing when host has a ipsec tunnel

### ISSUE THREAD

**Issue by johansmitsnl** [k3s-io/k3s#1132]
**Version:** v1.0.0 (18bd921c)

**Describe the bug**
The server is in a datacenter and it has ipsec tunnels to the local offices. The server can access all network devices from the local office. But inside the pods they can't access devices from the local office.

**To Reproduce**
* Server with ipsec tunnel
* Start a pod
* curl from inside the pod to a web service (webcam in my case) and you will only see trying.

**Expected behavior**
Access the device like the host can.

**Actual behavior**
Timeout on the connection

**Additional context**
Might be related to #951 but the set-up is now without ipsec from the flannel and moved to the host(master) and router of the office to be able to connect more hosts on the office network.

**Comment by alexellis** [comment]
I have a similar issue to this @ibuildthecloud @erikwilson 

Server is on DO
Agent is at home on RPi3

Scheduled two pods with nodeSelector and appropriate architecture - both run a webserver. When I schedule alpine on the server, I can hit the webserver on the server, but not the one on the RPi. The reverse is also true - running alpine on the RPi - I can hit the RPi webserver, but not the DO webserver pod. 

Using ipsec made no difference.

**Comment by alexellis** [comment]
@erikwilson @ibuildthecloud PTAL. This seems like a basic use-case that should work, or be documented clearly that it’s not supported.

Agent behind NAT, i.e. Intel NUC or RPi
Server on public cloud with public IP

Agent joins server with IPSec or Wireguard option, both nodes can be listed, but containers scheduled on either host cannot communicate.

**Comment by alexellis** [comment]
@johansmitsnl did you get any further with this? Have you tried the wireguard option instead?

**Comment by ibuildthecloud** [comment]
@alexellis The way we run ipsec it will not traverse a NAT without configuration and is extremely limited. In short traversing a NAT is not supported with our ipsec setup.

**Comment by ibuildthecloud** [comment]
I think if users want this use case of traversing a NAT they should open a different issue for a feature request to add NAT traversal. We have to use a different approach, most likely not ipsec.

**Comment by jakolehm** [comment]
@alexellis wireguard seems to work with NAT.

**Comment by johansmitsnl** [comment]
@alexellis I have not. I switched to a infrastructure VPN tunnel and not use the ipsec from K3S.

**Comment by txomon** [comment]
I just opened a bug that is really similar to this one (#1613), however to me it seems like it's not related to NAT transversal though.

@johansmitsnl given that you have found a workaround, mind describing your setup?

**Comment by johansmitsnl** [comment]
The work around I did was to run the pod in a node that in the target network.

The set-up I have is like this

```
Node 01 -- IPSEC on host (not in K3) --- IPSEC tunnel --- router -- Node 03
   |
Node 02
```

Node 01
* ens3 Public IP
* ens7 Local lan

Installation of Node 01 is: `$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface ens7" sh -`

When a pod in node 01 wants to access the network of the node 03 I get this issue. But when I am not wihtin a pod on node 01 it works.
When a pod in node 02 want to access the network of node 03 it works.

Note that node02 routes the network to node03 though node01.

It looks like some routing issue where it does not see the route available for the IPSEC tunnel.
