### ISSUE TITLE
Nil pointer dereference panic when migrating from 1.19

### ISSUE THREAD

**Issue by foverzar** [k3s-io/k3s#11328]
**Environmental Info:**
K3s Version: 
v1.19.x -> v1.30.6-k3s1

Node(s) CPU architecture, OS, and Version: 
Linux [REDACTED] 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
A small k8s testbed, expanding and contracting over multiple home and cloud hosts over time, currently 1 master, 1 worker

**Describe the bug:**
Nil pointer dereference at `pkg/nodepassword/nodepassword.go:111` when migrating master from v1.19.x (sorry, didn't write down the specific minor version) to 1.30.6-k3s1.

**Steps To Reproduce:**
I imagine triggering any call to github.com/k3s-io/k3s/pkg/nodepassword.MigrateFile with an actually existing passwordfile should suffice. Reproducible on a clean system via:
```sh
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.19.1+k3s1" sh -
# Wait for the cluster to startup and then upgrade it:
curl -sfL https://get.k3s.io | sh -
```

Didn't try checking if other versions are affected, sorry.

**Expected behavior:**
A successful migration, systemd service is stable.

**Actual behavior:**
NPE during server startup, systemd service falls into a restart loop.

**Additional context / logs:**
```
k3s[1530330]: panic: runtime error: invalid memory address or nil pointer dereference
k3s[1530330]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdcf5ab]
k3s[1530330]: goroutine 991 [running]:
k3s[1530330]: k8s.io/client-go/tools/cache.ListAll({0x726a320, 0xc0175024e0}, {0x0, 0x0}, 0xc01ec69b50)
k3s[1530330]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.30.6-k3s1/tools/cache/listers.go:35 +0x2b
k3s[1530330]: k8s.io/client-go/tools/cache.ListAllByNamespace({0x7284110?, 0xc0175024e0}, {0x0?, 0x30?}, {0x0, 0x0}, 0xc01ec69b50)
k3s[1530330]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.30.6-k3s1/tools/cache/listers.go:57 +0x413
k3s[1530330]: github.com/rancher/wrangler/v3/pkg/generic.(*Cache[...]).List(0xc017d16560?, {0x0?, 0x414525?}, {0x0?, 0x0?})
k3s[1530330]:         /go/pkg/mod/github.com/rancher/wrangler/v3@v3.0.0-rc2/pkg/generic/cache.go:77 +0x77
k3s[1530330]: github.com/rancher/wrangler/v3/pkg/generic.(*NonNamespacedCache[...]).List(...)
k3s[1530330]:         /go/pkg/mod/github.com/rancher/wrangler/v3@v3.0.0-rc2/pkg/generic/cache.go:115
k3s[1530330]: github.com/k3s-io/k3s/pkg/nodepassword.MigrateFile({0x728dcf0, 0xc0086ee000}, {0x728dfb0, 0xc0170136d0}, {0xc001f5c030, 0x2c})
k3s[1530330]:         /go/src/github.com/k3s-io/k3s/pkg/nodepassword/nodepassword.go:111 +0xe4
k3s[1530330]: github.com/k3s-io/k3s/pkg/server.runControllers({0x7243c28, 0xc0015faaa0}, 0xc000fb5908)
k3s[1530330]:         /go/src/github.com/k3s-io/k3s/pkg/server/server.go:110 +0x133
k3s[1530330]: github.com/k3s-io/k3s/pkg/server.startOnAPIServerReady({0x7243c28, 0xc0015faaa0}, 0xc000fb5908)
k3s[1530330]:         /go/src/github.com/k3s-io/k3s/pkg/server/server.go:90 +0x99
k3s[1530330]: created by github.com/k3s-io/k3s/pkg/server.StartServer in goroutine 1
k3s[1530330]:         /go/src/github.com/k3s-io/k3s/pkg/server/server.go:76 +0x2ed
systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: k3s.service: Failed with result 'exit-code'.
```

Apparently nil is not a valid value to pass down to `Cache.List(selector)` as it gets dereferenced at `github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.30.6-k3s1/tools/cache/listers.go:35` via `selectAll := selector.Empty()` without any prior nil-checks.

```go
        nodeNames := []string{}
	nodeList, _ := nodeClient.Cache().List(nil) // <---- panic here. Should have been labels.Everything()?
	for _, node := range nodeList {
		nodeNames = append(nodeNames, node.Name)
	}
	if len(nodeNames) == 0 {
		nodeNames = append(nodeNames, passwd.Users()...)
	}

	logrus.Infof("Migrating node password entries from '%s'", passwordFile)
	ensured := int64(0)
	start := time.Now()
	for _, nodeName := range nodeNames {
		if pass, ok := passwd.Pass(nodeName); ok {
			if err := Ensure(secretClient, nodeName, pass); err != nil {
				logrus.Warn(errors.Wrapf(err, "error migrating node password entry for node '%s'", nodeName))
			} else {
				ensured++
			}
		}
	}
```

Code semantics suggests that it should have been `labels.Everything()` instead of a nil. At least I've managed to kick-start the migration process after applying a patch and replacing a binary: https://github.com/k3s-io/k3s/compare/release-1.30...foverzar:k3s:release-1.30

I can make a proper pull request, if this is indeed the right place to fix it.

**Comment by brandond** [comment]
1.19 to 1.30 is not a tested or supported upgrade path.

You are expected to adhere to the upstream [version skew policy](https://kubernetes.io/releases/version-skew-policy/), and upgrade through each intermediate minor version. So 1.19 -> 1.20 -> 1.21 and so on until you get to 1.30.

Skipping intermediate versions will miss important migrations that occur between versions.
