### ISSUE TITLE
Exposing etcd metrics does not provide TLS certificate

### ISSUE THREAD

**Issue by fmunteanu** [k3s-io/k3s#11332]
**Environmental Info:**
K3s Version: 

```
# k3s -v
k3s version v1.30.6+k3s1 (1829eaae)
go version go1.22.8
```

Node(s) CPU architecture, OS, and Version: 

```
# uname -a
Linux apollo 6.8.0-1014-raspi #16-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 15 20:54:23 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:
3 servers, 5 agents

**Describe the bug:**

I'm exposing `kubeControllerManager`, `kubeEtcd` and `kubeScheduler` metrics, used with VictoriaMetrics, which complains `kubeEtcd` does not have a certificate:

> cannot perform request to "https://192.168.4.2:2379/metrics": Get "https://192.168.4.2:2379/metrics": remote error: tls: certificate required

```
# ss -tulpn | grep -E '2379|10257|10259'
tcp   LISTEN 0      4096          127.0.0.1:2379       0.0.0.0:*    users:(("k3s-server",pid=5273,fd=16))
tcp   LISTEN 0      4096        192.168.4.2:10259      0.0.0.0:*    users:(("k3s-server",pid=5273,fd=193))
tcp   LISTEN 0      4096        192.168.4.2:10257      0.0.0.0:*    users:(("k3s-server",pid=5273,fd=182))
tcp   LISTEN 0      4096        192.168.4.2:2379       0.0.0.0:*    users:(("k3s-server",pid=5273,fd=17))
```

There are no issues with  `kubeControllerManager` and `kubeScheduler`, current K3s configuration on `apollo` server:

```
# cat /etc/rancher/k3s/config.yaml
bind-address: 192.168.4.2
cluster-dns: 10.43.0.10
cluster-domain: cluster.local
disable:
  - local-storage
  - servicelb
  - traefik
disable-cloud-controller: true
disable-kube-proxy: true
disable-network-policy: true
embedded-registry: true
etcd-expose-metrics: true
flannel-backend: none
kube-controller-manager-arg: bind-address=192.168.4.2
kube-scheduler-arg: bind-address=192.168.4.2
node-taint:
  - node.cilium.io/agent-not-ready:NoExecute
  - node-role.kubernetes.io/control-plane:NoSchedule
server: https://192.168.4.10:6443
tls-san:
  - 192.168.4.10
token: redacted
```

`192.168.4.10` is a load balancer. I'm wondering if there is a specific setting I'm missing, thank you for your help.

**Comment by brandond** [comment]
See the discussion at https://github.com/rancher/rke2/issues/7170#issuecomment-2455360481

**Comment by fmunteanu** [comment]
@brandond you mean to use port 2381 instead?

**Comment by brandond** [comment]
Yes. Metrics are available via plaintext on the dedicated metrics port. The client port is only for use by etcd grpc API clients, not the Prometheus http API.

**Comment by fmunteanu** [comment]
Thank you for clarifying this, @brandond. From your perspective, is there a way to use the `https` scheme with `kubeEtcd`? Same way it is used with `kubeControllerManager`. Also, I'm interested to know what is the general consensus for `etcd` metrics exposure, with K3s. From my understanding, we should use 2381.

**Comment by brandond** [comment]
There is some discussion of that on the other thread. Although I'd recommend just checking over http unless you have a pressing reason to do otherwise.

**Comment by fmunteanu** [comment]
Thank you, I'll see what is the outcome. The reason I would prefer to use `https` scheme, is to align with `kubeControllerManager` and `kubeScheduler` scraping implementation, which use `https` scheme.

**Comment by brandond** [comment]
You don't need to use the bearer token for auth either.
