### ISSUE TITLE
Failed to find node

### ISSUE THREAD

**Issue by tbrandstetter** [k3s-io/k3s#1140]
**Version:**
k3s version v1.0.0 (18bd921c)
os version: Ubuntu 18.04.03 (latest patches)

**Describe the bug**
All nodes are configured with IP 127.0.1.1 in /etc/hosts

`Nov 27 09:27:16 prod-kubernetes-master-2 k3s[701]: E1127 09:27:16.122259     701 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Nov 27 09:27:16 prod-kubernetes-master-2 k3s[701]: E1127 09:27:16.122283     701 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Nov 27 09:27:16 prod-kubernetes-master-2 k3s[701]: E1127 09:27:16.122290     701 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Nov 27 09:27:16 prod-kubernetes-master-2 k3s[701]: E1127 09:27:16.122306     701 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Nov 27 09:27:16 prod-kubernetes-master-2 k3s[701]: E1127 09:27:16.122312     701 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
`

**To Reproduce**
Install a k3s multi master cluster with embedded db
Install two nodes

**Expected behavior**
If a configuration step is missing to suppress this error it should be added to the documentation.

**Actual behavior**
see bug description

**Comment by ShylajaDevadiga** [comment]
@tbrandstetter Have you used DQlite to create the multi master cluster? It would help if you could share the command and the flags used for us to reproduce the issue.

**Comment by tbrandstetter** [comment]
Sure!

The embedded solution only uses DQlite right?

**First Master**
/usr/local/bin/k3s server --cluster-init --no-deploy traefik,local-storage --kube-apiserver-arg service-node-port-range=30000-52000  --token XXX

**Other Masters**
/usr/local/bin/k3s server --server https://_IP of first Server_:6443 --no-deploy traefik,local-storage --kube-apiserver-arg service-node-port-range=30000-52000  --token XXX

**Nodes**
/usr/local/bin/k3s agent -s https://_IP of first Server_:6443 --token XXX

**Comment by tbrandstetter** [comment]
It was a relict because of: https://github.com/rancher/k3s/issues/299

I've already changed that, because I thought the same for a multi master requirement and because issue 299 is already fixed.

Nevertheless, changing that had no effect on this issue. Hostname is now backed by dns and should be resolved fine. Is it necessary to reinstall the master nodes? Or add the nodes directly in the /etc/hosts?

Dec  3 14:45:00 prod-kubernetes-master-0 k3s[19153]: E1203 14:45:00.428654   19153 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 14:45:00 prod-kubernetes-master-0 k3s[19153]: E1203 14:45:00.428684   19153 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 14:45:00 prod-kubernetes-master-0 k3s[19153]: E1203 14:45:00.428695   19153 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 14:45:00 prod-kubernetes-master-0 k3s[19153]: E1203 14:45:00.428704   19153 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 14:45:00 prod-kubernetes-master-0 k3s[19153]: E1203 14:45:00.428714   19153 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 15:01:39 prod-kubernetes-master-0 k3s[24627]: E1203 15:01:39.586209   24627 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 15:01:39 prod-kubernetes-master-0 k3s[24627]: E1203 15:01:39.586226   24627 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 15:01:39 prod-kubernetes-master-0 k3s[24627]: E1203 15:01:39.586236   24627 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found

**Comment by ShylajaDevadiga** [comment]
Entry in /etc/hosts is not needed. Try resolving your hostname after removing those entries.

**Comment by erikwilson** [comment]
This probably doesn't have anything to do with /etc/hosts or resolving from the server. We likely need to do some more testing to reproduce, but am guessing this is a legit issue with our cloud controller. Does the error keep occurring in the logs and never stop?

**Comment by ShylajaDevadiga** [comment]
To make sure we understand it right, @tbrandstetter does the nodes appear healthy and are the logs that is flooded with these errors?

**Comment by tbrandstetter** [comment]
I wouldn't say flooded - maybe it has something to do with https://github.com/rancher/k3s/issues/1139

The node looks not unhealthy, but I have many restarts of the some pods (not all - which is strange) --> see Issue 1139

This are the log entry of the master with the most entries of this type (I changed the hostname configuration at 6am)

```
Dec  3 10:21:13 prod-kubernetes-master-1 k3s[28398]: E1203 10:21:13.022429   28398 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 10:21:13 prod-kubernetes-master-1 k3s[28398]: E1203 10:21:13.022448   28398 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 10:21:13 prod-kubernetes-master-1 k3s[28398]: E1203 10:21:13.022455   28398 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 10:21:13 prod-kubernetes-master-1 k3s[28398]: E1203 10:21:13.022460   28398 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 10:21:13 prod-kubernetes-master-1 k3s[28398]: E1203 10:21:13.022466   28398 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 10:22:42 prod-kubernetes-master-1 k3s[28474]: E1203 10:22:42.200828   28474 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 10:22:42 prod-kubernetes-master-1 k3s[28474]: E1203 10:22:42.200850   28474 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 10:22:42 prod-kubernetes-master-1 k3s[28474]: E1203 10:22:42.200861   28474 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 10:22:42 prod-kubernetes-master-1 k3s[28474]: E1203 10:22:42.200871   28474 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 10:22:42 prod-kubernetes-master-1 k3s[28474]: E1203 10:22:42.200881   28474 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 10:27:27 prod-kubernetes-master-1 k3s[28995]: E1203 10:27:27.897413   28995 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 10:27:27 prod-kubernetes-master-1 k3s[28995]: E1203 10:27:27.897435   28995 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 10:27:27 prod-kubernetes-master-1 k3s[28995]: E1203 10:27:27.897442   28995 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 10:27:27 prod-kubernetes-master-1 k3s[28995]: E1203 10:27:27.897455   28995 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 10:27:27 prod-kubernetes-master-1 k3s[28995]: E1203 10:27:27.897462   28995 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 22:10:17 prod-kubernetes-master-1 k3s[11391]: E1203 22:10:17.014145   11391 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 22:10:17 prod-kubernetes-master-1 k3s[11391]: E1203 22:10:17.014342   11391 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 22:10:17 prod-kubernetes-master-1 k3s[11391]: E1203 22:10:17.014371   11391 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
Dec  3 22:10:17 prod-kubernetes-master-1 k3s[11391]: E1203 22:10:17.014383   11391 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 22:10:17 prod-kubernetes-master-1 k3s[11391]: E1203 22:10:17.014394   11391 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 22:13:14 prod-kubernetes-master-1 k3s[11631]: E1203 22:13:14.437067   11631 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-0: node "prod-kubernetes-node-0" not found
Dec  3 22:13:14 prod-kubernetes-master-1 k3s[11631]: E1203 22:13:14.437108   11631 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-2: node "prod-kubernetes-master-2" not found
Dec  3 22:13:14 prod-kubernetes-master-1 k3s[11631]: E1203 22:13:14.437120   11631 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-0: node "prod-kubernetes-master-0" not found
Dec  3 22:13:14 prod-kubernetes-master-1 k3s[11631]: E1203 22:13:14.437130   11631 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-master-1: node "prod-kubernetes-master-1" not found
Dec  3 22:13:14 prod-kubernetes-master-1 k3s[11631]: E1203 22:13:14.437141   11631 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node prod-kubernetes-node-1: node "prod-kubernetes-node-1" not found
```
