### ISSUE TITLE
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/mirrored-pause:3.6"

### ISSUE THREAD

**Issue by yansuan** [k3s-io/k3s#11412]
![image](https://github.com/user-attachments/assets/415fe365-b60c-4af2-b658-5f7cfc8ca822)
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/mirrored-pause:3.6": failed to pull image "rancher/mirrored-pause:3.6": failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": failed to resolve reference "docker.io/rancher/mirrored-pause:3.6": failed to do request: Head "https://registry-1.docker.io/v2/rancher/mirrored-pause/manifests/3.6": dial tcp 103.252.115.53:443: connect: connection refused

**Comment by liyimeng** [comment]
you are likely bocked by the WALL(qiang), nothing wrong with k3s

**Comment by brandond** [comment]
> `dial tcp 103.252.115.53:443: connect: connection refused`

You can't connect to docker hub. Figure out why and fix it, or use an image mirror.
