### ISSUE TITLE
v1.31.3+k3s1 breaking on download

### ISSUE THREAD

**Issue by brunohydro** [k3s-io/k3s#11417]
**Environmental Info:**
K3s Version: 
v1.31.3+k3s1

**Describe the bug:**
Trying to download the mentioned version with the download provided script, i'm getting an instant fail at the moment of downloading the hash file. This not happening using another versions

**Steps To Reproduce:**
Just run:
```
export INSTALL_K3S_CHANNEL=v1.31.3+k3s1
curl -sfL https://get.k3s.io | sh
```

**Additional context / logs:**
```
Cloud-init v. 23.3.3-0ubuntu0~23.04.1 running 'modules:config' at Thu, 05 Dec 2024 12:06:00 +0000. Up 15.26 seconds.
Cloud-init v. 23.3.3-0ubuntu0~23.04.1 running 'modules:final' at Thu, 05 Dec 2024 12:06:01 +0000. Up 16.07 seconds.
[INFO]  Finding release for channel v1.31
[INFO]  Using v1.31.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.31.3+k3s1/sha256sum-amd64.txt
[ERROR]  Download failed
chown: cannot access '/etc/rancher/k3s/k3s.yaml': No such file or directory
```

**Comment by mm503** [comment]
There are no amd64 artifacts published: https://github.com/k3s-io/k3s/releases/tag/v1.31.3%2Bk3s1

![image](https://github.com/user-attachments/assets/3d359f39-968b-47cf-babc-d7a312f86416)

**Comment by dereknola** [comment]
1. If your going to be on the bleeding edge, please check the status of the release on GitHub . The 1.31.3+k3s1 is clearly marked `Pre-release` for a reason. We don't uncheck it as latest and update the channels until the release is actually ready. 

2. `export INSTALL_K3S_CHANNEL=v1.31.3+k3s1` Is not the correct use of k3s channel. If you want to install a specific version, use `INSTALL_K3S_VERSION=v1.31.3+k3s1`. If you want the latest version from a particular minor, use `INSTALL_K3S_CHANNEL=v1.31` Everything after the `v1.XX` is just being ignored. 

3. Put together, if you want to avoid this happening in the future, and not have to check GitHub, just use `INSTALL_K3S_CHANNEL=latest`. This will install the newest version available that is fully released.

**Comment by mm503** [comment]
Hi @dereknola , what you said above makes 100% sense. However, I experienced the same issue with `INSTALL_K3S_CHANNEL=latest`. Not a biggie, just fyi, since the `latest` release seems to be pointing to `v1.31.3+k3s1` already.

```shell
root@pam:~# curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - --disable traefik --disable servicelb --tls-san pam --tls-san pam.local
[INFO]  Finding release for channel latest
[INFO]  Using v1.31.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.31.3+k3s1/sha256sum-amd64.txt
[ERROR]  Download failed
root@pam:~#
```
