### ISSUE TITLE
Install script broken

### ISSUE THREAD

**Issue by Bratzmeister** [k3s-io/k3s#11421]
**Describe the bug:**
install script doesn't work.

**Steps To Reproduce:**

1. go to https://docs.k3s.io/quick-start
2. follow instruction
3. paste and execute 'curl -sfL https://get.k3s.io | sh -'
4. ...

**Expected behavior:**
running the install script works as described in https://docs.k3s.io/quick-start

**Actual behavior:**
 after executing the script it seems to fail at downloading the release (hash) 

**Additional context / logs:**
```
root@backend:~# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
[ERROR]  Download failed

```

**Comment by Bratzmeister** [comment]
tried on multiple machines, same result

**Comment by janfrederik** [comment]
Problem seems with the channel server: https://update.k3s.io/v1-release/channels returns the normal json with all channels, however https://update.k3s.io/v1-release/channels/v1.30 (or any other specific channel) returns a 404.

**Comment by janfrederik** [comment]
@Bratzmeister problem seems to be solved now.

**Comment by cwayne18** [comment]
We're actively looking into an issue with the channel server, please stand
by

**Comment by brandond** [comment]
cloudflare cached some 404s while we were updating the channel server to address https://github.com/k3s-io/k3s/issues/11416 / https://github.com/k3s-io/k3s/issues/11417. Should be resolved now.

**Comment by Bratzmeister** [comment]
> @Bratzmeister problem seems to be solved now.

thx it is
