### ISSUE TITLE
only kubctl logs error pods "pod" not found in namespace "default"    

### ISSUE THREAD

**Issue by ashesofdream** [k3s-io/k3s#11428]
**Environmental Info:**
K3s Version: 

k3s version v1.30.6+k3s1 (1829eaae)
go version go1.22.8
Node(s) CPU architecture, OS, and Version: 

1 master no scheduled ,1 node
Cluster Configuration:

**Describe the bug:**

descibe pod is run normal.
but logs pod return `error: error from server (NotFound): pods "pod" not found in namespace "default"`
**Steps To Reproduce:**

- Installed K3s: 
I donot know  how  to trigger this. And after reboot node and k3s-agent service ,it still keep same problem.

**Expected behavior:**

I just to want to know how to fix this problem temporarily.

**Actual behavior:**

```
kubectl get deployments
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
alist-with-autoupload   1/1     1            1           4d7h

kubectl get pods
NAME                                     READY   STATUS    RESTARTS      AGE
alist-with-autoupload-6dc67495db-k8r56   2/2     Running   2 (96s ago)   44h

kubectl describe pod alist-with-autoupload-6dc67495db-k8r56
Name:             alist-with-autoupload-6dc67495db-k8r56
Namespace:        default
Priority:         0
Service Account:  default
Node:         ........

kubectl logs pod alist-with-autoupload-6dc67495db-k8r56
error: error from server (NotFound): pods "pod" not found in namespace "default"    
```

**Additional context / logs:**

**Comment by brandond** [comment]
It's not `kubect logs pod PODNAME`. Its just `kubectl logs PODNAME`. There is nothing other than pods that you can get logs from. The error also makes it clear that it's trying to find a pod named `pod`.

**Comment by ashesofdream** [comment]
> User error. It's not `kubect logs pod PODNAME`. Its just `kubectl logs PODNAME`. There is nothing other than pods that you can get logs from. The error also makes it clear that it's trying to find a pod named `pod`.

sorry , forget pod is not need for pod suddenly.
