### ISSUE TITLE
Updated channel server response breaks Rancher Desktop

### ISSUE THREAD

**Issue by jandubois** [k3s-io/k3s#11447]
The `responseType` field of the channel server response used to be `channels`, but has changed to `channel` sometime late last week:

```
$ curl --silent --fail https://update.k3s.io/v1-release/channels | jq 'del(.data)'
{
  "type": "collection",
  "links": {
    "self": "https://update.k3s.io/v1-release/channels"
  },
  "actions": {},
  "resourceType": "channel"
}
```

This unfortunately breaks Rancher Desktop 1.16 (the latest public release), which checks the `resourceType`: https://github.com/rancher-sandbox/rancher-desktop/pull/7461

This means on any new installation of Rancher Desktop, as well as any time a user performs a factory reset that wipes the k3s cache, the list of available k3s versions will be empty and the user cannot enable Kubernetes.

**Comment by brandond** [comment]
Fixed by https://github.com/rancher/channelserver/pull/30
