### ISSUE TITLE
Bump CoreDNS to 1.12.0

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#11450]
**Is your feature request related to a problem? Please describe.**

Need to address several CVEs in our current coreDNS 1.11.3

**Describe the solution you'd like**
Bump to coreDNS 1.12.0

**Describe alternatives you've considered**

**Additional context**

**Comment by VestigeJ** [comment]
Validated against the main branch only with COMMIT=124be7472bc2a0347477a279ef28d72df73c8699

will leave open for backports to be valdiated

$ k3s -v
```
k3s version v1.31.3+k3s1 (6e6af988)
go version go1.22.8
```

$ kgp coredns-56f6fc8fd7-jxfpp -n kube-system -o yaml | grep -i image: 
```
image: rancher/mirrored-coredns-coredns:1.11.3
```



$ COMMIT=124be7472bc2a0347477a279ef28d72df73c8699
$ k3s -v
```
k3s version v1.31.3+k3s-124be747 (124be747)
go version go1.22.8
```

$ kgp coredns-ccb96694c-4jm5p -n kube-system -o yaml | grep -i image:
```
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/e21d7296c251abecb820ef9fa98e41326a3e586663529bed35b02666781a9a98
DEBU[0000] Running /var/lib/rancher/k3s/data/e21d7296c251abecb820ef9fa98e41326a3e586663529bed35b02666781a9a98/bin/kubectl [kubectl get pods coredns-ccb96694c-4jm5p -n kube-system -o yaml]
    image: rancher/mirrored-coredns-coredns:1.12.0
    image: docker.io/rancher/mirrored-coredns-coredns:1.12.0
```
