### ISSUE TITLE
Configuration directory different than `/etc/rancher/`

### ISSUE THREAD

**Issue by rorosen** [k3s-io/k3s#11473]
**Is your feature request related to a problem? Please describe.**

I run k3s server on a system with [volatile root](https://www.man7.org/linux//man-pages/man8/systemd-volatile-root.8.html) where only specific paths are persisted across reboots. The inability of changing the configuration directory to something other than `/etc/rancher` and k3s not following directory symlinks at `/etc/rancher` make it very hard for me to persist the content of `/etc/rancher`. Unfortunately, mounts also don't work for me in combination with [systemd-confext](https://manpages.debian.org/testing/systemd/systemd-confext.8.en.html).

**Describe the solution you'd like**

My problem would be solved if I could point k3s to another configuration directory. Is this already possible and I'm missing something here? I didn't find a way to set it to another path, please let me know if this is already possible.

**Describe alternatives you've considered**

It would be also ok if k3s would follow symlinks, currently it errors with `file exists` when a symlink exists at `/etc/rancher`.

**Additional context**

Is there anything speaking against making this configurable? If not, I could try to contribute a PR for it.

**Comment by brandond** [comment]
Hmm, the error when it's a symlink is unexpected, we can look at that.

Have you tried symlinking /etc/rancher/node and /etc/rancher/k3s individually? Do you get the same behavior?

**Comment by rorosen** [comment]
> Have you tried symlinking /etc/rancher/node and /etc/rancher/k3s individually?

I just tried this but it results in the same error
```
level=error msg="Failed to generate kubeconfig: mkdir /etc/rancher/k3s: file exists"
```

For reference, this is the error I get when only symlinking `/etc/rancher/`
```
level=error msg="Failed to generate kubeconfig: mkdir /etc/rancher: file exists"
```

I tried with `v1.30.6+k3s1` and `v1.31.2+k3s1` but the error is the same. It seems to fail when calling [WriteToFile()](https://github.com/k3s-io/k3s/blob/master/pkg/clientaccess/kubeconfig.go#L47) in [WriteClientKubeConfig()](https://github.com/k3s-io/k3s/blob/master/pkg/server/server.go#L427).

**Comment by rorosen** [comment]
The problem was the target of the symlink at `/etc/rancher` didn't exist. `os.MkDirAll()` doesn't create a directory at the target location if it doesn't exist and I guess that is expected. It works if I create the directory to which `/etc/rancher` points.

Sorry for the noise, I had the wrong idea of how a symlink is treated in this case.

**Comment by brandond** [comment]
> It works if I create the directory to which /etc/rancher points.

Well yeah, that seems important.
