### ISSUE TITLE
x509: certificate signed by unknown authority for containerd connecting to private docker registery

### ISSUE THREAD

**Issue by floydljy** [k3s-io/k3s#1148]
**Version:**
v1.0.0

**Describe the bug**
I'm using the airgap install by the following link:
https://rancher.com/docs/k3s/latest/en/installation/airgap/

For the part "Create Registry YAML", I created following :
```
[aiops@7 ~]$ cat /etc/rancher/k3s/registries.yaml
---
mirrors:
  customreg:
    endpoint:
      - "https://192.168.100.3:5000"
configs:
  customreg:
    auth:
      username: repo-deploy # this is the registry username
      password: repo-deploy!QAZ # this is the registry password
    tls:
      ca_file: /etc/rancher/k3s/cert.d/ca.crt
      cert_file: /etc/rancher/k3s/cert.d/ca.crt
      key_file: /etc/rancher/k3s/cert.d/nginx.key

```
I do not understand why there are THREE settings for cert files. and why key file of the private docker registery is needed. 

the ca.crt is the one I set for my docker env to connect to the private registery. and the nginx.key is the priavate key I set for the https. 

erros when I try to connect to my private registery. seems like still cert error here. 
```
[aiops@7 ~]$ crictl pull 192.168.100.3:5000/centos:latest
FATA[2019-11-28T13:39:24.527331046+08:00] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "192.168.100.3:5000/centos:latest": failed to resolve reference "192.168.100.3:5000/centos:latest": failed to do request: Head https://192.168.100.3:5000/v2/centos/manifests/latest: x509: certificate signed by unknown authority
```

**To Reproduce**
always,

**Expected behavior**
the contained can connect to my private docker registery

**Actual behavior**
the containerd failed due to the error "x509: certificate signed by unknown authority"

**Additional context**
attach the ca.crt. my private registery is 192.168.100.3:5000, only https enabled.
[ca.tar.gz](https://github.com/rancher/k3s/files/3900097/ca.tar.gz)

```
[aiops@7 ~]$ crictl info
{
  "status": {
   .......
    "cni": {
      "binDir": "/var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69/bin",
      "confDir": "/var/lib/rancher/k3s/agent/etc/cni/net.d",
      "maxConfNum": 1,
      "confTemplate": ""
    },
    "registry": {
      "mirrors": {
        "customreg": {
          "endpoint": [
            "https://192.168.100.3:5000"
          ]
        },
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        }
      },
      "configs": {
        "customreg": {
          "auth": {
            "username": "repo-deploy",
            "password": "repo-deploy!QAZ",
            "auth": "",
            "identitytoken": ""
          },
          "tls": {
            "caFile": "/etc/rancher/k3s/cert.d/ca.crt",
            "certFile": "/etc/rancher/k3s/cert.d/ca.crt",
            "keyFile": "/etc/rancher/k3s/cert.d/nginx.key"
          }
        }
      },
      "auths": null
    },
    "disableTCPService": true,
    "streamServerAddress": "127.0.0.1",
    "streamServerPort": "10010",
    "streamIdleTimeout": "4h0m0s",
    "enableSelinux": false,
    "sandboxImage": "k8s.gcr.io/pause:3.1",
    "statsCollectPeriod": 10,
    "systemdCgroup": false,
    "enableTLSStreaming": false,
    "x509KeyPairStreaming": {
      "tlsCertFile": "",
      "tlsKeyFile": ""
    },
 ...
}

[aiops@7 ~]$ cat /var/lib/rancher/k3s/agent/etc/
cni/        containerd/ flannel/
[aiops@7 ~]$ cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml

[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"



[plugins.cri.registry.mirrors]

[plugins.cri.registry.mirrors."customreg"]
  endpoint = ["https://192.168.100.3:5000"]




[plugins.cri.registry.configs."customreg".auth]
  username = "repo-deploy"
  password = "repo-deploy!QAZ"




[plugins.cri.registry.configs."customreg".tls]
  ca_file = "/etc/rancher/k3s/cert.d/ca.crt"
  cert_file = "/etc/rancher/k3s/cert.d/ca.crt"
  key_file = "/etc/rancher/k3s/cert.d/nginx.key"


```

**Comment by floydljy** [comment]
searched some docs, that is from prometheus, the definition here seems like the cert_file and the key file is for Client AUTH, but actually, I only need the one way ssl. just my guessing, seek for confirmation. please help guide how to solve th x509 issue.

**Comment by vbohinc** [comment]
Put the certificate to the systems trusted anchor store and run update-ca-trust. I have also added the registry credentials to the serviceaccount [https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account](kubernetes.io).

There also seems to be a problem with containerd, I was only able to pull images when the k3s server is run with docker (--docker switch for k3s server).

**Comment by floydljy** [comment]
thanks @vbohinc , but I want to use containerd in my test. 
I acutally find a doc from containerd site. 
https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-tls-communication
I'm using self signed cert. so it may be related. 
[plugins.cri.registry.configs."my.custom.registry".tls]
  insecure_skip_verify = true

unfortunatly, when I try to change the file /var/lib/rancher/k3s/agent/etc/containerd/config.toml, it always rever back. so I can't test it by restarting containerd as I have no way to change the config to test it. @team, please help.

**Comment by vbohinc** [comment]
[plugins.opt]
  path = "{{ .NodeConfig.Containerd.Opt }}"
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
{{- if .IsRunningInUserNS }}
  disable_cgroup = true
  disable_apparmor = true
  restrict_oom_score_adj = true
{{end}}
{{- if .NodeConfig.AgentConfig.PauseImage }}
  sandbox_image = "{{ .NodeConfig.AgentConfig.PauseImage }}"
{{else}}
  sandbox_image = "docker.io/rancher/pause:3.1"
{{end}}
{{- if not .NodeConfig.NoFlannel }}
[plugins.cri.cni]
  bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
  conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"
{{end}}
[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
{{ if .PrivateRegistryConfig }}
{{ if .PrivateRegistryConfig.Mirrors }}
[plugins.cri.registry.mirrors]{{end}}
{{range $k, $v := .PrivateRegistryConfig.Mirrors }}
[plugins.cri.registry.mirrors."{{$k}}"]
  endpoint = [{{range $i, $j := $v.Endpoints}}{{if $i}}, {{end}}{{printf "%q" .}}{{end}}]
{{end}}
{{range $k, $v := .PrivateRegistryConfig.Configs }}
{{ if $v.Auth }}
[plugins.cri.registry.configs."{{$k}}".auth]
  {{ if $v.Auth.Username }}username = "{{ $v.Auth.Username }}"{{end}}
  {{ if $v.Auth.Password }}password = "{{ $v.Auth.Password }}"{{end}}
  {{ if $v.Auth.Auth }}auth = "{{ $v.Auth.Auth }}"{{end}}
  {{ if $v.Auth.IdentityToken }}identity_token = "{{ $v.Auth.IdentityToken }}"{{end}}
{{end}}
{{ if $v.TLS }}
[plugins.cri.registry.configs."{{$k}}".tls]
  insecure_skip_verify = true
  {{ if $v.TLS.CAFile }}ca_file = "{{ $v.TLS.CAFile }}"{{end}}
  {{ if $v.TLS.CertFile }}cert_file = "{{ $v.TLS.CertFile }}"{{end}}
  {{ if $v.TLS.KeyFile }}key_file = "{{ $v.TLS.KeyFile }}"{{end}}
{{end}}
{{end}}
{{end}}

**Comment by erikwilson** [comment]
`insecure_skip_verify` was added two days ago to CRI and is not yet available in k3s.

Using the skip TLS verification option is probably a very bad idea, you would be much better off just supplying the CA file.

The registries.yaml configuration is not used with the `--docker` flag, that configuration is only for containerd.

It looks like the hostname part of your registry is wrong, ie:
```
---
mirrors:
  customreg:
    endpoint:
      - "https://192.168.100.3:5000"
```

Would work if the image being pulled is customreg/centos:latest, if you are trying to `crictl pull 192.168.100.3:5000/centos:latest` then the registry config would need to look something like:

```
---
mirrors:
  192.168.100.3:5000:
    endpoint:
      - "https://192.168.100.3:5000"
```

**Comment by floydljy** [comment]
@erikwilson， thanks， your solution works perfectly.
but i may want the doc to be improved. https://rancher.com/docs/k3s/latest/en/installation/airgap/
I can't get the information about I have to change the customereg information. 
thanks again.

**Comment by denwork** [comment]
Is there a final solution to this problem?
I have a same problem.
My registries.yaml:
---
mirrors:
  push.example.com:
    endpoint:
      - "https://push.example.com"
configs:
  "push.example.com":    
    auth:
      username: admin
      password: admin123
    tls:
      cert_file: /etc/containerd/tls.crt
      key_file:  /etc/containerd/tls.key
      ca_file: /etc/containerd/cacerts.pem

The specific performance is as follows:
`crictl  info
............
        "push.example.com": {
          "endpoint": [
            "https://push.example.com"
          ]
        }
      },
      "configs": {
        "push.example.com": {
          "auth": {
            "username": "admin",
            "password": "admin123",
            "auth": "",
            "identitytoken": ""
          },
          "tls": {
            "caFile": "/etc/containerd/cacerts.pem",
            "certFile": "/etc/containerd/tls.crt",
            "keyFile": "/etc/containerd/tls.key"
          }
.........
crictl pull push.example.com/ics-sale-activity:20200114160546
FATA[2020-04-03T02:23:28.685026029+08:00] pulling image failed: rpc error: code = NotFound desc = failed to pull and unpack image "push.example.com/ics-sale-activity:20200114160546": failed to resolve reference "push.example.com/ics-sale-activity:20200114160546": push.example.com/ics-sale-activity:20200114160546: not found
`
But run docker pull push.example.com/ics-sale-activity:20200114160546 is ok.
I'm sure the image exists.
Who can help me? I would appreciate it very much.

**Comment by catherineluse** [comment]
To answer your question

> I do not understand why there are THREE settings for cert files. and why key file of the private docker registery is needed.

Based on the [CRI docs,](https://github.com/containerd/cri/blob/master/docs/registry.md) it says

> `ca_file` is file name of the certificate authority (CA) certificate used to authenticate the x509 certificate/key pair specified by the files respectively pointed to by `cert_file` and `key_file`.

@erikwilson Should we say the following in the docs?

> For one-way SSL, provide the `ca_file` only. For mutual SSL, provide the `ca_file`, `cert_file` and `key_file`.

**Comment by rezss** [comment]
The documentation is indeed a bit harder to understand, than is should be.
As an example: In an usual lab use-case, like: i deployed a docker registry, accessable through an Ingress (e.g. https://registry.k8s.example.com) with a self-signed certificate provided by cert-manager and k3s itself is not able to pull images from there, the simple solution is to add a registries.yaml file containing 4 lines:

```yaml
configs:
  registry.k8s.example.com:
    tls:
      ca_file: /etc/pki/tls/certs/root-ca.crt
```
