### ISSUE TITLE
k3s v1.25.16+k3s can not run on linux kernal 6.12.6

### ISSUE THREAD

**Issue by clywm520** [k3s-io/k3s#11496]
k3s v1.25.16+k3s can not run on linux kernal 6.12.

I1224 13:32:22.801965    2645 server.go:172] Version: v1.25.16+k3s
I1224 13:32:22.801980    2645 server.go:174] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
INFO[0000] Server node token is available at /var/lib/rancher/k3s/server/token 
INFO[0000] To join server node to cluster: k3s server -s https://10.0.12.7:6443 -t ${SERVER_NODE_TOKEN} 
INFO[0000] Agent node token is available at /var/lib/rancher/k3s/server/agent-token 
INFO[0000] To join agent node to cluster: k3s agent -s https://10.0.12.7:6443 -t ${AGENT_NODE_TOKEN} 
INFO[0000] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml   
INFO[0000] Run: k3s kubectl                             
WARN[0000] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
ERRO[0000] Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
FATA[0000] failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 

uname -a 
Linux vm1 6.12.6

这个问题该如何解决呢。

**Comment by brandond** [comment]
Please read the docs.
https://docs.k3s.io/installation/requirements?os=pi#operating-systems

**Comment by stefanlasiewski** [comment]
@clywm520 Note that some Raspberry Pi guides tell folks to add the options to the "last line of cmdline.txt", which can be confusing. You should add the options to the **same line** as the other commands, as shown in the k3s documentation.
