### ISSUE TITLE
Take cloud MySQL resource quickly is normal?

### ISSUE THREAD

**Issue by ashesofdream** [k3s-io/k3s#11491]
**Environmental Info:**
K3s Version: 
1.31

Cluster Configuration:

2 server deployment with a cloud mysql from TiDB , 1 agent , 2 work pod, use ingress-nginx instead of  pacifik.
**Describe the bug:**

CloudSql show that, mysql are executed about 15 times queries per second and take request unit ( a way to count consumption of resources
) quickly. Is that normal? 

**Actual behavior:**

For example:
```
SELECT
  (
    SELECT
      max (`rkv`.`id`) AS `id`
    FROM
      `kine` AS `rkv`
  ),
  (
    SELECT
      max (`crkv`.`prev_revision`) AS `prev_revision`
    FROM
      `kine` AS `crkv`
    WHERE
      `crkv`.`name` = ?
  ),
  `kv`.`id` AS `theid`,
  `kv`.`name` AS `thename`,
  `kv`.`created`,
  `kv`.`deleted`,
  `kv`.`create_revision`,
  `kv`.`prev_revision`,
  `kv`.`lease`,
  `kv`.`value`,
  `kv`.`old_value`
FROM
  `kine` AS `kv`
WHERE
  `kv`.`name` LIKE ?
  AND `kv`.`id` > ?
ORDER BY
  `kv`.`id` ASC
LIMIT
  ?
```
are executed 74.9 k times in 4 hour.
in the mean while , 
```
INSERT INTO
  `kine` (
    `name`,
    `created`,
    `deleted`,
    `create_revision`,
    `prev_revision`,
    `lease`,
    value,
    `old_value`
  )
VALUES
  (...)
```
are executed 40.09k  times.

Is this  normal ?may be deployment a local mysql is more suitable?

**Additional context / logs:**

**Comment by brandond** [comment]
This is normal. The datastore is constantly accessed in order to support reads and writes from clients and the control plane.
