### ISSUE TITLE
cloud provider

### ISSUE THREAD

**Issue by luisbrandao** [k3s-io/k3s#1177]
Is there any way to enable any type of cloud-integration with k3s?

I understand that cloud specific vendor have been removed from k3, is there any way to alternatively provide native cloud suport?

I am looking more specifically to be able to use AWS EBS volumes and load-balancers.

**Comment by DavidZisky** [comment]
Yes, it's possible. You just need to install cloud controller manager on your own. You have to find if AWS CCM is available somewhere on github and follow the instructions (if there are some) how to install it. I did it for DigitialOcean for example.

**Comment by jgreat** [comment]
Does the built-in CCM support any of the in-tree providers (aws, azure...) or is it just for the internal k3s type?

**Comment by DavidZisky** [comment]
> Does the built-in CCM support any of the in-tree providers (aws, azure...) or is it just for the internal k3s type?

It doesn't. Only internal k3s type

**Comment by brandond** [comment]
You should use the external cloud provider for whatever platform you're using: https://github.com/kubernetes/cloud-provider-aws#readme

**Comment by DavidZisky** [comment]
> Those docs are as clear as mud sweat_smile how is this actually added to a cluster, any ideas?

https://itnext.io/how-to-integrate-k3s-with-the-cloud-controller-36bd5020b8f7

**Comment by DavidZisky** [comment]
> Thanks for the article, anything on integrating with AWS?

The article uses DigitalOcean as an example but the process is the same for any provider. So you just need to understand the process and apply it to AWS controller, they have this documented as well on their controller page but there are some k3s specifics, so again, just use the above + the below:

https://cloud-provider-aws.sigs.k8s.io/getting_started/

**Comment by dereknola** [comment]
Closing as 1.23+ are the only supported versions.
