### ISSUE TITLE
k3s segmentation fault Rpi 4 4GB

### ISSUE THREAD

**Issue by vFondevilla** [k3s-io/k3s#1181]
**Version:**
  v1.0.0 (18bd921c)
Installed with:
curl -fL https://get.k3s.io | K3S_TOKEN=Randompassword sh -s - server --cluster-init

**Describe the bug**
K3s is segfaulting in Ubuntu 19.10

**To Reproduce**
After deploying a multimaster (3 nodes) cluster and deployed my first pod (NFS Provisioner), loaded an storage class and deployed a Pihole using PVC, the first master began to segfault.

**Expected behavior**
K3s keeps running.

**Actual behavior**
Segmentation Fault

**Additional context**
Logs from the Debug.
[k3s_segv.log](https://github.com/rancher/k3s/files/3947347/k3s_segv.log)

**Comment by davidnuzik** [comment]
This doesn't appear to be the same issue but (maybe) related: https://github.com/rancher/k3s/issues/1115

**Comment by vFondevilla** [comment]
In this case the OS is ARM64 and not armfh

**Comment by jonstelly** [comment]
I saw this yesterday.  3 raspberry 4s with Ubuntu 19.10 arm64 and k3s 1.0.  I've just recreated the cluster since I had tried to install a mountain of stuff all at once.  I'll try adding things back one at a time and attach another log if it crashes again.
