### ISSUE TITLE
CrashLoopBackOff when I deploy the python

### ISSUE THREAD

**Issue by chankamlam** [k3s-io/k3s#1187]
I get a Raspi cluster with two Raspi 3b

as the title I get "CrashLoopBackOff" when I deploy the python image which pull from docker.io

and I can not find any log with "sudo kubectl logs" , just empty

and I can not find any wrong with "sudo kubectl describe"

pls, help!!! (I just think about is it the problem between choosing containerd and docker?)

<img width="334" alt="Screenshot 2019-12-12 at 15 36 38" src="https://user-images.githubusercontent.com/9009522/70691929-3e89b980-1cf5-11ea-9e43-ad61f3858cc6.png">

<img width="392" alt="Screenshot 2019-12-12 at 15 18 15" src="https://user-images.githubusercontent.com/9009522/70691805-ee125c00-1cf4-11ea-994c-1dd6d10217a5.png">

<img width="586" alt="Screenshot 2019-12-12 at 15 17 39" src="https://user-images.githubusercontent.com/9009522/70691695-a7246680-1cf4-11ea-96ec-daf740547d6d.png">

<img width="394" alt="Screenshot 2019-12-12 at 15 26 23" src="https://user-images.githubusercontent.com/9009522/70691712-b3a8bf00-1cf4-11ea-85d9-2e05c710b94e.png">

<img width="882" alt="Screenshot 2019-12-12 at 15 28 01" src="https://user-images.githubusercontent.com/9009522/70691716-b86d7300-1cf4-11ea-9f5d-6b0894478f9e.png">

**Comment by erikwilson** [comment]
I am guessing you are on a Pi and the image is not multi-arch?

**Comment by erikwilson** [comment]
Sorry, it looks like there should be an armv7 python image. Maybe following the logs might help show the error? There are also the k3s logs and containerd logs which might provide additional info, please check /var/log and /var/lib/rancher/k3s/agent/containerd/containerd.log

**Comment by chankamlam** [comment]
> Sorry, it looks like there should be an armv7 python image. Maybe following the logs might help show the error? There are also the k3s logs and containerd logs which might provide additional info, please check /var/log and /var/lib/rancher/k3s/agent/containerd/containerd.log


for /var/log, which one should I take care as pic?

<img width="932" alt="Screenshot 2019-12-13 at 10 43 23" src="https://user-images.githubusercontent.com/9009522/70765345-819b6980-1d95-11ea-9ec5-d53a3c465530.png">


for /var/lib/rancher/k3s/agent/containerd/containerd.log, I can find the log looping display 
<img width="1013" alt="Screenshot 2019-12-13 at 10 42 11" src="https://user-images.githubusercontent.com/9009522/70765333-6f213000-1d95-11ea-9d8e-950b9c6340bd.png">

**Comment by onedr0p** [comment]
Please don't post screenshots of logs or text, it makes search engines useless for other people having similar issues. Use markdown code blocks instead.

Now to the issue, you are just running python:latest? Do you know that brings you to the python shell? What are you expecting? The container isn't doing anything...

```bash
docker run -it python:latest
Python 3.8.0 (default, Nov 23 2019, 05:36:56)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by chankamlam** [comment]
> Please don't post screenshots of logs or text, it makes search engines useless for other people having similar issues. Use markdown code blocks instead.
> 
> Now to the issue, you are just running python:latest? Do you know that brings you to the python shell? What are you expecting? The container isn't doing anything...
> 
> ```shell
> docker run -it python:latest
> Python 3.8.0 (default, Nov 23 2019, 05:36:56)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>>
> ```

so sorry, thank you for ur reply ,u a right

**Comment by onedr0p** [comment]
Please close the issue if you are all set.
