### ISSUE TITLE
error pull for java8

### ISSUE THREAD

**Issue by chankamlam** [k3s-io/k3s#1188]
<img width="992" alt="Screenshot 2019-12-12 at 16 13 09" src="https://user-images.githubusercontent.com/9009522/70694435-8ced8700-1cfa-11ea-87be-b89d57fb1c6f.png">
<img width="515" alt="Screenshot 2019-12-12 at 16 13 29" src="https://user-images.githubusercontent.com/9009522/70694512-c58d6080-1cfa-11ea-9e6a-2d3a89b6a1c7.png">

how can I get auth to pull java8 from the docker.io with using the containerd without using docker

**Comment by erikwilson** [comment]
It looks like the image name is wrong. Are you deploying a file from another project?

**Comment by chankamlam** [comment]
> It looks like the image name is wrong. Are you deploying a file from another project?

can deploy in my Mac, it's about the auth of containerd which I don't know how to setup the login as docker login. here is the log about the deployment error of java8
<img width="1002" alt="Screenshot 2019-12-13 at 10 42 58" src="https://user-images.githubusercontent.com/9009522/70765586-27e76f00-1d96-11ea-93dc-62c5fd772e0d.png">

**Comment by chankamlam** [comment]
I know how to fix it now! it needs to pull with --creds: sudo crictl pull --creds dockerAccount:dockerPassword store/oracle/serverjre:8, but I still don't know how to fixed it when deveployment what it is not sured to run the pull cmd in which node when cluster, until I excute pull cmd to get the image local for every node of cluster.
