### ISSUE TITLE
[Documentation] Requests for alignment of examples, more advanced usage examples

### ISSUE THREAD

**Issue by jonstelly** [k3s-io/k3s#1194]
**Is your feature request related to a problem? Please describe.**
I understand k3s just went 1.0 (congrats on getting to that point, this is an awesome project).  I also see a handful of other documentation issues already being worked on...  But I have a few things I've struggled a bit with so wanted to capture them here as requests for more documentation.

I don't know if I'm doing things "correctly" so I don't want to submit pull requests for this since I bet they'd just get rejected or spend more time getting reworked anyway so I'll try and provide examples here that may be useful for someone to copy/paste (or explain that I'm doing something wrong).

I'm trying to set up an HA control plane with embedded db with a mix of agents, some being bare metal and others as simple docker containers using the `rancher/k3s` docker image.

**Describe the solution you'd like**

***- get.k3s.io script vs k3s commands***

Documentation flips around between piping the `get.k3s.io` script to `sh -` and showing raw `k3s` commands.

I may be wrong, but I'd wager most people will be using the script to install as a service and running k3s from the command-line would be less common.  If nothing else, the k3s commands have pretty thorough documentation of all the options by way of `k3s ??? --help`, so maybe all the web documentation could focus only on installation / configuration using the script?  This would prevent the flipping back and forth that's currently there and I hope would make the documentation easier to both read and write?

Alternatively, would a general guideline that any time an example command is given, give both the install script format and the k3s command-line?

Regarding the script, it took me a while before I understood some implications of how the `get.k3s.io` script could take parameters... It's somewhat documented in the [INSTALL_K3S_EXEC](https://rancher.com/docs/k3s/latest/en/installation/install-options/) section of the install options documentation.  But one point that's not quite clear: when using the script it sets up a k3s service, do all parameters end up going to the service command line that gets executed every time the service starts?  When I tried to use a complex token (special characters) I got errors when the service tried to start.  Changing to a simple token fixed that issue.  Is there some general guidance on what the best way to pass parameters is?  ENV or arguments after `sh -s -`?  Is there a difference?

***- K3S_CLUSTER_SECRET***

This is referenced in a couple places but the documentation doesn't really explain the difference between `K3S_CLUSTER_SECRET` and `K3S_TOKEN`.  From this comment: https://github.com/rancher/k3s/issues/876#issuecomment-543224140 it seems that `KCS` is stable where `KT` may change?  Under what conditions does `KT` change?  When a cluster is recreated and TOKEN isn't specified explicitly?  At first I assumed `KCS` had been replaced with `KT` but I still see `KCS` being used in the example docker compose file and other places.
 
***- More environment examples***

A few more examples would be helpful...

- After spending a bit of time figuring out how to bootstrap my environment, here are the commands I used to get an HA (embedded db) cluster set up with a few agents:

```
#First Server
curl -sfL https://get.k3s.io | K3S_TOKEN="SHHHH" sh -s - server --cluster-init

#Other Servers
curl -sfL https://get.k3s.io | K3S_TOKEN="SHHHH" K3S_URL="https://SERVERONE:6443/" sh -s - server

#Agents
curl -sfL https://get.k3s.io | K3S_TOKEN="SHHHH" K3S_URL="https://SERVERONE:6443/" sh -s -
```

- Running the k3s image in docker as an agent:

`docker run -it --rm -e K3S_TOKEN=SHHHH -e K3S_URL=https://SERVERONE.FULLDOMAIN:6443/ -p 80:80 -p 443:443 --name agent-01 -h agent-01 --privileged rancher/k3s:v1.0.0 agent`

My last issue is that I need to figure out where to mount a volume so the agent secret node-passwd entry gets persisted and retained across restarts... If I stop and relaunch the agent command above I get this error until I change the agent name:

`Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag`

**Comment by alekc** [comment]
Judging by https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#deprecated-options it looks like K3S_CLUSTER_SECRET is deprecated in favour of token

**Comment by dereknola** [comment]
This is an old issue, most of this was resolved over the years, but the big one was recently with the new docs website, we added a whole new section on [configuration](https://docs.k3s.io/installation/configuration) and reworked the [HA setup guide](https://docs.k3s.io/installation/ha-embedded). Docker connections to K3s are also [avaliable](https://docs.k3s.io/advanced#running-k3s-in-docker).
