### ISSUE TITLE
k3s and port 443

### ISSUE THREAD

**Issue by swuecho** [k3s-io/k3s#1204]
**Version:**

k3s version v1.0.0 (18bd921c)

**Describe the bug**

I have a service run on port 443. After install k3s (master or ndoe), that service can not be connected anymore.

I changed the port of my service to 444 and work again.

not sure why this is happening.

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by adamcavendish** [comment]
It seems that I'm experiencing the same issue. I can connect to the pod and the corresponding service on their ports but I cannot connect to the ingress host path.

**Comment by SergeyBear** [comment]
Hi. It's all because ingress, which is installed by default with k3s.
See [comment](https://github.com/rancher/k3s/issues/436#issuecomment-489737289) for details.
