### ISSUE TITLE
option to disable load balancer for k3s agent

### ISSUE THREAD

**Issue by texascloud** [k3s-io/k3s#1211]
**Is your feature request related to a problem? Please describe.**
I am having trouble having "agents" join the "server" due to sending GET requests for `/cacerts` through the local load balancer. When sending requests directly to ServerURL/cacerts, I am able to successfully get the certs. My use-case is non-common, and I'm developing it for a kubecon talk.

[This is where](https://github.com/rancher/k3s/blob/e6f8418820622ee1cbe70746df4eaee1edeaee76/pkg/cluster/join.go#L71) the agents join using the joinURL (which is set to the `ServerURL` [here](https://github.com/rancher/k3s/blob/97383868bd89a39d386a431e44c17d41cb9258ee/pkg/cli/server/server.go#L66), but then the agent's `ServerURL` is [overridden by the lb URL](https://github.com/rancher/k3s/blob/d4959d53aff20e9242ff3896f89a5c5d2f44ebf2/pkg/agent/run.go#L117), which explains why requests to `/cacerts` are being sent to localhost:<random_port> rather than the `ServerURL` I specified when starting the agent)

 (Note: func `ParseAndValidateToken` is called in httpJoin as well as `NormalizeAndValidateTokenForUser`, why?)

[Here](https://github.com/rancher/k3s/blob/e6f8418820622ee1cbe70746df4eaee1edeaee76/pkg/clientaccess/clientaccess.go#L124) is where `GetCACerts` is called. [This is the error](https://github.com/rancher/k3s/blob/e6f8418820622ee1cbe70746df4eaee1edeaee76/pkg/clientaccess/clientaccess.go#L257) that's showing up when I look in the logs of k3s-agent on my ubuntu16 node via running `journalctl -u k3s-agent`. Here is a more complete picture:

```
Dec 17 22:10:20 worker systemd[1]: Started Lightweight Kubernetes.
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.255021031Z" level=info msg="Starting k3s agent v1.0.0 (18bd921c)"
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.255799257Z" level=info msg="module overlay was already loaded"
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.256096370Z" level=info msg="module nf_conntrack was already loaded"
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.256381942Z" level=info msg="module br_netfilter was already loaded"
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.257068167Z" level=info msg="Running load balancer 127.0.0.1:34722 -> [hcp.v2.platform9.beer:443]" // Ask me about HCP ;)
Dec 17 22:10:21 worker k3s[1759]: time="2019-12-17T22:10:21.266337539Z" level=error msg="failed to get CA certs at https://127.0.0.1:34722/cacerts: Get https://127.0.0.1:34722/cacerts: EOF"
Dec 17 22:10:23 worker k3s[1759]: time="2019-12-17T22:10:23.288821027Z" level=error msg="failed to get CA certs at https://127.0.0.1:34722/cacerts: Get https://127.0.0.1:34722/cacerts: EOF"
Dec 17 22:10:25 worker k3s[1759]: time="2019-12-17T22:10:25.331732701Z" level=error msg="failed to get CA certs at https://127.0.0.1:34722/cacerts: Get https://127.0.0.1:34722/cacerts: EOF"
... (continues doing this forever)
```

Output from curling the same load balancer endpoint locally
```
root@worker:~# curl -k -v https://127.0.0.1:34722/cacerts
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 34722 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

Output from curling the `ServerURL` with `/cacerts` path from the worker
```
root@worker:~# curl -k -v https://hcp.v2.platform9.beer/cacerts
*   Trying 172.107.176.28...
* Connected to hcp.v2.platform9.beer (172.107.176.28) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: k3s (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: EC
*        certificate version: #3
*        subject: O=k3s,CN=k3s
*        start date: Mon, 16 Dec 2019 23:35:07 GMT
*        expire date: Tue, 15 Dec 2020 23:46:02 GMT
*        issuer: CN=k3s-server-ca@1576539307
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /cacerts HTTP/1.1
> Host: hcp.v2.platform9.beer
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/plain
< date: Tue, 17 Dec 2019 22:13:20 GMT
< content-length: 526
< x-envoy-upstream-service-time: 0
< server: envoy
<
-----BEGIN CERTIFICATE-----
MYCERTREDACTED
-----END CERTIFICATE-----
* Connection #0 to host hcp.v2.platform9.beer left intact
```

So I'm able to successfully hit the `/cacerts` path from the agent if the request is sent directly to the value of `ServerURL`.

**Describe the solution you'd like**
1 of 2 would solve my problem:

1) I would like for the agent to be able to make a successful GET request to the server through the local load balancer proxy without getting this non-properly terminated error

2) The ability to disable the load balancer for agents when making requests to the servers, since I've made sure the `ServerURL` will load balance requests to all the available servers. *NOTE*: My servers are running with the flag `--disable-agent`, which I know @erikwilson has made clear is something that breaks a lot of functionality. It hasn't caused problems until maybe now

**Describe alternatives you've considered**
I've considered adding the ability to disable the load balancer for agents via a flag, just like is [done for the server](https://github.com/rancher/k3s/blob/97383868bd89a39d386a431e44c17d41cb9258ee/pkg/cli/server/server.go#L204).

**Additional context**
My k3s "server" is running as a Pod in a cluster while my "agents" are VMs running in openstack, and cannot be accessed directly. There is no flannel network traffic going to the k3s "server".

**Comment by CamelCaseNotation** [comment]
@erikwilson perhaps you can get me unblocked?

**Comment by erikwilson** [comment]
Is there a good reason to use `--disable-agent`? The preferred alternative is to just add a taint to the master nodes if you don't want things running on them by default.

Are you running behind an SSL terminating load balancer? The server URL should typically include the port 6443, which is the k8s/k3s API.

**Comment by CamelCaseNotation** [comment]
I'm running k3s server in a Pod

Yes, I'm using ambassador to do TLS termination. It is configured to pass through the TLS connection all the way to the k3s process running on port 6443

**Comment by erikwilson** [comment]
k3s server  should still be run without `--disable-agent`, even in a pod. I don't think it is the issue here, but using that flag will probably cause trouble or confusion at some point in the future.

Are you only having issues with the TLS terminating load balancer? Does using a simple TCP load balancer or the server IP work okay?

**Comment by erikwilson** [comment]
It also might be worth checking that your cert has 127.0.0.1 in the TLS SANs, as this is the IP that the cert would be validated against.

**Comment by CamelCaseNotation** [comment]
The load balancer isn't terminating TLS in this case. I'm using this [feature of ambassador](https://www.getambassador.io/reference/tls/origination/#tls-origination), which keeps the TLS connection intact all the way to the k3s server. Here's the annotations on the secret which contains the cert (this is the k3s-serving secret that gets created)

```
    listener.cattle.io/cn-10.20.35.135: 10.20.35.135
    listener.cattle.io/cn-10.43.0.1: 10.43.0.1
    listener.cattle.io/cn-127.0.0.1: 127.0.0.1
    listener.cattle.io/cn-172.107.176.28: 172.107.176.28
    listener.cattle.io/cn-hcp.testing.svc.cluster.local: hcp.testing.svc.cluster.local
    listener.cattle.io/cn-hcp.v2.platform9.beer: hcp.v2.platform9.beer
    listener.cattle.io/cn-kubernetes: kubernetes
    listener.cattle.io/cn-kubernetes.default: kubernetes.default
    listener.cattle.io/cn-kubernetes.default.svc.cluster.local: kubernetes.default.svc.cluster.local
    listener.cattle.io/cn-localhost: localhost
    listener.cattle.io/cn-v2.platform9.beer: v2.platform9.beer
```

I at first used a nodeport Service to have agents talk to the k3s server, and that works fine. It must be something to do with the TLS termination, but unsure why that would cause issues

**Comment by CamelCaseNotation** [comment]
I wonder what's happening is the Host header is being set to `127.0.0.1` so it's not matching my Ambassador TLSContext `hosts` value, so it's not choosing the correct certs & route? This is likely a me problem. Either way, being able to disable the agent load balancer would be nice if I've ensured my ServerURL is a load balancer address itself

**Comment by CamelCaseNotation** [comment]
Actually, the SNI doesn't seem to be the problem. I configured my Mapping/TLSContext to route to my k3s server if the host matches the exact "host" that the agent is presumably using when attempting to connect to the ServerURL through the local load balancer, and that did not work. However a curl _did_ show it working.

```
# This works as expected after configuring the above resources to map requests whose host
# matches the IP:PORT that the local load balancer is running as on the agent trying to join
curl -H "Host: 127.0.0.1:32864" -v -k https://hcp.v2.platform9.beer/cacerts

# Still seeing this repeated message from the k3s-agent logs
Dec 18 00:49:23 worker k3s[12447]: time="2019-12-18T00:49:23.019141506Z" level=error msg="failed to get CA certs at https://127.0.0.1:32864/cacerts: Get https://127.0.0.1:32864/cacerts: EOF"
```

**Comment by erikwilson** [comment]
Not sure what is gong on here, but I am guessing it is an ambassador configuration issue. Does it work using the server url as `https://server-ip:6443/`? Does it work if you do not set any tls config but use the ambassador tcp round_robin load_balancer policy? Are you running ambassador in the k3s cluster you are connecting the agent to? Is this multi-master or single master cluster? 

There is also a `--tls-san` flag for the server that can be set to `hcp.v2.platform9.beer` in case it is helpful.

**Comment by CamelCaseNotation** [comment]
> There is also a --tls-san flag for the server that can be set to hcp.v2.platform9.beer in case it is helpful.

this is set, so all SAN issues have been ruled out

> Does it work using the server url as https://server-ip:6443/?
yup, sure does! When I used NodePort Service it worked fine, so I'm sure it's something to do with the SNI configuration. If that _is_ the issue, then I'll have more details to post about what can be done on the k3s side

> Are you running ambassador in the k3s cluster you are connecting the agent to?
nope

> Is this multi-master or single master cluster?
is this relevant? there's just 1 k3s server atm, but I've tested agents are able to join the cluster when the `ServerURL` is a NodePort Service address and I'm running 3 replicas of the k3s server Deployment

**Comment by erikwilson** [comment]
Cool, yah some of those are probably silly questions but just trying to understand the setup more. Sorry I don't have a better idea what is going on, the only other thing I can think of is to use the `openssl` command to see if you can get some more debugging information.

**Comment by CamelCaseNotation** [comment]
So, I think I know what's going on here.
For starters, my above curl command using the Host header is not the correct way to debug what's going on with an SNI-enabled server. See [this great article](https://hacksbrain.com/2018/08/27/testing-sni-enabled-servers-with-curl/)

I created a `Mapping` like so:
```
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  hcp-testing
  namespace:  testing
spec:
  prefix: /
  service: https://hcp.testing:6443
  host: "hcp.v2.platform9.beer:32864"
```
The reason for specifying `32864` in my host in the `Mapping` is cuz you can't add a port after `127.0.0.1` in curl's `--resolve` flag, but that's the port where the proxy is listening.

I then ran this command from the VM where k3s agent is running:
```
curl -v -k --resolve hcp.v2.platform9.beer:32864:127.0.0.1 https://hcp.v2.platform9.beer:32864/cacerts
```

### In ambassador's debug logs, I can see the following logs when making the curl request above:
```
[2019-12-18 02:59:27.688][624][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:72] tls inspector: new connection accepted
[2019-12-18 02:59:27.688][624][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:142] tls:onServerName(), requestedServerName: hcp.v2.platform9.beer
```

I can also see log messages that are spaced out 2s apart, which is the amount of time k3s waits before issuing another request to `/cacerts` as part of the `NormalizeAndValidateTokenForUser` func [here](https://github.com/rancher/k3s/blob/d4959d53aff20e9242ff3896f89a5c5d2f44ebf2/pkg/agent/run.go#L127)
```
[2019-12-18 03:04:58.317][624][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:72] tls inspector: new connection accepted
[2019-12-18 03:04:58.317][624][debug][main] [source/server/connection_handler_impl.cc:276] closing connection: no matching filter chain found
[2019-12-18 03:05:00.419][624][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:72] tls inspector: new connection accepted
[2019-12-18 03:05:00.419][624][debug][main] [source/server/connection_handler_impl.cc:276] closing connection: no matching filter chain found
```

These timestamps match the k3s agent logs:
```
Dec 18 03:04:58 worker k3s[12447]: time="2019-12-18T03:04:58.413428695Z" level=error msg="failed to get CA certs at https://127.0.0.1:32864/cacerts: Get https://127.0.0.1:32864
Dec 18 03:05:00 worker k3s[12447]: time="2019-12-18T03:05:00.420103145Z" level=error msg="failed to get CA certs at https://127.0.0.1:32864/cacerts: Get https://127.0.0.1:32864
```

## What I think is going on in the code
The load balancer proxy implementation in k3s for agents is using google's [tcpproxy library](https://godoc.org/github.com/google/tcpproxy). Note the comment in the [Conn struct above the HostName field](https://godoc.org/github.com/google/tcpproxy#Conn)
> In the case of a fixed route, i.e. those created with AddRoute(), this will always be empty.

[The proxy uses `AddRoute`](https://github.com/rancher/k3s/blob/d4959d53aff20e9242ff3896f89a5c5d2f44ebf2/pkg/agent/loadbalancer/loadbalancer.go#L75)

I'm not sure how this library works, but I assume if you used [`AddSNIRoute`](https://godoc.org/github.com/google/tcpproxy#Proxy.AddSNIRoute) then... well idk. The goal, at least in my case, is to have a request which is sent to the local proxy on the agent machine include an SNI which matches the `ServerURL`

**Comment by erikwilson** [comment]
That may work, but I would be surprised because as far as I can tell AddSNIRoute would not fix the issue. We don't really need to inspect traffic and route differently depending on the SNI match. The load balancer will fail over to the next entry on TCP error, but the only load balancer entry at that point is the server url, so that is where it should always connect to.

**Comment by CamelCaseNotation** [comment]
You know what, I added a `TCPMapping` and that solved my problem LOL

**Comment by CamelCaseNotation** [comment]
Actually I take that back, I still had the nodeport service configured, so that's why it worked. Making k3s server service routable only via Mapping/TCPMapping doesn't seem to work with the k3s agent proxy

**Comment by erikwilson** [comment]
As far as connectivity, ensuring that TCP load balancing works is a good first step. If possible ambassadar should be configured to just deal with TCP rather than trying to deal with SNI routing, to at least eliminate that as an issue. It sounds like SNI inspection of hostname vs 127.0.0.1 was the original problem (maybe combined with a need for sticky sessions in the ambassador instance), but without the nodeport service you are now running into a connectivity issue.

**Comment by carneiroskeeled** [comment]
Hi @texascloud, did you manage to solve your issue? I believe I am having the exact same issue.

To try out the new k3s I deployed the server (both with the agent enabled and disabled) in an already existing Kubernetes cluster.
When I try to access the `/cacerts` directly (without the load balancer) it works and I have also tried with k3s v0.6.0 (a version without the load balancer) and it also works.
This might come as a very newbie question @erikwilson , but would it be possible that the load balancer removes the host header therefore not reaching the destination?

**Comment by erikwilson** [comment]
It is just a simple TCP load balancer that does no packet inspection.

When you say you can access `/cacerts` directly, this is from the agent? Are you using the same IP that the load balancer on the agent uses, the endpoints defined in k8s?

**Comment by carneiroskeeled** [comment]
```
# curl https://ENDPOINT_HERE/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
# sudo ./k3s agent --token TOKEN_HERE --server https://ENDPOINT_HERE/
INFO[2020-10-30T19:01:45.746139400Z] Starting k3s agent v1.18.10+k3s1 (6fa97306)
INFO[2020-10-30T19:01:45.747071100Z] module overlay was already loaded
INFO[2020-10-30T19:01:45.747167100Z] module nf_conntrack was already loaded
WARN[2020-10-30T19:01:45.748498100Z] failed to start br_netfilter module
INFO[2020-10-30T19:01:45.751322300Z] Running load balancer 127.0.0.1:34291 -> [ENDPOINT_HERE:443]
ERRO[2020-10-30T19:01:46.172093500Z] failed to get CA certs at https://127.0.0.1:34291/cacerts: https://127.0.0.1:34291/cacerts: 404 Not Found
ERRO[2020-10-30T19:01:48.485172500Z] failed to get CA certs at https://127.0.0.1:34291/cacerts: https://127.0.0.1:34291/cacerts: 404 Not Found
```

I censored the TOKEN and ENDPOINT. The 401 is what it is supposed to happen because it has the default basic authentication, if I pass it I can access the `/cacerts`.

**Comment by erikwilson** [comment]
Ah, so it sounds like you are also pointing at a TLS terminating load balancer? Is it also ambassador?

**Comment by brandond** [comment]
I notice that your load-balancer is on 443. Are you redirecting 443 to 6443 on the backend? Is there some reason you can't or don't want to retain the normal k3s server port?

**Comment by carneiroskeeled** [comment]
It is not ambassador @erikwilson, it is a nginx ingress with a let's encrypt certificate.

k3s server container is running in port 6443 @brandond, with a ingress exposing it (443), is it a problem?

Must I expose the server directly instead of having the ingress in-front?

**Comment by brandond** [comment]
I would recommend leaving it on the proper port rather than moving it to 443. Also, Kubernetes uses certificate authentication. If you put a SSL-terminating load-balancer in front of it, it will break that. Can you try moving it to port 6443 and switching it to a L4 load-balancer configuration that does not offload SSL handling?
