### ISSUE TITLE
Documenting network flags for https://get.k3s.io install

### ISSUE THREAD

**Issue by mangelajo** [k3s-io/k3s#1224]
I'm playing around with submariner and k3s lately, and something I miss from the POV of K3S documentation is how to deploy with different ClusterIP CIDRs and Pod CIDRs to avoid overlapping issues.

Can this be documented somewhere?

Thanks

**Comment by cwayne18** [comment]
Is this still needed? @catherineluse

**Comment by dereknola** [comment]
This is core K8s functionality, that is document well within the K8s upstream docs ([here](https://kubernetes.io/docs/concepts/services-networking/) and [here](https://kubernetes.io/docs/concepts/cluster-administration/networking/)). There is no need to specifically call out this functionality in K3s.
