### ISSUE TITLE
DQlite connects to itself

### ISSUE THREAD

**Issue by PerryTheDuckHolder** [k3s-io/k3s#1226]
**Version:**

k3s v1.0.0 (18bd921)

**Describe the bug**

Trying to setup HA cluster with DQlite

Started first master with
```
k3s server --cluster-init
```

And restarted this service several times

Now, at start of service i see only this line:
```
Testing connection to peers [10.20.30.40:6443] 
```
(10.20.30.40 - this node IP, seems like this node trying connect to itself, but it fails, because dqlite is still not initialized?)

After changing verbosity (-v 100) i see addictional lines on top of output, but nothing more (ip addresses is censoured):
```
Interface "enp4s0" has 3 addresses :[10.20.30.40/32 2a01:fff:fff:ffff::2/64 fe80::ffff:ffff:ffff:2291/64].
interface.go:223] Checking addr  10.20.30.40/32.
interface.go:230] IP found 10.20.30.40
interface.go:262] Found valid IPv4 address 10.20.30.40 for interface "enp4s0".
interface.go:414] Found active IP 10.20.30.40
```

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by PerryTheDuckHolder** [comment]
Built master branch (k3s v1.17.0+7e18a8d6e0 (7e18a8d6)) and added some debug output, now i see that process doesn't go further than this line
https://github.com/rancher/k3s/blob/master/pkg/dqlite/join.go

**Comment by philkry** [comment]
did you ever figure this out?
I am facing the exact same issue with my 3 node RPI cluster in k3s version v1.17.2+k3s1 (cdab19b0)

my node does hang at this stage and does not continue at all:

> /usr/local/bin/k3s server --cluster-init --tls-san 192.168.1.241
> INFO[2020-02-23T15:26:49.189680467+01:00] Starting k3s v1.17.2+k3s1 (cdab19b0)
> INFO[2020-02-23T15:26:50.496298218+01:00] Testing connection to peers [192.168.1.241:6443 192.168.1.243:6443 192.168.1.242:6443

**Comment by soilsk** [comment]
same with RPI4 x 3 HA masters. After a few hours (i think random) one of masters change state to NotReady.
