### ISSUE TITLE
Bundle helm executable in k3s

### ISSUE THREAD

**Issue by rektide** [k3s-io/k3s#1237]
**Is your feature request related to a problem? Please describe.**
Currently k3s has tools to load helm charts at startup. But it's less clear what to do to manage helm after that fact. Tickets such as #1203 show that users aren't sure what to do with their loaded helm charts.

**Describe the solution you'd like**
It would be neat if helm were bundled in the k3s executable. This would make it clear that helm isn't just a tool for getting started with k3s, but also a tool for managing k3s once started.

**Describe alternatives you've considered**
Users can download their own helm releases. This is very easy to do, and with helm v3, there's no tiller or other onerous install issues to deal with: it's just an executable, & easy to work with, once dropped into a /usr/bin or what not.

**Additional context**
This is just an idea that ocured while reading #1203, & it for sure does not seem like a complete answer to that ticket. But I thought it might be worth raising. Happy to re-assess. Thanks.

**Comment by sotiris84** [comment]
I would agree that there is a confusion on how to use helm with K3S. I would suggest what the OP said.

**Comment by txomon** [comment]
Myself being interested on keeping k3s as small as possible, I would actually advocate to remove helm completely. With v3, where there is no server side process to be run, this is a fantastic opportunity to remove helm completely, or at least to be able to build k3s without helm.

**Comment by rektide** [comment]
> Myself being interested on keeping k3s as small as possible,

Why? A full helm release is 11MB. I expect much of that is already included in k3s & that this ticket is mostly trying to surface that dependency.

>  I would actually advocate to remove helm completely. 

I for one think Helm is a huge value add. The ability to bootstrap K3S clusters with Helm charts at startup helps all sorts of people. It's also how [traefik](https://github.com/rancher/k3s/blob/master/manifests/traefik.yaml) is loaded right now.

Helm, atm, seems like the chief means #k8s has to deploy packages of manifests, & it has huge adoption. It makes sense to use Helm at initialization of the k3s cluster, & it makes further sense to provide operational capabilities over Helm, which is what this ticket proposes doing.

> With v3, where there is no server side process to be run, this is a fantastic opportunity

I do not see why A (v3 not needing a management process) a leads you to B (it could be removed). If the burden to operate is even lower, if the complexity of having Helm working on k3s is so much lower, why is that an incentive to drop it?

**Comment by txomon** [comment]
The reason why I'm proposing to remove helm is to reduce the memory footprint of the k3s executable. I agree that using helm is really convenient, but I wouldn't like to increase the VSZ of the binary for a client side feature.

To my understanding, we would have a service (k3s) running with some dead code (helm) that isn't used unless a user invokes a command within the server.
