### ISSUE TITLE
Prometheus scraping configuration

### ISSUE THREAD

**Issue by REBELinBLUE** [k3s-io/k3s#1244]
Not really a feature request but obviously since the controller manager and scheduler aren't deployed as pods like with `kubeadm` this Prometheus configuration doesn't work https://github.com/REBELinBLUE/k8s-on-hypriot/blob/master/deployments/monitoring/prometheus/config/prometheus.yaml#L409-L467 for scraping the metrics

Is there a way to get them? Does anyone have an example configuration file?

**Comment by NicklasWallgren** [comment]
Take a look at https://github.com/rancher/k3s/issues/1562 if you are looking for a solution.
