### ISSUE TITLE
Documentation about the ipsec cni

### ISSUE THREAD

**Issue by drym3r** [k3s-io/k3s#1245]
Hi

I've searched but I can't find information about the ipsec cni. I assumed that it wouldn't support NetworkPolicies, but I was gladly surprised because it does. This makes me see that I don't really know how it works, aside that it does encrypt traffic between nodes. Is there's information about it, could you point to it? If not, it could be done? 
Thanks

**Comment by dereknola** [comment]
We have deprecated ipsec support and are removing it in 1.27. There is a section in the docs on this https://docs.k3s.io/installation/network-options#migrating-from-wireguard-or-ipsec-to-wireguard-native. As such, there is no need to add info about a old feature.
