### ISSUE TITLE
How to specify Kubernetes version?

### ISSUE THREAD

**Issue by ogbofjnr** [k3s-io/k3s#1248]
Is it possible to specify Kubernetes version ?

**Comment by dweomer** [comment]
k3s v1.0.x was built with k8s v1.16.x.
k3s v1.17.0+k3s.1 was built with k8s v1.17.0. from this point forward, k3s releases will be tagged according to the version of k8s they were built with/against.

see https://github.com/rancher/k3s/releases/tag/v1.17.0%2Bk3s.1

---

![Screen Shot 2020-01-14 at 10 13 44 AM](https://user-images.githubusercontent.com/1033444/72365998-9e89cc00-36b6-11ea-9618-acb6d8e2647f.png)
