### ISSUE TITLE
Unable to run k3s on a GCE f1-micro 

### ISSUE THREAD

**Issue by ainiml** [k3s-io/k3s#1249]
**Describe the bug**
It appears to use too many resources for the instance to be able to respond. For example, you can no longer SSH to the instance after installing k3s.

**To Reproduce**
`curl -sfL https://get.k3s.io | sh -`

**Expected behavior**
Less resource intensive 

**Actual behavior**
![image](https://user-images.githubusercontent.com/28725423/71525132-6f91ee80-289e-11ea-847a-984121842368.png)
![image](https://user-images.githubusercontent.com/28725423/71525163-7e78a100-289e-11ea-8dca-51439f415803.png)
![image](https://user-images.githubusercontent.com/28725423/71525190-90f2da80-289e-11ea-99dc-cd4c105940f3.png)
![image](https://user-images.githubusercontent.com/28725423/71525202-9bad6f80-289e-11ea-9919-31a84bf7904a.png)

**Additional context**

**Comment by DavidZisky** [comment]
K3S requirement:

1 CPU and 512MB RAM

f1-micro:

0.2CPU and 0.6GB RAM

so it's just not gonna work...
https://rancher.com/docs/k3s/latest/en/installation/node-requirements/#hardware

**Comment by ainiml** [comment]
> K3S requirement:
> 
> 1 CPU and 512MB RAM
> 
> f1-micro:
> 
> 0.2CPU and 0.6GB RAM
> 
> so it's just not gonna work...
> https://rancher.com/docs/k3s/latest/en/installation/node-requirements/#hardware

IOT devices can get pretty small too. 

Okay, that's a bit interesting. So it's limited in the types of IOT devices k3s can work on. 

I was hoping it was flexible for _all_ IOT devices

**Comment by DavidZisky** [comment]
> > K3S requirement:
> > 1 CPU and 512MB RAM
> > f1-micro:
> > 0.2CPU and 0.6GB RAM
> > so it's just not gonna work...
> > https://rancher.com/docs/k3s/latest/en/installation/node-requirements/#hardware
> 
> IOT devices can get pretty small too.
> 
> Okay, that's a bit interesting. So it's limited in the types of IOT devices k3s can work on.
> 
> I was hoping it was flexible for _all_ IOT devices

I believe it would work fine on IoT devices (that's what k3s was actually build for). The problem here is that k3s sees 1vCPU (because you can't have 0.2 CPU in linux system) but is allowed to use 0.2 only so it may confuse k3s probably. If you have some not so powerful IoT device you will be able to use whole 1 CPU even if it's very slow.

**Comment by ainiml** [comment]
> > > K3S requirement:
> > > 1 CPU and 512MB RAM
> > > f1-micro:
> > > 0.2CPU and 0.6GB RAM
> > > so it's just not gonna work...
> > > https://rancher.com/docs/k3s/latest/en/installation/node-requirements/#hardware
> > 
> > 
> > IOT devices can get pretty small too.
> > Okay, that's a bit interesting. So it's limited in the types of IOT devices k3s can work on.
> > I was hoping it was flexible for _all_ IOT devices
> 
> I believe it would work fine on IoT devices (that's what k3s was actually build for). The problem here is that k3s sees 1vCPU (because you can't have 0.2 CPU in linux system) but is allowed to use 0.2 only so it may confuse k3s probably. If you have some not so powerful IoT device you will be able to use whole 1 CPU even if it's very slow.

Very true, very technical as well. 

From a user stand point, we're just hopping I'll just work
