### ISSUE TITLE
Docs: Clarify the need for a firewall if ipsec or wg is used as flannel backend & default ipsec

### ISSUE THREAD

**Issue by desmap** [k3s-io/k3s#1252]
From reading the docs and some issues, I assume that the ports 6443 and 8472 do not need to be blocked via a firewall if k3s server is started with `--flannel-backend=ipsec` or wg, right?

I am not 100% sure and it would be good to clarify this more in the docs. Besides, if I use ufw on debian buster to just deny mentioned ports ufw wont let anything through anymore and just letting k3s running with IPSec seems to be the easier

defaulting ipsec is anyway on the roadmap, the sooner the better.

**Comment by dereknola** [comment]
We have deprecated ipsec support and are removing it in 1.27. There is a section in the docs on this https://docs.k3s.io/installation/network-options#migrating-from-wireguard-or-ipsec-to-wireguard-native. As such, there is no need to add info about a old feature.

In terms of firewall exceptions, we have a whole table now about ports and their use. https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-server-nodes
