### ISSUE TITLE
Interactions with kubectl very slow compared to k3s kubectl

### ISSUE THREAD

**Issue by brennantaylor** [k3s-io/k3s#1255]
**Version:**
```bash
-> k3s -v
k3s version v1.0.1 (e94a3c60)
-> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Describe the bug**
While using the upstream kubectl, running commands that scan multiple api-resources by label run very slowly. The more api-resources that are scanned the more time adds up even with very few objects in the k8s api.

**To Reproduce**
For example some output. All running on the host machine running the k3s server.
```
-> time env KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get all
3 pods
11 services
3 jobs

real    0m59.446s
-> time k3s kubectl get all
3 pods
11 services
3 jobs

real    0m2.299s
```

**Expected behavior**
Expect this to be fast. It should just be a client/server interaction.

**Actual behavior**
Super slow.

**Additional context**
Running on ubuntu on an r4.xlarge ec2 instance. Lots of cpu and ram however no physical storage, EBS only. I even mounted `/var/lib/rancher` as a ramdisk with lots of room and see no noticeable performance improvement.

Installed with 
```
curl -sfL https://get.k3s.io | env K3S_KUBECONFIG_MODE="777" sh -s - server --no-deploy=traefik --no-deploy=servicelb --no-deploy=local-storage --no-deploy=metrics-server
```

**Comment by verbunk** [comment]
I'm seeing this as well but in my case its 1m3s for both k3s kubectl get all and kubectl get all.

**Comment by msm-code** [comment]
@verbunk I had a similar problem and solved it with

```
sudo chown msm:msm ~/.kube/ -R
```

(The problem was caused by tons of -EPERM on cache reads).

This is probably not related to the original error, because in my case both commands were slow.

**Comment by anuragvohraec** [comment]
> @verbunk I had a similar problem and solved it with
> 
> ```
> sudo chown msm:msm ~/.kube/ -R
> ```
> 
> Substitute your username of course.
> 
> (The problem was caused by tons of -EPERM on cache reads).
> 
> This is probably not related to the original error, because in my case both commands were slow.

This solved my problem!, thank you
