### ISSUE TITLE
Documentation/info about switchen between storage backends

### ISSUE THREAD

**Issue by BlackTurtle123** [k3s-io/k3s#1257]
I started a k3s cluster, single node, single master. Now I see that k3s support postgresql as backend, and this you can build HA-master nodes.
I was looking in a migration path, or some info around this, but I couldn't find anything

Write clear information about how we can migrate from sqllite to postgresql

**Comment by davidnuzik** [comment]
There currently isn't a path for migration. We have plans to add disaster recovery options (backup/snapshot/restore) but when we implement this it may still be difficult to move from one database to another I believe due to different schemas for the db.
We have some more research to do in this area -- perhaps there is a simple solution that will work.

I will be switching the labels in this issue from documentation to enhancement as this requires work to implement the capability.

**Comment by BlackTurtle123** [comment]
Okay thanks for the update.
I believe it might at least be usefull to provide a path towards k3s internal data store which you guys are trying to make the default.

**Comment by mogoman** [comment]
I managed to migrate a brand new installation from sqlite to Postgres using this command:

```
sqlite3 /var/lib/rancher/k3s/server/db/state.db .dump | egrep 'INSERT INTO "kine"|BEGIN TRANSACTION|COMMIT;' | sed "s/X'/'\\\\x/g" | sed "s/NULL)/'\\\\x')/g" | psql -U k3s k3s
```

The pg schema I just ```pg_dump```ed from a fresh install.

Older installs have a "key_value" table in sqlite, however this doesn't seem to be a problem as it is migrated:
https://github.com/rancher/k3s/blob/b56e52ee9652a476b4e113fe8e3f64afbee7cf3e/vendor/github.com/rancher/kine/pkg/drivers/generic/generic.go#L105
(side note, the old key_value table isn't dropped from sqlite in the migration)

I tried the same on an older (pre v0.9.0) sqlite db and it imported without errors. I'm a bit apprehensive to fire it up and destroy our prod instance - call me scared. I'll try creating the DB on a separate system and see if kubectl lists anything. 

1. Does this approach sound sensible?
2. In sqlite "old_value" is NULL, but in PG it is "\x" can PG handle NULL?

**Comment by maxirus** [comment]
@mogoman Did you ever test your idea in Prod?

**Comment by brandond** [comment]
There is now native support for migrating from sqlite to embedded etcd; but not for other storage backends.

**Comment by maxirus** [comment]
@brandond that's awesome! I saw #3982 but nothing in the Docs on the steps to accomplish this. For myself and others that my find this issue, is it simply passing the `--cluster-init` on the master, during an upgrade?

**Comment by brandond** [comment]
Just restart it with that flag when running a version that's supports migration, yeah.

**Comment by mogoman** [comment]
ok thanks for that. I will test on our older test cluster and report back

**Comment by caroline-suse-rancher** [comment]
Closing due to age, and because we have support for migrating from sqlite to etcd, and documentation that references restore/backup options for other external datastores.
