### ISSUE TITLE
Rancher's Authorized Cluster Endpoint

### ISSUE THREAD

**Issue by shinebayar-g** [k3s-io/k3s#1260]
**Is your feature request related to a problem? Please describe.**
Rancher's [authorized cluster endpoint](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint) allows connection to kubernetes master directly bypassing rancher server. It's very handy feature for us. However it is only available for Rancher bootstrapped kubernetes clusters. (Not imported, nor hosted).

**Describe the solution you'd like**
Is it possible to support authorized cluster endpoint feature in rancher? I guess it would be possible if Rancher supports creating k3s cluster from Rancher UI itself.

**Comment by cwayne18** [comment]
This seems like it should be opened against Rancher manager itself, so I'll close it out here.
