### ISSUE TITLE
Metric Server Authentication?

### ISSUE THREAD

**Issue by sdan** [k3s-io/k3s#1262]
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**
Username/Password auth is required to access 
`https://ip:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`
What is the username/pass?

**To Reproduce**
Go to `https://ip:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`

**Comment by ngobach** [comment]
Hello,
This URL is a proxy to Kubernetes service. However in your case it pointed to **kube-dns**, which doesn't speak HTTP(S) so I don't think this is what you are looking for.
For your question, k3s use password based authentication and you can found the username and password for admin user in **/etc/rancher/k3s/k3s.yaml** file. This credentials will allow you to access k3s APIs.
