### ISSUE TITLE
Can't start agent: Failed to connect to proxy too many colons in address

### ISSUE THREAD

**Issue by JorisBolsens** [k3s-io/k3s#1268]
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**
k3s agent fails to start with an error in ws proxy

**To Reproduce**
run `sudo k3s agent --server https://server:6443 --token mytoken`

**Expected behavior**
k3s starts and joins the master node

**Actual behavior**
the agent fails to join the master and shows the error:
```
$ sudo k3s agent --server https://server:6443 --token token
INFO[2020-01-05T19:00:29.662843946Z] Starting k3s agent v1.0.1 (e94a3c60)         
WARN[2020-01-05T19:00:29.664065519Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
INFO[2020-01-05T19:00:29.664333244Z] module overlay was already loaded            
WARN[2020-01-05T19:00:29.693394482Z] failed to start nf_conntrack module          
WARN[2020-01-05T19:00:29.722644463Z] failed to start br_netfilter module          
WARN[2020-01-05T19:00:29.723234986Z] failed to write value 1 at /proc/sys/net/ipv6/conf/all/forwarding: open /proc/sys/net/ipv6/conf/all/forwarding: no such file or directory 
WARN[2020-01-05T19:00:29.723454442Z] failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory 
WARN[2020-01-05T19:00:29.723656460Z] failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-ip6tables: open /proc/sys/net/bridge/bridge-nf-call-ip6tables: no such file or directory 
INFO[2020-01-05T19:00:29.725222696Z] Running load balancer 127.0.0.1:37713 -> [2600:1700:65a0:b3c0::16:6443 server:6443] 
INFO[2020-01-05T19:00:31.246795196Z] Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log 
INFO[2020-01-05T19:00:31.247721523Z] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd 
INFO[2020-01-05T19:00:31.468078384Z] Connecting to proxy                           url="wss://2600:1700:65a0:b3c0::16:6443/v1-k3s/connect"
ERRO[2020-01-05T19:00:31.468589581Z] Failed to connect to proxy                    error="dial tcp: address 2600:1700:65a0:b3c0::16:6443: too many colons in address"
ERRO[2020-01-05T19:00:31.468783996Z] Remotedialer proxy error                      error="dial tcp: address 2600:1700:65a0:b3c0::16:6443: too many colons in address"
```

**Additional context**
I am attempting to run this on a Pynq-Z1 which runs a modified version of Ubuntu bionic 
```
$ cat /proc/cmdline 
root=/dev/mmcblk0p2 rw earlyprintk rootfstype=ext4 rootwait devtmpfs.mount=1 uio_pdrv_genirq.of_id="generic-uio" clk_ignore_unused cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory ipv6.disable=1
```
probably related to rancher/k3s#1191 however the workaround doesn't work for me

**Comment by JorisBolsens** [comment]
I managed to workaround this by telling the master to advertise it's local ipv4 address.

**Comment by j-landru** [comment]
```tcp: address 2600:1700:65a0:b3c0::16:6443: too many colons in address```

I think this error message could be related to an URI syntax violation. According to RFC3986 "Uniform Resource Identifier (URI): Generic Syntax" : in an URI IPv6 literral address has to be square bracket '[' ']' enclosed, as colon ':' is ambigous because it's the 16-bit word separator in IPv6 address notation (RFC4291) as well the service port separator in URI syntax. In log above ```wss://2600:1700:65a0:b3c0::16:6443``` is ambigous :  does it mean a standard port (```443```) connection on the host addressed ```2600:1700:65a0:b3c0:0:0:16:6443``` or alternatively a ```6443``` port connection on the host addressed ```2600:1700:65a0:b3c0:0:0:0:16``` ? To to remove the ambiguity the RFC3986 requires to enclose the IPv6 address between square brackets, so the URL should be ```wss://[2600:1700:65a0:b3c0::16]:6443```
Does ```sudo k3s agent --server https://[server]:6443 --token mytoken``` (or mabye ```sudo k3s agent --server https://\[server\]:6443 --token mytoken``` if brackets need to be bash escaped) command could solve that IPv6 connection error ?
If so, the k3s / k8s code should perhaps be aware of enclosing IPv6 addresses in square brackets when formatting an IPv6 service endpoint.

**Comment by dereknola** [comment]
Closing this as Out of Date, https://github.com/k3s-io/k3s/pull/1198 fixed this issue. v1.19 is also EOL.
