### ISSUE TITLE
[Documentation] move info from Advanced section about kubectl/helm to new section

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1274]
Based on a slack discusion 1/6/20 with Catherine.

We should consider moving the docs around a little with regard to sections on the /advanced/ page that talk about using helm and setting up the kubeconfig. This could perhaps be its own parent page and a go-to for users to:

- Properly set up KUBECONFIG env var or how to use --kubeconfig flag for kubectl and helm (with examples)
- How to deploy apps (with examples) using both traditional helm3 or by placing yaml on disk in the /manifests/ folder (auto-deploying apps)

The idea is that it should be a go-to place that talks about how to manage the cluster at a low level such as with kubectl and also how to deploy apps (with examples) using helm or manifests. This could be a good place to provide a few examples so users can actually get started running stuff on their k3s cluster.

**Comment by catherineluse** [comment]
I have added the following pages:

- Cluster access (about kubectl/kubeconfig): https://rancher.com/docs/k3s/latest/en/cluster-access/
- Helm: https://rancher.com/docs/k3s/latest/en/helm/

The Helm page could have some more detail and examples though.

**Comment by dereknola** [comment]
This was completed some time ago. We now have https://docs.k3s.io/helm and a section on using the kubeconfig https://docs.k3s.io/cluster-access
