### ISSUE TITLE
K3S can't pull  multiarch images due tu `failed to unpack image on snapshotter overlayfs: `

### ISSUE THREAD

**Issue by kamilgregorczyk** [k3s-io/k3s#1278]
For some reason, K3S seems to be failing to download the image that I build with `docker buildx build....` https://hub.docker.com/repository/docker/uniqe15/event-sourced-bank/tags?page=1 

I'm using k3s  (k3s version v1.0.0 (18bd921c))with containerd

```
➜  event-sourced-bank3 git:(master) ✗ kubectl --insecure-skip-tls-verify describe pod event-sourced-bank-77f5c8cc65-f66lj

Name:         event-sourced-bank-77f5c8cc65-f66lj
Namespace:    default
Priority:     0
Node:         worker1/192.168.0.202
Start Time:   Tue, 07 Jan 2020 10:55:45 +0000
Labels:       app=event-sourced-bank
              pod-template-hash=77f5c8cc65
Annotations:  <none>
Status:       Pending
IP:           10.42.1.76
IPs:
  IP:           10.42.1.76
Controlled By:  ReplicaSet/event-sourced-bank-77f5c8cc65
Containers:
  event-sourced-bank:
    Container ID:   
    Image:          uniqe15/event-sourced-bank:latest
    Image ID:       
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rb494 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-rb494:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rb494
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned default/event-sourced-bank-77f5c8cc65-f66lj to worker1
  Normal   Pulling    3m40s (x4 over 5m6s)  kubelet, worker1   Pulling image "uniqe15/event-sourced-bank:latest"
  Warning  Failed     3m39s (x4 over 5m5s)  kubelet, worker1   Failed to pull image "uniqe15/event-sourced-bank:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/uniqe15/event-sourced-bank:latest": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:de324984a3ba9bde1a2bc5230ca8754a2d3e055b301a2301bfd9a8115a6822a5: not found
  Warning  Failed     3m39s (x4 over 5m5s)  kubelet, worker1   Error: ErrImagePull
  Normal   BackOff    3m24s (x6 over 5m4s)  kubelet, worker1   Back-off pulling image "uniqe15/event-sourced-bank:latest"
  Warning  Failed     3m13s (x7 over 5m4s)  kubelet, worker1   Error: ImagePullBackOff
```

**Comment by kamilgregorczyk** [comment]
works only with just one arch (armv8 for e.g.)

**Comment by dweomer** [comment]
@kamilgregorczyk `uniqe15/event-sourced-bank` doesn't look to be a multi-arch image:

![Screen Shot 2020-01-14 at 9 36 17 AM](https://user-images.githubusercontent.com/1033444/72363202-ab57f100-36b1-11ea-8b98-ad720efb4ec7.png)

---

Is the log you provided from a and arm64 node? If not, it looks to be working as expected.

**Comment by kamilgregorczyk** [comment]
Ah, I changed it to see if arm only would woke, will rebuild in 1-2 hours

**Comment by kamilgregorczyk** [comment]
@dweomer done

**Comment by dweomer** [comment]
@kamilgregorczyk these worked for me on a k3OS amd64 VM built from master (k3s v1.0.1):
- `sudo ctr image pull docker.io/uniqe15/event-sourced-bank:latest`
- `sudo ctr image pull --platform linux/arm64 docker.io/uniqe15/event-sourced-bank:latest`

also rebuilt against k3s v1.0.0 with same results.

---

have you tried again on both platforms and asserted that things are still broken? if your pod is still broken please run `k3s ctr image pull docker.io/uniqe15/event-sourced-bank:latest` and share the results.

**Comment by kamilgregorczyk** [comment]
I'm reworking my cluster as I had raspberry pi image which limited the cluster to only armv7, I'm now redoing to on ubuntu server to have arm64, will try once it's up and running

**Comment by hasheddan** [comment]
@kamilgregorczyk any updates here? I have encountered the same issue using a multi-arch image. Seems this was an underlying issue with containerd that appears to have been fixed here: https://github.com/containerd/containerd/pull/3484

**Comment by kamilgregorczyk** [comment]
I created two separate images for different archs

**Comment by dalekurt** [comment]
@kamilgregorczyk I'm also interested in your solution if you have one. I am running K3s on Raspberry Pi cluster and I'm trying to deploy `rook/ceph` Docker image and having the same results. 

Model: Raspberry Pi 3 Model B Plus Rev 1.3
Processor model: ARMv7 Processor rev 4 (v7l)
OS: Raspbian Buster
K3S version: v1.17.0+k3s.1

**Comment by cloudeyes** [comment]
I have the same issue. I was working on a multi-arch image `cloudeyes/hell-node` and got this error.

![image](https://user-images.githubusercontent.com/2653362/77232144-ad26bf00-6be2-11ea-9eb7-f020ab4ecfba.png)

**Comment by David-Igou** [comment]
Experiencing this issue on Raspberry Pi 3 B+'s running k3s. Deployed fine on my 4's.

**Comment by kamilgregorczyk** [comment]
I belive 3b+ has no arm64  support and you need armv7 image for 3B+

**Comment by dalekurt** [comment]
> Experiencing this issue on Raspberry Pi 3 B+'s running k3s. Deployed fine on my 4's.
> 
> The image I'm experiencing the failure with is cattle-node-agent

I recently bought Raspberry 4's and I now have K3s running on them, however I'm experiencing the same issue. 

```
Failed to pull image "rook/ceph:v1.0.6": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rook/ceph:v1.0.6": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:6c4475a7dc2c123f3f150100824e05d39270b5297ad0594abfe61b492cf5aff7: not found
```

**Comment by onedr0p** [comment]
@dalekurt what OS are you using on the Pi? Raspbian will not work.

**Comment by brandond** [comment]
That means there's no docker.io/rook/ceph:v1.0.6 image for your architecture.

**Comment by dalekurt** [comment]
@onedr0p You hit the nail on the head with that, I reinstalled the OS (Ubuntu 64-bit) and I’m in a much better position now. I eventually figured it out while troubleshooting. Thank you

**Comment by anirtek** [comment]
I am also having the same issue while applying a yaml deployment that works absolutely fine with the kubeadm cluster. My docker image is hosted at https://quay.io/repository/cloudian/hap-spark-tf.

But I am getting this error: 
```Failed to pull image "quay.io/cloudian/hap-spark-tf:0.0.1": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/cloudian/hap-spark-tf:0.0.1": failed to copy: httpReaderSeeker: failed open: failed to do request: Get https://quay.io/v2/cloudian/hap-spark-tf/blobs/sha256:6001bcf3ad9585c9fd3abe302e0f4974f6c9b0f95ae8b34ca234a582452361c0: dial tcp: lookup quay.io: Try again```

**Comment by brandond** [comment]
@anirtek you appear to have a different issue - your error suggests some sort of DNS problem.

`lookup quay.io: Try again`

**Comment by miticojo** [comment]
Same issue with trying to deploy gitlab/gitlab-runner:alpine-bleeding arm64 on k3s cluster (raspberry 4 - 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux).

**Comment by golyalpha** [comment]
Had the same issue happen with the rancher images. Forcing a pull with the `linux/arm64` platform succeeded however.
```
$ sudo k3s ctr i pull docker.io/rancher/rancher:v2.4.8
docker.io/rancher/rancher:v2.4.8:                                              resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:5a16a6a0611e49d55ff9d9fbf278b5ca2602575de8f52286b18158ee1a8a5963: exists         |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.6 s                                                                 total:   0.0 B (0.0 B/s)
unpacking linux/arm/v8 sha256:5a16a6a0611e49d55ff9d9fbf278b5ca2602575de8f52286b18158ee1a8a5963...
ctr: no match for platform in manifest sha256:5a16a6a0611e49d55ff9d9fbf278b5ca2602575de8f52286b18158ee1a8a5963: not found
```

Note that the base OS was arm64.

**Comment by vitobotta** [comment]
> I am also having the same issue while applying a yaml deployment that works absolutely fine with the kubeadm cluster. My docker image is hosted at https://quay.io/repository/cloudian/hap-spark-tf.
> 
> But I am getting this error:
> `Failed to pull image "quay.io/cloudian/hap-spark-tf:0.0.1": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/cloudian/hap-spark-tf:0.0.1": failed to copy: httpReaderSeeker: failed open: failed to do request: Get https://quay.io/v2/cloudian/hap-spark-tf/blobs/sha256:6001bcf3ad9585c9fd3abe302e0f4974f6c9b0f95ae8b34ca234a582452361c0: dial tcp: lookup quay.io: Try again`
> 
> I am using Centos 7.6 and a 3 node k3s cluster.

Hi, I am having this issue now and Google took me here. How did you solve? (Sorry to the others for asking here but I'm kinda desperate)

**Comment by Oats87** [comment]
@vitobotta if your actual issue is the one reported, you are having what seems to be DNS issues.

Feel free to open a new issue with your exact error if your DNS setup is not your issue.

**Comment by vitobotta** [comment]
> @vitobotta if your actual issue is the one reported, you are having what seems to be DNS issues.
> 
> Feel free to open a new issue with your exact error if your DNS setup is not your issue.

Hi! It was indeed DNS! I was checking the DNS resolution inside the cluster, but k3s/containerd uses the system's resolvers when pulling images, right? It turns out Hetzner's resolvers are not very reliable. Replaced with Cloudflare's and all is good again. Thanks and sorry for adding that question here!
