### ISSUE TITLE
How to add a role to k3s agen nodes ?

### ISSUE THREAD

**Issue by colben** [k3s-io/k3s#1289]
# ENV
- CentOS 7.7
- K3S v1.17.0+k3s.1

# Problem
- The role of agent nodes displayed in this command "kubectl get nodes" is "\<none\>"
- Here is the output of the command "kubectl get nodes"
<img width="400" alt="图片" src="https://user-images.githubusercontent.com/7829126/72217560-ad636800-356a-11ea-94a7-db4662a23655.png">

# Feature
- Is there any way to modify this role string "\<none\>"

**Comment by rust84** [comment]
kubectl label node ${node} node-role.kubernetes.io/worker=worker

**Comment by colben** [comment]
> kubectl label node ${node} node-role.kubernetes.io/worker=worker
I know that this cmd works, but is there any way to specify this label as a parament in the k3s agent start cmd ?

**Comment by dweomer** [comment]
> > kubectl label node ${node} node-role.kubernetes.io/worker=worker

> I know that this cmd works, but is there any way to specify this label as a parament in the k3s agent start cmd ?

@colben you may use `k3s agent --kublet-arg node-labels=node-role.kubernetes.io/worker=worker` if you wish for the role label to be present at node registration or you may use `k3s agent --node-label node-role.kubernetes.io/worker=worker` if you wish the role label to be present at registration as well as applied each time the kublet starts up (potentially reverting a change to the node's role label applied at runtime and recorded by the cluster).

**Comment by erikwilson** [comment]
Looks like this doesn't work, it will produce a fatal error like:

> F0114 10:32:04.072486   11355 server.go:186] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/worker]
--node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/os, node.kubernetes.io/instance-type, topology.kubernetes.io/region, topology.kubernetes.io/zone)

**Comment by dweomer** [comment]
Love to apply magic labels

**Comment by ideal** [comment]
> you may use `k3s agent --kublet-arg node-labels=node-role.kubernetes.io/worker=worker` if you wish for the role label to be present at node registration or you may use `k3s agent --node-label node-role.kubernetes.io/worker=worker` if you wish the role label to be present at registration as well as applied each time the kublet starts up (potentially reverting a change to the node's role label applied at runtime and recorded by the cluster).

typo here, kublet should be kubelet, but it still has problems.

**Comment by avoidik** [comment]
The `--node-label='node-role.kubernetes.io/worker=worker'` option doesn't work

```
Oct 09 11:09:09 worker k3s[6927]: --node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/os, node.kubernetes.io/instance-type, topology.kubernetes.io/region, topology.kubernetes.io/zone)
Oct 09 11:09:09 worker k3s[6927]: F1009 11:09:09.488727    6927 server.go:187] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/worker]
```

**Comment by brandond** [comment]
Yes, the node-role.kubernetes.io label namespace has been deprecated.

**Comment by rlabrecque** [comment]
Looks like `node-role.kubernetes.io/worker=` has been replaced with `kubernetes.io/role=`

```[ 16:06:07 ] $ kubectl get nodes
NAME            STATUS   ROLES    AGE     VERSION
ip-10-0-4-20    Ready    master   2d23h   v1.19.7+k3s1
ip-10-0-4-165   Ready    <none>   2d23h   v1.19.7+k3s1

[ 16:06:16 ] $ kubectl label nodes ip-10-0-4-165 kubernetes.io/role=agent
node/ip-10-0-4-165 labeled

[ 16:06:25 ] $ kubectl-tools get nodes
NAME            STATUS   ROLES    AGE     VERSION
ip-10-0-4-20    Ready    master   2d23h   v1.19.7+k3s1
ip-10-0-4-165   Ready    agent    2d23h   v1.19.7+k3s1
```

I suspect `--node-label='kubernetes.io/role=agent'` will work.

**Comment by lachnerd** [comment]
any progress on this or has somebody found out whats the right expression to set ?

**Comment by brandond** [comment]
You can still do `kubectl label nodes --all node-role.kubernetes.io/MyRole=true` from kubectl. Nodes are no longer allowed to set their own role annotations at startup though.

**Comment by lachnerd** [comment]
ok, thx
> Nodes are no longer allowed to set their own role annotations at startup though.
Where does this Info come from ?

**Comment by brandond** [comment]
https://github.com/kubernetes/kubernetes/issues/84912#issuecomment-551362981

**Comment by tcurdt** [comment]
So to clarify and summarise the outcome of this issue...

It's no longer possible to specify the agent role on install.
One has to manually run another `kubectl` to add the role to the nodes. For example like this:

    kubectl label nodes --all kubernetes.io/role=agent

Is that correct?

**Comment by fragtom** [comment]
There are still changes in labeling with newer versions of Kubernetes. 
`node-role.kubernetes.io/agent=true`
did the label of kubernetes node with agent.

**Comment by donhector** [comment]
What worked for me with multiple agents (post cluster creation):

`kubectl get nodes -o name | grep agent | xargs -n1 -I@ kubectl label @ node-role.kubernetes.io/agent=`

NOTE: Where '@' is an arbitrary placeholder symbol that xargs will use inject the ouput from grep one line at a time

**Comment by msolimans** [comment]
I love to use `k3d` - simply pass `--k3s-node-label 'foo=bar@agent:1`

**Comment by mihaigalos** [comment]
This is still happening in k3s with 1.26.

```bash
$ kubectl get nodes
NAME     STATUS   ROLES                  AGE   VERSION
master   Ready    control-plane,master   41s   v1.26.1+k3s1
worker   Ready    <none>                 35s   v1.26.1+k3s1
```

I confirm I can manually set the worker label so:
```bash
$ kubectl label node ${node} node-role.kubernetes.io/worker=worker
```
I however cannot pass the `--node-label='node-role.kubernetes.io/worker=worker'` flag, seeing the following error:
```bash
INFO[0002] Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --cpu-cfs-quota=false --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=worker --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --kubelet-cgroups=/k3s --node-labels=node-role.kubernetes.io/worker=worker --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/var/lib/rancher/k3s/agent/etc/resolv.conf --runtime-cgroups=/k3s --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key 
Flag --cloud-provider has been deprecated, will be removed in 1.25 or later, in favor of removing cloud provider code from Kubelet.
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Error: failed to validate kubelet flags: unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/worker]
--node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/os, node.kubernetes.io/instance-type, topology.kubernetes.io/region, topology.kubernetes.io/zone)
FATA[0002] kubelet exited: failed to validate kubelet flags: unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/worker]
--node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/os, node.kubernetes.io/instance-type, topology.kubernetes.io/region, topology.kubernetes.io/zone) 
```

**Comment by brandond** [comment]
@mihaigalos please read the comments that you're responding to. This is not a defect in k3s.
