### ISSUE TITLE
Change ports where scheduler and manager are listening

### ISSUE THREAD

**Issue by jeusdi** [k3s-io/k3s#1292]
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**
Is there any way to change port where `scheduler` and `controller-manager` components are listening?

I mean, currently thuey are listening to 10252 and 10251.

Is there any way to change that?

**Comment by BlackTurtle123** [comment]
We are also looking for this, when we want to put everything connecting to an internal interface

**Comment by euank** [comment]
Yes, you can configure them in the usual way for component flags.

For example, to change the scheduler's port and bind address, I believe the following works: `k3s server --kube-scheduler-arg 'port=12345' --kube-scheduler-arg 'bind-address=127.0.0.1'`

Note that those ports only matter if you care about the output of `kubectl get componentstatus` or you have something monitoring componentstatus. Componentstatus should be considered depreciated iiuc though, so you may want to just turn those ports off entirely (with `port=0` in the above flags).
