### ISSUE TITLE
Node joined to the cluster as secondary master is in NotReady state

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#1293]
**Version:**
k3s -v
k3s version v1.17.0+k3s.1 (0f644650)

**Describe the bug**
Create three nodes as masters. Third node changes from Ready state to NotReady state after sometime, using DQLite as the embedded db

**To Reproduce**
Create a cluster with single node providing token.
Join two more nodes as server to the cluster.

**Expected behavior**
All nodes in Ready state

**Actual behavior**
Third node goes to NotReady state after a while.

**Additional context**
No workloads added. Cluster was in idle state after creation to reproduce the issue. Logs show TLS handshake error

```Jan 13 21:32:29 ip-172-31-13-183 k3s[14501]: time="2020-01-13T21:14:59.705766079Z" level=error msg="Error writing ping" error="websocket: write timeout"
Jan 13 21:34:00 ip-172-31-13-183 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jan 13 21:34:04 ip-172-31-13-183 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jan 13 21:37:17 ip-172-31-13-183 k3s[14501]: I0113 21:32:37.208395   14501 leaderelection.go:288] failed to renew lease kube-system/k3s: failed to tryAcquireOrRenew context deadline exceeded```

```Jan 13 22:02:47 ip-172-31-8-214 k3s[3105]: time="2020-01-13T22:02:47.675343907Z" level=error msg="failed to record compact revision: database is locked"
Jan 13 22:02:15 ip-172-31-8-214 k3s[3105]: I0113 22:02:15.282964    3105 log.go:172] http: TLS handshake error from 172.31.6.214:36398: EOF```

**Comment by davidnuzik** [comment]
@ShylajaDevadiga does the cluster datastore type matter? I'm guessing all are affected.

**Comment by ShylajaDevadiga** [comment]
Updated issue. Issue is seen while using DQLite.

**Comment by caroline-suse-rancher** [comment]
Closing - DQLite is now deprecated
