### ISSUE TITLE
Unable to create an IPv6 only k3s cluster 

### ISSUE THREAD

**Issue by rom1pass** [k3s-io/k3s#1301]
**Version:**
k3s version v0.5.0 ((8c0116dd)) 

**Describe the bug**
We want to create an IPv6 only cluster on which k3s will run. We tried to install k3s using the Ansible playbook present in the contrib folder. (https://github.com/rancher/k3s/tree/master/contrib/ansible).  Since this playbook seems not to support IPv6 we tried modify it to do so. But it won't work. 
Could you help us with the configuration of the playbook to get it working ?  
**To Reproduce**
Find our git were all config files are presents : 
https://github.com/TGuimbert/cluster-ceph-k3s/tree/master/k3s-ansible
**Expected behavior**
We expected the k3s server to run and receive the connection of our 4 nodes. 
**Actual behavior**
First the server was started but no nodes could connect then we modified the server option with some informations we could find about an IPv6 only networks. But now the server is unable to start. 
**Additional context**
This Ansible playbook create services to launch the server and the agent you can find the k3s commands in `roles/k3s/master/templates/k3s.service.j2` and `roles/k3s/node/templates/k3s.service.j2`

Thanks in advance for your help

**Comment by iam-TJ** [comment]
I'll be interesting in this too as we're about to deploy a cluster across multiple architectures and k3s hits the nails on their heads in every respect!

As I understand it though, the issue over lack of IPv6 support is a Kubernetes issue. I'm following a related PR in Kubernetes where IPv6 support has been put back from 1.18 due to some unresolved issues. See:

https://github.com/kubernetes/enhancements/issues/508

**Comment by unixfox** [comment]
Isn't it the other way around? That kubernetes 1.18 is going to have IPv6 support?

**Comment by iam-TJ** [comment]
They removed the v1.18 milestone then added it again but from other stuff I'm watching don't bank on it arriving in v1.18.

**Comment by elloe** [comment]
This is iam-TJ with my business hat on. Still watching for full native IPv6-only functionality to land. As we currently understand it, k8s v1.20 should land mid-December with dual-stack *alpha* support that could be subject to API revision ( https://github.com/kubernetes/enhancements/issues/563  https://github.com/kubernetes/kubernetes/pull/91824 ).

Currently blocking k3s full IPv6 is complete kube-router support for IPv6 ( https://github.com/cloudnativelabs/kube-router/issues/988 https://github.com/cloudnativelabs/kube-router/pull/956 ). We are beginning work on solving that ourselves and will offer a PR upstream if we're successful.

Our scenario is on-premises networks (multiple VLANs) with no IPv4 and with a NAT64 gateway to cope with external IPv4-only sites and services, delegating our IPv6 sub-prefixes to container services, so I do not want us forced into using IPv4 for containers. Additionally, we're deploying on two architectures (aarch64 and amd64).

Any suggestions or hints on anything else we need to address to enable IPv6-only k3s clusters would be welcome.

**Comment by aojea** [comment]
> Isn't it the other way around? That kubernetes 1.18 is going to have IPv6 support?

IPv6 "only" is Beta since 1.18 in kubernetes, it was available as alpha since 1.9.
Dual Stack is alpha right now

**Comment by elloe** [comment]
k3s may also require coredns patches to support dual-stack as is discussed in this coredns PR for EndpointSlices https://github.com/coredns/coredns/pull/4209#issuecomment-717277766

That indicates coredns will not add support for clusterIP arrays until the k8s feature is out of alpha and included in the API.

**Comment by elloe** [comment]
The k8s enhancement that added support for IPv6 only is https://github.com/kubernetes/enhancements/issues/508 and comments there add some useful context and comments on how to deploy IPv6 only (summary: use IPv6 addresses anywhere you'd use IPv4 addresses!).

**Comment by elloe** [comment]
Just noticed my comments would be better off attached to https://github.com/rancher/k3s/issues/284

**Comment by unixfox** [comment]
Still important but it is soon going to be resolved thanks to the recent IPv6 support in k3s.
