### ISSUE TITLE
Pod Ready and Running Status not correct / not consistent when using StatefulSet

### ISSUE THREAD

**Issue by sebschlue** [k3s-io/k3s#1303]
**Version:**
k3s version v1.17.0+k3s.1 (0f644650)

**Describe the bug**
I am experiencing wrong or stale status information while testing StatefulSets using three nodes. The Pods are indirectly pinned to hosts via LocalPersistentVolumes. If I shut down a node, the Pods that were running on this node are gone for good and cannot be re-created on another node due to said LocalPersistentVolumes constraints. So far, so good. If I shut down a node, this is quickly noticed:

````
$ kubectl get nodes 
NAME     STATUS     ROLES    AGE   VERSION
node03   Ready      <none>   19d   v1.17.0+k3s.1
node01   Ready      master   19d   v1.17.0+k3s.1
node02   NotReady   <none>   19d   v1.17.0+k3s.1
````

But the Pod that was running on this node is still reported as Running and Ready:

````
# kubectl -n vault get pods -o wide
NAME            READY   STATUS    RESTARTS   AGE     IP            NODE     NOMINATED NODE   READINESS GATES
vault-transit   1/1     Running   0          22m     10.42.0.182   node01   <none>           <none>
vault-0         1/1     Running   0          21m     10.42.0.183   node01   <none>           <none>
vault-2         1/1     Running   0          21m     10.42.2.43    node03   <none>           <none>
vault-1         1/1     Running   0          2m59s   10.42.1.54    node02   <none>           <none>
````

This also gives the same wrong/stale info:

````
$ kubectl -n vault get pod vault-1 -o json | jq .status.containerStatuses[0].ready
true
````

Only this delivers the correct info:

````
$ kubectl -n vault describe pod vault-1 | grep "^  Ready"
  Ready             False 
````

The headless service for the StatefulSet apparently also already knows that the Pod is gone and offers only two Pod IP addresses instead of three:

````
# dig +nocmd +noall +answer @10.42.0.162 vault.vault.svc.cluster.local
vault.vault.svc.cluster.local. 5 IN	A	10.42.0.183
vault.vault.svc.cluster.local. 5 IN	A	10.42.2.43
````

If the whole node is down, a Pod running on that Node obviously cannot be "Running" and if it's not "Running", it also cannot be "Ready". Even is this argument did not count, this StatefulSet has a readinessProbe with period 10 seconds and failure threshold of three, so a Pod that is gone should not be ready anymore after 30 seconds.

After a looong period of time, the state changes to "Terminating":

````
# kubectl -n vault get pods -o wide
NAME            READY   STATUS        RESTARTS   AGE   IP            NODE     NOMINATED NODE   READINESS GATES
vault-transit   1/1     Running       0          31m   10.42.0.182   node01   <none>           <none>
vault-0         1/1     Running       0          30m   10.42.0.183   node01   <none>           <none>
vault-2         1/1     Running       0          30m   10.42.2.43    node03   <none>           <none>
vault-1         1/1     Terminating   0          11m   10.42.1.54    node02   <none>           <none>
````

This seems to be the final state., I did not observe further state changes.

**To Reproduce**
Not sure. Maybe this is already a well-known problem. I just stumbled over this. I guess you need at least two nodes (master and worker), a StatefulSet and node-pinning for its members.

**Expected behavior**
I would expect kubectl to show correct and consistent data.

**Actual behavior**
kubectl shows incorrect and inconsistent data.

**Additional context**
Re-starting the shut-down node works fine without any issues. The vault Pod gets started again automatically. I would personally expect the RESTART count to increase since the name of the Pod has not changed ("vault-1") but in fact the RESTART count is still 0. But I guess this is just a matter of convention. Also, the IP address changes, but this is to be expected for Kubernetes Pods that are being restarted, although somehow unfortunate for StatefulSet members.

**Comment by dereknola** [comment]
Closing as Out of Date. Kubectl information is controlled by upstream.
