### ISSUE TITLE
[Documentation] What does it mean to disable the default k3s network policy? And more details on Network Policy

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1308]
Opened via https://github.com/rancher/docs/issues/2178 we use rancher/k3s for tracking docs currently as it's easier to manage on our boards.

What exactly does disable network policy do? From a user standpoint, I don’t see any docs on what the network policy is to begin with (google “k3s network policy” or search the docs page). So, I'm not not sure what is being disabled when I use the `--disable-network-policy` flag or how it correlates to other flags such as the group for networking:
```
--cluster-cidr value                       (networking) Network CIDR to use for pod IPs (default: "10.42.0.0/16")
--service-cidr value                       (networking) Network CIDR to use for services IPs (default: "10.43.0.0/16")
--cluster-dns value                        (networking) Cluster IP for coredns service. Should be in your service-cidr range (default: 10.43.0.10)
--cluster-domain value                     (networking) Cluster Domain (default: "cluster.local")
--flannel-backend value                    (networking) One of 'none', 'vxlan', 'ipsec', or 'flannel' (default: "vxlan")
 ```

**Further, we should talk about network policy in general some - not just what it means to disable default k3s network policy.**

**Comment by keslerm** [comment]
This is actually a good question and caught me by surprise when a network policy was being enforced despite my understanding that flannel doesn't support them.

I dug around a bit and it looks like k3s implements an internal network policy controller based on the kube-router one, you can see PR #913 when it was added. So I'm doing some digging to see if i can assist with updating the documentation around this some.

Does the internal network policy controller have to be disabled if installing something like Calico? Also since this is fundamentally different than Kubernetes afaik, it should probably be documented that this controller exists in the first place and some details on how to use it.

**Comment by davidnuzik** [comment]
In docs we may want to touch on this upstream issue as well: https://github.com/cloudnativelabs/kube-router/issues/873

**Comment by onedr0p** [comment]
I am also wondering with the option to disable kube-proxy, we can run cilium and kube-router, does using kube-router mean we can use their NPC instead? The issue I linked above is trying to apply [this](https://github.com/fluxcd/toolkit/blob/main/manifests/policies/deny-ingress.yaml) policy but it doesn't work when using cilium + kube-router.

**Comment by cawoodm** [comment]
The [docs](https://rancher.com/docs/k3s/latest/en/installation/install-options/how-to-flags/) reference `disable-network-policy: true` but I too could find no explanation.

**Comment by comphilip** [comment]
K3S uses `kube-router` network policy controller. The controller is golang based and is built into k3s binary: https://github.com/k3s-io/k3s/blob/master/pkg/agent/netpol/netpol.go

`disable-network-policy: true` let K3S not run `kube-router` network policy controller: https://github.com/k3s-io/k3s/blob/c00f953ef953ef25797bd851baca2066e2754e5f/pkg/agent/run.go#L143-L147

The controller setup iptables firewall rules for kubernetes network policy definitions. You should think it over if your k3s cluster uses different CNI other than flannel.

**Comment by brandond** [comment]
It is also covered in the readme in the repo: https://github.com/k3s-io/k3s/blob/master/README.md#what-is-this
> K3s bundles the following technologies together into a single cohesive distribution:
> * ...
> * [Kube-router](https://www.kube-router.io/) netpol controller for network policy

**Comment by alokhom** [comment]
Most CNI plugins come with their own network policy engine, so it is recommended to set --disable-network-policy as well to avoid conflicts.
