### ISSUE TITLE
[Documentation] Discuss the debug flag / environment variable and how to use them

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1310]
We should document the --debug flag and it's environment variable, K3S_DEBUG.

We should have perhaps a Troubleshooting section in our docs that could discuss the debug flag/env var and perhaps we mention Logging here as well. Logging should be separate but we could link to it from this Troubleshooting section I propose.

**Comment by davidnuzik** [comment]
@davidnuzik investigate - why are debug flags hidden -- or have these been removed for some reason (doubt that). Test, and query the k3s/rke2 team on this. I think it should be documented so others may utilizes this feature.

**Comment by brandond** [comment]
I'd be curious to know what the debug flags enable that wouldn't show up in normal k8s `--v=9` output.

**Comment by cwayne18** [comment]
Is this still needed? @catherineluse
