### ISSUE TITLE
Don't overwrite manifests on service restart

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#1317]
**Is your feature request related to a problem? Please describe.**
k3s server rewrites all enabled manifests every time it starts. I edited my coredns configuration at /var/lib/rancher/k3s/server/manifests/coredns.yaml, and was surprised when the changes were lost when the host restarted.

**Describe the solution you'd like**
k3s should not overwrite manifests that have been customized by the user.

**Describe alternatives you've considered**
I've considered disabling all the core components and providing my own, but users shouldn't be forced to guess ahead of time at what configuration they might want to change once the system is running, especially when the addon manager's live-update functionality encourages users to edit the files in-place.

**Additional context**
N/A

**Comment by davidnuzik** [comment]
Related https://github.com/rancher/k3s/issues/1254 (support custom manifests)

**Comment by brandond** [comment]
I don't recall seeing this in the documentation anywhere, but apparently the existence of a .skip file (/var/lib/rancher/k3s/server/manifests/coredns.yaml.skip for example) will prevent the deploy controller from staging manifests. Unfortunately it also masks the file from being deployed as an Addon. It'd be nice if I could chose between skipping staging and skipping deployment.

**Comment by jonstelly** [comment]
Thanks for that find.  Just a note:

If you modify a yaml file in the `/var/lib/rancher/k3s/server/manifests` directory, it seems like you need to wait until after the change gets picked up and applied, then create the skip file.  I created a .skip file at the same time that I modified my `traefik.yaml` and the change didn't get applied.  I deleted the .skip file and let the deployment happen, then created it again.

**Comment by camaeel** [comment]
It would be nice to have to switches - one to block reverting change, and secnd to block applying file contents.

**Comment by meappy** [comment]
I've tested just modifying `/var/lib/rancher/k3s/server/manifests/traefik.yaml`

```
    perl -p -i -e 's/(rbac.enabled: "true")/$1\n    ssl.insecureSkipVerify: "true"/g' \
                   /var/lib/rancher/k3s/server/manifests/traefik.yaml 
```

Then deployed `k3s` again with the following command without `INSTALL_K3S_EXEC="--no-deploy=traefik"`

```
# k3s --version 
k3s version v1.17.4+k3s1 (3eee8ac3)
```

```
sudo curl -sfL https://get.k3s.io | sh -
```

My changes are not overwritten, am I missing something here?

**Comment by RedHawker** [comment]
One **workaround** is to modify `/etc/systemd/system/k3s.service` to have the line `ExecStartPost=<path to bootstrap script>`

Then in your bootstrap script, you can have

```bash
#!/usr/bin/bash
# commands to modify the file as needed
```

With `k3s` >= 1.19.0, you should be able to use a HelmChartConfig: https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by xzycn** [comment]
Hi，is there any update on the progress？
When I changed the replica of coredns in /var/lib/rancher/k3s/server/manifests/coredns.yaml to 2, after some time, I found it was changed back to 1 :(
I change the replica and node-affinity through **kubelet edit**, I want to know a better way to do this.
I‘m using v1.24.4+k3s1, thanks in advance.

**Comment by brandond** [comment]
We are not currently planning on changing this behavior. The only supported way to modify the configuration of packaged components like CoreDNS that are not installed via HelmChart is to `--disable` the packaged component and deploy your own. You can use the default manifest as a starting point, just be sure to give the file a different name (call it custom-coredns.yaml for example, instead of coredns.yaml) so that it does not conflict with the disabled component.
