### ISSUE TITLE
Support Snapshot/Backup/Restore of embedded sqlite

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1318]
As a part of our effort for integrating with Rancher we need to support Snapshot/Backup/Restore of K3s with embedded sqlite.

Anyone using an external database is recommended to backup/restore their external database.

As for DQLite, we may add this feature later but for now we just need embedded sqlite support.

**Comment by liyimeng** [comment]
How is this going on?

**Comment by danieldaeschle** [comment]
Any possibility to backup the sqlite right now?

**Comment by brandond** [comment]
@danieldaeschle all you need to do is stop k3s and make a copy of /var/lib/rancher/k3s/server

**Comment by andrescaroc** [comment]
@brandond Let's say I have my backup of `/var/lib/rancher/k3s/server` 

How to proceed to recover a k3s cluster hosted in k3os?

Note: I understand that for a cluster installed using the script you have to delete k3s and then install again and replace the backed up directory. But it is not clear when the k3s comes within a k3OS (let say an aws AMI or an ISO)

**Comment by caroline-suse-rancher** [comment]
Closing - this appears to be resolved.
