### ISSUE TITLE
Improve feedback of deploy controller operations and failures

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#1337]
**Is your feature request related to a problem? Please describe.**
When making use of the deploy controller (which I do, because I find it easier than using `kubectl apply`), deployment status and errors are not exposed anywhere except the k3s server log.

**Describe the solution you'd like**
It would be nice if there was some feedback in the Addon CR as to deployment milestones. This would include events when the manifest is loaded or updated, any errors encountered when applying the manifest, etc.

Additionally, if the manifest does not contain at least one valid resource, the Addon CR is not created at all. Ideally the Addon would be created anyway so as to expose the errors.

Since actually storing and presenting the errors is likely to create a lot of noise if there's an unresolved error, the watcher should probably retry individual manifests with exponential backoff rather than a fixed 15 second cycle.

**Describe alternatives you've considered**
Currently I have to just tail the k3s server log and watch for errors applying manifests. There is no feedback when it works, but if it fails there's usually some sort of error (of varying usefulness) that indicates I need to go fix something.

**Comment by ShylajaDevadiga** [comment]
Validated using commit ID: 
k3s version v1.21.2+k3s-a4c992ce
Events are displayed when describing AddOn
```
Events:
  Type    Reason            Age   From    Message
  ----    ------            ----  ----    -------
  Normal  ApplyingManifest  113s  deploy  Applying manifest at "/var/lib/rancher/k3s/server/manifests/traefik.yaml"
  Normal  AppliedManifest   113s  deploy  Applied manifest at "/var/lib/rancher/k3s/server/manifests/traefik.yaml"
```

**Comment by rancher-max** [comment]
Previously validated and continues to work on latest master commit `90960ebf4e7a08df075526f411e3afe06731b01e` so am closing this
