### ISSUE TITLE
Systemctl start does not return on HA server install

### ISSUE THREAD

**Issue by embcla** [k3s-io/k3s#1356]
### Version
k3s 1.17.2+k3s1 

### Configuration
So I have this configuration I run via vagrant+vbox+ubuntu lts which I put together following the webinars.
It's composed of 2 masters in HA via MySQL and 3 nodes.
And it works: I can push helm charts, bring nodes up and down, and so on.
Prometheus is working, rabbitmq is working, bring down nodes causes rescheduling of pods, etc
So I take that the cluster itself is working

### Issue
Automatic provisioning hangs because systemctl start of the masters hangs, it just never returns on any master.
Systemctl does not return on master install with status saying
```
vagrant@master1:~$ systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Fri 2020-02-07 17:18:42 UTC; 4min 59s ago
     Docs: https://k3s.io
  Process: 19774 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 19763 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 19775 (k3s-server)
    Tasks: 17
   CGroup: /system.slice/k3s.service
           ├─19775 /usr/local/bin/k3s server -v 2 -l /vagrant/master1.log -t NDY0YzdjZjBlMGMwYmM2NDY3YzBjNmJhMDM4MDY4YWYxZTNjYjkwYSAgLQo= --flannel-iface=enp0s8 --write-kubeconfig-mode 644 
           ├─19796 k3s server -v 2 -l /vagrant/master1.log -t NDY0YzdjZjBlMGMwYmM2NDY3YzBjNmJhMDM4MDY4YWYxZTNjYjkwYSAgLQo= --flannel-iface=enp0s8 --write-kubeconfig-mode 644 --tls-san k3s-c
           └─19824 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/c

```

### Behaviour
I guess that _activating_ is the key here. What is the startup sequence waiting for?
* new nodes work fine and service activation returns correctly
* new masters work fine, their service activation however _**does not**_ return 

### Expectations
That all systemd services return correctly

### Additional info
Here is my install line

`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="-v 2 -l /vagrant/master1.log -t ${NODE_TOKEN} --flannel-iface=enp0s8 --write-kubeconfig-mode 644 --tls-san k3s-cluster-01.lan --node-taint k3s-controlplane=true:NoExecute --datastore-endpoint mysql://k3s:${MYSQL_PASSWORD}@tcp(${IPADDR}:3306)/k3s" sh -`

**Comment by embcla** [comment]
Tried also with v1.17.2+k3s1 and the same happens: systemctl does not return on master install

Status says
```
vagrant@master1:~$ systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Fri 2020-02-07 17:18:42 UTC; 4min 59s ago
     Docs: https://k3s.io
  Process: 19774 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 19763 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 19775 (k3s-server)
    Tasks: 17
   CGroup: /system.slice/k3s.service
           ├─19775 /usr/local/bin/k3s server -v 2 -l /vagrant/master1.log -t NDY0YzdjZjBlMGMwYmM2NDY3YzBjNmJhMDM4MDY4YWYxZTNjYjkwYSAgLQo= --flannel-iface=enp0s8 --write-kubeconfig-mode 644 
           ├─19796 k3s server -v 2 -l /vagrant/master1.log -t NDY0YzdjZjBlMGMwYmM2NDY3YzBjNmJhMDM4MDY4YWYxZTNjYjkwYSAgLQo= --flannel-iface=enp0s8 --write-kubeconfig-mode 644 --tls-san k3s-c
           └─19824 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/c

```

**Comment by brandond** [comment]
I am guessing that this has something to do with your INSTALL_K3S_EXEC variable, since there are better ways to pass arguments to the server or agent, and I've used k3s with systems on ubunt without issue.

**Comment by embcla** [comment]
Hi @brandond 
Can you elaborate on the "_better ways to pass arguments_" ?
It's easy to pass the token as an envvar, but what other things should I change and what's the effect?

**Comment by embcla** [comment]
I'd love to get some pointers on debugging this, I still see this issue and am unable to understand what's blocking the service from reporting a correct startup to systemd

**Comment by embcla** [comment]
using 1.7.4+k3s1
I found some more details on this.

Here is my INSTALL_K3S_EXEC
`export INSTALL_K3S_EXEC="-server  --flannel-backend=wireguard --datastore-endpoint http://node01:2379,http://node02:2379,http://node03:2379  --flannel-iface=eth1"`

And all goes well.
As soon as I add
`--no-deploy=traefik --no-deploy=servicelb`
then it doesn't return anymore.

Now I tried disabling only one at a time, but it still doesn't return.
in this case the log at level5 shows only
```
I0412 17:37:25.257357   17913 interface.go:400] Looking for default routes with IPv4 addresses
I0412 17:37:25.257738   17913 interface.go:408] Default route transits interface "eth0"
I0412 17:37:25.257887   17913 interface.go:208] Interface eth0 is up
I0412 17:37:25.257972   17913 interface.go:256] Interface "eth0" has 3 addresses :[masked/20 masked/16 masked/64].
I0412 17:37:25.258023   17913 interface.go:223] Checking addr  masked/20.
I0412 17:37:25.258041   17913 interface.go:230] IP found masked
I0412 17:37:25.258056   17913 interface.go:262] Found valid IPv4 address masked for interface "eth0".
I0412 17:37:25.258075   17913 interface.go:414] Found active IP masked
time="2020-04-12T17:37:25.258192904Z" level=info msg="found ip masked from iface eth1"
I0412 17:37:25.258245   17913 services.go:51] Setting service IP to "masked" (read-write).
time="2020-04-12T17:37:25.258273331Z" level=info msg="Starting k3s v1.17.4+k3s1 (3eee8ac3)"
```

With flannel dying and traefik 2, what is the plan to move k3s onward?

**Comment by ahjsun** [comment]
I had the same issue. Removing the -l or --log variable when you  run curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC , returns the systemctl k3s status as running/active

**Comment by charlesdrews** [comment]
I'm having the same problem where if I include `-l` or `--log` in `INSTALL_K3S_EXEC` then it never returns after `systemd: Starting k3s` and `systemctl status k3s` shows it stuck at `activating (start)`. Is there any way to re-open this ticket? I need to be able to log to somewhere other than syslog.

**Comment by brandond** [comment]
@charlesdrews that is tracked under https://github.com/k3s-io/k3s/issues/2277#issuecomment-700468473

**Comment by charlesdrews** [comment]
@brandond Thank you so much, this solved the problem of being stuck on `activating` for me.

Question - with --log, does journald still capture what's written to the specified log file and forward to syslog? My end goal is to not add to syslog.

**Comment by brandond** [comment]
no, if you manually send it somewhere else then it doesn't go to stdout/stderr and nothing is captured by journald. It sounds like you might want to filter some units out of the journald syslog output?

**Comment by charlesdrews** [comment]
Perfect, then I am all set. I will look into filtering units out of journald syslog output, but for now this solves my immediate need. Thanks again!
