### ISSUE TITLE
HA multi-master deploy controller behavior

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#1357]
**Version:**
v1.17.2+3592d0bd on Ubuntu 19.10 amd64

1 node deployed with:
`K3S_TOKEN=asecret INSTALL_K3S_COMMIT=3592d0bdd9e0656d9f1704548ccf199039f27136 ./k3s.sh server --no-deploy=coredns,servicelb,traefik,local-storage --disable-cloud-controller --disable-network-policy --cluster-init`

2 nodes deployed with:
`K3S_URL=https://k3s01.khaus:6443 K3S_TOKEN=asecret INSTALL_K3S_COMMIT=3592d0bdd9e0656d9f1704548ccf199039f27136 ./k3s.sh server --no-deploy=coredns,servicelb,traefik,local-storage --disable-cloud-controller --disable-network-policy`

**Describe the bug**
I'm not sure which nodes are running the deploy controller. All of them? Just the one that's currently holding the lease for kube-controller-manager?

**To Reproduce**
Configure 3 nodes as described above

**Expected behavior**
Clear knowledge over which node is responsible for deploying manifests from the filesystem

**Actual behavior**
Unknown behavior

**Comment by dereknola** [comment]
We have long had the distinction between `--cluster-init` and `--server` flags. The primary server deploys the manifests. Closing as OOD.

**Comment by brandond** [comment]
Actually all of them deploy the manifests 😬
