### ISSUE TITLE
Traefik nodeploy schedule traefik anyway

### ISSUE THREAD

**Issue by embcla** [k3s-io/k3s#1364]
Version: v1.17.2+k3s1 (cdab19b0)
Install line v1:
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="-v 2 -l /vagrant/master2.log -t ${NODE_TOKEN} --flannel-iface=enp0s8 --no-deploy=traefik,servicelb --write-kubeconfig-mode 644 --tls-san k3s-cluster-01.lan --node-taint k3s-controlplane=true:NoExecute --datastore-endpoint mysql://k3s:${MYSQL_PASSWORD}@tcp(192.169.1.251:3306)/k3s" sh -`

Install line v2:
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="-v 2 -l /vagrant/master2.log -t ${NODE_TOKEN} --flannel-iface=enp0s8 --no-deploy traefik --no-deploy servicelb --write-kubeconfig-mode 644 --tls-san k3s-cluster-01.lan --node-taint k3s-controlplane=true:NoExecute --datastore-endpoint mysql://k3s:${MYSQL_PASSWORD}@tcp(192.169.1.251:3306)/k3s" sh -`

**Describe the bug**
the process is started with the right options inheriting the --no-deploy but logs show the scheduler is still trying to find a suitable node to schedule the traefik helm install pod.

```
time="2020-01-30T08:51:17.793504260Z" level=info msg="Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik-1.81.0.tgz"
I0130 08:51:33.726660   23789 factory.go:453] Unable to schedule kube-system/helm-install-traefik-tjqzc: no fit: 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.; waiting
I0130 08:51:33.786132   23789 event.go:281] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"helm-install-traefik", UID:"81275b2f-5987-4dc1-8614-9ac98fe268cd", APIVersion:"batch/v1", ResourceVersion:"313", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: helm-install-traefik-tjqzc
```

**To Reproduce**
Install a master with the above mentioned line and check its logs.

**Expected behavior**
No attempt at loading/scheduling traefik

**Actual behavior**
Same behaviour as without the --no-deploy flag

**Additional context**
Vagrant, Ubuntu 18.04 LTS
[master1.log](https://github.com/rancher/k3s/files/4133090/master1.log)

**Comment by brandond** [comment]
Did you do a complete cleanup of files and clean the database between installations? k3s-uninstall.sh should delete the manifests directory and any other on-disk artifacts, but it won't clean up your mysql tables. It looks to me like you still have a Job defined for the Helm chart install, perhaps from an older cluster. If this is true, you probably have some old Addon and HelmChart custom resources in there too.

The first line is from the static file controller, which I think is unrelated to the deploy controller that respects the no-deploy flags. I believe that it'll write out the helm chart tarball regardless of whether or not the traefik addon is enabled.

**Comment by embcla** [comment]
Hi Brandon

I'm always deploying via vagrant provisioning, and that deletes the database and user via mysql commands before creating them again

It does not run the k3s-uninstall though, I'll try adding this step

**Comment by davidnuzik** [comment]
When you have the time, please let us know if what Brandon suggested resolved the issue (and close the issue). Or if you still have issues please let us know and supply any useful details. Thanks!

**Comment by atosatto** [comment]
If that helps, I can confirm that with 

```
root@k3s-dev:~# k3s-installer.sh --docker --no-deploy traefik
```

the following systemd unit is generated on the k3s server

```
root@k3s-dev:~# systemctl cat k3s
# /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--docker' \
        '--no-deploy' \
        'traefik' \
```

resulting in traefik being excluded from the deployment

```
root@k3s-dev:~# k3s kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   metrics-server-6d684c7b5-8brmk            1/1     Running   0          8s
kube-system   coredns-d798c9dd-xfrpn                    0/1     Running   0          8s
kube-system   local-path-provisioner-58fb86bdfd-gdq9v   1/1     Running   0          8s
```
