### ISSUE TITLE
Deploy controller allows conflicting state from same manifests in different directories

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#1369]
**Version:**

v1.17.2-alpha1+k3s1
K3S_TOKEN=xxx INSTALL_K3S_COMMIT=3592d0bdd9e0656d9f1704548ccf199039f27136 ./k3s.sh server --no-deploy=coredns,servicelb,traefik,local-storage --disable-cloud-controller --disable-network-policy

**Describe the bug**
If you have multiple manifests with the same name but in different directories, the deploy controller will happily load them in to the same addon resource every loop. If the content is not exactly the same, this causes a continual loop of conflicting configurations that the controller attempts to apply every 15 seconds

**To Reproduce**
1. Deploy with stock addon manifests
2. `cp /var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-deployment.yaml /var/lib/rancher/k3s/server/manifests`
3. modify /var/lib/rancher/k3s/server/manifests/metrics-server-deployment.yaml

**Expected behavior**
The deploy controller should include the subpath within the manifests directory in the generated addon name, instead of simply using the file basename as the addon name. Alternately, it should refuse to modify an existing addon if the path does not match the path of the file being loaded.

**Actual behavior**
Endless loop of resource changes

**Additional context**
I know I'm probably overusing the deploy controller. Sorry for all the issues.

**Comment by galal-hussein** [comment]
Thanks @bradtopol for submitting the issue, I think this is a normal behavior when trying to apply two objects with the same name and different spec in kubernetes, the k3s controller doesn't modify the user's manifests within the directory, it applies the objects defined within, so I think its the user responsibility to make sure there are no conflicts in the manifests
