### ISSUE TITLE
k3s server fails to start ContainerManager with --rootless

### ISSUE THREAD

**Issue by marcbrandner** [k3s-io/k3s#1378]
**Version:**
`v1.17.2+k3s1`

**Describe the bug**
Had k3s with `--rootless` working without problems using `v1.17.0+k3s.1`. After switching to `v1.17.2+k3s1` with the same setup (including the same rootless preparation steps), the k3s server fails to start.

**To Reproduce**
- Prepare rootless requirements as [documented ](https://rancher.com/docs/k3s/latest/en/advanced/#running-k3s-with-rootlesskit-experimental)
- Run: `k3s server --rootless`
- Check logs: `journalctl -u k3s`

**Expected behavior**
k3s server does not fail to start.

**Actual behavior**
k3s server fails to start and exits with code 255. Logs in `journalctl -u k3s` show:
```
[...]
Feb 03 10:04:59 k3s-master-01 k3s[2971]: F0203 10:04:59.417996    3046 kubelet.go:1380] Failed to start ContainerManager [open /proc/sys/vm/overcommit_memory: permission denied, open /proc/sys/kernel/panic: permission denied, open /proc/sys/kernel/panic_on_oops: permission denied]
Feb 03 10:04:59 k3s-master-01 k3s[2971]: time="2020-02-03T10:04:59.670248433Z" level=fatal msg="child diedcommand [/proc/self/exe server --rootless] exited: exit status 255"
```

Output from kubectl cannot be provided, as API calls fail (I guess because K8s components are not up):
```
$ kubectl get node
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```

Other parts in the log show:
```
Feb 03 10:05:22 k3s-master-01 k3s[3138]: I0203 10:05:22.619186    3208 server.go:1111] Started kubelet
Feb 03 10:05:22 k3s-master-01 k3s[3138]: E0203 10:05:22.620872    3208 cri_stats_provider.go:375] Failed to get the info of the filesystem with mountpoint "/home/vagrant/.rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs": unable to find data in memory cache.
Feb 03 10:05:22 k3s-master-01 k3s[3138]: E0203 10:05:22.621124    3208 kubelet.go:1302] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
```
(But there is plenty of disk space left.)

**Additional context**
* `$ cat /etc/issue`: `Ubuntu 18.04.3 LTS`
* `$ uname -a`: `Linux xxxxxxxx 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* System is running on a VirtualBox VM (started with Vagrant using `ubuntu/bionic64`) on a local computer (no limited VPS or any cloud-based instance is in use)

**Comment by davidnuzik** [comment]
Assigned to QA to test and attempt to reproduce.

**Comment by AkihiroSuda** [comment]
Is this still an issue with the latest version?

**Comment by marcbrandner** [comment]
The same errors show up with `v1.17.3+k3s1`.
