### ISSUE TITLE
Reduce memory requirement for edge computing usecases

### ISSUE THREAD

**Issue by sureshsankaran** [k3s-io/k3s#1399]
**Is your feature request related to a problem? Please describe.**
For IoT usecases, like app/pod/container reading from sensor connected to node and pushing data to cloud/northbound, traditional k8s based distributed pod deployment with replicas, scaling, load-balancing are NOT very useful. 

Main goal here is we need one instance of app running in each nodes where sensor is connected and the app doesn't really need to talk east-west, as all it does is gathering sensor data and push it to northbound aggregator. To deploy this app on bunch sensor connected nodes, few ways to do it like using docker swarm or kubernetes/k3s. 

Docker swarm comes closer to solving this problem where you just have dockerd on IoT node and manage the apps from swarm master. But given docker EE is sold and swarm furture to be honest is bit skeptical. Coming to kubernetes, having regular kubelet and other components requires a LOT of RAM, CPU and Disk which won't be available in an average IoT Node. K3s solves this resource consumption problem quite a bit but still current requirement is like minimum 512MB RAM which is kind of bummer as it is at-least 5 times higher as one would have liked. 

Since our usecase doesn't need all fancy k8s controllers and features, can we further optimize k3s in terms of memory consumption to address this requirement ? Already k3s provides knobs for disabling few controllers, can we have more such knobs which can reduce the memory footprint ?

**Describe alternatives you've considered**
Docker swarm.

Thanks for doing great work!!

**Comment by carlosonunez** [comment]
In my limited experience with k3s, it bombs out with less than 512MB RAM even with a minimal Linux distribution like Alpine.

**Comment by brandond** [comment]
You can currently chase k3s down to a bit over 300mb of ram - including the datastore. Given that you can now get a Raspberry Pi with 8gb of memory for significantly less than $100, I'm not sure how much more cut down things can get. You can already disable all the embedded manifests and flannel - is there anything else you'd like to do without?
