### ISSUE TITLE
Set toleration, node-selectors for helm-install jobs

### ISSUE THREAD

**Issue by David-Igou** [k3s-io/k3s#1400]
**Is your feature request related to a problem? Please describe.**

When I deploy HelmChart objects, I want to control what node the job deploying them runs on.

**Describe the solution you'd like**

Some way to set a nodeSelector or Tolerations for these jobs. If this is already a feature, it doesn't appear to be documented anywhere. 

The implementation of the HelmController in k3s appears to differ from how its documented in its repo (There is no helm-controller pod in kube-system in k3s) so I don't even know where to start hacking a solution.

**Comment by g18yqu** [comment]
@David-Igou ever figure out a solution?

**Comment by brandond** [comment]
Helm-controller is over here, if you want to out in a PR:
https://github.com/k3s-io/helm-controller/blob/master/pkg/helm/controller.go#L184

**Comment by avEryALt** [comment]
Ended up reading the docs better, https://rancher.com/docs/k3s/latest/en/helm/, setting `spec.bootstrap=True` did the trick!

**Comment by g18yqu** [comment]
Ended up reading the docs closer after seeing the bootstrap option in the controller. Setting that to true got what I needed.
