### ISSUE TITLE
Traefik ingress controller dosen't listen on ports 80, 443, and 8080 on the host, but ramdon nodeport

### ISSUE THREAD

**Issue by thetruechar** [k3s-io/k3s#1414]
**Version:**
k3s version v1.0.0 (18bd921c)

**Describe the bug**
Traefik ingress controller dosen't listen on ports 80, 443, and 8080 on the host, but ramdon nodeport

**To Reproduce**
install the v1.0.0

**Expected behavior**
The Traefik ingress controller will use ports 80, 443, and 8080 on the host

**Actual behavior**
Traefik ingress controller listen on nodeport(like 30579)
 kubectl get svc --namespace=kube_system
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                     AGE
kube-dns         ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP                      97m
metrics-server   ClusterIP      10.43.162.222   <none>          443/TCP                                     97m
traefik          LoadBalancer   10.43.20.185    172.16.24.138   80:30579/TCP,443:30051/TCP,8080:32535/TCP   96m

**Comment by dabio** [comment]
traefik LoadBalancer 10.43.20.185 172.16.24.138 **80**:30579/TCP,**443**:30051/TCP,**8080**:32535/TCP 96m

The traefik service is listening on ports 80, 443 and 8080.

**Comment by thetruechar** [comment]
@dabio  no, I tried... only 30579 work for http...

**Comment by brandond** [comment]
Are your iptables rules broken or something? What OS is this on?

**Comment by thetruechar** [comment]
awsubuntu 18.04,  a brand new ECS in alibaba cloud(like aws ec2)

**Comment by davidnuzik** [comment]
Is this issue reproducible? What about on another platform? This should be working.

**Comment by glinkaf** [comment]
I am having the same issue. I did a takeover installation of k3os inside an Ubuntu 18.04 inside an Oracle Cloud VM.

k3os-master [~]$ kubectl get svc --namespace=kube_system
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       4h8m
metrics-server       ClusterIP      10.43.196.27    <none>        443/TCP                      4h8m
traefik-prometheus   ClusterIP      10.43.105.130   <none>        9100/TCP                     4h7m
traefik              LoadBalancer   10.43.247.164   10.0.0.27     80:30345/TCP,443:31768/TCP   4h7m

**Comment by glinkaf** [comment]
@brandond Your guess might fit for my issue ontop of k3os. The log of one of the Klipper Service Load Balancer Container:

`k3os-master [~]$ kubectl logs -n kube-system svclb-traefik-dhnnt lb-port-80
+ trap exit TERM INT
**/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system**
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '!=' 1 ]
+ iptables -t nat -I PREROUTING '!' -s 10.43.132.141/32 -p TCP --dport 80 -j DNAT --to 10.43.132.141:80
+ iptables -t nat -I POSTROUTING -d 10.43.132.141/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause`

I suppose that's related to k3os having a read-only file system approach. However, I wonder why this (probably) worked for others...

**Comment by thetruechar** [comment]
@davidnuzik  can you tell me why this should be working? 
I found that the k3s are not listening on 80, 443, so how can this work?

**Comment by davidnuzik** [comment]
Based on our suite of tests against Ubuntu 18.04 and CentOS7 this should work. I would review firewall rules, etc. You mentioned aws ec2 instances -- the security group has been set up correctly, etc?

**Comment by thetruechar** [comment]
I installed k3s again with no-traefik option, and install nginx-ingress helm with nodeports 30080 and 30443.
```
nginx-ingress-controller        LoadBalancer   10.43.101.91    172.16.55.78   80:30080/TCP,443:30443/TCP   9h
```
I found that k3s-serve is listening on port 30080 but not 80.
```
root@testing-k3s-master:~# lsof -i :30080
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
k3s-serve 2975 root  255u  IPv6  35407      0t0  TCP *:30080 (LISTEN)
```
But it still can visit the ingress by port 80, so how the k3s achieve this? by iptables?

**Comment by iam-TJ** [comment]
Confirming this too, the external interface is listening on the random port number not the servce port number.

```
$ kubectl get svc --namespace=kube_system
NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
kube-dns             ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP       19h
metrics-server       ClusterIP      10.43.56.99    <none>        443/TCP                      19h
traefik-prometheus   ClusterIP      10.43.218.74   <none>        9100/TCP                     19h
traefik              LoadBalancer   10.43.2.147    10.127.0.1    80:30046/TCP,443:30259/TCP   19h
```
On the master:
```
# ss -tnlp sport = 443
State           Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port           Process           
root@elloe01:~# ss -tnlp sport = 30259
State            Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port          Process           
LISTEN           0                4096                                   *:30259                                *:*              users:(("k3s-server",pid=16866,fd=284))
```
On one of the workers:
```
# ss -tnlp sport = 443
State           Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port           Process           
root@innovation00:~# ss -tnlp sport = 30259
State            Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port          Process           
LISTEN           0                4096                                   *:30259                                *:*              users:(("k3s-agent",pid=27726,fd=179))
```

**Comment by brandond** [comment]
Yes, this is how kubernetes (specifically kube-proxy) works. It listens on a random node port, and then uses iptables rules to masquerade traffic from the loadbalancer address and port to the appropriate node port.

```
brandond@seago:~$ kubectl get svc --namespace=traefik
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                     AGE
traefik   LoadBalancer   10.43.25.120   10.0.3.80     80:31417/TCP,443:31119/TCP,9000:31462/TCP   57d
```

```
brandond@seago:~$ sudo iptables -vnL -t nat | grep traefik/traefik:websecure
    0     0 KUBE-XLB-LODJXQNF3DWSNB7B  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* traefik/traefik:websecure loadbalancer IP */
    0     0 KUBE-XLB-LODJXQNF3DWSNB7B  all  --  *      *       10.0.3.80            0.0.0.0/0            /* traefik/traefik:websecure loadbalancer IP */
    0     0 KUBE-MARK-DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* traefik/traefik:websecure loadbalancer IP */
    0     0 KUBE-MARK-MASQ  tcp  --  *      *       127.0.0.0/8          0.0.0.0/0            /* traefik/traefik:websecure */ tcp dpt:31119
    0     0 KUBE-XLB-LODJXQNF3DWSNB7B  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* traefik/traefik:websecure */ tcp dpt:31119
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.42.0.0/16         10.43.25.120         /* traefik/traefik:websecure cluster IP */ tcp dpt:443
    0     0 KUBE-SVC-LODJXQNF3DWSNB7B  tcp  --  *      *       0.0.0.0/0            10.43.25.120         /* traefik/traefik:websecure cluster IP */ tcp dpt:443
    0     0 KUBE-FW-LODJXQNF3DWSNB7B  tcp  --  *      *       0.0.0.0/0            10.0.3.80            /* traefik/traefik:websecure loadbalancer IP */ tcp dpt:443
    0     0 KUBE-MARK-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* masquerade LOCAL traffic for traefik/traefik:websecure LB IP */ ADDRTYPE match src-type LOCAL
    0     0 KUBE-SVC-LODJXQNF3DWSNB7B  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* route LOCAL traffic for traefik/traefik:websecure LB IP to service chain */ ADDRTYPE match src-type LOCAL
    0     0 KUBE-MARK-DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* traefik/traefik:websecure has no local endpoints */
```

**Comment by iam-TJ** [comment]
In our case we're based on Ubuntu 20.04 and using the 'legacy' iptables and the various KUBE* chains and rules are in place. Despite all that its unclear why exposed services cannot be reached from the public IP addresses of the workers.

I suspect the original reporter on this issue has the same problem as we're seeing but came to the same conclusion as we did when the expected behaviour wasn't observed.

Like the original reporter we can only connect to the exposed services via the random port numbers from outside the cluster not the well-known service ports.

**Comment by iam-TJ** [comment]
I *think* I've figured out our issue.

Our master(s) are deployed on the office LAN. Workers are in remote data-centres. Because the cluster needs to be on its own sub-net to avoid PNAT/routing issues we've created a Wireguard VPN that the cluster uses on 10.127.0.0/16 with the master on 10.127.0.1.

On the master we can attach to traefik using HTTP (tested using telnet) but from the workers that fails (strange since the workers can reach the master via the 10.127.0.0/16 sub-net).

However, it is clear our issue is to do with our 'IoT' edge network requirements rather than a problem with traefik.

**Comment by imba-tjd** [comment]
I'm a new learner and I don't quite understand. I have previously set nginx listening on 80 and 443. Now I'm trying to install k3s. Does this issue mean they are not compatible?

**Comment by JasLin** [comment]
if you run traefik with root, it can bind 80 and 443
if you want to run traefik container with non root user, and bind to 80, it's not easy to do that. see [this issue](https://github.com/containous/traefik-library-image/issues/38)

**Comment by magixus** [comment]
have the same issue on fresh install (kubeadm way) on ubuntu 20.04.1 LTS 
> traefik is using normal ports 80, 443, 8080 forwarded to random ports
![image](https://user-images.githubusercontent.com/7642058/99897321-c6639c00-2c98-11eb-975d-df98c1d6860d.png)


> hosts are (very well configured, no mistake) 
![image](https://user-images.githubusercontent.com/7642058/99897345-f0b55980-2c98-11eb-9258-3b20a153113f.png)


> access normal ports from inside doesn't work 
![image](https://user-images.githubusercontent.com/7642058/99897360-12164580-2c99-11eb-8880-e91e191b8ae8.png)

> those normal ports are closed from outside
![image](https://user-images.githubusercontent.com/7642058/99897433-bbf5d200-2c99-11eb-86c5-fbc751f1b1d3.png)

> iptables modules and configuration are well loaded (no mistake):
![image](https://user-images.githubusercontent.com/7642058/99897483-1f7fff80-2c9a-11eb-813f-72b60823b03a.png)



even though everything is set correctly, i can't access traefik ports on my cluster. hope community could give as a clu on that
it has nothing to do with k8s i think it has something to do

**Comment by fox-md** [comment]
Faced the same issue. After doing some digging I found that hostPort is disabled by default in values.yml file. Traefik pods are reachable outside of k8s cluster over NodePort only. 
In order to fix it, try to set hostPort for both web and websecure:
`helm install traefik traefik/traefik --set service.type=NodePort --set ports.web.hostPort=80 --set ports.websecure.hostPort=443`

Once that is done, you should see dnat rules for ports 80 and 443 translating 

`[root@kubeworker01 ~]# iptables-save | grep "CNI-DN-"
:CNI-DN-93de6c3d8fbd2d47d8d5b - [0:0]
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"weave\" id: \"327a3792c563e30691f676dd650dcfff67c7d83fa51ff95bfdf7ffcc63386e63\"" -m multiport --dports 80,443 -j CNI-DN-93de6c3d8fbd2d47d8d5b
-A CNI-DN-93de6c3d8fbd2d47d8d5b -s 10.32.0.0/12 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-93de6c3d8fbd2d47d8d5b -s 127.0.0.1/32 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-93de6c3d8fbd2d47d8d5b -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.36.0.4:8000
-A CNI-DN-93de6c3d8fbd2d47d8d5b -s 10.32.0.0/12 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-93de6c3d8fbd2d47d8d5b -s 127.0.0.1/32 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-93de6c3d8fbd2d47d8d5b -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.36.0.4:8443
`

**Comment by fox-md** [comment]
Try to setup hostPort for web and websecure ports. That will create dnat rules in iptables.

**Comment by magixus** [comment]
> Try to setup hostPort for web and websecure ports. That will create dnat rules in iptables.

@fox-md you can't simply setup hostPort... am using a service with NodePort, setting hostport need to be in pods not in service ... and it's not working in both (i've tried)

Thank you.

**Comment by fox-md** [comment]
> @fox-md you can't simply setup hostPort... am using a service with NodePort, setting hostport need to be in pods not in service ... and it's not working in both (i've tried)
> 
> Thank you.

@magixus, 
My understanding is that putting hostPort into the picture creates dnat rules that help requests against ports 80 and 443 reach ingress pod. Without having hostPort, I do not quite understand what would make iptables create nat rules to route requests to ingress-controller service.

**Comment by magixus** [comment]
> Hi @magixus,
> My understanding is that putting hostPort into the picture creates dnat rules that help requests against ports 80 and 443 reach ingress pod.
> `[root@kubeworker01 ~]# iptables-save | grep "CNI-DN" | grep "to-destination"`
> `-A CNI-DN-051e5bdafb630d2c22b59 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.36.0.4:8000`
> `-A CNI-DN-051e5bdafb630d2c22b59 -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.36.0.4:8443`
> Without having hostPort, I do not quite understand what would make iptables create nat rules to route requests to ingress-controller service.

To be honest I didn't understand your replay, but I can tell that I've tried setting **hostPort** as well a long with my configurations and **it didn't work**. no DNAT routing has been created unfortunately.
any way I saved my journey with a startup script as following 

```sh
#!/bin/bash

#sleep 2m
TRAEFIK_IP=$(kubectl get pods -n kube-system -o wide | grep traefik | awk '{print $6}')


# check IP PREROUTING 
PREROUTING_IP=$(iptables -t nat -vnL PREROUTING --line-numbers | sed '/^num\|^$\|^Chain/d' | wc -l)
if [ "$PREROUTING_IP" == 4 ] ; then
	# update IP DNAT prerouting rules
	iptables -R PREROUTING 3 -t nat -i ens160 -p tcp --dport 80 -j DNAT --to $TRAEFIK_IP:80
	iptables -R PREROUTING 4 -t nat -i ens160 -p tcp --dport 443 -j DNAT --to $TRAEFIK_IP:443
elif [ "$PREROUTING_IP" == 2 ]; then 
	# create DNAT prerouting rules if they don't existe
	iptables -A PREROUTING -t nat -i ens160 -p tcp --dport 80 -j DNAT --to $TRAEFIK_IP:80
	iptables -A PREROUTING -t nat -i ens160 -p tcp --dport 443 -j DNAT --to $TRAEFIK_IP:443
fi

# check IP FORWARD 
FORWARD_IP=$(iptables -vnL FORWARD --line-numbers | sed '/^num\|^$\|^Chain/d' | wc -l)
if [ "$FORWARD_IP" == 12 ] ; then
	# update IP DNAT FORWARD rules
	iptables -R FORWARD 11 -p tcp -d $TRAEFIK_IP --dport 80 -j ACCEPT
 	iptables -R FORWARD 12 -p tcp -d $TRAEFIK_IP --dport 443 -j ACCEPT
elif [ "$FORWARD_IP" == 10 ]; then 
	# create DNAT FORWARD rules if they don't existe
	iptables -A FORWARD -p tcp -d $TRAEFIK_IP --dport 80 -j ACCEPT
 	iptables -A FORWARD -p tcp -d $TRAEFIK_IP --dport 443 -j ACCEPT
fi
``` 

What the script is doing is basically checking any PREROUTING and FORWARD rules and update or create them accordingly.

**Comment by magixus** [comment]
guys, found a very interesting workaround, 
setting **traefik** service spec type to :  **LoadBalancer**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: LoadBalancer
```

Then apply the config 
> if it show pending for a long time like this
> ![image](https://user-images.githubusercontent.com/7642058/106324991-641bae80-627a-11eb-8f87-a3d6851ca9dd.png)
> just patch the service with this following command and you'll be ok : 
> kubectl patch svc traefik -n kube-system -p '{"spec":{"externalIPs":["<VPS-or-VM-local-IP@"}}'
> you should see that SVC is getting the external IP like this 
>  ![image](https://user-images.githubusercontent.com/7642058/106325142-a04f0f00-627a-11eb-9e2b-290ebe335919.png)


and you look back to your system, you 'll find on master node services being exposed : 
![image](https://user-images.githubusercontent.com/7642058/106325237-cb396300-627a-11eb-8276-91df005a3ba5.png)

**Comment by idealtech-i3dlabs** [comment]
OMG --- This fixed it for me!!!

> guys, found a very interesting workaround,
> setting **traefik** service spec type to : **LoadBalancer**
> 
> ```yaml
> apiVersion: v1
> kind: Service
> metadata:
>   name: traefik
>   namespace: kube-system
> spec:
>   type: LoadBalancer
> ```
> 
> Then apply the config
> 
> > if it show pending for a long time like this
> > ![image](https://user-images.githubusercontent.com/7642058/106324991-641bae80-627a-11eb-8f87-a3d6851ca9dd.png)
> > just patch the service with this following command and you'll be ok :
> > kubectl patch svc traefik -n kube-system -p '{"spec":{"externalIPs":["<VPS-or-VM-local-IP@"}}'
> > you should see that SVC is getting the external IP like this
> > ![image](https://user-images.githubusercontent.com/7642058/106325142-a04f0f00-627a-11eb-9e2b-290ebe335919.png)
> 
> and you look back to your system, you 'll find on master node services being exposed :
> ![image](https://user-images.githubusercontent.com/7642058/106325237-cb396300-627a-11eb-8276-91df005a3ba5.png)

**Comment by pojntfx** [comment]
Sadly, this workaround does not work for me. Fresh install of Debian 10 (and Fedora 33). This sort of breaks the default installation process.

**Comment by brandond** [comment]
You shouldn't need to do that - creating the LB pods and then setting the externalIP field based on the addresses of the nodes running the pods is exactly what the servicelb controller is supposed to do. See how you've got the same IP listed twice now?

**Comment by pojntfx** [comment]
Exactly; the pods all run properly, but if the IP has been added twice it works. svclb pods run fine, bith before and after adding the IP a second time.

**Comment by brandond** [comment]
Yes, that is how it works. It doesn't bind to the node port directly. It binds to a random port in the pod, and the ServiceLB pod programs iptables rules to forward the traffic from the host port to the pod port. It is not expected that you will see it actually listening on the host ports.

**Comment by pojntfx** [comment]
@brandond Thanks for the insight! I naively assumed that they would just bind so I evaluated with `iproute2`'s `ss` and didn't even test reachability from the outside. Works as expected now:

```bash
# Test VM@DO
root@debian-s-1vcpu-1gb-ams3-01:~# curl -sfL https://get.k3s.io | sh -
root@debian-s-1vcpu-1gb-ams3-01:~# k3s kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   helm-install-traefik-9d7bl                0/1     ContainerCreating   0          20s
kube-system   local-path-provisioner-5ff76fc89d-slrbk   0/1     ContainerCreating   0          19s
kube-system   metrics-server-86cbb8457f-4vx7s           1/1     Running             0          19s
kube-system   coredns-854c77959c-92p5b                  0/1     Running             0          19s
# Local Linux system
[pojntfx@felixs-xps13 ~]$ curl 188.166.84.48
curl: (7) Failed to connect to 188.166.84.48 port 80: Connection refused
# Test VM@DO
root@debian-s-1vcpu-1gb-ams3-01:~# k3s kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-86cbb8457f-4vx7s           1/1     Running     0          40s
kube-system   local-path-provisioner-5ff76fc89d-slrbk   1/1     Running     0          40s
kube-system   coredns-854c77959c-92p5b                  1/1     Running     0          40s
kube-system   helm-install-traefik-9d7bl                0/1     Completed   0          41s
kube-system   traefik-6f9cbd9bd4-dmtss                  0/1     Running     0          17s
kube-system   svclb-traefik-9n4rv                       2/2     Running     0          17s
# Local Linux system
[pojntfx@felixs-xps13 ~]$ curl 188.166.84.48
404 page not found
```

**Comment by kerberjg** [comment]
I think I was able to figure it out, at least **if Calico is involved**.
It essentially comes down to this: https://github.com/projectcalico/calico/issues/4842

Basically, Calico disables IP forwarding, preventing svclb from functioning the way @brandond mentions.
Since they fail to set up forwarding, they get stuck in a CrashLoopBackOff state.

My solution:

1. Download `https://docs.projectcalico.org/master/manifests/custom-resources.yaml`
2. Add the following lines:
```
spec:
  calicoNetwork:
    containerIPForwarding: Enabled
```
3. Apply your `custom-resources.yaml` to the `tigera-operator` namespace
4. Use @magixus 's external IP patch for good measure (probably not necessary) -> https://github.com/k3s-io/k3s/issues/1414#issuecomment-770038893
5. In the `kube-system` namespace remove pods starting with `svclb` so they can get recreated
6. Profit!

You will not see the port listening in `ss -tlnp` because, as @brandond said, it just forwards from 80/443 to the random NodePorts using iptables.
If everything else is configured well and you attempt to connect to your cluster's external IP on ports 80/443 you should see your service :)

**Comment by buzanits** [comment]
The trick with 
`kubectl patch svc traefik -n kube-system -p '{"spec":{"externalIPs":["192.168.178.54"]}}' `
did it also for me (of course with a different IP). I think the main problem is, that I do not have a pod `svclb-traefik-*`. I installed traefik with helm. I also tried to reinstall it. But this pod never appeared.

**Comment by WowMuchName** [comment]
It seems this issue still exists. After performing an update on Ubuntu 22 today networking was broken for me. I had an FTP server using node port and several services behind the build-in traefik ingress. None of it worked anymore showing the symptoms outlined in this issue.

The solutions outlined in this thread did not resolve the problem. I needed to uninstall k3s via the script, which returned the IP-Tables rules back to defaults, then reinstall k3s. Now it works again. Not the biggest of deals since I had everything encapsulated as helm charts and only run k3s on a workstation. Makes me hesitant to use k3s for production workloads though.

Would it be possible to introduce a self-healing mechanism that examines and repairs network related configuration like ip-tables upon server start? Or maybe a script / commandline switch that does this on demand without having to loose all deployed workloads?

**Comment by sdekna** [comment]
> Ubuntu 22

I have the same issue... tried uninstalling using the provided script and reinstalling again, but doesn't seem to work. Traefik listens in a random port still.

**Comment by brandond** [comment]
I am going to lock this, as there seems to be ongoing confusion in this thread about how ports work in Kubernetes.

1. The traefik process listens on the configured ports **within the pod**, not on the host itself. There are exceptions to this rule if the pod uses host network, but traefik does not.
2. The traefik service is assigned random node ports that pass traffic from the service to the pods.
3. The load-balancer controller pods (svclb) use hostPorts to occupy the requested service ports (80/443), and add iptables rules to forward traffic from the service ports, to the nodeport, to the pods.

If anyone has questions about configuring traefik ingress resources, please check the [Traefik Community Forums](https://community.traefik.io/), or open a new discussion thread.
