### ISSUE TITLE
Is it possible to use AWS ECR as repository for K3S running on AWS EC2

### ISSUE THREAD

**Issue by urupaud** [k3s-io/k3s#1427]
We have a k3s cluster which is running on AWS ec2, we want to deploy containers into this cluster using images in our AWS ECR, is this possible ?

**Comment by HuJake** [comment]
We also want to ask this question.

**Comment by brandond** [comment]
It appears that containerd does not support external credential helpers like docker does. See: https://github.com/containerd/cri/issues/1131

**Comment by HuJake** [comment]
@brandond  thanks your reply my question.

We have changed it to docker but after setting the following flag

```
--kubelet-arg = "cloud-provider = external" --kubelet-arg = "provider-id = aws: /// $ (curl -s http://169.254.169.254/latest/meta-data/placement/ availability-zone) / $ (curl -s http://169.254.169.254/latest/meta-data/instance-id) "
```
Seems unable to solve..
It seems there is no information to refer to

**Comment by bigbohne** [comment]
not nice but you can always generate the `/etc/rancher/k3s/registries.yaml` using crontab ...

**Comment by brandond** [comment]
@HuJake did you actually install the out-of-tree aws cloud provider, set up the aws credential helper, and configure docker registry auth to use the helper?

@bigbohne will it actually re-read it, or is it just loaded on startup? I couldn't tell.

**Comment by HuJake** [comment]
@brandond 

I simply set the relevant flag,

```
k3s server 
--docker
--kubelet-arg = "cloud-provider = external" \
--kubelet-arg = "provider-id = aws: /// $ (curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)/$(curl -s http: / /169.254.169.254/latest/meta-data/instance-id) "
```

I'm want to use [aws cloud provider] but not sure how to apply related yaml?
Are there references to successful cases?
thanks

**Comment by brandond** [comment]
@HuJake All that does is set the ID. If you want a full cloud provider you can find deployment documentation at https://github.com/kubernetes/cloud-provider-aws . For authenticating to ECR you would want https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by bigbohne** [comment]
With docker as container engine this is easily possible using the ecr-credential-helper. But what about containerd? Or is it a design decision to not include plugable authenticators?

**Comment by brandond** [comment]
The containerd folks seem to have philosophical issues that preclude them from adding support for pluggable authentication.

**Comment by bigbohne** [comment]
Than it is what it is ...

**Comment by brandond** [comment]
@bigbohne see https://github.com/containerd/cri/issues/1131#issuecomment-631633816

**Comment by canadiannomad** [comment]
> will it actually re-read it, or is it just loaded on startup? I couldn't tell.

I'm wondering the same... I can easily write a cronjob to grab new creds, but restarting k3s every time....?

**Comment by studiocredo** [comment]
We are running k3s with docker as container engine here. I installed and configured the amazon-ecr-credential-helper.
I can successfully `docker pull` images from our private ECR repo as a regular user, but k3s itself keeps complaining with ErrImagePull.

A `kubectl describe pod` shows: `Failed to pull image "***": rpc error: code = Unknown desc = Error response from daemon: Get https://***: no basic auth credentials`

So my understanding of this is that the kubelet service (running inside a docker container) cannot pull the image because it does not know about the credential helper. Any pointers on how to overcome this?

**Comment by brandond** [comment]
Probably related: https://github.com/awslabs/amazon-ecr-credential-helper/issues/210

**Comment by studiocredo** [comment]
I was able to solve/work around this by deploying [registry-creds](https://github.com/upmc-enterprises/registry-creds) in my cluster (this is basically what the registry-creds addon in Minikube is doing)

**Comment by KennyReeldata** [comment]
I was able to get auth working with K3s by slightly editing this script for my needs: https://stackoverflow.com/a/55658863
Requires the aws cli to be installed on your servers

**Comment by johnlane** [comment]
Just in case it's useful.... I'm running k3s locally with the docker backend and I was able to pull from ecr using information from [here](https://stackoverflow.com/a/55658863) and [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry).

**Comment by mandrean** [comment]
@urupaud I got it working by:

1. `$ git clone github.com/upmc-enterprises/registry-cred`
2. Edit `k8s/deployment.yaml` and `secret.yaml` to suit your needs. For me, I removed everything ACR/GCR/DPR and only kept the ECR stuff.
3. `$ kubectl apply -f k8s/`
4. Add `awsecr-cred` as an image pull secret to any deployment using images in ECR:
```
imagePullSecrets:
  - name: awsecr-cred
```

**Comment by moonape1226** [comment]
@mandrean 
Your solution above works like a charm on my on-premises K3S cluster. Thanks a lot.
