### ISSUE TITLE
Namespace's Status Terminating  Not delete 

### ISSUE THREAD

**Issue by liyongxian** [k3s-io/k3s#1432]
**Version:**

k3s version v1.17.0+k3s.1 (0f644650)

**Describe the bug**

Can not delete namespace,its status is Terminating,but Not events of deleting namespace.
**To Reproduce**

**Expected behavior**

kubectl delete ns xxx
**Actual behavior**

**Additional context**

**Comment by a01fe** [comment]
I've run into this when there's a problem with `metrics-server`. See: <https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-429754733>

This might be related to #1433 too.
