### ISSUE TITLE
BAD Certificate --> High Availability with Embedded DB

### ISSUE THREAD

**Issue by gioalex** [k3s-io/k3s#1442]
**Version:**
k3s version v1.17.2+k3s1 (cdab19b0)

**Describe the bug**
I can get the first server node to work but when I try to install the second one I receive a TLS handshake error.

Logs from first node:
Feb 22 21:33:10 raspi4 k3s[21804]: I0222 21:33:10.675986   21804 log.go:172] http: TLS handshake error from 192.168.1.86:44222: remote error: tls: bad certificate
Feb 22 21:33:29 raspi4 k3s[21804]: I0222 21:33:29.736448   21804 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io

Logs from second node:
I0222 21:43:52.695745   32085 interface.go:400] Looking for default routes with IPv4 addresses
I0222 21:43:52.695865   32085 interface.go:408] Default route transits interface "eth0"
I0222 21:43:52.696171   32085 interface.go:208] Interface eth0 is up
I0222 21:43:52.696317   32085 interface.go:256] Interface "eth0" has 2 addresses :[192.168.1.86/24 fe80::1858:8959:5f01:63f1/64].
I0222 21:43:52.696390   32085 interface.go:223] Checking addr  192.168.1.86/24.
I0222 21:43:52.696419   32085 interface.go:230] IP found 192.168.1.86
I0222 21:43:52.696450   32085 interface.go:262] Found valid IPv4 address 192.168.1.86 for interface "eth0".
I0222 21:43:52.696473   32085 interface.go:414] Found active IP 192.168.1.86
I0222 21:43:52.696508   32085 services.go:51] Setting service IP to "10.43.0.1" (read-write).
time="2020-02-22T21:43:52.696557387+01:00" level=info msg="Starting k3s v1.17.2+k3s1 (cdab19b0)"
time="2020-02-22T21:43:53.051802119+01:00" level=fatal msg="starting kubernetes: preparing server: https://192.168.1.242:6443/v1-k3s/server-bootstrap: 403 Forbidden"

**To Reproduce**
Install first server with this command:
curl -sfL https://get.k3s.io | INSTALL_K3S_exec="server --cluster-init --docker --tls-san raspi4 -v 5 --log /tmp/k3s.log --bind-address 192.168.1.242" sh -s -

Install second server with this command:
curl -sfL https://get.k3s.io | K3S_TOKEN=K1053dba120a32f879180bda159552777d21d477664896569ba449a91ed34c61b24::server:7f5803735f055e195e40a288f346b8e4 INSTALL_K3S_EXEC="server --tls-san raspi42 -v 5 --log /tmp/k3s.log"  K3S_URL=https://192.168.1.242:6443 sh -s -

**Expected behavior**
A spreaded cluster formed..

**Actual behavior**
TLS error

**Additional context**
Platform raspberry pi 4 with raspbian Linux raspi4 4.19.97-v7l+ #1294 installed
openssl version --> 1.1.1d  10 Sep 2019

**Comment by Moep90** [comment]
@gioalex  Have you tried to specifiy the K3S-Token explicit?
 

First Server
```shell
$ curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_exec="server --cluster-init --docker --tls-san raspi4 -v 5 --log /tmp/k3s.log --bind-address 192.168.1.242" sh -s -
```

Second Server:
```shell
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_EXEC="server --tls-san raspi42 -v 5 --log /tmp/k3s.log" K3S_URL=https://192.168.1.242:6443 sh -s -
```

**Comment by gioalex** [comment]
@Moep90 Thank you Danny for your response!

Nothing changed, I'm still getting TLS error on first server and 403 on the second.

I'm going crazy on this problem..

**Comment by brandond** [comment]
* Completely remove the current installations and reinstall using an explicit token for both hosts as per @Moep90's example.
* Get name resolution working. Add stuff to the hosts file if you have to, but things will be much happier if you use hostnames, and those hostnames (both short and fqdn) all resolve properly from both hosts.

**Comment by gioalex** [comment]
- Removed both installations with k3s-uninstall.sh

- Checked name resolution --> working

- Installed both servers with these commands:
  **First server:**
  curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_exec="server --cluster-init --docker --tls-san raspi4 -v 5 --log /tmp/k3s.log " sh -s -
  **Second server:**
  curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_EXEC="server --tls-san raspi42 -v 5 --log /tmp/k3s.log" K3S_URL=https://raspi4.local:6443 sh -s -

Unfortunately nothing changed.
I've also checked time on both servers and their are aligned.

**Comment by gioalex** [comment]
Just tried to find some files from previous installation with:

find / -name "*k3s*"

and removed everything.

After that I've tried to reinstall k3s but swapping the first and the second server but again, nothing changed in result; again bad certificate.

**Comment by castironclay** [comment]
https://github.com/rancher/k3s/issues/163#issuecomment-469882207

**Comment by castironclay** [comment]
`root@master1:~# k3s kubectl get nodes`
`NAME      STATUS   ROLES    AGE   VERSION`
`worker4   Ready    <none>   15m   v1.17.3+k3s1`
`worker3   Ready    <none>   13m   v1.17.3+k3s1`
`master2   Ready    master   18m   v1.17.3+k3s1`
`master1   Ready    master   36m   v1.17.3+k3s1`
`worker1   Ready    <none>   15m   v1.17.3+k3s1`
`worker2   Ready    <none>   15m   v1.17.3+k3s1`
`worker5   Ready    <none>   15m   v1.17.3+k3s1`
</br>
**Preporatory Steps**
I ensured both `/etc/hosts` were updated for the respective hostnames as well as ensuring both master1 and master2 had 127.0.0.1 and 127.0.1.1 added to their /etc/hosts. Shortcut command for that is below.</br> `echo 127.0.1.1 $(hostname) >> /etc/hosts; echo 127.0.0.1 $(hostname) >> /etc/hosts`
</br>
The steps I took are below for each master node
**Command for Master1**
`curl -sfL https://get.k3s.io | K3S_TOKEN="randomstring" INSTALL_K3S_EXEC=”server --cluster-init --docker --no-deploy=traefik” sh -s -
`</br>
Grab the token from Master1 to be used for the Master2 command
`cat /var/lib/rancher/k3s/server/node-token`
**Command for Master**
`curl -sfL https://get.k3s.io | K3S_TOKEN="token_from_master1" INSTALL_K3S_EXEC="server  --server https://master1:6443 --docker --no-deploy=traefik" sh -s -`

The initial command on Master2 reported a failure but after checking the k3s service and giving it about 60 seconds it popped in on master1.

**Comment by gioalex** [comment]
@castironclay thankyou!

I've checked every point you mentioned.
Now I can get a successful installation but cluster still not working.

On the first node I see that, if I don't specify the bind address, k3s start listeing on 127.0.0.1 so, I changed the installation command as follow:
**Master1**
curl -sfL https://get.k3s.io | K3S_TOKEN="randomstring" INSTALL_K3S_EXEC=”server --cluster-init --bind-address=192.168.1.242 --docker --no-deploy=traefik” sh -s -

Then I see that, **on node Master2**, installation try to connect to server 127.0.0.1.
When I try to force Master2's configuration to connect to the right address with the command:

k3s kubectl config set clusters.default.server https://_<Master1_ipaddress>_ 

the command **k3s kubectl get nodes** (issued on Master2) give me Master1 in a ready status but, after a while, configuration return on his original state and start again to connect to 127.0.0.1.

Please feel free to ask any clarification in case I wasn't clear in my description.

**Comment by castironclay** [comment]
Try changing `--bind-address` to `--advertise-address` for the Master1 command.

**Comment by gioalex** [comment]
@castironclay  Tried.

Added --advertise-address on Master1 because, if I leave only --advertise-address, listeing address after installation is localhost. So, new command for install Master1 node is:

curl -sfL https://get.k3s.io | K3S_TOKEN="randomstring" INSTALL_K3S_EXEC=”server --cluster-init --advertise-address=192.168.1.242 --bind-address=192.168.1.242 --docker --no-deploy=traefik” sh -s -

Uninstalled Master2 and re-installed with the same command described above (but with the ).

Result --> nothing changed. I've to change by hand the server address and, after a while, it return to localhost.

Here the commands issued to check configuration:

root@master2:~# k3s kubectl config view; k3s kubectl config set clusters.default.server "https://master1:6443"; k3s kubectl get nodes; sleep 15; k3s kubectl get nodes; k3s kubectl config view

---
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: **https://127.0.0.1:6443**
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: xxxxxxxxx
    username: admin
---
Property "clusters.default.server" set.
---
NAME     STATUS   ROLES    AGE   VERSION
Master1   Ready    master   42m   v1.17.3+k3s1
---
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
---
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: xxxxxxxx
    username: admin

root@master2:~# 




Sorry for the layout but I can't get nothing best of this result...

**Comment by castironclay** [comment]
Not sure if you're a Slack user but if you join that we can have some easy back and forth. Then if we come to a conclusion you can post it here. I have the same username on there: CastIronClay
https://slack.rancher.io/

**Comment by linuxmail** [comment]
Hello,

I have the very same issue:

* Version: v1.19.2+k3s1
* Three nodes
* **OS: K3OS**

The initial cluster works, after installing the master and the other two nodes ( via cloud-init file ) .. but .. If I shutdown one or two of the nodes (n2 + n3) and booting up again:

```
level=fatal msg="starting kubernetes: preparing server: failed to get CA certs at https://fra-corp-node-01.office.ina:6443/cacerts: https://fra-corp-node-01.office.ina:6443/cacerts: 503 Service Unavailable"
```
On the first node (which had --cluster-init)
```
...
time="2020-11-24T10:27:03.876682988Z" level=info msg="Cluster-Http-Server 2020/11/24 10:27:03 http: TLS handshake error from 192.168.43.53:57862: remote error: tls: bad certificate"
2020-11-24 10:27:06.592275 W | rafthttp: health check for peer 5a9c780c87ef232 could not connect: dial tcp 192.168.43.53:2380: connect: connection refused
2020-11-24 10:27:06.592868 W | rafthttp: health check for peer 5a9c780c87ef232 could not connect: dial tcp 192.168.43.53:2380: connect: connection refused
2020-11-24 10:27:06.604366 W | rafthttp: health check for peer a8ea6ec75aff0f56 could not connect: dial tcp 192.168.43.54:2380: connect: connection refused
2020-11-24 10:27:06.611941 W | rafthttp: health check for peer a8ea6ec75aff0f56 could not connect: dial tcp 192.168.43.54:2380: connect: connection refused
time="2020-11-24T10:27:06.779964675Z" level=info msg="Cluster-Http-Server 2020/11/24 10:27:06 http: TLS handshake error from 192.168.43.54:50730: remote error: tls: bad certificate"
raft2020/11/24 10:27:08 INFO: bbe5bb207c710269 is starting a new election at term 60
raft2020/11/24 10:27:08 INFO: bbe5bb207c710269 became candidate at term 61
raft2020/11/24 10:27:08 INFO: bbe5bb207c710269 received MsgVoteResp from bbe5bb207c710269 at term 61
raft2020/11/24 10:27:08 INFO: bbe5bb207c710269 [logterm: 2, index: 7382] sent MsgVote request to 5a9c780c87ef232 at term 61
raft2020/11/24 10:27:08 INFO: bbe5bb207c710269 [logterm: 2, index: 7382] sent MsgVote request to a8ea6ec75aff0f56 at term 61
time="2020-11-24T10:27:09.931470245Z" level=info msg="Cluster-Http-Server 2020/11/24 10:27:09 http: TLS handshake error from 192.168.43.53:57866: remote error: tls: bad certificate"
....
```
So a reboot / shutdown one or more nodes is enough, to have a non working K3S cluster.

I have no /var/lib/rancher/k3os/config.yaml yet. Do I need it for start with --cluster-init again ?

I had before the setup with external MariaDB and that was working, also with shutdown / reboots.

cu denny

**Comment by dharmendrakariya** [comment]
@gioalex I was having the same issue earlier when I was trying to add Node2 and Node3 to Node1's cluster (this guy was initiating with --cluster-init) manually( didn't use cloudinit files in first try).

however they were not being added with the same certs error, and I figured out that may be that's because when you bring up k3Os it  brings up own cluster being master(server node) itself (when you installing it and choosing 'server' option ). and so it would have its own certs generated by default. after that when you try to make it join the Node1 it will clash the certs and throw this error. (please correct my knowledge @brandond if this is not the case)

I solved this issue by using cloudinit file mentioned [here](https://github.com/rancher/k3os/issues/613)

**Comment by brandond** [comment]
Please don't use v1.19.2+k3s1 or any of the other early releases with experimental managed etcd support. There are newer releases of 1.19 available that may fix some of the issues you're describing.

**Comment by linuxmail** [comment]
It works with newer versions fine. I’ve tried it with a replaced k3s version for a K3OS image. Also there is a new dev5 version released, a few minutes ago for k3os.

**Comment by dharmendrakariya** [comment]
great!! will try and update the issue.
