### ISSUE TITLE
Ability to disable embedded helm controller

### ISSUE THREAD

**Issue by ivan046** [k3s-io/k3s#1445]
Is it possible to turn off K3S helm controller so it won't conflict with manually managed newer helm controller deployment from rancher's repo?

Adding `--disable-helm-controller` server installation argument will help a lot!
Thanks in advance.

**Comment by brandond** [comment]
For the record, the helm controller in Rancher does not conflict with the one built in to K3s, as they do not watch the same CRD types. It is still useful to have an option to disable helm-controller though.

**Comment by rancher-max** [comment]
#### Validated this is working in v1.22.2+k3s1

- Not using the flag allows k3s to continue working as expected
- The flag is now present for `k3s server` and is working as expected when passed both as an exec arg or via the config.yaml file
- Using the flag does **not** install helm resources by default (traefik and traefik crd), as expected
- Using the flag **does** leave the crds for `helmcharts.helm.cattle.io` and `helmchartconfigs.helm.cattle.io`, as expected

**Comment by bo0tzz** [comment]
This flag is only documented in the HA installation guides, but seems to be missing from pages like the [server config reference](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components).
