### ISSUE TITLE
How can I use the cloud-controller-manager for aws?

### ISSUE THREAD

**Issue by carlosrmendes** [k3s-io/k3s#1447]
How can I use and configure the cloud-controller-manager for aws? If I set the `--kube-cloud-controller-manager-arg=cloud-provider=aws` the k3s won't with something like _"aws is not a valid cloud provider"_ in the logs.

**Comment by Bessonov** [comment]
dupe of https://github.com/k3s-io/k3s/issues/1177

**Comment by brandond** [comment]
You should use the external cloud provider for whatever platform you're using: https://github.com/kubernetes/cloud-provider-aws#readme

**Comment by nurhun** [comment]
I'm trying to use cloud-provider-aws, I'm getting daemonset installed with desired 0. Checking the manifest https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/aws-cloud-controller-manager-daemonset.yaml , noticed that `nodeSelector:node-role.kubernetes.io/master: ""`, while in` k3s nodes nodeSelector:node-role.kubernetes.io/master=true`.
I tried to modify values manually to "true", it worked and LB initiated successfully. I'm wondering what's the proper behavior here?

**Comment by brandond** [comment]
node roles are essentially arbitrary. It might be worth noting that `master` is being replaced with `control-plane` upstream.

**Comment by nurhun** [comment]
I see, there are 2 labels` node-role.kubernetes.io/control-plane=true` & `node-role.kubernetes.io/master=true`. Anyways, I overcame it by applying `kubectl label node --all --overwrite node-role.kubernetes.io/master=""` as part of the installation script, however, I don't think it should be there in the manifest at all.
