### ISSUE TITLE
http: TLS handshake error from ... :59309: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by ndjhartman** [k3s-io/k3s#1452]
**Version:**

k3s version v1.17.2+k3s1 (cdab19b0)

**Describe the bug**

When attempting to connect local k3s agent to EC2 k3s server, k3s server logs report:
`http: TLS handshake error from ... :59313: remote error: tls: bad certificate`

Agent logs:
`Feb 24 17:42:25 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:42:25.318584810-05:00" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""`

`Feb 24 17:42:26 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:42:26.432472774-05:00" level=info msg="Updating load balancer server addresses -> [...  ...:587]"`

`Feb 24 17:42:26 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:42:26.432843527-05:00" level=info msg="Connecting to proxy" url="wss://...:587/v1-k3s/connect"`

`Feb 24 17:44:37 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:44:37.363270503-05:00" level=error msg="Failed to connect to proxy" error="dial tcp ...:587: connect: connection timed out"`

`Feb 24 17:44:37 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:44:37.363349247-05:00" level=error msg="Remotedialer proxy error" error="dial tcp ...:587: connect: connection timed out"`

**To Reproduce**

Server (EC2)
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --tls-san internal_ip --tls-san external_ip --https-listen-port 587" sh -`

Agent (local):
`curl -sfL https://get.k3s.io | K3S_URL=https://$public_ip:587 K3S_TOKEN=$token sh -`

**Expected behavior**

K3s agent connects to K3s server

**Actual behavior**
K3s agent fails to connect to K3s server

**Additional context**

**Comment by ndjhartman** [comment]
After enabling debug mode on the server, I notice the following error immediately after the `tls: bad certificate` line:

`Feb 25 15:44:16 ip-172-31-35-19 k3s[7176]: I0225 15:44:16.578490    7176 log.go:172] http: TLS handshake error from 128.224.252.2:41832: remote error: tls: bad certificate`

`Feb 25 15:44:16 ip-172-31-35-19 k3s[7176]: time="2020-02-25T15:44:16.677096180Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1`

After searching for that message, I find it's in a Docker related file?

`find . -name '*.*' | xargs grep 'FIXME: Got an status-code for which error does not match any expected type!!!' 2>/dev/null`

`./vendor/github.com/docker/docker/errdefs/http_helpers.go:		}).Debugf("FIXME: Got an status-code for which error does not match any expected type!!!: %d", statusCode)`

Will continue investigating.

**Comment by ndjhartman** [comment]
Appears to be unrelated as it appears several times in the log without attempted connections from the agent. 

Not a clue what's causing the issue then.

**Comment by brandond** [comment]
What SANs are on your ec2 k3s server's certificate? Is it valid for the EC2 instance's public IP, or just the private?

**Comment by ndjhartman** [comment]
Assuming I'm doing this correctly:

`kubectl get secret -o yaml k3s-serving -n kube-system`
`echo "tls.crt" | base64 --decode | openssl x509 -noout -text`

`X509v3 Subject Alternative Name:`
`DNS:public_dns ... IP Address:private_ip, IP Address:public_ip`

So I believe so. I added every IP under the sun with the `--tls-san` flag with no success

**Comment by brandond** [comment]
The agent itself is just reporting connection timeout:
```
Feb 24 17:44:37 yow-nhartman-lx k3s[18979]: time="2020-02-24T17:44:37.363349247-05:00" level=error msg="Remotedialer proxy error" error="dial tcp ...:587: connect: connection timed out"
```
Can you do a simple curl test to confirm connectivity to the remote host?
`curl -vks https://<public_dns>:587/`

**Comment by ndjhartman** [comment]
Sorry about that. I had the security wide open to try debug the issue, I've since tightended it. Here are the unadultered logs:

Server:
`Feb 25 20:40:55 ip-172-31-35-19 k3s[20848]: I0225 20:40:55.067028   20848 log.go:172] http: TLS handshake error from 128.224.252.2:22934: remote error: tls: bad certificate`

Agent:
`Feb 25 20:41:06 yow-nhartman-lx k3s[19334]: time="2020-02-25T20:41:06.734438562Z" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""`
`Feb 25 20:41:07 yow-nhartman-lx k3s[19334]: time="2020-02-25T20:41:07.851456120Z" level=info msg="Connecting to proxy" url="wss://172.31.35.19:873/v1-k3s/connect"`
`Feb 25 20:43:18 yow-nhartman-lx k3s[19334]: time="2020-02-25T20:43:18.316157449Z" level=error msg="Failed to connect to proxy" error="dial tcp 172.31.35.19:873: connect: connection timed out"`
`Feb 25 20:43:18 yow-nhartman-lx k3s[19334]: time="2020-02-25T20:43:18.316236936Z" level=error msg="Remotedialer proxy error" error="dial tcp 172.31.35.19:873: connect: connection timed out"`

SANs:
`X509v3 Subject Alternative Name: `
`DNS:ec2-18-221-152-110.us-east-2.compute.amazonaws.com, DNS:ip-172-31-35-19, DNS:ip-172-31-35-19.us-east-2.compute.internal, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:172.31.35.19, IP Address:18.221.152.110`

Curl result:

> *   Trying 18.221.152.110:873...
* TCP_NODELAY set
* Connected to ec2-18-221-152-110.us-east-2.compute.amazonaws.com (18.221.152.110) port 873 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=k3s; CN=k3s
*  start date: Feb 25 19:02:47 2020 GMT
*  expire date: Feb 24 19:02:48 2021 GMT
*  issuer: CN=k3s-server-ca@1582657367
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873
> User-Agent: curl/7.65.3
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Www-Authenticate: Basic realm="kubernetes-master"
< Date: Tue, 25 Feb 2020 20:45:16 GMT
< Content-Length: 165
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
* Connection #0 to host ec2-18-221-152-110.us-east-2.compute.amazonaws.com left intact

**Comment by ndjhartman** [comment]
If I pass it the server-ca.crt file, the error is slightly better, but still the same core issue:

`sudo curl -vs https://ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873 --cacert /var/lib/rancher/k3s/agent/server-ca.crt`

```
*   Trying 18.221.152.110:873...
* TCP_NODELAY set
* Connected to ec2-18-221-152-110.us-east-2.compute.amazonaws.com (18.221.152.110) port 873 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/lib/rancher/k3s/agent/server-ca.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=k3s; CN=k3s
*  start date: Feb 25 19:02:47 2020 GMT
*  expire date: Feb 24 19:02:48 2021 GMT
*  subjectAltName: host "ec2-18-221-152-110.us-east-2.compute.amazonaws.com" matched cert's "ec2-18-221-152-110.us-east-2.compute.amazonaws.com"
*  issuer: CN=k3s-server-ca@1582657367
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873
> User-Agent: curl/7.65.3
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Www-Authenticate: Basic realm="kubernetes-master"
< Date: Tue, 25 Feb 2020 22:11:07 GMT
< Content-Length: 165
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
* Connection #0 to host ec2-18-221-152-110.us-east-2.compute.amazonaws.com left intact
```

**Comment by ndjhartman** [comment]
So after connecting manually to the public dns via chrome `https://ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873` I was able to succesfully log in with the kubectl login.

After further research I came across the following issues which I think are more relevant:

https://github.com/rancher/k3s/pull/881
https://github.com/rancher/k3s/issues/986

Not sure how to proceed. That pull request seems to be what I need but it hasn't seen attention since October...

**Comment by brandond** [comment]
Yeah, I think that's probably the issue. Now that you've posted some unredacted logs it's pretty clear that the agent is trying to connect up to the server's private IP, not the public:

```Feb 25 20:43:18 yow-nhartman-lx k3s[19334]: time="2020-02-25T20:43:18.316236936Z" level=error msg="Remotedialer proxy error" error="dial tcp 172.31.35.19:873: connect: connection timed out"```

Have you tried playing with the `--bind-address` at all? I'm not sure how that affects the cluster networking though. It may just not work properly with NAT in between the server and agents, or you may have to muck about with name resolution so that the hostname that the server advertises itself as resolves to an address that the agents can resolve and reach.

**Comment by ndjhartman** [comment]
I ended up forking v1.17.2+k3s1, and making the changes referenced in this PR ((PR)[https://github.com/rancher/k3s/pull/881]), and built the binary. Adding the --server-public flag completely resolved the issue.

I would love to see that functionality natively in K3S. 

I will give the --bind-address flag a go though, I hadn't seen that flag.

**Comment by ndjhartman** [comment]
After trying the --bind-address with the public DNS, I get the same issue but on the server this time:

```
Feb 26 18:32:16 ip-172-31-35-19 k3s[730]: time="2020-02-26T18:32:16.632950073Z" level=info msg="Connecting to proxy" url="wss://172.31.35.19:873/v1-k3s/connect"
Feb 26 18:32:16 ip-172-31-35-19 k3s[730]: time="2020-02-26T18:32:16.633747308Z" level=error msg="Failed to connect to proxy" error="dial tcp 172.31.35.19:873: connect: connection refused"
Feb 26 18:32:16 ip-172-31-35-19 k3s[730]: time="2020-02-26T18:32:16.633916832Z" level=error msg="Remotedialer proxy error" error="dial tcp 172.31.35.19:873: connect: connection refused"
```

Then, after running the server with `--disable-agent` I don't get the errors on the server, but can't connect at all one the agent:

```
ERRO[2020-02-26T18:35:10.746416196Z] failed to get CA certs at https://127.0.0.1:33303/cacerts: Get https://127.0.0.1:33303/cacerts: read tcp 127.0.0.1:35718->127.0.0.1:33303: read: connection reset by peer 
```

So for now I will continue using the `--server-public` flag provided by that PR as a good work around. Ideally this would be better integrated into K3S though.

**Comment by agilob** [comment]
I'm having this issue too but with local dns resolution. I initialized server with:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san rpi4.lan" sh -
```

and connected node with:

```
curl -sfL https://get.k3s.io | K3S_URL=https://rpi4.lan:6443 K3S_TOKEN=<<token>> sh -
```

After a few restarts of worker nodes I'm getting:

```
level=info msg="Connecting to proxy" url="wss://[fd73:ffaf:c5ab::665]:6443/v1-k3s/connect"
level=error msg="Failed to connect to proxy" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 146.90.112.113, 146.90.112.38, 192.168.1.153, not fd73:ffaf:c5ab::66
level=error msg="Remotedialer proxy error" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 146.90.112.113, 146.90.112.38, 192.168.1.153, not fd73:ffaf:c5ab::665"
level=info msg="Connecting to proxy" url="wss://[fd73:ffaf:c5ab::665]:6443/v1-k3s/connect"
level=error msg="Failed to connect to proxy" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 146.90.112.113, 146.90.112.38, 192.168.1.153, not fd73:ffaf:c5ab::66
level=error msg="Remotedialer proxy error" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 146.90.112.113, 146.90.112.38, 192.168.1.153, not fd73:ffaf:c5ab::665"
```

IP address of nodes didn't change, they have a lease for a month. Should the cert be valid for rpi4.lan too?
Not sure, but might be related to https://github.com/rancher/rke2/issues/518


> and built the binary. Adding the --server-public flag to the agent completely resolved the issue.

This doesn't work for me

>time="2021-03-25T11:51:32Z" level=fatal msg="flag provided but not defined: -server-public"
> k3s-agent.service: Main process exited, code=exited, status=1/FAILURE


```
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

**Comment by brandond** [comment]
K3s does not currently support ipv6. Please make sure that you don't have any ipv6 records for your nodes. Note that when using .local addresses you may actually be relying on avahi/mdns - you should either have a private zone with records you control, or use hosts file entries.
