### ISSUE TITLE
storageClassName: local-path is not removable and prevents using NFS

### ISSUE THREAD

**Issue by avarf** [k3s-io/k3s#1454]
**Version:**
```bash
k3s -v
k3s version v1.17.2+k3s1 (cdab19b0)
```
K3s installed via k3sup and I used the default values.

**Describe the bug**

Hi, I am new to k3s and I just installed a k3s single node cluster using k3sup. Things are working properly except the storage.

I am using NFS in my applications and I have no problem for setting up an NFS server and use it on normal k8s but k3s doesn't recognise NFS:
```bash
kubectl describe pvc gstreamer-claim 

Name:          gstreamer-claim
StorageClass:  local-path
Status:        Pending
Volume:        gstreamer-dir
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      0
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    gstreamer-processor-0
               mediaserver-648bc745bb-6bscs
Events:
  Type     Reason          Age                    From                         Message
  ----     ------          ----                   ----                         -------
  Warning  VolumeMismatch  54s (x841 over 3h30m)  persistentvolume-controller  Cannot bind to requested volume "gstreamer-dir": storageClassName does not match
```

And
```bash
kubectl get pvc gstreamer-claim -o yaml 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-02-25T12:14:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: gstreamer-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: gstreamer-wws
status:
  phase: Pending
```
The thing is k3s automatically added the `storageClassName: local-path` and I am not able to remove it (on k8s this line doesn't exists at all).

I followed the solution mentioned at https://github.com/rancher/k3s/issues/390 and I installed the `nfs-client-provisioner` but there was no change and everything are exactly the same.

How I can use NFS on k3s?

**Expected behavior**
NFS should work out of the box similar to official K8s

**Comment by brandond** [comment]
Did you create a NFS StorageClass as part of installing nfs-client-provisioner? Did you update your PVC to use the NFS storageClassName instead of still referring to the local path provisioners's StorageClass?

**Comment by avarf** [comment]
I installed the helm chart of nfs-client-provisioner and NFS storage class is part of that helm chart: https://github.com/helm/charts/blob/master/stable/nfs-client-provisioner/templates/storageclass.yaml

Yes I tried to update but k3s always replaced it with the local-path.

**Comment by brandond** [comment]
Yes, you can't just edit an existing PVC to change it to another Storage Class. You have to delete it and recreate it so that the thing you're claiming (the Persistent Volume) can be provisioned on the correct provider.

**Comment by BartoszKaszewczuk** [comment]
I observed the same issue when trying to use k3s with NFS provider.

1. Fresh k3s cluster with master node only
2. `helm install nfs-client-provisioner stable/nfs-client-provisioner --set nfs.server=mynfs.share --set nfs.path=/volumes/nfs`
3. Make `local-path` a non-default `StorageClass`
4. Mark new NFS provider as default `StorageClass`
5. `kubectl get pv` returns no pvs
6. Delete local-path provider like mentioned in their docs using `kubectl delete -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml`
7. Delete `deployment.apps/local-path-provisioner`
8. Reboot cluster node and `local-path` is installed again, marked as default as entire cluster gets trashed until it becomes unresponsive to any `kubectl` command.

Perhaps this happens because of `k3s` default deployments in `kube-system` namespace but why if supposedly there are no registered PVC attached to `local-path`?
How to drop `local-path` StorageClass entirely from k3s?

**Comment by brandond** [comment]
If you want to remove built-in components like traefik or local-storage, you need to disable them or they will come back every time you restart the server:

https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components. In your case, I think you want`--disable=local-storage`

**Comment by brandond** [comment]
Also, you should probably be specifying the appropriate storageClassName in your PVCs, rather than relying on a specific StorageClass being set to default.

**Comment by BartoszKaszewczuk** [comment]
Thanks @brandond for a pointer in the right direction.  
`--disable` flag has been deprecated and replaced with `--no-deploy` so `--no-deploy local-storage` did it.
I tested deployment of a cluster with NFS support and with the flag had no more issues after restarts.
I submitted a PR to update the docs: https://github.com/rancher/docs/pull/2475

**Comment by brandond** [comment]
@BartoszKaszewczuk you've got it backwards, no-deploy is deprecated and disable is the one you should be using.

**Comment by BartoszKaszewczuk** [comment]
Interesting. Just double checked and it looks like the "latest" version of k3s pulled by `k3sup` is 2 releases behind. Revered the PR.
