### ISSUE TITLE
UDP service reachable only by the node where the pod is

### ISSUE THREAD

**Issue by Oznup** [k3s-io/k3s#1471]
**Version:** k3s version v1.17.3+k3s1 (5b17a175)
For masters : 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--docker --no-deploy traefik --no-deploy servicelb --node-label master-1 --datastore-endpoint 'postgres://Login:Password@DB_HOST:DB_PORT/k3s'" sh -s -
For workers : 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--docker" K3S_URL=https://LOADBALANCER_IP:6443 K3S_TOKEN=TOKEN sh -

**Describe the bug**
Hello,
I have a self hosted multi master cluster in which I try to set up a DNS service in UDP, but I have an issue and I can't get rid of it.

Let's explain :
I have 2 masters and 4 workers, and when I deploy my service, I can reach it this way :
`dig @service-ip hostname` BUT it works only on the node where the pod is located.
If I call the pod directly by doing `dig @pod-ip hostname`, it works from any node.

I've tried `iptables -P FORWARD ACCEPT` on every node, but it hasn't changed anything.
Note : I've tried the same in TCP, everything works fine !

**To Reproduce**
- Install a multi master cluster on bare metal / VM (Debian 10 in my case)
- Create a DNS service listening to UDP port 53
- Install **dnsutils** on every node
- Locate the pod where the DNS the pod is located by doing `kubectl get pods -o wide`

**Expected behavior**
- On every node : `dig @pod-ip hostname` --> OK
- On the node containing the pod : `dig @service-ip hostname` --> OK
- On the other nodes : `dig @service-ip hostname` --> OK
- From anywhere : `dig @external-ip hostname` --> OK

**Actual behavior**
- On every node : `dig @pod-ip hostname` --> OK
- On the node containing the pod : `dig @service-ip hostname` --> OK
- On the other nodes : `dig @service-ip hostname` --> NOK
- From anywhere : `dig @external-ip hostname` --> Same behaviour as using service-ip

**Additional context**
K3s based on Docker (no Containerd)
2 Masters and 4 Workers dispatched in 2 physical machines, Keepalived as Load Balancer installed on the masters to expose one single K3s API IP
Hypervisor XCP-ng, the K3s nodes are on Debian 10 VM (no openstack)
MetalLB as Load Balancer
Nginx Ingress Controller

Thank's for helping :)

Oznup

**Comment by Oznup** [comment]
Hello,

Finally found a solution there : https://github.com/kubernetes/kubernetes/issues/52783
I had to user **ipsec** instead of **vxlan** (by default) as flannel backend.
I have torn down and set up again my whole cluster, and the issue also appeared on the fresh install.
So I think this is a real bug and you'll be able to reproduce it.

BUT !!! Since I have passed on ipsec, I have another problem.
Some of my pods can't reach some services.
I can't see any reason why... Some services can be reached, some of them can't, it seems totally random.
Any idea?

Oznup

**Comment by txomon** [comment]
@Oznup would you say this is something like what I described in #1613 ?

**Comment by Oznup** [comment]
Hello @txomon,
Actually I had the symptoms you describe when I used vxlan, and only on UDP services.
Since I have switched on ipsec, the connectivity problem was totally random that have been solved by a solution which has absolutely nothing to do with it.
My CoreDNS has in its configmap 3 Upstream DNS :
- my internal DNS (the cause of this thread)
- 8.8.8.8 (Google)
- 8.8.4.4 (Google)
I removed the Google DNS, and now it works... ¯\_(ツ)_/¯

**Comment by Oznup** [comment]
Hello @txomon, something new happened !
I have had to set up my cluster again.
With exactly the same steps, it behaves exactly as described in the issue you mentionned : [#1613](https://github.com/rancher/k3s/issues/1613).
I've also tried with vxlan, same behaviour.
The only differences are:
- swapoff -a before installing the cluster
- the version of k3s (v1.17.3+k3s1 before, v1.17.4+k3s1 now)
