### ISSUE TITLE
kubectl to cluster over IPv6 breaks on invalid k3s-secrets metadata

### ISSUE THREAD

**Issue by ohthehugemanatee** [k3s-io/k3s#1478]
**Version:**
`k3s version v1.17.3+k3s1 (5b17a175)`
Installed with curl | shell commands from the doco. 
from `cluster1`: `curl -sfL https://get.k3s.io | sh -`
from `cluster2`: `-sfL https://get.k3s.io | K3S_URL=https://cluster1:6443 K3S_TOKEN=... sh -`

**Describe the bug**
After a no-problem setup, and validating that both nodes are visible when running `kubectl` from the server itself, I copied k3s.yaml from the server to my own laptop as `.kube/config`, changed the hostname in it, and tried to connect with `kubectl`. Every command gave the same error: 

```
» kubectl api-resources                                                                                                                                           
NAME   SHORTNAMES   APIGROUP   NAMESPACED   KIND
Unable to connect to the server: remote error: tls: internal error
```

On the server, `systemctl status -l k3s` shows me this in the logs:
```
Mar 02 20:12:15 cluster1 k3s[515]: time="2020-03-02T20:12:15.038982749+01:00" level=info msg="Updating TLS secret for k3s-serving (count: 10): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.1.172:192.168.1.172 listener.cattle.io/cn-192.168.1.41:192.168.1.41 listener.cattle.io/cn-2a02:8109:a280:2288:d2bc:91bb:d4dd:8f7c:2a02:8109:a280:2288:d2bc:91bb:d4dd:8f7c listener.cattle.io/cn-cluster1:cluster1 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:bf10edbb053df795ba8f29a2ef40cc43a4c589ef08b06d6079b4d647852c24bb]"
Mar 02 20:12:15 cluster1 k3s[515]: I0302 20:12:15.075099     515 log.go:172] http: TLS handshake error from 192.168.1.111:52950: Secret "k3s-serving" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-2a02:8109:a280:2288:d2bc:91bb:d4dd:8f7c": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

I had a look at the `k3s-serving` secret, and it has a metadata entry for all the ways the listening interface might be addressed. The value it tries to assign in that error message is based on the server's IPv6 address. 

If I change my `.kube/config` to point to the IPv4 address of the server, everything works. Clearly my local DNS server is returning the IPv6 address of `cluster1`. When `kubectl` tries to connect, k3s tries to add that metadata entry and fails, because `:` is not a valid character.

**To Reproduce**

Try to use kubectl over IPv6

**Expected behavior**
The server should respond.

**Actual behavior**
The server is unable to add the IPv6 address to the metadata of the `k3s-serving` secret, and fails to establish a TLS connection.

**Comment by sharpone74** [comment]
I'm seeing this issue as well.

With command:
```
▶ kubectl get nodes
Unable to connect to the server: remote error: tls: internal error
```

On master `journalctl -ft k3s`

```
Apr 02 03:10:20 kube-master k3s[668]: time="2020-04-02T03:10:20.524523120+01:00" level=info msg="Updating TLS secret for k3s-serving (count: 9): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.1.100:192.168.1.100 listener.cattle.io/cn-2601:681:8500:af:7684:3728:956f:9019:2601:681:8500:af:7684:3728:956f:9019 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:f6f4c0e25604e586826e2836eb298b00430ef61e643394c15027b999822efcaf]"
Apr 02 03:10:20 kube-master k3s[668]: I0402 03:10:20.547931     668 log.go:172] http: TLS handshake error from 192.168.1.1:62695: Secret "k3s-serving" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-2601:681:8500:af:7684:3728:956f:9019": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')```

**Comment by blake** [comment]
i was able to work around this error by editing `/var/lib/rancher/k3s/server/tls/dynamic-cert.json` on my master node, removing any IPv6 addresses (both keys & values), and restarting k3s (`systemctl restart k3s`).

Hopefully this is enough to keep things working until there's an official fix.
