### ISSUE TITLE
v1.17.2 + k3s1 cadvisor metrics are incorrect

### ISSUE THREAD

**Issue by 504274990** [k3s-io/k3s#1522]
**Version:**

v1.17.2+k3s1

**Describe the bug**

In the k3s v1.17.2 + k3s1 version, some metrics obtained by curl the kubernetes cadvisor API interface are missing some labs such as the container name. I compared it with k3s v1.15.4-k3s.1 version and k8s v1.17.2 version of kubernetes.

**To Reproduce**

This pod needs a service account with the correct permissions，$HOSTNAME is node hostname。You can also curl in  v1.15.4-k3s.1 version k3s to compare the metrics labels。
1、`TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)`
2、`curl -H "Authorization: Bearer $TOKEN" -k https://kubernetes.default.svc:443/api/v1/nodes/$HOSTNAME/proxy/metrics/cadvisor`

**Expected behavior**

**v1.15.4-k3s.1 metrics: this metrics label container name is correct**
`container_memory_working_set_bytes{container="node-exporter",container_name="node-exporter",id="/kubepods/burstable/pode2a26949-59dc-11ea-b2e6-c400ad30e5fd/ce80c5e890c9d8e9c39866b9ec2f2285fab5d1a30380083ba180d6268eb15c9c",image="sha256:e5a616e4b9cf68dfcad7782b78e118be4310022e874d52da85c55923fb615f87",name="k8s_node-exporter_prom-node-exporter-wd6c9_monitoring_e2a26949-59dc-11ea-b2e6-c400ad30e5fd_0",namespace="monitoring",pod="prom-node-exporter-wd6c9",pod_name="prom-node-exporter-wd6c9"} 1.25952e+07 1584003165568`

**Actual behavior**

**v1.17.2+k3s1 metrics: this metrics label container name is incorrect**
`container_memory_working_set_bytes{container="",id="/kubepods/burstable/podfe7e12f3-2912-480c-a5e0-05b79832de87",image="",name="",namespace="monitoring",pod="prom-node-exporter-zv7fd"} 2.2122496e+07 1584000987796`

**And miss this metrics**
`container_network_transmit_packets_total{container="POD",container_name="POD",id="/kubepods/burstable/pod801d6f16-32a8-11ea-b2e6-c400ad30e5fd/aec862b815534bfd381fc490642f539cff4cb2ac0613997f59234150e3d15ddb",image="k8s.gcr.io/pause:3.1",interface="eth0",name="k8s_POD_flume-57b6bbc975-qllg6_iot_801d6f16-32a8-11ea-b2e6-c400ad30e5fd_0",namespace="iot",pod="flume-57b6bbc975-qllg6",pod_name="flume-57b6bbc975-qllg6"} 1.51109154e+08 1584003548712`

**Additional context**

**Comment by 504274990** [comment]
I mean in v1.17.2 + k3s1 version, `container` has no value

**Comment by NicklasWallgren** [comment]
@504274990 Have you tried adding `--kubelet-arg containerd=/run/k3s/containerd/containerd.sock` as an statup option.

I'm able to retrieve container name using v1.17.3+k3s1.

**Comment by 504274990** [comment]
I use ` --kubelet-arg containerd=/run/containerd/containerd.sock` as an statup option, the  `container` 
 still has no value ... 
`container_memory_working_set_bytes{container="",id="/kubepods/burstable/pod935a0c15-53a3-4606-9aa0-f248c38388e",image="",name="",namespace="monitoring",pod="prom-node-exporter-gqb5t"} 2.0324352e+07 1584326161323`

**Comment by NicklasWallgren** [comment]
@504274990 Right, I can reproduce the issue using the --docker flag.

**Comment by 504274990** [comment]
> @504274990 Right, I can reproduce the issue using the --docker flag.

Now I  replaced with containerd, and  this metrics is normal

**Comment by brandond** [comment]
This issue is specific to the docker runtime, and should be fixed in recent releases. Either upgrade or use containerd until you can.
