### ISSUE TITLE
DNS resolution with k3s cluster is broken

### ISSUE THREAD

**Issue by c0dyhi11** [k3s-io/k3s#1527]
**Version:**

```bash
# k3s -v
k3s version v1.17.3+k3s1 (5b17a175)
```
**Describe the bug**

DNS resolution does not work within the cluster at all.
**To Reproduce**

1. Deploy vanilla k3s on Ubuntu 16.04
```bash
curl -sfL https://get.k3s.io | sh -
```
2. List services
```bash
# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   48m
```
3. Deploy busybox pod
```bash
# kubectl run -i -t busybox --image=busybox --restart=Never
If you don't see a command prompt, try pressing enter.
/ #
```
4. Do an nslookup for the `kubernetes` service you see above
```bash
/ # nslookup kubernetes
Server:		10.43.0.10
Address:	10.43.0.10:53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN
```
**Expected behavior**

On step 4 above you should resolve the correct IP Address.
```bash
# nslookup kubernetes
Server:		10.43.0.10
Address:	10.43.0.10:53

Name:	kubernetes.default.svc.cluster.local
Address: 10.43.0.1

*** Can't find kubernetes.svc.cluster.local: No answer
*** Can't find kubernetes.cluster.local: No answer
*** Can't find kubernetes.default.svc.cluster.local: No answer
*** Can't find kubernetes.svc.cluster.local: No answer
*** Can't find kubernetes.cluster.local: No answer
```
**Actual behavior**

The DNS server returns an NXDOMAIN...
```bash
/ # nslookup kubernetes
Server:		10.43.0.10
Address:	10.43.0.10:53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN
```
**Additional context**

I noticed this the first time around trying to change the cluster domain in order to use submariner. I figured it was a bug that has to do with that. But it seems as though this issue happens on vanilla installed clusters as well.

Any help would be appreciated.

**Comment by samirsss** [comment]
Bump - We're seeing this issue intermittently as well and would like some help or digging.

**Comment by tarioch** [comment]
What I noticed that the coredns has log errors like this

```
E0509 09:13:58.363970       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:58.363970       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:58.439475       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:58.439501       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.43.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:59.364700       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:59.440181       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:13:59.441288       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.43.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
E0509 09:14:00.365607       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused
```

So it looks to me like coredns is not able to reach kube api

**Comment by ShylajaDevadiga** [comment]
@c0dyhi11  Would you please try using 1.28.4 version of busybox
```
kubectl run -i -t busybox --image=busybox:1.28.4 --restart=Never
```
It seems to be an issue with specific busybox version as mentioned in this issue and not related to k3s or coredns
https://github.com/coredns/coredns/issues/2026

**Comment by davidnuzik** [comment]
The upstream issue is closed; we should look into this more. tried to follow the issues to see if there is an open issue to resolve. Or if this isn't going to be fixed upstream then we need to decide what our next steps are

**Comment by brandond** [comment]
Based on the errors in the coredns logs about an inability to reach the apiserver, I am curious if this might be related to some of the vxlan issues that were recently resolved - @tarioch are you able to upgrade to the latest version of whatever release you're on and see if you still experience this issue?

**Comment by mikkel1156** [comment]
I'm having the same issue, although when doing a nslookup test it succeeds:
```
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.43.0.1
```

However getting the same errors in CoreDNS.
No fix or workaround?

**Comment by mikkel1156** [comment]
Actually found a fix it seems from [another issue](https://github.com/k3s-io/k3s/issues/24#issuecomment-469759329) - which was a networking/iptables problem.

After that I also had to remove the `search mydomain.com` from my /etc/resolv.conf files before it could properly resolve other domains. That might just have been my setup though.

**Comment by mfrancisc** [comment]
as @mikkel1156 suggested , removing `search domain.com` from /etc/resolv.conf solved also for us. But this is a workaround, the search entry is needed for internal fqdn resolution.

Any updates about a permanent solution ?

**Comment by brandond** [comment]
Do you by any chance have a wildcard record for your domain that is preventing pods from finding services within the cluster?

**Comment by gsvachulay01** [comment]
My office VPN interfered with the name resolution on ubuntu. If you have a VPN try disconnecting or check host routes to make sure nothing's intercepting the DNS traffic from k3s.

**Comment by dereknola** [comment]
Closing issue. While people have continued to hit this, it appears to no be a configuration error in `/etc/resolv.conf` where wildcards or other entries are being appended to DNS results.
