### ISSUE TITLE
Add self-defined template configure file for embedded flannel

### ISSUE THREAD

**Issue by Encore222** [k3s-io/k3s#1531]
**Is your feature request related to a problem? Please describe.**
I wanna set flannel to vxlan backend and directrouting. And I also wanna the "network" field in flannel conf is auto-generated by k3s according to its cluster cidr. But in fact if I go to set vxlan backend and directrouting, the only way is to set --flannel-conf in k3s to a self-defined conf, and then the "network" field is also sel-defined, too. Since on a productive env, to define every agent's ip range is an unfriendly and uneasy work, it's more reasonable to make a self-defined template of flannel conf to instantiate a real conf by args of k3s agent.

I got this by reading the source code in [pkg/agent/flannel/setup.go](https://github.com/rancher/k3s/blob/master/pkg/agent/flannel/setup.go)
`
func createFlannelConf(nodeConfig *config.Node) error {
	if nodeConfig.FlannelConf == "" {
		return nil
	}
	if nodeConfig.FlannelConfOverride {
		logrus.Infof("Using custom flannel conf defined at %s", nodeConfig.FlannelConf)
		return nil
	}
	confJSON := strings.Replace(flannelConf, "%CIDR%", nodeConfig.AgentConfig.ClusterCIDR.String(), -1)

	var backendConf string

	switch nodeConfig.FlannelBackend {
	case config.FlannelBackendVXLAN:
		backendConf = vxlanBackend
	case config.FlannelBackendHostGW:
		backendConf = hostGWBackend
	case config.FlannelBackendIPSEC:
		backendConf = strings.Replace(ipsecBackend, "%psk%", nodeConfig.AgentConfig.IPSECPSK, -1)
		if err := setupStrongSwan(nodeConfig); err != nil {
			return err
		}
	case config.FlannelBackendWireguard:
		backendConf = wireguardBackend
	default:
		return fmt.Errorf("Cannot configure unknown flannel backend '%s'", nodeConfig.FlannelBackend)
	}
	confJSON = strings.Replace(confJSON, "%backend%", backendConf, -1)

	return util.WriteFile(nodeConfig.FlannelConf, confJSON)
}
`

**Describe the solution you'd like**
We can add an additional parameter to k3s agent like '--flannel-conf-tpl' to set a template of flannel conf. And render a real conf for embedded flannel.

**Describe alternatives you've considered**
1. Add a new parameter as above described. (can extend to other field in flannel conf)
2. Let driectrouting be a k3s' parameter passed by user. (simple and direct, but limit)
3. Reuse the '--flannel-conf' to set a template file, and rander it no matter what it is, a normal file or a template file. Then  generate a new conf for the embedded flannel. (maybe lead to confusion)

**Comment by Encore222** [comment]
@davidnuzik Do I need to commit my code？

**Comment by rbrtbnfgl** [comment]
Do we still need it? It feels like another flannel flag.

**Comment by caroline-suse-rancher** [comment]
Closing due to age, and potential redundancy - can reopen if it becomes more important.
