### ISSUE TITLE
chcon: can't apply partial context to unlabeled file '/usr/local/bin/k3s'

### ISSUE THREAD

**Issue by arranf** [k3s-io/k3s#1543]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
`curl -sfL https://get.k3s.io | sh -`

**Describe the bug**
When installing on Raspbian lite (2020-02-03) on both master and agent nodes this error occurs
`chcon: can't apply partial context to unlabeled file '/usr/local/bin/k3s'`

**To Reproduce**
Setup a Raspbian lite Raspberry Pi 4 4GB and run the script.

**Expected behavior**
No error to occur.

**Actual behavior**
The error occurs!

**Additional context / logs**
```
[INFO]  Finding latest release
[INFO]  Using v1.17.3+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.3+k3s1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.17.3+k3s1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
chcon: can't apply partial context to unlabeled file '/usr/local/bin/k3s'
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

**Comment by javachen** [comment]
me too
```
$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

$ docker --version
Docker version 19.03.8, build afacb8b

$ k3s --version
k3s version v1.17.3+k3s1 (5b17a175)
```

**Comment by brandond** [comment]
Does this result in an actual failure, or are you just not expecting to see the message? It looks like the intent is to hide both stdout and stderr from the chcon command, but the shell output redirection is bad - it first sends stderr to /dev/null, then to stdout.

https://github.com/rancher/k3s/blob/master/install.sh#L393

**Comment by jfmatth** [comment]
I get the same thing on Ubuntu 18.03, and it never seems to start properly

**Comment by biels** [comment]
Same as @jfmatth

**Comment by jfmatth** [comment]
Weird, VERY Weird, tried everything again, and even though i get the chcon error, K3s comes up fine.

I'm wondering if it's a debian / library issue that got resolved today?

**Comment by jfmatth** [comment]
Sadly, same behavior from previous version too, if the firewalld is running, no route to host on a lot of the pod startup.  turn it off, and pods come up fine.

For reference, I merely install firewallD on my ubuntu VM's, and it's automatically opens port 22 for SSH, and I manually open 80 and 443 after install.

**Comment by jfmatth** [comment]
Good news (and sorry for all the posts) - Using UFW on Ubuntu seems to work!

Not sure the differences here, but it solves what i need today :)

Hope this helps everyone

**Comment by brandond** [comment]
This issue was for the chcon error, I'm not sure why everyone is talking about iptables and firewalld in here.

**Comment by arranf** [comment]
> Does this result in an actual failure, or are you just not expecting to see the message? It looks like the intent is to hide both stdout and stderr from the chcon command, but the shell output redirection is bad - it first sends stderr to /dev/null, then to stdout.
> 
> https://github.com/rancher/k3s/blob/master/install.sh#L393

Just to confirm everything else works fine it's just scary when installing.

**Comment by jfmatth** [comment]
> > Does this result in an actual failure, or are you just not expecting to see the message? It looks like the intent is to hide both stdout and stderr from the chcon command, but the shell output redirection is bad - it first sends stderr to /dev/null, then to stdout.
> > https://github.com/rancher/k3s/blob/master/install.sh#L393
> 
> Just to confirm everything else works fine it's just scary when installing.

sorry for the confusion, yes, the message doesn't seem related to the FW comments.
