### ISSUE TITLE
Guide to Integrate with LINBIT's LINSTORE

### ISSUE THREAD

**Issue by fire** [k3s-io/k3s#1544]
**Is your feature request related to a problem? Please describe.**

I would like K3S to cluster storage resources with the current commands.

> curl -sfL https://get.k3s.io | K3S_URL=https://myserver:6443 K3S_TOKEN=XXX sh -

Distributed Kubernetes storage is difficult. K3S can exceed the storage of a single system. Streamlined instructions are lacking. Many alternatives are slow and technically complicated.

> Situations where a PhD in k8s clusterology is infeasible

The above quote about infeasiblity of k8s clusterology is related to the above goals.

**Describe the solution you'd like**

Would like a guide to setup K3S with LINBIT's LINSTORE.

Can contribute time on documentation.

**Describe alternatives you've considered**

K3S with local path provisioner. - Limited to single node. No migration.

K3S with ROOK / CEPH. - Many moving parts. Performance is slower.

K3S with OPENEBS - Performance is slower.

**Additional context**
This is not entirely a K3S feature request, but I don't know where to put this request.

https://www.linbit.com/drbd-user-guide/users-guide-linstor/

https://vitobotta.com/2020/01/04/linstor-storage-the-kubernetes-way/

**Comment by fire** [comment]
No movement, I switched to openebs.

**Comment by unixfox** [comment]
you can still let this issue open even if you moved to another storage solution
