### ISSUE TITLE
[Documentation] CentOS7 support and any necessary firewall config

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1556]
We plan to add official support for CentOS7. We need to document this on the install requirements page https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/ and we also need to mention any additional config required for firewalld for CentOS7. Additionally, we should look into explaining how to work with ufw as well (may need its own issue).

**Comment by p-hash** [comment]
Recently I've tried to set up k3s on CentOS 7 with firewalld enabled. These rules pretty much resolve it for me

```
firewall-cmd --permanent --add-port=6443/tcp # flannel
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 # pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 # services
firewall-cmd --reload
```

**Comment by leandrosolagna** [comment]
2 nights in a row and I've just came across this. I am using CentOS 8 with firewalld. Thank you, @p-hash. These commands worked for me.

**Comment by pavelanni** [comment]
Thanks, @p-hash ! It helped a lot!

**Comment by dbuchwald** [comment]
Thanks, @p-hash, I have just tested it in Fedora 35 and it works like a charm. I hope the documentation is updated.

**Comment by jarekdziedzic** [comment]
Thank you @p-hash. This resolved it for me as well on Fedora 37 and k3s version v1.25.4+k3s1 (0dc63334).

**Comment by coyzeng** [comment]
> Recently I've tried to set up k3s on CentOS 7 with firewalld enabled. These rules pretty much resolve it for me
> 
> ```
> firewall-cmd --permanent --add-port=6443/tcp # flannel
> firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 # pods
> firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 # services
> firewall-cmd --reload
> ```

But centos stream wont work.
