### ISSUE TITLE
k3s failing on datastore-endpoint

### ISSUE THREAD

**Issue by brittocj** [k3s-io/k3s#1573]
k3s service failing on datastore-endpoint execution. With usr/local/bin/k3s server --datastore-endpoint=mysql:// is working fine. When giving an IP address and details like /usr/local/bin/k3s server --datastore-endpoint=mysql://kube:KubesOwnPassword@tcp(192.168.1.11:3306)/kube_db it fails.

**Find following status of k3s service:**
```
# service k3s status
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-03-24 14:06:14 GMT; 3s ago
     Docs: https://k3s.io
  Process: 13095 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 13096 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 13097 ExecStart=/usr/local/bin/k3s server --datastore-endpoint=mysql://kube:KubesOwnPassword@tcp(192.168.1.11:3306)/kube_db (code=exited, status=1/FAILURE)
 Main PID: 13097 (code=exited, status=1/FAILURE)
```

**Comment by davidnuzik** [comment]
Does the issue still occur when you avoid using a special char in the dbname like:
kube_db change to kubedb
