### ISSUE TITLE
kube-bench spike

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1574]
The purpose of this issue is to track any effort required to take a look at kube-bench and what pain points are, incompatibilities, etc.

We need to get an understanding of what issues we may have so we can start planning on what changes we may need to make in order to be more compatible with kube-bench as we would like to support it.

As we learn more we may create one or more github issues; any milestones are subject to change.

Additional Info:
If we can just provide our own config for kube-bench and it's more or less just one arg to pass to the config that can work too. However, if there are a lot of non-standard parths and configurations then it's too much of a deviations for some customers to accept.

Some feedback:
- kubeadm seems to work fine out of the box with kube-bench and properly reports the CIS benchmark findings without passing any special flags/args.

**Comment by davidnuzik** [comment]
Related: https://github.com/rancher/k3s/issues/1504

**Comment by slapula** [comment]
kube-bench tries to match the Main PID name with the actual command running the process.  k3s doesn't work with it out of the box because these two values are not the same. In this case of an agent, kube-bench looks for the command associated with what k3s sets as the name of the Main PID `k3s-agent` but what it finds is `/usr/local/bin/k3s`.  It's expecting to find `/usr/local/bin/k3s-agent`.

```$ kubectl logs kube-bench-s667r -f
I1004 14:17:06.679145  245865 common.go:303] Kubernetes version: "" to Benchmark version: "k3s-1.0"
I1004 14:17:06.679385  245865 util.go:116] Looking for config specific CIS version "k3s-1.0"
I1004 14:17:06.679411  245865 util.go:120] Looking for file: cfg/k3s-1.0/node.yaml
I1004 14:17:06.681676  245865 common.go:235] Using config file: cfg/k3s-1.0/config.yaml
I1004 14:17:06.681995  245865 common.go:80] Using test file: cfg/k3s-1.0/node.yaml
I1004 14:17:06.682081  245865 util.go:69] ps - proc: "k3s-agent"
I1004 14:17:06.720968  245865 util.go:76] ps - returning: "/usr/local/bin/k3s agent --flannel-iface eth0 --server https://k3s-master:6443\n"
I1004 14:17:06.721112  245865 util.go:218] reFirstWord.Match(/usr/local/bin/k3s agent --flannel-iface eth0 --server https://k3s-master:6443)
I1004 14:17:06.721393  245865 util.go:218] reFirstWord.Match()
I1004 14:17:06.721439  245865 util.go:248] executable 'k3s-agent' not running
I1004 14:17:06.721471  245865 util.go:69] ps - proc: "k3s"
I1004 14:17:06.755382  245865 util.go:73] [/bin/ps -C k3s -o cmd --no-headers]: exit status 1
I1004 14:17:06.755429  245865 util.go:76] ps - returning: ""
I1004 14:17:06.755562  245865 util.go:218] reFirstWord.Match()
I1004 14:17:06.755581  245865 util.go:248] executable 'k3s' not running
W1004 14:17:06.755640  245865 util.go:96] 
Unable to detect running programs for component "agent"
The following "worker node" programs have been searched, but none of them have been found:
	- k3s-agent
```

**Comment by slapula** [comment]
I nailed down the function that manages this behavior: https://github.com/aquasecurity/kube-bench/blob/master/cmd/util.go#L199-L225

**Comment by thejan2009** [comment]
I've opened [a discussion](https://github.com/aquasecurity/kube-bench/discussions/1178) on kube-bench discussions about this.

**Comment by cwayne18** [comment]
As we support CIS benchmarks, I don't think this is relevant anymore, closing out.

**Comment by thejan2009** [comment]
@cwayne18 are you sure? `kube-bench` merely automates the CIS benchmark controls where possible. Alternatives are either another tool doing pretty much the same or verifying all the controls manually which is a time-consuming and error-prone process.

**Comment by brandond** [comment]
We support verifying CIS Benchmark controls via the CIS Operator which can be deployed from Rancher. We're not going to do it as part of K3s.
