### ISSUE TITLE
state.db-wal grown too large

### ISSUE THREAD

**Issue by VladoPortos** [k3s-io/k3s#1575]
Any idea what is in state.db-wal ? 
It grown to 8+GB within a month or so... is it something that can be cleaned up, or how can I find out why it is filling up so much ?

**Comment by clook** [comment]
I had the same issue (16 GB file, leading to pod eviction).
I could vacuum the following way without problem (not sure how safe it is though):
```
systemctl stop k3s
sqlite3 /var/lib/rancher/k3s/server/db/state.db
sqlite> vacuum;
sqlite> .quit
```
The file  /var/lib/rancher/k3s/server/db/state.db-wal is not there anymore.

If the vacuum has to be implemented, a specific issue should imo go there: https://github.com/rancher/kine

**Comment by Locus99** [comment]
I had a similar situation where the file got to an amazing 177GB in size.  Running those commands got rid of that file.  Will follow up if there are any issues from running the commands.

**Comment by brandond** [comment]
We should probably evaluate either enabling auto-vacuum, or manually vacuuming at intervals or at startup since auto-vacuum cannot be enabled on existing databases.

**Comment by brandond** [comment]
For anyone encountering this in the future - could you comment here? We'd like to know more about the workload and perhaps collect some statistics from your database.

**Comment by brandond** [comment]
Closing this issue as it does not appear to be affecting anyone any longer. If someone does run into this, please collect information on the sqlite database as described above and open a new issue.

**Comment by andrewwebber** [comment]
Unfortunately I experience this issue on K3OS on AWS. Due to the minimal OS it is difficult to execute sqlite3 on the host.

I have make the following workaround for anyone on K3OS or a minimum / cloud OS

https://github.com/andrewwebber/k3os-db-vacuum
