### ISSUE TITLE
question: for loadbalancer, why I can direct connect the container port?

### ISSUE THREAD

**Issue by thetruechar** [k3s-io/k3s#1577]
```
kubectl  get svc
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)       AGE
proxy-lb  LoadBalancer   10.43.209.160   172.16.55.78   1210:32432/TCP  4h35m
```
why I can access the service by port 1210(the 32432 also works)?  
The k3s is not even listening on port 1210, how can k3s achieve this?

**Comment by rolinux** [comment]
Are you testing from a node that is part of the cluster?
If yes, that is an expected Kubernetes behaviour as by default (without network policies) any node inside the cluster should be able to connect to services/pods ports.
