### ISSUE TITLE
How to use a private registry by local DNS name?

### ISSUE THREAD

**Issue by DuncanvR** [k3s-io/k3s#1581]
### Context
I'd like to run an image registry that is not exposed to the outside world, so that it can only be reached via a proxy or from within the cluster. I can get this to work quite easily with the IP address of the registry service hard coded, but am having difficulty using a DNS entry like `*.svc.cluster.local`. How can I achieve the latter?

I have a single node cluster running K3OS (v0.9.1) and K3S (v1.17.2+k3s1). Below is a description of what I've done so far.

### Private registry
I have deployed Docker registry (v2.7.1) without ingress, TLS or authentication.
```sh
> kubectl get svc --namespace containers
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
image-registry   ClusterIP   10.43.174.140   <none>        5000/TCP   30m
> kubectl get pod --namespace containers
NAME                             READY   STATUS    RESTARTS   AGE
image-registry-94946fd49-rlg6t   1/1     Running   0          30m
```

I can successfully connect to the registry and push images, e.g.:
```sh
> kubectl port-forward --namespace containers image-registry-94946fd49-rlg6t 5000
> docker pull nginx:alpine
> docker tag  nginx:alpine localhost:5000/test-image:latest
> docker push              localhost:5000/test-image:latest
```

I followed [the documentation](https://rancher.com/docs/k3s/latest/en/installation/private-registry) to make K3S use my private registry:
```sh
> cat /etc/rancher/k3s/registries.yaml
mirrors:
  "image-registry-1.duncanvr":
    endpoint:
      - "http://10.43.174.140:5000"
  "image-registry-2.duncanvr":
    endpoint:
      - "http://image-registry.containers.svc.cluster.local:5000"
```

### Pulling images
When I create a simple deployment with a container using `image-registry-1.duncanvr/test-image:latest`, the pod comes online and works as expected. However, I'm not too fond of hard coding IP addresses in configuration, as this makes things brittle. I'd prefer using an alias, like the endpoint of the second mirror.

But using `image-registry-2.duncanvr/test-image:latest` fails:
```sh
> kubectl describe pod
Name:         test-544d574bd9-plwpc
Namespace:    default
Status:       Pending
Containers:
  test:
    Container ID:   
    Image:          image-registry-2.duncanvr/test-image:latest
    Image ID:       
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Events:
  Type     Reason     Age        From               Message
  ----     ------     ----       ----               -------
  Normal   Scheduled  <unknown>  default-scheduler  Successfully assigned default/test-544d574bd9-plwpc to node
  Normal   Pulling    5s         kubelet, node      Pulling image "image-registry-2.duncanvr/test-image:latest"
  Warning  Failed     5s         kubelet, node      Failed to pull image "image-registry-2.duncanvr/test-image:latest": rpc error: code = Unknown desc = failed to pull and unpack image "image-registry-2.duncanvr/test-image:latest": failed to resolve reference "image-registry-2.duncanvr/test-image:latest": failed to do request: Head http://image-registry.containers.svc.cluster.local:5000/v2/test-image/manifests/latest: dial tcp: lookup image-registry.containers.svc.cluster.local: no such host
```
So while it is correctly looking for `http://image-registry.containers.svc.cluster.local:5000`, it cannot resolve the address. Here, *it* is K3S, I think, or whatever K3S is using to pull the image. It seems that *it* doesn't check the DNS resolver from the cluster when resolving hosts.

### DNS nameservers
I can ssh into the node and see that it indeed cannot resolve that address.
```sh
> nslookup image-registry.containers.svc.cluster.local
Server:		213.133.98.98
Address:	213.133.98.98:53

** server can't find image-registry.containers.svc.cluster.local: NXDOMAIN
```
It makes sense that K3OS isn't configured to use the cluster's DNS resolver as a nameserver, as it isn't even granted to be deployed or running. However, given what I'm trying to do, I figured I could try adding the IP address of kube-dns to the top of `/etc/resolve.conf`. Then the previous command succeeds:
```sh
> nslookup image-registry.containers.svc.cluster.local
Server:		10.43.0.10
Address:	10.43.0.10:53

Name:	image-registry.containers.svc.cluster.local
Address: 10.43.174.140
```
Unfortunately this isn't sufficient to allow the image to be pulled. Even after restarting the K3S service, I keep seeing the same error. Only after forcing the core-dns pod to restart (by scaling to 0 and back to 1), the image is found and the pod is running. Hurray!

### Permanent solution
The above isn't a permanent solution though, because under K3OS, `/etc/resolve.conf` gets overwritten at boot time. As I understand, the `k3os.dns_nameservers` option is only for setting fallback nameservers, so that won't help. I haven't looked into the configuration of connman yet, which might allow to set a default nameserver.

However, I'm not convinced that changing `/etc/resolve.conf` is the best way to go, as core-dns doesn't seem to be enjoying this configuration (it is now effectively querying itself when looking upstream):
```sh
> kubectl describe pod --namespace kube-system coredns-d798c9dd-k58w5
Name:         coredns-d798c9dd-k58w5
Namespace:    kube-system
Status:       Running
Containers:
  coredns:
    Image:         coredns/coredns:1.6.3
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Normal   Scheduled         <unknown>          default-scheduler  Successfully assigned kube-system/coredns-d798c9dd-k58w5 to node
  Normal   Pulled            30s                kubelet, node      Container image "coredns/coredns:1.6.3" already present on machine
  Normal   Created           30s                kubelet, node      Created container coredns
  Normal   Started           30s                kubelet, node      Started container coredns
  Warning  DNSConfigForming  29s (x4 over 30s)  kubelet, node      Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.43.0.10 213.133.98.98 213.133.99.99
```
That's how far I got. It kinda works, but I have a feeling this isn't the way it should be done.

**What would be the best way to make K3S resolve hostnames through the cluster's DNS nameserver when pulling images?**

**Comment by webees** [comment]
I seem to be having the same problem as you.

https://github.com/containerd/containerd/issues/4452

**Comment by n-guitar** [comment]
I seem to be having the same problem as you.

My Environment information

info | &nbsp;
-- | --
Architecture | amd64
Container Runtime Version | containerd://1.4.4-k3s1
Image | Ubuntu 20.04.2 LTS
Kernel Version | 5.8.0-53-generic
Kube Proxy Version | v1.20.7+k3s1
Kubelet Version | v1.20.7+k3s1
Operating System | linux

**Comment by brandond** [comment]
Containerd runs containers for Kubernetes, but runs on the host and is not itself part of the cluster nor aware of its existence. If the host you're running K3s on cannot resolve in-cluster DNS names, then neither can containerd.

**Comment by DuncanvR** [comment]
Thanks @brandond. I guess that makes the K3OS repo a better place for my issue.
