### ISSUE TITLE
k3s master deployment failed

### ISSUE THREAD

**Issue by fangfuhaomin** [k3s-io/k3s#1586]
Type     Reason             Age               From               Message
  ----     ------             ----              ----               -------
  Normal   Scheduled          <unknown>         default-scheduler  Successfully assigned default/nginx-deployment-7f997555d8-7k6kf to k3s-s-1
  Warning  Failed             8s (x5 over 44s)  kubelet, k3s-s-1   Error: ErrImageNeverPull
  Warning  ErrImageNeverPull  8s (x5 over 44s)  kubelet, k3s-s-1   Container image "nginx:latest" is not present with pull policy of Never

K3s is not deployable

The k8s is deployable

**Comment by fangfuhaomin** [comment]
master fail
node successful

**Comment by fangfuhaomin** [comment]
I want pod to be deployed on the master

**Comment by fangfuhaomin** [comment]
There is already a mirror locally

**Comment by fangfuhaomin** [comment]
[root@k3s-s-1 k3s]# docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
nginx                                               latest              6678c7c2e56c        3 weeks ago         127MB

**Comment by DuncanvR** [comment]
Here's what I think you're trying to say:
1. You have a deployment with a container using `nginx:latest` and a pull policy `Never`;
1. The pod is failing to come up, stating that it can't find the container image;
1. But you can see the image when running `docker images`.

Which version of K3S are you running?
How have you configured K3S to use docker?
