### ISSUE TITLE
TLS handshake error after k3s installation

### ISSUE THREAD

**Issue by panho66** [k3s-io/k3s#1603]
**Version:**

k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**

yum install -y container-selinux selinux-policy-base
rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm

curl -o /srv/rds-combined-ca-bundle.pem https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem

export INSTALL_K3S_VERSION='v1.17.3+k3s1'
export INSTALL_K3S_EXEC='--tls-san rancher.sysgreen.policy.cloud.net  --no-deploy traefik '
expirt K3S_CLUSTER_SECRET='G5Ks16JvrU0lhadG'
export K3S_STORAGE_CAFILE='/srv/rds-combined-ca-bundle.pem'
export K3S_STORAGE_ENDPOINT='postgres://ra:k3s@k3s-sys-green.cluster-ceqwulg2rd6c.ap-southeast-2.rds.amazonaws.com/k3s'

until (curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint=postgres://ra:k3s@k3s-sys-green.cluster-ceqwulg2rd6c.ap-southeast-2.rds.amazonaws.com/k3s); do
  echo 'k3s did not install correctly'
  sleep 2
done

**Describe the bug**

error message in /var/log/messages

Apr  1 06:48:07 ip-10-98-146-164 k3s: I0401 06:48:07.856926     543 log.go:172] http: TLS handshake error from 10.98.146.42:59034: EOF
Apr  1 06:48:07 ip-10-98-146-164 k3s: I0401 06:48:07.919186     543 log.go:172] http: TLS handshake error from 10.98.146.42:40918: EOF
Apr  1 06:48:08 ip-10-98-146-164 k3s: I0401 06:48:08.083893     543 log.go:172] http: TLS handshake error from 10.98.146.42:63911: EOF
Apr  1 06:48:08 ip-10-98-146-164 k3s: I0401 06:48:08.695750     543 log.go:172] http: TLS handshake error from 10.98.146.42:59371: EOF
Apr  1 06:48:09 ip-10-98-146-164 k3s: I0401 06:48:09.043574     543 log.go:172] http: TLS handshake error from 10.98.146.42:61399: EOF
Apr  1 06:48:09 ip-10-98-146-164 k3s: I0401 06:48:09.623273     543 log.go:172] http: TLS handshake error from 10.98.146.42:12471: EOF
Apr  1 06:48:09 ip-10-98-146-164 k3s: I0401 06:48:09.907325     543 log.go:172] http: TLS handshake error from 10.98.146.42:22455: EOF
Apr  1 06:48:10 ip-10-98-146-164 k3s: I0401 06:48:10.305752     543 log.go:172] http: TLS handshake error from 10.98.146.42:48028: EOF
Apr  1 06:48:11 ip-10-98-146-164 k3s: I0401 06:48:11.441058     543 log.go:172] http: TLS handshake error from 10.98.146.42:10644: EOF
Apr  1 06:48:13 ip-10-98-146-164 k3s: I0401 06:48:13.150093     543 log.go:172] http: TLS handshake error from 10.98.146.42:56273: EOF
Apr  1 06:48:13 ip-10-98-146-164 k3s: I0401 06:48:13.500232     543 log.go:172] http: TLS handshake error from 10.98.146.42:22758: EOF
Apr  1 06:48:13 ip-10-98-146-164 k3s: I0401 06:48:13.692449     543 log.go:172] http: TLS handshake error from 10.98.146.42:5797: EOF
Apr  1 06:48:13 ip-10-98-146-164 k3s: I0401 06:48:13.822993     543 log.go:172] http: TLS handshake error from 10.98.146.42:59511: EOF
Apr  1 06:48:14 ip-10-98-146-164 k3s: I0401 06:48:14.374536     543 log.go:172] http: TLS handshake error from 10.98.146.42:31787: EOF
Apr  1 06:48:14 ip-10-98-146-164 k3s: I0401 06:48:14.799729     543 log.go:172] http: TLS handshake error from 10.98.146.42:40425: EOF
Apr  1 06:48:14 ip-10-98-146-164 k3s: I0401 06:48:14.932599     543 log.go:172] http: TLS handshake error from 10.98.146.42:40439: EOF
Apr  1 06:48:15 ip-10-98-146-164 k3s: I0401 06:48:15.479555     543 log.go:172] http: TLS handshake error from 10.98.146.42:64169: EOF
Apr  1 06:48:15 ip-10-98-146-164 k3s: I0401 06:48:15.795957     543 log.go:172] http: TLS handshake error from 10.98.146.42:57562: EOF
Apr  1 06:48:16 ip-10-98-146-164 k3s: I0401 06:48:16.222399     543 log.go:172] http: TLS handshake error from 10.98.146.42:50970: EOF
Apr  1 06:48:16 ip-10-98-146-164 k3s: I0401 06:48:16.873020     543 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Apr  1 06:48:17 ip-10-98-146-164 k3s: I0401 06:48:17.357339     543 log.go:172] http: TLS handshake error from 10.98.146.42:46312: EOF
Apr  1 06:48:17 ip-10-98-146-164 k3s: I0401 06:48:17.534825     543 log.go:172] http: TLS handshake error from 10.98.146.42:48662: EOF
Apr  1 06:48:17 ip-10-98-146-164 k3s: I0401 06:48:17.863891     543 log.go:172] http: TLS handshake error from 10.98.146.42:62527: EOF
Apr  1 06:48:18 ip-10-98-146-164 k3s: I0401 06:48:18.135783     543 log.go:172] http: TLS handshake error from 10.98.146.42:62264: EOF
Apr  1 06:48:18 ip-10-98-146-164 k3s: I0401 06:48:18.214426     543 log.go:172] http: TLS handshake error from 10.98.146.42:48245: EOF
Apr  1 06:48:18 ip-10-98-146-164 k3s: I0401 06:48:18.322681     543 log.go:172] http: TLS handshake error from 10.98.146.42:5447: EOF
Apr  1 06:48:18 ip-10-98-146-164 k3s: I0401 06:48:18.794346     543 log.go:172] http: TLS handshake error from 10.98.146.42:35019: EOF

**I have 2 nodes and NLB in front of 2 nodes running k3s**
[root@ip-10-98-146-164 scripts]# getent hosts rancher.sysgreen.policy.cloud.net
10.98.146.90    rancher.sysgreen.policy.cloud.net
10.98.146.42    rancher.sysgreen.policy.cloud.net

**problem 1**
a lot error message in /var/log/message
**problem 2**
on node 1 
     kubectl get nodes
     return quick with node information
on node 2
    kubectl get nodes
    waits for about 14 seconds and return node information

Any idea what causes it ?

**To Reproduce**

install k3s and run kubectl command

**Expected behavior**

no TLS error message in /var/log/message
second node kubectl command without delay

**Actual behavior**

**Additional context / logs**

Red Hat Enterprise Linux Server release 7.6 (Maipo)
run containerd rather than Docker

● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-04-01 06:31:16 UTC; 15min ago
     Docs: https://k3s.io
  Process: 541 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 539 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 543 (k3s-server)
    Tasks: 69
   Memory: 1.4G
   CGroup: /system.slice/k3s.service
           ├─  555 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
           ├─11632 /var/lib/rancher/k3s/data/ca752b211ccbacb1b66df2ec0bc203a9511c0ec045ef5566b31c297958d46a3a/bin/containerd-shim-runc-v2 -namespace k8s.io -id af43f155dcc6d6e67855618f9bec80c1ca37a1cc7b1b12ab6efa38ecf0f2b4fe -address /run/k3s/containerd/containerd.sock
           ├─11647 /var/lib/rancher/k3s/data/ca752b211ccbacb1b66df2ec0bc203a9511c0ec045ef5566b31c297958d46a3a/bin/containerd-shim-runc-v2 -namespace k8s.io -id 66208f8d3458c23d698da134db8a77709483a324d9ce949bfedc3bd1b223faaa -address /run/k3s/containerd/containerd.sock
           ├─11681 /var/lib/rancher/k3s/data/ca752b211ccbacb1b66df2ec0bc203a9511c0ec045ef5566b31c297958d46a3a/bin/containerd-shim-runc-v2 -namespace k8s.io -id 3520bc971c2d29874e12024dbd3ad16a766f079c18b0027142b9631499b3eaab -address /run/k3s/containerd/containerd.sock
           └─12075 /var/lib/rancher/k3s/data/ca752b211ccbacb1b66df2ec0bc203a9511c0ec045ef5566b31c297958d46a3a/bin/containerd-shim-runc-v2 -namespace k8s.io -id 4cdc90e0f26998871417c19ffd6cb30b9b7e58308da3cbe72dabcf6c7b361368 -address /run/k3s/containerd/containerd.sock
           ‣ 543 /usr/local/bin/k3s server --tls-san rancher.sysgreen.policy.iagcloud.net --no-deploy traefik server --datastore-endpoint=postgres://rancher:k3s@k3s-sys-green.cluster-ceqwulg2rd6c.ap-southeast-2.rds.amazonaws.com/k3s

Apr 01 06:46:43 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:43.757683     543 log.go:172] http: TLS handshake error from 10.98.146.42:31541: EOF
Apr 01 06:46:43 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:43.849848     543 log.go:172] http: TLS handshake error from 10.98.146.42:4560: EOF
Apr 01 06:46:43 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:43.907535     543 log.go:172] http: TLS handshake error from 10.98.146.42:28583: EOF
Apr 01 06:46:44 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:44.807056     543 log.go:172] http: TLS handshake error from 10.98.146.42:17864: EOF
Apr 01 06:46:44 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:44.941987     543 log.go:172] http: TLS handshake error from 10.98.146.42:16786: EOF
Apr 01 06:46:45 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:45.445551     543 log.go:172] http: TLS handshake error from 10.98.146.42:16001: EOF
Apr 01 06:46:46 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:46.115452     543 log.go:172] http: TLS handshake error from 10.98.146.42:59652: EOF
Apr 01 06:46:47 ip-10-98-146-164.ap-southeast-2.compute.internal k3s[543]: I0401 06:46:47.164312     543 log.go:172] http: TLS handshake error from 10.98.146.42:63591: EOF

**Comment by marcstreeter** [comment]
any information on why this was closed?  I also see this issue.

**Comment by davidnuzik** [comment]
Reopening as we have a couple of reports of others seeing the issue.

**Comment by FrankieSanzica** [comment]
Hello,

It appears I may have run into this same issue:

**Version:**
k3s version v1.18.3+k3s1 (96653e8d)

**K3s arguments:**
/usr/local/bin/k3s server --tls-san $AWS_NLB --disable-agent --disable metrics-server

**Describe the bug**
'k3s[]: http: TLS handshake error from $IP:$PORT: EOF' error on server nodes

**To Reproduce**
‘journalctl -u k3s -f’ or ‘systemctl status k3s.service’ on any server node

**Expected behavior**
No TLS handshake errors

**Actual behavior**
TLS errors

**Additional context / logs**
Currently running this in AWS on Amazon Linux EC2s (amzn2-ami-hvm-2.0.20200520.1-x86_64-gp2 (ami-026dea5602e368e96)) all deployed with Terraform 0.12.

The setup is similar to: https://github.com/rancher/terraform-k3s-aws-cluster

'k3s check-config' passes on all server/agent nodes.

**Comment by brandond** [comment]
@FrankieSanzica did you by any chance deploy it behind an elb/alb?

**Comment by FrankieSanzica** [comment]
@brandond I did.  Two NLBs.  A private one for the server nodes, a public one for the agent nodes.

Pretty identical to: https://github.com/rancher/terraform-k3s-aws-cluster/blob/master/loadbalancer.tf

**Comment by brandond** [comment]
The messages are probably from ELB health checks then. The health check just connects and disconnects without doing a full SSL handshake, so you get errors complaining about the unexpected EOF.

You might try changing it to a https health check that hits https://<address>:6443/ping

**Comment by FrankieSanzica** [comment]
@brandond you led me in the right direction!  It does appear the issue was due to NLB health checks on my end.  

You can see in the Rancher Terraform, there is no health check for the 6443 target group: https://github.com/rancher/terraform-k3s-aws-cluster/blob/master/loadbalancer.tf#L21-L26

However, I was able to get these CA errors to stop by adding the following:

resource "aws_lb_target_group" "server-6443" {
  name     = K3S-6443"
  port     = 6443
  protocol = "TCP"
  vpc_id   = $VPC

  health_check {
    path                = "/ping"
    port                = 6443
    protocol            = "HTTP"
  }
}

Thanks for the help and hope this helps anyone else with this issue!

**Comment by brandond** [comment]
You might open an issue or PR against the terraform-k3s-aws-cluster project as well.
