### ISSUE TITLE
What is the easiest way to enable PodPreset admission plugin in an existing k3s cluster ?  

### ISSUE THREAD

**Issue by marouanabbessi** [k3s-io/k3s#1604]
What is the easiest way to enable PodPreset admission plugin in an existing k3s cluster ?

**Comment by rolfberkenbosch** [comment]
Is this implemented ?

**Comment by brandond** [comment]
Have you tried enabling it as per [the documentation](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#enable-pod-preset)?

For k3s you can pass API server arguments via `--kube-apiserver-arg` so for admission plugins it would look like `--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodPreset`

**Comment by swiftugandan** [comment]
> Have you tried enabling it as per [the documentation](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#enable-pod-preset)?
> 
> For k3s you can pass API server arguments via `--kube-apiserver-arg` so for admission plugins it would look like `--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodPreset`

Not working for me. 

`I0716 15:32:42.336401    5967 trace.go:116] Trace[154550481]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-16 15:32:32.320906805 +0000 UTC m=+2.042222994) (total time: 10.015472408s):
Trace[154550481]: [10.015472408s] [10.015472408s] END
E0716 15:32:42.336475    5967 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1alpha1.PodPreset: the server could not find the requested resource (get podpresets.settings.k8s.io)
E0716 15:32:43.646154    5967 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1alpha1.PodPreset: the server could not find the requested resource (get podpresets.settings.k8s.io)
E0716 15:32:45.662613    5967 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1alpha1.PodPreset: the server could not find the requested resource (get podpresets.settings.k8s.io)`

**Comment by brandond** [comment]
@swiftugandan did you create any PodPreset resources?

**Comment by swiftugandan** [comment]
> @swiftugandan did you create any PodPreset resources?
> 
> https://kubernetes.io/docs/tasks/inject-data-application/podpreset/

`--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodPreset --kube-apiserver-arg=runtime-config=settings.k8s.io/v1alpha1=true` got it working, thanx

**Comment by FLM210** [comment]
I added two startup parameters to the K3s service configuration file  '--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodPreset' 
        '--kube-apiserver-arg=runtime-config=settings.k8s.io/v1alpha1=true'
