### ISSUE TITLE
cluster-init flag is not documented correctly

### ISSUE THREAD

**Issue by couillonnade** [k3s-io/k3s#1617]
Hello, 

I found an mistake in the documentation (or maybe I don't understand it correctly?). To create a cluster, you suggest the following command: `K3S_TOKEN=SECRET k3s server --cluster-init`

After reviewing the [how-to-flags page](https://rancher.com/docs/k3s/latest/en/installation/install-options/how-to-flags/), I installed the server with the following command:

`curl -fL https://get.k3s.io | K3S_TOKEN='mysecrettoken' sh -s - k3s server --cluster-init` 

but this is not working since **k3s** should not be here and one should read: 

`curl -fL https://get.k3s.io | K3S_TOKEN='mysecrettoken' sh -s - server --cluster-init`

I am referring to the [ha embedded page](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/) 

In case someone tried with k3s, you can uninstall the not working k3s server with: `/usr/local/bin/k3s-k3s-uninstall.sh` instead of `/usr/local/bin/k3s-uninstall.sh`

There is also the same typo in [ha with external db page](https://rancher.com/docs/k3s/latest/en/installation/ha/): 

K3S_TOKEN=SECRET **k3s** agent --server https://fixed-registration-address:6443

Hope this will help someone in the same situation
Torpi

**Comment by brandond** [comment]
Seems to be some user confusion between passing environment variables and arguments to the install script, vs the k3s binary post-install. I don't see any errors in the docs, but then I am pretty handy with a shell so I may understand the intent better than some folks just getting started.

**Comment by torpinouche** [comment]
You are absolutely right, the confusion comes from passing vars and args to the install script vs lauching k3s with args and variables (post-install). 

What's confusing is that the sample to launch the cluster (post-install) is in the installation chapter of the documentation.

**Comment by aboyum** [comment]
Thanks. This helped a lot. The documentation is still wrong and hence it's very difficult to install.

**Comment by brandond** [comment]
@aboyum can you point to which specific portion of the documentation is wrong?

**Comment by aboyum** [comment]
As torpinouche mentioned in 2020. From the installation options (https://rancher.com/docs/k3s/latest/en/installation/install-options/) it looks like you are supposed to write the installation like this (at least from my notes trying to install it):
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET k3s server --cluster-init sh -
However, the secret should be written with single quotes, and you should not write "k3s", but rather:
curl -fL https://get.k3s.io | K3S_TOKEN='my-secret' sh -s - server --cluster-init

It's was quite confusing for me to try to install a HA-K3S cluster. 
Take a look at this page: https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/
It doesn't give any help, but I rather got confused even more.
Like this part:
_To get started, first launch a server node with the cluster-init flag to enable clustering and a token that will be used as a shared secret to join additional servers to the cluster.

K3S_TOKEN=SECRET k3s server --cluster-init_

But what you really should write is something like this:
curl -fL https://get.k3s.io | K3S_TOKEN='SECRET' sh -s - server --cluster-init
Would have been nice if the documentation was easier to understand. Thanks.

**Comment by brandond** [comment]
As I said above, you're conflating different instructions:

> Seems to be some user confusion between passing environment variables and arguments to the install script, vs the k3s binary post-install.

The install options page shows you how to provide flags when installing K3s:
> curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_EXEC="server --cluster-init" sh -

The ha-embedded page shows you how to provide flags when starting K3s from the command line:
> K3S_TOKEN=SECRET k3s server --cluster-init

Neither of them is wrong, they are just different scenarios.

**Comment by gpow81** [comment]
I do understand that these are two different options. The problem  (at least for me) is that the other option with a binary seems to be the one suggested for an HA with Embedded DB but the documentation didn't tell much and left me in the middle of woods
"to get started, first launch a server node with the cluster-init". Ok, I run this and after seeing a bunch of messages it just stays on the screen. Do I ctrl+c it? ctrl+z?  Without killing it I started the the binary on two other nodes. It seemed like they started chatting. But again, do I ctrl+z it now? Should I kill it and start it again in background, with no "cluster-init" this time?  
How should I start them after reboot. No systemd, no nothing in documentation about it (perhaps I am not looking right then I apologize)
Where can I find next steps on how to finish install of the ha cluster and make it prod ready? I think I understand that this is all wrapped in one k3 binary and it needs to stay running so I guess I could poke around and make my my own service file but it would be nice to have some guidance in the documentation. 

thanks!

**Comment by brandond** [comment]
Putting it all together:
```bash
# run this on the first server
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_EXEC="server --cluster-init" sh -

# run this on the other two servers, one at a time
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET K3S_URL=https://server1:6443 INSTALL_K3S_EXEC="server" sh -
```

That's it.

**Comment by gpow81** [comment]
Thank you! These two lines (with a short information explaining that it will not only initialize the cluster but also will take care of systemd, provide some uninstall scripts etc)  was probably something that beginners like I could really use in "High Availability with Embedded DB" section. Now I am putting all the blocks together and I see that information is there in fact but there was no way I would connect on my own the INSTALL_K3S_EXEC (1 out of 15 listed variables) which was mentioned in Example B: INSTALL_K3S_EXEC  (which didn't have anything to do with initialization) with information provided in the "Availability with Embedded DB". So thanks again, helped a lot. If anyone responsible for documentation is reading this, please consider adding a small note in the HA section.

**Comment by andreasdotorg** [comment]
> Putting it all together:
> 
> ```shell
> # run this on the first server
> curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET INSTALL_K3S_EXEC="server --cluster-init" sh -
> 
> # run this on the other two servers, one at a time
> curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET K3S_URL=https://server1:6443 INSTALL_K3S_EXEC="server" sh -
> ```
> 
> That's it.

This, right there, saved me a couple of hours of head scratching. Thanks! It should live in some HA quickstart guide.

**Comment by ZouhairCharef** [comment]
> K3S_TOKEN=SECRET **k3s** agent --server https://fixed-registration-address:6443
For this one you can export K3s_TOKEN and K3S_URL and run the installation command and it adds the agent to your cluster
