### ISSUE TITLE
Windows flannel host-gw support

### ISSUE THREAD

**Issue by KnicKnic** [k3s-io/k3s#1618]
**Is your feature request related to a problem? Please describe.**
Add code to ensure that a windows node can setup flannel in host-gw mode.
related to issues https://github.com/rancher/k3s/issues/1486 & https://github.com/rancher/k3s/issues/114

**Describe the solution you'd like**
User specifies starting up k3s with host-gw and windows node comes up with kube-proxy & flannel configured correctly.

**Additional context**
Below is a bunch of notes on what needs to be done, as well as a working example (where it was manually configured and not automatically configured).

# setting up flannel
Information on how to setup host-gw mode in windows is available in  https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/flannel/flannel-host-gw.yml and https://github.com/kubernetes-sigs/sig-windows-tools/blob/a4311b743b4caf656f94c8cff442be09f91c5a2b/kubeadm/flannel/setup.go#L19-L21 It should be noted that hns.ps1 being reffered here is available at https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/flannel/hns.psm1

## extra binaries and more sample configs
https://github.com/microsoft/SDN/tree/master/Kubernetes/flannel/l2bridge which also contains host-local.exe and win-bridge.exe These binaries will need to be on the path so that flannel can find them.

## Flannel creating the network
Here is a related bug about overlay windows configuring itself.  https://github.com/coreos/flannel/issues/1128

## kube-proxy config
Need to set the name of the environment variable KUBE_NETWORK to the appropriate network and you need to set `cluster-cidr=10.42.0.0/16` or whatever your pod namespace is

### other kube-proxy args
`--kube-proxy-arg "proxy-mode=kernelspace" --kube-proxy-arg "hostname-override=$($env:COMPUTERNAME)" `
Need to figure out if hostname-override needs to be set. These params were obtained from https://github.com/microsoft/SDN/blob/6022aee9e747b3263dc2db564936bb55d791b14a/Kubernetes/flannel/start-kubeproxy.ps1#L16-L17

# Put together example
reference variables
```
service subnet "10.43.0.0/16"
clustercidr / pod subnet "10.42.0.0/16"
machine subnet  "192.168.11.108/24"
machine ip "192.168.11.108/32"
Ethernet - the name of the physical adapter I used for this example
```

create network
```
ipmo .\hns.psm1; 
New-HNSNetwork -Type l2bridge -AddressPrefix "192.168.255.0/30" -Gateway "192.168.255.1" -Name "External" -AdapterName "Ethernet"
```

add path containing host-local.exe and win-bridge.exe
```
$env:Path +=";C:\Users\Administrator\go\src\github.com\rancher\k3s"
```

setup KUBE_NETWORK & launch
```
$env:KUBE_NETWORK="cbr0"
.\k3s.exe server -d c:\tmp\k3s --flannel-backend host-gw --docker  --kube-proxy-arg "proxy-mode=kernelspace" --kube-proxy-arg "cluster-cidr=10.42.0.0/16" --kube-proxy-arg "hostname-override=$($env:COMPUTERNAME)" --disable-network-policy  --flannel-conf C:\tmp\k3s\agent\etc\flannel\net-conf.json --resolv-conf C:\Users\Administrator\go\src\github.com\rancher\k3s\k3s-resolv.conf --pause-image mcr.microsoft.com/k8s/core/pause:1.0.0
```

Various files referenced below

C:\Users\Administrator\go\src\github.com\rancher\k3s\k3s-resolv.conf workaround for resolv.conf issue
```
nameserver 8.8.8.8
```

C:\tmp\k3s\agent\etc\flannel\net-conf.json
```
{
	"Network": "10.42.0.0/16",
	"Backend": {
        "Name": "cbr0",
	"Type": "host-gw"
}
}
```

C:\tmp\k3s\agent\etc\cni\net.d\10-flannel.conf
```
{
    "name": "cbr0",
    "cniVersion": "0.3.0",
    "type": "flannel",
    "capabilities": {
      "dns": true
    },
    "delegate": {
      "type": "win-bridge",
      "hairpinMode": true,
      "isDefaultGateway": true,
      "policies": [
        {
          "Name": "EndpointPolicy",
          "Value": {
            "Type": "OutBoundNAT",
            "ExceptionList": [
                "10.43.0.0/16",
                "10.42.0.0/16",
                "192.168.11.108/24"]
          }
        },
        {
          "Name": "EndpointPolicy",
          "Value": {
            "Type": "ROUTE",
            "DestinationPrefix": "10.43.0.0/16",
            "NeedEncap": true
          }
        },
        {
          "Name": "EndpointPolicy",
          "Value": {
            "Type": "ROUTE",
            "DestinationPrefix": "192.168.11.108/32",
            "NeedEncap": true
          }
        }
      ]
    }
  }
```

**Comment by heroku-miraheze** [comment]
In the next release of k3s we will add Windows containers to work in it.

**Comment by KnicKnic** [comment]
> In the next release of k3s we will add Windows containers to work in it.

Can you ping me on k3s slack, thanks!

**Comment by KnicKnic** [comment]
@teyc @luthermonson @heroku-miraheze 

I **hacked** up some code to do this on my own branch  https://github.com/KnicKnic/k3s/tree/k3s_run_windows_node_7 you are welcome to clean it up and check it in

**Comment by KnicKnic** [comment]
@phillipsj is this now working? I ask because I saw that recently you have been addressing windows issues.

**Comment by brandond** [comment]
We're only working on windows agent support for RKE2. There have been some changes for k3s to support this, but we're not planning on supporting k3s on windows at this time.

**Comment by KnicKnic** [comment]
> We're only working on windows agent support for RKE2. There have been some changes for k3s to support this, but we're not planning on supporting k3s on windows at this time.

I do not know how to parse your statement to understand what (if any) sections of CNI configuration would fall into shared section.
