### ISSUE TITLE
Can't get k3s to work out of the box on raspberry pi cluster

### ISSUE THREAD

**Issue by g4njawizard** [k3s-io/k3s#1633]
I've made almost identical steps like in this guide: https://kauri.io/install-and-configure-a-kubernetes-cluster-with-k3s-to-self-host-applications/418b3bc1e0544fbc955a4bbba6fff8a9/a

**Setup:** 
Rasbian lite latest

- 1x rpi 4 b 4GB (Master) 64GB SD
- 2x rpi 3b+ (Nodes) 16GB SD

I didn't configure my pi's in any special way. Just Updates, raspi-config, ssh adjustments and non root-user. The guide uses dhcpcd and iptables legacy changes. I tried it with and without these settings, but I always end up with the same issue.

My k3s-master Node is up and running. I have some syslog errors, but that seem due to missing kernel driver:
```
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_RT_GROUP_SCHED: missing
```
k3s-master:
```
sudo kubectl get node -o wide
NAME         STATUS   ROLES    AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
k3s-master   Ready    master   19s   v1.17.4+k3s1   192.168.2.27   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s2
helios@k3s-master:~$ sudo cat /var/lib/rancher/k3s/server/node-token
K101656ce6e12309448aa9ca40507011d7353f1a3904ad71a11946e8e83907bd310::server:8cceceb0d22755505b3750e0b0434936
```

Node1 Output:
```
helios@k3s-node1:~$ sudo systemctl start k3s-agent.service 
helios@k3s-node1:~$ sudo kubectl get node -o wide
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04 
INFO[0007] error changing modtime: chtimes /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04-tmp/bin/containerd: no such file or directory (further Chtimes errors suppressed) 
INFO[0007] error extracting tarball into /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04-tmp after 4 files, 1 dirs, 5.908381796s: symlink busybox /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04-tmp/bin/runlevel: no such file or directory 
FATA[0007] extracting data: symlink busybox /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04-tmp/bin/runlevel: no such file or directory 
helios@k3s-node1:~$ k3s check-config
Verifying binaries in /var/lib/rancher/k3s/data/0d6b3c3bdce515346f525129585a7d743d4b317feac3b9c71df2fbffbb009b04/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.2 (legacy): ok
- swap: should be disabled
- routes: default CIDRs 10.42.0.0/16 or 10.43.0.0/16 already routed

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

info: reading kernel config from /proc/config.gz ...

- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_RT_GROUP_SCHED: missing
`
```

Node2 Output:
```
helios@k3s-node2:~$ export K3S_KUBECONFIG_MODE="644"
helios@k3s-node2:~$ export K3S_URL="https://192.168.2.27:6443"
helios@k3s-node2:~$ export K3S_TOKEN="K101656ce6e12309448aa9ca40507011d7353f1a3904ad71a11946e8e83907bd310::server:8cceceb0d22755505b3750e0b0434936"
helios@k3s-node2:~$ sudo curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v1.17.4+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s-agent.service → /etc/systemd/system/k3s-agent.service.
[INFO]  systemd: Starting k3s-agent
helios@k3s-node2:~$ sudo kubectl get nodes -o wide
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Seems like the Master cant offer needed files in time? Could this be a network related problem?
Nodes are getting registered as expected on the master. Status "Ready" But they are unable to find a config. If I run 
```
helios@k3s-node2:~$ kubectl config view
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```

**Comment by brandond** [comment]
What is going on with your node1 output? I don't see where you're installing it, just running kubectl. Where is kubectl coming from on node1 and node2? k3s only makes kubectl available on server nodes, not on agents.

**Comment by g4njawizard** [comment]
I installed node1 the same way as I did with node 2.
Just stopped the service, deleted the content of rancher/k3s/data/* and started the service to reproduce this error.

**Comment by g4njawizard** [comment]
I've added the missing driver to the kernel on all pi's. Installed k3s again and I still experience the same issue.
Here's the syslog from master:
[syslog.txt](https://github.com/rancher/k3s/files/4464705/syslog.txt)
From the node:
[syslognode.txt](https://github.com/rancher/k3s/files/4464709/syslognode.txt)

**Comment by SteelCrow** [comment]
Do you booting from SD card with RaspbianOS?  Check if file `cmdline.txt` in boot partition have this lines `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1` 

This link may help this nessesary configuration of rasp hw.
 
https://kauri.io/build-your-very-own-self-hosting-platform-with-raspberry-pi-and-kubernetes-introduction/1229f21044ef4bff8df35875d6803776/a

**Comment by brandond** [comment]
You can only use kubectl on the master, NOT the agents.

**Comment by g4njawizard** [comment]
Yes, i checked that before installing.

**Comment by g4njawizard** [comment]
> What is going on with your node1 output? I don't see where you're installing it, just running kubectl. Where is kubectl coming from on node1 and node2? k3s only makes kubectl available on server nodes, not on agents.

But inside that guide on step 3/8 it's possible. You even can download it on your notebook for remote administration. You can of course use kubectl on agents. You are only limited to lower privileged commands for the current node you are logged in. For example, you cant do "kubectl delete node x" from there.

**Comment by SteelCrow** [comment]
May you describe your network topology with ip addresses? It seems that you have connectivity errors.
Your master and nodes on the same network?

**Comment by g4njawizard** [comment]
There is no big network cluster behind it. Its simply plugged to an unmanaged switch ans dhcp is coming from my router. I am awaiting a firewall, nas and managed switch assets. But now they currently run with pretty home network default setup.
Router: 192.168.2.1
Master: ... 2.27
Node: ... 2.66

No VLANs, no dmz nor firewall...

**Comment by SteelCrow** [comment]
> There is no big network cluster behind it. Its simply plugged to an unmanaged switch and dhcp is managed by my router. I am awaiting a firewall, nas and managed switch assets. But now they currently run with pretty home network default setup.
> Router: 192.168.2.1
> Master: ... 2.27
> Node: ... 2.66
> 
> No VLANs, no dmz nor firewall...

Ok, please show `journalctl -u k3s` for all three nodes.

**Comment by aleonnet** [comment]
Hi guys,
K3s isn't just working... the google is full of this such failured. I've tried many things to get it running.


pi@kube-master:~ $ sudo systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-02 03:05:06 BST; 
     Docs: https://k3s.io
  Process: 7644 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 7645 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 7646 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
 Main PID: 7646 (code=exited, status=1/FAILURE)

**Comment by dweomer** [comment]
@aleonnet lacking any obvious relationship to this issue thread it is not really appropriate or at all helpful to tack on your `systemctl status` output. Please open a new issue telling us how you've installed and configured k3s and on what operating system and hardware you are using.
