### ISSUE TITLE
kube-proxy problem on v1.17.2-k3s1

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#1638]
**Version:**
k3s: v1.17.2-k3s-1
OS: CentOS 7.6  with kernel:3.10.0-957.el7.x86_64
CentOS 7.7 with kernel   3.10.0-1062.18.1.el7.x86_64

**Describe the bug**
I have two node, nodeA is the k3s-server ,also as a worker, node B is a worker.

If one workload has one pod is scheduled to node B,   and it has a kubernetes service releated to it with nodeport.

on node A: 
I cannot access the service with cluster IP and its service port.
I cannot access with node A's node IP:nodeport to access the service

if a workload with one pod is scheduled to node A
on node B: 
I cannot access the service with cluster IP and its service port.
I cannot access with node B's node IP:nodeport to access the service

on node A, I can ping success the pod IP who is scheduled to node B,
on node B, I can ping success the pod IP who is scheduled to node A,

on node A, I can access the service with nodeip:nodeport or clusterip:service-port to access the workload who's pod is scheduled to node A.
on node B, I can access the service with nodeip:nodeport or clusterip:service-port to access the workload who's pod is scheduled to node B.

 I'm so confused. I need your help, thanks

**To Reproduce**
just install a two node k3s cluster , both of them as worker while one of them also as k3s server.

**Comment by loganhz** [comment]
as you cannot access pods of node B via `node-b-ip:nodeport` on node B, I think it should be kubeproxy related issue. Maybe you can check related logs and iptable rules

**Comment by zengyongjie** [comment]
> as you cannot access pods of node B via `node-b-ip:nodeport` on node B, I think it should be kubeproxy related issue. Maybe you can check related logs and iptable rules

no, I can access the pod by node-b-ip:nodeport or clusterip:service-port on node b, while the pod is running on node b.

**Comment by zengyongjie** [comment]
> as you cannot access pods of node B via `node-b-ip:nodeport` on node B, I think it should be kubeproxy related issue. Maybe you can check related logs and iptable rules

I can not access the pod by clusterip:service-port or node-ip:node-port   on the node except the node which the pod is running .   But in containers, all the network communication is normal( include communication between pod,   between cluster ip, between node) .

**Comment by loganhz** [comment]
kubeproxy/iptable\ipvs is responsible for svc. Maybe you can try to debug them?

**Comment by zengyongjie** [comment]
> as you cannot access pods of node B via `node-b-ip:nodeport` on node B, I think it should be kubeproxy related issue. Maybe you can check related logs and iptable rules


I captured some packet on the normal cluster and the bad cluster and checked the difference between them, I got the following result:

![Uploading image.png…]()

**Comment by zengyongjie** [comment]
a more detailed picture to show :
![image](https://user-images.githubusercontent.com/62204644/79543154-83689700-80bf-11ea-9a20-2e738e99d6d3.png)

**Comment by niusmallnan** [comment]
@zengyongjie It looks like this is caused by a kernel problem. It cannot be reproduced on Ubuntu 18.04.
I found a similar issue in the community, maybe it is useful for you. https://github.com/coreos/flannel/issues/1243

You can try this `ethtool -K flannel.1 tx-checksum-ip-generic off` on your OS.

**Comment by nemonik** [comment]
I think i'm seeing similar problems with 1 master and 1 worker node both hosted CentOS 7 on VirtualBox.  If I deploy the docker registry container on master via k3s exposed on loadBalancerIP via MetalLB... I can easily curl the registry on the loadBalancerIP from the computer's host operating system and from master, but if I try to do the same on the worker node the curl pauses for a long bit and then finally registry's JSON is returned.  This is after disabling firewalld and enabling iptables, clearing the ip tables rules on both the master and worker node.  I have Ansible code I can share.   If deploy to Ubuntu Bionic 64 or Alpine 3.10 this all works like butter...

**Comment by nemonik** [comment]
Hot darn.  

```
sudo ethtool -K flannel.1 tx-checksum-ip-generic off
```

run on worker node fixed it !!!!

```
[vagrant@node1 ~]$ time curl http://192.168.0.201:5000/v2/_catalog
{"repositories":[]}

real	0m0.012s
user	0m0.000s
sys	0m0.008s
```

Thank you @niusmallnan!

**Comment by zengyongjie** [comment]
> @zengyongjie It looks like this is caused by a kernel problem. It cannot be reproduced on Ubuntu 18.04.
> I found a similar issue in the community, maybe it is useful for you. [coreos/flannel#1243](https://github.com/coreos/flannel/issues/1243)
> 
> You can try this `ethtool -K flannel.1 tx-checksum-ip-generic off` on your OS.
> 
> Also, you can try `host-gw` mode if these nodes are in the same subnet.

Thanks , It works.

**Comment by zengyongjie** [comment]
> Hot darn.
> 
> ```
> sudo ethtool -K flannel.1 tx-checksum-ip-generic off
> ```
> 
> run on the worker node fixed it !!!!
> 
> ```
> [vagrant@node1 ~]$ time curl http://192.168.0.201:5000/v2/_catalog
> {"repositories":[]}
> 
> real	0m0.012s
> user	0m0.000s
> sys	0m0.008s
> ```
> 
> Thank you @niusmallnan!

Thanks , It works for me.

**Comment by pwais** [comment]
lazyweb:  I had the exact same problem as described in https://github.com/k3s-io/k3s/issues/1638#issuecomment-615088410

I was using k3s version 1.25.x .  Upon upgrading to k8s version 1.28.x the issue went away entirely, without having to use the mentioned `ethtool` stuff.  Hope this helps searchers out there!
