### ISSUE TITLE
Host DNS not working after deploying a (non-recursive) DNS

### ISSUE THREAD

**Issue by lucaelin** [k3s-io/k3s#1640]
**Version:**
`k3s version v1.17.4+k3s1 (3eee8ac3)`

**K3s arguments:**
`curl -sfL https://get.k3s.io | sh -`

**Describe the bug**
`systemd-resolved` fails to provide dns lookups on the host after deploying a (non-recursive) DNS service in the cluster.
To my understanding, `systemd-resolved` binds itself on `127.0.0.53:53` in order to reply to local dns lookups. When deploying a loadbalancer on that port, those requests get intercepted by iptables and forwarded into the cluster. Since the in-cluster DNS does not resolve requests for domains other than the one it was setup to handle, those intercepted requests fail in most cases.

**To Reproduce**
1. Install k3s on a server/vm using systemd-resolved
2. Deploy a loadbalancer service to port 53 UDP

**Expected behavior**
The host should remain able to resolve DNS, while the in-cluster dns is handing requests coming from external sources.

**Actual behavior**
The host fails to resolve (almost) any DNS requests it makes. Using the deployed DNS service from the outside works fine though.

**Comment by DuncanvR** [comment]
Sounds like we are trying to achieve the same thing! #1581

From what I've seen, the in-cluster DNS resolver uses the host's `/etc/resolve.conf` as a fallback when resolving external domains. I'm not familiar with systemd-resolved, but if it simply makes the host point to kube-dns, the latter might no longer have a way of knowing about outside DNS resolvers.

When you say *requests fail in **most** cases* and *the host fails to resolve **(almost)** any request* though, what exactly do you mean? Does 1 in *n* succeed? Do only the first *n* succeed?

**Comment by lucaelin** [comment]
Only those succeed that are registered within my own DNS, which is some but not many :D
Yeah it seems like your issue is fairly similar but different in context. I'm gonna let other people decide if it should be considered a dup :see_no_evil:

**Comment by DuncanvR** [comment]
Right, so **all** requests for outside domains fail; i.e. it's not an intermittent issue. That distinction might be important.

As for the similarity, we're definitely taking different approaches. I'm using K3OS, which doesn't use systemd. So I can't even try out systemd-resolved.

**Comment by lucaelin** [comment]
I got it working by replacing the svclb load-balancer that comes with k3s with metallb.. metallb lets you specify the address pool and doesn't seem to respond to localhost on the host, keeping resolved available.  
I'm gonna keep this issue open as it's feels more like a workaround than an actual fix to me :)
