### ISSUE TITLE
Flag for disabling kube-proxy

### ISSUE THREAD

**Issue by seanmwinn** [k3s-io/k3s#1641]
Current networking solutions for kubernetes provide a datapath that does not include kube-proxy (cilium, kube-router), however, k3s does not have a flag allowing kube-proxy to be disabled.

k3s should implement a flag to disable kube-proxy

**Comment by runningman84** [comment]
see
https://github.com/rancher/k3s/issues/366

**Comment by onedr0p** [comment]
This is addressed in v1.19 and the issue can be closed.
