### ISSUE TITLE
k3s crash when using dqlite for HA

### ISSUE THREAD

**Issue by huangxuxin233** [k3s-io/k3s#1643]
**Version:**
k3s v1.17.2+k3s1

**Describe the bug**
When testing k3s HA, I start three k3s servers. After running for several hours, one of the servers crashes, and the other server will crash with it. The log of the crash is "Assertion failed: db->follower == NULL (src/db.c: db__open_follower: 44)"

**Comment by wilmardo** [comment]
You seem to experience #1391

**Comment by huangxuxin233** [comment]
> You seem to experience #1391

thanks for your answer, but I think there has some different behavior from that issue, I don't shutdown any one of the three server nodes , but one which is not the cluster-init server crashes，and the other one which is not the cluster-init server also crashes with it. It seems to be due to a crash in dqlite

**Comment by hwaastad** [comment]
Hi, I've seen similar issues. Running two servers (plus one agent), one with initial-cluster, works fine. Having three, the third one crashes. cpu/memory goes through the roof. I can provide debug messages if needed.
I've redeployed clusters multiple times, and it's always the third one freezing.(might be a coincident)

**Comment by huangxuxin233** [comment]
> Hi, I've seen similar issues. Running two servers (plus one agent), one with initial-cluster, works fine. Having three, the third one crashes. cpu/memory goes through the roof. I can provide debug messages if needed.
> I've redeployed clusters multiple times, and it's always the third one freezing.(might be a coincident)

Yes, the same situation I encountered, it was the third server crash. I try to update dqlite to v1.4.1, but it still didn't work.
