### ISSUE TITLE
Not able to Import k3s raspberrypi 4 cluster  into Rancher 2.4

### ISSUE THREAD

**Issue by johnmay1** [k3s-io/k3s#1651]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
curl -sfL https://get.k3s.io | sh -

**Describe the bug**
I am successfully able to install k3s server on raspberrypi 4 on my home n/w. I am trying to import k3s cluster into my rancher hosted on digital ocean. After waiting for several hours i am still getting "This cluster is currently Pending; areas that interact directly with it will not be available until the API is ready." and it still not appears into my rancher.

**To Reproduce**
1. Add new cluster into rancher by "Import Existing Cluster".
2. execute below on k3s server 
kubectl apply -f https://xx.xx.xx.xx/v3/import/bklktn5wfzvqrvqc86nltl9bv8rf6c8m4cwd9zqsb9bvjjzlvzqfhh.yaml

**Expected behavior**
k3s cluster should Imported successfully and should be accessing from Rancher.

**Actual behavior**
Stuck at "Pending" state on Rancher.

**Additional context / logs**
Noticed "ImagePullBackOff" status for cattle-system.
<img width="1173" alt="Screen Shot 2020-04-17 at 7 27 00 PM" src="https://user-images.githubusercontent.com/22088585/79622009-883f4200-80e3-11ea-8256-a28b834d1a0e.png">

**Comment by idanbenyair** [comment]
I had the same issue. When you install k3s install it like this: 
`curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644`
This will give the node the access to download the images for the cattle node/cluster agents.

The other issue I now see after getting over the ErrImagePull error:

`time="2020-05-10T01:03:19Z" level=info msg="Connecting to proxy" url="wss://k3slab.com/v3/connect"
time="2020-05-10T01:03:19Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8sm7s/m-9dcdd2f47983\" not found" error="websocket: bad handshake"
time="2020-05-10T01:03:19Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-05-10T01:03:29Z" level=info msg="Connecting to wss://k3slab.com/v3/connect with token zljbsj5chnwxnq4s6x88hltqwf2z5kvrp9jztd66gn85m5kgz9f25w"
time="2020-05-10T01:03:29Z" level=info msg="Connecting to proxy" url="wss://k3slab.com/v3/connect"
time="2020-05-10T01:03:29Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8sm7s/m-9dcdd2f47983\" not found" error="websocket: bad handshake"
time="2020-05-10T01:03:29Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-05-10T01:03:39Z" level=info msg="Connecting to wss://k3slab.com/v3/connect with token zljbsj5chnwxnq4s6x88hltqwf2z5kvrp9jztd66gn85m5kgz9f25w"
time="2020-05-10T01:03:39Z" level=info msg="Connecting to proxy" url="wss://k3slab.com/v3/connect"
time="2020-05-10T01:03:39Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8sm7s/m-9dcdd2f47983\" not found" error="websocket: bad handshake"
time="2020-05-10T01:03:39Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-05-10T01:03:49Z" level=info msg="Connecting to wss://k3slab.com/v3/connect with token zljbsj5chnwxnq4s6x88hltqwf2z5kvrp9jztd66gn85m5kgz9f25w"
time="2020-05-10T01:03:49Z" level=info msg="Connecting to proxy" url="wss://k3slab.com/v3/connect"
time="2020-05-10T01:03:49Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8sm7s/m-9dcdd2f47983\" not found" error="websocket: bad handshake"
time="2020-05-10T01:03:49Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
`

**Comment by carlskii** [comment]
Hi, Im hitting same issue, however everthing looks OK 

Ubuntu 20.10
Raspberry Pi 4, 4GB 

k3s version v1.19.3+k3s3 (0e4fbfef)

```
kubectl get pods --all-namespaces -o wide
NAMESPACE       NAME                                     READY   STATUS      RESTARTS   AGE   IP          NODE              NOMINATED NODE   READINESS GATES
kube-system     local-path-provisioner-7ff9579c6-zb85j   1/1     Running     0          18m   10.42.0.2   cbourne-desktop   <none>           <none>
kube-system     coredns-66c464876b-nsbjb                 1/1     Running     0          18m   10.42.0.4   cbourne-desktop   <none>           <none>
kube-system     metrics-server-7b4f8b595-4dlv6           1/1     Running     0          18m   10.42.0.3   cbourne-desktop   <none>           <none>
kube-system     helm-install-traefik-sbwqc               0/1     Completed   0          18m   10.42.0.5   cbourne-desktop   <none>           <none>
kube-system     svclb-traefik-t4xcf                      2/2     Running     0          17m   10.42.0.7   cbourne-desktop   <none>           <none>
kube-system     traefik-5dd496474-jxwxv                  1/1     Running     0          17m   10.42.0.6   cbourne-desktop   <none>           <none>
cattle-system   cattle-cluster-agent-786dcf4-wgtdb       0/1     Running     5          16m   10.42.0.8   cbourne-desktop   <none>           <none>
```
```
kubectl logs -f cattle-cluster-agent-786dcf4-wgtdb -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.42.0.8 CATTLE_CA_CHECKSUM=8ad66f5fdfc28aad95fdd0710649485bb2666e6cb0dcd49be0a54b22c059beee CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-786dcf4-wgtdb CATTLE_SERVER=https://192.168.1.16
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
```
