### ISSUE TITLE
gitRepo volume k3s not working

### ISSUE THREAD

**Issue by andresetevejob** [k3s-io/k3s#1654]
**Version:**

**K3s arguments:**

**Describe the bug**

Pod is never created when, i use gitRepo for volume
**To Reproduce**

Create a pod with this yaml :
apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/andresetevejob/smsmonitoringweb.
      revision: master
      directory: .

**Expected behavior**

Pod should be created,a the git repository should be clone
**Actual behavior**

Pod is never created
**Additional context / logs**

Events:
  Type     Reason       Age        From               Message
  ----     ------       ----       ----               -------
  Normal   Scheduled    <unknown>  default-scheduler  Successfully assigned default/gitrepo-volume-pod to k3s
  Warning  FailedMount  10s        kubelet, k3s       Unable to attach or mount volumes: unmounted volumes=[htmls], unattached volumes=[default-token-spbmg htmls]: failed to get Plugin from volumeSpec for volume "htmls" err=no volume plugin matched

**Comment by brandond** [comment]
From the README:

```
k3s is intended to be a fully compliant Kubernetes distribution with the following changes:

* Removed most in-tree plugins (cloud providers and storage plugins) which can be replaced with out of tree addons.
```
The gitRepo volume type has been deprecated for several years, so I'm not surprised it's not included:
https://github.com/kubernetes/kubernetes/pull/63445

**Comment by davidnuzik** [comment]
Please do not exclude version information and args used to install k3s when filing issues.
