### ISSUE TITLE
Move Ansible contrib to sub-repo

### ISSUE THREAD

**Issue by jfmatth** [k3s-io/k3s#1656]
**Describe the solution you'd like**
Can we move the k3s/contrib/ansible folder to it's own sub-repository?  Cloning down the whole of K3s for just that piece seems heavy

**Describe alternatives you've considered**
A personal copy of the contrib/ansible folder, but then i can't get updates

**Comment by geerlingguy** [comment]
It's kind of neat to have it in the main repo, but I do agree having it in this main repo is very 'heavy'—I cloned it today and the repo is like ~700 MB, whereas the playbook is only 57KB...

**Comment by jfmatth** [comment]
Jeff, thanks for the response.

I'll keep an eye out for changes to K3s' main repo.

J
