### ISSUE TITLE
Host to Host latency

### ISSUE THREAD

**Issue by kmcgrath** [k3s-io/k3s#1657]
**Version:**
k3s version v1.17.4+k3s1

**K3s arguments:**
```
curl -sfL https://get.k3s.io | INSTALL_K3S_NAME=ocean-k3s sh -s server --disable-cloud-controller \
      --disable servicelb \
      --disable local-storage \
      --disable traefik \
      --kubelet-arg="cloud-provider=external" \
      --kubelet-arg="provider-id=aws:///$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)/$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
```

**Describe the bug**
On AWS, communication between pods on different hosts experience high latency. Sometimes taking up to 20s to process a request.  The experience is the same using DNS name, ClusterIP or pod IP.  This issue sometimes manifests as DNS lookups and other times with direct pod to pod communication.

**To Reproduce**
Have terraform that will provision k3s master and workers with the required infrastructure:
https://github.com/kmcgrath/k3s-terraform-modules#k3s-only

1. provision the k3s_aws module with terraform apply and 1 worker
2. Log into the master and run: kubectl apply -f https://raw.githubusercontent.com/kmcgrath/k3s-terraform-modules/master/manifests/echo_server.yaml
3. run kubectl get svc - copy the External ELB DNS
4. wait for the DNS to start responding and run `while true; do time curl http://abc5b740e58d34c0a8f10352bc4589d2-359054142.us-east-1.elb.amazonaws.com; done` - replacing with the correct DNS - this will be **fast** - it is also possible to do this curl from a pod against the ClusterIP
5. Use terraform apply to increase the worker count to 2
6. Wait for the worker to register and run the command in step 4 - you will see about every 5 request will take **10-20s to respond**.  This is because some requests hit kube-proxy which roud-robin all requests between both nodes.
7. The fix for this particular situation: `kubectl apply -f https://raw.githubusercontent.com/kmcgrath/k3s-terraform-modules/master/manifests/echo_server-local.yaml` - forcing kube-proxy to only forward requests locally on the instance that it is running on. **fast again**

**Expected behavior**
No significant latency when kube-proxy or other networking needs to communicate from host to host.

**Actual behavior**
latency

**Additional context / logs**
The AWS Cloud Provider and AWS EBS Driver are also running within the cluster.

**Comment by tsahiduek** [comment]
I can confirm this behavior as well.
Pod to pod communication over different instances, result in `request time out`.
