### ISSUE TITLE
API server not working when using PostgreSQL backend

### ISSUE THREAD

**Issue by janeczku** [k3s-io/k3s#1660]
**Version:**
v1.17.4+k3s1

**K3s arguments:**
```
export https_proxy="http://139.25.155.165:8888/"
export http_proxy=$https_proxy
export no_proxy=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
export K3S_DATASTORE_ENDPOINT='postgres://k3s-user:REDACTED@postgresql.dev.XXX:5432/rke_db?sslmode=disable'
curl -sfL https://get.k3s.io | sh -s - server
```

**Describe the bug**
1. Running `kubectl get nodes` on the same machine yields `certificate signed by unknown authority`.

2. Systemd service log contains errors like

```
Apr 21 15:09:07 rke-master-0 k3s[6130]: http: TLS handshake error from 127.0.0.1:36460: remote error: tls: bad certificate
Apr 21 15:09:07 rke-master-0 k3s[6130]: time="2020-04-21T15:09:07.084321664Z" level=error msg="server https://127.0.0.1:6443/cacerts is not trusted: Get https://127.0.0.1:6443/cacerts: x509: certificate signed by unknown authority"
Apr 21 15:09:07 rke-master-0 k3s[6130]: http: TLS handshake error from 127.0.0.1:36462: remote error: tls: bad certificate
Apr 21 15:09:07 rke-master-0 k3s[6130]: time="2020-04-21T15:09:07.691564894Z" level=info msg="Waiting for master node  startup: resource name may not be empty"
```

**To Reproduce**
1. Setup PostgreSQL database
2. On an Ubuntu 18.04 machine run the above command to install k3s.
3. On the same machine run "kubectl get nodes"

**Additional context / logs**

[install.log](https://github.com/rancher/k3s/files/4511183/install.log)

**Comment by Akay7** [comment]
@janeczku have you tried clean `rke_db` database before initialize server?

**Comment by ShylajaDevadiga** [comment]
This issue was not reproducible. As part of our internal sync up earlier, @janeczku would provide more details. Any updates on this @janeczku?

**Comment by janeczku** [comment]
1. Root cause was a misconfigured firewall rule dropping packets to the database server.
2. Attributing factor was that the k3s PostgreSQL client isn't using a dial timeout by default and the k3s process did therefore not exit or log an error for a couple of minutes until the kernel timeout would close the client's TCP socket.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga please revisit/review later after our k3s releases this week.

**Comment by brandond** [comment]
I've seen similar issues when using etcd but the etcd cluster doesn't have quorum when k3s starts. It will just silently hang until the datastore is available with no indication of what it's waiting for.

**Comment by ShylajaDevadiga** [comment]
@janeczku Sorry for the late response. I tried to reproduce the issue blocking traffic to the database server, It timed out after trying to connect for about less 2 min. Do you think the postgres version may be different?

Postgres 11.5
K3s v1.17.4+k3s1
Ubuntu 18.04.
```
Nov 21 00:50:08 ip-172-31-5-170 systemd[1]: Starting Lightweight Kubernetes...
Nov 21 00:50:08 ip-172-31-5-170 k3s[2236]: time="2020-11-21T00:50:08Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/6a3098e6644f5f0dbfe14e5efa99bb8fdf60d63cae89fdffd71b7de11a1f1430"
Nov 21 00:50:10 ip-172-31-5-170 k3s[2236]: time="2020-11-21T00:50:10.511562172Z" level=info msg="Starting k3s v1.17.4+k3s1 (3eee8ac3)"
Nov 21 00:52:19 ip-172-31-5-170 k3s[2236]: time="2020-11-21T00:52:19.959493050Z" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 172.31.13.166:5432: connect: connection timed out"
```

**Comment by ShylajaDevadiga** [comment]
We are unable to reproduce the issue. Please feel free to reopen if you see it happen again
