### ISSUE TITLE
Pod is unable to reach another pod via service

### ISSUE THREAD

**Issue by kamikaze** [k3s-io/k3s#1673]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
```bash
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik --flannel-backend wireguard --flannel-iface wg0" sh -s - --disable-selinux
```

**Describe the bug**
Install 2 pods and services. Then try to connect from one pod into another by using service.

**To Reproduce**
```bash
bash-5.0# psql -U developer -d gitea -h postgresql
^C
bash-5.0# ping postgresql
PING postgresql (10.43.222.113): 56 data bytes
^C
--- postgresql ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
bash-5.0# psql -U developer -d gitea -h postgresql
psql: error: could not connect to server: could not connect to server: Operation timed out
        Is the server running on host "postgresql" (10.43.222.113) and accepting
        TCP/IP connections on port 5432?
```

**Expected behavior**
Should connect

**Actual behavior**
Doesn't connect

If I specify IP (10.42.*.*) which should be resolved by the service, then I'm able to connect.

**Comment by kamikaze** [comment]
More info:
```bash
$ lxc --project einsteinium exec master01 -- kubectl -n einsteinium get svc -o wide
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE   SELECTOR
gitea                             NodePort    10.43.84.86     <none>        3000:30534/TCP   11m   app=gitea
postgresql                        ClusterIP   10.43.222.113   <none>        5432/TCP         11m   app=postgresql
```

```bash
$ lxc --project einsteinium exec master01 -- kubectl -n einsteinium get ep postgresql
NAME         ENDPOINTS        AGE
postgresql   10.42.1.7:5432   12m
```

**Comment by brandond** [comment]
What OS is this on? Also looks like you're using wireguard; I've seen some other complaints about it not behaving reliably.

**Comment by kamikaze** [comment]
> 
> 
> What OS is this on? Also looks like you're using wireguard; I've seen some other complaints about it not behaving reliably. Did you do any configuration of wireguard prior to installing k3s that it might be conflicting with?

I'm running an LXC container with Alpine 3.11 for arm64 as a base image. it doesn't work w/o using wireguard as well. I have installed my own traefik 2.2 stuff instead of bundled and it is working somehow to find pods via services etc. but inter-pod communication doesn't work

**Comment by brandond** [comment]
So you have all of k3s (including containerd) running inside a lxc container? I wonder if the inter-node iptables NAT stuff doesn't work right when it's nested like that. Have you tried with `--flannel-backend=host-gw` ?

**Comment by kamikaze** [comment]
> 
> 
> So you have all of k3s (including containerd) running inside a lxc container? I wonder if the inter-node iptables NAT stuff doesn't work right when it's nested like that. Have you tried with `--flannel-backend=host-gw` ?

Just tried, same
```bash
bash-5.0# psql -U developer -d gitea -h postgresql
psql: error: could not connect to server: could not connect to server: Operation timed out
        Is the server running on host "postgresql" (10.43.41.67) and accepting
        TCP/IP connections on port 5432?
bash-5.0# ping postgresql
PING postgresql (10.43.41.67): 56 data bytes
^C
--- postgresql ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by kamikaze** [comment]
direct connect works fine:
```bash
# psql -U developer -d gitea -h 10.42.1.8
Password for user developer: 
psql (12.2)
Type "help" for help.

gitea=#
```

**Comment by kamikaze** [comment]
Could it be somehow related to Traefik (nothing configured for postgresql there) or it is needed only for external connection passing?

**Comment by kamikaze** [comment]
After installing on a host w/o LXC - I still have the same issue. Here is the traceroute:

```
$ sudo kubectl -n einsteinium exec gitea-f78d849b7-wjwdb -- traceroute postgresql
traceroute to postgresql (10.43.93.38), 30 hops max, 46 byte packets
 1  10.42.0.1 (10.42.0.1)  0.019 ms  0.018 ms  0.010 ms
 2  10.49.185.254 (10.49.185.254)  0.688 ms  0.519 ms  0.505 ms
```

**Comment by renanqts** [comment]
I have the same issue here. Any update on this?
