### ISSUE TITLE
kubectl top pod Error from server (NotFound): podmetrics.metrics.k8s.io

### ISSUE THREAD

**Issue by moluzhui** [k3s-io/k3s#1675]
**Version:**

k3s version v1.17.4+k3s1 (3eee8ac3)
**K3s arguments:**

```
export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666"
curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
```

**Describe the bug**

```
kubectl top pod cpu-demo --namespace=cpu-example
Error from server (NotFound): podmetrics.metrics.k8s.io "cpu-example/cpu-demo" not found
```
**To Reproduce**

[Specify a CPU request and a CPU limit](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#specify-a-cpu-request-and-a-cpu-limit)

Creating a pod based on yaml, top pod failed to view the resource condition

**Expected behavior**

```
NAME                        CPU(cores)   MEMORY(bytes)
cpu-demo                    974m         <something>
```
**Actual behavior**

```
# kubectl top pod cpu-demo --namespace=cpu-example
Error from server (NotFound): podmetrics.metrics.k8s.io "cpu-example/cpu-demo" not found
```
**Additional context / logs**

```
# docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

OS is `Centos7.5`

**Comment by brandond** [comment]
I believe metrics for Docker pods was fixed in https://github.com/rancher/k3s/commit/5c3d7508a7bba011d4b1a5088943c43e28a39ada - have you tried upgrading?

**Comment by moluzhui** [comment]
@brandond I ran the installation script but it was not updated to the `v1.18.2-rc1+k3s1` version seemed to solve the problem.
```
# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.17.4+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/k3s
......
```
Is my update mode wrong?

**Comment by moluzhui** [comment]
the stdout of `kubectl get node -o wide`  is as follows
```
# kubectl get node -o wide
NAME                      STATUS   ROLES    AGE     VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
xxxxxxxxxxxxxxxxxxxxxxx   Ready    master   3h49m   v1.17.4+k3s1   172.xx.xx.xxx   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://17.12.1-ce
```
**Even the top pod system pod fails**

the stdout of `kubectl top pod --namespace=kube-system`  is as follows
```
# kubectl top pod --namespace=kube-system
W0424 21:39:08.595480   20573 top_pod.go:266] Metrics not available for pod kube-system/local-path-provisioner-58fb86bdfd-scmjl, age: 3h47m25.595467399s
error: Metrics not available for pod kube-system/local-path-provisioner-58fb86bdfd-scmjl, age: 3h47m25.595467399s
```
Then, the stdout of `kubectl logs -f  metrics-server-6d684c7b5-jc92b --namespace=kube-system` is as follows
```
E0424 13:34:43.406841       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/metrics-server-6d684c7b5-jc92b: no metrics known for pod
E0424 13:34:43.406855       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/coredns-6c6bb68b64-jhm28: no metrics known for pod
E0424 13:34:43.406859       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/local-path-provisioner-58fb86bdfd-scmjl: no metrics known for pod
E0424 13:34:43.406862       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/traefik-7b8b884c8-zcx5j: no metrics known for pod
E0424 13:34:43.406866       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/svclb-traefik-9pmzd: no metrics known for pod
```

**Comment by brandond** [comment]
I don't think there's a Stable release out with that fix yet. If you want to grab a newer release, you can point the installer at a specific Git commit by setting a variable before running the script: `export INSTALL_K3S_COMMIT=2c49341113702b8ba8360975d5425b611393e765` - that should pull down the most recent commit as of this morning.

**Comment by moluzhui** [comment]
@brandond   Sorry, I am a Chinese student, because the `network problems`, I couldn't get by making ` export INSTALL_K3S_COMMIT = 2 c49341113702b8ba8360975d5425b611393e765 ` download the latest release, whether have other method to download the latest version?

**Comment by brandond** [comment]
You could try grabbing the latest RC from GitHub:
https://github.com/rancher/k3s/releases/tag/v1.18.2-rc2%2Bk3s1
