### ISSUE TITLE
K3s fails to start with etcd autotls environment 

### ISSUE THREAD

**Issue by rungej** [k3s-io/k3s#1678]
**Version:**
v1.17.4+k3s1

**K3s arguments:**
 K3S_TOKEN={token} K3S_DATASTORE_ENDPOINT='https://127.0.0.1:2379' sh -s - --write-kubeconfig-mode 644 --cluster-init

**Describe the bug**
Issue occurs when using self-signed etcd option and K3s.

**To Reproduce**
etcd --auto-tls --advertise-client-urls=https://127.0.0.1:2379 --listen-client-urls=https://127.0.0.1:2379

start K3s

**Expected behavior**
K3s should start

**Actual behavior**
K3s does not start

**Additional context / logs**
Switching back to HTTP allows K3s to start

Is there a flag to allow self-signed certificates to be allowed. Potentially add flag to permit.

**Comment by brandond** [comment]
This isn't k3s specific. I don't see any way to tell kube-apiserver to skip validating the etcd certificates. Either generate the certs manually and ensure that the CA is trusted by k3s, or just use http.

**Comment by brontide** [comment]
Why not...

```
--datastore-cafile value                   (db) TLS Certificate Authority file used to secure datastore backend communication [$K3S_DATASTORE_CAFILE]
```
