### ISSUE TITLE
Failed k3s ctr containers list

### ISSUE THREAD

**Issue by Aliabbask08** [k3s-io/k3s#1679]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
curl -sfL https://get.k3s.io | sh -

**Describe the bug**
Executing k3s ctr containers list inside alpine container and getting below error
**ctr: failed to dial "/run/k3s/containerd/containerd.sock": context deadline exceeded**
i'm able to execute all commands except ctr, crictl
**To Reproduce**
1. Run k3s server using (curl -sfL https://get.k3s.io | sh -) no worker node
2. deploy alpine container on hostNetwork and mount k3s binary from host to pod for k3s command.
3. Run k3s ctr containers list
**Expected behavior**
List of container images

**Actual behavior**

**Additional context / logs**

**Comment by brandond** [comment]
Did you mount the containerd socket path into the pod? Using host net won't help for Unix sockets, you have to mount the actual socket into the pod for that.

**Comment by Aliabbask08** [comment]
> Did you mount the containerd socket path into the pod? Using host net won't help for Unix sockets, you have to mount the actual socket into the pod for that.

@brandond i have not mount containerd socket either..mount only k3s binary.
can u guide me with mount path..thanks!

**Comment by Aliabbask08** [comment]
@brandond  yes i did and it works..but taking long time  to generate output.

**Comment by brandond** [comment]
Not sure what to say about things being slow. How's the load on your system?

**Comment by rbuisson** [comment]
>but taking long time to generate output.
@Aliabbask08 , how long?

I am having the exact same message but with a different setup, wondering if that's related. On a "master" this got resolved somehow after 1h30m or so.
Now trying again on simple nodes, and I am stuck with the error...

**Comment by vadorovsky** [comment]
Hitting the same issue right now, but the thing is that the `/run/k3s` directory doesn't exist on agent nodes at all.

Server

```bash
root@ubuntu2110:~# ls /run/k3s/
containerd
root@ubuntu2110:~# k3s ctr containers list
CONTAINER                                                           IMAGE                                                  RUNTIME                  
1246d9568589fcf2ac5328fe1f0c689892a4e5e23ab1e58ce092e6b26458268f    docker.io/rancher/klipper-helm:v0.7.1-build20220407    io.containerd.runc.v2    
29ad76ff40d1319dd3abf71611709e4dc7ba060e43a284e1212d39daa461ef27    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
694ea67f698c2a0843fcdf8b630a931d96ebb8516ef7d0b260298ebac51240a7    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
7d4301c99c3b8f4c5a97b0ee37a01135b5dd65d8282320b2cb1ba55f06482cf9    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
85d1fb95bf83d90df14f583f397624dd24dc9df0db09668edf11bb0885df801d    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
8a02d111cbe3ec629f4bb1a0928e3b98b89c161af4e09d0e12e9aa69e4c8c437    docker.io/rancher/mirrored-metrics-server:v0.5.2       io.containerd.runc.v2    
981e754588fcd38a00962e7a82218c568377e51cd290171ca4710f8304df8689    docker.io/rancher/mirrored-library-traefik:2.6.2       io.containerd.runc.v2    
9b8ca8dad970e595e6d11890dffadb1bda4c8e40392545569f123f4241fa7753    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
a1bbd2760cdfc3c8c61b60c5dd4e490f8849bb41936d47b8716dd35c52b60209    docker.io/rancher/klipper-lb:v0.3.5                    io.containerd.runc.v2    
acfb9b5fac710fc2fd2cb1e7ee2f65b996b8b347c38adb0b1a150f96c508c8e4    docker.io/rancher/klipper-helm:v0.7.1-build20220407    io.containerd.runc.v2    
afdc3014d068906f9501651f0f408e9217c16f32fdf24297bf68cc754cd38e8e    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
d58fa328aa81da4542d9a3f90d96de4adf1362d004d6b441577646320ddac9d6    docker.io/rancher/mirrored-pause:3.6                   io.containerd.runc.v2    
de9d570813bd6c2b41947fd46f7678117316696651888ea0e7bcf7ab010978b5    docker.io/rancher/klipper-lb:v0.3.5                    io.containerd.runc.v2    
dffca409b8b1501376fa29d11bf4712eb1018ee2e00da8225e0f6f9538d5236d    docker.io/rancher/mirrored-coredns-coredns:1.9.1       io.containerd.runc.v2    
e401cbbb353c95ad48ba15f53f40a2e0cf924da07b647926b6846574a34cec67    docker.io/rancher/local-path-provisioner:v0.0.21       io.containerd.runc.v2
```

Agent:

```bash
root@ubuntu2110:~# ls /run/k3s/
ls: cannot access '/run/k3s/': No such file or directory
root@ubuntu2110:~# k3s ctr containers list
ctr: failed to dial "/run/k3s/containerd/containerd.sock": context deadline exceeded
```

I wanted to use `ctr` to import my container images, without necessity to deploy a registry just for a small testing cluster.

**Comment by vadorovsky** [comment]
Also, I don't see `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` on the agent node.

**Comment by vadorovsky** [comment]
Nevermind, I didn't notice that agent was failing. :facepalm: All good after fixing it.
