### ISSUE TITLE
K3s and Flexvolume on read-only file system like RedHat CoreOS

### ISSUE THREAD

**Issue by stellirin** [k3s-io/k3s#1683]
**Version:**
```
v1.17.4+k3s1 (3eee8ac3)
```

**K3s arguments:**

**Describe the bug**
I run k3s on RedHat CoreOS, which has a partially read-only file system. In logs I see:

```
Apr 25 09:13:18 k3s-0-server k3s[1637]: W0425 09:13:18.062008    1637 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Apr 25 09:13:18 k3s-0-server k3s[1637]: E0425 09:13:18.062064    1637 plugins.go:599] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec/kubernetes: read-only file system
```
https://bugzilla.redhat.com/show_bug.cgi?id=1667606
RedHat solved this by using a different location, specifically `/etc/kubernetes/kubelet-plugins/volume/exec`.

**To Reproduce**
Run k3s in any environment with read-only file system.

**Expected behavior**
K3s will either detect RedHat CoreOS and Fedora CoreOS as having a read-only file system and automatically use the available writable location, or k3s will offer a runtime parameter to customize the location.

**Actual behavior**
K3s raises an error and continues running.

**Additional context / logs**

**Comment by dweomer** [comment]
@stellirin we ran into this as well, see https://github.com/rancher/k3os/issues/282#issuecomment-554771553. A reasonable work-around is to pass `--kube-controller-arg=flex-volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec` to `k3s server`
