### ISSUE TITLE
[Documentation] Update automated upgrades with new system-upgrade-controller

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1773]
The docs today link statically to a specific version. Do we want to keep it this way? For example v0.5.0 is out now (but needs testing) so perhaps it makes sense to leave this as it is as v0.5.0 is not necessarily verified and stable yet.

If we want to keep it manual (manually update docs with each new version bump we consider stable) then I should ensure I have this called out in internal documentation notes so this gets done regularly so docs don't get stale.

**Comment by dereknola** [comment]
This was updated as some point to point to the latest version of the `system-upgrade-controller`. See https://docs.k3s.io/upgrades/automated#install-the-system-upgrade-controller. Closing this as complete.
