### ISSUE TITLE
Invalid node-external-ip causes the node to register incorrectly

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#1775]
**Version:**
v1.18.2+k3s1 (Also in prior versions)

**K3s arguments:**
--node-external-ip=1.2.3.4

**Describe the bug**
Label not set for node with invalid external ip

**To Reproduce**
Scenario1:
1. Install k3s with node-external-ip set to an invalid ip
2.kubectl get node returns No resources found in default namespace.

Scenario2:
1. Install k3s with node-external-ip set to valid ip
2. Update the node, setting node-external-ip set to an invalid ip
3. Node label is not updated and ip change is not reflected.

**Expected behavior**
Label should be updated and new IP should be set to the node

**Actual behavior**
node-external-ip can be set only when existing external or internal IP is used.

**Additional context / logs**
```
May 07 22:36:52 ip-172-31-9-153 k3s[16280]: time="2020-05-07T22:36:52.894843532Z" level=error msg="tunnel context canceled while waiting for connection"
May 07 22:36:52 ip-172-31-9-153 k3s[16280]: time="2020-05-07T22:36:52.895058464Z" level=fatal msg="context canceled"
May 07 22:36:52 ip-172-31-9-153 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 07 22:36:52 ip-172-31-9-153 systemd[1]: k3s.service: Failed with result 'exit-code'.
```

**Comment by brandond** [comment]
By invalid, do you mean just not a valid IP address at all, or just not an address at which the node can be reached?

**Comment by ShylajaDevadiga** [comment]
It has to be an IP that is assigned to the NIC on the host.

**Comment by davidnuzik** [comment]
Had internal discussion scenario 1 expected. Scenario 2 not sure perhaps the setting should be immutable. Also there is no validation on the IP -- we are not giving a good error if the IP cannot be reached. And in both cases k3s doesn't exit -- it hangs (kubelet doesn't start). We shouldn't start any components if the IP is invalid; should exit with a no-nonsense error.

There may be some challenges when it comes to validation. For example Linode external IP is not on interface -- it's on cloud provider level.

**Comment by brandond** [comment]
Would a simple connectivity check work? Might be fragile if NAT or fw rules weren't set up right I suppose, but the node could perhaps attempt to connect back to itself at the listed address, and fail if it cannot?

**Comment by davidnuzik** [comment]
Perhaps. Based on our discussion it sounded like that was an option but yes we could run into difficulties. I think it can be done just requires some thought.
