### ISSUE TITLE
Can't customize default services due to removal of `--no-deploy`

### ISSUE THREAD

**Issue by stuartpb** [k3s-io/k3s#1797]
It looks like k3s is moving forward with the plan to [remove the `--no-deploy` option altogether](https://github.com/rancher/k3s/issues/1382#event-3278556957), and hasn't considered one *very important detail*:

**This prevents users from *modifying* the default k3s services.**

Let's say I want to customize my `coredns` deployment. By default, `k3s` will redeploy its own version of of the `kube-system/coredns` manifest [(you know, for updates)](https://github.com/rancher/k3s/releases/tag/v1.17.5%2Bk3s1), which will, of course, overwrite my customizations.

However, if I use `--disable`, k3s will **delete the coredns service that I had defined**.

The workaround for this requires calling my version of the `coredns` service something *other than `coredns`* so it won't match the name k3s tries to delete if the user's disabled the k3s version of the service.

## Possible solution

If k3s believes its core default services should never be modified by the end user (which is what removing `--no-deploy` would seem to suggest), maybe it should give them names like `k3s-coredns` instead? That way, if a user wants to make their own version of a service k3s deploys, they can just redeploy it without the `k3s-` prefix?

**Comment by brandond** [comment]
Yeah, I noticed the same thing. I ended up just putting a prefix on all my manifests so that the filenames don't conflict. I like the idea of prefixing the default manifests (with k3s- or rancher-) instead of making me prefix all of mine ;)

I think the core issue here is that the deploy controller isn't really meant to be particularly user-friendly at the moment. Beside this issue, there's the fact that any errors encountered during deployment only go to the system log - ideally both success and failure would create events attached to the custom resource. This would also require fixing the fact that (iirc) the custom resource isn't created until after the initial deployment succeeds.

**Comment by i5Js** [comment]
I'm trying to disable traefik but it doesn't work with --disable or --no-deploy flag:

`NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-vr7np   1/1     Running   5          68m
kube-system   metrics-server-7566d596c8-xsx8z          1/1     Running   5          68m
kube-system   coredns-8655855d6-h2nrs                  1/1     Running   5          68m
kube-system   traefik-758cd5fc85-2b8b2                 1/1     Running   4          66m
kube-system   svclb-traefik-849qd                      2/2     Running   0          11m`

It was installed with this command:

`cur -sfL https://get.k3s.io | sh -s - --disable traefik`

What I'm doing wrong?

Thanks

**Comment by piotron** [comment]
@i5Js maybe try this
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik" sh -s -
```
This is for server, you don't need to disable on agents.

**Comment by i5Js** [comment]
Hey! thanks for answer, finally I made it with this:

`INSTALL_K3S_EXEC=" -t ${NODE_TOKEN} --tls-san <nodename> --no-deploy servicelb --disable traefik`

**Comment by stuartpb** [comment]
I just realized, in a k3os context, you can technically emulate the behavior of `--no-deploy` by setting the content of the corresponding manifest file to `""` in the `write_files` array of `/var/lib/rancher/k3os/config.yaml` (since there's no `delete_files` array). That would make it so, on startup, before `k3s` parses the file for document names to delete, they're all removed first, so the "disable" step would do nothing

Of course, if you're doing this, you don't need to specify `--disable` for the service any more, since this would also negate the function of *applying* that manifest.

You just have to make sure that there's never a situation where an upgrade restores your manifests, and then k3s restarts without re-executing the k3os configuration.

**Comment by larssb** [comment]
It's been really informative to read this issue. I'm just wondering though, isn't it making good sense to use `--disable` and use some custom name for deploying ones own version of e.g. `coredns`. I mean in that way, everyone administering the K3S cluster should be able to transparently tell that the installed `coredns` version is not the default one.
