### ISSUE TITLE
proposal: keep all settings to the install script

### ISSUE THREAD

**Issue by thewilli** [k3s-io/k3s#1799]
**Is your feature request related to a problem? Please describe.**

Maintaining an existing k3s Installation I'd like to get an overview of the setup configuration. When using the installation script for updates, some settings might get lost as well. In general, I'd expected an update to re-use the original configuration unless its values are overwritten.

**Describe the solution you'd like**

The installation options are [passed as environment variables](https://github.com/rancher/k3s/blob/ad4c542/install.sh#L22-L85) prefixed with `INSTALL_K3S_`. It would be easy to save them [just as done](https://github.com/rancher/k3s/blob/ad4c542/install.sh#L627) with the `K3S_` prefixed ones. The resulting file could be optionally sourced for updates to maintain the original values.

**Describe alternatives you've considered**

* Manually replace the `k3s` binary for updates (i.e. not using the installation script).
  * This would work but one would loose the comfort and additional options of the installation script.

**Comment by brandond** [comment]
k3s currently keeps all the arguments in the `k3s.io/node-args` annotation on each node. I think the intent is to persist the actual resulting arguments to the server or agent, rather than the variables that they might have been derived from.

**Comment by thewilli** [comment]
> k3s currently keeps all the arguments in the k3s.io/node-args annotation on each node 

while this works for the server arguments, it won't (and probably doesn't make sense to keep as annotation) for the installer options like `INSTALL_K3S_CHANNEL` or `INSTALL_K3S_BIN_DIR`. This is why the [upgrade using the installation script](https://rancher.com/docs/k3s/latest/en/upgrades/basic/#upgrade-k3s-using-the-installation-script) requires you to

> [...] re-run the installation script using the same flags

So why don't we save those values and either reuse them or at least allow to see all related configuration values used in a previous installation, so one can decide whether to re-apply them for the update.
