### ISSUE TITLE
Cannot configure the cluster name on initialization via the command line flag

### ISSUE THREAD

**Issue by ghost** [k3s-io/k3s#1806]
### Feature request

There is no way to configure a `clusterName` via the command line, during the initialization of the new K3s cluster. Due to that, the cluster name of a new cluster is `default`. That causes issues when we have to manage multiple K3s clusters via a single kubeconfig file (all kubeconfigs were flattened into a single `~/.kube/config` file).

### Potential solution

A command line flag which allows us to configure the cluster name on initialization.

**Comment by mkatt** [comment]
When I write `clusterName`, I'm thinking about something like [kubeadm's clusterName](https://github.com/kubernetes/kubeadm/blob/1cfbee6a2e900f794515e12e3598292ec4908df6/kinder/pkg/kubeadm/config.go#L87).

**Comment by brandond** [comment]
I don't believe clusters have any idea of their own name. See: https://github.com/kubernetes/kubernetes/issues/44954

If you're merging the kubeconfig files, the point at which you import it from the new cluster might be the time to set it in your config file?

**Comment by brandond** [comment]
Also see this comment: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L268

**Comment by mkatt** [comment]
@brandond, the use-case here is that we have an internal tool (similar to helm) which uses these cluster names to identify the correct environment to deploy stuff.

Imagine a scenario where an developer has access to three clusters:

* remote development AKS
* remote development K3s
* local development K3s

AKS configures an unique cluster name in the kubeconfig file but the two K3s clusters will have it's clusterName set to `default`. Now if we merge all kubeconfig files into one, the internal tool we use won't be able to target an specific K3s cluster as both are named `default`.

Do you consider this as a feature that K3s should provide? Are you open to a potential PR which would allow the K3s users to set `clusterName`?

**Comment by brandond** [comment]
I get the use case, but I kinda doubt that k3s is going to change behavior that the upstream k8s apiserver folks declined to add. According to k8s devs, cluster name is currently considered a property external to the cluster and exists only within the cloud provider configuration.

Could you maybe just set and query an annotation on the kube-system namespace or something?

**Comment by caroline-suse-rancher** [comment]
Closing due to age
