### ISSUE TITLE
Pi 4 Embedded HA: Cannot join masters, "TLS handshake error...remote error: tls: bad certificate"

### ISSUE THREAD

**Issue by R8s6** [k3s-io/k3s#1808]
**Version:**

k3s version v1.18.2+k3s1 (698e444a)
Also tried INSTALL_K3S_CHANNEL=1.16 and 1.17, with the same errors.

**K3s arguments:**

Master 1 (192.168.0.110): 
`curl -sfL https://get.k3s.io | K3S_TOKEN=wv5hemayPiKPUSDu sh -`

Master 2 (192.168.0.111):   
`curl -sfL https://get.k3s.io | K3S_URL=https://192.168.0.110:6443 K3S_TOKEN=wv5hemayPiKPUSDu INSTALL_K3S_EXEC="server --server https://192.168.0.110:6443" sh -`

I also uninstalled and tried: `curl -sfL https://get.k3s.io | K3S_TOKEN=wv5hemayPiKPUSDu INSTALL_K3S_EXEC="server --server https://192.168.0.110:6443" sh -`

I also tried `KS3_TOKEN=K10f1c8becc5f32f0b408c7a64247b13029b39cf5d6c39d885fb0c95df3c2ce5788::server:wv5hemayPiKPUSDu`, which is found in Master 1's `/var/lib/rancher/k3s/server/node-token`

**Describe the bug**

Master 1: installed correctly, k3s.service started normally, but after Master 2 tried to join, `systemctl status k3s` gave this error:
```
May 18 21:04:21 km1 k3s[1605]: I0518 21:04:21.897746    1605 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
May 18 21:04:26 km1 k3s[1605]: I0518 21:04:26.538937    1605 log.go:172] http: TLS handshake error from 192.168.0.111:57438: remote error: tls: bad certificate
```

Master 2 cannot start k3s.service (at the last step of the installation), it gave this error:
```
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```
And journalctl -xe outputs:
```
-- Automatic restarting of the unit k3s.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
May 18 21:48:53 km2 systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: Unit k3s.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has finished shutting down.
May 18 21:48:53 km2 systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has begun starting up.
May 18 21:48:54 km2 k3s[27276]: time="2020-05-18T21:48:54.148270584Z" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 21:48:54 km2 k3s[27276]: time="2020-05-18T21:48:54.417177952Z" level=fatal msg="starting kubernetes: preparing server: https://192.168.0.110:6443/v1-k3s/server-bootstrap: 403 Forbidden"
May 18 21:48:54 km2 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 21:48:54 km2 systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 21:48:54 km2 systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has failed.
```

**To Reproduce**

0. Installed ubuntu 18.04 LTS on 3 Pi 4s.

1. added `cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` to `/boot/firmware/nobtcmd.txt`, updated all packages, then rebooted.

2. 1st server (192.168.0.110): generate a SECRET, for example, `wv5hemayPiKPUSDu`, then `curl -sfL https://get.k3s.io | K3S_TOKEN=wv5hemayPiKPUSDu sh -`

3. On the 2nd/3rd server: `curl -sfL https://get.k3s.io | K3S_URL=https://192.168.0.110:6443 K3S_TOKEN=wv5hemayPiKPUSDu INSTALL_K3S_EXEC="server --server https://192.168.0.110:6443" sh -`

**Expected behavior**

2nd and 3rd masters to join the 1st server

**Actual behavior**

The 2nd and 3rd server would not have this directory: /var/lib/kubelet, they couldn't start k3s.service and had this error:
```
May 17 19:48:24 km2 k3s[8587]: time="2020-05-17T19:48:24.682555482Z" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 17 19:48:24 km2 k3s[8587]: time="2020-05-17T19:48:24.899135217Z" level=fatal msg="starting kubernetes: preparing server: token is not valid: https://192.168.0.110:6443/apis: 401 Unauthorized"
May 17 19:48:24 km2 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 17 19:48:24 km2 systemd[1]: k3s.service: Failed with result 'exit-code'.
May 17 19:48:24 km2 systemd[1]: Failed to start Lightweight Kubernetes.
```

**Additional context / logs**

The problem was very similar to, if not identical with, [issue 1442](https://github.com/rancher/k3s/issues/1442).

Also, I saw the OP of [issue 1798](https://github.com/rancher/k3s/issues/1798) also tried to run 3 masters with embedded database on Pi 4, so I actually tried his exact installation:
```
First master:

curl -sfL https://get.k3s.io | \
INSTALL_K3S_EXEC="server --cluster-init" sh -

Remaining master nodes (2 for 3 total master nodes):

curl -sfL https://get.k3s.io | \
K3S_URL=https://<ip address of initial master >:6443 \
K3S_TOKEN=< token from initial master > \
INSTALL_K3S_EXEC="server --server https://<ip address of initial master >:6443" \
sh -
```
(only to replace initial master's IP and token found in `/var/lib/rancher/k3s/server/node-token`.)

But I had the same errors, which was very weird.

Did I do anything wrong?

Thank you.

**Comment by narimantos** [comment]
i'm having the same issue.

While trying to join the master i get: 
>server https://127.0.0.1:46237/cacerts is not trusted: Get https://127.0.0.1:46237/cacerts: x509: certificate has expired or is not yet valid

**Comment by brandond** [comment]
@narimantos is time set correctly on both nodes? Was it set properly at the time k3s was installed on the first node?

**Comment by narimantos** [comment]
Yes that seems be the problem!

Next issue: 
> json: cannot unmarshal array into Go struct field Control.Skips of type map[string]bool 

I think this had something to do with k3s version. 
Workers version: 1.18.2
Master version: 1.17.3

**Comment by brandond** [comment]
Don't do that. Everything should be the same version. Masters can be newer than agents for a short time during upgrades but not the other way around.
