### ISSUE TITLE
How do I set up a pod to allow scheduling on the master

### ISSUE THREAD

**Issue by moluzhui** [k3s-io/k3s#1814]
I would like to allow pod scheduling on k3s master, which can be done using `kubectl taint` on k8s, but failed in k3s.

**Version:**

```
k3s -v
k3s version v1.18.2+k3s1 (698e444a)
```
**K3s arguments:**

```
export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --bind-address 192.168.x.xx"
```

**Describe the bug**

Failed to set master schedulable pod

**To Reproduce**

```
$ kubectl get node -o wide
NAME     STATUS   ROLES    AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node-4   Ready    <none>   17h   v1.18.2+k3s1   192.168.x.xxx   <none>        Ubuntu 16.04.6 LTS   4.15.0-72-generic   docker://19.3.2
node-3   Ready    master   17h   v1.18.2+k3s1   192.168.x.xx   <none>        Ubuntu 16.04.6 LTS   4.4.0-143-generic   docker://18.9.3
```
kubectl taint failed
```
$ kubectl taint node node-3 node-role.kubernetes.io/master-
error: taint "node-role.kubernetes.io/master" not found
```

**Expected behavior**

I want to be able to do the same thing on the k8s cluster installed by kubeadm, changing the master to be a callable node
```
$ kubectl taint node node-2 node-role.kubernetes.io/master-
node/node-2 untainted
```

**Actual behavior**

```
$ kubectl taint node node-3 node-role.kubernetes.io/master-
error: taint "node-role.kubernetes.io/master" not found
```

Do k3s use other commands to implement this functionality or do I have some configuration errors?

**Comment by brandond** [comment]
k3s masters are scheduleable by default.

**Comment by moluzhui** [comment]
> k3s masters are scheduleable by default.

I'm afraid not. I tried to extend my application to three replicas of a service, but all the pods(five) were on the `agent node`. .And I get the same results when I repeatedly create and delete the application.

**Comment by brandond** [comment]
There are no taints on k3s masters by default. You're getting an error telling you the same thing when you try to remove it: `taint not found`.

I have a 3-node cluster where all three are masters, and I have not manually added or removed any taints:
```
brandond@seago:~$ kubectl describe nodes | grep Taints
Taints:             <none>
Taints:             <none>
Taints:             <none>
```

There's probably some other reason why pods aren't being scheduled onto that node. Do you have resources, affinities, or nodeSelectors in the pod spec that only that node can satisfy?

**Comment by moluzhui** [comment]
@brandond 
 My k3s two-node cluster is a `master` and an `agent`.

```
$ kubectl get node -o wide
NAME     STATUS   ROLES    AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node-4   Ready    <none>   42h   v1.18.2+k3s1   192.168.0.24   <none>        Ubuntu 16.04.6 LTS   4.15.0-72-generic   docker://19.3.2
node-3   Ready    master   42h   v1.18.2+k3s1   192.168.0.23   <none>        Ubuntu 16.04.6 LTS   4.4.0-143-generic   docker://18.9.3
```

I have checked that there is no Taints, 

```
$ kubectl describe nodes | grep Taints
Taints:             <none>
Taints:             <none>
```
The following is the command for me to install `k3s master and agent`. I have not done any other configuration, but to achieve the effect you mentioned
**master**
```
$ export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --bind-address myMasterHostIP"
$ curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
```

**agent**
```
$ export K3S_URL="https://myMasterHostIP:6443"
$ export K3S_TOKEN="K106edce2ad174510a840ff7e49680fc556f8830173773a1ec1a5dc779a83d4e35b::server:5a9b70a1f5bc02a7cf775f97fa912345"
$ export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666"
$ curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=${K3S_URL} K3S_TOKEN=${K3S_TOKEN} sh -
```

I didn't configure anything else. But I don't know why it didn't work the way you did

If you know where I was wrong, please let me know. thank you in advance!

**Comment by brandond** [comment]
Is *nothing* being scheduled onto the master, or are you just not seeing the pods distributed as you would expect? What does `kubectl get pods -A -o wide` show?

I doubt it's related, but you might try to get both nodes on the same kernel and docker version, just for consistency's sake. Ubuntu 16.04 also went end-of-life almost a year ago...

**Comment by moluzhui** [comment]
Except for the pod scheduling in the `kube-system` namespace on the `Master` node, other application pods are scheduled on the `agent` node
```
$ kubectl get pod -o wide -A
NAMESPACE     NAME                                                              READY   STATUS      RESTARTS   AGE     IP           NODE     NOMINATED NODE   READINESS GATES
kube-system   helm-install-traefik-ljvdw                                        0/1     Completed   0          6d13h   10.42.0.5    node-3   <none>           <none>
kube-system   svclb-traefik-f7q4k                                               2/2     Running     0          6d13h   10.42.1.2    node-4   <none>           <none>
kube-system   metrics-server-7566d596c8-snlml                                   0/1     Evicted     0          6d13h   <none>       node-3   <none>           <none>
kube-system   metrics-server-7566d596c8-rtg26                                   1/1     Running     0          98m     10.42.1.46   node-4   <none>           <none>
kube-system   traefik-758cd5fc85-nw582                                          1/1     Running     5          6d13h   10.42.0.6    node-3   <none>           <none>
kube-system   local-path-provisioner-6d59f47c7-zqmtv                            1/1     Running     7          6d13h   10.42.0.3    node-3   <none>           <none>
kube-system   svclb-traefik-wgcfl                                               2/2     Running     10         6d13h   10.42.0.7    node-3   <none>           <none>
kube-system   coredns-8655855d6-7phv6                                           1/1     Running     5          6d13h   10.42.0.4    node-3   <none>           <none>
default       test-1-846994f5fmnsxg                                             1/1     Running     0          51m     10.42.1.47   node-4   <none>           <none>
default       test-2-5d6f6dd56f645                                              1/1     Running     0          51m     10.42.1.49   node-4   <none>           <none>
default       test-2-5d6f6dd5pw5lg                                              1/1     Running     0          51m     10.42.1.50   node-4   <none>           <none>
default       test-2-5d6f6dd5lkjlw                                              1/1     Running     0          51m     10.42.1.48   node-4   <none>           <none>
default       test-3-cf4697b6pfdjm                                              1/1     Running     0          51m     10.42.1.51   node-4   <none>           <none>
```
I don't think all five pods will be stored on node-4 whilch is a `agent node`.

**Comment by brandond** [comment]
It looks to me like it's working normally, scheduling pods onto both nodes. What's the problem? Are there not enough resources to run all these pods on the same node? If so, you should ensure that the pod resource requests and limits are set correctly.

**Comment by grisu48** [comment]
Hey! I somehow ended up here having the same issue. In my case the underlying reason was a non-existing path in one of the `volumes` section of a deployment. `kubectl` was complaining about taints, however the actual reason was that something was just off in my `deployment.yml` file.

So, for all future fellas that also end up here, check your yaml files first, the error messages in `kubectl describe pods` are sometimes a bit misleading.
