### ISSUE TITLE
k3s doesn't seem to allow dns queries on an ipv6 enabled node

### ISSUE THREAD

**Issue by sixcorners** [k3s-io/k3s#1826]
**Version:**
k3s version v1.18.2+k3s1 (698e444a)

**K3s arguments:**
no arguments to server

**Describe the bug**
pods can't query dns on ipv6 node

**To Reproduce**
run k3s on machine with ipv6 working
install the helm tiller (from v2) from inside a pod like how gitlab's kubernetes integration does it.
this is the command it seems to run
```
helm init --tiller-tls --tiller-tls-verify --tls-ca-cert /data/helm/helm/config/ca.pem --tiller-tls-cert /data/helm/helm/config/cert.pem --tiller-tls-key /data/helm/helm/config/key.pem --service-account tiller
```

**Expected behavior**
helm chart downloads I guess

**Actual behavior**
```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.43.0.10:53: server misbehaving
```
**Additional context / logs**
lots of lines like this from the coredns pod.
```
[ERROR] plugin/errors: 2 kubernetes-charts.storage.googleapis.com. A: dial udp [2606:4700:4700::1111]:53: connect: network is unreachable
```

**Comment by brandond** [comment]
Do you have ipv6 connectivity to the internet, or just within the cluster? Any other ideas why coredns wouldn't be able to establish an outbound ipv6 connection to the 1.1.1.1 ipv6 endpoint?

**Comment by sixcorners** [comment]
the former. The node can connect to the internet but I didn't do anything special in k3s to enable it there.
I'm not sure. It didn't seem like it was attempting to. There were no errors showing it failed to try to contact 1.1.1.1.

**Comment by brandond** [comment]
It's there in your error from coredns: `dial udp [2606:4700:4700::1111]:53: connect: network is unreachable`. That's the ipv6 version of 1.1.1.1. It sounds like ipv6 to the internet isn't working - or at least not for DNS.

**Comment by sixcorners** [comment]
@brandond Sure. Why would that be though? If the node's ipv6 is working fine what should I start checking?
