### ISSUE TITLE
didn't find a plugin capable of expanding the volume

### ISSUE THREAD

**Issue by liyongxian** [k3s-io/k3s#1841]
**Version:**

**K3s arguments:**

**K3s Version**
NAME        STATUS   ROLES    AGE   VERSION
storage-2   Ready    master   14h   v1.17.2+k3s1
**K3s Server args:**    
server --docker   \
    --kubelet-arg="feature-gates=ExpandInUsePersistentVolumes=true"

**Describe the bug**

Can Not Support Expanding Volume
**To Reproduce**

1、Update **“local-path (default)”** to Allow Expanding, **"allowVolumeExpansion: true"**
  **NAME                     PROVISIONER               RECLAIMPOLICY   VOLUMEBINDINGMODE**      **ALLOWVOLUMEEXPANSION**  
local-path (default)     rancher.io/local-path     Delete          WaitForFirstConsumer   **true**           
        
2、Create pvc by The **“local-path (default)”**
3、Mount The PVC In a Pod
4、The PVC's  STATUS Is "Bound" 
**NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS** 
pvc-local      **Bound**    pvc-2fe7b2c8-2709-4a58-ab44-ebf1b1ec6dc5   **1Gi**        RWO            local-path 
5、Resize The PVC.
But The Size Can Not Resize.
The Log: **didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC**
![aaaa](https://user-images.githubusercontent.com/18571576/83217738-0260ed00-a19f-11ea-9f07-225ddf50df22.jpg)
**Expected behavior**

The PVC Can Resize.
**Actual behavior**

**Additional context / logs**

**Comment by liyongxian** [comment]
Including the controller of expanding volume In Vendor of K3s,But it does not work.
**vendor--k8s.io--kubernetes--pkg--controller--volume--expand--expand_controller.go**

**Comment by philippevidal80** [comment]
Did you try to install [external-resizer](https://github.com/kubernetes-csi/external-resizer) in you K3S @liyongxian ?

I did it and it works perfectly (with AWS EBS driver as default storageclass).
