### ISSUE TITLE
K3s in Docker (K3d), CSI plugins, and /var/lib/kubelet mount

### ISSUE THREAD

**Issue by carstenkoester** [k3s-io/k3s#1846]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
(K3s in Docker, see below)

**Describe the bug**
With K3s running inside Docker, trying to run a CSI plugin. Plugin fails to start with error,

```
spec: path "/var/lib/kubelet/pods" is mounted on "/var/lib/kubelet" but it is not a shared mount
```

The plugin in question is Cert-Manager-CSI in my case; I suspect though that the issue might apply to at least _some_ other CSI plugins as the pattern of mounting `/var/lib/kubelet/pods` seems somewhat generic across CSI plugins.

**To Reproduce**
I've been using K3d, but (based on my initial little bit of analysis) it looks like the issue would be no different when K3s was started in Docker using docker-compose or manually using `docker run`. What matters, is that K3s runs in Docker, not in a "regular" deployment.

```
k3d create
export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager-csi/master/deploy/cert-manager-csi-driver.yaml

kubectl describe pod -n cert-manager cert-manager-csi-jfwqs
```

**Expected behavior**
Would love to be able to experiment with CSI plugins in K3d. (Understanding, of course, that some CSI plugins are less suitable than others for a K3s-in-Docker use case naturally).

**Actual behavior**
CSI plugin will be in `CreateContainerError` status, with the following seen in `kubectl describe pod`:

```
  Warning  Failed     11s        kubelet, k3d-k3s-default-server  Error: failed to generate container "47231776e20dce21ebd062e45ce52adaf90ab64c1684aea55789d5f42354ff9f" spec: path "/var/lib/kubelet/pods" is mounted on "/var/lib/kubelet" but it is not a shared mount
```

**Additional context / logs**
First of all, reason I am opening this issue here (in K3s), and not in K3d or Cert-Manager, is because:

 - my initial assumption was that the issue somewhat comes down to the K3s Dockerfile (`package/Dockerfile`) declaring `/var/lib/kubelet` as a volume, and for the purpose of this issue, it would not matter _how_ K3s gets started in Docker. (Although admittedly, mount options during container instantiation might be a way to resolve this.)

 - Taking a cursory glance at other CSI plugin manifests, it does seem like mounting `/var/lib/kubelet` or `/var/lib/kubelet/pods` into a CSI plugin DaemonSet, with bidirectional mount propagation, is a pattern that is common to several (perhaps most, or all) CSI plugins -- not just a one-off for Cert-Manager's plugin

So it seems that K3s' Dockerfile [declares `/var/lib/kubelet` as a volume](https://github.com/rancher/k3s/blob/02dccd328a2ded49efbee5c05a439fbe6e6b22a0/package/Dockerfile#L15).

In the absence of any other mount options, this will cause the K3s container to mount `/var/lib/kubelet` as an anonymous volume:

```
$ docker inspect k3d-k3s-default-server  | jq '.[0].Mounts[] | select(.Destination=="/var/lib/kubelet")'
{
  "Type": "volume",
  "Name": "9fb8120c8d2da95d03b6ba17a90e9c15ea9c0abeb7fee0f4ac44c34045ca587d",
  "Source": "/var/lib/docker/volumes/9fb8120c8d2da95d03b6ba17a90e9c15ea9c0abeb7fee0f4ac44c34045ca587d/_data",
  "Destination": "/var/lib/kubelet",
  "Driver": "local",
  "Mode": "",
  "RW": true,
  "Propagation": ""
}
```

Not sure if there's anything that can be done when actually mounting the volume, to mount it such that it is shared.

If I remove the volume from Dockerfile (effectively reverting commit 1429496b39bf1b091fe679c61a00923ea9a6e224), then that issue goes away and the CSI plugin loads just fine. However, I am sure that that would re-introduce whatever issue 1429496b39bf1b091fe679c61a00923ea9a6e224 was fixing in the first place as it seems there was a deliberate change made to make `/var/lib/kubelet` a volume. Not sure what the options are...

**Comment by zer0def** [comment]
Bumped into this yesterday, as well. Haven't given it much thought, because it was easier to use a different solution ad-hoc, but might be that `pkg/rootless/mounts.go` would benefit from either additional flags or an additional mount, similarly to how Kubelet's code does this.

**Comment by muttonhead** [comment]
I also ran in to this issue adding `-v "/var/lib/kubelet:/var/lib/kubelet:shared"` to my cluster create command has gotten passed this particular error. Though I am running into other problems down the line from this.

**Comment by belerweb** [comment]
any updated?
