### ISSUE TITLE
Docs on builtin service load balancer; NodeAffinity for host ports feature request

### ISSUE THREAD

**Issue by epicfilemcnulty** [k3s-io/k3s#185]
Would be nice to have more docs on the builtin LB and traefik.
Is it possible right now to "pinpoint" a LB for a service to a specific node? 
In my particular case I have a 3 nodes k3s cluster, 1 master and 2 workers. 
I have 2 different DNS services, which I want to expose to the world: first one listening on 53 port of the master node, and second one on 53 port of both worker nodes.

**Comment by cjellick** [comment]
Yeah, svc lb needs explains in much greater detail. Current docs basically hand wave the feature.

**Comment by catherineluse** [comment]
For reference, is what we currently say about the default service load balancer:

> K3s includes a basic service load balancer that uses available host ports. If you try to create a load balancer that listens on port 80, for example, it will try to find a free host in the cluster for port 80. If no port is available, the load balancer will stay in Pending.
> 
> To disable the embedded load balancer, run the server with the `--disable servicelb` option. This is necessary if you wish to run a different load balancer, such as MetalLB.

@ShylajaDevadiga Do you have any information on the configuration options for this load balancer?
