### ISSUE TITLE
K3S wrong  backend for Rpi 4 on MicroSD Cards

### ISSUE THREAD

**Issue by armandleopold** [k3s-io/k3s#1850]
**Version:**
v1.18.2+k3s1

**K3s arguments:**
Install procedure can be found here : 
https://github.com/armandleopold/raspberry-install-scripts/tree/master/k3s-install

**Describe the bug**
K3S sqlLite backend doesn't manage well I/O disk latency and therefore makes a chain reaction when we have slow MicroSD Card I/O in particular on raspberry pi clusters. 
It makes the [Kubernetes controller manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) to loose leader election because of timeout and then force restart kubelet. It generates also restart on all the pods that are using leader election, in particular Storage Providers.

**To Reproduce**
- Have x1 Raspberry Pi 4 with slow MicroSD Card.
- Install **raspbian buster** with **arm_64=1** & rpi-update the kernel to **5.4.42-v8+**
- Install k3s with default backend

**Expected behavior**
- No restart of storage provider pods
- No restart of k3s kubelet

**Actual behavior**
- k3s crashloop
- storage provider pods crashloop

**Additional context / logs**
Had to switch to etcd backend and enforce R/W priority on k3s process using : 
```bash
sudo ionice -c2 -n0 -p `pgrep k3s`
```

It has been one night and no restart at all as before (~230 restarts)

I still see some I/O (the cluster has nothing install in it except : 
traefik/openebs/rancher/grafana/gitlab-runner
![https://i.imgur.com/UAQYdnm.png](https://i.imgur.com/UAQYdnm.png)

Does it happen to somebody else or is it just me ?

**Comment by brandond** [comment]
You actually get less IO load using etcd than sqlite? That's the first time I've heard anyone say that - there are a number of folks out there running k3s on Pi using sqlite, and when I tried to go from sqlite to etcd I had to put it on SSD to keep the IO latency down.

**Comment by armandleopold** [comment]
I must assume i am not really sure, i have tried a lot of things, but i can assure you that the best fit for me Is to Switch to etcd right now. Maybe has it something to do with the version of raspbian ? Of the kernel ?, The fact that i am using aarch64 instead or armv7 on raspbian buster 32bits . I honnestly don't know.

**Comment by plsnotracking** [comment]
@armandleopold were you able to run etcd as the backend successfully? If yes, how's the stability/performance been? Etcd seems like a solid software but too heavy for something like a pi?

**Comment by armandleopold** [comment]
Yes, succeded, Great performances, i have to run it on SSD with OS Booting on it directly.
With 400 Mo/s Read and 240 Mo/s Write. No problems.
**I DO NOT RECOMMEND TO RUN K3S ETCD BACKEND ON SD-CARD** 
Closing the issue.
