### ISSUE TITLE
Set up slack notifications for build failures

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1861]
This is an internal task for the Rancher dev team.

Based on our 6/2/20 planning session, we established that we should enable slack notifications in our internal k3s-developers channel so we get notified on k3s publishing failure. We should set this up for k3s-upgrade as well.

We touched on possibly setting this up for successful builds too - we can experiment with this and see if it's too noisy or not.

**Comment by briandowns** [comment]
I don't know if this is all that necessary as Drone provides a UI, sends emails, and Github also shows the status of the builds. Adding another notification seems arbitrary especially since notification channels are quickly muted.

**Comment by cwayne18** [comment]
agreed with @briandowns, additionally it's really tricky to get apps access to slack, let's close this out and re-open if anything changes.
