### ISSUE TITLE
[RFE] Ability to change the Rancher UI background color to differentiate Dev from Prod environments

### ISSUE THREAD

**Issue by victorcasado** [k3s-io/k3s#1862]
Persona: Rancher Operator/Rancher Admin

As a Rancher Operator, I would like to have in the Rancher UI a visual evidence of the environment I am working on, so that I am not running a deployment in a Dev environment, for example.

That's why I would like to have the ability to change the Rancher UI background color to differentiate Dev from Prod environments.

gz#10458

**Comment by brandond** [comment]
Shouldn't this be in the rancher issue tracker, not k3s?

**Comment by zaggash** [comment]
I think this can be closed in favor of https://github.com/rancher/rancher/issues/27480
