### ISSUE TITLE
k3s upgrade/installation overrides NO_PROXY env variable in k3s.service.env

### ISSUE THREAD

**Issue by aureq** [k3s-io/k3s#1873]
**Version:**
Version: `v1.18.3+k3s1`

**K3s arguments:**
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest INSTALL_K3S_EXEC="--docker" sh -

**Describe the bug**
I run k3s in an environment that requires a proxy to access the internet. For this to work, my environment has multiple environment variables. Namely `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY`.

To prevent k3s internal services to reach my proxy when make API calls, I also set a `NO_PROXY` variable. For example:
`NO_PROXY="192.168.2.203/24,172.17.0.1/16,10.0.0.0/8,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16,*.svc"`

During the upgrade to version `v1.18.3+k3s1`, the file `/etc/systemd/system/k3s.service.env` is (re)created but the `NO_PROXY` variable only contained `192.168.2.203/24`.

**To Reproduce**
1. Set the `http*`/`HTTP*` variables.
2. Set the `NO_PROXY` variable to your liking, with at least one extra hostname or IP address.
3. Upgrade (or install) k3s on a bare metal server
4. Look into `/etc/systemd/system/k3s.service.env` for the `NO_PROXY` variable.

**Expected behavior**
The variable `NO_PROXY` stored in `/etc/systemd/system/k3s.service.env` should match the current shell. The server's IP address should be in that variable too.

**Actual behavior**
1. The variable `NO_PROXY` only contains the server's main IP address.
2. Previous customization on `NO_PROXY` are lost.

**Comment by Id2ndR** [comment]
Is this still reproducible with latest version? I'm using *v1.20.2+k3s1* and the `NO_PROXY` variable was set according to my shell when I installed K3S.

**Comment by brandond** [comment]
No. This was fixed in #936
