### ISSUE TITLE
tls: bad certificate problems

### ISSUE THREAD

**Issue by mschneider82** [k3s-io/k3s#1884]
**Version:**
v1.18.3+k3s-af10a574 (master branch build) with embedded etcd

**K3s arguments:**
server --cluster-init --flannel-backend=wireguard --no-deploy=traefik

 sh -s - server --server https://server1:6443 --flannel-backend=wireguard --no-deploy=traefik 
 sh -s - server --server https://server1:6443 --flannel-backend=wireguard --no-deploy=traefik 

**Describe the bug**
the 3 node cluster with embedded etcd works, but when I reboot the 2nd or 3rd server it cannot connect to server1

server1 says: 
```
k3s[5776]: http: TLS handshake error from 127.0.0.1:53262: remote error: tls: bad certificate
```
server2 (which was rebootet):
```
time="2020-06-10T10:12:07.713137818+02:00" level=info msg="To join node to cluster: k3s agent -s https://extip.of.server2:6443 -t ${NODE_TOKEN}"
time="2020-06-10T10:12:07.714879025+02:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2020-06-10T10:12:07.715263629+02:00" level=info msg="Run: k3s kubectl"
time="2020-06-10T10:12:07.715720335+02:00" level=info msg="module overlay was already loaded"
time="2020-06-10T10:12:07.715959995+02:00" level=info msg="module nf_conntrack was already loaded"
time="2020-06-10T10:12:07.716155196+02:00" level=info msg="module br_netfilter was already loaded"
time="2020-06-10T10:12:07.717352581+02:00" level=info msg="Waiting for API server to become available"
http: TLS handshake error from 127.0.0.1:34400: remote error: tls: bad certificate
http: TLS handshake error from 127.0.0.1:34410: remote error: tls: bad certificate
```

**To Reproduce**
I also tried it without wireguard, it just exists in the master branch build, not in the latest release with dqlite.

**Expected behavior**
if should reconnect

**Comment by chris-makaio** [comment]
seriously, I'm currently on the 15th try to setup a basic k3s multi-network cluster and there are always TLS problems coming up. I do understand that this is OSS, but while we can't afford enterprise licensing I'd be happy to pay for bug-fixing the TLS mess.

**Comment by mschneider82** [comment]
@chris-makaio  try to setup and use an external etcd (e.g. with etcdadm) its currently way more stable and reboot resistant

**Comment by brandond** [comment]
Hopefully nobody is setting up any new dqlite HA clusters. Managed etcd has been supported since 1.19 and many improvements have been made since this issue was opened.

**Comment by chris-makaio** [comment]
I started „playing“ with k3s 2 weeks so please excuse my noob question: „managed“ means external db via eg postgress? Or running an external etcd control plane?

**Comment by Bessonov** [comment]
@chris-makaio  because of mention of 1.19, it must be the [embedded etcd](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/).
