### ISSUE TITLE
running rootless logs error message for system container stats constantly

### ISSUE THREAD

**Issue by coopstah13** [k3s-io/k3s#1885]
**Version:**
`k3s version v1.0.1 (e94a3c60)`

**K3s arguments:**
`--rootless`

**Describe the bug**
The server starts up and starts spewing a log message nonstop.

**To Reproduce**
Just run k3s with rootless

**Expected behavior**
Logs are not noisy with spurious messages

**Actual behavior**
See below for log messages

**Additional context / logs**
```
E0610 03:19:46.286411   26976 summary_sys_containers.go:47] Failed to get system container stats for "/systemd/user.slice/user-1001.slice": failed to get cgroup stats for "/systemd/user.slice/user-1001.slice": failed to get container info for "/systemd/user.slice/user-1001.slice": unknown container "/systemd/user.slice/user-1001.slice"
```
and
```
W0610 14:34:22.870751   26976 container_manager_linux.go:628] [ContainerManager] Failed to ensure state of "/systemd/user.slice/user-1001.slice": failed to find pid namespace of init process
```

**Comment by AkihiroSuda** [comment]
You can ignore these messages. Rootless mode doesn't support cgroup anyway.

**Comment by coopstah13** [comment]
I figured it is benign, but it is going to fill up the logs very quickly and it makes it hard to look for actual problems within the log. It will cause a disk space issue. We will plan on using logrotate to ensure we don't over utilize disk space, but still it makes it hard to diagnose any problems when the log is filled with spam like this.
