### ISSUE TITLE
LoadBalancer service does not get ExternalIP, if LoadBalancer service come up first before system pods during first boot 

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#1888]
**Version:**
k3s version v1.18.3+k3s1
Ubuntu 20.04

**K3s arguments:**
--node-external-ip=<ExternalIP>

**Describe the bug**
LoadBalancer service does not get ExternalIP if it comes up first, while the svclb is still in ContainerCreating state during initial install.

**To Reproduce**
1. Install k3s 
2. Deploy loadbalancer service (not waiting for the svclb controller to be Running)
3. Load balancer service does not get the External IP

**Expected behavior**
Having --node-external-ip set, LoadBalancer service should have been updated with the External IP after certain interval.

**Actual behavior**
LoadBalancer service continues to have internal IP even after svclb daemonset is in Running state.

**Additional Info**
```
kubectl get nodes -o wide
NAME              STATUS   ROLES    AGE     VERSION        INTERNAL-IP    EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-6-176   Ready    master   3h37m   v1.18.3+k3s1   172.31.6.176   18.217.67.101   Ubuntu 18.04.3 LTS   4.15.0-1057-aws   containerd://1.3.3-k3s2

kubectl get svc
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
kubernetes        ClusterIP      10.43.0.1      <none>         443/TCP          3h38m
rancher-k3s-svc   LoadBalancer   10.43.165.66   172.31.6.176   8000:32138/TCP   3h37m
```

**Comment by fapatel1** [comment]
@ShylajaDevadiga would you be able to revalidate this one to see if this still needs to be resolved?

**Comment by caroline-suse-rancher** [comment]
closing due to age and no longer an issue - please reopen or create anew if issue reappears.
