### ISSUE TITLE
404 Page Not found with standard traefilk deployment 

### ISSUE THREAD

**Issue by adamj-codethink** [k3s-io/k3s#1894]
hi all,

I am not sure if this is the best place to raise this issue/query, please feel free to point me elsewhere.

ISSUE:

I have deployed k3s onto an ubuntu 20.04 server using:

`curl -sfL https://get.k3s.io | sh -`

k3s installs correctly and i see all pods come up and report a *running* status.

I have connected from my local laptop to the remote cluster using the credentials from `/etc/rancher/k3s/k3s.yaml` and replacing local host with my public DNS.

I can connect to the cluster fine and i see: 

```
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-7566d596c8-cz7wh          1/1     Running     0          4d4h
kube-system   local-path-provisioner-6d59f47c7-z9wgc   1/1     Running     0          4d4h
kube-system   helm-install-traefik-lldfg               0/1     Completed   0          4d4h
kube-system   coredns-8655855d6-wx8gx                  1/1     Running     0          4d4h
kube-system   svclb-traefik-6sbjd                      2/2     Running     0          4d4h
kube-system   traefik-758cd5fc85-gw4df                 1/1     Running     0          4d4h

```

I have then tried port forwarding both of traefik pods to my localhost to try and access the Traefik dashboard, as this is my first time using Traefik, but i keep seeing 404 erros.

The kubcetl logs report:

```
Handling connection for 9000
E0612 18:04:28.993970   37483 portforward.go:400] an error occurred forwarding 9000 -> 8080: error forwarding port 8080 to pod 4d650ed8f732ac429c8fa49f663964fe70d2266cd55ec689cfc07e9993f2c2c3, uid : failed to execute portforward in network namespace "/var/run/netns/cni-2477ab46-c326-f0fe-ec5c-3621d1c94d32": socat command returns error: exit status 1, stderr: "2020/06/12 17:04:28 socat[3058] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused\n"
```

EXPECTED BEHAVIOUR:

What i have expected to see was the standard traefik dashboard appear with no services available, is this a correct understanding or do i need to further configure traefik to enable this behaviour? 

Thanks for your time

**Comment by brandond** [comment]
I can't tell much from the information you've shared, but it appears that the pod isn't listening on the port you've port forwarded to. Are you sure you configured it to listen for the dashboard on 8080?

**Comment by adamj-codethink** [comment]
Hey @brandond,

Sorry for my slow reply i was taking some time away.

I did try 80/8080 as suggested in the Traefik documentation, unless k3s uses a different port?

**Comment by woa7** [comment]
@adamj-codethink i have the same problem
how can i debug it?

**Comment by adamj-codethink** [comment]
Hey @woa7, i never got anywhere with this, sorry, please keep me updated though

**Comment by woa7** [comment]
@brandond how can i debug this problem? or collect all the Information for a debugging form your side?

**Comment by brandond** [comment]
I guess I would probably start by confirming that you've enabled the Traefik dashboard?

**Comment by woa7** [comment]
for my case I switched form k3s to k3s without Traefik together with RIO

**Comment by Id2ndR** [comment]
By default, traefik dashboard is not enable. Rancher K3S documentation does not explain how to enable it, so I will:
- the [traefik helm chart](https://github.com/helm/charts/tree/master/stable/traefik) allows you to enable dashboard with values `dashboard.enabled`
- since K3S v1.19, you can customize helm values with additional config files [see here for details](https://rancher.com/docs/k3s/latest/en/helm/)

In my case, I create the file `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` with following content
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      domain: "traefik.localhost"
 ```
About 30 seconds latter, traefik was redeployed with the dashboard enabled (look at `helm -n kube-system get values traefik` to check it), and the dashboard is accessible at http://traefik.localhost
