### ISSUE TITLE
how to clean unused images, just like `docker system prune`

### ISSUE THREAD

**Issue by 2637309949** [k3s-io/k3s#1900]
hello, i use k3s for a period of time and the disk of my server is full

Here are some tracker log from my server, i know i can use `docker system prune` in docker env, but i donot know  how to do in k3s. can you see see my probleam, thk so much
```sh
Filesystem                                                                                 1K-blocks     Used Available Use% Mounted on
udev                                                                                         3923948        0   3923948   0% /dev
tmpfs                                                                                         789228     9368    779860   2% /run
/dev/vda1                                                                                   41152812 25905904  13343252  67% /
tmpfs                                                                                        3946124        0   3946124   0% /dev/shm
tmpfs                                                                                           5120        0      5120   0% /run/lock
tmpfs                                                                                        3946124        0   3946124   0% /sys/fs/cgroup
/dev/vdb1                                                                                  102686648 15806308  81621128  17% /data
tmpfs                                                                                        3946124       12   3946112   1% /var/lib/rancher/k3s/agent/kubelet/pods/54c97049-2ea6-11ea-9425-00163e0eee13/volumes/kubernetes.io~secret/coredns-token-2rndp
shm                                                                                            65536        0     65536   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/bbfe551e1001b4c51d8cca6d4f5c9714cb58173ce8e5b1724fef3a921b598416/shm
overlay                                                                                     41152812 25905904  13343252  67% /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/bbfe551e1001b4c51d8cca6d4f5c9714cb58173ce8e5b1724fef3a921b598416/rootfs
overlay                                                                                     41152812 25905904  13343252  67% /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/7a145faf74bc445afd143e2c84f65f3ad3f0de1729f61fbd804b4e35cffd1f3c/rootfs
tmpfs                                                                                        3946124        8   3946116   1% /var/lib/rancher/k3s/agent/kubelet/pods/5dc4e594-2ea6-11ea-9425-00163e0eee13/volumes/kubernetes.io~secret/ssl
tmpfs                                                                                        3946124       12   3946112   1% /var/lib/rancher/k3s/agent/kubelet/pods/5dc96e45-2ea6-11ea-9425-00163e0eee13/volumes/kubernetes.io~secret/default-token-5w542
tmpfs                                                                                        3946124       12   3946112   1% /var/lib/rancher/k3s/agent/kubelet/pods/5dc4e594-2ea6-11ea-9425-00163e0eee13/volumes/kubernetes.io~secret/traefik-token-c7lxb
s
```

**Comment by brandond** [comment]
kubernetes nodes automatically performs garbage collection of images. You can find documentation on the default thresholds here:

https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#user-configuration

If for some reason you want to muck about with this manually, you can try:
`sudo k3s crictl images` to see what images have been pulled locally
`sudo k3s crictl rmi --prune` to delete any images no currently used by a running container

**Comment by 2637309949** [comment]
> kubernetes nodes automatically perform image garbage collection. You can find documentation on the default thresholds here:
> 
> https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#user-configuration
> 
> If for some reason you want to muck about with this manually, you can try:
> `sudo k3s crictl images` to see what images have been pulled locally
> `sudo k3s crictl rmi --prune` to delete any images no currently used by a running container

thk, every much

**Comment by 2637309949** [comment]
> kubernetes nodes automatically perform image garbage collection. You can find documentation on the default thresholds here:
> 
> https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#user-configuration
> 
> If for some reason you want to muck about with this manually, you can try:
> `sudo k3s crictl images` to see what images have been pulled locally
> `sudo k3s crictl rmi --prune` to delete any images no currently used by a running container

`~# sudo k3s crictl rmi --prune
Incorrect Usage: flag provided but not defined: -prune

NAME:
   crictl rmi - Remove one or more images

USAGE:
   crictl rmi IMAGE-ID [IMAGE-ID...]
FATA[2020-06-22T17:21:58.911596931+08:00] flag provided but not defined: -prune        `

**Comment by brandond** [comment]
You didn't say what version of k3s you're using. You might need to upgrade to get that option? I'm on 1.18.3.

**Comment by johanneskastl** [comment]
> You can tune these thresholds on your k3s nodes by adding arguments to the service command line: `--kubelet-arg=image-gc-high-threshold=85 --kubelet-arg=image-gc-low-threshold=80`

I just stumbled upon the same issue in nodes running 1.26.8 k3s version. Manually pruning reduced the size of `/var/lib/rancher/k3s/agent/` from 94GB to 8GB.

Does anyone know which default settings for the kubelet settings that @brandond mentioned are in use in current k3s/kubernetes releases? Apparently the garbage collection was never triggered on my machine...

**Comment by johanneskastl** [comment]
Thanks for the quick reply, @onedr0p!
