### ISSUE TITLE
Return extra information via PodSandboxStatusRequest

### ISSUE THREAD

**Issue by cadeniyi** [k3s-io/k3s#1904]
**Is your feature request related to a problem? Please describe.**
When using docker as the container runtime, crictl is not able to retrieve useful information about pods such as the pod hostname (which can be set in the pod YAML). 

This is contrast to using containerd as the container runtime which does return this information (via the info field of the PodSandboxStatusResponse returned by the PodSandboxStatus function.

**Describe the solution you'd like**
Make PodSandboxStatus (in kubelet/dockershim/docker_sandbox.go) return the config field that is already available in the PodSandboxDetails. The hostname field will then be available via crictl.

I have an implementation ready for review.

**Describe alternatives you've considered**
There is no easy way to get this information via crictl. 

**Additional context**
The CRI spec does declare the info field as optional. The only alternative would be to get this hostname field added as a mandatory part of the PodSandboxStatus message.

**Comment by brandond** [comment]
Is this a k3s issue? Sounds like a dockershim issue, and dockershim is going away.
