### ISSUE TITLE
Manifests customization overriden on cluster restart

### ISSUE THREAD

**Issue by bflorat** [k3s-io/k3s#1909]
**Version:**
v1.17.5+k3s1 (58ebdb2)

**K3s arguments:**
```
ExecStart=/usr/local/bin/k3s <br />
server <br />
--write-kubeconfig-mode=644 \
```
**Describe the bug**
I want to customize local-path.yaml due to bug #1908. As explained in [the doc](https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests), I don't use a k apply but I changes directly  `/var/lib/rancher/k3s/server/manifests/local-storage.yaml`.

It works fine but each time the cluster is restarted (after a machine reboot for instance), the initial version of `local-storage.yaml` overrides my changes.

**To Reproduce**
1) Make a change in `/var/lib/rancher/k3s/server/manifests/local-storage.yaml`, check it is applied
2) Stop the cluster and start it again : 
```bash
# k3s-killall.sh 
# systemctl restart k3s 
```
3) Check the local-path deployment : you changes should have been overriden by initial version

**Expected behavior**
Keep the changes made to manifests in `/var/lib/rancher/k3s/server/manifests` among cluster restarts.

**Actual behavior**
The changes are lost

** Workaround **
Make a hack in systemd script to override with our files version.

**Comment by brandond** [comment]
Yes. There are a couple open issues about it. The one that best represents the current state is probably #1797.

Your best bet at the moment is to copy local-storage.yaml to something unique (local-storage-custom.yaml, for example), then add --disable=local-storage to the command-line options, and restart k3s.
