### ISSUE TITLE
Interop with k8s?

### ISSUE THREAD

**Issue by ShadowJonathan** [k3s-io/k3s#1916]
**Is your feature request related to a problem? Please describe.**
Not specifically to a problem, but more to a use-case. K8s' standards allow [built-in node labels](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels) to group them together by topology or environment requirements.

`k3s` exposes some specific ones (`beta.kubernetes.io/instance-type=k3s`, `node.kubernetes.io/instance-type=k3s`, etc. diagnostic ones), which alongside taints could be used for a bigger k8s control plane + cloud nodes interoperating with k3s edge nodes, creating a hybrid/failover domain.

**Describe the solution you'd like**
A way for k3s agents to join a k8s control plane normally, if possible, or for the k3s master to become a "delegate" that forwards kubelet requests from a k8s control plane to their individual nodes.

**Describe alternatives you've considered**
I also thought about a controller pattern, where a controller in the control plane connects to the k3s control plane via it's api, and syncs it via virtual kubelets in the k8s control plane, effectively "outsourcing" it, in a manner not unlike the [Virtual Cluster](https://github.com/kubernetes-sigs/multi-tenancy) or [`k3v`](https://github.com/ibuildthecloud/k3v)

**Comment by chris13524** [comment]
Direct interoperability would be a problem because of two ways k3s works:
 - it manages the certificates via tokens
 - it uses websockets to connect to the master nodes

It would be nice to have a solution that bundles all the k8s components into one binary without managing anything else.

**Comment by ShadowJonathan** [comment]
@stale piss off

**Comment by ShadowJonathan** [comment]
@stale no

**Comment by brandond** [comment]
We don't have any plans to support clusters with mixed Kubernetes distributions.

**Comment by ShadowJonathan** [comment]
@brandond then close this issue on that note if you think that's an indefinite decision, don't let issues with feature requests like these rot. Proper feature and project management triages features like these properly, and either commits them then, commits them as a "nice to have", or rejects them, it does not let each rot until nobody has passion for them anymore, to let be reaped by anti-productive bots like @stale, no wonder k3s has lost all acceleration

**Comment by brandond** [comment]
It's your issue, and this is an open source project. If it something doesn't align with our goals, we at SUSE are unlike to work on it, but you are welcome to open a pull request referencing this issue - which is why we aren't going to close it unilaterally.

**Comment by ShadowJonathan** [comment]
@stale no
