### ISSUE TITLE
Joining a new master sometimes hangs with round robin DNS

### ISSUE THREAD

**Issue by Jille** [k3s-io/k3s#1918]
**Version:**
k3s version v1.17.6+k3s1 (bd7fb4b0)
K3OS v0.10.2 on x86 in a Xen VM

**K3s arguments:**
k3s server --cluster-init # on node 1
k3s server # on node 2 & 3

I have a DNS entry with three IN A records pointing at all three servers. I've used that for the K3S_URL.

**Describe the bug**
k3s hangs when trying to join a cluster when using a round robin DNS to point at the master.

**To Reproduce**
Set up a cluster and use a round robin DNS address as the K3S_URL. k3s might hang at first startup for the second and third node. I presume it only works if DNS randomly gives the IP of a node that's already up and running.

**Expected behavior**
I expected k3s to try all resolved IP addresses to see if any of them is serving and use that IP to join.

**Actual behavior**
k3s just hung. `service k3s-service restart` solved it.

```
$ tail -f /var/log/k3s-service.log
time="2020-06-17T13:44:19Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae"
time="2020-06-17T13:44:20.827382120Z" level=info msg="Starting k3s v1.17.6+k3s1 (bd7fb4b0)"
time="2020-06-17T13:44:21.918629593Z" level=info msg="Active TLS secret  (ver=) (count 7): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.2.29:192.168.2.29 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:a6b2e3695159bd7ccbede8412e6ea3af42450c4992ab9a8a3ba8d18f2cc6349e]"
time="2020-06-17T13:44:21.919633294Z" level=info msg="Active TLS secret  (ver=) (count 8): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.2.29:192.168.2.29 listener.cattle.io/cn-k3s.skynet.quis.cx:k3s.skynet.quis.cx listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:df747e60d3f9f09e446ff70cd74001aa7b8bb8f04f87145889dc0ee2f9d996b9]"
<no more output>
```

192.168.2.29 is the IP of the node I'm setting up. 192.168.2.28 is the working node 1. 192.168.2.30 would have bene node 3, but I didn't start it yet.

**Comment by brandond** [comment]
Trying all three would be nice. Right now I believe it assumes you're using some sort of external LB that is able to health check nodes, or point it at a node that you know is up.
