### ISSUE TITLE
CLI help lists wrong default bind address

### ISSUE THREAD

**Issue by thecjharries** [k3s-io/k3s#1928]
**Version:**
k3s version v1.18.3+k3s1 (96653e8d)

**K3s arguments:**
vanilla

**Describe the bug**
`k3s server --help` reports the following default bind address: `0.0.0.0` ([source](https://github.com/rancher/k3s/blob/master/pkg/cli/cmds/server.go#L73))

However, the actual default is `127.0.0.1` as seen [here](https://github.com/rancher/k3s/blob/master/pkg/cli/server/server.go#L238), [here](https://github.com/rancher/k3s/blob/master/pkg/server/server.go#L67), and [here](https://github.com/rancher/k3s/blob/master/pkg/server/server.go#L259) (and probably a few other places).

**To Reproduce**
To see the help menu,
```
k3s server --help
```
Writing the kube config seems to work well to display the default bind address.
```
k3s server --write-kubeconfig ~/.kube/k3s-bind-demo.yml
```

**Expected behavior**
Either the help should list `127.0.0.1` as the default or `0.0.0.0` should be the default bind address.

**Conclusion**
Based on the prevalence of `127.0.0.1`, I'd be more than happy to submit a PR to change the CLI help to `127.0.0.1`.

**Comment by erikwilson** [comment]
What is the difference with `netstat -tlnp | grep 6443` when using that flag?
