### ISSUE TITLE
Better handling when installing on incompatible filesystem

### ISSUE THREAD

**Issue by bobdvb** [k3s-io/k3s#1930]
**Is your feature request related to a problem? Please describe.**
K3S is often used in embedded targets, many of which use overlayfs as their default rootfs. I have two separate targets that I am working with, both of which use a rootfs which use this structure. It is very frustrating that the k3s installer does not at least warn the user that the install will ultimately fail due to fs incompatibility. I note from my investigation that others have seen similar issues with zfs as the rootfs.

**Describe the solution you'd like**
- Install script shall notify the user that they are targeting a system which is incompatible with the underlying container system and warn them that this will cause issues.
- Install script should ask the user if they wish to continue or cancel to take actions that would allow the install to succeed.
- Install script could have a environment variable which declares an alternative location for the container elements so that users can use a separate volume (such as USB drive, NVMe or NFS/Longhorn).

**Describe alternatives you've considered**
- Spent too much time diagnosing the issue, ultimately used an attached block device formatted with ext4 and created a symbolic link to a folder on that device.
- Setting fire to the whole device

**Additional context**
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4V2
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_Fire3

**Comment by ibuildthecloud** [comment]
The directory /var/lib/rancher/k3s can not be a overlayfs mount. If this is the case the pods will fail with a fairly opaque error. Something like "operation not supported." We should on start of the agent validate that /var/lib/rancher/k3s fstype is not of know bad types.

**Comment by dweomer** [comment]
Would not #1991 give folks a way around this limitation?
