### ISSUE TITLE
Doc improvement needed around config.toml.tmpl

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1932]
This issue originates from https://github.com/rancher/k3s/issues/1031 which asked for various tweaks and enhancements to the documentation. This issue was created so we can close that issue (which is nearly complete) to make things cleaner.

> The config.toml.tmpl will be treated as a Golang template file, and the config.Node structure is being passed to the template, the following is an example on how to use the structure to customize the configuration file https://github.com/rancher/k3s/blob/master/pkg/agent/templates/templates.go#L16-L32

- [ ] _This needs to be improved. What is the config.Node that it is referencing?_

**Comment by DanSibbernsen** [comment]
I'm stumbling into this as a new user of k3s, trying to adjust some parameters inside the `config.toml.tmpl`. I *think* the `config.Node` variable it mentions is [here](https://github.com/k3s-io/k3s/blob/d4522de06a4bf9674288d6d1ec1b203a6b63767b/pkg/agent/config/config.go#L45) and the data structure is defined [here](https://github.com/k3s-io/k3s/blob/b0ed13485588651b1eba3cb0ba423c500325a28f/pkg/daemons/config/types.go#L45)

Does that seem right?

**Comment by brandond** [comment]
yep, that's the one.
