### ISSUE TITLE
kubelet doesn't honor streaming-connection-idle-timeout=0 setting

### ISSUE THREAD

**Issue by benwbooth** [k3s-io/k3s#1936]
**Version:**

k3s version v1.18.3+k3s1 (96653e8d)

**K3s arguments:**

ExecStart=/usr/local/bin/k3s server --disable traefik --disable servicelb --kubelet-arg=streaming-connection-idle-timeout=0

**Describe the bug**

Passing the argument --kubelet-arg=streaming-connection-idle-timeout=0 to the kubelet does not disable the streaming connection idle timeout.

**To Reproduce**

- Install k3s with argument  --kubelet-arg=streaming-connection-idle-timeout=0
- Start a pod
- kubectl exec into the pod with /bin/sh
- Wait 4 hours
- kubectl exec disconnects

**Expected behavior**

kubectl exec should not disconnect after 4 hours

**Actual behavior**

kubectl exec still disconnects after 4 hours

**Additional context / logs**

k3s journalctl logs show that streaming-connection-idle-timeout=0 is set, but it doesn't help:

> Jun 20 12:34:47 maple k3s[3050]: time="2020-06-20T12:34:47.916064988-07:00" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/31f16867327c45f309297f2846b7f471edba2b97c394cddb49d4e70ff7d41bcd/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --container-runtime-endpoint=/run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=maple --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --kubelet-cgroups=/systemd/system.slice --node-labels= --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --runtime-cgroups=/systemd/system.slice --serialize-image-pulls=false --streaming-connection-idle-timeout=0 --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"

Running the following to get the kubelet config also shows `streamingConnectionIdleTimeout` set to 0s which should disable it:

```
kubectl proxy --port=8001 &
NODE_NAME="maple"; curl -sSL "http://localhost:8001/api/v1/nodes/${NODE_NAME}/proxy/configz" | jq '.kubeletconfig|.kind="KubeletConfiguration"|.apiVersion="kubelet.config.k8s.io/v1beta1"' > kubelet_configz_${NODE_NAME}
```

```
{
  "syncFrequency": "1m0s",
  "fileCheckFrequency": "20s",
  "httpCheckFrequency": "20s",
  "address": "0.0.0.0",
  "port": 10250,
  "tlsCertFile": "/var/lib/rancher/k3s/agent/serving-kubelet.crt",
  "tlsPrivateKeyFile": "/var/lib/rancher/k3s/agent/serving-kubelet.key",
  "authentication": {
    "x509": {
      "clientCAFile": "/var/lib/rancher/k3s/agent/client-ca.crt"
    },
    "webhook": {
      "enabled": true,
      "cacheTTL": "2m0s"
    },
    "anonymous": {
      "enabled": false
    }
  },
  "authorization": {
    "mode": "Webhook",
    "webhook": {
      "cacheAuthorizedTTL": "5m0s",
      "cacheUnauthorizedTTL": "30s"
    }
  },
  "registryPullQPS": 5,
  "registryBurst": 10,
  "eventRecordQPS": 5,
  "eventBurst": 10,
  "enableDebuggingHandlers": true,
  "healthzPort": 10248,
  "healthzBindAddress": "127.0.0.1",
  "oomScoreAdj": -999,
  "clusterDomain": "cluster.local",
  "clusterDNS": [
    "10.43.0.10"
  ],
  "streamingConnectionIdleTimeout": "0s",
  "nodeStatusUpdateFrequency": "10s",
  "nodeStatusReportFrequency": "5m0s",
  "nodeLeaseDurationSeconds": 40,
  "imageMinimumGCAge": "2m0s",
  "imageGCHighThresholdPercent": 85,
  "imageGCLowThresholdPercent": 80,
  "volumeStatsAggPeriod": "1m0s",
  "kubeletCgroups": "/systemd/system.slice",
  "cgroupsPerQOS": true,
  "cgroupDriver": "cgroupfs",
  "cpuManagerPolicy": "none",
  "cpuManagerReconcilePeriod": "10s",
  "topologyManagerPolicy": "none",
  "runtimeRequestTimeout": "2m0s",
  "hairpinMode": "promiscuous-bridge",
  "maxPods": 110,
  "podPidsLimit": -1,
  "resolvConf": "/run/systemd/resolve/resolv.conf",
  "cpuCFSQuota": true,
  "cpuCFSQuotaPeriod": "100ms",
  "maxOpenFiles": 1000000,
  "contentType": "application/vnd.kubernetes.protobuf",
  "kubeAPIQPS": 5,
  "kubeAPIBurst": 10,
  "serializeImagePulls": false,
  "evictionHard": {
    "imagefs.available": "5%",
    "nodefs.available": "5%"
  },
  "evictionPressureTransitionPeriod": "5m0s",
  "evictionMinimumReclaim": {
    "imagefs.available": "10%",
    "nodefs.available": "10%"
  },
  "enableControllerAttachDetach": true,
  "makeIPTablesUtilChains": true,
  "iptablesMasqueradeBit": 14,
  "iptablesDropBit": 15,
  "failSwapOn": false,
  "containerLogMaxSize": "10Mi",
  "containerLogMaxFiles": 5,
  "configMapAndSecretChangeDetectionStrategy": "Watch",
  "enforceNodeAllocatable": [
    "pods"
  ],
  "kind": "KubeletConfiguration",
  "apiVersion": "kubelet.config.k8s.io/v1beta1"
}
```

**Comment by brandond** [comment]
Does it work with the docker backend? If so, k3s may need to the correct options to the containerd config to pass this along as per https://github.com/containerd/cri/issues/1057#issue-414329803

**Comment by benwbooth** [comment]
Thanks. Switching to the docker backend fixed it. 

Is there any way we could get an error message or a warning in the docs stating that this feature does not work with containerd?

**Comment by brandond** [comment]
I think this might actually be an upstream kubernetes issue, not k3s. The link above is for adding support to containerd, I don't see anywhere that the option was plumbed through to kubelet, where it continues to be a no-op on non-docker platforms.
