### ISSUE TITLE
/sys/devices/system/cpu/cpu0/cache: no such file or directory

### ISSUE THREAD

**Issue by guleng** [k3s-io/k3s#1937]
**Version:**

v1.15.3-k3s.1

**K3s arguments:**

k3s agent --pause-image advertise/pause:3.1 --registry-domain docker.io --registry-user  --registry-pass  --run-mode join_k8s --k8s-version v1.14.1 --node-name 172.16.194.73 --node-ip 172.16.194.73 --node-label device=camera -v 2 --log /mnt/nfs0/k3s/k3s-agent.log --kubelet-arg bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubelet-arg kubeconfig=/etc/kubernetes/kubelet.conf --kubelet-arg pod-infra-container-image=advertise/pause:3.1 --kubelet-arg v=2 --kubelet-arg enforce-node-allocatable=pods --kubelet-arg kube-reserved=cpu=100m,memory=100Mi,ephemeral-storage=1Gi --kubelet-arg system-reserved=cpu=100m,memory=100Mi,ephemeral-storage=1Gi --kubelet-arg cni-conf-dir=/etc/cni/net.d --no-flannel -d /mnt/nfs0/k3s --token hwfep2.iw7q7ltqdwxbati5 --discovery-token-ca-cert-hash sha256:8d505d3e153a36750e51da7ecfd7790f0a5eb39cdc80bfbd326091e1c7696f25 --server https://172.16.190.250:8443 --registry http://172.16.190.201:5000 --kubelet-arg cluster-dns=10.32.0.10 --kubelet-arg cluster-domain=cluster.local --kubelet-arg rotate-certificates=true --kubelet-arg rotate-server-certificates=true

**Describe the bug**

The emergence of k3s agent frequency division e0609 11:39:28.435288 19219 machine.go:288 ] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory
![image](https://user-images.githubusercontent.com/40238640/85295576-b7eb3b80-b4d2-11ea-982b-ea1e7420eedb.png)

**To Reproduce**

In general, if this problem occurs, it will be OK after restarting. If it is not restarted, it is not ready

**Additional context / logs**

![image](https://user-images.githubusercontent.com/40238640/85296084-6e4f2080-b4d3-11ea-90d7-b3e0bfcb6170.png)

**Comment by brandond** [comment]
This is an issue with cadvisor, not k3s: https://github.com/google/cadvisor/pull/2550

Fortunately this has already been fixed upstream, all you need to do is upgrade.
