### ISSUE TITLE
systemd stuck with log option

### ISSUE THREAD

**Issue by monfardineL** [k3s-io/k3s#1961]
/kind bug

**Version:**
v1.17.2+k3s1, v1.17.7+k3s1

**K3s arguments:**
server --no-deploy traefik **--log /var/log/k3s.log**

**Describe the bug**
When deploying K3s with **--log** flag, systemctl command won't "finish" after the startup, leaving the console stuck, like waiting for the end of instructions. Killing the task (Ctrl + C) will release the console and K3s keeps running normally. Picture below.

![2020-06-27 00_04_02-root@appliance-001_~](https://user-images.githubusercontent.com/9057896/85913288-c22a7400-b809-11ea-981d-c42f1c2d9657.png)

**To Reproduce**
Any install with --log flag enabled

**Expected behavior**
Command finish clear and release console.

**Actual behavior**
Command keeps stuck and won't release console.

**Additional context / logs**
SO: CentOS 7
I don't know exactly where to find relevant logs for this. I've tried removing the dot from the path with no luck, and also compared the systemd file (/etc/systemd/system/k3s.service) on both installs with and withou flag. Nothing that seems wrong.

**Comment by brandond** [comment]
Closing in favor of #2277
