### ISSUE TITLE
Servicelb uses a DaemonSet and only supports one LoadBalancer per port

### ISSUE THREAD

**Issue by nhinds** [k3s-io/k3s#1969]
**Version:**

    k3s version v1.18.4+k3s1 (97b7a0e9)

**K3s arguments:**

    k3s server --no-deploy traefik --tls-san 0.0.0.0

**Describe the bug**
LoadBalancer services handled by the Service Load Balancer grab that service's port on all nodes using a `DaemonSet`. This means that if e.g. two services want to listen on port 80, only one of them will succeed.

**To Reproduce**
Deploy a k3s cluster with e.g. 8 nodes, without Traefik:

    $ k3d create cluster CLUSTERNAME --workers 8 --k3s-server-arg --no-deploy --k3s-server-arg traefik

Create a `Service` for port `80` and wait for it to have an external IP and for all pods to be running:
```
$ kubectl create service loadbalancer first --tcp=80
$ kubectl get svc first
NAME    TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
first   LoadBalancer   10.43.136.13   172.31.0.4    80:31633/TCP   7s
$ kubectl get pods
NAME                READY   STATUS    RESTARTS   AGE
svclb-first-8qrjn   1/1     Running   0          14s
svclb-first-bv2n9   1/1     Running   0          14s
svclb-first-22q64   1/1     Running   0          14s
svclb-first-zvbqp   1/1     Running   0          14s
svclb-first-xxbzm   1/1     Running   0          14s
svclb-first-24bc2   1/1     Running   0          14s
svclb-first-2cd4n   1/1     Running   0          14s
svclb-first-l7ss5   1/1     Running   0          14s
svclb-first-l5h8w   1/1     Running   0          14s
```
Create another service for port `80`
```
$ kubectl create service loadbalancer second --tcp=80
service/second created
$ kubectl get svc second
NAME     TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
second   LoadBalancer   10.43.90.178   <pending>     80:30671/TCP   3m22s
$ kubectl get pods -l app=svclb-second
NAME                 READY   STATUS    RESTARTS   AGE
svclb-second-mqs5q   0/1     Pending   0          3m42s
svclb-second-p8b2t   0/1     Pending   0          3m42s
svclb-second-cg5ql   0/1     Pending   0          3m42s
svclb-second-7bz5c   0/1     Pending   0          3m42s
svclb-second-txplr   0/1     Pending   0          3m42s
svclb-second-xtxsp   0/1     Pending   0          3m42s
svclb-second-8chf7   0/1     Pending   0          3m42s
svclb-second-6qmrw   0/1     Pending   0          3m42s
svclb-second-wtlw5   0/1     Pending   0          3m42s
```

**Expected behavior**
Given enough worker nodes to run the loadbalancer pods, it should be possible to run two `LoadBalancer` services listening on the same port.

**Actual behavior**
The second service never gets an external IP, and its pods can never be scheduled, because the first service has used a `DaemonSet` to deploy pods on every node in the cluster.  All `svclb-second-*` fail scheduling with "0/9 nodes are available: 9 node(s) didn't have free ports for the requested pod ports."

It is possible to race the two daemonsets against each other by repeatedly running `kubectl delete pod --all`. If you do this enough times, some of the pods from the second service will win the scheduling race and both loadbalancers will come up with external IPs, although both daemonsets will still have pods stuck in the "Pending" state.

**Additional context / logs**
The [Service Load Balancer documentation](https://rancher.com/docs/k3s/latest/en/networking/?query=servicelb#service-load-balancer) seems to imply that it's possible to run multiple load balancers, and they will find a node with a free port to be scheduled on:
> If you try to create a load balancer that listens on port 80, for example, it will try to find a free host in the cluster for port 80. If no port is available, the load balancer will stay in Pending.

It seems like that was true at some point in the past, when servicelb used a `Deployment` instead of a `DaemonSet`, but the usage of a `DaemonSet` means that a single service claims its ports on all hosts in the cluster, not just one or two free hosts in the cluster.

Would it be possible to switch back to using a `Deployment`? It was switched in #375 when adding a node selector, but I was unable to find a reason for the LB to claim ports on all hosts with a `DaemonSet` (rather than e.g. specifying the `nodeSelector` on the existing `Deployment`). If that's not possible, could it be called out in the documentation that you can only have one loadbalancer service per port, rather than finding a free host in the cluster?

As an aside, if you don't disable Traefik when deploying k3s, it claims ports 80 and 443 on all hosts and no other services can use them - i.e. it becomes the "first" service in the reproduction steps above.

**Comment by predakanga** [comment]
Another bit of strangeness from this bug - the Service object only shows one IP under EXTERNAL-IP (status.loadBalancer.ingress.ip on the API object)

**Comment by Platou** [comment]
@nhinds Any updates on this? On why to use a DeamonSet instead of Deployment? I try to understand why a loadbalancer service should lock the specified port on all nodes of the cluster...

**Comment by nhinds** [comment]
I have not heard any updates to this, no. To my knowledge this has not been fixed, and nobody has clarified why a DaemonSet is used.

**Comment by brandond** [comment]
ServiceLB is a very basic stub service controller that is `just enough` to get services with type=LoadBalancer up and running without requiring any additional configuration. You are not required to use it, and it is very easy to turn off. Most use cases that go beyond standing up a small cluster to serve a single workload will immediately replace it with MetalLB, kube-vip, or a cloud provider's LB service.

**Comment by praveenmak** [comment]
I created a K3s cluster with all default settings.
3 master nodes (with embedded etcd).
3 worker nodes.
No additional settings i.e. traefik is not disabled.

All the servicelb-traefik are in pending state.  They are not scheduled because "traefik" service is using port 80 and 443.

I would expect default setting to work without any changes. Correct?

**Comment by brandond** [comment]
The Traefik service does not bind to host ports, that's what the svclb pods are for. Do you have something else on your nodes that's using port 80 and 443?  What do you see if you describe the pending pods?

**Comment by praveenmak** [comment]
@brandond  I moved away from Traefik.  I disabled it and used Metallb. No issues.

Since you are asking for error description. The Pods were in pending state because port 80 was occupied.  No, nothing was running in those. It was deployed from scratch using Terraform.

Pretty easy to replicate,  3 master, 3 workers. And another important thing is I am using Cloud providers LoadBalancer (Openstack).

**Comment by brandond** [comment]
Traefik is an ingress controller not a loadbalancer. If you're using metallb you would want to disable servicelb.

**Comment by praveenmak** [comment]
I get that part. I disabled both Traefik and KlipperLB. 

The thing that fixed me was this.
**--disable traefik --disable servicelb** and **not** using cloud provider LB.

Default settings in HA mode has this issue.

**Comment by brandond** [comment]
Maybe it did a while ago, but it has supported multiple ports for a while, and as of recent releases, adds IP addresses for all nodes.

**Comment by ShylajaDevadiga** [comment]
Validated as per the steps in verification.
1. Labeled all nodes ```svccontroller.k3s.cattle.io/enablelb=true```
2. Labeled two nodes  ```svccontroller.k3s.cattle.io/lbpool=pool_1```
3. Labeled other two nodes ```svccontroller.k3s.cattle.io/lbpool=pool_2```
4. Created service loadbalancer with **svccontroller.k3s.cattle.io/lbpool=pool_1** and another service loadbalancer with **svccontroller.k3s.cattle.io/lbpool=pool_2**
```
$ kubectl get nodes --show-labels
NAME              STATUS   ROLES                  AGE   VERSION            LABELS
ip-172-31-11-86   Ready    <none>                 15h   v1.23.5-rc1+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-11-86,kubernetes.io/os=linux,node.kubernetes.io/instance-type=k3s,svccontroller.k3s.cattle.io/enablelb=true,svccontroller.k3s.cattle.io/lbpool=pool_2
ip-172-31-3-145   Ready    <none>                 15h   v1.23.5-rc1+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-3-145,kubernetes.io/os=linux,node.kubernetes.io/instance-type=k3s,svccontroller.k3s.cattle.io/enablelb=true,svccontroller.k3s.cattle.io/lbpool=pool_2
ip-172-31-15-88   Ready    control-plane,master   15h   v1.23.5-rc1+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-15-88,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/master=true,node.kubernetes.io/instance-type=k3s,svccontroller.k3s.cattle.io/enablelb=true,svccontroller.k3s.cattle.io/lbpool=pool_1
ip-172-31-6-139   Ready    <none>                 15h   v1.23.5-rc1+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-6-139,kubernetes.io/os=linux,node.kubernetes.io/instance-type=k3s,svccontroller.k3s.cattle.io/enablelb=true,svccontroller.k3s.cattle.io/lbpool=pool_1
ubuntu@ip-172-31-15-88:~$
```
Verified service lb is created matching the label on the node
```ubuntu@ip-172-31-15-88:~$ kubectl get svc
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP                 PORT(S)                      AGE
kubernetes                ClusterIP      10.43.0.1       <none>                      443/TCP                      15h
nginx-loadbalancer-svc2   LoadBalancer   10.43.202.18    172.31.11.86,172.31.3.145   82:31304/TCP,445:30743/TCP   81s
nginx-loadbalancer-svc    LoadBalancer   10.43.137.148   172.31.15.88,172.31.6.139   81:31965/TCP,444:30586/TCP   93s
```
Daemonset is created in all the nodes while the service is accessible on designated node
```
ubuntu@ip-172-31-15-88:~$ kubectl get pods -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
test-loadbalancer-nvgtm               1/1     Running   0          99s   10.42.3.20   ip-172-31-11-86   <none>           <none>
test-loadbalancer-6ztw8               1/1     Running   0          99s   10.42.1.22   ip-172-31-6-139   <none>           <none>
test-loadbalancer-gtz58               1/1     Running   0          99s   10.42.2.20   ip-172-31-3-145   <none>           <none>
test-loadbalancer-tr8wm               1/1     Running   0          99s   10.42.0.28   ip-172-31-15-88   <none>           <none>
test-loadbalancer2-h9xjh              1/1     Running   0          87s   10.42.1.23   ip-172-31-6-139   <none>           <none>
svclb-nginx-loadbalancer-svc2-lnb64   2/2     Running   0          87s   10.42.3.21   ip-172-31-11-86   <none>           <none>
test-loadbalancer2-nxb64              1/1     Running   0          87s   10.42.3.22   ip-172-31-11-86   <none>           <none>
svclb-nginx-loadbalancer-svc2-stt5p   2/2     Running   0          87s   10.42.2.21   ip-172-31-3-145   <none>           <none>
test-loadbalancer2-x7n84              1/1     Running   0          87s   10.42.2.22   ip-172-31-3-145   <none>           <none>
test-loadbalancer2-zmxft              1/1     Running   0          87s   10.42.0.29   ip-172-31-15-88   <none>           <none>
svclb-nginx-loadbalancer-svc-7nscf    2/2     Running   0          15s   10.42.0.30   ip-172-31-15-88   <none>           <none>
svclb-nginx-loadbalancer-svc-x68g8    2/2     Running   0          13s   10.42.1.24   ip-172-31-6-139   <none>           <none>
ubuntu@ip-172-31-15-88:~$
```
```
ubuntu@ip-172-31-15-88:~$ curl http://172.31.11.86:82
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>

ubuntu@ip-172-31-15-88:~$ curl http://172.31.11.86:81
curl: (7) Failed to connect to 172.31.11.86 port 81: Connection refused

ubuntu@ip-172-31-15-88:~$ curl http://172.31.15.88:81
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>

ubuntu@ip-172-31-15-88:~$ curl http://172.31.15.88:82
curl: (7) Failed to connect to 172.31.15.88 port 82: Connection refused
```
