### ISSUE TITLE
How can I use local docker image for creating pod in k8s

### ISSUE THREAD

**Issue by mehdihadeli** [k3s-io/k3s#1970]
Hi,
I want to create a pod from my local image with kubectl in my k3s cluster. I set `imagePullPolicy`  to never but after that my pod will be going to `ErrImageNeverPull` state. what can I do for this issue?

**Comment by photoszzt** [comment]
I encounter the same problem too. Would love to get an answer to this question.

**Comment by photoszzt** [comment]
After switch to docker version, it work.

**Comment by Arvintian** [comment]
If you use container runtime with containerd you can't use local image (docker image) to start pods, so switch to docker, it work. @photoszzt

**Comment by brandond** [comment]
Tools to do this with the default containerd backend are coming. For the moment, it's easiest to do this by switching to the docker backend.

**Comment by cickes** [comment]
> After switch to docker version, it work.

Can you please share the commands used to make this work?  What do you mean "switch to docker version"?

**Comment by brandond** [comment]
@cickes https://rancher.com/docs/k3s/latest/en/advanced/#using-docker-as-the-container-runtime

**Comment by KeoYang** [comment]
KIND create cluster ...
`kind create cluster --name test`
when i  
`kubectl load docker-image YOU-LOCAL-DOCKER_IMAGE --name test`
then
`docker exec it <cluster-node-name> crictl images`, you will find your local image had loaded in one node of kind cluster
then
`imagePullPolicy: IfNotPresent` 
`kubectl create -f YOU-CONFIG.YAML -n test`
suc

**Comment by brandond** [comment]
kind is not k3s.
