### ISSUE TITLE
Manifests deleted in the manifest path are not removed from the cluster

### ISSUE THREAD

**Issue by johscheuer** [k3s-io/k3s#1971]
**Version:**
```bash
$ k3s -v
k3s version v1.18.4+k3s1 (97b7a0e9)
```

**K3s arguments:**
I started k3s with the following command (no flags): `sudo bash -c 'k3s server &>> /var/log/k3s/k3s.log' &`

**Describe the bug**
I tried out some settings with k3s and I wanted to deploy a sample application with the [manifest](https://rancher.com/docs/k3s/latest/en/architecture/#automatically-deployed-manifests) approach. The application is a simple go application (with redis) and can be found here: https://github.com/johscheuer/todo-app-web.git. When I tried to remove the application I just the deleted the subfolder in the manifests folder and noticed that k3s doesn't cleanup. I waited ~30min and the application was still there (and no errors in the log file). I don't know if this behaviour is intended but I couldn't find some documentation that specifies this behaviour.

**To Reproduce**

Install the app over the manifest path:

```bash
git clone https://github.com/johscheuer/todo-app-web.git
sudo mkdir -p /var/lib/rancher/k3s/server/manifests/todo-app
sudo ln -s $(pwd)/todo-app-web/k8s-deployment/* /var/lib/rancher/k3s/server/manifests/todo-app
```

Wait until everything has started and now delete the folder:

```bash
sudo rm -r /var/lib/rancher/k3s/server/manifests/todo-app
```

and the app will never be deleted.

**Expected behavior**
I would expect that the application (or actually all manifests in this folder) are removed from k3s if I remove the folder. 

**Actual behavior**
The resources will still be there if you just delete the according folder (e.g. in the example above `/var/lib/rancher/k3s/server/manifests/todo-app`) and you need to manually delete the resources.

**Additional context / logs**

```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```bash
$ uname -a
Linux ubuntu-focal 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

If you want I can also provide some logs but there is nothing special (at least with the default log level).
I also tried this with a single manifest file: `sudo mv /var/lib/rancher/k3s/server/manifests/coredns.yaml .` with the same result.
If this behaviour is expected it should be documented (e.g. here: https://rancher.com/docs/k3s/latest/en/helm/#deploying-manifests-and-helm-charts)

**Comment by brandond** [comment]
Yes, you can add or change things by managing manifests in that directory. If you want to delete things entirely, you need to both delete the file, and delete the corresponding AddOn custom resource from the kube-system namespace.

**Comment by johscheuer** [comment]
Is this somewhere documented? If not, we should adjust the docs.

**Comment by brandond** [comment]
The whole thing feels a bit magic at the moment. Works best if you treat it as a black box for deploying the built-in components at the moment, much beyond that and you run into issues with visibility (no events, no metrics) and lack of documentation.

**Comment by pdf** [comment]
This mechanism is primarily targeted at deploying supplementary cluster components, rather than general workloads. There's no sane way to have this remove resources on deletion of a file (the file is what defines the resources), just use `kubectl`/`helm`/whatever to manage your workloads per the standard Kubernetes workflow.

**Comment by 205g0** [comment]
> Is this somewhere documented? If not, we should adjust the docs.

It's not[1] and it created some confusion. The docs call this auto-deploying manifests but don't tell that removal doesn't do anything. Once you know all good but until then you waste some time. I did a PR, pls review, change and/or approve

[1] https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests

**Comment by hickersonj** [comment]
Couldn't the chart/yaml file that defines the resources be staged and when removed a similar method of `kubectl delete -f` be applied to the staged file? After which remove the staged file. If k0s is doing it they must be keeping that info somewhere.

**Comment by brandond** [comment]
What happens if you delete the file on one server but not on the other? Should one server `kubectl delete -f` it, and then other one put it back?

**Comment by hickersonj** [comment]
> What happens if you delete the file on one server but not on the other? Should one server `kubectl delete -f` it, and then other one put it back?

Perhaps you have a policy configured that performs manifest synchronization and states: "Synchronize servers based on manifest changes.  I.e. if you remove a manifest on one server, the other(s) will also remove the manifest." 

This also might just be the default behavior and is not configurable.

**Comment by brandond** [comment]
We have not historically been interested in tackling the complexity required to support that. The manifests are best used to deploy stuff at the time of initial installation, or perhaps for very simple automation on a single-node system. Beyond that, once you start looking for more advanced features, you probably want to look at proper gitops tooling.

**Comment by hickersonj** [comment]
> We have not historically been interested in tackling the complexity required to support that. The manifests are best used to deploy stuff at the time of initial installation, or perhaps for very simple automation on a single-node system. Beyond that, once you start looking for more advanced features, you probably want to look at proper gitops tooling.

I see, I didn't want to reinvent the wheel since programmatically doing this is not as straightforward. So far I don't see go bindings for apply, delete etc to ingest yaml charts (I was able to do so for Deployment kinds, but not CRD etc).  I figured if k3s is already doing that, a simple link to the manifest folder, which conveniently uses fnotify, would be suitable. 

I hadn't thought about multi-node systems, I can see where the complexity increases considerably in that arena.

**Comment by LolHens** [comment]
Might be a bit off topic for this issue but I was always a bit concerned about what happens if I have different versions on multi-node clusters. If I want to modify a manifest do I have to modify the manifests on each node? Do the nodes start to fight over the different versions?

**Comment by brandond** [comment]
Yes, if you're deploying manifests to multiple node it is up to the operator to either pick a single node that is responsible for deploying them, or keep them in sync across all nodes.
