### ISSUE TITLE
ServerAddresses of the controller not changed after IP change due to network changes

### ISSUE THREAD

**Issue by nvtkaszpir** [k3s-io/k3s#1977]
controller  == k3s server (or master)
worker == k3s node worker ( or plain node)

**Environmental Info:**
K3s Version: 
controller:  `v1.17.4+k3s1`
nodes: ` v1.17.4+k3s1` and `v1.18.4+k3s1`

Node(s) CPU architecture, OS, and Version: 
```
Linux test-k3s-node 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 controller, 3 different workers nodes

**Describe the bug:**
Running controller on the laptop with ethernet card and wifi, thus IP address can float depending on the state of the interfaces which were on and their priorities.
Looks like k3s controller takes it's `ServerAddresses` only on service start.

**Steps To Reproduce:**
Prepare three hosts (can be virtual), one for controller, another two for worker.

- Create controller on multi-homed host which are not bonded (and so on, just plain dumb interfaces, can be virtual), let's say it has 2 interfaces eth0 and eth1 with DHCP enabled.
- On controller - connect network to eth0, leave eth0 disconnected.
- On controller - start k3s.service.
- From another host - add it as new worker node to the k3s (or just check the k3s master IP reported via `kubect nodes -o wide`).
- On controller - disconnect cable from eth0 and connect it to eth1, so that IP address should change to different one.
- On controller - check the k3s master IP again, it should show old IP address.
- On another node - try to add new node via hostname (may need to add it to /etc/hosts)  - this node will actually obtain config from the master but the config on the node will show ServerAddresses to point to old IP of the master. So this node will not be able to finalize registration to the master.
- On master - notice that previously registered node will report it is not ready.
- On controller - restart k3s.service, it should pick up correct IP address and update itself.
- See the failing node again, after a while it should successfully register to the master. Also notice that previously registered node reconnects back and is ready.

**Expected behavior:**
k3s master should be aware of the IP changes it is using. 

**Actual behavior:**
k3s master keeps old IP address.

**Additional context / logs:**
on the new node:
```
Jun 30 18:33:30 test-k3s-node k3s[863]: time="2020-06-30T18:33:30.812867696Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:35 test-k3s-node k3s[863]: time="2020-06-30T18:33:35.813288958Z" level=info msg="Connecting to proxy" url="wss://192.168.1.236:6443/v1-k3s/connect"
Jun 30 18:33:38 test-k3s-node k3s[863]: time="2020-06-30T18:33:38.876887374Z" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:38 test-k3s-node k3s[863]: time="2020-06-30T18:33:38.876971005Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:43 test-k3s-node k3s[863]: time="2020-06-30T18:33:43.877304370Z" level=info msg="Connecting to proxy" url="wss://192.168.1.236:6443/v1-k3s/connect"
Jun 30 18:33:46 test-k3s-node k3s[863]: time="2020-06-30T18:33:46.940672879Z" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:46 test-k3s-node k3s[863]: time="2020-06-30T18:33:46.940768055Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:51 test-k3s-node k3s[863]: time="2020-06-30T18:33:51.941191924Z" level=info msg="Connecting to proxy" url="wss://192.168.1.236:6443/v1-k3s/connect"
Jun 30 18:33:55 test-k3s-node k3s[863]: time="2020-06-30T18:33:55.004890677Z" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.1.236:6443: connect: no route to host"
Jun 30 18:33:55 test-k3s-node k3s[863]: time="2020-06-30T18:33:55.004969927Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.1.236:6443: connect: no route to host"
```

Status of the hosts before and after service restart on master:
```
20:41:28 kaszpir@misiek ~/src/k3s  $ kubectl get nodes -o wide
NAME     STATUS     ROLES    AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
hormes   NotReady   <none>   115d   v1.17.4+k3s1   192.168.1.21    <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7+        containerd://1.3.3-k3s2
misiek   Ready      master   115d   v1.17.4+k3s1   192.168.1.236   <none>        Ubuntu 18.04.4 LTS               5.4.0-39-generic   containerd://1.3.3-k3s2

20:41:29 kaszpir@misiek ~/src/k3s  $ kubectl get nodes -o wide
NAME            STATUS   ROLES    AGE     VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
hormes          Ready    <none>   115d    v1.17.4+k3s1   192.168.1.21    <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7+        containerd://1.3.3-k3s2
test-k3s-node   Ready    <none>   3m52s   v1.18.4+k3s1   192.168.1.178   <none>        Ubuntu 18.04.4 LTS               5.3.0-61-generic   containerd://1.3.3-k3s2
misiek          Ready    master   115d    v1.17.4+k3s1   192.168.1.125   <none>        Ubuntu 18.04.4 LTS               5.4.0-39-generic   containerd://1.3.3-k3s2
```

**Possible fix**
If using systemd register service restart on IP address change.

**Comment by brandond** [comment]
kubernetes has some core assumptions built into it, one of them is that nodes in the cluster will not randomly change IP addresses or have control plane interfaces go up and down. You might find that it's more work than it's worth to get this working as you expect.

**Comment by nvtkaszpir** [comment]
You know you cannot prevent this in real life?

**Comment by brandond** [comment]
I can say that in the last 20 years I have never worked in an environment where it was expected for servers to change IP addresses at random or unexpected times. Clients, sure, but servers are generally expected to stay in one place. Clients may get directed to multiple servers with different addresses, but a single server should not be moving around on the network.

**Comment by nvtkaszpir** [comment]
Well, lucky you, then :)
I've seen it at least 10 times, especially in the cloud environments.

If anyone interested currently using systemd-networkd which triggers networkd-disparcher , which runs script placed in /etc/networkd-dispatcher/routable.d/ just to restart k3s service is sufficient.

More details under https://unix.stackexchange.com/questions/469716/systemd-networkd-run-script-after-dhcp-client-aqcuires-new-address

I believe at least mentioning in the docs would be sufficient.

**Comment by brandond** [comment]
I don't believe that AWS/GCP/Azure will change the primary IP on a running node either. It can get reassigned if you stop/start the instance, and you can add/remove secondary addresses and interfaces at runtime, but that's about it. Maybe some of the other providers are less strict about it?

**Comment by nvtkaszpir** [comment]
Yes, some other providers are less strict about it - that is, they REALLY emphasize the word 'Dynamic' in 'DHCP'.

I believe we can stop further discussion because the issue is really specific corner case - yet still quite valid in the world of DHCP.
I see two options:
- propose short update to the docs for those seeking the solution for the issue (I bet we can count them on the fingers of the single hand)
- do nothing, and let them exercise searching function over github so that they would find proposed solution in the comments of this issue :)

Feel free to ask me for PR with a little guidance where to update docs, otherwise just close the issue and we're done - I know there are more important things to be done in the project.
