### ISSUE TITLE
PostgreSQL: Stop using public schema

### ISSUE THREAD

**Issue by toonsevrin** [k3s-io/k3s#1987]
This may not be relevant for a lot of people, but by default k3s/kine creates it's tables under the `public` schema. As you may or may not know, [any user in the database can thus access this data by default](https://dba.stackexchange.com/a/156607).

As k3s is mainly for small clusters, I doubt users care about this level of isolation, but in my case I definitely do :laughing:.

Is it possible to specify another schema then `public` with the postgresql endpoint?

Thanks a lot!!!

**Comment by toonsevrin** [comment]
I'd like to clarify that running the following sequency during database bootstrapping does solve this problem. But it would be nice to be able to enforce this from the consumer side (if this sql is not ran for any reason, the public schema is used again). 
```sql
CREATE SCHEMA k3s;
ALTER DATABASE db SET search_path to k3s;
```

**Comment by fapatel1** [comment]
Looks like this was resolved from the PR above (https://github.com/k3s-io/kine/issues/40)

**Comment by brandond** [comment]
That's an issue, not a PR. Nothing has been changed to allow this.
