### ISSUE TITLE
k3s install script failure

### ISSUE THREAD

**Issue by chensheng0** [k3s-io/k3s#1992]
first thanks your work, k3s is excellent

recently i am using k3s script to install it in China, but failed

curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -

and crashed Downloading https://mirror-k3s.rancher.cn/download/v1.18.4-k3s1/sha256sum-arm64.txt
 
![image](https://user-images.githubusercontent.com/49777677/86466473-46c74600-bd66-11ea-822a-ed53e3629a57.png)

![image](https://user-images.githubusercontent.com/49777677/86466534-5f376080-bd66-11ea-90ac-f7b1f8854da2.png)

thanks for helping me

**Comment by hellozhe** [comment]
me too

**Comment by chiyanking** [comment]
me too

**Comment by johnwong369** [comment]
1、先下载离线安装包。
2、部署镜像：

```sh
sudo mkdir -p /var/lib/rancher/k3s/agent/images/
sudo cp ./k3s-airgap-images-$ARCH.tar /var/lib/rancher/k3s/agent/images/
```

 Place the k3s binary at /usr/local/bin/k3s and ensure it is executable. 

单机部署

在server端执行：

```
INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh
```

worker节点执行：

```
INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken ./install.sh
```

 Take care to ensure you replace `myserver` with the IP or valid DNS of the server and replace `mynodetoken` with the node token from the server typically at `/var/lib/rancher/k3s/server/node-token`

**Comment by xiaoluhong** [comment]
In the early days, mirror was synchronized once a day. It has now been changed to synchronize every hour.
