### ISSUE TITLE
Please don't use sticky nav headers

### ISSUE THREAD

**Issue by brandonkal** [k3s-io/k3s#1993]
The doc site is unusable because of it.

Example URL:
https://rancher.com/docs/k3s/latest/en/installation/network-options/

As an excersize, try reading the table on mobile. No horizontal scrolling and the header takes away valuable screen space. In landscape, three lines of text are visible. The rest is obscured by that nav bar.

**Comment by brandond** [comment]
I believe this belongs in https://github.com/rancher/docs
