### ISSUE TITLE
Control Plane LoadBalancer

### ISSUE THREAD

**Issue by schmitch** [k3s-io/k3s#2031]
**Describe the solution you'd like**
actually when running in k3s ha mode with an external database one still needs to have a "Configure the Fixed Registration Address" this could be overcome with a built-in `kube-vip` (https://github.com/plunder-app/kube-vip), however that would mean that some needs to provide a VIP, but I think that might be the lower evil

btw. even kubeadm now introduces `kube-vip`: https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#kube-vip
and it's also possible to use it directly with it:
https://kube-vip.io/control-plane/#first-node

**Describe alternatives you've considered**
keep k3s as it is, however that would mean that it would still be a hassle in a ha scenario (it still is since etcd is not built into it).

**Comment by brandond** [comment]
Another simple thing to do would be to just use a DNS alias maintained by ExternalDNS or something.

**Comment by nustiueudinastea** [comment]
It would be great if the Kubelet would be made multi-master aware, so that a load balancer wouldn't be needed for HA setups.

**Comment by brandond** [comment]
@nustiueudinastea the apiserver is already multi-master. The issue is that clients need to be given a fixed address in order to do the initial bootstrapping. This can be a loadbalancer, dns alias, or just the address of one of the servers.

**Comment by schmitch** [comment]
@brandond sadly I did not answer directly but unfortunatly a dns alias is most often not possible especially not in the IoT world.
So I think it would be good to include something that is as simple as saying `--master-loadbalancer-ip=` if not specified k3s does not configure a ha ip or use the code at all.

**Comment by xiaods** [comment]
@schmitch you can manually setup kube-vip with k3s server cluster. if it satisfies your environment, please feedback. Currently, this is not high priority request for the use cases.

**Comment by nustiueudinastea** [comment]
Why not accept a list of IPs representing all the available masters?

**Comment by xiaods** [comment]
> Why not accept a list of IPs representing all the available masters?

this also needs some extra code to filter an IP to interact with the agent. if the master gets down or add more master nodes, we also need to update the IPS in your ways.

**Comment by nustiueudinastea** [comment]
Indeed, this is more complicated and thats what I meant when I suggested multi-master support in the kubelet. While it would add some complexity in the implementation, it would also make k3s operationally less complex in HA environments and much easier to setup. An LB is often not available in self-hosted or IoT environments.

**Comment by xiaods** [comment]
> Indeed, this is more complicated and thats what I meant when I suggested multi-master support in the kubelet. While it would add some complexity in the implementation, it would also make k3s operationally less complex in HA environments and much easier to setup. An LB is often not available in self-hosted or IoT environments.

for ipvs support node, we can use ipvs to create a vs in local node, add host alias to this vs name. it also get rid of this control plan issue.

**Comment by brandond** [comment]
Note that k3s only needs a stable registration endpoint for the initial startup of the agent. After that it uses a client load balancer to route connections between available servers.

**Comment by xiaods** [comment]
@brandond thanks for your reminder. so k3s don't need to add more components to handle the ha logic.

**Comment by schmitch** [comment]
yeah this can be closed of now, I do not think that many IoT devices need a highly available registration ip. It might need to be documented tough.

**Comment by schmitch** [comment]
actually when thinking about it, it might still make sense to provide that. so that services like clilium can work without kube-proxy: https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/ (this needs high available api server)
