### ISSUE TITLE
[QUESTION] i386 support for k3s

### ISSUE THREAD

**Issue by laurids-reichardt** [k3s-io/k3s#2075]
Given that k3s supports 32-bit ARM I'm wondering what it would take to build k3s for i386?

Thanks for your work on this great project!

**Comment by brandond** [comment]
I think the largest problem with this would be that while arm is just now going from 32bit to 64bit, x86 is going the other way. RHEL/CentOS 7 and Ubuntu 18.04 (and newer) are only available 64-bit. Alpine (which is where we build and link against) is only available 64-bit. While there are projects like i386/alpine, I'm not sure how well supported they are.

Is there a particular use case you're looking at where you are restricted to running on i686?

**Comment by laurids-reichardt** [comment]
Hi @brandond! Thanks for your reply.

This is in all likelihood a ridiculous request but I'm trying to get k3s running in Fabrice Bellard's x86 [JSLinux](https://bellard.org/jslinux/). Please don't ask me why. I don't have an answer but the curiosity whether it is in theory possible is killing me.

On my machine JSLinux runs at somewhere around 1% of native performance, which might be enough to proof that k3s can in fact run completely local inside the browser.

I'm therefore not asking you to officially support i386 going forward, but would be interested to know how a one-time i386 build of k3s could be done. Do you have some ideas what I should look at?

**Comment by brandond** [comment]
You could start by grepping through the source code for anywhere that arm64 is mentioned and see about duplicating that logic for i386. You would probably have to build i386 versions of all the airgaps images, since a cluster that can't run anything isn't worth much. This also assumes that you can get docker and containerd working on i386.

**Comment by briandowns** [comment]
If you download Ubuntu 16, install the i686 Linux build of Go, you can compile k3s to complettion. I'd suggest installing all dependencies first like sqllite, libsqlite-dev, etc, and giving it plenty of RAM as the OOM killer will do what it does best if not. The other caveat after this point is CNI. I didn't get that far but wanted to at least test if it was possible.

**Comment by brandond** [comment]
It looks like jslinux actually implements something closer to i686 than i386/i387 so as @briandowns mentioned it shouldn't be too hard to get it to build on an older distro. Let us know what you find out!

**Comment by briandowns** [comment]
One small caveat is the calico stuff I found. A lot of that needs to be built manually instead of their build process. I got nearly everything working aside from a `host-local` binary being present preventing the kubelet process from starting.

**Comment by laurids-reichardt** [comment]
@brandond yeah, that makes sense.

@briandowns does that mean you complied k3s on 32-bit Ubuntu 16 via the build commands described in the documentation?
```bash
./scripts/download && ./scripts/build && ./scripts/package-cli
```
Could you share your progress in some form? Maybe a repo fork?

Many thanks to the both of you for looking into it!

**Comment by briandowns** [comment]
I ran `go build -v` to avoid anything else since Go itself will target 32-bit linux.

**Comment by laurids-reichardt** [comment]
Ah, I see. So this does not yet include containerd for example?

**Comment by briandowns** [comment]
This is as far as I've gotten:

As root.

```sh
sudo apt-get update
sudo apt-get install make git gcc jq
apt-get install build-essential ca-certificates
curl https://golang.org/dl/go1.14.6.linux-386.tar.gz --output go1.14.6.linux-386.tar.gz
curl -L https://golang.org/dl/go1.14.6.linux-386.tar.gz --output go1.14.6.linux-386.tar.gz
tar -C /usr/local -xzf go1.14.6.linux-386.tar.gz
```

Add `/usr/local/go/bin` to your path. 

```sh
mkdir -p ~/go/src/github.com/rancher ~/go/bin ~/go/pkg
cd github.com/rancher/
git clone https://github.com/rancher/k3s.git
cd k3s/
```

Next...

```sh
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=i686] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get install sqlite libsqlite-dev docker.io linux-headers-$(uname -r) musl musl-dev
swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
```

And then...

```sh
mkdir -p ~/go/src/github.com/containernetworking
cd ~/go/src/github.com/containernetworking
git clone https://github.com/containernetworking/cni.git
cd cni
go install github.com/containernetworking/cni/cnitool
go build -v ./...
```

5 minutes later...

```sh
sysctl net.bridge.bridge-nf-call-iptables=1
mkdir ~/go/src/github.com/projectcalico
cd ~/go/src/github.com/projectcalico
git clone https://github.com/projectcalico/calicoctl.git
cd calicoctl/
go build -v -o bin/calicoctl -ldflags "-X github.com/projectcalico/calicoctl/calicoctl/commands.VERSION=$(git rev-parse --short HEAD) -X github.com/projectcalico/calicoctl/calicoctl/commands.GIT_REVISION=$(git rev-parse --short HEAD) -s -w" "./calicoctl/calicoctl.go"
cp bin/calicoctl /usr/local/bin/
cd ../
git clone --depth=1 https://github.com/projectcalico/cni-plugin.git
cd cni-plugin/
go build -v -o bin/calico -ldflags "-X main.VERSION=$(git rev-parse --short HEAD) -s -w" ./cmd/calico
```

```sh
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
cd ~/go/src/github.com/rancher/k3s
go build -v .
```

At the end of this, you'll have a `k3s` binary that is executable and will run however you'll see in the logs that it's still missing the `host-local` binary which prevents kublet from starting. I stopped there.

I hope this helps.
