### ISSUE TITLE
where to define the kubeconfig context name?

### ISSUE THREAD

**Issue by ozbillwang** [k3s-io/k3s#2081]
I used the docker-compose file (https://github.com/rancher/k3s/blob/master/docker-compose.yml) to create k3s, but I found the context name is set to `default`, which is not easily to identify it out to other contexts I installed before. 

Are there any ways to define the context name easily?
```
cat kubeconfig.yaml
...
  name: default
```

**Comment by brandond** [comment]
That doesn't exist or matter anywhere except in the config file. Feel free to change it.
