### ISSUE TITLE
Rancher Server not accessible with K3s version v1.17.7+k3s1

### ISSUE THREAD

**Issue by talha22081992** [k3s-io/k3s#2091]
**Environmental Info:**
K3s Version: 
k3s version v1.17.7+k3s1 (b0260b33)

Node(s) CPU architecture, OS, and Version: 
Linux ip-172-31-12-253 5.3.0-1023-aws #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node cluster

**Describe the bug:**
Rancher does not work on the instance (having the k3s version v1.17.7+k3s1 installed). The UI gives "404 page not found"

**Steps To Reproduce:**
- Installed K3s: 
k3sup install --ip=18.222.161.92 user=root --k3s-version=v1.17.7+k3s1
-Installed Docker:
Docker version 19.03.12, build 48a66213fe
-Installed Rancher:
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:v2.4.5

**Expected behavior:**
Rancher should work, UI should should be accessible to add the cluster

**Actual behavior:**
On accessing the Rancher Server, it gives "404 page not found"

**Comment by brandond** [comment]
Are you trying to run both k3s with the containerd backend, and Docker, with Rancher in Docker, on the same host? Why aren't you installing Rancher into k3s?
