### ISSUE TITLE
Lightweight Moniting And Logging In K3s

### ISSUE THREAD

**Issue by liyongxian** [k3s-io/k3s#2107]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
Elasticsearch And Prometheus are used in K3s,but they need much more resources.In Edge,we can not stand on it.We hope there are lightweight "Elasticsearch " and "Prometheus ".Thanks.

**Comment by samirsss** [comment]
+1 to this. I've been looking at options different from elasticsearch with metricbeats which is much more lightweight to get this done.

**Comment by nustiueudinastea** [comment]
vector + loki or promtail + loki might be a good option for log aggregation.
