### ISSUE TITLE
staged binary location to enable upgrading

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#2110]
**Is your feature request related to a problem? Please describe.**
Upgrading a running `k3s` node as currently implemented by the [rancher/k3s-upgrade](https://github.com/rancher/k3s-upgrade) container image is to leverage procfs, grep, and regex to determine the location of the running `k3s` executable and replace that file-system path with `k3s` from the image. This works in most scenarios but simple things like changing the k3s unit file to invoke `k3s --debug server ...` have caused issues in the past. 

**Describe the solution you'd like**
Given that `k3s` as non-trivial service binary it would be nice to enable upgrades by dropping a new binary in a staging directory that `k3s`, upon start-up, will look for and upgrade itself to. This can be as simple as:
- copy from staging to expected location (ideally a full path matching where a service unit will expect it to be)
- HUP or EXIT and allow supervisor to restart `k3s`

**Describe alternatives you've considered**
n/a

**Additional context**
- https://github.com/rancher/k3s-upgrade/pull/26
- https://github.com/rancher/k3s-upgrade/pull/24
- https://github.com/rancher/k3s-upgrade/pull/21
- https://github.com/rancher/k3s-upgrade/pull/17

**Comment by fapatel1** [comment]
@dweomer hey does this still need to be worked on? Or should we close this one up for now and recreate if it comes up again

**Comment by dweomer** [comment]
Well, I still think it's a good idea (because it's at least partly mine) but it is currently low-enough of a priority that we should just close this out, sure.
