### ISSUE TITLE
Local code changes do not take effect while building

### ISSUE THREAD

**Issue by rohrit** [k3s-io/k3s#2121]
**Environmental Info:**
K3s Version: master

Node(s) CPU architecture, OS, and Version: 1, Ubuntu 18.04 LTS

Cluster Configuration: 1 (single node)

**Describe the bug:**
I am trying to build the k3s code base as described in https://github.com/rancher/k3s/blob/master/BUILDING.md. I made some changes to vendor/k8s.io/kubernetes/cmd/kube-proxy/app/conntrack.go. I did make after this. The rebuilt k3s executable does not seem have the changes. I had to silence the scripts/validate since it was complaining about source dirty.

I want to copy the built k3s executable to a different machine which is why i am building the release version through make.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**
Build has changes

**Actual behavior:**
Build does not have changes

**Additional context / logs:**

**Comment by cjrpriest** [comment]
I am experiencing the same problem
