### ISSUE TITLE
Update rancher/plugins for k3s

### ISSUE THREAD

**Issue by sonicaj** [k3s-io/k3s#2122]
I was experimenting building k3s and saw that we are using a fork of containernetworking/plugins ( https://github.com/rancher/plugins ) which has not been updated in quite some time. Upstream has added lots of features / fixes during that time and it would be great if we could either update the fork or default to using containernetworking/plugins directly if we don't have a diff to maintain.

**Environmental Info:**
K3s Version: 

Master branch of k3s repo

**Comment by sonicaj** [comment]
I can make a PR to use containernetworking/plugins directly if you guys approve. Thank you

**Comment by sonicaj** [comment]
On a closer look we do need that fork it seems because of how we integrate it into the build script we have. Can we please update it then to include the latest plugins offered by upstream ( i am particularly interested in `static` ). If you would like me to help with the update part, I can do that as well. Thank you

**Comment by brandond** [comment]
Are you asking that k3s update its vendored version of rancher/plugins, or that rancher/plugins itself be updated from the upstream repo so that we can make those improvements available in k3s?

Are there any specific features / bug fixes / etc in particular that you're running into?

**Comment by brandond** [comment]
FYI, k3s is currently using https://github.com/rancher/plugins/tree/v0.8.6-k3s1 which is the latest tagged release available upstream.
