### ISSUE TITLE
Rancher K3s with Ipv6

### ISSUE THREAD

**Issue by rassadi** [k3s-io/k3s#2123]
Hi,

I have been trying to bring up k3s with IPv6 address. 
Here is how I started k3s:

curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent --no-flannel --no-deploy coredns  --no-deploy servicelb --no-deploy traefik --disable-agent  --write-kubeconfig /etc/kubernetes/kubeconfig   --bind-address [2600:1f13:9b3:8c76:1c9c:4f05:dafc:d54d]  --node-ip 2600:1f13:9b3:8c76:1c9c:4f05:dafc:d54d  --tls-san 2600:1f13:9b3:8c76:1c9c:4f05:dafc:d54d  --cluster-cidr "fd20::0/112"  --service-cidr "fd00:4000::/112"  --kube-controller-manager-arg node-cidr-mask-size=120" sh -

The logs suggest k3s could come up:

[INFO]  Finding release for channel stable
[INFO]  Using v1.18.6+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.18.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service -> /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

But Pods are not created:

ubuntu@ip-172-31-64-221:~$ sudo kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-kjvqb   0/1     Pending   0          7s
kube-system   metrics-server-7566d596c8-4hpnl          0/1     Pending   0          7s

 sudo kubectl describe pod metrics-server-7566d596c8-4hpnl -n kube-system
Name:           metrics-server-7566d596c8-4hpnl
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=metrics-server
                pod-template-hash=7566d596c8
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/metrics-server-7566d596c8
Containers:
  metrics-server:
    Image:        rancher/metrics-server:v0.3.6
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-8wnwf (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-8wnwf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-8wnwf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods

And k3s log says:

journalctl -u k3s -f
-- Logs begin at Tue 2020-08-11 18:14:55 UTC. --
Aug 13 15:26:51 ip-172-31-64-221 k3s[5203]: I0813 15:26:51.712309    5203 controller.go:127] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
Aug 13 15:27:02 ip-172-31-64-221 k3s[5203]: I0813 15:27:02.694795    5203 request.go:621] Throttling request took 1.04872152s, request: GET:https://127.0.0.1:6444/apis/rbac.authorization.k8s.io/v1?timeout=32s
Aug 13 15:27:03 ip-172-31-64-221 k3s[5203]: W0813 15:27:03.445541    5203 garbagecollector.go:644] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
Aug 13 15:27:10 ip-172-31-64-221 k3s[5203]: E0813 15:27:10.616643    5203 resource_quota_controller.go:408] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Aug 13 15:27:34 ip-172-31-64-221 k3s[5203]: I0813 15:27:34.996471    5203 request.go:621] Throttling request took 1.048798886s, request: GET:https://127.0.0.1:6444/apis/rbac.authorization.k8s.io/v1?timeout=32s
Aug 13 15:27:35 ip-172-31-64-221 k3s[5203]: W0813 15:27:35.747293    5203 garbagecollector.go:644] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
Aug 13 15:27:41 ip-172-31-64-221 k3s[5203]: E0813 15:27:41.018756    5203 resource_quota_controller.go:408] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Aug 13 15:28:07 ip-172-31-64-221 k3s[5203]: I0813 15:28:07.298141    5203 request.go:621] Throttling request took 1.048650417s, request: GET:https://127.0.0.1:6444/apis/rbac.authorization.k8s.io/v1?timeout=32s
Aug 13 15:28:08 ip-172-31-64-221 k3s[5203]: W0813 15:28:08.049105    5203 garbagecollector.go:644] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
Aug 13 15:28:11 ip-172-31-64-221 k3s[5203]: E0813 15:28:11.420900    5203 resource_quota_controller.go:408] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

Can you please suggest what might be causing this and further steps ?

**Comment by j-landru** [comment]
IPv6 k3s clusters are not yet operational. This is the subject of issue #284 
I also published some personal notes about my unsuccessful tries on an alternate git, see https://framagit.org/snippets/5803
Hope this can be helpful.

**Comment by unixfox** [comment]
Still relevant but it will soon be fixed.

**Comment by 662** [comment]
Can I listen ipv6 now?

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 483eadb59a499fe8173d59714f05045f8a3bc2bf using default cni on one server one agent cluster on a ipv6 only setup using nat64
```
$ kubectl get nodes
NAME                  STATUS   ROLES                  AGE   VERSION
i-0b32536624bdc13af   Ready    <none>                 72m   v1.23.5+k3s-483eadb5
i-0cf8aac355da42cbb   Ready    control-plane,master   76m   v1.23.5+k3s-483eadb5

$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-6c79684f77-nb98k   1/1     Running     0          77m
kube-system   coredns-d76bd69b-n4xh9                    1/1     Running     0          77m
kube-system   helm-install-traefik-crd-m9wls            0/1     Completed   0          77m
kube-system   metrics-server-7cd5fcb6b7-lnmrd           1/1     Running     0          77m
kube-system   helm-install-traefik-qbzf4                0/1     Completed   2          77m
kube-system   svclb-traefik-brg9j                       2/2     Running     0          76m
kube-system   traefik-58b759688b-ppknm                  1/1     Running     0          76m
kube-system   svclb-traefik-llcz6                       2/2     Running     0          72m

```
From the logs, ipv6 address is used to join the agent. 
```
Apr 11 15:44:14 i-0cf8aac355da42cbb k3s[2979]: time="2022-04-11T15:44:14Z" level=info msg="Running kube-apiserver --advertise-address=2600:1f1c:ab4:ee10:19a3:1d0e:4a32:4915 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --authorization-mode=Node,RBAC --bind-address=::1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --feature-gates=JobTrackingWithFinalizers=true --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=2001:cafe:43:1::/112 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
Apr 11 15:44:14 i-0cf8aac355da42cbb k3s[2979]: time="2022-04-11T15:44:14Z" level=info msg="To join node to cluster: k3s agent -s https://[2600:1f1c:ab4:ee10:19a3:1d0e:4a32:4915]:6443 -t ${NODE_TOKEN}"
Apr 11 15:44:22 i-0cf8aac355da42cbb k3s[2979]: time="2022-04-11T15:44:22Z" level=info msg="Connecting to proxy" url="wss://[2600:1f1c:ab4:ee10:19a3:1d0e:4a32:4915]:6443/v1-k3s/connect"
```

```
$ sudo cat /var/lib/rancher/k3s/agent/etc/flannel/net-conf.json
{
	"Network": "0.0.0.0/0",
	"EnableIPv6": true,
	"EnableIPv4": false,
	"IPv6Network": "2001:cafe:43::/56",
	"Backend": {
	"Type": "vxlan"
}
}
```
Note: Tracking issue when etcd backend is used (https://github.com/k3s-io/k3s/issues/5237)
