### ISSUE TITLE
k3s cannot pull the images of my private repository

### ISSUE THREAD

**Issue by linzj3** [k3s-io/k3s#2130]
**Environmental Info:**
K3s Version: 

v1.17.9+k3s1 (000a361f)
Node(s) CPU architecture, OS, and Version: 

Linux k3s-node2 5.8.1-1.el7.elrepo.x86_64 #1 SMP Tue Aug 11 12:01:11 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

2 masters, no workers
**Describe the bug:**

Failed to pull image "harbor.mideazy.com/rancher/istio-pilot:1.4.9": rpc error: code = Unknown desc = Error response from daemon: unauthorized: unauthorized to access repository: rancher/istio-pilot, action: pull: unauthorized to access repository: rancher/istio-pilot, action: pull
**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by linzj3** [comment]
but I can pull the images by myself. ex: docker pull harbor.mideazy.com/rancher/istio-pilot:1.4.9 
[root@k3s-node2 k3s]# docker pull harbor.mideazy.com/rancher/istio-pilot:1.4.9 
1.4.9: Pulling from rancher/istio-pilot
23884877105a: Already exists 
bc38caa0f5b9: Already exists 
2910811b6c42: Already exists 
36505266dcc6: Already exists 
a78d895d9f83: Already exists 
9b0dd883c8fd: Already exists 
38e7f77217c9: Pull complete 
bdaa8c182830: Pull complete 
Digest: sha256:440f809544f7fed6c17334f9a4ab592b6a01b8600395b375a477177f6ba375e0
Status: Downloaded newer image for harbor.mideazy.com/rancher/istio-pilot:1.4.9
harbor.mideazy.com/rancher/istio-pilot:1.4.9

**Comment by mnorrsken** [comment]
have you configured /etc/rancher/k3s/registries.yaml on each node as per
https://rancher.com/docs/k3s/latest/en/installation/private-registry/
