### ISSUE TITLE
k3s kubectl slow on rpi

### ISSUE THREAD

**Issue by mnorrsken** [k3s-io/k3s#2132]
**Environmental Info:**
K3s Version: 
k3s version v1.18.4+k3s1 (97b7a0e9)

Node(s) CPU architecture, OS, and Version: 
Linux alderaan 5.4.51-v8+ #1326 SMP PREEMPT Fri Jul 17 10:58:13 BST 2020 aarch64 GNU/Linux

Cluster Configuration:
1 master 1 worker

**Describe the bug:**
k3s kubectl is slow to load compared to official kubectl. this varies in slowness but it is always a slight bit slower. When a lot of stuff going on in the k3s cluster, difference is much larger. most likely is connected to slow write latency of SD cards, which can sometimes be ~800ms, but the issue is why official kubectl is always faster.
```
# time k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:40Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:40Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm64"}

real    0m0.988s
user    0m0.874s
sys     0m0.123s
# time ./kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:40Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm64"}

real    0m0.223s
user    0m0.193s
sys     0m0.037s

```

Kubectl get all when having a lot of pods restarting:
```
# k3s kubectl get all
real    0m57.156s
user    0m1.140s
sys     0m0.317s

# ./kubectl get all
real    0m19.824s
user    0m0.564s
sys     0m0.242s
```

**Steps To Reproduce:**
on two nodes:
install raspbian buster on RPi4 4GB, samsung EVO+ 64gb SD card
apt update, apt upgrade
switch to 64 bit kernel in config.txt
arm_64bit=1
disable ipv6, enable cgroups in cmdline.txt
ipv6.disable=1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1

on master:
k3s installed with --disable local-storage --write-kubeconfig-mode 640 --disable traefik
installed traefik2 helm chart for ingress
installed nfs-client-provisioner for persistent storage

on worker:
install worker node as per k3s documentation

Install loads of services, around 30 deployments/daemonsets/statefulsets
run k3s kubectl commands

**Expected behavior:**
k3s kubectl responding sufficiently fast

**Actual behavior:**
k3s kubectl responding slower than official kubectl, sometimes much slower

**Comment by ob** [comment]
I have a similar problem with a cluster of 4 raspberry pi nodes configured in HA mode (multi-master, three are servers, one is agent). 

```
# k3s --version
k3s version v1.19.2+k3s1 (d38505b1)
```

If I use the first master for the API server:

```
❯ time kubectl get pods -A
      24
kubectl get pods -A  0.17s user 0.13s system 1% cpu 15.569 total
```

But if I edit `~/.kube/config` and point to the second master:

```
❯ time kubectl get pods -A
      24
kubectl get pods -A  0.15s user 0.11s system 23% cpu 1.115 total
```

I'm not going to change anything in case anyone wants me to debug further.
