### ISSUE TITLE
k3s without network connectivity

### ISSUE THREAD

**Issue by posteingang** [k3s-io/k3s#2135]
Hi,
we want to serve offline k3s standalone devices. Unfortunately we have to external network connectivity at all. Is it possible to start k3s without a default route?

**Environmental Info:**
K3s Version: k3s version v1.18.4+k3s1 (97b7a0e9)

Node(s) CPU architecture, OS, and Version: Linux 3i8g3j 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux CentOS 8

Cluster Configuration: 1 Master

**Describe the bug:**

k3s is not starting without network connectivity.

**Steps To Reproduce:**
* unplug/disble all network connections
* start k3s
* `apiserver exited: Unable to find suitable network address.error='no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.`

**Expected behavior:**
* k3s should start also in standalone mode

**Actual behavior:**
* k3s does'nt start

**Comment by dweomer** [comment]
Have you tried disabling ipv6?

**Comment by posteingang** [comment]
yes, right now. no change. :-(

**Comment by brandond** [comment]
Have you tried either adding a dummy default route, or setting the apiserver arguments as described in the error message?

**Comment by posteingang** [comment]
My current setup to workaround that problem is:
* one dummy interface with a default route metric 999
* set --advertise-address to that dummy interface `$(ip r | grep default | grep 999 | cut -d' ' -f 3)`

That works so far, but actually I am not sure if this is a good solution or not. I played also around with BindAddress but that didn't work for me.

**Comment by janeczku** [comment]
Creating a single dummy route on the primary NIC might be sufficient to work around this:

```
ip route add 0.0.0.0 via 0.0.0.0 metric 9999 dev eth0
```

where `dev eth0` should match the interface that has a valid global unicast address configured (either statically or via DHCP)
