### ISSUE TITLE
Unable to edit 10-flannel.conflist

### ISSUE THREAD

**Issue by segabond** [k3s-io/k3s#2138]
**Environmental Info:**
K3s Version: 
k3s version v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version: 
Linux MS01200530000045 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**
CNI config file is being overwritten with defaults every time I restart a service
I am adding a section into /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist
to enable bandwidth management
```

{
  "name":"cbr0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}

```

and it is being reverted on `systemctl restart k3s`

**Expected behavior:**
Changes are kept in the  /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist

**Actual behavior:**
Changes are lost in the  /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist

**Comment by brandond** [comment]
Yes, there is not currently any way to customize the CNI configuration file.

**Comment by VictorRobellini** [comment]
The only way I have found to do this is to follow [these steps:](https://github.com/intel/multus-cni/issues/549#issuecomment-683491163
)
