### ISSUE TITLE
NGINX Ingress | LoadBalancer in pending state. even with static ip

### ISSUE THREAD

**Issue by srinathganesh1** [k3s-io/k3s#2139]
**Environmental Info:**
K3s Version: k3s version v1.18.6+k3s1 (6f56fa1d)

**Describe the bug:**

For a simple ingress like (terraform script)
```
resource "helm_release" "ingress" {
  name       = "ingress-foo"
  chart      = "https://github.com/kubernetes/ingress-nginx/releases/download/ingress-nginx-2.5.0/ingress-nginx-2.5.0.tgz"
}
```

- External IP is never getting assigned. Status is pending for IP
- Even attempted to set static IP, still pending
- For minikube, we solve this with `minikube tunnel`. is there a similar approach here?

**Comment by brandond** [comment]
What are you using as your loadbalancer provider? If you're using the built-in servicelb, have you confirmed that you have the requested port available on at least one of your nodes?

**Comment by srinathganesh1** [comment]
> have you confirmed that you have the requested port available on at least one of your nodes

I have not performed any action to make port available on nodes (in AKS, GKE etc I just deploy helm and its default LoadBalancer auto start)

I'll try to check within the nodes

**Comment by srinathganesh1** [comment]
> have you confirmed that you have the requested port available on at least one of your nodes?

is there a way to exec in to a Node? I know to exec into a pod with `kubectl exec -it pod_id -- bin/bash`
