### ISSUE TITLE
Setting my local private registry in k3s & containerd

### ISSUE THREAD

**Issue by Roihn** [k3s-io/k3s#2149]
**Environmental Info:**
K3s Version: v1.18.8+k3s1 (6b595318)
crictl version v1.18.0-k3s1

```bash
#docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Node(s) CPU architecture, OS, and Version:** 
only one node works as server;
```bash
Linux ubu-node 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Cluster Configuration:**

1 master

**Describe the bug:**

I would like to let `kubectl` automatically pull the images (take `nginx` as an example) from my private registry. Hence I placed my `registries.yaml` in `/etc/rancher/k3s/` (copied from #1210)

```yaml
mirrors:
  docker.io:
    endpoint:
      - "http://192.168.63.129:5000"
  192.168.63.129:5000:
    endpoint:
      - "http://192.168.63.129:5000"
```

and `sudo systemctl restart k3s`

Then I see that with `sudo crictl info`

```bash
 ...
 "registry": {
      "mirrors": {
        "192.168.63.129:5000": {
          "endpoint": [
            "http://192.168.63.129:5000"
          ]
        },
        "docker.io": {
          "endpoint": [
            "http://192.168.63.129:5000"
          ]
        }
      },
      "configs": null,
      "auths": null
    },
...
```

The registry has already been changed. 

However, when I change to off-line environment ( to make sure that `kubectl` will pull image from local server), and run the command `sudo kubectl apply -f ./nginx.yaml` where 

```yaml
#nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-example
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers:
      - image: nginx
        name: hello-nginx
        ports:
        - containerPort: 7001
```

However, I get the output when running `sudo kubectl describe pods`

```bash
Events:
  Type     Reason     Age        From               Message
  ----     ------     ----       ----               -------
  Normal   Scheduled  <unknown>  default-scheduler  Successfully assigned default/hello-nginx-6857b944d4-bdkf7 to ubu-node
  Normal   Pulling    9s         kubelet, ubu-node  Pulling image "nginx"
  Warning  Failed     4s         kubelet, ubu-node  Error: ErrImagePull
  Warning  Failed     4s         kubelet, ubu-node  Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head https://registry-1.docker.io/v2/library/nginx/manifests/latest: dial tcp: lookup registry-1.docker.io: Try again
  Warning  Failed     3s         kubelet, ubu-node  Error: ImagePullBackOff
  Normal   BackOff    3s         kubelet, ubu-node  Back-off pulling image "nginx"

```

It still goes to `https://registry-1.docker.io/v2/library/nginx/manifests/latest` to pull image...

I have made sure that my registry is running, 

```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
a8d9282908fe        registry:2          "/entrypoint.sh /etc…"   6 hours ago         Up 46 minutes       0.0.0.0:5000->5000/tcp   registry_roihn
```

But when i check the logs with `docker logs registry_roihn`, there is no related record of visiting this registry, which means that `kubectl` did not even try to visit this registry.

**Steps To Reproduce:**

- Install `k3s` with air-gap:

  - Download three files: `k3s-airgap-images-amd64.tar`, `k3s` binary file, `install.sh` from https://get.k3s.io
  - Give them permission (`chmod +x`) and change the location
  - `sudo INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh`

- Prepare private registry:

  I followed the instructions [here](https://www.tutorialspoint.com/docker/docker_private_registries.htm) step by step. 

- Place `registries.yaml`

  ```bash
  sudo cp registries.yaml /etc/rancher/k3s/
  sudo systemctl restart k3s
  ```

- Turn off the internet (WLAN)

- Apply a deployment called "hello-nginx"

  ```bash
  sudo kubectl apply -f ./nginx.yaml
  ```

- Get the description of related pod

  

**Expected behavior:**

`kubectl` can pull `nginx` from local private registry, which means that `k3s` can be applied off-line.

**Actual behavior:**

`kubectl` still goes to  `https://registry-1.docker.io/v2/library/nginx/manifests/latest` to pull image.

**Additional context / logs:**

**Comment by brandond** [comment]
* You mentioned accessing registry logs via `docker logs` - are you using the docker backend for k3s, or the default containerd backend?
* Is the registry on the same host as k3s?
* Did you load the airgap images into your local registry, or just place the airgap tarball into `/var/lib/rancher/k3s/agent/images/`?

**Comment by Roihn** [comment]
> * You mentioned accessing registry logs via `docker logs` - are you using the docker backend for k3s, or the default containerd backend?
> * Is the registry on the same host as k3s?
> * Did you load the airgap images into your local registry, or just place the airgap tarball into `/var/lib/rancher/k3s/agent/images/`?

- I'm using default containerd backend, since I did not add the flag `--docker` during the installation. Am I right?
- Yes.
- I just place the tar file in that path, but I've checked that those images have already been loaded automatically (run `crictl images` and see the following:
```bash
$ sudo crictl images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/library/nginx                    latest              4bb46517cac39       53.5MB
docker.io/rancher/coredns-coredns          1.6.9               4e797b3234604       43.3MB
docker.io/rancher/klipper-helm             v0.2.5              6207e2a3f5225       138MB
docker.io/rancher/klipper-lb               v0.1.2              897ce3c5fc8ff       6.46MB
docker.io/rancher/library-traefik          1.7.19              aa764f7db3051       86.6MB
docker.io/rancher/local-path-provisioner   v0.0.11             9d12f9848b99f       36.5MB
docker.io/rancher/metrics-server           v0.3.6              9dd718864ce61       41.2MB
docker.io/rancher/pause                    3.1                 da86e6ba6ca19       746kB

```
Thx!

**Comment by daniyalrayn** [comment]
@Roihn Nicely explained about your issue. Even I have the same issue Error: ImagePullBackOff.  Have you resolved this by any chance.

**Comment by justin0mcateer** [comment]
I am seeing the same error. For me, the problem seems to be that  k3s is trying to pull the image using HTTPS rather than HTTP, even though the 'registries.yaml' file clearly has an HTTP endpoint defined:

```
mirrors:
  "registry.local:5000":
    endpoint:
      - "http://registry.local:5000"
```

Running crictl output:
```
...
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        },
        "registry.local:5000": {
          "endpoint": [
            "http://registry.local:5000"
          ]
        }
      },
      "configs": null,
      "auths": null
    },
...
```

![Screenshot from 2020-10-05 12-42-04](https://user-images.githubusercontent.com/2607229/95113519-2feb1380-0708-11eb-8cf9-819975b0c870.png)

**Comment by himslm01** [comment]
That's not right.
The OPs registries.yaml includes a mirror for `docker.io`, so the container image being just `nginx` should have used that mirror.
```
mirrors:
  docker.io:
    endpoint:
      - "http://192.168.63.129:5000"
  192.168.63.129:5000:
    endpoint:
      - "http://192.168.63.129:5000"
 ```
That is very similar to my registries.yaml, where I have a local registry which is mirroring docker.io.

I'm sure this configuration used to work on k3s 1.17 but does not seem to be working on k3s 1.19

**Comment by dprateek1991** [comment]
Why this issue is closed ? 

Is there a solution to this issue. I'm facing something similar with K3s **v1.20.2+k3s1**

I have a Private Container Registry backed by GitLab. I have my registries.yaml at required place and have restarted K3s as well on all the nodes. I'm getting a similar error - 

**Warning  Failed     3s (x2 over 14s)  kubelet            Failed to pull image "10.77.10.16:5050/demo:latest": rpc error: code = Unknown desc = failed to pull and unpack image "10.77.10.16:5050/demo:latest": failed to resolve reference "10.77.10.16:5050/demo:latest": failed to do request: Head "https://10.77.10.16:5050/v2/telco-cdl-infra/demo/manifests/latest": x509: certificate signed by unknown authority**

When I do **sudo crictl info** I can see Private Registry being added successfully 

 **"registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://gitlab.lan:5050"
          ]
        }
      },
      "configs": {
        "gitlab.lan:5050": {
          "auth": {
            "username": "xxxx",
            "password": "xxxx",
            "auth": "",
            "identitytoken": ""
          },
          "tls": {
            "insecure_skip_verify": false,
            "caFile": "/etc/gitlab/ssl/ca.crt",
            "certFile": "/etc/gitlab/ssl/gitlab.crt",
            "keyFile": "/etc/gitlab/ssl/gitlab.key"
          }
        }
      },**

**Comment by brandond** [comment]
@dprateek1991 It's closed because it works when you configure it properly. In your case, it appears that you have configured gitlab.lan as an endpoint (mirror) for docker.io, but I don't see anything at all in there about 10.77.10.16:5050. What were you intending to do?

**Comment by sdamico918** [comment]
@brandond Is there any way to configure k3s such that it does _not_ require explicitly prepending the private registry? I have basically the same setup as the original poster and a use case where I want a generic image name (e.g. `nginx:latest`) to resolve to my private registry without me having to put `private-registry.com/nginx:latest`.

My `registries.yaml` looks like this:
```
mirrors:
  docker.io:
    endpoint:
      - "https://private-registry.com"
  private-registry.com:
    endpoint:
      - "https://private-registry.com"
```
When I restart k3s, I see that this configuration also gets automatically updated in containerd's `config.toml`. But when I `kubectl apply -f nginx` (same deployment file in the original post), k3s is still trying to pull from the default registry:
```
  Warning  Failed     18m                   kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp 18.232.227.119:443: i/o timeout
```
(It's timing out because I purposely set my outbound rules to only allow traffic to my private registry).

I can successfully pull images from my private registry _if_ I prepend the private registry name, but have yet to find a definitive answer on if it's possible to pull from a private registry by default, without prepending it.

**Comment by brandond** [comment]
Which version of K3s are you on? Different versions of K3s have different versions of containerd, and newer containerd versions have drastically improved support for properly overriding endpoints. I would probably just go with two mirrors in the config: one for `docker.io` (to override the hardcoded default) and another for `*` to match everything else.

**Comment by sdamico918** [comment]
> Which version of K3s are you on? Different versions of K3s have different versions of containerd, and newer containerd versions have drastically improved support for properly overriding endpoints. If you're not on 1.19 or newer, upgrade to that version. Once you've done that, I would probably just go with two mirrors in the config: one for `docker.io` (to override the hardcoded default) and another for `*` to match everything else.

I'm using version 1.20 of k3s:
```
[root@ip-10-109-142-22 k3s]# k3s --version
k3s version v1.20.0+k3s2 (2ea6b163)
go version go1.15.5
[root@ip-10-109-142-22 k3s]# ctr version
Client:
  Version:  v1.4.3-k3s1
  Revision: 
  Go version: go1.15.5

Server:
  Version:  v1.4.3-k3s1
  Revision: 
  UUID: 01123b10-d8df-4b05-9f29-6c63dbf73760
```

I tried replacing my `registries.yaml` file with the following:
```
mirrors:
  docker.io:
    endpoint:
      - "https://private-registry.com"
  "*":
    endpoint:  
      - "https://private-registry.com"
```
and saw the exact same results - I have connectivity to my private registry, and I can pull images from the private registry if I prepend the private registry DNS, but when I `kubectl apply -f` the following deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-example
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers:
      - image: nginx
        name: hello-nginx
        ports:
        - containerPort: 7001
```
the `nginx` image pull times out due to trying to reach `https://registry-1.docker.io/v2/library/nginx/manifests/latest`.

**Comment by sdamico918** [comment]
I am definitely not using a cert that is not trusted by containerd - again, I _can_ pull images from my private registry, both from a direct `ctr image pull` command and from a kubernetes deployment object, if I type the image name as `private-registry.com/nginx:latest`.

Since I'm not certain what deployment file/pod manifest you are using in conjunction with that `registries.yaml` example you've provided, I can't validate that we are dealing with the same use case. To reiterate, I want to be able to provide a deployment such as:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-example
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers:
      - image: nginx
        name: hello-nginx
        ports:
        - containerPort: 7001
```
and see that the image name `nginx` resolves to my private registry.

With the following `registries.yaml`:
```
mirrors:
  docker.io:
    endpoint:
      - "https://private-registry.com"
  "*":
    endpoint:  
      - "https://private-registry.com"
```
I could type the image name as `docker.io/nginx`, or `whatever-I-want-because-of-the-wildcard-entry.io/nginx`, and both of those will resolve to my private registry. If I just leave the image name as `nginx`, though, it seems to skip this mirror configuration altogether and try to pull from docker.io anyways:
```
Failed to pull image "nginx:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp 52.55.168.20:443: i/o timeout
```


The solution I figured out was to add the following entry to the `registries.yaml`:
```
mirrors:
  docker.io:
    endpoint:
      - "https://private-registry.com"
  "":
    endpoint:
      - "https://private-registry.com"
  "*":
    endpoint:  
      - "https://private-registry.com"
```
With an empty string as one of the mirrors, providing an image name with _no prepended registry_ will now resolve to my private registry.

What still seems problematic is the fact that if k3s cannot pull from any of the mirrors provided, it will still try to reach docker.io. So, if the image I'm trying to pull doesn't exist in my registry, instead of failing immediately and displaying an "image not found" error, it still reaches out to docker.io. The whole point of this use case is to keep traffic to my internal resources, so this defeats the purpose.

**Comment by brandond** [comment]
Containerd should be normalizing the image names before checking the mirrors - `nginx` is normalized to `docker.io/library/nginx:latest` so just pulling `nginx` should use the mirror settings for `docker.io`. Similarly, the wildcard entry should match that as well.

It's odd that it's not doing that, and probably worth opening an issue in containerd/containerd, since that's what's responsible for the behavior you're seeing.

**Comment by brandond** [comment]
You might also check out https://github.com/containerd/cri/blob/master/docs/registry.md:
> As an example, for the image gcr.io/library/busybox:latest, the endpoints are:
>
>gcr.io is configured: endpoints for gcr.io + default endpoint https://gcr.io/v2.
>* is configured, and gcr.io is not: endpoints for * + default endpoint https://gcr.io/v2.
>None of above is configured: default endpoint https://gcr.io/v2.

**Comment by brandond** [comment]
Just for another datapoint, if I start K3s with CONTAINERD_LOG_LEVEL=debug, and the registry configuration provided above, here's what I see in `/var/lib/rancher/k3s/agent/containerd/containerd.log` when I do `kubectl run -i --tty busybox --image=busybox --restart=Never`. Note that it **does** normalize the reference and pulls from the mirror.

This is on `v1.20.4+k3s-fad2a046` so if you're on an older release, you might try updating?

```
level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:busybox,Uid:d43d8679-073c-4204-bad7-a2e62ac2706c,Namespace:default,Attempt:0,}"
level=debug msg="Sandbox config &PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:busybox,Uid:d43d8679-073c-4204-bad7-a2e62ac2706c,Namespace:default,Attempt:0,},Hostname:busybox,LogDirectory:/var/log/pods/default_busybox_d43d8679-0
level=debug msg="Generated id \"952e93a76e21ea31bca7c161900bfc360c29bd4351b2bd32900ddd397b237d53\" for sandbox \"busybox_default_d43d8679-073c-4204-bad7-a2e62ac2706c_0\""
level=debug msg="Sandbox container \"952e93a76e21ea31bca7c161900bfc360c29bd4351b2bd32900ddd397b237d53\" spec: (*specs.Spec)(0xc001c49700){Version:(string)1.0.2-dev Process:(*specs.Process)(0xc0005c4690){Terminal:(bool)false ConsoleSi
level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:busybox,Uid:d43d8679-073c-4204-bad7-a2e62ac2706c,Namespace:default,Attempt:0,} returns sandbox id \"952e93a76e21ea31bca7c161900bfc360c29bd4351b2bd32900ddd397b237d53\""
level=info msg="PullImage \"busybox:latest\""
level=debug msg="PullImage using normalized image ref: \"docker.io/library/busybox:latest\""
level=debug msg="do request" host=docker-io.registry.k3s.khaus request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest
level=debug msg="fetch response received" host=docker-io.registry.k3s.khaus response.header.content-length=158 response.header.content-type="application/json; charset=utf-8" response.header.date="Fri, 26 Feb 2021 01:29:12 GMT" respon
level=debug msg="do request" host=docker-io.registry.k3s.khaus request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest
level=debug msg="fetch response received" host=docker-io.registry.k3s.khaus response.header.content-length=2080 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 26 Feb
level=debug msg="do request" digest="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" mediatype=application/vnd.docker.distribution.manifest.list.v2+json request.header.accept="application/vnd.docker.distribut
level=debug msg="fetch response received" digest="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=158 respons
level=debug msg="do request" digest="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" mediatype=application/vnd.docker.distribution.manifest.list.v2+json request.header.accept="application/vnd.docker.distribut
level=debug msg="fetch response received" digest="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=2080 respon
level=debug msg="do request" digest="sha256:74e4a68dfba6f40b01787a3876cc1be0fb1d9025c3567cf8367c659f2187234f" mediatype=application/vnd.docker.distribution.manifest.v2+json request.header.accept="application/vnd.docker.distribution.m
level=debug msg="fetch response received" digest="sha256:74e4a68dfba6f40b01787a3876cc1be0fb1d9025c3567cf8367c659f2187234f" mediatype=application/vnd.docker.distribution.manifest.v2+json response.header.content-length=527 response.hea
level=debug msg="do request" digest="sha256:491198851f0ccdd0882cb9323f3856043d4e4c65b773e8eac3e0f6bc979a2ae7" mediatype=application/vnd.docker.container.image.v1+json request.header.accept="application/vnd.docker.container.image.v1+j
level=debug msg="fetch response received" digest="sha256:491198851f0ccdd0882cb9323f3856043d4e4c65b773e8eac3e0f6bc979a2ae7" mediatype=application/vnd.docker.container.image.v1+json response.header.content-length=1457 response.header.c
level=debug msg="do request" digest="sha256:5c4213be9af904dd74649d250f22023f532b2f9179ffcb15260b5eaa10d7a3b4" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff
level=debug msg="fetch response received" digest="sha256:5c4213be9af904dd74649d250f22023f532b2f9179ffcb15260b5eaa10d7a3b4" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.content-length=764655 response.hea
level=debug msg="create image" name="docker.io/library/busybox:latest" target="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f"
level=info msg="ImageCreate event &ImageCreate{Name:docker.io/library/busybox:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
level=debug msg="create image" name="docker.io/library/busybox:latest" target="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f"
level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/library/busybox:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
level=debug msg="create image" name="docker.io/library/busybox@sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" target="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f"
level=info msg="ImageCreate event &ImageCreate{Name:docker.io/library/busybox@sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
level=debug msg="Pulled image \"busybox:latest\" with image id \"sha256:491198851f0ccdd0882cb9323f3856043d4e4c65b773e8eac3e0f6bc979a2ae7\", repo tag \"docker.io/library/busybox:latest\", repo digest \"docker.io/library/busybox@sha256
level=info msg="PullImage \"busybox:latest\" returns image reference \"sha256:491198851f0ccdd0882cb9323f3856043d4e4c65b773e8eac3e0f6bc979a2ae7\""
level=info msg="CreateContainer within sandbox \"952e93a76e21ea31bca7c161900bfc360c29bd4351b2bd32900ddd397b237d53\" for container &ContainerMetadata{Name:busybox,Attempt:0,}"
level=debug msg="Container config &ContainerConfig{Metadata:&ContainerMetadata{Name:busybox,Attempt:0,},Image:&ImageSpec{Image:sha256:491198851f0ccdd0882cb9323f3856043d4e4c65b773e8eac3e0f6bc979a2ae7,Annotations:map[string]string{},},
level=debug msg="Generated id \"6b0281fc92735745e3658f1f66afb51f84f0ef8335e1ea9e29052b7dd63d5a11\" for container \"busybox_busybox_default_d43d8679-073c-4204-bad7-a2e62ac2706c_0\""
level=debug msg="Container \"6b0281fc92735745e3658f1f66afb51f84f0ef8335e1ea9e29052b7dd63d5a11\" spec: (*specs.Spec)(0xc00212bf80){Version:(string)1.0.2-dev Process:(*specs.Process)(0xc0005c4a50){Terminal:(bool)true ConsoleSize:(*spec
level=debug msg="Composed container full log path \"/var/log/pods/default_busybox_d43d8679-073c-4204-bad7-a2e62ac2706c/busybox/0.log\" using sandbox log dir \"/var/log/pods/default_busybox_d43d8679-073c-4204-bad7-a2e62ac2706c\" and c
level=info msg="CreateContainer within sandbox \"952e93a76e21ea31bca7c161900bfc360c29bd4351b2bd32900ddd397b237d53\" for &ContainerMetadata{Name:busybox,Attempt:0,} returns container id \"6b0281fc92735745e3658f1f66afb51f84f0ef8335e1ea
level=debug msg="Start writing stream \"stdout\" to log file \"/var/log/pods/default_busybox_d43d8679-073c-4204-bad7-a2e62ac2706c/busybox/0.log\""

```

**Comment by akhishukla23** [comment]
I am facing this issue with latest k3s version: v1.21.1+k3s1 and containerd as runtime while using private registry

/etc/rancher/k3s/registries.yaml configuration:

mirrors:
  "my-registry.in.net:443":
    endpoint:
      - "https://my-registry.in.net:443"

When I run: 
kubectl run pod1 --image my-registry.in.net:443/my_image

I get the following error:

Successfully assigned default/pod1 to node1
22m         Normal    Pulling                   pod/pod1      Pulling image "my-registry.in.net:443/my_image"
22m         Warning   Failed                    pod/pod1      Failed to pull image "my-registry.in.net:443/my_image": rpc error: code = Unknown desc = failed to pull and unpack image "my-registry.in.net:443/my_image:latest": failed to resolve reference "my-registry.in.net:443/my_image:latest": failed to do request: Head "https://my-registry.in.net/v2/my_image/manifests/latest": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

Using following docker command,  I can pull "my_image" from same private registry (having set "insecure-registries" to /etc/docker/daemon.son):

docker pull my-registry.in.net:443/my_image

I also tar the image pulled from docker command and placed in /var/lib/rancher/k3s/agent/images/my_image.tar and when I restarted k3s server the "crictl images" loaded the docker image to containerd along with rancher images:
my-registry.in.net:443/my_image:   latest 

Despite the image available in containerd, running a pod tried to pull my_image from private registry and gives the same error.

Can I get the answer for following questions:
1. Why k3s is not pulling images from my private registry, am I missing something?
2. If the image is available locally on k3s host, why is it still trying to pull from remote? How can I configure local images/tar and make it available to k3s?

Thanks!

**Comment by brandond** [comment]
> x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

You need to fix the certificate on your registry; it is not valid according to Go's certificate validation rules. You can Google that error message for more information.

**Comment by akhishukla23** [comment]
> > x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
> 
> You need to fix the certificate on your registry; it is not valid according to Go's certificate validation rules. You can Google that error message for more information.

Thanks @brandond. Can you please suggest any other workaround? Either skipping the certificate validation should work or I should be able to use the local image? I am trying both these approaches but not able to successfully deploy: 

1.  I have explicitly set insecure_skip_verify: true in registries.yaml to skip certificate validation. I believe this is true by default and should work:

```
mirrors:
"my-registry.in.net:443":
endpoint:
- "https://my-registry.in.net:443"
configs:
  "my-registry.in.net:443":
  tls:
   insecure_skip_verify: true
```

2. I  have loaded the the image locally in containerd of k3s server host, I should be able to deploy it without pulling it from remote:
```
$ crictl images
IMAGE                                              TAG                    IMAGE ID            SIZE
my-registry.in.net:443/my_image   latest                 f36c4bcee3c41     155MB
```

can you suggest a workaround other than fixing the certificates on my registry server?

**Comment by brandond** [comment]
> 1. I have explicitly set insecure_skip_verify: true in registries.yaml to skip certificate validation. I believe this is true by default and should work

`insecure_skip_verify` is NOT the default, and I don't believe that this disables the same CN processing that is controlled by the `GODEBUG=x509ignoreCN=0` environment variable. Your best bet is to update the self-signed cert to include the SubjectAlternativeName attribute that go (and other TLS clients) require - or simply use HTTP instead of HTTPS.

> 2. I have loaded the the image locally in containerd of k3s server host, I should be able to deploy it without pulling it from remote:

If you're going to do this, you need to import the images into the `k8s.io` namespace otherwise the kubelet will not find them.

**Comment by Code7Bit** [comment]
The fastest way for me is to move the self-signed certificate to the trusted of the machine it self k3s containerd picks it up:
apt-get install ca-certificates
cp cacert.pem /usr/share/ca-certificates
sudo dpkg-reconfigure ca-certificates

**Comment by cthumuluru** [comment]
I've trouble setting up my local private registry to work in k3s. I couldn't get it to work. Can you someone take a look at what I'm missing?

# /etc/rancher/k3s/registries.yaml
$ /etc/rancher/k3s $ cat registries.yaml 
mirrors:
  private-registry.com:
    endpoint:
      - "http://192.168.86.25:5000"

# k3s version
$ k3s --version
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10

# Pod creation command
kubectl run crdb-pod --image private-registry.com:5000/crdb:v24.1.2

# Error pulling the image
Failed to pull image "private-registry.com:5000/crdb:v24.1.2": failed to pull and unpack image "private-registry.com:5000/crdb:v24.1.2": failed to resolve reference "private-registry.com:5000/crdb:v24.1.2": failed to do request: Head "https://private-registry.com:5000/v2/crdb/manifests/v24.1.2": dial tcp: lookup private-registry.com: no such host

# Docker images from private registry
$ docker images | grep private
private-registry.com:5000/crdb   v24.1.2   c3b7cf301fe1   4 days ago     761MB

**Comment by brandond** [comment]
@cthumuluru please don't ask for new help on a 3 year dead issue. Open a new issue or discussion topic.
