### ISSUE TITLE
unknown container ".../kube-proxy"

### ISSUE THREAD

**Issue by unautre** [k3s-io/k3s#216]
Hello,

**Describe the bug**
I'm trying to start k3s using the Dockerfile, but the logs keep spouting errors about containers and I don't really know what is going on or if it's a real problem or not:
`node_1    | E0311 13:24:57.703258       1 pod_workers.go:190] Error syncing pod 700db7d3-43e8-11e9-aa0c-0242ac1c0003 ("coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=coredns pod=coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:24:59.173932       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get cgroup stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get container info for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": unknown container "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy"
node_1    | E0311 13:25:01.703026       1 pod_workers.go:190] Error syncing pod 704e0298-43e8-11e9-aa0c-0242ac1c0003 ("helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=helm pod=helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:25:09.225411       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get cgroup stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get container info for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": unknown container "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy"
node_1    | E0311 13:25:12.704937       1 pod_workers.go:190] Error syncing pod 704e0298-43e8-11e9-aa0c-0242ac1c0003 ("helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=helm pod=helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:25:12.710680       1 pod_workers.go:190] Error syncing pod 700db7d3-43e8-11e9-aa0c-0242ac1c0003 ("coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=coredns pod=coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:25:19.278406       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get cgroup stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get container info for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": unknown container "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy"
node_1    | E0311 13:25:26.703003       1 pod_workers.go:190] Error syncing pod 704e0298-43e8-11e9-aa0c-0242ac1c0003 ("helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=helm pod=helm-install-traefik-ccqfr_kube-system(704e0298-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:25:26.704013       1 pod_workers.go:190] Error syncing pod 700db7d3-43e8-11e9-aa0c-0242ac1c0003 ("coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"), skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=coredns pod=coredns-7748f7f6df-vmjfm_kube-system(700db7d3-43e8-11e9-aa0c-0242ac1c0003)"
node_1    | E0311 13:25:29.326512       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get cgroup stats for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": failed to get container info for "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy": unknown container "/docker/2535ecd453ce9ca5ece4e11ef0107aabe10123e238c52abf96712910f7d88ade/kube-proxy"
`
Here is the docker-compose file I'm using:
`version: '3'
services:
  server:
    image: rancher/k3s:v0.1.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=hellothisismykey
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    - http_proxy=http://proxy:8080/
    - https_proxy=http://proxy:8080/
    - no_proxy=localhost,cluster.local,k3s_node_1,k3s_server_1
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.1.0
    command: agent --docker
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=hellothisismykey
    - http_proxy=http://proxy:8080/
    - https_proxy=http://proxy:8080/
    - no_proxy=localhost,cluster.local,k3s_node_1,k3s_server_1
    volumes:
    - /lib/modules:/lib/modules
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  k3s-server: {}
`

**To Reproduce**
`docker-compose up`

**Expected behavior**
Expected: containers not crashing repeatedly

**Additional context**
The machine is a CentOS 7, and as seen in the docker-compose.yml there is a corporate proxy.

**Comment by Guigouu** [comment]
Hello, same to me:

`node_3    | E0319 16:24:49.024328       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/0d66dcd7a51f277ed692dc202f1dcce18b0c1e3c7c9722023ead435c4fe4b5d6": failed to get cgroup stats for "/docker/0d66dcd7a51f277ed692dc202f1dcce18b0c1e3c7c9722023ead435c4fe4b5d6": failed to get container info for "/docker/0d66dcd7a51f277ed692dc202f1dcce18b0c1e3c7c9722023ead435c4fe4b5d6": unknown container "/docker/0d66dcd7a51f277ed692dc202f1dcce18b0c1e3c7c9722023ead435c4fe4b5d6"
node_1    | E0319 16:24:49.027432       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/9d6490d76a45675c0a57e3a12cd93e3a95294f9745d2866e459149221091c092": failed to get cgroup stats for "/docker/9d6490d76a45675c0a57e3a12cd93e3a95294f9745d2866e459149221091c092": failed to get container info for "/docker/9d6490d76a45675c0a57e3a12cd93e3a95294f9745d2866e459149221091c092": unknown container "/docker/9d6490d76a45675c0a57e3a12cd93e3a95294f9745d2866e459149221091c092"
node_2    | E0319 16:24:59.014935       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/c1289edbc5531cca8f25ade5601202b0c135703c29d11790884c6b163c1569c9": failed to get cgroup stats for "/docker/c1289edbc5531cca8f25ade5601202b0c135703c29d11790884c6b163c1569c9": failed to get container info for "/docker/c1289edbc5531cca8f25ade5601202b0c135703c29d11790884c6b163c1569c9": unknown container "/docker/c1289edbc5531cca8f25ade5601202b0c135703c29d11790884c6b163c1569c9"`

Regards,

**Comment by nheinemans** [comment]
Exact same behaviour here.

I'm also using the http_proxy, https_proxy and no_proxy environment values to make K3S work behind a proxy. I noticed @unautre also has these in his docker-compose.

Also, I'm using the latest k3s version, 0.3.0-rc3

**Comment by pataha** [comment]
same problem to me, 0.2.0, 0.3.0-rc3

**Comment by ibuildthecloud** [comment]
The error messages that look like `node_3 | E0319 16:24:49.024328 1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/0d66dcd7a51f277ed692dc202f1dcce18b0c1e3c7c9722023ead435c4fe4b5d6": failed to get cgroup stats for "/docker` have no real side effect.  We are trying to get rid of those in #31.  But those errors are not really going to prevent k3s from working.  

@unautre Your current issue is that CoreDNS is not starting.  That is typically a result of an issue regarding your DNS configuration on the host.  We have fixed some issue in this area, specifically with http_proxy.  Can you please retest with v0.4.0+?

**Comment by 030** [comment]
0.7.0-rc9

```
node_1    | E0718 20:30:13.489059       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/336f25e8220a08ec12395e4736ab19624288b5ab0bf5157e22717b84b3fa4fa5/kube-proxy": failed to get cgroup stats for "/docker/336f25e8220a08ec12395e4736ab19624288b5ab0bf5157e22717b84b3fa4fa5/kube-proxy": failed to get container info for "/docker/336f25e8220a08ec12395e4736ab19624288b5ab0bf5157e22717b84b3fa4fa5/kube-proxy": unknown container "/docker/336f25e8220a08ec12395e4736ab19624288b5ab0bf5157e22717b84b3fa4fa5/kube-proxy"
```

The aim was to test 0.7.0, but that is not available in dockerhub.

**Comment by huapox** [comment]
**same err run k3s-v070 in docker: **
node_1  | E0727 23:10:13.495123       7 summary_sys_containers.go:47] Failed to get system container stats for "/docker/dd137c8d7c649540855029da974c3051a51a5116cb9463f5d633812520b077e1": failed to get cgroup stats for "/docker/dd137c8d7c649540855029da974c3051a51a5116cb9463f5d633812520b077e1": failed to get container info for "/docker/dd137c8d7c649540855029da974c3051a51a5116cb9463f5d633812520b077e1": unknown container "/docker/dd137c8d7c649540855029da974c3051a51a5116cb9463f5d633812520b077e1"

**Comment by brandond** [comment]
Closing due to age.
