### ISSUE TITLE
Test and validate mysql 8.x

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2167]
Test mysql 8.x and formally add support.

**Comment by linyinli** [comment]
@davidnuzik Hi, Could you tell me is there a completion date?

**Comment by davidnuzik** [comment]
Hi @linyinli there is no date. This item is in the backlog to be picked up later when we review items in the backlog. I cannot provide a date at this time. We do have an interest to test this though, if we have some time free up in a couple of months we _may_ take this on then. It's possible we may be able to validate by the end of the year (no promises).

**Comment by pcgeek86** [comment]
Unfortunately Digital Ocean Managed MySQL DBs only support MySQL version 8.0. I'd like to use DO Managed MySQL, but k3s apparently doesn't support it yet?

**Comment by brandond** [comment]
It should work fine. It's tested upstream by kine, just QA hasn't signed off on it yet.
https://github.com/k3s-io/kine/blob/master/scripts/test-run-mysql#L25-L32

**Comment by pcgeek86** [comment]
Yup, I tested it out on DO and it works fine with 1.24 RC

**Comment by caroline-suse-rancher** [comment]
Closing because this appears to be resolved
