### ISSUE TITLE
There are some problems with K3S using external IP and custom Ingress Controller

### ISSUE THREAD

**Issue by hyunrealshadow** [k3s-io/k3s#2178]
**Environmental Info:**

K3s Version: k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Linux tc-gz-1 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
Linux tc-sh-1 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

Cluster Configuration: 1master 1workers

**Describe the bug:**

When I install gloo on the configured cluster, the agent node cannot communicate with the server node

**Steps To Reproduce:**

I have two servers, and they can only communicate through the public network, so I set up "node-external-ip" for them.

Server Service Unit
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
    --docker \
    --disable traefik \
    --tls-san 182.254.xxx.xxx \
    --node-external-ip 182.254.xxx.xxx \
    --flannel-backend wireguard \
    --kube-proxy-arg "proxy-mode=ipvs" "masquerade-all=true" \
    --kube-proxy-arg "metrics-bind-address=0.0.0.0"
```
Agent Service Unit
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=exec
EnvironmentFile=/etc/systemd/system/k3s-agent.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    agent \
    --docker \
    --node-external-ip 118.25.xxx.xxx \
    --kube-proxy-arg "proxy-mode=ipvs" "masquerade-all=true" \
    --kube-proxy-arg "metrics-bind-address=0.0.0.0"
```

In order for flennel to work properly, I set the flannel.alpha.coreos .com/public-ip-overwrite.
The metrics-server is also set to use "external IP"

So far everything is working well, but when I installed gloo, the problem happened.
I use `glooctl install gateway --with-admin-console` to install gloo

**Expected behavior:**

gloo works well

**Actual behavior:**

The agent node will block connections from the server node and will also block access to the server node

**Additional context / logs:**

So I want to know what I did wrong or what I need to modify?

node detail
```
NAME      STATUS   ROLES    AGE   VERSION        INTERNAL-IP   EXTERNAL-IP       OS-IMAGE                       KERNEL-VERSION    CONTAINER-RUNTIME
tc-sh-1   Ready    <none>   16m   v1.18.8+k3s1   172.17.0.7    118.25.xxx.xxx    Debian GNU/Linux 10 (buster)   4.19.0-10-amd64   docker://19.3.12
tc-gz-1   Ready    master   18m   v1.18.8+k3s1   172.16.0.7    182.254.xxx.xxx   Debian GNU/Linux 10 (buster)   4.19.0-10-amd64   docker://19.3.12
```

**Comment by brandond** [comment]
I don't believe we have ever tested with gloo - are you sure this is a k3s issue? It sounds like bloo is blocking something or adding some bad routes between nodes?
