### ISSUE TITLE
Ubuntu (20.10) nftables support

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2183]
Based upon https://lists.ubuntu.com/archives/ubuntu-devel/2020-August/041142.html it looks like Ubuntu 20.10 will be moving to nftables.

Presently we intended to support LTS releases only such as 18.04 and 20.04; however, we should look into support nftables when able.

**Comment by davidnuzik** [comment]
October 22, 2020 is planned release date for 20.10

**Comment by gizmotronic** [comment]
This would be helpful, since 20.10 is the first version of Ubuntu to (officially) support a desktop install on the Raspberry Pi 4.

**Comment by cjellick** [comment]
This was completed by Chris. Closing. If needed, we can open a bug for this.
