### ISSUE TITLE
Create a tool for kine <-> etcd migration

### ISSUE THREAD

**Issue by stevefan1999-personal** [k3s-io/k3s#2190]
So [here](https://github.com/rancher/kine/pull/46#issuecomment-683259484) I've expressed my view on the embedded etcd support and my interest in it that it could be a [potential termination to the domination of kubeadm](https://github.com/rancher/k3s/pull/1770#issuecomment-679931374), and how kine will be ultimately replaced to just using etcd. 

However, one thing I noticed though is that because kine doesn't implement a full set of etcd features, it means we cannot effectively and correctly transfer the key-values in our kine backed datastore, so we may have to write a new tool to analyze the kine journal and then reconstruct it piece by piece in etcd.

I'm in the process of figuring out how to write such tool...meanwhile any input here would be positive.

**Comment by stevefan1999-personal** [comment]
Some simple brainstorming:
1.  We can just pull out all the KV data and then asynchronously do batch put tx in target etcd. This however cannot preserve compaction and previous versioning history
2. We can use an ORM to speed up some SQL hassle, I've written a sample schema [here](https://github.com/stevefan1999-personal/kine/blob/accc1f772cdff62ba9bb62b6971bedfae973edba/pkg/alpha/gorm/compat/schema.go#L4-L14)
3. We can also create a simple BoltDB bucket and append kine data directly, then we instruct etcd to use the new db instead
4. Make sure the migration process is verifiable. But I'm not a good dev who can write tests...

**Comment by ElisaMeng** [comment]
velero is the tool for u?

**Comment by unixfox** [comment]
Bump

**Comment by ozeliurs** [comment]
bump ?
