### ISSUE TITLE
dqlite / operation not supported on socket on --cluster-init 

### ISSUE THREAD

**Issue by alexanderturner** [k3s-io/k3s#2213]
**Environmental Info:**
K3s Version: 
k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04
Linux spine1 5.5.11-050511-generic #202003210837 SMP Sat Mar 21 08:40:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 masters 

**Describe the bug:**
When trying to instantiate a new cluster, I'm being met with the error:
```
INFO[2020-09-07T14:47:56.454649901+10:00] Starting k3s v1.18.8+k3s1 (6b595318)
FATA[2020-09-07T14:47:57.064290920+10:00] starting kubernetes: preparing server: start cluster and https: raft_init(): io: create I/O capabilities probe file: posix_allocate: operation not supported on socket
root@spine1:~# posix_allocate: operation not supported on socket
```

I don't believe this is related to the following dqlite issue https://github.com/rancher/k3s/issues/1688 as this machine doesnt run zfs, instead: 

```
root@xcloud-spine1:~# df -Th | grep "^/dev"
/dev/sda3      ext2       15G  7.9G  6.0G  57% /
/dev/sda2      ext4      120M   19M   93M  17% /mnt/onie-boot
/dev/loop1     squashfs   97M   97M     0 100% /snap/core/9665
/dev/loop0     squashfs   97M   97M     0 100% /snap/core/9804
```

**Steps To Reproduce:**
Create multimaster k3s cluster (HA)

**Comment by alexanderturner** [comment]
anything here?

**Comment by brandond** [comment]
Dqlite was experimental, and has not been carried forward into 1.19 for a multitude of reasons. I encourage you to give the managed etcd a try when 1.19 is marked stable.
