### ISSUE TITLE
Prevent CoreDNS from rewriting it's configmap on restart

### ISSUE THREAD

**Issue by VictorRobellini** [k3s-io/k3s#2214]
I'm currently using k3s in my Lab to host different services.  The situation is that I want to expose my services via LB. I've replaced the included LB with [metallb](https://metallb.universe.tf/).  Being able to share my services via L2 is great but what's even better is that I can utilize the [k8s_external](https://coredns.io/plugins/k8s_external/#description) extension in CoreDNS.  This allows me to create a dedicated subdomain that hosts all of my Kubernetes services.  All services automatically get resolved to the subdomain (service name = "A" record) via CoreDNS. With an externally accessible CoreDNS and LAN DHCP setting search domains, it's now easier than ever to interact with my services.  All it requires is some DNS config on my non-K3s DNS servers and to add a single line to the CoreDNS config map... long and short resolvable names for all the services!

The problem is that whenever I restart my system or the k3s services, the configmap gets reverted back to its original state.  I imagine that I could "--disable coredns" and install it myself, but staying as close to the k3s distribution is a much better long term plan.

**Comment by pavanfhw** [comment]
@VictorRobellini did you make any progress on this?

**Comment by brandond** [comment]
For personal use I do just copy the coredns manifest to another file with a unique name, and start k3s with `--disable coredns`. We don't currently have a good way to customize configuration of resources other than the Traefik helm chart.

**Comment by VictorRobellini** [comment]
I used `--disable coredns` and just installed it manually.

**Comment by m-bers** [comment]
@VictorRobellini  did you just manually configure `NodeHosts` as described in [this comment](https://github.com/k3s-io/k3s/issues/1328#issuecomment-606135618)? 

I'm trying to do almost the exact same thing as you but with Klipper instead of MetalLB but I want to be able to add nodes dynamically and this workaround feels pretty fragile.

**Comment by VictorRobellini** [comment]
@m-bers, I've never messed with that option, it wasn't needed to get my system up and running.  I redeployed about 2 months ago and k8s_external was all I needed.

**Comment by m-bers** [comment]
I actually got mine working today by creating another server block in `coredns-custom`, in case anyone else finds it useful:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  external.server: |
    cluster.external:53 {
      kubernetes
      k8s_external cluster.external
    }
```
