### ISSUE TITLE
Incorrect netmask / broken networking

### ISSUE THREAD

**Issue by ghost** [k3s-io/k3s#2218]
**Environmental Info:**
K3s Version: 
v1.18.8+k3s1

Node(s) CPU architecture, OS, and Version:
CPU: amd64
```
cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)
```

Cluster Configuration:
Single machine.

**Describe the bug:**
The netmask set when starting k3s is ignored/overwritten in the actual network details.

**Steps To Reproduce:**
I start k3s like this:
```
k3s server --pause-image k8s.gcr.io/pause:3.1 --cluster-cidr=172.17.0.0/16 --service-cidr=172.18.0.0/16
```
But then I see error messages in the CoreDNS log:
```
E0909 06:46:32.062213       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to watch *v1.Endpoints: Get "https://172.18.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=1968&timeout=9m9s&timeoutSeconds=549&watch=true": dial tcp 172.18.0.1:443: connect: connection refused
E0909 06:46:33.071399       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to watch *v1.Namespace: the server is currently unable to handle the request (get namespaces)
E0909 06:46:33.072022       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to watch *v1.Service: the server is currently unable to handle the request (get services)
E0909 06:46:33.072107       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to watch *v1.Endpoints: the server is currently unable to handle the request (get endpoints)
E0909 06:46:34.072784       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Namespace: the server is currently unable to handle the request (get namespaces)
E0909 06:46:34.073363       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Service: the server is currently unable to handle the request (get services)
E0909 06:46:34.074324       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: the server is currently unable to handle the request (get endpoints)
```
Although I started k3s with /16 mask, `ip a` tells me it's /24:
```
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 16:40:80:5d:c4:78 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.0/32 brd 172.17.0.0 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::1440:80ff:fe5d:c478/64 scope link
       valid_lft forever preferred_lft forever
4: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 5a:b1:b0:a2:42:5f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/24 brd 172.17.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::58b1:b0ff:fea2:425f/64 scope link
       valid_lft forever preferred_lft forever
```
Br_netfilter is on:
```
 lsmod | grep br_netfilter
br_netfilter           24576  0
bridge                188416  1 br_netfilter
```

Initially nftables was on but I turned it off and the issue persists.

I tried to understand the scope of the issue like this: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

I created the dnsutils container, I do `kubectl exec -ti dnsutils /bin/sh`.
I can run `nslookup kubernetes`:
```
nslookup kubernetes
Server:         172.18.0.10
Address:        172.18.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 172.18.0.1
```
But `telnet 172.18.0.1 443` does not work (it just hangs).
If I do `ip a` inside the dnsutils container, the netmask is again /24.
`route -n` does not mention the 172.18.0.0 network:
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.17.0.0      172.17.0.1      255.255.0.0     UG    0      0        0 eth0
```

**Expected behavior:**
- `ip a` output should match the `k3s server...` input
- CoreDNS should not complain
- telnet from the dnsutils container to 172.18.0.1:443 should connect.

**Actual behavior:**
Mismatching netmask, connection issues, missing route.

**Comment by brandond** [comment]
Just changing the cluster and service CIDRs does not change the ode-cidr-mask-size, which defaults to 24. See https://github.com/rancher/k3s/issues/697#issuecomment-576463182

Note that these args effectively cannot be changed once the cluster is up, if you want to change the per-node mask to allocate more than a /24 per node from the pod and service CIDR ranges you should start with a clean install.

**Comment by g574** [comment]
Thank you very much. That helped me a lot - I can live with /24.
But is then there no conflict between the default ` --cluster-cidr` being 10.42.0.0/16 and the default node-cidr-mask-size 24?
