### ISSUE TITLE
you should use wget prior to curl to support download broken resume

### ISSUE THREAD

**Issue by cytown** [k3s-io/k3s#2232]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
wget auto support broken resume but curl don't

**Describe the solution you'd like**
just change:
```
verify_downloader curl || verify_downloader wget || fatal 'Can not find curl or wg
et for downloading files'
```
to:
```
verify_downloader wget || verify_downloader curl || fatal 'Can not find curl or wg
et for downloading files'
```

**Describe alternatives you've considered**

**Additional context**
no

**Comment by brandond** [comment]
We're not really calling the downloader in a way that would support resume anyway, so I don't think it makes a big difference. Are you experiencing connectivity issues such that you can't download a ~60MB file in a single go?

**Comment by cytown** [comment]
Hi @brandond,

Yes, I did experience the connectivity issue, maybe just temporary issue, but it affect the real experience...
