### ISSUE TITLE
dns resolving not working after adding new agent

### ISSUE THREAD

**Issue by SagiMedinaCheckmarx** [k3s-io/k3s#2241]
**Environmental Info:**
K3s Version: 
k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 

Linux ip-aws #36-Ubuntu SMP Tue Aug 18 08:58:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux ip-aws #36-Ubuntu SMP Tue Aug 18 08:58:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master
1 worker

**Describe the bug:**

After installing new agent and join him into the cluster i can't resolve any DNS record including **google.com** and **kubernetes.default**

**Steps To Reproduce:**

On master:
- `curl -sfL https://get.k3s.io | sh `
- `kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default ` --> working!
- `kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup google.com ` --> working!
- `cat /var/lib/rancher/k3s/server/node-token` -> copy

On worker:

- curl -sfL https://get.k3s.io | K3S_URL=https://.....:6443 K3S_TOKEN=.... sh

then back to master:

- `kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default ` --> not working!
- `kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup google.com ` --> not working!

**Expected behavior:**

DNS resolving should work.

**Actual behavior:**

DNS resolving is not working.

**Additional context / logs:**

```
kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup google.com
If you don't see a command prompt, try pressing enter.
Address 1: 10.43.0.10

nslookup: can't resolve 'google.com'
pod "busybox" deleted
pod default/busybox terminated (Error)
```

An additional thing that may be related - I only expose the following ports on both nodes:
8472 (UDP)
6443 (TCP)

**Comment by memelet** [comment]
This seems to be exactly what I am seeing. I have been pounding my head for a day trying all kinds of options.

**Comment by brandond** [comment]
See the required ports here:
https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#networking

@memelet If you continue to have problems after confirming that these ports are open, please open a new issue and fill out the issue template so that we have sufficient information on your environment.

**Comment by pnavais** [comment]
Same issue here (1 master / 3 workers on Manjaro ARM 64 @ Raspberry Pi 4). Interestingly enough, after a restart of k3s on all nodes (systemctl restart k3s.service (master) systemctl restart k3s-agent.service) DNS starts working properly. This happens systematically, even after master/workers boot, DNS only starts working after k3s restart.

**Comment by brandond** [comment]
It sounds like traffic to the DNS service is being dropped if the coredns pod isn't running on the node that's trying to do the lookup. Do you have the default firewall (firewalld/ufw) enabled? Are you using nftables, or iptables-legacy?

**Comment by pnavais** [comment]
No iptables frontend (firewalld/ufw) installed and iptables legacy installed (1.8.5).

Some screenshots attached showing running pods (same pods after restarting worker node)

![CC0425A4-73AE-44D3-914E-04497DE3680D](https://user-images.githubusercontent.com/158292/96505462-70917380-1256-11eb-9555-2304012fd369.jpeg)

![415F6C5A-2CB0-46C3-B895-416E5DA395FA](https://user-images.githubusercontent.com/158292/96505459-6ec7b000-1256-11eb-85b7-f5d40455edb1.jpeg)
