### ISSUE TITLE
[k3s upgrade] K3s upgrade stuck when one of the control plane nodes is powered down. 

### ISSUE THREAD

**Issue by khushboo-rancher** [k3s-io/k3s#2251]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
**Scenario 1:**
1. Import a k3s cluster (2 control plane and 2 worker) - version v1.16.3
2. Power down 1 control plane, wait for it to become unavailable.
3. Upgrade to v1.16.7 with server/worker concurrency 1

**Result:**
1. Upgrade started with a latency of around 10 mins on the control plane node which was active.
2. Upgrade stuck.

**Scenario 2:**
1. Import a k3s cluster (2 control plane and 2 worker) - version v1.16.3
2. Power down 1 control plane, wait for it to become unavailable.
4 Upgrade to v1.16.7 with server/worker concurrency 1
5. When upgrade is stuck on powered down node, edit the cluster and change the server concurrency to 2

**Result:**
1. Upgrade started on the control plane node which was unavailable initially.
2. After editing the server concurrency to 2, upgrade started on the control plane node which was active.
3. Upgrade stuck for both nodes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2431-head- a1bb0a3e9
- Installation option (single install/HA): Single

**Comment by davidnuzik** [comment]
I moved the issue to rancher/k3s as it's in our wheelhouse.

**Comment by dweomer** [comment]
> Scenario 1:
> 
> * Neither of the given options worked. After deleting the node, the other Control Plane node began upgrading but became stuck after it was Cordoned. It is showing `Kubelet stopped posting node status.` and will not progress.
> * Editing cluster to have different Control Plane Concurrency values did not fix this.

Multi-mast upgrade does not work consistently. Sometimes it happens that once the original leader goes down nothing will ever come back up. The reason for secondary masters to fail to start-up had to do with embedded dqlite which should no longer be in use. This scenario should be re-tested using embedded etcd.

> Scenario 2:
> 
> * Deleting the node from the cluster worked and the rest of the nodes upgraded successfully afterwards.
> * Powering on the node did not work.
> 
> Powering on the node did not work in either scenario.

How long did you wait? Failing jobs can and will fail and be recreated on a 15-30 minute window, depending on failure mode.

**Comment by rancher-max** [comment]
I don't remember exactly how long I waited, but it was probably less than 30 minutes I can retry scenario 2 and wait longer to ensure the information is accurate.

As for re-testing with embedded etcd, we will either need a couple of stable rc's created so that we have something to upgrade to, or wait for another release cycle to do that as it is currently only available in our unreleased v1.19 branch.
