### ISSUE TITLE
Runtime updation of datastore URL in k3s master

### ISSUE THREAD

**Issue by raja-ashok** [k3s-io/k3s#2254]
This is a minor query about how to update datastore URL in k3s master at runtime ?

Consider a k3s master started with `--datastore-endpoint="https://etcd-host-1:2379"`. At later point how to change this URL on the **running k3s master**, to something like `--datastore-endpoint="https://etcd-host-1:2379,https://etcd-host-2:2379,https://etcd-host-3:2379"`

Thanks in advance!!

**Comment by brandond** [comment]
Edit the k3s systemd unit or openrc unit script, reload the configuration (for systemd), restart k3s service.

**Comment by raja-ashok** [comment]
Thanks for responding. I was looking for a solution which doesn't require restart of k3s server.

**Comment by brandond** [comment]
No, that is not possible. I don't believe upstream Kubernetes supports this either.

Why are you averse to restarting k3s? It doesn't stop any running pods.
