### ISSUE TITLE
Tests fail when building on debian

### ISSUE THREAD

**Issue by th3wyatt** [k3s-io/k3s#2255]
I've been exerimenting with building k3s with dpkg-buildpackage and get failures when it gets to the testing portion of the build.

**Environmental Info:**
K3s Version: 
k3s-1.16.15+k3s1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04 server amd64

Cluster Configuration:
build only

**Describe the bug:**
When attempting to build using debuild on an ubuntu server (also tried debian buster) the build goes through all steps and appears to build successfuly, but fails tests due to "kubectl: command not found"

16:18:51  [[35mBASICS[m] + docker run -d --name k3s-agent-1-tdq4wO --privileged -e K3S_TOKEN= -e K3S_URL=https://172.17.0.3:6443 rancher/k3s:v1.16.15-05f0aa27-amd64 agent
16:18:51  [[36mBASICS[m] 3a426782b659e06b955e92d16c0830000d4276425b9726cacd8e1779e7dc8da8
16:18:51  [[35mBASICS[m] + echo 'Started k3s-agent-1-tdq4wO'
16:18:51  [[36mBASICS[m] Started k3s-agent-1-tdq4wO
16:18:51  [[35mBASICS[m] + run-function agent-post-hook 1
16:18:51  [[35mBASICS[m] + declare -f agent-post-hook
16:18:51  [[35mBASICS[m] + return 0
16:18:51  [[35mBASICS[m] + timeout --foreground 1m bash -c 'wait-for-nodes 2'
16:18:51  [[35mBASICS[m] environment: kubectl: command not found
16:18:51  [[35mBASICS[m] Waiting for nodes to be ready...
16:18:57  [[35mBASICS[m] environment: kubectl: command not found
16:18:57  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:02  [[35mBASICS[m] environment: kubectl: command not found
16:19:02  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:07  [[35mBASICS[m] environment: kubectl: command not found
16:19:07  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:12  [[35mBASICS[m] environment: kubectl: command not found
16:19:12  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:17  [[35mBASICS[m] environment: kubectl: command not found
16:19:17  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:22  [[35mBASICS[m] environment: kubectl: command not found
16:19:22  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:27  [[35mBASICS[m] environment: kubectl: command not found
16:19:27  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:32  [[35mBASICS[m] environment: kubectl: command not found
16:19:32  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:37  [[35mBASICS[m] environment: kubectl: command not found
16:19:37  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:42  [[35mBASICS[m] environment: kubectl: command not found
16:19:42  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:48  [[35mBASICS[m] environment: kubectl: command not found
16:19:48  [[35mBASICS[m] Waiting for nodes to be ready...
16:19:52  [[35mBASICS[m] + test-cleanup
16:19:52  [[36mBASICS[m] Cleaning up...

**Steps To Reproduce:**
download source in a zip
unzip
run debmake to build debian templates
edit debian/changelog and remove comments from the debian/rules file for all items
run dpkg-buildpackage -b -us -uc -tc

**Expected behavior:**
.deb created from artifacts

**Actual behavior:**
build fails and exits due to tests not passing

**Comment by brandond** [comment]
I've trimmed the build log from your issue report. If you want, please attach it to the issue rather than including it inline.

Have you tried following the instructions in https://github.com/rancher/k3s/blob/master/BUILDING.md? That said, the packages are usually built directly from git, not from a source tarball so some things that expect to be able to look up tags may not work properly.
