### ISSUE TITLE
K3S should use 'pullSecrets' to read credentials stored in secrets instead of reading it from 'registries.yaml' 

### ISSUE THREAD

**Issue by ramran-r** [k3s-io/k3s#2279]
To create a desired container by pulling the images from local registry ( docker or containerd ) , credentials are stored in secrets. However it always refer 'registries.yaml' ( /etc/rancher/k3s)  to read TLS & auth credentials to pull images from local registry  and ignore 'pullSecrets' argument defined in deployment.yaml. 
Keeping hard-coded auth credentials in plain text file is non-compliance with the security standards defined in many end customers we would be going to implement k3s clustering setup. 

Our implementation for many customers would be on air-gapped environment and it is mandate to keep all required images in local regisitry either using docker or cotainderd. 

Default kubernetes  deployment files  ( values.yaml used in helm charts ) have option to use the flag 'pullSecrets' but k3s doesn't consider it. 
<<<<<<<<<<
image:
  repository: localhost:30000/grafana/loki
  tag: 1.6.1
  PullPolicy: Always
  pullSecrets: myRegistryKeySecretName
>>>>>>>>>>>

**Describe the solution you'd like**
K3S should support to use 'ImagePullSecrets' to read credentials instead of keeping  hardcoded values.

**Describe alternatives you've considered**
For current release of desired clustering setup , decided to go with using 'registries.yaml' but I am not most of the end customers don't agree who would be consuming it. 
Not sure whether it is an known issue or  should be considered as an enhancement. Pls. provide appropriate resolution or workaround to address this. 

**Additional context**

**Comment by brandond** [comment]
You can also use pullSecrets if you like, we have not disabled this functionality. The containerd registry configuration will be used as a default; if you have pullSecrets for an image those credentials should be used instead.

If you are having a trouble getting pullSecrets working, please provide more information on your configuration.

**Comment by aokomorowski** [comment]
I don't want to dig this out, but I think somebody may find it useful: if you're using imagePullSecret in k3s, SSH into the host and try to pull the image (via `crictl`) with the credentials copy-pasted from the secret. If you've got 401 Unauthorized it's most likely because the secret is invalid. Happened to me with AWS ECR, I was using credentials for `eu-central-1` and fetching images from `eu-west-2` and it took me way too long to find it.
