### ISSUE TITLE
Some pods can't resolve .svc DNS entries

### ISSUE THREAD

**Issue by ghost** [k3s-io/k3s#2287]
**Environmental Info:**
K3s Version: 
k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Linux rancher1sc 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Two masters (all-in-one without separate worker nodes)

**Describe the bug:**
Some pods can't resolve DNS entries when the hostname has .cluster.local omitted.
For example, the ingress-nginx controller and cert-manager can't resolve their own services name when they run a POST method, because they fail to recognize their FQDN.
This is not affecting all pods. I tried to spawn a busybox and a centos:7 pods and everything worked properly there.

**Steps To Reproduce:**
Create an ingress or a ClusterIssuer and see the Unknown Host error in the output.

**Expected behavior:**
DNS resolution working properly on every pod

**Actual behavior:**
Only some pods are actually able to resolve hostnames of the services without .cluster.local

**Additional context / logs:**
```
root@rancher1sc:~# kubectl create -f ingress.yml
Error from server (InternalError): error when creating "ingress.yml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s: Unknown Host
root@rancher1sc:~# kubectl create -f clusterissuer.yml
Error from server (InternalError): error when creating "clusterissuer.yml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: Unknown Host
root@rancher1sc:~# kubectl exec -ti centos -- bash
[root@centos /]# nslookup cert-manager-webhook.cert-manager.svc
Server:         10.144.0.10
Address:        10.144.0.10#53

Name:   cert-manager-webhook.cert-manager.svc.cluster.local
Address: 10.144.180.174
```

**Comment by danielefranceschi** [comment]
I can confirm DNS problems with k3s `v1.19.3+k3s3 ` on CentOS7 and docker `19.3.13`:
```shell
$ kubectl run -n default -it --rm --restart=Never alpino --image=alpine:latest
If you don't see a command prompt, try pressing enter.
/ # nslookup kubernetes.default.svc.cluster.local
Server:         10.43.0.10
Address:        10.43.0.10:53
Name:   kubernetes.default.svc.cluster.local
Address: 10.43.0.1
```
resolves fqdn,
```
/ # nslookup kubernetes.default
Server:         10.43.0.10
Address:        10.43.0.10:53
** server can't find kubernetes.default: REFUSED
** server can't find kubernetes.default: REFUSED
```
does not resolve short names,
```
/ # nslookup vm.internal.COMPANY.COM
Server:         10.43.0.10
Address:        10.43.0.10:53
Name:   vm.internal.COMPANY.COM
Address: 172.16.10.129
```
resolves internal,
```
/ # nslookup -debug www.google.it
Server:         10.43.0.10
Address:        10.43.0.10:53
Query #0 completed in 2ms:
** server can't find www.google.it: REFUSED
Query #1 completed in 2ms:
** server can't find www.google.it: REFUSED
```
but does not resolve anything else.

Coredns log:
```
[INFO] 10.42.0.30:53796 - 17310 "A IN www.google.it. udp 31 false 512" REFUSED qr,rd,ra,ad 31 0.00103648s
[INFO] 10.42.0.30:53796 - 17597 "AAAA IN www.google.it. udp 31 false 512" REFUSED qr,rd,ra,ad 31 0.001312487s
```

**Comment by danielefranceschi** [comment]
I can confirm that this happens in k3s 1.19.3, 1.18.12, 1.18.9 (on centos7+docker)

**Comment by SASCloudLearner** [comment]
Hello, is there any update or advise on what can be done to fix this. we have similar issue in our k8 on premis cluster as well
