### ISSUE TITLE
Bump CoreDNS to v1.8.0

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2293]
Bump to ~v1.7.1~ 1.8.0 of CoreDNS

We were originally planning on an update to 1.7.1; however there is a bug upstream. Please see https://github.com/k3s-io/k3s/issues/2700#issuecomment-747605130

As such, for the 1.20 line of K3s it made the most sense for us to bump CoreDNS past the 1.7.x line and to 1.8.0.

**Comment by brandond** [comment]
I am expecting some failures from this as described at https://github.com/k3s-io/k3s/issues/2700#issuecomment-747605130

**Comment by davidnuzik** [comment]
Here is the PR for 1.8.0 bump: https://github.com/k3s-io/k3s/pull/2726

**Comment by rancher-max** [comment]
Validated in v1.20.0-rc5+k3s1 we are using coredns 1.8.0
Validated in v1.19.5+k3s2 we are using coredns 1.6.9

The issue as noted here previously is resolved in both of these versions.
