### ISSUE TITLE
disable kube-proxy

### ISSUE THREAD

**Issue by schmitch** [k3s-io/k3s#2296]
currently there is a way to use cilium without kube-proxy. it would be great if it would be possible to use k3s without kube-proxy at all.

https://docs.cilium.io/en/v1.8/gettingstarted/kubeproxy-free/

**Comment by marcbachmann** [comment]
This landed in https://github.com/k3s-io/k3s/pull/1695 
You can use it with`--disable-kube-proxy`

**Comment by onedr0p** [comment]
@davidnuzik this looks to be in the source, but not documented.

**Comment by davidnuzik** [comment]
@onedr0p I created https://github.com/rancher/docs/issues/3050 to track fixing the docs. Sorry for the delay in response and thanks for reporting!
