### ISSUE TITLE
k3s master with static pod etcd as datastore

### ISSUE THREAD

**Issue by raja-ashok** [k3s-io/k3s#2302]
Does a k3s master can be bring up with static pod `etcd` as datastore ? 

By placing a etcd's manifest file in `/path/to/staticpod/manifest/`, I am executing below cmd. But master is not coming up. 
```
./install.sh server --kubelet-arg="pod-manifest-path=/path/to/staticpod/manifest/ \
  --datastore-endpoint="https://<host_ip>:2379"
```

I looked into embedded etcd feature using `--cluter-init` option, which doesn't create static pod for etcd. I am looking for a cluster setup with db as static pod to k3s master.

**Comment by brandond** [comment]
You might look at RKE2 - it reuses much of the k3s core, but moves etcd, apiserver, into static pods. The k3s design requires the datastore to be available before the apiserver and kubelet start, so it cannot be used to host core infrastructure as static pods.

https://github.com/rancher/rke2/

Note that it's still very much a work in progress; we're hoping for an initial GA release soon.

**Comment by brandond** [comment]
This is what RKE2 does, and RKE2 is now GA.
