### ISSUE TITLE
Joining cluster with wrong password results in "500 Internal Server Error"

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2310]
**Environmental Info:**
K3s Version: 
k3s version v1.19.2+k3s-f698c8e7 (f698c8e7)

Node(s) CPU architecture, OS, and Version: 
 Linux centos02.lan.khaus 5.8.10-1.el7.elrepo.x86_64 rancher/k3s#1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 node managed etcd

**Describe the bug:**
Error message indicates server failure, not invalid authentication / bad token

**Steps To Reproduce:**
* start a k3s server with --cluster-init
* Copy token from /var/lib/rancher/k3s/server/token
* Attempt to join second k3s server with --server and --token, but omit the final character from the token string

**Expected behavior:**
Expect a 401 error or other message indicating invalid token/credentials.

**Actual behavior:**
Receive an error message indicating that something is wrong with the remote server:
```
FATA[2020-09-25T01:13:53.736998813-07:00] starting kubernetes: preparing server: https://centos01.lan.khaus:6443/v1-k3s/server-bootstrap: 500 Internal Server Error
```

The remote server does log something more useful:
```
ERRO[2020-09-25T01:23:42.135514724-07:00] Failed to authenticate request from 10.0.1.170:51946: invalid username/password combination
```

**Additional context / logs:**
Just returning a 401 would be fine, as that should prompt the user to confirm the token, instead of attempting to figure out what's wrong with the server they're trying to join.

According to RFCs:
* https://github.com/rancher/k3s/blob/master/pkg/server/auth.go#L40 should be http.StatusUnauthorized
    > If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials. 
* https://github.com/rancher/k3s/blob/master/pkg/server/auth.go#L45 should be http.StatusForbidden
    > The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.

**Comment by jandubois** [comment]
I ran into the same issue today when I extracted the token from a Docker container with:

```
TOKEN=$(docker exec -it k3s cat /var/lib/rancher/k3s/server/node-token)
```

The `-it` option replaces each `\n` in the output with `\r\n`, and the `\r` becomes part of `$TOKEN`, creating the same errors as described above. See also [Docker run/exec and carriage return](https://ddanilov.me/docker-run-exec-and-carriage-return/).

Improving the error message to point at a potentially invalid token would have helped.

I think additionally removing leading/trailing whitespace from the token would be even better; I would think that nobody would intentionally create a token manually that has whitespace in the front or back (or even inside, but that should obviously remain untouched).

**Comment by brandond** [comment]
Should now see something like:

```
Feb 09 17:10:10 centos02.lan.khaus k3s[4294]: time="2021-02-09T17:10:10.544420481-08:00" level=info msg="Running load balancer 127.0.0.1:33651 -> [centos01.lan.khaus:6443]"
Feb 09 17:10:10 centos02.lan.khaus k3s[4294]: time="2021-02-09T17:10:10.589242735-08:00" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
Feb 09 17:10:10 centos02.lan.khaus k3s[4294]: time="2021-02-09T17:10:10.599853079-08:00" level=error msg="Failed to retrieve agent config: https://127.0.0.1:33651/v1-k3s/config: 401 Unauthorized"
```

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 5749f66aa3c469b4c744caab1878c6967ac08041 on a two node cluster.

node1
```
$ k3s -v
k3s version v1.20.2+k3s-5749f66a (5749f66a)
go version go1.15.8

$ kubectl get nodes
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-31-24-212   Ready    control-plane,etcd,master   4m23s   v1.20.2+k3s-5749f66a
```
Joining node2 using the wrong token, logs show the below error msg. 
```
Feb 17 02:05:21 ip-172-31-25-157 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 02:05:21 ip-172-31-25-157 systemd[1]: k3s.service: Failed with result 'exit-code'.
Feb 17 02:05:21 ip-172-31-25-157 systemd[1]: Failed to start Lightweight Kubernetes.
Feb 17 02:05:26 ip-172-31-25-157 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 51.
Feb 17 02:05:26 ip-172-31-25-157 systemd[1]: Stopped Lightweight Kubernetes.
Feb 17 02:05:26 ip-172-31-25-157 systemd[1]: Starting Lightweight Kubernetes...
Feb 17 02:05:26 ip-172-31-25-157 k3s[3177]: time="2021-02-17T02:05:26.686981001Z" level=info msg="Starting k3s v1.20.2+k3s-5749f66a (5749f66a)"
Feb 17 02:05:26 ip-172-31-25-157 k3s[3177]: time="2021-02-17T02:05:26.736660922Z" level=info msg="Managed etcd cluster not yet initialized"
Feb 17 02:05:26 ip-172-31-25-157 k3s[3177]: time="2021-02-17T02:05:26.739920852Z" level=fatal msg="starting kubernetes: preparing server: https://<IP>:6443/v1-k3s/server-bootstrap: 401 Unauthorized"
```
