### ISSUE TITLE
k3s embedded etcd problem -- Peer URL's already exists

### ISSUE THREAD

**Issue by skmansfield** [k3s-io/k3s#2328]
I am having trouble buiding k3s using the new experimental ectd embedded store.  I execute this for my primary k3s server and it installs correctly showing ready and roles "etcd, master".  So far so good.

```sh
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="\
  --write-kubeconfig ~/.kube/config \
  --write-kubeconfig-mode 644 \
  --tls-san 52.142.5.234 \
  --cluster-init" \
  INSTALL_K3S_VERSION="v1.19.1+k3s1" \
  K3S_TOKEN="blah_blah_blah" sh - 
```

I try to start the second k3s server using this curl command,

```sh
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=" \
  --write-kubeconfig ~/.kube/config \
  --write-kubeconfig-mode 644 \
  --tls-san 20.185.1.154 \
  --server https://52.142.5.234:6443" \
  INSTALL_K3S_VERSION="v1.19.1+k3s1" \
  K3S_TOKEN="blah_blah_blah" \
  sh - 
``

 However fails to install k3s with etcd because of this error.  Looking through the journalctl -xe logs it seems to be squawking about this,

"level=fatal msg="starting kubernetes: preparing server: start cluster and https: joining etcd cluster: etcdserver: Peer URLs already exists"

Here is the total output of the error message.

Sep 30 12:50:48 skmk3smaster2 k3s[31460]: time="2020-09-30T12:50:48.422410805Z" level=info msg="Starting k3s v1.19.1+k3s1 (b66760fc)"
Sep 30 12:50:48 skmk3smaster2 k3s[31460]: time="2020-09-30T12:50:48.514135773Z" level=info msg="Adding https://10.0.0.5:2380 to etcd cluster [skmk3smaster2-dc93e533=https://10.0.0.5:2380 skmk3smaster1-bdc49cec=https://10.0.0.4:2380]"
Sep 30 12:50:48 skmk3smaster2 k3s[31460]: {"level":"warn","ts":"2020-09-30T12:50:48.516Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-8495ba6f-12cd-4735-8e13-162b834f6588/10.0.0.4:2379","attempt":0,"error":"rpc error: code
Sep 30 12:50:48 skmk3smaster2 k3s[31460]: time="2020-09-30T12:50:48.516753098Z" level=fatal msg="starting kubernetes: preparing server: start cluster and https: joining etcd cluster: etcdserver: Peer URLs already exists"
Sep 30 12:50:48 skmk3smaster2 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 12:50:48 skmk3smaster2 systemd[1]: k3s.service: Failed with result 'exit-code'.
Sep 30 12:50:48 skmk3smaster2 systemd[1]: Failed to start Lightweight Kubernetes.

Any help is welcome

My environment is,

Platform: Azure Ubuntu 18.04 LTS VM's
Cluster: 3x3 -- 3 servers and 3 agents
Ports open: 6443, 443, 2376, 2379, and 2380

**Comment by brandond** [comment]
Can you go back and find the very start of the k3s logs on skmk3smaster2? The error indicates that it is already added to the cluster, but it is still trying to add itself, so it must have crashed, been cancelled partway through, or had someone delete the local data.

You can reset the cluster membership by stopping the service on skmk3smaster1, running `k3s server --cluster-reset`, then joining skmk3smaster2 again.

**Comment by brandond** [comment]
@skmansfield any information you can provide about how this was caused would be helpful. In addition to the logs, can you also provide the output of the following on skmk3smaster2 before you join it to the cluster again:

```
find /var/lib/rancher/k3s/server/db/
cat /var/lib/rancher/k3s/server/db/etcd/config
```

**Comment by skmansfield** [comment]
Hello Brandon,

I was worked with one of your colleague at Rancher and he helped me figure out the problem.  I am integrating the new embedded etcd storage and discovered that I had to install the latest version of k3s, v1.19.2+k3s1.  If you look at my k3s install script you will find that I used INSTALL_K3S_VERSION="v1.19.1+k3s1".  I had some problems with the script and during debug I tried INSTALL_K3S_CHANNEL=latest.  What we discovered was that INSTALL_K3S_Channel has its own delete command, k3s-channel-uninstall.sh.  I did not know this and used k3s-uninstall.sh.  k3s-uninstall.sh does not delete all of the k3s CHANNEL deployment files and directories.  It apparently left a few directories used by etcd to determine the name and ip address of the other servers.  When I re-installed INSTALL_K3S_VERSION="v1.19.1+k3s1" on the first server node the k3s manager found those files and started to try and connect to a second server that was deleted earlier.  It just hung forever trying to connect.  When I installed the second server it could not connect to the first server.  I uninstalled both servers and issued a rm -rf "/var/lib/rancher/k3s/ and deleted all of the directories manually.  After doing this INSTALL_K3S_VERSION="v1.19.1+k3s1" installed fine and all 3 servers were able to connect correctly.  You should highlight in your documentation the different uninstall commands.

**Comment by brandond** [comment]
I'm unfamiliar with the `k3s-channel-uninstall.sh` script, can you tell me more about that? Here's what I see when installing using the channel:

```
[root@centos01 ~]# curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 644 --tls-san 52.142.5.234 --cluster-init"   INSTALL_K3S_CHANNEL="latest"   K3S_TOKEN="blah_blah_blah" sh -
[INFO]  Finding release for channel latest
[INFO]  Using v1.19.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink from /etc/systemd/system/multi-user.target.wants/k3s.service to /etc/systemd/system/k3s.service.

**Comment by alexellis** [comment]
I have this issue also and uninstalling did nothing to help, likewise removing the node password on the primary server

```
Oct 21 12:44:10 1befbd15 k3s[12085]: time="2020-10-21T12:44:10.992050262+01:00" level=info msg="Starting k3s v1.19.3+k3s1 (974ad30b)"
Oct 21 12:44:11 1befbd15 k3s[12085]: time="2020-10-21T12:44:11.360666069+01:00" level=info msg="Adding https://192.168.2.123:2380 to etcd cluster [7feb56e7-84575992=https://192.168.2.147:2380 1b9a8834-ab283639=https://192.1
Oct 21 12:44:11 1befbd15 k3s[12085]: {"level":"warn","ts":"2020-10-21T12:44:11.381+0100","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-26e2fa43-257b-4592-8c
Oct 21 12:44:11 1befbd15 k3s[12085]: time="2020-10-21T12:44:11.381610846+01:00" level=fatal msg="starting kubernetes: preparing server: start cluster and https: joining etcd cluster: etcdserver: Peer URLs already exists"
Oct 21 12:44:11 1befbd15 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by alexellis** [comment]
This is a really surprising behaviour, that you can't change a node's role, from agent to server.

The trace goes back to this line: 
https://github.com/rancher/k3s/blob/373449ec0ab62248eb3c3a1d290a1d8e65df135c/pkg/etcd/etcd.go#L269
