### ISSUE TITLE
http2: panic serving 10.10.100.24:47945: runtime error: slice bounds out of range [:832] with capacity 71

### ISSUE THREAD

**Issue by josefcub** [k3s-io/k3s#2331]
**Environmental Info:**
K3s Version: 
k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 
Linux kworker1 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
$ cat /etc/debian_version
10.6

Cluster Configuration:
Raspberry Pi 4 4GB, 2 masters on external mariadb, 8 workers.

**Describe the bug:**
The logs contain an abundance of:

I1001 19:28:23.412729   12048 log.go:172] http2: panic serving 10.10.100.24:13964: runtime error: slice bounds out of range [:832] with capacity 71

The '71' after capacity changes occasionally to other values.  This is occurring mostly on the masters, but it occasionally happens on a worker as well.  prometheus-operator and Grafana register only 95% of nodes are up at any given time (I have ten nodes.  How can one-half of one kubelet be down?  Grafana math errors are out of scope I suspect).  This occurs on a fresh reinstall of the entire cluster as well as in its current configuration.

**Steps To Reproduce:**

Install k3s with external MariaDB masters on aarch64.  Observe logs.  To keep the cluster busy, install prometheus-operator, though I have also observed this on the cluster when nothing was installed.

- Installed K3s: 

 curl -sfL https://get.k3s.io | sh -s - server   --datastore-endpoint="mysql://nunya@tcp(db:3306)/k3s"

**Expected behavior:**
I would expect to not see this in the log.

**Actual behavior:**
~80 of the above messages per hour.

**Additional context / logs:**
I'll provide any other logs/data points on request.

**Comment by brandond** [comment]
Is it always that same IP address listed in the error? I believe it should print a stack trace after that error, can you you share that if so?

**Comment by josefcub** [comment]
> Is it always that same IP address listed in the error? I believe it should print a stack trace after that error, can you you share that if so?

Unfortunately, the log entries show the address of whichever node the occurrence happens on.  This is mostly just my two masters, at 10.10.100.20 and 10.10.100.21, though as above sometimes other nodes will throw the same error.  I've attached a set of logs, with the error and (what I hope is) a complete stack trace found after the error. 

Thank you for taking a look!

[stack.txt](https://github.com/rancher/k3s/files/5318005/stack.txt)

**Comment by brandond** [comment]
This seems to be occurring somewhere deep in the kubelet's bearer token auth handling:
```
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache.writeLengthPrefixedString(0x7fac907948, 0x401a7fcc60, 0x401519d740, 0x4, 0x4, 0x4016a18807, 0x3a8)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:219 +0x84
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache.keyFunc(0x4017d94fc0, 0x0, 0x0, 0x0, 0x4016a18807, 0x3a8, 0x211, 0x361fb80)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:201 +0xc4
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache.(*cachedTokenAuthenticator).AuthenticateToken(0x4003de6500, 0x429a040, 0x40191855c0, 0x4016a18807, 0x3a8, 0x0, 0x4002ad7200, 0x0, 0x0)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:116 +0xcc
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/request/bearertoken.(*Authenticator).AuthenticateRequest(0x401782f810, 0x401b8c1f00, 0x0, 0x500, 0x0, 0x0)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/request/bearertoken/bearertoken.go:54 +0xf4
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/request/union.(*unionAuthRequestHandler).AuthenticateRequest(0x4017c811c0, 0x401b8c1f00, 0x40032b5748, 0x40c2ec, 0x40032b5738, 0x449a8c)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/request/union/union.go:56 +0x90
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/group.(*AuthenticatedGroupAdder).AuthenticateRequest(0x401782f830, 0x401b8c1f00, 0x40032b57ad, 0x817a08, 0x2, 0x40032b5790)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go:40 +0x3c
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0x40191856b0, 0x4019fbac40, 0x4019185620)
#011/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go:251 +0x4c
```

I remember running into this once on one of my dev instances, I believe I eventually tracked it down to something left over from an old cluster - it was either another server that had previously been part of the cluster still trying to connect, or a pod still running on that server, or something like that. It was using an bearer token that was not valid for the current cluster, and somehow this can cause a crash in the right circumstances.

It was really difficult to figure out because the error message doesn't really give you anything useful. I ended up recompiling with some additional details in the error, like the URL that had been requested, and tracked that back to the client that would have been accessing that resource.

**Comment by erikwilson** [comment]
For finding a root cause the top part should be the most relevant part:
```
Oct  2 07:41:02 kmaster1 k3s[5868]: I1002 07:41:02.902434    5868 log.go:172] http2: panic serving 10.10.100.24:50330: runtime error: slice bounds out of range [:832] with capacity 71
Oct  2 07:41:02 kmaster1 k3s[5868]: goroutine 7322995 [running]:
Oct  2 07:41:02 kmaster1 k3s[5868]: net/http.(*http2serverConn).runHandler.func1(0x400bc07928, 0x4004fd7f58, 0x401b944180)
Oct  2 07:41:02 kmaster1 k3s[5868]: #011/usr/local/go/src/net/http/h2_bundle.go:5706 +0x128
Oct  2 07:41:02 kmaster1 k3s[5868]: panic(0x35e4ee0, 0x401051ad60)
Oct  2 07:41:02 kmaster1 k3s[5868]: #011/usr/local/go/src/runtime/panic.go:679 +0x194
Oct  2 07:41:02 kmaster1 k3s[5868]: crypto/sha256.(*digest).Write(0x4011456200, 0x4016a18807, 0x3a8, 0x83, 0x4, 0x0, 0x0)
Oct  2 07:41:02 kmaster1 k3s[5868]: #011/usr/local/go/src/crypto/sha256/sha256.go:198 +0x200
Oct  2 07:41:02 kmaster1 k3s[5868]: crypto/hmac.(*hmac).Write(0x401a7fcc60, 0x4016a18807, 0x3a8, 0x83, 0x4, 0x3a8, 0x3324620)
Oct  2 07:41:02 kmaster1 k3s[5868]: #011/usr/local/go/src/crypto/hmac/hmac.go:54 +0x4c
```

In that the http interaction is abstracted away to where k8s shouldn't be able to trigger a panic like this. It seems like a bug with golang net/http, doing a search for that error turns up a common issue with using MySQL authentication without a password, not sure if related. Am a little surprised not to see Kine in the stack, so may not be related.

Are you able to reproduce with v1.19?

The other part of this is that the `arm` builds of k3s have never been particularly stable, it passes some basic sanity checks but we have had to work through a lot of random panics that do not seem to be at all related to what is happening, and a small insignificant code change can make the error go away. Would also try with `arm64`, that should be much more stable.

**Comment by brandond** [comment]
@erikwilson there's something in the bearer token auth path that triggers this when the token is invalid. It looks like he's already on arm64, which is where I saw it as well - so this may come down to an issue with platform-specific crypto code.

**Comment by erikwilson** [comment]
Yah, that is the path that triggers the panic, but if the crypto code is breaking on arm64 that is probably a golang issue that should be addressed. k3s v1.19 uses go 1.15 which may give a better result.

**Comment by brandond** [comment]
Yes, that was where I landed as well. I didn't have time to chase down the root cause, I just got rid of the thing that was causing it by sending invalid tokens.

**Comment by erikwilson** [comment]
Looks like the last k8s call is here: https://github.com/kubernetes/apiserver/blob/release-1.18/pkg/authentication/token/cache/cached_token_authenticator.go#L220

Which we can see is trying to write to the crypto hash. The sha256 code tries to chunk out blocks here: https://github.com/golang/go/blob/release-branch.go1.13/src/crypto/sha256/sha256.go#L198

It looks like that fails calculating a wrong `n` value before going into the platform specific block code. My guess is that the bit-wise operation is using different size types and somehow that is causing the problem. So not net/http related, that is just bubbling up the error, but does look like crypto somehow. Unfortunately I am not seeing any changes which would likely fix this.

**Comment by josefcub** [comment]
I took the advice from @erikwilson and upgraded the cluster to the latest arm64 release (k3s version v1.19.2+k3s1 (d38505b1)) and the problem has been greatly reduced (from many per hour, to a mere handful).  I've included an example latest stack trace here, though it looks substantially similar to the first one I attached.

If there's any chance that the old-version cluster data may be causing these new instances to pop up, I'll be quite happy to fully uninstall k3s on all nodes, wipe the kine table on mariadb, and start over with the new k3s binary.

[stack.txt](https://github.com/rancher/k3s/files/5320885/stack.txt)

Thank you all!

**Comment by brandond** [comment]
Do you by any chance have devices in the cluster, or accessing the cluster, that have not seen a reboot since the cluster was most recently configured or upgraded? You might try a rolling reboot of your environment to ensure that there's not anything left over hiding away somewhere.

**Comment by josefcub** [comment]
I have now ensured everything short of the internet was rebooted.  Unfortunately, there's no change and those errors are still occurring, although thankfully less frequently than originally stated.

**Comment by erikwilson** [comment]
Hmmm, would you happen to have swap enabled? If so should be off, still wouldn't expect that error tho.

The new stack is complaining about `capacity 4`. That sha256 line is looking for a length greater than a chunk size of 64, so would expect the capacity to be at least that size. Might have something to do with k8s use of `unsafe.Pointer` in `toBytes`.
By chance are you able to reproduce on x86_64?

**Comment by josefcub** [comment]
I can definitely confirm that I do not have swap enabled anywhere near the cluster.  

Unfortunately, I don't have the ability to spin up an x86_64 cluster at this time, sorry.

**Comment by erikwilson** [comment]
Cool, thanks for the info!
No worries, was thinking maybe just attach a single x86_64 worker to the existing cluster.
Not sure where to go from here, if we should keep digging into it & try to repro, or file an issue in k8s, or an issue with golang.

**Comment by josefcub** [comment]
Just as an update, I managed to stand up a Debian 10 64-bit VM with k3s at the same version, and I did NOT observe this issue occurring on that platform.
