### ISSUE TITLE
[Question]: How to generate the external IP of the node of k3s cluster?

### ISSUE THREAD

**Issue by Imboncy** [k3s-io/k3s#2336]
## Details

- I wanted to use the k3s cluster as part of GitLab CI for which I need to connent the cluster to GitLab which needs an external IP.
In configuration file the server IP is on localhost how to generate an external IP to use the cluster from outside / connet to CI?

GitLab CI:

![Screenshot from 2020-10-03 14-25-41](https://user-images.githubusercontent.com/67638533/94987493-6d269880-0584-11eb-8c99-c8468bb21d73.png)

Configuration file:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: XXX
    username: admin
```

```bash
$ kubectl get nodes -o wide

NAME             STATUS   ROLES    AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
ip-172-31-8-50   Ready    master   45m   v1.18.9+k3s1   172.31.8.50   <none>        Ubuntu 18.04.5 LTS   5.3.0-1035-aws   containerd://1.3.3-k3s2
```

**Comment by a01fe** [comment]
You're running k3s and GitLab on the same host? You can use the host's IP address.

**Comment by sharmababu** [comment]
Thanks, @a01fe for responding. I don't think it is on the same host as I'm
using GitLab default runner for running the jobs and adding this k3s
cluster which is present in a VM separately. Is there a way to generate the
external IP of the node I'm using?

**Comment by a01fe** [comment]
You can use the IP address of the host running k3s server.

**Comment by louiznk** [comment]
@sharmababu your gitlab is in the cluster ? in this case you could use the url of the API service https://kubernetes.default:443

**Comment by brandond** [comment]
https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#agent-networking

Is `--node-external-ip` what you're looking for?

**Comment by uditgaurav** [comment]
Faced similar issue
It’s the URL that GitLab uses to access the Kubernetes API. Kubernetes exposes several APIs, GitLab wants the “base” URL that is common to all of them. @a01fe @sharmababu 

we can get the URL though:
`kubectl cluster-info | grep 'Kubernetes master' | awk '/http/ {print $NF}'`

Not sure why but @brandond using `node-external-ip` also gives the same local URL.

**Comment by poblin-orange** [comment]
Probablement better to define an alias for the k3s Master (corporate dns or /etc/hosts) and adding --tls-san so k3s generates appropriation certificates?
