### ISSUE TITLE
Custom Wireguard port for Flannel

### ISSUE THREAD

**Issue by stevefan1999-personal** [k3s-io/k3s#2343]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
I have multiple instances of k3s running on a same machine but segregated via virtualization. However as I'm behind NAT I can only have one 51820 port. I want my other instances to run on 51821, 51822...etc

Combining this with `advertise-port` with port forwarding at L3, we can run multiple k3s exposed on the internet at home.

**Describe the solution you'd like**
Just let us set a new option `--flannel-backend-port` where the defaults are the default of each backend, e.g. 4789 for VXLAN, 51820 for Wireguard. When this option is set the backend port is _forced_ to use that port.

**Comment by stevefan1999-personal** [comment]
https://github.com/rancher/k3s/blob/ba70c41cce76fcae70867754cdf390501a8cef1b/pkg/agent/flannel/setup.go#L65-L67

you can see they are fixed, this is not good.

**Comment by mschneider82** [comment]
I tried to solve it, but it doesnt really work. because it seems that all wireguard servers needs the same port. When changing the port in the "SubnetAddCommand" line, it tries to connect to remote 51821  instead of 51820. I have linked my commit branch, if someone wants to continue
