### ISSUE TITLE
Pods can't find each other (Raspberry Pi + k3s + gRPC)

### ISSUE THREAD

**Issue by jazzsaxmafia** [k3s-io/k3s#2344]
Hello team, I am trying to run gRPC on my small Kubernetes cluster made of Raspberry pis. The source code is located here: https://github.com/jazzsaxmafia/productinfo (based on [this](https://github.com/grpc-up-and-running/samples))

**Environmental Info:**
K3s Version: k3s version v1.18.9+k3s1 (630bebf9)

```
(base) taeksoo@taeksoo-X399-AORUS-PRO:~/Development/Practice/productinfo$ kubectl get nodes
NAME      STATUS   ROLES    AGE     VERSION
kmaster   Ready    master   4d10h   v1.18.9+k3s1
knode1    Ready    <none>   4d10h   v1.18.9+k3s1
```

Node(s) CPU architecture, OS, and Version:  Arm v7 (Raspberry Pi 4) with Raspbian Lite (32bite)

Cluster Configuration: 1 master, 1 worker

**Describe the bug:** I am launching a gRPC server (+service) and a client using Kubernetes. The server seems to be running fine
```
(base) $:~/Development/Practice/productinfo$ kubectl get deployment
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
grpc-productinfo-server   1/1     1            1           15h
```

```
(base) $:~/Development/Practice/productinfo$ kubectl get svc
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
kubernetes    ClusterIP   10.43.0.1       <none>        443/TCP           3d21h
productinfo   NodePort    10.43.159.192   <none>        50051:30378/TCP   15
```

```
(base) $:~/Development/Practice/productinfo$ kubectl logs -f grpc-productinfo-server-58b49d5967-sxcfc
2020/10/04 22:13:33 server listening at port :50051
```

However, when I launch the client, this is what I am getting:
```
(base) $:~/Development/Practice/productinfo$ kubectl logs -f grpc-productinfo-client-vzmsz
2020/10/05 13:53:04 Could not add product: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"
```

**Steps To Reproduce:**

- Installed K3s: 
```
curl -sfL https://get.k3s.io | sh - // master

export K3S_URL="{server ip:port}"
export K3S_TOKEN="{token}"
curl -sfL [https://get.k3s.io](https://get.k3s.io/) | sh -
```

**Expected behavior:** The client receiving an immediate result.

**Actual behavior:** Receiving a timeout error

**Additional context / logs:**

**Comment by brandond** [comment]
I am not sure what the current state of 32bit raspbian is, but have you tried disabling firewalld/ufw and enable iptables legacy mode?
