### ISSUE TITLE
[Question]: Do i need a virtual IP for server nodes when using HA mode?

### ISSUE THREAD

**Issue by deciojr** [k3s-io/k3s#2354]
I'm experimenting with k8s and tried out their HA mode with kubeadm ([Reference](https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md)). Then i discovered k3s and started to play with k3s' HA mode (the one with embedded ectd), but the docs do not mention anything related to this. So i would just like some insight in this topic, if it is needed or not, or when would i need it.

**Comment by runningman84** [comment]
I suppose you need some kind of virtual ip or loadbalancer because the agent tries to connect to a master server. In the docs the first server is mentioned which could be offline which would lead to node not registering... 

I also wonder if remaining master nodes would survice an outage of the first master server.

**Comment by brandond** [comment]
That is covered in the docs here: https://rancher.com/docs/k3s/latest/en/installation/ha/

> A fixed registration address that is placed in front of the server nodes to allow agent nodes to register with the cluster
> For more details on how these components work together, refer to the architecture section.
> 
> Agents register through the fixed registration address, but after registration they establish a connection directly to one of the server nodes. This is a websocket connection initiated by the k3s agent process and it is maintained by a client-side load balancer running as part of the agent process.

This could be as simple as a DNS alias that points at your servers, an external load balancer, etc.
