### ISSUE TITLE
[Documentation] Context label needs to be set on the dir used by local-path-provisioner

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#2357]
Issue: ProvisioningFailed without context label on dir. PVC, Pod will be in pending state

By default local-path-provisioner is not deployed with rke2. The dir used by local-path-provisioner needs to have the context label set. 
Command used to set the label on the default dir.
```
chcon -t container_file_t -R /opt/local-path-provisioner
```

**Comment by dereknola** [comment]
This was fixed at some point in selinux, and pvc come up just fine. No documentation change is necessary.
```
[root@smoke vagrant]# k3s kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
volume-test   1/1     Running   0          82s
```
```
system_u:system_r:container_t:s0:c744,c913 root 8642 0.0  1.9 733716 35700 ?     Ssl  21:31   0:01 local-path-provisioner start --config /etc/config/config.json
```
