### ISSUE TITLE
How does k3s deal with node with IP leased by DHCP?

### ISSUE THREAD

**Issue by kahou82** [k3s-io/k3s#2360]
**Environmental Info:**
K3s Version: 
k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 
Ubuntu 18.04

Cluster Configuration:
1 nodes 
k3s.sh --docker

**Describe the bug:**
I have a one node server running with k3s. Everything runs fine and the node IP address is leased by a DHCP server. The problems surface up when I reboot my node that get a new IP address.

kubernetes will treat the cluster having two nodes (one with the new IP address and one with the old IP address) and the workload will stick to the old node that are waiting for timeout.

The cause the workload to have major outage as we have to wait for k8s to evict the workload to the new node.

Can you shed some light on how to deal with this situation?

**Steps To Reproduce:**
1. Create an one node ubuntu, IP is leased by DHCP
2. Install k3s
3. Deploy some workloads
4. Reboot the node
5. Node comes with new IP address
6. Workload stays pending until timeout and the workload will be evicted

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Are you unable to give your k3s node a reservation in your DHCP server, or configure a static IP address instead of using DHCP?

**Comment by dweomer** [comment]
Our K3s docs do not mention this explicitly but it is captured in the [Rancher 2.x Docs](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#node-ip-addresses):
> Each node used should have a static IP configured, regardless of whether you are installing Rancher on a single node or on an HA cluster. In case of DHCP, each node should have a DHCP reservation to make sure the node gets the same IP allocated.

**Comment by retr0h** [comment]
@brandond @dweomer a follow up to this question would be, how would one use k3s baked into an amazon AMI for example?  When building an AMI packer/etc would install k3s, install manifests, then save the ami for future use.

K3s would be configured to run on an IP address that is no longer valid.  I am trying to prevent the install of crio/docker/k3s  and k8s manifests during boot via cloud-init as that seems less than ideal.

**Comment by brandond** [comment]
Don't start k3s before imaging the node. If you must, you should stop it and delete all the cluster data - including the datastore and certificates - before imaging.

**Comment by retr0h** [comment]
@brandond could you provide a few more details on how to accomplish this.  Appreciate it.
