### ISSUE TITLE
Migrate k3s.io website to CNCF owned neutral organization

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2362]
**My understanding as per the website guidelines is that this is migration is not strictly required. However, we still want this to happen. The website is an important part to K3s and should get migrated.** CNCF already owns the domain, we just haven't moved the project yet :)

While the k3s.io [website is open](https://github.com/rancherlabs/k3s-website) and can be updated today, and while there doesn't appear to be any requirement to move the website itself to a CNCF owned neutral organization, I would still like to transfer the project over to k3s-io so its in a more logical place and thus easier for the community to make any necessary updates.

This will involve transferring the https://github.com/rancherlabs/k3s-website project over to https://github.com/k3s-io/k3s-website

**Comment by davidnuzik** [comment]
Linking as related to https://github.com/rancher/k3s/issues/2189 effort.

**Comment by fapatel1** [comment]
Per @cjellick follow the pattern for website that other OSS projects are using

**Comment by cwayne18** [comment]
We've done this on our end, just waiting on DNS now
