### ISSUE TITLE
Testing HA failover on hard power off of a master node - "ghost" workloads not failing over

### ISSUE THREAD

**Issue by bodleytunes** [k3s-io/k3s#2366]
Hi All,

Versions are 1.18 stable all round.  Using external postgres DB in a VM

Not sure if this is K3S , Kubernetes or even DB related.

Have a 3 node test cluster, 3 masters, 2 of which are running workloads and the 3rd is set for "noexecute"

I also have it connecting to a postgres VM which resides on the same host as one of the masters ( I know this is terrible terrible design but its a home baked test ).

I wanted to test hard power off failure, so shutdown (hard poweroff) the VM host running one of the masters and the DB.

The DB fails over to the other master host without issue as I planned for.

Connections I see start coming into the db and everything _looks_ normal

Kubectl get nodes shows the particular master is notready  which is expected.

However, kubectl get pods --all-namespaces is showing the pods "RUNNING" on the dead node still even though its hard down?  I wait and wait even though I've set a low timeout (10s)

This means now that kube isn't failing services across to the node that is still alive, resulting in basically dead services.  No rancher page (404 on login), no workloads.

I'm sure it's not supposed to act like this so I assume its something wrong with my configuration or design?  Could it be a problem with the DB, some how in a locked/frozen read-only state because of the hard failure?  Pgadmin is showing connections and usually when there is a DB issue I see everything grind to a halt there or I can't connect to pgadmin at all. 

I'm pretty sure when I used the built in etcd clustering it seemed to fail the services over on its own?  But etcd seems a bit less robust at the moment.

Is there something else you need to do if using a fixed external DB to allow the other nodes to form quorum and know when their peer is down so they can take the services from the dead node?

Sorry for the dumb questions, still in the learning phase, but thoroughly enjoying!

Cheers,
Jon.

**Comment by bodleytunes** [comment]
Update: 
It seems a reboot of the still alive node as forced it to spin up the services on itself, fixing the issues.  Seems a bit drastic to have to reboot the still alive node though?

**Comment by brandond** [comment]
Please see the discussion of Kubernetes behavior around pod eviction for NotReady nodes:

https://github.com/rancher/k3s/issues/1264#issuecomment-571233958

**Comment by bodleytunes** [comment]
Hi Brandon,

Thanks for the reply.

I think I saw that thread earlier today during manic googling sessions, but I couldn't make out what the outcome was? Is it kubernetes design that it doesn't failover the pods automatically if a node's power is pulled / hard failure?  If so that doesn't sound like "hands off" HA if I have to manually intervene.
Surely some quorum should be formed so 2 nodes know if a 3rd is gone? Proxmox manages it fine with corosync and has for years.
Maybe I'm missing something? 
or is it the fact that this is just not designed for workloads that should failover, and they should be alive on all nodes and be stateless / fronted by the LB, which is all well and good in the world of web services I suppose?  It kind of limits the uses though.  I was hoping I could move away from VM's :( 

Cheers!  
Jon.
