### ISSUE TITLE
Master failing to join cluster - TLS handshake error: bad certificate

### ISSUE THREAD

**Issue by BeardyC** [k3s-io/k3s#2369]
K3s Version: 
```k3s version v1.17.2+k3s1 (cdab19b0)```

Node(s) CPU architecture, OS, and Version: 
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
4 masters, 8 agents

**Describe the bug:**
Master node dropped from the cluster and is unable to rejoin due to certificate issues.

**Steps To Reproduce:**
Running airgap installation with the below service file

```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/opt/app/mdx/MdxCache1/k3s/bin/k3s \
    server \
        '--data-dir' \
        '/opt/app/mdx/MdxCache1/k3s-data' \
        '--datastore-endpoint' \
        'https://...:2379,https://...:2379,https://...:2379,https://....:2379,https://....:2379' \
        '--datastore-cafile' \
        '/opt/app/mdx/MdxCache1/k3s/etcd/ca.crt' \
        '--datastore-certfile' \
        '/opt/app/mdx/MdxCache1/k3s/etcd/etcd-server.crt' \
        '--datastore-keyfile' \
        '/opt/app/mdx/MdxCache1/k3s/etcd/etcd-server.key' \
        '--tls-san' \
        'KUBERNETES-CA' \

```

- Installed K3s: 

**Expected behavior:**
Master node should join the cluster

**Actual behavior:**
Master failed to join the cluster with ```http: TLS handshake error from 127.0.0.1:40404: remote error: tls: bad certificate```

**Additional context / logs:**

```Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.342762701+01:00" level=info msg="To join node to cluster: k3s agent -s https://...:6443 -t ${NODE_TOKEN}"
Oct 06 17:06:00 lonrs13760 k3s[12866]: http: TLS handshake error from 127.0.0.1:40396: remote error: tls: bad certificate
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382530597+01:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382558967+01:00" level=info msg="Run: k3s kubectl"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382571906+01:00" level=info msg="k3s is up and running"
Oct 06 17:06:00 lonrs13760 systemd[1]: Started Lightweight Kubernetes.
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382810224+01:00" level=info msg="module overlay was already loaded"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382836321+01:00" level=info msg="module nf_conntrack was already loaded"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.382851414+01:00" level=info msg="module br_netfilter was already loaded"
Oct 06 17:06:00 lonrs13760 k3s[12866]: I1006 17:06:00.385210   12866 controller.go:606] quota admission added evaluator for: addons.k3s.cattle.io
Oct 06 17:06:00 lonrs13760 k3s[12866]: http: TLS handshake error from 127.0.0.1:40404: remote error: tls: bad certificate
Oct 06 17:06:00 lonrs13760 k3s[12866]: http: TLS handshake error from 127.0.0.1:40410: remote error: tls: bad certificate
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.418355513+01:00" level=info msg="Using registry config file at /etc/rancher/k3s/registries.yaml"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.421453594+01:00" level=info msg="Logging containerd to /opt/app/mdx/MdxCache1/k3s-data/agent/containerd/containerd.log"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.421624206+01:00" level=info msg="Running containerd -c /opt/app/mdx/MdxCache1/k3s-data/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /opt/app/mdx/MdxCache1/k3s-data/agent/containerd"
Oct 06 17:06:00 lonrs13760 k3s[12866]: time="2020-10-06T17:06:00.421784727+01:00" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""
 ```

Have tried removing the certs from ```/opt/app/mdx/MdxCache1/k3s-data/server/tls``` and deleting ```/api/v1/namespaces/kube-system/secrets/k3s-serving``` secret to regenerate new certificates and restarting but no improvement.

**Comment by brandond** [comment]
You don't appear to be supplying the `--token` to joining servers - are you doing this via the environment file, or some other means?

**Comment by brandond** [comment]
Yes, but you still need a token as it is used to encrypt/decrypt the bootstrap data, which includes the CA certificates:

https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#cluster-options
https://github.com/rancher/k3s/blob/master/pkg/cluster/storage.go#L31

**Comment by BeardyC** [comment]
Just to clarify, this a master node which disconnected from the cluster and is attempting to rejoin. We've never used the token when installing the master nodes since they connect to the data store to get the shared secret. 
Will try passing in the token at service start.
I've attempted to remove all the certificates in ```k3s-data/server/tls``` folder so it would regenerate new ones on starting the service with no luck. Have also forced regeneration of the k3s-serving secret but that didn't help either.

**Comment by BeardyC** [comment]
I tried adding the token when spinning up the master but had no luck with that. 
Tied removing the node from the cluster via ```kubectl delete node ``` and reinstalling which also did allow the node to join the cluster with certificate issues. 
In the end I ended up deleting all under ```k3s-data/server/cred/``` and ```k3s-data/server/tls``` which I saw were not being cleaned up via the uninstall script. 

Can I get a bit more insight on what exactly is in the cred folder, more specifically the below
```
ipsec.psk
node-passwd
passwd
```
I understand that ```k3s-serving``` secret is used to create everything in the tls folder, which then those certificates are used in the kubeconfig for each of the services.  But I'm not entirely sure how the above files fit into this.

**Comment by gynter** [comment]
I have same issue when trying to connect k3s server to etcd. 

It's worth noting, that CA, certificate and key are correct, because I'm able connect to etcd using wget and openssl:
```
wget \
--ca-certificate=etcd_ca_bundle.crt \
--certificate=master1_client.crt \
--private-key=master1_client.key \
-O - https://etcd1:2379/metrics

openssl s_client -showcerts \
-connect etcd1:2379 \
-CAfile etcd_client_ca_bundle.crt \
-cert master1_client.crt \
-key master1_client.key
```

Both of those work fine for me.

My CA chain is like this: `Root CA -> Client CA -> etcd1 & master1` certificates. The `etcd_client_ca_bundle.crt` consists of Root CA and Client CA.

**Comment by brandond** [comment]
K3s does not use the Kubernetes verbosity flags - can you try `k3s --debug server` or setting the K3S_DEBUG=1 environment variable?

**Comment by gynter** [comment]
@brandond Yes I'm sure because there are no issues when using wget and OpenSSL. I have also tried illegal certificates just to test what happens if I supply wrong CA or certificate. Then I get error from wget and OpenSSL as I should. Both of those tests confirm that certificate chain is correct. The only thing which I could currently think of is that I'm using ECC certificates and k3s fails to deal with that.

I'm already using `--debug`flag. Commands are as follows:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START="true" sh -s -

sudo /usr/local/bin/k3s \
--debug \
server \
-v=3 \
--log=/srv/k3s/log/k3s.log \
--data-dir=/srv/k3s/data/ \
--alsologtostderr \
--node-taint CriticalAddonsOnly=true:NoExecute \
--tls-san="api.kube" \
--datastore-endpoint="https://etcd1:2379,https://etcd2:2379" \
--datastore-cafile="/srv/k3s/ssl/etcd_client_ca_bundle.crt" \
--datastore-certfile="/srv/k3s/ssl/master1_client.crt" \
--datastore-keyfile="/srv/k3s/ssl/master1_client.key"
```

Output from terminal:
```
INFO[0000] Preparing data dir /srv/k3s/data/data/688c8ca42a6cd0c042322efea271d6f3849d3de17c850739b0da2461f6c69ee8 
DEBU[0002] Running /srv/k3s/data/data/688c8ca42a6cd0c042322efea271d6f3849d3de17c850739b0da2461f6c69ee8/bin/k3s-server [/usr/local/bin/k3s --debug server -v=3 --log=/srv/k3s/log/k3s.log --data-dir=/srv/k3s/data/ --alsologtostderr --node-taint CriticalAddonsOnly=true:NoExecute --tls-san=api.kube --datastore-endpoint=https://etcd1:2379,https://etcd2:2379 --datastore-cafile=/srv/k3s/ssl/etcd_client_ca_bundle.crt --datastore-certfile=/srv/k3s/ssl/master1_client.crt --datastore-keyfile=/srv/k3s/ssl/master1_client.key] 
time="2020-10-15T12:10:49.439802664+03:00" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
```

And then it just goes to etcd connection loop. From etcd side:
```2020-10-15T12:10:58.453844+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:10:58.453+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47230","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:11:04.470810+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:11:04.470+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47246","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:11:13.182322+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:11:13.181+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47250","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:11:28.817367+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:11:28.816+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47254","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:11:59.561427+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:11:59.560+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47272","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:12:46.740392+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:12:46.739+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47302","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:14:03.222264+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:14:03.221+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47346","server-name":"etcd1","error":"remote error: tls: bad certificate"}
2020-10-15T12:16:00.722905+03:00 etcd1 etcd: {"level":"warn","ts":"2020-10-15T12:16:00.721+0300","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"master1:47400","server-name":"etcd1","error":"remote error: tls: bad certificate"}
```

**Comment by brandond** [comment]
Can you share the actual output of the openssl s_client command? Does it work properly if you use rsa instead of ecdsa?

**Comment by gynter** [comment]
@brandond, it seems to me, that intermediate certificate (*Client CA*) causes the issue for k3s (*full chain isn't being recursively checked?*). If I change chain to `Root CA > etcd1 & master1` then everything works fine with both RSA and ECC.

I also changed etcd1 configuration so it only has *Client CA* as client CA (not full chain/bundle like previously), *etcd1* cert is issued by *Client CA*. Both wget and openssl are still working fine when specifying correct *Root CA* or *Root CA & Client CA* bundle. Authentication also works fine when specifying *master1* cert (also issued by *Client CA*) and key.

Output is here thou I'd slightly had to redact it. As You can see, verification succeeds.
```
$ openssl s_client -showcerts \
> -connect etcd1:2379 \
> -CAfile root_ca.crt \
> -cert master1.crt \
> -key master1.key
CONNECTED(00000003)
depth=2 CN = Root CA
verify return:1
depth=1 CN = Client CA
verify return:1
depth=0 CN = etcd1
verify return:1
---
Certificate chain
 0 s:/CN=etcd1
   i:/CN=Client CA
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
 1 s:/CN=Client CA
   i:/CN=Root CA
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=etcd1
issuer=/CN=Client CA
---
Acceptable client certificate CA names
/CN=Client CA
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2430 bytes and written 1208 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 384 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: ...
    Session-ID-ctx: 
    Master-Key: ...
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket:
    ...

    Start Time: ...
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestclosed
```

If I don't specify authentication cert & key I still can connect correctly, but receive cert error, as I should, but the verification still succeeds:

```
$ openssl s_client -showcerts \
> -connect etcd1:2379 \
> -CAfile root_ca.crt
CONNECTED(00000003)
depth=2 CN = Root CA
verify return:1
depth=1 CN = Client CA
verify return:1
depth=0 CN = etcd1
verify return:1
139800371771280:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:s3_pkt.c:1493:SSL alert number 42
139800371771280:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
Certificate chain
 0 s:/CN=etcd1
   i:/CN=Client CA
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
 1 s:/CN=Client CA
   i:/CN=Root CA
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=etcd1
issuer=/CN=Client CA
---
Acceptable client certificate CA names
/CN=Client CA
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1585 bytes and written 138 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 384 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: ...
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: ...
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by brandond** [comment]
In that case you'll probably need to concatenate the root and intermediate (or root and client) CAs into a single file, and pass that as the `--datastore-cafile`.

**Comment by gynter** [comment]
@brandond I have also tried both concatenated (bundle) and non-concatenated ways, no luck with k3s. Both ways worked fine with OpenSSL and wget.

Also, as far as I know the bundle (Root CA + Intermediate CA) needs to be only on server side, since full certificate chain is being sent from server to client anyway. Client should only have Root CA to confirm the "starting" point of the full chain, to verify the chain.

**Comment by brandond** [comment]
Have you tried with etcdctl? That might be a more relevant test, since it would use the same Go crypto routines as k3s.

**Comment by gynter** [comment]
Same with when using `etcdctl` from master1. I think I just figured out what's the issue. Sadly (or luckily) issue is between the keyboard and chair. I completely ignored the fact that checking CN is not mandatory when SAN field is present, so I just assumed that etcdctl crypto routines behave like "everyone else" and still check CN as last resort measure. Obviously it's not that way and I need to add `DNS: etcd1` to *X509v3 Subject Alternative Name* also... Sad thing is that wget (and many other) completely ignore that part in RFC to maintain backwards compatibility. Also the scripts I used to generate the certificates weren't smart enough to put the domain also to subjectAltName.

So, issue solved for me. Thank You for the help @brandond . Running `etcdctl` from `master1` really helped to figure this out for me.

**Comment by brandond** [comment]
Yeah, ai think that the CN fallback was removed from the golang crypto routines in 1.15.

**Comment by daenney** [comment]
https://golang.org/doc/go1.15#commonname
>  It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable.

**Comment by brandond** [comment]
Closing as per https://github.com/k3s-io/k3s/issues/2369#issuecomment-713555350

**Comment by oppshorer** [comment]
maybe do not set hostname
