### ISSUE TITLE
a dashboard without need to configuration

### ISSUE THREAD

**Issue by lygstate** [k3s-io/k3s#237]
The dashbaord for k3s are failing and failing, to much annoy

also without the Internet

**Comment by loversama** [comment]
This or documentation as the normal methods don't apply to K3s or how its setup by default?

**Comment by lygstate** [comment]
the demo in k3s.io did not mention how to showing the dashboard

**Comment by erikwilson** [comment]
Not sure if related to issues/233, it may be the `kubectl proxy` part is not working correctly, or the URL visited is not correct, or failure to setup user correctly. Are there any error logs produced? I am curious if using `--insecure-skip-tls-verify` with kubectl might help if it is a cert issue.

**Comment by lygstate** [comment]
can you provide full document about  --insecure-skip-tls-verify@erikwilson also am
talking about the agent are blocked in china， I hope the `k3s agent` docker image are self contained， no need downloading from the Internet， so I can use it without Internet access。

**Comment by erikwilson** [comment]
The 0.3.0 RC has support for air-gap w/ images as part of the release, please try it out!

**Comment by deniseschannon** [comment]
Here are the docs for airgap: https://github.com/rancher/k3s#air-gap-support

@lygstate please let us know if you are able to test it out.

**Comment by milosonator** [comment]
I've been able to get a dashboard up and running using the standard dashboard documentation and fully airgapped.
