### ISSUE TITLE
Unable to get the service details and Unable to bring down the k3s node for some testing

### ISSUE THREAD

**Issue by Imboncy** [k3s-io/k3s#2371]
#### Bring Down the Node to Not Ready

- I want to bring down the node of k3s cluster to `NotReady` state for **_sometime_** and then again up it for some testing purpose.
  - I tried to do it via stopping kubelet service for sometime.
  - stopping containerd service for sometime as container runtime is containerd. 

But unable to access those services. 
```bash
root@ip-172-31-14-243:~# kubectl get nodes
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-19-233   Ready    master   27m   v1.18.9+k3s1

root@ip-172-31-14-243:~# systemctl status kubelet
● kubelet.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
root@ip-172-31-14-243:~# systemctl status docker
● docker.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
root@ip-172-31-14-243:~# systemctl status containerd
● containerd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

_I tried it from inside the container and outside the container_  but unable to get the services. Do I need to ssh into the nodes? If so how to do that I tried `ssh <node-name>` but it doesn't work. 

Is there any other way to bring node down by interupting any service?

**Comment by brandond** [comment]
The service is called k3s (for servers) or k3s-agent (for agents). However, if you stop k3s on a single-server cluster, there will be no control plane left to access via kubectl. Kubelet, containerd, etc do not have separate services because they are embedded within the k3s binary. Please see: https://github.com/rancher/k3s#how-is-this-lightweight-or-smaller-than-upstream-kubernetes
> There are two major ways that K3s is lighter weight than upstream Kubernetes:
> The memory footprint to run it is smaller
> The binary, which contains all the non-containerized components needed to run a cluster, is smaller
> The memory footprint is reduced primarily by **running many components inside of a single process**. This eliminates significant overhead that would otherwise be duplicated for each component.

**Comment by sharmababu** [comment]
Thanks for the information @brandond. Yes, I saw those services (k3s, k3s
agents) now I get some Idea about how it is working. So Is there any way
that I can use to back the nodes to NotReady state?

**Comment by brandond** [comment]
If you have a single-node cluster, stopping k3s will shut down both the kubelet and the apiserver, so there wouldn't really be anything running for the node to show as NotReady in. If you had a two-node cluster (one server, one agent) you could stop k3-agent on the second node to see it as NotReady.
