### ISSUE TITLE
Traefik Version

### ISSUE THREAD

**Issue by littleforce163** [k3s-io/k3s#2374]
Any schedule to update Traefik to v2.3?
——

Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SvenDowideit** [comment]
is this basically a dupe of #1141 ?

**Comment by lexfrei** [comment]
@SvenDowideit yes
