### ISSUE TITLE
k3s airgap & local-path provisioner

### ISSUE THREAD

**Issue by vdups** [k3s-io/k3s#2391]
**Environmental Info:**
K3s Version: v1.18.9+k3s1

Node(s) CPU architecture, OS, and Version: 
Various deployments

Cluster Configuration:
1 single node.
Offline installer (without internet connection).
k3s + docker-ce
docker-ce image cache filled using _docker load -i k3s-airgap-images-*.tar_

Similar use case as described in https://github.com/rancher/k3s/issues/172 (comment https://github.com/rancher/k3s/issues/172#issuecomment-476339625 )

**Describe the bug:**
When trying to create a pvc using the default Storage Class (local-path), the local-path provisioner fails.
PVC keeps in "Pending" state

**Steps To Reproduce:**
Create any PVC which will use the local-path

**Expected behavior:**
PVC should be created

**Actual behavior:**
PVC stays in pending mode forever

**Proposed solution**
local-path provisioner tries to create a create-pvc-XXXXXX pod in kube-system namespace.
In this pod, the _local-path-create_ container tries to use the _busybox_  image which is unavailable in the k3s-airgap-images-amd64.tar containers images pack.

Importing a busybox image pulled from another computer into fresh offline k3s install solved the problem.
Would it be feasible to include a busybox (the default one, or any custom rancher one) in the images tarball in a future release guys?

**Additional context / logs:**

**Comment by brandond** [comment]
This has been fixed on the master branch in https://github.com/rancher/k3s/pull/2257. There are not currently any stable builds available with this fix.

**Comment by vdups** [comment]
Thanks Brandon
Wasn't able to find an issue mentioning this and add to investigate myself.

Great to have the workaround and know that it will be fixed in a future release!

Cheers
