### ISSUE TITLE
k3s overrides the shm size defined in container runtime configuration

### ISSUE THREAD

**Issue by w3st3ry** [k3s-io/k3s#2392]
**Environmental Info:**
K3s Version: 
v1.18.4+k3s1 (97b7a0e9)

Node(s) CPU architecture, OS, and Version: 
64 bits, 5.4.0-47-generic, Ubuntu LTS 20.04.1

Cluster Configuration:
2 masters, 6 workers

**Describe the bug:**
`default-shm-size` modified option from `/etc/docker/daemon.json` is override in a Pod by k3s.

**Steps To Reproduce:**
* Drain nodes
* Edit `/etc/docker/daemon.json` and put `"default-shm-size": "1G"` per ex.
* Restart the Docker daemon, uncordon the node
* Test the Docker daemon is aware of the new configuration changes by running a local container on the machine and do a `df -h` to checkout the shm assigned size. (atm everything works, we get 1G through Docker directly)
* Run a pod in interactive and do a `df -h` to checkout the shm assigned size. (the pod don't took the configuration of the container runtime shm size, override it by default 64mb instead of 1G as mentioned).

**Expected behavior:**
`tmpfs                      1G  0  1G   0% /dev/shm`

**Actual behavior:**
`tmpfs                      64M  0  64M   0% /dev/shm`

**Additional context / logs:**
Absolutely nothing relevant in logs.

**Comment by brandond** [comment]
I don't believe this is a k3s specit issue. See: https://github.com/kubernetes/kubernetes/issues/28272
