### ISSUE TITLE
Hey on the edge!

### ISSUE THREAD

**Issue by gybfefe** [k3s-io/k3s#2402]
Why not making a mobile app k3s?

**Comment by gybfefe** [comment]
Why not making a mobile app k3s? Is it done or just simply closed?

**Comment by davidnuzik** [comment]
Hi @gybfefe my apologies I may have initially taken this as an advertisement or spam. My mistake.
I'm curious, what would you be looking for in a mobile app? Effectively being able to run k3s on android phones? What might the use case be for this? Thanks.

**Comment by gybfefe** [comment]
Thank you for considering my suggestion. I think if you click on an app to install and run server or client filling out the necessary parameters is a convenience rather than writing command lines. If you top it with qr reading capabilities it's half of an automation. Further development should use NFC etc. The point of my view, is the ability to use old mobile phones as IoT. The market leader hardware today is mobile phone, why not make clever recycling via IT. People just throw away old phones as I understand, and their resources gets better every year to use like edge devices.
Best wishes,
Ben

**Comment by erikwilson** [comment]
It would be nice if k3s could run on Android, unfortunately last time I tried it was not possible with a stock Android kernel. It would need the necessary kernel modules to run containerd and likely rootless mode, and even then that may require some root setup. Using a rooted custom kernel it is likely possible to run k3s, but that is likely not an accessible solution to most people.

**Comment by gybfefe** [comment]
It could:
https://gist.github.com/arno01/ebf570af208e28c1a0cf78da4f63bc9c

**Comment by gybfefe** [comment]
"This is docker successfully running containers directly in Android. No chroot inside GNU/Linux rootfs and no VM emulation with qemu. This is pure Android.

As showed [here](https://github.com/termux/termux-root-packages/issues/60#issuecomment-636553841), docker runs fine in Android, it just can't pull any container since the Android OS isn't supported by them. Trying to politely ask a Linux version of the container with the flag --platform=linux didn't work either. So I lost my patience debugging the seg fault I was getting and had the idea to spoof my operating system by replacing every occurrence of runtime.GOOS (which returns the string android) by "linux". And guess what, it worked."

**Comment by erikwilson** [comment]
Maybe I am missing something, but those links seem to back up my assertions. If the kernel has support for it then it may work, but if the necessary kernel modules are not present or you cannot setup rootless then there is a problem. Samsung may be special in that it had support for Linux DeX at some point which may have required these things, however on other devices I don't think these modules or capabilities are usually included in the kernel. Unfortunately the GOOS fix to use `linux` doesn't really matter much if ASOP as a baseline doesn't support this.

**Comment by cwayne18** [comment]
While we appreciate the suggestion, as Erik pointed out above, this is currently not yet feasible.  We'd be happy to revisit this in the future if the android kernel picks up what we need.
