### ISSUE TITLE
scan the base build image for vulnerabilities before compiling binaries and copying to Scratch image

### ISSUE THREAD

**Issue by cnuber** [k3s-io/k3s#2418]
**Is your feature request related to a problem? Please describe.**
The k3s image build process results in a FROM scratch image.  As such, scanners like trivy/clair/etc do not run against the image.

**Describe the solution you'd like**
Scanning the base build image as part of the image build process before the binaries are compiled and copied over to the final Scratch image would allow for proactive identification and remediation of any known vulnerabilities in the libraries included in the compiled binary.

**Comment by brandond** [comment]
I believe this is closed by #2253
