### ISSUE TITLE
check to include features from microk8s

### ISSUE THREAD

**Issue by SimonHeimberg** [k3s-io/k3s#2423]
**Is your feature request related to a problem? Please describe.**

microk8s form ubuntu https://github.com/ubuntu/microk8s has similar goals as k3s.

Some things sound great:
* creating a ha cluster sounds simple. No external data storage required.
* working with dqlite
* sounds like the servers manage automatically which instances have dql roles (https://microk8s.io/docs/high-availability)

**Describe the solution you'd like**
* Use components/parts of microk8s
* Pick some code from microk8s
* send patches to microk8s, to allow to simplify using components

 

* mention specific benefits of k3s somewhere

**Describe alternatives you've considered**
-

**Additional context**
Both project have an apache license, so license should not hinder collaboration.

**Comment by brandond** [comment]
Are there any specific microk8s features that you feel like k3s is missing? Our experimental dqlite support has been replaced with managed (embedded) etcd in 1.19, and will be marked stable soon.

**Comment by SimonHeimberg** [comment]
What I miss from k8s is:
* already having a stable solution
* that the system looks itself on which nodes the dqlite (or etcd) data is stored (https://microk8s.io/docs/high-availability in `Working with HA`)

And I miss a comparison of features. The ones I find by a search engine are personal experiences.

----

already comparable
* simple to set up ha:
  * microk8s 
    $ sudo snap install microk8s ... # (on h1, h2, h3) # well, snap must be installed first
    h1$ microk8s add-node
    h2$ microk8s join ...
    h1$ microk8s add-node
    h3$ microk8s join ...
  * k3s
     $ curl -sfL https://get.k3s.io | sh - # (on h1, h2, h3)
     h1$ K3S_TOKEN=SECRET k3s server --cluster-init
     h2$ K3S_TOKEN=SECRET k3s server --server https://<ip or hostname of server1>:6443
     h3$ K3S_TOKEN=SECRET k3s server --server https://<ip or hostname of server1>:6443
