### ISSUE TITLE
where are my certs - connection reset

### ISSUE THREAD

**Issue by rbucker** [k3s-io/k3s#2427]
I have created 3x Photon V3 instances... and deployed 1x k3s server in the usual way.I then created 2x agents in the same way but added the K3S_TOKEN and K3S_URL to the command line.

On the server I opened port 6443 and ICMP on the iptables.

when I journalctl on the agent I get this error:

```
Oct 25 16:27:01 phos3k3.bucker.local k3s[546]: time="2020-10-25T16:27:01.403081772Z" level=error msg="failed to get CA certs at https://127.0.0.1:40793/cacerts: Get https://127.0.0.1:40793/cacerts: read tcp 127.0.0.1:40510->127.0.0.1:40793: read: connection reset by peer"
```

I tried the URL manually

```
$ curl https://127.0.0.1:40793/cacerts
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
```

tried it insecure

```
$ curl --insecure https://127.0.0.1:40793/cacerts
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
```

**Comment by brandond** [comment]
Can you share the complete logs from both server and agent, as well as the commands you used to install or start them?

Did you open the required ports in both iptables, and in the security groups? You called them instances so I am assuming you are doing this on a cloud service provider.

**Comment by rbucker** [comment]
I've installed the k3s server and agents on a vmware esxi 6.7 machine.  The underlying guest OS is from vmware (Photon OS v3). There is a default IPTables and I added an accept for 6443. The error on the agent side suggests that the particular port is not open. When I read the docs it was fairly vague on the subject... I'm assembling the logs as I'm looking for the iptables list.

**Comment by ieugen** [comment]
I'm also seeing this in a cluster, after reboot.
I'm running up to date Debian stable 

```
uname -a
Linux w01-k05 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

```
Nov 26 09:14:46 w01-k05 k3s[1517]: time="2020-11-26T09:14:46.915017796+01:00" level=info msg="Running load balancer 127.0.0.1:45581 -> [10.20.0.8:6443]"
Nov 26 09:15:06 w01-k05 k3s[1517]: time="2020-11-26T09:15:06.918774371+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49594->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:15:28 w01-k05 k3s[1517]: time="2020-11-26T09:15:28.921032944+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49602->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:15:50 w01-k05 k3s[1517]: time="2020-11-26T09:15:50.924164581+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49610->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:16:12 w01-k05 k3s[1517]: time="2020-11-26T09:16:12.926180750+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49618->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:16:34 w01-k05 k3s[1517]: time="2020-11-26T09:16:34.928101209+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49626->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:16:56 w01-k05 k3s[1517]: time="2020-11-26T09:16:56.936043204+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49634->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:17:18 w01-k05 k3s[1517]: time="2020-11-26T09:17:18.938860741+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49642->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:17:40 w01-k05 k3s[1517]: time="2020-11-26T09:17:40.941379517+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49650->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:18:02 w01-k05 k3s[1517]: time="2020-11-26T09:18:02.943810928+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49658->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:18:24 w01-k05 k3s[1517]: time="2020-11-26T09:18:24.945899041+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49666->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:18:46 w01-k05 k3s[1517]: time="2020-11-26T09:18:46.948217115+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49674->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:19:08 w01-k05 k3s[1517]: time="2020-11-26T09:19:08.951102819+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49682->127.0.0.1:45581: read: connection reset by peer"
Nov 26 09:19:30 w01-k05 k3s[1517]: time="2020-11-26T09:19:30.953882537+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:45581/cacerts: Get https://127.0.0.1:45581/cacerts: read tcp 127.0.0.1:49690->127.0.0.1:45581: read: connection reset by peer"

```

**Comment by ieugen** [comment]
The issue in my case was broken network connection. 
The cloud provider had an incident where private network between some servers (including our own) dd not work.

**Comment by bmmpp** [comment]
> I have created 3x Photon V3 instances... and deployed 1x k3s server in the usual way.I then created 2x agents in the same way but added the K3S_TOKEN and K3S_URL to the command line.
> 
> On the server I opened port 6443 and ICMP on the iptables.
> 
> when I journalctl on the agent I get this error:
> 
> ```
> Oct 25 16:27:01 phos3k3.bucker.local k3s[546]: time="2020-10-25T16:27:01.403081772Z" level=error msg="failed to get CA certs at https://127.0.0.1:40793/cacerts: Get https://127.0.0.1:40793/cacerts: read tcp 127.0.0.1:40510->127.0.0.1:40793: read: connection reset by peer"
> ```
> 
> I tried the URL manually
> 
> ```
> $ curl https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```
> 
> tried it insecure
> 
> ```
> $ curl --insecure https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```



> I have created 3x Photon V3 instances... and deployed 1x k3s server in the usual way.I then created 2x agents in the same way but added the K3S_TOKEN and K3S_URL to the command line.
> 
> On the server I opened port 6443 and ICMP on the iptables.
> 
> when I journalctl on the agent I get this error:
> 
> ```
> Oct 25 16:27:01 phos3k3.bucker.local k3s[546]: time="2020-10-25T16:27:01.403081772Z" level=error msg="failed to get CA certs at https://127.0.0.1:40793/cacerts: Get https://127.0.0.1:40793/cacerts: read tcp 127.0.0.1:40510->127.0.0.1:40793: read: connection reset by peer"
> ```
> 
> I tried the URL manually
> 
> ```
> $ curl https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```
> 
> tried it insecure
> 
> ```
> $ curl --insecure https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```



> I have created 3x Photon V3 instances... and deployed 1x k3s server in the usual way.I then created 2x agents in the same way but added the K3S_TOKEN and K3S_URL to the command line.
> 
> On the server I opened port 6443 and ICMP on the iptables.
> 
> when I journalctl on the agent I get this error:
> 
> ```
> Oct 25 16:27:01 phos3k3.bucker.local k3s[546]: time="2020-10-25T16:27:01.403081772Z" level=error msg="failed to get CA certs at https://127.0.0.1:40793/cacerts: Get https://127.0.0.1:40793/cacerts: read tcp 127.0.0.1:40510->127.0.0.1:40793: read: connection reset by peer"
> ```
> 
> I tried the URL manually
> 
> ```
> $ curl https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```
> 
> tried it insecure
> 
> ```
> $ curl --insecure https://127.0.0.1:40793/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:40793 
> ```

Hi, I hava the same questino,  Have you found a solution

**Comment by guykanyvision** [comment]
+1

**Comment by brandond** [comment]
> Oct 25 16:27:01 phos3k3.bucker.local k3s[546]: time="2020-10-25T16:27:01.403081772Z" level=error msg="failed to get CA certs at https://127.0.0.1:40793/cacerts: Get https://127.0.0.1:40793/cacerts: read tcp 127.0.0.1:40510->127.0.0.1:40793: read: connection reset by peer"

Either the server isn't running, or the port is not available to the agent. You'll see a loopback address in the error because the agent uses a tunnel proxy to connect to servers. Ensure that you can `curl -vks https://server:6443/ping`
