### ISSUE TITLE
CNCF SIG-Runtime presentation?

### ISSUE THREAD

**Issue by raravena80** [k3s-io/k3s#2433]
Hello K3s team,

I'm one of the co-chairs of the CNCF SIG-Runtime, and since you are CNCF Sandbox project I think it would be great for you to present/discuss k3s at one of our meetings. For example, discuss things such as k3s adoption, k3s architecture, etc.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by cjellick** [comment]
Hi. Sounds like a good idea. Any more details on what you'd want to hear about? If not, maybe we could have someone sit in on a meeting to get a feel for what is typically covered.

**Comment by raravena80** [comment]
A general overview of the project, use-cases, and current users would be great. Let me know if that works. You are welcome to join the meetings anytime or you can browse through the recordings [here](https://www.youtube.com/channel/UCvqbFHwN-nwalWPjPUKpvTA). Thanks!

**Comment by raravena80** [comment]
Hi @cjellick, checkin in. 

Would the team be interested in presenting in our next CNCF SIG-runtime meeting? (April 1st)

Thanks!

**Comment by cjellick** [comment]
Ah! Issue got lost in my notifications. Fortunately, we just presented recently anyway. Going to close for now.
