### ISSUE TITLE
uninstall does not remove CNI network namespaces

### ISSUE THREAD

**Issue by elloe** [k3s-io/k3s#2435]
**Environmental Info:**
K3s Version: 

```
[INFO]  Using v1.18.9+k3s1 as release                                                                                                
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/k3s                                         
[INFO]  Verifying binary download
```
Node(s) CPU architecture, OS, and Version: 

`Linux elloe000 5.4.0-52-lowlatency #57-Ubuntu SMP PREEMPT Thu Oct 15 12:05:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

Single node master

**Describe the bug:**

CNI net namespaces are not removed when the uninstall script is executed.

**Steps To Reproduce:**

- Installed K3s: 

```
$ sudo k3s_install
...
[INFO]  systemd: Starting k3s

$ ip netns
cni-45b9e5e5-8d10-10e3-d4cc-8d3fadea0ee0 (id: 2)
cni-b19b317e-5dbb-34a1-6f0a-02fe231d122a (id: 6)
cni-12754ebc-456a-58fb-9cc3-2307bb171279 (id: 5)
cni-56a785e1-dba4-4855-d402-37189f735aa4 (id: 4)
cni-6b97a604-2027-3af7-f82c-44be992c43ae (id: 3)
cni-79138b92-27ab-e18d-2ad3-5b7404dee089 (id: 1)

$ sudo k3s-uninstall.sh 
...
+ remove_uninstall
+ rm -f /usr/local/bin/k3s-uninstall.sh

$ ip netns                     
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
cni-45b9e5e5-8d10-10e3-d4cc-8d3fadea0ee0
Error: Peer netns reference is invalid.
cni-b19b317e-5dbb-34a1-6f0a-02fe231d122a
Error: Peer netns reference is invalid.
cni-12754ebc-456a-58fb-9cc3-2307bb171279
Error: Peer netns reference is invalid.
cni-56a785e1-dba4-4855-d402-37189f735aa4
Error: Peer netns reference is invalid.
cni-6b97a604-2027-3af7-f82c-44be992c43ae
Error: Peer netns reference is invalid.
cni-79138b92-27ab-e18d-2ad3-5b7404dee089

$ for ns in $( cd /run/netns; ls -1 cni*); do sudo ip netns del $ns; done
$ ip netns
$
```
**Expected behavior:**

cni-* net namesspaces removed

**Actual behavior:**

`ip netns` reports cni-* namespaces still exist

**Additional context / logs:**

**Comment by davidnuzik** [comment]
Unmount but this doesn't seem to delete them? See https://github.com/rancher/k3s/blob/master/install.sh#L602

**Comment by brandond** [comment]
Yes, unmounting does not delete them.

**Comment by rancher-max** [comment]
#### Validated using current released uninstall script
Steps:
1. `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" INSTALL_K3S_VERSION=v1.18.9+k3s1 sh -`
2. Ensured nodes and pods all up and running
3. `k3s-uninstall.sh`

- Validated there is an unmount and remove step that removes from `/run/netns/cni-*`
- Validated result of `ip netns` after uninstall is empty
- Validated result of `ls /run/netns` after uninstall is empty
