### ISSUE TITLE
[Question] Certificate authentication and cert issuing via Certificate API. Have these features been removed?

### ISSUE THREAD

**Issue by zsolt-keseru-epam** [k3s-io/k3s#245]
I would like to authenticate users via client certificate, but I've got stuck.
I've tried to find information about setting up user authentication, but only found in the apiserver commandline arguments and the kubeconfig that it uses HTTP basic auth by default.
Is the content of the htpasswd file managed by k3s? If so, how can we add new entries?

I've also tried to issue a new client certificate via the Certifcates API as `k3s kubectl api-versions` show it's supported. (This is how I tried: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster and it works on other clusters)
But after approving the CSR with `k3s kubectl certificate approve ...` the CSR only goes to "Approved" state and not "Approved,Issued", and there is no `.status.certificate` field.

Without these I've tried to sign my CSR directly using the CA cert, and I wasn't able to authenticate (I'm not sure I've used correct cert files).

Are these the expected behaviors and it's better to forget cert auth to integrate with, or should I report it as bug?
I'm using k3s v0.2.0 (amd64)

**Comment by zsolt-keseru-epam** [comment]
I've found the server authentication code meanwhile, and as I see it uses the upstream k8s authenticator so I guess certificate authentication should work. Maybe I've created a wrong client certificate without the Certificate API.

**Comment by iluminae** [comment]
Does this work? I am using the stable/cockroachdb helm chart on k8s installed via kubeadm, and this system with k3s - only the kubeadm based system issues the approved CSRs.

**Comment by huapox** [comment]
How's it going?

**Comment by huapox** [comment]
@zsolt-keseru-epam

**Comment by zsolt-keseru-epam** [comment]
@huapox I didn't have the chance to investigate this deeper as we decided to move with other solution for a start.
Although now I have checked that certificate issuing is still not working in 0.5.0

**Comment by huapox** [comment]
I've tested the version 0.7.0-rc2 , it seems works after #359

**Comment by huapox** [comment]
Tested Okay, via #684

**Comment by brandond** [comment]
Closing due to age.
