### ISSUE TITLE
Frequent relist all objects when edge workers disconnect to apiserver

### ISSUE THREAD

**Issue by kubeeeee** [k3s-io/k3s#2450]
Now for the edge computing  scenario, since the low quality of network, edge workers always disconnect to apiserver. 

At this time, if the connection is disconnected for a while(enough for the watch cache in apiserver expired), it will cause relisting all the objects, which consumes a lot of bandwidth and the control plane. 

And for K8s run in DC, nodes rarely disconnect or reconnects soon. I think this is different from the edge computing scenario.

Do we have any optimization for this edge computing  scenario?

**Comment by kubeeeee** [comment]
cc @erikwilson @ibuildthecloud

**Comment by brandond** [comment]
For edge computing scenarios we usually envision many small clusters, managed through Rancher or Fleet. Kubernetes is not really built to handle the kubelets disconnecting and reconnecting frequently.
