### ISSUE TITLE
401 Unauthorized message when joining a single-node cluster

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2463]
**Environmental Info:**
K3s Version: 
v1.19.3-rc1+k3s2

Node(s) CPU architecture, OS, and Version: 
Linux centos02.lan.khaus 5.8.10-1.el7.elrepo.x86_64 rancher/k3s#1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
* 1 server using embedded sqlite
* 1 server attempting to join the cluster

**Describe the bug:**
Get a `401 Unauthorized` error when attempting to join a single-node cluster

**Steps To Reproduce:**
* Start 1st server with `k3s server --token token`
* Start 2nd server with `k3s server --server https://server1:6443 --token token`

**Expected behavior:**
Get an error message indicating that you cannot join a single-node cluster (not using etcd or external database)

**Actual behavior:**
Get unauthorized error from server:
```
INFO[2020-10-29T22:42:48.817118214-07:00] Starting k3s v1.19.3-rc1+k3s2 (f8a4547b)
INFO[2020-10-29T22:42:48.856336230-07:00] Managed etcd cluster not yet initialized
FATA[2020-10-29T22:42:48.859634131-07:00] starting kubernetes: preparing server: https://centos01.lan.khaus:6443/v1-k3s/server-bootstrap: 401 Unauthorized
```

**Additional context / logs:**

**Comment by Nicolasery** [comment]
exact same issue, my kubectl commands like kubectl get pods return: The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by chrispyduck** [comment]
I think I'm seeing the same thing:
```
# k3s server --token '<redacted>' --server https://<redacted>:6443 -v 999
I1224 10:44:31.326306    1071 interface.go:400] Looking for default routes with IPv4 addresses
I1224 10:44:31.326434    1071 interface.go:408] Default route transits interface "wlan0"
I1224 10:44:31.326730    1071 interface.go:208] Interface wlan0 is up
I1224 10:44:31.326904    1071 interface.go:256] Interface "wlan0" has 2 addresses :[<redacted>].
I1224 10:44:31.326965    1071 interface.go:223] Checking addr  <redacted>.
I1224 10:44:31.326997    1071 interface.go:230] IP found <redacted>
I1224 10:44:31.327032    1071 interface.go:262] Found valid IPv4 address <redacted> for interface "wlan0".
I1224 10:44:31.327061    1071 interface.go:414] Found active IP <redacted>
I1224 10:44:31.327126    1071 services.go:51] Setting service IP to "<redacted>" (read-write).
INFO[2020-12-24T10:44:31.327201649-05:00] Starting k3s v1.19.5+k3s2 (746cf403)         
INFO[2020-12-24T10:44:31.698838790-05:00] Managed etcd cluster not yet initialized     
FATA[2020-12-24T10:44:31.820523251-05:00] starting kubernetes: preparing server: https://<redacted>:6443/v1-k3s/server-bootstrap: 401 Unauthorized
```

**Comment by brandond** [comment]
@chrispyduck did you start your first server with --cluster-init?

**Comment by chrispyduck** [comment]
I thought my environment variables implied --cluster-init, but it turns out they didn't. Explicitly adding it to the command line resolved the problem. Thank you!

**Comment by rgstephens** [comment]
I'm running into this when I try to set a feature-gate:

```sh
$ sudo k3s server --token ${k3s_token} --server ${k3s_url} --kubelet-arg --feature-gates="MixedProtocolLBService=true"
INFO[2021-01-29T21:00:39.382325148-08:00] Starting k3s v1.20.2+k3s1 (1d4adb03)
INFO[2021-01-29T21:00:39.430699348-08:00] Managed etcd cluster not yet initialized
FATA[2021-01-29T21:00:39.432581008-08:00] starting kubernetes: preparing server: https://10.3.3.2:6443/v1-k3s/server-bootstrap: 401 Unauthorized
```

**Comment by brandond** [comment]
@rgstephens I don't think your problem is related to the subject of this issue, unless the server you are joining is indeed not running etcd.

Also, the flag syntax you're looking for is `--kubelet-arg=feature-gates=MixedProtocolLBService=true`, although you might want to confirm that this needs to be enabled on the kubelet and not the kube-apiserver.

**Comment by caroline-suse-rancher** [comment]
Closing as this appears to be resolved
