### ISSUE TITLE
Service endpoint is pointing to wrong ip address

### ISSUE THREAD

**Issue by prashilgupta** [k3s-io/k3s#2464]
**Environmental Info:**
K3s Version: 
```
$ sudo k3s -v
k3s version v1.18.6+k3s1 (6f56fa1d)
```

Node(s) CPU architecture, OS, and Version: 
```
$ sudo uname -a
Linux ztna-gateway 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

Cluster Configuration:
Single machine.

**Describe the bug:**
The service endpoint is pointing to the wrong IP. As a result, another service depending on it is stuck in init

**Steps To Reproduce:**
```
sudo curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.18.6+k3s1" sh -s - --no-deploy traefik
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh --version v3.3.4
helm install <name> ./<name> --kubeconfig /etc/rancher/k3s/k3s.yaml
sleep 60
/usr/bin/gawk -i inplace '{ gsub(/server/, "server --secrets-encryption") }; { print }' /etc/systemd/system/k3s.service
systemctl daemon-reload
```

**Expected behavior:**
All pods are running fine

**Actual behavior:**
Service endpoint is pointing to wrong ip. Redis service endpoint is saying 10.42.0.15 but pod is running on 10.42.0.22
```
$sudo kubectl get endpoints | grep redis
redis           10.42.0.15:6379                                2d3h
$sudo kubectl describe service  redis
Name:              redis
Namespace:         default
Labels:            app.kubernetes.io/managed-by=Helm
                   service=redis
Annotations:       meta.helm.sh/release-name: ztna
                   meta.helm.sh/release-namespace: default
Selector:          app=redis
Type:              ClusterIP
IP:                10.43.149.110
Port:              6379  6379/TCP
TargetPort:        6379/TCP
Endpoints:         10.42.0.15:6379
Session Affinity:  None
Events:            <none>
$ sudo iptables-save  | grep redis
-A KUBE-SEP-MGG6GT4KKVPVNFQV -s 10.42.0.15/32 -m comment --comment "default/redis:6379" -j KUBE-MARK-MASQ
-A KUBE-SEP-MGG6GT4KKVPVNFQV -p tcp -m comment --comment "default/redis:6379" -m tcp -j DNAT --to-destination 10.42.0.15:6379
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.149.110/32 -p tcp -m comment --comment "default/redis:6379 cluster IP" -m tcp --dport 6379 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.149.110/32 -p tcp -m comment --comment "default/redis:6379 cluster IP" -m tcp --dport 6379 -j KUBE-SVC-VJVGUQLGUAB5SOUJ
-A KUBE-SVC-VJVGUQLGUAB5SOUJ -m comment --comment "default/redis:6379" -j KUBE-SEP-MGG6GT4KKVPVNFQV
$ sudo k3s kubectl get all -o wide -A | grep redis

default       pod/redis-5c96dbcc9d-pt45t                   1/1     Running    1          2d    10.42.0.22   ztna-gateway   <none>           <none>
default       service/redis            ClusterIP      10.43.149.110   <none>          6379/TCP                                    2d    app=redis
default       deployment.apps/redis                    1/1     1            1           2d    redis                    redis:6.0.5-alpine3.12                                             app=redis
default       replicaset.apps/redis-5c96dbcc9d                   1         1         1       2d    redis                    redis:6.0.5-alpine3.12                                             app=redis,pod-template-hash=5c96dbcc9d

$nc -vz 10.42.0.22 6379
10.42.0.22 (10.42.0.22:6379) open
$ nc -vz 10.43.149.110 6379
nc: 10.43.149.110 (10.43.149.110:6379): Host is unreachable

```

**Additional context / logs:**
**Below error start coming after ntp time change:** 

...
Oct 29 20:43:34 host k3s[1045]: W1029 20:43:34.871244    1045 lease.go:224] Resetting endpoints for master service "kubernetes" to [10.194.194.20]
Oct 29 20:43:34 host k3s[1045]: time="2020-10-29T20:43:34.875207654Z" level=info msg="Tunnel endpoint watch event: [10.194.194.20:6443]"
Oct 29 20:43:34 host k3s[1045]: time="2020-10-29T20:43:34.876002738Z" level=info msg="Stopped tunnel to 10.0.2.15:6443"
**Oct 29 15:17:27 host systemd-timesyncd[583]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).**
...
k3s[1045]: I1029 15:19:28.882048    1045 event.go:278] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"redis", UID:"9ae34f58-702b-4635-bfe7-e102f0bb03bc", APIVersion:"v1", ResourceVersion:"721", FieldPath:""}): type: 'Warning' reason: 'FailedToUpdateEndpoint' Failed to update endpoint default/redis: Unauthorized
k3s[1045]: E1029 15:19:28.887947    1045 claims.go:109] unexpected validation error: *errors.errorString

**Comment by prashilgupta** [comment]
@brandond I am getting a similar Unauthorized error for all remaining pods also. I haven't made any modification to RBAC config. There is no RBAC constraint for redis though. This is fresh deployment.

**Comment by brandond** [comment]
That sounds pretty broken, but not in a way that I have ever seen before. I suspect if you go back to the beginning of your logs there's a critical error there somewhere that has caused the rest of this.

Just out of curiosity, how did you settle on a 3 month old release for a new deployment of k3s?

**Comment by prashilgupta** [comment]
@brandond I didn't find any critical error generic to k3s or this pod. We have been using this deployment method for the last 3 months. This issue we hit recently, we don't see it always.

**Comment by brandond** [comment]
Can you share the logs since initial k3s startup? If not, can you reproduce this issue on a new cluster?

**Comment by prashilgupta** [comment]
@brandond Please find attached the startup logs

[k3s_startup.txt](https://github.com/rancher/k3s/files/5473230/k3s_startup.txt)

**Comment by brandond** [comment]
Is this from the same node? I don't see any errors from the endpoint controller. 

Are you running this on a clean system? The logs would seem to indicate that this host previously had a different IP address, or there was more than one member in the cluster:
```
lease.go:224] Resetting endpoints for master service "kubernetes" to [10.0.2.15 10.194.194.20]
```

**Comment by prashilgupta** [comment]
@brandond Yes. Initially the k3s pods are spun up and we get a VMware vmdk disk saved. This vmdk disk is then deployed as part of OVA

**Comment by brandond** [comment]
Ah OK. What are your goals with doing that? Do you just want the images pre-pulled, or is there some specific task you need to accomplish before you make the image? This is most likely what's causing the issue, depending on what your goals are I might have some different recommendations on the best way to accomplish that without corrupting the cluster state.

**Comment by prashilgupta** [comment]
I want the pod images to be pre pulled and running as image generation. Also its build for multiple target platforms like virtualbox, vmware esxi, etc

**Comment by prashilgupta** [comment]
We found that there is a race condition in NTP and k3s services. When ubuntu host machine boots up with hardware clock which isn't in sync with NTP, k3s boots up with the hardware clock time. Soon afterward NTP syncs the time and the secret tokens used by K3s become invalid!!
Is there an existing issue that handles NTP(time change) with k3s so that tokens are reissued?

[startup_error_ntp.txt](https://github.com/rancher/k3s/files/5528312/startup_error_ntp.txt)

**Comment by brandond** [comment]
I don't believe Kubernetes has any special code to handle time jumps, no. Neither does k3s. You might look at adding an `After=systemd-time-wait-sync.service` entry to your systemd unit.
https://www.freedesktop.org/software/systemd/man/systemd-time-wait-sync.service.html

**Comment by prashilgupta** [comment]
I tried it out but it didn't help 

echo 'After=systemd-timesyncd.service' | cat >> /etc/systemd/system/k3s.service.env

<img width="1331" alt="Screenshot 2021-02-02 at 4 22 38 PM" src="https://user-images.githubusercontent.com/1067669/106590296-f4a40880-6572-11eb-9636-056978427b64.png">
<img width="747" alt="Screenshot 2021-02-02 at 4 15 08 PM" src="https://user-images.githubusercontent.com/1067669/106590310-f7066280-6572-11eb-8af2-4ebfaa2a2f2f.png">

**Comment by brandond** [comment]
That needs to go into the systemd unit itself, not the environment file.

**Comment by prashilgupta** [comment]
Seems the dependency is there by default. But still, it doesn't work I think as expected? 

$ systemctl list-dependencies  k3s
k3s.service
● ├─system.slice
● ├─network-online.target
● │ └─systemd-networkd-wait-online.service
● └─sysinit.target
●   ├─apparmor.service
●   ├─blk-availability.service
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─lvm2-lvmetad.socket
●   ├─lvm2-lvmpolld.socket
●   ├─lvm2-monitor.service
●   ├─open-iscsi.service
●   ├─plymouth-read-write.service
●   ├─plymouth-start.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─setvtrgb.service
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot-efi.mount
●   │ └─systemd-remount-fs.service
●   └─swap.target

**Comment by brandond** [comment]
I think that you want to put `After=time-sync.target` in the `[Unit]` section of /etc/systemd/system/k3s.service

**Comment by prashilgupta** [comment]
@brandond I tried this also but it didn't work. Seems systemd-time-wait-sync.service is available on only 239 and aboveof systemd. I am using ubuntu 18.04 which has systemd 237!
Is there an alternative like netstat or crunchy I should try?

**Comment by brandond** [comment]
you could try ntpd or chrony but without systemd integration I don't think there's a good way for you to tell it to wait for time to be sync'd as opposed to just the services being started. 

It's a bit of a hack, but you could try just adding `ExecStartPre=/bin/sleep 30` to the `[Service]` part of the unit? Assuming 30 seconds is enough time for time to sync on start.

**Comment by iam-TJ** [comment]
`systemd-timesyncd` applies the lastest timestamp to `/var/lib/systemd/timesync/clock` which can be seen with `stat`. (see `man systemd-timesyncd`)

If you were to delete that file in `systemd-timesyncd.service` something like this such that its existence is an indication that timesync has been done :

```
[Service]
ExecStartPre=/bin/rm /var/lib/systemd/timesync/clock
```
It should then be possible to amend (add an override to) `k3s.service` with a similar statement that waits for that file to exist. Something like:
```
[Service]
ExecStartPre=/bin/sh -c "while ! [ -e /var/lib/systemd/timesync/clock ]; do sleep 1; done"

**Comment by prashilgupta** [comment]
Thanks @brandond  and @iam-TJ But this still is just a workaround. What happens in case the internet was down initially, k3s started and then NTP sync happened. Shouldn't this be something k3s should fix?

**Comment by iam-TJ** [comment]
@prashilgupta I suspect the answer here is that time-sync is required BEFORE a service (in this case k8s/k3s) that depends on time being accurate - rather like with Kerberos.

In other words it would probably not be considered in-scope for the application to try to keep track of, and handle, potential time changes - that would be an extremely hard problem to solve especially for clusters.

The entire purpose of NTP is to do it once for all applications.

**Comment by brandond** [comment]
Yeah, Kubernetes is not responsible for ensuring that time is in sync on your nodes, or that it stays in sync while it is running. You need to ensure that you have reliable infrastructure in order for your software to function reliably.
