### ISSUE TITLE
Restarting a highly available k3s cluster

### ISSUE THREAD

**Issue by OmegaRogue** [k3s-io/k3s#2466]
How can I restart all nodes in a highly available k3s cluster? I tried to just restart them and now the cluster is completly broken

**Comment by brandond** [comment]
What version are you using, on what distro? How many nodes are in your cluster? What kind of datastore? Normally these questions would be answered if you filled out the issue template.

**Comment by OmegaRogue** [comment]
I'm using k3s version 1.19.3, with the embedded etcd with three nodes in the cluster (technically only two nodes, because one of them is a raspberry pi 3 which keeps crashing, the two other nodes are running Ubuntu Server 20.04, the raspberry pi is running Raspberry Pi OS Lite

**Comment by brandond** [comment]
Are you running 1.19.3+k3s1 or +k3s2? There were many changes to etcd between the two versions. The first release in particular suffered from a problem where clusters that were completely shut down and lost quorum could not be brought back up.

**Comment by adyanth** [comment]
Hi @brandond 
Could you elaborate or point me to other resources for that issue on 1.19.3+k3s1 to bring etcd to quorum? Is it only effecting clusters with etcd and multi master?

I ask because I restarted a 3 node 1 master cluster and on that version, and I am seeing a crashloopbackoff as below:
```
cattle-system             rancher-69c4f4c9f9-gdjpq                   0/1     Running            31         34h
kube-system               local-path-provisioner-7ff9579c6-8n9v7     0/1     CrashLoopBackOff   30         34h
cert-manager              cert-manager-cainjector-55db655cd8-pwdlh   0/1     CrashLoopBackOff   30         34h
fleet-system              fleet-controller-79554fcbf5-r5tcg          0/1     CrashLoopBackOff   30         33h
```

**Comment by adyanth** [comment]
okay, after restarting k3s and k3s-agent using `systemctl`  the issue went away. Weird.
