### ISSUE TITLE
Learners can't promote to voter for originally 3 node setup down to 1

### ISSUE THREAD

**Issue by stevefan1999-personal** [k3s-io/k3s#2467]
I upgraded to v1.19.3+k3s2 so I have to stop the nodes first. I stopped node 2, 1 then 0 one by one and tried to restart, only to see it failing refutably.

I did cluster-reset beforehand because I have an agent node to upgrade to master (my home server behind a NAT router seems to be able to be promoted to master), then I noticed that the peer IP addresses are not correct, I'm foolish enough to reset it. I started node 0 (supposedly leader/master) then node 1, but now node 1 seems to be stucking in eternity due to that there aren't enough voters for the learner to be promoted. 

So it sounds like this perhaps? I reset the cluster but the quorum is actually still remaining at 3, which means I need at least 2 votes to promote 1 learner, because node 1 and 2 is theoretically dead (I reset the cluster), now when node 1 re-joins, it is considered to be a learner, because I have 1/3 survival node in the cluster, which is not enough to promote node 1 either. 

The only way to go forward is, unfortunately, completely nuke the cluster.

Here's the log:
```
Oct 31 09:32:59 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:32:59.855Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:03 k3s-1 k3s[1088080]: time="2020-10-31T09:33:03.241969183Z" level=info msg="Failed to test data store connection: this server has not yet been promoted from learner to voting member"
Oct 31 09:33:03 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:03.700Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:05 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:05.366Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:08 k3s-1 k3s[1088080]: time="2020-10-31T09:33:08.245064725Z" level=info msg="Failed to test data store connection: this server has not yet been promoted from learner to voting member"
Oct 31 09:33:09 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:09.200Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:10 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:10.859Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:13 k3s-1 k3s[1088080]: time="2020-10-31T09:33:13.248012144Z" level=info msg="Failed to test data store connection: this server has not yet been promoted from learner to voting member"
Oct 31 09:33:14 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:14.701Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:16 k3s-1 k3s[1088080]: {"level":"info","ts":"2020-10-31T09:33:16.383Z","caller":"raft/raft.go:1530","msg":"fccabecbf9f53078 switched to configuration voters=(4666803214023224165) learners=(18215581426134626424)"}
Oct 31 09:33:18 k3s-1 k3s[1088080]: time="2020-10-31T09:33:18.251780626Z" level=info msg="Failed to test data store connection: this server has not yet been promoted from learner to voting member"
```

However I see that in node 1 I had actually grabbed some data from node 0 perhaps?
```
root@k3s-1:/var/lib/rancher/k3s/server# du -sh db/
196M    db/
```
And still there's no progression. Nothing.

**Comment by stevefan1999-personal** [comment]
I have ultimately decided to use ZeroTier for internal node communication. This also solved my NAT problem. However, since ZeroTier is a userland application and its severely bottlenecked by context switch, and it eats a lot of memory. I'll use it as a short term solution to find a better way to "mesh" things up.

Sigh. Nevermind, if k3s team decided this is a WONTFIX and want to close this issue, I won't mind.

**Comment by brandond** [comment]
Can you share more information on your order of operations? What sequence did you follow to reset the cluster and join the new node? Are you setting --node-external-ip or anything else that might influence node address selection on the servers?

Based on the logs you shared, the cluster currently has one voting member and one learner. Is the voting member online at the moment? What do the logs on the voting member show?

**Comment by stevefan1999-personal** [comment]
@brandond 
1. shut down all nodes with k3s-killall.sh
2. `rm -rf /var/lib/rancher/k3s/server/db` for each "worker master" node, leaving only node 0 to retain the original data
3. started `k3s server --cluster-init --cluster-reset", after that `systemctl start k3s` node 0 first, at this point the cluster is "functional"
4. but if i tried to add the second node, that error happen, and the "awaiting promotion" process stucks forever. this is not happening in `v1.19.3+k3s1` so perhaps this is a...regression?
5. i'm using zerotier for all workers and masters now, despite it being slow it is to my surprise it is not that unbearable (i mean i used to iperf ZT on lan and only got 300mbps), maybe k3s can even integrate ZT2, which is written in Go in the future lol.

**Comment by brandond** [comment]
Can you share the logs from the first node when this is all going on? Its the one that would be responsible for promoting the other nodes.

What are you using zerotier for? I've not used it before; it appears to be a peer-to-peer VPN mesh sort of thing? Are all your nodes not on the same network?

If it's slow, that could be part of the problem. Resetting the cluster doesn't wipe old data from etcd, it just removes records pertaining to cluster join/leave. Members can't be promoted until they've caught up with the rest of the cluster, so this will take longer when you've got more data in etcd. I wouldn't imagine it'd take more than a few minutes though...
