### ISSUE TITLE
k3s.io "this won't take long" missing sudo

### ISSUE THREAD

**Issue by SvenDowideit** [k3s-io/k3s#2469]
on https://k3s.io, there is a text at the top:

```
 curl -sfL https://get.k3s.io | sh -
  # Check for Ready node, 
  takes maybe 30 seconds
  k3s kubectl get node
```

running the last bit on a totally new system, fails:

```
$   k3s kubectl get node
The connection to the server localhost:8080 was refused - did you specify the right host or port?
``

considering `-rw------- 1 root root 1108 Nov  2 12:16 /etc/rancher/k3s/k3s.yaml`, I presume you mean to add `sudo` to that line too

```
$ sudo k3s kubectl get nodes
NAME        STATUS   ROLES    AGE   VERSION
onaci-010   Ready    master   23m   v1.18.9+k3s1
```

**Comment by brandond** [comment]
I think the instructions may assume you're running it as root.

**Comment by brandond** [comment]
@cjellick I'm not sure where the copy on get.k3s.io lives; it doesn't appear to be in the docs?

**Comment by spro** [comment]
"this won't take long" is pretty misleading when trying with a non-root user, the script uses sudo so it looks like it all went well and then you get stuck trying to actually use it.

**Comment by dereknola** [comment]
Closing as complete.
