### ISSUE TITLE
Restarting Kube-apiserver

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#247]
Hello, 

I have 2 questions : 

Is there a way to restart kube-apiserver ?
It is the only way I found to add a specific user to basic-auth-file .
Or is there any way to add a login/pass key into the basic-auth-file on startup ?

Second question : 
Is there a way to setup some kubelet environment variable ? ( I am looking to set KUBE_EDITOR="nano" ) :)

Regards,

**Comment by zsolt-keseru-epam** [comment]
I would be interested in the first question as well, it's somewhat related to my issue too.

For the second question: the KUBE_EDITOR is not kubelet related, you can easily set it for your kubectl command, for example this command would edit a pod with nano:
```KUBE_EDITOR=nano k3s kubectl edit pod POD_NAME```

**Comment by brandond** [comment]
Closing due to age.
