### ISSUE TITLE
CIFS Support

### ISSUE THREAD

**Issue by thecrazyrussian** [k3s-io/k3s#2472]
We are planning on utilizing k3s in multiple embedded setups that require CIFS support. Can we add an out of band cifs provisioner/client for k3s?

gz#13203

**Comment by brandond** [comment]
Yes, you should be able to use out-of-tree provisioners/CSI drivers.

**Comment by dnoland1** [comment]
Right, wouldn't something like this work - https://github.com/kubernetes-csi/csi-driver-smb ?

**Comment by thecrazyrussian** [comment]
Awesome, thanks David. I'll give that a go.

**Comment by brandond** [comment]
@thecrazyrussian did you get this working?

**Comment by thecrazyrussian** [comment]
Oh yeah, flawlessly, also as a client for encrypted shares.

**Comment by doug62** [comment]
I am running K3s from a docker-compose (supplied in this repo), I am unable to install Longhorn & the cs-driver-smb, for the SMB i keep getting:
skipping: failed to "StartContainer" for "smb" with CreateContainerError: "failed to generate container \"xxx\" spec: failed to generate spec: path \"/var/lib/kubelet/\" is mounted on \"/var/lib/kubelet\" but it is not a shared mount"
