### ISSUE TITLE
K3s with docker as default container

### ISSUE THREAD

**Issue by sandhyarme** [k3s-io/k3s#2490]
Hi,

I am trying to install k3s with docker as container on  centos 7 vm, receiving below error.

"starting kubernetes: preparing server: creating storage endpoint: building kine: pq: SSL is not enabled on the server"

Have followed steps as mentioned in 
https://rancher.com/docs/k3s/latest/en/advanced/#using-docker-as-the-container-runtime
Docker is up and running.
With k3s server install  -Failed to start Lightweight Kubernetes.
Attached entire log from journalctl -xe

[log.txt](https://github.com/rancher/k3s/files/5507357/log.txt)

**Comment by brandond** [comment]
Have you enabled ssl on your postgres server, or disabled ssl in you datastore connection string?

**Comment by sandhyarme** [comment]
How to enable ssl on postgres server ?

**Comment by sandhyarme** [comment]
With below datastore settings we could install k3s.
export K3S_DATASTORE_ENDPOINT='postgres://postgres:postgres@15.213.141.54:5432/postgres?sslmode=disable'

[root@kong bin]# kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
kong.master   Ready    master   80s   v1.18.9+k3s1

But the pods are not comming up, it shows container creating state.

[root@kong bin]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS              RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-v82fp   0/1     ContainerCreating   0          17m
kube-system   coredns-7944c66d8d-gchf2                 0/1     ContainerCreating   0          17m
kube-system   metrics-server-7566d596c8-gxxcf          0/1     ContainerCreating   0          17m
[root@kong bin]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@kong bin]#

**Comment by sandhyarme** [comment]
[root@kong lib]# ls
NetworkManager  authconfig  dbus      dnf     dockershim  initramfs  logrotate  misc  os-prober  polkit-1  rancher  rpm-state  selinux    systemd  vmware
alternatives    containerd  dhclient  docker  games       kubelet    machines   ntp   plymouth   postfix   rpm      rsyslog    stateless  tuned    yum

Containerd also exists along with docker(/var/lib path), so while installing k3s with docker conatiner do we need to disable conatinerd ?

**Comment by janeczku** [comment]
```
Nov 09 16:48:32 kong.master dockerd[30524]: time="2020-11-09T16:48:32.108069660+05:30" level=error msg="Handler for POST /v1.38/images/create returned error: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```
@sandhyarme You will need to configure the Docker system daemon to use your corporate proxy (web-proxy.in.hpecorp.net):
https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
