### ISSUE TITLE
Sqlite TO MySQL

### ISSUE THREAD

**Issue by liyongxian** [k3s-io/k3s#2491]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
**K3s Backend Storage is Sqlite.Now Backend Storage Switch To  MySQL,and Wants to Stay The Data of Sqlite. Sqlite To MySQL,How To  Do. Thanks.**
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
We do not have any supported tools for migrating data between storage backends. You might look at something like Velero.
