### ISSUE TITLE
Pod cannot access company internal DNS 

### ISSUE THREAD

**Issue by BoDING1007** [k3s-io/k3s#2494]
**Environmental Info:**
K3s Version: 

k3s version v1.18.9+k3s1 (630bebf9)
Node(s) CPU architecture, OS, and Version: 

Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

single node cluster

**Describe the bug:**

Install K3S on top of Windows 10 WSL2 Ubuntu-18.04 LTS. Domain name resolution from a Kubernetes pod is not working for company internal domain names. However it works fine from the Ubuntu shell. Company is using an intranet DNS server for the internal domains and Ubuntu in WSL2 seems to be resolving them properly.

**Steps To Reproduce:**

- Enable WSL2 in window 10 build number: 10.0.18363 or higher
- Install Ubuntu-18.04 LTS 
- Install systemd (https://github.com/DamionGans/ubuntu-wsl2-systemd-script)
- Install Docker (https://docs.docker.com/engine/install/ubuntu/)
- Install K3s:  (curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode=644 --kube-apiserver-arg=service-node-port-range=1-60000 --no-deploy=traefik,servicelb --resolv-conf=/run/systemd/resolve/resolv.conf --docker)
- Open WSL2 Ubuntu:

In Linux:
1. wget google.com, works.
2. Curl or wget a company_internal_URL, got response. 

In Pod: 
1. wget google.com, works.
2. wget same company_internal_URL, got 'bad address' error.

It looks like CoreDNS is not picking up the DNS settings configured in the WSL2 host.

**Expected behavior:**

Pod should be able to access to company_internal_URL like WSL2 ubuntu .

**Actual behavior:**

Pod cannot access to company_internal_URL but WSL2 ubuntu host can.

**Additional context / logs:**

gz#13342

**Comment by discordianfish** [comment]
Had the same issue, in my case it was due to k8s using the hosts' /etc/resolv.conf and if that contains 127/8 IP, it will use 8.8.8.8 as dns, bypasing your hosts/companies DNS server. Fix was setting `kubelet-arg: "resolv-conf=/run/dnsmasq/resolv.conf"` (in my case) in /etc/rancher/k3s/config.yaml


----
If some maintainer comes across this issue. Don't want to open a separate issue but despite setting `resolv-conf`, k3s still prints this warning which is misleading since it appears to not use the autogenerated resolv.conf (as expected):

> May 03 11:41:52 rpi-kitchen k3s[10801]: time="2023-05-03T11:41:52+01:00" level=warning msg="Host resolv.conf includes loopback or multicast nameservers - kubelet will use autogenerated resolv.conf with nameserver 8.8.8.8"

**Comment by discordianfish** [comment]
@brandond Ah, thanks for the clarification!

Maybe consider pointing this out in the getting started guide since I believe many will overlook the warning in the log and just be surprised that some random names are unresolvable. Took me a while to figure this out.

**Comment by brandond** [comment]
Most people don't need to use this flag, so we don't cover it in the getting-started guide. It is covered in the agent configuration docs though.
