### ISSUE TITLE
Specify TLS Version on Ingress level

### ISSUE THREAD

**Issue by garrit-schroeder** [k3s-io/k3s#2524]
**Environmental Info:**
K3s Version: 

k3s version v1.19.3+k3s2 (f8a4547b)

Node(s) CPU architecture, OS, and Version: 

Linux v22019068602391930 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

One Server Master & Node
**Describe the bug:**

Unable to set the TLS minimal version of ingress.
**Steps To Reproduce:**

- Installed K3s: 

my ingress config:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/tls-minimum-version: "1.2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: hello-world-ingress
  namespace: default
spec:
  rules:
    - host: hello.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80
  tls:
    - hosts:
        - hello.mydomain
      secretName: my-cert

**Expected behavior:**

    ingress.kubernetes.io/tls-minimum-version: "1.2" should change the minimal tls version. 

**Actual behavior:**

External scan showed that tls 1.0 & 1.1 is still enabled.

**Additional context / logs:**

**Comment by brandond** [comment]
It looks like traefik doesn't support this annotation, or setting TLS options on a per-ingress level at all. It can only be set on the https entrypoint:

https://github.com/helm/charts/pull/5616/files

**Comment by garrit-schroeder** [comment]
I did more research and it looks like traefik V2 does support this annotation (probably set a bit different) 
1. Do you know at what point k3s will switch to V2
2. How can I change the default configuration on v1? 

Thank you

**Comment by brandond** [comment]
1. We don't currently have a timeline for going to traefik v2.
1. You can customize the chart using the values from the link I posted above: `ssl.tlsMinVersion`. The easiest way to do this would probably be to use a HelmChartConfig as documented here: https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by garrit-schroeder** [comment]
And just another security input from my site. 
Default SSL/  TLS settings should be adjusted to provide secure ingress connections out of the box. 

Report of ssllabs
![Screenshot_20201114-135404](https://user-images.githubusercontent.com/12541078/99147399-fc919200-2680-11eb-928d-91069ba79fc3.jpg)

**Comment by garrit-schroeder** [comment]
# generated 2020-11-14, Mozilla Guideline v5.6, Traefik 1.7.22, intermediate configuration
# https://ssl-config.mozilla.org/#server=traefik&version=1.7.22&config=intermediate&guideline=5.6
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]

      # due to Go limitations, it is highly recommended that you use an ECDSA
      # certificate, or you may experience compatibility issues
      [[entryPoints.https.tls.certificates]]
      certFile = "/path/to/signed_cert_plus_intermediates"
      keyFile = "/path/to/private_key"

**Comment by brandond** [comment]
I'm not sure what you've posted - are those traefik settings that worked for you?

**Comment by garrit-schroeder** [comment]
The screenshot is taken from the site https://www.ssllabs.com/ssltest/analyze.html checking my private ingress to my kubernetes cluster. (not changing any default settings). This shows that tls settings should be tweaked (immediatly). For example disabling TLS 1.0 & 1.1 and disabling weak ciphers.

The second config is automatically generated by mozilla. They are providing secure and up to date configurations for many web servers. I just copy pasted their recommendation. 

I think that k3s should apply the intermediate configuration by mozilla by default in traefik. I am going to test that configuration probably during this week.

**Comment by DibbsZA** [comment]
@garrit-schroeder How did your test go?

**Comment by foobarbecue** [comment]
So, how do we use k3s with bundled traefik and get a recent version of TLS?

**Comment by garrit-schroeder** [comment]
Going to check tomorrow and the following days this week. Got a bit caught up in other stuff.

To change this behaviour you probably have to modify the traefik.toml. Going to post my results here later.

**Comment by foobarbecue** [comment]
Ok, I managed to do it by editing the traefik.toml inside the traefik configmap according to https://doc.traefik.io/traefik/v1.7/configuration/entrypoints/ and then deleting the pod to trigger update.

**Comment by brandond** [comment]
That will probably get reverted when you restart, you may need to configure the helm chart to get it to stick.

**Comment by balibebas** [comment]
> 1. We don't currently have a timeline for going to traefik v2.

Seeing as how Traefik 2 [was merged](https://github.com/k3s-io/k3s/issues/1141#issuecomment-792036498) 13 days ago you won't need to.

**Comment by balibebas** [comment]
> 1. We don't currently have a timeline for going to traefik v2.

Seeing as how Traefik 2 [was merged](https://github.com/k3s-io/k3s/issues/1141#issuecomment-792036498) about two weeks ago you won't need to.

**Comment by brandond** [comment]
Note that this won't be in a release until v1.21

**Comment by foobarbecue** [comment]
Is there an easy way to install k3s master branch?

**Comment by brandond** [comment]
When using the installer, you can set INSTALL_K3S_COMMIT to the value of any git commit hash that has been built by CI to install that version.

**Comment by eumel8** [comment]
A default TLSOption is helpful to get grade A by Qualys SSL Check for all Ingress as described [here](
https://doc.traefik.io/traefik/v2.2/https/tls/#tls-options)

```yaml
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
    - TLS_AES_256_GCM_SHA384                  # TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true
```
