### ISSUE TITLE
Managed etcd should detect and handle `member has been permanently removed from the cluster` errors

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2527]
**Environmental Info:**
K3s Version: 
1.19.x

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
Managed etcd

**Describe the bug:**
As of https://github.com/rancher/k3s/commit/de18528412439ed1802d93bc19236d414c40023e#diff-74aae7a0c94d0bae304e13a2914cfca90237ef9b957903c42a0549b066e01b58 we are watching the StopNotify channel of embedded etcd to see when it stops - but there is no feedback as to WHY it stopped. This approach also does not work on rke2 where we do not watch for etcd pod termination at all.

As discussed in the thread at https://github.com/rancher/k3s/pull/2399#discussion_r509575496 we need some way to access the errors here: 
   ```
   {"level":"warn","ts":"2020-10-21T12:28:51.439-0700","caller":"etcdserver/server.go:1095","msg":"server error","error":"the member has been permanently removed from the cluster"}
   {"level":"warn","ts":"2020-10-21T12:28:51.439-0700","caller":"etcdserver/server.go:1096","msg":"data-dir used by this member must be removed"}
   ```
and handle it by rotating the current data dir out of place so that we can rejoin the cluster. We need to do this in a way that works for both k3s and rke2.

**Steps To Reproduce:**
1. Create 3-node k3s cluster using managed etcd (--cluster-init, etc)
1. Stop k3s on node 3
1. Run `kubectl delete node <node 3>` to remove stopped node from both k3s and etcd cluster
1. Start k3s on node 3

**Expected behavior:**
* K3s should rejoin the cluster

**Actual behavior:**
* K3s fails to join cluster due to having been marked as permanently deleted from the etcd cluster

**Additional context / logs:**
Final blocker for rancher/k3s#2398

**Comment by ShylajaDevadiga** [comment]
Using commit id fadc5a8057c244df11757cd47cc50cc4a4cf5887, unable to start k3s.
Steps followed
1. Create a 3 node cluster
```
kubectl get nodes
NAME               STATUS   ROLES         AGE    VERSION
ip-172-31-0-250    Ready    etcd,master   16m    v1.19.4+k3s-fadc5a80
ip-172-31-11-233   Ready    etcd,master   36m    v1.19.4+k3s-fadc5a80
ip-172-31-13-162   Ready    etcd,master   8m2s   v1.19.4+k3s-fadc5a80
```
2. Stop k3s on node3
```
ubuntu@ip-172-31-13-162:~$ sudo systemctl stop k3s
```
3. Delete node 3 to remove  from cluster
```
ubuntu@ip-172-31-11-233:~$ kubectl delete node ip-172-31-13-162
ubuntu@ip-172-31-11-233:~$ kubectl get nodes
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-0-250    Ready    etcd,master   18m   v1.19.4+k3s-fadc5a80
ip-172-31-11-233   Ready    etcd,master   38m   v1.19.4+k3s-fadc5a80
```
4. Starting k3s on node3 is stuck
```
sudo systemctl start k3s

```
Logs
```
Dec 08 16:50:20 ip-172-31-13-162 k3s[3084]: time="2020-12-08T16:50:20.908136938Z" level=error msg="Failed to check local etcd status for learner management: context deadlin>
Dec 08 16:50:20 ip-172-31-13-162 k3s[3084]: {"level":"warn","ts":"2020-12-08T16:50:20.908Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to>
Dec 08 16:50:21 ip-172-31-13-162 k3s[3084]: {"level":"warn","ts":"2020-12-08T16:50:21.064Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker fai>
Dec 08 16:50:21 ip-172-31-13-162 k3s[3084]: time="2020-12-08T16:50:21.064503701Z" level=info msg="Failed to test data store connection: context deadline exceeded"
```

**Comment by davidnuzik** [comment]
Backport https://github.com/k3s-io/k3s/pull/2667 is in to 1.19 release branch.

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 989c9369
k3s version v1.19.4+k3s-989c9369

Steps followed as discussed with @galal-hussein 
1. Create a 3 node cluster
2. Verify nodes are ready and pods are running
3. Delete node3 using kubectl delete node
4. Verify tombstone file is created.
5. Restart k3s on deleted node and validate the node is joined back to the cluster

Issue seen during node deletion #2669

```
ubuntu@ip-172-31-21-160:~$ kubectl get nodes 
NAME               STATUS   ROLES         AGE     VERSION
ip-172-31-20-19    Ready    etcd,master   71s     v1.19.4+k3s-989c9369
ip-172-31-21-160   Ready    etcd,master   3m38s   v1.19.4+k3s-989c9369
ip-172-31-23-61    Ready    etcd,master   2m10s   v1.19.4+k3s-989c9369

ubuntu@ip-172-31-21-160:~$ kubectl delete node ip-172-31-20-19
node "ip-172-31-20-19" deleted

ubuntu@ip-172-31-21-160:~$ kubectl get nodes
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-21-160   Ready    etcd,master   11m   v1.19.4+k3s-989c9369
ip-172-31-23-61    Ready    etcd,master   10m   v1.19.4+k3s-989c9369

ubuntu@ip-172-31-20-19:~$ sudo ls /var/lib/rancher/k3s/server/db/etcd
config	member	name  tombstone

ubuntu@ip-172-31-20-19:~$ sudo systemctl restart k3s

ubuntu@ip-172-31-21-160:~$ kubectl get nodes
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-20-19    Ready    etcd,master   28m   v1.19.4+k3s-989c9369
ip-172-31-21-160   Ready    etcd,master   40m   v1.19.4+k3s-989c9369
ip-172-31-23-61    Ready    etcd,master   39m   v1.19.4+k3s-989c9369
```
