### ISSUE TITLE
when I build k3s in my dev

### ISSUE THREAD

**Issue by yyf1986** [k3s-io/k3s#2538]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

 git clone https://github.com/rancher/k3s.git
cd cmd/k3s
go build -mod=vendor

```
D:\github.com\learn\k3s\cmd\k3s>go build -mod=vendor
main.go:13:2: cannot find package "." in:
        D:\github.com\learn\k3s\pkg\data
```

```
import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/pkg/errors"
	"github.com/rancher/k3s/pkg/cli/cmds"
	"github.com/rancher/k3s/pkg/data"
	"github.com/rancher/k3s/pkg/datadir"
	"github.com/rancher/k3s/pkg/dataverify"
	"github.com/rancher/k3s/pkg/flock"
	"github.com/rancher/k3s/pkg/untar"
	"github.com/rancher/k3s/pkg/version"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)
```
then I can not find 'pkg/data' in my local path.

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by yyf1986** [comment]
How to build from source?

**Comment by brandond** [comment]
Follow the instructions in https://github.com/rancher/k3s/blob/master/BUILDING.md
