### ISSUE TITLE
Supported OCI complaint container runtimes for K3s

### ISSUE THREAD

**Issue by Mohid-A** [k3s-io/k3s#2539]
Hi There,
I am doing some evaluation on supported OCI container platforms for K3S, need more insights on the following queries?  
Does K3s support all OCI compliant runtimes like the upstream K8s version? In the documentation, I could see it only supports/mentions containerd and Docker?

Is the integration of kubevirt, is supported and tested with the K3s?

Appreciate your inputs.

Thanks

**Comment by brandond** [comment]
1. We support containerd and docker, as you deduced from our documentation. Others may work but we haven't tested them and don't support them.
1. Kubevirt should work as well as it does on any other Kubernetes distribution. We don't document anything other than k3s itself so you won't find any documentation for it on our site; you should be able to follow the normal steps to install it as you would anywhere else.

**Comment by abdul-muqees** [comment]
Hi Brad,

Thanks for your reply, if i want to test any other container engine such as
podman what would be the available option should I use to test them ?

Any other documentation or technical support team i could reach to to check
the k3s compatability with the other container  runtimes ?

Thanks,
Abd

**Comment by oskapt** [comment]
@abdul-muqees I was asked by Shannon to respond to the email you sent. To keep things clean, I'll post my response here, and this is where the conversation can continue.

> 1) Is there any specific reason why k3s by default uses containerd and not Docker? Which is more preferable to use based on your testing and the benefits associated with using containerd over docker?

"Docker" is more than just the container engine. It also includes orchestration (Swarm), volumes, buildkit, networking, and distribution. These are features that aren't necessary if all you want to do is run containers. The engine within Docker is containerd (https://www.docker.com/products/container-runtime). K3s strives to be small and fast, and to do so it strips out unneeded components. This includes all of the stuff that comes with Docker that isn't needed, other than containerd.

For environments that already have Docker installed, the `--docker` flag leverages that installation and doesn't deploy containerd.

> 2) If I want to test any other container runtime example podman, cri-o, rkt ? Is there any option available to integrate another container runtime with k3s, as we do for Docker by passing the argument " --docker option  ( curl -sfL https://get.k3s.io | sh -s - --docker)" ?

At the moment, no. Development on rkt stopped in 2018 (https://github.com/rkt/rkt).  It's a dead project. CRI-O may be on the roadmap, but I don't have information on when it will be available. Podman is a standalone solution for running Pods without orchestration (e.g. without Kubernetes). It isn't a container engine that one would use with Kubernetes.

If you'd like support for CRI-O, please create a new issue for the feature request. Feature requests are prioritized according to demand from the community. 

Do you have any other questions?

**Comment by Mohid-A** [comment]
@oskapt Thanks for your detailed response. I read somewhere that contained is recommended container runtime with k3s. 
In what scenarios, replacing Docker as the runtime for k3s will be more useful? Any significant difference in the performance, security-wise, compatibility or any notable benefits. I have screen through the k3s documentation and other publications to learn more about the above scenario but had no luck with finding the appropriate answer. Maybe if you can shed some light on this that would be very helpful?

**Comment by cawoodm** [comment]
I just installed K3S and it demanded I first install Docker. This was surprising and confusing given Kubernetes deprecated Docker.

**Comment by brandond** [comment]
> I just installed K3S and it demanded I first install Docker.

Our install script does no such thing. Where did you install K3s from?

**Comment by cawoodm** [comment]
I always use `curl -sfL https://get.k3s.io | bash` but I cannot quite remember if it was the K3S intsallation or a later step which forced me to use docker.

The issue was I needed to tell Kubernetes to use a private repo (in my case DockerHub) with credentials:
```
kubectl create secret docker-registry regcred --docker-server=index.docker.io --docker-username=mydockeruser --docker-password=*** --docker-email=me@***
kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}'
```
I think at this point I had to install Docker to proceed.

**Comment by cawoodm** [comment]
I think I know what the confusion was. I was following the official Kubernetes [use a private registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) docs and it's example starts off with docker cli commands. I did not realize they meant (and said) "on your laptop" and ended up installing docker on the server. It seems however that kubectl is still superfocoaööy "wedded" to docker with official commands like `kubectl create secret docker-registry ...`.

**Comment by brandond** [comment]
@cawoodm I think you probably want to follow the instructions at https://rancher.com/docs/k3s/latest/en/installation/private-registry/ instead.
