### ISSUE TITLE
Unexpected behavior in HA

### ISSUE THREAD

**Issue by lexfrei** [k3s-io/k3s#2540]
**Environmental Info:**
K3s Version: 
`k3s version v1.19.3+k3s3 (0e4fbfef)`

Node(s) CPU architecture, OS, and Version: 
```
NAME       STATUS   ROLES         AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
master01   Ready    etcd,master   17m   v1.19.3+k3s3   192.168.5.100   <none>        Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.1-k3s1
master02   Ready    etcd,master   12m   v1.19.3+k3s3   192.168.5.101   <none>        Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.1-k3s1
node01     Ready    <none>        12m   v1.19.3+k3s3   192.168.5.111   <none>        Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.1-k3s1
node02     Ready    <none>        12m   v1.19.3+k3s3   192.168.5.112   <none>        Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.1-k3s1
node03     Ready    <none>        12m   v1.19.3+k3s3   192.168.5.113   <none>        Ubuntu 20.04.1 LTS   5.4.0-1022-raspi   containerd://1.4.1-k3s1
```

Cluster Configuration:
2 masters, 3 workers

**Describe the bug:**
Disabled components appear in the cluster if the initial master powered off and the secondary is rebooted

**Steps To Reproduce:**
1. On initial master: `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest INSTALL_K3S_EXEC="server --server https://master01:6443 --disable traefik,local-storage,servicelb,metrics-server --cluster-domain k8s.home.lex.la --flannel-backend=wireguard --cluster-init" sh -`
2. On another master: `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest K3S_TOKEN=TOKEN-FROM-MASTER INSTALL_K3S_EXEC="server --server https://master01:6443" sh -`
3. Turn off both masters
4. Boot the only 2nd one

**Expected behavior:**
No traefik, local-storage, servicelb and metrics-server in the cluster

**Actual behavior:**
Traefik, local-storage, servicelb, and metrics-server are deployed. Also, they stay deployed when the initial master comes back.

**Additional context / logs:**
This is not expected behavior. At least, in docs should be mentioned the manual cloning of all arguments from the initial master. The secondary master should not change the components state.
I can understand why it works this way, but this is not a HA, just horizontal scaling if I should keep alive my initial master. Potential race condition on power loss.

**Comment by brandond** [comment]
1. Yes, anything you want to `--disable` needs to be disabled on all servers
1. Two etcd servers are incapable of meeting quorum when one server is down. If either server goes offline the entire cluster will be unavailable, see: https://etcd.io/docs/v3.3.12/faq/#why-an-odd-number-of-cluster-members

**Comment by lexfrei** [comment]
It's not clear behavior at least for me. Not the k8s part, but how k3s (not) cloning starting arguments in HA mode.
Here is my note to your docs about this moment.
