### ISSUE TITLE
K3s CIS Docs

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2541]
Task tracking work required to build out docs for K3s CIS.
Once we have the material ready we'll need to partner with Catherine. It will be necessary to create a rancher/docs issue so Catherine can add this to the live k3s docs site.

**Comment by davidnuzik** [comment]
This is in v1.19 - Backlog milestone because it's not directly tied to a K3s release. We do want this as soon as possible - it's not an actual backlog item.

**Comment by briandowns** [comment]
PR to the docs repo. https://github.com/rancher/docs/pull/2882

**Comment by davidnuzik** [comment]
Closing. https://github.com/rancher/docs/pull/2882 has been merged.
