### ISSUE TITLE
Nightly Automation Runs

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2557]
In our 11/19/2020 design call, the idea of nightly automation runs was proposed. This may help to prevent the addition of further tests to CI which would cause slower CI runs.

The idea is we can run sensical tests nightly separately from the CI pipeline such as tests for running docker as the CRI.

**Comment by ShylajaDevadiga** [comment]
Closing as duplicate https://github.com/k3s-io/k3s/issues/2958
