### ISSUE TITLE
Specify resource specifications (CPU/memory) for K3S pods

### ISSUE THREAD

**Issue by aalcaraz97** [k3s-io/k3s#2559]
Is there any possibility to specify resource specifications like:

```
resources: 
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 150m
    memory: 200Mi
```
in the K3S pods deployed in the kube-system namespace?

The only K3S pods I am deploying in my current setup are:

- metrics-server
- local-path-provisioner
- coredns

I'm currently installing K3S by downloading the install.sh script, and executing the following command:
```
  INSTALL_K3S_SKIP_DOWNLOAD=true \
  INSTALL_K3S_EXEC='--disable=traefik' \
  INSTALL_K3S_SYMLINK=force ./install.sh
```

And after the installation of K3S, the kube-system pods do not have any CPU/Memory limits or requests (except the coredns pod). 
If I describe the server node where I have K3S deployed:

```
$ kubectl describe node <server-node>
Non-terminated Pods:        (17 in total)
Namespace                   Name                                              CPU Requests  CPU Limits    Memory Requests  Memory Limits  AGE
---------                   ----                                              ------------  ----------    ---------------  -------------  ---
kube-system                 metrics-server-7b4f8b595-2tfgx                    0 (0%)        0 (0%)        0 (0%)           0 (0%)         122m
kube-system                 coredns-66c464876b-mdbk9                          100m (5%)     0 (0%)        70Mi (1%)        170Mi (2%)     122m
kube-system                 local-path-provisioner-7ff9579c6-msch5            0 (0%)        0 (0%)        0 (0%)           0 (0%)         122m
[...]
```
I have also looked into the `/var/lib/rancher/k3s/server/manifests` folder after the K3S installation, and checked the contents of the K3S Deployment YAML files:
- coredns.yaml 
- metrics-server/metrics-server-deployment.yaml 
- local-storage.yaml
 
None of them has any resource specifications in the YAML files.

Is there any way I can specify in the install script to use resource specifications?

OS used: CentOS Linux release 7.8.2003 (Core)
K3S version used: k3s v1.19.2+k3s1

**Comment by gbarton** [comment]
I would like this as well, I dont want k8s to unschedule my coredns because its effectively lowest priority due to no limits defined.

**Comment by brandond** [comment]
Setting the priority class should prevent it from getting unchseduled. Adding requests and potentially limits as well would be good, but that's a bit harder to take on as we can't guarantee they'll work for everyone since k3s is used in a wide variety of environments.
