### ISSUE TITLE
Set apiserver hostname and ip address

### ISSUE THREAD

**Issue by mschuchard** [k3s-io/k3s#256]
**Is your feature request related to a problem? Please describe.**
In Vagrant I would like to use k3s with Helm and other instances.

**Describe the solution you'd like**
I would like to specify the apiserver hostname and ip address. This functionality is analogous to `--apiserver-names=<hostname> --apiserver-ips=ipaddr` arguments  to `minikube start`. If this could be done in the `k3s server` command, then great, but any valid solution would be nice.

**Describe alternatives you've considered**
Unsure

**Additional context**
This may be subsumed by #72

**Comment by erikwilson** [comment]
Not sure if this is addressed with rancher/k3s/pull/239 or rancher/k3s/pull/250

**Comment by mschuchard** [comment]
Going to give this another go soon since I just saw this seems to be configurable and handled now.

**Comment by cbluth** [comment]
@mschuchard 
please report back if you have success, i am trying to do the same thing.

**Comment by mschuchard** [comment]
It did not work. Changing the bind address and hostname (but I would guess primarily the bind address) on the API server, and then the address on the scheduler and controller, causes Prometheus to fail to start up during the k3s server initialization. This is treated as a fatal error.

This works when configured with Minikube and works automatically with Microk8s (somehow it gets the correct hostname and bind address without input configuration), so I have to stick to single node portable labs for the time being.

**Comment by erikwilson** [comment]
Flags that might help in addition to `tls-san` are `node-ip`, and `flannel-iface`. The main issue with vagrant I think is that eth0 is NAT and the default route which is not addressable between nodes, for node-to-node communication everything needs to talk over eth1. I think a good idea might be for us to create a flag which specifies some interface for k3s and auto-populates the other values from that.

**Comment by mschuchard** [comment]
Yeah I was using the `eth1` address for the `bind-address`. I may very well have missed all of the places where the `eth0` address needs to be replaced with the `eth1`. This kind of thing is easily automated on the provision side though with software provisioning facts, but I just need to know what places need configuration.

Basically I cannot connect to the instance with Kubectl or Helm on my host device after adding the `kubeconfig`, which is what I use as my test for functionality here.

**Comment by erikwilson** [comment]
Sorry, I have not tried this yet. It works without issue using minikube?
Is it an issue with exposing ports through vagrant/virtualbox? 
Does the hostname in the kubeconfig need to change? 
More info with the specific error is appreciated! :)

**Comment by cbluth** [comment]
the errors are all related to the ssl validation, usually hostname mismatch for me.

I have reported another issue here, mostly likely related: https://github.com/rancher/k3s/issues/469

**Comment by nrvale0** [comment]
@mschuchard : I've been testing some Helm Charts via k3s in Vagrant and using [this](https://github.com/nrvale0/sandbox-vagrant-k3s/blob/master/vms/ctrlplane/bootstrap.sh#L72) to bootstrap the master/control plane. I've not noticed any problems related to API server, TLS, etc.

**Comment by erikwilson** [comment]
It looks like there is a bug with the tls-sans flag where it will only take IPs, I will take a closer look and should have fix out for next release.

**Comment by mschuchard** [comment]
@nrvale0 I was not configuring the flannel interface. I will give that a shot next time.

**Comment by iMartyn** [comment]
@erikwilson whilst you check that out (assuming you haven't done so already.... time has passed but no update, so not sure), can you allow multiple entries?  e.g. I want to pass the IP and a hostname in the sans, and relying on the fact that it always says "a" in the docs, it must only take one right?

**Comment by brandond** [comment]
@iMartyn I believe you can specify it multiple times and they will all be collected: 
`--tls-san=1.1.1.1 --tls-san=2.2.2.2`
