### ISSUE TITLE
Revisit using systemd notifications

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#2577]
https://github.com/rancher/k3s/issues/2548#issuecomment-732387569 we are changing from `Type=notify` to `Type=exec`. We should revisit this when we have time, and potentially change back to using `Type=notify` for our `systemd` unit file.

cc @dweomer

**Comment by brandond** [comment]
Possibly related: https://github.com/rancher/k3s/issues/2502

**Comment by Oats87** [comment]
Closing as we are not going to change the unit type.
