### ISSUE TITLE
Provide Means of Passing Etcd Args from CLI

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#2582]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
There are some use cases where it'd be preferred to have the ability to pass additional parameters to start etcd with. For example, passing parameters that would make it comply with CIS 1.x guidelines.

**Describe the solution you'd like**
K3S currently provides a means of passing additonal arguments to the K8S control plane using args like `--kube-apiserver-arg`, `--kube-controller-manager-arg`, `-kube-scheduler-arg`, and `--kubelet-arg`. A similar argument can be introduced to the `server` subcommand for etcd. E.g. `--etcd-arg` and can function in the same manner.

**Describe alternatives you've considered**

**Additional context**

**Comment by LarsBingBong** [comment]
isn't this implemented now? See `--etcd-arg value` [here](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/) - under the **K3s Server CLI Help** header.

**Comment by dereknola** [comment]
This has now been implemented, closing as complete.
