### ISSUE TITLE
k3s service manipulates the cgroups of the independent Docker service

### ISSUE THREAD

**Issue by janeczku** [k3s-io/k3s#2587]
**Environmental Info:**
K3s Version: v1.19.3+k3s3

**Describe the bug:**

Starting k3s with the `--docker` flag causes the `dockerd` process (owned by `docker.service`) to be moved from it's original cgroup  `/system.slice/docker.service` to `/systemd/system.slice/docker.service`.

**Steps To Reproduce:**

1. `systemctl start docker`
2. Check cgroup hierarchy with `systemd-cgls`
```
└─system.slice
  ├─docker.service
  │ └─8280 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
  ├─containerd.service
  │ └─5807 /usr/bin/containerd
```
3. `systemctl start k3s`
4. Check cgroup hierarchy with `systemd-cgls`

```
├─systemd
│ └─system.slice
│   ├─5818 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
│   └─5967 /usr/local/bin/k3s server
└─system.slice
  ├─containerd.service
  │ ├─5807 /usr/bin/containerd
```

**Expected behavior:**

k3s should not move processes owned by independent systemd units.

**Comment by brandond** [comment]
Is k3s explicitly doing this, or does the kubelet do this as a side effect? The latter, I believe.

**Comment by Oats87** [comment]
The kubelet is doing this because we (K3s) are setting the `--runtime-cgroups` flag on the kubelet to `/systemd/system.slice`

**Comment by brandond** [comment]
Related to #2548
