### ISSUE TITLE
Write Out Control Plane Config Files at Start Up

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#2588]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**

It would be helpful to write out control plane config files, ie kube-apiserver, kube-controller-manager, kube-scheduler, kubelet, and etcd to provide the user/operator the knowledge of how the system was started. This also provides a simple solution to provide users/operators a means of performing security scans and/or audits.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/50041#issuecomment-412591736
