### ISSUE TITLE
vsphere pvc ?

### ISSUE THREAD

**Issue by chris93111** [k3s-io/k3s#2589]
hello 

sorry to post it here, I couldn't find a discussion queue

i know nfs, longhorn work but VMware Vsphere volume is compatible with k3s ? 
i have error with plugin not found but i don't see plugin available for vsphere 

thanks

**Comment by brandond** [comment]
I'm not sure what you're looking for. Are you trying to find a CSI driver or cloud controller for vsphere? Neither of these would be k3s specific.

**Comment by chris93111** [comment]
yes is VMware Vsphere volume , is work with rancher and cloud-init

**Comment by djerfy** [comment]
Hi @chris93111, you can use Kubernetes vSphere CSI Driver ([documentation is here](https://vsphere-csi-driver.sigs.k8s.io/))

**Comment by brandond** [comment]
I'm not sure what you mean about working with rancher and cloud-init? The CSI driver should work fine in K3s but that wouldn't have any direct interactions with either rancher or cloud-init.

**Comment by chris93111** [comment]
@djerfy thanks so csi is compatible

@brandond it's with vsphere volume , is not csi driver

thanks

**Comment by brandond** [comment]
I'm still not sure what you're trying to ask if not about the vmware vsphere csi driver.
