### ISSUE TITLE
K3s should respect `--data-dir`, `-d` at a global level

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#2593]
Today, K3s does not allow setting `--data-dir` for packaged commands such as `kubectl`, i.e. it is not possible to do a `k3s kubectl --data-dir=/<my-desired-datadir>` or `k3s --data-dir=/<my-desired-datadir> kubectl`. This is not desirable behavior as our self-extracting wrapper will proceed to unzip a full `k3s-root` into `/var/lib/rancher/k3s/data` while the user may have already specified their own `data-dir` whether through CLI flag or config file.

We should be more global in our acceptance of `data-dir`, hence allowing it to be specified when calling commands like `kubectl` and so forth. In addition, we should be global in our acceptance of `config-file` for the case when `data-dir` is specified in our config file.

We should be able to source our specified `data-dir` when we have specified it in the config file, regardless of what subcommand we are running, as specified in the bug here: https://github.com/rancher/k3s/issues/2563

**Comment by ShylajaDevadiga** [comment]
Validated in the scope of #2563
