### ISSUE TITLE
Private registry mirror not working as expected

### ISSUE THREAD

**Issue by ccll** [k3s-io/k3s#2606]
**Environmental Info:**
K3s Version: 

`k3s version v1.19.4+k3s1 (2532c10f)`

Node(s) CPU architecture, OS, and Version: 

`Linux <my_hostname> 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

1 master, no workers

**Describe the bug:**

Private registry mirror is configured correctly, but k3s/containerd still trying to pull from the original domain which is blocked by GFW, causing a timeout.

**Steps To Reproduce:**

- Installed K3s: with https://github.com/k3s-io/k3s-ansible.
Inventory file:
```
[all:vars]
k3s_version = 'v1.19.4+k3s1'

[all]
my-host ansible_host=xx.xx.xx.xx internal_ip=xx.xx.xx.xx labels="['datacenter=xx-xx','svccontroller.k3s.cattle.io/enablelb=true']"

...
```

I'm in China so gcr.io is blocked by GFW.

First I deployed a jFrog Artifactory as a docker pull through cache/proxy for gcr.io on a digitalocean VPS, and confirmed pulling directly from it on my k3s master node have no problem.
```
$ sudo crictl pull jcr.my-domain.com/gcr/istio-release/citadel:release-1.3-latest-daily
Image is up to date for sha256:86aaa5fde684d81dfe05c1be54f0d3b900c6cbe6ce31b863da5ac8114a2e1550
```

Then I added a file to `/etc/rancher/k3s/registries.yaml` following this guide, trying to make use of my jFrog pull through cache/proxy. https://rancher.com/docs/k3s/latest/en/installation/private-registry/

Content of my registries.yaml:
```
mirrors:
  'gcr.io':
    endpoint:
      - 'https://jcr.my-domain.com/gcr'
```

`sudo crictl info` shows that the registry mirror is configured correctly:
```
    "registry": {                                                                                                                                                     
      "mirrors": {                                                                                                                                                    
        "docker.io": {                                                                                                                                                
          "endpoint": [                                                                                                                                               
            "https://registry-1.docker.io"                                                                                                                            
          ]                                                                                                                                                           
        },                                                                                                                                                            
        "gcr.io": {                                                                                                                                                   
          "endpoint": [
            "https://jcr.my-domain.com/gcr" 
          ]
        }
      },
      "configs": null,
      "auths": null,
      "headers": null
    },
```

**Expected behavior:**

k3s/containerd should pull gcr.io images successfully, via my private jFrog pull through cache/proxy.

**Actual behavior:**

Pulling gcr.io images fails due to timeout:
```
Failed to pull image "gcr.io/istio-release/citadel:release-1.3-latest-daily": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/istio-release/citadel:release-1.3-latest-daily": failed to resolve reference "gcr.io/istio-release/citadel:release-1.3-latest-daily": failed to do request: Head "https://gcr.io/v2/istio-release/citadel/manifests/release-1.3-latest-daily": dial tcp 74.125.204.82:443: i/o timeout
```

The IP address `74.125.204.82` is belonging to Google LLC, so it seems that k3s/containerd is still pulling from the original gcr.io domain, instead of my private jFrog pull through cache/proxy.

**Additional context / logs:**

Also tried on `v1.19.3+k3s1`, same problem.

**Comment by brandond** [comment]
The endpoint cannot include a path component; containerd does not support name prefixing like that. A valid entry would look like:

```yaml
mirrors:
  gcr.io:
    endpoint:
      - https://jcr.my-domain.com:443
```

Using the above configuration you should be able to pull `gcr.io/istio-release/citadel:release-1.3-latest-daily` assuming your registry has been configured to pull-through `istio-release/citadel:release-1.3-latest-daily` from GCR.

**Comment by ccll** [comment]
@brandond You saved me! Thanks!
But I could not find a clear statement of this restriction in the containerd docs.

Anyway, the problem is solved, I'm closing the issue.
