### ISSUE TITLE
Upgrade Controller Issues Due to Taint on Master

### ISSUE THREAD

**Issue by thecrazyrussian** [k3s-io/k3s#2607]
**Environmental Info:**
K3s Version: 1.18.9=k3s1

Node(s) CPU architecture, OS, and Version: 
Raspberry Pi 4, JeOS

Cluster Configuration:
1 Master, 3 Workers.

**Describe the bug:**
Unable to upgrade in place via Rancher 2.5.2 System Upgrade Controller. The first issue is around missing taints to deploy on the master. Once able to deploy on master, I am hit with "E1201 09:00:57.476992       1 controller.go:135] error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Operation cannot be fulfilled on  "system-upgrade-controller": delaying object set, requeuing"

**Steps To Reproduce:**
Setup local multi-node cluster, this should set up a k3s-controlplane=true:NoExecute taint on your master node.
Once you add the taint to correct, the above error will display in the SUC pod's logs.

**Expected behavior:**
SUC figures out where the master nodes are and ads proper taints to deploy on the proper node updating the k3s version below.

**Actual behavior:**
It fails to deploy. Then fails to upgrade.

**Comment by thecrazyrussian** [comment]
I was able to edit the upgrade plan to include the taints in the spec for the worker and master nodes:
```
kubectl edit plan k3s-worker-plan -n cattle-system
kubectl edit plan k3s-master-plan -n cattle-system
```

So aside from the original upgrade failing, there is a workaround by adding the taints manually.

**Comment by brandond** [comment]
Did you add the `k3s-controlplane=true:NoExecute` taint yourself? Critical components should have a toleration for the standard `noderole.kubernetes.io/master=true` taint but if you've added other custom taints you'll need to add corresponding tolerations.
