### ISSUE TITLE
Docs uncelar (Need Help)

### ISSUE THREAD

**Issue by Berndinox** [k3s-io/k3s#2614]
May it's me, but i dont get how to install k3s in embedded ha mode.

**Reference 1**:
https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

`K3S_TOKEN=SECRET k3s server --cluster-init`

OK, seems like i need k3s installed before...
so i switched to:

**Reference 2**:
https://rancher.com/docs/k3s/latest/en/installation/install-options/

`curl -sfL https://get.k3s.io | sh -`
Good lets install k3s

then i went back to step 1, k3s server --cluster-init.
Does not work, because k3s seems already to be running.
Port is used, kubectl get nodes lists the server.

Ähm OK. 
How can i install k3s **and** enable embedded etc mode?
I _just_ want a 3 node master/agent/ha all-in-on cluster! 👍 

May someone can helps me out, i can't see the woodland cause of too many trees. Thx!

**Comment by brandond** [comment]
The install script will configure and start a service for k3s. You can pass extra arguments that the service will use via INSTALL_K3S_EXEC like so:

```bash
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
```

This is covered on the install-options page you linked to; there are also examples here: https://rancher.com/docs/k3s/latest/en/installation/install-options/how-to-flags/#example-b-install-k3s-exec

**Comment by Berndinox** [comment]
Thanks so much @brandond!
That was the missing piece i was looking for!

**Comment by Berndinox** [comment]
@brandond May you can quick answer me one more question.

How can i add the same Nodes as Workers to the Cluster?
So that all 3 Nodes are: ETCD, MASTER, WORKER

Does it make sense to use a LB to connect the worker nodes to the cluster?

Thanks, Bernd

**Comment by brandond** [comment]
Worker is just a made-up role. You can add that role label if you feel like it, but it doesn't really change anything. By default both k3s servers and agents can run workload pods.

**Comment by Berndinox** [comment]
Oh, got it. Thanks!
