### ISSUE TITLE
Docker/Dockershim deprecation: guidance on k3s moving away from Docker runtime

### ISSUE THREAD

**Issue by aureq** [k3s-io/k3s#2622]
**Is your feature request related to a problem? Please describe.**
Kubernetes has recently taken the decision to [migrate away from Docker](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) runtime as of Kubernetes 1.20 (deprecation).

Some users/customers of k3s may be using Docker as their preferred runtime environment (I do).

Could it be possible to have a clear path and some documentation of what is necessary to get back onto `containerd` container runtime as it is provided by k3s please?

**Describe the solution you'd like**
* Some for detailed step by step to migrate away from `dockerd` as container runtime
* A dedicated documentation page explaining why, and how to migrate away from `dockerd`
* Some early deprecation warning when installing `k3s` with `dockerd` as container runtime

**Additional context**
* https://kubernetes.io/blog/2020/12/02/dockershim-faq/
* https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

Thank you very much.

**Comment by brandond** [comment]
The easiest way to migrate off would probably be to simply one-by-one drain your nodes and then restart them without the `--docker` flag. Once that's done you can stop/uninstall dockerd and clean up /var/lib/docker.

**Comment by aureq** [comment]
@brandond I currently have a single node (little bare metal single board computer). So, what would be a path forward in that scenario?

Thanks

**Comment by brandond** [comment]
@aureq same instructions. Note that this will (obviously) cause downtime on a single-node server as all your pods will be stopped during the transition from one runtime to another.

**Comment by aureq** [comment]
some  feedback here.

I did update k3s without the `--docker` install option. At restart, there was a lot of problems. Many pods were evicted due to `DiskPressure` and running out space (At that time, something appeared to be writing inside the pod and k8s wasn't happy about it).

Unfortunately, I used `k3s-killall.sh` which wipe all my pods (insert very sad face). That also wipe all my logs/evidences I had in my terminal screen. I didn't get a chance to try to fix the issues. Unfortunately, I wish I knew about `kubectl drain` and `kubectl cordon` commands before attempting this.

Weirdly enough, I redeployed all my pods with the upgraded `Service` declaration for k8s 1.19.3. So far, I haven't experienced any issues.

I think it would be worth for the k3s team to give some clearer guidance so the community doesn't get stranded like I was on Saturday.

**Comment by brandond** [comment]
The official statement from Rancher on dockershim deprecation is available here: https://support.rancher.com/hc/en-us/articles/360053308831

In case it isn't clear, switching container runtimes DOES SPECIFICALLY involve replacing all your pods. Draining and cordoning your nodes ahead of time is a good idea, but is not strictly necessary on a single-node system since the entire cluster goes down when you stop k3s. There is no 'converting' things over - the docker pods are stopped and deleted when you remove docker, and new containerd-based pods replace them.
