### ISSUE TITLE
Database disk image is malformed on K3S Start

### ISSUE THREAD

**Issue by user1011101** [k3s-io/k3s#2623]
**Environmental Info:**
K3s Version:  v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version: x86_64, Ubuntu 18.04

Cluster Configuration: Single Server with one node (2 cores with 2GB)

**Describe the bug:**
Database source when trying to start the k3s server report a 'database disk image is malformed'. I think this is the etcd data? (if that is what is used? - still a little new to k3s / k8s).

So it looks like one of our pods, set to a single replica, failed at some point and when it started to re-build looked like the pod was up and running. However, it did not set the deloyment count to 1, that was still showing 0. We tried to re-move all deployment and service and re-build but that did not seem to work, same issue. 

We then restarted the server, which is when we could not start the k3s server. Trying to start it by hand, give me logs as to what the issue is! 

Is there anyway to repair the database? Or should i just re-install over the top or remove and re-install?

**Steps To Reproduce:**
Not sure it can be reproduce, as we are not sure what the problem is. Most likely when the pod failed and it tried to re-build, it run out of resources, e.g. RAM/CPU at the time it was running or trying to update the database

**Additional context / logs:**

ERRO[2020-12-04T08:19:42.385800803Z] error while range on /registry/clusterroles/ /registry/clusterroles/: database disk image is malformed
E1204 08:19:42.386013   10620 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:2, Message:"database disk image is malformed", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E1204 08:19:42.386866   10620 storage_rbac.go:182] unable to initialize clusterroles: rpc error: code = Unknown desc = database disk image is malformed
I1204 08:19:42.510392   10620 trace.go:116] Trace[1830584008]: "Create" url:/api/v1/namespaces,user-agent:k3s/v1.18.6+k3s1 (linux/amd64) kubernetes/6f56fa1,client:127.0.0.1 (started: 2020-12-04 08:19:32.509073642 +0000 UTC m=+4.352105634) (total time: 10.001266049s):
Trace[1830584008]: [10.001266049s] [10.00114867s] END
E1204 08:19:42.510979   10620 controller.go:151] Unable to perform initial Kubernetes service initialization: namespaces "default" is forbidden: not yet ready to handle request
E1204 08:19:42.512784   10620 controller.go:156] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/10.20.1.27, ResourceVersion: 0, AdditionalErrorMsg:
ERRO[2020-12-04T08:19:42.516777919Z] error while range on /registry/services/specs/ /registry/services/specs/: database disk image is malformed
E1204 08:19:42.517089   10620 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:2, Message:"database disk image is malformed", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
F1204 08:19:42.518222   10620 controller.go:165] Unable to perform initial IP allocation check: unable to refresh the service IP block: rpc error: code = Unknown desc = database disk image is malformed

**Comment by brandond** [comment]
This error is coming from the local sqlite datastore. It sounds like the file was corrupted when you restarted the server. Did you restart without shutting down k3s cleanly? Is there something wrong with the local disk?

You might be able to use the [sqlite3 tools](https://www.sqlite.org/download.html) to open the file at `/var/lib/rancher/k3s/server/db/state.db` and see if the file can be recovered at all. If not, you'll need to restore that file from backup, or just rebuild the cluster if you don't have a backup.

**Comment by turowicz** [comment]
@GlennWC  did you recover?
