### ISSUE TITLE
Unable to access k3s from a container

### ISSUE THREAD

**Issue by uditgaurav** [k3s-io/k3s#2627]
## Details

- I've one k3s cluster deployed. I wanted to access the cluster from a container but this is not working. The container is a GitLab Docker executor container. (So I'm trying to run GitLab CI with k3s Kubernetes deployed in my VM). Whereas from outside the container it is running fine and the problem is with only the GitLab runner container and not with all the pods deployed. 

- When I run `kubectl config view` from GitLab docker container it doesn't show any config. 
```
$ kubectl config view
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```

- When I run go-client to deploy some application then it thows error:

```
    Unable to Get the kubeconfig, due to {open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory}
    Expected
        <*os.PathError | 0xc000414090>: {
            Op: "open",
            Path: "/var/run/secrets/kubernetes.io/serviceaccount/token",
            Err: 0x2,
        }
    to be nil
```

- `kubectl get nodes` from container 
```
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

Seems like it is not able to access the cluster(config file) at all. 

What should we do to help this container to have access to the k3s cluster.

**Comment by dweomer** [comment]
Is the gitlab container privileged? It must be to run k3s in a container.

**Comment by brandond** [comment]
Is the GitLab container running in the k3s cluster, or just in a Docker container unrelated to the k3s cluster? If it is the latter, how are you passing Kubernetes client configuration to the GitLab container? The messages you've shared suggest that it's. running outside the cluster and you haven't mounted your kubeconfig into the container.

**Comment by uditgaurav** [comment]
Hi, @brandond thanks for responding. 

It looks like the docker container is unrelated to the k3s cluster right now. The container is created by GitLab Runner at runtime when we trigger the pipeline and gets deleted after the completion. So just thinking how to pass Kubernetes client configuration to the GitLab container?

**Comment by brandond** [comment]
How does GitLab recommend doing it? Do they have a native in-cluster configuration you could reference?

**Comment by uditgaurav** [comment]
- GitLab provides different types of runners like a shell, docker, Kubernetes, and others.  I was trying to use docker which was creating a docker container in the VM that doesn't have configuration mounted on it we need to see how GitLab allows mounting configuration (IDK right now) So it's more of a GitLab issue than k3s. 

- I started using Kubernetes type of GitLab runner which unblocked me with the current issue. Kubernetes runner creates pods having container running the GitLab jobs so it is having the access to the k3s cluster.

Thanks, @brandond for your help.
