### ISSUE TITLE
Support configurable taints and tolerations

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2637]
- piped through to helm charts
- must be pass through rancher cluster config
- does it affect static pods at all?﻿

This topic may require more design discussion, as necessary.
This is also needed in RKE2 (see https://github.com/rancher/rke2/issues/572)

**Comment by cjellick** [comment]
Is this just the work we did in order to support "roles" in rancher? @cjellick to clean up

**Comment by cjellick** [comment]
I'm going to close this issue and track it elsewhere.
