### ISSUE TITLE
Add SLES 15+ support

### ISSUE THREAD

**Issue by dirkmueller** [k3s-io/k3s#2648]
**Is your feature request related to a problem? Please describe.**
A Harbor based private registry solution has recently been announced by SUSE: https://www.suse.com/c/suse-private-registry-harbor/

For Edge and more lightweight air-gap usecases, it was deemed useful to be exploring k3s as a small-footprint and easy-to-manage deployment. However based on https://rancher.com/support-maintenance-terms/ there is no declared host-os support for SLES 15 SP2+ on K3s (only some RKE variants). Testing appears to show no observable issues, things seem to work fine on that OS.

**Describe the solution you'd like**
The SLES base OS would be listed as a supported offering alongside other already listed OS.

**Describe alternatives you've considered**
It looks like https://k0sproject.io/ is a viable alternative as well. I haven't fully understood the commercial support offerings around that yet, if it is supporting that host OS then that might be a good alternative.

**Comment by cjellick** [comment]
@dirkmueller - k3s - This issue confuses me a bit, so I'm going to make a few clarifications.

First, you should note that k3s is an independent, upstream project "owned by" the CNCF. We avoid requests around the rancher support matrix here. You can route those through a product manager at suse. That said, note that Rancher's support martix for k3s is here: https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.5.8/.  You can search for `Rancher K3S Downstream Clusters` to find it. SLES 15 SP 2 is on that list.

Next, it feels like you are asking more specifically for official harbor support? Or possibly embedding harbor in k3s? Can you clarify?

**Comment by dirkmueller** [comment]
@cjellick I wasn't asking about Harbor, I was working on Harbor back then and was looking for a small scale Kubernetes that is supported. I can see that K3s is now supported on SLE. so considering the issue resolved. thanks!
