### ISSUE TITLE
Cattle loadbalancer locking the requested port on all the nodes of the k3s cluster

### ISSUE THREAD

**Issue by Platou** [k3s-io/k3s#2662]
Why to use a DeamonSet instead of Deployment? I try to understand why a loadbalancer service should lock the specified port on all nodes of the cluster...

https://rancher.com/docs/k3s/latest/en/networking/#how-the-service-lb-works

**Comment by Platou** [comment]
A situation is exposed here: https://github.com/k3s-io/k3s/issues/1969

**Comment by avoyer-fuze** [comment]
Thanks for documenting this, we're also facing the same issue and have the same question!

**Comment by brandond** [comment]
I'll repeat what I've commented elsewhere:
> ServiceLB is a very basic stub service controller that is 'just enough' to get services with type=LoadBalancer up and running without requiring any additional configuration. You are not required to use it, and it is very easy to turn off. Most use cases that go beyond standing up a small cluster to serve a single workload will immediately replace it with MetalLB, kube-vip, or a cloud provider's LB service.
