### ISSUE TITLE
HelmChart won't apply with large chartContent

### ISSUE THREAD

**Issue by tinyzimmer** [k3s-io/k3s#2663]
**Environmental Info:**
K3s Version: **v1.19.4+k3s1**

Testing on latest currently in docker, but I imagine outside would be the same issue. 

```
$ docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                            NAMES
39cc6026a630   rancher/k3d-proxy:latest   "/bin/sh -c nginx-pr…"   7 minutes ago   Up 7 minutes   80/tcp, 0.0.0.0:6443->6443/tcp   test-serverlb
804e0da6ee6a   rancher/k3s:v1.19.4-k3s1   "/bin/k3s server --t…"   7 minutes ago   Up 7 minutes                                    test-server-2
f34409460b33   rancher/k3s:v1.19.4-k3s1   "/bin/k3s server --t…"   8 minutes ago   Up 8 minutes                                    test-server-1
34d98e7e4daf   rancher/k3s:v1.19.4-k3s1   "/bin/k3s server --t…"   8 minutes ago   Up 8 minutes                                    test-server-0
```

Node(s) CPU architecture, OS, and Version: 

Again probably not related, but at this very moment Docker on WSL2

```
$ uname -a
Linux DESKTOP-5H08KBL 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux
```

Cluster Configuration:

Three servers as shown above, can reproduce on just one too

**Describe the bug:**

The `chartContent` field in the `HelmChart` CRD is super useful for a side project I am working on (that I may open source in the coming days, just checking with work), but I think I may have just stumbled on a limitation. I wanted to see how it handled a really large chart, and I failed. 

Logs from the server

```bash
time="2020-12-09T06:03:31.706243300Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/k3s/server/manifests/kube-prometheus-stack-12.7.0.tgz-helm-chart.yaml: failed to create kube-system/kube-prometheus-stack-12.7.0.tgz helm.cattle.io/v1, Kind=HelmChart for  kube-system/kube-prometheus-stack-12: HelmChart.helm.cattle.io \"kube-prometheus-stack-12.7.0.tgz\" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"
```

If I had to guess what is happening here, `kubectl` is trying to populate the `last-applied-configuration` with the full spec of the CR. That probably wouldn't be the easiest fix, because best I can think is having `k3s` call `client-go` directly for either all `HelmChart` CRs or ones that exceed a certain size.

**Steps To Reproduce:**

- Make a really big `HelmChart` CR and place in `/var/lib/rancher/k3s/server/manifests/`.
- Install/Start K3s
- Don't profit

**Expected behavior:**

The helm chart would be installed at cluster bootstrap

**Actual behavior:**

The helm chart was not installed

**Additional context / logs:**

Don't have much else at the moment, but happy to provide

**Comment by tinyzimmer** [comment]
I realize I should have included an example `HelmChart` CR probably. I'm generating them in this example, below is the template, which I think shows the meat of what is relevant (namely that I don't even have any annotations to begin with 😛)

```gotmpl
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ .Name }}
  namespace: kube-system
spec:
  targetNamespace: default 
  chartContent: {{ .ChartContent }}
```

**Comment by brandond** [comment]
Yes, using the chartContent field isn't a great idea. It's not a great idea to stuff data blobs into the kubernetes datastore unless you absolutely have to; it exists for when you have some situation in which you absolutely can't store the chart anywhere else. It also probably should have been implemented as a binary field instead of base64-encoded text.

If you're trying to avoid having to set up a separate webserver for your chart, you can actually host static content off the k3s apiserver by placing content in `/var/lib/rancher/k3s/server/static`. See traefik's chart for an example:
https://github.com/k3s-io/k3s/blob/master/manifests/traefik.yaml#L7

**Comment by tinyzimmer** [comment]
> If you're trying to avoid having to set up a separate webserver for your chart, you can actually host static content on the k3s apiserver by placing content in `/var/lib/rancher/k3s/server/static`

Genius! I'll look into it.
