### ISSUE TITLE
Could not register device plugin: context deadline exceeded

### ISSUE THREAD

**Issue by mcrisafu** [k3s-io/k3s#2664]
Hi all
**Environmental Info:**
K3s Version: v1.19.4+k3s1 (2532c10f)

Node(s) CPU architecture, OS, and Version: Linux demeter-w1 5.4.0-56-generic #62-Ubuntu (20.04 LTS) SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 master 6 worker

**Describe the bug:**

Unable to register nvidia gpu

**Steps To Reproduce:**

- Installed Docker on gpu node
- Installed nvidia driver and nvidia-docker2
- Set nvidia as default runtime
- Tested docker with: docker run --rm nvidia/cuda:10.0-base nvidia-smi (works)
- Started master with --kubelet-arg="feature-gates=DevicePlugins=true" (is this needed?)
- Installed K3s agent with --docker and --kubelet-arg="feature-gates=DevicePlugins=true"
- Modified nvidia device plugin daemonset so that hostPath points to: /var/lib/rancher/k3s/agent/kubelet/device-plugins
- Check if nvidia.sock found in pod under: /var/lib/kubelet/device-plugins/ (found) 

**Expected behavior:**

Registered gpu

**Actual behavior:**

Pod logs:
2020/12/09 13:30:40 Loading NVML
2020/12/09 13:30:41 Starting FS watcher.
2020/12/09 13:30:41 Starting OS watcher.
2020/12/09 13:30:41 Retreiving plugins.
And then every 5s this:
2020/12/09 13:30:41 Starting GRPC server for 'nvidia.com/gpu'
2020/12/09 13:30:41 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia.sock
2020/12/09 13:30:46 Could not register device plugin: context deadline exceeded
2020/12/09 13:30:46 Stopping to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia.sock
2020/12/09 13:30:46 Could not contact Kubelet, retrying. Did you enable the device plugin feature gate?
2020/12/09 13:30:46 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/12/09 13:30:46 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start

**Additional context / logs:**

I read trough #988 and #443. I am using v0.7.1 of https://github.com/NVIDIA/k8s-device-plugin.

Thanks in advance for any help.
Regards
Marco

**Comment by brandond** [comment]
Where did you see that you should use `/var/lib/rancher/k3s/agent/kubelet`? This was changed to the standard path of `/var/lib/kubelet` in https://github.com/k3s-io/k3s/pull/901 over a year ago.

**Comment by mcrisafu** [comment]
I read it in #988 and #442 but yeah you are absolutely right. With standard path it does work. Thank you very much!
