### ISSUE TITLE
Install k3s on kvm cluster.

### ISSUE THREAD

**Issue by sandhyarme** [k3s-io/k3s#2666]
Hi,

Can we install k3s on KVM with Masters running on KVM VM’s and all workers are bare metal servers, where KVM is running.

Like for example. I have 2 Physical Nodes which has KVM cluster. Can I host k3s masters as VM on KVM cluster and hand over those 2 Physical servers as workers to k3s?

Please provide reference link to install k3s on kvm cluster..

**Comment by brandond** [comment]
K3s does not care if the operating system is running on a VM or bare metal.
