### ISSUE TITLE
Install script runs cleanup exit code=7 after hash download

### ISSUE THREAD

**Issue by jakoberpf** [k3s-io/k3s#2671]
Hello, I have trouble installing k3s on three raspberry pis (arm64). When I run the installer script, the script stops after the Hash download. My humble debugging skills let me to the cleanup function which is exiting with code 7, but that where I don't have any more clues. I have seen some previous posts about these symptoms when the sd card is full or there are missing permission, but the sd card is quite empty and I did not find permission issues.

Would really appreciate some guidance.

**Environmental Info:**
K3s Versions: tried most Versions from 17 to 19

Node(s) CPU architecture, OS, and Version: 
Raspberry PI 4 (3x)

**Describe the bug:**
Installer script stops after the hash download.

**Steps To Reproduce:**
run `curl -sfL https://get.k3s.io | sh -`

**Expected behavior:**
Fluent run of installer

**Actual behavior:**
Installer stops after '[INFO]  Downloading hash `https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt`

**Additional context / logs:**
```
# --- run the install process --
{
    verify_system
    setup_env "$@"
    download_and_verify
    setup_selinux
    create_symlinks
    create_killall
    create_uninstall
    systemd_disable
    create_env_file
    create_service_file
    service_enable_and_start
}
+ verify_system
+ '[' -x /sbin/openrc-run ']'
+ '[' -d /run/systemd ']'
+ HAS_SYSTEMD=true
+ return
+ setup_env
+ case "$1" in
+ '[' -z '' ']'
+ CMD_K3S=server
+ verify_k3s_url
+ case "${K3S_URL}" in
++ quote_indent
++ printf ' \\\n'
+ CMD_K3S_EXEC='server \'
+ '[' -n '' ']'
+ '[' server = server ']'
+ SYSTEM_NAME=k3s
++ printf %s k3s
++ sed -e 's/[][!#$%&()*;<=>?\_`{|}/[:space:]]/^/g;'
+ valid_chars=k3s
+ '[' k3s '!=' k3s ']'
+ SUDO=sudo
++ id -u
+ '[' 0 -eq 0 ']'
+ SUDO=
+ '[' -n '' ']'
+ '[' server = server ']'
+ SYSTEMD_TYPE=notify
+ '[' -n '' ']'
+ BIN_DIR=/usr/local/bin
+ sh -c 'touch /usr/local/bin/k3s-ro-test && rm -rf /usr/local/bin/k3s-ro-test'
+ '[' -n '' ']'
+ SYSTEMD_DIR=/etc/systemd/system
+ SERVICE_K3S=k3s.service
+ UNINSTALL_K3S_SH=/usr/local/bin/k3s-uninstall.sh
+ KILLALL_K3S_SH=/usr/local/bin/k3s-killall.sh
+ '[' true = true ']'
+ FILE_K3S_SERVICE=/etc/systemd/system/k3s.service
+ FILE_K3S_ENV=/etc/systemd/system/k3s.service.env
++ get_installed_hashes
++ sha256sum /usr/local/bin/k3s /etc/systemd/system/k3s.service /etc/systemd/system/k3s.service.env
++ true
+ PRE_INSTALL_HASHES='f909f64c7ff42e2100f94dedc0c22ae4ee329a1f2f9e73f86661ca4eca46d7bc  /usr/local/bin/k3s
sha256sum: /etc/systemd/system/k3s.service: No such file or directory
sha256sum: /etc/systemd/system/k3s.service.env: No such file or directory'
+ '[' '' = true ']'
+ INSTALL_K3S_CHANNEL_URL=https://update.k3s.io/v1-release/channels
+ INSTALL_K3S_CHANNEL=stable
+ download_and_verify
+ can_skip_download
+ '[' '' '!=' true ']'
+ return 1
+ setup_verify_arch
+ '[' -z '' ']'
++ uname -m
+ ARCH=aarch64
+ case $ARCH in
+ ARCH=arm64
+ SUFFIX=-arm64
+ verify_downloader curl
++ which curl
+ '[' -x /usr/bin/curl ']'
+ DOWNLOADER=curl
+ return 0
+ setup_tmp
++ mktemp -d -t k3s-install.XXXXXXXXXX
+ TMP_DIR=/tmp/k3s-install.IfQqqbxXBJ
+ TMP_HASH=/tmp/k3s-install.IfQqqbxXBJ/k3s.hash
+ TMP_BIN=/tmp/k3s-install.IfQqqbxXBJ/k3s.bin
+ trap cleanup INT EXIT
+ get_release_version
+ '[' -n '' ']'
+ '[' -n '' ']'
+ info 'Finding release for channel stable'
+ echo '[INFO] ' 'Finding release for channel stable'
[INFO]  Finding release for channel stable
+ version_url=https://update.k3s.io/v1-release/channels/stable
+ case $DOWNLOADER in
++ curl -w '%{url_effective}' -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null
++ sed -e 's|.*/||'
curl: (7) Couldn't connect to server
+ VERSION_K3S=stable
+ info 'Using stable as release'
+ echo '[INFO] ' 'Using stable as release'
[INFO]  Using stable as release
+ download_hash
+ '[' -n '' ']'
+ HASH_URL=https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt
+ info 'Downloading hash https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt'
+ echo '[INFO] ' 'Downloading hash https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt'
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt
+ download /tmp/k3s-install.IfQqqbxXBJ/k3s.hash https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt
+ '[' 2 -eq 2 ']'
+ case $DOWNLOADER in
+ curl -o /tmp/k3s-install.IfQqqbxXBJ/k3s.hash -sfL https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt
cleanup
+ cleanup
+ code=7
+ set +e
+ trap - EXIT
+ rm -rf /tmp/k3s-install.IfQqqbxXBJ
+ exit 7

```

**Comment by brandond** [comment]
Are you setting INSTALL_K3S_VERSION=stable or something like that? That should be a complete release version, such as `v1.19.4+k3s1` - not a channel name. If you want to set the channel to `testing` or `stable` you can set INSTALL_K3S_CHANNEL. If you don't set any version or channel, you should get something like this:

```
[root@centos ~]# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.19.4+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
```

**Comment by brandond** [comment]
Oh, I see an error hidden in your log output:
```
+ version_url=https://update.k3s.io/v1-release/channels/stable
+ case $DOWNLOADER in
++ curl -w '%{url_effective}' -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null
++ sed -e 's|.*/||'
curl: (7) Couldn't connect to server
```

Can you run this command separately to see why it's failing?
`curl -v https://update.k3s.io/v1-release/channels/stable`

**Comment by jakoberpf** [comment]
> Are you setting `INSTALL_K3S_VERSION=stable` or something like that? That should be a complete release version, such as `v1.19.4+k3s1` - not a channel name. If you want to set the channel to `testing` or `stable` you can set `INSTALL_K3S_CHANNEL`. If you don't set any version or channel, you should get something like this:
> 
> ```
> [root@centos ~]# curl -sfL https://get.k3s.io | sh -
> [INFO]  Finding release for channel stable
> [INFO]  Using v1.19.4+k3s1 as release
> [INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/sha256sum-amd64.txt
> [INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/k3s
> [INFO]  Verifying binary download
> [INFO]  Installing k3s to /usr/local/bin/k3s
> ```
I didn't have any env vars set.




> Can you run these commands separately to see why it's failing?
> `curl -vs https://update.k3s.io/v1-release/channels/stable`
> `curl -vsL https://update.k3s.io/v1-release/channels/stable`

I tried both commands on one of the pis and got this
`*   Trying 52.36.54.134:443...
* TCP_NODELAY set
* Immediate connect fail for 52.36.54.134: Network is unreachable
*   Trying 34.208.213.149:443...
* TCP_NODELAY set
* Immediate connect fail for 34.208.213.149: Network is unreachable
* Closing connection 0`

Then I tried the same commands on another machine in the same network and they worked fine.
