### ISSUE TITLE
k3s   Memory continues to grow

### ISSUE THREAD

**Issue by wuzhe585659** [k3s-io/k3s#2677]
**Environmental Info:**
K3s Version: 
k3s version v1.18.10+k3s1 (6fa97306)

Node(s) CPU architecture, OS, and Version: 
Linux ubuntu 4.19.0-xilinx-v2019.1 #1 SMP Tue Dec 1 08:45:32 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
1k3s server

**Describe the bug:**
Memory continues to grow

**Steps To Reproduce:**

- Installed K3s: 
docker load -i k3s-airgap-images-arm64.tar
cp ./k3s-arm64 -p /usr/local/bin/k3s && sudo chmod 755 /usr/local/bin/k3s
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666" sh install-k3s-arm64.sh
**Expected behavior:**

**Actual behavior:**

<img width="674" alt="QQ20201208-154741@2x" src="https://user-images.githubusercontent.com/22166723/101714977-94926800-3ad5-11eb-93e8-782e81a1a8ea.png">

**Additional context / logs:**

![e826c7b645567ab0fa89133eacdb92fc](https://user-images.githubusercontent.com/22166723/101715123-d7ecd680-3ad5-11eb-957a-94179b94eef8.png)

**Comment by brandond** [comment]
It looks like you have quite a few errors from the container runtime that may or may not be related to why it's using so much memory. Can you post the complete k3s log, beginning with the initial startup, in text format? It's hard to work based on a small screenshot of just a few errors.

**Comment by wuzhe585659** [comment]
> It looks like you have quite a few errors from the container runtime that may or may not be related to why it's using so much memory. Can you post the complete k3s log, beginning with the initial startup, in text format? It's hard to work based on a small screenshot of just a few errors.


[k3s.log](https://github.com/k3s-io/k3s/files/5676846/k3s.log)

**Comment by brandond** [comment]
Your logs contain an odd time jump. The logs start out in mid-October, which is around when the release you're running came out. Suddenly they jump forward to December 4th, and then end on the 5th. What else is going on with this system?

```
Oct 12 23:34:03 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44864: remote error: tls: bad certificate
Oct 12 23:34:04 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44866: remote error: tls: bad certificate
Oct 12 23:34:05 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44868: remote error: tls: bad certificate
Oct 12 23:34:06 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44870: remote error: tls: bad certificate
Oct 12 23:34:07 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44872: remote error: tls: bad certificate
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.673932    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.673990    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.675473515+08:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0"
Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.676919280+08:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.701172822+08:00" level=info msg="Running cloud-controller-manager --allocate-node-cidrs=true --allow-untagged-cloud=true --bind-address=127.0.0.1 --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --node-status-update-frequency=1m --secure-port=0"
Dec 04 13:48:00 ubuntu k3s[4818]: Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.707697    4818 controllermanager.go:161] Version: v1.18.10+k3s1
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.710985    4818 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.720373    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.720438    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.726995    4818 controllermanager.go:120] Version: v1.18.10+k3s1
```

**Comment by wuzhe585659** [comment]
> Your logs contain an odd time jump. The logs start out in mid-October, which is around when the release you're running came out. Suddenly they jump forward to December 4th, and then end on the 5th. What else is going on with this system?
> 
> ```
> Oct 12 23:34:03 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44864: remote error: tls: bad certificate
> Oct 12 23:34:04 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44866: remote error: tls: bad certificate
> Oct 12 23:34:05 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44868: remote error: tls: bad certificate
> Oct 12 23:34:06 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44870: remote error: tls: bad certificate
> Oct 12 23:34:07 ubuntu k3s[4818]: http: TLS handshake error from 127.0.0.1:44872: remote error: tls: bad certificate
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.673932    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.673990    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.675473515+08:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0"
> Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.676919280+08:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
> Dec 04 13:48:00 ubuntu k3s[4818]: time="2020-12-04T13:48:00.701172822+08:00" level=info msg="Running cloud-controller-manager --allocate-node-cidrs=true --allow-untagged-cloud=true --bind-address=127.0.0.1 --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --node-status-update-frequency=1m --secure-port=0"
> Dec 04 13:48:00 ubuntu k3s[4818]: Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.707697    4818 controllermanager.go:161] Version: v1.18.10+k3s1
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.710985    4818 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.720373    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.720438    4818 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Dec 04 13:48:00 ubuntu k3s[4818]: I1204 13:48:00.726995    4818 controllermanager.go:120] Version: v1.18.10+k3s1
> ```

The clock of the device is not synchronized with the current time. After modifying the clock, restart k3s to resume normal operation. At the end of the 5th day, due to the limitation of the upload file size, only some logs were intercepted.
