### ISSUE TITLE
Update to use go mod

### ISSUE THREAD

**Issue by xrain0610** [k3s-io/k3s#268]
Can you consider to update the golang to 1.12? and use the go mod for package management?

**Comment by warmchang** [comment]
Upgrade to golangci-lint & go v1.12.1: https://github.com/rancher/k3s/pull/262

**Comment by deniseschannon** [comment]
We'll revisit this after k8s 1.15 is released.

**Comment by brandond** [comment]
Closing due to age. Golang has been updated several times.
