### ISSUE TITLE
k3s constantly restarting due to a failed assertion

### ISSUE THREAD

**Issue by tburschka** [k3s-io/k3s#2688]
**Environmental Info:**
K3s Version: 
    k3s v1.18.12+k3s2

Node(s) CPU architecture, OS, and Version: 
    Linux se04 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz, 6 Cores
    MemTotal: 65615752 kB
    ssd: /
    md0 (raid10) (4x hdd): /var/lib

Cluster Configuration:
    single master

**Describe the bug:**

**Steps To Reproduce:**
setup k3s

**Expected behavior:**
not restarting ;-)

**Actual behavior:**
The k3s constantly restarting

**Additional context / logs:**

        Dec 11 09:27:34 se04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
        Dec 11 09:27:34 se04 systemd[1]: k3s.service: Found left-over process 640714 (pause) in control group while starting unit. Ignoring.
        Dec 11 09:27:34 se04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
        Dec 11 09:27:34 se04 systemd[1]: k3s.service: Found left-over process 640795 (pause) in control group while starting unit. Ignoring.
        Dec 11 09:27:34 se04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
        Dec 11 09:27:34 se04 systemd[1]: k3s.service: Found left-over process 640873 (pause) in control group while starting unit. Ignoring.
        Dec 11 09:27:34 se04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
        Dec 11 09:27:34 se04 systemd[1]: k3s.service: Found left-over process 641391 (webhook) in control group while starting unit. Ignoring.
        Dec 11 09:27:34 se04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
        Dec 11 09:27:34 se04 k3s[989807]: time="2020-12-11T09:27:34.712094234Z" level=info msg="Starting k3s v1.18.12+k3s2 (1f350537)"
        Dec 11 09:27:36 se04 k3s[989807]: time="2020-12-11T09:27:36.094882591Z" level=info msg="Testing connection to peers [192.168.20.14:6443]"
        Dec 11 09:27:36 se04 k3s[989807]: time="2020-12-11T09:27:36.095214906Z" level=info msg="Connection OK to peers [192.168.20.14:6443]"
        Dec 11 09:27:36 se04 k3s[989807]: time="2020-12-11T09:27:36.096115203Z" level=info msg="Configuring dqlite database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
        Dec 11 09:27:36 se04 k3s[989807]: time="2020-12-11T09:27:36.096155834Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
        Dec 11 09:27:36 se04 k3s[989807]: Assertion failed: tx->id == c->tx_id (src/fsm.c: apply_frames: 52)
        Dec 11 09:27:36 se04 systemd[1]: k3s.service: Main process exited, code=killed, status=6/ABRT
        Dec 11 09:27:36 se04 systemd[1]: k3s.service: Failed with result 'signal'.
        Dec 11 09:27:36 se04 systemd[1]: Failed to start Lightweight Kubernetes.

**Comment by brandond** [comment]
It looks like you're using dqlite. We were unable to get it to work with sufficient stability to move it beyond the experimental state, and it has been dropped as of the 1.19 release branch. I would suggest you look at rebuilding your cluster with embedded etcd.

**Comment by tburschka** [comment]
@brandond In short, i have to upgrade to 1.19.x to get etcd support or is it possible to enable it for 1.18.x branch?

**Comment by brandond** [comment]
No, we are not backporting embedded etcd to the 1.18 branch. Note that it's not an upgrade so much as a rebuild, as there is no direct path to migrate your data from dqlite to etcd.
