### ISSUE TITLE
Does k3s support Bootstrap token?

### ISSUE THREAD

**Issue by jiayihu** [k3s-io/k3s#2691]
I'm trying to use k3s server with a custom agent from https://github.com/deislabs/krustlet and it works fine but I just have some curiosity on the auth flow.

Krustlet works by using the bootstrap token flow, but I've noticed that the k3s server seems to always allow it even if I don't create the secret as described [in the k8s docs](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#bootstrap-token-secret-format). I just have to approve CSR and it's ready to go.

**Comment by brandond** [comment]
No, K3s has its own bootstrap workflow. It does not use the kubelet bootstrap token workflow as it didn't exist at the time K3s was created and we have not yet replaced our process with something that uses or extends the upstream functionality.

**Comment by jiayihu** [comment]
I've read a bit about k3s in #2645 . From my understanding k3s server generates a static token when the service is launched, but it's different from the [k8s static token file](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-token-file) right? Then the agents use the token for bootstraping but instead of retrieving and saving a certificate, they retrieve a password. Then all communication happens using basic auth.

What's happening with the bootstrap token flow instead? The server just assumes it's fine and procede with the default k8s flow? Since it's working I have no complains though 😄

**Comment by brandond** [comment]
Our token is mostly just basic auth, plus an encoded hash of the CA cert so that the client can confirm it's joining the correct cluster.

We don't use any of the bootstrap code, and to be honest I haven't looked at it enough to know how K3s might interact with it. Since we take care of provisioning the certs for the node, it probably doesn't get used at all.
