### ISSUE TITLE
setup vendor-neutral security list

### ISSUE THREAD

**Issue by cjellick** [k3s-io/k3s#2692]
K3s security issue reporting is still tied to rancher, specifically users are directed to send issues to security@rancher.com. 
We need to move this to a vendor neutral mailing list.

**Comment by davidnuzik** [comment]
Tentatively applying a mid-jan milestone. I will try to get this all sorted before then. Worst case this lands a little later in Jan 2021.

**Comment by davidnuzik** [comment]
Quick update: Am on track to get this done, however we have to wait until the email migration internally completes so this could delay my deadline slightly.

**Comment by davidnuzik** [comment]
This work item is complete. security@k3s.io email is now functioning correctly and ready.
