### ISSUE TITLE
Move cloud-controller-manager functionality into dedicated controller

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2697]
**Is your feature request related to a problem? Please describe.**
Upstream `cloud-controller-manager` is no longer supported. As per the 1.20.0 release notes:

> Kubernetes will no longer ship an instance of the Cloud Controller Manager binary. Each Cloud Provider is expected to ship their own instance of this binary. Details for a Cloud Provider to create an instance of such a binary can be found under [here](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cloud-provider/sample). Anyone with questions on building a Cloud Controller Manager should reach out to SIG Cloud Provider. Questions about the Cloud Controller Manager on a Managed Kubernetes solution should go to the relevant Cloud Provider. Questions about the Cloud Controller Manager on a non managed solution can be brought up with SIG Cloud Provider.

**Describe the solution you'd like**
Move the work currently handled by the cloud-controller-manager hooks into a dedicated embedded controller. This is mostly just:
* Setting the node external IP address
* Removing the uninitialized taint on new nodes

**Describe alternatives you've considered**
* Keep using the current mess that we had to hack in to get CCM to work in 1.20.0:
https://github.com/k3s-io/k3s/commit/c6950d2cb0b242595640ea3ad5a7570343ab7829#diff-c68274534954d72488196ca23f12cfb3ebe65998d9e7c4a43d7ba9acc9532574R914

**Additional context**
* Possibly related to k3s-io/k3s#2425
* kubernetes/sig-release#1378
* https://twitter.com/ibuildthecloud/status/1336341788827611138

**Comment by brandond** [comment]
I have also seen CI flakes where the `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` taint doesn't clear on the test cluster nodes. In looking at the logs, it appears that the cloudprovider node lifecycle hook is failing, perhaps due to some internal caching that is causing it to fail to find the newly-added node?

```
I1216 19:41:56.710081       1 range_allocator.go:373] Set node 99cc7a89bf52 PodCIDR to [10.42.0.0/24]
I1216 19:41:56.710231       1 node_controller.go:390] Initializing node 99cc7a89bf52 with cloud provider
E1216 19:41:56.710271       1 node_controller.go:212] error syncing '99cc7a89bf52': failed to get provider ID for node 99cc7a89bf52 at cloudprovider: failed to get instance ID from cloud provider: Failed to find node 99cc7a89bf52: node "99cc7a89bf52" not found, requeuing
I1216 19:41:56.711156       1 range_allocator.go:373] Set node a2144c8e7203 PodCIDR to [10.42.1.0/24]
I1216 19:41:56.711435       1 node_controller.go:390] Initializing node a2144c8e7203 with cloud provider
E1216 19:41:56.711466       1 node_controller.go:212] error syncing 'a2144c8e7203': failed to get provider ID for node a2144c8e7203 at cloudprovider: failed to get instance ID from cloud provider: Failed to find node a2144c8e7203: node "a2144c8e7203" not found, requeuing
```

**Comment by rancher-max** [comment]
#### Validated in master branch commit: `ada145641c2fd56c4b170ef6810804125e4b946c`

- Correctly sets ProviderID in default installs
- Can still be disabled and that functionality is working correctly
