### ISSUE TITLE
rancher log ship to elasticsearch not work with default fluent configuration

### ISSUE THREAD

**Issue by warthur1214** [k3s-io/k3s#2706]
**Environmental Info:**
K3s Version: k3s version v1.19.4+k3s1 (2532c10f)

Node(s) CPU architecture, OS, and Version: Linux k3s-node1 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 2 masters, 0 workers

**Describe the bug:**

I installed rancher-logging charts. After I configure elasticearch, I clicked the test button and it shows success. kibana also successfully received the log. But When I checked the rancher-logging-fluentd-linux log, it shows 'pattern not found'.

**Expected behavior:**

I try to upgraded secrets 'rancher-logging-fluentd' by updating project.conf，it worked.
```
  format  json
```
to
```
  format  /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
```
But when i updated elaticsearch configuration by rancher logging ui，`format  json` was back

**Comment by brandond** [comment]
I believe this belongs in rancher/rancher, not k3s.
