### ISSUE TITLE
dev documentation

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2712]
The K3s team discussed recently that we may want to improve documentation for developers in K3s.
- Do we just need to give BUILDING.md a lift?
- Does CONTRIBUTING.md need any updates? (Any rules for PR submission, etc?)

**Comment by cwayne18** [comment]
I'd like to spend some cycles on this ASAP, as we are already overhauling some of our documentation.

**Comment by katran001** [comment]
@jossemargt-3pillar is currently working on this, will move to the next milestone until further notice.

**Comment by jossemargt-3pillar** [comment]
Contributor documentation is already merged. Now it addresses :

- Git workflow and CI
- Coding conventions 
- Development setup and tooling involved
