### ISSUE TITLE
Add CI step to check for proper vendoring

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2720]
**Is your feature request related to a problem? Please describe.**
Our current Kubernetes patch update process sees us getting PR approval with go.mod pointing at a personal fork of kubernetes/kubernetes, before pushing tags to k3s-io/kubernetes, updating go.mod AGAIN, and then merging the PR.

Since the push and go.mod update occurs after approval has been granted and CI is green, this final step can be missed, resulting in incorrect vendoring. This happened in #2385 / #2719 for example.

**Describe the solution you'd like**
CI should check to ensure that we're replacing vendored components with the correct forks. This should be a separate *check* in the drone pipeline that runs after (or independent of) the rest of the PR checks, so that we can continue to use the other checks as a smoke-test before pushing tags across forks when updating patch releases.

**Describe alternatives you've considered**
Continue to validate this manually

**Additional context**

**Comment by davidnuzik** [comment]
Closing. Drone CI change.

**Comment by davidnuzik** [comment]
Reopened for backports

**Comment by MonzElmasry** [comment]
Backports are merged, closing
