### ISSUE TITLE
Rancher-K3s Bootstrap Mechanism

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2724]
In order to be able to provision K3s or RKE2 from within Rancher, a bootstraping mechanism is needed. As we consider design and iterate on this we can update this issue with more information.

**Comment by brandond** [comment]
Bootstrapping has been moved into the scope of the Rancher agent that @Oats87 is working on.

**Comment by davidnuzik** [comment]
Close in favor of https://github.com/rancher/rancher/issues/31379 which more accurately describes the work being done in the agent.
