### ISSUE TITLE
Bump K3s KDM version (v1.19.5+k3s2)

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2729]
v1.19.5+**k3s2** was released to fix an upstream bug in 1.7.1 coredns. You can reference the release notes [here](https://github.com/k3s-io/k3s/releases/tag/v1.19.5%2Bk3s2) for details.

We need to bump the KDM version (used by rancher/rancher) in the dev branches so that we are all set for 12/22 planned KDM release.

**Comment by cjellick** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/444
https://github.com/rancher/kontainer-driver-metadata/pull/443

**Comment by rancher-max** [comment]
#### Validated in both rancher v2.4-head and v2.5.4

Am able to properly update k3s from v1.19.4+k3s2 to v1.19.5+k3s2 through UI without updating default KDM settings.
