### ISSUE TITLE
User/Password access instead of x509 client certificate authentication for default admin account

### ISSUE THREAD

**Issue by ezYakaEagle442** [k3s-io/k3s#2733]
**Is your feature request related to a problem? Please describe.**
Since 1.19 it looks like there is no more User/Password access , this is a breaking change

**Describe the solution you'd like**

I would like to be able to run quiclkyly this kind of query, without having to deal with certificates issues, as the certificatre is valid only for the local IP address

```sh
sudo sed -i "s/127.0.0.1/${k3s_pub_ip_address}/g" /etc/rancher/k3s/k3s.yaml 

k3s_usr=$(k config view -o json | jq -Mr '.users[0].user.username')
k3s_pwd=$(k config view -o json | jq -Mr '.users[0].user.password')

curl -k https://${k3s_pub_ip_address}:6443/api/v1/namespaces  --user $k3s_usr:$k3s_pwd -H 'Accept: application/json'

```

Is there any option as design time when running curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=" ........." to specify an option to use User/Password access  instead of x509 client certificate ?

**Describe alternatives you've considered**

**Additional context**
See [https://github.com/k3s-io/k3s/issues/1616](https://github.com/k3s-io/k3s/issues/1616)

**Comment by brandond** [comment]
Please read through the entire thread on #1616 that you already linked. There is more discussion in https://github.com/k3s-io/k3s/issues/2342#issuecomment-703830567.

**Comment by ezYakaEagle442** [comment]
Thanks @brandond I have seen :
Support for Basic authentication has been removed from upstream Kubernetes. Note that this is not just deprecated or disabled, but deleted from the codebase: kubernetes/kubernetes#89069

**Comment by brandond** [comment]
Yep, that's it. It is gone and will not return.

**Comment by ezYakaEagle442** [comment]
I add the snippet updated : 

```sh
k config view --minify --raw --output 'jsonpath={..cluster.certificate-authority-data}' | base64 -d > k3s-server-ca.crt # | openssl x509 -text -out -)
cat k3s-server-ca.crt

k config view --minify --raw --output 'jsonpath={..user.client-certificate-data}' | base64 -d > k3s-admin-user.crt # | openssl x509 -text -out -)
cat k3s-admin-user.crt

k config view --minify --raw --output 'jsonpath={..user.client-key-data}' | base64 -d > k3s-admin-user-key.key
cat k3s-admin-user-key.key

k config set-credentials k3s-admin \
  --client-key=k3s-admin-user-key.key \
  --client-certificate=k3s-admin-user.crt \
  --embed-certs=false

curl -k https://localhost:6443/api/v1/namespaces -H 'Accept: application/json' --cert k3s-admin-user.crt --key k3s-admin-user-key.key 
```

**Comment by brandond** [comment]
I'm confused as to why you need to do this. What problem are you solving?

**Comment by erikwilson** [comment]
Probably to get raw data, which using `kubectl get --raw` might help with. Would suggest avoiding curl's `-k` insecure flag tho.
