### ISSUE TITLE
can a node be used both as master and worker?

### ISSUE THREAD

**Issue by tuananh** [k3s-io/k3s#2746]
for homelab, teh resource is quite restrictive and i would like to use master to host workload as well. is it possible?

**Comment by brandond** [comment]
Yes, servers nodes also run the kubelet, and do not by default create any taints that would prevent scheduling of workload pods.

**Comment by tuananh** [comment]
> Yes, servers nodes also run the kubelet, and do not by default register any taints that would prevent scheduling of workload pods.

So if i have 3 master (ha with embedded etcd) and 2 agents, the workload by default will be scheduled to all 5 nodes?

**Comment by brandond** [comment]
Correct.

**Comment by tuananh** [comment]
Many thanks
