### ISSUE TITLE
Enable logging passthrough

### ISSUE THREAD

**Issue by mxplusb** [k3s-io/k3s#275]
**Is your feature request related to a problem? Please describe.**

I'm attempting to debug the HelmCharts CRD but there aren't any logging flags passed through to the various k8s daemons.

**Describe the solution you'd like**

Support `-v Level` flag for daemons which support it, a good MVP could be the `api-server` and `kube-controller-manager`.

**Describe alternatives you've considered**

None

**Comment by brandond** [comment]
Closing due to age. Flags can be passed through to various components with `--kube-apiserver-args=key=val` etc.
