### ISSUE TITLE
Looking for guidance on k3s + Traefik + rancher + Metal LB

### ISSUE THREAD

**Issue by timothystewart6** [k3s-io/k3s#2756]
**Environmental Info:**
K3s Version: 

`k3s version v1.19.5+k3s2 (746cf403)`
Node(s) CPU architecture, OS, and Version: 

`Linux server-01 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Cluster Configuration:

2 API servers 4 Agents

**Describe the bug:**

Looking for guidance on k3s + Traefik + rancher + Metal LB
**Steps To Reproduce:**

- Installed K3s: 
`k3s version v1.19.5+k3s2 (746cf403)`
**Expected behavior:**

Run both rancher and Traefik with Metal LB
**Actual behavior:**

After configuring Metal LB, the IPs flap and I cannot configure both Rancher and Traefik with Metal LB
**Additional context / logs:**

Every time I install this combination, Traefik stops serving out requests on the Load Balancer.

I stumbled upon this post, which was very helpful, 

https://github.com/k3s-io/k3s/issues/2323

However once I remove the Service LB and Traefik I am able to route to Rancher on the MetalLB IP but I cannot route to any of my services that are deployed to an ingress

I've tried adding it back, but I still cannot route to anything on the new `LoadBalancer` that was created for Traefik and Metal LB.

```
kube-system     traefik                                    LoadBalancer   10.43.45.13     192.168.30.230   80:30720/TCP,443:31969/TCP   37m     app=traefik,release=traefik
cattle-system   rancher-lb                                 LoadBalancer   10.43.105.252   192.168.30.231   443:30728/TCP                19m     app=rancher
```

Any there any tips on how I can get these 3 to work together?

I feel like creating a load balancer for rancher on a Metal LB IP was a step in the right direction however now I cannot access any of my deployments that use the Traefik Load Balancer for HTTP traffic. 

Everything was installed using documentation from k3s, rancher, and metal lb.  

Thank you.

**Comment by timothystewart6** [comment]
I am going to close this.  I have it working with quite a few steps.

The general idea is:

* install `k3s`
* reconfiguring the existing version of traefik that ships with `k3s` didn't seem to work as I expected it to, so I found you have to remove it
* use `--disable servicelb --disable traefik` when installing / reconfiguring your servers
* install and configure metal lb
* install traefik 1/2 - I went with 2
* install rancher
* you can then either expose rancher directly to metal lb or expose it through traefik
* if you expose through traefik you will need to add customer headers for web sockets to work `customRequestHeaders: X-Forwarded-Proto: https`

There are quite a few moving parts here and quite a few quirks since traefik ships with `k3s`.

**Comment by clumbo** [comment]
> I am going to close this. I have it working with quite a few steps.
> 
> The general idea is:
> 
> * install `k3s`
> * reconfiguring the existing version of traefik that ships with `k3s` didn't seem to work as I expected it to, so I found you have to remove it
> * use `--disable servicelb --disable traefik` when installing / reconfiguring your servers
> * install and configure metal lb
> * install traefik 1/2 - I went with 2
> * install rancher
> * you can then either expose rancher directly to metal lb or expose it through traefik
> * if you expose through traefik you will need to add customer headers for web sockets to work `customRequestHeaders: X-Forwarded-Proto: https`
> 
> There are quite a few moving parts here and quite a few quirks since traefik ships with `k3s`.

I am looking to do this.

How did you expose Rancher through metal lb or traefik?

**Comment by timothystewart6** [comment]
@clumbo  if you want to expose it directly to your `LoadBalancer` (metal lb) just use

```
kubectl expose deployment rancher -n cattle-system --type=LoadBalancer --name=rancher-lb --port=443
```

**Comment by clumbo** [comment]
> @clumbo if you want to expose it directly to your `LoadBalancer` (metal lb) just use
> 
> ```
> kubectl expose deployment rancher -n cattle-system --type=LoadBalancer --name=rancher-lb --port=443
> ```

Thanks

**Comment by DavidIlie** [comment]
How would you expose rancher through traefik?

**Comment by ryanwkan** [comment]
@DavidIlie do you mind elaborating on "can't easily control it through rancher"? 

I have rancher with traefik 2.4 setup and can not control it at all through rancher. Anything added via rancher will be stuck at initializing

**Comment by DavidIlie** [comment]
@ryanwkan 

I got it perfectly working to make Rancher Ingresses that are not stuck in "pending". The way I did was with this guide from @timothystewart6 

https://techno-tim.github.io/posts/k3s-traefik-rancher/

**Comment by ryanwkan** [comment]
Wow that was quick! Thanks @DavidIlie !

**Comment by DavidIlie** [comment]
@ryanwkan 

Saw the notification on my phone! Not a problem, glad to help!
