### ISSUE TITLE
Docker Image: Persistent Volume Support for NFS/SMB

### ISSUE THREAD

**Issue by doug62** [k3s-io/k3s#2757]
As a developer I wish to share storage amoungst several edge nodes running K3s as as PersistentVolumes in docker-compose stack via NFS and/or SMB but am currently prevented from doing so because 'samba' and/or 'nfs-utils' is not installed within the image.

I have read and agree that these utilities shouldn't be installed in the normal distro but given the static nature of the images, and the typical/common need to persist shared data kindly ask that we add these to the docker build for:  rancher/k3s

Or is there a better way? Perhaps a docker-compose volume with an NFS/SMB image linked?

AC:
* Able to create shared NFS/SMB PVs from within docker-compose/images

**Comment by eplightning** [comment]
The Kubernetes in general seems to be moving away from in-tree PV drivers. I'd suggest looking at CSI drivers implementing SMB/NFS support:

https://github.com/kubernetes-csi/csi-driver-smb
https://github.com/kubernetes-csi/csi-driver-nfs

**Comment by doug62** [comment]
@eplightning Thanks for the response: You are correct that they are moving PVs into separate drivers, installing those PV/CSI requires that a few other linux nfs/smb utlilities be installed, as the title suggests I am running K3s from  a container/docker-compose stack, it is impossible install the 2 CSI packages because they require installing 'nfs-tools' and 'samba' into the linux shell in order for them to work AND, to save space in the image much as been removed such as 'apk install', so, due to limitations/bugs it is not possible for the "rancher/k3s" image to install/use any PV other than localpath

**Comment by eplightning** [comment]
I'm pretty sure CSI drivers don't require anything to be installed on nodes themselves usually (well some might require custom kernel modules but that's likely very uncommon).

CSI drivers run as standard K8s workloads so they can bundle all userspace tools they need in their Docker images (for example https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smbplugin/Dockerfile).

**Comment by brandond** [comment]
CSI drivers do require things like the iscsi client and utilities to be installed at the host level. I don't think it's appropriate for the k3s container image to bundle all these userspace tools when they really need to be available and compatible with the host kernel in order to operate properly.

**Comment by doug62** [comment]
Thanks - Perhaps I should have clarified - I am trying to run this on a Windows 10 machine with Linux containers - therefore it is not possible to install these items in the host, only option would be to have them in the image - as it stands no  CSI drivers will function.  I understand that folks don't want a larger image but perhaps do another image with these features/dependencies, perhaps a conditional build/dockerfile..  Basic needs NTFS, SMB, Longhorn?

**Comment by brandond** [comment]
@doug62 how are you running this exactly? Most of the stuff I've seen for running Linux containers on Windows gives you either WSL2 host binaries, or a full linux VM to host the container runtime. If you're going to actually mount things using the linux kernel mount interface, it seems like you'd need to be doing this via the latter, in which case you should be able to install the required binaries within the VM.

**Comment by doug62** [comment]
Thanks @brandond I'm hoping to run this on a windows 10 pc, in Windows, no WSL - We are exploring the prospect of adding a K3s agent to all our mostly idle employee's PCs.  Docker for windows does not permit mounting shares (a bug)

**Comment by brandond** [comment]
K3s doesn't currently support native Windows agents; at the moment you would need to run a full linux VM in order to make use of Windows nodes. That may change at some point in the future, but native Kubernetes on Windows still has some difficult wrinkles to work out.

**Comment by doug62** [comment]
@brandond Thanks, however, I'm running Windows 10 host, Docker Linux Containers and aside from the inability to pass shares into the containers that part works (a windows/docker bug).  So the only resolution seems to be to add nfs/smb to the K3s image, it is super stripped down tho, Exploring modifying the K3s docker build and/or use the K3s as a base and add my dependencies...
