### ISSUE TITLE
k3s local image server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by vincentmli** [k3s-io/k3s#2760]
**Environmental Info:**
k3s version v1.20.0+k3s2 (2ea6b163)

Node(s) CPU architecture, OS, and Version: 

Linux 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master, no worker

**Describe the bug:**

followed https://cwienczek.com/2020/06/import-images-to-k3s-without-docker-registry/ to import image as:

 #k3s ctr images import cis-C3456795-v2.0.0.1.tar 

it listed as docker.io/library/k8s-bigip-ctlr:latest as below

#k3s ctr image ls 

REF                                                                                                              TYPE                                                      DIGEST                                                                  SIZE      PLATFORMS                         LABELS                          

docker.io/library/k8s-bigip-ctlr:latest                                                                          application/vnd.docker.distribution.manifest.v2+json      sha256:92de40ac1c8011696d9bcdc330083fd139b8f5a4dc2f1c12ba05e08083a4d8bf 264.4 MiB linux/amd64                       io.cri-containerd.image=managed 

then referenced in deployment yaml and apply the deployment
<pre>
    spec:
      hostNetwork: true
      serviceAccountName: bigip-ctlr-serviceaccount
      containers:
      - args:
        - --bigip-partition
        - k8s
        - --bigip-url
        - 10.169.72.34
        command:
        - /app/bin/k8s-bigip-ctlr
        image:  k8s-bigip-ctlr:latest
        imagePullPolicy: Always
        name: cc-cluster
</pre>

**Steps To Reproduce:**

steps in https://cwienczek.com/2020/06/import-images-to-k3s-without-docker-registry/

**Expected behavior:**

expect k3s pull imported local image

**Actual behavior:**
k3s fail to pull local image

**Additional context / logs:**

Dec 28 22:46:09 k8s-cilium-master k3s[5095]: I1228 22:46:09.448942    5095 event.go:291] "Event occurred" object="kube-system/cc-cluster" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="ScalingReplicaSet" message="Scaled up replica set cc-cluster-5df489cf68 to 1"
Dec 28 22:46:09 k8s-cilium-master k3s[5095]: I1228 22:46:09.462162    5095 event.go:291] "Event occurred" object="kube-system/cc-cluster-5df489cf68" kind="ReplicaSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="Created pod: cc-cluster-5df489cf68-6fg6f"
Dec 28 22:46:09 k8s-cilium-master k3s[5095]: I1228 22:46:09.471435    5095 topology_manager.go:187] [topologymanager] Topology Admit Handler
Dec 28 22:46:09 k8s-cilium-master k3s[5095]: I1228 22:46:09.576917    5095 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "bigip-ctlr-serviceaccount-token-6zqf8" (UniqueName: "kubernetes.io/secret/d8a64d88-7d98-4567-a8fb-e5a972d06e69-bigip-ctlr-serviceaccount-token-6zqf8") pod "cc-cluster-5df489cf68-6fg6f" (UID: "d8a64d88-7d98-4567-a8fb-e5a972d06e69")
Dec 28 22:46:11 k8s-cilium-master k3s[5095]: E1228 22:46:11.773166    5095 remote_image.go:113] PullImage "k8s-bigip-ctlr:latest" from image service failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/k8s-bigip-ctlr:latest": failed to resolve reference "docker.io/library/k8s-bigip-ctlr:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Dec 28 22:46:11 k8s-cilium-master k3s[5095]: E1228 22:46:11.773244    5095 kuberuntime_image.go:51] Pull image "k8s-bigip-ctlr:latest" failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/k8s-bigip-ctlr:latest": failed to resolve reference "docker.io/library/k8s-bigip-ctlr:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Dec 28 22:46:11 k8s-cilium-master k3s[5095]: E1228 22:46:11.773386    5095 kuberuntime_manager.go:829] container &Container{Name:cc-cluster,Image:k8s-bigip-ctlr:latest,Command:[/app/bin/k8s-bigip-ctlr],Args:[--bigip-partition k8s --bigip-url 10.169.72.34 --bigip-username admin --bigip-password admin --verify-interval 30 --namespace default --node-poll-interval 1 --pool-member-type cluster --flannel-name flannel_vxlan --log-level INFO --insecure true --agent as3 --log-as3-response true],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{128 6} {<nil>} 128M DecimalSI},},Requests:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{128 6} {<nil>} 128M DecimalSI},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:bigip-ctlr-serviceaccount-token-6zqf8,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod cc-cluster-5df489cf68-6fg6f_kube-system(d8a64d88-7d98-4567-a8fb-e5a972d06e69): ErrImagePull: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/k8s-bigip-ctlr:latest": failed to resolve reference "docker.io/library/k8s-bigip-ctlr:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by brandond** [comment]
You've imported the image into the local ContainerD image store but then set the imagePullPolicy to Always, which means it's going to go out to your registry and try to pull it again, even though it's already present on disk. If you want to preload the images for airgap purposes, you should set the imagePullPolicy to IfNotFound or Never.

Note that the containerd local image store is NOT a networked registry that you can push to/pull from.

**Comment by vincentmli** [comment]
@brandond Thank you, set imagePullPolicy to  Never resolved the problem
