### ISSUE TITLE
Is cluster federation possible with k3s?

### ISSUE THREAD

**Issue by SadmiB** [k3s-io/k3s#2763]
**Is your feature request related to a problem? Please describe.**

I came across some docs saying that k3s could be deployed in the edge as an independent cluster and the management will be from that edge; so if we have 100 edges for example we will have 100 running clusters each one in it's edge site. 

**Describe the solution you'd like**

I'm wondering if k3s deployed in various edge sites, is it possible to apply kind of cluster federation and join all the clusters to one central cluster deployed in the cloud to make the management of the clusters easy?

**Comment by brandond** [comment]
We generally recommend that folks use [Rancher](https://github.com/rancher/rancher/blob/master/README.md)for multi-cluster management.
