### ISSUE TITLE
Upgrading k3s via system-upgrade-controller causes local-path storage class to be marked as default

### ISSUE THREAD

**Issue by japsu** [k3s-io/k3s#2767]
**Environmental Info:**
K3s Version: 1.19.5+k3s2 to 1.20.0+k3s2

```
k3s version v1.20.0+k3s2 (2ea6b163)
go version go1.15.5
```

Node(s) CPU architecture, OS, and Version: 

```
japsu@qb1:~$ uname -a
Linux qb1 5.4.0-1031-azure #32-Ubuntu SMP Tue Oct 6 09:47:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
japsu@qb1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

Cluster Configuration: Distributed etcd, 3 servers, 1 non-server node (4 nodes in total)

**Describe the bug:**

I have Longhorn installed in my cluster. Longhorn makes its `longhorn` storage class the default storage class by default. To make this work, I have `kubectl edit`ed the k3s-provided `local-path` storage class to have `storageclass.kubernetes.io/is-default-class: "false"` instead of ` storageclass.kubernetes.io/is-default-class: "true"`.

However, when I upgrade K3s using the Rancher System Upgrade Controller, `local-path` resets to being default. This causes the cluster to have two default storage classes, causing in turn PVC allocations that try to use the default storage class to fail with "the cluster has multiple default storage classes".

**Steps To Reproduce:**

1. Install K3s 1.19.5+k3s2
2. Install another storage class, eg. `longhorn`, and mark it as default
3. `kubectl edit storageclass local-path` to make it non-default
4. Upgrade to K3s 1.20.0+k3s2 using Rancher System Upgrade Controller

**Expected behavior:**

`longhorn` is still the default storage class and `local-path` is not

**Actual behavior:**

Both `longhorn` and `local-path` are default, causing PVC allocations using default storage class to fail

**Additional context / logs:**

**Comment by brandond** [comment]
Yes, the l[ocal-storage manifest](https://github.com/k3s-io/k3s/blob/master/manifests/local-storage.yaml#L93) sets the local-path storage class as default. This is required so that PVCs work out-of-the-box on K3s. If you're using an external CSI provider like longhorn, you probably don't need local-storage and should disable it by adding `--disable=local-storage` to the K3s server flags.

**Comment by jonstelly** [comment]
I'm running into a similar issue.  I would like to keep local-path but use longhorn as my default.  Is using `--disable=local-storage` then applying a custom local storage manifest without the `is-default-class` flag the easiest way to go there?

Is that something I can do for an existing cluster or would I need to recreate the cluster?

**Comment by brandond** [comment]
Yes, you can copy the local-storage manifest to another file with a unique name, modify that, and then disable the default local-storage component.
