### ISSUE TITLE
dns cant resolve by cluster_ip when host is defferent from coredns

### ISSUE THREAD

**Issue by dulm** [k3s-io/k3s#2768]
**Environmental Info:**
K3s Version: 

`k3s version v1.18.9+k3s1 (630bebf9)`
Node(s) CPU architecture, OS, and Version: 

`Linux i-qoy2h7fd 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Cluster Configuration:

**2 master 0 workers**

**Describe the bug:**

follow steps in https://v1-18.docs.kubernetes.io/zh/docs/tasks/administer-cluster/dns-debugging-resolution/

```
[root@i-qoy2h7fd ~]# kubectl describe service kube-dns -n kube-system 
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
                   objectset.rio.cattle.io/hash=bce283298811743a0386ab510f2f67ef74240c57
Annotations:       objectset.rio.cattle.io/applied:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/owner-gvk":"k3s.ca...
                   objectset.rio.cattle.io/id: 
                   objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
                   objectset.rio.cattle.io/owner-name: coredns
                   objectset.rio.cattle.io/owner-namespace: kube-system
                   prometheus.io/port: 9153
                   prometheus.io/scrape: true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.43.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         10.42.0.137:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         10.42.0.137:53
Port:              metrics  9153/TCP
TargetPort:        9153/TCP
Endpoints:         10.42.0.137:9153
Session Affinity:  None
Events:            <none>
```

in dnsutils container:
```
[root@i-qoy2h7fd ~]# crictl exec -it 1cb4cf9252a9c sh
/ # dig @10.42.0.137 kubernetes.default

; <<>> DiG 9.11.6-P1 <<>> @10.42.0.137 kubernetes.default
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11776
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kubernetes.default.            IN      A

;; AUTHORITY SECTION:
.                       30      IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021010101 1800 900 604800 86400

;; Query time: 136 msec
;; SERVER: 10.42.0.137#53(10.42.0.137)
;; WHEN: Sat Jan 02 03:53:17 UTC 2021
;; MSG SIZE  rcvd: 122

/ # dig @10.43.0.10 kubernetes.default

; <<>> DiG 9.11.6-P1 <<>> @10.43.0.10 kubernetes.default
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached


/ # telnet 10.42.0.137 53
Connection closed by foreign host
/ # telnet 10.43.0.10 53
telnet: can't connect to remote host (10.43.0.10): Connection refused
/ # telnet 10.43.0.10 54
telnet: can't connect to remote host (10.43.0.10):  Connection timed out
```

the resp of telnet cluster_ip: 53   is different from telnet cluster_ip:54(this port is not listen).

when run dig on the host,  witch is same host of  pod coredns, it runs successfully; when run dig on the host,  witch is diffrent host of pod  coredns, it runs fails. I haven't test in container by different hosts, i think should be same result like in different hosts. 
it's oppsite to https://github.com/k3s-io/k3s/issues/751#issuecomment-619055097

And could access other web server by cluster_ip of other web svc.
```
[root@i-qoy2h7fd ~]# crictl exec -it 1cb4cf9252a9c sh
/ # telnet 10.43.231.177 80
GET / HTTP/1.1
Host: 10.43.231.177
User-Agent: curl/7.61.1
Accept: */*

HTTP/1.1 200 OK
Date: Mon, 04 Jan 2021 02:30:39 GMT
Content-Length: 212
Content-Type: text/plain; charset=utf-8

Hostname: dep-whoami-64898b8798-8d662
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.83
IP: fe80::34d4:7cff:fe87:5023
RemoteAddr: 10.42.0.228:47458
GET / HTTP/1.1
Host: 10.43.231.177
User-Agent: curl/7.61.1
Accept: */*
```

what's the problem,  or how to further diagnose the problem?

**Steps To Reproduce:**

- Installed K3s: 

with  traefik:v2.2
default  flannel VXLAN

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
The cluster DNS service only working on hosts running the CoreDNS service usually indicates some sort of firewall blocking routing between nodes. Can you confirm that you have disabled the firewall between your nodes, or at least opened all the necessary ports?

**Comment by dulm** [comment]
> The cluster DNS service only working on hosts running the CoreDNS service usually indicates some sort of firewall blocking routing between nodes. Can you confirm that you have disabled the firewall between your nodes, or at least opened all the necessary ports?

here is my iptable of the one not run coredns.


[root@i-qoy2h7fd ~]#  iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes externally-visible service portals */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
KUBE-FORWARD  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.2           tcp dpt:10800
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.3           tcp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.3           tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain KUBE-NWPLCY-ST3MSTWE52CMIKX7 (0 references)
target     prot opt source               destination         

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination         

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination         

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-PROXY-CANARY (0 references)
target     prot opt source               destination         

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
DROP       all  -- !127.0.0.0/8          127.0.0.0/8          /* block incoming localnet connections */ ! ctstate RELATED,ESTABLISHED,DNAT

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination         
# Warning: iptables-legacy tables present, use iptables-legacy to see them

**Comment by brandond** [comment]
Are you using the docker backend, or containerd? It looks like there are a bunch of docker-related rules in there.

**Comment by dulm** [comment]
containerd,  

> Are you using the docker backend, or containerd? It looks like there are a bunch of docker-related rules in there.

i use containerd, but the host has installed docker for other usage too.

**Comment by dulm** [comment]
pre state: host1: no

**Comment by dulm** [comment]
pre state: 
|host|coredns| dns suc|
|--|--|--|
|host1|F|F|
|host2|T|T|

I stop k3s on host2, then kubectl rollout restart  coredns, then start k3s on host2, now state is:
|host|coredns| dns suc|
|--|--|--|
|host1|T|F|
|host2|F|T|


maybe  it's only relate to the iptable, so why the two master node's iptable is different.

**Comment by brandond** [comment]
What Linux distribution is this on? Do you perhaps have a mix of legacy iptables and nftables rules?

**Comment by dulm** [comment]
```
[root@i-qoy2h7fd ~]# uname -a
Linux i-qoy2h7fd 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@i-qoy2h7fd ~]# cat /proc/version
Linux version 4.18.0-80.el8.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) #1 SMP Tue Jun 4 09:19:46 UTC 2019
[root@i-qoy2h7fd ~]# lsb_release -a
-bash: lsb_release: command not found
[root@i-qoy2h7fd ~]# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core) 
[root@i-qoy2h7fd ~]# cat /etc/issue
\S
Kernel \r on an \m
```

**Comment by samirsss** [comment]
Was there any update on this issue - we're seeing similar issues and I'd like to know the solution or the root cause

**Comment by brandond** [comment]
> The cluster DNS service only working on hosts running the CoreDNS service usually indicates some sort of firewall blocking routing between nodes.

While firewalls are a frequent issue, anything that mucks with iptables or causes vxlan traffic between nodes to be dropped can cause problems. Confirm that you're running a recent version of K3s, have opened the ports for vxlan (or whatever flannel backend you're using), and that firewalld is disabled.

**Comment by samirsss** [comment]
Thanks Brandon - yes we're using flannel as the cni, we're on 1.18.19 version of k3s

How do i check if iptables is the cause of this issue? We're seeing a curious issue where traefik endpoints disappear too.

**Comment by brandond** [comment]
Oh, that's quite old, in Kubernetes years. Can you try a much more recent version? There was a flannel vxlan fix that we pulled in a bit ago.
