### ISSUE TITLE
Duplicate Hostnames for server nodes in HA cluster

### ISSUE THREAD

**Issue by erikwilson** [k3s-io/k3s#2769]
**Environmental Info:**
K3s Version: 

1.20+

Cluster Configuration:

HA servers

**Describe the bug:**

Node passwords or unique node names not effectively enforced for HA

**Steps To Reproduce:**

- Installed K3s: 
Use multiple servers with same node name

**Expected behavior:**

An error should occur

**Actual behavior:**

Duplicate nodes

**Additional context / logs:**

Needs to work for etcd only nodes

**Comment by davidnuzik** [comment]
For now, putting this in the 1.20.1 milestone -- assuming this LOE is not high and we can get this in this week for 1/13 release.

**Comment by fapatel1** [comment]
@erikwilson wasn't in triage meeting; will need to follow up

**Comment by galal-hussein** [comment]
The issue can't be solved by checking the node password only since this depends on the node password secret which can only be checked after the k8s is up and running, so we need to check a duplicate hostname early at the time we join etcd node as a new member, and fail if we found a duplicate hostname, this issue can be verified by the following steps:

- Start a server (or etcd only node) with node name node1 (--node-name node1)
- join another server with the same node name

you should get an error stating that:
```
FATA[0000] starting kubernetes: preparing server: start managed database: joining etcd cluster: Failed to join etcd cluster due to duplicate node names, please use unique node name for the server
```

**Comment by bmdepesa** [comment]
k3s v1.22.2-rc1 

* Started a server and joined another node with hostname set to that of the first node
```
# node 1
hostnamectl set-hostname node1
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --token secret --cluster-init" INSTALL_K3S_VERSION=v1.22.2-rc1+k3s1 sh -

# node 2
hostnamectl set-hostname node1
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --token secret --server https://<node1_ip>:6443" INSTALL_K3S_VERSION=v1.22.2-rc1+k3s1 sh -
```
* The expected error was seen
```
Sep 21 22:25:34 ip-172-31-42-65 k3s[21998]: time="2021-09-21T22:25:34Z" level=fatal msg="starting kubernetes: preparing server: start managed database: joining etcd cluster: Failed to join etcd cluster due to duplicate node names, please use unique node name for the server"
Sep 21 22:25:34 ip-172-31-42-65 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Sep 21 22:25:34 ip-172-31-42-65 systemd[1]: k3s.service: Failed with result 'exit-code'.
```
