### ISSUE TITLE
wrong stable release channel

### ISSUE THREAD

**Issue by Fuochi** [k3s-io/k3s#2775]
It's not a real bug, but I think https://update.k3s.io/v1-release/channels/stable is pointing to the wrong release:

https://github.com/k3s-io/k3s/releases/tag/v1.20.0+k3s2
instead of
https://github.com/k3s-io/k3s/releases/tag/v1.19.5+k3s2

Is this wanted?

**Comment by Bessonov** [comment]
https://github.com/k3s-io/k3s/pull/2773

**Comment by Fuochi** [comment]
Thanks, I'll wait for the release notes to be updated. Meanwhile, I'm closing the issue.

**Comment by brandond** [comment]
As of yesterday afternoon it should be pointing at v1.20.0+k3s2, please reopen if you're seeing something else.
