### ISSUE TITLE
Need to use stable helm charts repo on k3s install

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#2777]
**Environmental Info:**
K3s Version: 

N/A

Node(s) CPU architecture, OS, and Version: 

N/A

Cluster Configuration:

N/A

**Describe the bug:**

k3s install is still pulling traefik from deprecated helm charts stable repo:
https://github.com/k3s-io/klipper-helm/blob/master/entry#L67

**Steps To Reproduce:**

- Install K3s: `curl -sfL https://get.k3s.io | sh -`
- View helm install pod logs and note this line: `Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com`

**Expected behavior:**

Stable repo should be: `https://charts.helm.sh/stable`

**Actual behavior:**

Stable repo is using the deprecated one

**Additional context / logs:**

Needs to be updated at https://github.com/k3s-io/klipper-helm/blob/master/entry#L67 and then tagged, helm-controller updated and tagged, and then pulled through to k3s

**Comment by rancher-max** [comment]
This is fixed for k3s on v1.20.2 but still needs backports into v1.18 and v1.19

**Comment by brandond** [comment]
Yeah, I realized yesterday that we should have backported this all way back to 1.17

**Comment by rancher-max** [comment]
Validated fixes in latest rcs, but this should be working in the releases that came after Jan 22.

- v1.18.20-rc1+k3s1: `Adding stable repo with URL: https://charts.helm.sh/stable/`
- v1.19.12-rc1+k3s1: `Adding stable repo with URL: https://charts.helm.sh/stable/ `
- v1.20.8-rc1+k3s1: `Adding stable repo with URL: https://charts.helm.sh/stable/ `
- v1.21.2-rc1+k3s1: `Adding stable repo with URL: https://charts.helm.sh/stable/`
