### ISSUE TITLE
etcd probe timeout

### ISSUE THREAD

**Issue by ningpengtao-coder** [k3s-io/k3s#2782]
{"level":"warn","ts":"2021-01-07T12:16:46.416+0800","caller":"rafthttp/probing_status.go:70","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"65526dc322192643","rtt":"6.251985ms","error":"dial tcp 192.168.1.192:2380: i/o timeout"}

**Comment by modzilla99** [comment]
Same here :/

**Comment by dharmendrakariya** [comment]
did you solve brother ? @PengtaoNing @modzilla99

**Comment by modzilla99** [comment]
> did you solve brother ? @PengtaoNing @modzilla99

Sorry, but I didn't find a solution and switched to normal k8s with ansible.

**Comment by dharmendrakariya** [comment]
@modzilla99  thanks for the reply!
Same we are doing.
