### ISSUE TITLE
Master restore from mysql backup fails

### ISSUE THREAD

**Issue by pleusmann-conet** [k3s-io/k3s#2785]
**Environmental Info:**
K3s Version: 
v1.20.0+k3s2 (2ea6b163)

Node(s) CPU architecture, OS, and Version: 
Linux devops-test42.mycompany.de 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 1 node, 1 mysql 

**Describe the bug:**
reinstallation of the k3s master node with a mysql-etcd restored from backup fails.

**Steps To Reproduce:**
1) Use mysqldump to create a backup of your running cluster configuration.
2) Trash cluster
3) recreate mysql server and restore backup
4) reinstall k3s on master node, connecting to the mysql db

**Expected behavior:**

running k3s master (without nodes after the steps stated above) and restored state

**Actual behavior:**

k3s master process is running, but not useable (for instance, no flannel interface provided).

**Additional context / logs:**

A lot of strange stuff int the log, but this is repeating:

Jan 07 21:05:27 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:27.043384270+01:00" level=info msg="Waiting for control-plane node agent startup"
Jan 07 21:05:27 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:27.766522903+01:00" level=info msg="Cluster-Http-Server 2021/01/07 21:05:27 http: TLS handshake error from 127.0.0.1:56726: remote error: tls: bad certificate"
Jan 07 21:05:28 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:28.044026285+01:00" level=info msg="Waiting for control-plane node agent startup"
Jan 07 21:05:28 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:28.116126525+01:00" level=error msg="unable to verify hash for node 'devops-test42.mycompany.de': hash does not match"
Jan 07 21:05:28 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:28.117458428+01:00" level=error msg="Failed to retrieve agent config: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not
Jan 07 21:05:29 devops-test42.mycompany.de k3s[1731]: time="2021-01-07T21:05:29.044231225+01:00" level=info msg="Waiting for control-plane node agent startup"

**Comment by brandond** [comment]
Did you retain any of the files from the old cluster, or is this on a clean host as well?

**Comment by pleusmann-conet** [comment]
The only artifact used from the old cluster is the mysqldump file. no other retained files.

**Comment by pleusmann-conet** [comment]
Any idea of what's wrong here? 
What kind of hash is of concern here?

Is the pasted part of the logfile relevant for my issue at all or should i have a look for different output?

**Comment by pleusmann-conet** [comment]
@brandond any clue?

**Comment by brandond** [comment]
Generally I would expect this to work. Can you provide complete logs from startup onwards, as well as any additional steps you performed? Are you using the exact same arguments to `k3s server` when starting it up on the new host?
