### ISSUE TITLE
k3s 离线安装提示错误

### ISSUE THREAD

**Issue by daixilong** [k3s-io/k3s#2789]
[root@192-168-117-140 kubernetes]# kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by i5Js** [comment]
Try to perform the command without root user, use another one.

**Comment by daixilong** [comment]
[daixilong@192-168-117-140 k3s_dir]$ 
 the connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by vivisidea** [comment]
The default config file for kubectl is located at /etc/rancher/k3s/k3s.yaml

try this
```
mkdir ~/.kube/  && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
```

and execute  `kubectl get nodes` again
