### ISSUE TITLE
Addons must have an unique name

### ISSUE THREAD

**Issue by denysvitali** [k3s-io/k3s#2791]
**Environmental Info:**
K3s Version: v1.18.12+k3s1

Node(s) CPU architecture, OS, and Version: 

amd64, RHEL 7

Cluster Configuration:

- 1x master node (don't judge 😁)

**Describe the bug:**

Manifests in `/var/lib/rancher/k3s/server/manifests` must have an unique name.

I've just randomly discovered this today - it wasn't a pleasant surprise since it deleted two namespaces.  
Basically, our setup includes some static manifests divided into directory in the path mentioned above. Today, whilst adding a new static application on the k3s cluster by adding a new subdirectory in `manifests`, the two namespace.yml files clashed and started to compete with eachother for their addons CRD entry, causing a repetetive deletion of the two namespaces involved (with all the funny consequences of deleting a NS).

Only after removing one of the two `namespace.yml` files, the situation settled and the namespaces stopped terminating themselves. After an intense debug session (where I initially thought it was due to https://github.com/k3s-io/kine/issues/61), I discovered that this whole bug was caused by k3s trying to have two addons with the same name.

**Steps To Reproduce:**

- Installed K3s: Shell script

1. Create two directories in `/var/lib/rancher/k3s/server/manifests`, name them `app-1` and `app-2`.

1. For each folder, create two namespace.yml files, give them two different names.

1. Watch the result with `kubectl get ns -w`

**Expected behavior:**

`k get addons` returns two addons: named however you like (e.g: `app-1_namespace` and `app-2_namespace`)

No resource is automatically deleted because its file name matches the one in another directory.

**Actual behavior:**

![A non pleasant surprise](https://media1.giphy.com/media/146BUR1IHbM6zu/giphy.gif?cid=6c09b952dlwtg10xqa4hmy9wsmfk6glnsgnctfdiyuvj220v&rid=giphy.gif)

In all seriousness, the result is the addons entry named `namespace` and the two namespaces deleting themselves.

**Additional context / logs:**

Granted that this might be an intended behavior, I didn't find this thing mentioned anywhere in the docs, and thus I consider this a bug. A more graceful solution might be preferred (like an error in the events or something more noisy).

**Comment by brandond** [comment]
Yes, I opened an issue for this a while ago back before joining the project... but I'm not finding it at the moment. The addon name is currently based on the file basename, NOT the full pathname within the manifests directory.

I have a WIP PR to rewrite some of the deploy controller behavior, but it's not a high priority at the moment and so has been sitting unmerged pending resolution of a few discussion points.

**Comment by denysvitali** [comment]
I would strongly suggest anyways to mention this problem in the documentation: we might for the time being prevent this issue from happening to someone else 👍

**Comment by denysvitali** [comment]
Still relevant

**Comment by voidengineer** [comment]
Funny! I discovered this by exactly the same way. Seems to be natural to name the file for the namespace 'namespace.yml' ;-)

**Comment by voidengineer** [comment]
Still relevant?

**Comment by denysvitali** [comment]
As far as I know, yes

**Comment by michel-zimmer** [comment]
In case anyone runs into the same problem es I did:

I've been naming the files in the following pattern: `[resource-name].[resource-type].yml`.
Sometimes I have the same name for resources of different types: `istio-ingress.namespace.yml` and `istio-ingress.helm-chart.yml`.

As the addons name is taken from the file name up to the first point, it was trying to use the same addon name.

My workaround is using a dash instead: `istio-ingress-namespace.yml` and `istio-ingress-helm-chart.yml`

**Comment by brandond** [comment]
This was added to the docs in https://github.com/k3s-io/docs/pull/101
