### ISSUE TITLE
traefik update

### ISSUE THREAD

**Issue by Kamzs** [k3s-io/k3s#2792]
**Is your feature request related to a problem? Please describe.**

We want to set Ingress timeouts per domain. Currently, it is not possible as this feature was added to Traefik in v2.

**Describe the solution you'd like**

As of today k3s uses Traefik v1.7.19.
Currently, most up to date Traefik is v2.3.6.

Could you update Traefik version in k3s?

**Comment by jenting** [comment]
duplicate as #1141
