### ISSUE TITLE
fresh k3s install k3s-server process high cpu and failed to response to kubectl

### ISSUE THREAD

**Issue by jli3388** [k3s-io/k3s#2798]
**Environmental Info:**
K3s Version: v1.20.0+k3s2

Node(s) CPU architecture, OS, and Version: Linux k0 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

Cluster Configuration: 1 master, 5 workers. All raspberry pi 4.

**Describe the bug:**
Fresh installation afterwards on the server node, k3s-server would stay on around 100+% cpu and it fails to answer any kubectl command. 

**Steps To Reproduce:**
1. uninstalled old k3s installation using "**k3s-uninstall.sh**" (https://rancher.com/docs/k3s/latest/en/installation/uninstall/).
2. **find . -type d | grep rancher | xargs rm -Rf**   _(manually remove any directory on the system that has the word "rancher" on it. )_
3. follow the[ install doc ](https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster) to make sure the node uses legacy iptables.
4.  **curl -sfL https://get.k3s.io | sh -**
5. **k3s --debug kubectl get nodes**     <--- would simply hangs.. 

- Installed K3s: **curl -sfL https://get.k3s.io | sh -**

**Expected behavior:**
 - **k3s kubectl get nodes**  _<--- should returns at least showing master node before I register any worker nodes._ 
 - k3s-server shouldn't consistently on high cpu usage.
 - 

**Actual behavior:**
 - k3s-server didn't start properly
 - k3s-server failed to communicate with kubectl.

**Additional context / logs:**

**Comment by jli3388** [comment]
[journalctl.log - log tail while I run the k3s server installation](https://github.com/k3s-io/k3s/files/5794134/journalctl.log)
[k3s-install-screen-shot.txt - the screen that shows my installation command and the output from the screen](https://github.com/k3s-io/k3s/files/5794135/k3s-install-screen-shot.txt)
[k3s-kubectl-hangs.txt - run with --debug, but not much output ](https://github.com/k3s-io/k3s/files/5794136/k3s-kubectl-hangs.txt)

**Comment by i5Js** [comment]
Downgrade to 1.19 or wait till 1.20.2, There is a known issue with v1.20 on arm caused by a golang compiler issue. v1.20.2 will include a workaround: kubernetes/kubernetes#97685

**Comment by rancher-max** [comment]
Watching k3s-server with `top` consistently shows below 10% usage on my raspberrypi 4 using commit `6e768c301e77738ffd69934363aa0479c4a516d6`. I am also able to execute kubectl commands successfully, including deploying, removing, etc.
