### ISSUE TITLE
Search domain stops DNS from working properly

### ISSUE THREAD

**Issue by modzilla99** [k3s-io/k3s#2801]
**Environmental Info:**
| Name          | Status | Roles                     | Age | Version      | Internal-IP | External-IP | OS-Image           | Kernel-Version            |
|---------------|--------|---------------------------|-----|--------------|-------------|-------------|--------------------|---------------------------|
| k3s-master-01 | Ready  | control-plane,etcd,master | 1h  | v1.20.0+k3s2 | 10.0.0.52   | \<none>      | Ubuntu 20.04.1 LTS | 5.4.0-60-generic (x86_64) |
| k3s-master-02 | Ready  | control-plane,etcd,master | 1h  | v1.20.0+k3s2 | 10.0.0.53   | \<none>      | Ubuntu 20.04.1 LTS | 5.4.0-60-generic (x86_64) |
| k3s-master-03 | Ready  | control-plane,etcd,master | 1h  | v1.20.0+k3s2 | 10.0.0.54   | \<none>      | Ubuntu 20.04.1 LTS | 5.4.0-60-generic (x86_64) |

**Describe the bug:**
DNS Lookups will always bring up the same IP address. 
This happens the search domain and a wild card record for a subdomain is set. Then every domain lookup will fail and (I think) be resolved like this: `google.com.mydomain.com`

**Steps To Reproduce:**
```bash
ssh -t k3s-master-01 '
 sudo hostnamectl set-hostname k3s-master-01.mydomain.com
 sudo rm -f /etc/resolv.conf
 echo -e "nameserver 10.0.0.1\nsearch mydomain.com" | sudo tee /etc/resolv.conf
 export K3S_TOKEN="d0f23ad0d814bc489a00e111ec5970c7368130be963bfb4"
 export INSTALL_K3S_EXEC="server --cluster-init --secrets-encryption \
                         --tls-san=cluster.mydomain.com \
                         --node-name k3s-master-01
                         --disable traefik --disable servicelb --disable local-storage"

 export INSTALL_K3S_SYMLINK="skip"
 export INSTALL_K3S_CHANNEL="stable"

 sudo curl -SsL "https://share.mydomain.com/k3s" -o /usr/local/bin/k3s #Just to bypass the slow github cdn in my area
 sudo chmod +x /usr/local/bin/k3s

 curl -SsfL "https://get.k3s.io" | sudo --preserve-env=K3S_TOKEN --preserve-env=INSTALL_K3S_EXEC --preserve-env=INSTALL_K3S_SYMLINK --preserve-env=INSTALL_K3S_CHANNEL sh -
'
```
Set *.mydomain to an IP

```zone
*.mydomain.com.			IN      A       10.0.0.150
cluster.mydomain.com.		IN      A       10.0.0.50
k3s-master-01.mydomain.com.	IN      A       10.0.0.52
k3s-master-02.mydomain.com.	IN      A       10.0.0.53
k3s-master-03.mydomain.com.	IN      A       10.0.0.54
```

**Expected behavior:**
```
[modzilla@fedora33 k3s-cluster]$ kubectl run -i -t alpine --image=alpine --restart=Never
If you don't see a command prompt, try pressing enter.
/ # ping google.com
PING google.com (172.217.16.78): 56 data bytes
64 bytes from 172.217.16.78: seq=0 ttl=118 time=3.877 ms
^C
--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.877/3.877/3.877 ms
```

**Actual behavior:**
```
[modzilla@fedora33 k3s-cluster]$ kubectl run -i -t alpine --image=alpine --restart=Never
If you don't see a command prompt, try pressing enter.
/ # ping google.com
PING google.com (10.0.0.150): 56 data bytes
^C
--- google.com ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```

**Additional context / logs:**
I'm a newbie, so tell me what you need!

**Comment by brandond** [comment]
Where are you creating these DNS records? This seems like an issue with your DNS resolver, not K3s.

**Comment by modzilla99** [comment]
On my router / DNS server running bind. The thing is DNS resolution works totally fine on the VMs itself but not in the containers!

**Comment by brandond** [comment]
Alpine uses musl libc which is known to have some odd dns lookup behavior, especially around ndots / search domains. Have you tried this in any different containers? Something based on debian or centos perhaps?

**Comment by modzilla99** [comment]
Oh okay, no I actually did not know that! But shouldn't coredns do the domain resolution?

**Comment by brandond** [comment]
CoreDNS responds to queries. The dns client decides what queries to make, and in what order. This is why you specify search domains, ndots, etc in your resolv.conf, NOT in your dns server configuration.

**Comment by modzilla99** [comment]
Okay thanks for the explanation. But then my configuration should work. my DNS Server doesn't have any search domain specified, only the k3s nodes had that!

I'll try if it's related to alpine later and close the issue if that's the case!

**Comment by brandond** [comment]
Yes, that was my point. You don't configure search domains on the DNS server, that behavior is all client side (resolv.conf + client libraries)

**Comment by asreich** [comment]
@modzilla99 Take note of the busy box version [these](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-if-domain-names-are-resolving) troubleshooting docs DNS use. If your issue isn't with the Alpine behavior, you may be encountering something like [this](https://tech.findmypast.com/k8s-dns-lookup/), which has been an outstanding [issue](https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-613589347) with the suggested resolution of [NodeLocal DNS](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/). Hopefully one of these points you in the right direction.

**Comment by erikwilson** [comment]
k3s will attempt to locate a valid resolv.conf, and it will use 8.8.8.8 if it can't find one. https://github.com/k3s-io/k3s/blob/09eb44ba5340e727344ba6e4ebd514a5ab60e9e2/pkg/agent/config/config.go#L277-L294

You can also manually configure k3s with the `--resolv-conf` flag.

**Comment by modzilla99** [comment]
So I tried it again with ubuntu and the problem still occurs, but running nslookup as the rancher docs tell me to do, it is working perfectly fine, pinging works as well. I'll the --resolv-conf route as that seems to be the easiest.

**Comment by NormJohnIV** [comment]
I was able to replicate this issue on a new deploy on ubuntu server 20.04. 
![Untitled](https://user-images.githubusercontent.com/11449055/108150345-8ac34d00-70a2-11eb-81f8-75db317b0f23.png)

The search domain is being appended to the query, thus causing it to fail lookups. Querying from the Ubuntu hosts works without issue. Also, if i query from the pod but append an ending "." (ex ping google.com.) then the dns is able to resolve without issue. I tested these both with and without the --resolv-conf to no avail. 

After removing the search domains from my hosts the dns resolves inside the pods normally.
![Untitled2](https://user-images.githubusercontent.com/11449055/108151022-cb6f9600-70a3-11eb-962c-d0b8f642ebd9.png)

**Comment by NormJohnIV** [comment]
Also, here is a copy of the netplan. Not setting anything really complicated
`network:
    ethernets:
        eth0:
          optional: true
    vlans:
      vlanXXX:
        id: XXX
        link: eth0
        addresses:
          - 10.XXX.XXX.XXX/XXX
        gateway4:
          10.XXX.XXX.XXX
        nameservers:
          addresses:
            - 10.XXX.XXX.XXX
          search:
            - private.XXX.XXX
      vlanXXX:
        id: XXX
        link: eth0
        addresses:
          - 10.XXX.XXX.XXX/XXX
        nameservers:
          addresses: []
          search:
            - storage.XXX.XXX
    version: 2`

**Comment by DarthBlair** [comment]
@brandond Could you tell me how to change the default ndots setting of the cluster? (maybe during with any K3s args?)

**Comment by brandond** [comment]
@DarthBlair what you're looking for is in the pod spec, it is not configurable at a cluster level:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#poddnsconfigoption-v1-core
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: nginx
  dnsConfig:
    options:
      - name: ndots
        value: "1"
```

**Comment by syphr42** [comment]
I'm running into this problem now exactly as described. For me, it happened when I tried to setup Longhorn to perform NFS backups and it failed to find my NFS server. I found that it is due to this DNS resolution error where "storage.my.domain" is searched as "storage.my.domain.my.domain" and my wildcard CNAME picks that up and directs the request to the wrong server.

I tried the Rancher DNS test from [here](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/) and everything resolved correctly with busybox. I tried alpine and everything worked. So I looked to see what the longhorn-manager image is based on and that is ubuntu:18.04 (https://github.com/longhorn/longhorn-manager/blob/master/Dockerfile.dapper). So I tried a simple test with both ubuntu:18.04 and debian:latest and that seems to be the problem.

Since the Ubuntu and Debian images do not have ping or nslookup installed, I just tried to run `apt-get update` and it is failing trying to retrieve the package lists from the server configured as my wildcard CNAME.

```
kubectl run -it --rm --restart=Never dns-test --image=ubuntu:18.04 -- apt-get update
```

or

```
kubectl run -it --rm --restart=Never dns-test --image=debian:latest -- apt-get update
```

So this is where I'm at in my investigation. I don't know why this is happening only inside containers based on Debian or Ubuntu and only on k3s. Outside of k3s everything is resolving normally on the network and every machine on the network is running either Debian or Ubuntu (including the machines running k3s).

**Comment by brandond** [comment]
Why do you have a wildcard record? DNS client search behavior relies on trying all the configured domain and domain parts until it finds one under which the record exists. If you have a wildcard record in one of your search domains, it breaks that behavior.

**Comment by syphr42** [comment]
A wildcard CNAME record simplifies provisioning services with k8s (and before I switched to k3s, it did the same for Docker Swarm). The wildcard points to a round robin of worker nodes in the cluster so anything provisioned is automatically available. 

I've had this setup for years now working with Swarm, but this is the first time I've seen an issue with the search domain being appended to a fully qualified domain name. My understanding of how resolution worked was that first the name as provided was tried and if that didn't result in a hit, then then search domains are added one at a time. There should be no reason to ever add the search domain to a valid fully qualified domain name. So far, my experience has matched this, but that could have been coincidence.

As for breaking the search domains, you're right. If I were using more than one search domain and the one with a wildcard were tested before others, it would prevent the others from ever being used. However, I only use one search domain so it's not a problem.

**Comment by brandond** [comment]
You might read up on the ndots option in resolv.conf:
https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

**Comment by syphr42** [comment]
Thanks for that link. ndots does indeed explain what's going on. There is still some weirdness with alpine where nslookup seems to ignore ndots while ping respects ndots, but you mentioned that alpine might be different above. While searching for a solution I already put in a workaround for Longhorn by using a dot at the end of the hostname which I think in this specific case is easier than trying to modify Longhorn's manager pods.

The dns config option on pods is useful when I'm writing my own Helm charts or applying manifests directly. However, most published Helm charts do not provide an option to modify the dns config so there are still many cases where changing ndots will be difficult or at least inconvenient. Without some other way to control this behavior, I guess we just need chart maintainers to start adding config option for ndots.

**Comment by modzilla99** [comment]
Yeah, I did. Funnily enough I just ran into this today on Magnum cluster... The easiest way to fix it is changing the nodes search domains to either nothing if possible or in the case of systemd-resolved to something arbitrary:

```bash
mkdir -p /etc/systemd/resolved.conf.d
cat <<EOF > /etc/systemd/resolved.conf.d/override-search-domain.conf
[Resolve]
Domain = sth
EOF
systemctl restart systemd-resolved
```

If you now recreate the pod it should have sth at the end in the resolve.conf and start to work.

**Comment by proligde** [comment]
This seems to be still an issue - tested with current K3S v1.28.4+k3s2.

While I can not reproduce it reliably from scratch, I have some machines here that stopped working out of a sudden. Turns out, the local Router provides a search domain `fritz.box` via DHCP which should be perfectly fine.

While the host system resolves correctly, all DNS resolves within k3s' containers fail, adding the search as a suffix even to FQDNs - even when explicitely requesting external DNS. Example:

```
# host www.spiegel.de 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

Host www.spiegel.de.fritz.box not found: 2(SERVFAIL)
```

So the fix mentioned by @modzilla99 did not work in my case for obvious reasons. I think the root problem is still, that for some reason, search domains are added to FQDN's within K3S.
