### ISSUE TITLE
Traefik Timeout

### ISSUE THREAD

**Issue by Kamzs** [k3s-io/k3s#2805]
**Environmental Info:**
K3s Version: v1.20.0+k3s2

**Describe the bug:**
Not able to set applications timeouts on Traefik with Ingress annotations.

**Steps To Reproduce:**

1. I installed k3s using  curl -sfL https://get.k3s.io | sh -

2. I started k3s with Traefik v2.2 
I was able to do that thanks to solution found here  #1141 .
In detail :
  a. I replaced original /var/lib/rancher/k3s/server/manifests/traefik.yaml with the one including code below:
  ``` apiVersion: helm.cattle.io/v1 
  kind: HelmChart
  metadata:
    name: traefik
    namespace: kube-system
  spec:
    chart: traefik
    repo: https://containous.github.io/traefik-helm-chart
    set:
      image.tag: "2.2"
``` 
  
  b. I started k3s with: sudo k3s server -no-deploy=traefik

3. I deployed on the cluster application with a single endpoint which role is to sleep given amount of seconds (after receiving http request) and respond with status 200 after that.

The application is reachable from outside the cluster through the Ingress.

The timeouts (for application) are defined through Traefik annotations and are equal to 7 seconds for each type of timeout:
  transport.respondingTimeouts.readTimeout
  transport.respondingTimeouts.writeTimeout
  transport.respondingTimeouts.idleTimeout
as described here:
https://doc.traefik.io/traefik/routing/entrypoints/#transport

Ingress description below:
k3s kubectl describe ingress 
```
Name:             test-timeout
Namespace:        app-qplwhubfno7n
Address:          xxx.xxx.xxx.xxx
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                                     Path  Backends
  ----                                     ----  --------
  test-timeout-app-qplwhubfno7n.localhost  
                                           /   test-timeout:8080 ()
Annotations:                               hsts: false
                                           hsts-include-subdomains: false
                                           transport.respondingTimeouts.idleTimeout: 7
                                           transport.respondingTimeouts.readTimeout: 7
                                           transport.respondingTimeouts.writeTimeout: 7
Events:                                    <none>
```
4. I performed http request telling my app to sleep 10 seconds (timeouts are 7 seconds) and return status 200 after that.

**Expected behavior:**
My application should return error 504 (gateway timeout) due to timeout (as time of execution of program (10 sec) exceeded 7 seconds).

**Actual behavior:**
My application returned status 200 after waiting 10 seconds (i.e. Traefik did not returned timeout after 7 seconds).

**Comment by brandond** [comment]
If you're using the upstream Traefik 2.2 helm chart and not seeing the desired behavior, then I believe you should open an issue with Traefik?
