### ISSUE TITLE
Format for using the --kube-proxy-arg option

### ISSUE THREAD

**Issue by sraillard** [k3s-io/k3s#2806]
Using `k3s version v1.19.5+k3s2 (746cf403)`

I would like to change some kube-proxy parameters and specify some options using the k3s server flag `--kube-proxy-arg`. I have tried different formatting, without any luck. Is-there an example to show how to add option?

I have tried these formats:
`--kube-proxy-arg="conntrack-tcp-timeout-established=1800"`
`--kube-proxy-arg="conntrack-tcp-timeout-established 1800"`

**Comment by brandond** [comment]
Either `"--kube-proxy-arg=conntrack-tcp-timeout-established=1800"` or `--kube-proxy-arg=conntrack-tcp-timeout-established=1800` would do it.

**Comment by sraillard** [comment]
Thank you!  

These options are now working correctly (and prevent kube-proxy to change the TCP timeouts):  
* `--kube-proxy-arg=conntrack-tcp-timeout-established=0`
* `--kube-proxy-arg=conntrack-tcp-timeout-close-wait=0`

Maybe adding some informtion here https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#customized-flags would help other trying to use these flags.
