### ISSUE TITLE
k3s-killall.sh is not removing the created network config 

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#2808]
**Environmental Info:**
k3s version v1.20.0+k3s
go version go1.15.5

Node(s) CPU architecture, OS, and Version: 
Linux master1 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 2 workers

**Describe the bug:**
When using host-gw as flannel backend, the routes to access pods in other nodes are not deleted after executing k3s-killall.sh
When using ipsec as flannel backend, the ipsec policies are not deleted after executing k3s-killall.sh

The consequence is that if we move from one backend to another using the same nodes, we might see problems. For example, if we try ipsec and then move to host-gw or vxlan, communication between pods that run on different nodes will not work as the ipsec kernel module will intercept packets and apply the non-cleaned-up policy

**Steps To Reproduce:**
1 - Deploy k3s with ipsec flannel backend with at least two nodes
2 - k3s-killall.sh and k3s-uninstall.sh as stated in the docs `https://rancher.com/docs/k3s/latest/en/installation/uninstall/`
3 - Deploy k3s again now using a different flannel backend with at least two nodes

**Expected behavior:**
k3s-killall.sh removes the created config by the flannel backend

**Actual behavior:**
The created config stays and can create problems

**Comment by manuelbuil** [comment]
Unfortunately, flannel does not support a clean-up command. There was a proposal but nobody implemented it: https://github.com/coreos/flannel/issues/886

**Comment by manuelbuil** [comment]
When moving from ipsec to another backend, one quick and manual way to fix this is by executing `ip xfrm policy flush` or if you can't delete all policies, deleting the flannel-configured policies one by one with `ip xfrm policy delete ....` before deploying again

**Comment by stenwt** [comment]
I might be having an issue like this; I moved from vxlan -> ipsec -> vxlan, and my pods can't communicate across nodes. Would a reboot clean it up? After a reboot, `ip xfrm policy list` shows nothing. Is there anything else that might be hanging around after a reboot?

**Comment by manuelbuil** [comment]
> I might be having an issue like this; I moved from vxlan -> ipsec -> vxlan, and my pods can't communicate across nodes. Would a reboot clean it up? After a reboot, `ip xfrm policy list` shows nothing. Is there anything else that might be hanging around after a reboot?

After removing the policies, it all worked for me
