### ISSUE TITLE
Update rancher docs clarifying removal of node-passwd file

### ISSUE THREAD

**Issue by sonicaj** [k3s-io/k3s#2813]
In latest k3s master, k3s does not write out `/var/lib/rancher/k3s/server/cred/node-passwd` anymore and any users relying on k3s writing it out would be affected.

We should update rancher k3s documentation outlining the new behavior change where k3s stores this as a secret right now. This is the page in question which needs to be updated ( https://rancher.com/docs/k3s/latest/en/architecture/ ).

**Comment by brandond** [comment]
cc @davidnuzik @erikwilson

**Comment by LucasCarioca** [comment]
It definitely took me way too long to find this. I see that the documentation is updated now but there are a lot of old references to `node-passwd`.
