### ISSUE TITLE
SystemD doesn't release command line after start k3s if log-path specified

### ISSUE THREAD

**Issue by verbunk** [k3s-io/k3s#2825]
**Environmental Info:**
K3s Version: Any

Node(s) CPU architecture, OS, and Version: 
x86_64 EL8

**Describe the bug:**
If a seperate log-path is specified during install (present in k3s.service), SystemD gets confused and doesn't release shell after systemctl start k3s. Manual CTRL-C is needed to regain shell. This has no effect on k3s process with backgrounds successfuly.

**Steps To Reproduce:**

- Install K3s with log-path specified
- Attempt to start with systemctl

**Expected behavior:**
- Shell is regained after k3s starts

**Actual behavior:**
SystemD gets confused and doesn't release shell.

**Comment by brandond** [comment]
Duplicate of https://github.com/k3s-io/k3s/issues/2277
