### ISSUE TITLE
 When the IP of the worker node changes, k3s-agent cannot report the IP of the worker node to k3s-server in time, and the k3s-agent service needs to be restarted to trigger an IP update

### ISSUE THREAD

**Issue by waynezhang1984** [k3s-io/k3s#2827]
**Environmental Info:**
K3s Version: 

v1.19.3+k3s2
Node(s) CPU architecture, OS, and Version: 

             beta.kubernetes.io/arch=amd64
             beta.kubernetes.io/instance-type=k3s
             beta.kubernetes.io/os=linux
centos:3.10.0-957.21.3.el7.x86_64

Cluster Configuration:

master:1
worker:3
**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

 When the IP of the worker node changes, k3s-agent cannot report the IP of the worker node to k3s-server in time, and the k3s-agent service needs to be restarted to trigger an IP update
**Actual behavior:**

k3s-agent service needs to be restarted to trigger an IP update
**Additional context / logs:**

**Comment by brandond** [comment]
Kubernetes expects stable network addresses and so by extension does K3s. There are too many corner cases and unexpected behaviors that can be caused by node IPs changing.

**Comment by waynezhang1984** [comment]
In my cluster, each worker node is distributed in different places, and the master node is deployed on the public cloud. Because the worker node is pppoe (ADSL) dial-up Internet access, the IP will change regularly. When the IP changes, k3s-agent can run normally, but it cannot report the latest IP address. What the master sees is the IP address before the change. You need to restart k3s-agent to report the latest IP address. Because the worker nodes are physically scattered. This causes difficulties for cluster operation and maintenance. So I want to see if there is a way to solve this problem.

**Comment by brandond** [comment]
Most distributions offer some way to execute a post-up script anytime network configuration changes. Your best bet would be to use this to trigger a restart of the k3s service.

**Comment by waynezhang1984** [comment]
@brandond Ok,thanks a lot
