### ISSUE TITLE
Verify Postgresql as a supported backend

### ISSUE THREAD

**Issue by leflambeur** [k3s-io/k3s#2828]
**Is your feature request related to a problem? Please describe.**

Currently, k3s does not describe Postgresql as being supported on the rancher maintenance terms

https://rancher.com/support-maintenance-terms/

This is because we do not currently regression test it as a backend

**Describe the solution you'd like**
Perform validation steps on Postgresql as a backend so it can be officially supported on the Matrix

**Additional context**
gz#14360

**Comment by cjellick** [comment]
@brandond we actually recently discovered a particular version is "bad", right?
Can you share what version that is here? if possible, slide a note into our docs too and link here

**Comment by cjellick** [comment]
going to close this issue and @leflambeur will open in rancher/rancher, to maintain a better separation bt cncf k3s and rancher
