### ISSUE TITLE
K3s v1.20.0+k3s2: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by carmelo0x99** [k3s-io/k3s#2829]
**Environmental Info:**
K3s Version: 
k3s version v1.20.0+k3s2 (2ea6b163)
go version go1.15.5

Node(s) CPU architecture, OS, and Version: 
3x Raspberry Pi 4, 4GB, running "minimal" 32-bit Raspbian
```
Linux pico1 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
Linux pico2 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
Linux pico3 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
```

Cluster Configuration:
1 master, 2 workers

**Describe the bug:**
The following error is returned when running "sudo kubectl get nodes -o wide":
`Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Steps To Reproduce:**
- Installed K3s: 
  - master: `curl -sfL https://get.k3s.io | sh -`
  - workers: `curl -sfL https://get.k3s.io | K3S_URL=https://<master_ip>:6443 K3S_TOKEN=<TOKEN> sh -`
  - run `sudo kubectl get nodes -o wide` from CLI

**Expected behavior:**
```
$ sudo kubectl get nodes -o wide
NAME                   STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
pico3   Ready    <none>                 10m   v1.20.0+k3s2   10.0.2.93     <none>        Raspbian GNU/Linux 10 (buster)   5.4.83-v7l+      containerd://1.4.3-k3s1
pico2   Ready    <none>                 10m   v1.20.0+k3s2   10.0.2.92     <none>        Raspbian GNU/Linux 10 (buster)   5.4.83-v7l+      containerd://1.4.3-k3s1
pico1   Ready    control-plane,master   12m   v1.20.0+k3s2   10.0.2.91     <none>        Raspbian GNU/Linux 10 (buster)   5.4.83-v7l+      containerd://1.4.3-k3s1
```

**Actual behavior:**
Commands such as `sudo kubectl get nodes -o wide` are initially OK. After a few minutes they consistently fail with the error below:
`Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
The error can be temporarily recovered if K3s is restarted, such as `sudo systemctl restart k3s`. Invariably, after a short time, the error pops up again.
The dashboard also appears to be in a lock.
The issue goes away if K3s v1.20.0+k3s2 is removed and **v1.19.7+k3s1** is installed instead. The issue seems to be present in v1.20.

**Additional context / logs:**
On a different tab where `sudo k3s kubectl proxy` is run, the following errors appear:
`E0119 15:54:28.828995   18538 proxy_server.go:144] Error while proxying request: context canceled`

**Comment by brandond** [comment]
Please try with v1.20.2. See: https://github.com/kubernetes/kubernetes/pull/97860

**Comment by carmelo0x99** [comment]
Many thanks for your kind response. Upgrading to `v1.20.2+k3s1` seems to have resolved the issue. `kubectl get` is much more stable now.

I seem to have a side problem now, in that the dashboard doesn't seem to work any more.
I've deployed the dashboard according to instructions found at: `https://rancher.com/docs/k3s/latest/en/installation/kube-dashboard/`.
It's been working find previously with both v1.19.7 and v1.20.0. Now it just throws this message:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

I've done a little, newbie-level, debugging but I'm unable to find a way to resolve this. I'd appreciate any suggestions.

```
sudo kubectl get endpoints -o wide --all-namespaces
NAMESPACE              NAME                        ENDPOINTS        AGE
default                kubernetes                  10.0.2.91:6443   15m
kube-system            kube-dns                    <none>           15m
kube-system            metrics-server              <none>           15m
kubernetes-dashboard   kubernetes-dashboard        <none>           12m   <<< ???
kubernetes-dashboard   dashboard-metrics-scraper   <none>           12m   <<< ???
```

```
sudo kubectl get services -o wide --all-namespaces
NAMESPACE              NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE   SELECTOR
default                kubernetes                  ClusterIP   10.43.0.1       <none>        443/TCP                  17m   <none>
kube-system            kube-dns                    ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   17m   k8s-app=kube-dns
kube-system            metrics-server              ClusterIP   10.43.180.227   <none>        443/TCP                  17m   k8s-app=metrics-server
kubernetes-dashboard   kubernetes-dashboard        ClusterIP   10.43.145.43    <none>        443/TCP                  14m   k8s-app=kubernetes-dashboard   <<< ???
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.43.0.51      <none>        8000/TCP                 14m   k8s-app=dashboard-metrics-scraper   <<< ???
```

```
sudo ss -tunap | grep 8001
tcp   LISTEN 0      4096             127.0.0.1:8001               0.0.0.0:*      users:(("kubectl",pid=3974,fd=7))
```

**Comment by brandond** [comment]
Looks like you don't have any pods serving the dashboard?

**Comment by carmelo0x99** [comment]
Please excuse my lack of familiarity with K3s, I'm still learning :)
You're right:
```
sudo kubectl get pods -o wide
No resources found in default namespace.
```

The long and the short of it is that with either v1.19.7 or v1.20.0 the dashboard would work out of the box.
With v1.20.2+k3s1, while `kubectl get` looks stable, the dashboard just stopped working. And, of course, I've followed the same simple steps from the Rancher Docs:
```
GITHUB_URL=https://github.com/kubernetes/dashboard/releases
VERSION_KUBE_DASHBOARD=$(curl -w '%{url_effective}' -I -L -s -S ${GITHUB_URL}/latest -o /dev/null | sed -e 's|.*/||')
sudo k3s kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/${VERSION_KUBE_DASHBOARD}/aio/deploy/recommended.yaml
```

I've taken a look at `https://raw.githubusercontent.com/kubernetes/dashboard/v2.1.0/aio/deploy/recommended.yaml` but I'm unable to spot anything that would make it work with one version but not with another.
Any troubleshooting steps you can recommend?

**Comment by carmelo0x99** [comment]
On a second thought, `default namespace` may be the key here. The following output is more relevant IMHO:
```
sudo kubectl get pods -o wide --all-namespaces
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
kube-system            metrics-server-86cbb8457f-w7lk8              0/1     Pending   0          4h51m   <none>   <none>   <none>           <none>
kube-system            local-path-provisioner-7c458769fb-5pdps      0/1     Pending   0          4h51m   <none>   <none>   <none>           <none>
kube-system            coredns-854c77959c-rvtkx                     0/1     Pending   0          4h51m   <none>   <none>   <none>           <none>
kubernetes-dashboard   dashboard-metrics-scraper-79c5968bdc-2h6jz   0/1     Pending   0          4h48m   <none>   <none>   <none>           <none>
kubernetes-dashboard   kubernetes-dashboard-7448ffc97b-vhlbx        0/1     Pending   0          4h48m   <none>   <none>   <none>           <none>
kube-system            helm-install-traefik-t927p                   0/1     Pending   0          4h51m   <none>   <none>   <none>           <none>
```

READY = 0/1 doesn't look good, correct? I'll try uninstalling/reinstalling to see if the issue gets resolved.

**Comment by brandond** [comment]
All of your pods are pending, not a single one has run yet. Have you looked at the k3s logs? Or described any of the pods to see what they're waiting for?

**Comment by carmelo0x99** [comment]
Everything is running fine now. There must have been something with my upgrade to v1.20.2+k3s1 that had gone awry.

I've documented the procedure, repeated it a few times and the new version looks pretty stable and operational now.

Thanks for your help!
