### ISSUE TITLE
[QA] Test and Verify Oracle Linux Support

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2830]
**On BOTH K3s 1.20.x and 1.19.x as well as RKE2 1.19.x**, test latest Oracle Linux 7.x and 8.x so that we may add such support to our support matrix.

Note that while Oracle Linux is generally expected to work today, it has not yet been explicitly tested. Our testing here will certify and add to the official support matrix on Rancher's website.

**Comment by rancher-max** [comment]
#### Validated v1.19.10, v1.20.6, and v1.21.0 in both k3s and rke2 (using 1.21.0-alpha3 for rke2)

Certified the following cases on Oracle Linux 7.9 and 8.3:
- Fresh Installation and sonobuoy execution 
- Run functional test on imported rke2 cluster on Rancher
- Upgrade using SUC
- Install as local management cluster for Rancher 
- For k3s, validated installation with docker CRI 

Also for k3s, did the first two scenarios using both embedded etcd and external (mysql) datastore.
