### ISSUE TITLE
Request: cgroup v2 CI

### ISSUE THREAD

**Issue by AkihiroSuda** [k3s-io/k3s#2845]
**Is your feature request related to a problem? Please describe.**
CI infra for testing cgroup v2.

Several projects have been using Fedora 33 on Vagrant on GitHub Actions for cgroup v2 infra:
- runc: https://github.com/opencontainers/runc/blob/2adbc66b710f89bea89b6804137c934279a4abff/.github/workflows/test.yml#L91-L122
- containerd: https://github.com/containerd/containerd/blob/c4bff3d17cd0d92e516e755252e98f92d224cf2f/.github/workflows/ci.yml#L352-L378
- Docker/Moby: https://github.com/moby/moby/pull/41918 (on proposal)
- kind: https://github.com/kubernetes-sigs/kind/pull/2017
- Usernetes: https://github.com/rootless-containers/usernetes/blob/fbfc32d7705398fa3e4ad282473ea8dee3bfbe6b/.github/workflows/main.yaml#L31-L58

However,  non-Vagrant instances would be more preferable for better performance.

**Additional context**
cgroup v2 has been enabled by default since Fedora 31.

In addition, Debian 11 and Ubuntu 21.10 are highly like to use cgroup v2 by default as well.
- Debian: https://lists.debian.org/debian-user/2020/12/msg00731.html
- Ubuntu: https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1850667 (See comment `#16` on 2021-01-18)

On other environments, cgroup v2 can be enabled by adding `systemd.unified_cgroup_hierarchy=1` to the `GRUB_CMDLINE_LINUX` line in `/etc/default/grub`.
Requires kernel 5.2 or later for k3s.

**Comment by phedders** [comment]
Would it be possible to expedite a new release to include #2844 ?
Many thanks!

**Comment by AkihiroSuda** [comment]
PR: https://github.com/k3s-io/k3s/pull/2887

**Comment by ShylajaDevadiga** [comment]
Validated cgroup2 fix on fedora33 using commit id 1d85a6a3 on a two node cluster
```
$ k3s -v
k3s version v1.20.2+k3s-1d85a6a3 (1d85a6a3)
go version go1.15.8
$ kubectl get nodes
NAME                                          STATUS   ROLES                  AGE     VERSION
ip-172-31-31-247.us-east-2.compute.internal   Ready    <none>                 4m19s   v1.20.2+k3s-1d85a6a3
ip-172-31-8-209.us-east-2.compute.internal    Ready    control-plane,master   6m23s   v1.20.2+k3s-1d85a6a3
```
Validating rootless on Ubuntu 20.04, Here is the results and initial setup that was needed.  Will create an issue to document these extra steps.

```
$ /usr/local/bin/k3s -v
k3s version v1.20.2+k3s-ad5e504c (ad5e504c)
 
$ /usr/local/bin/k3s server --rootless
FATA[2021-02-09T18:17:52.259301133Z] expected sysctl value "net.ipv4.ip_forward" to be "1", got "0"; try adding "net.ipv4.ip_forward=1" to /etc/sysctl.conf and running `sudo sysctl --system`

Enabled ip_forwarding

$ sudo sysctl -p |grep forward
net.ipv4.ip_forward = 1

$ /usr/local/bin/k3s server --rootless
FATA[2021-02-09T18:19:37.223798150Z] failed to setup UID/GID map: newuidmap 7333 [0 1000 1 1 100000 65536] failed: : exec: "newuidmap": executable file not found in $PATH

Cluster was up after installed uidmap package
$ kubectl get nodes
NAME               STATUS   ROLES                  AGE    VERSION
ip-172-31-30-169   Ready    control-plane,master   147m   v1.20.2+k3s-ad5e504c

$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-5ff76fc89d-pd942   1/1     Running     0          147m
kube-system   coredns-854c77959c-6cwrq                  1/1     Running     0          147m
kube-system   metrics-server-86cbb8457f-22tf5           1/1     Running     0          147m
kube-system   helm-install-traefik-s67rf                0/1     Completed   0          147m
kube-system   svclb-traefik-5kqx7                       2/2     Running     0          147m
kube-system   traefik-6f9cbd9bd4-cjg42                  1/1     Running     0          147m

Here is the detail of the log from the console when k3s server --rootless was run

W0209 20:21:51.017431      18 container_manager_linux.go:671] [ContainerManager] Failed to ensure state of "/k3s": [failed to find container of PID 18: cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-1000.slice/session-11.scope, failed to move PID 18 (in "") to "/k3s": mkdir /sys/fs/cgroup/cpuset/k3s: permission denied, failed to apply oom score -999 to PID 18: write /proc/18/oom_score_adj: permission denied]
E0209 20:22:00.457693      18 summary_sys_containers.go:47] Failed to get system container stats for "/k3s": failed to get cgroup stats for "/k3s": failed to get container info for "/k3s": unknown container "/k3s"
```

On Fedora33, following the above steps, below error is seen on console log
```
$ cat /etc/redhat-release
Fedora release 33 (Thirty Three)

$ lsmod |grep overlay
overlay               139264  0

ERRO[2021-02-09T20:36:13.589998728Z] Failed to retrieve agent config: "overlayfs" snapshotter cannot be enabled for "/home/fedora/.rancher/k3s/agent/containerd", try using "fuse-overlayfs" or "native": failed to mount overlay: operation not permitted
INFO[2021-02-09T20:36:13.981408262Z] Waiting for control-plane node ip-172-31-19-101.us-east-2.compute.internal startup: nodes "ip-172-31-19-101.us-east-2.compute.internal" not found
```

**Comment by AkihiroSuda** [comment]
Why was this closed?

**Comment by brandond** [comment]
@ShylajaDevadiga I know this was linked as the issue for a couple other PRs about rootless, but let's leave it open until we actually get CI for rootless.
