### ISSUE TITLE
k3s agent can't connect to master  "failed to get CA certs"

### ISSUE THREAD

**Issue by JonasGroenbek** [k3s-io/k3s#2852]
this is a school project, hence the ips are not hidden. 

**Environmental Info:**
Master
`k3s -v
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5`

Node(s) CPU architecture, OS, and Version: 
each node is within a AWS t2.micro instances

**Describe the bug:**
It seems that the agent node can't get the correct TSL certificate in order to communicate with the master node. We are in desperate need for a fix soon, but we can't seem to solve the issue.

**Reproduction:**

**Master vm:**
```export K3S_DATASTORE_ENDPOINT='mysql://k3s:123qweasdzxc@tcp(34.89.128.178:3306)/k3s'```

```curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 external-hostname=3.22.187.191 --tls-san 3.22.187.191 --node-external-ip=3.22.187.191" sh -```

```
sudo kubectl get nodes

NAME              STATUS   ROLES                  AGE   VERSION
ip-172-31-20-43   Ready    control-plane,master   78m   v1.20.2+k3s1
```

`sudo cat /var/lib/rancher/k3s/server/node-token`

**Agent vm:**

```curl -sfL https://get.k3s.io | K3S_URL=https://3.22.187.191:6443 K3S_TOKEN=K10c51acd66ae9515cc8260c025fb7d2cf9707762c89f1dde9e02c195dc9b65a0e3::server:85157734a5505d44fbdc96c83f2dc580 sh -```

**Master vm:** 
```
sudo kubectl get nodes
NAME              STATUS   ROLES                  AGE   VERSION
ip-172-31-20-43   Ready    control-plane,master   81m   v1.20.2+k3s1
```

**Agent vm:** 
```
sudo systemctl status k3s-agent
● k3s-agent.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-01-24 19:22:54 UTC; 47s ago
       Docs: https://k3s.io
    Process: 3722 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 3723 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 3724 (k3s-agent)
      Tasks: 6
     Memory: 171.8M
     CGroup: /system.slice/k3s-agent.service
             └─3724 /usr/local/bin/k3s agent

Jan 24 19:22:54 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:54Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/>
Jan 24 19:22:54 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:54Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/b>
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.312499368Z" level=info msg="Starting k3s agent v1.19.5+k3s2 (746>
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.313312920Z" level=info msg="Module overlay was already loaded"
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.313473807Z" level=info msg="Module nf_conntrack was already load>
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.313612229Z" level=info msg="Module br_netfilter was already load>
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.313749406Z" level=info msg="Module iptable_nat was already loade>
Jan 24 19:22:57 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:22:57.315148865Z" level=info msg="Running load balancer 127.0.0.1:4511>
Jan 24 19:23:17 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:23:17.316631450Z" level=error msg="failed to get CA certs: Get \"https>
Jan 24 19:23:39 ip-172-31-4-28 k3s[3724]: time="2021-01-24T19:23:39.318819874Z" level=error msg="failed to get CA certs: Get \"https>
lines 1-22/22 (END)
```

**Additional context / logs:**

`://127.0.0.1:45113/cacerts\": read tcp 127.0.0.1:58444->127.0.0.1:45113: read: connection reset by peer"`

**Comment by KristofferTolboll2** [comment]
bump

**Comment by brandond** [comment]
Are the ports open on the server node? Can you successfully `curl -vk https://3.22.187.191:6443/cacerts` from the agent?

**Comment by GetchaDEAGLE** [comment]
@brandond, I'm having the exact same problem. However, when running the curl command to get the cacerts, it works perfectly fine. I had the exact same problem with RKE2 as well. Any thoughts as to what could be causing this?

**Comment by brandond** [comment]
@GetchaDEAGLE can you provide full logs, with --debug?

**Comment by GetchaDEAGLE** [comment]
@bradtopol, I'm trying a few things and then I'll provide the full logs. I can definitely confirm that when I remove the load balancer from the equation, it works fine. Not sure why that's happening as I didn't have a problem with RKE. Also, I'm using HAProxy as the load balancer in this situation. 

**When I Stop HAProxy**

`Mar 07 15:13:11 k8s-wrkr-dev-01 k3s[16618]: time="2021-03-07T15:13:11.585476102-06:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:39255/cacerts\": read tcp 127.0.0.1:43126->127.0.0.1:39255: read: connection reset by peer"`

**When I Start HAProxy**

`Mar 07 15:13:13 k8s-wrkr-dev-01 k3s[16618]: time="2021-03-07T15:13:13.600047017-06:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:39255/cacerts\": EOF"`

**Comment by GetchaDEAGLE** [comment]
@brandond, I figured it out. Hopefully this solution will help someone that may be running HAProxy. I updated my HAProxy config file and changed the offending line which fixed the problem.

**Changed:**

tcp-request content accept if { req_ssl_hello_type 1 }

_to ->_

tcp-request content accept if { req_ssl_hello_type 2 }


**Fixed HAProxy Config:**

```
frontend k8s-api
        description Kubernetes API
        bind *:6443
        mode tcp
        tcp-request inspect-delay 5s
        tcp-request content accept if { req_ssl_hello_type 2 }
        option tcplog
        option socket-stats

        acl k8s-api-clstr-mgmt req_ssl_sni -i k8s-clstr-mgmt.internal.example.com
        use_backend k8s-api-clstr-mgr-nodes if k8s-api-clstr-mgmt

        acl k8s-api-tools req_ssl_sni -i k8s-tools.internal.example.com
        use_backend k8s-api-tools-nodes if k8s-api-tools

        acl k8s-api-dev req_ssl_sni -i k8s-dev.internal.example.com
        use_backend k8s-api-dev-nodes if k8s-api-dev
```

**Comment by GetchaDEAGLE** [comment]
@bradtopol, I ended up resolving my problem. I was using the req_ssl_sni option in HAProxy so I could forward to multiple K8s backends using the same listener port and then route based on the FQDN. It appears this is the problem. This seems to work with kubectl when getting nodes and also works fine on server nodes but when used with agent nodes, results in the CA certs error.

The fix in HAProxy was to not use req_ssl_sni and have multiple frontends which listen on different ports (e.g. 10443, 11443, 12443) which then route the traffic to their respective backends on 6443. The only downside to this approach is keeping track of the different ports. It would be great to just use a listener for 6443 and then route based on the FQDN.

Thanks for your time and willingness to help. It's greatly appreciated.

**Comment by brandond** [comment]
Not sure why people keep tagging @bradtopol when they're replying to me...

**Comment by GetchaDEAGLE** [comment]
> 
> 
> Not sure why people keep tagging @bradtopol when they're replying to me...

My bad... autocomplete is my enemy in this case.

**Comment by nickma82** [comment]
Cross link to https://github.com/k3s-io/k3s/issues/3882

I used RockyLinux who's firewallD by default blocked `port 6443/tcp`. Adding it to the public zone worked for me:
```
systemctl status firewalld.service     # showed a working version
firewall-cmd --zone=public --add-port=6443/tcp
firewall-cmd --list-ports
```

**Comment by guigomcha** [comment]
> @brandond, I'm having the exact same problem. However, when running the curl command to get the cacerts, it works perfectly fine. I had the exact same problem with RKE2 as well. Any thoughts as to what could be causing this?
> 
> **Update:** When I update /etc/systemd/system/k3s-agent.service.env to use the IP address of the manager node, it works fine. It has issues going through the load balancer for some reason but works fine when I use curl to get the cacerts from that node.

 @brandond it has been a while but, could you show what your k3s-agent.service.env looks like? I do not see documentation about this file or how to set the load balancer IP to point to the master node.

Although logs show that local load balancer should be redirecting to the master node it is clear that it is not doing so
 ```
INFO[0000] Starting k3s agent v1.22.3+k3s1 (61a2aab2)
INFO[0000] Running load balancer 127.0.0.1:6443 -> [MASTER_IP:6443]
ERROR[0020] failed to get CA certs: Get "https://127.0.0.1:6443/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by brandond** [comment]
> Although logs show that local load balancer should be redirecting to the master node it is clear that it is not doing so

It does. The load-balancer connects to the server nodes, and then the client issues HTTP requests through the load-balancer. You might use `curl` to confirm that the agent can actually reach the server on port 6443.

**Comment by guigomcha** [comment]
> > Although logs show that local load balancer should be redirecting to the master node it is clear that it is not doing so
> 
> It does not redirect, it tunnels the connections. The load-balancer connects to the server nodes, and then the client issues HTTP requests through the load-balancer, and the requests are routed to an available server. You might use `curl` to confirm that the agent can actually reach the server on port 6443.

Ok... Curl shows that the master noder is reachable on port 6443. The firewall for the server where the worker node is deployed might be problematic, do I need to open (for in and out) and 6443 for any protocl in particular needed for the tunneling thing that is not the one used by curl?   Should I have 6444 fully open too?

It is truth that the worker node is deployed in a NUC that does not have a load-balancer provider configured or anything like that, could that be an issue? I have tested the installation when both master and worker sit inside an Openstack and it works like a charm....

**Comment by guigomcha** [comment]
in case it helps anyone, hosts need to allow all connections  coming from localhost in the local firewall config.

**Comment by brandond** [comment]
That is correct. Servers also run an agent, and will need to be able to connect back to themselves.

**Comment by dempc6469** [comment]
> in case it helps anyone, hosts need to allow all connections coming from localhost in the local firewall config.

it did indeed help someone! thank you for this.

**Comment by mathisve** [comment]
What did it for me was to double check my Security Groups and make sure that traffic between the two instances is actually allowed!

**Comment by matschaffer-roblox** [comment]
I ran into this because I'd accidentally set my server to port 6443 instead of 9345 🤦

**Comment by matttrach** [comment]
I have also run into this because I was setting the server attribute on the initial server. /facepalm
The server attribute should not point to the server being deployed.

**Comment by yyu233** [comment]
I ran into the same issue.  `curl -kv https://172.22.22.163:6443` returned the CA, but ks-agent.service failed. 

```level=info msg="Adding server to load balancer k3s-agent-load-balancer: 172.22.22.163:6443"
 level=info msg="Running load balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [172.22.22.163:6443] [default: 172.22.22.163:6443]"   
 level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:42113->127.0.0.1:6444: read: connection reset by peer"
```
```
curl -kv https://127.0.0.1:6444/cacerts

* Uses proxy env variable https_proxy == 'http://127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
* Connected to (nil) (127.0.0.1) port 7890 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to 127.0.0.1:6444
> CONNECT 127.0.0.1:6444 HTTP/1.1
> Host: 127.0.0.1:6444
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
* error:0A000126:SSL routines::unexpected eof while reading
* Closing connection 0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
```

**Comment by brandond** [comment]
> `* Uses proxy env variable https_proxy == 'http://127.0.0.1:7890'`

What exactly do you have going on with your proxy here?

**Comment by brandond** [comment]
Check that you can `curl -vks https://172.22.22.163:6443/cacerts`

**Comment by yyu233** [comment]
> curl -vks https://172.22.22.163:6443/cacerts

This works and returns the CA.

**Comment by brandond** [comment]
Make sure you don't have a local firewall enabled?

**Comment by ksl28** [comment]
Got the exact same issue here - been following this guide.
https://fernandosilva.me/3-node-k3s-cluster-with-etcd-and-metallb-4ddc7dcfb303

UFW is disabled on the first node, and when i execute this command `curl -vk https://192.168.4.41:6443/cacerts` it returns the certificate just fine.
![image](https://github.com/user-attachments/assets/1ff93298-b17e-45f8-8482-f76acd780e11)

**Comment by qin-nz** [comment]
FYI:
In my case,  `curl -kv https://172.22.22.163:6443` is ok, but k3s can't connect.
Because MTU on both server is config to 1500, but actual MTU is less.  It's totally a network problem.

**Comment by Ilshidur** [comment]
I had the same issue when using the wrong port in the join command :
```diff
- curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://XXX.XXX.XXX.XXX --token MYTOKEN" sh -s -
+ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://XXX.XXX.XXX.XXX:6443 --token MYTOKEN" sh -s -
```
