### ISSUE TITLE
K3s如何部署Flink流式计算软件

### ISSUE THREAD

**Issue by wanziyu** [k3s-io/k3s#2855]

**Comment by brandond** [comment]
https://ci.apache.org/projects/flink/flink-docs-stable/deployment/resource-providers/standalone/kubernetes.html

**Comment by wanziyu** [comment]
Which kinds of Flink on k8s development could be used on k3s cluster? I mean standlone, native or operator.

**Comment by brandond** [comment]
I don't really know anything about Flink, I would refer to their documentation or post a question on their forums or issue tracker. Just following their standard Kubernetes instructions should work.
