### ISSUE TITLE
Renew API cert with added --tls-san

### ISSUE THREAD

**Issue by gazzer82** [k3s-io/k3s#2856]
I have a 3 master k3s cluster setup on Ubuntu 20, running etcd.

I need to update the api cert to add an additional floating IP to the cert, so I've updated the k3s.service file on master 1, adding a second --tls-san option for that IP.

So it now looks like this:

```
ExecStart=/usr/local/bin/k3s \
    server --disable servicelb --disable traefik \
        '--cluster-init' \
        '--tls-san' \
        '11.11.11.11' \
        '--tls-san' \
        '12.12.12.12' \
```

Master 2/3 have service files that look like this, so I have made no changes to them.

```
ExecStart=/usr/local/bin/k3s \
    server --disable servicelb --disable traefik \
        '--server' \
        'https://10.10.10.10:6443' \
```

I have restarted the K3S service on all systems, rebooted master 1, and fully drained master 2 and master 3, but the API cert doesn't seem to be updating with the additional IP address?

If there a way to manually force the certificate to be rotated with the new config, or steps I need to take to force the rotation and then updating of the cert on the management pane for all masters?

I have done some googling, but haven't managed to find anything, apologies if I've missed the steps somewhere!

Thanks

Gareth

**Comment by brandond** [comment]
You should see additional DNS or IP SAN entries show up on the port 6443 listener after you have made a request to that IP or hostname.

**Comment by gazzer82** [comment]
> You should see additional DNS or IP SAN entries show up on the port 6443 listener after you have made a request to that IP or hostname.

I’m assuming that’s after updating the —tls-san parameter and restarting the service? When I was testing that earlier that didn’t seem to be working, subsequent requests where reporting the same inital IP addresses?

**Comment by brandond** [comment]
Are you getting an error when accessing it at the floating IP address? Have you added that arg to all the nodes that might host the floating IP?

**Comment by kidhasmoxy** [comment]
Running into the same issue with the same setup (cluster with embedded etcd) and adding the load balancer after. 

Have added the tls parameter to the service setup of all 3 servers, restarted the service, attempted to use kubectl and got the tls error. Get the error every time I try to access via the load balancer IP. 

Will it only trigger if I add a worker to the cluster using the load balancer ip?

**Comment by ambis** [comment]
I had the same problem initially with `v1.20.4+k3s1`, using `K3S_CONFIG_FILE` which had the tls-san spesified.

When running the installer script after changes, it just said `No change detected so skipping service start`. So I restarted each k3s instance manually with `systemctl restart k3s`. 

It took some minutes after that when kubectl started to work using the new hostnames without tls error. 

Maybe the change detection algorithm in the installer needs a bit of TLC, to check if `K3S_CONFIG_FILE` has any changes in it?

It could also be, that k3s tracks chages to the config file and the whole restart process was unnecessary...

**Comment by brandond** [comment]
That is correct. If you are relying on the install script to restart K3s for you, you should be aware that it only detects changes to the systemd unit. If you change the environment or config file, you should manually restart the service.

In general I wouldn't rely on the install script as a general-purpose utility for changing configuration. If that's all you need to do, just edit the systemd unit, environment file, or config file, and then reload/restart the service.

**Comment by hauks96** [comment]
Can anyone explain what needs to be changed and where in order to update the tls-san options? Or maybe link some useful documentation that I can read upon to understand how to configure it?

I just want to add a domain to the tls-san but I don't have a clue how to do it. I can only find half a sentence of context for this functionality in the k3s docs.

**Comment by FischerLGLN** [comment]
I've found the solution [here](https://github.com/k3s-io/k3s/issues/3369#issuecomment-849005179), you just have to renew the dns cache. I could execute this on the master node:

```sh
export MY_LB_IP=<IP>
curl -vk --resolve $MY_LB_IP:6443:127.0.0.1  https://$MY_LB_IP:6443/ping
```
No changes to the external/client kubeconfig are needed after this!
