### ISSUE TITLE
K3S crashing

### ISSUE THREAD

**Issue by srayancha** [k3s-io/k3s#2859]
**Environmental Info:**
K3s Version: 
k3s version v1.19.5+k3s2 (746cf403)

Node(s) CPU architecture, OS, and Version: 
Linux ip-10-202-13-193.ec2.internal 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
currently scaled to 1 master only, have operated as 1,2, and 3 masters as well

**Describe the bug:**
On any of the nodes, k3s is crashing.  I have k3s logs, a portion of them is attached to the ticket.

**Steps To Reproduce:**
Any existing or new node that has k3s installed and is attached to the backing AWS AuroraDB has this issue.

**Expected behavior:**
Not crash

**Actual behavior:**
Crash

**Additional context / logs:**
Logs are attached to the ticket.
[k3slogs.txt.zip](https://github.com/k3s-io/k3s/files/5868701/k3slogs.txt.zip)

**Comment by brandond** [comment]
These logs seem to be sorted in descending order with newer events at the top, which makes them very hard to read. Can you get them in the normal order? 

`journalctl --no-pager -u k3s &> k3s.log`

**Comment by srayancha** [comment]
Grabbed the logs for the last hour in regular order.  Let me know if this is better.

[k3slogs4.txt.zip](https://github.com/k3s-io/k3s/files/5868948/k3slogs4.txt.zip)

**Comment by brandond** [comment]
The response times from the database are higher than I would like to see. The increasing response latencies are also followed by some weird responses from the datastore layer that I have not seen before, but I suspect are caused by the backend database rejecting connections. What size RDS database are you using? Are there any errors in the database logs? Do the metrics suggest any throttling or connection limiting is occurring?

You should also note that we have not technically qualified RDS Aurora in MySQL or PostgreSQL modes for use with K3s - only MySQL and PostgreSQL (and their direct RDS equivalents) have been tested. If increasing the RDS database size does not resolve the issue, you might try switching to a better supported RDS database type.

**Comment by srayancha** [comment]
When the issue started I had a similar feeling and I sized up the DB writer to R5.large.  That is 2 cores and 16GB of RAM.  The actualy K3S nodes are now T3a.large, so I think sizable enough.  There is some oddness in the DB logs below.  So this may be the issue.  CPU usage on the DB is a bit high, bouncing between 20-60%.  For some reasons I thought AuroraDB was supported after reading a hosted Rancher whitepaper.  I can look to switching if I can't get this working.  I'll review all of our VPC and security group settings as well.  I don't think there is an issue since the new node would've have even been able to join the cluster, but not sure.

`2021-01-25T18:58:36.805319Z 598421 [Note] Aborted connection 598421 to db: 'kubernetes' user: 'admin' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.828019Z 599642 [Note] Aborted connection 599642 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.828027Z 599641 [Note] Aborted connection 599641 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.828082Z 599639 [Note] Aborted connection 599639 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.828247Z 599640 [Note] Aborted connection 599640 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.829835Z 599638 [Note] Aborted connection 599638 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.829845Z 599637 [Note] Aborted connection 599637 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.829976Z 599636 [Note] Aborted connection 599636 to db: 'unconnected' user: 'unauthenticated' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.914735Z 599132 [Note] Aborted connection 599132 to db: 'kubernetes' user: 'admin' host: '10.202.13.193' (Got an error reading communication packets)
2021-01-25T18:59:29.914735Z 599131 [Note] Aborted connection 599131 to db: 'kubernetes' user: 'admin' host: '10.202.13.193' (Got an error reading communication packets)
----------------------- END OF LOG ----------------------`

**Comment by brandond** [comment]
I would avoid running K3s on any burstable instance types. The Kubernetes scheduler depends on having a consistent amount of CPU to allocate to pods, and this expectation is violated when burstable instance types run out of CPU credits and begin throttling. Everything looks fine until you start putting actual load on the system and then things start falling over because you're starved for CPU time. Better to use larger instance types that allow consistent 100% utilization. If you must use burstable instances then run them in Unlimited mode so that they don't get throttled.

Out of curiosity, are you running Aurora in MySQL or PostgreSQL mode?

If you are going to switch engines I would recommend mysql first. It seems to do a better job of supporting the query workload that K3s uses. Postgres 13 works quite well too, but I have seen performance issues at moderate scale with PostgreSQL 11 and to a lesser extent 12.

**Comment by srayancha** [comment]
I believe we're running in unlimited mode, but I'll double check.  I can try a standard instance to see what happens.  There still isn't much loaded on here, but it's possible we're hitting limits.

We're running with Aurora as MySQL 5.7.  We have 4 deployments, Dev, QA, Demo and Prod.  The first 3 are behaving right now.  Prod is the only one misbehaving.  At the moment there are an extra 2 clusters managed in Rancher prod.

**Comment by srayancha** [comment]
Ok, switched to a C5.Large instance. Things are much more responsive, but it appears K3S is still crashing.  I'll try scaling the DB up some more, but I really think there's some kind of runaway blocking process that keeps causing this.  Any other ideas on what I can try?

**Comment by brandond** [comment]
Are you running all 4 deployments on the same RDS instance? What version of Rancher are you using? My first suggestion would be to switch over to using RDS MySQL 8.0 but that would require downtime to dump/restore the SQL database.

**Comment by srayancha** [comment]
No, each deploying has a different RDS DB backing it.  At the moment, I've held stable for an hour now by changing the DB sizing to r5.xlarge.  CPU usage is very spiky, but appears to top out around 45%.  Going to see how this holds up. I'll probably re-size our original two nodes to not use burstable instances and shutdown the third node if that looks good.  I'll update again tomorrow if this appears to be stable and close the ticket.  Thanks for the help!

**Comment by srayancha** [comment]
Ok, we appears to be more stable, but we're still crashing and I'm really stumped on why.  Plenty of extra capacity now on the hosts as well as the DB.  Log from one of the nodes for the last hour attached.
[k3s.log.zip](https://github.com/k3s-io/k3s/files/5870167/k3s.log.zip)

**Comment by brandond** [comment]
Same thing, DB latency is way too high. The times here should never be over 2-3 seconds max. At 9-10 seconds Kubernetes internal components start timing out when they fail to renew their master leases, and then everything crashes.

I think you're going to need to switch off of Aurora.

```
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[1348488127]: [9.987864077s] [9.987864077s] END
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: E0125 23:00:58.508402   27841 autoregister_controller.go:195] v1alpha1.fleet.cattle.io failed with : context deadline exceeded
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: time="2021-01-25T23:00:58.508446337Z" level=error msg="error in txn: context canceled"
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: time="2021-01-25T23:00:58.508799015Z" level=info msg="Cluster-Http-Server 2021/01/25 23:00:58 http: TLS handshake error from 127.0.0.1:59358: EOF"
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:00:58.518308   27841 trace.go:205] Trace[617977170]: "Patch" url:/api/v1/namespaces/kube-system/pods/traefik-758cd5fc85-9rc4t/status,user-agent:k3s/v1.19.5+k3s2 (linux/amd64) kubernetes/746cf40,client:127.0.0.1 (25-Jan-2021 23:00:48.532) (total time: 9985ms):
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[617977170]: [9.985528483s] [9.985528483s] END
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:00:58.519368   27841 trace.go:205] Trace[119328997]: "Patch" url:/api/v1/nodes/ip-10-202-11-14.ec2.internal/status,user-agent:k3s/v1.19.5+k3s2 (linux/amd64) kubernetes/746cf40,client:127.0.0.1 (25-Jan-2021 23:00:48.528) (total time: 9990ms):
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[119328997]: [9.99076643s] [9.99076643s] END
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: time="2021-01-25T23:00:58.566647950Z" level=error msg="error in txn: context deadline exceeded"
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:00:58.566717   27841 trace.go:205] Trace[1254312415]: "Create" url:/api/v1/namespaces/default/events,user-agent:k3s/v1.19.5+k3s2 (linux/amd64) kubernetes/746cf40,client:127.0.0.1 (25-Jan-2021 23:00:24.566) (total time: 34000ms):
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[1254312415]: [34.000228685s] [34.000228685s] END
Jan 25 23:00:58 ip-10-202-11-14.ec2.internal k3s[27841]: E0125 23:00:58.566929   27841 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"ip-10-202-11-14.ec2.internal.165d9bdf302433e4", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-202-11-14.ec2.internal", UID:"ip-10-202-11-14.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kube-proxy.", Source:v1.EventSource{Component:"kube-proxy", Host:"ip-10-202-11-14.ec2.internal"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbffbf1422126e3e4, ext:3926267411, loc:(*time.Location)(0x6ec2900)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbffbf1422126e3e4, ext:3926267411, loc:(*time.Location)(0x6ec2900)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Timeout: request did not complete within requested timeout 34s' (will not retry!)
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:01:00.098120   27841 trace.go:205] Trace[356475293]: "GuaranteedUpdate etcd3" type:*core.ConfigMap (25-Jan-2021 23:00:35.418) (total time: 24679ms):
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[356475293]: ---"Transaction committed" 24679ms (23:01:00.098)
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[356475293]: [24.679663886s] [24.679663886s] END
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:01:00.098120   27841 trace.go:205] Trace[1283307823]: "GuaranteedUpdate etcd3" type:*core.ConfigMap (25-Jan-2021 23:00:54.860) (total time: 5237ms):
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[1283307823]: ---"Transaction committed" 5236ms (23:01:00.098)
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[1283307823]: [5.237287449s] [5.237287449s] END
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: I0125 23:01:00.098228   27841 trace.go:205] Trace[775957565]: "Update" url:/api/v1/namespaces/kube-system/configmaps/rancher-controller-lock,user-agent:rancher-operator/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.202.12.60 (25-Jan-2021 23:00:35.418) (total time: 24680ms):
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[775957565]: ---"Object stored in database" 24679ms (23:01:00.098)
Jan 25 23:01:00 ip-10-202-11-14.ec2.internal k3s[27841]: Trace[775957565]: [24.680111844s] [24.680111844s] END
```

**Comment by srayancha** [comment]
Ok got it, thanks for the info.  I'll have to work on backing up the DB and restoring to RDS.

**Comment by brandond** [comment]
Rancher is a great stress test for Kubernetes datastores because it is constantly hammering on updates to custom resources. Things that might work fine for a workload that doesn't use Kuberneted much for anything except the occasional update to a deployment version or scaling things up/down won't work for Rancher because it's constantly updating the CRDs to reflect the actual state of downstream clusters.

**Comment by srayancha** [comment]
Yeah, makes total sense.  I can also see it by looking at the transaction rate on the DB.  Something is still weird with this level of latency.  It appears to be over writes/updates so I wonder if something in the way AWS implements MySQL in Aurora causes certain blocking/deadlock situations to mirror the writes to the slave/reader instance(s).  I'm trying an upgrade of the Aurora version to see if we get better behavior, but if not, then I'll stand up regular RDS.  For what it's worth, Aurora is depicted in the Rancher Cloud PDF which is why I thought it was supported.

**Comment by srayancha** [comment]
Ok, backed up and restored to an RDS MySQL instance.  It's held stable with no pods restarts for about a half hour.  I am getting some errors about the metrics API.  Otherwise things look ok.  Log snippet below.  Any ideas for what's hopefully the last issue here?

`Jan 26 02:57:40 ip-10-202-11-14.ec2.internal k3s[18974]: E0126 02:57:40.337659   18974 available_controller.go:490] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: bad status from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: 404
Jan 26 02:57:40 ip-10-202-11-14.ec2.internal k3s[18974]: E0126 02:57:40.338446   18974 available_controller.go:490] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: bad status from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: 404
Jan 26 02:57:40 ip-10-202-11-14.ec2.internal k3s[18974]: E0126 02:57:40.371435   18974 available_controller.go:490] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: bad status from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: 404
Jan 26 02:57:40 ip-10-202-11-14.ec2.internal k3s[18974]: E0126 02:57:40.907295   18974 available_controller.go:490] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: bad status from https://10.43.129.131:443/apis/metrics.k8s.io/v1beta1: 404`

**Comment by brandond** [comment]
Glad to hear that it's working for you on MySQL! I see that metrics server stuff from time to time, it's not likely to be related.

**Comment by srayancha** [comment]
Thanks!  Yeah, the metrics server stuff seems to have cleared up eventually.  Logs look very clean now.  I'll have to check our other deployments to see if I'm seeing similar issues with long running requests.  I feel like we would've seen that before though.  This deployment had more horsepower and a couple of clusters added.  The one thing I didn't think of before, any chance you've seen issues with index corruption in the DB before causing problems?  I wonder if that could have been the issue.  Otherwise, AuroraDB just my not be a way to go with K3S.
