### ISSUE TITLE
k3s not working in Ubuntu 20.10 on Raspberry pi 4B

### ISSUE THREAD

**Issue by Amazeryogo** [k3s-io/k3s#2860]
**Environmental Info:**
K3s Version: 

v1.20.2+k3s1
Node(s) CPU architecture, OS, and Version: 

Raspberry pi 4 (ARM)
OS: Ubuntu Server 20.10

Cluster Configuration:

Installation Problem (so 0 masters and 0 workers)

**Describe the bug:**

So I installed k3s on my Raspberry pi 4 using the command on the website (curl -sfL https://get.k3s.io | sh -)
It gives the error that I should enable cgroup memory in /boot/cmdline.txt
I tried enabling it in cmdline.txt but it still does not work
I also tried looking at other people's issues but most of them use the version from 18.* 
I also tried reinstalling and rebooting but it just won't stop giving the error.
I also tried editing /boot/firmware/nobtcmd.txt and /boot/firmware/nobtmcd.txt  but it still wont work

**Steps To Reproduce:**
- Installed K3s: 
- run sudo k3s server &

**Expected behaviour:**
Should Just Show the node and be ready to join a cluster
**Actual behaviour:**
Gives the same error even if I change multiple files

**Comment by Amazeryogo** [comment]
I also wanted to tell that I tried the same thing on a Raspberry Pi 3 2 with Debian/Raspbian Installed using the following steps

`$curl -sfL https://get.k3s.io | sh - `
` $ micro /boot/cmdline.txt #basically adding cgroup_memory=1 cgroup_enable=memory`
` $ sudo reboot`

And it starts working..

**Comment by brandond** [comment]
On Ubuntu you should put the options in the LINUX_KERNEL_CMDLINE variable in `/etc/default/flash-kernel`.

**Comment by VladoPortos** [comment]
Look here, I have 9 rpi 4 with ubuntu 20.10 working, and whole steps here: https://rpi4cluster.com/

```
ubuntu@control01:~$ grep 'Name\|VERSION' /etc/os-release
VERSION="20.10 (Groovy Gorilla)"
VERSION_ID="20.10"
VERSION_CODENAME=groovy

root@control01:/home/ubuntu# kubectl get nodes
NAME        STATUS   ROLES                       AGE     VERSION
control01   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
control02   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
control03   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
cube01      Ready    worker                      2d23h   v1.20.2+k3s1
cube02      Ready    worker                      2d23h   v1.20.2+k3s1
cube03      Ready    worker                      2d23h   v1.20.2+k3s1
cube04      Ready    worker                      2d23h   v1.20.2+k3s1
cube05      Ready    worker                      2d23h   v1.20.2+k3s1
cube06      Ready    worker                      2d23h   v1.20.2+k3s1
```

**Comment by Amazeryogo** [comment]
> On Ubuntu you should put the options in the LINUX_KERNEL_CMDLINE variable in `/etc/default/flash-kernel` and run flash-kernel to sync the settings into `/boot/firmware/cmdline.txt`

Ok, I'll try this...

**Comment by Amazeryogo** [comment]
> Look here, I have 9 rpi 4 with ubuntu 20.10 working, and whole steps here: https://rpi4cluster.com/
> 
> ```
> ubuntu@control01:~$ grep -w 'NAME\|VERSION' /etc/os-release 
> NAME="Ubuntu"
> VERSION="20.10 (Groovy Gorilla)"
> 
> root@control01:/home/ubuntu# kubectl get nodes
> NAME        STATUS   ROLES                       AGE     VERSION
> control01   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
> control02   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
> control03   Ready    control-plane,etcd,master   2d23h   v1.20.2+k3s1
> cube01      Ready    worker                      2d23h   v1.20.2+k3s1
> cube02      Ready    worker                      2d23h   v1.20.2+k3s1
> cube03      Ready    worker                      2d23h   v1.20.2+k3s1
> cube04      Ready    worker                      2d23h   v1.20.2+k3s1
> cube05      Ready    worker                      2d23h   v1.20.2+k3s1
> cube06      Ready    worker                      2d23h   v1.20.2+k3s1
> ```

I'll try this too

**Comment by Amazeryogo** [comment]
> boot/firmware/cmdline.txt

wdym by syncing?

**Comment by Amazeryogo** [comment]
I tinkered on my own and did this:

I modified `/boot/firmware/config.txt` and added cmdline as nobtcmd.txt
Next, I opened `boot/firmware/nobtcmd.txt` and added the lines `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`
next reboot.
And it starts working, 
Thanks, @brandond  and @VladoPortos
