### ISSUE TITLE
Consider including the snapshot controller + related resources as part of k3s

### ISSUE THREAD

**Issue by joshimoo** [k3s-io/k3s#2865]
**Is your feature request related to a problem? Please describe.**
Now that volume snapshots are GA in k8s, it would be nice if k3s can make the the crds + snapshot controller + validation webhook available as part of it's installation.
https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/#how-to-deploy-volume-snapshots

**Describe the solution you'd like**
Consider shipping the snapshot crds + controller + validation webhook as part of k3s/rke.
https://github.com/kubernetes-csi/external-snapshotter#validating-webhook

**Describe alternatives you've considered**
Longhorn currently asks the users to ensure availability of these components, since they are global and based on k8s documentation the responsibility of the distribution to make them available.

**Additional context**
https://github.com/kubernetes-csi/external-snapshotter#usage
https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/#how-to-deploy-volume-snapshots
https://github.com/kubernetes-csi/external-snapshotter#overview

I left some comments on why longhorn isn't switching to v1 just yet below:
https://github.com/longhorn/longhorn/issues/2214#issuecomment-768172972

**Comment by remkolems** [comment]
+1 for this request! (I don't know if we can we vote). Longhorn + K3s + Rancher: ideal combination

**Comment by fapatel1** [comment]
Moved to backlog per @cjellick until we hear explicit requests from Product Management

**Comment by ieugen** [comment]
I would also love to see this included with k3s or be easy to install. 

You can manually install the snapshotter: https://github.com/kubernetes-csi/external-snapshotter#readme .
Recomendation is to upgrade to k8s 1.20 so the API version is stable.

**Comment by sqqqrly** [comment]
I would love for this to be included or easy to install.  I am working on a CSI driver and have to manually add this to test in k3s. Regardless, K3s is ideal for my test case.  

I am currently managing the snapshot-controller myself by including it in my helm chart's templates/.   I think I will create a separate chart for this controller.

```
NAME                            READY   STATUS    RESTARTS   AGE
pod/bar-snapshot-controller-0   1/1     Running   0          131m
pod/bar-node-xwnf8              2/2     Running   0          131m
pod/bar-driver-0                5/5     Running   0          131m```

**Comment by sqqqrly** [comment]
I have a simple Helm chart to deploy a snapshot-controller.

**Comment by brandond** [comment]
Yeah, the fact that most K3s users don't use CSI storage drivers, and it's easy to deploy standalone if you need it, are the biggest reasons that have prevented us from taking action on this.

**Comment by sqqqrly** [comment]
Is the fact that CSI is not included documented somewhere?   Wondering what else is missing that I should be aware of.

**Comment by joshimoo** [comment]
@sqqqrly just to clarify csi support is available in k3s as well as by default k3s ships with the local path provisioner which utilizes the csi support. It's just that at the moment the csi snapshot support requires deployment of the snapshot resource + controller independently from the default k3s installation.

**Comment by LarsBingBong** [comment]
This is interesting. Cool that it's done. How about CSI's e.g. the Longhorn one. That supports a specific version of the snapshot-controller? See > https://longhorn.io/docs/1.4.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/#if-your-kubernetes-distribution-does-not-bundle-the-snapshot-controller

Yeah I see that the version by default out of the box with K3s is too new > https://github.com/rancher/image-mirror/pull/312/files/10e7775ed0faf476aab445f59451f1e71b83baec#diff-fc8680832ee99f26da6bdab27ee40807b32fefa3dbe930e0eb19ff8c1f949bff

---

But, cool. I see that the snapshot-controller can be disabled. Hmm I guess that's the way forward then. When we get to v1.26.1+k3s1.

**Comment by brandond** [comment]
copying my comment from the closed PR:
> We've decided not to do this, in favor of covering use of the [piraeusdatastore](https://github.com/piraeusdatastore/helm-charts/tree/main/charts/) chart in the docs. I'll open a new ADR to cover this decision.

**Comment by LarsBingBong** [comment]
I overlooked that. Thank you for pointing me to it @brandond ... good stuff.

**Comment by jamesharr** [comment]
@brandond I was looking around trying to find the ADR you mentioned in hopes I might find the reasoning for not including the snapshot controller and couldn't find it. Any chance you could post a link here for others and/or share the reasoning?

My best guess is that either the feature isn't as useful as it initially seems and/or that it's excluded so resource constrained systems, but I'd like to hear the real reasoning behind it.

**Comment by brandond** [comment]
It's the closed/rejected PR linked up above.

**Comment by jamesharr** [comment]
So I see that the PR to include it is rejected, and I see that there's a way to install CSI snapshots externally, but I'm still not getting the reasoning for the decision to not include it as part of k3s. I'm willing to accept that fact, but I just didn't see the reasoning why. There were a few reasons thrown out there in the tickets, but they didn't seem like enough on their own to really decide to not include a feature.

**Comment by jamesharr** [comment]
Ty for clarifying. We're debating in our team whether we need PVC Snapshotting

Right now we're using Longhorn which provides backups and snapshots via its own mechanisms, but we have some data workloads that do their own Snapshotting and might benefit from Local only NVMe storage, possibly provided by TopoLVM. The caveat is that we still need backups for local volumes and I'm trying figuring out if we'll need PVC Snapshots to get those backups.

I haven't figured it out by yet, but I suspect things like Velero would need it, which I'm eyeing because we need manifest backups anyway, which longhorn doesn't provide

**Comment by brandond** [comment]
If you want to use the stuff we repackage for RKE2, you can just apply this or drop it in the manifests dir on a server node:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-snapshot-controller
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-snapshot-controller
---    
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-snapshot-controller-crd
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-snapshot-controller-crd
--- 
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-snapshot-validation-webhook
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-snapshot-validation-webhook

```

**Comment by LarsBingBong** [comment]
@jamesharr you're welcome to reach out to me on the RancherLabs Slack Community - I'm Lars Bingchong over there. 

The above, if you're interested as we're running Longhorn and Velero for backup. We backup to a MinIO vm-cluster. And so far, for more than 1,5 years, it's worked very well.

Have a great day.
