### ISSUE TITLE
Replacing k3s tokens with k8s bootstrap tokens

### ISSUE THREAD

**Issue by chris13524** [k3s-io/k3s#2866]
The main issue with k3s tokens is that they are a global shared credential which makes revoking access in the event of physical agent node compromise impossible. In the event of token compromise, it is difficult to rotate the token without cluster downtime and re-configuring every node to use the new token.

The main benefit I've observed with k3s tokens is their convenience to add new nodes to the cluster. However, k8s now supports [bootstrap tokens](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) which make joining the cluster easy. By default they do not expire which is useful for checking into a secret manager (but personally I would enable expiry). I do not see any benefits k3s agent tokens have over k8s bootstrap tokens (other than their UX), but please clarify if there are other benefits k3s agent tokens have that I am not considering.

The main issue with completely removing k3s tokens is that server nodes use these to connect to each other under the embedded DB HA setup. Perhaps server nodes would have to continue using tokens while worker nodes could support/switch to using k8s bootstrap tokens.

Replacing k3s tokens with k8s native functionality would further enable interoperability with a regular k8s control plane: https://github.com/k3s-io/k3s/issues/1916

/ref https://github.com/k3s-io/k3s/issues/2645

**Comment by brandond** [comment]
We are talking internally about reworking join tokens, but in reality they will probably not align with kubeadm's join tokens. The desire was to have a UX similar to docker swarm or microk8s, where you can use pre-generate the tokens that can be used to create an entire cluster ahead of time, without having to bring the cluster up first and then provision tokens, update your automation to reference those tokens, etc.

One thing you might have missed about the K3s tokens is that they also currently serve to bootstrap a root of trust - if you pass a full token (with K10 prefix, as found in the node token file) that actually includes a hash of the cluster's CA cert. This is checked against the CA cert of the cluster being joined, to confirm that you're joining the intended cluster, and that the host you are communicating with uses a cert signed by that cluster CA.

**Comment by ShadowJonathan** [comment]
@stale no

**Comment by ShadowJonathan** [comment]
@brandond could this be re-opened? It's still applicable
