### ISSUE TITLE
Configure CoreDNS to be more resilient to multi-nic and multi-nameserver (per nic) setups

### ISSUE THREAD

**Issue by bentastic27** [k3s-io/k3s#2870]
**Is your feature request related to a problem? Please describe.**

Some edge users have setups where the nodes have multiple nic types. An example I hit was where they had connections from multiple providers and each nic having its own set of nameservers (set on the nic via netplan yaml). There are times where a connection via one nic goes down, but CoreDNS was relying on that nic's DNS configuration. Their resolution ultimately was to reboot the node.

**Describe the solution you'd like**

The user ended up setting up an intermediary network service that handles the DNS forwarding. They set the /etc/resolv.conf to point to that. This ultimately fixed this issue for them.

Perhaps we could include something like that or set up the Corefile a little differently to do something similar.

**Comment by brandond** [comment]
K3s just uses the system's resolv.conf. If that points at a DNS server on a specific interface, that's what we'll use. If you want to set up a special resolv.conf for K3s that points to a DNS server that is reachable via multiple interfaces, you can do so using the `--resolv-conf` flag:
https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#networking

**Comment by bentastic27** [comment]
@brandond Interesting. That almost doesn't look to be the case for the user I'm working with:

> Ubuntu DNS (systemd-resolve) appears to be able to adapt to network changes which have different DNS nameservers; but coreDNS does not, which is really a bit odd, given that the host /etc/resolve.conf has the nameserver of 127.0.0.53 which is the systemd-resolve service.   So, when the network switches, what is causing coreDNS lookups to fail when Ubuntu lookups are working?  Is coreDNS caching nameservers or something else?

**Comment by brandond** [comment]
Are you sure that the failure was due to coredns not being able to reach a specific name server? If you're using a local resolver (such as systemd-resolved) as the upstream for coredns then that should work fine. That said, I've frequently been irritated by systemd-resolved doing things I don't want it to do (such as caching lookups from an old network when switching networks), so it may in fact be causing more problems than it's solving.

**Comment by bentastic27** [comment]
@brandond I am actually wondering if this is a weird gotchya when the host's resolv.conf is pointed to resolved (?) or similar. It seems to pull the nameservers off of resolved's configs or... something instead of pointing to 127.0.0.53:

```
root@ben-rancheragent-all-2:~# docker cp acfe56f7bf93:/etc/resolv.conf ./

root@ben-rancheragent-all-2:~# cat resolv.conf
nameserver 67.207.67.3
nameserver 67.207.67.2

root@ben-rancheragent-all-2:~# cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0
```

This also doesn't seem to adapt when I take the nic down that has those nameservers set, which I didn't expect it to, but I tested that anyways. A possible is to set the pod to use that IP instead. It works for me, but I'm having the customer test that for their use case.

```
spec:
  template:
    spec:
      dnsConfig:
        nameservers:
        - 127.0.0.53
```
