### ISSUE TITLE
kube-router network policy controller needs to be updated

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2876]
**Environmental Info:**
K3s Version: 
K3s v1.20.2

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
N/A

**Describe the bug:**
Our fork of the kube-router network policy controller hasn't been sync'd with upstream since @erikwilson added it back in da3a7c6bbc47ad0b186249631680ee0c0b7d0e35.  There have been some nice/important fixes since then:
cloudnativelabs/kube-router#807
cloudnativelabs/kube-router#856
cloudnativelabs/kube-router#902
cloudnativelabs/kube-router#917
cloudnativelabs/kube-router#931
cloudnativelabs/kube-router#992
cloudnativelabs/kube-router#1001
cloudnativelabs/kube-router#1007

**Steps To Reproduce:**
Run normal test suite

**Expected behavior:**
NPC is updated

**Actual behavior:**
NPC is old

**Additional context / logs:**

**Comment by rancher-max** [comment]
- Validated standard regression tests pass with the updated kube-router network policy controller, using commit: `6e768c301e77738ffd69934363aa0479c4a516d6`
