### ISSUE TITLE
How to configure apiserver parameters

### ISSUE THREAD

**Issue by wxq851685279** [k3s-io/k3s#2880]
For example --feature-gates mapStringBool
[https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

**Comment by brandond** [comment]
`--kube-apiserver-arg=feature-gates=MixedProtocolLBService=true`

https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#customized-flags

**Comment by wxq851685279** [comment]
Thank you
