### ISSUE TITLE
cAdvisor stops updating container_cpu_usage_seconds_total

### ISSUE THREAD

**Issue by mnorrsken** [k3s-io/k3s#2881]
**Environmental Info:**
K3s Version: 
```
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5
```

Node(s) CPU architecture, OS, and Version: 
`Linux glados 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

Cluster Configuration:
single master

**Describe the bug:**
After some time or if something happens cAdvisor stops reporting CPU usage, for example:
`kubectl get --raw /api/v1/nodes/glados/proxy/metrics/cadvisor | grep elasticsearch-master-0 | grep container_cpu_usage_seconds_total`
returns the correct metric but it never changes
 
**Steps To Reproduce:**
- Installed K3s: 
`curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.20 sh -s - --write-kubeconfig-mode 640 --disable local-storage --disable servicelb --disable traefik --kubelet-arg containerd=/run/k3s/containerd/containerd.sock`

This issue is hard to reproduce because I'm not sure whats happening, I think it happens after for example doing maintenance work like upgrading k3s... or pulling network cables etc. I notice on my grafana dashboards that the CPU usage only updates for a small number of containers. The only way I'm getting this working again is to reboot the node, a restart of k3s service doesn't work.

This also happens on my raspberry pi cluster. I can get this working by draining/rebooting/uncordon the nodes one by one.

**Expected behavior:**
cAdvisor container_cpu_usage_seconds_total metric works even after temporary "outages" (planned and unplanned)

**Actual behavior:**
cAdvisor container_cpu_usage_seconds_total metric seems to stop updating and "freezes" at one value.

**Additional context / logs:**
I will provide more info when this happens again

**Comment by mnorrsken** [comment]
After some log checking, this seems to coincide with a "service k3s restart", and a lot of log lines like this:
```
k3s.service: Found left-over process 6577 (postgres_export) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

**Comment by brandond** [comment]
Current 1.20 releases have an issue with cadvisor stats that has been fixed on master. Can you try with a recent commit from master? If that does not resolve it, there are some cadvisor fixes from upstream that will get pulled into the next patch release.

**Comment by brandond** [comment]
I believe this is a duplicate of #2831

**Comment by mnorrsken** [comment]
> I believe this is a duplicate of #2831

No not really. I’m already using the workaround. What happens in my case is that something makes a lot of my container metrics disappear. For example I can be running a heavy elastic instance still the highest cpu usage is from traefik container or something reporting 35milicores.

Ive not tried the master branch yet, however considering that I cant seem to reproduce this behavior easily I will close the issue.
