### ISSUE TITLE
Upgrade local-path-storage to v0.0.19

### ISSUE THREAD

**Issue by mbarlow** [k3s-io/k3s#2883]
https://github.com/k3s-io/k3s/blob/c5aad1b5ed4e877eb7ed40f7c5910a83216f983c/manifests/local-storage.yaml#L66

looks like v0.0.14 is currently used. 

latest release is v0.0.19

**Comment by brandond** [comment]
Yes, it hasn't been bumped in a bit. Are you running into any issues at the moment, or are just looking to see it updated?

**Comment by mbarlow** [comment]
I've recently been having some intermittent issues with volume provisioning. Just started investigating and saw a few releases have happened since v0.0.14.

**Comment by rancher-max** [comment]
#### Validated on commit ``

- Ensured using v0.0.19
```
deployment.apps/local-path-provisioner   1/1     1            1           71m   local-path-provisioner   rancher/local-path-provisioner:v0.0.19   app=local-path-provisioner
```
- Volumes continue to work as expected
