### ISSUE TITLE
[QA] Certify CENTOS/RHEL 8.3

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2884]
With both K3s and RKE2, certify they function correctly on CENTOS or RHEL 8.3.
Run standard tests, conformance, upgrades, etc.

**Comment by ShylajaDevadiga** [comment]
Validation complete on k3s and rke2 based on our validation matrix with selinux enforced mode
On k3s

- Conformance test have passed
- Functionality test on imported k3s cluster
- Upgrade tests with workloads have passed
- k3s as local management cluster has passed
- Installation with docker CRI was successful

On rke2

- Conformance test have passed
- Functionality test on imported rke2 cluster
- Upgrade tests with workloads have passed
- rke2 as local management cluster, rancher pods do not crashloop on rke2 version v1.18.15+rke2r1 but fails on v1.19.7+rke2r1. Issue is tracked here https://github.com/rancher/rke2/issues/690 and it is not related to rhel/centos 8.3

```
$ rke2 -v
rke2 version v1.18.15+rke2r1 (44a0b3f1821709c882dcb0471f2eb8aa41e2206d)
go version go1.13.15b4
$ kubectl get pods -n cattle-system
NAME                               READY   STATUS      RESTARTS   AGE
helm-operation-5869k               0/2     Completed   0          14m
helm-operation-6c9cp               0/2     Completed   0          14m
helm-operation-d6f7r               0/2     Completed   0          14m
helm-operation-gk5tb               0/2     Completed   0          14m
helm-operation-xdwn8               0/2     Completed   0          12m
helm-operation-zqvbv               0/2     Completed   0          13m
rancher-9597c7bcb-rrfcz            1/1     Running     0          16m
rancher-9597c7bcb-vdfkg            1/1     Running     0          16m
rancher-9597c7bcb-vpx9h            1/1     Running     0          16m
rancher-webhook-798c5599d9-rd5cc   1/1     Running     0          14m
```
