### ISSUE TITLE
k3s on SLE Micro with SELinux Enabled

### ISSUE THREAD

**Issue by abonillabeeche** [k3s-io/k3s#2889]
**Environmental Info:**
K3s Version: 
N/A

Node(s) CPU architecture, OS, and Version: 
SLE Micro 5.0 Linux microos-1 5.10.9-1-default #1 SMP Wed Jan 20 07:26:11 UTC 2021 (b7732a5) x86_64 x86_64 x86_64 GNU/Linux
Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)

Cluster Configuration:
Individual node

**Describe the bug:**
Trying to install k3s while SLE Micro has SELinux enabled errors with

microos-1:~ # curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.2+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[ERROR]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux selinux-policy-base
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm 

**Steps To Reproduce:**
* Install SLE Micro
* Enable SELinux 
* ~# transactional-update setup-selinux
* reboot
* Try installing k3s via script

- Installed K3s: 

**Expected behavior:**
Successful installation 

**Actual behavior:**
[ERROR]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux selinux-policy-base
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm 

**Additional context / logs:**

**Comment by brandond** [comment]
We assume that yum/rpm based distributions have selinux packages equivalent to those provided by RHEL/CentOS. If you are using an unsupported distribution but have installed the appropriate selinux packages, you can disable the selinux checks in the install script by setting INSTALL_K3S_SELINUX_WARN and INSTALL_K3S_SKIP_SELINUX_RPM variables to true.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga as we beginning taking a look at SLE Micro 5.0, let's see if we can reproduce this issue (I imagine we will as it seems straightforward).

**Comment by dweomer** [comment]
sle-micro 5.1 should at least work now via #4331, #4398, and #4402

**Comment by cwayne18** [comment]
@rancher-max we should be able to close this out, right/
