### ISSUE TITLE
How to disable seccomp?

### ISSUE THREAD

**Issue by JulianZhang** [k3s-io/k3s#2890]
K3s Version: 

```
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5
```

install with command :

`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable-cloud-controller --disable-network-policy --disable traefik" sh -s 
`

run k3s check-config :
```
....
Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: missing
....

```
All pod blocked at ContainerCreating status.

```
kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   local-path-provisioner-7c458769fb-fzc7z   0/1     ContainerCreating   0          2d3h
kube-system   coredns-854c77959c-5sm6p                  0/1     ContainerCreating   0          2d3h
kube-system   metrics-server-86cbb8457f-flnw7           0/1     ContainerCreating   0          147m
```

describe pod get event as blow:

```
Events:
  Type     Reason                  Age                     From     Message
  ----     ------                  ----                    ----     -------
  Warning  FailedCreatePodSandBox  2m55s (x659 over 148m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to generate sanbdox container spec options: failed to generate seccomp spec opts: seccomp is not supported
```

In the same Environmental the 1.17 version will be ok.

`curl -sfL https://get.k3s.io \| INSTALL_K3S_EXEC="server --disable-cloud-controller --disable-network-policy --disable traefik" INSTALL_K3S_VERSION="v1.17.17+k3s1" sh -s -`

**Comment by brandond** [comment]
I have not actually encountered a modern kernel that doesn't offer seccomp support. What are you running this on?

**Comment by JulianZhang** [comment]
Dear @brandond 

I'm try to run k3s on our arm chips, the OS is base on ubuntu 16.04 , the "XX.." is our internal SN.

`Linux XXXXXXX #204 SMP PREEMPT Thu Jul 9 14:43:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux`

If k3s can't disable seccomp by config, I will try to install seccomp.

**Comment by brandond** [comment]
You've redacted the entire kernel version? If it's a custom build, do you have the ability to enable seccomp?

**Comment by dweomer** [comment]
Looks like seccomp is just assumed in containerd/cri: https://github.com/k3s-io/cri/blob/k3s-release/1.4/pkg/server/sandbox_run_unix.go#L164

This is our fork but it matches upstream I do believe.

**Comment by brandond** [comment]
It appears to try to detect whether or not seccomp is supported on your kernel:
https://github.com/k3s-io/cri/blob/k3s-release/1.4/pkg/seccomp/seccomp_linux.go#L43

@JulianZhang can you share more information about your kernel version and which seccomp modules if any are enabled? What is the output from `grep Seccomp /proc/self/status` ?

**Comment by JulianZhang** [comment]
@brandond  , the blow the /proc/self/status in my chips, I can;t find seccomp in it.

```
cat /proc/self/status
Name:	cat
State:	R (running)
Tgid:	17154
Ngid:	0
Pid:	17154
PPid:	26180
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	256
Groups:	0 
NStgid:	17154
NSpid:	17154
NSpgid:	17154
NSsid:	26180
VmPeak:	    5352 kB
VmSize:	    5352 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	     412 kB
VmRSS:	     412 kB
VmData:	     300 kB
VmStk:	     132 kB
VmExe:	      28 kB
VmLib:	    1392 kB
VmPTE:	      28 kB
VmPMD:	      16 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	1
SigQ:	0/7445
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000000000000
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Cpus_allowed:	f
Cpus_allowed_list:	0-3
Mems_allowed:	1
Mems_allowed_list:	0
voluntary_ctxt_switches:	1
nonvoluntary_ctxt_switches:	1
```

**Comment by brandond** [comment]
Thanks. Can you provide any of the other requested info?

**Comment by JulianZhang** [comment]
@brandond  I had try to run the flowing test code in my chips, it look like seccomp shouled not be run.

```
go run main.go 
DEBU[0000] err is :<nil>                                
DEBU[0000] status is :map[CapAmb:	0000000000000000 CapBnd:	0000003fffffffff CapEff:	0000003fffffffff CapInh:	0000000000000000 CapPrm:	0000003fffffffff Cpus_allowed:	f Cpus_allowed_list:	0-3 FDSize:	64 Gid:	0	0	0	0 Groups:	0  HugetlbPages:	       0 kB Mems_allowed:	1 Mems_allowed_list:	0 NSpgid:	8293 NSpid:	8347 NSsid:	25147 NStgid:	8347 Name:	main Ngid:	0 PPid:	8293 Pid:	8347 ShdPnd:	0000000000000000 SigBlk:	0000000000000000 SigCgt:	fffffffe7fc1feff SigIgn:	0000000000000000 SigPnd:	0000000000000000 SigQ:	0/7445 State:	R (running) Tgid:	8347 Threads:	5 TracerPid:	0 Uid:	0	0	0	0 VmData:	  101188 kB VmExe:	     660 kB VmHWM:	    1476 kB VmLck:	       0 kB VmLib:	       0 kB VmPMD:	      16 kB VmPTE:	      28 kB VmPeak:	  102948 kB VmPin:	       0 kB VmRSS:	    1476 kB VmSize:	  102948 kB VmStk:	     132 kB VmSwap:	       0 kB nonvoluntary_ctxt_switches:	1 voluntary_ctxt_switches:	1] 
DEBU[0000] s["Seccomp"] is :                            
DEBU[0000] false   
```

```
 cat main.go
package main

import (
        "bufio"
        "os"
        "strings"
        log "github.com/sirupsen/logrus"

        "golang.org/x/sys/unix"
)


func IsEnabled() bool {
        // Try to read from /proc/self/status for kernels > 3.8
		s, err := parseStatusFile("/proc/self/status")
		log.Debug("err is :" , err)
		log.Debug("status is :" , s)
        if err != nil {
                // Check if Seccomp is supported, via CONFIG_SECCOMP.
                if err := unix.Prctl(unix.PR_GET_SECCOMP, 0, 0, 0, 0); err != unix.EINVAL {
                        // Make sure the kernel has CONFIG_SECCOMP_FILTER.
                        if err := unix.Prctl(unix.PR_SET_SECCOMP, unix.SECCOMP_MODE_FILTER, 0, 0, 0); err != unix.EINVAL {
                                
                                   return true
                        }
                }
                return false
        }
		_, ok := s["Seccomp"]
		log.Debug("s[\"Seccomp\"] is :" , s["Seccomp"])
        return ok
}

// parseStatusFile is from https://github.com/opencontainers/runc/blob/v1.0.0-rc91/libcontainer/seccomp/seccomp_linux.go#L243-L268
func parseStatusFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	s := bufio.NewScanner(f)
	status := make(map[string]string)

	for s.Scan() {
		text := s.Text()
		parts := strings.Split(text, ":")

		if len(parts) <= 1 {
			continue
		}

		status[parts[0]] = parts[1]
	}
	if err := s.Err(); err != nil {
		return nil, err
	}

	return status, nil
}

func main() {
	log.SetLevel(log.DebugLevel)
	f:= IsEnabled()
	log.Debug(f)
}

```

**Comment by brandond** [comment]
Yes, that was my analysis from looking at the code. I don't see why it's taking the path that it's taking on your device.

**Comment by brandond** [comment]
Would you be able to test with a CI build? 

`curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=37db7d11a1e8b0d66ccc236789b2b2ffb227de12 INSTALL_K3S_EXEC="server --disable-cloud-controller --disable-network-policy --disable traefik" sh -s`

**Comment by JulianZhang** [comment]
@brandond  in 1.20.x version, pod will get event as blow 

```
Events:
  Type     Reason                  Age                   From     Message
  ----     ------                  ----                  ----     -------
  Warning  FailedCreatePodSandBox  2m8s (x434 over 97m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to generate sanbdox container spec options: failed to generate seccomp spec opts: seccomp is not supported

```

In CI BUILD, pod will get event as blow, pod still can't been created.

```
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               31s   default-scheduler  Successfully assigned kube-system/metrics-server-86cbb8457f-fhncq to ubuntu1
  Warning  FailedCreatePodSandBox  11s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to generate sanbdox container spec options: failed to generate seccomp spec opts: seccomp is not supported
```

**Comment by mazzy89** [comment]
I'm interested here as well. I'm trying to run k3s in an OS where seccomp is not present. Hence pods can't start. Any solution at the horizon?

**Comment by dweomer** [comment]
As @brandond has commented at https://github.com/k3s-io/k3s/issues/2890#issuecomment-772740726, this seems to be failing a check in containerd which is enforcing that a non-nil `container.securityContext.seccompProfile` must have `type` == `unconfined` for unprivileged pods on systems without seccomp:

See https://github.com/containerd/containerd/blob/release/1.5/pkg/cri/server/container_create_linux.go#L427-L434
```golang
	if !seccompEnabled {
		if sp != nil {
			if sp.ProfileType != runtime.SecurityProfile_Unconfined {
				return nil, errors.New("seccomp is not supported")
			}
		}
		return nil, nil
	}
```

With similar for 1.4, see https://github.com/containerd/cri/blob/release/1.4/pkg/server/container_create_unix.go#L342-L347
```golang
	if !seccompEnabled {
		if seccompProf != "" && seccompProf != unconfinedProfile {
			return nil, errors.New("seccomp is not supported")
		}
		return nil, nil
	}
```

@mazzy89 which pods are failing for you? Any and all?

**Comment by mazzy89** [comment]
All the pods are failing. I cannot bootstrap the cluster.

**Comment by mazzy89** [comment]
I've also played with the containerd runtime config. I've tried to set the parameter `unset_seccomp_profile` first to `nil` then to `unconfined` but it did not work.

**Comment by dweomer** [comment]
> All the pods are failing. I cannot bootstrap the cluster.

@mazzy89 Please open a separate issue with details that can help us reproduce the error state that you are encountering. See https://github.com/k3s-io/k3s/issues/new?assignees=&labels=&template=bug_report.md&title=

Additionally, it may help to provide detail of a pod that is failing, e.g.:
```shell
kubectl get -n kube-system deploy/coredns -o yaml
```
... along with some events detail:
```shell
kubectl get events -A
```

**Comment by mazzy89** [comment]
@dweomer no need to open another issue. The issue I have is exactly explained by you here https://github.com/k3s-io/k3s/issues/2890#issuecomment-912886342

**Comment by asaaki** [comment]
Today I wanted to test k3d with an arm64 k3s image, and also ran into the same issue as described here.
As mentioned before, for me also all pods are failing to create due to this seccomp problem.

Image I tried to use: `rancher/k3s:v1.22.3-k3s1-arm64`
Since lots of older releases are not even available through docker hub I cannot even fall back to a working version.

**Comment by zhangzq644** [comment]
Under my conditions, when installing k3s, use `INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--node-name=master --docker"` /path/to/your/k3s-install.sh. The key parameter is `--docker`, which means containerd is no longer used, and it switches to Docker, and than just allowing you to schedule Pods.
