### ISSUE TITLE
k3s-uninstall.sh does not clean up user-provided CNI configuration

### ISSUE THREAD

**Issue by kimma** [k3s-io/k3s#2898]
**Environmental Info:**
K3s Version: v1.20.2+k3s1 (1d4adb03)

Node(s) CPU architecture, OS, and Version: Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

N/A

**Describe the bug:**

When running the k3s-uninstall.sh script CNI configuration is not cleaned up, and a new install on K3S will rely on old CNI config.

**Steps To Reproduce:**

- Installed K3s: using install script, latest stable
- Start K3S and set up cluster without networking (flannel-backend: none, disable: servicelb,traefik)
- Confirm no network (node is in NotReady state)
- Install CNI (Calico in this case)
- Confirm network up (Node is in Ready state)
- Stop K3S, run k3s-killall.sh and k3s-uninstall.sh
- Install K3S again with install script
- Start up K3S, notice that old CNI config is loaded and node goes directly to "Ready" state

**Expected behavior:**

Expect all CNI config to be cleared.
In calico's case this would be:
rm -rf /var/lib/calico /etc/cni /opt/cni

On startup of fresh K3S install expect to see following log line:
Feb 05 14:56:09 har-k3s01 k3s[182743]: E0205 14:56:09.219916  182743 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network>

**Actual behavior:**

CNI config is not cleaned up, nodes are started up with old CNI config, which can be bad if you uninstalled it for a reason.

**Additional context / logs:**

For Calico, it will complain about certificates not being correctly signed, as new k3s install has generated new certificates.

K3S logs following on startup:
Feb 05 14:39:29 har-k3s01 k3s[177496]: E0205 14:39:29.931655  177496 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "903e4004329ab5e02c8c77e2556a638d1993d2190d9851a139a36f52c50f5b3e": error getting ClusterInformation: Get "https://api.k3s.local:6443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority
Feb 05 14:39:29 har-k3s01 k3s[177496]: E0205 14:39:29.931752  177496 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "coredns-854c77959c-bgtq8_kube-system(3517ed12-ce16-46a1-a492-9ecc364c296b)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "903e4004329ab5e02c8c77e2556a638d1993d2190d9851a139a36f52c50f5b3e": error getting ClusterInformation: Get "https://api.k3s.local:6443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority

**Comment by brandond** [comment]
> Start K3S and set up cluster without networking (flannel-backend: none, disable: servicelb,traefik)
> Install CNI (Calico in this case)

If you provide your own CNI plugin, you will need to be responsible for cleaning it up on uninstall as well. I don't think it's reasonable for us to know about and clean up the paths of every user-provided component that someone might possibly install on a node.

**Comment by kimma** [comment]
> > Start K3S and set up cluster without networking (flannel-backend: none, disable: servicelb,traefik)
> > Install CNI (Calico in this case)
> 
> If you provide your own CNI plugin, you will need to be responsible for cleaning it up on uninstall as well. I don't think it's reasonable for us to know about and clean up the paths of every user-provided component that someone might possibly install on a node.

This is of course true, the uninstall script cannot keep track of everything.
However, since it apparently is auto-loading these modules even after a full uninstall, from folders that is not mentioned in the k3s documentation as far as I can see, it would perhaps be an idea that the uninstall script at least informs the user that certain folders will need manual cleaning?
I had no idea that /etc/cni would be autoloaded by K3s, especially since I installed the CNI with a "kubectl apply", not any manual procedures.

**Comment by brandond** [comment]
CNIs usually include daemonset pods that alter configuration and drop files on the host OS, since they are (by their very design) responsible for setting up networking on the host so that containers have a functioning cluster network. There is no way for K3s to know what an arbitrary CNI does or where it does it since it's all handled as part of the CNI plugin manifest and/or the images deployed by the manifest.

Are you saying that you saw errors on a subsequent install when attempting to go back to using Flannel? Or you got errors on a subsequent install when trying to use Calico again, and it found the left-over Canal configuration?

Where did you get the manifest that you applied?

**Comment by kimma** [comment]
> Are you saying that you saw errors on a subsequent install when attempting to go back to using Flannel? Or you got errors on a subsequent install when trying to use Calico again, and it found the left-over Canal configuration?

No, I got the error before even trying to install anything.
I did this several times, uninstalling K3S and any trace of "rancher" or "k3s" in the filesystem.
I use an external Etcd, and this was also wiped on every try to be completely sure that there was no leftover config from previous install.

> Where did you get the manifest that you applied?
https://docs.projectcalico.org/getting-started/kubernetes/k3s/multi-node-install
specifically I used the Operator approach with "tigera-operator.yaml".

As mentioned in the original bug report, I would not expect k3s to load any config other than that specified in the k3s config file, or remove any config file that it automatically loads when the k3s-uninstall script is executed.


k3s config on all nodes is the following (with different node name ofc.):
`datastore-endpoint: "https://10.12.100.11:2379,https://10.12.100.12:2379,https://10.12.100.13:2379"
datastore-cafile: "/etc/certs/ca-bundle.pem"
datastore-certfile: "/etc/certs/etcd.cert.pem"
datastore-keyfile: "/etc/certs/etcd.key.pem"
node-name: "har-k3s01"
cluster-cidr: "10.12.192.0/20"
service-cidr: "10.12.208.0/20"
cluster-dns: "10.12.208.10"
cluster-domain: "k3s.guiltyspark.net"
flannel-backend: "none"
disable: "servicelb,traefik"
disable-kube-proxy: "true"
disable-network-policy: "true"`

**Comment by brandond** [comment]
I'm not seeing a problem here. If I install Calico using your steps and then uninstall K3s, the things created by the Calico calico-node pod are still there, but they don't interfere with the operation of K3s on subsequent installs that do not use Calico:

Install K3s with Calico:
```bash
[root@centos01 ~]# curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_EXEC="server --flannel-backend=none --disable-network-policy --disable=traefik,servicelb --cluster-cidr=192.168.0.0/16" bash -
(...)

[root@centos01 ~]# kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/installations.operator.tigera.io created
customresourcedefinition.apiextensions.k8s.io/tigerastatuses.operator.tigera.io created
namespace/tigera-operator created
podsecuritypolicy.policy/tigera-operator created
serviceaccount/tigera-operator created
clusterrole.rbac.authorization.k8s.io/tigera-operator created
clusterrolebinding.rbac.authorization.k8s.io/tigera-operator created
deployment.apps/tigera-operator created

[root@centos01 ~]# kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
installation.operator.tigera.io/default created

[root@centos01 ~]# kubectl get nodes -o wide
NAME                 STATUS   ROLES                  AGE     VERSION                INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
centos01.lan.khaus   Ready    control-plane,master   4m35s   v1.20.2+k3s-1d85a6a3   10.0.1.137    <none>        CentOS Linux 7 (Core)   5.8.10-1.el7.elrepo.x86_64   containerd://1.4.3-k3s3

[root@centos01 ~]# kubectl get pods -A
NAMESPACE         NAME                                      READY   STATUS    RESTARTS   AGE
tigera-operator   tigera-operator-b6c4bfdd9-d9b5z           1/1     Running   0          3m40s
kube-system       metrics-server-86cbb8457f-mvjl2           1/1     Running   0          4m10s
kube-system       local-path-provisioner-5ff76fc89d-zhd6z   1/1     Running   0          4m10s
calico-system     calico-typha-59bdbf8fd-pcfbh              1/1     Running   0          3m28s
kube-system       coredns-854c77959c-2jc89                  1/1     Running   0          4m10s
calico-system     calico-node-pvz47                         1/1     Running   0          3m28s
calico-system     calico-kube-controllers-cfb4ff54b-nw4cg   1/1     Running   0          3m27s
```

Uninstall and reinstall using default flannel:
```
[root@centos01 ~]# k3s-uninstall.sh
(...)

[root@centos01 ~]# curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_EXEC="server --disable-network-policy --disable=traefik,servicelb" bash -
(...)

[root@centos01 ~]# kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-5ff76fc89d-hr6tw   1/1     Running   0          36s
kube-system   metrics-server-86cbb8457f-wll65           1/1     Running   0          36s
kube-system   coredns-854c77959c-vm226                  1/1     Running   0          36s

[root@centos01 ~]# kubectl get nodes -o wide
NAME                 STATUS   ROLES                  AGE   VERSION                INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
centos01.lan.khaus   Ready    control-plane,master   56s   v1.20.2+k3s-1d85a6a3   10.0.1.137    <none>        CentOS Linux 7 (Core)   5.8.10-1.el7.elrepo.x86_64   containerd://1.4.3-k3s3
[root@centos01 ~]#
```

**Comment by brandond** [comment]
If there is a directory that we are responsible for creating, but leave behind on uninstall, AND read content from on a subsequent install, that is something we should fix. Can you identify what that path is?

**Comment by caroline-suse-rancher** [comment]
Closing as this is an enhancement we currently have in the Backlog
