### ISSUE TITLE
K3s Service CrashLoop After Raspberry Pi 3 Reboot

### ISSUE THREAD

**Issue by simoncaron** [k3s-io/k3s#2903]
**Environmental Info:**
K3s Version: k3s version v1.19.7+k3s1 (5a00e38d)

Node(s) CPU architecture, OS, and Version: Linux rpi3-k8s-master01 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux

Cluster Configuration: Single-node Raspberry Pi 3

**Describe the bug:** After rebooting the Pi, K3s service is crash-looping

**Steps To Reproduce:**

- Install K3s with the following command: 
   `curl -sfL https://get.k3s.io | sh -s - --no-deploy traefik --no-deploy servicelb --node-taint CriticalAddonsOnly=true:NoExecute`
- Check that kube-system pods are up and running with: 
   `kubectl -n kube-system get pods`
- Reboot the Raspberry Pi

**Expected behavior:**
After reboot, K3s restart properly and kube-apiserver is responding properly. 

**Actual behavior:**
After system reboot, k3s service enters a crash-loop, kubectl commands are ending with timeouts.

**Additional context / logs:**
Systemctl Logs: [k3s.log](https://github.com/k3s-io/k3s/files/5936259/k3s.log) Using Raspbian Lite, swap is disabled.

**Comment by brandond** [comment]
Can you install the agnostics package (via apt on raspbian, or using the deb at https://archive.raspberrypi.org/debian/pool/main/a/agnostics/agnostics_0.6_armhf.deb on ubuntu), run `/usr/share/agnostics/sdtest.sh` and post the results?

**Comment by simoncaron** [comment]
Tried with 2 different SD Cards, same install:

#### Sandisk Extreme Plus 16 Gb
```
Run 1
prepare-file;0;0;18935;36
seq-write;0;0;21229;41
rand-4k-write;0;0;2879;719
rand-4k-read;9432;2358;0;0
Sequential write speed 21229 KB/sec (target 10000) - PASS
Random write speed 719 IOPS (target 500) - PASS
Random read speed 2358 IOPS (target 1500) - PASS
```

#### Sandisk Extreme Pro 128Gb
```
Run 1
prepare-file;0;0;21494;41
seq-write;0;0;21305;41
rand-4k-write;0;0;4016;1004
rand-4k-read;8040;2010;0;0
Sequential write speed 21305 KB/sec (target 10000) - PASS
Random write speed 1004 IOPS (target 500) - PASS
Random read speed 2010 IOPS (target 1500) - PASS
```

**Comment by brandond** [comment]
You appear to be missing a bunch of critical RBAC. Did you perhaps reboot it without cleanly shutting down K3s and some of the data in the datastore was lost?

**Comment by simoncaron** [comment]
Does a clean shutdown implies running the k3s-killall.ah script before shutting down the server (or any other node)?

**Comment by brandond** [comment]
Just stopping the k3s service would do it. You don't need to kill all the pods - just getting the database flushed out to disk is the most important part.

**Comment by simoncaron** [comment]
I tried to do a simple `systemctl stop k3s` before starting it again but no luck. I see the same errors about forbidden access to resources in the service logs.

**Comment by simoncaron** [comment]
Awaiting a Pi4 2GB next week. We'll see how it goes... I might also try an older version like 1.17x to see if it behaves similarly.

Took another Pi3 to boot a worker and it's also entering a restart loop after reboot.

**Comment by hgw77** [comment]
same here! I have a Pi3 and 16GB Sandisk Ultra SDCard, I am very interested how the Pi4 will handle the latest version 

`v1.18.15+k3s1` is working but the latest version is ending in crashloop after reboot

**Comment by hgw77** [comment]
I ordered a Raspi4 4GB and tested the latest k3s version and it seems this is working with the same SD Card (new 16GB Sandisk Ultra SDCard) that I used on my Raspi3

**Comment by brandond** [comment]
I would recommend running with a larger SD card, as that gives it more cells to wear-level your writes over. With only 16 GB, you're pretty likely to exceed the rated write count of the device pretty quickly.

**Comment by hgw77** [comment]
ok thank you for the hint, I will use the Raspi only as server so I was thinking 16GB is enough but you are right the logs are written to the SD card. Which size is recomended?

**Comment by brandond** [comment]
They're dirt cheap, get the biggest and fastest you can afford! I usually go for the 64GB Class 10 ones, you can get them for less than 10 bucks.

**Comment by hgw77** [comment]
thank you for the advice, I just installed a SSD 120GB cost arround 24 euro, I guess this is more future proof and I do not need to be affraid that my sdcard will die ;-)
