### ISSUE TITLE
Need to reduce K3s shipped binary size

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2904]
**Is your feature request related to a problem? Please describe.**
We're creeping up on 60MB K3s binaries again, and we're going to be adding more code soon for S3 backups/restore and etcdctl.

**Describe the solution you'd like**
Should take steps to reduce image size. If we can't eliminate anything we should try to compress things more efficiently.

**Describe alternatives you've considered**
Let the binaries keep growing

**Additional context**
From a recent PR build: `k3s binary dist/artifacts/k3s size 58429440 is less than max acceptable size of 61000000 bytes`

**Comment by ShylajaDevadiga** [comment]
Validated using commit k3s version v1.20.2+k3s-5749f66a

Before compression 55M
```
$ k3s -v
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5

$ ls -lh /usr/local/bin/k3s
-rwxr-xr-x 1 root root 55M Feb 17 00:32 /usr/local/bin/k3s
```
After compression 44M
```
$ k3s -v
k3s version v1.20.2+k3s-5749f66a (5749f66a)
go version go1.15.8

$ ls -lh /usr/local/bin/k3s
-rwxr-xr-x 1 root root 44M Feb 16 23:54 /usr/local/bin/k3s
```
