### ISSUE TITLE
x86 32bit support

### ISSUE THREAD

**Issue by rossbeazley** [k3s-io/k3s#2906]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
im running some low power 32bit x86 equipment at home as a router and ideally would like to also use the device as the ingress controller. There is no native support for 32bit x86 aka 386 with k3s however i have had some success building my own binaries using https://github.com/k3s-io/k3s/issues/2075 as a guide. 

this is an event log snippet from describing a failed pod

Events:
  Type     Reason                  Age               From               Message
  ----     ------                  ----              ----               -------
  Normal   Scheduled               <unknown>         default-scheduler  Successfully assigned default/httpd-deployment-cdb8d664c-qf72r to debian
  Warning  FailedCreatePodSandBox  3s (x7 over 89s)  kubelet, debian    Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "docker.io/rancher/pause:3.1": no matching manifest for unknown in the manifest list entries

So now I have a problem deploying pods to the node as the pause container is not available as a 32bit image.

Before I sink several hours into this learning how things work do you have any advice?

Alternatively start supporting 32bit x86 k3s :D

**Comment by brandond** [comment]
As you noticed, there are no 32bit x86 images for most if not all of the components that you would need to actually run a Kubernetes cluster. If you're going to try building this, you'll need to also build images for everything on the airgap images list, plus whatever you want to run on the cluster once it's up.

**Comment by rossbeazley** [comment]
thanks for the pointer, so for example this tarball

https://github.com/k3s-io/k3s/releases/download/v1.17.17%2Bk3s1/k3s-airgap-images-amd64.tar

for the version im running

its certainly something im willing to give a go, faff all else to do at the moment except walk endlessly past closed shops

**Comment by rossbeazley** [comment]
actually, it would just be the images needed for a node so maybe the list is smaller

**Comment by rossbeazley** [comment]
so maybe just rancher/pause and possibly rancher/local-path-provisioner

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/releases/download/v1.20.2%2Bk3s1/k3s-images.txt

**Comment by rossbeazley** [comment]
actually, where is the source for your Pause container?

**Comment by brandond** [comment]
It's just a copy of the upstream pause container image. Not all the images in our docker hub org are built by us, some are just mirrored there so we have control over tags and such.

**Comment by rossbeazley** [comment]
right, makes sense. So for now im using an image published by another dev and have configured k3s to use this by tweaking the unit file

ExecStart=/usr/local/bin/k3s \
    agent \
	'--docker' \
        --pause-image='docker.io/knovus/pause:3.3' \

I know the versions arnt quite matching but things look to be working just now.

I couldnt get the local "airgap" images to work.

I shall look into publishing my own image at some point soon i imagine.

just for completeness in case anyone else is looking to do this i cloned, built and installed all the cni plugins from https://github.com/containernetworking/plugins in order to get the host-local binary for k3s to use.

i guess we can close this issue if you like

thanks for the help
