### ISSUE TITLE
Questions about the high-availability registration method of k3s

### ISSUE THREAD

**Issue by AbelTaylor** [k3s-io/k3s#2907]
hello!
My k3s version is 1.20.2. I used the following high-availability implementation to form a cluster of 3 master nodes, but I am a little curious, that is, there is only one server specified in the k3s-agent.service file on the worker node. When this server goes down, logically, the worker node should lose contact with the cluster. However, in fact, the worker node and other master nodes that are not his server can still maintain the normal cluster status. May I ask, in high When available, how does the worker node still work normally when its server is down?

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Comment by brandond** [comment]
The recommendation from the "HA with external DB" page applies to embedded etcd as well - you should supply a "a fixed registration address that is placed in front of the server nodes to allow agent nodes to register with the cluster". This could be an external load-balancer, DNS alias, etc.

Note that this is only necessary to make registration of new nodes HA, or in case of a complete replacement of all server nodes. Agents use the server address to bootstrap their configuration, but once that is complete they cache a list of servers and load-balance connections between them internally. The list of servers is cached to disk and re-loaded on startup.

**Comment by lkj4** [comment]
> you should supply a "a fixed registration address..."

@brandond You mean when running `k3s ... --server https://<the fixed registration address here?>` right? I did this and my fixed registration is address is the one from one my cloud-native load balancer and now I wonder if this was the right place (since the load balancer just pipes `:6443` traffic).

And when running `kubectl get nodes -o wide` I get the node public IPs in `INTERNAL-IP` and no `EXTERNAL-IP`. Shouldn't the INTERNAL-IP' show the private IPs of the nodes which are all in a private network?

**Comment by brandond** [comment]
The registration address is the endpoint that you point new servers and agents at via the --server CLI flag. Once nodes have joined the clusters, the communicate directly with the servers via their IP addresses.

The Internal and External IPs are determined by the cloud provider, or in the case of the build-in k3s cloud provider, the arguments given to the --node-ip and --node-external-ip CLI flags. If your cloud infrastructure  gives you multiple interfaces, some with private IPs and some with public, you may need to manually configure K3s to tell it what these IPs are as it cannot figure them out on its own.

**Comment by lkj4** [comment]
Good info thx, ...

- with just `--node-ip <private IP of the host executing k3s server/installer>` servers find each other
- with both, the aforementioned flag and `--node-external-ip <public IP of the host executing k3s server/or the installer>` secondary servers hang at `[INFO]  systemd: Starting k3s`

But actually the cluster doesn't need to connect within the cluster with public IPs anyway, so this might be neglectable, or is there any reason to let them advertise also with public IPs?

FWIW, the `--server` registration address is the one of the external load balancer targeting the hosts via their private IPs on `:6443`. 

FWIW2, IDK if this works on any Linux distro but what I did to automate the IP retrieval:

```
...
  --node-ip `hostname -I | sed -En 's/^\S+\s(\S+)\s.*/\1/p'` \
  --node-external-ip `hostname -I | sed -En 's/^(\S+)\s.*/\1/p'`
```

**Comment by btrepp** [comment]
I found myself wondering the same question here.

It seems this is just for initial bootstrapping of nodes. Eg only at registration time, and once registered it will try any control planes it knows about when restarting/rebooting?.

So for most 'home' cases, if you have relatively static servers, it would be fine to specify the first one. As the you won't be dynamically provisioning many nodes there (physical devices are unlikely to spontaneously appear and join the cluster).
This would still be HA once 'installed'?.
