### ISSUE TITLE
Enable using "--etcd-prefix" for reusing external ETCD cluster with multiple tenants/K3S cluster

### ISSUE THREAD

**Issue by BrommD** [k3s-io/k3s#2908]
Hi

do you plan to implement the possibility to reuse an existing external ETCD cluster for multiple tenants/K3S cluster?

This is done by having the embedded Kubernetes use the startup argument "--etcd-prefix <string>", which is used as prefix within ETCD environment to separate the registry tree.

Thanks

Dejan

**Comment by brandond** [comment]
I think this should work fine if you use `--datastore-endpoint=https://X` with `--kube-apiserver-arg=etcd-prefix=foo`. I haven't tried that myself though - reply here if you run into any problems?

**Comment by BrommD** [comment]
Hi,

yes, this works, got this option completely out of my mind. Thx, Dejan
