### ISSUE TITLE
K3s Service CrashLoop After Reboot on armhf

### ISSUE THREAD

**Issue by linsmalldragon** [k3s-io/k3s#2916]
**Environmental Info:**
K3s Version: k3s version v1.20.2+k3s1 (1d4adb03)

Node(s) CPU architecture, OS, and Version: Linux w1 5.3.8-aml-OC-BonusCloud #6 SMP Mon Nov 11 18:32:45 PST 2019 armv7l GNU/Linux

Cluster Configuration:

1master,4workers
**Describe the bug:**

worker status is aways not ready after reboot worker and master

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://get.k3s.io | K3S_URL=https://k1:6443 K3S_TOKEN=TOKENXXX sh -

**Expected behavior:**

worker status ready
**Actual behavior:**

worker status notReady
**Additional context / logs:**

[syslog.txt](https://github.com/k3s-io/k3s/files/5950898/syslog.txt)

**Comment by linsmalldragon** [comment]
after run the script /usr/share/agnostics/sdtest.sh result:

sh /usr/share/agnostics/sdtest.sh
Run 1
prepare-file;0;0;14945;29
seq-write;0;0;13727;26
rand-4k-write;0;0;5685;1421
rand-4k-read;11943;2985;0;0
Sequential write speed 13727 KB/sec (target 10000) - PASS
Random write speed 1421 IOPS (target 500) - PASS
Random read speed 2985 IOPS (target 1500) - PASS

**Comment by brandond** [comment]
Your kernel appears to be missing many critical modules. Can you run `k3s check-config` and verify that you have all the required modules?
```
Feb  9 19:08:02 localhost k3s[1216]: W0209 19:08:02.179764    1216 iptables.go:564] Could not set up iptables canary mangle/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.8-aml-OC-BonusCloud/modules.dep.bin'
Feb  9 19:08:02 localhost k3s[1216]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.3.8-aml-OC-BonusCloud
Feb  9 19:08:02 localhost k3s[1216]: iptables v1.6.0: can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Feb  9 19:08:02 localhost k3s[1216]: Perhaps iptables or your kernel needs to be upgraded.
Feb  9 19:08:02 localhost k3s[1216]: I0209 19:08:02.181693    1216 conntrack.go:103] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
Feb  9 19:08:02 localhost k3s[1216]: F0209 19:08:02.182980    1216 server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: no such file or directory
```

**Comment by linsmalldragon** [comment]
> Your kernel appears to be missing many critical modules. Can you run `k3s check-config` and verify that you have all the required modules?
> 
> ```
> Feb  9 19:08:02 localhost k3s[1216]: W0209 19:08:02.179764    1216 iptables.go:564] Could not set up iptables canary mangle/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.8-aml-OC-BonusCloud/modules.dep.bin'
> Feb  9 19:08:02 localhost k3s[1216]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.3.8-aml-OC-BonusCloud
> Feb  9 19:08:02 localhost k3s[1216]: iptables v1.6.0: can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
> Feb  9 19:08:02 localhost k3s[1216]: Perhaps iptables or your kernel needs to be upgraded.
> Feb  9 19:08:02 localhost k3s[1216]: I0209 19:08:02.181693    1216 conntrack.go:103] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
> Feb  9 19:08:02 localhost k3s[1216]: F0209 19:08:02.182980    1216 server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: no such file or directory
> ```

Thank you brandond.
k3s check-config helps me find the kernel problem.
