### ISSUE TITLE
ship with bundled/embedded stargz snapshotter

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#2918]
**Is your feature request related to a problem? Please describe.**
With the advent of https://github.com/containerd/stargz-snapshotter we should consider bundling it as part of k3s.

**Describe the solution you'd like**
Since we're building containerd we should build this as a native plugin. Otherwise k3s would need to supervise the stargz snapshotter as a separate process prior to spinning up containerd.

**Describe alternatives you've considered**
n/a

**Additional context**
- https://medium.com/nttlabs/startup-containers-in-lightning-speed-with-lazy-image-distribution-on-containerd-243d94522361

**Comment by AkihiroSuda** [comment]
cc @ktock

**Comment by brandond** [comment]
What's the lift on publishing stargz-compatible image layers? Is there an easy way to pull them in place of the default images, or do you need to specify an alternative image?

**Comment by ktock** [comment]
eStargz-converted image needs to be specified instead of the original image. But this image is backward-compatible to OCI so still pullable from lazy-pulling-agnostic nodes.

If you don't want to change the image tag config, I haven't tried but converting images and storing them to the mirrored registry with the same tags might work?

**Comment by AkihiroSuda** [comment]
[nerdctl](https://github.com/AkihiroSuda/nerdctl) provides Docker-like CLI for converting Docker images into eStargz images, so maybe it's also worth including?

```console
$ nerdctl build -t example.com/foo .
$ nerdctl image convert --estargz --oci example.com/foo example.com/foo:estargz
$ nerdctl push example.com/foo:estargz
```
https://github.com/AkihiroSuda/nerdctl/blob/master/docs/stargz.md

**Comment by AkihiroSuda** [comment]
[The k3c project](https://github.com/rancher/k3c) seems rebooted recently, and I assume it is going to be embedded in k3s. So probably we should port over `nerdctl image convert` to `k3c image convert`.

**Comment by ktock** [comment]
Opened a PR on https://github.com/k3s-io/k3s/pull/2936.

**Comment by ktock** [comment]
Can we move this forward?

**Comment by dweomer** [comment]
We very much appreciate you work on this @ktock and @AkihiroSuda!

**Comment by ktock** [comment]
Thank you all for the review and the discussion!

**Comment by AkihiroSuda** [comment]
@ktock 

:tada:

We need to have docs under https://github.com/rancher/docs/tree/master/content/k3s/latest/en  (https://rancher.com/docs/k3s/latest/en/)

**Comment by ktock** [comment]
We have the docs PR  at https://github.com/rancher/docs/pull/3322 .

**Comment by rancher-max** [comment]
#### Validated using master commit `eda65b19d9893a033c681ab5b0045d7a0e29d6cb`

- Compared the performance between stargz and the default of overlayfs and saw increased performance times when using stargz
- Saw containerd configuration in the config.toml set appropriately
- Ran a modified version of the test included in the PR and saw the images were the remote snapshots
