### ISSUE TITLE
coredns crashloopback issue.plugin/forward: no nameservers found

### ISSUE THREAD

**Issue by rajibul007** [k3s-io/k3s#2919]
**Environmental Info:**
K3s Version:  k3s version v1.19.7+k3s1 (5a00e38d)

Node(s) CPU architecture, OS, and Version: 

root@cxcloudagent:/var/lib/rancher/k3s/agent/images# uname -a
Linux cxcloudagent 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 node

**Describe the bug:**

                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               26m                  default-scheduler  Successfully assigned kube-system/coredns-66c464876b-tc622 to cxcloudagent
  Warning  FailedCreatePodSandBox  26m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "310a39a22b190e492487da98543913daca26db6a81d73d499b9b32babab58502": open /run/flannel/subnet.env: no such file or directory
  Normal   Pulled                  24m (x5 over 25m)    kubelet            Container image "rancher/coredns-coredns:1.6.9" already present on machine
  Normal   Created                 24m (x5 over 25m)    kubelet            Created container coredns
  Normal   Started                 24m (x5 over 25m)    kubelet            Started container coredns
  Warning  BackOff                 16m (x50 over 25m)   kubelet            Back-off restarting failed container
  Normal   Pulled                  10m (x4 over 11m)    kubelet            Container image "rancher/coredns-coredns:1.6.9" already present on machine
  Normal   Created                 10m (x4 over 11m)    kubelet            Created container coredns
  Normal   Started                 10m (x4 over 11m)    kubelet            Started container coredns
  Warning  BackOff                 114s (x54 over 11m)  kubelet            Back-off restarting failed container
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# kubectl logs  coredns-66c464876b-tc622 -n kube-sytem
Error from server (NotFound): namespaces "kube-sytem" not found

**Steps To Reproduce:**
installed k3s offline

Place the k3s binary at /usr/local/bin/k3s and ensure it is executable.

as airgap image tar size is big , I don't need all the images so manually I exported and imported 
like 

ctr  i export k3s_images.tar   docker.io/rancher/coredns-coredns:1.6.9 docker.io/rancher/local-path-provisioner:v0.0.14 docker.io/rancher/metrics-server:v0.3.6 docker.io/rancher/pause:3.1

and imported after k3s install using ctr i import 

I need only this images not 350mb airgap tar file

all pod are in running state except coredns

Please help

**Comment by rajibul007** [comment]
later I importer full airgapimages tar files but still wont help

**Comment by brandond** [comment]
```
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# kubectl logs coredns-66c464876b-tc622 -n kube-sytem
Error from server (NotFound): namespaces "kube-sytem" not found
```

Can you correct your typo and show the logs?

**Comment by rajibul007** [comment]
Ok Is it ok to just take only those image which is needed or I need full airgap images tar , it is 350 mb , no idea why

**Comment by brandond** [comment]
The airgap tarball contains all the images necessary to run a K3s cluster. If you are not disabling any of the core components then you do need all the images, yes. If you are troubleshooting I would recommend not trying to get too fancy.

**Comment by rajibul007** [comment]
I need only coredns , metrics server  and local-path-provisioner
all came in by choosing  docker.io/rancher/coredns-coredns:1.6.9 docker.io/rancher/local-path-provisioner:v0.0.14 docker.io/rancher/metrics-server:v0.3.6 docker.io/rancher/pause:3.1 

except coredns

**Comment by rajibul007** [comment]
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               101s               default-scheduler  Successfully assigned kube-system/coredns-66c464876b-4wj5                                                           x to cxcloudagent
  Warning  FailedCreatePodSandBox  91s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown d                                                           esc = failed to get sandbox image "docker.io/rancher/pause:3.1": failed to pull image "docker.io/rancher/pause:3.1": failed to pul                                                           l and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request:                                                            Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: Try again
  Normal   Pulled                  10s (x4 over 62s)  kubelet            Container image "rancher/coredns-coredns:1.6.9" already p                                                           resent on machine
  Normal   Created                 10s (x4 over 62s)  kubelet            Created container coredns
  Normal   Started                 10s (x4 over 62s)  kubelet            Started container coredns
  Warning  BackOff                 7s (x8 over 60s)   kubelet            Back-off restarting failed container
root@cxcloudagent:~# crictl images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/library/busybox                  latest              3a093384ac306       1.42MB
docker.io/rancher/coredns-coredns          1.6.9               4e797b3234604       13.4MB
docker.io/rancher/local-path-provisioner   v0.0.14             e422121c9c5f9       13.4MB
docker.io/rancher/metrics-server           v0.3.6              9dd718864ce61       10.5MB
docker.io/rancher/pause                    3.1                 da86e6ba6ca19       327kB
insight.engine/sdp/postgresql              1.0.0               f62cb108a23d4       166MB
root@cxcloudagent:~# kubectl get po -A
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   local-path-provisioner-7ff9579c6-j558v   1/1     Running            0          2m34s
kube-system   metrics-server-7b4f8b595-g26l8           1/1     Running            0          2m34s
kube-system   helm-install-traefik-j62m2               0/1     ImagePullBackOff   0          2m34s
kube-system   coredns-66c464876b-4wj5x                 0/1     CrashLoopBackOff   4          2m34s

**Comment by rajibul007** [comment]
facing same with 
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# k3s -v
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5

but when installing in open internet working fine , issue  happens only for offline installation

root@cxcloudagent:/var/lib/rancher/k3s/agent/images# kubectl get po -A
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   metrics-server-86cbb8457f-fc56w           1/1     Running            0          6m16s
kube-system   local-path-provisioner-7c458769fb-lwnz4   1/1     Running            0          6m16s
kube-system   coredns-854c77959c-tfjpn                  0/1     CrashLoopBackOff   3          6m16s
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# k3 -v
k3: command not found
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# crictl images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/rancher/coredns-coredns          1.8.0               296a6d5035e2d       12.9MB
docker.io/rancher/local-path-provisioner   v0.0.14             e422121c9c5f9       13.4MB
docker.io/rancher/metrics-server           v0.3.6              9dd718864ce61       10.5MB
docker.io/rancher/pause                    3.1                 da86e6ba6ca19       327kB
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# kubectl logs coredns-854c77959c-tfjpn -n kube-system
plugin/forward: no nameservers found
root@cxcloudagent:/var/lib/rancher/k3s/agent/images#

**Comment by rajibul007** [comment]
@brandond please let me know what is missing

**Comment by rajibul007** [comment]
I found the issue
if I dont set the nameserver ,coredns is not working , why is that ?
I can,t ask the customer to use set nameserver as a mandatory

**Comment by brandond** [comment]
```
root@cxcloudagent:/var/lib/rancher/k3s/agent/images# kubectl logs coredns-854c77959c-tfjpn -n kube-system
plugin/forward: no nameservers found
```

coredns requires an upstream dns server to forward requests to. I don't think I've ever seen an airgap installation where there isn't at least a private DNS server available? If there really is not ANYTHING that you can point at for DNS, you will need to `--disable coredns` and provide your own coredns manifest that does not include the forward plugin. You can use this as a starting point: https://github.com/k3s-io/k3s/blob/master/manifests/coredns.yaml

**Comment by rajibul007** [comment]
I installed as you suggested 
 INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh --disable servicelb,traefik,coredns

then tried to install this manifest 
https://github.com/k3s-io/k3s/blob/master/manifests/coredns.yaml

root@cxcloudagent:~# kubectl create -f tt.yml
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
Error from server (AlreadyExists): error when creating "tt.yml": serviceaccounts "coredns" already exists
Error from server (AlreadyExists): error when creating "tt.yml": clusterroles.rbac.authorization.k8s.io "system:coredns" already exists
Error from server (AlreadyExists): error when creating "tt.yml": clusterrolebindings.rbac.authorization.k8s.io "system:coredns" already exists
Error from server (AlreadyExists): error when creating "tt.yml": configmaps "coredns" already exists
Error from server (AlreadyExists): error when creating "tt.yml": deployments.apps "coredns" already exists
error parsing tt.yml: error converting YAML to JSON: yaml: line 16: found character that cannot start any token


----


kube-system   coredns-854c77959c-wmc6d                  0/1     ContainerCreating   0          9m39s



Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    5m51s                  default-scheduler  Successfully assigned kube-system/coredns-854c77959c-wmc6d to cx                                                           cloudagent
  Warning  FailedMount  101s (x10 over 5m51s)  kubelet            MountVolume.SetUp failed for volume "config-volume" : configmap                                                            references non-existent config key: NodeHosts
  Warning  FailedMount  94s (x2 over 3m48s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[config-vol

**Comment by brandond** [comment]
That's why I said that you can use it as a starting point. You need to customize it to replace `%{CLUSTER_DOMAIN}%` with your actual cluster domain, and add a NodeHosts section that contains hosts file entries for your nodes. An old example that probably needs some tweaking to work with coredns 1.8 is available here: https://github.com/k3s-io/k3s/issues/1328#issuecomment-606135618

**Comment by rajibul007** [comment]
ok what exact changes required so I can run without nameserver

**Comment by rajibul007** [comment]
For 

k3s -v

k3s version v1.18.6+k3s1 (6f56fa1d)

it is in running state but showing error in log

oot@cxcloudagent:/var/tmp/k3s# kubectl logs -f coredns-8655855d6-xcsjv -n kube-system
.:53
[INFO] plugin/reload: Running configuration MD5 = 4665410bf21c8b272fcfd562c482cb82
[ERROR] Recovered from panic in server: "dns://:53"

/ / ________ / __ / | / / / ~ CoreDNS-1.6.3 / / / __ / / _ / / / / |/ /_ \ ~ linux/amd64, go1.12.9, 37b9550 / // // / / / / // / /| // /
_/_// _/// |//__/

[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"

**Comment by rajibul007** [comment]
I just replace the image of coredns from CoreDNS-1.8.0 CoreDNS-1.6.3 in k3s version v1.20.2+k3s1 (1d4adb03)
now coredns is running 

kube-system   coredns-667944d57d-hkh4z                  1/1     Running   0          19s
root@cxcloudagent:~# k3s -v
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5
root@cxcloudagent:~# kubectl logs coredns-667944d57d-hkh4z  -n kube-system
.:53
[INFO] plugin/reload: Running configuration MD5 = 442b35f70385f5c97f2491a0ce8a27f6
   ______                ____  _   _______
  / ____/___  ________  / __ \/ | / / ___/      ~ CoreDNS-1.6.3
 / /   / __ \/ ___/ _ \/ / / /  |/ /\__ \       ~ linux/amd64, go1.12.9, 37b9550
/ /___/ /_/ / /  /  __/ /_/ / /|  /___/ /
\____/\____/_/   \___/_____/_/ |_//____/
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"
[ERROR] Recovered from panic in server: "dns://:53"


what is changed in coredns image ? any parameter that we can set

**Comment by brandond** [comment]
I have linked to two example coredns manifests, were you able to customize either of those to meet your needs?

**Comment by rajibul007** [comment]
yes If I delete the forward line from config its is running but giving an error from the log,

ERROR] plugin/errors: 2 7202836699202280184.5126757322247728313. HINFO: plugin/loop: no next plugin found

Is it ok to delete that ?

Also, I tried to add the IP of that server as a dummy nameserver in /etc/resolv.conf ,
then It is running without error , 

So I decided to add the IP of that server only if the client doesn't have any nameserver.
please let me know your suggestion.

In nameserver, if I give anything 127..... IP it is giving error and crashloopback state as the request is looping into coredns only. So I concluded with the above approach.

  @brandond  Please let me know your valuable suggestion.
  As per our product, adding a nameserver is optional.
