### ISSUE TITLE
Cannot start k3s systemd unit without environment file

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2923]
From @AkihiroSuda 

**Environmental Info:**
K3s Version: 
N/A

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
N/A

**Describe the bug:**
`k3s.service` was failing when the `EnvironmentFile` does not exist:
```
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed to load environment files: No such file or directory
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed to run 'start' task: No such file or directory
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed with result 'resources'.
Feb 02 17:17:30 suda-ws01 systemd[1]: Failed to start Lightweight Kubernetes.
```

**Steps To Reproduce:**
- Install K3s
- Delete environment file at /etc/systemd/system/k3s.service.env
- Restart k3s service

**Expected behavior:**
K3s starts/restarts

**Actual behavior:**
K3s fails with error above

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
While validating using the latest commit, noticed the following
1. The fix are not reflected in the k3s.service file as it is created by the install script. The changes are made to the static service file in the repo.
2. The install script always creates the env file. Installation would not fail unless the file is deleted.
```
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
```
3. By deleting the file I was able to reproduce the issue and updated the service file manually and validated the fix.

**Comment by ShylajaDevadiga** [comment]
As discussed internally, closing the issue as example file would not be used in conjunction with the install script.
