### ISSUE TITLE
ServiceLB only assigns single internal IP address

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2925]
**Environmental Info:**
K3s Version: 
v1.20.2

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
Multi-node cluster (1 server 1 agent will work)

**Describe the bug:**

I found a problem in the code that handles the loadbalancer ips for the built in service-lb (not metallb or anything else). This isn't necessarily the only problem causing real-ip issues, but it's the one that's caused me to tear my hair out for almost two days.

https://github.com/k3s-io/k3s/blob/c5e2676d5c43aa85ed1e5ac900235f3ce7cf6a1f/pkg/servicelb/controller.go#L232

This code was likely intended to only include a node's internalIP if the node has no externalIP specified. However, since the if statement checks against the global ips list that's being built, it stops doing so if any ip has been found earlier in the nodes loop. This has the unintended effect that for subsequent nodes no internalIPs will be added at all. The order at which this happens is random.
The obvious fix here is to add a boolean variable inside the node loop and set that boolean to true inside the externalIP loop.

This ultimately prevents kube-proxy from adding the appropriate iptables rules, note in iptables that only one of the nodes is listed (`iptables S KUBE-SERVICES -t nat`) explicitly, and thus the masquerade rule (SNAT) kicks in. Except for one random node.

Until the code is fixed, the workaround is to set --node-external-ip=(ip) on the desired nodes. This causes all those ips to be listed as loadbalancerIPs and routed appropriately. This fixes the RemoteAddress that the pods receive, at least in my case.

_I tested this with k3s 1.20.2. With calico+wireguard instead of flannel. And whoami to test. Also checked it with whoami behind traefik (traefik 2 helm chart with externalTrafficPolicy=local on the loadbalancer). I'm not sure if the same happens with flannel, the iptable rules appear to be kube-proxy specific, not flannel/calico._

_Originally posted by @Taloth in https://github.com/k3s-io/k3s/issues/1652#issuecomment-774497788_

**Steps To Reproduce:**
- Install K3s on 2 or more nodes. Do not assign either node an External IP address.

**Expected behavior:**
Note that the traefik service shows the IP of only one node, despite the fact that the LB pod is running on both.

**Actual behavior:**
Traefik service should show both nodes

**Additional context / logs:**

**Comment by rancher-max** [comment]
#### Validated on commit `6e768c301e77738ffd69934363aa0479c4a516d6`

- Confirmed that on v1.20.2+k3s1 it only shows one externalip:
```
$ k get service -n kube-system -o wide
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
kube-dns             ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP       25m   k8s-app=kube-dns
metrics-server       ClusterIP      10.43.158.233   <none>          443/TCP                      25m   k8s-app=metrics-server
traefik-prometheus   ClusterIP      10.43.210.116   <none>          9100/TCP                     24m   app=traefik,release=traefik
traefik              LoadBalancer   10.43.37.109    172.31.34.247   80:32319/TCP,443:32755/TCP   24m   app=traefik,release=traefik
```

- Now, with the changes, it shows both:
```
$ k get service -n kube-system -o wide
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP                   PORT(S)                      AGE     SELECTOR
kube-dns             ClusterIP      10.43.0.10      <none>                        53/UDP,53/TCP,9153/TCP       4m42s   k8s-app=kube-dns
metrics-server       ClusterIP      10.43.227.223   <none>                        443/TCP                      4m42s   k8s-app=metrics-server
traefik-prometheus   ClusterIP      10.43.50.152    <none>                        9100/TCP                     4m17s   app=traefik,release=traefik
traefik              LoadBalancer   10.43.102.106   172.31.34.247,172.31.35.104   80:31364/TCP,443:32477/TCP   4m17s   app=traefik,release=traefik
```

**Comment by rgulden** [comment]
@rancher-max - is this fix only for 1.20.x? I am running 1.18.17 and my LoadBalancer is only grabbing one of nodes ip addresses. Is there a way to manually define the IP address Traefik uses?

**Comment by Taloth** [comment]
@rgulden Workaround is to set `--node-external=<ip>` when installing k3s to set an explicit external IP. _Note that this just ends up in the systemd unit, so you can probably edit it there too._

And yes, it's a safe bet it's only for 1.20.4 and up.

**Comment by rancher-max** [comment]
@rgulden Yes I can confirm this is only for 1.20.4 and above. Glad you got the workaround already for previous versions!

**Comment by rgulden** [comment]
@rancher-max  - Is there any more detailed documentation on how load balancing with Klipper works? It lists my nodes external IP but when I hit it, its times out. Does the targeted pod need to be on that node for it to work? 

Example: PodA lives on Node1. I have a LB deployed targeting that pod. Node1 external is 10.10.10.1 and Node2 external is 10.10.10.2. If I curl 10.10.10.2 should it be able to forward the traffic to my pod, even though its living on another node?

**Comment by blackandred** [comment]
Sorry for posting in closed issue - it may help someone.
For me additionally the Cloud Controller was required to be enabled, even if on bare-metal - it is setting a valid external IP address - so I **had to remove switch** `--disable-cloud-controller`
