### ISSUE TITLE
Enhance documentation on the usage of a single SQLite database file (e.g. on a network share) by multiple k3s instances (e.g. on different machines)

### ISSUE THREAD

**Issue by haukepribnow** [k3s-io/k3s#2933]
First of all: Thanks a lot for k3s.

**Is your feature request related to a problem? Please describe.**
I'm looking for a lightweight way to have the k3s datastore data maintained on an existing network storage solution. This should allow me to set up a HA cluster on two (older) Raspberry Pis that are in the same local network as the network storage solution.

While the network storage solution can be considered HA in this context, it is a "dumb" one, i.e. it only provides a network share. It's impossible to install anything on the device that provides the network storage solution, so MySQL/MariaDB/PostgreSQL are out of the question. I also want to avoid running ethd on the Raspberry Pis because 1) there are only two of them, so no quorum, 2) the less overhead these old devices have, the more they can focus actually on running useful processes, and 3) the network share is already there - so why not try to make use of it.

**Describe the solution you'd like**
While digging through the source code of k3s and kine, I realized that you can provide something like `sqlite://<your_path>` as the k3s datastore endpoint. Since SQLite provies a filesystem-based locking mechanism, I assume that you could run multiple k3s processes on the same SQLite file.

Consequently, I plan on mounting the network share provided by the existing network storage solution on both devices at `/mnt/k3s-datastore` and providing `sqlite:///mnt/k3s-datastore/k3s-sqlite.db` (sic!) as the datastore endpoint to k3s.

Now I wonder if such a setup would work and is supported.

**Additional Context:**
The [documentation for the datastore endpoint format and functionality](https://rancher.com/docs/k3s/latest/en/installation/datastore/#datastore-endpoint-format-and-functionality) does not contain any information on the `sqlite://<your_path>` datastore endpoint syntax,. It also does not contain information how k3s instances behave if they share the very same SQLite file.

**"Feature" request**
This feature request is primarily about enhancing the documentation, primarily on the page https://rancher.com/docs/k3s/latest/en/installation/datastore/

With this ticket, I request as a "feature" to enhance the documentation to
- give a hint about the possibility to change the SQLite database location by using the `sqlite://<your_path>` datastore endpoint syntax, and
- provide information if a cross-instance database file sharing setup as described here is somewhere along the lines of a) recommended, b) supported, c) possible, d) dangerous, e) nonfunctional.

Looking forward to your comments & questions.

**Comment by brandond** [comment]
No, you cannot run multiple servers against a single sqlite database file. File-level locking challenges aside, k3s itself disables some unnecessary Kubernetes locking functionality when run with sqlite, since it knows it will be the only server in the cluster.

**Comment by haukepribnow** [comment]
Thank you for the very fast response. I found two aspects that make datastore endpoint configurations result in different behavior for SQLite:

**a) Write-Ahead Journal**

```dataSourceName = "./db/state.db?_journal=WAL&cache=shared"``` in [sqlite.go -> `NewVariant()`](https://github.com/k3s-io/kine/blob/30047c865361907f14727f2f82a3a3e6b645ac70/pkg/drivers/sqlite/sqlite.go#L55). However, if you provide your own sqlite datastore endpoint, this line will actually not be run, so the default rollback journal configuration will be used instead of the [WAL](https://sqlite.org/wal.html) configuration. So this is not a factor for the use case of this issue.

**b) Leader Election Disabling**

```
	switch driver {
	case SQLiteBackend:
		leaderElect = false
		backend, err = sqlite.New(ctx, dsn, cfg.ConnectionPoolConfig)
```
in [endpoint.go -> `getKineStorageBackend()`](https://github.com/k3s-io/kine/blob/30047c865361907f14727f2f82a3a3e6b645ac70/pkg/endpoint/endpoint.go#L126), so the leader election process gets deactivated when using SQLite.

You wrote:
> k3s itself disables some unnecessary Kubernetes locking functionality when run with sqlite

I assume that you are referring to the latter aspect, i.e. the disabling of the leader election process, right? Or is there more to this that I did not find?

In case the leader election process remains the only blocking point for this use case: Would you accept a pull request that adds an option to k3s that allows you to decide if you want to have the leader election process active or inactive?

**Comment by brandond** [comment]
I don't think I'd want to support it. There are just too many opportunities for breakage with a highly loaded sqlite database on nfs, where you're reliant on frequently flakey shared locking behavior.

If you have a 3rd server that you can use to host the shared filesystem, you should also be run a small database instance on there and point the two servers at it. Failing that, I would probably just make one node a server, the other an agent, and use the 3rd server to host NFS persistent volumes.

**Comment by haukepribnow** [comment]
Understood. Thank you.

Initially, I was assuming that only the leading kine instance interacts with the database server. If this was the case, there would actually not have been any parallel write processing during normal operation (but maybe some parallelism after the leader goes down).

Now that I browsed through kine's code a little further, I question this initial assumption. Did I get it correctly that all kine instances interact with the database server? So the "leadership election" process only takes place for the sake of fulfilling the framing conditions as given by the original etcd implementation?

If this is the case, I understand your concerns.
