### ISSUE TITLE
Enable install script to install selinux rpms for any rpm based systems

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#2937]
While installing k3s on Fedora nodes, we need to explicitly install the selinux rpms. Install script currently handles these package installation for centos/rhel 7/8 OS only.

https://github.com/k3s-io/k3s/blob/master/install.sh#L490

We do not have Fedora in our support matrix. Its nice to have install script handle the installation of required rpms for automation purpose.

```
$ cat /etc/redhat-release
Fedora release 33 (Thirty Three)

curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=5749f66aa3c469b4c744caab1878c6967ac08041 sh -s - server --token secret --selinux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --100 24781  100 24781    0     0   164k      0 --:--:-- --:--:-- --:--:--  164k
[INFO]  Using commit 5749f66aa3c469b4c744caab1878c6967ac08041 as release
[INFO]  Downloading hash https://storage.googleapis.com/k3s-ci-builds/k3s-5749f66aa3c469b4c744caab1878c6967ac08041.sha256sum
[INFO]  Downloading binary https://storage.googleapis.com/k3s-ci-builds/k3s-5749f66aa3c469b4c744caab1878c6967ac08041
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[ERROR]  Failed to apply container_runtime_exec_t to /usr/local/bin/k3s, please install:
    yum install -y container-selinux selinux-policy-base
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm
```
Additional info:
No issues seen with bringing up the cluster with the packages installed
```
$ kubectl get nodes
NAME                                          STATUS   ROLES                  AGE   VERSION
<IP>   Ready    control-plane,master   14m   v1.20.2+k3s-5749f66a
[fedora@ip-172-31-33-203 ~]$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-5ff76fc89d-6h9jp   1/1     Running     0          14m
kube-system   metrics-server-86cbb8457f-rgzvl           1/1     Running     0          14m
kube-system   coredns-854c77959c-f5fmk                  1/1     Running     0          14m
kube-system   helm-install-traefik-7g8t4                0/1     Completed   0          14m
kube-system   svclb-traefik-5n7ps                       2/2     Running     0          14m
kube-system   traefik-6f9cbd9bd4-9zr4s                  1/1     Running     0          14m
$
```

**Comment by dlouzan** [comment]
Maybe a related question would be: is Fedora considered at all for the k3s-selinux packages? tested?

The version for k3s-selinux is fixed on the install script as of today to `0.2-1`, whereas there's a newer stable version `0.3.stable.0` with a new naming scheme.

We are deploying currently on Fedora 33 and, while a manual install of the k3s-selinux package works, it needs a manual verification of the version the k3s install script actually deploys on the other systems, and ofc the question of compatibility remains.

Any feedback will be really welcome!

**Comment by brandond** [comment]
We really should have an evergreen link for the RPM itself; I agree that having a direct (and stale) link in the install script isn't the best.

**Comment by rancher-max** [comment]
https://github.com/k3s-io/k3s/pull/6945

**Comment by rancher-max** [comment]
Bumping to next release per some failing tests that were commented in the PR

**Comment by est-suse** [comment]
Validated On:

rhel8 *
rhel9 (v1.26) *
ubuntu *
sles15 RPM install (instead of default tar) *
centos7 *
Fedora coreos
sle micro
Scenarios:

Single installation

Upgrade from previous version to current commit - Deploying Workloads
Cluster config:

1 server - 1 agent
Commits:

1.26 4182dcaac8da225dd004737db2aae1393308c79d

1.25 c25f611eed749c15a51c6858480b84047974ab63

1.24 53e5d566b5a415544e8c501d34588bdb0a815f40
