### ISSUE TITLE
check-config should not complain about nftables

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2946]
**Environmental Info:**
K3s Version: 
v1.20.2

Node(s) CPU architecture, OS, and Version: 
Linux centos8.lan.khaus 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
N/A

**Describe the bug:**
`k3s check-config` throws an error about iptables needing to be in legacy mode even though we now support nftables.

**Steps To Reproduce:**
- Install K3s
- `k3s check-config`

**Expected behavior:**
No error

**Actual behavior:**
```
System:
- /sbin iptables v1.8.4 (nf_tables): should be older than v1.8.0 or in legacy mode (fail)
```

**Additional context / logs:**

**Comment by rancher-max** [comment]
#### Validated this is working on master branch, commit id: `a7d1159ba6f71f36990fac2a1780fcc3f8621ab6`

```
System:
- /var/lib/rancher/k3s/data/ef9ee2697d4f467b2cbc675d62db2a3a4ac9f32686af2206db7da150afe66116/bin/aux iptables v1.8.5 (nf_tables): ok
```
