### ISSUE TITLE
Add CI tests for nf_tables

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2955]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when nf_tables support is broken and I don't know about it because CI doesn't test for it

**Describe the solution you'd like**
Working CI tests for nf_tables support

**Describe alternatives you've considered**
Continue to not actually ensure that nf_tables support works

**Additional context**
#2940

**Comment by rancher-max** [comment]
Closing as we generally do not test CI changes (CI tests them itself 🙂 )
