### ISSUE TITLE
Support ServiceTopology

### ISSUE THREAD

**Issue by ssimard-genetec** [k3s-io/k3s#2959]
Is the service topology feature supported with k3s?
(https://kubernetes.io/docs/concepts/services-networking/service-topology/)

I tried to enabled it using the following command line on the server node:

`curl -sfL https://get.k3s.io | sh -s - --kube-apiserver-arg="feature-gates=ServiceTopology=true,EndpointSlice=true" --kube-scheduler-arg="feature-gates=ServiceTopology=true,EndpointSlice=true" --kube-controller-manager-arg="feature-gates=ServiceTopology=true,EndpointSlice=true" --kube-apiserver-arg="feature-gates=ServiceTopology=true,EndpointSlice=true"`

and the following command on the agent nodes:
`curl -sfL https://get.k3s.io | K3S_URL=https://172.xx.xx.xx:6443 K3S_TOKEN=Kxxx::server:xxxe sh -`

Am I missing something?

**Comment by brandond** [comment]
You can't put the quotes in the middle of the flag like that. Keep it simple:
`curl -sfL https://get.k3s.io | sh -s - --kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true --kube-scheduler-arg=feature-gates=ServiceTopology=true,EndpointSlice=true --kube-controller-manager-arg=feature-gates=ServiceTopology=true,EndpointSlice=true --kubelet-arg=feature-gates=ServiceTopology=true,EndpointSlice=true`

I am not sure you need to enable that everywhere though, you might confirm that?

**Comment by brandond** [comment]
Also, note that EndpointSlice has defaulted to true since v1.18 so you don't really need to set that.

**Comment by ssimard-genetec** [comment]
Is there a way to verify that the feature is properly enabled?

What I can see is that the feature flags are passed to the k3s server, but the ServiceTopology behavior is still not effective.

Since ServiceTopology feature is still in alpha stage, is it possible that K3s does not supports it (has been stripped out)?

```
cat /etc/systemd/system/k3s.service

[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-scheduler-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-controller-manager-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
```

**Comment by ssimard-genetec** [comment]
Found it...

To make it work, I had to also pass the feature flags to the kube-proxy on the server and the agents.

Thank you very much for your help.
