### ISSUE TITLE
K3S install ignores --disable flag

### ISSUE THREAD

**Issue by FRUCHTiii** [k3s-io/k3s#2962]
**Environmental Info:**
K3s Version: k3s version v1.20.2+k3s1 (1d4adb03)

Node(s) CPU architecture, OS, and Version: Linux ubuntu 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration: for testing only one node

**Describe the bug:**
The install curl script ignores --disable flag.

**Steps To Reproduce:**

- Installed K3s: 
  curl -sfL https://get.k3s.io | K3S_TOKEN=1234567890 INSTALL_K3S_EXEC="server --disable servicelb" sh -

**Expected behavior:**
There should be no Klipper container in ctr container list

**Actual behavior:**
There is a Klipper container

**Additional context / logs:**
For both tests I used a fresh installed ubuntu and only changed the cgroups.

If I use the following script:
It also dont work with --no-deploy
curl -sfL https://get.k3s.io | K3S_TOKEN=1234567890 INSTALL_K3S_EXEC="server --no-deploy servicelb" sh -
[k3s_disable.log](https://github.com/k3s-io/k3s/files/6009166/k3s_disable.log)
[k3s_no-deploy.log](https://github.com/k3s-io/k3s/files/6009167/k3s_no-deploy.log)

**Comment by brandond** [comment]
Seems to work for me, I don't see any servicelb pods. Can you show similar output for your node?

```
root@centos01 manifests]# cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--disable' \
	'servicelb' \

[root@centos01 manifests]# kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-7c458769fb-87j9v   1/1     Running     0          45s
kube-system   metrics-server-86cbb8457f-s9lrg           1/1     Running     0          45s
kube-system   coredns-854c77959c-5htc4                  1/1     Running     0          45s
kube-system   helm-install-traefik-7kr2d                0/1     Completed   0          45s
kube-system   traefik-6f9cbd9bd4-tvm58                  1/1     Running     0          23s

[root@centos01 manifests]# kubectl get service -A
NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       kubernetes           ClusterIP      10.43.0.1       <none>        443/TCP                      66s
kube-system   kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       63s
kube-system   metrics-server       ClusterIP      10.43.38.198    <none>        443/TCP                      63s
kube-system   traefik-prometheus   ClusterIP      10.43.76.178    <none>        9100/TCP                     30s
kube-system   traefik              LoadBalancer   10.43.213.134   <pending>     80:30510/TCP,443:30483/TCP   30s

**Comment by FRUCHTiii** [comment]
Yes your right. But why is there a Klipper container created by K3s?

`root@ubuntu:~# curl -sfL https://get.k3s.io | K3S_TOKEN=1234567890 INSTALL_K3S_EXEC="server --disable servicelb" sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.2+k3s1/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.20.2+k3s1/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
root@ubuntu:~# curl -sfL https://get.k3s.io | K3S_TOKEN=1234567890 INSTALL_K3S_EXEC="server --disable servicelb" sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.2+k3s1/sha256sum-arm64.txt
^Croot@ubuntu:~# cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--disable' \
	'servicelb' \

root@ubuntu:~# kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-7c458769fb-v9w7v   1/1     Running     0          46s
kube-system   coredns-854c77959c-vkrhn                  1/1     Running     0          46s
kube-system   helm-install-traefik-2nbnm                0/1     Completed   0          46s
kube-system   metrics-server-86cbb8457f-kqmkk           1/1     Running     0          46s
kube-system   traefik-6f9cbd9bd4-6qvtv                  0/1     Running     0          17s
root@ubuntu:~# kubectl get service -A
NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       kubernetes           ClusterIP      10.43.0.1       <none>        443/TCP                      71s
kube-system   kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       69s
kube-system   metrics-server       ClusterIP      10.43.210.191   <none>        443/TCP                      68s
kube-system   traefik-prometheus   ClusterIP      10.43.63.123    <none>        9100/TCP                     26s
kube-system   traefik              LoadBalancer   10.43.130.160   <pending>     80:30476/TCP,443:32067/TCP   26s
root@ubuntu:~# ctr container list
CONTAINER                                                           IMAGE                                                                                                        RUNTIME
1057b6eac95e9e8f046b085dc611b5916a5fe78bac45d6dea19272a5a5978de3    docker.io/rancher/library-traefik@sha256:3ba3ed48c4632f2b02671923950b30b5b7f1b556e559ce15446d1f5d648a037d    io.containerd.runc.v2
24c549045563c2464e95caf098ea47ecd550a53783c71129585878942e1e7db1    docker.io/rancher/pause:3.1                                                                                  io.containerd.runc.v2
60da34b8a3548a6af80b9abcb0c72b7cbb86949c716b32727592377279c9060d    docker.io/rancher/pause:3.1                                                                                  io.containerd.runc.v2
a4ea4001aa82a256751c39adcaeca7a1213973f7d6c94a65acf61ab4affbbdfd    docker.io/rancher/coredns-coredns:1.8.0                                                                      io.containerd.runc.v2
b6d9c259adabacabdc74492621e2eb52ab63e41039e4d1701d94d2edcecd32c8    docker.io/rancher/local-path-provisioner:v0.0.14                                                             io.containerd.runc.v2
bde02c10072fe72a3fda32788a5cf2f7f7855933dd934884a2ef411ec4602996    docker.io/rancher/metrics-server:v0.3.6                                                                      io.containerd.runc.v2
c63ef1161a21f0aa4ed2d95089c42664373a0937db4a5753065d699caa7a8ec4    docker.io/rancher/klipper-helm:v0.4.3                                                                        io.containerd.runc.v2
d379f58fbd32c61e491684433e5981e3e9883554d9ba5b062ddacb035739c25d    docker.io/rancher/pause:3.1                                                                                  io.containerd.runc.v2
e15c0ef803cfc13f0af3a3159e6e57d9ac981e953f231daf1741ffc78e241209    docker.io/rancher/pause:3.1                                                                                  io.containerd.runc.v2
fd4c964a6533ac4051346ab1f66079904eaac3b554526a3d026a585e680e5c25    docker.io/rancher/pause:3.1                                                                                  io.containerd.runc.v2
root@ubuntu:~#`

**Comment by brandond** [comment]
That's the Helm image, not ServiceLB? For the pod that was run to install the traefik chart?

**Comment by FRUCHTiii** [comment]
Ok thanks a lot.
