### ISSUE TITLE
Kubectl multiple server Ips ? When 1 node is down ? Failover and still able to access Kubectl ?

### ISSUE THREAD

**Issue by iangregsondev** [k3s-io/k3s#2964]
Hi,

I have a working HA setup using k3s (3 nodes) and it works great, I can power nodes down and a test a deployment I have continues to work. I am using metallb for the loadbalancer - all is working great. As nodes are powered off the deployment moves to another node and their is practically no down time. This is great.

Here is my nodes

```
❯ kubectl get nodes -o wide
NAME            STATUS   ROLES         AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION    CONTAINER-RUNTIME
onechain-lab1   Ready    etcd,master   23h   v1.19.7+k3s1   192.168.1.20   <none>        Debian GNU/Linux 10 (buster)   4.19.0-14-amd64   containerd://1.4.3-k3s1
onechain-lab2   Ready    etcd,master   23h   v1.19.7+k3s1   192.168.1.21   <none>        Debian GNU/Linux 10 (buster)   4.19.0-14-amd64   containerd://1.4.3-k3s1
onechain-lab3   Ready    etcd,master   23h   v1.19.7+k3s1   192.168.1.22   <none>        Debian GNU/Linux 10 (buster)   4.19.0-14-amd64   containerd://1.4.3-k3s1
```

The problem is that in the Config for kubectl I only see 1 IP address under "server", so my config points to 192.168.1.20 so if this node is available then kubectl works great.

Problem is that when 192.168.1.20 goes down - everything continues to work BUT kubectl no longer works.

The only fix I have found is by editing the config file and replaces 192.168.1.20 with 192.168.1.21 for example

I don't have any more infrastructure - only the 3 machines, the "server" inside of the config file doesn't seem to accept multiple ips.

Is there anything I can do ?

Hence if node1 goes down and I still want to access kubectl then I have to update this IP manually

```
    server: https://192.168.1.20:6443
  name: default
contexts:
- context:
```

Thanks in advance for any insight.

**Comment by brandond** [comment]
You would need to put an external load-balancer or virtual ip in front of the control plane if you want it to be HA from outside the cluster.

**Comment by iangregsondev** [comment]
Thanks. OK, I will try and put a ha proxy in from of the nodes, running on a pi 😂

Should be sufficient.

Thanks
