### ISSUE TITLE
No relationship found between node '[NODENAME]' and this object

### ISSUE THREAD

**Issue by ambis** [k3s-io/k3s#2966]
**Environmental Info:**
K3s Version:
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5

Node(s) CPU architecture, OS, and Version: 
Hetzner Cloud VPS Debian-10 (up to date)
Linux master-10 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

Cluster Configuration:
3 masters with builtin etcd, are in LAN and none of the masters have firewalls or anything
Longhorn 1.1.0 as CSI
Calico as CNI

**Describe the bug:**
Very randomly a pod that has been running for a few days might get stuck in a Terminating state after being automatically updated by Flux2.

When describing said pod, it has this event:

MountVolume.WaitForAttach failed for volume "pvc-9c98d5b9-2922-4062-9fab-e61f3cecd61e" : volume pvc-9c98d5b9-2922-4062-9fab-e61f3cecd61e has GET error for volume attachment csi-86c3aab1fd6222a222a39c6f4aec413fd8aa0bdbeab4f17741c7b185f6c0a0a9: volumeattachments.storage.k8s.io "csi-86c3aab1fd6222a222a39c6f4aec413fd8aa0bdbeab4f17741c7b185f6c0a0a9" **is forbidden: User "system:node:master-12.cloud.MY.DOMAIN" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'master-12.cloud.MY.DOMAIN' and this object**

**Steps To Reproduce:**

- Installed K3s: 
```
export INSTALL_K3S_VERSION="v1.20.2+k3s1"
export INSTALL_K3S_EXEC="server"
export K3S_CONFIG_FILE="/etc/rancher/k3s-setup/config.yaml"
export K3S_URL=https://masters.cloud.MY.DOMAIN:6443

curl -sfL https://get.k3s.io | sh -
```

```
# /etc/rancher/k3s-setup/config.yaml
node-name: master-12.cloud.MY.DOMAIN
disable:
    - traefik
    - servicelb
    - local-storage
    - metrics-server
disable-network-policy: true
disable-cloud-controller: true
flannel-backend: "none"
token-file: "/etc/rancher/k3s-setup/token"
agent-token-file: "/etc/rancher/k3s-setup/agent-token"
tls-san:
    - masters.cloud.MY.DOMAIN
```

```
export ETCDCTL_ENDPOINTS='https://127.0.0.1:2379'
export ETCDCTL_CACERT='/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt'
export ETCDCTL_CERT='/var/lib/rancher/k3s/server/tls/etcd/server-client.crt'
export ETCDCTL_KEY='/var/lib/rancher/k3s/server/tls/etcd/server-client.key'
export ETCDCTL_API=3

etcdctl member list
496648d7656ca884, started, master-11-b0cc809a, https://10.0.0.11:2380, https://10.0.0.11:2379
83939a10babbc3ee, started, master-10-3768c602, https://10.0.0.10:2380, https://10.0.0.10:2379
ba381af040aa4740, started, master-12-779d77ac, https://10.0.0.12:2380, https://10.0.0.12:2379
```

**Expected behavior:**
...not get this error.

**Actual behavior:**
Pod Terminates OK and not get this error.

**Additional context / logs:**
I went through Longhorn's logs about this volume "pvc-9c98d5b9-2922-4062-9fab-e61f3cecd61e" and it had operated completely normal. So I don't think this has nothing to do with Longhorn. 

This can happen on all of the nodes.

I believe this has something to do with NodeAutorization (as the error is thrown in 
https://gitlab.cncf.ci/kubernetes/kubernetes/blob/16e355791f2c3438862cb09bf6f5213caaded996/plugin/pkg/auth/authorizer/node/node_authorizer.go#L200
(Not sure if link is to a proper version or which line it is.)

I have checked all DNS settings and servers and everything seems to be in fully functioning order.

Also I'm running a lot of workloads in the cluster and *everything* else works flawlessly except for this one random error!

**Comment by ambis** [comment]
I have a hunch of what might be amiss here:
Linux **master-10** 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

I now changed my nodes' hostname to FQDN as they are registered with them:
Linux **master-10.MY.DOMAIN** 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

Lets see if this helps..

**Comment by ambis** [comment]
"Noooooooooooo!" -Darth Vader

```
 is forbidden: User "system:node:master-10" cannot get resource "volumeattachments" in 
API group "storage.k8s.io" at the cluster scope: no relationship found between node 
'master-10' and this object
```

I deleted/rejoined masters one by one with short names instead of FQDN, so their `hostname` matches the kubernetes node's name. No luck.

DNS search domain is set to `cloud.MY.DOMAIN` so that when resolving `master-10` it resolves to `master-10.cloud.MY.DOMAIN`.

Help?

**Comment by brandond** [comment]
Kubernetes really doesn't like having nodes change hostnames. The agent certs and such probably have the wrong hostnames in them. You might try doing the following on each node:
* Stop K3s
* Delete node from cluster (using kubectl on a different node, of course)
* rm -rf /var/lib/rancher/k3s/agent
* Start K3s
