### ISSUE TITLE
K3s deployed on CentOS8 cannot join rancher

### ISSUE THREAD

**Issue by AbelTaylor** [k3s-io/k3s#2977]
**Environmental Info:**

K3s Version: 
<v18.15-k3s1>

Rancher Version:
<v2.5.5>

![image](https://user-images.githubusercontent.com/71317399/108942973-ebe6b400-7692-11eb-8f39-eaeb645b15b5.png)
![image](https://user-images.githubusercontent.com/71317399/108943012-ff921a80-7692-11eb-963b-0d06f67acafc.png)

Node(s) CPU architecture, OS, and Version: 
<CentOS Linux 8   4.18.0-240.10.1.el8_3.x86_64>

Cluster Configuration:
<1 masters, 2 workers>

**Describe the bug:**

<As shown in the figure, I tried to add a k3s cluster deployed on CentOS8 to rancher, but it failed. The relevant screenshots and logs have been uploaded>

![image](https://user-images.githubusercontent.com/71317399/108954250-7b965d80-76a7-11eb-9df4-cc1f3fbf75a7.png)
![image](https://user-images.githubusercontent.com/71317399/108954296-92d54b00-76a7-11eb-95f0-a9773034457b.png)
![image](https://user-images.githubusercontent.com/71317399/108954380-ae405600-76a7-11eb-92e0-5d9a02f2704c.png)

**Expected behavior:**
<join rancher>

**Actual behavior:**

**Comment by brandond** [comment]
Can you attach the full k3s service logs? Screenshots are hard to work off of. Logs from the crashing pods would also be useful.

**Comment by AbelTaylor** [comment]
Hi, brandond, Thank you for replying so late.
This is the log of my three hosts.

[k3s-server-210.log](https://github.com/k3s-io/k3s/files/6033701/k3s-server-210.log)
[k3s-agent-220.log](https://github.com/k3s-io/k3s/files/6033699/k3s-agent-220.log)
[k3s-agent-221.log](https://github.com/k3s-io/k3s/files/6033700/k3s-agent-221.log)

**Comment by brandond** [comment]
I don't see anything wrong with the k3s server/agent logs. Can you share the logs from the crashing rancher pods? If it is a Rancher issue (which is appears to be, since your k3s cluster is working fine) we can move this issue to the rancher/rancher repo.

**Comment by AbelTaylor** [comment]
Hi,brandond
As shown:
![image](https://user-images.githubusercontent.com/71317399/109090794-91ab2900-774e-11eb-836d-14b7bb68239d.png)

**Comment by brandond** [comment]
Can you successfully `curl -vk https://192.168.163.200/ping` both on the host and within the pod?

**Comment by AbelTaylor** [comment]
Hi,brandond,both on host and within pod look good..
host:
![image](https://user-images.githubusercontent.com/71317399/109124843-588eab00-7786-11eb-81b2-5ecd4568b9a2.png)
pod:
![image](https://user-images.githubusercontent.com/71317399/109128904-f7b5a180-778a-11eb-8395-32b3e268d68f.png)
![image](https://user-images.githubusercontent.com/71317399/109129002-1451d980-778b-11eb-8652-aded0cc99320.png)

with cattle-system pod
![image](https://user-images.githubusercontent.com/71317399/109129148-47946880-778b-11eb-9824-6b918fb3be84.png)

What a strange question. .

**Comment by brandond** [comment]
Since you can successfully access the Rancher server from both the nodes and the pods, it looks like K3s is working properly. I think this issue needs to be moved to rancher/rancher to figure out why the cattle-cluster-agent isn't working.
