### ISSUE TITLE
The two POD networks are disconnected

### ISSUE THREAD

**Issue by LinXiaoJian** [k3s-io/k3s#2978]
Recently, I encountered a particularly strange problem.
I have a K3S cluster and recently added a new machine to the K3S cluster, but found that the POD network on two different machines could not connect.
I use the ping command on machine a to Ping the IP address of pod on machine B.Use the tcpdump tool to grab the packet

![image](https://user-images.githubusercontent.com/11407854/109025224-7eba3980-76f9-11eb-97a3-b0ab47b5850c.png)

As shown, there is no Reply data
At the same time, I used the route -n to check, and found no exception

![image](https://user-images.githubusercontent.com/11407854/109025648-e1133a00-76f9-11eb-8c96-65c226a01016.png)

The K3s version of the machine in question is V1.20.2 + K3S1, and the K3s version of the other machines is V1.19.4 + K3S1
Is this problem caused by version inconsistency.How can I solve this problem.Looking forward to your reply. Thank you very much.

**Comment by brandond** [comment]
It is not generally recommended to run different versions of Kubernetes in the same cluster, except for briefly during an upgrade. Have you tried bringing both nodes up to the latest 1.20 release?

**Comment by LinXiaoJian** [comment]
I adjusted the version to the same version.The problem is solved.Thanks
