### ISSUE TITLE
Cluster failing when reloading my flannel wireguard interface.

### ISSUE THREAD

**Issue by maxisme** [k3s-io/k3s#2979]
**Environmental Info:**
K3s Version: 

k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 

Linux ovh-node 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master 4 workers

**Describe the bug:**

I have set the flannel interface on the masters and the workers like:
```
--flannel-iface wg1
```
Unfortunately however if on the master I reload the `wg1`  interface (`wg-quick down wg1 && wg-quick up wg1`) - k3s does not seem to handle it well with a lot of things appearing to start hanging. It is then fixed by reloading the k3s service on the master node (`service k3s restart`).
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network-online.target

[Service]
Type=notify
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server --node-external-ip X.X.X.X --node-ip 10.1.0.6 --no-deploy traefik --flannel-iface wg1
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

**Steps To Reproduce:**

- Installed K3s with `--flannel-iface wg1`
- restart wg1

**Expected behavior:**

- k3s to handle the reload of the interface without needing to be restarted.

**Actual behavior:**

I can't find any specific logs but it just feels like flanel breaks and the internal networking stops working.

**Additional context / logs:**

N/A - but would really appreciate some pointers on where I should be looking.

**Comment by brandond** [comment]
I don't know what wireguard is doing when you take it down and bring it back up that would leave communication on that interface permanently broken. If it is deleting interfaces that we are bound to, I can see how that would require a restart to resume listening. Does it seem unreasonable that a service would need to be restarted when you take down the interface that it is bound to?

**Comment by maxisme** [comment]
yes when you run `wg-quick down wg1` it completely deletes the interface. For some reason when adding a node to my wg mesh I have to restart (down/up) every interface. I have tried other wireguard techniques such as [syncconf](https://manpages.debian.org/unstable/wireguard-tools/wg.8.en.html) but they don't work. Do you think that perhaps I need to add some hook to my config above to restart k3s after?

**Comment by brandond** [comment]
Yeah, I'm not sure of the best way to add that hook but I don't see any other way around it. If the interface we're listening on goes away, K3s (and all the Kubernetes bits) need to be restarted to resume listening on it.

**Comment by maxisme** [comment]
I have noticed that if I restart wireguard on any node all connections to it stop working even though k8s is saying the node is in a ready state. restarting the master node fixes this...
