### ISSUE TITLE
Update CoreDNS version in master

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3001]
CoreDNS 1.8.3 is out - we should consider bumping to this updated version.

**Comment by briandowns** [comment]
Work done in #3168 3168

**Comment by rancher-max** [comment]
#### Validated in v1.21.0-rc1+k3s1

- rancher/coredns-coredns:1.8.3 is installed by default in v1.21.0-rc1+k3s1
- Upgrading from v1.20.6+k3s1 upgrades coredns version from rancher/coredns-coredns:1.8.0 to rancher/coredns-coredns:1.8.3
- DNS checks continue to work as expected
