### ISSUE TITLE
missing routes when node IP addresses change

### ISSUE THREAD

**Issue by iameli** [k3s-io/k3s#3006]
**Environmental Info:**
```
$ k3s -v
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux rkv-small-0 5.0.0-41-generic #45~18.04.1-Ubuntu SMP Fri Feb 14 13:06:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
6 servers, all of which are control-plane masters.

**Describe the bug:**
Since upgrading to v1.20.4+k3s1, a variety of nodes in multiple clusters have been booting up without getting their Flannel routes properly. Here's a problematic node:

```
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG    100    0        0 eth0
10.42.4.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
169.254.169.254 192.168.10.2    255.255.255.255 UGH   100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

Compared with a working node:
```
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG    100    0        0 eth0
10.42.0.0       10.42.0.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.1.0       10.42.1.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.2.0       10.42.2.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.4.0       10.42.4.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.5.0       10.42.5.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.6.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
169.254.169.254 192.168.10.3    255.255.255.255 UGH   100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**Steps To Reproduce:**

- Installed K3s: ansible playbook

**Expected behavior:**
Flannel routes

**Actual behavior:**
No Flannel routes

**Additional context / logs:**
The only thing that seems like it might be related is this? (I redacted our public IPv4 prefix and replaced it with "8.8" for our purposes here.)

```
Mar 02 18:47:10 rkv-small-a-0 k3s[8651]: time="2021-03-02T18:47:10.670603552Z" level=info msg="Connecting to proxy" url="wss://8.8.22.103:6443/v1-k3s/connect"
Mar 02 18:47:10 rkv-small-a-0 k3s[8651]: time="2021-03-02T18:47:10.673022296Z" level=error msg="Failed to connect to proxy" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 192.168.10.102, 192.168.10.109, 192.168.10.144, 192.168.10.145, 192.168.10.198, 192.168.10.30, 192.168.10.58, 192.168.10.62, 192.168.10.68, 192.168.10.69, 192.168.10.78, 192.168.10.90, 8.8.20.20, 8.8.20.240, 8.8.20.245, 8.8.21.118, 8.8.21.180, 8.8.21.56, 8.8.22.123, 8.8.22.186, 8.8.23.191, 8.8.23.213, 8.8.23.244, not 8.8.22.103"
Mar 02 18:47:10 rkv-small-a-0 k3s[8651]: time="2021-03-02T18:47:10.673136277Z" level=error msg="Remotedialer proxy error" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 192.168.10.102, 192.168.10.109, 192.168.10.144, 192.168.10.145, 192.168.10.198, 192.168.10.30, 192.168.10.58, 192.168.10.62, 192.168.10.68, 192.168.10.69, 192.168.10.78, 192.168.10.90, 8.8.20.20, 8.8.20.240, 8.8.20.245, 8.8.21.118, 8.8.21.180, 8.8.21.56, 8.8.22.123, 8.8.22.186, 8.8.23.191, 8.8.23.213, 8.8.23.244, not 8.8.22.103"
```

I guess the IP address of some of our nodes changed, but we were also getting this in cases where it didn't change, and surely if an IP changed the pertinent x509 certificate should be re-issued too?

EDIT: Full sanitized logs upon `systemctl restart k3s` on the problematic node: https://gist.github.com/iameli/b7cac680500c0dc2878417d254aae267

**Comment by iameli** [comment]
This seems to have been resolved with a rolling restart of k3s on all nodes; someone needed to update their x509 certs.

Do y'all think nodes should be smart enough to mark themselves NotReady in this instance, where internal pod networking isn't working well?

**Comment by brandond** [comment]
Did the IP address change on the nodes while K3s was running? K3s (and Kubernetes) only checks node address stuff on startup; static addresses (or at least a DHCP server which will reuse lease addresses) are pretty well documented as a requirement for running Kubernetes.

**Comment by iameli** [comment]
I don't believe so; the cluster was shut down a few days ago and then all the nodes booted up with new IPs yesterday.
