### ISSUE TITLE
On an etcd-only setup second node cannot be joined to the first node using public IP

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3020]
**Environmental Info:**
K3s Version: 
k3s -v
k3s version v1.20.4+k3s-fad2a046 (fad2a046)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Node1:

- etcd only

Node 2:

- all roles

**Describe the bug:**
Unable to join the second node using public-ip of first node while first node being etcd-only fails with invalid certificate error.
Joining using private ip is successful.
```
CA cert validation failed: Get \"https://<public ip of node1>:6443/cacerts\": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 172.31.21.225, not  <node1 public ip>"
```

**Steps To Reproduce:**

Node1:
```
$ curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=fad2a046c37e296a82e33be943cfe316a20f47bb sh -s - server --cluster-init --token <shared secret> --disable-api-server --disable-controller-manager --disable-scheduler
```
Node2:
```
$ curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=fad2a046c37e296a82e33be943cfe316a20f47bb sh -s - server  --token <shared secret> --server https://<public ip of node1>:6443
```

**Expected behavior:**
Second node should join using public ip

**Actual behavior:**
Second node does not join using public ip

**Comment by brandond** [comment]
Right now we don't support etcd nodes communicating via public IPs at all. We've had users ask for it, but right now we only advertise the private IPs in the PeerURLs/ClientURLs lists so even if we added the right SANs to the certs I think there are other things keeping it from working.

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 8ace8975d293bf6eb46e27d207fb667a47d282a5, second node was able to join first node successfully following steps to reproduce.
```
k3s -v
k3s version v1.20.4+k3s-8ace8975 (8ace8975)
go version go1.15.8

kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-13-32   Ready    etcd                        31s   v1.20.4+k3s-8ace8975
ip-172-31-14-69   Ready    control-plane,etcd,master   39s   v1.20.4+k3s-8ace8975
```
