### ISSUE TITLE
Generate a large number of logs in real time like http: TLS handshake error from [::1]

### ISSUE THREAD

**Issue by guanxingfeng** [k3s-io/k3s#3025]
### Version:

OS:Ubuntu 16.04.6 LTS
k3s version： v1.18.13+k3s1 (b682c9c6)
Docker version：18.06.3-ce
### Describe the bug
I have lots of TLS handshake error log on Both k3s master node and agent node in real time，Daily log files reach 50 MB. 
Restart node does not work.
eg:
root@edge-master-1:~# journalctl -xf
-- Logs begin at Fri 2021-03-05 11:11:23 CST. --
Mar 05 14:24:12 edge-master-1 k3s[29827]: I0305 14:24:12.262579   29827 log.go:172] http: TLS handshake error from [::1]:54608: EOF
Mar 05 14:24:12 edge-master-1 k3s[29827]: I0305 14:24:12.262918   29827 log.go:172] http: TLS handshake error from [::1]:48812: EOF
Mar 05 14:24:12 edge-master-1 k3s[29827]: I0305 14:24:12.762717   29827 log.go:172] http: TLS handshake error from [::1]:54612: EOF
Mar 05 14:24:12 edge-master-1 k3s[29827]: I0305 14:24:12.764057   29827 log.go:172] http: TLS handshake error from [::1]:48816: EOF
Mar 05 14:24:13 edge-master-1 k3s[29827]: I0305 14:24:13.262245   29827 log.go:172] http: TLS handshake error from [::1]:54616: EOF
Mar 05 14:24:13 edge-master-1 k3s[29827]: I0305 14:24:13.262575   29827 log.go:172] http: TLS handshake error from [::1]:48820: EOF
Mar 05 14:24:13 edge-master-1 k3s[29827]: I0305 14:24:13.766151   29827 log.go:172] http: TLS handshake error from [::1]:54620: EOF
Mar 05 14:24:13 edge-master-1 k3s[29827]: I0305 14:24:13.767896   29827 log.go:172] http: TLS handshake error from [::1]:48824: EOF
Mar 05 14:24:14 edge-master-1 k3s[29827]: I0305 14:24:14.261992   29827 log.go:172] http: TLS handshake error from [::1]:48828: EOF
Mar 05 14:24:14 edge-master-1 k3s[29827]: I0305 14:24:14.262103   29827 log.go:172] http: TLS handshake error from [::1]:54624: EOF
Mar 05 14:24:14 edge-master-1 k3s[29827]: I0305 14:24:14.786533   29827 log.go:172] http: TLS handshake error from [::1]:54628: EOF
Mar 05 14:24:14 edge-master-1 k3s[29827]: I0305 14:24:14.787237   29827 log.go:172] http: TLS handshake error from [::1]:48832: EOF
Mar 05 14:24:15 edge-master-1 k3s[29827]: I0305 14:24:15.263500   29827 log.go:172] http: TLS handshake error from [::1]:54634: EOF
Mar 05 14:24:15 edge-master-1 k3s[29827]: I0305 14:24:15.264196   29827 log.go:172] http: TLS handshake error from [::1]:48838: EOF
Mar 05 14:24:15 edge-master-1 k3s[29827]: I0305 14:24:15.764337   29827 log.go:172] http: TLS handshake error from [::1]:48842: EOF
Mar 05 14:24:15 edge-master-1 k3s[29827]: I0305 14:24:15.765405   29827 log.go:172] http: TLS handshake error from [::1]:54638: EOF
Mar 05 14:24:16 edge-master-1 k3s[29827]: I0305 14:24:16.264795   29827 log.go:172] http: TLS handshake error from [::1]:54644: EOF
Mar 05 14:24:16 edge-master-1 k3s[29827]: I0305 14:24:16.264912   29827 log.go:172] http: TLS handshake error from [::1]:48848: EOF
Mar 05 14:24:16 edge-master-1 k3s[29827]: I0305 14:24:16.764533   29827 log.go:172] http: TLS handshake error from [::1]:54648: EOF
Mar 05 14:24:16 edge-master-1 k3s[29827]: I0305 14:24:16.765676   29827 log.go:172] http: TLS handshake error from [::1]:48852: EOF
Mar 05 14:24:17 edge-master-1 k3s[29827]: I0305 14:24:17.264364   29827 log.go:172] http: TLS handshake error from [::1]:48856: EOF
Mar 05 14:24:17 edge-master-1 k3s[29827]: I0305 14:24:17.264638   29827 log.go:172] http: TLS handshake error from [::1]:54652: EOF
Mar 05 14:24:17 edge-master-1 k3s[29827]: I0305 14:24:17.786284   29827 log.go:172] http: TLS handshake error from [::1]:48864: EOF
Mar 05 14:24:17 edge-master-1 k3s[29827]: I0305 14:24:17.786357   29827 log.go:172] http: TLS handshake error from [::1]:54660: EOF
Mar 05 14:24:18 edge-master-1 k3s[29827]: I0305 14:24:18.265290   29827 log.go:172] http: TLS handshake error from [::1]:54666: EOF
Mar 05 14:24:18 edge-master-1 k3s[29827]: I0305 14:24:18.266826   29827 log.go:172] http: TLS handshake error from [::1]:48870: EOF
Mar 05 14:24:18 edge-master-1 k3s[29827]: I0305 14:24:18.765441   29827 log.go:172] http: TLS handshake error from [::1]:48874: EOF
Mar 05 14:24:18 edge-master-1 k3s[29827]: I0305 14:24:18.766151   29827 log.go:172] http: TLS handshake error from [::1]:54670: EOF
Mar 05 14:24:19 edge-master-1 k3s[29827]: I0305 14:24:19.265595   29827 log.go:172] http: TLS handshake error from [::1]:54674: EOF
Mar 05 14:24:19 edge-master-1 k3s[29827]: I0305 14:24:19.266476   29827 log.go:172] http: TLS handshake error from [::1]:48878: EOF
Mar 05 14:24:19 edge-master-1 k3s[29827]: I0305 14:24:19.765639   29827 log.go:172] http: TLS handshake error from [::1]:54678: EOF
Mar 05 14:24:19 edge-master-1 k3s[29827]: I0305 14:24:19.765904   29827 log.go:172] http: TLS handshake error from [::1]:48882: EOF
Mar 05 14:24:20 edge-master-1 k3s[29827]: I0305 14:24:20.265526   29827 log.go:172] http: TLS handshake error from [::1]:48886: EOF
Mar 05 14:24:20 edge-master-1 k3s[29827]: I0305 14:24:20.266088   29827 log.go:172] http: TLS handshake error from [::1]:54682: EOF

root@edge-storage-2:/var/log# journalctl -xf
-- Logs begin at Fri 2021-03-05 03:44:21 CST. --
Mar 05 15:29:23 edge-storage-2 k3s[2952]: I0305 15:29:23.135884    2952 log.go:172] http: TLS handshake error from [::1]:58352: EOF
Mar 05 15:29:23 edge-storage-2 k3s[2952]: I0305 15:29:23.636760    2952 log.go:172] http: TLS handshake error from [::1]:58362: EOF
Mar 05 15:29:24 edge-storage-2 k3s[2952]: I0305 15:29:24.172030    2952 log.go:172] http: TLS handshake error from [::1]:58372: EOF
Mar 05 15:29:24 edge-storage-2 k3s[2952]: I0305 15:29:24.636279    2952 log.go:172] http: TLS handshake error from [::1]:58382: EOF
Mar 05 15:29:25 edge-storage-2 k3s[2952]: I0305 15:29:25.136169    2952 log.go:172] http: TLS handshake error from [::1]:58394: EOF
Mar 05 15:29:25 edge-storage-2 k3s[2952]: I0305 15:29:25.636261    2952 log.go:172] http: TLS handshake error from [::1]:58404: EOF
Mar 05 15:29:26 edge-storage-2 k3s[2952]: I0305 15:29:26.136012    2952 log.go:172] http: TLS handshake error from [::1]:58414: EOF
Mar 05 15:29:26 edge-storage-2 k3s[2952]: I0305 15:29:26.636080    2952 log.go:172] http: TLS handshake error from [::1]:58424: EOF
Mar 05 15:29:27 edge-storage-2 k3s[2952]: I0305 15:29:27.137007    2952 log.go:172] http: TLS handshake error from [::1]:58434: EOF
Mar 05 15:29:27 edge-storage-2 k3s[2952]: I0305 15:29:27.638053    2952 log.go:172] http: TLS handshake error from [::1]:58444: EOF
Mar 05 15:29:28 edge-storage-2 k3s[2952]: I0305 15:29:28.138731    2952 log.go:172] http: TLS handshake error from [::1]:58454: EOF
Mar 05 15:29:28 edge-storage-2 k3s[2952]: I0305 15:29:28.639068    2952 log.go:172] http: TLS handshake error from [::1]:58464: EOF
Mar 05 15:29:29 edge-storage-2 k3s[2952]: I0305 15:29:29.139376    2952 log.go:172] http: TLS handshake error from [::1]:58474: EOF
Mar 05 15:29:29 edge-storage-2 k3s[2952]: I0305 15:29:29.639507    2952 log.go:172] http: TLS handshake error from [::1]:58486: EOF
Mar 05 15:29:30 edge-storage-2 k3s[2952]: I0305 15:29:30.139691    2952 log.go:172] http: TLS handshake error from [::1]:58496: EOF
Mar 05 15:29:30 edge-storage-2 k3s[2952]: I0305 15:29:30.639479    2952 log.go:172] http: TLS handshake error from [::1]:58506: EOF
Mar 05 15:29:31 edge-storage-2 k3s[2952]: I0305 15:29:31.139236    2952 log.go:172] http: TLS handshake error from [::1]:58516: EOF
Mar 05 15:29:31 edge-storage-2 k3s[2952]: I0305 15:29:31.639029    2952 log.go:172] http: TLS handshake error from [::1]:58526: EOF
Mar 05 15:29:32 edge-storage-2 k3s[2952]: I0305 15:29:32.138763    2952 log.go:172] http: TLS handshake error from [::1]:58536: EOF
Mar 05 15:29:32 edge-storage-2 k3s[2952]: I0305 15:29:32.639501    2952 log.go:172] http: TLS handshake error from [::1]:58546: EOF
Mar 05 15:29:33 edge-storage-2 k3s[2952]: I0305 15:29:33.140839    2952 log.go:172] http: TLS handshake error from [::1]:58558: EOF
Mar 05 15:29:33 edge-storage-2 k3s[2952]: I0305 15:29:33.639566    2952 log.go:172] http: TLS handshake error from [::1]:58568: EOF
Mar 05 15:29:34 edge-storage-2 k3s[2952]: I0305 15:29:34.174942    2952 log.go:172] http: TLS handshake error from [::1]:58578: EOF
Mar 05 15:29:34 edge-storage-2 k3s[2952]: I0305 15:29:34.639627    2952 log.go:172] http: TLS handshake error from [::1]:58590: EOF
Mar 05 15:29:35 edge-storage-2 k3s[2952]: I0305 15:29:35.139672    2952 log.go:172] http: TLS handshake error from [::1]:58600: EOF
Mar 05 15:29:35 edge-storage-2 k3s[2952]: I0305 15:29:35.639675    2952 log.go:172] http: TLS handshake error from [::1]:58610: EOF
Mar 05 15:29:36 edge-storage-2 k3s[2952]: I0305 15:29:36.139259    2952 log.go:172] http: TLS handshake error from [::1]:58620: EOF
Mar 05 15:29:36 edge-storage-2 k3s[2952]: I0305 15:29:36.639721    2952 log.go:172] http: TLS handshake error from [::1]:58630: EOF
Mar 05 15:29:37 edge-storage-2 k3s[2952]: I0305 15:29:37.140466    2952 log.go:172] http: TLS handshake error from [::1]:58640: EOF
Mar 05 15:29:37 edge-storage-2 k3s[2952]: I0305 15:29:37.640286    2952 log.go:172] http: TLS handshake error from [::1]:58650: EOF
Mar 05 15:29:38 edge-storage-2 k3s[2952]: I0305 15:29:38.140306    2952 log.go:172] http: TLS handshake error from [::1]:58660: EOF
Mar 05 15:29:38 edge-storage-2 k3s[2952]: I0305 15:29:38.640280    2952 log.go:172] http: TLS handshake error from [::1]:58670: EOF

![image](https://user-images.githubusercontent.com/25924966/110087819-1c36fc80-7dcf-11eb-9c16-56d746abf2da.png)

### Expected behavior
NO TLS error
### Actual behavior
TLS error

**Comment by guanxingfeng** [comment]
I saw someone also mentioned same error log in Rancher，I don't know where the problem is.
![image](https://user-images.githubusercontent.com/25924966/110090019-c57ef200-7dd1-11eb-9ffc-954acf0afe55.png)

**Comment by brandond** [comment]
That just means you have a process running locally that is connecting and disconnecting rapidly. There's no way to tell from the logs what it is; you'll need to look at the local process list to figure it out.

**Comment by guanxingfeng** [comment]
@brandond
