### ISSUE TITLE
Flannel wireguard backend writes files to /

### ISSUE THREAD

**Issue by iioragg** [k3s-io/k3s#3031]
Hi everyone,

I'm facing an issue with the setup of k3s using wireguard as flannel backend. 
In particular, my node have openSUSE MicroOS ( filesystem read-only ). 
During the initialization of the k3s service, the flannel failed to init and the logs are : 

```
k3s[9036]:  extension.go:88] Ran command: wg genkey | tee privatekey | wg pubkey
k3s[9036]:  Output: tee: privatekey: Read-only file system
```

I couldn't find the path where this command is run, how can I find this path?
Has anyone had a similar problem?
Thanks

**Comment by brandond** [comment]
That's actually a good question. On the server, it's run with a working directory of /var/lib/rancher/rke2/server. On the agent it's whatever the working directory was when the process was started, so probably / for systemd units.

**Comment by davidnuzik** [comment]
@manuelbuil @brandond does this need a backport? It's in 1.21.2 milestone but it's in master (not in 1.21 release branch)

**Comment by brandond** [comment]
I think it does merit a backport; I'll open an issue.

I would like to have QA specifically test this as an upgrade operation though; I'm not sure how wireguard handles nodes rekeying. As far as I can tell they currently generate new keys every time flannel starts so it SHOULD be handled correctly but I want to validate that.

**Comment by rancher-max** [comment]
#### Validated on master branch using commitid: `88f95ec409eeb6a2d1330a836b0d1b960a3b5c31`

- Fresh install writes on both server and agent nodes to:
```
...
extension.go:87] Ran command: wg genkey | tee /var/lib/rancher/k3s/agent/etc/flannel/privatekey | wg pubkey
...
$ sudo ls /var/lib/rancher/k3s/agent/etc/flannel
net-conf.json  privatekey
```
- Upgrade is successful and writes on both server and agents node to the same above location. Cluster continues to operate as normal.
