### ISSUE TITLE
Replace klipper with haproxy for servicelb

### ISSUE THREAD

**Issue by sandys** [k3s-io/k3s#3032]
**Is your feature request related to a problem? Please describe.**
https://github.com/k3s-io/k3s/issues/852
https://github.com/k3s-io/k3s/discussions/2997
https://github.com/traefik/traefik-helm-chart/issues/380

There are recurring, tons of issues around getting real-ip inside k3s. The only stable solution here is proxy protocol. The issue is that proxy protocol must be INJECTED from the load balancer. klipper does not inject these headers. 

**Describe the solution you'd like**
Haproxy is fairly well tested as a load balancer and has very deep k8s integrations (including a golang SDK) https://github.com/haproxytech/client-native.
It would be great to have the option to replace klipper with haproxy (with proxy protocol turned on by default).

Nothing else changes - Traefik remains as the ingress as such. Traefik supports reading proxy protocol headers (not injecting them), so it will interoperate well 

**Additional context**
Haproxy can be deployed in daemonset mode - https://github.com/haproxytech/kubernetes-ingress/blob/4700559761b4ac365acda6579902872320ae1645/deploy/haproxy-ingress-daemonset.yaml

In addition, haproxy supports being deployed outside the kubernetes cluster - https://www.haproxy.com/blog/announcing-haproxy-kubernetes-ingress-controller-1-5/#external-ingress-controller

**Comment by xiaods** [comment]
@sandys  This would make a great PR!

**Comment by jaydrogers** [comment]
Just wanted to chime in and say thank you for this discussion. I read @sandys comment (https://github.com/k3s-io/k3s/discussions/2997#discussioncomment-449838) and he had some interesting points.

From my perspective, I would love to see a K3s suggested way for restoring the origin IP address.

I think it's an important thing that a lot of people will want (especially for logging, security, etc).

I totally understand @brandond's comment:

> Anyone that's trying to configure their ingress to pass through the source address is probably well into the "needs to customize things a bit" space

I just want to make sure I keep my stack as "K3s accepted" as possible. I love the flexibility, but I don't want to customize it so much to the point where it's "not K3s" anymore.

Seeing an official statement in how to handle the origin IP address in the documentation would go a long way.

**Comment by Ognian** [comment]
Well I ran into this issue too. I concentrated on so many things, that I didn't noticed that the source IP is not forwarded until the cluster was already 6 months in production :-). This was something I simply expected from k3s.
Unfortunately stale bot marked this as closed, which is a pitty, since I would like to have a resolution in either way:
- replace clipper with haproxy (or something different)
- at least document this behavior on a prominent place with some instructions on how to replace klipper with i.e. haproxy

@ibuildthecloud what would you recommend?

Thanks
Ognian

**Comment by sandys** [comment]
@Ognian so this is very tricky right now. We do run with source ip in production and we have taken two broad directions.

One is to remove klipper and traefik and just have haproxy ingress. This is fairly non standard and ur uptime management is ur own (since the lb is out of the picture).

The other way is some less-documented way we found by searching a lot on issues here. I think Calico is a pre-requisite for that. That one is better if ur running a high-availability setup. I would struggle to tell u how we did it. I think it was fairly black magic and we will never update k3s for fear of breaking it.

Even I would pray to the k3s gods to give us an out of the box answer here. This is genuinely a big issue for lots of people.

**Comment by jaydrogers** [comment]
> I didn't noticed that the source IP is not forwarded until the cluster was already 6 months in production

Ouch! That is a bummer!

**Update from our end:**

- I spent $1,000 in learning resources on Kubernetes and about 250+ hours
- K3s was by far my favorite way to self host Kubernetes
- The issue of not being able to get the origin IP address easily was a "show stopper" for me
- I went to Docker Swarm instead (_wayyyyyy_ easier for simple setups)

Keeping my eye on the K3s project for Origin IP support out of the box (without an external load balancer or working against how K3s is shipped).

**Comment by brandond** [comment]
As mentioned above, ServiceLB is just intended to be a very minimal zero-configuration Service controller for users that want to quickly prototype things that expect to be able to use Services with type=LoadBalancer. It has almost no features and is intentionally easy to disable and replace with an alternative LB controller such as kube-vip or metallb for production use. Most Ingress controllers can also be set up as a NodePort Deployment where the controller binds directly to the address on the node so as to avoid NATing and hairpin routing between nodes.

**Comment by figassis** [comment]
What is working for me is having an external HAProxy LB with proxy protocol enabled, and using Nginx as ingress, and enabling proxy protocol there as well. ServiceLB forwards Haproxy traffic to Nginx and I get proper client IPs from nginx controller.

But I also see a bunch of error while reading proxy protocol headers coming from ServiceLB pod, which I think it's some health check from ServiceLB that does not support proxy protocol. Everything works so far, so not sure what consequence the failing ServiceLB health checks will cause.
