### ISSUE TITLE
Allow specifying custom controllers in the server config

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#3034]
Today, there is no way to add custom controllers to K3s. We should add the ability to specify custom controllers to be run (so that RKE2 can define its own controllers), very similar to the `startupHook` strategy.

**Comment by Oats87** [comment]
This is needed for https://github.com/rancher/rke2/issues/745

**Comment by brandond** [comment]
It would be nice if we used the same mechanism to sequence the startup of the existing K3s embedded controllers; they're currently scattered around the codebase and don't necessarily all use the same informer caches.

**Comment by Oats87** [comment]
> It would be nice if we used the same mechanism to sequence the startup of the existing K3s embedded controllers; they're currently scattered around the codebase and don't necessarily all use the same informer caches.

I think that would be a great goal, but is a bit out of scope given the existing timeline we have for adding this new NetworkPolicy controller.

**Comment by dweomer** [comment]
> > It would be nice if we used the same mechanism to sequence the startup of the existing K3s embedded controllers; they're currently scattered around the codebase and don't necessarily all use the same informer caches.
> 
> I think that would be a great goal, but is a bit out of scope given the existing timeline we have for adding this new NetworkPolicy controller.

Would love a proper internals lifecycle design.

**Comment by rancher-max** [comment]
Based on the PRs, this should not functionally change k3s, so closing without strict validation here. Validated in rke2 on all 3 release branches.
