### ISSUE TITLE
Duplicated lines on pkg/apiaddresses/controller.go and pkg/agent/tunnel.go

### ISSUE THREAD

**Issue by xiaods** [k3s-io/k3s#3036]
**Environmental Info:**
K3s Version:  upstream

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

there are duplicated lines for two files.  getAddresses func in pkg/apiaddresses/controller.go and pkg/agent/tunnel.go

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

remove duplicated lines

**Actual behavior:**

two function with same code.

**Additional context / logs:**

**Comment by brandond** [comment]
Feel free to put in a PR!
