### ISSUE TITLE
Add documentation for etcd-only support

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3044]
Add documentation to reflect etcd-only support functionality #2635

Include various configurations
1. node with etcd-only role
2. node with all roles
3. node with no etcd
4. disable roles

Note:
On a node with all roles, etcd can be disable by passing disable-etcd: true in config.yaml.
To enable etcd on the same node back again, remove the disable-etcd entry from the config.yaml and restart k3s as opposed to setting disable-etcd: false (which aligns with removing the --disable-etcd flag in the CLI)

**Comment by xiaods** [comment]
also need this documents for use etcd with k3s

**Comment by davidnuzik** [comment]
@ShylajaDevadiga please review PR at your next availability.
