### ISSUE TITLE
High Availability with an External DB with CockroachDB is not working

### ISSUE THREAD

**Issue by alifpay** [k3s-io/k3s#3056]
**Environmental Info:**
K3s Version: 
k3s v1.20.4+k3s1

Node(s) CPU architecture, OS, and Version: 
amd64, ubuntu 20, k3s v1.20.4+k3s1

Cluster Configuration:
2 masters

**Describe the bug:**
level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: storage backend is not defined"

**Steps To Reproduce:**
High Availability with an External DB with CockroachDB

CockroachDB is supports lib/pq driver, but k3s is not running with CockroachDB

**Comment by brandond** [comment]
The error message suggests you've entered an invalid datasource driver. Can you confirm that your datastore-endpoint value looks like `postgres://username:password@hostname:port/database-name` - in particular confirm that it is `postgres://` not `postgresql://` or `pq://`or `cockroachdb://` or something else like that?

**Comment by alifpay** [comment]
postgres://username:password@hostname:port/database-name

**Comment by brandond** [comment]
Can you confirm the exact arguments you're passing to K3s? Redact the password if necessary. The error message indicates you're using an incorrect scheme.

**Comment by alifpay** [comment]
v1.20.6+k3s1

postgres://root@127.0.0.1:26257/k3sdb?sslmode=disable

this is working
