### ISSUE TITLE
k3s fails with unknown flag: --event-ttl

### ISSUE THREAD

**Issue by varac** [k3s-io/k3s#3057]
**Environmental Info:**
K3s Version: 

```
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Node(s) CPU architecture, OS, and Version: 

`Linux 706-events-rentention 5.4.22 #2 SMP Sun Oct 11 09:03:08 UTC 2020 x86_64 GNU/Linux`

Cluster Configuration:

* single-node cluster, master and worker on the same host

**Describe the bug:**

I'd like to increase the time k8s events are retained. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ show the `--event-ttl` option for this:

```
--event-ttl duration Default: 1h0m00 
   Amount of time to retain events.
```

So I try to start k3s with `--kubelet-arg=event-ttl="48h0m0s"`

**Steps To Reproduce:**

- Download k3s from github release page
- Try to start k3s with `k3s server --kubelet-arg=event-ttl="48h0m0s"`

**Expected behavior:**

The server should start and the event retention time is increased to 48h.

**Actual behavior:**

k3s fails to start.

**Additional context / logs:**

It fails to start with 

```
time="2021-03-12T10:50:19.683434517Z" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/a6857be08414815b83ca6b960373efd98879a0b286fb24cb62b1c5fdbf3a8cb5/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --event-ttl=48h0m0s --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=706-events-rentention --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-labels= --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
...
F0312 10:50:19.689944   21834 server.go:155] unknown flag: --event-ttl
```

Here's the whole log: 
[k3s.err.log](https://github.com/k3s-io/k3s/files/6129509/k3s.err.log)

**Comment by mrtndwrd** [comment]
`--event-ttl` is not an argument of the [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) but of the [kube-apiserver](https://v1-16.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). Can you try using that?

**Comment by brandond** [comment]
As @mrtndwrd said, you're passing an apiserver arg to the kubelet. Is there any reason in particular you're not using --kube-apiserver-arg?

**Comment by varac** [comment]
Ack, sorry for the noise - works now!
