### ISSUE TITLE
K3S execution affecting Docker containers network

### ISSUE THREAD

**Issue by bgarber** [k3s-io/k3s#3058]
**Environmental Info:**
K3S Version: 
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Linux imladris 5.3.18-24.52-default #1 SMP Tue Mar 2 13:15:25 UTC 2021 (c35b124) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: only one master node

**Describe the bug:**
When building a container image with `docker build`, if the K3S daemon is running, sometimes I get the following message when building certain layers of the container:
```
Step 5/11 : RUN http_proxy=$http_proxy zypper install -y coreutils && zypper clean --all
 ---> Running in a555afc882d3
Building repository 'Non-OSS Repository' cache [....done]
Building repository 'Main Repository' cache [....done]
Warning: File 'repomd.xml' from repository 'Main Update Repository' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'Main Update Repository' is unsigned, continue? [yes/no] (no): no
Error building the cache:
[repo-update|http://download.opensuse.org/update/leap/15.1/oss/] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
 - Can't provide /repodata/repomd.xml

Warning: Skipping repository 'Main Update Repository' because of the above error.
```
If I stop K3S, flush the iptables rules, and restart Docker daemon, everything works fine. Noteworthy is that if I keep repeating the `docker build`, eventually it will work.

**Steps To Reproduce:**

- Installed Docker through Zypper (SUSE Linux)
- Installed K3s: 
   ```
   curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" K3S_KUBECONFIG_MODE="644" sh -s -
   ```
- Tried to build any container image with `docker build`.

**Expected behavior:**
Containers should be correctly built. K3S iptables rules should not affect Docker installed rules. Or a limitation should be warned to not have both in the same machine.

**Actual behavior:**
Steps with `zypper install` fail while trying to communicate with the package repository, failing the container creation.

**Additional context / logs:**

**Comment by brandond** [comment]
Which part of this is the unique error, can you show example output from a successful run? Are you saying that k3s is somehow making `repomd.xml` from one of your repos come back as unsigned?

**Comment by bgarber** [comment]
Hi @brandond! Thank you for your quick reply!
What I'm saying is that if K3S daemon is running concurrently with Docker daemon, looks like any communication with the external world from inside a container running in Docker does not work properly. I have to stop the K3S daemon (`sudo systemctl stop k3s`), flush iptables rules (`sudo iptables -F`) and restart Docker (`sudo systemctl restart docker`) to get a container running with Docker to work correctly. And I do not mean a pod using Docker; I really have the 2 (K3S and Docker) executing separately on the same machine.

**Comment by xiaods** [comment]
> Hi @brandond! Thank you for your quick reply!
> What I'm saying is that if K3S daemon is running concurrently with Docker daemon, looks like any communication with the external world from inside a container running in Docker does not work properly. I have to stop the K3S daemon (`sudo systemctl stop k3s`), flush iptables rules (`sudo iptables -F`) and restart Docker (`sudo systemctl restart docker`) to get a container running with Docker to work correctly. And I do not mean a pod using Docker; I really have the 2 (K3S - with containerd - and Docker) executing separately on the same machine.

do you like to try to switch to another NIC to route the network

**Comment by bgarber** [comment]
Hello everyone. I'm really sorry for the delayed response. I was just trying to reproduce again the issue, but it looks like it just vanished. Not sure exactly what changed, but if I hit the problem again, I'll let you know. Thanks!

**Comment by xiaods** [comment]
> Hello everyone. I'm really sorry for the delayed response. I was just trying to reproduce again the issue, but it looks like it just vanished. Not sure exactly what changed, but if I hit the problem again, I'll let you know. Thanks!

please close it asap.
