### ISSUE TITLE
use mysql5.7 when kine data over 100000, k3s sql very slow, causes startup failure

### ISSUE THREAD

**Issue by sewenc** [k3s-io/k3s#3063]
i find error logs , all api is timeout

i use sql find full sql, 
```
show full processlist ;
```

Randomly find a SQL，this sql executed separately cost 42s
```sql
SELECT (
           SELECT rkv.id
           FROM kine rkv
           ORDER BY rkv.id
               DESC LIMIT 1), COUNT(c.theid)
FROM (
         SELECT (
                    SELECT rkv.id
                    FROM kine rkv
                    ORDER BY rkv.id
                        DESC LIMIT 1), (
                    SELECT crkv.prev_revision
                    FROM kine crkv
                    WHERE crkv.name = 'compact_rev_key'
                    ORDER BY crkv.id DESC LIMIT 1), kv.id as theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value
         FROM kine kv
                  JOIN (
             SELECT MAX(mkv.id) as id
             FROM kine mkv
             WHERE
                     mkv.name LIKE '/registry/rolebindings/%'

             GROUP BY mkv.name) maxkv
                       ON maxkv.id = kv.id
         WHERE
             (kv.deleted = 0 OR 0)
         ORDER BY kv.id ASC

     ) c
```

**Comment by sewenc** [comment]
how to fix it?

**Comment by brandond** [comment]
It appears you skipped the issue template - what version of k3s are you using? How many servers are in your cluster?

**Comment by sewenc** [comment]
> It appears you skipped the issue template - what version of k3s are you using? How many servers are in your cluster?

sorry , k3s version:  v1.18.3-k3s1  ， There are 20 servers

**Comment by brandond** [comment]
1. 20 servers? All of them actual servers, not just agents? That is probably way more than you need, and is likely contributing to the problem. I would recommend no more than 2-4 servers when using an external SQL datastore.

2. Please upgrade to a newer K3s release. There have been some significant changes to the Kine SQL datastore layer that should prevent the datastore from growing out of control. An excessive number of servers accessing the datastore at once was one of the potential triggers for this.

**Comment by sewenc** [comment]
> 1. 20 servers? All of them actual servers, not just agents? That is probably way more than you need, and is likely contributing to the problem. I would recommend no more than 2-4 servers when using an external SQL datastore.
> 2. Please upgrade to a newer K3s release. There have been some significant changes to the Kine SQL datastore layer that should prevent the datastore from growing out of control. An excessive number of servers accessing the datastore at once was one of the potential triggers for this.

sorry，is only one server, It manages 20 servers
I'm trying to upgrade， thanks!
