### ISSUE TITLE
Ephemeral storage directory

### ISSUE THREAD

**Issue by BeardyC** [k3s-io/k3s#3076]
**Environmental Info:**
K3s Version: 

```
k3s version v1.17.2+k3s1 (cdab19b0)
```
Node(s) CPU architecture, OS, and Version: 

```
Linux svwrs60003 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

4 masters, 8 agents

K3s arguments:
```
ExecStart=/opt/app/mdx/MdxCache1/k3s/bin/k3s \
    agent \
        '--server' \
        'https://svwrs60001:6443' \
        '--token' \
        'token' \
        '--data-dir' \
        '/opt/app/mdx/MdxCache1/k3s-data' \
```

**Describe the bug:**
We've set up our cluster to use a different data dir as our PRD env the ```var``` directory is only a few GBs in size. 
We're running into issues where any pods that have emptyDir storage mounted are filling it up quite quickly as its writing into ```/var/lib/kubelet/pods/```. 
Is there something I'm missing or is there a way to configure where ephemeral data is written to? If not would the solution be to just symlink ```/var/lib/kubelet/``` to our original data directory ```/opt/app/mdx/MdxCache1/k3s-data```?

**Comment by brandond** [comment]
I probably wouldn't link /var/lib/kubelet/ directly into your data-dir, but either putting it on a dedicated partition or symlinking it into subdirectory on a different partition is probably your best bet.
