### ISSUE TITLE
Allow CoreDNS image registry override in the original manifest.

### ISSUE THREAD

**Issue by dev-ninja-ops** [k3s-io/k3s#3093]
**Is your feature request related to a problem? Please describe.**
I work in an airgapped environments, and I have to change the tagging of the Image to the one appears in the original manifest, I want to pull directly from the my private docker registry.

**Describe the solution you'd like**
Something like this: "--coredns-image=<registry_url>/rancher/coredns-coredns:1.8.0" passed to binary would probably do the trick, also should be pretty easy feature to implement.
only needs to add an extra placeholder to the original coredns manifest file.

**Describe alternatives you've considered**
I was creating an extra manifest overwritting the original image, but this causes issues, and the manifests are being reapplied every couple of minutes.

**Additional context**
None.
Thanks.

**Comment by brandond** [comment]
The coredns image is included in the airgap image artifact. The recommended way to get K3s working in airgapped environments is to place the airgap tarball on all nodes, or configure a registry mirror using registries.yaml.

If you still want to customize the coredns manifest, you might look at the thread at https://github.com/k3s-io/k3s/issues/1328#issuecomment-577448534

**Comment by dev-ninja-ops** [comment]
Hi,
Thanks for the comment.

I understand this, and I also know this thread, the problem is that if I set up coredns myself, it requires me to understand who the nodes are, their hostnames, their addresses, etc. Then I will have to produce the configmap myself with these values. I mean I'll have to do processes that k3s does for me. Do you know a solution to this? One I still be able to only overwrite a specific value within the manifest?

Thanks

**Comment by brandond** [comment]
If you want to customize any of the coredns deployment, you currently need to customize all of it. I agree that it's not great.

Does just dropping the airgap images tarball, or configuring a registry mirror using registries.yaml, not work for you?

**Comment by dev-ninja-ops** [comment]
Hi,

Thanks again for the comment,

Not really, 
The way it works right now is that I have already done full automation to set up an entire infrastructure, as part of the infrastructure I am setting up a central Repository server, which contains the k3s images in addition to another full of other packages for package managers like npm, maven etc. Now the point is that I am setting up a lot of such mobile environments, and I have an existing and orderly process for synchronizing dockers between the various repositories and the different networks, and I dont wanna break the current processes I already have(which by the way works great) for syncing dockers between repositories because it is mainly based on semantic versioning and I have custom self-made applications that uses those repositories api's to know what dockers and in which versions I currently have. now every image that synced into this environment gets retagged to meet our organizational standard.

long-story-short every image gets different tag, I cannot use tarballs, and the registries.yaml file needs to have the private registry username & password + tls keys path which is a big no-no in this type of deployment.

In any case, I have developed in my organization a library, which flatten YAML files and treats them as environment variables, so I can use any existing manifest file, and edit it while running without knowing what it looks like, and without using ugly placeholders. I think this can be very useful in the case of k3s when you put manifests and want to give dynamic editing capability to any existing manifest file. think about it.

Thanks again!

**Comment by defo89** [comment]
I would also want to vote for ability to override default DockerHub registry. One reason is introduced rate limiting but our reason to switch is better reachability of AWS ECR public registry in some of regions. In our case override is needed for `rancher/coredns-coredns` and `rancher/metrics-server`

**Comment by brandond** [comment]
The rancher org in Docker Hub is exempted from rate-limiting. You will never be rate-limited pulling `rancher/coredns-coredns`.

**Comment by defo89** [comment]
Good to hear this. Unfortunately this does not solve reachability issues of DockerHub in some regions e.g. China (image layer pulls are going through Cloudflare CDN which is leveraged by DockerHub but blocked there).
