### ISSUE TITLE
traefik always restarting

### ISSUE THREAD

**Issue by Leon-pan** [k3s-io/k3s#3098]
**Environmental Info:**
K3s Version: 
k3s version v1.19.7+k3s1 (5a00e38d)

Node(s) CPU architecture, OS, and Version: 
Linux k8s-1.prod 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
NAME           STATUS   ROLES    AGE    VERSION
k8s-2.prod   Ready    master   100d   v1.19.7+k3s1
k8s-1.prod   Ready    master   100d   v1.19.7+k3s1

**Describe the bug:**
Cluster traefik always restarting,because Liveness probe failed.But I don't know why it is happened, it just did.

**Steps To Reproduce:**

- Installed K3s: 
curl -sfL https://get.k3s.io | sh -

**Additional context / logs:**

![Snipaste_2021-03-19_14-10-07](https://user-images.githubusercontent.com/37100346/111739968-dc880e80-88be-11eb-83de-163f17fb198c.png)
![Snipaste_2021-03-19_14-10-17](https://user-images.githubusercontent.com/37100346/111739975-e01b9580-88be-11eb-8fce-c14cd81a5a25.png)
![Snipaste_2021-03-19_14-11-41](https://user-images.githubusercontent.com/37100346/111739985-e3af1c80-88be-11eb-8248-e236f8d0806c.png)

**Comment by Leon-pan** [comment]
![image](https://user-images.githubusercontent.com/37100346/111740111-22dd6d80-88bf-11eb-8bfe-c847cb9b8e34.png)

**Comment by Leon-pan** [comment]
By the way,the cluster and other services still working.

**Comment by brandond** [comment]
Can you attach the actual pod logs? It's hard to work with a couple lines from a screenshot.

**Comment by Leon-pan** [comment]
> Can you attach the actual pod logs? It's hard to work with a couple lines from a screenshot.

{"level":"info","msg":"Using TOML configuration file /config/traefik.toml","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"No tls.defaultCertificate given for https: using the first item in tls.certificates as a fallback.","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Traefik version v1.7.19 built on 2019-10-28_02:07:32PM","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v1.7/basics/#collected-data\n","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Preparing server http \u0026{Address::80 TLS:\u003cnil\u003e Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:true ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc00061eac0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Preparing server https \u0026{Address::443 TLS:0xc000687170 Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:true ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc00061eae0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Preparing server prometheus \u0026{Address::9100 TLS:\u003cnil\u003e Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:false ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc00061eaa0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Starting provider configuration.ProviderAggregator {}","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Starting server on :80","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Starting server on :443","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Starting server on :9100","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":{\"IP\":\"\",\"Hostname\":\"\",\"PublishedService\":\"kube-system/traefik\"},\"ThrottleDuration\":0}","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"ingress label selector is: \"\"","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Creating in-cluster Provider client","time":"2021-03-19T06:42:39Z"} 
{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress does not exist","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Server configuration reloaded on :9100","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Server configuration reloaded on :80","time":"2021-03-19T06:42:39Z"} 
{"level":"info","msg":"Server configuration reloaded on :443","time":"2021-03-19T06:42:39Z"} 
{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress does not exist","time":"2021-03-19T06:42:40Z"} 
{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress does not exist","time":"2021-03-19T06:42:40Z"} 
{"level":"info","msg":"Server configuration reloaded on :80","time":"2021-03-19T06:42:41Z"} 
{"level":"info","msg":"Server configuration reloaded on :443","time":"2021-03-19T06:42:41Z"} 
{"level":"info","msg":"Server configuration reloaded on :9100","time":"2021-03-19T06:42:41Z"} 
{"level":"info","msg":"I have to go...","time":"2021-03-19T06:43:18Z"} 
{"level":"info","msg":"Stopping server gracefully","time":"2021-03-19T06:43:18Z"} 
{"level":"info","msg":"Server stopped","time":"2021-03-19T06:43:18Z"} 
{"level":"info","msg":"Shutting down","time":"2021-03-19T06:43:18Z"}

**Comment by Leon-pan** [comment]
Readiness probe failed: Get "http://10.42.0.68:80/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by brandond** [comment]
Are you trying to use this with Rancher? If so, did you install cert-manager first? It looks like the certificate secret isn't getting created by cert-manager.

`{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress does not exist","time":"2021-03-19T06:42:40Z"} `

**Comment by Leon-pan** [comment]
> Are you trying to use this with Rancher? If so, did you install cert-manager first? It looks like the certificate secret referenced by the Rancher ingress isn't getting created by cert-manager.
> 
> `{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress does not exist","time":"2021-03-19T06:42:40Z"} `

Besause I hava a CA cert,so I did't install cert-manager.I use ingress.tls.source=secret to install rancher.
and I use to import my CA cert to cluster
`kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key`
