### ISSUE TITLE
k3s Agent seems to attempt to start the worker twice- and blocks itself from using its own ports.

### ISSUE THREAD

**Issue by Bjohnson131** [k3s-io/k3s#3101]
### K3s Version: 
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Linux ubuntu 5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
Attempting to connect 1 worker to a cluster with 1 master.

### **Describe the bug:**
While attempting to connect a worker to a master, the k3s agent seems to try to bind many of the same ports twice, resulting in some self-sabotage. The agent will crash and there will be some orphaned processes left.

### **Steps To Reproduce:**
- Installed K3s via web script
- ran `sudo systemctl stop k3s.service` (Note that `systemctl disable k3s.service` has also been attempted)
- observe using  ss -tuwp that the only open ports are SSH ports.
- ran the agent with the server, token, and v flags
- The script produces a lot of errors pertaining to ports already being bound.

### **Expected behavior:**
K3s starts without double-binding any ports it uses.

### **Actual behavior:**
k3s attempts to double-bind most ports it uses.

### **Additional context / logs:**
A small log snippet (full logs attached)

```
I0320 03:36:41.208026 2174837 server.go:1177] Started kubelet
I0320 03:36:41.213797 2174837 server.go:148] Starting to listen on 0.0.0.0:10250
I0320 03:36:41.216154 2174837 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
I0320 03:36:41.216762 2174837 server.go:410] Adding debug handlers to kubelet server.
E0320 03:36:41.218684 2174837 cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs": unable to find data in memory cache.
E0320 03:36:41.218782 2174837 kubelet.go:1292] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
F0320 03:36:41.218801 2174837 server.go:162] listen tcp 0.0.0.0:10250: bind: address already in use

```

[server.log](https://github.com/k3s-io/k3s/files/6174830/server.log)

**Comment by brandond** [comment]
Are you trying to run the server and agent on the same host?

**Comment by Bjohnson131** [comment]
> Are you trying to run the server and agent on the same host?

No, the server and host do have the same `uname -a` output, and the master and node both have the same version of k3s.

**Comment by brandond** [comment]
I am confused as to how they are binding to the same ports if they're not on the same host?

**Comment by Bjohnson131** [comment]
> I am confused as to how they are binding to the same ports if they're not on the same host?

I am as well. Is it possible for `k3s agent` to spawn a `k3s server` process?

**Comment by brandond** [comment]
Just so I understand what you're doing, you're stopping `k3s server` on a host, and then trying to start `k3s agent` on that same host afterwards?

**Comment by Bjohnson131** [comment]
> Just so I understand what you're doing, you're stopping `k3s server` on a host, and then trying to start `k3s agent` on that same host afterwards?

Yes, the script by default builds and runs k3s.service, and I stop and disable that service before I run k3s agent. I also kill any k3s processes that are running in the background.

**Comment by Bjohnson131** [comment]
@brandond  So I'm not the brightest...

## SOLVED:

 make sure that your /etc/hostname of your master and node are separate values.
