### ISSUE TITLE
I don't get any errors but is not installed on my machine

### ISSUE THREAD

**Issue by falahatiali** [k3s-io/k3s#3102]
I want to install k3s on a ubuntu 20.04 machine with 2G ram and 2 core CPU. I used following command and I get following message but after that I dont have installed version on my machine. I repeat this step more than 10 times and  I get same result.

```
root@kuber:~# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.4+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.20.4+k3s1/sha256sum-amd64.txt
```

**Comment by brandond** [comment]
You are apparently not able to access github. What happens if you do:
`curl -vsL https://github.com/k3s-io/k3s/releases/download/v1.20.4+k3s1/sha256sum-amd64.txt`
