### ISSUE TITLE
Shorter unique tags

### ISSUE THREAD

**Issue by derekyle** [k3s-io/k3s#311]
As I'm sure many are aware, kubernetes uses unique and random tags on the end of pods and nodes and other generated objects.

So when I take a look at my nodes I see something like "my-node-name-c5410167-2m2s" and pods like my-pod-name-75d41dbf2d-6wolp.

I understand the need for unique names on the different deployments and pods. But this does make it difficult to work with. For example, deleting a pod requires either some quick shell foo or copy pasting. And especially during setup and testing and before things are more scripted, it would be great if the generated unique id's were a bit easier to work with. Even a 3 character alphanumeric string would give you 46,656 uniques which should be way more than anyone would ever need on k3s (and probably 99% of anyone using k8s).

"kubectl drain my-node-3y7-23r" is so much easier than "kubect drain my-node-c5410167-2m2s" and even possible to hold in my memory for a bit. Shorter unique ids are also a lot easier to compare at a glance and skim through a list looking for matches.

Just a thought. I am not familiar with the internals of how these are generated, but I imagine a single method somewhere simply generates them, confirms it is unique and then returns it.

**Comment by brandond** [comment]
Closing due to age.
