### ISSUE TITLE
Running server fails on Arch Linux

### ISSUE THREAD

**Issue by wvxvw** [k3s-io/k3s#3111]
**Environmental Info:**
K3s Version: 
```
k3s -v
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux whatever 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux
```

Cluster Configuration:
None

**Describe the bug:**
Tried running `k3s server`. Received `FATA[2021-03-24T14:32:53.777464359+02:00] flannel exited: operation not supported`.

The error reporting is exceptionally poor, so it's hard to supply any additional details. There was a suspicious entry in the log earlier: `Skipping network policy controller start, ipset save failed: ipset v7.6: Kernel error received: Invalid argument`, but it's hard to tell if it is related. Is this related to `ipset` utility? If so, why isn't this mentioned in requirements?

**Steps To Reproduce:**

Try running `k3s server` on recent Arch Linux

**Expected behavior:**

Server starts.

**Actual behavior:**

Server crashes with unintelligible error message.

```
flannel exited: operation not supported
```

**Additional context / logs:**

```
WARN[2021-03-24T14:32:53.180375132+02:00] Skipping network policy controller start, ipset save failed: ipset v7.6: Kernel error received: Invalid argument 
I0324 14:32:53.227525 2374751 shared_informer.go:247] Caches are synced for crd-autoregister 
I0324 14:32:53.227580 2374751 apf_controller.go:266] Running API Priority and Fairness config worker
I0324 14:32:53.227602 2374751 cache.go:39] Caches are synced for autoregister controller
I0324 14:32:53.227581 2374751 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I0324 14:32:53.227712 2374751 shared_informer.go:247] Caches are synced for cluster_authentication_trust_controller 
I0324 14:32:53.227586 2374751 cache.go:39] Caches are synced for AvailableConditionController controller
INFO[2021-03-24T14:32:53.574049481+02:00] RunPodsandbox for &PodSandboxMetadata{Name:metrics-server-86cbb8457f-2wbqc,Uid:79a8b498-2348-4e0a-8a5f-710cc8e312e7,Namespace:kube-system,Attempt:0,} 
I0324 14:32:53.773058 2374751 kube.go:124] Node controller sync successful
I0324 14:32:53.773186 2374751 vxlan.go:121] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
FATA[2021-03-24T14:32:53.777464359+02:00] flannel exited: operation not supported
```

I read in other tickets mentioning the same error that this may be related to VXLAN support, but, I'm not a networking engineer, and don't even know how to check if such support is present in kernel. Anyways, even if I could, I wish the error message was more relevant: what operation is not supported?

**Comment by brandond** [comment]
The network policy controller and flannel are different components, but you're probably right in that whatever is causing the NPC to fail is also preventing flannel from working.

What happens if you `modprobe ipset` before starting k3s?

**Comment by wvxvw** [comment]
I figured that my kernel was up for update, so there was a discrepancy
between some installed libraries and the loaded kernel modules. A
restart seems to have solved the problem, at least, the server starts
now.

I don't have an ipset module. I do have ip_set, but it doesn't seem to
be loaded by default. I could load it, but the server startup
succeeded, so, I'm going to hold off on that for now, unless I run
into further problems.

Thanks for the reply though.

Oh, and finally. I think that diagnostic of this particular failure
could use some work. Since I'm trying to learn about Kubernetes, I
wouldn't might doing it myself, but I'd appreciate some pointers as to
the nature of the problem.

**Comment by brandond** [comment]
Thanks for the update. I agree that it sounds like an underlying OS issue with some updates that need to be applied.
