### ISSUE TITLE
How to make a complete backup of the k3s cluster data?

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#3114]
When my cluster is down, and cannot be recovered anymore.  I want to create a new cluster and restore the data from the previous cluster.

I want that I can simpley make a data backup of the k3s cluster ,  and use the data to restore a cluster.

**Comment by StarpTech** [comment]
Hi @zengyongjie you can do that but this depends on your storage type (embedded etcd, Postgres). This might help https://github.com/k3s-io/k3s/issues/3174
