### ISSUE TITLE
[svclb-traefik] can't create /proc/sys/net/ipv4/ip_forward: Read-only file system

### ISSUE THREAD

**Issue by dorinclisu** [k3s-io/k3s#3116]
**Environmental Info:**
K3s Version: 
- k3s version v1.20.4+k3s1 (838a906a)
- go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
- `Linux k3s 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- `Linux rk322x-box 5.9.14-rk322x #20.11.3 SMP PREEMPT Fri Dec 11 21:46:56 CET 2020 armv7l GNU/Linux`

Cluster Configuration:
 - 1 master = DigitalOcean droplet (2 GB Memory / 25 GB Disk / FRA1 - Ubuntu 20.04 (LTS) x64)
 - 1 worker = Bare metal ARM machine, (2 GB RAM, Armbian 20.11.6 Buster)

**Describe the bug:**
Cluster works but the load balancer does not. It responds with 404 or 503 to external requests if ingress or service resources do not exist (this is normal), but it responds with 500 if they exist, and the request never reaches the service pods.
This is the logs from every load balancer pod / container:
```
+ trap exit TERM INT
/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '!=' 1 ]
+ iptables -t nat -I PREROUTING '!' -s 10.43.247.127/32 -p TCP --dport 80 -j DNAT --to 10.43.247.127:80
+ iptables -t nat -I POSTROUTING -d 10.43.247.127/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause
```

Running `sysctl net.ipv4.ip_forward` on all nodes shows `net.ipv4.ip_forward = 1` so it's not clear what the problem is.

**Steps To Reproduce:**
- Installed K3s **as root** using the quick start guide, everything on default
- Worker machine is not necessary to reproduce, the load balancer gets stuck even on 1 node cluster, but I added it to rule out possible restrictions related to VPS on DigitalOcean.

**Comment by brandond** [comment]
I think the ip_forward error is not the actual problem. As you noted, ip_forward is already enabled, and the iptables rules are being created successfully.

Can you show the output of `kubectl get service -A -o wide`? Are you able to `curl` any of your target services from the nodes themselves?

Note that the default ServiceLB implementation isn't really suitable for distributed installations - it will assign the nodes IP addresses as the service's external IPs, and in this case the two nodes probably can't actually reach each other at their private IPs?

**Comment by dorinclisu** [comment]
It's true that the worker node does not have the Flannel VXLAN port open, but I'm not planning to use the loadbalancer on all nodes and in any case, the problem is the same with a single node cluster.

I'm not sure what you mean by curling external IP. If you mean ClusterIP, yes, I can curl from the host the services on their clusterIP. Curling on the external IP, in my understanding, goes through the loadbalancer, and this is what I described it's not working. Here's the output you're asking:
```
NAMESPACE              NAME                               TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE    SELECTOR
default                kubernetes                         ClusterIP      10.43.0.1       <none>           443/TCP                      4d4h   <none>
kube-system            kube-dns                           ClusterIP      10.43.0.10      <none>           53/UDP,53/TCP,9153/TCP       4d4h   k8s-app=kube-dns
kube-system            metrics-server                     ClusterIP      10.43.213.134   <none>           443/TCP                      4d4h   k8s-app=metrics-server
kube-system            traefik-prometheus                 ClusterIP      10.43.246.179   <none>           9100/TCP                     4d4h   app=traefik,release=traefik
kubernetes-dashboard   kubernetes-dashboard               ClusterIP      10.43.202.130   <none>           443/TCP                      4d3h   k8s-app=kubernetes-dashboard
kubernetes-dashboard   dashboard-metrics-scraper          ClusterIP      10.43.144.158   <none>           8000/TCP                     4d3h   k8s-app=dashboard-metrics-scraper
gitlab-managed-apps    certmanager-cert-manager-webhook   ClusterIP      10.43.151.133   <none>           443/TCP                      35h    app.kubernetes.io/instance=certmanager,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=webhook,app=webhook
gitlab-managed-apps    certmanager-cert-manager           ClusterIP      10.43.112.60    <none>           9402/TCP                     35h    app.kubernetes.io/instance=certmanager,app.kubernetes.io/name=cert-manager
kube-system            traefik                            LoadBalancer   10.43.247.127   64.227.121.221   80:31618/TCP,443:31275/TCP   4d4h   app=traefik,release=traefik
```

**Comment by dorinclisu** [comment]
Meanwhile I created a sample nginx deployment/service and it works correctly with ingress and LB.
I think the problem is not k3s or the loadbalancer, because my problem only occurs when trying to access kubernetes-dashboard. It seems that the dashboard container only listens on httpS, and somehow this clashes with traefik expecting http.

**Comment by tobunka-git** [comment]
I also encounter this problem. take the taefik service for instance.
`# kubectl get service -A -o wide
NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP                                     PORT(S)                      AGE     SELECTOR
default       kubernetes           ClusterIP      10.43.0.1       <none>                                          443/TCP                      2d23h   <none>
kube-system   kube-dns             ClusterIP      10.43.0.10      <none>                                          53/UDP,53/TCP,9153/TCP       2d23h   k8s-app=kube-dns
kube-system   metrics-server       ClusterIP      10.43.146.109   <none>                                          443/TCP                      2d23h   k8s-app=metrics-server
kube-system   traefik-prometheus   ClusterIP      10.43.224.69    <none>                                          9100/TCP                     2d23h   app=traefik,release=traefik
kube-system   traefik              LoadBalancer   10.43.49.23     192.168.192.180,192.168.192.2,192.168.192.205   80:30373/TCP,443:32464/TCP   2d23h    #app=traefik,release=traefik`

**Comment by tobunka-git** [comment]
I also encounter this problem. Taking the traefik service for an instance
```
# kubectl get service -A -o wide
NAMESPACE     NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP                                     PORT(S)                      AGE     SELECTOR
default       kubernetes           ClusterIP      10.43.0.1       <none>                                          443/TCP                      2d23h   <none>
kube-system   kube-dns             ClusterIP      10.43.0.10      <none>                                          53/UDP,53/TCP,9153/TCP       2d23h   k8s-app=kube-dns
kube-system   metrics-server       ClusterIP      10.43.146.109   <none>                                          443/TCP                      2d23h   k8s-app=metrics-server
kube-system   traefik-prometheus   ClusterIP      10.43.224.69    <none>                                          9100/TCP                     2d23h   app=traefik,release=traefik
kube-system   traefik              LoadBalancer   10.43.49.23     192.168.192.180,192.168.192.2,192.168.192.205   80:30373/TCP,443:32464/TCP   2d23h   app=traefik,release=traefik
```
it should be accessible from all three external IPs displayed, however, it is actually accessible only from the external IP of the node where the pod is running, and not the other two.

I have ran the `kubectl -n kube-system logs svclb-traefik-pl28k lb-port-80` command on each of the three svclb-traefik pods, and the output returned is as follows:
```
+ trap exit TERM INT
/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '!=' 1 ]
+ iptables -t nat -I PREROUTING '!' -s 10.43.49.23/32 -p TCP --dport 80 -j DNAT --to 10.43.49.23:80
+ iptables -t nat -I POSTROUTING -d 10.43.49.23/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause
```
I would like to know, should the service be accessible from the nodes other than the one where is pod is running, or the reported  error related to iptables are negatively impacting the access the service?
