### ISSUE TITLE
failed to get CA certs at https://127.0.0.1:40649/cacerts: 401 Unauthorized

### ISSUE THREAD

**Issue by InsOpDe** [k3s-io/k3s#3119]
**Environmental Info:**
K3s Version: k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
functioning workers: Linux hcloud-cx41-nbg1-8-16-ubuntu20-worker3 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
master: Linux hcloud-ubuntu-20-4gb-internal-master-1 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
host: Linux marcel-desktop 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**Not functioning agent:** DockerImage: `rancher/k3s:v1.18.9-k3s1`

Cluster Configuration:
1 master, 3 workers - *managed by rancher rke*

**Describe the bug:**
I cannot join the master with a k3s-agent even tho the correct ip and token is specified.

When curling the loadbalancer, created by the agent, I get:
```
curl -k https://127.0.0.1:40649/cacerts
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Steps To Reproduce:**
```
docker run --rm  -e K3S_TOKEN="<token from /var/lib/rancher/k3s/server/token>" -e K3S_URL=https://<external-ip>:6443  rancher/k3s:v1.18.9-k3s1 agent
```

**Expected behavior:**
Should successfully join

**Actual behavior:**
See log output below

**Additional context / logs:**
```logs
time="2021-03-26T11:14:57.609596317Z" level=info msg="Starting k3s agent v1.18.9+k3s1 (630bebf9)"
time="2021-03-26T11:14:57.609745747Z" level=info msg="module overlay was already loaded"
time="2021-03-26T11:14:57.609771827Z" level=info msg="module nf_conntrack was already loaded"
time="2021-03-26T11:14:57.609786847Z" level=info msg="module br_netfilter was already loaded"
time="2021-03-26T11:14:57.609816418Z" level=warning msg="failed to write value 1 at /proc/sys/net/ipv4/conf/all/forwarding: open /proc/sys/net/ipv4/conf/all/forwarding: read-only file system"
time="2021-03-26T11:14:57.609835278Z" level=warning msg="failed to write value 1 at /proc/sys/net/ipv4/conf/default/forwarding: open /proc/sys/net/ipv4/conf/default/forwarding: read-only file system"
time="2021-03-26T11:14:57.610148528Z" level=warning msg="failed to write value 1 at /proc/sys/net/ipv6/conf/all/forwarding: open /proc/sys/net/ipv6/conf/all/forwarding: read-only file system"
time="2021-03-26T11:14:57.610200829Z" level=warning msg="failed to write value 1 at /proc/sys/net/ipv6/conf/default/forwarding: open /proc/sys/net/ipv6/conf/default/forwarding: read-only file system"
time="2021-03-26T11:14:57.610231899Z" level=warning msg="failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: read-only file system"
time="2021-03-26T11:14:57.610266509Z" level=warning msg="failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-ip6tables: open /proc/sys/net/bridge/bridge-nf-call-ip6tables: read-only file system"
time="2021-03-26T11:14:57.610836910Z" level=info msg="Running load balancer 127.0.0.1:40649 -> [<external-ip>:6443]"
time="2021-03-26T11:14:57.718154448Z" level=error msg="failed to get CA certs at https://127.0.0.1:40649/cacerts: https://127.0.0.1:40649/cacerts: 401 Unauthorized"
time="2021-03-26T11:14:59.801651297Z" level=error msg="failed to get CA certs at https://127.0.0.1:40649/cacerts: https://127.0.0.1:40649/cacerts: 401 Unauthorized"
time="2021-03-26T11:15:01.881300478Z" level=error msg="failed to get CA certs at https://127.0.0.1:40649/cacerts: https://127.0.0.1:40649/cacerts: 401 Unauthorized
```

**Comment by InsOpDe** [comment]
What I noticed is when I tried to create a server (as described in quickinstall) that I can get the certificate when I curl `https://<server-ip>:6443/cacerts -k` which I cannot do on my current setup.

**Comment by InsOpDe** [comment]
I think the problem is that I am trying to connect a `k3s` agent to a `rke` cluster. If this is not possible that one can close this.

But Id be glad for a hint of how one could connect a node-agent to an existing rke cluster (managed by rancher)

**Comment by brandond** [comment]
K3s agents can only be used with K3s servers. RKE, K3s, and RKE2 are not mutually compatible with each other.
