### ISSUE TITLE
`kubectl get` output is not properly sorted

### ISSUE THREAD

**Issue by howardjohn** [k3s-io/k3s#3120]
**Environmental Info:**
K3s Version: 
$ k3s -v
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Linux arch 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64 GNU/Linux

Cluster Configuration:
1 master

**Describe the bug:**
```
$ kubectl get pods -A
NAMESPACE        NAME                                             READY   STATUS              RESTARTS   AGE
grafana          grafana-fbcdc8cfc-t6qk8                          0/1     ContainerCreating   0          11d
prometheus       prometheus-node-exporter-mg8xl                   1/1     Running             0          11d
default          echo-cb96f8d94-jvfhz                             1/1     Running             0          11d
cert-manager     cert-manager-cainjector-74459fcc56-w2zf2         1/1     Running             0          11d
metallb-system   speaker-nrmlj                                    1/1     Running             0          11d
kube-system      local-path-provisioner-5ff76fc89d-qvtxj          1/1     Running             0          11d
metallb-system   controller-65db86ddc6-6p4hs                      1/1     Running             0          11d
kube-system      coredns-854c77959c-xd2jj                         1/1     Running             0          11d
```

The output here is not in a sorted order. With standard Kubernetes, these are sorted (I think alphabetically by namespace then pod name??). 

**Steps To Reproduce:**
Install k3s, then run `kubectl get pods -A`

**Expected behavior:**
Output is sorted

**Actual behavior:**
Output is not sorted. It is stable though

**Additional context / logs:**
I am not sure if this is a bug or a feature request. I am guessing this is not part of k8s conformance, so maybe its a feature request. With no knowledge of the underlying system, seems like it may be an etcd vs other storage mechanism driving the change?

**Comment by eplightning** [comment]
I compared two k3s clusters, one running on SQLite and second one running etcd.
 
k3s running on etcd returns sorted (by namespace then by name) list of pods, while k3s running on SQLite returns them in some unspecified order.

I don't think Kubernetes API guarantees any order when returning lists and `kubectl` doesn't do any sorting on it's own by default.

**Comment by brandond** [comment]
I don't believe that returning things sorted is guaranteed, nor is it covered by any of the conformance tests.

**Comment by howardjohn** [comment]
If its better to classify this as a feature request rather than a bug that is fine with me. I get that its conformant, but from a user perspective it still gives undesirable behavior, both because it doesn't match "standard" Kubernetes behavior which folks are familiar with, and because IMO the sorted behavior is better

**Comment by zdzichu** [comment]
Standard Kubernetes does not guarantee sorting. What you see is a coincidence, implementation detail.
If you need specific order, `kubectl` has `--sort-by=` switch.
