### ISSUE TITLE
Fail to connect etcd

### ISSUE THREAD

**Issue by AbelTaylor** [k3s-io/k3s#3121]
**Environmental Info:**
K3s Version: 
v1.19.8+k3s1 && v1.20.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04.1 LTS   5.4.0-42-generic

Cluster Configuration:
1 master 2 agents

**Describe the bug:**
etcd client can not connet to etcd

**Steps To Reproduce:**
I saw in the file '/var/lib/rancher/k3s/server/db/etcd/config' there are some connection information about etcd as follows：
"
advertise-client-urls: https://172.16.99.120:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
heartbeat-interval: 500
listen-client-urls: https://172.16.99.120:2379,https://127.0.0.1:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://172.16.99.120:2380
log-outputs:
- stderr
logger: zap
name: cluster-lab-f8d25f47
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
"
so I tried to use etcdctl to connect to etcd,'ETCDCTL_API=3 etcdctl --cacert= "/var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt" --cert="/var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt" --key="/var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key" --endpoints="https://127.0.0.1:2379" snapshot save /opt/etcd. db'
but i get:
"
Error:  context deadline exceeded
"

**Expected behavior:**
connet to etcd successfully

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Is k3s running when you execute the etcdctl command?

**Comment by AbelTaylor** [comment]
> Is k3s running when you execute the etcdctl command?

Yes, it is running, but after I stop k3s and execute the etcdctl command, it shows'Error: dial tcp 127.0.0.1:2379: connect: connection refused'. I compared it. When the k3s service started, 2379 port is open, and the port is closed after stopping k3s.

**Comment by brandond** [comment]
Yes, that's correct. Like the kubelet, apiserver, and other Kubernetes components, etcd runs within the k3s server process and is not available when k3s is stopped. You are welcome to deploy your own etcd server and point k3s at that if you want.

**Comment by AbelTaylor** [comment]
> Yes, that's correct. Like the kubelet, apiserver, and other Kubernetes components, etcd runs within the k3s server process and is not available when k3s is stopped. You are welcome to deploy your own etcd server and point k3s at that if you want.

So, is there any other way to access the embedded etcd?

**Comment by brandond** [comment]
You should be able to access it as normal when k3s is running. Master builds of k3s also include native support for both scheduled and on-demand snapshots as well as snapshot restore, if that's what you're trying to do.

**Comment by AbelTaylor** [comment]
> You should be able to access it as normal when k3s is running. Master builds of k3s also include native support for both scheduled and on-demand snapshots as well as snapshot restore, if that's what you're trying to do.

OK...Thanks..
