### ISSUE TITLE
Firewalld is not being configured properly for ingress on el8

### ISSUE THREAD

**Issue by Klaas-** [k3s-io/k3s#3122]
**Environmental Info:**
K3s Version: v1.20.4+k3s1 (838a906a)

Node(s) CPU architecture, OS, and Version: 

4.18.0-240.15.1.el8_3.x86_64
CentOS Linux release 8.3.2011

Cluster Configuration:

single node

**Describe the bug:**

The ingress via traefik is not working. It will simply show:
`HTTP/1.1 502 Bad Gateway`

**Steps To Reproduce:**

- Basic CentOS 8.3 server, nothing special single nic VM
- Installed K3s: `curl -sfL https://get.k3s.io | sh -`
- Install something that uses ingress, I installed awx via awx-operator

**Expected behavior:**
curl http://ingress-host.tld is successful

**Actual behavior:**

curl http://ingress-host.tld is not working, reply `HTTP/1.1 502 Bad Gateway`

**Additional context / logs:**
I can get it to work by either doing:
`firewall-cmd --zone=trusted --add-interface=cni0`
or
`systemctl stop firewalld`

This could also just be a doc issue if you say this is expected behavior if firewalld is enabled.

**Comment by brandond** [comment]
Upstream flannel does not technically support operation with firewalld. The recommendation is to disable it.

**Comment by Klaas-** [comment]
okay, I'll change this to a docs PR then and add a note about this somewhere in the k3s docs.

just for completeness: it also works when I enable masquerading
`firewall-cmd --add-masquerade`
