### ISSUE TITLE
replace "which" usage with internal shell equivalent

### ISSUE THREAD

**Issue by fcrozat** [k3s-io/k3s#3125]
Currently, k3s installation script relies on "which" tool on host to discover where various tools are located.

SLE minimal installation (as well as MicroOS / SLE Micro) don't install "which" package by default.

It would be better to rely on the internal shell equivalent ("command -v") to do this search (see https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then for the rationale).

I could cook a PR if you are fine with it.

related (internal) SLE Epic: https://jira.suse.com/browse/PM-2563

**Comment by brandond** [comment]
This seems reasonable, a PR would be welcome!

**Comment by rancher-max** [comment]
#### Validated this is now working using this latest install script from https://get.k3s.io

- I was first able to reproduce the problem on MicroOS, Ubuntu, and Centos8 by manually deleting the which binary and trying to install using an old install script:
```
$ curl -sfL https://raw.githubusercontent.com/k3s-io/k3s/v1.20.5%2Bk3s1/install.sh | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" INSTALL_K3S_VERSION=v1.20.5+k3s1 sh -
main: line 319: which: command not found
main: line 319: which: command not found
[ERROR]  Can not find curl or wget for downloading files
```
- Confirmed this error no longer occurs and k3s installs correctly on these systems
- Should therefore also work on SLES minimal installation, but I did not validate this directly as I don't have easy access to an ISO or AMI for this and the change made shouldn't be a risk based on the other validations made.
