### ISSUE TITLE
k3s `kubectl` and `crictl` shadow natively installed commands

### ISSUE THREAD

**Issue by mrwulf** [k3s-io/k3s#313]
**Describe the bug**
When `kubectl` or `crictl` are already installed, links created in `/usr/local/bin/` shadow natively installed commands.

**To Reproduce**
1. Install `kubectl` and `cri-tools` ( `sudo dnf install kubectl cri-tools` )
1. Locate the executables ( `which kubectl`, `which crictl` )
    * `/usr/bin/kubectl`
    * `/usr/bin/crictl`
1. Install `k3s` ( `curl -sfL https://get.k3s.io | sh -` )
1. Locate the executables ( `which kubectl`, `which crictl` )
    * `/usr/local/bin/kubectl`
    * `/usr/local/bin/crictl`

**Expected behavior**
For `kubectl` it would be nice to see existing configured clusters, but new k3s cluster too (don't add the link in `/usr/local/bin`). For `crictl` just use the existing executable.

**Additional context**
If `kubectl` is already installed, maybe you should just add the k3s cluster to the user's config file (and set it as the default?).

**Comment by warmchang** [comment]
For example when we deploy the k3s-0.30, it include k8s-v1.13.5, but the kubectl which native installed is an old version (eg. k8s-v1.10). How to deal with the compatibility between different versions? It's hard to deal for K3S.

So it's better to keep K3S independent and independent from other components or configurations.

Two alternatives can be considered:

1. User native kubectl cmd: kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml
2. User k3s/kubectl: alias kubectl="k3s kubectl"

**Comment by brandond** [comment]
Closing due to age. I believe the install script no longer force-links the binaries.
