### ISSUE TITLE
/etc/rancher/k3s/registries.yaml has no effect

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#3133]
**Environmental Info:**
K3s Version:  k3s version v1.18.15+k3s1 (60f1e80d)

Node(s) CPU architecture, OS, and Version: 
Linux puppet-agent-81 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
One node, master and agent on the one node.

**Describe the bug:**
I use my own private image registry, I configured /etc/rancher/k3s/registries.yaml, the content as following:
``` yaml
mirrors:
   harbor.dev.cn:
     endpoint:
         - "http://harbor.dev.cn"
configs:
   "harbor.dev.cn":
      auth:
         username: xxxxxx 
         password: xxxxxx
```

**Steps To Reproduce:**
I installed the k3s through following command line:
``` bash
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_SKIP_START=true INSTALL_K3S_VERSION=v1.18.15-k3s1 INSTALL_K3S_CHANNEL=stable K3S_TOKEN=token123456 sh -
```

then I modified /etc/systemd/system/k3s.service

``` 
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
    --write-kubeconfig=/root/.kube/.config \
    --write-kubeconfig-mode=644 \
    --node-ip="10.0.0.81" \
    --alsologtostderr=true \
    --data-dir=/opt/k3s/data/ \
    --cluster-cidr=10.42.0.0/16 \
    --service-cidr=10.43.0.0/16 \
    --flannel-backend=host-gw \
    --disable-cloud-controller \
    --disable-network-policy \
    --private-registry=/etc/rancher/k3s/registries.yaml \
```

then restart my k3s server

**Expected behavior:**
I can pull image from my private registry.

**Actual behavior:**
It seems the private registry config has no effect.

**Comment by brandond** [comment]
It looks like you've configured harbor.dev.cn as a mirror for harbor.dev.cn. What are you seeing when you pull images? Can you confirm that you're referencing the images as `harbor.dev.cn/repo/image:tag`?

**Comment by zengyongjie** [comment]
> It looks like you've configured harbor.dev.cn as a mirror for harbor.dev.cn. What are you seeing when you pull images? Can you confirm that you're referencing the images as `harbor.dev.cn/repo/image:tag`?

It said 401 unauthorized,


I tried again:
![image](https://user-images.githubusercontent.com/62204644/113119053-9ded3f00-9242-11eb-961d-4279023b4e7a.png)

and I succedded.

**Comment by jmckeown2** [comment]
For others who find this thread, the endpoint for the "mirror" apparently must not include a path, so your registry houses the mirror on a path you need a "rewrite." For example, if your company hosts `dockerhub` images at `registry.company.com/dockerhub/...` you would need:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://registry.company.com"
    rewrite:
      "^(.*)": "dockerhub/$1"
 ```

**Comment by whysi** [comment]
> For others who find this thread, the endpoint for the "mirror" apparently must not include a path, so if your registry houses the mirror on a path you need a "rewrite." For example, if your company hosts `dockerhub` images at `registry.company.com/dockerhub/...` you would need:
> 
> ```yaml
> mirrors:
>   docker.io:
>     endpoint:
>       - "https://registry.company.com"
>     rewrite:
>       "^(.*)": "dockerhub/$1"
> ```

Thanks, it works with this exact configuration with Harbor as a private registry in a proxy-cache configuration for Dockerhub (and other public registries).
