### ISSUE TITLE
containerd private registry auth config does not work in k3s

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#3134]
**Environmental Info:**
K3s Version: 
k3s version v1.18.15+k3s1 (60f1e80d)

Node(s) CPU architecture, OS, and Version: 
Linux puppet-agent-81 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
one node, master also as agent

**Describe the bug:**
I use private registry, I add the following config in `config.toml.tmpl`:
```
 [plugins.opt]
  path = "/opt/k3s/data/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "docker.io/rancher/pause:3.1"

[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/53ea32aa9bdb1dd1d2d12cf991ab86f2ed697d97a12ceaed2871449c8bfd1078/bin"
  conf_dir = "/opt/k3s/data/agent/etc/cni/net.d"


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugin.cri.registry]
  [plugin.cri.registry.mirrors]
    [plugins.cri.registry.mirrors."harbor.dev.cn"]
      endpoint=["http://harbor.dev.cn"]
    [plugins.cri.registry.mirrors."myharbor.ufw.com"]
      endpoint=["https://myharbor.ufw.com"]
  [plugin.cri.registry.configs]
    [plugins.cri.registry.configs."harbor.dev.cn".auth]
      username = "admin"
      password = "admin"
    [plugins.cri.registry.configs."myharbor.ufw.com".auth]
      username = "testuser"
      password = "Test@123"
```

Then I restarted the k3s server.

I use `crictl info` command to inspect if it has taking effect, I can see my config in the output .
![image](https://user-images.githubusercontent.com/62204644/113106003-d128d180-9234-11eb-80fb-dcabf909b119.png)

I can use crictl pull command to pull image from my registry.

But the ctr command and the deploy in k3s cannot pull image from my private registry .  It said 401 Unauthorized.

**Steps To Reproduce:**

- Installed K3s:
- configure the contained config template as above.
- try to deploy application which pull image from the private registry.

**Expected behavior:**
either use crictl or the k3s itself can pull image from my configured private registry successfully.

**Actual behavior:**
crictl can, but ctr command and k3s itself can not.

**Additional context / logs:**

**Comment by brandond** [comment]
Just out of curiosity, why are you manually providing the containerd config instead of just using registries.yaml?
https://rancher.com/docs/k3s/latest/en/installation/private-registry/

**Comment by zengyongjie** [comment]
> Just out of curiosity, why are you manually providing the containerd config from a template instead of just using registries.yaml and letting k3s generate the containerd config?
> https://rancher.com/docs/k3s/latest/en/installation/private-registry/

Because I configured registries.yaml, But It has no effect.....   so embarrassing

**Comment by zengyongjie** [comment]
> enerate the containerd config?

finally I succedded.   https://github.com/k3s-io/k3s/issues/3133
