### ISSUE TITLE
Missing flannel-backend CLI option for k3s agent

### ISSUE THREAD

**Issue by avoidik** [k3s-io/k3s#3142]
**Environmental Info:**
K3s Version: 

```
k3s version v1.20.5+k3s1 (355fff30)
go version go1.15.10
```

Node(s) CPU architecture, OS, and Version: 

```
Linux k3s-master 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 master, 1 worker

**Describe the bug:**

k3s agent has `--no-flannel` option to disable flannel CNI, which is suggesting to use `--flannel-backend=none` instead, however there is no such option available for k3s agent

**Steps To Reproduce:**

Try to run k3s agent with `--flannel-backend=none` option, check the logs using `journalctl -xru k3s-agent.service`

```
Apr 03 12:22:05 k3os-agent-a k3s[3342]: time="2021-04-03T12:22:05Z" level=fatal msg="flag provided but not defined: -flannel-backend"
```

Then check available options

```
$ k3s server --help | grep flannel
   --flannel-backend value                    (networking) One of 'none', 'vxlan', 'ipsec', 'host-gw', or 'wireguard' (default: "vxlan")
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --no-flannel                               (deprecated) use --flannel-backend=none
$ k3s agent --help | grep flannel
   --flannel-iface value               (agent/networking) Override default flannel interface
   --flannel-conf value                (agent/networking) Override default flannel config file
   --no-flannel                        (deprecated) use --flannel-backend=none
```

So `--flannel-backend` option is available for k3s server only 

**Expected behavior:**

I'd like to run k3s agent with `--flannel-backend=none` option in consistency with server CLI and as suggested in deprecation warning

**Actual behavior:**

The service wasn't able to start with `--flannel-backend=none` option

**Additional context / logs:**

As a workaround I'm using `--no-flannel` option on k3s agents

**Comment by xiaods** [comment]
install flannel is k3s embed components. don't need add flannel-backend in my mind.  do you have some context let me know your requirements.

**Comment by avoidik** [comment]
both `--flannel-backend` and `--no-flannel` options are already there, this issue is about inconsistency between agent and server CLI options, where the former option is available in the server component, but not in the client

**Comment by brandond** [comment]
The agent's flannel configuration (including the flannel-backend value) is actually retrieved from the server and does not need to be set on each agent. This is why there is no flag on the agent.

**Comment by avoidik** [comment]
so then `--no-flannel` shouldn't be there?

**Comment by brandond** [comment]
if you're setting `--flannel-backend=none` on the server then you should not need `--no-flannel` on the agent. That's why the flag is marked as deprecated.

**Comment by avoidik** [comment]
thanks, I'll close it
