### ISSUE TITLE
CoreDNS not working

### ISSUE THREAD

**Issue by clambin** [k3s-io/k3s#3153]
**Environmental Info:**
K3s Version: 
k3s version v1.20.5+k3s1 (355fff30)
go version go1.16.2

Node(s) CPU architecture, OS, and Version: 
Linux raspberrypi1 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

Cluster Configuration:
4 nodes: 1 master, 3 agents

**Describe the bug:**
Overnight, my cluster stopped being able to resolve external hostnames.  CoreDNS logs show the following:

```
[ERROR] plugin/errors: 2 github.com.telenet.be. AAAA: dial udp [2a02:1800:100::41:2]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 github.com.telenet.be. A: read udp 10.42.2.132:36102->192.168.0.1:53: i/o timeout
[ERROR] plugin/errors: 2 index.docker.io. AAAA: read udp 10.42.2.132:40000->192.168.0.1:53: i/o timeout
[ERROR] plugin/errors: 2 index.docker.io. AAAA: dial udp [2a02:1800:100::41:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io.telenet.be. AAAA: dial udp [2a02:1800:100::41:2]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io.telenet.be. A: dial udp [2a02:1800:100::41:2]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io.telenet.be. AAAA: dial udp [2a02:1800:100::41:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io.telenet.be. A: dial udp [2a02:1800:100::41:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io. AAAA: dial udp [2a02:1800:100::41:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io. AAAA: dial udp [2a02:1800:100::41:2]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 quay.io. A: read udp 10.42.2.132:41973->192.168.0.1:53: i/o timeout
[ERROR] plugin/errors: 2 quay.io. A: dial udp [2a02:1800:100::41:2]:53: connect: network is unreachable
```

telenet.be is my ISP.  Name resolution in the nodes:

```
cat /etc/resolv.conf
# Generated by resolvconf
search telenet.be
nameserver 192.168.0.1
nameserver 2a02:1800:100::41:2
nameserver 2a02:1800:100::41:1
```

To the best of my knowledge, that hasn't changed.

**Steps To Reproduce:**
- Installed K3s: 

Master installed as follows:
curl -sfL https://get.k3s.io | sudo INSTALL_K3S_EXEC="server --tls-san <<my public url>> --disable traefik" sh -

Agents installed as follows:
curl -sfL https://get.k3s.io | sudo K3S_URL=https://192.168.0.11:6443 K3S_TOKEN=<token> sh -

**Expected behavior:**
CoreDNS should resolve external hostnames

**Actual behavior:**
It doesn't.

**Additional context / logs:**
Nothing special in syslog, etc.

Tried rebooting the cluster, but got the same behaviour.
Switched back to legacy iptables & iptables6, (with reboot), but got the same behaviour.

**Comment by clambin** [comment]
Update:  things tried:
- rebuild the cluster (no change)
- disabling IPv6 (no change)
- setting DNS resolution to use only 8.8.8.8 and 8.8.4.4:

```
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

After that, things started working again.  No clue why (as DNS resolution was working fine outside of the cluster).  Will leave this open if you want to investigate further.

**Comment by brandond** [comment]
IPv6 does not work within the cluster, and K3s will actively work to ensure that you don't have IPv6 servers in the resolv.conf used by pods so I'm not sure how coredns ended up trying to use those servers.
