### ISSUE TITLE
Update flannel version in master

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3157]
Upstream flannel has been moved out from coreos to a new flannel-io org and all of the changes we were carrying in our fork have been pulled upstream. We should drop use of our custom fork for the 1.21 release and just point at a recent release or commit of flannel-io/flannel.

**Comment by brandond** [comment]
Done in #3097

**Comment by ShylajaDevadiga** [comment]
Validated using commit id
```
k3s -v
k3s version v1.21.1+k3s-7e175e8a (7e175e8a)
go version go1.16.4
```
Flannel version v0.13.1-rc2
