### ISSUE TITLE
Install script improvements - preflight checks

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3167]
Perhaps leverage check-config script or pass a `--preflight-checks` flag to check for any potential issues prior to an install.

For example, check if NetworkManager is utilized, if so warn the user this could cause issues (related to https://github.com/rancher/rke2/issues/786)

**Comment by davidnuzik** [comment]
RKE2: https://github.com/rancher/rke2/issues/863

**Comment by caroline-suse-rancher** [comment]
Closing due to age
