### ISSUE TITLE
With retention count set to 2, local snapshots is not removed from disk after transfer to S3 

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3178]
**Environmental Info:**
K3s Version: 
v1.20.5-alpha1+k3s2

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single node cluster

**Describe the bug:**
Passing retention count to 2 is honored in s3 bucket but does not honor the retention count to locally stored snapshots

**Steps To Reproduce:**
Run the server with below params 
```
k3s server --cluster-init --etcd-s3 --etcd-s3-bucket=<bucket name> --etcd-s3-access-key=<key> --etcd-s3-secret-key=<secret>  --etcd-snapshot-schedule-cron='* * * * *' --etcd-snapshot-retention=2
```

Verify snapshots are deleted periodically in sync with retention value

**Expected behavior:**
Retention count should be equal to value passed to etcd-snapshot-retention both locally as well as in s3

**Actual behavior:**
snapshots are not deleted locally. It does only in s3 bucket

**Comment by brandond** [comment]
If using S3, I don't think a local snapshot should be retained at all - we should delete the file from disk as soon as the upload is done regardless of success or failure.

**Comment by briandowns** [comment]
This is to bring it into feature parity with RKE1. If not for that, I completely agree.

**Comment by davidnuzik** [comment]
Moved to next milestone; not a blocker for k3s releases today.

**Comment by briandowns** [comment]
This is ready to test and has been backported.

https://github.com/k3s-io/k3s/pull/3197

**Comment by ShylajaDevadiga** [comment]
Validated on k3s version v1.20.6-rc1+k3s1, we have 2 snapshots retained when the retention count is set as 2.
```
root@ip-172-31-12-126:~# ls -l /var/lib/rancher/k3s/server/db/snapshots/
total 4988
-rw------- 1 root root 2486304 Apr 16 16:29 etcd-snapshot-1618590540
-rw------- 1 root root 2613280 Apr 16 16:30 etcd-snapshot-1618590600
root@ip-172-31-12-126:~# ls -l /var/lib/rancher/k3s/server/db/snapshots/
total 5464
-rw------- 1 root root 2732064 Apr 16 16:31 etcd-snapshot-1618590660
-rw------- 1 root root 2854944 Apr 16 16:32 etcd-snapshot-1618590720
root@ip-172-31-12-126:~#
```
