### ISSUE TITLE
Install script does not properly escape shell special characters in arguments

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3179]
**Environmental Info:**
K3s Version: 
v1.20.5-alpha1+k3s2 (881500d9)

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single node server with etcd backend

**Describe the bug:**
While creating scheduled snapshot install script does not honor passing of '*' for the cron parameter

**Steps To Reproduce:**
1. Install k3s passing etcd  snaphot flags as below with --etcd-snapshot-schedule-cron='*/1 * * * *'
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.5-alpha1+k3s2 sh -s - server --cluster-init --etcd-s3 --etcd-s3-bucket=<bucket>  --etcd-snapshot-schedule-cron='*/1 * * * *'
```
2. Systemd unit file contains invalid entry for the cronjob value  as */1 a snap a snap a snap *
```
cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--cluster-init' \
	'--etcd-s3' \
	'--etcd-s3-bucket=<bucket naame>' \
	'--etcd-snapshot-schedule-cron=*/1 a snap a snap a snap *' \
```
**Expected behavior:**
Regex should recognize * as a literal when passed within ''

**Actual behavior:**
Regex in install script does not recognize  '*'  as a literal passed to cron job and replaces with invalid value

NOTE: Snapshot/Restore functionality is working as expected when executing k3s binary with same flags.

**Comment by justbk** [comment]
when installing from config.yaml i'm running into the same/a similar issue

here, instead of snapshotting every 12 hours, etcd gets backed up every minute

```
# /etc/rancher/k3s/config.yaml
cluster-init: true
etcd-s3: true
etcd-s3-endpoint: "some.url"
etcd-s3-access-key: "access"
etcd-s3-secret-key: "secret"
etcd-s3-bucket: "rancher"
etcd-s3-folder: "etcd-k3s"
etcd-snapshot-schedule-cron: '* */12 * * *'
etcd-snapshot-retention: '14'
```

environment:
`k3s version v1.20.6+k3s1 (8d043282)`
`CentOS Linux release 7.9.2009`

**Comment by davidnuzik** [comment]
@brandond can review as he works on other install.sh script changes.

**Comment by davidnuzik** [comment]
Fixing milestone. Fixing issue state @cjellick

**Comment by ShylajaDevadiga** [comment]
Validated on v1.21.1+k3s1 shell special characters are interpreted correctly in the install script.
