### ISSUE TITLE
Does not see kubelet volume stats data

### ISSUE THREAD

**Issue by stoneshi-yunify** [k3s-io/k3s#3184]
**Environmental Info:**
K3s Version: 

k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**
Similar issue: https://github.com/k3s-io/k3s/issues/1396, but I'm using a newer k3s.

Does not get any volume stats data from kubelet:
```
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
```

And does not see related code in k3s source code, was it removed? In Kubernetes repo, the code is in pkg/kubelet/metrics/collectors/volume_stats.go.

**Comment by eplightning** [comment]
Does the CSI driver you're using support those stats? For example the `local-path-provisioner` included with k3s does not.

I'm using v1.20.2+k3s1 and for volumes provisioned by my cloud's CSI driver it all works fine.

**Comment by brandond** [comment]
> And does not see related code in k3s source code, was it removed? In Kubernetes repo, the code is in pkg/kubelet/metrics/collectors/volume_stats.go.

Have you looked at: https://github.com/k3s-io/k3s/blob/release-1.20/vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats.go

This is working for me - as @eplightning asked, are you sure that your storage driver provides these stats?

**Comment by stoneshi-yunify** [comment]
I'm using a hostpath CSI driver at https://github.com/kubernetes-csi/csi-driver-host-path. Looks like it does not export the volume metrics ... I installed another CSI driver and now I got the volume metrics. So it's a CSI driver issue as you suspected. Thanks.
