### ISSUE TITLE
How to use servicelb without traefik ingress

### ISSUE THREAD

**Issue by kuddusrhce** [k3s-io/k3s#3196]
We are planning to use other ingress instead of using treafik as default ingress controller. Is there any way if we can use service load balancer without traefik. If we disabled traefik then automatically it also disables servicelb.  

**Is your feature request related to a problem? Please describe.**
We are planning to use other ingress instead of using treafik as default ingress controller. Is there any way if we can use service load balancer without traefik. If we disabled traefik then automatically it also disables servicelb.  

**Describe the solution you'd like**
I want to use load balancer through service lb (klipper) so that I can load balance between nodes.

**Comment by brandond** [comment]
ServiceLB isn't disabled when you disable traefik - it only creates LB pods on-demand, when you have a Service with type=LoadBalancer. Does your other ingress create a service with the appropriate type?

**Comment by kuddusrhce** [comment]
Thanks Brad. LB pods are created if found any service with type=LoadBalancer. My replacement ingress also creates service with Load Balancer. In that case, I may need to disable either Klipper service load balancer or replacement ingress service with type=LoadBalancer so that it will not conflict with each other. Thanks a lot for your help and quick response. I will reach out you in case any help needed.

**Comment by xiaods** [comment]
i also don't know howto use traefik and servicelb. if you have some docs, please share with us. @kuddusrhce

**Comment by kuddusrhce** [comment]
Sorry for the late reply. I configured traefik and Klipper load balancer with the help of the below links.

Traefik: https://doc.traefik.io/traefik/v1.7/ 
Klipper: https://registry.hub.docker.com/r/inercia/klipper-lb

**Comment by kuddusrhce** [comment]
Also if you are using k3os then traefik ingress controller and Klipper load balancer are part of k3os itself.
