### ISSUE TITLE
Support conf.d style config loading for config.yaml

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3205]
Configuration should be loaded from config.yaml and then config.yaml.d/*.(yaml|yml) in alphanumeric order. The merging should be done by just taking the last value of a key found, so LIFO for keys. Slices should not be not merged but replaced.

**Comment by rancher-max** [comment]
#### Validated using commit id `c2eff9298ca7f8b427eca17a475e84c1b73ea791` - all expected results achieved

- Scenario1: Multiple files, installed via `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=c2eff9298ca7f8b427eca17a475e84c1b73ea791 sh -`
```
# config.yaml
token: boop
node-label:
  - foo=bar
  - bar=baz


# config.yaml.d/test1.yaml
write-kubeconfig-mode: 600
node-label:
  - test=me


# config.yaml.d/test2.yaml
write-kubeconfig-mode: 777
node-label:
  - other=what
  - foo=three


# config.yaml.d/test3.txt
write-kubeconfig-mode: 400
node-label:
  - hey=you


# expected result validated: 
write-kubeconfig-mode: 777
token: boop
node-label:
  - other=what
  - foo=three
```

- Scenario 2: Multiple files with exec, installed via `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" INSTALL_K3S_COMMIT=c2eff9298ca7f8b427eca17a475e84c1b73ea791 sh -`
```
Same  data and expected results from Scenario 1, 
although this time the `kubeconfig-mode` is `644` as it takes the value from INSTALL_K3S_EXEC
```

- Scenario 3: No files in .d directory (the current way k3s is used)
```
# config.yaml
token: boop
node-label:
  - foo=bar
  - bar=baz

# expected result: 
token: boop
node-label:
  - foo=bar
  - bar=baz
```

- Scenario 4: No config.yaml, ONLY files in the .d directory
```
# config.yaml.d/test1.yaml
write-kubeconfig-mode: 600
token: test
node-label:
  - test=me


# config.yaml.d/test2.yaml
write-kubeconfig-mode: 777
node-label:
  - other=what
  - foo=three


# config.yaml.d/test3.txt
write-kubeconfig-mode: 400
node-label:
  - hey=you

# expected result: 
write-kubeconfig-mode: 777
token: test
node-label:
  - other=what
  - foo=three
```
