### ISSUE TITLE
Document the new configuration file changes (.d directory support)

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3207]
Related to: https://github.com/k3s-io/k3s/issues/3205

https://docs.rke2.io/install/install_options/install_options/#configuration-file needs updates to reflect this new support added in 1.21.0 and newer.

**Comment by davidnuzik** [comment]
@brandond just pinging to ensure this is still on your radar. I know you have a lot on your plate but don't want this to be forgotten.

**Comment by brandond** [comment]
I'll try to knock this out before I swing back around to working on CI improvements.
