### ISSUE TITLE
registries.yml + mirror-authentication

### ISSUE THREAD

**Issue by strowi** [k3s-io/k3s#3211]
**Environmental Info:**
K3s Version: 
k3s version v1.16.15+k3s1 (790b740f)

Node(s) CPU architecture, OS, and Version: 
Linux sleipnir 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 node

**Describe the bug:**
Trying to use a pull-through registry cache with authentication seems to fail.

**Steps To Reproduce:**
Setup single k3s node, adding a `registries.yaml`:

``yaml
`mirrors:
  docker.io:
    endpoint:
      - https://registry-cache.domain.xyz
configs:
  registry-cache.domain.xyz:
    auth:
      username: registry
      password: PASSWORD!123
```

Fails to pull image e.g. "nginx:alpine" from the cache with a 401 error. Removing authentication from the registry-cache it works.


**Expected behavior:**
Being able to authenticate to the registry-cache and pull images from it.

**Actual behavior:**
Image-Pull fails with HTTP-401 error. Also no fallback to docker.io (not exactly sure if "mirrors" is supposed to fallback...).

regards,
strowi

**Comment by brandond** [comment]
v1.16.15+k3s1 is quite old and no longer supported, can you try with a more recent release?

**Comment by strowi** [comment]
Thx for the hint, seems to work now with the latest version.;)
