### ISSUE TITLE
K3s Version compatibility between master and agent?

### ISSUE THREAD

**Issue by aljohn0422** [k3s-io/k3s#3217]
**Environmental Info:**
K3s Version: 
- Master: `k3s version v1.20.0+k3s2 (2ea6b163); go version go1.15.5`
- agent: `k3s version v1.20.5+k3s1 (355fff30); go version go1.15.10`

Node(s) CPU architecture, OS, and Version: 
- Master: `Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
- agent: `Linux 4.9.201-tegra #1 SMP PREEMPT aarch64 aarch64 aarch64 GNU/Linux` (Jetson Xavier NX on Jetpack 4.5)

Cluster Configuration:
1 server with 6 other running agents on other devices (including a Jetson Nano, but no other Jetson devices.)

**Describe the bug:**
Cannot connect this agent to master. Installation script ran without any issue. But this machine is not listed in `sudo k3s kubectl get node`.

**Steps To Reproduce:**

- Installed latest K3s: `curl -sfL https://get.k3s.io | K3S_URL=<server ip> K3S_TOKEN=<server token> sh -s - --docker`
- check on master node: `sudo k3s kubectl get node`

**Expected behavior:**
K3s agent successfully connected to master.

**Actual behavior:**
This machine is not listed when I run `sudo k3s kubectl get node` on master.

**Additional context / logs:**
When I set `export INSTALL_K3S_VERSION=v1.20.0+k3s2` to install older k3s version, the agent connected successfully. It just won't connect on the latest version which is `v1.20.5+k3s1`.

Master is on version `v1.20.0+k3s2`.
I have other agent nodes running on `v1.20.2+k3s1`, `v1.20.4+k3s1`, `v1.20.0+k3s2` without a problem.

**Comment by brandond** [comment]
In general, the Kubernetes version skew policy applies: 
https://kubernetes.io/docs/setup/release/version-skew-policy/

In short, servers can be newer than agents, but agents should not be newer than servers.

**Comment by aljohn0422** [comment]
Got it. Thanks for providing this reference!
