### ISSUE TITLE
Support for s390x arch

### ISSUE THREAD

**Issue by rohitsakala** [k3s-io/k3s#3221]
**Describe the solution you'd like**

k3s-root supports s390x. So adding s390x support for k3s which will enable running of rancher standalone. 

**Dependencies Required**
- [x] https://github.com/k3s-io/klipper-lb/pull/32 - Klipper LB
- [x] https://github.com/rancher/image-mirror - CoreDNS Mirrored
- [x] https://github.com/traefik/traefik/pull/8729 - Traefik
- [x] https://github.com/rancher/image-mirror/pull/225- Traefik Mirrored
- [x] https://github.com/k3s-io/k3s-upgrade/pull/47 - K3S Upgrade

** K3S **
- [x] https://github.com/k3s-io/k3s/pull/5018 - K3S

**Comment by thomasferrandiz** [comment]
Another related PR for k3s-upgrade: https://github.com/k3s-io/k3s-upgrade/pull/47

**Comment by rancher-max** [comment]
Moved to Peer Review while waiting for https://github.com/k3s-io/k3s-upgrade/pull/47 to get one more review and be merged.

**Comment by rancher-max** [comment]
Validated in all of v1.24.1-rc3+k3s1, v1.23.7-rc1+k3s1, and v1.22.10-rc1+k3s1. s390x arch can be supported now.
