### ISSUE TITLE
Request: add `k3s-rootless.service` to release artifact

### ISSUE THREAD

**Issue by AkihiroSuda** [k3s-io/k3s#3222]
**Is your feature request related to a problem? Please describe.**

It is hard to find where to download `k3s-rootless.service`.

**Describe the solution you'd like**

Add https://github.com/k3s-io/k3s/blob/master/k3s-rootless.service to the release artifact (https://github.com/k3s-io/k3s/releases)

**Describe alternatives you've considered**
None

**Comment by brandond** [comment]
I'm not sure that it's worth shipping that as a separate artifact, since it doesn't really require any building or anything. Is this something we could fix with documentation?

**Comment by AkihiroSuda** [comment]
>  Is this something we could fix with documentation?

SGTM.

And/or maybe we should embed the systemd config in k3s binary, and have `k3s install-systemd` subcommand.

**Comment by AkihiroSuda** [comment]
Documentation PR: https://github.com/rancher/docs/pull/3243
