### ISSUE TITLE
cgroups v2 validation

### ISSUE THREAD

**Issue by tjay** [k3s-io/k3s#3228]
Hi,

in 
https://github.com/k3s-io/k3s/blob/2705431d9645d128441c578309574cd262285ae6/pkg/agent/run.go#L185
cgroups v2 is validated against "cgroups.Unified".
This test leads on systems with enabled cgroups v2 and cgroups v1 to fall back to cgroups v1. (github.com/containerd/cgroups returns "Hybrid")

A switch to control this behavior would make sense.

**Comment by AkihiroSuda** [comment]
The "Hybrid" mode is meaningless in the OCI/Kubernetes ecosystem, as you can't enable v2 controllers and v1 controllers simultaneously.
So, ignoring "Hybrid" is the right behavior.
