### ISSUE TITLE
K3s install script should support `INSTALL_K3S_FORCE_RESTART`

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#3232]
The K3s install script today currently performs a checksum comparison between the "old" and "new" binaries for `K3s` (along with the environment file and service files). If it does not detect a change of any of these files, it will not perform a service restart, which is not ideal if you are manually placing `k3s` binaries into place and using the `INSTALL_K3S_SKIP_DOWNLOAD` feature of the install script. We should add this feature to the install script to support the `system-agent`

**Comment by brandond** [comment]
Already merged, needs testing.

**Comment by ShylajaDevadiga** [comment]
Validated on k3s version v1.21.1+k3s1, INSTALL_K3S_FORCE_RESTART=true restarts k3s even when the binary is not changed.
