### ISSUE TITLE
customize coredns upstream servers on install

### ISSUE THREAD

**Issue by justinrush** [k3s-io/k3s#3233]
**Is your feature request related to a problem? Please describe.**
We are unable to resolve internal (private) DNS entries inside pods after installing k3s, although the host is able to resolve these entries fine. Looking at the CoreFile entry in the coredns configmap, it shows:
```
forward . /etc/resolv.conf
```

**Describe the solution you'd like**
I would like to be able to provide upstream DNS servers as a comma delimited string in an environment variable, i.e.:
```
K3S_UPSTREAM_DNS="192.168.0.53,10.0.3.53"
```

**Describe alternatives you've considered**
We've done a few things to work around this:
* edit /etc/hosts in the pod that needs to resolve internal hostnames... ew.
* post deploy, manually edit the configmap and change the forward statement to include the ips... ew
* edit our deploy script to include this hacky bit on post deploy:
```
kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get configmap/coredns -o yaml -n kube-system |sed 's/forward \. \/etc\/resolv.conf$/forward . 192.168.0.53/' |kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system apply -f -
kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml delete pod `kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get pods -n kube-system |grep coredns |awk '{print $1}'`

```

**Additional context**

Related to https://github.com/k3s-io/k3s/issues/53

**Comment by brandond** [comment]
You are welcome to provide your own resolv.conf and point coredns at it via the `--resolv-conf` CLI flag.

**Comment by justinrush** [comment]
> You are welcome to provide your own resolv.conf and point coredns (and other pods) at it via the `--resolv-conf` CLI flag.

but then I have to maintain both the local system's /etc/resolv.conf and some other file on the system specific to k3s.  I don't know why the local resolv.conf does not work - I am able to resolve private dns on the host (standard Ubuntu 20.04 install that has the 127.0.0.1 resolver)

**Comment by brandond** [comment]
> but then I have to maintain both the local system's /etc/resolv.conf and some other file on the system specific to k3s.

How is that different from maintaining both the system resolv.conf and the K3s configuration via a new CLI flag or environment variable?

**Comment by justinrush** [comment]
> > but then I have to maintain both the local system's /etc/resolv.conf and some other file on the system specific to k3s.
> 
> How is that different from maintaining both the system resolv.conf, and the K3s configuration via a new CLI flag or environment variable?

I suppose it isn't all that different and we could just dynamically generate a resolv.conf file that just has the nameserver and search lines in it. I'll go ahead and close this isssue.
