### ISSUE TITLE
[systemd] K3s services should support multiple env files

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3243]
As reported by @ibuildthecloud  - the K3s systemd unit should support loading .env files from multiple locations; ideally the same ones as RKE2 supports.

Right now it just supports a single .env file location, and it gets clobbered every time you run the install script.

**Comment by ShylajaDevadiga** [comment]
Validated on k2s v1.21.1-rc1+k3s1

- ENV variables in /etc/default/k3s and /etc/sysconfig/k3s are honored
- Files are not overwritten or deleted during install or uninstall
- Files are parsed in the order specified in the systemd unit file
- ENV variables passed over CLI is honored over values in ENV variables in the above two files 
- Additional ENV passed variables are written to default k3s.service.env env file under /etc/systemd/system dir
