### ISSUE TITLE
CSRs for kubernetes.io/kubelet-serving are signed with the client CA instead of the server CA

### ISSUE THREAD

**Issue by siegfriedweber** [k3s-io/k3s#3244]
We are implementing a kubelet on top of [Krustlet](https://github.com/deislabs/krustlet). Krustlet creates a CSR with `"signerName": "kubernetes.io/kubelet-serving"` which is signed by k3s with the client CA. `kubectl logs` fails with `x509: certificate signed by unknown authority`.

I think that *serving* certificates must be signed with the server CA. [pkg/daemons/control/server.go](https://github.com/k3s-io/k3s/blob/v1.21.0+k3s1/pkg/daemons/control/server.go#L112-L113) sets the `cluster-signing-cert-file` for all requests to the client CA since #1768. If there are several unrelated CAs then the certificates must be set for every signer individually.

The following parameters for `k3s server` solve the problem for us:

```
--kube-controller-manager-arg cluster-signing-cert-file= \
--kube-controller-manager-arg cluster-signing-key-file= \
--kube-controller-manager-arg cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt \
--kube-controller-manager-arg cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key \
--kube-controller-manager-arg cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt \
--kube-controller-manager-arg cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key \
--kube-controller-manager-arg cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt \
--kube-controller-manager-arg cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key
```

I think this change is necessary to also move #1520 and #2882 forward.

**Comment by brandond** [comment]
I don't think things were configurable at that level when #1768 went in; you had to choose between one ca or the other. I'm glad this has been improved upstream. Would you be willing to put in a PR?

**Comment by ron1** [comment]
@brandond Is it possible to backport https://github.com/k3s-io/k3s/pull/3259 to k8s 1.20 in order to fix deployment of workloads such as the minio-operator which require csr signing?

**Comment by brandond** [comment]
I can bring it up next week.

**Comment by ron1** [comment]
@brandond Thanks for the quick response. If I had checked the rke2 release-1.20 go.mod file I would have noticed that rke2 1.20 already includes most k3s 1.21.1 functionality including this patch. I actually encountered the issue in an rke2 1.18.12 cluster. I expect an upgrade of that cluster to rke 1.20.7 will fix the problem. I'll open an rke2 issue if that is not the case. So don't bother backporting this patch to k3s 1.20 for my sake. However, it isn't ideal that popular minio operator workload is broken on k3s 1.20 so you might want to backport it anyway.

Thanks again!

**Comment by cjellick** [comment]
@davidnuzik @fapatel1 needs bmped out to 1.20.9

**Comment by brandond** [comment]
This one shouldn't be bumped, #3446 should be bumped. I'll take care of that.

**Comment by ShylajaDevadiga** [comment]
Need to validate on k3s v1.21 and rke2 1.20 and backports
$ k3s -v
k3s version v1.21.1+k3s-b74c4997
```
$ journalctl -u k3s|grep cluster-signing
Jun 16 08:03:37 ip-172-31-15-119 k3s[1479]: time="2021-06-16T08:03:37.309453018Z" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key
```

**Comment by ShylajaDevadiga** [comment]
Validated on k3s version v1.21.2-rc1+k3s1
```
journalctl -u k3s |grep cluster-signing
Jun 21 06:26:59 ip-172-31-0-45 k3s[1194]: time="2021-06-21T06:26:59.272336669Z" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
```
