### ISSUE TITLE
Can only access NodePort through the node the app is running on

### ISSUE THREAD

**Issue by nurhun** [k3s-io/k3s#3245]
**Environmental Info:**
K3s Version: 
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10

Node(s) CPU architecture, OS, and Version: 
Linux ip-10-0-2-179.eu-north-1.compute.internal 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
NAME                                        STATUS   ROLES                  AGE    VERSION
ip-10-0-2-179.eu-north-1.compute.internal   Ready    control-plane,master   104m   v1.20.6+k3s1
ip-10-0-2-170.eu-north-1.compute.internal   Ready    control-plane,master   91m    v1.20.6+k3s1

**Describe the bug:**
Can only access NodePort through the node the app is running on, unable to get response from the same port on other nodes. This affects the LB functionality.

**Steps To Reproduce:**
running any NodePort or LoadBalaner service, and you get the port responding on only one node.

**Expected behavior:**
Port is responding on all nodes.
![nodeport2](https://user-images.githubusercontent.com/37078437/116575038-963abc00-a90e-11eb-8d6d-82962e6a836f.png)

**Comment by brandond** [comment]
You might check the docs here: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

>  If you set service.spec.externalTrafficPolicy to the value Local, kube-proxy only proxies proxy requests to local endpoints, and does not forward traffic to other nodes. This approach preserves the original source IP address. If there are no local endpoints, packets sent to the node are dropped.

**Comment by nurhun** [comment]
No externalTrafficPolicy was defined. Setting it to Cluster solved the issue. Thanks !
