### ISSUE TITLE
k3s causes a surge in the iptables chain

### ISSUE THREAD

**Issue by AbelTaylor** [k3s-io/k3s#3251]
**Environmental Info:**
K3s Version:  v1.20.5

Node(s) CPU architecture, OS, and Version: 5.4.0-70-generic

Cluster Configuration: 1master 2agents

I have a total of three nodes here, one master node and two working nodes. The problem is that on one of the working nodes, k3s caused the number of iptables to skyrocket. In the end, a new chain could not be created, resulting in pods on this node. The network is blocked, and the error message'Another app is currently holding the xtables lock. Perhaps you want to use the -w option?' will appear when using the iptables command, and the other logs are shown in the figure below.

**Additional context / logs:**
![image](https://user-images.githubusercontent.com/71317399/116680733-9acea580-a9de-11eb-8424-eb262013afd7.png)
![image](https://user-images.githubusercontent.com/71317399/116678510-fb101800-a9db-11eb-84a3-9437d0e2dc2e.png)

Then, I stop k3s, and I can use the iptables command, and I see the following screenshot:
![image](https://user-images.githubusercontent.com/71317399/116679130-bb95fb80-a9dc-11eb-89b5-fe86a2ce21a1.png)

There are tens of thousands of chains as shown in the figure above.
![image](https://user-images.githubusercontent.com/71317399/116677910-55f53f80-a9db-11eb-8957-0fc533f900a4.png)

**Comment by brandond** [comment]
This sounds like a duplicate of #3117 - can you try one of the solutions suggested in the comments there?
