### ISSUE TITLE
.net core slow on k3s

### ISSUE THREAD

**Issue by bzmotoros** [k3s-io/k3s#3252]
**Environmental Info:**
K3s Version: 
k3s version v1.19.3+k3s3 (0e4fbfef)

Node(s) CPU architecture, OS, and Version: 
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 server

**Describe the bug:**
.Net core 3.1 app runs 10-20 times slower on MongoDB query (tcp connection) than native on node

**Steps To Reproduce:**

- Installed K3s: 
- k3sup install \
        --k3s-version v1.19.3+k3s3 \
        --ip  \ 
        --user root --cluster \
        --k3s-extra-args ' --kube-apiserver-arg=default-unreachable-toleration-seconds=0

**Expected behavior:**
Nearly same performance as on node

**Actual behavior:**
10-20 times slower

**Additional context / logs:**

**Comment by brandond** [comment]
K3s doesn't do anything different than upstream Kubernetes when it comes to running your pods. Can you confirm that this is a K3s-specific issue?

**Comment by Oats87** [comment]
@bzmotoros is there any way you can test your workload on the host network for performance? Wondering if pod networking is getting in the way. 

I’m assuming you are talking to a non-containerized mongo?

For what it’s worth, just because it runs well in minikube does not mean it is not “Kubernetes” related.

**Comment by bzmotoros** [comment]
@Oats87 Mongo is on separated host.
Could you please explain the test steps that you recommend?
k3s / k3d networking is the default, as I know flannel.
Tested on multiple nodes, so not node or firewall related.

**Comment by brandond** [comment]
How are you testing that it's the TCP connection itself that is slow? Do you have packet captures or other information to show what's going on? I have seen issues where some clients do a number of DNS lookups to attempt to find a server to connect to, and if cluster DNS is not configured correctly those can time out and cause delays before the client finally locates the correct record and connects.

**Comment by bzmotoros** [comment]
@brandond Running same c# MongoDB query Find(Query) and download 10 000 items from DB
DNS not involved becase server is specified by IP and port

**Comment by brandond** [comment]
OK you said the "tcp connection" was slow which I took as meaning that it was slow to establish a TCP connection - it sounds like you are reporting slower network throughput? Or slower application performance? It might help if you could quantify what specifically is slower, other than just the app in general not delivering results as quickly.

**Comment by bzmotoros** [comment]
@brandond Said TCP because mongo use TCP. Tested with speedtest cli, network troughput is okay in k3s.

**Comment by bzmotoros** [comment]
Tried with mongodb shell, same as .net: fast on the node, slow in k3s.

**Comment by bzmotoros** [comment]
Investigating with tcpdump its weird that node uses packet with some 10-20K but container not bigger than MTU (1450)
Maybe this is the problem?

**Comment by comphilip** [comment]
@bzmotoros what does `Client -> Server ICMP` means?
