### ISSUE TITLE
make certificate renewal/expiry configurable

### ISSUE THREAD

**Issue by mschneider82** [k3s-io/k3s#3253]
**Is your feature request related to a problem? Please describe.**
the k3s cluster will only be stable for 1 year, then the certificates are expired.

**Describe the solution you'd like**
i would like to configure a longer period for certifiacte expiry.
having a way to configure both parameters (renew before expiry / expiry days)

Its currently hardcoded:

https://github.com/k3s-io/k3s/blob/master/pkg/daemons/config/types.go#L24
https://github.com/k3s-io/k3s/blob/master/vendor/github.com/rancher/dynamiclistener/factory/cert_utils.go#L83

**Describe alternatives you've considered**
manually create all certificates

**Additional context**
when running the cluster for 9 month and then restart k3s to renew the certificates is difficult to address.
An expiry of e.g. 10 years and CertificateRenewDays of 1-2 Years better fits for an long running offline cluster.

**Comment by brandond** [comment]
FWIW Kubernetes releases are only supported for 1 year, and nodes should be patched or replaced regularly within that period. It is not currently expected that nodes will be up without at least restarting services for >1 year.

**Comment by mschneider82** [comment]
Yes we could keep the defaults to 90/365 but to have a way to configure that values would be great.

**Comment by mschneider82** [comment]
@brandond since the vendored dynamiclistener lib did not support a custom expiry value, i have created a PR to support that while not breaking the existing api.

**Comment by ChristianCiach** [comment]
A simple "thumbs up" is not enough in this case, I am sorry.

We deploy K3s into environments that are *really* hard to reach (on premise), without internet access and without direct intranet access. You can think of this as "hardcore air-gapped" environments.

These systems are designed to run for a very long time without any human intervention (as long as there are no errors). I guess we could create our own certificates, but it would be a lot easier to just have a configuration for this.

**Comment by giezi** [comment]
This would be a very important feature. +1

**Comment by xiaods** [comment]
@giezi  yes, you can use k8e to archive your purpose. https://getk8e.com/docs/install/cert-check/

**Comment by giezi** [comment]
Any news on this? This is very important - many thanks!

**Comment by xiaods** [comment]
@giezi  you can use k8e instread. it's based on k3s codebase and provision new lightweight kubernetes distribion.
following this step to build a cluster with 10 years of kubectl client certs.

**Comment by jovizhangwei** [comment]
++++1, we also really need this feature, otherwise it's very painful for our internal env maintenance.

**Comment by mschneider82** [comment]
my fix for dynamiclistener was rejected but they solved it in a differend way, i think it could work already in k3s when setting the env to:

```export CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=99999```

see https://github.com/rancher/dynamiclistener/blob/master/README.md

**Comment by xiaods** [comment]
> my PR for dynamiclistener (the underlying lib) was rejected but they solved it in a different way, i think it could work already in k3s when setting the env to:
> 
> `export CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=99999`
> 
> see https://github.com/rancher/dynamiclistener/blob/master/README.md

yes, it works.

**Comment by mschneider82** [comment]
closing this issue.

**Comment by jovizhangwei** [comment]
@mschneider82 @xiaods which k3s version support this env setting?

**Comment by CharesLee** [comment]
> 我的动态监听器（底层库）的 PR 被拒绝了，但他们以不同的方式解决了它，我认为当将 env 设置为：时它可以在 k3s 中工作：
> 
> `export CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=99999`
> 
> 请参阅https://github.com/rancher/dynamiclistener/blob/master/README.md

`CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=36500 INSTALL_K3S_EXEC="--node-name=${node_name} --disable=traefik --kube-controller-manager-arg=node-cidr-mask-size=20 --kubelet-arg=max-pods=4094" INSTALL_K3S_SKIP_DOWNLOAD=true /bin/bash ./install.sh`

`root@master:/opt/powerlaw/k3s-install-data# for i in `ls /var/lib/rancher/k3s/server/tls/*.crt`; do echo $i; openssl x509 -enddate -noout -in $i; done

/var/lib/rancher/k3s/server/tls/client-admin.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-ca.crt
notAfter=Apr 27 07:03:17 2034 GMT
/var/lib/rancher/k3s/server/tls/client-controller.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-k3s-cloud-controller.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-k3s-controller.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-kube-proxy.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/client-scheduler.crt
notAfter=Apr 29 07:03:17 2025 GMT
/var/lib/rancher/k3s/server/tls/request-header-ca.crt
notAfter=Apr 27 07:03:17 2034 GMT
/var/lib/rancher/k3s/server/tls/server-ca.crt
notAfter=Apr 27 07:03:17 2034 GMT
/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt
notAfter=Apr 29 07:03:17 2025 GMT`

Hello, I specified this ENV when installing k3s and it still doesn't work

**Comment by mschneider82** [comment]
@CharesLee i think that must be a runtime env. Try to set it in file /etc/systemd/system/k3s.service.env
and restart k3s

**Comment by CharesLee** [comment]
> @CharesLee我认为这一定是一个运行时环境。尝试在文件 /etc/systemd/system/k3s.service.env 中设置它 并重新启动 k3s。创建证书时或稍后续订证书时，环境必须在 k3s 首次启动时出现

According to what you said, I need to reinstall my k3s service and do not let k3s start.  Then create a/etc/systemd/system/k3s.  Service.  Add CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS env = 99999, finally start k3s service？

**Comment by CharesLee** [comment]
> @CharesLee i think that must be a runtime env. Try to set it in file /etc/systemd/system/k3s.service.env and restart k3s. The env must be present on the first start of k3s when the certs are created or later when they are renewed

According to what you said, I need to reinstall my k3s service and do not let k3s start. Then create a/etc/systemd/system/k3s. Service. Add CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS env = 99999, finally start k3s service？

**Comment by mschneider82** [comment]
@CharesLee try https://docs.k3s.io/cli/certificate#client-and-server-certificates

**Comment by FelsiyaVasanthi** [comment]
@CharesLee - Did adding CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS env = 99999, finally start k3s service, worked? 
@mschneider82 - I cannot see the certificate configurable part in the link shared

**Comment by CharesLee** [comment]
> [@CharesLee](https://github.com/CharesLee) - Did adding CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS env = 99999, finally start k3s service, worked? [@mschneider82](https://github.com/mschneider82) - I cannot see the certificate configurable part in the link shared

After my test, there is no problem
k3s version: v1.29.4+k3s1

Add command in master
echo CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=36500 > /etc/default/k3s
echo CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=36500 >  /etc/sysconfig/k3s

Download https://github.com/k3s-io/k3s/blob/master/contrib/util/generate-custom-ca-certs.sh
vim generate-custom-ca-certs.sh update 3700 and 7300 change 36500
chmod +x generate-custom-ca-certs.sh
./generate-custom-ca-certs.sh

Go and install k3s
