### ISSUE TITLE
K3S v1.21.0+k3s1 :  Nodes topology is not available, providing CPU topology

### ISSUE THREAD

**Issue by jc42jc** [k3s-io/k3s#3254]
**Environmental Info:**
K3s Version:  v1.21.0+k3s1

Node(s) CPU architecture, OS, and Version:  ARM 64 / Raspberry PI / UBUNTU 20.4 LTS

Cluster Configuration: Cannat init master, so cluster instaled for the moment

**Describe the bug:**
I have this error in loop when I inititialiase the first master: W0429 19:41:04.325885 4743 sysinfo.go:203] Nodes topology is not available, providing CPU topology"

**Steps To Reproduce:**
Intall K3S on PI
root@master1:/home/ubuntu# export K3S_KUBECONFIG_MODE="644"
root@master1:/home/ubuntu# export INSTALL_K3S_SKIP_ENABLE="true"
root@master1:/home/ubuntu# export INSTALL_K3S_SKIP_START="true"
root@master1:/home/ubuntu# export INSTALL_K3S_CHANNEL="latest"

root@master1:/home/ubuntu# curl -sfL https://get.k3s.io | sh -s -

And initialise the first master:
root@master1:/home/ubuntu# export K3S_TOKEN="Token"
root@master1:/home/ubuntu# k3s server --cluster-init

- Installed K3s: 

**Expected behavior:**
Have a functionnal K3S cluster

**Actual behavior:**
Does'nt work

**Additional context / logs:**
W0429 19:41:04.325885 4743 sysinfo.go:203] Nodes topology is not available, providing CPU topology

**Comment by brandond** [comment]
That is correct, the Raspberry PI sysfs structure does not provide any CPU topology information. This message is from cadvisor, not K3s itself, and as noted by the `W` prefix is just a warning. You might see this a few times on startup but it should not affect anything. If you're seeing the agent fail to start then something else is likely going on, can you attach the full logs?

**Comment by jc42jc** [comment]
Hello,
A detail of the logs:

Trace[1351750712]: [1.422234783s] [1.422234783s] END
I0430 19:25:57.669183    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for traefikservices.traefik.containo.us
I0430 19:25:57.669316    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for tlsoptions.traefik.containo.us
I0430 19:25:57.669393    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for middlewares.traefik.containo.us
I0430 19:25:57.669481    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for serverstransports.traefik.containo.us
I0430 19:25:57.669570    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for ingressroutes.traefik.containo.us
I0430 19:25:57.669657    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for tlsstores.traefik.containo.us
I0430 19:25:57.669765    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for ingressroutetcps.traefik.containo.us
I0430 19:25:57.669841    9930 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for ingressrouteudps.traefik.containo.us
I0430 19:25:57.670058    9930 shared_informer.go:240] Waiting for caches to sync for resource quota
I0430 19:25:57.770982    9930 shared_informer.go:247] Caches are synced for resource quota
I0430 19:25:58.141310    9930 shared_informer.go:240] Waiting for caches to sync for garbage collector
I0430 19:25:58.141452    9930 shared_informer.go:247] Caches are synced for garbage collector
W0430 19:29:07.776945    9930 sysinfo.go:203] Nodes topology is not available, providing CPU topology
{"level":"info","ts":"2021-04-30T19:33:57.807Z","caller":"mvcc/index.go:189","msg":"compact tree index","revision":1338}
{"level":"info","ts":"2021-04-30T19:33:57.856Z","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":1338,"took":"47.998627ms"}
W0430 19:34:07.775270    9930 sysinfo.go:203] Nodes topology is not available, providing CPU topology
{"level":"warn","ts":"2021-04-30T19:35:25.783Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"194.751062ms","expected-duration":"100ms","prefix":"","request":"header:<ID:3020922646603799314 username:\"etcd-client\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/services/endpoints/kube-system/rancher.io-local-path\" mod_revision:2359 > success:<request_put:<key:\"/registry/services/endpoints/kube-system/rancher.io-local-path\" value_size:543 >> failure:<request_range:<key:\"/registry/services/endpoints/kube-system/rancher.io-local-path\" > >>","response":"size:16"}
{"level":"info","ts":"2021-04-30T19:38:57.819Z","caller":"mvcc/index.go:189","msg":"compact tree index","revision":2134}
{"level":"info","ts":"2021-04-30T19:38:57.843Z","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":2134,"took":"22.116912ms"}
W0430 19:39:07.777223    9930 sysinfo.go:203] Nodes topology is not available, providing CPU topology
W0430 19:41:02.048722    9930 watcher.go:220] watch chan error: etcdserver: mvcc: required revision has been compacted
{"level":"warn","ts":"2021-04-30T19:41:59.266Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"188.712222ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/leases/kube-system/cloud-controller-manager\" ","response":"range_response_count:1 size:488"}
{"level":"info","ts":"2021-04-30T19:41:59.266Z","caller":"traceutil/trace.go:145","msg":"trace[1025808100] range","detail":"{range_begin:/registry/leases/kube-system/cloud-controller-manager; range_end:; response_count:1; response_revision:3408; }","duration":"188.942033ms","start":"2021-04-30T19:41:59.077Z","end":"2021-04-30T19:41:59.266Z","steps":["trace[1025808100] 'agreement among raft nodes before linearized reading'  (duration:
151.93363ms)","trace[1025808100] 'range keys from in-memory index tree'  (duration: 36.666224ms)"]}
{"level":"warn","ts":"2021-04-30T19:42:36.010Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"228.444391ms","expected-duration":"100ms","prefix":"","request":"header:<ID:3020922646603802348 username:\"etcd-client\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/leases/kube-system/kube-controller-manager\" mod_revision:3500 > success:<request_put:<key:\"/registry/leases/kube-system/kube-controller-manager\" value_size:410 >> failure:<request_range:<key:\"/registry/leases/kube-system/kube-controller-manager\" > >>","response":"size:16"}
{"level":"warn","ts":"2021-04-30T19:42:36.012Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"162.122013ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/persistentvolumeclaims/\" range_end:\"/registry/persistentvolumeclaims0\" count_only:true ","response":"range_response_count:0 size:5"}
{"level":"info","ts":"2021-04-30T19:42:36.013Z","caller":"traceutil/trace.go:145","msg":"trace[2059236475] range","detail":"{range_begin:/registry/persistentvolumeclaims/; range_end:/registry/persistentvolumeclaims0; response_count:0; response_revision:3505; }","duration":"163.035385ms","start":"2021-04-30T19:42:35.850Z","end":"2021-04-30T19:42:36.013Z","steps":["trace[2059236475] 'agreement among raft nodes before linearized reading'  (duration: 161.890776ms)"]}
{"level":"warn","ts":"2021-04-30T19:42:36.220Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"112.885897ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/limitranges/\" range_end:\"/registry/limitranges0\" count_only:true ","response":"range_response_count:0 size:5"}
{"level":"info","ts":"2021-04-30T19:42:36.220Z","caller":"traceutil/trace.go:145","msg":"trace[1837113421] range","detail":"{range_begin:/registry/limitranges/; range_end:/registry/limitranges0; response_count:0; response_revision:3506; }","duration":"113.088967ms","start":"2021-04-30T19:42:36.107Z","end":"2021-04-30T19:42:36.220Z","steps":["trace[1837113421] 'agreement among raft nodes before linearized reading'  (duration: 42.107137ms)","trace[1837113421] 'range keys from in-memory index tree'  (duration: 70.704965ms)"]}
{"level":"info","ts":"2021-04-30T19:43:57.832Z","caller":"mvcc/index.go:189","msg":"compact tree index","revision":2927}
{"level":"info","ts":"2021-04-30T19:43:57.856Z","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":2927,"took":"22.491251ms"}
W0430 19:44:07.776353    9930 sysinfo.go:203] Nodes topology is not available, providing CPU topology
^CINFO[2021-04-30T19:48:13.138442754Z] Shutting down /v1, Kind=Secret workers
INFO[2021-04-30T19:48:13.138740804Z] Shutting down /v1, Kind=Endpoints workers
INFO[2021-04-30T19:48:13.138937301Z] Shutting down /v1, Kind=Pod workers
INFO[2021-04-30T19:48:13.139075169Z] Shutting down /v1, Kind=Service workers
INFO[2021-04-30T19:48:13.139281999Z] Shutting down batch/v1, Kind=Job workers
INFO[2021-04-30T19:48:13.139423275Z] Shutting down helm.cattle.io/v1, Kind=HelmChart workers
INFO[2021-04-30T19:48:13.139552736Z] Shutting down helm.cattle.io/v1, Kind=HelmChartConfig workers
ERRO[2021-04-30T19:48:13.140797197Z] Tunnel endpoint watch channel closed: {ERROR &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding,Reason:InternalError,Details:&StatusDetails{Name:,Group:,Kind:,Causes:[]StatusCause{StatusCause{Type:UnexpectedServerResponse,Message:unable to decode an event from the watch stream: context canceled,Field:,},StatusCause{Type:ClientWatchDecoding,Message:unable to decode an event from the watch stream: context canceled,Field:,},},RetryAfterSeconds:0,UID:,},Code:500,}}
INFO[2021-04-30T19:48:13.140997712Z] Proxy done                                    err="context canceled" url="wss://192.168.2.1:6443/v1-k3s/connect"
INFO[2021-04-30T19:48:13.141607129Z] Shutting down /v1, Kind=Node workers
INFO[2021-04-30T19:48:13.142626371Z] Shutting down k3s.cattle.io/v1, Kind=Addon workers
W0430 19:48:13.143874    9930 reflector.go:436] github.com/flannel-io/flannel/subnet/kube/kube.go:300: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
I0430 19:48:13.144315    9930 controller.go:185] Shutting down kubernetes service endpoint reconciler
I0430 19:48:13.145590    9930 controller.go:89] Shutting down OpenAPI AggregationController
I0430 19:48:13.147162    9930 controller.go:123] Shutting down OpenAPI controller
I0430 19:48:13.147865    9930 crdregistration_controller.go:142] Shutting down crd-autoregister controller
I0430 19:48:13.148400    9930 available_controller.go:487] Shutting down AvailableConditionController
I0430 19:48:13.149025    9930 crd_finalizer.go:278] Shutting down CRDFinalizer
I0430 19:48:13.149644    9930 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
I0430 19:48:13.150259    9930 autoregister_controller.go:165] Shutting down autoregister controller
I0430 19:48:13.150915    9930 establishing_controller.go:87] Shutting down EstablishingController
I0430 19:48:13.151541    9930 apiservice_controller.go:131] Shutting down APIServiceRegistrationController
I0430 19:48:13.152056    9930 apf_controller.go:303] Shutting down API Priority and Fairness config worker
I0430 19:48:13.152199    9930 cluster_authentication_trust_controller.go:463] Shutting down cluster_authentication_trust_controller controller
I0430 19:48:13.152299    9930 naming_controller.go:302] Shutting down NamingConditionController
I0430 19:48:13.152402    9930 nonstructuralschema_controller.go:204] Shutting down NonStructuralSchemaConditionController
I0430 19:48:13.152494    9930 customresource_discovery_controller.go:245] Shutting down DiscoveryController
I0430 19:48:13.153357    9930 dynamic_cafile_content.go:182] Shutting down request-header::/var/lib/rancher/k3s/server/tls/request-header-ca.crt
I0430 19:48:13.153474    9930 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/var/lib/rancher/k3s/server/tls/client-ca.crt
I0430 19:48:13.153665    9930 dynamic_serving_content.go:145] Shutting down aggregator-proxy-cert::/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt::/var/lib/rancher/k3s/server/tls/client-auth-proxy.key
I0430 19:48:13.153740    9930 dynamic_cafile_content.go:182] Shutting down request-header::/var/lib/rancher/k3s/server/tls/request-header-ca.crt
I0430 19:48:13.141681    9930 network_policy_controller.go:157] Shutting down network policies full sync goroutine
I0430 19:48:13.141746    9930 network_policy_controller.go:172] Shutting down network policies controller
I0430 19:48:13.141798    9930 watch.go:40] context canceled, close receiver chan
I0430 19:48:13.154026    9930 vxlan_network.go:74] evts chan closed
INFO[2021-04-30T19:48:13.141805662Z] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
FATA[2021-04-30T19:48:13.154074076Z] flannel exited: <nil>
root@master1:~#

**Comment by brandond** [comment]
Are you trying to use embedded etcd on a raspberry pi? MMC and SD Card are both far too slow for etcd; it needs SSD or NVMe to function within the required storage latency.
