### ISSUE TITLE
Server logs flooded with Skipping invalid IP

### ISSUE THREAD

**Issue by Ripolin** [k3s-io/k3s#3255]
**Environmental Info:**
K3s Version: v1.21.0+k3s1

Node(s) CPU architecture, OS, and Version: Linux 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 

Cluster Configuration: 1 server & 3 agents

**Describe the bug:**
I use an external cloud controller manager to manage load balancing and services exposition. But on my services spec, I have no ```status.loadBalancer.ingress.IP``` field but  a ```status.loadBalancer.ingress.hostname``` instead. Everything works fine but server logs are flooded with entries like ```utils.go:288] Skipping invalid IP:```

**Steps To Reproduce:**

- Installed K3s: 
- Use an external CCM which only  provide a hostname to expose service 

**Expected behavior:**
No more logs like ```utils.go:288] Skipping invalid IP:```

**Actual behavior:**
Server logs are flooded with entries like ```utils.go:288] Skipping invalid IP:```

**Additional context / logs:**

Should it be a good idea to test consistency of IP here : https://github.com/k3s-io/k3s/blob/2db3bf7a8905ca3578fb20544bbe269b37803d68/vendor/k8s.io/kubernetes/pkg/proxy/service.go#L204 or here ? https://github.com/k3s-io/k3s/blob/2db3bf7a8905ca3578fb20544bbe269b37803d68/vendor/k8s.io/kubernetes/pkg/proxy/util/utils.go#L284

**Comment by brandond** [comment]
Both of the things you linked to are in core Kubernetes code, not K3s code - so we would not modify them here. You might create an issue at https://github.com/kubernetes/kubernetes ?

**Comment by Ripolin** [comment]
> Both of the things you linked to are in core Kubernetes code, not K3s code - so we would not modify them here. You might create an issue at https://github.com/kubernetes/kubernetes?
> 
> That said - if you're using an external CCM, you should probably `--disable=servicelb`, as the conflicting service controllers might be the source of your problem?

servicelb is already disable. Il will create an issue on k8s project.

**Comment by brandond** [comment]
Ah OK, you didn't mention that you had already disabled it - your notes said this was just a standard install of K3s with an external CCM deployed. If that's the case then yeah probably worth chasing it down upstream.
