### ISSUE TITLE
systemd or openrc

### ISSUE THREAD

**Issue by vikasgoswami5035** [k3s-io/k3s#3256]
I am trying to connect k3s agent to master node. I am using air-gap installation. When I connect using the script then it is giving me error that cannot find systemd or openrc to use as a process supervisor.
I already downloaded the binary of k3s and placed it in a /var/local/bin/k3s
I am running this command :-
INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken ./install.sh
I will really appreciate for your help.

**Comment by brandond** [comment]
What distribution are you installing K3s on? If it doesn't use SystemD or OpenRC then you should probably just download the K3s binary directly and figure out how to call it on startup from whatever init system your host DOES use.
