### ISSUE TITLE
Huge delay in the creation of persistent volumes with Rook

### ISSUE THREAD

**Issue by jose-sanchezm** [k3s-io/k3s#326]
**Describe the bug**
PVC created with Rook takes about one hour to start provisioning a volume after its creation.

**To Reproduce**
- Have a unformatted disk of at least 5GB attached to the master machine running CentOS
- Install k3s with the installation script ```curl -sfL https://get.k3s.io | sh -```
- Wait for k3s to finish loading and check that all pods are running
- Install Rook as specified here: https://rook.io/docs/rook/v0.9/ceph-quickstart.html using branch 0.9.3 in here https://github.com/rook/rook
- Deploy a storage class found here https://github.com/rook/rook/blob/release-0.9/cluster/examples/kubernetes/ceph/storageclass.yaml 
- Deploy a sample mysql pod found in here: https://github.com/rook/rook/blob/release-0.9/cluster/examples/kubernetes/mysql.yaml. If the data disk has less than 20GB, modify the expected size in the yaml file to fit inside your disk.

**Expected behavior**
The PVC gets bound in seconds and the mysql pod starts running

**Screenshots**

**Additional context**
The same example in a cluster created with kubeadm works as expected.

**Comment by pramodvallanur** [comment]
Experienced a similar behavior. For almost 60m, the pvc was not bound.

**Comment by danacr** [comment]
I am using rook-ceph 1.0.2 and it is working fine: https://github.com/danacr/kubernetes-the-fun-way/blob/master/docs/04-rook-ceph.md

**Comment by jose-sanchezm** [comment]
Are you running CentOS? In Ubuntu *sometimes* works at first try, sometimes not.

**Comment by danacr** [comment]
I'm running Ubuntu, it doesn't attach on the first try, but within 1-2 minutes the PVC is there.

**Comment by walkerandco** [comment]
Didn't you guys have to specify the volume for the FlexVolume plugin directory?
