### ISSUE TITLE
Provide also an "all-in" admin.kubeconfig

### ISSUE THREAD

**Issue by 205g0** [k3s-io/k3s#3263]
**Is your feature request related to a problem? Please describe.**
I want to copy and paste `admin.kubeconfig` into Lens on my desktop but I can't—this file redirects to cert files on the latest k3s (`1.21`).

**Describe the solution you'd like**
Provide a second file where everything is included and which I can just copy and paste.

**Describe alternatives you've considered**
Just using k9s.

**Additional context**
k0s offers such an all-in config.

**Comment by brandond** [comment]
Have you checked the file at /etc/rancher/k3s/k3s.yaml as covered in the [documentation](https://rancher.com/docs/k3s/latest/en/cluster-access/)?

**Comment by 205g0** [comment]
Cool, I had checked `/var/lib/rancher/k3s/k3s.yaml` but unfortunately not `/etc/rancher/k3s/k3s.yaml`. Btw, do you know why this file sits lonely in `/etc/`? So, I know it and head next time intuitively to `/etc/`.
