### ISSUE TITLE
Failed to retrieve agent config: \"overlayfs\" snapshotter cannot be enabled

### ISSUE THREAD

**Issue by Bl00d-B0b** [k3s-io/k3s#3266]
Hello,

I try to install k3s v1.20.6+k3s1 on my Raspberry PI 4B. And receiving error message:
"Failed to retrieve agent config: \"overlayfs\" snapshotter cannot be enabled for \"/var/lib/rancher/k3s/agent/containerd\", try using \"fuse-overlayfs\" or \"native\": failed to mount overlay: invalid argument"

I assume, I know where is an issue, but I don't have today enough k3s experience, and need help.

My Raspberry do not have any local storage, I use PXE boot from nfs. for NFS I use TrueNAS.

I assume I need to configure snapshotter for NFS, but's can't find a solution.

Ed

**Comment by brandond** [comment]
You cannot run containerd on a NFS root. If you must boot over the network, you might try using an iscsi disk instead of NFS.

**Comment by Bl00d-B0b** [comment]
Hello,

this was my assumption. but Raspberry supports only NFS PXE boot. I assume I need to try change eeprom firmware. As I google, it's possible.

Ed

**Comment by brandond** [comment]
You could always boot off NFS and then mount an iscsi disk somewhere. That's getting pretty complicated though.

**Comment by windowsrefund** [comment]
Wondering if some additional information about overlayfs can be made available (or pointed to as it relates to k3s) as I am running into the same blocker despite not using NFS in any way. I'm attempting to run k3s on LXD containers that are using a zfs formatted storage pool (single local block device). I'm seeing the exact error in my logs when I run 'k3s server' inside my LXD container.

**Comment by brandond** [comment]
Snapshotters are part of containerd: https://github.com/containerd/containerd/blob/master/design/snapshots.md
