### ISSUE TITLE
Add the Ability to List etcd Snapshots from the CLI

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3269]
**Is your feature request related to a problem? Please describe.**

For the best possible integration into Rancher, we need to provide the ability to list snapshots created by etcd.

**Describe the solution you'd like**

This command will be `ls` and take the necessary flags to list locally stored snapshots and snapshots stored in an S3 compatible object store.

Running this operation will have an effect on the contents of the snapshots ConfigMap by removing matching entries.

Example:

```sh
k3s etcd-snapshot ls
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ShylajaDevadiga** [comment]
Validated ls lists snapshots stored locally on the node as well as all snapshots from s3 bucket 
k3s v1.21.1-rc1+k3s1
```
sudo k3s etcd-snapshot ls
etcd-snapshot-ip-172-31-47-221-1621413660 file:///var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-ip-172-31-47-221-1621413660 3309600 2021-05-19T08:41:00Z
etcd-snapshot-ip-172-31-47-221-1621413720 file:///var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-ip-172-31-47-221-1621413720 3309600 2021-05-19T08:42:00Z
```
```
sudo k3s etcd-snapshot ls --s3 --s3-bucket=...
```
