### ISSUE TITLE
Add the Ability to Prune etcd Snapshots from the CLI

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3278]
**Is your feature request related to a problem? Please describe.**

For the best possible integration into Rancher, we need to provide the ability to prune snapshots created by etcd. This subcommand off of the `etcd-snapshot` command will force run of the etcd snapshot retention policy.

**Describe the solution you'd like**

This command will be `ls` and take the necessary flags to list locally stored snapshots and snapshots stored in an S3 compatible object store.

Running this operation will have an effect on the contents of the snapshots ConfigMap by removing matching entries.

Example:

```sh
k3s etcd-snapshot prune
```

**Describe alternatives you've considered**

**Additional context**

**Comment by briandowns** [comment]
Verification procedure can be found in #3310

**Comment by ShylajaDevadiga** [comment]
Currently prune subcommand works on pruning local snapshots based on count passed to --snapshot-retention. Does not prune snapshots from s3 bucket
```
sudo k3s etcd-snapshot prune  --snapshot-retention=3 --s3 ...
```
Needs documentation mentioning prune subcommand works only with scheduled snapshot and not meant for on demand snapshots.

**Comment by briandowns** [comment]
#3340 will resolve the above mentioned issue.

**Comment by ShylajaDevadiga** [comment]
Validated using commit id
k3s version v1.21.1+k3s-5bf4d9f6
Passing subcommand prune with s3 params prunes snapshotss from s3 bucket.
```
sudo k3s etcd-snapshot prune  --snapshot-retention=1 --s3 ...
```
