### ISSUE TITLE
failed to find memory cgroup

### ISSUE THREAD

**Issue by ItsDrike** [k3s-io/k3s#3293]
I've just installed Arch Linux on my server (bare-metal) and I wanted to run rancher on it, through docker. I used:
`docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher`

I waited for a while and eventually, since I wasn't able to connect to the control panel.
In the docker log output I found out that k3s failed with error message of: 
`Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)`

This is quite weird since I don't have any `/boot/cmdline.txt` file and I'm certainly not on a Raspberry Pi, this is bare-metal arch server.

This is complete log from the rancher docker container: http://ix.io/3mlb

**Comment by Oats87** [comment]
That is a generic message stating that the memory cgroup is not available, hence why it is providing a Raspberry Pi message. Does your system actually have cgroups enabled?

**Comment by ItsDrike** [comment]
> That is a generic message stating that the memory cgroup is not available, hence why it is providing a Raspberry Pi message. Does your system actually have cgroups enabled?

I am not sure what are cgroups nor how to enable them, could you explain what are they for exactly? I assume I can enable them just by putting those values as grub kernel parameters? Or is there something more that needs to be installed/done?

**Comment by ItsDrike** [comment]
I tried adding `cgroup_memory=1 cgroup_enable=memory` to my linux command parameters through grub
(
in `/etc/default/grub`: `GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet nomodeset cgroup_memory=1 cgroup_enable=memory"` after which I've ran `grub-mkconfig`
)

but even with those kernel parameters, the error is still there. I'm not at all sure what's wrong here, or was I supposed to add those parameters elsewhere?

**Comment by prathamesh-gharat** [comment]
Note: If you are using something like Berryboot, editing `/boot/cmdline.txt` or `/boot/firmware/cmdline.txt` from inside the OS might not work ( test using `cat /proc/cmdline` ).

Try removing the SD card and editing the `{sdcard}/cmdline.txt`
Worked for me.
