### ISSUE TITLE
CrashLoopBackoff after fresh install (https://10.43.0.1:443: connection refused)

### ISSUE THREAD

**Issue by Sebastian-Landl** [k3s-io/k3s#3297]
**Environmental Info:**
K3s Version: 
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10

Node(s) CPU architecture, OS, and Version: 
Linux 5.8.0-50-generic #56~20.04.1-Ubuntu SMP x86_64 GNU/Linux

Cluster Configuration:
1 Server

**Describe the bug:**
After installing k3s `local-path-provisioner`, `metrics-server`, and `helm-install-traefik` are stuck in `CrashLoopBackoff`. It seems to be, because they all run into a similar error along the lines of: `Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused"`

**Steps To Reproduce:**
`sudo sysctl -w net.ipv4.ip_forward=1` (This solved a networking issue for me once)
`export K3S_EXTERNAL_IP=<external_ip>`
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --tls-san $K3S_EXTERNAL_IP  --node-external-ip=$K3S_EXTERNAL_IP" sh -`

**Expected behavior:**
The pods should be up and running

**Actual behavior:**
The three pods mentioned above are stuck in `ChrashLoopBackoff`. All their logs indicate a failure to contact: `https://10.43.0.1:443`, the connection was refused. Here is the output of `kubectl get pods -A`:
```
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   coredns-854c77959c-7dm7j                  0/1     Running            0          14m
kube-system   local-path-provisioner-5ff76fc89d-zqh92   0/1     CrashLoopBackOff   7          14m
kube-system   metrics-server-86cbb8457f-pkhtr           0/1     CrashLoopBackOff   7          14m
kube-system   helm-install-traefik-lrfzm                0/1     CrashLoopBackOff   7          14m
```

**Additional context / logs:**
I did a `kubectl get services -A` to see, if `10.43.0.1:443` was up and it seems yes, this is the output:
```
NAMESPACE     NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes       ClusterIP   10.43.0.1       <none>        443/TCP                  15m
kube-system   kube-dns         ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   15m
kube-system   metrics-server   ClusterIP   10.43.136.178   <none>        443/TCP                  15m
```

**Comment by Sebastian-Landl** [comment]
I have neither `ufw` or `firewalld` installed. All I have is a plain Ubuntu 20.04.1 install hosted in AWS. I have `iptables`, here's the output of `iptables -S` (not configured by me manually, I guess k3s configured that):
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N KUBE-EXTERNAL-SERVICES
-N KUBE-FIREWALL
-N KUBE-FORWARD
-N KUBE-KUBELET-CANARY
-N KUBE-PROXY-CANARY
-N KUBE-ROUTER-FORWARD
-N KUBE-ROUTER-INPUT
-N KUBE-ROUTER-OUTPUT
-N KUBE-SERVICES
-A INPUT -m comment --comment "kube-router netpol - 4IA2OSFRMVNDXBVV" -j KUBE-ROUTER-INPUT
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "kube-router netpol - TEMCG2JMHZYE7H7T" -j KUBE-ROUTER-FORWARD
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A FORWARD -s 10.42.0.0/16 -j ACCEPT
-A FORWARD -d 10.42.0.0/16 -j ACCEPT
-A OUTPUT -m comment --comment "kube-router netpol - VEAAIY32XVBHCSCY" -j KUBE-ROUTER-OUTPUT
-A OUTPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FIREWALL ! -s 127.0.0.0/8 -d 127.0.0.0/8 -m comment --comment "block incoming localnet connections" -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -j DROP
-A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-ROUTER-INPUT -d 10.43.0.0/16 -m comment --comment "allow traffic to cluster IP - M66LPN4N3KB5HTJR" -j RETURN
-A KUBE-ROUTER-INPUT -p tcp -m comment --comment "allow LOCAL TCP traffic to node ports - LR7XO7NXDBGQJD2M" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
-A KUBE-ROUTER-INPUT -p udp -m comment --comment "allow LOCAL UDP traffic to node ports - 76UCBPIZNGJNWNUZ" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
-A KUBE-SERVICES -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics has no endpoints" -m tcp --dport 9153 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.43.14.30/32 -p tcp -m comment --comment "kube-system/metrics-server has no endpoints" -m tcp --dport 443 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.43.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreachable
```

**Comment by Sebastian-Landl** [comment]
No, I get:
```
*   Trying NODE-EXTERNAL-IP:6443...
* TCP_NODELAY set
```
At that point I waited a bit, but nothing happened anymore.

**Comment by brandond** [comment]
Sounds like you need to open things up on the security groups.

**Comment by Sebastian-Landl** [comment]
Your help is appreciated, but I'd have to do some more research in order to figure out exactly what you mean. Anyway, our network infrastructure has changed, so that the arguments `--tls-san $K3S_EXTERNAL_IP --node-external-ip=$K3S_EXTERNAL_IP` are not needed anymore and without them the install works fine.

However, as `k3s` manipulates the iptables rules upon installation anyway, wouldn't it be possible for this to work out-of-the-box even with the `--tls-san $K3S_EXTERNAL_IP --node-external-ip=$K3S_EXTERNAL_IP` arguments by performing the right iptables adjustments during installation of `k3s`? Or does my original problem lie somewhere else?

**Comment by brandond** [comment]
No, security groups are form of firewall policy configured in AWS. They are unrelated to the iptables rules on the node itself.

**Comment by Sebastian-Landl** [comment]
Oh, I see, thanks for clearing that up. That could be the problem. Currently it looks like we won't be using AWS in the future and if that's the case I won't get the chance to figure this out. In that case I'll close this issue in a couple of days. Otherwise I'll document my progress on that problem here.

**Comment by Sebastian-Landl** [comment]
Closing this issue, as it is apparently an AWS security groups issue and we're not using AWS anymore.
