### ISSUE TITLE
Rename RBAC resources for K3s integrated cloud-controller-manager

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3308]
The K3s cloud-controller-manager should use unique names for its RBAC resources (ClusterRole, ClusterRoleBinding, etc) so that it does not conflict with resources created by out-of-tree cloud providers:

https://github.com/rancher/rancher/issues/32604

**Comment by dereknola** [comment]
Closed issue on accident.

**Comment by brandond** [comment]
Moving this to 1.22 milestone as it's only fixed on master, we'll need a separate issue to track backporting to release-1.21

**Comment by rancher-max** [comment]
#### Validated on master branch commitid: `88f95ec409eeb6a2d1330a836b0d1b960a3b5c31`

- ClusterRole and ClusterRoleBinding are both updated to be prefixed with k3s:
```
$ k get clusterroles,clusterrolebindings | grep -i cloud-controller
clusterrole.rbac.authorization.k8s.io/k3s-cloud-controller-manager                                           2021-06-15T17:57:47Z
clusterrolebinding.rbac.authorization.k8s.io/k3s-cloud-controller-manager                           ClusterRole/k3s-cloud-controller-manager                           3m14s
```
- ProviderID is still set by default on the nodes:
```
$ k describe nodes | grep -i provider
ProviderID:                   k3s://ip-172-31-25-148
```
