### ISSUE TITLE
Add "Save" subcommand to etcd-snapshot

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3309]
**Is your feature request related to a problem? Please describe.**

For the best possible integration into Rancher, we need to provide the ability to save snapshots created by etcd. This subcommand off of the `etcd-snapshot` command will cause etcd to create a snapshot with the given config options. 

This is duplicate functionality since the `k3s etcd-snapshot` command will do the same thing. Since this has been already released as functionality, we're keeping it the same for now.

**Describe the solution you'd like**

This command will be `save` and take the necessary flags to save snapshots locally and to S3 compatible object store.

Running this operation will have an effect on the contents of the snapshots ConfigMap by adding entries.

Example:

```sh
k3s etcd-snapshot save
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ShylajaDevadiga** [comment]
Using commit for validation:
k3s version v1.21.1+k3s-7e175e8a (7e175e8a)

- Validated **sudo k3s etcd-snapshot** as well as **sudo k3s etcd-snapshot save** both created the snapshot in the predefined dir. 
- Validated snapshot creation in s3 bucket as well using subcommand save


```
ubuntu@ip-172-31-13-137:~$ sudo k3s etcd-snapshot ls
on-demand-ip-172-31-13-137-1621379496 file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-13-137-1621379496 950304 2021-05-18T23:11:36Z
on-demand-ip-172-31-13-137-1621379501 file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-13-137-1621379501 978976 2021-05-18T23:11:41Z
ubuntu@ip-172-31-13-137:~$ sudo kubectl get cm -n kube-system k3s-etcd-snapshots -o json
{
    "apiVersion": "v1",
    "data": {
        "on-demand-ip-172-31-13-137-1621379496": "{\"name\":\"on-demand-ip-172-31-13-137-1621379496\",\"location\":\"file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-13-137-1621379496\",\"nodeName\":\"ip-172-31-13-137\",\"createdAt\":\"2021-05-18T23:11:36Z\",\"size\":950304}",
        "on-demand-ip-172-31-13-137-1621379501": "{\"name\":\"on-demand-ip-172-31-13-137-1621379501\",\"location\":\"file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-13-137-1621379501\",\"nodeName\":\"ip-172-31-13-137\",\"createdAt\":\"2021-05-18T23:11:41Z\",\"size\":978976}"
    },
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2021-05-18T23:11:20Z",
        "name": "k3s-etcd-snapshots",
        "namespace": "kube-system",
        "resourceVersion": "546",
        "uid": "cd9de320-d9eb-4613-ad33-d837b4788653"
    }
}
ubuntu@ip-172-31-13-137:~$
```
