### ISSUE TITLE
K3S - Rotating registries.yaml/config.toml credentials

### ISSUE THREAD

**Issue by billykwooten** [k3s-io/k3s#3314]
Hey guys, so currently K3S does not support ImagePullSecrets objects, especially since docker support is being deprecated. The solution to that is to use the registries.yaml file for k3s (https://rancher.com/docs/k3s/latest/en/installation/private-registry/) to set private registry authentication credentials. That presents a problem for lots of enterprises that auto-rotate secrets, issue described below:

**Is your feature request related to a problem? Please describe.**
This is an issue for enterprises that auto-rotate private registry authentication credentials. In our case when our credential passwords rotate we will have to update registries.yaml on all k3s host and restart all k3s systemd services. As of right now from what I can tell registries.yaml configures the containerd config.toml file, thus containerd does not hot-reload this configuration and a k3s service restart is needed.

**Describe the solution you'd like**
The solution up for discussion here is for k3s and/or containerd to hot reload registries.yaml and/or config.toml for containerd via a goroutine without having to restart the entire control plane across all k3s nodes. 

**Describe alternatives you've considered**
At this point I don't have many alternatives with `--docker` not being supported soon and lack of hot-reloading of registries.yaml/config.toml. I am not sure how to use k3s with rotating registry credentials without restarting the control plane at this point.

If anyone has any input into this it would be much appreciated, this is up for discussion.

**Comment by brandond** [comment]
What do you mean we don't support ImagePullSecrets? These are a core Kubernetes feature, not tied to the container runtime, and we certainly do support it.

Upstream is moving towards kubelet image credential provider plugins for system-level auth to cloud-based registries (ECR, GCR, etc) so that's probably what you should be looking for. It's currently still in alpha as of 1.21, but we're adding some scaffolding to support this as part of our core private registry support. See: https://github.com/rancher/wharfie

**Comment by billykwooten** [comment]
Ok, I'll definitely test ImagePullSecrets, from my research it looked like you guys didn't support them when reading https://github.com/k3s-io/k3s/issues/502.

Let me look into the link you posted however, that might be exactly what I'm looking for, I definitely appreciate the information.

**Comment by brandond** [comment]
That thread was closed with https://github.com/k3s-io/k3s/issues/502#issuecomment-739093745

**Comment by billykwooten** [comment]
Yep, just tested with imagePullSecrets and that will work in the short term for me, going ahead with closing this as the above https://github.com/rancher/wharfie is definitely what I was looking for as a future solution. 

Much appreciated @brandond.
