### ISSUE TITLE
Failed to create pod sandbox operation timeout: context deadline exceeded

### ISSUE THREAD

**Issue by maxianwei** [k3s-io/k3s#3325]
**Environmental Info:**
K3s Version: 
root@admin-k3s-test:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

root@admin-k3s-test:~# docker  version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Node(s) CPU architecture, OS, and Version: 

Linux admin-k3s-test 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
root@admin-k3s-test:~# kubectl get node
NAME             STATUS   ROLES                  AGE     VERSION
admin-k3s-test   Ready    control-plane,master   4d22h   v1.20.6+k3s1

**Describe the bug:**

root@admin-k3s-test:~# kubectl get po  -A  |grep  local
local-path-storage   local-path-provisioner-5696dbb894-8kwlz   0/1     ContainerCreating   0          41m

**Steps To Reproduce:**
- Installed K3s: 
offline

**Expected behavior:**
pod created

**Actual behavior:**
Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               40m                    default-scheduler  Successfully assigned local-path-storage/local-path-provisioner-5696dbb894-8kwlz to admin-k3s-test
  Warning  FailedCreatePodSandBox  38m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "local-path-provisioner-5696dbb894-8kwlz": operation timeout: context deadline exceeded
  Warning  FailedSync              2m30s (x118 over 36m)  kubelet            error determining status: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Additional context / logs:**

May 13 14:03:16 admin-k3s-test k3s[1426]: I0513 14:03:16.352033    1426 setters.go:577] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2021-05-13 14:03:16.351999146 +0800 CST m=+68940.369784799 LastTransitionTime:2021-05-13 14:03:16.351999146 +0800 CST m=+68940.369784799 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active 3m6.817660533s ago; threshold is 3m0s}
May 13 14:03:16 admin-k3s-test k3s[1426]: E0513 14:03:16.535996    1426 kubelet.go:1857] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m7.001638124s ago; threshold is 3m0s
May 13 14:03:19 admin-k3s-test k3s[1426]: I0513 14:03:19.795001    1426 node_lifecycle_controller.go:1195] Controller detected that all Nodes are not-Ready. Entering master disruption mode.
May 13 14:03:21 admin-k3s-test k3s[1426]: E0513 14:03:21.536125    1426 kubelet.go:1857] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m12.001757892s ago; threshold is 3m0s
May 13 14:03:22 admin-k3s-test k3s[1426]: E0513 14:03:22.127278    1426 horizontal.go:227] failed to compute desired number of replicas based on listed metrics for Deployment/istio-system/istio-ingressgateway: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
May 13 14:03:22 admin-k3s-test k3s[1426]: I0513 14:03:22.127349    1426 event.go:291] "Event occurred" object="istio-system/istio-ingressgateway" kind="HorizontalPodAutoscaler" apiVersion="autoscaling/v2beta2" type="Warning" reason="FailedGetResourceMetric" message="failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API"

can you help me?

**Comment by cheng0214** [comment]
Encountered a similar problem
