### ISSUE TITLE
README Quick-Start - Install Script does no work with IPv4 on multiple machines

### ISSUE THREAD

**Issue by bluepuma77** [k3s-io/k3s#3334]
**Environmental Info:**
K3s Version: 
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10

Node(s) CPU architecture, OS, and Version: 
Linux test 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

Cluster Configuration:
2 separate VMs with Internet-reachable v4 IPs

**Describe the bug:**
Newbie, trying to get started with K3s according to the short README [Quick-Start - Install Script](https://github.com/k3s-io/k3s/blob/master/README.md). It's just two commands, but the second one does not work. It seems the agent can not connect to master. I assume it's because master is just listening on localhost instead of the external IP.

Either "Quick-Start - Install Script" should mention that it's just working on the same machine **or** the server should listen on all IPs. **Or** at least show how to set the correct IP to bind. **But in Quick-Start current state it's confusing and not working for everyone.**

**Steps To Reproduce:**
Install k3s as a service according to docs (on master): 
```
// machine-1 master
curl -sfL https://get.k3s.io | sh -
cat /var/lib/rancher/k3s/server/node-token
```

Install k3s as agent according to docs:
```
// machine-2 agent
// using K207fc1e...::server:bc8864dd... from machine-1 as TOKEN
curl -sfL https://get.k3s.io | K3S_URL=https://machine-1:6443 K3S_TOKEN=XYZ sh -
```

**Expected behavior:**
Run commands according to "Quick-Start - Install Script" on two different machines and having agent connect to master.

**Actual behavior:**
Agent does not connect to master, seems master is only listening on localhost.

**Additional context / logs:**
```
# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:31710           0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 0.0.0.0:31798           0.0.0.0:*               LISTEN      912/k3s server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      739/sshd
tcp        0      0 127.0.0.1:10010         0.0.0.0:*               LISTEN      937/containerd
tcp6       0      0 :::10250                :::*                    LISTEN      912/k3s server
tcp6       0      0 :::6443                 :::*                    LISTEN      912/k3s server
tcp6       0      0 :::22                   :::*                    LISTEN      739/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           512/dhclient
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
```

**Comment by bluepuma77** [comment]
It works with IPv6, though. Is this a bug or a feature?

At least it should be stated in the "Quick-Start - Install Script" README.

**Comment by bluepuma77** [comment]
I tried to manually change the listening address in `/etc/rancher/k3s/k3s.yaml` from `127.0.0.1` to `0.0.0.0`.

After a reboot it is back to `127.0.0.1` ?!?

**Comment by bluepuma77** [comment]
```
k3s-killall
k3s server --bind-address=12.34.56.78 &
```
This way I get the master to listen on IPv4, but how can I persist it?

I still wonder why k3s server it is just listening on IPv6 and why this is not documented.

Sidenote: `k3s kubectl get node -o wide` shows my external IPs as `INTERNAL-IP` and no `EXTERNAL-IP`

**Comment by bluepuma77** [comment]
This can be used to bind the k3s server to a specified IPv4 address

**Install k3s master on a fresh Debian server**
```
# update
apt update && apt -y upgrade

# get first IP address (quick hack)
IP=$(hostname -I | cut -d' ' -f1)
echo "Using IP $IP"

# install k3s master, specify IP address to use
curl -sfL https://get.k3s.io | sh -s - server --bind-address $IP --advertise-address $IP

# get token for agents
cat /var/lib/rancher/k3s/server/node-token
```
For later: check nodes
```
k3s kubectl get node -o wide
```
Optional: install Portainer web GUI (access on IP:30777) 
```
sudo kubectl apply -n portainer -f https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/portainer/portainer.yaml
```

**Install k3s agent on another fresh Debian server**
```
# update
apt update && apt -y upgrade

# set values (from master)
IP="12.34.56.78"
TOKEN="K123990875b170106e82df1127ee974ce1b::server:3821e0d0d0c03f22dd3c"

# install k3s agent
curl -sfL https://get.k3s.io | K3S_URL=https://$IP:6443 K3S_TOKEN=$TOKEN sh -
```
It's great to be an engineer, you can solve puzzles all day long 😄

**Comment by brandond** [comment]
You shouldn't need to jump through all these hoops. Up until recently K3s did not support IPv6 at all, and is still definitely not required.

I think you may have confused yourself a bit - note that processes listening on a IPv6 wildcard address can also receive connections from IPv4 clients:

```shell
[root@centos01 ~]# netstat -tulpn | grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      1052/k3s server

[root@centos01 ~]# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.137  netmask 255.255.255.0  broadcast 10.0.1.255
        inet6 fe80::5054:ff:fea9:2f1a  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:a9:2f:1a  txqueuelen 1000  (Ethernet)
        RX packets 930125  bytes 1336794463 (1.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 404505  bytes 28325814 (27.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@centos01 ~]# curl -ks https://10.0.1.137:6443/ping; echo
pong
```

Unfortunately you didn't include any logs from the agent when it failed to join the server, so I can't really say what WAS going on.

**Comment by Symbiatch** [comment]
Just a note: I had similar issue with another project (libwebsocket) and what I assume is a kernel/distro feature: if a bind was done to the IPv6 wildcard address I couldn't connect to it via IPv4. I had to modify it to bind to IPv4 wildcard address for this to work. This might be the same thing, since your listing correctly shows bound to IPv6 wildcard, it allows IPv6 connections, but not IPv4, and it works if you change it to IPv4 specific address (or wildcard most likely). I did not find any reason for this, and others assumed it might be due to specific kernel/library version. I was using Debian 10/11 and their latest kernels. 

So if there's a way for you to set it to 0.0.0.0 somewhere that might fix this issue. But I'd like to know what exactly causes this since I'm sure we aren't the only two people who run into this problem.

**Comment by bluepuma77** [comment]
@Symbiatch Was your issue with Debian, too?

**Comment by bluepuma77** [comment]
@brandond What logs do you need? How do I get them?

**Comment by Symbiatch** [comment]
> @Symbiatch Was your issue with Debian, too?

Yes, it happened on Debian
