### ISSUE TITLE
Add "install.sh" as release artifact

### ISSUE THREAD

**Issue by ChristianCiach** [k3s-io/k3s#3338]
We usually install k3s inside airgapped environments, and we're using the shellscript https://github.com/k3s-io/k3s/blob/master/install.sh for the installation (using `INSTALL_K3S_SKIP_DOWNLOAD=true`), which can also be retrieved from https://get.k3s.io/ .

Now, every time we download a new k3s release from the github releases page, we also have to manually download the new install script from https://get.k3s.io/, to make sure that the install script and the new `k3s` binary are compatible to each other.

While I assume that new install scripts are generally compatible to older versions of k3s, I am not too sure that old install scripts are guaranteed to be compatible with newer versions of k3s.

I would prefer to not even have to think about these things. So, to sidestep this issue completely, I think the script `install.sh` should be part of a versioned k3s release and downloadable as an artifact from the release page.

**Comment by Oats87** [comment]
The issue I have with just blindly including the `install.sh` script as an artifact is that it will attempt to download the latest version of K3s. If we were to release a versioned `install.sh` script, I would imagine it should install that specific version of K3s, but that would mean performing on-the-fly renderings of the `install.sh` script when we release it. 

That being said, we do occasionally make tweaks to the install script that improve overall functionality of the script, and are still compatible with the older K3s versions.

**Comment by ChristianCiach** [comment]
> that it will attempt to download the latest version of K3s

That's a good point.

Maybe it is good enough for us to just manually download the latest install.sh from https://get.k3s.io/ whenever we download a new release. Or maybe we should just ditch the install.sh altogether and build our own Ansible playbook for deployment. (We cannot use https://github.com/k3s-io/k3s-ansible because we are deploying a multi-master setup with embedded etcd.)

I don't know what's the best solution here. Feel free to close the issue if you think that the current solutions are good enough.

**Comment by Oats87** [comment]
I don't believe the current solutions are good enough, but I am just stating that the "proper" solution to this is not as cut and dry as just including the install script in the github artifacts.

We can keep this issue open to keep track of this and any progress that is made. I am on the train of thought that we should simply render a per-version install script that is included with the github artifacts.

If you really want to guarantee install script compatibility, just download the install script out of the corresponding tagged release of the binary you are using.

**Comment by ChristianCiach** [comment]
> If you really want to guarantee install script compatibility, just download the install script out of the corresponding tagged release of the binary you are using.

Thanks, that is a good idea!

I just occurred to me that a custom playbook as a replacement for the `install.sh` creates pretty much the same issue. In this case, I would need to keep the systemd unit file in sync with https://github.com/k3s-io/k3s/blob/master/k3s.service, which isn't a release artifact, either.

**Comment by ChristianCiach** [comment]
Would still be nice to have, but I can live with grabbing the file directly from the git tag.

I think this issue is similar to https://github.com/k3s-io/k3s/issues/4181
