### ISSUE TITLE
Update etcd-snapshot-retention flag(s) to indicate default of 5

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3339]
**Is your feature request related to a problem? Please describe.**

Add default value for the etcd rentention flag for server command and etcd-snapshot command.

**Describe the solution you'd like**

Add default value for etcd rentention.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShylajaDevadiga** [comment]
Validated using commit 
k3s version v1.21.1+k3s-5bf4d9f6
```
sudo k3s etcd-snapshot prune --help |grep retention
   k3s etcd-snapshot prune - Remove snapshots that exceed the configured retention count
   --snapshot-retention value  (db) Number of snapshots to retain. Default: 5 (default: 5)
```
