### ISSUE TITLE
How to cleanup k3s agent manually?

### ISSUE THREAD

**Issue by cupen** [k3s-io/k3s#3363]
So where is `k3s-agent-uninstall.sh`? 
https://rancher.com/docs/k3s/latest/en/installation/uninstall/

I run k3s agent on my host, then all of my https web service down.  It seems that it changed my ipatbles rules and root CA? So how to clean it manually?

**Comment by cupen** [comment]
I try to make workaround for install k3s scripts, it works.

1. Download the bash script, but don't exec it.
```
curl -sfL https://get.k3s.io > k3s.sh
```
2. Modify the last lines, then run it for install k3s script.
```
{                                                                                                                                       
    verify_system
    setup_env "$@"
    create_killall
    create_uninstall
    create_env_file
}
```
3. Now, run the `/usr/local/bin/k3s-uninstall.sh`.

**Comment by smutel** [comment]
Do you know which github repo I need to fork to do a PR on k3s.sh script ?
