### ISSUE TITLE
Agent can't connect to Server

### ISSUE THREAD

**Issue by DebakelOrakel** [k3s-io/k3s#3364]
**Environmental Info:**
k3s version v1.20.7+k3s1 (aa768cbd)
go version go1.15.12

Cluster Configuration:
3 servers with 2 network interfaces.
10.10.10.0/24: public network
10.10.0.0/24: cluster network

**Describe the bug:**
The agent is not able to connect to the servers:
```
# k3s agent
INFO[2021-05-23T15:33:42.557102854Z] Starting k3s agent v1.20.7+k3s1 (aa768cbd)
INFO[2021-05-23T15:33:42.557934295Z] Running load balancer 127.0.0.1:45775 -> [10.10.10.13:6443 10.10.10.12:6443 10.10.10.11:6443 10.10.0.11:6443]
ERRO[2021-05-23T15:34:02.558961317Z] failed to get CA certs: Get "https://127.0.0.1:45775/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
10.10.10.0/24 is not reachable from node.

**Steps To Reproduce:**
- Installed K3s servers
- Install K3s agent
```
export K3S_TOKEN=<TOKEN_FROM_ABOVE>
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://10.10.0.11:6443" sh -
```

**Expected behavior:**
Loadbalancer (above) configured with correct interfaces

**Actual behavior:**
Agent using wrong ips for loadbalancer

**Comment by brandond** [comment]
The agents must be able to reach the server nodes at their listed addresses. The fixed registration endpoint specified by the --server flag is only used for initial bootstrapping - once that is complete the nodes connect directly to the servers at their listed addresses.
