### ISSUE TITLE
[Feature request] Support CIDR for --tls-san option

### ISSUE THREAD

**Issue by joeky888** [k3s-io/k3s#3368]
Instead of

```fish
k3s server --tls-san 10.0.0.1 --tls-san 10.0.0.2 ... --tls-san 10.255.255.255
```

I would like to use it as below

```fish
k3s server --tls-san "10.0.0.0/8" --tls-san "192.168.0.0/16"
```

Where 10.0.0.0/8 indicates the range `10.x.x.x`, and 192.168.0.0/16 indicates the range `192.168.x.x`.

**Comment by brandond** [comment]
There is no support for this in TLS clients. See: https://security.stackexchange.com/questions/91368/ip-range-in-ssl-subject-alternative-name

**Comment by joeky888** [comment]
> There is no support for this in TLS clients.

Thanks, good to know. However,

Is it possible to make a "polyfill" for this? By "polyfill" I meant [expanding the CIDR](https://play.golang.org/p/m8TNTtygK0) `--tls-san 192.168.0.0/16` to `--tls-san 192.168.0.0 --tls-san 192.168.0.1 .... --tls-san 192.168.255.255` in k3s code. Or is it a bad practice?

**Comment by brandond** [comment]
You could probably do that with a shell script, but at some point the list would get so long that the certificate would no longer be accepted by clients.  If you find yourself needing this, the answer is probably to get working DNS and add a wildcard record to the cert.
