### ISSUE TITLE
Using the --tls-san option to update the cluster does not take effect

### ISSUE THREAD

**Issue by kingsd041** [k3s-io/k3s#3369]
**Environmental Info:**
K3s Version:  v1.20.7+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux ip-172-31-6-197 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 server

**Describe the bug:**

Update the k3s cluster and add the `--tls-san` option. After the update is successful, the corresponding ip is not added to the `k3s-serving`

**Steps To Reproduce:**

- Installed K3s: 
```
curl -sfL https://get.k3s.io | sh -
```
- Update the cluster, add the `--tls-san` option
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san 172.31.13.97" sh -
```

**Expected behavior:**

`172.31.13.97` is added to the `annotations` list of secret k3s-serving

**Actual behavior:**

`172.31.13.97` is not added to the `annotations` list of secret k3s-serving, and k3s API cannot be accessed through `172.31.13.97`

```
# kubectl get nodes
Unable to connect to the server: x509: certificate is valid for 10.43.0.1, 127.0.0.1, 172.31.2.134, 172.31.2.42, not 172.31.13.97
```

**Additional context / logs:**

```
# kubectl -n kube-system get secret k3s-serving -o yaml
kind: Secret
metadata:
  annotations:
    listener.cattle.io/cn-10.43.0.1: 10.43.0.1
    listener.cattle.io/cn-127.0.0.1: 127.0.0.1
    listener.cattle.io/cn-172.31.6.197: 172.31.6.197
    listener.cattle.io/cn-kubernetes: kubernetes
    listener.cattle.io/cn-kubernetes.default: kubernetes.default
    listener.cattle.io/cn-kubernetes.default.svc.cluster.local: kubernetes.default.svc.cluster.local
    listener.cattle.io/cn-localhost: localhost
...
```

**Comment by brandond** [comment]
SANs should be added to the dynamiclistener cert on demand. What do you get from the following:
```bash
curl -vk --resolve 172.31.13.97:6443:127.0.0.1  https://172.31.13.97:6443/ping
kubectl get nodes
```

**Comment by aisensiy** [comment]
> SANs should be added to the dynamiclistener cert on demand, based on the SNI hostname requested by the client. Try running the following on the server:
> 
> ```shell
> curl -vk --resolve 172.31.13.97:6443:127.0.0.1  https://172.31.13.97:6443/ping
> ```

This is sooo cool. It solved a great problem for me. But could you please give me some explain for me. ChatGPT doest not help...

**Comment by grstearns** [comment]
> > SANs should be added to the dynamiclistener cert on demand, based on the SNI hostname requested by the client. Try running the following on the server:
> > ```shell
> > curl -vk --resolve 172.31.13.97:6443:127.0.0.1  https://172.31.13.97:6443/ping
> > ```
> 
> This is sooo cool. It solved a great problem for me. But could you please give me some explain for me. ChatGPT doest not help...

For you and all the googlers out there that have landed here: `-v` is responsible for the verbose output, `-k` lets the request go through even if the cert should be rejected. The magic is in `--resolve` which fakes DNS resolution (in this case it's not even DNS, but it still works since it's basically a find/replace) for the given input. In this case it says "when you try to make a connection to 172.31.13.97 on 6443, call 127.0.0.1 instead, but still use the 172 address in host headers".
