### ISSUE TITLE
CreateContainerError with version v1.21.0+k3s1

### ISSUE THREAD

**Issue by brlbil** [k3s-io/k3s#3370]
**Environmental Info:**
K3s Version:
k3s version v1.21.0+k3s1 (2705431d)
go version go1.16.2

Node(s) CPU architecture, OS, and Version: 

Linux xxxxx 5.4.0-72-generic 80 SMP Tue May 4 19:31:44 UTC 2021 x86_64 GNU/Linux
k3os version v0.21.0-k3s1r0

Cluster Configuration:

Tested with two configurations same result
1 master, 2 agents
3 master, 2 agents

**Describe the bug:**

After installing v0.21.0-k3s1r0, I got CreateContainerError on all the pods. In the k3s logs I got the error message below
```
"Error syncing pod, skipping" err="failed to \"StartContainer\" for \"fluent-bit\" with CreateContainerError: \"failed to create containerd container: get apparmor_parser version: exec: \\\"apparmor_parser\\\": executable file not found in $PATH\""
```
**Steps To Reproduce:**

- Installed K3os version v0.21.0-k3s1r0 which is bundled with k3s version v1.21.0+k3s1

**Expected behavior:**

Since contained is bundled with k3s I would expect the pods to be scheduled without any issues.

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
I see there's already an issue for this with k3os that I believe @dweomer is aware of; lets track it there.
