### ISSUE TITLE
Update K3s embedded flannel to v0.14

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3371]
Update K3s embedded flannel to v0.14

We're currently using a post-v0.13.1-rc2 commit off master; we should update this to v0.14 now that it is out.

**Comment by rancher-max** [comment]
There aren't any good logs to show flannel version, but network checks continue to work so this version bump has been validated using commit id: `a7d1159ba6f71f36990fac2a1780fcc3f8621ab6`
