### ISSUE TITLE
[release-1.21] Update embedded kube-router network policy controller

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3374]
Backport kube-router network policy controller update from #3373

**Comment by davidnuzik** [comment]
Not a blocker for release. this is a nice-to-have soon, ideally before 1.22 release.

**Comment by brandond** [comment]
Work should land on #3373 first

**Comment by rancher-max** [comment]
#### Validated using 1.21.2-rc1+k3s2

- There are many new rules added, including the one we are looking for. See https://github.com/k3s-io/k3s/issues/3373#issuecomment-877527072
- Standard checks continue to pass after running these steps
