### ISSUE TITLE
External IP not set of some nodes in larger clusters

### ISSUE THREAD

**Issue by ibalajiarun** [k3s-io/k3s#3377]
**Environmental Info:**
K3s Version: v1.19.10+k3s1

Node(s) CPU architecture, OS, and Version: Azure Standard_D4s_v4 with Ubuntu Linux 18.04

Cluster Configuration: 1 master, 320 agents

**Describe the bug:**

When I run k3s agents with an external IP address and run `kubectl get nodes -o wide`, the external IP addresses for some (about 30) nodes are `nil`. I usually run with 150 nodes and this never occurred, but as I scale to 350 nodes, this is occurring. I am using the default embedded k3s store, and I don't know if this is the limitation. 

Below is part of my systemd config.

```
...
ExecStart=/usr/local/bin/k3s \
    agent \
    --node-label topology.kubernetes.io/region="westus2" \
    --node-label node.kubernetes.io/instance-type="Standard_D4s_v4" \
    --node-label node-role="server" \
    --node-external-ip xx.xx.xx.xx --server https://xxx:6443 --token xxtokenxx
```

**Steps To Reproduce:**

- Installed K3s v1.19.10+k3s1 on 350 nodes
- Set the `--node-external-ip` field in k3s systemd file
- One node is started as master
- All other nodes are agents

**Expected behavior:**

`kubectl get nodes -o wide` should return external IP address for all nodes

**Actual behavior:**

`kubectl get nodes -o wide` shows nil IP address for about 30 nodes (out of 350)

**Additional context / logs:**

**Comment by brandond** [comment]
How many servers do you have, and what are you using for your datastore? What cli flags do you have set on the servers? On the nodes that are missing their external ip, do you see the node ip/hostname labels set?

**Comment by ibalajiarun** [comment]
I have one master and 250 agents. I use the default datastore, which I think is sqlite? This is how I start my server:

```
/usr/local/bin/k3s \
    server \
    --node-label topology.kubernetes.io/region="westus2" \
    --node-label node.kubernetes.io/instance-type="Standard_D4s_v4" \
    --node-label node-role="server" \
    --node-external-ip xx.xx.xx.xx  --disable traefik
```

The following are the labels I see on a node that is missing its external IP.

```
beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=destiny-westus2-vm304
                    kubernetes.io/os=linux
                    node-role=server
                    node.kubernetes.io/instance-type=k3s
                    topology.disk.csi.azure.com/zone=
                    topology.kubernetes.io/region=westus2
```

This one is from the node with IP:

```
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    k3s.io/external-ip=52.235.19.181
                    k3s.io/hostname=destiny-canadaeast-vm4
                    k3s.io/internal-ip=10.0.2.5
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=destiny-canadaeast-vm4
                    kubernetes.io/os=linux
                    node-role=server
                    node.kubernetes.io/instance-type=k3s
                    plan.upgrade.cattle.io/k3s-agent=6e5064f5678a24dca1dcb9d23686e32af4d547242db8fb4cb4634009
                    topology.disk.csi.azure.com/zone=
                    topology.kubernetes.io/region=canadaeast

```

**Comment by brandond** [comment]
Can you provide logs from the first startup of one of the agents with the missing address?

**Comment by ibalajiarun** [comment]
Hi @brandond, upon investigation I think the problem has to do with the CIDR mask. I am using the default CIDR value of 10.42.0.0/16, so I am only able to support 256 nodes. Nodes beyond that number are not allocated a node CIDR so flannel does not come up. I will increase my CIDR value to 10.40.0.0/15 and try again

```
Jun 02 15:37:10 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:10.806559533Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
Jun 02 15:37:12 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:12.887960048Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
Jun 02 15:37:14 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:14.969281361Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
Jun 02 15:37:17 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:17.060000780Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
Jun 02 15:37:19 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:19.141521492Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
Jun 02 15:37:21 destiny-uksouth-server-vm000005 k3s[2484]: time="2021-06-02T15:37:21.223526405Z" level=info msg="Waiting for node destiny-uksouth-server-vm000005 CIDR not assigned yet"
```

Reference: https://github.com/k3s-io/k3s/issues/2218

**Comment by ibalajiarun** [comment]
Quick question: should I also change `service-cidr` in addition to `cluster-cidr`?

**Comment by brandond** [comment]
No, you shouldn't need to change that unless you're running out of ClusterIP addresses for your services.

**Comment by comphilip** [comment]
@ibalajiarun `only able to support 256 nodes`. It maybe flannel default configuration limit. By default, K3S uses `10.42.0.0/16` for cluster CIDR. Flannel takes `10.42.xx.0/24` for each node. For example, for one master and 4 workers, flannel will assign CIDR:

master: 10.42.0.1/24
worker1: 10.42.1.1/24
worker2: 10.42.2.1/24
worker3: 10.42.3.1/24
worker4: 10.42.4.1/24

As you can see, `10.42.0.0/16` can be assigned to 256 nodes.

**Comment by ibalajiarun** [comment]
@comphilip i made a typo when i said 250 agents. I meant 350 agents. Changing the CIDR mask worked for me.

**Comment by brandond** [comment]
Yeah the correct answer is to change the cluster cidr and/or mask.
