### ISSUE TITLE
pods unable to resolve private dns entries

### ISSUE THREAD

**Issue by bigbrovar** [k3s-io/k3s#3380]
**Environmental Info:**
K3s Version: 
"k3s version v1.20.5+k3s1 (355fff30)"
"go version go1.15.10"

Node(s) CPU architecture, OS, and Version: 
" 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
" 5.4.0-1035-raspi #38-Ubuntu SMP PREEMPT Tue Apr 20 21:37:03 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux"

Cluster Configuration:
"1 servers, 9 agents".

**Describe the bug:**
does not) right now I am just clueless. 
I am running a multi arch cluster made up of 4 x86 nodes and 6 raspberry pi 4 nodes. I have traefik and serviceLB disabled and use nginx-ingress and metalb instead. For the most part the cluster runs well but I noticed recently that private dns entries (created by my router) for running some of the services I deployed on the cluster can not be resolved by pods running in the cluster. I am able to resolve external (internet) dns entries. The individual nodes are not affected by this issues.

**Steps To Reproduce:**
when I run kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup private.dns.com

Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'private.dns.com'
pod "busybox" deleted
pod default/busybox terminated (Error)

if I run the same command for a publicly resolvable dns entry 
kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup google.com

kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup google.com
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2c0f:fb50:4003:802::200e
Address 2: 216.58.223.238 los02s04-in-f14.1e100.net
pod "busybox" deleted

The cluster was installed using the [k3s-playblook](https://github.com/k3s-io/k3s-ansible) with the following options
extra_server_args: "--disable traefik --disable servicelb"
- Installed K3s: 

**Expected behavior:**
pods should be able to resolve dns created on my private network just as the nodes they are running on is able to resolve this private dns entries.

**Actual behavior:**
pods running in the cluster are unable to resolve any private dns entries.

**Additional context / logs:**
 kubectl exec -i -t dnsutils -- nslookup radarr.privatedomain.org
Server:		10.43.0.10
Address:	10.43.0.10#53

** server can't find radarr.privatedomain.org: NXDOMAIN

kubectl exec -ti dnsutils -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5

kubectl logs --namespace=kube-system -l k8s-app=kube-dns
.:53
[INFO] plugin/reload: Running configuration MD5 = 442b35f70385f5c97f2491a0ce8a27f6
CoreDNS-1.8.0
linux/arm64, go1.15.3, 054c9ae

kubectl logs --namespace=kube-system -l k8s-app=kube-dns
.:53
[INFO] plugin/reload: Running configuration MD5 = 442b35f70385f5c97f2491a0ce8a27f6
CoreDNS-1.8.0
linux/arm64, go1.15.3, 054c9ae

kubectl get endpoints kube-dns --namespace=kube-system
NAME       ENDPOINTS                                        AGE
kube-dns   10.42.4.101:53,10.42.4.101:53,10.42.4.101:9153   58d

kubectl -n kube-system edit configmap coredns
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

**Comment by bigbrovar** [comment]
Just to add, if I made the following changes to my cluster.
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        }
        privatedns.com:53 {
        errors
        cache 30
        forward . router1p
    }

I am able to get private dns resolving working. unfortunately the changes does not persist a restart. How can I make changes to the config map persist restarting?

**Comment by brandond** [comment]
K3s will attempt to use resolv.conf from your host, unless it contains unicast or IPv6 server entries, in which case it will generate a default resolv.conf that points at 8.8.8.8 for upstream name resolution.

You might try creating a simple resolv.conf that contains just your private search domain and IPv4 upstream DNS server, place it at /etc/rancher/k3s/resolv.conf, and tell K3s to use that with the [--resolv-conf](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#networking) CLI flag.

**Comment by bigbrovar** [comment]
@brandond Thanks for that. My issue is how to make this persist a restart

**Comment by brandond** [comment]
If you modify the flags in the k3s systemd unit, it should persist across reboots?

**Comment by bigbrovar** [comment]
Thanks @brandond that did the trick.

**Comment by brandond** [comment]
The changes to what don't persist? Your k3s.service systemd unit?

**Comment by bigbrovar** [comment]
Yes sìr changes to K3s.service does not persist after restart.

**Comment by brandond** [comment]
There's nothing in k3s that rewrites the contents of that file. What linux distribution are you using? Do you have some other script or automation in place that reruns the installer on startup or something?

**Comment by bigbrovar** [comment]
Oh sorry @brandond I did not communicate clearly, It was late here when I replied and I was a bit fatigued. The changes I made to k3s.service file in /etc/systemd/system/ did persist. But it did not solve my problem. of pods resolving the private domain. I made that change on the master node. The exact change I made is below
`ExecStart=/usr/local/bin/k3s server --disable traefik --disable servicelb --resolv-conf=/etc/rancher/k3s/resolv.conf`

the content of /etc/rancher/k3s/resolv.conf are:
```
nameserver 172.42.0.1
search lan
```

However like I said, the edit to systemd did not have any effect on the main issue (even though that change did persist) it had no effect on pods ability to resolve private domains.

The only change that allows private domains to be resolve by pods is when I edit the config map like [here](https://github.com/k3s-io/k3s/issues/3380#issuecomment-851009524) but this works till the next reboot when the file gets over written. Is there a way I can make a config map change persist across reboot? 

if not is there a way I can could have a yml file executed while the cluster is rebooting, if I could I could make changes to the config file in form of a yml config file.

**Comment by bigbrovar** [comment]
The issue I am having is related to [this](https://github.com/k3s-io/k3s/issues/462) unfortunately they don't seem to be a working solution :(

**Comment by brandond** [comment]
I see you have 9 agents? The resolv.conf change should be applied on all the nodes, not just the server.

Alternatively, you can --disable coredns and provide your own deployment so the k3s does not roll back your configmap changes.

**Comment by bigbrovar** [comment]
Honestly don't under what providing Mt own deployment means or how to do that. Ideally it would be nice if private DNS just works OOTB like it wsd designed to. And since that is not the case how can I add my own DNS configuration.. If I have been able to do that how can I persist my changes. 

I seem to have finally figured it out following the report I referred to earlier. Thanks.

**Comment by brandond** [comment]
Ok.
