### ISSUE TITLE
--target doesn't work for kubectl debug

### ISSUE THREAD

**Issue by fengxx** [k3s-io/k3s#3381]
**Environmental Info:**
K3s Version: k3s version v1.20.7+k3s1 (aa768cbd)

Node(s) CPU architecture, OS, and Version:  Alpine  5.10.12-0-virt

Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

pods with spec shareProcessNamespace: true are working fine, but debug container doesn't enable process sharing

**Steps To Reproduce:**

- Installed K3s: 
```
kubectl run test-pod-1 --image busybox  --command sleep --restart Never 24h
kubectl debug --image busybox test-pod-1 --target test-pod-1  -it -- sh
# then run ps
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
   44 root      0:00 sh
   50 root      0:00 ps

```
**Expected behavior:**

ps should show the sleep process
```
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 24h
```

**Actual behavior:**

can not see processes inside the test-pod-1
**Additional context / logs:**

Reference [debug-running-pod](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/)

**Comment by brandond** [comment]
From the docs you linked:
> Note: The --target parameter must be supported by the Container Runtime. When not supported, the Ephemeral Container may not be started, or it may be started with an isolated process namespace

I haven't chased this down with containerd to see if they support this or not.

**Comment by ejose19** [comment]
I stumbled with this as well, and as mentioned by @brandond this is not yet supported by `containerd` version used by `k3s`, it was implemented in this [PR](https://github.com/containerd/containerd/pull/5203) which landed in version `1.5`. So we have to wait until `k3s` uses that version of `containerd`.

**Comment by brandond** [comment]
You'll probably see that in k3s 1.22.

cc @dweomer

**Comment by fengxx** [comment]
Thanks, looking forward to it

**Comment by ejose19** [comment]
I confirm this works as expected using k3s v1.22, so this can be closed
