### ISSUE TITLE
install failing

### ISSUE THREAD

**Issue by mark-gaug** [k3s-io/k3s#3390]
curl -sfL https://get.k3s.io | sh -  is failing in the middle with the command https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/22/el/8/repodata/repomd.xml  returns with a 403 forbidden error.  This used to work without issue.

**Comment by brandond** [comment]
That is not one of our repos. I suspect you have added a 3rd part Yum repo to your system configuration, and that repo is no longer available, which causes an error when k3s attempts to install the k3s-selinux package via yum. You'll need to find the repo file that is pulling from bintray.com, and disable or delete it.

**Comment by mark-gaug** [comment]
Understand ... thanks
