### ISSUE TITLE
Client IP with integrated ServiceLB + Nginx ingress

### ISSUE THREAD

**Issue by gallart** [k3s-io/k3s#3391]
**Environmental Info:**
K3s Version: 
k3s version v1.21.0+k3s1 (2705431d)

Node(s) CPU architecture, OS, and Version: 
* Centos 7
* 2x Intel 4214
* 64 GB

Cluster Configuration:
* 3 servers/agents
* Kube-vip for BGP Annoucements/IP

**Describe the bug:**
I have disabled integrated traefik and deployed nginx ingress-controler based on https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml.

What I understand is that traffic goes to svclb (integrated serviceLB from `daemonset.apps/svclb-ingress-nginx-controller` then flow to nginx-ingress controller pod, then to the app.

The problem is that nginx-ingress is seeing the internal LB pod IP instead of client IP.

**Steps To Reproduce:**

```
curl -fL https://get.k3s.io | K3S_TOKEN=XXX INSTALL_K3S_CHANNEL=latest sh -s - server --cluster-init --kube-apiserver-arg default-not-ready-toleration-seconds=10 --kube-apiserver-arg default-unreachable-toleration-seconds=10 --disable traefik

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
```

- Installed K3s: 

**Expected behavior:**
Nginx should see client IP.

**Actual behavior:**
Nginx sees pod IP.

```
10.42.0.237 - - [02/Jun/2021:20:50:09 +0000] "GET /....
```

**Additional context / logs:**

```
ingress-nginx                           ingress-nginx-admission-create-fcctn                              0/1     Completed           0          16d
ingress-nginx                           ingress-nginx-admission-patch-2z4gz                               0/1     Completed           1          16d
ingress-nginx                           ingress-nginx-controller-8c5c75d6d-ck8w7                          1/1     Running             0          5h3m
ingress-nginx                           svclb-ingress-nginx-controller-9mzg9                              2/2     Running             0          5h4m
ingress-nginx                           svclb-ingress-nginx-controller-w975p                              2/2     Running             0          5h4m
ingress-nginx                           svclb-ingress-nginx-controller-xs4sd                              2/2     Running             0          5h4m
```

```
ingress-nginx                           ingress-nginx-controller                    LoadBalancer   10.43.17.98     10.10.50.14,10.10.50.15,10.10.50.16   80:32296/TCP,443:30248/TCP   16d
ingress-nginx                           ingress-nginx-controller-admission          ClusterIP      10.43.90.68     <none>                                443/TCP                      16d
```

**Comment by brandond** [comment]
Have you read through: https://kubernetes.io/docs/concepts/services-networking/service/ - specifically the bit about:

> By setting .spec.externalTrafficPolicy to Local, the client IP addresses is propagated to the end Pods, but this could result in uneven distribution of traffic. Nodes without any Pods for a particular LoadBalancer Service will fail the NLB Target Group's health check on the auto-assigned .spec.healthCheckNodePort and not receive any traffic.

You must use `externalTrafficPolicy: Local` in order to see the original client IP address, with the caveat that this only allows nodes with pods for the service to receive traffic.

**Comment by gallart** [comment]
`externalTrafficPolicy` is already set to local on the nginx-ingress.

**Comment by gallart** [comment]
To understand more in details, I have deployed a http-echo container :

![image](https://user-images.githubusercontent.com/2728195/120853275-aaac4d00-c57b-11eb-9ea3-e5ed5cdde499.png)

I'm expecting to get x-real-ip with customer IP. Instead, I get the IP of the internal LB pod (`svclb-ingress-nginx-controller-6clmw `) deployed by this daemonset `daemonset.apps/svclb-ingress-nginx-controller`.

This daemonset is default LB from K3S.

I tried to switch flannel to host-gw but not diffence (should I restart anything?).

Thanks

**Comment by comphilip** [comment]
@gallart ingress-nginx-controller should be daemonset. See traesfik example: https://comphilip.wordpress.com/2021/05/23/k3s-thing-make-traefik-forward-real-client-ip/

**Comment by CracKOl** [comment]
Hi all, i have exactly the same behavior with newer version of K3S.
Have you managed to fix the issue @gallart  ?
Cheers
Olivier

**Comment by gallart** [comment]
Hi @CracKOl,

My solution was to : `--disable traefik --disable servicelb`

And manage ingress on my own.

Gaëtan

**Comment by KiillThemAll** [comment]
> Hi @CracKOl,
> 
> My solution was to : `--disable traefik --disable servicelb`
> 
> And manage ingress on my own.
> 
> Gaëtan

Can you tell, how have you managed ingress on you own? I have the same problem with bare metal k3s and i cant understand how to setup external visibility for services with ingress...

**Comment by KiillThemAll** [comment]
Tried metallb, but problem is same

**Comment by ammirator-administrator** [comment]
@KiillThemAll @gallart @brandond 

I'm having the same issue, when setting externalTrafficPolicy as Local it shows the node public IP as being the client IP

Is assume there should be some option to pass to ServiceLB so that it passes the real client ip to Ingress but not the Node IP

**Comment by brandond** [comment]
If you set it to Local the service should see the correct service address. If you're passing through an ingress, the backend will still not see the original source address - only the ingress pod will see the original source address.

**Comment by ammirator-administrator** [comment]
My problem is that the Ingress itself doesn't see the source IP
I use nginx ingress controller, and in logs it shows the Node IP but not the client IP
The ingress controller service is of type LoadBlancer which uses Service LB

Is my understanding correct that since the ingress controller is of type load balancer, then the Request will got firstly thru LoadBalancer then it will redirect to the ingress controller? Is this flow correct?
If yes then most probably that'sthe LoadBalancer which should send the x-real-ip or other header to the ingress controller because LB is first taking the request and any onther service behind is obviously unaware of the initiator they think is the loadBalancer node

Is my understanding correct? If yes then  I assume some settings are needed at the load balancer level to set at least some header before redirecting the request to the ingress controller

**Comment by ammirator-administrator** [comment]
Another question, maybe I misunderstood something

This `kubectl patch svc <name> -p '{"spec":{"externalTrafficPolicy":"Local"}}'`
Should be applied on Ingress Controller or on the LoadBalancer or on both? I see a lot of comments that this option works but none of them says on which service this needs to be applied

**Comment by KiillThemAll** [comment]
@ammirator-administrator 
Way that helped me:
1) --disable traefik --disable servicelb on cluster creation
2) Setup Metallb instead of ServiceLB
3) Setup Traefik instead of nginx-ingress with service.spec.externalTrafficPolicy=Local
4) Inside ingresses set ingressClassName: traefik
