### ISSUE TITLE
kubernetes.default.svc not among SANs in Kubernetes API serving certificate

### ISSUE THREAD

**Issue by tallaxes** [k3s-io/k3s#3392]
**Environmental Info:**
RKE2 Version: v1.20.7+rke2r2
K3s Version: v1.21.1-rc1.0.20210514205428-fd4d226e3deb (based on go.mod in RKE2)

**Describe the bug:**

In-cluster attempt to connect to https://kubernetes.default.svc fails with "requested domain name does not match the server's certificate".

**Steps To Reproduce:**

From any pod (with curl and not on host network):
```sh
curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc
```

**Expected behavior:**

Successful certificate verification:

```log
$ curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc    
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

(401 Unauthorized is fine, just looking for no cert issues ...)

**Actual behavior:**

```
$ curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

(Originally observed with in-cluster Java client failing with "javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching kubernetes.default.svc found.")

Also note that the same request with https://kubernetes.default (without .svc) works fine.

**Additional context / logs:**

This is very likely introduced recently by https://github.com/k3s-io/k3s/pull/3241.

As @brandond pointed out, it is surprising this is not caught by Kubernetes conformance tests. (They check for DNS resolution for selected required PQDNs, but not for their presence in SAN list / ability to actually establish connection.) Filed https://github.com/kubernetes/kubernetes/issues/102549

**Comment by cjellick** [comment]
We need to also see if this issue shows up in k3s 1.20.x and fix it there as well if so.

**Comment by galal-hussein** [comment]
hmmm, thats kinda weird since if I recall correctly we do add kubernetes.default.svc to the sans https://github.com/k3s-io/k3s/blob/master/pkg/daemons/control/deps/deps.go#L322

**Comment by tallaxes** [comment]
It is added with cluster domain suffix (`kibernetes.default.svc.<cluster suffix>`, FQDN), the issue is when client uses one without suffix (`kubernetes.default.svc`, PQDN)

**Comment by Oats87** [comment]
@tallaxes Just confirming here, you are testing this in an RKE2 cluster, correct?

**Comment by tallaxes** [comment]
@Oats87 Yes

**Comment by brandond** [comment]
As @Oats87 points out, K3s itself masks this issue by putting the dynamiclistener in front of the apiserver, which adds the correct SANs on-demand.

**Comment by brandond** [comment]
On K3s, this can be reproduced by hitting the pure apiserver port directly, on the server:
```
echo QUIT | openssl s_client -connect localhost:6444 2>/dev/null | openssl x509 -noout -text | grep DNS
```

**Comment by rancher-max** [comment]
#### Validated on master using commitid: `a7d1159ba6f71f36990fac2a1780fcc3f8621ab6`

- Recreated in v1.21.1+k3s1 by running command mentioned by Brad: `echo QUIT | openssl s_client -connect localhost:6444 2>/dev/null | openssl x509 -noout -text | grep DNS` which produced default DNS results of: 
`DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc.cluster.local`
- On master, running the same command produces: 
`DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local`
- In both cases, confirmed that curl'ing using the kuberentes.default.svc cert from inside a container continues to work and retrieves the Not Authorized message.
