### ISSUE TITLE
[release-1.21] kubernetes.default.svc not among SANs in Kubernetes API serving certificate

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3399]
Backport "kubernetes.default.svc not among SANs in Kubernetes API serving certificate" from #3392 to release-1.21 branch

**Comment by rancher-max** [comment]
#### Validated on release-1.21 branch using commitid: `eac48f69bce086a789585e0158de79c06b2ff50e`

- Performed the same steps as in https://github.com/k3s-io/k3s/issues/3392#issuecomment-861011491. The recreation there still applies. Results: `DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local`
