### ISSUE TITLE
[release-1.21] Flannel wireguard backend writes files to /

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3400]
Backport "Flannel wireguard backend writes files to /" fixes from #3031 to release-1.21

**Comment by rancher-max** [comment]
#### Validated on release 1.21 branch using commitid: `8651d6af5feb291d6011b550e6c5a88e0e6f558a`

- Fresh install writes on both server and agent nodes to:
```
...
extension.go:87] Ran command: wg genkey | tee /var/lib/rancher/k3s/agent/etc/flannel/privatekey | wg pubkey
...
$ sudo ls /var/lib/rancher/k3s/agent/etc/flannel
net-conf.json  privatekey
```
- Upgrade is successful and writes on both server and agents node to the same above location. Cluster continues to operate as normal.
