### ISSUE TITLE
K3s should not perform etcd setup when managed etcd is not enabled

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3404]
When support for etcd was added in https://github.com/k3s-io/k3s/commit/39571424dda6a177abd8205dcc67c5c05dbfc70a, generation of certificates and keys for etcd was not gated behind use of managed etcd. Keys are generated and distributed across servers even if managed etcd is not enabled.

Similarly, the [k3s-apiserver-lb-controller](https://github.com/k3s-io/k3s/blob/master/pkg/apiaddresses/controller.go) attempts to set up a client LB tunnel to the local etcd instance on port 2379, even if managed etcd is not enabled.

These bits of etcd-specific setup should only be enabled when managed etcd is in use.

**Comment by bartossh** [comment]
The [k3s-apiserver-lb-controller](https://github.com/k3s-io/k3s/blob/master/pkg/apiaddresses/controller.go) is at this address I believe.

**Comment by brandond** [comment]
yeah some of this should be fixed in recent commits, but we haven't addressed the issue of the etcd certs being generated unconditionally.

**Comment by bartossh** [comment]
Can I take care of that, please?

**Comment by bartossh** [comment]
My conclusion from the test in [PR](https://github.com/k3s-io/k3s/pull/6998#issuecomment-1445305372) is that we can only avoid generating server etcd certs, we will still need peer and client certs.

**Comment by dereknola** [comment]
@bartossh Sorry this took so long to get resolved, the PR got lost in the pile. This should be fixed in all updated releases for July 2023.

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit be442433
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
 
*Cluster Configuration:*

```
2 servers, 1 agent
Split role setup: 1 etcd-only, 1 cp-only and 1 agent node
```
 
*Config.yaml:*

<details> 

```
# etcd-only S1
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
node-taint:
  - node-role.kubernetes.io/etcd:NoExecute
write-kubeconfig-mode: 644
cluster-init: true

# cp-only S2
disable-etcd: true
node-taint:
  - node-role.kubernetes.io/control-plane:NoSchedule
server: "https://<IP of S1>:6443"
token: "<K10 from S1>"
write-kubeconfig-mode: 644

# agent
server: "https://<IP of S1>:6443"
token: "<K10 from S1>"
```
</details>
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s on server and agent nodes
3. Ensure the cluster is up and running
4. Validate the files below are **NOT** present on the cp-only (as it has the flag `disable-etcd: true`)  server node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
...
-rw-r--r-- 1 root root 1258 Jul 17 21:00 server-client.crt
-rw------- 1 root root  227 Jul 17 21:00 server-client.key
``` 
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5
```
<details>


- Observed the files are present on cp-only node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
total 48
drwx------ 2 root root 4096 Jul 17 20:42 .
drwx------ 4 root root 4096 Jul 17 20:42 ..
-rw-r--r-- 1 root root 1140 Jul 17 20:42 client.crt
-rw------- 1 root root  227 Jul 17 20:42 client.key
-rw------- 1 root root  566 Jul 17 20:21 peer-ca.crt
-rw------- 1 root root  227 Jul 17 20:21 peer-ca.key
-rw-r--r-- 1 root root 1250 Jul 17 20:42 peer-server-client.crt
-rw------- 1 root root  227 Jul 17 20:42 peer-server-client.key
-rw------- 1 root root  570 Jul 17 20:21 server-ca.crt
-rw------- 1 root root  227 Jul 17 20:21 server-ca.key
-rw-r--r-- 1 root root 1258 Jul 17 20:42 server-client.crt
-rw------- 1 root root  227 Jul 17 20:42 server-client.key
```
</details>
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.27.3+k3s-be442433 (be442433)
go version go1.20.5
```
<details>


- Observed the files are **NOT** present on cp-only node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
total 40
drwx------ 2 root root 4096 Jul 17 21:02 .
drwx------ 4 root root 4096 Jul 17 21:02 ..
-rw-r--r-- 1 root root 1140 Jul 17 21:02 client.crt
-rw------- 1 root root  227 Jul 17 21:02 client.key
-rw------- 1 root root  566 Jul 17 21:00 peer-ca.crt
-rw------- 1 root root  227 Jul 17 21:00 peer-ca.key
-rw-r--r-- 1 root root 1250 Jul 17 21:02 peer-server-client.crt
-rw------- 1 root root  227 Jul 17 21:02 peer-server-client.key
-rw------- 1 root root  570 Jul 17 21:00 server-ca.crt
-rw------- 1 root root  227 Jul 17 21:00 server-ca.key
```
</details>
