### ISSUE TITLE
Test and Certify SLES 15 SP3

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3410]
Test and Certify SLES 15 SP3

**Comment by dirkmueller** [comment]
Please see also #2648 and #1803

**Comment by rancher-max** [comment]
#### Validated using k3s versions v1.19.11+k3s, v1.20.7+k3s1, and v1.21.1+k3s1 with both externaldb and etcd 


Test Coverage | Status | Comments
-- | -- | --
Fresh Installation and sonobuoy execution | Pass | &nbsp;
Run functional test on imported k3s cluster on Rancher | Pass | &nbsp;
Validate installation with docker CRI | Pass | &nbsp;
Upgrade SUC k3s native with workloads | Pass | &nbsp;
Install k3s as local management cluster for Rancher | Pass | &nbsp;
