### ISSUE TITLE
Possible race where bootstrap data might not save

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3414]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Depending on when the channel is read, it may not return anything and the goroutine will continue on. The code needs to be updated so the channel is checked multiple times until the signal is received to guarantee the bootstrap data is saved.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
Validated using commit ID: k3s version v1.21.2+k3s-4be912b9 using embedded etcd datastore

Bootstrap data is saved 
```
/bootstrap/2bb80d537b1d
/registry/clusterroles/system:node-bootstrapper
/registry/rolebindings/kube-public/system:controller:bootstrap-signer
/registry/rolebindings/kube-system/system:controller:bootstrap-signer
/registry/roles/kube-public/system:controller:bootstrap-signer
/registry/roles/kube-system/system:controller:bootstrap-signer
```

**Comment by ShylajaDevadiga** [comment]
Validated in rc: v1.21.2-rc1+k3s2, bootstrap data is saved
```
/bootstrap/2bb80d537b1d
/registry/clusterroles/system:node-bootstrapper
/registry/rolebindings/kube-public/system:controller:bootstrap-signer
/registry/rolebindings/kube-system/system:controller:bootstrap-signer
/registry/roles/kube-public/system:controller:bootstrap-signer
/registry/roles/kube-system/system:controller:bootstrap-signer
```
