### ISSUE TITLE
Use ReplaceAll function instead of Replace

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#3416]
The flannel code is using in various places the strings.Replace function with number of occurrences=-1 to replace all

https://github.com/k3s-io/k3s/blob/master/pkg/agent/flannel/setup.go#L121-L140

There is a better function to do this strings.ReplaceAll

**Comment by rancher-max** [comment]
Flannel continues to work on master using commitid: `a7d1159ba6f71f36990fac2a1780fcc3f8621ab6` and its config files did not appear to have any erroneous values
