### ISSUE TITLE
K3s should log directly to `journal` instead of `stdout/stderr` on `systemd` systems

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#3421]
Today, `K3s` logs to `stdout` and `stderr` and the logs then get captured and categorized under the corresponding `K3s` unit. 

We also have a mismatch issue of formatting for all of the logs that come out of K3s: more information on this can be found here: https://github.com/k3s-io/k3s/issues/3420

Ideally, if we can log to `journald` directly, for the same reasons as listed here: https://github.com/rancher/rke2/issues/1111 we will make our logs easier to ingest.

**Comment by HaleyACS** [comment]
This should be reopened. Having a central logging instance can help tremendously. Especially when having to handle security - going through a single journald log would help a lot.
Imagine having a dedicated remote logging server! What a bliss that would be.
