### ISSUE TITLE
Update helm-controller to v0.10.0 or newer

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3426]
There have been several improvements to helm-controller that have been pulled in to RKE2 to fix issues specifically encountered by that project; we should update helm-controller in K3s as well.

**Comment by rancher-max** [comment]
#### Validated using master commit `a1d7a62493a5943d33d0d01100ee26aa0044ccff`

- klipper-helm version bumped to `rancher/klipper-helm:v0.6.1-build20210616`
- Version confirmed at v0.10.1:
```
$ go mod graph | grep helm-controller
github.com/rancher/k3s github.com/k3s-io/helm-controller@v0.10.1
...
```
- Helm installs and config changes from manifest directory continue to work
