### ISSUE TITLE
[release-1.21] Update helm-controller to v0.10.0 or newer

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3427]
Backport "Update helm-controller to v0.10.0 or newer" from #3426

RKE2 1.21 is on helm-controller v0.10.0, k3s 1.21 should be as well

**Comment by ShylajaDevadiga** [comment]
Validated using release-1.21 branch 
```
$ go mod graph|grep helm
github.com/rancher/k3s github.com/k3s-io/helm-controller@v0.10.1
```
