### ISSUE TITLE
Cannot disable nginx servicelb (svclb-ingress-nginx-controller)

### ISSUE THREAD

**Issue by gallart** [k3s-io/k3s#3432]
**Environmental Info:**
K3s Version: 
`k3s version v1.21.0+k3s1 (2705431d)`

Node(s) CPU architecture, OS, and Version: 
`Linux myhost 5.4.114-1.el7.elrepo.x86_64 #1 SMP Mon Apr 19 18:53:45 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
3 servers, no agents

**Describe the bug:**
`daemonset.apps/svclb-ingress-nginx-controller` keeps coming back after delete despite cluster having `--disable servicelb` option at startup.

**Steps To Reproduce:**
- Installed K3s
- Add option `--disable servicelb` to systemd
- `kubectl delete daemonset.apps/svclb-ingress-nginx-controller -n ingress-nginx`

See daemonset + pods coming back.

**Expected behavior:**
Daemonset should get away or being deleted.

**Actual behavior:**
Pod + Daemonset coming back.

**Additional context / logs:**

**Comment by brandond** [comment]
After adding `--disable servicelb` to the systemd unit, did you daemon-reload and restart k3s?

**Comment by gallart** [comment]
> After adding `--disable servicelb` to the systemd unit, did you daemon-reload and restart k3s?

That's exactly what we did.

**Comment by brandond** [comment]
If you have restarted all the servers in your k3s cluster with servicelb disabled, and deleted the daemonset, there should be nothing left to recreate it. Can you provide the output of: `kubectl get nodes -o yaml | grep node-args`

**Comment by gallart** [comment]
```
➜  ~ kubectl get nodes -o yaml | grep node-args
      k3s.io/node-args: '["server","--server","--disable","traefik","--disable","servicelb","https://10.10.50.14:6443"]'
      k3s.io/node-args: '["server","--disable","traefik","--disable","servicelb"]'
      k3s.io/node-args: '["server","--server","--disable","traefik","--disable","servicelb","https://10.10.50.14:6443"]'
```

**Comment by brandond** [comment]
Those args look wrong. Did you put the disable lines between the --server flag and the server value? That would mess up the key-value pairs for all the remaining arguments.

**Comment by gallart** [comment]
Ordering params on a single-line configuration in systemd service file was the solution.

```
ExecStart=/usr/local/bin/k3s \
    server --server https://10.10.50.15:6443 --disable traefik --disable servicelb
```

```
➜  ~ kubectl get nodes -o yaml | grep node-args
      k3s.io/node-args: '["server","--server","https://10.10.50.14:6443","--disable","traefik","--disable","servicelb"]'
      k3s.io/node-args: '["server","--server","https://10.10.50.15:6443","--disable","traefik","--disable","servicelb"]'
      k3s.io/node-args: '["server","--server","https://10.10.50.14:6443","--disable","traefik","--disable","servicelb"]'
```

Gaëtan

**Comment by brandond** [comment]
They don't all have to be on the same line, but in your case it sounds like you'd put things in between the lines for the server flag, and server value?

**Comment by gallart** [comment]
I could not tell as I didn't save. One-line permits better reading. Probably was mistaken on our side.
