### ISSUE TITLE
Use managedFields to track which node's deploy controller modified a resource

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3434]
For rancher/rke2#1124 - Helm Job Pod Affinity Implementation Options / Option B: Use managedFields to track the updating node

We would like to be able to track which node's deploy controller most recently modified an object via server-side-apply's field manager:

`kubectl get service -n kube-system kube-dns -o yaml --show-managed-fields` - note entry in managedFields list showing manager: deploy@NODENAME

**Comment by ShylajaDevadiga** [comment]
Validated using commit id. Waiting on rc for close the issue.
$ k3s -v
k3s version v1.21.1+k3s-b74c4997 (b74c4997)
go version go1.16.4
$ kubectl get service -n kube-system kube-dns -o yaml --show-managed-fields |grep deploy
    manager: deploy@ip-172-31-15-119

**Comment by ShylajaDevadiga** [comment]
Closing the issue as validated as it is self-contained.
