### ISSUE TITLE
Restoration on a fresh node fails to verify hash for node using the node password file

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#3435]
**Environmental Info:**
K3s Version: master HEAD commit ID 2afa3dbe1ce833938e1b39e1b51fd22d7b87ccec

Node(s) CPU architecture, OS, and Version: 
dev-shell environment

Cluster Configuration:
1 node

**Describe the bug:**
After cluster restoration on a fresh node, k3s shows an error:
```
INFO[2021-06-10T20:43:52.568960427Z] Cluster-Http-Server 2021/06/10 20:43:52 http: TLS handshake error from 127.0.0.1:60600: remote error: tls: bad certificate 
ERRO[2021-06-10T20:43:52.688701585Z] unable to verify hash for node 'rke2-server': hash does not match 
ERRO[2021-06-10T20:43:52.688933347Z] Failed to configure agent: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag 
```

**Steps To Reproduce:**
- start k3s on 1 node with custom token
- take a snapshot using etcd-snapshot subcommand
- copy the snapshot to a fresh node
- restore the snapshot with the same custom token and the same **node name**
- start k3s server

**Expected behavior:**
for k3s to start normally

**Actual behavior:**
k3s shows the above error and kubelet fails to start successfully

**Comment by ShylajaDevadiga** [comment]
Validated using commit ID : k3s version v1.21.2+k3s-4be912b9
Restoration on a fresh node was successful following the steps to reproduce.

**Comment by davidnuzik** [comment]
@galal-hussein this issue has no milestone - can you set it please? If it's master, then should be v1.22.0 milestone.

**Comment by rancher-max** [comment]
This has previously been validated so I am closing.
