### ISSUE TITLE
etcd-snapshot needs to be run as root

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3438]
_Originally posted by @ChristianCiach in https://github.com/k3s-io/k3s/discussions/3429#discussioncomment-857698_

I've identified the cause why `k3s etcd-snapshot` didn't work for me before: I didn't run this command with sudo. Although I've installed K3s with `write-kubeconfig-mode: '0644'` (and kubectl-commands work fine without sudo), `k3s etcd-snapshot` insists to be called via sudo:

```
[vagrant@k3s-server-1 ~]$ kubectl get nodes
NAME           STATUS   ROLES                       AGE   VERSION
k3s-agent-1    Ready    <none>                      10m   v1.21.1+k3s1
k3s-server-1   Ready    control-plane,etcd,master   11m   v1.21.1+k3s1
```

```
[vagrant@k3s-server-1 ~]$ k3s etcd-snapshot
FATA[2021-06-11T11:21:33.427082412Z] managed etcd database has not been initialized 
```
```
[vagrant@k3s-server-1 ~]$ sudo k3s etcd-snapshot
INFO[2021-06-11T11:21:44.324976430Z] Managed etcd cluster bootstrap already complete and initialized 
W0611 11:21:44.336049    9282 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0611 11:21:44.343039    9282 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0611 11:21:44.346082    9282 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
INFO[2021-06-11T11:21:44.355481652Z] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1623410504 
{"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1623410504.part"}
{"level":"info","ts":"2021-06-11T11:21:44.358Z","caller":"clientv3/maintenance.go:200","msg":"opened snapshot stream; downloading"}
{"level":"info","msg":"fetching snapshot","endpoint":"https://127.0.0.1:2379"}
{"level":"info","ts":"2021-06-11T11:21:44.393Z","caller":"clientv3/maintenance.go:208","msg":"completed snapshot read; closing"}
{"level":"info","msg":"fetched snapshot","endpoint":"https://127.0.0.1:2379","size":"3.5 MB","took":"41.570489ms"}
{"level":"info","msg":"saved","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1623410504"}
INFO[2021-06-11T11:21:44.397475355Z] Saving current etcd snapshot set to k3s-etcd-snapshots ConfigMap 
```

**Comment by brandond** [comment]
Need to update the docs to note that etcd-snapshot needs to be run as root or via sudo

**Comment by ChristianCiach** [comment]
Do elaborate: It wasn't my goal to actually create a snapshot. I just wanted to see if my single-server cluster with embedded etcd was working. In fact, I didn't read any documentation about this subcommand and I expect there to be other k3s subcommand that also require root.

I think the *issue* (if there is one) is not the lack of documentation, but the confusing error message. Something like `permission denied` would have saved me some time, but I got `managed etcd database has not been initialized` instead, which made me think there is something wrong with my setup.

**Comment by brandond** [comment]
The reason it's telling you it's not initialized is that it looks at a different path for the data-dir when run as non-root. It's not a permissions error, it's just that it doesn't find the root-owned database.

**Comment by cjellick** [comment]
It does seem we could improve the error message somehow as well.

**Comment by cjellick** [comment]
While this should be accompanied by a docs, update, i removed the documentation label so that it isnt mistaken for solely a docs issue. I think we should tweak that error message a bit, even if it is somewhat generic.

**Comment by brandond** [comment]
The correct behavior would probably be to look at the user data-dir first, and if nothing is found then fall back to system-level data-dir as we do for other things like config files.

**Comment by ShylajaDevadiga** [comment]
Validated using commit ID: 238dc208
```
$ k3s etcd-snapshot
FATA[2021-07-12T19:47:27.104943220Z] etcd database not found in /home/ubuntu/.rancher/k3s/server 
```

**Comment by rancher-max** [comment]
I am going to close this as it has already been validated and there is another issue I'm keeping around related to etcd-snapshot to verify on an RC
