### ISSUE TITLE
K3s-arm64 Error 

### ISSUE THREAD

**Issue by Esaga-Esg** [k3s-io/k3s#3439]
Hello,

I´m trying to make a K3s cluster using Raspberry ubuntu 20.04 version on the agent. I get k3s-arm64 (my raspberry architecture is arm64) from github and i try to run it like root. I receive that error:
INFO[2021-06-12T10:52:58.365813580Z] Starting k3s agent v1.21.1+k3s1 (75dba57f)
ERRO[2021-06-12T10:52:58.366803091Z] Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
FATA[2021-06-12T10:52:58.366964998Z] failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)

On journalctl -xe I receive the same error:
Jun 12 10:46:23 ubuntu k3s[2481]: time="2021-06-12T10:46:23.620358520Z" level=error msg="Failed to find memory cgroup, you may need to add \"cgroup_memory=1>
Jun 12 10:46:23 ubuntu k3s[2481]: time="2021-06-12T10:46:23.620471574Z" level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1>
Jun 12 10:46:23 ubuntu systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE

Any idea what happen and how can I initialize the agent on the raspberry?

**Comment by brandond** [comment]
Have you tried following the instructions from the error message?

**Comment by Esaga-Esg** [comment]
Yeah, I add this lines and I take another error that i could solve. 

Thank you so much and sorry.

**Comment by nguyenvulong** [comment]
@Esaga-Esg  if you problem is solved, please make sure to close the issue. This would help reduce the burden of the maintainers.

**Comment by cwayne18** [comment]
Closing this as it cannot be seen after configuring cgroups correctly.  For more info, please see: https://rancher.com/docs/k3s/latest/en/advanced/#enabling-cgroups-for-raspbian-buster
