### ISSUE TITLE
LoadBalancer being created for ClusterIP service type also

### ISSUE THREAD

**Issue by satb** [k3s-io/k3s#3440]
**Environmental Info:**
K3s Version: 

$ k3s -version
k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 

Linux, Ubuntu 20.10

Cluster Configuration:

Very simple test configuration. Just 1 single tenant node.

**Describe the bug:**

I have no services setup as a LoadBalancer service except 1. However, for two other pods, there is a load balancer pod deployed and running into port conflicts with the lone load balancer service which remains in pending state forever. I for the life of me cannot figure out why the load balancer is being setup for the two services that are setup as a clusterIp. I am checking using "kubectl -n <namespace> get svc". None but one is setup as a LoadBalancer. However, I have 3 load balancer pods running and running into port conflicts on the node. I have no idea why this is happening. Describing the pod that is setup as a load balancer shows this

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  57m   default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  57m   default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.

**Steps To Reproduce:**

- Installed K3s: 

curl -sfL 'https://get.k3s.io' | sh -s - --disable=traefik --write-kubeconfig-mode 644

**Expected behavior:**

Since only 1 service is setup as a load balancer, only one load balancer pod should be launched. The ones setup as clusterIp should not have a load balancer.

**Actual behavior:**

3 load balancers. Initially all 3 were defined as load balancers. However, I changed two of them to clusterIp and expected those 2 load balancer pods to go away. However, they don't even after launching the services as clusterIp

**Additional context / logs:**

kubectl -n testns get svc

NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                   AGE
svc1                  ClusterIP      None            <none>        8080/TCP                                                                                                                  177m
svc2                  ClusterIP      None            <none>        5432/TCP                                                                                                                  177m
svc3                  ClusterIP      10.43.136.118   <none>        8080/TCP                                                                                                                  177m
svc4                  ClusterIP      10.43.240.248   <none>        27147/TCP,27146/TCP,28660/TCP                                                                                             177m
svc5                  ClusterIP      10.43.106.30    <none>        1317/TCP                                                                                                                  177m
svc6                  ClusterIP      10.43.103.213   <none>        6040/TCP,5040/TCP,9000/TCP                                                                                                177m
svc7                  ClusterIP      10.43.157.239   <none>        27146/TCP,27147/TCP,26660/TCP                                                                                             177m
lb1                   LoadBalancer   10.43.141.215   <pending>     80:30734/TCP,6040:30270/TCP,5040:32479/TCP,8080:30065/TCP,1317:31616/TCP,6657:32185/TCP,27147:32224/TCP,27146:31180/TCP   177m

kubectl -n testns get pods

svclb-lb1-nzmh7                        0/8     Pending    0          62m
lb1-74f5dfcf94-dwnjx                0/1     Init:0/1   0          62m
svclb-svc6-pwnld                      3/3     Running    1          62m
svclb-svc7-pdwt2                      3/3     Running    1          62m
svc2-0                                          1/1     Running    0          62m
svc4-7b58b7dc87-sjpg8            1/1     Running    0          62m
svc7-6d699c8cb7-jpq8j             1/1     Running    3          62m
svc5-594fb48c65-hrj6z             1/1     Running    0          62m
svc6-6479997565-chndb           1/1     Running    0          62m
svc3-0                                           0/1     Running    0          62m

As you can see, there is only one Load Balancer service but 3 svclb pods running conflicting with the ports. Can't figure out why those additional load balancers are running.

**Comment by satb** [comment]
Had to manually delete the service and add it back again. Then the LB was gone for those services.

**Comment by brandond** [comment]
Yes, servicelb doesn't correct clean up lb pods for services that have their type changed after the fact. I believe there's an issue open for this, although I'm not finding it at the moment.
