### ISSUE TITLE
Promote 1.21.2+k3s1 to stable

### ISSUE THREAD

**Issue by fapatel1** [k3s-io/k3s#3450]
**Rule of thumb:**
- new patch, wait ~4 days before mark as stable.
- new minor version, wait about 1-2 weeks before we mark the new minor release as stable

**Steps:**
- [x] First, review new GH issues. Ensure there are no serious issues reported by the community or any SUSE staff.
- [x] Second, review the rancher-users slack and ensure there are no serious issues reported there.
- [x] If no obvious/serious issues exist, modify channel.yaml stable section such that it points to the new release.
- [x] Get PR reviewed and then merge the PR. Confirm that the [endpoint ](https://update.k3s.io/v1-release/channels)gets updated (takes up to about 15 mins post CI all being green).
- [ ] Ask QA to test so they can ensure that when you install via install.sh it pulls down the correct stable version.

**Comment by ShylajaDevadiga** [comment]
Validated tarball and rpm install
OS: Ubuntu, Centos7, Centos8
