### ISSUE TITLE
Host DNS fails to resolve immediately after install

### ISSUE THREAD

**Issue by dsikes** [k3s-io/k3s#3451]
**Environmental Info:**
K3s Version:  v1.21.1+k3s1 (75dba57f)

Node(s) CPU architecture, OS, and Version: 
Linux ip-10-42-10-0 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
After running 
```
curl -sfL https://get.k3s.io | sh -
```
DNS fails to resolve any external domain names.

For example,  immediately after installation is complete, these commands fail to work as expected.
```
ping google.com

or

sudo apt-get update -y
```

**Steps To Reproduce:**

- Installed K3s: 
- ran the ping and update commands

**Expected behavior:**
Expect ping and update to work as normal

**Actual behavior:**
DNS fails to resolve and eventually times out

**Additional context / logs:**
The machine also seems to be laggy after this occurs. For example, opening /etc/resolv.conf took about 3 to 5 seconds, when it's usually instant.

**Comment by brandond** [comment]
This is not something I've seen before or can reproduce locally. It sounds like you're doing this on AWS? Can you try the steps described here: https://github.com/rancher/rke2/issues/1053

**Comment by dsikes** [comment]
Thanks for the reply. 

Yes, I am running this in AWS.

That particular service / unit doesn't exist on either the Ubuntu instance or the Amazon Linux instance that I tried, so I can't disable it.

This issue is very strange. After about 10 - 15 seconds of K3s starting up, I loose all outbound internet connectivity on the host, which obviously prevents me being able to use k3s because it can't pull images, update packages, etc..

Any other thoughts on where else I can try to troubleshoot? I wouldn't think I'm the only one trying to run k3s on AWS, and this seems like it's in the critical path to me.

Thanks!

**Comment by brandond** [comment]
Do you see the same behavior on both Ubuntu and Amazon Linux? Can you share the AMI IDs that you're using?

**Comment by dsikes** [comment]
Yes. Its exactly the same behavior.

For the Ubuntu Instance I am using `ami-09e67e426f25ce0d7` (us-east-1, Ubuntu Server 20.04 LTS (HVM), SSD Volume Type) and for the Amazon Linux I used `ami-0aeeebd8d2ab47354 (64-bit x86)` (us-east1, Amazon Linux 2 AMI (HVM), SSD Volume Type)

Really appreciate the extra set of eyes on this one!

**Comment by dsikes** [comment]
I also verified that it wasn't anything to do with my VPC, and other networking settings in the AWS Cloud. I spun up another instance, using the same AMI and did *not* install k3s, and everything works as expected.

![image](https://user-images.githubusercontent.com/8764573/121992018-c7603600-cd6e-11eb-941f-577782c50f62.png)

**Comment by ystyle** [comment]
has the same issue
It is normal on the host, there are more than ten seconds in the pod
![微信图片_20210615151604](https://user-images.githubusercontent.com/4478635/122009390-a0484980-cdec-11eb-958d-5a25089fe8e2.png)

**Comment by dsikes** [comment]
So,  I just tried again with a fresh ubuntu instance. This time it did last longer before losing network connectivity. I was able to use it for about 3 min or so and then it failed again. I tried rebooting the box, based on @ystyle's comment just to see if that would help, and it does not for me.

As you can see, even the internal healthchecks are partially failing because the instances have no outbound internet.
![image](https://user-images.githubusercontent.com/8764573/122084963-46d22180-cdd0-11eb-84aa-2e9c6439f837.png)

I looked at /etc/resolv.conf to see if the file had been manipulated, or corrupted in some way, but it looks fine. I'm honestly not sure why the networking stack works fine for a few minutes and then randomly stops working.

**Comment by brandond** [comment]
We do most of our QA for on EC2, and haven't run into this before on any distro. I'm not able to reproduce it either. Are there any other things that might be unique to your environment? What DNS server are you using? What do your security group rules look like? Are you deploying any other software to the nodes other than K3s?

**Comment by dsikes** [comment]
Before I install k3s, everything is reachable as normal. That should rule out any of my VPC, DNS, and other configurations, as they all work as expected prior to installing k3s. It appears that k3s does update iptables, and there could be something going on there?  I am not customizing the rules in any way. I am only running k3s, no other software is being installed.

**Comment by dsikes** [comment]
@brandond What versions of Ubuntu and or Amazon Linux do you run your QA testing on within AWS?

**Comment by dsikes** [comment]
After further inspection, it appears that k3s is adding an additional default route. In my case, it was called `cni0`. If I remove that route, everything seems to work as expected. I need to do more testing to confirm, but I at least have outbound connectivity working again.

![image](https://user-images.githubusercontent.com/8764573/122099818-6ec98100-cde0-11eb-9af1-89e82f82f94f.png)

**Comment by brandond** [comment]
K3s doesn't muck about with the default route, so I suspect something else is going on. Can you grab the output of `ip rule` before and after installing K3s, as shown here:

https://github.com/rancher/rke2/issues/1053#issuecomment-854875902

**Comment by dsikes** [comment]
Before Installing K3s
![image](https://user-images.githubusercontent.com/8764573/122105397-ba7f2900-cde6-11eb-8323-035dd982bc0c.png)
![image](https://user-images.githubusercontent.com/8764573/122105573-f31f0280-cde6-11eb-9ae0-a28ef862db8f.png)


After Installing K3s
![image](https://user-images.githubusercontent.com/8764573/122105919-4db85e80-cde7-11eb-9c9d-83cb73169fb8.png)
![image](https://user-images.githubusercontent.com/8764573/122105884-43966000-cde7-11eb-8f45-0440c6f056bf.png)


The output from `ip rule` is the same. But if you look at the route table, you can see the extra `cni0` interface. Because of this, it seems to be "double homing" the default interface and so that creates all sorts of networking weirdness and would also explains why the box "feels slow". 

K3s is literally the only thing I installed, so it has to be updating the route table.
This is true on both Ubuntu 20.04 and Amazon Linux 2.

**Comment by dsikes** [comment]
Is there any harm in removing that route table entry for the `cni0` interface? If I do that, as stated, it appears to work properly., and I can still interact with k3s via `kubectl`. 

I would like to avoid any unforeseen consequences though. Any thoughts?

**Comment by brandond** [comment]
Ohhhh I see what's going on. That's not a default route, it's a route to the pod cidr.

Your VPC CIDR of 10.42.0.0/22 conflicts with the default cluster CIDR ranges: 10.42.0.0/16 for pods, and 10.43.0.0/16 for services. You should change one of these: either create new subnets for your VPC or change the K3s cluster and service CIDRs:

https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#networking

**Comment by dsikes** [comment]
Ok, I will give that a shot. Thats really funny if thats all it is. I guess I'm not the only one who liked "42" haha. Will update shortly.

**Comment by dsikes** [comment]
So, that was totally it. Thanks for your help on this one. I should've been more careful with my VPC configuration. Glad you caught that!
