### ISSUE TITLE
Send systemd notifications for both server and agent

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3459]
This issue serves to track the testing of #3430 

Original RKE2 issue: https://github.com/rancher/rke2/issues/989

**Verification**

Start k3s server and verify that there is a wait from the time `systemctl start k3s.service` is issued to the time the command returns. Same thing needs to be done for the agent, however the wait period is shorter for agent.

**Comment by rancher-max** [comment]
This has been previously validated, and confirmed it continues to happen so closing
