### ISSUE TITLE
CNI plugin "host-local" assumed to be in PATH

### ISSUE THREAD

**Issue by afbjorklund** [k3s-io/k3s#346]
**Is your feature request related to a problem? Please describe.**

The current code assumes that "host-local" is available in the PATH:

https://github.com/rancher/k3s/blob/ea834eb2ecebf8a8585b67d5438749b6f73f24fd/pkg/agent/config/config.go#L204

**Describe the solution you'd like**

It would be nice if you could configure the CNI plugins directory ?

**Describe alternatives you've considered**

Currently using a symlink from `/usr/local/sbin`, as a workaround.

**Additional context**

My plugins are located in `/usr/local/lib/cni` (which is not in the path)

**Comment by erikwilson** [comment]
k3s should ship with a version of host-local that it puts in the path, like `/var/lib/rancher/k3s/data/XXX/bin/host-local`. 

Are you using the release version of k3s? 
What is the error you are getting if host-local is not symlinked in /usr/local/sbin?

**Comment by afbjorklund** [comment]
I am using a custom build from source, i.e. I am not using the version self-extracting in data

`ERRO[0001] failed to find host-local: exec: "host-local": executable file not found in $PATH`

**Comment by erikwilson** [comment]
Would it be better to modify the path to include /usr/local/lib/cni before starting your custom compilation of k3s, rather than adding more flags to modify the path inside k3s?

**Comment by afbjorklund** [comment]
Sure, I can add it to the startup script rather than modifying the binary. Just thought you might consider it as a config option, since most distros (other than the bundled k3s one) has CNI installed outside their PATH.

I really like the `cni` binary though, definitely going to "borrow" that one - is it going upstream perhaps ? It fixes the problem where the CNI plugins package was twice as big (22M) as everything else on the system...

**Comment by afbjorklund** [comment]
Never mind, it won't work upstream (need to modify the module in the sources). `import "github.com/containernetworking/plugins/plugins/ipam/host-local" is a program, not an importable package`

**Comment by rokf** [comment]
Just tried to use `k3s` on Alpine (https://git.alpinelinux.org/aports/tree/testing/k3s/APKBUILD) and it is failing because of the same reason:

```
ERRO[0057] failed to find host-local: exec: "host-local": executable file not found in $PATH
```

**Comment by mskwon** [comment]
I am using Alpine too. You need to get cni-plugins separately and add the cni-plugins bin directory to PATH.

`apk add --no-cache cni-plugins --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`
`PATH=/usr/share/cni-plugins/bin:$PATH`

**Comment by unixfox** [comment]
how do I add the path `/usr/share/cni-plugins/bin` to the k3s openrc service?

**Comment by verbunk** [comment]
> how do I add the path `/usr/share/cni-plugins/bin` to the k3s openrc service?

I added, 
PATH=$PATH:/usr/share/cni-plugins/bin to /etc/conf.d/k3s
