### ISSUE TITLE
crypto/rand: blocked for 60 seconds

### ISSUE THREAD

**Issue by alexellis** [k3s-io/k3s#347]
**Describe the bug**

On my odroid-c2 I can't get the k3s server to come up upon reboot

```
root@c2:~# k3s kubectl get node
The connection to the server localhost:6443 was refused - did you specify the right host or port?
root@c2:~# systemctl status k3s --all
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sun 2019-04-14 07:29:38 UTC; 1min 27s ago
     Docs: https://k3s.io
  Process: 1785 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 1773 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 1786 (k3s-server)
    Tasks: 10
   CGroup: /system.slice/k3s.service
           └─1786 /usr/local/bin/k3s server

Apr 14 07:29:38 c2 systemd[1]: Starting Lightweight Kubernetes...
Apr 14 07:29:47 c2 k3s[1786]: time="2019-04-14T07:29:47.052135008Z" level=info msg="Starting k3s v0.3.0 (9a1a1ec)"
Apr 14 07:29:47 c2 k3s[1786]: time="2019-04-14T07:29:47.082678841Z" level=info msg="Running kube-apiserver --watch-cache=false --cert-dir /var/lib/rancher/k3s/server/tls/temporar
Apr 14 07:30:59 c2 k3s[1786]: crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
lines 1-15/15 (END)
```

After 60 secs it just fails:

```
Apr 14 07:30:59 c2 k3s[1786]: crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
Apr 14 07:31:21 c2 systemd[1]: k3s.service: Start operation timed out. Terminating.
Apr 14 07:31:21 c2 k3s[1786]: time="2019-04-14T07:31:21.557062822Z" level=info msg="Received SIGTERM, cancelling"
Apr 14 07:32:51 c2 systemd[1]: k3s.service: State 'stop-sigterm' timed out. Killing.
Apr 14 07:32:51 c2 systemd[1]: k3s.service: Killing process 1786 (k3s-server) with signal SIGKILL.
Apr 14 07:32:51 c2 systemd[1]: k3s.service: Main process exited, code=killed, status=9/KILL
Apr 14 07:32:51 c2 systemd[1]: k3s.service: Failed with result 'timeout'.
Apr 14 07:32:51 c2 systemd[1]: Failed to start Lightweight Kubernetes.
```

**To Reproduce**

Reboot the device 

**Expected behavior**

**Screenshots**

**Additional context**

If I spent a lot of time typing in `systemctl start k3s` and doing I/O on another tty it will eventually start after several minutes.

Could you use `/dev/urandom` instead of `/dev/random` on low-powered devices?

**Comment by ibuildthecloud** [comment]
@alexellis I believe this only happens on first boot because after all the certs are generated we don't do this again.  Do you see that behavior?  Also is this just fixed by changing the TimeoutSec in the systemd k3s.unit file?  Look at the diff in this PR https://github.com/rancher/k3s/pull/226/files

**Comment by alexellis** [comment]
I have rebooted 2 to 3 times on this one.

**Comment by ibuildthecloud** [comment]
@alexellis Just to clarify, so you have started k3s successfully once?  And then a `systemctl restart k3s` will still fail?

**Comment by erikwilson** [comment]
For crypto.rand reader the expected behavior is as follows:
```
// Reader is a global, shared instance of a cryptographically
// secure random number generator.
//
// On Linux and FreeBSD, Reader uses getrandom(2) if available, /dev/urandom otherwise.
// On OpenBSD, Reader uses getentropy(2).
// On other Unix-like systems, Reader reads from /dev/urandom.
// On Windows systems, Reader uses the CryptGenRandom API.
// On Wasm, Reader uses the Web Crypto API.
```

Doing a quick search I am curious if `getrandom` is broken for the odroid kernel you are using, or if it is just very slow, @alexellis .

**Comment by erikwilson** [comment]
This should be fixed with rancher/k3s/pull/342, I am guessing systemd is killing the process in the middle of key generation. The root of the issue is probably low entropy on the system tho, entropy can be viewed with `cat /proc/sys/kernel/random/entropy_avail`. `haveged` or `rng-tools` may be helpful in that scenario.

**Comment by alexellis** [comment]
```
root@c2:~# cat /proc/sys/kernel/random/entropy_avail
128
```

**Comment by alexellis** [comment]
```
sudo reboot
root@c2:~# cat /proc/sys/kernel/random/entropy_avail
29
```

**Comment by erikwilson** [comment]
It looks like there are two issues here @alexellis, the first being that `TimeoutStartSec=infinity` does not work for you, can you verify the version of systemd that you are using with `systemctl --version`? I suspect it is prior to 229 and #365 will fix the timeout. 

The other issue is that your system looks to be very low on entropy so will be very slow, some entropy is needed to generate secure keys even if urandom is being used.
