### ISSUE TITLE
k3s use embedded etcd  should provide a configuration file to configure etcd parameters

### ISSUE THREAD

**Issue by 290760647** [k3s-io/k3s#3473]
k3s use embedded etcd  should provide a configuration file to configure etcd parameters，Just like RKE, we can configure ETCD space and compression using cluster.yml！

**Comment by pekinglone** [comment]
I have the same problem,I was created a k3s cluster and used the embedded ETCD, the default size of ETCD is 2G.
----------
etcdctl --cacert=server-ca.crt --cert=client.crt --key=client.key --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX |             ERRORS             |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
| 127.0.0.1:2379 | 7f0b6bf57639838f |  3.4.13 |  2.1 GB |      true |      false |         5 |       7321 |               7321 |   memberID:9154529369555305359 |
|                |                  |         |         |           |            |           |            |                    |                 alarm:NOSPACE  |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
------
I want to adjust the database size of ETCD by using the --quota-backend-bytes parameter, but K3s does not support configuring this parameter.
K3S supports to set kube-apiserver startup parameters by adding kube-apiserver-arg to /etc/rancher/k3s/config.yaml. Is it possible to define the etcd parameter in the same way?
