### ISSUE TITLE
Test and Certify OpenSUSE (Leap) 15 SP3 [k3s]

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3501]
Test and Certify OpenSUSE (Leap) 15 SP3 on v1.21, v1.20, v1.19, v1.18 (with latest June patches or newer).
The precise versions mentioned here and the milestone are subject to change!

amd64 cpu architecture only for now.

**Comment by ShylajaDevadiga** [comment]
Validated OpenSuse (Leap) 15 SP3 as per New OS Certification matrix on k3s version  v1.21.3-rc1+k3s1, v1.20.9-rc1+k3s1, v1.19.13-rc1+k3s1

- Conformance Test
- Basic k8s functionality test
- Deployed K3s as a local management cluster
- Validated K3s with docker container runtime
- Upgrade using installer and System Upgrade Controller

Deployed rancher on k3s v1.21.1-rc1+k3s1

![image](https://user-images.githubusercontent.com/56045581/126045533-009f1d63-16d5-4bfe-80d8-a1312a04a9b9.png)
![image](https://user-images.githubusercontent.com/56045581/126045546-09d4b7c5-61a0-4a85-82ce-d6c351240e99.png)

Deployed rancher on k3s v1.20.9-rc1+k3s1
![image](https://user-images.githubusercontent.com/56045581/126046076-7aac9b50-5a50-4260-b22a-cbe30ec9491c.png)

Deployed rancher on k3s v1.19.13-rc1+k3s1
![image](https://user-images.githubusercontent.com/56045581/126046856-de97b362-bb6d-42df-aa7e-5c3abbf15c6d.png)
