### ISSUE TITLE
Test and Certify Alma Linux 8.3 and 8.4 [k3s]

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3502]
on v1.21, v1.20, v1.19, v1.18 (with latest June patches or newer).
The precise versions mentioned here and the milestone are subject to change!

amd64 cpu architecture only.

**Comment by davidnuzik** [comment]
Alma is moved to backlog for future consideration now. Rocky is still planned for by v1.21.3+k3s1.

**Comment by cwayne18** [comment]
No longer in the plans, closing this out
