### ISSUE TITLE
Test and Certify Rocky Linux 8.3 and 8.4 [k3s]

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#3503]
on v1.21, v1.20, v1.19, v1.18 (with latest June patches or newer).
The precise versions mentioned here and the milestone are subject to change!

amd64 cpu architecture only.

**Comment by rancher-max** [comment]
Validated Rocky LInux 8.4 using etcd and mysql backends on k3s versions 1.19.12-rc1+k3s2, 1.20.8-rc1+k3s2, and 1.21.2-rc1+k3s2. Will do a sanity check when we have rcs of bumped k8s versions as well. Validated the following per our matrix:
- sonobuoy conformance
- rancher local cluster deployment
- upgrade using SUC
- automated regression checks
- docker cri install
