### ISSUE TITLE
Local-path volume on master node

### ISSUE THREAD

**Issue by pavanfhw** [k3s-io/k3s#3506]
**Environmental Info:**
K3s Version:  k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: Linux 5.4.0-48-generic #52 SMP Sat Sep 26 08:27:15 UTC 2020 x86_64 GNU/Linux

Cluster Configuration: 1 server, 2 agents

**Describe the bug:**

My master node has the taint `k3s-controlplane=true:NoExecute`. I am trying to create a statefulset with toleration for this taint. The statefulset creates `local-path` pvc for each pod, the pvc for the master node is stuck at `Pending`. The pvc has the annotation `volume.kubernetes.io/selected-node: <master-node>`. These are the events of the pvc:
```
Events:
  Type     Reason                Age                  From                                                                                               Message
  ----     ------                ----                 ----                                                                                               -------
  Normal   WaitForFirstConsumer  15m                  persistentvolume-controller                                                                        waiting for first consumer to be created before binding
  Normal   Provisioning          3m31s (x5 over 15m)  rancher.io/local-path_local-path-provisioner-6d59f47c7-vkcmn_d74d6e69-d047-11eb-8aba-2e3d2679af6b  External provisioner is provisioning volume for claim "linstor/datadir-piraeus-op-etcd-1"
  Warning  ProvisioningFailed    89s (x5 over 13m)    rancher.io/local-path_local-path-provisioner-6d59f47c7-vkcmn_d74d6e69-d047-11eb-8aba-2e3d2679af6b  failed to provision volume with StorageClass "local-path": failed to create volume pvc-e98332a5-bdd7-4cae-918e-2662a6477e6f: create process timeout after 120 seconds
  Normal   ExternalProvisioning  19s (x63 over 15m)   persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
```
The other pvc are created OK on the agents nodes, so I'm thinking I need to do something to be able to provision local-path pvc on the master node, like the toleration for the pods, but there is no specific error problem for k3s not being able to provision the volume.

**Steps To Reproduce:**

- Installed K3s via K3os ISO
- Master has the taint `k3s-controlplane=true:NoExecute`
- Create a statefulset with the toleration 
```
tolerations:
        - key: k3s-controlplane
          operator: Equal
          value: "true"
          effect: NoExecute
```
and a volumeClaimTemplates that uses the local-path storage class, it is the default is my case
```
- metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
```

**Expected behavior:**

Pod and pvc created on master node
**Actual behavior:**

pvc created on master node, but provision timeout after 120 seconds resulting on pod not being able to go up
**Additional context / logs:**

**Comment by brandond** [comment]
The helper pod that is started by local-path-provisioner to create the local path should tolerate all taints. Do you see a pending helper pod? If not, do you see anything in the local-path-provisioner controller pod logs?

**Comment by pavanfhw** [comment]
I don't see any helper pods, not in the statefulset namespace nor in the `kube-system` namespace.

The logs from the local-path-provisioner pod has this messages in loop until 15 failures when it gives up syncing:
```
provision "linstor/datadir-piraeus-op-etcd-1" class "local-path": started
time="2021-06-24T14:55:53Z" level=info msg="Creating volume pvc-e98332a5-bdd7-4cae-918e-2662a6477e6f at c1-k8m.vulca.cloud:/var/lib/rancher/k3s/storage/pvc-e98332a5-bdd7-4cae-918e-2662a6477e6f" 
ERROR: logging before flag.Parse: I0624 14:55:53.354114       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"linstor", Name:"datadir-piraeus-op-etcd-1", UID:"e98332a5-bdd7-4cae-918e-2662a6477e6f", APIVersion:"v1", ResourceVersion:"3972308", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "linstor/datadir-piraeus-op-etcd-1"
ERROR: logging before flag.Parse: W0624 14:57:55.607252       1 controller.go:686] Retrying syncing claim "linstor/datadir-piraeus-op-etcd-1" because failures 0 < threshold 15
ERROR: logging before flag.Parse: E0624 14:57:55.607280       1 controller.go:701] error syncing claim "linstor/datadir-piraeus-op-etcd-1": failed to provision volume with StorageClass "local-path": failed to create volume pvc-e98332a5-bdd7-4cae-918e-2662a6477e6f: create process timeout after 120 seconds
ERROR: logging before flag.Parse: I0624 14:57:55.607325       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"linstor", Name:"datadir-piraeus-op-etcd-1", UID:"e98332a5-bdd7-4cae-918e-2662a6477e6f", APIVersion:"v1", ResourceVersion:"3972308", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "local-path": failed to create volume pvc-e98332a5-bdd7-4cae-918e-2662a6477e6f: create process timeout after 120 seconds
```

**Comment by brandond** [comment]
Can you delete the pvc, and then run `kubectl get pods -A` a few times immediately after recreating it? If you look at the code, it creates a helper pod and then waits for it to exit successfully - for some reason this is failing but we're not getting an indication as to why.

https://github.com/rancher/local-path-provisioner/blob/v0.0.19/provisioner.go#L411-L436

**Comment by pavanfhw** [comment]
I was able to resolve the problem. The helper pod was not being able to be created on the master node due to configuration. It was not whitelisted on a server to download images.

**Comment by pavanfhw** [comment]
This was a not a bug, it was a misconfiguration on my cluster. Thank you @brandond for the help finding the problem.
