### ISSUE TITLE
fleet-controller constantly crashing

### ISSUE THREAD

**Issue by 6485im43** [k3s-io/k3s#3518]
**Environmental Info:**
K3s Version: 
v1.21.1+k3s1 (75dba57f)
Go Version: 
go1.16.4

**Node(s) CPU architecture, OS, and Version:**
Linux K3S01 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

**Cluster Configuration:**
standalone server (one node)

**Describe the bug:**
Fleet-Controller constantly crashing:
fleet-system              fleet-controller-79554fcbf5-np96b          0/1     CrashLoopBackOff   177        21h

**Actual behavior:**
~# kubectl logs fleet-controller-79554fcbf5-np96b -n fleet-system -p
Error: Get "https://10.43.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": dial tcp 10.43.0.1:443: connect: connection refused

**Additional context / logs:**
Jun 26 19:55:36 K3S01 k3s[432]: E0626 19:55:36.967644     432 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"fleet-controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=fleet-controller pod=fleet-controller-79554fcbf5-np96b_fleet-system(404c2114-dec1-4def-9ae4-65151bbe0913)\"" pod="fleet-system/fleet-controller-79554fcbf5-np96b" podUID=404c2114-dec1-4def-9ae4-65151bbe0913
Jun 26 19:55:49 K3S01 k3s[432]: I0626 19:55:49.968233     432 scope.go:111] "RemoveContainer" containerID="0e77b5fc55a5330e51a924ae2e18975c329419dd2b822965d8d32fd2af9148b7"

~# kubectl get services --all-namespaces
NAMESPACE       NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default         kubernetes             ClusterIP      10.43.0.1       <none>           443/TCP                      29d

**Comment by brandond** [comment]
Inability to reach the apiserver service usually indicates a problem with inter-node traffic being blocked. Debian frequently has two issues: broken iptables-nft, and NetworkManager enabled. Switch your iptables into legacy mode, make sure NetworkManager is disabled, and see if the problem goes away after rebooting.

**Comment by 6485im43** [comment]
problem fixed.

Thanks!
