### ISSUE TITLE
How to use containerd

### ISSUE THREAD

**Issue by yyf1986** [k3s-io/k3s#3520]
**Environmental Info:**
K3s Version: k3s version v1.21.2+k3s1 (5a67e8dc)

Node(s) CPU architecture, OS, and Version: Linux host-10-19-83-32 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:1 server

**Describe the bug:**

I install containerd myself,and run 'k3s server --disable traefik --container-runtime-endpoint=/run/containerd/containerd.sock' then the console log like 
`
E0628 15:19:59.865807   12294 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0628 15:20:04.867441   12294 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0628 15:20:09.868416   12294 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0628 15:20:14.869383   12294 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0628 15:20:19.870794   12294 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

`

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by cwayne18** [comment]
Hi there, thank you for taking the time to log this issue!  K3s actually uses containerd by default, is there any particular reason you're passing the --container-runtime-endpoint (i.e. are you trying to use a different version of containerd)?

Also if you could please attach the logs from the k3s server that could help us pin down the issue further
