### ISSUE TITLE
CI failures due to kine NULL prev_revision when ranging on /bootstrap

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3523]
Seems to be flakey - doesn't occur on every run. May be triggered by https://github.com/k3s-io/k3s/pull/3422 but the underlying bug is in somewhere in Kine. There's another issue in that code, in that the kine client Delete operation doesn't use a transaction, which will cause it to fail because the kine server only supports transactional deletes - but that's not what's causing this.

Ref:
* https://drone-publish.k3s.io/k3s-io/k3s/376/1/3
* https://drone-pr.k3s.io/k3s-io/k3s/1267/1/3

```console
time="2021-06-22T20:56:21.620608398Z" level=error msg="error while range on /bootstrap /bootstrap: sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"
{"level":"warn","ts":"2021-06-22T20:56:21.620Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-4bb28906-4404-4bba-a331-5f3076e58016/kine.sock","attempt":0,"error":"rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"}
time="2021-06-22T20:56:21.621013908Z" level=fatal msg="starting kubernetes: preparing server: rpc error: code = Unknown desc = sql: Scan error on column index 0, name \"prev_revision\": converting NULL to int64 is unsupported"
```

**Comment by rancher-max** [comment]
Closing as this is mostly CI and bootstrap issues have been validated already
