### ISSUE TITLE
k3s service error msg "Failed to connect to proxy" error="dial tcp 192.168.88.17:6443: co...ute to host"

### ISSUE THREAD

**Issue by geneliu** [k3s-io/k3s#3559]
**Environmental Info:**
K3s Version: 
v1.21.2+k3s1

Node(s) CPU architecture, OS, and Version: 
x86_64, RHEL7.9

Cluster Configuration:
Single node server

**Describe the bug:**
Installed the k3s server on VM on openstack (with ip 192.168.88.17 via dhcp), make an image from the VM. 
Create a new instance from the image with a new ip (192.168.88.12 via dhcp).
systemctl status k3s.service shows error message below:

time="2021-06-30T21:18:30.434609851-04:00" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.88.17:6443: co...ute to host"
time="2021-06-30T21:18:30.434687885-04:00" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.88.17:6443: conn...ute to host"

Something requires clean up about the old ip address (192.168.88.17) before make the image template?
Where is the ip (192.168.88.17) information stored if a clean up required?

**Steps To Reproduce:**
Installed the k3s server on VM on openstack (with ip 192.168.88.17 via dhcp), make an image from the VM. 
Create a new instance from the image with a new ip (192.168.88.12 via dhcp).
systemctl status k3s.service
- Installed K3s: 

**Expected behavior:**
systemctl status k3s -- no error message complaining the old ip address which is from the template image

**Actual behavior:**
k3s service show error message, the cluster has coredns udp i/o timeout.
read udp 10.42.0.18:55701->10.43.0.10:53: i/o timeout (10.43.0.10:53 is coredns svc)

**Additional context / logs:**
A restart of k3s will resolve the coredns udp i/o timeout issue. And other pods which depends on dns query will up running from dead-loop restarting.

**Comment by brandond** [comment]
I would recommend installing with INSTALL_K3S_SKIP_START=true if you're going to make an image of the host, otherwise every instance you start from that image will essentially be a copy of the same cluster - same root CA, same kubeconfig, same information about the original (but nonexistent) node, etc.

**Comment by geneliu** [comment]
Thank you @brandond for your suggestion!
But I have to start k3s because I need install extra services like docker registry (harbor), httpd (nginx) during the template/image build. 

The question is that any extra clean up I missed to clean/remove the ip address in that template VM? My guess is something in etcd? Or I need pass the "--bind-address" explicitly with systemd starting the k3s service?

**Comment by geneliu** [comment]
I should mention that old version (we picked last year) has not an issue.
```# k3s --version
k3s version v1.0.1 (e94a3c60)```

Our existing template was build a year ago with k3s version v1.0.1. Now I am trying to update it to the latest v1.21.x.

**Comment by brandond** [comment]
You're building a cluster on one node, and then shutting it down and loading it up on a new node. It's going to go looking for the other node, unless you delete the original node from the cluster after starting it up on the new node.

**Comment by geneliu** [comment]
The scenario is exactly. What is interesting for me is that a restart of the k3s service (systemd restart k3s) will bring up the cluster running correct without any error. What I am doing so for as a workaround is use ansible rescue to restart k3s service after 90s timeout of `kubectl wait for pods ready`.

Also k3s v1.0.1 (early last year) has no such an issue. I wonder something must changed.

**Comment by brandond** [comment]
v1.0.1 is from December of 2019 - over a year and a half ago - and includes Kubernetes 1.16. A LOT has changed, both in Kubernetes, and in K3s, since then.

If you're not already doing this, I would probably drain/cordon the original node before you image it, and delete the original node from the Kubernetes cluster when the new node starts up. That should help things get rescheduled sooner.

**Comment by geneliu** [comment]
@brandond Thanks for the suggestion and support. I am going to live with the 'restart' workaround for now.

**Comment by EvanCarroll** [comment]
I'm having this same issue. Also using OpenStack. 

* So is Icy, over here https://github.com/k3s-io/k3s/issues/535#issuecomment-1020295149

Here is another copy of the same issue (but maybe not with openstack, I've asked):

* https://github.com/k3s-io/k3s/issues/4587#issue-1064684164
