### ISSUE TITLE
Set limits and forward additional ports in example docker-compose.yaml

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3567]
From @joeky888 in #3393

> The default values of ulimits were set to 65536 in EKS, which can be configured in docker-compose.yml as well. And port 80/443 should be forwarded by default for all ingress controllers.

IMO this file should probably be in the `contrib` directory since we don't really offer any support for it.

**Comment by rancher-max** [comment]
Validated by running `docker-compose up` on master:

```
ubuntu@ip-172-31-18-13:~/k3s$ sudo docker container inspect -f "{{.HostConfig.Ulimits}}" k3s_agent_1
[nproc=65535:65535 nofile=65535:65535]
ubuntu@ip-172-31-18-13:~/k3s$ sudo docker container inspect -f "{{.HostConfig.Ulimits}}" k3s_server_1
[nproc=65535:65535 nofile=65535:65535]
```
