### ISSUE TITLE
K3S Agent :Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dennis08** [k3s-io/k3s#3569]
**Environmental Info:**
K3s Version:  V1.21.2

Node(s) CPU architecture, OS, and Version:
X86(K3S LB) + NVIDIA Jetson Xaver ARM64(K3S Masterx2, K3S Agentx2), Ubuntu18.04

Cluster Configuration:
K3S HA:  1LB, 2Server, 2Agents

**Describe the bug:**
K3S Cluster works fine but when get nodes from K3S agent get an authority error ?
```
root@k3s-agent1:~# kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Step to reproduce this issue:**
- Install Mysql and Rancher2.5.8 in X86 (K3S LB, IP:192.168.1.195)
```
docker run -d  --name k3s-mysql  --restart=always  -v //home/aiot/k3s/mysql/conf:/etc/mysql/conf.d -v //home/aiot/k3s/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mysql:5.7.34 --default-time-zone=+8:00
docker run -d --restart=unless-stopped --name rancher-server -v /data/rancher/:/var/lib/rancher/ -p 8088:80 -p 8443:443 --privileged rancher/rancher:stable
```
- Installed K3s master on two Jetson Xavier:(K3S Master, IP: 192.168.1.170/192.168.1.171)
```export INSTALL_K3S_EXEC="--datastore-endpoint=mysql://root:root@tcp(k3s-mysql-server:3306)/k3sdb --kube-apiserver-arg service-node-port-range=1-65000 --no-deploy traefik --write-kubeconfig  ~/.kube/config --write-kubeconfig-mode 666"
curl -sfL https://get.k3s.io/ | sh -s -
```
K3S Master kubectl get nodes and pods works fine. This cluster works fine too.
![image](https://user-images.githubusercontent.com/6428170/124360045-2c19fc80-dc5a-11eb-8d52-f20e37d330cd.png)

- Installed K3s agent on other two Jetson Xavier:
```
export K3S_TOKEN=K10cdea6a8c87dd05a23cbd21b01338ed740fbdf053e8760ecfc7ec1bb5456523e9::server:c43844de5ba8162d48768ba021477add
export INSTALL_K3S_EXEC="--docker --kube-apiserver-arg service-node-port-range=1-65000 --no-deploy traefik --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666"
export K3S_URL=https://192.168.1.195:6443 
curl -sfL https://get.k3s.io/ | sh -s -
```

K3S Agent kubectl get nodes get these error 
```
root@k3s-agent1:~# kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Comment by brandond** [comment]
K3s agents don't run the Kubernetes control-plane and don't have a copy of the admin kubeconfig. If you want to do this, you can copy the file from /etc/rancher/k3s/k3s.yaml on the servers to somewhere on the agent, and edit it to contain the proper server address.
