### ISSUE TITLE
k3s[3753781]: http: TLS handshake error from : remote error: tls: bad certificate

### ISSUE THREAD

**Issue by xiaomabetter** [k3s-io/k3s#3572]
versioin:  v1.17.6 

The cluster was created less than a month ago

**Comment by brandond** [comment]
The 1.17 branch has been out of support for while; could you try an up to date version?

**Comment by nurhun** [comment]
Having the same issue. Installed k3s with below arguments

```
curl -sfL https://get.k3s.io | sh -s - server \
  --token ${token} \
  --datastore-endpoint="postgres://${dbuser}:${dbpass}@${db_endpoint}/${dbname}" \
  --disable servicelb \
  --disable traefik \
  --disable local-storage \
  --disable-cloud-controller \
  --kubelet-arg provider-id=aws:///$provider_id \
  --write-kubeconfig-mode 644 \
  --tls-san ${lb_dns_name}
```

Also tried to edit /var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-deployment.yaml ... spec.template.spec.containers
```
        args:
        - /metrics-server
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --logtostderr

```
Still the same issue.

**Comment by brandond** [comment]
That one message isn't much to work with. Can you attach the complete service logs from both the server and agent nodes?
