### ISSUE TITLE
Agents, will not pick up in servers

### ISSUE THREAD

**Issue by SinLess-Games** [k3s-io/k3s#3575]
**Environmental Info:**
K3s Version: 
k3s version v1.21.2+k3s1 (5a67e8dc)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 

2 cores
2048mb RAM
ubuntu 20.04

Cluster Configuration:

2 servers 4 agents
**Describe the bug:**

Agents will not pick up in servers when running "sudo k3s kubectl get node"
output recieved
`NAME     STATUS   ROLES                  AGE   VERSION
hoku-1   Ready    control-plane,master   48m   v1.21.2+k3s1
hoku-2   Ready    control-plane,master   61m   v1.21.2+k3s1
`   
**Steps To Reproduce:**

re installed k3s on both servers three times, then went to re register my agents still no pick up.
- Installed K3s: 
code used to install for server
`
export K3S_DATASTORE_ENDPOINT='mysql://admin:Shellshocker93!@tcp(172.16.3.21:33306)/k3s' 

curl -fsL https://get.k3s.io | sh -s server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san 172.16.0.0
`
got token with 
`
sudo cat /var/lib/rancher/k3s/server/node-token 

#output
K10694cea5d49d7da432bc96705e39bc4be687d85c7994e63648e83ee8a66780f80::server:42a1815a502c44754133ceb4d944d0c2
`

Installed Agents with 
`
curl -sfL https://get.k3s.io | K3S_URL=https://172.16.0.0:6443 K3S_TOKEN=K10694cea5d49d7da432bc96705e39bc4be687d85c7994e63648e83ee8a66780f80::server:42a1815a502c44754133ceb4d944d0c2 sh -
`

**Additional context / logs:**

`
Jul 06 07:08:39 hele-1 k3s[3230]: time="2021-07-06T07:08:11.358716883Z" level=error msg="failed to get CA certs: Get \ "https://127.0.0.1:6444/cacerts\" EOF"
Jul 06 07:08:41 hele-1 k3s[3230]: time="2021-07-06T07:08:11.358716883Z" level=error msg="failed to get CA certs: Get \ "https://127.0.0.1:6444/cacerts\" read tcp 127.0.0.1:40466->127.0.0.1:6444: read: connection reset by peer"
`

How ever the service is running on all agents they wont connect through to my two servers. I am using kemp load balancing using tcp round robin with vip 172.16.0.0:6443

**Comment by brandond** [comment]
172.16.0.0 isn't a valid IP address, it has no host bits set.
