### ISSUE TITLE
api healthchecks not available

### ISSUE THREAD

**Issue by piwi3910** [k3s-io/k3s#3576]
Hi, it seems the api health checks healthz, livez , readyz and ever the older health are not available
https://kubernetes.io/docs/reference/using-api/health-checks/ 

I'm trying to setup my LB in a more smart way to check the health of an api server and not just the port.
however without the api health endpoints this is not possible
I'm a bit confused regarding the not authorized as those endpoints should not need authorization. 
or it's just a void message and the error 401 just means they don't exist in k3s.

root@k8s-master02:~# curl -k https://localhost:6443/livez?verbose
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}root@k8s-master02:~# curl -k https://localhost:6443/health
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}root@k8s-master02:~# curl -k https://localhost:6443/healthz
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**Comment by brandond** [comment]
These endpoints exist, they are just not accessible without authentication. The insecure port and anonymous auth are both disabled by default on modern versions of Kubernetes, so you'd need to find some way to authenticate your health checks (using a client cert, etc)
https://github.com/kubernetes/kubernetes/issues/43784#issuecomment-304524127
