### ISSUE TITLE
k3s agent start failed 

### ISSUE THREAD

**Issue by gouchaoer** [k3s-io/k3s#3577]
**Environmental Info:**
K3s Version: 

```
./k3s-arm64 -v
k3s-arm64 version v1.21.2+k3s1 (5a67e8dc)
go version go1.16.4
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
```
uname -a
Linux a1000 4.19.66+2.0.g322665d6.202106191046 #1 SMP Sat Jun 19 02:42:07 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Describe the bug:**

We have a custom arm OS on our own chip. When I try to run k3s agent on it:
```
`./k3s-arm64 agent --server https://10.28.10.80:6443 --token K10cb49f7abc195575b8da1845b1371cce90f540603bd8945b0c5824420b27e1a32::server:8ccf7b0f02c585ca3f2ff323ef8e13e4`
```

it failed with:
![image](https://user-images.githubusercontent.com/5207582/124577024-792ae800-de7f-11eb-9a4a-dc3eda921a5b.png)

I think our OS kernel is not OK. So what's wrong with our OS kernel?

**Comment by brandond** [comment]
Are you running this within a VPS or other restricted environment? The logs indicate that Kubernetes is unable to load any of the required modules, set sysctl, or create kernel ipsets.
