### ISSUE TITLE
Automated tagging of system-agent images based on K3s releases

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#3581]
Basically identical to what was done for: https://github.com/rancher/rke2/issues/1206

We need to dispatch on release to the `rancher/system-agent-installer-k3s` repository for every new K3s release.

**Comment by katran001** [comment]
Moving this to backlog v1.22 since it will never be closed

**Comment by caroline-suse-rancher** [comment]
Closing due to age
