### ISSUE TITLE
Windows containerd endpoints and source-vip are causing errors in RKE2.

### ISSUE THREAD

**Issue by phillipsj** [k3s-io/k3s#3585]
The containerd socket information has a typo and being generated incorrectly. Those issues have been corrected and unit tests have been added to verify the fix for generating the correct runtime endpoint. 

In addition to the above, the crictl template was incorrect due to upstream changes that altered the expected format resulting in the incorrect one being generated. 

Lastly, the source-vip had the HNS network hard coded to the flannel value which doesn't allow it to be overridden when other CNIs are used.

**Comment by brandond** [comment]
Nothing to test; only used in RKE2
