### ISSUE TITLE
After install prometheus-operator,controller-manager and scheduler can not be monitor

### ISSUE THREAD

**Issue by xiaomabetter** [k3s-io/k3s#3587]
controller-manager and scheduler  running bind address is 127.0.0.1 ，i want change it by --kube-scheduler-arg and --kube-controller-arg . but It doesn't work。

version:  1.21.0

startup parameter ：

/usr/local/bin/k3s server --docker --cluster-cidr 172.21.0.0/16 --service-cidr 192.168.236.0/22 --flannel-backend=none --datastore-endpoint=etcd --kube-apiserver-arg "etcd-servers=http://10.40.191.236:2379,http://10.40.10.168:2379,http://10.40.46.124:2379"  --tls-san 165.154.38.34 --node-ip 10.40.26.145 --node-external-ip 123.132.38.34 --no-deploy servicelb  --kube-proxy-arg "proxy-mode=ipvs" "masquerade-all=true" --kube-proxy-arg "metrics-bind-address=0.0.0.0" --kube-scheduler-arg "bind-address=10.40.26.145" --kube-controller-arg "bind-address=10.40.26.145"

--kube-scheduler-arg "bind-address=10.40.26.145" --kube-controller-arg "bind-address=10.40.26.145"

**Comment by brandond** [comment]
Can you explain more about what you mean by "doesn't work"? What behavior do you see?

**Comment by xiaomabetter** [comment]
![image](https://user-images.githubusercontent.com/13087771/125592359-6f62afe4-6335-4aa2-bd22-f3866f31a6c4.png)

![image](https://user-images.githubusercontent.com/13087771/125592578-35dfdd62-4aba-4e26-9066-b17521957c78.png)

controller-manager and scheduler running bind address is 127.0.0.1 , how to change the listening addr  ???

**Comment by brandond** [comment]
Have you tried `--controller-manager-arg=bind-address=0.0.0.0` ?
