### ISSUE TITLE
k3s starting user datastore-endpoint  etcd and etcd cluster is external, why k3s server start another etcd itself

### ISSUE THREAD

**Issue by xiaomabetter** [k3s-io/k3s#3588]
version: 1.21.0

starting parameter :

/usr/local/bin/k3s server --docker --cluster-cidr 172.21.0.0/16 --service-cidr 192.168.236.0/22 --flannel-backend=none --datastore-endpoint=etcd --kube-apiserver-arg "etcd-servers=http://10.40.191.236:2379,http://10.40.10.168:2379,http://10.40.46.124:2379"  --tls-san 135.12.38.65 --node-ip 10.40.26.145 --node-external-ip 135.12.38.65 --no-deploy servicelb  --kube-proxy-arg "proxy-mode=ipvs" "masquerade-all=true" --kube-proxy-arg "metrics-bind-address=0.0.0.0" --kube-scheduler-arg bind-address=10.40.26.145 --kube-controller-arg bind-address=10.40.26.145

when started, use netstat -ntlp find there listening 127.0.0.1:2379 and 10.40.26.145:2380  

I try add --disable etcd , but it does not work。

**Comment by brandond** [comment]
'etcd' is not a valid k3s datastore endpoint; it's falling back to the default kine sqlite endpoint which you then override with the kube-apiserver arg.  Do it like this: `-datastore-endpoint=http://10.40.191.236:2379`

You may not be able to pass multiple endpoints. I am not sure that the upstream kube-apiserver actually uses multiple endpoints; last time I checked it actually just connects to the first in the list. The usual deployment pattern is to run etcd alongside the apiserver, and point the apiserver at the local instance.

**Comment by xiaomabetter** [comment]
is there no way to use external etcd clusters ?

**Comment by xiaomabetter** [comment]
How to use etcd cluster for multiple k3s master servers to achieve high availability ？

**Comment by brandond** [comment]
Have you tried `-datastore-endpoint=http://server1:2379,http://server2:2379,http://server3:2379` ?
