### ISSUE TITLE
Traefik not reloading after a configuration update

### ISSUE THREAD

**Issue by lbm** [k3s-io/k3s#3593]
**Environmental Info:**
K3s Version: `k3s version v1.21.2+k3s1 (5a67e8dc)`

Node(s) CPU architecture, OS, and Version: `Linux REDACTED 5.10.34-sunxi64 #21.05.1 SMP Fri May 7 15:50:19 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Cluster Configuration: 1 server, 5 agents

**Describe the bug:**
After updating `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` with new content, the `helm-install-traefik` pod runs without any issues but the actual Traefik deployment doesn't restart to reflect the changes. The same applies even when changes are made to the original `/var/lib/rancher/k3s/server/manifests/traefik.yaml` file.

**Steps To Reproduce:**
Stock installation without any custom configuration. Agents configured in the same way. Install `cert-manager` v1.4.0 and set up a certificate so that a secret exists for Traefik to be provided with. Create `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` and populate with the following:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    extraVolumeMounts:
    - name: ssl
      mountPath: /ssl
    extraVolumes:
    - name: ssl
      secret:
        secretName: REDACTED
    dashboard:
      enabled: true
      domain: REDACTED
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/redirect-entry-point: https
```

**Expected behavior:**
Traefik deployment should be restarted with the added `ssl` volume being made available.

**Actual behavior:**
The deployment isn't restarted, even though the `helm-install-traefik` pod seems to complete with no errors.

**Additional context / logs:**

Logs from the `helm-install-traefik` pod:
```
CHART=$(sed -e "s/%{KUBERNETES_API}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/g" <<< "${CHART}")
set +v -x
+ cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
+ update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
+ '[' '' '!=' true ']'
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ tiller --listen=127.0.0.1:44134 --storage=secret
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://charts.helm.sh/stable/ 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ ++ jq helm_v2 -r ls '.Releases | length'--all 
'^traefik$' --output json
[main] 2021/07/07 16:25:09 Starting Tiller v2.17.0 (tls=false)
[main] 2021/07/07 16:25:09 GRPC listening on 127.0.0.1:44134
[main] 2021/07/07 16:25:09 Probes listening on :44135
[main] 2021/07/07 16:25:09 Storage driver is Secret
[main] 2021/07/07 16:25:09 Max history per release is 0
[storage] 2021/07/07 16:25:09 listing all releases with filter
+ EXIST=
+ '[' '' == 1 ']'
+ '[' '' == v2 ']'
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/traefik.tgz
+ '[' '!' -f /chart/traefik.tgz.base64 ']'
+ return
+ '[' install '!=' delete ']'
+ helm_repo_init
+ grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
chart path is a url, skipping repo update
Error: no repositories configured
+ true
+ return
+ helm_update install --set global.systemDefaultRegistry=0
+ '[' helm_v3 == helm_v3 ']'
++ helm_v3 ls -f '^traefik$' --namespace kube-system --output json
++ tr '[:upper:]' ++ jq -r '"\(.[0].app_version),\(.[0].status)"'
'[:lower:]'
+ LINE=2.4.8,deployed
++ echo 2.4.8,deployed
++ cut -f1 -d,
+ INSTALLED_VERSION=2.4.8
++ echo 2.4.8,deployed++ cut -f2 -d,

+ STATUS=deployed
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ '[' install = delete ']'
+ '[' -z 2.4.8 ']'
+ '[' deployed = deployed ']'
+ echo Already installed traefik, upgrading
Already installed traefik, upgrading
+ shift 1
+ helm_v3 upgrade --set global.systemDefaultRegistry=0 traefik https://10.43.0.1:443/static/charts/traefik-9.18.2.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Release "traefik" has been upgraded. Happy Helming!
NAME: traefik
LAST DEPLOYED: Wed Jul  7 16:25:13 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 10
TEST SUITE: None
+ exit
```

Possibly related issue: #1609. I have tried matching the format described by @niusmallnan in https://github.com/k3s-io/k3s/issues/1609#issuecomment-610723612, but even that didn't work. Considering that the format I'm using above is the same as the default `traefig.yaml` config that k3s provides, I'd think it would work either way.

Please let me know if I can provide any other information.

**Comment by brandond** [comment]
We're packaging the vanilla helm chart from upstream; if it doesn't reload to apply the changes when the helm chart is upgraded then a bug probably needs to be filed over there: https://github.com/traefik/traefik-helm-chart

**Comment by lbm** [comment]
Thank you @brandond, after more research today it definitely appears to be a problem upstream with the newer versions of the chart. Rolling back to K3s version `v1.20.8+k3s1` fixes the issue. Closing this issue for the time being.
