### ISSUE TITLE
rootless: remove cgroup v1 support ("none" cgroup driver)

### ISSUE THREAD

**Issue by AkihiroSuda** [k3s-io/k3s#3596]
The k/k PR for rootless was merged into the upstream (Kubernetes 1.22): https://github.com/kubernetes/kubernetes/commit/ebbe63f116500b5f3c4fcd1dacbc8d7eb1c7e7a2

We no longer need any patch for cgroup v2, but we still need the [`[Not for Upstream] kubelet: new cgroup driver: "none"`](https://github.com/rootless-containers/usernetes/blob/6bd26a7d8ca7bff70d6dc36ed768c522d29288a8/src/patches/kubernetes/0001-Not-for-Upstream-kubelet-new-cgroup-driver-none.patch) patch if we want to support cgroup v1.

The "none" cgroup driver isn't stable, so I suggest dropping support for cgroup v1 on rootless.

https://github.com/rootless-containers/usernetes/issues/235

**Comment by brandond** [comment]
I already took a pass at 1.22, most of the stuff applied cleanly but I did have to trim out some of the cgroupv2 stuff; it wasn't clear if any of what remained was still necessary.
https://github.com/brandond/kubernetes/commits/v1.22.0-beta.0-k3s1

**Comment by AkihiroSuda** [comment]
@brandond 

> kubelet: new feature gate: Rootless …
> kube-proxy: allow running in userns …
> kubelet/cm: ignore sysctl error when running in userns …

These patches are no longer needed for v1.22, but `KubeletInUserNamespace` feature gate needs to be enabled.



![image](https://user-images.githubusercontent.com/9248427/124874452-b9ff3a00-e002-11eb-8f69-89853320e372.png)

**Comment by brandond** [comment]
Thanks! I'll drop those when I update to beta.1.

**Comment by AkihiroSuda** [comment]
https://github.com/k3s-io/kubernetes/commits/v1.22.1-k3s1 seems to retain `kubelet: new cgroup driver: "none"`.

Do we still want to support cgroup driver=none in k3s 1.22?
