### ISSUE TITLE
Unable to add new master to cluster with embedded etcd

### ISSUE THREAD

**Issue by dsafont** [k3s-io/k3s#3597]
**Environmental Info:**
K3s Version: 
k3s -v
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Linux andreasp61 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
5 masters, now trying to add 2 more masters

**Describe the bug:**
When trying to add a 6th node to the cluster i'm getting the following error:

{"level":"info","ts":"2021-07-08T12:43:50.702+0200","caller":"raft/node.go:325","msg":"raft.node: d7b511c51f0b845f elected leader be23a81d48f61f6b at term 57"}
{"level":"info","ts":"2021-07-08T12:43:50.724+0200","caller":"etcdserver/server.go:716","msg":"initialized peer connections; fast-forwarding election ticks","local-member-id":"d7b511c51f0b845f","forward-ticks":8,"forward-duration":"4s","election-ticks":10,"election-timeout":"5s","active-remote-members":5}
{"level":"warn","ts":"2021-07-08T12:44:00.677+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
INFO[2021-07-08T12:44:00.677875833+02:00] Failed to test data store connection: context deadline exceeded
{"level":"warn","ts":"2021-07-08T12:44:00.678+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context canceled\". Reconnecting..."}
{"level":"warn","ts":"2021-07-08T12:44:05.674+0200","caller":"etcdserver/server.go:2068","msg":"failed to publish local member to cluster through raft","local-member-id":"d7b511c51f0b845f","local-member-attributes":"{Name:andreasp61-f0c52b9d ClientURLs:[https://10.16.182.106:2379]}","request-path":"/0/members/d7b511c51f0b845f/attributes","publish-timeout":"15s","error":"etcdserver: request timed out, possibly due to connection lost"}

{"level":"warn","ts":"2021-07-08T12:44:11.609+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context deadline exceeded\". Reconnecting..."}

{"level":"warn","ts":"2021-07-08T12:44:15.609+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
ERRO[2021-07-08T12:44:15.610140689+02:00] Failed to check local etcd status for learner management: context deadline exceeded
{"level":"warn","ts":"2021-07-08T12:44:15.610+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context canceled\". Reconnecting..."}
{"level":"warn","ts":"2021-07-08T12:44:15.678+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
INFO[2021-07-08T12:44:15.678236945+02:00] Failed to test data store connection: context deadline exceeded
{"level":"warn","ts":"2021-07-08T12:44:15.678+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context canceled\". Reconnecting..."}

**Steps To Reproduce:**

- Installed K3s 
- Add 5 master nodes
- Attempt to add a 6th node to the cluster

**Expected behavior:**
Successfully added the node to the cluster.

**Actual behavior:**
The new node is not joining the cluster correctly.

**Additional context / logs:**
The cluster is running behind a corporate proxy, but the proper env vars are being set correctl(http_proxy, https_proxy, no_proxy).

**Comment by brandond** [comment]
How many servers are you planning on adding to your cluster? Each member you add to the etcd cluster adds a fair bit of overhead; etcd does not recommend any more than 7 for event the most fault-tolerant of use cases. 5 should be more than enough for most folks.

From the logs, it looks like the new member is unable to connect to the other servers in the cluster. Have you checked the logs on the other nodes?

`{"level":"warn","ts":"2021-07-08T12:44:05.674+0200","caller":"etcdserver/server.go:2068","msg":"failed to publish local member to cluster through raft","local-member-id":"d7b511c51f0b845f","local-member-attributes":"{Name:andreasp61-f0c52b9d ClientURLs:[https://10.16.182.106:2379]}","request-path":"/0/members/d7b511c51f0b845f/attributes","publish-timeout":"15s","error":"etcdserver: request timed out, possibly due to connection lost"}`

**Comment by dsafont** [comment]
We're just trying to replace 2 if the current masters with 2 new machines. To do this, we wanted first to add the 2 new members and then remove the old ones, in order to not reduce the availability of the masters.

I've been reviewing the logs in the existing masters, and found this relevant log line:

Jul 13 08:52:28 qradafsp25 k3s[1862482]: time="2021-07-13T08:52:28.784736884+02:00" level=info msg="Cluster-Http-Server 2021/07/13 08:52:28 http: TLS handshake error from 10.16.182.106:51624: remote error: tls: bad certificate"

Seems like a problem with the certificates generated for authentication with the etcd cluster. Any clue on how to adress this?

**Comment by brandond** [comment]
That's a normal message, you will see that once each time a server or agent starts up, as it checks to see if the cluster CA is trusted by the OS CA bundle. If you're seeing it constantly then something might be wrong, but it's not an error if you see it occasionally when nodes are starting up.

Can you confirm that the required ports are open on both the old and new nodes?

**Comment by mstarostik** [comment]
I'm experiencing this as well now on v1.20.7+k3s1 (k3OS 0.20.7-k3s1r0). The same base image used to work before to join nodes, but on an attempt to rejoin a node, the logs look like in this issue. Except I'm trying to rejoin the third out of three etcds so currently running on two :-/ 
I can confirm that in this state, curl https://127.0.0.1:2379 on the joining node as well as accessing the port from externally, hangs indefinately. The ports are in listeing state by the k3s process and not blocked by anything.

Just checked with v1.21.1+k3s1 (k3OS 0.21.1-k3s1r0). That one seems to work fine.

**Comment by brandond** [comment]
@mstarostik can you post logs from both nodes?

**Comment by mstarostik** [comment]
@brandond unfortunately not; upgraded all nodes to 1.21.1+k3s1 by now and the logs are gone.
And now in this setup I can't reproduce it anymore, both versions join just fine.
From memory:

no (obvious) line suggesting a root cause
etcdctl member list shows the new node as a learner for a short while
then it gets booted off again, after existing nodes experience timeouts trying to connect to :2379 on the new node
new node stays in a loop trying to reach 127.0.0.1:2379
kubelet not started

sorry, that's as much as I can tell anymore

**Comment by roger21gm** [comment]
Same error here, also after updating to v1.21.4+k3s1.

### New node
Logs in node that I want to add as a server to the cluster:
```
ERRO[2021-09-16T12:41:33.318032754+02:00] Failed to check local etcd status for learner management: context deadline exceeded
{"level":"warn","ts":"2021-09-16T12:41:33.318+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context canceled\". Reconnecting..."}
{"level":"warn","ts":"2021-09-16T12:41:33.331+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
INFO[2021-09-16T12:41:33.331427438+02:00] Failed to test data store connection: context deadline exceeded
{"level":"warn","ts":"2021-09-16T12:41:33.331+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context canceled\". Reconnecting..."}
{"level":"warn","ts":"2021-09-16T12:41:33.979+0200","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: authentication handshake failed: context deadline exceeded\". Reconnecting..."}
{"level":"warn","ts":"2021-09-16T12:41:38.326+0200","caller":"etcdserver/server.go:2068","msg":"failed to publish local member to cluster through raft","local-member-id":"adea52081ea2c35d","local-member-attributes":"{Name:andreasp35-aba1c9b4 ClientURLs:[https://10.16.182.93:2379]}","request-path":"/0/members/adea52081ea2c35d/attributes","publish-timeout":"15s","error":"etcdserver: request timed out"}
{"level":"warn","ts":"2021-09-16T12:41:48.317+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
```

It seems etcd do not start properly in the new node. 
```
root@andreasp35:~# ETCDCTL_ENDPOINTS='https://127.0.0.1:2379' ETCDCTL_CACERT='/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/k3s/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/k3s/server/tls/etcd/server-client.key' ETCDCTL_API=2 etcdctl member list
client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://127.0.0.1:2379 exceeded header timeout

root@andreasp35:~# ETCDCTL_ENDPOINTS='https://127.0.0.1:2379' ETCDCTL_CACERT='/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/k3s/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/k3s/server/tls/etcd/server-client.key' ETCDCTL_API=3 etcdctl member list
Error:  context deadline exceeded
```

Although it is able to connect and add correctly to the ETCD cluster at first moment. But after local stops responding, it deletes from the etcd cluster.

### Current server node
Logs in current server node:
```
Sep 16 12:39:38 qradaasp09 k3s[1281082]: time="2021-09-16T12:39:38.285244113+02:00" level=info msg="Cluster-Http-Server 2021/09/16 12:39:38 http: TLS handshake error from 10.16.182.93:42184: remote error: tls: bad certificate"
```

**Comment by brandond** [comment]
@roger21gm can you attach the complete logs from the "current server node" as well as the output of `kubectl get node -o yaml` ?

**Comment by roger21gm** [comment]
Node list: [nodes.txt](https://github.com/k3s-io/k3s/files/7194105/nodes.txt)

**Comment by roger21gm** [comment]
I use this documentation to add new master to the cluster:

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

`K3S_TOKEN=SECRET k3s server --server https://<ip or hostname of server1>:6443`

**Comment by brandond** [comment]
@roger21gm it looks to me like you have 6 nodes in your cluster. One of them is not configured the same as the rest; and none of them appear to have K3S_URL or --server set. How exactly have you been adding nodes to this cluster, and why do you have so many servers? 

```
    name: qasp04
      k3s.io/node-args: '["server","--flannel-backend","none","--cluster-cidr","10.245.0.0/16","--service-cidr","10.95.0.0/16","--cluster-dns","10.95.0.10","--disable","traefik,servicelb"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed","K3S_TOKEN":"********"}'
--
    name: qasp09
      k3s.io/node-args: '["server","--flannel-backend","none","--cluster-cidr","10.245.0.0/16","--service-cidr","10.95.0.0/16","--cluster-dns","10.95.0.10","--disable","traefik,servicelb"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed"}'
--
    name: qasp25
      k3s.io/node-args: '["server","--flannel-backend","none","--cluster-cidr","10.245.0.0/16","--service-cidr","10.95.0.0/16","--cluster-dns","10.95.0.10","--disable","traefik,servicelb"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed","K3S_TOKEN":"********"}'
--
    name: qasp34
      k3s.io/node-args: '["server","--flannel-backend","none","--cluster-cidr","10.245.0.0/16","--service-cidr","10.95.0.0/16","--cluster-dns","10.95.0.10","--disable","traefik,servicelb"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed"}'
--
    name: qfsp03
      k3s.io/node-args: '["server","--server","https://10.16.3.69:6443","--token","********"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed"}'
--
    name: qfsp23
      k3s.io/node-args: '["server","--flannel-backend","none","--cluster-cidr","10.245.0.0/16","--service-cidr","10.95.0.0/16","--cluster-dns","10.95.0.10","--disable","traefik,servicelb"]'
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed","K3S_TOKEN":"********"}'
```

**Comment by roger21gm** [comment]
Hi @brandond, I try to add the server to the cluster using this command:

```
k3s server --server https://10.16.3.69:6443 --flannel-backend=none --cluster-cidr=10.245.0.0/16 --service-cidr=10.95.0.0/16 --cluster-dns=10.95.0.10 --disable traefik,servicelb
```
And that's the output I get:
[out.txt](https://github.com/k3s-io/k3s/files/7202263/out.txt)


Related to other servers, I joined to the cluster the first time using the command above, and then I ran the service using systemctl. This is the content of `/etc/systemd/system/k3s.service.env`

```
K3S_TOKEN=<TOKEN>
no_proxy=10.245.0.0/16,10.95.0.0/16, *.lc.es, gitlab.lc,registrypro.lc,registry-s1.lc,registry-s2.lc.es, kubernetes.default.svc, *.csrt.csrt, 10.16.2.0/23, 10.241.122.0/24
https_proxy="<proxy>"
http_proxy="<proxy>"
```

**Comment by brandond** [comment]
I would honestly recommend against adding any more servers at this point. Etcd recommends no more than 7 servers for the very largest of workloads, and only with appropriately sized hardware.

> https://etcd.io/docs/v3.3/faq/#what-is-maximum-cluster-size
> A 5-member etcd cluster can tolerate two member failures, which is enough in most cases. Although larger clusters provide better fault tolerance, the write performance suffers because data must be replicated across more machines

**Comment by roger21gm** [comment]
What I'm trying to do is add two servers and remove two old ones. I don't want more than 5 masters, but i dare not take out masters until I manage to add new ones.

**Comment by greggameplayer** [comment]
I got those errors because the ports 2379 and 2380 weren't opened.
