### ISSUE TITLE
k3s kube-proxy

### ISSUE THREAD

**Issue by michalip** [k3s-io/k3s#3618]
**Environmental Info:**
K3s Version: 
k3s -v
k3s version v1.21.2+k3s1 (5a67e8dc)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

Cluster Configuration:
1Server
**Describe the bug:**

I would like to play with iptables, ipvs so I need to see what kube-proxy is configured like on K3s. But I cannot even find the kube-proxy pod.
I've started the server default after installation and also like the below , but no Pod
are we not supposed to see the kube-proxy pod ? is it integrated somewhere ? Any info or pointing me to the right doc would be appreciated

`k3s server --kube-proxy-arg proxy-mode=ipvs`
`kubectl get po --all-namespaces`

NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE

kube-system   metrics-server-86cbb8457f-frpbv           1/1     Running     0          22m
kube-system   coredns-7448499f4d-v88zh                  1/1     Running     0          22m
kube-system   local-path-provisioner-5ff76fc89d-mb96r   1/1     Running     0          22m
kube-system   helm-install-traefik-crd-zwf4p            0/1     Completed   0          12m
kube-system   helm-install-traefik-vlcbg                0/1     Completed   1          12m
kube-system   svclb-traefik-sqsm6                       2/2     Running     0          12m
kube-system   traefik-97b44b794-8gj8b                   1/1     Running     0          12m

thanks

**Comment by brandond** [comment]
As described in our readme:
> The memory footprint is reduced primarily by running many components inside of a single process. This eliminates significant overhead that would otherwise be duplicated for each component.

This means that you won't find pods for any of the core Kubernetes components, such as the kube-apiserver, kube-controller-manager, or kube-proxy. You can find the kube-proxy command-line flags in the K3s logs, along with log output from the kube-proxy component itself.

**Comment by snd3r** [comment]
I also try the options for configuring the kube-proxy and stopped at the fact that I cannot change the type of scheduling.
When I set any sheduler other than RoundRobin, kube-proxy rolls back to using iptables.

```
# cat /etc/rancher/k3s/config.yaml
token: 5f230d732850f066c986be9531056de6
tls-san:
  - "test.cluster"
disable: ['traefik', 'servicelb']
kubelet-arg: ['container-runtime=remote', 'container-log-max-files=2', 'container-log-max-size=10Mi']
kube-proxy-arg: ['proxy-mode=ipvs', 'ipvs-scheduler=rr']
```

```
# ipvsadm -L
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  node-91:https rr
  -> node-91:6443                 Masq    1      5          0
  -> node-92:6443                 Masq    1      3          0
  -> node-93:6443                 Masq    1      4          0
TCP  node-91:domain rr
  -> 10.42.0.15:domain            Masq    1      0          0
TCP  node-91:9153 rr
  -> 10.42.0.15:9153              Masq    1      0          0
TCP  node-91:https rr
  -> 10.42.0.14:https             Masq    1      3          0
UDP  node-91:domain rr
  -> 10.42.0.15:domain            Masq    1      0          0
```

Scheduler changed:

```
# cat /etc/rancher/k3s/config.yaml
token: 5f230d732850f066c986be9531056de6
tls-san:
  - "test.cluster"
disable: ['traefik', 'servicelb']
kubelet-arg: ['container-runtime=remote', 'container-log-max-files=2', 'container-log-max-size=10Mi']
kube-proxy-arg: ['proxy-mode=ipvs', 'ipvs-scheduler=lc']
```

```
# ipvsadm -L
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
```
