### ISSUE TITLE
Upgrade k3s-root to 0.9.1 version

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#3625]
There is a new version of k3s-root that upgrades the binaries to newer versions. We should jump to that one

**Comment by brandond** [comment]
I'm going to open backport issues; I'd like to see the ipv6 --random-fully bug fixed on all supported branches.

**Comment by rancher-max** [comment]
Linked backport issues have been closed. This was pending rc for standard sonobuoy and regressions checks, which will be validated as part of standard patch testing so I will close this issue.
