### ISSUE TITLE
K3S unauthorized errors - failing to start

### ISSUE THREAD

**Issue by dhasek00** [k3s-io/k3s#3628]
Hi, we are running a Rancher deployment in a Dev environment. A couple of days ago the deployment went down suddenly. No one on the team is aware of any changes made. The logs indicated from the metrics-server that there were TLS handshake errors with the API.

From a couple other issues read here, we attempted to remove the coredns token and traefik secrets, then delete the pods for them allowing it to recreate themselves. At this point, 3 pods are failing to start up and continue a CrashLoopBackOff. My assumption right now is that we were coming up on 1 year since the original build out of the cluster and it possibly tried to rotate its certificates. But it's difficult to determine the cause.

Is there a way to recover from this? We've asked our DB team to restore the mysql datastore from a backup, but not sure if this is going to help us.

Here are the logs from each of the failing pods...

### metrics-server
```console
I0713 17:10:15.696812       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
Error: Unauthorized
Usage:
   [flags]

Flags:
      --alsologtostderr                                         log to standard error as well as files
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authentication-tolerate-lookup-failure                  If true, failures to look up missing authentication configuration from the cluster are not considered fatal. Note that this can result in authentication that treats all requests as anonymous.
      --authorization-always-allow-paths strings                A list of HTTP paths to skip during authorization, i.e. these are authorized without contacting the 'core' kubernetes server.
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
  -h, --help                                                    help for this command
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to
use golang's default.
      --kubeconfig string                                       The path to the kubeconfig used to connect to the Kubernetes API server and the Kubelets (defaults to in-cluster config)
      --kubelet-certificate-authority string                    Path to the CA to use to validate the Kubelet's serving certificates.
      --kubelet-insecure-tls                                    Do not verify CA of serving certificates presented by Kubelets.  For testing purposes only.
      --kubelet-port int                                        The port to use to connect to Kubelets. (default 10250)
      --kubelet-preferred-address-types strings                 The priority of node address types to use when determining which address to use to connect to a particular node (default [Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP])
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                                          If non-empty, write log files in this directory
      --log_file string                                         If non-empty, use this log file
      --logtostderr                                             log to standard error instead of files (default true)
      --metric-resolution duration                              The resolution at which metrics-server will retain metrics. (default 1m0s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization.If 0, don't serve HTTPS at all. (default 443)
      --skip_headers                                            If true, avoid header prefixes in the log messages
      --stderrthreshold severity                                logs at or above this threshold go to stderr
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS
serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are
fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
  -v, --v Level                                                 number for the log level verbosity
      --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging

panic: Unauthorized

goroutine 1 [running]:
main.main()
        /go/src/github.com/kubernetes-incubator/metrics-server/cmd/metrics-server/metrics-server.go:39 +0x13b
```

### helm-install-traefik
```console
CHART=$(sed -e "s/%{KUBERNETES_API}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/g" <<< "${CHART}")
set +v -x
+ cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
+ update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
+ '[' '' '!=' true ']'
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
+ tiller --listen=127.0.0.1:44134 --storage=secret
[main] 2021/07/13 17:12:35 Starting Tiller v2.16.10 (tls=false)
[main] 2021/07/13 17:12:35 GRPC listening on 127.0.0.1:44134
[main] 2021/07/13 17:12:35 Probes listening on :44135
[main] 2021/07/13 17:12:35 Storage driver is Secret
[main] 2021/07/13 17:12:35 Max history per release is 0
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://charts.helm.sh/stable/
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ helm_v2 ls --all '^traefik$' --output json
++ jq -r '.Releases | length'
[storage] 2021/07/13 17:12:35 listing all releases with filter
[storage/driver] 2021/07/13 17:12:35 list: failed to list: Unauthorized
Error: Unauthorized
+ EXIST=
+ '[' '' == 1 ']'
+ '[' '' == v2 ']'
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/traefik.tgz
+ '[' '!' -f /chart/traefik.tgz.base64 ']'
+ return
+ '[' install '!=' delete ']'
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install
+ '[' helm_v3 == helm_v3 ']'
++ helm_v3 ls -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
+ LINE=
++ echo
++ cut -f1 -d,
+ INSTALLED_VERSION=
++ echo
++ cut -f2 -d,
+ STATUS=
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ '[' install = delete ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ helm_v3 install traefik https://10.43.0.1:443/static/charts/traefik-1.81.0.tgz --values /config/values-01_HelmChart.yaml
Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
```

### local-path-provisioner

```console
time="2021-07-13T17:12:47Z" level=fatal msg="Error starting daemon: Cannot start Provisioner: failed to get Kubernetes server version: the server has asked for the client to provide credentials"
```

**Comment by dhasek00** [comment]
Here is a snippet of logs from the K3S service

Jul 13 17:26:38 fmvdrchk3s200.fm.intel.com k3s[18039]: W0713 17:26:38.814625   18039 handler_proxy.go:102] no RequestInfo found in the context
Jul 13 17:26:38 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:38.814718   18039 controller.go:116] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
Jul 13 17:26:38 fmvdrchk3s200.fm.intel.com k3s[18039]: , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
Jul 13 17:26:38 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:38.814731   18039 controller.go:129] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate
Limited Requeue.
Jul 13 17:26:39 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:39.201700   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 8e5e0c5b216e3df2d116627ab10eacb9830d4140b6a8c773f4e33d091208076e
Jul 13 17:26:39 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:39.202025   18039 pod_workers.go:191] Error syncing pod 5489c76b-40e7-44a4-a992-4cd01efbae7e ("helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "back-off 5m0s restarting failed container=helm pod=helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"
Jul 13 17:26:40 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:40.762046   18039 request.go:645] Throttling request took 1.048893257s, request: GET:https://127.0.0.1:6444/apis/networking.k8s.io/v1beta1?timeout=32s
Jul 13 17:26:41 fmvdrchk3s200.fm.intel.com k3s[18039]: W0713 17:26:41.612922   18039 garbagecollector.go:642] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server
is currently unable to handle the request]
Jul 13 17:26:42 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:26:42.877586768Z" level=info msg="Cluster-Http-Server 2021/07/13 17:26:42 http: TLS handshake error from
10.241.55.101:54470: EOF"
Jul 13 17:26:44 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:26:44.053281698Z" level=info msg="Cluster-Http-Server 2021/07/13 17:26:44 http: TLS handshake error from
10.241.55.102:49104: EOF"
Jul 13 17:26:48 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:48.201740   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 619386a73e4bcd38ce662c9cfcf47a4056e35f4afee40b92e56f6fd0ac473160
Jul 13 17:26:48 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:48.201979   18039 pod_workers.go:191] Error syncing pod f41ba692-1650-44a0-b977-404bbb6497d9 ("metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"), skipping: failed to "StartContainer" for "metrics-server" with CrashLoopBackOff: "back-off 5m0s restarting failed
container=metrics-server pod=metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"
Jul 13 17:26:48 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:48.202336   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 076d2df3aae576d189bec63af2ad1c4a38ca395434cd8f31e1eca912347a42fe
Jul 13 17:26:48 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:48.202514   18039 pod_workers.go:191] Error syncing pod 8821523d-0c92-402e-9a23-7884b528bce6 ("local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"), skipping: failed to "StartContainer" for "local-path-provisioner" with CrashLoopBackOff: "back-off 5m0s restarting failed container=local-path-provisioner pod=local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"
Jul 13 17:26:54 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:54.201907   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 8e5e0c5b216e3df2d116627ab10eacb9830d4140b6a8c773f4e33d091208076e
Jul 13 17:26:54 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:54.202655   18039 pod_workers.go:191] Error syncing pod 5489c76b-40e7-44a4-a992-4cd01efbae7e ("helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "back-off 5m0s restarting failed container=helm pod=helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"
Jul 13 17:26:57 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:26:57.854704167Z" level=info msg="Cluster-Http-Server 2021/07/13 17:26:57 http: TLS handshake error from
10.241.55.101:58946: EOF"
Jul 13 17:26:58 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:26:58.981540246Z" level=info msg="Cluster-Http-Server 2021/07/13 17:26:58 http: TLS handshake error from
10.241.55.102:53318: EOF"
Jul 13 17:26:59 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:26:59.201614   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 076d2df3aae576d189bec63af2ad1c4a38ca395434cd8f31e1eca912347a42fe
Jul 13 17:26:59 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:26:59.201904   18039 pod_workers.go:191] Error syncing pod 8821523d-0c92-402e-9a23-7884b528bce6 ("local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"), skipping: failed to "StartContainer" for "local-path-provisioner" with CrashLoopBackOff: "back-off 5m0s restarting failed container=local-path-provisioner pod=local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"
Jul 13 17:27:00 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:00.767337   18039 resource_quota_controller.go:408] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Jul 13 17:27:02 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:02.202022   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 619386a73e4bcd38ce662c9cfcf47a4056e35f4afee40b92e56f6fd0ac473160
Jul 13 17:27:02 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:02.202266   18039 pod_workers.go:191] Error syncing pod f41ba692-1650-44a0-b977-404bbb6497d9 ("metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"), skipping: failed to "StartContainer" for "metrics-server" with CrashLoopBackOff: "back-off 5m0s restarting failed
container=metrics-server pod=metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"
Jul 13 17:27:05 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:05.201610   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 8e5e0c5b216e3df2d116627ab10eacb9830d4140b6a8c773f4e33d091208076e
Jul 13 17:27:05 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:05.201941   18039 pod_workers.go:191] Error syncing pod 5489c76b-40e7-44a4-a992-4cd01efbae7e ("helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "back-off 5m0s restarting failed container=helm pod=helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"
Jul 13 17:27:10 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:10.203748   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 076d2df3aae576d189bec63af2ad1c4a38ca395434cd8f31e1eca912347a42fe
Jul 13 17:27:10 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:10.204053   18039 pod_workers.go:191] Error syncing pod 8821523d-0c92-402e-9a23-7884b528bce6 ("local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"), skipping: failed to "StartContainer" for "local-path-provisioner" with CrashLoopBackOff: "back-off 5m0s restarting failed container=local-path-provisioner pod=local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"
Jul 13 17:27:12 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:27:12.847457251Z" level=info msg="Cluster-Http-Server 2021/07/13 17:27:12 http: TLS handshake error from
10.241.55.101:34396: EOF"
Jul 13 17:27:13 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:13.263285   18039 request.go:645] Throttling request took 1.048813257s, request: GET:https://127.0.0.1:6444/apis/networking.k8s.io/v1beta1?timeout=32s
Jul 13 17:27:14 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:27:14.027431777Z" level=info msg="Cluster-Http-Server 2021/07/13 17:27:14 http: TLS handshake error from
10.241.55.102:57232: EOF"
Jul 13 17:27:14 fmvdrchk3s200.fm.intel.com k3s[18039]: W0713 17:27:14.114354   18039 garbagecollector.go:642] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server
is currently unable to handle the request]
Jul 13 17:27:17 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:17.201660   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 619386a73e4bcd38ce662c9cfcf47a4056e35f4afee40b92e56f6fd0ac473160
Jul 13 17:27:17 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:17.201898   18039 pod_workers.go:191] Error syncing pod f41ba692-1650-44a0-b977-404bbb6497d9 ("metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"), skipping: failed to "StartContainer" for "metrics-server" with CrashLoopBackOff: "back-off 5m0s restarting failed
container=metrics-server pod=metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"
Jul 13 17:27:20 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:20.201835   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 8e5e0c5b216e3df2d116627ab10eacb9830d4140b6a8c773f4e33d091208076e
Jul 13 17:27:20 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:20.202384   18039 pod_workers.go:191] Error syncing pod 5489c76b-40e7-44a4-a992-4cd01efbae7e ("helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "back-off 5m0s restarting failed container=helm pod=helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"
Jul 13 17:27:21 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:21.201654   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 076d2df3aae576d189bec63af2ad1c4a38ca395434cd8f31e1eca912347a42fe
Jul 13 17:27:21 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:21.201959   18039 pod_workers.go:191] Error syncing pod 8821523d-0c92-402e-9a23-7884b528bce6 ("local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"), skipping: failed to "StartContainer" for "local-path-provisioner" with CrashLoopBackOff: "back-off 5m0s restarting failed container=local-path-provisioner pod=local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"
Jul 13 17:27:27 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:27:27.844864430Z" level=info msg="Cluster-Http-Server 2021/07/13 17:27:27 http: TLS handshake error from
10.241.55.101:38780: EOF"
Jul 13 17:27:29 fmvdrchk3s200.fm.intel.com k3s[18039]: time="2021-07-13T17:27:29.024587557Z" level=info msg="Cluster-Http-Server 2021/07/13 17:27:29 http: TLS handshake error from
10.241.55.102:33128: EOF"
Jul 13 17:27:31 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:31.201635   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 619386a73e4bcd38ce662c9cfcf47a4056e35f4afee40b92e56f6fd0ac473160
Jul 13 17:27:31 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:31.201866   18039 pod_workers.go:191] Error syncing pod f41ba692-1650-44a0-b977-404bbb6497d9 ("metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"), skipping: failed to "StartContainer" for "metrics-server" with CrashLoopBackOff: "back-off 5m0s restarting failed
container=metrics-server pod=metrics-server-7b4f8b595-6wnwb_kube-system(f41ba692-1650-44a0-b977-404bbb6497d9)"
Jul 13 17:27:31 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:31.269319   18039 resource_quota_controller.go:408] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Jul 13 17:27:32 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:32.201868   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 076d2df3aae576d189bec63af2ad1c4a38ca395434cd8f31e1eca912347a42fe
Jul 13 17:27:32 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:32.202235   18039 pod_workers.go:191] Error syncing pod 8821523d-0c92-402e-9a23-7884b528bce6 ("local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"), skipping: failed to "StartContainer" for "local-path-provisioner" with CrashLoopBackOff: "back-off 5m0s restarting failed container=local-path-provisioner pod=local-path-provisioner-7ff9579c6-ghwtj_kube-system(8821523d-0c92-402e-9a23-7884b528bce6)"
Jul 13 17:27:35 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:35.201651   18039 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 8e5e0c5b216e3df2d116627ab10eacb9830d4140b6a8c773f4e33d091208076e
Jul 13 17:27:35 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:35.201982   18039 pod_workers.go:191] Error syncing pod 5489c76b-40e7-44a4-a992-4cd01efbae7e ("helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"), skipping: failed to "StartContainer" for "helm" with CrashLoopBackOff: "back-off 5m0s restarting failed container=helm pod=helm-install-traefik-tk7kv_kube-system(5489c76b-40e7-44a4-a992-4cd01efbae7e)"
Jul 13 17:27:38 fmvdrchk3s200.fm.intel.com k3s[18039]: W0713 17:27:38.814959   18039 handler_proxy.go:102] no RequestInfo found in the context
Jul 13 17:27:38 fmvdrchk3s200.fm.intel.com k3s[18039]: E0713 17:27:38.815048   18039 controller.go:116] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
Jul 13 17:27:38 fmvdrchk3s200.fm.intel.com k3s[18039]: , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
Jul 13 17:27:38 fmvdrchk3s200.fm.intel.com k3s[18039]: I0713 17:27:38.815057   18039 controller.go:129] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate
Limited Requeue.

**Comment by brandond** [comment]
Can you attach (rather than pasting inline) the complete K3s service log, from startup onwards? Providing the info requested by the new issue template (K3s version, node count, operating system, etc) would also be helpful.

**Comment by dhasek00** [comment]
> Can you attach (rather than pasting inline) the complete K3s service log, from startup onwards? Providing the info requested by the new issue template (K3s version, node count, operating system, etc) would also be helpful.

I appreciate your reply. I have another deployment running in a new database while I wait for our DB team to perform a restoration. Once that happens I can point it at the old DB and generate the logs for you.
