### ISSUE TITLE
[Release-1.21] Restoration on a fresh node fails to verify hash for node using the node password file

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#3632]
Backport fix for "Restoration on a fresh node fails to verify hash for node using the node password file" to release-1.21 branch:
* #3435

**Comment by ShylajaDevadiga** [comment]
Validated below scenarios using v1.21.2-rc2+k3s2 following the steps below on single node and multi-node setup

- Passing token using --token flag
- Without passing token

Validation Steps
1. Create a single node cluster passing token during creation
2. Deploy workload
3. Take snapshot. Optionally store it in s3 bucket
6. On a new node download k3s binary
7. Restore from snapshot passing the token used during cluster creation
8. Run the install script
9. Verify cluster is up and workloads are deployed
10. Delete the old node
