### ISSUE TITLE
K3S - Service can not start

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [k3s-io/k3s#3637]
**Environmental Info:**
K3s Version: 

```
k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4
```

Node(s) CPU architecture, OS, and Version: 

```
Linux k3s-server-a 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

Cluster Configuration:

2 servers, 2 agents with an external MySQL database for High availability.

All VMs are managed with Proxmox

**Describe the bug:**

I didn't use my cluster for a few days, now it gives me this error message for every kubectl command 
```
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```
I tried rebooting the server and restarting the services nothing change.

**Steps To Reproduce:**
I have absolutely no idea, I didn't use the cluster for a few days and it worked perfectly before.

**Expected behavior:**
I want it to handle my requests

**Actual behavior:**

```
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Additional context / logs:**

This is the only logs that I get with `journalctl -xe` : 
```
juil. 14 11:55:24 k3s-server-a k3s[344]: time="2021-07-14T11:55:24.008094451+02:00" level=info msg="Starting k3s v1.21.1+k3s1 (75dba57f)"
juil. 14 11:55:24 k3s-server-a k3s[344]: time="2021-07-14T11:55:24.011254430+02:00" level=info msg="Cluster bootstrap already complete"
```

Service status output :
```
root@k3s-server-a:~# systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Wed 2021-07-14 11:55:22 CEST; 19min ago
     Docs: https://k3s.io
  Process: 317 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 339 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 344 (k3s-server)
    Tasks: 8
   Memory: 131.8M
   CGroup: /system.slice/k3s.service
           └─344 /usr/local/bin/k3s server

juil. 14 11:55:22 k3s-server-a systemd[1]: Starting Lightweight Kubernetes...
juil. 14 11:55:24 k3s-server-a k3s[344]: time="2021-07-14T11:55:24.008094451+02:00" level=info msg="Starting k3s v1.21.1+k3s1 (75dba57f)"
juil. 14 11:55:24 k3s-server-a k3s[344]: time="2021-07-14T11:55:24.011254430+02:00" level=info msg="Cluster bootstrap already complete"
```

**Comment by brandond** [comment]
I suspect that it's hanging trying to connect to the external SQL datastore - the place it's pausing is right where it would connect to that. Can you successfully connect to the SQL datastore using the mysql CLI on this host?

**Comment by Anthony-Jhoiro** [comment]
Yes, that was the problem, the database couldn't handle requests because of the huge amount of logs on the VM. (10Go). I had to reset the database to make it work correctly.
