### ISSUE TITLE
GetArgsList function appends additional hyphens to args if it already has hyphens.

### ISSUE THREAD

**Issue by phillipsj** [k3s-io/k3s#3642]
Please assign this bug to me. Thanks.

**Environmental Info:**
K3s Version: Main branch

**Describe the bug:**

When calling GetArgsList and passing an args that already have `--` you will get back args with `----`.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

That you only return args with two hyphens.

**Comment by brandond** [comment]
This is needed so that we can use the function to merge additional args in downstream executors.

**Comment by rancher-max** [comment]
This was mostly necessary for rke2 windows. The fact that's working is confirmation of this, and also this had unit tests added to them and is small enough that we should be able to trust those and not need any additional validation from me here.
