### ISSUE TITLE
Adding support for waitgroup to the Startuphooks

### ISSUE THREAD

**Issue by phillipsj** [k3s-io/k3s#3653]
The startup hooks where executing after the deploy controller. We needed the deploy controller to wait until the startup hooks had completed. This was causing issues for the kube-proxy as a static pod.

**Comment by rancher-max** [comment]
Should be able to just do an upgrade test during release testing to validate this is OK as the change was needed mostly for rke2 and that has already been validated.

**Comment by rancher-max** [comment]
As upgrades to v1.22.2-rc1+k3s1 have been successful, pending some potential issues related to SUC directly, I am closing this out.
