### ISSUE TITLE
Massive state.db-wal file

### ISSUE THREAD

**Issue by clrxbl** [k3s-io/k3s#3660]
**Environmental Info:**
K3s Version: v1.21.1+k3s1

Node(s) CPU architecture, OS, and Version: Intel Xeon E-2288G (16 threads), Debian 10, Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

Cluster Configuration:
1 server, 6 agents

**Describe the bug:**
#1575 

**Steps To Reproduce:**
N/A

**Expected behavior:**
Small state.db-wal file

**Actual behavior:**
state.db-wal file has grown to a whopping 240GB.

**Additional context / logs:**
@brandond  mentioned collecting statistics about our state.db database.
```
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> .header on
sqlite> .mode column
sqlite> .dbinfo
database page size:  4096
write format:        2
read format:         2
reserved bytes:      0
file change counter: 54229252
database page count: 1054104
freelist page count: 1041266
schema cookie:       6
schema format:       4
default cache size:  0
autovacuum top root: 0
incremental vacuum:  0
text encoding:       1 (utf8)
user version:        0
application id:      0
software version:    3032001
number of tables:    2
number of indexes:   5
number of triggers:  0
number of views:     0
schema size:         565
data version         2
sqlite> SELECT
   ...>   COUNT(*) AS rows,
   ...>   (SELECT prev_revision FROM kine WHERE name = "compact_rev_key" LIMIT 1) AS compact_rev,
   ...>   MAX(id) AS current_rev
   ...> FROM kine;
rows        compact_rev  current_rev
----------  -----------  -----------
4646        111430156    111433200
{"mode":"full","isActive":false}
```
https://gist.github.com/clrxbl/7c5f6b15f7a1377449d56c6e2bc9c9a2

**Comment by brandond** [comment]
From your gist, it appears that 99% of the space on disk is actually free pages; given that compaction does not appear to have stalled (your compact_rev and current_rev keys are not very far apart) I'm not sure what would cause this - did you at some point in time have some very large configmaps, secrets, or other blobs-type custom resources in your Kubernetes cluster?

```
/** Disk-Space Utilization Report For state.db

Page size in bytes................................ 4096
Pages in the whole file (measured)................ 1054104
Pages in the whole file (calculated).............. 1054104
Pages that store data............................. 12837        1.2%
Pages on the freelist (per header)................ 1041266     98.8%
Pages on the freelist (calculated)................ 1041267     98.8%
Pages of auto-vacuum overhead..................... 0            0.0%
Number of tables in the database.................. 3
Number of indices................................. 5
Number of defined indices......................... 5
Number of implied indices......................... 0
Size of the file in bytes......................... 4317609984
Bytes of user payload stored...................... 47881822     1.1%
```

Either way, you should be able to stop k3s and manually vacuum the database using the steps listed in https://github.com/k3s-io/k3s/issues/1575#issuecomment-613078214

**Comment by clrxbl** [comment]
> From your gist, it appears that 99% of the space on disk is actually free pages. Given that compaction does not appear to have stalled (your compact_rev and current_rev keys are not very far apart) I'm not sure what would cause this - did you at some point in time have some very large configmaps, secrets, or other blob-type custom resources in your Kubernetes cluster?
> 
> ```
> /** Disk-Space Utilization Report For state.db
> 
> Page size in bytes................................ 4096
> Pages in the whole file (measured)................ 1054104
> Pages in the whole file (calculated).............. 1054104
> Pages that store data............................. 12837        1.2%
> Pages on the freelist (per header)................ 1041266     98.8%
> Pages on the freelist (calculated)................ 1041267     98.8%
> Pages of auto-vacuum overhead..................... 0            0.0%
> Number of tables in the database.................. 3
> Number of indices................................. 5
> Number of defined indices......................... 5
> Number of implied indices......................... 0
> Size of the file in bytes......................... 4317609984
> Bytes of user payload stored...................... 47881822     1.1%
> ```
> 
> Either way, you should be able to stop k3s and manually vacuum the database using the steps listed in [#1575 (comment)](https://github.com/k3s-io/k3s/issues/1575#issuecomment-613078214)

Nothing like that in my cluster.

**Comment by brandond** [comment]
What was the initial version of K3s that you ran on this node? How long has it been in operation?

**Comment by clrxbl** [comment]
> What was the initial version of K3s that you ran on this node? How long has it been in operation?

241 days, master last restarted 1 month ago on 1.21. I believe the version we started with is 1.19

**Comment by brandond** [comment]
Ah, interesting. We don't configure any vacuuming, but in general the database should be pretty steady-state so I'm unsure what would cause it to not reuse old blocks, other than perhaps a bug in older versions of sqlite.

**Comment by eigood** [comment]
"steady-state" operation?  What does that mean?  As in, no other k8s objects being created/destroyed?  We just ran into this as well, 3.3G state.db/383G wal file, in 10 days. Our cluster creates lots and lots of tekton pipelineruns(and their taskruns, etc), then adds additional nodes in AWS to process those.  Those *runs do not run on the base nodes.

**Comment by eigood** [comment]
I see there there has been a kine release with a fix fo this, but that it has not yet been included into any k3s release; I see at this time there are were 3 rc releases for 1.20, 1.21, and 1.22(4 days ago), but none of them actually upgraded the included kine.

What is the release process to get this fix into our hands?

**Comment by brandond** [comment]
We are past code freeze for the current release; at this point we are only adding fixes for issues kicked back for rework by QA. It will most likely make it into the December release cycle.

**Comment by eigood** [comment]
Another observation; this bug could actually explain some of the high CPU load we've been seeing; when this wal file gets *huge*, we are seeing mostly idle loads of 40 or more, with high 'sys' time as reported by top.  This is probably due to various seeks that are occurring as sqllite attempts to read scattered blocks in the file.  Over time, the load gets higher and higher, in relation to the size of the file.

**Comment by brandond** [comment]
You can test a CI build of 1.22 with `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=24defe361492c4e8e7a2bf4fad3ec4de6308e85f sh -` if you want to see how it works in your environment.

**Comment by eigood** [comment]
I'm hoping this gets backported to previous releases?  We have to keep redeploying/rebooting our master.  In the 5 days it's been up, it's created a 200G wal file, against a 3.8G, on a highly active tekton PipelineRun setup.

```
root@ip-10-0-2-144:/var/lib/rancher/k3s/server/db# ls -lh
total 213G
-rw-r--r-- 1 root root    0 Dec  2 01:33 joined-e3b0c44298fc
-rw-r--r-- 1 root root 3.8G Dec  7 20:51 state.db
-rw-r--r-- 1 root root 415M Dec  7 20:51 state.db-shm
-rw-r--r-- 1 root root 209G Dec  7 20:51 state.db-wal
```

The last deploy of the server added a CronJob that runs every 6 hours, removes *completed* PipelineRuns, and the current total pod count is 600, with a load of 26(32 cpus available).  The load has continued to increase from the initial start of the server.  I had hoped that cleaning out pods would allow for the wal state to be reused, but that seems to not be the case.

**Comment by brandond** [comment]
Have you been able to test the fix by running a CI build as described above? That would be immensely helpful.

**Comment by ShylajaDevadiga** [comment]
Would it be reasonable to ask to reopen the issue after testing the fix by running a CI build as described above. If you still see it happen, it would be helpful if you could share the kind of workload you have used.
I tried having a tekton PipelineRun setup, but the db-wal file size was of negligible size compared to what was reported above. 
Please feel free to reopen if the issue persists.
