### ISSUE TITLE
K3s/RKE2 bootstrap data is encrypted with empty string if user does not supply a token

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#3675]
**K3s and RKE2 bootstrap data (CA certs and keys, secret encryption data, etc) is written to the datastore (sql or etcd) and used by servers when bootstrapping. We are supposed to be encrypting this data at rest using the passphrase from the node token. If the user does not supply a token, we generate a random passphrase and write it to disk for use when joining additional servers or agents to the cluster - this instruction is provided to the user during startup as:

Node token is available at /var/lib/rancher/k3s/server/token
To join node to cluster: k3s agent -s https://server:6443 -t ${NODE_TOKEN}
The issue is that the we encrypt the bootstrap data using the raw token string from the CLI flag without falling back to using the random passphrase from the node token file if the flag is unset. This means that we are encrypting with an empty string if the user does not specify a token when starting the first cluster member, which is a common occurrence.

We need to:

For new clusters, ensure that the bootstrap data is encrypted with a non-empty string - either the passphrase specified by the user, or the randomly generated passphrase.
For existing clusters where the bootstrap data is encrypted with an empty string, continue to load/store using the legacy behavior.**

**Comment by fapatel1** [comment]
@cwayne18 you mentioned this is completed
