### ISSUE TITLE
Fedora VM Worker Not Joining

### ISSUE THREAD

**Issue by davesargrad** [k3s-io/k3s#3700]
In past, I've used k8s 1.20 in a bare metal cluster that i've established. I have a fair expertise with K8S. 

This is my first time using K3S. 

I am starting with a 2 VM (Fedora 33 on Virtualbox) test cluster.

I've followed the [quickstart ](https://rancher.com/docs/k3s/latest/en/quick-start/)instructions.

I am able to create a master ("wiggles") .
![image](https://user-images.githubusercontent.com/48793689/126685419-218316e0-78bb-4183-8da0-2bfb3e98a84f.png)

I run a command to have my worker node "giggles" join the cluster

The command runs without error:
![image](https://user-images.githubusercontent.com/48793689/126685582-a4a838e2-5255-46f0-a4a4-2a36c5a7b2b1.png)

I've run this command with and without K3S_NODE_NAME (each time on a pristine VM).

Yet the master doesnt see the worker.

Guidance?

P.S. I'm going to delete these machines.. and start fresh. This time I'll use the K3S_NODE_NAME on each node (rather than an IP address).

**Comment by davesargrad** [comment]
I've recreated the VM's and tried again.. same result.. 

The k3s server runs on the master:
![image](https://user-images.githubusercontent.com/48793689/126689843-6bba406e-50e4-4540-83b4-e2ac0bcea50c.png)

The k3s-agent runs on the worker:
![image](https://user-images.githubusercontent.com/48793689/126689795-83a12fa2-9a86-4907-b2b8-6344295e6c65.png)

Yet the master does not see the worker:
![image](https://user-images.githubusercontent.com/48793689/126689897-4c30ea11-4acf-4cfb-9efe-4f70a9b8bc0a.png)

**Comment by davesargrad** [comment]
I've noticed that the agent is trying to connect to 10.0.2.15.. despite the fact that I had configured the URL to be 192.168.56.113

**Comment by davesargrad** [comment]
[This ](https://github.com/k3s-io/k3s/issues/1523#issuecomment-602098986)issue suggests that the fix is to set K3S_EXTERNAL_IP.

**Comment by davesargrad** [comment]
Latest Attempt (Will tweak this until I have an answer that works):

On Master (After Clean VM Creation):
```
sudo hostnamectl set-hostname wiggles
reboot
```

On Worker (After Clean VM Creation):
```
sudo hostnamectl set-hostname giggles
reboot
```

On Master:
 - Add giggles to /etc/hosts

On Worker 
- Add wiggles to /etc/hosts

On Master:
```
sudo -i
export K3S_NODE_NAME=wiggles
export K3S_EXTERNAL_IP=192.168.56.115
export K3S_KUBECONFIG_MODE="644"

dnf install https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm
curl -sfL https://get.k3s.io | sh -

cat /var/lib/rancher/k3s/server/node-token
```

On Worker: 
```
sudo -i
export K3S_NODE_NAME=giggles
export K3S_KUBECONFIG_MODE="644"

export K3S_URL="https://192.168.56.115:6443"
export K3S_TOKEN=CHANGEME

dnf install https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm
curl -sfL https://get.k3s.io | sh -
```

**Comment by davesargrad** [comment]
This is still not working with K3S_EXTERNAL_IP exported on the master! :(

**Comment by davesargrad** [comment]
With this it looks like its still using the 10.42 interface:

![image](https://user-images.githubusercontent.com/48793689/126700142-fdc89232-66f0-4de3-b219-d8d67300f1b9.png)

**Comment by davesargrad** [comment]
Yay.. 

![image](https://user-images.githubusercontent.com/48793689/126706178-d08cf6ff-90b8-4a0e-ab39-151eee3e9bc3.png)

**Comment by drriguz** [comment]
> Yay..
> 
> ![image](https://user-images.githubusercontent.com/48793689/126706178-d08cf6ff-90b8-4a0e-ab39-151eee3e9bc3.png)
> 
> ### The Magic Sauce
> I installed two pristine Virtualbox Fedora 33 images. I set each up with two networks. ![image](https://user-images.githubusercontent.com/48793689/126711850-24052fa8-66fd-4468-b0fb-ab070dbfbbfd.png)
> 
> Then, other than setting the hostname for each, I was able to immediately install k3s as follows.
> 
> **On Master**
> 
> ```
> export K3S_NODE_NAME=wiggles
> export INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --node-external-ip 192.168.56.117 --tls-san 192.168.56.117"
> curl -sfL https://get.k3s.io | sh -s -
> 
> cat /var/lib/rancher/k3s/server/node-token
> ```
> 
> **On Worker**
> 
> ```
> export K3S_NODE_NAME=giggles
> export K3S_URL="https://192.168.56.117:6443"
> export K3S_TOKEN=CHANGEME
> curl -sfL https://get.k3s.io | sh -s -
> ```
> 
> P.S. I didnt need to update the hosts file (on either master or worker) to ensure that each VM could get to the other VM using that hostname (I use IP addresses in the magic sauce). By default in Virtualbox my VM's both had the name "fedora". I did modify their hostnames (using hostnamectl set-hostname _changeme_), prior to installing k3s
> 
> P.P.S I did need this command (prior to running curl): `dnf install https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm`
> 
> If you have not installed this RPM, the k3s install script fails and indicates that this package must be installed. The script says to use "yum". However "dnf" works. Its safest to use the URL provided by the script itself (on that first failure).
> 
> P.P.P.S I spent the better part of a day struggling with this. I am happy with the end result though. Hopefully this answer will help someone avoid spending a day scratching their head over the variety of comments found in other issues.
> 
> P.P.P.P.S I found [this](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/), [this](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/), and [this ](https://rancher.com/docs/k3s/latest/en/installation/install-options/how-to-flags/)documentation to be the most helpful.
> 
> It's actually fairly accurate and clear documentation... yay [Rancher](https://rancher.com/). The only thing it seems to lack is a number of clear, and complete, examples. For example I'd have thought that a small (at home) Virtualbox cluster would be a good example. To me what these kinds of packages often lack, are a set of examples that people can reference in a hope to find an environment close to theirs. Nowadays people just assume you are serving machines up from AWS or some other public cloud. I wish there was better documentation support for environments such as an at-home VM cluster (all on a single laptop in my case).

I got same issue when deploying k3s cluster using virtualbox/vagrant, agent could not be found after installed.

Your solution works well, and thanks for saving days of my life!

For those who are interested on my scripts to create k3s cluster, here is the repository: https://github.com/drriguz/k3s-vagrant

**Comment by TheodoreCAshmore** [comment]
Thanks for this very detailed guide @davesargrad, you've surely helped me save quite a lot of time!
I'd also like to point out that in my case I had to disable the firewall, in case someone else faces the same issue. This can easily be done with :
`systemctl disable firewalld --now`
It is also indicated in the K3s requirements page, but when you've tried so many things without success, it's easy to miss again!
