### ISSUE TITLE
Auto-deploy Manifests Should Periodically Re-evaluate

### ISSUE THREAD

**Issue by ekristen** [k3s-io/k3s#3711]
**Environmental Info:**
K3s Version: 

```
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6
```

Node(s) CPU architecture, OS, and Version: 

```
Linux ip-10-130-0-25 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 server

**Describe the bug:**

This could easily be a bug or a feature request. Technically the behavior 15 months ago was preferred from my perspective, but due to issues with HA and upgrades was altered.

As it stands today, once the server does the initial auto-deploy, it will only pick up changes IF the modtime on the file has changed. 

Previously it behaved more like gitops model where the manifests were treated as a source of truth, whatever was in manifests directory was always applied against the cluster, so if you made changes directly to the cluster that contradicted the manifest files, they'd be overwritten on the next evaluation loop.

In my opinion, the previous way was better.

From a HelmChart use case, when it deploys a service along with a deployment and said service is deleted, the service will never come back. 

The behavior of the auto-deploy is a bit inconsistent too, the first run of the deploy controller will always evaluate all manifests but subsequent runs will not unless the modtime has changed. This means that after k3s is up if someone goes and modifies the traefic or metrics-server deployment directly on the cluster it'll be 100% ok, but as soon as the deploy controller restarts for any reason, all those changes will be overwritten, which could be 1 hour from now or 30 days from now.

I suggest that the manifests directory should always be applied therefore being a reliable source of truth.

I currently have a work around for this. I place an entry in `/etc/cron.d` with a script that literally runs `touch` against every file in the `/var/lib/rancher/k3s/server/manifests` directory every minute. This forces k3s to re-evaluate on it's 15 second interval and will see the modtime changed and then apply the changes against the cluster.

**Steps To Reproduce:**
- Install K3s
- Place manifest file that creates a deployment
- Delete the deployment

**Expected behavior:**

I would expect the auto-deploy to re-evaluate and have the deployment return eventually.

**Actual behavior:**

The deployment never returns unless the modtime of the file is modified.

**Comment by brandond** [comment]
This behavior hasn't been changed - the manifests were only ever applied under two conditions:
* All manifests are applied at node startup
* Manifests are re-applied whenever their mtime and content changes.

**Comment by ekristen** [comment]
@brandond thanks for your response, ultimately I think this should be treated more as a feature request than a bug.

It would be nice to get this feature more on parity with flux and the gitops model of being a source of truth, if set, it should always ensure anything defined is in the correct state.

However I would have to disagree with your assertion that it hasn't changed.

Your first assertion is correct, it will always apply at start. As for your second assertion, it'll re-apply anytime mtime is modified (regardless of content changes) unless compareChecksums is enabled and the checksum matched. You can test this by simply running `touch manifest.yaml` file. 

However prior to 15 months ago, they were always applied unless compareChecksum was enabled and the checksum matched.

By default I never see checksum set on the Addon.Spec so I think the compareChecksums is likely not a factor.

**Comment by brandond** [comment]
Ah I see, the checksum validation behavior was broken just over a month ago, in https://github.com/k3s-io/k3s/commit/a7d1159ba6f71f36990fac2a1780fcc3f8621ab6. I'm not sure what might have changed 15 months ago - that would have probably around the 1.17 time frame? Can you clarify which release you're coming from that behaved as you're describing?

**Comment by ekristen** [comment]
I don't have a version, I've been using it a long time, just something I noticed and then I dug into the code and backtracked the changes to see the commits that changed the behavior,

15 months ago the mtime check was added.

**Comment by ekristen** [comment]
I don't have a version, I've been using it a long time, just something I noticed and then I dug into the code and backtracked the changes to see the commits that changed the behavior,

15 months ago the mtime check was added.

**Comment by rancher-max** [comment]
#### Validated on master branch commit `699ea165231cf6d665425c50ff5c75e1831f4afb`

- Deploying custom manifests that are located in `/var/lib/rancher/k3s/server/manifests` continues to work on startup. I did this by adding the following file there as `busyb.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: busyb
spec:
  selector:
    app: busy
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command:
            - sleep
            - "3600"
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
```
- I can then delete the busyb deployment in the cluster 
  - Then, if I just run `touch /var/lib/rancher/k3s/server/manifests/busyb.yaml` it does NOT redeploy since the checksum did not change
  - If I run `touch /var/lib/rancher/k3s/server/manifests/coredns.yaml` it does also not try to redeploy that
  - If I now change contents in `/var/lib/rancher/k3s/server/manifests/busyb.yaml`, for example change the `sleep 3600` to `sleep 1800`, then it successfully redeploys
- Confirmed that checksums match on both this custom manifest and default ones like coredns and traefik with commands such as the following:
```
$ kubectl get addon coredns -n kube-system -o yaml
apiVersion: k3s.cattle.io/v1
kind: Addon
metadata:
  creationTimestamp: "2021-09-14T18:37:35Z"
  generation: 2
  name: coredns
  namespace: kube-system
  resourceVersion: "308"
  uid: 3ac713db-721f-4583-8457-4f58b34948a9
spec:
  checksum: 6f91460074c0a726b39dc38be9e7ae89fbab1a2a81fb3e999f548420c54eafe1
  source: /var/lib/rancher/k3s/server/manifests/coredns.yaml
status: {}

$ sudo sha256sum /var/lib/rancher/k3s/server/manifests/coredns.yaml
6f91460074c0a726b39dc38be9e7ae89fbab1a2a81fb3e999f548420c54eafe1  /var/lib/rancher/k3s/server/manifests/coredns.yaml
```

**Comment by ekristen** [comment]
Wait just so I understand, the manifests only get applied if the file contents has changed?

The applying if the modtime has changed has been removed?

**Comment by brandond** [comment]
that's correct, that was the expected behavior that was regressed as discussed in https://github.com/k3s-io/k3s/issues/3711#issuecomment-887048741. The manifest is only intended to apply on startup or when changed.

**Comment by ekristen** [comment]
Well shoot. Removing the modtime now takes my entire workaround away. Perhaps I didn't communicate effectively.

The problem that the original issue was calling out is that the manifests weren't being re-evaluated on a periodic basis, where early versions I'm fairly confident they were, but no hard proof.

The problem was that if I added the following service, then deleted it, unless the contents changed or the modtime changed it would never get re-evaluated against the cluster, which I felt was the real issue. 

```
apiVersion: v1
kind: Service
metadata:
  name: busyb
spec:
  selector:
    app: busy
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
```

My point/suggestion was that all manifests should be re-evaluated against the cluster periodically and treat them as a source of truth like Flux for example does.

With this fix now, I have no way to ensuring that the manifests in the directly remain applied against the cluster at all times.

Having used the workaround now for several months I think the modtime regression should stay in place.

Ideally I think there should be three triggers for re-apply/re-evaluating against the cluster

1. modtime changes
2. checksum changes
3. period of time passes (ie 2min/5min, possibly configurable)
4.

**Comment by brandond** [comment]
> My point/suggestion was that all manifests should be re-evaluated against the cluster periodically and treat them as a source of truth like Flux for example does.

The manifests dir and deploy controller is intended primarily as a very minimal way to install or update components when the cluster is installed or upgraded; it is not intended to function as a GitOps style operator that constantly reconciles the manifests contents against the running system. There are other more capable tools for doing that; you could even use the manifests directory to deploy them when the cluster is created.

**Comment by ekristen** [comment]
I agree and disagree. It’s minimal and wonderful for bootstrapping a cluster because that’s how I use it mostly. 

Can we leave the modtime check in place, that allows what I need and as long as checksum is checked as well, it meets the original need goal too? Removing modtime now breaks my workaround and will break some of my stuff unfortunate. 

The manifests directory is very powerful for k3s, limiting its capabilities would be a bummer. Flux and others expect remote sources with complex auth, whereas the deploy controller is simple and elegant using local files.

**Comment by jon-nfc** [comment]
> that's correct, that was the expected behavior that was regressed as discussed in [#3711 (comment)](https://github.com/k3s-io/k3s/issues/3711#issuecomment-887048741). Manifests are only intended to apply on startup or when changed.

Why? I currently have hit the issue that OP has raised and as a consequence the addon contrary to the addons and events system within kubernetes did not apply and apprarently never will unless the file changes or k3s is restarted. periodic checking would confirm the manifest applied and keep the addons in a known state. There is no point having a system in place to shoot and forget.

I agree with what OP has stated, re-evaluation of the manifiests needs to occur and not just when the file changes/startup. In my case the object that should have been created when the manifest was initially applied and subsequently failed, contrary to the success messages; would have been applied again during a re-evaluation.


> > My point/suggestion was that all manifests should be re-evaluated against the cluster periodically and treat them as a source of truth like Flux for example does.

Agreed. this issue should be re-opened and have this feature applied/re-applied


> > My point/suggestion was that all manifests should be re-evaluated against the cluster periodically and treat them as a source of truth like Flux for example does.
> The manifests dir and deploy controller is intended primarily as a very minimal way to install or update components when the cluster is installed or upgraded; it is not intended to function as a GitOps style operator that constantly reconciles the manifests contents against the running system. There are other more capable tools for doing that; you could even use the manifests directory to deploy them when the cluster is created.


_"The manifests dir and deploy controller is intended primarily as a very minimal way to install or update components when the cluster is installed or upgraded"_ so boot strapping! if no re-evaluation is done, then this point will fail to be met

_"it is not intended to function as a GitOps style operator that constantly reconciles the manifests contents against the running system. There are other more capable tools for doing that;"_

This is beside the point. the addon system as elaborated upon multiple times, is a simple system to install/update items within kubernetes. without polling and confirming that what is present (the kubernetes object) against what is supposed to be present (the manifest file) it's a broken system. OP's point that this is either a bug/feature request is clearly valid here.
whilst there may be more capable systems for "git ops" style single source of truth, the manifests folder with this issues intent would already meet that. Leaning users who are having issues with this system to use "ANOTHER" tool is not a solution. Again I'm with OP here this is either a bug/feature request.


> The manifests directory is very powerful for k3s, limiting its capabilities would be a bummer. Flux and others expect remote sources with complex auth, whereas the deploy controller is simple and elegant using local files.

Agreed. I use ansible to deploy everything. Now whilst I could create playbooks to ensure a single source of truth and then constantly run plays against the cluster just to ensure consistency is an option, it makes no sense when there is already a system in place to ensure that the manifests apply, or should apply.



<details><summary>Relevant kubernetes output show another reason polling/re-evaluation is required </summary>

## Explaination

This deployment was on a single node K3s cluster and was a clean install.

As there was no polling/re-evaluation of the manifests, I now have an addon that has claimed to sucessfully deployed, when in fact it doesn't exist.

The flow of what occured:

1. deployed new manifests, namely kyverno (kubernetes policy controller)
1. the cluster policy manifest deployed before kyveron manifest 
1. as the policy manifest required CRDs from kyverno, failing to apply was expected.
1. events system reports failure of applying policy manifest
1. event system reports success of deploying policy manifest (A minute before the kyverno manifest was deployed, which included the CRDs for it to be added to kubernetes)
1. kyverno deployed
1. manual confirmation if the policy existed? no it doesn't.


This is one of those scenarios that have occured as the simple system of applying manifests during install failed which would not have been an issue is polling/re-evaluation had occured.


``` bash
root@oracle-arm-free:/home/sysadmin# kubectl get clusterpolicy
No resources found
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# date
Wed Nov 22 11:43:47 UTC 2023
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# kubectl get events -n kube-system --watch
LAST SEEN   TYPE      REASON                OBJECT                                             MESSAGE
59m         Normal    ApplyingManifest      addon/clusterpolicy-manifest-configmap-update      Applying manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml"
60m         Warning   ApplyManifestFailed   addon/clusterpolicy-manifest-configmap-update      Applying manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml" failed: the server could not find the requested resource
59m         Normal    AppliedManifest       addon/clusterpolicy-manifest-configmap-update      Applied manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml"
60m         Normal    ApplyingManifest      addon/helmchart-manifest-kyverno-policy-reporter   Applying manifest at "/var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno-policy-reporter.yaml"
60m         Normal    AppliedManifest       addon/helmchart-manifest-kyverno-policy-reporter   Applied manifest at "/var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno-policy-reporter.yaml"
60m         Normal    ApplyingManifest      addon/helmchart-manifest-kyverno                   Applying manifest at "/var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno.yaml"
60m         Normal    AppliedManifest       addon/helmchart-manifest-kyverno                   Applied manifest at "/var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno.yaml"
^Croot@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# kubectl get addons -n kube-system -o wide
NAME                                         SOURCE                                                                                  CHECKSUM
...truncated......


clusterpolicy-manifest-configmap-update      /var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml      a67d5e52fc4f500f3c0436534224db85ca7236bb454ecca4d098d27ac138ca88


...truncated......

helmchart-manifest-kubernetes-monitoring     /var/lib/rancher/k3s/server/manifests/helmchart-manifest-kubernetes-monitoring.yaml     4a2f54f754d47bf8e0d8408d1d18f87af8a62b6db3080916e9ae55b37b265844
helmchart-manifest-kyverno                   /var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno.yaml                   a4d00378b10a4d9b7d9c3f9e44258575fe0800709bd4ac09fa01aeb55b6c8c41
helmchart-manifest-kyverno-policies          /var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno-policies.yaml          905315855d8b5dd14e0217833e69da676d00f51774ce70e7a5b2b9532a233979
helmchart-manifest-kyverno-policy-reporter   /var/lib/rancher/k3s/server/manifests/helmchart-manifest-kyverno-policy-reporter.yaml   58b84c2e6044792a0b4bdfa8baa7f4608939405a06ff54d9a2b419ec217f11cd

...truncated......

root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# kubectl describe addon -n kube-system clusterpolicy-manifest-configmap-update
Name:         clusterpolicy-manifest-configmap-update
Namespace:    kube-system
Labels:       <none>
Annotations:  addon.k3s.cattle.io/gvks: kyverno.io/v1, Kind=ClusterPolicy
API Version:  k3s.cattle.io/v1
Kind:         Addon
Metadata:
  Creation Timestamp:  2023-11-22T10:42:37Z
  Generation:          2
  Managed Fields:
    API Version:  k3s.cattle.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:addon.k3s.cattle.io/gvks:
      f:spec:
        .:
        f:checksum:
        f:source:
    Manager:         deploy@oracle-arm-free
    Operation:       Update
    Time:            2023-11-22T10:44:08Z
  Resource Version:  394263
  UID:               7dcb94c0-3952-48c7-98ae-a07696e2a1a6
Spec:
  Checksum:  a67d5e52fc4f500f3c0436534224db85ca7236bb454ecca4d098d27ac138ca88
  Source:    /var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml
Events:
  Type     Reason               Age                From    Message
  ----     ------               ----               ----    -------
  Warning  ApplyManifestFailed  60m (x6 over 61m)  deploy  Applying manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml" failed: the server could not find the requested resource
  Normal   ApplyingManifest     60m (x7 over 61m)  deploy  Applying manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml"
  Normal   AppliedManifest      60m                deploy  Applied manifest at "/var/lib/rancher/k3s/server/manifests/clusterpolicy-manifest-configmap-update.yaml"
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# date
Wed Nov 22 11:44:18 UTC 2023
root@oracle-arm-free:/home/sysadmin# 
root@oracle-arm-free:/home/sysadmin# kubectl get clusterpolicy
No resources found
root@oracle-arm-free:/home/sysadmin# 

```

</details>
