### ISSUE TITLE
[Backport 1.21] Cannot write data to local PVC

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#3720]
Backport https://github.com/k3s-io/k3s/issues/3704 to 1.21

**Comment by rancher-max** [comment]
Confirmed the same steps mentioned in https://github.com/k3s-io/k3s/issues/3704#issuecomment-893784575 are working on release-1.21 branch commit `69047a35c0a2c3f1b8914e1917332c42c2d332e2`
