### ISSUE TITLE
token CA hash does not match the Cluster CA certificate

### ISSUE THREAD

**Issue by 1ntouchble** [k3s-io/k3s#3727]
server logs:

Jul 29 06:42:17 localhost.localdomain k3s[10654]: time="2021-07-29T06:42:17.081458904-04:00" level=info msg="Cluster-Http-Server 2021/07/29 06:42:17 http: TLS handshake error from 192.168.1.188:44072: remote error: tls: bad certificate"
Jul 29 06:42:19 localhost.localdomain k3s[10654]: time="2021-07-29T06:42:19.084450414-04:00" level=info msg="Cluster-Http-Server 2021/07/29 06:42:19 http: TLS handshake error from 192.168.1.188:44080: remote error: tls: bad certificate"
Jul 29 06:42:21 localhost.localdomain k3s[10654]: time="2021-07-29T06:42:21.087358624-04:00" level=info msg="Cluster-Http-Server 2021/07/29 06:42:21 http: TLS handshake error from 192.168.1.188:44088: remote error: tls: bad certificate"

agent logs:
Jul 29 06:42:37 localhost.localdomain k3s[5015]: time="2021-07-29T06:42:37.109627641-04:00" level=error msg="token CA hash does not match the Cluster CA certificate hash: f08676bf4f7418e46f692f21543118417d2698b7f758027b352dd87cfd6de3ab != 8e7d49c6991960d1a116415d9506f0a15ea3e278538c173b1d9965b62727267d"
Jul 29 06:42:39 localhost.localdomain k3s[5015]: time="2021-07-29T06:42:39.112147270-04:00" level=error msg="token CA hash does not match the Cluster CA certificate hash: f08676bf4f7418e46f692f21543118417d2698b7f758027b352dd87cfd6de3ab != 8e7d49c6991960d1a116415d9506f0a15ea3e278538c173b1d9965b62727267d"
Jul 29 06:42:41 localhost.localdomain k3s[5015]: time="2021-07-29T06:42:41.115356069-04:00" level=error msg="token CA hash does not match the Cluster CA certificate hash: f08676bf4f7418e46f692f21543118417d2698b7f758027b352dd87cfd6de3ab != 8e7d49c6991960d1a116415d9506f0a15ea3e278538c173b1d9965b62727267d"

please help me ,thx

**Comment by xiaods** [comment]
@1ntouchble  please double-check the server token, it should be equal with the bootstrap server.

**Comment by brandond** [comment]
Yeah, it looks like you're trying to join using a token from a different cluster?

**Comment by 1ntouchble** [comment]
thx,I write a wrong token
