### ISSUE TITLE
First snapshot created as part of scheduled snapshot creation does not always follow the naming convention

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3736]
**Environmental Info:**
K3s Version:
k3s version v1.21.3+k3s1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04, amd64

Cluster Configuration:
Single node cluster

**Describe the bug:**
When snapshot creation is scheduled during the creation of the cluster, first snapshot does not have naming format that is followed in the consecutive snapshot names

**Steps To Reproduce:**
Create a cluster with scheduled snapshot creation, example **etcd-snapshot--1627633080**
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.3+k3s1  sh -s - server --cluster-init --etcd-snapshot-schedule-cron='* * * * *'
```
```
k3s -v
k3s version v1.21.3+k3s1 (1d1f220f)

ubuntu@ip-172-31-21-33:~$ sudo k3s etcd-snapshot ls
etcd-snapshot--1627633080                file:///var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot--1627633080                36896   2021-07-30T08:18:00Z
etcd-snapshot-ip-172-31-21-33-1627633800 file:///var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-ip-172-31-21-33-1627633800 3334176 2021-07-30T08:30:00Z
etcd-snapshot-ip-172-31-21-33-1627633860 file:///var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-ip-172-31-21-33-1627633860 3334176 2021-07-30T08:31:00Z
etcd
```

**Expected behavior:**
All snapshot name should have same prefix

**Actual behavior:**
First snapshot name does not contain node ip address

**Comment by brandond** [comment]
NODE_NAME hasn't been set by the agent yet; we should probably retry until it is.

**Comment by algebra2k** [comment]
When executing a snapshot, if the `NODE_NAME` environment variable does not exist, should we get it again and set it?

**Comment by Oats87** [comment]
> When executing a snapshot, if the `NODE_NAME` environment variable does not exist, should we get it again and set it?

It likely makes more sense to simply hold off on taking recurring etcd snapshots until the `NODE_NAME` has been set.

**Comment by katran001** [comment]
Moving this to the next milestone since the QA team didn't have a chance to work on it for v1.22.6+k3s1
