### ISSUE TITLE
install.sh: commit 5ad76043acbf reintroduced the previously purged dependency towards awk

### ISSUE THREAD

**Issue by joakimr-axis** [k3s-io/k3s#3737]
**Environmental Info:**
K3s Version: 

Current HEAD (b1b5f72dc350d369d50a378aef54be9b3afb9769)

**Describe the bug:**

If `install.sh` relies on `awk`, `install.sh` (or, in this case rather the killall-script created by `install.sh`) malfunctions when run on a device with a limited environment where `awk` is not available. (Yes, such systems exist and yes, I install and run K3s on such systems.)

Previously, `install.sh` got `awk`  dependencies replaced, but commit 5ad76043acbf re-introduced the `awk` dependency in `do_unmount()`so that the `awk`-less systems will now fail trying to run that function.

**Steps To Reproduce:**

Run `do_unmount()` on a system that does not have `awk`.

**Expected behavior:**

`do_unmount()` should work on systems that do not have `awk`.

**Actual behavior:**

Failure since `awk` does not exist.

**Comment by brandond** [comment]
Reopened for QA

**Comment by briandowns** [comment]
Validated on master.
