### ISSUE TITLE
K3s cpu using is consistently running at 20%-100% on the master node on Raspberry Pi4 8Gb

### ISSUE THREAD

**Issue by oreillymj** [k3s-io/k3s#3743]
**Environmental Info:**
K3s Version: 
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
Linux raspi-k3-controller 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

Cluster Configuration:
1 server, 1 agent

**Describe the bug:**
I noticed that the temperature on my server node was consistently running hotter than the agent node.
Looking at top on the server

```
top - 17:56:12 up  2:48,  2 users,  load average: 1.02, 0.97, 1.00
Tasks: 170 total,   1 running, 169 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.9 us, 37.3 sy,  0.0 ni, 58.6 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :   7875.3 total,   6607.3 free,    614.2 used,    653.8 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   7019.5 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  925 root      20   0  912768 464404  85500 S 105.6   5.8  92:45.37 k3s-server
  987 root      20   0  935916 112196  74084 S   1.0   1.4   3:55.17 containerd
 5571 root      20   0  830828  35432  27936 S   0.7   0.4   1:02.24 coredns
 6772 pi        20   0    6260   2788   2344 R   0.7   0.0   0:00.24 top
   12 root      20   0       0      0      0 I   0.3   0.0   0:11.07 rcu_sched
  581 root      20   0  970232  65660  32748 S   0.3   0.8   0:32.52 dockerd
 3898 65532     20   0  864396  54812  41296 S   0.3   0.7   0:44.78 traefik
 4771 root      20   0  826180  23236  17764 S   0.3   0.3   0:27.09 local-path-prov
 4954 root      20   0       0      0      0 I   0.3   0.0   0:00.07 kworker/u8:2-flush-179:0
 5171 root      20   0       0      0      0 I   0.3   0.0   0:00.05 kworker/2:3-events
    1 root      20   0   34064   8300   6368 S   0.0   0.1   0:07.81 systemd
```

On the agent

```
top - 17:57:23 up 1 day,  1:42,  1 user,  load average: 0.00, 0.00, 0.00
Tasks: 125 total,   1 running, 124 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3827.3 total,   2970.0 free,    116.0 used,    741.3 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   3381.6 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
32569 pi        20   0   10320   2904   2472 R   1.7   0.1   0:00.20 top
 1217 root      20   0  803688   9820   7204 S   0.3   0.3   0:32.61 containerd-shim
    1 root      20   0   34876   8308   6476 S   0.0   0.2  24:39.03 systemd
    2 root      20   0       0      0      0 S   0.0   0.0   0:00.16 kthreadd

```

**Steps To Reproduce:**

- Installed K3s: 
- curl -sfL https://get.k3s.io | sh -
- After troubleshooting the fact that the k3s.service had failed, I discovered that I had to add the following to /boot/cmdline.txt
- $ cat /boot/cmdline.txt
**console=cgroup_memory=1 cgroup_enable=memory** serial0,115200

**Expected behavior:**
I would expect CPU to be below 20% at all times.

**Actual behavior:**

**Additional context / logs:**

I do have some pods running on the master, but these workloads are trivial, busybox, nginx (with no active requests)
The setup is just used for learning, labs etc and not for any "production" workloads.
As such, the system is booting and running off of a microSD card.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
There are a couple threads about this:
* https://github.com/k3s-io/k3s/issues/2375#issuecomment-888019420
* https://github.com/k3s-io/k3s/issues/2278#issuecomment-771104128

**Comment by brandond** [comment]
I also notice that you're running a 32bit OS despite having a pi4. You're probably best off using a 64bit OS on nodes with 4GB or more of memory.

**Comment by agustinvinao** [comment]
I'm facing the same issue. I have a cluster of 6 nodes, Pi4 8GB. 

```
top - 01:18:35 up 18 days, 11:19,  3 users,  load average: 10.98, 17.63, 16.82
Tasks: 216 total,   4 running, 212 sleeping,   0 stopped,   0 zombie
%Cpu(s): 24.8 us, 39.9 sy,  0.0 ni, 11.3 id,  0.0 wa,  0.0 hi, 23.9 si,  0.0 st
MiB Mem :   7814.6 total,    977.9 free,   2039.5 used,   4797.2 buff/cache
MiB Swap:   1024.0 total,   1023.0 free,      1.0 used.   5708.9 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
26098 root      20   0 1658012 835496  97320 S  87.2  10.4  10:44.95 k3s-server
    9 root      20   0       0      0      0 S  58.0   0.0   7565:51 ksoftirqd/0
15561 root      20   0   11344   9452   1624 R  14.1   0.1   0:00.43 iptables
15562 root      20   0   10640   8640   1812 R  11.5   0.1   0:00.35 iptables-restor
 1772 root      20   0  742112  71968  28556 S   7.9   0.9   5:41.66 longhorn-manage
 3518 nobody    20   0 1509916 651872  52912 S   4.3   8.1   0:29.93 prometheus
10254 root      20   0 1533024  22952  12888 S   4.3   0.3   0:04.67 longhorn
31773 root      20   0 1459292  23644  13464 S   3.9   0.3   0:26.38 longhorn
   20 root      20   0       0      0      0 S   1.6   0.0 142:20.14 ksoftirqd/2
   25 root      20   0       0      0      0 S   1.6   0.0 140:36.39 ksoftirqd/3
   15 root      20   0       0      0      0 S   1.3   0.0 139:39.09 ksoftirqd/1
30429 root      20   0 1238096  18180  12632 S   1.3   0.2   0:01.81 longhorn
 4563 root      20   0  130216  33400  17336 S   1.0   0.4 388:32.70 speaker
26249 root      20   0  856928 147816  87068 S   1.0   1.8   0:29.17 containerd
30973 root      20   0 1459292  18440  12888 S   1.0   0.2   0:04.36 longhorn
31760 root      20   0 1459292  19712  13400 S   1.0   0.2   0:10.73 longhorn
 2803 root      20   0  111996  11552   6832 S   0.7   0.1 121:37.15 containerd-shim
 5999 999       20   0  894448  43088  22268 S   0.7   0.5 177:07.82 node
```

```
root@borges:/home/uqbar# uname -a
Linux borges 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux

```
It has picks of CPU 100%, this cluster was using 1.19 perfectly. After certs expired I was forced to update to 1.21.

**Comment by teq0** [comment]
FWIW I've been running K8s of one flavour or another on my RPi 3 cluster for several years. I moved to K3s maybe a year ago, and it's all been good, but I recently upgraded to the latest version (v1.21.3+k3s1) and it's not healthy. In my case CPU is high, but it's actually consuming crazy amounts of memory, like 70+% just for k3s-server.

I've done a couple of completely clean installs, definitely in 64-bit mode:

k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6
Linux k8s-pi-m01 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux

It works long enough to add a few nodes, but as soon as I deploy an actual application, in this case ArgoCD, then before the app is even fully running the API starts having SSL handshake timeouts and everything stops. Rebooting the master gives you a short window where ssh and kubectl are responsive but within a few minutes the master just times out for everything. There seems to be many more containerd and k3s-server instance in htop than there are actual containers running. You can sit there and watch more and more k3s-server processes starting up.

I've trolled through journalctl but can't see any obvious root cause, it just seems to go along for a while and then the API calls start timing out.

Deleted everything and reinstalled using v1.19.13+k3s1 and it's working normally again. So far.

**Comment by brandond** [comment]
Please take a look at the links I posted above, particularly the first one.
