### ISSUE TITLE
snapshot creation without sudo should return a permission denied error message

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#3745]
Environmental Info:
K3s Version:
k3s version v1.21.3+k3s1

Node(s) CPU architecture, OS, and Version:
Ubuntu 20.04, amd64

Cluster Configuration:
Single node cluster

Describe the bug:
When we run a etcd-snapshot subcommand without sudo it returns no error message

Steps To Reproduce:

1. Create a cluster with etcd backend
2. Run **k3s etcd-snapshot ls** without passing sudo 

**Expected behavior:**
Command should return a error message  to pass sudo or permission denied message

**Actual behavior:**
Returns nothing

**Backporting**
- [X] Needs backporting to older releases

**Comment by rancher-max** [comment]
#### Validated this is working using master branch commit `8b857eef9c15ed97180079c0dcf5cf0f8cb888de`


```
# Passing data-dir with sudo
$ sudo k3s etcd-snapshot ls --data-dir=/var/lib/rancher/k3s
on-demand-ip-172-31-16-110-1631039576 file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-16-110-1631039576 2637856 2021-09-07T18:32:56Z

# Passing data-dir without sudo
$ k3s etcd-snapshot ls --data-dir=/var/lib/rancher/k3s
FATA[0000] failed to get the snapshot dir: stat /var/lib/rancher/k3s/server/db/snapshots: permission denied 

# Not passing data-dir without sudo
$ k3s etcd-snapshot ls
FATA[0000] failed to get the snapshot dir: stat /home/ubuntu/.rancher/k3s/server/db/snapshots: no such file or directory 

# Not passing data-dir with sudo
$ sudo k3s etcd-snapshot ls
on-demand-ip-172-31-16-110-1631039576 file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-16-110-1631039576 2637856 2021-09-07T18:32:56Z
```
