### ISSUE TITLE
can bind a specific ip for servicelb?

### ISSUE THREAD

**Issue by Eronana** [k3s-io/k3s#3747]
**Is your feature request related to a problem? Please describe.**

There are two network adaptors in my k3s master node, so I have two ip address 10.0.0.1 and 10.0.0.2.
I want to use 10.0.0.1:22 for access the master node, and 10.0.0.2:22 for another ssh service like git.
So I create a LoadBalancer service with port 22 for the git deployment, then all traffic be routed to the git pod, I can't even use 10.0.0.1:22 to access my master node.

**Describe the solution you'd like**

I read the relevant code and I think it is easy to implement:
- step 1. we can just add a env that named `SRC_IP` here. (but need to thinking about which ip should be given, maybe k3s.io/internal-ip is ok)
https://github.com/k3s-io/k3s/blob/02a5bee62f5d7a0811a6a9401fc9ff5b1399c0bc/pkg/servicelb/controller.go#L354-L371
- step 2. add `-d ${SRC_IP}` in this line
https://github.com/k3s-io/klipper-lb/blob/master/entry#L12

**Additional context**

We can discuss this feature, and if there are no too many changes from the implement way, I can submit a PR for it.

**Comment by brandond** [comment]
You might look at using something like MetalLB or kube-vip for this purpose. servicelb is intentionally simplistic and doesn't allow much by way of configuration.

**Comment by Eronana** [comment]
> You might look at using something like MetalLB or kube-vip for this purpose. servicelb is intentionally simplistic and doesn't allow much by way of configuration.

I got it, thanks.
