### ISSUE TITLE
Use new image name if the image is mirrored from the upstream 

### ISSUE THREAD

**Issue by jiaqiluo** [k3s-io/k3s#3750]
Maintenance.
The new naming schema for the image that is mirrored/cloned from the upstream is to append the prefix `mirrored-` to its name. 
We need to update k3s to use the new image name if the image is mirrored from the upstream.

**Comment by briandowns** [comment]
Validated on master by checking the files that contain the image name references and comparing the images in use to the list of mirrored images in the Rancher Dockerhub org.
