### ISSUE TITLE
More visible documentation regarding kernel modules for rootless K3s (br_netfilter, etc.)

### ISSUE THREAD

**Issue by joanbm** [k3s-io/k3s#3751]
As mentioned in https://github.com/k3s-io/k3s/issues/24#issuecomment-461989680, the br_netfilter kernel module needs to be loaded for container networking / DNS to work (e.g. `nslookup google.com`). As far as I can see this is done automatically during startup if possible.

However, for Rootless K3s, obviously the kernel module can't be automatically loaded. A warning is printed to the journal:

```
Aug 03 19:46:36 solpc k3s[1188385]: time="2021-08-03T19:46:36.088451303+02:00" level=warning msg="Failed to load kernel module br_netfilter with modprobe"
```

It seems sensible to add an explicit note regarding br_netfilter (or any other modules or configurations that need to be done as root) to the rootless K3s documentation (https://rancher.com/docs/k3s/latest/en/advanced/#running-k3s-with-rootless-mode-experimental) to get a fully working Rootless K3s install out-of-the-box.

**Comment by joanbm** [comment]
unstale

**Comment by shashankram** [comment]
unstale
