### ISSUE TITLE
Imported images are not associated with k3s lease

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3752]
https://github.com/k3s-io/k3s/pull/3464 dropped the WithLease context wrapping. The change properly creates and deletes leases, but since it dropped the `client.WithLease` call that wrapped the context, the lease is never associated with operations done using that context (such as importing images).

**Comment by rancher-max** [comment]
I saw this working on master commit `90960ebf4e7a08df075526f411e3afe06731b01e` using boltbrowser but am going to close this in favor of https://github.com/k3s-io/k3s/issues/3193 to address in an airgap scenario as well.
