### ISSUE TITLE
Update helm v3 version in klipper-helm image

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3753]
There is a vulnerability in helm versions before 3.6.1. I'm not sure if we're strictly affected since helm-controller does not support authenticating to chart repos, but we should update the helm v3 version in klipper-helm and pull this through into our next round of releases.
* https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf
* k3s-io/klipper-helm#30

**Comment by briandowns** [comment]
Validated on master by checking `pkg/helm/controller.go`.
