### ISSUE TITLE
Argo CI RBAC tests fail after upgrading from v1.18.17+k3s1 to v1.21.2+k3s1

### ISSUE THREAD

**Issue by alexec** [k3s-io/k3s#3756]
**Environmental Info:**
K3s Version: 

v1.21.2+k3s1

Node(s) CPU architecture, OS, and Version: 

Ubuntu 20 (Github action default)

https://github.com/argoproj/argo-workflows/pull/6486

Cluster Configuration:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.2+k3s1 INSTALL_K3S_CHANNEL=stable INSTALL_K3S_EXEC=--docker K3S_KUBECONFIG_MODE=644 sh -
```
        

**Describe the bug:**

I have a series of tests that ensure that RBAC is working. This should pass because the server returns "403 Forbidden", but now they fail with "200 OK". This indicates that Kubernetes RBAC is either broken or disabled. 

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
What requests exactly are you seeing fail with 200 OK? Can you provide specific steps to reproduce?

**Comment by alexec** [comment]
The step is to run the Github actions. Underneath it is just using client-go, which I'm guessing is the same as `kubectl`, so I expect you can hack the kubeconfig to invalidate or remove the token.

**Comment by brandond** [comment]
Which github actions are you referring to?

**Comment by brandond** [comment]
We don't customize any of the RBAC stuff, so I suspect you're running into a change to upstream Kubernetes. Can you validate that you get the responses you expect on a 1.21 release of another Kubernetes distribution?

**Comment by alexec** [comment]
OK. I did wonder if we need to enable RBAC, like you do for Docker for Desktop?

**Comment by brandond** [comment]
No, rbac is on by default, same as it has always been. What specifically is your test doing? Deleting a service account token, and then checking to see that the request fails? If so you're probably seeing fallout from [Bound Service Account Token Volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) support. Pods now get an ephemeral token that is rotated hourly and destroyed when the pod terminates; they don't use the service account token itself so deleting it has no impact.

**Comment by brandond** [comment]
Updated the subject to make it clear that RBAC itself isn't broken, your tests just rely on some behavior that has changed upstream.

**Comment by alexec** [comment]
Some context: Our server accepts a token from the user in the authorization header. That token is to client-go as a Kubernetes bearer token when we creating a new client. The test creates an invalid token and attempts to use it, expecting the usage to fail with an unauthorised or forbidden error. Instead the we appear to be allow to use it.

This is change in behaviour, and if it is core to Kubernetes, then we have a security issue which I would assume lies with Argo rather than Kubernetes or K3S. Which would mean our security model is broken in v1.21. I'm going to test in v1.19 and v1.20 to see what happens.

**Comment by brandond** [comment]
What is generating the token, and what is validating it? It sounds like both the generation and the validation occur in Argo, not Kubernetes?

**Comment by brandond** [comment]
@alexec can you provide any more information on what ended up being the issue?
