### ISSUE TITLE
k3s can't work well with coredns / kubedns , built by official website script

### ISSUE THREAD

**Issue by 510mt** [k3s-io/k3s#3767]
**Environmental Info:**
K3s Version: 

k3s version v1.20.7+k3s1 
go version go1.15.12

Node(s) CPU architecture, OS, and Version: 

centos 7 
ubuntu 18/20

Cluster Configuration:

single server / 1 server 1 agent

**Describe the bug:**

after i installed k3s by the offical website script 
`curl -sfL https://get.k3s.io | sh -` 
i found that coredns is installed and ran well too ,
`root@mt510:/home/mt510# kubectl get pods -n kube-system -o wide|grep coredns

coredns-854c77959c-n5mpf                  1/1     Running     16         69d   10.42.0.152   mt510   <none>           <none>
`
but actually , after i deployed a service like nginx,  i can't access it by using curl (or nslookup / dig) nginx.nginx.svc.cluster.local ,
same to whatever pod i used, but i can nslookup / dig kubernetes.default.svc.cluster.local !!!
so i assume that coredns work well but some settings is wrong , maybe k3s or kubelet ? 

**Steps To Reproduce:**

- Installed K3s: 
curl -sfL https://get.k3s.io | sh -

**Expected behavior:**

create a nginx deployment and svc in nginx namespace, create annoter pod which with a curl / nslookup /dig util ,
and use the pod with the network utils to request the nginx by access nginx-xxxx.nginx.svc.cluster.local

**Actual behavior:**

it can't access the svc by request by the url nginx-xxxx.nginx.svc.cluster.local

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
You are not expected to be able to resolve cluster addresses from outside containers running in the cluster. You'd normally expose things via LoadBalancer services, externaldns, etc.
