### ISSUE TITLE
k3s can't work well with coredns inside the cluster containers

### ISSUE THREAD

**Issue by 510mt** [k3s-io/k3s#3769]
You are not expected to be able to resolve cluster addresses from outside containers running in the cluster. You'd normally expose things via LoadBalancer services, externaldns, etc.

_Originally posted by @brandond in https://github.com/k3s-io/k3s/issues/3767#issuecomment-893151089_

**Comment by 510mt** [comment]
Hello ,thanks for response me quickly, actually i access the nginx-xxxx.nginx.svc.cluster.local by the cluster container, but not outside (node host). In many scene , cluster container in the difference namespace access each other by internal domain.
Such as we need to access services by the internal domain like this zk-0.zookeeper.svc.cluster.local in the cluster container @brandond

**Comment by brandond** [comment]
Please follow up in the discussion.
