### ISSUE TITLE
NodePort not accepting traffic from forwarded nginx traffic

### ISSUE THREAD

**Issue by sr229** [k3s-io/k3s#377]
**Describe the bug**
We rely on K3s for a tightly-secured way to handle our services. However, since we rely on a shared node, we have to use `NodePort` for the service and the preinstalled nginx, when forwarding traffic from nginx to the NodePort, the NodePort seems to drop the traffic.

**To Reproduce**

- Create a sample app with a service exposed with NodePort
- Create virtual host in nginx to forward to NodePort
- Access said virtual host that should point to NodePort

**Expected behavior**

NodePort should acknowledge the traffic and serve the content.

**Additional context**

Apparently this should have been fixed in Kubernetes 1.9, where forwarded traffic is accepted by default in all NodePorts

**Comment by galal-hussein** [comment]
@sr229 I am not able to reproduce the issue on my setup, I was able to create a NodePort service normally and it accepts traffic as expected, can you send the issue you are referring to and more details on the setup.

**Comment by sr229** [comment]
@galal-hussein Kubernetes issue is [here](https://github.com/kubernetes/kubernetes/issues/39823).

Keep in mind traffic must come from a external nginx then goes to NodePort as a forward for this bug, not directly query the nodeport.

**Comment by abdennour** [comment]
Same here with RHEL7 known that firewalld was stopped: 

![image](https://user-images.githubusercontent.com/1788384/56839529-9ae5b900-688b-11e9-91a7-61380f64708b.png)
