### ISSUE TITLE
[release-1.21] Systemd does not get notified with READY state in etcd only nodes

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3792]
K3s fix for **Systemd does not get notified with READY state in etcd only nodes** on branch **release-1.21**:
* rancher/rke2#1483

**Comment by dereknola** [comment]
**Validated on release-1.21 branch commmit `18bc38d83852154d0a6f7cbc96f9c21aa5603d56`**
- Start up etcd-only k3s using systemd, no errors
```
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=18bc38d83852154d0a6f7cbc96f9c21aa5603d56 sh -s - server --cluster-init --disable-controller-manager --disable-scheduler --disable-apiserver
```
- Stopped k3s service with no errors
`systemctl stop k3s`
- Started k3s service with no errors
`systemctl start k3s`
- Restarted k3s service with no errors
`systemctl restart k3s`
