### ISSUE TITLE
k3s etcdctl wrapper

### ISSUE THREAD

**Issue by samcday** [k3s-io/k3s#3796]
**Is your feature request related to a problem? Please describe.**
When things inevitably go wrong with a cluster using an embedded etcd setup, it can be useful to drop down to `etcdctl` and talk to the etcd server about life (current health/status), politics (leader election info), and the environment (what other peers are there?). Sometimes all an etcd server needs is a good friend who can listen to them talk about their problems for a while... you know?

**Describe the solution you'd like**
I would like k3s to embed etcdctl as a subcommand: `k3s etcdctl`. This subcommand will act as a wrapper to `etcdctl` (so everything following `k3s etcdctl` is passed unmodified to the `etcdctl` CLI). It will set the necessary env vars or prepend the necessary flags in order to specify the endpoint address, CA file, and client certificate+key that etcdctl should use.

**Describe alternatives you've considered**
Using etcdctl directly. This requires manually installing etcdctl and passing a half-dozen complicated flags to it. [See this gist for an example](https://gist.github.com/superseb/0c06164eef5a097c66e810fe91a9d408).

**Additional context**
k3s already provides `k3s kubectl`, `k3s crictl`, etc. It also already provides `k3s etcd-snapshot`.

**Backporting**
Dunno, really.

**Comment by onedr0p** [comment]
Shame it won't be included since k3s already wraps kubectl and crictl. Having etcdctl embedded would be great because the cluster admins don't have to worry about the maintainence cost of providing the same etcdctl version as etcd included with k3s.

**Comment by brandond** [comment]
The embedded etcd should be self-managed by k3s; we want to discourage folks from poking at it manually.

> For example, creating a systemd service/timer to run etcdctl defrag

Recent releases of K3s compact the datastore on startup. It shouldn't be necessary to compact the datastore during the course of normal operations; if you run into some situation where you find this necessary please post more information about your environment.

**Comment by onedr0p** [comment]
Running kube-prometheus-stack I get notified about high fragmentation. Maybe their default alert threshold is too high? But in any case I did create a systemd service and timer to run etcdctl defrag once a day and that cleared up the alerts.

**Comment by brandond** [comment]
Do you happen to know what their threshold is? After how long do you get the alert?

**Comment by onedr0p** [comment]
https://github.com/prometheus-community/helm-charts/blob/3c4ae526051925d19776aea75beb0f4464351234/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml#L286

**Comment by brandond** [comment]
> etcd database size in use is less than 50% of the actual allocated storage.

that doesn't seem excessive. You might see the conversation starting at https://github.com/kubernetes/kubernetes/pull/45090#issuecomment-298067076 - a defrag shouldn't generally be run while the datastore is in use, as it stops all read/write operations to the datastore, copies all uncompacted revisions into a new file, and then deletes the old file, before resuming operations. This can be a time-consuming operation, blocking for up to several seconds depending on how much data you have in your cluster.

**Comment by onedr0p** [comment]
Good find, I guess I could go back to ignoring the alert and not defrag etcd.
