### ISSUE TITLE
`etcd-snapshot-dir` setting in config file is not honored for `k3s etcd snapshot` command

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#3799]
Hello, 

Seems that on demand snapshot are not saved on path defined by `--etcd-snapshot-dir` by at the default location.
Is it expected behavior to have only automatic snapshots performed at the correct location ? 

K3s Version: 
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
Severals nodes under Ubuntu ( mix of x86 and arm64 )

Cluster Configuration:
4 master 2workers using embeded etcd

**Steps To Reproduce:**
Run with the `--etcd-snapshot-dir` set to a given path , exectute `k3s etcd-snapshot save` 

**Expected behavior:**
Snapshot save under path set in `--etcd-snapshot-dir`

**Actual behavior:**
Snapshot save under `/var/lib/rancher/k3s/server/db/snapshots/on-demand.....`

**Backporting**
May be needed
- [x] Needs backporting to older releases

**Comment by adi90x** [comment]
> you must also pass it to the on-demand snapshot command.

Is it possible  ? I get a `FATA[0000] flag provided but not defined: -etcd-snapshot-dir`

Flag was set in a config file already...

**Comment by brandond** [comment]
Oh, my apologies... for some reason we decided to make this just `dir` for the --etcd-snapshot command, probably to avoid a stutter in the CLI. The downside to this is that the config file setting isn't honored, which I think is worth considering a bug.

https://github.com/k3s-io/k3s/blob/v1.21.3+k3s1/pkg/cli/cmds/etcd_snapshot.go#L91
