### ISSUE TITLE
k3s state inconsistent after filesystem rollback of all nodes in cluster

### ISSUE THREAD

**Issue by nikhilbhandari123** [k3s-io/k3s#3803]
**Environmental Info:**
K3s Version: 

k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 

Linux ztna-gateway 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 masters

**Describe the bug:**

In a 3 node cluster, two of the nodes are showing different node status, although part of the same cluster. On node 1:

root@node1-8yn:~# kubectl get node
NAME                                   STATUS     ROLES                       AGE     VERSION
2cbec8fc-af94-4e71-905d-e4a4147adb8d   NotReady   control-plane,etcd,master   7h45m   v1.21.1+k3s1
402d4f67-753e-4eee-bde9-1753b8e8c8af   NotReady   control-plane,etcd,master   7h38m   v1.21.1+k3s1
b6db18f1-9645-4c7c-bd00-7535b61f0ab2   Ready      control-plane,etcd,master   7h38m   v1.21.1+k3s1

On node2:
root@ztna-gateway-rh2k:/# kubectl get node
NAME                                   STATUS     ROLES                       AGE     VERSION
2cbec8fc-af94-4e71-905d-e4a4147adb8d   Ready      control-plane,etcd,master   7h46m   v1.21.1+k3s1
402d4f67-753e-4eee-bde9-1753b8e8c8af   NotReady   control-plane,etcd,master   7h39m   v1.21.1+k3s1
b6db18f1-9645-4c7c-bd00-7535b61f0ab2   NotReady   control-plane,etcd,master   7h38m   v1.21.1+k3s1

As can be seen, both nodes are giving different status for the same nodes

**Steps To Reproduce:**

- Installed K3s: 
Installed k3s using config file

1) We have two kernel partitions. k3s with all pods running on partition 1
2) Do an upgrade, which involves copying all the data (including etcd related one) to partition2 and rebooting each node. This is done sequentially, one by one.
3) After some time, do a rollback. This involves just switching the partitions. Just boot from partition 1. This is done simultaneously on all nodes.
4) Sometimes we hit the problem after the nodes come back up

**Expected behavior:**

The k3s cluster should be up and running and give consistent status on aqll nodes

**Actual behavior:**

The cluster is in undetermininstic state, giving different status on every node

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> Do an upgrade, which involves copying all the data (including etcd related one) to partition2 and rebooting each node. This is done sequentially, one by one.
> After some time, do a rollback. This involves just switching the partitions. Just boot from partition 1. This is done simultaneously on all nodes.

You don't say, but I'm assuming you're using managed etcd? I'm not sure how etcd will handle this, but it shouldn't be possible to end up with a split-brain scenario due to how etcd handles quorum. Can you provide logs from K3s after each of the operations (after switch over to the new partitions, and after rollback)?

**Comment by brandond** [comment]
I've changed the title to reflect the fact that you're not simply rebooting the nodes, but rather rolling back the cluster and filesystem state.

**Comment by nikhilbhandari123** [comment]
> > Do an upgrade, which involves copying all the data (including etcd related one) to partition2 and rebooting each node. This is done sequentially, one by one.
> > After some time, do a rollback. This involves just switching the partitions. Just boot from partition 1. This is done simultaneously on all nodes.
> 
> You don't say, but I'm assuming you're using managed etcd? I'm not sure how well etcd will handle what you're doing, but it shouldn't be possible to end up with a split-brain scenario due to how etcd handles quorum. Can you provide logs from K3s after each of the operations (after switch over to the new partitions, and after rollback)?

We are using embedded etcd. Attached are the k3s logs from one node. Check for the first occurrence of "-- Reboot --" in these files.

**Comment by nikhilbhandari123** [comment]
[logs_before_upgrade.txt](https://github.com/k3s-io/k3s/files/6959001/logs_before_upgrade.txt)

**Comment by nikhilbhandari123** [comment]
[logs_after_downgrade_2.txt](https://github.com/k3s-io/k3s/files/6959029/logs_after_downgrade_2.txt)

**Comment by brandond** [comment]
Other than a couple warnings about clock drift between nodes, I don't see anything particularly critical here:
```console
Aug 09 11:03:08 node1-8yn k3s[1102]: {"level":"warn","ts":"2021-08-09T11:03:08.732Z","caller":"rafthttp/probing_status.go:86","msg":"prober found high clock drift","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"968b2f6122bb50ec","clock-drift":"1.222858017s","rtt":"6.374297ms"}
Aug 09 11:03:08 node1-8yn k3s[1102]: {"level":"warn","ts":"2021-08-09T11:03:08.733Z","caller":"rafthttp/probing_status.go:86","msg":"prober found high clock drift","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"968b2f6122bb50ec","clock-drift":"1.222436228s","rtt":"6.338044ms"}
```
Can you attach the output from `kubectl describe nodes` from two nodes that disagree about cluster member readiness?

**Comment by nikhilbhandari123** [comment]
[describe_node_1.txt](https://github.com/k3s-io/k3s/files/6959120/describe_node_1.txt)
[describe_node_2.txt](https://github.com/k3s-io/k3s/files/6959121/describe_node_2.txt)

**Comment by brandond** [comment]
Are you rolling back **all** of the filesystem data, or just some of it? etcd reports that it hasn't seen a heartbeat from the other nodes since before the filesystems were switched, so I suspect it has something to do with stale caches stuck using data from before you reverted. I'm not sure that filesystem rollback of this type is really supported by etcd.

**Comment by nikhilbhandari123** [comment]
We are just switching the disk partition, so all the data should be from the other partition. Also, how can we detect this condition and come out of it ?

**Comment by brandond** [comment]
Have you tried just restarting k3s an extra time after rolling back the filesystem?

**Comment by nikhilbhandari123** [comment]
yes, k3s restart and reboot of the VM also did not help

**Comment by brandond** [comment]
Hmm, I'm not sure then. Can you explain more about why you're trying to roll back the filesystem? The supported way of doing this would be via etcd cluster backup/restore.

**Comment by nikhilbhandari123** [comment]
Basically, we have to support the upgrade and downgrade of our software releases. In case of upgrade to higher version, we keep one release in one partition and download a newer one in the second one. And copy all the /var and /etc data to the newer partition and then switch the partition. This works fine and we do it one node at a time.

But if the user wants to go back to the previous release, we simply switch the partitions on all nodes and reboot. No copying of /var or /etc is done as we want the older data to continue.

k3s also supports the etcd backup and restore but it needs some synchronization between nodes. We need to stop the k3s on all nodes first, then do a restore on one of the nodes and then start the k3s on all, right ? This is difficult to automate.

**Comment by brandond** [comment]
That's an interesting approach. Clearly something is getting out of sync when you switch back to the old partition. Kubernetes does not have any caches that persist across process restarts so if simply restarting K3s on all the nodes doesn't resolve the issue I'm concerned that something in your process is causing bad data to be fed into the datastore.

**Comment by nikhilbhandari123** [comment]
No, our product is not yet available. So what I am gathering is that our approach is not entirely incorrect but probably incomplete.

The etcd backup/restore approach is not quite amenable to automation. What all can go wrong with the datastore ? Are we overwriting something or using some stale data ?

**Comment by brandond** [comment]
I'm not sure what's going on, that's why I wanted to try it myself. I would expect to see some stale data for maybe a minute or two after first starting up using an old snapshot of the database, but I wouldn't expect that to persist for an extended period of time, or across multiple service restarts.

**Comment by nikhilbhandari123** [comment]
Ok, sometimes we see one of the three nodes is not able to join the cluster after reboot. Its k3s would not get started. In those cases, we stop the k3s on that node, delete the node from the cluster, wipe out the etcd database and start the k3s again.  That would allow the node to join back. But there the k3s would not start and we can detect the condition and take the above steps automatically.

But in this case, the k3s is up and running on all nodes but does not have correct data. If we could detect this case, we can take remedial steps.
