### ISSUE TITLE
Cluster Reset Issue

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#3806]
Hello, 

Trying to play with the cluster-reset from one of the embedded etcd snapshot, cluster is working fine, but if I switch all host off, clean `/var/lib/rancher` to make sure everything is deleted, then I can use `k3s server --cluster-reset --cluster-reset-path path-to-a-snapshot` , it run fine , cluster is up on this host and other host are in NotReady status as expected.

Host with public ip seems to be able to rejoin the cluster without any issue.
However , hosts behind NAT are not able to rejoin the cluster ( while they were able to connect to the cluster at inception ) 
Even, removing it from the cluster node , don't let them connect anymore.  

**Environmental Info:**
K3s Version: 
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
Several host under Ubuntu

Cluster Configuration:
4 masters / 2 agents ==> 2 master behind NAT, 2 in the cloud / agents are behind NAT

**Expected behavior:**
Would expect any node to be able to reconnect to the cluster.

**Actual behavior:**
Some hosts are not able to rejoin the cluster

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Duplicate of https://github.com/k3s-io/k3s/issues/3651 - will be fixed in a subsequent release.

**Comment by adi90x** [comment]
Testing it using ansible ( so process is stable), and one of the step completly remove any iptables rules so normally no distinction between bare metal host ( nated) and cloud machine ( at least at the moment it is the only difference between the 2 hosts I can think of ) ...
Will grab and some more logs of working and non working host.
