### ISSUE TITLE
s3 snapshots do not show in the rancher 2.6 UI

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3811]
Fix for **s3 snapshots do not show in the rancher 2.6 UI** on branch **master**:
* rancher/rke2#1551

**Comment by rancher-max** [comment]
Confirmed working the same as in https://github.com/k3s-io/k3s/issues/3808#issuecomment-901293631, using commitid from master branch `8b857eef9c15ed97180079c0dcf5cf0f8cb888de`
