### ISSUE TITLE
The waitManagementIP function in pkg/daemons/agent/agent_windows.go is calling the incorrect HNS function.

### ISSUE THREAD

**Issue by phillipsj** [k3s-io/k3s#3817]
The waitManagementIP function in pkg/daemons/agent/agent_windows.go is calling the incorrect HNS function. It is calling GetHNSEndpointByName instead of calling GetHNSNetworkByName.

**Environmental Info:**
K3s Version: HEAD

**Describe the bug:**
This causes an issue, because the call never resolves a valid IP.

**Comment by rancher-max** [comment]
This has been validated in rke2 windows agents. k3s windows agents currently are not supported, so we aren't doing any specific k3s validations against this.
