### ISSUE TITLE
Cannot run multiple integration tests at once.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#3819]
**Describe the bug:**

Now that multiple integration tests exist, they cannot be run at the same time. 

**Steps To Reproduce:**
`go test ./pkg/... ./tests/... -run Integration` 
**Expected behavior:**

All integration tests pass.

**Actual behavior:**

The tests fail, because the second integration test launches a second k3s server which gets killed by the first test on cleanup. 

**Additional context / logs:**
While the initial CLI controls for integration tests worked, it does not scale to multiple tests running concurrently. We need to either convert integration tests to exclusively run sequentially, or implement a locking system.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
Since this is for CI tests you can close this out as there is no testing for me to do here. Unless @dereknola you want to do something more with this before closing.

**Comment by dereknola** [comment]
Closed as this only affects testing.
