### ISSUE TITLE
Cannot join etcd node with specific combinations of member IP addresses

### ISSUE THREAD

**Issue by mstarostik** [k3s-io/k3s#3831]
**Environmental Info:**
k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4

Also present in:
k3s version v1.21.3+k3s-a1e36153-dirty (a1e36153)
go version go1.16.6
the -dirty part just being the fix for this issue

Node(s) CPU architecture, OS, and Version: 
Linux c-1 5.4.0-73-generic #82 SMP Thu Jun 3 02:29:43 UTC 2021 x86_64 GNU/Linux
k3OS v0.21.1-k3s1r0

Cluster Configuration:
Minimal test cluster: 1 server (including embedded etcd), 2nd server to join

**Describe the bug:**
Second server with etcd role cannot join if the string representation of its Node/Advertise IP address is a substring of the existing etcd server's IP

**Steps To Reproduce:**
- Installed K3s: Installed k3OS on two nodes.
- 1st server with --cluster-init, node IP 10.0.0.255
- 2nd server with server_url: https://10.0.0.255:6443, node IP 10.0.0.2

**Expected behavior:**
Get a cluster with two server nodes, both being etcd members

**Actual behavior:**
2nd node won't join

**Additional context / logs:**
time="2021-08-12T19:07:15.180143758Z" level=info msg="Starting k3s v1.21.1+k3s1 (75dba57f)"
time="2021-08-12T19:07:15.219392660Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
time="2021-08-12T19:07:15.219765757Z" level=info msg="Managed etcd cluster not yet initialized"
time="2021-08-12T19:07:15.235265597Z" level=fatal msg="starting kubernetes: preparing server: start managed database: joining etcd cluster: etcdclient: no available endpoints"

**Backporting**
- [ ] Needs backporting to older releases

Don't think this is needed, there's an easy workaround (use different IPs).

**Comment by rancher-max** [comment]
Validated the same as in https://github.com/k3s-io/k3s/issues/3833#issuecomment-901405862 using master commitid `ad1a40a96c400c17780cf9455f5da330d690194c`
