### ISSUE TITLE
[master] Restoration fails on etcd only nodes due to invalid state of loadbalancers

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#3873]
**Environmental Info:**
K3s Version: v1.21.x

Node(s) CPU architecture, OS, and Version: 
Linux rke2-server 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 GNU/Linux

Cluster Configuration:
- 1 etcd only node server
- 1 controlplane node servers
- 
**Describe the bug:**
upon restoring on an existing etcd only node, it tries to setup internal load balancer with existing configuration, and tries to connect to old supervisor servers, which may or may not exist and fails to restore wiht the following error:

```
g 17 18:29:25 darren-pool1-hjh5k rancher-system-agent[3099]: time="2021-08-17T18:29:25Z" level=info msg="[stderr]: time=\"2021-08-17T18:29:25Z\" level=info msg=\"Waiting to retrieve agent configuration; server is not ready: Get \\\"https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt\\\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\""
```

**Backporting**

- [x] Needs backporting to older releases

**Comment by rancher-max** [comment]
Validated this is working on master branch commitid `8b857eef9c15ed97180079c0dcf5cf0f8cb888de`
