### ISSUE TITLE
getting logs fails

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [k3s-io/k3s#3883]
**Environmental Info:**
K3s Version: v1.21.3+k3s1 (1d1f220f)

Node(s) CPU architecture, OS, and Version: Linux honestmistake 5.13.9-200.fc34.x86_64 #1 SMP Sun Aug 8 14:34:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: default installation (1 server, 1 agent ?)

**Describe the bug:**

querying for the logs of a pod fails with the error message `Error from server: Get "https://honestmistake:10250/containerLogs/default/scorecard-test-pc8j/scorecard-test": dial tcp: lookup honestmistake: Try again
`
"honestmistake" is my hostname
**Steps To Reproduce:**

- Installed K3s: 
`curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644`
- Create a pod
- try to get the logs with `kubectl logs pod-name` or `k3s kubectl logs pod-name`

**Expected behavior:**
See the logs of the pod

**Actual behavior:**

```
Error from server: Get "https://honestmistake:10250/containerLogs/default/scorecard-test-pc8j/scorecard-test": dial tcp: lookup honestmistake: Try again
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
You should be able to resolve the node's hostname. If you don't have functioning DNS, you might try adding an entry in /etc/hosts?

**Comment by SoMuchForSubtlety** [comment]
After rebooting my laptop the problem has gone away (I guess I could have tried that before opening an issue).

I'm still curious why only gettings logs didnt work and other operations performed by kubectl worked. 🤔

**Comment by brandond** [comment]
Getting logs and execing into pods are unique operations in that they require the apiserver to initiate a connection to the node running the pod. Everything else is pretty much contained to the apiserver.
