### ISSUE TITLE
Traefik not upgraded when going from 

### ISSUE THREAD

**Issue by timyates** [k3s-io/k3s#3885]
**Environmental Info:**
K3s Version: v1.20.9+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux ip-172-31-47-178.eu-west-1.compute.internal 4.14.238-182.422.amzn2.x86_64 #1 SMP Tue Jul 20 20:35:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node installation via `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.9+k3s1 sh -s - --write-kubeconfig-mode 644;`

**Describe the bug:**

The manifests in `/var/lib/rancher/k3s/server/manifests` are not updated when upgrading the single node k3s installation via `curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644;`

This means that the old version of Traefik (as an example) is still running, so I cannot use `IngressRoute` on the updated cluster.

Is there a step I'm missing to get the updated manifests?

**Steps To Reproduce:**

Install the old version with Traefik 1

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.9+k3s1 sh -s - --write-kubeconfig-mode 644;
```

Check out the manifests folder:

```
$ sudo ls -lah /var/lib/rancher/k3s/server/manifests
total 24K
drwx------ 3 root root  135 Aug 18 14:23 .
drwx------ 7 root root  118 Aug 18 14:24 ..
-rw------- 1 root root 1.1K Aug 18 14:25 ccm.yaml
-rw------- 1 root root 4.3K Aug 18 14:25 coredns.yaml
-rw------- 1 root root 3.6K Aug 18 14:25 local-storage.yaml
drwx------ 2 root root  227 Aug 18 14:23 metrics-server
-rw------- 1 root root 1.1K Aug 18 14:25 rolebindings.yaml
-rw------- 1 root root  759 Aug 18 14:23 traefik.yaml
```

Upgrade to latest stable

```
curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644;
```

The manifests folder has not changed

```
$ sudo ls -lah /var/lib/rancher/k3s/server/manifests
total 24K
drwx------ 3 root root  135 Aug 18 14:23 .
drwx------ 7 root root  118 Aug 18 14:24 ..
-rw------- 1 root root 1.1K Aug 18 14:25 ccm.yaml
-rw------- 1 root root 4.3K Aug 18 14:25 coredns.yaml
-rw------- 1 root root 3.6K Aug 18 14:25 local-storage.yaml
drwx------ 2 root root  227 Aug 18 14:23 metrics-server
-rw------- 1 root root 1.1K Aug 18 14:25 rolebindings.yaml
-rw------- 1 root root  759 Aug 18 14:23 traefik.yaml
```

And the contents of the traefik.yaml file is still the old:

```
$ sudo cat /var/lib/rancher/k3s/server/manifests/traefik.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  valuesContent: |-
    rbac:
      enabled: true
    ssl:
      enabled: true
    metrics:
      prometheus:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    priorityClassName: "system-cluster-critical"
    image: "rancher/library-traefik"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
```

With a fresh, clean install of k3s on a clean new box, that file contains (as expected)

```
$ sudo cat /var/lib/rancher/k3s/server/manifests/traefik.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-9.18.2.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-9.18.2.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/library-traefik"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
```

Am I missing an important step?

**Comment by brandond** [comment]
As per the docs at https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller:

> If Traefik is not disabled K3s versions 1.20 and earlier will install Traefik v1, while K3s versions 1.21 and later will install Traefik v2 if v1 is not already present.
>
>To migrate from an older Traefik v1 instance please refer to the Traefik documentation and migration tool.

The docs contains links to the migration docs and tool. If you don't want to worry about migrating and are open to a clean instal, you can always start k3s with `--disable=traefik` to remove the v1 Helm chart, and then restart again without the flag to install the v2 chart.

**Comment by timyates** [comment]
Cool, I knew I'd missed something 😁

I'm sure I tried running the installer with traefik disabled, then running the new version with it enabled, and nothing happened

I will try again as soon as I get back to my laptop, and report my results here

Thanks for the help 👍

**Comment by timyates** [comment]
Closing the loop here, I tested it out, and all works as you said

Ran the old installer with `--disable=traefik` then when it had gone away, installed the new version and new traefik came back 😎 

Thank you so much for the response, and my apologies for the noise 👍
