### ISSUE TITLE
Validate S3 credentials before taking backups

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#3889]
**Environmental Info:**
K3s Version: master HEAD

Cluster Configuration:
any cluster configuration

**Describe the bug:**

We dont validate s3 credentials before taking the backup

**Steps To Reproduce:**
- Install k3s with etcd backend (--cluster-init)
- Take snapshot with s3 backend with wrong credentials

**Expected behavior:**
To exit with an error before taking a snapshot

**Actual behavior:**
snapshot is taken on disk and an error is thrown after that because of wrong credentials

- https://github.com/rancher/rancher/issues/34314

**Comment by briandowns** [comment]
No change to be made at this time to the code. Issue lies in an adjacent system.
