### ISSUE TITLE
k3s-uninstall.sh should be aware of non-default k3s data-dir

### ISSUE THREAD

**Issue by ChristianCiach** [k3s-io/k3s#3904]
See:

https://github.com/k3s-io/k3s/blob/703b5af950ed136c1745ccad574eb26b6bccf37c/install.sh#L692

The uninstall scripts created by `install.sh` (both for servers and agents) should take non-default data-dir locations into account. The same may be true for other paths that are currently hardcoded.

**Comment by brandond** [comment]
How would you suggest going about that, without embedded a full cli/yaml parser in the uninstall script?

**Comment by xiaods** [comment]
good question.

**Comment by ChristianCiach** [comment]
Well, i have several possible solutions in mind.

For example, the k3s binary could provide a new command like `k3s get-config-value [key]` that returns the current value of the given config key (`data-dir` in this example). The uninstall script could then retrieve the necessary values from the k3s binary. 

That being said, I don't really *need* this fixed. I call the uninstall script from an ansible playbooks and I could just as well delete the data-dir by myself. I was just surprised by the current behavior of the uninstall script.

**Comment by xiaods** [comment]
ansible is good optinal tools.

**Comment by ChristianCiach** [comment]
> How would you suggest going about that, without embedded a full cli/yaml parser in the uninstall script?

By the way: `k3s secrets-encrypt rotate` seems to workaround this issue by accepting a `--data-dir` argument. These scripts could do the same, but it may not be worth the effort.
