### ISSUE TITLE
[release-1.21] Auto-deploy Manifests Should Periodically Re-evaluate

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3919]
Backport fix for **Auto-deploy Manifests Should Periodically Re-evaluate** to branch **release-1.21**:
* #3711

Just the issue described at https://github.com/k3s-io/k3s/issues/3711#issuecomment-887048741

**Comment by rancher-max** [comment]
Validated on release-1.21 branch using commitid `863512e0555662e4bc72c3722c13c04c62e92386` following the same steps mentioned in my comment against the issue this is backported from.
