### ISSUE TITLE
Move to newer cni plugin binaries

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#3924]
**Is your feature request related to a problem? Please describe.**

The cni plugin binaries that k3s is using are quite old

**Describe the solution you'd like**

I would like binaries to be newer. At least v0.9.1, so that flannel supports dual-stack

**Describe alternatives you've considered**

**Additional context**

Connected to issue https://github.com/k3s-io/k3s/issues/1405

**Backporting**

No

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
This will be validated as part of standard patch testing so I am just going to close this and let that be a blanket cover for this (sonobuoy, regression checks including ingress, service discovery, etc.)
