### ISSUE TITLE
Implement Sonobuoy Plugin for Integration tests

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#3927]
**Is your feature request related to a problem? Please describe.**

It is difficult to use integration tests on existing k3s clusters.

**Describe the solution you'd like**

In order to improve testing across a wide range of k3s deployments, creating a Sonobuoy plugin which will run integration tests in on a existing cluster is desirable.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
This is run as part of CI so is good to close as needs no additional testing
