### ISSUE TITLE
[engine-1.21] Add functions to separate ipv4 and ipv6 CIDRs

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#3928]
Add two functions to discriminate ipv4 and ipv6 addresses. This will simplify our lives if we want to use dual-stack with cni plugins such as Calico which does not follow the kubernetes convention "cluster-cidr: $CIDR_ipv4,$CIDR_ipv6"

Linked issue: https://github.com/k3s-io/k3s/issues/3930

**Comment by rancher-max** [comment]
Closing for the same reason as https://github.com/k3s-io/k3s/issues/3930
