### ISSUE TITLE
API proxy server 127.0.0.1:6445 under k3s kube-proxy ipvs mode not reachable from pod

### ISSUE THREAD

**Issue by vincentmli** [k3s-io/k3s#393]
**Describe the bug**
when run k3s kube-proxy mode in ipvs mode, the internal API proxy server 127.0.0.1:6445 is unreachable from POD

for example, telnet k3s service 10.43.0.1 443 which  should be served by 127.0.0.1:6445

<pre>

[root@rancher-k3s ~]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.43.0.1:443 rr
  -> 127.0.0.1:6445               Masq    1      0          3         !----------
TCP  10.43.0.10:53 rr
  -> 10.42.0.168:53               Masq    1      0          0         
TCP  10.43.0.10:9153 rr
  -> 10.42.0.168:9153             Masq    1      0          0         
TCP  10.43.255.52:80 rr
  -> 10.42.0.169:80               Masq    1      0          0         
  -> 10.42.0.170:80               Masq    1      0          0         
UDP  10.43.0.10:53 rr
  -> 10.42.0.168:53               Masq    1      0          0         

[root@rancher-k3s home]# kubectl get po -o wide
NAME            READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
busybox-td4x8   1/1     Running   26         24h   10.42.0.171   rancher-k3s   <none>           <none>
nginx-6gcpf     1/1     Running   4          24h   10.42.0.170   rancher-k3s   <none>           <none>
nginx-vdc7l     1/1     Running   4          24h   10.42.0.169   rancher-k3s   <none>           <none>

</pre>

from iptables trace, there is no DNAT to 127.0.0.1

<pre>
Apr 25 10:37:46 localhost kernel: TRACE: raw:PREROUTING:policy:2 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: nat:PREROUTING:rule:1 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: nat:KUBE-SERVICES:rule:2 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: nat:KUBE-NODE-PORT:return:1 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: nat:KUBE-SERVICES:rule:3 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: filter:INPUT:rule:1 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: filter:KUBE-FIREWALL:return:2 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
Apr 25 10:37:46 localhost kernel: TRACE: filter:INPUT:policy:2 IN=cni0 OUT= PHYSIN=veth9d176157 MAC=16:d8:49:2b:ee:6d:8e:b1:b2:a2:af:77:08:00 SRC=10.42.0.166 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=23703 DF PROTO=TCP SPT=57326 DPT=443 SEQ=613122998 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0003DF210000000001030307)
</pre>

when k3s kube-proxy running in iptables mode, there is a specific iptables nat rule to do the DNAT, I looked through the k3s code, I could not find where this DNAT rule is setup, could you point me to the right direction?

<pre>
Chain KUBE-SEP-QUSWRCCKNVSH5RXX (1 references)
target     prot opt source               destination
KUBE-MARK-MASQ  all  --  127.0.0.1            0.0.0.0/0
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp to:127.0.0.1:6445  !-------------DNAT

Apr 25 10:55:00 localhost kernel: TRACE: raw:PREROUTING:rule:2 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: raw:PREROUTING:policy:3 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: nat:PREROUTING:rule:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: nat:KUBE-SERVICES:rule:2 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: nat:KUBE-SVC-NPX46M4PTMTKRN6Y:rule:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: nat:KUBE-SEP-QUSWRCCKNVSH5RXX:rule:2 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=10.43.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=443 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307) !-------------
Apr 25 10:55:00 localhost kernel: TRACE: filter:INPUT:rule:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:KUBE-SERVICES:return:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:INPUT:rule:2 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:KUBE-EXTERNAL-SERVICES:return:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:INPUT:rule:3 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:KUBE-FIREWALL:return:2 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: filter:INPUT:policy:4 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
Apr 25 10:55:00 localhost kernel: TRACE: nat:INPUT:policy:1 IN=cni0 OUT= PHYSIN=veth2be92e2c MAC=c6:3c:24:8a:47:33:a2:28:bc:92:e1:45:08:00 SRC=10.42.0.171 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=29277 DF PROTO=TCP SPT=37488 DPT=6445 SEQ=566882261 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A00039D880000000001030307)
                                                                     
</pre>

when in ipvs mode, the ipvs should do the DNAT, but since the destination is 127.0.0.1, there might be some special thing to ipvs to DNAT to 127.0.0.1, I think if the api proxy destination is  non loopback address 127.0.0.1, it should work since I have no problem reach other k3s service that has backend point to pod ip address.  maybe adjust the API proxy server backend to non 127.0.0.1  address when in ipvs mode? this may expose 6445 port to external so I would like to get more input.

**To Reproduce**

execute k3s server with as below:

ExecStart=/usr/local/bin/k3s server --no-deploy traefik --kube-proxy-arg "proxy-mode=ipvs" 

*Expected behavior**

k3s API proxy server service 10.43.0.1:443 is reachable in kube-proxy ipvs mode from pod

**Screenshots**

**Additional context**

**Comment by ibuildthecloud** [comment]
We might have legitimate issues supporting ipvs.  This hasn't been tried.  We make a change to kubernetes such that kube-proxy sends all traffic to localhost (which is running a proxy to the API server).  I don't know if IPVS will work because of that.

**Comment by runningman84** [comment]
Maybe even the client ip address could be preserved with ipvs.
