### ISSUE TITLE
Add functions to separate ipv4 and ipv6 CIDRs

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#3930]
**Is your feature request related to a problem? Please describe.**

Add two functions to discriminate ipv4 and ipv6 addresses. This will simplify our lives if we want to use dual-stack with cni plugins such as Calico which does not follow the kubernetes convention "cluster-cidr: $CIDR_ipv4,$CIDR_ipv6"

**Describe the solution you'd like**

Create two functions, one for ipv4 and one for ipv6

**Describe alternatives you've considered**

Use only one function with an extra argument to decide if it is ipv4, ipv6 or both. However, that will be more complicated

**Additional context**

Dual-stack is beta since 1.21

**Backporting**

To the k3s-engine

- [X] Needs backporting to older releases

Linked issue: https://github.com/rancher/rke2/issues/1717
PR: https://github.com/k3s-io/k3s/pull/3916

**Comment by rancher-max** [comment]
I'm going to close this out as it's just two unused functions in k3s. The rke2 issue will need to be validated separately as it will use these.
