### ISSUE TITLE
When k3s server flannel-backend=none flannel.alpha.coreos.com annotation attached to node

### ISSUE THREAD

**Issue by vincentmli** [k3s-io/k3s#3932]
**Environmental Info:**
K3s Version: 
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

ExecStart=/usr/local/bin/k3s \
    server \
        '--disable=traefik' \
        '--flannel-backend=none' \
        '--node-ip=10.169.72.127' \

**Describe the bug:**

when specify --flannel-backend=none, the k3s server node still has flannel annotation attached to the node

```
kubectl describe node k8s-cilium-master 
Name:               k8s-cilium-master
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    k3s.io/hostname=k8s-cilium-master
                    k3s.io/internal-ip=10.169.72.127
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k8s-cilium-master
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.169.72.127
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"46:b9:0f:9c:bd:f8"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.3.72.127
                    io.cilium.network.ipv4-cilium-host: 10.0.0.86
                    io.cilium.network.ipv4-pod-cidr: 10.0.0.0/24
                    k3s.io/hostname: k8s-cilium-master
                    k3s.io/internal-ip: 10.169.72.127
                    k3s.io/node-args: ["server","--disable","traefik","--flannel-backend","none","--node-ip","10.169.72.127"]

```

**Steps To Reproduce:**

- Installed K3s: 
```
curl -sfL https://get.k3s.io | sh -s - --disable=traefik --flannel-backend=none --node-ip=10.169.72.127
```
**Expected behavior:**
expect no flannel annotation  attached to node when flannel-backend set to none

```
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"46:b9:0f:9c:bd:f8"}
                    flannel.alpha.coreos.com/backend-type: vxlan
```
**Actual behavior:**
k3s node has flannel annotation attached to node

**Additional context / logs:**

**Backporting**

**Comment by brandond** [comment]
Other than being unexpected, are the annotations causing any problems?

Those labels are managed by Flannel; if you disable Flannel there is nothing in K3s that will remove them. You should probably start the cluster with flannel disabled from the start (by setting --flannel-backend=none) so that the annotations are never set. If you're disabling flannel on an existing cluster, you can delete them manually if they present a problem.

**Comment by vincentmli** [comment]
I believe I started k3s from fresh install with flannel-backend=none and the flannel annotation is still attached to the node, the old '--no-flannel' does not attach flannel annotation to node, so I think flannel-backend=none should behave same as --no-flannel since flannel-backend=none is suppose to replace --no-flannel. 

the flannel annotation did cause problem with https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/vxlan/vxlanMgr.go#L143-L151 because k8s-bigip-ctlr get wrong MAC and VNI value when flannel is not used in k3s.

**Comment by brandond** [comment]
> I believe I started k3s from fresh install with flannel-backend=none and the flannel annotation is still attached to the node

I don't believe you did, or the annotations wouldn't exist.

K3s does not set the annotations, Flannel does. If you start k3s with --flannel-backend=none then Flannel is never started and will not set the annotations. I confirmed this by starting a fresh cluster with:
```bash
docker run --rm -it --privileged --name k3s-server-1 --hostname k3s-server-1 rancher/k3s:v1.21.4-k3s1 server --token=token --flannel-backend=none
```

and then running this on another terminal:
```console
brandond@dev01:~$ docker exec -it k3s-server-1 kubectl describe node
Name:               k3s-server-1
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k3s-server-1
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        k3s.io/hostname: k3s-server-1
                    k3s.io/internal-ip: 172.17.0.2
                    k3s.io/node-args: ["server","--token","********","--flannel-backend","none"]
                    k3s.io/node-config-hash: DCJ4GIWEKZ3AHLKVN4B2SYE65Y6RPFBZD272VOIWFBXVYGAOCVGA====
                    k3s.io/node-env: {}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 30 Aug 2021 20:54:29 +0000
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
```

As you can see, there are no flannel annotations.

**Comment by vincentmli** [comment]
> 
> As you can see, there are no flannel annotations.
indeed, I tested again, no flannel annotation, I must have messed up with my fresh install with old install, glad it is working as expected, thanks for confirming this, we are good to close this
