### ISSUE TITLE
Container gives too many open file error

### ISSUE THREAD

**Issue by wouldgo** [k3s-io/k3s#3934]
**Environmental Info:**
K3s Version: 
```
k3s version v1.21.3+k3s1 (1d1f220f)
go version go1.16.6
```

Node(s) CPU architecture, OS, and Version: 
```
Linux midgard 5.10.27-0-rpi4 #1-Alpine SMP PREEMPT Wed Mar 31 09:40:59 UTC 2021 aarch64 Linux
Linux asgard 5.10.43-0-rpi4 #1-Alpine SMP PREEMPT Fri Jun 11 11:47:08 UTC 2021 aarch64 Linux
```

Cluster Configuration:
```
NAME      STATUS   ROLES                  AGE   VERSION
midgard   Ready    control-plane,master   28d   v1.21.3+k3s1
asgard    Ready    <none>                 28d   v1.21.3+k3s1
```

**Describe the bug:**
As reported also [here](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12951) I have an influxdb instance inside a container managed by k3s that complains about `too many open files`. The `ulimit -a` output inside the container gives me this:

```shell
bash-5.1# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 14891
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 14891
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

but I'm not able to increase the `nofile` value. Digging a little bit more reveal that every container managed by k3s has the same `ulimit -a` output. 

Are there any suggestions on how increase the `nofile` value?
Thanks for your time
Dario.

**Comment by ChristianCiach** [comment]
I know next to nothing about Alpine, but maybe I can point you in the right direction.

When installing k3s using the `install.sh`, the installer creates a systemd unit file that looks like this: https://github.com/k3s-io/k3s/blob/master/k3s.service

It contains these lines:

```
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
```

These limit are usually found inside the service file of containerd, but since k3s includes containerd inside its binary, these limits are set for the k3s service in this case. 

I guess Alpine probably does not use systemd, so you probably use another way to run the service. Maybe you find the comment from the systemd unit file helpful.

Also have a look at the installation instructions for Alpine Linux: https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup

**Comment by wouldgo** [comment]
Alpine uses OpenRC. 
As a point of reference the host images loaded on the machines are from [this](https://github.com/wouldgo/alpine-raspberry-pi) script.

The cgroup settings from that page are into the `/boot/cmdline.txt` that rpi uses to [boot the system](https://github.com/wouldgo/alpine-raspberry-pi/blob/master/bootstrap/01-kernel.sh#L10)

**Comment by brandond** [comment]
https://github.com/OpenRC/openrc/blob/master/user-guide.md#ulimit-and-cgroups

Can you try creating `/etc/conf.d/k3s` with contents `-n 1048576`

**Comment by wouldgo** [comment]
Seems the same advice that @ncopa suggest [here](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12951#note_176871) and nothing changed. I tried also to put limits on the `/etc/rc.conf` file but I didn't spot any change

**Comment by brandond** [comment]
Did you kill the existing pod after changing that and restarting k3s?

**Comment by wouldgo** [comment]
I tried putting in `containerd` after see no changes on his suggestion on putting into `k3s`.
I reboot the entire node (asgard in that configuration) and what I report is after reboot
.

**Comment by wouldgo** [comment]
What you suggested delete the `influxd` too many open file error from its logs. Thanks a lot for your help. 

I've only one more question. After seeing that influxdb-0 pod is finally ready and healty:
```sh
k get pods -n influxdb      
NAME         READY   STATUS    RESTARTS   AGE
influxdb-0   1/1     Running   472        5d22h
```

I took a look at its `ulimit`:
```sh
k -n influxdb exec -it influxdb-0 -- bash 
bash-5.1# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 14891
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 14891
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
bash-5.1# ^C
bash-5.1# exit
exit
command terminated with exit code 130
```

And there are the previous values, even looking on the node `/proc/<>/limits` file I see only the default values. 
Have you any clue why there is this situation now?

**Comment by brandond** [comment]
Limits are only set on container creation. As mentioned above, you should restart k3s using `k3s-killall.sh` if you want to terminate all pods so that they can pick up changes to the environment. If you want to restart only selected pods, you can just delete them using kubectl after restarting the k3s service.

**Comment by wouldgo** [comment]
Ok, previously I put the value into the `/etc/rancher/k3s/k3s.env` file and rebooted the node again, then I spotted what I was stating on the last part of last comment. Anyway I did a rollout on the statefulset influxdb and now again I got this scenario:

```sh
$ k -n influxdb rollout restart statefulset influxdb 
statefulset.apps/influxdb restarted

$ k get pods -n influxdb -w
NAME         READY   STATUS        RESTARTS   AGE
influxdb-0   0/1     Terminating   472        5d22h
influxdb-0   0/1     Terminating   472        5d22h
influxdb-0   0/1     Terminating   472        5d22h
influxdb-0   0/1     Pending       0          0s
influxdb-0   0/1     Pending       0          0s
influxdb-0   0/1     ContainerCreating   0          0s
influxdb-0   0/1     Running             0          2s

$ k -n influxdb exec -it influxdb-0 -- bash 
bash-5.1# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 14891
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 14891
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

Maybe I'm missing something but as far as i understand I restarted k3s and everything else rebooting.

**Comment by brandond** [comment]
It looks like for some reason our install script overwrites the k3s.env file; are you by any chance re-running the installer on startup and wiping out the contents? Other than that I can't reproduce this.

```console
alpine01:~# cat /etc/rancher/k3s/k3s.env
rc_ulimit="-n 1048576"
alpine01:~# kubectl run busybox -i --tty --image=busybox --restart=Never --rm -- sh -c 'ulimit -a'
core file size (blocks)         (-c) 0
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) 7887
max locked memory (kb)          (-l) 64
max memory size (kb)            (-m) unlimited
open files                      (-n) 1048576
POSIX message queues (bytes)    (-q) 819200
real-time priority              (-r) 0
stack size (kb)                 (-s) 8192
cpu time (seconds)              (-t) unlimited
max user processes              (-u) 7887
virtual memory (kb)             (-v) unlimited
file locks                      (-x) unlimited
pod "busybox" deleted
```

**Comment by wouldgo** [comment]
At the moment I cannot wipe anything (everything pop out because I'm importing 2 years of data into influx) and I have to finish that task but for sure in a matter of days I'll try again to install k3s on a fresh alpine image.

**Comment by wouldgo** [comment]
Hi again,

I wiped the cluster installation and after echoing the ulimit into `k3s.env` file I have the same result as yours.

**Comment by cybercoder** [comment]
@brandond 
After adding the env:

```
sudo service k3s restart
sh: error setting limit: Operation not permitted
 * k3s: unable to apply RC_ULIMIT settings
 * Stopping k3s ...                                                                                                          [ ok ]
sh: error setting limit: Operation not permitted
 * k3s: unable to apply RC_ULIMIT settings
 * Starting k3s ...
 ```

**Comment by brandond** [comment]
That appears to be an Alpine/openrc issue, not k3s?
