### ISSUE TITLE
High CPU usage after running for some time

### ISSUE THREAD

**Issue by fallenwood** [k3s-io/k3s#3956]
**Environmental Info:**
K3s Version: 

k3s version v1.21.2+k3s1 (5a67e8dc)
go version: go1.16.4

Node(s) CPU architecture, OS, and Version: 

Linux master 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

Model name:          Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz

Azure VM

Master: 1C 2G
Agent: 1C 1G

Cluster Configuration:

1 server, 2 agents

**Describe the bug:**

k3s & iptables running with high cpu usage, and the services in pods are not avaliable
![QQ图片20210901114047](https://user-images.githubusercontent.com/11188646/131608974-54b4076e-5732-4195-bd55-ccc4b702ea4d.png)

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

CPU usage is high. services not response

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
This looks a lot like https://github.com/k3s-io/k3s/issues/3117#issuecomment-810660207
