### ISSUE TITLE
RKE2 apiserver cert is missing hostname SAN entries

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3960]
Tracking issue for fixing **RKE2 apiserver cert is missing hostname SAN entries** from RKE2 on branch **master**:
* https://github.com/rancher/rke2/issues/1739

**Comment by rancher-max** [comment]
#### Validated on master branch commit `eda65b19d9893a033c681ab5b0045d7a0e29d6cb`

This has all of the node-name, node-ip, tls-san values, and node-external-ip values when set. When nothing is set, it correctly has the hostname and private ip.
