### ISSUE TITLE
[release-1.21] RKE2 apiserver cert is missing hostname SAN entries

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3961]
Tracking issue for fixing **RKE2 apiserver cert is missing hostname SAN entries** from RKE2 on branch **release-1.21** and **engine-1.21**:
* #3960
* https://github.com/rancher/rke2/issues/1739

**Comment by rancher-max** [comment]
Validated on release-1.21 branch commit `6acee2e2f5d5f3cf9da416baf321cefa7de8991c` using the same steps as on the 1.22 (master) issue.
