### ISSUE TITLE
Cluster options marked experimental

### ISSUE THREAD

**Issue by mjrist** [k3s-io/k3s#3964]
**Environmental Info:**
K3s Version: 
k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
Linux somehostname 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(2 more nodes running the same)

Cluster Configuration:
3 node HA embedded etcd

**Describe the bug:**
Not sure if a bug report for this is appropriate, but I would like some clarification here.

"k3s server --help" output lists the cluster options as experimental. 
![image](https://user-images.githubusercontent.com/59707001/131737381-8da80cf0-c620-441a-97a4-21a3765a67a4.png)

The documentation states that "K3s has added full support for embedded etcd as of release v1.19.5+k3s1." https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

Is this a documentation discrepancy or are the cluster features still considered experimental? Thanks in advance.

**Steps To Reproduce:**
Run "k3s server --help" and view output

**Expected behavior:**
I expected the cluster options not to be marked experimental.

**Comment by dereknola** [comment]
Good catch @mjrist these options are no longer experimental and should not be marked as such.

**Comment by mjrist** [comment]
Thanks @dereknola, that answers my question.

**Comment by rancher-max** [comment]
Validated on master branch commit `eda65b19d9893a033c681ab5b0045d7a0e29d6cb` that these are no longer marked experimental. I want to leave this open to backport the fix to 1.19, 1.20, and 1.21 branches.

**Comment by rancher-max** [comment]
This has been validated on all branches 1.19, 1.20, 1.21, and master and no longer lists these flags as experimental
