### ISSUE TITLE
https://get.k3s.io | sh - fails with '[ERROR]  download needs exactly 2 arguments' when DOWNLOADER is wget

### ISSUE THREAD

**Issue by DanielBanobreDopico** [k3s-io/k3s#3965]
**Environmental Info:**
K3s Version:  no matters

Node(s) CPU architecture, OS, and Version: no matters

Cluster Configuration: no matters

**Describe the bug:**

get.k3s.io script line number 359 don't works. Server is currently don't providing the 'Location' header who grep command is searching for. 

In addition, wget print header to stderr. It must be redirected: 
```
wget -SqO /dev/null https://github.com/k3s-io/k3s/releases/tag/v1.21.4+k3s1 2>&1 | grep -i Location
```

**Steps To Reproduce:**

There is no Location header:
```
wget -SqO /dev/null https://github.com/k3s-io/k3s/releases/tag/v1.21.4+k3s1
```

You must to redirect stderr:
```
wget -SqO /dev/null https://github.com/k3s-io/k3s/releases/tag/v1.21.4+k3s1 2>&1 | grep -e Location
```

- Installed K3s: 

**Expected behavior:**

'wget -O - https://get.k3s.io | sh -' must install K3S or print a error if don't find curl.

**Actual behavior:**

'wget -O - https://get.k3s.io | sh -' prints
```
[INFO]  Finding release for channel stable
[INFO]  Using v1.21.4+k3s1
socket-worker-b05e50fc.js as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.4+k3s1
socket-worker-b05e50fc.js/sha256sum-amd64.txt
[ERROR]  download needs exactly 2 arguments
```

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
fwiw this works with real curl or wget; just not the fake wget provided by busybox.
