### ISSUE TITLE
wrong permissions on /etc/rancher/k3s/k3s.yaml

### ISSUE THREAD

**Issue by notklaatu** [k3s-io/k3s#3969]
**Environmental Info:**
K3s Version: 
```
k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6
```

Node(s) CPU architecture, OS, and Version: 

```
Linux k100c 5.4.60-v8.1.el8 #1 SMP PREEMPT Sun Aug 23 02:58:38 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:

None yet, this is intended as my control plane and I've not set up nodes. Planning on 3 nodes total.

**Describe the bug:**

After installing K3s for the first time on a Pi4, it ended with this error:

```
Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
```

Solution:

```
$ sudo chmod 644 /etce/rancher/k3s/k3s.yaml
```

**Steps To Reproduce:**

- Installed K3s: 

```
$ curl -sfL https://get.k3s.io | sh -
```
**Expected behavior:**

Expected k3s to start without issue.

**Actual behavior:**

K3s told me to add boot args to /boot/cmdline.txt, which I did.
It also failed to start due to an unreadable k3s.yaml file, which I solved and have now started k3s successfully.

**Additional context / logs:**

This is on CentOS 8 running on a Pi 4.

**Comment by smerschjohann** [comment]
This is expected behavior. It is not secure to allow everyone on the system to use you cluster by default. You can change that behaviour using `--write-kubeconfig-mode "0644" ` as described here: https://rancher.com/docs/k3s/latest/en/installation/install-options/#options-for-installation-from-binary

Another option is becoming root: `sudo su -`

**Comment by notklaatu** [comment]
Brilliant, thank you!

**Comment by notklaatu** [comment]
> Quoted solution has a typo. It should be `$ sudo chmod 644 /etc/rancher/k3s/k3s.yaml`

Thank you. Fixed.

**Comment by brandond** [comment]
It's reproducible because it's working as designed.
