### ISSUE TITLE
ansible playbook for deployment

### ISSUE THREAD

**Issue by egeneralov** [k3s-io/k3s#397]
#### Hello.

Please, review my ansible role, which can be founded at [egeneralov/k3s](https://github.com/egeneralov/k3s).

#### Manualy tested cases:
- deployment with dedicated master
- deployment with default server mode
- deployment with slave nodes
- local path provisioner operability
- metrics server operability

All tested running in KVM vm's, located on same bridge.

**Comment by erikwilson** [comment]
Neat! We have this PR https://github.com/rancher/k3s/pull/217 which will hopefully be merged soon. I am not sure what the pros/cons are of the different approaches, if you have any feedback for the PR or would like to update it with future PRs that would be greatly appreciated.

**Comment by egeneralov** [comment]
i hope you are joking.

I saw the #217 and [itwars/k3s-ansible](https://github.com/itwars/k3s-ansible), but all, what i can see - not good ansible knowlege. Thanks to this guy for reminder about slurp module, but rest of his code - is very dirty.

Wait for PR from me, i need apply some changes to my role, and prepare and test on arm.

**Comment by itwars** [comment]
I'll dive into your playbook to update my *dirty* code.
