### ISSUE TITLE
Unable to dual-stack k3s API server

### ISSUE THREAD

**Issue by mrjester888** [k3s-io/k3s#3970]
**Environmental Info:**
K3s Version: k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:35:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
3 node, combined master/worker

**Describe the bug:**
Unable to start k3s API server on IPv6 or dual-stack tcp socket.  When setting the `--node-ip` to dual-stack, k3s-server process only bind to IPv4 tcp socket.

Added `--bind-address=::` to force it to bind to all IPs and get this error: 
`"starting kubernetes: preparing server: init cluster datastore and https: listen tcp: address :::6443: too many colons in address"`

Also tried with `--bind-address=*` (fails to start) and `--bind-address=[::]` (binds v4 only)

**Steps To Reproduce:**
Initialized new cluster with k3sup. 
`k3sup install \
    --host=dnsinf1.home.example.com \
    --tls-san dnsinf.home.example.com \
    --cluster \
    --k3s-version=v1.21.4+k3s1 \
    --merge \
    --local-path $HOME/.kube/dns-infra-config \
    --context=dns-infra \
    --user local-admin \
    --k3s-extra-args="--bind-address=:: --disable-network-policy --flannel-backend=none --disable servicelb --disable traefik --cluster-cidr=10.250.0.0/16,f250::/48 --service-cidr=10.251.0.0/16,f251::/112 --cluster-dns=10.251.0.10 --node-ip=10.8.10.201,2001:db8:10::201" \
    --ssh-key=$HOME/.ssh/id_ed25519`

Install fails. Check journalctl on new node.  Get this error.
`"starting kubernetes: preparing server: init cluster datastore and https: listen tcp: address :::6443: too many colons in address"`

**Expected behavior:**
The k3s-server process to listen on both IPv4 and IPv6

**Actual behavior:**
k3s-server process either binds to IPv4 only or fails to start.

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by adamcharnock** [comment]
I'm also encountering this on RKE2, `v1.21.5+rke2r1`.
