### ISSUE TITLE
Allow backing up etcd snapshots to work with an insecure s3 endpoint

### ISSUE THREAD

**Issue by onedr0p** [k3s-io/k3s#3972]
**Is your feature request related to a problem? Please describe.**

I am trying to take backups of etcd to an insecure (http only) endpoint.

**Describe the solution you'd like**

Allow backing up etcd snapshots to work with an insecure s3 endpoint

**Describe alternatives you've considered**

Nothing

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by bmdepesa** [comment]
Validated on master branch commit `086ca8ba6a3bd5d6204826b3866010d2d3741749`

* Set up a minio instance accessed over http 
* Started an etcd snapshot 
```
sudo k3s etcd-snapshot \
  --s3 \
  --s3-endpoint="url:9000" \
  --s3-bucket="newbucket" \
  --s3-access-key="example" \
  --s3-secret-key="example" \
  --s3-insecure
```
* Snapshot is successfully stored in minio
