### ISSUE TITLE
etcd member management controller

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#3973]
Currently, etcd member management is a bit haphazard, with member addition being performed when a K3s server node is started for the first time and `--disable-etcd` is not true, or a K3s server node is joined to the cluster with `--disable-etcd` not being set to true.

etcd member removal is performed when a node is deleted, which can be problematic in cases where the underlying infrastructure is deleted before the node object is deleted from the cluster. For example, see: https://github.com/rancher/rancher/issues/34488

What will be added and tracked per this issue is a new `etcd member management` controller, which has the sole purpose in life of managing/reconciling member management within the cluster. This will be a leader elected controller and run on the server nodes.

The controller will have the obligations as defined below: 
1. When a node is removed from the cluster, remove the node from the etcd member list as well within the etcd cluster.
2. Allow for manual removal of an etcd member from the cluster via an annotation interface, to be defined.
3. ~Periodically (based on cache rehydration and/or node updates/changes) reconcile the etcd cluster member list against the node list within the cluster, to ensure that we are removing all nodes that should not be members of the cluster.~
(Additional design discussion must take place around the periodic reconciliation as this can be potentially extremely dangerous to the data integrity of the cluster)

**Comment by rancher-max** [comment]
Performed the steps mentioned in https://github.com/k3s-io/k3s/issues/4002#issuecomment-920339611 but on master branch commit `086ca8ba6a3bd5d6204826b3866010d2d3741749`.
