### ISSUE TITLE
How to configure kubelet to adjust allocatable resources

### ISSUE THREAD

**Issue by venom85** [k3s-io/k3s#3979]
Hello! I am trying to find a way to adjust the allocatable resources on the nodes in my K3s cluster, and I have completely struck out. I am using Raspberry Pi 4s (3x4GB models for the control plane, 2x8GB for the workers), and while the memory is mostly available to pods, the CPU is not. I only get 1 out of 4 CPU cores on any node for pods to use. Given the lack of other workloads and ongoing monitoring of CPU utilization, I feel I can tune that to allow for better balancing of my cluster workloads.

My question here is if there is a way I can do that. I can find information about setting kube-reserved and system-reserved values with kubelet in vanilla Kubernetes, but I can't seem to find a way to do that in K3s. Thanks for the help!

Host OS: Fedora 34 ARM64
K3s version: v1.20.6+k3s1

Note that I tried [asking this same question on Rancher's K3s forum](https://forums.rancher.com/t/how-to-configure-kubelet-to-change-nodes-allocatable-resources/21006), but as you can see, I didn't get any replies after a couple of weeks. Hopefully this is still an appropriate place to ask, since I'm not sure where else to go.

Let me know if any additional information is needed.

**Comment by brandond** [comment]
What part of setting the reserved and allocatable flags are you having trouble with? Note that the flags just impact the scheduler, not the actual amount available to the pods. For that you need to set cpu and memory limits.

**Comment by venom85** [comment]
So, what I can't seem to figure out is how to configure kubelet within K3s. I found /var/lib/rancher/k3s/agent/kubelet.kubeconfig, but that gets overwritten every time I restart the K3s service. Is there something I'm missing about how to manage the finer details of kubelet?

Also, I'm fairly new to Kubernetes in general, so I'm keenly aware of the possibility that I'm way off base here. If I shouldn't be worrying about this at all, or if there's a better way to manage allocatable resources, I'm all for knowing.

**Comment by brandond** [comment]
It sounds like you want to pass extra flags to the kubelet. Have you seen:
https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#customized-flags

**Comment by venom85** [comment]
I did see that when I first set up the cluster, and then apparently I forgot about it entirely. That's embarrassing.

One last clarification, and then this should be a very easy close: is that an adjustment that can be done on an existing node, or do I have to remove and re-add a node with the necessary flags set?
