### ISSUE TITLE
Can't pull the images after starting the k3s

### ISSUE THREAD

**Issue by sabir-piludiya** [k3s-io/k3s#3981]
I have set up k3s in CentOS 7 and started the k3s cluster. However, when I listed the pods, It stuck on the ContainerCreating status as follow:
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   local-path-provisioner-5ff76fc89d-bnvvk   0/1     ContainerCreating   0          8s
kube-system   coredns-7448499f4d-dzchp                  0/1     ContainerCreating   0          8s
kube-system   metrics-server-86cbb8457f-7jj5c           0/1     ContainerCreating   0          8s
```

By describing one of the **coredns** pod I found:
```
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               35s                default-scheduler  Successfully assigned kube-system/coredns-7448499f4d-dzchp to ab-cdxxx-yy
  Warning  FailedCreatePodSandBox  15s (x2 over 33s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": pulling from host registry-1.docker.io failed with status code [manifests 3.1]: 403 Forbidden
```
If anyone can provide a workaround for this issue.

**Comment by ChristianCiach** [comment]
You get a "403 Forbidden" response from docker hub when trying to pull the image.

Are you using a custom `registries.yaml`? If yes, are your credentials correct? Or did you hit the rate-limit of docker hub (but I think the response status code would be different in this case)?

Anyway. You can completely workaround this issue by deploying the airgap-tarball of k3s which contains all these images.

**Comment by sabir-piludiya** [comment]
No @ChristianCiach I'm not using `registries.yaml`. However, https_proxy was set in the environment variables. Image can't be pulled still even after unsetting the variables.!

**Comment by brandond** [comment]
Something in your environment is preventing your host from accessing Docker Hub. Do you need to authenticate to your proxy?

**Comment by rodrigofvale** [comment]
same problem here. after rebooting the server started to get same error in all pods.

NAME                                   READY   STATUS              RESTARTS       AGE
vocabulary-master-5564798485-4sdg4     0/1     ContainerCreating   1 (13m ago)    18h

docker info shows 
Insecure Registries:
  192.168.86.59:32000
  192.168.86.59:5000
  127.0.0.0/8

registries.yaml shows
mirrors:
  "192.168.86.59:5000":
    endpoint:
      - "http://192.168.86.59:5000"

kubectl describe pods
  Warning  FailedCreatePodSandBox  11m                    kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "cfa3acf5933e85440d8d6ed8f64fe2eddb4e99cea0cc2bcfab19ac33c995bd30" network for pod "vocabulary-master-5564798485-4sdg4": networkPlugin cni failed to set up pod "vocabulary-master-5564798485-4sdg4_default" network: CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "cfa3acf5933e85440d8d6ed8f64fe2eddb4e99cea0cc2bcfab19ac33c995bd30"
  Warning  FailedCreatePodSandBox  7m48s (x52 over 11m)   kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "77999e146db1354a4961a0e8b8985a7a9b236eed756233dec8e4e517d7303488" network for pod "vocabulary-master-5564798485-4sdg4": networkPlugin cni failed to set up pod "vocabulary-master-5564798485-4sdg4_default" network: CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "77999e146db1354a4961a0e8b8985a7a9b236eed756233dec8e4e517d7303488"
  Normal   SandboxChanged          2m48s (x125 over 12m)  kubelet  Pod sandbox changed, it will be killed and re-created.


any ideas why CNI stopped working?

**Comment by brandond** [comment]
@rodrigofvale that sounds like a different error completely, nothing in there at all about failing to pull images. Would you please open a new issue, and fill out the issue template with information about your cluster?

**Comment by caroline-suse-rancher** [comment]
Closing due to age
