### ISSUE TITLE
Migrate sqlite data to etcd when initializing the cluster

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3982]
It would be nice if we could migrate data from sqlite to managed etcd.
* If an sqlite datastore is found on disk when starting a node with --cluster-init, migrate all the etcd keys into the single-node etcd cluster
* The sqlite database should be moved aside when this is done so that migration does not attempt to run multiple times
* Migrating from external SQL datastores is currently out of scope

**Comment by rancher-max** [comment]
Validated by migrating both during an upgrade and by restarting the service in a fresh install, but using `--cluster-init`, using master branch commit `eda65b19d9893a033c681ab5b0045d7a0e29d6cb`

- Had workloads deployed both before and after migration 
- Was able to successfully add both server and agent nodes after migration
