### ISSUE TITLE
[release-1.21] etcd-expose-metrics setting replaces loopback listener with exposed listener

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3984]
Backport fix for **etcd-expose-metrics setting replaces loopback listener with exposed listener** on branches **release-1.21** and **engine-1.21**
* #3983

**Comment by rancher-max** [comment]
Confirmed on release-1.21 commit `863512e0555662e4bc72c3722c13c04c62e92386` using the same confirmation as in https://github.com/k3s-io/k3s/issues/3983#issuecomment-919341861
