### ISSUE TITLE
k3s failed start  server 

### ISSUE THREAD

**Issue by rockylee3128** [k3s-io/k3s#399]
when I want add a node for master 
to shows that
W0426 14:55:40.805492   24201 kubelet_getters.go:279] Path "/var/lib/rancher/k3s/agent/kubelet/pods/1ec285fc-67ec-11e9-959c-fa163e1da570/volumes" does not exist
W0426 14:55:40.805559   24201 kubelet_getters.go:279] Path "/var/lib/rancher/k3s/agent/kubelet/pods/1e8834ed-67ec-11e9-959c-fa163e1da570/volumes" does not exist
E0426 15:00:39.031284   24201 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache/index0/size: no such file or directory
E0426 15:05:39.028750   24201 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache/index0/size: no such file or directory

and master shows 
[root@kwephicprd01665 ~]# ./k3s-arm64 kubectl get node
NAME              STATUS   ROLES    AGE     VERSION
kwephicprd01664   Ready    <none>   166m    v1.14.1-k3s.4
kwephicprd01665   Ready    <none>   7d23h   v1.14.1-k3s.4

I wonder is this the normal function

**Comment by erikwilson** [comment]
Which kernel & device is this? Is it actually causing an issue or does everything work okay otherwise?

**Comment by b3nw** [comment]
getting the same here on all 3 worker nodes
 v1.15.4-k3s.1
Linux k3-pi-3.local 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

`E1007 06:14:53.194720    2788 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory
`

**Comment by zimme** [comment]
As for the `E1007 06:14:53.194720 2788 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory` error I don't believe it affects anything based on an issue I found in another project. It's just rpi's that don't have L1/L2 caching and that's why this error is shown and there are other ARM/ARM64 boards that do have L1/L2 cache so that code can't be removed, though they could probably add a check instead if printing an error.

https://github.com/google/cadvisor/issues/2229

**Comment by alexellis** [comment]
I also got an error like this:

```
machine.go:331] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache
```

It prints out in the journal over and over. Perhaps we can silent this error with a patch @ibuildthecloud ? :thinking:

**Comment by brandond** [comment]
@alexellis what kernel and architecture are you on? Is this also on a ARM chipset with no cache exposed via sysfs?

**Comment by alexellis** [comment]
Yes it's RPi4 with Raspbian

**Comment by jimangel** [comment]
This error exists for me as well building upstream k8s via kubeadm (v1.18.3) on RPi4. If a patch does get created, it might be nice to PR it back upstream. 😄

**Comment by brandond** [comment]
Upstream has already moved this to info as per https://github.com/google/cadvisor/pull/2550 - unless @rockylee3128 has some additional error logs to show this should be resolved when the vendored cadvisor is next updated.

**Comment by brandond** [comment]
Closing due to age.
