### ISSUE TITLE
Removing default role labels on master nodes

### ISSUE THREAD

**Issue by jorikseldeslachts** [k3s-io/k3s#3998]
I am trying to remove the default labels from master nodes using kubectl. Custom labels can be set and removed like this without any problems, but those default labels seem like they can not be removed? On agent nodes I can set and remove labels without any issues.

I am using the following command:

```
kubectl label node k8s-node-1 "node-role.kubernetes.io/control-plane-"
kubectl label node k8s-node-1 "node-role.kubernetes.io/etcd-"
```

```
NAME         STATUS   ROLES                       AGE     VERSION
k8s-node-1   Ready    control-plane,etcd,master   21h     v1.21.4+k3s1
k8s-node-2   Ready    control-plane,etcd,master   21h     v1.21.4+k3s1
k8s-node-3   Ready    control-plane,etcd,master   21h     v1.21.4+k3s1
...
```

I would like to replace the default roles with just `master`.

System:
- Ubuntu 20.04 VM on Proxmox
- K3s version v1.21.4+k3s1
- 3 master cluster with embedded Etcd database.

**Comment by brandond** [comment]
The etcd, control-plane, and master role labels are managed by the supervisor and cannot be removed. Note that the master role is deprecated and will be removed completely in 1.23; you should start transitioning to control-plane as soon as possible.
