### ISSUE TITLE
Option to configure http proxy settings doesn't work at installation

### ISSUE THREAD

**Issue by nicolasbrechet** [k3s-io/k3s#4008]
**Environmental Info:**
K3s Version: v1.22.1+k3s-699ea165

Node(s) CPU architecture, OS, and Version: amd64, Ubuntu 2104

Cluster Configuration:

1 master, 1 node

**Describe the bug:**

As mentionned in #2026 and #3552, a new feature has been added to configure HTTP proxy settings, for Containerd. 
However, these settings are not taken into account in the installation script, as only the "_proxy" environment variables are written in the service environment file.

**Steps To Reproduce:**

- Install K3s master node with INSTALL_K3S_COMMIT=699ea165231cf6d665425c50ff5c75e1831f4afb and variables prefixed with "CONTAINERD"
- On the master node, check the content of the /etc/systemd/system/k3s.service.env 

**Expected behavior:**

the /etc/systemd/system/k3s.service.env should contains all environment variables prefixed with CONTAINERD

**Actual behavior:**

the /etc/systemd/system/k3s.service.env doesn't contain the environment variables prefixed with CONTAINERD

**Additional context / logs:**

@rancher-max you've tested the fact that the environment variables are used when the k3s service starts after you manually modify the service definition, could you test with my PR that it works correctly from the install script ?

**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
Validated on the PR itself that this is working as expected. See comments there. Thank you again for the contribution!
