### ISSUE TITLE
Check-config causes false-negative on pure cgroup V2 system

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4013]
As per @rowanthorpe:

> Problem:
> In check-config.sh assumptions are made about cgroups v1/v2/hybrid, causes false-negative on pure V2 system.

**Comment by rancher-max** [comment]
#### Validated using master branch commit `debb508643c46c253d750903dc2ae263dce55127`

- Cgroups v2:
```
...
Generally Necessary:
- cgroup hierarchy: cgroups V2 mounted, cpu|cpuset|memory controllers status: good
...
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
...
Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_CGROUP_NET_PRIO: enabled
...
```
- Hybrid cgroups:
```
- cgroup hierarchy: cgroups Hybrid mounted, cpuset|memory controllers status: bad (fail)
    (for cgroups V1/Hybrid on non-Systemd init see https://github.com/tianon/cgroupfs-mount)
```

Because of this result on hybrid, I believe this isn't fully working. This check previously passed on v1.21.4+k3s1: `- cgroup hierarchy: properly mounted [/sys/fs/cgroup]`

This one was tested on a simple Ubuntu 20.04 LTS system.

**Comment by brandond** [comment]
@rowanthorpe are you available to address the regressions?

**Comment by rowanthorpe** [comment]
OK @brandond I will try to look at it this weekend (will need to get back into mental context a bit - the PR is from April).

**Comment by rowanthorpe** [comment]
I was able to access an Ubuntu Focal system to check the layout of a hybrid system, and saw that it was just a silly assumption I'd made about commonality of file-format between the sysfs and procfs pseudo-files. It required a tweak to the regex to fix it for hybrid, and unless I missed something else surprising it would fix the same error on pure v1 systems too (I have no access to one to verify). Am opening a pull-request now.

**Comment by rancher-max** [comment]
Validated in v1.22.2-rc1+k3s1 that this is working in all of v1, hybrid, and v2 cgroup systems 🎉 

v1:
```
Generally Necessary:
- cgroup hierarchy: cgroups V1 mounted, cpuset|memory controllers status: good
```

Hybrid:
```
Generally Necessary:
- cgroup hierarchy: cgroups Hybrid mounted, cpuset|memory controllers status: good
```

v2:
```
Generally Necessary:
- cgroup hierarchy: cgroups V2 mounted, cpu|cpuset|memory controllers status: good
```
