### ISSUE TITLE
Joining etcd members stop prematurely

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4017]
After several seconds of operation, etcd cluster members other than the first member stop their etcd instance:

```
Sep 15 01:56:44 ip-172-31-25-17 k3s[41412]: time="2021-09-15T01:56:44Z" level=info msg="stopping etcd"
Sep 15 01:56:44 ip-172-31-25-17 k3s[41412]: {"level":"info","ts":"2021-09-15T01:56:44.965Z","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"ip-172-31-25-17-2d79e983","data-dir":"/var/lib/rancher/k3s/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://172.31.25.17:2379"]}
```

It appears that we're using the wrong context to run the joining etcd member, and it is getting cancelled early and shutting down when it should not. The change to stop the cluster member was introduced in https://github.com/k3s-io/k3s/pull/3975 but some other latent bug is causing the context to be cancelled early.

This wasn't caught by CI because CI doesn't test multi-server clusters.

**Comment by rancher-max** [comment]
Validated this is working again in etcd multi-server clusters on master commit `086ca8ba6a3bd5d6204826b3866010d2d3741749`
