### ISSUE TITLE
Agent API loadbalancer obstructs network errors

### ISSUE THREAD

**Issue by nabam** [k3s-io/k3s#4020]
**Environmental Info:**
K3s Version: v1.20.6+k3s1

Node(s) CPU architecture, OS, and Version: x86_64, Linux, kernel 5.4.81

Cluster Configuration: 3 servers, 201 agents

**Describe the bug:**

We spend quite some time trying to troubleshoot why k3s agent can't connect to the API server. Only error logs it was producing were:
```
level=error msg="Failed to retrieve agent config: CA cert validation failed: Get \"https://127.0.0.1:34605/cacerts\": read tcp 127.0.0.1:42924->127.0.0.1:34605: read: connection reset by peer"
```
In a while we enable debug logs and turned out that the actual problem was related to dns infrastructure:
```
level=debug msg="Dial error from load balancer: dial tcp: lookup api.example.com: no such host"
```
I suggest to change log level for dial error to "error" to avoid confusion as "CA cert validation failed" error obfuscates network issues https://github.com/k3s-io/k3s/blob/ac507e530d134fbfa15cff90d66c0cb8c71801a2/pkg/agent/loadbalancer/loadbalancer.go#L132

**Comment by nabam** [comment]
it's still relevant, fix is tiny, can make a PR if it's accepted

**Comment by brandond** [comment]
The reason this is only logged at Debug level is that it can be VERY noisy when a cluster member is down, to the point of obscuring other more meaningful messages. There may be some way to log initial connection errors at a higher log level, but it hasn't been a priority to date. We'd welcome a PR that resolves the issue without creating excessive log spam during cluster maintenance.
