### ISSUE TITLE
Pods of Kube system are stuck in containercreating and prompt no such host

### ISSUE THREAD

**Issue by fengzhibin** [k3s-io/k3s#4026]
**Environmental Info:**
K3s Version: 
k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
Linux localhost 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

Cluster Configuration:
1 servers 1 agents

**Describe the bug:**
![image](https://user-images.githubusercontent.com/12097229/133537116-7e0071ae-0e4d-4e72-9388-a5016afd9255.png)

After executing the get.k3s.io installation script, all pods under Kube system are stuck in the containercreating state. View the status of pods through describe and see the following information：
`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: no such host`

I tried to check whether the registry-1.docker.io domain name can be accessed through curl and found no problem
![image](https://user-images.githubusercontent.com/12097229/133536907-589b2198-c60e-4097-a5b2-2344a6c931a4.png)

I tried to add the --resolv conf = /etc/resolv conf option, but the problem was not solved.
![image](https://user-images.githubusercontent.com/12097229/133537540-ce53dfbb-ca5d-415f-bc8c-9d1926d8ac66.png)

I tried to bind the registry-1.docker.io domain name through the /etc/host file. After restarting the k3s service, I checked the description of pods. I did not continue to prompt that the registry-1.docker.io domain name could not be resolved, but reported that other domain names could not be resolved
![image](https://user-images.githubusercontent.com/12097229/133537372-633a5b85-de95-49f4-a4c7-550cf8294adb.png)

**Steps To Reproduce:**
After executing the following script:
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 644 --resolv-conf /etc/resolv.conf" sh -`

**Additional context / logs:**
`  Warning  FailedCreatePodSandBox  15h (x414 over 17h)   kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: no such host
  Warning  FailedCreatePodSandBox  4m2s (x161 over 39m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: no such host
`

**Comment by brandond** [comment]
Can you share more information about your environment? Do you have a private DNS server, firewall, or proxy in your environment that is blocking your access when attempting to reach registry-1.docker.io? I've seen cases where the DNS server can't be reached and you get timeout errors, but something in your environment is claiming that registry-1.docker.io does not exist.

**Comment by fengzhibin** [comment]
> Can you share more information about your environment? Do you have a private DNS server, firewall, or proxy in your environment that is blocking your access when attempting to reach registry-1.docker.io? I've seen cases where the DNS server can't be reached and you get timeout errors, but something in your environment is claiming that registry-1.docker.io does not exist.

My environment is vagrant + VirtualBox. The virtual machine operating system is Debian 10. The VirtualBox is configured with 
--natdnsproxy1 option as on 
--natdnshostresolver1 option as on

Vagrant version:2.2.18
Virtualbox version:6.1.26 r145957
Debian version:Linux version 5.10.0-8-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110

My VirtualBox environment is configured with two virtual network cards, one is NAT and the other is host only. The virtual network card of NAT is used as the gateway in the virtual machine, while the network card of host only cannot be used as the gateway to request to the public network

![image](https://user-images.githubusercontent.com/12097229/133710225-8b74ad5f-9d77-49ea-9243-1883dcda9fe3.png)




There is no problem running docker + docker compose in my environment. I also try to set k3s to use docker, but Debian 11 does not support docker of version 19.03. So I can only use container as the runtime. I try to modify the /etc/ranger/k3s/registers.yaml file and replace the domain name of registry-1.docker.io with docker.mirrors.ustc.edu.cn. After restarting the k3s service, check the description of pods and prompt 
`dial TCP: lookup docker.mirrors.ustc.edu.cn: no such host.`
However, if I request the domain name of docker.mirrors.ustc.edu.cn through curl, there is no problem

**Comment by fengzhibin** [comment]
The problem was solved when I turned off both options of the virtual box
--natdnsproxy1
--natdnshostresolver1

![image](https://user-images.githubusercontent.com/12097229/133869657-b866cea9-6b20-4779-9db2-00ae91609c3c.png)

No more no such host errors have occurred
![image](https://user-images.githubusercontent.com/12097229/133869532-e5dbe8da-06e8-44bb-bb2c-209c2e9cb96c.png)
![image](https://user-images.githubusercontent.com/12097229/133869745-1a8da170-c018-4b38-aea2-26e0c6606fae.png)

However, in some scenarios where vagrant is used, the -- natdnsproxy1 and -- natdnshostresolver1 options need to be set to on to solve the problem of DNS parsing exceptions in some scenarios

[https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working](url)
