### ISSUE TITLE
Change etcd to external db

### ISSUE THREAD

**Issue by jbpoint** [k3s-io/k3s#4046]
Hi,

is there an easy way to change the datastore option from etcd to an external database without loosing any data?

Thanks

**Comment by brandond** [comment]
We recently added support for migration from sqlite to etcd; this is currently the only supported path.

**Comment by werdnum** [comment]
> We recently added support for migration from sqlite to etcd; this is currently the only supported path.

Is there any info anywhere on how to do that? I didn't find anything in the documentation.

**Comment by brandond** [comment]
Just add --cluster-init to the flags of the single control-plane node.

**Comment by werdnum** [comment]
Any updates on this? I migrated my data store to the embedded etcd for the native backups, but my hardware can't support the I/O requirements of etcd and I'd like to migrate back to a traditional database.

**Comment by brandond** [comment]
Only sqlite -> etcd is supported, not etcd back to sqlite.

**Comment by Serverfrog** [comment]
Nice, so Documented is that SQLite is the default, and here is that the it migrates from SQLite to external etcd.
So i restart with systemd with --cluster-init and the `datastore-endpoint`...

Now i have an empty cluster...

**Comment by brandond** [comment]
> So i restart with systemd with --cluster-init and the datastore-endpoint...

No, don't do that.

--cluster-init starts a new embedded etcd instance, and will copy over data from sqlite, if any is present. 

--datastore-endpoint overrides the embedded etcd instance, and points at the requested datastore, without enabling any migration.

Don't use both together, it won't do what you want.

**Comment by Serverfrog** [comment]
So what would be the migration way to migrate from internal SQLite to external etcd?
Because i want to switch out the Main node (due to the fact i want to transfer them from a VM to an LXC due to PCI devices) 

Or is it only possible to migrate from an Internal SQLite to an internal etcd?
