### ISSUE TITLE
Atomic writing of cert files

### ISSUE THREAD

**Issue by ibuildthecloud** [k3s-io/k3s#405]
We are not currently using an atomic approach to writing files for certs so it is possible to end up with a corrupted (incomplete or zero length file) cert on disk.  We should be writing to a tempfile and moving to the target.

**Comment by ibuildthecloud** [comment]
Related to #359

**Comment by davidnuzik** [comment]
@ibuildthecloud is this done? Do we need any tests/checks or can we close this?

**Comment by davidnuzik** [comment]
Needs checking if this needs work in RKE2 as well - we'll want this covered in both k3s and RKE2.

**Comment by caroline-suse-rancher** [comment]
Closing due to age
