### ISSUE TITLE
Sometimes traefik LB service is missing agent node ips

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#4052]
**Environmental Info:**
K3s Version: 

v1.21.4 up through 1.22.2

Node(s) CPU architecture, OS, and Version: 

Centos8 + selinux enforcing: `Linux ip-172-31-10-80.us-east-2.compute.internal 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 servers, 1 agent

**Describe the bug:**

The agent node's ip is not being added to the list of IPs in the traefik LoadBalancer service. This causes created ingress resources to also not have this node's ip in its list of addresses. In a simple test, I was still able to see querying the IP working even without it in the list.

**Steps To Reproduce:**

- Install k3s and add an agent node

**Expected behavior:**

The loadbalancer resource should have all node ips in its list.

**Actual behavior:**

It does not

**Additional context / logs:**

```
NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP                              PORT(S)                      AGE
service/kube-dns         ClusterIP      10.43.0.10     <none>                                   53/UDP,53/TCP,9153/TCP       3h41m
service/metrics-server   ClusterIP      10.43.98.56    <none>                                   443/TCP                      3h41m
service/traefik          LoadBalancer   10.43.237.86   <server2 ip>,<server1 ip>,<server3 ip>   80:32677/TCP,443:30322/TCP   3h40m

NAME                                              STATUS   ROLES                       AGE     VERSION            INTERNAL-IP    EXTERNAL-IP      OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
node/ip-172-31-0-120.us-east-2.compute.internal   Ready    <none>                      3h32m   v1.22.2-rc1+k3s1   172.31.0.120   <agent1 ip>      CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.5.5-k3s1
node/ip-172-31-0-97.us-east-2.compute.internal    Ready    control-plane,etcd,master   3h36m   v1.22.2-rc1+k3s1   172.31.0.97    <server3 ip>     CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.5.5-k3s1
node/ip-172-31-8-41.us-east-2.compute.internal    Ready    control-plane,etcd,master   3h37m   v1.22.2-rc1+k3s1   172.31.8.41    <server2 ip>     CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.5.5-k3s1
node/ip-172-31-9-89.us-east-2.compute.internal    Ready    control-plane,etcd,master   3h42m   v1.22.2-rc1+k3s1   172.31.9.89    <server1 ip>     CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.5.5-k3s1
```

**Backporting**

- [x] Needs **forwardporting** to 1.22

**Comment by brandond** [comment]
It looks like the ServiceLB controller isn't consistently adding the node's IP to the service when a new node joins the cluster. The logs show it creating a new pod for the deployment, but the service doesn't get updated with the new pod's node address. I am guessing there's a stale cache somewhere; this will need to be investigated.

When we touch the servicelb code to fix this, we should also add events to make this more traceable in the future.

**Comment by cwayne18** [comment]
Can we verify if this is still something we're seeing? cc @rancher-max

**Comment by rancher-max** [comment]
This doesn't appear to be an issue anymore. Tried on 10 clusters using different OSes.
