### ISSUE TITLE
Broken `sha256sum-amd64.txt` files in recent releases

### ISSUE THREAD

**Issue by whynowy** [k3s-io/k3s#4054]
Broken `sha256sum-amd64.txt` files in recent releases, which made installation via https://get.k3s.io fail.

Click `sha256sum-amd64.txt` in the release pages.

https://github.com/k3s-io/k3s/releases/tag/v1.21.5%2Bk3s1
https://github.com/k3s-io/k3s/releases/tag/v1.21.2%2Bk3s1

**Comment by brandond** [comment]
We're seeing the same thing with the sha256 files across all of our repos. There appears to be some sort of outage with the GitHub artifacts CDN, which is hosted by fastly in front of S3. I don't believe there's anything we can do about it.

**Comment by DanSibbernsen** [comment]
> We're seeing the same thing with the sha256sum files across all of our repos. There appears to be some sort of outage with the GitHub artifacts CDN, which is hosted by fastly in front of S3. I don't believe there's anything we can do about it.

That's a darn shame. Do people sometimes get into the habit of hosting these files locally? I'm still experimenting with installing k3s to host my Rancher instance, so was relying heavily on this for development today.

**Comment by jorgeghm** [comment]
temp work around while is fixed is to disable hashes verification on install script. Lines 546 and 554

    546     #download_hash
    547 
    548     if installed_hash_matches; then
    549         info 'Skipping binary downloaded, installed k3s matches hash'
    550         return
    551     fi
    552 
    553     download_binary
    554     #verify_binary
    555     setup_binary

**Comment by davidnuzik** [comment]
Note: Also is breaking internal Rancher QA automation

**Comment by wranders** [comment]
I opened a ticked with Github Support about 2 hours ago (~1730EST). Seems to be effecting the same file on all releases, so no ability to use an older release. I started experiencing problems around 1400EST and relayed that information to them in the ticket.

**Comment by brandond** [comment]
I have an issue open too - https://support.github.com/ticket/personal/0/1319404 and we've reached out to CNCF to see if they can shake anyone loose.

**Comment by Luke31** [comment]
> temp work around while is fixed is to disable hashes verification on install script. Lines 546 and 554
> 
> ```
> 546     #download_hash
> 547 
> 548     if installed_hash_matches; then
> 549         info 'Skipping binary downloaded, installed k3s matches hash'
> 550         return
> 551     fi
> 552 
> 553     download_binary
> 554     #verify_binary
> 555     setup_binary
> ```

Thank you.
Temporary workaround in case you use `curl -sfL https://get.k3s.io | sh -` in CI:

```
curl -sfL https://get.k3s.io | sed "s/download_hash$/#download_hash/" | sed "s/verify_binary$/#verify_binary/" | sh -
```

Test to verify it's working correctly and only replacing these two lines:
```
curl -sfL https://get.k3s.io | sed "s/download_hash$/#download_hash/" | sed "s/verify_binary$/#verify_binary/" > disabled_ver.sh
curl -sfL https://get.k3s.io > original.sh
diff original.sh disabled_ver.sh
546c546
<     download_hash
---
>     #download_hash
554c554
<     verify_binary
---
>     #verify_binary
```

**Comment by thibgc** [comment]
All the `sha256sum-amd64.txt` of 1.21 (from 1.21.0 to 1.21.5) seem to be working again, for example:

https://github.com/k3s-io/k3s/releases/download/v1.21.5%2Bk3s1/sha256sum-amd64.txt seems to work again

I haven't tried other versions, though, but this is encouraging.

**Comment by brandond** [comment]
GitHub resolved my ticket just before midnight last night:
> Thanks for your patience while we worked on this!
>
>I just wanted to let you know that we've deployed a fix that should have resolved the issue.
>
>Sorry again for the trouble, and please let us know if there's anything else we can do.

**Comment by Keith-Nowosielski-SJSU** [comment]
This appears to be broken again, I'm unable to install any v1.25.x that I've tried. 
Output for each attempt: 

[INFO]  Finding release for channel v1.25
[INFO]  Using v1.25 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25/sha256sum-amd64.txt

I curl the URL shown here or goto it in a web browser : Not Found
I've tried v.1.25.0, 1.25.10 I think I tried one other also and no dice I get this same thing.

**Comment by brandond** [comment]
Do you perhaps have something blocking your access to the channel server? v1.25 is not a valid release. You should see something like this:

```console
systemd-node-1:/ # curl -sfL get.k3s.io | INSTALL_K3S_CHANNEL=v1.25 sh -s -
[INFO]  Finding release for channel v1.25
[INFO]  Using v1.25.11+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.11+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.25.11+k3s1/k3s
```

**Comment by Keith-Nowosielski-SJSU** [comment]
> Do you perhaps have something blocking your access to the channel server? v1.25 is not a valid release. You should see something like this:
> 
> ```
> systemd-node-1:/ # curl -sfL get.k3s.io | INSTALL_K3S_CHANNEL=v1.25 sh -s -
> [INFO]  Finding release for channel v1.25
> [INFO]  Using v1.25.11+k3s1 as release
> [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.11+k3s1/sha256sum-amd64.txt
> [INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.25.11+k3s1/k3s
> ```

You say it's not a valid release but then show me an output using that version? 
It stops for me at the downloading output. Curl the URL for the SHA file where it stopped and it comes back with "Not Found" same as if you use the URL in a browser. I'm using version 1.26.5 on the stable channel because I couldn't get any of the v1.25.x versions to work, they all had this problem. I hacked the script to download the correct files for 1.25.11 to install but then I couldn't join the nodes into an etcd cluster which does work in version 1.26.5. I wanted to use 1.25 so I could be on a "supported" implementation. I had to pull the chart and modify it to install rancher because anything > 1.26 isn't supported.

**Comment by brandond** [comment]
Please pay attention to the difference between channels and releases. `v1.25` is a channel, not a release. In the example above, the 1.25 channel served the `v1.25.11+k3s1` release, which was successfully downloaded and installed.

**Comment by brandond** [comment]
> I'm using version 1.26.5

This is not a valid k3s release version. A k3s release, targetable with the INSTALL_K3S_RELEASE environment variable, would be something like `v1.26.5+k3s1` - or any other release listed on GitHub.

**Comment by Keith-Nowosielski-SJSU** [comment]
Okay, well you shouldn't have said it's not a valid version release when I said 1.25.x, the "X" meaning any version within the 1.25 releases or channel. It doesn't work if i let the channel choose or if I specify one explicitly. It gives me the output I described in my original comment. I've spent hours on this IT DOESN'T WORK. Why would I be able to get the latest one 1.26.5 and not 1.25. Yes I know 1.25 isn't a valid version. When I say 1.25 I mean any 1.25 release. 

I guess it doesn't matter at the point. I wanted to use this version because the helm chart demands it and I would rather use the supported implementation, however even after forcing it to install it didn't work properly like version 1.26 does, so I guess I'm going with the unsupported setup which will severely affect my ability to determine if I can use this in a production environment and purchase support.

**Comment by brandond** [comment]
You can add `x` to the sh flags to see why you're unable to resolve the release from the channel server: `curl -sfL get.k3s.io | INSTALL_K3S_CHANNEL=v1.25 sh -xs -` - and post the resulting output to see where things are failing.

Most likely something is preventing you from hitting the channel server, in which case you can just test that request by itself: `curl -Ssv https://update.k3s.io/v1-release/channels/v1.25`
