### ISSUE TITLE
Bad permissions in `/run/k3s`

### ISSUE THREAD

**Issue by xlejo** [k3s-io/k3s#4056]
Hi. Actually, the `/run/k3s` directory by default owner root and having 0711 permissions, allow unprivileged users list directories in `/run/k3s/containerd/io.containerd.runtime.v2.task/` directory.

For example: `/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/adc5e646b2e916e7055d44feafa75551d7d31af47b88676273d806b792fe406a/rootfs`.

In some case allowing write files in this location if some folder have 0777 permissions.

It's normal?

This issue is solved by simply doing `chmod 0700 /run/k3s`.

Thanks!

**Comment by brandond** [comment]
K3s itself does not create this directory or manage its permissions. The containerd state directory is created with 0711 permissions by containerd itself during startup. If you think these permissions are overly broad, I would recommend creating an issue upstream:
https://github.com/containerd/containerd/blob/release/1.4/runtime/v2/manager.go#L65

**Comment by brandond** [comment]
I believe this is resolved upstream by GHSA-c2h3-6mxw-7mvq.
