### ISSUE TITLE
Update RootlessKit to v0.14.5

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4061]
From @AkihiroSuda 
> Update RootlessKit to v0.14.5
> Release notes: https://github.com/rootless-containers/rootlesskit/releases

**Comment by AkihiroSuda** [comment]
Seems already updated

https://github.com/k3s-io/k3s/blob/28be0de4e81a20608f9dbb5729543a89aa936711/go.mod#L115

**Comment by brandond** [comment]
Yes, just created this for issue tracking.

**Comment by rancher-max** [comment]
Rootless was validated as part of the 1.22 release in https://github.com/k3s-io/k3s/issues/3900#issuecomment-925160289, so I am going to close this out
