### ISSUE TITLE
check-config add proble for mangle

### ISSUE THREAD

**Issue by nbn** [k3s-io/k3s#4077]
**Is your feature request related to a problem? Please describe.**
Was installing k3s on a custom kernel, where it took a while to realize that the kernel was built without the mangle table

**Describe the solution you'd like**
I can see that check-config verifies the presence of filter and nat, so I assume it would be easy to include a check for the mangle table.

e.g.
```
- CONFIG_IP_NF_NAT: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_MANGLE: enabled

```
**Describe alternatives you've considered**
None
**Additional context**
Given this was a custom kernel it is not likely to arise in other contexts, but for clarity it was based on debian/buster

**Backporting**
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
PR welcome!
