### ISSUE TITLE
Basic install instructions do not result in a single node cluster

### ISSUE THREAD

**Issue by swright-eti** [k3s-io/k3s#4078]
**Environmental Info:**
K3s Version: 
k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 
```Linux swright 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

Cluster Configuration:
1 server

**Describe the bug:**
After deploying k3s per the instructions there is no worker node on the server. 

**Steps To Reproduce:**
- disabled firewalld
- Installed K3s per instructions: ```curl -sfL https://get.k3s.io | sh -```
- Ran: ```k3s kubectl get node```

**Expected behavior:**
I expected to see output that shows me that the node is up and ready to work. 

**Actual behavior:**
```
k3s kubectl get node
No resources found
```

**Additional context / logs:**

```
# kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

```
# kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   16h

# kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get ns
NAME              STATUS   AGE
default           Active   16h
kube-system       Active   16h
kube-public       Active   16h
kube-node-lease   Active   16h
```

**Comment by brandond** [comment]
I think you ran your `kubectl get node` command too early during the startup process - when the apiserver was up, but before the kubelet had finished registering. Have you tried running it again?

**Comment by swright-eti** [comment]
It turned out to be an incompatible file system. Granted, I should have dug this out of the logs earlier, but it would have been nice if the installer had told me this. 

```
ERRO[2021-09-24T10:40:28.848795952-04:00] Failed to configure agent: "overlayfs" snapshotter cannot be enabled for "/var/lib/rancher/k3s/agent/containerd", try using "fuse-overlayfs" or "native": /var/lib/rancher/k3s/agent/containerd does not support d_type. If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support
```
