### ISSUE TITLE
node certificates do not rotated ,if wo not restart k3s-agent service 

### ISSUE THREAD

**Issue by wolfguoliang** [k3s-io/k3s#4097]
**Environmental Info:**
K3s Version: 
k3s version v1.19.4+k3s2 (8f9e5628)

when certificates are expired or have fewer than 90 days remaining，we restart k3s server , server certificates are rotated ,bu node certificates are not rotated!  when we restart k3s-agent ,the node certificates are rotated.  Is that make sense? thanks
Certificate Rotation
By default, certificates in K3s expire in 12 months.

If the certificates are expired or have fewer than 90 days remaining before they expire, the certificates are rotated when K3s is restarted.

**Comment by brandond** [comment]
Can you be more specific about which certificates are not being rotated? What commands are you running to check the expiration?

**Comment by wolfguoliang** [comment]
Thanks for you response，
below certificates are not being rotated,
/var/lib/rancher/k3s/agent/client-k3s-controller.crt
/var/lib/rancher/k3s/agent/client-kubelet.crt
/var/lib/rancher/k3s/agent/client-kube-proxy.crt
/var/lib/rancher/k3s/agent/serving-kubelet.crt

use below command 
for i in `ls /var/lib/rancher/k3s/agent/*.crt`; do echo $i; openssl x509 -enddate -noout -in $i; done

**Comment by brandond** [comment]
These files are generated by the server. In order to get them updated on agents, the server needs to be restarted in order to perform the renewal; the agent will pick up them the next time it restarts.

**Comment by wolfguoliang** [comment]
OK ，Thanks
