### ISSUE TITLE
[release-1.22] Support dual-stack in klipper-lb

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4100]
* Backport of #4021 on branch release-1.22

**Is your feature request related to a problem? Please describe.**

Dual-stack services in load-balanced mode are not working because klipper-lb does not support it:

```
+ iptables -t nat -I PREROUTING '!' -s 2001:cafe:42:1::def/32 -p TCP --dport 8080 -j DNAT --to 2001:cafe:42:1::def:8080
iptables v1.6.2: Port `cafe:42:1::def:8080' not valid
```

**Describe the solution you'd like**

klipper-lb is able to apply an ipv6 config

**Additional context**

https://github.com/k3s-io/k3s/issues/1405

**Comment by rancher-max** [comment]
Validated the config at `/proc/sys/net/ipv6/conf/all/forwarding` inside the pods matches the host (both set to 1) using v1.22.2-rc1+k3s2 and the current validated ipv6 functionality continues to work.

**Comment by ShylajaDevadiga** [comment]
Validated in the new rc v1.22.3-rc3+k3s1 https://github.com/k3s-io/k3s/issues/4021
