### ISSUE TITLE
k3s ignores external IP for services, no way to block connections to other IPs

### ISSUE THREAD

**Issue by Symbiatch** [k3s-io/k3s#4151]
**Environmental Info:**
K3s Version: k3s version v1.22.2+k3s1 (10bca343)

Node(s) CPU architecture, OS, and Version: 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux

Cluster Configuration: single server

**Describe the bug:**

k3s will ignore the external IP set for it / services running on it and will accept connections to services from anywhere. There also is no way to use iptables to block the connections since KUBE-ROUTER-INPUT is forcibly pushed to be the first rule and it'll accept the connections before custom rules can block them.

**Steps To Reproduce:**

- Install k3s with specific external IP address on a system with multiple IP addresses
- Create a service which binds to this specific address
- Connect to the service port on any other IP address on the system

**Expected behavior:**

Only connections to the specific external IP address succeed - the IP shown by kubectl get service/x is the only one that accepts the connection.

**Actual behavior:**

Any connection to that port on any IP address on the system will succeeed, the external IP setting is entirely ignored

**Additional context / logs:**

If there was a way to at least add iptables rules before KUBE-ROUTER-INPUT this would be less of a problem. I understand that k3s is not meant to be connected to the internet directly so this might not be considered a bigger issue, but there are other reasons also why people would need to only bind to specific IPs, or have iptables rules set up before the routing happens.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Are you talking about services of type=LoadBalancer when using ServiceLB (klipper-lb), or just services in general?

**Comment by Symbiatch** [comment]
Sorry, I should've been more specific. Yes it's about LoadBalancers added to the system. So when I have this in `kubectl get service/traefik`

> kube-system            traefik                                          LoadBalancer   10.43.109.55    1.2.3.4   80:30595/TCP,443:30045/TCP

then I'd assume it's only bound to 1.2.3.4:80 and 1.2.3.4:443, not anyip:80 and anyip:443. Or I could add rules to block connections with iptables at least.

**Comment by brandond** [comment]
No, that's not really how it works. See: https://rancher.com/docs/k3s/latest/en/networking/#how-the-service-lb-works

Because it uses a NodePort pod behind the scenes, the service port is available via all addresses on that node; the Node's internal and external addresses are used to determine the ExternalIP for the Service. ServiceLB is intentionally a simplistic zero-configuration load balancer controller; if you want something more complicated you might consider disabling it and deploying kube-vip or metallb instead.
