### ISSUE TITLE
`kube-apiserver-arg` does not set up correctly API Server in case of flags that can be set multiple times

### ISSUE THREAD

**Issue by mazzy89** [k3s-io/k3s#4162]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

```
k3os version v0.20.11-k3s1r1
```

Cluster Configuration:

1 master, 3 agents

**Describe the bug:**

When I try to set up `--kube-apiserver-arg=service-account-key-file` multiple times only the last `service-account-key-file` is applied to the API Server. However officialy the API Server allows to define the commands multiple times.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

I would expect that defining:

```
--kube-apiserver-flag=service-account-key-file=key1
--kube-apiserver-flag=service-account-key-file=key2
```

the API Server be stood up with both the `service-account-key-file`

**Actual behavior:**

```
time="2021-10-06T16:55:54.418895840Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=sts.amazonaws.com --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --feature-gates=ServiceAccountIssuerDiscovery=false --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://s3-eu-central-1.amazonaws.com/my-amazing-bucket --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/sa-signer.key --service-cluster-ip-range=10.107.0.0/23 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
```

**Additional context / logs:**

I'm using k3os and I'm not fully sure whether the bug belongs here or there. If I haven't understood wrongly how the args parsing work it should belong here but opened also under https://github.com/rancher/k3os/issues/777

**Backporting**

- [ ] Needs backporting to older releases

**Comment by mazzy89** [comment]
It just fails reporting that the file `key1,key2` does not exist

**Comment by brandond** [comment]
Also, what is your intent with passing additional keys?

**Comment by mazzy89** [comment]
Yes I was thinking of some hack like that to overcome the issue but I haven't tried that.

Passing additional keys is usually common practice to enable other external providers like OIDC providers. See a common use case in deploying the EKS webhook https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md

**Comment by mazzy89** [comment]
Also, I've opened a discussion here https://github.com/k3s-io/k3s/discussions/4173 because something with the k3s configuration confuses me and makes things more complicated.

**Comment by brandond** [comment]
Can you share a bit more about how you ended up configuring the service account issuer stuff?  As of 1.21 we pre-configure most of that out of the box to just work with the stub OIDC discovery endpoint built in to the apiserver.

**Comment by mazzy89** [comment]
In the end those were the only flags needed in my case:

```
    - "--kube-apiserver-arg=feature-gates=ServiceAccountIssuerDiscovery=true"
    - "--kube-apiserver-arg=service-account-issuer=https://s3-eu-central-1.amazonaws.com/my-bucket"
    - "--kube-apiserver-arg=service-account-jwks-uri=https://s3-eu-central-1.amazonaws.com/my-bucket/openid/v1/jwks"
```

**Comment by caroline-suse-rancher** [comment]
Closing due to age
