### ISSUE TITLE
Add aliases to etcd-snapshot s3 flags for parity with k3s server

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add aliases for all `etcd-snapshot` flags that do not have the `etcd` -prefix. Achieve flag parity with `k3s server` s3 commands

**Describe alternatives you've considered**

**Additional context**

The original etcd-snapshot command flags where shortened to make CLI more convenient and prevented the user from typing "etcd" over and over again. 

**Backporting**

- [X] Needs backporting to `engine-1.21`, `release-1.22`, `release-1.21`.

**Comment by ShylajaDevadiga** [comment]
Validated using commit id from master branch: d71b3358714711c2f95bc6cc6020320b6f6e5f0f. Snapshot was created successfully in s3 bucket as well as locally. All params were prefixed with etcd
```
$ k3s -v
k3s version v1.22.4+k3s-d71b3358
$ sudo k3s etcd-snapshot  --etcd-s3  --etcd-s3-bucket=<bucket>  --etcd-s3-access-key=<key>    --etcd-s3-secret-key=<secret> --etcd-s3-region=<region>
```
