### ISSUE TITLE
[1.22] Consider switching the metrics-server port from 443 back to 8443

### ISSUE THREAD

**Issue by jandubois** [k3s-io/k3s#4167]
The metrics-server pod from k3s 1.22.2 fails in Rancher Desktop on Windows with this error:

```
Error: failed to create listener: failed to listen on 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied
```

This seems to be a known problem due to metrics-server 0.5.0 changing the port to 433 "to test during CI that it can be bound to a privileged port": https://github.com/kubernetes-sigs/metrics-server/issues/782

rke2 also restores the port value to `8443`, and I think k3s should do the same: https://github.com/rancher/rke2-charts/blob/main/charts/rke2-metrics-server/rke2-metrics-server/2.11.100-build2021091503/templates/metrics-server-deployment.yaml#L56

I'm not completely sure this will fix the issue for Rancher Desktop, as the binary will still be marked `CAP_NET_BIND_SERVICE` via `setcap`. At least I assume the binary in the rancher image is marked the same way as the official image.

I'm further confused that I cannot reproduce this problem with Rancher Desktop on macOS/Lima, but just on Windows/WSL2, and I don't have any explanation for this.

**Comment by jandubois** [comment]
Please put this on hold for now; we need to dig deeper on what exactly is causing the failure on WSL2; it looks like k3s always used port `443` for metrics-server.

**Comment by cwayne18** [comment]
@jandubois is this still needed?
