### ISSUE TITLE
Node stuck in NotReady status after temporary interface disconnect

### ISSUE THREAD

**Issue by mjrist** [k3s-io/k3s#4168]
**Environmental Info:**
K3s Version: 
k3s version v1.22.2+k3s1 (10bca343)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux somehostname1 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux somehostname2 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux somehostname3 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 node HA cluster with embedded etcd.
```
NAME               STATUS   ROLES                       AGE     VERSION
somehostname1   Ready    control-plane,etcd,master   5m      v1.22.2+k3s1
somehostname2   Ready    control-plane,etcd,master   4m      v1.22.2+k3s1
somehostname3   Ready    control-plane,etcd,master   3m47s   v1.22.2+k3s1
```

Nothing is deployed on the cluster except coredns and local-path-provisioner.

**Describe the bug:**
Node is stuck in NotReady status after temporarily disconnecting interface and reconnecting.

**Steps To Reproduce:**
Set up a three node HA cluster with embedded etcd using k3s version v1.22.2+k3s1.

1. On one node, bring the interface down: `ifdown $interface`
2. Wait till Node goes into NotReady status. Determined by watching `kubectl get nodes` from one of the remaining 2 nodes.
3. Bring the interface back up: `ifup $interface`

The node does not return to Ready, although it appears to be reconnected.

Notes:
* I've tested this multiple times - disconnecting both the etcd leader and non etcd leader nodes.
* Physically unplugging the ethernet cable, waiting, and then plugging the cable back in has the same effect.
* Occasionally it does recover by itself (within a minute). However most of the time it does not.
* I've let it sit for over 12 hours without it recovering.
* Restarting k3s manually (systemctl restart k3s) does restore the node.
* `etcdctl endpoint status --cluster` indicates that the node is back in the etcd cluster after the interface is brought back up.

`kubectl describe node` on the "failed" node shows:
```
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----             ------    -----------------                 ------------------                ------              -------
  MemoryPressure   Unknown   Wed, 06 Oct 2021 14:23:52 -0700   Wed, 06 Oct 2021 14:24:52 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure     Unknown   Wed, 06 Oct 2021 14:23:52 -0700   Wed, 06 Oct 2021 14:24:52 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure      Unknown   Wed, 06 Oct 2021 14:23:52 -0700   Wed, 06 Oct 2021 14:24:52 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready            Unknown   Wed, 06 Oct 2021 14:23:52 -0700   Wed, 06 Oct 2021 14:24:52 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
```

**Expected behavior:**
When the interface is reconnected the node should return to Ready status.

**Comment by brandond** [comment]
I see that you're using the ipsec flannel backend. Do you see the same issue with different a different backend?

**Comment by mjrist** [comment]
Okay, the exit makes sense to me - thanks for explaining.

I ran some more tests and confirmed some things - which you may already know - I'm catching up :)

If I disconnect non-etcd-leader nodes (in which case there is no leader change and no "leaderelection lost"/fatal error on any nodes during failover or recovery) everything recovers fine.

The problem arises only when the fatal error occurs (leaderelection lost) on the node that went down. Furthermore, if I manually restart k3s before the node comes back online it recovers fine when it rejoins.

So all that just confirms what you are saying - fix the panic and restart and it should work.

By the way, thanks for your fast responses on this.

**Comment by brandond** [comment]
> if I disconnect the controller-manager node, I wait a little over 15 seconds for the kube-controller-manager lease to be taken by another node, and then the 30 seconds for my node to go into NotReady status. Is there anyway to avoid the 15 second delay?

I don't believe the controller failover resets the timer, as it's not actually a timer as far as I know. The kubelet updates the status on both its Node object, and the kube-node-lease matching its Node name. That is what the controller looks at to determine whether or not the kubelet is healthy. This is documented at https://kubernetes.io/docs/concepts/architecture/nodes/#heartbeats

**Comment by mjrist** [comment]
Good information thanks.

Found this in my logs when the controller manger picks up on a new node during failover.
```
node_lifecycle_controller.go:1013] Missing timestamp for Node somehostname1. Assuming now as a timestamp.
node_lifecycle_controller.go:1013] Missing timestamp for Node somehostname2. Assuming now as a timestamp.
node_lifecycle_controller.go:1013] Missing timestamp for Node somehostname3. Assuming now as a timestamp.
```

and I gave node_lifecycle_controller.go a look

```
if nodeHealth == nil {
		klog.Warningf("Missing timestamp for Node %s. Assuming now as a timestamp.", node.Name)
		nodeHealth = &nodeHealthData{
			status:                   &node.Status,
			probeTimestamp:           nc.now(),
			readyTransitionTimestamp: nc.now(),
		}
```

My go is not greatest, but here is what I gathered from the rest of the code. The node controller just stores the probe times in memory (in the node heath objects in a map). On spin up it creates a new map and subsequently sets the last probe times to the current time, which of course has the effect of reseting t0 for the grace period.

I suppose it's cheaper this way than constantly persisting and sharing the last probe time to account for a controller manager shift.

In any case, the failover times should be good enough for now.

**Comment by brandond** [comment]
Right, node health is nil on startup because the nodeHealthMap hasn't been populated yet. The timestamps will get updated almost immediately as the Node watch sees the initial `nodeLister.List` results come in via the code path in `monitorNodeHealth`.  The Kubernetes code has a ton of parallel goroutines and as I said earlier, an eventual consistency model so not everything is in its final state at startup.

**Comment by rancher-max** [comment]
Performed the same steps mentioned in https://github.com/k3s-io/k3s/issues/4239#issuecomment-956933405 using master branch commit `702fe24afe3f08f96ebc167313c20c0339a5510f`
