### ISSUE TITLE
Update error messaging around using "K10" prefixed --token

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4169]
**Is your feature request related to a problem? Please describe.**

After being pointed out in https://github.com/rancher/docs/pull/3580, an unassuming user could get stuck if they try and supply a "K10" prefixed token to a k3s server or agent. This is because the first K3s server in the cluster will take the string passes to `--token` and format it into a K10 token with  `K10<ca-hash>::<username>:<password>`. This token is then supplied to other agents and servers to form the multi-node cluster. 

Currently if the user runs `k3s server --token=K10THISISATEST`, on the first node, k3s will crash with the error `panic: failed to normalize token` which is not helpful to explain what went wrong. This is because K3s saw the "K10" prefix and assumed that the token passes is in the  `K10<ca-hash>::<username>:<password>`, not that the password happens to start with "K10". 

**Describe the solution you'd like**

The error message when a K10 prefixed token is given to the first server should contain more detail on what went wrong. 

**Describe alternatives you've considered**

Adding additional documentation around this. Documentation should not be used to warn users what "NOT TO DO", errors should inform users on that. 

**Additional context**

**Backporting**

- [X] Needs backporting to older releases

**Comment by mdrahman-suse** [comment]
**Verified on k3s master with commit** `86c692411913e87d88039ff87f9fd095aa94d152`

Steps:
1. Create single node or multi node cluster
2. Installed k3s from the commit and started using
```
k3s server --token=K10THISISATEST
```
3. Observed the message below
```
panic: failed to normalize token; must be in format K10<CA-HASH>::<USERNAME>:<PASSWORD> or <PASSWORD>
```
