### ISSUE TITLE
Ubuntu 21.04 - vxlan failing to route

### ISSUE THREAD

**Issue by clemenko** [k3s-io/k3s#4188]
**Environmental Info:**
K3s Version: 
1.21.5+k3s2
```
NAME       STATUS   ROLES                       AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
k3s-85fc   Ready    control-plane,etcd,master   18m   v1.21.5+k3s2   134.122.5.183    <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1
k3s-a648   Ready    <none>                      18m   v1.21.5+k3s2   104.131.58.161   <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1
k3s-ad66   Ready    <none>                      18m   v1.21.5+k3s2   143.198.24.211   <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1
```

Node(s) CPU architecture, OS, and Version: 
`Linux k3s-85fc 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
As per above. 3 nodes, 1 master and 2 workers. This is a fresh install of k3s on Ubuntu 21.04.

**Describe the bug:**
With a fresh install of k3s on Ubuntu 21.04 vxlan is not working. AKA pods are not able to talk to each other across flannel. I have stopped and disabled ufw. 

**Steps To Reproduce:**
- build 3 - 21.04 - vms on Digitalocean.
- use k3sup ` k3sup install --ip $server --user $user --k3s-extra-args '--no-deploy traefik --debug' --cluster --k3s-channel $k3s_channel --local-path ~/.kube/config`
- Installed K3s: 

**Expected behavior:**
pods talk / ping across the nodes. 

**Actual behavior:**
no ping

**Additional context / logs:**
journalct does not show any logs. 
`net.ipv4.ip_forward = 1` is enabled. 

pings are not working.
`root@k3s-8fea:~# ip a list cni0 | grep -w inet
    inet 10.42.0.1/24 brd 10.42.0.255 scope global cni0`

```
root@k3s-aaaa:~# ping 10.42.0.1
PING 10.42.0.1 (10.42.0.1) 56(84) bytes of data.
^C
--- 10.42.0.1 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1019ms
```

Updated both servers 

**Backporting**
no . This seems to be tide to Ubuntu 21.04. This works on 20.10.

**Comment by clemenko** [comment]
`--flannel-backend=host-gw` is not working either. granted i am using `k3sup`. How can i validate what backend is active on the master node?

**Comment by brandond** [comment]
host-gw only works if all your nodes are on the same subnet, which from looking at your node addresses it appears they are not.

**Comment by vadorovsky** [comment]
According to what @brandond and @manuelbuil wrote above, I consider that as a flannel but. Here is the attempt to fix it:

flannel-io/flannel#1485

**Comment by ajvn** [comment]
I'm also getting hit by this when trying to deploy some workload that tries to reach public registry. In this specific case, this is the error I'm encountering when trying to deploy `pihole`:
```bash
failed to resolve reference "docker.io/pihole/pihole:2021.10.1": failed to do request: Head "https://registry-1.docker.io/v2/pihole/pihole/manifests/2021.10.1": dial tcp: lookup registry-1.docker.io: Try again
```
It also breaks DNS across the cluster, here's output from one of the nodes before/after the deployment:
```bash
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=10 ttl=107 time=23.8 ms
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=11 ttl=107 time=23.3 ms
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=12 ttl=107 time=23.6 ms
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=13 ttl=107 time=33.4 ms
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=14 ttl=107 time=24.1 ms
64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=15 ttl=107 time=24.3 ms
64 bytes from 172.253.120.138: icmp_seq=16 ttl=107 time=31.5 ms
64 bytes from 172.253.120.138: icmp_seq=17 ttl=107 time=25.8 ms
64 bytes from 172.253.120.138: icmp_seq=18 ttl=107 time=26.9 ms
64 bytes from 172.253.120.138: icmp_seq=19 ttl=107 time=24.3 ms
64 bytes from 172.253.120.138: icmp_seq=20 ttl=107 time=26.0 ms
```
If I stop that, and retry pinging google, it will fail to resolve name resolution.

As soon as I remove that deployment, DNS resolution starts working again.
This happens with latest `k3s version v1.21.6-rc2+k3s1 (254d2f69)` which, at least from what I managed to find, uses updated version of flannel, 0.15.1.

Please let me know if I can provide any more output that could help with solving this.

Thank you.

**Comment by manuelbuil** [comment]
> As I said, Debian 11 uses nftables and I had to set it to legacy to work properly in my k3s clusters

So, even though Debian 11 uses nftables as default, k3s does not work properly with nftables and thus you must change iptables to legacy in order for k3s to work? If that's the case, could you please open a different issue? Thanks! And sorry for not understanding the issue :(

**Comment by manuelbuil** [comment]
> This is kindof documented here: https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster
> 
> I'd argue that this recommendation should be be moved from "Advanced Options and Configurations" to "FAQ" or "Known Issues", and expand that this applies to all of modern versions of "Raspian", "Ubuntu" and "Debian".

Thanks for this

**Comment by Brice187** [comment]
> So, even though Debian 11 uses nftables as default, k3s does not work properly with nftables and thus you must change iptables to legacy in order for k3s to work? If that's the case, could you please open a different issue? Thanks! And sorry for not understanding the issue :(

the workaround with iptables runs pretty well, so this is not an mentionable issue (for me

**Comment by manuelbuil** [comment]
> I'm also getting hit by this when trying to deploy some workload that tries to reach public registry. In this specific case, this is the error I'm encountering when trying to deploy `pihole`:
> 
> ```shell
> failed to resolve reference "docker.io/pihole/pihole:2021.10.1": failed to do request: Head "https://registry-1.docker.io/v2/pihole/pihole/manifests/2021.10.1": dial tcp: lookup registry-1.docker.io: Try again
> ```
> 
> It also breaks DNS across the cluster, here's output from one of the nodes before/after the deployment:
> 
> ```shell
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=10 ttl=107 time=23.8 ms
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=11 ttl=107 time=23.3 ms
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=12 ttl=107 time=23.6 ms
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=13 ttl=107 time=33.4 ms
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=14 ttl=107 time=24.1 ms
> 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=15 ttl=107 time=24.3 ms
> 64 bytes from 172.253.120.138: icmp_seq=16 ttl=107 time=31.5 ms
> 64 bytes from 172.253.120.138: icmp_seq=17 ttl=107 time=25.8 ms
> 64 bytes from 172.253.120.138: icmp_seq=18 ttl=107 time=26.9 ms
> 64 bytes from 172.253.120.138: icmp_seq=19 ttl=107 time=24.3 ms
> 64 bytes from 172.253.120.138: icmp_seq=20 ttl=107 time=26.0 ms
> ```
> 
> If I stop that, and retry pinging google, it will fail to resolve name resolution.
> 
> As soon as I remove that deployment, DNS resolution starts working again. This happens with latest `k3s version v1.21.6-rc2+k3s1 (254d2f69)` which, at least from what I managed to find, uses updated version of flannel, 0.15.1.
> 
> Please let me know if I can provide any more output that could help with solving this.
> 
> Thank you.

Could you open a different issue for this please?

**Comment by mdrahman-suse** [comment]
**Validated the fix with k3s master commit: 86c692411913e87d88039ff87f9fd095aa94d152 and performed same steps as https://github.com/k3s-io/k3s/issues/4259#issuecomment-958170687**

**Comment by clemenko** [comment]
Commented on #4259 

This is still broken for me.
Deploying with https://github.com/clemenko/k3s/blob/master/k3s.sh#L173

root@k3s-831b:~# systemd --version
systemd 247 (247.3-3ubuntu3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

root@k3s-831b:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

root@k3s-831b:~# uname -a
Linux k3s-831b 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Then deployed the noted yaml from above.

kube:

clemair:clemenko k3s ( 167.99.124.208:6443 ) $ kubectl get nodes,pods  -o wide
NAME            STATUS   ROLES                       AGE     VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
node/k3s-831b   Ready    control-plane,etcd,master   9m47s   v1.21.5+k3s2   167.99.124.208   <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1
node/k3s-a95e   Ready    <none>                      9m21s   v1.21.5+k3s2   167.99.116.17    <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1
node/k3s-bda2   Ready    <none>                      9m15s   v1.21.5+k3s2   142.93.69.32     <none>        Ubuntu 21.04   5.11.0-18-generic   containerd://1.4.11-k3s1

NAME                         READY   STATUS    RESTARTS   AGE    IP          NODE       NOMINATED NODE   READINESS GATES
pod/othertest-deploy-2glbg   1/1     Running   0          7m4s   10.42.1.7   k3s-a95e   <none>           <none>
pod/othertest-deploy-bdrbq   1/1     Running   0          7m4s   10.42.2.7   k3s-bda2   <none>           <none>
pod/othertest-deploy-blnnd   1/1     Running   0          7m4s   10.42.0.9   k3s-831b   <none>           <none>

and the pings

clemair:clemenko k3s ( 167.99.124.208:6443 ) $ kubectl exec -it othertest-deploy-2glbg -- bash
nginx@othertest-deploy-2glbg:/$ ping -c 1 -t 1 10.42.2.7   
PING 10.42.2.7 (10.42.2.7) 56(84) bytes of data.
From 10.42.1.1 icmp_seq=1 Time to live exceeded

--- 10.42.2.7 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

nginx@othertest-deploy-2glbg:/$ ping -c 1 -t 1 10.42.0.9   
PING 10.42.0.9 (10.42.0.9) 56(84) bytes of data.
From 10.42.1.1 icmp_seq=1 Time to live exceeded

--- 10.42.0.9 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

One of the things I noticed is that you are NOT using the upstream kernel. You are using the aws compiled one. Wonder if that has a fix. I am on DigitalOcean. This problem still applies to 21.10 as well.

**Comment by brandond** [comment]
QA marked this as fixed in the version that we're about to release, not the version that you're currently using. Please try again once we actually release the fixed version.

**Comment by clemenko** [comment]
v1.22.3+k3s1 works!

**Comment by ajvn** [comment]
> > I'm also getting hit by this when trying to deploy some workload that tries to reach public registry. In this specific case, this is the error I'm encountering when trying to deploy `pihole`:
> > ```shell
> > failed to resolve reference "docker.io/pihole/pihole:2021.10.1": failed to do request: Head "https://registry-1.docker.io/v2/pihole/pihole/manifests/2021.10.1": dial tcp: lookup registry-1.docker.io: Try again
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It also breaks DNS across the cluster, here's output from one of the nodes before/after the deployment:
> > ```shell
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=10 ttl=107 time=23.8 ms
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=11 ttl=107 time=23.3 ms
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=12 ttl=107 time=23.6 ms
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=13 ttl=107 time=33.4 ms
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=14 ttl=107 time=24.1 ms
> > 64 bytes from wd-in-f138.1e100.net (172.253.120.138): icmp_seq=15 ttl=107 time=24.3 ms
> > 64 bytes from 172.253.120.138: icmp_seq=16 ttl=107 time=31.5 ms
> > 64 bytes from 172.253.120.138: icmp_seq=17 ttl=107 time=25.8 ms
> > 64 bytes from 172.253.120.138: icmp_seq=18 ttl=107 time=26.9 ms
> > 64 bytes from 172.253.120.138: icmp_seq=19 ttl=107 time=24.3 ms
> > 64 bytes from 172.253.120.138: icmp_seq=20 ttl=107 time=26.0 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I stop that, and retry pinging google, it will fail to resolve name resolution.
> > As soon as I remove that deployment, DNS resolution starts working again. This happens with latest `k3s version v1.21.6-rc2+k3s1 (254d2f69)` which, at least from what I managed to find, uses updated version of flannel, 0.15.1.
> > Please let me know if I can provide any more output that could help with solving this.
> > Thank you.
> 
> Could you open a different issue for this please?

Done https://github.com/k3s-io/k3s/issues/4486

Thank you.

**Comment by 0xD3** [comment]
For anyone who stumbles on this issue while using the latest version of ubuntu 21.10, vxlan modules were moved by upstream to a separate package: ```linux-modules-extra-raspi```. Installing these should solve your issues.
