### ISSUE TITLE
Documentation for embedded etcd configuration

### ISSUE THREAD

**Issue by mjrist** [k3s-io/k3s#4204]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux
3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 node HA cluster using embedded etcd

**Describe the bug:**
Cannot determine how to configure embedded etcd. As far as I can tell, beyond what is listed here (https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#database), the documentation does not explain how to pass etcd configuration to the embedded instance. Perhaps, other etcd configuration options are considered unsupported?

Specifically, I am trying to set the etcd `pre-vote` option to true. I attempted to modify the configuration file at /var/lib/rancher/k3s/server/db/etcd/config, but that appears to be overwritten on restart of k3s.

Is there a way to change configuration for embedded etcd?

**Comment by brandond** [comment]
The embedded etcd database does not accept any configuration options at this time.
