### ISSUE TITLE
hardcoded etcd snapshot s3 upload timeout of 30 seconds

### ISSUE THREAD

**Issue by jeffborg** [k3s-io/k3s#4205]
**Environmental Info:**
K3s Version: 

k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 

Linux pi1 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux

Cluster Configuration:

3 servers, 1 agent

**Describe the bug:**

Been told there is a hard coded timeout of 30seconds on uploading etcd snapshots to s3, On a slower internet connection it may take longer than 30 seconds to push the snapshot to an s3 storage.

**Steps To Reproduce:**

- Installed K3s: 
- enabled s3 snapshots
- no s3 snapshots

**Expected behavior:**

Should expect snapshots on s3 bucket

**Actual behavior:**

snapshots only stored locally

**Additional context / logs:**

```
Oct 14 00:00:38 pi3 k3s[1928]: time="2021-10-14T00:00:38.258458746+11:00" level=error msg="Error received in attempt to upload snapshot to S3: Put \"https://BUCKETNAME.s3.dualstack.ap-southeast-2.amazonaws.com/etcd-snapshot-pi3-1634130000\": context deadline exceeded"
Oct 14 00:00:38 pi3 k3s[1928]: time="2021-10-14T00:00:38.258554116+11:00" level=info msg="S3 upload complete for etcd-snapshot-pi3-1634130000"
Oct 14 00:00:38 pi3 k3s[1928]: time="2021-10-14T00:00:38.706423059+11:00" level=info msg="Saving current etcd snapshot set to k3s-etcd-snapshots ConfigMap"
```

config.yaml

```
etcd-s3: true
etcd-s3-access-key: KEY
etcd-s3-bucket: BUCKETNAME
etcd-s3-region: ap-southeast-2
etcd-s3-secret-key: SECRET
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by mdrahman-suse** [comment]
**Verified in k3s on Master with commit id ef263bd2b0ecb29c3404cd4b80fcfcf8b4301912**

Steps
- Create a single node cluster (1 server 1 agent, Ubuntu 20.04)
- Install k3s on server and agent nodes
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --token secret --cluster-init" INSTALL_K3S_COMMIT=ef263bd2b0ecb29c3404cd4b80fcfcf8b4301912 sh -
```
- Verified the cluster is created and running
- Take snapshot of the cluster and store in s3
```
k3s etcd-snapshot \
  --s3 \
  --s3-bucket=<BUCKET_NAME> \
  --s3-access-key=<ACCESS_KEY> \
  --s3-secret-key=<SECRET_KEY> \
  --s3-region=<REGION> \
  --s3-timeout=50s
```
- Validate the snapshot is created locally and also stored in s3 bucket respectively
```
INFO[0000] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/<ID>
{"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/k3s/server/db/snapshots/<ID>.part"}
{"level":"info","logger":"client","msg":"opened snapshot stream; downloading"}
{"level":"info","msg":"fetching snapshot","endpoint":"<REDACTED>"}
{"level":"info","logger":"client","msg":"completed snapshot read; closing"}
{"level":"info","msg":"fetched snapshot","endpoint":"<REDACTED>","size":"2.0 MB","took":"now"}
{"level":"info","msg":"saved","path":"/var/lib/rancher/k3s/server/db/snapshots/<ID>"}
INFO[0000] Saving etcd snapshot <ID> to S3
INFO[0000] Checking if S3 bucket <BUCKET_NAME> exists
INFO[0000] S3 bucket <BUCKET_NAME> exists
INFO[0000] S3 upload complete for <ID>
INFO[0000] Saving current etcd snapshot set to k3s-etcd-snapshots ConfigMap
```
