### ISSUE TITLE
rootless mode - tries to create /usr/libexec/kubernetes

### ISSUE THREAD

**Issue by itoffshore** [k3s-io/k3s#4216]
**Environmental Info:**

K3s Version: 

```
k3s version v1.22.2+k3s2 (3f5774b4)
go version go1.16.8
```

**Node(s) CPU architecture, OS, and Version:** 

* `Linux web 5.13.0-19-generic #19-Ubuntu SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* **Ubuntu 21.10** (`cgroups v2` supported by default)
---
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          3
On-line CPU(s) list:             0-2
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       3
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
Stepping:                        4
CPU MHz:                         2999.834
BogoMIPS:                        5999.66
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       96 KiB
L1i cache:                       96 KiB
L2 cache:                        12 MiB
L3 cache:                        48 MiB
NUMA node0 CPU(s):               0-2
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and s
                                 eccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanit
                                 ization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW
                                 , STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
                                  pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rd
                                 tscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpu
                                 id tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2
                                  x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand h
                                 ypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjus
                                 t smep erms xsaveopt arat md_clear
```
---

**Cluster Configuration:**

single server 

**Describe the bug:**

`plugins.go` attempts to `mkdir /usr/libexec/kubernetes`

**Steps To Reproduce:**

* Installed K3s: 
* start `rootless` mode as an unprivileged `$USER` with `k3s-rootless.service` from `master`

**Expected behavior:**

* in `rootless` mode `plugins.go` should create directories somewhere in `$HOME/.rancher` of the unprivileged user. 
* I symlinked `/usr/libexec/kubernetes` to `$HOME/.rancher/k3s/libexec/kubernetes` to workaround the issue.

**Actual behavior:**

creating `/usr/libexec/kubernetes` fails due to running `rootless`

**Additional context / logs:**

`Oct 14 17:42:18 web k3s[1927]: E1014 17:42:18.725678      31 plugins.go:609] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec/kubernetes: permission denied`

**Backporting**

- [X] Needs backporting to older releases (this issue also exists on current `stable` version `v1.21.5+k3s2`)

---

Many thanks for working on `rootless` mode ;o)

**Comment by AkihiroSuda** [comment]
> creating /usr/libexec/kubernetes fails due to running rootless

Just to confirm, k3s itself continue to work regardless to this error, right?
(Seems to work for me, as of the latest commit 5a923ab8dc46716b34135c4d505bef99694a1616 , on Ubuntu 21.10)


> cc @AkihiroSuda - is this something that we need to adjust for the kubelet?

Yes.
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/


> volumePluginDir
> string 
>
> volumePluginDir is the full path of the directory in which to search for additional third party volume plugins. If DynamicKubeletConfig (deprecated; default off) is on, when dynamically updating this field, consider that changing the volumePluginDir may disrupt workloads relying on third party volume plugins. Default: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"


The path should be probably changed, even for rootful mode?

**Comment by itoffshore** [comment]
yes the cluster comes up in `rootless` mode on **Ubuntu 21.10** regardless of the `/usr/libexec/kubernetes` path:
```
NAMESPACE     NAME                                     READY   STATUS      RESTARTS       AGE
kube-system   helm-install-traefik-crd--1-h2c2s        0/1     Completed   0              12h
kube-system   helm-install-traefik--1-pcmxv            0/1     Completed   1              12h
kube-system   coredns-85cb69466-r5f9g                  1/1     Running     13 (49s ago)   12h
kube-system   local-path-provisioner-64ffb68fd-w2bts   1/1     Running     14 (49s ago)   12h
kube-system   metrics-server-9cf544f65-dvrc2           1/1     Running     14 (49s ago)   12h
kube-system   svclb-traefik-qlvxj                      2/2     Running     26 (49s ago)   12h
kube-system   traefik-74dd4975f9-mtnhx                 1/1     Running     13 (49s ago)   12h
```

I had an error in my `nftables` **outbound** `loopback` rule:

`oif "lo" accept` (in error I had `iif`)

which was preventing the cluster coming up.

---

I think the **rootful** `k3s.service` needs the following added [so the firewall starts after](https://unix.stackexchange.com/a/239978/93470) the `flannel` & `cni0` interfaces are up:
```
[unit]
Before=network-pre.target
Wants=network-pre.target
```

---

A small **rootful** firewall note for others:

in my **forward** `nftables` rules I also needed:

`oif "cni0" accept`
