### ISSUE TITLE
Race condition in the cloud provider

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4217]
**Environmental Info:**
K3s Version: master

Node(s) CPU architecture, OS, and Version: ubuntu

Cluster Configuration: 1 server

**Describe the bug:**

We always get this log:

```
435407-Oct 14 18:59:11 ip-10-0-10-7 k3s[2268670]: I1014 18:59:11.239823 2268670 node_controller.go:330] Skipping node address update for node "ip-10-0-10-7" since cloud provider did not return any
435408:Oct 14 18:59:11 ip-10-0-10-7 k3s[2268670]: I1014 18:59:11.239847 2268670 node_controller.go:454] Successfully initialized node ip-10-0-10-7 with cloud provider
```
And the reason is that, by the time the k3s cloud provider reports to be ready, the node annotations are not set yet by the agent. As a consequence, node addresses update needs to wait until the next iteration. That creates a delay for, among others, the ipv6 address of the node which generates problems in dual-stack mode

**Steps To Reproduce:**

Just deploy k3s

**Expected behavior:**

I'd like addresses to be updated when the node is successfully initialized by the k3s provider

**Actual behavior:**

Addresses are not updated when the node is successfully initialized by the k3s provider. They are updated much later

**Additional context / logs:**

**Backporting**

- [X] Needs backporting to older releases

**Comment by rancher-max** [comment]
The full use case of this will involve validating dual-stack, but for this issue, I validated that the `Skipping node address update` log isn't present, the Successfully initialized node` log is present, and the node providerid and addresses are set correctly. Used commit `702fe24afe3f08f96ebc167313c20c0339a5510f`
