### ISSUE TITLE
[release-1.22] Node stuck in NotReady status after temporary interface disconnect

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4239]
Backport fix for **Node stuck in NotReady status after temporary interface disconnect** to branch **release-1.22**
* https://github.com/k3s-io/k3s/issues/4168#issuecomment-937496817

K3s should exit when a core component experiences a fatal error, but does not - apparently due to a locking bug in our fork of klog.

**Comment by rancher-max** [comment]
Was able to recreate on v1.22.2+k3s1 by running `sudo ifconfig eth0 down && sleep 100 && sudo ifconfig eth0 up` on the k3s leader node. I do not see this issue on v1.22.3-rc3+k3s1 after multiple attempts, so I believe this is resolved.
