### ISSUE TITLE
etcd members fail to join cluster if image import or pull takes more than 5 minutes

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4242]
New members are joined to the cluster as soon as the supervisor starts, but in the case of RKE2 the cluster member won't actually start and join until the image is available - which may be more than the 5 minutes (originally 1 minute) that we give members to proceed with joining. This is only an issue on RKE2 where etcd is run as a static pod, but the code that manages the etcd cluster lives in K3s so it needs to be fixed here.

* https://github.com/rancher/rke2/issues/349

**Comment by rancher-max** [comment]
I validated this on master branch commit id `8271d98a766b060463bc73ef66c5085b5797b4cc`. There was a part that was broken by previous bootstrap changes that has now been resolved.
