### ISSUE TITLE
[release-1.21] etcd members fail to join cluster if image import or pull takes more than 5 minutes

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4244]
Backport fix for **etcd members fail to join cluster if image import or pull takes more than 5 minutes** to branch **release-1.21** and **engine-1.21**
* #4242
* https://github.com/rancher/rke2/issues/1972
* https://github.com/rancher/rke2/issues/1973

**Comment by rancher-max** [comment]
Validated this is working in v1.21.6-rc3+k3s1
