### ISSUE TITLE
KubeletInUserNamespace is not set in unprivileged LXD containers when k3s is run as root

### ISSUE THREAD

**Issue by itoffshore** [k3s-io/k3s#4249]
**Environmental Info:**

K3s Version: 
- k3s version v1.22.2+k3s2 (3f5774b4)
- go version go1.16.8

Node(s) CPU architecture, OS, and Version: 

- Linux u2110 5.13.0-19-generic-Ubuntu SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 21.10 LXD host

Cluster Configuration:

- 1 server (inside LXD on `zfs`)

**Describe the bug:**

- `KubeletInUserNamespace` is not set in unprivileged LXD containers when `k3s` is run as `root`

**Steps To Reproduce:**

- Installed K3s: 
- started rootful `k3s` service inside unprivileged LXD container

**Expected behavior:**

- cluster comes up

**Actual behavior:**

- service fails

**Additional context / logs:**

```
E1019 02:54:37.458733     215 container_manager_linux.go:456] "Updating kernel flag failed (Hint: enable KubeletInUserNamespace feature flag to ignore the error)" err="open /proc/sys/kernel/panic_on_oops: permission denied" flag="kernel/panic_on_oops"
E1019 02:54:37.458850     215 container_manager_linux.go:456] "Updating kernel flag failed (Hint: enable KubeletInUserNamespace feature flag to ignore the error)" err="open /proc/sys/vm/overcommit_memory: permission denied" flag="vm/overcommit_memory"
E1019 02:54:37.459114     215 kubelet.go:1423] "Failed to start ContainerManager" err="[open /proc/sys/kernel/panic_on_oops: permission denied, open /proc/sys/vm/overcommit_memory: permission denied]"
```

**Backporting**

- [X] Needs backporting to older releases

---

Trying to run k3s  `rootless` inside unprivileged LXD on `zfs` is problematic (`btrfs` gives a similar error):
```
WARN[0000] The host root filesystem is mounted as "master:258". Setting child propagation to "" is not supported. 
```

(This causes sandbox creation to fail)

This error disappears when running **rootful** `k3s` inside unprivileged LXD but the service fails due to `KubeletInUserNamespace` feature gate not being enabled. 

An easy way to check if running inside a container is to check `/proc/1/environ` which contains `container=lxc` inside LXD containers.

**Comment by brandond** [comment]
So you're running it as root but in an unprivileged container? How would we detect that in order to enable this feature gate automatically? You're welcome to enable the feature gate yourself if you're running K3s in an odd configuration like this that requires it. I'm honestly not convinced this is something we're doing wrong?

**Comment by itoffshore** [comment]
Inside LXD `/proc/self/uid_map` & `/proc/self/gid_map` can be checked:

privileged LXD (root maps to root):
```
# cat /proc/self/uid_map 
         0          0 4294967295
# cat /proc/self/gid_map 
         0          0 4294967295
```

Unprivileged LXD (root maps to user namespace):
```
[root@u2110 ~]# cat /proc/self/gid_map 
         0    1000000 1000000000
[root@u2110 ~]# cat /proc/self/uid_map 
         0    1000000 1000000000
```

**Comment by brandond** [comment]
That just sounds like user and group remapping; is there anything unique that can be used to identify unprivileged operation?

**Comment by itoffshore** [comment]
if `uid 0` maps to anything other than `0` you are in an unprivileged container

**Comment by itoffshore** [comment]
the `system-upgrade-controller` also works in `rootful` & `rootless` modes with `v0.8.0` - change to the docs [proposed](https://github.com/rancher/docs/pull/3639/commits/aab0d7708f53acf74bc6915ebbb22f4f687c70ff):

![k3s-lxd-upgrade](https://user-images.githubusercontent.com/1141947/139519788-6f6cc52a-39db-4236-aa27-f003e8094bfe.png)

![k3s-lxd-upgrade-unpriv](https://user-images.githubusercontent.com/1141947/139519793-c95d0930-c1fb-4bda-8a00-d29f3643fedb.png)

**Comment by itoffshore** [comment]
no problems in `ubuntu-22.04` LXD containers either with an `ext4 zvol` mounted for `containerd`

**Comment by itoffshore** [comment]
As of LXD `5.6` (& [until kernel `5.19`](https://discuss.linuxcontainers.org/t/disable-idmapped-mount-of-the-container-rootfs/14342)) - you also need to add to `/etc/environment`:
```
LXD_IDMAPPED_MOUNTS_DISABLE=1
```
for `overlayfs` / `stargz` snapshotters to work on `lvm` storage volumes. At the moment with the latest `k3s` I use in the service script:
```
ExecStart=/usr/local/bin/k3s \
    server --snapshotter=stargz \
    --kubelet-arg=feature-gates=KubeletInUserNamespace=true \
    --kube-controller-manager-arg=feature-gates=KubeletInUserNamespace=true \
    --kube-apiserver-arg=feature-gates=KubeletInUserNamespace=true \
    --disable=servicelb --cluster-init
```
![Screenshot_2022-10-02_21-13-15](https://user-images.githubusercontent.com/1141947/193476821-6f94613a-dc37-498b-a192-5efcf5399423.png)

**Comment by dalbani** [comment]
Hi @itoffshore, would you mind sharing the full commands/settings that you used to setup the LXD container and then K3s inside it?
I've tried to replicate your commands in an Ubuntu 22.04 container in LXD 5.0.2, but it doesn't seem to work when starting up K3s.
For example:
```
...
"Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"proc\" to rootfs at \"/proc\": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown" pod="kube-system/helm-install-traefik-crd-zsnr5"
...
```
Did you use a particular LXD container profile for example?

**Comment by itoffshore** [comment]
@dalbani  - this profile should work using `lvm` as the LXD backing store (NB: I used `nftables` for my firewall - so if you use `iptables` your `kernel_modules` in your profile may need to be slightly different:
```
config:
  limits.cpu: "2"
  limits.memory: 2GB
  limits.memory.swap: "false"
  linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,nf_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |-
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw cgroup:rw
    lxc.cgroup.devices.allow=a
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "false"
description: K3s LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    propagation: shared
    type: disk
name: k3s
```

I also made `k3s` work in unprivileged LXD on `zfs` if I created an ext4 `zvol` & mounted it inside the container under `/var/lib/rancher` (wherever `kubelet` runs it expects an `ext4` filesystem) - possibly in the `agent` subdirectory of `/var/lib/rancher` ?

You should probably start with `lvm` until you get it working - also note the service script settings above. Everything seemed to work - I even had the `stargz` snapshotter working.

**Comment by dalbani** [comment]
Thanks @itoffshore, I've indeed managed to run K3s within an unprivileged container, using storage from a ZFS pool being "delegated" (`zoned=on`).

I'm curious though what changes have been applied to the K3s codebase to be able to mark this issue as *completed*, as it happened a couple of weeks ago?

And how does that relate to the so-called "rootless mode" (e.g. commit https://github.com/k3s-io/k3s/commit/6e8284e3d4d3595824ffb5c6fa305a1dd9aa9274)?

**Comment by itoffshore** [comment]
@dalbani  - [this is probably why](https://github.com/k3s-io/k3s/issues/4249#issuecomment-951604936) the issue was closed. Thanks for the new `rootless` note.
