### ISSUE TITLE
K3s secrets encryption key rotation

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4254]
**Is your feature request related to a problem? Please describe.**
Currently users can only enable secrets-encryption, they cannot rotate the keys nor disable encryption

**Describe the solution you'd like**
A new CLI tool that enables the user to disable and rotate encryption keys
Design doc: https://github.com/k3s-io/k3s/issues/3407

**Backporting**

- [X] Needs backporting to older releases

**Comment by dereknola** [comment]
Moved back to v1.22.5 due to underlying bootstrap changes.

**Comment by mdrahman-suse** [comment]
Validated in k3s master as per comment https://github.com/k3s-io/k3s/pull/4372#issuecomment-995302477

**Comment by mdrahman-suse** [comment]
Validated in k3s RC v1.21.8-rc1+k3s1 and v1.22.5-rc1+k3s1 as per comment #4372 (comment)

**Comment by lazzio7** [comment]
Good morning,

I'd like to ask regarding secret encryption feature..

i implemented it on our k3s cluster , but when i want recreate multiple times im getting mentioned errors 
`FATA[0000] see server log for details: https://127.0.0.1:6443/v1-k3s/encrypt/config: 400 Bad Request secrets-encrypt error ID 11737 ` as it is describe on "Secrets Encryption Test Plan"
is there any update about this feature please?

Thank You

**Comment by brandond** [comment]
@lazzio7 please open a new discussion topic for your question.
