### ISSUE TITLE
Enable etcd-snapshot to use `config.yaml` flags.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4284]
**Is your feature request related to a problem? Please describe.**

etcd-snapshot is not able to use config.yaml values to store s3 credentials.
**Describe the solution you'd like**

Enable etcd-snapshot to use config.yaml values.
**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [X] Needs backporting to older releases

**Comment by ShylajaDevadiga** [comment]
Validated using commit id d85b2468ea9df3187cb230f503bd41c4cfa0f842
k3s version v1.22.3+k3s-d85b2468
