### ISSUE TITLE
Cluster reset does not update the peer addresses

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#4296]
**Environmental Info:**
K3s Version: master/v1.21/v1.20/v1.19

Cluster Configuration:
1 node cluster

**Describe the bug:**

When user changes the IP of the node and try cluster-reset to restore the state of the cluster, etcd complains with the following error:
```
INFO[0103] Failed to test data store connection: this server is a not a member of the etcd cluster. Found [ubuntu-focal-95aeb14b=https://10.0.0.100:2380], expect: ubuntu-focal-95aeb14b=10.0.0.101
```
**Steps To Reproduce:**
- Install K3s
- change the IP of the node
- restart k3s and run cluster-reset

**Expected behavior:**
The cluster should run normally after cluster-reset

**Actual behavior:**
- the cluster hangs when the user run cluster-reset

**Backporting**

- [x] Needs backporting

**Comment by ShylajaDevadiga** [comment]
Validated using commit id: d85b2468ea9df3187cb230f503bd41c4cfa0f842
```
k3s version v1.22.3+k3s-d85b2468
```

**Comment by ShylajaDevadiga** [comment]
Validated using rc v1.22.4-rc1+k3s1
