### ISSUE TITLE
Protect packaged helm charts from upgrade via Rancher UI

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4315]
The Rancher UI currently suggests upgrades and allows edits of Helm charts for packaged components. We should protect these charts so that they cannot be edited via the Rancher UI, and it does not suggest upgrades if a matching chart name is found in a chart repo.

As per @vincent99 we could do this by setting an annotation in the Helm release data:
https://github.com/rancher/rancher/issues/35256#issuecomment-950018715

We should confirm with the Rancher team that this is the correct and best way to do this, and then figure out how to do so. A Helm plugin (similar to what we did for [helm-set-status](https://github.com/k3s-io/helm-set-status)) may be the easiest thing to do?

**Comment by rancher-max** [comment]
Have not fully validated yet on master branch (slated for k8s 1.23), but will do that when the PR is merged and then close this issue. I opened a backport for 1.22 which I closed with comments and linked to the PR that fixes it, and will move this milestone to 1.23.

**Comment by rancher-max** [comment]
#### Validated on master branch commitid `2f3bfc27c094ed81a2faf1e06e302e403ab9eab0`

- Confirmed traefik chart version is 10.3.001
- Confirmed no upgrade shown in rancher UI on both fresh installs and upgrades
- Confirmed it shows Managed on rancher UI on fresh installs and after an upgrade:
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/55997940/145852926-047375e9-f9f2-47f1-a409-7020605d87c3.png">
