### ISSUE TITLE
Add Ability to Trigger Cert Regeneration for DynamicListener

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#4349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

We need the ability to trigger certificate regeneration for the dynamic listener

**Describe alternatives you've considered**

**Additional context**

Needed for certificate rotation in k3s.

#2636 

**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
I believe this was validated as part of cert rotation on v1.23.1, v1.22.5, and v1.21.8 so I am closing this out.
