### ISSUE TITLE
Flannel wireguard backend doesn't support dual-stack setup

### ISSUE THREAD

**Issue by sjoerdsimons** [k3s-io/k3s#4364]
Currently the flannel backend doesn't support dual-stack operation; It doesn't end up complaining during setup the the wireguard setup doesn't allow ipv6 traffic through the wireguard tunnel

**Comment by brandond** [comment]
cc @manuelbuil I think we have an existing issue for updating the wireguard backend?

**Comment by manuelbuil** [comment]
Flannel+Wireguard does not support dual-stack in upstream flannel. This PR: https://github.com/flannel-io/flannel/pull/1230 is making wireguard an officially supported backend for flannel. I asked the author whether he'd be interested to provide dual-stack support and he was positive about it. But until then, it is not supported

**Comment by sjoerdsimons** [comment]
Yeah if you look at the linked MR (#4365) as well as the linked flannel-io/flannel#1501 then you'll see those add the necessary support to flannel to make the extension backend dual-stacked first (hence #4365 being in draft state).. Maybe the direct wireguard backend will land in flannel upstream (first), but that's been ongoing for quite a while so this may be a faster path (and the changes in k3s itself are rather small).  I guess we'll see :)

**Comment by manuelbuil** [comment]
That PR was unfortunately forgotten by the upstream community. But I'm committed to review it today and hopefully have it merged before the end of the week :) (maybe too optimistic...)

**Comment by sjoerdsimons** [comment]
Hah didn't notice you were the reviewer; The changes to flannel for the extension backend  are still useful even if the wireguard backend goes native. But I guess given that your preferred solutions for dual-stacked wireguard in k3s would be to go via the native wireguard backend as soon as that lands then rather then the current extension backend? (I'm happy to have a look at adding dual-stack support on top of the outstanding flannel PR given all the required bits needed from the extension backend are still reasonably fresh)

**Comment by manuelbuil** [comment]
He is actually pointing at your PR --> https://github.com/flannel-io/flannel/pull/1230#discussion_r740626207

I think your solution is faster but it would be "deprecated" as soon as we move to the native wireguard backend, right? I'd say, let's try to merge the "native wireguard backend" ASAP, so that we can unblock you. I'll get into the review right after breakfast :). You are welcome to review it too!

**Comment by sjoerdsimons** [comment]
@manuelbuil fwiw update the (draft) MR to now take advantage of the upstream wireguard backend.

**Comment by prometheanfire** [comment]
It looks like upstream flannel wireguard now supports ipv6, I think...  Is there anything blocking support in k3s as well?

**Comment by euank** [comment]
Gentle ping on this issue, and a couple questions:

1. Would an external contribution be welcome here? It seems to me like the implementation will be relatively easy, and most of the work will just be in testing it, and I'm happy to give that a go if it would help.
2. Would it be better to fully replace `wg-add.sh` now, or to keep it as a second backend type to give people a chance to migrate? i.e. should `--flannel-backend=wireguard` immediately move over to the new setup, possibly breaking existing clusters, or should we support `--flannel-backend=wireguard` and `--flannel-backend=wireguard-native` side-by-side for a few releases? Maybe `--flannel-backend=wireguard-legacy` and `=wireguard`, requiring people to switch to `-legacy` on update to not break?

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 483eadb59a499fe8173d59714f05045f8a3bc2bf
```
ubuntu@ip-192-168-71-132:~$ k3s -v
k3s version v1.23.5+k3s-483eadb5 (483eadb5)
```
Configured a two node cluster with one server one agent, verified the connections are open and inter-node communication is successful
```
ubuntu@ip-192-168-71-132:~$ k3s -v
k3s version v1.23.5+k3s-483eadb5 (483eadb5)

ubuntu@ip-192-168-71-132:~$ kubectl get nodes
NAME                STATUS   ROLES                  AGE    VERSION
ip-192-168-71-132   Ready    control-plane,master   16h    v1.23.5+k3s-483eadb5
ip-192-168-84-174   Ready    <none>                 6h4m   v1.23.5+k3s-483eadb5
ubuntu@ip-192-168-71-132:~$ sudo wg show
interface: flannel-wg
  public key: NID4J7J+QpLo9It/Hx8NJaag5/uN1OGmfEjuw75NjEk=
  private key: (hidden)
  listening port: 51820

peer: zkCM4NONsCC4hGsFhfg4seP5cBjEqDqU4Me+7d0NdHw=
  endpoint: 192.168.84.174:51820
  allowed ips: 10.42.1.0/24
  latest handshake: 1 minute, 39 seconds ago
  transfer: 150.81 KiB received, 137.46 KiB sent
  persistent keepalive: every 25 seconds

interface: flannel-wg-v6
  public key: NID4J7J+QpLo9It/Hx8NJaag5/uN1OGmfEjuw75NjEk=
  private key: (hidden)
  listening port: 51821

peer: zkCM4NONsCC4hGsFhfg4seP5cBjEqDqU4Me+7d0NdHw=
  endpoint: [2600:1f1c:ab4:ee20:39a2:9095:f508:782d]:51821
  allowed ips: 2001:cafe:42:1::/64
  latest handshake: 46 seconds ago
  transfer: 54.94 KiB received, 15.28 KiB sent
  persistent keepalive: every 25 seconds
ubuntu@ip-192-168-71-132:~$ 
```

```
test-deployment-7cb7645c5d-jncx8          1/1     Running   0          94s   10.42.0.9    ip-192-168-71-132   <none>           <none>
test-deployment-7cb7645c5d-w5rhg          1/1     Running   0          94s   10.42.1.4    ip-192-168-84-174   <none>           <none>
```
```
$ kubectl exec -it test-deployment-7cb7645c5d-jncx8  -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8921 qdisc noqueue state UP group default 
    link/ether 6a:fc:fc:25:9b:df brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.0.9/24 brd 10.42.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:cafe:42::9/64 scope global 
```
```
ubuntu@ip-192-168-71-132:~$ kubectl exec -it test-deployment-7cb7645c5d-w5rhg -- ping 10.42.0.9
PING 10.42.0.9 (10.42.0.9) 56(84) bytes of data.
64 bytes from 10.42.0.9: icmp_seq=1 ttl=62 time=0.494 ms
64 bytes from 10.42.0.9: icmp_seq=2 ttl=62 time=0.376 ms
64 bytes from 10.42.0.9: icmp_seq=3 ttl=62 time=0.364 ms
^C
--- 10.42.0.9 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2029ms
rtt min/avg/max/mdev = 0.364/0.411/0.494/0.058 ms
ubuntu@ip-192-168-71-132:~$ kubectl exec -it test-deployment-7cb7645c5d-w5rhg -- ping -6 2001:cafe:42::9
PING 2001:cafe:42::9(2001:cafe:42::9) 56 data bytes
64 bytes from 2001:cafe:42::9: icmp_seq=1 ttl=62 time=0.597 ms
64 bytes from 2001:cafe:42::9: icmp_seq=2 ttl=62 time=0.401 ms
^C
--- 2001:cafe:42::9 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1026ms
rtt min/avg/max/mdev = 0.401/0.499/0.597/0.098 ms
ubuntu@ip-192-168-71-132:~$ 
```
