### ISSUE TITLE
DNF Update fails due to dependency conflicts on AlmaLinux 8

### ISSUE THREAD

**Issue by nq0m** [k3s-io/k3s#4366]
**Environmental Info:**
K3s Version: 
k3s version v1.21.4+k3s1 (3e250fdb)

Node(s) CPU architecture, OS, and Version: 
Linux awx.servers.test-net.work 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 11:28:53 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single-Node Cluster

**Describe the bug:**
Cannot Yum Update due to Dependency Errors

**Steps To Reproduce:**
Upon running dnf update on AlmaLinux 8 (RHEL 8 Clone), dependency errors prevent the update

**Expected behavior:**
Successful dnf update

**Actual behavior:**
Package k3s-selinux-0.4-1.el8.noarch requires container-selinux < 2:2.164.2, however AlmaLinux is up to 2:2.167.0

**Comment by brandond** [comment]
You might see if this works better with https://github.com/k3s-io/k3s-selinux/releases/tag/v0.5.testing.1 - there were some unfortunate changes made to the container-selinux package that we are trying to work around.
