### ISSUE TITLE
[k3s-upgrade] Does not properly Upgrade master with server + agent running

### ISSUE THREAD

**Issue by Lol3rrr** [k3s-io/k3s#4367]
**Environmental Info:**
K3s Version: 

v1.19.4+k3s1

Node(s) CPU architecture, OS, and Version: 

* Linux knode1 5.10.17-v7l+ armv7l GNU/Linux

Cluster Configuration:

* 1 node as server + agent
* 1 node only as agent 

**Describe the bug:**

When using the k3s-upgrade for automatic system upgrades, it fails to correctly locate the running instance for the master node, because it is running both the master and the agent and therefore receives 2 processes when looking for them.
This causes the process lookups to fail leading to it erroring out and doing nothing

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

Expected it to either only use one of the Process or handle them one after another, but considering that they should point to the same underlying binary it really does not make a difference

**Actual behavior:**

It fails to locate the Binary itself or actually obtain any useful information about the process because it does not format/seperate the two ids correctly leading to other problems down the line.

**Additional context / logs:**

Output from the upgrade container:
```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $1}'
[INFO]  K3S binary is running with pid 388
569
+ K3S_PID='388
569'
+ '[' -z '388
569' ]
+ info 'K3S binary is running with pid 388
569'
+ echo '[INFO] ' 'K3S binary is running with pid 388
569'
+ awk '{print $1}'
+ cat /host/proc/388 569/cmdline
+ head -n 1
cat: read error: Is a directory
cat: can't open '569/cmdline': No such file or directory
+ K3S_BIN_PATH=
+ '[' '388
569' '==' 1 ]
+ '[' -z  ]
+ fatal 'Failed to fetch the k3s binary path from process 388
569'
+ echo '[ERROR] ' 'Failed to fetch the k3s binary path from process 388
569'
[ERROR]  Failed to fetch the k3s binary path from process 388
569
+ exit 1
```

**Comment by brandond** [comment]
It is not supported to run multiple instances of k3s on a single node, except when running them completely containerized as in K3d. How did you get it to even start running like this?

**Comment by brandond** [comment]
Oh, I see. You're on a very old version of k3s where there could be multiple pids with K3s in the process name. This is unrelated to the server also hosting workloads as an agent does. Upgrade your K3s version (manually if necessary) and you should no longer see this issue.

**Comment by Lol3rrr** [comment]
Okay, Im going to try and update it manually and see if that all works out. Thanks for the help already

**Comment by Lol3rrr** [comment]
Just a quick question, after which version should this work again? @brandond

**Comment by Lol3rrr** [comment]
Thanks for your help, in the End it turned out to be a minor missconfiguration on my part that I must have made a long while back but now everything is working as expected, thanks again for your help
