### ISSUE TITLE
Use plain channel send or receive   SCC-S1000 for pkg/agent/tunnel/tunnel.go

### ISSUE THREAD

**Issue by xiaods** [k3s-io/k3s#4369]
**Environmental Info:**
K3s Version:  upstream

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

https://github.com/k3s-io/k3s/blob/master/pkg/agent/tunnel/tunnel.go#L96

use deepsource.io SaaS service to scan, it reports:
should use for range instead of for { select {} } (S1000)go-staticcheck

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

the code should be refactor

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
PR welcome.

**Comment by brandond** [comment]
Closing; nothing to test since it's just a refactor to meet style guide.
