### ISSUE TITLE
k3s Failing to install on YHKYLIN-OS 

### ISSUE THREAD

**Issue by sixinyiyu** [k3s-io/k3s#4371]
Fresh install of YHKYLIN-OS Linux version 4.19.90-17.ky10.x86_64.

Ran the following commands:

```
curl -sfL https://get.k3s.io | sh -
```

Output was the following:

```
[root@localhost ~]# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.21.5+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/sha256sum-amd64.txt

```

this no service of k3s

**Comment by brandond** [comment]
See if you can successfully `curl -s https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/sha256sum-amd64.txt` - I suspect there is a firewall (great or otherwise) blocking your access to Github.
