### ISSUE TITLE
When passing s3 params in config, etcd-snapshot subcommands does not honor params passed in config file

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#4379]
**Environmental Info:**
K3s Version: 
v1.22.3-rc1+k3s1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04. OS not applicable to reproduce

Cluster Configuration:
Single or multi node

**Describe the bug:**
When s3 params are stored in config file, **k3s etcd-snapshot save** subcommand does not use s3 params from config.yaml and store the snapshot in s3 bucket passed.
```
sudo k3s etcd-snapshot save
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Applying CRD addons.k3s.cattle.io            
INFO[0000] Applying CRD helmcharts.helm.cattle.io       
INFO[0000] Applying CRD helmchartconfigs.helm.cattle.io 
INFO[0000] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635805643 
{"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635805643.part"}
{"level":"info","logger":"client","msg":"opened snapshot stream; downloading"}
{"level":"info","msg":"fetching snapshot","endpoint":"https://127.0.0.1:2379"}
{"level":"info","logger":"client","msg":"completed snapshot read; closing"}
{"level":"info","msg":"fetched snapshot","endpoint":"https://127.0.0.1:2379","size":"3.4 MB","took":"now"}
{"level":"info","msg":"saved","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635805643"}
INFO[0000] Saving current etcd snapshot set to k3s-etcd-snapshots ConfigMap 
```

Without **save** subcommand the snapshot uses the params in config.yaml and works as expected
```
$ sudo k3s etcd-snapshot 
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Applying CRD addons.k3s.cattle.io            
INFO[0000] Applying CRD helmcharts.helm.cattle.io       
INFO[0000] Applying CRD helmchartconfigs.helm.cattle.io 
INFO[0000] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635804680 
{"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635804680.part"}
{"level":"info","logger":"client","msg":"opened snapshot stream; downloading"}
{"level":"info","msg":"fetching snapshot","endpoint":"https://127.0.0.1:2379"}
{"level":"info","logger":"client","msg":"completed snapshot read; closing"}
{"level":"info","msg":"fetched snapshot","endpoint":"https://127.0.0.1:2379","size":"2.0 MB","took":"now"}
{"level":"info","msg":"saved","path":"/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-31-54-1635804680"}
INFO[0000] Saving etcd snapshot on-demand-ip-172-31-31-54-1635804680 to S3 
INFO[0000] Checking if S3 bucket "REDACTED"  exists 
INFO[0001] S3 bucket "REDACTED"  exists            
INFO[0001] S3 upload complete for on-demand-ip-172-31-31-54-1635804680 
INFO[0001] Saving current etcd snapshot set to k3s-etcd-snapshots ConfigMap 
```
Similarly any subcommand like delete does not honor values in config.yaml

**Steps To Reproduce:**

- Create /etc/rancher/k3s/config.yaml with below params

etcd-s3: "true"
etcd-s3-bucket: "REDACTED" 
etcd-s3-access-key: "REDACTED"                                           
etcd-s3-secret-key: "REDACTED" 
    
- Install k3s

- Run **k3s etcd-snapshot save** command
- Run **k3s etcd-snapshot** command

**Expected behavior:**
**k3s etcd-snapshot save** should use params from config.yaml as **k3s etcd-snapshot** command does

**Actual behavior:**
**k3s etcd-snapshot save** does not use params from config.yaml and create snapshot locally only.

**Backporting**
- [* ] Needs backporting to older releases
- [* ] Needs backporting to rke2 releases as well

**Comment by brandond** [comment]
As far as I can tell this should work as per https://github.com/k3s-io/k3s/commit/f98934980d355d52a5c971106635ae100898a523 and https://github.com/k3s-io/k3s/commit/dd4b36e034f312cb03221fa4bb2b7070d82c97fa

**Comment by brandond** [comment]
Ah, its because of this:
https://github.com/k3s-io/k3s/blob/f1622129e4ebce40bf901322d53dc7b6a28a3373/pkg/configfilearg/parser.go#L24-L27

in this case `save` is the last arg, so the `After` does not match and the parser doesn't add any flags.

**Comment by rancher-max** [comment]
#### Validated using release-1.22 branch commit `f1b429f9ce5075c2ab794b7e274854b248a76d63`

- Performed the steps mentioned in the issue which now pass with both the `save` command and leaving that out
- Confirmed including other args such as `etcd-s3-folder` also work
- Confirmed I can update the config.yaml file without restarting k3s and take a new snapshot and it will use the updated values
