### ISSUE TITLE
Store arbitrary metadata with etcd snapshots 

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#4380]
**Is your feature request related to a problem? Please describe.**
Today, when K3s takes `etcd` snapshots, it does not include any metadata with these snapshots. It can be desirable to take etcd snapshots and keep metadata with the snapshots.

**Describe the solution you'd like**
When an etcd snapshot is taken, there should be a method to store additional metadata into the `k3s-etcd-snapshots` configmap along with the etcd snapshot name, so as to provide association. This metadata should be able to be sourced from a ConfigMap that exists within the cluster that the snapshot is being taken of.

Snapshot metadata in the configmap should also indicate "status" of the snapshot, i.e. whether it's successful/failed, still on disk, etc.

**Describe alternatives you've considered**
Storing metadata directly from disk rather than from ConfigMap.

**Additional context**
This is required for the Rancher v2 Provisioning Framework parity enhancement with existing RKE(1) provisioning.

**Backporting**
- [X] Needs backporting to older releases

**Comment by rancher-max** [comment]
#### Validated on master branch commit `2f3bfc27c094ed81a2faf1e06e302e403ab9eab0`

- This appears to be working, though is a bit unclear to a human reader. Confirmed this is OK as the consumption of this configmap is specifically not designed for human consumption.
```
$ k describe cm -n kube-system k3s-etcd-snapshots
Name:         k3s-etcd-snapshots
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
local-on-demand-ip-172-31-4-226-1639414135:
----
{"name":"on-demand-ip-172-31-4-226-1639414135","location":"file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-4-226-1639414135","nodeName":"ip-172-31-4-226","createdAt":"2021-12-13T16:48:55Z","size":2007072,"status":"successful"}
local-on-demand-ip-172-31-4-226-1639414410:
----
{"name":"on-demand-ip-172-31-4-226-1639414410","location":"file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-4-226-1639414410","nodeName":"ip-172-31-4-226","createdAt":"2021-12-13T16:53:30Z","size":2449440,"status":"successful"}
local-on-demand-ip-172-31-4-226-1639414471:
----
{"name":"on-demand-ip-172-31-4-226-1639414471","location":"file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-4-226-1639414471","nodeName":"ip-172-31-4-226","createdAt":"2021-12-13T16:54:31Z","size":2547744,"status":"successful"}
s3-on-demand-ip-172-31-4-226-1639414410:
----
{"name":"on-demand-ip-172-31-4-226-1639414410","nodeName":"s3","size":2449440,"status":"successful","s3Config":{"endpoint":"s3.amazonaws.com","bucket":"mybucket","region":"us-east-2","folder":"newsnap"}}

BinaryData
====

Events:  <none>
```
- Pruning without passing s3 info only removes local according to the retention count
- Pruning with passing s3 info prunes both local and s3 snapshots
- In both above cases, configmap is updated accordingly and is correct
- Forcing a failure (by pressing ctrl+c midway through an s3 snapshot upload) updates the configmap correctly with the base64 encoded error
- Pruning after a failure is NOT correctly pruning the failed attempts. Tracking this as its own issue: https://github.com/k3s-io/k3s/issues/4738
- Having snapshots of multiple different names correctly only prunes based on the name given
