### ISSUE TITLE
K3s 1.21.4-k3s1 version modified certificate expiration time does not take effect

### ISSUE THREAD

**Issue by YibiaoWu** [k3s-io/k3s#4390]
**Environmental Info:**
K3s Version: 

k3s version v1.21.4+k3s- (3e250fd)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 

Linux k3s-n1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 servers

**Describe the bug:**

After modifying the expiration time of the certificate file generated by k3s, the recompilation and installation will not take effect

**Steps To Reproduce:**

- Installed K3s: 
- wget https://github.com/k3s-io/k3s/archive/refs/tags/v1.21.4+k3s1.tar.gz
- tar -xf v1.21.4+k3s1.tar.gz && cd k3s-1.21.4-k3s1

- Major modification files
- vendor/github.com/rancher/dynamiclistener/cert/cert.go
- maxAge := time.Hour * 24 * 365 * 100         // one year self-signed certs
- NotAfter:     time.Now().Add(duration365d * 100).UTC()
- vendor/github.com/rancher/dynamiclistener/factory/cert_utils.go
- All NotAfter places
- NotAfter:     time.Now().Add(time.Hour * 24 * 365 * 100).UTC(),

- Annotate the following content, recompile
![image](https://user-images.githubusercontent.com/92915249/140054128-0ceb9627-ee1d-423c-a541-9b3017ed6e7a.png)

$ make 
$ cp dist/artifacts/k3s /usr/local/bin/
$ INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="server --data-dir=/data/k3s --docker " ./install.sh

**Expected behavior:**

All certificates expire after 100 years

**Actual behavior:**

$ for i in `ls /data/k3s/server/tls/*.crt`; do echo $i; openssl x509 -enddate -noout -in $i; done
/data/k3s/server/tls/client-admin.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-auth-proxy.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-ca.crt
notAfter=Nov  1 11:47:51 2031 GMT
/data/k3s/server/tls/client-controller.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-k3s-cloud-controller.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-k3s-controller.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-kube-apiserver.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-kube-proxy.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/client-scheduler.crt
notAfter=Nov  3 11:47:51 2022 GMT
/data/k3s/server/tls/request-header-ca.crt
notAfter=Nov  1 11:47:51 2031 GMT
/data/k3s/server/tls/server-ca.crt
notAfter=Nov  1 11:47:51 2031 GMT
/data/k3s/server/tls/serving-kube-apiserver.crt
notAfter=Nov  3 11:47:51 2022 GMT

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by dweomer** [comment]
> **Describe the bug:**
> 
> After modifying the expiration time of the certificate file generated by k3s, the recompilation and installation will not take effect

The "code" below that you have shared does not modify existing certificates but the parameters for creating new ones (which only get created when they are missing or about to expire). By the way you have formatted your Steps to Reproduce it would seem that you have installed k3s before modifying the source, thus it seems likely to me that you are inspecting the original certificates created with the unmodified code.

> **Steps To Reproduce:**
> 
> * Installed K3s:
> * wget https://github.com/k3s-io/k3s/archive/refs/tags/v1.21.4+k3s1.tar.gz
> * tar -xf v1.21.4+k3s1.tar.gz && cd k3s-1.21.4-k3s1
> * Major modification files
> * vendor/github.com/rancher/dynamiclistener/cert/cert.go
> * maxAge := time.Hour * 24 * 365 * 100         // one year self-signed certs
> * NotAfter:     time.Now().Add(duration365d * 100).UTC()
> * vendor/github.com/rancher/dynamiclistener/factory/cert_utils.go
> * All NotAfter places
> * NotAfter:     time.Now().Add(time.Hour * 24 * 365 * 100).UTC(),
> * Annotate the following content, recompile
>   ![image](https://user-images.githubusercontent.com/92915249/140054128-0ceb9627-ee1d-423c-a541-9b3017ed6e7a.png)
> 
> $ make $ cp dist/artifacts/k3s /usr/local/bin/ $ INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="server --data-dir=/data/k3s --docker " ./install.sh
> 
> **Expected behavior:**
> 
> All certificates expire after 100 years

This would be ill-advised.

> **Actual behavior:**
> 
> $ for i in `ls /data/k3s/server/tls/*.crt`; do echo $i; openssl x509 -enddate -noout -in $i; done /data/k3s/server/tls/client-admin.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-auth-proxy.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-ca.crt notAfter=Nov 1 11:47:51 2031 GMT /data/k3s/server/tls/client-controller.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-k3s-cloud-controller.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-k3s-controller.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-kube-apiserver.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-kube-proxy.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/client-scheduler.crt notAfter=Nov 3 11:47:51 2022 GMT /data/k3s/server/tls/request-header-ca.crt notAfter=Nov 1 11:47:51 2031 GMT /data/k3s/server/tls/server-ca.crt notAfter=Nov 1 11:47:51 2031 GMT /data/k3s/server/tls/serving-kube-apiserver.crt notAfter=Nov 3 11:47:51 2022 GMT

As mentioned above, I think you are inspecting the certificates generated on the original install. If you run `k3s-uninstall.sh` and then reinstall your modified version of k3s you will likely get the results that you expect.

---

First time, I think, that I have ever seen a bug report against local modifications.
