### ISSUE TITLE
install: /sbin/transactional-update => /usr/sbin/transactional-update for sle-micro

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#4402]
**Environmental Info:**
K3s Version: **all**

Node(s) CPU architecture, OS, and Version: **SLE-MicroOS**

Cluster Configuration: **n/a**

**Describe the bug:**
`install.sh` incorrectly checks for `transactional-update` in `/sbin` instead of `/usr/sbin`

**Steps To Reproduce:**
- attempt to install via https://get.k3s.io
- watch it fail because it looks for `transactional-update` in the wrong place

**Expected behavior:**
the installation works

**Actual behavior:**
the installation does not work

**Additional context / logs:**
n/a

**Comment by rancher-max** [comment]
Validated by curl'ing k3s install script on SLE Micro 5.1. I saw this succeed and successfully install k3s.
