### ISSUE TITLE
Add IPv6 to existing cluster

### ISSUE THREAD

**Issue by IceeMC** [k3s-io/k3s#4404]
Hi, I have an existing K3S cluster, I have recently acquired IPv6 address space, I cannot change the pod CIDRs to allow it. Flannel is halfway broken. How can I add IPv6 to existing cluster, which is strictly on IPv4, I do not want to re-create my cluster either, that is too much of a hassle.

**Comment by IceeMC** [comment]
Calico doesn’t work, any CNI i’ve found hasn’t worked at all. I’m getting quite angry why you can’t add a pod CIDR for IPV6 when clearly you should be able to

**Comment by brandond** [comment]
The Kubernetes PodCIDR IPAM doesn't currently support this. It will not add additional CIDRs once the node already has one assigned. This means that IPv6 must be enabled when the cluster is first created, not after the fact.

**Comment by IceeMC** [comment]
How do i go about this!

**Comment by brandond** [comment]
Uninstall and reinstall k3s, or build a new cluster on separate nodes, with IPv6 configured when bringing up the first server.
