### ISSUE TITLE
Reserve Compute Resources for agent not work. 

### ISSUE THREAD

**Issue by supermanhuyu** [k3s-io/k3s#4405]
**Environmental Info:**
K3s Version:  v1.20.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux 4.15.0-101-generic Ubuntu  x86_64 GNU/Linux

Cluster Configuration:  2 servers, 1 agents
```
root@prod-world-core-2:/var/lib/rancher/k3s# kubectl get nodes -o wide 
NAME                 STATUS   ROLES                       AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
prod-world-apigw-1   Ready    <none>                      35m    v1.20.4+k3s1   172.17.11.142   <none>        Ubuntu 18.04.4 LTS   4.15.0-101-generic   docker://19.3.6
prod-world-core-2    Ready    control-plane,etcd,master   217d   v1.20.4+k3s1   172.17.11.140   <none>        Ubuntu 18.04.4 LTS   4.15.0-96-generic    docker://19.3.6
prod-world-db-1      Ready    control-plane,etcd,master   168d   v1.20.4+k3s1   172.17.11.145   <none>        Ubuntu 18.04.5 LTS   4.15.0-96-generic    docker://19.3.6

```

**Describe the bug:**
Reserve Compute Resources for agent not work. 

**Steps To Reproduce:**
for master it works.
```
root@prod-world-core-2:~# cat /etc/systemd/system/k3s.service
ExecStart=/usr/local/bin/k3s \
        server \
        ...
        '--kubelet-arg=eviction-hard=memory.available<2000Mi' \

root@prod-world-core-2:~# kubectl describe node prod-world-core-2
Addresses:
  InternalIP:  172.17.11.140
  Hostname:    prod-world-core-2
Capacity:
  cpu:                16
  memory:             16422896Ki
Allocatable:
  cpu:                16
  memory:             14374896Ki

```

for agent it doesn't work.
```
root@prod-world-apigw-1:~# cat /etc/systemd/system/k3s-agent.service
ExecStart=/usr/local/bin/k3s \
    agent \
    ...
	'--kubelet-arg=eviction-hard=memory.available<500Mi' \

root@prod-world-core-2:~# kubectl describe node prod-world-apigw-1
Addresses:
  InternalIP:  172.17.11.142
  Hostname:    prod-world-apigw-1
Capacity:
  cpu:                4
  memory:             7891936Ki
Allocatable:
  cpu:                4
  memory:             7891936Ki

```

**Expected behavior:**
Reserve Compute Resources for agent works.

**Comment by brandond** [comment]
I don't think that `eviction-hard` does what you want. As far as I know, this just causes it to evict pods if less than the specified amount of memory is available -  I don't think it actually reduces the capacity or allocatable.

> By reserving some memory via --eviction-hard flag, the kubelet attempts to evict pods whenever memory availability on the node drops below the reserved value.

Did you perhaps want to use https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved or https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved ?

**Comment by supermanhuyu** [comment]
@brandond yes, you are right! thanks.  my agent service have some error args before "eviction-hard". so it doesn't works.
