### ISSUE TITLE
k3s check-config iptables issue on debian 11 bullseye

### ISSUE THREAD

**Issue by dominch** [k3s-io/k3s#4406]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux najada 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

Cluster Configuration:
Test cluster with 1 master and 1 node - both on debian 11 bullseye 

**Describe the bug:**
```
curl https://raw.githubusercontent.com/k3s-io/k3s/master/contrib/util/check-config.sh | bash
```
Reports: 
```
System:
- /sbin iptables v1.8.7 (legacy): ok
- swap: disabled
- routes: default CIDRs 10.42.0.0/16 or 10.43.0.0/16 already routed
```
On debian 10 it reported that iptables is not legacy and You immediately know that there is something wrong about iptables and use update-alternatives to switch to that.  Install arptables and ebtables and then switch to legacy: 

```
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set arptables /usr/sbin/arptables-legacy
update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

Without that DNS service is not working on such node (it may be node without coredns). All queries are timmed out and services that relies on naming (like longhorn-system) will not start. 
If k3s script can report problem about iptables on debian11 then it would be much easier to fix it. 

**Steps To Reproduce:**
Just run check config script on plain debian 11 and take a look at iptables section. 

**Expected behavior:**
It should report error about iptables so it's clear that some traffic is blocked. 

**Actual behavior:**
Check config reports ok for iptables when it's not. If You join to cluster You won't get dns on such node.

**Comment by jeanpommier** [comment]
Hi,

**Comment by dominch** [comment]
I already moved to debian 11 if You are asking about that and check-config is still broken (on both current and latest version). Yes - it's ok with iptables legacy, but initially it failed with name resolution so some changes are needed.

**Comment by jeanpommier** [comment]
Actually I tried on debian 11, but check-config was a lot worse, so I stepped back to debian 10.

I'm using iptables-legacy on debian 10, but nervertheless, it seems to be causing trouble.For now, I still haven't figured out exactly what happens, but using top, I can see iptables save & restore operations taking more and more resources, until the node gets unresponsive. Did you ever encouter something like that ?

**Comment by dominch** [comment]
It's not that hard to tweak system to pass almost everything on check-config on debian 11, by just adding sbin to path most is ok, for others You may need some extra packages or configuration. It's worth to upgrade. I think I had your problem on D10,

**Comment by dominch** [comment]
I'm using iptables-legacy. Please note that k3s config check script incorrectly reported wrong version of that (and that was reason for this bug report).
