### ISSUE TITLE
 v1.21.6+k3s1 fails install on FCOS due to missing dnf command

### ISSUE THREAD

**Issue by brokenjacobs** [k3s-io/k3s#4409]
**Environmental Info:**
K3s Version:  v1.21.6+k3s1

Node(s) CPU architecture, OS, and Version: 

Fedora CoreOS

**Describe the bug:**

Installing k3s fails with the following output:
`main: line 548: dnf: command not found`

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

Install proceeds

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brokenjacobs** [comment]
I found:
INSTALL_K3S_SKIP_SELINUX_RPM

Which allows to skip this. I did not see this in the release notes for v1.21.6+k3s1 though.

Doc bug?

**Comment by brandond** [comment]
@dweomer it looks like this came in via https://github.com/k3s-io/k3s/commit/52eb6cac1ccf29260f6a58c80ea231d7bb83f429#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR533 - we check for `dnf` before using it in favor of `yum` up above, but here hardcode it for any EL8 distro.

**Comment by dweomer** [comment]
whoops

**Comment by dweomer** [comment]
I had an outstanding PR for a fix on sle-micro (original changes for which caused this bug) so I rolled it up into that. Included now are github actions tests, via Vagrant, against both Fedora CoreOS and openSUSE MicroOS.

**Comment by brokenjacobs** [comment]
LOL thanks. Long story on the handle.
