### ISSUE TITLE
K3s system pods cannot communicate with API server on AWS Workspace(AL2)

### ISSUE THREAD

**Issue by dmarkey** [k3s-io/k3s#4413]
**Environmental Info:**
K3s Version: 
k3s --version
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
AL2 on AWS Workspaces (intel)

Cluster Configuration:
Single Node

**Describe the bug:**
System pods cannot communicate with the API server:
panic: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.43.0.1:443: i/o timeout

But seems fine from the host:

```
curl --insecure https://10.43.0.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
```

**Steps To Reproduce:**

Install vanilla k8s on an AL2 Amazon workspace.

**Expected behavior:**
That system pods function

**Actual behavior:**
System pods crash.

**Additional context / logs:**

Iptables version:

`iptables v1.8.4 (legacy)`

Iptables rules before attempting to install k3s:

```
[root@a-22vtkk6t9g0d ~]# iptables -L -v -n | cat
Chain INPUT (policy ACCEPT 1595 packets, 203K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 912 packets, 189K bytes)
 pkts bytes target     prot opt in     out     source               destination    
 
```
I understand this AL2 likely has major customisations so it runs on workspaces, so this might be a tricky issue.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by dmarkey** [comment]
Output from curl https://raw.githubusercontent.com/k3s-io/k3s/master/contrib/util/check-config.sh | bash
`Verifying binaries in .:
- sha256sum: sha256sums unavailable
- links: link list unavailable

System:
- /usr/sbin iptables v1.8.4 (legacy): ok
- swap: should be disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

modprobe: FATAL: Module configs not found in directory /lib/modules/4.14.252-195.483.amzn2.x86_64
info: reading kernel config from /boot/config-4.14.252-195.483.amzn2.x86_64 ...

Generally Necessary:
- cgroup hierarchy: cgroups V1 mounted, cpuset|memory controllers status: good
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: pass
`

**Comment by dmarkey** [comment]
Anyone have any clues here by any chance?

**Comment by brandond** [comment]
How many nodes are in your cluster? Are you using iptables (firewalld/ufw)? Have you confirmed that the correct ports are open between nodes in the security group configuration?

**Comment by dmarkey** [comment]
This is a single node configuration, all local traffic. Simply `curl -sfL https://get.k3s.io | sh -`

I don't believe there is a firewall, although I do suspect something funky with iptables. `iptables v1.8.4 (legacy)` should be OK?

**Comment by brandond** [comment]
Can you share more of the logs from the cluster? Which specific "system pods" are crashing?

**Comment by dmarkey** [comment]
Practically everything in `kube-system`

```
NAME                                      READY   STATUS             RESTARTS   AGE
coredns-7448499f4d-cxbp7                  0/1     CrashLoopBackOff   8          29m
local-path-provisioner-5ff76fc89d-b9fvs   0/1     CrashLoopBackOff   9          29m
metrics-server-86cbb8457f-tzt46           0/1     CrashLoopBackOff   9          29m
helm-install-traefik-crd-mx82t            0/1     CrashLoopBackOff   6          29m
helm-install-traefik-8vx8g                0/1     CrashLoopBackOff   6          29m

```
Here's the log line from the local-path-provisioner as an example:

```
time="2021-11-09T14:34:18Z" level=fatal msg="Error starting daemon: Cannot start Provisioner: failed to get Kubernetes server version: Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: i/o timeout" 
```




K3s journalctl log: [log.txt](https://github.com/k3s-io/k3s/files/7505521/log.txt)

If you need anything else lemme know, thanks for the help!

**Comment by jessequinn** [comment]
@dmarkey what was the issue? I am having the same on Yocto.

**Comment by dmarkey** [comment]
Sorry I gave up on AWS workspaces.

**Comment by WS-JordanThomas** [comment]
@dmarkey Did you end up figuring this out outside of AL2? I have this exact same issue for an EC2 instance, single node deployment.
