### ISSUE TITLE
Airgap install doesn't work

### ISSUE THREAD

**Issue by xliangdh** [k3s-io/k3s#4420]
When I do something like this, the airgap install doesn't work, it still downloads the images from registry, How do I do that?
```
$ cp /home/k3s/k3s /usr/local/bin/
$ chmod +x /usr/local/bin/k3s
$ mkdir -p /lvdata/var/lib/rancher
$ mkdir -p /var/lib/rancher
$ mount --bind /lvdata/var/lib/rancher /var/lib/rancher
$ mkdir -p /var/lib/rancher/k3s/agent/images
$ cp /home/k3s/k3s-airgap-images.tar /var/lib/rancher/k3s/agent/images/
$ k3s server
```

**Comment by brandond** [comment]
Can you show which images it's downloading from the internet?

**Comment by xliangdh** [comment]
I'm really sorry that this is a problem with my host environment. The problem has been solved through the following operations
1. Reset the VM
2. Download k3s and k3S-airGap-images.tar.gz again

Thank you very much for taking the time to pay attention to my question
