### ISSUE TITLE
How to correctly set --node-external-ip for HA server setup

### ISSUE THREAD

**Issue by MisterWS** [k3s-io/k3s#4421]
I'm currently working through the steps to set up a HA cluster following the instructions in the Rancher docs [here](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/). I have installed keepalived in order to share a virtual IP address across all 3 server nodes - in this case, each node gets a DHCP-assigned main IP (e.g. `10.0.0.132`) and each node broadcasts using keepalived to `10.0.1.10`, which I have a DNS record set to `k3s.sys.domain.local`. This ensures that I can just point kubectl commands at this DNS record.

My question is: what should I be setting the `--node-external-ip` flag as on each server? Should it be the DHCP-assigned 'real' IP address in the `10.0.0.0/24` range, or should all 3 server nodes be set to the same 'virtual' IP being broadcast by keepalived, `10.0.1.10`? Is `--node-external-ip` meant to be unique?

**Comment by brandond** [comment]
The nodes should never share an IP address for either the private or public IP. --node-external-ip is meant for use in environments such a cloud provider networks where there is a public IP address NATed to the node's private IP address. If you're using an external service to map a VIP to multiple servers, all you should need to add is --tls-san to ensure that the VIP hostname and IP address are valid for the cert used on port 6443.

**Comment by MisterWS** [comment]
Awesome - thanks. I'm already setting `--tls-san` as suggested, but need to set `--node-external-ip` as my machines have several network interfaces and k3s is selecting the wrong one to advertise by default. Appreciate the advice!

**Comment by brandond** [comment]
In that case you might try setting --node-ip instead of --node-external-ip. The external IP is not expected to be actually bound to an interface on the node.

**Comment by markmaker** [comment]
> The external IP is not expected to be actually bound to an interface on the node.

Is that statement correct in all scenarios? 

In the [NodeAddressType doc](https://pkg.go.dev/k8s.io/api/core/v1#NodeAddressType) I read:

```go
        // NodeExternalIP identifies an IP address which is, in some way, intended to be
	// more usable from outside the cluster then an internal IP, though no specific
	// semantics are defined. It may be a globally routable IP, though it is not
	// required to be.
	//
        // External IPs may be assigned directly to an interface on the node, like a
	// NodeInternalIP, or alternatively, packets sent to the external IP may be NAT'ed
	// to an internal node IP rather than being delivered directly (making the IP less
	// efficient for node-to-node traffic than a NodeInternalIP).
```

My case is a HA bare metal cluster with globally routable IP directly assigned to the nodes, no NAT. 

These IP addresses aren't actually used for Kubernetes networking, just for ssh access etc. 

Kubernetes stuff is reachable through KubeVIP assigned floating IPs.

How should I configure it for that scenario?

_Mark

**Comment by brandond** [comment]
I am not aware of any cloud providers that actually assign the externalip to the node, but I suppose it is possible. The intended use of the fields was not documented until mid 2021: https://github.com/kubernetes/kubernetes/commit/4272ac92a761cdd36b5c4c598d34fb965ad79f70

**Comment by markmaker** [comment]
Thanks. 

Just to clarify, there is no cloud provider. It is a bare metal cluster setup on root servers. 

_Mark
