### ISSUE TITLE
[Release-1.22] Update error messaging around using "K10" prefixed --token

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4429]
Backport of https://github.com/k3s-io/k3s/issues/4169 to `release-1.22`

**Comment by mdrahman-suse** [comment]
**Verified on k3s v1.22 Release branch with commit `586ed948dd2978da510e31d1eb5ea8eac4be2990` using the same steps as https://github.com/k3s-io/k3s/issues/4169#issuecomment-964568349 and observed the same expected behavior**
