### ISSUE TITLE
k3s should rotate /etc/rancher/k3s/k3s.yaml when certificates are re-generated

### ISSUE THREAD

**Issue by erulabs** [k3s-io/k3s#4439]
**Is your feature request related to a problem? Please describe.**
When certificates are regenerated, the k3s.yaml can get out-of-date, and leave the user with a `Unable to connect to the server: x509: certificate signed by unknown authority` message. This also makes intentionally rotating the certificates less obvious. Some users have reported this here: https://github.com/k3s-io/k3s/issues/1621

**Describe the solution you'd like**
When k3s starts, it checks the existence of several TLS files in `/var/lib/rancher/k3s/server/tls` - if the server certificate is missing, it will generate a new one (this is excellent, it means `rm -rf /var/lib/rancher/k3s/server/tls` effectively rotates credentials!) - however, it does -not- regenerate /etc/rancher/k3s/k3s.yaml, leaving the user with a broken `k3s kubectl` experience.

**Describe alternatives you've considered**
When I want to rotate credentials now, I call:
```
service k3s stop
rm -vrf /var/lib/rancher/k3s/agent/*.key /var/lib/rancher/k3s/agent/*.crt /etc/rancher/k3s/k3s.yaml /var/lib/rancher/k3s/server/tls
service k3s start
```
Ideally, I should only have to wipe `/var/lib/rancher/k3s/server/tls` and restart k3s, and the cluster would be effectively rotated.

**Additional context**
Some context: We (@erulabs and @pastudan) are behind https://pibox.io - which is a pre-loaded kubernetes cluster, ready to plug-and-play. We make use of k3s, because its excellent, and want the experience to be as quick as possible for users. Thus we pre-install k3s, but for security reasons only want to provision certificates when the user receives the device. While we got this all working, I noticed several users in https://github.com/k3s-io/k3s/issues/1621 having trouble.

**Backporting**
Does not need back porting, this can be a new improvement 👯

**Comment by brandond** [comment]
As far as I know admin kubeconfig is rewritten on every startup:

https://github.com/k3s-io/k3s/blob/d85b2468ea9df3187cb230f503bd41c4cfa0f842/pkg/server/server.go#L101

**Comment by erulabs** [comment]
Hi @brandond - Ah, I suppose it re-writes that file with the correct server CA cert only if the agent certs are also wiped `/var/lib/rancher/k3s/agent/*.key`. 

If you just do:
```
service k3s stop
rm -vrf /etc/rancher/k3s/k3s.yaml /var/lib/rancher/k3s/server/tls
service k3s start
```
then k3s kubectl is broken. I suppose the agent/server-ca.crt needs to be re-generated as well

**Comment by brandond** [comment]
Yes. Deleting the files to force their regeneration is a bit of a hack, so you will need to manually ensure that you're deleting all the correct files. In the future we'll have some CLI commands to manage this.

**Comment by erulabs** [comment]
Ah, just expanding on the script required to force-refresh the k3s certificates:

```
k3s kubectl --insecure-skip-tls-verify -n kube-system delete secret k3s-serving
service k3s stop
rm -vrf /var/lib/rancher/k3s/agent/*.key \
  /var/lib/rancher/k3s/agent/*.crt \
  /etc/rancher/k3s/k3s.yaml \
  /var/lib/ra ncher/k3s/server/tls
```
