### ISSUE TITLE
unable to join secondary master HA member - ETCD connection refused 

### ISSUE THREAD

**Issue by anubisg1** [k3s-io/k3s#4458]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux CZRSC-LAN-SRV02 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux

Cluster Configuration:
3 nodes cluster, trying to setup an HA cluster with embedded etcd

**Describe the bug:**
cannot join 2nd or 3rd node to the cluster

 k3s[13412]: {"level":"warn","ts":"2021-11-11T08:12:36.400Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}

**Steps To Reproduce:**

- install k3s on primary node with:
 curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s server --cluster-init
- obtain primary node token from /var/lib/rancher/k3s/server/node-token
- install secondary node with:
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_TOKEN=K10d3b89ae87119ee7657a75c85c0a1cf097778c5e8c7e15b72af4565039a2095a0::server:9e6da834b9028eebd95c84a69bfe25d3 sh -s - server --server https://192.168.0.30:6443
- secondary node never joins the cluster, logs are spammed with 

Nov 11 08:52:22 CZSRC-LAN-SRV02 k3s[17185]: time="2021-11-11T08:52:22.731018915Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Nov 11 08:52:23 CZSRC-LAN-SRV02 k3s[17185]: {"level":"warn","ts":"2021-11-11T08:52:23.689Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Nov 11 08:52:24 CZSRC-LAN-SRV02 k3s[17185]: {"level":"warn","ts":"2021-11-11T08:52:24.690Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Nov 11 08:52:26 CZSRC-LAN-SRV02 k3s[17185]: {"level":"warn","ts":"2021-11-11T08:52:26.254Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Nov 11 08:52:27 CZSRC-LAN-SRV02 k3s[17185]: {"level":"warn","ts":"2021-11-11T08:52:27.730Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}

**Expected behavior:**
additional servers should join the cluster

**Actual behavior:**
etcd seems to fail to start, k3s cannot connect to the local instance of etcd

**Additional context / logs:**
- standalone master node can be installed on the same machine
- worker agent node can be installed on the same machine

**Comment by brandond** [comment]
Can you attach the complete k3s service logs from both the first server, and the server you're trying to join?

**Comment by anubisg1** [comment]
primary node:

```
root@CZSRC-LAN-SRV01:/home/pi# curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s server --cluster-init
[INFO]  Finding release for channel stable
[INFO]  Using v1.21.5+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
root@CZSRC-LAN-SRV01:/home/pi# kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
czsrc-lan-srv01   Ready    control-plane,etcd,master   30s   v1.21.5+k3s2
```

server 2:

```
33aba84b8b9c257bb2" sh -s - server --server https://192.168.0.30:6443
[INFO]  Finding release for channel stable
[INFO]  Using v1.21.5+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

stuck here until the service is manually stopped.


all syslog and journal logs are attached
[logs.zip](https://github.com/k3s-io/k3s/files/7519338/logs.zip)

**Comment by anubisg1** [comment]
> Can you attach the complete k3s service logs from both the first server, and the server you're trying to join?

i hope the above logs help

**Comment by brandond** [comment]
Your logs are all truncated to 190 characters long. Can you collect them via `journalctl -u k3s --no-pager &> k3s.log` so that they're not missing the end of the messages?

From what I can see though, the second server is unable to reach the first server on the etcd ports. Confirm that you have all the correct ports open on the first node: https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#networking

**Comment by anubisg1** [comment]
let me do that.

in the meantime you can see from here that network connectivity is ok.
The hosts are in the same subnet, there is no firewall in the middle except for iptables which should be handled by k3s anyway.

this is the output from the secondary node after the first was installed and service running correctly

```
root@CZRSC-LAN-SRV03:/home/pi# nmap 192.168.0.21 -p U:8472,T:6443,10250,2379-2380
Starting Nmap 7.80 ( https://nmap.org ) at 2021-11-15 18:46 GMT
Nmap scan report for 192.168.0.21
Host is up (0.00032s latency).

PORT      STATE SERVICE
2379/tcp  open  etcd-client
2380/tcp  open  etcd-server
6443/tcp  open  sun-sr-https
10250/tcp open  unknown
MAC Address: DC:A6:32:B1:74:EF (Raspberry Pi Trading)

Nmap done: 1 IP address (1 host up) scanned in 6.82 seconds

root@CZRSC-LAN-SRV03:/home/pi# telnet 192.168.0.21 2379
Trying 192.168.0.21...
Connected to 192.168.0.21.
Escape character is '^]'.

^C
Connection closed by foreign host.

root@CZRSC-LAN-SRV03:/home/pi# telnet 192.168.0.21 2380
Trying 192.168.0.21...
Connected to 192.168.0.21.
Escape character is '^]'.
^C
Connection closed by foreign host.
```

**Comment by anubisg1** [comment]
attached the logs

logs from master server:
[k3s-master.log](https://github.com/k3s-io/k3s/files/7541009/k3s-master.log)

logs from secondary member after installation fail due to service failing to start:
[k3s-install-fail.log](https://github.com/k3s-io/k3s/files/7541011/k3s-install-fail.log)

logs from secondary member when attempting manual start of k3s:
[k3s-startup-fail.log](https://github.com/k3s-io/k3s/files/7541010/k3s-startup-fail.log)

**Comment by brandond** [comment]
What are you using for storage on these nodes? It appears that the local disk is struggling to keep up with the IO load; there are a number of warnings about etcd operations taking too long, even when there is only a single member in the cluster.

Did you change the IP addresses of your nodes, or do you perhaps have multiple IPs configured on them? The joining node appears to be using an IP address of `192.168.0.195`, but its certificate is only valid for `"127.0.0.1","192.168.0.23","10.43.0.1"`
```console
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.624Z","caller":"raft/raft.go:1530","msg":"e4c0813c987fdb4c switched to configuration voters=(16483316733432552268) learners=(18168891765339884893)"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.625Z","caller":"membership/cluster.go:392","msg":"added member","cluster-id":"afb0a5e986f206a9","local-member-id":"e4c0813c987fdb4c","added-peer-id":"fc24decc339a8d5d","added-peer-peer-urls":["https://192.168.0.23:2380"]}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.625Z","caller":"rafthttp/peer.go:128","msg":"starting remote peer","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.625Z","caller":"rafthttp/pipeline.go:71","msg":"started HTTP pipelining with remote peer","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.626Z","caller":"rafthttp/stream.go:166","msg":"started stream writer with remote peer","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.627Z","caller":"rafthttp/stream.go:166","msg":"started stream writer with remote peer","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.628Z","caller":"rafthttp/peer.go:134","msg":"started remote peer","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.628Z","caller":"rafthttp/stream.go:406","msg":"started stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.628Z","caller":"rafthttp/transport.go:327","msg":"added remote peer","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d","remote-peer-urls":["https://192.168.0.23:2380"]}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.628Z","caller":"rafthttp/stream.go:406","msg":"started stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"e4c0813c987fdb4c","remote-peer-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"info","ts":"2021-11-15T18:52:39.628Z","caller":"etcdserver/server.go:1967","msg":"applied a configuration change through raft","local-member-id":"e4c0813c987fdb4c","raft-conf-change":"ConfChangeAddLearnerNode","raft-conf-change-node-id":"fc24decc339a8d5d"}
Nov 15 18:52:39 CZRSC-LAN-SRV01 k3s[2757]: {"level":"warn","ts":"2021-11-15T18:52:39.663Z","caller":"embed/config_logging.go:270","msg":"rejected connection","remote-addr":"192.168.0.195:50898","server-name":"","ip-addresses":["127.0.0.1","192.168.0.23","10.43.0.1"],"dns-names":["localhost","czrsc-lan-srv03"],"error":"tls: \"192.168.0.195\" does not match any of DNSNames [\"localhost\" \"czrsc-lan-srv03\"] (lookup czrsc-lan-srv03: no such host)"}
```

Also - and this isn't critical, but it is creating a lot of noise - your kernel appears to be missing hugepage support. Are you using a custom-build kernel on these nodes?

**Comment by anubisg1** [comment]
So, in oderder:

1) micro SD card, I have SanDisk Ultra micro SD HC I class 10. I can try to move to SSD or iscsi and see if it makes a difference

2) I'll check that, I have static ip address configured on raspberry pi cmdline.txt. I think that dhcpd might still be running in the background and therefore proving an unwanted secondary dhcp address

3) czrsc-lan-srv03 is the hostname of the secondary server while czrsc-lan-srv01 is the primary. They should resolve to localhost, i do not have a DNS entry for those but I can easily add it.

4) default raspbian kernel. Nothing custom. I only have "arm_64bit=1" under config.txt


I will start with the easiest ones first (validating up address and DNS), then move to storage.

Thank you

**Comment by brandond** [comment]
> czrsc-lan-srv03 is the hostname of the secondary server while czrsc-lan-srv01 is the primary. They should resolve to localhost

This should resolve to the actual IP of the node, not to the loopback address. You might see if correcting that helps.

**Comment by anubisg1** [comment]
so, i can confirm that dhcpcd was the culprit of the second ip address.
take care of that :

Before:
```
root@CZRSC-LAN-SRV01:/etc# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:b1:74:ef brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.21/24 brd 192.168.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.0.226/24 brd 192.168.0.255 scope global secondary dynamic noprefixroute eth0
       valid_lft 79413sec preferred_lft 68613sec
    inet6 fe80::dea6:32ff:feb1:74ef/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether dc:a6:32:b1:74:f0 brd ff:ff:ff:ff:ff:ff
```


after

```
root@CZRSC-LAN-SRV01:/home/pi# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:b1:74:ef brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.21/24 brd 192.168.0.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::118:ebd4:a129:b57e/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether dc:a6:32:b1:74:f0 brd ff:ff:ff:ff:f
```

the DNS part was added too

```
root@CZRSC-LAN-SRV01:/home/pi# nslookup CZRSC-LAN-SRV01
Server:         192.168.0.20
Address:        192.168.0.20#53

Name:   CZRSC-LAN-SRV01.anubisg1.local
Address: 192.168.0.21

root@CZRSC-LAN-SRV01:/home/pi# nslookup CZRSC-LAN-SRV02
Server:         192.168.0.20
Address:        192.168.0.20#53

Name:   CZRSC-LAN-SRV02.anubisg1.local
Address: 192.168.0.22

root@CZRSC-LAN-SRV01:/home/pi# nslookup CZRSC-LAN-SRV03
Server:         192.168.0.20
Address:        192.168.0.20#53

Name:   CZRSC-LAN-SRV03.anubisg1.local
Address: 192.168.0.23
```

now let see if this makes any difference

**Comment by anubisg1** [comment]
it worked

```
root@CZRSC-LAN-SRV01:/home/pi# kubectl get nodes
NAME              STATUS   ROLES                       AGE     VERSION
czrsc-lan-srv01   Ready    control-plane,etcd,master   5m21s   v1.21.5+k3s2
czrsc-lan-srv02   Ready    control-plane,etcd,master   2m1s    v1.21.5+k3s2
czrsc-lan-srv03   Ready    control-plane,etcd,master   55s     v1.21.5+k3s2
```

thanks a lot for your help!
