### ISSUE TITLE
k3s ooming when running iptables

### ISSUE THREAD

**Issue by nimrodishi** [k3s-io/k3s#4460]
**Environmental Info:**
K3s Version: 
```
 $ k3s --version
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 
```
$ uname -a
Linux ip-10-11-11-16.eu-west-1.compute.internal 4.18.0-257.el8.x86_64 #1 SMP Thu Dec 3 22:16:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
Single host server+agent (1)
Created by running:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--kube-apiserver-arg service-node-port-range=1-65535" sh -
```

**Describe the bug:**
Running on a t3.medium ec2 instance (4GB RAM).
I'm running a couple of small releases. The largest is [prometheus](https://prometheus-community.github.io/helm-charts). In no time did I see my actual deployment using (or nearing) to get all system resources.

After some time (I think 3 days) - oom killer kicks in to kill something, but fail. It crashes the machine, and I'm forced to force reboot it from aws console.
After this happened - I started running atop to monitoring the situation. It seems like just before the final crash, k3s-server process starts running multiple iptable process which use a lot of memory (~800-900 Mb). No idea why it does this, or why the oom killer fails to solve the issue.
I have swapping disabled.

**Steps To Reproduce:**
- get a 4GM RAM centos 8 stream machine
- Installed K3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--kube-apiserver-arg service-node-port-range=1-65535" sh -`
- install prometheus from public chart (I'm using a HelmChart yaml file in server/manifests). I tried playing with some of the values to limit prometheus resources, but it really seems to be the iptables.
```
$ cat /var/lib/rancher/k3s/server/manifests/prometheus-helm-chart.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts

  version: 9.4.2

  targetNamespace: monitoring
  valuesContent: |-
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        resources:
          limits:
            memory: 600Mi
        retention: 12h
```
- wait (????)
- machine crashing

**Expected behavior:**
No OOM? no crash?
**Actual behavior:**
Crash
**Additional context / logs:**
some of atops result: https://gist.github.com/nimrodishi/cfade1a30ac92fe192720a52673c2843
(`atop -r /var/log/atop/atop_20211107  -m  202111100450`. I couldn't find a way to get only the last hours binary and upload it. issue start around 05:00)

**Comment by brandond** [comment]
Are you running with swap enabled, by any chance?

**Comment by nimrodishi** [comment]
@brandond disabled (I wrote it somewhere in the wall of text). I remember seeing somewhere an issue about ooming and a recommendation to disable it.

**Comment by nimrodishi** [comment]
After leaving two machines up during the weekend, one with prometheus, and the other without, I do see that only the prometheus running one had issues. I think It's correlated to the retention of prometheus. I'll continue debugging this

**Comment by brandond** [comment]
Since you mentioned iptables you might also take a look at https://github.com/k3s-io/k3s/issues/3117 - but prometheus is certainly memory intensive.

**Comment by nimrodishi** [comment]
going over atop results, see something interesting:
```
1242445       - D  18% iptables-save -t filter
1242582       - D  15% /usr/sbin/iptables -t filter -C KUBE-ROUTER-FORWARD -m comment --comment rule to explicitly ACCEPT traffic that comply to network policies -m mark --mark 0x20000/0x20000 -j ACCEPT --wait
```
looks like k3s uses the `usr/sbin/iptables` instead of (or alongside with?) `/var/lib/rancher/k3s/data/current/bin/aux/iptables`.
Is it possible that the existence of both iptables binaries causes issues and conflict?

Also - it's not prometheus. limiting it's memory and retention changes nothing

**Comment by brandond** [comment]
The host's iptables is used in preference to our packaged iptables. As discussed in #3117, we've seen some broken versions of iptables cause the high CPU load behavior you're describing. You might try uninstalling the host iptables/nftables packages, which will cause k3s to use the known-good ones we package.

**Comment by ChristianCiach** [comment]
> The host's iptables is used in preference to our packaged iptables.

Can this be changed without uninstalling the `nftables` package of the host? We are seeing similar problems with CentOS 8 (not "CentOS Stream")

**Comment by chris93111** [comment]
Hi @ChristianCiach @brandond 
someone success try to use the embedded iptables rather than the os ?

Not possible to remove the standard iptables 1.8.4 on RHEL/Centos

**Comment by brandond** [comment]
Why is it not possible to remove the system iptables package?

**Comment by ChristianCiach** [comment]
@brandond Our IT department insists in adding there own rules using `iptables-service` on system startup :)

**Comment by chris93111** [comment]
@brandond the installation package is protected with dependency
The operation would result in removing the following protected packages: systemd

**Comment by brandond** [comment]
I'm not sure why rhel is still shipping a broken package...
