### ISSUE TITLE
etcd extra args should be supported

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#4462]
Etcd needs to support extra args, like we support for the rest of the embedded components.

Reference:
https://github.com/k3s-io/k3s/blob/bc7cdc78ca2f4331023035727e242f01b760cc6c/pkg/daemons/executor/executor.go#L34

```
2021-11-03T10:02:41.515889233-07:00 stderr F {"level":"info","ts":"2021-11-03T17:02:41.515Z","caller":"etcdmain/config.go:307","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"/var/lib/rancher/rke2/server/db/etcd/config"}
```

**Comment by dweomer** [comment]
This is an argument for external etcd, no?

**Comment by rancher-max** [comment]
#### Validated on master branch commit `ef263bd2b0ecb29c3404cd4b80fcfcf8b4301912`

- Can set multiple `--etcd-arg` parameters when running via binary and see them being used correctly (and blow up correctly if using args like "name" and setting values that shouldn't work)
- Can set `etcd-arg` in config.yaml like the following and see it working (NOTE: do not set data-dir or wal-dir using this argument in practice as it causes failures in your cluster):
```
etcd-arg:
  - 'data-dir=/home/ubuntu/configdata'
  - 'name=maxtestetcd1'
  - 'wal-dir=/home/ubuntu/configwal'
```

**Comment by leisurelyclouds** [comment]
k8s 1.20 need this feature
