### ISSUE TITLE
Increase agent's apiserver ready timeout

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4466]
Increase agent's apiserver ready timeout. Since the agent starts up earlier, the 30 second timeout is causing problems in RKE2 when trying to update K3s for:
* https://github.com/rancher/rke2/issues/1755

**Comment by mdrahman-suse** [comment]
**Verified on k3s Master with commit 535a9196351b65764071a27b7d68ec7497e67e55**
Steps
- Create 1 server and 1 agent node (ubuntu 20.04)
- Install k3s using the commit
- Once the nodes and pods are up, use `systemctl stop/restart` and `systemctl stop/start` on agent node
- Verify the state changes and the process are in correct state
- Also used `killall` and `uninstall` script for validation and ensure that all the process related to k3s is terminated
