### ISSUE TITLE
[release-1.22] Increase agent's apiserver ready timeout

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4467]
Increase agent's apiserver ready timeout. Since the agent starts up earlier, the 30 second timeout is causing problems in RKE2 when trying to update K3s for:
* https://github.com/rancher/rke2/issues/1755
* https://github.com/k3s-io/k3s/issues/4466

**Comment by mdrahman-suse** [comment]
**Verified in k3s Release 1.22 with commit f1b429f9ce5075c2ab794b7e274854b248a76d63** using the same steps as in https://github.com/k3s-io/k3s/issues/4466#issuecomment-970442477
