### ISSUE TITLE
[release-1.21] Increase agent's apiserver ready timeout

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4468]
Increase agent's apiserver ready timeout. Since the agent starts up earlier, the 30 second timeout is causing problems in RKE2 when trying to update K3s for:
* https://github.com/rancher/rke2/issues/1755
* https://github.com/k3s-io/k3s/issues/4466

**Comment by mdrahman-suse** [comment]
**Verified in k3s Release 1.22 with commit 93cf545ab26010a1827acf6a6c1693b5fdb6466c** using the same steps as in https://github.com/k3s-io/k3s/issues/4466#issuecomment-970442477
