### ISSUE TITLE
specifying install script options appears to block install

### ISSUE THREAD

**Issue by blueskyjunkie** [k3s-io/k3s#4497]
**Environmental Info:**
K3s Version: 
1.21.5

Node(s) CPU architecture, OS, and Version: 
`Linux k3s-cp1 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
n/a - just trying to get k3s installed on an initial node.

**Describe the bug:**
Specification of any environment variable options appears to result in the install script failing to complete.

**Steps To Reproduce:**

As described in https://get.k3s.io/

```
> curl https://get.k3s.io/ > /tmp/k3s-install.sh
> chmod 755 /tmp/k3s-install.sh
> INSTALL_K3S_SKIP_START="true" INSTALL_K3S_VERSION="v1.21.5" /tmp/k3s-install.sh
[INFO]  Using v1.21.5 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.5/sha256sum-amd64.txt
> echo $#
0
> which k3s
<empty>
```

Specifying either `INSTALL_K3S_SKIP_START` or `INSTALL_K3S_VERSION` as a sole setting preceding the install script also causes the script to silently fail and exit clean.

**Expected behavior:**
Expect the k3s to be installed at `/usr/local/bin` without being started

**Actual behavior:**
k3s is not installed

**Additional context / logs:**
n/a

**Comment by blueskyjunkie** [comment]
`INSTALL_K3S_VERSION` must be specified as the *exact* release identifier used by github releases. eg. `v1.21.5+k3s2`

seems like the script needs some "invalid release id" logic to generate a useful error.

**Comment by brandond** [comment]
That is correct. You were passing it a Kubernetes version, but not a K3s version.
