### ISSUE TITLE
Starting agent/server with --docker does not appear to use Air-Gap images from tarball

### ISSUE THREAD

**Issue by jonbender-stripe** [k3s-io/k3s#4502]
**Environmental Info:**
K3s Version: 

```
$ k3s --version
k3s version v1.22.3-rc4+k3s1 (61a2aab2)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 

```
 5.11.0-1021-aws #22~20.04.2-Ubuntu SMP Wed Oct 27 21:27:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

Cluster Configuration:
2 servers, 1 agent, no public egress configured (air-gap install).

**Describe the bug:**

Passing `--docker` to the server/agent with an air-gap install does not appear to use the local images.

Sample logs:
```
[2021-11-16 01:16:47.502748] E1116 01:16:47.501917   34931 kuberuntime_manager.go:818] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed pulling image \"rancher/mirrored-pause:3.1\": Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" pod="kube-system/svclb-traefik-wl7w7"
```

With the standard containerd executor this works (I wanted to use Docker for other reasons, namely better interop with ECR).

**Steps To Reproduce:**

Install airgap image tarball:
`/k3s/data/agent/images/k3s-airgap-images-amd64.tar`

Start the server with `--docker`. Observe failures to pull from the registry (this machine does otherwise have public egress), and docker images is empty:

```
$ docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
```

Remove `--docker` flag, observe log lines showing the image import: `[2021-11-16 01:25:19.878604] time="2021-11-16T01:25:19Z" level=info msg="Importing images from /k3s/data/agent/images/k3s-airgap-images-amd64.tar"`

Observe crictl shows the images:

```
sudo k3s -d /k3s/data crictl images list
IMAGE                                        TAG                    IMAGE ID            SIZE
docker.io/rancher/klipper-helm               v0.6.6-build20211022   194c895f8d63f       242MB
docker.io/rancher/klipper-lb                 v0.3.4                 746788bcc27e2       8.48MB
docker.io/rancher/local-path-provisioner     v0.0.20                933989e1174c2       35.2MB
docker.io/rancher/mirrored-coredns-coredns   1.8.4                  8d147537fb7d1       47.7MB
docker.io/rancher/mirrored-library-busybox   1.32.1                 388056c9a6838       1.45MB
docker.io/rancher/mirrored-library-traefik   2.5.0                  3c1baa65c3430       98.3MB
docker.io/rancher/mirrored-metrics-server    v0.5.0                 1c655933b9c56       64.8MB
docker.io/rancher/mirrored-pause             3.1                    da86e6ba6ca19       746kB
```

**Comment by brandond** [comment]
That is correct; the tarballs are only imported into the embedded containerd. If you are running docker, you should load them yourself manually before starting K3s.

**Comment by jonbender-stripe** [comment]
Ah, thanks for clarifying! This may be self-evident for many people, but a line in the air-gap install docs would help to avoid future confusion.
