### ISSUE TITLE
Master used to create a cluster of masters with embedded etcd is always Ready despite being powered off

### ISSUE THREAD

**Issue by indywidualny** [k3s-io/k3s#4504]
**Environmental Info:**
K3s Version: 
```
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux master-2 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
NAME       STATUS   ROLES                       AGE   VERSION
master-1   Ready    control-plane,etcd,master   51m   v1.21.5+k3s2
master-2   Ready    control-plane,etcd,master   48m   v1.21.5+k3s2
master-3   Ready    control-plane,etcd,master   47m   v1.21.5+k3s2
node-1     Ready    <none>                      46m   v1.21.5+k3s2
node-2     Ready    <none>                      46m   v1.21.5+k3s2
```

**Describe the bug:**
I'm experimenting with k3s and high availability so created a cluster basing on: https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/ and noticed that bringing down master used to create the cluster will break the cluster despite its high availability. Pods will stop to be managed, status of this master (only this one is problematic) will be also Ready in spite of being powered off.

**Steps To Reproduce:**

- Installed K3s: 

```
# Install K3S on master
curl -sfL https://get.k3s.io | sh -s - server \
    --clu
    --disable-cloud-controller \
    --write-kubeconfig-mode=644 \
    --node-name="$(hostname -f)" \
    --cluster-cidr="10.244.0.0/16" \
    --kube-controller-manager-arg="address=0.0.0.0" \
    --kube-controller-manager-arg="bind-address=0.0.0.0" \
    --kube-proxy-arg="metrics-bind-address=0.0.0.0" \
    --kube-scheduler-arg="address=0.0.0.0" \
    --kube-scheduler-arg="bind-address=0.0.0.0" \
    --kubelet-arg="cloud-provider=external" \
    --token="SECRET" \
    --flannel-iface=ens10 \
    --tls-san="10.0.0.10" \
    --tls-san="$(hostname -I | awk '{print $2}')"

# `tls-san`: internal IP of the machine, internal IP of a Load Balancer for the API on port 6443

# Hetzner Cloud related
kubectl -n kube-system create secret generic hcloud --from-literal=token=SECRET --from-literal=network=network-kubernetes
kubectl apply -f https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml
```

Then I've joined 2 additional masters.

```
curl -sfL https://get.k3s.io | K3S_URL=https://10.0.0.10:6443 K3S_TOKEN=SECRET sh -s - server \
    --node-name="$(hostname -f)" \
    --kubelet-arg="cloud-provider=external" \
    --flannel-iface=ens10 \
    --disable-cloud-controller

# Uses IP of a LB for Kubernetes API
```

Later joined 2 nodes.

The problem is cluster can easily survive failure of master-2 or master-3 and still spawn pods etc. however when bringing down master-1 used to initialize the cluster things start to stop working. Pods are no longer managed and status of a dead master-1 stays in status Ready forever.

`kubectl get cs` occasionally show errors about components being unhealthy as well which isn't the case when master-2 or master-3 is down.
 
**Expected behavior:**

master-1 can be down and everything is still up and running since the quorum is maintained by master-2 and master-3

**Actual behavior:**

Kubernetes cluster is no longer managed, node master-1 is always in Ready state.

**Additional context / logs:**
Will add when I know which logs can help.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
I suspect there's something unique to your environment or configuration; all the core Kubernetes controllers are lease-locked and should migrate over to a new node within a minute or so of a server node being stopped. Can you attach the logs from all three servers, as well as the output of `kubectl get lease -A` when one of the servers is stopped?
