### ISSUE TITLE
Kubelet serving cert SANs list should contain external IP

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#4520]
**Is your feature request related to a problem? Please describe.**
Currently, the Kubelet serving certificate SAN list does not add the external IP of the node to the list. 

**Describe the solution you'd like**
K3s should add the external IP of a node to the SAN list that is used for the kubelet serving certificate.

**Describe alternatives you've considered**
N/A

**Additional context**
[
](https://rancher-users.slack.com/archives/C01PHNP149L/p1637102366189900)

**Backporting**
- [X] Needs backporting to older releases

**Comment by VestigeJ** [comment]
[k3s version v1.21.7+k3s-8e1b2340 (8e1b2340)
go version go1.16.10](https://github.com/k3s-io/k3s/issues/4665#issuecomment-989323120)

[k3s version v1.22.4+k3s-82125e65 (82125e65)
go version go1.16.10](https://github.com/k3s-io/k3s/issues/4664#issuecomment-989347258)
