### ISSUE TITLE
Unable to join additional server in Dual Stack

### ISSUE THREAD

**Issue by xaque208** [k3s-io/k3s#4535]
**Environmental Info:**
K3s Version:

```
# k3s -v
k3s version v1.22.3+k3s1 (61a2aab2)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 

```
# uname -a
Linux k1 5.15.2-arch1-1 #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux
```

Cluster Configuration:

Starting with 2 servers + external postgres database.

**Describe the bug:**

When starging a new cluster with fresh database, the first server comes up without issue, but trying to join a second server looks like it has trouble reaching the metrics-server and then fails.

**Steps To Reproduce:**

- Installed K3s: 
On the first server.
```
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.22 sh -s \
- server \
--datastore-endpoint="postgres://k3s:PW@db.example.com:5432/k3s" \
--node-ip="172.16.15.21,fc15::21" \
--cluster-cidr="10.42.0.0/16,fc15:1::/64" \
--service-cidr="10.43.0.0/16,fc15:2::/112" \
--disable-network-policy \
--tls-san=k.znet
```

Then I wait for all pods.  Then on the second server.

```
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.22 K3S_TOKEN="TOKEN" sh -s \
- server \
--datastore-endpoint="postgres://k3s:PW@db.example.com:5432/k3s" \
--node-ip="172.16.15.22,fc15::22" \
--cluster-cidr="10.42.0.0/16,fc15:1::/64" \
--service-cidr="10.43.0.0/16,fc15:2::/112" \
--disable-network-policy \
--tls-san=k.znet
```

The install never completes on the second node, but `journalctl` tells us it is still trying.  Some flavor of the following keeps looping.

```
Nov 18 10:08:55 k2 k3s[518]: E1118 10:08:55.369789     518 available_controller.go:524] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.170.124:443/apis/metrics.k8s.io/v1beta1: Get "https://10.43.170.124:443/apis/metrics.k8s.io/v1beta1": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Nov 18 10:09:00 k2 k3s[518]: E1118 10:09:00.381292     518 available_controller.go:524] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again
Nov 18 10:09:00 k2 k3s[518]: E1118 10:09:00.879126     518 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"a93b592512d21f5ee58e6d36cc16a2596a78392a52fd72a88ca6c75e88e9a562\": open /run/flannel/subnet.env: no such file or directory"
Nov 18 10:09:00 k2 k3s[518]: E1118 10:09:00.879209     518 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"a93b592512d21f5ee58e6d36cc16a2596a78392a52fd72a88ca6c75e88e9a562\": open /run/flannel/subnet.env: no such file or directory" pod="kube-system/svclb-traefik-vpwtd"
Nov 18 10:09:00 k2 k3s[518]: E1118 10:09:00.879244     518 kuberuntime_manager.go:818] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"a93b592512d21f5ee58e6d36cc16a2596a78392a52fd72a88ca6c75e88e9a562\": open /run/flannel/subnet.env: no such file or directory" pod="kube-system/svclb-traefik-vpwtd"
Nov 18 10:09:00 k2 k3s[518]: E1118 10:09:00.879337     518 pod_workers.go:836] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"svclb-traefik-vpwtd_kube-system(4e5f21a9-c545-4f71-81a3-16ba98d64d2d)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"svclb-traefik-vpwtd_kube-system(4e5f21a9-c545-4f71-81a3-16ba98d64d2d)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"a93b592512d21f5ee58e6d36cc16a2596a78392a52fd72a88ca6c75e88e9a562\\\": open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/svclb-traefik-vpwtd" podUID=4e5f21a9-c545-4f71-81a3-16ba98d64d2d
```

**Expected behavior:**
I'd expect the install to complete.

**Actual behavior:**
Instllation of the second node never completes repeating the errors above.  First node works fine and I can deploy pods to it with no issue.

**Additional context / logs:**
See above.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Can you post the complete logs from the second node? The metrics-server stuff is a symptom of whatever problem you're running into, not the cause. For some reason flannel isn't coming up right on the second node.

**Comment by xaque208** [comment]
Here is everything after an uninstall on the second node, leaving the first node and database untouched and the install using the command above.

https://gist.github.com/xaque208/433e461abb0bb7b1c5fe231c25c85889

**Comment by brandond** [comment]
The system is still in the process of starting up as of the end of that log. Can you collect the rest of the logs, along with the output of `kubectl get nodes -o yaml` from the first node?

**Comment by xaque208** [comment]
Ah yes, I should have been more patient.  I've updated the gist above.  Here is the `get nodes` output from the first node.

https://gist.github.com/xaque208/2f038492e6d8a2933e127779f40b3104

**Comment by manuelbuil** [comment]
The log `open /run/flannel/subnet.env: no such file or directory` is saying that flannel was not yet ready. After waiting a bit, can you check if that file already exists? If dual-stack is correctly enabled, it should contain: `FLANNEL_IPV6_NETWORK` and `FLANNEL_IPV6_SUBNET`

**Comment by xaque208** [comment]
I left it overnight last night and that message was still present.  This file exists on the first node, but never shows up on the second.

Too, I've just checked back on the second node after providing the logging above, and the log message is still present after an hour or so.  I'm new to k8s and so not sure how to check the CNI state to confirm.

**Comment by manuelbuil** [comment]
Unfortunately, I'm not able to replicate this issue :(. Can you verify that `/var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist` exists?

**Comment by manuelbuil** [comment]
And the output of `/var/lib/rancher/k3s/agent/etc/flannel/net-conf.json`

**Comment by xaque208** [comment]
These messages seem to be repeating.

```
Nov 19 10:30:49 k2 k3s[113668]: E1119 10:30:49.575326  113668 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"e511f9cd97f6d718ad6d685cadb0365d3793b4763c91c1db602df8289da93a5e\": open /run/flannel/subnet.env: no such file or directory"
Nov 19 10:30:49 k2 k3s[113668]: E1119 10:30:49.575410  113668 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"e511f9cd97f6d718ad6d685cadb0365d3793b4763c91c1db602df8289da93a5e\": open /run/flannel/subnet.env: no such file or directory" pod="kube-system/svclb-traefik-kx499"
Nov 19 10:30:49 k2 k3s[113668]: E1119 10:30:49.575450  113668 kuberuntime_manager.go:818] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"e511f9cd97f6d718ad6d685cadb0365d3793b4763c91c1db602df8289da93a5e\": open /run/flannel/subnet.env: no such file or directory" pod="kube-system/svclb-traefik-kx499"
Nov 19 10:30:49 k2 k3s[113668]: E1119 10:30:49.575539  113668 pod_workers.go:836] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"svclb-traefik-kx499_kube-system(9baf3df6-39f5-4b50-adb5-9a0c2e20f6c4)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"svclb-traefik-kx499_kube-system(9baf3df6-39f5-4b50-adb5-9a0c2e20f6c4)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"e511f9cd97f6d718ad6d685cadb0365d3793b4763c91c1db602df8289da93a5e\\\": open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/svclb-traefik-kx499" podUID=9baf3df6-39f5-4b50-adb5-9a0c2e20f6c4
```

**Comment by manuelbuil** [comment]
Thanks! There are a few weird things going on.

1 - For unknown reasons, flannel code is not being executed in the second server and thus you don't get `/run/flannel/subnet.env`
2 - Even if it is not being executed, the second node's kubelet is finding a network config for flannel. Then it starts the pods and flannel binary complains because it can't find the config, which should be in `/run/flannel/subnet.env`

According to your logs, kubelet is looking for the network config at `--cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d`, and something must exist there, otherwise, it will not start the pods. However, you say that `/var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist` does not exist, could you do `ls -altr /var/lib/rancher/k3s/agent/etc/cni/net.d` in the second node please?

**Comment by xaque208** [comment]
```
# ls -altr /var/lib/rancher/k3s/agent/etc/cni/net.d
total 12
-rw-r--r-- 1 root root  311 Nov 19 10:25 10-flannel.conflist
drwxr-xr-x 3 root root 4096 Nov 19 10:25 ..
drwxr-xr-x 2 root root 4096 Nov 19 10:25 .
```

**Comment by xaque208** [comment]
```
[root@k2 ~]# cat /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist 
{
  "name":"cbr0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```

**Comment by manuelbuil** [comment]
Could you reinstall using `INSTALL_K3S_COMMIT=e3e404a84a0af22ec5823627f179f259fb7ea1d8` and in the config set `debug: true`. Then please check `journalctl | grep flannel` and paste the output. Thanks!

**Comment by xaque208** [comment]
Hmm, I get `json: cannot unmarshal string into Go value of type bootstrap.File` running the following.
```
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=e3e404a84a0af22ec5823627f179f259fb7ea1d8 INSTALL_K3S_CHANNEL=v1.22 K3S_TOKEN=$TOKEN sh -s \
- server \
--datastore-endpoint=$DATASTORE_ENDPOINT \
--node-ip="172.16.15.22,fc15::22" \
--cluster-cidr="10.42.0.0/16,fc15:1::/64" \
--service-cidr="10.43.0.0/16,fc15:2::/112" \
--disable-network-policy \
--tls-san=k-dev.znet \
--debug=true
```

**Comment by manuelbuil** [comment]
> Hmm, I get `json: cannot unmarshal string into Go value of type bootstrap.File` running the following.
> 
> ```
> curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=e3e404a84a0af22ec5823627f179f259fb7ea1d8 INSTALL_K3S_CHANNEL=v1.22 K3S_TOKEN=$TOKEN sh -s \
> - server \
> --datastore-endpoint=$DATASTORE_ENDPOINT \
> --node-ip="172.16.15.22,fc15::22" \
> --cluster-cidr="10.42.0.0/16,fc15:1::/64" \
> --service-cidr="10.43.0.0/16,fc15:2::/112" \
> --disable-network-policy \
> --tls-san=k-dev.znet \
> --debug=true
> ```

Strange, same command works in my env. You get that in the journalctl logs? Can you show the output of what you get in the terminal when executing that command please?

**Comment by manuelbuil** [comment]
@xaque208 I finally found time to properly test this and I could reproduce it. The problem is that `node-cidr-mask-size-ipv6` is 64 and you are defining `fc15:1::/64`. Therefore, one node takes all available IPs. If you change to: `--cluster-cidr="10.42.0.0/16,fc15:1::/56"` things work for me.

One annoying thing was that kube-controller-manager was not throwing any error explaining this! :(

**Comment by xaque208** [comment]
Oh awesome, this appears to work after adjusting the prefix.  Thank you for reproducing the issue and pointing this out.  I'm not sure where I would have read this on the path to getting to this point.  What do you think about documenting the restrictions about prefix length?  If I understand correctly now, a `/64` will be used for each node out of the supplied `--cluster-cidr`, and the size of that `node-cidr-mask-size-ipv6` isn't something the user is in control of.

**Comment by Oats87** [comment]
@xaque208 Manuel is currently off having fun and enjoying time off, but I was looking at this issue with him before he took off and can provide some info around this.

I think a small note can be added for sure.

You should be able to set the `kube-controller-manager`s `--node-cidr-mask-size-ipv6` via using `--kube-controller-manager-arg="node-cidr-mask-size-ipv6=64"` on `k3s`.

**Comment by xaque208** [comment]
This is all working well for a while now.  Thank you for the support.
