### ISSUE TITLE
Enable enable_unprivileged_ports and enable_unprivileged_icmp

### ISSUE THREAD

**Issue by olljanat** [k3s-io/k3s#4545]
**Is your feature request related to a problem? Please describe.**
Pod running as non-root cannot listen ports <=1024 and pods without CAP_NET_RAW capability cannot use ICMP.

**Describe the solution you'd like**
Just released [containerd 1.6.0-beta.3](https://github.com/containerd/containerd/releases/tag/v1.6.0-beta.3) added support for `enable_unprivileged_ports` and `enable_unprivileged_icmp` [CRI options](https://github.com/containerd/containerd/blob/main/docs/cri/config.md) but unfortunately there was no consensus to enable those by default before containerd version 2.0 which why those need to be enabled on here.

**Describe alternatives you've considered**
Of course those can be also added as option on here too but most probably it is not needed as anyway containerd version is not raised to 1.6 before also K8s is raised to 1.23.0 

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by katran001** [comment]
Pending for an inked PR merged so this will remain open for this current sprint
