### ISSUE TITLE
k3s SBOM

### ISSUE THREAD

**Issue by mattfarina** [k3s-io/k3s#4552]
With [Kubernetes you can now get a Software Bill of Materials (SBOM)](https://github.com/kubernetes-sigs/bom/blob/main/docs/bom/create-a-bill-of-materials.md). This is a feature request to do the same for k3s.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An [SPDX](https://spdx.dev/) based SBOM following the same conventions as Kubernetes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Backporting**

- [ ] Needs backporting to older releases

**Comment by dweomer** [comment]
Fixed the link that was giving me a 404 (new location is https://github.com/kubernetes-sigs/bom/blob/main/docs/bom/create-a-bill-of-materials.md)
