### ISSUE TITLE
SLSA Level 1 built releases

### ISSUE THREAD

**Issue by mattfarina** [k3s-io/k3s#4553]
[Kubernetes recently cut SLSA level 1 compliant releases.](https://twitter.com/puerco/status/1461176447742226440) Meeting [SLSA](https://slsa.dev/) levels provides a means to secure the build process and what's built. This is a request for k3s to start releasing SLSA level 1 builds.

You can find some additional context in the [Kubernetes SLSA level 1 issue](https://github.com/kubernetes/release/issues/2267).

**Is your feature request related to a problem? Please describe.**
There is a general software security problem. Many systems are getting hacked. In response to this organizations and governments want better software security. SLSA is an emerging standard, driven by the Linux Foundation, to provide some security by implementing good practices. K3s can benefit from the added security.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Backporting**

- [ ] Needs backporting to older releases

**Comment by puerco** [comment]
Hey @mattfarina nice to see this proposal!
I am happy to share some of our experiences and help if I can. I think a really good idea would be to start forming a longer secured chain by connecting both projects using the provenance attestations we are generating. Especially if you are using any of the Kubernetes artifacts as direct inputs.
