### ISSUE TITLE
selinux: some files under the data-dir are container_runtime_exec_t that should not be so

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#4554]
**Environmental Info:**
K3s Version: _any_

Node(s) CPU architecture, OS, and Version: _any os/arch with selinux enforcing_

Cluster Configuration: _1 .. n_

**Describe the bug:**
When k3s disgorges it's user-land content to disk it leverages a `.lock` file at the root of the data-dir (via flock) that does not get cleaned up. By default, our selinux policy has everything under and including the data-dir to be labeled `container_runtime_exec_t` (because containerd and runc need to transition to container_runtime_t process label to function correctly). Additionally, the strongswan/ipsec config directory/files are incorrectly labeled `container_runtime_exec_t`.

To recap, these locations on disk for a running k3s installation have content with labels that could lend elevated privilege via the `container_runtime_exec_t` label:
- `${data-dir}/.lock`
- `${data-dir}/current/etc/**`

**Steps To Reproduce:**
install via https://get.k3s.io on a supported selinux system

**Expected behavior:**
The following locations are correctly labeled:
- `${data-dir}/.lock`
- `${data-dir}/current/etc/**`

`container_lock_t` and `container_config_t` respectively

**Actual behavior:**
The following locations are incorrectly labeled:
- `${data-dir}/.lock`
- `${data-dir}/current/etc/**`

`container_runtime_exec_t` :disappointed:

**Additional context / logs:**
- https://github.com/k3s-io/k3s/issues/4401
- https://github.com/containers/container-selinux/pull/156
- https://github.com/k3s-io/k3s-selinux/pull/25

**Backporting**
n/a

**Comment by dweomer** [comment]
Closing https://github.com/k3s-io/k3s/issues/4401 in favor of this issue

**Comment by ShylajaDevadiga** [comment]
Validated on v1.22.4-rc1+k3s1, files are labeled correctly.
```
[centos@ip-172-31-30-172 ~]$ k3s -v
k3s version v1.22.4-rc1+k3s1 (1a513bba)
go version go1.16.10
[centos@ip-172-31-30-172 ~]$ ls -lZ /var/lib/rancher/k3s/data/.lock
-rw-------. 1 root root system_u:object_r:container_lock_t:s0 0 Nov 23 00:57 /var/lib/rancher/k3s/data/.lock
[centos@ip-172-31-30-172 ~]$ ls -lZ /var/lib/rancher/k3s/data/current/etc/
total 0
drwxr-xr-x. 5 root root system_u:object_r:container_config_t:s0 118 Nov 23 00:58 strongswan
[centos@ip-172-31-30-172 ~]$ ls -alZ /var/lib/rancher/k3s/data/current/etc/strongswan/
total 12
drwxr-xr-x.  5 root root system_u:object_r:container_config_t:s0 118 Nov 23 06:51 .
drwxr-xr-x.  3 root root system_u:object_r:container_config_t:s0  24 Nov 23 06:51 ..
-rw-r--r--.  1 root root system_u:object_r:container_config_t:s0 608 Jul 12 19:23 ipsec.conf
drwxr-xr-x. 10 root root system_u:object_r:container_config_t:s0 119 Nov 23 06:51 ipsec.d
-rw-------.  1 root root system_u:object_r:container_config_t:s0  48 Jul 12 19:23 ipsec.secrets
-rw-r--r--.  1 root root system_u:object_r:container_config_t:s0 281 Jul 12 19:23 strongswan.conf
drwxr-xr-x.  3 root root system_u:object_r:container_config_t:s0 138 Nov 23 06:51 strongswan.d
drwxr-xr-x. 16 root root system_u:object_r:container_config_t:s0 218 Nov 23 06:51 swanctl
[centos@ip-172-31-30-172 ~]$
```
