### ISSUE TITLE
[release-1.21] Protect packaged helm charts from upgrade via Rancher UI

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4560]
* https://github.com/k3s-io/k3s/issues/4315

The Rancher UI currently suggests upgrades and allows edits of Helm charts for packaged components. We should protect these charts so that they cannot be edited via the Rancher UI, and it does not suggest upgrades if a matching chart name is found in a chart repo.

As per @vincent99 we could do this by setting an annotation in the Helm release data:
https://github.com/rancher/rancher/issues/35256#issuecomment-950018715

We should confirm with the Rancher team that this is the correct and best way to do this, and then figure out how to do so. A Helm plugin (similar to what we did for [helm-set-status](https://github.com/k3s-io/helm-set-status)) may be the easiest thing to do?

**Comment by rancher-max** [comment]
#### Validated on [this PR commit to release-1.21 branch](https://github.com/k3s-io/k3s/pull/4559/commits/6d812775202afffc77f9f5258f57b212d718a0d5) on rancher v2.6.3-rc2

- Fresh install of a cluster and import into rancher does not have any prompt to upgrade traefik
- Upgrading a cluster already imported into rancher removes the prompt to upgrade traefik

The resulting view looks like:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/55997940/143149440-3961bafa-4bae-49b5-816b-772966163fdd.png">
