### ISSUE TITLE
[release-1.20] Protect packaged helm charts from upgrade via Rancher UI

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4561]
* https://github.com/k3s-io/k3s/issues/4315

The Rancher UI currently suggests upgrades and allows edits of Helm charts for packaged components. We should protect these charts so that they cannot be edited via the Rancher UI, and it does not suggest upgrades if a matching chart name is found in a chart repo.

As per @vincent99 we could do this by setting an annotation in the Helm release data:
https://github.com/rancher/rancher/issues/35256#issuecomment-950018715

We should confirm with the Rancher team that this is the correct and best way to do this, and then figure out how to do so. A Helm plugin (similar to what we did for [helm-set-status](https://github.com/k3s-io/helm-set-status)) may be the easiest thing to do?

**Comment by rancher-max** [comment]
#### Validated on [this PR to release-1.20 branch](https://github.com/k3s-io/k3s/pull/4556/commits/856171838e4a1ad222506eec2bc8d432e36866a8), commit `856171838e4a1ad222506eec2bc8d432e36866a8`  on rancher v2.6.3-rc2

- Fresh install of a cluster and import into rancher does not have any prompt to upgrade traefik
- Upgrading a cluster already imported into rancher removes the prompt to upgrade traefik

The resulting view looks like:
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/55997940/143149286-564e6d7a-34bc-49d0-9e97-3255d8e15c2d.png">

**Comment by rancher-max** [comment]
I want to add one thing here. I also confirmed that upgrading from 1.20.12+k3s1 to v1.21.7-rc2+k3s1 still does NOT upgrade traefik to Traefik v2. Therefore, NO traefik upgrade happens and the rancher UI still encounters this issue. I would recommend users to upgrade to v1.20.13+k3s1 BEFORE upgrading to v1.21.7 or v1.22.4 if they want to go to v1.21+ during this cycle.
