### ISSUE TITLE
[release 1.21] selinux: most items under /var/lib/rancher/k3s/data/current/bin should not be container_runtime_exec_t

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#4564]
**Environmental Info:**
K3s Version: **all**

Node(s) CPU architecture, OS, and Version:  **n/a**

Cluster Configuration: **n/a**

**Describe the bug:**

Most of the files under `/var/lib/rancher/k3s/data/current/bin/` should not be `container_runtime_exec_t`

**Steps To Reproduce:**
- Fire up a CentOS Stream 8 node
- Install k3s with SELinux enabled (see the Vagrantfile below)
- `ls -alZ /var/lib/rancher/k3s/data/current/bin/` :arrow_right:
  - (notice everything is `system_u:object_r:container_runtime_exec_t:s0`)
- `ls -alZ /var/lib/rancher/k3s/data/current/bin/aux/` :arrow_right:
  - (notice everything is `system_u:object_r:container_runtime_exec_t:s0`)

**Expected behavior:**
- `/var/lib/rancher/k3s/data/current/bin/**` content should be labeled with something like `bin_t` with the following exceptions:
  - these should retain the `container_runtime_exec_t` label:
    - `containerd`
    - `containerd-shim`
    - `containerd-shim-runc-v2`
    - `runc`
  - these should retain the `iptables_exec_t` label:
    - `aux/iptables-apply`
    - `aux/xtables-legacy-multi`
    - `aux/xtables-nft-multi`

**Actual behavior:**
_Please see steps to reproduce above._

**Additional context / logs:**
```ruby
Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-k3s"]
  config.vm.box = "centos/stream8"
  %w[hyperv libvirt virtualbox vmware_desktop].each do |p|
    config.vm.provider p do |v, o|
      v.memory = "2048"
      v.cpus = 2
    end
  end
  config.vm.provision :k3s, run: 'once' do |k3s|
    k3s.config_mode = '0644'
    k3s.env = <<~ENV
      INSTALL_K3S_NAME=server
      K3S_KUBECONFIG_MODE=0644
      K3S_SELINUX=true
      K3S_TOKEN=vagrant
    ENV
  end
end
```

**Backporting**
- n/a

**Comment by dweomer** [comment]
After doing some more digging I do not think this is solvable without changing how we package k3s (or developing custom policy types for k3s):
- `${data_dir}/current/bin/aux/mount` symlinks back to `${data_dir}/current/bin/busybox` while `/usr/sbin/mount` on a centos-8 system is labeled with `mount_exec_t`
- `${data_dir}/current/bin/aux/modprobe` symlinks back to `${data_dir}/current/bin/busybox` while `/usr/sbin/modprobe` on a centos-8 system is a symlink to `/usr/bin/kmod` labeled with `kmod_exec_t`
- if the `busybox` executable is forced to be `bin_t` then neither of these would work as expected

To address the SELinux type-label concerns in this issue we will likely need to revisit what we ship in the embedded user-land and/or develop new context-types specific to k3s. /cc @cwayne18 @cjellick

**Comment by dweomer** [comment]
Additionally, changing the context of the `sh` symlink to `bin_t` while leaving `busybox` binary with `container_runtime_exec_t` still begets a `container_runtime_t` process label:
```shell
[vagrant@smoke bin]$ pwd
/var/lib/rancher/k3s/data/current/bin

[vagrant@smoke bin]$ sudo chcon -vh -t bin_t sh
changing security context of 'sh'

[vagrant@smoke bin]$ sudo chcon -vh -t container_runtime_exec_t busybox
changing security context of 'busybox'

[vagrant@smoke bin]$ ls -alFZ sh busybox 
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0 816728 Jul 12 19:24 busybox*
lrwxrwxrwx. 1 root root system_u:object_r:bin_t:s0                         7 Nov 23 06:27 sh -> busybox*

[vagrant@smoke bin]$ ./sh -c 'id -Z'
unconfined_u:system_r:container_runtime_t:s0-s0:c0.c1023
```

**Comment by dweomer** [comment]
No joy with hardlinks: I tried the same deal with sh as a hardlink to busybox and the same chcon (with no dereference) sets the label for both files (because its just the one file).

**Comment by cjellick** [comment]
@cwayne18 @dweomer - we need issue for 1.22 as well. doesn't need backported further than 1.21.

**Comment by dweomer** [comment]
- #4601 
- #4600

**Comment by dweomer** [comment]
Spoke with @cmurphy who pushed me into the idea of attempting to possibly patch busybox and coreutils (via our buildroot build) such that choice applets run with the correct process label.

**Comment by dweomer** [comment]
Addressed via https://github.com/k3s-io/k3s-selinux/pull/26

**Comment by cwayne18** [comment]
@dweomer Can we close out this issue?

**Comment by katran001** [comment]
Moving this to the current milestone until we get confirmation from @dweomer  that we can close it.
