### ISSUE TITLE
How to add disk capacity

### ISSUE THREAD

**Issue by cbluth** [k3s-io/k3s#4565]
**Environmental Info:**
K3s Version: 
```
# k3s -v
k3s version v1.22.3+k3s1 (61a2aab2)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 
```
# uname -a
Linux mini 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
Two nodes:
- Master: 4 core cpu laptop (AMD64)
- Worker: 4 core cpu NUC-like device (AMD64), with 1TB disk attached  <<-- problem is here

**Describe the bug:**
I have a NUC-like device, with an embedded disk (mmcblk1) that is not replaceable. so i added a 1TB USB3 disk.
I would like to use the extra 1TB disk capacity for the node.
unfortunately, the node keeps getting disk pressure because k3s cannot "see" the extra space.

**Steps To Reproduce:**

- Installed K3s: via binary and systemd from k3s-io/k3s/k3s.service file
- mount 1TB disk to `/mnt`
- use `mv` to migrate `/var/lib/docker` to `/mnt/var/lib/docker`
- use `mv` to migrate `/var/lib/containerd` to `/mnt/var/lib/containerd`
- use symlink to fix the broken paths: `/var/lib/docker` -> `/mnt/var/lib/docker` (same with containerd)

**Expected behavior:**
i was expecting the node to see the extra space after migrating to the 1TB disk, the migration procedure seems to work with docker but not for k3s

**Actual behavior:**
the node still gets disk pressure, and doesnt see the extra space

**Additional context / logs:**

**Comment by brandond** [comment]
You didn't provide any info on how K3s is configured on your nodes - are you using the --docker flag? If not, then you don't need to worry about moving /var/lib/docker.

Either way, you will also want to move /var/lib/rancher/k3s somewhere; thats where K3s stores most of its data.
