### ISSUE TITLE
Node to node communication failing

### ISSUE THREAD

**Issue by willsond01** [k3s-io/k3s#4566]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s1 (acad8ef8)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux rpi-rancher4 5.10.78-1.ph4 #1-photon SMP Thu Nov 11 02:54:51 UTC 2021 aarch64 GNU/Linux

Cluster Configuration:
3 server nodes, 2 agent nodes
3 CPUs, 7GB RAM
MetalLB installed, --no-deploy servicelb

**Describe the bug:**
After installation node to node communication is failing. Pods on the same node seem to communicate fine, however running an overlay test the nodes are not able to communicate until k3s/agent is restarted.

**Steps To Reproduce:**

- Installed K3s: 

- 1st server: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.5+k3s1 INSTALL_K3S_EXEC='--cluster-init --no-deploy servicelb --tls-san <alternate-name>' K3S_TOKEN=<mytoken> sh -

- 2nd/3rd servers: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.5+k3s1 INSTALL_K3S_EXEC='--no-deploy servicelb --server https://<ip-from-first-node>:6443' K3S_TOKEN=<mytoken> sh -

- agents: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.5+k3s1 K3S_TOKEN='"$token"' K3S_URL=https://<ip-from-first-node>:6443 sh -"

After installation I ran the overlay test DaemonSet from the Rancher documentation (customized with an image supporting ARM64) and the supporting shell script. The results indicated that pods were unable to communicate between nodes. 

**Expected behavior:**
Nodes should be able to communicate after system start and service start

**Actual behavior:**
Simply restarting k3s/agent resolves the issue. At least on server nodes adding a systemd timer that delays 3 minutes (arbitrary, just to ensure fully booted) and then starts k3s resolved the issue on the server nodes, it does not appear to on agent nodes.

**Additional context / logs:**

Not sure if its a k3s issue or a PhotonOS 4 issue, but I'd be happy to include any logs if I knew which ones were needed.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by willsond01** [comment]
Here are the logs from an agent node:
[k3s-agent.txt](https://github.com/k3s-io/k3s/files/7591472/k3s-agent.txt)

**Comment by brandond** [comment]
Can you try with 1.21.6? There were some issues with flannel's vxlan overlay that were resolved in that release.

**Comment by willsond01** [comment]
Yup, I reinstalled an agent and it seemed to fix the problem. I am reinstalling the whole cluster now to make sure all the node types work.

**Comment by willsond01** [comment]
After installing 1.21.6 on all the nodes and running the various tests this seemed to correct the issue! A side note I was running that version because of a support matrix for Rancher that I can't seem to find anymore, I'd rather run the latest k3s if it is now not running behind Rancher, is that the case now?

**Comment by willsond01** [comment]
Since this solved my issue I'll go ahead and close it, my additional question does not really have any bearing on the issue needing it to stay open.
