### ISSUE TITLE
Add etcd advertise address support

### ISSUE THREAD

**Issue by mixitgit** [k3s-io/k3s#4576]
**Is your feature request related to a problem? Please describe.**

Currently ip address that embedded etcd advertises is set either using `--node-external-ip` or `utilnet.ChooseHostInterface`.
So it is impossible to explicitly set any different ip or domain name, which is useful, for example, when running k3s in kubernetes
**Describe the solution you'd like**

Add additional flag to set explicitly set advertise address
**Describe alternatives you've considered**

This could be done with setting `--etcd-arg` flag, but it seems to be a less convenient way, because many things will have to be overriten, including certificates 
**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by dereknola** [comment]
With the new additional of `--etcd-arg` I don't particularly see a need to add this flag. AFIK the point of adding a generic etcd flag was to prevent having to add a bunch of specific etcd controls like this. Storing the necessary flags in `config.yaml` is always an option to make launching k3s easier.

**Comment by dereknola** [comment]
@Oats87 since he wrote the `--etcd-arg`.

**Comment by mixitgit** [comment]
@Oats87 As an alternative to my proposal we could pass
```
--etcd-arg=--advertise-client-urls=https://etcd.local:2379
--etcd-arg=--advertise-peer-urls=https://etcd.local:2380
--etcd-arg=-listen-client-urls=https://0.0.0.0:2379
--etcd-arg=-listen-peer-urls=https://0.0.0.0:2380
--tls-san=etcd.local
```
But currently it doesn't work, because these arguments are getting overritten

**Comment by Oats87** [comment]
What is your desired outcome here? Why are you trying to change the advertise/listen URLs? Are you trying to use the embedded etcd for other applications? 

In this case, in my opinion, you have passed the threshold of the purpose of the embedded etcd and at this point I would start looking at running my own etcd cluster and pointing to it from K3s.

**Comment by mixitgit** [comment]
I am running k3s inside of kubernetes cluster, so peer ips are not sticky, so I am trying to put the behind fqdn

**Comment by brandond** [comment]
Static node addressing is currently a requirement for a functional Kubernetes cluster. It is not expected to work properly if the nodes addresses are not stable.

**Comment by mixitgit** [comment]
I am not completely sure, but from my understanding static IP might be needed for nodes (kubelet/kube-proxy), contolplane doesn't have such requirement. And I am trying to run only the controlplane

**Comment by dereknola** [comment]
Thank you for submitting this issue, we always encourage community contribution. After discussion here and between maintainers, we have decided to close this issue. We currently do not want to add more customization to the embedded etcd. It is suggested that you might try running an external ectd or run another DB such as mySQL in a pod and have the K3s servers connect to an in-cluster service endpoint.
