### ISSUE TITLE
Verify new control plane nodes joining the cluster use the same config as the rest

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4579]
**Is your feature request related to a problem? Please describe.**

Sometimes users complain about inconsistencies in their k3s HA cluster and the root cause is a different configuration in their control-plane servers. There is nothing guardrailing us from doing that mistake and for example it is possible to define different `--cluster-cidr` in each node

**Describe the solution you'd like**

Have a method that verifies that the joining control-plane node shares the same config as the already members of the cluster

**Describe alternatives you've considered**

Documenting this better instead of adding logic

**Additional context**

**Backporting**

- [X] Needs backporting to older releases

**Comment by Oats87** [comment]
+1 x100000

**Comment by manuelbuil** [comment]
**How to test:**
- Two hosts or instances is enough
- Start k3s server in the first host in HA mode (e.g. `sudo K3S_TOKEN=SECRET k3s server --cluster-init`)
- Start k3s server in the second host in HA mode but using a different config (e.g. `sudo K3S_TOKEN=SECRET k3s server --server https://$Server1:6443 --token secret --flannel-backend=none`)

**Expected result:**
- Immediately, the joining k3s server fails with the message: ` Unable to join cluster due to critical configuration value mismatch`

If the second k3s server is started with `--debug true`, you should see the config of the cluster and the config of this server. It should help the user realize what is different

If the second server is started with the same config as the first server, it should still work

**Comment by ShylajaDevadiga** [comment]
Validated using commit id from master branch **k3s version v1.22.4+k3s-e8a30a87**
Node1:
```
curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=e8a30a87c8c1b36754653fb3318b1b19debf8632 sh -s - server --cluster-init --token=<TOKEN>
```
Node2:
```
curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=e8a30a87c8c1b36754653fb3318b1b19debf8632 sh -s - server --token <TOKEN> --server https://<serverone IP>:6443 --debug --flannel-backend=none
```
From the logs
```
$ journalctl -u k3s |grep mismatch
Dec 09 07:54:20 ip-172-31-4-208 k3s[3102]: time="2021-12-09T07:54:20Z" level=fatal msg="starting kubernetes: preparing server: Unable to join cluster due to critical configuration value mismatch"
```

**Comment by bguzman-3pillar** [comment]
Validated using version: **v1.23.1-rc1+k3s1** 



Test 1: Create a k3s server in the first host in HA mode and k3s server in the second host in HA mode but using a different config, expecting a error msg "Unable to join cluster due to critical configuration value mismatch" 

Node1: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.1-rc1+k3s1  INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --token secret --cluster-init" sh -
```


Node2: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.1-rc1+k3s1  INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --token secret --server https://<serverone IP>:6443 --flannel-backend=none" sh -
```

Actual result from Node2 logs
The expected message is displayed correctly:
```
$ journalctl -u k3s |grep mismatch
Jan 04 16:35:42 ip-172-31-43-18 k3s[1550]: time="2022-01-04T16:35:42Z" level=fatal msg="starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch"
Jan 04 16:35:47 ip-172-31-43-18 k3s[1567]: time="2022-01-04T16:35:47Z" level=fatal msg="starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch"
Jan 04 16:35:53 ip-172-31-43-18 k3s[1582]: time="2022-01-04T16:35:53Z" level=fatal msg="starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch"
Jan 04 16:35:58 ip-172-31-43-18 k3s[1597]: time="2022-01-04T16:35:58Z" level=fatal msg="starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch"
Jan 04 16:36:04 ip-172-31-43-18 k3s[1612]: time="2022-01-04T16:36:04Z" level=fatal msg="starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch"
```






Test 2: Create a k3s server in the first host in HA mode and k3s server in the second host in HA mode using the same config as the first server, expecting joining correctly to the first node.

Node1: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.1-rc1+k3s1  INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --token secret --cluster-init" sh -
```


Node2: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.1-rc1+k3s1  INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --token secret --server https://<serverone IP>:6443" sh -
```

Actual result is the second server has joined correctly:
```
[INFO]  Using v1.23.1-rc1+k3s1 as release
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

```
NAME              STATUS   ROLES                       AGE   VERSION
ip-server1   Ready    control-plane,etcd,master   43m   v1.23.1-rc1+k3s1
ip-server2   Ready    control-plane,etcd,master   19m   v1.23.1-rc1+k3s1
```

**Comment by withinboredom** [comment]
The downside to this: when you want to change those settings and don't care about downtime ... only to discover you have to rebuild an entire cluster to change a single setting.
