### ISSUE TITLE
Allow agent to store configuration in a different directory other than /etc

### ISSUE THREAD

**Issue by imavroukakis** [k3s-io/k3s#4597]
**Is your feature request related to a problem? Please describe.**

I cannot use the agent on embedded devices that come with  a read-only`/etc` as that is where it tries to create the `rancher` directory.

**Describe the solution you'd like**

It would be great if the agent could be configured to use a different directory other than `/etc/rancher` to store configuration.

**Describe alternatives you've considered**

Modify the embedded distro to create a new image that soft-links `/etc/rancher` to a writeable mount - this is painful though!

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by imavroukakis** [comment]
Hey folks, any advice or suggestion about this?

**Comment by brandond** [comment]
I don't believe we have any plans to add support for this, but a PR would be welcome!

**Comment by imavroukakis** [comment]
Thanks @brandond I'd be up for that 😃  If it is not too huge an imposition on your time, where should I start looking?
