### ISSUE TITLE
When the firewall is activated, when multiple network cards are in the same network segment, use the designated specific network card to install the k3s cluster service, and the node service cannot be accessed abnormally

### ISSUE THREAD

**Issue by YibiaoWu** [k3s-io/k3s#4624]
**Environmental Info:**
K3s Version: 

k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 

Linux soc01 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server 1agent

**Describe the bug:**

server node telnet pod_ip port:
![image](https://user-images.githubusercontent.com/92915249/144369488-1014f8f9-108d-4462-96cd-5ba328d6652a.png)

agent node telnet pod_ip port:
![image](https://user-images.githubusercontent.com/92915249/144369649-bc2c6c2b-d4b5-4a2e-bb2a-504b73ff0372.png)

**Steps To Reproduce:**

- Installed K3s: 
First open the firewall designated port：
server node:
firewall-cmd --add-port=6443/tcp --add-port=123/udp --add-port=10250/tcp --add-port=10251/tcp --add-port=10252/tcp --add-port=8472/udp --add-port=30000-32767/tcp --add-port=443/tcp --add-port=80/tcp --add-port=514/udp --permanent
firewall-cmd --add-masquerade --permanent && firewall-cmd --reload
worker node:
firewall-cmd --add-port=6444/tcp --add-port=10250/tcp --add-port=8472/udp --add-port=30000-32767/tcp --add-port=443/tcp --add-port=80/tcp --add-port=514/udp --permanent
firewall-cmd --add-masquerade --permanent && firewall-cmd --reload

server node installation:
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="server --data-dir=/data/k3s --docker --cluster-cidr 172.90.0.0/16 --service-cidr 10.96.0.0/12  --flannel-iface ens38 --bind-address 192.168.110.131 --advertise-address 192.168.110.131 --node-external-ip 192.168.110.131" ./k3s

agent node installation:
INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://192.168.110.131:6443 K3S_TOKEN=K101ae162xxxxxxxxxxxxxxxxxxxxxxxxxxxxca92ee0a5::server:d27582479454ec73086b99201058dd09 INSTALL_K3S_EXEC="agent --data-dir=/data/k3s --docker --flannel-iface ens38" ./k3s

server node environment information
![image](https://user-images.githubusercontent.com/92915249/144369943-5f41f631-d7b1-4f31-b76c-c4df5666ae6d.png)

agent node environment information
![image](https://user-images.githubusercontent.com/92915249/144370032-9d1a38d1-8e78-462f-869c-e888625f0118.png)

**Expected behavior:**

I want to access the Pod service with the firewall turned on and the network card is not disabled
What firewall policy needs to be added
Example：worker node:  telnet server_pod_ip port Pass

**Actual behavior:**

When the firewall is turned off or the ens33 network card is disabled
worker node:  telnet server_pod_ip port Pass
![image](https://user-images.githubusercontent.com/92915249/144370359-e09b6039-7d35-4609-ac62-66a15dd8f738.png)
![image](https://user-images.githubusercontent.com/92915249/144370403-78f2e2b7-8274-431b-9712-9ea3b620eecf.png)

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by manuelbuil** [comment]
If I understand correctly, your firewalld configuration is not working correctly because you can't access port 8000 when firewalld is running, even though you haven't blocked port 8000, right? Why do you think k3s is the source of the problem?

**Comment by YibiaoWu** [comment]
172.90.0.7:8000 Is the traefik container port，As shown in FIG，The firewall rules for communication between k3s nodes have been turned on，Logically, the current node accesses the pod_ip of other nodes: pod_port is accessible，But now it’s not accessible.
If my firewall configuration is not working，The current node should not be able to ping the pod_ip address of other nodes，But it can actually be pinged，And the current cluster is installed with the firewall turned on，This shows that port 6443 of the master node can be accessed.
