### ISSUE TITLE
Namespaces disappear error.

### ISSUE THREAD

**Issue by qq253498229** [k3s-io/k3s#4625]
My cluster uses both k3s and rancher. After running for a period of time, there was a problem caused in my cluster. 
All namespaces disappeared, but projects remained, and everything under the project disappeared, including workload, load balancing, service discovery, and so on. 
I logged in to the host computer and used "kubectl get no / kubectl get po --all-namespaces" to check the cluster running status. No exceptions were found. How should I check the cause of the problem?

My linux system is ubuntu 16.04.

**Comment by qq253498229** [comment]
In addition, all pods in the cluster are still running normally, that is, all namespaces cannot be detected on the Ranger.

**Comment by qq253498229** [comment]
This problem has occurred before. 
When I restart the master node, the error is still there. 
But when I restart all the servers in the cluster, the error disappears. 
Of course, I don't think this is a long-term solution.

**Comment by qq253498229** [comment]
I also tried to delete the cluster on the rancher UI and then import the cluster again, and the problem will disappear.

**Comment by brandond** [comment]
If the namespaces and pods are still there, then this sounds like a Rancher issue, not k3s.

**Comment by qq253498229** [comment]
Oh, sorry, I just figured it out.
