### ISSUE TITLE
Connectivity issues when cluster-cidr and network interface IP reside in the same address space

### ISSUE THREAD

**Issue by braye** [k3s-io/k3s#4627]
**Environmental Info:**
K3s Version: 

- k3s version v1.22.4+k3s1 (bec170bc)
- go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

- `Linux tbiseud4 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Red Hat Enterprise Linux release 8.4 (Ootpa)

Cluster Configuration:

- HA, Using embedded etcd (--cluster-init)
- 3 servers, 1 agent
- Using tokenfiles on all nodes
- Using --write-kubeconfig-mode=644
- Everything else default

**Describe the bug:**

On a computer with a single network interface, whose IP address resides within the /16 of the cluster-cidr, traffic from pods destined for nodes or the kubernetes API is not NATed correctly.

**Steps To Reproduce:**

- Installed K3s via playbook based on [k3s-io/k3s-ansible](https://github.com/k3s-io/k3s-ansible) where the k3s binary is downloaded directly, rather than running the sh install script.
- Playbook creates a custom unit file: 
```[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network-online.target

[Service]
Type=notify
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay

ExecStart=/trvapps/bidata/k3s/bin/k3s server --cluster-init --write-kubeconfig-mode=644

Environment="K3S_TOKEN_FILE=/var/lib/rancher/k3s/server/tokenfile"
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s

[Install]
```

Unit file on other servers and agents are identical except for command line options. Servers and agent have --server instead of cluster-init, agent instead of server, etc.

**Expected behavior:**

Pods scheduled on the agent node should be able to contact the Kubernetes API via the service IP (default: 10.43.0.1), and metrics-server pod should be able to contact the metrics service running on all nodes on port 10250.

**Actual behavior:**

The issue manifested as i/o timeouts in various pods. For example, when the kubernetes-dashboard pod of the K8S dashboard was scheduled on the single agent node, it produced this:
```
$ kubectl -n kubernetes-dashboard logs kubernetes-dashboard-576cb95f94-255r5
2021/12/01 17:48:05 Using namespace: kubernetes-dashboard
2021/12/01 17:48:05 Using in-cluster config to connect to apiserver
2021/12/01 17:48:05 Using secret token for csrf signing
2021/12/01 17:48:05 Initializing csrf token from kubernetes-dashboard-csrf secret
2021/12/01 17:48:05 Starting overwatch
panic: Get "https://10.43.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf": dial tcp 10.43.0.1:443: i/o timeout
```

The metrics service also fails in a similar way:
(This is a separate, non-HA cluster, but the issue manifests the same way on the cluster that this report is concerned with.)
```
 $ kubectl top node
NAME       CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
tbiseud0   149m         3%     5377Mi          33%
tbiseud2   <unknown>                           <unknown>               <unknown>               <unknown>
tbiseud3   <unknown>                           <unknown>               <unknown>               <unknown>
tbiseud1   <unknown>                           <unknown>               <unknown>               <unknown>
```
metrics-server logs:

```
E1202 20:06:05.353389       1 scraper.go:139] "Failed to scrape node" err="Get \"https://tbiseud3:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 10.42.x.x:10250: i/o timeout" node="tbiseud3"
E1202 20:06:05.360053       1 scraper.go:139] "Failed to scrape node" err="Get \"https://tbiseud1:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 10.42.x.x:10250: i/o timeout" node="tbiseud1"
E1202 20:06:05.370311       1 scraper.go:139] "Failed to scrape node" err="Get \"https://tbiseud2:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 10.42.x.x:10250: i/o timeout" node="tbiseud2"
```

I believe the root cause of this (as far as I understand it, anyways) are the following iptables chains:

```
Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
target     prot opt source               destination
KUBE-MARK-MASQ  tcp  -- !tbiseud4/16          10.43.0.1            /* default/kubernetes:https cluster IP */ tcp dpt:https
KUBE-SEP-CNRSP6IYSTKQO5DG  all  --  anywhere             anywhere             /* default/kubernetes:https */ statistic mode random probability 0.33333333349
KUBE-SEP-QY44CRYVB534HB6O  all  --  anywhere             anywhere             /* default/kubernetes:https */ statistic mode random probability 0.50000000000
KUBE-SEP-X3CC6L4UZXJ5Z6ZV  all  --  anywhere             anywhere             /* default/kubernetes:https */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
CNI-HOSTPORT-MASQ  all  --  anywhere             anywhere             /* CNI portfwd requiring masquerade */
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
RETURN     all  --  tbiseud4/16          tbiseud4/16
MASQUERADE  all  --  tbiseud4/16         !base-address.mcast.net/4  random-fully
RETURN     all  -- !tbiseud4/16          tbiseud4/24
MASQUERADE  all  -- !tbiseud4/16          tbiseud4/16          random-fully
```

For the first chain, because the source IP (10.42.0.3) resides within the /16 of `tbiseud4` (10.42.183.x), the packet never gets marked for masquerading. 

In the POSTROUTING chain, because the source ip and destination IP both reside in 10.42.0.0/16, the chain RETURNs before the packets masqueraded.

The end result of this is that packets go out over the wire with a source address corresponding to the pod IP that originated the traffic. This isn't what's actually breaking connectivity, but this particular cluster resides in an environment where packets that don't match the IP address of the interface are silently dropped. Might be a vmWare thing, not sure. I have a packet capture of this happening, but I don't have the ability to provide it right now. I can look into that if it would help.

**Additional context / logs:**

I think it's worth mentioning that I don't really know if this constitutes a "bug". "Bad things happen if your cluster CIDR overlaps with the IP address of your machine" isn't unreasonable, but I was completely unable to find any reference to this potential issue in the K3s documentation or FAQs, and it doesn't seem that `k3s check-config` is checking for that. There is a warning when the cluster-cidr is already routed, but it's innocuous yellow text. Doesn't seem to suggest that it's going to cause issues with cluster functionality.

This is also my first time really diving into advanced iptables configuration like this, so I apologize if I'm mis-understanding how these rules are intended to function. Regardless of the cause, changing the cluster-cidr to 10.44.0.0/16 fixed all of these issues.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> On a computer with a single network interface, whose IP address resides within the /16 of the cluster-cidr, traffic from pods destined for nodes or the kubernetes API is not NATed correctly.

As the saying goes, "don't do that"

**Comment by braye** [comment]
> As the saying goes, "don't do that". This same issue would occur with any Kubernetes distro, not just K3s.

I kind of got the feeling that was the case, but I wasn't 100% sure. Thanks for clearing that up!
