### ISSUE TITLE
Node status is incorrect after it shutdown with the command "shutdown now"

### ISSUE THREAD

**Issue by Cryingmouse** [k3s-io/k3s#4647]
**Environmental Info:**
K3s Version: 
k3s version v1.22.2+k3s2 (3f5774b4)

Node(s) CPU architecture, OS, and Version: 
`[root@jay1 ~]# uname -a`
`Linux jay1 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`[root@jay1 ~]# cat /etc/redhat-release`
`CentOS Linux release 8.1.1911 (Core)`

Cluster Configuration:
3 servers, no agents

**Describe the bug:**
In order to verify the high availability of k3s cluster, I shutdown one of the server nodes (that is, jay2) with Linux command "shutdown now". **_After half an hour_**, the output of the command `kubectl get node` is as follow:
`[root@jay1 ~]# kubectl get node`
`NAME   STATUS   ROLES                  AGE     VERSION`
`jay1   Ready    control-plane,master   5d17h   v1.22.2+k3s2`
`jay2   Ready    control-plane,master   5d17h   v1.22.2+k3s2`
`jay3   Ready    control-plane,master   5d17h   v1.22.2+k3s2`

It is expected that the status of jay2 should be NotReady. Furthermore, I cannot even deploy any pod in the cluster anymore.
This issue is highly possible to happen instead of 100%. In my testing, it would be 1/3~1/5 possibility to be reproduced.

**Steps To Reproduce:**

- Install docker engine and deploy etcd cluster in the three nodes.
- Installed K3s: Using the similar k3s configuration in the three nodes:
using systemd service to install k3s. Here is the service configuration I used:
`[root@jay1 ~]# vi /etc/systemd/system/k3s.service`
`[Unit]`
`Description=Lightweight Kubernetes`
`Documentation=https://k3s.io`
`Wants=network-online.target`
`After=network-online.target`
``
`[Install]`
`WantedBy=multi-user.target`
``
`[Service]`
`Type=notify`
`NotifyAccess=all`
`EnvironmentFile=/etc/systemd/system/k3s.service.env`
`KillMode=process`
`Delegate=yes`
`LimitNOFILE=1048576`
`LimitNPROC=infinity`
`LimitCORE=infinity`
`TasksMax=infinity`
`TimeoutStartSec=0`
`Restart=always`
`RestartSec=5s`
`ExecStartPre=-/sbin/modprobe br_netfilter`
`ExecStartPre=-/sbin/modprobe overlay`
`ExecStart=/usr/local/bin/k3s \`
`    server \`
`        '--datastore-endpoint=http://10.128.136.173:2379,http://10.128.136.174:2379,http://10.128.136.175:2379' \`
`        '--token' \`          `'K102464b49c67e3bd3b3af643e8209ddb38e1a275d819e7a7b58a7668d41f364e5c::server:5e8c2744396b063d7916a38ac7837938' \`
`       '--log' \`
`        /var/log/k3s-server.log' \`

- In one of the nodes (for example, the node name as jay2), run the command `shutdown now` to shutdown the node immediately to simulate power off of the server.
`[root@jay2 ~]# date; shutdown now`
`Tue Dec  7 10:43:25 CST 2021`
`[root@jay2 ~]#`

- check the status of etcd cluster with the following command:
`[root@jay3 ~]# docker exec $(docker ps | awk '{print $1}' | grep -v CONTAINER) etcdctl endpoint --cluster status -w table`
`{"level":"warn","ts":"2021-12-07T03:21:35.687Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d2a80/#initially=[127.0.0.1:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.128.136.174:2379: connect: no route to host\""}`
`Failed to get the status of endpoint http://10.128.136.174:2379 (context deadline exceeded)`
`+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+`
`|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |`
`+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+`
`| http://10.128.136.173:2379 | b9a6dd4e6cd6b676 |   3.5.0 |  5.6 MB |      true |      false |        39 |     581645 |             581645 |        |`
`| http://10.128.136.175:2379 | d7cfebacf35e190f |   3.5.0 |  5.9 MB |     false |      false |        39 |     581645 |             581645 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+`

- run the command "kubectl get nodes" in another two nodes to check the status of all nodes. 
`[root@jay3 ~]# kubectl get node`
`NAME   STATUS   ROLES                  AGE     VERSION`
`jay1   Ready    control-plane,master   5d18h   v1.22.2+k3s2`
`jay2   Ready    control-plane,master   5d18h   v1.22.2+k3s2`
`jay3   Ready    control-plane,master   5d18h   v1.22.2+k3s2`

**Expected behavior:**
It is expected that the status of the node which is shutdown should be `NotReady` when running the command `kubectl get nodes` in other nodes. 

**Actual behavior:**
the status of the node which is shutdown is still in `Ready` status.

**Additional context / logs:**
[173.txt](https://github.com/k3s-io/k3s/files/7665496/173.txt)
[175.txt](https://github.com/k3s-io/k3s/files/7665495/175.txt)

**Backporting**

- [ ] Needs backporting to older releases

**Comment by Cryingmouse** [comment]
[](url)

**Comment by brandond** [comment]
Kubernetes is eventually consistent; it may take a couple minutes before the active controller-manager lease moves over to a new node and the offline node gets updated to NotReady by the node controller.

**Comment by Cryingmouse** [comment]
I wait for a whole night, but unfortunately it is still in Ready status.

> Kubernetes is eventually consistent; it may take a couple minutes before the active controller-manager lease moves over to a new node and the offline node gets updated to NotReady by the node controller.

Actually I waited for a whole night, but it is still in Ready Status. :(

**Comment by brandond** [comment]
> Actually I waited for a whole night, but it is still in Ready Status. :(

This suggests that there is something else wrong with your cluster. Can you show the output of:
* `kubectl get lease -A`
* `kubectl get node -o wide`

**Comment by Cryingmouse** [comment]
Sorry for low response, and looks like this issue is related to my mis-configuration during the service startup.
