### ISSUE TITLE
Implement Certificate Expiry Extension Capabilities

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#4651]
**Is your feature request related to a problem? Please describe.**

#4271 

**Describe the solution you'd like**

The details are outlined in the design doc linked above. Synopsis: add cli sub commands / flags to manipulate the expiration time on a given certificate or all certificates.

**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [X] Needs backporting to older releases

**Comment by caroline-suse-rancher** [comment]
Closing, this should be fixed with the most recent CA cert changes.
