### ISSUE TITLE
Failed to build k3s binary 

### ISSUE THREAD

**Issue by snuramjirajukammila** [k3s-io/k3s#4655]
Hi Team,

Trying to build k3s binary and package it as docker, followed the build doc to build it.

when trying to run this command

mkdir -p build/data && ./scripts/download && go generate
.
getting below error

awk: line 1: syntax error at or near ,

while parsing traefik.yaml it is failing with this error.

Can you please let us know how to fix this issue.

OS: ubuntu:18.04

Thanks,
Ramji.

**Comment by brandond** [comment]
I suspect there were other errors before that one that you've missed, as I believe it should build on ubuntu 18.04.  Can you post the complete output from those commands?

Doing that should only be necessary if you've updated go.mod or the embedded manifests though; if you're just working on the k3s code itself you should be able to just run `make ci`.

**Comment by snuramjirajukammila** [comment]
Thanks brandond for the response

Below is the command where it was failing

snuramjirajukammila@bvrmlpt123:~/docker-compose/k3s/k3s$ **mkdir -p build/data && ./scripts/download && go generate
awk: line 1: syntax error at or near ,**

Initially it failed with error yq not found, installed yq than facing this issue.

Able to proceed with make ci

**Comment by brandond** [comment]
no, can you show the complete **output** of those commands. What all do you get when you run them? What have you modified in your fork that you're trying to change - is it possible that you've broke the build scripts yourself?

**Comment by snuramjirajukammila** [comment]
we just pulled master and followed the commands in building.md file, no changes made to code or any scripts.

Built straight away from master

**Comment by snuramjirajukammila** [comment]
Able to proceed with make ci

**Comment by iwilltry42** [comment]
I faced the same issue and figured that the problem was that I had `mawk` installed on my machine (seems to be the default in newer Ubuntu versions).
So just `sudo apt install gawk` (which superseded mawk in my case) did the trick.
The `dockerfile.dapper` explicitly installs `gawk` :+1:
