### ISSUE TITLE
[release-1.22] Issues with dynamiclistener

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4657]
Backport fix for **Issues with dynamiclistener** to branch **release-1.22**:
* #2226

**Comment by VestigeJ** [comment]
**Validated**
---------------------------------------------------------------------------------------------

Version bump on the PR looks good to me


$ k3s -v
```
k3s version v1.22.4+k3s-b38bc7dd (b38bc7dd)
go version go1.16.10
```

**Comment by VestigeJ** [comment]
$ k3s -v
```
k3s version v1.22.4-rc3+k3s2 (5e73a828)
 go version go1.16.10
```
