### ISSUE TITLE
[release-1.22] Kubelet serving cert SANs list should contain external IP

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4664]
Backport fix for **Kubelet serving cert SANs list should contain external IP** to branch **release-1.22**
* #4520

**Comment by VestigeJ** [comment]
_**Validated Functionality**_
Using Commit ID - 82125e6580e1861036e927771400685a8b74402f


---------------------------------------------------------------------------------------------
**AWS EC2 Ubuntu 20.04 Server Node**
---------------------------------------------------------------------------------------------
$ k3s -v
```
k3s version v1.22.4+k3s-82125e65 (82125e65)
go version go1.16.10
```
$ uname -a
```
Linux ip-172-31-24-147 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
$ INSTALL_K3S_COMMIT=82125e6580e1861036e927771400685a8b74402f ./install.sh
$ sudo systemctl stop k3s.service
$ sudo k3s server --token $TOKEN --kube-apiserver-arg kubelet-preferred-address-types=ExternalIP --node-external-ip $EXTERNAL_IP

$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'

```
X509v3 Subject Alternative Name: 
DNS:ip-172-31-24-147, 
DNS:localhost, 
IP Address:127.0.0.1, 
IP Address:172.31.24.147, 
IP Address:3.136.86.50
Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:4b:68:24:58:17:12:f3:ad:a2:7f:6b:7e:17:d8:
```

**tty2**
$ sudo chmod 644 /etc/rancher/k3s/k3s.yaml
$ watch kubectl get nodes
```
NAME               STATUS   ROLES                  AGE   VERSION
ip-172-31-24-147   Ready    control-plane,master   17m   v1.22.4+k3s-82125e65
justin80           Ready    <none>                 20s   v1.22.4+k3s-82125e65
justin49           Ready    <none>                 11s   v1.22.4+k3s-82125e65
```


---------------------------------------------------------------------------------------------
**Digital Ocean CentOS Agents X2**
---------------------------------------------------------------------------------------------
 
 Agent1
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin49 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

$ sudo cat /etc/rancher/k3s/config.yaml
```
server: https://3.136.86.50:6443
token: K1066a830b6c7085b44c18776e6dc8b687a9b78227866257a2cbe095885470637b3::server:vartaba
```

$ echo $EXTERNAL_IP
`143.198.63.165`
$ echo $EXECEC
`agent --node-external-ip 143.198.63.165 sh -`
$ INSTALL_K3S_COMMIT=82125e6580e1861036e927771400685a8b74402f INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh


  Agent2
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin80 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

$ sudo cat /etc/rancher/k3s/config.yaml
```
server: https://3.136.86.50:6443
token: K1066a830b6c7085b44c18776e6dc8b687a9b78227866257a2cbe095885470637b3::server:vartaba
```

$ echo $EXTERNAL_IP
`147.182.250.255`
$ echo $EXECEC
`agent --node-external-ip 147.182.250.255 sh -`
$ INSTALL_K3S_COMMIT=82125e6580e1861036e927771400685a8b74402f INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh



$ kubectl logs metrics-server-9cf544f65-qxgwg -n kube-system
```
I1209 00:26:36.617620       1 serving.go:341] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I1209 00:26:37.122454       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I1209 00:26:37.122478       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I1209 00:26:37.122725       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1209 00:26:37.122777       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1209 00:26:37.122888       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I1209 00:26:37.122951       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I1209 00:26:37.124183       1 dynamic_serving_content.go:130] Starting serving-cert::/tmp/apiserver.crt::/tmp/apiserver.key
I1209 00:26:37.127119       1 secure_serving.go:197] Serving securely on [::]:443
I1209 00:26:37.127276       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I1209 00:26:37.222677       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I1209 00:26:37.223961       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I1209 00:26:37.224080       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
```

**Comment by VestigeJ** [comment]
Server Node in AWS

$ COMMIT=5e73a828e45ed49bd73243cd618ba8e6e1169a76

$ sudo INSTALL_K3S_COMMIT=$COMMIT \
INSTALL_K3S_EXEC="server --token coolvegetables --kube-apiserver-arg kubelet-preferred-address-types=ExternalIP --node-external-ip 3.2.1.1" \
./install-k3s.sh

$ k3s -v
```
k3s version v1.22.4-rc3+k3s2 (5e73a828)
go version go1.16.10
```

$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'
```     
X509v3 Subject Alternative Name: 
DNS:ip-37-20-12-19.us-north-9.compute.internal, DNS:localhost, 
IP Address:127.0.0.1, IP Address:172.31.22.202, IP Address:3.2.1.1
Signature Algorithm: ecdsa-with-SHA256
30:45:02:21:00:88:a6:2f:58:28:34:a5:fc:85:4c:0e:7f:36:
```

$ kubectl get nodes
```
NAME                                          STATUS   ROLES                  AGE     VERSION
justin78                                      Ready    <none>                 2m23s   v1.22.4-rc3
+k3s2
ip-37-20-12-19.us-north-9.compute.internal   Ready    control-plane,master   7m29s   v1.22.4-rc3
+k3s2
```

---------------------------------------------------------------------------------------------

Agent Node in DO

$ COMMIT=5e73a828e45ed49bd73243cd618ba8e6e1169a76

$ sudo INSTALL_K3S_COMMIT=$COMMIT \
INSTALL_K3S_EXEC="agent --token coolvegetables --server https://3.2.1.1:6443 --node-external-ip 1.2.2.3" \
./install-k3s.sh

$ k3s -v
```
k3s version v1.22.4-rc3+k3s2 (5e73a828)
go version go1.16.10
```
$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'
```
X509v3 Subject Alternative Name: 
DNS:justin78, DNS:localhost, 
IP Address:127.0.0.1, IP Address:1.2.2.3, IP Address:1.2.2.3
Signature Algorithm: ecdsa-with-SHA256
30:46:02:21:00:95:f8:48:78:0c:9b:4e:3d:84:57:04:f1:17:
```
