### ISSUE TITLE
[release-1.21] Kubelet serving cert SANs list should contain external IP

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4665]
Backport fix for **Kubelet serving cert SANs list should contain external IP** to branch **release-1.21**
* #4520

**Comment by VestigeJ** [comment]
_**Validated Functionality**_
Using Commit ID - 8e1b2340c9f85af3adf63ce5af54e1444c808b35 ( ARM was still building at this time )
---------------------------------------------------------------------------------------------
**AWS EC2 Ubuntu 20.04 Server Node**
---------------------------------------------------------------------------------------------
$ k3s -v
```
k3s version v1.21.7+k3s-8e1b2340 (8e1b2340)
go version go1.16.10
```
$ uname -a
```
Linux ip-172-31-24-147 5.11.0-1022-aws
#23~20.04.1-Ubuntu SMP
Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'
```
X509v3 Subject Alternative Name:
  DNS:ip-172-31-24-147, DNS:
  localhost, IP Address:127.0.0.1,
  IP Address:172.31.24.147,
  IP Address:3.136.86.50
  Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:cb:35:3f:af:99:10:dc:0a:83:58:22:b8:69:
```
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 ./install.sh
$ sudo systemctl stop k3s.service
$ sudo k3s server --token $TOKEN --kube-apiserver-arg kubelet-preferred-address-types=ExternalIP --node-external-ip $EXTERNAL_IP
**tty2**
$ sudo chmod 644 /etc/rancher/k3s/k3s.yaml
$ watch kubectl get nodes
```
NAME               STATUS   ROLES                  AGE   VERSION
ip-172-31-24-147   Ready    control-plane,master   50m   v1.21.7+k3s-8e1b2340
justin80           Ready    <none>                 37m   v1.21.7+k3s-8e1b2340
justin49           Ready    <none>                 38m   v1.21.7+k3s-8e1b2340
```
Interesting Logs on Server node
```
I1208 22:57:10.085436   19324 garbagecollector.go:151] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
W1208 22:57:17.063081   19324 lease.go:233] Resetting endpoints for master service "kubernetes" to [3.136.86.50]
INFO[2021-12-08T22:57:17.067179375Z] Stopped tunnel to 172.31.24.147:6443
INFO[2021-12-08T22:57:17.067419556Z] Proxy done                                    err="context canceled" url="wss://172.31.24.147:6443/v1-k3s/connect"
INFO[2021-12-08T22:57:17.067657802Z] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
```
---------------------------------------------------------------------------------------------
**Digital Ocean CentOS Agents X2**
---------------------------------------------------------------------------------------------
  Agent1
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin49 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
$ echo $EXTERNAL_IP
`143.198.63.165`
$ echo $EXECEC
`agent --node-external-ip 143.198.63.165 sh -`
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh
---------------------------------------------------------------------------------------------
  Agent2
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin49 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
$ echo $EXTERNAL_IP
`147.182.250.255`
$ echo $EXECEC
`agent --node-external-ip 147.182.250.255 sh -`
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh
---------------------------------------------------------------------------------------------
$ kubectl logs helm-install-traefik-ct8cl  -n kube-system
```
CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
+ tiller --listen=127.0.0.1:44134 --storage=secret
[main] 2021/12/08 22:24:26 Starting Tiller v2.17.0 (tls=false)
[main] 2021/12/08 22:24:26 GRPC listening on 127.0.0.1:44134
[main] 2021/12/08 22:24:26 Probes listening on :44135
[main] 2021/12/08 22:24:26 Storage driver is Secret
[main] 2021/12/08 22:24:26 Max history per release is 0
Creating /home/klipper-helm/.helm
Creating /home/klipper-helm/.helm/repository
Creating /home/klipper-helm/.helm/repository/cache
Creating /home/klipper-helm/.helm/repository/local
Creating /home/klipper-helm/.helm/plugins
Creating /home/klipper-helm/.helm/starters
Creating /home/klipper-helm/.helm/cache/archive
Creating /home/klipper-helm/.helm/repository/repositories.yaml
Adding stable repo with URL: https://charts.helm.sh/stable/
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ jq -r '.Releases | length'
++ timeout -s KILL 30 helm_v2 ls --all '^traefik$' --output json
[storage] 2021/12/08 22:24:26 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ [[ -n '' ]]
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-9.18.201.tgz --values /config/values-01_HelmChart.yaml
+ exit
NAME: traefik
LAST DEPLOYED: Wed Dec  8 22:24:26 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by VestigeJ** [comment]
_**Validated Functionality**_
Using Commit ID - 8e1b2340c9f85af3adf63ce5af54e1444c808b35 ( ARM was still building at this time )
---------------------------------------------------------------------------------------------
**AWS EC2 Ubuntu 20.04 Server Node**
---------------------------------------------------------------------------------------------
$ k3s -v
```
k3s version v1.21.7+k3s-8e1b2340 (8e1b2340)
go version go1.16.10
```
$ uname -a
```
Linux ip-172-31-24-147 5.11.0-1022-aws
#23~20.04.1-Ubuntu SMP
Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'
```
X509v3 Subject Alternative Name:
  DNS:ip-172-31-24-147, DNS:
  localhost, IP Address:127.0.0.1,
  IP Address:172.31.24.147,
  IP Address:3.136.86.50
  Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:cb:35:3f:af:99:10:dc:0a:83:58:22:b8:69:
```
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 ./install.sh
$ sudo systemctl stop k3s.service
$ sudo k3s server --token $TOKEN --kube-apiserver-arg kubelet-preferred-address-types=ExternalIP --node-external-ip $EXTERNAL_IP
**tty2**
$ sudo chmod 644 /etc/rancher/k3s/k3s.yaml
$ watch kubectl get nodes
```
NAME               STATUS   ROLES                  AGE   VERSION
ip-172-31-24-147   Ready    control-plane,master   50m   v1.21.7+k3s-8e1b2340
justin80           Ready    <none>                 37m   v1.21.7+k3s-8e1b2340
justin49           Ready    <none>                 38m   v1.21.7+k3s-8e1b2340
```
Interesting Logs on Server node
```
I1208 22:57:10.085436   19324 garbagecollector.go:151] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
W1208 22:57:17.063081   19324 lease.go:233] Resetting endpoints for master service "kubernetes" to [3.136.86.50]
INFO[2021-12-08T22:57:17.067179375Z] Stopped tunnel to 172.31.24.147:6443
INFO[2021-12-08T22:57:17.067419556Z] Proxy done                                    err="context canceled" url="wss://172.31.24.147:6443/v1-k3s/connect"
INFO[2021-12-08T22:57:17.067657802Z] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
```
---------------------------------------------------------------------------------------------
**Digital Ocean CentOS Agents X2**
---------------------------------------------------------------------------------------------
 
 Agent1
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin49 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
$ echo $EXTERNAL_IP
`143.198.63.165`
$ echo $EXECEC
`agent --node-external-ip 143.198.63.165 sh -`
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh


  Agent2
---------------------------------------------------------------------------------------------
$ uname -a
`Linux Justin49 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
$ echo $EXTERNAL_IP
`147.182.250.255`
$ echo $EXECEC
`agent --node-external-ip 147.182.250.255 sh -`
$ INSTALL_K3S_COMMIT=8e1b2340c9f85af3adf63ce5af54e1444c808b35 INSTALL_K3S_EXEC="agent --node-external-ip $EXTERNAL_IP sh -" ./install-k3s.sh



$ kubectl logs helm-install-traefik-ct8cl  -n kube-system
```
CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
+ tiller --listen=127.0.0.1:44134 --storage=secret
[main] 2021/12/08 22:24:26 Starting Tiller v2.17.0 (tls=false)
[main] 2021/12/08 22:24:26 GRPC listening on 127.0.0.1:44134
[main] 2021/12/08 22:24:26 Probes listening on :44135
[main] 2021/12/08 22:24:26 Storage driver is Secret
[main] 2021/12/08 22:24:26 Max history per release is 0
Creating /home/klipper-helm/.helm
Creating /home/klipper-helm/.helm/repository
Creating /home/klipper-helm/.helm/repository/cache
Creating /home/klipper-helm/.helm/repository/local
Creating /home/klipper-helm/.helm/plugins
Creating /home/klipper-helm/.helm/starters
Creating /home/klipper-helm/.helm/cache/archive
Creating /home/klipper-helm/.helm/repository/repositories.yaml
Adding stable repo with URL: https://charts.helm.sh/stable/
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ jq -r '.Releases | length'
++ timeout -s KILL 30 helm_v2 ls --all '^traefik$' --output json
[storage] 2021/12/08 22:24:26 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ [[ -n '' ]]
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-9.18.201.tgz --values /config/values-01_HelmChart.yaml
+ exit
NAME: traefik
LAST DEPLOYED: Wed Dec  8 22:24:26 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by VestigeJ** [comment]
## Server Node hosted in aws
$ k3s -v
```
k3s version v1.21.7-rc2+k3s2 (5260e4a6)
go version go1.16.10
```

$ uname -a
```
Linux ip-12-3-7-18.us-north-9.compute.internal 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

$ sudo openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'
```
X509v3 Subject Alternative Name: 
DNS:ip-12-3-7-18.us-north-9.compute.internal, DNS:localhost, 
IP Address:127.0.0.1, IP Address:12.3.7.18, IP Address:18.17.21.23
Signature Algorithm: ecdsa-with-SHA256
30:44:02:20:42:61:70:ec:bb:c2:69:bf:02:52:2d:51:73:26:
```

$ COMMIT=5260e4a649ace3888781c28c702af5c318cbc276
$ sudo INSTALL_K3S_COMMIT=$COMMIT  ./install.sh 
$ EXECEC="server --kube-apiserver-arg kubelet-preferred-address-types=18.17.21.23 sh -"

$ kubectl get nodes
```
NAME                                          STATUS   ROLES                  AGE     VERSION
ip-12-3-7-18.us-north-9.compute.internal   Ready    control-plane,master   2m59s   v1.21.7-rc2
+k3s2
justin68                                      Ready    <none>                 21s     v1.21.7-rc2
+k3s2
```


---------------------------------------------------------------------------------------------
Agent Node hosted in digital ocean

$ k3s -v
```
k3s version v1.21.7-rc2+k3s2 (5260e4a6)
go version go1.16.10
```

$ uname -a
```
Linux Justin68 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

$ EXTERNAL_IP=199.232.13.14
$ EXECEC="agent --node-external-ip $EXTERNAL_IP sh -"
$ COMMIT=5260e4a649ace3888781c28c702af5c318cbc276
