### ISSUE TITLE
arg --pause-image not work for containerd, but work for --docker

### ISSUE THREAD

**Issue by dianny123** [k3s-io/k3s#4673]
**Environmental Info:**
K3s Version: 
v1.22.4+k3s1
Node(s) CPU architecture, OS, and Version: 
Linux XXX 4.19.112-2.el8.x86_64 #1 SMP Wed Jun 10 09:04:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

**Describe the bug:**
when start k3s server with command '`k3s server --docker --pause-image rancher/mirrored-pause:3.1`', the pods works fine.
But when start with '`k3s server --pause-image rancher/mirrored-pause:3.1'`, the pods always with status 'ContainerCreating'.
Following is the error info from pods:
```
[root]#k3s kubectl describe pods nginx-deployment-78cfbb5bb6-rztct
Warning  FailedCreatePodSandBox  87s (x187 over 41m)  kubelet            Failed to create pod sandbox: rpc error: code = NotFound desc = failed to get image from containerd "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e": image "docker.io/rancher/mirrored-pause:3.1": not found
```
Additional info is I use private image registry, but i don't think k3s should pull images from my  private image registry, if `--pause-image` is defined for local images.

**Steps To Reproduce:**

- Installed K3s: via binary and systemd from k3s-io/k3s/k3s.service file
- use `k3s crictl pull rancher/mirrored-pause:3.1` , to pull images from private image registry. 
- `[root]# k3s crictl images list`

```
IMAGE                                                           TAG                 IMAGE ID            SIZE
rancher/mirrored-pause   3.1                 da86e6ba6ca19       746kB
```
- use `k3s server --pause-image rancher/mirrored-pause:3.1` to start k3s server.

- use `k3s kubectl apply -f XXX` 
- use `k3s kubectl describe pods nginx-deployment-78cfbb5bb6-rztct` to see pods detail info
```
Name:           nginx-deployment-78cfbb5bb6-rztct
Namespace:      default
Priority:       0
Node:           XXXX
Start Time:     Wed, 08 Dec 2021 16:01:26 +0800
Labels:         app=nginx
                pod-template-hash=78cfbb5bb6
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/nginx-deployment-78cfbb5bb6
Containers:
  nginx:
    Container ID:   
    Image:          nginx:1.14.2
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
    Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
 ......
  **Warning  FailedCreatePodSandBox  3m47s (x280 over 63m)  kubelet  Failed to create pod sandbox: rpc error: code = NotFound desc = failed to get image from containerd "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e": image "docker.io/rancher/mirrored-pause:3.1": not found**
```

**Expected behavior:**
pods are running successful.

**Actual behavior:**
pods is pending with error info:
Warning  FailedCreatePodSandBox  3m47s (x280 over 63m)  kubelet  Failed to create pod sandbox: rpc error: code = NotFound desc = failed to get image from containerd "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e": image "docker.io/rancher/mirrored-pause:3.1": not found

**Comment by brandond** [comment]
> Additional info is I use private image registry, but i don't think k3s should pull images from my private image registry, if --pause-image is defined for local images.

When using registries.yaml, the pause image will be pulled using your mirror configuration, regardless of what image you've specified. Docker doesn't honor registries.yaml though, so that should not matter.

> Warning FailedCreatePodSandBox 3m47s (x280 over 63m) kubelet Failed to create pod sandbox: rpc error: code = NotFound desc = failed to get image from containerd

This suggests that K3s is still running with containerd, not docker. Can you do `kubectl get node -o yaml`

**Comment by dianny123** [comment]
@brandond Hi Thanks for reply!
The issue Suddenly disappeard! I don't know what has been done.  K3s works fine now.
This issue can be closed. Thank you！
