### ISSUE TITLE
pod creation failure: "no IP addresses available in range set"

### ISSUE THREAD

**Issue by jeanpommier** [k3s-io/k3s#4682]
**Environmental Info:**
K3s Version: 
v1.21.5+k3s2

Node(s) CPU architecture, OS, and Version: 
3 AMD64 nodes, Debian 10.11

Cluster Configuration:
1 server (VPS), 2 agents (1 VPS, 1 baremetal)

**Describe the bug:**
I'm regularly pod creation failures. The error message is 
```
Warning  FailedCreatePodSandBox  4m39s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d615cc04143d0a1e4be8aa76e4214bc7add843b4e6c4813d6dbfee223e1c29d6": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
```
If I look on the node, in the folder /var/lib/cni/networks/cbr0, all IPs are indeed reserved, even though I don't have that many pods running. It looks like the IPs are not cleared when a pod is destroyed.
I had the same issue also on my dev environment (similar config)

I found a quick workaround: remove the said folder and restart the node. But this is not really production-friendly.

I must say I'm running several cronjobs. It most of the time occurs when a cronjob is being created.

**Steps To Reproduce:**
```
1. configure iptables on Debian on all nodes (ref. https://github.com/k3s-io/k3s/issues/4406)
apt-get install -y iptables arptables ebtables curl rsync acl
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set arptables /usr/sbin/arptables-legacy
update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```
2. install K3S on control plane  using k3sup
```
k3sup install --ssh-key ~/.ssh/id_ed25519 --ip ${K3S_CONTROL_PLANE_IP} --user root --k3s-channel stable --local-path ~/dev/sk/psk/kubernetes_migration/kube-config.yaml --context psk-prod

# Taint it so that it doesn't get workload
kubectl config use-context psk-prod
kubectl taint nodes -l node-role.kubernetes.io/control-plane=true dedicated_control-plane:NoSchedule
```
3. Configure worker nodes using k3sup:
```
k3sup join --ssh-key ~/.ssh/id_ed25519 --ip ${K3S_WORKER_IP} --user root --k3s-channel stable --server-ip ${K3S_CONTROL_PLANE_IP}
```

**Expected behavior:**
I would expect K3S to be able to assign an IP to any new pod, as long as I'm not hosting more than 254 pods on the node

**Actual behavior:**
From time to time, I'm stuck with K3S being unable to create the pods because no IP is available. My only workaround is to go on the node, remove all entries in /var/lib/cni/networks/cbr0 and restart the node (which means my services are down for several minutes)

**Additional context / logs:**
Events through kubectl
```
Warning  FailedCreatePodSandBox  21m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8890212e0fbd5fdb07ddb98b46ddd5fd7a969c260cb36d093293e8f36e1a1f37": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
  Warning  FailedCreatePodSandBox  20m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f877efdae345073a069bda06b53584dca3f75d673f75660e94efd19120a2092e": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
  Warning  FailedCreatePodSandBox  19m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1f652b4d7342db191abdabd57afe92ba4e05d4340d7b3d0fbb6fce4b62dbb43b": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
  Warning  FailedCreatePodSandBox  17m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d615cc04143d0a1e4be8aa76e4214bc7add843b4e6c4813d6dbfee223e1c29d6": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
  Warning  FailedCreatePodSandBox  24s (x14 over 16m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2d0a0b88f74946b97328638bf2d9ed69d16c066039bc291126a6f1af529147c1": failed to allocate for range 0: no IP addresses available in range set: 10.42.2.1-10.42.2.254
```

**Comment by manuelbuil** [comment]
Not sure what is going on in your env. k3s by default uses flannel as the CNI plugin. Flannel is using the host-local ipam to distribute ips. The host-local ipam should remove the files in `/var/lib/cni/networks/cbr0` when the pod is removed from the system: https://github.com/containernetworking/plugins/blob/master/plugins/ipam/host-local/main.go#L137-L164

Can you confirm that pods are completely removed and do not exist with an error? Can you dump the k3s logs? If you execute `ip a` in an agent, do you see the veth interfaces?

**Comment by manuelbuil** [comment]
I'm trying to reproduce the issue in Debian 10.11 with k3s-1.21 but I see how the ips are removed ( 10.42.1.4 and  10.42.1.5) as soon as the pod is removed:
```
admin@ip-10-0-10-46:~$ sudo ls /var/lib/cni/networks/cbr0
10.42.1.2  10.42.1.3  10.42.1.4  10.42.1.5  last_reserved_ip.0	lock
admin@ip-10-0-10-46:~$ sudo ls /var/lib/cni/networks/cbr0
10.42.1.2  10.42.1.3  10.42.1.5  last_reserved_ip.0  lock
admin@ip-10-0-10-46:~$ sudo ls /var/lib/cni/networks/cbr0
10.42.1.2  10.42.1.3  last_reserved_ip.0  lock
```
Can you create a dummy pod and verify that the ip address is in `/var/lib/cni/networks/cbr0`?. Then remove it and check if the ip is still in `/var/lib/cni/networks/cbr0` please

**Comment by jeanpommier** [comment]
Hi,
Thank you for your help

> Not sure what is going on in your env. k3s by default uses flannel as the CNI plugin. Flannel is using the host-local ipam to distribute ips. The host-local ipam should remove the files in `/var/lib/cni/networks/cbr0` when the pod is removed from the system: https://github.com/containernetworking/plugins/blob/master/plugins/ipam/host-local/main.go#L137-L164
> 
> Can you confirm that pods are completely removed and do not exist with an error? Can you dump the k3s logs? If you execute `ip a` in an agent, do you see the veth interfaces?

When I run `kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=w2.geopresovregion.sk` (the node that causes trouble), I only get 9 pods.

Here is the dump of k3s logs (command run is `journalctl --no-pager -u k3s &> k3s.log`)
[k3s.log.gz](https://github.com/k3s-io/k3s/files/7677893/k3s.log.gz)

If I run `ip a ` on the troublesome worker node, I'm getting 4 veth interfaces (and I've got 4 running pods at that moment)

What's weird is that it seems to work well on the second worker node, that is much more active (and bigger). The main difference is that the troublesome node (w2) is a VPS, while the working node (w1) is a baremetal server. So they might have slightly different configs.

I'll try the experiment you suggest and let you know

**Comment by brandond** [comment]
I wonder if perhaps the VPS has some extra udev or systemd hooks enabled that are trying to manage the veth interfaces that are created for the containers. If something is preventing the container interfaces from being torn down, that would explain why the IPs cannot be reused. You might take a look at the system logs and see if there are any differences in the messages from systemd/avahi/udev between your VPS and bare-metal host regarding virtual interface management.

**Comment by jeanpommier** [comment]
Thanks @brandond. It seems a bit hardcore for me to follow you there, but I'll try.

Actually, just restarting the VPS was enough for the IPs and veths to be cleared.

What's weird is that I've had this issue on 2 VPS : the one we are talking about, hosted by Hetzner, and a VPS on my dev setup, hosted by OVH. The fact that it's different hosting providers would have make me believe that it's not related to the VPS initial setup, unless this is something I did myself. Could my iptables settings above be responsible for instance ? I've out of my depth for this and just copied what I found in a ticket here (ttps://github.com/k3s-io/k3s/issues/4406)

**Comment by jeanpommier** [comment]
@manuelbuil I've created a dummy pod: its IP was present in networks/cbr0. When I removed it, it was indeed removed, as expected. 
Same thing for the cronjobs. So it seems to be back into order.

**Comment by jeanpommier** [comment]
Actually, looking at `journalctl -b` on my problematic node (w2), I'm seeing a lot of lines of the kind
```
Dec 08 18:00:02 w2.geopresovregion.sk k3s[642]: I1208 18:00:02.497451     642 pod_container_deletor.go:79] "Container not found in pod's containers" containerID="04eff39dbe70ef012a687c37f87c942df0bce8238179980026fab70e8d8e5db3"
```
So maybe there were some ghost containers blocking the IP from being released ?

**Comment by manuelbuil** [comment]
> @manuelbuil I've created a dummy pod: its IP was present in networks/cbr0. When I removed it, it was indeed removed, as expected. Same thing for the cronjobs. So it seems to be back into order.

Thanks for checking. I wonder why it is happening sometimes, can you remember doing something differently?

**Comment by jeanpommier** [comment]
Me ? Nope. I should ask kubectl ;o)

I've had this happening twice on my dev server, on which I've been very idle lately, so I don't think it's something I have _done_. At least not with a direct and quick reaction (of course, my configuration can be bad, I'm not a k8s guru, not even a trained sysadmin) 

I know I couldn't set up K3S on Debian 11 (networking issues), so I switched back to Debian 10, but could it be that there is also some networking issues on Debian 10 ?
