### ISSUE TITLE
ipallocator-repair-controller doesn't seem to support non-default service cidr

### ISSUE THREAD

**Issue by dpippenger** [k3s-io/k3s#4708]
**Environmental Info:**
K3s Version:  v1.21.7+k3s1 (ac705709)

Cluster Configuration:
3 node embedded HA config using host-gw flannel backend and custom cluster/service cidr

**Describe the bug:**
After install the ipallocator-repair-controller logs the following periodically
```
Cluster IP [IPv4]:10.5.0.1 is not within the service CIDR 10.43.0.0/16; please recreate service
```

**Steps To Reproduce:**

- Installed K3s: 
```
export INSTALL_K3S_EXEC="--etcd-expose-metrics=true --flannel-backend=host-gw --cluster-cidr=10.4.0.0/16 --service-cidr=10.5.0.0/16 --cluster-dns=10.5.0.10"
curl -sfL https://get.k3s.io | sh -s server --cluster-init 
```

**Expected behavior:**
ipallocator-repair-controller checks correct service CIDR range

**Actual behavior:**

ipallocator-repair-controller checks default service CIDR range

**Additional context / logs:**

```
# kubectl cluster-info dump | grep -i cidr 
                    "k3s.io/node-args": "[\"server\",\"--etcd-expose-metrics\",\"true\",\"--flannel-backend\",\"host-gw\",\"--cluster-cidr\",\"10.4.0.0/16\",\"--service-cidr\",\"10.5.0.0/16\",\"--cluster-dns\",\"10.5.0.10\",\"--cluster-domain\",\"cpcm.io\",\"server\",\"--cluster-init\"]",
                "podCIDR": "10.4.0.0/24",
                "podCIDRs": [
                "podCIDR": "10.4.1.0/24",
                "podCIDRs": [
                "podCIDR": "10.4.2.0/24",
                "podCIDRs": [
            "message": "Cluster IP [IPv4]:10.5.0.10 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.0.10 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.10.36 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.10.36 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.130.186 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.130.186 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.0.1 is not within the service CIDR 10.43.0.0/16; please recreate service",
            "message": "Cluster IP [IPv4]:10.5.0.1 is not within the service CIDR 10.43.0.0/16; please recreate service",
```

**Comment by brandond** [comment]
It looks to me like you changed the CIDRs after the cluster was initially started, and services were allocated addresses in the default cluster CIDR. This isn't supported by Kubernetes; you must set the desired CIDRs during initial cluster startup.

**Comment by dpippenger** [comment]
Except I didn't. This is a fresh install. I've deleted it multiple times and purged any files in /var/lib/rancher and /etc/rancher.

**Comment by brandond** [comment]
You've got something left behind from a previous install. I can confirm that this works on a clean cluster using the same args you're using:
`docker run -it --rm --privileged --name k3s-server-1 --hostname k3s-server-1 rancher/k3s:v1.21.7-k3s1 server --etcd-expose-metrics=true --flannel-backend=host-gw --cluster-cidr=10.4.0.0/16 --service-cidr=10.5.0.0/16 --cluster-dns=10.5.0.10`

```console
brandond@dev01:~$ docker exec -it k3s-server-1 kubectl get service -A
NAMESPACE     NAME             TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
default       kubernetes       ClusterIP      10.5.0.1       <none>        443/TCP                      2m47s
kube-system   kube-dns         ClusterIP      10.5.0.10      <none>        53/UDP,53/TCP,9153/TCP       2m45s
kube-system   metrics-server   ClusterIP      10.5.253.6     <none>        443/TCP                      2m44s
kube-system   traefik          LoadBalancer   10.5.245.231   172.17.0.2    80:31722/TCP,443:30850/TCP   2m17s
```

**Comment by dpippenger** [comment]
Could you please provide un-install instructions? I run k3s-uninstall.sh on all nodes. Then for good measure remove /var/lib/rancher (empty dir at this point) and /etc/rancher (only contains a password file at this point).

I've searched the filesystem looking for evidence of other files deployed by k3s and I've been unable to find them.

**Comment by dpippenger** [comment]
Also I'm not sure your test is valid, I also get the same results from a kubectl get service -A
```
 kubectl get service -A
NAMESPACE     NAME             TYPE           CLUSTER-IP     EXTERNAL-IP                     PORT(S)                      AGE
default       kubernetes       ClusterIP      10.5.0.1       <none>                          443/TCP                      41m
kube-system   kube-dns         ClusterIP      10.5.0.10      <none>                          53/UDP,53/TCP,9153/TCP       41m
kube-system   metrics-server   ClusterIP      10.5.10.36     <none>                          443/TCP                      41m
kube-system   traefik          LoadBalancer   10.5.130.186   10.0.0.25,10.0.0.26,10.0.0.27   80:30784/TCP,443:32248/TCP   40m
```

**Comment by brandond** [comment]
I can't replicate the messages you're getting, either. Where are those coming from? Can you provide the full `cluster-info` output?

```console
brandond@dev01:~$ docker exec k3s-server-1 kubectl cluster-info dump | grep -i CIDR
                    "k3s.io/node-args": "[\"server\",\"--etcd-expose-metrics\",\"true\",\"--flannel-backend\",\"host-gw\",\"--cluster-cidr\",\"10.4.0.0/16\",\"--service-cidr\",\"10.5.0.0/16\",\"--cluster-dns\",\"10.5.0.10\"]",
                "podCIDR": "10.4.0.0/24",
                "podCIDRs": [
```

**Comment by dpippenger** [comment]
The only thing I've done beyond running the install for k3s using the command referenced is that I've accessed the cluster with Lens. This is my first k8s cluster but I don't think Lens automatically installs anything on connect. Is ipallocator-repair-controller not part of k3s?

[kubectl-dump.txt](https://github.com/k3s-io/k3s/files/7688034/kubectl-dump.txt)

**Comment by brandond** [comment]
Oh. You've not set the same values on all your servers, so two out of the three nodes are trying to use the wrong CIDRs:
```
                    "k3s.io/hostname": "slug1.cpcm.io",
                    "k3s.io/internal-ip": "10.0.0.25",
                    "k3s.io/node-args": "[\"server\",\"--etcd-expose-metrics\",\"true\",\"--flannel-backend\",\"host-gw\",\"--cluster-cidr\",\"10.4.0.0/16\",\"--service-cidr\",\"10.5.0.0/16\",\"--cluster-dns\",\"10.5.0.10\",\"--cluster-domain\",\"cpcm.io\",\"server\",\"--cluster-init\"]",

                    "k3s.io/hostname": "slug2.cpcm.io",
                    "k3s.io/internal-ip": "10.0.0.26",
                    "k3s.io/node-args": "[\"server\",\"--server\",\"https://slug1.cpcm.io:6443\"]",
                    
                    "k3s.io/hostname": "slug3.cpcm.io",
                    "k3s.io/internal-ip": "10.0.0.27",
                    "k3s.io/node-args": "[\"server\",\"--server\",\"https://slug1.cpcm.io:6443\"]"
```

You need to provide the same configuration to all nodes in the cluster.

**Comment by brandond** [comment]
You've also got `server` in your args twice on the first node, but it's not hurting anything.

**Comment by dpippenger** [comment]
Ahh, the documentation doesn't explain this. So I should use the same INSTALL_K3S_EXEC on every node? Or just the server nodes?

**Comment by brandond** [comment]
The servers all need the same configuration, yes. Aside from the `--cluster-init` and `--server` flags of course.

**Comment by dpippenger** [comment]
Things seem happier now, thank you for your assistance.

**Comment by dpippenger** [comment]
Oh maybe I spoke too soon... the second master node seems to not like to get the same flags as the first master...
```
export K3S_TOKEN="SECRET"
export INSTALL_K3S_EXEC="--etcd-expose-metrics=true --flannel-backend=host-gw --cluster-cidr=10.4.0.0/16 --service-cidr=10.5.0.0/16 --cluster-dns=10.5.0.10 --cluster-domain=cpcm.io"
export K3S_URL="https://slug1.cpcm.io:6443"
curl -sfL https://get.k3s.io | sh -s server --server https://slug1.cpcm.io:6443
```

Adding the INSTALL_K3S_EXEC seems to make the install run in "agent" mode

**Comment by dpippenger** [comment]
Ok, I see I think... K3S_URL being present without INSTALL_K3S_EXEC seemed to be ok, but having it in there with K3S_EXEC seems to make it go into agent mode instead of server. Removing the K3S_URL environment from the other masters seems to have fixed it.
