### ISSUE TITLE
k3s server  failed to start.

### ISSUE THREAD

**Issue by mutomasa** [k3s-io/k3s#4726]
**Environmental Info:**
-3 VM Environment

k3s version v1.20.11+k3s2 (9cb5fb57)
go version go1.15.14

Node(s) CPU architecture, OS, and Version: 

*-cpu                     
       description: CPU
       product: Common KVM processor
       vendor: Intel Corp.
       physical id: 400
       bus info: cpu@0
       version: pc-i440fx-6.1
       slot: CPU 0
       size: 2GHz
       capacity: 2GHz
       width: 64 bits

Ubuntu Version:Ubuntu 20.04.3 LTS
Kernel Version:Linux xxxx 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

- k3s HA( 3 server)
- https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Describe the bug:**

when I was trying to setup a k3s HA with an external PostgreSQL,I could not get the second and third node active in a systemctl environment.
・I succeded to setup the k3s in the first node by executing the command line.
export K3S_KUBECONFIG_MODE="644" 
curl -sfL https://get.k3s.io |INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN='test' INSTALL_K3S_EXEC='server --cluster-init --kubelet-arg=max-pods=240 --datastore-endpoint=postgres://postgres:password@xxx.xxx.xx.xxx:5432/k3s?sslmode=disable'　 sh  -

・I failed to setup the k3s in the second and third node by executing the command line.
export K3S_KUBECONFIG_MODE="644" 
curl -sfL https://get.k3s.io |INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN='test' INSTALL_K3S_EXEC='server --server https://xxx.xxx.xx.xxx:6443 --kubelet-arg=max-pods=240' sh  -

**Steps To Reproduce:**

- the first node:
export K3S_KUBECONFIG_MODE="644" 
curl -sfL https://get.k3s.io |INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN='test' INSTALL_K3S_EXEC='server --cluster-init --kubelet-arg=max-pods=240 --datastore-endpoint=postgres://postgres:password@xxx.xxx.xx.xxx:5432/k3s?sslmode=disable'　 sh  -

- the second the third node:
export K3S_KUBECONFIG_MODE="644" 
curl -sfL https://get.k3s.io |INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN='test' INSTALL_K3S_EXEC='server --server https://xxx.xxx.xx.xxx:6443 --kubelet-arg=max-pods=240' sh  -

**Expected behavior:**

the k3s of the second and third node succeed to start.

**Actual behavior:**

the k3s of the second and third node failed to start.

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Ok, and what do the logs say? It's difficult to troubleshoot an issue without knowing anything more than "it's not working".

**Comment by mutomasa** [comment]
@brandond 
sorry to forget the attachement of the logs.
The error output:
journalctl -u  k3s
Dec 10 09:51:39 k3-master2-ubnt2004cloud-init-base k3s[1234]: time="2021-12-10T09:51:39.889410972+09:00" level=fatal msg="starting kubernetes: preparing server: https://192.168.55.228:6443/v1-k3s/server-bootstrap: 401 Unauthorized"
Dec 10 09:51:39 k3-master2-ubnt2004cloud-init-base systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 09:51:39 k3-master2-ubnt2004cloud-init-base systemd[1]: k3s.service: Failed with result 'exit-code'.
Dec 10 09:51:39 k3-master2-ubnt2004cloud-init-base systemd[1]: Failed to start Lightweight Kubernetes.
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1.
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: Stopped Lightweight Kubernetes.
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: Starting Lightweight Kubernetes...
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base sh[1253]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base sh[1259]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base k3s[1269]: time="2021-12-10T09:51:45.274607357+09:00" level=info msg="Starting k3s v1.19.5+k3s1 (b11612e2)"
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base k3s[1269]: time="2021-12-10T09:51:45.303415196+09:00" level=info msg="Managed etcd cluster not yet initialized"
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base k3s[1269]: time="2021-12-10T09:51:45.305338496+09:00" level=fatal msg="starting kubernetes: preparing server: https://xxx.xxx.xx.xxx:6443/v1-k3s/server-bootstrap: 401 Unauthorized"
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: k3s.service: Failed with result 'exit-code'.
Dec 10 09:51:45 k3-master2-ubnt2004cloud-init-base systemd[1]: Failed to start Lightweight Kubernetes.

**Comment by brandond** [comment]
Ah, I see. 

You're using an external SQL database. You should just configure all three servers with the same arguments - the datastore endpoint being the most important.

If you start the additional servers with the --server argument specified, it expects to join an etcd cluster, which is not what you're doing.

**Comment by brandond** [comment]
Also, the docs for what you're doing are at
https://rancher.com/docs/k3s/latest/en/installation/ha/

**Comment by mutomasa** [comment]
@brandond 
Thank you so much for helping me out.
your comments solved my issue.
