### ISSUE TITLE
local-path-provisioner failed to start until I created /var/lib/rancher/k3s/storage

### ISSUE THREAD

**Issue by moschlar** [k3s-io/k3s#4727]
**Environmental Info:**
K3s Version: 
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux rancher-03 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

Cluster Configuration:

1 server (with cluster-init, but no other nodes joined yet)

**Describe the bug:**
After setting up k3s, I noted that replicaset, deployment and pod for local-path-provisioner in the kube-system namespace didn't come up. After digging around, I tried out manually creating the directory /var/lib/rancher/k3s/storage about which I read somewhere and suddenly the pod became running.

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://get.k3s.io | sh -s - server --cluster-init

**Additional context / logs:**
```
rancher-03:~ # k3s kubectl -n kube-system logs pod/local-path-provisioner-5ff76fc89d-x7dxb
time="2021-12-13T10:41:05Z" level=fatal msg="Error starting daemon: invalid empty flag helper-pod-file and it also does not exist at ConfigMap kube-system/local-path-config with err: configmaps \"local-path-config\" is forbidden: User \"system:serviceaccount:kube-system:local-path-provisioner-service-account\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\": RBAC: clusterrole.rbac.authorization.k8s.io \"local-path-provisioner-role\" not found" 
```

**Comment by brandond** [comment]
It sounds like the root cause of your problem is missing cluster RBAC for the local-path provisioner. Can you attach the complete k3s service logs, from k3s startup onwards?

**Comment by moschlar** [comment]
Hm. I did another run later on where the pod came up about ten minutes after cluster instantiation and I try to put the relevant timestamps here:

<details>
<summary><code>stat /var/lib/rancher/k3s/storage/</code></summary>
<pre>
  File: /var/lib/rancher/k3s/storage/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 528575      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-12-13 13:42:48.281173211 +0100
Modify: 2021-12-13 13:42:48.281173211 +0100
Change: 2021-12-13 13:42:48.281173211 +0100
 Birth: -
</pre>
</details>

<details>
<summary><code>kubectl -n kube-system describe pod local-path-provisioner-5ff76fc89d-8vvf8</code></summary>
<pre>
Name:                 local-path-provisioner-5ff76fc89d-8vvf8
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 rancher-03/10.94.7.136
Start Time:           Mon, 13 Dec 2021 13:42:37 +0100
Labels:               app=local-path-provisioner
                      pod-template-hash=5ff76fc89d
Annotations:          <none>
Status:               Running
IP:                   10.42.0.6
IPs:
  IP:           10.42.0.6
Controlled By:  ReplicaSet/local-path-provisioner-5ff76fc89d
Containers:
  local-path-provisioner:
    Container ID:  containerd://aca8cfcd8a3be12f76778216778193ddd23c5bc14b90f2890e7e1172acbeb051
    Image:         rancher/local-path-provisioner:v0.0.19
    Image ID:      docker.io/rancher/local-path-provisioner@sha256:9666b1635fec95d4e2251661e135c90678b8f45fd0f8324c55db99c80e2a958c
    Port:          <none>
    Host Port:     <none>
    Command:
      local-path-provisioner
      start
      --config
      /etc/config/config.json
    State:          Running
      Started:      Mon, 13 Dec 2021 13:51:16 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 13 Dec 2021 13:50:31 +0100
      Finished:     Mon, 13 Dec 2021 13:50:31 +0100
    Ready:          True
    Restart Count:  4
    Environment:
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/config/ from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9ggwf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      local-path-config
    Optional:  false
  kube-api-access-9ggwf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
</pre>
</details>

[journalctl-u-k3s-since-13:40-until-13-55.log](https://github.com/k3s-io/k3s/files/7710377/journalctl-u-k3s-since-13.40-until-13-55.log)

**Comment by xiaods** [comment]
yes, i came across same issue.

**Comment by xiaods** [comment]
https://github.com/rancher/local-path-provisioner/issues/211

**Comment by xiaods** [comment]
@moschlar  i double check this https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml, it works

**Comment by xiaods** [comment]
k3s release-1.21 branch need update for this local-path-storage.yaml

**Comment by xiaods** [comment]
upstream already fix it.

**Comment by brandond** [comment]
I can't reproduce this on 1.21. Is there something unique about your configuration?
