### ISSUE TITLE
Snapshot Restoration failing on blank nodes

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#4739]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by mdrahman-suse** [comment]
Validated in https://github.com/k3s-io/k3s/issues/4703#issuecomment-996594231
