### ISSUE TITLE
k3s won't startup with tailscale if ipv6 applied

### ISSUE THREAD

**Issue by tearfulDalvik** [k3s-io/k3s#4743]
**Environmental Info:**
K3s Version: k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: Linux  5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 master

**Describe the bug:**

Cluster master won't startup if `--flannel-iface=tailscale0` is provided in `INSTALL_K3S_EXEC`. Only occurs when ipv6 is enabled.

Work if `--flannel-iface` is not set or not tailscale0:
```curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=100.xxx,fd7a:xxx --disable-network-policy=true --service-cidr=10.43.0.0/16,fc15:2::/112 --cluster-cidr=10.42.0.0/16,fc15:1::/56  --flannel-iface=eth0" sh -```  

Work if ipv4 only:
```curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=100.xxx --service-cidr=10.43.0.0/16 --cluster-cidr=10.42.0.0/16  --flannel-iface=tailscale0" sh -```  

Does not work: 
```curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=100.xxx,fd7a:xxx --disable-network-policy=true --service-cidr=10.43.0.0/16,fc15:2::/112 --cluster-cidr=10.42.0.0/16,fc15:1::/56 --flannel-iface=tailscale0" sh -```

**Steps To Reproduce:**

```
curl -fsSL https://tailscale.com/install.sh | sh
tailscale up
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=100.xxx,fd7a:xxx --disable-network-policy=true --service-cidr=10.43.0.0/16,fc15:2::/112 --cluster-cidr=10.42.0.0/16,fc15:1::/56 --flannel-iface=tailscale0" sh -
```
*Please change 100.xxx,fd7a:xxx to your actual ip on tailscale0*

**Expected behavior:**

Cluster master will startup with ipv6 functionalities

**Actual behavior:**

Cluster master throw an error: `flannel exited: failed to configure interface flannel-v6.1: failed to ensure v6 address of interface flannel-v6.1: failed to add v6 IP address fc15:1::/56 to flannel-v6.1: invalid argument` and keep restarting

There seems to be related to the flannel cni:
```
root@:/home/ubuntu# ip addr add fc15:1::/56 dev flannel-v6.1
RTNETLINK answers: Invalid argument
root@:/home/ubuntu# ip addr add fc15:1::/56 dev tailscale0
root@:/home/ubuntu# echo $?
0
```

**Additional context / logs:**

```
45617 controllermanager.go:142] Version: v1.21.7+k3s1
45617 secure_serving.go:202] Serving securely on 127.0.0.1:10258
45617 tlsconfig.go:240] Starting DynamicServingCertificateController
Level=info msg="Starting /v1, Kind=Secret controller"
45617 kube.go:127] Node controller sync successful
45617 vxlan.go:137] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
45617 kube.go:345] Skip setting NodeNetworkUnavailable
level=fatal msg="flannel exited: failed to configure interface flannel-v6.1: failed to ensure v6 address of interface flannel-v6.1: failed to add v6 IP address fc15:1::/56 to flannel-v6.1: invalid argument"
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
What kind of interface is tailscale0? What driver is it using? Does it support subinterfaces?

**Comment by tearfulDalvik** [comment]
I'm sorry, how can I find out these information?
Now all I know about this interface is:
```
163: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 100.97.54.72/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6261:3648/128 scope global 
       valid_lft forever preferred_lft forever
```

**Comment by tearfulDalvik** [comment]
> What kind of interface is tailscale0? What driver is it using? Does it support subinterfaces?

@brandond Thanks for helping

I'm sorry, how can I find out these information?
Now all I know about this interface is:
```
163: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 100.97.54.72/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6261:3648/128 scope global 
       valid_lft forever preferred_lft forever
```

**Comment by brandond** [comment]
I suspect that since this is a point-to-point connection, it doesn't support adding more than one address of a given type. You might go ask the upstream project at https://github.com/flannel-io/flannel if there is anything that can be done to make this work?

also cc @manuelbuil

**Comment by manuelbuil** [comment]
> I suspect that since this is a point-to-point connection, it doesn't support adding more than one address of a given type. You might go ask the upstream project at https://github.com/flannel-io/flannel if there is anything that can be done to make this work?
> 
> also cc @manuelbuil

Yeah, most likely this is the problem. I'll try to reproduce it

**Comment by manuelbuil** [comment]
@tearfulDalvik before starting digging into this, if you are using tailscale to add wireguard, please note that flannel can use wireguard too when choosing that as backend

**Comment by manuelbuil** [comment]
https://github.com/tailscale/tailscale/issues/3575

**Comment by tearfulDalvik** [comment]
@manuelbuil, thank you. After slightly increasing the MTU, flannel and tailscale works together now. I think that the wireguard backend is not ready for dual stack yet #4364, I'll try after new releases are published.
