### ISSUE TITLE
 ServiceTopology k3s

### ISSUE THREAD

**Issue by justlucknb** [k3s-io/k3s#4748]
How to enable  ServiceTopology in k3s?

I start k3s server with params:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--no-deploy' \
        'traefik' \
        '--kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-proxy-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \

```
Also start a agent:
```

ExecStart=/usr/local/bin/k3s \
    agent \
    '--kube-proxy-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
    '--kubelet-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
```

Label one node:
`kubectl label nodes node1 topology.kubernetes.io/region=us-east-1 --overwrite`

And add TopologyKeys to service:
```
  topologyKeys:
    - "topology.kubernetes.io/region"
```

**But traffic goes to another nodes (what's not labeled)**

What's the problem?

**Comment by brandond** [comment]
How are you testing this? What services are you sending traffic to?

**Comment by justlucknb** [comment]
@brandond A service with the ClusterIP type sends traffic to a simple container. The container gives the user: the hostname and the IP address of the pod. And when I refresh the page, I see that the hostname and IP address are no-label nodes.

**Comment by justlucknb** [comment]
examples:
 https://i.imgur.com/zdkUug8.png
 https://i.imgur.com/zdkUug8.png

**Comment by brandond** [comment]
According to [the documentation](**url**) you need to enable the FeatureGates on all the Kubernetes components, but you've only enabled them on the apiserver and kube-proxy. What happens if you follow the instructions and enable it on kube-controller-manager and kubelet as well?

**Comment by justlucknb** [comment]
@brandond 
Edit k3s server.service: `ExecStart=/usr/local/bin/k3s \
    server \
        '--no-deploy' \
        'traefik' \
        '--kube-scheduler-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-controller-manager-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kube-proxy-arg=feature-gates=ServiceTopology=true,EndpointSlice=true' \
        '--kubelet-arg=feature-gates=ServiceTopology=true,EndpointSlice=true'
        
 but ServiceTopology not working...

**Comment by brandond** [comment]
Reading through the rest of the page I linked, I see that it's actually deprecated since 1.21. What version are you using?

**Comment by justlucknb** [comment]
1.21.1

**Comment by brandond** [comment]
Sounds like you should be looking at Topology Aware Hints instead, or testing on 1.20.
