### ISSUE TITLE
Inclusive Language: Change Master -->  Main

### ISSUE THREAD

**Issue by madeline-brennan** [k3s-io/k3s#4749]
**Is your feature request related to a problem? Please describe.**
It's not a technical problem, but rather an issue that doesn't align with our company style guide. Currently, "master" is a role for our nodes, however, this doesn't meet our inclusive language standards. 

**Describe the solution you'd like**
Change naming from "master" to "main" per https://inclusivenaming.org/word-lists/tier-1/

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot of example from our docs: ![image](https://user-images.githubusercontent.com/85683928/146200134-d50cb4b2-e0d7-494f-96a9-6484652ff3c5.png)

**Backporting**

- [ x ] Needs backporting to older releases
Not sure which/how many branches this applies to--I suspect many

**Comment by brandond** [comment]
The "master" role and taint are in the process of being deprecated. See:
* https://github.com/k3s-io/k3s/pull/2385/commits/b5f6fb0fc6439bbf63eeeec9cdb4776f4af99ff1
* https://github.com/kubernetes/kubernetes/pull/95382
