### ISSUE TITLE
For the installed k3s, the container management tool cannot be switched: docker

### ISSUE THREAD

**Issue by slothjun** [k3s-io/k3s#4763]
**Environmental Info:**
K3s Version: 

k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

Cluster Configuration:

1server,1agents

**Describe the bug:**

for k3s runtime ,exec k3s server --docker . consol print info:
INFO[2021-12-16T15:38:22.268915787+08:00] Starting k3s v1.21.7+k3s1 (ac705709)         
INFO[2021-12-16T15:38:22.275067781+08:00] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
INFO[2021-12-16T15:38:22.275310708+08:00] Configuring database table schema and indexes, this may take a moment... 
INFO[2021-12-16T15:38:22.276654400+08:00] Database tables and indexes are up to date   
INFO[2021-12-16T15:38:22.338303967+08:00] Kine listening on unix://kine.sock           
INFO[2021-12-16T15:38:22.536036455+08:00] Reconciling bootstrap data between datastore and disk 
FATA[2021-12-16T15:38:22.969074749+08:00] starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use 

**Steps To Reproduce:**

- Installed K3s: 
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
- docker info

          Client:
           Context:    default
           Debug Mode: false
           Plugins:
            app: Docker App (Docker Inc., v0.9.1-beta3)
            buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
          
          Server:
           Containers: 0
            Running: 0
            Paused: 0
            Stopped: 0
           Images: 0
           Server Version: 20.10.12
           Storage Driver: overlay2
            Backing Filesystem: extfs
            Supports d_type: true
            Native Overlay Diff: true
            userxattr: false
           Logging Driver: json-file
           Cgroup Driver: systemd
           Cgroup Version: 2
           Plugins:
            Volume: local
            Network: bridge host ipvlan macvlan null overlay
            Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
           Swarm: inactive
           Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
           Default Runtime: runc
           Init Binary: docker-init
           containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
           runc version: v1.0.2-0-g52b36a2
           init version: de40ad0
           Security Options:
            seccomp
             Profile: default
            cgroupns
           Kernel Version: 5.10.63-v7l+
           Operating System: Raspbian GNU/Linux 11 (bullseye)
           OSType: linux
           Architecture: armv7l
           CPUs: 4
           Total Memory: 3.749GiB
           Name: raspberrypi
           ID: 6OQ2:QWVR:25RI:276L:HENX:ZPWS:DZNV:JUJS:IDWR:6MEE:TMXX:3XQ4
           Docker Root Dir: /var/lib/docker
           Debug Mode: false
           Registry: https://index.docker.io/v1/
           Labels:
           Experimental: false
           Insecure Registries:
            127.0.0.0/8
           Live Restore Enabled: false

- k3s server --docker
 sudo k3s server --docker

**Expected behavior:**

The k3s container uses docker instead of containerd
**Actual behavior:**

  The --docker command failed to run
  **Additional context / logs:**
  
INFO[2021-12-16T15:38:22.268915787+08:00] Starting k3s v1.21.7+k3s1 (ac705709)         
INFO[2021-12-16T15:38:22.275067781+08:00] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
INFO[2021-12-16T15:38:22.275310708+08:00] Configuring database table schema and indexes, this may take a moment... 
INFO[2021-12-16T15:38:22.276654400+08:00] Database tables and indexes are up to date   
INFO[2021-12-16T15:38:22.338303967+08:00] Kine listening on unix://kine.sock           
INFO[2021-12-16T15:38:22.536036455+08:00] Reconciling bootstrap data between datastore and disk 
FATA[2021-12-16T15:38:22.969074749+08:00] starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use 

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> sudo k3s server --docker
> FATA[2021-12-16T15:38:22.969074749+08:00] starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use

You're trying to run a second instance of k3s, while the k3s service is still running. You should either edit the CLI flags in the systemd unit and restart it, or re-run the install scripts with the flags you want.
