### ISSUE TITLE
Plain k3s (traefik) doesn't work with cert-manager

### ISSUE THREAD

**Issue by domvo** [k3s-io/k3s#4765]
**Environmental Info:**
K3s Version: 
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux k3snode 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single Node Cluster

**Describe the bug:**
I want to use cert-manager along with ACME to issue certificates.

Cert-manager creates a temporary pod/service/ingress combination for acme to request the challenge (example.com/.well-known/...).

The ingress created by the clusterissuer has a spec called "ingressClassName" with the value of "traefik". Somehow traefik does not pick up this ingress and therefore doesn't serve the challenge correctly. In order to make it work I have to manually edit the created resource and delete the ingressClassName.

**Steps To Reproduce:**
- Installed K3s: `k3sup install --ip <IP> --user root`
- (Wait enough until all resources are installed successfully - give it a minute or two, otherwise CRDs might be missing)
- Installed cert-manager: `cmctl x install`
- Applied ClusterIssuer:
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: email@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secret-key-ref
    solvers:
    - http01:
        ingress:
          class: traefik # note: this is translated to ingressClassName: traefik, but it's mandatory
```
- Applied Certificate:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-certificate
spec:
  secretName: le-certificate-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: example.com
  dnsNames:
    - example.com
```

**Expected behavior:**
The ACME challenge gets resolved

**Actual behavior:**
The ACME challenge cannot get resolved because of a 404 error.

**Additional context / logs:**
This is how the created ingress resource looks like:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  creationTimestamp: "2021-12-16T16:16:53Z"
  generateName: cm-acme-http-solver-
  generation: 1
  labels:
    acme.cert-manager.io/http-domain: "680789352"
    acme.cert-manager.io/http-token: "1281232752"
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-qnkfq
  namespace: test
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: le-certificate-64pxn-1779917817-1391228548
    uid: fe6ef2ef-c619-4658-acd1-ae64d55b9e09
  resourceVersion: "25090"
  uid: 7c02ec7e-888c-4022-a415-ca7315ca54e4
spec:
  ingressClassName: traefik # Note: this is why it doesn't work. Traefik doesn't pick up this ingress for some reason. If I delete it, it works.
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-mmsd8
            port:
              number: 8089
        path: /.well-known/acme-challenge/8n6P9Ra5v_rSStcIrOYalquyhJoJR2tqzoNbUQRd5fk
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

**Comment by brandond** [comment]
> The ingress created by the clusterissuer has a spec called "ingressClassName" with the value of "traefik".

I suspect this is customizable, have you checked to see if you can disable this in order to use the default ingress class?

**Comment by domvo** [comment]
I did in fact find a workaround:
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-certificate
spec:
  acme:
    email: mail@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  kubernetes.io/ingress.class: traefik
```
If I do it like so it works. Apparently earlier cert-manager versions used to translate the `ingress.class` different compared to how it does now and traefik out of the box doesn't understand that it needs to pick up Ingress resources with `ingressClassName: traefik`.

Another workaround is to manually create an IngressClass Resource like so:
```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
```

Maybe the latter should be part of k3s?

**Comment by brandond** [comment]
> Maybe the latter should be part of k3s?

We use the upstream Traefik chart, if there is a version of the chart that includes this we could certainly update to it.

**Comment by domvo** [comment]
Alright, I will close this issue then. The breaking change in the cert-manager was made in v1.6.1, which was released on Nov 01. I hope this issue with the outlined workarounds can help some people in the future.
