### ISSUE TITLE
Nodes failing to join cluster with configuration error mismatch

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#4768]
**Environmental Info:**
K3s Version: 
v1.20.14-rc1+k3s1

Node(s) CPU architecture, OS, and Version: 
Any OS

Cluster Configuration:
HA Setup

**Describe the bug:**
On v1.20 HA is failing with configuration error mismatch
This issue is not seen in v1.21 or v1.22

**Steps To Reproduce:**
Create a multi node cluster with more than one server
Node1:
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.14-rc1+k3s1 sh -s - server --debug  --token <token> --cluster-init
```
Node2:
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.14-rc1+k3s1 sh -s - server --token <token> --server https://serveroneIP:6443 --debug
```

**Expected behavior:**
Add nodes should join the cluster

**Actual behavior:**
Second server node fails with configuration error mismatch

**Additional context / logs:**
```
Dec 16 22:55:41 ip-172-31-25-227 k3s[4976]: time="2021-12-16T22:55:41.643370539Z" level=debug msg="This is the server CriticalControlArgs: config.CriticalControlArgs{ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:\"cluster.local\", ClusterIPRange:(*net.IPNet)(0xc001846690), DisableCCM:false, DisableKubeProxy:false, DisableNPC:false, Disables:map[string]bool{}, FlannelBackend:\"vxlan\", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc0018466f0), Skips:map[string]bool{}}"
Dec 16 22:55:41 ip-172-31-25-227 k3s[4976]: time="2021-12-16T22:55:41.643421075Z" level=debug msg="This is the local CriticalControlArgs: config.CriticalControlArgs{ClusterDNS:net.IP{0xa, 0x2b, 0x0, 0xa}, ClusterDomain:\"cluster.local\", ClusterIPRange:(*net.IPNet)(0xc001478f30), DisableCCM:false, DisableKubeProxy:false, DisableNPC:false, Disables:map[string]bool{}, FlannelBackend:\"vxlan\", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc001478f60), Skips:map[string]bool{}}"
Dec 16 22:55:41 ip-172-31-25-227 k3s[4976]: time="2021-12-16T22:55:41.643480725Z" level=fatal msg="starting kubernetes: preparing server: Unable to join cluster due to critical configuration value mismatch"
Dec 16 22:55:41 ip-172-31-25-227 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 22:55:41 ip-172-31-25-227 systemd[1]: k3s.service: Failed with result 'exit-code'.
Dec 16 22:55:41 ip-172-31-25-227 systemd[1]: Failed to start Lightweight Kubernetes.
```

**Comment by thehejik** [comment]
I see similar problem also on RKE2 `v1.21.8-rc1+rke2r1` on s390x when joining a second master/server node (using `/etc/rancher/rke2/config.yaml` with `server:` and `token:`)
```
rke2 --debug server
WARN[0000] not running in CIS mode                      
DEBU[0000] Parsed control plane requests/limits: {KubeAPIServerCPURequest: KubeAPIServerCPULimit: KubeAPIServerMemoryRequest: KubeAPIServerMemoryLimit: KubeSchedulerCPURequest: KubeSchedulerCPULimit: KubeSchedulerMemoryRequest: KubeSchedulerMemoryLimit: KubeControllerManagerCPURequest: KubeControllerManagerCPULimit: KubeControllerManagerMemoryRequest: KubeControllerManagerMemoryLimit: KubeProxyCPURequest: KubeProxyCPULimit: KubeProxyMemoryRequest: KubeProxyMemoryLimit: EtcdCPURequest: EtcdCPULimit: EtcdMemoryRequest: EtcdMemoryLimit: CloudControllerManagerCPURequest: CloudControllerManagerCPULimit: CloudControllerManagerMemoryRequest: CloudControllerManagerMemoryLimit:} 
INFO[0000] Starting rke2 v1.21.8-rc1+rke2r1 (2cb118b28f818f2cd35445c0c2b4fb0d75256931) 
INFO[0000] Managed etcd cluster not yet initialized     
DEBU[0000] This is the server CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc00174e6c0)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc00174e6f0), DisableCCM:false, DisableHelmController:false, DisableKubeProxy:false, DisableNPC:true, Disables:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-kube-proxy":true, "rke2-multus":true, "servicelb":true}, DisableServiceLB:false, FlannelBackend:"none", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc00174e750), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc00174e780)}, Skips:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-kube-proxy":true, "rke2-multus":true, "servicelb":true}} 
DEBU[0000] This is the local CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc000a97d70)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc000a97d70), DisableCCM:false, DisableHelmController:false, DisableKubeProxy:false, DisableNPC:true, Disables:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-multus":true, "servicelb":true}, DisableServiceLB:false, FlannelBackend:"none", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc000a97da0), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc000a97da0)}, Skips:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-multus":true, "servicelb":true}} 
FATA[0000] starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch 
```

**Comment by manuelbuil** [comment]
> I see similar problem also on RKE2 `v1.21.8-rc1+rke2r1` on s390x when joining a second master/server node (using `/etc/rancher/rke2/config.yaml` with `server:` and `token:`)
> 
> ```
> rke2 --debug server
> WARN[0000] not running in CIS mode                      
> DEBU[0000] Parsed control plane requests/limits: {KubeAPIServerCPURequest: KubeAPIServerCPULimit: KubeAPIServerMemoryRequest: KubeAPIServerMemoryLimit: KubeSchedulerCPURequest: KubeSchedulerCPULimit: KubeSchedulerMemoryRequest: KubeSchedulerMemoryLimit: KubeControllerManagerCPURequest: KubeControllerManagerCPULimit: KubeControllerManagerMemoryRequest: KubeControllerManagerMemoryLimit: KubeProxyCPURequest: KubeProxyCPULimit: KubeProxyMemoryRequest: KubeProxyMemoryLimit: EtcdCPURequest: EtcdCPULimit: EtcdMemoryRequest: EtcdMemoryLimit: CloudControllerManagerCPURequest: CloudControllerManagerCPULimit: CloudControllerManagerMemoryRequest: CloudControllerManagerMemoryLimit:} 
> INFO[0000] Starting rke2 v1.21.8-rc1+rke2r1 (2cb118b28f818f2cd35445c0c2b4fb0d75256931) 
> INFO[0000] Managed etcd cluster not yet initialized     
> DEBU[0000] This is the server CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc00174e6c0)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc00174e6f0), DisableCCM:false, DisableHelmController:false, DisableKubeProxy:false, DisableNPC:true, Disables:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-kube-proxy":true, "rke2-multus":true, "servicelb":true}, DisableServiceLB:false, FlannelBackend:"none", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc00174e750), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc00174e780)}, Skips:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-kube-proxy":true, "rke2-multus":true, "servicelb":true}} 
> DEBU[0000] This is the local CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc000a97d70)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc000a97d70), DisableCCM:false, DisableHelmController:false, DisableKubeProxy:false, DisableNPC:true, Disables:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-multus":true, "servicelb":true}, DisableServiceLB:false, FlannelBackend:"none", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc000a97da0), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc000a97da0)}, Skips:map[string]bool{"coredns":true, "harvester-cloud-provider":true, "harvester-csi-driver":true, "rancher-vsphere-cpi":true, "rancher-vsphere-csi":true, "rke2-calico":true, "rke2-calico-crd":true, "rke2-cilium":true, "rke2-cilium-crd":true, "rke2-multus":true, "servicelb":true}} 
> FATA[0000] starting kubernetes: preparing server: unable to join cluster due to critical configuration value mismatch 
> ```
> 
> Edit: I was able add a worker/agent node successfully.

How did you deploy the first master and the second one?

**Comment by manuelbuil** [comment]
Maybe it makes sense to force all involved IPs to have the 16 byte representation.... that way we will avoid any issue

**Comment by thehejik** [comment]
> How did you deploy the first master and the second one?

More less standard deployment procedure:
first master:
```
$ curl -sL https://raw.githubusercontent.com/rancher/rke2/v1.21.8-rc1%2Brke2r1/install.sh | INSTALL_RKE2_VERSION="v1.21.8-rc1+rke2r1" INSTALL_RKE2_TYPE=server sh -
$ systemctl enable --now rke2-server
```
Second master with the same command but with `/etc/rancher/rke2/config.yaml` containing `server: <uri>` and `token: <token>`

**Comment by rancher-max** [comment]
This was validated as part of v1.20 release process and is working in v1.20.14+k3s1
