### ISSUE TITLE
overlayfs: not supported as upperdir

### ISSUE THREAD

**Issue by u0u0** [k3s-io/k3s#4769]
I just install k3s by install script   `curl -sfL https://get.k3s.io | sh -`
The OS is SONiC run on qemu, [SONiC-on-virtual-machine-for-Windows](https://github.com/Azure/SONiC/wiki/SONiC-on-virtual-machine-for-Windows).
but it fail to start after installed
```
overlayfs: filesystem on '/var/lib/rancher/k3s/agent/containerd/multiple-lowerdur-check214524349/upper' not supported as upperdir
then systemd[1]: Failed to start Journal Service. 
```

**Environmental Info:**
K3s Version: 
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
`Linux sonic 5.10.0-8-2-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`

**Comment by brandond** [comment]
Looks like that OS sets up the an overlayfs somewhere in the path above /var/lib/rancher/k3s. This isn't going to work with containerd. You'll need to either mount a normal ext4/xfs filesystem for /var/lib/rancher/k3s, or use the --data-dir option to move k3s's runtime files to a normal filesystem mounted elsewhere.

**Comment by u0u0** [comment]
SONiC hava default docker installed,  i solve the problem by add param "--docker" to install command line.
