### ISSUE TITLE
GitLab integration fails with error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by yangm97** [k3s-io/k3s#477]
- Install k3s using the script from k3s.io
- Set up Gitlab integration as per https://gitlab.com/help/user/project/clusters/index.md

```
==> /var/log/gitlab/gitlab-rails/kubernetes.log <==
{"severity":"ERROR","time":"2019-05-14T18:05:07.665Z","correlation_id":"fZjt5GwDph4","error_code":null,"service":"Clusters::Applications::InstallService","app_id":1,"project_ids":[],"group_ids":[9],"exception":"Kubeclient::HttpError","message":"SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)","backtrace":["lib/gitlab/kubernetes/kube_client.rb:34:in `get_namespace'","lib/gitlab/kubernetes/namespace.rb:14:in `exists?'","lib/gitlab/kubernetes/namespace.rb:26:in `ensure_exists!'","lib/gitlab/kubernetes/helm/api.rb:13:in `install'","app/services/clusters/applications/install_service.rb:10:in `execute'","app/workers/cluster_install_app_worker.rb:10:in `block in perform'","app/workers/concerns/cluster_applications.rb:8:in `find_application'","app/workers/cluster_install_app_worker.rb:9:in `perform'","lib/gitlab/sidekiq_status/server_middleware.rb:7:in `call'","lib/gitlab/sidekiq_middleware/correlation_logger.rb:10:in `block in call'","lib/gitlab/correlation_id.rb:15:in `use_id'","lib/gitlab/sidekiq_middleware/correlation_logger.rb:9:in `call'","lib/gitlab/sidekiq_middleware/batch_loader.rb:7:in `call'","lib/gitlab/sidekiq_middleware/request_store_middleware.rb:8:in `call'","lib/gitlab/sidekiq_middleware/memory_killer.rb:18:in `call'"]}
```

**Comment by kingdevnl** [comment]
Yep same issue here @yangm97 
Weird enough iv'e had a few different errors after trying to set it up again

**Comment by JaanTaponen** [comment]
same issue right here!

**Comment by alex37529** [comment]
I have similar error 
`{"severity":"ERROR","time":"2019-07-03T18:48:16.743Z","correlation_id":"swuWil1xyx4","exception":"Kubeclient::HttpError","status_code":null,"namespace":"gitlab-managed-apps","class_name":"Gitlab::Kubernetes::Namespace","event":"failed_to_create_namespace","message":"SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)"}`

**Comment by jusplayin** [comment]
+1

**Comment by kingdevnl** [comment]
I think this is related to https://gitlab.com/gitlab-org/gitlab-ce/issues/45939#note_193183530

**Comment by jusplayin** [comment]
I think using the `--tls-san` k3s install option with your k3s external IP may do the trick

**Comment by kingdevnl** [comment]
@jusplayin Have you tested it yet?

**Comment by jusplayin** [comment]
@kingdevnl Yes

**Comment by kingdevnl** [comment]
@jusplayin Did helm tiller install fine?

**Comment by jusplayin** [comment]
@kingdevnl It appears so as i'm able to install ingress, cert manager, prometheus and my deployments

Note that ingress did not obtain an IP by itself, was stuck at pending. I patched the resource with an IP and it seems to work

**Comment by lucifer1004** [comment]
@jusplayin Could you please explain in detail how you `patched the resource with an IP`? Thanks.

**Comment by jusplayin** [comment]
Found a question on stackoverflow and applied the solution to the Gitlab installed ingress:

```
# Fix pending IP for ingress (https://stackoverflow.com/questions/44110876/kubernetes-service-external-ip-pending)
kubectl patch service/ingress-nginx-ingress-controller -n gitlab-managed-apps -p '{"spec": {"type": "LoadBalancer", "externalIPs":["192.168.0.46"]}}'
```
Note that this is a different IP than traefik is using (Currently have 2 'LoadBalancer's):

```
gitlab-managed-apps         service/ingress-nginx-ingress-controller         LoadBalancer   10.43.141.135   192.168.0.46   80:30041/TCP,443:32360/TCP   7d3h
kube-system                 service/traefik                                  LoadBalancer   10.43.6.55      192.168.0.77   80:30093/TCP,443:32636/TCP   7d3h
```
This can probably be cleaned up a bit better. Maybe have Gitlab make use of traefik or not install traefik and just use gitlab-managed ingress. I thinking about checking out metallb as well.
