### ISSUE TITLE
[k3s-engine] rke2 servers not able to join the ha cluster

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4773]
**Environmental Info:**
K3s Version: v1.20, v.1.21, v1.22, engine

Cluster Configuration:

2 servers

**Describe the bug:**

New servers can't join the rke2 ha cluster because their config is different from the initial server node. This is because we are adding rke2-kube-proxy to the Disable slice in rke2 automatically

**Expected behavior:**

rke2 servers are able to join the cluster

**Actual behavior:**

rke2 servers can't join the cluster

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
Confirmed that in all of v1.22.5-rc2+rke2r1, v1.21.8-rc2+rke2r1, and v1.20.14-rc2+rke2r1 rke2 is able to join server nodes in HA clusters.
