### ISSUE TITLE
Update bootstrap logic to print out all changed files on disk

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#4797]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

Scenario 1:

1. Create a new cluster and change `client-ca.crt`.
2. Restart k3s and verify that k3s halts with a fatal log message that includes the file changed.

Scenario 2:

1. If using the same cluster, change the contents of `client-ca.key`. If using a new cluster, repeat step 1 from the scenario above.
2. Restart k3s and verify that both files are listed as changed in the fatal log message.

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [x] Needs backporting to older releases

**Comment by VestigeJ** [comment]
[Validated Engine v1.21.8](https://github.com/k3s-io/k3s/issues/4806#issuecomment-1004385150)

[Validated Release v1.22.5](https://github.com/k3s-io/k3s/issues/4805#issuecomment-1004378840)

[Validated Release v1.21.8](https://github.com/k3s-io/k3s/issues/4804#issuecomment-1004314643)
