### ISSUE TITLE
Cannot enable Node Authorization via --kube-apiserver-arg

### ISSUE THREAD

**Issue by nrvale0** [k3s-io/k3s#482]
**Describe the bug**
Passing ```--kube-apiserver-arg authorization-mode=Node,RBAC``` per the k8s docs does not enable Node Authorization.

**To Reproduce**
```
$ grep ExecStart /etc/system.d/system/k3s.service
ExecStart=/usr/local/bin/k3s server --bind-address 10.20.1.5 --node-ip 10.20.1.5 --flannel-iface enp0s8 --kube-apiserver-arg authorization-mode=Node,RBAC
```

```
$ k3s kubectl cluster-info dump | grep -i author ; echo $?
0
```

**Expected behavior**
Node Authz should enabled and cluster-info dump should show as much.

k3s logs do show that the parameter is being passed to the API server at startup:

```
# journalctl -u k3s.service | grep 'Node,'
May 15 23:20:19 k8scontrol0 k3s[8622]: time="2019-05-15T23:20:19.509958932Z" level=info msg="Running kube-apiserver --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --allow-privileged=true --bind-address=127.0.0.1 --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-issuer=k3s --advertise-address=127.0.0.1 --requestheader-username-headers=X-Remote-User --
watch-cache=false --tls-cert-file=/var/lib/rancher/k3s/server/tls/localhost.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/localhost.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --requestheader-extra-headers-prefix=X-Remote-Extra- --service-cluster-ip-range=10.43.0.0/16 --secure-port=6444 --kubelet-client-key=/va
r/lib/rancher/k3s/server/tls/token-node.key --requestheader-allowed-names=kubernetes-proxy --authorization-mode=Node,RBAC --advertise-port=6445 --insecure-port=0 --api-audiences=unknown --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-
group-headers=X-Remote-Group --enable-admission-plugins=NodeRestriction --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/token-node-1.crt" 
```

**Comment by vincentmli** [comment]
maybe add quote ? --kube-apiserver-arg "authorization-mode=Node,RBAC"

**Comment by erikwilson** [comment]
The default is already Node,RBAC. Are you trying to check for `authorization-mode` in cluster-info dump @nrvale0? Not sure that is the best way to verify.

**Comment by nrvale0** [comment]
@erikwilson I started reading through the code to see if any of the Node Auth stuff was set up out of the box but I never found the list of defaults. Perhaps you can point me to that code?

As to the check for Node Auth and RBAC, indeed, that's the grep of the cluster-info dump. According to the k8s docs and various folks I've asked, including on k8s Slack, that's the best way to check. I'm open to other methods though. Mostly I just need to test some of the Node Auth features.

**Comment by erikwilson** [comment]
The default is set here: https://github.com/rancher/k3s/blob/2d74e342973c56ff7100f6ef9e7612ea77866837/pkg/daemons/control/server.go#L170

I wasn't able to find any k8s documentation which suggested using cluster-info to verify that configuration (link appreciated), I have a feeling it would only show up if kube-apiserver is running in a pod. (also see [here](https://stackoverflow.com/questions/51238988/how-to-check-whether-rbac-is-enabled-using-kubectl) for people having issues using cluster-info to check for rbac)

The only site I have found with good info for verifying node authorization as working is https://acotten.com/post/kube17-security.

Even tho this feature is "enabled" on the api-server by default it needs PR #359 to actually use node x509 certs with `system:node` credentials.

Out of curiosity, is there a specific issue you are running into?

**Comment by nrvale0** [comment]
@erikwilson None of the official docs mention 'kubectl cluster-info dump' as a way to validate Node Auth/RBAC directly. That suggestion comes from k8s Slack for the most part.

After looking at your links and comparing to the k8s docs it's not clear to me that Node Auth is not enabled; it seems more like the docs are incomplete as to how to **configure it** after it is enabled and thus the API server logs I was seeing indicating Node Authz was not active. Thanks for those links. I'll leave this open until I can get a chance to really dig into them and the perhaps close this ticket if my above guess is correct.

Side question...why would 'cluster-info dump' care if the API server is running as a Pod?
