### ISSUE TITLE
External IP do not match ip address set with --node-external-ip flag

### ISSUE THREAD

**Issue by mohamedaminearous** [k3s-io/k3s#4828]
**Environmental Info:**
K3s Version: 
``` bash
k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 
``` bash
Linux k3s-master 5.4.0-88-generic #99-Ubuntu SMP *** x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
signle node (one server)

**Describe the bug:**
I'm installing k3s on ovh server with a private ip and a floating ip (static ip independent of the server itself).
This floating ip is public and its traffic is routed onto the private ip and they share the same network interface:
``` bash
k3s-master:~# ip add
.........
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UP group default qlen 1000
    link/ether **:**:**:**:**:** brd **:**:**:**:**:**
    inet $floating_ip/32 scope global ens3
       valid_lft forever preferred_lft forever
    inet $private_ip/24 brd ***.***.***.*** scope global dynamic ens3
       valid_lft 82693sec preferred_lft 82693sec
    inet6 ****::****:****:****:****/64 scope link 
       valid_lft forever preferred_lft forever
```
When I install k3s without ip flags, k3s select the flaoting ip as the internal ip and do not select any external ip.
So, I set these ips with `--node-ip $private_ip` and `--node-external-ip $floating_ip` flags.
K3s, then, set the private ip as internal ip but nothing for the external ip. (as shown in the current behavior)
Is there any solution for this bug ? and is there any relation between setting external ip and `ccm` (Cloud Control Manager) ?

**Steps To Reproduce:**
``` bash
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=$k3s_channel K3S_TOKEN=$k3s_token sh -s - \
    --flannel-backend=host-gw \
    --disable local-storage \
    --disable-cloud-controller \
    --disable traefik \
    --disable servicelb \
    --data-dir $k3s_data_folder \
    --default-local-storage-path $volume_mount_point/local_storage \
    --write-kubeconfig $volume_mount_point/k3s.yaml \
    --node-external-ip $floating_ip \
    --node-ip $private_ip \
    --kubelet-arg 'cloud-provider=external'
```
- Installed K3s: 

**Expected behavior:**
``` bash
k3s-master:~# kubectl get nodes -o wide
NAME         STATUS   ROLES                  AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k3s-master   Ready    control-plane,master   12h   v1.22.5+k3s1   $private_ip     $floating_ip   Ubuntu 20.04.3 LTS   5.4.0-88-generic   containerd://1.5.8-k3s1
```

**Actual behavior:**
``` bash
k3s-master:~# kubectl get nodes -o wide
NAME         STATUS   ROLES                  AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k3s-master   Ready    control-plane,master   12h   v1.22.5+k3s1   $private_ip      <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   containerd://1.5.8-k3s1
```

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
You have disabled the embedded cloud controller with `--disable-cloud-controller`, and this is whats responsible for setting the node external IP. Unless you're deploying an OVH-specific cloud controller, you should leave the k3s embedded cloud controller enabled.

**Comment by mohamedamine93** [comment]
Thanks, I will install the CCM of ovh. 
I installed k3s also on hetzner server and I installed there CCM but instead of getting the floating ip as external ip (as I set the external ip flag to the floating ip), it set another public ip as the external ip (this public ip share the same network interface with the floating ip).
Can it be a ccm or a k3s bug ?

**Comment by brandond** [comment]
The K3s embedded cloud controller will set the external IP to whatever you set --node-external-ip to; nothing else.

**Comment by mohamedamine93** [comment]
Thanks again
