### ISSUE TITLE
HA Cluster stuck and unable to start after enabling secrets encryption

### ISSUE THREAD

**Issue by ssmall** [k3s-io/k3s#4838]
### K3s Version: 

k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10

### Node(s) CPU architecture, OS, and Version: 

Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### Cluster Configuration:

3 servers (referred to here as **S1**, **S2**, and **S3**) and 3 agents

## Describe the bug:

Server was already running with HA configuration and no issues. I followed https://rancher.com/docs/k3s/latest/en/security/secrets_encryption/ to attempt to enable secrets configuration on the cluster. Upon restarting them, **S2** and **S3** failed to start k3s and showed the following log:

```
time="2021-12-23T23:20:37-08:00" level=fatal msg="/var/lib/rancher/k3s/server/cred/encryption-state.json newer than datastore and could cause cluster outage. Remove the file from disk and restart to be recreated from datastore."
```

So I followed the recommendation to remove `/var/lib/rancher/k3s/server/cred/encryption-state.json`, and now **S2** and **S3** fail to start with:

```
time="2021-12-24T00:07:44-08:00" level=fatal msg="stat /var/lib/rancher/k3s/server/cred/encryption-state.json: no such file or directory"
 ```
Meanwhile, on **S1**, `systemctl status k3s.service` shows `activating` as it waits for the other master nodes to restart.

### Initial configuration
Before making any changes, `ExecStart` of `/etc/systemd/system/k3s.service` on **S1** (local IP: 192.168.1.33) looked like:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--server' \
        'https://192.168.1.31:6443' \
        '--disable' \
        'servicelb,traefik'
```

On **S2** (local IP: 192.168.1.31), it looked like:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--cluster-init' \
        '--disable' \
        'servicelb,traefik'
```

On **S3** (local IP: 192.168.1.62), it looked like:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--server' \
        'https://192.168.1.31:6443' \
        '--disable' \
        'servicelb,traefik'
```

### Steps:

1. On **S1**: Update `/etc/systemd/system/k3s.service` to add `'--secrets-encryption'` to args
2.  On **S1**: `systemctl restart k3s.service`
3. On **S1**:
```> k3s secrets-encrypt status 
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
 ```
3. On **S2** and **S3**:  Update `/etc/systemd/system/k3s.service` to add `'--secrets-encryption'` to args
4. On **S2** and **S3**: `systemctl restart k3s.service`

## Expected behavior:

**S2** and **S3** come back up cleanly, secret encryption is enabled on the cluster

## Actual behavior:

**S2** and **S3** fail to start with

```
time="2021-12-23T23:20:37-08:00" level=fatal msg="/var/lib/rancher/k3s/server/cred/encryption-state.json newer than datastore and could cause cluster outage. Remove the file from disk and restart to be recreated from datastore."
```

After deleting `/var/lib/rancher/k3s/server/cred/encryption-state.json`, **S2** and **S3** fail to start with 

```
time="2021-12-24T00:07:44-08:00" level=fatal msg="stat /var/lib/rancher/k3s/server/cred/encryption-state.json: no such file or directory"
 ```

**S1** is stuck in activating state.

## Backporting

- [ ] Needs backporting to older releases

**Comment by ssmall** [comment]
I was able to get the nodes to start back up again successfully by manually copying  `/var/lib/rancher/k3s/server/cred/encryption-state.json` from **S1** to **S2** and **S3**

**Comment by brandond** [comment]
I'm not sure that we've tested adding that flag to an existing cluster after the fact.

cc @dereknola

**Comment by dereknola** [comment]
We have not tested that, and it isn't supported AFAIK. Something for next month's release :)

**Comment by ssmall** [comment]
I was able to get my cluster back up and running, thankfully. Currently I see the following:

```
k3s secrets-encrypt status                                                                                                                                                                                       
Encryption Status: Enabled
Current Rotation Stage: reencrypt_active
Server Encryption Hashes: hash does not match between S1 and S2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
 ```

Given that you've said this is not supported, can you please advise on a way to safely turn secrets encryption back off without breaking the cluster again?

**Comment by dereknola** [comment]
There is already a line about not using it on existing clusters in a bolded NOTE box:
![image](https://user-images.githubusercontent.com/11727736/147986383-ab4a7ad6-9dd1-40d1-9eaa-52cbf40601e5.png)

To disable encryption you can follow the instructions here:
https://rancher.com/docs/k3s/latest/en/security/secrets_encryption/#single-server-secrets-encryption-disable-enable

**Comment by dereknola** [comment]
I have posted a Docs PR to add the same note in the HA section, not just the Single Node section.
https://github.com/rancher/docs/pull/3768
