### ISSUE TITLE
K3s server etcd snapshot failed

### ISSUE THREAD

**Issue by flo-mic** [k3s-io/k3s#4845]
**Environmental Info:**
K3s Version: k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: Linux Cloud-Server 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

Cluster Configuration: single node cluster

**Describe the bug:**
On a fresh isntalled k3s single node cluster the etcd snapshot is not working. First I tried to customize the cron timer but there was no backup generated. When I run the command `sudo k3s etcd-snapshot save` I get the below error message:

> FATA[0000] etcd database not found in /var/lib/rancher/k3s/server 

**Steps To Reproduce:**
1. Install k3s: `curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=10.100.0.0/16,fd00:0:0:100::/64 --service-cidr=10.99.0.0/16,fd00:0:0:99::/112  --disable-network-policy --disable=traefik,local-storage,servicelb" sh -
`
2. Run snapshot: `sudo k3s etcd-snapshot save`

**Expected behavior:**
The snapshot should be created without any issues

**Additional context / logs:**
If I browse the k3s folder structure I can see that the db folder is in `/var/lib/rancher/k3s/server/db` and not `/var/lib/rancher/k3s`
The folder structure in `/var/lib/rancher/k3s` looks like this

>root@Cloud-Server:/var/lib/rancher/k3s# ls -la
total 20
drwxr-xr-x 5 root root 4096 Dez 27 13:38 .
drwxr-xr-x 3 root root 4096 Dez 27 13:38 ..
drwx------ 5 root root 4096 Dez 27 13:38 agent
drwxr-xr-x 3 root root 4096 Dez 27 13:38 data
drwx------ 7 root root 4096 Dez 28 15:41 server

**Comment by brandond** [comment]
You didn't start the k3s server with --cluster-init as documented at https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/ so the error message is correct - you do not have an etcd database to snapshot.

**Comment by flo-mic** [comment]
@brandond thanks that solved it

**Comment by galenwarren** [comment]
In case anyone else lands here, this error also happens if you don't run the snapshot command as root. Sudo fixed it for me.
