### ISSUE TITLE
tag validate has something wrong in version.sh when build from source

### ISSUE THREAD

**Issue by yanggeorge** [k3s-io/k3s#4851]
**Environmental Info:**
K3s Version: v1.18.9+k3s1 (may be occur in other tag version when building )

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**
[stackoverflow question](https://stackoverflow.com/questions/70502525/fail-to-build-k3s-from-source-on-tag-v1-18-9k3s1)

I clone k3s source from https://github.com/k3s-io/k3s.git, and want to build version=v1.18.9+k3s1. but I get error as bellow

`Tagged version 'v1.18.10+k3s1' does not match expected version 'v1.18.9[+-]*' `

**Steps To Reproduce:**

```
git clone https://github.com/k3s-io/k3s.git
cd k3s
git checkout v1.18.9+k3s1
make
```

**Expected behavior:**

no error info

**Actual behavior:**

report error info `Tagged version 'v1.18.10+k3s1' does not match expected version 'v1.18.9[+-]*' ` and fail to build

**Advice**
As I have asked [stackoverflow question](https://stackoverflow.com/questions/70502525/fail-to-build-k3s-from-source-on-tag-v1-18-9k3s1),  if modify one line code in `./scripts/version.sh` from `GIT_TAG=$(git tag -l --contains HEAD | head -n 1)` to `GIT_TAG=$(git describe --contains HEAD | head -n 1)`,  it succeed to build.

**Comment by brandond** [comment]
We don't usually (if ever) rebuild old releases, so this is probably something that we haven't run into. You could try running `SKIP_VALIDATE=true make` which should skip the unnecessary checks.

**Comment by yanggeorge** [comment]
thank you
