### ISSUE TITLE
k3s-uninstall.sh does not respect btrfs snapshotter

### ISSUE THREAD

**Issue by cy8aer** [k3s-io/k3s#4852]
**Environmental Info:**
K3s Version: v1.23.1-rc1+k3s1

Node(s) CPU architecture, OS, and Version: 

* Debian bookworm
* 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18)
* btrfs filesystem

Cluster Configuration:

single node

**Describe the bug:**

I just tried to install k3s with `--snapshotter btrfs`. This works great with the actual rc. But `k3s-uninstall.sh` does not remove the btrfs snapshots.

**Steps To Reproduce:**

- Installed K3s: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.1-rc1+k3s1 sh -s  --snapshotter btrfs
```
* Install k3s
* `/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.btrfs/snapshots/` fills up with snapshots
* sudo k3s-uninstall.sh

* Install k3s again

**Expected behavior:**

Kube-Nodes start up until Running

**Actual behavior:**

Install fails: container pulling does not work because the snapshots to be pulled are already existing.

After `k3s-uninstall.sh` the btrfs directories/subvolumes are still existing. An

```
btrfs subvolume remove /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.btrfs/snapshots/*
rm -rf /var/lib/rancher
```
would do the job right. But this is not done by `k3s-uninstall.sh`

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
cc @dweomer - you up for adding btrfs snapshot cleanup?
