### ISSUE TITLE
cadvisor stops reporting metrics after few seconds

### ISSUE THREAD

**Issue by daniellavoie** [k3s-io/k3s#4853]
**Environmental Info:**
K3s Version: 
```
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux k3os-32148 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 GNU/Linux
```

Cluster Configuration: 

```
1 server
```

**Describe the bug:**
cadvisor metrics will stop reporting `container_*` after few minutes. `container_scrape_error` will report to `1`. When this occurs, the following error is observed in k3s: `Partial failure issuing cadvisor.ContainerInfoV2`.

Rebooting the node fixes things for a few seconds until the error appears again.

What would be helpful for further troubleshooting this problem is to be referenced with documentation that highlights under which condition `cadvisor_scrape_error` gets flagged to `0`. All I'm seing in the logs are partial errors.

**Steps To Reproduce:**
- Installed K3s with K3OS `v0.21.5-k3s2r1` (reproduced on the same hardware with ubuntu using standard latest k3s install script)
- Deployed a few containers
- Monitored the cadvisor metrics with `kubectl get --raw /api/v1/nodes/k3os-32148/proxy/metrics/cadvisor`

**Expected behavior:**
Expecting `container_scrape_error` to report `0` and the `container_*` to be continuously reported:
```
kubectl get --raw /api/v1/nodes/k3os-32148/proxy/metrics/cadvisor
...
# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="",cadvisorVersion="",dockerVersion="Unknown",kernelVersion="5.4.0-88-generic",osVersion="k3OS v0.21.5-k3s2r1"} 1
# HELP container_blkio_device_usage_total Blkio Device bytes usage
# TYPE container_blkio_device_usage_total counter
container_blkio_device_usage_total{container="",device="",id="/",image="",major="7",minor="0",name="",namespace="",operation="Async",pod=""} 0 1640889963346
...
```

**Actual behavior:**
Only the following metrics gets reported:
[Actual metrics](https://github.com/k3s-io/k3s/files/7794554/actual-cadvisor-metrics.log)

**Additional context / logs:**

```
W1230 18:30:37.821160    3077 container.go:586] Failed to update stats for container "/kubepods/besteffort/pod094c416f-d396-4cc3-bd43-c0cd191fc1eb": /sys/fs/cgroup/cpuset/kubepods/besteffort/pod094c416f-d396-4cc3-bd43-c0cd191fc1eb/cpuset.mems found to be empty, continuing to push stats
...
E1230 18:30:41.512106    3077 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods/besteffort/pod094c416f-d396-4cc3-bd43-c0cd191fc1eb\": RecentStats: unable to find data in memory cache]"

```
[Complete k3s-service.log](https://github.com/k3s-io/k3s/files/7794521/k3s-service.log)
[Expected metrics](https://github.com/k3s-io/k3s/files/7794553/cadvisor-metrics.log)

**Backporting**
- [ ] Needs backporting to older releases

**Comment by daniellavoie** [comment]
I've continued my investigation. I'm running cadvisor standalone with a dedicated helm chart (https://artifacthub.io/packages/helm/ckotzbauer/cadvisor) and the standalone cadvisor process never fails to report the `container_*` metrics.

**Comment by brandond** [comment]
Cadvisor is built in to the kubelet, we don't package our own. It's just whatever comes with the version of Kubernetes you're using. You might check for issues upstream.

**Comment by daniellavoie** [comment]
Indeed, I'm going through the dependency list and my understanding is that I'm impacted by [https://github.com/google/cadvisor/pull/2868](#2868). I'm running concourse inside the k3s cluster and it runs a lot of short lived containers. Cache miss would cause the the container metrics gatherer to stop on the error and not move.

v0.40.0 of cadvisor seems to fix the issue. I'm trying to figure out which version of kubelet is used by k3s and consequently which cadvisor version it embedds.

**Comment by daniellavoie** [comment]
Sounds like I'm on the right track: https://github.com/kubernetes/kubernetes/blob/v1.21.5/go.sum

```
github.com/google/cadvisor v0.39.0 h1:jai6dmBP9QAYluNGqU18yVUTw6uuyAW0AqtZIjvl8Qg=
github.com/google/cadvisor v0.39.0/go.mod h1:rjQFmK4jPCpxeUdLq9bYhNFFsjgGOtpnDmDeap0+nsw=
```

So far everything is starting to making sense! Only k8s 1.23.x ships with a cadvisor > than `v0.40.0`. What kind of timeline are we looking into for k3s to support `1.23.x`?

**Comment by daniellavoie** [comment]
Just found out the `v1.23.1-rc1+k3s1` tag, will give it a try.

**Comment by brandond** [comment]
Generally we follow upstream with regards to kubelet / cadvisor version pairings; we'll have to see if upstream bumps cadvisor in older branches for their next release cycle.

**Comment by daniellavoie** [comment]
I've submitted a backport [#3038](google/cadvisor/pull/3038) on `v0.39.x` for cadvisor. Bumping older branches of kubernetes to >= `v0.40.x` seems to have a lot of side effects.
