### ISSUE TITLE
Failed to connect to github.com port 443: not behind a proxy

### ISSUE THREAD

**Issue by the-iron-pig** [k3s-io/k3s#4855]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Can you provide any information on what you're trying to do, how you're trying to do it, and what the results are?

**Comment by the-iron-pig** [comment]
Trying to download and install via the curl command on a raspberry pi 4 that's the air that I'm getting

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by brandond** [comment]
Sounds like the node doesn't have access to GitHub? What do you get if you curl GitHub from a shell?

**Comment by the-iron-pig** [comment]
Failed to connect to github.com port 443 network unreachable. That is the error I get, although network connectivity is fine, I can ping google etc and browse web. Using Pi4 with most updated bullseye, not behind a proxy of any kind.

Be Well,
https://the-iron-pig.github.io/

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
