### ISSUE TITLE
Executing K3s from Docker stucks on Failed to get CA certs

### ISSUE THREAD

**Issue by jonathanvila** [k3s-io/k3s#4863]
**Environmental Info:**
K3s Version:  latest

k3s version v1.20.14+k3s1 (6149cba2)
go version go1.15.15

Node(s) CPU architecture, OS, and Version: 

Linux pc-136.home 5.15.10-200.fc35.x86_64 #1 SMP Fri Dec 17 14:46:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

**Describe the bug:**

I execute K3s using the docker image with : 
docker run --tmpfs /run --tmpfs /var/run -e K3S_URL=https://mycluster:6443 -e K3S_TOKEN=mynodetoken --privileged  rancher/k3s

It gets stuck showing 
time="2022-01-04T10:37:53.698311411Z" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:42803/cacerts\": read tcp 127.0.0.1:52318->127.0.0.1:42803: read: connection reset by peer"

**Steps To Reproduce:**

- Installed K3s: docker run --tmpfs /run --tmpfs /var/run -e K3S_URL=https://mycluster:6443 -e K3S_TOKEN=mynodetoken --privileged rancher/k3s

**Expected behavior:**

K3s starting fine

**Actual behavior:**

Error with failed to get CA certs
If I try to to open https://mycluster:6443/cacerts or using localhost or 127.0.0.1 , or using the port 42803 as shown in the log, nothing is not working

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
What is the server `mycluster`?  Is that an actual host on your network, another Docker container, etc?

**Comment by jonathanvila** [comment]
@brandond nop, it's a totally made up name..... I've assumed that this is the name my cluster will be published , the similar way as other K8s distros ( CRC e.g ) that create a name : api-crc-testing:6443

**Comment by jonathanvila** [comment]
@brandond ups, my fault on the copy-paste , I will fix the command in the description.

**Comment by brandond** [comment]
No... that's the URL of a server that the agent will attempt to join. The environment variable is equivalent to setting the --server CLI flag. If you don't have an existing server/cluster to join, you shouldn't set it.

**Comment by jonathanvila** [comment]
But if I dont set it then it complains that the --server is mandatory

**Comment by brandond** [comment]
Correct, because the rancher/k3s image defaults to running an agent if not otherwise configured, and agents require both a server and a token when connecting to a server.

Did you want to run:
```bash
docker run --tmpfs /run --tmpfs /var/run -e K3S_TOKEN=mynodetoken --privileged rancher/k3s server
```

**Comment by jonathanvila** [comment]
Ohhhhh that "server" made a real difference :+1: 

But now I have several errors : https://gist.github.com/jonathanvila/b1a5583f8e98aed0b161a4de1451e6c0

**Comment by brandond** [comment]
`F0104 17:47:52.424230      22 kubelet.go:1367] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 35 in cached partitions map`

This is a crash somewhere in the core Kubelet code. I can't reproduce this locally when running the same command as you, but I suspect it has something to do with the tmpfs volumes you're mounting in the container. Why are you doing that?

**Comment by jonathanvila** [comment]
Same command with a colleague in Mac and another Linux distro and it worked fine.

I'm trying to reproduce this : https://github.com/testcontainers/testcontainers-java/pull/4582/files#diff-0a74318afacc2d638c24ac87f1642eed4f15510d1f3ea60e40fd438ce5595f8aR17

**Comment by brandond** [comment]
A bit of light googling suggests that it could also be related to the node filesystem... are you by any chance using btrfs subvolumes? I've seen the kubelet have a hard time with that.

**Comment by jonathanvila** [comment]
docker run --expose=6443 --expose=8443  --name k3s2 -e K3S_TOKEN=mynodetoken --privileged rancher/k3s server

Same errors inside the container.... 

Regarding the volumes : 
![image](https://user-images.githubusercontent.com/1836434/148104668-cb2bd52c-dd8e-43ab-875a-1ae09a6976fe.png)

**Comment by brandond** [comment]
So yeah, btrfs subvolumes. Looks like you're also using the docker btrfs snapshotter. I don't think that's handled properly by the kubelet when running inside a container. You may need to stick with something that uses ext4/xfs, at least for /var/lib/docker.

**Comment by jonathanvila** [comment]
yep apparently not :( 

```
docker run --expose=6443 --expose=8443  --name k3s5 -e K3S_TOKEN=mynodetoken -e K3S_SNAPSHOTTER=btrfs --privileged rancher/k3s:v1.23.1-rc1-k3s1 server 
```
log
```
...........
I0104 18:53:25.348429      57 reconciler.go:295] "Volume detached for volume \"content\" (UniqueName: \"kubernetes.io/configmap/93f8ef66-df68-4e82-92c7-9afe330d23e0-content\") on node \"d46a82a77513\" DevicePath \"\""
I0104 18:53:25.348455      57 reconciler.go:295] "Volume detached for volume \"kube-api-access-p7828\" (UniqueName: \"kubernetes.io/projected/93f8ef66-df68-4e82-92c7-9afe330d23e0-kube-api-access-p7828\") on node \"d46a82a77513\" DevicePath \"\""
I0104 18:53:25.348463      57 reconciler.go:295] "Volume detached for volume \"values\" (UniqueName: \"kubernetes.io/configmap/93f8ef66-df68-4e82-92c7-9afe330d23e0-values\") on node \"d46a82a77513\" DevicePath \"\""
W0104 18:53:34.047150      57 fs.go:599] Unable to get btrfs mountpoint IDs: stat failed on /dev/mapper/luks-a1f97aea-fa42-4a22-bbdd-1f5b86f16eb3 with error: no such file or directory
W0104 18:53:34.047354      57 fs.go:599] Unable to get btrfs mountpoint IDs: stat failed on /dev/mapper/luks-a1f97aea-fa42-4a22-bbdd-1f5b86f16eb3 with error: no such file or directory
W0104 18:53:34.047376      57 fs.go:599] Unable to get btrfs mountpoint IDs: stat failed on /dev/mapper/luks-a1f97aea-fa42-4a22-bbdd-1f5b86f16eb3 with error: no such file or directory
W0104 18:53:34.053156      57 fs.go:599] Unable to get btrfs mountpoint IDs: stat failed on /dev/mapper/luks-a1f97aea-fa42-4a22-bbdd-1f5b86f16eb3 with error: no such file or directory
```

**Comment by brandond** [comment]
Probably because /dev in the container is not the same as /dev on the host? Most of the big Kubernetes providers (Google, Amazon, VMware, MS, etc) just use ext4 or xfs for their cluster distros, so you will in general find btrfs to be not very well supported by the project.
