### ISSUE TITLE
overwritten of k3s.yaml file after implementing RBAC(after reboot of master node)

### ISSUE THREAD

**Issue by Nishant27Saini** [k3s-io/k3s#4869]
**Environmental Info:**
K3s Version: v1.22.5+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux xxx 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node cluster

**Describe the bug:**
I have launched one single-node k3s cluster for some testing,  I did some changes and applied RBAC in k3s by taking the help of Certificate Authority placed in /var/lib/rancher/k3s/server/tls location and all my changes were saved  successfully in /etc/rancher/k3s/k3s.yaml file and my setup was working fine. But when i rebooted the system, all the changes(i.e addition of user-contexts for RBAC) that I done in /etc/rancher/k3s/k3s.yaml file were undone and /etc/rancher/k3s/k3s.yaml file was changed to its default file(the file which comes after fresh installation of k3s.

**Steps To Reproduce:**
Installed k3s by curl -sfL https://get.k3s.io | sh -
    cd /var/lib/rancher/k3s/server/tls

Step 1: Creation of key:
            openssl genrsa -out john.key 2048
Step 2: Creation of Certificate from key:
          openssl req -new -key john.key -out john.csr -subj "/CN=john/O=group1"

Step 3: Creation of Certificate Signing request

cat <<EOF | kubectl apply -f -
 apiVersion: certificates.k8s.io/v1
 kind: CertificateSigningRequest
 metadata:
   name: john
 spec:
   groups:
   - system:authenticated
   request: $(cat john.csr | base64 | tr -d '\n')
   signerName: kubernetes.io/kube-apiserver-client
   usages:
   - client auth
 EOF

Step 4: Signing of Certificate

  kubectl certificate approve john

Step 5:  Getting signed certificate
    kubectl get csr john -o jsonpath='{.status.certificate}'  | base64 -d > john.crt

Step 6: Created role.yml file

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: john-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  -
Step 7: Applying role.yml file 

    kubectl apply -f role.yml

Step 8: Creating rolebinding.yml file

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: john-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: john-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: john

Step 9: Applying rolebinding.yml file
 
   kubectl apply -f rolebinding.yml

Step 10:  
kubectl config set-credentials john --client-key=john.key --client-certificate=john.crt --embed-certs=true

Step 11: Setted context 
kubectl config set-context john --cluster=default --user=john

Step 12: Shifted to newly created context
 kubectl config use-context john

Step 13: Checked my current context
  kubectl config current-context

Now, if I do "cat /etc/rancher/k3s/k3s.yaml", all my changes i.e addition of newly created contexts are saved in this file.

But, if I reboot/restart the system all the newly created contexts(like john context added by me) will be deleted and /etc/rancher/k3s/k3s.yaml will be changed to its default file which was present during fresh installation of k3s.

- Installed K3s: 

**Expected behavior:**
Changes done in /etc/rancher/k3s/k3s.yaml after installation of k3s should be permanent/persistent even if master node restarts.

**Actual behavior:**
After installation of k3s, if we do some changes in /etc/rancher/k3s/k3s.yaml, all these changes will be undone if we restart the node.

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
That is correct. The admin kubeconfig at /etc/rancher/k3s/k3s.yaml is rewritten every time k3s starts, by design.

If you want to modify this file, copy it somewhere else (`$HOME/.kube/config` is the traditional place to put user kubeconfigs) and modify that copy.

**Comment by Nishant27Saini** [comment]
Yes, I can copy the modified file to "$HOME/.kube/config" location, but in one node if we have two kubeconfig files (i.e at $HOME/.kube/config and at /etc/rancher/k3s/k3s.yaml),  then k3s by-default will read kubeconfig file from /etc/rancher/k3s/k3s.yaml. Is there any way that k3s will read kubeconfig file by-default from $HOME/.kube/config instead of  /etc/rancher/k3s/k3s.yaml, without passing --kubeconfig=$HOME/.kube/config in kubectl commands.

**Comment by brandond** [comment]
You can still `export KUBECONFIG=/path/to/file` ?
