### ISSUE TITLE
Update etcd to 3.5.1 due to upstream 'ancient' member issue

### ISSUE THREAD

**Issue by DanWard** [k3s-io/k3s#4870]
**Environmental Info:**
K3s Version: 
```
k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 
```
Linux kube01 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
NAME     STATUS   ROLES                       AGE     VERSION
kube01   Ready    control-plane,etcd,master   3d11h   v1.22.5+k3s1
kube02   Ready    control-plane,etcd,master   138d    v1.22.5+k3s1
kube03   Ready    control-plane,etcd,master   3d11h   v1.22.5+k3s1
```

**Describe the bug:**
Etcd members are resurrected on complete cluster reboot due to an upstream bug in the removal of the etcd members from both the v2 and v3 store.
In my case, I had 2 nodes that were replaced early on in the cluster whilst running 1.21 - this caused 2 additional etcd members to be reconstructed in 3.5.0.

**Steps To Reproduce:**
The upstream issue contains steps for reproduction: https://github.com/etcd-io/etcd/issues/13196

**Expected behavior:**
K3s should be able to handle a restart without etcd quorum failing on 3 members.

**Actual behavior:**
Etcd could not remove these 2 old members, as per the upstream issue.

**Additional context / logs:**
I rebuilt k3s with the new 3.5.1 bugfix release and the issue went away, I would rather not remain off of the official release train for too long.
As per some other investigations, I tried to set the snapshot to 2 to force the old data to be compacted. However this didn't work in my individual case. I also tried deleting the WAL to see if it would stop attempting to recreate the members list from the historical data, however this also didn't work. A full cluster rollback was required (VM restore), then replacement of the k3s binary with my patched version.

**Backporting**

- [x] Needs backporting to older releases
- [ ] 1.22.x

**Comment by brandond** [comment]
Running a --cluster-reset to knock the etcd cluster back down to 1 node, and then doing a stop / remove the datastore files / start on both of the other two servers should resolve it?

**Comment by DanWard** [comment]
Unfortunately not, the same errors occur as etcd reconstructs the member list in the startup phase before the removal commands execute. It causes the cluster-reset flag to loop on the removal of the ghost members as they don't exist in the v3 store.
Etcd errors with `member not found` on removal.

**Comment by mdrahman-suse** [comment]
Verified in k3s release 1.23 v1.23.2-rc1+k3s1 that the containerd and etcd versions are updated to v1.5.9 and v3.5.1

Performed cluster-reset after bringing the 2 nodes down (loosing the quorum) and then restarting the servers. All the servers joined the cluster successfully
