### ISSUE TITLE
k3s external apiserver certificates access failed

### ISSUE THREAD

**Issue by YchauWang** [k3s-io/k3s#4872]
**Environmental Info:**
K3s Version: 
k3s version v1.22.3+k3s-d4db2a77 (d4db2a77)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux node01 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 servers, 1 agents

**Describe the bug:**
When I try to use the follow command
```
curl --cacert /var/lib/rancher/k3s/server/tls/server-ca.crt \
  --cert /var/lib/rancher/k3s/server/tls/client-admin.crt \
  --key /var/lib/rancher/k3s/server/tls/client-admin.key \
  https://192.168.220.147:6443/api/v1/pods
```
access the apiserver of the k3s server, It always reported `curl: (58) unable to load client key: -8178 (SEC_ERROR_BAD_KEY)`.

**Expected behavior:**
Which certificates can I use to access the `https://externalIP:6443/api`? I want to use curl access k3s apiserver.

**Actual behavior:**
[root@node01 tls]# curl -vv --cacert /var/lib/rancher/k3s/server/tls/server-ca.crt \
>   --cert /var/lib/rancher/k3s/server/tls/client-admin.crt \
>   --key /var/lib/rancher/k3s/server/tls/client-admin.key \
>   https://192.168.220.147:6443/api/v1/pods
* About to connect() to 192.168.220.147 port 6443 (#0)
*   Trying 192.168.220.147...
* Connected to 192.168.220.147 (192.168.220.147) port 6443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /var/lib/rancher/k3s/server/tls/server-ca.crt
  CApath: none
* unable to load client key: -8178 (SEC_ERROR_BAD_KEY)
* NSS error -8178 (SEC_ERROR_BAD_KEY)
* Peer's public key is invalid.
* Closing connection 0
curl: (58) unable to load client key: -8178 (SEC_ERROR_BAD_KEY

**Comment by YchauWang** [comment]
I am a beginner for the k3s project. Could you give me some help @brandond?

**Comment by brandond** [comment]
It looks like the version of curl/openssl on your host doesn't support the key type that k3s uses. Is there some reason you can't use `kubectl get --raw`?

**Comment by YchauWang** [comment]
> It looks like the version of curl/openssl on your host doesn't support the key type that k3s uses. Is there some reason you can't use `kubectl get --raw`?

 `kubectl get --raw` can get pods list from the server. And I remove the client-admin.crt，It show like this:
```

[root@node01 tls]# curl -vv --cacert /var/lib/rancher/k3s/server/tls/server-ca.crt \
>     https://192.168.220.147:6443/api/v1/pods
* About to connect() to 192.168.220.147 port 6443 (#0)
*   Trying 192.168.220.147...
* Connected to 192.168.220.147 (192.168.220.147) port 6443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /var/lib/rancher/k3s/server/tls/server-ca.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=k3s,O=k3s
* 	start date: Jan 06 02:21:16 2022 GMT
* 	expire date: Jan 06 02:21:16 2023 GMT
* 	common name: k3s
* 	issuer: CN=k3s-server-ca@1641435676
> GET /api/v1/pods HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.220.147:6443
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Audit-Id: 1d30dc47-bdf6-434d-ab8d-3cb74d411c57
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Thu, 06 Jan 2022 11:31:58 GMT
< Content-Length: 165
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
* Connection #0 to host 192.168.220.147 left intact

```
