### ISSUE TITLE
metrics-server stopped working since the latest v0.5.0 Docker image (rancher/mirrored-metrics-server) was pulled down

### ISSUE THREAD

**Issue by Kami** [k3s-io/k3s#4875]
Today I restarted my k3s cluster which is using version ``v1.22.5+k3s1``.

On restart, k3s automatically picked up and pulled down latest ``rancher/mirrored-metrics-server/metrics-server:v0.5.0`` image.

Since then, metrics-server doesn't start anymore and the pod log contains this error:

```bash
panic: failed to create listener: failed to listen on 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied

goroutine 1 [running]:
main.main()
	/go/src/sigs.k8s.io/metrics-server/cmd/metrics-server/metrics-server.go:39 +0xec
```

I assume the issue is related to the change in the upstream metrics-server release which removes``cap_net_bind_service`` permission (https://github.com/kubernetes-sigs/metrics-server/releases).

The thing is, k3s pins metrics-server to v0.5.0 in the manifest file and it worked just fine with v0.5.0 until it pulled down latest v0.5.0 tagged image today.

I also haven't changed anything on the cluster - I haven't touched the manifests or updated any other definitions related to the metrics-server.

Is it possible that CI which pushes Docker images to Docker Hub (``rancher/mirrored-metrics-server``) "malfunctioned" and also incorrectly tagged latest v0.5.2 release as v0.5.0 and that's the reason for the breakage?

The pod log and the behavior does seem to indicate that may be the case since the metrics-server changelog claims that capability change / removal is only included in >= 0.5.2 and the capability should still be there in v0.5.0.

Looking at https://registry.hub.docker.com/r/rancher/mirrored-metrics-server/tags?page=1&ordering=last_updated, I do see that various tags have been re-published today, but I didn't have a chance to dig and inspect the actual images yet.

![Screenshot from 2022-01-06 19-01-15](https://user-images.githubusercontent.com/125088/148430435-a6605814-dcbf-47b9-8b44-b549a4db22c7.png)

The solution / workaround I'm currently using is pinning metrics-server in ``/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-deployment.yaml`` to an older release (aka pre 0.5.0 and 0.4.5) where that capability is still present.

**Comment by brandond** [comment]
No, the mirroring script just makes things look like they've been touched. The v0.5.0 image is still correct:
```console
brandond@dev01:~$ docker run --rm -it rancher/mirrored-metrics-server:v0.5.0 --version
v0.5.0
```

I suspect something else is going on in your environment, since it works fine out of the box. Have you applied any hardening to your cluster or nodes?

**Comment by Kami** [comment]
Thanks for the response.

I haven't changed anything beyond a reboot. I only changed the image tag as a workaround for this issue. Later on, I can try updating manifest back to v0.5.0 tag again and see if the issue will be reproduced again.

Here is the output of ``kubectl get -n kube-system deployment metrics-server -o yaml`` (with updated tag workaround applied):

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6yTT4/TMBDFvwqac5z+pzQSh9UuJ6AgIXFZ9TC1p62J/8meBqIq3x05YVHRbigHbk5s/+bNm+cLYNBfKSbtHVSAIaRJM4MCau0UVPBAwfjWkmMowBKjQkaoLoDOeUbW3qX86fffSHIiLqP2pURmQ6X2E50hUIzu+++Oojg2NVRQL9LVTjMrXr3XTr29U8q7mwiHlqDKEqOWSSSKDUWhruXfBqSAMlPq855EahOTha4Ag3syfZv1myQwhGeF/kI/YTpBBTSb0ny5otmClq9xPV/JjVJKLQ8b2s8Xm8NsuV6vlweV673YCwz/RySmQDILTGRIso95bZHl6cNt7V1XAJMNBpn6e1dj/ofWRwVfyZLeMWpHMUH1eAGMx7wAISRFFkrn7iZsA+wK0BaPmRbRyRPFidUx+khK/Imvmmm5KqcwblfjzdnSR392PJS1efkZOc+jr/b7LtvQq+h23a6AELWPmtt7gylthxOD1cJ5RUJGzVqigQJyMS3pTsrM3o4oYW8oPj2WxwvU1EIF978wfcDTJ2faHKOQT+YBwrsfOnGCrrgAHQ4kGSrY+i/yROpsKL/RHtNLit5QmTMRHTGlHLzsefRGBIOO/ivZYuIh88+Ruyffh07JBm4fdM5j95LbXdf9DAAA//921xA6gwQAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: metrics-server-deployment
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2021-12-16T22:20:08Z"
  generation: 4
  labels:
    k8s-app: metrics-server
    objectset.rio.cattle.io/hash: e10e245e13e46a725c9dddd4f9eb239f147774fd
  name: metrics-server
  namespace: kube-system
  resourceVersion: "2887724"
  uid: 91aa480f-1797-4c26-907c-de42616a2f93
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-01-06T18:32:42+01:00"
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
      name: metrics-server
    spec:
      containers:
      - args:
        - --cert-dir
        - /tmp
        image: rancher/mirrored-metrics-server:v0.5.1
        imagePullPolicy: IfNotPresent
        name: metrics-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp-dir
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-06T21:38:09Z"
    lastUpdateTime: "2022-01-06T21:38:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-16T22:20:24Z"
    lastUpdateTime: "2022-01-06T21:38:30Z"
    message: ReplicaSet "metrics-server-788648b979" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by aleksanderllada** [comment]
I had the same issue, except it happened to several images. While I was trying to figure out what was causing it it suddenly succeeded to pull the images. This is what the pod status looked like:

```Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  24s               default-scheduler  Successfully assigned kube-system/metrics-server-9cf544f65-2d5b5 to server
  Normal   BackOff    17s               kubelet            Back-off pulling image "rancher/mirrored-metrics-server:v0.5.0"
  Warning  Failed     17s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    6s (x2 over 23s)  kubelet            Pulling image "rancher/mirrored-metrics-server:v0.5.0"
  Warning  Failed     1s (x2 over 18s)  kubelet            Failed to pull image "rancher/mirrored-metrics-server:v0.5.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/mirrored-metrics-server:v0.5.0": failed to resolve reference "docker.io/rancher/mirrored-metrics-server:v0.5.0": failed to do request: Head "https://registry-1.docker.io/v2/rancher/mirrored-metrics-server/manifests/v0.5.0": dial tcp: lookup registry-1.docker.io: Try again
  Warning  Failed     1s (x2 over 18s)  kubelet            Error: ErrImagePull
```

I had just updated K3s. My guess is that something happened to its DNS server and it took a while to update.
