### ISSUE TITLE
Use of --agent-token prevents additional servers from joining managed etcd cluster

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4881]
When the initial server is started with --agent-token, and this agent-only token does not match the server --token value, additional servers cannot join the cluster. This is due to the joining server incorrectly using the agent username, but the server token, when validating that the local configuration matches the existing server.

This affects the most recent round of releases, all the way back to the 1.20 branch:
* v1.20.14+k3s1
* v1.21.8+k3s1
* v1.22.5+k3s1
* v1.23.1+k3s1

On the Rancher side we have a related issue:
* https://github.com/rancher/rancher/issues/36051

There is a related but separate issue with the recently added `secrets-encrypt` subcommands allowing use of agent credentials to modify server encryption configuration, but this does not affect node join.

**Comment by rancher-max** [comment]
#### Validated using v1.20.14-rc1+k3s2, v1.21.8-rc1+k3s2, v1.22.5-rc1+k3s2, and v1.23.1-rc1+k3s2

- Can still use only `token` arg
- Can provide `agent-token` with a different value than `token`. It is required to be passed on all server nodes when joining.
- Can create v1.22 and v1.21 clusters in rancher using config: 3 nodes all roles
  - Note that using config: 3 nodes all roles, 2 nodes etcd only, 1 node cp only, 1 node worker only is failing in k3s, but failed on the previous releases as well. This appears to be unrelated and I will create a separate issue (probably in rancher after I debug further) to track.
