### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by webees** [k3s-io/k3s#4898]
**Environmental Info:**
K3s Version: 
```
k3s version v1.20.14+k3s1 (6149cba2)
go version go1.15.15
```

Node(s) CPU architecture, OS, and Version: 
```
Linux K3S 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug:**
The same container can be run in a docker environment, but not in k3s, even though I have docker as a runtime.
I'm not sure if the problem is caused by "hugepages" being enabled, but I can set shm-size in docker, and I can achieve similar results in k3s through host mapping. But it doesn't work in k3s.

I have reviewed a lot of information and think that the following is a similar situation. This problem may come from upstream.
https://github.com/kubernetes/kubernetes/issues/71233
https://github.com/kubernetes/kubernetes/issues/99483
https://stackoverflow.com/questions/67941955/kubernetes-postgres-bus-error-core-dumped

**Steps To Reproduce:**
- Installed K3s: 
Enable hugepage on the host, bind the data volumes as shown below, and start pods in the k3s cluster.
```
    volumes:
      - /dev/hugepages:/dev/hugepages 
      - /run/shm:/dev/shm
```

- Installed Docker: 
docker-compose.yml
```
version: '3'
services:
  carmi:
    image: 'carmi:latest'
    volumes:
      - /dev/hugepages:/dev/hugepages 
      - /run/shm:/dev/shm
```

**Actual behavior:**
Print "Bus error (core dumped)"

**Comment by brandond** [comment]
K3s doesn't alter any of upstream Kubernetes' behavior with regards to shm/hugepages, so I don't think that the issue is going to be related to anything we've done differently than upstream.

Can you provide a sample pod spec that reproduces the issue, as well as the output of `cat /proc/meminfo` on the node you're running that pod on?

**Comment by webees** [comment]
I will create an image for testing purposes, please wait.
