### ISSUE TITLE
Ingress through default Traefik working but stuck on status "Initializing"

### ISSUE THREAD

**Issue by crsantini** [k3s-io/k3s#490]
**Describe the bug**
Tested on Rancher 2.2.3 and K3S 0.5 on AWS using default traefik embedded on k3s.
After defining my ingress, the same works (respond to my external connections, hostname and paths) but get stuck on status "Initializing"

**To Reproduce**
1. Create a pod and service exposing the pod port. 
2. Create an ingress including annotation "kubernetes.io/ingress.class: "traefik"" redirecting requests to the specific service
3. Apply yaml and on rancher status will show "Initializing"
4. kubectl get ingress [ingress=name] --namespace="[namespace]" shows the ingress

**Expected behaviour**
1. To show Active on "load balancing" rancher section
2. To show all endpoints inside the deployed app

**Screenshots**
![Screen Shot 2019-05-20 at 4 57 48 pm](https://user-images.githubusercontent.com/11076880/58001994-6c709c00-7b20-11e9-8cf2-dfeff4ea45a4.png)

**Additional context**
Tested on Rancher 2.2.3 and K3S 0.5 on AWS using default traefik embedded on k3s. Kluster was imported to Rancher.

**Comment by superboris** [comment]
Hello, the same thing is happening to me, 
![image](https://user-images.githubusercontent.com/44072415/58256040-41fb2a80-7d3c-11e9-8f2b-911a7bc386d9.png)
although if I access the application if it works, although it does not redirect to https, I have to enter this line in the annotations:
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
also it is not showing in the logs the real IP that asks for the application tested with Nginx.
![image](https://user-images.githubusercontent.com/44072415/58256313-c9e13480-7d3c-11e9-88f3-86a0f898f06a.png)
Additional context
**Tested on Rancher** 2.2.2 and K3S 0.5.0 on VMWare using default traefik embedded on k3s. Kluster was imported to Rancher.

**Comment by cloudnautique** [comment]
We are aware of this issue, and will need to work something out between the two projects to address. Rancher looks for the external IP set by a cloud provider or in the case of RKE it looks for an annotation on the node. Once Rancher can get that information the ingresses move into the active state.

We are working on a hack-y solution to populate: `rke.cattle.io/external-ip: <ip>` annotation on the node manually.

**Comment by digitalassembly** [comment]
@cloudnautique Thanks for your reply! Looking forward to a solution. Please let me know if you require help on testing again.

**Comment by gunturaf** [comment]
any luck on bypassing this for the time being to make the status changed from `Initializing`? The ingress works just fine though.

My setup are:
- Racher v2.2.6
- rancher/ui v2.2.90
- rancher/helm v2.10.0-rancher11
- rancher/machine v0.15.0-rancher8-1
- traefik v1.7.12-alpine
- K8S v1.13.7
- On-Premise atop Proxmox

thank you

**Comment by h2aopsdev** [comment]
Hello, same issue for me.
Even if the annotation (rke.cattle.io/external-ip)  is correctly populate by rancher on the node . 
The status still Initializing 
Rancher | v2.3.0
User Interface | v2.3.15
Machine | v0.15.0-rancher12-1
Traefik | V2.0.2

**Comment by vitobotta** [comment]
Same here with Traefik.

**Comment by vol-pi** [comment]
Is this related to https://github.com/traefik/traefik/issues/2173 ? 

As far as I understand the k3s default traefik deployment via helm value `kubernetes.ingressEndpoint.useDefaultPublishedService` queries its corresponding service status, which does not seem to work.

**Comment by BobTB** [comment]
This is a trafeik problem. 

Just set kubernetes.ingressendpoint.publishedservice=namespace/traefik-ingress-service (use your namespace and traefik service name) and it will work. At least it does for me, I am using RKE2 + Traefik V2.

 I just had to set the Traefik V2 helm chart from the following default:

  publishedService:
      enabled: false

to

  publishedService:
      enabled: true

And apply the helm chart again and ingreses will be updated to 'Active' + IP address in kubect get ing -A will show the IP
