### ISSUE TITLE
S3 Backup Cron not working

### ISSUE THREAD

**Issue by tabnul** [k3s-io/k3s#4902]
**Environmental Info:**
K3s Version: 
v1.22.5+k3s1

Node(s) CPU architecture, OS, and Version: 
3 nodes, AMD64

Cluster Configuration:
Master/Worker x3

**Describe the bug:**
The S3 etcd backup schedule doesnt work. 
See below server parameters. When i initiate a manual snapshot with these exact same parameters, a backup is made to S3. 
No logging at the moments the CRON should do something. Doesnt seem to get triggered.

```
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable' \
        'servicelb' \
        '--disable' \
        'traefik' \
        '--write-kubeconfig-mode' \
        '644' \
        '--write-kubeconfig' \
        '/tmp/kubeconfig_org.yaml' \
        '--token' \
        'XXXXX' \
        '--node-label' \
        'workertype=master' \
        '--node-taint' \
        'node-role.kubernetes.io/master=effect:NoSchedule' \
        '--tls-san' \
        'XXXXX.localdomain' \
        '--etcd-s3' \
        '--etcd-snapshot-schedule-cron' \
        '0 \*/12 \* \* \*' \
        '--etcd-s3-endpoint' \
        's3.eu-central-1.amazonaws.com' \
        '--etcd-s3-access-key' \
        'XXXXXX' \
        '--etcd-s3-secret-key' \
        'XXXXXX' \
        '--etcd-s3-region' \
        'eu-central-1' \
        '--etcd-s3-folder' \
        'etcd' \
        '--etcd-s3-bucket' \
        'XXXXXXX' \
        '--cluster-init' \
```

**Steps To Reproduce:**
Install K3s using the supplied parameters.

- Installed K3s: 

**Expected behavior:**
Backups to S3 to be made accoring to the set CRON schedule.

**Actual behavior:**
No backups

**Additional context / logs:**
No logs at moments it should make the backup

**Comment by brandond** [comment]
I don't believe that `'0 \*/12 \* \* \*'` is a valid Cron expression. Backlashes within single quotes don't escape the following character, they are just included as literal backslashes in the Cron expression, which would render it invalid.

**Comment by tabnul** [comment]
> I don't believe that `'0 \*/12 \* \* \*'` is a valid Cron expression. Backlashes within single quotes don't escape the following character, they are just included as literal backslashes in the Cron expression, which would render it invalid.

It is the result of the following installation command, which seems correct. By the way also the CRON value for the generic etcd backup suffers the same issue;

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.5+k3s1 INSTALL_K3S_EXEC=" \
server --disable servicelb \
--disable traefik \
--write-kubeconfig-mode 644 \
--token XXXXXX \
--node-label workertype=normal \
--tls-san XXXX \
--etcd-snapshot-schedule-cron '0 */12 * * *' \
--etcd-snapshot-retention 14 \
--etcd-s3 --etcd-snapshot-schedule-cron '0 */12 * * *' \
--etcd-s3-endpoint s3.eu-central-1.amazonaws.com \
--etcd-s3-access-key XXXXX \
--etcd-s3-secret-key XXXX  \
--etcd-s3-region eu-central-1 \
--etcd-s3-folder etcd \
--etcd-s3-bucket XXXXX \
--server https://XXXXX:6443" sh - 
```

**Comment by tabnul** [comment]
After a little investigation i found this issue for k3sup:
https://github.com/alexellis/k3sup/issues/350#issuecomment-946797559
The third scenario indeed does the trick. So refactoring the installation command into the following results in correct CRON syntax. I will just assume it will actually schedule now ;)

Question remains: is this a bug in the K3S installation script? 
In my opinion at least it should not accept these values if it results in a non-functioning situation.

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.5+k3s1 INSTALL_K3S_EXEC=\
**"server" sh -s - \**
--disable servicelb \
--disable traefik \
--write-kubeconfig-mode 644 \
--token XXXX  \
--node-label workertype=normal \
--tls-san XXXXXX \
--etcd-snapshot-schedule-cron "0 */12 * * *" \
--etcd-snapshot-retention 14 \
--etcd-s3 \
--etcd-snapshot-schedule-cron "0 */12 * * *" \
--etcd-s3-endpoint s3.eu-central-1.amazonaws.com \
--etcd-s3-access-key XXXXX \
--etcd-s3-secret-key XXXXX \
--etcd-s3-region eu-central-1 \
--etcd-s3-folder etcd \
--etcd-s3-bucket XXXXX \
--server https://XXXXXX:6443
```

**Comment by brandond** [comment]
The install script is just that, an install script. It doesn't validate any of the args. This is all just how quoting works in shells - the argument needs to be a single string with asterisks in it. Not split into multiple arguments, not escaped with backslashes. Just a simple quoted Cron expression. If you passed it in to the install script differently, and the installer mangled it, that would constitute a bug.
