### ISSUE TITLE
k3s.service: Failed at step LIMITS spawning /usr/local/bin/k3s: Operation not permitted

### ISSUE THREAD

**Issue by mpv945** [k3s-io/k3s#4909]
I modified the file number configuration of the system:

vi /etc/systemd/system.conf
DefaultLimitCORE=1024000
DefaultLimitNOFILE=1024000
DefaultLimitNPROC=1024000

vi /etc/security/limits.conf
* soft nofile 1024000
* hard nofile 1024000
* soft nproc 1024000
* hard nproc 1024000
* soft core unlimited
* hard core unlimited
* soft fsize unlimited
* hard fsize unlimited
* soft cpu unlimited
* hard cpu unlimited
* soft as unlimited
* hard as unlimited

vi /etc/sysctl.conf
fs.file-max = 1024000
fs.nr_open = 1024000

curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - server ......

**Comment by brandond** [comment]
Can you share the complete output from running the install script, and attach the logs from `journalctl --no-pager -u k3s &>k3s.log`
