### ISSUE TITLE
etcd-snapshot subcommand does not out debug logs even when `--debug` flag is provided

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4920]
**Environmental Info:**
K3s Version: 

Master branch

Cluster Configuration:

Any etcd cluster
**Describe the bug:**

With a running k3s server, calling k3s etcd-snapshot save --debug does not correctly output debug logs.

**Steps To Reproduce:**

- Installed K3s: 

Steps To Reproduce:

    Installed K3s:
    Run any cluster
    Attempt to save a snapshot with the --debug flag set in either CLI or config.yaml

Expected behavior:

All k3s subcommands that support debug flag should output debug logs

Actual behavior:

Only server and agent output debug logs with the flag set.
etcd-snapshot and others do not.
**Backporting**

- [X] Needs backporting to all older releases.

**Comment by ShylajaDevadiga** [comment]
Validated using the commit 48ffed38522aea0003b1997367969936967c8489 from master branch. Passing --debug flag displays the debug logs while using etcd-snapshot subcommands.
```
$ sudo k3s etcd-snapshot save --debug
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Applying CRD addons.k3s.cattle.io            
DEBU[0000] DesiredSet - Patch apiextensions.k8s.io/v1,
```

**Comment by ShylajaDevadiga** [comment]
Validated on rc using k3s version v1.23.2-rc1+k3s1
