### ISSUE TITLE
encryption at rest configuration

### ISSUE THREAD

**Issue by camaeel** [k3s-io/k3s#4928]
Currently used aescbc encryption is not recomended by the kubernetes project (https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers). I'd like to create my own encryption-config.json. But after I introduced changes k3s failed with:
```
Jan 12 22:46:59 master k3s[84316]: time="2022-01-12T22:46:59+01:00" level=fatal msg="/var/lib/rancher/k3s/server/cred/encryption-config.json newer than datastore and could cause cluster outage. Remove the file from disk and restart to be recreated from datastore."
```

This functionality prevents cluster administrator from providing own encryption config. I'd like to provide encryption key from external source (like hashicorp vault) in order to be able to recover cluster in case of disaster from etcd backup. Without control of this key I won't be able to recover it.

**Comment by brandond** [comment]
If you use `--secrets-encryption` flag, then the encryption configuration is managed by K3s; you should not modify it yourself. If you want to provide your own configuration configuration, you should use --kube-apiserver-arg=encryption-provider-config=/path/to/config.json` to point the apiserver at a custom configuration file.
