### ISSUE TITLE
[Release-1.22] etcd-snapshot subcommand does not out debug logs even when --debug flag is provided

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#4929]
Backport https://github.com/k3s-io/k3s/issues/4920 to release-1.22

**Comment by rancher-max** [comment]
#### Validated using commitid `354477adbfbd596828a56ce9882b081629321ed8` from branch `release-1.22`

- Multiple debug logs are now passed when passing the `--debug` flag to the snapshot command. See below snippet of the command and the start of the logs which now contain `DEBU` for debug outputs.
```
~$ sudo k3s etcd-snapshot save --debug
WARN[0000] Unknown flag --write-kubeconfig-mode found in config.yaml, skipping 
WARN[0000] Unknown flag --tls-san found in config.yaml, skipping 
WARN[0000] Unknown flag --token found in config.yaml, skipping 
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Applying CRD addons.k3s.cattle.io            
DEBU[0000] DesiredSet - Patch apiextensio
```
