### ISSUE TITLE
[release-1.22] Cluster restore fails with "127.0.0.1:6444: read: connection reset by peer"

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4935]
Backport fix for **Cluster restore fails with "127.0.0.1:6444: read: connection reset by peer"** to branch **release-1.22**
* https://github.com/k3s-io/k3s/issues/4914

**Comment by ShylajaDevadiga** [comment]
Fix is validated using rc2 on 1.22.5. Restore in current setup and fresh node setup is successful.
Scenarios covered

- Validate cluster-reset flag functionality

- Verify snapshot/restore functionality in a quorum loss scenario when snapshot is stored locally. 

- Create snapshot and store in s3 bucket

- Restore to any of the current nodes

- Restore to a new setup
