### ISSUE TITLE
Multi-node cluster becomes unstable after upgrading from v1.20.4 to v1.21.8

### ISSUE THREAD

**Issue by aalcaraz97** [k3s-io/k3s#4937]
**Environmental Info:**
K3s Version: 
* Before K3S upgrade:
```bash
$ k3s --version
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```
* Desired version after K3S upgrade:
```bash
$ k3s --version
k3s version v1.21.8+k3s1 (cbff7350)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version:
* Output of the 3 nodes `uname -a` command:
```bash
Linux dmspcsfupgrade219-ha0 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dmspcsfupgrade219-ha1 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dmspcsfupgrade219-ha2 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* OS version in all 3 nodes:
```bash
CentOS Linux release 7.9.2009 (Core)
```

Cluster Configuration:
* A multi-node K3S cluster with 3 nodes, with all nodes being **control-plane nodes**.
* Using the **embedded etcd** as the cluster storage database
* The cluster CNI is **Flannel + Wireguard** (using the --flannel-backend=wireguard flag in all 3 nodes)

**Describe the bug:**

I have a 3-node K3S cluster using the v1.20.4+k3s1 version. All the 3 nodes are control-plane nodes, and they are all using the embedded etcd as the cluster storage database.

I am installing Istio on top of the cluster, together with the Istio CNI Plugin. This CNI plugin requires two config values:
* The path where to store the Istio CNI binaries, which should be set to the K3S binaries path, which is `/var/lib/rancher/k3s/data/current/bin`
* The path where to store the Istio CNI config, which should be set to the K3S CNI config, which is `/var/lib/rancher/k3s/agent/etc/cni/net.d`

I want to upgrade the K3S version in the cluster to the v1.21.8+k3s1 version. 

These are the steps that I'm performing in order to upgrade K3S to the new version:

**Step 1**: Scale down the Istio CNI Plugin

This is done as a workaround to solve an issue with the Istio CNI Plugin. As I described before, the Istio CNI binary folder path is set to `/var/lib/rancher/k3s/data/current/bin`, which is a softlink to the "K3S data folder" with a defined string (in K3s v1.20.4, the folder string is `a6857be08414815b83ca6b960373efd98879a0b286fb24cb62b1c5fdbf3a8cb5`). When upgrading to K3s v1.21.8, this softlink strategy changes: a new softlink called "previous" now points to the v1.20.4 data folder, and the "current" softlink points to the new v1.21.8 data folder (which is `d57e8308a6ecab1a8523633f3c9d0fbb19a79217e3f9f1a2a21addbb55cb5cdf`)

As the Istio CNI configuration points to the "current" softlink instead of the hardcoded v1.20.4 string folder, when upgrading K3S to v1.21.8, I have to restart the Istio CNI pods, so their config points to the new v1.21.8 "current" softlink path, and the Istio CNI binaries are installed in the new 1.21.8 K3S data binary folder.

**Step 2**: Stop the K3S systemd unit:
```bash
sudo systemctl stop k3s
```

**Step 3**: Replace the v1.20.4 K3s binary and files ("k3s" binary, "install.sh" script and the "k3s-airgap-images-amd64.tar" file) with the new v1.21.8 artifacts.

**Step 4**: Update the K3s systemd unit file to add new v1.21.8 flags (only adding a new K3S flag to configure the etcd DB quota to 8 GB):
```bash
echo "        '--etcd-arg' 'quota-backend-bytes=8589934592'" | sudo tee -a /etc/systemd/system/k3s.service >/dev/null
```

**Step 5**: Reload the systemd daemons to apply the new systemd unit change
```bash
sudo systemctl daemon-reload
```

**Step 6**: Start the K3S systemd unit with the new version:
```bash
sudo systemctl start k3s
```

**Step 7**: Wait for K3s to be ready after the upgrade

I have to implement a busy wait to check for K3s to be ready after the upgrade, because I realized by looking at the K3S journalctl logs that K3s is restarted a couple of times after starting again the K3S systemd unit with the v1.21.8 version.

The check that I implemented is to query the apiserver using the "kubectl cluster-info" command as the check for the K3s API being up and running (as I had encountered some errors while trying to perform some "kubectl" commands in the cluster after the upgrade, but the "kubectl" commands failed due to the apiserver not being running):
```bash
Error from server (InternalError): an error on the server ("apiserver not ready") has prevented the request from succeeding
```
The check that I implemented is the following:
```bash
waitForK3sToBeReady() {
  declare -i timeout=0
  declare -i successCheck=0
  while [[ "$successCheck" < "150" && "$timeout" < "1800" ]]; do
    sleep 2
    timeout =$((timeout + 2))
    kubectl cluster-info
    if [[ "$?" -eq 0 ]]; then
      successCheck=$((successCheck + 1))
    else
      successCheck = 0
    fi
  done
  if [[ "$timeout" > 1800 ]]; then
    exit 1
  fi
}
```
It basically checks every 2 seconds if the "kubectl cluster-info" command does not return an error (apiserver not being available), and considers K3s "stable" when 150 consecutive successful checks are achieved (that is, 5 minutes receiving consecutive successful checks). This has been done to detect possible K3S restarts after 1-2 minutes of starting the 1.21.8 K3S systemd unit.

**Step 8**: Scale up the Istio CNI Plugin

After checking that K3s is now stable and should not be restarted, I scale up again the Istio CNI pods, so the CNI binaries are copied in the new v1.21.8 K3S data binary folder. I have to manually scale down and scale up because the K3s systemd stop/start does not restart the Istio CNI pods by itself.

**Step 9**: Wait for all pods to be ready after K3S start

I basically perform a busy wait for all the other cluster pods to be ready. 

After the busy wait is finished, all the cluster pods are ready and the node should be successfully upgraded to K3S v1.21.8. After that, I have to repeat the K3s upgrade process in the other 2 remaining nodes to update every cluster node to v1.21.8.

I am having issues on the Step 8 (scaling up the Istio CNI plugin). After scaling up the pods, I perform an active wait for the Istio CNI pods to be running before continuing.
The active wait is implemented as the following:
```bash
kubectl wait --for=condition=Ready --namespace istio-system -l k8s-app=istio-cni-node --timeout=600s
```
This specific command almost always timeouts (it fails after 10 minutes), as the Istio CNI pods never achieve the Running state.
After manually checking the pods state, I see the Istio CNI pods as Pending:
```bash
$ kubectl get pods -n istio-system -l k8s-app=istio-cni-node -o wide
NAME                   READY   STATUS    RESTARTS   AGE   IP            NODE
istio-cni-node-ch4nc   0/2     Pending   0          15m   <ip-ha0>      dmspcsfupgrade219-ha0   
istio-cni-node-jlp4k   0/2     Pending   0          15m   <ip-ha2>      dmspcsfupgrade219-ha2  
istio-cni-node-jwxpd   0/2     Pending   0          15m   <ip-ha1>      dmspcsfupgrade219-ha1   
```

If I describe the pending pod events, the only event I see is the following:
```bash
$ kubectl describe pod --namespace istio-system istio-cni-node-ch4nc
Name:                 istio-cni-node-ch4nc
Namespace:            istio-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 dmspcsfupgrade219-ha0/<ip-ha0>
[...]
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  15m   default-scheduler  Successfully assigned istio-system/istio-cni-node-ch4nc to dmspcsfupgrade219-ha0
```

After waiting for a long time (sometimes is 60 minutes, sometimes has been even 6 or 7 hours!), the pod eventually transitions to the Running state. But that does not mean that the problem is solved, as some other pods in the cluster also get stuck indefinitely in other unwanted states, as in Terminating or ContainerCreating state. Overall, the cluster does not recover from the upgrade.

This happen almost ever time I perform the K3s upgrade to the v1.21.8 version. However, there has been a few times that this same procedure has worked successfully for me: the Istio CNI pods are successfully scaled up, and all the other cluster pods get to Running state. Then, I proceed to perform the same steps in the other 2 remaining nodes to upgrade all 3 nodes to v1.21.8.

I want to have all this upgrade K3s process automated with scripts (which perform busy waits for all steps), so waiting for 30 minutes (or even 6/7 hours) for some pods to be Running is not possible. There is definitely something that is not going well here.

I wanted to open this Github issue to:

* Find a suitable solution for my problem in the upgrade, so I can automate the K3S upgrade in my cluster
* Also check if the upgrade process that I'm following is the right one, or if I am making some mistake or any wrong procedure to perform a K3s upgrade.

Unfortunately, the K3S upgrade-controller is not a solution for me, as I need to support air-gapped installations and upgrades of my cluster.
I cannot upgrade to any Kubernetes version >= 1.22 either, as I have some components in my cluster that are not compatible with Kubernetes 1.22 or above, so I have to stick with the 1.21 Kubernetes version.

**Steps To Reproduce:**

The steps performed are detailed above.

**Expected behavior:**

Upgrade to K3s v1.21.8+k3s1 version in an embedded etcd multi-node cluster is working

**Actual behavior:**

Upgrade to K3s v1.21.8+k3s1 version in an embedded etcd multi-node cluster leaves the cluster in an unstable stable, where the existing pods have different behaviors:
* Some pods never reach the Running state
* Some pods are stuck for a long time in Pending state
* Some pods are stuck for a long time or indefinitely in Terminating state
* Some pods are stuck for a long time or indefinitely in ContainerCreating state

**Additional context / logs:**

I can post the K3s journalctl logs of the nodes if needed to debug the issue. I have set the --debug flag to check if I missed something on the journalctl logs that might give me a clue of what could be happening.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
I suspect that you might be running into https://github.com/kubernetes/kubernetes/issues/70044.

If k3s (the kubelet in particular) is restarted while pods are in the process of being terminated, they can get stuck that way until force-deleted, or until the kubelet is restarted another few times. These stuck pods can prevent their replacements from starting, as they're holding on to ports or mounts that the new pods need.

The best workaround we've found is to wait longer between restarting K3s nodes, especially after making any change that might cause pods to be terminated (for example, updating deployments or daemonsets).
