### ISSUE TITLE
Update packaged containerd and etcd

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4940]
* containerd 1.5.9 - fix (previously patched in our fork) for CVE: GHSA-mvff-h3cj-wj9c
* etcd 3.5.1 - fix for https://github.com/etcd-io/etcd/issues/13196

**Comment by mdrahman-suse** [comment]
Verified in k3s master commit fc8309a46c1e2a1c9e2491b5c63fe3c9a63ab6cb for the updated versions of containerd and etcd to v1.5.9 and v3.5.1 respectively

containerd
```
$ sudo crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.5.9-k3s1
RuntimeApiVersion:  v1alpha2
```
etcd
```
$ journalctl -xe | grep "etcd-version"
Jan 20 21:59:14 ip-172-31-35-3 k3s[2164]: {"level":"info","ts":"2022-01-20T21:59:14.387Z","caller":"embed/etcd.go:307","msg":"starting an etcd server","etcd-version":"3.5.1"
```
