### ISSUE TITLE
[release-1.21] Update packaged image versions

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4944]
Update packaged images for 1.21 releases:
* rancher/local-path-provisioner:v0.0.21
* rancher/mirrored-coredns-coredns:1.8.6
* rancher/mirrored-library-busybox:1.34.1
* rancher/mirrored-metrics-server:1.5.2
* rancher/mirrored-library-traefik:2.5.6
* rancher/mirrored-pause:3.5

**Comment by VestigeJ** [comment]
Metrics server is reporting v0.5.2 using 
COMMIT=8069a88177f75d4b42336e5dad6683731cb079f3
Other than that and not seeing busybox everything else seems solid.
$ k3s -v
```
k3s version v1.21.8+k3s-8069a881 (8069a881)
go version go1.16.10
```

$ sudo k3s crictl images
```
IMAGE                                        TAG                    IMAGE ID            SIZE
docker.io/rancher/klipper-helm               v0.6.6-build20211022   194c895f8d63f       84.5MB
docker.io/rancher/klipper-lb                 v0.3.4                 746788bcc27e2       3.33MB
docker.io/rancher/local-path-provisioner     v0.0.21                fb9b574e03c34       11.4MB
docker.io/rancher/mirrored-coredns-coredns   1.8.6                  a4ca41631cc7a       13.6MB
docker.io/rancher/mirrored-library-traefik   2.5.6                  2cd4bc25ad14d       30MB
docker.io/rancher/mirrored-metrics-server    v0.5.2                 f73640fb50619       26MB
docker.io/rancher/mirrored-pause             3.5                    ed210e3e4a5ba       301kB
```

**Comment by brandond** [comment]
You will only see busybox if you use the local-path provisioner. There's a sample manifest to test with at https://github.com/k3s-io/k3s/blob/master/scripts/airgap/volume-test.yaml

**Comment by VestigeJ** [comment]
Thanks for the tip I've shared it with QA. Can you verify that v0.5.2 is correct for metrics-server?
