### ISSUE TITLE
Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)

### ISSUE THREAD

**Issue by binbashblog** [k3s-io/k3s#4967]
**Environmental Info:**
K3s Version:  k3s version v1.23.1+k3s2 (a0cadcd3)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: Linux pi-k3s-m01 5.4.0-1048-raspi #53-Ubuntu SMP PREEMPT Wed Dec 8 13:06:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration: 1 control plane, 3 nodes. Using System-Upgrade-Controller for automatic upgrades.

**Describe the bug:**
The ingress host addresses  are unreachable, I get a 404 page error.
Checking logs on Traefik gives the following repeationg error:
E0117 15:28:41.267438       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)

**Steps To Reproduce:**

- Installed K3s: 
Standard install via installation script
Automatic upgrades enabled

**Expected behavior:**

Ingresses to be reachable

**Actual behavior:**

404 errors 

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
`v1beta1.Ingress` is no longer available as of Kubernetes 1.22. Did you by any chance upgrade this cluster from a much older version of K3s, and are still running Traefik v1? If so, you will need to take manual steps to migrate to Traefik v2, which includes support for `v1.Ingress`. 

This was called out in the 1.22 release notes, which you may have missed if you were just relying on the upgrade controller and not visiting the GitHub release page:
https://github.com/k3s-io/k3s/releases/tag/v1.22.2%2Bk3s1

**Comment by binbashblog** [comment]
Yes I upgraded it from a older version around 1.19 or so. Is there any documentation how to do it, I tried to install v2 but I get this:

"+ helm_v3 install --repo https://containous.github.io/traefik-helm-chart --set-string image.tag=2.2 traefik traefik
Error: failed to install CRD crds/ingressroute.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1""

**Comment by binbashblog** [comment]
I've found the following resolves this:
https://pet2cattle.com/2021/12/k3s-update-traefik-to-v2

As per the above link "the manifest located on /var/lib/rancher/k3s/server/manifests are not being updated. To update them we can check the appropriate K3s version on it's github repository for the default yaml file that is being shipped with K3s to update it.".

**Comment by dollarpo7** [comment]
Hi @binbashblog how did you end up resolving this. Got the same issue.

**Comment by brandond** [comment]
This message indicates that the traefik chart needs to be upgraded. If you've upgraded from a much older release of K3s that was still on Traefik 1, you will need to migrate to v2 as described here: https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller

If you haven't customized your ingress configuration and are OK with a short amount of downtime, you can stop k3s, temporarily start it with `--disable=traefik` to remove the old v1 chart, and then start it again without that flag to install the new v2 chart.

**Comment by binbashblog** [comment]
> Hi @binbashblog how did you end up resolving this. Got the same issue.

As per my above post the solution in the link (https://pet2cattle.com/2021/12/k3s-update-traefik-to-v2) fixed my issue. You need to upgrade to Traefik V2, follow the link it's all there.

**Comment by nachtmaar** [comment]
> This message indicates that the traefik chart needs to be upgraded. If you've upgraded from a much older release of K3s that was still on Traefik 1, you will need to migrate to v2 as described here: https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller
> 
> If you haven't customized your ingress configuration and are OK with a short amount of downtime, you can stop k3s, temporarily start it with `--disable=traefik` to remove the old v1 chart, and then start it again without that flag to install the new v2 chart.

@brandond Thanks, your tip worked 😎
```bash
service k3s stop
k3s server --disable=traefik
# wait until the pod which removes traefik is completed
# then press CTRL-C and run:
service k3s start
# wait until the pod which installs traefik is completed
```
