### ISSUE TITLE
kubernetes iptables rules not automatically setup after reinstalling

### ISSUE THREAD

**Issue by lostcoaster** [k3s-io/k3s#4969]
**Environmental Info:**
K3s Version: k3s version v1.23.1+k3s2 (a0cadcd3); go version go1.17.5

Node(s) CPU architecture, OS, and Version: Linux pi4x4 5.4.0-1048-raspi #53-Ubuntu SMP PREEMPT Wed Dec 8 13:06:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration: 1 server, 2 agents 

**Describe the bug:**

k3s seems not generating iptables rules when reinstalling the same version.

**Steps To Reproduce:**

In order to recover from a failure state, I uninstalled and reinstalled k3s-agent on one of my nodes.
* First did `/usr/local/bin/k3s-agent-uninstall.sh` to uninstall the current installation, which is same as latest version v1.23.1+k3s2
* Then checked `iptables -L`, confirming no rules remains.
* Then ran ` curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest K3S_URL=<my server url> K3S_TOKEN=<my server token> sh -`, reinstall is completed.
* However `iptables -L` is still empty, `service k3s-agent status` shows the agent tried to connect through 127.0.0.1:6444 which should be mapped to server:6443, and failed repeatedly.

**Expected behavior:**

iptables rules should be set up automatically.

**Actual behavior:**

**Additional context / logs:**

I tried to uninstall again and this time downgrading the agent node to v1.20.4+k3s1 (last stable version I used), and this time when `k3s-agent` is started, the iptables rules are automatically populated as expected.

**Comment by brandond** [comment]
> However iptables -L is still empty, service k3s-agent status shows the agent tried to connect through 127.0.0.1:6444 which should be mapped to server:6443, and failed repeatedly.

It sounds like the rules aren't there because the agent can't reconnect to the server. What exactly do the k3s-agent logs say? Did you delete the node from the cluster after uninstalling? If you you it may not have the correct node token, as documented at https://rancher.com/docs/k3s/latest/en/architecture/#how-agent-node-registration-works

**Comment by lostcoaster** [comment]
> > However iptables -L is still empty, service k3s-agent status shows the agent tried to connect through 127.0.0.1:6444 which should be mapped to server:6443, and failed repeatedly.
> 
> It sounds like the rules aren't there because the agent can't reconnect to the server. What exactly do the k3s-agent logs say? Did you delete the node from the cluster after uninstalling? If not, you it may not have the correct node token, as documented at https://rancher.com/docs/k3s/latest/en/architecture/#how-agent-node-registration-works

Thanks for the reply. The logs looked something like these:

```
Jan 17 20:50:09 pi4x4 systemd[1]: Starting Lightweight Kubernetes...
Jan 17 20:50:09 pi4x4 sh[1754]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jan 17 20:50:10 pi4x4 sh[1756]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jan 17 20:50:10 pi4x4 systemd[1]: Started Lightweight Kubernetes.
Jan 17 20:50:11 pi4x4 k3s[1827]: time="2022-01-17T20:50:11Z" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:38720->127.0.0.1:6444: read: connection reset by peer"
Jan 17 20:50:15 pi4x4 k3s[1807]: time="2022-01-17T20:50:15Z" level=info msg="Starting k3s agent v1.23.1+k3s2 (a0cadcd3)"
Jan 17 20:50:15 pi4x4 k3s[1807]: time="2022-01-17T20:50:15Z" level=info msg="Running load balancer 127.0.0.1:6444 -> [192.168.1.117:6443 pi4x1:6443]"
Jan 17 20:50:31 pi4x4 k3s[1827]: time="2022-01-17T20:50:31Z" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:38728->127.0.0.1:6444: read: connection reset by peer"
Jan 17 20:50:34 pi4x4 k3s[1807]: time="2022-01-17T20:50:34Z" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:48552->127.0.0.1:6444: read: connection reset by peer"
...
```

But at that moment, I could run `curl https://my_server_addr:6444/cacerts --insecure` to get the cert correctly, on this worker node.

Another observation is when the node was trying to connect to `127.0.0.1:6444`, `iptables -L` was still empty, that made me believe the node was just trying to connect to localhost without forwarding, which surely failed.

**Comment by brandond** [comment]
> Jan 17 20:50:15 pi4x4 k3s[1807]: time="2022-01-17T20:50:15Z" level=info msg="Running load balancer 127.0.0.1:6444 -> [192.168.1.117:6443 pi4x1:6443]"

You'd only see multiple addresses here if you had files left over from a previous install. Which one of these (192.168.1.117 or pi4x1) is the actual server you're trying to join?

**Comment by lostcoaster** [comment]
They "should" point to the same server because my router is mapping the hostname to their IPs. But I think you are right, the first IP might be changed because of router restarting. Where is the setting file to clear in case this happens again?

**Comment by brandond** [comment]
Uninstalling should do it, but you can also stop k3s-agent, `rm -rf /var/lib/rancher/k3s/agent/etc/*.json`, and then restart it and it should go back to trying only the endpoint specified by the --server CLI flag.

**Comment by lostcoaster** [comment]
That's the weird thing, I did tried uninstalled, ran both `k3s-killall.sh` and `k3s-agent-uninstall.sh`, but after installing with the latest version (same version), the problem persisted.

It only went away when I chose another version, in this case 1.20.4. I am not sure whether a new version means a "cleaner" reinstall.
