### ISSUE TITLE
Custom kube-scheduler

### ISSUE THREAD

**Issue by aledbf** [k3s-io/k3s#4970]
**Is your feature request related to a problem? Please describe.**

I want to use a custom scheduler plugin from  https://github.com/kubernetes-sigs/scheduler-plugins/ as `default-scheduler`.
Right now I can disable the default scheduler using `--disable-scheduler` but I am not sure how to enable the replacement.

**Describe the solution you'd like**

Not sure. An option to use a container instead of an embedded feature in the binary?

**Describe alternatives you've considered**

Using `schedulerName` in the pods

**Additional context**

N/A

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
I don't believe there's anything stopping you from using a different scheduler. K3s doesn't have any built in though - if you want to run your own as a pod, you'd need to solve the chicken-and-egg problem of getting it running. Leaving the default in place and using schedulerName to use your alternative one is probably the best bet.

**Comment by aledbf** [comment]
Closing. Using a secondary scheduler with `schedulerName` is enough. Thanks"

**Comment by heyu1207** [comment]
I want to customize a scheduler. How can I use k3s to debug the scheduler like using k8s?

**Comment by heyu1207** [comment]
> 

May I ask how to register the customize scheduler to k3s?

**Comment by aledbf** [comment]
Please check https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler

**Comment by heyu1207** [comment]
Thank you very much.  I didn't know there can be multiple schedulers.
