### ISSUE TITLE
Is there any plan to support docker cgroupv2?

### ISSUE THREAD

**Issue by zzzhangqi** [k3s-io/k3s#4971]
When I run K3s with docker in docker in docker desktop for mac, I encounter that cgroupv2 does not support it.

Docker Desktop for Mac introduced cgroupv2 in version [4.3.0](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-430).

Installing versions prior to 4.3.0 can solve the problem

**Comment by brandond** [comment]
K3s has supported cgroupv2 for quite a while. You've not provided much information at all on what error you're running into, but I suspect that it's not caused by K3s itself.
