### ISSUE TITLE
How does traefik configure the addresses outside the cluster in upstream

### ISSUE THREAD

**Issue by MagicStarTrace** [k3s-io/k3s#4976]
I plan to use ingress in the cluster to associate all services outside the cluster, and no longer use nginx to manage

How should I configure traefik upstream?

Thank You!

**Comment by poblin-orange** [comment]
You should define ExternalName services, and use them as backend in your Traefik configuration (ingress/IngressRoute or IngressRouteTCP)

**Comment by MagicStarTrace** [comment]
Thanks you!

I currently use the external svc  + ingress way to achieve
