### ISSUE TITLE
[Release 1.21] IPv6 masquerade NAT rules missing in dual-stack installation

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#4979]
Backport for #4683

**Comment by ShylajaDevadiga** [comment]
Validated on a two node cluster using v1.21.9-rc1+k3s1, one server one agent

- Install k3s in dual stack mode
- Deploy testing pod. 
- ping any target host using ipv4 and as well as ipv6
- Verify that the packets arrive on the target host

Pod got deployed on the agent node, with node ip 2600:<REDACTED>6462
ping ipv6 address from with the testing pod
```
ping -c 5 2600:<REDACTED>:3273
PING 2600:<REDACTED>:3273(2600:<REDACTED>:3273) 56 data bytes
64 bytes from 2600:<REDACTED>:3273: icmp_seq=1 ttl=63 time=0.739 ms
```
Verify on target host using tcpdump, pod ipv6 address is NATed
```
sudo tcpdump -i eth0 -n ip6
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
23:50:14.232607 IP6 2600:<REDACTED>6462 > 2600:<REDACTED>:3273: ICMP6, echo request, seq 1, length 64
23:50:14.232649 IP6 2600:<REDACTED>:3273 > 2600:<REDACTED>:6462: ICMP6, echo reply, seq 1, length 64
```
