### ISSUE TITLE
17004 proxier.go:1600] "can't open port, skipping it

### ISSUE THREAD

**Issue by BlackTurtle123** [k3s-io/k3s#4985]
https://github.com/kubernetes/kubernetes/issues/107619

I am not sure if it is a k3s or a kubernetes issue. Neither how to resolve it.

**Comment by brandond** [comment]
Are you sure that these errors are actually preventing you from starting pods? When I've seen these warnings in the past, it seems like it is actually trying to bind the ports twice.

**Comment by BlackTurtle123** [comment]
> Are you sure that these errors are actually preventing you from starting pods? When I've seen these warnings in the past, it seems like it is actually trying to bind the ports twice.

I see following issues/symptoms:

=> lot of bots are in restart/often fail
=> traefik shows the default example.com (even when cert-manager is installed and working)
=> these errors are showed more then once.

I had a feeling there would be some kind of ghost pods since the mounting also failed, but i really can't figure it out why this is happening

**Comment by BlackTurtle123** [comment]
The behavior went away and can't reproduce so this can be closed.
