### ISSUE TITLE
Being able to distinguish metrics from port 10250

### ISSUE THREAD

**Issue by flokli** [k3s-io/k3s#4987]
**Environmental Info:**
K3s Version:
```
k3s version v1.21.2+k3s1 (5a67e8dc)
go version go1.16.4
```

Node(s) CPU architecture, OS, and Version: 
```
Linux ns101338 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server, ~5 agents.

**Describe the bug:**
I'm using port 10250 (https-metrics) to collect k3s kubernetes metrics. This is done using grafana-agent-operator, and the kubelet service that it can manage.

It seems this endpoint includes apiserver, kube-controller-manager and kube-scheduler metrics, all in the same output.

I'm trying to get this into a format that's expected by the [generic kubernetes Grafana Dashboards](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14) and PrometheusRules.

They rely on a `job=` label, which can be one of `kube-controller-manager`, `kube-scheduler`, `kubelet`, `apiserver`, …

As all metrics are served in the same endpoint, I need a way to distinguish them.

In some cases, looking at the metric name allows figuring out which daemon this belongs to (`scheduler_`, `apiserver_`), but some metrics exist for different types of service.

For example, `kube-scheduler` exposes `rest_client_requests_total`, as well as `kube-controller-manager`.

**Expected behavior:**
Expose a job=… field in the combined metrics returned over that endpoint. That way, during scraping, one can simply keep the `job` label as it was returned.

Alternatively, individual metrics endpoint could be exposed via another metrics URL (/metrics/apiserver/…), and it'd be up to the one writing the scraping rules to set the `job` label accordingly.

**Comment by brandond** [comment]
K3s runs all the controllers in a single process, so the metrics for all the upstream components are commingled together due to their use of a single global metrics exporter. They don't have a job label because they are not run as pods. If you're looking for this level of separation, you might check out RKE2.

**Comment by flokli** [comment]
Urgh, and I assume there's no plans to use multiple instances of a metrics exporter to ever be able to split them and expose on separate endpoints?

**Comment by brandond** [comment]
That would require fairly extensive changes to the upstream codebase, something we're attempting to reduce.

**Comment by flokli** [comment]
Understandable, still a big bummer - this essentially means I can't really rely on any of the kubernetes dashboards and alerting rules with k3s :disappointed:
