### ISSUE TITLE
Move over k3os to k3s-io

### ISSUE THREAD

**Issue by mysticaltech** [k3s-io/k3s#4991]
Hey folks, k3s is amazing, and so is [k3os](https://github.com/rancher/k3os), for having used it, I can say that it's both easy to install and even easier to maintain, as the OS just upgrades itself and k3s automatically via the system upgrade controller. 

Since Rancher was acquired by SUSE, k3os has been put on the back burner, as an undesirable project, because duh, it does not use SUSE.

Please folks, it just would make total sense to move k3os under [k3s-io](https://github.com/k3s-io)'s wing, so that it stays alive. Many young projects like [kube-hetzner](https://github.com/kube-hetzner/kube-hetzner) depend on it. 

@ibuildthecloud @dweomer @brendandburns Tagging you here, because you probably can make this happen. Please! 🥺🙏

**Comment by chris93111** [comment]
+1 k3os has real added value

k3os under k3s-io 🙏

**Comment by mysticaltech** [comment]
Folks, relatively good [news](https://twitter.com/mysticaltech/status/1483724076950724609) from @dweomer, saying that the project is not completely abandoned and that some k3s releases are coming to k3os soon (but as a weekend project). And that the community could maintain it. 

IMHO it should really take refuge under the wing of [k3s-io](https://github.com/k3s-io), there are so many brilliant folks here, like @lavalamp, @brandond, @smarterclayton, @deads2k, @smarterclayton, @gmarek, @sttts, @caesarxuchao, @mikedanese, and many others! Please, folks, this is not an attempt to spam you, it is a call for help! Don't you think that [k3os](https://github.com/rancher/k3os), an OS custom built for k3s, and that runs in a maintenance-free fashion, should be hosted and maintained by k3s-io?

**k3os is pure magic because of the tight integration with k3s and the system upgrade controller**. It's just magic! Kube and the underlying nodes OS all stay fresh, secure, and always up-to-date, that was a dream come true for me personally and my tiny project [kube-hetzner](https://github.com/kube-hetzner/kube-hetzner). 

And I am sure that there are thousands of other projects that rely on it too! It has accumulated 2.9k stars, it's a very successful and useful project. Please do not let it die, I myself do not have the resources or knowledge to maintain it.

**Comment by mysticaltech** [comment]
The other solution would be to discover a flow to use a container OS like [Fedora CoreOS](https://getfedora.org/en/coreos?stream=stable), which has huge backing from Redhat. And figure out how to install k3s (the easy part) and automated OS upgrade (harder to coordinate drain and reboots), and finally figure out k3s upgrades (probably via the system upgrade controller). 

The beauty of k3os is that upgrades were all-in-one, which meant minimal disruption, and low cluster implementation complexity.

**Comment by mysticaltech** [comment]
Another alternative would be to use [OpenSuse MicroOS](https://en.opensuse.org/Portal:MicroOS), which piggybacks on OpenSuse Tumbleweed, and has a particularly interesting [transactional update](https://kubic.opensuse.org/documentation/transactional-update-guide/transactional-update.html) that could be leveraged to inform a tool like [kured](https://github.com/weaveworks/kured) to reboot nodes.

Then, installation of k3s and upgrade via the system upgrade controller should be doable too.

@ibuildthecloud @dweomer Rancher could maybe build a **k3os2** that would be based on OpenSuse MicroOS, and simplify all of the above! It would make all of our lives simpler! 🙏

**Comment by chalko** [comment]
What was the result of the bug.  Is k3os moving?

**Comment by mysticaltech** [comment]
@chalko Unless a miracle happens and folks start contributing to the project out of the blue, k3os is pretty much dead. 

OpenSuse MicroOS or Fedora CoreOS are now better options IMHO, they have huge backing and piggyback on the latest and greatest Linux kernels, and are also regularly patched and used by industry, so that's it for me. I will give a shot to MicroOS, as it integrates well with Kured to reboot nodes after transactional updates, and also should work well with system-upgrade-controller to update to keep k3s fresh and latest. Basically, we would get k3os functionality but in better!
