### ISSUE TITLE
k3s secrets-encrypt status is not able to connect to API not bound to 127.0.0.1

### ISSUE THREAD

**Issue by kriansa** [k3s-io/k3s#5006]
**Environmental Info:**
K3s Version: v1.23.1+k3s2 (a0cadcd3)

Node(s) CPU architecture, OS, and Version: Debian 11 - 5.10.0-10-amd64

Cluster Configuration: Single-node cluster

**Describe the bug:**
My K3S server is listening to a specific network interface (not wildcard 0.0.0.0 as default).

When we run `k3s secrets-encrypt status`, we get the error message:

```
FATA[0000] failed to get CA certs: Get "https://127.0.0.1:6443/cacerts": dial tcp 127.0.0.1:6443: connect: connection refused
```

**Steps To Reproduce:**

- Installed K3s with the following command:
```sh
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
```

Ensure you have this setting on `/etc/rancher/k3s/config.yaml` (or simply start k3s with --bind-address):

```yaml
bind-address: 192.168.1.1 # or whatever is your network ip
````

Then start it with

```sh
systemctl start k3s
```

Now run:

```sh
k3s secrets-encrypt status
```

**Comment by dereknola** [comment]
@kriansa Thanks for finding this. I sound have a fix out to master within the week. Its too late for this month's releases, so look out for the February releases with this fix.

**Comment by kriansa** [comment]
@dereknola I appreciate your quick input on this issue, better yet, coming up with a fix. Thanks!

**Comment by mdrahman-suse** [comment]
Reproduced in k3s v1.23.3+k3s1 single node cluster
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_VERSION=v1.23.3+k3s1 sh -
...
$ sudo k3s server --cluster-init --secrets-encryption --bind-address=<ip_address>
...
```
From another terminal, logged in to same server, ran the command and observed the error
```
$ sudo k3s secrets-encrypt status
FATA[0000] failed to get CA certs: Get "https://127.0.0.1:6443/cacerts": dial tcp 127.0.0.1:6443: connect: connection refused

$ sudo k3s secrets-encrypt status --server=https://<ip_address>:6443
Incorrect Usage: flag provided but not defined: -server

NAME:
   k3s secrets-encrypt status - Print current status of secrets encryption

USAGE:
   k3s secrets-encrypt status [command options] [arguments...]

OPTIONS:
   --data-dir value, -d value  (data) Folder to hold state default /var/lib/rancher/k3s or ${HOME}/.rancher/k3s if not root
   --token value, -t value     (cluster) Shared secret used to join a server or agent to a cluster [$K3S_TOKEN]

FATA[0000] flag provided but not defined: -server
```
Verified the fix in k3s master commit 4f36c82ff771543af6d6010ce41287cdd2f659e7
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_COMMIT=4f36c82ff771543af6d6010ce41287cdd2f659e7 sh -
...
$ sudo k3s server --cluster-init --secrets-encryption --bind-address=<ip_address>
...
```
From another terminal, logged in to same server, ran the command and still observed the error (@dereknola to confirm on the expected output)
```
$ sudo k3s secrets-encrypt status
FATA[0000] failed to get CA certs: Get "https://127.0.0.1:6443/cacerts": dial tcp 127.0.0.1:6443: connect: connection refused
```
But passing the server flag worked as expected
```
$ sudo k3s secrets-encrypt status --server=https://<ip_address>:6443
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```
Also not helper doc was found for the server flag

**Comment by dereknola** [comment]
@mdrahman-suse This is the expected output. To "fix" the issue you must use the `--server` flag.

**Comment by mdrahman-suse** [comment]
Verified in k3s with Release 1.23 on RC v1.23.4-rc1+k3s1 using the steps mentioned in https://github.com/k3s-io/k3s/issues/5006#issuecomment-1030262033 and observed the expected results. Also the helper doc was observed for the new `--server` flag
