### ISSUE TITLE
k3s-serving secret no update certificate on 1.22

### ISSUE THREAD

**Issue by chris93111** [k3s-io/k3s#5007]
Hello i expose the kubeapiserver with metallb on port 443 in front node, in 1.21 patching the secret k3s-serving for add ip of load balancer (metallb) work.
But in 1.22 patching has no effect, i tried rotate certificate but nothing

kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"listener.cattle.io/cn-10.208.6.35":"10.208.6.35"},"name":"k3s-serving","namespace":"kube-system"}}
    listener.cattle.io/cn-10.43.0.1: 10.43.0.1
    listener.cattle.io/cn-10.208.6.35: 10.208.6.35 #LB
    listener.cattle.io/cn-10.210.6.3: 10.210.6.3
    listener.cattle.io/cn-127.0.0.1: 127.0.0.1

[chris@~ ] $ kubectl get pods -A
Unable to connect to the server: x509: certificate is valid for 10.210.6.3, 10.43.0.1, 127.0.0.1, not 10.208.6.35
[chris@~ ]

**Steps To Reproduce:**
install k3s 1.22.5
patch k3s-serving secret
target ip on kubeconfig
try kubectl

**Comment by brandond** [comment]
The correct way to do this is to set the --tls-san parameter when starting the server. Directly patching the annotations on the secret has never been a documented way to add SANs to the cert.

**Comment by chris93111** [comment]
@brandond ok thanks , with --tls-san work
