### ISSUE TITLE
IPv6 masquerade NAT rules remain after uninstall k3s

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#5010]
Environmental Info:
K3s Version: v1.23.2-rc1+k3s1, 1.22.6-rc1+k3s1, 1.21.9-rc1+k3s1

Describe the bug:
When deploying k3s in dual-stack mode and IPv6 masquerade NAT rules are applied, k3s-uninstall.sh does not clean up the masquerade rules

Node(s) CPU architecture, OS, and Version: 
NA, Tested on Ubuntu

Cluster Configuration:
Single node configuration with k3s deployed in dual-stack mode

**Steps To Reproduce:**

- Install k3s in dual stack mode, apply IPv6 masquerade NAT rules to translate the pod ipv6 addresses
- Uninstall k3s using k3s-uninstall.sh
- Check iptables using

```
$ sudo ip6tables-save | grep MASQUERADE
-A POSTROUTING -s 2001:cafe:42::/56 ! -d ff00::/8 -j MASQUERADE --random-fully
-A POSTROUTING ! -s 2001:cafe:42::/56 -d 2001:cafe:42::/56 -j MASQUERADE --random-fully
```

**Expected behavior:**
All rules applied during installation should be removed at uninstall

**Actual behavior:**
Some ipv6 rules remain

**Backporting**
- [*] Needs backporting to older releases

**Comment by katran001** [comment]
The goal is to fix this in the next release for k3s. In the meantime, moving to next milestone

**Comment by ShylajaDevadiga** [comment]
Validated on k3s commit id on v1.23.3+k3s-e28be291 on dual stack mode, after uninstalling k3s no rules remain.
```
$ sudo ip6tables-save | grep MASQUERADE
$ 
```
