### ISSUE TITLE
[BUG] K3s CoreDNS terminates around every minute

### ISSUE THREAD

**Issue by IceeMC** [k3s-io/k3s#5030]
**Environmental Info:**
K3s Version: v1.23.1+k3s1

Node(s) CPU architecture, OS, and Version: x64, Linux, 20.04

Cluster Configuration: 3 masters

**Describe the bug:**
CoreDNS exists around every minute or so, causing massive DNS failures.

**Steps To Reproduce:**

- Installed K3s
- Setup Kubelocal DNS
- Wait until it exits

**Expected behavior:** CoreDNS to run indefinently until the current node goes under maintenance.

**Actual behavior:** CoreDNS exists gracefully every 30 seconds to 2 minutes, causing DNS failures.

**Additional context / logs:**
```
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
.:53
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[INFO] plugin/reload: Running configuration MD5 = 442b35f70385f5c97f2491a0ce8a27f6
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5 
[INFO] SIGTERM: Shutting down servers then terminating
```

![Gif](https://go.is-rocket.science/ffe0e9411d.gif)

The deployment files and configmap are the normal ones from when I originally deployed K3s a year ago.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by ii64** [comment]
I am experiencing this issue, how did you manage to get the issue fixed? It seem this only affect a Deployment with `coredns` set as its name, I tried to rename it to something else and it works just fine - no more SIGTERM (this is my current workaround).

So I am wondering if there's something else terminating the CoreDNS pod indeed every 30 seconds - Still haven't found the cause of it, the workaround works just fine but it leave me a question to the issue, still.

**Comment by cranberrysoft** [comment]
Same for me, coredns on my k3s are being restarted.  This is an issue as DNS is not stable and  I get errors in my apps while resolving hostnames
