### ISSUE TITLE
High CPU load + Large Database with KINE SQLite when running KNative Serving, Eventing + Camel K

### ISSUE THREAD

**Issue by crosscode-nl** [k3s-io/k3s#5033]
When running a workload with KNative Serving + Eventing + Camel K on our K3S with KINE/Sqlite installation we run into lots of problems. 

Our Sqlite database grows quickly (+/- 10 days) to 8GB and 20+GB write ahead log, also the CPU load of K3S increases, not that of the pods. When the write ahead log is too large it will not even start k3s anymore, probably because of a timeout. 

When investigating the issues it looks like the database is filled with hundreds of thousands of lease resources created by KNative components. 

When switching to a single node etcd node instead of KINE/Sqlite the problems disappear and with 5 snapshots and 5 write ahead logs which totals to about 400MB of data. 

Our K3S installation is: v1.22.3+k3s1

**Comment by brandond** [comment]
Can you try a newer release, one that includes https://github.com/k3s-io/kine/releases/tag/v0.8.1 - https://github.com/k3s-io/k3s/releases/tag/v1.22.5%2Bk3s1 or newer should do it.

**Comment by brandond** [comment]
I will also say that kine could probably handle leases a little better; at the moment each lease creates a timer goroutine that sleeps until the lease expires. High lease counts may require additional optimizations to kine.

**Comment by crosscode-nl** [comment]
I believe a never version might solve the WAL issues, but I don't think it will solve the lease issue. I can't switch back now since my customer does not want to change back. 

I wanted to raise attention regarding the hundreds of thousands of lease resources in the DB (8GB) when using knative eventing and serving in combination with Camel K. 

Out solution is using a single node etcd, which is lightweight enough for our usecase and makes k3s perform a lot better. Before that it was to the point of becoming unusable within hours after an installation dependending on the resources in the VM it was running on. 

Maybe there is bug with leases which could be distilled from this issue. If I have some spare time I might focus on leases and setup a test environment with a test container and see if I can reproduce the issues with newer versions of k3s and exposing the real problem.

**Comment by brandond** [comment]
On recent versions of k3s you can easily switch a single server from SQLite to etcd by simply adding the --cluster-init flag to the args. It will even migrate the data for you.
