### ISSUE TITLE
run k3s in docker with macvlan bridge, pod can't access network outside k3s

### ISSUE THREAD

**Issue by belerweb** [k3s-io/k3s#5039]
**Environmental Info:**
K3s Version: v1.19.7+k3s1/v1.23.3-k3s1

Node(s) CPU architecture, OS, and Version: 4.18.0-240.10.1.el8_3.x86_64

Cluster Configuration: 1 server

**Describe the bug:**

**Steps To Reproduce:**
A physical centos8 server with ip 192.168.1.2, gateway is 192.168.1.1, the server can access public network.
Install docker on it. Use macvlan create docker bridge network for docker containers.
Execute:
```
docker run --rm --name=k3s -itd --privileged --net=br0 rancher/k3s:v1.19.7-k3s1 server
```
The running k3s was assigned ip 192.168.1.3.
```docker exec -it k3s sh``` enter into k3s docker container.
```
# it works
ping 192.168.1.1
# it works
ping 114.114.114.114
```
```
/ # kubectl get pod --all-namespaces
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-7b4f8b595-gqr6l           1/1     Running     0          89s
kube-system   helm-install-traefik-nqjvn               0/1     Completed   0          90s
kube-system   local-path-provisioner-7ff9579c6-pk7gj   1/1     Running     0          89s
kube-system   svclb-traefik-b6v6g                      2/2     Running     0          45s
kube-system   traefik-5dd496474-828sm                  1/1     Running     0          45s
kube-system   coredns-66c464876b-54tzl                 1/1     Running     0          89s
```
Find a pod for test, for example: svclb-traefik-b6v6.

```kubectl exec -it svclb-traefik-b6v6g sh -n kube-system``` enter pod for test.
```
# it should work, but not
ping 192.168.1.1
# it should work, but not
ping 114.114.114.114
```

**Expected behavior:**
pod can access physical server network and public network.

**Actual behavior:**
pod can't access physical server network and public network.

**Additional context / logs:**

**Backporting**

- [*] Needs backporting to older releases

**Comment by manuelbuil** [comment]
What is the IP of the pod? Could it be that docker is creating iptables that block unexpected traffic, i.e. traffic that does not match the Docker CIDR? https://docs.docker.com/network/iptables/

**Comment by belerweb** [comment]
> 

10.42.0.*
