### ISSUE TITLE
Bundle a build Dockerfile tool.

### ISSUE THREAD

**Issue by cnmade** [k3s-io/k3s#5043]
If we have not installed docker, how to build docker image .
K3s can bundle a tool to build Docker image?

then we do not need any thirdparty tools go build Docker image from Dockerfile

**Comment by ChristianCiach** [comment]
This is not what you are asking for, but maybe this helps anyway: https://github.com/GoogleContainerTools/kaniko

**Comment by ChristianCiach** [comment]
I still hope that K3s will some day bundle nerdctl instead of ctr: https://github.com/k3s-io/k3s/issues/3279

With nerdctl you would be able to use `nerdctl build`.
