### ISSUE TITLE
Pinging inside container public domain results in wrong DNS queries

### ISSUE THREAD

**Issue by CiraciNicolo** [k3s-io/k3s#5044]
**Environmental Info:**
K3s Version: 
k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux hostname 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
Pinging public domain such as google.com results in DNS request with "svc.cluster.local" appended. 

<img width="1799" alt="Screenshot 2022-01-30 at 14 00 33" src="https://user-images.githubusercontent.com/910971/151700924-4e692de8-dce6-44ef-a4b4-2e3c2e8e1e86.png">

**Steps To Reproduce:**
- Installed K3s
- Run COREDNS mirrored-coredns-coredns:1.8.6 with this config
 ```.:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        hosts /etc/coredns/Nodes {
          reload 1s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

**Expected behavior:**
Pinging google.com inside a container should return google ip

**Actual behavior:**
root@dig:/# ping google.com
PING 825610.parkingcrew.net (75.2.81.221) 56(84) bytes of data.
64 bytes from a2e6b661ca0e4c4c4.awsglobalaccelerator.com (75.2.81.221): icmp_seq=1 ttl=120 time=1.23 ms
64 bytes from a2e6b661ca0e4c4c4.awsglobalaccelerator.com (75.2.81.221): icmp_seq=2 ttl=120 time=1.36 ms

**Comment by manuelbuil** [comment]
This is the default behaviour of linux. From `man resolv.conf`:
```
       search Search list for host-name lookup.
              By default, the search list contains one entry, the local domain name.  It is determined from the local hostname returned by gethostname(2); the local domain name is taken to be everything after  the  first  '.'.   Fi‐
              nally, if the hostname does not contain a '.', the root domain is assumed as the local domain name.

              This  may  be  changed  by listing the desired domain search path following the search keyword with spaces or tabs separating the names.  Resolver queries having fewer than ndots dots (default is 1) in them will be at‐
              tempted using each component of the search path in turn until a match is found.  For environments with multiple subdomains please read options ndots:n below to avoid man-in-the-middle attacks  and  unnecessary  traffic
              for the root-dns-servers.  Note that this process may be slow and will generate a lot of network traffic if the servers for the listed domains are not local, and that queries will time out if no server is available for
              one of the domains.
```
It will generate different FQDNs with the different search domains until it fins one that works

**Comment by CiraciNicolo** [comment]
The issue was caused by a rogue DNS registration; before the issue the search domain was returning NXDOMAIN so no "external" DNS queries were followed.
