### ISSUE TITLE
Bump containerd and stargz-snapshotter

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5066]
Bump stargz-snapshotter to v0.11.0 from v0.10.1
Bump containerd

**Comment by rancher-max** [comment]
[These docs](https://rancher.com/docs/k3s/latest/en/advanced/#enabling-lazy-pulling-of-estargz-experimental) should also help with how to use stargz in k3s

**Comment by ShylajaDevadiga** [comment]
Validated above on k3s version v1.23.4-rc1+k3s1 (43b1cb48)
```
ec2-user@ip-172-31-0-189:~> k3s -v
k3s version v1.23.4-rc1+k3s1 (43b1cb48)
go version go1.17.5
ec2-user@ip-172-31-0-189:~> sudo grep snapshotter /var/lib/rancher/k3s/agent/etc/containerd/config.toml
  snapshotter = "stargz"
ec2-user@ip-172-31-0-189:~>
