### ISSUE TITLE
Auto-Deploying Manifests Ordering

### ISSUE THREAD

**Issue by retr0h** [k3s-io/k3s#5081]
**Environmental Info:**
K3s Version: 

v1.21.1+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux primary 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Primarily using with k3d

**Describe the bug:**

[Auto-Deploying](https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests) manifests does not account for ordering. 

Specifically, we deploy CRDs such as Prometheus, Nginx Ingress Webhooks, etc... once these are deployed successfully, we can deploy the remaining manifests.  Because of this, we use an install script, which I was hoping to avoid.

```
 26     kubectl apply -f "${SCRIPT_DIR}/kubernetes/crd.yaml"
 25
 23     kubectl delete configmap data-plane-cm -n "${NAMESPACE}" || true
 22     kubectl create configmap data-plane-cm --from-literal=INTERFACE="${monitoring_interface}" -n "${NAMESPACE}"
 21     kubectl apply -f "${SCRIPT_DIR}/kubernetes/bootstrap.yaml"
 20
 18     kubectl wait --namespace ingress-nginx \
 17         --for=condition=complete job \
 16         --selector=app.kubernetes.io/component=admission-webhook \
 15         --selector=app.kubernetes.io/instance=ingress-nginx \
 14         --timeout=300s
 13
 11     kubectl wait --namespace ${NAMESPACE} \
 10         --for=condition=complete job \
  9         --selector=xxx/app=bootstrap \
  8         --timeout=180s
  7
  5     kubectl wait --namespace ingress-nginx \
  4         --for=condition=ready pod \
  3         --selector=app.kubernetes.io/component=controller \
  2         --timeout=180s
```

If I do not perform the above, deployments can fail due to webhooks not being ready and requires re-running kube apply again. 

**Steps To Reproduce:**

Deploy ingress-nginx controller and immediately deploy an ingress object.

**Expected behavior:**

Ability to wait on arbitrary resource creation.

**Comment by brandond** [comment]
There is no inherent order to the chart installation; they are all run as independent parallel jobs. Chart installations are retried if they fail; we in fact rely on this for installation of the Traefik chart that we package - it is split into a CRD chart, and an application chart. The application chart usually fails to install the first time, and then succeeds on retry once the CRD chart has been installed.

**Comment by retr0h** [comment]
Oh, that's good to know.  I didn't realize it would retry.  So k3s retries manifests continually until they succeed?

**Comment by bensta** [comment]
Hi all, a quick question regarding that: 
I am trying to customize my traefik helm values following the official documentation: https://rancher.com/docs/k3s/latest/en/helm/
- I created a file named traefik-config.yaml in /var/lib/rancher/k3s/server/manifests on the master node
- I expected, that this will be applied automatically by k3s (at the very least on reboot) and merged with the k3s default helm values for traefik 
- I rebooted my master node, but the config is not applied
- When I manually apply the file, all works as expected

Maybe the default traefik.yaml file is applied after my custom file and hence it is overwritten? Any other reason why it is not applied properly?

**Comment by brandond** [comment]
I'm not aware of any issues with auto-deploying manifests not being read. You should see events in the K3s service log, as well as an AddOn Custom Resource created in the kube-system namespace with a name that matches the name of the file you created. Can you check for those?
