### ISSUE TITLE
Pod CPU throttling even when limits aren't reached

### ISSUE THREAD

**Issue by iosifnicolae2** [k3s-io/k3s#5085]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux dedicated-master-1 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, one master, 3 workers

**Describe the bug:**
The pods are throttled even when the limits aren't reached.

**Steps To Reproduce:**
- create a container with a 200 mili CPU limit, then make some load inside the pod until 100 mili CPU units are consumed.

**Expected behavior:**
The CPU should be throttled when the usage is close to the CPU limit. 

**Actual behavior:**
The CPU is being throttled when the CPU usage is 50% from the target limit, especially when the target limit is <= 1000 milis.

**Additional context / logs:**
![image](https://user-images.githubusercontent.com/7108834/152821015-3f233ce0-4d00-4904-aca1-f31c99b76948.png)

**Backporting**
I don't know if this issue needs backporting.

**Comment by brandond** [comment]
K3s does not modify upstream's behavior at all with regards to resource allocation. What you're probably running into has something to do with how the kernel allocates time slices based on CPU allocations, see:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run
