### ISSUE TITLE
[CI] Fix Vagrant centos:8 box

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#5091]
**Describe the bug:**

Our CI is failing in the smoke test that uses centos-8. The error is:

`install-centos-8: Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

This is expected as centos-8 is EOL

A potential solution could be this one : https://github.com/rancher/rke2-packaging/pull/22/files#diff-04d83d78a554aeff1435508ff7b64f91b4d949907c1fd55c956e09dc2b5e1195R3

**Steps To Reproduce:**

Check master CI, e.g. https://github.com/k3s-io/k3s/runs/5091108013?check_suite_focus=true

**Expected behavior:**

smoke test runs correctly on centos-8

**Actual behavior:**

smoke test fails on centos-8

**Comment by jossemargt-3pillar** [comment]
Fixed on #5094 and backported to release-1.22 on #5100
