### ISSUE TITLE
Unable to ping between pods. New containers don't get added to coreDNS

### ISSUE THREAD

**Issue by yurividal** [k3s-io/k3s#5093]
k3s 1.21.7 (also tried 1.19.5)

Rancher version: 2.6.3
Installation option : Helm Chart
Host: Ubuntu 20.04 LTS

I have some old containers, from which i am able to ping between them.
In workspace1 i have containerA and containerB. I am able to ping "ping containerA" from containerB and vice versa.
But, with the new containers that i create, I am having issues. If i deploy containerC in that same namespace, i am able to "ping containerA" and "ping containerB" from it, but, from A and B i am NOT able to ping the containerC. I get "temporary failure on name resolution". I have also tried using the full FQDN containerC.namespace1.svc.cluster.local but this also fails to resolve.
I am able to ping if i use the pod IP.

I have checked the coreDNS logs, and it seems that these new pods are not being added to the coreDNS table. Is this a known bug? Is there a way to manually add an entry as a workaround?

I have started 2 identical busybox containers with the follwing command:
`kubectl run --namespace=default -it --rm --restart=Never busybox --image=busybox:1.28 -- /bin/sh`

This is the results from busybox2:

````
/ # nslookup busybox2
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local`

Name:      busybox2
Address 1: 10.42.0.91 busybox2

/ # nslookup busybox
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local 


nslookup: can't resolve 'busybox'


/ # nslookup www.google.com
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      www.google.com
Address 1: 2a00:1450:4009:81d::2004 lhr25s31-in-x04.1e100.net
Address 2: 172.217.16.228 mad08s04-in-f4.1e100.net`
````

And this is my coreDNS log:

````
(successfull)

[INFO] 10.42.0.91:54674 - 2 "PTR IN 10.0.43.10.in-addr.arpa. udp 41 false 512" NOERROR qr,aa,rd 116 0.000213745s


(error)

[INFO] 10.42.0.91:48163 - 2 "PTR IN 10.0.43.10.in-addr.arpa. udp 41 false 512" NOERROR qr,aa,rd 116 0.000154475s
[INFO] 10.42.0.91:37591 - 3 "AAAA IN . udp 51 false 512" NXDOMAIN qr,aa,rd 144 0.00057097s
[INFO] 10.42.0.91:47398 - 4 "AAAA IN busybox.svc.cluster.local. udp 43 false 512" NXDOMAIN qr,aa,rd 136 0.000173237s
[INFO] 10.42.0.91:39423 - 5 "AAAA IN busybox.cluster.local. udp 39 false 512" NXDOMAIN qr,aa,rd 132 0.000365971s
[INFO] 10.42.0.91:44506 - 6 "AAAA IN busybox. udp 25 false 512" NXDOMAIN qr,rd,ra,ad 100 0.006584385s
[INFO] 10.42.0.91:60544 - 7 "A IN busybox.default.svc.cluster.local. udp 51 false 512" NXDOMAIN qr,aa,rd 144 0.000323953s
[INFO] 10.42.0.91:51239 - 8 "A IN busybox.svc.cluster.local. udp 43 false 512" NXDOMAIN qr,aa,rd 136 0.000491898s
[INFO] 10.42.0.91:51651 - 9 "A IN busybox.cluster.local. udp 39 false 512" NXDOMAIN qr,aa,rd 132 0.000145048s
[INFO] 10.42.0.91:49942 - 10 "A IN busybox. udp 25 false 512" NXDOMAIN qr,rd,ra,ad 100 0.00610748s
````

**Comment by brandond** [comment]
You might check out the upstream docs on what is expected to resolve within clusters. I didn't see you say anything about creating a service for the busybox pods, so I would not expect to find a service record (busybox.default.svc) for them.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by yurividal** [comment]
What kind of service are needed if all i need is pods for pods to be able to communicate with each other within a same namespace? Also, why do my older pods (created with older versions of Rancher) work just fine without having to create any services?

**Comment by brandond** [comment]
This behavior isn't governed by Rancher or K3s version. It is specified as part of the Kubernetes DNS standard, which is covered in that document and at https://github.com/kubernetes/dns/blob/master/docs/specification.md

**Comment by brandond** [comment]
I think the behavior you're looking for is covered in this paragraph of the docs:

> If there exists a headless service in the same namespace as the pod and with the same name as the subdomain, the cluster's DNS Server also returns an A or AAAA record for the Pod's fully qualified hostname. For example, given a Pod with the hostname set to "busybox-1" and the subdomain set to "default-subdomain", and a headless Service named "default-subdomain" in the same namespace, the pod will see its own FQDN as "busybox-1.default-subdomain.my-namespace.svc.cluster-domain.example". DNS serves an A or AAAA record at that name, pointing to the Pod's IP. Both pods "busybox1" and "busybox2" can have their distinct A or AAAA records.

**Comment by yurividal** [comment]
Acording to this documentation "In summary, a pod in the test namespace can successfully resolve either data.prod or data.prod.svc.cluster.local" 
This is NOT the case, as seen on my initial message. 
Even if I use the entire FQDN like the documentation exeplifies, DNS Resolution still fails.
````
/ # nslookup busybox1.default
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'busybox1.default'
/ # 
/ # 
/ # 
/ # nslookup busybox1.default.svc.cluster.local
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'busybox1.default.svc.cluster.local'
/ # 
````

**Comment by brandond** [comment]
You didn't mention creating a service, only pods. Did you create a headless service matching the pod subdomain, and set both the subdomain and hostname on the pod spec? This is all covered in the core Kubernetes docs as standard behavior.

**Comment by yurividal** [comment]
I dont understand....
These are screenshots of a workload created the same exact way as the one I am trying to create now.

![image](https://user-images.githubusercontent.com/8555749/153088561-29699f73-1b77-4bd4-8509-ac06c82b34f1.png)
![image](https://user-images.githubusercontent.com/8555749/153088563-0401c8a4-9f5a-464b-8638-db6a6ab54f7b.png)


This workload, created with an older version of Rancher, can be reached by other pods in the same namespace by simply doing "ping influxdb"

When I create another workload, with the SAME EXACT settings, i am unable to ping it by its name - it's not resolved.

**Comment by brandond** [comment]
It sounds like you might want to take that question to https://github.com/rancher/rancher or the Rancher users slack. Workloads in Rancher bundle up several different components (pods, services, etc), and the behavior associated with the Workload creation workflow may have changed across versions. Either way, it's Rancher specific behavior, not related to CoreDNS, K3s, or Kubernetes itself.

**Comment by brandond** [comment]
In particular, what I think you're seeing is described here: https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/service-discovery/

> For every workload (with at least one port configured) created, a complementing Service Discovery entry is created. This Service Discovery entry enables DNS resolution for the workload’s pods using the following naming convention: <workload>.<namespace>.svc.cluster.local.

**Comment by yurividal** [comment]
Thank you!
Aparently, this is the "new" way in rancher to creaste a headless service:

![image](https://user-images.githubusercontent.com/8555749/153091414-ea1a6742-4add-40e1-b3da-b160c01d6345.png)

It works now.

**Comment by brandond** [comment]
Right, if you compare the 2.5 and 2.6 docs, the `(with at least one port configured)` bit was added in 2.6. So the Rancher behavior has indeed changed across versions.
