### ISSUE TITLE
How to remove "orphaned" agent from database?

### ISSUE THREAD

**Issue by exocode** [k3s-io/k3s#5112]
**Environmental Info:**
K3s Version: 
```
bash-5.0# k3s -v
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

```
Node(s) CPU architecture, OS, and Version: 
```
bash-5.0# uname -a
Linux k3s-control-plane-0 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 GNU/Linux
```
Cluster Configuration:
```
3 control-planes 
6 nodes
```

**Describe the bug:**

One of my nodes died because of too high CPU usage.
I had to delete it manually in my provider UI (Hetzner).
After that I reapplied my Terraform script (I use this one: https://github.com/kube-hetzner/kube-hetzner)

Somehow my "agent-3"-node is not able to provisioned anymore.
I can provision any agent (agent-0, agent-1, agent-2, agent-4, agent-5, agent-6, )
EXCEPT agent-3. So my thought was, that somewhere k3s must know names of nodes. 
Is it possible that my "shutdown" of my agent-3 is still left somewhere in a database?

**Steps To Reproduce:**
I dont know how to reproduce. I've created an issue with all logfiles at the Terraform script repo, but I assume it's a k3s issue.

- Installed K3s: 

**Expected behavior:**
Any agent should provision properly

**Actual behavior:**
All agents are provisioned properly EXCEPT a node called "agent-3"

**Additional context / logs:**
I do not wanna overfill this issue, all logs are described here.
https://github.com/kube-hetzner/kube-hetzner/issues/59

- could it be, that the "agent-3" name is in any database of k3s?
- if yes, how can I remove that orphaned entry

Maybe someone can point me in the right direction. 

Thank you

**Comment by brandond** [comment]
Have you tried `kubectl get node` to see the nodes listed in the cluster, and `kubectl delete node` to remove the one you terminated?

**Comment by exocode** [comment]
In the meantime I deleted the whole cluster, so it's not possible anymore to reproduce the issue.
