### ISSUE TITLE
[release-1.22] k3s server --disable traefik does not correctly remove existing Traefik

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5114]
Backport fix to branch **release-1.22**:
* https://github.com/k3s-io/k3s/issues/5103

**Comment by rancher-max** [comment]
#### Validated using `release-1.22` branch commitid `efe99dc0fac32a4c79aec99b945350719e6e5aee`

- Started k3s without disabling anything. Edited the config.yaml to disable traefik and restarted k3s. It was properly removed from the manifests folder and disabled.
- Using the same setup as above, I then edited config.yaml to re-enable traefik. This re-enabled successfully after restarting k3s.
- Using the same setup, I then edited the config.yaml to disable both traefik and coredns. Both disabled successfully after restarting k3s. 

- I also attempted this in a multi-server-node setup. I did not disable anything on any of the server nodes when first running k3s, then I disabled on only one of the server nodes and restarted k3s. The disabled services stopped running in the cluster. However, after restarting the second node's k3s service (still without the config.yaml updated to disable anything) the services restarted. **These config disable params must match on all nodes before restarting the k3s process when performing this disable flow.**

**Comment by brandond** [comment]
Correct, if you don't disable it on all the nodes, it'll come back when any of the nodes without it disabled are restarted.
