### ISSUE TITLE
K3S fails to start due to expired certificate

### ISSUE THREAD

**Issue by edita-timo** [k3s-io/k3s#5120]
**Environmental Info:**
K3s Version: 

k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux server.name 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Cluster running 1 master and 2 worker nodes each CentOS 7

**Describe the bug:**

The cluster fails to rotate certificates causing the cluster to stop functioning.

**Steps To Reproduce:**

- Installed K3s: 
```
         /usr/local/bin/k3s server \
         --disable-cloud-controller \
         --datastore-endpoint='postgres://{{ k3s_db_username }}:{{ k3s_db_password }}@{{ k3s_db_conn_string }}' \
         --datastore-cafile=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
         --no-deploy traefik
```
  
**Expected behavior:**

The k3s service should start and function normally with certificates rotated automatically as stated in documentation.

**Actual behavior:**

The k3s server fails to start due to expired certificate.

**Additional context / logs:**

```
Feb 14 08:14:01 server.com k3s[13440]: time="2022-02-14T08:14:01+02:00" level=info msg="Starting k3s v1.22.5+k3s1 (405bf79d)"
Feb 14 08:14:01 server.com k3s[13440]: time="2022-02-14T08:14:01+02:00" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: x509: certificate has expired or is not yet valid: current time 2022-02-14T08:24:08+02:00 is after 2022-01-31T10:58:04Z"
Feb 14 08:14:01 server.com systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Feb 14 08:14:01 server.com systemd[1]: Failed to start Lightweight Kubernetes.
Feb 14 08:14:01 server.com systemd[1]: Unit k3s.service entered failed state.
Feb 14 08:14:01 server.com systemd[1]: k3s.service failed.
```

The server is updated and restarted at least once a month so there would have been plenty of opportunities for k3s to renew certificates.

I tried to manually rotate certificates with "/usr/local/bin/k3s certificate rotate" and it seems to rotate all other certs besides the disabled cloud-controller one in tls directory:
```
# for crt in *.crt; do printf '%s: %s\n' "$(date --date="$(openssl x509 -enddate -noout -in "$crt"|cut -d= -f 2)" --iso-8601)" "$crt"; done | sort
2021-12-22: client-cloud-controller.crt
2030-02-21: client-ca.crt
2030-02-21: request-header-ca.crt
2030-02-21: server-ca.crt
```

I also tested by stopping k3s, chronyd and setting clock back and starting k3s. This allowed to start the k3s and it seemed to rotate some certs. After stopping k3s and restoring correct time the k3s fails to start with same error:
```
# date 120110102021
Wed Dec  1 10:10:00 EET 2021
# systemctl start k3s
# for crt in *.crt; do printf '%s: %s\n' "$(date --date="$(openssl x509 -enddate -noout -in "$crt"|cut -d= -f 2)" --iso-8601)" "$crt"; done | sort
2021-12-22: client-cloud-controller.crt
2022-12-01: client-admin.crt
2022-12-01: client-auth-proxy.crt
2022-12-01: client-controller.crt
2022-12-01: client-k3s-cloud-controller.crt
2022-12-01: client-k3s-controller.crt
2022-12-01: client-kube-apiserver.crt
2022-12-01: client-kube-proxy.crt
2022-12-01: client-scheduler.crt
2022-12-01: serving-kube-apiserver.crt
2030-02-21: client-ca.crt
2030-02-21: request-header-ca.crt
2030-02-21: server-ca.crt
# systemctl stop k3s
# date 021408392022
Mon Feb 14 08:39:00 EET 2022
# systemctl start chronyd
# date
Mon Feb 14 08:39:10 EET 2022
# date
Mon Feb 14 08:40:23 EET 2022
# date
Mon Feb 14 08:40:25 EET 2022
# systemctl start k3s
Job for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details.
# journalctl -u k3s -e | tail -5
Feb 14 08:42:37 server.com k3s[22097]: time="2022-02-14T08:42:37+02:00" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: x509: certificate has expired or is not yet valid: current time 2022-02-14T08:42:37+02:00 is after 2022-01-31T10:58:04Z"
Feb 14 08:42:37 server.com systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Feb 14 08:42:37 server.com systemd[1]: Failed to start Lightweight Kubernetes.
Feb 14 08:42:37 server.com systemd[1]: Unit k3s.service entered failed state.
Feb 14 08:42:37 server.com systemd[1]: k3s.service failed.
```

What certificate is giving the 2022-01-31T10:58:04Z expiration error and how it should be fixed?

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> Feb 14 08:14:01 server.com k3s[13440]: time="2022-02-14T08:14:01+02:00" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: x509: certificate has expired or is not yet valid: current time 2022-02-14T08:24:08+02:00 is after 2022-01-31T10:58:04Z"

The certificate on your database server is expired. I'm not sure how k3s would be expected to rotate this.

**Comment by edita-timo** [comment]
Ah, forgot about those and searching web for the issue lead to wrong places.

Could the error message be extended to be more explicit so it would say "data store cert expired" or something similar?

**Comment by brandond** [comment]
The `creating storage endpoint: building kine` bits do make it clear that it's related to the datastore, but it could probably be more clear for folks that haven't read the docs enough to know what kine is.

**Comment by edita-timo** [comment]
I have browsed the k3s docs occasionally but I don't have a clue what kine is. Where is it documented?

**Comment by brandond** [comment]
kine is https://github.com/k3s-io/kine - the package that implements all the non-etcd storage backends, including the default single-node sqlite storage. https://rancher.com/docs/k3s/latest/en/installation/datastore/

**Comment by edita-timo** [comment]
So it seems the whole kine is undocumented. The datastore page could have small section about it, something like "Kine is used to implement etcd-like abstraction for non-etcd storage like databases." with link to the project. This would help give a pointer that kine is part of k3s and it deals with the datastores.
