### ISSUE TITLE
Btrfs snapshotter causing high cpu usage because of stats collection

### ISSUE THREAD

**Issue by mnorrsken** [k3s-io/k3s#5121]
**Environmental Info:**
K3s Version: 

k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
`Linux bespin 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`

Cluster Configuration:
1 server 3 agents

**Describe the bug:**
Using the btrfs snapshotter causes high cpu usage because of containerd snapshot stats collection every 10 seconds. Btrfs calculates used size by walking the complete directory.

**Steps To Reproduce:**
Enable the btrfs snapshotter on a system with constrained io and/or cpu.

**Expected behavior:**
system load low when idle < 0.1

**Actual behavior:**
System load at 2-3

**Additional context / logs:**
This problem can be mitigated by reducing snapshot stats collection in containerd configuration. Default interval is 10 (seconds). I have incresed this to 900 to reduce cpu/io usage. Even on high-performance systems it seems like a waste of cycles to collect snapshot stats every 10 seconds. I added the following to the containerd config.toml.tmpl:
```
...
[plugins.cri]
  stats_collect_period = 900
...
```

It would be nice if there was a less clunky way to edit this value, I can see two options that would help:
* add a containerd_stats_collect_period flag to k3s
* or change the default value when btrfs snapshotter is used (900 seems to be a good compromise between 10seconds and 2 hours as suggested by https://github.com/containerd/containerd/issues/4217 

Note:
I enabled quotas but it didnt seem to help, or maybe a little. Also I would say this is more of a problem in the btrfs snapshotter, so marking this as a k3s bug is maybe not correct.

**Comment by mnorrsken** [comment]
Another note, I enabled quotas but it didnt seem to help, or maybe a little. Also I would say this is more of a problem in the btrfs snapshotter, so marking this as a k3s bug is maybe not correct.

**Comment by mnorrsken** [comment]
Applying this fix reduces read io from 70MB/sec to 660KB/sec on my controller host and reduces cpu usage from 34% to 7%

**Comment by brandond** [comment]
This sounds like something that should be reported upstream to Containerd? We're not customizing any of this behavior; it's just how containerd and the btrfs snapshotter are comes configured by default.

**Comment by mnorrsken** [comment]
It propably is an upstream issue, I'll close this one and do some more testing with my amd64 server, then report it to containerd.
