### ISSUE TITLE
Running `k3s server` with custom entrypoint raises error "Failed to start ContainerManager" 

### ISSUE THREAD

**Issue by picarro-msimpson** [k3s-io/k3s#5123]
# Environmental Info:
## K3s Version: 
Docker image: `rancher/k3s:v1.23.3-k3s1`
``` $k3s -v
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5
```

## Node(s) CPU architecture, OS, and Version:
Host machine is Pop_OS 21.10, but I am starting the k3s server and agent via Docker container. 
``` shell
$ uname -a
Linux pop-os 5.15.15-76051515-generic #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U x86_64 x86_64 x86_64 GNU/Linux
```
Docker info:
``` shell
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 48
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.15-76051515-generic
 Operating System: Pop!_OS 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.99GiB
 Name: pop-os
 ID: 6BNL:KLZA:7MGB:RW4U:ISTM:THWW:5MLZ:CDGP:O6RG:IDA5:QY4O:ZMMH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
## Cluster Configuration:

One server and one agent both on the same machine. Using the `docker-compose.yml` based off of the [example](https://github.com/k3s-io/k3s/blob/master/docker-compose.yml) in the root of this repo.

# Describe the bug:
We want to update the entrypoint of the k3s server docker container to apply our yaml files after the k3s server has started up. We did this by mounting a directory with a custom start script `start_server`, changed the working directory to this mounted volume, and changed the docker-compose entrypoint and command to `/bin/sh`, `-c ./start_server`. The `start_server` script will apply yamls in a background process while `k3s server` is ran in the foreground. However, starting the container like this causes the following error:
```
...
E0214 18:25:05.208619       7 kubelet.go:2001] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
E0214 18:25:05.264780       7 node_container_manager_linux.go:61] "Failed to create cgroup" err="cannot enter cgroupv2 \"/sys/fs/cgroup/kubepods\" with domain controllers -- it is in an invalid state" cgroupName=[kubepods]
W0214 18:25:05.264780       7 watcher.go:93] Error while processing event ("/sys/fs/cgroup/kubepods": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/kubepods: no such file or directory
E0214 18:25:05.264801       7 kubelet.go:1431] "Failed to start ContainerManager" err="cannot enter cgroupv2 \"/sys/fs/cgroup/kubepods\" with domain controllers -- it is in an invalid state"
```

Removing our custom logic from the `start_server` script so it just calls `k3s server` in the foreground still causes this same error.

## Steps To Reproduce:

- Get the `docker-compose.yml` file from [here](https://github.com/k3s-io/k3s/blob/master/docker-compose.yml).
- Create an entrypoint script on the host machine, e.g. `~/temp/start_server`.
  - The contents of this file should be:
``` shell
#!/bin/sh
k3s server
```
  - Make this file executable, `chmod +x ~/temp/start_server`.
- Add an entrypoint, change the command, and mount the volume in the `server` service in the `docker-compose.yml` file:
``` yaml
...
server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    entrypoint: /bin/sh
    command: "-c ./start_server"
    working_dir: /home/temp
    ...
    volumes:
       - k3s-server:/var/lib/rancher/k3s
       # This is just so that we get the kubeconfig file out
       - .:/output
       - ~/temp:/home/temp
```
- Open a terminal in the directory with the `docker-compose.yml` file, and run `docker-compose up`.

## Expected behavior:

K3s server starts like normal from custom entrypoint.

## Actual behavior:

K3s server fails to start.

## Additional context / logs:

I saw this error had come up in the past https://github.com/k3s-io/k3s/issues/4085. Docker is setup to use cgroupv2 via systemd, as seen from my `docker info` output from above. Running the command from that issue gives me the same output:
``` shell
$ stat -fc %T /sys/fs/cgroup/       
cgroup2fs
```
I also saw this error about Pop_OS! 21.10 https://github.com/k3s-io/k3s/issues/4783. However I dont get this problem if I dont have a custom entrypoint. I am able to get the k3s server to start if I remove the `entrypoint` from the `docker-compose` file, and also change the `command` back to just `server`. My volumes still apply and I am able to them exec into the running container and apply my custom yaml files manually without problem.

This method of changing the entrypoint was working for me on PopOS 21.04. I have been getting these errors since upgrading to 21.10, kernel 5.15.15-76051515-generic.

## Backporting

I have tried this on an older version of `rancher/k3s:v1.21.3+k3s1`, and I still get the same problem.

**Comment by brandond** [comment]
K3s needs to be pid 1 in the container in order to evacuate the root cgroup for cgroupv2 to function properly. If you are going to use an entrypoint script to act as pid 1, you need to have your entrypoint evacuate the root cgroup, as k3d does: https://github.com/k3d-io/k3d/blob/main/pkg/types/fixes/assets/k3d-entrypoint-cgroupv2.sh

**Comment by picarro-msimpson** [comment]
@brandond This worked, thank you!

**Comment by brandond** [comment]
Although now that I read closer:
> The start_server script will apply yamls in a background process 

You know you can just dump files into `/var/lib/rancher/k3s/server/manifests` and K3s will apply them for you, right? You can even just mount a host path into a subdirectory of that path and it'll apply them for you from there.

**Comment by picarro-msimpson** [comment]
I did not know that, I'll have to try it out. Is that a feature specific to `k3s`?

**Comment by brandond** [comment]
K3s and RKE2.

**Comment by picarro-msimpson** [comment]
That's super cool. I can see how that can be useful, however our implementation can't leverage that. We have some logic in the `start_server` script which populates values in various `.yaml` files with environment variables. Not sure yet if using Helm would solve this where we could use the automatically deploying manifests feature with multiple profiles for our different secret values, however I would need to look into that further.

**Comment by brandond** [comment]
If you wanted to do it a more Kubernetes-native way, you could probably refactor your script to run as a Job within the cluster that mounted the manifests directory on the host (container) and templated the files into there. That way all you'd need to do to extend the K3s image is just copy in a manifest to kick off that job.

**Comment by picarro-msimpson** [comment]
I can see that being a cleaner solution instead of having a custom entrypoint. K3S is definitely helping us with local microservice development, so coming up with more kubernetes native ways of doing things is way easier to maintain.

Thanks for the advice!

**Comment by mickours** [comment]
I just hit this issue with a custom entrypoint and k3s v1.25. I had trouble finding the script that finally fix it, thanks for the link! Putting it again here, just in case:
https://github.com/k3d-io/k3d/blob/main/pkg/types/fixes/assets/k3d-entrypoint-cgroupv2.sh

Maybe it should be added to the advanced docker section here: https://docs.k3s.io/advanced#running-k3s-in-docker

**Comment by brandond** [comment]
Yeah, it could probably use documenting somewhere. I would in general recommend against wrapping k3s with another entrypoint though, in favor of just mounting a manifest to do what you need.
