### ISSUE TITLE
Add -o / --output flag to secrets-encrypt status and support JSON

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5138]
**Is your feature request related to a problem? Please describe.**

For a better test integration the output from the `secrets-encrypt status` command have the option of JSON output.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by VestigeJ** [comment]
**Validated using COMMIT=44c53743dd27bce9422ebdbd59c34b7359446c95**

$ k3s -v
```
k3s version v1.23.4+k3s-44c53743 (44c53743)
go version go1.17.5
```

$ sudo k3s secrets-encrypt status
```
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```

$ sudo k3s secrets-encrypt status -o json
```
{
        "stage": "start",
        "activekey": "aescbckey",
        "enable": true,
        "hashmatch": true
}
```
