### ISSUE TITLE
Secrets encryption rotation does not work when upgrading from older K3s versions.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5139]
**Environmental Info:**
K3s Version: 

Any K3s version before secrets-encryption rotation was introduced (I am using v1.22.4+k3s1 as an example)

Cluster Configuration:

Single server
**Describe the bug:**

Upon upgrade the secrets encryption subcommand will not work and reports the error:
```
# k3s secrets-encrypt status
FATA[0000] https://127.0.0.1:6443/v1-k3s/encrypt/status: 500 Internal Server Error
```
With the server logs showing:
```
secrets-encrypt-60217: invalid annotation  found on node server-0"
```
**Steps To Reproduce:**

- Install "pre encryption rotation" version of K3s v1.22.4+k3s1
- Start k3s with `--secrets-encryption`
- Stop server
- Upgrade to version with rotation v1.22.6+k3s1
- Start server
- Try and run `k3s secrets-encrypt status`  

**Expected behavior:**

Status and all other secrets-encrypt commands should work as expected.

**Actual behavior:**

All commands return a 500 Internal server error.
**Additional context / logs:**

This is caused by a missing encryption-hash.json file that has been added and was not present in older K3s versions.
Manual work around for other users that can't upgrade (again) but run into this problem:
```
# On all server nodes repeat this process
# Generate the file
echo "start-$(sha256sum /var/lib/rancher/k3s/server/cred/encryption-config.json | cut -d ' ' -f1)" >> /var/lib/rancher/k3s/server/cred/encryption-state.json
# Update the annotation
kubectl annotate no <NODE_NAME> k3s.io/encryption-config-hash=$(cat /var/lib/rancher/k3s/server/cred/encryption-state.json) --overwrite
```

**Backporting**

- [X] Needs backporting to older releases

**Comment by mdrahman-suse** [comment]
**Reproduced** the issue following the steps mentioned on here: https://github.com/k3s-io/k3s/issues/5139#issue-1141976793

**Verified** the fix is k3s on master branch with commit 3531df3f31b65b6c9f74979bbf1e347145a92635

After upgrading, observed the response below and NO 500 internal server error

```
$ k3s -v
k3s version v1.23.4+k3s-3531df3f (3531df3f)
go version go1.17.5
$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```
