### ISSUE TITLE
insecure network interface

### ISSUE THREAD

**Issue by gfrankliu** [k3s-io/k3s#5142]
I have multiple network interfaces on the host. One of them is connected to an insecure network, so I have existing iptable rules to block INPUT traffic on that interface.

K3s seems to open the NodePort access on that insecure interface by default. How can I re-order and make sure the k3s iptables rules and existing/manual iptables won't step on each other?

**Comment by gfrankliu** [comment]
ens192 is the insecure interface, if I manually insert the reject rule to the top, client on the insecure network will no longer be able to access the nodeport:
```
iptables -I FORWARD -i ens192 -j REJECT 
```

BTW, before I install k3s on the host, there was only one reject rule in the FORWARD chain:
```
sudo iptables -S FORWARD
-P FORWARD ACCEPT
-A FORWARD -i ens192 -j REJECT --reject-with icmp-port-unreachable
```

After installing k3s, it somehow got moved to the 4th position, 
```
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A FORWARD -i ens192 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -s 10.42.0.0/16 -j ACCEPT
-A FORWARD -d 10.42.0.0/16 -j ACCEPT
```
so the reject is no longer taking affect. KUBE-FORWARD installed by k3s let through the insecure traffic.

**Comment by manuelbuil** [comment]
When you mention nodePort access, do you mean the port created by servicelb? By default it opens 443 and 80 for traefik, right?

**Comment by gfrankliu** [comment]
I was talking about [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) (those high ports on the node), but the Ingress/Traefik ports (80/443) has the same issue. My pre-existing iptable rules block inbound access to any ports on the node stopped working, those NodePorts and LB Ports are all open to the insecure interface.

**Comment by manuelbuil** [comment]
The nodePort is, by default, open for all interfaces.

There is one thing I don't understand. After deploying k3s, when you run `iptables -I FORWARD -i ens192 -j REJECT`, you rule will be on top, so it will be the first one to be executed, doesn't that solve your problem?

**Comment by gfrankliu** [comment]
Are you suggesting the issue I reported (k8s/flannel moves my custom iptable rule) only happens when deploying k3s? If I add customer rules afterwards, k3s will no longer change the iptable rules order during its lifecycle?

**Comment by manuelbuil** [comment]
> Are you suggesting the issue I reported (k8s/flannel moves my custom iptable rule) only happens when deploying k3s? If I add customer rules afterwards, k3s will no longer change the iptable rules order during its lifecycle?

From my experience, yes. The network policy chain (KUBE-ROUTER-FORWARD) might move before it but the rest should stay below (KUBE-FORWARD included). Can you please give it a try?

**Comment by gfrankliu** [comment]
Yeah, I had my k3s cluster running (idle) for a few days and don't see the rules moving. Since I don't know exact which action triggers the move, it is hard to test.

**Comment by laszlocph** [comment]
> The nodePort is, by default, open for all interfaces.

@manuelbuil Would it be possible to configure which interface NodePorts are exposed on?

**Comment by manuelbuil** [comment]
> > The nodePort is, by default, open for all interfaces.
> 
> @manuelbuil Would it be possible to configure which interface NodePorts are exposed on?

Sorry for the late reply, I was on parental leave @laszlocph . Yes! https://kubernetes.io/docs/concepts/services-networking/service/#service-nodeport-custom-listen-address

**Comment by laszlocph** [comment]
Hope you had a good one! And thanks @manuelbuil
