### ISSUE TITLE
Test to modify the server time rolling update ca certificate, ca certificate can not be updated

### ISSUE THREAD

**Issue by 651016236** [k3s-io/k3s#5147]
**Environmental Info:**
K3s Version: 
1.22.6+k3s1

Node(s) CPU architecture, OS, and Version: 
ubuntu 20.04

Cluster Configuration:
1 servers

**Describe the bug:**
Test k3s certificate rotation A 10-year ca certificate generated at the beginning, there is no way to update it by restarting k3s
![image](https://user-images.githubusercontent.com/5875767/154896992-e55b3a86-3201-49ff-8848-8b9fc92d9e98.png)

**Comment by brandond** [comment]
Correct; at the moment the root CA certificates are not renewed. They are generated as valid for 10 years, so renewing them on demand is somewhat less critical than the other leaf certs that have only 1 year validity. It is something that we will need to address at some point though.

**Comment by 651016236** [comment]
> 正确的; 目前根 CA 证书没有更新。它们的有效期为 10 年，因此按需更新它们比其他只有 1 年有效期的叶子证书的重要性要低一些。不过，这是我们需要在某个时候解决的问题。

Thank you very much, renewing this certificate is still needed, if the cluster keeps running one day there will be a certificate expiration problem

**Comment by 651016236** [comment]
> Correct; at the moment the root CA certificates are not renewed. They are generated as valid for 10 years, so renewing them on demand is somewhat less critical than the other leaf certs that have only 1 year validity. It is something that we will need to address at some point though.

Thank you very much, renewing this certificate is still needed, if the cluster keeps running one day there will be a certificate expiration problem

**Comment by brandond** [comment]
Just to follow up on this - rotating (generating new keys and certs) and/or renewing (extending the validity) of the cluster CA certs was considered out of scope for certificate rotation. We will need to fix this at some point, but there are wrinkles around it - in particular the fact that the cluster join token embeds a hash of the cluster CA certificate, which would be changed if the certificate was altered in any way. There are other concerns around invalidating auth tokens that will need to be addressed as well.

**Comment by love-miao** [comment]
Is this function not yet completed：renewing (extending the validity) of the cluster CAs

**Comment by love-miao** [comment]
Is this function not yet completed？
renewing (extending the validity) of the cluster CAs

**Comment by brandond** [comment]
We now cover this in the CA certificate rotation docs. We will never automatically renew the CA certs, but you can use the docs and example script to do so manually.
