### ISSUE TITLE
Can someone tell me what to fill here in 'k3s.yml' [server: [LOAD-BALANCER-DNS]:6443 # Edit this line]

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#5159]
**Environmental Info:**
K3s Version: v1.21.7+k3s1

Node(s) CPU architecture, OS, and Version: 2node,centos7.9 x86_64

Cluster Configuration: 2server,1nginx_lb

**Describe the bug:** > 

```
kubectl get pods --all-namespaces
Unable to connect to the server: x509: certificate is valid for 10.0.2.15, 10.0.2.6, 10.43.0.1, 127.0.0.1, not 10.0.2.8
```
**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

- k3s.yaml
```
apiVersion: v1
clusters:
- cluster:
    server: https://10.0.2.8:6443 # nginx ip
```
- /etc/profile
```
# MySQL
#export K3S_DATASTORE_ENDPOINT="mysql://root:root@tcp(192.168.56.103:3306)/k3s_xiaowu"
# etcd
export K3S_DATASTORE_ENDPOINT="http://192.168.56.103:2379"
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export INSTALL_K3S_VERSION=v1.21.7+k3s1
```
- nginx.conf
```
stream {
    upstream k3s {
        least_conn;
        server 10.0.2.15:6443  max_fails=3 fail_timeout=5s;
        server 10.0.2.6:6443  max_fails=3 fail_timeout=5s;
    }
    server {
       listen 6443;
       proxy_pass k3s;
    }
}
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
It sounds like you're putting the K3s servers behind an external load-balancer. If you're doing this, you should use the --tls-san flag on your servers to add the hostname and/or IP address of the load-balancer to the certificate.

**Comment by wang-xiaowu** [comment]
> It sounds like you're putting the K3s servers behind an external load-balancer. If you're doing this, you should use the --tls-san flag on your servers to add the hostname and/or IP address of the load-balancer to the certificate.

thank u,i have finished it
