### ISSUE TITLE
After I add the "--tls-san rancher.k3s.cn" instruction, this should be the server nodes, but it turned out to be the agent node

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#5160]
**Environmental Info:**
K3s Version: v1.21.7+k3s1

Node(s) CPU architecture, OS, and Version: 2server

Cluster Configuration: nothing

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

```
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  systemd: Starting k3s-agent
[root@k3s-node2 ~]# curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_EXEC="--tls-san rancher.k3s.cn" INSTALL_K3S_MIRROR=cn sh -s - server --datastore-endpoint="http://rancher.k3s.cn:2379"
```
**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
`--tls-san` adds a SubjectAlternativeName entry to the supervisor/apiserver certificate on the server nodes. Your issue is missing any detail on what you're actually running into, but it sounds like you have also pointed `rancher.k3s.cn` at your agents, and this is leading to unexpected behavior? I see that you're also using an external etcd server, located at the same address. I'm not exactly sure what you're trying to do - providing more information about your intended configuration may help us figure out what your next steps should be.

**Comment by wang-xiaowu** [comment]
> `--tls-san`将 SubjectAlternativeName 条目添加到服务器节点上的主管/apiserver 证书。您的问题缺少有关您实际遇到的任何细节，但听起来您也指向`rancher.k3s.cn`了您的代理，这会导致意外行为吗？我看到您还在使用位于同一地址的外部 etcd 服务器。我不确定您要做什么 - 提供有关您的预期配置的更多信息可能会帮助我们确定您的下一步应该是什么。

i found the problem, if i do the cmd like this,the error will happen
```
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_EXEC="--tls-san rancher.k3s.cn" INSTALL_K3S_MIRROR=cn sh -s - server
```
but if i put "INSTALL_K3S_EXEC" on the back of "server", it's worked, to be honest ,i do not know why :)
```
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - server INSTALL_K3S_EXEC="--tls-san rancher.k3s.cn"
```

**Comment by brandond** [comment]
Environment variables need to go before the command, that's how bash works.
