### ISSUE TITLE
[Release-1.22] - Secrets encryption rotation does not work when upgrading from older K3s versions.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5166]
Backport fix for Secrets encryption rotation does not work when upgrading from older K3s versions.

* #5139

**Comment by bguzman-3pillar** [comment]
Validated first using k3s version: `v1.22.4+k3s1` before upgrade.

Full steps: 

- Installing k3s using version: `v1.22.4+k3s1`
    
    `curl -sfl https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.4+k3s1 INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --secrets-encryption" sh -
    `

- Stop k3s 

- Upgrading using this commit: 5b26c2eb4e77907530614c288ddb760511c507fc
    
    `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --secrets-encryption" INSTALL_K3S_COMMIT=5b26c2eb4e77907530614c288ddb760511c507fc sh -
    `

- Run command `sudo k3s secrets-encrypt status` :

```
$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey

```
