### ISSUE TITLE
[Release-1.21] - Secrets encryption rotation does not work when upgrading from older K3s versions.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5167]
Backport fix for Secrets encryption rotation does not work when upgrading from older K3s versions.

* #5139

**Comment by rancher-max** [comment]
Performed the steps mentioned in the PR. Started with v1.21.1+k3s1, upgraded to commit `0ec1c41cd574732cfe061f131976a38903db8fb3`, and saw success:
```
$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```

Validated this on both single node and multi-server node clusters. The command is successful on all server nodes in the multi-node setup.
