### ISSUE TITLE
k3s `LoadBalancer` implementation: why are `nodePort`'s allocated and why is an `svclb-<lb-name>` created?

### ISSUE THREAD

**Issue by ibeckermayer** [k3s-io/k3s#5182]
I've been trying to gain a firm understanding of k3s `LoadBalancer` implementation, and have been able to infer much of what's going on behind the scenes by tinkering with the default Traefik helm chart deployment (which includes a `LoadBalancer`) and examining `iptables`.

 The aspect of the implementations I think I _do_ understand is, given a `LoadBalancer` like so:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-02-14T01:32:36Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.18.201
  name: traefik
  namespace: kube-system
  resourceVersion: "69879"
  uid: 09c7dc40-08b6-466b-8161-5dbe4a34a8cd
spec:
  clusterIP: 10.43.171.236
  clusterIPs:
  - 10.43.171.236
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 31644
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31466
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.18.0.2
```

a node's `iptables` are configured such that any packets coming in to either my node's external IP (represented by the Node's name: `k3d-demo-server-0` in my `iptables`) or in to the `LoadBalancer` service's given IP (`clusterIP: 10.43.171.2361` above) on either of the selected exposed ports (`port: 80` and `port: 443`) are load-balanced to any pods selected by the `selector`. The output below follows the relevant tables/chains for port `80`

```bash
$ iptables -t nat -L PREROUTING
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

$ iptables -t nat -L KUBE-SERVICES
Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
KUBE-SVC-UQMCRMJZLI3FTLDP  tcp  --  anywhere             10.43.171.236        /* kube-system/traefik:web cluster IP */ tcp dpt:80
KUBE-FW-UQMCRMJZLI3FTLDP  tcp  --  anywhere             k3d-demo-server-0    /* kube-system/traefik:web loadbalancer IP */ tcp dpt:80

$ iptables -t nat -L KUBE-FW-UQMCRMJZLI3FTLDP
Chain KUBE-FW-UQMCRMJZLI3FTLDP (1 references)
target     prot opt source               destination
KUBE-SVC-UQMCRMJZLI3FTLDP  all  --  anywhere             anywhere             /* kube-system/traefik:web loadbalancer IP */

$ iptables -t nat -L KUBE-SVC-UQMCRMJZLI3FTLDP
Chain KUBE-SVC-UQMCRMJZLI3FTLDP (3 references)
target     prot opt source               destination
KUBE-SEP-W3PGDKCKIBAX3BCM  all  --  anywhere             anywhere             /* kube-system/traefik:web */

$ # This rule is where the loadbalancing would happen if I had multiple pods that matched my service's selector. Since I don't, it just
$ # forwards traffic to the single selected pod (10.42.0.46) on the port selected in the service above (port 8000 == targetPort: web).
$ iptables -t nat -L KUBE-SEP-W3PGDKCKIBAX3BCM
Chain KUBE-SEP-W3PGDKCKIBAX3BCM (1 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             anywhere             /* kube-system/traefik:web */ tcp to:10.42.0.46:8000
```

To my relatively naïve eye, this seems like a complete implementation. Presumably k3s' sees this `LoadBalancer` has been created, and sets up my `iptables` to implement kubernetes' `LoadBalancer` semantics, shown above. However, it seems as if the implementation is doing at least two other things that I don't understand.

#### 1) A `nodePort` is created
A `nodePort` is assigned for each `port` in the `LoadBalancer`. Above I get `nodePort: 31644` and `nodePort: 31466` corresponding to `port: 80` and `port: 443` respectively. If I follow the `iptables chain` for `KUBE-NODEPORTS`, any traffic sent to these ends up in the exact same place as traffic sent in the example above (i.e. traffic on port `31644` ends up in the `KUBE-SVC-UQMCRMJZLI3FTLDP` chain). 

While this doesn't harm anything, its not clear to me precisely why a `nodePort` is required here. Is all `LoadBalancer` services having a `nodePort` just some part of the official k8s standard that I'm unaware of? If so, why was it deemed necessary. Or if not, why has the k3s team deemed it necessary for this implementation?

#### 2) A `svclb-<service-name>` `DaemonSet` is created
Given that `iptables` seem well configured to forward the appropriate traffic to the appropriate pods, I'm confused as to why this daemonset is necessary. The [docs](https://rancher.com/docs/k3s/latest/en/networking/#how-the-service-lb-works) say:

> K3s creates a controller that creates a Pod for the service load balancer, which is a Kubernetes object of kind Service.

> For each service load balancer, a DaemonSet is created. The DaemonSet creates a pod with the svc prefix on each node.

> The Service LB controller listens for other Kubernetes Services. After it finds a Service, it creates a proxy Pod for the service using a DaemonSet on all of the nodes. This Pod becomes a proxy to the other Service, so that for example, requests coming to port 8000 on a node could be routed to your workload on port 8888.

> If the Service LB runs on a node that has an external IP, it uses the external IP.

> If multiple Services are created, a separate DaemonSet is created for each Service.

> It is possible to run multiple Services on the same node, as long as they use different ports.

> If you try to create a Service LB that listens on port 80, the Service LB will try to find a free host in the cluster for port 80. If no host with that port is available, the LB will stay in Pending.

however this doesn't clarify why these pods are needed. They each run a [`klipper-lb`](https://github.com/k3s-io/klipper-lb/blob/master/entry) image, however all that appears to do is set up `iptables` to forward all traffic on the configured port(s) to the `LoadBalancer`'s IP ().

`klipper-lb` entry:
```bash
#!/bin/sh
set -e -x

trap exit TERM INT

for dest_ip in ${DEST_IPS}
do
    if echo ${dest_ip} | grep -Eq ":" 
    then
        if [ `cat /proc/sys/net/ipv6/conf/all/forwarding` != 1 ]; then
            exit 1
        fi
        ip6tables -t nat -I PREROUTING ! -s ${dest_ip}/128 -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to [${dest_ip}]:${DEST_PORT}
        ip6tables -t nat -I POSTROUTING -d ${dest_ip}/128 -p ${DEST_PROTO} -j MASQUERADE
    else
        if [ `cat /proc/sys/net/ipv4/ip_forward` != 1 ]; then
            exit 1
        fi
        iptables -t nat -I PREROUTING ! -s ${dest_ip}/32 -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to ${dest_ip}:${DEST_PORT}
        iptables -t nat -I POSTROUTING -d ${dest_ip}/32 -p ${DEST_PROTO} -j MASQUERADE
    fi
done

if [ ! -e /pause ]; then
    mkfifo /pause
fi
</pause
```

The environment configuraiton for one of the containers on the `svclb-traefik-q4tmv` pod that was created by the `svclb-traefik` daemonset:
```yaml
  containers:
  - env:
    - name: SRC_PORT
      value: "80"
    - name: DEST_PROTO
      value: TCP
    - name: DEST_PORT
      value: "80"
    - name: DEST_IPS
      value: 10.43.171.236
    image: rancher/klipper-lb:v0.3.4
```

So it appears that any traffic sent to that pod on port 80 will end up at my `LoadBalancer`'s IP 10.43.171.236, however its not clear why traffic would ever end up sent directly to that pod.

**Comment by rl-simons** [comment]
Hello,

Unfortunately I have the same questions and would really like to know the rationale for assignment of nodeports in the scenario.
I installed K3S on a Raspberry Pi using: curl -sfL https://get.k3s.io | sudo sh -s - --write-kubeconfig-mode 644 --no-deploy traefik
Then applied this manifest:
apiVersion: v1
kind: Namespace
metadata:
  name: test-pods
  labels:
    name: namespace-test
---
apiVersion: v1
kind: Service
metadata:
  name: svc-web-server-apache
  namespace: test-pods
spec:
  type: LoadBalancer
  selector:
    web: apache
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server-apache
  namespace: test-pods
  labels:
    web: apache
spec:
  containers:
  - name: webserver-apache
    image: arm32v6/httpd:alpine
    ports:
    - containerPort: 80
Output from "kubectl get all -A"
NAMESPACE     NAME                                          READY   STATUS    RESTARTS      AGE
kube-system   pod/local-path-provisioner-84bb864455-zr4ld   1/1     Running   1 (44h ago)   4d17h
kube-system   pod/coredns-96cc4f57d-5xt8q                   1/1     Running   1 (44h ago)   4d17h
kube-system   pod/metrics-server-ff9dbcb6c-6qljt            1/1     Running   2 (44h ago)   4d17h
test-pods     pod/svclb-svc-web-server-apache-jqvtl         1/1     Running   0             28m
test-pods     pod/web-server-apache                         1/1     Running   0             28m

NAMESPACE     NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes              ClusterIP      10.43.0.1      <none>        443/TCP                  4d17h
kube-system   service/kube-dns                ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP   4d17h
kube-system   service/metrics-server          ClusterIP      10.43.29.202   <none>        443/TCP                  4d17h
test-pods     service/svc-web-server-apache   LoadBalancer   10.43.56.11    10.1.0.211    80:31419/TCP             28m

NAMESPACE   NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test-pods   daemonset.apps/svclb-svc-web-server-apache   1         1         1       1            1           <none>          28m

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           4d17h
kube-system   deployment.apps/coredns                  1/1     1            1           4d17h
kube-system   deployment.apps/metrics-server           1/1     1            1           4d17h

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/local-path-provisioner-84bb864455   1         1         1       4d17h
kube-system   replicaset.apps/coredns-96cc4f57d                   1         1         1       4d17h
kube-system   replicaset.apps/metrics-server-ff9dbcb6c            1         1         1       4d17h

The pod is accessible on both <ipaddress>:80 and <ipaddress>:31419.

**Comment by rl-simons** [comment]
I've got the same questions, specifically relating to a load balancer needing a Node Port.
K3S was installed on my Raspberry PI, using:
`  curl -sfL https://get.k3s.io | sudo sh -s - --write-kubeconfig-mode 644 --no-deploy traefik
`
Apply this manifest:
```
 ApiVersion: v1
kind: Namespace
metadata:
  name: test-pods
  labels:
    name: namespace-test
---
metadata:
  name: svc-web-server-apache
  namespace: test-pods
spec:
  type: LoadBalancer
  selector:
    web: apache
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server-apache
  namespace: test-pods
  labels:
    web: apache
spec:
  containers:
 - name: webserver-apache
   image: arm32v6/httpd:alpine
    ports:
    - containerPort: 80
```
Output from "kubectl get all -A":
```
NAMESPACE     NAME                                          READY   STATUS    RESTARTS      AGE
kube-system   pod/local-path-provisioner-84bb864455-zr4ld   1/1     Running   1 (44h ago)   4d17h
kube-system   pod/coredns-96cc4f57d-5xt8q                   1/1     Running   1 (44h ago)   4d17h
kube-system   pod/metrics-server-ff9dbcb6c-6qljt            1/1     Running   2 (44h ago)   4d17h
test-pods     pod/svclb-svc-web-server-apache-jqvtl         1/1     Running   0             28m
test-pods     pod/web-server-apache                         1/1     Running   0             28m

NAMESPACE     NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes              ClusterIP      10.43.0.1      <none>        443/TCP                  4d17h
kube-system   service/kube-dns                ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP   4d17h
kube-system   service/metrics-server          ClusterIP      10.43.29.202   <none>        443/TCP                  4d17h
test-pods     service/svc-web-server-apache   LoadBalancer   10.43.56.11    10.1.0.211    80:31419/TCP             28m

NAMESPACE   NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test-pods   daemonset.apps/svclb-svc-web-server-apache   1         1         1       1            1           <none>          28m

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           4d17h
kube-system   deployment.apps/coredns                  1/1     1            1           4d17h
kube-system   deployment.apps/metrics-server           1/1     1            1           4d17h

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/local-path-provisioner-84bb864455   1         1         1       4d17h
kube-system   replicaset.apps/coredns-96cc4f57d                   1         1         1       4d17h
kube-system   replicaset.apps/metrics-server-ff9dbcb6c            1         1         1       4d17h
```
The pod is accessible on both `<ipaddress>:80` and `<ipaddress>:31419` from a web browser.

**Comment by brandond** [comment]
LoadBalancer type Services were designed to work with external (cloud-provider managed) Load Balancers. The pod is exposed via a random port on nodes, and the Load Balancer listens (publicly) on the published ports, and forwards traffic to the node ports on the back-end. The Service controller is responsible for working with the cloud provider to create the Load Balancer, point it at the correct nodes/ports, and then sync the address that the Load Balancer is using back into the Service resource.

The K3s ServiceLB serves this same functionality, but it does so without any external dependencies by binding a pod on the published ports, forwarding traffic from those ports to the pods, and publishing the addresses of the nodes running the pods as the Load Balancer address.

There are other products that will allow you to use LoadBalancer services without a cloud provider, such as kube-vip and MetalLB, but those generally require some way to allocate additional IP addresses for LoadBalancer virtual IPs. ServiceLB just uses the node addresses, so there is no additional dependency.

**Comment by ibeckermayer** [comment]
@brandond thanks for helping out. It's starting to make a bit more sense in the context of it being designed to work with external Load Balancers, however I'm still a bit confused about some of the specifics. 

For example, if I were a cloud provider attempting to implement a k3d compatible external load balancer, I still don't see why I'd need the `nodePort`. I already have the `iptables` rule below, where `k3d-demo-server-0` is the dns name of the node. 

```
$ iptables -t nat -L KUBE-SERVICES
Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
KUBE-FW-UQMCRMJZLI3FTLDP  tcp  --  anywhere             k3d-demo-server-0    /* kube-system/traefik:web loadbalancer IP */ tcp dpt:80
```

Ergo if I have some other program running that needs to forward traffic to this node can't I just forward it to `k3d-demo-server-0:80`? Why do I need that additional port? 

It could be that I'm confused about what `k3d-demo-server-0` means in this context, and perhaps it isn't something that would typically be accessible from outside the cluster. 

I'm running k3s via k3d, so this is the name of the docker container that's running.
```
$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED       STATUS             PORTS                                          NAMES
0c90207fa52f   rancher/k3d-proxy:5.2.2    "/bin/sh -c nginx-pr…"   2 weeks ago   Up About an hour   0.0.0.0:8080->80/tcp, 0.0.0.0:6550->6443/tcp   k3d-demo-serverlb
217872b10a5f   rancher/k3s:v1.21.7-k3s1   "/bin/k3d-entrypoint…"   2 weeks ago   Up About an hour                                                  k3d-demo-server-0
```

It's also the `hostname` of the "node" (k3d managed docker container)
```
$ docker exec -it k3d-demo-server-0 /bin/sh
/ # hostname
k3d-demo-server-0
```

Perhaps that's the case, and ergo I need the `nodePort` exposed so that I could access the node directly via its `<ip-addr>:<nodePort>`? But even in that case, I don't see why I need another port. Presumably with the right firewall configuration, it seems like I should just be able to use `<ip-addr>:80`.

**Comment by brandond** [comment]
You're looking at k3d specific stuff that's created to expose things on the inner clusters. These have pretty much nothing to do with Kubernetes or the normal functioning of LoadBalancer services.
