### ISSUE TITLE
Installing K3S 1.21.7+k3s1 on SLE Micro 5.1 got errors

### ISSUE THREAD

**Issue by gogbac** [k3s-io/k3s#5183]
**Environmental Info:**
K3s Version:  v1.21.7+k3s1

Node(s) CPU architecture, OS, and Version: x86_64, SLE Micro 5.1

Cluster Configuration: Single node

**Describe the bug:**

K3S does not run on SLE Micro 5.1, Initial containers failed

**Steps To Reproduce:**

- Installed K3s: 

K3s_VERSION="v1.21.7+k3s1"

curl -sfL https://get.k3s.io | \
INSTALL_K3S_VERSION=${K3s_VERSION} \
INSTALL_K3S_EXEC='server --cluster-init --write-kubeconfig-mode=644' \
sh -s -

watch -c "kubectl get deployments -A"

kubectl get all -A

**Expected behavior:**

All containers should run without errors

**Actual behavior:**

not able to create containers, I will add more screenshots...

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by gogbac** [comment]
1. Installating K3S on SLE Micro 5.1
![image](https://user-images.githubusercontent.com/51060150/156051177-3f1cc396-7b7d-4e9e-9ee0-252355266d8c.png)

![image (1)](https://user-images.githubusercontent.com/51060150/156051191-77c6f1b9-3c0a-47f5-8782-ee7934770e5f.png)

2. See errors
![image (2)](https://user-images.githubusercontent.com/51060150/156051297-b331206a-b47f-448e-addb-df1ca9e8e8c6.png)

3. more info

![image (3)](https://user-images.githubusercontent.com/51060150/156051322-84df64a0-dd31-4625-9451-46854b4a2372.png)

![image (4)](https://user-images.githubusercontent.com/51060150/156051338-a2f7edf4-1517-4677-99bd-2f539049f77d.png)

**Comment by galal-hussein** [comment]
As per @dweomer comment, the current installed version of container-selinux on SLE Micro doesn't have the changes that he did for pulling out k3s file contexts from the policy, thats why we see so many conflicts between our policy and container-selinux policy, the workaround for now is to install the custom built container-selinux https://github.com/k3s-io/k3s-selinux/releases/download/v1.0.testing.1/container-selinux-2.171.0-99.sle.noarch.rpm on SLE micro until we get support for rpms of versions  > v1.171.0 on SLE micro systems

**Comment by mysticaltech** [comment]
I also get this, on OpenSuse MicroOS, where I installed k3s with the install script:

```
control-plane-0:~ # /sbin/semodule -v -i /usr/share/selinux/packages/k3s.pp 
Attempting to install module '/usr/share/selinux/packages/k3s.pp':
Ok: return value of 0.
Committing changes:
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:170
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4195
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:153
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4185
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:171
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4196
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:158
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4186
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:168
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4193
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:149
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4126
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:169
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4187
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:154
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4188
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:155
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4189
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:157
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4191
Found conflicting filecon rules
  at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:156
  at /var/lib/selinux/targeted/tmp/modules/200/container/cil:4190
Problems processing filecon rules
Failed post db handling
Post process failed
/sbin/semodule:  Failed!

```

**Comment by mysticaltech** [comment]
However, when I use the default version of `k3s-selinux` v0.5 that ships via the OpenSuse repos, it installs without issue!

![ksnip_20220303-013731](https://user-images.githubusercontent.com/518555/156474745-e6a7db1e-3866-482b-9efc-0e3191b0b767.png)
