### ISSUE TITLE
Override CoreDNS default forward

### ISSUE THREAD

**Issue by gfrankliu** [k3s-io/k3s#5186]
CoreDNS installed by k3s uses
```
  forward . /etc/resolv.conf
```

Debian hosts have `nameserver 127.0.0.1` in /etc/resolv.conf (eg: if you install/run dnsmasq). Can k3s provide an installation option to configure the default forward IPs?

- The custom configmap import *.server feature can only configure subdomains.

- If you modify the cm/coredns, the change will get overwritten once you restart k3s.

**Comment by brandond** [comment]
No, but you can provide a different resolv.conf for K3s to use, via the `--resolv-conf` flag.

**Comment by gfrankliu** [comment]
Can I create a temp /tmp/resolv.conf during k3s installation, and remove it once k3s is running?

**Comment by brandond** [comment]
no, the file needs to remain in place, otherwise pods can't read it?

**Comment by gfrankliu** [comment]
I was hoping to have it once for installation configuration. Can we have a feature request to add a k3s server option during installation time, eg: --coredns-default-forward-to ?  People can then use it to set list of upstream dns server IPs, or alternative resolv.conf (like what --resolv-conf flag does).

**Comment by brandond** [comment]
I'm not sure that it's worth another option to accomplish the same result. Is there some reason you can't just create /etc/rancher/k3s/resolv.conf with your desired options, and add `--resolv-conf=/etc/rancher/k3s/resolv.conf` to the CLI flags?

**Comment by gfrankliu** [comment]
I created /etc/rancher/k3s/resolv.conf on an existing server, and updated /etc/systemd/system/k3s.server to add `--resolv-conf=/etc/rancher/k3s/resolv.conf`, after restarting k3s service, the `kubectl -n kube-system get cm/coredns -o yaml` still shows `forward . /etc/resolv.conf`. How to update an existing k3s instance?

For a brand new installation, there is no /etc/rancher/k3s directory. If I pre-create it, will it cause problem for k3s installer?

**Comment by brandond** [comment]
The path within pods does not change. It just changes the location of the host resolv.conf that the kubelet injects into pods.

**Comment by brandond** [comment]
No, neither K3s nor the kubelet support dynamic reconfiguration at runtime. Any configuration files you want to reference must exist before starting K3s.

**Comment by ccll** [comment]
> No, but you can provide a different resolv.conf for K3s to use, via the `--resolv-conf` flag.

@brandond It seems that `--resolv-conf` can only accept non-local unicast addresses for nameservers, in my case I need to setup custom domain resolution with a locally deployed dnsmasq at the address 192.168.1.10, so `--resolv-conf` simply does not work, k3s will still generate `/tmp/k3s-resolv.conf` which uses 8.8.8.8 as nameserver.

Any ideas?

**Comment by brandond** [comment]
I'm confused, why wouldn't 192.168.1.10 work? That should be fine.
