### ISSUE TITLE
While upgrading from v1.22.6 to v1.22.7, it creates communication issue in cluster and from pod to outside services

### ISSUE THREAD

**Issue by ssharma2089** [k3s-io/k3s#5188]
**Environmental Info:**
K3s Version: 
k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux mwsdev01.xxx.xxx 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
one master and one worker node

**Describe the bug:**
We have upgraded k3s from v1.22.6 to v1.22.7. After upgrading, pod communicating with LDAP is throwing an error "failed: unable to read LDAP response packet: read tcp 10.0.0.11:40074->10.xx.x.xxx:389: read: connection reset by peer and throwing error in traefik "Error: Kubernetes cluster unreachable: Get "https://10.xx.0.1:443/version?timeout=32s": net/http: TLS handshake timeout"
We are using cilium and metallb. So, fannel, kube-proxy,servicelb and metrics server are disabled.
Reverting to previous version with system upgrade fixes the issues. 
**Is the new way of using kube-router library changing the default network policy?** 

**Steps To Reproduce:**
1. Install k3s v1.22.6
2. Upgrade k3s v1.22.7 (by using k3s system-upgrade plan)

**Expected behavior:**
It should work as with existing version v1.22.6

**Actual behavior:**
There is communication issue which is mentioned in description of the bug

**Additional context / logs:**
Example logs with previous version of traefik (i.e v2.5.6)
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string 'global.systemDefaultRegistry=%{SYSTEM_DEFAULT_REGISTRY_RAW}%'
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
Error: Kubernetes cluster unreachable: Get "https://10.xx.0.1:443/version?timeout=32s": net/http: TLS handshake timeout
+ LINE=
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ '' =~ ^(|null)$ ]]
+ [[ '' =~ ^(|null)$ ]]
+ helm_v3 install --set-string 'global.systemDefaultRegistry=%{SYSTEM_DEFAULT_REGISTRY_RAW}%' traefik https://10.xx.0.1:443/static/charts/traefik-10.9.100.tgz --values /config/values-01_HelmChart.yaml

**Comment by brandond** [comment]
> We are using cilium and metallb. So, flannel, kube-proxy, servicelb and metrics-server are disabled.
> Is the new way of using kube-router library changing the default network policy?

I would not suspect that the kube-router changes are affecting anything, since we don't ship any network policies. You can try starting with `--disable-network-policy` to see if that's the issue.

Honestly though I think it's probably something to do with your CNI deployment though, since you've lost access to both things outside the cluster (your LDAP server) and within the cluster (the apiserver in-cluster endpoint).

**Comment by ssharma2089** [comment]
@brandond  first off thank you for a quick reply and ultimately useful hint. We went through quite a few scenarios of upgrade between k3s and cilium and found that in order to have a frictionless upgrades beyond 1.22.6+k3s1 we need to run k3s with the --disable-network-policy flag. There is some support for it in the cilium project with documentation for the latest version (which we aren't using) https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/ where they also advise installing k3s with --disable-network-policy. Up to 1.22.6 we had several upgrades that didn't require the flag and we didn't have time to tease out what is the hump between 1.22.6 and 1.22.7 that makes the flag a must.

**Comment by brandond** [comment]
cc @manuelbuil - although I suspect this is probably just a docs issue, we should suggest that anyone replacing flannel with a CNI that also does network policy also disable the network policy controller, even if not deploying an policies.

**Comment by manuelbuil** [comment]
Yes! That's a good point. Or even better:
1 - document it
2 - disable netpol if flannel-backend=none

**Comment by manuelbuil** [comment]
BTW thanks @ssharma2089 for reporting it

**Comment by manuelbuil** [comment]
Now I am wondering whether we should automate `disable netpol if flannel-backend=none`. Apart from flannel, I don't know any CNI plugin which does not include a network policy engine but users might come with their own and expect k3s to implement network policies
