### ISSUE TITLE
"failed to find Session for client" for kubectl logs

### ISSUE THREAD

**Issue by cromega** [k3s-io/k3s#519]
OS: Ubuntu 19.04
K3s version: 0.5.0

I'm trying to set up an immutable VM for running K3s, meaning I will destroy/recreate the VM while keeping the K3s data-dir on a persistent volume. After the VM comes back and K3s restores its state weird things happen:

```
$ kubectl --kubeconfig ~/.kube/k3s -n kube-system logs traefik-55bd9646fc-gkhcb
Error from server: Get https://ip-10-10-0-218:10250/containerLogs/kube-system/traefik-55bd9646fc-gkhcb/traefik: failed to find Session for client ip-10-10-0-218
```

AWS instances may pick a random private IP from a pool and 10.10.0.218 is the **previous** private IP of the instance so I guess something got stuck in the service state and now it refuses to respond.

**To Reproduce**
* Create an instance on AWS with a persistent volume attached and mounted
* Install K3s using a location on the volume as data-dir
* Probably run `kubectl logs` to create a session(?)
* Destroy the instance and create a new one with a different private IP and the same volume attached
* Mount the volume on the instance and start K3s
* run `kubectl logs`

**Expected behavior**
I see the logs of the container

**Comment by warmchang** [comment]
Use hostname instead of IP address.
https://github.com/rancher/k3s#accessing-cluster-from-outside

**Comment by cromega** [comment]
```
$ kubectl --kubeconfig ~/.kube/k3s cluster-info 
Kubernetes master is running at https://platform.***:6443
```

**Comment by andyjeffries** [comment]
As this link now goes nowhere - does anyone know what the steps to resolve this were?

@warmchang

**Comment by warmchang** [comment]
> As this link now goes nowhere - does anyone know what the steps to resolve this were?
> 
> @warmchang

Here is it: https://rancher.com/docs/k3s/latest/en/configuration/#accessing-cluster-from-outside

But according to the [replay](https://github.com/rancher/k3s/issues/519#issuecomment-499010327) from @cromega , it seems that it didn't solve the problem.

**Comment by murlock** [comment]
I've installed `k3s` with default install on my laptop, and I think this issue is maybe related to IP used on public interface since I've met this issue after switching wifi network to another one.
I hope this can help

**Comment by raftAtGit** [comment]
I've hit the same error: both `kubectl logs ..` and `kubectl exec ..` commands were failing with `failed to find Session for client <hostname>`.

in my case, it turned out to be, the hostname where `k3s` is running changed after reboot. to my understanding, `master` was trying to connect to `worker node` with name `hostname` and was failing. after sometime, I've noticed `kubectl get node` command also returned the old `hostname` with `NotReady ` status and rescheduled all old pods to new `hostname`. 

I set the `hostname` to `old hostname` and issue disappeared after a reboot.

possibly this is the same issue.

**Comment by liyimeng** [comment]
The problem for me when I try to restore a node from back, even without changing the hostname. 
I then delete master node from /var/lib/rancher/server/cred/node-passwd and reboot. The problem solved, but I don't get the theory. :(

**Comment by erikwilson** [comment]
There is also agent node data stored in `/etc/rancher` that may be relevant @liyimeng

**Comment by brandond** [comment]
Closing due to age.
