### ISSUE TITLE
k3s go panic on migrating node-passwd

### ISSUE THREAD

**Issue by jdunhamvrtx** [k3s-io/k3s#5190]
**Environmental Info:**
K3s Version: 

k3s version v1.21.9+k3s1 (101917b0)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Mon Jun 14 17:25:42 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

6 nodes, redhat 7 on esxi

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 
- set node as agent
- node involved in cluster
- turn off k3s
- fill in service details to make node a server
- restart k3s

**Expected behavior:**
Migration happens

**Actual behavior:**

time="2022-03-01T12:43:29.006274984-05:00" level=info msg="Migrating node password entries from '/var/lib/rancher/k3s/server/cred/node-passwd'"
panic: runtime error: integer divide by zero

goroutine 390 [running]:
github.com/rancher/k3s/pkg/nodepassword.MigrateFile(0x7f42b8c12ed0, 0xc01ae8c120, 0x7f42b8c12f20, 0xc01ae8c180, 0xc001289aa0, 0x2c, 0x0, 0x43d026)
	/go/src/github.com/rancher/k3s/pkg/nodepassword/nodepassword.go:114 +0x965
github.com/rancher/k3s/pkg/server.runControllers(0x54db178, 0xc0012f9700, 0xc001140d80, 0x0, 0x2)
	/go/src/github.com/rancher/k3s/pkg/server/server.go:120 +0x33e
github.com/rancher/k3s/pkg/server.startOnAPIServerReady(0x54db178, 0xc0012f9700, 0xc001140d80)
	/go/src/github.com/rancher/k3s/pkg/server/server.go:101 +0xe5
created by github.com/rancher/k3s/pkg/server.StartServer
	/go/src/github.com/rancher/k3s/pkg/server/server.go:70 +0x3cb
**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Just to be clear, this occurs when attempting to convert a node from agent to server? This is easy to fix, but the only way I can see it being triggered is if the cluster has both no nodes, and no entries in the node password file - neither of which should be possible on a functioning cluster. Can you provide the exact CLI arguments you used when restarting the node as a server?

**Comment by katran001** [comment]
Tracking internally as SURE-4303

**Comment by ShylajaDevadiga** [comment]
Validated on k3s version v1.23.6-rc4+k3s1 
Created a two node cluster with etcd backend, 1 server 1 agent
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-31-10-210   Ready    control-plane,etcd,master   3m42s   v1.23.6-rc4+k3s1
ip-172-31-14-161   Ready    <none>                      2m45s   v1.23.6-rc4+k3s1
```
Stopped k3s agent 
Updated the k3s-agent systemd unit file, changed agent to server
Restarted service
```
ubuntu@ip-172-31-10-210:~$ kubectl get nodes 
NAME               STATUS   ROLES                       AGE    VERSION
ip-172-31-10-210   Ready    control-plane,etcd,master   9m6s   v1.23.6-rc4+k3s1
ip-172-31-14-161   Ready    control-plane,etcd,master   8m9s   v1.23.6-rc4+k3s1
```

No panic seen in the logs
```
ubuntu@ip-172-31-14-161:~$ journalctl -u k3s-agent.service |grep "Migrating node password"
ubuntu@ip-172-31-14-161:~$
```

**Comment by rgulden** [comment]
@ShylajaDevadiga @brandond  Is there any fix for this? I am trying to upgrade v1.19 to v1.20 and am facing this error in the logs. Its only a one node cluster also.

**Comment by cwayne18** [comment]
This was fixed in 1.21+, 1.19 and 1.20 were already EOL at this point

**Comment by rgulden** [comment]
@cwayne18  - Alright ill give 1.21 a try

**Comment by cwayne18** [comment]
Honestly, 1.21 is EOL now as well, so realistically if you're upgrading you may want to go to at least 1.22

**Comment by rgulden** [comment]
@cwayne18  - Thanks for the heads up, i need to convert some ingress over to the new api before

**Comment by cwayne18** [comment]
Happy to help, let us know if youre still seeing this on 1.22+ and we can reopen
