### ISSUE TITLE
SELinux context never gets applied on MicroOS by the install script

### ISSUE THREAD

**Issue by mysticaltech** [k3s-io/k3s#5191]
Hello folks, we are testing k3s on MicroOS OpenStack Cloud image, which initializes with cloud-init on Hetzner, see https://github.com/kube-hetzner/kube-hetzner/pull/103. In doing so, found out that if we rely on the k3s install script to install the k3s-selinux RPM - the context actually never gets applied, because of the reboot needed for it to work!

In the following logic, the k3s-selinux RPM installs itself via transactional-update in a new snapshot, then the `chcon -u system_u -r object_r -t container_runtime_exec_t ${BIN_DIR}/k3s` command fails, and gives a message to reboot, and follows up with the k3s install.

https://github.com/k3s-io/k3s/blob/4b064b5d22ebd1c746763ddbf335a5acda61438a/install.sh#L496-L505

It works, but without SElinux because the context just never gets applied, unless manually applied after rebooting.

What we do now is first install the k3s-selinux RPM manually, reboot, install k3s with the `INSTALL_K3S_SKIP_START=true` & `INSTALL_K3S_SKIP_SELINUX_RPM=true` flags, and then apply the `chcon` command manually. Then start k3s.

Am I correct?

**Comment by brandond** [comment]
I suspect that this is related to the same failure to apply the policy that is described here: https://github.com/k3s-io/k3s/issues/5183

**Comment by mysticaltech** [comment]
@brandond It could be, but I do not think so. Everything actually works, unlike in the above issue. It's just that by the logic of the `install.sh` file, the context will never get applied unless I got it wrong.

**Comment by brandond** [comment]
I believe that the `chcon -u` shouldn't be necessary since it's handled by the RPM postinstall once the transactional-update reboot is done. @galal-hussein can you confirm?

**Comment by mysticaltech** [comment]
If that is the case, then perfect! Also, it's not a problem if k3s starts and runs for a few minutes before it reboots right? SELinux for k3s should still kick in upon reboot, without the need to issue any commands?

**Comment by mysticaltech** [comment]
This command manually applies the policies, correct? `/sbin/semodule -v -i /usr/share/selinux/packages/k3s.pp`

**Comment by mysticaltech** [comment]
I believe the answers to my questions above are Yes and Yes, but please correct me if I am wrong! Thank you and keep up the good work.
