### ISSUE TITLE
internal node IP is not in kubelet cert SAN, breaking metrics server

### ISSUE THREAD

**Issue by acuteaura** [k3s-io/k3s#5193]
**Environmental Info:**
K3s Version: 1.22.6+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux k3s 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 17:53:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

(that's rocky linux 8, EL8 equivalent)

Cluster Configuration:
single node, hetzner CCM with networks support (so InternalIP is set to a private IP)

**Describe the bug:**
In #4966 the default `kubelet-preferred-address-types` was changed to use `InternalIP` by default. The internal node IP is however not included in the kubelet certificate SAN and seems unaffected by the `tls-san` option, leading to metrics server failing the TLS handshake.

**Steps To Reproduce:**
Setup k3s on Hetzner, with options
- kubelet-args "cloud-provider=external"
- disable servicelb
- disable-cloud-controller

Then place the node in a hetzner network and set up [hetzner CCM with networks](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md) (skipping the CNI steps).

**Expected behavior:**
The internal IP is added to the kubelet SAN, or can be added via `tls-san` command and k3s restart.

**Actual behavior:**
kubelet does not include internal IP

**Additional context / logs:**
metrics-server repeatedly logs

```
E0302 19:48:00.550773       1 scraper.go:139] "Failed to scrape node" err="Get \"https://10.0.0.2:10250/stats/summary?only_cpu_and_memory=true\": x509: certificate is valid for 127.0.0.1, 157.90.145.248, not 10.0.0.2" node="k3s"
```

10.0.0.2 here is the internal IP of the node as set up by hetzner CCM

**Backporting**
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Are you setting --node-ip to the public IP instead of the private IP? Normally you would set `--node-ip` to the private IP, and `--node-external-ip` to the public, and the kubelet cert would be valid for both. This is handled at https://github.com/k3s-io/k3s/blob/f090bf2d5eb9abc6cd09ed8ff794bb00a9276079/pkg/agent/config/config.go#L370-L371

**Comment by toabi** [comment]
I have the same issue (and similar setup). I'm not setting any IPs manually. We create the agents via terraform and install the agent via cloud-init so external IP wouldn't be known yet to pass it.

Although I just tried recreating one agent with `--node-ip` and apparently this is sufficient. The error for this agent disappeared from the metrics-server logs. Jey. 🎉

**Comment by acuteaura** [comment]
`--node-ip` fixes it, but it is not ideal because figuring out the interfaces is not trivial and should be the job of the CCM.

**Comment by brandond** [comment]
CCM is only responsible for setting the external IP and hostname; the primary IP is the responsibility of the kubelet when it registers.
