### ISSUE TITLE
Install script failing with Rocky Linux 

### ISSUE THREAD

**Issue by hkdd** [k3s-io/k3s#5194]
Presumably with the ending of CentOS proper (and the move to CentOS Stream) there will be more and more people moving to other rebuilds of "Enterprise Linux."  I assume you might have a similar problem with AlmaLinux which is also becoming increasingly popular.  

**Environmental Info:**
K3s Version:  latest

Node(s) CPU architecture, OS, and Version: 

Rocky Linux 8.5
Linux k05 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 17:53:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

HA with embedded etcd

**Describe the bug:**

When you curl the sh script it incorrectly identifies Rocky as SUSE and creates the repo file in the /etc/zypp directory instead of /etc/dnf

**Steps To Reproduce:**

Install Rocky Linux 8.5, full updated
run (as root):  curl -sfL https://get.k3s.io | sh -

**Expected behavior:**

Should install k3s

**Actual behavior:**

Script fails attempting to install k3s-selinux via rpm because the repo isn't added correctly.  Specifically:

No match for argument: k3s-selinux                                      
Error: Unable to find a match: k3s-selinux  

**Additional context / logs:**

Obviously this is pretty trivial to fix by modifying the appropriate section of the install script to correctly identify Rocky as EL8.

If it helps, this is what /etc/redhat-release looks like:  Rocky Linux release 8.5 (Green Obsidian)

**Backporting**

- [ ] Needs backporting to older releases

**Comment by knweiss** [comment]
FWIW: I've updated the stable channel two days ago on Rocky Linux 8.5 and did not have this issue i.e. the `k3s-selinux-1.0-1.el8.noarch` rpm was installed successfully.

May you could repeat the installation with `sh -x` and provide the trace?

**Comment by hkdd** [comment]
Just tried again and I'm not getting the same behavior, seems to be working fine now.  Thanks!

**Comment by cwayne18** [comment]
Great! Closing this out, please re-open if you see this pop up again
