### ISSUE TITLE
Database driver plug-in architecture

### ISSUE THREAD

**Issue by bencompton** [k3s-io/k3s#520]
PostgreSQL and MySQL support are great. However, I'm sure there will eventually requests to support every database under the sun. For example, I would like to see SQL Server support. It might be worthwhile to have a plug-in architecture (i.e., dynamically linked) that allows the community to create separate database driver plug-ins for K3s.

It appears that this "etcd shim" capability introduced with k3s may eventually [become a more generic solution](https://twitter.com/ibuildthecloud/status/1125848099765624832) usable with upstream K8s. In that case, having a wide range of database choices would be even more valuable.

**Comment by ibuildthecloud** [comment]
I'm quietly already working on this.  More details to come. https://github.com/ibuildthecloud/kine/

**Comment by davidnuzik** [comment]
Needs testing; needs docs regarding external db.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga to test as a low priority / background task. We should test with Microsoft SQL. Not certain if we will fully support (official in docs for example) but this should work.

**Comment by brandond** [comment]
Closing due to age. Kine is now a top-level project.
