### ISSUE TITLE
Upgrading from single Sqlite master to 3 master built-in etcd control plane

### ISSUE THREAD

**Issue by ssharma2089** [k3s-io/k3s#5211]
**Environmental Info:**
K3s Version: 
v1.22.7

Node(s) CPU architecture, OS, and Version: 
Linux mwsdev01.xxx.xxx 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
one master and 3 worker nodes

**Describe the bug:**
As the above name indicates that we are about to embark on upgrading our 1master+3 workers cluster to 3 master+1 worker. We have some affinity/antiaffinity rules based on node names and would like to have as smooth as possible transition. 
Is there anything else to the exercise besides the instructions listed below
- cordon off a worker node 
- stop k3s agent
- uninstall k3s agent
- install k3s server 
- join k3s server like documented in https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

Is there a suggested version with a nice clean-up of the agent, containerd, flannel, iptables rules so on...(we have observed some issues on here like https://github.com/k3s-io/k3s/issues/5190 ).  Any other considerations than the ones stated in https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/ that assumes a fresh server install/no previous agent?

This should be a common scenario now that it's possible to migrate from sqlite to etcd embedded and subsequently to etcd HA, therefore it's worth documenting.

**Comment by adyanth** [comment]
Were you able to get this working? My understanding was that all servers need to be using embedded etcd which necessitated a reinstall of the server nodes (meaning a migration was not possible).

**Comment by ssharma2089** [comment]
@ adyanth, if you see our outline we do plan to uninstall agent and install server. We are raising this issue/discussion to check if there is a validated procedure/version where the uninstall/install steps result in non borked node. In our organization the server restore and/or requisition of new node are responsibility of different teams, which take their time so would like to avoid a borked system. In any case we plan to test the approach in our DEV environemnt. It is currently 1 master one slave so 2 master etcd embeded would be unsupported config but it will at least test the uninstall/install part.

**Comment by adyanth** [comment]
I have uninstalled and reinstalled on the same nodes multiple times as a part of testing (non-prod), and the `k3s-uninstall.sh` and `k3s-agent-uninstall.sh` work perfectly fine as [mentioned in the docs](https://rancher.com/docs/k3s/latest/en/installation/uninstall/). I will let others chime in if there is a different way to do this.
