### ISSUE TITLE
Node Pressure Eviction threshold

### ISSUE THREAD

**Issue by Shreekant1997** [k3s-io/k3s#5213]
Hi,

I am new to k3s and I was going through the document and saw the concept ' Node Pressure Eviction '. 

I wanted to carry out this use case for my basic setup - One Master, One Agent. 

Use-Case: 
What I wanted to carry out was that if the Memory(RAM) goes below a certain threshold then I want my pods to be evicted from the node and then gets scheduled to other available node. I read about 'Hard Eviction'  and wanted to implement the same. But I a, struggling with some basic issue. 

**Issue I am struggling with**

1. I am not able to manipulate or change the Threshold for eviction. I understand kubelet has a role to play but installing k3s doesnt come with kubelet service. 

2. When I am filling up my system with grabage RAM, I could see all the pods are evicting from the node even the system critical and they are getting scheduled on the same. 

**Help I am looking for**

1. Is there any way I can carry out the use case in k3s. 
2. How can I change the hard eviction threshold. 
3. Any other alternative way.

**Comment by brandond** [comment]
> installing k3s doesnt come with kubelet service.

The kubelet is built in to k3s, and is run as a subprocess of the k3s supervisor process. You can tune pass arguments through to the kubelet via the `--kubelet-arg` flag.

Documentation references:
* https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#customized-flags-for-kubernetes-processes
* https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by Shreekant1997** [comment]
Hi brandon, 

Thanks for the quick reply. Do we need to pass this **--kubelet-arg=arg=value** while installing k3s or we after installing we can run this as CLI. 

If my understanding is correct then: 

--kubelet-arg= memory.available<4Gb will ensure a eviction when the memory goes below 4Gb. 

Also it would be better If you could help me with the complete command. 

Thanks.

**Comment by Shreekant1997** [comment]
Also I read that CLI for kubelet has been depreciated and it is to be used with Config file. But I could not find anywhere the config file for the same.

**Comment by brandond** [comment]
The CLI args have been deprecated for ages and show no actual signs of going away; I would continue to use them.

You can pass it while installing k3s, or edit the systemd unit for k3s to add the args post-install, and then restart the service.

**Comment by Shreekant1997** [comment]
Hi Brandon, 

Yes I was able to execute the kubelet configration which you mentioned above and it was working perfectly fine. I used to start the k3s server with those argument and it was working. But since I installed k3s with script instead of binary that option is not feasible. I'll try to check with the systemd file. That should work.

**Comment by EvanCarroll** [comment]
@brandond you can also set the args in the the KUBECONFIG.yaml, right?

```yaml
kubelet-arg:
  - "eviction-hard=imagefs.available<case>,memory.available<case>,nodefs.available<case>,nodefs.inodesFree<case>"
```
