### ISSUE TITLE
SQlite DB dump/backup size

### ISSUE THREAD

**Issue by adyanth** [k3s-io/k3s#5219]
**Environmental Info:**
K3s Version: 
k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
`Linux kratos-master 5.10.93-6.ph4-esx #1-photon SMP Thu Feb 17 02:54:43 UTC 2022 x86_64 GNU/Linux`

Cluster Configuration:
1 server (sqlite), 2 workers

**Describe the bug:**
When taking a backup of the state.db and then restoring it back, the size of the db is reduced drastically.

**Steps To Reproduce:**
- Installed K3s: using k3sup, --disable servicelb --disable traefik
Let the k3s run for few days, add workloads?
Then run the following:

```bash
❯ sqlite3 state.db .dump | sqlite3 state.db.backup
❯ ls -alh state.db*
-rw-r--r--  1 adyah  staff    79M Mar  8 00:25 state.db
-rw-r--r--  1 adyah  staff    32K Mar  8 00:26 state.db-shm
-rw-r--r--  1 adyah  staff     0B Mar  8 00:26 state.db-wal
-rw-r--r--  1 adyah  staff    15M Mar  8 00:26 state.db.backup
```

**Expected behavior:**
I have a question of if this is a good backup. If it is, why is the DB so large when running (will it cleanup or keep on growing?)

**Actual behavior:**
The restored version is quite small compared to the actual DB. 79MB vs 15MB.

**Additional context / logs:**
Taking a `sqlite3 state.db ".backup state.db.backup"` results in similar size since it copies the database pages, whereas the .dump converts to SQL representation and builds a fresh database.

**Backporting**
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
This is probably a question best asked of the sqlite author. I suspect it has a lot to do with how sqlite reuses empty pages, truncates the file to reclaim disk space, etc.

**Comment by adyanth** [comment]
I thought so too, but I am not sure where that would be. The information on differences between .dump and .backup is already very slim.

With this issue, I wanted to gain insights from how k3s (you guys, the org) thinks if the backups are good enough if I take a dump vs doing a backup.

**Comment by brandond** [comment]
As long as the databased content is all there it should be fine. We don't do anything weird with sqlite, everything is done via SQL bindings so I can't see why there would be a difference between a dump/restore compared to a backup. If you are backing up the files, just make sure you get the .db-wal file in addition to the .db, in case k3s was shut down uncleanly. In either case I would recommend stopping K3s before backing up or dumping the database.

**Comment by adyanth** [comment]
The sqlite's .dump and .backup are designed to be run when the DB is online. It takes the relevant write locks before dumping it. I also believe it considers the write ahead logs, and since I would be doing when k3s is online, unsafe shutdown should hopefully not be a concern.

Thanks for info on not doing anything complicated with the db, the dump should suffice then. I was just alarmed at the huge difference in size it resulted in.

I take daily backups via K3s CronJob to a PV, so stopping k3s would not be possible for me.

I think is is good enough info here, so I will close this issue for now. (Unless someone with indepth sqlite knowledge wants to chime in? :) )
Thanks again, @brandond !
