### ISSUE TITLE
[Release-1.21] - Unable to use `secrets-encrypt` subcommand with CP/Etcd-Only configuartion.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5226]
Backport fix for Unable to use `secrets-encrypt` subcommand with CP/Etcd-Only configuartion.

* #5225

**Comment by rancher-max** [comment]
Encounter the same issue noted in https://github.com/k3s-io/k3s/issues/5225#issuecomment-1077951857 on v1.21.11-rc2+k3s1

**Comment by rancher-max** [comment]
Validated using v1.21.11-rc3+k3s1 that the error seen previously is resolved and running all of the secrets-encrypt subcommands are successful
