### ISSUE TITLE
[Release-1.22] - Unable to use `secrets-encrypt` subcommand with CP/Etcd-Only configuartion.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5227]
Backport fix for Unable to use `secrets-encrypt` subcommand with CP/Etcd-Only configuartion.

* #5225

**Comment by rancher-max** [comment]
Validated using v1.22.8-rc3+k3s1 that the error seen previously is resolved and running all of the secrets-encrypt subcommands are successful
