### ISSUE TITLE
Single host mode documentation is required

### ISSUE THREAD

**Issue by Novitoll** [k3s-io/k3s#5249]
**Is your feature request related to a problem? Please describe.**
Single host mode setup is not documented. This [issue](https://github.com/k3s-io/k3s/issues/541) is same, though I'd like to have a setup with traefik installed. There is a [rancher documentation](https://rancher.com/docs/k3s/latest/en/architecture/#single-server-setup-with-an-embedded-db), though it does not provide with any technical instructions.

Current setup (everything on the same machine):
```
# 10250/tcp is for agent's kubelet
k3s server --kubelet-arg="port=10251"

# 6444/tcp is for server's https api
k3s agent --server https://127.0.0.1:6443 --lb-server-port 6445 --token ${NODE_TOKEN}
```

**Describe the solution you'd like**
Provide with a config file to map each listening TCP port for server and agent nodes.

**Additional context**
![image](https://user-images.githubusercontent.com/8348972/157689742-8c1afa19-7f0f-495f-a829-9483b5e81b01.png)

**Comment by brandond** [comment]
I'm not sure what you mean by "single host mode". Are you trying to run the server and agent on the same node? That is unsupported and unnecessary. The server also runs the same components as an agent (kubelet, cni, etc), so if you want a single-node cluster, all you need to do is install K3s and start the server. That's it.

You can reference the diagram at https://k3s.io/img/how-it-works-k3s-revised.svg for more info on what components the server and agent include.
