### ISSUE TITLE
Selinux installation failure on Centos7 

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#5258]
**Environmental Info:**
K3s Version: any version

Node(s) CPU architecture, OS, and Version: 
Centos 7

Cluster Configuration:
1 server

**Describe the bug:**
The k3s-selinux v1.0 stable version causes a problem on Centos 7 because it has an old container-selinux version: `container-selinux-2.119.2-1.911c772.el7_8.noarch`

**Steps To Reproduce:**
- Start centos7 server
- enable selinux "selinux: true"
- install k3s

**Expected behavior:**
For k3s to start correctly

**Actual behavior:**

```
  Installing : k3s-selinux-1.0-1.el7.noarch                                                                                                                                               9/9 
Failed to resolve typeattributeset statement at /etc/selinux/targeted/tmp/modules/200/k3s/cil:21
/usr/sbin/semodule:  Failed!

```
**Additional context / logs:**
**Backporting**

- [ ] Needs backporting to older releases

**Comment by rancher-max** [comment]
Validated this is working in all of v1.21.11+k3s1, v1.22.8+k3s1, and v1.23.5+k3s1
