### ISSUE TITLE
PRODUCTION ERROR - Can I evict master?

### ISSUE THREAD

**Issue by turowicz** [k3s-io/k3s#5269]
I am having production disaster. 

3 node cluster. 1 master + 2 slaves.

The master node is experiencing ReadOnly filesystem mode and 100% CPU usage. Is it safe to evict pods from the master node so they spin up on other nodes, so we can back up the data?

Or will it also evict the control plane?

**Comment by brandond** [comment]
K3s does not run any control-plane components as pods. Unless you have some critical component that you've deployed yourself and are running on master, you should be fine to evict from that node.

If the system is at 100% cpu utilization and has a read-only filesystem I'd be surprised if K3s is working though; you might find that you just need to run k3s-killall.sh and then restart the k3s server once things have stabilized.

**Comment by turowicz** [comment]
@brandond we are currently backing up data files using https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/

as soon that is done we will start experimenting

**Comment by turowicz** [comment]
BTW the `--cluster-init` flag should be more visible to the beginners. Had we installed our cluster with etcd replicated this would be a non issue (disk failure on one of the nodes).

**Comment by brandond** [comment]
That will cover your Longhorn volumes, but not any of the K3s cluster state.

The install docs cover multiple High Availability options; is there some way we could make that more obvious? Having a single server should be an obvious single point of failure, regardless of what args you use to start it up.
https://rancher.com/docs/k3s/latest/en/installation/

**Comment by turowicz** [comment]
I wasn't aware that you need `--cluster-init` to make it a multimaster setup. Back in the day we have realized this AFTER setting up all services from scratch on the three-node kit. We had ran out of time to start all over again with that specific flag. We have scheduled to rebuild everything with the flag 2 weeks from now. Unfortunately the disk failed today.

**Comment by turowicz** [comment]
> I wasn't aware that you need `--cluster-init` to make it a multimaster setup.

Initially

There could be an outright recommendation to always use cluster init coz ya never know

**Comment by brandond** [comment]
As of newer releases you can add --cluster-init to an single-node server and it will convert it over to etcd; from there you can add additional servers. 

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/#existing-clusters

We don't recommend etcd by default, as K3s is frequently used to host a single-node clusters where the additional overhead of etcd is unnecessary. SQlite is far less demanding in terms of disk/CPU/memory.

**Comment by turowicz** [comment]
> We don't recommend etcd by default because K3s is frequently used to host a single-node clusters where the additional overhead of etcd is unnecessary. SQlite is far less demanding in terms of disk/CPU/memory. Etcd IS the default for RKE2, which is almost exclusively used in multi-node deployments.

I figured that. Nevertheless its an important decision point with no return that should be explicitly mentioned in the quick start guide.

**Comment by turowicz** [comment]
> As of newer releases you can add `--cluster-init` to a single-node server and it will convert it over to etcd; from there you can add additional servers.

Can you show me how? I have some single-node deployments that will be scaled horizontally in the future.

**Comment by turowicz** [comment]
@brandond  Question 2: If I have K3s 1.21.x, will updating to a newer one allow me to do the conversion to multi-master?

**Comment by brandond** [comment]
> I figured that. Nevertheless its an important decision point with no return that should be explicitly mentioned in the quick start guide.

It is no longer a critical decision point, since you can switch to etcd later.

> Can you show me how? I have some single-node deployments that will be scaled horizontally in the future. Which K3s versions?

I linked to the docs up above.

> If I have K3s 1.21.x, will updating to a newer one allow me to do the conversion to multi-master?

yes.

**Comment by turowicz** [comment]
@brandond so we run the install script again with the flag or do we add the flag to the kubelet?

**Comment by brandond** [comment]
You can re-run the install script again, which will add the flags to the arg to the systemd unit, or you can cut out the middle man and just edit the systemd unit yourself to add the flag.
