### ISSUE TITLE
k3s won't run without audit log directory 

### ISSUE THREAD

**Issue by stanleytho** [k3s-io/k3s#5285]
**Environmental Info:**
K3s Version: 
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux 3.10.0-1160.15.2.el7.mcp.x86_64 

Cluster Configuration:
1 server 

**Describe the bug:**
the k3s service won't run if the audit log directory was missing. 

```
INFO[0000] Node token is available at /var/lib/rancher/k3s/server/token
INFO[0000] To join node to cluster: k3s agent -s https://100.123.227.254:6443 -t ${NODE_TOKEN}
I0317 21:39:53.460223   28428 shared_informer.go:240] Waiting for caches to sync for node_authorizer
INFO[0000] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml
INFO[0000] Run: k3s kubectl
Error: ensureLogFile: open /var/log/kube-audit/audit-log.json: no such file or directory
FATA[0000] apiserver exited: ensureLogFile: open /var/log/kube-audit/audit-log.json: no such file or directory
```

this is the config for the audit log 
 - audit-log-path=/var/log/kube-audit/audit-log.json
 
to fix this issue I have to manually create a kube-audit directory and restart the k3s ` /bin/k3s server --config /etc/rancher/k3s/k3s_config.yaml`

is the log path created automatically when the k3s service start? 

**Step to reproduce**
stop k3s service
remove audit-log folder 
start k3s service

**Comment by brandond** [comment]
No, neither K3s nor the Kubernetes apiserver will create paths to hold log files. Whatever path you want to contain logs should exist before starting K3s.

**Comment by stanleytho** [comment]
Thank you, 

The log output is in json format so we just name it .json.

**Comment by brandond** [comment]
I think technically it is multiple lines each containing a complete JSON chunk; the suggested extension for that is `.jsonl`: https://jsonlines.org/
