### ISSUE TITLE
[release-1.22] Embedded etcd server does not account for exceeding database space

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5291]
Backport to branch **release-1.22**:
* https://github.com/k3s-io/k3s/issues/4787

**Comment by mdrahman-suse** [comment]
Reproduced the issue in k3s with v1.22.7+k3s1 and Verified the fix with v1.22.8-rc1+k3s1 by following the steps and recording the observations as described in https://github.com/k3s-io/k3s/issues/4787#issuecomment-1076451785
