### ISSUE TITLE
Master Down, Entire Cluster Down

### ISSUE THREAD

**Issue by cawoodm** [k3s-io/k3s#5299]
We have a 2 node K3S cluster with one master and one worker node and would like "reasonable availability" in that, if one or the other nodes goes down the cluster still works. We have an external load balancer (F5) which does active health checks on each node and only sends traffic to up nodes.

**Unfortunately, if the master goes down the worker will not serve any traffic (ingress).**

This is strange because all the pods on the worker node are running.

We suspect the reason is that key services such as the `traefik` ingress controller and `coredns` are only running on the master.

Indeed when we simulated a master failure, restoring it from a backup, none of the pods on the worker could do any DNS resolution. Only a reboot of the worker solved this.

We've tried to increase the number of replicas of the `traefik` and `coredns` deployment which helps a bit BUT:
* This gets lost on the next reboot
* The worker still functions when the master is down but every 2nd request fails
  * It seems the worker still blindly (round-robin) sends traffic to a non-existant master

We would appreciate some advice and explanation:
* Should not key services such as `traefik` and `coredns` be DaemonSets by default?
* How can we change the service description (e.g. replica count) in a persistent way
* How can we get intelligent traffic routing to only "up" nodes
* Would it make sense to make this a 2-master cluster?

**Comment by zanehala** [comment]
[Per the documentation](https://rancher.com/docs/k3s/latest/en/installation/ha/) you can set up a HA cluster with 2 masters you'll just need an external datastore. 
The only way to use the built in etcd datastore is to have an [odd number of masters](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/), this is a hard requirement for etcd as I understand it.

**Comment by cawoodm** [comment]
Thanks,
we've actually managed some degree of HA with `externalTrafficPolicy: Local` on the `traefik` load balancer and running 2 replicas of `coredns` and `traefik` ingress controllers. 

Unfortunately scaling these Deployments gets lost when K3S restarts. Do you have any ideas on how to switch `traefik` and `coredns` to DaemonSets in a persistent way?

**Comment by cawoodm** [comment]
OK, I see we can edit these files:
* `/var/lib/rancher/k3s/server/manifests/coredns.yaml`
* /var/lib/rancher/k3s/server/manifests/traefik.yaml
  * Alternatively edit HelmChartConfig `traefik`

However, I don't see how to persist this change:
```
kubectl patch svc traefik -n kube-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'
```

It seems to get lost if the server reboots.

**Comment by zanehala** [comment]
You would need to add that to the traefik.yaml file you listed above for the changes to persist, or alternatively you could just disable it and install the helm chart yourself.

**Comment by cawoodm** [comment]
There is no Service in the traefik.yaml - we've added it to the HelmChartConfig:
```bash
kubectl edit helmchartconfig -n kube-system
```
Add the following lines
```yaml
service:
  spec:
    externalTrafficPolicy: Cluster
```

**Comment by cawoodm** [comment]
When I change `coredns.yaml` to `kind: Deployment` and remove `replicas` and `strategy` it will not deploy:
> ApplyManifestFailed - Applying manifest at "/var/lib/rancher/k3s/server/manifests/coredns.yaml" failed: failed to discover client for apps/v1, Kind=Daemonset

**Comment by zanehala** [comment]
> There is no Service in the traefik.yaml - we've added it to the HelmChartConfig:
> 
> ```shell
> kubectl edit helmchartconfig -n kube-system
> ```
> 
> Add the following lines
> 
> ```yaml
> service:
>   spec:
>     externalTrafficPolicy: Local
> ```

Ah I see, editing via kubectl as I understand it is not persistent and won't save to disk, you'd need to go manually edit the yaml on the hosts themselves.



> When I change `coredns.yaml` to `kind: Deployment` and remove `replicas` and `strategy` it will not deploy:
> 
> > ApplyManifestFailed - Applying manifest at "/var/lib/rancher/k3s/server/manifests/coredns.yaml" failed: failed to discover client for apps/v1, Kind=Daemonset

Similarly as above, I would leave most of the coredns.yaml alone and set the replica count to 2, the k8s scheduler _should_ try to schedule the 2 pods on the seperate hosts by itself.

**Comment by cawoodm** [comment]
I've done as you said.

We still get really bad availability when one of the nodes goes down. We have an external F5 Load Balancer which only sends traffic to a node if it's healthy and when the worker goes down all traffic goes to the master BUT we still see 50% of requests fail. I presume because the master is still sending traffic to the down worker. It takes the master 30s to notice the worker is down. I am unsure where the problem is:
* svclb-traefik?
* traefik ingress controller?
* kube-proxy?
* my own nginx pod?

**Comment by cawoodm** [comment]
No, it's a bit of an enigma.

My current theory is that the endpoints (which belong to the services) are still listing pod IPs which no longer exist. Since the worker node has no access to the cluster/kubernetes API (because the master is down) there is no way for it to know it should not send traffic to dead pods.

What is very strange however is that when the *Worker* goes down I also have bad availability. This I cannot explain.

**Comment by dyipon** [comment]
we had the same situation, tried the next points, maybe some of them can help you:
1. settings for k3s-server:
_-kube-apiserver-arg default-not-ready-toleration-seconds=20 --kube-apiserver-arg default-unreachable-toleration-seco
nds=20 --kube-controller-arg node-monitor-period=20s --kube-controller-arg node-monitor-grace-period=20s --kubelet-arg node-status-update-frequency=5s --kube-controller-arg pod-eviction-timeout=30s_

2. disabled TCP keepalive on nginx pods ( _keepalive_timeout 0;_ )

3. setuped a frequent readiness and liveness probes ( _periodSeconds: 2_ )

4. but after all, we had to write an own operator to check and disable endpoints in Service upon failures - finally we reached 1-2sec downtime if any pod/node goes down

**Comment by cawoodm** [comment]
We've just installed a 2-master (embedded etcd) cluster and can confirm that if either of the nodes goes down the entire cluster is down (services not accessible or only intermittently). Interestingly the Kubernetes API on the UP node is inaccessible so we could not investigate further. I suspect the services still have endpoints on the DOWN node.

I find this very strange since ALL our services are available on BOTH nodes. It seems however that the Kubernetes API just stops working if "half" the cluster is missing. I know, I know - use a 3-node cluster...

**Comment by cawoodm** [comment]
You're dead right but this is so unintuitive: we start with a working single node (embedded etcd) cluster, add a node, remove the node and it's broken. I know it's "Raft" but geeze...

Did another test today taking a worker down in a single master (2-node cluster). It takes about 30s for the master to notice the worker is down and remove it's pod IPs from the endpoints. Once it does this, the cluster recovers and stops sending traffic to non-existant pods. I think we need to implement @dyipon 's suggestions somehow in k3s.

**Comment by cawoodm** [comment]
Tested a 3 master HA embedded etcd cluster today. What a disaster. Would not run stably. As far as I can see etcd was very fragile, freaking out if it couldn't see a node and shutting things down.

**Comment by cawoodm** [comment]
> 1. -kube-apiserver-arg default-not-ready-toleration-seconds=20 --kube-apiserver-arg default-unreachable-toleration-seconds=20 --kube-controller-arg node-monitor-period=20s --kube-controller-arg node-monitor-grace-period=20s --kubelet-arg node-status-update-frequency=5s --kube-controller-arg pod-eviction-timeout=30s

@dyipon Why did you use such a long `pod-eviction-timeout=30s`? In my experience the downtime is about 30s before K8S evicts a dead node (or rather it's pods). So I would start with this setting...

**Comment by cawoodm** [comment]
@brandond Could you advise on how to pass multiple `kube-apiserver-args` via the config YAML?

Tried and failed with the following variations:
```yaml
kube-apiserver-arg:
  - 'node-monitor-period=2s'
  - 'node-monitor-grace-period=5s'
  - 'node-status-update-frequency=2s'
  - 'pod-eviction-timeout=5s'
```

```yaml
kube-apiserver-arg:
  - node-monitor-period: 20s
  - node-monitor-grace-period: 20s
  - node-status-update-frequency: 5s
  - pod-eviction-timeout: 5s
```

```yaml
kube-apiserver-arg:
  node-monitor-period: 2s
  node-monitor-grace-period: 5s
  node-status-update-frequency: 1s
  pod-eviction-timeout: 5s

```


map: `apiserver exited: unknown flag: --[{default-not-ready-toleration-seconds 20} {default-unreachable-toleration-seconds 20} {node-monitor-period 20s} {node-monitor-grace-period 20s} {node-status-update-frequency 5s} {pod-eviction-timeout 5s}]"`

array: `apiserver exited: unknown flag: --[{default-not-ready-toleration-seconds 20}]`

**Comment by brandond** [comment]
I responded to your questions about the flags on the other issues, but I wanted to warn you that setting these things to extremely low intervals will probably cause your cluster to perform extremely poorly. Kubernetes isn't designed for the real-time pod-level outage response that you appear to be trying to get out of it.

**Comment by cawoodm** [comment]
If what you are saying is true then we are taking a step backwards introducing Kubernetes. In German they call it "Ettikettenschwindel" when all the marketing jargon is about High-Availability and you get worse availability when switching to complex, 3-node K8S than you had before with simple 2-Server and an external LB. I know this is not the fault of K3S and perhaps we are just using it incorrectly. It is highly irritating that our LB identifies Node B as down, routes all traffic to Node A and Node A sends traffic to a dead Node B. 🤦‍♂️

Surely there is a proper way to achieve low latency health checks so services aren't routing to dead pods for minutes at time?

**Comment by cawoodm** [comment]
Could you share your operator @dyipon ?

**Comment by dyipon** [comment]
@cawoodm sorry, but it's not possible. And would be pointless, because this operator is specified for our requirements.

**Comment by CharesLee** [comment]
Looking for a solution, I have a three-node master highly available k3s cluster, using the external database MySQL.  However, after I shut down a master server at random, I access the services in the cluster again, and all the services cannot be accessed.  In addition, the service running on the not ready node needs to wait for a long time before it can be migrated to other normal nodes, which I think is not normal.  Is it possible to complete the automatic switchover after the failure (1 minute) to improve the stability of my system

**Comment by academiaresf** [comment]
@CharesLee i also have a 3 master cluster (with 8 workers) and if we remove one master then all the cluster is down from the traefik/coredns/slb perspective. Maybe is some skill issues but the mental model about HA, in my mind, is that the masters are complete copies and when one fails the external LB (HAPROXY in my case) will forward to the next master that is healthy.

Can someone clarify this?
