### ISSUE TITLE
The `latest` tag on Docker Hub is pointing to an older version

### ISSUE THREAD

**Issue by dokmic** [k3s-io/k3s#5313]
**Environmental Info:**
K3s Version: 1.21.10+k3s1

Node(s) CPU architecture, OS, and Version: Docker

**Describe the bug:**
The `latest` tag on Docker Hub is pointing to `v1.21.10+k3s1` when the actual latest version is `v1.23.4`.

![image](https://user-images.githubusercontent.com/15189627/159160950-7f3753e5-5a66-4663-b841-ef248a11e909.png)

**Steps To Reproduce:**
```bash
docker pull rancher/k3s:latest
```

- Installed K3s: `v1.23.4`

**Expected behavior:**
There should be the latest k3s version installed.

**Comment by brandond** [comment]
Latest is just whatever release was built most recently. We should make more of an effort to sync this with the latest version published by the channel server, but at the moment you should probably continue use a specific version tag.
