### ISSUE TITLE
[Feature Request] Shell completion enhancements

### ISSUE THREAD

**Issue by HectorB-2020** [k3s-io/k3s#5316]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add `bash` and `zsh` completion enhancements like many other tools do now.
It can be implemented like this: `k3s completion`.
This will significantly simplify entering lengthy commands by typing double `Tab`.

Examples of similar functionality in `kubectl`, `helm` and `argocd`:
`kubectl completion`
`argocd completion`
`helm completion`

**Describe alternatives you've considered**

Add files directly to folder `/etc/profile.d/`.

**Additional context**
None

**Backporting**

- [ ] Needs backporting to older releases
It can be back-ported, this shouldn't break anything.

**Comment by VestigeJ** [comment]
**Validated bash using COMMIT=3e5561daca4128d8e310b22a777052ff0f1044f8**

Minor improvement opportunity would be to reduce or drop the additional command for help in the console return: 
```
$ k3s h (tab,tab)
h     help  
```

$ k3s --version
```
k3s version v1.23.6+k3s-3e5561da (3e5561da)
go version go1.17.5
```

Command listed on output
$ k3s
```
NAME:
   k3s - Kubernetes, but small and simple

USAGE:
   k3s [global options] command [command options] [arguments...]

VERSION:
   v1.23.6+k3s-3e5561da (3e5561da)

COMMANDS:
   server           Run management server
   agent            Run node agent
   kubectl          Run kubectl
   crictl           Run crictl
   ctr              Run ctr
   check-config     Run config check
   etcd-snapshot    Trigger an immediate etcd snapshot
   secrets-encrypt  Control secrets encryption and keys rotation
   certificate      Certificates management
   completion       Install shell completion script
   help, h          Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug                     (logging) Turn on debug logs [$K3S_DEBUG]
   --data-dir value, -d value  (data) Folder to hold state default /var/lib/rancher/k3s or ${HOME}/.rancher/k3s if not root
   --help, -h                  show help
   --version, -v               print the version
```

command help output prints
$ k3s completion -h
```
NAME:
   k3s completion - Install shell completion script

USAGE:
   k3s completion [SHELL] (valid shells: bash, zsh)

OPTIONS:
   -i  Install source line to rc file
```

$ k3s completion bash -i
```
Autocomplete for bash added to: /home/ubuntu/.bashrc
```

$ k3s (tab, tab)
```
agent            completion       etcd-snapshot    kubectl          
certificate      crictl           h                secrets-encrypt  
check-config     ctr              help             server  
```

$ k3s - (tab, tab)
```
--data-dir  --debug     --help      --version   -d          -h          -v
```

$ k3s a (tab,tab) -> $ k3s agent

$ k3s c (tab,tab)
```
certificate   check-config  completion    crictl        ctr
```

$ k3s e(tab,tab) -> $ k3s etcd-snapshot

$ k3s s (tab,tab) -> $ k3s se ->
```
secrets-encrypt  server
```

$ k3s --
```
--data-dir  --debug     --help      --version 
```
