### ISSUE TITLE
The Agent with Same hostname replaces the nodes

### ISSUE THREAD

**Issue by Jeyanthinath** [k3s-io/k3s#532]
**Describe the bug**
I tried setting up the k3s server and agent on two pi's in same network, both having the same hostname.

 I tried running server and agent service on one node and the agent service on another node. I _always ended up showing only one node_.

After a day of searching, I found out the nodes is replaced  by the agent in the other node, If I stop one agent service the other node with agent service is getting displayed.

**To Reproduce**
Try running two agent services with same hostname , ( I have problems on raspberry pi)

**Expected behavior**
It should at-least show error while starting the service, from the same hostname machine 
(or)
May be it should attach the node with the help of ip address

**Screenshots**
```
root@raspberrypi:/var/lib/rancher/k3s/server# k3s kubectl get nodes -o wide
NAME          STATUS   ROLES    AGE   VERSION         INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypi   Ready    <none>   24h   v1.14.1-k3s.4   192.168.1.39   <none>        Raspbian GNU/Linux 9 (stretch)   4.14.79-v7+      containerd://1.2.5+unknown
root@raspberrypi:/var/lib/rancher/k3s/server# 

<After stopping one agent service >

root@raspberrypi:/var/lib/rancher/k3s/server# k3s kubectl get nodes -o wide
NAME          STATUS   ROLES    AGE   VERSION         INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypi   Ready    <none>   24h   v1.14.1-k3s.4   192.168.1.62   <none>        Raspbian GNU/Linux 9 (stretch)   4.14.79-v7+      containerd://1.2.5+unknown
root@raspberrypi:/var/lib/rancher/k3s/server# 
```

**Additional context**

**Comment by warmchang** [comment]
In this regard, K3S is the same as K8S.

You can set the "--hostname-override" para of kubelet to make the diffirents node-name:

> --hostname-override string                            If non-empty, will use this string as identification instead of the actual hostname.

**Comment by brandond** [comment]
Closing due to age. Also, two nodes on the same network should not have the same hostname.
