### ISSUE TITLE
k3s Installation fails

### ISSUE THREAD

**Issue by ramzcode** [k3s-io/k3s#5326]
unable to install k3s using curl -sfl https://get.k3s.io 

below file is not found
https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt

**Comment by brandond** [comment]
`stable` is not a valid release version. I believe there was a brief outage for our channel server earlier this morning, please try again.

**Comment by ramzcode** [comment]
Yes all looks good now. Thank you
