### ISSUE TITLE
broken/mixed logs in containderd.log

### ISSUE THREAD

**Issue by rurus9** [k3s-io/k3s#5335]
I'm not sure if this is a good place to report this bug, but it is for containerd version=v1.5.9-**k3s1**

Cluster Configuration:

3 servers (rke2 cluster using containerd revision=d5a46d003e3079a0f4897fd97408409ab77b8e27 version=**v1.5.9-k3s1**)

**Describe the bug:**
As I understand, containerd pushes its own logs to a file containerd.log (for RKE2: /var/lib/rancher/rke2/agent/containerd/containerd.log)
Most have syntax key=value syntax: `time=DATE level=LEVEL msg=MESSAGE another_key=ANOTHER_MESSAGE`, e.g:
```
time="2022-03-16T12:26:30.747636805+01:00" level=info msg="StopPodSandbox for \"a9ec29d76a502803484c679bb6d1a4ee3f5030b16e7035f322e9dd969a6667ae\" returns successfully"
time="2022-03-16T12:26:30.747929968+01:00" level=info msg="RemovePodSandbox for \"a9ec29d76a502803484c679bb6d1a4ee3f5030b16e7035f322e9dd969a6667ae\""
time="2022-03-22T15:58:14.930347871+01:00" level=warning msg="cleaning up after shim disconnected" id=abc7c5d56247b013756f3459ea9a3c4277389424f6414bbe8f4ffb5d25fc0fa4 namespace=k8s.io
```
but sometimes we have a log in the log (note the time, level, msg fields in second log):
```
time="2022-03-16T14:13:06.358684326+01:00" level=info msg="RemoveContainer for \"d8cd561fbc6366ecb83664b58c180c600243c0f2704feaf962d42e1fbb0eb209\" returns successfully"
time="2022-03-16T14:13:06.369393578+01:00" level=warning msg="cleanup warnings time=\"2022-03-16T14:13:06+01:00\" level=info msg=\"starting signal loop\" namespace=k8s.io pid=78873\n"
time="2022-03-16T14:13:07.941624436+01:00" level=info msg="TearDown network for sandbox \"c711dc176dfccab27338e069a7f34e1781333fd7a3104fbdcd6fccdd91371422\" successfully"
```
sometimes logs appear in a completely different format:
```
2022-03-16 14:13:00.273 [INFO][77942] k8s.go 563: Cleaning up netns ContainerID="5ec424996a253fc02b248e1633ff6ccf139c140a8cc2e9d5f2ac81373ef56135"
2022-03-16 14:13:00.273 [INFO][77942] k8s.go 570: Releasing IP address(es) ContainerID="5ec424996a253fc02b248e1633ff6ccf139c140a8cc2e9d5f2ac81373ef56135"
2022-03-16 14:13:00.273 [INFO][77942] utils.go 196: Calico CNI releasing IP address ContainerID="5ec424996a253fc02b248e1633ff6ccf139c140a8cc2e9d5f2ac81373ef56135"
```
**Expected behavior:**

All logs in containderd.log in the same format.
**Actual behavior:**

Mixed/broken (log in log) logs format.
**Additional context / logs:**

Log processing systems (fluentd, logstash etc) expect a clear definition of the log structure, otherwise, automatic processing is not possible.

**Comment by brandond** [comment]
I believe what you're seeing is containerd passing through the logs from the CNI helpers that are executed to set up container networking. In this case, they appear to be logs from the Calico components. It's not something that would be fixable by RKE2, K3s, or containerd, since none of these projects have control over the logs output by the various CNI plugins. You'd need to chase it down with the CNI projects themselves and ask them to use a different log format.

**Comment by rurus9** [comment]
OK, I understand the mechanism behind these different logs.
Thanks for the clarification.
