### ISSUE TITLE
CRDT based Control Plane State

### ISSUE THREAD

**Issue by malarinv** [k3s-io/k3s#5347]
**Is your feature request related to a problem? Please describe.**

Etcd being a strongly consistent kv store, it compromises on availability for edge use-cases, A lightweight eventually consistent control-plane state storage based on CRDTs could make k0s much more scalable and efficient.

**Describe the solution you'd like**

Well described in this paper https://dl.acm.org/doi/pdf/10.1145/3434770.3459730

**Describe alternatives you've considered**

All other solutions aren't as performant(claimed) as the CRDT based solution

**Additional context**

This could be an unique/special feature of k3s :wink: 
I am not the author of the paper just found it to be an interesting read which might improve k3s/k0s. So here I am.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
That paper seems to be long on analysis but short on actual actionable conclusions. Is there a particular library or implementation of the suggested alternative datatype available to consume?

**Comment by malarinv** [comment]
Not aware of a library that exposes a storage interface but the json crdt part seems to be covered by https://github.com/gpestana/rdoc. it is an implementation of https://arxiv.org/abs/1608.03960 [27]th reference on the original paper.

**Comment by malarinv** [comment]
The actual persistence service which uses Json CRDT probably has to be implemented. The design might be similar to Kine, except using a kubernetes hosted _Json CRDT store_ rather than an external SQL store.

**Comment by brandond** [comment]
You might take a look at https://github.com/k3s-io/kine/pull/115
