### ISSUE TITLE
Agent nodes require a control-plane node to join cluster instead of either that OR etcd-only node

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#5348]
If giving the IP of an etcd-only node, the agent will fail to join the cluster with constant looping logs like:
```
Mar 28 19:52:32 ip-172-31-39-31 k3s[1558]: time="2022-03-28T19:52:32Z" level=info msg="Connecting to proxy" url="wss://172.31.32.154:6443/v1-k3s/connect"
Mar 28 19:52:32 ip-172-31-39-31 k3s[1558]: time="2022-03-28T19:52:32Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

This gets confusing because in a setup of just 1 etcd-only node, 1 cp-only node, and 1 agent, one must setup the etcd-only node first, then join the cp-only node using the etcd-only node's IP, then join the agent using now the cp-only node's ip. Joining other etcd-only, cp-only, or all-role nodes (default server node) does not have this limitation. 

Note this happens in all versions of both k3s and rke2.

**Comment by ShylajaDevadiga** [comment]
Is it safe to say version used is v1.23.5-rc3+k3s1 so we have a version to refer when we have a fix?

**Comment by rancher-max** [comment]
Yep, all three of these rcs:
v1.23.5-rc3+k3s1, v1.22.8-rc3+k3s1, and v1.21.11-rc3+k3s1

**Comment by brandond** [comment]
I test this and confirmed that it has been occurring as far back as v1.22.5+k3s1 before giving up, so it's been around for a bit.

**Comment by rancher-max** [comment]
#### Validated on master branch using commitid `5cb4894a5066ef31ebdb5b45b6f3bdac4cd4581d`

- Agent node is able to join using etcd node's ip
- Agent node is still able to join using cp node's ip

@brandond Are we planning on backporting this to 1.22 and 1.21 as well or just in the 1.23+ line?

**Comment by brandond** [comment]
I am planning on backporting it back to both.

**Comment by rancher-max** [comment]
I'll close this out and create some simple backport issues! Thank you!
