### ISSUE TITLE
Failed to get unit file state for nm-cloud-setup.service

### ISSUE THREAD

**Issue by litcc** [k3s-io/k3s#5350]
**Environmental Info:**
- K3s Version: 
k3s version v1.23.4+k3s1 (43b1cb48)
go version go1.17.5

- Node(s) CPU architecture, OS, and Version: 

Linux iZwz9dkmg7ytg42k8bu3nmZ 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

- Cluster Configuration:
1 server

- **Describe the bug:**
Failed to get unit file state for nm-cloud-setup.service: No such file or directory
k3s won't start

- **Steps To Reproduce:**

- Installed K3s: 
The k3s.sh used is basically the same as the k3s.sh in the github repository
```shell
curl -sfL https://lovol-file.oss-accelerate.aliyuncs.com/binary-file/shell/k3s.sh | GITHUB_URL="https://ghproxy.com/https://github.com/k3s-io/k3s/releases" INSTALL_K3S_VERSION=v1.23.4+k3s1 INSTALL_K3S_MIRROR=cn INSTALL_K3S_EXEC=server K3S_NODE_NAME=shenzhen-47.**.54 K3S_AGENT_TOKEN="QtG097Al5EgB2pAbEe0xWqdMw5338mB7d" K3S_DATASTORE_ENDPOINT="mysql://my_cluster:**@tcp(example.com:3306)/my_cluster" bash -s - --bind-address 0.0.0.0 --advertise-address 47.**.54 --tls-san 47.**.54 --tls-san 192.168.0.208 --kube-apiserver-arg 'bind-address=0.0.0.0' --node-ip 47.**.54 --node-external-ip 47.**.54 --default-local-storage-path /opt/k3s/local-storage
```

- **Expected behavior:**
Start k3s normally , I want to know how to fix him

- **Actual behavior:**

The commands are basically the same, the same machine, using the previous old version can run normally, the latest version can not run

- **Additional context / logs:**

![image](https://user-images.githubusercontent.com/13202561/160525496-85d47b84-e7da-497b-8d2d-f6e696ba94f8.png)

```
The job identifier is 494857 and the job result is done.
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ systemd[1]: Starting Lightweight Kubernetes...
░░ Subject: A start job for unit k3s.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit k3s.service has begun execution.
░░
░░ The job identifier is 494857.
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ sh[204575]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ sh[204576]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ k3s[204579]: time="2022-03-29T11:10:17+08:00" level=info msg="Starting k3s v1.23.4+k3s1 (43b1cb48)"
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ k3s[204579]: time="2022-03-29T11:10:17+08:00" level=fatal msg="starting kubernetes: preparing server: creati>
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit k3s.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ systemd[1]: k3s.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit k3s.service has entered the 'failed' state with result 'exit-code'.
Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ systemd[1]: Failed to start Lightweight Kubernetes.
░░ Subject: A start job for unit k3s.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit k3s.service has finished with a failure.
░░
░░ The job identifier is 494857 and the job result is failed.

```

- **Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
The nm-cloud-setup message is not an error. K3s checks to ensure that nm-cloud-setup is NOT running before starting K3s.

There is another error message, but you have truncated your log lines so I can't see what it is. Can you post the complete journactl log entry?
`Mar 29 11:10:17 iZwz9dkmg7ytg42k8bu3nmZ k3s[204579]: time="2022-03-29T11:10:17+08:00" level=fatal msg="starting kubernetes: preparing server: creati>`

**Comment by litcc** [comment]
Very sorry, the logs are not shown in full, I have found the problem in the full logs

**Comment by unknownzone96** [comment]
Maybe "Failed to get unit file state for nm-cloud-setup.service: No such file or directory" should not be logged or wording should be changed, as now it is implying an erroneous configuration.

The same is seen with https://github.com/k3s-io/k3s/issues/4911

**Comment by brandond** [comment]
That is the message that systemd prints when the unit file cannot be found, which is the desired state. For some reason people just stop reading the logs when they see that and don't make it to the actual error message.

**Comment by litcc** [comment]
is the case, the main problem is not looking closely at the logs.
The problem I met before is because the cluster database based on mysql database high availability already has data, so it can't overwrite the installation, so there is a problem; finally delete the library and reinstall it is fine
