### ISSUE TITLE
How to provide a KubeSchedulerConfiguration ?

### ISSUE THREAD

**Issue by JBaptisme33** [k3s-io/k3s#5354]
Hi,

I'm trying to configure topo-lvm provisionner into k3s.
Unfortunately, kube-scheduler need to be re-configured to ignore topo-lvm PVC creation, via this config:
https://github.com/topolvm/topolvm/blob/main/deploy/README.md#configure-kube-scheduler
https://github.com/topolvm/topolvm/blob/main/deploy/scheduler-config/scheduler-config-v1beta2.yaml

It seem impossible to do so into K3S seem kube-scheduler and his API is not accessible ?

Thanks for hard work,

**Comment by brandond** [comment]
you can pass args to kube-scheduler via the `--kube-scheduler-arg` flag on servers. For example, `--kube-scheduler-arg=config=/var/lib/scheduler/scheduler-config.yaml`. Is there something beyond this that does not seem possible?

**Comment by JulianTS** [comment]
I got a similar problem. 


> For example, `--kube-scheduler-arg=config=/var/lib/scheduler/scheduler-config.yaml`. 

That command throws an `--kube-scheduler-arg=config=: command not found` error on my machine.
did I do something wrong?

I want to run a scheduler configuration file from the  [tutorial](https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles) in K3s, currently only for testing 

but that ApiVersion is probably also incompatible with my K3s version

**Comment by brandond** [comment]
> That command throws an `--kube-scheduler-arg=config=: command not found error` on my machine.

That's not a command to run, it's an option to add to the K3s command-line arguments.

**Comment by JulianTS** [comment]
@brandond Thanks for the fast response!

So this e.g. is an installation with a configured scheduler, correct?
`curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - k3s server --kube-scheduler-arg=config=/var/lib/scheduler/scheduler-config.yaml`

I'm getting this output:
[INFO]  Finding release for channel stable
[INFO]  Using v1.23.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.23.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.23.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-k3s.service
[INFO]  systemd: Enabling k3s-k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s-k3s.service → /etc/systemd/system/k3s-k3s.service.
[INFO]  systemd: Starting k3s-k3s

**Comment by brandond** [comment]
Yes, that looks like the output of the installer. Is there some problem with it?

**Comment by brandond** [comment]
If you're providing a scheduler config you need to provide ALL the config, as passing a config causes it to skip other CLI flags - such as those that tell it what kubeconfig to use. This is covered in the docs:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
> 
>**--kubeconfig string**
>DEPRECATED: path to kubeconfig file with authorization and master location information. This parameter is ignored if a config file is specified in --config.
