### ISSUE TITLE
Incomplete uninstall with longhorn

### ISSUE THREAD

**Issue by chad-autry** [k3s-io/k3s#5360]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

After uninstalling a system using k3s-uninstall.sh on a system with longhorn persistent volumes, and then re-installing there are continuous iscsid logs that fill up /var/logs    sudo journalctl -u iscsid

`Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:27 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 03 07:50:29 dmspcsfbackuprestore-manual6.idm.dev.entrust.com iscsid[2650]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)`

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

k3s uninstall should correctly uninstall longhorn

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Longhorn and any other CSI that attaches volumes probably need specific cleanup. I'm not sure that this should be the responsibility of K3s to be aware of though; whatever CSI you deploy will have its own specific steps to clean up a node.

**Comment by PhanLe1010** [comment]
Looks like Longhorn was killed unexpectedly and cannot clean up the iscsi database. Can you check the iscsi database (`/var/lib/iscsi/nodes` for RHEL, `/etc/iscsi/nodes/` for ubuntu, etc...) and clean up that folder?

**Comment by PhanLe1010** [comment]
I am thinking if we can detect the orphan iscsi targets and remove them automatically @shuo-wu @joshimoo . Anything with the format `iqn.2019-10.io.longhorn:testvol` and currently not corresponding to any volume can be removed. This logic can be inside the instance manager e. How do you think?

**Comment by brandond** [comment]
Thanks @PhanLe1010 - that would definitely help users that will be re-deploying Longhorn again to the same node. Is there a cleanup script that users could run if they do not plan on using Longhorn again?

**Comment by PhanLe1010** [comment]
I don't think we have a cleaning-up script

**Comment by shuo-wu** [comment]
I prefer not to involve Longhorn instance managers. By design, Longhorn instance manager does not know anything about the engine/replica details, including the iSCSI configs. Besides, this issue happens when Longhorn does not correctly. Using a stand-alone script would be better.
