### ISSUE TITLE
Containerd API version too old

### ISSUE THREAD

**Issue by profhase** [k3s-io/k3s#5378]
**Environmental Info:**
K3s Version:
``` 
k3s version v1.20.15+k3s1 (c7a91e1c)
go version go1.15.15
```

Single node cluster

**Describe the bug:**
I am trying to get woodpecker running, that is a CI engine that needs to spin up containers
Client exits with:
```
client version 1.41 is too new. Maximum supported API version is 1.40
```
So apparently containerd is too old.
```
/usr/local/bin/crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.4.12-k3s1
RuntimeApiVersion:  v1alpha2
```
I could not find anywhere in the docs if i can install containerd or how to configure either the containerd version for k3s or how to tell k3s to use containerd installed on the system (as systemd service). 

The Runtime version looks very much alpha, is this desired?

Could you please help there

**Comment by brandond** [comment]
Please upgrade to a newer release of K3s. 1.22 and 1.23 releases of K3s include Containerd 1.5.

The Kubernetes CRI API is still in alpha, that is to be expected.

**Comment by profhase** [comment]
@brandond thank you. If I would install a regular containerd as of here:

https://containerd.io/docs/getting-started/#systemd-based-distributions

Would k3s then use that one or does it require it's own?

**Comment by brandond** [comment]
You can use your own containerd and point k3s at it by setting the `--container-runtime-endpoint` to point at the containerd socket.
