### ISSUE TITLE
coredns issues with k3s on openSUSE MicroOS using kernel 5.16.15 or later (5.17.1): cluster broken due to DNS not working

### ISSUE THREAD

**Issue by johanneskastl** [k3s-io/k3s#5379]
**Environmental Info:**
K3s Version: 
- v1.22.6+k3s1
- v1.22.7+k3s1
- v1.22.8+k3s1
- v1.23.3+k3s1

Node(s) CPU architecture, OS, and Version: 

- multiple x86_64 machines of different CPUs
- one Raspberry Pi 4 

Cluster Configuration:
- one three-node cluster (v1.22.6+k3s1, three servers, no agents)
- all other machines are singlenode clusters (3x x86_64, 1x Raspi4)

**Describe the bug:**
Using a kernel 5.16.15.1 or later leads to coredns not getting connections to the outside, and thus never getting LIVE. This leads to many other pods running into CrashLoopBackOff if they rely on cluster-internal DNS.

The logs of the coredns pod contain errors like the following, until it terminates and restarts the pods:

```
[ERROR] plugin/errors: 2 2710547001195683759.7881225443334916626. HINFO: read udp 10.0.0.190:35403->192.168.99.1:53: i/o timeout 
[ERROR] plugin/errors: 2 2710547001195683759.7881225443334916626. HINFO: read udp 10.0.0.190:35711->192.168.99.121:53: i/o timeout
```
(192.168.99.1 and 192.168.99.121 are the local DNS resolver and the nodes IP address)

Rolling back to a openSUSE MicroOS BTRFS snapshot containing kernel 5.16.14.1 (`14`, not `15`) makes the cluster working again.

**Steps To Reproduce:**
- Installed K3s without servicelb and without Traefik
- install MetallLB via helm
- install Traefik via helm
- install workload
- openSUSE MicroOS updates the node to 5.16.15 => problem
- rollback to 5.16.15 => cluster running again

**Expected behavior:**
Cluster working :-)

**Actual behavior:**
- coredns broken
- cluster-internal DNS not working
- (DNS from cluster to outside not working)
- hence many pods running into CrashLoopBackOff errors

**Backporting**
- [?] Needs backporting to older releases

**Comment by brandond** [comment]
Have you opened an issue with MicroOS? It sounds like a kernel issue.

**Comment by johanneskastl** [comment]
Hi @brandond,

I was checking the bugzilla for openSUSE for related issues, after opening up the discussion on the opensuse-kubic mailinglist (where most of the kubic and MicroOS folks are subscribed). I am currently preparing an issue as I found none that fits.

I wanted to raise awareness within k3s, to watch out for this issue, as I cannot tell if this is an error inside the kernel, changed behaviour inside the kernel, or any other incompatibility.

**Comment by johanneskastl** [comment]
Here is the openSUSE bug report:
https://bugzilla.opensuse.org/show_bug.cgi?id=1198064

**Comment by manuelbuil** [comment]
Next time this happens to you, could you please check that `/net/ipv4/conf/all/forwarding` is set to 1 and especially the main interface, e.g. `/net/ipv4/conf/eth0/forwarding`. We found some inconsistencies when using wicked and rke2 and it could be that k3s is also impacted: https://docs.rke2.io/known_issues/#wicked

**Comment by johanneskastl** [comment]
> Next time this happens to you, could you please check that `/net/ipv4/conf/all/forwarding` is set to 1 and especially the main interface, e.g. `/net/ipv4/conf/eth0/forwarding`. We found some inconsistencies when using wicked and rke2 and it could be that k3s is also impacted: https://docs.rke2.io/known_issues/#wicked

Hi Manuel,
thanks for the hints, I checked that and all looked good.

After @SchoolGuy replied in bugzilla I investigated some more, and currently it looks like this is caused by breakage in cilium due to the new kernel version. I could get the cluster running again by switching to flannel. That fits the pattern from another bugzilla where people had issues with weave due to the same kernel upgrade.

So, closing this issue as it seems this is not related to k3s itself or coredns or other parts being provided by k3s.

**Comment by johanneskastl** [comment]
And yet again I have to eat my words, so for the record:
The cluster seem to be working again, i.e. switching to flannel leads to the coredns pod reaching LIVE status.

But after that I still have lots and lots of errors in the coredns pod logs due to DNS timeouts. So it seems like flannel is also affected, at least in my clusters (or maybe something broke during switching to flannel)

:-(

**Comment by manuelbuil** [comment]
> And yet again I have to eat my words, so for the record: The cluster seem to be working again, i.e. switching to flannel leads to the coredns pod reaching LIVE status.
> 
> But after that I still have lots and lots of errors in the coredns pod logs due to DNS timeouts. So it seems like flannel is also affected, at least in my clusters (or maybe something broke during switching to flannel)
> 
> :-(

Did you check the parameters I mentioned? Is it only DNS or the traffic pod ===> internet is also affected?

**Comment by johanneskastl** [comment]
Sorry for the late reply, was on business travel...

> Did you check the parameters I mentioned? Is it only DNS or the traffic pod ===> internet is also affected?

Yes, I had checked them, and everything looked fine.

From what I found it looks like the whole networking to the outside is broken:
- DNS queries are not working
- ping against an IP not working
- `wget` against an IP address is not working

**Comment by johanneskastl** [comment]
But:
The same issue starts happening on a k3s cluster running on RockyLinux8. Also using cilium and Traefik.
So this might be entirely unrelated to the kernel version.

Upgrading k3s to 1.23.6 did not improve the situation.

```
NAME             STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                           KERNEL-VERSION                 CONTAINER-RUNTIME
some-host   Ready    control-plane,master   104d   v1.23.6+k3s1   XXX   <none>        Rocky Linux 8.6 (Green Obsidian)   4.18.0-348.20.1.el8_5.x86_64   containerd://1.5.11-k3s2
```

Another one of the broken cluster (on openSUSE MicroOS) was also updated to 1.23.6, the one using flannel. But though coredns says it is running (at least the pod is "healthy"), the workload is still broken and cannot communicate with the outside apparently.

**Comment by johanneskastl** [comment]
Just to close this topic properly:

Seems like this was caused by cilium being broken due to a missing sysctl parameter. The [latest 1.11.7 documentation](https://docs.cilium.io/en/v1.11/operations/system_requirements/) states that systemd >=245 causes issues:

```
Systemd 245 and above (systemctl --version) overrides rp_filter setting of Cilium network interfaces. This introduces connectivity issues (see [GitHub issue 10645](https://github.com/cilium/cilium/issues/10645) for details). To avoid that, configure rp_filter in systemd using the following commands:

echo 'net.ipv4.conf.lxc*.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
systemctl restart systemd-sysctl
```

I did not notice that warning in the docs at the time the problem started, or it was not present back then, I do not know. However I tried the workaround and my clusters started working properly again.

Thanks for your help!

**Comment by torsten-online** [comment]
Hi,

I run into same issue with latest K3S v1.25.3+k3s1, Rancher and OpenSuSE Micro, also selinux configured.

For me, I was assuming that the default settings will use /etc/resolv.conf, because the checkup of coredns looks like this setting.

As I changed the systemd unit to use /etc/resolv.conf - it was fixing that kind of stupid issue!

I wrote a short gist about that:

## DNS Issue K3S + Rancher with OpenSuSE MicroOS

If you run into the issue, that DNS Resolving is not possible with K3S, Rancher, OpenSuSE MicroOS and SELinux enabled:

Please make sure, that the following Settings at K3S SystemD Unit are enabled:

- /etc/systemd/system/k3s.service

```
ExecStart=/usr/local/bin/k3s \
    server \
        '--cluster-init' \
        '--selinux' \
        '--resolv-conf=/etc/resolv.conf' \
```

Using the /etc/resolv.conf seems not to be the "working" default setting at OpenSuSE MicroOS,
but CoreDNS Config shows these setting, so I dont really understand - why these was not working:

```
kubectl get cm coredns -o yaml -n kube-system
```


```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.1.100 my-k3s-master
    192.168.1.101 my-k3s-node1
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  labels:
    objectset.rio.cattle.io/hash:
  name: coredns
  namespace: kube-system
```

It is also possible with the daemon-settings, to use another dns server config, e.g. at /etc/rancher/k3s/resolv.conf

For me it will be helpful, why the standard settings of coredns with opensource is configured to use /etc/resolv.conf, but it was not working fine?

Another Setup with Debian Bullseye was working well for me, without that requirement of configure /etc/resolv.conf at the systemd unit. 

https://gist.github.com/torsten-online/092df9369e47862f97d28e4c702f5ab4

I will be happy, if my short suggestion will be helpful, if you run into a similar dns issue, which u dont understand  really :)
