### ISSUE TITLE
systecm restarts k3s, which causes   coredns dropping configmap configuration

### ISSUE THREAD

**Issue by MagicStarTrace** [k3s-io/k3s#5394]
OS  Version:   ubuntu 18.04
k3s Version:   1.21.4+k3s1

kubectl describe   configmaps   coredns  -n kube-system 
Name:         coredns
Namespace:    kube-system
Labels:       objectset.rio.cattle.io/hash=bce283298811743a0386ab510f2f67ef74240c57
Annotations:  objectset.rio.cattle.io/applied:
                {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n  ...
              objectset.rio.cattle.io/id: 
              objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
              objectset.rio.cattle.io/owner-name: coredns
              objectset.rio.cattle.io/owner-namespace: kube-system

Data
====
Corefile:
----
.:53 {
    errors
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    hosts /etc/coredns/NodeHosts {
    192.168.100.1  datamart.tool.com
    192.168.100.10 bigdata.tool.com
    192.168.100.11 employee.tool.com
      ttl 60
      reload 15s
      fallthrough
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}

command : systecm restarts k3s ,  After restarting k3s, the following configuration is lost(Rebooting the server can also cause configuration loss)

    192.168.100.1  datamart.tool.com
    192.168.100.10 bigdata.tool.com
    192.168.100.11 employee.tool.com

How can this be solved?
What is causing the problem?
Thank You!

**Comment by brandond** [comment]
The coredns configmap is managed by K3s; any changes made to it will be reverted on startup. If you want to inject some additional values into the configmap, you can do so by creating a configmap named coredns-custom. See this issue for more information:
* https://github.com/k3s-io/k3s/pull/4397#issue-1044719103

**Comment by MagicStarTrace** [comment]
> The coredns configmap is managed by K3s; any changes made to it will be reverted on startup. If you want to inject some additional values into the configmap, you can do so by creating a configmap named coredns-custom. See this issue for more information:
> 
> * [[Feature] Customizing CoreDNS ConfigMap with overrides and additional servers #4397 (comment)](https://github.com/k3s-io/k3s/pull/4397#issue-1044719103)

What causes restarting k3s to overwrite coredns configmap?
Thank You!

**Comment by brandond** [comment]
It is part of the coredns manifest. All  of the manifests for packaged components are re-deployed on startup.

**Comment by MagicStarTrace** [comment]
> It is part of the coredns manifest. All of the manifests for packaged components are re-deployed on startup.

I tried to modify /var/lib/rancher/k3s/server/manifests/coredns.yaml
and then restarting still doesn't seem to work

New coredns-config.yaml in /var/lib/rancher/k3s/server/manifests, how to make it work?
Thank You

**Comment by brandond** [comment]
If you want to modify it, you should copy it to a new file and then start k3s with --disable=coredns

**Comment by MagicStarTrace** [comment]
> If you want to modify it, you should copy it to a new file and then start k3s with --disable=coredns

--disable=coredns

Isn't disabling not deploying coredns?

**Comment by brandond** [comment]
Correct, but it will instead deploy coredns from the manifest that you copied and customized...
