### ISSUE TITLE
deleted node from k8s,after restart node, rejoin the k8s

### ISSUE THREAD

**Issue by jiangzhengqun** [k3s-io/k3s#5404]
**Environmental Info:**
K3s Version: 
v1.20.11+k3s2

Node(s) CPU architecture, OS, and Version: 
CPU: 40 cores
OS: Centos 7.8

Cluster Configuration:
3 Servers (1+2)
one of them is set node-role.kubernetes.io/controlplane=true:NoSchedule and node-role.kubernetes.io/etcd=true:NoExecute

**Describe the bug:**
deleted node from k8s,after restart, rejoin the k8s

**Steps To Reproduce:**
1.Ues Rancher UI delete node or execute "kubectl delete node $node_name"
2.execute "kubectl get node", I find the node number is 2
3.restart the deleted node
4.execute "kubectl get node", the deleted node is rejoin

**Expected behavior:**
I want to deleted the node which is set node-role.kubernetes.io/controlplane=true:NoSchedule and node-role.kubernetes.io/etcd=true:NoExecute from my k8s

**Comment by brandond** [comment]
Yes, nodes will automatically join the cluster on startup - the first time, or after being deleted. If you don't want it to come back into the cluster, stop and disable the service before deleting the node resource.

**Comment by jiangzhengqun** [comment]
> Yes, nodes will automatically join the cluster on startup - the first time, or after being deleted. If you don't want it to come back into the cluster, stop and disable the service before deleting the node resource.

thank you, I uninstall k3s by using "/usr/local/bin/k3s-uninstall.sh", and then deleted the node
