### ISSUE TITLE
Where can I see etcd data for k3s. I can't see etcd-related processes, and I don't know where the data is stored.

### ISSUE THREAD

**Issue by MagicStarTrace** [k3s-io/k3s#5435]
OS：ubuntu 18.04
k3s version: v1.21.4+k3s1 (3e250fdb)

I use the following command to initialize k3s:
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | K3S_DATASTORE_ENDPOINT="etcd" INSTALL_K3S_VERSION=v1.21.4+k3s1   INSTALL_K3S_MIRROR=cn sh -s - --service-node-port-range=1-65535  --no-flannel --write-kubeconfig ~/.kube/config 

But check the configuration and find that there is no etcd related configuration:
```console
cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--flannel-backend=none' \
  	'--service-node-port-range=1-65535' \
```

Where can I see etcd persistent data of k3s and etcd related startup item configuration?
Thank You!

**Comment by brandond** [comment]
I believe the files you're looking for are at `/var/lib/rancher/k3s/server/db/etcd/`

**Comment by MagicStarTrace** [comment]
> I believe the files you're looking for are at `/var/lib/rancher/k3s/server/db/etcd/`. Since etcd run embedded within k3s, like all the other components, there isn't a separate systemd unit. If you want to change the configuration of the embedded etcd you should use the `--etcd-arg` flag to do so.

K3S_DATASTORE_ENDPOINT="etcd" is this parameter useless?

**Comment by brandond** [comment]
That parameter is only useful if you're going to use an external SQL datastore or etcd cluster. If you're using the single-node sqlite database, or managed etcd via --cluster-init, it should not be set.

**Comment by brandond** [comment]
I will also note that, given the systemd unit you showed above, you are not using etcd at all. You are using the single-server kine sqlite backend.

**Comment by MagicStarTrace** [comment]
> I will also note that, given the systemd unit you showed above, you are not using etcd at all. You are using the single-server sqlite backend.
> 
> https://rancher.com/docs/k3s/latest/en/installation/datastore/
Now I want to open etcd as k3s storage, no parameters have been added before(K3S_DATASTORE_ENDPOINT="etcd")
Will doing k3s initialization again rebuild k3s?

Thanks

**Comment by brandond** [comment]
If you want etcd, get rid of the datastore environment variable and add the --cluster-init flag.

**Comment by MagicStarTrace** [comment]
> If you want etcd, get rid of the datastore environment variable and add --cluster-init to the CLI arguments.

Wouldn't that affect the current cluster?

**Comment by brandond** [comment]
https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/#existing-clusters

**Comment by MagicStarTrace** [comment]
> k3s version: v1.21.4+k3s1 ([3e250fd](https://github.com/k3s-io/k3s/commit/3e250fdbab72d88f7e6aae57446023a0567ffc97))


k3s version: v1.21.4+k3s1 

Seeing that 1.22 is supported, is there any way for v1.21.4+k3s1?

**Comment by brandond** [comment]
No, you would need to upgrade.

**Comment by ostapkostyk** [comment]
> /var/lib/rancher/k3s/server/db/etcd/

Could you suggest how to change flags for etcd embedded into k3s? I added desired options to the ```/var/lib/rancher/k3s/server/db/etcd/config```. How to apply it safely? I have a cluster with three nodes. Also, I have configured etcdctl, if it helps.

**Comment by brandond** [comment]
> I added desired options to the /var/lib/rancher/k3s/server/db/etcd/config

don't do that

> Could you suggest how to change flags for etcd embedded into k3s?

use the `--etcd-arg` CLI flag or config file key.

This is a quite old issue, if you have further questions please open a discussion thread.
