### ISSUE TITLE
Failed to pull image from quay.io

### ISSUE THREAD

**Issue by akoserwal** [k3s-io/k3s#5445]
Running on a raspberrypi single master node cluster

Failed to pull image "[quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787](http://quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787)": rpc error: code = NotFound desc = failed to pull and unpack image "[quay.io/cilium/operator-generic@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787](http://quay.io/cilium/operator-generic@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787)": no match for platform in manifest: not found

**Environmental Info:**
K3s Version: 

k3s version v1.22.7+k3s1

Node(s) CPU architecture, OS, and Version: 

NAME          STATUS   ROLES                  AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                           KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypi   Ready    control-plane,master   94m   v1.22.7+k3s1      <none>        Raspbian GNU/Linux 11 (bullseye)   5.15.32-v7l+     containerd://1.5.9-k3s1

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
It appears that Cilium doesn't have images for arm/arm64. Is there something that needs to be fixed on the K3s side?

**Comment by akoserwal** [comment]
ah, yes you are right. I had doubts about whether its an issues with pulling images from the quay.
