### ISSUE TITLE
Some Installer Issues with Directories and Data

### ISSUE THREAD

**Issue by cawoodm** [k3s-io/k3s#5456]
**Environmental Info:**
K3s Version: 
k3s version v1.23.5+k3s1 (313aaca5)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
x64 CentOS 7

Cluster Configuration:
single node

**Describe the bug:**
We are seeing some issues where directories are incorrectly created or not created:
1. The following directory is not created:
  * `/var/lib/rancher/k3s/server/`
2. The following directory is created but it shouldn't be since we specified a different `data-dir: /data/k3s`:
  * `/var/lib/rancher/k3s/data`

**Steps To Reproduce:**
```
export INSTALL_K3S_VERSION=v1.23.5+k3s1
curl -sfL https://get.k3s.io | sh -s - server --config /etc/my/k3s/config.yaml
```

## /etc/my/k3s/config.yaml
```yaml
data-dir: /data/k3s
datastore-endpoint: "postgres://k8s_dev:***@dbserver:30008/k8s_dev?sslmode=disable"
write-kubeconfig-mode: 644
```

**Expected behavior:**
1. Expected `/var/lib/rancher/k3s/server/manifests/`
2. Expected all data in `/data/k3s`

**Actual behavior:**
1. `/var/lib/rancher/k3s/server/` is missing
2. We are seeing data in `/var/lib/rancher/k3s/data`

```bash
ls /var/lib/rancher/k3s/data/
total 0
drwxr-xr-x 3 root root 106 Apr 18 10:42 ./
drwxr-xr-x 3 root root  18 Apr 18 10:42 ../
drwxr-xr-x 4 root root  28 Apr 18 10:42 05cfd5aec8ddf622207749ef3eda0e0efa12d8900105fdac78815a8cd6c73685/15a8cd6c73685/                                                                             22207749ef3eda0e0efa12d
lrwxrwxrwx 1 root root  90 Apr 18 10:42 current -> /var/lib/rancher/k3s/data/05cfd5aec8ddf622207749ef3eda0e0efa12d8900105fdac78815a8cd6c73685/
-rw------- 1 root root   0 Apr 18 10:42 .lock
```

**Comment by brandond** [comment]
data-dir does not relocate /var/lib/rancher/k3s/data, it relocates /var/lib/rancher/k3s.

Note that if you fail to pass the `--config=/path/to/config` flag to any of the k3s wrapped commands (k3s kubectl, k3s crictl, etc) it will not find the config file, will not use your custom data-dir, and will re-extract the binaries to the default location. I would suggest either making sure that you reliably export K3S_CONFIG_FILE=/path/to.config in your environment, or just use the default config file path.

**Comment by cawoodm** [comment]
> data-dir does not relocate /var/lib/rancher/k3s/data, it relocates /var/lib/rancher/k3s. Everything (agent, server, data) will be moved when you set the data-dir.

So you're saying `/var/lib/rancher/k3s/data` was probably not created by the installer (to which I passed my config) but perhaps by `kubectl` to which I did not pass a config?

**Comment by cawoodm** [comment]
Whoah! That's an accident waiting to happen. Usually when you pass configuration to an installer for a "tool" the installer will persist that for the tool. Just sayin'

**Comment by brandond** [comment]
Yes, except k3s allows you to change the location where configuration is stored (via the --config flag). If you take advantage of that option, it is your responsibility to ensure that your customization is applied globally. We can't very well store the configuration file path in the configuration file itself, can we?

**Comment by cawoodm** [comment]
True, but it could be persisted as an ENV variable. Lot's of installers do this.

I just think anyone who, like me, changes this location, will run into trouble fairly quickly. Consider that many 3rd party tools (e.g. K9S or Rancher, Portainer) use kubectl directly. They definitely won't be passing a config param to kubectl.

**Comment by brandond** [comment]
Persisted where? By writing to your bashrc or something?

**Comment by cawoodm** [comment]
Yes, that is one possibility. Perhaps I am misunderstanding the idea of `--config` is the idea that you can run multiple different configs of k3s on the same machine? Sounds more like a k3s developer option.

In the wild users are only running one k3s config. If they specify `--config` at installation I would expect this to persist - e.g. by symlinking `/etc/rancher/k3s/config.yaml` to that config.

For myself I will just stop using `--config` because I see no simple way to ensure all tools will respect it and it sounds dodgy to have the data directory become "uncertain" when executing kubectl.

**Comment by cawoodm** [comment]
OK, back to the original issue. We are now able to find our manifests in:
```
/data/k3s/server/manifests
```
Thanks!

**Comment by cawoodm** [comment]
Final questions:
* Does K3S move existing data if we change `data-dir` on an existing server?
* Are PVs stored in `data-dir`

**Comment by cawoodm** [comment]
As a workaround symlinks:
```bash
ln -s /data/k3s /var/lib/rancher/k3s
```

(Source](https://github.com/k3s-io/k3s/issues/1258#issuecomment-574276043)

**Comment by brandond** [comment]
> Yes, that is one possibility. Perhaps I am misunderstanding the idea of `--config` is the idea that you can run multiple different configs of k3s on the same machine? Sounds more like a k3s developer option.

Up until fairly recently K3s was only configurable via CLI flags and environment variables. Any desired configuration needed to be explicitly set every time K3s was run. When we added config file support, it made sense to make the configuration file path configurable instead of hard-coded. How you use that flexibility is up to you.

**Comment by cawoodm** [comment]
That makes sense as far as k3s is concerned. In my case it seemed that kubectl did not know about the config file and created data files outside of data-dir. This is inexplicable. Not sure if it’s a problem though.
