### ISSUE TITLE
k3s nodes can't join 

### ISSUE THREAD

**Issue by bemanuel** [k3s-io/k3s#5459]
**Environmental Info:**
K3s Version: v1.23.5+k3s1 (313aaca5)
go version go1.17.5

HAProxy as Load Balancer

Node(s) CPU architecture, OS, and Version: 16 vcpus amd64 / Alpine 3.15 
Linux k3s-3-5-wrk 5.15.32-0-virt #1-Alpine SMP Mon, 28 Mar 2022 13:09:00 +0000 x86_64 Linux

Cluster Configuration:

2 servers, 4 agents

**Describe the bug:**
Joining command executed, the system doesn't accept it.

time="2022-04-18T20:49:32Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
time="2022-04-18T20:49:42Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-18T20:49:52Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-18T20:50:03Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-18T20:50:13Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-18T20:50:23Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-18T20:51:11Z" level=info msg="Starting k3s agent v1.23.5+k3s1 (313aaca5)"

**Steps To Reproduce:**

- Installed K3s: 
Server: curl -sfL https://get.k3s.io | K3S_TOKEN=<my_token> K3S_KUBECONFIG_MODE=644 INSTALL_K3S_VERSION=v1.23.5+k3s1 sh -s - server --cluster-init --tls-san=lb_ip:6443
Agent: curl -sfL https://get.k3s.io | K3S_TOKEN=<my_token> K3S_URL=https:
//lb_ip:6443 INSTALL_K3S_VERSION=v1.23.5+k3s1 sh -
HA Proxy: 2.5.5-1ppa1
  frontend kube-apiserver
    bind *:6443
    mode TCP
    option tcplog
    default_backend kube-apiserver

  backend kube-apiserver
     mode TCP
     balance round-robin
     option  tcplog
     log       global
     default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
     server k3s-master-01 ip-node01:6443 check
     server k3s-master-02 ip-node02:6443 check

**Expected behavior:**

  The system accept the new node.

**Actual behavior:**

  The agent can't join to cluster.
**Additional context / logs:**

70:6443 K3S_KUBECONFIG_MODE=644 INSTALL_K3S_VERSION=v1.23.5+k3s1 sh -
[INFO]  Using v1.23.5+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.23.5+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.23.5+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/rancher/k3s/k3s-agent.env
[INFO]  openrc: Creating service file /etc/init.d/k3s-agent
[INFO]  openrc: Enabling k3s-agent service for default runlevel
[INFO]  openrc: Starting k3s-agent
 * Caching service dependencies ...                                                               [ ok ]
 * Mounting cgroup filesystem ...                                                                 [ ok ]
 * Starting k3s-agent ...      
**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> HAProxy as Load Balancer

Are you offloading SSL to the load balancer? K3s (and Kubernetes) use client certificate authentication, which will be broken if your load-balancer is terminating SSL.

Also, the agent needs to be able to directly access the servers on port 6443; make sure that you are not blocking this access. The load-balancer is only used for the initial connection to the servers; it switches over to direct connections to all servers early in the bootstrap process.

**Comment by bemanuel** [comment]
I see. But no there is no SSL Termination, is a TCP direct connection.
However, I did the same test directly to the server and didn't work too.
About the connection. Yes, there is no firewall or access blocking between nodes and servers, they work on the same subnet.

**Comment by bemanuel** [comment]
And weirder, some nodes joined.
So I decide to clone them creating a new node, then I repeat the process and this new node can't join.

**Comment by brandond** [comment]
Are both of the servers up and running? Can you successfully curl `https://lb-ip:6443/ping` from all the nodes?

**Comment by bemanuel** [comment]
> curl -ks https://lb-ip:6443/ping

Yes. I can. And I switched the IP from lb to the server, giving the same error.

```
time="2022-04-19T08:56:18Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
time="2022-04-19T08:56:28Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2022-04-19T08:56:38Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: context deadline exceeded (Client.Timeout or context cancellation while reading body)"
time="2022-04-19T08:56:48Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

This is the check-config result
```
k3s check-config

Verifying binaries in /var/lib/rancher/k3s/data/05cfd5aec8ddf622207749ef3eda0e0efa12d8900105fdac78815a8cd6c73685/bin:
- sha256sum: good
- links: good

System:
- /sbin iptables v1.8.7 (legacy): ok
- swap: disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: cgroups Hybrid mounted, cpuset|memory controllers status: good
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled (as module)
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: pass
```

**Comment by brandond** [comment]
The error you're getting indicates that the client is able to connect to the server and make the request, but it's not getting any response.
> Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Just to confirm that it's not the load-balancer creating problems, can you try specifying on of the servers as the --server address, instead of the load-balancer?

**Comment by bemanuel** [comment]
Yes, I tried but didn't work.
Happened the same.

**Comment by brandond** [comment]
Can you try starting both the server and agent with `--debug` ?

I really suspect there is something else going on in your environment that's disrupting the communication between the nodes. Firewall, proxy server, or perhaps even mismatched MTU.

**Comment by bemanuel** [comment]
@brandond, thank you!
You talk about mismatched MTU, so I realize that we use Jumbo Frame ( MTU 9000 ) on our interfaces.
The problem was on switches and some Hypervisor Hosts, even the VM had the MTU 9000 the system can't send huge packages.
The commands used to test from nodes: ``` ping -M do -s 8972 <ip>``` / Alpine: ``` ping -s 8972 <ip>```
As we use a cluster with 10 nodes, I didn't realize that some of them were misconfigured.
As soon we fix the Jumbo Frame the nodes started to work. And using HAProxy as LB.

> Can you try starting both the server and agent with `--debug`?
> 
> I really suspect there is something else going on in your environment that's disrupting the communication between the nodes. Firewall, proxy server, or perhaps even incorrect/mismatched **MTU.**

**Comment by brandond** [comment]
Glad to hear it! Feel free to close out the issue if it's resolved.
