### ISSUE TITLE
option 'kubelet-args' doesn't work when restart node

### ISSUE THREAD

**Issue by MagicalBomb** [k3s-io/k3s#5488]
**Environmental Info:**
K3s Version: 

k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux data-api-test 4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server 0 agent

**Describe the bug:**

`kubelet-args` doesn't work when restart server node by script , only work when uninstall server node then reinstall it

**Steps To Reproduce:**

1. install server node  `curl -sfL https://get.k3s.io/ | sh -`
2. use `kubectl describe node`  can see `Capacity` is equal to `Allocatable`
3. make a `/home/wzp/config.yaml` like blow
```yaml
kubelet-arg=kube-reserved: "cpu=500m,memory=1Gi,ephemeral-storage=2Gi"
kubelet-arg=system-reserved: "cpu=500m, memory=1Gi,ephemeral-storage=2Gi"
kubelet-arg=eviction-hard: "memory.available<500Mi,nodefs.available<10%"
```
4. restart server node `curl -sfL https://get.k3s.io/ | K3S_CONFIG_FILE=/home/wzp/config.yaml sh -`
5. use `kubectl describe node`  can see `Capacity` is still equal to `Allocatable`

but if you uninstall server node and reinstall with `config.yaml`, these reservation options would work

**Expected behavior:**

restart node by `curl -sfL https://get.k3s.io/ | K3S_CONFIG_FILE=/home/wzp/config.yaml -`, the reservation options can work

**Actual behavior:**

restart node by `curl -sfL https://get.k3s.io/ | K3S_CONFIG_FILE=/home/wzp/config.yaml -`, the reservation options don't work

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
You're not providing a path to the config file, so I'm not surprised it's not loading it. You should provide an absolute path to the config file, or use the default path and create your file at `/etc/rancher/k3s/config.yaml`. You don't need to configure the path if you use the default; it will be loaded automatically.

**Comment by MagicalBomb** [comment]
> You're not providing a path to the config file, so I'm not surprised it's not able to load it. I have no idea what directory you placed that file in and neither does k3s. You should provide an absolute path to a config file, or use the default path of `/etc/rancher/k3s/config.yaml`. You don't need to specify K3S_CONFIG_FILE or --config-file if you use the default; it will be loaded automatically.

sorry, I simplified the path to config.yaml. Actually, I used absolute path in K3S_CONFIG_FILE, not relative path, it doesn't work

**Comment by brandond** [comment]
Hmm. Even so, I can't reproduce what you're describing; the K3S_CONFIG_FILE variable is persisted no matter how many times I re-run the installer. Also note that it is probably more effective to just use systemctl to restart k3s, as opposed to re-running the installer.

Additionaly, your YAML is malformed; you want something like this:

```yaml
kubelet-arg:
  - "kube-reserved=cpu=500m,memory=1Gi,ephemeral-storage=2Gi"
  - "system-reserved=cpu=500m, memory=1Gi,ephemeral-storage=2Gi"
  - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
```

**Comment by MagicalBomb** [comment]
> Hmm. Even so, I can't reproduce what you're describing; the K3S_CONFIG_FILE variable is persisted no matter how many times I re-run the installer. Note that it is probably more effective to just use systemctl to restart k3s, as opposed to re-running the installer.
> 
> Additionally, your YAML is malformed; you want something like this:
> 
> ```yaml
> kubelet-arg:
>   - "kube-reserved=cpu=500m,memory=1Gi,ephemeral-storage=2Gi"
>   - "system-reserved=cpu=500m, memory=1Gi,ephemeral-storage=2Gi"
>   - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
> ```

I tried several times again. It's weird that kubelet-args works...

**Comment by brandond** [comment]
It's just the arg exactly as you would pass it to the kubelet; the leading -- is optional so I tend to leave it off. In yaml, repeated args must be given as a list since you can't repeat the same key multiple times.

**Comment by MagicalBomb** [comment]
> It's just the arg exactly as you would pass it to the kubelet; the leading -- is optional so I tend to leave it off. In yaml, repeated args must be given as a list since you can't repeat the same key multiple times. The k3s yaml config file keys are just the exact same as CLI flags from the documentation.

Got it, thank you brandond ~

**Comment by EvanCarroll** [comment]
> Hmm. Even so, I can't reproduce what you're describing; the K3S_CONFIG_FILE variable is persisted no matter how many times I re-run the installer. Note that it is probably more effective to just use systemctl to restart k3s, as opposed to re-running the installer.
> 
> Additionally, your YAML is malformed; you want something like this:
> 
> ```yaml
> kubelet-arg:
>   - "kube-reserved=cpu=500m,memory=1Gi,ephemeral-storage=2Gi"
>   - "system-reserved=cpu=500m, memory=1Gi,ephemeral-storage=2Gi"
>   - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
> ```

This doesn't work for me, if I copy this exact thing and past it into `/etc/rancher/k3s/k3s.yaml` it gets removed when I start the server. I also don't see anything in the logs.

**Comment by brandond** [comment]
`/etc/rancher/k3s/k3s.yaml` is the kubeconfig file, not the K3s confif. Did you want to put it in `/etc/rancher/k3s/config.yaml` ?

**Comment by EvanCarroll** [comment]
Thanks that worked! Just confirmed it. Two more question while I have your ear. [In this post you said](https://github.com/k3s-io/k3s/issues/5213#issuecomment-1061650465),

> The CLI args have been deprecated for ages and show no actual signs of going away; I would continue to use them.

Does that mean this method of putting these in the `config.yaml` is also deprecated, and if so is there a method of specifying the `kublet-args` in the environmental variables file (`/etc/systemd/system/k3s.service.env`), or anywhere else?

**Comment by brandond** [comment]
Configuring Kubernetes components via CLI flags has been deprecated upstream for years. We still use it extensively. If upstream ever does get around to moving forward on actually removing support for it, we will provide some way to migrate our pass-through arguments (--kubelet-arg, etc) over to config files.

**Comment by 2fst4u** [comment]
Sorry to beat a dead horse but I can't get this to work. Previously I passed the kublet args to the intaller but I want to change these values now.

In my `/etc/systemd/system/k3s.service` I can see these values as I passed them initially as such:

```
[truncated]
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable' \
        'traefik' \
        '--disable' \
        'servicelb' \
        '--server' \
        '[redacted]' \
        '--token' \
        '[redacted]' \
        '--resolv-conf' \
        '/run/systemd/resolve/resolv.conf' \
        '--kubelet-arg' \
        'system-reserved=cpu=300m,memory=500Mi' \
        '--kubelet-arg' \
        'kube-reserved=cpu=300m,memory=600Mi' \
```

My `/etc/rancher/k3s/config.yaml` didn't exist so I created it and added the args in the same format as you showed @brandond. I restarted k3s but it doesn't seem to have loaded these. My `/etc/systemd/system/k3s.service` is still exactly the same.

Is it because I passed these values on install that it's taking those original values and ignoring my config.yml?

I'm really struggling to understand how to reserve these values. I'm starting to second guess my original reservations and whether they've even been implemented correctly.

**Comment by brandond** [comment]
If you want to configure those args via config.yaml then you should probably remove them from the CLI flags in the systemd unit. Only the install script manages the content of the unit file; adding things to the config file will not cause k3s to update the args passed to the systemd unit.

**Comment by 2fst4u** [comment]
Can `/etc/systemd/system/k3s.service` be safely edited to remove these flags?

**Comment by brandond** [comment]
That's not really a K3s question but yes, you can edit systemd units. You should do `systemctl daemon-reload` to tell systemd to update its configuration.
https://www.freedesktop.org/software/systemd/man/systemctl.html#daemon-reload

**Comment by 2fst4u** [comment]
> That's not really a K3s question but yes, you can edit systemd units. You should do `systemctl daemon-reload` to tell systemd to update its configuration. https://www.freedesktop.org/software/systemd/man/systemctl.html#daemon-reload

This worked thank you. Note the node needed to be rebooted, restarting k3s didn't apply the change. After a reboot the setting applied.

**Comment by brandond** [comment]
Well you would need to do a daemon-reload and then restart k3s. You shouldn't need to reboot the whole node.
