### ISSUE TITLE
secrets-encrypt reencrypt gets stuck in `reencrypt_active`

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#5489]
**Environmental Info:**
K3s Version: `k3s version v1.22.8+k3s1 (21fed356)`

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
Single node, all-in-one

**Describe the bug:**
When walking through a secrets-encrypt rotation, the node gets stuck in `reencrypt_active` during the `secrets-encrypt reencrypt` stage.

**Steps To Reproduce:**
Install and start K3s with `--secrets-encryption=true`.
Run `k3s secrets-encrypt prepare`
Restart `k3s`
Run `k3s secrets-encrypt rotate`
Restart `k3s`
Run `k3s secrets-encrypt reencrypt`

Observe that the `Stage` gets stuck in `reencrypt_active`

**Expected behavior:**
`Stage` ends up going to `reencrypt_finished`

**Actual behavior:**
`Stage` gets stuck in `reencrypt_active`

**Additional context / logs:**
It looks like K3s is unable to update the node annotations to set the `reencrypt_finished` stage. 

```

Apr 21 23:02:18 ck-c7-0 k3s[9081]: time="2022-04-21T23:02:18-07:00" level=info msg="Removed key:  Name: aescbckey-2022-04-21T23:01:02-07:00, Secret: [REDACTED]"
Apr 21 23:02:18 ck-c7-0 k3s[9081]: time="2022-04-21T23:02:18-07:00" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"ck-c7-0\", UID:\"0f8ee753-e406-4277-8507-485cff853380\", APIVersion:\"v1\", ResourceVersion:\"2661\", FieldPath:\"\"}): type: 'Normal' reason: 'SecretsUpdateComplete' completed reencrypt of 64 secrets"
Apr 21 23:02:19 ck-c7-0 k3s[9081]: time="2022-04-21T23:02:19-07:00" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"ck-c7-0\", UID:\"0f8ee753-e406-4277-8507-485cff853380\", APIVersion:\"v1\", ResourceVersion:\"2661\", FieldPath:\"\"}): type: 'Warning' reason: 'SecretsUpdateError' Operation cannot be fulfilled on nodes \"ck-c7-0\": the object has been modified; please apply your changes to the latest version and try again"
```

```
[root@ck-c7-0 ~]# k3s -v
k3s version v1.22.8+k3s1 (21fed356)
go version go1.16.10
[root@ck-c7-0 ~]# k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_active
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-04-21T23:01:02-07:00
```

**Backporting**
- [X] Needs backporting to older releases

This is required for and is blocking progress on https://github.com/rancher/rancher/issues/35436

**Comment by brandond** [comment]
I suspect that the node updates at https://github.com/k3s-io/k3s/blob/f2ceeb01d9c392e7d9497b6ba3181510620f5102/pkg/secretsencrypt/controller.go#L93 and https://github.com/k3s-io/k3s/blob/f2ceeb01d9c392e7d9497b6ba3181510620f5102/pkg/secretsencrypt/controller.go#L107 need to be wrapped in https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict

**Comment by rancher-max** [comment]
#### Validated using v1.23.6-rc2+k3s1

- Followed the same steps and saw success
```
$ sudo k3s secrets-encrypt reencrypt
reencryption started

$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_active
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-04-25T21:08:48Z
        AES-CBC   aescbckey

$ k annotate node/ip-172-31-10-213 foo=bar
node/ip-172-31-10-213 annotated

$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_active
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-04-25T21:08:48Z
        AES-CBC   aescbckey

$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-04-25T21:08:48Z

$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-04-25T21:08:48Z
```
