### ISSUE TITLE
Failed to create pod sandbox: open /tmp/k3s-resolv.conf: no such file or directory

### ISSUE THREAD

**Issue by cablespaghetti** [k3s-io/k3s#5503]
**Environmental Info:**
K3s Version: v1.22.4+k3s1 and v1.23.5+k3s1
Node(s) CPU architecture, OS, and Version: x86_64 on Arch Linux and ARM64 on Oracle Linux
Cluster Configuration: Single node master on Arch and 3 master using embedded etcd on Oracle
**Describe the bug:**
After around a week the `/tmp/k3s-resolv.conf` file disappears (I presume /tmp gets cleaned up by the OS...) and pods fail to start until k3s is restarted and the file is regenerated.

The error looks like this on the Pods events:
```
Warning  FailedCreatePodSandBox  11s (x10 over 2m6s)  kubelet            Failed to create pod sandbox: open /tmp/k3s-resolv.conf: no such file or directory
```

**Steps To Reproduce:**
- Installed K3s:
I don't have the steps as the Arch box has been around for a while and I've just been restarting it weekly to resolve the issue. The oracle cluster was installed with the following command.

```
export INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --disable-cloud-controller --cluster-init"
curl -sfL https://get.k3s.io | sh -
```

**Expected behavior:**
I'm not sure but why is this clearly critical file stored in tmp which is by definition ephemeral storage?

**Actual behavior:**
I have to keep restarting k3s :(

**Additional context / logs:**
Happy to provide some but I've not found any related logs to give a lead unfortunately.

**Backporting**
- [x] Needs backporting to older releases
It does seem to exist in 1.22 and 1.23 from my experience.

**Comment by cablespaghetti** [comment]
For additional context, I found this discussion: https://github.com/k3s-io/k3s/discussions/3867

On Oracle Linux (on Oracle Cloud) I think k3s is creating the file because the default resolv.conf has `nameserver 169.254.169.254`.

On Arch it's using systemd-resolved and the resolv.conf has `nameserver 127.0.0.53`.

I can see how I may have been saved from problems in both of these cases. However I still think the the file being in `/tmp` and getting "tidied up", potentially by the `systemd-tmpfiles-clean` unit/timer on both Arch and Oracle Linux is probably a bug.

**Comment by brandond** [comment]
Having something cleaning up actively in use temp files seems like a problem. That's said, we could probably evaluate moving that file elsewhere.

**Comment by cablespaghetti** [comment]
Hi @brandond I agree, it was news to me when I discovered this was running on my systems. However it is there by default in Arch and Oracle Linux 8, so I assume it is there on many other systemd-based distros as well. I'm not sure how the file permissions work out, but maybe it should live in `/var/lib/rancher/k3s/agent/etc/` with much of the other configuration.

**Comment by rancher-max** [comment]
#### Validated on release-1.23 branch using commitid `2f22703c9e2f3cee40709265de8676811d0aadff`

- File is not present in `/tmp/` and is present now in `$datadir/agent/etc/`
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/resolv.conf
nameserver 8.8.8.8
```
- There are no erroneous pod events
- Also confirmed this same behavior is seen using v1.24.0-rc1+k3s1
- This only happens when `/etc/resolv.conf` and `/run/systemd/resolve/resolv.conf` are not found to be valid resolv.conf files
