### ISSUE TITLE
Add installation options to choose directories different than /etc/rancher, /usr/libexec and /var/lib/rancher

### ISSUE THREAD

**Issue by mossroy** [k3s-io/k3s#5504]
**Is your feature request related to a problem? Please describe.**
k3s can't run out-of-the-box on specific linux distributions that have a mostly readonly filesystem, like LibreElec, see #4859

**Describe the solution you'd like**
Some installation options could be added (like the existing INSTALL_K3S_BIN_DIR and INSTALL_K3S_SYSTEMD_DIR) to tell k3s installer where to put some files it creates (instead of /etc/rancher, /usr/libexec and /var/lib/rancher, which should still be the default values)

**Describe alternatives you've considered**
I've implemented some dirty workarounds to copy the contents of /etc and /usr in a writable place, and mount them instead (see #4859). But it's clearly not optimal.

**Comment by poblin-orange** [comment]
Had the same issue while integrating k3s with bosh filesystems (spécific config, temps and persistend disk mount locations). eg https://github.com/orange-cloudfoundry/k3s-boshrelease/blob/master/jobs/k3s-server/templates/bin/ctl.erb#L40

**Comment by mossroy** [comment]
To me, this issue is still relevant
