### ISSUE TITLE
Ability to add dual-stacking to existing clusters

### ISSUE THREAD

**Issue by Blorpy** [k3s-io/k3s#5514]
**Is your feature request related to a problem? Please describe.**

I have some existing k3s clusters that I would like to enable dual-stack on (currently single stack IPv4), but as per the docs and the comment at https://github.com/k3s-io/k3s/issues/284#issuecomment-962003445 this is not possible (indeed k3s panics on startup). 

**Describe the solution you'd like**

It would be great if it possible to add on dual-stacking to an existing cluster, without needing to start from scratch. 

**Describe alternatives you've considered**

I have considered tearing down the clusters and starting over with dual stack from day 1, but this is a fair amount of work. 

**Additional context**

It's not clear to me if this is a k3s issue, flannel issue, or a combination thereof. I'm not intimately familiar with the internal workings of the IPAM here, so if this feature request if next to impossible then please feel free to close. 

Note that I do not expect IPv6 addresses to appear on currently running pods, simply that an existing cluster can be dual stacked so new pods can pickup an IPv6 address. 

**Backporting**

- [ ] Needs backporting to older releases

**Comment by manuelbuil** [comment]
This is tricky to do. It should be a kubernetes feature but I don't think that it currently exists. Flannel picks the ip range from the kubernetes nodes but, as far as I know, there is no way to update the ip range of each node on the fly

**Comment by brandond** [comment]
Correct, Kubernetes does not support changing the CIDRs on nodes after the fact, so at the moment it will require deleting and rejoining all the nodes at the very least. I believe they may be working on enhancing this in the future.

**Comment by Blorpy** [comment]
Thanks for the clarification, since this is an upstream limitation for now I will close this issue.

**Comment by eutampieri** [comment]
Is there already an issue on k8s? Do we have to open one upstream?

**Comment by j-heffron** [comment]
If I am not wrong, it looks like [the upstream limitation](https://github.com/kubernetes/kubernetes/pull/131263) is now resolved with 1.33. If nothing else is blocking dual-stack conversion on existing clusters, this issue should probably be re-opened.

**Comment by manuelbuil** [comment]
> If I am not wrong, it looks like [the upstream limitation](https://github.com/kubernetes/kubernetes/pull/131263) is now resolved with 1.33. If nothing else is blocking dual-stack conversion on existing clusters, this issue should probably be re-opened.

The link you provided specifies a conversion in the Service CIDR. This issue is talking about doing that on the pod CIDR, which is still unsupported. They are targeting different CIDRs.
