### ISSUE TITLE
Multiple cluster solution support

### ISSUE THREAD

**Issue by Shreekant1997** [k3s-io/k3s#5522]
Hi Team, 

I am looking for ways where I can manage mulltiple kubernetes cluster. By manage I mean a single command that could deploy the application on both the cluster at the same time. I have found few ways but I am facing some unavoidable challenges implementing them. Is there any tool that is compatible with k3s or any other alternative I could look for to manage these multiple on premise cluster. 

Here is what I have found so far: 

1. Kubesphere : I was able to establish kubesphere, but turns out as of now kubesphere is not supported on arm64 platform. Hence not able to utilize its functionality. 

2. Kubefed: The installations are not happening propery. 

What I am looking for is a multicluster tool to visualize as well as manage multiple k3s cluster. Any suggestions ?

**Comment by brandond** [comment]
Rancher?

**Comment by Shreekant1997** [comment]
Sorry, Didn't understand!

Does Rancher has a tool or plugin that supports multi-cluster management along with dashboards ?

**Comment by brandond** [comment]
Rancher IS a multi-cluster management tool.

**Comment by cwayne18** [comment]
Closing this out as it's not really a k3s issue
