### ISSUE TITLE
k3s install fails (Ubuntu 21.10 desktop)

### ISSUE THREAD

**Issue by gmacario** [k3s-io/k3s#5528]
**Environmental Info:**
K3s Version:  TBV (INSTALL_K3S_CHANNEL=stable)

Node(s) CPU architecture, OS, and Version: x86_64, Ubuntu 21.10 desktop

```text
gmacario@hw0929:~$ uname -a
Linux hw0929 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gmacario@hw0929:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
gmacario@hw0929:~$
```

Cluster Configuration: N.A. (fails during install)

**Describe the bug:**

I have been trying to install k3s on a new Ubuntu host through https://get.k3s.io
but the install script terminates without effect and no apparent errors.

Also, I cannot understand why channel "stable" still links to https://github.com/k3s-io/k3s/releases/tag/v1.22.7+k3s1 even though newer releases have already been published.

**Steps To Reproduce:**

Install k3s using the official script

```bash
curl -sfL https://get.k3s.io | sh -
```

Result:

```text
gmacario@hw0929:~$ curl -sfL https://get.k3s.io | sh -
[sudo] password for gmacario: 
[INFO]  Finding release for channel stable
[INFO]  Using v1.22.7+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
gmacario@hw0929:~$
```

- Installed K3s: 

**Expected behavior:**

The install script should complete successfully

**Actual behavior:**

Nothing happens, the install script terminates with no errors

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by gmacario** [comment]
Launching shell with `-x` option to have more verbosity

```text
gmacario@hw0929:~$ curl -sfL https://get.k3s.io | sh -x -
+ set -e
+ set -o noglob
+ GITHUB_URL=https://github.com/k3s-io/k3s/releases
+ STORAGE_URL=https://storage.googleapis.com/k3s-ci-builds
+ DOWNLOADER=
+ escape 
+ printf %s 
+ sed -e s/\([][!#$%&()*;<=>?\_`{|}]\)/\\\1/g;
+ quote
+ eval set --
+ set --
+ verify_system
+ [ -x /sbin/openrc-run ]
+ [ -x /bin/systemctl ]
+ HAS_SYSTEMD=true
+ return
+ setup_env
+ [ -z https://arneis-vm01.gmacario.it:6443 ]
+ [ -z K1015e93c37ae40fe3254da641646ba83be3e35da3c0e5ae97d8044cb09f4f06408::server:f22587a6fb80f1d9f1556ddd1c8672c3 ]
+ CMD_K3S=agent
+ verify_k3s_url
+ quote_indent
+ printf  \\\n
+ CMD_K3S_EXEC=agent \
+ [ -n  ]
+ [ agent = server ]
+ SYSTEM_NAME=k3s-agent
+ printf %s+  k3s-agent
sed -e s/[][!#$%&()*;<=>?\_`{|}/[:space:]]/^/g;
+ valid_chars=k3s-agent
+ [ k3s-agent != k3s-agent ]
+ SUDO=sudo
+ id -u
+ [ 1000 -eq 0 ]
+ [ -n  ]
+ [ agent = server ]
+ SYSTEMD_TYPE=exec
+ [ -n  ]
+ BIN_DIR=/usr/local/bin
+ sudo sh -c touch /usr/local/bin/k3s-ro-test && rm -rf /usr/local/bin/k3s-ro-test
+ [ -n  ]
+ SYSTEMD_DIR=/etc/systemd/system
+ SERVICE_K3S=k3s-agent.service
+ UNINSTALL_K3S_SH=/usr/local/bin/k3s-agent-uninstall.sh
+ KILLALL_K3S_SH=/usr/local/bin/k3s-killall.sh
+ [ true = true ]
+ FILE_K3S_SERVICE=/etc/systemd/system/k3s-agent.service
+ FILE_K3S_ENV=/etc/systemd/system/k3s-agent.service.env
+ get_installed_hashes
+ sudo sha256sum /usr/local/bin/k3s /etc/systemd/system/k3s-agent.service /etc/systemd/system/k3s-agent.service.env
+ true
+ PRE_INSTALL_HASHES=sha256sum: /usr/local/bin/k3s: No such file or directory
sha256sum: /etc/systemd/system/k3s-agent.service: No such file or directory
sha256sum: /etc/systemd/system/k3s-agent.service.env: No such file or directory
+ [  = true ]
+ INSTALL_K3S_CHANNEL_URL=https://update.k3s.io/v1-release/channels
+ INSTALL_K3S_CHANNEL=stable
+ download_and_verify
+ can_skip_download
+ [  != true ]
+ return 1
+ setup_verify_arch
+ [ -z  ]
+ uname -m
+ ARCH=x86_64
+ ARCH=amd64
+ SUFFIX=
+ verify_downloader curl
+ command -v curl
+ [ -x /snap/bin/curl ]
+ DOWNLOADER=curl
+ return 0
+ setup_tmp
+ mktemp -d -t k3s-install.XXXXXXXXXX
+ TMP_DIR=/tmp/k3s-install.MESYqb4Gr7
+ TMP_HASH=/tmp/k3s-install.MESYqb4Gr7/k3s.hash
+ TMP_BIN=/tmp/k3s-install.MESYqb4Gr7/k3s.bin
+ trap cleanup INT EXIT
+ get_release_version
+ [ -n  ]
+ [ -n  ]
+ info Finding release for channel stable
+ echo [INFO]  Finding release for channel stable
[INFO]  Finding release for channel stable
+ version_url=https://update.k3s.io/v1-release/channels/stable
+ curl -w %{url_effective} -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null
+ sed -e s|.*/||
+ VERSION_K3S=v1.22.7+k3s1
+ info Using v1.22.7+k3s1 as release
+ echo [INFO]  Using v1.22.7+k3s1 as release
[INFO]  Using v1.22.7+k3s1 as release
+ download_hash
+ [ -n  ]
+ HASH_URL=https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
+ info Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
+ echo [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
+ download /tmp/k3s-install.MESYqb4Gr7/k3s.hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
+ [ 2 -eq 2 ]
+ curl -o /tmp/k3s-install.MESYqb4Gr7/k3s.hash -sfL https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
+ cleanup
+ code=23
+ set +e
+ trap - EXIT
+ rm -rf /tmp/k3s-install.MESYqb4Gr7
+ exit 23
gmacario@hw0929:~$
```

**Comment by brandond** [comment]
The curl command is exiting with error code 23. You might try curling that GitHub URL manually to see why it's failing. I suspect something on your network is blocking the request.

**Comment by gmacario** [comment]
I spent some time trying to figure out why `curl` returned error code 23 (it seems it was unable to write the file under TMP_DIR) but with no success. 

I also updated the host OS to Ubuntu 22.04 LTS but that did not solve the issue.

On the other hand I realized the `wget` did not have any issues, therefore I managed to complete the installation by locally downloading the `install.sh` script, then edited it to use `wget` instead than `curl`

```diff
root@hw0929:~# diff -uw install.sh install-debug.sh 
--- install.sh	2022-05-10 17:20:51.037850862 +0200
+++ install-debug.sh	2022-05-11 07:34:42.086679732 +0200
@@ -563,7 +563,8 @@
     fi
 
     setup_verify_arch
-    verify_downloader curl || verify_downloader wget || fatal 'Can not find curl or wget for downloading files'
+    # verify_downloader curl || verify_downloader wget || fatal 'Can not find curl or wget for downloading files'
+    verify_downloader wget || fatal 'Can not find curl or wget for downloading files'
     setup_tmp
     get_release_version
     download_hash
root@hw0929:~#
```

I understand this is a dirty hack, but at least it solved the problem for me.

Documenting it here in case someone in the future has similar issues.

**Comment by gardellajuanpablo** [comment]
I just solved by defining INSTALL_K3S_VERSION environment variable whit required version. 
```
export INSTALL_K3S_VERSION="v1.24.4+k3s1"
curl -sfL https://get.k3s.io | sh -x -
```

**Comment by mtwebmaster** [comment]
i had this same issue, i tried many many things.

sudo apt install apt-transport-https ca-certificates curl software-properties-common -y

this solved it. hope it does for you someone else as well.

**Comment by surya-abs** [comment]
> Launching shell with `-x` option to have more verbosity
> 
> ```
> gmacario@hw0929:~$ curl -sfL https://get.k3s.io | sh -x -
> + set -e
> + set -o noglob
> + GITHUB_URL=https://github.com/k3s-io/k3s/releases
> + STORAGE_URL=https://storage.googleapis.com/k3s-ci-builds
> + DOWNLOADER=
> + escape 
> + printf %s 
> + sed -e s/\([][!#$%&()*;<=>?\_`{|}]\)/\\\1/g;
> + quote
> + eval set --
> + set --
> + verify_system
> + [ -x /sbin/openrc-run ]
> + [ -x /bin/systemctl ]
> + HAS_SYSTEMD=true
> + return
> + setup_env
> + [ -z  ]
> + CMD_K3S=server
> + verify_k3s_url
> + quote_indent
> + printf  \\\n
> + CMD_K3S_EXEC=server \
> + [ -n  ]
> + [ server = server ]
> + SYSTEM_NAME=k3s
> + printf %s k3s
> + sed -e s/[][!#$%&()*;<=>?\_`{|}/[:space:]]/^/g;
> + valid_chars=k3s
> + [ k3s != k3s ]
> + SUDO=sudo
> + id -u
> + [ 1000 -eq 0 ]
> + [ -n  ]
> + [ server = server ]
> + SYSTEMD_TYPE=notify
> + [ -n  ]
> + BIN_DIR=/usr/local/bin
> + sudo sh -c touch /usr/local/bin/k3s-ro-test && rm -rf /usr/local/bin/k3s-ro-test
> + [ -n  ]
> + SYSTEMD_DIR=/etc/systemd/system
> + SERVICE_K3S=k3s.service
> + UNINSTALL_K3S_SH=/usr/local/bin/k3s-uninstall.sh
> + KILLALL_K3S_SH=/usr/local/bin/k3s-killall.sh
> + [ true = true ]
> + FILE_K3S_SERVICE=/etc/systemd/system/k3s.service
> + FILE_K3S_ENV=/etc/systemd/system/k3s.service.env
> + get_installed_hashes
> + sudo sha256sum /usr/local/bin/k3s /etc/systemd/system/k3s.service /etc/systemd/system/k3s.service.env
> + true
> + PRE_INSTALL_HASHES=sha256sum: /usr/local/bin/k3s: No such file or directory
> sha256sum: /etc/systemd/system/k3s.service: No such file or directory
> sha256sum: /etc/systemd/system/k3s.service.env: No such file or directory
> + [  = true ]
> + INSTALL_K3S_CHANNEL_URL=https://update.k3s.io/v1-release/channels
> + INSTALL_K3S_CHANNEL=stable
> + download_and_verify
> + can_skip_download
> + [  != true ]
> + return 1
> + setup_verify_arch
> + [ -z  ]
> + uname -m
> + ARCH=x86_64
> + ARCH=amd64
> + SUFFIX=
> + verify_downloader curl
> + command -v curl
> + [ -x /snap/bin/curl ]
> + DOWNLOADER=curl
> + return 0
> + setup_tmp
> + mktemp -d -t k3s-install.XXXXXXXXXX
> + TMP_DIR=/tmp/k3s-install.OtS1512181
> + TMP_HASH=/tmp/k3s-install.OtS1512181/k3s.hash
> + TMP_BIN=/tmp/k3s-install.OtS1512181/k3s.bin
> + trap cleanup INT EXIT
> + get_release_version
> + [ -n  ]
> + [ -n  ]
> + info Finding release for channel stable
> + echo [INFO]  Finding release for channel stable
> [INFO]  Finding release for channel stable
> + version_url=https://update.k3s.io/v1-release/channels/stable
> + curl -w %{url_effective} -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null+ 
> sed -e s|.*/||
> + VERSION_K3S=v1.22.7+k3s1
> + info Using v1.22.7+k3s1 as release
> + echo [INFO]  Using v1.22.7+k3s1 as release
> [INFO]  Using v1.22.7+k3s1 as release
> + download_hash
> + [ -n  ]
> + HASH_URL=https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> + info Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> + echo [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> + download /tmp/k3s-install.OtS1512181/k3s.hash https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> + [ 2 -eq 2 ]
> + curl -o /tmp/k3s-install.OtS1512181/k3s.hash -sfL https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-amd64.txt
> + cleanup
> + code=23
> + set +e
> + trap - EXIT
> + rm -rf /tmp/k3s-install.OtS1512181
> + exit 23
> gmacario@hw0929:~$
> ```

god thanks mate .. works like charm!

**Comment by surya-abs** [comment]
> i had this same issue, i tried many many things.
> 
> sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
> 
> this solved it. hope it does for you someone else as well.

God thanks mate .. you;re a savior works like charm!
