### ISSUE TITLE
No Network Access when advertise-address Specified

### ISSUE THREAD

**Issue by cawoodm** [k3s-io/k3s#5544]
**Environmental Info:**
K3s Version: v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux uzug29 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x8iles (default true)                                                          │6_64 x86_64 x86_64 GNU/Linux 

Cluster Configuration:
2 master servers

**Describe the bug:**
As discussed in #5455 we are seeing network issues when we try to specify a custom CIDR for pods and services:
```yaml
cluster-dns: 192.168.178.10
cluster-cidr: 192.168.176.0/23
service-cidr: 192.168.178.0/23
```

**Steps To Reproduce:**
```bash
# Install K3S
export INSTALL_K3S_VERSION=v1.23.6+k3s1
curl -sfL https://get.k3s.io | sh -s - server --config /etc/my/k3s/config.yaml
# Initialize the cluster
systemctl stop k3s
k3s server --cluster-init --config /etc/my/k3s/config.yaml
```

Run an ubuntu pod and ping google:
```
kubectl run ubuntu -i --tty --image ubuntu:latest -- sh
apt update
apt install -y curl net-tools iputils-ping procps dnsutils
ping google.com
``


**Expected behavior:**
When we access a pod we expect to `ping google.com` successfully.

**Actual behavior:**
```bash
# ping google.com
ping: google.com: Temporary failure in name resolution
# nslookup
>
> google.com
;; connection timed out; no servers could be reached
```

**Additional context / logs:**
### Logs for coredns
```
[WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://192.168.178.1:443/version": dial tcp 192.168.178.1:443: connect: no route to host
[INFO] plugin/ready: Still waiting on: "kubernetes"           
[INFO] plugin/ready: Still waiting on: "kubernetes"               
 [INFO] plugin/ready: Still waiting on: "kubernetes" 
```
### Logs for helm-install-traefik
```
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik http ││ s://192.168.178.1:443/static/charts/traefik-10.19.300.tgz --values /confi ││ g/values-01_HelmChart.yaml                                                ││ Error: INSTALLATION FAILED: failed to download "https://192.168.178.1:443 ││ /static/charts/traefik-10.19.300.tgz"
```

### Logs for metrics-server
```
 panic: unable to load configmap based request-header-client-ca-file: Get "https://192.168.178.1:443/api/v1/namespaces/kube-system/configmaps/extension- ││ apiserver-authentication": dial tcp 192.168.178.1:443: connect: no route to host 
```

**Comment by brandond** [comment]
I'm curious why would you set the advertised address to a random unassigned IP address. This tells the node to advertise its address as being something that is guaranteed not to be reachable. What behavior did you expect from doing that?

**Comment by cawoodm** [comment]
I had assumed, apparently incorrectly, that this would be the cluster‘s IP advertised via ARP by a node similarly to MetalLB.

Docs are a bit thin, could you explain?

**Comment by brandond** [comment]
It is passed through to the apiserver argument of the same name, as documented at https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> --advertise-address string
> The IP address on which to advertise the apiserver to members of the cluster. This address must be reachable by the rest of the cluster. If blank, the --bind-address will be used. If --bind-address is unspecified, the host's default interface will be used.

The load-balancer that comes with k3s behaves as described in the docs; notably it just uses the nodes actual IP address and does not include any virtual IP or ARP advertisement behavior.
https://rancher.com/docs/k3s/latest/en/networking/#how-the-service-lb-works

**Comment by cawoodm** [comment]
I'm no wiser after reading the Kubernetes docs as to what this IP is or should be.

Does "advertise" not imply ARP? What exactly is being advertised and how? If the IP exists already and is routed to the node, why advertise it?

**Comment by cawoodm** [comment]
From the Service LB docs:

> If the Service LB runs on a node that has an external IP, it uses the external IP.

Could we somehow specify this "external IP"? Sounds like that would make MetalLB superfluous. Hmm🤔

**Comment by brandond** [comment]
> Does "advertise" not imply ARP? What exactly is being advertised and how?

"Advertise" in the case of the apiserver addresses means list it as an endpoint for the in-cluster kubernetes service. 

If you're making assumptions about Kubernetes and thinking about Layer 2 behavior you're probably approaching things from the wrong discipline. Those sorts of things are generally delegated to other components, such as the CNI, load-balancer controller, etc. Kubernetes itself is designed to be agnostic of those details so that it can be deployed in a wide variety of environments. The infrastructure provider or system administrator is responsible for providing the correct implementations and configurations for their environment.

> Could we somehow specify this "external IP"

yes, this is what the `--node-exernal-ip` flag is for: https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#agent-networking

**Comment by cawoodm** [comment]
OK, so to summarize we should set `advertise-address` to an IP address which is or will be routed to the control plane servers - either via an external load balancer or using MetalLB or Kube VIP.

* I still don't see in what way this is "advertised". To whom and by what mechanism?
* How does `advertise-address` differ from `node-exernal-ip`?
  * Is `advertise-address` only for the Kubernetes API and the external IP for services?

**Comment by brandond** [comment]
> I still don't see in what way this is "advertised". To whom and by what mechanism?

As I said above, "advertise" in the case of the apiserver addresses means list it as an endpoint for the in-cluster kubernetes service. `kubectl get endpoints -n default kubernetes`.

> How does advertise-address differ from node-exernal-ip?

In the output of `kubectl get node -o wide`, note that there are internal-ip and external-ip fields? `--node-external-ip` sets the external IP for that node.

> Is advertise-address only for the Kubernetes API and the external IP for services?

It is only for the apiserver endpoint address, as described above. The node IP or node external IP is what's used for LoadBalancer-type Services when using the ServiceLB controller. Different LB controllers (kube-vip, metallb, etc) behave differently, and can assign load-balancer service IPs from pools of addresses not already bound to the node; you may want to look into those if that's the behavior you're looking for.
