### ISSUE TITLE
k3s-agent can not start runtime: out of memory: cannot allocate 4398587576320-byte block (66584576 in use)

### ISSUE THREAD

**Issue by chinasoftgit** [k3s-io/k3s#5545]
After restarted k3s agent node,  k3s-agent service can not start, fatal  error out of memory .  But node has sufficient  memory resources. The error log:
 Starting Lightweight Kubernetes...
May  6 22:05:14 sdaict-client-2 systemd[1]: Started Lightweight Kubernetes.
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime: out of memory: cannot allocate 4398587576320-byte block (66617344 in use)
May  6 22:05:15 sdaict-client-2 k3s[5459]: fatal error: out of memory
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime stack:
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.throw(0x3bc23f3, 0xd)
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/panic.go:1116 +0x54
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.largeAlloc(0x40020000028, 0x1, 0x1)
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/malloc.go:1179 +0x1a0
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.mallocgc.func1()
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/malloc.go:1071 +0x44
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.systemstack(0x65c0ea0)
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/asm_arm64.s:235 +0xa0
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.mstart()
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/proc.go:1116
May  6 22:05:15 sdaict-client-2 k3s[5459]: goroutine 1 [running, locked to thread]:
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.systemstack_switch()
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/asm_arm64.s:180 +0x8 fp=0x4000f79970 sp=0x4000f79960 pc=0x466078
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.mallocgc(0x40020000028, 0x37acc80, 0x1, 0x40001c04d0)
May  6 22:05:15 sdaict-client-2 k3s[5459]: #011/usr/local/go/src/runtime/malloc.go:1070 +0x778 fp=0x4000f79a30 sp=0x4000f79970 pc=0x40cc98
May  6 22:05:15 sdaict-client-2 k3s[5459]: runtime.newobject(0x37acc80, 0x40001c04d0)

K3S vesrion and node memory disk messages:

:/# k3s --version
k3s version v1.19.4+k3s1 (2532c10f)
root@sdaict-client-2:/# free -g
              total        used        free      shared  buff/cache   available
Mem:              7           1           5           0           1           6
Swap:            30           0          30
:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   57G   16G   39G  30% /
none            3.5G     0  3.5G   0% /dev
tmpfs           3.8G   52K  3.8G   1% /dev/shm
tmpfs           3.8G  199M  3.7G   6% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1  234G   66G  157G  30% /data
tmpfs           778M     0  778M   0% /run/user/1000
overlay         234G   66G  157G  30% /data/docker/overlay2/c34bef7569315bdd24eda97eccdaddd6c43571cbe84f9cd72ba495bb492a4748/merged
overlay         234G   66G  157G  30% /data/docker/overlay2/3a39ebe6c919cc99d7b633e7e166dae5cb8010118a655e2bfa7868641c698f13/merged

:/# top -c
top - 22:01:07 up  5:45,  1 user,  load average: 0.34, 0.25, 0.20
Tasks: 264 total,   1 running, 263 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.4 sy,  0.0 ni, 99.2 id,  0.0 wa,  0.4 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.4 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.4 us,  0.8 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  1.7 us,  0.4 sy,  0.0 ni, 97.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  2.5 us,  0.4 sy,  0.0 ni, 97.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  7958064 total,  5383932 free,  1238656 used,  1335476 buff/cache
KiB Swap: 31644740 total, 31644740 free,        0 used.  6329460 avail Mem

Before restarted node，k3s-agent service is good. why k3s-agent service can not start after restarted  node?

**Comment by brandond** [comment]
That is a quite old version of k3s. Can you reproduce this with a newer version?

**Comment by chinasoftgit** [comment]
> That is a quite old version of k3s. Can you reproduce this with a newer version?

I'm not sure a newer version reproduce this question。Using old version, other nodes of the cluster are normal，only this node is error after shut down and restart。
