### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by xxl4tomxu98** [k3s-io/k3s#5547]
**Environmental Info:**
K3s Version: k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: Linux 2TK10401S7 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: just installation got problems

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: [INFO]  Using v1.23.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.23.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.23.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Expected behavior:** [INFO]  systemd: Starting k3s

**Actual behavior:** System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
This appears to be a systemd-based distro on WSL2, but apparently systemd is not functional? That error message is coming from the `systemctl start k3s`, not from K3s itself. That seems pretty broken.

**Comment by phillipsj** [comment]
@xxl4tomxu98 WSL doesn't support systemd due to the startup time and overhead. If I recall correctly it leverages sysvinit. You will need to edit that and add it there if you want. You can also enable systemd, that is more challenging. 

Stuff that may help:

* https://boxofcables.dev/deploying-rancher-on-k3s-on-wsl2/
* https://www.theregister.com/2021/11/17/ubuntu_team_systemd_windows_wsl2

**Comment by cwayne18** [comment]
Closing this out based on Jamie's response

**Comment by kzorluoglu** [comment]
Edit /etc/wsl.conf in WSL Distro

```
[boot]
systemd=true
```
