### ISSUE TITLE
K3s pod not able to access internet which is in different network

### ISSUE THREAD

**Issue by ashissharma97** [k3s-io/k3s#5549]
Hi,
I have a K3s Cluster master node in the cloud and the worker nodes are Raspberry Pis both of them are in different networks. After deploying applications in the worker node pods cannot access the internet whereas the worker node has the internet. I am doing something wrong or this is expected. 

K3s Version: v1.23.3+k3s1

Thanks for help
Ashis

**Comment by brandond** [comment]
Are you sure that your CNI backend can actually send traffic between the two networks? The default flannel backend is vxlan and is only designed for use between nodes on the same network; this is most likely not going to be successful in passing in-cluster traffic (for example, traffic to the coredns service) between the agent and server when they are not on the same private network.

You might look at using wireguard, or another encrypted tunnel that is suitable for use over the internet.
