### ISSUE TITLE
Inclusion of 'non-default feature-gate enabled' features, particularly from kubernetes 1.24 onwards.

### ISSUE THREAD

**Issue by JamesTGrant** [k3s-io/k3s#5551]
**Is your feature request related to a problem? Please describe.**
From kubernetes 1.24 onwards, features maturing from alpha to beta will no longer be enabled by default. https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/#beta-apis-off-by-default Currently k3s excludes non-default enabled k8s features. Will this k3s policy change with kubernetes 1.24? If not, there may be a long period where new kubernetes features are not availalble in k3s.

**Describe the solution you'd like**

- I would like the inclusion in the k3s of all kubernetes features in beta in k8s. These beta features would be enabled/not enabled by default in k3s as per the corresponding k8s version.
- I would like the inclusion in the k3s of all kubernetes features in alpha in k8s. By default, in k3s, these alpha features would be not enabled unless the relevant feature-gate is configured.

I would like the above features in k3s even at the expense of a larger binary. Controlling the enablement of features by feature-gates, as today, is fine and good, for example:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable=traefik' \
        'feature-gates=StatefulSetAutoDeletePVC=true' \

```
I don't mind if this means there's a an option to download either a small k3s binary or a large k3s binary. I also don't mind if there's only a single k3s binary (like today) which is bigger than the binary today - I suspect many other people will mind!

**Describe alternatives you've considered**

Using a single node k8s - k3s is really good for single node applications.

**Additional context**

One feature I'd like to have access to, is statefulset-pvc-retention-policy for example. One of the many useful newish features which are still in alpha. There are others I'd like to use too.
https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/#the-new-statefulset-pvc-retention-policy

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> features maturing from alpha to beta will no longer be enabled by default. https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/#beta-apis-off-by-default Currently k3s excludes non-default enabled k8s features.

We're not planning on changing our general policy about enabling features.

Note that there may be some confusion here about what upstream is saying; please read [KEP-3136](https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/3136-beta-apis-off-by-default) and node that they are only changing the policy for beta APIs, NOT FeatureGates:

> **Non-Goals**
> Change feature gate defaults. Feature gates control new features (not just new APIs) and they are on by default for beta features. This KEP is not changing the lifecycle flow for feature gates. It is currently alpha=off-by-default, beta=on-by-default, stable=locked-to-on.

**Comment by JamesTGrant** [comment]
Thank you @brandond - I had misunderstood, thank you for taking the time to explain. I see this also, which was useful to updating my old, wrong understanding: https://github.com/k3s-io/k3s/issues/1017

**Comment by JamesTGrant** [comment]
Final update. The effective way to do this for my usecase:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--kube-apiserver-arg=feature-gates=StatefulSetAutoDeletePVC=true' \

```

**Comment by TwiN** [comment]
For those lost and confused, you'll likely find `ExecStart=/usr/local/bin/k3s...` in `/etc/systemd/system/k3s.service`.
