### ISSUE TITLE
failed to setup network for sandbox

### ISSUE THREAD

**Issue by cawoodm** [k3s-io/k3s#5556]
**Environmental Info:**
K3s Version: 
```
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5
```

Node(s) CPU architecture, OS, and Version: 
```
Linux uzug29 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
3 servers, embedded etcd

**Describe the bug:**
Of our 3 nodes, one is unable to deploy any pods - including traefik - the pod remains in the ContainerCreating state with the following events:

> Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "***GUID***": plugin type="flannel" failed (add): open /run/flannel/subnet.env: no such file or directory

**Steps To Reproduce:**
Installed 3 servers according to [docs](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/) but with CIDRs specified

**Expected behavior:**
Expected node to handle DaemonSets like traefik and pods in general.

**Actual behavior:**
No pods can be scheduled on the node.

**Additional context / logs:**
The logs indicate `CIDRNotAvailable` but we have provided 512 addresses for pods and services and we haven't even started adding our own pods/services yet.
```
E0512 10:08:59.038481  439882 controller_utils.go:248] Error while processing Node Add: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0512 10:08:59.038713  439882 node_controller.go:391] Initializing node ecom-app07 with cloud provider
E0512 10:08:59.038747  439882 node_controller.go:213] error syncing 'ecom-app07': failed to get provider ID for node ecom-app07 at cloudprovider: failed to get instance ID from cloud provider: address annotations not yet set, requeuing
W0512 10:08:59.038884  439882 actual_state_of_world.go:539] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="ecom-app07" does not exist
I0512 10:08:59.039668  439882 event.go:294] "Event occurred" object="ecom-app07" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node ecom-app07 status is now: CIDRNotAvailable"
```

### config.yaml
We have the following configures (the same) on all nodes:
```yaml
# Allowed Ranges for Cluster IPs
cluster-cidr: 192.168.176.0/23
service-cidr: 192.168.178.0/23
cluster-dns: 192.168.178.10
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> E0512 10:08:59.038481  439882 controller_utils.go:248] Error while processing Node Add: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range

> cluster-cidr: 192.168.176.0/23

The default CIDR mask is /24, so you've reduced the cluster CIDR to the point  where you only have enough space for 2 nodes. See: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
>--node-cidr-mask-size int32
>   Mask size for node cidr in cluster. Default is 24 for IPv4 and 64 for IPv6.

**Comment by cawoodm** [comment]
We have been given a CIDR of `192.168.176.0/20` so that the default `10.41.*`/`10.42.*` doesn't conflict with existing LAN reservations.

I merely divided this 4096 block into 2 blocks of 512 (far more than we will ever need) for pods and services respectively:

* cluster-cidr: 192.168.176.0/23 => 512 (192.168.176.0 -> 192.168.177.255)
* service-cidr: 192.168.178.0/23 => 512 (192.168.178.0 -> 192.168.179.255)

I don't understand how the masks work and how, as you say, this setting results in only 2 IP addresses.

**Comment by cawoodm** [comment]
It's also not clear from the docs if this is a per-node config or a cluster-wide setting.

**Comment by cawoodm** [comment]
With `kubectl cluster-info dump | grep -i cidr` I see that the ranges I provided have been subdivided to the nodes.

* node1: "podCIDR": "192.168.176.0/24",
* node2: "podCIDR": "192.168.177.0/24",
* node3: CIDRNotAvailable 🔥

Sorry, I just re-read your comment and see you are referring to `nodes` and not `pods`!

**Comment by cawoodm** [comment]
Thanks @brandond your assistance solved it!

```yaml
cluster-cidr: 192.168.176.0/21
service-cidr: 192.168.184.0/21
cluster-dns: 192.168.184.10
```
