### ISSUE TITLE
Objects removed from a manifest file aren't removed from the cluster

### ISSUE THREAD

**Issue by thedadams** [k3s-io/k3s#5559]
**Environmental Info:**
K3s Version: v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: any

Cluster Configuration: 1 server

**Describe the bug:**
When a manifest file is put in the /var/lib/rancher/k3s/server/manifests directory, the objects are correctly deployed to the cluster. However, if an object is removed from the file (for example, if the file is made blank), the objects will not be removed from the cluster.

**Steps To Reproduce:**
1. Install K3S via curl
2. Put a file in the referenced directory to deploy an simple nginx deployment
3. Wait for the pods to be deployed.
4. Change the file's contents to be blank.

**Expected behavior:**
The nginx deployment is removed from the cluster.

**Actual behavior:**
The nginx deployment is not removed from the cluster.

**Backporting**

- [x] Needs backporting to older releases

**Comment by brandond** [comment]
We used to track the DesiredSet GVKs in the AddOn's `status.gvks` field, but stopped doing so when we switched to using Wrangler's apply in
https://github.com/k3s-io/k3s/commit/c0702b04927fb18693b168ddb3b12be40d845d5c#diff-c4f8a6638f496b7edccd14823bd72217e2b7fda10b88f055c43d754d0ef742c2L164-L168

Prior to that change the GVKs were nilled out and reset based on the list of objects to be applied, so it wasn't used when removing.

The code to delete things was added in 
https://github.com/k3s-io/k3s/commit/0374c4f63d056df01c3e9e8cf4d77a6461169070#diff-c4f8a6638f496b7edccd14823bd72217e2b7fda10b88f055c43d754d0ef742c2R200-R203 

That code is still mostly used, but relies on having the file around to discover the list of GVKs that need to be searched for objects to be deleted. If the file is deleted or modified, the current implementation may not find all the objects that need to be deleted.

The fix from @thedadams is probably a good step towards fixing this, as tracking applied GVKs and then using them when applying future updates SHOULD ensure that wrangler searches the proper GVKs for managed objects. My apologies for dismissing your fix before I had a chance to dig into it; I just assumed something had broken on the wrangler side again.

As an additional step, we should switch to a cluster-scoped AddOn type and use `addon.WithSetOwnerReference(false, true)` to ensure that the Kubernetes garbage collector catches anything wrangler misses when the AddOn resource is deleted.

**Comment by ShylajaDevadiga** [comment]
Validated using commit id: 1ef34728c99ba8831bb22b34acd18211df7f7155 on master branch
When the nginx deployment file exists and file content is deleted the deployment is removed.
```
root@ip-172-31-1-111:/var/lib/rancher/k3s/server/manifests# logout
ubuntu@ip-172-31-1-111:~$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-7b7dc8d6f5-7486h   1/1     Running     0          3m19s
kube-system   coredns-b96499967-4p76m                   1/1     Running     0          3m19s
kube-system   helm-install-traefik-crd-26w5b            0/1     Completed   0          3m19s
kube-system   svclb-traefik-nz948                       2/2     Running     0          3m5s
kube-system   helm-install-traefik-sbmmb                0/1     Completed   1          3m19s
kube-system   metrics-server-668d979685-m5trm           1/1     Running     0          3m19s
kube-system   traefik-7cd4fcff68-75wp7                  1/1     Running     0          3m5s
default       nginx-deployment-6595874d85-tgxps         1/1     Running     0          2m43s
default       nginx-deployment-6595874d85-8vqnk         1/1     Running     0          2m43s
default       nginx-deployment-6595874d85-rlmm4         1/1     Running     0          2m43s
ubuntu@ip-172-31-1-111:~$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-7b7dc8d6f5-7486h   1/1     Running     0          3m23s
kube-system   coredns-b96499967-4p76m                   1/1     Running     0          3m23s
kube-system   helm-install-traefik-crd-26w5b            0/1     Completed   0          3m23s
kube-system   svclb-traefik-nz948                       2/2     Running     0          3m9s
kube-system   helm-install-traefik-sbmmb                0/1     Completed   1          3m23s
kube-system   metrics-server-668d979685-m5trm           1/1     Running     0          3m23s
kube-system   traefik-7cd4fcff68-75wp7                  1/1     Running     0          3m9s
```
