### ISSUE TITLE
Agent Nodes Saying Not Ready

### ISSUE THREAD

**Issue by chrisblatt** [k3s-io/k3s#5561]
**Environmental Info:**
K3s Version: v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 3 Raspberry Pi 4s 4 GB, Rasbian (Debian GNU/Linux 11 (bullseye))
Linux rpi4-primary 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

Cluster Configuration: 1 server, 2 agents

**Describe the bug:**
When I run kubectl get no, it shows the server as Ready but 2 agent nodes as Not Ready

NAME            STATUS     ROLES                  AGE   VERSION
rpi4-worker01   NotReady   <none>                 75d   v1.23.6+k3s1
rpi4-worker02   NotReady   <none>                 75d   v1.23.6+k3s1
rpi4-primary    Ready      control-plane,master   75d   v1.23.6+k3s1

I have disabled ufw on all 3 PIs, and I see these logs on the 2 agents:

May 13 08:24:30 rpi4-worker01 k3s[655]: time="2022-05-13T08:24:30-04:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:56322->127.0.0.1:6444: read: connection reset by peer"

I looked at a few other issue logs and tried to curl the various api server addresses:
curl -vk https://127.0.0.1:6444/cacerts
*   Trying 127.0.0.1:6444...
* Connected to 127.0.0.1 (127.0.0.1) port 6444 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to 127.0.0.1:6444
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to 127.0.0.1:6444

curl -vk https://10.20.0.18:6443/cacerts
*   Trying 10.20.0.18:6443...
* connect to 10.20.0.18 port 6443 failed: No route to host
* Failed to connect to 10.20.0.18 port 6443: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.20.0.18 port 6443: No route to host

**Steps To Reproduce:**

- Installed K3s: Using the install script, no env vars for the server install, just server and token on agent install

I didn't start seeing Not Ready until I ran the k3s-killall.sh on the server node, at least that happened right around the time this happened but it could be a coincidence.

**Expected behavior:**
Agent nodes should be in Ready state

**Actual behavior:**
Agent nodes are in Not Ready state

**Additional context / logs:**
Can provide more information if needed, not sure what else would be helpful.

**Backporting**
Not sure

**Comment by brandond** [comment]
> Failed to connect to 10.20.0.18 port 6443: No route to host

That sounds more like an issue with your network. Why don't the agents have a route to the server?

**Comment by chrisblatt** [comment]
Yeah as I have been troubleshooting more I keep thinking its a network issue. All 3 nodes can ping the gateway (10.20.0.1) but when I try to ping each node from another node, it says destination host unreachable (just a testing cluster so currently using wlan interface) but I think it should work with the current ip route table:
worker01:
default via 10.20.0.1 dev wlan0 src 10.20.0.19 metric 303
10.20.0.0/24 dev wlan0 proto dhcp scope link src 10.20.0.19 metric 303
worker02:
default via 10.20.0.1 dev wlan0 src 10.20.0.20 metric 303
10.20.0.0/24 dev wlan0 proto dhcp scope link src 10.20.0.20 metric 303
primary:
default via 10.20.0.1 dev wlan0 src 10.20.0.18 metric 303
10.20.0.0/24 dev wlan0 proto dhcp scope link src 10.20.0.18 metric 303
10.42.0.0/24 dev cni0 proto kernel scope link src 10.42.0.1
10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink
10.42.2.0/24 via 10.42.2.0 dev flannel.1 onlink
169.254.0.0/16 dev flannel.1 scope link src 169.254.124.53 metric 204
169.254.0.0/16 dev veth21930f18 scope link src 169.254.160.143 metric 206
169.254.0.0/16 dev veth49cd8dc5 scope link src 169.254.26.115 metric 207
169.254.0.0/16 dev veth93ca8e27 scope link src 169.254.137.89 metric 208
169.254.0.0/16 dev vethd9fc8942 scope link src 169.254.53.87 metric 209
169.254.0.0/16 dev veth13d804a4 scope link src 169.254.45.23 metric 210
169.254.0.0/16 dev veth5c20db73 scope link src 169.254.47.175 metric 211
169.254.0.0/16 dev vethee04c781 scope link src 169.254.138.63 metric 212
169.254.0.0/16 dev vetha18e5c21 scope link src 169.254.165.74 metric 213
169.254.0.0/16 dev veth8623bff6 scope link src 169.254.56.225 metric 214
169.254.0.0/16 dev veth0ed39028 scope link src 169.254.182.151 metric 215
169.254.0.0/16 dev veth95af6b44 scope link src 169.254.44.210 metric 216

**Comment by chrisblatt** [comment]
The biggest part that is confusing me, I can ping my 3 nodes (10.20.0.18, 10.20.0.19, and 10.20.0.20) from a workstation in a different network, but trying to ping eachother doesn't work. Networking was working fine until yesterday my wifi went out and when it came back this issue appeared, but I didn't make any changes. I can ping google.com and the gateway so I was thinking it was a firewall issue maybe but when I turned off ufw on all nodes it didn't fix anything.

**Comment by chrisblatt** [comment]
It could just be a network issue on my end, but wanted to check that it wasn't a misconfiguration with my k3s setup or something. Each node can ping other nodes on the network and can ping the gateway and google, but cannot ping each other. That made me think firewall so I posted here but if it just a local network issue I can close this.

**Comment by brandond** [comment]
Yeah, if the nodes can't ping each other then K3s isn't going to work either.

**Comment by chrisblatt** [comment]
The only firewall I should have to worry about blocking communication between nodes would be if I setup ufw on the nodes myself? the iptables that came with k3s shouldn't be causing any issues?

**Comment by chrisblatt** [comment]
Should netstat should ipv4 tcp have a listening connection for port 6443? because I don't see that in the output:
`root@rpi4-primary:/home/pi# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10258         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      492/sshd: /usr/sbin
tcp        0      0 0.0.0.0:31000           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:31128           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:32500           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:30370           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:30670           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 127.0.0.1:10010         0.0.0.0:*               LISTEN      670/containerd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      3928/sshd: pi@pts/0
tcp        0      0 0.0.0.0:32000           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:30000           0.0.0.0:*               LISTEN      627/k3s server
tcp        0      0 0.0.0.0:30088           0.0.0.0:*               LISTEN      627/k3s server
tcp6       0      0 :::22                   :::*                    LISTEN      492/sshd: /usr/sbin
tcp6       0      0 :::10250                :::*                    LISTEN      627/k3s server
tcp6       0      0 :::6443                 :::*                    LISTEN      627/k3s server
tcp6       0      0 ::1:6010                :::*                    LISTEN      3928/sshd: pi@pts/0
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           386/avahi-daemon: r
udp        0      0 0.0.0.0:68              0.0.0.0:*                           617/dhcpcd
udp        0      0 0.0.0.0:43112           0.0.0.0:*                           386/avahi-daemon: r
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
udp6       0      0 :::5353                 :::*                                386/avahi-daemon: r
udp6       0      0 :::44981                :::*                                386/avahi-daemon: r
`

**Comment by brandond** [comment]
```
tcp6 0 0 :::6443 :::* LISTEN 627/k3s server
```

This is what's known as a dual-stack bind; it's listening on both 0.0.0.0 [::] which is the ipv6 equivalent.

**Comment by chrisblatt** [comment]
Ah that makes sense, thanks for explaining that. This is only a test cluster so I think I might try to blow it away and redo, restarting my router and moving the cluster to a different network didn't solve the issue, not sure why it went into a broken state but it should be easy enough to rebuild, most of my setup was through helm charts.

**Comment by brandond** [comment]
If possible you might try using ethernet instead of wifi. I have seen some APs misbehave if they see multiple IPs coming from a single client.

**Comment by chrisblatt** [comment]
Thanks for the tip, I will try that out!

**Comment by chrisblatt** [comment]
It was the AP, based on your tip, I turned off one of the APs at my house and forced the cluster to join another one. After that they could ping eachother. A different issue to troubleshoot now, but this is fixed haha! I have only used k3s for the last few months but it is a great product especially for quick kubernetes testing, I appreciate the effort and time!
