### ISSUE TITLE
What is the minimum Linux kernel version required for K3S? 

### ISSUE THREAD

**Issue by hyl1416134510** [k3s-io/k3s#5569]
What is the minimum Linux kernel version required for K3S? The kernel version 3.10 that we run on embedded devices does not support some of the necessary components, such as CONFIG_IP_NF_NAT, CONFIG_CGROUP_PIDS

**Comment by bwenrich** [comment]
I am not finding a specific note on the minimum kernel required for k3s or k8s.
However, from the container runtime side I do see a suggestion in containerd to use a 4.x kernel https://github.com/containerd/containerd/blob/main/README.md#runtime-requirements
