### ISSUE TITLE
Corrupt Etcd and then the cluster with mis-behaving node

### ISSUE THREAD

**Issue by liyimeng** [k3s-io/k3s#5576]
**Environmental Info:**
K3s Version:  1.21.7  --> 1.23.6 

Node(s) CPU architecture, OS, and Version: 

amd64, ubuntu 20.04 
Cluster Configuration:

3 servers
**Describe the bug:**

I was trying to upgrade my hobby cluster from 1.21.7 to 1.23.6.  I found a simple mis-behaviour can corrupt the Etcd database and then screw the entire cluster.  Luckily, I can do a cluster-reset to store it from previous snapshots.

**Steps To Reproduce:**

- Installed K3s version 1.21.7 
- Upgrade a node to version 1.23.6, but change its hostname before joining back to cluster. 
- Cluster see the upgraded node as a new node since its hostname is changed

**Expected behavior:**

- New joining node should be rejected and Etcd data should be protected
**Actual behavior:**

- New joining node is reported as Ready, but get no roles reported 
- Check log, it say k3s-serving secret is failed to decode
- do a kubectl get secret --all-namespace, command failed and saying data is corrupted.
- No any new pod or whatever need access to secret operations fails. 
  
It seems the misbehaviour node propagated corrupted data into the Etcd cluster and screw entire cluster.
**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
> * Upgrade a node to version 1.23.6, but change its hostname before joining back to cluster.
> * Cluster see the upgraded node as a new node since its hostname is changed

Yes, don't do that. If you're going to change the node name, make sure to delete the old server from the cluster using `kubectl delete node` **BEFORE** you rejoin it to the cluster.

**Comment by liyimeng** [comment]
@brandond Sorry, I was not clear enough. I don't mean to do that. In my case, it was an accident. My point is that the penalty of such a mistake is too high. k3s should detect such a mistake and prevent it form nuking down the entire cluster.

**Comment by brandond** [comment]
It shouldn't nuke the cluster, but I would expect that you'd end up with a 4-node etcd cluster. One of the node is permanently down (due to it being the old node pre-rename) so if you take one of the 3 real nodes down you are at 2/4 which no longer has quorum, and yes your cluster will stop functioning.

I'm not sure how K3s should guard against you intentionally adding servers to the cluster? I suppose we could prevent adding new cluster members when there is a NotReady server, but will be times when it's necessary to do that in order to recover from an outage.

**Comment by liyimeng** [comment]
It actually dose, and it is the reason why I report the issue. 

Somehow, it corrupts secret data and propagate the corrupted data into the entire etcd cluster. When there is enough corrupted data spreading over the cluster, the k3s cluster lost its function, at least the entire controller plane is destroyed. 

One possible way for doing this is to check at startup. If etcd database is already init-ed, and hostname is in-consistent, maybe even check the IP address as well, refuse to join the member  into etcd cluster.  

What do you think? @brandond

**Comment by brandond** [comment]
> Somehow, it corrupts secret data 

Can you explain what you mean by this? It sounds like etcd itself is still operational but somehow you have multiple controller-managers active at the same time? You haven't attached any logs so I'm not sure what you're seeing.

If all the nodes have the same etcd data on disk they should have the same certificates and keys, so nothing within the datastore itself should be corrupted. We don't enable secrets-encryption by default on K3s, so those shouldn't be affected either, even if you did have different keying material on different nodes.

**Comment by liyimeng** [comment]
@brandond I was in hurry to bring back my cluster and forget to save a copy of the log. 

etcd cluster still functioning as it should, but the data stored in it is corrupted. e.g. secrets are encoded in base64 and stored in etcd.  I remember the log are flooded with  complaints saying that it can not list secrets since base64 decoding failed.

When having the bad behaviour node running longer, I see more secrets data corrupted.  So I guess, for some reason, the "new" node write some bad data into the etcd cluster, overwrite the  good one with the bad one.  I don't know why. 

When I have more resource, I will try to reproduce it and collect some logs.
