### ISSUE TITLE
does k3s simplify containerd 

### ISSUE THREAD

**Issue by ningmingxiao** [k3s-io/k3s#5578]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by ningmingxiao** [comment]
@brandond   does k3s simplify containerd？containerd sometimes use high memory

**Comment by brandond** [comment]
Ah, there's the question. It looked like the issue had been opened without any comments, and I wasn't able to divine what you wanted info on from the title.

The only customizations we make to containerd are to support image rewrites. The CPU and memory footprint should be identical to upstream containerd.
