### ISSUE TITLE
"Automatic" mode

### ISSUE THREAD

**Issue by cweagans** [k3s-io/k3s#5581]
**Is your feature request related to a problem? Please describe.**

k3s removes a lot of the complexity of standing up a Kubernetes cluster, which is great! There is still some k3s-related complexity that I have to understand as a new user though. It would be really cool if there were a way to stand up a kubernetes cluster without really having to worry about the inner workings of Kubernetes _at all_.

**Describe the solution you'd like**

It'd be cool if there was an "automatic" mode in k3s. This could potentially be the default, so when you're standing up a new node, you're not specifying whether a given node is a k3s "agent" or "server" anymore - it's just part of the k3s cluster.

The k3s server stuff is just another workload at that point, so k3s could (for instance) determine how many nodes are in the cluster and by extension, how many "server" workloads are needed to effectively coordinate that work. If one of the nodes currently designated as a server dies off suddenly, then another node in the cluster should be nominated as a server node, the components start up, and that node takes over for the one that was lost. There wouldn't be a distinction between a server node or an agent node: they're all just nodes and some of them happen to be running some extra coordination workloads.

This would be really neat for autoscaling k3s clusters too: as the cluster scales up, k3s can add the extra coordination components to some of the nodes as needed.

You could take this idea a step further, too: there are a number of options for e.g. network drivers, storage drivers, and cluster datastore. In an even more automatic mode, it might be cool to be a little more opinionated about what technologies are used. e.g. pick the one that's easiest to automate and use that one by default. Maybe even run an ingress pod on _every_ node and allow for DNS-based load balancing instead of having to have a real load balancer in front of the kube cluster.

I'm not sure if this deviates too far from the "kubernetes way" of doing things, but it'd sure make my life easier as a very casual kubernetes user.

I think the majority of this is in line with these items from the main docs page:

> Situations where a PhD in K8s clusterology is infeasible
> Simple but powerful “batteries-included” features have been added
> Operation of all Kubernetes control plane components is encapsulated in a single binary and process.

I really just don't want to care about anything under the hood. A working Kubernetes cluster is my goal, and researching the right network driver or figuring out how to do block storage with Longhorn or w/e just isn't relevant to my interests.

**Describe alternatives you've considered**
I've thought about trying to perform this automation outside of k3s, but I don't see that being particularly successful.

I've also thought about just running _all_ k3s nodes as server nodes, but that seems wrong (and probably wasteful).

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
If you don't want to worry about it, then just having one server and the rest as agents is probably the way to go. I doesn't get much simpler than that.

**Comment by cweagans** [comment]
> Kubernetes is NOT simple, and any HA arrangement is going to require some sort of planning.

I am not suggesting that Kubernetes is simple, but that k3s can perhaps encapsulate that complexity and put a nice facade in front of it.

I would challenge you on the second part of your statement however: I think that for > 50-60% of Kubernetes setups, one could make some assumptions about usage and factor in available computing resources on each node, node count, etc and have a pretty workable & automated HA setup. For instance, in your example of having one server and the rest of the nodes as agents, there is some point at which one server becomes inappropriate for the number of agents, right? Let's say 10 agents? 20? The threshold really doesn't matter. At that point, is it unreasonable for k8s to promote two of the nodes in the cluster to servers instead of just being agents?

It's a highly simplified model for sure and there are more than a few use cases for which this model is an inappropriate solution.

(To be clear, I have experience running very large production Kubernetes systems. I don't have an issue digging into the details when I'm being paid for it. Using Kubernetes in non-professional contexts has been of interest, but impractical due to the amount of work that is required to set up and maintain the cluster. In a highly simplified environment (like a pile of Digital Ocean VMs in a single private IP space with no real restrictions on inter-node communication), it seems like fully automating it is not an insurmountable task).

**Comment by dereknola** [comment]
Have you considered using [k3sup](https://github.com/alexellis/k3sup)? Or [autok3s](https://github.com/cnrancher/autok3s)? There are other projects out there that build ontop of k3s for this reason.
