### ISSUE TITLE
k3s node can't resolve internal image registry 

### ISSUE THREAD

**Issue by MojtabaSPR** [k3s-io/k3s#5584]
**Environmental Info:**
K3s Version: 
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
Linux km1 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 master nodes
5 worker nodes

**Describe the bug:**
k3s cluster can not resolve the internal image registry name to private ip.
when I deploy a pod with an image on my internal image registry I get image pulling error:
"pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "myreg.mydomain.com/tools/cicd-helper:latest": failed to resolve reference "myreg.mydomain.com/tools/cicd-helper:latest": failed to do request: Head "https://myreg.mydomain.com/v2/tools/cicd-helper/manifests/latest": dial tcp: lookup myreg.mydomain.com: no such host "

I have tested the name resolution of the internal image registry on each cluster node using nslookup and everything is fine and it return the actual ip address.
Curl and ping of the internal image registry is OK on every node in cluster.
In a running pod everything is fine (curl, nslookup, ping).

Pulling image with crictl on cluster members node has the same error:
sudo crictl pull --creds user1:pass1 myreg.mydomain.com/tools/cicd-helper:latest
"pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "myreg.mydomain.com/tools/cicd-helper:latest": failed to resolve reference "myreg.mydomain.com/tools/cicd-helper:latest": failed to do request: Head "https://myreg.mydomain.com/v2/tools/cicd-helper/manifests/latest": dial tcp: lookup myreg.mydomain.com: no such host"

All cluster nodes have been configured to use my internal dns server as name server.
Dns lookups are fine on all nodes.

**Steps To Reproduce:**
- Installed K3s: 

**Expected behavior:**
Find internal image registry and pull image

**Actual behavior:**
Fails pulling image

**Additional context / logs:**
pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "myreg.mydomain.com/tools/cicd-helper:latest": failed to resolve reference "myreg.mydomain.com/tools/cicd-helper:latest": failed to do request: Head "https://myreg.mydomain.com/v2/tools/cicd-helper/manifests/latest": dial tcp: lookup myreg.mydomain.com: no such host

**Comment by brandond** [comment]
> All cluster nodes have been configured to use my internal dns server as name server.
> lookup myreg.mydomain.com: no such host

How did you configure your nodes to use your internal DNS server? I suspect that K3s found an issue with the DNS configuration on your hosts and is using a public resolver instead.

**Comment by MojtabaSPR** [comment]
@brandond In /etc/netplan/01-netcfg.yaml file
$ cat /etc/netplan/01-netcfg.yaml
`# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
      addresses: [ 192.168.4.24/24 ]
      gateway4: 192.168.4.1
      nameservers:
          search: [ mydomain.com ]
          addresses:
              - "192.168.4.1"`
              
$ cat /run/systemd/resolve/resolv.conf
`# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 192.168.4.1
search mydomain.com`

$ nslookup myreg.mydomain.com
`Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   myreg.mydomain.com
Address: 192.168.4.7`

**Comment by MojtabaSPR** [comment]
Yes. What's your DNS server?
that's weird but for me, it seems to be a DNS server problem.
I used to use regex in DNS records, as a solution I created specific A records instead, and the problem was fixed!!!
I hope it helps you.

**Comment by dberardo-com** [comment]
i am facing a similar issue. is it even possible for k3s to pull images from internal containers ?
