### ISSUE TITLE
Improve Documentation on Passing and Changing Parameters

### ISSUE THREAD

**Issue by cawoodm** [k3s-io/k3s#5587]
k3s v1.23.6+k3s1 (418c3fa8)

**Is your feature request related to a problem? Please describe.**
The learning curve for k3s CLI parameters is steep and fraught with trial and error.

* Most parameters are [explained](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/) in a little more than a single sentence.
* It is not always clear if the parameters can be changed at a later date without rebuilding the cluster.
* It is not always clear how to pass the parameters via a YAML config file.

**Describe the solution you'd like**
Please improve the documentation explaining the parameters, how and when they can be changed and how to pass them correctly on the CLI or as YAML.

**Describe alternatives you've considered**
One example would be that flags such as `--service-cidr` cannot be changed without re-building the cluster.

Another would be the `--init-cluster` flag mentioned [here](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/) - is this something we pass once at installation, once after installation or inside the systemd service at every run? If the latter, on all master nodes? Just one?

Another would be the `--config` flag which apparently and confusingly applies not only to `k3s` but `kubectl` and, if not passed consistently would result in chaos.

Another illustration would be that it seems to be near impossible to pass kube-apiserver-arg flags to k3s via CLI or YAML:

## Attempts via CLI

```bash
k3s server --config /etc/myb/k3s/config.yaml \
  --kube-apiserver-arg='node-monitor-period=2s' \
  --kube-apiserver-arg='node-monitor-grace-period=5s' \
  --kube-apiserver-arg='node-status-update-frequency=2s' \
  --kube-apiserver-arg='pod-eviction-timeout=5s'
```

> Error: unknown flag: --node-monitor-grace-period

```bash
k3s server --config /etc/myb/k3s/config.yaml \
  --kube-apiserver-arg='node-monitor-period=2s' \
  --kube-apiserver-arg='node-status-update-frequency=2s' \
  --kube-apiserver-arg='pod-eviction-timeout=5s'
```

> Error: unknown flag: --node-monitor-period

```bash
k3s server --config /etc/myb/k3s/config.yaml \
  --kube-apiserver-arg node-monitor-period=2s  \
  --kube-apiserver-arg node-status-update-frequency=2s  \
  --kube-apiserver-arg pod-eviction-timeout=5s 
```

  > Error: unknown flag: --node-monitor-period

```bash
k3s server --config /etc/myb/k3s/config.yaml \
  --kube-apiserver-arg node-status-update-frequency=2s  \
  --kube-apiserver-arg pod-eviction-timeout=5s 
```

  > apiserver exited: unknown flag: --node-status-update-frequency

## Attempts via YAML

```yaml
kube-apiserver-arg:
  - 'node-monitor-period=2s'
  - 'node-monitor-grace-period=5s'
  - 'node-status-update-frequency=2s'
  - 'pod-eviction-timeout=5s'
```

```yaml
kube-apiserver-arg:
  - node-monitor-period: 20s
  - node-monitor-grace-period: 20s
  - node-status-update-frequency: 5s
  - pod-eviction-timeout: 5s
```

```yaml
kube-apiserver-arg:
  node-monitor-period: 2s
  node-monitor-grace-period: 5s
  node-status-update-frequency: 1s
  pod-eviction-timeout: 5s

```

**Comment by brandond** [comment]
The reason you're getting errors is because most of these are kube-controller-manager args, not kube-apiserver args. Make sure that the things you're passing are valid options for the component you're passing them to:
* https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
* https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by cawoodm** [comment]
Thanks brandond. Could you comment on the correct usage of `--cluster-init`? It sounds like something you run once on one node but I wasn't sure. The docs seem to assume an existing cluster which is then "converted" to embedded etcd by running with that param. Just wasn't sure how an initial install on multiple nodes would happen. In the meantime we've given up on HA embedded etcd. It was too fragile - constantly bombing out when etcd wasn't happy.
