### ISSUE TITLE
dynamiclistener cert is not reliably written back to the Kubernetes datastore

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5591]
As discussed at https://github.com/rancher/rancher/pull/36932#issuecomment-1123558636 the dynamiclistener cert is not written back to Kubernetes when updated before the core controllers are available. We should update Dynamiclistener to v0.3.3 to ensure that the certificate is consistent across all members in the cluster.

**Comment by rancher-max** [comment]
Validated both general functionality of k3s and upgrade. Networking checks continue to work. Used master branch commit `1ef34728c99ba8831bb22b34acd18211df7f7155`
