### ISSUE TITLE
Provide a way to install curated multi-arch add-ons

### ISSUE THREAD

**Issue by erikwilson** [k3s-io/k3s#560]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it is hard to install basic kubernetes add-ons, especially on non-amd64 architectures.

**Describe the solution you'd like**
k3s should provide a small curated set of add-ons with good multi-arch support.

**Describe alternatives you've considered**
Modifying lots of default yaml configurations and researching available images or building new ones for my desired architecture.

**Additional context**
Many of the projects that are desirable to use do not provide multi-arch images. While it is impossible to provide multi-arch support for every project we should select a limited set of useful projects where we can select an appropriate image. 

Which projects should be supported as add-ons?
What is the best way to maintain add-ons so they stay up to date?

### Proposal:
Standard yaml containing some minimal package/add-on information:
- name: string
- image: string w/ pattern to insert arch
- archs: string map w/ arch translations if different than default
- conflicts: string array of conflicting packages
- provides: string array of aliases / generic names
- requires: string array of other packages to install / enable

#### commands:
- kpkg enable/disable [pkg:string]
- kpkg list
- kpkg search [pkg:string]
- kpkg repo add/remove [name:string] [url:string]
- kpkg info [pkg:string]
- kpkg update
- kpkg upgrade [pkg:string]

#### other:
- git repo based?
- enabling/disabling k3s options (eg servicelb)?

**Comment by giminni** [comment]
@erikwilson BTW I made today to yaml files for dashboard-amd64 and dashboard-arm64. 
The difference was the nodeSelector in spec -> template -> spec pointing to amd64 and arm64.
Should I PR this into a specific directory?

**Comment by erikwilson** [comment]
Thanks @giminni! It would probably be most helpful if you would like to put in a PR for the README (we should verify the existence of arm images also), until we can come up with a common template or way to select the appropriate arch image & version. The dashboard is a little bit trickier because people will try to access it in different ways, some have reported that adding 'type: LoadBalancer' to the service configuration of the dashboard helped for accessibility.

**Comment by caroline-suse-rancher** [comment]
Closing due to age
