### ISSUE TITLE
[Release-1.23] - Allow configuring the EgressSelector mode

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5602]
Backport fix for Allow configuring the EgressSelector mode

* #5596

**Comment by rancher-max** [comment]
#### Validated using release-1.23 branch

- For rke2, confirmed metrics are functional and there are no errors using commit `a0e81e4a88665d55d4433773e3e9513ef0196d50`

- For k3s, confirmed the same using commit `615020eed9afa120efdace526ca3ba292f254f6b`

- Confirmed for both that the egress-selector-mode flag is present:
```
   --egress-selector-mode value                  (networking) One of 'agent', cluster', 'pod', 'disabled' (default: "pod")
```
- For both, the value of this flag is defaulted to "pod" unless calico is the CNI, in which case it is defaulted to "cluster"
