### ISSUE TITLE
Cannot get high-availability embedded etcd to work

### ISSUE THREAD

**Issue by chrisdmacrae** [k3s-io/k3s#5604]
**Environmental Info:**
K3s Version: 

k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 

Linux node-1 5.13.0-1018-oracle #22~20.04.1-Ubuntu SMP Wed Feb 16 09:28:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

AND

Linux toshiba 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers, 7 agents

**Describe the bug:**

Agents can connect fine, but no matter what type of fresh install is done, servers 2 and 3 fail to connect with:

```
ERRO[0042] CA cert validation failed: Get "https://127.0.0.1:6443/cacerts": x509: certificate signed by unknown authority 
```

I run the following commands, starting with server one:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
K3S_TOKEN=abc123 sudo k3s server --cluster-init --tls-san 9maclaren.cloud
```

Then on server 2:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
K3S_TOKEN=abc123 sudo k3s server --server https://9maclaren.cloud:6443
```

Then on server 3:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -

K3S_TOKEN=abc123 sudo k3s server --server https://9maclaren.cloud:6443
K3S_TOKEN=abc123 sudo k3s server --server https://9maclaren.cloud:6443
```

After doing so, any kubectl command will fail with:

```
Unable to connect to the server: x509: certificate signed by unknown authority
```

To fix, I must re-add the `.kube/config` from `/etc/rancher/k3s/k3s.yaml`. 

It appears trying to join the second and third node effects the certificate data...

**Steps To Reproduce:**

- Installed K3s:
  - Following commands above

**Expected behavior:**

x509 certs are signed correctly and read correctly, chain unbroken

**Actual behavior:**

Chain appears broken

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by chrisdmacrae** [comment]
I am happy to debug live if that is of any use, and/or provide access to the servers by request over secure communication.

**Comment by brandond** [comment]
I'm guessing you figured out that variables aren't passed though when running things with sudo?
