### ISSUE TITLE
Cannot get embedded etcd to work with multiple networks

### ISSUE THREAD

**Issue by chrisdmacrae** [k3s-io/k3s#5605]
**Environmental Info:**
K3s Version: 

```
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5
```

Node(s) CPU architecture, OS, and Version: 

Server 1:
```
Linux toshiba 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Server 2:
```
Linux node-1 5.13.0-1018-oracle #22~20.04.1-Ubuntu SMP Wed Feb 16 09:28:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Server 3:
```
Linux node-2 5.13.0-1018-oracle #22~20.04.1-Ubuntu SMP Wed Feb 16 09:28:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

3 serves, 7 agents

**Describe the bug:**

Getting a networking error when trying to connect a second and third server to first server:

```
E0524 00:49:25.965438 3891564 kubelet.go:2461] "Error getting node" err="node \"node2\" not found"
{"level":"warn","ts":"2022-05-24T00:49:26.044Z","caller":"etcdserver/cluster_util.go:79","msg":"failed to get cluster response","address":"https://192.168.0.88:2380/members","error":"Get \"https://192.168.0.88:2380/members\": dial tcp 192.168.0.88:2380: i/o timeout"}
{"level":"info","ts":"2022-05-24T00:49:26.045Z","caller":"embed/etcd.go:368","msg":"closing etcd server","name":"node-1-fd1ac7e1","data-dir":"/var/lib/rancher/k3s/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://10.0.0.39:2379"]}
{"level":"info","ts":"2022-05-24T00:49:26.045Z","caller":"embed/etcd.go:370","msg":"closed etcd server","name":"node-1-fd1ac7e1","data-dir":"/var/lib/rancher/k3s/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://10.0.0.39:2379"]}
FATA[0030] ETCD join failed: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs
```

It appears to be trying to access the nodes local IP `192.168.0.88` instead of the hostname or WAN IP.

**Steps To Reproduce:**

- Installed K3s: 
- Ran on server 1:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
 K3S_TOKEN=plm951rew sudo k3s server --cluster-init --tls-san 9maclaren.cloud  --advertise-address [[ WAN_IP ]] --node-external-ip [[ WAN_IP ]]
```
- Ran on server 2
```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
sudo k3s server --server https://9maclaren.cloud:6443 --token K101f9c46da245583f4cf9e7fae25e942ebe82909e95379544a7b197f7e5a677631::server:180f63bebc3f6110f4d5f7d5897e1a5c --node-name node2
```
- Ran on server 3
```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -
sudo k3s server --server https://9maclaren.cloud:6443 --token K101f9c46da245583f4cf9e7fae25e942ebe82909e95379544a7b197f7e5a677631::server:180f63bebc3f6110f4d5f7d5897e1a5c --node-name node2
```

**Expected behavior:**

It resolves and connects

**Actual behavior:**

It can't resolve and fails

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Are all three servers on the same network? Embedded etcd does expect that all servers are on the same LAN; etcd is not designed to be run over the internet.

**Comment by chrisdmacrae** [comment]
@brandond they are not! One is in oracle cloud and the others are on a home network.

In this case, what's my best option: SQLLite or PostGres?

**Comment by chrisdmacrae** [comment]
Also @brandond, I’d recommend updating the high availability with electd dock to highlight the same network in the first few paragraphs!

**Comment by brandond** [comment]
I would probably avoid splitting your servers across providers entire. Even with a SQL-backed cluster, the latency and throughput will be poor. Keep al your servers in one location, and add remote agents. Assuming you're using a CNI backend that is functional over the internet (wireguard, or an existing site to site VPN).

**Comment by chrisdmacrae** [comment]
@brandond that makes perfect sense, thank you!

**Comment by chrisdmacrae** [comment]
@brandond now I get:

```
FATA[0024] ETCD join failed: initial cluster stage-0f65f025=https://10.0.2.15:2380,stage-a9249197=https://10.0.2.15:2380 has duplicate url 
```

**Comment by brandond** [comment]
Do you have multiple nodes with the same private IP? That appears to be what etcd is complaining about...
