### ISSUE TITLE
Request support for PowerPC (ppc64le) CPU

### ISSUE THREAD

**Issue by crystalattice** [k3s-io/k3s#5608]
**Is your feature request related to a problem? Please describe.**

k3s is supposed to support IoT devices, but it appears that PowerPC-based devices are excluded. 

**Describe the solution you'd like**

Support for PowerPC-based (ppc64le) devices is desired.

**Describe alternatives you've considered**

Both minikube and kind support PowerPC but having a more lightweight solution would be desirable.

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
We do not currently have access to any PPC hardware on which to build or test K3s.

**Comment by crystalattice** [comment]
Understood.
