### ISSUE TITLE
Option to modify server endpoint in kubeconfig output

### ISSUE THREAD

**Issue by andyli** [k3s-io/k3s#5615]
**Is your feature request related to a problem? Please describe.**

I use a docker-compose file (based on the one in k3s source root) to start k3s for use with [VSCode remote container](https://code.visualstudio.com/docs/remote/containers). For the kubectl in the workspace container to work, I set `KUBECONFIG` to point to the auto generated kubeconfig.yaml file. I have to replece `server: https://127.0.0.1:6443` to `server: https://${MY_K3S_SERVER}:6443` manually.

**Describe the solution you'd like**

It would be great if I can set the endpoint as an env var for the k3s server service in my docker-compose file, such that the auto generated kubeconfig.yaml file will use the value instead of using `https://127.0.0.1:6443`.

e.g. `--write-kubeconfig-server value` (client) Write kubeconfig with this server endpoint [`$K3S_KUBECONFIG_SERVER`]
(default: `https://127.0.0.1:6443`)

**Comment by heyu1207** [comment]
Hi，I  want to ask for some help. Can you tell me how to autogenerate kubeconfig.yaml in k3s? I want to use client-go in my code to access the k3s cluster, but I find the k3s doesn't have the ~/.kube/config like k8s.

**Comment by andyli** [comment]
@heyu1207 Use `K3S_KUBECONFIG_OUTPUT`. Read its doc at https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#client-options
