### ISSUE TITLE
k3s agent not respecting K3S_RESOLV_CONF=""

### ISSUE THREAD

**Issue by PriyankPa** [k3s-io/k3s#5627]
**Environmental Info:**
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 

`uname -a`
Linux ip-172-xx-xx-xx.xx-xxxx-1.compute.internal xx.xx.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`cat /etc/os-release`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Cluster Configuration:

1 server, 1 agent
**Describe the bug:**

kubelet parameter `--resolv-conf`, if set to `""` should result in pod's `/etc/resolv.conf` being set to  use`kube-dns` service IP as the name server. As I understand the environment variable `K3S_RESOLV_CONF` can be set to `""` during agent installation to achieve this.
What is actually happening is it uses  agent host's `/etc/resolv.conf` as is inside the pod. So service name resolution fails in pod running on that agent.

**Steps To Reproduce:**

- Installed K3s master:
 k3s master server was installed without using any custom environment variables or arguments.
Just `sudo curl -sfL https://get.k3s.io | sh -`

- Agent was installed on another node by running the following command as root:
`curl -sfL https://get.k3s.io | K3S_URL=https://xx.xx.xx.xx:6443 K3S_TOKEN=K103.....123 K3S_RESOLV_CONF="" sh -`
 

**Expected behavior:**

`/etc/resolv.conf` should have kube-dns service's IP as the name server

> If a Pod's dnsPolicy is set to default, it inherits the name resolution configuration from the node that the Pod runs on. The Pod's DNS resolution should behave the same as the node. But see [Known issues](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues).
> 
> If you don't want this, or if you want a different DNS config for pods, you can use the kubelet's --resolv-conf flag. Set this flag to "" to prevent Pods from inheriting DNS. Set it to a valid file path to specify a file other than /etc/resolv.conf for DNS inheritance.

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

**Actual behavior:**

`/etc/resolv.conf` in pod is identical to `/etc/resolv.conf` of host, which obviously does not contain kube-dns IP.  So service name resolution fails in pod running on agent. Some pods running on server/master, for example, grafana installed using official helm chart, can resolve Kubernetes service names properly that pod does have kude-dns IP entry in pod's `etc/resolve.conf`

**Additional context / logs:**

`cat /etc/systemd/system/k3s-agent.service.env`
K3S_RESOLV_CONF=""
K3S_TOKEN="K103...redacted..123"
K3S_URL="https://172.xx.xx.72:6443"

**Backporting**

Not sure

**Comment by brandond** [comment]
There is some additional logic around the k3s --resolv-conf / K3S_RESOLV_CONF setting. It will only be used if set to a valid resolv.conf file. If you want to directly set the kubelet resolv-conf flag without any additional processing, do so directly: `--kubelet-arg=resolv-conf=`

**Comment by PriyankPa** [comment]
After a bit more exploration I found that many pods on the agent do not have their `/etc/resolve.conf` pointing to kube-dns. I checked the `dnsPolicy `in pod spec by requesting an edit and it said `ClusterFirst`. As per my understanding if `dnsPolicy `is `ClusterFirst `then the pod should be capable of resolving service names. But since` /etc/resolve.conf `do not have right entries, these pods can't do that.

Examples of problematic pods: 
`prometheus-node-exporter` running on agent node (prometheus installed from official helm chart without customization, in its own namespace)
`longhorn-csi-plugin` running on agent node (longhorn installed on master node before adding agent)
`longhorn-csi-plugin` is stuck in `CrashLoopBackOff `as it can't resolve longhorn-backend service.

There is a networking problem as well. which I will investigate separately but to give you a gist - even if I skip past the DNS resolution and just try to curl the cluster IP of a service (whose pods are on master) from a pod running on agent, the the request times out. Connection does not happen. This is a separate problem. I will bump into it after the DNS problem is resolved.

**Comment by PriyankPa** [comment]
Thanks, my DNS issue is resolved. I reinstalled the agent via script with the `kubelet-arg=resolv-conf=` argument. 
The pods on agent are now automatically getting kube-dns; except prometheus-exporter pod which has `hostNetwork: true` in its manifest, hence that's expected. 

The networking issue still remains. I'll probably raise it in a separate issue.

**Comment by brandond** [comment]
I'm glad it worked for you, but I don't think I've ever seen that be necessary, so I'm curious what else is going on in your environment.

**Comment by PriyankPa** [comment]
I am not sure my self. I generally start with clean VM instances. But this time I have been given instances that seem to have been used for other tasks earlier. Plus my organization firewalls/access-controls everything to the hilt so could be any of those things. 

The DNS issue was actually a non issue. It was working as per spec. Kubernetes nodes should indeed default to host's DNS. I just find it a bad default. As it automatically means cluster DNS won't work. Strangely I did not have to do this on Tanzu. Probably Tanzu overrides upstream Kubernetes defaults for a more sensible one.

**Comment by PriyankPa** [comment]
The issue with networking is likely due to UDP being blocked between nodes. Is there a work around for this (without opening UDP)?

**Comment by brandond** [comment]
You could try switching to a different flannel backend, but no, VXLAN runs over UDP.
