### ISSUE TITLE
k3s autoscale

### ISSUE THREAD

**Issue by TheYkk** [k3s-io/k3s#563]
I cant autoscale deploys
`kubectl autoscale deployment hello-world --min=2 --max=5 --cpu-percent=50`
i use this command

```
➜ k3s -v
k3s version v0.6.1 (7ffe802a)
```
![image](https://user-images.githubusercontent.com/21688838/59902901-22712380-9408-11e9-99b2-df42d795069e.png)
![image](https://user-images.githubusercontent.com/21688838/59902941-3fa5f200-9408-11e9-8a85-931f9c283f01.png)

after load with hey!
![image](https://user-images.githubusercontent.com/21688838/59902994-6fed9080-9408-11e9-9fdf-5b620abf3eaf.png)

**Comment by lentzi90** [comment]
It looks like your deployment does not have a resource request. Autoscaling for pods is based on the resources they request so you must have this for the autoscaler to work.

For example, you could set the request to be 1000m CPU cores. When you create the autoscaler, you tell it `--cpu-percent=50`, so it should try to make enough pods to keep the usage at 50 % of the request (1000m in this example), so it will try to keep the usage at 500m.

Check [this](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#run-expose-php-apache-server) example. Note that they specify `--requests=cpu=200m` when they create the deployment. The algorithm details can be found [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) if you are interested.

**Comment by brandond** [comment]
Closing due to age.
