### ISSUE TITLE
servicelb violates baseline PodSecurity policy

### ISSUE THREAD

**Issue by ibuildthecloud** [k3s-io/k3s#5631]
**Environmental Info:**
K3s Version: 

k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Servicelb will violate the baseline PodSecurity policy.  You get an error like below

```
E0602 05:26:50.050690       6 daemon_controller.go:319] r-09590d3e/svclb-redis-publish-09590d3e-c10 failed with : pods "svclb-redis-publish-09590d3e-c10-h6z5m" is forbidden: violates PodSecurity "baseline:latest": non-default capabilities (container "lb-tcp-6379" must not include "NET_ADMIN" in securityContext.capabilities.add), hostPort (container "lb-tcp-6379" uses hostPort 6379)
```

**Steps To Reproduce:**

- Installed K3s: 

* Set the label on the `default` namespace     `pod-security.kubernetes.io/enforce: baseline`
* Create the below
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: "redis"
  type: LoadBalancer

```                                                                                                                                                              
**Expected behavior:**

The service should get an IP

**Actual behavior:**

Stuck pending with
```yaml
status:
  loadBalancer: {}

```

And errors from k8s like 
```
E0602 05:26:50.050690       6 daemon_controller.go:319] r-09590d3e/svclb-redis-publish-09590d3e-c10 failed with : pods "svclb-redis-publish-09590d3e-c10-h6z5m" is forbidden: violates PodSecurity "baseline:latest": non-default capabilities (container "lb-tcp-6379" must not include "NET_ADMIN" in securityContext.capabilities.add), hostPort (container "lb-tcp-6379" uses hostPort 6379)
```

This is obviously because the svclb containers use hostports which is not allowed.  I ran into a similar issue with a different component I was writing and I believe the proper workaround is that all svclb container should be created in a system namespace that will not have the profile assigned.

**Comment by manuelbuil** [comment]
Agree with the solution. We should try to fix/document this before v1.25 is released because users will probably start using these policies. AFAIK, v1.25 is the first release without the deprecated psp mechanism and its replacement is the Pod Security Standards which allows to define policies per namespace

**Comment by ibuildthecloud** [comment]
I'll gladly fix this right now.  We can argue about namespace name but one design point is do we just move all lb pods to that namespace or only do it if we detect pod-security annotation.  I prefer the former (less code, variability) but the impact is that if we do that on upgrade of k3s the user will have downtime on all servicelbs because the klipper pods will move.

**Comment by brandond** [comment]
yeah, maybe `klipper-lb-system`? As long as it's something unique to servicelb/klipper-lb, there will be less argument about whether or not it's correct for the servicelb controller to be managing the security config for the NS.

**Comment by ibuildthecloud** [comment]
Previously k3s created no new namespaces, now it will. Maybe we should default to kube-system and then make it a configuration to pick a different namespace?

**Comment by brandond** [comment]
Yeah, I guess I'm a little concerned about it preventing us from hardening the kube-system namespace where the rest of the components live, if we want to do so, but perhaps that's not an actual problem?

**Comment by ibuildthecloud** [comment]
I updated my PR to now have a --servicelb-namespace argument which defaults to kube-system.  If you change that value, enable, disable, upgrade, downgrade the pods will all move where they are supposed to be.

**Comment by VestigeJ** [comment]
**Environment Details-**
 
*Node(s) CPU architecture, OS, and Version:*

Linux 5.4.0-1009-aws x86_64 GNU/Linux-Ubuntu 20.04 LTS

*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1               Ready    control-plane,etcd,master   7m13s   v1.23.6+k3s1
ip-2               Ready    control-plane,etcd,master   8m55s   v1.23.6+k3s1
ip-3               Ready    control-plane,etcd,master   7m35s   v1.23.6+k3s1 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
```

**Reproduced with-**
 
** k3s Version/Commit:**

VERSION=v1.23.6+k3s1 

**Steps To Reproduce:**
 
```
   $  VERSION=v1.23.6+k3s1
   $  sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC="server --cluster-init --secrets-encryption sh -s" ./install-k3s.sh
   $  k label namespace default pod-security.kubernetes.io/enforce=baseline
   $  k apply -f tot
   $  kg svc -n default
   $  sudo journalctl -xeu k3s
```

**Results:**
```
kg svc -n default
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP          7m46s
redis        LoadBalancer   10.13.13.3   <pending>     6379:31866/TCP   4m33s
```

**Validated with COMMIT=2968a83bc046f43be62852b94d07c531de97c416**
 
** k3s Version/Commit:**
 v1.24.1+k3s-2968a83b
**Steps To Validate:**
 
- Installed k3s:
```
$ COMMIT=2968a83bc046f43be62852b94d07c531de97c416
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC="server --cluster-init --secrets-encryption sh -s" ./install-k3s.sh
$  k label namespace default pod-security.kubernetes.io/enforce=baseline
$  k apply -f tot
$  kg svc -n default
```
 
**Results:**
```
$ kg svc -n default
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP                                PORT(S)          AGE
kubernetes   ClusterIP      10.43.0.1      <none>                                     443/TCP          15m
redis        LoadBalancer   10.43.116.93   12.3.8.6,12.3.2.7,12.3.2.15   6379:31866/TCP   11m
```
**Additional context / logs:**
$ cat tot
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: "redis"
  type: LoadBalancer
```

Errors from journalctl 
```
.342508   16291 daemon_controller.go:1013] pods "svclb-redis-fn7lg" is forbidden: violates PodSecurity "baseline:la>
.342550   16291 daemon_controller.go:319] default/svclb-redis failed with : pods "svclb-redis-fn7lg" is forbidden: >
.342872   16291 event.go:294] "Event occurred" object="default/svclb-redis" kind="DaemonSet" apiVersion="apps/v1" t>
```
