### ISSUE TITLE
Configmap is not updated after pod restart

### ISSUE THREAD

**Issue by M-Gregoire** [k3s-io/k3s#5632]
**Environmental Info:**
K3s Version: 
```
k3s version v1.22.3+k3s1 (61a2aab2)
go version go1.16.13
```

Node(s) CPU architecture, OS, and Version: 
```
Linux 5.17.11 #1-NixOS SMP PREEMPT Wed May 25 12:43:10 UTC 2022 x86_64 GNU/Linux
```

Cluster Configuration:
`Single node server`

**Describe the bug:**
I have the following configmap:
```
apiVersion: v1
kind: ConfigMap

metadata:
  name: my-cm
data:
  some-file: |
    my content is here !
```

Which is used inside a deployment, within the container:
```
            - name: my-vol
              mountPath: /my/path
              subPath: some-file
              readOnly: false
```
With the volume declared with:
```
        - name: my-vol
          configMap:
            name: my-cm

```

The file is created, as intended, at `/my/path`. However, any change made to the configmap is not reflected inside the container.

The [documentation](https://kubernetes.io/docs/concepts/configuration/configmap/) states: 
> Note: A container using a ConfigMap as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes#using-subpath) volume mount will not receive ConfigMap updates.

However, even after deleting the deployment and the configmap, and recreating them, the old configmap is still in use. I've setup [Reloader](https://github.com/stakater/Reloader) to make sure the pod is correctly restarted with the same result.

The problem seems also to exist when using the configmap as a list of environment variables:
```
          envFrom:
            - configMapRef:
                name: my-env-cm
```

`kubectl describe cm my-cm -n my-namespace` returns the up-to-date configmap, but even after deleting the pod or recreating the deployment, the old values are in use.

What leads me to believe this might be a bug, is that removing the deployment, restarting k3s (`systemctl restart k3s`) then recreating the deployment fixes this issue.

Am I missing something or is this a bug?

Thank you for any help you might provide.

**Comment by brandond** [comment]
I'm not aware of any k3s-specific issues with regards to configmap volumes. You're saying that you see the old configmap values even in new pods?

**Comment by M-Gregoire** [comment]
Yes, even though the configmap is deleted, and the pod restarted, the only values are still in use.

I can try to make a minimal working example if you wish.

**Comment by brandond** [comment]
If the configmap is deleted, I don't see how its values could continue to be available on a pod created afterwards. Is there perhaps some default file content present in the image that you're seeing instead when the configmap isn't mounted?

**Comment by M-Gregoire** [comment]
Sorry for my slow reply. I was unable to reproduce my issue, I suspect I just made a typo in the configuration map when recreating it, leading to the creation of a new one instead during my testing.

Closing this issue.
