### ISSUE TITLE
Allow changing the flannel cni config

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#5655]
**Is your feature request related to a problem? Please describe.**

Flannel CNI conf is currently hardcoded in the code and impossible to modify: https://github.com/k3s-io/k3s/blob/master/pkg/agent/flannel/setup.go#L28-L47

Users might want to modify it, for example to use extra CNI plugins on top of flannel, but currently is it impossible to do it.

**Describe the solution you'd like**

A config flag that allows providing your own flannel CNI conf and gets prioritized over the hardcoded one

**Describe alternatives you've considered**

Deploy k3s and then replace the config. However, this is not good because in reboots, upgrades, etc it will be overwritten

**Additional context**

There are already users that have asked for this, especially to use the bandwidth CNI plugin

**Backporting**

- [X] Needs backporting to older releases

**Comment by manuelbuil** [comment]
## How to test this ##

By default, you get a cniconfig when deploying k3s here: `/var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist`. Copy that config to another file and change it slightly, e.g. change the cni version `"cniVersion":"x.y.z", to 1.0.0 or 0.3.1 or 0.4.0. 

Use this flag to point to the newly created config (with the slight change) and deploy. The new config file content should be in `/var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist`

**Comment by mdrahman-suse** [comment]
## Environment Details >>
 
*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.4.0-1009-aws Ubuntu x86_64 GNU/Linux
"Ubuntu 20.04 LTS"
```
 
*Cluster Configuration:*
```
Single node
```
 
*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: clouds
flannel-cni-conf: "/home/ubuntu/10-flannel.conflist"
```
 
## Replication Steps:
 
- Create and copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
- Install K3S:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 sh -
```
 
**Results:**
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist
{
  "name":"cbr0",
  "cniVersion":"1.0.0",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```
 
## Validation Steps:
 
- Create and copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
- Install K3S:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=a5414bb1fc904e3d44a6a66ccffa819340e712a8 sh -
```
 
**Results:**
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist
{
  "name":"valp0",
  "cniVersion":"0.4.0",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```
 
**Additional context / logs:**

This file was saved on a local dir (can be saved anywhere to be referred on the config.yaml)

*10-flannel.conflist*
```
{
  "name":"valp0",
  "cniVersion":"0.4.0",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```

**Comment by mdrahman-suse** [comment]
### Validated in 1.24.2-rc1+k3s1
