### ISSUE TITLE
x509: certificate has expired or is not yet valid, client-ca.crt is not update

### ISSUE THREAD

**Issue by TonyZZhang** [k3s-io/k3s#5664]
**Environmental Info:**
K3s Version:  v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
only 1 server 

**Describe the bug:**

I want to test whether the certificate can be automatically updated，but I found that every certificate  except the **client-ca.crt** was updated.

**Steps To Reproduce:**

- Installed K3s: 
- find /var/lib/rancher/k3s/server/tls -type f -name "*.crt" -print|xargs -L 1 -t -i bash -c 'openssl x509 -noout -text -in {}|grep Not'
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-ca.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Jun  6 08:52:20 2032 GMT
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-admin.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Sep 19 16:00:17 2035 GMT
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-controller.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Sep 19 16:00:17 2035 GMT
- k3s kubectl --insecure-skip-tls-verify=true delete secret k3s-serving -n kube-system
- systemctl stop k3s
- rm -rf /var/lib/rancher/k3s/server/tls/dynamic-cert.json
- date -s 20340920
- systemctl start k3s
- find /var/lib/rancher/k3s/server/tls -type f -name "*.crt" -print|xargs -L 1 -t -i bash -c 'openssl x509 -noout -text -in {}|grep Not'
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-ca.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Jun  6 08:52:20 2032 GMT
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-admin.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Sep 19 16:00:09 2035 GMT
  bash -c openssl x509 -noout -text -in /var/lib/rancher/k3s/server/tls/client-controller.crt|grep Not 
              Not Before: Jun  9 08:52:20 2022 GMT
              Not After : Sep 19 16:00:09 2035 GMT
**Expected behavior:**

The client-ca.crt should be updated.
**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
CA certificates are not currently renewed when they expire. I believe there is at least one existing issue tracking this.

**Comment by TonyZZhang** [comment]
> CA certificates are not currently renewed when they expire, but they are valid for 10 years unlike the 1 year validity on the leaf certificates. I believe there is at least one existing issue tracking this.

Thanks for your reply, and could you tell me how to solve the problem when the certificate expires.
