### ISSUE TITLE
[root@localhost .kube]# kubectl get pod -A Error from server: converting (v1.Endpoints) to (core.Pod): unknown conversion

### ISSUE THREAD

**Issue by sharkat** [k3s-io/k3s#5665]
[root@localhost .kube]# kubectl get pod -A
Error from server: converting (v1.Endpoints) to (core.Pod): unknown conversion

6月 10 16:52:50 localhost.localdomain k3s[1947320]: E0610 16:52:50.786200 1947320 shared_informer.go:243] unable to sync caches for resource quota
6月 10 16:52:50 localhost.localdomain k3s[1947320]: E0610 16:52:50.786219 1947320 resource_quota_controller.go:448] timed out waiting for quota monitor sync
6月 10 16:52:51 localhost.localdomain k3s[1947320]: E0610 16:52:51.378775 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:52 localhost.localdomain k3s[1947320]: E0610 16:52:52.515382 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:53 localhost.localdomain k3s[1947320]: E0610 16:52:53.644629 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:54 localhost.localdomain k3s[1947320]: E0610 16:52:54.775530 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:55 localhost.localdomain k3s[1947320]: E0610 16:52:55.909168 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:57 localhost.localdomain k3s[1947320]: E0610 16:52:57.039400 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:58 localhost.localdomain k3s[1947320]: E0610 16:52:58.172227 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:52:59 localhost.localdomain k3s[1947320]: E0610 16:52:59.300703 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:00 localhost.localdomain k3s[1947320]: E0610 16:53:00.431695 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:01 localhost.localdomain k3s[1947320]: E0610 16:53:01.565557 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:02 localhost.localdomain k3s[1947320]: E0610 16:53:02.699443 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:03 localhost.localdomain k3s[1947320]: E0610 16:53:03.830018 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:04 localhost.localdomain k3s[1947320]: E0610 16:53:04.594529 1947320 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"converting (v1.Endpoints) to (core.Pod): unknown conversion"}
6月 10 16:53:04 localhost.localdomain k3s[1947320]: E0610 16:53:04.595391 1947320 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Pod: failed to list *v1.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion
6月 10 16:53:04 localhost.localdomain k3s[1947320]: E0610 16:53:04.961978 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:06 localhost.localdomain k3s[1947320]: E0610 16:53:06.091773 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:07 localhost.localdomain k3s[1947320]: E0610 16:53:07.221641 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:08 localhost.localdomain k3s[1947320]: E0610 16:53:08.354053 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:09 localhost.localdomain k3s[1947320]: E0610 16:53:09.485010 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:10 localhost.localdomain k3s[1947320]: E0610 16:53:10.170240 1947320 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"converting (v1.Endpoints) to (core.Pod): unknown conversion"}
6月 10 16:53:10 localhost.localdomain k3s[1947320]: E0610 16:53:10.170957 1947320 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:67: Failed to watch *v1.Pod: failed to list *v1.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion
6月 10 16:53:10 localhost.localdomain k3s[1947320]: E0610 16:53:10.614011 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:11 localhost.localdomain k3s[1947320]: E0610 16:53:11.747129 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:12 localhost.localdomain k3s[1947320]: E0610 16:53:12.879624 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:14 localhost.localdomain k3s[1947320]: E0610 16:53:14.010377 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:15 localhost.localdomain k3s[1947320]: E0610 16:53:15.138928 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:16 localhost.localdomain k3s[1947320]: E0610 16:53:16.268852 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:16 localhost.localdomain k3s[1947320]: E0610 16:53:16.413396 1947320 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"converting (v1.Endpoints) to (core.Pod): unknown conversion"}
6月 10 16:53:16 localhost.localdomain k3s[1947320]: E0610 16:53:16.414267 1947320 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Pod: failed to list *v1.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion
6月 10 16:53:16 localhost.localdomain k3s[1947320]: E0610 16:53:16.950366 1947320 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"converting (v1.Endpoints) to (core.Pod): unknown conversion"}
6月 10 16:53:16 localhost.localdomain k3s[1947320]: E0610 16:53:16.951340 1947320 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Pod: failed to list *v1.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion
6月 10 16:53:17 localhost.localdomain k3s[1947320]: E0610 16:53:17.398456 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:18 localhost.localdomain k3s[1947320]: E0610 16:53:18.530978 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
6月 10 16:53:19 localhost.localdomain k3s[1947320]: E0610 16:53:19.664854 1947320 cacher.go:419] cacher (*core.Pod): unexpected ListAndWatch error: failed to list *core.Pod: converting (v1.Endpoints) to (core.Pod): unknown conversion; reinitializing...
lines 142176-142244/142244 (END)

**Comment by sharkat** [comment]
求助

**Comment by brandond** [comment]
What version of k3s are you using? How did you manage to get endpoints back in response to a pod list query?

**Comment by sharkat** [comment]
> What version of k3s are you using? How did you manage to get endpoints back in response to a pod list query?

K3S_VERSION=v1.20.11+k3s2

**Comment by sharkat** [comment]
> What version of k3s are you using? How did you manage to get endpoints back in response to a pod list query?

kubectl get  pod -A or kubectl get  pod --all-namespaces

**Comment by brandond** [comment]
I have no idea how that would happen, and certainly can't reproduce it. Was there something that happened to your cluster to precipitate this issue?

**Comment by sharkat** [comment]
> 

[root@localhost ~]# kubectl version -o yaml
clientVersion:
  buildDate: "2021-10-05T19:21:09Z"
  compiler: gc
  gitCommit: 9cb5fb5716bdfb13e755206aff5688961f5bafb3
  gitTreeState: clean
  gitVersion: v1.20.11+k3s2
  goVersion: go1.15.14
  major: "1"
  minor: "20"
  platform: linux/arm64
serverVersion:
  buildDate: "2021-10-05T19:21:09Z"
  compiler: gc
  gitCommit: 9cb5fb5716bdfb13e755206aff5688961f5bafb3
  gitTreeState: clean
  gitVersion: v1.20.11+k3s2
  goVersion: go1.15.14
  major: "1"
  minor: "20"
  platform: linux/arm64

[root@localhost ~]#

**Comment by sharkat** [comment]
> 我不知道那会如何发生，当然也无法重现它。您的集群是否发生了什么事情导致了这个问题？
> 
> 的输出是`kubectl version -o yaml`什么？

这个是接的别人的工作，集群应该是进行了迁移导致的。

**Comment by brandond** [comment]
I have no idea what might cause you to get endpoints back in response to a request for pods. If simply restarting all of the servers does not resolve the issue, I would try upgrading to a newer release. The 1.20 branch is end of support.

**Comment by sharkat** [comment]
> 我不知道是什么可能导致您返回端点以响应对 pod 的请求。如果简单地重新启动所有服务器并不能解决问题，我会尝试升级到更新的版本。1.20 分支是支撑结束。

好的谢谢
