### ISSUE TITLE
Missing upgrade images of k3s version 1.23.7

### ISSUE THREAD

**Issue by timbrd** [k3s-io/k3s#5670]
Hello,

there are no upgrade images of release 1.23.7: https://hub.docker.com/r/rancher/k3s-upgrade/tags?page=1&name=1.23.7
Are they still being build?

Thanks

**Comment by timbrd** [comment]
The image is now available

**Comment by brandond** [comment]
There were some failures in the CI pipeline; a re-run appears to have succeeded.
