### ISSUE TITLE
The coredns of k3s always resolves abnormally and can only be recovered by kubectl rollout restart deployment coredns

### ISSUE THREAD

**Issue by MagicStarTrace** [k3s-io/k3s#5671]
OS Version:  Centos 7
k3s -version:
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

![image](https://user-images.githubusercontent.com/15685376/173267309-02015e41-c976-4aaa-a2ae-48fa190c594e.png)

kubectl  logs cattle-cluster-agent-54f7b64565-v4zlq -n  cattle-system
INFO: Environment: CATTLE_ADDRESS=10.42.2.84 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_CLUSTER_REGISTRY= CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-54f7b64565-v4zlq CATTLE_SERVER=https://rancehr.test.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://rancehr.test.com/ping is not accessible (Could not resolve host: rancehr.test.com)

Why pod resolution in kube-system namespace fails, but pods in other namespaces can be resolved normally?

Thank You!

**Comment by brandond** [comment]
Those warnings are not errors; it's hard to tell what's going on from just a screenshot. Can you attach the complete coredns pod logs, when it is not working?

You might also consider upgrading K3s; the version you're on is almost 8 months old; 1.21 is about to go end of support. You could at the very least upgrade to v1.21.13+k3s1 for a newer version of coredns.

**Comment by MagicStarTrace** [comment]
> Those warnings are not errors; it's hard to tell what's going on from just a screenshot. Can you attach the complete coredns pod logs, when it is not working?
> 
> You might also consider upgrading K3s; the version you're on is almost 8 months old; 1.21 is about to go end of support. You could at the very least upgrade to v1.21.13+k3s1 for a newer version of coredns.

Can  directly upgrade the Coredns service?

**Comment by brandond** [comment]
Can you test with dig or nslookup instead of ping? What is the upstream DNS server on your nodes? There not really enough info here to tell why things aren't resolving from within pods

**Comment by MagicStarTrace** [comment]
> Can you test with dig or nslookup instead of ping? What is the upstream DNS server on your nodes? Therse not really enough info here to tell why things aren't resolving from within pods. Start with DNS tools and work your way up the chain.

Figure 1 shows that the pod under the self-built ns can be parsed normally:

![image](https://user-images.githubusercontent.com/15685376/173762523-3b86c3ee-a2e1-413e-9cc8-7e0203b9ed85.png)

Figure 2 is the pod under kube-system, which cannot be parsed normally
![image](https://user-images.githubusercontent.com/15685376/173764323-53a13d7c-b15a-471c-bfe9-972b851035e0.png)

All are configured to use coredns (10.43.0.10)
Why is this so? what do I do 
Thank You!

**Comment by MagicStarTrace** [comment]
> Looks like it can't reach the coredns pod, or coredns can't reach the upstream server. How many nodes are in this cluster? Is coredns running on the same node as your test container? Are you sure that all of the correct ports for your CNI backend are open between nodes?

3 nodes, coredns and the test container of Figure 2 on one node

Currently I have this problem when tests and coredns are run on the same node.

I am now running coredns on the master node. Temporarily solved 

Why is this happening?

**Comment by brandond** [comment]
> Currently I have this problem when tests and coredns are run on the same node.

Can you confirm that ufw/firewalld or any other iptables based firewall are disabled?

**Comment by MagicStarTrace** [comment]
> > Currently I have this problem when tests and coredns are run on the same node.
> 
> Can you confirm that ufw/firewalld or any other iptables based firewall are disabled?

 cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--docker' \
	'--disable=metrics-server' \
	'--disable=coredns' \
	'--disable-selinux' \
        '--service-node-port-range=1-65535' \
	'--node-external-ip=192.168.100.20' \
	'--write-kubeconfig' \
	'/root/.kube/config' \

It seems that iptables cannot be completely disabled, although some functions of iptables are replaced by ipvs (some components still rely on iptables)

**Comment by brandond** [comment]
Any reason in particular you're using --docker? That is not supported as of 1.24; it's possible that switching to containers and uninstalling Docker may alleviate your problem.

**Comment by MagicStarTrace** [comment]
> Any reason in particular you're using --docker? That is not supported as of 1.24; it's possible that switching to containerd and uninstalling Docker may alleviate your problem.

Too many pits, although the runtime overhead is reduced
