### ISSUE TITLE
Zombie process overflow when pods  don't reap exec probe processes

### ISSUE THREAD

**Issue by thejan2009** [k3s-io/k3s#5675]
**Environmental Info:**
K3s Version: 
v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 
ubuntu 20.04

Cluster Configuration:
single-node installation - 1 server, 1 agent

**Describe the bug:**
Some pod processes don't reap `exec` {liveness, readiness, startup}Probe child processes, resulting in zombie processes, which eventually overloads the server.

**Steps To Reproduce:**
See https://github.com/Enapter/charts/issues/50. The chart in question has two `exec` probes. To reproduce, deploy the chart and observe the pod's child processes.

**Expected behavior:**
Pod process or init reaps exec probe child processes.

**Actual behavior:**
Doesn't do that.

**Additional context / logs:**
I was also able to reproduce the same issue on `k3d`, deployed a chart with `exec` probe and ran `while true; do docker exec -it k3d-server-0 ps -eo ppid,comm |  wc -l; sleep 5; done`. The number of processes was continuously increasing.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
I believe that what you're describing is covered by upstream issues - which is to say this is not a problem with k3s.
* https://github.com/kubernetes/kubernetes/issues/81042
* https://github.com/kubernetes/kubernetes/issues/84210
