### ISSUE TITLE
[Release 1.23] Remove kube-ipvs0 interface when cleaning up

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#5676]
Backport: https://github.com/k3s-io/k3s/issues/5643

**Comment by est-suse** [comment]
*Node(s) CPU architecture, OS, and Version:*
Ubuntu LTS, 20gb Hard drive
 
*Cluster Configuration:*
1 node
 
*Config.yaml:*
write-kubeconfig-mode: 644
kube-proxy-arg: "proxy-mode=ipvs"
 
**Reproduced with-**
 
**K3S Version/Commit:**
 
**Steps To Reproduce:**
 
- Installed K3S:
curl -sfl https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 sh -
 
**Results:**
```
```
 
**Validated with-**
 ip a, is the command to show the interface
**K3S Version/Commit:**
 v1.23.7+k3s1 

**Steps To Validate:**
Create the config.yaml as follow:

write-kubeconfig-mode: 644
kube-proxy-arg: "proxy-mode=ipvs"
 


- Installed K3S:
curl -sfl https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 sh -
 
**Results:**
ip a, to validate:

The ipvs0 will be shown as follow:

![image](https://user-images.githubusercontent.com/106194120/173934452-4b78a5dc-0105-4526-a278-8226e612f597.png)

After uninstalling k3s with the script: k3s-uninstall.sh, no results for ipvs0 are displayed:

ip a, to validate:

![image](https://user-images.githubusercontent.com/106194120/173934762-50824441-a05f-4c49-85e1-88e598560baa.png)

 

**Additional context / logs:**
