### ISSUE TITLE
Disable urfave markdown/man docs generation

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5697]
urfave/cli includes functions to generate markdown/man docs from CLI help. Unfortunately these pull in a couple other libraries, even if not used. Recent versions of this library allow use of a build flag to disable this functionality, and save a few 100 kbytes from the resulting binary.

**Comment by mdrahman-suse** [comment]
### Validated on master with commit 61b714b2dd2b70535bca1089cb160bbb6b886226
 
## Environment Details

 
*Infrastructure*
- [x] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux  5.4.0-1009-aws #9-Ubuntu x86_64 GNU/Linux
"Ubuntu 20.04 LTS"
```
 
*Cluster Configuration:*

```
Single node
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summerheat
debug: true
```
 
## Replication Steps

- Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
 
- Install K3S:

```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.1+k3s1 sh -
```
- Check size of k3s binary using `ls -la /usr/local/bin/k3s`
 
**Results:**

```
$ sudo ls -la /usr/local/bin/k3s
-rwxr-xr-x 1 root root 66269184 Jun 22 21:53 /usr/local/bin/k3s
$ sudo ls -lah /usr/local/bin/k3s
-rwxr-xr-x 1 root root 64M Jun 22 21:53 /usr/local/bin/k3s
```
 
## Validation Steps

- Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
- Install K3S:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=61b714b2dd2b70535bca1089cb160bbb6b886226 sh -
```
- Check size of k3s binary using `ls -la /usr/local/bin/k3s`

**Results:**

- The size of binary has reduced to ~1MB
```
$ sudo ls -lar /usr/local/bin/k3s
-rwxr-xr-x 1 root root 65622016 Jun 22 21:43 /usr/local/bin/k3s
$ sudo ls -lah /usr/local/bin/k3s
-rwxr-xr-x 1 root root 63M Jun 22 21:43 /usr/local/bin/k3s
```

**Comment by mdrahman-suse** [comment]
### Validated in 1.24.2-rc1+k3s1
