### ISSUE TITLE
K3s using 300% CPU of mariadb, 70k+ "joins without indexes" in 42 days

### ISSUE THREAD

**Issue by oskapt** [k3s-io/k3s#5713]
**Environmental Info:**
K3s Version: v1.21.11+k3s1

Node(s) CPU architecture, OS, and Version: 

`Linux k02 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

2 servers, 3 agents, mariadb running on external system w/ 4 CPUs and 32GB of RAM, 18GB allocated to mariadb

**Describe the bug:**

Periodically kubectl reports Connection Refused when connecting to either of the 2 server nodes. When this happens it will work again a few seconds later and then report Connection Refused again. Kube-VIP is always restarting, so I can't use that address reliably at all. This happenes every couple of weeks, and I have to restart k3s on the server nodes to get it to stabilize with kubectl requests; otherwise, kubectl fails about 3 out of every 10 requests. The server logs show non-stop debug/traces from slow communication with the API. 

The db node is showing steady 300% CPU usage for mariadb, with queries in the process list showing that they use anywhere from 15-50% of the CPU when running. Analysis of the db server reports that since rebooting the db node 42 days ago there have been >70k queries that are performing "joins without indexes," which means full table scans. There have been more than 600 of them in the last hour. The table was fragmented and > 800MB in size. I optimized it and got it down to 50MB, but the CPU usage is still abysmal. 

Today is the first time that I've looked at the db node while kubectl was reporting that the API server was coming and going. I restarted K3s on both server nodes, and after about 15 minutes, CPU usage on the database dropped to normal, with occasional spikes to 150% or higher for a few seconds. It stayed this way for about 15 minutes and then went back to 300%. Now it seems to be cycling back and forth every few minutes. The slow query log reports lots of queries without indexes, but I don't see a pattern with a particular query. I grabbed a random one and ran it myself, and it takes more than 4 seconds to complete. That seems like an eternity.

These server nodes were built over a year ago and have been upgraded in place. I can't go to anything higher than 1.21 because of a limitation in the iSCSI storage class that I'm using, which doesn't have an update for >= 1.22 yet. I've confirmed that the indexes on the table are the same as in the current mysql.go driver in the master branch.

I've attached the slow query log. Can you see anything that needs an additional index? My kine table has 230k rows in it, but I don't know if that's a lot or not. I trust MariaDB when it reports that there are full table scans happening from joins without indexes, but maybe the query doesn't expect to have to scan 200k rows to find what it's looking for. If that's the case, maybe compaction broke somewhere along the way?

[mariadb-slow.log](https://github.com/k3s-io/k3s/files/8905467/mariadb-slow.log)

**Comment by oskapt** [comment]
Here are some sample traces, all showing queries taking > 6s to complete:
```
Jun 15 03:40:39 k02 k3s[3586769]: I0615 03:40:39.199712 3586769 trace.go:205] Trace[2008387359]: "Update" url:/api/v1/namespaces/kube-system/configmaps/cert-manager-cainjector-leader-election,user-agent:cainjector/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election,client:10.68.0.67,accept:application/json, */*,protocol:HTTP/1.1 (15-Jun-2022 03:40:38.064) (total time: 1134ms):
Jun 15 03:40:39 k02 k3s[3586769]: Trace[2008387359]: ---"Object stored in database" 1134ms (03:40:39.199)
Jun 15 03:40:39 k02 k3s[3586769]: Trace[2008387359]: [1.134753381s] [1.134753381s] END
Jun 15 03:40:39 k02 k3s[3586769]: I0615 03:40:39.199748 3586769 trace.go:205] Trace[1238617453]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cert-manager-controller,user-agent:controller/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election,client:10.68.0.66,accept:application/json, */*,protocol:HTTP/1.1 (15-Jun-2022 03:40:38.314) (total time: 884ms):
Jun 15 03:40:39 k02 k3s[3586769]: Trace[1238617453]: ---"Object stored in database" 884ms (03:40:39.199)
Jun 15 03:40:39 k02 k3s[3586769]: Trace[1238617453]: [884.94083ms] [884.94083ms] END
Jun 15 03:40:41 k02 k3s[3586769]: I0615 03:40:41.980282 3586769 trace.go:205] Trace[831825611]: "List etcd3" key:/events,resourceVersion:,resourceVersionMatch:,limit:500,continue:eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6MzAyMjI3NzM4LCJzdGFydCI6Imt1YmUtc3lzdGVtL2t1YmUtdmlwLWRzLTZibDhqLjE2ZjNiZjBiZjhjMzUyZmNcdTAwMDAifQ (15-Jun-2022 03:40:35.389) (total time: 6590ms):
Jun 15 03:40:41 k02 k3s[3586769]: Trace[831825611]: [6.590422099s] [6.590422099s] END
Jun 15 03:40:41 k02 k3s[3586769]: I0615 03:40:41.983781 3586769 trace.go:205] Trace[652410864]: "List" url:/apis/events.k8s.io/v1/events,user-agent:k3s/v1.21.11+k3s1 (linux/amd64) kubernetes/4eb3a48/shared-informers,client:127.0.0.1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (15-Jun-2022 03:40:35.389) (total time: 6593ms):
Jun 15 03:40:41 k02 k3s[3586769]: Trace[652410864]: ---"Listing from storage done" 6591ms (03:40:41.980)
Jun 15 03:40:41 k02 k3s[3586769]: Trace[652410864]: [6.593960585s] [6.593960585s] END
Jun 15 03:40:48 k02 k3s[3586769]: I0615 03:40:48.430591 3586769 trace.go:205] Trace[1605129254]: "List etcd3" key:/events,resourceVersion:,resourceVersionMatch:,limit:500,continue:eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6MzAyMjI3NzM4LCJzdGFydCI6ImRlZmF1bHQvazAyLjE2ZjNjMGUyNDEwYmQwOTZcdTAwMDAifQ (15-Jun-2022 03:40:41.986) (total time: 6444ms):
Jun 15 03:40:48 k02 k3s[3586769]: Trace[1605129254]: [6.444020692s] [6.444020692s] END
Jun 15 03:40:48 k02 k3s[3586769]: I0615 03:40:48.433952 3586769 trace.go:205] Trace[605340753]: "List" url:/apis/events.k8s.io/v1/events,user-agent:k3s/v1.21.11+k3s1 (linux/amd64) kubernetes/4eb3a48/shared-informers,client:127.0.0.1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (15-Jun-2022 03:40:41.986) (total time: 6447ms):
Jun 15 03:40:48 k02 k3s[3586769]: Trace[605340753]: ---"Listing from storage done" 6444ms (03:40:48.430)
```

**Comment by brandond** [comment]
That's not a particularly large cluster, I wouldn't expect it to be that hard on the database server unless you have a workload that is unusually hard on the apiserver.

Is the mariadb server a single node, or is there multi-master replication in place?

Are you able to run a couple ad-hoc queries against the database?
```sql
SELECT 
  COUNT(*) AS `rows`, 
  (SELECT prev_revision FROM kine WHERE name = "compact_rev_key" LIMIT 1) AS `compact_rev`,
  MAX(id) AS `current_rev`
FROM kine;

SELECT
  COUNT(*) AS `rows`,
  SUBSTRING_INDEX(name, "/", 3) AS `prefix`
FROM kine
GROUP BY SUBSTRING_INDEX(name, "/", 3)
ORDER BY `rows` DESC;
```

**Comment by oskapt** [comment]
```
+--------+-------------------------------------------+
| rows   | prefix                                    |
+--------+-------------------------------------------+
| 250722 | /registry/events                          |
|   4635 | /registry/leases                          |
|   1867 | /registry/configmaps                      |
|   1058 | /registry/kustomize.toolkit.fluxcd.io     |
|    617 | /registry/services                        |
|    339 | /registry/secrets                         |
|    231 | /registry/masterleases                    |
|    211 | /registry/cilium.io                       |
|    200 | /registry/replicasets                     |
|    173 | /registry/pods                            |
|    114 | /registry/clusterroles                    |
|    110 | /registry/endpointslices                  |
|    105 | /registry/serviceaccounts                 |
|    101 | /registry/apiregistration.k8s.io          |
|     92 | /registry/clusterrolebindings             |
|     83 | /registry/apiextensions.k8s.io            |
|     82 | /registry/traefik.containo.us             |
|     66 | /registry/kyverno.io                      |
|     64 | /registry/controllerrevisions             |
|     59 | /registry/deployments                     |
|     48 | /registry/cert-manager.io                 |
|     34 | /registry/source.toolkit.fluxcd.io        |
|     33 | /registry/bitnami.com                     |
|     33 | /registry/namespaces                      |
|     33 | /registry/rolebindings                    |
|     32 | /registry/acme.cert-manager.io            |
|     30 | /registry/roles                           |
|     29 | /registry/minions                         |
|     24 | /registry/helm.toolkit.fluxcd.io          |
|     23 | /registry/persistentvolumes               |
|     21 | /registry/daemonsets                      |
|     21 | /registry/persistentvolumeclaims          |
|     13 | /registry/k3s.cattle.io                   |
|     12 | /registry/flowschemas                     |
|     11 | /registry/jobs                            |
|      8 | /registry/prioritylevelconfigurations     |
|      8 | /registry/statefulsets                    |
|      8 | /registry/volumeattachments               |
|      6 | /registry/podsecuritypolicy               |
|      5 | /registry/csinodes                        |
|      4 | /registry/mutatingwebhookconfigurations   |
|      4 | /registry/validatingwebhookconfigurations |
|      2 | /registry/priorityclasses                 |
|      2 | /registry/ranges                          |
|      2 | /registry/storageclasses                  |
|      1 | /bootstrap/131d6a1905f4                   |
|      1 | /registry/cronjobs                        |
|      1 | /registry/csidrivers                      |
|      1 | /registry/health                          |
|      1 | /registry/ingress                         |
|      1 | /registry/snapshot.storage.k8s.io         |
|      1 | compact_rev_key                           |
|      1 | gap-303543129                             |
|      1 | gap-303543278                             |
|      1 | gap-303544829                             |
|      1 | gap-303544835                             |
|      1 | gap-303544837                             |
|      1 | gap-303544838                             |
|      1 | gap-303544840                             |
|      1 | gap-303544841                             |
|      1 | gap-303544843                             |
|      1 | gap-303544844                             |
|      1 | gap-303544849                             |
|      1 | gap-303544851                             |
|      1 | gap-303544852                             |
|      1 | gap-303544855                             |
|      1 | gap-303544856                             |
|      1 | gap-303544861                             |
|      1 | gap-303544862                             |
|      1 | gap-303544863                             |
|      1 | gap-303544864                             |
|      1 | gap-303544865                             |
|      1 | gap-303544876                             |
|      1 | gap-303544881                             |
|      1 | gap-303544882                             |
|      1 | gap-303547693                             |
|      1 | gap-303547694                             |
|      1 | gap-303547703                             |
|      1 | gap-303547704                             |
|      1 | gap-303547706                             |
|      1 | gap-303547707                             |
|      1 | gap-303547710                             |
|      1 | gap-303547711                             |
|      1 | gap-303547712                             |
|      1 | gap-303547713                             |
|      1 | gap-303547714                             |
|      1 | gap-303547715                             |
|      1 | gap-303547716                             |
|      1 | gap-303547717                             |
|      1 | gap-303547719                             |
|      1 | gap-303547721                             |
|      1 | gap-303547723                             |
|      1 | gap-303547725                             |
|      1 | gap-303547727                             |
|      1 | gap-303547730                             |
|      1 | gap-303547732                             |
|      1 | gap-303547738                             |
+--------+-------------------------------------------+
```

```
mysql> SHOW GLOBAL VARIABLES LIKE 'tmp_table_size';
+----------------+----------+
| Variable_name  | Value    |
+----------------+----------+
| tmp_table_size | 16777216 |
+----------------+----------+
```

**Comment by brandond** [comment]
Can you run the first query? That one will show us if compaction is having a hard time keeping up.

That event count is just out of control though. Do you have something deployed to this cluster that is creating an unusually large number of events? What do you get from:
* `kubectl get event -A | wc -l`
* `kubectl get event -A -o wide | tail -n 50`

**Comment by oskapt** [comment]
sorry - not sure how i missed the first one:
```
+--------+-------------+-------------+
| rows   | compact_rev | current_rev |
+--------+-------------+-------------+
| 400524 |   305373556 |   305474349 |
+--------+-------------+-------------+
```

Two days ago the number of rows was 271239. 

The `kubectl get event` commands never return. It times out or says that connecting to port 6443 returns `Connection refused` because it appears that k3s is restarting over and over. 

I tried running the request against individual namespaces and appending to a file, and most of those requests timed out because the apiserver wasn't responding. In the output that _was_ captured, nothing looked unusual other than lots and lots of issues related to timeouts with the API server and restarts.

I'm not running any workloads that are doing anything out of the ordinary, and even after shutting down a whole bunch of workloads, the load is still there.

**Comment by brandond** [comment]
OK. Something is flooding the datastore with event records, to the point where compaction is unable to prune deleted rows at the same rate they are being inserted. 

This is going to look like garbage since it's got a bunch of nonprintable binary data in it, but what do you get from:
```sql
SELECT CONVERT(value USING ascii) FROM kine WHERE name LIKE "/registry/events/%" ORDER BY id DESC LIMIT 100;
```

**Comment by oskapt** [comment]
I've put that output [here](https://pastebin.com/HpMyASbz). 

This system was totally out of control yesterday and affecting other things around it, so I built a new RKE2 cluster and moved everything over. I still have the K3s system around if you want to poke at it, but I honestly think this system got into a state where it couldn't keep up, and reporting that it couldn't keep up generated more records that it couldn't keep up with. It's likely that the root cause is long gone. 

The new cluster is happy and quiet. Unless you have a burning curiosity to figure this out, we can abandon it and close the issue.

**Comment by Glacial-truman** [comment]
> I've put that output [here](https://pastebin.com/HpMyASbz).
> 
> This system was totally out of control yesterday and affecting other things around it, so I built a new RKE2 cluster and moved everything over. I still have the K3s system around if you want to poke at it, but I honestly think this system got into a state where it couldn't keep up, and reporting that it couldn't keep up generated more records that it couldn't keep up with. It's likely that the root cause is long gone.
> 
> The new cluster is happy and quiet. Unless you have a burning curiosity to figure this out, we can abandon it and close the issue.





https://stackdev.space/questions/choosing-a-random-2-percent-of-rows-in-mysql-a-simple-guide
