### ISSUE TITLE
key newer than datastore and could cause a cluster outage

### ISSUE THREAD

**Issue by ekhc** [k3s-io/k3s#5714]
**Environmental Info:**
K3s Version:

k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 

Linux dev-pachyderm-rhel002-ncl 4.18.0-348.23.1.el8_5.x86_64 #1 SMP Tue Apr 12 11:20:32 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers

**Describe the bug:**

Certificates and keys are duplicated(?). Removing the files doesn't do anything

**Steps To Reproduce:**

On a fresh RHEL 8.5 VM (same issue in Centos 7.4)

```
systemctl disable firewalld --now
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init
```

On a second fresh RHEL 8.5 VM:

```
systemctl disable firewalld --now
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init
sudo K3S_TOKEN=SECRET k3s server --server https://ip or hostname of server1:6443 --disable-agent
```

**Expected behavior:**

Installation should proceed as normal

**Actual behavior:**

Installation fails

**Additional context / logs:**

```
WARN[0000] Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation.
INFO[0000] Reconciling bootstrap data between datastore and disk
FATA[0000] /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt, /var/lib/rancher/k3s/server/tls/etcd/server-ca.key, /var/lib/rancher/k3s/server/tls/client-ca.key, /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt, /var/lib/rancher/k3s/server/tls/client-ca.crt, /var/lib/rancher/k3s/server/tls/etcd/peer-ca.key, /var/lib/rancher/k3s/server/tls/request-header-ca.crt, /var/lib/rancher/k3s/server/tls/request-header-ca.key, /var/lib/rancher/k3s/server/tls/server-ca.crt, /var/lib/rancher/k3s/server/tls/service.key, /var/lib/rancher/k3s/server/cred/ipsec.psk, /var/lib/rancher/k3s/server/tls/server-ca.key newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore.
```

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
```console
systemctl disable firewalld --now
curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init
sudo K3S_TOKEN=SECRET k3s server --server https://ip or hostname of server1:6443 --disable-agent
```

This will result in the install script starting the k3s systemd unit, followed by running another copy of `k3s server` running from your shell. What are you attempting to do by running it interactively?

**Comment by ekhc** [comment]
ahhhh I see. I was just following the directions here

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

<img width="969" alt="image" src="https://user-images.githubusercontent.com/8185339/173772060-584ef98d-ad28-4243-bc8c-38ec67651893.png">

I'm trying to create a k3s cluster to run a MLOps program that runs on k8s.

I also tried deleting k3s and then running

```
systemctl disable firewalld --now
curl -sfL https://get.k3s.io sh -
sudo K3S_TOKEN=SECRET k3s server --server https://ip or hostname of server1:6443 --disable-agent
```

and I still get the same error.

**Comment by brandond** [comment]
Do you actually need multiple servers? If not, and one server with multiple agents is OK, I would probably just install one server node and several agents. You might consider running `k3s-uninstall.sh` first to clean up after the failed initial installs.

> `sudo K3S_TOKEN=SECRET k3s server --server https://ip or hostname of server1:6443 --disable-agent`

Why are you running k3s with `--disable-agent`?  If you want to deploy things to the cluster you'll need the kubelet and containerd, both of which are not present if you disable the agent.

**Comment by Makos63** [comment]
Hello, I am having the same issue with the certificate while following the documentation to install k3s HA with etcd. Logfile snippet:

```
Jun 15 15:05:06 .... k3s[8187]: time="2022-06-15T15:05:06Z" level=warning msg="Cluster CA certificate is
 not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the serv
er's node-token file to enable Cluster CA validation."
Jun 15 15:05:06 .... k3s[8187]: time="2022-06-15T15:05:06Z" level=info msg="Reconciling bootstrap data b
etween datastore and disk"
Jun 15 15:05:06 .... k3s[8187]: time="2022-06-15T15:05:06Z" level=fatal msg="/var/lib/rancher/k3s/server
/tls/server-ca.crt, /var/lib/rancher/k3s/server/tls/server-ca.key, /var/lib/rancher/k3s/server/tls/etcd/peer-c
a.crt, /var/lib/rancher/k3s/server/tls/service.key, /var/lib/rancher/k3s/server/tls/etcd/server-ca.key, /var/l
ib/rancher/k3s/server/tls/request-header-ca.crt, /var/lib/rancher/k3s/server/tls/client-ca.key, /var/lib/ranch
er/k3s/server/tls/etcd/peer-ca.key, /var/lib/rancher/k3s/server/cred/ipsec.psk, /var/lib/rancher/k3s/server/tls/request-header-ca.key, /var/lib/rancher/k3s/server/tls/client-ca.crt, /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore."
```
Deleting these files, rerunning the application, is not recreating them. I tried the embedded HA installation on OL8, Ubuntu 20.04 LTE and encountered the same result. There is only one instance of k3s per server and 3 servers in total.

**Comment by brandond** [comment]
@Makos63 I would run the uninstall script as suggested above, then start over from scratch, doing the following:

On the first server:
`curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init`

On servers n>1
`curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --server=https://SERVER1:6443`

On the agents:
`curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - agent --server=https://SERVER1:6443`

That's all there is to it.

**Comment by Makos63** [comment]
I tried the command and the results are the same. Attempts to join the cluster result in timeout on the first master, and every next master node has error  or "_with connection refused_" or "_certificate signed by unknown authority_". Some more logs from my 3 servers: [K3S_ha_with_etcd.txt](https://github.com/k3s-io/k3s/files/8926172/K3S_ha_with_etcd.txt)


Now I will try to install the cluster with an older version.

**Comment by brandond** [comment]
> every next master node has error or "with connection refused" or "certificate signed by unknown authority"

Do you have the correct port open between your nodes?

**Comment by Makos63** [comment]
Like mentioned in other post, I tried the HA installation on Ubuntu 20.04 and Oracle Linux 8 both failed. But installing only one master node and 2 worker nodes is successfully. 



Some more information on my environments. All hosts in OL8 cluster use SSDs in ZFS split mirror pool (similar to RAID 10), these are the benchmark results:
```
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=8G --readwrite=randrw --rwmixread=75


fiotest: (groupid=0, jobs=1): err= 0: pid=248445: Mon Jun 20 10:02:11 2022
  read: IOPS=97.3k, BW=380MiB/s (399MB/s)(6141MiB/16154msec)
   bw (  KiB/s): min=348656, max=451944, per=100.00%, avg=389417.19, stdev=28312.53, samples=32
   iops        : min=87164, max=112988, avg=97354.47, stdev=7078.28, samples=32
  write: IOPS=32.5k, BW=127MiB/s (133MB/s)(2051MiB/16154msec); 0 zone resets
   bw (  KiB/s): min=115920, max=149984, per=100.00%, avg=130032.59, stdev=9045.25, samples=32
   iops        : min=28980, max=37496, avg=32508.12, stdev=2261.33, samples=32
```
the OS template has 4 Cores, 8GB of RAM and 100GB root disk and data disk with 30GB all are encrypted. 


But on this cluster we have some security(FIPS, GRUB password, firewall, CIS/pci dss compliance) so to make sure that it does not intervene with the installation I decided to install it on not restrictive cluster with ubuntu 20.04 (we use HDDs here), yet still the log messages and how the nodes behave look pretty much the same. ZFS pool with HDD Benchmark:
```
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=8G --readwrite=randrw --rwmixread=75

fiotest: (groupid=0, jobs=1): err= 0: pid=1012800: Mon Jun 20 08:50:23 2022
  read: IOPS=6271, BW=24.5MiB/s (25.7MB/s)(3070MiB/125312msec)
   bw (  KiB/s): min=   80, max=34872, per=100.00%, avg=25589.22, stdev=5216.90, samples=245
   iops        : min=   20, max= 8718, avg=6397.30, stdev=1304.22, samples=245
  write: IOPS=2096, BW=8384KiB/s (8585kB/s)(1026MiB/125312msec); 0 zone resets
   bw (  KiB/s): min=   24, max=10888, per=100.00%, avg=8551.47, stdev=1708.60, samples=245
   iops        : min=    6, max= 2722, avg=2137.86, stdev=427.15, samples=245
  cpu          : usr=3.76%, sys=11.78%, ctx=260206, majf=0, minf=9
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
```
Ubuntu OS template has 8 Cores, 4GB of RAM and 32GB root disk not encrypted. 


The Logs from last post come from ubuntu cluster and I double-checked the firewall and scanned the network with nmap. It looks good to me, but still the problem persists. Can it have something to do with Proxmox cluster? The hosts are physically next to each other, so network latency is also not a problem.
