### ISSUE TITLE
Release directory filenames

### ISSUE THREAD

**Issue by datamgmt** [k3s-io/k3s#572]
I've been looking at the Release directory: https://github.com/rancher/k3s/releases/tag/v0.6.1

As a new user it was a little confusing and so can I suggest the following amendments

hyperkube - should this have a platform architecture added - hyperkube-amd64?
hyperkube-arm64
hyperkube-armhf
k3s - should this have a platform architecture added - k3s-amd64?
k3s-airgap-images-amd64.tar
k3s-airgap-images-arm.tar - should this be renamed to armhf from just arm? 
k3s-airgap-images-arm64.tar
k3s-arm64 downloads as k3s-arm64.dms
k3s-armhf downloads as k3s-armhf.dms
sha256sum-amd64.txt
sha256sum-arm.txt - should this be renamed to armhf from just arm?
sha256sum-arm64.txt
Source code (zip)
Source code (tar.gz)

**Comment by brandond** [comment]
Closing due to age.
