### ISSUE TITLE
Traefik helm chart job fails in v1.23.6+k3s1 or later.

### ISSUE THREAD

**Issue by greerga** [k3s-io/k3s#5745]
**Environmental Info:**
K3s Version: 
k3s version v1.24.1+k3s1 (0581808f)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 
Linux rpi4b-{serial} 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
Jobs "helm-install-traefik" and "helm-install-traefik-crd" go into CrashLoopBackOff because they can't write to /dev/termination-log.

**Steps To Reproduce:**
- Upgraded k3s from v1.21.7+k3s1 to v1.23.6+k3s1 and v1.24.1+k3s1.

**Expected behavior:**
Job succeeds, like it did back in v1.21.7+k3s1.

**Actual behavior:**
```
+ echo 'Upgrading helm_v3 chart'
/usr/bin/entry: line 68: /dev/termination-log: Permission denied
```
and
```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
```

**Additional context / logs:**
```
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
	echo "KUBERNETES_SERVICE_HOST is using IPv6"
	CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
	CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ tiller --listen=127.0.0.1:44134 --storage=secret
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
Creating /home/klipper-helm/.helm 
Creating /home/klipper-helm/.helm/repository 
Creating /home/klipper-helm/.helm/repository/cache 
Creating /home/klipper-helm/.helm/repository/local 
Creating /home/klipper-helm/.helm/plugins 
Creating /home/klipper-helm/.helm/starters 
Creating /home/klipper-helm/.helm/cache/archive 
Creating /home/klipper-helm/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://charts.helm.sh/stable/ 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ timeout -s KILL 30 helm_v2 ls --all '^traefik$' --output json
++ jq -r '.Releases | length'
[main] 2022/06/20 02:11:19 Starting Tiller v2.17.0 (tls=false)
[main] 2022/06/20 02:11:19 GRPC listening on 127.0.0.1:44134
[main] 2022/06/20 02:11:19 Probes listening on :44135
[main] 2022/06/20 02:11:19 Storage driver is Secret
[main] 2022/06/20 02:11:19 Max history per release is 0
[storage] 2022/06/20 02:11:19 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ [[ -f /config/ca-file.pem ]]
+ [[ -n '' ]]
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls ++ jq -r '"\(.[0].app_version),\(.[0].status)"'
--all -f '^traefik$' --namespace kube-system --output json
++ tr '[:upper:]' '[:lower:]'
+ LINE=2.6.2,deployed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ 2.6.2 =~ ^(|null)$ ]]
+ [[ deployed =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ deployed == \d\e\p\l\o\y\e\d ]]
+ echo 'Already installed traefik'
Already installed traefik
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ helm_v3 mapkubeapis traefik --namespace kube-system
2022/06/20 02:11:22 Release 'traefik' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2022/06/20 02:11:22 Get release 'traefik' latest version.
2022/06/20 02:11:23 Check release 'traefik' for deprecated or removed APIs...
2022/06/20 02:11:23 Finished checking release 'traefik' for deprecated or removed APIs.
2022/06/20 02:11:23 Release 'traefik' has no deprecated or removed APIs.
2022/06/20 02:11:23 Map of release 'traefik' deprecated or removed APIs to supported versions, completed successfully.
+ echo 'Upgrading helm_v3 chart'
/usr/bin/entry: line 68: /dev/termination-log: Permission denied
```
This was failing when Traefik v1 was present and continues to fail the same way after I manually updated to Traefik v2.
The presence or absence of the `/dev/termination-log` file on the host doesn't seem to matter.  (On host it is `-rwxr-xr-x 1 root root 0 Jun 18 00:11 /dev/termination-log`.)

**Backporting**
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
`Upgraded k3s from v1.21.7+k3s1 to v1.23.6+k3s1 and v1.24.1+k3s1.`

Are you saying that you see the same behavior from both of the newer versions?

In general, the Kubernetes [version skew policy](https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order) expects you to step through upgrades, so you should go through 1.21 -> 1.22 -> 1.23 -> 1.24.

**Comment by greerga** [comment]
> `Upgraded k3s from v1.21.7+k3s1 to v1.23.6+k3s1 and v1.24.1+k3s1.`
> 
> Are you saying that you see the same behavior from both of the newer versions?
> 
> In general, the Kubernetes [version skew policy](https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order) expects you to step through upgrades, so you should go through the latest release on each minor of 1.21 -> 1.22 -> 1.23 -> 1.24. Upgrade **all** nodes to each version, allow the cluster to settle, then move to the next version.

Are you sure?  It says:

> kubelet must not be newer than kube-apiserver, and may be up to two minor versions older.

And I did step everything up from v1.21 to v1.23 before progressing on to v1.24.

The other components are all-in-one packages as far as I know with k3s so the control plan was all upgraded in step.

**Comment by greerga** [comment]
> can't reproduce this under any circumstances. Is there anything else you can share about your node or cluster configuration?

I'd be happy to if I could think of what might be relevant.  They're "Raspbian GNU/Linux 10 (buster)" with the 64-bit kernels as base OS.

> I will say that it's rather odd that the host itself has a `/dev/termination-log` file; this is not something that should exist on a host - did you create it manually?

No, it seems to appear when running the `k3s` upgrade script. (As in the `curl -sfL https://get.k3s.io | sh -` command.)

```
$ kubectl run -i --tty --rm test --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # ls -la /dev/termination-log
-rw-rw-rw-    1 root     root             0 Jun 30 02:51 /dev/termination-log
```
So that looks normal.

I tried making a copy of the job that ran `sh -c 'sleep 86400'` instead, but even that looked fine when I `kubectl exec` into it:

```
$ kubectl -n kube-system exec -i -t helm-install-traefik-crd-manual-xpmsc -- /bin/sh
~ $ ls -la /dev/termination-log
-rw-rw-rw-    1 root     root             0 Jun 30 03:22 /dev/termination-log
```

but if I look at the pod logs of a fresh job run, I still see the:
```
+ echo 'Upgrading helm_v3 chart'
/usr/bin/entry: line 68: /dev/termination-log: Permission denied
```
so not sure if the helm controller is doing something odd, or one of the scripts run by the image change it.

**Comment by brandond** [comment]
Do you have selinux or apparmor enabled?

**Comment by greerga** [comment]
Raspberry Pi OS kernel doesn't have SELinux enabled.  It does have AppArmor enabled but the only two AppArmor profiles on the host are `usr.bin.man` and `usr.sbin.ntpd`, and the AppArmor binaries aren't installed so they might not even be active.

**Comment by brandond** [comment]
That file is world writable so there is something preventing the pod from writing to it. Usually that's some sort of security module but I'm at a loss as to what it might be on your node. Have you tried Ubuntu on this node instead of Pi OS?

**Comment by greerga** [comment]
I checked the mounts in the container and it has a special direct mount of that file to the host:
```
10.0.1.201:/home/tftpboot/{serial}-root/var/lib/kubelet/pods/a99b119c-9eb5-4773-a384-31905972d208/containers/helm/a28deee7 on /dev/termination-log type nfs4 (rw,relatime,vers=4.0,rsize=4096,wsize=4096,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.0.1.193,local_lock=none,addr=10.0.1.201)
```
(The Raspberry Pis are running with NFS root except that /var/lib/rancher is on the SD card.)

So normally I'd blame SELinux on that NFS server except it is running in Permissive mode.

But more likely than not the issue is related to my setup rather than k3s in general so I'll close this until/if I get evidence it is a general issue.
