### ISSUE TITLE
Need a flag to disable the generation of the k3s.yaml file

### ISSUE THREAD

**Issue by chasain** [k3s-io/k3s#5758]
**Environmental Info:**
K3s Version: v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 5.11.0-37-generic #41~20.04.2-Ubuntu

Cluster Configuration: Single Node

We're in the process of hardening deployments for some edge clusters we are deploying to customer sites and we need a way to either disable the generation of the k3s.yaml file or change the write path to a tmpfs path. We've determined it would be okay if it's a flag since the user would need to authenticate to the host to change it, but written to disk in plaintext is something we need to avoid.

**Comment by brandond** [comment]
This seems like part of a flawed risk analysis. Having admin credentials written to disk in /etc/rancher/k3s/k3s.yaml does not change your risk profile. All servers have a copy of the cluster root CA certificates and keys written to disk under /var/lib/rancher/k3s/server/tls; anyone with access to those files could generate certificates with the exact same (or more) privilege as provided by the current admin kubeconfig.
