### ISSUE TITLE
Restoring a snapshot of a hardened setup to a fresh node fails

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#5763]
**Environmental Info:**
K3s Version: 

All: 1.21, 1.22, 1.23, and 1.24

Node(s) CPU architecture, OS, and Version: 

Any, recreated with ubuntu and sles both

Cluster Configuration:

1 server

**Describe the bug:**

When hardening a k3s node via https://rancher.com/docs/k3s/latest/en/security/hardening_guide/, then taking a snapshot, then restoring that snapshot to a fresh node, it fails to properly restore.

**Steps To Reproduce:**

1. Create necessary files and setup the VM for hardening:
[hardened-k3s.tar.gz](https://github.com/k3s-io/k3s/files/9115649/hardened-k3s.tar.gz)
```
$ tar -xvzf hardened-k3s.tar.gz
$ chmod +x harden.sh
$ sudo ./harden.sh 
```
2. Install k3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 sh -`
3. After everything is up and running, take a snapshot to s3: `sudo k3s etcd-snapshot --s3 --s3-bucket=maxrtest --s3-folder=maxk3s --s3-region=us-east-2 --s3-access-key=<redacted> --s3-secret-key="<redacted>"`
4. Shutdown the VM 
5. On a new fresh VM, attempt to restore the snapshot that was taken:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 INSTALL_K3S_SKIP_ENABLE=true sh -
$ sudo k3s server --cluster-reset --etcd-s3 --cluster-reset-restore-path=<your snapshot's name> --etcd-s3-bucket=maxrtest --etcd-s3-folder=maxk3s --etcd-s3-region=us-east-2 --etcd-s3-access-key=<redacted> --etcd-s3-secret-key="<redacted>" --token=test --debug
```

**Expected behavior:**

Snapshot should restore successfully with no errors and I should be able to then start k3s and have this fresh VM with the original data from the cluster on the previous VM.

**Actual behavior:**

An error occurs during the reset:
```
INFO[0004] etcd data store connection OK                
INFO[0004] Waiting for API server to become available   
INFO[0004] ETCD server is now running                   
INFO[0004] k3s is up and running                        
WARN[0004] bootstrap key already exists                 
INFO[0004] Reconciling etcd snapshot data in k3s-etcd-snapshots ConfigMap 
INFO[0005] Tunnel server egress proxy waiting for runtime core to become available 
INFO[0005] Defragmenting etcd database                  
{"level":"info","ts":"2022-06-24T17:09:41.163Z","caller":"v3rpc/maintenance.go:89","msg":"starting defragment"}
{"level":"info","ts":"2022-06-24T17:09:41.169Z","caller":"backend/backend.go:497","msg":"defragmenting","path":"/var/lib/rancher/k3s/server/db/etcd/member/snap/db","current-db-size-bytes":2424832,"current-db-size":"2.4 MB","current-db-size-in-use-bytes":2416640,"current-db-size-in-use":"2.4 MB"}
{"level":"info","ts":"2022-06-24T17:09:41.216Z","caller":"backend/backend.go:549","msg":"finished defragmenting directory","path":"/var/lib/rancher/k3s/server/db/etcd/member/snap/db","current-db-size-bytes-diff":0,"current-db-size-bytes":2424832,"current-db-size":"2.4 MB","current-db-size-in-use-bytes-diff":0,"current-db-size-in-use-bytes":2416640,"current-db-size-in-use":"2.4 MB","took":"53.155117ms"}
{"level":"info","ts":"2022-06-24T17:09:41.216Z","caller":"v3rpc/maintenance.go:95","msg":"finished defragment"}
INFO[0005] Reconciling bootstrap data between datastore and disk 
DEBU[0005] Reconciling RequestHeaderCA at '/var/lib/rancher/k3s/server/tls/request-header-ca.crt' 
FATA[0005] stat : no such file or directory   
```

**Additional context / logs:**

Full output of the command:
[reset.log](https://github.com/k3s-io/k3s/files/8978856/reset.log)

Full output of the command _with debug flag included_:
[reset.log](https://github.com/k3s-io/k3s/files/8994179/reset.log)

Adding the directories that were present before install on the other node does not fix the issue:
```
$ sudo mkdir -p -m 700 /var/lib/rancher/k3s/server/logs
$ sudo mkdir -p /etc/rancher/k3s
$ sudo mkdir -p /var/lib/rancher/k3s/server/manifests
$ sudo k3s server --cluster-reset --etcd-s3 --cluster-reset-restore-path=on-demand-ip-172-31-36-255-1656090522 --etcd-s3-bucket=maxrtest --etcd-s3-folder=maxk3s --etcd-s3-region=us-east-2 --etcd-s3-access-key=<redacted> --etcd-s3-secret-key="<redacted>" --token=test
...
FATA[0002] Failed to reconcile with temporary etcd: stat : no such file or directory
```

**Backporting**

- [x] Needs backporting to older releases

**Comment by brandond** [comment]
Although I'm not finding the issue at the moment, I remember seeing something similar a while back and I couldn’t figure out how it got into that state. I believe I added some debug logging - would you be able to try the same with `--debug`?

**Comment by rancher-max** [comment]
Yep! Updated the original issue comment with results from debug 👍

**Comment by rancher-max** [comment]
So the issue stands as it's written, but it may be that we invalidate this. When I performed the following steps to harden the fresh VM before restoring the snapshot, it worked:

**Fresh Node Steps:**
5. Harden a new fresh VM by performing step 1 above on a new machine.
6. Attempt to restore the snapshot that was taken:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 INSTALL_K3S_SKIP_ENABLE=true sh -
$ sudo k3s server --cluster-reset --etcd-s3 --cluster-reset-restore-path=<your snapshot's name> --etcd-s3-bucket=maxrtest --etcd-s3-folder=maxk3s --etcd-s3-region=us-east-2 --etcd-s3-access-key=<redacted> --etcd-s3-secret-key="<redacted>" --token=test --debug
```

**Comment by brandond** [comment]
I added some additional debug logging and believe I've found a more simple reproduction:

1. start k3s with `--cluster-init --secrets-encryption=true --token=test`
2. take an etdc snapshot to s3
3. k3s-killall.sh && rm -rf /var/lib/rancher/k3s
4. start k3s with `--cluster-reset --cluster-reset-restore=xxx --secrets-encryption=false --token=test`


Logs from this show:
```
INFO[0001] Reconciling bootstrap data between datastore and disk
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking ETCDServerCAKey at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.key'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking IPSECKey at '/var/lib/rancher/k3s/server/cred/ipsec.psk'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking ServerCA at '/var/lib/rancher/k3s/server/tls/server-ca.crt'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking ServiceKey at '/var/lib/rancher/k3s/server/tls/service.key'
DEBU[0001] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt' - case 1 checking EncryptionConfig at ''
FATA[0001] Failed to reconcile with temporary etcd: case 1 failed to stat EncryptionConfig at '': stat : no such file or directory
```

For some we have inner loops in the time skew checks:
https://github.com/k3s-io/k3s/blob/a237260237b549b90dd3aae449de09231caf1351/pkg/cluster/bootstrap.go#L364-L368
https://github.com/k3s-io/k3s/blob/a237260237b549b90dd3aae449de09231caf1351/pkg/cluster/bootstrap.go#L394-L398

Besides causing O(n^2) stat calls on all the files, the inner loops will cause the reconcile to fail if the bootstrap data contains data for a feature not currently enabled (encryption config, in this case).
