### ISSUE TITLE
[question] Re-enabling the metrics-server after an installation

### ISSUE THREAD

**Issue by aureq** [k3s-io/k3s#5765]
**Environmental Info:**
K3s Version: v1.23.6+k3s1

Node(s) CPU architecture, OS, and Version: 
* `Linux k3s-1 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`
* `Linux k3s-2 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`
* `Linux k3s-3 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

Cluster Configuration:
* 3 servers (control-plane,etcd,master)

**Problem / Question:**
I have a working k3s cluster with 3 nodes and all is fine and working perfectly well. However, when the cluster was first installed, a few options were passed to disable a number of features. Specifically: `INSTALL_K3S_EXEC="--disable-cloud-controller --disable traefik --disable metrics-server --disable servicelb --bind-address 192.168.2.81 --cluster-init --tls-san 192.168.2.80"`

Today, I'm trying to find a way to re-enable the `metrics-server` as part of this existing cluster. However, I didn't find any relevant documentation. I looked at the [K3s Server Configuration Reference](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/) and [Disable Components Flags](https://rancher.com/docs/k3s/latest/en/installation/disable-flags/) pages.

I also found that `/etc/systemd/system/k3s.service` uses `--disable metrics-server` but I'm trying to find a way to make the change persistent across upgrades as well, so I don't think this would be the correct way.

My questions are:
* what is the recommended way to re-enable a feature that has been disabled during the installation?
* how to ensure the change will be persistent across upgrades?

Thank you

**Comment by brandond** [comment]
> I also found that /etc/systemd/system/k3s.service uses --disable metrics-server

Remove that flag from the systemd unit, then run `systemctl daemon-reload` and `systemctl restart k3s` .

**Comment by aureq** [comment]
@brandond I'll perform the change tomorrow and I'll keep you posted. I'm also planning in update to the latest 1.23.8 to make sure the procedure work with the assisted system-upgrade.
