### ISSUE TITLE
[release-1.23] Kine version bump

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5801]
Issue does not affect Kubernetes 1.23, but we should keep kine in sync across all active branches:
* #5794

**Comment by ShylajaDevadiga** [comment]
As mentioned there is no issue getting resources in k3s v1.23. Validated kine version bump using go.mod in release1.23 branch `github.com/k3s-io/kine v0.9.3`

```
ubuntu@ip-172-31-3-23:~$ k3s -v
k3s version v1.23.1+k3s1 (08d538fb)
go version go1.17.5
ubuntu@ip-172-31-3-23:~$ kubectl get svc --field-selector metadata.name=kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   29s
ubuntu@ip-172-31-3-23:~$ 

```
