### ISSUE TITLE
Improve or re-design website

### ISSUE THREAD

**Issue by reveurguy** [k3s-io/k3s#5807]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

The look and design of the current website can be improved. I would like to work upon that, either make changes to the current one or do a re-design. I wanted to get started doing that but i was not able to find the codebase for the website.

**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Thanks for the offer! At the moment the docs are still entangled with the main Rancher docs, and the website itself is in a private repo and hosted on Rancher infra. We'll be renewing our focus on disentangling k3s from suse/rancher over the next few months.

**Comment by reveurguy** [comment]
Great, would love to contribute!

**Comment by brandond** [comment]
docs have moved.
