### ISSUE TITLE
K3s agent node not getting connected to master node on AWS-EC2

### ISSUE THREAD

**Issue by ayush29azad** [k3s-io/k3s#5808]
**Environmental Info:**
K3s Version: 
v1.23.8+k3s1 (53f2d4e7)

Node(s) CPU architecture, OS, and Version: 
Linux ip-172-31-88-240 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master and 2 agent nodes

**Description  the bug:**
Agent node not joining master node when I type command kubectl get nodes.

**Steps To Reproduce:**
- **Installed K3s on the master node**

    - $ `MASTER_IP=3.93.220.207 (IPv4 Public IP: 3.93.220.207)`

```
$curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --no-deploy traefik --disable traefik --tls-san "$MASTER_IP" --node-external-ip "$MASTER_IP" --disable servicelb" sh -s -
```

Generated token by  sudo cat /var/lib/rancher/k3s/server/node-token

**On each agent**

    MASTER_IP=3.93.220.207
    export TOKEN=YOUR_MASTER_TOKEN 
    curl -sfL https://get.k3s.io | sh -s - agent --server https://$MASTER_IP :6443 --token ${TOKEN} 

**Expected behavior:**
`kubectl get nodes` command should show agent nodes, but agent nodes are not attached ...

![Screenshot 2022-07-04 at 2 51 39 PM](https://user-images.githubusercontent.com/62204960/177124751-a0c48e6b-b772-4339-a380-2547d8a85197.png)

**Actual behavior:**
kubectl get nodes does not show agent nodes ....

Please help me to resolve this issue ..... I have done all steps correctly and also exposed the public IP ....I am feeling frustated ... I have been trying this from many days.I even tried implementing this on a virtual box as well but every time I get disappointment. 

**EXTRA INFORMATION** 
(failed to get CA CERTS)

`systemctl status k3s-agent` command gives shows [![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Mi1qK.png

**Comment by ayush29azad** [comment]
😭😭😭😭😭

**Comment by ayush29azad** [comment]
![image](https://user-images.githubusercontent.com/62204960/177136823-069cf1be-b309-48b6-b8b1-83950abd5a3b.png)

**Comment by ayush29azad** [comment]
I am Running k3s on AWS EC2 INSTANCES

**Comment by brandond** [comment]
Are you sure that you have all the correct ports open in the nodes security groups? You can find the full port list here: https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#networking

The basic test to ensure that you've opened the api server port on the server would be to run `curl -vks https://SERVER-IP:6443/ping` from the agent. If you cannot successfully use curl to reach the server, then the agent will not be able to do so either.
