### ISSUE TITLE
HA Clusters and Load balancing

### ISSUE THREAD

**Issue by invent360** [k3s-io/k3s#5809]
This may not be the right channel for such questions so apologies in advance.
1) What is the right master/worker nodes ratio in a production type k8s cluster considering the following use cases.

i) 3 Master (embedded etcd) Nodes (4GB RAM each) : 5 Worker Nodes (4GB RAM each)
ii) 5 Master (embedded etcd) Nodes (4GB RAM each) : 3 Worker Nodes (4GB RAM each)
iii)3 Master (embedded etcd) Nodes (4GB RAM each) : 3 Worker Nodes (4GB RAM each)

2) In order to create an HA cluster, will it suffice to just create e.g. 3 Master Nodes and 5 Worker Nodes? or do we need a load balancer like nginx in front of the masters ?. If not, how does client requests like (`kubectl get pods`) get "load balanced" or does it go just to one master every time ?

3) Is there a need to also place a load balancer between the masters and the workers ?
And what other factors should be considered when creating a production grade k8s cluster ?

**Comment by LarsBingBong** [comment]
Very classic Kubernetes architecture question. You should check out the official docs and recommendations.

**Comment by invent360** [comment]
The k8s doc does not say anything regarding master:worker ratio, all other details and recommendations are well explained and assumptions shouldn't be made that i did not take a look at the k8s official specifications. What i am trying to get here is personal experiences and question 2 is very specific to k3s.
