### ISSUE TITLE
Add `aws-vpc` as a flannel backend option

### ISSUE THREAD

**Issue by ajohnson-veri** [k3s-io/k3s#5811]
**Is your feature request related to a problem? Please describe.**

Flannel v18.1 supports a backend option called `aws-vpc` but the k3s install option `--flannel-backend` does not allow for this backend mode to be used. It reports the usage error seen here. 

k3s Option: https://github.com/k3s-io/k3s/blob/a693071c74688db1cc3330748f1a98f5321ffcd4/pkg/cli/cmds/server.go#L208-L213

Flannel Backends: https://github.com/flannel-io/flannel/blob/master/Documentation/aws-vpc-backend.md

**Describe the solution you'd like**

My request is that the `--flannel-backend` option allow for the `aws-vpc` setting along with another Networking option to provide an associated CIDR block for flannel. Below is the flannel configuration I've been installing manually

```
etcdctl set /coreos.com/network/config '{"Network":"10.20.0.0/16", "Backend": {"Type": "aws-vpc"}}'
```

My current workaround/solution is to install k3s with the following options...
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr=10.244.0.0/16 --disable traefik --flannel-backend=none --disable-network-policy" sh -
```
...while launching etcd and flannel separately as services on ubuntu 20.04 and then manually adding the above flannel configuration.

The `aws-vpc` option would let us continue using embedded etcd with k3s and simply set an option for flannel rather than running it ourselves.

Example aws-vpc install:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr=10.244.0.0/16 --disable traefik --flannel-backend=aws-vpc --disable-network-policy --cluster-init" sh -
```

**Describe alternatives you've considered**

There are various workarounds available but they involve a lot of manually steps to essentially launch and configure flannel manually and the solution I proposed simply leverages an existing configuration option.

**Additional context**

Flannel Backends: https://github.com/flannel-io/flannel/blob/master/Documentation/aws-vpc-backend.md

**Backporting**

N/A

**Comment by brandond** [comment]
We tend to not include any extra cloud-provider specific stuff built in to k3s, but if the aws-vpc backend doesn't require any additional packages to coordinate setting up the interface, or if those binaries can be provided by the end user, this seems fairly doable.
