### ISSUE TITLE
k3s crashed regulary -> context deadline exceeded

### ISSUE THREAD

**Issue by DarianAnjuhal** [k3s-io/k3s#5834]
**Environmental Info:**
K3s Version: 

k3s version v1.20.15+k3s1 (c7a91e1c)
go version go1.15.15

Node(s) CPU architecture, OS, and Version: 

Linux node18 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 server in one cluster

**Describe the bug:**

We using monitoring and always observed down times from cluster services. In the k3s log using 'journalctl -u k3s' we have seen crashed and restarts with a lot of trace logs.

**Expected behavior:**

Should run without crashed

**Actual behavior:**

Crashes regulary -> daily

**Additional context / logs:**

[node18.short.log](https://github.com/k3s-io/k3s/files/9078769/node18.short.log)

It would be awesome if we can get some infos/hints how to tackle/debug this problem. Or maybe there are bugfixes already.

Thanks in advance
Darian

**Comment by brandond** [comment]
>  v1.20.15+k3s1

The 1.20 release branch has been end of life since 2021-12-30. However, the logs indicate that upgrading is unlikely to solve your problem, as it appears that the disks on your nodes are unable to commit writes in a timely manner:

`Jul 10 06:10:55 node18 k3s[3570163]: {"level":"warn","ts":"2022-07-10T06:10:55.088+0200","caller":"wal/wal.go:808","msg":"slow fdatasync","took":"5.466372338s","expected-duration":"1s"}`

Ensure that you have sufficient disk iops available. Etcd is usually run on SSD or NVME. If you are also running an IO intensive workload, steps should be taken to isolate workload IO from system IO by placing them on separate disks.

**Comment by DarianAnjuhal** [comment]
Hi!

Thanks for your information. We are actually using SSD for all 3 nodes in the cluster. I want to share some server specification which are equal for each node in the cluster:

Disk: 320 GB SSD 
DDR4: 16 GB
Core: 6 ddedicated
Processor: AMD EPYC™ 7702

I don't know anything about intensive IO workload. Is there a tool to find out where the workload is coming from? Which process?

Thank you and bye
Darian

**Comment by brandond** [comment]
If you have Prometheus, there should be some pod-level IO statistics available. You could also use tools like dstat or iotop to look at disk IO from the terminal.

**Comment by DarianAnjuhal** [comment]
Hi, thank you!
Unfortunately we are currently not using Prometheus because the Prometheus needs to much resources we want to save. :-)
But I can try iotop to get some informations...

Another thing is we curring couple of clusters with similar hardware. Crashes just occur on two clusters...

Thank you and Bye
Daniel

**Comment by DarianAnjuhal** [comment]
Hi again, I am using fio to test the speed on the nodes.

I used this link: https://www.suse.com/support/kb/doc/?id=000020100 -> Testing etcd performance

Here is an example output:

```
fio --rw=write --ioengine=sync --fdatasync=1 --directory=test-data --size=100m --bs=2300 --name=mytest
mytest: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
fio-3.30-85-g3e1d3
Starting 1 process
mytest: Laying out IO file (1 file / 100MiB)
Jobs: 1 (f=1): [W(1)][100.0%][w=6544KiB/s][w=2913 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=2737696: Fri Jul 29 09:44:37 2022
  write: IOPS=3534, BW=7940KiB/s (8130kB/s)(100.0MiB/12897msec); 0 zone resets
    clat (nsec): min=1693, max=415641, avg=6428.41, stdev=7964.29
     lat (nsec): min=1813, max=416062, avg=6699.49, stdev=8011.90
    clat percentiles (usec):
     |  1.00th=[    3],  5.00th=[    3], 10.00th=[    3], 20.00th=[    4],
     | 30.00th=[    5], 40.00th=[    5], 50.00th=[    6], 60.00th=[    6],
     | 70.00th=[    7], 80.00th=[    8], 90.00th=[   10], 95.00th=[   14],
     | 99.00th=[   31], 99.50th=[   39], 99.90th=[   63], 99.95th=[  101],
     | 99.99th=[  355]
   bw (  KiB/s): min= 5287, max= 9613, per=100.00%, avg=7951.08, stdev=982.12, samples=25
   iops        : min= 2354, max= 4280, avg=3540.16, stdev=437.29, samples=25
  lat (usec)   : 2=0.07%, 4=25.94%, 10=64.22%, 20=6.92%, 50=2.65%
  lat (usec)   : 100=0.16%, 250=0.02%, 500=0.03%
  fsync/fdatasync/sync_file_range:
    sync (usec): min=77, max=9452, avg=274.47, stdev=205.67
    sync percentiles (usec):
     |  1.00th=[   98],  5.00th=[  105], 10.00th=[  112], 20.00th=[  130],
     | 30.00th=[  147], 40.00th=[  186], 50.00th=[  262], 60.00th=[  297],
     | 70.00th=[  330], 80.00th=[  367], 90.00th=[  437], 95.00th=[  562],
     | 99.00th=[  816], 99.50th=[ 1012], 99.90th=[ 2507], 99.95th=[ 3228],
     | 99.99th=[ 5669]
  cpu          : usr=1.45%, sys=11.11%, ctx=112172, majf=0, minf=14
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,45590,0,0 short=45590,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=7940KiB/s (8130kB/s), 7940KiB/s-7940KiB/s (8130kB/s-8130kB/s), io=100.0MiB (105MB), run=12897-12897msec

Disk stats (read/write):
  vda: ios=0/117324, merge=0/51463, ticks=0/11267, in_queue=28, util=99.31%
```
Because the 99.00th percentil is less than 10 ms it should be more then okay. I really think its a kind of misconfiguration or issue from the software side.

Maybe there are more ideas or you can point me to the correct direction.

Bye Darian

**Comment by brandond** [comment]
There's not really anything to misconfigure. Etcd calls fsync to ensure that writes are committed to disk. When the cluster is operating, fsync calls take too long; the logs show that quite clearly. 

> If you are also running an IO intensive workload, steps should be taken to isolate workload IO from system IO by placing them on separate disks.

Keep in mind that fsync has to flush ALL outstanding IO to disk. If you have a workload that is also writing, the latency will go up as the disks have to flush not just the write from etcd, but also anything else that your workload is doing. This is why running a disk benchmark on an idle system doesn't really give a good idea what your real-world performance looks like.

**Comment by DarianAnjuhal** [comment]
Hi,
in order to investigate this issue I have rent 3 new servers and we setted them up with the same configuration.
k3s in rancher and without workload. So there is nothing running.

So without workload there is still the same issue. I will give logs soon.

**Comment by cybercoder** [comment]
same here
