### ISSUE TITLE
k8s dns known issues replicated on k3s

### ISSUE THREAD

**Issue by ChongmingDu** [k3s-io/k3s#5836]
**Environmental Info:**
K3s Version: 

**v1.24.2+k3s2**

Node(s) CPU architecture, OS, and Version: 

**Ubuntu 22.04 LTS**

**5.15.0-40-generic**

Cluster Configuration:

**Single Node**

**Describe the bug:**

**pod evnets**

```bash
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: x.x.x.x
```

**Steps To Reproduce:**

**k8s known issues**

[k8s.io Known issues](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues)

**Comment by cwayne18** [comment]
Thank you for taking the time to open this issue. As you have pointed out, this is a known issue with upstream kubernetes and is therefore not specific to k3s. I'd suggest tracking this upstream. If you believe there are any specific issues with k3s, please let us know
