### ISSUE TITLE
Ingress-nginx ipv4 forwarding not persisting in the svclb network

### ISSUE THREAD

**Issue by johnyoungatwork** [k3s-io/k3s#5837]
**Environmental Info:**
K3s Version: v1.23.8+k3s1

Node(s) CPU architecture, OS, and Version: lxc

Cluster Configuration:

**Describe the bug:** 
ipv4 forwarding is not working
![image](https://user-images.githubusercontent.com/108930388/178187979-cefad990-fbc0-4ca7-9019-f3fa43e9a9c8.png)
When I logged one of the failed worker nodes, It showed ip_forwarding is not on.
![image](https://user-images.githubusercontent.com/108930388/178188219-ce70547f-bb20-41e5-92eb-2ba3e0c5d8a4.png)
However, ip_forward of all the master and worker nodes is set to 1.
![image](https://user-images.githubusercontent.com/108930388/178209187-28943902-e738-4b4d-91c2-f4f692661086.png)

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

The applied nginx yaml file:
![image](https://user-images.githubusercontent.com/108930388/178209729-32be2326-f46b-4911-9775-5be67cec38be.png)

**Backporting**

- [ ] Needs backporting to older releases

**Comment by johnyoungatwork** [comment]
Thank you for your help in advance! I have been struggling to solve this in the past few days.

**Comment by johnyoungatwork** [comment]
it s set to 1

**Comment by brandond** [comment]
Do you have some other security or network configuration management tool present on the host? What you're describing is not standard behavior.

**Comment by johnyoungatwork** [comment]
It turns out I just set the /proc/sys/net/ipv4/forward=1 in all the lxc but forgot to set ip_forward=1 in the host!
