### ISSUE TITLE
etcd snapshot issues with compression and timeout

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5839]
There are a couple issues with the snapshot controller that are creating problems for Rancher users
* Scheduled snapshots are not compressed
* The default s3 upload timeout is too short, but raising the default timeout may allow multiple snapshot operations to stack up if it exceeds the configured interval.

Upstream issues:
* https://github.com/rancher/rke2/issues/3109
* https://github.com/rancher/rancher/issues/37904#issuecomment-1179413881

**Comment by est-suse** [comment]
Validated on release-1.24 RC  v1.24.3-rc1+k3s1
Environment Details
Infrastructure

 Cloud (AWS)
 Hosted
Node(s) CPU architecture, OS, and Version:

Ubuntu 20.04 LTS

Cluster Configuration:

1 server

Config.yaml:

write-kubeconfig-mode: 644
token: test
cluster-init: true
etcd-snapshot-compress: true
etcd-s3: true
etcd-s3-bucket: maxrtest
etcd-s3-folder: maxk3s
etcd-s3-region: us-east-2
etcd-s3-access-key: "<redacted>"
etcd-s3-secret-key: "<redacted>"
etcd-snapshot-retention: 4
etcd-snapshot-schedule-cron: "*/2 * * * *"
Additional files

N/A

Testing Steps
Copy config.yaml
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
Install k3s
Monitor both the the k3s logs and the designated s3 bucket
Replication Results:

k3s version used for replication:
v1.24.2+k3s2
![image](https://user-images.githubusercontent.com/106194120/179282079-d4c99cff-65d7-4be0-9746-93870d107e3f.png)
![image](https://user-images.githubusercontent.com/106194120/179282158-0f55233a-be9b-42f5-9df4-58f48abf61c9.png)

Validation Results:

k3s version used for validation:
 release-1.24 RC  v1.24.3-rc1+k3s1
Snapshots are saved with zips when defined in the config yaml
On demand snapshots continue to work and save as zips when defined
Logs show snapshots being saved as zips

![image](https://user-images.githubusercontent.com/106194120/179282313-d77cea8e-43f8-4910-a400-abffe58e1446.png)

When compression flag is not defined in the config, snapshots are not saved compressed as expected
