### ISSUE TITLE
CoreDNS resolves AAAA when dualstack is not enabled

### ISSUE THREAD

**Issue by Privatecoder** [k3s-io/k3s#5849]
- Cluster was created without Dual-stack support
- Dual-stack support cannot be added after setting up the cluster according to [this](https://rancher.com/docs/k3s/latest/en/installation/network-options/)
- The host-nodes have IPv6 enabled
- The hosts-nodes DNS – Cloudflare in my case – returns AAAA records
- Therefore DNS lookups within the cluster also return AAAA records
- AAAA targets cannot be reached from pods within in the cluster
- CoreDNS's config-map cannot be persistently overridden like this:

```
 template ANY AAAA {
  rcode NOERROR
}
```

How can this be solved?

**Comment by brandond** [comment]
I don't believe this is on K3s or coredns to resolve. If your client stack attempts to resolve and connect to AAAA records when not using ipv6, that is a problem with the client. What image are you experiencing this problem with?

**Comment by Privatecoder** [comment]
there used to be a setting to override the original settings by using  `*.override.start`, `*.override.fallthrough` and `*.override.end`.

`*.override.fallthrough` would have helped in this case..

**Comment by brandond** [comment]
Can you confirm that the pods don't have any ipv6 addresses configured? They shouldn't, but sometimes other things on the host can conflict with the CNI network configuration and cause undesired behavior. If the pod doesn't have an IPv6 address, the client stack should ignore AAAA records. Any other behavior is an error on the part of the client.

**Comment by Privatecoder** [comment]
they do have a link local IPv6 configured...

**Comment by brandond** [comment]
That should be fine. [RFC 6555](https://datatracker.ietf.org/doc/html/rfc6555) covers dual-stack client behavior; I can confirm that my tests work despite pods having an ipv6 link-local addresses assigned:
```console
root@ubuntu01:~# kubectl run -it --rm curl --image=curlimages/curl --restart=Never --command=true -- /bin/sh -c 'ip addr; nslookup -type=a clients.l.google.com; nslookup -type=aaaa clients.l.google.com; curl -vks http://clients.l.google.com/generate_204'
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if25: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether ba:5a:83:0c:07:4e brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.22/24 brd 10.42.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b85a:83ff:fe0c:74e/64 scope link
       valid_lft forever preferred_lft forever
Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:
Name:	clients.l.google.com
Address: 142.251.215.238

Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:
Name:	clients.l.google.com
Address: 2607:f8b0:400a:800::200e

*   Trying 142.251.215.238:80...
* Connected to clients.l.google.com (142.251.215.238) port 80 (#0)
> GET /generate_204 HTTP/1.1
> Host: clients.l.google.com
> User-Agent: curl/7.84.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Content-Length: 0
< Date: Tue, 12 Jul 2022 20:49:44 GMT
<
* Connection #0 to host clients.l.google.com left intact
pod "curl" deleted
```

**Comment by Privatecoder** [comment]
Thank you for testing this @brandond!

Having tested this on my end a couple of times does indeed also work as shown, however in node I also run into this only occasionally (`Error: connect ENETUNREACH`  because in that particular moment node tries to reach a AAAA target).

Maybe node is to blame here but as I am not running into the issue above all the time either, I might have to write a test for that and re-try this a couple of hundred times in order to make sure curl always tries to connect to the IPv4 response as in your example.

**Comment by Privatecoder** [comment]
Running nslookup on an effected pod sometimes returns an empty result:

```
/usr/src/app # nslookup www.google.com 10.43.0.10
Server:         10.43.0.10
Address:        10.43.0.10:53

```
then the next lookup is successful (the next 500 can be successful and then there can be 3-4-5 empty responses again)
```
/usr/src/app #  nslookup www.google.com 10.43.0.10
Server:         10.43.0.10
Address:        10.43.0.10:53


Non-authoritative answer:
Name:   www.google.com
Address: 216.58.212.132
```

**Comment by brandond** [comment]
Are there any errors in the coredns logs, or is the nslookup hanging? You'll probably need to use dnsutils or something like that; the busybox version of nslookup doesn't provide much to work with when troubleshooting.

https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by Privatecoder** [comment]
Nothing but `[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server`.

I don't get any timeouts or errors from nslookup and this only happens occasionally.

Thanks for the link, I will give that a try.

**Comment by Privatecoder** [comment]
Even with logging enabled I cannot seem to find any issues following all of the instructions from [this](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) link.
```
> kubectl get pods dnsutils
NAME       READY   STATUS    RESTARTS      AGE
dnsutils   1/1     Running   9 (49m ago)   9h
```
```
> kubectl exec -i -t dnsutils -- nslookup kubernetes.default
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.43.0.1
```
```
> kubectl exec -ti dnsutils -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5
```
```
> kubectl exec -i -t dnsutils -- nslookup kubernetes.default
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.43.0.1
```
```
> kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
NAME                       READY   STATUS    RESTARTS   AGE
coredns-55bfd77c45-cq847   1/1     Running   0          11h
coredns-55bfd77c45-fmc5z   1/1     Running   0          11h
coredns-55bfd77c45-gqvzm   1/1     Running   0          11h
```
```
> kubectl logs --namespace=kube-system -l k8s-app=kube-dns
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
....and many more of those
```
```
> kubectl get svc --namespace=kube-system
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
hcloud-csi-controller-metrics   ClusterIP   10.43.51.105   <none>        9189/TCP                 283d
hcloud-csi-node-metrics         ClusterIP   10.43.31.63    <none>        9189/TCP                 283d
kube-dns                        ClusterIP   10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP   283d
```
```
> kubectl get endpoints kube-dns --namespace=kube-system
NAME       ENDPOINTS                                                  AGE
kube-dns   10.244.0.19:53,10.244.1.31:53,10.244.7.25:53 + 6 more...   283d
```
```
> kubectl describe clusterrole system:coredns -n kube-system
Name:         system:coredns
...
PolicyRule:
  Resources                        Non-Resource URLs  Resource Names  Verbs
  ---------                        -----------------  --------------  -----
  endpoints                        []                 []              [list watch]
  namespaces                       []                 []              [list watch]
  pods                             []                 []              [list watch]
  services                         []                 []              [list watch]
  endpointslices.discovery.k8s.io  []                 []              [list watch]
  ```

All nodes are running Ubuntu 20.04 without `systemd-resolved`, i.e. regular `/etc/resolv.conf`
```
root@master2:~# cat /etc/resolv.conf
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Comment by brandond** [comment]
You might try using dig, it gives you much more information about the query and response than nslookup: `kubectl exec -i -t dnsutils -- dig +all a google.com aaaa google.com` 

See what that gives you back when you get no result for the A lookup.

**Comment by Privatecoder** [comment]
Thanks again! I think I might be onto something. `dig` throws an `Error from server: error dialing backend: EOF` which lead me to [this](https://cloud.ibm.com/docs/containers?topic=containers-ts_clis).

As I am using wireguard-native as flannel-backend I think this might be connected to wireguard!

**Comment by brandond** [comment]
That's not an error that dig would throw. That is an error from kubectl when trying to run the `exec` command. Rather than running a bunch of exec commands in a loop (and overloading the apiserver with exec requests), you might run the actual dig command in a loop within the exec command: `kubectl exec -i -t dnsutils -- sh -c 'while true; do dig +all a google.com aaaa google.com; sleep 1; done'`

**Comment by Privatecoder** [comment]
I am running one Cluster with Rancher which manages another Cluster – both on v1.23.7+k3s1. The imported Cluster was using `wireguard-native` as flannel-backend right from the start, the other was created using the old / deprecated `wireguard`-hacky-solution.

Even though the `Error from server: error dialing backend: EOF` presumably had nothing to do with the original issue – as you wrote – I switched the Cluster config to `wireguard-native` yesterday and cannot find any more issues in the logs for the  past 9 hours or so.

I will keep an eye on this and report back.

**Comment by Privatecoder** [comment]
I will close this issue tomorrow if there are no more errors (haven't had any more since switching to wireguard-native), however this keeps being a pretty weird issue:

- All nodes were up and healthy in both the _Master_-Cluster and the managed / imported through Rancher-Cluster
- nslookup in affected Pods (on the _Master_-Cluster) would ~95% of the time return IPv4 and IPv6 addresses, i.e. everything would work as expected
- In ~5% if the time I would receive an empty response or an IPv6 only response, i.e. I would receive `Error: connect ENETUNREACH` or `getaddrinfo ENOTFOUND` errors in nodejs-scripts trying to resolve FQDNs.
- Disabling IPv6 responses in CoreDNS's config-map (as per the first post) would lead to empty responses, i.e. `getaddrinfo ENOTFOUND` errors only
- I did not _actively_ encounter this issue on the imported through Rancher-Cluster which has been initially setup with `wireguard-native` as flannel-backend option (however I can't say this for sure plus it is on a different Hosting-Provider with a slightly different setup)
- After changing `wireguard` to `wireguard-native` as flannel-backend on the affected Cluster however the issue seems to have disappeared

**Comment by Privatecoder** [comment]
closing as after 1000+ successful resolves this seems to be fixed.

**Comment by brandond** [comment]
It kinda sounds like the legacy wireguard setup was dropping some portion of udp DNS traffic.
