### ISSUE TITLE
k3s server --rootless, pods/......./volumes does not exist

### ISSUE THREAD

**Issue by michielhemme** [k3s-io/k3s#585]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**
During the startup of the rootless environment (k3s server --rootless) I get the following warnings.: 
W0628 07:39:07.512658   10690 pod_container_deletor.go:75] Container "7d9e65ac7e460e026a171739d5bed9885bdf863c0963b2aa8454e8a87b90ba00" not found in pod's containers
W0628 07:39:07.512830   10690 pod_container_deletor.go:75] Container "8555af280505734254bed8ecd9fbadef3b25a1d8f7bccfd054cef9c33fd963d2" not found in pod's containers
W0628 07:39:07.512931   10690 pod_container_deletor.go:75] Container "fb0e6303b1f6d22e2538cb46b39e549aac3c106ea912f296ca9e430216018efb" not found in pod's containers
W0628 07:39:07.513013   10690 pod_container_deletor.go:75] Container "2d489f6bb6a4e18488ae22983d3d34562abd62f1881c3cd4f96d6da74f1730a4" not found in pod's containers
W0628 07:39:07.513116   10690 pod_container_deletor.go:75] Container "0975fab5cb68f1232ffd549b9f9f839dee4278e3efd64cc517f90949f5c9f997" not found in pod's containers
W0628 07:39:07.513212   10690 pod_container_deletor.go:75] Container "3ab577cd5eadf47e3ceda9fab29d3d7cd57f9ac9e33153d0b21666eb60e2982d" not found in pod's containers
W0628 07:39:07.513304   10690 pod_container_deletor.go:75] Container "8e41a364da1f312b4d7c108bec37b701aa28b9f11d2601119ff0efc2a8378315" not found in pod's containers
W0628 07:39:07.513397   10690 pod_container_deletor.go:75] Container "897522b8b088f3fe30277a99a5bd3b17d115f26ab1ce782fa4830872a3ef7b0c" not found in pod's containers
W0628 07:39:07.513511   10690 pod_container_deletor.go:75] Container "6810715bae541f95d34d456ed4993f739fe41c30195de6f8ad2e729ce132d796" not found in pod's containers
W0628 07:39:07.513603   10690 pod_container_deletor.go:75] Container "cdd5179a818446bec1cb16a0a8bd51bea6a23fd602e9ba5c7258a55902a31403" not found in pod's containers

Later in the process I get these messages keep popping up:
W0628 07:39:39.117576   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f4e9bde-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:39.117714   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f5f7cf5-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:39.117802   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/479f651b-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:41.138070   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f4e9bde-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:41.138250   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f5f7cf5-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:41.138595   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/479f651b-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:43.118508   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f4e9bde-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:43.118677   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f5f7cf5-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:43.118797   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/479f651b-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:45.118593   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f4e9bde-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:45.118762   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/4f5f7cf5-9976-11e9-880a-6e457e4815bf/volumes" does not exist
W0628 07:39:45.121306   10690 kubelet_getters.go:279] Path "/home/ubuntu/.rancher/k3s/agent/kubelet/pods/479f651b-9976-11e9-880a-6e457e4815bf/volumes" does not exist

When browsing /home/ubuntu/k3s/agent/kubelet/pods and preforming a LS on it I only get the following folders:
drwxr-x--- 5 ubuntu ubuntu 4096 Jun 28 07:39 ac6447b2-9976-11e9-aa7e-5e5ade8037b8
drwxr-x--- 5 ubuntu ubuntu 4096 Jun 28 07:39 b4888db2-9976-11e9-aa7e-5e5ade8037b8
drwxr-x--- 5 ubuntu ubuntu 4096 Jun 28 07:39 b49e28eb-9976-11e9-aa7e-5e5ade8037b8

**To Reproduce**
1. Install the required files on the system.
2. kill the current services with /usr/local/bin/k3s-killall.sh
3. Execute k3s server --rootless

**Expected behavior**
A working k3s rootless cluster.

**Additional context**
Ubuntu 18.04.2 LTS - Fully updated (28-JUN-2019)
4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brandond** [comment]
Closing due to age. Rootless should be working properly int newer releases.
