### ISSUE TITLE
systemd cgroup driver detection does not work on servers

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5850]
It looks like this was regressed by https://github.com/k3s-io/k3s/commit/a9b5a1933fb. On servers, the `NOTIFY_SOCKET` environment variable gets unset, which prevents the cgroup detection code from detecting that it is running under systemd.

_Originally posted by @brandond in https://github.com/k3s-io/k3s/issues/5454#issuecomment-1182605398_

**Comment by est-suse** [comment]
![image](https://user-images.githubusercontent.com/106194120/185704296-8ab8b948-493b-45fa-bafd-07fb334d355f.png)
