### ISSUE TITLE
Incompatible CNI versions error

### ISSUE THREAD

**Issue by simsicon** [k3s-io/k3s#5854]
**Environmental Info:**
K3s Version: 
Before upgrade: v1.23.4+k3s1
Tried upgraded version: stable v1.23.8+k3s1 & latest v1.24.2+k3s2

Node(s) CPU architecture, OS, and Version: 
Linux node1 5.10.0-11-amd64 # 1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

Cluster Configuration:
standalone

**Describe the bug:**
After upgrading to the stable or latest, the pods produce "Incompatible CNI versions error", as described in this [doc](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors/#incompatible-cni-versions-error)

I can not fix the error as the doc suggests, I have checked the embedded flannel and containerd already are the latest, I have no idea how this problem happened, after hours battle, I rolled back to v1.23.4+k3s1 and it's back to normal.

**Steps To Reproduce:**
- Upgrade K3s from v1.23.4+k3s1 to v1.23.8+k3s1 

**Expected behavior:**
Upgrade seamlessly without error

**Actual behavior:**
Incompatible CNI versions error

**Additional context / logs:**

**Comment by simsicon** [comment]
Since rolling back k3s fixed this issue, I think maybe there's an internal setting maybe the trigger to the issue?

**Comment by brandond** [comment]
If you're using the containerd that comes with k3s, or using a recent version of docker/containerd, this should not be an issue. The only thing I can think of is that you're using an out of date version of containerd or docker. Are you using the containerd packaged with k3s, or are you using your own docker/containerd runtime via the --docker or --container-runtime-endpoint flags?

**Comment by simsicon** [comment]
> 

Hi,  for now I can not afford to upgrade it again to get the output you asked, but indeed there's something not quite right:

```bash
$ /data/k3s/data/current/bin/containerd --version
containerd github.com/k3s-io/containerd v1.5.13-k3s1

$ kubectl get node -o wide
NAME    STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
node1   Ready    control-plane,master   170d   v1.23.4+k3s1   192.168.10.88   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-11-amd64   containerd://1.5.9-k3s1
```

the containerd version doesn't match.

And I found that
```bash
$ ls -lah /data/k3s/data/current
lrwxrwxrwx 1 root root   79 Jul 13 13:54 current -> /data/k3s/data/c9a6d90256a51820d938c023e90f73b9a423b3a7f5775cc6b1568a49d0fd5028
```
but
```bash
$ k3s check-config
Verifying binaries in /data/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917/bin:
- sha256sum: good
- links: good

System:
- /data/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917/bin/aux/iptables: unknown version:
- swap: should be disabled
- routes: ok
```
indicates that k3s actually using `/data/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917`


we can confirm that its containerd version matches `kubectl get node -o wide` outputs
```bash
$ /data/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917/bin/containerd --version
containerd github.com/k3s-io/containerd v1.5.9-k3s1
```

I think the binary is new installed rather than legacy, but why this happens?
```bash
$ ls -lah `which k3s`
-rwxr-xr-x 1 root root 60M Jul 13 14:05 /usr/local/bin/k3s
```

Thanks for your reply and information.

**Comment by brandond** [comment]
Can you provide the output of `kubectl get node -o yaml` as well as any other relevant information about the container runtime or CNI in use on your node? Do you have OS docker or containerd packages installed on the node?

**Comment by simsicon** [comment]
> Can you provide the output of `kubectl get node -o yaml` as well as any other relevant information about the container runtime or CNI in use on your node? Do you have OS docker or containerd packages installed on the node?

I am a little bit cautious about the minimal dependencies of the host OS, so I dont think there is OS docker or containerd packages install, there's some outout

```bash
$ sudo apt list --installed docker
Listing... Done
$ sudo apt list --installed containerd
Listing... Done
$ snap list
Name     Version    Rev    Tracking       Publisher     Notes
certbot  1.29.0     2192   latest/stable  certbot-eff✓  classic
core     16-2.56.2  13425  latest/stable  canonical✓    core
core18   20220428   2409   latest/stable  canonical✓    base
core20   20220527   1518   latest/stable  canonical✓    base
procs    v0.12.1    820    latest/stable  dalance       -

```

and `kubectl get node -o yaml` output

```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      csi.volume.kubernetes.io/nodeid: '{"driver.longhorn.io":"node1"}'
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"c6:9a:35:18:e0:84"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 192.168.10.88
      k3s.io/hostname: node1
      k3s.io/internal-ip: 192.168.10.88
      k3s.io/node-args: '["server","--data-dir","/data/k3s","--kubelet-arg","max-pods=250"]'
      k3s.io/node-config-hash: NK73Q6B6L2U5WBGCODMDYBTZ66OOUAJSCC7PC7FO3YUPQTVDDB5A====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/data/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917"}'
      management.cattle.io/pod-limits: '{"cpu":"35","memory":"86700Mi"}'
      management.cattle.io/pod-requests: '{"cpu":"14600m","memory":"25236Mi","pods":"86"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2022-01-24T13:45:10Z"
    finalizers:
    - wrangler.cattle.io/node
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      egress.k3s.io/cluster: "true"
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: node1
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
      node-role.kubernetes.io/master: "true"
      node.kubernetes.io/instance-type: k3s
    name: node1
    resourceVersion: "56777127"
    uid: bff5f297-0a7c-40e4-b156-ef6743c6369c
```

Now I think maybe the problem is in install scripts that I upgraded k3s with?

**Comment by brandond** [comment]
I'm unable to replicate this. How did you install and upgrade K3s?
```console
root@ubuntu01:~# curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.4+k3s1 sh -s - server --token=token
[INFO]  Using v1.23.4+k3s1 as release
...

root@ubuntu01:~# kubectl get node -o wide
NAME                 STATUS   ROLES                  AGE     VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
ubuntu01.lan.khaus   Ready    control-plane,master   2m33s   v1.23.4+k3s1   10.0.1.147    <none>        Ubuntu 21.10   5.14.13-051413-generic   containerd://1.5.9-k3s1

root@ubuntu01:~# curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.8+k3s1 sh -s - server --token=token
[INFO]  Using v1.23.8+k3s1 as release
...

root@ubuntu01:~# kubectl get node -o wide
NAME                 STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
ubuntu01.lan.khaus   Ready    control-plane,master   11m   v1.23.8+k3s1   10.0.1.147    <none>        Ubuntu 21.10   5.14.13-051413-generic   containerd://1.5.13-k3s1

root@ubuntu01:~# kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-6c79684f77-59vwh   1/1     Running     0          14m
kube-system   metrics-server-7cd5fcb6b7-drvvm           1/1     Running     0          14m
kube-system   coredns-d76bd69b-qxfzs                    1/1     Running     0          10m
kube-system   svclb-traefik-5c5c99aa-xrn5v              2/2     Running     0          10m
kube-system   helm-install-traefik-crd-7xc8l            0/1     Completed   0          10m
kube-system   helm-install-traefik-qvr5m                0/1     Completed   0          10m
kube-system   traefik-df4ff85d6-2sq9b                   1/1     Running     0          10m
```

I think the bit with `/data/k3s/data/current` not pointing to the actual current data dir might be a bug; that link is only updated when the data dir is extracted out. When you rolled back the old data dir still existed and therefore the link wasn't updated to point back at the old dir.

Since I can't reproduce your issue, I'm not sure how to help until you get another chance to attempt the upgrade and collect more information.

**Comment by simsicon** [comment]
> I'm unable to replicate this. How did you install and upgrade K3s?
> 
> ```
> root@ubuntu01:~# curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.4+k3s1 sh -s - server --token=token
> [INFO]  Using v1.23.4+k3s1 as release
> ...
> 
> root@ubuntu01:~# kubectl get node -o wide
> NAME                 STATUS   ROLES                  AGE     VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
> ubuntu01.lan.khaus   Ready    control-plane,master   2m33s   v1.23.4+k3s1   10.0.1.147    <none>        Ubuntu 21.10   5.14.13-051413-generic   containerd://1.5.9-k3s1
> 
> root@ubuntu01:~# kubectl get pods -A
> NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
> kube-system   local-path-provisioner-6c79684f77-59vwh   1/1     Running     0          8m53s
> kube-system   metrics-server-7cd5fcb6b7-drvvm           1/1     Running     0          8m53s
> kube-system   coredns-d76bd69b-qxfzs                    1/1     Running     0          5m39s
> kube-system   svclb-traefik-5c5c99aa-xrn5v              2/2     Running     0          5m39s
> kube-system   helm-install-traefik-crd-7xc8l            0/1     Completed   0          5m39s
> kube-system   helm-install-traefik-qvr5m                0/1     Completed   0          5m39s
> kube-system   traefik-df4ff85d6-2sq9b                   1/1     Running     0          5m25s
> 
> root@ubuntu01:~# curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.8+k3s1 sh -s - server --token=token
> [INFO]  Using v1.23.8+k3s1 as release
> ...
> 
> root@ubuntu01:~# kubectl get node -o wide
> NAME                 STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
> ubuntu01.lan.khaus   Ready    control-plane,master   11m   v1.23.8+k3s1   10.0.1.147    <none>        Ubuntu 21.10   5.14.13-051413-generic   containerd://1.5.13-k3s1
> 
> root@ubuntu01:~# kubectl get pods -A
> NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
> kube-system   local-path-provisioner-6c79684f77-59vwh   1/1     Running     0          14m
> kube-system   metrics-server-7cd5fcb6b7-drvvm           1/1     Running     0          14m
> kube-system   coredns-d76bd69b-qxfzs                    1/1     Running     0          10m
> kube-system   svclb-traefik-5c5c99aa-xrn5v              2/2     Running     0          10m
> kube-system   helm-install-traefik-crd-7xc8l            0/1     Completed   0          10m
> kube-system   helm-install-traefik-qvr5m                0/1     Completed   0          10m
> kube-system   traefik-df4ff85d6-2sq9b                   1/1     Running     0          10m
> ```
> 
> I think the bit with `/data/k3s/data/current` not pointing to the actual current data dir might be a bug; that link is only updated when the data dir is extracted out. When you rolled back the old data dir still existed and therefore the link wasn't updated to point back at the old dir.
> 
> Since I can't reproduce your issue, I'm not sure how to help until you get another chance to attempt the upgrade and collect more information.

I downloaded the install script, then run `bash install.sh` to it.

Thanks for your help, I will try to upgrade it again in this weekend, with the new information I think I could find more clues.

**Comment by simsicon** [comment]
@brandond  I am upgrading it now, I have upgraded to `v1.24.2+k3s2`, ran `kill-all script` then `systemctl start k3s`, now the latest is `/data/k3s/data/f4431393712ffbc38bd97607e1f813faef14e378c15e53ea07e11c6bbe9a634f/`, and I manually deleted the other legacy directions and soft link the current and prev to the `f4431`

pod output is like this, seems k3s is keeping looking for a legacy data dir

```bash
Warning  FailedCreatePodSandBox  26s (x13 over 2m56s)   kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Un │
│ known desc = failed to setup network for sandbox "9d35f20a35bf4f0433f48d2705d9cef133d163bd9be0a91960ac2aa0d3f3a82c": plugin type="flannel" failed (add): failed │
│  to find plugin "flannel" in path [/data/k3s/data/2e877cf4762c3c7df37cc556de3e08890fbf450914bb3ec042ad4f36b5a2413a/bin]
```

**Comment by simsicon** [comment]
some outputs
```bash
$ /data/k3s/data/current/bin/containerd --version
containerd github.com/k3s-io/containerd v1.6.6-k3s1

$ /data/k3s/data/current/bin/k3s --version
k3s version v1.24.2+k3s2 (a2372602)
go version go1.18.1

$ kubectl get node -o wide
NAME    STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
node1   Ready    control-plane,master   172d   v1.24.2+k3s2   192.168.10.88   <none>        Debian GNU/Linux 11 (bullseye)   5.10.0-11-amd64   containerd://1.6.6-k3s1

$ k3s check-config

Verifying binaries in /data/k3s/data/f4431393712ffbc38bd97607e1f813faef14e378c15e53ea07e11c6bbe9a634f/bin:
- sha256sum: good
- links: good

System:
- /data/k3s/data/f4431393712ffbc38bd97607e1f813faef14e378c15e53ea07e11c6bbe9a634f/bin/aux/iptables: unknown version:
- swap: should be disabled
- routes: ok
```

**Comment by simsicon** [comment]
My workaround is `cp -a /data/k3s/data/f44313 /data/k3s/data/2e877cf`, it solves the crisis, but the reason remains mystery...😂

**Comment by brandond** [comment]
What do you get from
* `echo $PATH` 
* `which k3s`
* `which kubectl`

**Comment by simsicon** [comment]
> 

It's universal, all of the pods getting the error

```bash
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
$ which k3s
/usr/local/bin/k3s
$ which kubectl
/usr/local/bin/kubectl
```

**Comment by simsicon** [comment]
> What do get from `grep bin_dir /var/lib/rancher/k3s/agent/etc/containerd/config.toml` ? Have you by any chance customized your containerd config by creating a `config.toml.tmpl` in that same directory?

You are just amazing.

Yes I have customized the containerd config by creating `config.toml.tmpl` to modify the `cri registry`, and `bin_dir` is set to `/data/k3s/data/2e877cf` in this config template.

Should I just change the hashed directory to `current dir` in the `config.toml.tmpl`?

**Comment by brandond** [comment]
Hmm, well that's certainly doing more to k3s than just downloading the install script and running it.

If you provide your own containerd config template, you're expected to actually keep it a template, not just copy over the file from a previously rendered template. You can find the raw template here:
https://github.com/k3s-io/k3s/blob/990ba0e88c90f8ed8b50e0ccd375937b841b176e/pkg/agent/templates/templates_linux.go#L11-L126

Replace your template with that, customizing whatever it was that you'd tried to change, WITHOUT removing the variables that make it portable as k3s as upgraded.

**Comment by simsicon** [comment]
OK, thank you so much, this issue is closed.
