### ISSUE TITLE
K3S server wont start with "context deadline exceeded"

### ISSUE THREAD

**Issue by CiraciNicolo** [k3s-io/k3s#5855]
**Environmental Info:**
K3s Version: 

```
k3s version v1.24.2+k3s2 (a2372602)
go version go1.18.
```

Node(s) CPU architecture, OS, and Version: 
```
Linux hostname 3.10.0-1160.62.1.el7.centos.plus.x86_64 #1 SMP Wed Apr 6 18:21:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server + 2 agents

**Describe the bug:**

K3S server won't start with "FATA[0025] apiserver exited: context deadline exceeded" error, logs are not helpful. Older issues suggest to vacuum the SQLITE database but it didnt help either.

Also starting with the debug flag, I get a lot of:

```
INFO[0016] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error
INFO[0056] Cluster-Http-Server 2022/07/13 10:28:03 http: TLS handshake error from 127.0.0.1:48134: remote error: tls: bad certificate
```

**Steps To Reproduce:**
Pods started to become stale and wasn't able to schedule more pods, restarted K3S to check startup logs. Deleting pods or other resource don't commit actions (aka the resource are still shown with kubectl get)

**Expected behavior:**
Able to delete resource

**Actual behavior:**
K3S won't start

**Comment by brandond** [comment]
Can you post the **complete** k3s server logs? `journalctl -u k3s --no-pager &> k3s.log`

**Comment by CiraciNicolo** [comment]
Hi! 

We investigated more and we think our SQLITE database is corrupted; we migrated to etcd and recovered our CRD so we can recover the state (our workloads are operator based). Closing this for now.
