### ISSUE TITLE
CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#5856]
**Environmental Info:**
K3s Version: v1.21.7+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux k3s-prod-master1 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux k3s-prod-master2 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux k3s-prod-master3 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux k3s-prod-node1 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux k3s-prod-node2 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux k3s-prod-node3 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3server,3agent

**Describe the bug:**

after agent join the server node, it shows error like this
```
Jul 13 16:49:37 k3s-prod-node1 k3s[18336]: time="2022-07-13T16:49:37.252325400+08:00" level=error msg="CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": x509: certificate signed by unknown authority"
```

**Steps To Reproduce:**

- Installed K3s: 
server node
```
export K3S_CLUSTER_INIT=true
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export INSTALL_K3S_VERSION=v1.21.7+k3s1
export INSTALL_K3S_EXEC="server \
--tls-san xxx \
--kubelet-arg max-pods=300 \
--kube-apiserver-arg service-node-port-range=30000-40000"
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh |INSTALL_K3S_MIRROR=cn sh -
```
agent node
```
export K3S_TOKEN="xxx"
export K3S_URL="https://xxx:6443"
export INSTALL_K3S_VERSION=v1.21.7+k3s1
export INSTALL_K3S_EXEC="agent \
--kubelet-arg max-pods=300"
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh |INSTALL_K3S_MIRROR=cn sh -
```

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

i made the cert by myself(use create_self-signed-cert.sh from rancherlab)
and it used in loadbalance(Layer 7 loadbalancing)
is the error related to this?

**Backporting**

- [ ] Needs backporting to older releases

**Comment by wang-xiaowu** [comment]
ok, thanks
plus, is there any method that i can continue using the ssl on the loadbalancer
i did not see any information about client use mutual tls to auth with the server use ssl

**Comment by wang-xiaowu** [comment]
> > i made the cert by myself(use create_self-signed-cert.sh from rancherlab)
> > and it used in loadbalance(Layer 7 loadbalancing)
> > is the error related to this?
> 
> Yes, that is the problem. You should not configure SSL offload on the load balancer that sits in front of the K3s servers. Clients use Mutual TLS to authenticate with the server, so TLS must be passed through the load-balancer.

sorry, after i configured the lb like this,
```
stream {
      upstream k3s {
              least_conn;
              server 192.168.56.100:6443  max_fails=3 fail_timeout=5s;
      }
      server {
         listen 6443;
         proxy_pass k3s;
      }
}
```

 it shows error like this
```
Jul 14 16:08:28 k3s-node2 k3s[4603]: time="2022-07-14T16:08:28.338152366+08:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": EOF"
```

or this
```
Jul 14 15:04:14 k3s-prod-node1 k3s[8290]: time="2022-07-14T15:04:14.452008772+08:00" level=error msg="token CA hash does not match the Cluster CA certificate hash: 075b4ee8d38f269fe385fb892c3ea259b0ae152317d6c...c9f6c8b141bf530"
```

i am using etcd, not extra datastore

**Comment by brandond** [comment]
You need to turn off all http and tls termination on the load-balancer. If you can't put it into pure TCP mode, then it is not suitable for use in front of the k3s control-plane. You might consider using a DNS alias that points to active K3s server nodes instead of a load-balancer.

**Comment by wang-xiaowu** [comment]
> 

thanks for your answer
but i have three k3s server

**Comment by wang-xiaowu** [comment]
> You need to turn off all http and tls termination on the load-balancer. If you can't put it into pure TCP mode, then it is not suitable for use in front of the k3s control-plane. You might consider using a DNS alias that points to active K3s server nodes instead of a load-balancer.

thanks for your answer
but i have three k3s server

**Comment by wang-xiaowu** [comment]
> You need to turn off all http and tls termination on the load-balancer. If you can't put it into pure TCP mode, then it is not suitable for use in front of the k3s control-plane. You might consider using a DNS alias that points to active K3s server nodes instead of a load-balancer.

ok, thanks for your answer
i install another nginx only work for loadbalancing k3s server on the same machine, it's working
