### ISSUE TITLE
K3S Airgapped deployments fail randomly

### ISSUE THREAD

**Issue by BlackTurtle123** [k3s-io/k3s#586]
**Describe the bug**
When running k3s airgapped, the deployments randomly can't find the airgapped tar's.
During startup from k3's we can see that tar are loaded in. When checking the tar's for versions we also confirm that the version is correct, however at random moments or after reboots, the deployment would crash/restart and not find the image anymore.
This happens with different images at different times, on the same setup, so sometimes image 'abc' isnt found and a few hours later 'abc' is found, but 'bcd' isn't

**To Reproduce**
Install k3s airgapped. Run deployments with these airgapped images.

**Expected behavior**
Images which are loaded in the airgapped way and do match the image version, should always load airgapped. And not with random non airgapped fails.

**Comment by erikwilson** [comment]
Thanks for reporting this! Please be sure to include the version of k3s as that is linked to the dependencies we use. If you are able please try with https://github.com/rancher/k3s/releases/tag/v0.7.0-rc5, if it is still happening k3s and containerd logs might be helpful.

**Comment by BlackTurtle123** [comment]
For now the behavior doesn't seem to show up again.

**Comment by brandond** [comment]
Closing due to age.
