### ISSUE TITLE
everything works well but the rancher server is not up

### ISSUE THREAD

**Issue by johnyoungatwork** [k3s-io/k3s#5863]
hi, i am a beginner in rancher and k3s. I was stucked in getting the rancher server up.
**Environmental Info:**
K3s Version: v1.23.8+k3s2

Node(s) CPU architecture, OS, and Version:  I use a external nginx load balancer and DNS to achieve HA rancher and k3s.

Cluster Configuration: two server nodes and 3 agent nodes

**Describe the bug:**
When I logged into the nginx. It shows
2022/07/14 03:03:21 [error] 1073#1073: *1682 no live upstreams while connecting to upstream, client: 192.168.1.35, server: 0.0.0.0:443, upstream: "rancher_servers_https", bytes from/to client:0/0, bytes from/to upstream:0/0
It seems the rancher server is not up. However, rancher rolled out sucessfully.
![image](https://user-images.githubusercontent.com/108930388/178889428-8ab82ce0-2183-4637-94e9-6b0e7bd756ff.png)
status of the deployment:
![image](https://user-images.githubusercontent.com/108930388/178889602-165060d6-1c44-4eba-9d6a-c690eb63a773.png)
All the nodes are in ready state.
![image](https://user-images.githubusercontent.com/108930388/178889997-fc98dbff-fda2-4a2b-aedf-d5f62bddf329.png)

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**
I will be directed to the rancher page with the dns name.

**Actual behavior:**
The site cant be reached.

**Additional context / logs:**

The nginx conf:
```
load_module /usr/lib/nginx/modules/ngx_stream_module.so;
worker_processes 4;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;
events {
}
stream {
    # k3
    upstream k3s_servers {
    server 192.168.1.53:6443;
    server 192.168.1.54:6443;
    }
    server {
    listen 6443;
    proxy_pass k3s_servers;
    }
    # rancher
    upstream rancher_servers_http{
    least_conn;
    server 192.168.1.53:80;
    server 192.168.1.54:80;
    }
    upstream rancher_servers_https{
    least_conn;
    server 192.168.1.53:443;
    server 192.168.1.54:443;
    }
    server{
    listen 0.0.0.0:80;
    proxy_pass rancher_servers_http;
    }
    server{
    listen 0.0.0.0:443;
    proxy_pass rancher_servers_https;
    }
}
```
status of the pods:
![image](https://user-images.githubusercontent.com/108930388/178890842-2207f38b-5c8a-4ed9-9a43-c400f23ca970.png)

[test.txt](https://github.com/k3s-io/k3s/files/9108118/test.txt)

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Can you provide more information on how you build this cluster and what else you've installed? All you mention is installing rancher, but it looks like you've installed metallb without disabling the built-in servicelb service controller, and have deployed ingress-nginx in place of traefik?

**Comment by johnyoungatwork** [comment]
I build the cluster with a external database and a an external load balancer nginx to direct the trafic to the server nodes. When i installed the metallb, and ingress-ingress in place of traefik.

**Comment by brandond** [comment]
If you're going to install metallb, you need to disable servicelb, otherwise you have competing loadbalancer controllers. If disabling servicelb doesn't do it (and you may need to delete and recreate any loadbalancer services to straighten things out), then you're probably on your own to figure out if the problem is metallb or ingress-nginx.

**Comment by johnyoungatwork** [comment]
I will try it out later! Huge thx!
