### ISSUE TITLE
help!! emergency!! metrics not available yet

### ISSUE THREAD

**Issue by zzps** [k3s-io/k3s#5865]
K3s Version: 
v1.21.0+k3s1

Node(s) CPU architecture, OS, and Version: 
centos7.8

Cluster Configuration:
2server+2agent

**Describe the bug:**
after k3s run 1 year, today the woker nodes status become unready of the cluster ,and my app are all crashed!!! 
I operate the command " k3s agent --token mytoken -s myserver"  and the worker nodes status become ready. but 
kubectl top nodes => metrics not available yet ; kubectl top pods => Metrics not available for pod...
when I command "kubectl logs metrics-server-86cbb8457f-dtgpt -n kube-system" .it show info like
 "Failed to list *v1.Node: Unauthorized" ; " request failed - "401 Unauthorized", response: "Unauthorized"".
the important tips is: the cluster run 1 year precisely .  
emergency!!!help!!!

![1E3C8540-8E25-4a9e-877A-FF8E5953C790](https://user-images.githubusercontent.com/33255974/178952096-38e41419-85f4-43d3-8ab3-bfe60052dab0.png)
![87FB1DE3-80DC-47a6-9871-1296563022FC](https://user-images.githubusercontent.com/33255974/178952363-0e069783-36d0-4617-a4d9-1a0a964ce2b5.png)

**Comment by brandond** [comment]
Kubernetes 1.21 is end of life. Are you able to upgrade your cluster to a newer release, and confirm that you see the same issue there?

**Comment by zzps** [comment]
> Kubernetes 1.21 is end of life. Are you able to upgrade your cluster to a newer release, and confirm that you see the same issue there?

it is really a big risk to upgrade because it is a product env and no backup

**Comment by brandond** [comment]
Have you tried just deleting the metrics-server pod and letting the deployment recreate it?

**Comment by zzps** [comment]
> 

no, I do not know how to delete metrics-server pod and recreate it. and I  can not find relation doc on website https://docs.rancher.cn/docs/k3s

**Comment by zzps** [comment]
> Have you tried just deleting the metrics-server pod and letting the deployment recreate it?

no, I do not know how to delete metrics-server pod and recreate it. and I can not find relation doc on website https://docs.rancher.cn/docs/k3s

**Comment by brandond** [comment]
You know how to list and delete pods using kubectl, right? This is just basic Kubernetes stuff, nothing specific to k3s.

**Comment by zzps** [comment]
> pods

ok

**Comment by zzps** [comment]
> You know how to list and delete pods using kubectl, right? This is just basic Kubernetes stuff, nothing specific to k3s.



> You know how to list and delete pods using kubectl, right? This is just basic Kubernetes stuff, nothing specific to k3s.

ok
