### ISSUE TITLE
Avoid conflicts with host network

### ISSUE THREAD

**Issue by tdewitt** [k3s-io/k3s#588]
Thanks for helping us to improve k3s! We welcome all feature requests. At this stage, we are also looking for help in testing/QAing issues. Once we've addressed your feature request, we'll ping you in the comments to see if you can verify the change. We'll give you details on what version can be used to test the change. Additionally, if you are interested in testing other fixes or feature requests that you ***didn't*** report, look for the issues with the status/to-test label. You can pick any of these up for verification. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
My home network (10.42.0.0/23) collides with the default cluster CIDR (10.42.0.0/16).  This causes the master node to become non responsive when the k3s server starts.  Based on conversations with @erikwilson, this is mostly likely caused by iptables changes for the k3s network.

**Describe the solution you'd like**
Possible solutions:
1. inspect host network and warn on possible collisions with network interface or existing routes
1. inspect host network and select default network that won't collide with network interface or existing routes
1. update ansible roles (in contrib) to enable setting these networks via variables
1. Put a big loud note in the README.md that indicates the default CIDRs and the impact over overlap

**Describe alternatives you've considered**
I manually edited the systemd service file to set --cluster-cidr and --service-cidr to different subnets.  This works.

**Additional context**
This is a hard problem to debug, when running headless.  The behavior could indicate any number of failure modes.  The first thing the we chased was memory because that felt likely.  It wasn't until we started talking about networking that it became obvious that a network overlap was a likely culprit.

The only mention of using the 10.4[2,3].0.0/16 in the README.md is in a log line under "Running server".  If you look through the code, you'll see it in a couple places but that's it.

**NOTE:** Thanks again @erikwilson for all the help!

**Comment by caroline-suse-rancher** [comment]
Closing due to age
