### ISSUE TITLE
Change k3s master node IP?

### ISSUE THREAD

**Issue by vincentmli** [k3s-io/k3s#5880]
Sorry if this has been asked and answered, I could not find it from issue reports or google

**Is your feature request related to a problem? Please describe.**
I ran k3s with reserved IP in lab that has internet access, but IP with Internet access is limited so I want to change the
k3s master node to internal IP that is behind corporate proxy, I could not find documentation or issue reports to support this or procedure to workaround this

**Describe the solution you'd like**
if k3s support changing master node ip, please provide documents on how to do it
if k3s does not support changing master node ip, please support it if possible ?

**Additional context**

k3s is embedded in some commercial product that these commercial customers might want this feature 

**Backporting**

- [x] Needs backporting to older releases

**Comment by brandond** [comment]
Changing node IPs after the fact is not well supported by Kubernetes. Are you using the embedded etcd, or just sqlite? Do you have any agents joined to the server?

**Comment by vincentmli** [comment]
I am using sqlite and this is just a single node k3s deployment, the commercial product from my employer (F5) uses single node k3s deployment

**Comment by brandond** [comment]
In that case just using `kubectl delete node` to remove the node, and then restarting the service, should do it.

**Comment by vincentmli** [comment]
nice, I noticed that as long as the new IP I changed has working network connectivity, simply reboot the k3s single node, after reboot, all pod started working, it did not work previously because the new IP I changed actually did not have network connectivity because Ubuntu 20.04 network configuration issue

**Comment by vincentmli** [comment]
> In that case just using `kubectl delete node` to remove the node, and then restarting the service, should do it. Although if your employer is building a commercial product around K3s you might suggest they reach out to someone at suse about the partner program so that you're not left relying on best-effort community support.

I understand that. I am actually not the people who develop the commercial product with k3s so I have no saying on that, I started using k3s way before my employer does, I use k3s mainly for my OSS contribution to other projects :-).

**Comment by cjp1016** [comment]
Ubuntu 20.04.5 LTS  INTERNAL-IP 和实际IP不符合
- kubectl delete node [nodename]  
- systemctl restart k3s
