### ISSUE TITLE
http: TLS handshake error from 10.42.3.0:42146: EOF from the pod/cert-manager-webhook after the installion of rancher

### ISSUE THREAD

**Issue by johnyoungatwork** [k3s-io/k3s#5884]
Hi, I am new to k3s and rancher, please point it out if you found any mistake in the installation of k3s and rancher. I follow the official [website](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/#ingress-controller) to install rancher and k3s. Which pods do i need to look into for debugging the issue? Your help will be much appreciated!!
**Environmental Info:**
K3s Version: v1.23.8+k3s2

Node(s) CPU architecture, OS, and Version:  I used an external database, nginx load balancer and DNS to build a k3s cluster.

Cluster Configuration: 2 servers, 2 agents

> root@m2:~# kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy

**Describe the bug:**
Everything seems working well after the roll out of rancher. However, i was not able to connect to the rancher web UI. The external nginx load balancer is working well, so i started to debug the pod/cert-manager-webhook, I saw 

> root@m1:~# kubectl -n cert-manager logs pod/cert-manager-webhook-57c994b6b9-4h8hk
I0720 07:56:04.037910       1 feature_gate.go:245] feature gates: &{map[]}
W0720 07:56:04.037968       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0720 07:56:04.053918       1 webhook.go:129] cert-manager "msg"="using dynamic certificate generating using CA stored in Secret resource"  "secret_name"="cert-manager-webhook-ca" "secret_namespace"="cert-manager"
I0720 07:56:04.054071       1 server.go:133] cert-manager/webhook "msg"="listening for insecure healthz connections"  "address"=":6080"
I0720 07:56:04.054107       1 server.go:197] cert-manager/webhook "msg"="listening for secure connections"  "address"=":10250"
I0720 07:56:05.095071       1 dynamic_source.go:267] cert-manager/webhook "msg"="Updated serving TLS certificate"  
I0720 08:03:15.911480       1 logs.go:59] http: TLS handshake error from 10.42.0.0:38780: EOF
I0720 08:03:16.047874       1 logs.go:59] http: TLS handshake error from 10.42.0.0:38782: EOF
I0720 08:07:15.620544       1 streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF
I0720 08:08:21.226097       1 logs.go:59] http: TLS handshake error from 10.42.3.0:42144: EOF
I0720 08:08:21.286990       1 logs.go:59] http: TLS handshake error from 10.42.3.0:42146: EOF

I am not sure if it is reason of unsuccessful connection to the rancher web UI. If yes, how can i fix the bug? 

**Steps To Reproduce:**
I installed the server node with the `curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint="postgres://root:123123@192.168.1.211:5432/k3s2?sslmode=disable" --node-taint CriticalAddonsonly=true:NoExecute --tls-san 192.168.1.52 ` where 192.168.1.52 is the IP of the external load balancer and agent node with `curl -fsL https://get.k3s.io | K3S_URL=https://192.168.1.52:6443 K3S_TOKEN=XXX sh -s - `

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
status of pods:

> root@m2:~# kubectl get pod -A -o wide
NAMESPACE                   NAME                                      READY   STATUS      RESTARTS   AGE    IP           NODE   NOMINATED NODE   READINESS GATES
kube-system                 local-path-provisioner-6c79684f77-bprmr   1/1     Running     0          146m   10.42.1.6    w1     <none>           <none>
kube-system                 coredns-d76bd69b-8bgb4                    1/1     Running     0          146m   10.42.1.4    w1     <none>           <none>
kube-system                 helm-install-traefik-crd-dz928            0/1     Completed   0          146m   10.42.1.5    w1     <none>           <none>
kube-system                 helm-install-traefik-cqm7c                0/1     Completed   1          146m   10.42.1.2    w1     <none>           <none>
kube-system                 metrics-server-7cd5fcb6b7-pphbp           1/1     Running     0          146m   10.42.1.3    w1     <none>           <none>
kube-system                 svclb-traefik-3e3b35ac-9vg8k              2/2     Running     0          142m   10.42.1.7    w1     <none>           <none>
kube-system                 traefik-df4ff85d6-gnhjm                   1/1     Running     0          142m   10.42.1.8    w1     <none>           <none>
kube-system                 svclb-traefik-3e3b35ac-h8qlr              2/2     Running     0          141m   10.42.4.2    w2     <none>           <none>
cert-manager                cert-manager-cainjector-9b679cc6-769wb    1/1     Running     0          140m   10.42.4.5    w2     <none>           <none>
cert-manager                cert-manager-76d44b459c-hxnx2             1/1     Running     0          140m   10.42.4.6    w2     <none>           <none>
cert-manager                cert-manager-webhook-57c994b6b9-4h8hk     1/1     Running     0          140m   10.42.4.3    w2     <none>           <none>
cattle-system               rancher-864b9b7d48-tzr69                  1/1     Running     0          133m   10.42.1.9    w1     <none>           <none>
cattle-system               rancher-864b9b7d48-8qfqk                  1/1     Running     0          133m   10.42.4.7    w2     <none>           <none>
cattle-system               rancher-864b9b7d48-wgbf2                  1/1     Running     0          133m   10.42.4.8    w2     <none>           <none>
cattle-fleet-system         gitjob-6b977748fc-dwhf4                   1/1     Running     0          129m   10.42.1.12   w1     <none>           <none>
cattle-fleet-system         fleet-controller-784d6fbcd8-8mzrl         1/1     Running     0          129m   10.42.1.11   w1     <none>           <none>
cattle-system               rancher-webhook-5b65595df9-zvwdg          1/1     Running     0          128m   10.42.4.14   w2     <none>           <none>
cattle-fleet-local-system   fleet-agent-699b5fb945-dqdgc              1/1     Running     0          128m   10.42.4.13   w2     <none>           <none>

status of certificate:

> root@m2:~# kubectl get certificate -A -o wide 
NAMESPACE       NAME                  READY   SECRET                ISSUER    STATUS                                          AGE
cattle-system   tls-rancher-ingress   True    tls-rancher-ingress   rancher   Certificate is up to date and has not expired   139m

status of issuer:
> NAMESPACE       NAME      READY   STATUS                AGE
cattle-system   rancher   True    Signing CA verified   140m

**Backporting**

- [ ] Needs backporting to older releases

**Comment by galal-hussein** [comment]
@johnyoungatwork thanks for opening the issue, but this seems to be related to rancher and not k3s, you might want to open and issue or ask for more information at  https://github.com/rancher/rancher/issues

Note: K3S uses Traefik for its ingress operations and not Nginx controller

**Comment by pberndt** [comment]
Hello,
I am experiencing the very same problem on **k3s**, _not_ rancher:
`kubectl logs -n cert-manager pod/cert-manager-webhook-7d4b5b8c56-psgqp`
```
I0831 17:22:59.906177       1 logs.go:59] http: TLS handshake error from 10.42.0.1:49220: EOF
I0831 17:23:25.218156       1 logs.go:59] http: TLS handshake error from 10.42.0.1:50672: EOF
```
```
$ k3s --version
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1
```
cert-manager v1.9.1 (vanilla install from yaml)

I believe the title of this issue is wrong and should read k3s, not rancher, as @johnyoungatwork was really showcasing a k3s install.
Kindly re-open and rename, thanks!
