### ISSUE TITLE
Support autodeploy of manifests in /etc

### ISSUE THREAD

**Issue by yajo** [k3s-io/k3s#5892]
**Is your feature request related to a problem? Please describe.**

K3s writes its own manifest files into `/var/lib/rancher/k3s/server/manifests`. This is expected, as `/var/lib` is defined in [the FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) as:

> State information. Persistent data **modified by programs** as they run (e.g., databases, packaging system metadata, etc.).

However, [the docs](https://github.com/rancher/docs/blob/dda29b33af1a03365a0b1a683fed6c8ff554949e/content/k3s/latest/en/helm/_index.md?plain=1#L19) say that sysadmins should put their own manifests also inside that directory. Sometimes the differences are subtle, but a sysadmin is not generally a program.

It's most common to write configuration files inside `/etc/`, not inside `/var/lib/`. The FHS supports this usage:

> Host-specific system-wide configuration files.

**Describe the solution you'd like**

Paths inside `/etc` supported for manifest autodeployment. Possibly `/etc/rancher/k3s/manifests` and `/etc/rancher/k3s/static`.

These paths could act similar to the `$PATH` environment variable: when searching for a manifest, first look inside the `/etc` path, and then look in the `/var/lib` path. 

**Describe alternatives you've considered**

1. Writing manifests in `/var/lib/rancher/k3s/server/manifests`.

2. Configure in `/etc` the files that systemd-tmpfilesd will write into `/var/lib`.

**Additional context**

Some distros such as NixOS include [options to configure `/etc` declaratively](https://nixos.org/manual/nixos/stable/options.html#opt-environment.etc). But not for stuff inside `/var/lib`, where the app itself is expected to write.

[Systemd acts in a similar way](https://www.computernetworkingnotes.com/linux-tutorials/systemd-unit-configuration-files-explained.html) as the one proposed here.

**Comment by brandond** [comment]
Other than FHS compliance, is there any particular reason for the deploy controller to watch an additional or different directory?

**Comment by yajo** [comment]
Yes, simplified NixOS integration.

In that OS, configuration is built declaratively along with the rest of the system binaries and libraries. Let's say that only `/home` and `/var` are meaningful stateful directories under that system, because the rest of it can be rebuilt from a single configuration file.

So, k3s autodeployment manifests become very hard to integrate there.

**Comment by brandond** [comment]
> Let's say that only /home and /var are meaningful stateful directories under that system

Wouldn't `/var/lib/rancher/k3s/server/manifests` already be considered stateful then? I am aware that some folks are more dogmatic about keeping administrator-provided configuration under `/etc` than others, but if it's just a matter of what path roots are expected to contain state, it sounds like we already meet those requirements.

**Comment by yajo** [comment]
> Or do you believe that cluster manifests files should **not** be included in state?

I'm not sure if I understand exactly what you mean by "state". The stateful vs stateless concept blurs a bit with container tools.

I think that cluster manifests *supplied by the app* should be stateful, while cluster manifests *supplied by the sysadmin* should be stateless. Thus, using 2 different folders seems sensible IMHO.

To put it in context, imagine that next year traefik project dies and there's a new shiny proxy that k3s wants to use. Well, the manifests inside `/var/lib/rancher/k3s/server/manifests` would change to reflect that *the app* decided to make a change, while the configuration inside `/etc/rancher/k3s/manifests` would remain the same because it's a matter of _the sysamin_ putting there the files. I know it's a hypothetical case that will probably never happen, it's just an example.


> I am aware that some folks are more dogmatic about keeping administrator-provided configuration under `/etc` than others

For the use case at hand (NixOS), it's not a dogma but a technical limitation.

Well, not exactly a limitation. You can always just go and write those files by hand inside `/var/lib/rancher/k3s/server/manifests` or use some of the workarounds. But that's not declarative or not ergonomic. By having them inside `/etc`, in NixOS these files can be configured declaratively, with rollback support and paranoid reproducibility guarantees.

**Comment by nemith** [comment]
This is still valid.  Since something like nix wants to declaratively define the files what is happening is for initial start I am writing a kube-vip manifest to `/var/lib/rancher/k3s/server/manifests` but then when k3s starts for the first time it is wiping that folder.  So there is no way for me to define kube-vip as an initial requirement.

**Comment by brandond** [comment]
What do you mean k3s "is wiping that folder"? The only way k3s will delete things from that folder is if you specify their name in the --disable list. K3s definitely will not ever wipe that directory clean.

Please open a new issue describing the specific problem you're encountering, whatever it is - it's not this.

Locking this as it is 2 years dead; any additional conversation can go in a new discussion or issue.
