### ISSUE TITLE
k3s start permission denied (air-gap)

### ISSUE THREAD

**Issue by turowicz** [k3s-io/k3s#5903]
I am unable to start k3s server in an air-gapped scenario.

**Environmental Info:**
K3s Version: 
```
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 
Intel x64, SLES 15 5.3.18-150300.59.43-default

Cluster Configuration:
1 server

**Describe the bug:**
After running the installation steps, the k3s service fails to start after "preparing data dir". Logs below.

**Steps To Reproduce:**
- scp k3s binary and k3s-images to server
- cp k3s to /usr/local/bin 
- cp k3s-images to /var/lib/rancher/k3s/agent/images/
- `INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="server --cluster-init --no-deploy traefik" INSTALL_K3S_VERSION="v1.21.7+k3s1" K3S_TOKEN="mytoken" ./install.sh`

**Expected behavior:**
I expect the installation script to complete and k3s to be up and running.

**Actual behavior:**
k3s fails to start.

**Additional context / logs:**
```
Jul 26 10:03:32 bpknsvmonp01 systemd[1]: Starting Lightweight Kubernetes...
Jul 26 10:03:32 bpknsvmonp01 sh[2457]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jul 26 10:03:32 bpknsvmonp01 sh[2458]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jul 26 10:03:32 bpknsvmonp01 k3s[2461]: time="2022-07-26T10:03:32+02:00" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Jul 26 10:03:32 bpknsvmonp01 k3s[2461]: time="2022-07-26T10:03:32+02:00" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/e61cd97f31a54dbcd9893f8325b7133cfdfd0229ff3bfae5a4f845780a93e84c"
Jul 26 10:03:34 bpknsvmonp01 k3s[2461]: time="2022-07-26T10:03:34+02:00" level=fatal msg="permission denied"
Jul 26 10:03:34 bpknsvmonp01 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jul 26 10:03:34 bpknsvmonp01 systemd[1]: k3s.service: Failed with result 'exit-code'.
Jul 26 10:03:34 bpknsvmonp01 systemd[1]: Failed to start Lightweight Kubernetes.
```

**Comment by turowicz** [comment]
cc @brandond

**Comment by turowicz** [comment]
cc @VestigeJ

**Comment by brandond** [comment]
```
time="2022-07-26T10:03:32+02:00" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/e61cd97f31a54dbcd9893f8325b7133cfdfd0229ff3bfae5a4f845780a93e84c"
time="2022-07-26T10:03:34+02:00" level=fatal msg="permission denied"
```

I'm unable to reproduce this. Has this node been hardened beyond the usual measures? Do you have selinux enabled?

**Comment by turowicz** [comment]
Figured it out: the `/var` was mounted in `fstab` with `noexec` option.

**Comment by turowicz** [comment]
@brandond unfortunately removing the `noexec` option from `fstab` is not an option - client datacenter restrictions. Unfortunately when installing `k3s server` with `--data-dir` the `containerd` executables are still placed in `/var/lib/rancher/...`. This is a major problem for installing k3s in corporate environments!

**Comment by turowicz** [comment]
This: https://github.com/k3s-io/k3s/issues/5456#issuecomment-1119477040
