### ISSUE TITLE
Network policy is not enforced

### ISSUE THREAD

**Issue by ahmedgabers** [k3s-io/k3s#5907]
**Environmental Info:**
K3s Version: `v1.21.4+k3s1`

Node(s) CPU architecture, OS, and Version: `Linux server 5.13.0-1019-gcp #23~20.04.1-Ubuntu SMP Mon Mar 7 13:39:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: 1 server, 1 agent.

**Describe the bug:**

Applying deny-all network policy in a namespace is not enforced as expected. 

**Steps To Reproduce:**

- Installed K3s: `/usr/local/bin/k3s server` with defaults, no flags were passed.
- The policy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: prod       
  name: deny-all
spec:
  podSelector: {}               
  policyTypes:
  - Ingress
  - Egress
```
**Expected behavior:**
Applying deny-all network policy in a namespace should deny all traffic.

**Actual behavior:**

I set up three namespaces with some pods running: `prod`, `qa` and `demo`.

From the diagram, the policy is applied in the `prod` namespace. I am expecting traffic to block, but for some odd reason, pod-1 is able to reach.

![Screenshot from 2022-07-27 09-56-17](https://user-images.githubusercontent.com/51884558/181206376-58f35e33-f703-48a4-8938-986ff93780da.png)

The second scenario, I applied the policy in the `demo` namespace. And I still get this odd behaviour where the `ds` pods are able to reach whereas the `curl` pod not as expected.

![Screenshot from 2022-07-27 09-56-23](https://user-images.githubusercontent.com/51884558/181206675-b6e338b3-dcfd-4772-81d7-a88a4226188e.png)

**Additional context / logs:**

server: iptables-save -c | grep deny

> [1:60] -A KUBE-POD-FW-J3LFR2RAC67TX63O -m comment --comment "run through nw policy deny-all" -j KUBE-NWPLCY-SA6FJAI3TI2BUUWP

agent: iptables-save -c | grep deny

> [1:60] -A KUBE-POD-FW-Q57E535675JMJWPF -m comment --comment "run through nw policy deny-all" -j KUBE-NWPLCY-YV6U3WFXB7MUMPRI

<details>
  <summary>Output from /etc/cni/net.d/87-podman.conflist</summary>
  
```
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "routes": [{ "dst": "0.0.0.0/0" }],
        "ranges": [
          [
            {
              "subnet": "10.88.0.0/16",
              "gateway": "10.88.0.1"
            }
          ]
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "firewall"
    },
    {
      "type": "tuning"
    }
  ]
}
```
</details>

**Comment by ahmedgabers** [comment]
So `hostNetwork: true` was enabled on the ds spec, thus policies won't apply as pods become part of the host's networking. I wonder if there is a workaround built-in before trying out calico's host policies?

**Comment by brandond** [comment]
I believe this is listed as a known issue upstream: https://kubernetes.io/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet
> The ability to prevent loopback or incoming host traffic (Pods cannot currently block localhost access, nor do they have the ability to block access from their resident node).
