### ISSUE TITLE
deploy embedded etcd k3 cluster  error on public cloud

### ISSUE THREAD

**Issue by chinasoftgit** [k3s-io/k3s#5908]
I have a public cloud machine to deploy embedded etcd k3s cluster ；
 cloud	        publicIP	privateIP	
Alibaba cloud	 47.xx.xx.12	172.28.94.133
Tencent cloud  122.xx.xxx.111 192.168.112

On Alibaba cloud execute command 
INSTALL_K3S_EXEC='server --docker --cluster-init --node-external-ip 47.XX.XX.12 --advertise-address 47.XX.XX.12  --flannel-iface eth0 --kube-apiserver-arg enable-admission-plugins=NodeRestriction,PodNodeSelector' ./install.sh

kubectl get nodes
NAME          STATUS   ROLES                       AGE    VERSION         INTERNAL-IP     EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
sdaict-demo   Ready    control-plane,etcd,master   129m   v1.22.11+k3s1   172.28.94.133   47.XX.XX.12   Ubuntu 20.04.4 LTS   5.4.0-110-generic   docker://20.10.12

then on tencent cloud execute command 
K3S_TOKEN=XXXXX INSTALL_K3S_EXEC='server  --docker  --node-external-ip 122.XX.XX.111  --flannel-iface enp0s31f6' K3S_URL=https://47.XXX.XXX.12:6443 ./install.sh

but tencent cloud can not join first master, error log:

Jul 27 17:26:52 sdaict220-desktop k3s[1774356]: time="2022-07-27T17:26:52+08:00" level=info msg="Handling backend connection request [sdaict220-desktop]"
Jul 27 17:26:52 sdaict220-desktop k3s[1774356]: time="2022-07-27T17:26:52+08:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
Jul 27 17:26:57 sdaict220-desktop k3s[1774356]: time="2022-07-27T17:26:57+08:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Jul 27 17:26:57 sdaict220-desktop k3s[1774356]: time="2022-07-27T17:26:57+08:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
Jul 27 17:27:02 sdaict220-desktop k3s[1774356]: {"level":"warn","ts":"2022-07-27T17:27:02.765+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc001872000/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Jul 27 17:27:02 sdaict220-desktop k3s[1774356]: time="2022-07-27T17:27:02+08:00" level=info msg="Failed to test data store connection: context deadline exceed

On alibaba cloud  execute command：kubectl describe node sdaict-demo ,  

Name:               sdaict-demo
Roles:              control-plane,etcd,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    egress.k3s.io/cluster=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=sdaict-demo
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/etcd=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        etcd.k3s.cattle.io/node-address: 172.28.94.133------------------- privateIP
                    etcd.k3s.cattle.io/node-name: sdaict-demo-4ca6458e
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"a6:a9:28:4f:11:e7"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true

exctue command:  etcdctl --cacert=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --cert=/var/lib/rancher/k3s/server/tls/etcd/client.crt --key=/var/lib/rancher/k3s/server/tls/etcd/client.key member list

etcd member info:

ee32af0af68f2fcf, started, sdaict-demo-4ca6458e, https://172.28.94.133:2380, https://172.28.94.133:2379, false

etcd member is privateIP

exctue command:  cat /var/lib/rancher/k3s/server/db/etcd/config 
advertise-client-urls: https://172.28.94.133:2379---------------------- privateIP
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
heartbeat-interval: 500
listen-client-urls: https://127.0.0.1:2379,https://172.28.94.133:2379---------------------- privateIP
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://172.28.94.133:2380---------------------- privateIP
log-outputs:
- stderr
logger: zap
name: sdaict-demo-4ca6458e
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000

I guess etcd members are privateIP， other etcd member can't join it， cause other master to fail to join。How can specify etcd member as publicIp  or  annotate  etcd.k3s.cattle.io/node-address publicIP。 Is this deployment of embedded etcd k3s cluster still not supported

**Comment by brandond** [comment]
> I guess etcd members are privateIP， other etcd member can't join it， cause other master to fail to join。How can specify etcd member as publicIp

K3s does not currently support running etcd over the public addresses. When using embedded etcd, the server nodes must be able to access each other via their private IPs.
