### ISSUE TITLE
"Using Docker as the Container Runtime" documentation seems out of date

### ISSUE THREAD

**Issue by mathiashls** [k3s-io/k3s#5910]
**Environmental Info:**
K3s Version:
```
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1
```

Node(s) CPU architecture, OS, and Version: 
`Linux debian11.localdomain 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux`

**Describe the bug:**
When trying to run k3s with docker, I get the error 
```
"Waiting to retrieve agent configuration; server is not ready: --docker is no longer supported; to continue using docker, install cri-dockerd and set --container-runtime-endpoint"
```
Yet the [official k3s page](https://rancher.com/docs/k3s/latest/en/advanced/#using-docker-as-the-container-runtime) say that I need to use `--docker` to install it using docker.

**Steps To Reproduce:**

- Installed K3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--docker --write-kubeconfig-mode 644 --kubelet-arg cgroup-driver=systemd" sh -`
- Also installed K3s with: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --kubelet-arg cgroup-driver=systemd" sh -s - --docker`

I believe that this is a documentation issue, so I am skipping some information about my environment. If this happens to be other problem I will update the issue with all the information needed.

**Comment by mathiashls** [comment]
As my solution for this problem was to downgrade the k3s version I'm using, I don't have the knowledge to create a PR with new instructions on how to install it with docker.

With more time available, if I find out how to install it with docker on the new version, I will gladly open a PR if the issue is still open.

**Comment by endlessbest** [comment]
> As my solution for this problem was to downgrade the k3s version I'm using, I don't have the knowledge to create a PR with new instructions on how to install it with docker.
> 
> With more time available, if I find out how to install it with docker on the new version, I will gladly open a PR if the issue is still open.

what version to use for docker support?

**Comment by brandond** [comment]
Kubernetes 1.24 and higher no longer include dockershim, and k3s does not either. If you want to use k3s with docker, you should install cri-dockerd and set `--container-runtime-endpoint` to point at the path of its api socket.

**Comment by endlessbest** [comment]
> 

thanks for the quick reply, after google for a while, k3s 1.20.x can support docker by default.

**Comment by mathiashls** [comment]
> > As my solution for this problem was to downgrade the k3s version I'm using, I don't have the knowledge to create a PR with new instructions on how to install it with docker.
> > With more time available, if I find out how to install it with docker on the new version, I will gladly open a PR if the issue is still open.
> 
> what version to use for docker support?

I would suggest that you follow @brandond method, just using an older k3s version seems not optimal. But to answer your question, I was able to run it correctly using `1.23.6+k3s1`.

**Comment by endlessbest** [comment]
> > > As my solution for this problem was to downgrade the k3s version I'm using, I don't have the knowledge to create a PR with new instructions on how to install it with docker.
> > > With more time available, if I find out how to install it with docker on the new version, I will gladly open a PR if the issue is still open.
> > 
> > 
> > what version to use for docker support?
> 
> I would suggest that you follow @brandond method, just using an older k3s version seems not optimal. But to answer your question, I was able to run it with docker and no other change using k3s version `1.23.6+k3s1`.

yeah, the last version of  k3s for docker support would be precious for whose who want to move their docker projects to k3s with little effort. i know containerd is the way to go, it may be done step by step.

**Comment by mdrahman-suse** [comment]
Validated in https://github.com/k3s-io/k3s/issues/5741#issuecomment-1220734069

**Comment by brandond** [comment]
Leaving this open to track updating the docs to note which 1.24 releases did not support `--docker`.

**Comment by caroline-suse-rancher** [comment]
@dereknola Did this make it into the latest version of the k3s docs?

**Comment by brandond** [comment]
Closing; docs have moved and --docker has been supported for several releases.
