### ISSUE TITLE
Improve incorrect Peer Url Error

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5915]
**Is your feature request related to a problem? Please describe.**

If an etcd peer url is invalid, the current error looks like:
```
Found [thisnode1=http://10.10.10.123:2380], expect: thisnode1=10.10.10.123 
```
This is misleading, as we don't actually want just the raw IP, we want a `https:<IP>:2380` format. The error should reflect this. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [X] Needs backporting to older releases

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using v1.24.4-rc1+k3s1
## Environment Details
Infrastructure
Cloud EC2 instance

Node(s) CPU architecture, OS, and Version:
Ubuntu 20.04

Cluster Configuration:
Single node

 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml
2. Install k3s

**To reproduce:**

Reproduced the issue passing incorrect initial-advertise-peer-urls and initial-cluster values. Found the expected output in the logs 
```
curl -fL https://get.k3s.io| INSTALL_K3S_VERSION=v1.24.3+k3s1 sh -s - server --token secret --cluster-init --write-kubeconfig-mode=644 --node-external-ip=18.220.221.205 --etcd-arg initial-advertise-peer-urls=http://172.31.13.79:2380 --etcd-arg initial-cluster="debugstr=http://172.31.13.79:2380" --etcd-arg name=debugstr
```
Logs:
```
Aug 24 18:31:30 ip-172-31-13-79 k3s[34463]: time="2022-08-24T18:31:30Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [debugstr=http://172.31.13.79:2380], expect: ip-172-31-13-79-587cb699=172.31.13.79"
```

**To validate:**
```
$ curl -fL https://get.k3s.io| INSTALL_K3S_VERSION=v1.24.4-rc1+k3s1 sh -s - server --token secret --cluster-init --write-kubeconfig-mode=644 --etcd-arg initial-advertise-peer-urls=http://172.31.6.25:2380 --etcd-arg initial-cluster="debugstr=http://172.31.6.25:2380" --etcd-arg name=debugstr
```
Logs show what is the expected value to be fixed
```
Aug 24 18:37:04 ip-172-31-6-25 k3s[7211]: time="2022-08-24T18:37:04Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [debugstr=http://172.31.6.25:2380], expect: ip-172-31-6-25-d45e7c5f=https://172.31.6.25:2380"
```
