### ISSUE TITLE
Ubuntu 22.04 LTS -> Failed to get unit file state for nm-cloud-setup.service (as already reported)

### ISSUE THREAD

**Issue by thiscantbeserious** [k3s-io/k3s#5925]
Since the last ticket is already pointing to this issue I'm just linking this again:

https://github.com/k3s-io/k3s/issues/4911

**It was just closed as solved - but this seems actually unsolved**

**Should be able to reproduce this easily with a brand new/clean Ubuntu 22.04 VM**

**If you don't have Network Manager installed or if the Service file 'nm-cloud-setup.service' is not there the k3s.service will actually never start.** 

(seems to be the default case for new Ubuntu LTS)

I just verified this on three different Bare Metal Machines all running Ubuntu

Two different architectures (amd64, arm64), 3 different Ubuntu Server Versions 20.04, 22.02 and 22.04 and installation state (fresh - old lts, upgraded, fresh new lts).

**Comment by brandond** [comment]
As I said at https://github.com/k3s-io/k3s/issues/4911#issuecomment-1087968204
> If k3s is failing and you see this message in your logs, look further - this is not the cause of your problem.

**Comment by thiscantbeserious** [comment]
Yes I did read all and verified it myself on my different hosts before I put it up - let me add reference from the systemd manpage:

> ExecStart= commands **are only run after all ExecStartPre= commands that were not prefixed with a "-" exit successfully**.

from https://www.freedesktop.org/software/systemd/man/systemd.service.html

So for the case of 

`ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'`

This will actually cause the ExecStart k3s to fail, or did I miss an update on this? Do I need to be on latest master?

**Comment by brandond** [comment]
No, we DON'T want to skip that check, unlike the others. K3s will fail to operate properly if nm-cloud-setup is enabled, so we want the startup to fail if it is found.

I'm not aware of any distros that only have `/bin/systemctl`:

```console
root@dev01:~# grep VERSION= /etc/os-release; ls -la /bin/systemctl /usr/bin/systemctl
VERSION="22.04 LTS (Jammy Jellyfish)"
-rwxr-xr-x 1 root root 1115760 Apr 21 05:14 /bin/systemctl
-rwxr-xr-x 1 root root 1115760 Apr 21 05:14 /usr/bin/systemctl
```

```console
root@ubuntu01:~# grep VERSION= /etc/os-release; ls -la /bin/systemctl /usr/bin/systemctl
VERSION="21.10 (Impish Indri)"
-rwxr-xr-x 1 root root 1107504 Apr 21 12:41 /bin/systemctl
-rwxr-xr-x 1 root root 1107504 Apr 21 12:41 /usr/bin/systemctl
```

```console
[root@centos01 ~]# grep VERSION= /etc/os-release; ls -la /bin/systemctl /usr/bin/systemctl
VERSION="7 (Core)"
-rwxr-xr-x. 1 root root 721744 Oct  1  2020 /bin/systemctl
-rwxr-xr-x. 1 root root 721744 Oct  1  2020 /usr/bin/systemctl
```

**Comment by thiscantbeserious** [comment]
Then how about something like making sure the file does not exists or if exists the service is disabled?

`ExecStartPre=/bin/sh -xc '[! -f /etc/systemd/nm-cloud-setup.service ] || ! systemctl is-enabled --quiet nm-cloud-setup.service'`

**Comment by brandond** [comment]
I'm more interested in figuring out why your host is missing one of the standard systemctl binary locations...

**Comment by thiscantbeserious** [comment]
That is because Ubuntu Server is not using NetworkManager but systemd-networkd in 20.04 and from 22.04 by default netplan:

https://tecadmin.net/how-to-configure-static-ip-address-on-ubuntu-22-04/

NetworkManager isn't installed by default.

So you check will fail for everyone using the Server deployments not the Desktop variants.  

Same should hold true for other Server variants not going after Desktop Deployments - e.g OpenSUSE (using wicked).

So in the end it all comes down to not every deployment having installed NetworkManager, 

which should be handled by the above file-check proporsal for everyone.

**Comment by lalyos** [comment]
Hi, I'm just run into a similar issue. Actually I was using [autok3s](https://github.com/cnrancher/autok3s) to start a single-node cluster.

The instance is started on google cloud and using the base image: "ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20210514"

```
grep VERSION= /etc/os-release; ls -la /bin/systemctl /usr/bin/systemctl
VERSION="18.04.5 LTS (Bionic Beaver)"
ls: cannot access '/usr/bin/systemctl': No such file or directory
-rwxr-xr-x 1 root root 182352 Apr  7  2021 /bin/systemctl
```

That was the default image provided, by autok3s. But tried to change it to 22.04 and that was working fine.

So I leave this comment here, if somebody runs into:

> upgrading from ubuntu 18.04 to 22.04 solves the issue on google cloud

**Comment by Bizkitcan** [comment]
This is still an issue, when you try to install and run RKE2 on a fresh Ubuntu 22.04.2 VM.

**Comment by brandond** [comment]
@Bizkitcan no, this is not your issue. All of your ExecStartPre commands exited successfully. Please check the journald logs for rke2-agent. If you're not able to figure out from those logs why it's not working, please open a new issue.

**Comment by brandond** [comment]
I am closing and locking this issue.
* K3s expects `systemctl` to reside at `/usr/bin/systemctl`. If your distro uses systemd but places the binaries somewhere else, you will need to modify the k3s systemd unit.
* Messages about `nm-cloud-setup.service` not being found are not errors. We are specifically checking to confirm that this service IS NOT ENABLED.
