### ISSUE TITLE
Minio does not support Instance Metadata v2 Credentials

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5927]
Copied from RKE2 issues:
* https://github.com/rancher/rke2/issues/3198

**Comment by cwayne18** [comment]
@brandond can we close this?

**Comment by brandond** [comment]
Sorry, should have gone to To Test. I'll let QA close it out.

**Comment by rancher-max** [comment]
Performed the same validations as in https://github.com/rancher/rke2/issues/3198#issuecomment-1233459133. Validated using k3s v1.24.4+k3s1.
