### ISSUE TITLE
The domestic acceleration download link is wrong

### ISSUE THREAD

**Issue by gglnp** [k3s-io/k3s#5942]
Domestic users, the accelerated installation link cannot download the script

![image](https://user-images.githubusercontent.com/61819511/182518766-8d1c687d-00a5-4c15-ab8f-b7683d171320.png)

browser access effect：

![image](https://user-images.githubusercontent.com/61819511/182518896-b0b216f0-006b-4f4b-ad75-8b8a796e8361.png)

The terminal is obtained as follows:

![image](https://user-images.githubusercontent.com/61819511/182519052-733a37c7-ee87-4b1e-b730-60b8640efd01.png)

This installation script download link seems to be wrong and needs to be changed

**Comment by brandond** [comment]
The Chinese k3s documentation and artifact mirror are maintained by an independent team. We do not have any access to the docs or mirror infrastructure.

**Comment by gglnp** [comment]
> 中文k3s文档和神器镜像由独立团队维护。我们无权访问文档或镜像基础架构。

So where do I go to find a solution?

**Comment by brandond** [comment]
I would probably try the forums: https://forums.rancher.cn/c/k3s/8

**Comment by gglnp** [comment]
Problem solved, thank you very much for your help
