### ISSUE TITLE
[Release-1.23] In case of NodeIP not specified with dualstack setup K3S fails to start

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#5943]
Backport for #5918

**Comment by mdrahman-suse** [comment]
### Validated on 1.23 branch with commit d04af60aad053ec94e60c986bf4c70cdbfc9e11c
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-192-168-7-155 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
```
 
*Cluster Configuration:*

```
Single node
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summer
cluster-cidr: 10.42.0.0/16,2001:cafe:43:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:44:1::/112
flannel-iface: "ens5"
disable-network-policy: true
flannel-ipv6-masq: true
cluster-init: true
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
 - For replication: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.9+k3s1 sh -`
 - For validation: `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=d04af60aad053ec94e60c986bf4c70cdbfc9e11c sh -`
3. Ensure k3s cluster is up

**Replication Results:**
- k3s version used for replication:

```
k3s version v1.23.9+k3s1 (f45cf326)
go version go1.17.5
```
 

- The cluster does not come up as k3s fails to start and the below error is observed
```
$ journalctl -xeu k3s.service | grep 'cluster-cidr:'
Aug 10 05:13:53 ip-192-168-7-155 k3s[1865]: time="2022-08-10T05:13:53Z" level=fatal msg="cluster-cidr: [10.42.0.0/16 2001:cafe:43::/56] and node-ip: [192.168.7.155], must share the same IP version (IPv4, IPv6 or dual-stack)"
Aug 10 05:14:07 ip-192-168-7-155 k3s[1882]: time="2022-08-10T05:14:07Z" level=fatal msg="cluster-cidr: [10.42.0.0/16 2001:cafe:43::/56] and node-ip: [192.168.7.155], must share the same IP version (IPv4, IPv6 or dual-stack)"
```

**Validation Results:**
- k3s version used for validation:

```
k3s version v1.23.9+k3s-d04af60a (d04af60a)
go version go1.17.5
```
 

- The cluster comes up successfully and no error is observed
```
```
 
**Additional context / logs:**
```
```
