### ISSUE TITLE
Thrashing loop with 22 node armhf cluster - kill, reschedule, kill

### ISSUE THREAD

**Issue by alexellis** [k3s-io/k3s#595]
**Describe the bug**

With 1-2 nodes I saw harmony in the cluster. When I added an additional set of around 20, bumping up to 22, I began to see problems. It seems that one of the pods gets killed, rescheduled and then this repeats over and over.

**To Reproduce**

* I put together a 22 node k3s cluster running on RPi3
* Installed OpenFaaS (using httpProbe option, non-default)
* I deployed nodeinfo from the store https://raw.githubusercontent.com/openfaas/store/master/store-armhf.json and set its min scale to 20, max to 40

![Screenshot 2019-06-30 at 21 16 47](https://user-images.githubusercontent.com/6358735/60401620-625ca700-9b7c-11e9-893d-7ca570063725.png)
![Screenshot 2019-06-30 at 21 14 47](https://user-images.githubusercontent.com/6358735/60401621-62f53d80-9b7c-11e9-9586-71818f3bf8e4.png)

I received the output above.

Workers are reporting healthy

![Screenshot 2019-06-30 at 21 17 54](https://user-images.githubusercontent.com/6358735/60401636-8e782800-9b7c-11e9-8b24-bdc8034c63ed.png)

YAML I used in addition to creating the [basic auth secret](https://github.com/openfaas/faas-netes/tree/master/yaml#20-create-password)

[yaml_armhf.tgz.zip](https://github.com/rancher/k3s/files/3343301/yaml_armhf.tgz.zip)

**Possible solution**

I could try to extend the livenessProbe / readinessProbe on the function to run at a lower interval.

```
        - name: readiness_probe_initial_delay_seconds
          value: "2"
        - name: readiness_probe_timeout_seconds
          value: "1"
        - name: readiness_probe_period_seconds
          value: "5"
        - name: liveness_probe_initial_delay_seconds
          value: "10"
        - name: liveness_probe_timeout_seconds
          value: "1"
        - name: liveness_probe_period_seconds
          value: "5"
```

I assume that the image pull time is not part of the initial delay.

**Comment by alexellis** [comment]
This appeared to eventually calm down, apart from when I tried scaling to > 20 replicas where I saw some of this again.

**Comment by brandond** [comment]
Closing due to age.
