### ISSUE TITLE
Update flannel to v0.19.1

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#5961]
**Describe the solution you'd like**

Update flannel version to v0.19.1

**Describe alternatives you've considered**

**Additional context**

**Comment by est-suse** [comment]
Validated on commit https://github.com/k3s-io/k3s/commit/2b13d70afd6f324604c2e9e7d48ad9398aeaf437
Environment Details
Infrastructure

[ x ] Cloud
Node(s) CPU architecture, OS, and Version:

VERSION="20.04 LTS (Focal Fossa)"
Cluster Configuration:

3 servers, 1 agent
Testing Steps
Install k3s using commit id https://github.com/k3s-io/k3s/commit/b14cabc107e848ea4122e6917994925b1ca2418c
Once everything is up and ready run /var/lib/rancher/k3s/data/*/bin/flannel
Validation Results:
Version v0.19.1 is showed correctly!
