### ISSUE TITLE
[Release 1.23] Update flannel v0.19.1

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#5965]
Backport for #5961

**Comment by mdrahman-suse** [comment]
### Validated on 1.23 branch with commit 826b9498df9578509e8c4b6906071592a6295159
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-45-67 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```
 
*Cluster Configuration:*

```
Single node
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
token: summer
```

## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=826b9498df9578509e8c4b6906071592a6295159 sh -`
3. Run `$ /var/lib/rancher/k3s/data/*/bin/flannel`
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.23.10+k3s-826b9498 (826b9498)
go version go1.17.5
```
 

- Version is updated
```
$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.19.1 (linux/amd64) commit 826b9498df9578509e8c4b6906071592a6295159 built on 2022-08-19T05:29:48Z
```
- Cluster is ready

- Also observed that upgrade from v1.23.9+k3s1 to the commit is not upgrading flannel version (Please advice @rbrtbnfgl 
- Before upgrade
```
$ k3s -v
k3s version v1.23.9+k3s1 (f45cf326)
go version go1.17.5
$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.18.1 (linux/amd64) commit f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca built on 2022-07-19T00:42:17Z
```
- After upgrade
```
$ k3s -v
k3s version v1.23.10+k3s-826b9498 (826b9498)
go version go1.17.5
ubuntu@ip-172-31-45-67:~$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.18.1 (linux/amd64) commit f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca built on 2022-07-19T00:42:17Z
```
