### ISSUE TITLE
Pods can't talk to Services in Debian and Ubuntu

### ISSUE THREAD

**Issue by Vacant0mens** [k3s-io/k3s#5971]
**Environmental Info:**
K3s Version: 

```
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1
```
Node(s) CPU architecture, OS, and Version: 

`Linux k3s-1 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
I also experienced this in Debian 11, but I rebuilt the cluster using Ubuntu 22.04 to see if it was something specifically with Debian (since Debian isn't officially tested with K3s)

Cluster Configuration:

3 nodes set up using HA with Embedded Database

**Describe the bug:**

from a given pod, `nc 10.42.x.x -p <any port>` works fine, but `nc 10.43.x.x -p <any port>` doesn't.
DNS resolves correctly when using the service name and/or the FQDN for the service, but somehow all of the pods I've tried can't connect to anything in 10.43.0.0/16, even within the same node and namespace.

**Steps To Reproduce:**
- Installed K3s using documented guide for HA with Embedded Database
- Deployed a helm chart (into a new namespace)
- exec'd into a container from the chart
- used the `nc` and `nslookup` commands on pod IP's and Service IP's from inside and outside of the namespace

**Expected behavior:**

pods should be able to communicate with services, especially inside the same namespace

**Actual behavior:**

pods can communicate with other pods, but not services.

**Additional context / logs:**

**Comment by manuelbuil** [comment]
I deployed k3s using HA with embedded database and things are working for me. 

1. Could you try using something different than netcat to test (e.g. curl)?
2. Can you check that when querying `kubectl get endpoints -A` you see endpoints for the service?

**Comment by Vacant0mens** [comment]
1. after some messing with getting a proper test pod going, `curl` did end up working. strange that `nc` doesn't. Why is that?
1. yes, the endpoints exist, and are the correct port.

**Comment by Vacant0mens** [comment]
after some troubleshooting, I was able to figure out that if i leave off `.cluster.local` in the DNS names, the pods are able to connect to each other correctly.
i.e. 
`servicename.namespace.svc.cluster.local` <- doesn't work
`servicename.namespace.svc` <- works

**Comment by dsyorkd** [comment]
I've also been able to reproduce this in k3s version v1.24.3+k3s1 
1 control plane node
4 workers 
Steps to reproduce exactly the same 
ubuntu 22.04

nslookup works fine 
nc from busybox pod  to Kubernetes service on 10.43.0.1:443 timeout 

extra diagnostics - not sure if they are related. 
unable to reach lb ips though they are arping - metallb complains of config reloads constantly, kube-vip also shows state going from active to idle. 
nothing in crash loop

**Comment by manuelbuil** [comment]
I left this issue unresolved before going on leave, sorry about that! Now that I'm back, do you guys still need help with this?

**Comment by brandond** [comment]
> doing an nslookup from my test container, using .cluster.local without the . at the end results in my personal domain getting appended

This indicates that you have a wildcard record in your personal domain. Don't do that. Your personal domain's wildcard record is being returned, when instead the lookup should get a NXDOMAIN and continue to look for other records in cluster DNS.
