### ISSUE TITLE
containerd config world readable and contains private registry credentials in plaintext

### ISSUE THREAD

**Issue by discordianfish** [k3s-io/k3s#5972]
K3s Version: v1.24.2+k3s2
```
ls -l /var/lib/rancher/k3s/agent/etc/containerd/config.toml
-rw-r--r-- 1 root root 867 28. Jul 13:36 /var/lib/rancher/k3s/agent/etc/containerd/config.toml
```

**Comment by fbirlik** [comment]
Parent folder /var/lib/rancher/k3s/agent folder is not executable, so it shouldn't be possible to reach any files in its sub directories.

ubuntu@kube-01:~$ sudo ls -l /var/lib/rancher/k3s/agent/etc/containerd/config.toml
-rw-r--r-- 1 root root 728 Aug  7 20:57 /var/lib/rancher/k3s/agent/etc/containerd/config.toml
ubuntu@kube-01:~$ sudo ls -l /var/lib/rancher/k3s
total 12
**drwx------ 5 root root 4096 Aug  7 20:57 agent**
drwxr-xr-x 3 root root 4096 Aug  7 20:57 data
drwx------ 8 root root 4096 Aug  7 20:57 server
ubuntu@kube-01:~$ sudo ls -l /var/lib/rancher/k3s

**Comment by brandond** [comment]
The comment from @fbirlik is correct. The parent directory permissions prevent the file from being readable by non-root users.
