### ISSUE TITLE
[BUG][document]K3s installation problem

### ISSUE THREAD

**Issue by ChenpiDog** [k3s-io/k3s#5980]
Here are my installation records：
master：
curl https://releases.rancher.com/install-docker/19.03.sh | sh
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - --docker
cat /var/lib/rancher/k3s/server/node-token

worker：
curl https://releases.rancher.com/install-docker/19.03.sh | sh
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=https://172.17.176.167:6443/ K3S_TOKEN=K101effcd7b5a9e1c943f9067d89687a006d9789ed207c0d674ce9cb7e997e0f895::server:fa93327e800173ca7f07e40c24af5fa1 sh -s - --docker

When I execute "kubectl get node":
![image](https://user-images.githubusercontent.com/55483982/184085949-9f91e8ea-09be-47cf-8537-42f76f97ec1f.png)

**Comment by ChenpiDog** [comment]
Is there a problem with the deployment script of the official document recently？

**Comment by brandond** [comment]
Note: Current 1.24 releases do not support `--docker`. Also, as noted on other issues, the k3s team does not support the China content mirrors.
