### ISSUE TITLE
etcd-snapshot-schedule-cron Parameter does not take effect

### ISSUE THREAD

**Issue by Heyz6** [k3s-io/k3s#5983]
k3s version: v1.21.13

INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --docker --cluster-init --etcd-snapshot-schedule-cron "\*/2 \* \* \* \*" --disable servicelb,traefik,local-storage,metrics-server' K3S_TOKEN=SECRET K3S_NODE_NAME="node1" ./k3s-install.sh

INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --docker --cluster-init --etcd-snapshot-schedule-cron "*/2 * * * *" --disable servicelb,traefik,local-storage,metrics-server' K3S_TOKEN=SECRET K3S_NODE_NAME="node1" ./k3s-install.sh

https://docs.rancher.cn/docs/k3s/installation/install-options/server-config/_index/
After the configuration in the official document, the ETCD periodic backup parameter does not take effect in the above two methods. Is it because I installed the wrong command? Or something else.
Below is a screenshot of my successful manual backup
What if I specify the timing of a scheduled task during installation
![image](https://user-images.githubusercontent.com/13972460/184286791-6f4f886c-d56e-4b12-8a7a-4830cabc57f3.png)

**Comment by brandond** [comment]
Passing a quoted string inside another quoted string is hard to get right. You can play around with it, but you might find it easier to write that bit of config to /etc/rancher/k3s/config.yaml prior to installing K3s, rather than trying to pass it as part of the INSTALL_K3S_EXEC args.
