### ISSUE TITLE
Incorrect warning of overlayfs cannot be enable for xfs

### ISSUE THREAD

**Issue by divick** [k3s-io/k3s#5989]
K3s Version:
k3s version v1.24.3+k3s1 (https://github.com/k3s-io/k3s/commit/990ba0e88c90f8ed8b50e0ccd375937b841b176e)
go version go1.18.1

```dmidecode | grep Product
Product Name: VMware Virtual Platform
Product Name: 440BX Desktop Reference Platform
```
Node(s) CPU architecture, OS, and Version:
```Linux colmbapp208133 3.10.0-327.10.1.el7.x86_64 https://github.com/k3s-io/k3s/issues/1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

Cluster Configuration:
Trying to run k3s on a single server only.

**Describe the bug:**
Starting k3s server shows the following "incorrect" warning:

```
 Waiting to retrieve agent configuration; server is not ready: "overlayfs" snapshotter cannot be enabled for "/var/lib/rancher/k3s/agent/containerd", try using "fuse-overlayfs" or "native": /var/lib/rancher/k3s/agent/containerd does not support d_type. If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support
INFO[0101] Waiting for control-plane node node1 startup: nodes "node1" not found 
```

This is even when the filesystem mounted on /var is xfs

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**
No warning should have been emitted and the control plane node to have started correctly.

**Actual behavior:**
It keeps emitting this warning and the node never becomes ready.

**Additional context / logs:**
The output from df shows:

```
/dev/sda5      xfs        15G  7.2G  7.9G  48% /var
```

and from mount:
```
mount | grep "/var"
/dev/sda5 on /var type xfs (rw,relatime,attr2,inode64,noquota)
```

So even though it is xfs filesystem but it still complains.

**Comment by brandond** [comment]
The error is correct. Your xfs filesystem has been created without the required option:
`If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support`

If you cannot ensure that the filesystem on `/var` is created with the `ftype=1` option, then you should create a separate partition for `/var/lib/rancher/k3s` and create it with xfs using the correct options, or using ext4.
