### ISSUE TITLE
k3s agent doesn't support `flannel-backend` flag

### ISSUE THREAD

**Issue by BonusPlay** [k3s-io/k3s#5999]
**Environmental Info:**
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 
`Linux zion1 5.18.1-1-aarch64-ARCH #1 SMP PREEMPT Wed Jun 1 19:34:45 MDT 2022 aarch64 GNU/Linux`
running on raspberry pi 4b

Cluster Configuration:
1 master 3 slaves

**Describe the bug:**
k3s agent doesn't support `--flannel-backend` flag, despite `-no-flannel` flag being deprecated.

**Steps To Reproduce:**
`k3s agent -h | grep flannel-backend`
or
`k3s agent --flannel-backend=none`

**Expected behavior:**
k3s agent accepts `flannel-backend` flag

**Actual behavior:**
```
Incorrect Usage: flag provided but not defined: -flannel-backend
(missing `--flannel-backend` option)
```

**Comment by brandond** [comment]
Explained at https://github.com/k3s-io/k3s/issues/3497#issuecomment-866383562
