### ISSUE TITLE
Secret Encryption

### ISSUE THREAD

**Issue by lazzio7** [k3s-io/k3s#6001]
Good morning,

I'd like to ask regarding secret encryption feature..

I implemented it on our k3s cluster , but when I want recreate multiple times I'm getting mentioned errors
`FATA[0000] see server log for details: https://127.0.0.1:6443/v1-k3s/encrypt/config: 400 Bad Request secrets-encrypt error ID 11737`
as it is describe on "[Secrets Encryption Test Plan](https://github.com/k3s-io/k3s/wiki/Secrets-Encryption-Test-Plan)"
is there any update about this feature please?

Thank You

**Comment by brandond** [comment]
> I implemented it on our k3s cluster
How did you go about enabling secrets encryption?

> when I want recreate multiple times I'm getting mentioned errors

What specific command are you running when you see this error?

**Comment by brandond** [comment]
> `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --secrets-encryption --disable=traefik --disable=coredns " sh -`

Was this the first time K3s was installed on this node, or was k3s already installed and running when you added the --secrets-encryption flag?

> `400 Bad Request secrets-encrypt error ID 39582`

Check the k3s service log for an error message with this same ID.
