### ISSUE TITLE
Oracle ARM and Public IP -> Access API server from "outside"

### ISSUE THREAD

**Issue by lukasmrtvy** [k3s-io/k3s#6002]
**Environmental Info:**
K3s Version:  
- v1.24.3+k3s1

Node(s) CPU architecture, OS, and Version:  
- Ubuntu 22.04 LTS, Oracle Cloud ARM instance ( Linux arm 5.15.0-1011-oracle # 15-Ubuntu SMP Fri Jun 10 12:21:49 UTC 2022 aarch64 aarch64 aarch64 GNU/Linu ) 

Cluster Configuration:

- Single node

**Describe the bug:**

Its not possible to reach API server from "outside", from clients PC. VM instance does not have directly attached NIC with Public IP, its probably NAT, thus there might be some iptables rule missing.

**Steps To Reproduce:**

- `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik --no-deploy servicelb --advertise-address 144.24.188.XX --tls-san 144.24.188.XX" sh -`
- `kubectl get pods -A` from clients PC results in  `Unable to connect to the server: dial tcp 144.24.188.XX:6443: connect: no route to host`

**Expected behavior:**

`kubectl get pods -A` is working and API is reachable from "outside"

**Actual behavior:**

`kubectl get pods -A` is not working and API is not reachable from "outside"

**Additional context / logs:**
`iptables -F` and `iptables -X` will temporarily allow access to API server from "outside". Its not problem in Oracle infrastructure nor Security Groups.

```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 02:00:17:03:91:b4 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.246/24 metric 100 brd 10.0.0.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::17ff:fe03:91b4/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by Alehap** [comment]
You need to allow input port with your iptables too. Default policy is drop.
# iptables -I INPUT -p tcp -m tcp --dport 6443 -j ACCEPT
