### ISSUE TITLE
1.24.0-0 incompatible with Kubernetes v1.24.3+k3s1

### ISSUE THREAD

**Issue by gbrlins** [k3s-io/k3s#6008]
**Environmental Info:**
K3s Version: 
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 
Linux all-in1 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 node (all labels in one)

**Describe the bug:**
Error during installing Rancher helm chart. 

**Steps To Reproduce:**
- Installed K3s: 
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=stable K3S_KUBECONFIG_MODE=0644 INSTALL_K3S_SYMLINK=true sh -

- Rancher install:
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
kubectl create namespace cattle-system
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
helm repo add jetstack https://charts.jetstack.io 
helm repo update
helm install cert-manager jetstack/cert-manager -n cert-manager --create-namespace --version v1.7.1
helm install rancher rancher-latest/rancher -n cattle-system --set hostname="FQDN" --set bootstrapPassword="PASSWORD" --set replicas=1

**Expected behavior:**
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out

**Actual behavior:**
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.24.0-0 which is incompatible with Kubernetes v1.24.3+k3s1

**Additional context / logs:**
kubectl get pods -A
NAMESPACE      NAME                                       READY   STATUS      RESTARTS   AGE
kube-system    coredns-b96499967-4ddn6                    1/1     Running     0          23m
kube-system    local-path-provisioner-7b7dc8d6f5-pn7zv    1/1     Running     0          23m
kube-system    helm-install-traefik-crd-52qqc             0/1     Completed   0          23m
kube-system    metrics-server-668d979685-tj8bw            1/1     Running     0          23m
kube-system    helm-install-traefik-sgts8                 0/1     Completed   2          23m
kube-system    svclb-traefik-03f0c4d3-bx6qp               2/2     Running     0          22m
kube-system    traefik-7cd4fcff68-b65zg                   1/1     Running     0          22m
cert-manager   cert-manager-cainjector-7cb8669d6b-hlkr4   1/1     Running     0          16m
cert-manager   cert-manager-646c67487-kw7pg               1/1     Running     0          16m
cert-manager   cert-manager-webhook-696c5db7ff-j2mwm      1/1     Running     0          16m

**Comment by Oats87** [comment]
This is not a valid K3s issue. Please reopen if there is a specific K3s issue.
