### ISSUE TITLE
Certificates should be automatically regenerated without having to manually restart k3s

### ISSUE THREAD

**Issue by eradnab** [k3s-io/k3s#6009]
**Is your feature request related to a problem? Please describe.**

When the k3s certificates expire, or are about to expire, one must restart k3s to update them.

**Describe the solution you'd like**

I think this should be handled automatically without having to manually restart k3s. Even if it means k3s restarts itself automatically, although that's not desirable.

**Describe alternatives you've considered**

Currently the certificates will just expire - because I don't have a need to restart k3s. To work around this I have added a cron job which checks the cert expiry and if less than 90 days remain, it will restart k3s.  A sysadmin should not need to install or create additional tools to keep k3s working.

**Additional context**

I run systems with many months uptime - usually air gapped or in a shed in the desert 5 hours drive away - so they need to keep running without intervention.

**Comment by brandond** [comment]
The core Kubernetes components we're packaging don't support live certificate reloading, so this is not possible at the moment.

**Comment by eradnab** [comment]
Thanks for the reply and I agree with the best workarounds. I think my point is that k3s could package a workaround as standard, with option to not install the workaround.
