### ISSUE TITLE
Fail to deploy epinio on k3s when firewalld is enabled

### ISSUE THREAD

**Issue by mmartin24** [k3s-io/k3s#6024]
**Environmental Info:**
`K3s Version: k3s version v1.24.3+k3s1 (990ba0e8) go version go1.18.1`

Node(s) CPU architecture, OS, and Version: 
`Linux localhost.localdomain 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64 x86_64 GNU/Linux
`

Cluster Configuration:

**Describe the bug:**
I can't deploy [Epinio](https://epinio.io/) in openSUSE Leap 15.4 with k3s if `firewalld` is enabled

**Steps To Reproduce:**
- Install k3s on openSUSE Leap 15.4 with `firewalld` enabled
- Attempt to install epinio later following these instructions: 
    https://docs.epinio.io/howtos/install_epinio_on_k3s and later https://docs.epinio.io/installation/install_epinio

    Specific steps to save time in reproduction:

    ```
    # Install k3s

    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode \"0644\"" sh -  
    # At this point pod kube-system/metrics-server is bad state

    # Export k3s cluster config
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    # Get IP running from k3s
    kubectl get svc -n kube-system traefik -o jsonpath="{.status.loadBalancer.ingress[0]}"

    # Cert Manager installation
    kubectl create namespace cert-manager
    helm repo add jetstack https://charts.jetstack.io
    helm repo update
    helm install cert-manager --namespace cert-manager jetstack/cert-manager \
    --set installCRDs=true \
    --set extraArgs[0]=--enable-certificate-owner-ref=true

    # Install Epinio
    helm repo add epinio https://epinio.github.io/helm-charts
    helm upgrade --install epinio -n epinio --create-namespace epinio/epinio  --set global.domain=${K3S-IP}.sslip.io

    ```
- Once installed open dashboard link provided in the instructions at the end of the cli:
![image](https://user-images.githubusercontent.com/37271841/186143839-89da9c63-79d5-40e2-805a-2fe45505f682.png)

**Expected behavior:**
Epinio should be installed and all pods should be in healthy state

**Actual behavior:**
- Application is not correctly deployed showing a `Bad Gateway` error
- Pod `kube-system/metrics-server` is in an unhealthy state

![image](https://user-images.githubusercontent.com/37271841/186142592-be5204b3-bc64-42aa-9352-1b954fcc6ba1.png)
![image](https://user-images.githubusercontent.com/37271841/186142664-29fb36e4-2c44-40f5-9251-4721e48fff57.png)

**Additional context / logs:**
Please note I observe the `kube-system/metrics-server` pod in unhealthy state right after k3s in installed;
The problem is fixed if `firewalld` is disabled. Both UI and `kube-system/metrics-server` pod work and are in healthy state

```
mmartin@localhost:~> firewall-cmd --state
not running
```
![image](https://user-images.githubusercontent.com/37271841/186142901-b0c4b94e-f55b-4452-a891-189118e9a450.png)
![image](https://user-images.githubusercontent.com/37271841/186142989-59568853-8633-4157-9591-2da659cb0299.png)

Related issue: https://github.com/epinio/epinio/issues/1690

**Comment by brandond** [comment]
We don't recommend running k3s with firewalld enabled. Its rules will frequently interfere with intra-cluster traffic. If you want to experiment with opening the correct ports to the correct sources you are welcome to try to do so, but we do not support this or cover it in our documentation.

https://k3s-io.github.io/docs/docs/advanced#additional-preparation-for-red-hatcentos-enterprise-linux
