### ISSUE TITLE
some errors  when building k3s from source

### ISSUE THREAD

**Issue by heyu1207** [k3s-io/k3s#6031]
**Environmental Info:**
K3s Version: v1.22.13-k3s1

Node(s) CPU architecture, OS, and Version:  centos7

Cluster Configuration:

**Describe the bug:**

I tried to build k3s following the document: https://github.com/k3s-io/k3s/blob/master/BUILDING.md, but met some errors.
The output of the cmd "mkdir -p build/data && make download && make generate":

```
Step 11/28 : RUN GOPROXY=direct go get golang.org/x/tools/cmd/goimports@gopls/v0.7.0
 ---> Running in 47a153e5203a
go get golang.org/x/tools/cmd/goimports@gopls/v0.7.0: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": dial tcp 172.217.160.81:443: connect: connection refused
The command '/bin/sh -c GOPROXY=direct go get golang.org/x/tools/cmd/goimports@gopls/v0.7.0' returned a non-zero code: 1
FATA[0030] exit status 1                                
make: *** [download] 错误 1
```

I tried deleteing the line "RUN GOPROXY=direct go get golang.org/x/tools/cmd/goimports@gopls/v0.7.0" from"Dockerfile.dapper" , and then the output of the cmd "mkdir -p build/data && make download && make generate":
```
INFO[0071] docker cp /go/src/github.com/k3s-io/k3s/bin . 
INFO[0071] docker cp /go/src/github.com/k3s-io/k3s/dist . 
INFO[0071] docker cp /go/src/github.com/k3s-io/k3s/build/out build 
Error: No such container:path: k3s-NfpVarS:/go/src/github.com/k3s-io/k3s/build/out
INFO[0071] docker cp /go/src/github.com/k3s-io/k3s/pkg/static pkg 
INFO[0072] docker cp /go/src/github.com/k3s-io/k3s/pkg/deploy pkg 
INFO[0072] docker cp /go/src/github.com/k3s-io/k3s/pkg/generated pkg 
INFO[0072] docker cp /go/src/github.com/k3s-io/k3s/build/static build 
```
and the output of the cmd "make":
```
Running: go mod tidy
go: github.com/Microsoft/hcsshim@v0.9.2 (replaced by github.com/Microsoft/hcsshim@v0.8.20): Get "https://proxy.golang.org/github.com/%21microsoft/hcsshim/@v/v0.8.20.mod": dial tcp 172.217.163.49:443: connect: connection refused
FATA[0261] exit status 1                                
make: *** [ci] 错误 1
```

**Steps To Reproduce:**

- follow the document: https://github.com/k3s-io/k3s/blob/master/BUILDING.md

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Both of your commands are failing at the same point. Something is preventing your host from accessing the go module proxy server. Do you have a firewall or something else blocking your connection?

`https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": dial tcp 172.217.160.81:443: connect: connection refused`

**Comment by heyu1207** [comment]
I stop the firewalld.service, but I still can't access the websites. I wonder if there're some alternative websites and how to reconfigure the bulding process.

**Comment by xiaods** [comment]
@heyu1207 you came across GFW issue, don't worry.  you can buy a usa region server, you can build k3s.
