### ISSUE TITLE
   Issues list Install script doesn't work AMD64 GNU/Linux

### ISSUE THREAD

**Issue by huezo** [k3s-io/k3s#6035]
![fe](https://user-images.githubusercontent.com/15940634/186769146-c51ae345-a6ab-4269-be3d-cfa2396e7614.png)

`curl -sfL https://get.k3s.io | sh -`

**Comment by nicklasfrahm** [comment]
This is a duplicate, could you please close this issue in favor of #6033.

**Comment by briandowns** [comment]
Closing duplicate. Link above to original has resolution.
