### ISSUE TITLE
Deprecate cli flag for wireguard config

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#6038]
**Is your feature request related to a problem? Please describe.**

Deprecate this #5552 because it was already doable using `flannel-conf` flag with the following flannel config:
```
{
	"Network": "10.42.0.0/16",
	"EnableIPv6": false,
	"EnableIPv4": true,
	"Backend": {
	"Type": "wireguard",
	"PersistentKeepaliveInterval": 25,
	"Mode": "separate"
}
}
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cwayne18** [comment]
@rbrtbnfgl is this done? or should we move it to the Dec milestone?

**Comment by rbrtbnfgl** [comment]
yes it's done I forgot to update it.
