### ISSUE TITLE
use docker to run k3s failed to setup db

### ISSUE THREAD

**Issue by bangzhuzhu** [k3s-io/k3s#6051]
**Environmental Info:**
K3s Version: 

k3s v1.22.13+k3s1 (3daf4ed4)

Node(s) CPU architecture, OS, and Version: 

 docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 20
  Running: 17
  Paused: 0
  Stopped: 3
 Images: 47
 Server Version: 20.10.6+azure
 Storage Driver: lcow (linux) windowsfilter (windows)
  LCOW:
  Windows:
 Logging Driver: etwlogs
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.10021.amd64fre.rs5_release_svc_asdb.191223-1900)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.10877)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 18.25GiB
 Name: rn0601-Xrp02
 ID: UMHU:XBT2:KDGB:EQBW:WDQ3:E7OE:5OXH:QVP2:PEK6:IUKQ:YJYO:3MU6
 Docker Root Dir: X:\DockerState
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  registry.azs:5000
  127.0.0.0/8
 Live Restore Enabled: false
Cluster Configuration:

just try to start server
**Describe the bug:**

docker run --entrypoint /bin/sh rancher/k3s -c "/bin/k3s server &&true"

docker : WARNING: The requested image's platform (linux/amd64) does not match the detected host platform
(windows/amd64) and no specific platform was requested
    + CategoryInfo          : NotSpecified: (WARNING: The re...m was requested:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

time="2022-08-30T02:40:04Z" level=info msg="Starting k3s v1.22.13+k3s1 (3daf4ed4)"
time="2022-08-30T02:40:04Z" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2,
maxOpenConns=0, connMaxLifetime=0s"
time="2022-08-30T02:40:04Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
time="2022-08-30T02:40:04Z" level=error msg="failed to setup db: disk I/O error: invalid argument"

**Steps To Reproduce:**

- Installed K3s: 

docker run --entrypoint /bin/sh rancher/k3s -c "/bin/k3s server &&true"

**Expected behavior:**

start k3s server.

**Actual behavior:**

can't start
**Additional context / logs:**

**Comment by cwayne18** [comment]
K3s doesn't support windows at this time

**Comment by bangzhuzhu** [comment]
> K3s doesn't support windows at this time

But I use docker to run a linux container to run k3s, I think it's an acceptable way to use k3s.
