### ISSUE TITLE
wireguard interfaces don't get deleted when removing the cluster

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6053]
**Environmental Info:**
K3s Version: 

Any

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

flannel-backend: wireguard-native

**Describe the bug:**

The interfaces flannel-wg and flannel-wg-v6 stay after removing the cluster

**Steps To Reproduce:**

- Installed K3s: 

Install k3s with that flannel backend and then remove the cluster with `k3s-uninstall.sh`. If you are doing single-stack, one interface will remain there. If you are doing dual-stack two interfaces will remain

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
### Validated on k3s version v1.25.0-rc2+k3s1
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04

*Cluster Configuration:*
Single stack
Dual stack

  *Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
flannel-backend: wireguard-native
write-kubeconfig-mode: 644
token: TOKEN
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
flannel-ipv6-masq: true
```
 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml
2. Install k3s

**To validate:**
```
curl -fL https://get.k3s.io| INSTALL_K3S_VERSION=v1.25.0-rc2+k3s1 sh -s - server 
```
Run wg show to list the interfaces
```
sudo wg show
$ sudo wg show
interface: flannel-wg
  public key: KEY
  private key: (hidden)
  listening port: 51820

interface: flannel-wg-v6
  public key: KEY
  private key: (hidden)
  listening port: 51821
```
Uninstalled k3s and confirmed both interfaces are deleted
```
$ k3s-uninstall.sh 
$ sudo wg show
$ 
```
