### ISSUE TITLE
[Epic] Add Integration Test for all server/agent flags

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#6057]
Similar to https://github.com/k3s-io/k3s/issues/6056, but this is for a single test that uses ALL (or the most possible) configuration flags. 

**EDIT 04/11/23**
**Integration Server Flags Testing Status**
| Server flags: | | | 
| - | - | - |
| <ul><li>- [x] disable</li></ul> | <ul><li>- [x] disable-network-policy</li></ul> | <ul><li>- [x] with-node-id</li></ul> |
| <ul><li>- [x] write-kubeconfig-mode</li></ul> | <ul><li>- [x] flannel-external-ip</li></ul> | <ul><li>- [x] selinux</li></ul> |
| <ul><li>- [x] cluster-init</li></ul> | <ul><li>- [x] disable-scheduler</li></ul> | <ul><li>- [x] node-taint</li></ul> |
| <ul><li>- [x] data-dir</li></ul> | <ul><li>- [x] token</li></ul> | <ul><li>- [x] server</li></ul> |
| <ul><li>- [x] node-label</li></ul> | <ul><li>- [x] cluster-cidr</li></ul> | <ul><li>- [x] node-name</li></ul> |
| <ul><li>- [x] flannel-ipv6-masq</li></ul> | <ul><li>- [x] node-ip</li></ul> | <ul><li>- [x] kubelet-arg</li></ul> |
| <ul><li>- [x] bind-address</li></ul> | <ul><li>- [x] snapshotter</li></ul> | <ul><li>- [x] secrets-encryption</li></ul> |
| <ul><li>- [x] node-external-ip</li></ul> | <ul><li>- [x] disable-helm-controller</li></ul> | <ul><li>- [x] flannel-iface</li></ul> |
| <ul><li>- [x] service-cidr</li></ul> | <ul><li>- [x] multi-cluster-cidr</li></ul> | <ul><li>- [x] tls-san</li></ul> |
| <ul><li>- [x] flannel-backend</li></ul> | <ul><li>- [x] etcd-arg</li></ul> | <ul><li>- [x] prefer-bundled-bin</li></ul> |
| <ul><li>- [ ] debug</li></ul> | <ul><li>- [x] kube-proxy-arg</li></ul> | <ul><li>- [x] kube-controller-manager-arg</li></ul> |
| <ul><li>- [ ] write-kubeconfig</li></ul> | <ul><li>- [x] etcd-snapshot-retention</li></ul> | <ul><li>- [ ] log</li></ul> |
| <ul><li>- [ ] agent-token-file</li></ul> | <ul><li>- [x] kube-apiserver-arg</li></ul> | <ul><li>- [ ] disable-cloud-controller</li></ul> |
| <ul><li>- [ ] resolv-conf</li></ul> | <ul><li>- [ ] etcd-expose-metrics</li></ul> | <ul><li>- [ ] lb-server-port</li></ul> |
| <ul><li>- [ ] https-listen-port</li></ul> | <ul><li>- [ ] advertise-port</li></ul> | <ul><li>- [ ] cluster-dns</li></ul> |
| <ul><li>- [x] etcd-snapshot-name</li></ul> | <ul><li>- [ ] default-local-storage-path</li></ul> | <ul><li>- [ ] vmodule</li></ul> |
| <ul><li>- [x] kube-scheduler-arg</li></ul> | <ul><li>- [x] kube-cloud-controller-manager-arg</li></ul> | <ul><li>- [ ] token-file</li></ul> |
| <ul><li>- [x] etcd-disable-snapshots</li></ul> | <ul><li>- [x] etcd-snapshot-schedule-cron</li></ul> | <ul><li>- [x] etcd-snapshot-dir</li></ul> |
| <ul><li>- [ ] disable-kube-proxy</li></ul> | <ul><li>- [ ] advertise-address</li></ul> | <ul><li>- [ ] agent-token</li></ul> |
| <ul><li>- [ ] datastore-cafile</li></ul> | <ul><li>- [x] etcd-snapshot-compress</li></ul> | <ul><li>- [ ] alsologtostderr</li></ul> |
| <ul><li>- [ ] servicelb-namespace</li></ul> | <ul><li>- [ ] egress-selector-mode</li></ul> | <ul><li>- [ ] config</li></ul> |
| <ul><li>- [ ] protect-kernel-defaults</li></ul> | <ul><li>- [ ] enable-pprof</li></ul> | <ul><li>- [ ] service-node-port-range</li></ul> |
| <ul><li>- [ ] cluster-reset-restore-path</li></ul> | | |

The following flags are unsuited for Integration test 
| Not For Integration Test | | |
| - | - | - |
| :x: system-default-registry | :x: cluster-domain | :x: etcd-s3-folder |
| :x: private-registry | :x: etcd-s3-region | :x: etcd-s3 |
| :x: datastore-endpoint | :x: image-credential-provider-bin-dir | :x: docker |
| :x: datastore-certfile | :x: etcd-s3-secret-key | :x: pause-image |
| :x: etcd-s3-access-key | :x: flannel-cni-conf | :x: rootless |
| :x: datastore-keyfile | :x: etcd-s3-insecure | :x: etcd-s3-skip-ssl-verify |
| :x: container-runtime-endpoint | :x: image-credential-provider-config | :x: etcd-s3-endpoint |
| :x: etcd-s3-endpoint-ca | :x: etcd-s3-bucket | :x: etcd-s3-timeout |
| :x: flannel-conf | :x: cluster-reset | |

**Comment by caroline-suse-rancher** [comment]
@rancher-max is this still in progress?

**Comment by rancher-max** [comment]
Yes I don't think any of us have picked it up to start working yet.

**Comment by caroline-suse-rancher** [comment]
@osodracnai Hey! Are you still working on this? The last linked PR I see is from May. Thanks!

**Comment by osodracnai** [comment]
@caroline-suse-rancher Yeah, but not only focused on it. If you want i can make it my priority.

**Comment by caroline-suse-rancher** [comment]
@osodracnai No, no worries! Just asking for a status update, that sounds good :)

**Comment by dereknola** [comment]
Closing this as complete, all easily testable flags via integration test have been covered.
