### ISSUE TITLE
Add Integration Test for common/uncommon server/agent flag options

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#6058]
Similar to https://github.com/k3s-io/k3s/issues/6056. This should add tests for different options that we see. We still need to define what is common vs. uncommon, but for example, a lot of users deploy k3s with traefik and svclb disabled, so that is one configuration to have in the tests here. 

Feel free to add configurations as comments to this issue for tracking and to make it easier to add tests for them!

To start:
```
k3s server --disable=traefik,servicelb,metrics-server,local-storage,coredns --disable-network-policy \
--disable-agent --disable-cloud-controller --flannel-backend=none --disable-scheduler \
--kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle \
--kube-apiserver-arg=endpoint-reconciler-type=none
```

**Comment by dereknola** [comment]
Agentless servers is covered by an e2e test: https://github.com/k3s-io/k3s/pull/7331
Disable traefik is covered by an integration test: https://github.com/k3s-io/k3s/pull/5630

**Comment by caroline-suse-rancher** [comment]
Closing this - we can create new issues that are more specific to the flags still needing tests.
