### ISSUE TITLE
Service IP family must match public address family

### ISSUE THREAD

**Issue by samip5** [k3s-io/k3s#6063]
**Environmental Info:**
K3s Version: v1.24.4+k3s1 (c3f830e9)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

aarch64 and amd64, all running Ubuntu 22.04.

Cluster Configuration:

1 server, 4 agents

**Describe the bug:**
Unable to set the default IP family to be IPv6.

**Steps To Reproduce:**

- Installed K3s: Using [k3s-ansible](https://github.com/PyratLabs/ansible-role-k3s) role.

Server systemd unit:
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server --disable-kube-proxy --config /etc/rancher/k3s/config.yaml 
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

Server config:
```
cluster-cidr: fddf:f7bc:9670::/48,10.244.0.0/16
disable:
- flannel
- traefik
- servicelb
- metrics-server
- local-storage
disable-cloud-controller: true
disable-network-policy: true
docker: false
etcd-expose-metrics: true
flannel-backend: none
kube-controller-manager-arg:
- 'bind-address=::'
kube-scheduler-arg:
- 'bind-address=::'
kubelet-arg:
- feature-gates=GracefulNodeShutdown=true
- feature-gates=MixedProtocolLBService=true
node-ip: 2001:67c:1104:e08d:e89b:6305:d07e:123e,10.0.105.10
service-cidr: 2001:67c:1104:fdb::/112,10.96.0.0/16
tls-san:
- 10.0.105.10
- 2001:67c:1104:e08d:e89b:6305:d07e:123e
write-kubeconfig-mode: '644
```

**Expected behavior:**

It would not error out.

**Actual behavior:**

It errors out on server, with an error about IP family must match.

**Additional context / logs:**

```
Aug 31 00:20:48 k8s-master1 k3s[32999]: Error: error creating bootstrap controller: service IP family "2001:67c:1104:fdb::/112" must match public address family "10.0.105.10"
Aug 31 00:20:48 k8s-master1 k3s[32999]: time="2022-08-31T00:20:48+03:00" level=fatal msg="apiserver exited: error creating bootstrap controller: service IP family \"2001:67c:1104:fdb::/112\" must match public address family \"10.0.105.10\""
```

**Comment by brandond** [comment]
This appears to be an error somewhere in the core Kubernetes apiserver code. I suspect there's some additional argument that you'll need to pass to kube-apiserver to properly order the endpoint addresses to match the rest of the addresses you're using.

**Comment by samip5** [comment]
That's indeed a bug in upstream Kubernetes: https://github.com/kubernetes/kubernetes/issues/111671

Current workaround is to specify manually the advertise-address for apiserver to match.

**Comment by samip5** [comment]
Current issue is that the internal API k8s svc is not serving the certificate with the IP address of svc.

CoreDNS inside cluster:
`WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://[2001:67c:1104:fdb::1]:443/version": x509: certificate is valid for 10.0.105.10, 10.96.0.1, 127.0.0.1, 2001:67c:1104:e08d:e89b:6305:d07e:123e, ::1, not 2001:67c:1104:fdb::1`

**Comment by dereknola** [comment]
Thanks for bringing this issue up. I am closing this issue as it has been identified as being tracked upstream.
