### ISSUE TITLE
not able to configure containerd 

### ISSUE THREAD

**Issue by fenio** [k3s-io/k3s#6068]
https://rancher.com/docs/k3s/latest/en/advanced/#configuring-containerd says that config for containerd should be in /var/lib/rancher/k3s/agent/etc/containerd/config.toml.
That's not the case with k3s 1.24.4+k3s1.

I tried to find config in several places but I think it simply doesn't exist anymore. So I'm not able to change any containerd settings.
If that's intentional then documentation is misleading.

**Comment by brandond** [comment]
That file will be created in that directory after starting k3s, but only if you’re using the containerd built in to k3s. If you’re using your own container runtime endpoint, or using docker, then none of this matters. As the docs say, you need to create a different file in that same directory (config.toml.tmpl, NOT config.toml) if you want to customize the template... so it doesn’t really matter if the toml file exists yet or not.

However, if you want to change the snapshotter, there’s a dedicated flag for that: [`--snapshotter`](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#:~:text=or%20docker%20sandbox-,--snapshotter,-value)
