### ISSUE TITLE
k3s v1.24.4+k3s1 cann't use custom cni

### ISSUE THREAD

**Issue by lazywhite** [k3s-io/k3s#6083]
**Environmental Info:**
K3s Version:  1.24.4+k3s1

Node(s) CPU architecture, OS, and Version: 

os: centos7.9
arch: x86_64

Cluster Configuration:

1 master
**Describe the bug:**

run server with this command
k3s server  --flannel-backend=none --disable-network-policy 

but node won't be ready, then calico can't be installed because node is not ready

 E0901 20:27:43.955758    3037 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by alexellis** [comment]
Have you tried out `k3s check-config` yet? Perhaps there's a network clash with the CNI driver you're trying to use and another adapter you're running?

**Comment by manuelbuil** [comment]
How are you installing calico?

**Comment by brandond** [comment]
> calico can't be installed because node is not ready

Calico should tolerate the NotReady taint, since it is the CNI and the node will (by definition) not be ready until after it is installed. I suspect there is a problem in your install process - as @manuelbuil asked, what steps are you following to install calico?

**Comment by lazywhite** [comment]
node not ready is because of kernel missing iptables comment module,  not  related with custom cni
