### ISSUE TITLE
iptables rule failed to add 

### ISSUE THREAD

**Issue by lazywhite** [k3s-io/k3s#6093]
**Environmental Info:**
K3s Version:  1.24.4+k3s1
iptables: v1.8.7 (legacy)
os: ubuntu 20.04 arm64

```
E0902 17:55:34.945527    3747 proxier.go:874] "Failed to ensure chain jumps" err=<
        error checking rule: exit status 2: iptables v1.8.4 (legacy): Couldn't load match `comment':No such file or directory

        Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0902 17:55:34.945597    3747 proxier.go:858] "Sync failed" retryingTime="30s"
I0902 17:55:34.961991    3747 kube.go:357] Skip setting NodeNetworkUnavailable
time="2022-09-02T17:55:34+08:00" level=info msg="Wrote flannel subnet file to /run/flannel/subnet.env"
time="2022-09-02T17:55:34+08:00" level=info msg="Running flannel backend."
I0902 17:55:34.964430    3747 vxlan_network.go:61] watching for new subnet leases
E0902 17:55:34.968743    3747 proxier.go:874] "Failed to ensure chain jumps" err=<
        error checking rule: exit status 2: ip6tables v1.8.4 (legacy): Couldn't load match `comment':No such file or directory

        Try `ip6tables -h' or 'ip6tables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
```

**Comment by brandond** [comment]
https://github.com/kubernetes-sigs/kind/issues/1461#issuecomment-748605056

Your kernel appears to be missing `CONFIG_NETFILTER_XT_MATCH_COMMENT` - did you build your own kernel without including this, or perhaps need to reboot after applying kernel updates?

**Comment by lazywhite** [comment]
> [kubernetes-sigs/kind#1461 (comment)](https://github.com/kubernetes-sigs/kind/issues/1461#issuecomment-748605056)
> 
> Your kernel appears to be missing `CONFIG_NETFILTER_XT_MATCH_COMMENT` - did you build your own kernel without including this option, or perhaps need to reboot after applying kernel updates?

I'm using firefly roc-rk3588s-pc arm64 opensource motherboard, they turn off this config on default..
