### ISSUE TITLE
No internet connectivity after starting k3s

### ISSUE THREAD

**Issue by glover279** [k3s-io/k3s#6098]
**Environmental Info:**
K3s Version:  v1.24.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux proxmox 5.15.30-2-pve #1 SMP PVE 5.15.30-3 (Fri, 22 Apr 2022 18:08:27 +0200) x86_64 GNU/Linux

Cluster Configuration: 1 server, 2 agents

**Describe the bug:**
After starting k3s internet connectivity is lost.

I am running an Opnsense firewall in a VM using KVM (proxmox)
The Opnsense VM has two NICs assigned to it, one for LAN and one for WAN.
After k3s starts I can connect to the LAN interface but the WAN interface loses all connectivity.

Below are the Iptables rules generated when k3s is started. Could these be the issue?
https://pastebin.com/JvydhGu4

Please let me know what other information I can provide
**Steps To Reproduce:**

- Installed K3s: - Traefik disabled, longhorn installed, metallb installed.

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by glover279** [comment]
Tried specifying the flannel interface with --flannel-iface but still no changes.
Please see the startup logs below:
https://pastebin.com/aUUuJ0fa

**Comment by brandond** [comment]
In general, Kubernetes and most CNIs don't work well with iptables-based firewalls deployed to the same host. Kubernetes makes extensive use of iptables to manage traffic between pods, nodes, and services, and it is likely to cause problems with other things that expect to have sole ownership of iptables rules on a host.

**Comment by glover279** [comment]
The firewall does not manage the iptables on the host OS. The opnsense firewall runs in a KVM virtual machine on the host.
Please let me know if there is any more information I can provide. Thanks

**Comment by brandond** [comment]
`Linux proxmox 5.15.30-2-pve`

Are you really running k3s on proxmox? I'm not sure I've ever seen that; nor am I familiar with what distro it is based on. Are you sure that it doesn't have anything else using iptables, or attempting to manage the network interfaces in a way that is incompatible with running containers on the node?
