### ISSUE TITLE
Install calico  

### ISSUE THREAD

**Issue by xxdyu** [k3s-io/k3s#6100]
**Environmental Info:**
K3s Version: v1.24.4+k3s1

Node(s) CPU architecture, OS, and Version: Linux master 5.19.0-1.el7.elrepo.x86_64

Cluster Configuration: 1  servers, 2 agents

**Describe the bug:**  

Install calico   need "container_settings": {
              "allow_ip_forwarding": true
          }

**Steps To Reproduce:**

- Installed K3s: 
- server：
      curl -sfL https://get.k3s.io | sh -s - server \
        --docker \
        --token=123456 \
        --flannel-backend=none \
        --disable-network-policy \
        --disable selinux \
        --cluster-cidr=192.168.0.0/16 \
        --kube-proxy-arg=proxy-mode=ipvs \
        --cluster-init
-agent：
       curl -sfL https://get.k3s.io | sh K3S_URL=https://master:6443 K3S_TOKEN=123456 sh -s - agent \
        --docker \
        --kube-proxy-arg=proxy-mode=ipvs
-- kubectl get nodes
![image](https://user-images.githubusercontent.com/32918557/188542088-c6659e54-5592-4c82-bf39-3c9e02a85c8b.png)
--     wget  https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
      add "container_settings": {
              "allow_ip_forwarding": true
          }
   kubectl apply -f calico.yaml
-- After a while
  
![image](https://user-images.githubusercontent.com/32918557/188542700-6ae32805-bd41-4744-b840-59f0189b6446.png)
-- question
    
![image](https://user-images.githubusercontent.com/32918557/188542743-48eae67e-4811-47be-b19d-6372e27f92c7.png)
-- agent log
   
![image](https://user-images.githubusercontent.com/32918557/188542887-12bcb6c1-c26c-4f0d-a69b-3a168205e3c3.png)

**Comment by brandond** [comment]
Something is blocking the agent's access to port 6443 on the server. Does the installation initially work, and then fail later? Do you have any host-based or external firewalls in place between the two nodes?

**Comment by xxdyu** [comment]
fananl  have the same problem，The initial installation was successful，There was a problem after svclb starting，add --disable servicelb is ok

**Comment by xxdyu** [comment]
I have another question: how to disable selinux
cat > /etc/rancher/k3s/registries.yaml <<EOF
 selinux: false
EOF
Can this method work?

**Comment by brandond** [comment]
It is off by default. Did you want to disable it on the hosts instead of in k3s?

**Comment by xxdyu** [comment]
thanks，Every time I deploy, it will load k3s-selinux, I thought it was always on
