### ISSUE TITLE
Convert depracted flags to fatal errros for v1.25

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#6110]
Component of https://github.com/k3s-io/k3s/issues/5940, with v1.25, we need to transition the following flags to give fatal errors:
-  `no-flannel`
- `cluster-secret`
- `no-deploy`

**Comment by bguzman-3pillar** [comment]
### Validated on rc `v1.25.0-rc2+k3s1`
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
v1.25.0-rc2+k3s1
```
 
*Cluster Configuration:*

```
1 server
```
  
## Testing Steps

1. Run the install command using those flags `--no-flannel, --cluster-secret, --no-deploy`
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.0-rc2+k3s1 INSTALL_K3S_EXEC="server --no-deploy coredns" sh -
```
- Look for the error msg `no-deploy flag is deprecated. Use --skip-deploy instead.`
```
$ journalctl -xeu k3s.service | grep -i "is deprecated"
Sep 08 20:30:23 ip-172-31-44-235 k3s[12107]: time="2022-09-08T20:30:23Z" level=fatal msg="no-deploy flag is deprecated. Use --skip-deploy instead."
```


2. Run `$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.0-rc2+k3s1 INSTALL_K3S_EXEC="server --cluster-secret secret" sh -`

- Look for the error msg `cluster-secret is deprecated. Use --token instead.`
```
$ journalctl -xeu k3s.service | grep -i "is deprecated"
Sep 08 20:32:52 ip-172-31-44-235 k3s[12870]: time="2022-09-08T20:32:52Z" level=fatal msg="cluster-secret is deprecated. Use --token instead."
```


3. Run `$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.0-rc2+k3s1 INSTALL_K3S_EXEC="server --no-flannel" sh -`
- Look for the error msg `no-flannel is deprecated. Use --flannel-backend=none instead.`
```
$ journalctl -xeu k3s.service | grep -i "is deprecated"
Sep 08 20:21:01 ip-172-31-44-235 k3s[9252]: time="2022-09-08T20:21:01Z" level=fatal msg="no-flannel is deprecated. Use --flannel-backend=none instead."
```
 
 
**Validation Results:**

All of these FATAL error/messages expected were shown correctly using those flags.

`no-flannel is deprecated. Use --flannel-backend=none instead.`
`cluster-secret is deprecated. Use --token instead.`
`no-deploy flag is deprecated. Use --skip-deploy instead.`

**Comment by ShylajaDevadiga** [comment]
Re-opening due to incorrect log message.

We do not have --skip-deploy instead **--no-deploy is now replaced with --disable** flag

```
Sep 09 03:07:34 ip-172-31-10-100 k3s[21999]: Incorrect Usage: flag provided but not defined: -skip-deploy
Sep 09 03:07:34 ip-172-31-10-100 k3s[21999]: NAME:
Sep 09 03:07:34 ip-172-31-10-100 k3s[21999]:    k3s server - Run management server
```

**Comment by bguzman-3pillar** [comment]
Validated on `v1.25.2-rc1+k3s1`

Logs showed correctly using `no-deploy flag is deprecated. Use --disable instead.`

Steps:
1. Install K3S `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.2-rc1+k3s1 INSTALL_K3S_EXEC="server --no-deploy coredns" sh -`
2. Check logs using `journalctl -xeu k3s.service`

Expected message: `no-deploy flag is deprecated. Use --disable instead.` 
Actual result:
```
$ journalctl -xeu k3s.service | grep -i "disable instead"
Sep 22 20:46:43 ip-172-31-45-201 k3s[6536]: time="2022-09-22T20:46:43Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead."
Sep 22 20:46:48 ip-172-31-45-201 k3s[6553]: time="2022-09-22T20:46:48Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead."
```
