### ISSUE TITLE
Access to pod logs is forbidden

### ISSUE THREAD

**Issue by madduci** [k3s-io/k3s#6123]
**Environmental Info:**
K3s Version: 
```sh
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1
```

Node(s) CPU architecture, OS, and Version: 
Linux k3s-Box 5.8.0-1033-azure 20.04.1-Ubuntu x86_64 GNU/Linux

Cluster Configuration:
1 single node installed using the Script from k3s website

**Describe the bug:**

It's impossible to access the logs of a running pod. It gets permanently the following error:

```sh
$> kubectl -n test logs test-5db84856b-p84l2
Error from server: Get "https://172.25.169.251:10250/containerLogs/test/test-5db84856b-p84l2/nginx": Forbidden
```

**Steps To Reproduce:**

In a fresh cluster, 

```sh
$> kubectl create namespace test
$> kubectl create deployment test --image=nginx:latest --port=80 -n test
$> kubectl logs test-[generatedId]
Error from server: Get "https://172.25.169.251:10250/containerLogs/default/test-5db84856b-2sblw/nginx": Forbidden
```

**Expected behavior:**

Logs of Containers in a Pod are shown without errors.

**Actual behavior:**

A message with "Forbidden" is shown

**Additional context / logs:**

Logs from k3s (enabled with `--log`)

`E0913 11:39:27.419348  104927 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://172.25.169.251:10250/containerLogs/cloud-workshop/test-5db84856b-p84l2/nginx", Err:(*errors.errorString)(0xc005477290)}: Get "https://172.25.169.251:10250/containerLogs/cloud-workshop/test-5db84856b-p84l2/nginx": Forbidden`

**Comment by brandond** [comment]
Do you have a proxy configured on your node - are HTTP_PROXY/HTTPS_PROXY/NO_PROXY variables set in one of `/etc/default/k3s`, `/etc/sysconfig/k3s`, or `/etc/systemd/system/k3s.env`? If so, you should be sure that your node address ranges (172.25.0.0/16, for example) are included in the NO_PROXY variable.

**Comment by madduci** [comment]
After trying different configurations, I've added to NO_PROXY in the `/etc/systemd/system/k3s.env` these values:

`NO_PROXY='127.0.0.1,localhost,172.0.0.0/8,10.0.0.0/8'` 

and it worked
