### ISSUE TITLE
Add `v1.25` in the release channels list

### ISSUE THREAD

**Issue by guidoiaquinti** [k3s-io/k3s#6124]
First of all, congratulations on the v1.25 release 🎉  and thank you for all your work! 

**Is your feature request related to a problem? Please describe.**
`v1.25` has been released but it is not present as a [dedicated release channel](https://update.k3s.io/v1-release/channels). Users can only use 1.25 via `latest`.

**Describe the solution you'd like**
Have a dedicated channel for 1.25 (like we have for 1.16 and above). 

As this is a duplicate/recurring issue (see https://github.com/k3s-io/k3s/issues/5746) could be possible to make sure a new channel is created when a new version is released?

**Describe alternatives you've considered**
Do nothing

**Additional context**
N/A. 

Thank you! 🙇

**Comment by VestigeJ** [comment]
$ sudo INSTALL_K3S_CHANNEL=v1.25 ./install-k3s.sh 
```
[INFO]  Finding release for channel v1.25
[INFO]  Using v1.25.0+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.0+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.25.0+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

$ k3s -v
```
k3s version v1.25.0+k3s1 (26e94057)
go version go1.19
```

$ kgn
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-1-1-1-12   Ready    control-plane,etcd,master   4m   v1.25.0+k3s1
```

**Comment by guidoiaquinti** [comment]
Thank you @galal-hussein and @VestigeJ!

**Comment by VestigeJ** [comment]
De nada, señor
