### ISSUE TITLE
Behavior change for `INSTALL_K3S_SKIP_DOWNLOAD` in install.sh

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#6128]
_Originally reported by [sauerborn-git](https://github.com/sauerborn-git) in https://github.com/k3s-io/k3s/pull/6126_

**Describe the bug:**

A behavior change was introduced with: https://github.com/k3s-io/k3s/pull/6003/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fL486-R486

A change was necessary to get `install` tests working on PR checks, but "this" particular way of doing it has proved confusing to users. A new way which does not affect the original `SKIP_DOWNLOAD` functionality is required.

**Steps To Reproduce:**

- Installed K3s: 

Executing install with INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_BIN_DIR=/usr/bin files/install.sh on an offline environment, I get the following error with the latest version:

    "stderr": "Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - \"Could not resolve host: mirrorlist.centos.org; Name or service not known\"\n\n\n One of the configured repositories failed (Unknown),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=<repoid> ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable <repoid>\n        or\n            subscription-manager repos --disable=<repoid>\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true\n\nCannot find a valid baseurl for repo: base/7/x86_64",
    "stderr_lines": [
        "Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was",
        "14: curl#6 - \"Could not resolve host: mirrorlist.centos.org; Name or service not known\"",
        "",
        "",
        " One of the configured repositories failed (Unknown),",
        " and yum doesn't have enough cached data to continue. At this point the only",
        " safe thing yum can do is fail. There are a few ways to work \"fix\" this:",
        "",
        "     1. Contact the upstream for the repository and get them to fix the problem.",
        "",
        "     2. Reconfigure the baseurl/etc. for the repository, to point to a working",
        "        upstream. This is most often useful if you are using a newer",
        "        distribution release than is supported by the repository (and the",
        "        packages for the previous distribution release still work).",
        "",
        "     3. Run the command with the repository temporarily disabled",
        "            yum --disablerepo=<repoid> ...",
        "",
        "     4. Disable the repository permanently, so yum won't use it by default. Yum",
        "        will then just ignore the repository until you permanently enable it",
        "        again or use --enablerepo for temporary usage:",
        "",
        "            yum-config-manager --disable <repoid>",
        "        or",
        "            subscription-manager repos --disable=<repoid>",
        "",
        "     5. Configure the failing repository to be skipped, if it is unavailable.",
        "        Note that yum will try to contact the repo. when it runs most commands,",
        "        so will have to try and fail each time (and thus. yum will be be much",
        "        slower). If it is a very temporary problem though, this is often a nice",
        "        compromise:",
        "",
        "            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true",
        "",
        "Cannot find a valid baseurl for repo: base/7/x86_64"

**Expected behavior:**

K3s should not attempt to download anything when `SKIP_DOWNLOAD=true`

**Actual behavior:**

It will attempt to download SELINUX RPMS

**Workaround**
Until this is resolved, a workaround exists:
```
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_BIN_DIR=/usr/bin files/install.sh
```

**Additional context / logs:**

**Comment by rancher-max** [comment]
### Validated using latest install script 
 
## Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a && cat /etc/os-release
Linux ip-172-31-42-181.us-east-2.compute.internal 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```
 
*Cluster Configuration:*

1 server
 
*Config.yaml:*

N/A
 
*Additional files*

N/A
 
## Testing Steps

1. Bring up an airgap node
2. Bring up a non-airgap (bastion) node
3. On the bastion node, download the required files:
- k3s binary from v1.24.4+k3s1: `wget https://github.com/k3s-io/k3s/releases/download/v1.24.4%2Bk3s1/k3s`
- Install.sh from get.k3s.io: `wget -O new-install.sh https://get.k3s.io/`
- (for replication) install.sh from previous release: `wget https://raw.githubusercontent.com/k3s-io/k3s/v1.25.0%2Bk3s1/install.sh`
4. Copy the files to the airgap node and move the k3s binary to the bin dir
5. Attempt to install k3s: `INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_BIN_DIR=/usr/bin ./install.sh`
 
 
**Replication Results:**
- RPM download is not skipped
```
$ INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_BIN_DIR=/usr/bin ./install.sh 
[INFO]  Skipping k3s download and verify
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Rancher K3s Common (stable)                                                                                                                                                                                   0.0  B/s |   0  B     02:00    
Errors during downloading metadata for repository 'rancher-k3s-common-stable':
  - Curl error (28): Timeout was reached for https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/repodata/repomd.xml [Connection timed out after 30000 milliseconds]
Error: Failed to download metadata for repo 'rancher-k3s-common-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
 
**Validation Results:**
- RPM download is skipped:
```
$ INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_BIN_DIR=/usr/bin ./new-install.sh 
[INFO]  Skipping k3s download and verify
[INFO]  Skipping installation of SELinux RPM
[ERROR]  Failed to find the k3s-selinux policy, please install:
    dnf install -y container-selinux
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-0.4-1.el8.noarch.rpm
```
