### ISSUE TITLE
Worker agent: "failed to get CA certs: EOF

### ISSUE THREAD

**Issue by Anddiy** [k3s-io/k3s#6133]
Hello Guys, i have a HA multi-master k3s cluster running but now im with trouble to add the workers node to the cluster. 

All of the machines are running on a CentOS-8 (8.3.2011) using the v1.21.14+k3s1 version of the K3S ( I need to use this version because of my future application.)

My load balancer is running on another machine named lacrosse5, and here im running a simple nginx to do the load-balance stuff:

```
load_module /usr/lib64/nginx/modules/ngx_stream_module.so;

events {}

stream {
  upstream k3s_servers {
    server 10.1.8.1:6443;
    server 10.1.9.67:6443;
  }

  server {
    listen 6443;
    proxy_pass k3s_servers;
  }
}
```
I have 2 masters node ( Working fine)

```
root@kraken1:/var/lib/rancher/k3s/server/tls#  kubectl get nodes
NAME                    STATUS   ROLES                  AGE    VERSION
tardis7.icarotech.com   Ready    control-plane,master   123m   v1.21.14+k3s1
kraken1.icarotech.com   Ready    control-plane,master   131m   v1.21.14+k3s1
```

And i need to add my 3 workers node, i've installed the K3S-AGENT using this setup:
```
export K3S_KUBECONFIG_MODE="644"
export K3S_URL="https://10.1.8.184:6443"
export INSTALL_K3S_VERSION="v1.21.14+k3s1" 
export K3S_TOKEN="myk3stoken"
export INSTALL_K3S_SKIP_SELINUX_RPM=true
curl -sfL https://get.k3s.io | sh - 
```
But the installation is stuck on starting k3s-agent, when i stoped the command with a crtl+c and open the logs to see what happens, i got this: 

```
Sep 13 21:22:27 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:27.915378610-03:00" level=info msg="Running load balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [10.1.8.184:6443]"
Sep 13 21:22:27 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:27.917862150-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46928->127.0.0.1:6444: read: connection re>
Sep 13 21:22:30 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:30.946326468-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46936->127.0.0.1:6444: read: connection re>
Sep 13 21:22:33 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:33.954775137-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46944->127.0.0.1:6444: read: connection re>
Sep 13 21:22:36 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:36.961402378-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46952->127.0.0.1:6444: read: connection re>
Sep 13 21:22:39 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:39.969165874-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46960->127.0.0.1:6444: read: connection re>
Sep 13 21:22:42 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:42.977317762-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46968->127.0.0.1:6444: read: connection re>
Sep 13 21:22:45 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:45.985400529-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46976->127.0.0.1:6444: read: connection re>
Sep 13 21:22:48 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:48.993222621-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46984->127.0.0.1:6444: read: connection re>
Sep 13 21:22:52 tardis10.icarotech.com k3s[14334]: time="2022-09-13T21:22:52.001395868-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:46992->127.0.0.1:6444: read: connection re>
```

I already dig some posts here that say that the solution to this is to change the /etc/systemd/system/k3s-agent.service.env to the IP, but im already done that and the error continues, here a sample of my k3s-agent.service.env:

```
K3S_KUBECONFIG_MODE="644"
K3S_TOKEN="myk3stoken"
K3S_URL="https://10.1.8.184:6443"
```

The ip here it's the same as my load balancer, so what is happening here?

**Comment by brandond** [comment]
Can you successfully `curl -vs https://10.1.8.184:6443/cacerts` from the agent?

You should also be aware that the 1.21 release has been end of support for about 4 months; 1.22 is almost end of support as well. I would recommend against targeting either of these versions for future application deployments.

**Comment by Anddiy** [comment]
> Can you successfully `curl -vs https://10.1.8.184:6443/cacerts` from the agent?
> 
> You should also be aware that the 1.21 release has been end of support for about 4 months; 1.22 is almost end of support as well. I would recommend against targeting either of these versions for future application deployments.

Hello @brandond , i've tried to curl the host and get this, can you help me solve this? 

```
root@tardis10:~#  curl -vs https://10.1.8.184:6443/cacerts
*   Trying 10.1.8.184...
* TCP_NODELAY set
* connect to 10.1.8.184 port 6443 failed: No route to host
* Failed to connect to 10.1.8.184 port 6443: No route to host
* Closing connection 0
```

About the k3s version, i know the support for this version has ended, i use it because of the kubernetes version, my application only runs on a 1.21.x kubernetes version, its possible to upgrade the k3s but not update the kubernetes?

**Comment by brandond** [comment]
> connect to 10.1.8.184 port 6443 failed: No route to host

Why don't your hosts have a route to the load balancer? I'm not sure how to help with that.

> its possible to upgrade the k3s but not update the kubernetes?

No, K3s releases are built around Kubernetes releases

**Comment by Anddiy** [comment]
> > connect to 10.1.8.184 port 6443 failed: No route to host
> 
> Why don't your hosts have a route to the load balancer? I'm not sure how to help with that.
> 
> > its possible to upgrade the k3s but not update the kubernetes?
> 
> No, K3s releases are built around Kubernetes releases

Hello @brandond, i've managed to connect my agent to my master with the port 6443.

```
root@tardis10:~#`  curl -vs 10.1.8.1:6443
* Rebuilt URL to: 10.1.8.1:6443/
*   Trying 10.1.8.1...
* TCP_NODELAY set
* Connected to 10.1.8.1 (10.1.8.1) port 6443 (#0)
> GET / HTTP/1.1
> Host: 10.1.8.1:6443
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
<
```

On this, tardis10 is my agent and 10.1.8.1 is my master node, i can connect them, but still get an error on k3s-agent:
```
 Sep 15 14:11:34 tardis10.icarotech.com k3s[124590]: time="2022-09-15T14:11:34.205960481-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\"

```

My 2 masters nodes are running normally, but im having this problem to add the workers.

**Comment by brandond** [comment]
>  Sep 15 14:11:34 tardis10.icarotech.com k3s[124590]: time="2022-09-15T14:11:34.205960481-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\"

This error is truncated. What is the full message?

You can join agents directly to either one of the servers, or to an external load-balancer, or simply use a DNS alias that points at both of the servers. I'm not sure I would go through the work of setting up a whole haproxy load-balancer just for this, as the connection is only used once when joining nodes to the cluster. After that, the nodes query the cluster for the server addresses and reconnect directly to them using a client-side load-balancer. For that reason, a DNS alias pointing at both of the servers is probably much less work and equally reliable.

**Comment by Anddiy** [comment]
> > Sep 15 14:11:34 tardis10.icarotech.com k3s[124590]: time="2022-09-15T14:11:34.205960481-03:00" level=error msg="failed to get CA certs: Get "[https://127.0.0.1:6444/cacerts\](https://127.0.0.1:6444/cacerts%5C)"
> 
> This error is truncated. What is the full message?
> 
> You can join agents directly to either one of the servers, or to an external load-balancer, or simply use a DNS alias that points at both of the servers. I'm not sure I would go through the work of setting up a whole haproxy load-balancer just for this, as the connection is only used once when joining nodes to the cluster. After that, the nodes query the cluster for the server addresses and reconnect directly to them using a client-side load-balancer. For that reason, a DNS alias pointing at both of the servers is probably much less work and equally reliable.

Sorry for that,  here's the full message:
```
Sep 15 15:16:40 tardis10.icarotech.com k3s[6951]: time="2022-09-15T15:16:40.136241730-03:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:55224->127.0.0.1:6444: read: connection reset by peer"

```

**Comment by Anddiy** [comment]
Hello @brandond,

Reopened this issue and updated the information about the problem, sorry about the other issue.

**Comment by brandond** [comment]
> Tried again with another port and its succeed:
> 
> `* error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

That's not success, that's just an SSL error instead of a `No route to host` error. It still seems like your nginx config is problematic. What is your goal in putting nginx in front of the K3s control-plane? This would only be used when the agent is initially joining the cluster; once it's connected it maintains direct connections to all the servers.

**Comment by Anddiy** [comment]
> > Tried again with another port and its succeed:
> > `* error:1408F10B:SSL routines:ssl3_get_record:wrong version number`
> 
> That's not success, that's just an SSL error instead of a `No route to host` error. It still seems like your nginx config is problematic. What is your goal in putting nginx in front of the K3s control-plane? This would only be used when the agent is initially joining the cluster; once it's connected it maintains direct connections to all the servers.


My goal with nginx is to use it as a Load Balancer, all the tutorials i saw and the documentation says i will need a fix ip or a load balancer to connect my 2 master node to the cluster, i've tried to build my cluster without the load balancer for an example, and with that i get an error when add the worker node saying it don't have a route to my second master node.

With or Without the load balancer, untill now i can add 2 masters, but get problems when add worker nodes.

**Comment by AdoPi** [comment]
Did you solve your issue? I have the exact same one

**Comment by vineethmn** [comment]
Same issue here, does anyone able to fix this? :(

**Comment by BruceDone** [comment]
> Same issue here, does anyone able to fix this? :(

may be your server didn't open the 6443 port , after i open it , the agent successfully join

**Comment by VardyNg** [comment]
> > Same issue here, does anyone able to fix this? :(
> 
> may be your server didn't open the 6443 port , after i open it , the agent successfully join

I solved the issue in the same way, for some reason the server 6443 port is not accessible, I changed to another master server and it worked
