### ISSUE TITLE
listen tcp :6443: bind: address already in use and the k3s-server process <defunct>

### ISSUE THREAD

**Issue by YchauWang** [k3s-io/k3s#6134]
**Environmental Info:**
K3s Version: 
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux allinone-02-62898 3.10.0-957.1.1.el7.x86_64 #1 SMP Wed Jul 28 14:46:37 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 servers, 1 agents

**Describe the bug:**
When I tried to from one server switch to the another server. k3s.service started failed. The system message as following:
```
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=info msg="Configuring mysql database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=info msg="Database tables and indexes are up to date"
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=info msg="Kine available at unix://kine.sock"
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=info msg="Reconciling bootstrap data between datastore and disk"
Sep 14 19:31:28 allinone-02-47762 k3s: time="2022-09-14T19:31:28+08:00" level=fatal msg="starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use"
Sep 14 19:31:28 allinone-02-47762 systemd: k3s.service: main process exited, code=exited, status=1/FAILURE
Sep 14 19:31:28 allinone-02-47762 systemd: Failed to start Lightweight Kubernetes.
Sep 14 19:31:28 allinone-02-47762 systemd: Unit k3s.service entered failed state.
Sep 14 19:31:28 allinone-02-47762 systemd: k3s.service failed.
Sep 14 19:31:30 allinone-02-47762 systemd: Stopped Lightweight Kubernetes.
```

**Steps To Reproduce:**
- Installed K3s: 
Sorry I can not reproduce it, but this issue reported some times.

**Expected behavior:**
Expected the k3s.service is working OK, Through the systemd service restarting strategy.

**Additional context / logs:**
```
Sep 14 15:21:34 allinone-02-47762 systemd: Stopping Lightweight Kubernetes...
Sep 14 15:21:34 allinone-02-47762 k3s: I0914 15:21:34.061405   23963 server.go:204] "Requested to terminate, exiting"
Sep 14 15:21:34 allinone-02-47762 k3s: I0914 15:21:34.061500   23963 requestheader_controller.go:183] Shutting down RequestHeaderAuthRequestController
Sep 14 15:24:34 allinone-02-47762 systemd: k3s.service still around after SIGKILL. Ignoring.
Sep 14 15:27:34 allinone-02-47762 systemd: k3s.service still around after final SIGKILL. Entering failed mode.
Sep 14 15:27:34 allinone-02-47762 systemd: Stopped Lightweight Kubernetes.
Sep 14 15:27:34 allinone-02-47762 systemd: Unit k3s.service entered failed state.
Sep 14 15:27:34 allinone-02-47762 systemd: k3s.service failed.
...
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Starting k3s v1.23.3+k3s1 (5fb370e5)"
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Configuring mysql database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Database tables and indexes are up to date"
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Kine available at unix://kine.sock"
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=info msg="Reconciling bootstrap data between datastore and disk"
Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=fatal msg="starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use"
Sep 14 15:27:34 allinone-02-47762 systemd: k3s.service: main process exited, code=exited, status=1/FAILURE
Sep 14 15:27:34 allinone-02-47762 systemd: Failed to start Lightweight Kubernetes.
Sep 14 15:27:34 allinone-02-47762 systemd: Unit k3s.service entered failed state.
Sep 14 15:27:34 allinone-02-47762 systemd: k3s.service failed.
Sep 14 15:27:34 allinone-02-47762 journal: [ ics root ERROR Execute command [ systemctl restart k3s ] failed with error ['Job for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details.']. ]
Sep 14 15:27:34 allinone-02-47762 journal: [ ics root ERROR restart k3s service failed. ]
```

ps -ef | grep 23963
root     23963     1  0 13:54 ?        00:02:13 [k3s-server] <defunct>
root     24076 23963  0 13:54 ?        00:00:08 [containerd] <defunct>

**Comment by brandond** [comment]
> When I tried to from one server switch to the another server. k3s.service started failed.

What do you mean by "switch to the another server"?

> `Sep 14 15:27:34 allinone-02-47762 k3s: time="2022-09-14T15:27:34+08:00" level=fatal msg="starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use"`
This indicates that another `k3s server` process is still running. Are you attempting to run multiple copies of k3s at the same time?

**Comment by YchauWang** [comment]
My cluster is 2 masters and 1 node, the storage endpoint is the mysql. I used one vip for the apiserver server LB. This issue was reported when the vip switch from the master2 to the master1.

**Comment by YchauWang** [comment]
> It looks like systemd is not actually waiting for k3s to finish shutting down before attempting to start it again, which I would expect to cause problems. How long does the k3s process take to finish terminating?

The systemd restart k3s.service timeout:
Sep 14 19:09:22 allinone-01-19534 systemd: k3s.service stop-sigterm timed out. Killing.
Sep 14 19:12:22 allinone-01-19534 systemd: k3s.service stop-final-sigterm timed out. Killing.
Sep 14 19:12:22 allinone-01-19534 systemd: k3s.service stop-final-sigterm timed out. Killing.

**Comment by brandond** [comment]
> I used one vip for the apiserver server LB. This issue was reported when the vip switch from the master2 to the master1.

What are you using to host a VIP in front of the apiserver? Using something that's Kubernetes-aware that tries to stop/start services when the VIP moves is unlikely to work well. Have you tried using kube-vip or metallb to expose the kubernetes.default service?

**Comment by YchauWang** [comment]
Not kube-vip or metallb. It is VIP of our server. do you mean that is the VIP switching lead to the <defunct> process? And how to check the k3s.service finish shutdown?

**Comment by brandond** [comment]
I'm still not sure I understand what you're doing. Are you saying that you use some external tool to move the VIP between nodes, and only start the k3s server service on the node that holds the VIP, and stop it when the VIP is moved?

**Comment by YchauWang** [comment]
> I'm still not sure I understand what you're doing. Are you saying that you use some external tool to move the VIP between nodes, and only start the k3s server service on the node that holds the VIP, and stop it when the VIP is moved?

yes, the k3s follow the VIP

**Comment by brandond** [comment]
That is not how Kubernetes HA is designed to work. You should leave both servers running and pointed at the datastore regardless of which node holds the VIP. Otherwise you're going to have issues with control-plane functionality being disrupted every time the VIP moves. K3s agents only use the server IP (or Virtual IP) once, when initially joining the cluster; once that is done they maintain a client load-balancer with persistent connections to the actual server node addresses. 

I would probably do away with the complicated VIP arrangement entirely, and just use a DNS alias that points at both of the active server nodes. That is more inline with how it is intended to be deployed.

**Comment by YchauWang** [comment]
Thank you very much! I found the root reason of this issue: Our server storage I/O error, the k3s service process was blocked by this error.
Our k3s service tried to restart but getting errors:
`systemd: k3s.service stop-sigterm timed out. Killing.` and `systemd: k3s.service still around after final SIGKILL. Entering failed mode.`

That lead to the issue, 6443 port using.
