### ISSUE TITLE
Typo URL in v1.25.0+k3s1 release notes

### ISSUE THREAD

**Issue by victorhooi** [k3s-io/k3s#6137]
There appears to be a small typo in the [v1.25.0+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.0%2Bk3s1) release notes.

One of the bullet points has this:

> See [the docs](https://k3s-io.github.io/docs/docs/reference/server-config#deprecated-options) for their replacement.

The text "the docs" points to:

https://k3s-io.github.io/docs/docs/reference/server-config#deprecated-options

but I think the correct link should be:

https://k3s-io.github.io/docs/reference/server-config#deprecated-options

**Comment by brandond** [comment]
Thanks for the note. The docs have been in a bit of a state of flux as we transition over to the new platform. I'll update the notes.

**Comment by cwayne18** [comment]
Yeah this was on me for updating the gh-pages repos, apologies
