### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by Meraj** [k3s-io/k3s#6139]
**Environmental Info:**
K3s Version: 

```
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1
```
Node(s) CPU architecture, OS, and Version: 

```
Linux srv200956 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```
Cluster Configuration:

* 1 server (single-node cluster)

**Describe the bug:**

I have deployed a simple Django project with k3s, the problem is the project can not send any outbound HTTP requests, project deployed without any problem ,and works fine but if it want to request for example google.com from the pod, it throw SSL handshake error, I tried execute curl on the pod:
```
$ curl https://www.google.com
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
$ curl --tlsv1.2 --tls-max 1.2 https://www.google.com
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```
I tried to curl an HTTP domain and got:
```
error code: 1001
```
ping websites works fine:
```
$ ping google.com
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
```
DNS config of the pod:
```
search mynamespace.svc.k3s.test.com svc.k3s.test.com k3s.test.com bitcommand.com
nameserver 10.43.0.10
options ndots:5
```
openssl version:
```
OpenSSL 1.1.1n  15 Mar 2022
```
**Steps To Reproduce:**

- Installed K3s: 
```
$curl -sfL https://get.k3s.io | sudo sh -s - server
  --token="test=="
  --datastore-endpoint="postgres://postgres:postgres@127.0.0.1:5432/postgres"
  --cluster-domain="k3s.test.com"
  --node-name="test"
```
**Expected behavior:**

send HTTP requests from the pod
**Actual behavior:**

SSL handshake failed when trying to curl a website which has HTTPS, and on the http domains, error 1001
**Additional context / logs:**

* I didn't find anything helpful yet

**Comment by brandond** [comment]
It sounds like you have something on your network that's blocking outbound HTTP/HTTPS connections. Are you using or do you need to use a proxy server to reach the internet?

**Comment by Meraj** [comment]
Yeah, after your comment, I reset the VPS and installed k3s again, but the error was still there.
I get another VPS from another VPS provider, and the error is gone;
I think there is some rule or something on their service which cause this error;
