### ISSUE TITLE
Allow not stripping binaries in order to attach a debugger (Delve)

### ISSUE THREAD

**Issue by moio** [k3s-io/k3s#6146]
**Is your feature request related to a problem? Please describe.**

As a developer, attaching a debugger helps me understanding the inner workings, especially as a novice to the codebase.

This is currently not possible because all binaries are stripped during the build process.

**Describe the solution you'd like**

A build flag that prevents stripping.

**Describe alternatives you've considered**

Printf logging is an alternative but adds considerable turnaround time, especially in an explorative phase when one does not know exactly what to look for upfront.

**Additional context**

[Delve](https://github.com/go-delve/delve) is the defacto debugger for Golang, and [requires unstripped binaries](https://github.com/go-delve/delve/issues/2899).

**Comment by ShylajaDevadiga** [comment]
Closing as it does not need testing.
