### ISSUE TITLE
Running K3S Binary does not complete,  Failed to find cgroups of kubelet.

### ISSUE THREAD

**Issue by MayanNetwork** [k3s-io/k3s#6153]
Environmental Info:
K3s Version: 

k3s version v1.25.0+k3s1 (26e94057)
go version go1.19

**Node(s) CPU architecture, OS, and Version:** 

Linux osboxes 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

(It is from Centos Stream 8.5)

**Cluster Configuration:**

Have not gotten far enough to have any K3 service/servers/agent.

**Describe the bug:**

Trying to run the downloaded **binary** located on Downloads Folder.  
 Note 1: that I do have **success with script**:

   curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.0+k3s1 |sh -s - --token=MyCToken --write-kubeconfig-mode 644 --node-name k3s-01

Had several issues even after following Rancher's basic instructions for Centos.

systemctl disable firewalld --now

yum update
yum install -y container-selinux selinux-policy-base
sudo yum install -y https://rpm.rancher.io/k3s/latest/common/centos/8/noarch/k3s-selinux-1.2-2.el8.noarch.rpm

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

 I would expect running the binary would succeed like the script succeeds.  Also I would expect running the binary would stop on first FATAL, or first error.

First attempt, is same results:
sudo ./k3s server --debug 

SecondAttemp
sudo ./k3s server --debug --write-kubeconfig-mode 644  --token=MyCluToken --selinux --node-name k3s-02

**Actual behavior:**

Error output below.

Note 2:  inconfig has a lot of new interfaces now
 
**Additional context / logs:**

Error Logs are attached, summarized here

ime="2022-09-17T12:41:06-04:00" level=info msg="Cluster-Http-Server 2022/09/17 12:41:06 http: TLS handshake error from 127.0.0.1:41260: remote error: tls: bad certificate"
...
...
I0917 12:41:06.948372   19991 shared_informer.go:255] Waiting for caches to sync for node_authorizer
time="2022-09-17T12:41:06-04:00" level=info msg="Cluster-Http-Server 2022/09/17 12:41:06 http: TLS handshake error from 127.0.0.1:41288: remote error: tls: bad certificate"
...

0917 12:41:06.967481   19991 genericapiserver.go:656] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
...
time="2022-09-17T13:18:24-04:00" level=warning msg="SELinux is enabled for k3s but process is not running in context 'container_runtime_t', k3s-selinux policy may need to be applied"

ime="2022-09-17T12:41:07-04:00" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd"
I0917 12:41:07.111073   19991 instance.go:574] API group "internal.apiserver.k8s.io" is not enabled, skipping.
time="2022-09-17T12:41:07-04:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"

[k3sStart_Ifconfig_AfterStart.txt](https://github.com/k3s-io/k3s/files/9592273/k3sStart_Ifconfig_AfterStart.txt)
[k3sStartLogDump.txt](https://github.com/k3s-io/k3s/files/9592274/k3sStartLogDump.txt)
[k3StartLogDump2_longerCommand.txt](https://github.com/k3s-io/k3s/files/9592275/k3StartLogDump2_longerCommand.txt)

**Comment by brandond** [comment]
The tls handshake errors are normal to see if you've enabled --debug.

It is unclear to me if you are using the install script, or are installing the RPMs and downloading the k3s binary manually. You show your commands to do both; which is it?

Don't run k3s with sudo. Start the systemd unit, or user su/sudo to get a root shell, and then run it from there. You should also ensure that you are downloading and running the k3s binary from the correct path. If it is not in the expected path, the selinux policies won't apply to it.

**Comment by MayanNetwork** [comment]
Thanks for the reply.  My problem is that running the binary does not start K3S.   I mentioned the script approach to only to show that all things being equal, the only difference is running the binary directly on VM2.  My VM2 is a clone of VM1 before doing anything.   So to repeat in other words, on VM1 I ran using the script with success (except I get a SELinux activity for a later investigation), so VM1 kubectl get nodes , returns as expected.

        VM1 script success shows environment is ok:
        [osboxes@osboxes Downloads]$ kubectl get nodes
	        NAME     STATUS   ROLES                  AGE   VERSION
	        k3s-01   Ready    control-plane,master   12h   v1.25.0+k3s1

**HEREON VM2 binary has a problem**:

**K3S Bin Downloaded FROM:**:
    wget https://github.com/k3s-io/k3s/releases/download/**v1.25.0**+k3s1/k3s

I switched to su root as you suggested, below capture two longs, one with --debug, and one without.

[root@osboxes osboxes]# systemctl status firewalld
 firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor >
   Active: inactive (dead)
     Docs: man:firewalld(1)

[root@osboxes osboxes]# k3s server --debug --write-kubeconfig-mode 644 --token=MyCluToken --selinux --node-name k3s-02 > try1.txt 2>&1

Wait about 4 minutes, and kubectl command not found.

**Log--debug attached, summarized here:**

time="2022-09-17T16:55:46-04:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
time="2022-09-17T16:55:46.255802154-04:00" level=info msg="starting containerd" revision= version=v1.6.8-k3s1
I0917 16:55:46.281255    7316 instance.go:574] API group "internal.apiserver.k8s.io" is not enabled, skipping.

time="2022-09-17T16:55:46.298189542-04:00" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exit status 1 \"modprobe: **FATAL: Module aufs** not found in directory /lib/modules/4.18.0-408.el8.x86_64\\n\"): skip plugin" type=io.containerd.snapshotter.v1
W0917 16:55:46.070099    7316 genericapiserver.go:656] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.

WITHOUT --debug:  summary here, plu log attached

time="2022-09-17T17:03:22-04:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"

E0917 17:03:23.004685    7947 controller.go:163] Error removing old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service

**STUCK for a couple of minutes at log line 550**, so I CTRL-C
I0917 17:03:37.762927    7947 garbagecollector.go:163] Garbage collector: all resource monitors have synced. Proceeding to collect garbage


[Try1_withDebug.txt](https://github.com/k3s-io/k3s/files/9592636/Try1_withDebug.txt)

[Try2_noDebug.txt](https://github.com/k3s-io/k3s/files/9592637/Try2_noDebug.txt)

**Comment by brandond** [comment]
Can I ask what specifically you're trying to accomplish? You're trying to run k3s from a user sesssion, with su/sudo, and selinux? Is there any particular reason you're not just starting it from the systemd unit or openrc script?

**Comment by MayanNetwork** [comment]
Well I am on a learning path.  The eventual goal is to run the binary on an airgap environment.  Thus one step at a time as done above.  The reply above is all based on at the root level, [root@osboxes osboxes],  per your suggestion, but failed.   
The OS currently is Centos Stream 8.
I need read up on how to start from systemd unit, or openrc, I am not familiar with that, the few minutes I spent looking at that seemed complicated,  I saw no mention of it on Rancher/K3S,  but I guess you are saying that is my two ways to run the binary,

**Comment by MayanNetwork** [comment]
Two different things, the first is what I followed to be stuck.   The second is a simple question  

1. First  I followed these instructions
          https://github.com/k3s-io/k3s
**Manual Download**  (scroll far down)

      Download k3s from latest [release](https://github.com/k3s-io/k3s/releases/latest), x86_64, armhf, arm64 and s390x are supported.
      
      Run the server.
      **sudo k3s server** &
      
      # Kubeconfig is written to /etc/rancher/k3s/k3s.yaml
      sudo k3s kubectl get nodes
      
      # On a different node run the below. NODE_TOKEN comes from
      # /var/lib/rancher/k3s/server/node-token on your server
      sudo k3s agent --server https://myserver:6443 --token ${NODE_TOKEN}

2. I think I eventuall have to do the Air-Gap approach, might as well jump to that, which tar do I download for Linux on Intel 64 bit?   
    **amd64.tar.gz, or -arm.tar.gz?**  of does it matter in the case of air-gap.

**Comment by MayanNetwork** [comment]
I switched to an airgap environment.  Created a local repo with the Linux  .iso (it is on a USB so I mounted the USB) (googled how to create a local repo).  yum install (yes install knows to go to my repo)  the selinux container per that local repo.   Then disabled firewalld and selinux (on boot up disabled).  
K3S runs.

I hope that helps others.
You may close this issue.
