### ISSUE TITLE
K3S installation error on machine: Failed to find the k3s-selinux policy 

### ISSUE THREAD

**Issue by Anddiy** [k3s-io/k3s#6158]
Hello,

Im trying to install k3s on my second master node but getting some troubles with k3s-selinux policy. 

**K3S Version:** 
``
v1.21.14+k3s1 ( I NEED TO USE THIS VERSION because my application only runs on kubernetes 1.21.x)
``
**OS**: 
``Linux tardis7.icarotech.com 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
``

**Cluster:**
``
2 Masters and 3 Workers.
``

**Steps to reproduce:** 

Installing k3s with this options: 
export INSTALL_K3S_VERSION="v1.21.14+k3s1" 
export K3S_KUBECONFIG_MODE="644"
export INSTALL_K3S_EXEC="--no-deploy traefik"
export INSTALL_K3S_SKIP_SELINUX_RPM=true
curl -sfL https://get.k3s.io | K3S_TOKEN="myk3stoken" sh -s - server --server https://10.1.8.1:6443

**Error:**

When i tried to install k3s server on my second master node, i get this error: 

```
root@tardis7:~#  curl -sfL https://get.k3s.io | K3S_TOKEN="mymastertoken" sh -s - server --server https://10.1.8.1:6443
[INFO]  Using v1.21.14+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.14+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[ERROR]  Failed to find the k3s-selinux policy, please install:
    dnf install -y container-selinux
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-0.4-1.el8.noarch.rpm

```

I've tried to follow the installation of the k3s-selinux, but i got this: 

```
root@tardis7:~#  dnf install -y container-selinux
Last metadata expiration check: 0:00:40 ago on Mon 19 Sep 2022 01:00:53 PM -03.
Package container-selinux-2:2.167.0-1.module_el8.5.0+911+f19012f9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
root@tardis7:~#  dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-0.4-1.el8.noarch.rpm
Last metadata expiration check: 0:00:47 ago on Mon 19 Sep 2022 01:00:53 PM -03.
k3s-selinux-0.4-1.el8.noarch.rpm                                                                                                                                                                              24 kB/s |  19 kB     00:00
Error:
 Problem: package k3s-selinux-0.4-1.el8.noarch requires container-selinux < 2:2.164.2, but none of the providers can be installed
  - conflicting requests
  - package container-selinux-2:2.124.0-1.gitf958d0c.module_el8.3.0+569+1bada2e4.noarch is filtered out by modular filtering
  - package container-selinux-2:2.130.0-1.module_el8.5.0+1004+c00a74f5.noarch is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```
Thats weird for me, my first master node worked succesfully on installation of this version and i already have a cluster running, just need to add this second master to it, the most strange thing is that on my master1 my container-selinux package has a higher version than my second master so its doesn't make any sense that k3s error i think

Can i get any help?

Thanks.

**Comment by brandond** [comment]
That is a very old release of the k3s-selinux package. Try one of the more recent releases: https://github.com/k3s-io/k3s-selinux/releases

**Comment by Anddiy** [comment]
Hello @brandond .

Tried with a new version and it worked. 

Thank you.
