### ISSUE TITLE
failed to delete stale service connections

### ISSUE THREAD

**Issue by lazywhite** [k3s-io/k3s#6169]
**Environmental Info:**
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

Linux node1.localdomain.com 5.10.66 #3 SMP Thu Sep 22 15:55:15 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:

1 master node

**Describe the bug:**

I'm trying to run k3s on firefly roc-rk3588 ( Raspberry Pi like arm64 board), maybe this error is caused by missing kernel config?
```
Sep 22 17:24:19 node1.localdomain.com k3s[34223]: E0922 17:24:19.019309   34223 proxier.go:1519] "Failed to delete stale service connections" err="error deleting connection tracking state for UDP service IP: 10.43.0.10, error: conntrack command returned: \"conntrack v1.4.6 (conntrack-tools): Can't open handler\\n\", error message: exit status 1" IP="10.43.0.10"

```

**Comment by brandond** [comment]
> `conntrack command returned: \"conntrack v1.4.6 (conntrack-tools): Can't open handler`

This error is coming from the `conntrack` binary, which I'm not super familiar with. The error does suggest that you're missing some conntrack kernel modules though.

**Comment by lazywhite** [comment]
solved, kernel should compile with  nf_conntrack and nf_conntrack_netlink module according to this [https://conntrack-tools.netfilter.org/manual.html](url)
