### ISSUE TITLE
is there a kube-apiserver.yaml equivalent and missing settings?

### ISSUE THREAD

**Issue by Osokarp** [k3s-io/k3s#617]
Hi,

As of v0.3.0, I know that you can pass flags like this: "k3s server --kube-apiserver-arg value", b but just wanted to check if specifying a file as input to the kubernetes api server settings is supported as I can't find it anywhere in the documentation, the use case is for removing unwanted settings, e.g --basic-auth-file, which is initialized when you start up the server which you can't do as the method above is purely additive.

On a side note, there are also some settings for the apiserver that are not configurable some examples include: anonymous-auth, insecure-allow-any-token, and other many settings which are all part of the CIS benchmark. Am I missing something or will this be supported by k3s any time soon?

**Comment by erikwilson** [comment]
Creating a config file to pass in arguments is a good idea, something we have been wanting to do, I can't find an existing issue so marking this as an enhancement.

The `anonymous-auth` flag has been removed from k3s:
https://github.com/rancher/k3s/commit/153ca56b6e6cb883d223327344b40673631a9a82

And the `insecure-allow-any-token` flag has been removed from k8s:
https://github.com/kubernetes/kubernetes/commit/b78fc209a49049312ae038ef0235141f6c6eb929

**Comment by brandond** [comment]
Closing due to age. Related to #2588
