### ISSUE TITLE
K3S make need docker,  FATA[0000] exec: "docker": executable file not found in $PATH 

### ISSUE THREAD

**Issue by MayanNetwork** [k3s-io/k3s#6174]
I downloaded 1.23.5's Source.gz and tried to run make and get the FATAL below

**FATA**[0000] exec: "docker": executable file not found in $PATH 

Temporary expermenting on **VM Centos Stream 8**, but my end goal is embedded **airgap** environment.

Thanks.

**Comment by brandond** [comment]
At the moment the k3s makefile makes significant use of docker and dapper (a docker wrapper). While we would like to move away from this long term, it is not something that we are planning to address immediately.
