### ISSUE TITLE
can you expand the docs for K3S_TOKEN security

### ISSUE THREAD

**Issue by abe-winter** [k3s-io/k3s#6175]
**Is your feature request related to a problem? Please describe.**
It's not clear from the k3s docs whether `K3S_TOKEN` (recommended [here](https://rancher.com/docs/k3s/latest/en/quick-start/#install-script)) is a two-way validation. I.e., is it *just* a way for the new agent to authenticate to the cluster? Or does it *also* allow the new agent to validate that the server is who it appears to be?

**Describe the solution you'd like**

Can you please add a line in the [docs](https://rancher.com/docs/k3s/latest/en/quick-start/#install-script) saying if:
- K3S_TOKEN allows the client to validate the server
- whether this is safe to use on untrusted connections, or should only be used on a private network

**Describe alternatives you've considered**
(digging through code and old issues)

**Additional context**
- from [clientaccess/token.go](https://github.com/k3s-io/k3s/blob/bcb662926d005dd65275bc462d4664ff5994ce07/pkg/clientaccess/token.go#L59), it looks like the client validates the server's CA bundle, but I don't know exactly what that means in terms of trusted connections
- rke's [certs docs](https://rancher.com/docs/rke/latest/en/cert-mgmt/), possibly relevant?
- [jvns blog](https://jvns.ca/blog/2017/08/05/how-kubernetes-certificates-work/) on kube CAs is a good overview, but also makes it sound like there are many approaches here
- [cert rotation docs in k3s wiki](https://github.com/k3s-io/k3s/wiki/K3s-Cert-Rotation)
- seems like token-auth-file is recommended against in the [k3s security self-assessment](https://rancher.com/docs/k3s/latest/en/security/self_assessment/#1-2-3-ensure-that-the-token-auth-file-parameter-is-not-set-automated)? (not sure if that's the same as passing K3S_TOKEN). I think that's the same as this [CIS rule](https://docs.datadoghq.com/security_platform/default_rules/cis-kubernetes-1.5.1-1.2.3)
- discussion of token lifetime here https://github.com/k3s-io/k3s/issues/2645

**Comment by brandond** [comment]
This is a reasonable ask, but the short answer is that the token can be in one of two formats:
1. Just the bare token: simply the server or agent token required to join the cluster. This is in fact used as an auth-basic password when initially bootstrapping the agent. This is the format that should be used when creating a new cluster with the --token speficied.
2. K10 format: A packed format that includes the fixed string `K10`, the hash of the cluster CA, a username, and password. When this format is used, the cluster's CA certificate hash is validated against the hash included in the token. This is the format that should be used when joining additional servers or agents to the cluster, and can be retrieved from the node-token file on a server.

**Comment by abe-winter** [comment]
Thank you!

When connecting with K10 format, is the sequence:
1. new node connects to cluster via TLS, using the server cert
2. the new node uses the K10 hash to validate the current TLS connection
3. new node logs in user user/password from K10

(I.e. does validation happen before the user/password are transmitted)

**Comment by brandond** [comment]
Everything uses TLS.

1. Node connects to the server and retrieves the cluster CA certificate.
2. Node verifies that the CA certificate hash matches the hash in the token
3. Node verifies that the certificate used by the TLS connection to the server was issued by the cluster CA certificate
4. Node sends credentials to download bootstrap configuration

Step 2 is omitted if the hash is not included in the token; any cluster CA sent by the remote node is accepted.

**Comment by abe-winter** [comment]
Thanks, that makes total sense

**Comment by hauks96** [comment]
> This is a reasonable ask, but the short answer is that the token can be in one of two formats:
> 
> 1. Just the bare token: simply the server or agent password required to join the cluster. This is the format that should be used when creating a new cluster with the --token or --agent-token flag.

Does this mean that when I install the first server with the `--token` flag, I can just use the same `--token` flag on all nodes to join the cluster and don't need to retrieve a node token from the first installation?

**Comment by brandond** [comment]
Yes, you can absolutely use that short token format on all your nodes. You'll be missing the CA validation that comes from including the K10 prefix, but that cannot be known ahead of time as the CA certs are generated during initial server startup.
