### ISSUE TITLE
Not ready nodes after instance creation 

### ISSUE THREAD

**Issue by ksv510** [k3s-io/k3s#6179]
**Environmental Info:**
K3s Version: 

```
ubuntu@ip-10-0-0-40:~$ k3s -v
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1
```

Node(s) CPU architecture, OS, and Version: 

```
ubuntu@ip-10-0-0-40:~$ uname -a
Linux ip-10-0-0-40 5.15.0-1019-aws #23~20.04.1-Ubuntu SMP Thu Aug 18 03:20:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
single node

**Describe the bug:**

I have create AWS AMI to be able to create production-ready instances. But when I start the EC2 instance from the AMI I see that node list contains `NotReady` nodes. Is there any way to provide the node name on start, or some thing like that?

**Steps To Reproduce:**
1. Create EC2 instance, install K3S
```
curl -sfL https://get.k3s.io | sh - \
     && mkdir ~/.kube \
     && echo "export KUBECONFIG=~/.kube/config" >> ~/.bashrc \
     && source ~/.bashrc \
     && sudo k3s kubectl config view --raw > "$KUBECONFIG"
```
2. Add any workload, hashicorp consul for example
3. Make sure that everything works
4. Stop the instance
5. Create EC2 AMI `testAmi`
6. Create new EC2 instance from `testAmi`

**Expected behavior:**
```
ubuntu@ip-10-0-0-40:~$ kubectl get pods
NAME                   READY   STATUS        RESTARTS        AGE
bl-consul-0            1/1        Running               0               2d20h
```

**Actual behavior:**

```
ubuntu@ip-10-0-0-40:~$ kubectl get nodes
NAME            STATUS     ROLES                  AGE     VERSION
ip-10-0-0-32    NotReady   control-plane,master   2d20h   v1.24.4+k3s1
ip-10-0-0-40    Ready      control-plane,master   7m9s    v1.24.4+k3s1
```
As a result 
```
ubuntu@ip-10-0-0-40:~$ kubectl get pods
NAME                   READY   STATUS        RESTARTS        AGE
bl-consul-0            1/1     Terminating   0               2d20h
```
And the pod never starts

Whenever I remove the orphaned node, everything works fine

**Comment by brandond** [comment]
You should not create AMIs containing a pre-started K3s cluster. If you do so, all clusters created from that AMI will contain the same cluster Certificate Authority data, meaning that any kubeconfig or token that grants access to one cluster will also be considered valid for all the others. This is in addition to the issue you have found with regards to the "old" node still being present in the cluster.

The correct way to do what you want would be to install K3s but not start it, and populate the /var/lib/rancher/k3s/server/manifests directory with manifests that will automatically deploy your desired applications when the server starts.

**Comment by ksv510** [comment]
Hello @brandond 

thank you very much for your answer. I will consider the approach you have suggested.

But is there any way to renew Certificate Authority data in k3s?
