### ISSUE TITLE
nftables failed on Hyperbola

### ISSUE THREAD

**Issue by arankaren** [k3s-io/k3s#6184]
**Environmental Info:**
K3s Version: v1.25.0+k3s1

[Hyperbola](https://www.hyperbola.info/) OS Version: v0.4.1

Node(s) CPU architecture, OS, and Version: 

<code>Linux hyperbola 5.10.106-gnu1-1-lts #1 SMP Sat Jul 2 17:25:01 UTC 2022 x86_64 GNU/Linux</code>

Cluster Configuration:

**Describe the bug:**

Nftables support does not work without iptables-legacy.

Please add fully-support nftables

**Steps To Reproduce:**

- Installed K3s: 
<code>curl -sfL https://get.k3s.io | sh -s - --no-deploy traefik --write-kubeconfig-mode 644 --node-name k3s-master-01</code>

- Running K3s:
<code>/usr/local/bin/k3s server --no-deploy traefik --write-kubeconfig-mode 644 --node-name k3s-master-01</code>

**Expected behavior:**

<pre>
rc-service k3s status
* status: started
</pre>

**Actual behavior:**

<pre>
rc-service k3s status
* status: failed
</pre>

**Additional context / logs:**

log:
<pre>
E0928 23:55:49.198804    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: iptables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:49.198841    4424 proxier.go:858] "Sync failed" retryingTime="30s"
E0928 23:55:49.201527    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: ip6tables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `ip6tables -h' or 'ip6tables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
</pre>

<details>
  <summary>Full log k3s</summary>
<pre>
...
I0928 23:55:44.954919    4424 shared_informer.go:262] Caches are synced for node config
I0928 23:55:44.954975    4424 shared_informer.go:262] Caches are synced for service config
I0928 23:55:44.955021    4424 shared_informer.go:262] Caches are synced for endpoint slice config
E0928 23:55:44.958687    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: iptables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:44.958697    4424 proxier.go:858] "Sync failed" retryingTime="30s"
E0928 23:55:44.961265    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: ip6tables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `ip6tables -h' or 'ip6tables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:44.961276    4424 proxier.go:858] "Sync failed" retryingTime="30s"
I0928 23:55:44.968449    4424 controllermanager.go:593] Started "daemonset"
I0928 23:55:44.968549    4424 daemon_controller.go:284] Starting daemon sets controller
I0928 23:55:44.968581    4424 shared_informer.go:255] Waiting for caches to sync for daemon sets
I0928 23:55:45.118866    4424 controllermanager.go:593] Started "statefulset"
W0928 23:55:45.118927    4424 controllermanager.go:558] "service" is disabled
I0928 23:55:45.118996    4424 stateful_set.go:147] Starting stateful set controller
I0928 23:55:45.119033    4424 shared_informer.go:255] Waiting for caches to sync for stateful set
I0928 23:55:45.269175    4424 controllermanager.go:593] Started "ephemeral-volume"
I0928 23:55:45.269267    4424 controller.go:170] Starting ephemeral volume controller
I0928 23:55:45.269297    4424 shared_informer.go:255] Waiting for caches to sync for ephemeral
I0928 23:55:45.376747    4424 controller.go:611] quota admission added evaluator for: addons.k3s.cattle.io
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"ccm", UID:"ce149125-e3a7-4568-8b60-accc0b07b3eb", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"255", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/ccm.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"ccm", UID:"ce149125-e3a7-4568-8b60-accc0b07b3eb", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"255", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/ccm.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"coredns", UID:"a62ca600-b716-4ca4-bda7-bef6e1b970c9", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"263", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/coredns.yaml" 
I0928 23:55:45.424716    4424 controller.go:611] quota admission added evaluator for: deployments.apps
I0928 23:55:45.431678    4424 alloc.go:327] "allocated clusterIPs" service="kube-system/kube-dns" clusterIPs=map[IPv4:10.43.0.10]
E0928 23:55:45.436625    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: iptables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:45.436636    4424 proxier.go:858] "Sync failed" retryingTime="30s"
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"coredns", UID:"a62ca600-b716-4ca4-bda7-bef6e1b970c9", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"263", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/coredns.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"local-storage", UID:"718d68da-92f0-4c99-9110-a926e4ba6599", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"275", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/local-storage.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"local-storage", UID:"718d68da-92f0-4c99-9110-a926e4ba6599", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"275", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/local-storage.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"aggregated-metrics-reader", UID:"00978fdd-654e-47c3-aac3-41189997511b", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"285", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/aggregated-metrics-reader.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"aggregated-metrics-reader", UID:"00978fdd-654e-47c3-aac3-41189997511b", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"285", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/aggregated-metrics-reader.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"auth-delegator", UID:"52e266bc-d133-4192-9955-b1c73a8f85b0", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"290", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/auth-delegator.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"auth-delegator", UID:"52e266bc-d133-4192-9955-b1c73a8f85b0", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"290", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/auth-delegator.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"auth-reader", UID:"0e400664-8f92-4e40-88f6-5ccdd6d84428", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"295", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/auth-reader.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"auth-reader", UID:"0e400664-8f92-4e40-88f6-5ccdd6d84428", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"295", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/auth-reader.yaml" 
I0928 23:55:45.568426    4424 controllermanager.go:593] Started "horizontalpodautoscaling"
I0928 23:55:45.568500    4424 horizontal.go:168] Starting HPA controller
I0928 23:55:45.568530    4424 shared_informer.go:255] Waiting for caches to sync for HPA
I0928 23:55:45.618339    4424 controllermanager.go:593] Started "csrapproving"
I0928 23:55:45.618408    4424 certificate_controller.go:119] Starting certificate controller "csrapproving"
I0928 23:55:45.618437    4424 shared_informer.go:255] Waiting for caches to sync for certificate-csrapproving
I0928 23:55:45.769095    4424 controllermanager.go:593] Started "ttl"
I0928 23:55:45.769199    4424 ttl_controller.go:121] Starting TTL controller
I0928 23:55:45.769230    4424 shared_informer.go:255] Waiting for caches to sync for TTL
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-apiservice", UID:"143a93de-9684-4a66-8a1a-6b531f911c7b", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"301", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-apiservice.yaml" 
INFO[0008] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-apiservice", UID:"143a93de-9684-4a66-8a1a-6b531f911c7b", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"301", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-apiservice.yaml" 
W0928 23:55:45.902852    4424 reflector.go:324] k8s.io/client-go@v1.24.4-k3s1/tools/cache/reflector.go:167: failed to list *v1.Endpoints: endpoints "kubernetes" is forbidden: User "system:k3s-controller" cannot list resource "endpoints" in API group "" in the namespace "default"
E0928 23:55:45.902917    4424 reflector.go:138] k8s.io/client-go@v1.24.4-k3s1/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints "kubernetes" is forbidden: User "system:k3s-controller" cannot list resource "endpoints" in API group "" in the namespace "default"
I0928 23:55:45.918551    4424 controllermanager.go:593] Started "root-ca-cert-publisher"
I0928 23:55:45.918617    4424 publisher.go:107] Starting root CA certificate configmap publisher
I0928 23:55:45.918645    4424 shared_informer.go:255] Waiting for caches to sync for crt configmap
I0928 23:55:46.068898    4424 controllermanager.go:593] Started "pvc-protection"
I0928 23:55:46.068973    4424 pvc_protection_controller.go:103] "Starting PVC protection controller"
I0928 23:55:46.069003    4424 shared_informer.go:255] Waiting for caches to sync for PVC protection
INFO[0009] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-server-deployment", UID:"331399b4-3bd4-4ebc-a159-f2cbc54511b0", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"309", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-deployment.yaml" 
INFO[0009] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-server-deployment", UID:"331399b4-3bd4-4ebc-a159-f2cbc54511b0", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"309", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-deployment.yaml" 
I0928 23:55:46.566497    4424 serving.go:355] Generated self-signed cert in-memory
E0928 23:55:46.759030    4424 namespaced_resources_deleter.go:161] unable to get all supported resources from server: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0928 23:55:46.759154    4424 controllermanager.go:593] Started "namespace"
I0928 23:55:46.778340    4424 namespace_controller.go:200] Starting namespace controller
I0928 23:55:46.778378    4424 shared_informer.go:255] Waiting for caches to sync for namespace
W0928 23:55:46.818742    4424 handler_proxy.go:102] no RequestInfo found in the context
E0928 23:55:46.818802    4424 controller.go:116] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0928 23:55:46.818843    4424 controller.go:129] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
W0928 23:55:46.818898    4424 handler_proxy.go:102] no RequestInfo found in the context
E0928 23:55:46.818939    4424 controller.go:113] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: Error, could not get list of group versions for APIService
I0928 23:55:46.839093    4424 controller.go:126] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
INFO[0009] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-server-service", UID:"a3539cfe-36c8-464b-a555-93c3dea21183", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"316", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-service.yaml" 
I0928 23:55:46.965488    4424 node_ipam_controller.go:91] Sending events to api server.
I0928 23:55:47.031793    4424 alloc.go:327] "allocated clusterIPs" service="kube-system/metrics-server" clusterIPs=map[IPv4:10.43.124.231]
I0928 23:55:47.034931    4424 controllermanager.go:143] Version: v1.24.4+k3s1
E0928 23:55:47.039505    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: iptables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:47.039519    4424 proxier.go:858] "Sync failed" retryingTime="30s"
INFO[0010] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"metrics-server-service", UID:"a3539cfe-36c8-464b-a555-93c3dea21183", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"316", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-service.yaml" 
I0928 23:55:47.061299    4424 secure_serving.go:210] Serving securely on 127.0.0.1:10258
I0928 23:55:47.061681    4424 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0928 23:55:47.061725    4424 shared_informer.go:255] Waiting for caches to sync for RequestHeaderAuthRequestController
I0928 23:55:47.061780    4424 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0928 23:55:47.062030    4424 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0928 23:55:47.062069    4424 shared_informer.go:255] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0928 23:55:47.062121    4424 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0928 23:55:47.062152    4424 shared_informer.go:255] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
INFO[0010] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"resource-reader", UID:"bc546812-edac-4985-9eb0-8ba9db68a843", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"323", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/resource-reader.yaml" 
INFO[0010] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"resource-reader", UID:"bc546812-edac-4985-9eb0-8ba9db68a843", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"323", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/resource-reader.yaml" 
I0928 23:55:47.162475    4424 shared_informer.go:262] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0928 23:55:47.162531    4424 shared_informer.go:262] Caches are synced for RequestHeaderAuthRequestController
I0928 23:55:47.162611    4424 shared_informer.go:262] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
INFO[0010] Updated coredns node hosts entry [93.95.230.133 k3s-master-01] 
INFO[0010] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"rolebindings", UID:"2fe61457-78cb-4d8d-a3a4-fb39e5564ce9", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"330", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/rolebindings.yaml" 
INFO[0010] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"rolebindings", UID:"2fe61457-78cb-4d8d-a3a4-fb39e5564ce9", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"330", FieldPath:""}): type: 'Normal' reason: 'AppliedManifest' Applied manifest at "/var/lib/rancher/k3s/server/manifests/rolebindings.yaml" 
W0928 23:55:48.062545    4424 handler_proxy.go:102] no RequestInfo found in the context
E0928 23:55:48.062621    4424 controller.go:116] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0928 23:55:48.062662    4424 controller.go:129] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
W0928 23:55:48.062707    4424 handler_proxy.go:102] no RequestInfo found in the context
E0928 23:55:48.062740    4424 controller.go:113] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: Error, could not get list of group versions for APIService
I0928 23:55:48.063829    4424 controller.go:126] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
I0928 23:55:48.475271    4424 request.go:601] Waited for 1.04916275s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6444/apis/storage.k8s.io/v1beta1
E0928 23:55:49.075890    4424 controllermanager.go:463] unable to get all supported resources from server: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0928 23:55:49.076134    4424 node_controller.go:118] Sending events to api server.
I0928 23:55:49.076221    4424 controllermanager.go:291] Started "cloud-node"
I0928 23:55:49.076354    4424 node_lifecycle_controller.go:77] Sending events to api server
I0928 23:55:49.076400    4424 controllermanager.go:291] Started "cloud-node-lifecycle"
I0928 23:55:49.076713    4424 node_controller.go:157] Waiting for informer caches to sync
I0928 23:55:49.176877    4424 node_controller.go:406] Initializing node k3s-master-01 with cloud provider
I0928 23:55:49.184027    4424 node_controller.go:470] Successfully initialized node k3s-master-01 with cloud provider
I0928 23:55:49.198734    4424 event.go:294] "Event occurred" object="k3s-master-01" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
E0928 23:55:49.198804    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: iptables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `iptables -h' or 'iptables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:49.198841    4424 proxier.go:858] "Sync failed" retryingTime="30s"
E0928 23:55:49.201527    4424 proxier.go:874] "Failed to ensure chain jumps" err=<
	error checking rule: exit status 2: ip6tables v1.8.6 (nf_tables): Couldn't find match `conntrack'
	
	Try `ip6tables -h' or 'ip6tables --help' for more information.
 > table=filter srcChain=INPUT dstChain=KUBE-EXTERNAL-SERVICES
I0928 23:55:49.201537    4424 proxier.go:858] "Sync failed" retryingTime="30s"
</pre>
</details>

**Comment by brandond** [comment]
I see you also necro'd an old issue to post the same content. I'll link to my response:
https://github.com/k3s-io/k3s/issues/1812#issuecomment-1261202906

**Comment by arankaren** [comment]
> @brandond 
>  Your kernel appears to be missing the nf_conntrack module. See https://conntrack-tools.netfilter.org/manual.html#requirements

CONFIG_NF_CONNTRACK is enable in linux kernel: See https://git.hyperbola.info:50100/packages/core.git/tree/linux-libre-lts/config.x86_64#n1223

**Comment by brandond** [comment]
OK, is the module loaded then? The copy of ip6tables installed on your host (which reports to be from nf_tables v1.8.6) says that it can't find the match, which usually indicates that the module is missing or not loaded.

**Comment by brandond** [comment]
For nftables, it looks like you actually need the nft_ct module: https://www.kernelconfig.io/config_nft_ct

**Comment by arankaren** [comment]
> OK, is the module loaded then? The copy of ip6tables installed on your host (which reports to be from nf_tables v1.8.6) says that it can't match on conntrack entries, which usually indicates that a module is missing or not loaded. This isn't something K3s can fix or needs to support - you're missing something from your host OS.

I see. I'm contacting the Hyperbola devs to check what's going on.

> For nftables, it looks like you actually need the nft_ct module to match on conntrack state: https://www.kernelconfig.io/config_nft_ct

I very stange nft_ct is enable: https://git.hyperbola.info:50100/packages/core.git/tree/linux-libre-lts/config.x86_64#n1267

I'll keep researching and I'll write here

**Comment by brandond** [comment]
Did you end up figuring out how to resolve this?
