### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by bbhxwl** [k3s-io/k3s#6194]
Installation error.

curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -

![image](https://user-images.githubusercontent.com/26525599/193174561-3a48521b-47b7-4546-be60-7bbaebf35680.png)

**Comment by brandond** [comment]
You have trimmed out pretty much any useful information from your screenshot. Can you attach the actual logs (`journalctl -u k3s --no-pager`) instead?

**Comment by bbhxwl** [comment]
> 

INFO[1790] Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/193185815-d1ab7488-f17c-4c94-a58a-f9d514278c2c.png)

**Comment by bbhxwl** [comment]
> You have trimmed out pretty much any useful information from your screenshot. Can you attach the actual logs (`journalctl -u k3s --no-pager`) instead?

Although there has been an error, my server can see the client, but the client has always told me that the connection is not correct.

**Comment by bbhxwl** [comment]
> 

![image](https://user-images.githubusercontent.com/26525599/193186500-3880ac86-b767-43a9-8e8e-7dab954a9774.png)
![image](https://user-images.githubusercontent.com/26525599/193186545-7471d4cb-b99b-4ff1-969c-8aed33279437.png)

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/193187222-e1600b0e-2ab4-43e4-bb22-a2a20829a3a4.png)

**Comment by brandond** [comment]
The screenshots are still not enough to work from. Please attach the complete logs from the k3s (server) and k3s-agent (agent) journals on both nodes.

**Comment by bbhxwl** [comment]
> 

How should I read the log?


![image](https://user-images.githubusercontent.com/26525599/193201482-d719e7de-4457-4a0e-acfa-92f36e5b95a9.png)

**Comment by brandond** [comment]
On the agent node, check the k3s-agent log. On servers it is just k3s.

**Comment by bbhxwl** [comment]
> On the agent node, check the k3s-agent log. On servers it is just k3s.

ttps://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:50:10 guangdong2 k3s[16534]: time="2022-09-30T05:50:10Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:50:20 guangdong2 k3s[16534]: time="2022-09-30T05:50:20Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:50:30 guangdong2 k3s[16534]: time="2022-09-30T05:50:30Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:50:40 guangdong2 k3s[16534]: time="2022-09-30T05:50:40Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:51:00 guangdong2 k3s[16534]: time="2022-09-30T05:51:00Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:51:20 guangdong2 k3s[16534]: time="2022-09-30T05:51:20Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:51:40 guangdong2 k3s[16534]: time="2022-09-30T05:51:40Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:52:01 guangdong2 k3s[16534]: time="2022-09-30T05:52:01Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:52:21 guangdong2 k3s[16534]: time="2022-09-30T05:52:21Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:52:31 guangdong2 k3s[16534]: time="2022-09-30T05:52:31Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:52:51 guangdong2 k3s[16534]: time="2022-09-30T05:52:51Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:53:11 guangdong2 k3s[16534]: time="2022-09-30T05:53:11Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:53:31 guangdong2 k3s[16534]: time="2022-09-30T05:53:31Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:53:51 guangdong2 k3s[16534]: time="2022-09-30T05:53:51Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:54:01 guangdong2 k3s[16534]: time="2022-09-30T05:54:01Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:54:21 guangdong2 k3s[16534]: time="2022-09-30T05:54:21Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:54:41 guangdong2 k3s[16534]: time="2022-09-30T05:54:41Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:55:02 guangdong2 k3s[16534]: time="2022-09-30T05:55:02Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:55:22 guangdong2 k3s[16534]: time="2022-09-30T05:55:22Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:55:32 guangdong2 k3s[16534]: time="2022-09-30T05:55:32Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:55:52 guangdong2 k3s[16534]: time="2022-09-30T05:55:52Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:56:02 guangdong2 k3s[16534]: time="2022-09-30T05:56:02Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:56:22 guangdong2 k3s[16534]: time="2022-09-30T05:56:22Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:56:42 guangdong2 k3s[16534]: time="2022-09-30T05:56:42Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:57:02 guangdong2 k3s[16534]: time="2022-09-30T05:57:02Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:57:23 guangdong2 k3s[16534]: time="2022-09-30T05:57:23Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/server-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:57:43 guangdong2 k3s[16534]: time="2022-09-30T05:57:43Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:58:03 guangdong2 k3s[16534]: time="2022-09-30T05:58:03Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:58:13 guangdong2 k3s[16534]: time="2022-09-30T05:58:13Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:58:23 guangdong2 k3s[16534]: time="2022-09-30T05:58:23Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:58:34 guangdong2 k3s[16534]: time="2022-09-30T05:58:34Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:58:54 guangdong2 k3s[16534]: time="2022-09-30T05:58:54Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/server-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:59:14 guangdong2 k3s[16534]: time="2022-09-30T05:59:14Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:59:24 guangdong2 k3s[16534]: time="2022-09-30T05:59:24Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:59:34 guangdong2 k3s[16534]: time="2022-09-30T05:59:34Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 05:59:55 guangdong2 k3s[16534]: time="2022-09-30T05:59:55Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:00:15 guangdong2 k3s[16534]: time="2022-09-30T06:00:15Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:00:35 guangdong2 k3s[16534]: time="2022-09-30T06:00:35Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:00:45 guangdong2 k3s[16534]: time="2022-09-30T06:00:45Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:01:05 guangdong2 k3s[16534]: time="2022-09-30T06:01:05Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:01:15 guangdong2 k3s[16534]: time="2022-09-30T06:01:15Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:01:25 guangdong2 k3s[16534]: time="2022-09-30T06:01:25Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:01:35 guangdong2 k3s[16534]: time="2022-09-30T06:01:35Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:01:56 guangdong2 k3s[16534]: time="2022-09-30T06:01:56Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:02:06 guangdong2 k3s[16534]: time="2022-09-30T06:02:06Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:02:26 guangdong2 k3s[16534]: time="2022-09-30T06:02:26Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:02:46 guangdong2 k3s[16534]: time="2022-09-30T06:02:46Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:02:56 guangdong2 k3s[16534]: time="2022-09-30T06:02:56Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:03:17 guangdong2 k3s[16534]: time="2022-09-30T06:03:17Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:03:27 guangdong2 k3s[16534]: time="2022-09-30T06:03:27Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:03:37 guangdong2 k3s[16534]: time="2022-09-30T06:03:37Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:03:57 guangdong2 k3s[16534]: time="2022-09-30T06:03:57Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:04:17 guangdong2 k3s[16534]: time="2022-09-30T06:04:17Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:04:37 guangdong2 k3s[16534]: time="2022-09-30T06:04:37Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:04:57 guangdong2 k3s[16534]: time="2022-09-30T06:04:57Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:05:18 guangdong2 k3s[16534]: time="2022-09-30T06:05:18Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:05:38 guangdong2 k3s[16534]: time="2022-09-30T06:05:38Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:05:48 guangdong2 k3s[16534]: time="2022-09-30T06:05:48Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:05:58 guangdong2 k3s[16534]: time="2022-09-30T06:05:58Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:06:18 guangdong2 k3s[16534]: time="2022-09-30T06:06:18Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:06:38 guangdong2 k3s[16534]: time="2022-09-30T06:06:38Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:06:59 guangdong2 k3s[16534]: time="2022-09-30T06:06:59Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:07:19 guangdong2 k3s[16534]: time="2022-09-30T06:07:19Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Get \"https://127.0.0.1:6444/v1-k3s/client-ca.crt\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:07:29 guangdong2 k3s[16534]: time="2022-09-30T06:07:29Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:07:39 guangdong2 k3s[16534]: time="2022-09-30T06:07:39Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:07:49 guangdong2 k3s[16534]: time="2022-09-30T06:07:49Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:08:09 guangdong2 k3s[16534]: time="2022-09-30T06:08:09Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:08:30 guangdong2 k3s[16534]: time="2022-09-30T06:08:30Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Sep 30 06:08:50 guangdong2 k3s[16534]: time="2022-09-30T06:08:50Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by brandond** [comment]
That doesn't appear to be the full log, it's just the same errors repeating over and over. Can you restart the k3s-agent service, then **attach** (not paste) the full logs? You can get the full log from `journalctl -u k3s-server --no-pager > k3s-agent.log`. Again, attach the file, do not paste it into a comment. Do the same for the k3s log on the server, along with the output of `kubectl get node -o yaml` from the server.

**Comment by bbhxwl** [comment]
> That doesn't appear to be the full log, it's just the same errors repeating over and over. Can you restart the k3s-agent service, then **attach** (not paste) the full logs? You can get the full log from `journalctl -u k3s-server --no-pager > k3s-agent.log`. Again, attach the file, do not paste it into a comment. Do the same for the k3s log on the server, along with the output of `kubectl get node -o yaml` from the server.

How should I restart?

**Comment by brandond** [comment]
same as you would any other service on a node that uses systemd? `systemctl restart k3s-agent`

**Comment by brandond** [comment]
If someone could actually attach logs, that would be great. Even better if the failing agent was started with --debug.

**Comment by bbhxwl** [comment]
> If someone could actually attach logs, that would be great. Even better if the failing agent was started with --debug.

It's too difficult to give up learning k8s and k3s temporarily.

**Comment by shymega** [comment]
This is a persistent error I'm getting in 2023, on two Pi 4s and one x86_64 node. It's connected to a primary node hosted by Hetzner. I will create a new issue, and post logs correctly. Will reference this issue when done.
