### ISSUE TITLE
Installation of k3s behing an HTTP Proxy

### ISSUE THREAD

**Issue by mlschuler** [k3s-io/k3s#6195]
In the documentation I miss a note, how to install k3s behing an HTTP Proxy, e.g. in  a corporate network.

Here are the steps on a fresh SUSE SLES 15 SP4 system:

```console
# zypper -n in apparmor-parser iptables
# export HTTP_PROXY=http://<host>:<port>/
# export HTTPS_PROXY=http://<host>:<port>/
# export NO_PROXY=localhost,.svc,.cluster.local,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
# curl -sfL https://get.k3s.io/ | sh
```

Of course, you may extend NO_PROXY depending on your needs in your datacenter.

Please enhance the documentation.

**Comment by brandond** [comment]
These instructions aren't unique to K3s. If you're using `curl` behind a proxy you should already have those variables set in your shell, and the NO_PROXY variables for the cluster domain and CIDRs are automatically added by k3s - you don't need to populate them manually.

**Comment by mlschuler** [comment]
Thank you for pointing out the magic with NO_PROXY, but an issue remains, since in SUSE you usually setup the proxy in /etc/sysconfig/proxy. Then you have the environment veriables in small letters and no_proxy in /etc/sysconfig/proxy does not support subnets, in contrast to NO_PROXY in Go, which does.

**Comment by mlschuler** [comment]
You are right. It also works with the usual proxy configuration in /etc/sysconfig/proxy.

Will you add a note about that NO_PROXY autocompletion into the documentation. This is really interesting.

Thank you.

**Comment by mlschuler** [comment]
The comments should clarify that question
