### ISSUE TITLE
always keeping activating (start) status when install

### ISSUE THREAD

**Issue by zhaoyshine** [k3s-io/k3s#6208]
**Environmental Info:**
K3s Version: v1.24.6+k3s1 (a8e0c66d)

Node(s) CPU architecture, OS, and Version: Linux iZ8vb2p0lglgax8bc1dsxxZ 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 server

**Describe the bug:**

always keeping activating (start) status when install
```
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - --docker
```

got:
```
[INFO]  Finding release for channel stable
[INFO]  Using v1.24.6+k3s1 as release
[INFO]  Downloading hash rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/v1.24.6-k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/v1.24.6-k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s 
------------^ block here
```

systemctl status k3s.service:
```
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (start) since Mon 2022-10-03 03:17:46 CST; 9min ago
       Docs: https://k3s.io
    Process: 16747 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 16749 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 16754 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 16761 (k3s-server)
      Tasks: 8
     Memory: 354.3M
     CGroup: /system.slice/k3s.service
             └─16761 /usr/local/bin/k3s server
```
sudo journalctl -u k3s.service:
![QQ20221003-033234](https://user-images.githubusercontent.com/30611065/193472761-732d31c3-a8e4-4bc3-896c-91348affc063.png)

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - --docker

**Expected behavior:**

start success

**Actual behavior:**

![QQ20221003-033435](https://user-images.githubusercontent.com/30611065/193472852-e7932a4d-111c-4419-af21-9cf57cd783e3.png)
tried installing many times, all block here, total more than 30 min

**Additional context / logs:**

**Comment by brandond** [comment]
I can't copy-paste the specific log entry because you uploaded a screenshot instead of text, but it appears that etcd is hanging with a `db file is flocked by another process, or taking too long` error. What kind of storage are you running on?


It also appears that you're running the install script on a node that was already running K3s using embedded etcd. Are you sure that the previous installation of K3s was cleaned up properly? Did you still want to use etcd?

**Comment by zhaoyshine** [comment]
Hi @brandond, thank you for your reply, doesn't k3s use ```Sqlite``` as storage by default? I am a Single server. I have no requirements on what storage to use. I just want to run normally first, please give me any suggestions, thanks!!

**Comment by brandond** [comment]
Kine is the default, but your logs show that there are configuration and database files left over from a previous installation of k3s that used embedded etcd. Please run the uninstall script before installing again if you want a clean start.

**Comment by zhaoyshine** [comment]
@brandond thank you very much!
it is caused by the database, I can run success after specifying K3S_DATASTORE_ENDPOINT at install
```
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_DATASTORE_ENDPOINT="postgres://xxx:xxx@localhost:5432/k3s" sh -s - server --docker
```
