### ISSUE TITLE
Outbound network connection only working sometimes

### ISSUE THREAD

**Issue by tonsV2** [k3s-io/k3s#6238]
**Environmental Info:**
K3s Version: 
k3s version v1.25.2+k3s1 (53c268d8)
go version go1.19.1

Node(s) CPU architecture, OS, and Version: 
Linux performance-bot 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master node

**Describe the bug:**
Connecting to the internet from within a given pod only works sometimes.

I can use curl just fine from the host. If I do "curl google.com" I get the expected 301 response.

It also works as expected from within other docker containers. Executing something like "docker run -it alpine sh -c 'wget google.com'" works just fine.

However if I do it from a pod running within the cluster it only works about 20% of the times.

The below is terminal output from exec'ing into a pod and running the curl command. Out of six executions, only one succeeds.

```
$ kubectl exec -i -t -n perf-bot tons-db-2-database-postgresql-0 -c postgresql -- sh -c "clear; (bash || ash || sh)"
sh: 1: clear: not found
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
curl: (28) Failed to connect to google.com port 80: Connection timed out
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
curl: (28) Failed to connect to google.com port 80: Connection timed out
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
curl: (28) Failed to connect to google.com port 80: Connection timed out
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
curl: (28) Failed to connect to google.com port 80: Connection timed out
I have no name!@tons-db-2-database-postgresql-0:/$ curl google.com
curl: (28) Failed to connect to google.com port 80: Connection timed out
```

Please let me know if I should post any additional data.

**Steps To Reproduce:**
I'm not really sure how to reproduce this. I installed k3s using the below command and that's it. I tried various versions with the same result.

`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.2+k3s1 sh -`

**Expected behavior:**
Connecting should work every time.

**Actual behavior:**
Network only works some times.

**Comment by brandond** [comment]
I'm not aware of any issues with outbound networking. Do you perhaps have outbound firewall or security group rules that are blocking the connection? Have you tested with `curl -4` or `curl -6` to see if using IPv4 or v6 only changes the behavior?

**Comment by teleivo** [comment]
> I'm not aware of any issues with outbound networking. Do you perhaps have outbound firewall or security group rules that are blocking the connection? Have you tested with `curl -4` or `curl -6` to see if using IPv4 or v6 only changes the behavior?

Thank you @brandond for your hint 😄 @tonsV2 and I had a look and adding `-v` to curl showed what you point to. When curl goes with an IPv6 address of `google.com` it fails to reach it.

`Immediate connect fail for 2a00:1450:4016:80c::200e: Network unreachable`

If it goes with an IPv4 address it does reach it. (How curl chooses [IPv4](https://daniel.haxx.se/blog/2020/04/20/curl-ootw-ipv4/)/[IPv6](https://curl.se/libcurl/c/CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS.html)).

Whats puzzling to us is that k3s AFAIK by default is single stack IPv4-only, right?

How come pods will get an IPv6 link local address assigned to their network interface? Also in the pod we see IPv6 is not disabled `net.ipv6.conf.eth0.disable_ipv6 = 0`.

In another setup on EKS also single stack IPv4 pods only get an IPv4 with `net.ipv6.conf.eth0.disable_ipv6 = 1` while IPv6 is not disabled on the host as far as we can tell 😅.

Is it generally a bad idea to have dual-stack IPv4/IPv6 hosts but wanting to run single-stack IPv4 kubernetes on them?

With k3s is it only 

```
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
```

on the host or something else that influences what we experience? 

Thank you very much for your helping! 😄

**Comment by brandond** [comment]
> How come pods will get an IPv6 link local address assigned to their network interface?

This is how Linux works. If you have IPv6 enabled at a host level, interfaces will always get a link-local IPv6 address. If you don't want this, you should disable IPv6 on your node.
