### ISSUE TITLE
Failed to find cgroup v2 RPi (alt)

### ISSUE THREAD

**Issue by BrandWest** [k3s-io/k3s#6241]
**Environmental Info:**
K3s Version: 
k3s version v1.24.6+k3s1 (a8e0c66d)
go version go1.18.

Node(s) CPU architecture, OS, and Version: 
Linux node1 4.9.241-BPI-M5 #2 SMP PREEMPT Mon Jun 21 16:29:40 HKT 2021 aarch64 GNU/Linux

Cluster Configuration:
1 server. 4 agents. (4 RPI, 1 Banana Pi) The RPI's are running. FYI - The banana pi is running onhttps://wiki.banana-pi.org/Getting_Started_with_M5/M2Pro#Install_Image_to_EMMC with a 32GB microSD card as additional storage.

**Describe the bug:**
Working with a raspberry pi alternative (banana pi) when installing k3s with the k3s agent installs on the system and then fails to run with the following exit code: 
`Oct 09 15:47:34 node1 k3s[2888]: time="2022-10-09T15:47:34+01:00" level=fatal msg="failed to find cpu cgroup (v2)"
Oct 09 15:47:34 node1 systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE`

**Steps To Reproduce:**

All commands run as root via `sudo su -`.
- Pre-installation:
- `nano /boot/cmdline.txt` added: `cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory ip=10.0.0.203::10.0.0.1:255.255.255.0:node1:eth0:off`
- `nano /boot/config.txt` added: `arm_64bit=1`

- Installed K3s agent: 
Command run as root via `sudo su -`: `curl -sfL https://get.k3s.io | K3S_TOKEN="MyTokenFromServer" K3S_URL="https://[Server IP]:6443" K3S_NODE_NAME="node1" sh -` 

**Expected behavior:**

Expected to install and automatically start the k3s service

**Actual behavior:**

k3s service failed to load due to cgroup v2 not foud

**Additional context / logs:**

Full errors from `systemctl status k3s-agent.service`

● k3s-agent.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
     Active: activating (start) since Sun 2022-10-09 15:47:33 BST; 122ms ago
       Docs: https://k3s.io
    Process: 2872 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 2886 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 2887 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 2888 (k3s-agent)
      Tasks: 6
     Memory: 10.3M
     CGroup: /system.slice/k3s-agent.service
             └─2888 /usr/local/bin/k3s

Oct 09 15:47:33 node1 systemd[1]: Starting Lightweight Kubernetes...
Oct 09 15:47:33 node1 sh[2872]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Oct 09 15:47:33 node1 sh[2881]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Oct 09 15:47:34 node1 k3s[2888]: time="2022-10-09T15:47:34+01:00" level=info msg="Starting k3s agent v1.24.6+k3s1 (a8e0c66d)"
Oct 09 15:47:34 node1 k3s[2888]: time="2022-10-09T15:47:34+01:00" level=fatal msg="failed to find cpu cgroup (v2)"
Oct 09 15:47:34 node1 systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 15:47:34 node1 systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
Oct 09 15:47:34 node1 systemd[1]: Failed to start Lightweight Kubernetes.

journalctl -xe
`Oct 09 16:04:26 node1 systemd[1]: Starting Lightweight Kubernetes...
░░ Subject: A start job for unit k3s-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit k3s-agent.service has begun execution.
░░ 
░░ The job identifier is 13939.
Oct 09 16:04:26 node1 sh[7640]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Oct 09 16:04:26 node1 sh[7641]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Oct 09 16:04:26 node1 k3s[7645]: time="2022-10-09T16:04:26+01:00" level=info msg="Starting k3s agent v1.24.6+k3s1 (a8e0c66d)"
Oct 09 16:04:26 node1 k3s[7645]: time="2022-10-09T16:04:26+01:00" level=fatal msg="failed to find cpu cgroup (v2)"
Oct 09 16:04:26 node1 systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit k3s-agent.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 09 16:04:26 node1 systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit k3s-agent.service has entered the 'failed' state with result 'exit-code'.
Oct 09 16:04:26 node1 systemd[1]: Failed to start Lightweight Kubernetes.

I've ensured that cgroup2 is mounted via `mount` : `cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)`

I attempted to `apt-get install cgroupfs-mount` and ran `cgroupfs-mount` the output is:
`mount: /sys/fs/cgroup/memory: cgroup already mounted on /sys/fs/cgroup/cpuset.
mount: /sys/fs/cgroup/pids: cgroup already mounted on /sys/fs/cgroup/cpuset.`

Checked to see the cgroup.controllers with ` cat /sys/fs/cgroup/cgroup.controllers` resulting in:
`memory pids` (I expected to see cpuset here, but that could be because I don't know any better)

**Comment by brandond** [comment]
> `failed to find cpu cgroup`

It sounds like your system is using hybrid (mixed cgroup v1/v2) and the cpu controller is still on v1. You should disable the hybrid configuration, and go for pure v1 or v2.

**Comment by VestigeJ** [comment]
I'm chasing down some similar behavior on my Jetson Nano's @BrandWest I'll let you know what I find - I think it's related to the cgroup kernel params

**Comment by VestigeJ** [comment]
@BrandWest Seems like this is what ended up sorting out my installations - https://kubernetes.io/docs/concepts/architecture/cgroups/#linux-distribution-cgroup-v2-support

I'm still playing with any potential additional cgroup cmdline flags but this took care of the error you reported and I experienced.

**Comment by BrandWest** [comment]
> > `failed to find cpu cgroup`
> 
> It sounds like your system is using hybrid (mixed cgroup v1/v2) and the cpu controller is still on v1. You should disable the hybrid configuration, and go for pure v1 or v2.

I will attempt this and see where I get.

I will also follow up with @VestigeJ 's suggestion

**Comment by BrandWest** [comment]
@brandond according to my `stat -fc %T /sys/fs/cgroup/` and `[ $(stat -fc %T /sys/fs/cgroup/) = "cgroup2fs" ] && echo "unified" || ( [ -e /sys/fs/cgroup/unified/ ] && echo "hybrid" || echo "legacy")` I am running cgroupsfs and unified respectively. 

I've attempted to add other flags requiring cgroup v2s including:` systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all cgroup_enable=cpu cgroup_enable=cpuset cgroup_cpu=1 cgroup_cpuset=1 cgroup_enable=memory cgroup_memory=1`

From my research hierarchy=1 forces cgroup v2 and cgroup_no_v1=all should stop cgroup 1's from being used.

However, my exit code continues to be "Failed to find CPU Cgroup (V2)".

Additionally I followed @VestigeJ 's suggestion and after getting all the proper packages installed I still have the same issue.

**Comment by brandond** [comment]
What platform is this on? I have K3s running on several Pi4bs with Ubuntu with no problems or special configuration necessary. Is this another Jetson or off-brand Pi clone board? I wonder if there's something odd in their kernel configuration?

**Comment by BrandWest** [comment]
It is an off brand Pi clone, a Banana Pi.

**Comment by brandond** [comment]
Yeah, I suspect that there are features missing from their kernel build.

**Comment by BrandWest** [comment]
After a bunch of issues I was able to install their version of Ubuntu and install k3s.

**Comment by JoelJoos** [comment]
> After a bunch of issues I was able to install their version of Ubuntu and install k3s.

Were they issues with the manufacturer? Or were you able to resolve it on your own?
