### ISSUE TITLE
Enabling distributed tracing feature gate on API Server causes a crash.

### ISSUE THREAD

**Issue by austinlparker** [k3s-io/k3s#6254]
**Environmental Info:**
K3s Version: v1.25.2+k3s1

Node(s) CPU architecture, OS, and Version: `Linux minikube 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: Initial cluster server

**Describe the bug:**
Enabling `--kube-apiserver-arg=feature-gates=APIServerTracing=true` causes a repeatable crash from the APIServer.

**Steps To Reproduce:**
K3S install performed via script as follows:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.2+k3s1 K3S_TOKEN=secret INSTALL_K3S_EXEC="--kube-apiserver-arg=feature-gates=APIServerTracing=true --kube-apiserver-arg=tracing-config-file=/etc/kube-tracing/apiserver-tracing.yaml" sh -s - server --cluster-init
```

contents of `/etc/kube-tracing/apiserver-tracing.yaml`:
```
apiVersion: apiserver.config.k8s.io/v1alpha1
kind: TracingConfiguration
endpoint: 127.0.0.1:4317
samplingRatePerMillion: 1000000
```

In addition, you'll need the OpenTelemetry Collector running (default config is fine):
```
wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.61.0/otelcol_0.61.0_linux_amd64.deb
dpkg -i otelcol_0.61.0_linux_amd64.deb
```

**Expected behavior:** API Server to not crash and send traces to the defined endpoint.

**Actual behavior:** API Server crashed.

**Additional context / logs:**
```Oct 11 01:59:50 minikube k3s[15283]: I1011 01:59:50.329337   15283 server.go:581] external host was not specified, using 161.35.136.186
Oct 11 01:59:50 minikube k3s[15283]: I1011 01:59:50.329982   15283 server.go:171] Version: v1.25.2+k3s1
Oct 11 01:59:50 minikube k3s[15283]: I1011 01:59:50.330292   15283 server.go:173] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Oct 11 01:59:50 minikube k3s[15283]: 2022/10/11 01:59:50 <nil>
Oct 11 01:59:50 minikube k3s[15283]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 11 01:59:50 minikube k3s[15283]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26f98a7]
Oct 11 01:59:50 minikube k3s[15283]: goroutine 1247 [running]:
Oct 11 01:59:50 minikube k3s[15283]: k8s.io/apiserver/pkg/server/options.(*TracingOptions).ApplyTo.func1({0x57a7f68?, 0xc0011fb200?}, {0xc000bd7140?, 0x58660b?})
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apiserver@v1.25.2-k3s1/pkg/server/options/tracing.go:106 +0x27
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc/internal/transport.dial({0x57a7f68, 0xc0011fb200}, 0xc000bc69b0, {{0xc000bd7140, 0xe}, {0xc000bd7140, 0xe}, 0x0, 0x0, {0x0, ...}}, ...)
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/http2_client.go:157 +0x1d9
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc/internal/transport.newHTTP2Client({_, _}, {_, _}, {{0xc000bd7140, 0xe}, {0xc000bd7140, 0xe}, 0x0, 0x0, ...}, ...)
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/http2_client.go:196 +0x166
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc/internal/transport.NewClientTransport(...)
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/transport.go:574
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc.(*addrConn).createTransport(0xc0000c6b00, {{0xc000bd7140, 0xe}, {0xc000bd7140, 0xe}, _, _, {_, _}}, {{0x4cdbaa9, ...}, ...}, ...)
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1328 +0x439
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0000c6b00, {0xc00157e680?, 0x1, 0xc001039e68?}, {0x4077f1?, 0x489d240?, 0x80cebe0?})
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1258 +0x4b9
Oct 11 01:59:50 minikube k3s[15283]: google.golang.org/grpc.(*addrConn).resetTransport(0xc0000c6b00)
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1173 +0x265
Oct 11 01:59:50 minikube k3s[15283]: created by google.golang.org/grpc.(*addrConn).connect
Oct 11 01:59:50 minikube k3s[15283]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:849 +0x136
Oct 11 01:59:50 minikube systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT```
<!-- Add any other context and/or logs about the problem here. -->

**Comment by brandond** [comment]
The crash doesn't seem to be anywhere in k3s code; it's somewhere in the apiserver. Is there some additional configuration necessary, either on the apiserver, or on your trace collector?

**Comment by brandond** [comment]
Also, your endpoint doesn't appear to be correct? The docs say it should be in one of the formats listed here:
https://github.com/grpc/grpc/blob/master/doc/naming.md

**Comment by austinlparker** [comment]
shouldn't be any additional config on the APIServer or in the collector. Let me try changing the name, although I've used this same config in Minikube (for example) without a crash.

**Comment by brandond** [comment]
It looks like the crash is here: https://github.com/kubernetes/kubernetes/blob/v1.25.2/staging/src/k8s.io/apiserver/pkg/server/options/tracing.go#L106

It seems like this code might not handle egress selector configuration properly? Try starting with --egress-selector-mode=disabled

**Comment by austinlparker** [comment]
Same problem with `--egress-selector-mode=disabled`. Should I file a bug against upstream k8s then?

**Comment by brandond** [comment]
Yeah, that's probably where it needs to be fixed, if even disabling it doesn't work right.

You might also try `--kube-apiserver-arg=egress-selector-config-file=` but I'm not optimistic.

**Comment by austinlparker** [comment]
`--kube-apiserver-arg=egress-selector-config-file=` worked, everything came right up. Interesting!

**Comment by brandond** [comment]
I'm curious, if you put this into a file and point minkube's `--egress-selector-config-file` at it, does it also crash?

```json
{"kind":"EgressSelectorConfiguration","apiVersion":"apiserver.k8s.io/v1beta1","EgressSelections":[{"Name":"cluster","Connection":{"ProxyProtocol":"Direct","Transport":null}}]}
```

**Comment by brandond** [comment]
yep, there's definitely a bug there. `Lookup` may return a null dialer but also no error if one isn't configured for that particular context.
https://github.com/kubernetes/kubernetes/blob/v1.25.2/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go#L389-L396

Other places where this is used, the returned dialer is either set as an optional custom dialer (where `nil` is OK, and just uses the default dialer), or there are explicit nil checks.

* https://github.com/kubernetes/kubernetes/blob/v1.25.2/cmd/kube-apiserver/app/server.go#L501-L507
* https://github.com/kubernetes/kubernetes/blob/v1.25.2/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L238


Let me know if you end up opening a bug upstream. If not, I'll probably open one myself.

**Comment by austinlparker** [comment]
https://github.com/kubernetes/kubernetes/issues/112976 upstream issue

**Comment by brandond** [comment]
Closing in favor of upstream issue.
