### ISSUE TITLE
Adding K3s worker node on RKE2 configure K8s cluster

### ISSUE THREAD

**Issue by ajeesh-urolime** [k3s-io/k3s#6259]
k3s version: v1.24.6
OS: Ubuntu 18.4 LTS
Arch: ARM aarch64

I am trying to add one of my ARM aarch64-based node to my existing RKE2-based K8s cluster as a worker node. Since I would need to run some applications on ARM-based architecture. So first I installed K3s on my ARM instance and then tried to connect this node using my Rancher-generated script as follows

`curl --insecure -fL https://myrachercluster.com/system-agent-install.sh | sudo  sh -s - --server https://myrachercluster.com --label 'cattle.io/os=linux' --token xxxx --ca-checksum 333xx --worker`

But this is not working and I am getting the error message,

```
Oct 11 15:23:38 ip-172-x rancher-system-agent[4934]: time="2022-10-11T15:23:38Z" level=error msg="error while staging: no child with platform linux/arm64 in in>
Oct 11 15:23:38 ip-172-x rancher-system-agent[4934]: time="2022-10-11T15:23:38Z" level=error msg="error executing instruction 0: no child with platform linux/
```
Rancher console error,
![Screenshot from 2022-10-11 21-07-32](https://user-images.githubusercontent.com/26244606/195162089-8348892c-41b5-45dd-bf5e-2eb2ea26251d.png)

Is it possible to add my ARM-based instance as a worker node to the existing RKE2/RKE-installed K8s cluster?

**Comment by brandond** [comment]
No. We do not support heterogeneous clusters (clusters using different distributions). All of the cluster members must be running the same Kubernetes distro.
