### ISSUE TITLE
k3s streaming bootstrap is not working behind corporate proxy even after adding the proxy in environment

### ISSUE THREAD

**Issue by ritarya** [k3s-io/k3s#627]
I am unable to bootstrap "**k3s server**" on my VM running behind the corporate proxy even after enabling **http_proxy, https_proxy, no_proxy** into the Environment. CoreDNS pod and traefik pod keep stuck in "ContainerCreating" state.
Below is the error Message from the bootstrap console:

RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: proxyconnect tcp: EOF

CreatePodSandbox for pod "coredns-695688789-lcnvf_kube-system(b36be71d-a25a-11e9-acfe-fa163e3e80b3)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: proxyconnect tcp: EOF

CreatePodSandbox for pod "helm-install-traefik-gtvmg_kube-system(b36c38d3-a25a-11e9-acfe-fa163e3e80b3)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: proxyconnect tcp: EOF
 
Any help on this will be really appreciated! Thanks.

**Comment by erikwilson** [comment]
Sorry you are having issues, if you could provide some additional info such as the version of k3s and the value of no_proxy that would be helpful. Are you able to curl https://k8s.gcr.io/v2/pause/manifests/3.1 through the proxy?

**Comment by ritarya** [comment]
Hi @erikmcc Please find the below details on the problem:
**k3s version:** k3s version v0.6.1 (7ffe802a)
what can be the values that should be added in no_proxy?
Yes, and i am able to curl https://k8s.gcr.io/v2/pause/manifests/3.1.
Please find the output below for the confirmation:
[root@k3s-server-1 system]# curl -kv https://k8s.gcr.io/v2/pause/manifests/3.1
* About to connect() to proxy proxy.esl.cisco.com port 8080 (#0)
*   Trying 173.36.224.109...
* Connected to proxy.esl.cisco.com (173.36.224.109) port 8080 (#0)
* Establish HTTP proxy tunnel to k8s.gcr.io:443
> CONNECT k8s.gcr.io:443 HTTP/1.1
> Host: k8s.gcr.io:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.gcr.io,O=Google LLC,L=Mountain View,ST=California,C=US
* 	start date: Jun 18 08:36:51 2019 GMT
* 	expire date: Sep 10 08:16:00 2019 GMT
* 	common name: *.gcr.io
* 	issuer: CN=Google Internet Authority G3,O=Google Trust Services,C=US
> GET /v2/pause/manifests/3.1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: k8s.gcr.io
> Accept: */*
> 
< HTTP/1.1 200 OK
< Docker-Distribution-API-Version: registry/2.0
< Content-Type: application/vnd.docker.distribution.manifest.list.v2+json
< Content-Length: 1665
< Docker-Content-Digest: sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea
< Date: Wed, 10 Jul 2019 15:34:04 GMT
< Server: Docker Registry
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
< 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 527,
         "digest": "sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 527,
         "digest": "sha256:c84b0a3a07b628bc4d62e5047d0f8dff80f7c00979e1e28a821a033ecda8fe53",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 527,
         "digest": "sha256:f365626a556e58189fc21d099fc64603db0f440bff07f77c740989515c544a39",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 527,
         "digest": "sha256:bcf9771c0b505e68c65440474179592ffdfa98790eb54ffbf129969c5e429990",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 527,
         "digest": "sha256:882a20ee0df7399a445285361d38b711c299ca093af978217112c73803546d5e",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
* Connection #0 to host proxy.esl.cisco.com left intact

Please let me know if you need any more details here. Thanks!

**Comment by ritarya** [comment]
Hi @erikmcc Please find the below details on the problem:
k3s version: k3s version v0.6.1 (7ffe802)
what can be the values that should be added in no_proxy?
Yes, and i am able to curl https://k8s.gcr.io/v2/pause/manifests/3.1.
Please find the output below for the confirmation:
[root@k3s-server-1 system]# curl -kv https://k8s.gcr.io/v2/pause/manifests/3.1

About to connect() to proxy proxy.***.com port 8080 (#0)
Trying 173.36.224.109...
Connected to proxy.esl.cisco.com (173.36.224.109) port 8080 (#0)
Establish HTTP proxy tunnel to k8s.gcr.io:443
CONNECT k8s.gcr.io:443 HTTP/1.1
Host: k8s.gcr.io:443
User-Agent: curl/7.29.0
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 Connection established
<

Proxy replied OK to CONNECT request
Initializing NSS with certpath: sql:/etc/pki/nssdb
skipping SSL peer certificate verification
SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
Server certificate:
subject: CN=*.gcr.io,O=Google LLC,L=Mountain View,ST=California,C=US
start date: Jun 18 08:36:51 2019 GMT
expire date: Sep 10 08:16:00 2019 GMT
common name: *.gcr.io
issuer: CN=Google Internet Authority G3,O=Google Trust Services,C=US
GET /v2/pause/manifests/3.1 HTTP/1.1
User-Agent: curl/7.29.0
Host: k8s.gcr.io
Accept: /

< HTTP/1.1 200 OK
< Docker-Distribution-API-Version: registry/2.0
< Content-Type: application/vnd.docker.distribution.manifest.list.v2+json
< Content-Length: 1665
< Docker-Content-Digest: sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea
< Date: Wed, 10 Jul 2019 15:34:04 GMT
< Server: Docker Registry
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
<
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 527,
"digest": "sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 527,
"digest": "sha256:c84b0a3a07b628bc4d62e5047d0f8dff80f7c00979e1e28a821a033ecda8fe53",
"platform": {
"architecture": "arm",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 527,
"digest": "sha256:f365626a556e58189fc21d099fc64603db0f440bff07f77c740989515c544a39",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 527,
"digest": "sha256:bcf9771c0b505e68c65440474179592ffdfa98790eb54ffbf129969c5e429990",
"platform": {
"architecture": "ppc64le",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 527,
"digest": "sha256:882a20ee0df7399a445285361d38b711c299ca093af978217112c73803546d5e",
"platform": {
"architecture": "s390x",
"os": "linux"
}
}
]

Connection #0 to host proxy...com left intact
Please let me know if you need any more details here. Thanks!

**Comment by landonc** [comment]
I fixed this issue by adding the proxy settings to the /etc/systemd/system/k3s.service.env file as it seems to not be loading the proxy setting exported via /etc/profile.  Once I added the http_proxy, https_proxy, and no_proxy settings to the .env and restarted my containers came up correctly.

**Comment by brandond** [comment]
Closing due to age. The above-linked PR should also address the issue.
