### ISSUE TITLE
Trying to understand service type NodePort timeout

### ISSUE THREAD

**Issue by maitredede** [k3s-io/k3s#6279]
Hello :)

**Environmental Info:**
K3s Version: v1.24.6+k3s1

```
k3s version v1.24.6+k3s1 (a8e0c66d)
go version go1.18.6
```

Node(s) CPU architecture, OS, and Version: 

Linux node-1 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
Linux node-2 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
Linux node-3 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

Cluster Configuration:

3 servers

**Describe the bug:**

**Steps To Reproduce:**

- 3 server nodes, ip are 192.168.20.20x (201,202,203... 200 is vip)
- Installed K3s first node: `curl -sfL https://get.k3s.io | sh -s - --cluster-init --token="redacted" --tls-san=192.168.20.200 --flannel-backend=host-gw --disable=traefik --disable=local-storage --disable=metrics-server`
- next nodes : `curl -sfL https://get.k3s.io | sh -s - --server https://192.168.20.201:6443 --token="redacted" --flannel-backend=host-gw --disable=traefik --disable=local-storage --disable=metrics-server`
- installed rook, kube-vip, nginx ingress
- deployed using helm a statefullset+service (gitea), service type NodePort, with node port value 32022 (for gitea ssh port)

**Expected behavior:**

SSH connection to any of the 3 node on port 32022 should work (or to the VIP).

**Actual behavior:**

Only port 32022 of node where pod is deployed accepts connection. Connections to other nodes goes timeout (also if the vip is on an other node).

**Additional context / logs:**

**Comment by manuelbuil** [comment]
Can you provide the output of `kubectl get services -A -o wide`?

**Comment by maitredede** [comment]
```
gitea-ci        gitea-db-pgpool                                      ClusterIP      10.43.70.105    <none>                                         5432/TCP                       17d     app.kubernetes.io/component=pgpool,app.kubernetes.io/instance=gitea-db,app.kubernetes.io/name=gitea-db
gitea-ci        gitea-db-postgresql                                  ClusterIP      10.43.186.99    <none>                                         5432/TCP                       17d     app.kubernetes.io/component=postgresql,app.kubernetes.io/instance=gitea-db,app.kubernetes.io/name=gitea-db
gitea-ci        gitea-db-postgresql-headless                         ClusterIP      None            <none>                                         5432/TCP                       17d     app.kubernetes.io/component=postgresql,app.kubernetes.io/instance=gitea-db,app.kubernetes.io/name=gitea-db
gitea-ci        gitea-db-postgresql-metrics                          ClusterIP      10.43.175.88    <none>                                         9187/TCP                       17d     app.kubernetes.io/component=postgresql,app.kubernetes.io/instance=gitea-db,app.kubernetes.io/name=gitea-db
gitea-ci        gitea-http                                           ClusterIP      None            <none>                                         3000/TCP                       17d     app.kubernetes.io/instance=gitea,app.kubernetes.io/name=gitea
gitea-ci        gitea-memcached                                      ClusterIP      None            <none>                                         11211/TCP                      7d13h   app.kubernetes.io/instance=gitea,app.kubernetes.io/name=memcached
gitea-ci        gitea-ssh                                            NodePort       10.43.253.60    <none>                                         2022:32022/TCP                 7d13h   app.kubernetes.io/instance=gitea,app.kubernetes.io/name=gitea
```

**Comment by brandond** [comment]
> `gitea-ci        gitea-ssh                                            NodePort       10.43.253.60    <none>                                         2022:32022/TCP`

It appears that the service is on 2022; the pod is using 32022. So it makes sense that you can only reach 32022 on the node where the pod is running. Did you perhaps typo the port on the service?

**Comment by maitredede** [comment]
The pod runs ssh on port 2022 (double check and redeployed with enforced config).

`kubectl  -n gitea-ci describe service gitea-ssh` :
```
Name:                     gitea-ssh
Namespace:                gitea-ci
Labels:                   app=gitea
                          app.kubernetes.io/instance=gitea
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=gitea
                          app.kubernetes.io/version=1.17.3
                          helm.sh/chart=gitea-6.0.3
                          version=1.17.3
Annotations:              meta.helm.sh/release-name: gitea
                          meta.helm.sh/release-namespace: gitea-ci
Selector:                 app.kubernetes.io/instance=gitea,app.kubernetes.io/name=gitea
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.46.204
IPs:                      10.43.46.204
Port:                     ssh  2022/TCP
TargetPort:               2022/TCP
NodePort:                 ssh  32022/TCP
Endpoints:                10.42.2.52:2022
Session Affinity:         None
External Traffic Policy:  Local
Events:                   <none>
```
So if I understand correctly, the service listen on node (every node) port 32022 targeting pod port 2022.
The pod runs on node-3. When I `ssh -p 32022 node-3` from my workstation, it works. But if I try to other nodes, it does not (looks it goes timeout).
I have `ip route get 10.42.2.52` (the endpoint) on each nodes. node 1 and 2 shows something like `<endpoint> via <node-3 ip> dev <lan card> src <lan ip>`. on node-3 `<endpoint> dev cni0`.

Is there something I have missed ?

**Comment by maitredede** [comment]
I think I found the mistake : `externalTrafficPolicy: Local`. It falls into network routing issues. Replaced with `externalTrafficPolicy: Cluster`.

**Comment by brandond** [comment]
That would do it...
