### ISSUE TITLE
Prometheus API server monitoring is not working out of the box

### ISSUE THREAD

**Issue by JeffreyVdb** [k3s-io/k3s#628]
**Describe the bug**

When installing prometheus using the community helm chart, the wrong API server IP is used for monitoring.

This should work out of the box

**To Reproduce**

```
helm fetch --untar stable/prometheus
cd prometheus
helm template --name=my-prometheus . | kubectl apply -f -
```

**Expected behavior**

The API server is monitored correctly

**Screenshots**

![Screenshot from 2019-07-10 13-48-43](https://user-images.githubusercontent.com/681226/60967046-fc111a80-a319-11e9-9c01-53050d9813f4.png)

**Comment by erikwilson** [comment]
Thanks for reporting this! Would be helpful to know the version of k3s also, I think this should be fixed with the 0.7.0 RCs, if you are able to confirm it has been fixed or not in v0.7.0-rc4 would be greatly appreciated.

**Comment by ahmedmagdiosman** [comment]
Just to add another data point, I've had this issue with 0.6.1. I haven't tried any of the RCs.

**Comment by BlackTurtle123** [comment]
> Thanks for reporting this! Would be helpful to know the version of k3s also, I think this should be fixed with the 0.7.0 RCs, if you are able to confirm it has been fixed or not in v0.7.0-rc4 would be greatly appreciated.

We did try this with the 7rc4, here it was still happening.

**Comment by runningman84** [comment]
see https://github.com/rancher/k3s/issues/425

**Comment by brandond** [comment]
Closing due to age. Prometheus monitoring is working fine for me, and via Rancher monitoring app.
