### ISSUE TITLE
k3s kubectl requires access to k3s config file

### ISSUE THREAD

**Issue by xoxys** [k3s-io/k3s#6280]
**Environmental Info:**
K3s Version: 
```
k3s version v1.25.0+k3s1 (26e94057)
go version go1.19
```

Node(s) CPU architecture, OS, and Version: 
```
Linux ratchet 5.14.0-70.22.1.el9_0.x86_64 #1 SMP PREEMPT Tue Aug 9 19:45:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
Single master

**Describe the bug:**

After starting k3s via systemd service using a config file like `usr/local/bin/k3s server --config /etc/rancher/k3s/config.yaml`, `kubectl` requires access to `/etc/rancher/k3s/config.yaml`. As a result, unprivileged users can't use the `k3s kubectl` while the config file permission is restricted to e.g. `0600`.

**Expected behavior:**
I would expect `k3s kubectl` can be used from unprivileged users as well as long as those users have access to the `KUBECONFIG`.

**Additional context / logs:**
```
$ kubectl
FATA[0000] open /etc/rancher/k3s/config.yaml: permission denied
```

**Comment by xoxys** [comment]
Looks like there is more stuff executed, even if it is not required by the `kubectl` sub-command:

```
$ k3s kubectl
INFO[0000] Acquiring lock file /home/user/.rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /home/user/.rancher/k3s/data/5793f70de32aabc988a4b2734c5dda8caa4439e45176b663b5e317f3e9a83609 
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/

Basic Commands (Beginner):
[...]
```

**Comment by brandond** [comment]
Any time you run the k3s self-extracting wrappers, it will attempt to ensure that the binaries have been extracted out to the location specified by the data-dir. This also requires reading the config file. This is expected behavior. If you want to bypass this, you can add `/var/lib/rancher/k3s/data/current/bin/` to your PATH.

**Comment by xoxys** [comment]
Got it :+1: Thanks for your feedback.
