### ISSUE TITLE
node.spec.providerID is not URI formatted and no longer includes the node name

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6283]
**Environmental Info:**
K3s Version: 
v1.25.3-rc1+k3s1

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
n/a

**Describe the bug:**
* node.spec.providerID is not URI formatted and no longer includes the node name
* https://github.com/rancher/rke2/issues/3464

**Steps To Reproduce:**
start K3s

**Expected behavior:**
providerID should be in the format `k3s://nodename`

**Actual behavior:**
providerID is just `k3s`

**Additional context / logs:**
Downstream projects depend on this being set in the required format

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit b276b581 and version v1.25.3+k3s1
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-46-86 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summer
cluster-init: true
secrets-encryption: true
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s:
 - For validation: `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=b276b58175e914a24b93f56751335b55cd7a60ab sh - `
3. Check providerid: `kubectl describe node | grep -i providerid`
 
**Replication Results:**
Unable to replicate
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.25.3+k3s-b276b581 (b276b581)
go version go1.19.2
```
 

- Observed providerid is shown as expected format `k3s://nodename`
```
kubectl describe node | grep -i providerid
ProviderID:                   k3s://ip-xxx-yy-zz-86
```
 
**Additional context / logs:**
- Snippet of yaml for node: `kubectl get nodes nodename -o yaml`
```
spec:
...
  providerID: k3s://ip-xxx-yy-zz-86
```
