### ISSUE TITLE
v1.21.13+k3s1 Disk usage exceeds 85%, the image will be deleted and the node will be tainted

### ISSUE THREAD

**Issue by Heyz6** [k3s-io/k3s#6290]
v1.21.13+k3s1
docker version 20.10.18
Disk usage exceeds 85%, the image will be deleted and the node will be tainted

logs:
Events:
  Type     Reason                   Age                    From        Message
  ----     ------                   ----                   ----        -------
  Normal   NodeHasDiskPressure      12m                    kubelet     Node node1 status is now: NodeHasDiskPressure
  Warning  FreeDiskSpaceFailed      11m                    kubelet     failed to garbage collect required amount of images. Wanted to free 15152714547 bytes, but freed 0 bytes
  Warning  EvictionThresholdMet     9m18s (x15 over 12m)   kubelet     Attempting to reclaim ephemeral-storage
  Normal   NodeHasSufficientMemory  3m46s (x7 over 3m52s)  kubelet     Node node1 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    3m46s (x7 over 3m52s)  kubelet     Node node1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     3m46s (x7 over 3m52s)  kubelet     Node node1 status is now: NodeHasSufficientPID
  Normal   Starting                 3m42s                  kube-proxy  Starting kube-proxy.
  Normal   NodeHasNoDiskPressure    2m38s (x8 over 2m51s)  kubelet     Node node1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientMemory  2m38s (x8 over 2m51s)  kubelet     Node node1 status is now: NodeHasSufficientMemory
  Normal   Starting                 2m36s                  kube-proxy  Starting kube-proxy.
  Normal   NodeHasSufficientMemory  39s (x7 over 46s)      kubelet     Node node1 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    39s (x7 over 46s)      kubelet     Node node1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     39s (x7 over 46s)      kubelet     Node node1 status is now: NodeHasSufficientPID

How should I set it up without limiting disk usage, deleting images and tainting

**Comment by brandond** [comment]
Yes, this is how the kubelet works. Consult the upstream documentation at https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/
