### ISSUE TITLE
cgroup unified expected wrong location? [exec failed: error adding pid to cgroups]

### ISSUE THREAD

**Issue by narcoticfresh** [k3s-io/k3s#6302]
**Environmental Info:**
K3s Version: 
```
k3sdude:/home/dn# k3s -v
k3s version v1.25.2+k3s1 (53c268d8)
go version go1.19.1
``` 
Distribution is Alpine Linux 3.16

Node(s) CPU architecture, OS, and Version: 
``` 
k3sdude:/home/dn# uname -a
Linux k3sdude 5.15.72-0-rpi4 #1-Alpine SMP PREEMPT Mon Oct 10 13:00:16 UTC 2022 aarch64 Linux
``` 

Cluster Configuration:
``` 
k3sdude:~$ k get nodes -o wide
NAME      STATUS                        ROLES                       AGE    VERSION        INTERNAL-IP    EXTERNAL-IP    OS-IMAGE            KERNEL-VERSION   CONTAINER-RUNTIME
k3sdude   Ready                         control-plane,etcd,master   176d   v1.25.2+k3s1   192.168.1.49   192.168.1.49   Alpine Linux edge   5.15.72-0-rpi4   containerd://1.6.8-k3s1
w2        Ready                         <none>                      176d   v1.25.2+k3s1   192.168.1.47   192.168.1.47   Alpine Linux edge   5.15.73-0-lts    containerd://1.6.8-k3s1
w4        Ready                         <none>                      34d    v1.25.2+k3s1   192.168.1.44   192.168.1.44   Alpine Linux edge   5.15.72-0-rpi4   containerd://1.6.8-k3s1
``` 

2 nodes are Raspberry Pi 4s, one is an amd64 arch.. all of them are effected of the bug..

**Describe the bug:**

I setup this cluster a while ago.. after recent updates (it's unclear whether it was the Alpine Linux 3.16 update or the K3s 1.25.* update) - it is now impossible to `exec` into a running container due to a cgroup problem:

``` 
host:/# crictl exec -ti a1d258cd01eb1 bash
FATA[0000] execing command in container: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "8eabd87df6d9b37b935e7d5b9c439ddab304f4013a46289915b280ca6bc23655": OCI runtime exec failed: exec failed: unable to start container process: error adding pid 5788 to cgroups: failed to write 5788: open /sys/fs/unified/kubepods/burstable/pod9f0a88d8-fb33-402c-ae50-06bfeca4dd40/a1d258cd01eb125761a564511b2fd5eff0ff0aabf6356ee6e9dbd93ece40f673/cgroup.procs: no such file or directory: unknown 
``` 

These are the mounts

```
host:/# mount | grep cgroup
cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids)
openrc on /sys/fs/cgroup/openrc type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/rc/sh/cgroup-release-agent.sh,name=openrc)
none on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```

--> It seems that the `unified` structure is searched for at `/sys/fs/unified` by `crictl`, whereas it is on `/sys/fs/cgroup/unified`

Strangely, everything *else* (scheduling, workload execution; everything k3s does) seems to work pefectly fine.. so the cluster is "good" - but the inability to exec into running containers is quite hindering.

**Steps To Reproduce:**

* Install described k3s version on Alpine Linux 3.16
* Try to exec into running container

**Expected behavior:**
It is possible to exec into a running container

**Actual behavior:**
It is not possible to exec into a running container.

**Additional context / logs:**

**Comment by brandond** [comment]
You appear the be using hybrid cgroups, where some of the controllers are mounted individually under the v1 hierarchy, and others are mounted as unified (cgroupv2). This mode does not work well, and should not be used. I would recommend finding some way to switch your system over to use only cgroupv2.

You can reference https://github.com/systemd/systemd/blob/main/docs/CGROUP_DELEGATION.md for more information.

**Comment by narcoticfresh** [comment]
@brandond 
thanks for your reply.. yeah, i tried that already before, but didn't progress much..

after i changed 
`rc_cgroup_mode="unified"`
and a reboot, the mounts indeed look different:

```
w4:/home/dn# mount | grep cgroup
cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids)
none on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```

but then the Node stays `NotReady` - k3s-agent.log only shows..

```
w4:/home/dn# tail -f /var/log/k3s-agent.log
time="2022-10-21T07:10:38+02:00" level=info msg="Starting k3s agent v1.25.2+k3s1 (53c268d8)"
time="2022-10-21T07:10:38+02:00" level=fatal msg="failed to find cpu cgroup (v2)"
time="2022-10-21T07:10:44+02:00" level=info msg="Starting k3s agent v1.25.2+k3s1 (53c268d8)"
time="2022-10-21T07:10:44+02:00" level=fatal msg="failed to find cpu cgroup (v2)"
time="2022-10-21T07:10:49+02:00" level=info msg="Starting k3s agent v1.25.2+k3s1 (53c268d8)"
time="2022-10-21T07:10:49+02:00" level=fatal msg="failed to find cpu cgroup (v2)"
time="2022-10-21T07:10:52+02:00" level=info msg="Starting k3s agent v1.25.2+k3s1 (53c268d8)"
time="2022-10-21T07:10:52+02:00" level=fatal msg="failed to find cpu cgroup (v2)"
```

I read the document you linked, checked the `rc.conf` comments.. I'm not too familiar with `cgroups` to see what exactly is wrong.. when i check the directory, it has this content:

```
w4:/home/dn# ls /sys/fs/cgroup/
cgroup.controllers      cgroup.max.descendants  cgroup.stat             cgroup.threads          k3s-agent               rpcbind
cgroup.max.depth        cgroup.procs            cgroup.subtree_control  cpu.stat                rpc.statd               sshd
```

**Comment by brandond** [comment]
Hmm. It looks like it is still in a hybrid configuration.

**Comment by narcoticfresh** [comment]
aaah.. i still had an old `cgroup` fstype entry in my `/etc/fstab`.. 

so, for future reference.. if any alpine users find this:
* make sure you remove any `cgroup` lines in `/etc/fstab` - `cgroups` is mounted via the cgroups _service_..
* set `rc_cgroup_mode="unified"` in `/etc/rc.conf`

i guess that all was changed in the alpine 3.16 update..

@brandond thanks for your input!

**Comment by brandond** [comment]
Glad you were able to figure it out! That's quite the post-upgrade gotcha for Alpine to leave their users to figure out on their own.

**Comment by rhrn** [comment]
It helped me.
https://www.reddit.com/r/AlpineLinux/comments/12df03b/struggling_to_enable_cgroups_via_an_overlay/
