### ISSUE TITLE
Issue when upgrading from v1.22.3+k3s1 to v1.25.2+k3s1

### ISSUE THREAD

**Issue by tstackhouse** [k3s-io/k3s#6314]
**Environmental Info:**
K3s Version:

k3s version v1.25.2+k3s1 (53c268d8)
go version go1.19.1

Node(s) CPU architecture, OS, and Version: 

Linux node1 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
(All 5 nodes are the same)

Cluster Configuration:
1 leader, 4 nodes

**Describe the bug:**
I have a relatively simple cluster, I've got K3s paired with MetalLB and Longhorn on 5 raspberry pis, and having recently upgraded my nodes (one at a time) from v1.22.3+k3s1 to v1.25.2+k3s1, I've ran into a situation where my cluster is mostly fine, but a couple operations are failing with similar symptoms as #6273, which are only affecting a couple longhorn pods that are tring to access certain cluster details:

```
W1021 14:48:10.263390       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CronJob: the server could not find the requested resource
E1021 14:48:10.263481       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CronJob: failed to list *v1beta1.CronJob: the server could not find the requested resource
W1021 14:48:43.648429       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
E1021 14:48:43.648515       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.PodDisruptionBudget: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
```

Everything seemed fine until I ran the upgrade on my leader node, which was where the 2 pods first started failing, bouncing the pods to have them recreated didn't help.

**Steps To Reproduce:**
- Installed K3s via k3s-ansible
- Configure MetalLB and Longhorn with default configurations
- Upgraded K3s via k3s-ansible

**Expected behavior:**
Cluster upgrades successfully and all pods resume normal operation.

**Actual behavior:**
Cluster is mostly intact, but due to the failure of the longhorn pods to start, one deployment that uses a longhorn volume is unable to start.

**Additional context / logs:**
This issue also appears to affect OpenLens, which is throwing warnings when attempting to view CronJobs, PDBs, HPAs, and a few other resources, however `kubectl` shows them just fine:

![image](https://user-images.githubusercontent.com/149909/197226972-18001864-2794-4e33-8128-d0b50264f326.png)

**Comment by brandond** [comment]
Did you upgrade directly from 1.22 to 1.25, or did you step through the intermediate minors so that resources could be properly migrated to their new storage versions?

Have you confirmed that all of your components actually support Kubernetes 1.25?

**Comment by tstackhouse** [comment]
I directly upgraded to 1.25 via the Ansible role, I was unaware that I should have done any kind of incremental upgrade, rather than simply updating to the latest version.  Did I end up hosing myself by just bumping directly to 1.25?

As far as I'm aware Longhorn supports k8s 1.25, I don't see anything that indicates that it doesn't support the latest version.

I wanted to upgrade because I was experiencing the issue noted in #3517 with my logs growing to many gigs with those hugetlb errors.  Looking at #6273 I didn't see anything that stood out in the manifests on my nodes.

**Comment by brandond** [comment]
> I directly upgraded to 1.25 via the Ansible role, I was unaware that I should have done any kind of incremental upgrade

Don't do that. See https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

> Did I end up hosing myself by just bumping directly to 1.25?

It is certainly possible, hard to say for sure. I would check the apiserver logs following the upgrade. This may be the cause of some of your resources not being found though - you've jumped over the migration period for some of the resources changing API versions.

> As far as I'm aware Longhorn supports k8s 1.25

I wouldn't make any assumptions. Note that https://github.com/longhorn/longhorn/releases/tag/v1.3.2 for example says:
> Please ensure the Kubernetes cluster is >= v1.18 and <= v1.24 before upgrading to Longhorn v1.3.2 from v1.2.x or v1.3.x.

**Comment by tstackhouse** [comment]
> Don't do that. See https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

That's good to know.  It's not like docker or other pacakge-manager type things, like `apt`. Wish I knew it a little sooner :smile: 

> It is certainly possible, hard to say for sure. I would check the apiserver logs following the upgrade. This may be the cause of some of your resources not being found though - you've jumped over the migration period for some of the resources changing API versions.

I don't even see a kube-apiserver pod in my cluster, in any namespace...

> I wouldn't make any assumptions. Note that https://github.com/longhorn/longhorn/releases/tag/v1.3.2 for example says:
> 
> > Please ensure the Kubernetes cluster is >= v1.18 and <= v1.24 before upgrading to Longhorn v1.3.2 from v1.2.x or v1.3.x.

Well that's a fun one. The info I had found at first glance was very basic, just on the order of k8s > 1.10 or something (which of course I can't find again... I guess it might end poorly if I set the version back to 1.22 in the ansible role and did another rollout to try and reset the stage to do a 1.22 -> 1.23 -> 1.24.

**Comment by brandond** [comment]
> I don't even see a kube-apiserver pod in my cluster, in any namespace...

K3s doesn't run the control-plane in pods. Everything runs together in the main K3s process, so you can substitute the individual component versions for the K3s server version.

> I guess it might end poorly if I set the version back to 1.22 in the ansible role and did another rollout to try and reset the stage to do a 1.22 -> 1.23 -> 1.24.

Yeah, downgrading at this point would probably hose you worse than you currently are.

**Comment by tstackhouse** [comment]
Ok, I'm going through `journalctl -u k3s.service` and I'm seeing a ton of these messages:

```
654 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"acf25bc8-9967-4fed-be1f-4d99b30ab6f3\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=2
```

I did find the first startup after installing the upgrade, though I'm not sure exactly what I'm looking for, I took the logs from when the service was upgraded until I rebooted the node and put them here: http://sprunge.us/Rq6imR

**Comment by brandond** [comment]
This sounds a lot like https://github.com/kubernetes/kubernetes/issues/105536. This will be disruptive, but you might be able to recover from it by running k3s-killall.sh and then manually cleaning up the leftover files in`/var/lib/kubelet/pods/`.

**Comment by tstackhouse** [comment]
I'm going to look more, but it doesn't seem like my nodes have that script, but I do see it mentioned in the documentation here: https://docs.k3s.io/upgrades/killall

I've only got pihole running on my cluster right now, I half wonder if it would make more sense for me to switch my network to different DNS, try to wipe k3s from my nodes, and start fresh (with 1.24).  I've been pretty careful to have all my stuff in manifests, so there's nothing really to lose, except maybe a weeks worth of log data from my pi-hile instances...

**Comment by brandond** [comment]
you should have that script if you used the install script; if you are using ansible it may not create it.

**Comment by tstackhouse** [comment]
Yeah, it looks like the Ansible role just directly downloads the appropriate binary to the nodes and creates the necessary config files: https://github.com/k3s-io/k3s-ansible/blob/master/roles/download/tasks/main.yml

**Comment by tstackhouse** [comment]
Just an update here, I ended up considering my cluster a loss, completely uninstalled k3s via the ansible role, then stood it all back up in relatively short order, though I do need to do more research on configuring MetalLB and making it play nicely with the built-in K3S Traefik controller, but that's outside the scope of this issue, which I'm going to go ahead and close out.
