### ISSUE TITLE
Doesn't start: failed to initialize top level QOS containers: root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by exander77** [k3s-io/k3s#6318]
**Environmental Info:**
K3s Version: 
k3s version v1.24.4+k3s-7d66e419-dirty (7d66e419)

Node(s) CPU architecture, OS, and Version: 
Linux silverrock 5.15.62+truenas #1 SMP Tue Oct 18 16:08:51 UTC 2022 x86_64 GNU/Linux

**Describe the bug:**
Fails to start with:
```
Oct 21 23:17:48 silverrock k3s[1224251]: E1021 23:17:48.988477 1224251 kubelet.go:1378] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"
```
failed to initialize top level QOS containers: root container [kubepods] doesn't exist
**Expected behavior:**
k3s starts

**Actual behavior:**
k3s doesn't startg

[k3s.log](https://github.com/k3s-io/k3s/files/9842583/k3s.log)

On one in like 1000 tries, it actually starts.

**Comment by brandond** [comment]
> `v1.24.4+k3s-7d66e419-dirty`
Are you using K3s from our install script, or the weird truenas build of K3s that they are distributing independently?

**Comment by exander77** [comment]
> > `v1.24.4+k3s-7d66e419-dirty`
> 
> Are you using K3s from our install script, or the weird truenas build of K3s that they are distributing independently?
> 
> If you're using their build of k3s, you should open an issue with the TrueNAS devs for shipping a package that doesn't work no their distro.

Yes, I use the part of TrueNAS. I am not sure if I should blame them, but I saw similar error messages mentioned in the past. Do you think it is a configuration issue on the part of TrueNAS? I am debugging it for two days, I already complained to IX (TrueNAS makers, already opened issue with them, so far nothing interesting from them), but I am starting to think that this is some race condition or something like that within k3s as once in a while it actually starts and everything is ok and I mean everything. Also, the k3s error messages are entirely unhelpful in my opinion, can you at least point me what that message means, and how can I debug why is it happening?

**Comment by cwayne18** [comment]
I'm going to close this out and recommend opening against truenas' fork. If you can reproduce this on vanilla k3s please reopen

**Comment by brandond** [comment]
-> https://ixsystems.atlassian.net/jira/software/c/projects/NAS/issues

**Comment by exander77** [comment]
I tried it with stock binary:
```
k3s.v1.24.4+k3s1 server --flannel-backend=none --disable=traefik,metrics-server,local-storage --disable-kube-proxy --disable-network-policy --disable-cloud-controller --node-name=ix-truenas --docker
```
```
# k3s.v1.24.4+k3s1 -v
k3s.v1.24.4+k3s1 version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1
```
The log is identical, ending with:
```
E1022 16:13:01.838728  511917 kubelet.go:1378] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"
```

**Comment by exander77** [comment]
So, after a whole day of restarting, it finally started.

I am inclined to think this is an upstream issue as a configuration issue then it would never work and if it was a patch in TrueNAS fork, it would work with `v1.24.4+k3s1` version, I downloaded from here.

@brandond Please reopen.

**Comment by brandond** [comment]
Thanks for trying with vanilla K3s. I still believe this is something to do with TrueNAS; it sounds like there is something managing the crgroups that breaks the kubelet if they're both running at the same time. Unfortunately we don't have the cycles to set up a TrueNAS node and track this down; if someone from the TrueNAS side would like to help that would be great.

**Comment by exander77** [comment]
@brandond I actually tracked it down, and it seems to be a kernel issue, but it is covered by completely unhelpful error messages.

I opened two bug reports that are related:
https://github.com/kubernetes/kubernetes/issues/113322
https://github.com/opencontainers/runc/issues/3647

**Comment by brandond** [comment]
So by "kernel issue" do you mean that TrueNAS's kernel is missing support for some critical cgroups?

**Comment by exander77** [comment]
@brandond For some reason cpuset controller fails to set:
```
$ cat /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/kubepods/cgroup.controllers
cpuset cpu io memory hugetlb pids rdma misc 
cpu io memory hugetlb pids rdma misc
```
And cannot be set even manually:
```
$ echo "+cpuset" > cgroup.subtree_control
echo: write error: invalid argument
```
Opencontainers and kubernetes just covers the issue up. I am not entirely sure, if it borked kernel in TrueNAS or if it is some kernel upstream issue with cgroups v2 under some weird conditions.

**Comment by brandond** [comment]
What do you get from `grep cgroup /proc/mounts` ? I'm curious if they're using v1, v2, or hybrid. Hybrid is known not to work well with Kubernetes.

**Comment by exander77** [comment]
> What do you get from `grep cgroup /proc/mounts` ? I'm curious if they're using v1, v2, or hybrid. Hybrid is known not to work well with Kubernetes.

That's v2, my current workaround is `systemd.unified_cgroup_hierarchy=0` which most likely means hybrid as you call it?
```
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/misc cgroup rw,nosuid,nodev,noexec,relatime,misc 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
```

**Comment by exander77** [comment]
Any idea what could cause cpuset to be avaiable but failed to set?

**Comment by brandond** [comment]
Yes, you're running hybrid. You should get rid of that and go to pure v1 or v2. You have the cpuset controller mounted as v1 but the cpu controller v2. That's going to break things.

**Comment by exander77** [comment]
> Yes, you're running hybrid. You should get rid of that and go to pure v1 or v2. You have the cpuset controller mounted as v1 but the cpu controller v2 (the v2 controller picks up everything not specifically claimed by v1). That's going to break things.

I can't go v2 as it doesn't work. I may go v1. Btw, what's the kernel parameter for that? Is pure v1 even supported?

**Comment by exander77** [comment]
I don't have any controllers loaded in v2:

```
$ cat /sys/fs/cgroup/unified/kubepods/cgroup.controllers 
$ cat /sys/fs/cgroup/unified/kubepods/besteffort/cgroup.controllers 
$ cat /sys/fs/cgroup/unified/kubepods/burstable/cgroup.controllers 
```

**Comment by brandond** [comment]
> I can't go v2 as it doesn't work. 

Doesn't work with what? Other stuff in TrueNAS?

> I may go v1. Btw, what's the kernel parameter for that? 

Technically it's a systemd parameter. I'm not sure what version of systemd you're on, or if there are other considerations.

> Is pure v1 even supported?

By containerd and kubernetes, yes.

> I don't have any controllers loaded in v2:

Yes, that's the problem exactly. What do you get from `/sys/fs/cgroup/unified/cgroup.controllers`

**Comment by exander77** [comment]
It cannot set cpuset controller. It is not really to TrueNAS.

Nothing from `/sys/fs/cgroup/unified/cgroup.controllers`.

**Comment by exander77** [comment]
I don't think k3s is using anything from unified (v2) cgroups and everything is running smooth.

I am more interested why kernel can't set cpuset controller on that v2 cgroups.

**Comment by exander77** [comment]
@brandond I don't see that hybrid model issues. And no controllers are actually on cgroups v2. Do you have more info about possible problems?

**Comment by brandond** [comment]
If there are no controllers on cgroupv2, then you shouldn't have this entry in your mounts:
`cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0`

And you wouldn't be missing the`cpu` controller from your cgroup (v1) mounts

**Comment by superseb** [comment]
@exander77 Is it possible to try `v1.24.2+k3s1` and let me know if that returns the same error for you? I am looking into a possible similar issue but still narrowing it down. If that also doesn't work, please try `v1.22.11+k3s2`.

**Comment by exander77** [comment]
@superseb I can test, but issue is not with k3s, k8s has just utterly bad error reporting. If you have similar issue with cgroups then check your loaded controllers.
