### ISSUE TITLE
Installation instructions on the k3s home page result in an error

### ISSUE THREAD

**Issue by mperry2** [k3s-io/k3s#6325]
**Environmental Info:**
K3s Version: 

k3s version v1.24.6+k3s1 (a8e0c66d)
go version go1.18.6

Node(s) CPU architecture, OS, and Version: 

Linux k3test 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

Running the installation instructions presented on the https://k3s.io/ page returns an error at the end. The instructions state:
"This won't take long..."
```
curl -sfL https://get.k3s.io | sh - 
# Check for Ready node, takes ~30 seconds 
k3s kubectl get node 
```

**Steps To Reproduce:**

Run the following commands:
```
curl -sfL https://get.k3s.io | sh - 
# Check for Ready node, takes ~30 seconds 
k3s kubectl get node 
```

**Expected behavior:**

I expected output (or none) from the k3s command without an error message.

**Actual behavior:**

Running the `k3s kubectl get node` command outputs the following:
```
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```

**Additional context / logs:**

Full output below from a new Debian 11 virtual machine.

```
mperry@k3test:~$ curl -sfL https://get.k3s.io | sh - 
[INFO]  Finding release for channel stable
[INFO]  Using v1.24.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.24.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.24.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
mperry@k3test:~$ k3s kubectl get node
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
mperry@k3test:~$
```

**Comment by brandond** [comment]
It is expected that you would install k3s as root, or make the kubeconfig file readable using the --write-kubeconfig-mode flag. Other options are covered here:
https://docs.k3s.io/cluster-access and at https://docs.k3s.io/installation/configuration

**Comment by mperry2** [comment]
I think it would be helpful to add `sudo` before the two commands on the home page and/or state the root expectation explicitly. That way the two-line example on the home page works as expected.

I'm completely new to this program and Kubernetes, so when the install script worked when run under my user account, I thought everything was installed and working properly.

I would have found it helpful if the program exited with a message if it wasn't run as root and left me to try again as the root user. That way there would be no misunderstanding on my part.

**Comment by dereknola** [comment]
Closing as complete https://github.com/k3s-io/k3s-io.github.io/pull/9
