### ISSUE TITLE
k3s vloume plugin 

### ISSUE THREAD

**Issue by jianshanyao** [k3s-io/k3s#6330]
**Environmental Info:**
K3s Version: 
v1.24.1+k3s1

Node(s) CPU architecture, OS, and Version: 
CPU architecture   ---  arm64  
os--openwrt    
os-version   22.03.0-rc6

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 
server:   curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_VERSION=v1.24.1+k3s1  sh -

agent:   k3s agent --token ${TOKEN} --server [https://${SERVER_HOST}:6443]
**Expected behavior:**
mount lvs for pod

**Actual behavior:**
k3s agent log:
time="2022-10-25T05:01:44Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 10.40.1.3:6443: connect: connection timed out"
time="2022-10-25T05:01:44Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.40.1.3:6443: connect: connection timed out"
time="2022-10-25T05:01:49Z" level=info msg="Connecting to proxy" url="wss://10.40.1.3:6443/v1-k3s/connect"
E1025 05:02:39.697289    7461 kubelet.go:1709] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[data65550test], unattached volumes=[nodedb data65550test nodename kube-api-access-h9bfw rootfs node]: timed out waiting for the condition" pod="bxc-65550/bxc-app-1-65550-arm64-100g-zw4hd"
E1025 05:02:39.697857    7461 pod_workers.go:951] "Error syncing pod, skipping" err="unmounted volumes=[data65550test], unattached volumes=[nodedb data65550test nodename kube-api-access-h9bfw rootfs node]: timed out waiting for the condition" pod="bxc-65550/bxc-app-1-65550-arm64-100g-zw4hd" podUID=35d9426f-effe-4297-8557-ab58fe95558c
time="2022-10-25T05:03:58Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 10.40.1.3:6443: connect: connection timed out"
time="2022-10-25T05:03:58Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.40.1.3:6443: connect: connection timed out"
time="2022-10-25T05:04:03Z" level=info msg="Connecting to proxy" url="wss://10.40.1.3:6443/v1-k3s/connect"
E1025 05:04:56.697588    7461 kubelet.go:1709] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[data65550test], unattached volumes=[nodename kube-api-access-h9bfw rootfs node nodedb data65550test]: timed out waiting for the condition" pod="bxc-65550/bxc-app-1-65550-arm64-100g-zw4hd"
E1025 05:04:56.698213    7461 pod_workers.go:951] "Error syncing pod, skipping" err="unmounted volumes=[data65550test], unattached volumes=[nodename kube-api-access-h9bfw rootfs node nodedb data65550test]: timed out waiting for the condition" pod="bxc-65550/bxc-app-1-65550-arm64-100g-zw4hd" podUID=35d9426f-effe-4297-8557-ab58fe95558c
W1025 05:06:09.920535    7461 sysinfo.go:203] Nodes topology is not available, providing CPU topology
E1025 05:06:09.926732    7461 info.go:114] Failed to get system UUID: open /etc/machine-id: no such file or directory
W1025 05:06:09.926990    7461 machine.go:65] Cannot read vendor id correctly, set empty.
W1025 05:06:09.933679    7461 info.go:53] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
E1025 05:06:10.357319    7461 network_policy_controller.go:283] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 2 (iptables-restore v1.8.7 (legacy): Couldn't load match `physdev':No such file or directory

**Additional context / logs:**
ds   logs
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           6m12s                default-scheduler        Successfully assigned bxc-65550/bxc-app-1-65550-arm64-100g-zw4hd to openwrt-test-taiyuan
  Warning  FailedMount         4m10s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[data65550test], unattached volumes=[rootfs node nodedb data65550test nodename kube-api-access-h9bfw]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m (x10 over 6m12s)  attachdetach-controller  AttachVolume.Attach failed for volume "data65550test" : invalid character 'V' looking for beginning of value
  Warning  FailedMount         116s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[data65550test], unattached volumes=[nodename kube-api-access-h9bfw rootfs node nodedb data65550test]: timed out waiting for the condition

**Comment by jianshanyao** [comment]
agent :
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/bonuscloud.io~lvm/lvm

[root@OpenWrt-test-taiyuan:12:02 PM /usr/libexec/kubernetes/kubelet-plugins/volume/exec/bonuscloud.io~lvm] # sh lvm getvolumename '{"kubernetes.io/fsType":"ext4","kubernetes.io/pvOrVolumeName":"data65550test","kubernetes.io/readwrite":"rw","size":"100g","volumeID":"bonusvol65550v01","volumegroup":"bonusvolgroup"}'
{"status": "Success", "volumeName": "data65550test"}

and I don't know k3s apiserver want receive what kind of return information for getvolumename ,so  daemenset events  always  show  AttachVolume.Attach failed for volume "data65550test" : invalid character 'V' looking for beginning of value,  i am so  confused

**Comment by brandond** [comment]
There are a LOT of different errors here

* `time="2022-10-25T05:03:58Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.40.1.3:6443: connect: connection timed out"`
  This would indicate that the node can't connect to the server. What is that IP address, and do you have any idea why this node can't connect to it?
* `E1025 05:06:10.357319 7461 network_policy_controller.go:283] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 2 (iptables-restore v1.8.7 (legacy): Couldn't load match `physdev':No such file or directory`
  You seem to be missing some kernel modules on this host. The `physdev` match is not available, but is a required module for enforcing network policies.
* `AttachVolume.Attach failed for volume "data65550test" : invalid character 'V' looking for beginning of value`
  I would have to defer to the bonuscloud storage provider - have you opened an issue with their team yet? I would also check to see if they have a modern CSI plugin. Kubelet volume plugins have been deprecated for quite a while.

**Comment by jianshanyao** [comment]
> There are a LOT of different errors here
> 
> * `time="2022-10-25T05:03:58Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.40.1.3:6443: connect: connection timed out"`
>   This would indicate that the node can't connect to the server. What is that IP address, and do you have any idea why this node can't connect to it?
> * `E1025 05:06:10.357319 7461 network_policy_controller.go:283] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 2 (iptables-restore v1.8.7 (legacy): Couldn't load match `physdev':No such file or directory`You seem to be missing some kernel modules on this host. The`physdev` match is not available, but is a required module for enforcing network policies.
> * `AttachVolume.Attach failed for volume "data65550test" : invalid character 'V' looking for beginning of value`
>   I would have to defer to the bonuscloud storage provider - have you opened an issue with their team yet? I would also check to see if they have a modern CSI plugin. Kubelet volume plugins have been deprecated for quite a while.

Thank you very much, and i think the first and the second is independent the third。
The bonuscloud just a vg name,our disk is use lvm -> pv -> vg -> lvs to mount.I guess your mean is this k3s version is not support to lvm plugin?

**Comment by brandond** [comment]
I don't know,  but I don't believe we've ever tested this bonuscloud.io driver that you appear to be using. Where did you get it from? Why are you even using a volume plugin instead of a CSI driver? As I mentioned earlier, they've been deprecated for a while.

**Comment by jianshanyao** [comment]
Thank you very much for the information you provided me.

Well, our company has been using the k8s lvm plug-in to format the hard disk for node nodes, create vg, create lv, and hang the lv to the target directory for use by the business container. Now we expect to use k3s to complete this process, and continue the previous style to obtain better compatibility, so we do not intend to use the updated CSI method. Please tell me which version of k3s I need to use, and whether the server and agent should keep the same version

**Comment by brandond** [comment]
> our company has been using the k8s lvm plug-in
> Please tell me which version of k3s I need to use

Which one? Can you share a link to the source code or documentation?

> we do not intend to use the updated CSI method.

flexvolume plugin drivers will be removed from Kubernetes at some point. You should investigate moving to CSI drivers before that happens. Some options would be:
* https://github.com/metal-stack/csi-driver-lvm
* https://github.com/topolvm/topolvm

> whether the server and agent should keep the same version

Yes, servers and agents should always run the same version of Kubernetes, except briefly during upgrades.

**Comment by jianshanyao** [comment]
I must say, thank you very much for your reply.
At present, the k3s version we are using is v1.24.1+k3s1
Since csi driver is a better way, I will go to more research in this area to understand how csi and lvm work together, and what information can be provided in this regard
