### ISSUE TITLE
kubectl get nodes shows issue : - Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Sandeepchouhan05** [k3s-io/k3s#6339]
Hi, 

While creating k3s cluster, i was getting below error (using kubelet-1.24.1-00 same version for Kubeadm & Kubectl) 

The connection to the server 10.0.0.1:6443 was refused - did you specify the right host or port?
 
did some googling and run few commands shows to fix this issue but now another below issue created 

root@nodeone:~# kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
root@nodeone:~# kubectl -n kube-system get pods
The connection to the server 10.0.0.1:6443 was refused - did you specify the right host or port?
root@nodeone:~#

tried to root@nodeone:~# export KUBECONFIG=/etc/kubernetes/kubelet.conf but no solution here.

Please suggests here

**Comment by brandond** [comment]
How did you install k3s? Other than observing the error message, what have you checked so far? Is the k3s-server service running? What do the logs say?

**Comment by Sandeepchouhan05** [comment]
below is k3s server service status 

root@nodeone:~# systemctl status k3s
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-10-26 14:07:57 UTC; 2s ago
       Docs: https://k3s.io
    Process: 9515 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 9517 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 9518 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 9519 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
   Main PID: 9519 (code=exited, status=1/FAILURE)
        CPU: 405ms
root@nodeone:~#

i have installed using 
sudo apt-get install -y kubelet=1.24.1-00 kubeadm=1.24.1-00 kubectl=1.24.1-00

error is 
root@nodeone:~# kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
root@nodeone:~# kubectl -n kube-system get pods
Unable to connect to the server: x509: certificate signed by unknown authority
root@nodeone:~#

**Comment by brandond** [comment]
> i have installed using
  `sudo apt-get install -y kubelet=1.24.1-00 kubeadm=1.24.1-00 kubectl=1.24.1-00`

You have installed multiple Kubernetes distributions on your machine. Don't do that. Clean up your kubeadm-based cluster, remove the other packages, and reinstall k3s.
