### ISSUE TITLE
Update kube-router version and add extra logging

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6344]
**Is your feature request related to a problem? Please describe.**

We are using kube-router 1.5.0 and we should move to 1.5.1. Apart from that, it is hard to track what network policy is dropping packets. This PR fixes that

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VestigeJ** [comment]
@manuelbuil if this is trivial to print out the version in the journalctl logs that would be helpful



##Environment Details
 
*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and Version:*

Linux 5.11.0-1022-aws x86_64 GNU/Linux - Ubuntu 20.04.3 LTS
 
*Cluster Configuration:*
```
NAME                STATUS   ROLES                       AGE   VERSION
ip-1-1-1-248   Ready    control-plane,etcd,master   57m   v1.25.3+k3s-9a9f1f2d 
```
*Config.yaml:*

write-kubeconfig-mode: 644
debug: true
token: coolclouds
selinux: true
cni: cilium
protect-kernel-defaults: true
cluster-init: true
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
node-ip: 1.1.1.248,2000:1f1c:ice:ee48:bdd0:cafe:3e78:3e10
node-external-ip: 14.1.2.17,2000:1f1c:ice:ee48:bdd0:cafe:3e78:3e10

<details>
<summmary><h4> VERIFIED BY SHA265 </h4></summary>
## Replication Steps
 
- Installed k3s:

```
$  COMMIT=9a9f1f2d5eefff13f60fdcb7182149fcb9456f75
$  sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh 
$  sudo journalctl -u k3s | grep -i -e "kube-router" (copy sha256 on image pull)
$  SHAtoMatch=2ae3d78196fed81ec7ddb4581b7fc631bbd955b36063bf017c73c02a2818f6e2
$  echo $SHAtoMatch
$  docker pull cloudnativelabs/kube-router:latest (compare docker install of image output to journalctl sha256)
```

$docker pull cloudnativelabs/kube-router:latest
```
latest: Pulling from cloudnativelabs/kube-router
213ec9aee27d: Pull complete 
a35ea4791be5: Pull complete 
171345e3f30e: Pull complete 
7bbeffb65b8e: Pull complete 
b650b5fbbdc0: Pull complete 
aef1967c043e: Pull complete 
f77c99d8d1f8: Pull complete 
4705f0e2ba79: Pull complete 
d2e1ceeeb3ce: Pull complete 
fb499ebb0ea6: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:2ae3d78196fed81ec7ddb4581b7fc631bbd955b36063bf017c73c02a2818f6e2
Status: Downloaded newer image for cloudnativelabs/kube-router:latest
docker.io/cloudnativelabs/kube-router:latest
```

</details>
