### ISSUE TITLE
Validate SLE Micro 5.3

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#6352]
Please validate k3s on SLE Micro 5.3 to be included in the support matrix

**Comment by ShylajaDevadiga** [comment]
Validation for SLE Micro 5.3 is complete. 
- Conformance test
- SUC upgrade
- Install Rancher as local management cluster on v1.24.7+k3s1 and v1.23.13_k3s1
- Perform a cluster-reset-snapshot-restore
- Arm64 validation
- Secret Encryption
- Certification Rotation
- Docker CRI
