### ISSUE TITLE
master can‘t join server

### ISSUE THREAD

**Issue by tomiaa1926** [k3s-io/k3s#6365]
env：
 vagrant ubuntu

The second master joins the first one,Firewall is also off state

> [INFO] systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details.
time="2022-10-27T06:13:18Z" level=error msg="Process exited with status 1: Created symlink from /etc/systemd/system/multi-user.target.wants/k3s.service to /etc/systemd/system/k3s.service.\nJob for k3s.service failed because the control process exited with error code. See \"systemctl status k3s.service\" and \"journalctl -xe\" for details.\n"
time="2022-10-27T06:13:18Z" level=info msg="[native] executing rollback logic..."

sys.log :

> Oct 27 14:13:13 master2 k3s[1981]: time="2022-10-27T14:13:13+08:00" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Oct 27 14:13:13 master2 k3s[1981]: time="2022-10-27T14:13:13+08:00" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/2ef87ff954adbb390309ce4dc07500f29c319f84feec1719bfb5059c8808ec6a"
Oct 27 14:13:17 master2 k3s[1981]: time="2022-10-27T14:13:17+08:00" level=info msg="Starting k3s v1.25.3+k3s1 (f2585c16)"
Oct 27 14:13:17 master2 k3s[1981]: time="2022-10-27T14:13:17+08:00" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
Oct 27 14:13:17 master2 k3s[1981]: time="2022-10-27T14:13:17+08:00" level=info msg="Managed etcd cluster not yet initialized"
Oct 27 14:13:17 master2 k3s[1981]: time="2022-10-27T14:13:17+08:00" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
Oct 27 14:13:17 master2 k3s[1981]: time="2022-10-27T14:13:17+08:00" level=fatal msg="starting kubernetes: preparing server: https://192.168.2.201:6443/v1-k3s/server-bootstrap: 400 Bad Request"
Oct 27 14:13:17 master2 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE

**Comment by brandond** [comment]
> `https://192.168.2.201:6443/v1-k3s/server-bootstrap: 400 Bad Request"`

What does the log on the other server say when you attempt to join the new server? I suspect you'll find a nice message in its log telling you that it wasn't started with `--cluster-init`, in which case you're not using etcd and cannot add additional servers. Please see https://docs.k3s.io/installation/ha-embedded#existing-clusters

**Comment by tomiaa1926** [comment]
Thank you so much for your reply, I found a tip in master1,
`Received HTTP bootstrap request from 192.168.2.203:48768, but embedded etcd is not enabled`
:stuck_out_tongue_winking_eye:I'm actually using a third-party tool to build a cluster automatically, it's called autoK3
