### ISSUE TITLE
Print kube-router version to logs

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6372]
**Is your feature request related to a problem? Please describe.**
I want to know what version of kube-router k3s is using

**Describe the solution you'd like**
Something like this printed to the logs:
```
I1027 21:13:59.261477      53 network_policy_controller.go:162] Starting network policy controller v1.5.1-k3s1
```

**Describe alternatives you've considered**
Keep checking go.mod to figure out what version we're using

**Additional context**
* https://github.com/k3s-io/k3s/issues/6344

**Comment by brandond** [comment]
cc @manuelbuil

**Comment by est-suse** [comment]
Validated on Version 1.25 commit https://github.com/k3s-io/k3s/commit/e21208870c3b287a31a89f341bde2a7d1c996c7a

Node(s) CPU architecture, OS, and Version:

```
Linux ip-172-31-40-46 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

![image](https://user-images.githubusercontent.com/106194120/200922970-943e46bf-50c5-40cf-9912-29a3b7892e49.png)
