### ISSUE TITLE
cli: embed `check-config` command

### ISSUE THREAD

**Issue by bukowa** [k3s-io/k3s#6373]
**Is your feature request related to a problem? Please describe.**
While installing k3s as alpine package from https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/k3s
CLI is missing `check-config` command.

**Describe the solution you'd like**

`check-config` could be embed to form static cli binary

**Describe alternatives you've considered**

**Additional context**

````bash
alpine:/usr/local/bin# diff ./k3s.test.diff ./k3s.test.diff2
8c8
<    v1.25.3+k3s1 (AlpineLinux)
---
>    v1.25.3+k3s1 (f2585c16)
15a16
>    check-config     Run config check
````

**Comment by brandond** [comment]
We do embed the command in the k3s binary. This sounds like an issue with the Alpine build of k3s; I would open an issue over there. That is a community package, not one we maintain, and it does not use our official binaries.
