### ISSUE TITLE
k3s applying ipv6 address on nodes

### ISSUE THREAD

**Issue by ibrokethecloud** [k3s-io/k3s#6374]
**Environmental Info:**
K3s Version: 

v1.21.7+k3s1
v1.24.7+k3s1

Node(s) CPU architecture, OS, and Version: 

Ubuntu
Cluster Configuration:

Single node
**Describe the bug:**

On nodes with ipv6 addresses, k3s does not ignore the ipv6 address for the node. This behaviour has changed since v1.21.7 (not sure of exact version)

As per upstream kubelet docs for node-ip flag

```
 IP  address (or comma-separated dual-stack IP addresses) of the node. If  unset, kubelet will use the node's default IPv4 address, if any, or its  default IPv6 address if it has no IPv4 addresses. You can pass '::' to make it prefer the default IPv6 address rather than the default IPv4 address.
```

In k3s there has been a change to GetHostnameAndIPs in https://github.com/k3s-io/k3s/blob/v1.24.7+k3s1/pkg/util/net.go

The check should not look for ipv6 address when ipv4 is not nil, as this causes the supervisor to lookup ipv6 address and apply the same to the node.

```
	if len(nodeIPs) == 0 {
		hostIP, err := apinet.ChooseHostInterface()
		if err != nil {
			return "", nil, err
		}
		ips = append(ips, hostIP)
		// If IPv6 it's an IPv6 only node
		if hostIP.To4() != nil {
			hostIPv6, err := apinet.ResolveBindAddress(net.IPv6loopback)
			if err == nil && !hostIPv6.Equal(hostIP) {
				ips = append(ips, hostIPv6)
			}
		}
	}
```

The condition should be `hostIP.TO4() == nil`, as a result of this k3s on nodes with ipv6 addresses is setting the node internalIP to ipv6 as well,.

**Steps To Reproduce:**

- Installed K3s: 
On a sample ubuntu node running in libvirt with ipv6 enabled.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:82:42:34 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.214/24 brd 192.168.100.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3117sec preferred_lft 3117sec
    inet6 fd7d:844d:3e17:f3ae::127/128 scope global dynamic noprefixroute 
       valid_lft 85919sec preferred_lft 85919sec
    inet6 fe80::4201:cf96:fe21:65fb/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 92:c7:7a:3a:53:74 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::90c7:7aff:fe3a:5374/64 scope link 
       valid_lft forever preferred_lft forever
```

k3s version 1.21.7
```
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl get nodes -o json | jq .items[].status.addresses
[
  {
    "address": "192.168.100.214",
    "type": "InternalIP"
  },
  {
    "address": "ubuntu-standard-pc-q35-ich9-2009",
    "type": "Hostname"
  }
]
```
k3s version 1.24.7
```
[
  {
    "address": "192.168.100.214",
    "type": "InternalIP"
  },
  {
    "address": "fd7d:844d:3e17:f3ae::127",
    "type": "InternalIP"
  },
  {
    "address": "ubuntu-standard-pc-q35-ich9-2009",
    "type": "Hostname"
  }
]
```
**Expected behavior:**

ipv4 only address should be applied unless the ipv6 address is specified via node-ip flag

**Actual behavior:**

**Additional context / logs:**

This is likely to have unintended consequences for k3s/rke2 upgrades.

We also see the same issue in harvester:  https://github.com/harvester/harvester/issues/2962
This is impacting in place upgrades as well as fresh installs.

**Comment by brandond** [comment]
Ignoring ipv6 is not desired behavior. For a long time the kubelet did not automatically configure ipv6 address and required users to set them manually, but this has not been the case for a while now. I can try to find the specific commit to upstream that changed this, but it is not something unique to k3s.

If ipv6 is causing problems, it should be disabled at the kernel level via sysctls, rather than expecting software to just ignore it.

**Comment by brandond** [comment]
See also:
* https://github.com/kubernetes/kubernetes/issues/111695
* https://github.com/kubernetes/kubernetes/pull/107750
