### ISSUE TITLE
Install test images are Out-of-Date

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#6377]
**Describe the bug:**

- The opensuse 15.3 image used for install testing is now a year old and the repos are getting stale, causing testing failures. We should move to 15.4, it is regularly updated by opensuse. 
- The fedora coreos image used in the install test is [widely out of date ](https://app.vagrantup.com/dhml/boxes/fedora-coreos-34.20210725.3.0-20210813) and there is no replacement. We should move to standard fedora for this test as it get regularly published boxes by the fedora project.

**Comment by rancher-max** [comment]
Closing as we generally do not test CI changes (CI tests them itself 🙂 )
