### ISSUE TITLE
helm-install-* pod remains in pending when installing k3s with `--node-taint CriticalAddonsOnly=true:NoExecute`

### ISSUE THREAD

**Issue by afloarea** [k3s-io/k3s#6383]
**Environmental Info:**
K3s Version: 

k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.2

Node(s) CPU architecture, OS, and Version: 

[Server] Linux ceno 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

The helm-install-* pods are unable to run when installing k3s with `--node-taint CriticalAddonsOnly=true:NoExecute` to prevent apps from running on server (traefik, core-dns etc. have this toleration but the helm installer pods do not, so they remain in pending)

**Steps To Reproduce:**

- Created `/var/lib/rancher/k3s/serva/manifests/`
- Placed HelmChart (with toleration for  `CriticalAddonsOnly=true:NoExecute`) manifest and traefik HelmChartConfig
- Installed K3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=servicelb --disable local-storage --write-kubeconfig-mode=644" sh -`

**Expected behavior:**

I expect the helm chart to be installed.

**Actual behavior:**

The helm chart is not installed. `helm-install-*` pods remain in pending

**Additional context / logs:**

Trying to set up a cluster with 1 server and N agents. Starting installation on the server with `--node-taint CriticalAddonsOnly=true:NoExecute` to prevent apps from running on server. Also using a HelmChart manifest under `/var/lib/rancher/k3s/server/manifests`, as well as a HelmChartConfig manifest for customizing traefik. Even though traefik has the toleration set up it is not installed because the helm-install pod remains in pending.
It would be nice to know if traefik runs as expected before moving on to setting up additional nodes.

I found a [similar issue reported and fixed for rancher/rk2](https://github.com/rancher/rke2/issues/487)

**Comment by brandond** [comment]
Helm isn't flagged as a bootstrap chart (which would cause the install job to tolerate that taint) because it's not required for the cluster to be baseline functional. Remove the taint or add more nodes.
