### ISSUE TITLE
segmentation fault with v1.25.3+k3s1 on arm64 / PINE A64+

### ISSUE THREAD

**Issue by baichinger** [k3s-io/k3s#6385]
**Environmental Info:**
K3s Version: 
```
% /usr/local/bin/k3s-v1.25.3 -v
k3s-v1.25.3 version v1.25.3+k3s1 (f2585c16)
go version go1.19.2
```

Node(s) CPU architecture, OS, and Version: 
Hardware: [PINE A64+ SBC](https://www.pine64.org/devices/single-board-computers/pine-a64/) running Arch Linux ARM
```
% uname -a
Linux pine64 5.19.8-1-aarch64-ARCH #1 SMP PREEMPT Thu Sep 8 18:20:33 MDT 2022 aarch64 GNU/Linux
```
Cluster Configuration:
* 1 server (pine64)
* 1 agent (rpi4)

**Describe the bug:**
Running v1.25.3+k3s1 causes a segmentation fault:
```
% /usr/local/bin/k3s-v1.25.3 kubectl version
[1]    110003 segmentation fault  /usr/local/bin/k3s-v1.25.3 kubectl version
% /usr/local/bin/k3s-v1.25.3 ctr    
[1]    110086 segmentation fault  /usr/local/bin/k3s-v1.25.3 ctr
```

v1.25.2+k3s1 worked without issues.

**Comment by brandond** [comment]
Do you see the same crash on the Pi, or does this only affect the Pine64 board?

I suspect this is going to be a golang bug, as we have not changed anything about how we build k3s between the two releases.

**Comment by baichinger** [comment]
v1.25.3+k3s1 runs fine on the Pi.

**Comment by brandond** [comment]
Can you get a core dump from the k3s process when it crashes?

**Comment by baichinger** [comment]
It seems something got wrong when k3s unpacked its content to `/var/lib/rancher/k3s/data/48f93e534af9689a3f627296d5e208546e2d71a04a34d713e2eb39ae05e6fd77`. There where a couple (e.g. check-config) of _data_ files in the bin directory. After removing the directory, v1.25.3+k3s1 runs without issues on the Pine64.
