### ISSUE TITLE
Add check to avoid wrong flannel-external-ip configs

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6402]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

It is possible today to deploy `flannel-external-ip: true` even if the user has not defined a `node-external-ip`. As far as I know, this config is wrong because flannel-external-ip requires an external-ip to be defined.

Besides, it is not recommended to use an unencrypted flannel-backend when using this feature because the traffic is likely to travel across the internet and thus anyone could easily snoop

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by bguzman-3pillar** [comment]
### Validated on commit e2120887
```
$ k3s -v
k3s version v1.25.3+k3s-e2120887 (e2120887)
go version go1.19.2
```
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
# Test 1:
flannel-external-ip: true

# Test 2
flannel-external-ip: true
node-external-ip: xx.xx.xxx.xxx
```
 
## Testing Steps

- First scenario: Deploy k3s with `flannel-external-ip: true` and no `node-external-ip`. The deployment should fail.


1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=e21208870c3b287a31a89f341bde2a7d1c996c7a INSTALL_K3S_EXEC="server" sh -`
3. Run `journalctl -u k3s | grep flannel` to check the warning message `Server has flannel-external-ip flag set but this node does not set node-external-ip. Flannel will use internal address when connecting to this node.`
 
- Second scenario: 

1. Using the 2 config.yaml file
2. Install K3S `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=e21208870c3b287a31a89f341bde2a7d1c996c7a INSTALL_K3S_EXEC="server" sh -`
3. Look for this msg: `"Flannel is using external addresses with an insecure backend: vxlan. Please consider using an encrypting flannel backend."`

   

**Validation Results:**
- Result test 1:

```
$ journalctl -u k3s |grep flannel
Nov 09 21:06:22 ip-172-31-36-219 k3s[1624]: time="2022-11-09T21:06:22Z" level=warning msg="Server has flannel-external-ip flag set but this node does not set node-external-ip. Flannel will use internal address when connecting to this node."
```

- Result test 2:
```
$ journalctl -eu k3s | grep flannel
Nov 09 21:42:51 ip-172-31-36-219 k3s[5863]: time="2022-11-09T21:42:51Z" level=warning msg="Flannel is using external addresses with an insecure backend: vxlan. Please consider using an encrypting flannel backend."
```
