### ISSUE TITLE
[Release 1.23] Update Flannel version to 0.20.1

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#6416]
Backport for #6387

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id 2ac863c36b1747065949979a7df5a6581cb58f05 on release-1.23 branch
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04

*Cluster Configuration:*
Multi node with default config

 ## Steps to reproduce the issue  and validate the fix
1. Install k3s
2. Verify flannel version
3. Run basic networking checks including clusterip, nodeport, loadbalancer, ingress checks

**To validate:**
Flannel version is updated
Networking checks have passed
```
$ k3s -v
k3s version v1.23.13+k3s-2ac863c3 (2ac863c3)
go version go1.17.13

$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.20.1-k3s1.23 (linux/amd64) commit 2ac863c36b1747065949979a7df5a6581cb58f05 built on 2022-11-04T21:29:40Z
```
