### ISSUE TITLE
[Release 1.23] Print kube-router version to logs

### ISSUE THREAD

**Issue by thomasferrandiz** [k3s-io/k3s#6437]
Backport of https://github.com/k3s-io/k3s/issues/6372

**Comment by est-suse** [comment]
Validated on Version 1.23 commit 2ac863c36b1747065949979a7df5a6581cb58f05

Environment Details
Infrastructure

Cloud [x]
Hosted
Node(s) CPU architecture, OS, and Version:

```
1 server
```
