### ISSUE TITLE
Cannot disable servicelb in cluster, reinstalls randomly

### ISSUE THREAD

**Issue by vavallee** [k3s-io/k3s#6442]
**Environmental Info:**
K3s Version: 
k3s version v1.23.10+k3s1 (826b9498)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux k8s1 5.15.0-1017-raspi #19-Ubuntu SMP PREEMPT Fri Oct 14 08:22:47 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
and
Linux k8s5i 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
6 node cluster, 3 are raspberry pis, 3 are lenovo intel machines
3 are masters, 3 are agents

**Describe the bug:**
in all of my nodes systemd has --disable traefik --disable servicelb 

When I first set this, I rebooted all the nodes with this option and servicelb pods disappeared. Suddenly about 3 weeks later some of my services were not working properly. When I looked at the pods, all the servicelb pods had started again.

How can I completely disable servicelb? 

**Steps To Reproduce:**
Installed 1 node as master and 2 nodes as agents. Later I added 3 more nodes and installed those as agents. 
A bit later I switched two of those nodes to master with startup like this. I also did an init-cluster on one startup on the first node.

```
ExecStart=/usr/local/bin/k3s \
    server \
        '--server' \
        ' --disable traefik --disable servicelb' \
	'https://192.168.1.151:6443' \
```

- Installed K3s: 

**Expected behavior:**
servicelb not running
**Actual behavior:**
servicelb still starts, seemigly randomly

**Additional context / logs:**

**Comment by brandond** [comment]
Make sure you have the args set properly on all your nodes. Additionally, your arguments are super mangled - you have two --disable flags between the server flag and the server value. The should look something like this:

```
ExecStart=/usr/local/bin/k3s \
    server \
        '--server' \
        'https://192.168.1.151:6443' \
        ' --disable' \
        'traefik' \
        '--disable' \
        'servicelb'
```
or
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--server=https://192.168.1.151:6443' \
        ' --disable=traefik,servicelb'
```

**Comment by vavallee** [comment]
Thank you so much, this has been driving me crazy, and breaking my loadbalancers. it works so far!
