### ISSUE TITLE
Prevent user from joining servers with mismatched secrets-encryption config

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#6448]
**Is your feature request related to a problem? Please describe.**
Current if the leader of a cluster has `secrets-encryption` enabled, other servers can join without that config turned on. This leads to unclear error messages around secrets being "inaccessible" and the joining servers crash looping.

**Describe the solution you'd like**
Prevent servers without `secrets-encryption` from joining clusters with `secrets-encryption` enabled. Provide clear error messages.

**Describe alternatives you've considered**

**Additional context**

**Comment by VestigeJ** [comment]
Validated using COMMIT=b276b58175e914a24b93f56751335b55cd7a60ab

$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh
server 1
$ kgn
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-1-1-1-7   Ready    control-plane,etcd,master   15m   v1.25.3+k3s-b276b581
```

$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_SKIP_ENABLE=true ./install-k3s.sh 

server 2
$ sudo k3s server
```
INFO[0000] Starting k3s v1.25.3+k3s-b276b581 (b276b581) 
INFO[0000] Managed etcd cluster not yet initialized     
WARN[0000] critical configuration mismatched: secrets-encryption 
FATA[0000] starting kubernetes: preparing server: failed to validate server configuration: critical configuration value mismatch between servers
```

server 1
$ get.figs
```
write-kubeconfig-mode: 644
debug: true
token: turkieslurking
selinux: true
cni: cilium
protect-kernel-defaults: true
cluster-init: true
profile: cis-1.6
secrets-encryption: true
```

server 2
$ get.figs
```
write-kubeconfig-mode: 644
selinux: true
protect-kernel-defaults: true
profile: cis-1.6
server: https://3.128.120.6:6443
token: turkieslurking
```
