### ISSUE TITLE
store node-password in db when using external datastore

### ISSUE THREAD

**Issue by aberfeldy** [k3s-io/k3s#6455]
**Is your feature request related to a problem? Please describe.**
I'm trying out a diskless kubernetes approach with k3s on flatcar for a team.
In this build we can just reboot the node and it gets its updates and configs through an iPXE boot. 
With that approach we could ship a tested, hardened and versioned OS together with a k3s binary and could just replace a node in case of errors or updates (unlike performing e.g. apt update and upgrade on each node).

So far I'm able to spawn a cluster and use postgres as external datastore so that the cluster config doesn't get lost on reboot.

But once I reboot a node, it can't join the cluster again, printing a message similar to this:
```
Nov 07 10:01:05 static.xxx.xxx.xxx.xxx.your.dns.could.be.here k3s[1057]: time="2022-11-07T10:01:05Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"
```

Since everything on the node only exists in memory everything is gone after a reboot (this is intended, due to reasons). But that means that the hash inside the node secret `static.xxx.xxx.xxx.xxx.your.dns.could.be.here.node-password.k3s` in kubernetes and the content of `/etc/rancher/node/password` on the `static.xxx.xxx.xxx.xxx.your.dns.could.be.here` node don't match anymore. Fetching the node-pw from the external-db could solve the issue.

**Describe the solution you'd like**
By using an external datastore, I'd like to move configs like `node-password` into that datastore as well. This way I could run k3s agents on an ephemeral node without having to `kubectl delete node [...]` before a reboot. So far reading through the docs I couldn't find a way to achieve that, without discarding the diskless approach.

**Describe alternatives you've considered**
The alternative would be to refrain from using a diskless OS in memory and write everything onto a disk.

**Comment by brandond** [comment]
> Fetching the node-pw from the external-db could solve the issue.

If you're going to treat the nodes as disposable and not retain ANY data on reboot, you should either:
* Coordinate operations such that you delete the node from Kubernetes when you reboot it, which will ensure that both the node password and any pod scheduled to that node are deleted from the cluster.
* Use the [`--with-node-id`](https://docs.k3s.io/reference/agent-config#node) flag, which will automatically append a unique ID to the end of the node name.

If you are using diskless/ephemeral nodes but actually do want some node-specific data to persist across reboots, that seems like a system configuration issue, and not something that needs to be solved by K3s.

**Comment by aberfeldy** [comment]
the coordination is not the problem, using e.g. kured oder FLUO the node is drained before reboot anyway.
Eventually I don't want to persist anything on the node (that's why we tried out a diskless OS),  just providing the agent configuration with config flags. The idea is to have a bunch of dumb worker nodes which we could just power on/off whenever we need them. 
Maybe I don't yet understand what the node-pw is and what it's used for if I provide an agent token anyway. 
Will try the approach to kubectl delete the node before a reboot.

**Comment by brandond** [comment]
We're not currently planning on changing how node passwords work. They are an important feature for ensuring node integrity and name uniqueness within a running cluster.
