### ISSUE TITLE
Support Edge Autonomy

### ISSUE THREAD

**Issue by BussanQ** [k3s-io/k3s#6460]
Support Edge Autonomy

**Comment by brandond** [comment]
Would you care to provide a link or any further information on what specifically your looking for?

**Comment by BussanQ** [comment]
> Would you care to provide a link or any further information on what specifically you're looking for?

like [KubeEdge](https://github.com/kubeedge/kubeedge)、[OpenYurt](https://github.com/openyurtio/openyurt)、[SuperEdge](https://github.com/superedge/superedge)

**Comment by brandond** [comment]
Do you have any suggestions on what K3s could change or add to support any of these?

**Comment by brandond** [comment]
We're not planning on bundling any additional components at this time.
