### ISSUE TITLE
support on Loongnix-Server (loong64)

### ISSUE THREAD

**Issue by ysicing** [k3s-io/k3s#6473]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
Can you provide the team with hardware on which to build and test this? It is fairly difficult to support an architecture that we lack hardware for.

**Comment by ysicing** [comment]
I recently got a Loongson machine. What can I do ? how can I provide support ?

**Comment by cwayne18** [comment]
We're not currently planning to add official support to loong64 at this time, we'll certainly continue to evaluate and will re-open this issue if that changes in the future.
