### ISSUE TITLE
"noexec" on "/var" prevents the start of K3s (security profile ANSSI-BP-028 enhanced)

### ISSUE THREAD

**Issue by MrSpoocy** [k3s-io/k3s#6474]
**Environmental Info:**
```
K3s Version: 
k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.2
```

Node(s) CPU architecture, OS, and Version: 
```
Linux kubctl1.local 5.14.0-183.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 31 09:18:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 Server

**Describe the bug:**
When a fresh CentOS 9 server is installed and the security profile [ANSSI-BP-028 (enhanced)](https://github.com/RedHatOfficial/ansible-role-rhel9-anssi_bp28_enhanced) is enabled during the installation. It is not possible to start k3s server. It fail because of the permissions.

```
Nov 09 10:27:20 kubctl1.local k3s[8572]: time="2022-11-09T10:27:20+01:00" level=fatal msg="permission denied"
```

After long tests, we found out that the problem is the `noexec` for `/var` in the `/etc/fstab` from the https://github.com/RedHatOfficial/ansible-role-rhel9-anssi_bp28_enhanced/blob/main/defaults/main.yml#L111 direction.

**Steps To Reproduce:**
- Create a fresh CentOS 9 installation with the security profile "ANSSI-BP-028 (enhanced)" (which requires the partitions to be split).
- Start the installation with `curl -sfL https://get.k3s.io | sh -`
- Start the server with `k3s server`

**Comment by brandond** [comment]
You can change the location that k3s stores its data (including extracted binaries) with the `--data-dir` option, although if you do so you so and are also using selinux, you will need to provide custom selinux policies that apply to wherever you relocate the files to.

We do not plan on changing our default data-dir to prevent writing executables under /var/lib/rancher/k3s.

**Comment by MrSpoocy** [comment]
We have already played around with the `--data-dir` option, but unfortunately we were not able to install to another folder. The documentation also mentions the option only after running the install script.
