### ISSUE TITLE
[HELP] How to specify API version?

### ISSUE THREAD

**Issue by patoarvizu** [k3s-io/k3s#648]
Hi,

Is there a way to specify the API version that the k3s cluster launches with? For example, right now I can easily launch a 1.14 cluster with the default settings, but is there a way to pass a flag or set a parameter to run a 1.11 cluster? Or is there a 1:1 mapping between k3s image and k8s api version? If so, does that mean that to run a specific version of a k8s api I have to build a custom k3s image?

Thanks!

**Comment by erikwilson** [comment]
At the moment the version of k8s is compiled into k3s, where we are vendoring in a modified version of k8s in vendor.conf. If you wanted to use an earlier version of k8s it would require a custom compilation, but some of the features of k3s may depend on certain flags being support in k8s. Additionally it is not possible to swap out an upstream version of k8s, it would need to be our modified k3s version.

**Comment by patoarvizu** [comment]
Alright, that sounds good, thanks for the answer @erikwilson!

**Comment by brandond** [comment]
Closing due to age.
