### ISSUE TITLE
runtime-request-timeout is ignored when pulling images [Docker]

### ISSUE THREAD

**Issue by astingengo** [k3s-io/k3s#6482]
**Environmental Info:**
K3s Version: 
k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.2

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04
8 CPU
8 RAM
Cluster Configuration:
Single server

**Describe the bug:**
This is my k3s service file
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--docker' \
        '--kubelet-arg=runtime-request-timeout=3h' \
```
but still if after 2m my image wasn't pull it will fail with `ImagePullBackOff`

**Comment by brandond** [comment]
Did you check the help for that flag?
> Timeout of all runtime requests except long running request - pull, logs, exec and attach. When timeout exceeded, kubelet will cancel the request, throw out an error and retry later.

This only changes the kubelet's timeout for these operations. Docker itself may still have a lower timeout for the pull that would need to be raised in your docker config .

**Comment by astingengo** [comment]
Hows that? It says pull, logs, exec and attach

**Comment by stavros-k** [comment]
What flag should be used to increase image pull timeout? As I can see it fails if it takes more than 2m

**Comment by astingengo** [comment]
For the moment I unded up using containerd as it will work with it. No solution for Docker engine but for the moment I don't see reasons why to use it anyawy

**Comment by jasonbarbee** [comment]
Same problem here. I'm managing a fleet of mobile k3s edge endpoints on cellular connected internet. I also have to run Nvidia L4T/Jetson GPU images, which requires runtime of nvidia-docker as the backend and not containerd to get access to the gpu hardware and the shared os level libraries.
The 2 minute timeout has been causing problems, as k3s is not able to pull images in time, and the pod ends up in a failed state of ImagePullBackoff.
It would be nice to be able to set a timeout that is realistic for the environment.
