### ISSUE TITLE
rootless k3s: allow configuring the mtu of slirp4netns

### ISSUE THREAD

**Issue by paulcostinean** [k3s-io/k3s#6487]
**Is your feature request related to a problem? Please describe.**

I'm trying to change the mtu of slirp4netns used by k3s when running a mostly default rootless configuration and I don't see any option. This is because I suspect I'm hitting performance issues related to the following https://github.com/rootless-containers/slirp4netns/issues/128
The mtu in use defaults to `65520`

Is this already supported?
**Describe the solution you'd like**

Ideally this would be configurable directly in the `config.yaml` of k3s

**Comment by brandond** [comment]
I would defer to @AkihiroSuda on where this sort of configuration belongs.

**Comment by AkihiroSuda** [comment]
Probably in https://github.com/k3s-io/k3s/blob/f2585c1671b31b4b34bddbb3bf4e7d69662b0821/pkg/daemons/config/types.go#L38 ?

**Comment by brandond** [comment]
Is this just a flag that needs to be passed to the command, or ?

**Comment by paulcostinean** [comment]
I think so - slirp4netns starts with the following parameters:
```
slirp4netns --mtu 65520 -r 3 --disable-host-loopback --cidr 10.41.0.0/16 121584 tap0
```
I think doing just mtu is enough for most people hitting performance issues; maybe `--disable-host-loopback` as a toggle could be interesting. Everything else seems to have sane defaults.

For reference:
```
# slirp4netns --help
Usage: slirp4netns [OPTION]... PID|PATH [TAPNAME]
User-mode networking for unprivileged network namespaces.

-c, --configure          bring up the interface
-e, --exit-fd=FD         specify the FD for terminating slirp4netns
-r, --ready-fd=FD        specify the FD to write to when the network is configured
-m, --mtu=MTU            specify MTU (default=1500, max=65521)
-6, --enable-ipv6        enable IPv6 (experimental)
-a, --api-socket=PATH    specify API socket path
--cidr=CIDR              specify network address CIDR (default=10.0.2.0/24)
--disable-host-loopback  prohibit connecting to 127.0.0.1:* on the host namespace
--netns-type=TYPE        specify network namespace type ([path|pid], default=pid)
--userns-path=PATH       specify user namespace path
--enable-sandbox         create a new mount namespace (and drop all caps except CAP_NET_BIND_SERVICE if running as the root)
--enable-seccomp         enable seccomp to limit syscalls (experimental)
--outbound-addr=IPv4     sets outbound ipv4 address to bound to (experimental)
--outbound-addr6=IPv6    sets outbound ipv6 address to bound to (experimental)
--disable-dns            disables 10.0.2.3 (or configured internal ip) to host dns redirect (experimental)
--macaddress=MAC         specify the MAC address of the TAP (only valid with -c)
--target-type=TYPE       specify the target type ([netns|bess], default=netns)
-h, --help               show this help and exit
-v, --version            show version and exit
```

**Comment by brandond** [comment]
It doesn't look like we're actually setting the MTU, according to the code here we are setting it to 0 which I suspect causes `slirp4netns.NewParentDriver()` to configure it automatically? 

https://github.com/k3s-io/k3s/blob/master/pkg/rootless/rootless.go#L156-L167

**Comment by brandond** [comment]
Check out the PR I just merged. You should be able to use a commit build from the installer once CI is done.

**Comment by VestigeJ** [comment]
Tested slirpnet mtu configuration here at the bottom of the second detail section - https://github.com/k3s-io/k3s/issues/6488#issuecomment-1339946080
