### ISSUE TITLE
Remove windows sourceVip config for kube-proxy

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6499]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

k3s agent config is setting the sourceVip config of kube-proxy. That is wrong because it depends on the CNI plugin's hns overlay network. Setting sourceVip makes more sense in the rke2-windows executor, which is already happening: https://github.com/rancher/rke2/blob/master/pkg/pebinaryexecutor/pebinary.go#L190-L199

**Steps To Reproduce:**

- Installed K3s:

If you use the rke2 windows-calico PR: https://github.com/rancher/rke2/pull/3543, to deploy rke2-windows, you'll notice multiple logs saying that it can't find a network called vxlan0:
```
time="2022-11-14T10:07:38-08:00" level=warning msg="can't find HNS network, retryingvxlan0" error="Network vxlan0 not found"
```

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
This was reverted, so moved back to Working status

**Comment by mdrahman-suse** [comment]
Verified with rke2 master branch commit 8f52bbbb4760922bd7851ff33d2880811c109547.
Observed no errors or warnings such as `level=warning msg="can't find HNS network, retryingvxlan0" error="Network vxlan0 not found"`

```
rke2 -v
rke2.exe version v1.25.4-dev+8f52bbbb (8f52bbbb4760922bd7851ff33d2880811c109547)
go version go1.19.3
``` 
```
time="2022-12-04T05:21:31Z" level=info msg="Generating HNS networks, please wait"
time="2022-12-04T05:21:31Z" level=debug msg="[GET]=>[/networks/] Request : "
time="2022-12-04T05:21:31Z" level=debug msg="Network Response : [{\"ActivityId\":\"49F62917-A5C7-4147-87FB-
...
time="2022-12-04T05:21:31Z" level=debug msg="evaluating if the interface: Ethernet 2 with addresses ...
time="2022-12-04T05:21:31Z" level=info msg="Creating VXLAN network using the vxlanAdapter: Ethernet 2"
time="2022-12-04T05:21:31Z" level=debug msg="hcsshim::HNSNetwork::Create id="
time="2022-12-04T05:21:31Z" level=debug msg="[POST]=>[/networks/] Request : {\"Name\":\"External\",\"Type\":\"Overlay\",\"NetworkAdapterName\":\"Ethernet 2\",\"Subnets\":[{\"AddressPrefix\": ...
...
```
