### ISSUE TITLE
how to get cluster_cidr and service_cidr by kubectl

### ISSUE THREAD

**Issue by hackersean** [k3s-io/k3s#6516]
Is there any place in the cluster configmap to store cidr information？thanks。

**Comment by brandond** [comment]
These are not stored anywhere in a Kubernetes cluster, just as args to the servers. There is ongoing work to inject these sorts of things into a standard resource, but until then there's no good way to check them in a cluster-agnostic way. On k3s at least you can check the node args if they have been overridden, but you still need to know what the defaults are.

**Comment by zeritti** [comment]
The parameters' values are kept within annotation `k3s.io/node-args` attached to the node as seen in e.g. v1.24.8+k3s1.

```
kubectl get node NODE -o jsonpath='{.metadata.annotations}
```
Similarly, the annotation is included in the output of `cluster-info dump`.

**Comment by brandond** [comment]
@zeritti they are only there if you customize the flags; the defaults do not show up in node-args.

**Comment by zeritti** [comment]
> @zeritti they are only there if you customize the flags; the defaults do not show up in node-args.

@brandond Thank you for clarification. I did indeed modify the flags.
