### ISSUE TITLE
error with nvidia-container-runtime enabled: containerd-shim resolves to executable in current directory

### ISSUE THREAD

**Issue by iameli** [k3s-io/k3s#6518]
Pertinent log line:
```
Nov 17 16:36:00 rkv-2022-11-1 k3s[8529]: E1117 16:36:00.803238    8529 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: containerd-shim resolves to executable in current directory (./containerd-shim): unknown" pod="kube-system/metrics-server-5c8978b444-jtkl6"
```

**Environmental Info:**
K3s Version: 
```
# k3s -v
k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.2
```
nvidia-container-runtime version:
```
# apt  show nvidia-container-runtime
Package: nvidia-container-runtime
Version: 3.7.0~rc.1-1
Priority: optional
Section: utils
Maintainer: NVIDIA CORPORATION <cudatools@nvidia.com>
Installed-Size: 21.5 kB
Depends: nvidia-container-toolkit (>= 1.7.0~rc.1-1), nvidia-container-toolkit (<< 2.0.0)
Homepage: https://github.com/NVIDIA/nvidia-container-runtime/wiki
Download-Size: 4,992 B
APT-Manual-Installed: yes
APT-Sources: https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/amd64  Packages
Description: NVIDIA container runtime
 Provides a modified version of runc allowing users to run GPU enabled
 containers.
```

Node(s) CPU architecture, OS, and Version: 
```
# uname -a
Linux rkv-2022-11-1 5.3.0-76-generic #72-Ubuntu SMP Thu Jul 15 10:51:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
One-node cluster with a single server

**Describe the bug:**
Booting up with nvidia-container-runtime enabled results in this error. No Google results for "containerd-shim resolves to executable in current directory" so I figured I'd make this ticket to help people out.
```
Nov 17 16:36:00 rkv-2022-11-1 k3s[8529]: E1117 16:36:00.803238    8529 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: containerd-shim resolves to executable in current directory (./containerd-shim): unknown" pod="kube-system/metrics-server-5c8978b444-jtkl6"
```

**Steps To Reproduce:**

Pretty vanilla k3s installation, but [here's the file I'm putting into `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` to try and enable nvidia stuff] (https://gist.github.com/iameli/6b8fe2b3eedb9c5cb7cfa3f665d3db25).
EDIT: [And here's my k3s.service unit](https://gist.github.com/iameli/4f8e57e9b1b0fd510af1f5ef0480417a)

**Comment by brandond** [comment]
The problem probably comes from the fact that you've not provided a complete path to the `nvidia-container-runtime` in your custom config. You actually shouldn't need to manually modify the containerd config to enable this, see the discussion at https://github.com/k3s-io/k3s/issues/4391#issuecomment-1233314825
