### ISSUE TITLE
[question] How to do the upgrade manually on existing cluster?

### ISSUE THREAD

**Issue by staleks** [k3s-io/k3s#6520]
Hi,
I have HA K3s cluster with 2x k3s-server nodes (config is stored on external MySQL DB node and LoadBalancer is added infront of these 2 server nodes. Both server nodes are with Taint: CriticalAddonsOnly=true:NoExecute). Alongside these 2 k3s-servers I have added 3x k3s-worker/agents.
It was installed some time ago (month or so while K3s version was 1.24.6+k3s). Now I've added 2 more nodes, and these 2 new agents are of version 1.25.3+k3s)
I would like to unify complete cluster to be with the "latest & greatest" K8s version -> 1.25.3+k3s.

I want to this upgrade manually. 
I've checked documentation [here](https://docs.k3s.io/upgrades/manual) 

So far I've figured it out that describe procedure is not the same for k3s-server and k3s-worker node. 
When upgrading k3s-worker node, I have to provide K3S_URL (of server) and K3S_TOKEN and it will work.

Now my questions are: 

1. can you please tell me what I need to do on _**k3s-server-02**_ 
NOTE: this one is installed with following options
```
export K3S_DATASTORE_ENDPOINT="some mysql connection string"
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san <K3S_LB> --token <K3S_TOKEN>
```
2. can you please tell me what I need to do on _**k3s-server-01**_ 

NOTE: this one is installed with following options
```
export K3S_DATASTORE_ENDPOINT="some mysql connection string"
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san <K3S_LB> --cluster-init
```

For the k3s-server-02 do I need to use all the flags?
And what about k3s-server-01, having in mind --cluster-init flag?

Thank You

**Comment by brandond** [comment]
Just re-run the installer with the exact same arguments. If you don't feel comfortable doing that, just download the new k3s binary and replace the current one in /usr/local/bin/k3s, then restart the service.

**Comment by staleks** [comment]
Thank You, Brad. Cheers
