### ISSUE TITLE
package/Dockerfile脚本中缺少"build/out/data.tar.gz"

### ISSUE THREAD

**Issue by limx59** [k3s-io/k3s#653]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by warmchang** [comment]
https://github.com/rancher/k3s/blob/b87dd7c45af3ea05631da6e41ed5ed1eb95dd868/package/Dockerfile#L3

https://github.com/rancher/k3s/blob/b87dd7c45af3ea05631da6e41ed5ed1eb95dd868/package/Dockerfile#L11

So why you say missing "build/out/data.tar.gz" in the package/Dockerfile script?

**Comment by limx59** [comment]
> k3s/package/Dockerfile
>     
>     
>          Line 3
>       in
>       b87dd7c
>     
>     
>     
>     
> 
>         
>           
>            ADD build/out/data.tar.gz /image 
>         
>     
>   
> 
> 
> 
>   
>     
>       k3s/package/Dockerfile
>     
>     
>          Line 11
>       in
>       b87dd7c
>     
>     
>     
>     
> 
>         
>           
>            COPY --from=base /image / 
>         
>     
>   
> 
> 
> So why you say missing "build/out/data.tar.gz" in the package/Dockerfile script?

在编译过程中提示没有找到build/out/data.tar.gz 另外在k3s/package目录下除了Dockerfile没有其他文件夹。那么执行ADD如何将build/out/data.tar.gz 拷贝到镜像目录/image下面呢？

**Comment by yamt** [comment]
build/out/data.tar.gz is generated by previous steps. (scripts/package-cli)
please try the top level Makefile.

**Comment by brandond** [comment]
Closing due to age.
