### ISSUE TITLE
K3s showing wrong log

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6530]
**Environmental Info:**
K3s Version: 

k3s 1.25.4
Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

I haven't configured any externalIP and still I see the warning log:
```
level=warning msg="Flannel is using external addresses with an insecure backend: . Please consider using an encrypting flannel backend."
```

**Steps To Reproduce:**

- Installed K3s: 

Deploy k3s with any backend that is not `ipsec` or `wireguard`

**Expected behavior:**

That log should only appear if there was an externalIP configured

**Actual behavior:**

**Additional context / logs:**

**Comment by VestigeJ** [comment]
Reproduced log using release  VERSION=v1.25.4+k3s1
Validated fix using COMMIT= 614da78e43646dfc5b6fa4bbaab6078da7c18597

    


##Environment Details
COMMIT= 614da78e43646dfc5b6fa4bbaab6078da7c18597
VERSION= v1.25.4+k3s1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux SUSE Linux Enterprise Server 15 SP4
 ```
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE    VERSION
ip-2-3-6-3   Ready    control-plane,etcd,master   2m6s   v1.25.4+k3s-614da78e 
```
*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: epicsalsa
cluster-init: true
flannel-backend: vxlan
```
<details>
<summmary><h4> Reproduction && Validation </h4></summary>



$  curl https://get.k3s.io --output install-k3s.sh
$  sudo chmod +x install-k3s.sh
$  sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$  COMMIT=614da78e43646dfc5b6fa4bbaab6078da7c18597
$  VERSION=v1.25.4+k3s1
$  sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh 
$  sudo journalctl -xeu k3s | grep warning
    *see output log below
$  sudo k3s-killall.sh && sudo k3s-uninstall.sh
$  sudo mkdir -p /etc/rancher/k3s/
$  cp ~/tmp-configs/config.yaml /etc/rancher/k3s/
$  echo $COMMIT
$  sudo cat /etc/rancher/k3s/config.yaml
$  sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh
$  sudo journalctl -xeu k3s | grep warning
$  sudo journalctl -xeu k3s | grep -i -e "insecure backend"
$  sudo journalctl -xeu k3s | grep -i -e "insecure"
$  sudo journalctl -xeu k3s | grep -i -e "backend"

**Results:**
The misleading log entry does not occur in the up to date COMMIT-ID
</details>

 
**Additional context / logs:**
 Reproduction log output
$ sudo journalctl -xeu k3s | grep warning
```
Nov 28 23:55:21 ip-2-3-6-3 k3s[2731]: time="2022-11-28T23:55:21Z" level=warning msg="Flannel is using external addresses with an insecure backend: vxlan. Please consider using an encrypting flannel backend."
```

 Validation log output
```
$ sudo journalctl -xeu k3s | grep -i -e "insecure"
$ sudo journalctl -xeu k3s | grep -i -e "backend"
Nov 29 00:01:48 ip-2-3-6-3 k3s[6007]: time="2022-11-29T00:01:48Z" level=info msg="Handling backend connection request [ip-2-3-6-3]"
Nov 29 00:01:51 ip-2-3-6-3 k3s[6007]: time="2022-11-29T00:01:51Z" level=info msg="Starting flannel with backend vxlan"
Nov 29 00:01:56 ip-2-3-6-3 k3s[6007]: time="2022-11-29T00:01:56Z" level=info msg="Handling backend connection request [ip-2-3-6-3]"
Nov 29 00:02:06 ip-2-3-6-3 k3s[6007]: time="2022-11-29T00:02:06Z" level=info msg="Running flannel backend."
```
