### ISSUE TITLE
QA ingest kubectl cluster-info

### ISSUE THREAD

**Issue by VestigeJ** [k3s-io/k3s#6537]
The command 'kubectl cluster-info dump' returns a wealth of data that is worth exporting and tracking on successful tests furthermore that data is already structured JSON and therefore should be a great start to process and store in a database. The primary purpose of the database would be to record which operating systems receive tests, which types of clusters, the cluster configuration, health, CNI in use, etc could all be recorded and become a moving matrix of test history.

**Comment by caroline-suse-rancher** [comment]
@VestigeJ are you still currently working this or should we move it back to "Accepted" to be planned?

**Comment by VestigeJ** [comment]
@caroline-suse-rancher I'm currently looking at piggybacking off of kubetest2 which takes advantage of this output by default from it's built-in logging. So yes it's still underway, the initial plan was for me to work on this during hack week but I've been testing releases for three weeks instead.
