### ISSUE TITLE
[Release 1.23] K3s showing wrong log

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#6539]
Backport: https://github.com/k3s-io/k3s/issues/6530

**Comment by VestigeJ** [comment]
Reproduced log using release VERSION=v1.23.14+k3s1  
Validated fix using COMMIT=357f62924a718edc4ada61d09cc78b6606583e9c

    


##Environment Details

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux SUSE Linux Enterprise Server 15 SP4
 ```

*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE    VERSION
ip-2-4-4-106   Ready    control-plane,etcd,master   119s   v1.23.14+k3s-357f6292 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: epicsalsa
cluster-init: true
flannel-backend: vxlan
```
<details>
<summmary><h4> Reproduction && Validation </h4></summary>



$  curl https://get.k3s.io --output install-k3s.sh
$  sudo chmod +x install-k3s.sh
$  sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$  COMMIT=357f62924a718edc4ada61d09cc78b6606583e9c
$  VERSION=v1.23.14+k3s1
$  sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh 
$  sudo journalctl -xeu k3s | grep warning
    *see output log below
$  sudo k3s-killall.sh && sudo k3s-uninstall.sh
$  sudo mkdir -p /etc/rancher/k3s/
$  cp ~/tmp-configs/config.yaml /etc/rancher/k3s/
$  echo $COMMIT
$  sudo cat /etc/rancher/k3s/config.yaml
$  sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh
$  sudo journalctl -xeu k3s | grep warning
$  sudo journalctl -xeu k3s | grep -i -e "insecure backend"
$  sudo journalctl -xeu k3s | grep -i -e "insecure"
$  sudo journalctl -xeu k3s | grep -i -e "backend"

**Results:**
The misleading log entry does not occur in the up to date COMMIT-ID
</details>

 
**Additional context / logs:**
 Reproduction log output
$ sudo journalctl -xeu k3s | grep warning
```
Nov 28 23:55:18 ip-2-4-4-106 k3s[2732]: time="2022-11-28T23:55:18Z" level=warning msg="dynamiclistener [::]:6443: no cached certificate available for preload - deferring certificate load until storage initialization or first client request"
Nov 28 23:55:22 ip-2-4-4-106 k3s[2732]: time="2022-11-28T23:55:22Z" level=warning msg="Flannel is using external addresses with an insecure backend: vxlan. Please consider using an encrypting flannel backend."
Nov 28 23:55:22 ip-2-4-4-106 k3s[2748]: time="2022-11-28T23:55:22.369443417Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Nov 28 23:55:22 ip-2-4-4-106 k3s[2748]: time="2022-11-28T23:55:22.373206072Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
```

 Validation log output
$ sudo journalctl -xeu k3s | grep warning
```
Nov 29 00:01:38 ip-2-4-4-106 k3s[5980]: time="2022-11-29T00:01:38Z" level=warning msg="dynamiclistener [::]:6443: no cached certificate available for preload - deferring certificate load until storage initialization or first client request"
Nov 29 00:01:42 ip-2-4-4-106 k3s[5994]: time="2022-11-29T00:01:42.238152383Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Nov 29 00:01:42 ip-2-4-4-106 k3s[5994]: time="2022-11-29T00:01:42.242434604Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
```
$ sudo journalctl -xeu k3s | grep insecure
$ sudo journalctl -xeu k3s | grep backend
```
Nov 29 00:01:43 ip-2-4-4-106 k3s[5980]: time="2022-11-29T00:01:43Z" level=info msg="Handling backend connection request [ip-2-4-4-106]"
Nov 29 00:01:52 ip-2-4-4-106 k3s[5980]: time="2022-11-29T00:01:52Z" level=info msg="Handling backend connection request [ip-2-4-4-106]"
Nov 29 00:01:52 ip-2-4-4-106 k3s[5980]: time="2022-11-29T00:01:52Z" level=info msg="Starting flannel with backend vxlan"
Nov 29 00:02:01 ip-2-4-4-106 k3s[5980]: time="2022-11-29T00:02:01Z" level=info msg="Running flannel backend."
```
