### ISSUE TITLE
Validate Rocky Linux 8.7

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#6542]
Validate k3s on Rocky Linux 8.7 to be included in the support matrix

**Comment by mdrahman-suse** [comment]
### Validated Rocky Linux 8.7 with v1.23.14+k3s1, v1.24.8+k3s1, and v1.25.4+k3s1

Testing performed but not limited to:

[] Create HA cluster and run sonobuoy checks
[] SUC Upgrade with workloads
[] Rancher local cluster
[] Rancher imported cluster
[] Docker CRI
[] Network checks
[] Database support
[] Hardened cluster
