### ISSUE TITLE
Validate Oracle Linux 8.7

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#6543]
Validate Oracle Linux 8.7 to be added to support matrix

**Comment by est-suse** [comment]
The Following set of tests have been performed for K3s v1.23, v1.24 and v1.25.


Fresh Installation and sonobuoy execution | Automation | Pass |  
Perform snapshot and restore to a new node | Manual | Pass |  
Validate installation with docker CRI | Automation | Pass |  
Upgrade (From previous patch version to current) |   Pass |  
Upgrade SUC k3s native with workloads | Manual | Pass |  
Rancher Install on K3s cluster |  
Install k3s as local management cluster for Rancher | Manual | Pass
