### ISSUE TITLE
Can not kill containerd-shim processs by  k3s-killall.sh when set --data-dir

### ISSUE THREAD

**Issue by weapons97** [k3s-io/k3s#6553]
**Environmental Info:**
K3s Version: 

k3s version v1.23.7+k3s1 (ec61c667)
go version go1.17.5

Cluster Configuration:

/tmp/qt-core-tmp/20221124160808/install.sh --data-dir=/data/qt-core --cluster-init ....

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s and set data dir like --data-dir=/data/qt-core : 
- Delete k3s by k3s-killall.sh  and  k3s-uninstall.sh

**Expected behavior:**

kill all process use containerd-shim-runc-v2

**Actual behavior:**

can not kill process use containerd-shim-runc-v2 because getshims can't get pid which not start with k3s/data/

**Additional context / logs:**

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/74245876/203728657-3731bd7f-6e4e-4f75-aa5b-970592a2da39.png">

**Comment by jfhenriques** [comment]
Facing same issue right now

**Comment by brandond** [comment]
The uninstall and killall scripts don't know anything about the K3s configuration, and only handle the default install paths for binaries and the data-dir. If you customize these paths, you'll likely need to tweak the uninstall script to work properly on your host.

**Comment by caroline-suse-rancher** [comment]
This is by-design, and we don't currently have this in the plans for implementation
