### ISSUE TITLE
k3s server unable to start with errors like `unexpected ListAndWatch error: failed to list *apiregistration.APIService: couldn't get version/kind;`

### ISSUE THREAD

**Issue by polds** [k3s-io/k3s#6558]
**Environmental Info:**
K3s Version: 
- k3s version v1.24.3+k3s1 (990ba0e8)
- go version go1.18.1

Incase it's relevant, `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

Node(s) CPU architecture, OS, and Version: 

- `Linux ha-k3s-01 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 servers, 2 agents
MySQL Backed

**Describe the bug:**

After a recent failed attempt at installing Mastodon using helm, the k3s agent and server is now failing to start. The controller api kinda works in read only - but the results from reads are incorrect, nodes reporting as ready when I've shut them down, etc. Existing workloads that were already running still continue to run, but any mutating API fails and hangs indefinitely.

The output of `journalctl -xeu k3s.service` is full of logs similar to these that get written several times a second:
```
Nov 24 08:45:22 ha-k3s-03 k3s[915]: time="2022-11-24T08:45:22Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
Nov 24 08:45:23 ha-k3s-03 k3s[915]: W1124 08:45:23.256159     915 reflector.go:324] storage/cacher.go:/apiregistration.k8s.io/apiservices: failed to list *apiregistration.APIService: couldn't get version/kind; json parse error: invalid character 't' after object key:value pair
Nov 24 08:45:23 ha-k3s-03 k3s[915]: E1124 08:45:23.256205     915 cacher.go:425] cacher (*apiregistration.APIService): unexpected ListAndWatch error: failed to list *apiregistration.APIService: couldn't get version/kind; json parse error: invalid character 't' after object key:value pair; reinitializing...
Nov 24 08:45:24 ha-k3s-03 k3s[915]: W1124 08:45:24.260820     915 reflector.go:324] storage/cacher.go:/apiregistration.k8s.io/apiservices: failed to list *apiregistration.APIService: couldn't get version/kind; json parse error: invalid character 't' after object key:value pair
Nov 24 08:45:24 ha-k3s-03 k3s[915]: E1124 08:45:24.260856     915 cacher.go:425] cacher (*apiregistration.APIService): unexpected ListAndWatch error: failed to list *apiregistration.APIService: couldn't get version/kind; json parse error: invalid character 't' after object key:value pair; reinitializing...
```

I'm not entirely sure which API endpoint I can hit to see what the actual response being returned is to see why there's a json parse error.

The k3s-agent log is empty due to the server failing to start.

Probably related, I can no longer query / list deployments:
```
# kubectl get deployments
error: the server doesn't have a resource type "deployments"
```

Component Status reports:
```
# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                        ERROR
scheduler            Unhealthy   Get "https://127.0.0.1:10259/healthz": dial tcp 127.0.0.1:10259: connect: connection refused
controller-manager   Unhealthy   Get "https://127.0.0.1:10257/healthz": dial tcp 127.0.0.1:10257: connect: connection refused
```

**Steps To Reproduce:**

This all started after I attempted (and failed) to install Mastodon using the official helm chart, all of the workloads spun up correctly but were having issues connecting to my Postgres DB, after that the controller started having these issues.

- Installed K3s: 
```
curl -sfL https://get.k3s.io | sh -s - server \
  --disable traefik \
  --disable servicelb \
  --tls-san=ha-k3s.example.com \
  --flannel-iface tailscale0 \
  --flannel-backend vxlan \
  --advertise-address ${TAILSCALE_ADDR?} \
  --datastore-endpoint='mysql://kubernetes:<password>@tcp(<ip>:3306)/kubernetes'
```

Not blaming Mastodon, just starting seeing issues from an otherwise healthy k3s cluster after install:
- Attempt to install Mastodon using https://github.com/mastodon/mastodon/tree/main/chart 
`helm install --namespace mastodon --create-namespace mastodon ./ -f values.yaml`

**Expected behavior:**

- `kubectl delete pod foo -n default` deletes a pod
- `kubectl get deployments -A` lists all deployments in all namespaces

**Actual behavior:**

```
# kubectl delete pod foo
pod "foo" deleted
# hang indefinitely
```

```
# kubectl get deployments -A
error: the server doesn't have a resource type "deployments"
```

**Additional context / logs:**

```
# systemctl status k3s.service
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (start) since Thu 2022-11-24 17:00:01 UTC; 12s ago
       Docs: https://k3s.io
    Process: 2841 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 2843 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 2844 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 2845 (k3s-server)
      Tasks: 27
     Memory: 427.1M
        CPU: 5.949s
     CGroup: /system.slice/k3s.service
             ├─2845 "/usr/local/bin/k3s server" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "">
             └─2861 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd

Nov 24 17:00:10 ha-k3s-01 k3s[2845]: W1124 17:00:10.967020    2845 reflector.go:324] storage/cacher.go:/apiregistration.k8s.io/apiservices: failed to list *apiregistration.APIService: couldn't get versio>
Nov 24 17:00:10 ha-k3s-01 k3s[2845]: E1124 17:00:10.967054    2845 cacher.go:425] cacher (*apiregistration.APIService): unexpected ListAndWatch error: failed to list *apiregistration.APIService: couldn't>
Nov 24 17:00:11 ha-k3s-01 k3s[2845]: time="2022-11-24T17:00:11Z" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Nov 24 17:00:11 ha-k3s-01 k3s[2845]: W1124 17:00:11.972296    2845 reflector.go:324] storage/cacher.go:/apiregistration.k8s.io/apiservices: failed to list *apiregistration.APIService: couldn't get versio>
Nov 24 17:00:11 ha-k3s-01 k3s[2845]: E1124 17:00:11.972321    2845 cacher.go:425] cacher (*apiregistration.APIService): unexpected ListAndWatch error: failed to list *apiregistration.APIService: couldn't>
```

```
# systemctl status k3s-agent
Unit k3s-agent.service could not be found.
```

**Comment by brandond** [comment]
I've also deployed the Mastodon helm chart on K3s so I know it's possible. I've never seen the errors you're getting here though. Can you attach the complete k3s service log? We're there any other errors that preceded this happening?

**Comment by polds** [comment]
Yeah I'm not blaming Mastodon, it just all started happening around the same time. Briefly after deploying the helm chart operations like `kubectl get pods -n mastodon` would fail with an EOF (other namespaces were fine) - once those resolved themselves I started seeing the above errors - but my controller has basically been bricked since trying to deploy.

I don't recall any other blatant issues happening prior to trying to install the Mastodon helm chart.

Attached are the service logs (`journalctl -xeu k3s.service` let me know if you meant a different one) from a reboot.
[k3s.service.log](https://github.com/k3s-io/k3s/files/10087770/k3s.service.log). This is just one of the server nodes, but all of the servers are seeing similar errors and exhibiting similar behaviors.

**Comment by brandond** [comment]
I see you're using an external MySQL server. Is it possible that it's returning errors? Or is there some proxy configured in your environment?  The `couldn't get version/kind; json parse error: invalid character 't' after object key:value pair` error really makes it sound like there's an error message somewhere that would be really helpful if we could see, but instead Kubernetes it just complaining about it not being valid JSON.
