### ISSUE TITLE
Installation of Kubernetes.github.io/ingress-nginx results a timeout.

### ISSUE THREAD

**Issue by ocelik94** [k3s-io/k3s#6573]
**Environmental Info:**
K3s Version: 

```
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```

Node(s) CPU architecture, OS, and Version: 

Linux projectoc 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux

Cluster Configuration:

1 Server, Master+Worker

**Describe the bug:**

Following https://www.suse.com/support/kb/doc/?id=000020082 results in a timeout as described in https://github.com/kubernetes/ingress-nginx/issues/9091. 

I have a similiar Issue with Flux2 - "flux reconcile" results in a timeout with kubernetes.github.io/ingress-nginx.

**Steps To Reproduce:**

```
; <<>> DiG 8.18.8 <<>> kubernetes.github.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57937
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 09911d7f2be5f65e (echoed)
;; QUESTION SECTION:
;kubernetes.github.io. IN A

;; ANSWER SECTION:
kubernetes.github.io. 30 IN A 185.199.111.153
kubernetes.github.io. 30 IN A 185.199.109.153
kubernetes.github.io. 30 IN A 185.199.110.153
kubernetes.github.io. 30 IN A 185.199.108.153

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10) (UDP)
;; WHEN: Tue Nov 29 13:10:23 UTC 2022
;; MSG SIZE rcvd: 205

~ # curl -vvv -L https://kubernetes.github.io/ingress-nginx > /dev/null
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Trying 185.199.110.153:443...

Connected to kubernetes.github.io (185.199.110.153) port 443 (#0)

ALPN: offers h2

ALPN: offers http/1.1

CAfile: /etc/ssl/certs/ca-certificates.crt

CApath: none

TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]

TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
0 0 0 0 0 0 0 0 --:--:-- 0:00:10 --:--:-- 0

0 0 0 0 0 0 0 0 --:--:-- 0:00:11 --:--:-- 0

0 0 0 0 0 0 0 0 --:--:-- 0:00:38 --:--:-- 0
```

- Installed K3s: 

**Expected behavior:**

Successfully Download of the index.yaml

**Actual behavior:**

Timeout Error

**Comment by brandond** [comment]
Are you doing this `curl` test from within a pod, or on the node itself? It looks like it's connecting, but then the TLS handshake is failing. This usually indicates that there is a firewall, proxy, or some other device in your network that is interfering with the communication. Do you need to use a proxy, or open up access through a firewall?

**Comment by ocelik94** [comment]
No, no need of proxy. I turned off firewall as the environment is only for testing purpose

**Comment by brandond** [comment]
You didn't answer my question about whether this is happening in a pod, or on the node, but **something** is blocking your access to github. I'm not aware of any issues with K3s itself that would cause your TLS handshake to time out as your test is demonstrating.

**Comment by ocelik94** [comment]
It is happening only in the pod. Sorry forgot to answer your question

**Comment by ocelik94** [comment]
Reinstallation of the k3s installation seems to be the solution. I cannot explain what the issue has been exactly.
