### ISSUE TITLE
k3s not started with --selinux on selinux enabled installs

### ISSUE THREAD

**Issue by Klaas-** [k3s-io/k3s#6584]
**Environmental Info:**
K3s Version: 

k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3

Node(s) CPU architecture, OS, and Version: 

Linux host.tld 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single server

**Describe the bug:**

When installing k3s via install.sh the startup of the systemd service shows the following warning:
`level=warning msg="SELinux is enabled on this host, but k3s has not been started with --selinux - containerd SELinux support is disabled"`

**Steps To Reproduce:**

- Install K3s on RHEL8.7 with selinux enabled
- Observe warning in journal or /var/log/messages

**Expected behavior:**

No Warning

**Actual behavior:**

Warning

**Additional context / logs:**

I'd say the installed k3s works, even without the "--selinux" switch. If this is a real problem you could easily add it via a conditional variable somewhere around here:
https://github.com/k3s-io/k3s/blob/915c7719fec157181b95807c1e09b8e5b8a5a9c4/install.sh#L803

But I am not sure it's actually needed, since k3s seems to run fine with and without the --selinux switch.

**Comment by brandond** [comment]
Yes, you're supposed to add that flag yourself if you want to use it. The installer will set server or agent and pass through CLI flags, but it will not auto-detect flags for you.

**Comment by Klaas-** [comment]
@brandond would you accept a PR to automatically add it on selinux enabled systems? I mean why not automatically add that if it's recommended on selinux enabled systems?
