### ISSUE TITLE
Wrong Containerd version on release page for v1.25.4+k3s1

### ISSUE THREAD

**Issue by kurokobo** [k3s-io/k3s#6610]
**Environmental Info:**
K3s Version: k3s version v1.25.4+k3s1 (0dc63334)

Node(s) CPU architecture, OS, and Version: x86_64, CentOS Stream 8

Cluster Configuration: Single node

**Describe the bug:**

[The release page for K3s v1.25.4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.4%2Bk3s1) shows that the bundled Containerd is `v1.5.13-k3s2`, but actually Containerd `v1.6.8-k3s1` seems to be bundled.

```bash
$ k3s -v
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3

$ sudo $(which k3s) crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.8-k3s1
RuntimeApiVersion:  v1

$ sudo $(which k3s) ctr version
Client:
  Version:  v1.6.8-k3s1
  Revision: 
  Go version: go1.19.3

Server:
  Version:  v1.6.8-k3s1
  Revision: 
  UUID: 18f24dcb-9267-4dc5-9a5c-4e2b31d166be
```

**Steps To Reproduce:**

- Install K3s by `curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644`
- Get versions for k3s and containerd

**Expected behavior:**

The release page shows `v1.6.8-k3s1` as the bundled Containerd version.

**Actual behavior:**

The release page shows `v1.5.13-k3s2` as the bundled Containerd version.

**Additional context / logs:**

Thanks for awesome project, K3s! This is a super minor issue but I'm reporting it just in case.

**Comment by brandond** [comment]
Thanks for the report! Release notes have been updated.
