### ISSUE TITLE
Support for RedHat 9

### ISSUE THREAD

**Issue by djessich** [k3s-io/k3s#6611]
**Is your feature request related to a problem? Please describe.**
Cannot install on RedHat 9 because of missing k3s-common repo (requirement for k3s-selinux).

**Describe the solution you'd like**
Provide support for k3s-common repo.

**Describe alternatives you've considered**
There are no alternatives.

**Comment by brandond** [comment]
Let's track this in https://github.com/k3s-io/k3s/issues/6611
