### ISSUE TITLE
Validate RHEL 9

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6613]
Validate RHEL 9 on k3s to be added to support matrix

**Comment by vwbusguy** [comment]
For what it's worth, we've been running k3s on CentOS Stream 9 since December of 2021 when CS9 first came out.

**Comment by djessich** [comment]
In install script there is no configuration of k3s YUM repository. Only CentOS 7 and CentOS 8 is able to be configured. Question now is: Is the current status that there is no k3s YUM repository for RHEL / CentOS 9 or that the configuration of it is missing in install script? Because of that, this fails the installation, regardless if the binary works or not.

**Comment by vwbusguy** [comment]
> Is the current status that there is no k3s YUM repository for RHEL / CentOS 9 or that the configuration of it is missing in install script? Because of that, this fails the installation for me.

Interesting.  I just installed it using the install script and upgrade it by running it again.  Can you post the specific error you get?

**Comment by brandond** [comment]
We don't handle it properly when adding the k3s-selinux repo. I think that's the only real blocker at the moment.

**Comment by djessich** [comment]
@brandond Exactly!

**Comment by est-suse** [comment]
Validated on K3s v1.23,v1.24,v1.25 and v.1.26, AMI 0560d5a32eec08262

Completed Test:

- SUC upgrade.
- Validate installation with docker CRI 
- Perform snapshot and restore to a new node 

Pending Test:

- Fresh Installation and sonobuoy execution
- Install k3s as local management cluster for Rancher

**Comment by brandond** [comment]
@est-suse did that include selinux support? As mentioned above I don't think we handle the selinux repo properly on EL9.

**Comment by est-suse** [comment]
Hu @brandond, yes It was tested on Hardened cluster
