### ISSUE TITLE
Extreme dockerd cpu & memory usage in some environments

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [k3s-io/k3s#6617]
**Environmental Info:**
K3s Version:
```
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```

Node(s) CPU architecture, OS, and Version: 
`Linux codespaces-c89bc1 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 GNU/Linux`
This is a GitHub codespace using the "premiumLinux" machine type -- 8 cores, 16G RAM

Cluster Configuration: 1 server, 1 agent. Operating a k3d-like setup, but directly on the host for various reasons. Using docker runtime via `--docker` arg to `k3s`.

The docker runtime visible to k3s is a "docker-in-docker" configuration -- codespaces run your environment as a docker container, and the container I'm using has a nested copy of docker running inside it.

**Describe the bug:**

Some part of k3s, or possibly its embedded cri-dockerd, is very frequently making container inspect requests with size details (i.e. `/.../containers/ID/json?size=1` docker API requests) for each container that k3s is running. Not only does it issue these requests frequently, but it doesn't even seem to wait for the response to a prior request before sending another one for the same container!

In the codespace environment, something about disk i/o performance means that `dockerd` cannot respond to these requests as fast as they are issued. As a result, after starting a few pods/containers, `dockerd` consumes all available CPU, and starts seeming to leak memory at between 10 to _100 megabytes a second_.

Stopping k3s allows docker to "catch up" and eventually the CPU usage dies down. It doesn't (quickly) release memory, but I suspect that may be down to the Go runtime and not docker/k3s.

It doesn't take long before docker exhausts all available physical and swap memory, and the Codespace dies.

On some other self-hosted VMs, I can see these same requests coming through to dockerd, but the i/o is fast enough and disk cache plentiful enough that it only creates a mild CPU impact and doesn't cause memory hoarding by docker.

**Steps To Reproduce:**

- Installed K3s: codespaces don't support systemd, so I did this manually:
  - Download k3s release binary from github, install to /usr/local/bin/
- Start k3s: `sudo k3s server --write-kubeconfig-mode 644 --docker --kube-apiserver-arg=service-node-port-range=1024-32767 --tls-san 0.0.0.0`
- Start several pods via deployments
  - The pods I'm using now are mostly internal private code, I'm trying to setup a repro that uses just open source pods.
  - Most of the pods are running nodejs applications, which means they have a very large number of small files. On the order of 250k files for the whole image (including base debian image) is common.
- Wait a couple seconds, monitoring via `top` and `iotop`

**Expected behavior:**
k3s should not cause docker to crash the host

**Actual behavior:**
k3s causes docker to consume cpu & memory without bound

**Additional context / logs:**
Let me know if there's anything I can capture to help diagnose this further.

**Comment by brandond** [comment]
Yes, this is a commonly raised issue with cri-dockerd. I would recommend using containerd if at all possible. There is nothing that requires you to use docker when running inside a docker container; containerd in docker should work just fine.

**Comment by mgabeler-lee-6rs** [comment]
Well, having other parts of our workflow need `docker`, so having containers split between two runtimes gets messy fast, plus we , and the end user workflow for `crictl` is _abysmal_ compared to `docker`, e.g. not supporting "default" auth, volumes, ...

> this is a commonly raised issue with cri-dockerd

I think these are some relevant tickets for this then? Hoping this might help searchability for others :)
* https://github.com/Mirantis/cri-dockerd/issues/135
* https://github.com/rancher/rancher/issues/38816
* https://github.com/rancher/rancher/issues/38018

From trawling through those, it looks like "Native Overlay Diff" is a critical feature for where this is/isn't a major problem. I can confirm on my "happy" workstations/VMs, it is "true", and in the Codespaces it is "false".

Also useful to call out for searchability is this appearing in dockerd's startup logs:
```
level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" storage-driver=overlay2
```

At the very least you've given me a sufficient pointer here to help track down next steps for what I can do to work around this issue, so thank you for that :)
