### ISSUE TITLE
kubeconfig does not exist on server after successful installation

### ISSUE THREAD

**Issue by svdHero** [k3s-io/k3s#6636]
**Environmental Info:**
K3s Version:
- k3s version v1.25.4+k3s1 (0dc63334)
- go version go1.19.3

Node(s) CPU architecture, OS, and Version: 
- Linux k3s-server 5.15.0-56-generic 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Linux k3s-worker-1 5.15.0-56-generic 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 22.04 LTS on both machines

Cluster Configuration:
1 server, 1 agent

**Describe the bug:**
I installed the k3s server following the [quick-start guide](https://docs.k3s.io/quick-start). Both server and worker node are running fine and `kubectl` is working on the server.

Now, I wanted to install `kubectl` locally on my laptop, in order to connect to the cluster server. However, when I check the server, there is no kubeconfig file on the hard disk. The directory `~/.kube` does not exist and the directory `/root/.kube` only contains a subdirectory `cache`, but no file named `config`.

Why is that and where do I get my kubeconfig from? I'm new to Kubernetes.

**Steps To Reproduce:**
Follow the [quick-start guide](https://docs.k3s.io/quick-start) and execute
```bash
curl -sfL https://get.k3s.io | sh -
```
on the server machine. Log in via ssh and check the directories `~/.kube` and `/root/.kube` for config files.

**Expected behavior:**
There should be a file `/root/.kube/config`.

**Actual behavior:**
There is no file `/root/.kube/config`.

**Additional context / logs:**
`kubectl` is only working via `sudo kubectl`, i.e., the command `sudo kubectl get nodes` yields the output
```
NAME           STATUS   ROLES                  AGE   VERSION
k3s-worker-1   Ready    <none>                 44m   v1.25.4+k3s1
k3s-server     Ready    control-plane,master   68m   v1.25.4+k3s1
```
but the command `kubectl get nodes` yields
```
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```
Hence, I assumed that the kubeconfig should be located at `/root/.kube/config`.

Also note that there is no directory `/etc/kubernetes` as some Stackoverflow posts suggest.

**Comment by rbrtbnfgl** [comment]
you should give the right permission to the file.
`sudo chmod +r /etc/rancher/k3s/k3s.yaml` or start K3s with the flag `--write-kubeconfig-mode 644`

**Comment by brandond** [comment]
> There should be a file /root/.kube/config.

Please see the docs at https://docs.k3s.io/cluster-access

**Comment by svdHero** [comment]
@brandond thank you so much. How could I miss that. 🤦🏻‍♂️
I assumed k3s.yaml was just some sort of template file.

Thanks again.
