### ISSUE TITLE
Failed to initialize ipsets command executor due to ipset v7.6: Kernel and userspace incompatible

### ISSUE THREAD

**Issue by kolomparrudi** [k3s-io/k3s#6652]
**Environmental Info:**
K3s Version: 
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3

Node(s) CPU architecture, OS, and Version: 

Linux GIC-MPS-105-204 5.14.21-150400.24.33-default #1 SMP PREEMPT_DYNAMIC Fri Nov 4 13:55:06 UTC 2022 (76cfe60) x86_64 x86_64 x86_64 GNU/Linux

SUSE Linux Enterprise Server 15 SP4 amd64 with all updates

Cluster Configuration:

1 server setup
**Describe the bug:**

Deployed k3s cluster with these INSTALL_K3S_EXEC settings: 
"-docker --disable=servicelb --disable traefik --flannel-backend none --cluster-cidr=192.168.0.0/16 --kubelet-arg=cgroup-driver=systemd --disable local-storage"

Installed: 
calico v3.24.5
multus-daemonset v3.9.2
longhorn v1.4.0-rc1

After this k3s crashed:

```
Dec 14 09:35:00 GIC-MPS-105-204 k3s[22706]: time="2022-12-14T09:35:00+01:00" level=info msg="Using CNI configuration file /etc/cni/net.d/10-calico.conflist"
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: F1214 09:35:02.072850   22706 network_policy_controller.go:611] failed to initialize ipsets command executor due to ipset v7.6: Kernel and usersp
ace incompatible: settype hash:net with revision 7 not supported by userspace.
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: panic: F1214 09:35:02.072850   22706 network_policy_controller.go:611] failed to initialize ipsets command executor due to ipset v7.6: Kernel and
 userspace incompatible: settype hash:net with revision 7 not supported by userspace.
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: goroutine 23335 [running]:
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: k8s.io/klog/v2.(*loggingT).output(0x810cec0, 0x3, 0x0, 0xc006e15420, 0x1, {0x66391df?, 0x1?}, 0xc000508000?, 0x0)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:820 +0x694
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: k8s.io/klog/v2.(*loggingT).printfDepth(0x810cec0, 0x0?, 0x0, {0x0, 0x0}, 0x5785ee0?, {0x4e04c31, 0x36}, {0xc0096d6c10, 0x1, ...})
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:630 +0x1f2
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: k8s.io/klog/v2.(*loggingT).printf(...)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:612
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: k8s.io/klog/v2.Fatalf(...)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:1496
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).cleanupStaleIPSets(0xc00c6e4500?, 0x4cde6f5?)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:611 +0
x2bc
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).fullPolicySync(0xc00c6e4500)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:290 +0
xcc8
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run.func1(0xc00e123680, 0xc0003acc00, 0xc0037a97b8?)
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:193 +0
x88
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]: created by github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run
Dec 14 09:35:02 GIC-MPS-105-204 k3s[22706]:         /go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:177 +0
x2d0
Dec 14 09:35:02 GIC-MPS-105-204 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 14 09:35:02 GIC-MPS-105-204 systemd[1]: k3s.service: Failed with result 'exit-code'.
Dec 14 09:35:07 GIC-MPS-105-204 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1.

```
**Steps To Reproduce:**

- Use SLES15SP4 (or any kernel with ipset version 7 support)
- Install K3s: v1.25.4+k3s1 without flannel
- Install calico v3.24.5

**Expected behavior:**

No crash and ipset version 7 support for kube-router
**Actual behavior:**

kube-router ipset userspace does not support ipset version 7

**Additional context / logs:**

```
ipset -L
Name: cali40all-ipam-pools
Type: hash:net
Revision: 7
Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0x4dadbec4
Size in memory: 504
References: 1
Number of entries: 1
Members:
192.168.0.0/16

Name: cali40masq-ipam-pools
Type: hash:net
Revision: 7
Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0x16912808
Size in memory: 504
References: 1
Number of entries: 1
Members:
192.168.0.0/16

Name: cali40this-host
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0xbddfff30
Size in memory: 480
References: 0
Number of entries: 7
Members:
127.0.0.0
127.0.0.1
172.17.0.1
10.255.0.1
10.120.105.204
10.255.1.1
192.168.142.128

Name: cali40all-vxlan-net
Type: hash:net
Revision: 7
Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0x015c20cb
Size in memory: 456
References: 2
Number of entries: 0
Members:

```

**Comment by brandond** [comment]
Are you able to run the `ipset` command on this host? The error message is coming from the ipset tool, which should be installed on your host. Kube-router does not include a native go interface to ipsets, it just uses the ipset binary from your host. If you don't have ipset installed, k3s provides one, but it may not be compatible with your kernel.

Also, you should disable the k3s kube-router network policy engine if you're going to disable flannel and install calico. Calico has its own policy engine.

**Comment by kolomparrudi** [comment]
ipset is working on host (already sent the output in the Additional context / logs: chapter).
We are using kubernetes network policies, so I can't disable it.

Now I tested it with v1.26.0-rc1+k3s1 and it seems the problem solved in this version.

**Comment by kolomparrudi** [comment]
v1.24.9-rc2+k3s1 version also works fine

**Comment by brandond** [comment]
> >Install K3s: v1.25.4+k3s1 without flannel
> >Install calico v3.24.5
> We are using kubernetes network policies, so I can't disable it.

Calico comes with its own network policy engine, see:
https://projectcalico.docs.tigera.io/security/calico-network-policy

You're currently running two network policy engines. Other than just being unnecessary, this is likely to cause problems at some point.

> v1.24.9-rc2+k3s1 version also works fine

Glad to hear it. If one of the December releases works for you, they all should (with the exception of 1.22). The bundled userspace binaries have been updated in all of them.

**Comment by brandond** [comment]
I suspect that what's actually going on here is that Calico is creating ipsets using the host `ipset` command that the `ipset` bundled with k3s cannot parse because it's slightly too old. I don't think you would have run into this problem if you weren't trying to run multiple network policy engines.
