### ISSUE TITLE
Provide flag to disable k3s builtin node labels or do not override user-supplied values

### ISSUE THREAD

**Issue by chadgeary** [k3s-io/k3s#6665]
**Is your feature request related to a problem? Please describe.**

The aws-ebs-csi-driver checks node labels for capabilities. It expects `node.kubernetes.io/instance-type` to be a known aws ec2 instance type.

If the label is set via startup option:
`--node-label ...`
or post-install:
`kubectl label --overwrite=true node ...`
the user-supplied value appears briefly, then resets to `k3s`

**Describe the solution you'd like**

The ability to disable node labeling by k3s, or to allow user-supplied values to override.

**Describe alternatives you've considered**

I'll also open an issue @ https://github.com/kubernetes-sigs/aws-ebs-csi-driver, though the aws-ebs-csi-driver provides alternatives (pod perform lookup via ec2 instance metadata, a privilege preferred to _not_ grant).

**Additional context**

I was unable to find documentation regarding this behavior. There are other labels also set (e.g. `beta.kubernetes.io/instance-type`).

**Comment by brandond** [comment]
> It expects node.kubernetes.io/instance-type to be a known aws ec2 instance type.

This label is reserved for use by cloud provider (cloud-controller-manager) implementations. In the case of the K3s embedded CCM, our behavior is correct to set this to a value indicating that the node is managed by our cloud provider.

You should either disable the embedded K3s CCM and use the AWS cloud provider, or wait for `aws-ebs-csi-driver` to allow for use with other cloud providers.

**Comment by chadgeary** [comment]
Thank you for the fast response, disabling k3s' built-in ccm stopped the labels being overwritten. :+1:
