### ISSUE TITLE
How to rebuild the first etcd node in k3s

### ISSUE THREAD

**Issue by sunnoy** [k3s-io/k3s#6666]
There is data inconsistency in the cluster data

```bash
etcdctl endpoint status --cluster --write-out=table
+--------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|         ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://172.22.1.5:2379 | 4bdaa13baeb784f0 |   3.5.4 |  108 MB |     false |      false |        22 |   91437534 |           91437534 |        |
| https://172.22.1.6:2379 | ae725785fda5e61e |   3.5.4 |   12 MB |     false |      false |        22 |   91437535 |           91437535 |        |
| https://172.22.1.7:2379 | bc37fe3129da75dc |   3.5.4 |   12 MB |      true |      false |        22 |   91437535 |           91437535 |        |
+--------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

```

I want to rebuild the first node https://172.22.1.5:2379 ，But this node is the first node of cluster initialization with flag --cluster-init ，i want to rebuid etcd data,Clear the data of this node and let him copy data from other nodes

```bash
etcdctl member remove 4bdaa13baeb784f0
# 
initial-cluster-state: ‘existing’”
```
initial-cluster-state: ‘existing’”  How to operate in k3s ？

**Comment by brandond** [comment]
You should not be using etcdctl to try to manage the embedded etcd cluster. K3s manages the cluster itself.

If you want to rejoin this node to an existing cluster, you should:
* stop k3s on this node
* delete the datastore files from `/var/lib/rancher/k3s/server/db`
* On another node, use `kubectl delete node` to delete this node
* Start k3s on this node; it will automatically rejoin the cluster.

**Comment by sunnoy** [comment]
ExecStart=/usr/local/bin/k3s \
    server \
        '--node-taint' \
        'node-role.kubernetes.io/master=:NoSchedule' \
        '--tls-san' \
        'k8s-master.pro.devops.xxxxx' \
        '--data-dir' \
        '/data/k8s' \
        '--default-local-storage-path' \
        '/data/pods' \
        '--secrets-encryption' \
        '--protect-kernel-defaults' \
        '--server' \
        'https://172.20.1.88:6443' \


i have do this but there no etcd data only sqlite

```bash
ls
state.db  state.db-shm  state.db-wal
```

**Comment by brandond** [comment]
You appear to be missing a backslash to escape the newlines, on all of the lines except the last one. None of those flags are being passed to the command. If you have newlines between arguments, they must be escaped with a backslash. This is just how systemd units work, nothing specific to k3s.

**Comment by sunnoy** [comment]
ExecStart=/usr/local/bin/k3s \
    server \
        '--node-taint' \
        'node-role.kubernetes.io/master=:NoSchedule' \
        '--tls-san' \
        'k8s-master.pro.devops.xxx' \
        '--data-dir' \
        '/data/k8s' \
        '--default-local-storage-path' \
        '/data/pods' \
        '--secrets-encryption' \
        '--protect-kernel-defaults' \
        '--server' \
        'https://172.20.1.88:6443' \


just this ? but there no etcd data just "state.db  state.db-shm  state.db-wal"

**Comment by brandond** [comment]
yes, you now have sqlite files on disk because you didn't set the flags properly, and started it as a single-node server. You should delete the DB files from disk and allow it to join the cluster now that you have corrected the flags.

**Comment by sunnoy** [comment]
After I delete the db directory, it will still create a state file instead of etcd

```bash
1 del db files
/data/k8s/server ]# ls
cred  kine.sock  manifests  node-token  static  tls  token


2 start k3s ,it create sqlite files instead of etcd
[ /data/k8s/server/db ]# ls -l
total 5884
-rw-r--r-- 1 root root 1417216 Dec 28 14:32 state.db
-rw-r--r-- 1 root root   32768 Dec 28 14:31 state.db-shm
-rw-r--r-- 1 root root 4564992 Dec 28 14:32 state.db-wal

logs

Dec 28 14:31:42 xxxxxx k3s[291818]: time="2022-12-28T14:31:42+08:00" level=info msg="Starting k3s v1.23.6+k3s1 (418c3fa8)"
Dec 28 14:31:42 xxxxxx k3s[291818]: time="2022-12-28T14:31:42+08:00" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Dec 28 14:31:42 xxxxxx k3s[291818]: time="2022-12-28T14:31:42+08:00" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Dec 28 14:31:42 xxxxxx k3s[291818]: time="2022-12-28T14:31:42+08:00" level=info msg="Database tables and indexes are up to date"
Dec 28 14:31:42 xxxxxx k3s[291818]: time="2022-12-28T14:31:42+08:00" level=info msg="Kine available at unix://kine.sock"
```

**Comment by brandond** [comment]
You've still not got the flags set correctly. Are you sure there are no spaces between the backslash and the newline on every line? Did you do a daemon-reload to refresh the systemd unit contents before restarting?

**Comment by sunnoy** [comment]
The parameters I copied from other master nodes, just changed the ip, and systemctl daemon-reload will be executed every time it starts 
```bash
ExecStart=/usr/local/bin/k3s \
    server \
        '--node-taint' \
        'node-role.kubernetes.io/master=:NoSchedule' \
        '--tls-san' \
        'k8s-master.pro.devops.tuoying' \
        '--data-dir' \
        '/data/k8s' \
        '--default-local-storage-path' \
        '/data/pods' \
        '--secrets-encryption' \
        '--protect-kernel-defaults' \
        '--server' \
        'https://172.20.1.88:6443' \
```

**Comment by brandond** [comment]
The `Configuring sqlite3 database connection pooling` log line will not be output when a server joins an etcd cluster. Something is still not correct in your systemd unit. I cannot help you any more than that, given the information available to me.

**Comment by sunnoy** [comment]
this all k3s systemd unit

```bash
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--node-taint' \
        'node-role.kubernetes.io/master=:NoSchedule' \
        '--tls-san' \
        'k8s-master.pro.devops.tuoying' \
        '--data-dir' \
        '/data/k8s' \
        '--default-local-storage-path' \
        '/data/pods' \
        '--secrets-encryption' \
        '--protect-kernel-defaults' \
        '--server' \
        'https://172.20.1.88:6443' \
```

**Comment by brandond** [comment]
Take the backslash off the very last line, or make sure there are at least two blank lines after it? That's all I can think of...

**Comment by sunnoy** [comment]
I just launch it via command line as well
```bash
/usr/local/bin/k3s server --server https://172.20.1.56:6443 --tls-san k8s-master.pro.^Cvops.tuoying --data-dir /data/k8s
INFO[0000] Starting k3s v1.23.6+k3s1 (418c3fa8)         
INFO[0000] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
INFO[0000] Configuring database table schema and indexes, this may take a moment... 
INFO[0000] Database tables and indexes are up to date   
INFO[0000] Kine available at unix://kine.sock           
```

**Comment by sunnoy** [comment]
Is this a bug of v1.23.6+k3s1? I can rebuild etcd data in v1.26.0+k3s1, use the same operation

**Comment by brandond** [comment]
Perhaps. I will be honest I didn't play close attention to what version you're using. Have you tried the latest patch release for 1.23? That would be https://github.com/k3s-io/k3s/releases/tag/v1.23.15%2Bk3s1

**Comment by sunnoy** [comment]
v1.23.15+k3s1 and etcd not create too
```bash
./k3s -v
k3s version v1.23.15+k3s1 (50cab3b3)
go version go1.17.13

/opt/k3s server --tls-san k8s-master.pro.devops.xxx--data-dir /data/k8s --default-local-storage-path /data/pods --secrets-encryption --protect-kernel-defaults --server https://172.20.1.88:6443

INFO[0000] Acquiring lock file /data/k8s/data/.lock     
INFO[0000] Preparing data dir /data/k8s/data/8337c3c448159e502751ad88e10cd3bb2d8572cf28d9351bef216d68aaed3413 
INFO[0000] Starting k3s v1.23.15+k3s1 (50cab3b3)        
INFO[0000] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
```

**Comment by sunnoy** [comment]
i find code ,it need token args

```go
// pkg/cluster/managed.go
	// If we have been asked to initialize or join a cluster, do so using the default managed database.
	if c.config.Datastore.Endpoint == "" && (c.config.ClusterInit || (c.config.Token != "" && c.config.JoinURL != "")) {
		for _, driver := range managed.Registered() {
			if driver.EndpointName() == managed.Default() {
				c.managedDB = driver
				return nil
			}
		}
	}
```

so i add this 

```bash
/opt/k3s server --tls-san k8s-master.pro.devops.xxx --data-dir /data/k8s --default-local-storage-path /data/pods --secrets-encryption --protect-kernel-defaults --server https://172.20.1.88:6443 --token xxxx
```

it works for me !

**Comment by brandond** [comment]
Hmm, that token should be read from the file on disk, if this node had already been in use as a server. That's why I didn't mention it, but I guess I should have. Did you clean up anything besides the etcd database files before trying to rejoin it?

**Comment by sunnoy** [comment]
no ，i just delete db dir,i also guess k3s will read the token file on the disk ,but it not .
