### ISSUE TITLE
Cannot run any container on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by christian-schlichtherle** [k3s-io/k3s#6667]
**Environmental Info:**
K3s Version:
k3s version v1.26.0+k3s1 (fae88176)
go version go1.19.4

Node(s) CPU architecture, OS, and Version: 

Linux test-s0 6.0.0 #1.3 SMP Fri Nov 18 05:18:45 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:

3 servers, 11 agents

**Describe the bug:**

I'm trying to install K3s 1.26.0 on a newly flashed node with Ubuntu 22.04 LTS. The installation succeeds, but I'm unable to start any pod on the node. I get the following:

```
$ kubectl describe node salim-s0
[...]
Events:
  Type     Reason                            Age                  From                   Message
  ----     ------                            ----                 ----                   -------
  Normal   Starting                          57m                  kube-proxy             
  Normal   Starting                          9m3s                 kube-proxy             
  Normal   Starting                          57m                  kubelet                Starting kubelet.
  Warning  InvalidDiskCapacity               57m                  kubelet                invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory           57m (x2 over 57m)    kubelet                Node salim-s0 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure             57m (x2 over 57m)    kubelet                Node salim-s0 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID              57m (x2 over 57m)    kubelet                Node salim-s0 status is now: NodeHasSufficientPID
  Normal   NodeReady                         57m                  kubelet                Node salim-s0 status is now: NodeReady
  Warning  FailedNodeAllocatableEnforcement  32m (x26 over 57m)   kubelet                Failed to update Node Allocatable Limits ["kubepods"]: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory
  Normal   Starting                          9m4s                 kubelet                Starting kubelet.
  Warning  InvalidDiskCapacity               9m4s                 kubelet                invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory           9m4s (x2 over 9m4s)  kubelet                Node salim-s0 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure             9m4s (x2 over 9m4s)  kubelet                Node salim-s0 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID              9m4s (x2 over 9m4s)  kubelet                Node salim-s0 status is now: NodeHasSufficientPID
  Normal   Synced                            9m3s                 cloud-node-controller  Node synced successfully
  Normal   NodeReady                         9m2s                 kubelet                Node salim-s0 status is now: NodeReady
  Normal   RegisteredNode                    8m59s                node-controller        Node salim-s0 event: Registered Node salim-s0 in Controller
  Warning  FailedNodeAllocatableEnforcement  58s (x9 over 9m2s)   kubelet                Failed to update Node Allocatable Limits ["kubepods"]: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory
```

**Steps To Reproduce:**

- Install Ubuntu 22.04 LTS on an ARM node
- Configure iptables-legacy (k3s-agent won't even start with iptables-nft)
- Install k3s as agent
- Try to run any pod

**Expected behavior:**
Pod starting on the node.

**Actual behavior:**

**Additional context / logs:**
Pods remain in "pending" state and the node has the events listed above.

**Comment by christian-schlichtherle** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by christian-schlichtherle** [comment]
Same procedure works fine when executed on Ubuntu 20.04 LTS instead of 22.04 LTS.

**Comment by brandond** [comment]
Are you using cgroup v1, v2, or hybrid - what is the output of `grep cgroup /proc/mounts`?

Are you using the embedded containerd, --docker, or another runtime with --container-runtime-endpoint?

Is this a raspberry pi, or perhaps some other device with a kernel that is missing features? I am personally running K3s 1.26.0 on a Pi with Ubuntu 22.04 and it works fine.

```console
root@seago:~# kubectl get node -A -o wide
NAME              STATUS   ROLES                  AGE      VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION          CONTAINER-RUNTIME
pi02.lan.khaus    Ready    <none>                 108d     v1.26.0+k3s1   10.0.1.24     <none>        Ubuntu 22.04.1 LTS   5.15.0-1016-raspi       containerd://1.6.12-k3s1
seago.lan.khaus   Ready    control-plane,master   2y198d   v1.26.0+k3s1   10.0.1.20     <none>        Ubuntu 22.04.1 LTS   5.19.5-051905-generic   containerd://1.6.12-k3s1
```

**Comment by christian-schlichtherle** [comment]
Thanks for your swift response!

Our nodes are running on Khadas VIM3 Pro hardware. They've been running Ubuntu 20.04 LTS with K3s for a long time. Now I've upgraded all nodes to Ubuntu 22.04. It's been working fine except for this one.

```
$ ansible edge -a 'grep cgroup /proc/mounts'
[...]
kim-s0 | CHANGED | rc=0 >>
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
salim-s0 | CHANGED | rc=0 >>
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
```

and then ...

```
$ ansible edge -a  'cat /sys/fs/cgroup/cgroup.controllers'
[...]
kim-s0 | CHANGED | rc=0 >>
cpuset cpu io memory pids rdma
salim-s0 | CHANGED | rc=0 >>
cpuset cpu io memory pids rdma
```

These results are consistent for all edge nodes, so they all show the same results, except `/proc/mounts` has a few extra flags on the node `salim-s0` - that's the one with this issue. I have no idea what these params mean and where to change them if its relevant.

**Comment by christian-schlichtherle** [comment]
After yet another reboot the mount options `nsdelegate` and `memory_recursiveprot` disappeared and now everything works as expected. Although the problem solved itself now, it isn't a great user experience because I had to reboot the node once again.

**Comment by brandond** [comment]
That sounds like with an issue with Ubuntu or your host, not K3s. We don't change anything about how the cgroup controllers are mounted. Systemd is usually responsible for that?

**Comment by cwayne18** [comment]
Also are you using a custom kernel? That can cause issues as well.

**Comment by christian-schlichtherle** [comment]
We are flashing new nodes with an image (now Ubuntu 22.04 LTS, before it was 20.04 LTS) and then use Ansible to upgrade packages and configure the OS and eventually install K3s. The Ansible playbook obeys `/var/run/reboot-required` just before K3s gets installed - resulting in just a single reboot. This worked fine with Ubuntu 20.04. Apparently with 22.04 LTS one more manual reboot is required after the installation of K3s.

I agree this looks like an issue with Ubuntu, not K3s, so let me close this issue - thanks for your help.

PS: We are using a mainline Kernel from Khadas, the board manufacturer. The current version is 6.0.0.

**Comment by alexellis** [comment]
@brandond this seems like a similar issue, no problems at all with the same Kernel on Ubuntu 20.04 - the only difference here is the rootfs, which now uses Ubuntu 22.04.

I can see the cpuset cgroup in the above commands, too.

**Comment by brandond** [comment]
> K3s v1.20 works - anything below that fails with the above errors.

Why would you run anything earlier than 1.19 on Ubuntu 22.04? Those releases are all long end-of-life.

**Comment by alexellis** [comment]
It was part of a matrix test demo for [actuated](https://actuated.dev) which tested a CRD with every available K3s version.

It seems like v1.20 is the min compatible version for 22.04 - I didn't realise that was the case, and couldn't find that documented. Makes sense now that we talk about it.

Thanks for your time @brandond
