### ISSUE TITLE
Downloading v1.22.2-k3s2/sha256sum-amd64.txt faild

### ISSUE THREAD

**Issue by 15135925147** [k3s-io/k3s#6669]
**Environmental Info:**
K3s Version: v1.22.2+k3s2

![image](https://user-images.githubusercontent.com/48895226/209147532-8eafacfb-f7ab-4016-bf56-339b06d69595.png)

**Comment by brandond** [comment]
Please see https://github.com/k3s-io/k3s/issues/5942#issuecomment-1203643893
