### ISSUE TITLE
Service with no backing application takes approx. 120s to fail (w/ weave CNI)

### ISSUE THREAD

**Issue by HoustonDad** [k3s-io/k3s#6691]
**Environmental Info:**
K3s Version: 1.22.6 and 1.23.6 (On Centos 7). Support tested with 1.23.6 on ubuntu 20.04

Node(s) CPU architecture, OS, and Version: 
CentOS 7 / Ubuntu 20.04

Cluster Configuration:
Occurs on multinode and single node clusters

**Describe the bug:**
K3s service with no backing application takes approx 120sec to fail when performing netcat

**Steps To Reproduce:**
Create Service:

```
 apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - name: "1313"
      port: 1313
      targetPort: 1313
      nodePort: 31111
  selector:
    app: nginx
```

Run busybox container:
```
kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
```
 
Run check:
```
date; nc nginx 1313; echo $?; date
```
**Expected behavior:**
```
date; nc my-service 1313; echo $?; date
Thu May 12 14:00:47 UTC 2022
1
Thu May 12 14:00:48 UTC 2022
```

**Actual behavior:**
```
date; nc my-service 1313; echo $?; date
Thu May 12 13:35:34 UTC 2022
1
Thu May 12 13:37:42 UTC 2022
```

**Workaround:**
Is workararound available and implemented? yes

What is the workaround:

"I have a workaround, using the '-w 1' argument to nc, but it seems like this problem can affect anything that uses a Service to connect to something, and if we aren't being extremely careful, the timeout issue could pop up all over the place unexpectedly."

**Additional Info:**
When testing on RKE2 1.22.7, there is NO 120second lag.

**Comment by brandond** [comment]
OK, so you should be getting ICMP unreachable messages when trying to connect to those ports. Are you seeing those in your pods?

**Comment by RedHawker** [comment]
No. 

```
/ # ping nginx:1313
PING nginx:1313 (10.43.68.244): 56 data bytes
^C
--- nginx:1313 ping statistics ---
425 packets transmitted, 0 packets received, 100% packet loss
```

We're using Weave - could that be causing an issue?

**Comment by brandond** [comment]
That's not how that works. You would need to attempt a **tcp** connection on that port, and use tcpdump or something else to watch for an ICMP Port Unreachable message in response.

I don't know much about Weave but the rules from kube-proxy look correct, so I do suspect that something is going on with the CNI that is preventing the ICMP traffic from making it back to the pod.

**Comment by RedHawker** [comment]
Isn't the TCP connection the point of using `nc` above in the original problem description?

**Comment by brandond** [comment]
That specific difference - application not being up yet, vs application not listening on the port - is not what was described in the issue. What was specifically described was a NodePort service with no backing pods.

If the service has no ready pods (no endpoints), kube-proxy will see that and send an ICMP unreachable back. If the service HAS pods that have passed their startup and readiness checks, but the service itself is not yet responding - then the behavior is probably less desirable. This would be a configuration problem though - you should ensure that your pods have heath and rediness checks that ensure that they are both up and serving traffic before they are marked ready and start handling traffic for services.

**Comment by RedHawker** [comment]
> If the service has no ready pods (no endpoints), kube-proxy will see that and create rules to send an ICMP unreachable back to connection attempts on that port. That should trigger the 'fail fast' behavior.  

This is the expected behavior, do you have any suggestions on how to track down where the response is getting sent to the void?

This isn't specific to this one use case, it's **any** Service without a backing application and any client that happens to try and connect to that Service without including some kind of timeout, since that ICMP unreachable doesn't make it back until 120 seconds have elapsed.

**Comment by brandond** [comment]
> that ICMP unreachable doesn't make it back until 120 seconds have elapsed.

How have you confirmed that? Confirming the timing of when the unreachable gets sent is what I was attempting to have you check making a **tcp** connection to the NodePort and watching for the ICMP response with tcpdump. 

There is no delay in the iptables rule, any connection attempt (ie a new packet not part of an existing conntrack session) should trigger the ICMP response.

**Comment by RedHawker** [comment]
It's in the problem description.  

> Expected behavior:
> 
> date; nc my-service 1313; echo $?; date
> Thu May 12 14:00:47 UTC 2022
> 1
> Thu May 12 14:00:48 UTC 2022
> 
> Actual behavior:
> 
> date; nc my-service 1313; echo $?; date
> Thu May 12 13:35:34 UTC 2022
> 1
> Thu May 12 13:37:42 UTC 2022
> 

13:37:42 - 13:35:34 - sorry, it's 128 seconds.

**Comment by RedHawker** [comment]
It's probably 127 seconds, based on 7 retries and exponential back-off: https://mechpen.github.io/posts/2019-11-17-network-timeouts/#3.2.-tcp-connection-timeout

**Comment by brandond** [comment]
The issue was described as `K3s service with no backing application takes approx 120sec to fail when performing netcat`. The example manifest shows creating a service with no pods behind it, which matches the issue description, but is NOT what you're describing. You've described a service backed by pods that aren't serving traffic. There IS a difference.

**Comment by RedHawker** [comment]
No. I have not.

**Comment by RedHawker** [comment]
I misspoke above, regarding `nc` failing fast if the application is up but not listening on the specified port. It still fails slow.

- No Service created: `nc` fails fast with `bad address 'nginx'`  
- With Service created and no backing Pod: `nc` fails slow  
- With Service created and packing Pod listening to 1313, `nc nginx 1313` connects fine.  
- With Service created and packing Pod listening to 1313, `nc nginx 1314` displays the fail slow behavior.

**Comment by RedHawker** [comment]
This issue: https://bugzilla.redhat.com/show_bug.cgi?id=1782857 describes similar behavior, specifically calling out Services without Endpoints. 

That issue points to: https://github.com/kubernetes/kubernetes/pull/72534  - there seem to be PRs out there have attempted to address this (or similar) issue.

**Comment by RedHawker** [comment]
@HoustonDad you said:
> When testing on RKE2 1.22.7, there is NO 120second lag.  

Can you compare the `iptables-save` or `iptables --list` for RKE vs k3s?

**Comment by brandond** [comment]
they are going to be VERY different depending on the CNI in use.

**Comment by RedHawker** [comment]
If I try to run the `nc` command from the host (non container) the iptables rule to reject the connection gets hit, but when I run the `nc` command from inside a container, the rule **does not** get hit.

I've verified this by running `iptables --list --line-numbers -v` and seeing that the `pkts` amounts for the REJECT rule on the Service-without-Endpoint's internal port, under the `KUBE-SERVICES` chain.
I've also added packet tracing to my iptables to track packets:  

```
iptables -A PREROUTING -t raw -p tcp -m tcp --dport 1313 -j TRACE
iptables -A OUTPUT -t raw -p tcp -m tcp --dport 1313 -j TRACE
```

I'm definitely not an expert in iptables, so it's possible I'm attempting to track down the wrong thing.

**Comment by brandond** [comment]
Have you tried tinkering with the internal traffic policy on the service?

https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/

**Comment by RedHawker** [comment]
I don't see a difference with `internalTrafficPolicy: Local`. I also made my Service non-NodePort just to simplify things.

> I wonder if this is some odd interaction between kube-proxy and the CNI.  

Yeah, I'm wondering if weave isn't causing this issue. (FWIW: We're using weave, but not weave-npc). Though I'm not sure @HoustonDad used weave to verify the issue.

**Comment by brandond** [comment]
Hmm. I see that you compared it to RKE2, but did you compare to just vanilla K3s with Flannel?

**Comment by RedHawker** [comment]
So this is absolutely NOT the way to achieve my needs, but I at least verified I can get the desired behavior by adding a REJECT rule to iptables in `filter:FORWARD` for my Service's IP.

`iptables -t filter -I FORWARD -p tcp -d <Service IP here>/32 -j REJECT` - running my `nc` command now results in an immediate connection refused.

----

Interestingly, on the iptables packet trace, the last step the packet from the debug container takes is hitting the `nat:weave` rule, which is `MASQUERADE  all  --  10.32.0.0/16        !10.32.0.0/16 `

At this point, I'm not sure where the packet goes.

----

> Hmm. I see that you compared the behavior to RKE2, but did you compare to just vanilla K3s with Flannel? 

I haven't compared to RKE2, I'll try to spin up a machine with just flannel tomorrow (Jan 13).

**Comment by RedHawker** [comment]
Just verified with a bare install of k3s 1.22.6 on CentOS 7, using the command: 

`curl -fL https://raw.githubusercontent.com/k3s-io/k3s/v1.22.6%2Bk3s1/install.sh | INSTALL_K3S_VERSION=v1.22.6+k3s1 K3S_TOKEN=blah sh -s - --disable traefik server --cluster-init` 

That the issue exists.

The last step in my iptables trace is:

```
TRACE: nat:POSTROUTING:rule:3 IN= OUT=eth0 PHYSIN=veth0729e117 SRC=10.42.0.6 DST=10.43.98.255 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=4827 DF PROTO=TCP SPT=43676 DPT=1800 SEQ=874472060 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A000270A70000000001030307) MARK=0x20000
```


----


Running: `curl -fL https://get.k3s.io | K3S_TOKEN=blah sh -s - --disable traefik server --cluster-init` (v1.25.4+k3s1) results in the same behavior, but the last step in the trace is now:

```
TRACE: nat:FLANNEL-POSTRTG:rule:2 IN= OUT=eth0 PHYSIN=veth05c4a9b1 SRC=10.42.0.5 DST=10.43.211.181 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=43375 DF PROTO=TCP SPT=45096 DPT=1800 SEQ=2747207916 ACK=0 WINDOW=28200 RES=0x00 SYN URGP=0 OPT (020405820402080A0007B9830000000001030307) MARK=0x20000
```

**Comment by RedHawker** [comment]
Any thoughts?

**Comment by brandond** [comment]
Sounds like a flannel thing perhaps?
@manuelbuil @thomasferrandiz @rbrtbnfgl

**Comment by rbrtbnfgl** [comment]
I'll try to check what the CNI is doing. The issue is related to the service that results unreachable even if it is or if the service is deliberately unreachable it takes 120s to fail?

**Comment by rbrtbnfgl** [comment]
Ok I was able to have a similar setup. I'm tracing the iptables rules to check what is wrong.

**Comment by rbrtbnfgl** [comment]
I probably found where is the issue. It's on the FORWARD chain with K3s we have the following chain
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    7   628 KUBE-ROUTER-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-router netpol - TEMCG2JMHZYE7H7T */
    0     0 FLANNEL-FWD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* flanneld forward */
    0     0 KUBE-PROXY-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes load balancer firewall */
    0     0 KUBE-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */
    0     0 KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
    0     0 KUBE-EXTERNAL-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes externally-visible service portals */
```
The reject rule is on the `KUBE-SERVICES` chain but if one rule from the previous chain has `ACCEPT` as action the other following rules are not executed. On K3s every forwarded packet with an IP from a pod is accepted by `KUBE-ROUTER-FORWARD` a solution could be to disable the network policy `--disable-network-policy` but the same issue is on flannel because in `FLANNEL-FWD` the packets from the pods are accepted. The rules needs to be reordered I can fix it on flannel but for kube-router I have to check.

**Comment by RedHawker** [comment]
I see you made changes to flannel and kube-router, will the kube-router changes be sufficient for weave to work as expected, or will weave need to be updated to too?

**Comment by rbrtbnfgl** [comment]
It should work. I saw that the weave iptebles rules are appended at the end of the chain.

**Comment by brandond** [comment]
Reopening for QA

**Comment by VestigeJ** [comment]
##Environment Details
VERSION=v1.26.2+k3s1
COMMIT=9980504196ce0cb53c8e04756598d6f8982a5756

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-12-13-14-110   Ready    control-plane,etcd,master   6h40m   v1.26.2+k3s-99805041
ip-12-13-14-232   Ready    control-plane,etcd,master   6h38m   v1.26.2+k3s-99805041 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: acesbases
selinux: true
protect-kernel-defaults: true
cluster-init: true
```

<details><summmary><h4> Reproduced using VERSION=v1.26.2+k3s1 </h4></summary>


```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ VERSION=v1.26.2+k3s1
$ sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig
$ kgn
$ sudo journalctl -u k3s | grep netpol
$ kgp -A
$ kg ing -A
$ vim deploy.yaml
$ k apply -f ingress.yaml 
$ kg ing -A
$ kg svc -A
```

**Results:**

VERSION=v1.26.2+k3s1

$ /var/lib/rancher/k3s/data/current/bin/flannel
```
CNI Plugin flannel version v0.21.1 (linux/amd64) commit HEAD built on 2023-03-10T22:29:12Z
```

$ sudo journalctl -u k3s | grep netpol
```
Mar 17 17:05:54 ip-172-31-16-60 k3s[3376]: time="2023-03-17T17:05:54Z" level=info msg="Starting the netpol controller version v1.5.2-0.20221026101626-e01045262706, built on 2023-03-10T22:29:12Z, go1.19.6"
Mar 17 17:59:58 ip-172-31-16-60 k3s[10360]: time="2023-03-17T17:59:58Z" level=info msg="Starting the netpol controller version v1.5.2-0.20221026101626-e01045262706, built on 2023-03-10T22:29:12Z, go1.19.6"
```

$ cat deploy.yaml
```
#use expose command to expose the service and targetport shoule be 80 important
#kubectl expose deployment nginx-loadbalancer-pod  --target-port=80 --type=LoadBalancer --name=myservice --port=81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer-pod
spec:
  selector:
    matchLabels:
      app: nginx-app-lb
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app-lb
    spec:
      containers:
      - name: nginx
        image: ranchertest/mytestcontainer
        ports:
        - containerPort: 80
```

$ kg svc
```
NAME                    TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
kubernetes              ClusterIP   10.43.0.1     <none>        443/TCP    142m
othertest-ingress-svc   ClusterIP   10.43.88.20   <none>        8080/TCP   126m
```

$ kgp
```
NAME                                      READY   STATUS    RESTARTS   AGE
othertest-deploy-rpw64                    1/1     Running   0          85m
nginx-loadbalancer-pod-79b578bc74-nptnp   1/1     Running   0          74s
nginx-loadbalancer-pod-79b578bc74-chnt9   1/1     Running   0          74s
ec2-user@ip-172-31-16-60:~$ kubectl expose deployment nginx-loadbalancer-pod-79b578bc74-chnt9  --target-port=80 --type=LoadBalancer --name=othertest-ingress-svc --port=81
Error from server (NotFound): deployments.apps "nginx-loadbalancer-pod-79b578bc74-chnt9" not found
```

$ kubectl expose deployment nginx-loadbalancer-pod  --target-port=80 --type=LoadBalancer --name=otingress-svc --port=81
```
service/otingress-svc exposed
```

$ kg svc
```
NAME                    TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)        AGE
kubernetes              ClusterIP      10.43.0.1      <none>         443/TCP        143m
othertest-ingress-svc   ClusterIP      10.43.88.20    <none>         8080/TCP       127m
otingress-svc           LoadBalancer   10.43.254.11   172.31.16.60   81:30629/TCP   5s
```

```
$ curl -H host:test1.com http://172.31.16.60/name.html

othertest-deploy-rpw64

$ curl -H host:test1.com http://172.31.16.60:81/name.html

nginx-loadbalancer-pod-79b578bc74-nptnp

$ kgp -o wide

NAME                                      READY   STATUS    RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
othertest-deploy-rpw64                    1/1     Running   0          95m   10.42.0.9    ip-172-31-16-60   <none>           <none>
nginx-loadbalancer-pod-79b578bc74-nptnp   1/1     Running   0          11m   10.42.0.11   ip-172-31-16-60   <none>           <none>
nginx-loadbalancer-pod-79b578bc74-chnt9   1/1     Running   0          11m   10.42.0.10   ip-172-31-16-60   <none>           <none>

$ curl -H host:test1.com http://172.31.16.60:81/name.html

nginx-loadbalancer-pod-79b578bc74-chnt9

$ curl -H host:test1.com http://172.31.16.60:81/name.html

nginx-loadbalancer-pod-79b578bc74-nptnp

$ curl -H host:test1.com http://172.31.16.60:81/name.html

nginx-loadbalancer-pod-79b578bc74-nptnp

$ curl -H host:test1.com http://172.31.16.60:81/name.html

nginx-loadbalancer-pod-79b578bc74-chnt9

```



</details>

<details><summmary><h4>Validated using COMMIT=9980504196ce0cb53c8e04756598d6f8982a5756 </h4></summary>
 
## Validation Steps
 

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ COMMIT=9980504196ce0cb53c8e04756598d6f8982a5756
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig
$ kgn
$ sudo journalctl -u k3s | grep netpol
$ kgp -A
$ kg ing -A
$ vim ingress.yaml
$ k apply -f ingress.yaml 
$ kg ing -A
$ kg svc -A
$ get_report
```
 
**Results:**

COMMIT=9980504196ce0cb53c8e04756598d6f8982a5756

$ /var/lib/rancher/k3s/data/current/bin/flannel

```
CNI Plugin flannel version v0.21.3 (linux/amd64) commit HEAD built on 2023-03-17T00:57:13Z
```

$ sudo journalctl -u k3s | grep netpol

```
Mar 17 16:00:07 ip-172-31-24-232 k3s[2832]: time="2023-03-17T16:00:07Z" level=info msg="Starting the netpol controller version v1.5.1-0.20230223115732-df90811446a1, built on 2023-03-17T00:57:13Z, go1.19.6"
```


$ kg svc 
```
NAME                    TYPE           CLUSTER-IP     EXTERNAL-IP                   PORT(S)        AGE
kubernetes              ClusterIP      10.43.0.1      <none>                        443/TCP        4h24m
othertest-ingress-svc   ClusterIP      10.43.206.69   <none>                        8080/TCP       127m
otingress-svc           LoadBalancer   10.43.2.9      172.31.19.110,172.31.24.232   81:32049/TCP   3s
```

```
$ curl -H host:test1.com http://172.31.19.110/name.html

othertest-deploy-5h8m8

$ curl -H host:test1.com http://172.31.24.232/name.html

othertest-deploy-5zxqr

$ curl -H host:test1.com http://172.31.19.110:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-zdqcw

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-zdqcw

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-zdqcw

$ curl -H host:test1.com http://172.31.24.232:81/name.html

nginx-loadbalancer-pod-79b578bc74-jgmlz

```

ec2-user@ip-172-31-24-232:~$ kgp -o wide
```
NAME                                      READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
nginx-loadbalancer-pod-79b578bc74-jgmlz   1/1     Running   0          13m   10.42.1.4    ip-172-31-24-232   <none>           <none>
nginx-loadbalancer-pod-79b578bc74-zdqcw   1/1     Running   0          13m   10.42.0.10   ip-172-31-19-110   <none>           <none>
othertest-deploy-5h8m8                    1/1     Running   0          97m   10.42.0.9    ip-172-31-19-110   <none>           <none>
othertest-deploy-5zxqr                    1/1     Running   0          97m   10.42.1.3    ip-172-31-24-232   <none>           <none>
```
 
**Additional context / logs:**

$ cat deploy.yaml

```
#use expose command to expose the service and targetport shoule be 80 important
#kubectl expose deployment nginx-loadbalancer-pod  --target-port=80 --type=LoadBalancer --name=myservice --port=81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer-pod
spec:
  selector:
    matchLabels:
      app: nginx-app-lb
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app-lb
    spec:
      containers:
      - name: nginx
        image: ranchertest/mytestcontainer
        ports:
        - containerPort: 80
```

</details>
