### ISSUE TITLE
Cannot create agent with configuration file

### ISSUE THREAD

**Issue by fmunteanu** [k3s-io/k3s#6697]
**Environmental Info:**
K3s Version: 
k3s version v1.25.5+k3s1 (48e5d2af)
go version go1.19.4

Node(s) CPU architecture, OS, and Version: 

```
# uname -a
Linux atlas 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
```

Cluster Configuration:
1 server (atlas), 3 agents

**Describe the bug:**
I cannot create an agent with a config file.

control-plane:

```
install -d /etc/rancher/k3s
cat > /etc/rancher/k3s/config.yaml << 'EOF'
disable:
  - local-storage
  - servicelb
disable-cloud-controller: true
node-taint: CriticalAddonsOnly=true:NoExecute
tls-san:
  - 192.168.1.9
EOF
chown 0600 /etc/rancher/k3s/config.yaml
curl -sfL https://get.k3s.io | sh -s - server
```

Result:

```
# hostname
atlas
# hostname -I
192.168.4.2 10.42.0.0 169.254.105.12 10.42.0.1 169.254.109.34 169.254.41.102
# kubectl get nodes
NAME    STATUS   ROLES                  AGE   VERSION
atlas   Ready    control-plane,master   13m   v1.25.5+k3s1
```

worker:

```
install -d /etc/rancher/k3s
cat > /etc/rancher/k3s/config.yaml << 'EOF'
node-label:
  - kubernetes.io/role=worker
  - node-type=worker
server: https://192.168.4.2:6443
token: K10[removed]::server:[removed]
EOF
chown 0600 /etc/rancher/k3s/config.yaml
curl -sfL https://get.k3s.io | sh -s - agent
```

If I remove the node-label from configuration, I can deploy the agent. Since there are no references for config.yaml, I'm guessing the format I used is correct. Is there a way to have the config.yaml validated for errors?

**Comment by brandond** [comment]
Nodes cannot set their own roles. See the thread at https://github.com/k3s-io/k3s/issues/1289#issuecomment-784548173

> Nodes are not permitted to assert their own role labels. Node roles are typically used to identify privileged or control plane types of nodes, and allowing nodes to label themselves into that pool allows a compromised node to trivially attract workloads (like control plane daemonsets) that confer access to higher privilege credentials.

**Comment by brandond** [comment]
Also note that the "worker" role is not used for anything in K3s; the only roles used by K3s are `control-plane` and `etcd` (as well as `master` for legacy compatibility reasons). Labeling your agents with the worker role would be purely cosmetic. Any agent node without the control-plane or etcd nodes is implicitly a worker.

**Comment by fmunteanu** [comment]
@brandond thank you for the useful information, yes, `worker` label is purely cosmetic in my case. What is the proper way to validate that my `config.yaml` is correct? Say for example, I insert the wrong key/value.

**Comment by brandond** [comment]
There is no strict schema to the config file. The keys and values are translated directly to CLI flags and passed in to the command execution as if you'd included them on the command line. For that reason, there is no syntax checker; you have to just run the command.

**Comment by fmunteanu** [comment]
@brandond I understand, in other words, if the key/value is wrong, it will be ignored without warning.
