### ISSUE TITLE
[v1.22.16+k3s1] (and beyond) kubectl log produces proxy error 503 service unavailable

### ISSUE THREAD

**Issue by RumRogerz** [k3s-io/k3s#6698]
**Environmental Info:**
K3s Version: 
```
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.5+k3s1",
    "gitCommit": "48e5d2af5bfc69db051d46b6c6b83c46d15a9da5",
    "gitTreeState": "clean",
    "buildDate": "2022-12-21T00:06:36Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.5+k3s1",
    "gitCommit": "48e5d2af5bfc69db051d46b6c6b83c46d15a9da5",
    "gitTreeState": "clean",
    "buildDate": "2022-12-21T00:06:36Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

Node(s) CPU architecture, OS, and Version: 

`Linux ca-infr-dev-001.mycluster.internal 5.4.0-1092-aws #100~18.04.2-Ubuntu SMP Tue Nov 29 08:39:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 master, 1 worker
### k3s.service
```
ExecStart=/usr/local/bin/k3s \
    server \
	'--node-external-ip' \
	'1.2.3.4' \
	'--disable' \
	'traefik' \
	'--disable' \
	'servicelb' \
	'--flannel-backend' \
	'wireguard-native' \
	'--disable-network-policy' \
	'--cluster-cidr' \
	'10.42.0.0/16' \
	'--service-cidr' \
	'10.43.0.0/16' \
	'--disable' \
	'local-storage' \
	'--secrets-encryption' \
	'--cluster-init' \
	'--kube-scheduler-arg=config=/etc/rancher/k3s/control-plane-configs/scheduler.yaml' \
	'--kubelet-arg=config=/etc/rancher/k3s/control-plane-configs/kubelet-master.yaml' \
	'--kubelet-arg=provider-id=aws:///ca-central-1a/i-012c892410cd1097a' \
	'--kubelet-arg=cloud-provider=external' \
	'--kube-apiserver-arg=oidc-groups-claim=groups' \
	'--kube-apiserver-arg=oidc-username-claim=sub' \
	'--kube-apiserver-arg=oidc-client-id=k3s-apiserver' \
	'--kube-apiserver-arg=oidc-issuer-url=https://keycloak.mycluster.com/auth/realms/my-cool-realm' \
	'--kube-apiserver-arg=oidc-username-prefix=oidc:' \
	'--kube-apiserver-arg=oidc-groups-prefix=oidc:' \
```
**Describe the bug:**

doing a `kubectl log` on any pod, regardless of which node it runs on produces this error:

>Error from server: Get "https://10.10.0.79:10250/containerLogs/kube-system/coredns-689d6798c-5b7vd/coredns": proxy error from 127.0.0.1:6443 while dialing 10.10.0.79:10250, code 503: 503 Service Unavailable

**Steps To Reproduce:**

- Installed K3s: 
Upgraded from `v1.21.4+k3s1 ` to `v1.22.16+k3s1`.  Any version beyond 1.22 that we installed produces the same results.  v1.21 worked without a hitch.  We have tried both upgrading and fresh installs of 1.22+

**Expected behavior:**

see some logs :)

**Actual behavior:**

produces the above error.  Eventually, after repeated attempts of the `kubectl log` command, it _will_ produce output; but as you can imagine, this is not a desirable outcome.

**Additional context / logs:**

syslogs from the node (10.10.0.79) produce this error:

> Jan  5 15:43:35 ca-infr-dev-002 k3s[23589]: E0105 15:43:35.434756   23589 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://10.10.0.79:10250/containerLogs/kube-system/coredns-689d6798c-5b7vd/coredns", Err:(*errors.errorString)(0xc00a9497e0)}: Get "https://10.10.0.79:10250/containerLogs/kube-system/coredns-689d6798c-5b7vd/coredns": proxy error from 127.0.0.1:6443 while dialing 10.10.0.79:10250, code 503: 503 Service Unavailable

We have tried `export no_proxy="10.10.0.0/16,127.0.0.1,localhost"` and then restarting the k3s service - which did not work.

**Comment by brandond** [comment]
Environment variables exported in your shell aren't picked up by systemd units, even if you export them. You should add the no_proxy environment variables to `/etc/sysconfig/k3s` or `/etc/sysconfig/k3s-agent` depending on which this is on.

**Comment by RumRogerz** [comment]
@brandond Thanks for getting back to me.
I made the suggested changes and added `no_proxy` to the respective `.env` files & restarted the services however the issues still persist. :(

**Comment by brandond** [comment]
Can you start the servers with `--debug` and see what it says when attempting to connect to the agents to retrieve logs?

**Comment by RumRogerz** [comment]
@brandond Sorry for the lateness of my reply.  I enabled debug on the nodes and the only pertinent logs I can find are as follows:

> Jan  9 19:14:43 ca-swarmio-infr-dev-002 k3s[27700]: time="2023-01-09T19:14:43Z" level=debug msg="Wrote ping"
Jan  9 19:14:44 ca-swarmio-infr-dev-002 k3s[27700]: time="2023-01-09T19:14:44Z" level=debug msg="Tunnel server handing HTTP/1.1 CONNECT request for //10.10.0.79:10250 from 127.0.0.1:54724"
>Jan  9 19:14:44 ca-swarmio-infr-dev-002 k3s[27700]: time="2023-01-09T19:14:44Z" level=debug msg="Tunnel server egress proxy dial error: failed to find Session for client ip-10-10-0-79"
>Jan  9 19:14:44 ca-swarmio-infr-dev-002 k3s[27700]: E0109 19:14:44.278383   27700 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://10.10.0.79:10250/containerLogs/kube-system/coredns-689d6798c-5b7vd/coredns", Err:(*errors.errorString)(0xc008fe31a0)}: Get "https://10.10.0.79:10250/containerLogs/kube-system/coredns-689d6798c-5b7vd/coredns": proxy error from 127.0.0.1:6443 while dialing 10.10.0.79:10250, code 503: 503 Service Unavailable

**Comment by brandond** [comment]
```
Jan 9 19:14:44 ca-infr-dev-002 k3s[27700]: time="2023-01-09T19:14:44Z" level=debug msg="Tunnel server handing HTTP/1.1 CONNECT request for //10.10.0.79:10250 from 127.0.0.1:54724"
Jan 9 19:14:44 ca-infr-dev-002 k3s[27700]: time="2023-01-09T19:14:44Z" level=debug msg="Tunnel server egress proxy dial error: failed to find Session for client ip-10-10-0-79"
```
So it knows about that agent, but the agent doesn't appear to be connected. Is that node online at the moment?

**Comment by RumRogerz** [comment]
@brandond 

It sure is online.  I am currently in that node. k3s service is running.  I can view logs from any pod that is running on that node without issue - once i select a pod outside that node it will give me those lovely 503 errors.

**Comment by brandond** [comment]
Are you overriding the agent node names or hostnames or something? I'm at a loss as to how it could know the name of that node, but not have a session for it, if the node is up. Is there perhaps something preventing the agents from connecting to all of the servers? What is the output of `kubectl get node -o wide` on this cluster?

On the servers, you should see a log entry that says something like `INFO[0041] Handling backend connection request [k3s-agent-1]` whenever the agents connect. Do you see this?

**Comment by RumRogerz** [comment]
@brandond I suspect that there must be something preventing the connections from happening although I'm having a hell of a time trying to pin it down.
output of this cluster is:
```
NAME                                       STATUS   ROLES                       AGE     VERSION        INTERNAL-IP   EXTERNAL-IP    OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
ca-infr-dev-001.my-cool-site.internal   Ready    control-plane,etcd,master   450d    v1.25.5+k3s1   10.10.0.46    1.2.3.4   Ubuntu 18.04.5 LTS   5.4.0-1092-aws   containerd://1.6.12-k3s1
ca-infr-dev-002.my-cool-site.internal   Ready    control-plane,etcd,master   450d    v1.25.5+k3s1   10.10.0.43    1.2.3.4   Ubuntu 18.04.5 LTS   5.4.0-1092-aws   containerd://1.6.12-k3s1
ca-infr-dev-003.my-cool-site.internal   Ready    control-plane,etcd,master   450d    v1.25.5+k3s1   10.10.0.35    1.2.3.4   Ubuntu 18.04.5 LTS   5.4.0-1092-aws   containerd://1.6.12-k3s1
ip-10-10-0-79                              Ready    <none>                      4d15h   v1.25.5+k3s1   10.10.0.79    <none>         Ubuntu 18.04.5 LTS   5.4.0-1038-aws   containerd://1.6.12-k3s1
```
Sorry if I was not being clear.  This is what I mean by "that node": I am currently shelled into node 002.  I have a sts running on 3 different nodes: `ca-infr-dev-003.my-cool-site.internal`, `ip-10-10-0-79` and `ca-infr-dev-002.my-cool-site.internal`. If I `kubectl log` a pod that is running on `ca-infr-dev-002.my-cool-site.internal` - i get logs.  If I run `kubectl log` on any of the other two pods running on either `ca-infr-dev-003.my-cool-site.internal` or `ip-10-10-0-79` I will get that 503 error with a proxy error referring to the ip of the node I am trying to reach.  So it will either be 10.10.0.79 or 10.10.0.35 in this case.

This is not limited to viewing logs from an agent.

**Comment by brandond** [comment]
Its because all three of your servers have the same external IP. That is going to make the agent very confused and is probably causing it to only set up a tunnel to one of them. Nodes must have unique internal AND external IPs.

**Comment by brandond** [comment]
The original work for this was done in https://github.com/k3s-io/k3s/pull/5382 although there was some additional configurability added in follow-on PRs (such as https://github.com/k3s-io/k3s/pull/5577). If you want to disable this, you can start the servers with `--egress-selector-mode=disabled`, although this will require the servers to have direct connectivity to all the agent ports.

**Comment by RumRogerz** [comment]
@brandond I owe you a beer.  Maybe several beers.  Addresses have been fixed- we also used `--egress-selector-mode=disabled` and like magic everything started working again.  Thank you so much for your assistance.
