### ISSUE TITLE
Fix OpenRC init script errors with sourcex

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#6739]
An awesome user fix for OpenRC init script! Testing recommendations in linked PR.

Related PR: https://github.com/k3s-io/k3s/pull/6614

**Comment by ShylajaDevadiga** [comment]
Installed k3s using commit id f19892c2d24f7a614bb6130d1c2e54077ecb1faf on **Alpine version 3.17, with OpenRC version 0.45.2**, installation went through successfully, no error seen with **source not found**  but I am seeing a new error with **sourcex not found**


<img width="943" alt="image" src="https://user-images.githubusercontent.com/56045581/213545915-9cf346b8-ca11-41cd-a001-8b2269f7722b.png">

<img width="455" alt="image" src="https://user-images.githubusercontent.com/56045581/213546228-10598ce1-6615-448e-9bf6-616dc945c05c.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/56045581/213545993-1856e0a2-7c26-4081-a930-dffbf84b0396.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/56045581/213545339-d912f300-66d0-4242-8c39-83eee6e74fb5.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/56045581/213545534-c369e9d6-7228-43c3-93ba-5c79a1db1674.png">

**Comment by brandond** [comment]
@vazhnov it appears that both alpine and devuan have the same OpenRC version, but one of them supports sourcex, while the other supports source. Do you have any suggestions on how to address this in a portable way?

**Comment by vazhnov** [comment]
@ShylajaDevadiga , please don't use screenshots for text information. It is hard to copypaste error messages or to find an error message in the project issues.

About no "source: not found" message: of course it is impossible to see such message now, because of change #6614.

Also it is useless to do `which sourcex` in `zsh`, while the init script uses shebang `#!/sbin/openrc-run`, this is why I took `sourcex` from [openrc-run.sh](https://github.com/OpenRC/openrc/blob/master/sh/openrc-run.sh.in).

@ShylajaDevadiga, please dig into the root cause. Maybe we should ask OpenRC developers to help us to find the correct way.

As an alternative, there is also #5900.

**Comment by brandond** [comment]
Yeah, maybe just dot-sourcing things is better than relying on source or sourcex. sourcex is just a wrapper around dot-sourcing but it appears that some distros don't include it in their openrc-run?

**Comment by cwayne18** [comment]
> @ShylajaDevadiga , please don't use screenshots for text information. It is hard to copypaste error messages or to find an error message in the project issues.
> 
> About no "source: not found" message: of course it is impossible to see such message now, because of change #6614.
> 
> Also it is useless to do `which sourcex` in `zsh`, while the init script uses shebang `#!/sbin/openrc-run`, this is why I took `sourcex` from [openrc-run.sh](https://github.com/OpenRC/openrc/blob/master/sh/openrc-run.sh.in).
> 
> @ShylajaDevadiga, please dig into the root cause. Maybe we should ask OpenRC developers to help us to find the correct way.
> 
> As an alternative, there is also #5900.

While we're happy to review and merge PRs to add support for this, we don't have the time/resources to have our team root cause issues with openrc. If we can get this sorted that's lovely, but there are many high priority tasks @ShylajaDevadiga has on her plate.

**Comment by c33s** [comment]
i also got the error on alpine :
```
[INFO]  openrc: Starting k3s
 * Caching service dependencies ...
/lib/rc/sh/gendepends.sh: /etc/init.d/k3s: line 26: sourcex: not found
/lib/rc/sh/gendepends.sh: /etc/init.d/k3s: line 27: sourcex: not found                                                                                                                                                                 [ ok ]
 * Starting k3s ...                            
```

```
service k3s stop
/etc/init.d/k3s: line 26: sourcex: not found
 /etc/init.d/k3s: line 27: sourcex: not found  
```
why not use `.` for sourcing? 

according shellcheck it is the prefered way

> In POSIX sh, 'source' in place of '.' is undefined.
> See SC2039. 
> https://github.com/koalaman/shellcheck/wiki/SC2039

replacing `sourcex` with `.` in the `k3s` script fixes the problem for me

**Comment by brandond** [comment]
openrc doesn't use sh or bash, it has its own interpreter, which is the cause of all this weirdness to begin with. Using `.` instead of either does look to be the most likely to work across distros.

**Comment by AndrewBCN** [comment]
Hi,
I would just like to confirm that I am getting the same error and applied the same solution as c33s above : after installing k3s on Alpine Linux 3.17, I am getting the error "... sourcex: not found" when executing the /etc/init.d/k3s init script. Replacing 'sourcex' with '.' fixes the problem

Alpine Linux 3.17, v1.25.7+k3s1

**Comment by shoblingr** [comment]
Waiting for an linux alpine fix, we can use this command to fix it during install:
`curl https://get.k3s.io | sed 's/sourcex/\./g' | sh`

**Comment by brandonros** [comment]
curl https://get.k3s.io | sed 's/sourcex/\./g' | sed 's/sudo/doas/g' | sh

I had to do this for Alpine (which seems to have strategically gotten rid of sudo to the point where you can't `apk add sudo` as of 3.17 and need to use `doas` instead).

**Comment by shoblingr** [comment]
you can install sudo from 'community' repo, it is still available for 3.17.

**Comment by pr0ton11** [comment]
There is a sudo-doas-shim as well that you can use

**Comment by aganesh-suse** [comment]
using **_alpine 3.17.3 standard iso x86_64_**, created a vm on virtualbox. 
inbuilt **_openrc_** **_version was 0.45.2_**
added extra packages with "**_apk add curl_**"
was able to install k3s and the service, node, pods were up and running without any issues. 
Command executed:
```
export install_from="https://get.k3s.io/"
export K3S_TOKEN="nodetoken"
export version="v1.27.1-rc1+k3s1"
curl -fL $install_from | INSTALL_K3S_VERSION=$version K3S_TOKEN=$K3S_TOKEN K3S_KUBECONFIG_MODE="644" sh -s -
```
![Screenshot 2023-05-02 at 1 34 49 PM](https://user-images.githubusercontent.com/129900588/235781057-2a4ebd4b-d88d-4a28-bf0f-d17ecbdaafae.png)
