### ISSUE TITLE
[Doc] Containerd version not correct in v1.22.17+k3s1 release notes

### ISSUE THREAD

**Issue by iElephant** [k3s-io/k3s#6745]
**Environmental Info:**
K3s Version: 1.22.17+k3s1

**Describe the bug:**

In the Embedded Component version table in 1.22.17+k3s1 release notes, it shows Containerd version 1.6.9, however in the changes notes section and on the node, the containerd version should be v1.5.16-k3s1-1-22

See release notes: https://github.com/k3s-io/k3s/releases/tag/v1.22.17+k3s1

**Comment by brandond** [comment]
cc @nikolaishields

**Comment by caroline-suse-rancher** [comment]
@briandowns would you mind taking a look at this small release note issue?

**Comment by dereknola** [comment]
Fixed
