### ISSUE TITLE
Unknown flag warnings in config.yaml

### ISSUE THREAD

**Issue by reefland** [k3s-io/k3s#6756]
**Environmental Info:**
K3s Version: 
```
$ k3s -v
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```

Node(s) CPU architecture, OS, and Version: 
all nodes Ubuntu 22.04 bare metal.
```
$ uname -a
Linux k3s01 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
$ sudo kubectl get nodes
NAME    STATUS   ROLES                       AGE    VERSION
k3s01   Ready    control-plane,etcd,master   288d   v1.25.4+k3s1
k3s02   Ready    control-plane,etcd,master   262d   v1.25.4+k3s1
k3s03   Ready    control-plane,etcd,master   269d   v1.25.4+k3s1
k3s04   Ready    worker                      35d    v1.25.4+k3s1
k3s05   Ready    worker                      35d    v1.25.4+k3s1
```

**Describe the bug:**
Warning messaged about unknown flags within `config.yaml` such as:

```
$ sudo k3s etcd-snapshot ls

WARN[0000] Unknown flag --etcd-expose-metrics found in config.yaml, skipping 
WARN[0000] Unknown flag --kube-controller-manager-arg found in config.yaml, skipping 
WARN[0000] Unknown flag --kube-proxy-arg found in config.yaml, skipping 
WARN[0000] Unknown flag --kube-scheduler-arg found in config.yaml, skipping 
...
```

Trying to resolve the warning message. These entries were added a while back for Prometheus installation, which is working fine.  The documentation on using the `config.yaml` is pretty-thin, but based on <https://docs.k3s.io/installation/configuration#configuration-file> what I have below appears to be formatted correctly.

```
$ cat /etc/rancher/k3s/config.yaml
---
etcd-expose-metrics: true
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
```

Based on <https://docs.k3s.io/reference/server-config> these are valid flags.

I don't have an issue of something not working (that I'm aware of) just trying to understand the reason for the warning messages.

**Comment by brandond** [comment]
The config file contents are converted to CLI flags, some of which are not valid for the command you're currently running. It's just warning you about that.

**Comment by reefland** [comment]
Thank you! Appreciate the prompt response.
