### ISSUE TITLE
K3s Startup Error

### ISSUE THREAD

**Issue by joesan** [k3s-io/k3s#6771]
**Environmental Info:**
K3s Version: 

```
joesan@m1:/etc/systemd/system$ k3s -version
k3s version v1.26.0+k3s1 (fae88176)
go version go1.19.4
```

Node(s) CPU architecture, OS, and Version: 

```
joesan@m1:/etc/systemd/system$ uname -a
Linux m1 5.15.0-1012-raspi #14-Ubuntu SMP PREEMPT Fri Jun 24 13:10:28 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:

Just one master node

**Describe the bug:**

When I ran:

`$sudo k3s server`

I ran into the following error:

```
joesan@m1:~$ sudo k3s server --debug
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/86a8c46cd5fe617d1c1c90d80222fa4b7e04e7da9b3caace8af4daf90fc5a699 
DEBU[0000] Running /var/lib/rancher/k3s/data/86a8c46cd5fe617d1c1c90d80222fa4b7e04e7da9b3caace8af4daf90fc5a699/bin/k3s-server [k3s server --debug] 
INFO[0001] Starting k3s v1.22.3+k3s1 (61a2aab2)         
INFO[0001] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
INFO[0001] Configuring database table schema and indexes, this may take a moment... 
INFO[0001] Database tables and indexes are up to date   
INFO[0001] Kine available at unix://kine.sock           
FATA[0001] starting kubernetes: preparing server: json: cannot unmarshal object into Go value of type []uint8 
```

**Comment by brandond** [comment]
I general I recommend against running k3s with sudo. Can you try a more recent version of K3s? You said you're using `k3s version v1.26.0+k3s1` but your log clearly shows `v1.22.3+k3s1`. I suspect you have another copy of k3s somewhere on this host, and you're running that instead of the version you meant to run - due to sudo not using the paths from your shell and instead finding an old copy that you've left in a bin directory somewhere.

**Comment by joesan** [comment]
Yes, you are right. There seems to be a stale version hanging on and causing issues. I was able to fix it, but upon running 

`$joesan@m1:~$ sudo k3s kubectl get nodes`

That thing hangs and does not come back with a response. Is there any other way to check the nodes?

**Comment by joesan** [comment]
I will close this. It stands resolevd for me!
