### ISSUE TITLE
From rke2 issue: Flannel with many nodes results in dropped routes

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#6777]
**Environmental Info:**
RKE2 Version: 1.24.6

**Describe the bug:**

A bug has been identified in flannel that relates to environments on VXLAN that introduce many nodes. There appear to be missing routes. See the related flannel issue:

- https://github.com/flannel-io/flannel/issues/958#issuecomment-920859275

**Additional context / logs:**

Related JIRA ticket and rke2 issue:

- https://jira.suse.com/SURE-5710
- https://github.com/rancher/rke2/issues/3811

**Comment by rancher-max** [comment]
## Validated using same steps mentioned in https://github.com/k3s-io/k3s/issues/6924#issuecomment-1428264118, using commit https://github.com/k3s-io/k3s/commit/74ed4bef6191f74b9f9d178c03c3d5da729c7003 from `release-1.24` branch

### Results
- Flannel using the expected version
```
$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.21.1-k3s1.23 (linux/amd64) commit HEAD built on 2023-02-14T22:19:35Z
```
- Confirmed networking resources deploy successfully and are functional
- **Note that I was not able to reproduce the original issue, but this flannel version should be sufficient to fix it so I am calling this done.**
