### ISSUE TITLE
Flannel related log message to k3s.log every 5 seconds

### ISSUE THREAD

**Issue by rubin55** [k3s-io/k3s#6785]
**Environmental Info:**
K3s Version: 
```
k3s version v1.25.5+k3s2 (de654222)
go version go1.19.4
```
Node(s) CPU architecture, OS, and Version: 
```
Linux XENON 5.15.89-0-lts #1-Alpine SMP Thu, 19 Jan 2023 09:11:56 +0000 x86_64 Linux
```
Cluster Configuration:
```
single node
```
**Describe the bug:**
Every 5 seconds the following log message appears in `/var/log/k3s.log`:
```
time="2023-01-19T22:04:20+01:00" level=info msg="Using CNI configuration file /var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist"
```
**Steps To Reproduce:**
```
curl -sfL https://get.k3s.io | sh -s - --docker --kube-apiserver-arg enable-aggregator-routing=true --disable traefik
```
**Expected behavior:**
No log-spam!

**Actual behavior:**
Much log spam!

**Additional context / logs:**
N/A.

**Comment by brandond** [comment]
This appears to come from cri-dockerd. The sync function is called every 5 seconds and logs the message at info level: 
* https://github.com/Mirantis/cri-dockerd/blob/ede58f3a92e114a9c21d211936be2902f7a6bd62/network/cni/cni.go#L240-L241
* https://github.com/Mirantis/cri-dockerd/blob/ede58f3a92e114a9c21d211936be2902f7a6bd62/network/cni/cni.go#L213

If you find it irritating I would suggest opening an issue with that project. If they fix it, we can pull it in to k3s.

**Comment by brandond** [comment]
Note that in the short term or if Mirantis declines to change that log level, you can set `CRIDOCKERD_LOG_LEVEL=error` in the K3s service environment, and it will stop outputting info-level logs.
