### ISSUE TITLE
Installation of k3s fails on Tumbleweed

### ISSUE THREAD

**Issue by grisu48** [k3s-io/k3s#6790]
**Environmental Info:**
K3s Version: v1.25.5+k3s2

Node(s) CPU architecture, OS, and Version: 

```
Linux tumbleweed 6.1.6-1-default #1 SMP PREEMPT_DYNAMIC Mon Jan 16 05:11:14 UTC 2023 (573f4a9) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration: None

**Describe the bug:**

Installation of k3s via the get.k3s.io script fails on openSUSE Tumbleweed:

```
tumbleweed:~ # curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -s -
[INFO]  Finding release for channel stable
[INFO]  Using v1.25.5+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.5+k3s2/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[ERROR]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-1.2-2.el8.noarch.rpm
```

This is on a system with SELinux installed and set to ENFORCE. Changing SELinux to permissive doesn't change the outcome.

**Steps To Reproduce:**

* `# curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true sh -s -`

Installed K3s: -

**Expected behavior:**

* k3s gets installed

**Actual behavior:**

* Installer terminates with an error

**Additional context / logs:**

**Comment by grisu48** [comment]
The issue might be located in https://github.com/k3s-io/k3s/blob/master/install.sh#L469, where the detection of the SUSE Distribution fails and we end up in the EL8 branch (credits to @Vogtinator for the discovery)

**Comment by Vogtinator** [comment]
Yes, https://github.com/k3s-io/k3s/blob/f10af367c3c96863c081ada4018e94e085c9404d/install.sh#L469 is broken, that only works if `suse` is the first entry, but it's not.

**Comment by VestigeJ** [comment]
I just tried reproducing this with a reverted copy of the install.sh script but the install worked correctly - that being said the new install.sh seems to work correctly as well.


previous install.sh os-release check

![Screenshot 2023-02-08 at 1 13 19 PM](https://user-images.githubusercontent.com/8961630/217652138-48e0d9a6-7c2d-4f13-9526-12254827ff91.png)


latest install.sh

![Screenshot 2023-02-08 at 1 15 54 PM](https://user-images.githubusercontent.com/8961630/217652615-c7f605e0-0115-4ea3-b094-1187bf596072.png)
