### ISSUE TITLE
[release-1.24] Update cri-dockerd

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6796]
Backport: 
* #6794

**Comment by est-suse** [comment]
Validated using commit id 607ccbd49dbb3534ffbba32ec8421cab7ed8fc17  on release-1.24 branch. cri-dockerd version is bumped as expected.

From the logs:
```
sudo journalctl -xeu k3s | grep "cri-dockerd version"
Feb 10 16:32:02 ip-172-31-39-20 k3s[18881]: time="2023-02-10T16:32:02Z" level=info msg="cri-dockerd version v0.3.2-0.20230123224751-84abd1adca2f (HEAD)"
```

Created a cluster using one server one agent, confirmed nodes are up and pods are in running state

Install docker on the server node as well as the agent node
Install server passing --docker flag

```
 curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=607ccbd49dbb3534ffbba32ec8421cab7ed8fc17 sh -s - server --docker
```

```
```
