### ISSUE TITLE
K3s auto restart

### ISSUE THREAD

**Issue by xinmans** [k3s-io/k3s#6802]
**Environmental Info:**
K3s Version: 

k3s version v1.25.3+k3s-9afcd6b9-dirty (9afcd6b9)
go version go1.19.1

Node(s) CPU architecture, OS, and Version: 

Linux truenas 5.15.79+truenas #1 SMP Tue Dec 13 12:40:04 UTC 2022 x86_64 GNU/Linux

Cluster Configuration:

1 server
**Describe the bug:**

When I run sudo systemctl restart k3s,k3s keep auto-restart, all pods pending...

**Steps To Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

xinmans@truenas:~$ sudo systemctl status k3s
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/lib/systemd/system/k3s.service; disabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-01-22 17:01:55 CST;>
       Docs: https://k3s.io
    Process: 45652 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 45653 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 45654 ExecStart=/usr/local/bin/k3s server --flannel-backend=none --disable=traef>
   Main PID: 45654 (code=exited, status=1/FAILURE)
        CPU: 8.231s

cat k3s.log  |tail -20
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.471263   41251 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.471271   41251 crd_finalizer.go:266] Starting CRDFinalizer
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.471307   41251 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/mnt/tank/ix-applications/k3s/server/tls/client-ca.crt"
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.471535   41251 dynamic_cafile_content.go:157] "Starting controller" name="request-header::/mnt/tank/ix-applications/k3s/server/tls/request-header-ca.crt"
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.470758   41251 autoregister_controller.go:141] Starting autoregister controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.471788   41251 cache.go:32] Waiting for caches to sync for autoregister controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.470121   41251 customresource_discovery_controller.go:209] Starting DiscoveryController
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.469883   41251 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/mnt/tank/ix-applications/k3s/server/tls/client-ca.crt"
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.474436   41251 crdregistration_controller.go:111] Starting crd-autoregister controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.474460   41251 shared_informer.go:255] Waiting for caches to sync for crd-autoregister
Jan 22 16:55:26 truenas k3s[41251]: E0122 16:55:26.666885   41251 controller.go:163] Error removing old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.671000   41251 shared_informer.go:262] Caches are synced for cluster_authentication_trust_controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.671131   41251 cache.go:39] Caches are synced for APIServiceRegistrationController controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.676785   41251 cache.go:39] Caches are synced for AvailableConditionController controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.677421   41251 cache.go:39] Caches are synced for autoregister controller
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.705932   41251 apf_controller.go:305] Running API Priority and Fairness config worker
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.730416   41251 shared_informer.go:262] Caches are synced for crd-autoregister
Jan 22 16:55:26 truenas k3s[41251]: I0122 16:55:26.751886   41251 shared_informer.go:262] Caches are synced for node_authorizer
Jan 22 16:55:27 truenas k3s[41251]: I0122 16:55:27.271764   41251 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
Jan 22 16:55:27 truenas k3s[41251]: I0122 16:55:27.698793   41251 storage_scheduling.go:111] all system priority classes are created successfully or already exist.

**Comment by brandond** [comment]
Please attach the **complete** k3s logs from journald. It's hard to tell from the short snippet you included what's going on.

I also note that you are using a custom truenas build of K3s; I am going to close this out with a reference to https://github.com/k3s-io/k3s/issues/6318#issuecomment-1287466616
