### ISSUE TITLE
After restoring from snapshot, existing nodes lost connection to the cluster

### ISSUE THREAD

**Issue by ulzii0819** [k3s-io/k3s#6806]
**Environmental Info:**
K3s Version: 
v1.25.4+k3s1

Node(s) CPU architecture, OS, and Version: 
AMD64, Oracle Linux 9

Cluster Configuration:
2 master nodes

**Describe the bug:**
Our cluster was not responding after the reboot of one of the master node. So we ran the command 'k3s server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot....'.
After that, we tried to restart the second node, but it never came up and printer out the below log : 
: {"level":"warn","ts":"2023-01-23T14:19:01.151+0100","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"12ade19b02afc710","remote-peer-cluster-id":"96831dd7fb68f941","local-member-id":"a2ecd5a5473b846a","local-member-cluster-id":"f3896440d3d0845","error":"cluster ID mismatch"}

It seems, after restoring a cluster, it came up with a new cluster id. The second node is now out of the cluster and don't know how to join again. I can remove the node and rejoin. But not sure if it cause data loss or something undesired behavior. 
**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by ulzii0819** [comment]
After running restore on a first server successfully, tried to rejoin second node. Of course, made a backup of data_dir and removed. Then I ran command "k3s server -s https://api_server:6443 -t ${SERVER_NODE_TOKEN}
After that, cluster became failed again.

**Comment by brandond** [comment]
If you're getting ID mismatch errors on the other nodes, you have datastore files left behind. Please ensure that you have stopped K3s on all the server nodes before resetting the first node, and that you have removed the datastore files from the secondaries before restarting them.

**Comment by ulzii0819** [comment]
yes, I have stopped k3s service on all the nodes. Here's what I did in order : 
1. Stopped k3s service on all the nodes.
2. Removed the datastore files on the second nodes
3. Restored the first node with "k3s server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-xxx" command
4. restarted k3s service on the first node.
5. restarted k3s service on the first node. 
After restarting the second node both nodes became unreachable and prints an error : 
Error: failed to create listener: failed to listen on 127.0.0.1:6444: listen tcp 127.0.0.1:6444: bind: address already in use
level=fatal msg="apiserver exited: failed to create listener: failed to listen on 127.0.0.1:6444: listen tcp 127.0.0.1:6444: bind: address already in use

**Comment by brandond** [comment]
> After restarting the second node both nodes became unreachable and prints an error :
`Error: failed to create listener: failed to listen on 127.0.0.1:6444: listen tcp 127.0.0.1:6444: bind: address already in use
level=fatal msg="apiserver exited: failed to create listener: failed to listen on 127.0.0.1:6444: listen tcp 127.0.0.1:6444: bind: address already in use`

You are somehow running multiple k3s processes at the same time.

**Comment by ulzii0819** [comment]
Thank you @brandond . I found that when I started k3s with systemctl start k3s command it was starting k3s-agent service. So I used curl -sfL https://get.k3s.io | K3S_TOKEN='' sh -s server --server https:server:6444 to start the service as fresh.

**Comment by brandond** [comment]
Did that resolve the issue for you?

**Comment by ulzii0819** [comment]
Yes, issue has been resolved with the below steps : 
1. Restarted K3S service on the first node.
2. Stopped all services on secondary node using 'k3s-killall.sh' script
3. Rejoined the second node using 'curl -sfL https://get.k3s.io/ | K3S_TOKEN='' sh -s server --server https:server:6444'

**Comment by brandond** [comment]
Just to be clear, you're re-running the installer every time, instead of just stopping/starting the service?
