### ISSUE TITLE
Failure to reencrypt concurrently modified secret during secrets encryption

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6824]
* K3s tracking issue for https://github.com/rancher/rke2/issues/3801

Occasionally, `k3s secrets-encrypt reencrypt` will fail to update a secret as it may be modified while the secrets are being iterated over, which cause secrets encryption to fail.

The following error is recorded: `Failed to reencrypted secret: Operation cannot be fulfilled on secrets "serving-cert": the object has been modified; please apply your changes to the latest version and try again`.

I suspect that a similar error might occur if a secret is deleted, or deleted and recreated, after the secret list is stored in memory but before the secret is processed.

**Comment by bguzman-3pillar** [comment]
### Validated on 21560155
```
$ k3s -v
k3s version v1.26.1+k3s-21560155 (21560155)
go version go1.19.5
```
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Ubuntu
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: testing
cluster-init: true
secrets-encryption: true
```
  
## Testing Steps

1. Copy config.yaml `$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s`
2. Install k3s
3. Ensure cluster is up and running
4. Install etcdctl
5. Generate large number of secrets to reencrypt: `kubectl create namespace test-encryption-key-rotation && for i in {1..1000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done
Follow the secrets-encryption process`
6. Follow the secrets-encryption process
```
sudo k3s secrets-encrypt status
sudo k3s secrets-encrypt prepare
sudo systemctl restart k3s
sudo k3s secrets-encrypt rotate
sudo systemctl restart k3s
sudo k3s secrets-encrypt reencrypt
sudo systemctl restart k3s
```

7. While reencryption is active, edit any "high number" secret:


 
 
**Validation Results:**

- Secrets got encrypted successfully
- Observed no error in logs
```
$ sudo k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey

$ sudo k3s secrets-encrypt prepare
prepare completed successfully
$ sudo systemctl restart k3s
$ sudo k3s secrets-encrypt rotate
rotate completed successfully
$ sudo systemctl restart k3s
$ sudo k3s secrets-encrypt reencrypt
reencryption started
$ sudo systemctl restart k3s
```
```
$ sudo journalctl -xeu k3s | grep 'failed to reencrypted secret'
$ 
$ sudo journalctl -xeu k3s | grep 'failed to update secret'
$ 
$ 
```
