### ISSUE TITLE
kubectl logs not working because of incorrect external IP (certificate error)

### ISSUE THREAD

**Issue by mcordova1967** [k3s-io/k3s#6845]
**Environmental Info:**
K3s Version: 

k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5

Node(s) CPU architecture, OS, and Version: 

Linux cppserver 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Multipass Ubuntu 22.04 VM running on Windows, the VM IP on eth0 may change from time to time, after restarts or power off of host machine.

Cluster Configuration:

Single node installation, installed with this CMD:
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

**Describe the bug:**

Suddenly kubectl logs reported an error when I tried to use it to print a Pod's logs

kubectl logs cppserver-deployment-86cd66bf7-snjgd
Error from server: Get "https://172.23.180.205:10250/containerLogs/default/cppserver-deployment-86cd66bf7-snjgd/cppserver": x509: certificate is valid for 127.0.0.1, 172.23.190.100, not 172.23.180.205

The thing is 172.23.180.205 is not the IP of the VM, but it is listed as the external IP of the LoadBalancer service:

kube-system   traefik             LoadBalancer   10.43.101.152   172.23.180.205   80:32693/TCP,443:30271/TCP   9s

VM's "ip a" won't print this IP, it prints 172.23.190.100 which is the eth0 IP, access from external clients to the containers works OK via Ingress despite the LoadBalancer displaying this IP, I have not noticed this invalid IP until I got the error running kubectl logs, then I searched for this IP and it is not being used by the VM at all.

**Steps To Reproduce:**

I am not sure, first time I see this error after several days playing around with K3S a lot, this is a multipass Ubuntu VM running on Windows, the VM IP on eth0 may change from time to time, after restarts or power off of host machine.

- Installed K3s: 
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5
installed using: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

**Expected behavior:**

I expected it to print the Pod's logs, as usual, it has been working without problems until today

**Actual behavior:**

Error from server: Get "https://172.23.180.205:10250/containerLogs/default/cppserver-deployment-86cd66bf7-snjgd/cppserver": x509: certificate is valid for 127.0.0.1, 172.23.190.100, not 172.23.180.205

The invalid IP in cuestion is also listed as the external IP of the traefik service (LoadBalancer)

I know that I can quickly reinstall everything with K3S, that's great, but I would like to learn how to solve this problem if it ever happens in production. Thank you.

**Additional context / logs:**

ip a | grep eth0

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.23.190.100/20 metric 100 brd 172.23.191.255 scope global dynamic eth0

**Comment by brandond** [comment]
It sounds like the node's address changed after K3s started. Kubernetes nodes should have static IPs addresses, or have a stable DHCP lease that will not change for the duration of the node's presence in the cluster.

**Comment by mcordova1967** [comment]
Yes, I think that was the cause, because Multipass may change the virtual machine IP from time to time, I could not solve it by any means, so I uninstalled and reinstalled it in a few minutes.

k3s is great, I was finally able to deploy on Kubernetes thanks to k3s, thank you to all the people involved!
