### ISSUE TITLE
[Release-1.24] K3s crashes because it doesn't wait for CRI-dockerd to be ready

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#6856]
Backport tracker for https://github.com/k3s-io/k3s/issues/6811 to release-1.24

**Comment by mdrahman-suse** [comment]
### Validated on branch release-1.24 with commit c9f450b314898d341177ef70252fadb82861e1a5
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-34-160 5.14.21-150400.22-default #1 SMP PREEMPT_DYNAMIC Wed May 11 06:57:18 UTC 2022 (49db222) x86_64 x86_64 x86_64 GNU/Linux
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```
 
*Cluster Configuration:*

```
1 server, 1 agent
```
 
*Config.yaml:*

```
# server
write-kubeconfig-mode: 644
token: summer
cluster-init: true
docker: true

# agent
token: summer
server: https://<serverip>:6443
docker: true
```

NOTE: Ensure docker is installed and running on the nodes
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
- For replication: `curl -sfL https://get.k3s.io | sudo INSTALL_K3S_VERSION=v1.24.10+k3s1 sh -`
- For validation: `curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT=c9f450b314898d341177ef70252fadb82861e1a5 sh -`
3. Ensure cluster is up and running
4. Check agent logs for errors
 
 
**Replication Results:**
- k3s version used for replication:

```
v1.24.10+k3s1
```
 

Observed error on agent log
```
$ sudo journalctl -xeu k3s-agent.service | grep "Error while dialing dial"
Feb 08 20:53:04 ip-xxx-xx-xx-160 k3s[9898]: Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/k3s/cri-dockerd/cri-dockerd.sock: connect: no such file or directory"
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.24.10+k3s-c9f450b3 (c9f450b3)
go version go1.19.5
```
 

No error observed on the logs
```
$ sudo journalctl -xeu k3s-agent.service | grep "Error while dialing dial"
$
```
Cluster was up and running
