### ISSUE TITLE
The k3s quick start installer hangs indefinitely when adding an agent

### ISSUE THREAD

**Issue by emchristiansen** [k3s-io/k3s#6879]
I have an Ubuntu 22.04.1 server (already set up), and I'm trying to add an agent on another Ubuntu 22.0.4.1.
Here's what I see:

![Screenshot 2023-02-03 at 11 35 56 AM](https://user-images.githubusercontent.com/225668/216670288-b026eb23-eb71-449a-a7aa-7b1070a28a2a.png)

The agent start script just hangs forever, and doesn't indicate where I might find logs explaining what's happening.

BTW, both the server and agent machines are within a Tailscale VPN.

**Comment by brandond** [comment]
> doesn't indicate where I might find logs explaining what's happening.

As the log says it's starting a systemd service unit, so you can look in journald for logs from k3s-agent.

**Comment by Napuu** [comment]
I had this exact problem. `systemctl status k3s-agent` showed that agent was trying to access master node with wrong ip. I fixed it by adding `--node-external-ip` flag to my  `/etc/systemd/system/k3s.service` at master node.

ExecStart before:
```
ExecStart=/usr/local/bin/k3s \
    server \
```

ExecStart after:
```
ExecStart=/usr/local/bin/k3s \
    server --node-external-ip <master_node_tailscale_ip> \
```

And after that:
```
sudo systemctl daemon-reload
sudo systemctl restart k3s
```

(I think it is also possible to set this ip with some K3S_xxx env variable while installing cluster)

**Comment by caroline-suse-rancher** [comment]
Closing due to staleness
