### ISSUE TITLE
install script doesn't complete installation due to curl (60) SSL certificate problem

### ISSUE THREAD

**Issue by sp-yduck** [k3s-io/k3s#6882]
**Environmental Info:**
K3s Version: N/A

Node(s) CPU architecture, OS, and Version: Linux lima-k3s 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: N/A

**Describe the bug:**
[Install script](https://docs.k3s.io/quick-start#install-script) : `curl -sfL https://get.k3s.io/ | sh -` doesn't work properly
error log : 
```
[INFO]  Finding release for channel stable
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[INFO]  Using v1.25.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.6+k3s1/sha256sum-amd64.txt
```

**Steps To Reproduce:**

`curl -sfL https://get.k3s.io/ | sh -`

**Expected behavior:**

k3s installation success

**Actual behavior:**
exited status 60

**Additional context / logs:**

**Comment by brandond** [comment]
I'm not able to reproduce this. Our channel server at `https://update.k3s.io/v1-release/channels` is not using a self-signed certificate. Do you perhaps have some proxy server or firewall in your environment that is interfering with your connection?
