### ISSUE TITLE
Release for PPC64LE

### ISSUE THREAD

**Issue by NeilHanlon** [k3s-io/k3s#6886]
**Is your feature request related to a problem? Please describe.**

k3s builds and runs on ppc64le. I have compiled it on several ppc machines and have had it running in clusters for over a year.

**Describe the solution you'd like**

k3s should build and release artifacts for the ppc64le architecture.

**Describe alternatives you've considered**

#5608 was closed due to lack of resources to build and test k3s on ppc64le. I can confirm this architecture works and am happy to help provide build and test resources

**Additional context**

I have access to ppc64le hardware to build and test on (Though cross compiling with qemu-static would likely be more effective).

**Comment by caroline-suse-rancher** [comment]
Closing as we don't have this in the plans for support at this point in time.
