### ISSUE TITLE
I need information about k3s minimum number of master nodes required to be up in HA if k3s cluster have n number of master nodes available.

### ISSUE THREAD

**Issue by dsolanki28** [k3s-io/k3s#6913]
I have 3 k3s Master nodes HA cluster. If I stopped/crashed two master nodes then cluster gets down or get inaccessible. If I increase the number of master nodes to 6 and if I stopped/crashed 3 master nodes then cluster becomes inaccessible even after 3 other master nodes are up. 

Could you please confirm if it is an expected behavior ?

**Comment by brandond** [comment]
https://etcd.io/docs/v3.3/faq/#what-is-failure-tolerance
