### ISSUE TITLE
controlling-servicelb-node-selection doesn't work 

### ISSUE THREAD

**Issue by workerus** [k3s-io/k3s#6927]
**Environmental Info:**
K3s Version: 

k3s -v
k3s version v1.22.17+k3s1 (3ed243df)
go version go1.16.15

Node(s) CPU architecture, OS, and Version: 

uname -a
Linux node-10-210-167-4 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

1 master node and 4 worker nodes
**Describe the bug:**

I follow this guide but it doesn't work https://docs.k3s.io/networking#controlling-servicelb-node-selection
all worker nodes have label configured svccontroller.k3s.cattle.io/enablelb=true
Worker nodes are labeled : 
node 1 and 2 have label svccontroller.k3s.cattle.io/lbpool=pool1 
node 3 and 4 have label svccontroller.k3s.cattle.io/lbpool=pool2

both services are labeled also
nginx1 has label svccontroller.k3s.cattle.io/lbpool=pool1
nginx2 has label svccontroller.k3s.cattle.io/lbpool=pool2

**Steps To Reproduce:**

Please follow this: https://docs.k3s.io/networking#controlling-servicelb-node-selection 
- Installed K3s: 
Regular installation no customization.
**Expected behavior:**

service nginx1 pods should run only on node 1 and 2
service nginx2 pods should run only on node 3 and 4

**Actual behavior:**

kubectl get pod -n default -owide |grep svc
The output displaying on each worker node 2 service pods while it's expected service pods nginx1 to run only on node 1 and 2 and service pods nginx2 to run only on node 3 and 4. It looks like this label svccontroller.k3s.cattle.io/enablelb=true is working since these services pods not running on master as expected but these labels being ignored  svccontroller.k3s.cattle.io/lbpool=pool1 and  svccontroller.k3s.cattle.io/lbpool=pool2

**Additional context / logs:**

**Comment by brandond** [comment]
Can you `kubectl get -o yaml` the nodes, labeled services, and the daemonsets for those services?

**Comment by workerus** [comment]
Please see attached files.
[node.txt](https://github.com/k3s-io/k3s/files/10700223/node.txt)
[services.txt](https://github.com/k3s-io/k3s/files/10700226/services.txt)
[daemonset.txt](https://github.com/k3s-io/k3s/files/10700227/daemonset.txt)

**Comment by brandond** [comment]
Ah, my apologies. I see that you're still on 1.22 which doesn't have the lbpool functionality. Please upgrade to 1.23 or newer.

**Comment by workerus** [comment]
OK thank you Brandon!
