### ISSUE TITLE
k3s network configuration

### ISSUE THREAD

**Issue by titan85** [k3s-io/k3s#695]
who can help please?
I think is an easy question  but I can´t resolve my prolem
I´m using k3s while 2 weeks
I installed k3s and I have to change my network conf
SDN:
Cluster Network: IP .....
Service Network: IP.......
where and how can I change this ?
is in /etc/rancher/k3s/k3s.yaml?

**Comment by erikwilson** [comment]
The server will take flags to set the cluster and service cidr: https://rancher.com/docs/k3s/latest/en/installation/#server-options

**Comment by brandond** [comment]
Closing due to age.
