### ISSUE TITLE
[k3s-upgrade] fails on Alpine due to trying PPID

### ISSUE THREAD

**Issue by jeroenrnl** [k3s-io/k3s#6953]
**Environmental Info:**
K3s Version: 

k3s version v1.24.6+k3s1 (a8e0c66d)
go version go1.18.6

3s version v1.26.1+k3s1 (f10af367)
go version go1.19.5

but I've also seen it on other versions.
Node(s) CPU architecture, OS, and Version: 

Linux kube12.roosnl.com 5.15.88-0-virt #1-Alpine SMP Mon, 16 Jan 2023 09:39:56 +0000 x86_64 Linux

Cluster Configuration:

3 servers all control plane + etcd nodes
**Describe the bug:**

k3s-upgrade fails with the error
```
ha256sum: can't open '/hostsupervise-daemon': No such file or directory
```
but then ends with exit 0 anyway:
```
+ BIN_COUNT=1
+ '[' 1 '==' 1 ]
+ info 'Binary already been replaced'
+ echo '[INFO] ' 'Binary already been replaced'
+ exit 0
[INFO] Binary already been replaced
```
what happens is that is first succesfully identifies the k3s binary:
```
+ cat /host/proc/2130/cmdline
+ awk '{print $1}'
+ head -n 1
+ K3S_BIN_PATH=/usr/local/bin/k3s
```
but then tries to determine the binary of the PPID anyway:
```+ '[' 2129 '!=' 1 ]
+ cat /host/proc/2129/cmdline
+ awk '{print $1}'
+ head -n 1
+ K3S_BIN_PATH=supervise-daemon
```
and that ends up in a mess:
```
+ '[' 2130 '==' 1 ]
+ '[' -z supervise-daemon ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/hostsupervise-daemon
```
**Steps To Reproduce:**
Apply a plan, label nodes.

**Expected behavior:**

Working upgrade.
**Actual behavior:**

Failed upgrade
**Additional context / logs:**

Full output of process:
```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $2}'
+ K3S_PID=2130
+ ps -p 2130 -o 'ppid='
+ xargs
+ K3S_PPID=2129
+ '[' -z 2130 ]
+ info 'K3S binary is running with pid 2130'
+ echo '[INFO] ' 'K3S binary is running with pid 2130'
[INFO] K3S binary is running with pid 2130
+ cat /host/proc/2130/cmdline
+ awk '{print $1}'
+ head -n 1
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' 2129 '!=' 1 ]
+ cat /host/proc/2129/cmdline
+ awk '{print $1}'
+ head -n 1
+ K3S_BIN_PATH=supervise-daemon
+ '[' 2130 '==' 1 ]
+ '[' -z supervise-daemon ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/hostsupervise-daemon
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
[INFO] Comparing old and new binaries
+ sha256sum /opt/k3s /hostsupervise-daemon
+ cut '-d ' -f1
+ uniq
+ wc -l
s
ha256sum: can't open '/hostsupervise-daemon': No such file or directory
+ BIN_COUNT=1
+ '[' 1 '==' 1 ]
+ info 'Binary already been replaced'
+ echo '[INFO] ' 'Binary already been replaced'
+ exit 0
[INFO] Binary already been replaced
```
I have had success with simply removing the lines that try for the PPID:
```
-  if [ "$K3S_PPID" != "1" ]; then
-    K3S_BIN_PATH=$(cat /host/proc/${K3S_PPID}/cmdline | awk '{print $1}' | head -n 1)
-  fi
```
but these lines aren't there for nothing, so I suppose removing them will break the process on other machines. Would this be an option?
```
if [ -z "$K3S_BIN_PATH" -a "$K3S_PPID" != "1" ]; then
```
I can submit a patch if this could be the solution. I tested this on my system and that works.

**Comment by brandond** [comment]
I'm going to close this in favor of tracking it in https://github.com/k3s-io/k3s/issues/2007 - we need to make our pid search and the ppid check more robust.
