### ISSUE TITLE
Bump kine to v0.9.9 or newer

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6958]
Bump kine for small improvements:
* Bump module versions to resolve vulns by @brandond in https://github.com/k3s-io/kine/pull/155
* Increase COMPACT log messages to Info by @brandond in https://github.com/k3s-io/kine/pull/156

**Comment by mdrahman-suse** [comment]
The version has been added in go.mod: https://github.com/k3s-io/k3s/blob/master/go.mod#L111
