### ISSUE TITLE
mount directory to container's rootfs error, cause pod suck CrashLoopBackOff，

### ISSUE THREAD

**Issue by BYTZJB** [k3s-io/k3s#6961]
**Environmental Info:**
K3s Version: 
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5
----
cgroupV2

`note: other version, like v1.26.0+k3s1 has same problem`
Node(s) CPU architecture, OS, and Version: 
Linux testnode1 6.0.12-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
```shell
  containerStatuses:
  - containerID: containerd://feb40e326c1e89f8c7a503ca7932fb67d4f6c689d6710e58c982259d23a30126
    image: bumblebee:test
    imageID: portus.in.chaitin.net/beehive/bumblebee@sha256:5309e8d8d6765975f5e26d13ce5868bc270b01b141a51345bb777b9c859be8a9
    lastState:
      terminated:
        containerID: containerd://feb40e326c1e89f8c7a503ca7932fb67d4f6c689d6710e58c982259d23a30126
        exitCode: 128
        finishedAt: "2023-02-15T07:51:46Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          error during container init: error mounting "/var/lib/kubelet/pods/9fb595e2-4a29-4c8e-baba-05b0decd3ce1/etc-hosts"
          to rootfs at "/etc/hosts": open /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/feb40e326c1e89f8c7a503ca7932fb67d4f6c689d6710e58c982259d23a30126/rootfs/etc/hosts:
          no such file or directory: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
    name: manager
    ready: false
    restartCount: 2
    started: false
    state:
      waiting:
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          error during container init: error mounting "/var/lib/kubelet/pods/9fb595e2-4a29-4c8e-baba-05b0decd3ce1/etc-hosts"
          to rootfs at "/etc/hosts": open /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/feb40e326c1e89f8c7a503ca7932fb67d4f6c689d6710e58c982259d23a30126/rootfs/etc/hosts:
          no such file or directory: unknown'
        reason: RunContainerError

```

**Steps To Reproduce:**

- Installed K3s: 
`INSTALL_K3S_MIRROR=cn INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" ./k3s-install.sh`
- installed calico
- helm install some package (the bumblebee:latest image is self build image，i think unrelated to the problem。

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
This would appear to be Fedora Core 35, is that correct? Do you have selinux enabled on this node? Can you attach the containerd.log file, as well as the complete k3s log from journald?

**Comment by BYTZJB** [comment]
> This would appear to be Fedora Core 35, is that correct? Do you have selinux enabled on this node? Can you attach the containerd.log file, as well as the complete k3s log from journald?

yes, the linux os is  Fedora 35。
this problem may be caused by our other pods, the pod mount node cgroup path and did some things。
so i close this problem until i exclude  the pod's effect。
