### ISSUE TITLE
[Release 1.23] Update flannel to v0.21.1

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#6963]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Backport for #6884

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
## Validated using same steps mentioned in https://github.com/k3s-io/k3s/issues/6924#issuecomment-1428264118, using commit https://github.com/k3s-io/k3s/commit/bbd7fecf5881094a68b2821e51129001e5ccc899 from `release-1.23` branch

### Results
- Flannel using the expected version
```
$ /var/lib/rancher/k3s/data/*/bin/flannel
CNI Plugin flannel version v0.21.1-k3s1.23 (linux/amd64) commit bbd7fecf5881094a68b2821e51129001e5ccc899 built on 2023-02-15T17:19:53Z
```
- Confirmed networking resources deploy successfully and are functional
