### ISSUE TITLE
High CPU usage by k3s server. Profiling k3s shows: k8s.io/apiserver/pkg/util/flowcontrol

### ISSUE THREAD

**Issue by jetm** [k3s-io/k3s#6966]
**Environmental Info:**
K3s Version: 

```
$ k3s -v
k3s version v1.24.7+k3s1+gite3c9d859e870c460d966d3ef140aa1815c41a3ac (e3c9d859)
go version go1.19.4
```

Node(s) CPU architecture, OS, and Version: 

```
Linux trs-qemuarm64 5.15.87-yocto-standard #1 SMP PREEMPT Fri Jan 13 14:43:19 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:

One server and zero agent.
 
**Describe the bug:**

Just after starting the K3s server, it uses a lot of CPUs in QEMU and real HW

**Steps To Reproduce:**

- Installed K3s: 

Installed k3s using Yocto and the installer from k3s page. No difference. 

**Expected behavior:**

Low use of CPU

**Actual behavior:**

High use of CPU

**Additional context / logs:**

Profiling k3s server shows high use of `k8s.io/apiserver/pkg/util/flowcontrol`. Below commands to profile k3s on my AVA platform:
```
# perf record -e task-clock/freq=19999,call-graph=fp/ -p 2848
# perf report --call-graph=graph,2%,0,caller,function,branch,percent --stdio
```
Here are the profiling logs:
[k3s_profile.log](https://github.com/k3s-io/k3s/files/10750840/k3s_profile.log)

**Comment by brandond** [comment]
I don't have any reason to believe this is unique to k3s; have you performed a similar analysis of the vanilla Kubernetes apiserver?

**Comment by brandond** [comment]
You might also be interested in looking at:
* https://github.com/kubernetes/kubernetes/pull/110154
* https://github.com/k3s-io/k3s/pull/5527#issuecomment-1114376418

**Comment by brandond** [comment]
I am going to close this as I believe there were improvements made in more recent releases of Kubernetes. If you haven't yet, please try a newer release of K3s that includes some of these improvements.
