### ISSUE TITLE
Release assets 'k3s-airgap-images-arm64.tar.gz' contain amd64 image 'rancher/mirrored-coredns-coredns'

### ISSUE THREAD

**Issue by q1979635364** [k3s-io/k3s#6967]
**Environmental Info:**
K3s Version: 

```
k3s version v1.23.15+k3s1 (50cab3b3)
go version go1.17.13
```

Node(s) CPU architecture, OS, and Version: 
`Linux huzz 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

Docker version:
```
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.1
 Built:             Thu Jan 26 21:11:51 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.1
  Built:            Thu Nov 17 20:08:15 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:        
 runc:
  Version:          1.1.4-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```
Docker buildx 
```
$ docker buildx ls 
NAME/NODE      DRIVER/ENDPOINT             STATUS  BUILDKIT PLATFORMS
multi-build *  docker-container                             
  multi-build0 unix:///var/run/docker.sock running v0.10.4  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default        docker                                       
  default      default                     running 20.10.21 linux/amd64, linux/386, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/arm/v7, linux/arm/v6
```

Cluster Configuration: None

**Describe the bug:**
1. Download https://github.com/k3s-io/k3s/releases/download/v1.23.16%2Bk3s1/k3s-airgap-images-arm64.tar.gz
2. Make sure there is no rancher/mirrored-coredns-coredns:1.9.4 image locally
3. Load image from the **arm64** tar
4. Inspect image arch, but found **amd64**, why?
![image](https://user-images.githubusercontent.com/25050128/219262344-cddbc4e5-e5b5-4c15-9d1f-17beb2f9dbb4.png)

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by q1979635364** [comment]
Incidentally, other release versions also have this problem

**Comment by brandond** [comment]
The config json for the coredns images has had this issue for ages. If you look at the manifest list, or the actual binaries in the image, they are of the correct architecture. We're just mirroring the images from upstream coredns, so here isn't the correct place to raise an issue about it.
