### ISSUE TITLE
K3S compatibility matrix  and documentation not updated for Rhel 9

### ISSUE THREAD

**Issue by swetasgit** [k3s-io/k3s#6968]
**Environmental Info:**
K3s Version: 1.25.6

Node(s) CPU architecture, OS, and Version: 
single node, 2 CPU, Rhel 9

Cluster Configuration:

**Describe the bug:**
As per this git issue k3s 1.25.6 is compatible for RHEL 9
https://github.com/k3s-io/k3s/issues/6611
Could you please update the support matrix https://www.suse.com/suse-k3s/support-matrix/all-supported-versions/k3s-v1-26/ and let us know additional steps if any
**Steps To Reproduce:**
RHEL 9 not in Support matrix page https://www.suse.com/suse-k3s/support-matrix/all-supported-versions/k3s-v1-26/
- Installed K3s: 
1.25.6
**Expected behavior:**
updated Support Matrix document and installation documetation

**Actual behavior:**

**Additional context / logs:**
In case RHEL 9 is not compatible please let us know the reason and by when we can expect it

**Comment by swetasgit** [comment]
Any update? We want to move to latest rhel version for our system it would be helpful to have the support matrix sheet updated with RHEL 9 details for internal approval . Else could you please at least us know the timeline by when we can expect the documents updated or is their any thing pending from K3S side to make it work properly work with Rhel 9

**Comment by dereknola** [comment]
Our QA team is in the process of validating RHEL 9 for K3s. Hopefully we will be able to add it to the support matrix in the coming months.

**Comment by brandond** [comment]
QA validated EL9 in:
* https://github.com/k3s-io/k3s/issues/6611

Our team doesn't own the SUSE support matrix, so I'm going to close this. The matrix will be refreshed by suse PM during the next Rancher release cycle.
