### ISSUE TITLE
[Documentation] Document the feature details of the new cluster-cidr flannel flag

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#6972]
Feature Issue: https://github.com/k3s-io/k3s/issues/6443
Feature PR: https://github.com/k3s-io/k3s/pull/6885
K3s docs: https://github.com/k3s-io/docs

Please document the details of our new cluster-cidr flag feature in the "Networking Options" section under the "Installation" section [here](https://docs.k3s.io/installation/network-options) in the K3s docs. It will be especially important to note that this feature will work with ipv4 and ipv6, but _not_ dual-stack.

NOTE: This documentation should be merged _after_ the linked feature PR is merged.

**Comment by bhavyastar** [comment]
Hey @caroline-suse-rancher,  I would like to work on this issue! Can you assign this to me?

**Comment by brandond** [comment]
We haven't merged the linked feature PR, so we don't need docs for it yet. Usually, the dev responsible for adding the feature is also responsible for adding documentation for it.
