### ISSUE TITLE
Investigate adding .droneignore file to free up CI resources

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#6980]
Currently we get a lot of full drone runs that are not strictly necessary, as drone is kicked off for *any* change by default, as opposed to GH actions runners which are not triggered for things like markdown file changes.  Now that we have more access to our drone, we can enable extensions if needed (specifically https://github.com/fernandrone/drone-ignore-config) and then iterate on a `.droneignore` file to stop wasting CI cycles, especially around the release time.  Off the top of my head, we don't need to run drone on:

* .md files
* Install script (could be convinced otherwise here) 
* channels.yaml
* .github/*

**Comment by cwayne18** [comment]
This has now been merged, thanks Matt! I suppose for QA we could either just close this out as its a CI change, or have somebody open a PR against a .md file and make sure it's skipped? your choice @rancher-max

**Comment by rancher-max** [comment]
I'm not concerned! Closing it out -- thank you
