### ISSUE TITLE
default node labels are out of date

### ISSUE THREAD

**Issue by vtrenton** [k3s-io/k3s#6981]
**Environmental Info:**
K3s Version: all

Node(s) CPU architecture, OS, and Version: any

Cluster Configuration: any

**Describe the bug:**

on a fresh install of k3s the node labels provided to each node is out of date for example beta.kubernetes.io/os has been replaced with kubernetes.io/os since 1.14. On a fresh install of k3s 1.26.1 we are still seeing this issue occur.

**Steps To Reproduce:**

- Installed K3s using `curl https://get.k3s.io/ | sh -`
- ran `kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get nodes --show-labels`
- see node labels prefixed with beta that are no longer in beta

`susecowmeleon   Ready    control-plane,master   17s   v1.26.1+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,egress.k3s.io/cluster=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=susecowmeleon,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/master=true,node.kubernetes.io/instance-type=k3s`

**Expected behavior:**

Node labels are replaced with common expected upstream labels. based on: https://kubernetes.io/docs/reference/labels-annotations-taints/

**Comment by brandond** [comment]
This is not coming from K3s itself. They have been deprecated by upstream, but not removed, and are still created by the kubelet and synchronized by the node lifecycle controller. Ref: https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L143-L156
