### ISSUE TITLE
Using GCE VM instance service account

### ISSUE THREAD

**Issue by gfrankliu** [k3s-io/k3s#6983]
The k3s running inside a GCE VM doesn't seem to use VM's attached service account for image pulling from GCR image registry. Is this a bug or expected behavior, in which case we probably want a feature request.

**Comment by brandond** [comment]
See https://github.com/k3s-io/k3s/blob/master/README.md#what-have-you-removed-from-upstream-kubernetes - we have intentionally removed the build-in cloud-providers and their auth providers from K3s. This is one of the major changes that reduces the size of the K3s binary, as the cloud provider's API bindings are... huge.

If you need to use this, you should deploy a kubelet credential provider:
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/
