### ISSUE TITLE
Allow better control of etcd directory

### ISSUE THREAD

**Issue by mnlipp** [k3s-io/k3s#6992]
Maybe I haven't fully understood things yet, but...

I have a cluster with machines that have only a small amount of SSD storage. This is okay for the task at hand, because the setup is more about HA than about high loads.

As was to be expected, I get "expected-duration violation" messages from etcd. So I want to dedicate some of the SSD storage to etcd. This, however, proves to be unnecessarily difficult.

I can configure `${data-dir}`, but this is too coarse grained. It holds `agent`, `data` and `server`. The only data that has to go to the SSD is `server/db`, everything else can happily live on a HDD. You'd expect this to be configurable independently because k3s "integrates" etcd, but that's not the case.

Different approach: "move" `${data-dir}` and "move back" everything inside except `server/db`. But this isn't possible either. The only sub-directories that have a configuration option are `${data-dir}/server/db/snapshots` and `${data-dir}/storage`  (from `--default-local-storage-path`). The default for the latter is not documented, but I found it in `${data-dir}/server/manifests/local-storage.yaml`.

Of course, I can mount the SSD storage on `${data-dir}/server/db`. But I think it would be nice to be able to simply configure this particular directory when installing k3s.

**Comment by dereknola** [comment]
You may want to consider running K3s with an external etcd or other DB, which you can independently peg to a SSD portion. See https://docs.k3s.io/installation/ha

**Comment by mnlipp** [comment]
> You may want to consider running K3s with an external etcd or other DB, which you can independently peg to a SSD portion. See https://docs.k3s.io/installation/ha

Looks much more complicated than my workaround, which others have come up with, too (see https://www.suse.com/support/kb/doc/?id=000020050). I'm just suggesting that life could be simplified for everybody facing this issue.

**Comment by brandond** [comment]
K3s tries to strike a balance between being opinionated and configurable. We can't add CLI flags for every possible option, and in this case creating a mount or bind mount for the DB dir is a pretty easy way to address this ask without further bloating the CLI flags.

**Comment by mnlipp** [comment]
As mentioned, would have been nice, but, okay.
