### ISSUE TITLE
`k3s server` exits instead of retrying when receiving "too many learners" error from etcd join

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7000]
* K3s tracking issue for https://github.com/rancher/rancher/issues/39109

> Looking at the K3s.service logs, it seems that this error is related to the creation of the etcd quorum. Specifically, it seems that too many etcd nodes are attempting to join at once, resulting in the error level=fatal msg="ETCD join failed: etcdserver: too many learner members in cluster", which can be seen on every node which has a error reported in the UI.

K3s currently exits if it is unable to join the cluster due to another node currently being in the process of promoting up from learner. This is handled by systemd restarting k3s until it successfully joins, but the fact that the initial install-and-start sequence fails causes rancher-system-agent to mark the plan as failed.

https://github.com/rancher/system-agent-installer-k3s/pull/10 added a work-around to this, but its ugly as it dumps the service logs from journald out to a file and then greps through that file for a specific error string.

We should instead retry the join for a reasonable period of time without exiting.

**Comment by caroline-suse-rancher** [comment]
Closing as this is resolved in rancher now

**Comment by aganesh-suse** [comment]
OS: Ubuntu 22.04
K3s : 1 main server and 3 secondary servers

Verified that multiple log lines of "Adding member **" were visible on all joining servers in the journal logs. No Fatal errors were found. 

From  journalctl logs: 

```
May 10 19:45:15 ip-172-31-45-214 k3s[1799]: time="2023-05-10T19:45:15Z" level=info msg="Adding member ip-172-31-45-214-e973d605=https://172.31.45.214:2380 to etcd cluster [ip-172-31-38-203-5ba684ab=https://172.31.38.203:2380 ip-172-31-43-233-fdf7ce00=https://172.31.43.233:2380]"
May 10 19:45:16 ip-172-31-45-214 k3s[1799]: time="2023-05-10T19:45:16Z" level=info msg="Adding member ip-172-31-45-214-e973d605=https://172.31.45.214:2380 to etcd cluster [ip-172-31-38-203-5ba684ab=https://172.31.38.203:2380 ip-172-31-43-233-fdf7ce00=https://172.31.43.233:2380]"
May 10 19:45:17 ip-172-31-45-214 k3s[1799]: time="2023-05-10T19:45:17Z" level=info msg="Adding member ip-172-31-45-214-e973d605=https://172.31.45.214:2380 to etcd cluster [ip-172-31-38-203-5ba684ab=https://172.31.38.203:2380 ip-172-31-43-233-fdf7ce00=https://172.31.43.233:2380]"
```
