### ISSUE TITLE
Doc: Rocky Linux 8.7 not updated in support matrix

### ISSUE THREAD

**Issue by swetasgit** [k3s-io/k3s#7008]
**Environmental Info:**
K3s Version: 1.25.6

Node(s) CPU architecture, OS, and Version: 
Rocky Linux 8.7
Cluster Configuration:
3 nodes

**Describe the bug:**
The Support Matrix of Suse for k3s 1.25.X  doesn't include Rocky Linux 8.7

**Steps To Reproduce:**
Document link: https://www.suse.com/suse-k3s/support-matrix/all-supported-versions/k3s-v1-25/
Issue supporting Rocky Linux 8.7 : https://github.com/k3s-io/k3s/issues/6542
- Installed K3s: 

**Expected behavior:**
Support matrix of 1.25.X has Rocky linux 8.7 

**Actual behavior:**
Support matrix doesn't have Rocky Linux 8.7 for k3s 1.25.X

**Additional context / logs:**

**Comment by brandond** [comment]
This team doesn't own the suse support matrix. Updating that page will be handled by PM at a later date.
