### ISSUE TITLE
CentOS7 - coredns failing with CrashLoopBackOff

### ISSUE THREAD

**Issue by purevoip** [k3s-io/k3s#7014]
**issue:** Liveness probe failed: Get "http://10.42.0.72:8080/health": dial tcp 10.42.0.72:8080: connect: connection refused

# k3s -v
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5

k3s installed with 
#curl -sfL https://get.k3s.io | sh -

# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

# uname -a
Linux host1 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Selinux disabled
firewalld disabled
iptables enabled

according to issues 
https://github.com/k3s-io/k3s/issues/24
https://github.com/k3s-io/k3s/issues/1801
added iptables rules 
iptables -I INPUT 1 -i cni0 -s 10.42.0.0/16 -j ACCEPT
iptables -I FORWARD 1 -s 10.42.0.0/15 -j ACCEPT
iptables -I OUTPUT 1 -s 10.42.0.0/16 -j ACCEPT

```console
# kubectl -n kube-system logs coredns-597584b69b-xqwcl
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
.:53
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[INFO] plugin/reload: Running configuration SHA512 = b941b080e5322f6519009bb49349462c7ddb6317425b0f6a83e5451175b720703949e3f3b454a24e77f3ffe57fd5e9c6130e528a5a1dd00d9000e4afd6c1108d
CoreDNS-1.9.4
linux/amd64, go1.19.1, 1f0a41a
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[INFO] SIGTERM: Shutting down servers then terminating


# kubectl describe pod -n kube-system coredns-597584b69b-xqwcl
Name:                 coredns-597584b69b-xqwcl
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      coredns
Node:                 ***************************
Start Time:           Fri, 24 Feb 2023 19:14:18 -0500
Labels:               k8s-app=kube-dns
                      pod-template-hash=597584b69b
Annotations:          <none>
Status:               Running
IP:                   10.42.0.72
IPs:
  IP:           10.42.0.72
Controlled By:  ReplicaSet/coredns-597584b69b
Containers:
  coredns:
    Container ID:  containerd://9c9f86d69e4dfc0cd6663c45ab3cccf47fe3150ef14da520fad1f0412a474581
    Image:         rancher/mirrored-coredns-coredns:1.9.4
    Image ID:      docker.io/rancher/mirrored-coredns-coredns@sha256:823626055cba80e2ad6ff26e18df206c7f26964c7cd81a8ef57b4dc16c0eec61
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Thu, 02 Mar 2023 11:24:34 -0500
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 02 Mar 2023 11:23:12 -0500
      Finished:     Thu, 02 Mar 2023 11:24:33 -0500
    Ready:          True
    Restart Count:  2096
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=2s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /etc/coredns/custom from custom-config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mxncj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  custom-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns-custom
    Optional:  true
  kube-api-access-mxncj:
    Type:                     Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:   3607
    ConfigMapName:            kube-root-ca.crt
    ConfigMapOptional:        <nil>
    DownwardAPI:              true
QoS Class:                    Burstable
Node-Selectors:               beta.kubernetes.io/os=linux
Tolerations:                  CriticalAddonsOnly op=Exists
                              node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                              node-role.kubernetes.io/master:NoSchedule op=Exists
                              node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Topology Spread Constraints:  kubernetes.io/hostname:DoNotSchedule when max skew 1 is exceeded for selector k8s-app=kube-dns
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Normal   Killing    148m (x3 over 151m)   kubelet  Container coredns failed liveness probe, will be restarted
  Normal   Created    148m (x4 over 152m)   kubelet  Created container coredns
  Normal   Started    148m (x4 over 152m)   kubelet  Started container coredns
  Warning  Unhealthy  148m                  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Pulled     142m (x6 over 152m)   kubelet  Container image "rancher/mirrored-coredns-coredns:1.9.4" already present on machine
  Warning  Unhealthy  102m (x45 over 151m)  kubelet  Liveness probe failed: Get "http://10.42.0.72:8080/health": dial tcp 10.42.0.72:8080: connect: connection refused
  Warning  BackOff    92m (x170 over 145m)  kubelet  Back-off restarting failed container
  Normal   Killing    84m (x3 over 87m)     kubelet  Container coredns failed liveness probe, will be restarted
  Normal   Pulled     84m (x4 over 88m)     kubelet  Container image "rancher/mirrored-coredns-coredns:1.9.4" already present on machine
  Normal   Created    84m (x4 over 88m)     kubelet  Created container coredns
  Normal   Started    84m (x4 over 88m)     kubelet  Started container coredns
  Warning  BackOff    43m (x134 over 82m)   kubelet  Back-off restarting failed container
  Warning  Unhealthy  38m (x47 over 87m)    kubelet  Liveness probe failed: Get "http://10.42.0.72:8080/health": dial tcp 10.42.0.72:8080: connect: connection refused
  Warning  Unhealthy  34m                   kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing    29m (x3 over 32m)     kubelet  Container coredns failed liveness probe, will be restarted
  Normal   Created    29m (x4 over 34m)     kubelet  Created container coredns
  Normal   Started    29m (x4 over 34m)     kubelet  Started container coredns
  Normal   Pulled     24m (x6 over 34m)     kubelet  Container image "rancher/mirrored-coredns-coredns:1.9.4" already present on machine
  Warning  Unhealthy  8m37s (x25 over 33m)  kubelet  Liveness probe failed: Get "http://10.42.0.72:8080/health": dial tcp 10.42.0.72:8080: connect: connection refused
  Warning  BackOff    4m7s (x81 over 26m)   kubelet  Back-off restarting failed container
```

**Comment by rbrtbnfgl** [comment]
which are the the `iptables` rules if you do `iptables -vnL`?

**Comment by purevoip** [comment]
attached output of
[iptables_vnL.txt](https://github.com/k3s-io/k3s/files/10909321/iptables_vnL.txt)
iptables -vnL

**Comment by rbrtbnfgl** [comment]
what is the content of `/etc/hosts`? And if you try to ping a remote server name from the host is it correctly translated to an IP?

**Comment by purevoip** [comment]
# kubectl run -it --rm --restart=Never busybox --image=busybox sh
If you don't see a command prompt, try pressing enter.
/ #
/ #
/ # nslookup api.binance.com
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
api.binance.com canonical name = d3h36i1mno13q3.cloudfront.net

Non-authoritative answer:
api.binance.com canonical name = d3h36i1mno13q3.cloudfront.net
Name:   d3h36i1mno13q3.cloudfront.net
Address: 13.225.192.4

/ # cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.42.0.24      busybox
/ #

**Comment by purevoip** [comment]
/ # ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if133: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 8e:c5:f5:87:19:73 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.24/24 brd 10.42.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8cc5:f5ff:fe87:1973/64 scope link
       valid_lft forever preferred_lft forever
/ # ping  api.binance.com
PING api.binance.com (13.225.192.4): 56 data bytes
64 bytes from 13.225.192.4: seq=0 ttl=243 time=0.915 ms
64 bytes from 13.225.192.4: seq=1 ttl=243 time=5.320 ms
64 bytes from 13.225.192.4: seq=2 ttl=243 time=0.771 ms
64 bytes from 13.225.192.4: seq=3 ttl=243 time=0.714 ms
64 bytes from 13.225.192.4: seq=4 ttl=243 time=0.882 ms
^C
--- api.binance.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.714/1.720/5.320 ms

**Comment by brandond** [comment]
Have you tried turning the host iptables firewall off entirely, and restarting? I suspect that the rules you've put in place are not sufficient to allow all the required traffic.

**Comment by rbrtbnfgl** [comment]
The pod that you used has the right dns config and it's using `10.43.0.10` as DNS that I think is translated by kube-proxy to the address of coredns. Are you sure that is it still on `CrashloopBackOff`?

**Comment by purevoip** [comment]
Hello [brandond](https://github.com/brandond)
I tried flash iptables and restart k3s, see below:

/#iptables -F
/#iptables -F -t nat
/#service k3s restart
/#iptables -vnL > /tmp/iptables2.txt
[iptables2.txt](https://github.com/k3s-io/k3s/files/10919741/iptables2.txt)

/# kubectl get pods --all-namespaces
NAMESPACE     NAME                                          READY   STATUS             RESTARTS       AGE
kube-system   local-path-provisioner-79f67d76f8-bq4nh       1/1     Running            0              37h
kube-system   svclb-traefik-8301d908-sd747                  2/2     Running            0              37h
kube-system   helm-install-traefik-crd-sfnpc                0/1     Completed          0              37h
kube-system   helm-install-traefik-5ttxn                    0/1     Completed          1              37h
default       dnsutils                                      1/1     Running            0              37h
kube-system   svclb-shkeeper-55da36d8-5jhvn                 1/1     Running            0              37h
shkeeper      bitcoind-deployment-9c677cc84-jpfg8           2/2     Running            0              37h
shkeeper      dogecoind-deployment-54b4f979c4-9mn46         2/2     Running            0              37h
shkeeper      mariadb-77ddc74886-8xkj6                      1/1     Running            0              37h
shkeeper      litecoind-deployment-6d55ddc5bf-l2qcd         2/2     Running            0              37h
default       my-shkeeper-cred-generator-85f9b5448d-drvdh   1/1     Running            0              37h
shkeeper      shkeeper-deployment-588796d6cf-2c6gz          1/1     Running            3 (15h ago)    37h
kube-system   metrics-server-5f9f776df5-qxh8q               1/1     Running            0              37h
kube-system   traefik-66c46d954f-2p25t                      1/1     Running            0              37h
kube-system   coredns-597584b69b-xth69                      0/1     CrashLoopBackOff   6 (118s ago)   12m

/#kubectl -n kube-system logs --previous coredns-597584b69b-xth69

[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
.:53
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[INFO] plugin/reload: Running configuration SHA512 = b941b080e5322f6519009bb49349462c7ddb6317425b0f6a83e5451175b720703949e3f3b454a24e77f3ffe57fd5e9c6130e528a5a1dd00d9000e4afd6c1108d
CoreDNS-1.9.4
linux/amd64, go1.19.1, 1f0a41a
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": dial tcp :8080: connect: connection refused
[INFO] SIGTERM: Shutting down servers then terminating

[rbrtbnfgl](https://github.com/rbrtbnfgl)   coredns keep failing

**Comment by purevoip** [comment]
/# kubectl run -it --rm --restart=Never busybox --image=busybox sh
If you don't see a command prompt, try pressing enter.
/ #
/ #
/ # nslookup api.binance.com
;; connection timed out; no servers could be reached

**Comment by purevoip** [comment]
I edited coredns deployment with

/# kubectl -n kube-system edit deployment coredns -o yaml

and removed 
livenessProbe
readinessProbe


then coredns stop crashing

/# kubectl get pods --all-namespaces
NAMESPACE     NAME                                          READY   STATUS      RESTARTS      AGE
kube-system   local-path-provisioner-79f67d76f8-bq4nh       1/1     Running     0             38h
kube-system   svclb-traefik-8301d908-sd747                  2/2     Running     0             38h
kube-system   helm-install-traefik-crd-sfnpc                0/1     Completed   0             38h
kube-system   helm-install-traefik-5ttxn                    0/1     Completed   1             38h
default       dnsutils                                      1/1     Running     0             38h
kube-system   svclb-shkeeper-55da36d8-5jhvn                 1/1     Running     0             37h
shkeeper      bitcoind-deployment-9c677cc84-jpfg8           2/2     Running     0             37h
shkeeper      dogecoind-deployment-54b4f979c4-9mn46         2/2     Running     0             37h
shkeeper      mariadb-77ddc74886-8xkj6                      1/1     Running     0             37h
shkeeper      litecoind-deployment-6d55ddc5bf-l2qcd         2/2     Running     0             37h
default       my-shkeeper-cred-generator-85f9b5448d-drvdh   1/1     Running     0             37h
shkeeper      shkeeper-deployment-588796d6cf-2c6gz          1/1     Running     3 (15h ago)   37h
kube-system   metrics-server-5f9f776df5-qxh8q               1/1     Running     0             38h
kube-system   traefik-66c46d954f-2p25t                      1/1     Running     0             38h
kube-system   coredns-67c6495774-7wls6                      1/1     Running     0             112s

# kubectl run -it --rm --restart=Never busybox --image=busybox sh
If you don't see a command prompt, try pressing enter.
/ #
/ #
/ # nslookup api.binance.com
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
api.binance.com canonical name = d3h36i1mno13q3.cloudfront.net

Non-authoritative answer:
api.binance.com canonical name = d3h36i1mno13q3.cloudfront.net
Name:   d3h36i1mno13q3.cloudfront.net
Address: 13.225.192.4

/ #

**Comment by rbrtbnfgl** [comment]
if you try from the host to do `wget http://[IP coredns pod]:8080/health` what do you get?

**Comment by purevoip** [comment]
Getting "Connection refused"

# kubectl run -it --rm --restart=Never busybox --image=busybox sh
If you don't see a command prompt, try pressing enter.
/ #
/ #
/ # wget http://10.42.0.32:8080/health
Connecting to 10.42.0.32:8080 (10.42.0.32:8080)
wget: can't connect to remote host (10.42.0.32): Connection refused

**Comment by rbrtbnfgl** [comment]
That fixes your issue but coredns should listen on `8080` for the probe.
Are you sure that firewalld and selinux are disabled?

**Comment by purevoip** [comment]
/# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

/# cat  /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

I found that coredns is listening on 80 port instead on 8080
/# curl http://10.42.0.67:8080/health
curl: (7) Failed connect to 10.42.0.67:8080; Connection refused

/# curl http://10.42.0.67:80/health
OK

so I chaned in coredns deployment:
"
livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            **port: 80**
            scheme: HTTP
"
and added in iptables:
-A PREROUTING -s 10.42.0.0/16 -p tcp -m tcp --dport 8080 -j REDIRECT --to-ports 80
 
that solution is working for me

**Comment by brandond** [comment]
That is not the default port for coredns health checks, nor the way I would suggest to fix that issue. Have you customized your coredns deployment in some way? Did you perhaps alter the flags or configuration, and forget to update the health checks to match?

https://coredns.io/plugins/health/
> Enabled process wide health endpoint. When CoreDNS is up and running this returns a 200 OK HTTP status code. The health is exported, by default, on port 8080/health.
