### ISSUE TITLE
Installation stops after hash file download

### ISSUE THREAD

**Issue by Leviathan321** [k3s-io/k3s#7020]
**Describe the bug:**
I cannot install k3s on a ubuntu 21.04 system using the install script.
The installation stops without an error output.

**Steps To Reproduce:**
Run `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -s -`.

**Expected behavior:**
k3s is installed

**Actual behavior:**
k3s installation stops after hash download.

**Additional context / logs:**
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -s -
[INFO]  Finding release for channel stable
[INFO]  Using v1.25.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.6+k3s1/sha256sum-amd64.txt

**Comment by cubxxw** [comment]
Maybe because of the network, can you debug or give a short point？

**Comment by Leviathan321** [comment]
What do you mean with short point? I can actually execute the curl command
seperately.

Xinwei Xiong ***@***.***> schrieb am Fr., 3. März 2023, 18:28:

**Comment by brandond** [comment]
The host you are attempting to install K3s on cannot reach GitHub to download the release artifacts. Please ensure that there is not anything preventing you from accessing GitHub assets.

**Comment by Leviathan321** [comment]
The output for the given command is fine, I get the file:

...
< content-length: 440
< 
6d41ae24985061f6fcfd80bad1162ab39cfd40308f68956f22794be816b0245f  k3s
7d9008faf4b192e1ab0cce1d177cb615c6e30a777ac6e7ad66b7b15be4d1be5f  k3s-airgap-images-amd64.tar
6e5f11b00586df7ea517d996c5a26637c4c99f869cb42296ccaccaff59e7df96  k3s-airgap-images-amd64.tar.gz
51ced8c407cd50eaea7a7682c839ac55706ded52f6a5931cdb1164bc14799604  k3s-airgap-images-amd64.tar.zst
51244e55757554c98b60acf7d86c8a914a84037efebe525e905f59d4dad4e483  k3s-images.txt

**Comment by brandond** [comment]
is your curl perhaps installed from a snap, instead of as a .deb? I'm not finding an existing issue for it, but I have seen curl fail to download files with a `permission denied` errors when it is installed from a snap. 

You can run `curl -sfL https://get.k3s.io/ | INSTALL_K3S_EXEC="--disable=traefik" sh -sx -` to see the full curl command that's being run, and try the same manually.

**Comment by Leviathan321** [comment]
Thank you! The installation of curl was the reason. Strange that it did not output any error.
