### ISSUE TITLE
k3s crictl command relies on default path

### ISSUE THREAD

**Issue by asloan7** [k3s-io/k3s#7031]
**Environmental Info:**

k3s -v
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5

Node(s) CPU architecture, OS, and Version: 
Linux vrexsrv-hdc-05p.sys.comcast.net 5.4.234-1.el8.elrepo.x86_64 #1 SMP Thu Mar 2 15:14:31 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**
Install k3s with a non-default path:  --data-dir /usr/local/rancher/k3s

try a crictl command:
crictl images
FATA[0000] load config file: stat /var/lib/rancher/k3s/data/630c40ff866a3db218a952ebd4fd2a5cfe1543a1a467e738cb46a2ad4012d6f1/bin/crictl.yaml: no such file or directory

**Comment by dereknola** [comment]
The embedded `k3s crictl` does work with nondefault paths. You need to supply the `-d` to the root k3s command. 

```
k3s -d /usr/local/rancher/k3s crictl images 
```

**Comment by brandond** [comment]
@dereknola I don't think that works; when I try that I still see it using the default path.

**Comment by asloan7** [comment]
Thanks @dereknola , it worked for me, I couldn't find that documentation.
But k3s dir is owned by root, which isn't ideal

workaround is a bit tedious (will create alias):
sudo /usr/local/bin/k3s -d /usr/local/rancher/k3s crictl images

**Comment by dereknola** [comment]
It's generally assumed that when running K3s you have "sudo" permissions or are root. We have some rootless support, but it is experimental.

**Comment by brandond** [comment]
You can also just put it in the config file so you don't have to remember to use the alias:
```bash
echo "data_dir: /usr/local/rancher/k3s" >> /etcd/rancher/k3s/config.yaml
```

**Comment by asloan7** [comment]
It's just to reach the crictl.yaml, not run k3s non-root. 

Maybe something like K3S_KUBECONFIG_MODE="644" for crictl.yaml (which might mean storing it in /etcd/rancher/k3s/).
Coming from a "docker ps" world, new to crictl

Will try adding data_dir to /etcd/rancher/k3s/config.yaml

**Comment by asloan7** [comment]
@brandond had a few problems with
`echo "data_dir: /usr/local/rancher/k3s" >> /etcd/rancher/k3s/config.yaml`

I am guessing etcd should be etc

But doing 
`echo "data_dir: /usr/local/rancher/k3s" >> /etc/rancher/k3s/config.yaml; 
chmod 644 /etc/rancher/k3s/config.yaml`

creates NEW config.yaml (did you mean k3s.yaml?)

Still crictl is looking for its data dir
crictl ps
`FATA[0000] load config file: stat /var/lib/rancher/k3s/data/630c40ff866a3db218a952ebd4fd2a5cfe1543a1a467e738cb46a2ad4012d6f1/bin/crictl.yaml: no such file or directory`

**Comment by brandond** [comment]
no, k3s.yaml is the admin kubeconfig, you want config.yaml as covered in the docs: https://docs.k3s.io/installation/configuration#configuration-file

The other helper tools should load the config file to check for data_dir but it's possible they're not.

**Comment by asloan7** [comment]
Yes, that fixed it, thanks!
