### ISSUE TITLE
Pulling an image with --all-platforms fails if the image contains an SLSA provenance manifest

### ISSUE THREAD

**Issue by mrene** [k3s-io/k3s#7035]
**Environmental Info:**
K3s Version: 
```
k3s version v1.26.1+k3s1 (f10af367)
go version go1.19.6
```

Node(s) CPU architecture, OS, and Version: 
```
Linux beast 6.1.14 #1-NixOS SMP PREEMPT_DYNAMIC Sat Feb 25 10:25:43 UTC 2023 x86_64 GNU/Linux
```

Cluster Configuration:
Single node setup for testing purposes

**Describe the bug:**
We pull images in order to save them to an onprem bundle, when pulling a recent version of keycloak, the operation failed with `ctr: failed to extract layer sha256:09a85f55824bc820d92dc7578e2a0afe1d19cdc5dbdbd1b994891ee1ae5bb0b8: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown`

**Steps To Reproduce:**
```
k3s ctr images pull --all-platforms quay.io/keycloak/keycloak:20.0.5
```

**Expected behavior:**
It pulls the image correctly.

**Actual behavior:**
It fails with `ctr: failed to extract layer sha256:09a85f55824bc820d92dc7578e2a0afe1d19cdc5dbdbd1b994891ee1ae5bb0b8: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown`

**Additional context / logs:**
```
unpacking linux/amd64 sha256:054ef67eb7dae0129bbb9eb0e0797fd2392cd6d135094a6063ae7ff7773ef81f...
unpacking linux/arm64 sha256:054ef67eb7dae0129bbb9eb0e0797fd2392cd6d135094a6063ae7ff7773ef81f...
unpacking unknown/unknown sha256:054ef67eb7dae0129bbb9eb0e0797fd2392cd6d135094a6063ae7ff7773ef81f...
INFO[0020] apply failure, attempting cleanup             error="failed to extract layer sha256:09a85f55824bc820d92dc7578e2a0afe1d19cdc5dbdbd1b994891ee1ae5bb0b8: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown" key="extract-348288778-KLGm sha256:09a85f55824bc820d92dc7578e2a0afe1d19cdc5dbdbd1b994891ee1ae5bb0b8"
ctr: failed to extract layer sha256:09a85f55824bc820d92dc7578e2a0afe1d19cdc5dbdbd1b994891ee1ae5bb0b8: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown
```

**Comment by brandond** [comment]
We package containerd's `ctr` binary but it is not part of this project. You should check with the upstream project at https://github.com/containerd/containerd to see if there is already an issue reported for what you're experiencing.
