### ISSUE TITLE
Deploying k3s with k3s-install.sh on arm64 architecture, does the kernel PAGE_SIZE parameter have to be 4k?

### ISSUE THREAD

**Issue by lvyanru8200** [k3s-io/k3s#7038]
**Environmental Info:**
K3s Version: 

v1.25.6+k3s1
Node(s) CPU architecture, OS, and Version: 

Linux  4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
Cluster Configuration:

1 server 1 agent
**Describe the bug:**

After deployment, describe po reports an error: signal: segmentation fault: : unknown
**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by lvyanru8200** [comment]
cc @brandond @gdoucet

**Comment by brandond** [comment]
Yes. Tracking this at https://github.com/k3s-io/k3s/issues/6708#issuecomment-1430515990
