### ISSUE TITLE
Add updateCLI/automated dependency management to other k3s repos

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#7040]
We currently have automation to bump dependencies in k3s-io/k3s itself, but we don't have it for other repos we maintain (i.e kine, k3s-upgrade, etc).  Please follow the decisions highlighted in this [ADR](https://github.com/k3s-io/k3s/blob/master/docs/adrs/security-updates-automation.md) for the following repos:

* [ ] k3s-io/kine
* [ ] k3s-io/k3s-upgade
* [ ] k3s-io/klipper-lb
* [ ] k3s-io/klipper-helm
* [ ] k3s-io/helm-controller
* [ ] rancher/system-agent-installer-k3s

**Comment by matttrach** [comment]
I am going to add dependabot separately from updatecli so that the changes are atomic.

**Comment by matttrach** [comment]
I want to see how @macedogm feels about https://github.com/k3s-io/kine/pull/166 as sort of a generic way to get updatecli into every repo where we see it as useful. Then, once it is in, I will start having updatecli look at different files based on what the repo needs. I think that breaks things up so that the reviews are small and simple and the changes can be reasoned about easily without being too granular.

**Comment by matttrach** [comment]
@macedogm pointed out https://github.com/k3s-io/klipper-lb/pull/45#issuecomment-1480109824, which highlights that sometimes versions are in places we don't expect them to be. Dependabot will only manage the dockerfile lines that are structured as part of the build, we need to make sure to check the dockerfile for unstructured versions.

**Comment by macedogm** [comment]
> I am going to add dependabot separately from updatecli so that the changes are atomic.

@matttrach in some of the PRs that I reviewed I mentioned about adding UpdateCLI. Your approach in separating them makes sense 👍🏻

**Comment by macedogm** [comment]
> I want to see how @macedogm feels about [k3s-io/kine#166](https://github.com/k3s-io/kine/pull/166) as sort of a generic way to get updatecli into every repo where we see it as useful. Then, once it is in, I will start having updatecli look at different files based on what the repo needs. I think that breaks things up so that the reviews are small and simple and the changes can be reasoned about easily without being too granular.

@matttrach I made a few comments in the PR, but overall the approach is really great. From what I saw in K3s repos, most of the updates required, expect a few, are the same, so having a central config for UpdateCLI will greatly speed up the time to add it to more repos.

**Comment by matttrach** [comment]
Updatecli PRs have been added, dependabot PRs have been merged.
Updatecli has been introduced successfully to k3s-io/kine and is making PRs.

Next up: adding updatecli configs to update unstructured Dockerfile lines to Kine first, then the other repos.

**Comment by matttrach** [comment]
Here are the list of things to investigate for Kine:
- kine
	- https://github.com/k3s-io/kine/blob/master/Dockerfile.test.dapper#L6
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L12
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L22
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L56
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L95
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L126
	- https://github.com/k3s-io/kine/blob/master/.drone.yml#L165
	- https://github.com/k3s-io/kine/blob/master/scripts/test-helpers#L208
	- https://github.com/k3s-io/kine/blob/master/scripts/test-run-cockroachdb#L7
	- https://github.com/k3s-io/kine/blob/master/scripts/test-run-jetstream#L8
	- https://github.com/k3s-io/kine/blob/master/scripts/test-run-mysql#L25
	- https://github.com/k3s-io/kine/blob/master/scripts/test-run-postgres#L25

**Comment by caroline-suse-rancher** [comment]
Marking this issue as done since the initial setup is complete. Follow-on work will be in additional issues.
