### ISSUE TITLE
[Release-1.25] - Add warning that containerd's `config.toml` is auto generated

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#7058]
Backport fix for Add warning that containerd's `config.toml` is auto generated

* #7056

**Comment by mdrahman-suse** [comment]
### Validated on branch release-1.25 with commit 37a26379d5780d145203d59f5ebebf39e39632fa
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s: 
 - For replication: `curl -sfL https://get.k3s.io | sudo INSTALL_K3S_VERSION=v1.25.7+k3s1 sh -`
 - For validation: `curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT=37a26379d5780d145203d59f5ebebf39e39632fa sh -`
3. Check for warning comment on top of the file using `var/lib/rancher/k3s/agent/etc/containerd/config.toml`
 
 
**Replication Results:**
- k3s version used for replication:

```
v1.25.7+k3s1
```
 

- No warning is observed
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml

version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
...
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.25.7+k3s-37a26379 (37a26379)
go version go1.19.6
```
 

- Observed the warning
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml

# File generated by k3s. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
```
