### ISSUE TITLE
[New OS Validation] Oracle 9.1

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#7074]
Confirm this OS is functional using v1.26

**Comment by mdrahman-suse** [comment]
Validated Oracle Linux 9.1 with release v1.26.2+k3s1
Checks performed that passed
- [ ] Fresh Installation and sonobuoy execution 
- [ ] Perform snapshot and restore
- [ ] Validate installation with docker CRI 
- [ ] Upgrade SUC k3s native with workloads
