### ISSUE TITLE
FailedCreatePodSandBox

### ISSUE THREAD

**Issue by vhuezo** [k3s-io/k3s#7078]
```
 FailedCreatePodSandBox 	Pod rabbitmq-5b6d55d4f7-w5t97
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3b0fa3eecd2a402aa39496baa6d9e5c711c1abcd2bdc6fdc0321845ff0c1f387": plugin type="flannel" failed (add): failed to delegate add: failed to allocate for range 0: no IP addresses available in range set: 10.42.0.1-10.42.0.254 
```

**Comment by vhuezo** [comment]
> 1. Please fill out the issue template; don't just paste an error message into an empty comment.
> 
>     2. `no IP addresses available in range set: 10.42.0.1-10.42.0.254 ` - you're out of IPs. How many pods do you have - what's the output of `kubectl get pod -A`? Is there something going on with your host that prevents it from cleaning up pod address reservations?

`kubectl get pod -A`

https://pastebin.com/kQ5AeCvN

Is there a way to Manually Clear the IP's?

**Comment by brandond** [comment]
How many nodes do you have there?I see 97 pods, which is close to the default max pods-per-node limit of 110, but should not have exhausted all the IPs.

There is safe, easy way to clear all the IPs. The best way to manually clear the IPs is disruptive, in that it will restart both K3s and all of the pods running on a node.
1. run the `k3s-killall.sh` script to stop K3s and terminate all the running pods.
2. run `rm -rf /var/lib/cni` to ensure that all the CNI data is cleared, including the reserved IP lists.
3. start k3s.

**Comment by vhuezo** [comment]
![2023-03-13_20-10](https://user-images.githubusercontent.com/41808201/224874596-15535c14-3eba-489a-81bf-3d1073801e47.png)

Thank You.
