### ISSUE TITLE
k3s will be restart every 15 minutes when only run etcd

### ISSUE THREAD

**Issue by Jelly-Fisher-fish** [k3s-io/k3s#7085]
# error message
```
level=fatal msg="Tunnel watches failed to wait for apiserver ready: timed out waiting for the condition, failed to get apiserver /readyz status: apiserver disabled"
```
# configuration of k3s server
```
private-registry:/path/to/file
pause-image: docker.io/rancher/mirrored-pause:3.6
node-name: xxx
cluster-init: true
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
disable-helm-controller: true
disable-cloud-controller: true
disable: servicelb,traefik,local-storage
disable-agent: true
disable-kube-proxy: true
disable-network-policy: true
flannel-backend: none
token-file: /path/to/file
agent-token-file: /path/to/file
```
what should i do to keep etcd running and not restart

**Comment by brandond** [comment]
Have you added a control-plane node, without the apiserver and everything else disabled? You're not intended to leave the etcd-only node sitting there by itself forever.

**Comment by brandond** [comment]
As mentioned in the docs, disable-agent is experimental, and not supported with embedded etcd. Embedded etcd needs an agent so that a node object is created to track etcd cluster membership.

**Comment by Jelly-Fisher-fish** [comment]
I try to run etcd with disable-agent false, it have not  restart yet.
We will try another way to deal with etcd-only.
Thanks for your reply.

**Comment by brandond** [comment]
What are you trying to get out of running dedicated etcd and control-plane nodes without agents? If you could help us understand your use case, we might be able to accommodate it in future releases.

**Comment by Jelly-Fisher-fish** [comment]
We have a cluster with one k3s server which running etcd and master, and every time we try to delete all the pod in one namespace, k3s server will crash and restart. The server which k3s running on with high cpu usage, 100%wa.
That's the reason why we try to separate etcd from server.

**Comment by Jelly-Fisher-fish** [comment]
The number of pods is around 100

**Comment by brandond** [comment]
Ok but why did you disable the agent, instead of just tainting the node to keep workload pods off it?

**Comment by Jelly-Fisher-fish** [comment]
For the reason,
We don't want to see etcd node and master node by kubectl.
And the node may be scheduled when toleration Exists is present on the pod. That might cause some security issues.

**Comment by Jelly-Fisher-fish** [comment]
It's true we were suffer insufficient disk throughput for etcd when server crashed.
We will try to run server with sqlite later on our dev environment.
Thanks a lot, your recommendation is helpful for us.
