### ISSUE TITLE
Documentation - Clarify upgrade wording

### ISSUE THREAD

**Issue by udf2457** [k3s-io/k3s#7095]
At present, the [manual upgrades page](https://docs.k3s.io/upgrades/manual) states the following:

> To upgrade K3s from an older version you can re-run the installation script using the same flags

However this is an unclear statement, namely what is _"the same flags"_ ?

For example, if I originally installed using these flags:

> - server --secrets-encryption --flannel-backend=wireguard-native --cluster-init --tls-san="foo.example.com"

Am I expected to re-specify those ? Because my reading of "the same flags" would be ... yes, you do.

Or if I installed worker nodes using:

> K3S_URL=https://foo.example.com:6443 K3S_TOKEN="foobar" sh -s -

Am I expected to re-specify those ? Because again, my reading of "the same flags" would be ... yes, you do.

**Comment by brandond** [comment]
Yes, the same flags as you used when originally installing on that node. Is there a different way that "the same" could be read?

**Comment by udf2457** [comment]
Thanks @brandond 

Well, the problem then is that your example is confusing.  Because you say _"using the same flags, for example"_ and then your example shows no flags:

> curl -sfL https://get.k3s.io | sh -

**Comment by caroline-suse-rancher** [comment]
@udf2457 I think the implication is that the exact same flags should be specified, and the example is left blank to avoid confusion as users can specify any number of flags upon installation. I will move this to the Backlog for further consideration.
