### ISSUE TITLE
Script to generate custom ca certs ignores existing certs and generates new files on exising cluster using custom certs

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#7100]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single node

**Describe the bug:**
Script ignores the existing certs and generates new certs 
Docs need to be updated as service.key needs to be copied as mentioned in the script

```
Mar 16 20:10:31 ip-172-31-5-18 k3s[1753]: time="2023-03-16T20:10:31Z" level=warning msg="certificate error ID 13590: failed to validate new CA certificates and keys: ServiceKey: old ServiceAccount signing key not in new ServiceAccount key list"
```
[generate-custom-ca-certs.sh
](https://github.com/k3s-io/k3s/blob/master/contrib/util/generate-custom-ca-certs.sh)

**Steps To Reproduce:**
1. mkdir -p /var/lib/rancher/k3s/server/tls
2. curl -sL https://github.com/k3s-io/k3s/raw/master/contrib/util/generate-custom-ca-certs.sh | bash -
3. curl -fL https://get.k3s.io/ | INSTALL_K3S_COMMIT=7fee87d9765d01f1e478b06553b0b100410de289 sh -s - server --cluster-init
5. sudo mkdir -p /opt/k3s/server/tls
6.  cp /var/lib/rancher/k3s/server/tls/root-ca.pem /opt/k3s/server/tls/
7. cp /var/lib/rancher/k3s/server/tls/intermediate-ca.pem /opt/k3s/server/tls/
8. cp /var/lib/rancher/k3s/server/tls/intermediate-ca.key /opt/k3s/server/tls/
9. cp /var/lib/rancher/k3s/server/tls/service.key /opt/k3s/server/tls/
10. curl -sL https://github.com/k3s-io/k3s/raw/master/contrib/util/generate-custom-ca-certs.sh | DATA_DIR=/opt/k3s bash
11. k3s certificate rotate-ca --path=/opt/k3s/server

**Expected behavior:**
Should use existing root-ca cert file
```
Using /usr/bin/openssl: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
Generating additional Kubernetes service account issuer RSA key
Using existing root certificate
Using existing intermediate certificate
Generating k3s-client-ca leaf certificate authority EC key and certificate
Using configuration from .ca/config
```

**Actual behavior:**
Generates new files
```
Using /usr/bin/openssl: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
Generating Kubernetes service account issuer RSA key
Generating root certificate authority RSA key and certificate
Generating intermediate certificate authority RSA key and certificate
Generating k3s-client-ca leaf certificate authority EC key and certificate
Using configuration from .ca/config
```

**Comment by dereknola** [comment]
Documentation around correct use of the certificate command has been updated. This is no longer an issue.
