### ISSUE TITLE
metrics-server can not get metrics from worker node

### ISSUE THREAD

**Issue by liangxiong3403** [k3s-io/k3s#7125]
**Environmental Info:**
K3s Version: 
k3s version v1.25.7+k3s1 (f7c20e23)
go version go1.19.6

Node(s) CPU architecture, OS, and Version: 
Linux k3s-master01 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 servers, 1 agents

NAME           STATUS   ROLES                  AGE     VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
k3s-worker01   Ready    <none>                 9m30s   v1.25.7+k3s1   172.20.209.222   <none>        CentOS Linux 7 (Core)   3.10.0-1160.88.1.el7.x86_64   containerd://1.6.15-k3s1
k3s-master01   Ready    control-plane,master   12m     v1.25.7+k3s1   172.20.209.221   <none>        CentOS Linux 7 (Core)   3.10.0-1160.88.1.el7.x86_64   containerd://1.6.15-k3s1

**Describe the bug:**
when i use 'kubectl top no', i can not get metrics from worker node; i can only get metrics from master node
[root@k3s-master01 ~]# kubectl top no
NAME           CPU(cores)   CPU%        MEMORY(bytes)   MEMORY%     
k3s-master01   73m          3%          1506Mi          39%         
k3s-worker01   <unknown>    <unknown>   <unknown>       <unknown> 

**Steps To Reproduce:**
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=https://172.20.209.221:6443 K3S_TOKEN=mytoken sh -
- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Ensure that the node that the metrics-server pod is running on can reach the other node on its kubelet port  - 10250 by default. If this is not possible in your current environment, you may need to open ports or set up an overlay network between nodes.

**Comment by liangxiong3403** [comment]
@brandond  ;
I think it maybe a problem,beacause
when i use v1.23.17+k3s1 version; this probelm no happen again, i can successfully get metrics from worker node.
frist, i change nothing other than k3s version;
second, k3s version change from v1.25.7+k3s1  to v1.23.17+k3s1
finally, i get metrics from worker no


1. k3s version

NAME           STATUS   ROLES                  AGE     VERSION         INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
k3s-master01   Ready    control-plane,master   4m15s   v1.23.17+k3s1   172.20.209.221   <none>        CentOS Linux 7 (Core)   3.10.0-1160.88.1.el7.x86_64   containerd://1.5.16-k3s2-1-22
k3s-worker01   Ready    <none>                 95s     v1.23.17+k3s1   172.20.209.222   <none>        CentOS Linux 7 (Core)   3.10.0-1160.88.1.el7.x86_64   containerd://1.5.16-k3s2-1-22

2.metrcis return successfully 

[root@k3s-master01 ~]# kubectl top no
NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
`k3s-master01   96m          4%     1399Mi          36% `  
`k3s-worker01   27m          1%     638Mi           16% `      
[root@k3s-master01 ~]# kubectl top po -A
NAMESPACE     NAME                                      CPU(cores)   MEMORY(bytes)   
kube-system   coredns-5cfbb9f57c-tm4j7                  2m           17Mi            
kube-system   local-path-provisioner-5f8bbd68f9-bwjt8   1m           11Mi            
kube-system   metrics-server-65cd754bcd-nkppr           4m           20Mi            
kube-system   svclb-traefik-b0e9a9e5-mcwwf              0m           0Mi             
kube-system   svclb-traefik-b0e9a9e5-mtdp6              0m           0Mi             
kube-system   traefik-5cd8994cdd-nrm6f                  1m           28Mi

**Comment by brandond** [comment]
Possibly a duplicate of https://github.com/k3s-io/k3s/issues/7096 then

**Comment by liangxiong3403** [comment]
I got it, thanks a lot
