### ISSUE TITLE
k3s broken on Ubuntu 22.04 64bit ARM64 on RaPi

### ISSUE THREAD

**Issue by clarkezone** [k3s-io/k3s#7155]
**Environmental Info:**
K3s Version: v1.25.7+ks1

Node(s) CPU architecture, OS, and Version: 

Linux rapi-c3-n1 5.15.0-1025-raspi #27-Ubuntu SMP PREEMPT Thu Feb 16 17:09:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:

1 server, 1agent workload on single node

**Describe the bug:**

After system boot, first few kubeapis succeed until:
`The connection to the server 100.118.251.7:6443 was refused - did you specify the right host or port?`
Appears that server is crashing

**Steps To Reproduce:**

- Installed K3s: 
Install vanilla 22.04 64 bit for RaPi on a RaPi 4 (i used an 8GB)
Install latest k3s
Attempt to query / use the cluster

**Expected behavior:**

**Actual behavior:**

API will timeout, cluster unusable

**Additional context / logs:**

Mar 27 15:42:37 rapi-c3-n1 systemd[1]: Started Lightweight Kubernetes.
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: time="2023-03-27T15:42:37Z" level=info msg="Waiting for cloud-controller-manager privileges to become available"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.505506   16224 kubelet_network_linux.go:63] "Initialized iptables rules." protocol=IPv4
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.576965   16224 kubelet_node_status.go:108] "Node was previously registered" node="rapi-c3-n1"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.577303   16224 kubelet_node_status.go:73] "Successfully registered node" node="rapi-c3-n1"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: time="2023-03-27T15:42:37Z" level=info msg="Starting the netpol controller version v1.5.2-0.20221026101626-e01045262706, built on 2023-03-10T22:01:42Z, go1.19.6"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.639862   16224 network_policy_controller.go:163] Starting network policy controller
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: time="2023-03-27T15:42:37Z" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.755423   16224 kubelet_network_linux.go:63] "Initialized iptables rules." protocol=IPv6
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.755558   16224 status_manager.go:161] "Starting to sync pod status with apiserver"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.755625   16224 kubelet.go:2010] "Starting kubelet main sync loop"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: E0327 15:42:37.755840   16224 kubelet.go:2034] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: E0327 15:42:37.857277   16224 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.942663   16224 cpu_manager.go:213] "Starting CPU manager" policy="none"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.942788   16224 cpu_manager.go:214] "Reconciling" reconcilePeriod="10s"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.942863   16224 state_mem.go:36] "Initialized new in-memory state store"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.943651   16224 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.943723   16224 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.943754   16224 policy_none.go:49] "None policy: Start"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.986614   16224 memory_manager.go:168] "Starting memorymanager" policy="None"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.986820   16224 state_mem.go:35] "Initializing new in-memory state store"
Mar 27 15:42:37 rapi-c3-n1 k3s[16224]: I0327 15:42:37.987564   16224 state_mem.go:75] "Updated machine memory state"
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: E0327 15:42:38.073604   16224 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.081429   16224 network_policy_controller.go:175] Starting network policy controller full sync goroutine
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.176278   16224 apiserver.go:52] "Watching apiserver"
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.182834   16224 manager.go:447] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.187621   16224 plugin_manager.go:118] "Starting Kubelet Plugin Manager"
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.233520   16224 kube.go:151] Node controller sync successful
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.233682   16224 vxlan.go:138] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=falseMar 27 15:42:38 rapi-c3-n1 k3s[16224]: time="2023-03-27T15:42:38Z" level=fatal msg="flannel exited: operation not supported"
Mar 27 15:42:38 rapi-c3-n1 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 15:42:38 rapi-c3-n1 systemd[1]: k3s.service: Failed with result 'exit-code'.
Mar 27 15:42:38 rapi-c3-n1 systemd[1]: k3s.service: Consumed 25.932s CPU time.

**Comment by galal-hussein** [comment]
@clarkezone Thanks for opening the issue, can you start k3s with debug logs, so that we can get more info on flannel, and why is it failing to start:
```
Mar 27 15:42:38 rapi-c3-n1 k3s[16224]: I0327 15:42:38.233682 16224 vxlan.go:138] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=falseMar 27 15:42:38 rapi-c3-n1 k3s[16224]: time="2023-03-27T15:42:38Z" level=fatal msg="flannel exited: operation not supported"
```

**Comment by brandond** [comment]
You're probably missing the vxlan kernel module. See https://docs.k3s.io/advanced#raspberry-pi

**Comment by clarkezone** [comment]
That was in, thanks @brandond!
