### ISSUE TITLE
CIDR optimization in RHEL doc

### ISSUE THREAD

**Issue by tangentsoft** [k3s-io/k3s#7192]
[This section of the docs](https://docs.k3s.io/advanced#red-hat-enterprise-linux--centos) gives two `firewalld` commands that I believe can be consolidated thus:

```
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/15
```

The expansion of the CIDR range from two /16s to a single /15 covers both subnets.

While you're in there, you should drop the recommendation to disable the firewall. Not only is it bad advice generally, the `firewalld` commands you then give solve the problem.

**Comment by brandond** [comment]
It is true that the two default CIDRs can be aggregated into a single /15, however this won't be true for all CIDRs used by users, so it's good to explicitly note that both the cluster and service CIDRs need to be covered by plainly showing both CIDRs being trusted. Many users are not going to intuit that the two default CIDRs have been aggregated into a single /15.

Similarly, the recommendation is still to disable firewalld. While it can be made to work, we still don't technically support it.
