### ISSUE TITLE
Client loadbalancer does not close connections to removed servers

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7193]
K3s tracking issue for:
* https://github.com/rancher/rke2/issues/4060

When a server node is removed from the cluster, the loadbalancer endpoint watch removes it from the server list, which will prevent new connections from being sent to that server. It does not however close currently active connections to that server. If the server continues running but in a degraded state (as the RKE2 issue shows does happen) clients will stay connected and experience an outage instead of being forced to reconnect to an active server.

We should track open connections to each server, and ensure that they are closed when the server is removed from the loadbalancer.

**Comment by est-suse** [comment]
```
NAME              STATUS   ROLES                       AGE     VERSION
ip-172-31-0-215   Ready    control-plane,etcd,master   7m40s   v1.26.3+k3s-6b51ed47
ip-172-31-3-37    Ready    <none>                      4m46s   v1.26.3+k3s-6b51ed47
ip-172-31-4-224   Ready    control-plane,etcd,master   6m2s    v1.26.3+k3s-6b51ed47
ip-172-31-5-182   Ready    control-plane,etcd,master   5m33s   v1.26.3+k3s-6b51ed47
```
