### ISSUE TITLE
[release-1.24] Simultaneously started K3s servers may race to create CA certificates when using external SQL

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7224]
* #7185 Backport

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced (on the first try!) using VERSION=v1.24.12+k3s1
Best effort validation using RC VERSION=

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```

*Cluster Configuration:*

5 server nodes simultaneous joins onto postgres 14 DB hosted by t2.micro Ubuntu 22.04

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: calcifiedlies
selinux: true
protect-kernel-defaults: true
datastore-endpoint: postgres://k3s:carsap@veryboogeymanofyou:5432/kubernetes
```

<details><summmary><h4>Unable to reproduce consistently with five server nodes</h4></summary>




```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.24.12+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh (simultaneous across all nodes) 
$ sudo journalctl -u k3s | grep -i "ecdsa" | grep -i "unable" //run to catch the error in logs. 
$ sudo INSTALL_K3S_VERSION=v1.24.13-rc1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig
$ kgn
$ sudo journalctl -u k3s | grep -i "ecdsa" | grep -i "unable" 
$ get_report //generate this template
```

**Results:**

Thankfully on the v1.24.12+k3s1 I was able to trigger this on the first attempt using an external DB. 

$ sudo journalctl -u k3s | grep -i "ecdsa" | grep -i "unable"
```
Apr 14 03:07:33 ip-LOCALIP k3s[14493]: time="2023-04-14T03:07:33Z" level=warning msg="unable to verify existing certificate: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"k3s-server-ca@1681441464\") - signing operation may change certificate issuer"
```

</details>


This seems to still be an issue on v1.24.13-rc1+k3s1

$ kgn
```
NAME               STATUS     ROLES                  AGE   VERSION
ip-172-31-16-12    Ready      control-plane,master   17s   v1.24.13-rc1+k3s1
ip-172-31-20-46    Ready      control-plane,master   17s   v1.24.13-rc1+k3s1
ip-172-31-18-41    Ready      control-plane,master   16s   v1.24.13-rc1+k3s1
ip-172-31-20-241   NotReady   control-plane,master   6s    v1.24.13-rc1+k3s1
ip-172-31-17-133   NotReady   control-plane,master   4s    v1.24.13-rc1+k3s1
```

 We may need an rc2 for k3s on this race condition on the v1.24 branch

simultaneous installation across five nodes

$ sudo INSTALL_K3S_VERSION=v1.24.13-rc1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
```
[INFO]  Using v1.24.13-rc1+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.24.13-rc1+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.24.13-rc1+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority

![Screenshot 2023-04-13 at 8 17 08 PM](https://user-images.githubusercontent.com/8961630/231933249-ffc6782c-f7e2-490e-8982-190d373fbafd.png)


After a couple of minutes (nearly literally 2 minutes 30 seconds) the state seems to resolve and the cluster does begin to report as Ready

$ kgn
```
NAME               STATUS   ROLES                  AGE     VERSION
ip-172-31-20-241   Ready    control-plane,master   2m18s   v1.24.13-rc1+k3s1
ip-172-31-17-133   Ready    control-plane,master   2m16s   v1.24.13-rc1+k3s1
ip-172-31-18-41    Ready    control-plane,master   2m28s   v1.24.13-rc1+k3s1
ip-172-31-16-12    Ready    control-plane,master   2m29s   v1.24.13-rc1+k3s1
ip-172-31-20-46    Ready    control-plane,master   2m29s   v1.24.13-rc1+k3s1
```


Any thoughts or additional opinion here @brandond ?

**Comment by brandond** [comment]
@VestigeJ please grab the following from all the nodes:
* kubectl get node -o yaml
* K3s journald log
* Contents of /var/lib/rancher/k3s/server/TLS

**Comment by VestigeJ** [comment]
Just documenting - these logs were sent via Slack Friday morning

**Comment by brandond** [comment]
It looks to me like the race condition in question has been resolved; all cluster members have the correct CA certificates which is what this issue is scoped to fixing. We can see that the server in question found the bootstrap key locked, and properly waited for another server to populate it:
```console
Apr 14 03:14:40 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:40Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Apr 14 03:14:40 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:40Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/0085d5372d5c39a4b3a6b12330b17b21cc76d5faef3e4785cf3a1a85722607b6"
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Starting k3s v1.24.13-rc1+k3s1 (3f79b289)"
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Configuring postgres database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Database tables and indexes are up to date"
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Kine available at unix://kine.sock"
Apr 14 03:14:43 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:43Z" level=info msg="Bootstrap key is locked - waiting for data to be populated by another server"
Apr 14 03:14:44 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:44Z" level=info msg="Reconciling bootstrap data between datastore and disk"
Apr 14 03:14:44 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:44Z" level=debug msg="/var/lib/rancher/k3s/server/cred directory is empty"
Apr 14 03:14:44 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:14:44Z" level=debug msg="One or more certificate directories do not exist; writing data to disk from datastore"
```

It looks like there is a bit of thrashing amongst the leader-elected controllers as they all try to take leases at the same time. The database struggles a bit and there are a bunch of "Slow SQL" warnings until things settle out, at which point everything returns to normal.
* `Apr 14 03:14:47 ip-172-31-16-12 k3s[20398]: E0414 03:14:47.668324   20398 controller.go:166] Unable to perform initial Kubernetes service initialization: Service "kubernetes" is invalid: spec.clusterIPs: Invalid value: []string{"10.43.0.1"}: failed to allocate IP 10.43.0.1: provided IP is already allocated`
* `Apr 14 03:18:47 ip-172-31-16-12 k3s[20398]: time="2023-04-14T03:18:47Z" level=info msg="Slow SQL (started: 2023-04-14 03:18:46.792299158 +0000 UTC m=+243.789407949) (total time: 1.054899928s):  SELECT * FROM ( SELECT ( SELECT MAX(rkv.id) AS id FROM kine AS rkv), ( SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value FROM kine AS kv JOIN ( SELECT MAX(mkv.id) AS id FROM kine AS mkv WHERE mkv.name LIKE $1 GROUP BY mkv.name) AS maxkv ON maxkv.id = kv.id WHERE kv.deleted = 0 OR $2 ) AS lkv ORDER BY lkv.theid ASC  : [[/registry/health false]]"`
* `Apr 14 03:19:42 ip-172-31-16-12 k3s[20398]: E0414 03:19:42.059477   20398 leaderelection.go:334] error initially creating leader election record: leases.coordination.k8s.io "k3s" already exists`

I would consider this as validated successfully. You might re-run the test again with another more performant datastore (either higher capacity postgres, or mysql/mariadb) to see if things come up faster - but the issue in question has been resolved.

**Comment by VestigeJ** [comment]
Confirming this worked as expected by removing the extra server arg from the subsequent control plane nodes and solely targeting the database endpoint for cluster joining.
