### ISSUE TITLE
Add support for SLE Micro 5.4

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#7250]
This should include v1.25, v1.26, and v1.27

**Comment by grisu48** [comment]
This would be great! Will there also be support for SLEM 5.1, 5.2 or 5.3?

Currently installing k3s on SLEM works, with the exception of the SELinux rules:

```
2023-05-01 11:13:39 Executing `zypper --gpg-auto-import-keys install -y k3s-selinux`:
Refreshing service 'SUSE_Linux_Enterprise_Micro_5.2_x86_64'.
Building repository 'SUSE-MicroOS-5.2-Pool' cache [....done]
Error building the cache:
[rancher-k3s-common-stable|https://rpm.rancher.io/k3s/stable/common/slemicro/noarch] Valid metadata not found at specified URL
History:
 - [rancher-k3s-common-stable|https://rpm.rancher.io/k3s/stable/common/slemicro/noarch] Repository type can't be determined.

Warning: Skipping repository 'Rancher K3s Common (stable)' because of the above error.
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
'k3s-selinux' not found in package names. Trying capabilities.
No provider of 'k3s-selinux' found.
2023-05-01 11:13:41 Application returned with exit status 104.
```

**Comment by rancher-max** [comment]
We do actually have support for those today with the exception of the SELinux rules like you mentioned! There has been some work done to resolve that, but we are trying to add support for more than just SLEM as part of it and have encountered a few bugs where we've been unable to move it out of the `testing` branch.

That being said, you are free to use that (in a "play" environment since it is definitely not prod ready) if you want to try it out! The package is available at https://github.com/k3s-io/k3s-selinux/releases/tag/v1.3.testing.4 and can be installed, for example, by specifying the testing channel during install:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.9+k3s1 INSTALL_K3S_CHANNEL=testing sh -
```

**Comment by grisu48** [comment]
Oh nice, thank you! It's great to see that this is being worked on and I can't wait for this to also land in the `stable` channel :slightly_smiling_face: 

Great work :+1:

**Comment by est-suse** [comment]
Tested, please refer to SLE Micro 5.4 K3s Certification tests in confluence

**Comment by rancher-max** [comment]
For community users who don't have access to our internal confluence, this covers the following scenarios
- Fresh Installation and run sonobuoy conformance tests
- Upgrade using system-upgrade-controller
- Etcd snapshots/restoring from backup via `cluster-reset-restore-path`
- Secrets encryption
- Certificate rotation
- Dualstack

All scenarios passed using v1.25.9+k3s1, v1.26.4+k3s1 and v1.27.1+k3s1. Upgrade scenario performed using v1.25.8, v1.26.3, and v1.26.4 and upgraded to the aforementioned versions.

Remaining tests being validated before closure:
- Install using the [pending install script](https://raw.githubusercontent.com/galal-hussein/k3s/add_el9_selinux_rpm/install.sh) and `testing` channel for new k3s-selinux RPM.
- ARM64 Install and import into rancher
- Install k3s as local management cluster for Rancher
- HA installation using an external DB (instead of embedded etcd which is used in the other validations)

**Comment by est-suse** [comment]
The  following scenarios have been coverted:

- Fresh Installation and run sonobuoy conformance tests
- Upgrade using system-upgrade-controller
- Etcd snapshots/restoring from backup via cluster-reset-restore-path
- Secrets encryption
- Certificate rotation
- Dualstack
- Install using the [pending install script](https://raw.githubusercontent.com/galal-hussein/k3s/add_el9_selinux_rpm/install.sh) and testing channel for new k3s-selinux RPM.
- ARM64 Install and import into rancher
- Install k3s as local management cluster for Rancher
- HA installation using an external DB (instead of embedded etcd which is used in the other validations)
