### ISSUE TITLE
[KINE] etcd integration tests

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#726]
Create etcd integration tests

**Comment by caroline-suse-rancher** [comment]
@dereknola do these exist now?

**Comment by dereknola** [comment]
Yes, this has been addressed in a variety of ways, but most directly in the drone tests we do on ever PR. We test each backend we support with the same set of tests

**Comment by caroline-suse-rancher** [comment]
Beautiful. Thank you!
