### ISSUE TITLE
iptables are not clean after uninstalling k3s and rebooting the server

### ISSUE THREAD

**Issue by BlagovestDobrev** [k3s-io/k3s#7261]
**Environmental Info:**
K3s Version: 
all

**Describe the bug:**
When uninstalling  k3s with /usr/local/bin/k3s-uninstall.sh the iptables stay as it was before, the rules are not removed.

If I run /usr/local/bin/k3s-killall.sh before that and then run the uninstallation script and reboot the server the iptables are as they are before running k3s-killall.sh. 

**Steps To Reproduce:**

iptables -nvL
ip6tables -nvL

/usr/local/bin/k3s-killall.sh

iptables -nvL
ip6tables -nvL

/usr/local/bin/k3s-uninstall.sh

reboot the server 

iptables -nvL
ip6tables -nvL

iptables are the same as before uninstalling.

** Root cause **
In order this to be fix in the end of /usr/local/bin/k3s-uninstall.sh there should be two lines to save the iptables rules permanently, after k3s-killall.sh has been executed and already cleaned the iptables rules before executing  k3s-uninstall.sh:

iptables-save -f /etc/iptables/rules.v4 
ip6tables-save -f /etc/iptables/rules.v6

This is tested on Linux raspberry pi OS, for other OS the default path of the iptables file might be  different.

**Comment by brandond** [comment]
> In order this to be fix in the end of /usr/local/bin/k3s-uninstall.sh there should be two lines to save the iptables rules permanently, after k3s-killall.sh has been executed
>
> This is tested on Linux raspberry pi OS, for other OS the default path of the iptables file might be different.

It is up to the host operating system to permanently store changes to the iptables rules if they are intended to be persisted across reboots. We don't save the rules to disk at any point; if you at some point saved the Kubernetes-managed rules to disk that is not something we are expected to correct.

**Comment by BlagovestDobrev** [comment]
Ok, Thank you!
