### ISSUE TITLE
Add page size check in `check-config` command

### ISSUE THREAD

**Issue by cncal** [k3s-io/k3s#7288]
**Is your feature request related to a problem? Please describe.**

When I trying to deploy k3s on my arm64 servers, I noticed an important note in https://docs.k3s.io/installation/requirements#architecture that **the OS must use a 4k page size**, but nothing abnormal when I run the `k3s check-config` command. Considering that page size isn't 4k does have serious consequences (https://github.com/k3s-io/k3s/issues/6708), I think it's necessary to add page size check in `k3s check-config` if the machine architecture is `aarch64/arm64`.

**Describe the solution you'd like**

Add page size check in `k3s check-config` if the machine architecture is `aarch64/arm64`.

**Describe alternatives you've considered**

Print  a warning log when k3s service starts.

**Additional context**

None.

**Comment by dereknola** [comment]
This will likely be fixed in the next release.
