### ISSUE TITLE
 Moving "Agentless Servers" out of Experimental Feature for K3S Project

### ISSUE THREAD

**Issue by karthik1729** [k3s-io/k3s#7289]
As a user of K3S, I have been exploring the available features and have been particularly interested in the "Agentless Servers" functionality. I have found this feature to be quite useful and have been successfully utilizing it in my projects. However, I noticed that it is still classified as an experimental feature.

I would like to inquire about the current status of the "Agentless Servers" feature and the potential issues that may be preventing it from moving out of the experimental stage. I understand that experimental features may not be fully stable or production-ready, and I would like to know about any known issues or limitations associated with the "Agentless Servers" feature.

Additionally, I would like to understand the process of moving a feature out of the experimental stage in the K3S project. This information would be helpful for the community members who are interested in contributing to the project and ensuring the stability and reliability of the "Agentless Servers" feature.

To facilitate this discussion, I kindly request the following information:

1. Known Issues: Please provide a list of known issues or limitations associated with the "Agentless Servers" feature. This will help us understand the current state of the feature and the improvements needed before it can be considered for a stable release.

2. Process for Moving Out of Experimental Stage: Could you outline the process for moving a feature from experimental to stable in the K3S project? This will help the community understand the steps and requirements necessary for the "Agentless Servers" feature to graduate from experimental status.

3. How to Contribute: If there are any specific areas where the community can contribute to help expedite the process of moving "Agentless Servers" out of the experimental stage, please let us know. This information will enable us to actively participate in the project and work towards a stable release of the feature.

I believe that the "Agentless Servers" feature has the potential to greatly benefit the K3S project and its users, and I am eager to see it become a stable and reliable feature. I appreciate your time and consideration in addressing this request, and I look forward to your response.

**Comment by brandond** [comment]
Closing this in favor of the duplicate at https://github.com/k3s-io/k3s/discussions/7290
