### ISSUE TITLE
"iptables-save: command not found" upgrading from v1.25.7+k3s1 to v1.26.3+k3s1 on minimized Ubuntu Server

### ISSUE THREAD

**Issue by rlipscombe** [k3s-io/k3s#7291]
**Environmental Info:**
K3s Version: 

Upgrading from:

k3s version v1.25.7+k3s1 (f7c20e23)
go version go1.19.6

To:

k3s version v1.26.3+k3s1 (01ea3ff2)
go version go1.19.7

Node(s) CPU architecture, OS, and Version: 

Ubuntu 22.04.2 LTS (minimized)
Linux roger-nuc1 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server, 4 agents

**Describe the bug:**

When upgrading from v1.25.7+k3s1 to v1.26.3+k3s1 the upgrader outputs the following:

```
roger@roger-nuc1:~ % curl -sfL https://get.k3s.io | K3S_URL=https://...:6443 K3S_TOKEN=K... sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.26.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.26.3+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.26.3+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s-agent.service → /etc/systemd/system/k3s-agent.service.
sudo: iptables-save: command not found
sudo: iptables-restore: command not found
```

The warnings about iptables-save and iptables-restore are ... not reassuring. Are they harmful? Should the upgrader check that the commands exist first?

Normal (not minimized) Ubuntu server doesn't have this problem on my other nodes.

**Comment by dereknola** [comment]
@rbrtbnfgl maybe you could comment on whether the iptables-save/restore commands are necessary if the user never had it to begin with. IFAIK the commands are only relevant in the `k3s-killall.sh` script, and was related to a change in iptables chains from a flannel update.

**Comment by rbrtbnfgl** [comment]
The used install script wasn't the one on master?

**Comment by brandond** [comment]
The idea was to add them to the install script because kube-router doesn't have logic in it to properly clean up old rules. We just have the installer wipe out all the KUBE- rules so that K3s starts up fresh.

However it seems like for some reason the checks to confirm that the `iptables-save` command is available are not working in this environment? Either that or they are available for the `roger` user but not to the `sudo` shell, which seems wrong.

@rlipscombe can you confirm the output of `command -v iptables-save` as both your `roger` user, and as `root`?

**Comment by rlipscombe** [comment]
> The used install script wasn't the one on master?

It would presumably have been the one at v1.26.3+k3s1.

> can you confirm the output of `command -v iptables-save` as both your `roger` user, and as `root`?

At this point, I've installed iptables on the relevant node, but if I install a completely bare (minimized) Ubuntu 22.04 to a VM, I can see that `command -v iptables-save` outputs nothing and returns exit code 1.

I see that the `service_enable_and_start` function (since https://github.com/k3s-io/k3s/commit/d9f40d4f5b4776164322035499fabedea77f5f52 -- i.e. not in v1.26.3+k3s1) now checks for iptables-save and iptables-restore. I note, however, that the generated killall script still just runs them blindly -- https://github.com/k3s-io/k3s/blob/master/install.sh#L742.

**Comment by rlipscombe** [comment]
> The install script is always served off the master branch; it is not versioned.

TIL. Thanks.

**Comment by ppuschmann** [comment]
But also a completely fresh install triggers
```
Created symlink /etc/systemd/system/multi-user.target.wants/k3s-agent.service → /etc/systemd/system/k3s-agent.service.
sh: 972: iptables-save: not found
sh: 972: iptables-restore: not found
```
and exits with `127`.

`k3s` is then not started automatically after installation.

In https://docs.k3s.io/installation/requirements there's nothing that tells me explicitly to install `iptables` and I found even (maybe outdated) instructions that purged `iptables` and installed `nftables`.

So on my freshly installed machine there are no `iptables` installed.
What is the recommendation?

**Comment by rlipscombe** [comment]
I also get the paths to the iptables scripts, as if the redirection to `/dev/null` at https://github.com/k3s-io/k3s/blob/master/install.sh#L970 isn't working.

**Comment by rlipscombe** [comment]
Oh. I wonder... On Ubuntu, `iptables-save` (etc.) is managed via `/etc/alternatives`. Does `command -v` sometimes get tripped up by a symlink that doesn't point anywhere?

**Comment by rbrtbnfgl** [comment]
could you try to download the script and then modify it removing the `&> /dev/null` and executing it manually?

**Comment by aganesh-suse** [comment]
OS: Ubuntu 22.04

As a workaround to reproduce the issue above, moved the iptables-save and iptables-restore: 
sudo mv /usr/sbin/iptables-restore /usr/sbin/iptables-restore-bak
sudo mv /usr/sbin/iptables-save /usr/sbin/iptables-save-bak
command -v iptables-save; echo $?
1
command -v iptables-restore; echo $?
1

When using install script from here: 
https://raw.githubusercontent.com/k3s-io/k3s/v1.27.1-rc1%2Bk3s1/install.sh

Was able to see the error lines: 
sudo: iptables-restore: command not found
sudo: iptables-save: command not found

kubectl get nodes - showed the previous version of the k3s. a "sudo systemctl restart k3s" updated the k3s version of the nodes. 


When using the install script from here: "https://get.k3s.io"
I no longer see the iptables-save and iptables-restore command not found lines while running upgrades. 
'kubectl get nodes' shows the correct upgraded k3s version - without having to manually run a k3s service restart. 

We can mark this bug as verified - working as expected in the latest install script.

**Comment by ntx-ben** [comment]
This is also breaking under Alpine Linux using v1.24.10+k3s1. I see it is now fixed (using `command -v`) in latest versions (i.e. v1.28.1+k3s1), however it would be great if this fix was back-ported to previous versions where this new command was introduced...
