### ISSUE TITLE
Cannot install K3s with noexec flag in /var

### ISSUE THREAD

**Issue by FranchSpamch** [k3s-io/k3s#7296]
**Environmental Info:**
K3s Version: 

```
k3s version v1.24.10+k3s1
```

Node(s) CPU architecture, OS, and Version: 

```
Linux edm00 4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

Single-node K3s cluster, using embedded etcd as cluster storage database.

**Describe the bug:**

I am trying to harden the OS of the cluster according to the CIS Benchmark for Level 1 Servers. However, the following rule fails:
* CCE-82008-4: Add noexec Option to /var.

This is because k3s stores some binaries in the `/var` partition.

**Expected behavior:**

Being able to install k3s in a system with the `noexec` flag in the `/var` partition.
According to the [Linux Hierarchy](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05.html#purpose31) /var should only contain data, no executables.

**Actual behavior:**

Unable to install k3s in a system with the `noexec` flag in the `/var` partition.

**Additional context / logs:**

[Example in the code of binaries being stored in /var](https://github.com/k3s-io/k3s/commit/f6153201bafa49fa424eef792ee5754f77c70370#diff-bdecef8ec55fbf732f2438ef954879a2b300f9b04ac984e1038a3b154162ff02R14-R21).

**Comment by brandond** [comment]
That's correct. If you have `/var` on a dedicated partition that is mounted `noexec`, K3s will not work in its default configuration.

You are welcome to change the location that k3s uses from `/var/lib/rancher/k3s` to something else using the `--data-dir` flag.
