### ISSUE TITLE
dynamiclistener adds unwanted SubjectAlternativeName entries to certificate

### ISSUE THREAD

**Issue by optix2000** [k3s-io/k3s#7312]
**Is your feature request related to a problem? Please describe.**
While I understand dynamiclistener may be useful to generate certificates on the fly when the final config is not known, in most cases `--tls-san` can cover the case where a specific SAN is needed and known before hand.

Right now, if you do not need dynamic certificates, fuzzers will add random SAN's to the certificate. Depending on the fuzzer, this can actually add quite a few SAN's to the cert, polluting it pretty heavily.

**Describe the solution you'd like**
Add an option to disable dynamiclistener so random SNI requests from fuzzers will not pollute the cert and annotations.

**Describe alternatives you've considered**
Have a script prune any excess annotations that are not configured by the user on a regular basis.

**Additional context**
Related to #4542

**Comment by brandond** [comment]
You can actually "freeze" the certificate by running the following command:
`kubectl annotate secret -n kube-system k3s-serving listener.cattle.io/static=true`

IMPORTANT CAUTION: Note that this will also prevent it from getting renewed when it expires!

The dynamiclistener library itself does have a callback we could make use of to filter CNs to prevent unwanted entries, but K3s does not currently wire this up to a CLI flag. We can probably do some thinking about how we would want to make that work.

**Comment by cheddarwhizzy** [comment]
Does anyone know how SANs can be injected into a cert on a private server? We're pretty affected by this - setting the annotation on the k3s-serving secret does work, but since we're using AWS ELBs and the public IP's change from time to time, keeping this static isn't a great solution. 

Is there an API call on the k3s server that's exposed to update this cert that I should be blocking?

**Comment by brandond** [comment]
> Does anyone know how SANs can be injected into a cert on a private server?

I'm not sure I understand the question. Are you asking how to manually add IP SANs to the cert to stay in sync with the ELB's addresses? There is no direct API for updating the SANs on the cert. You would have to:
* Remove the static annotation
* Make a connection or request through the ELB using the new IP address in the host header or TLS SNI handshake
* Re-add the static annotation

This sort of dynamic certificate validity is exactly what dynamiclistener is designed to handle; if you turn it off you are making more work for yourself.

I am somewhat confused why you'd need this though, if you are connecting through an ELB you should always be using the ELB DNS address, and not need any IP SANs for the actual addresses in use by the load-balancer.

**Comment by cheddarwhizzy** [comment]
You can see all the bogus SANs on one of my k3s control planes by running:
````
echo | openssl s_client -showcerts -connect k3s-college-adaptor.ci.ccctechcenter.org:443  2>/dev/null | openssl x509 -text | grep DNS
```

Typically when I create certs, I specify the SANs. My question is how is this able to be tampered with from outside my servers? Clearly some scrubbing process some hacker created is doing this - I have no association with `iam.stage-lb-bridge.kyndryl.com` or 99% of the DNS:* you see in that command output

**Comment by cheddarwhizzy** [comment]
If I leave the secret set to not static, I'll eventually run into the error from this [discussion](https://github.com/k3s-io/k3s/discussions/7420)

**Comment by brandond** [comment]
> I'm just more interested in how those random string DNS records are added to the mix

Dynamiclistener adds SANs for any hostname or IP address requested via a HTTP Host header or TLS SNI handshake. It is designed to allow you to add or remove servers without having to manually regenerate the certificate. The downside (as you noted) is that this allows for SAN stuffing.

**Comment by brandond** [comment]
Steps to reproduce for QA:

```bash
echo QUIT | openssl s_client -servername foo.example.com -connect HOSTNAME:6443 | openssl x509 -noout -text
```

On current releases:
- note that the `X509v3 Subject Alternative Name:` field adds `foo.example.com` and any other value listed in the example command.

On fixed releases:
- note that the `X509v3 Subject Alternative Name:` field does not list any values other than hostnames or IPs of the Kubernetes apiserver, cluster servers, or values requested via the --tls-san option.

**Comment by ShylajaDevadiga** [comment]
### Validated on branch using commit id 9702f92345feb447a35cbebe0ae22a9129e09776
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
```
> cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```

*Cluster Configuration:*
Single node

*Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
write-kubeconfig-mode: "0644"
tls-san:
  - fake.fqdn.value
cluster-init: true
```
 ## Steps to reproduce

1. Copy config.yaml
2. Install k3s
3. Pass a hostname to servername and verify if it listed in the example command below under X509v3 Subject Alternative Name

echo QUIT | openssl s_client -servername foo.example.com -connect hostname -i :6443 | openssl x509 -noout -text

**Replication results:**
X509v3 Subject Alternative Name: field adds foo.example.com listed in the example command
```
ec2-user@ip-172-31-2-58:~> k3s -v
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6
```
```
ec2-user@ip-172-31-2-58:~> echo QUIT | openssl s_client -servername foo.example.com -connect `hostname -i `:6443 | openssl x509 -noout -text
...
            X509v3 Subject Alternative Name: 
                DNS:fake.fqdn.value, DNS:foo.example.com, DNS:ip-172-31-2-58, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:172.31.2.58, IP Address:<REDACTED>, IP Address:0:0:0:0:0:0:0:1
```
**Validation results:**
X509v3 Subject Alternative Name: field does not list any values other than hostnames or IPs of the Kubernetes apiserver, cluster servers, or values requested via the --tls-san
```
> k3s -v
k3s version v1.27.4+k3s-9702f923 (9702f923)
go version go1.20.6
```
```
ec2-user@ip-172-31-2-58:~> echo QUIT | openssl s_client -servername foo.example.com -connect `hostname -i `:6443 | openssl x509 -noout -text
...
            X509v3 Subject Alternative Name: 
                DNS:fake.fqdn.value, DNS:ip-172-31-4-151, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:172.31.4.151, IP Address:3.133.122.220, IP Address:0:0:0:0:0:0:0:1
```

**Comment by discordianfish** [comment]
That seems like a huge DoS issue? It seems trivial to spam any open apiserver, unauthenticated, until the max size for the secret is reached or until the apiserver just gives up?
