### ISSUE TITLE
k3s can not exec on OS: ubuntu 22.10 [787995 segmentation fault  k3s server]

### ISSUE THREAD

**Issue by jack-liew** [k3s-io/k3s#7342]
**Environmental Info:**
K3s Version: 
K3S: 1.26.4, 1.26.3

Node(s) CPU architecture, OS, and Version: 

OS: ubuntu 22.10,
CPU:intel 13400

Cluster Configuration:

**Describe the bug:**

![image](https://user-images.githubusercontent.com/102201538/233796536-80029dbc-1694-48d4-81ca-15601cf2ff4c.png)

**Steps To Reproduce:**

* 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Please fill out the issue template.
