### ISSUE TITLE
`--tls-san` should accept a comma-separated list, in addition to repeated use of the flag

### ISSUE THREAD

**Issue by e-minguez** [k3s-io/k3s#7365]
**Environmental Info:**
K3s Version: 

```
k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8
```

Node(s) CPU architecture, OS, and Version: 

`Linux cp01 5.14.21-150400.24.46-default #1 SMP PREEMPT_DYNAMIC Thu Feb 9 08:38:18 UTC 2023 (2d95137) aarch64 aarch64 aarch64 GNU/Linux`

Cluster Configuration:

Single node with `--tls-san=192.168.205.10,192.168.205.10.sslip.io`

**Describe the bug:**

Ideally, the SANs should be processed and added as DNS: (if provided a hostname) or IP Address: (if provided an IP). Currently they are all added as DNS 

**Steps To Reproduce:**

Install a k3s single node with `--tls-san=192.168.205.10,192.168.205.10.sslip.io`, observe the `/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt` file.

**Expected behavior:**

```
openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:192.168.205.10, DNS:192.168.205.10.sslip.io, DNS:localhost, DNS:cp01, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:192.168.205.89, IP Address:10.43.0.1
```

**Actual behavior:**

```
openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:192.168.205.10,192.168.205.10.sslip.io, DNS:localhost, DNS:cp01, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:192.168.205.89, IP Address:10.43.0.1
```

**Additional context / logs:**

Essentially, currently it is `DNS:192.168.205.10,192.168.205.10.sslip.io` and I think it should be `IP Address:192.168.205.10, DNS:192.168.205.10.sslip.io`

**Comment by dereknola** [comment]
We already do have that functionality builtin, see https://github.com/k3s-io/k3s/blob/master/pkg/daemons/control/deps/deps.go#L529 but its possible the IPs you have given are breaking the `ParseIP` logic. Let me check.

**Comment by brandond** [comment]
`--tls-san` can be repeated, but it does not take a comma-separated list. The comma-splitting behavior is not part of the CLI framework, and only a few args support support that.

What you want is:
`--tls-san=192.168.205.10 --tls-san=192.168.205.10.sslip.io`.

We could consider this a feature request to allow for comma-separated lists in addition to repeated use of the flag.

**Comment by e-minguez** [comment]
> `--tls-san` can be repeated, but it does not take a comma-separated list. The comma-splitting behavior is not part of the CLI framework, and the few args that do support it have specific code to do so.
> 
> What you want is: `--tls-san=192.168.205.10 --tls-san=192.168.205.10.sslip.io`
> 
> We could consider this a feature request to allow for comma-separated lists in addition to repeated use of the flag.

Interesting. I didn't imagine it can be done that way based on the docs or the built-in help in k3s. I don't think comma-separated lists are really needed but I guess the issue should be to clarify that usage in the docs or the built-in help instead. I'm closing this and will follow up with a PR to clarify the usage. Thanks 👍

**Comment by dereknola** [comment]
Yeah I'll probably have it out today

**Comment by VestigeJ** [comment]
$ cat validation_template.md


##Environment Details
Initial version used for comparison VERSION=v1.27.1+k3s1
CommitID used to validate changes COMMIT=a736b4b1b932a2f513077959a931f8f2faae6329

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```
 
*Cluster Configuration:*

```
NAME              STATUS   ROLES                       AGE    VERSION
ip-1-1-1-41        Ready    control-plane,etcd,master   124m   v1.27.1+k3s-a736b4b1 
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: gurtyo
selinux: true
protect-kernel-defaults: true
cluster-init: true
prefer-bundled-bin: true
```

<details><summmary><h4>Reproduction</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.27.1+k3s1 INSTALL_K3S_TYPE=server INSTALL_K3S_SKIP_START=true ./install-k3s.sh
$ sudo k3s server --tls-san "https://break-qa.web/,https://obelieve.tech"
$ sudo openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1

```

**Results:**

$ sudo openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1
```
            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:https://break-qa.web/,https://obelieve.tech, DNS:localhost, DNS:ip-172-31-23-42, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:172.31.23.42, IP Address:10.43.0.1
```

</details>

<details><summmary><h4>Validation</h4></summary>
 
## Validation Steps
 
```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf or ~/90-kubelet.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/ or 90-kubelet.conf
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_COMMIT=a736b4b1b932a2f513077959a931f8f2faae6329 INSTALL_K3S_TYPE=server INSTALL_K3S_SKIP_START=true ./install-k3s.sh
$ sudo k3s server --tls-san "https://break-qa.web/,https://obelieve.tech"
$ sudo openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1
``` 
 
**Results:** 

```
sudo openssl x509 -in /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt -noout -text | grep "Subject Alternative" -A1
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:https://break-qa.web/, DNS:https://obelieve.tech/, DNS:localhost, DNS:ip-172-31-23-42, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:172.31.23.42, IP Address:10.43.0.1
```

**Additional context / logs:**
</details>
