### ISSUE TITLE
Move containerd back into the main multicall binary

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7419]
Building containerd standalone in https://github.com/k3s-io/k3s/pull/4757 increased the release artifact size significantly. We should move it back into the main binary as soon as containerd, kubernetes, and etcd once again require compatible module versions.

It looks like this might be doable with containerd v1.7

**Comment by brandond** [comment]
This cannot be backported to 1.25 or earlier, as Kubernetes 1.25 and earlier are using incompatible versions of the opentelemetry modules.

**Comment by VestigeJ** [comment]
##Environment Details
Original binary checked using VERSION=v1.27.1+k3s1
New binary size compared using COMMIT=8f450bafe1cad0e962e521d56eb74a38a73722c7

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```

*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1-1-1-225       Ready    control-plane,etcd,master   8m19s   v1.27.1+k3s-8f450baf 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: scarylithiumchurros
selinux: true
protect-kernel-defaults: true
cluster-init: true
```

## Install k3s

```
$ sudo INSTALL_K3S_VERSION=v1.27.1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ ls -lah /usr/local/bin/k3s //observe 66M
$ k3s -v
```

**Results:**

Before 

$ ls -lah /usr/local/bin/k3s
```
-rwxr-xr-x 1 root root 66M May 11 17:06 /usr/local/bin/k3s
```

$ k3s -v
```
k3s version v1.27.1+k3s1 (bc5b42c2)
go version go1.20.3
```
 
## Validation Steps

``` 
$ sudo INSTALL_K3S_COMMIT=8f450bafe1cad0e962e521d56eb74a38a73722c7 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ ls -lah /usr/local/bin/k3s  //observe 56M about a 10M binary size reduction 👏🏽 
$ k3s -v
```

**Results:** 

After 

$ ls -lah /usr/local/bin/k3s
```
-rwxr-xr-x 1 root root 56M May 11 17:06 /usr/local/bin/k3s
```

$ k3s -v
```
k3s version v1.27.1+k3s-8f450baf (8f450baf)
go version go1.20.3
```
