### ISSUE TITLE
Update CNI plugins version and add additional plugins from upstream

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7424]
We are currently bunding CNI plugins v1.1.1-k3s1. The latest release from upstream is v1.2.0. There are also several plugins that the upstream Kubernetes docs document as generally available, and seem to expect all distributions to bundle, although we do not. This includes:
* firewall
* bandwidth

We should bump the version, and include the additional plugins.

**Comment by fmoral2** [comment]
## Validated on Version:
- v1.27.1+k3s-cbe8d33c (cbe8d33c)

## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04

*Cluster Configuration:*
1 node

*Config.yaml 1 node :*
```
cat /etc/rancher/k3s/config,yaml
write-kubeconfig-mode: 644
token: secret

```



## Steps to validate the fix:
1. Install k3s master last commit
2. Check cni bin version
3. Check cni flannel plugin version
4. Deploy a pod with bandwidth annotation
5. Validate the bandwidth annotation is applied to the pod





## **Validation Results:**

<details>

```

$ k3s --version
k3s version v1.27.1+k3s-cbe8d33c (cbe8d33c)

$ /var/lib/rancher/k3s/data/current/bin/cni
CNI plugins plugin v1.2.0-k3s1

$ /var/lib/rancher/k3s/data/current/bin/flannel
CNI Plugin flannel version v0.21.4 (linux/amd64) commit HEAD built on 2023-04-27T21:48:42Z


$ kubectl apply -f bandwidth.yaml
`
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    kubernetes.io/ingress-bandwidth: "1M"
    kubernetes.io/egress-bandwidth: "1M"
spec:
  containers:
  - name: test-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
`

$  kubectl get pod test-pod -o yaml | grep -A2 annotations
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"kubernetes.io/egress-bandwidth":"1M","kubernetes.io/ingress-bandwidth":"1M"},"name":"test-pod","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","echo The app is running! \u0026\u0026 sleep 3600"],"image":"busybox","name":"test-container"}]}}
    kubernetes.io/egress-bandwidth: 1M
    kubernetes.io/ingress-bandwidth: 1M
```
