### ISSUE TITLE
Add E2E Test around etcd-snapshot S3 bucket

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#7441]
We need to add an E2E test which covers the https://docs.k3s.io/cli/etcd-snapshot#s3-compatible-api-support section. As we don't want to have a dedicated S3 bucket just for this test, we should use a fake/mock S3 bucket system.

The general steps would be:
- start up a vagrant node
- Setup a local S3 endpoint
- Start k3s server with the `etc-s3-*` flags
- Ensure that the scheduled cron snapshots (should make these every 30s or so) are being uploaded to the s3 bucket
- Use the `k3s etcd-snapshot` tool to test on demand uploads to the s3 bucket

We should be able to cover the following flags:
- etcd-s3-region
- etcd-s3-secret-key
- etcd-s3-endpoint-ca
- etcd-s3-insecure
- etcd-s3-bucket
- etcd-s3

**Comment by brandond** [comment]
I'd suggest minio but they recently made it much harder to stand up a simple filesystem-backed bucket using their Docker image. Maybe https://github.com/adobe/S3Mock instead?

**Comment by osodracnai** [comment]
what about https://github.com/localstack/localstack ?

**Comment by brandond** [comment]
I haven't compared them recently, but IIRC that's a bit more than we need. All we need is a S3 endpoint, not the full AWS service stack.
