### ISSUE TITLE
The error message "failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the doc" occurred when trying to start k3s on CentOS due to the activation of the Docker TLS security option.

### ISSUE THREAD

**Issue by zengyufei** [k3s-io/k3s#7445]
How to solve this issue?

**Comment by brandond** [comment]
I don't see any options to configure TLS in cri-dockerd:
https://github.com/Mirantis/cri-dockerd/blob/master/cmd/server.go#L146

Have you reported this upstream?

**Comment by brandond** [comment]
Also, please fill out the issue template, and list what version of k3s you're using, on what platform, and how you have installed and configured it.

**Comment by brandond** [comment]
closing as upstream issue with cri-dockerd
