### ISSUE TITLE
Airgap install.sh script fails with a request to install additional packages

### ISSUE THREAD

**Issue by yaniveliash** [k3s-io/k3s#7464]
**Environmental Info:**
K3s Version:
```
k3s version v1.27.1+k3s1 (bc5b42c2)
go version go1.20.3
```

Node(s) CPU architecture, OS, and Version: 
* Centos 7.9 over Proxmox VM
* Eth0 wired to another VM acting as DHCP router 
* DHCP Router have 2 Ethernet legs and is being used as pivot SSH to my k3s-001 machine

`Linux k3s-001 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
A wanna be single node :)

**Describe the bug:**
Following the airgap installation procedure on k3s website instruct to run
`INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh`
The script exist with the following error:
```
[ERROR]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/
```
While `container-selinux` is installed (part of docker-ce installation)
```
yum list installed | grep container-selinux
container-selinux.noarch         2:2.119.2-1.911c772.el7_8     @extras
```
rancher is not installed as it's not part of the pre-req (unless I missed something?)

**Steps To Reproduce:**
1. Setup 2 VMs
2. One VM as DHCP Router with 2 ethernet legs and IP forward disabled
3. Second VM pre-installed with latest docker-ce with a single ethernet leg wired to the DHCP server
4. On the router machine, run the following
```
wget https://github.com/k3s-io/k3s/releases/download/v1.27.1%2Bk3s1/k3s-airgap-images-amd64.tar
wget https://github.com/k3s-io/k3s/releases/download/v1.27.1%2Bk3s1/k3s
wget https://get.k3s.io/ -O install.sh
```
5. `scp` the downloaded files to the k3s server
6. docker load the tar file
7. `chmod +x k3s`
8. `mv k3s /usr/local/bin`
9. chmod +x install.sh
10. run `INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh`

- Installed K3s: 
just the binary as described above

**Expected behavior:**

Install script run successfully and makes me happy

**Actual behavior:**

Failed with odd error message

**Additional context / logs:**

**Comment by yaniveliash** [comment]
I've continue my venture into a solution and found out that if I ran the following installation command, it succeed and I'm able to get the node up.

```
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_SELINUX_WARN=true ./install.sh
```

**Comment by brandond** [comment]
>```
> yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/
>```

This line is supposed to be asking you to install the k3s-selinux package. This is required if you want to use K3s with selinux.

**Comment by brandond** [comment]
cc @galal-hussein

**Comment by yaniveliash** [comment]
> > ```
> > yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/
> > ```
> 
> This line is supposed to be asking you to install the k3s-selinux package. I'm not sure why it got cut off though. The k3s-selinux package is required if you want to use K3s with selinux.

It would make sense to add this package (and any other optional package) to the pre-req in the airgap instructions as in airgap systems we use ISO templates that have been prepared in advance on the internet and it's something very difficult to add just "one more package" :)

**Comment by brandond** [comment]
We do call it out, see the `Manual Installation` tab at https://docs.k3s.io/advanced#selinux-support

**Comment by yaniveliash** [comment]
I probably missed that reference on https://docs.k3s.io/installation/airgap
or is it missing?

(if so - maybe adding a mention about it and a link for further reading?)

It's not a complaint, just feedback on my experience installing today K3s on airgap network
I think it will make it more clear for future generations :)

**Comment by caroline-suse-rancher** [comment]
Thank you for your feedback @yaniveliash! Any updates on Brads comment @galal-hussein?

> > ```
> > yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/
> > ```
> 
> This line is supposed to be asking you to install the k3s-selinux package. I'm not sure why it got cut off though. The k3s-selinux package is required if you want to use K3s with selinux.

**Comment by yaniveliash** [comment]
> Thank you for your feedback @yaniveliash! Any updates on Brad's comment @galal-hussein?
> 
> > > ```
> > > yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/
> > > ```
> > 
> > 
> > This line is supposed to be asking you to install the k3s-selinux package. I'm not sure why it got cut off though. The k3s-selinux package is required if you want to use K3s with selinux.

No further comments :)

**Comment by galal-hussein** [comment]
@brandond is correct, the script should have failed at the installation of k3s-selinux in airgap, however it didnt for some reason, @yaniveliash do you mind posting the output of the following command
