### ISSUE TITLE
Document how to add the HostPath storage driver

### ISSUE THREAD

**Issue by double16** [k3s-io/k3s#75]
**Is your feature request related to a problem? Please describe.**
Manifests that include PersistentVolumeClaims do not work.

**Describe the solution you'd like**
I would like documentation on how to install and configure the HostPath driver. I'm not interested in HA storage, etc.

**Describe alternatives you've considered**
None

Thanks!

**Comment by flxs** [comment]
Struggling with this too; is it possible to get that to work? If so, a few pointers in the general direction would be very helpful.

**Comment by warmchang** [comment]
I prefer to use [volume of the hostpath type](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) directly.

An example:
```
$ k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3-k3s.6", GitCommit:"da4e14f160174f356b1d95198f48439971cc8a85", GitTreeState:"clean", BuildDate:"2019-02-24T05:21+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3-k3s.6", GitCommit:"da4e14f160174f356b1d95198f48439971cc8a85", GitTreeState:"clean", BuildDate:"2019-02-24T05:21+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
$ alias k="k3s kubectl"
$ cat pod-hostpath.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory
$
$ k apply -f pod-hostpath.yaml
pod/test-pd created
$ k get pods
NAME                   READY   STATUS    RESTARTS   AGE
http-8654dd748-fjdkc   1/1     Running   0          9m22s
test-pd                1/1     Running   0          13s
$ k get pod test-pd -o yaml
apiVersion: v1
kind: Pod
......
    name: test-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-vz4pc
      readOnly: true
  dnsPolicy: ClusterFirst
......
  volumes:
  - hostPath:
      path: /data
      type: Directory
    name: test-volume
  - name: default-token-vz4pc
    secret:
      defaultMode: 420
      secretName: default-token-vz4pc
status:
......
    restartCount: 0
    state:
      running:
        startedAt: "2019-02-28T11:24:20Z"
  hostIP: 172.17.0.20
  phase: Running
  podIP: 10.42.0.7
  qosClass: BestEffort
  startTime: "2019-02-28T11:24:19Z"
$
$ k cluster-info
Kubernetes master is running at https://localhost:6443
CoreDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
$
```


If switch to CSI implementation, I need to install Provisioner, Driver, Attacher and Registrar plugins, which seems too complex. It goes against the original intention of k3s to pursue simplicity and lightness.


The following two articles describe the content related to the CSI host-path for reference:
1. https://kubernetes-csi.github.io/docs/example.html
2. https://github.com/Azure/kubernetes-volume-drivers/tree/master/csi/hostpath


Just my 2 cents. ☸☸ :smiley:

**Comment by double16** [comment]
My use case is for CI. If I change from PVC then it's not testing my config. Also, one particular application uses Helm to package and uses dependencies. Those dependencies use PVC. It'd be easier for me to install a plugin.

**Comment by curx** [comment]
an example for setting up a host-path-provisoner #85 (https://github.com/rancher/k3s/issues/85#issuecomment-468293334)

**Comment by flxs** [comment]
@warmchang hostPath volumes are always owned by root; this complicates things considerably when using pre-built containers that run their process(es) as another user. The localPath provisioner described in #85 does pretty much the same but via PVCs, which don't seem to suffer from the owned-by-root issue.

**Comment by double16** [comment]
Agree. I'm trying the local path solution now and it seems good so far. I'd
be happy with that and I may submit a PR for the docs later.

**Comment by brandond** [comment]
https://rancher.com/docs/k3s/latest/en/storage/
