### ISSUE TITLE
The official home address is unavailable

### ISSUE THREAD

**Issue by SilenceShine** [k3s-io/k3s#7528]
The official home address is unavailable
![image](https://github.com/k3s-io/k3s/assets/126382592/b0dd7a0e-7e43-44f5-ad95-4d3b34f175f5)

**Comment by cwayne18** [comment]
We'll try to get this to the right folks, but this isn't actually something owned by the k3s team

**Comment by SilenceShine** [comment]
ok 3q

**Comment by brandond** [comment]
If you can, please report this at https://forums.rancher.cn/
