### ISSUE TITLE
k3s server fatal exited because database locked

### ISSUE THREAD

**Issue by dragon9783** [k3s-io/k3s#755]
**Describe the bug**
k3s version v0.8.1 (d116e74a) 
k3s server fatal exited, because database locked

**To Reproduce**
1. k3s server --docker
2. journalctl -f -u k3s

**Expected behavior**
k3s run success

**Screenshots**
```
I0823 14:32:33.954766    6017 trace.go:81] Trace[1612309990]: "SQL Commit" (started: 2019-08-23 14:32:28.945805097 +0800 CST m=+4038.658662768) (total time: 5.008937729s):
Trace[1612309990]: [5.008937729s] [5.008223267s] END
I0823 14:32:33.954831    6017 trace.go:81] Trace[702899230]: "GuaranteedUpdate etcd3: *coordination.Lease" (started: 2019-08-23 14:32:28.945338 +0800 CST m=+4038.658195691) (total time: 5.009471312s):
Trace[702899230]: [5.009471312s] [5.009014446s] END
E0823 14:32:33.954900    6017 status.go:71] apiserver received an error that is not an metav1.Status: sqlite3.Error{Code:5, ExtendedCode:5, err:"database is locked"}
I0823 14:32:33.955362    6017 trace.go:81] Trace[1395905502]: "Update /apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/node-116" (started: 2019-08-23 14:32:28.944830212 +0800 CST m=+4038.657687852) (total time: 5.01050241s):
Trace[1395905502]: [5.01050241s] [5.010101987s] END
E0823 14:32:33.956373    6017 controller.go:159] failed to update node lease, error: database is locked
I0823 14:32:34.372213    6017 leaderelection.go:263] failed to renew lease kube-system/k3s: failed to tryAcquireOrRenew context deadline exceeded
FATA[2019-08-23T14:32:34.372431679+08:00] leaderelection lost for k3s
```

**Additional context**

**Comment by ibuildthecloud** [comment]
Does it 100% fail or something causes this? We do have a legit issue in that in single master mode we shouldn't be running leader election and terminating.

**Comment by dragon9783** [comment]
In single master mode, it is NOT 100% fail.

**Comment by scatat** [comment]
I have this issue as well. Would be nice to know where the sqlite files are so I can try and resolve the db issue

**Comment by rust84** [comment]
Similar issue. Here is my log (database is locked at 23:16:25). 

    Dec 02 23:10:13 k3s-node-1 k3s[26880]: I1202 23:10:13.260702   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:10:14 k3s-node-1 k3s[26880]: I1202 23:10:14.186194   26880 log.go:172] http: TLS handshake error from 192.168.1.104:19445: EOF
    Dec 02 23:10:14 k3s-node-1 k3s[26880]: I1202 23:10:14.186262   26880 log.go:172] http: TLS handshake error from 192.168.1.104:55767: EOF
    Dec 02 23:10:14 k3s-node-1 k3s[26880]: I1202 23:10:14.186853   26880 log.go:172] http: TLS handshake error from 192.168.1.104:38601: EOF
    Dec 02 23:10:14 k3s-node-1 k3s[26880]: I1202 23:10:14.187052   26880 log.go:172] http: TLS handshake error from 192.168.1.104:18857: EOF
    Dec 02 23:10:17 k3s-node-1 k3s[26880]: I1202 23:10:17.037552   26880 log.go:172] http: TLS handshake error from 192.168.1.104:40988: EOF
    Dec 02 23:10:18 k3s-node-1 k3s[26880]: E1202 23:10:18.957836   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 23:1
    Dec 02 23:10:20 k3s-node-1 k3s[26880]: I1202 23:10:20.780484   26880 log.go:172] http: TLS handshake error from 192.168.1.104:51103: EOF
    Dec 02 23:10:20 k3s-node-1 k3s[26880]: E1202 23:10:20.958965   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 2
    Dec 02 23:10:23 k3s-node-1 k3s[26880]: I1202 23:10:23.567937   26880 log.go:172] http: TLS handshake error from 192.168.1.104:63625: EOF
    Dec 02 23:10:31 k3s-node-1 k3s[26880]: I1202 23:10:31.002303   26880 log.go:172] http: TLS handshake error from 192.168.1.104:63151: EOF
    Dec 02 23:11:13 k3s-node-1 k3s[26880]: I1202 23:11:13.262939   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:11:44 k3s-node-1 k3s[26880]: E1202 23:11:44.979242   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until 201
    Dec 02 23:11:44 k3s-node-1 k3s[26880]: E1202 23:11:44.980164   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until
    Dec 02 23:12:13 k3s-node-1 k3s[26880]: I1202 23:12:13.266644   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:12:20 k3s-node-1 k3s[26880]: E1202 23:12:20.990123   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 23:1
    Dec 02 23:12:22 k3s-node-1 k3s[26880]: E1202 23:12:22.990107   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 2
    Dec 02 23:13:13 k3s-node-1 k3s[26880]: I1202 23:13:13.269776   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:13:57 k3s-node-1 k3s[26880]: E1202 23:13:57.010876   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until 201
    Dec 02 23:13:57 k3s-node-1 k3s[26880]: E1202 23:13:57.010925   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until
    Dec 02 23:14:13 k3s-node-1 k3s[26880]: I1202 23:14:13.272904   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:14:23 k3s-node-1 k3s[26880]: E1202 23:14:23.019707   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 23:1
    Dec 02 23:14:25 k3s-node-1 k3s[26880]: E1202 23:14:25.019895   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 2
    Dec 02 23:14:38 k3s-node-1 k3s[26880]: I1202 23:14:38.912977   26880 trace.go:116] Trace[22940172]: "List" url:/api/v1/namespaces/default/events (started: 2019-12-02 23:14:38.397528605 +0000 GMT m=+3574.567486230) (to
    Dec 02 23:14:38 k3s-node-1 k3s[26880]: Trace[22940172]: [304.130115ms] [304.12313ms] Listing from storage done
    Dec 02 23:14:38 k3s-node-1 k3s[26880]: Trace[22940172]: [515.413879ms] [211.283764ms] Writing http response done count:20263
    Dec 02 23:15:12 k3s-node-1 k3s[26880]: I1202 23:15:12.824769   26880 log.go:172] http: TLS handshake error from 192.168.1.104:7462: EOF
    Dec 02 23:15:13 k3s-node-1 k3s[26880]: I1202 23:15:13.276665   26880 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Dec 02 23:15:15 k3s-node-1 k3s[26880]: I1202 23:15:15.193007   26880 log.go:172] http: TLS handshake error from 192.168.1.104:16061: EOF
    Dec 02 23:15:18 k3s-node-1 k3s[26880]: I1202 23:15:18.783442   26880 log.go:172] http: TLS handshake error from 192.168.1.104:61723: EOF
    Dec 02 23:15:18 k3s-node-1 k3s[26880]: I1202 23:15:18.783479   26880 log.go:172] http: TLS handshake error from 192.168.1.104:21403: EOF
    Dec 02 23:15:24 k3s-node-1 k3s[26880]: I1202 23:15:24.967278   26880 log.go:172] http: TLS handshake error from 192.168.1.104:25206: EOF
    Dec 02 23:15:27 k3s-node-1 k3s[26880]: I1202 23:15:27.762806   26880 log.go:172] http: TLS handshake error from 192.168.1.104:56934: EOF
    Dec 02 23:15:29 k3s-node-1 k3s[26880]: I1202 23:15:29.570864   26880 log.go:172] http: TLS handshake error from 192.168.1.104:41317: EOF
    Dec 02 23:15:30 k3s-node-1 k3s[26880]: I1202 23:15:30.970921   26880 log.go:172] http: TLS handshake error from 192.168.1.104:35335: EOF
    Dec 02 23:16:09 k3s-node-1 k3s[26880]: E1202 23:16:09.082451   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until 201
    Dec 02 23:16:09 k3s-node-1 k3s[26880]: E1202 23:16:09.368096   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until
    Dec 02 23:16:09 k3s-node-1 k3s[26880]: I1202 23:16:09.437566   26880 trace.go:116] Trace[950449572]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/rook-ceph/leases/external-attacher-leader-rook-ceph-cephfs-csi-cep
    Dec 02 23:16:19 k3s-node-1 k3s[26880]: Trace[1534509974]: [14.035158796s] [14.035149309s] About to write a response
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.825064   26880 trace.go:116] Trace[1945632925]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:10.78997526 +0000 GMT m=+3666.95993289
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[1945632925]: [10.035066589s] [10.03497895s] END
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.826382   26880 trace.go:116] Trace[716601772]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:10.789479579 +0000 GMT m=+3666.95943720
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[716601772]: [10.036886567s] [10.036751054s] END
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: E1202 23:16:20.826402   26880 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.827384   26880 trace.go:116] Trace[301641149]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-6 (started: 2019-12-02 23:16:10
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[301641149]: [10.037961464s] [10.037893555s] END
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.827511   26880 trace.go:116] Trace[1571546984]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-5 (started: 2019-12-02 23:16:1
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[1571546984]: [10.037596931s] [10.037550705s] END
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: E1202 23:16:20.988549   26880 controller.go:170] failed to update node lease, error: Put https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.988772   26880 trace.go:116] Trace[1662014819]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:10.94086511 +0000 GMT m=+3667.11082274
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[1662014819]: [10.047889305s] [10.047716717s] END
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: I1202 23:16:20.989017   26880 trace.go:116] Trace[1876067532]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-1 (started: 2019-12-02 23:16:1
    Dec 02 23:16:20 k3s-node-1 k3s[26880]: Trace[1876067532]: [10.048253447s] [10.048170585s] END
    Dec 02 23:16:24 k3s-node-1 k3s[26880]: I1202 23:16:24.904582   26880 trace.go:116] Trace[2089588941]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:14.94012806 +0000 GMT m=+3671.11008568
    Dec 02 23:16:24 k3s-node-1 k3s[26880]: Trace[2089588941]: [9.964420661s] [9.964236617s] END
    Dec 02 23:16:24 k3s-node-1 k3s[26880]: E1202 23:16:24.904735   26880 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
    Dec 02 23:16:24 k3s-node-1 k3s[26880]: I1202 23:16:24.905371   26880 trace.go:116] Trace[167698949]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-7 (started: 2019-12-02 23:16:14
    Dec 02 23:16:24 k3s-node-1 k3s[26880]: Trace[167698949]: [9.996162787s] [9.965281655s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.007996   26880 trace.go:116] Trace[440403802]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:15.010719833 +0000 GMT m=+3671.18067746
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[440403802]: [9.99725158s] [9.997095548s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: E1202 23:16:25.008032   26880 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.008298   26880 trace.go:116] Trace[1626335835]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-4 (started: 2019-12-02 23:16:1
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[1626335835]: [9.998131274s] [9.997594281s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: time="2019-12-02T23:16:25.018458100Z" level=error msg="error while range on /registry/pods/kube-system/ /registry/pods/kube-system/: database is locked"
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.120642   26880 trace.go:116] Trace[809513329]: "List etcd3" key:/pods/kube-system,resourceVersion:,limit:0,continue: (started: 2019-12-02 23:16:12.206310328 +0000
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[809513329]: [12.914305681s] [12.914305681s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: E1202 23:16:25.120681   26880 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:2, Message:"database is locked", Details:[]*any.Any
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.121584   26880 trace.go:116] Trace[501256844]: "List" url:/api/v1/namespaces/kube-system/pods (started: 2019-12-02 23:16:12.206254095 +0000 GMT m=+3668.376211721)
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[501256844]: [12.915316548s] [12.915265478s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.129476   26880 trace.go:116] Trace[347088118]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:15.331075045 +0000 GMT m=+3671.50103267
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[347088118]: [9.798314538s] [9.798141833s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: E1202 23:16:25.129513   26880 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.129856   26880 trace.go:116] Trace[2116456305]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-2 (started: 2019-12-02 23:16:1
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[2116456305]: [9.799027808s] [9.798836211s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.172078   26880 trace.go:116] Trace[362421693]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-12-02 23:16:15.215579786 +0000 GMT m=+3671.38553741
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[362421693]: [9.956468933s] [9.956316173s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: E1202 23:16:25.172369   26880 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: I1202 23:16:25.172731   26880 trace.go:116] Trace[1135376580]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-node-3 (started: 2019-12-02 23:16:1
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: Trace[1135376580]: [9.957245415s] [9.957169996s] END
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: E1202 23:16:25.173174   26880 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-12-02 23:1
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime: program exceeds 10000-thread limit
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: fatal error: thread exhaustion
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime stack:
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime.throw(0x3d8ac7d, 0x11)
    Dec 02 23:16:25 k3s-node-1 k3s[26880]:         /usr/local/go/src/runtime/panic.go:774 +0x72
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime.checkmcount()
    Dec 02 23:16:25 k3s-node-1 k3s[26880]:         /usr/local/go/src/runtime/proc.go:600 +0xac
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime.mcommoninit(0xc02ff83880)
    Dec 02 23:16:25 k3s-node-1 k3s[26880]:         /usr/local/go/src/runtime/proc.go:618 +0x73
    Dec 02 23:16:25 k3s-node-1 k3s[26880]: runtime.allocm(0xc00007c000, 0x0, 0xc0000016b8)
    lines 3845081-3845132/3847564 100%

**Comment by paroque28** [comment]
I have the same issue:
`Unable to perform initial Kubernetes service initialization: rpc error: code = Unknown desc = database is locked`

**Comment by brandond** [comment]
Closing due to age. Many changes have been made to kine; please open a new issue if this reoccurs on newer releases.
