### ISSUE TITLE
DynamicListener Cert Issue with too many servers joining simultaneously

### ISSUE THREAD

**Issue by VestigeJ** [k3s-io/k3s#7557]
**Environmental Info:**
K3s Version: 

$ k3s -v
```
k3s version v1.25.9+k3s1 (7502ce6a)
go version go1.19.8
```

Node(s) CPU architecture, OS, and Version: 

T2.medium AWS EC2 (five nodes all matching)
```
Linux ip-1-1-1-231 5.14.21-150400.24.11-default #1 SMP PREEMPT_DYNAMIC Sun Jul 17 20:46:33 UTC 2022 (be260ca) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

5 servers (1 setup primary and allowed to get to ready status before simultaneously joining the remaining 4)

**Describe the bug:**

When trying to join too many servers at once to an existing server in a 'Ready' state one of the nodes (potentially given the race conditions) will generate this error instead of starting normally and joining the cluster with the other server nodes. The node can simply re-run the startup ie 'sudo k3s server' will rejoin just fine. 

This was uncovered while testing another issue and I have related comments here. https://github.com/k3s-io/k3s/issues/7511#issuecomment-1548686231

**Steps To Reproduce:**

- Installed K3s - on a single node primary server 
- wait for the initial server to become 'Ready'
- setup four additional nodes to be ready to join simultaneously
- start k3s on the four remaining nodes and observe one of them (most likely the first node out of them all) generate the certificate error
```
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/139baf56dd73135b3c4c2aea21e749ad26a4db4e71a0177dbb00c3e0793b3d3d 
INFO[0000] Starting k3s v1.25.9+k3s-3ce8dd17 (3ce8dd17) 
FATA[0000] starting kubernetes: preparing server: CA cert validation failed: Get "https://1.2.3.205:6443/cacerts": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 1.1.1.170, ::1, not 1.2.3.205
```

**Expected behavior:**

All server nodes join and negotiate the join without error and if an issue occurs retries the join accordingly

**Actual behavior:**

I need to pinpoint the nodes that did not join correctly and re-run the startup command.

**Additional context / logs:**

I was able to confirm this on both existing releases and the latest commit with the patches for the too many learners errors it is a less often hit race condition. 

These two errors are in tandem on the v1.25.9+k3s1 release

node 1
```
 sudo k3s server
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/feeeb9b2f9234f89a72104f4e1c25b6a2ffe117ddaadbe6791cf09885153bdc3 
INFO[0000] Starting k3s v1.25.9+k3s1 (7502ce6a)         
FATA[0000] starting kubernetes: preparing server: CA cert validation failed: Get "https://1.1.1.205:6443/cacerts": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 1.3.2.170, ::1, not 1.1.1.205 
```

node 2
```
level":"warn","ts":"2023-05-15T22:49:27.920Z","logger":"etcd-client","caller":"v3@v3.5.3-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009fbdc0/172.31.26.170:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: too many learner members in cluster"}
FATA[0004] ETCD join failed: etcdserver: too many learner members in cluster 
```

**Comment by brandond** [comment]
@VestigeJ what is 1.1.1.205? Is this an external load balancer, or one of the nodes? If it is one of the nodes, which one is it?

**Comment by VestigeJ** [comment]
Will follow up tomorrow but this is a single server node looking back at the primary node for joining the cluster. I am in the habit of just anonymizing the node-ip but in this case i neglected to add information from the cluster. The general process was starting a single node server, letting it get to a ready state, then nearly simultaneously joining four additional server nodes. There were no agent nodes joining at this time.

**Comment by brandond** [comment]
@VestigeJ when you get a chance, can you pull logs from a server where this is occurring? Logs from the server being joined, not the agents or the joining nodes. I'd like to figure out why the IP SAN for the server node is (apparently) getting removed when the other servers join.

**Comment by brandond** [comment]
Bumping this out - @VestigeJ please pull the requested logs if you can still reproduce this.

**Comment by brandond** [comment]
moving to to-test for QA visibility

**Comment by VestigeJ** [comment]
On the plus side new releases seem to rejoin just fine without the original issue of needing to retry the server startup on the nodes. The original error I logged there does still seem to be present. Logs are attached below.

[join-serverlogs.txt](https://github.com/k3s-io/k3s/files/12294290/join-serverlogs.txt)
[verbose.txt](https://github.com/k3s-io/k3s/files/12294291/verbose.txt)

**Comment by VestigeJ** [comment]
This warning still occurs in the logs but the overall functionality and automatic re-trying for the servers seems to be more stable on recent releases. So I'm going to opt to close this for now as resolved.
