### ISSUE TITLE
k3s does not start with etcdctl error (after upgrade to 1.27.1+k3s1)

### ISSUE THREAD

**Issue by cerebrate** [k3s-io/k3s#7558]
**Environmental Info:**
K3s Version: 
k3s version v1.27.1+k3s1 (bc5b42c2)
go version go1.20.3

Node(s) CPU architecture, OS, and Version: 
Linux princess-celestia 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08) x86_64 GNU/Linux

Cluster Configuration:
2 nodes, both master

**Describe the bug:**
After upgrading k3s on one node to 1.27.1+k3s1 and restarting, k3s.service remains indefinitely in "activating" state. The following error appears repeatedly in the log:

```
May 16 01:01:12 princess-celestia k3s[934]: time="2023-05-16T01:01:12-05:00" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [princess-luna-aa0a3cdf=https://[fdc9:b01a:9d26:0:8aae:ddff:fe0a:a3fa]:2380 princess-celestia-4289d1fb=https://172.16.0.141:2380], expect: princess-celestia-4289d1fb=https://[fdc9:b01a:9d26:0:1e69:7aff:fe68:de24]:2380"
```

All of these IP addresses are correct for the nodes they're attributed to; the failed node (_princess-celestia_) has the following configuration on eth0:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 1c:69:7a:68:de:24 brd ff:ff:ff:ff:ff:ff
    altname eno1
    altname enp0s31f6
    inet 172.16.0.141/16 metric 10 brd 172.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdc9:b01a:9d26:0:1e69:7aff:fe68:de24/64 scope global mngtmpaddr noprefixroute
       valid_lft forever preferred_lft forever
    inet6 2600:1700:6495:50f:1e69:7aff:fe68:de24/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 1998sec preferred_lft 1998sec
    inet6 fe80::1e69:7aff:fe68:de24/64 scope link
       valid_lft forever preferred_lft forever
```

**Steps To Reproduce:**

- Installed K3s: 

k3s was installed on the node some time ago with the following _/etc/rancher/k3s/config.yaml file:

```
token: <REDACTED>
resolv-conf: "/etc/rancher/k3s/resolv.conf"
node-ip: fdc9:b01a:9d26:0:1e69:7aff:fe68:de24,172.16.0.141
cluster-cidr: 10.42.0.0/16,fdc9:b01a:cafe:42:0::/56
service-cidr: 10.43.0.0/16,fdc9:b01a:cafe:42:1::/112
flannel-ipv6-masq: true
cluster-init: true
disable: traefik
write-kubeconfig-mode: 644
node-label:
  - "arkane-systems.lan/console=true"
  - "arkane-systems.lan/blinkenlights=false"
  - "arkane-systems.lan/hw=nuc"
  - "topology.kubernetes.io/region=core"
default-local-storage-path: /opt/k3store
```

I am unaware of any events that could have triggered this issue other than the upgrade and ensuing service restart. I also note that the other master node of this two-node cluster was upgraded and k3s.service restarted without triggering the issue.

**Expected behavior:**

A clean restart into 1.27.1+k3s1

**Actual behavior:**

The failure described above.

**Comment by brandond** [comment]
It looks like one of the nodes was joined with the IPv4 address as its primary, and is now properly using the order you selected, with IPv6 as the primary address. The easiest way to fix this would be to delete the node from the cluster with `kubectl delete node` and then rejoin it.

I will also note that a 2-node etcd cluster is not a supported configuration; you should always have an odd number of nodes to ensure quorum. As you've probably noticed, with only 2 nodes, both nodes must be online for the cluster to function.

**Comment by cerebrate** [comment]
Okay, that makes sense, although I'm not sure how it happened. To make sure it doesn't recur, is there a way I can check what each node _thinks_ the primary address is for this?

(The two-node situation is temporary; the purchase order with the third node in it just hadn't arrived yet. :grin: )

**Comment by brandond** [comment]
> is there a way I can check what each node _thinks_ the primary address is for this

Yes, it's right there in the error message you posted.

```
Found [
        princess-luna-aa0a3cdf=https://[fdc9:b01a:9d26:0:8aae:ddff:fe0a:a3fa]:2380
        princess-celestia-4289d1fb=https://172.16.0.141:2380
      ]
expect: princess-celestia-4289d1fb=https://[fdc9:b01a:9d26:0:1e69:7aff:fe68:de24]:2380
```

**Comment by cerebrate** [comment]
Sorry, my poor phrasing. I meant to check what etcd is expecting/using when it _isn't_ producing errors.

**Comment by caroline-suse-rancher** [comment]
Closing this as it seems your problem is resolved.
