### ISSUE TITLE
Multicidr e2e test fails

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#7566]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

When the agent needs to be restarted, it does not get restarted. The reason is that the wildcard `k3s*` only applies to loaded and active systemd units. However, in tests such as multicidr or the upcoming tailscale, the k3s-agent unit is loaded but inactive. Therefore, the wildcard will not apply and thus the e2e test fails

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
Nothing to test here as it applied only to test files.
