### ISSUE TITLE
K3s creating world writable files and un-owned files

### ISSUE THREAD

**Issue by gitr32** [k3s-io/k3s#758]
I installed k3s on a machine running Red Hat Enterprise Linux 7.6 and ran k3s with the following command and flags included as hardening based on CIS benchmark:

```
k3s server
'--no-deploy=traefik' \
'--data-dir=/app/var/lib/rancher/k3s' \
'--bind-address=127.0.0.1' \
'--node-ip=127.0.0.1' \
'--kube-apiserver-arg=bind-address=127.0.0.1' \
'--kube-apiserver-arg=insecure-port=0' \
'--kube-apiserver-arg=kubelet-https=true' \
'--kube-apiserver-arg=profiling=false' \
'--kube-apiserver-arg=enable-admission-plugins=NamespaceLifecycle' \
'--kube-apiserver-arg=audit-log-path=/var/log/apiserver/audit.log' \
'--kube-apiserver-arg=audit-log-maxage=30' \
'--kube-apiserver-arg=audit-log-maxbackup=10' \
'--kube-apiserver-arg=audit-log-maxsize=100' \
'--kube-apiserver-arg=service-account-lookup=true' \
'--kube-apiserver-arg=enable-admission-plugins=ServiceAccount,NodeRestriction' \
'--kube-apiserver-arg=tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384' \
'--kube-apiserver-arg=tls-min-version=VersionTLS12' \
'--kube-apiserver-arg=feature-gates=AllAlpha=true' \
'--kube-scheduler-arg=profiling=false' \
'--kube-scheduler-arg=address=127.0.0.1' \
'--kube-controller-arg=terminated-pod-gc-threshold=100' \
'--kube-controller-arg=profiling=false' \
'--kube-controller-arg=use-service-account-credentials=true' \
'--kube-controller-arg=feature-gates=RotateKubeletServerCertificate=true' \
'--kube-controller-arg=address=127.0.0.1' \
'--kubelet-arg=address=127.0.0.1' \
'--kubelet-arg=anonymous-auth=false' \
'--kubelet-arg=protect-kernel-defaults=true' \
'--kubelet-arg=make-iptables-util-chains=true' \
'--kubelet-arg=event-qps=0' \
'--kubelet-arg=feature-gates=RotateKubeletServerCertificate=true' \
'--kubelet-arg=tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'

```

With this configuration, we ran into 2 issues being highlighted by a vulnerability assessment software used to scan the server:
- World writable files were found on the server and it seems to be created by k3s. Some examples of the files are as indicated below:

> /app/var/lib/rancher/k3s/agent/kubelet/pods/35aea8cb-c50c-11e9-b7fe-001a4a16015d/containers/cert-manager/2482f3c5 (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35aea8cb-c50c-11e9-b7fe-001a4a16015d/containers/cert-manager/ef82a588 (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b03f19-c50c-11e9-b7fe-001a4a16015d/containers/cainjector/0b03761c (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b03f19-c50c-11e9-b7fe-001a4a16015d/containers/cainjector/381bf5a6 (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b045a3-c50c-11e9-b7fe-001a4a16015d/containers/webhook/06ea836c (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b045a3-c50c-11e9-b7fe-001a4a16015d/containers/webhook/d64a9167 (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b04a08-c50c-11e9-b7fe-001a4a16015d/containers/init-config/b7266ad4 (-rw-rw-rw-) * /app/var/lib/rancher/k3s/agent/kubelet/pods/35b04a08-c50c-11e9-b7fe-001a4a16015d/containers/init-config/e84a3def (-rw-rw-rw-) * 

- Un-owned files which also seem to have been created by k3s. Some examples of the files are as indicated below:

> /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/bfcf3f4ba445a821f5e30688d478b7584d14e30c763efce0dedf99d069f92626/rootfs/etc/shadow (-rw-r-----) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/cb1667f30d9a1a4c18e43d9bf8f1c5717e7c87a32707698cfd670e01a3476fc1/rootfs/etc/gshadow (-rw-r-----) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/cb1667f30d9a1a4c18e43d9bf8f1c5717e7c87a32707698cfd670e01a3476fc1/rootfs/run/utmp (-rw-rw-r--) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/cb1667f30d9a1a4c18e43d9bf8f1c5717e7c87a32707698cfd670e01a3476fc1/rootfs/sbin/unix_chkpwd (-rwxr-sr-x) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/cb1667f30d9a1a4c18e43d9bf8f1c5717e7c87a32707698cfd670e01a3476fc1/rootfs/usr/bin/chage (-rwxr-sr-x) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/cb1667f30d9a1a4c18e43d9bf8f1c5717e7c87a32707698cfd670e01a3476fc1/rootfs/usr/bin/expiry (-rwxr-sr-x) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/e6f1e1bc9dfcd30c6f53de96333a47e8e1b5b27f8c652dfddcc4afbcc145d724/rootfs/etc/gshadow (-rw-r-----) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/e6f1e1bc9dfcd30c6f53de96333a47e8e1b5b27f8c652dfddcc4afbcc145d724/rootfs/etc/ingress-controller/auth (drwxr-xr-x) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/e6f1e1bc9dfcd30c6f53de96333a47e8e1b5b27f8c652dfddcc4afbcc145d724/rootfs/etc/ingress-controller/ssl (drwxr-xr-x) * /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/e6f1e1bc9dfcd30c6f53de96333a47e8e1b5b27f8c652dfddcc4afbcc145d724/rootfs/etc/ingress-controller/ssl/default-fake-certificate.pem (-rw-r--r--) * 

Is the default behaviour of k3s to create files with these permissions or is this a configuration that we can change when running the k3s command, such that the files created by it are not world writable and un-owned. Thank you.

**Comment by erikwilson** [comment]
Are the files actually world readable?
```sh
vagrant🐮k3s-1:~$ ls -al /var/lib/rancher/k3s/agent/kubelet/pods/
ls: cannot access '/var/lib/rancher/k3s/agent/kubelet/pods/': Permission denied
```
```sh
vagrant🐮k3s-1:~$ ls -al /run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/
ls: cannot open directory '/run/k3s/containerd/io.containerd.runtime.v1.linux/k8s.io/': Permission denied
```
Seems that you are looking at ownerships and permissions of files which are in pods and likely have separate passwd and user id contexts. Unless I am misunderstanding seems like there is not an issue here, but if there is would probably be in upstream k8s or containerd.

**Comment by erikwilson** [comment]
Actually, we probably need to lock down the permissions of `/run/k3s`. I think `/var/lib/rancher/k3s/agent` is okay tho.

**Comment by matlec** [comment]
I actually ran into the same issue while hardening a Debian 9 system based on CIS benchmark. Any idea how and where to address this issue?

**Comment by erikwilson** [comment]
Which issue? We can change the permission of /run/k3s to 0700, but it looks like the benchmark is picking up stuff that shouldn't be a problem (re ownership & permissions).

**Comment by matlec** [comment]
Kubernetes has an [open issue](https://github.com/kubernetes/kubernetes/issues/81116) on world-writable files. It seems as if kubelet creates world-writable files (666) in `kubelet/pods/<podId>/containers/<containerId>`.

**Comment by xueyongg** [comment]
yes, may i know what is the status for this issue raised? I am encountering this.
