### ISSUE TITLE
k3s fails after upgrade

### ISSUE THREAD

**Issue by davidjade** [k3s-io/k3s#7593]
I have a fairly clean installation, not really anything deployed yet other that a small test app but it came to me (on a RPI computer) set up with an older version of k3s. So after using it for a while I decided to upgrade k3s. That did not go well as now it won't start up.

**Environmental Info:**
K3s Version: 
v1.26.4+k3s1 (8d0255af)

Node(s) CPU architecture, OS, and Version: 
Linux pibox 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:
1 node that does it all

**Describe the bug:**
after upgrading from v1.24.4+k3s1 to v1.26.4+k3s1, k3s server now fails with this:
```
level=fatal msg="flannel exited: failed to acquire lease: subnet \"10.42.0.0/16\" specified in the flannel net config doesn't contain \"172.31.10.0/24\" PodCIDR of the \"pibox\" node"
k3s.service: Main process exited, code=exited, status=1/FAILURE
k3s.service: Failed with result 'exit-code'.
```

**Steps To Reproduce:**
just upgrade from v1.24.4+k3s1 using:
```
curl -sfL https://get.k3s.io | sh -
```

**Expected behavior:**
a clean upgrade

**Actual behavior:**
broken installation

**Additional context / logs:**
content of /var/lib/rancher/k3s/agent/etc/flannel/net-conf.json

```
{
        "Network": "10.42.0.0/16",
        "EnableIPv6": false,
        "EnableIPv4": true,
        "IPv6Network": "::/0",
        "Backend": {
        "Type": "vxlan"
}
}
```

I also see this in the logs - not sure if relevant:
```
Updating runtime config through cri with podcidr" CIDR="172.31.10.0/24
Initialized iptables rules." protocol=IPv4
Updating Pod CIDR" originalPodCIDR="" newPodCIDR="172.31.10.0/24
```

**Comment by rbrtbnfgl** [comment]
If you run k3s with the following config?
`curl -sfL https://get.k3s.io | sh -s - --cluster-cidr: "172.31.10.0/16"`
I think you configured a cluster-cidr on your previous setup.

**Comment by davidjade** [comment]
So I'm not sure what options where used originally (the pibox came to me pre-configured with k3s) but from what I can tell, kube-system namespace several services were running in both the 10.43.10.x and 10.43.0.x address spaces. Pods in yet another 10.43.x.x. Furthermore, the rancher flannel conf file had one of those as well. I eventually got it working by finding a version of the k3s provisioning script used and through trial and error found that what was likely used (the authors switched it up a few times). Luckily I found just running the https://get.k3s.io upgrade again until I found the magic combination seems to do the right thing (mostly).

This is what finally stopped making things crash but not quite work. I'm not sure it is entirely correct but it works.
--cluster-cidr=172.31.10.0/24 --service-cidr=172.31.11.0/24

And I had to delete all the services and recreate them to get it fully back up and running as they hung onto the old 10.43.x.x addresses and continued to fail.

Oddly there's was never version of the k3s provisioning script for this device that ever used a cidr like 10.43.x.x (but there were versions that never specified a cidr at all during install). I have no idea which version of that script was used for my device unfortunately.

Which makes me wonder: Is this expected during an upgrade that those options have to be repeated exactly as first used? That you have to remember and use the same options or it all falls apart? Is there not a way/place for k3s to remember that so that upgrading is easier (i.e. keep the same config)?

Is there anything I should have done differently (other than somehow knowing how it was originally set up)?

**Comment by rbrtbnfgl** [comment]
Do you need the previous setup configuration? You can also run `k3s-uninstall.sh` script and deploy a new installation.

**Comment by davidjade** [comment]
Well I had a functioning installation that I was trying to upgrade. The upgrade process broke because it didn't keep the configuration, leaving everything in a broken network State. 

So in that sense, yes I think I needed the k3s upgrade process to keep the existing configuration. 

I expected an upgrade to not break things. Or at least warn me that it was going to break things.

**Comment by brandond** [comment]
all args are valid config file entries. Just convert them to yaml:
```yaml
cluster-cidr: 172.31.0.0/24
service-cidr: 172.31.0.0/24
disable:
  - traefik
```
and so on

**Comment by davidjade** [comment]
> I will note that I think you still have issues with your CIDRs, the cluster and service cidrs cannot overlap, and /24 is far too small. these are usually /16s.

I thought that too but this is what they (who set this up initially) used. Later on, they switched to this, which I tried, but it was giving me even more server & flannel errors on start up.

```
--cluster-cidr=172.30.0.0/16 --service-cidr=172.31.0.0/16
```

I agree that makes more sense but the server also didn't seem to like using 172.30.x.x and 172.31.xxx so unless they matched, it would not start. But maybe now that I've gotten things working and resolve the broken svcs, I can migrate back to the separate /24 addresses.

**Comment by brandond** [comment]
> I thought that too but this is what they (who set this up initially) used.

It sounds like the pibox hosts shipped you a pretty broken configuration, and now you get to try to unwind it. You might be better off just starting over from scratch and redeploying your manifests.

**Comment by davidjade** [comment]
I eventually sorted this out. It required using killall and me to delete and recreate the node so that I could edit the PodCIDR so that I could have separate 172.3x networks for the cluster and services. So I think this can be closed now. 

BUT, I would sure like to see the upgrade documentation have something about how you have to use the same arguments when upgrading manually via the script. That would have saved me a lot of heartache and I just don't see that info anywhere in the docs.

**Comment by brandond** [comment]
https://docs.k3s.io/upgrades/manual#upgrade-k3s-using-the-installation-script
> To upgrade K3s from an older version you can re-run the installation script **using the same flags**, for example:

I guess we could call out what happens if you ignore that, and don't use the same flags when re-running the installer?

**Comment by davidjade** [comment]
ok, yeah I totally missed the implications of that.

**Comment by brandond** [comment]
closing, will improve docs.
