### ISSUE TITLE
K3s server going to NODENOTREADY state

### ISSUE THREAD

**Issue by MohamedShaj** [k3s-io/k3s#7612]
> Looking at this a little further, you didn't mention this but it appears that you are also running longhorn on this node, is that correct? Are you putting both Longhorn and k3s on the same physical disks? If so I suspect that the disks may not have sufficient IO throughput to support both products. Note that etcd calls `fsync` to flush all pending IO on the disk (not the partition, but the physical disk) every time there is a write to the datastore. This includes any IO queued up for longhorn backing disk IO. Assuming that the iscsi errors are from LH and not some other storage system, the logs would further reinforce my guess that longhorn and etcd are contending for disk IO.

Before it was in the same physical disk, But now we made separate disk, but now the issue is different I believe,

please find the below logs from kernel and k3s,

`May 24 15:18:18 Demo-Box kernel: [1670655.742173] cni0: port 52(vethfa98589d) entered disabled state
May 24 15:18:18 Demo-Box kernel: [1670655.753874] device vethfa98589d left promiscuous mode
May 24 15:18:18 Demo-Box kernel: [1670655.753884] cni0: port 52(vethfa98589d) entered disabled state
May 24 15:18:21 Demo-Box kernel: [1670658.647720] IPv6: ADDRCONF(NETDEV_UP): veth6e07cfbf: link is not ready
May 24 15:18:21 Demo-Box kernel: [1670658.648223] cni0: port 52(veth6e07cfbf) entered blocking state
May 24 15:18:21 Demo-Box kernel: [1670658.648226] cni0: port 52(veth6e07cfbf) entered disabled state
May 24 15:18:21 Demo-Box kernel: [1670658.648402] device veth6e07cfbf entered promiscuous mode
May 24 15:18:21 Demo-Box kernel: [1670658.653907] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 24 15:18:21 Demo-Box kernel: [1670658.653935] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
May 24 15:18:21 Demo-Box kernel: [1670658.653997] IPv6: ADDRCONF(NETDEV_CHANGE): veth6e07cfbf: link becomes ready
May 24 15:18:21 Demo-Box kernel: [1670658.654068] cni0: port 52(veth6e07cfbf) entered blocking state
May 24 15:18:21 Demo-Box kernel: [1670658.654070] cni0: port 52(veth6e07cfbf) entered forwarding state
May 24 15:21:19 Demo-Box kernel: [1670836.700175] nfs: server 10.43.252.141 not responding, still trying
May 24 15:21:35 Demo-Box kernel: [1670852.252148] nfs: server 10.43.65.88 not responding, still trying
May 24 15:21:39 Demo-Box kernel: [1670856.860416] nfs: server 10.43.252.141 not responding, still trying
May 24 15:21:55 Demo-Box kernel: [1670872.284298] nfs: server 10.43.174.157 not responding, timed out
May 24 15:21:55 Demo-Box kernel: [1670872.408142] nfs: server 10.43.65.88 not responding, timed out
May 24 15:21:56 Demo-Box kernel: [1670872.988271] nfs: server 10.43.252.141 not responding, timed out
May 24 15:22:03 Demo-Box kernel: [1670880.476079] nfs: server 10.43.65.88 not responding, still trying
May 24 15:22:56 Demo-Box kernel: [1670933.724423] nfs: server 10.43.174.157 not responding, still trying
May 24 15:23:49 Demo-Box kernel: [1670986.717866] INFO: task influxd:27866 blocked for more than 120 seconds.
`
k3s logs -> [error.log](https://github.com/k3s-io/k3s/files/11567488/error.log)

We have reached the Longhorn community for the NFS server-related error and they clearly said "The stuck NFS client/server cases are sometimes caused by the operating system itself, and the restart of the worker node might be needed" they are working on to see why that happens ( I created a separate issue in Longhorn for that)

But they clearly mentioned due to Longhorn the "NodeNotReady" has not occurred, there may be some other reasons,

I would suspect there may be any issue with CNI (flannel), not sure just guessing so, 

can you help me on this !!!

_Originally posted by @MohamedShaj in https://github.com/k3s-io/k3s/issues/7343#issuecomment-1563238773_

**Comment by brandond** [comment]
Please keep the discussion on the existing issue.
