### ISSUE TITLE
Make klipper-lb image configurable 

### ISSUE THREAD

**Issue by orangedeng** [k3s-io/k3s#7625]
**Is your feature request related to a problem? Please describe.**
There is no way we can modify the default `klipper-lb` image at https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/servicelb.go#L46 because it is a const value instead of variable.

**Describe the solution you'd like**
Change the value type from const to var. And then it can be changed when building a k3s distro with go build flag `-X xxxx.DefaultLBImage=xxxx`

**Describe alternatives you've considered**
There is no alternative ways to do the same thing.

**Additional context**

**Comment by dereknola** [comment]
Hi orangedeng, thanks for taking the time to look into the codebase for this issue. However, easier alternatives exist than what you are proposing. You can always disable the builtin LB with `--disable=servicelb`. Or, since you are already compiling K3s for other reasons, you could just modify the code in your fork to accomplish this. I don't see the need to change this for the entire K3s project. K3s is opinionated by design, with the caveat that users can always disable parts they don't like.

**Comment by brandond** [comment]
You can already modify this as part of custom cloud provider config. Start K3s with `kube-cloud-controller-manager-arg=cloud-config=/etc/rancher/k3s/cloud-config.yaml`, and place the following in `/etc/rancher/k3s/cloud-config.yaml`:

```yaml
lbEnabled: true
lbImage: docker.io/rancher/klipper-lb:0.4.4
lbNamespace: kube-system
nodeEnabled: true
rootless: false
```

**Comment by brandond** [comment]
That said, if you wanted to open a PR to change it from a const to a var, we would probably accept that.

**Comment by ShylajaDevadiga** [comment]
### Validated as per @brandond's comment.
**Default install:**
```
$ sudo /usr/local/bin/crictl -r /var/run/k3s/containerd/containerd.sock images |grep klipper-lb
docker.io/rancher/klipper-lb                 v0.4.3                 613ae033d1f9c       4.28MB


$ kubectl get nodes
NAME             STATUS   ROLES                  AGE   VERSION
ip-172-31-1-32   Ready    control-plane,master   58s   v1.27.2+k3s1


$ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   coredns-77ccd57875-ftqwr                 1/1     Running     0          46s
kube-system   local-path-provisioner-957fdf8bc-h8zjg   1/1     Running     0          46s
kube-system   helm-install-traefik-crd-ldfn4           0/1     Completed   0          46s
kube-system   svclb-traefik-7d5aac53-6rsxb             2/2     Running     0          29s
kube-system   helm-install-traefik-sj49x               0/1     Completed   1          46s
kube-system   traefik-64f55bb67d-9q9nb                 1/1     Running     0          29s
kube-system   metrics-server-54dc485875-z8gdt          1/1     Running     0          46s

```
**Installation passing cloud-config.yaml using latest klipper-lb image**
```
$ cat /etc/rancher/k3s/cloud-config.yaml 
{
  "lbEnabled": true,
  "lbImage": "rancher/klipper-lb:v0.4.4",
  "lbNamespace": "kube-system",
  "nodeEnabled": true,
  "rootless": false
}


$ curl -fL https://get.k3s.io| INSTALL_K3S_VERSION=v1.27.2+k3s1 sh -s - server --kube-cloud-controller-manager-arg="cloud-config=/etc/rancher/k3s/cloud-config.yaml"


$ sudo /usr/local/bin/crictl -r /var/run/k3s/containerd/containerd.sock images |grep klipper-lb
docker.io/rancher/klipper-lb                 v0.4.4                 af74bd845c4a8       4.92MB


$ kubectl get nodes
NAME             STATUS   ROLES                  AGE   VERSION
ip-172-31-1-32   Ready    control-plane,master   12m   v1.27.2+k3s1


$ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-957fdf8bc-5vdmw   1/1     Running     0          11m
kube-system   coredns-77ccd57875-9xc7k                 1/1     Running     0          11m
kube-system   helm-install-traefik-crd-sh6w6           0/1     Completed   0          11m
kube-system   svclb-traefik-c874bc2f-j8qnp             2/2     Running     0          11m
kube-system   helm-install-traefik-lpjss               0/1     Completed   1          11m
kube-system   traefik-64f55bb67d-w44wn                 1/1     Running     0          11m
kube-system   metrics-server-54dc485875-hj8cs          1/1     Running     0          11m
```

**Comment by iTaybb** [comment]
Just an heads up to the others trying to apply @brandond workaround:
the cloud-config file must be json and not yaml, and the image tag is "v0.4.4" and not "0.4.4".
