### ISSUE TITLE
Cannot install operator lifecycle manager

### ISSUE THREAD

**Issue by coopstah13** [k3s-io/k3s#765]
**Describe the bug**
Cannot install the operator lifecycle manager in order to use operators within k3s.

**To Reproduce**
Attempt to install the operator lifecycle manager using the installation instructions from operatorhub.io

```
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.11.0/install.sh | bash -s 0.11.0
```

**Expected behavior**
Installation completes successfully

**Screenshots**
```
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
namespace/olm created
namespace/operators created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
serviceaccount/olm-operator-serviceaccount created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
clusterserviceversion.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "olm-operator" successfully rolled out
deployment "catalog-operator" successfully rolled out
Package server phase: Waiting for CSV to appear
CSV "packageserver" failed to reach phase succeeded
```

**Additional context**
I am not sure if this is a bug or a feature request. Also of note, in the above console output though it said that the deployments were "successfully rolled out" I did not see any deployment resources or replica sets actually running.

**Comment by gee4vee** [comment]
Also encountering this.

**Comment by EpiqSty** [comment]
I am facing the same on ARM, looks like OLM missing builds for that architecture
operator-framework/operator-lifecycle-manager#1138

**Comment by njhale** [comment]
@coopstah13, are there any failed pods in the `olm` namespace? If so, their status subresources would be very useful in figuring out what's going wrong.

**Comment by coopstah13** [comment]
Off the top of my head, there were failed pods yes. I don't recall their exact state, since it didn't work I just moved on and made alternate plans, which is unfortunate, but I don't have time to get into figuring this out.

**Comment by coopstah13** [comment]
```
NAME                                READY   STATUS             RESTARTS   AGE
catalog-operator-7b788c597d-jkb52   1/1     Running            0          6m9s
olm-operator-946bd977f-cjh45        0/1     CrashLoopBackOff   5          6m9s
```

**Comment by njhale** [comment]
Since at least one of OLM's pods are running, and they are built from the same source, in the same image, I think it's reasonable to assume that you're encountering a different issue than @EpiqSty.

I'm sorry to hear that this didn't work out for you. When/if you do find the time, and you encounter this issue again, please feel free to post an issue to [OLM's repo](https://github.com/operator-framework/operator-lifecycle-manager) and include the log output of the failing OLM pod. We can continue then/there.

**Comment by coopstah13** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/issues/1148

**Comment by coopstah13** [comment]
This is in the log file
```
time="2019-11-25T02:19:26Z" level=info msg="log level info"
time="2019-11-25T02:19:26Z" level=info msg="TLS keys not set, using non-https for metrics"
time="2019-11-25T02:19:26Z" level=info msg="Using in-cluster kube client config"
time="2019-11-25T02:19:26Z" level=info msg="Using in-cluster kube client config"
time="2019-11-25T02:19:26Z" level=info msg="Using in-cluster kube client config"
time="2019-11-25T02:19:27Z" level=info msg="operator not ready: communicating with server failed: Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: connect: no route to host"
```

Do containers deployed in k3s disallow API server access? Actually that is a huge problem for me if it is true.

**Comment by brandond** [comment]
Closing due to age.

**Comment by brandond** [comment]
This works as per https://github.com/operator-framework/operator-lifecycle-manager/issues/1148#issuecomment-565986256
