### ISSUE TITLE
Install error centos8: conflicting requests - nothing provides container-selinux

### ISSUE THREAD

**Issue by Aysnine** [k3s-io/k3s#7650]
**Environmental Info:**
K3s Version: 

v1.26.5+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux node1 5.4.119-19-0009.11 #1 SMP Wed Oct 5 18:41:07 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

CentOS 8

Cluster Configuration:

1 server.

**Describe the bug:**

Run install error. About k3s-selinux and container-selinux.

**Steps To Reproduce:**

- Installed K3s: `curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -`

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

```
[root@node1 ~]# curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.26.5+k3s1 as release
[INFO]  Downloading hash rancher-mirror.rancher.cn/k3s/v1.26.5-k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Finding available k3s-selinux versions
Rancher K3s Common (stable) 
Error: 
 Problem: conflicting requests
  - nothing provides container-selinux >= 3:2.191.0-1 needed by k3s-selinux-1.3-1.el9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by brandond** [comment]
Hmm, you say you're on CentOS 8 but for some reason it's selected the el9 k3s-selinux rpm. Can you provide the content of `/etc/os-release` on your host?

**Comment by Aysnine** [comment]
@brandond  Thank you for your reply. As I have to use rancher-mirror.rancher.cn in mainland China, I will try again on a server where get.k3s.io can be accessed.

Here is my current server information. `/etc/os-release`:

```
NAME="TencentOS Server"
VERSION="3.1 (Final)"
ID="tencentos"
ID_LIKE="rhel fedora centos"
VERSION_ID="3.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="TencentOS Server 3.1 (Final)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tencentos:tencentos:3"
HOME_URL="https://cloud.tencent.com/product/ts"

TENCENT_SUPPORT_PRODUCT="tencentos"
TENCENT_SUPPORT_PRODUCT_VERSION="3"
NAME_ORIG="TencentOS Server"
```

About OS: https://www.tencentcloud.com/document/product/213/40223

> TencentOS Server 3.1 | It is compatible with the CentOS 8 user mode and uses the tkernel4 version deeply optimized based on the community 5.4 LTS kernel.

**Comment by Aysnine** [comment]
I have conducted installation tests on a server that has access to get.k3s.io, using the same system as before. Below are the results of my testing.

```
Version 3.1 20221031
tlinux3.1-64bit-5.4.119-19.0009-20221031
[root@k3s-test ~]# curl -sfL https://get.k3s.io | sh -s - server --token test
[INFO]  Finding release for channel stable
[INFO]  Using v1.26.5+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Finding available k3s-selinux versions
Rancher K3s Common (stable)                                                                                                                                                   1.2 kB/s | 1.0 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides container-selinux >= 3:2.191.0-1 needed by k3s-selinux-1.3-1.el9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@k3s-test ~]# 
```

**Comment by brandond** [comment]
Upstream RHEL and CentOS have updated to a new version of container-selinux; it looks like your distro has not yet published that package. Until they do, you should manually install the previous release of k3s-selinux from https://github.com/k3s-io/k3s-selinux/releases/tag/v1.2.stable.2
