### ISSUE TITLE
helm-install-traefik fails with the error "exec /usr/bin/entry: exec format error"

### ISSUE THREAD

**Issue by carlossless** [k3s-io/k3s#7673]
**Environmental Info:**
K3s Version: 
```
k3s version v1.26.4+k3s1 (8d0255af)
go version go1.20.4
```

Node(s) CPU architecture, OS, and Version: 
```
Linux crls-kube-pi2 6.1.21 #1-NixOS SMP Tue Jan  1 00:00:00 UTC 1980 aarch64 GNU/Linux
```

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
helm-install-traefik fails with the error "exec /usr/bin/entry: exec format error"

**Steps To Reproduce:**
- Upgrade k3s from 1.25.3+k3s1 to 1.26.4+k3s1

---

It seems like I somehow ended up with the wrong arch for `rancher/klipper-helm:v0.7.7-build20230403`, but I am not entirely certain, and I don't know how to verify that - `k3s crictl` seems to give fairly limited information about images.

**Comment by brandond** [comment]
What model of Pi are you running this on? I'm unable to reproduce this - tests look fine on our aarch64 CI runners, and it runs fine on my personal Pi4b.

```console
sysadm@pi02:~$ uname -a
Linux pi02.lan.khaus 5.19.0-1016-raspi #23-Ubuntu SMP PREEMPT Fri Mar 31 13:54:29 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

sysadm@pi02:~$ sudo ctr run --rm --tty docker.io/rancher/klipper-helm:v0.7.7-build20230403 klipper-helm
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
	echo "KUBERNETES_SERVICE_HOST is using IPv6"
	CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
	CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi
```

Are you perhaps using a local registry mirror, and have pushed a single arch-specific image it, instead of the multi-arch manifest list?

**Comment by carlossless** [comment]
> What model of Pi are you running this on? I'm unable to reproduce this - tests look fine on our aarch64 CI runners, and it runs fine on my personal Pi4b

I'm also running this on rpi-4b!

Still here's the output I get:
```sh
> sudo k3s ctr --address "/run/containerd/containerd.sock" run --rm --tty docker.io/rancher/klipper-helm:v0.7.7-build20230403 klipper-helm
exec /usr/bin/entry: exec format error
```

> Are you perhaps using a local registry mirror, and have pushed a single arch-specific image it, instead of the multi-arch manifest list?

Not unless that's the default configuration, which I guess is not the case and I don't remember to have changed anything in that area.

The image does seem to get pulled very quickly after it has been deleted, but since its size is pretty small, I can't really tell whether that indicates anything.

I noticed that the sha256 digest of `docker.io/rancher/klipper-helm:v0.7.7-build20230403` doesn't seem to match anything that's published here - https://registry.hub.docker.com/r/rancher/klipper-helm/tags?page=1&name=v0.7.7-build20230403

```
> sudo k3s ctr --address "/run/containerd/containerd.sock" images ls
REF                                                                                                    TYPE                                                      DIGEST                                                                  SIZE      PLATFORMS                                                                    LABELS
docker.io/rancher/klipper-helm:v0.7.7-build20230403                                                    application/vnd.docker.distribution.manifest.list.v2+json sha256:3cd71ccc3cce5010865d9ab3548788a3a8cf5e9cfc5b48cc54b5b815675dd121 80.5 MiB  linux/amd64,linux/arm,linux/arm64,linux/s390x                                io.cri-containerd.image=managed
docker.io/rancher/klipper-helm@sha256:3cd71ccc3cce5010865d9ab3548788a3a8cf5e9cfc5b48cc54b5b815675dd121 application/vnd.docker.distribution.manifest.list.v2+json sha256:3cd71ccc3cce5010865d9ab3548788a3a8cf5e9cfc5b48cc54b5b815675dd121 80.5 MiB  linux/amd64,linux/arm,linux/arm64,linux/s390x                                io.cri-containerd.image=managed
registry.k8s.io/pause:3.8                                                                              application/vnd.docker.distribution.manifest.list.v2+json sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d 262.1 KiB linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 io.cri-containerd.image=managed
registry.k8s.io/pause@sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d          application/vnd.docker.distribution.manifest.list.v2+json sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d 262.1 KiB linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 io.cri-containerd.image=managed
sha256:48957d5c01a77280be19ca9f4ba00eaed44a6b5b60028d4879adcfa9b361b976                                application/vnd.docker.distribution.manifest.list.v2+json sha256:3cd71ccc3cce5010865d9ab3548788a3a8cf5e9cfc5b48cc54b5b815675dd121 80.5 MiB  linux/amd64,linux/arm,linux/arm64,linux/s390x                                io.cri-containerd.image=managed
sha256:4e42fb3c9d90ed7895bc04a9d96fe3102a65b521f485cc5a4f3dd818afef9cef                                application/vnd.docker.distribution.manifest.list.v2+json sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d 262.1 KiB linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 io.cri-containerd.image=managed
```

**Comment by brandond** [comment]
I wonder if perhaps the NixOS kernel is missing something? Are you able to reproduce this on PiOS, Debian, or Ubuntu?

That's the correct image.
```console
sysadm@pi02:~$ sudo ctr images ls name==docker.io/rancher/klipper-helm:v0.7.7-build20230403
REF                                                 TYPE                                                      DIGEST                                                                  SIZE     PLATFORMS                                     LABELS
docker.io/rancher/klipper-helm:v0.7.7-build20230403 application/vnd.docker.distribution.manifest.list.v2+json sha256:3cd71ccc3cce5010865d9ab3548788a3a8cf5e9cfc5b48cc54b5b815675dd121 80.5 MiB linux/amd64,linux/arm,linux/arm64,linux/s390x io.cri-containerd.image=managed
```

**Comment by carlossless** [comment]
> I wonder if perhaps the NixOS kernel is missing something?

I'm actually using the rpi-6.1 kernel with that NixOS installation, so I don't think that should be a problem.

> Are you able to reproduce this on PiOS, Debian, or Ubuntu?

I'm pretty sure that I wouldn't be able to reproduce with a fresh install on any OS, including NixOS. I think I messed something up in between the version upgrade, had to uninstall traefik and now am stuck with its reinstallation.

That said, I would like to avoid nuking and salvage this setup somehow...

> That's the correct image

Good to know, thanks!

**Comment by brandond** [comment]
Did you perhaps grab the arm32 version of k3s instead of arm64 when upgrading?

**Comment by carlossless** [comment]
> Did you perhaps grab the arm32 version of k3s instead of arm64 when upgrading?

I checked and it doesn't look like it

```
> file /nix/store/h5k23rfvh7fkriwlhgbvxjkjpkh9g51x-k3s-1.26.4+k3s1/bin/.k3s-wrapped
/nix/store/h5k23rfvh7fkriwlhgbvxjkjpkh9g51x-k3s-1.26.4+k3s1/bin/.k3s-wrapped: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=FWGNi6WUigIz1MTM0SE5/cgURd-dZEsas9R6vgzDz/QB1xHE3_UIcqalpzKEG3/vemFrxowUkDWLFkKFTKb, stripped
```

---

I went ahead and mounted the container to check what binaries it had, and everything was aarch64, although the `/usr/bin/entry` was empty (?)...

```
> file  /tmp/containerfiles/bin/busybox
/tmp/containerfiles/bin/busybox: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, stripped

> file  /tmp/containerfiles/usr/bin/entry
/tmp/containerfiles/usr/bin/entry: empty
```

---

Eventually, I got it fixed by just deleting all images via pulling the image manually, deleting all images, and allowing k3s to pull it again.

```
sudo k3s ctr --address "/run/containerd/containerd.sock" -n k8s.io i rm $(sudo k3s ctr --address "/run/containerd/containerd.sock" -n k8s.io i ls -q)
sudo k3s ctr --address "/run/containerd/containerd.sock" content fetch docker.io/rancher/klipper-helm:v0.7.7-build20230403
```

This doesn't really answer how I got into that initial state, but since it works, I am happy to close this issue! Thanks for the support @brandond !

**Comment by brandond** [comment]
Hmm that's odd. Perhaps some undetected corruption in the containerd image store?

**Comment by carlossless** [comment]
> Hmm that's odd. Perhaps some undetected corruption in the containerd image store or overlayfs?

Perhaps. I don't think I'll be able to verify that anymore though :(

**Comment by brandond** [comment]
Especially on a pi, that is the most likely explanation.

**Comment by chairwa** [comment]
related issue: https://github.com/containerd/containerd/issues/5854
