### ISSUE TITLE
k3s compilation fails

### ISSUE THREAD

**Issue by huntsman-li** [k3s-io/k3s#7679]
**Environmental Info:**
K3s Version: 
release-1.26

Node(s) CPU architecture, OS, and Version: 
22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

**Describe the bug:**
go mod tidy

go: golang.zx2c4.com/wireguard@v0.0.0-20220117163742-e0b8f11489c5 requires
	golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: reading https://goproxy.io/golang.zx2c4.com/go118/netip/@v/v0.0.0-20211111135330-a4a02eeacf9d.mod: 404 Not Found
	server response: not found: golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found

**Comment by brandond** [comment]
1. We don't generally build on Darwin, so you may run into some oddities.
2. The error messages you're reporting are from systems not under our control. If the errors don't resolve shortly, and can be reproduced when building elsewhere, we can evaluate next steps.
