### ISSUE TITLE
Unable to use Podman as the Container Runtime Engine

### ISSUE THREAD

**Issue by probrittle** [k3s-io/k3s#7697]
**Environmental Info:**
RHEL Version: 8.6
K3s Version:  v1.24.3+k3s1

k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1

**Describe the bug:**

I'm trying to use podman container runtime engine instead of the default containerd.

According to the ```k3s server --container-runtime-endpoint``` I should be able to use podman instead of containerd so long as I specify the podman socket.

**Steps To Reproduce:**

- Installed Podman 3.2.3
- Started and enabled podman.socket
- Attempted to install K3s v1.24.3+k3s1 with the following command: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.3+k3s1 INSTALL_K3S_EXEC="server --container-runtime-endpoint unix:///run/podman/podman.sock" sh -
```
- Attempted to start the K3s service with the following two commands:
``` 
systemctl daemon-reload
systemctl start k3s
```
- Got error and ran the following command:
```
journalctl -xe
```

**Expected behavior:**

K3s is using podman as the container runtime engine instead of containerd.

**Actual behavior:**

When I try to install K3s with the ```container-runtime-endpoint``` flag it fails to start the service and I cannot start it back up.
**Additional context / logs:**

- When I try the installation method mentioned above this is what the system file looks like:
```
cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--container-runtime-endpoint' \
        'unix:///run/podman/podman.sock' \
```
- Output from ```journalctl -xe``` command:
```
level=fatal msg="kubelet exited: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable
```

**Comment by brandond** [comment]
Podman does not, as far as I know, offer a CRI implementation. It has a restful http API, but it does not expose an actual grpc container runtime service usable by the kubelet. If you have evidence to the contrary, please share more information.
