### ISSUE TITLE
How can i deal with certs expiry problem?

### ISSUE THREAD

**Issue by qadet123** [k3s-io/k3s#770]
**Is your feature request related to a problem? Please describe.**
What can i do if my k3s componets' certificates/kubeconfigs expired? We suffered this a lot the first time use k8s(kubeadm).

**Describe the solution you'd like**
A painless way to rotate these credentials or some flags to generate them  so they can have enough time before expired.

**Comment by matlec** [comment]
I think this issue deserves more attention. As of now I do not see an easy way to rotate the client, server and request header certificates generated by k3s. This essentially renders k3s clusters unusable 1 year after initial deployment. Considering that k3s targets embedded devices, (unattended) certificate rotation is a _must_ requirement.

**Comment by schmitch** [comment]
/cc @davidnuzik sorry to cc you here, but I guess this issue can be closed.

K3s rotates the certificate upon restart if the cert expiry is < 90 days (am I correct here?)

(Btw. I would've prefered if an internal cluster cronjob could've been activated that would rotate the certs on all nodes.)

**Comment by davidnuzik** [comment]
Yes we rotate certs if cert expiry is less than 90 days. For this to happen, k3s must be restarted. If we'd like to change the functionality or if have ideas for improvement / tweaks feel free to open an issue for feature / enhancements consideration.

**Comment by schmitch** [comment]
well for myself that would be fine. but I think for k3os users and iot users they probably need something more automatic.
something like system-upgrade-controller.

**Comment by brandond** [comment]
Anything that updated the certs on disk would probably need k3s to restart anyway to pick up the changes. It's probably easiest to just schedule a cron task on whatever OS you're using to reboot the node or just restart the service.

**Comment by arifwn** [comment]
RKE seems to generate certs with 10 year expiry dates. I think it would be great if k3s generates certificates with long expiry time too. IMO rotating certs only when k3s is restarted within 90 days of certificate expiry date may cause people to miss this time window and ended up with expired certificates, especially people like me who usually do maintenance every >6 months on less important clusters.
