### ISSUE TITLE
after physical restart,pods in some virtual server can not reach other service

### ISSUE THREAD

**Issue by Nathan-lea** [k3s-io/k3s#7720]
**Environmental Info:**
K3s Version: 

v1.24.10+k3s1
Node(s) CPU architecture, OS, and Version: 

Linux master01 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

3 server
**Describe the bug:**

pods in two servers can not reach any service
**Steps To Reproduce:**

- Installed K3s: 
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_VERSION=v1.24.10+k3s1  INSTALL_K3S_MIRROR=cn sh -s - server --docker --disable traefik --disable servicelb  --datastore-endpoint="mysql://user:password@tcp(mysqldb:3306)/k3sdb"
**Expected behavior:**

**Actual behavior:**

normal server:
ping nginx 
PING nginx.crm.svc.cluster.local (10.43.146.193) 56(84) bytes of data.

abnormal servers:
ping nginx 
ping: nginx: Try again

**Additional context / logs:**

**Comment by brandond** [comment]
Are you able to attach journald logs from the affected servers, or anything else whatsoever? There's not really any information to work with here.

**Comment by Nathan-lea** [comment]
thanks,last night we retry it, found it may  caused by virtual machine migrate from a phisical machine to another.

**Comment by dereknola** [comment]
Closing as comments indicate that the issue has been resolved. @Nathan-lea If you feel this is not the case, please reopen the issue.
