### ISSUE TITLE
[Question] Scheduler changes

### ISSUE THREAD

**Issue by Adirio** [k3s-io/k3s#773]
This is neither a bug report nor a feature request, but I haven't found anywhere else to ask this question.

Has the k8s scheduler been modified to reduce its footprint?

We have some setups where we have multiple schedulers. Our normal way of developing this new custom schedulers is by taking the k8s scheduler source code, modifying it to our requirements and building a docker image from it. Then we deploy this new schedulers as normal k8s artifacts (deployments or stateful sets) and further pods will be able to be scheduled by either of them.

I was wondering if the scheduler has been modified in any way for k3s, in order to use this modified version instead of the k8s one.

**Comment by erikwilson** [comment]
The footprint of k8s has been reduced in k3s by combining separate processes into a single process & executable. 

That same pattern could be applied to other things, instead of running a docker image for each scheduler have a single image which runs all of your schedulers in the same process.

**Comment by Adirio** [comment]
The pattern I'm using in this case is different. The different schedulers are spread over several nodes.

My question was focused on source modification, like feature removal or algorithm simplification, related to the scheduler more than the general design pattern of combining all the processes into a single one.

**Comment by brandond** [comment]
Closing due to age.

**Comment by tmenouer** [comment]
Did you find a solution to create several scheduler with K3S ?
