### ISSUE TITLE
Validate Rocky 8.8

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#7731]
**K3s Versions to be Validated**

- 1.27
- 1.26
- 1.25

**Testing Considerations**

_QA to edit as necessary_
1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade

**Additional Information**

**Jira Ticket**: https://jira.suse.com/browse/SURE-6405

This should be validated with selinux enabled:
```
# /etc/rancher/k3s/config.yaml
selinux: true
```

**Comment by fmoral2** [comment]
Tested against:
1.25.8
1.26.5
1.27.2

<summary>Validation</summary>

```console
1. Install and run sonobuoy conformance tests on a hardened cluster -  ok 
2. Validate SUC upgrade - ok 
```
