### ISSUE TITLE
Validate RHEL 9.2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#7732]
**K3s Versions to be Validated**

- 1.27
- 1.26

**Testing Considerations**

_QA to change as necessary_
1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager

**Additional Information**

**Jira Ticket**: https://jira.suse.com/browse/SURE-6485

This should be validated with selinux enabled:
```
# /etc/rancher/k3s/config.yaml
selinux: true
```

**Comment by aganesh-suse** [comment]
v1.26.5+k3s sonobuoy results:  https://jenkins.int.rancher.io/job/rancher_qa/view/common-Jobs/job/rancher-v3_sonobuoy_test/64/

**Comment by aganesh-suse** [comment]
SUC Upgrades were successful.

Used system controller:
```
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/[v0.11.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.11.0-dev.1)/system-upgrade-controller.yaml
```
Created workloads. 
Applied a plan.yaml to upgrade the servers and workers 
from v1.25.10+k3s -> v1.26.5+k3s -> v1.27.2+k3s versions successfully.

**Comment by aganesh-suse** [comment]
3 server/ 1 agent setup

Installed k3s v1.26.5+k3s1 

with sample server config.yaml:

```
sudo mkdir -p /etc/rancher/k3s
sudo bash -c 'cat <<EOF> /etc/rancher/k3s/config.yaml
write-kubeconfig-mode: "0644"
debug: true
token: secret
cluster-init: true
selinux: true
node-label:
  - k3s-upgrade=server
tls-san: "18.117.117.224.nip.io"
node-external-ip: 18.117.117.224
EOF'
```

Then helm installed rancher: 

```
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest && \
helm repo add jetstack https://charts.jetstack.io && \
helm repo update && \
kubectl create namespace cattle-system && \
kubectl create namespace cert-manager && \
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.12.1/cert-manager.crds.yaml && \
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.12.1
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=18.117.117.224.nip.io \
  --set rancherImageTag=v2.7-head \
  --version=v2.7.5-rc2
```

Was able to get to rancher UI
