### ISSUE TITLE
Validate Oracle Linux 9.2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#7733]
**K3s Versions to be Validated**

- 1.27
- 1.26

**Testing Considerations**

_QA to change as necessary_
1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade

**Additional Information**

**Jira Ticket**: https://jira.suse.com/browse/SURE-6485

This should be validated with selinux enabled:
```
# /etc/rancher/k3s/config.yaml
selinux: true
```

**Comment by est-suse** [comment]
AMI-0c50bf6c5b057201a
