### ISSUE TITLE
Fix spelling test

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#7739]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

When merging a PR, we have a spell check test running. It is failing right now with the error:
```
Run codespell --skip=.git,./scripts,MAINTAINERS,LICENSE,go.mod,go.sum --check-filenames --ignore-regex=.te# --ignore-words=.codespellignore
./tests/e2e/validatecluster/validatecluster_test.go:304: stoped ==> stopped
Error: Process completed with exit code 65.
```

This PR fixes that
**Steps To Reproduce:**

https://github.com/k3s-io/k3s/actions/runs/5241218582/jobs/9463021221

**Expected behavior:**

No errors in the spell check

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
Closing as this is tested/validated in CI itself
