### ISSUE TITLE
Simplify vagrant config in networking e2e tests

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#7744]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Our e2e tests are changing Vagrant networking config and there is no need for that:
```
    :libvirt__dhcp_enabled => false,
    :libvirt__forward_mode => "none",
 ```

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
This is a change to CI e2e tests, and is validated as part of those running on PRs/merge so is okay to close with nothing additional to validate.
