### ISSUE TITLE
Unable to rotate CA certificates with custom data-dir

### ISSUE THREAD

**Issue by zhaileilei123** [k3s-io/k3s#7774]
**Environmental Info:**
K3s Version: 
[root@localhost ~]# k3s -version
k3s version v1.24.14+k3s1 (313a3b99)
go version go1.19.9

Node(s) CPU architecture, OS, and Version: 
Operating System: Kylin Linux Advanced Server V10 (Tercel)
Architecture: arm64
Kernel: Linux 4.19.90-23.8.v2101.ky10.aarch64

Cluster Configuration:
[root@localhost ~]# kubectl get node
NAME    STATUS   ROLES                  AGE   VERSION
node0   Ready    control-plane,master   46h   v1.24.14+k3s1

**Describe the bug:**
My reference document at https://docs.k3s.io/cli/certificate. Rotating Self-Signed CA Certificates.
export DATA_DIR=/data/k3s && bash -x rotate-default-ca-certs.sh 
is ok,but When I executed the command k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca, an error occurred. The error message is as follows:
[root@localhost tls]# k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca/
FATA[0000] open /var/lib/rancher/k3s/server/token: no such file or directory
[root@localhost tls]# k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca
FATA[0000] open /var/lib/rancher/k3s/server/token: no such file or directory

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Need to add a cli flag for this. Also, should probably have config file loading support for the certificate commands.

**Comment by zhaileilei123** [comment]
ln -s  /data /var/lib/rancher
[root@localhost server]# k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca
certificates saved to datastore

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id 2eddfe6cf4e67b7d6aab0fe8311d72372030459e
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Configuration:*
Single node

*Steps*
1. Install k3s passing custom dir using --data-dir flag
2. Generate new certs passing the above custom data-dir
3. Rotate the certs with the k3s tool
4. Restart k3s

**Replication results**
<details>

```
$ sudo mkdir -p /data/k3s
$ curl -fL https://get.k3s.io| INSTALL_K3S_VERSION=v1.27.3+k3s1 sh -s - server --cluster-init --data-dir=/data/k3s
$ wget https://github.com/k3s-io/k3s/raw/master/contrib/util/rotate-default-ca-certs.sh
$ chmod u+x rotate-default-ca-certs.sh
$ export DATA_DIR=/data/k3s && rotate-default-ca-certs.sh
$ k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca

To update certificates, you may now run:
    k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca
root@ip-172-31-12-65:~# k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/fac8750497b6e8dd01288d91f78fa4730acebd06ffcbfa232e5120b1fec6e476
FATA[0000] open /var/lib/rancher/k3s/server/token: no such file or directory
```

</details>


**Validation results**
<details>

```
#  mkdir -p /data/k3s
# curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=2eddfe6cf4e67b7d6aab0fe8311d72372030459e sh -s - server --cluster-init --data-dir=/data/k3s
```
Generate new certs in data-dir
```
# wget https://github.com/k3s-io/k3s/raw/master/contrib/util/rotate-default-ca-certs.sh

# export DATA_DIR=/data/k3s && rotate-default-ca-certs.sh 
```
Rotate the certs with the k3s tool
```
# k3s certificate rotate-ca --path=/data/k3s/server/rotate-ca --data-dir=/data/k3s
```
Restart k3s service
```
root@ip-172-31-7-8:~# sudo systemctl restart k3s
root@ip-172-31-7-8:~# ls -l /data/k3s/server/tls/
total 140
-rw-r--r-- 1 root root 3075 Jul 12 19:59 client-admin.crt
-rw------- 1 root root  227 Jul 12 19:59 client-admin.key
-rw-r--r-- 1 root root 3142 Jul 12 19:59 client-auth-proxy.crt
-rw------- 1 root root  227 Jul 12 19:59 client-auth-proxy.key
-rw-r--r-- 1 root root 2468 Jul 12 19:56 client-ca.crt
-rw------- 1 root root  454 Jul 12 19:56 client-ca.key
-rw-r--r-- 1 root root  627 Jul 12 19:59 client-ca.nochain.crt
-rw-r--r-- 1 root root 3063 Jul 12 19:59 client-controller.crt
-rw------- 1 root root  227 Jul 12 19:59 client-controller.key
-rw-r--r-- 1 root root 3059 Jul 12 19:59 client-k3s-cloud-controller.crt
-rw------- 1 root root  227 Jul 12 19:59 client-k3s-cloud-controller.key
-rw-r--r-- 1 root root 3051 Jul 12 19:59 client-k3s-controller.crt
-rw------- 1 root root  227 Jul 12 19:59 client-k3s-controller.key
-rw-r--r-- 1 root root 3079 Jul 12 19:59 client-kube-apiserver.crt
-rw------- 1 root root  227 Jul 12 19:59 client-kube-apiserver.key
-rw-r--r-- 1 root root 3042 Jul 12 19:59 client-kube-proxy.crt
-rw------- 1 root root  227 Jul 12 19:59 client-kube-proxy.key
-rw------- 1 root root  227 Jul 12 19:49 client-kubelet.key
-rw-r--r-- 1 root root 3051 Jul 12 19:59 client-scheduler.crt
-rw------- 1 root root  227 Jul 12 19:59 client-scheduler.key
-rw-r--r-- 1 root root 3083 Jul 12 19:59 client-supervisor.crt
-rw------- 1 root root  227 Jul 12 19:59 client-supervisor.key
-rw-r--r-- 1 root root 3823 Jul 12 19:49 dynamic-cert.json
drwxr-xr-x 2 root root 4096 Jul 12 19:49 etcd
-rw-r--r-- 1 root root 2551 Jul 12 19:56 request-header-ca.crt
-rw------- 1 root root  454 Jul 12 19:56 request-header-ca.key
-rw-r--r-- 1 root root 2468 Jul 12 19:56 server-ca.crt
-rw------- 1 root root  454 Jul 12 19:56 server-ca.key
-rw-r--r-- 1 root root  627 Jul 12 19:59 server-ca.nochain.crt
-rw------- 1 root root 1675 Jul 12 19:59 service.current.key
-rw------- 1 root root 3350 Jul 12 19:56 service.key
-rw-r--r-- 1 root root 3274 Jul 12 19:59 serving-kube-apiserver.crt
-rw------- 1 root root  227 Jul 12 19:59 serving-kube-apiserver.key
-rw------- 1 root root  227 Jul 12 19:49 serving-kubelet.key
drwx------ 2 root root 4096 Jul 12 19:49 temporary-certs
root@ip-172-31-7-8:~#
```
</details>
