### ISSUE TITLE
[Release 1.26] Fix a couple of tailscale integration issues

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#7780]
Backports: https://github.com/k3s-io/k3s/issues/7771 https://github.com/k3s-io/k3s/issues/7772

**Comment by ShylajaDevadiga** [comment]
### Validated on k3s version v1.26.6-rc1+k3s1 (3b1919b0), logs show useful message when auth key is expired or invalid
## Environment Details
**Infrastructure**
Cloud EC2 instance

**Node(s) CPU architecture, OS, and Version:**
SLES 15 SP3

**Cluster Configuration:**
Single node

**Config.yaml:**
```
write-kubeconfig-mode: 644
token: secret
cluster-init: true
vpn-auth: "name=tailscale,joinKey=tskey-auth-PASSKEY"
```
**Before fix:**
```
Jun 16 07:07:50 ip-172-31-6-131 k3s[4361]: time="2023-06-16T07:07:50Z" level=info msg="Starting VPN: tailscale"
Jun 16 07:07:51 ip-172-31-6-131 k3s[4361]: exit status 1
```
**After fix:**
```
Jun 16 07:04:01 ip-172-31-5-25 k3s[4245]: time="2023-06-16T07:04:01Z" level=info msg="Starting VPN: tailscale"
Jun 16 07:04:01 ip-172-31-5-25 k3s[4245]: time="2023-06-16T07:04:01Z" level=fatal msg="tailscale up failed: backend error: invalid key: API key PASSKEY not valid\n: exit status 1">

```

**Comment by ShylajaDevadiga** [comment]
Related issue https://github.com/k3s-io/k3s/issues/7772
