### ISSUE TITLE
Slow Image pull times on the Agent

### ISSUE THREAD

**Issue by vanshreddy** [k3s-io/k3s#7795]
We have a k3s cluster setup on EC2. We are using it to manage devices. We have several agents connected to the cluster. We have images hosted on ECR. 

**Environmental Info:**
K3s Version: 

k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8

Node(s) CPU architecture, OS, and Version: 

Linux {HOSTNAME} 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:

We have 3 master nodes and around 20 agents.

**Describe the bug:**

**PROBELM**
Agents have 5 mbps internet. We are struggling with slow image pull times on the agent. We use the docker container run time on the agent. I am comparing the time it takes to do a docker pull and comparing it with how long the kubelet pulls the images. The time is significantly higher. We want to minimize the time of pulling the image. Any suggestions on how to bring the time to pull the images down. 

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

Slower image pull times

**Actual behavior:**

Faster Image pull times
**Additional context / logs:**

**Comment by Shawn1874** [comment]
Did you mean to write the that the expected behavior is faster image pull times and the actual behavior is slow image pull times?

**Comment by vanshreddy** [comment]
Awesome let me try the setting . Would defining resource constraints on all the containers help pull time? ( increasing the QOS of the pod?

**Comment by brandond** [comment]
Pulls are done by the kubelet, not the pod... so no, changing the pod resources would have no effect on pulls, unless you are for some reason running k3s itself in a pod.

**Comment by brandond** [comment]
Did that make any difference?
