### ISSUE TITLE
Dynamic OIDC for kubernetes API

### ISSUE THREAD

**Issue by cybercoder** [k3s-io/k3s#7814]
K3S API currently supports single tenant OIDC e.g:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--write-kubeconfig-mode=0644' \
        '--flannel-backend=none' \
        '--disable-network-policy' \
        '--token=SECRET' \
        '--datastore-endpoint=postgres://postgres:postgres@mylabpg:5432/k3s' \
        '--kube-apiserver-arg' 'oidc-username-claim=email' \
        '--kube-apiserver-arg' 'oidc-groups-claim=groups' \
        '--kube-apiserver-arg' 'oidc-client-id=k3s' \
        '--kube-apiserver-arg' 'oidc-ca-file=/opt/keycloak/certs/rootCA.crt' \
        '--kube-apiserver-arg' 'oidc-issuer-url=https://mylabkeycloak:8011/realms/master'
```
currently, I can use the master realm (tenant) on my KeyCloak (the IAM), only.
But I need to use it in multi-tenat mode on-the-fly
**Describe the solution you'd like**

If ```oidc-issuer-url``` be an optional parameter on API header, it can handle multi-tenant IAM.

**Comment by brandond** [comment]
> If oidc-issuer-url be an optional parameter on API header

I'm unclear what you're asking for. These args are all just passed through to the kubernetes apiserver. Are you asking for changes to the K3s apiserver args passthrough, or for changes to the Kubernetes apiserver itself?
