### ISSUE TITLE
failed to list *core.Node: unexpected EOF

### ISSUE THREAD

**Issue by joelcomp1** [k3s-io/k3s#7837]
**Environmental Info:**
K3s Version:  1.27.1

Node(s) CPU architecture, OS, and Version: 
Rocky 8.7 x86-64

Cluster Configuration:
Single node

**Describe the bug:**
k3s wont restart after a server reboot, had been working fine but now won't come back as much as we restart service or the server.

**Steps To Reproduce:**
Reboot device or restart service same issue

**Expected behavior:**
k3s should come back up

**Actual behavior:**
K3s wont become available (node that is)

**Additional context / logs:**
Attached logs
[k3s.log](https://github.com/k3s-io/k3s/files/11906783/k3s.log)

**Comment by joelcomp1** [comment]
No sorry we didn't see anything initially and have since re-installed k3s on it.  The only thing we could guess is if some how etcd got corrupted in the sqlite embedded DB?

**Comment by joelcomp1** [comment]
it seems to have I am having issues installing our helm charts on top of it but I am not sure its related.  But yes I did run the k3s-install and re-installed with the curl menthod.  

I think it may have occurred from hard cycling (pulling power) from our radio vs using power off button.  Though we are concerned this could happen easily in the future depending on how users operate the radio

We had thought about running the cron job to backup the etcd store often (like every few minutes) and then always restoring it on boot would that be more failsafe?

**Comment by joelcomp1** [comment]
yup a single node...so I had k3s running and was installing my apps back in just like I had before and now it went into another bad state now the node is always not ready:

kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

so that looks good

At the end of dmesg it has:

[  180.796051] bash[26166]: segfault at 5604b2c23f90 ip 00005604b265f5b1 sp 00007ffd95698890 error 4 in bash[5604b262e000+108000]
[  180.796063] Code: 00 8b 3d 22 6c 2e 00 85 ff 78 ad 31 f6 e8 77 05 04 00 48 89 43 38 eb a0 90 f3 0f 1e fa 53 48 8b 1d 5c 21 2e 00 48 85 db 74 5f <48> 8b 03 48 8b 4b 10 c7 05 6e 21 2e 00 00 00 00 00 8b 53 08 48 8b


Journalctl log is attached

[output.txt](https://github.com/k3s-io/k3s/files/11909913/output.txt)

**Comment by joelcomp1** [comment]
copy results below, we are just using the k3s local storage, i believe our disk is a SSD 

mytest: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
fio-3.35-33-g50875
Starting 1 process
mytest: Laying out IO file (1 file / 100MiB)
Jobs: 1 (f=1)
Jobs: 1 (f=1): [W(1)][100.0%][w=2167KiB/s][w=965 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=32793: Thu Jun 29 16:09:52 2023
  write: IOPS=1082, BW=2431KiB/s (2489kB/s)(100.0MiB/42124msec); 0 zone resets
    clat (usec): min=3, max=148, avg=10.27, stdev= 3.50
     lat (usec): min=4, max=148, avg=10.50, stdev= 3.54
    clat percentiles (usec):
     |  1.00th=[    7],  5.00th=[    8], 10.00th=[    8], 20.00th=[    9],
     | 30.00th=[    9], 40.00th=[   10], 50.00th=[   10], 60.00th=[   10],
     | 70.00th=[   11], 80.00th=[   12], 90.00th=[   14], 95.00th=[   15],
     | 99.00th=[   20], 99.50th=[   24], 99.90th=[   54], 99.95th=[   74],
     | 99.99th=[  102]
   bw (  KiB/s): min= 1810, max= 2547, per=100.00%, avg=2431.71, stdev=101.29, samples=84
   iops        : min=  806, max= 1134, avg=1082.83, stdev=45.08, samples=84
  lat (usec)   : 4=0.01%, 10=63.06%, 20=35.99%, 50=0.83%, 100=0.11%
  lat (usec)   : 250=0.01%
  fsync/fdatasync/sync_file_range:
    sync (usec): min=387, max=51911, avg=911.47, stdev=738.20
    sync percentiles (usec):
     |  1.00th=[  416],  5.00th=[  420], 10.00th=[  445], 20.00th=[  478],
     | 30.00th=[  529], 40.00th=[  586], 50.00th=[  971], 60.00th=[ 1057],
     | 70.00th=[ 1139], 80.00th=[ 1221], 90.00th=[ 1319], 95.00th=[ 1369],
     | 99.00th=[ 1500], 99.50th=[ 3359], 99.90th=[ 8979], 99.95th=[ 9110],
     | 99.99th=[27919]
  cpu          : usr=0.54%, sys=3.81%, ctx=110003, majf=0, minf=14
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,45590,0,0 short=45590,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=2431KiB/s (2489kB/s), 2431KiB/s-2431KiB/s (2489kB/s-2489kB/s), io=100.0MiB (105MB), run=42124-42124msec

Disk stats (read/write):
    dm-2: ios=1/193361, merge=0/0, ticks=3/40110, in_queue=40113, util=98.71%, aggrios=1/142682, aggrmerge=0/51720, aggrticks=3/37721, aggrin_queue=37725, aggrutil=98.68%
  sda: ios=1/142682, merge=0/51720, ticks=3/37721, in_queue=37725, util=98.68%

**Comment by joelcomp1** [comment]
@vtrenton did you have any other ideas / thoughts on this?  We swapped out HDD and re-imaged everything and it seems OK now so maybe was a bad HDD we aren't 100% sure at this point

**Comment by brandond** [comment]
@vtrenton did y'all ever get this resolved? Offline we'd discussed the odd sqlite database error that I haven't seen before and can't replicate locally.

**Comment by joelcomp1** [comment]
@vtrenton got it thanks.  I'll see if we still have the disk around some where to test, it is just a simple m.2 HDD on a single board computer so I'm not 100% sure it has all the SMART attribute stuff but I'll take a look
