### ISSUE TITLE
Unable to start k3s server (panic: runtime error: slice bounds out of range [:8] with capacity 5)

### ISSUE THREAD

**Issue by arthurlemeux** [k3s-io/k3s#7851]
**Environmental Info:**
K3s Version: First appears in **v1.25.7+k3s1** and still appears after updated to **v1.27.3+k3s1**.

Node(s) CPU architecture, OS, and Version: Linux kybio 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (VMWare VM with 8Go of RAM and 4 processors)

Cluster Configuration: Single node cluster

**Describe the bug:**

Hello,

My team and I started the VM containing the k3s cluster with our services (This VM wasn't running for 3 months since April) and the k3s service failed to start with the following output :

![Capture](https://github.com/k3s-io/k3s/assets/114343780/8b026f18-3f0c-494b-b566-72a57be2ff5c)

We tried to update k3s and the same error appeared. We also restarted the VM, use the `k3s-killall.sh` scripts and then restart with the command line or with the `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --write-kubeconfig-mode 644 --etcd-expose-metrics --cluster-init" sh -` scripts but the same error is still here.

**Steps To Reproduce:**

- Installed K3s: We used `INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --write-kubeconfig-mode 644 --etcd-expose-metrics --cluster-init"`

**Expected behavior:**

We wanted the server to start the cluster and our services.

**Actual behavior:**

K3s cannot start and we are not able to recover our services.

**Additional context / logs:**

Thanks for your help !

**Comment by PoudNL** [comment]
Experiencing the same issue. After a power failure the K3S service does not start anymore.
 `Jul 05 10:27:05 k8s-n1 k3s[2899]: {"level":"info","ts":"2023-07-05T10:27:05.522Z","caller":"membership/cluster.go:287","msg":"set cluster version from store","cluster-version":"3.5"}
Jul 05 10:27:05 k8s-n1 k3s[2899]: {"level":"warn","ts":"2023-07-05T10:27:05.522Z","caller":"auth/store.go:1220","msg":"simple token is not cryptographically signed"}
Jul 05 10:27:05 k8s-n1 k3s[2899]: {"level":"info","ts":"2023-07-05T10:27:05.523Z","caller":"mvcc/kvstore.go:345","msg":"restored last compact revision","meta-bucket-name":"meta","meta-bucket-name-key":"finishedCompactRev","restored-compact-revision":47678348}
Jul 05 10:27:05 k8s-n1 k3s[2899]: panic: runtime error: slice bounds out of range [:8] with capacity 5
Jul 05 10:27:05 k8s-n1 k3s[2899]: goroutine 234 [running]:
Jul 05 10:27:05 k8s-n1 k3s[2899]: go.etcd.io/etcd/server/v3/mvcc.bytesToRev(...)
Jul 05 10:27:05 k8s-n1 k3s[2899]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.3-k3s1/mvcc/revision.go:58
Jul 05 10:27:05 k8s-n1 k3s[2899]: go.etcd.io/etcd/server/v3/mvcc.restoreIntoIndex.func1()
Jul 05 10:27:05 k8s-n1 k3s[2899]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.3-k3s1/mvcc/kvstore.go:466 +0x6fc
Jul 05 10:27:05 k8s-n1 k3s[2899]: created by go.etcd.io/etcd/server/v3/mvcc.restoreIntoIndex
Jul 05 10:27:05 k8s-n1 k3s[2899]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.3-k3s1/mvcc/kvstore.go:441 +0xfa
Jul 05 10:27:05 k8s-n1 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 05 10:27:05 k8s-n1 systemd[1]: k3s.service: Failed with result 'exit-code'.
Jul 05 10:27:05 k8s-n1 systemd[1]: Failed to start Lightweight Kubernetes.
Jul 05 10:27:05 k8s-n1 systemd[1]: k3s.service: Consumed 1.108s CPU time.`

**Comment by brandond** [comment]
It appears that the etcd datastore files have been corrupted. This failure is deep in the etcd key/value store code; I don't think there's anything we as a project can do to help if the files become corrupted due to unexpected power loss on unsafe storage. I would recommend restoring from an etcd snapshot.
