### ISSUE TITLE
"unable to select an IP from default routes."

### ISSUE THREAD

**Issue by x-coder-L** [k3s-io/k3s#7865]
I find 

> maybe alter that to
> 
> ```shell
> ip link add dummy0 type dummy
> ip link set dummy0 up
> ip addr add 169.254.255.254/31 dev dummy0
> ip route add default via 169.254.255.255 dev dummy0 metric 1000
> ```
> 
> You may have to play with it a bit - I haven't tested this myself recently.

hello, We saw a similar issue to this.But follow that step can not solve the problem.As I setted the dummy route and then restart k3s, it failed to start k3s and report a fatal message "unable to select an IP from default routes."
this is my route info:
`[root@master route-test]# ip route

default via 169.254.255.255 dev dummy0 metric 1000 
10.42.0.0/24 dev cni0 proto kernel scope link src 10.42.0.1 
169.254.255.254/31 dev dummy0 proto kernel scope link src 169.254.255.254 
192.168.169.0/24 dev ens33 proto kernel scope link src 192.168.169.12 metric 100`

And after I checked the source code of k3s and k8s , I found when k3s want to get hostname and ip, it will use func ChooseHostInterface() in "k8s.io/apimachinery/pkg/util/net" package and in this package it will detect the default route and check the ip by func IsGlobalUnicast() in net package, but now IsGlobalUnicast() will return false when using 169.xx.xx.xx.So I think maybe the change of func IsGlobalUnicast() that make the dummy route not work. Is there any other way to solve this problem?

_Originally posted by @x-coder-L in https://github.com/k3s-io/k3s/issues/1144#issuecomment-1621236881_

**Comment by brandond** [comment]
Lets keep this in the other thread, since it is a continuation of the existing discussion.
