### ISSUE TITLE
i want to know what kind of error this is 

### ISSUE THREAD

**Issue by sjfbjs** [k3s-io/k3s#789]
ERRO[2019-09-04T10:17:49.525083958+08:00] failed to get CA certs at https://127.0.0.1:32776/cacerts: Get https://127.0.0.1:32776/cacerts: read tcp 127.0.0.1:49286->127.0.0.1:32776: read: connection reset by peer 
This error  occurs when i install k3s-agent..
Which  components  i loss? this is important to me.

**Comment by lpil** [comment]
Hi there. Could you give some more detail as to what steps you have taken to get this error? Without more context we are unable to help you. Thank you.

**Comment by sriveros95** [comment]
I think I have the same error 

I'm trying to deploy in Digital Ocean doing some initial setup.
I use user-data at creation of the droplets and the script is the one provided in the tutorial
https://www.digitalocean.com/community/tutorials/automating-initial-server-setup-with-ubuntu-18-04
Additionally I enable UFW, these are the rules
 ```
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    LIMIT       Anywhere                  
6443/tcp                   LIMIT       Anywhere                  
8472/udp                   ALLOW       Anywhere                  
OpenSSH (v6)               LIMIT       Anywhere (v6)             
6443/tcp (v6)              LIMIT       Anywhere (v6)             
8472/udp (v6)              ALLOW       Anywhere (v6)  
```

**Comment by sriveros95** [comment]
Hmm no, I tried with some fresh Ubuntu 18.04.3 (LTS) x64 (2gb & 2CPU) without the user-data or any initial configuration other than following the instructions here in the readme running as root

**Comment by sriveros95** [comment]
I tried again with new droplet names and this time without a Digital Ocean Firewall that I was applying with a DO Tag and they worked...

**Comment by sriveros95** [comment]
Probably bad firewall configuration in my case. I have it now working with both ufw and digital ocean's firewall. I was missing allowing them to talk to each other while blocking outside traffic using a tag.
