### ISSUE TITLE
how to get token for restful api ?

### ISSUE THREAD

**Issue by helloworld-men** [k3s-io/k3s#7935]
Are there a way to get the TOKEN for restful api's bearer token?

**Comment by brandond** [comment]
Which API in particular are you asking about?

**Comment by helloworld-men** [comment]
Kubernetes API, I want connect cluster use curl, so i cloud use a TOKEN in Kubernetes API, like "curl -k "https://xxx:6443/api/v1/persistentvolumes/my-nfs-pv" -H "Authorization: Bearer $TOKEN""

> Which API in particular are you asking about?

**Comment by helloworld-men** [comment]
> Which API in particular are you asking about?

It's Kubernetes API, I want connect cluster use curl, so i should use a TOKEN in Kubernetes API, like "curl -k "https://xxx:6443/api/v1/persistentvolumes/my-nfs-pv" -H "Authorization: Bearer $TOKEN""

**Comment by brandond** [comment]
This isn't really a k3s issue then, that's part of core Kubernetes:
https://kubernetes.io/docs/concepts/security/service-accounts/#get-a-token
