### ISSUE TITLE
error reading CA cert file: expected 1 certificate, found 3

### ISSUE THREAD

**Issue by vemireddy-vaibhav** [k3s-io/k3s#7957]
**Environmental Info:**
K3s Version: 
v1.21.5+k3s2

Node(s) CPU architecture, OS, and Version: 
Ubuntu 22.04.2 LTS
Architecture:            x86_64

Cluster Configuration:
Single VM cluster

**Describe the bug:**
K3S Fails to install when using custom CA certificates

**Steps To Reproduce:**
1. Before installing k3s, provide root & intermediate certificates under /var/lib/rancher/k3s/server/tls and run leaf certificate generation script as described [here](https://docs.k3s.io/cli/certificate#:~:text=root%2Dca.key-,If,-you%20want%20to)
2. Run the installer to setup k3s: `curl -sfL https://get.k3s.io | sh - `
3. Installation fails complaining to check status using journalctl

I see the following information the error logs:
```
Jul 12 16:04:37 k3s-staging-uno k3s[22433]: time="2023-07-12T16:04:37.841648988Z" level=info msg="Cluster-Http-Server 2023/07/12 16:04:37 http: TLS handshake error from 127.0.0.1:44438: remote error: tls: bad certificate"
Jul 12 16:04:37 k3s-staging-uno k3s[22433]: time="2023-07-12T16:04:37.853692687Z" level=info msg="Cluster-Http-Server 2023/07/12 16:04:37 http: TLS handshake error from 127.0.0.1:44466: remote error: tls: bad certificate"
Jul 12 16:04:37 k3s-staging-uno k3s[22433]: time="2023-07-12T16:04:37.882258766Z" level=info msg="certificate CN=k3s-staging-uno signed by CN=k3s-server-ca@1689177699: notBefore=2023-07-12 16:01:40 +0000 UTC notAfter=2024-07-11 16:04:37 +0000 UTC"
Jul 12 16:04:37 k3s-staging-uno k3s[22433]: time="2023-07-12T16:04:37.889931842Z" level=info msg="certificate CN=system:node:k3s-staging-uno,O=system:nodes signed by CN=k3s-client-ca@1689177699: notBefore=2023-07-12 16:01:40 +0000 UTC notAfter=2024-07-11 16:04:37 +0000 UTC
Jul 12 16:04:45 k3s-staging-uno k3s[22433]: E0712 16:04:45.475574   22433 controllermanager.go:562] Error starting "csrsigning"
Jul 12 16:04:45 k3s-staging-uno k3s[22433]: F0712 16:04:45.475624   22433 controllermanager.go:223] error starting controllers: failed to start kubernetes.io/kubelet-serving certificate controller: error reading CA cert file "csr-controller::/var/lib/rancher/k3s/server/tls/server-ca.crt::/var/lib/rancher/k3s/server/tls/server-ca.key": expected 1 certificate, found 3
```

Checking the `server-ca.crt` there are 3 pem files. server-ca-cert, my-custom-intermediate-ca-cert, my-custom-root-ca-cert
This is inteneded as it's matching the expected output from cert generation [script](https://github.com/k3s-io/k3s/blob/3eb4e12c3b317a606f79ea2cbd9b7d78beea689b/contrib/util/generate-custom-ca-certs.sh#L147)

But k3s seems to have trouble when there are multiple certificates

**Comment by brandond** [comment]
You are using a very old and unsupported version of k3s. Please use a newer release that includes support for custom CA chains.
