### ISSUE TITLE
[K3s] CIS Benchmark 1.24 requires file permissions to be 600 instead of 644

### ISSUE THREAD

**Issue by andypitcher** [k3s-io/k3s#7975]
This issue is to improve the default file permissions of `K3s` files based on CIS (since 1.24) new requirements.

Here is the list of concerned CIS checks with their concerned files to be set from `644` to `600`. 

- 1.1.13 Ensure that the admin.conf file permissions are set to 600 or more restrictive (Automated)
   File: `/var/lib/rancher/k3s/server/cred/admin.kubeconfig`
- 1.1.15 Ensure that the scheduler.conf file permissions are set to 600 or more restrictive (Automated)
   File: `/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig`
- 1.1.17 Ensure that the controller-manager.conf file permissions are set to 600 or more restrictive (Automated)
   File: `/var/lib/rancher/k3s/server/cred/controller.kubeconfig`
- 1.2.19: Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive (Manual) 
   File: `/var/lib/rancher/k3s/server/tls/*`
- 4.1.3 If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive (Manual) 
   File: `/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig`
- 4.1.5 Ensure that the --kubeconfig kubelet.conf file permissions are set to 600 or more restrictive (Automated) 
   File: `/var/lib/rancher/k3s/agent/kubelet.kubeconfig`
- 4.1.7 Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Manual)
   File: `/var/lib/rancher/k3s/server/tls/server-ca.crt`
- 4.1.9 Ensure that the kubelet --config configuration file has permissions set to 600 or more restrictive (Automated)
   File: `/var/lib/rancher/k3s/agent/kubelet.kubeconfig`

Related issue: https://github.com/rancher/rancher/issues/41131

cc @rayandas

**Comment by dereknola** [comment]
We do not harden k3s automatically. These will need to by hand after install to harden k3s for the cis checks. Only RKE2 offers more default hardening with the `--cis` flag.

**Comment by andypitcher** [comment]
@dereknola With regards to the new permission constraints, we have two options for a given check/file mentioned above:

- Improve K3s file permissions to `600` (preferable).
or
- Deviate from CIS recommendation and keep the hardening guide and profile to `644`.

Could you list the files (mentioned above) that could not be changed to `600`, and would stick with `644` ?

**Comment by dereknola** [comment]
@andypitcher Most of these will be doable, the only one that likely will need to be remain manual would be:

1.2.19: Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive (Manual)
File: /var/lib/rancher/k3s/server/tls/*

The PR linked about will ensure that all relevant `kubeconfig` files have a 600 file perm.

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit be442433
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
 
*Cluster Configuration:*

```
2 servers, 1 agent
Split role setup: 1 etcd-only, 1 cp-only and 1 agent node
```
 
*Config.yaml:*

<details> 

```
# etcd-only S1
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
node-taint:
  - node-role.kubernetes.io/etcd:NoExecute
write-kubeconfig-mode: 644
cluster-init: true

# cp-only S2
disable-etcd: true
node-taint:
  - node-role.kubernetes.io/control-plane:NoSchedule
server: "https://<IP of S1>:6443"
token: "<K10 from S1>"
write-kubeconfig-mode: 644

# agent
server: "https://<IP of S1>:6443"
token: "<K10 from S1>"
```
</details>
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s on server and agent nodes
3. Ensure the cluster is up and running
4. Validate the files below are **NOT** present on the cp-only (as it has the flag `disable-etcd: true`)  server node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
...
-rw-r--r-- 1 root root 1258 Jul 17 21:00 server-client.crt
-rw------- 1 root root  227 Jul 17 21:00 server-client.key
``` 
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5
```
<details>


- Observed the files are present on cp-only node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
total 48
drwx------ 2 root root 4096 Jul 17 20:42 .
drwx------ 4 root root 4096 Jul 17 20:42 ..
-rw-r--r-- 1 root root 1140 Jul 17 20:42 client.crt
-rw------- 1 root root  227 Jul 17 20:42 client.key
-rw------- 1 root root  566 Jul 17 20:21 peer-ca.crt
-rw------- 1 root root  227 Jul 17 20:21 peer-ca.key
-rw-r--r-- 1 root root 1250 Jul 17 20:42 peer-server-client.crt
-rw------- 1 root root  227 Jul 17 20:42 peer-server-client.key
-rw------- 1 root root  570 Jul 17 20:21 server-ca.crt
-rw------- 1 root root  227 Jul 17 20:21 server-ca.key
-rw-r--r-- 1 root root 1258 Jul 17 20:42 server-client.crt
-rw------- 1 root root  227 Jul 17 20:42 server-client.key
```
</details>
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.27.3+k3s-be442433 (be442433)
go version go1.20.5
```
<details>


- Observed the files are **NOT** present on cp-only node
```
$ sudo ls -la /var/lib/rancher/k3s/server/tls/etcd
total 40
drwx------ 2 root root 4096 Jul 17 21:02 .
drwx------ 4 root root 4096 Jul 17 21:02 ..
-rw-r--r-- 1 root root 1140 Jul 17 21:02 client.crt
-rw------- 1 root root  227 Jul 17 21:02 client.key
-rw------- 1 root root  566 Jul 17 21:00 peer-ca.crt
-rw------- 1 root root  227 Jul 17 21:00 peer-ca.key
-rw-r--r-- 1 root root 1250 Jul 17 21:02 peer-server-client.crt
-rw------- 1 root root  227 Jul 17 21:02 peer-server-client.key
-rw------- 1 root root  570 Jul 17 21:00 server-ca.crt
-rw------- 1 root root  227 Jul 17 21:00 server-ca.key
```
</details>

**Comment by andypitcher** [comment]
@dereknola could you confirm that all file locations had their permissions set to 600 ?
My understanding is that any `kubeconfig` in `/var/lib/rancher/k3s/server/cred/` were covered by this [commit](https://github.com/k3s-io/k3s/commit/be442433538a39c0a568516fd39a06e364d5d075), what about `/var/lib/rancher/k3s/agent/` ?

**Comment by dereknola** [comment]
Yes this PR did change the agent file to 600 as well
```
root@degion:/var/lib/rancher/k3s/agent#  stat -c "%a %n" ./*
600 ./client-ca.crt
600 ./client-k3s-controller.crt
600 ./client-k3s-controller.key
600 ./client-kubelet.crt
600 ./client-kubelet.key
600 ./client-kube-proxy.crt
600 ./client-kube-proxy.key
700 ./containerd
700 ./etc
600 ./k3scontroller.kubeconfig
600 ./kubelet.kubeconfig
600 ./kubeproxy.kubeconfig
755 ./pod-manifests
600 ./server-ca.crt
600 ./serving-kubelet.crt
600 ./serving-kubelet.key
```
