### ISSUE TITLE
config.yaml does not work as documented for new installation

### ISSUE THREAD

**Issue by shaman007** [k3s-io/k3s#7995]
Environmental Info:
K3s Version:
k3s version v1.27.3+k3s1

Node(s) CPU architecture, OS, and Version:

Cluster Configuration:
Linux master.k8s.my.lan 6.1.30-rockchip64 #3 SMP PREEMPT Wed May 24 16:32:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Describe the bug:

Installation options provided by config.yaml are not used for a new installation.

Steps To Reproduce:

    Start with k3s not being installed
    Create file /etc/rancher/k3s/config.yaml user-readable with the following content:

```
write-kubeconfig-mode: "0644"
node-name: master.k8s.my.lan
tls-san:
  - " master.k8s.my.lan"
  - "localhost"

cluster-cidr: "10.42.0.0/16"
cluster-cidr-ipv6: "2001:cafe:42:0::/56"

service-cidr: "10.43.0.0/16"
service-cidr-ipv6: "2001:cafe:42:1::/112"

flannel-backend-type: "vxlan"
flannel-ipv6-masq: true

no-deploy:
  - traefik
```
    Install k3s by executing $ curl -sfL https://get.k3s.io | sh -

Expected behavior:

    The file /etc/rancher/k3s/k3s.yaml is created with mode 0644
    The node is named master.k8s.my.lan

Actual behavior:

Neither the custom node name, nor the provided mode, ipv6 to /etc/rancher/k3s/k3s.yaml are set, traefik is enabled

Additional context / logs:

[Documentation](https://rancher.com/docs/k3s/latest/en/installation/install-options/#configuration-file):

    By default, values present in a YAML file located at /etc/rancher/k3s/config.yaml will be used on install.

Later versions:

    Multiple configuration files are supported. By default, configuration files are read from /etc/rancher/k3s/config.yaml and /etc/rancher/k3s/config.yaml.d/*.yaml in alphabetical order.

**Comment by brandond** [comment]
also the no-deploy flag has been removed, you should use `disable` instead. If you'd actually used this config file, you would have seen the following warnings on startup:

```console
WARN[0000] Unknown flag --cluster-cidr-ipv6 found in config.yaml, skipping
WARN[0000] Unknown flag --service-cidr-ipv6 found in config.yaml, skipping
WARN[0000] Unknown flag --flannel-backend-type found in config.yaml, skipping
WARN[0000] Unknown flag --no-deploy found in config.yaml, skipping
WARN[0000] Unknown flag --cluster-cidr-ipv6 found in config.yaml, skipping
WARN[0000] Unknown flag --service-cidr-ipv6 found in config.yaml, skipping
WARN[0000] Unknown flag --flannel-backend-type found in config.yaml, skipping
WARN[0000] Unknown flag --no-deploy found in config.yaml, skipping
```

Please correct your config file contents, and confirm that the config file is in the correct location before K3s is started for the first time.

**Comment by shaman007** [comment]
Please make documentation update, thank you!

**Comment by brandond** [comment]
Can you point to specifically which documentation should be updated? You appear to have just made up several flags, and used outdated versions of others.
