### ISSUE TITLE
bug: Previous pods exist after a reinstallation

### ISSUE THREAD

**Issue by gaocegege** [k3s-io/k3s#8024]
**Version**

```
k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5
```

**Architecture**

```
5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2

x86_64
```

**Describe the bug**

I created some pods in the k3s cluster. Then I uninstall the cluster with `k3s-uninstall.sh`. Then I reinstall it with `curl -sfL https://get.k3s.io | sh -`

I still can get the previous pods. BTW, I am using k3s contained as the runtime. Thus it may not be related to https://github.com/k3s-io/k3s/issues/1995

**To Reproduce**

```bash
curl -sfL https://get.k3s.io | sh -
sudo k3s kubectl run nginx --image=nginx
k3s-uninstall.sh
curl -sfL https://get.k3s.io | sh -
sudo k3s kubectl get pods
// Could get the nginx successfully
```

**Expected behavior**

Previous pods should be deleted.

**Actual behavior**

Previous pods exist.

**Additional context**

**Comment by gaocegege** [comment]
There is no process. I think only the data in the control plane exists. All processes are deleted as expected.

But I also cannot reproduce in a clean VM. I am not sure if it is related to my local environment (with a kind cluster running locally, and a k3s cluster)

**Comment by brandond** [comment]
Possible explanations for this would be:
* The uninstall script failed for some reason, and you didn't notice.
* You were using an external SQL datastore, which isn't cleared by the uninstall script. A subsequent install using the same datastore will still have the old pods.

I'm going to close this out. If you manage to reproduce it, please include the exact steps you ran through, and console logs or screenshots showing the output of the uninstall script.

**Comment by gaocegege** [comment]
I found the dir `/var/lib/rancher/k3s` is not deleted. All the metadata of the pods are there. it works after a manual deletion.

**Comment by brandond** [comment]
Is /var/lib/rancher/ or /var/lib/rancher/k3s a mount point? That's the only reason I can think of that the install script wouldn't delete it. Either way, the install script should have printed an error when not deleting that directory; is it possible you just didn't notice?

**Comment by gaocegege** [comment]
The exit code is 0, and did not see error in the log: https://pastebin.com/LA7UgSPQ

**Comment by gaocegege** [comment]
It is not a mount point. It's a dir in the fs. The UID/GID is root (0).

**Comment by gaocegege** [comment]
BTW, commands like `sh -c 'umount "$0" && rm -rf "$0"' /var/lib/kubelet/pods/e92e523e-111e-4f9a-9f8d-0c376d3375b5/volumes/kubernetes.io~projected/kube-api-access-vfh5m` works well. The file is deleted successfully.

**Comment by brandond** [comment]
> ` + do_unmount_and_remove /var/lib/rancher/k3s`

It reports that it's deleting the directory. Can you show the output of `stat` and `ls` on that directory after you run the uninstall script?

**Comment by gaocegege** [comment]
```
drwxr-xr-x  3 root root 4096  8月  1 16:44 .
drwxr-xr-x 92 root root 4096  8月  1 16:44 ..
drwxr-xr-x  5 root root 4096  8月  1 16:44 k3s
```

It does not matter, I could work around it by deleting it manually. I think it should be related to my local env.
