### ISSUE TITLE
Specifying https-listen-port other than 6443 cause 

### ISSUE THREAD

**Issue by jay0129** [k3s-io/k3s#8030]
**Environmental Info:**
K3s Version: 
k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5

Node(s) CPU architecture, OS, and Version: 
Linux poc001-ais-jp2v-dev 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Tue Feb 21 19:25:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
Specifying https-listen-port other than 6443 cause metric pod failure.
I tries to change port from 6443 to 46443 due to our company vm prohibit exposing 6443.
I tried 46443, 30000 and 36443, but all of these new port failed

**Steps To Reproduce:**
```
cat /etc/rancher/k3s/config.yaml
prefer-bundled-bin: true
resolve-conf: /etc/rancher/k3s/resolve.conf
write-kubeconfig-mode: 644
https-listen-port: 46443
```
```
sudo systemctl daemon-reload
sudo systemctl restart k3s
```

**Expected behavior:**
systemctl restart k3s should be succesfull 

**Actual behavior:**
`systemctl restart k3s` doesn't finish and two pods got the follwoing error respectively:

**Additional context / logs:**
```
$ kubectl logs pod/local-path-provisioner-957fdf8bc-492fc -n kube-system
time="2023-07-22T02:30:18Z" level=fatal msg="Error starting daemon: invalid empty flag helper-pod-file and it also does not exist at ConfigMap kube-system/local-path-config with err: Get \"https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/local-path-config\": dial tcp 10.43.0.1:443: connect: connection refused"
```
```
$ kubectl logs pod/metrics-server-648b5df564-twjv6 -n kube-system
Error: unable to load configmap based request-header-client-ca-file: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 10.43.0.1:443: connect: connection refused
panic: unable to load configmap based request-header-client-ca-file: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 10.43.0.1:443: connect: connection refused
```

**Comment by brandond** [comment]
I can't reproduce this, and neither of the errors you included appear to be related to the port you've changed. It looks more like something is wrong with kube-proxy, as nothing is able to reach the port you've specified. Can you show the output of `kubectl get endpoint kubernetes`, and confirm that whatever other ports you've specified aren't being blocked by iptables or another host-based firewall package?

Here's what I see when setting the port to 60443:
```console
brandond@dev01:~$ kubectl get pod -o wide -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE     IP          NODE           NOMINATED NODE   READINESS GATES
kube-system   local-path-provisioner-957fdf8bc-jsm2q   1/1     Running     0          2m40s   10.42.0.3   k3s-server-1   <none>           <none>
kube-system   coredns-77ccd57875-mvns4                 1/1     Running     0          2m40s   10.42.0.2   k3s-server-1   <none>           <none>
kube-system   svclb-traefik-a097d776-9q82m             2/2     Running     0          2m32s   10.42.0.7   k3s-server-1   <none>           <none>
kube-system   helm-install-traefik-crd-fmpqn           0/1     Completed   0          2m40s   10.42.0.6   k3s-server-1   <none>           <none>
kube-system   helm-install-traefik-4hbmw               0/1     Completed   1          2m40s   10.42.0.5   k3s-server-1   <none>           <none>
kube-system   traefik-64f55bb67d-p9t7m                 1/1     Running     0          2m32s   10.42.0.8   k3s-server-1   <none>           <none>
kube-system   metrics-server-648b5df564-r2fjd          1/1     Running     0          2m40s   10.42.0.4   k3s-server-1   <none>           <none>
brandond@dev01:~$ kubectl get endpoints kubernetes
NAME         ENDPOINTS          AGE
kubernetes   172.17.0.3:60443   2m59s
```

**Comment by jay0129** [comment]
The command `kubectl get endpoints kubernetes` doesn't return anything on the issue case.
I think there is strict policy to our intranet.

**Comment by mjudeikis** [comment]
If somebody digs this out and still wonders what is happening in my  case when you provide external-ip address flag (`curl -sfL https://get.k3s.io | sh -s -  --node-external-ip $(curl icanhazip.com) to be used as node IP you get this:
```
root@mj-test-1:~# kubectl get svc kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   9m2s
root@mj-test-1:~# kubectl get ep kubernetes
NAME         ENDPOINTS            AGE
kubernetes   34.55.204.236:6443   9m6s
```

Now, every pod is trying to call recursively to k8s API using `kubernetes.default.svc.cluster.local` goes via EP and outside. Which might be ok or might not (not the topic here). But now, if your server does not allows 6443 at the firewall level - you will get half of the stuff broken inside the cluster (like the error below) 

 ```
 evel=fatal msg="Error starting daemon: invalid empty flag helper-pod-file and it also does not exist at ConfigMap kube-system/local-path-config with err: Get \"https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/local-path-config\": dial tcp 10.43.0.1:443: i/o timeout"
 ```
