### ISSUE TITLE
After upgrading k3s `Adding GroupVersion` is being repeated in the `k3s.log`

### ISSUE THREAD

**Issue by hickersonj** [k3s-io/k3s#8038]
**Environmental Info:**
K3s Version: 
```bash
k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5
```

Node(s) CPU architecture, OS, and Version: 
`Linux build 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

1 node, 1 server and 1 agent

**Describe the bug:**

I upgraded k3s to `v1.27.3+k3s1` and have noticed a log message regarding `Adding GroupVersion` is repeated in the `k3s.log`.  I do not see this when upgrading using another k8s orchestration manager with `kubernetes v1.27.3`.

**Steps To Reproduce:**

- Upgrade k3s from version `v1.26.2+k3s1` to `v1.27.3+k3s1` 

**Expected behavior:**

The k3s.log should not printout repeated logs.

**Actual behavior:**

The following messages are repeated in the `k3s.log`:
```
I0723 00:08:17.208415   18058 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
I0723 00:08:17.208638   18058 handler.go:232] Adding GroupVersion traefik.containo.us v1alpha1 to ResourceManager
I0723 00:08:17.208933   18058 handler.go:232] Adding GroupVersion migrations.kubevirt.io v1alpha1 to ResourceManager
I0723 00:08:17.209021   18058 handler.go:232] Adding GroupVersion kubevirt.io v1 to ResourceManager
I0723 00:08:17.209151   18058 handler.go:232] Adding GroupVersion kubevirt.io v1alpha3 to ResourceManager
I0723 00:08:17.209358   18058 handler.go:232] Adding GroupVersion instancetype.kubevirt.io v1alpha1 to ResourceManager
I0723 00:08:17.209439   18058 handler.go:232] Adding GroupVersion instancetype.kubevirt.io v1alpha2 to ResourceManager
I0723 00:08:17.209752   18058 handler.go:232] Adding GroupVersion crd.projectcalico.org v1 to ResourceManager
I0723 00:08:17.210052   18058 handler.go:232] Adding GroupVersion traefik.containo.us v1alpha1 to ResourceManager
...
```
**Additional context / logs:**

I tried `minikube version: v1.31.1` which is using `kubernetes v1.27.3` and it is not repeating the line `Adding GroupVersion` in the log.

**Comment by brandond** [comment]
This is coming from the core Kubernetes apiserver, not K3s:
https://github.com/kubernetes/kubernetes/blob/v1.27.3/staging/src/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go#L232

I'm not aware of anything we're doing that would cause custom resource discovery to run or re-run more frequently on K3s than it would on any other Kubernetes distribution.

**Comment by brandond** [comment]
This appears to be coming from the ResourceDiscoveryManager controller, which is gated behind the [`AggregatedDiscoveryEndpoint`](https://github.com/kubernetes/enhancements/issues/3352) feature-gate, which is on by default in Kubernetes 1.27. I am going to close this out, as it appears to be the expected behavior.
