### ISSUE TITLE
K3s-agent "Failed to configure agent: invalid node-ip" when raspberry's expansion network card unregister/unstable and unable to self-heal

### ISSUE THREAD

**Issue by east4ming** [k3s-io/k3s#8059]
**Environmental Info:**
K3s Version: 
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux xxxxxxx-4067 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

Cluster Configuration:
"1 servers(raspberry pi), 30 agents(raspberry pi)". 

**Describe the bug:**
1. k3s-agent config: `--flannel-iface eth1` (eth1 is the raspberry's expansion network card)
2. K3s-agent's raspberry's expansion network card unstable, see /var/log/message(as below), eth1 unregister/register very frequently

```
Jul 25 16:39:36 localhost kernel: [   78.979854] cdc_ether 1-1.2:1.0 eth1: unregister 'cdc_ether' usb-0000:01:00.0-1.2, CDC Ethernet Device
Jul 25 16:39:37 localhost kernel: [   79.871073] cdc_ether 1-1.2:1.0 eth1: register 'cdc_ether' at usb-0000:01:00.0-1.2, CDC Ethernet Device, 58:cf:79:34:ee:8e
```
3. K3s-agent disconnected with k3s-server. Even if eth1 returns to normal, it cannot automatically reconnect, but keeps reporting errors:

```
Jul 25 16:47:01 [localhost](http://localhost/) k3s[1703]: time="2023-07-25T16:47:01.687270395+08:00" level=error msg="Failed to configure agent: invalid node-ip "
```

4. I restart k3s-agent with `sudo systemctl restart k3s-agent.service`, and it returns to normal.

**Steps To Reproduce:**

- Installed K3s with the config (start with systemd):

```bash
/usr/local/bin/k3s agent --data-dir /var/lib/rancher/k3s --flannel-iface eth1
```

- Make  K3s-agent's raspberry's expansion network card unstable
- K3s-agent disconnected with k3s-server. Even if eth1 returns to normal, it cannot automatically reconnect

**Expected behavior:**

Because it is an edge device, our manual intervention is limited. We hope that after the network card returns to normal, k3s-agent can automatically return to normal without manual intervention.

**Actual behavior:**

 I restart k3s-agent with `sudo systemctl restart k3s-agent.service`

**Additional context / logs:**
```
...
Jul 25 16:47:01 [localhost](http://localhost/) k3s[1703]: time="2023-07-25T16:47:01.687270395+08:00" level=error msg="Failed to configure agent: invalid node-ip "
...
```

**Comment by manuelbuil** [comment]
Thanks for reporting this. You are using a pretty old k3s version and the code handling that node-ip and flannel-iface part changed, could you use a newer version and try again please?

**Comment by manuelbuil** [comment]
I was trying on a newer k3s version `1.27.3`. Deployed using `--flannel-iface eth2` in a node where eth2 does not exist. The log I got was:
```
level=warning msg="unable to get global unicast ip from interface name: route ip+net: no such network interface"
level=fatal msg="invalid node-ip: invalid ip format ''"
```
Then created a dummy eth2 and without restarting k3s, the log changed to:
```
Jul 27 17:58:23 mbuil-vm0 k3s[10782]: time="2023-07-27T17:58:23Z" level=warning msg="unable to get global unicast ip from interface name: the interface eth2 is not up"
Jul 27 17:58:23 mbuil-vm0 k3s[10782]: time="2023-07-27T17:58:23Z" level=fatal msg="invalid node-ip: invalid ip format ''"
I set the interface up and put an IP address to it and k3s was correctly running

**Comment by brandond** [comment]
Kubernetes (the kubelet in particular) does not deal well with IPs changing and interfaces coming and going while it is up. I would expect to have to restart K3s after an event that adds/removes interfaces or changes the interface IP, even if the resulting state is the same afterwards.
