### ISSUE TITLE
Is it possible k3s be a cncf project? for IOT and embed devices .

### ISSUE THREAD

**Issue by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [k3s-io/k3s#806]
Is it possible k3s be a cncf project? for IOT and embed devices .
The original kubernetes seems large and not easy to deploy with low memory/cpu devices. 
but the k3s seems better choice.

**Comment by caniszczyk** [comment]
k3s is a CNCF project now, you can track the effort here: https://github.com/cncf/toc/issues/513#issue-682049622

**Comment by cjellick** [comment]
going to close this

**Comment by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [comment]
Whoops, you guys did really good job.
Time goes very fast. 
Congratulations.
