### ISSUE TITLE
updating k3s on Fedora CoreOS fails due to an already installed k3s-selinux

### ISSUE THREAD

**Issue by paolofacchinetti** [k3s-io/k3s#8078]
**Environmental Info:**
K3s Version: 
v1.27.3+k3s1 (fe9604ca)

Node(s) CPU architecture, OS, and Version: 
Linux x86_64 Fedora CoreOS 38.20230709.3.0

Cluster Configuration:
1 server

**Describe the bug:**
After the first installation of k3s through the install script, re-running the install script produces the following error:
`error: Package/capability 'k3s-selinux' is already requested`

**Steps To Reproduce:**
- Installed K3s through `curl -sfL https://get.k3s.io | sh -`
- rebooted the system (due to [how fedora CoreOS works](https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/))
- ran once again the installation script of step 1.
- the script errors out

**Expected behavior:**
the installation script installs a new version of k3s if it's available. If not, it will reinstall the current version.

**Actual behavior:**
the installation script errors out.

**Additional context / logs:**
this behaviour could be avoided by using the `--idempotent` flag to the `rpm-ostree install` command used to install the `k3s-selinux` package.

From what I've seen by looking into k3s docs and the install script, it seems like Fedora CoreOS is a supported OS for k3s. I'm not sure how this issue hasn't popped up earlier.

**Comment by rancher-max** [comment]
This was tested as part of the development process since the install script goes live when we merge. This is resolved and should be working now and is available via get.k3s.io. Thank you for submitting the issue!
