### ISSUE TITLE
Add Go coverage reporting to all E2E tests

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#8091]
**Is your feature request related to a problem? Please describe.**

We currently have go coverage reporting on only a handful of E2E tests, making our coverage metrics incomplete.

**Describe the solution you'd like**

Add go coverage reporting to all E2E tests
**Describe alternatives you've considered**

**Additional context**

**Comment by cwayne18** [comment]
I feel like we can just close this, thoughts @rancher-max
