### ISSUE TITLE
Internal IPv4 to IPv6 mapping results in wrong IPv6 when using Port information

### ISSUE THREAD

**Issue by Reda1000** [k3s-io/k3s#811]
When starting "k3s agent" the given master-server information seems to be altered to an possibly available IPv6 adress when accessing load balancing functionality.

![grafik](https://user-images.githubusercontent.com/14124903/64907363-a4b07180-d6f1-11e9-8701-bec046caf597.png)

As you can see above the server url is being changed to "2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443" where the last portion is the port:
`
    INFO[2019-09-14T11:38:25.682935646+01:00] Updating load balancer server addresses -> [2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443 192.168.178.10:6443] `

Further the IPv6 adress is being used contacting a proxy with wss://2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443 a valid IPv6-Origin in my opinion should be wss://[2a02:8108:1240:2b13:e292:a303:bc11:d1d4]:6443
`
    INFO[2019-09-14T11:38:25.684216116+01:00] Connecting to proxy                           url="wss://2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443/v1-k3s/connect"`

Using the IPv6 adress will then result in this error:
`
    ERRO[2019-09-14T11:38:25.684549502+01:00] Failed to connect to proxy                    error="dial tcp: address 2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443: too many colons in address"`

I followed this article and stumbled on "Join a worker":
https://blog.alexellis.io/test-drive-k3s-on-raspberry-pi/

I expect to not getting the above mentioned error shown again and the load balancer being able to be connected by "k3s server"-command.

**Comment by galal-hussein** [comment]
According to the code, k3s will update the load balancer set of addresses according to the kubernetes service endpoints in the default namespaces https://github.com/rancher/k3s/blob/master/pkg/agent/tunnel/tunnel.go#L74-L80

can you get more information regarding your setup:
- is the setup in HA mode?
- what is the output of the following command:
```
kubectl get endpoints kubernetes 
```
cc @erikwilson

**Comment by Reda1000** [comment]
Thanks for getting back to me. I switched off IPv6 to get the Nodes successfully connected with Master-Node 3 days ago. Couple of hours ago I switched on IPv6 again on my Raspberry PI Node 1 (K3S-Master). 
I received this by `kubectl get endpoints kubernete` short after switching IPv6 on:
![grafik](https://user-images.githubusercontent.com/14124903/65185730-71ab0c80-da68-11e9-82e6-f8b98e155ad8.png)

After work I came back and reset the network setting of PI Node 1 (K3S-Master) (replugged network cable) aftwards received this:
![grafik](https://user-images.githubusercontent.com/14124903/65186113-3bba5800-da69-11e9-8283-7dc9a8be6930.png)

I now tried to check if PI Node 2 (K3S-Worker) can get through with IPv4 but there was this error:
![grafik](https://user-images.githubusercontent.com/14124903/65185562-1c6efb00-da68-11e9-9442-9d0458a83914.png)
It makes sense as the PI Node 1 (K3S-Master) is only available through IPv6 now.

I then checked with using IPv6 Address of PI Node 1 (K3S Master) in --server-value:
![grafik](https://user-images.githubusercontent.com/14124903/65185416-cd28ca80-da67-11e9-88ae-c48242c45224.png)
So i guess it is still an issue with IPv6 routing.

Regarding HA mode: I am new in training my DevOps skills comming from Softwaredevelopment. How could I determine HA mode? Currently the cluster is without any services / pods so I could even destroy it trying risky things.

**Comment by ikaruswill** [comment]
Hey, I'd just like to chime in on this issue. I am currently facing this as well, but since then I've switched the entire network to ipv4 only and it works like a charm.

One observation I'd like to point out is that after installing via:
```
curl -sfL https://get.k3s.io | sh - --no-deploy servicelb --no-deploy traefik
```
On the first startup, `journalctl -u k3s.service` on the master shows that the the `kube-apiserver` detects the ip address as the ipv4 address e.g. `192.168.1.11`. 

On rebooting the master, the subsequent startups detect the ipv6 address e,g. `2a02:8108:1240:2b13:e292:a303:bc11:d1d4:6443`

**Comment by kamilgregorczyk** [comment]
@Reda1000 How have you turned off ipv6 completely on raspberry pis? 

I'm having the same problem where everything started working in ipv4 but does not on ipv6. All the TCP queries with ipv6 IPs are not wrapped with `[...]` which causes system to fail. I turned off ipv6 by adding `net.ipv6.conf.all.disable_ipv6 = 1` to `sysctl` but with that i can't ssh to machines 

https://github.com/rancher/k3s/issues/1191

**Comment by Reda1000** [comment]
@kamilgregorczyk I did not particularly switch off IPv6 on Raspi - I told the router to not assign dynamic IPv6 addresses.

Currently I am accessing my cluster through IPv4 addresses that are dynamically assigned by my router. Would this be an option to you?

**Comment by kamilgregorczyk** [comment]
@Reda1000 thanks, will try to do it
