### ISSUE TITLE
Use go tooling to query module versions

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8139]
We should use `go list -m` instead of grep to look up versions.

This will consistently show the actual module that we're using, instead of having different regexes that may or may not find the correct replacement version.

We've tinkered with this occasionally, most recently in https://github.com/k3s-io/k3s/commit/f8b661d590ecd1ed2ed04b3c51ff5e6d67cb092b#diff-d9002f82f23cc9b3c1545ec7d5ddfc3911aec8ba24d4e3d21c73f40355da2a16R34 but this makes things consistent across the board.

**Comment by VestigeJ** [comment]
Verified in the scripts directory of the repository
