### ISSUE TITLE
WSL2 -> Ubuntu -> K3S cannot pull images after changing network

### ISSUE THREAD

**Issue by Chris2301** [k3s-io/k3s#8162]
Hi, 

I am using K3s to startup company pod via a VPN and since I have been to the office, where it also worked, pod wont start anymore because they cannot pull the images. 

`Failed to pull image "location/name:version": rpc error: code = Unknown desc = failed to pull and unpack image "location/name:version": failed to resolve reference "location/name:version": failed to do request: Head "location/name:version": dial tcp: lookup location: no such host`

I started a dummy pod and curl to the url and this works....

**Environment is as the title describes;**
Windows with a VPN running, WSL2 with K3s and docker installed (no docker desktop)

**What I have tried so far;**

- Restarting K3s
- kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml and debugged seeing no changes
- restart pod coredns
- ip route showing no duplicate routes
- docker pull image works
- Curl from inside a dummy container to the specific image works also

**Kubectl versions**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T09:46:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

**resolv.conf with interesting WSL text**
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 173.24.145.1
```

**More attempts that failed:**

- Tried this https://github.com/docker/for-linux/issues/1406#issuecomment-1183487816 (updating iptables to legacy mode), since I read that k3s uses the installed docker to pull images. I restarted docker, not k3s.

**Comment by cwayne18** [comment]
WSL or WSL2?

**Comment by Chris2301** [comment]
> WSL or WSL2?

Updated

**Comment by cwayne18** [comment]
Thanks, we can take a look but FWIW we don't test/support wsl at the moment so there's not a ton of expertise on the team. That said we'll certainly see what we can do!

**Comment by Chris2301** [comment]
Cheers @cwayne18 , I also keep updating my attempts in the topic start

**Comment by Chris2301** [comment]
Solved it by adding the ip + hostname to /etc/hosts on my ubuntu system. Probably a workaround, but it works. Still no clue why this can go wrong after switching networks.
