### ISSUE TITLE
DNS Resolution With An Authoritative Nameserver

### ISSUE THREAD

**Issue by TheDarkula** [k3s-io/k3s#8176]
**Environmental Info:**
K3s Version: v1.27.3+k3s1 (fe9604ca)

Node(s) CPU architecture, OS, and Version: 6.4.7-zen1-1-zen

Cluster Configuration: Single master/node

**Describe the bug:**
This is a rather odd bug that I am trying to figure out.
I am running an authoritative DNS server (PowerDNS) in k3s.

I opened an issue [over there](https://github.com/PowerDNS/pdns/issues/13085) as well.

Somehow, wires are not touching how they are supposed to, and I am getting this error:
```
	Jul 31 04:38:04 Received NOTIFY for example.com from 10.42.0.1 for which we are not authoritative, trying supermaster
	Jul 31 04:38:08 Error resolving SOA or NS for example.com at: 10.42.0.1: Timeout waiting for answer from 10.42.0.1
```

Effectively, the service is running a `dig SOA example.com`, but it seems as though k3s or some iptables rule may be getting in the way.

I did some more investigation, and setting `externalTrafficPolicy: Local` on the service reveals that it is trying to hit a local router at `192.168.1.1`.

The confusing thing is, `/etc/resolv.conf` on the k3s host is manually set to:
```
namesever 9.9.9.9
```

**Steps To Reproduce:**

- Installed K3s: Installed via the k3s-bin package in the AUR.

**Expected behavior:**
DNS to be handled via the specified nameservers.

**Actual behavior:**
DNS is attempted to be resolved by the local router.

**Comment by cwayne18** [comment]
Can you reproduce this when installing via the official install script? The k3s-bin package is not packaged/maintained by us as an upstream so we'd like to rule out any patches/differences from that package

**Comment by TheDarkula** [comment]
@cwayne18 Thank you for the response!
Not easily, given that I already have records and certificates in play with these DNS servers.

I will say that the AUR package does not patch the binary in any way.
You can have a look [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=k3s-bin).
