### ISSUE TITLE
nor working for 'curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -'

### ISSUE THREAD

**Issue by baymax55** [k3s-io/k3s#8205]
I just install k8s following 'https://docs.k3s.io/zh/quick-start', but when I execute this script is not working.

the script is below:
'curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -'

**Comment by brandond** [comment]
Please post on the forums at rancher.cn. The Chinese mirrors and infrastructure are not under our control.
