### ISSUE TITLE
Installation scripts can't handle `VERSION_ID` on Kylin V10 OS

### ISSUE THREAD

**Issue by ErikJiang** [k3s-io/k3s#8206]
**Environmental Info:**
K3s Version: v1.27.4+k3s1

Node(s) CPU architecture, OS, and Version: 

```
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

[root@localhost ~]# cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"

```

Cluster Configuration: 1 server

**Describe the bug:**

I'm installing k3s on [kylin v10](https://www.kylinos.cn/scheme/server/1.html), and the logging error is `main: line 569: [: V10: integer expression expected` because the `VERSION_ID` variable in kylin v10 is a string `V10`, not an integer number.

**Steps To Reproduce:**

Executing the k3s install script on the Kylin V10 OS reproduces the problem.

**Expected behavior:**

The value of the `VERSION_ID` variable on the Kylin OS is handled correctly.

**Actual behavior:**

Script reporting error: `V10: Integer expression expected`

**Additional context / logs:**

``` bash
[root@localhost ~]# curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.27.4+k3s1 as release
[INFO]  Downloading hash rancher-mirror.rancher.cn/k3s/v1.27.4-k3s1/sha256sum-arm64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
main: line 569: [: V10: integer expression expected
[INFO]  Finding available k3s-selinux versions
[ERROR]  Failed to apply container_runtime_exec_t to /usr/local/bin/k3s, please install:
    dnf install -y container-selinux
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/9/noarch/
```

**Comment by mdrahman-suse** [comment]
@ErikJiang Can you please validate the fix as we dont officially support this OS and the fix is available to test?

**Comment by ShylajaDevadiga** [comment]
Closing this issue as completed as no testing is required from QA.
