### ISSUE TITLE
About the problem that the number of concurrent connections between k3s and external mysql database is too high

### ISSUE THREAD

**Issue by 983183947** [k3s-io/k3s#8216]
I have k3s+rancher with 2 nodes, using an external mysql database. It is fine in normal use, but once I access a service deployed on it, k3s will have a large number of mysql query connections, resulting in my service and rancher being unable to access.
   This k3s+rancher cluster has been running for almost half a year, and this happened suddenly yesterday.

![image](https://github.com/k3s-io/k3s/assets/25240344/a7991263-d9c0-4702-b3c0-196e302e7ea5)

**Comment by brandond** [comment]
Please fill out the issue template - what version of k3s are you using? Are both nodes servers? Do you have any datastore latency warnings in your server logs?
