### ISSUE TITLE
`--disable-helm-controller` also disables Traefik

### ISSUE THREAD

**Issue by comminutus** [k3s-io/k3s#8228]
**Environmental Info:**
K3s Version: 
1.27.4+k3s1

Node(s) CPU architecture, OS, and Version: 
```
Linux k3s-server-1 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
Linux k3s-server-2 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
Linux k3s-server-3 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
Linux k3s-agent-1 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
Linux k3s-agent-2 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
Linux k3s-agent-3 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux
```
(all using Fedora CoreOS)

Cluster Configuration:
3 servers, 3 agents

**Describe the bug:**
Using `--disable-helm-controller` on k3s server deployments also disables Traefik.  This doesn't seem to be documented anywhere.

**Steps To Reproduce:**
1. Bootstrap an initial k3s server using `curl -sfL https://get.k3s.io | K3S_TOKEN=yourtoken sh -s server --cluster-init --disable-helm-controller
2. After server comes online, observe no traefik-controller in the `kube-system` namespace with: `kubectl get pods -n kube-system`
 
**Expected behavior:**
Disabling the Helm controller shouldn't disable Traefik, or it should be well documented that using this flag also disables Traefik.  It should be possible to still have Traefik installed via manifests instead of relying on the Helm chart.

**Actual behavior:**
Traefik is disabled along with the Helm controller.

The reason I disabled the Helm controller is that in some circumstances it can conflict with the Flux CD Helm controller which I rely upon.

**Comment by brandond** [comment]
> 

> in some circumstances it can conflict with the Flux CD Helm controller which I rely upon.
