### ISSUE TITLE
Allow to pass additional parameters to tailscale up

### ISSUE THREAD

**Issue by unixfox** [k3s-io/k3s#8245]
**Is your feature request related to a problem? Please describe.**
On my k3s nodes I do not want to have the ["MagicDNS"](https://tailscale.com/kb/1081/magicdns/) enabled because I want to use the local DNS. In order to do that, I usually do `tailscale up --accept-dns=false`

But in this case k3s will reset my setting at every restart: https://github.com/k3s-io/k3s/blob/ced330c66a26a21a6f9fcbb0596d8ac7837432f4/pkg/vpn/vpn.go#L51 so this doesn't work.

**Describe the solution you'd like**
I would like to be able to pass additional parameters for the `tailscale up` that k3s executes.

Example:
```
--vpn-auth name=tailscale,joinKey=tskey-auth-kT9X6U1CNTRL-YaTkku6rpUHSaKeiav6PUHZNE2Rqcowud,params=accept-dns=false
```

**Describe alternatives you've considered**

**Additional context**
Thank you in advance for considering to my feature request.

**Comment by manuelbuil** [comment]
What about something like: 
`--vpn-auth name=tailscale,joinKey=$KEY,exta-args=--accept-dns=false`
where everything that comes after "extra-args" is blindly applied to `tailscale up`?

I want to avoid having to check each and every parameter there because that will couple us tightly with tailscale releases since API changes will break us

**Comment by unixfox** [comment]
I'm fine with whatever implementation.

The only thing to note is that it shouldn't be too difficult in case you need to also pass quotes inside the `exta-args`, for example:
```
--vpn-auth name=tailscale,joinKey=$KEY,exta-args="--accept-dns=false --acustomparam="the-value""
```

**Comment by brandond** [comment]
> shouldn't be too difficult in case you need to also pass quotes

good callout

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id 00fc5a23ecd5f2c4df41f41062d4ae93ffbc0d1b
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04


*Cluster Configuration:*
Single node

*Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
debug: true
write-kubeconfig-mode: 644
token: secret
cluster-init: true
vpn-auth: "name=tailscale,joinKey=REDACTED,extraArgs=--accept-dns=false"
cluster-cidr: 10.50.0.0/16
```
 ## Steps to reproduce the issue  and validate the fix
1. Install tailscale
2. Copy config.yaml
3. Install k3s

## Validation Results:
**From the logs we see the extraArg --accept-dns is set to false**
```
$ journalctl |grep tailscale|grep accept-dns
Sep 29 22:10:26 ip-172-31-0-119 k3s[17074]: time="2023-09-29T22:10:26Z" level=debug msg="Flags passed to tailscale up: [up --authkey REDACTED --timeout=30s --reset --accept-dns=false]"
```
```
$ ip a|grep tailscale
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    inet 100.89.127.57/32 scope global tailscale0
```
extraArg passed persisted across restart of the service
```
$ sudo systemctl restart k3s
$ journalctl |grep tailscale|grep accept-dns
Sep 29 22:10:26 ip-172-31-0-119 k3s[17074]: time="2023-09-29T22:10:26Z" level=debug msg="Flags passed to tailscale up: [up --authkey REDACTED --timeout=30s --reset --accept-dns=false]"
Sep 29 22:18:05 ip-172-31-0-119 k3s[19541]: time="2023-09-29T22:18:05Z" level=debug msg="Flags passed to tailscale up: [up --authkey REDACTED --timeout=30s --reset --accept-dns=false]"
```
