### ISSUE TITLE
CA cert validation failure on additional server nodes prevents joining without explicitly configuring node-external-ip

### ISSUE THREAD

**Issue by VestigeJ** [k3s-io/k3s#8247]
**Environmental Info:**
K3s Version: 

Present on all current RCs 

Node(s) CPU architecture, OS, and Version: 

Linux ip-172-31-31-2 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Able to reproduce with two server nodes

**Describe the bug:**

Unless the node-external-ip is configured additional server nodes cannot verify the certificate for the primary server. Agents are able to join just fine. 

```
level=fatal msg="starting kubernetes: preparing server: CA cert validation failed: Get \"https://3.3.2.147:6443/cacerts\": tls: failed to verify certificate: x509: certificate is valid for 10.43.0.1, 127.0.0.1, 172.31.20.8, ::1, not 3.3.2.147"
```

**Steps To Reproduce:**

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.24.17-rc1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ watch kubectl get no,po -A
``` 
setup primary server and wait to observe it's ready to subsequent server node to join the cluster. 

Primary server config

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
protect-kernel-defaults: true
cluster-init: true
```

**Expected behavior:**

I expected additional server nodes to be able to join the primary server node without issue. 

**Actual behavior:**

Unless the node-external-ip address is set that will be targeted for joining additional server nodes the x509 certificate will fail to be verified.

If you simply add the node-external-ip: public_joining_ip and sudo systemctl restart k3s then any waiting nodes will correctly join the cluster afterwards. 

**Additional context / logs:**

**Comment by brandond** [comment]
I take it you're specifying the external IP or hostname in the --server address, but haven't actually configured that address on the server? This would be caused by the change to no longer add random unknown IPs and names to the cert in https://github.com/k3s-io/k3s/pull/8085

I get that this could be considered a regression in that it broke something that previously worked, but in this case it is necessary for security purposes. We could perhaps have some discussion about a way to relax the fix a bit. I personally would lean towards making the new behavior optional and off by default on existing minors, and on by default for 1.28+?

cc @Chris Wayne @macedogm

**Comment by VestigeJ** [comment]
##Environment Details
VERSION=v1.28.0-rc1+k3s1
VERSION=v1.28.1-rc1+k3s1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

ami-0bbc06589f2e4f4f2

Linux 5.14.21-150500.53-default x86_64 GNU/Linux 

PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
 
*Cluster Configuration:*

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-12-31-31-12     Ready    control-plane,etcd,master   2m18s   v1.28.1-rc1+k3s1
node/ip-12-31-31-7      Ready    control-plane,etcd,master   12m     v1.28.1-rc1+k3s1
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
protect-kernel-defaults: true
cluster-init: true
node-external-ip: 3.3.6.9
```


```
server: https://3.3.6.9:6443
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
protect-kernel-defaults: true
```

<details><summmary><h4>Reproduction</h4></summary>

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.28.0-rc1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ // on second node join primary node server - observe the failure
```

**Results:**

CA cert validation failed

</details>

<details><summmary><h4>Validation</h4></summary>

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.28.1-rc1+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ // on second node join primary node server - observe the cluster starts as expected
```
 
**Results:** 

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-12-31-31-12     Ready    control-plane,etcd,master   2m18s   v1.28.1-rc1+k3s1
node/ip-12-31-31-7      Ready    control-plane,etcd,master   12m     v1.28.1-rc1+k3s1
```

</details>  

Primary server omitted secondary server omitted ✅
Primary server true secondary server true ✅
