### ISSUE TITLE
Containerd logging not using logrus

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#8251]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

As explained in https://github.com/k3s-io/k3s/pull/8250 because we are not using logrus, when containerd fails to start in rke2-windows, we get no log of what is going on. We are using a hook in rke2-windows that binds logrus to EWT and any message not using logrus, gets dropped

**Steps To Reproduce:**

- Installed K3s: 
It needs rke2 to reproduce the error

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
Performed basic cluster creation tests in rke2 with Windows and added comment here: https://github.com/rancher/rke2/issues/4693#issuecomment-1756274653
