### ISSUE TITLE
kube-bench for k3s

### ISSUE THREAD

**Issue by gpkarnam** [k3s-io/k3s#826]
Hi,
I would like to use kube-bench to CIS validation on K3S.
But unfortunately get the error "need kubelet executable but none of the candidates are running" when I run the https://github.com/aquasecurity/kube-bench/blob/master/job.yaml

The volume paths referred in this yaml refer to kubeadm kubernetes.
Can we have the equivalent volume/hostpaths for k3s that can be used for kube-bench validation please?

gz#13301

**Comment by warmchang** [comment]
You need to make customized changes for the K3S project.

There are some example for redhat openshift (ocp-3.11 or ocp-3.10) in the "https://github.com/aquasecurity/kube-bench/tree/master/cfg" folder.

FYI: https://github.com/aquasecurity/kube-bench/blob/master/docs/README.md#configuration-and-variables

**Comment by jessequinn** [comment]
@gpkarnam do you have a configuration you can share?

**Comment by TARI0510** [comment]
@gpkarnam @jessequinn Hello, this PR https://github.com/aquasecurity/kube-bench/pull/1261 may help you~

**Comment by caroline-suse-rancher** [comment]
Closing due to age, and a potential resolution in kube-bench. Please make a new issue if your problem persists.
