### ISSUE TITLE
Kubelet args from config are not applied. 

### ISSUE THREAD

**Issue by clbx** [k3s-io/k3s#8266]
**Environmental Info:**
K3s Version: 
```
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6
```

Node(s) CPU architecture, OS, and Version: ``Linux hostname-redacted 4.18.0-477.15.1.el8_8.x86_64 #1 SMP Fri Jun 2 08:27:19 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux``

Cluster Configuration: Single node. 

**Describe the bug:**

Values set for ``kubelet-arg`` in ``/etc/rancher/k3s/config.yaml`` do not get applied when the kubelet is started

I have the following ``config.yaml``
```
kublet-arg: "protectKernelDefaults=true"
```

When k3s is started the first line of the k3s process is:

```
k3s[2872823]: time="2023-08-29T20:21:22Z" level=warning msg="Unknown flag --kublet-arg found in config.yaml, skipping\n"
```

Despite that being a valid flag as documented [here](https://docs.k3s.io/cli/server#customized-flags-for-kubernetes-processes)

And does not show up in the kubelet argument list on start:
```
k3s[2872823]: time="2023-08-29T20:21:41Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=hostname-redacted --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
```

**Steps To Reproduce:**

- Installed K3s Using Airgap Method
- Created /etc/rancher/k3s/config.yaml
- Added the config to that file
- Restarted k3s.service

**Expected behavior:**

Kubelet arguments are applied

**Actual behavior:**

Kubelet arguments are not applied. 

**Additional context / logs:**

**Comment by brandond** [comment]
>I have the following config.yaml
> kublet-arg: "protectKernelDefaults=true"

That's not how you spell "kubelet"

**Comment by clbx** [comment]
🙃, sorry for wasting your time. I should get a rubber duck.

**Comment by cwayne18** [comment]
Happens to all of us 🙂
