### ISSUE TITLE
runc: unable to start container (broken pipe)

### ISSUE THREAD

**Issue by shanduur-dell** [k3s-io/k3s#8277]
**Environmental Info:**
K3s Version: 

```
$ k3s -v
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6
```

Node(s) CPU architecture, OS, and Version: 

```
$  uname -a
Linux VM 5.14.0-284.25.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 2 14:53:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

Single node deployment.

**Describe the bug:**

The following error keeps popping. It affects multiple containers.

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown
```

**Steps To Reproduce:**

- Deployed Rocky 9.2 with disabled `firewalld`.
- Installed K3s via https://get.k3s.io/
-  Installed Jaeger operator (also happens with multiple other containers):

```
kubectl apply -f "https://github.com/cert-manager/cert-manager/releases/download/v1.44.0/cert-manager.yaml"
```

**Expected behavior:**

Running container.

**Actual behavior:**

Pods are not being created.

**Additional context / logs:**

```
Events:
  Type     Reason          Age                    From     Message
  ----     ------          ----                   ----     -------
  Warning  FailedMount     33m (x3 over 33m)      kubelet  MountVolume.SetUp failed for volume "cert" : object "observability"/"jaeger-operator-service-cert" not registered
  Warning  FailedMount     33m (x3 over 33m)      kubelet  MountVolume.SetUp failed for volume "kube-api-access-dhjgv" : object "observability"/"kube-root-ca.crt" not registered
  Normal   SandboxChanged  33m                    kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Started         33m                    kubelet  Started container jaeger-operator
  Normal   Pulled          33m                    kubelet  Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0" already present on machine
  Normal   Created         33m                    kubelet  Created container kube-rbac-proxy
  Normal   Started         33m                    kubelet  Started container kube-rbac-proxy
  Warning  Unhealthy       33m                    kubelet  Liveness probe failed: Get "http://10.42.0.113:8081/healthz": dial tcp 10.42.0.113:8081: connect: connection refused
  Warning  Unhealthy       33m (x4 over 33m)      kubelet  Readiness probe failed: Get "http://10.42.0.113:8081/readyz": dial tcp 10.42.0.113:8081: connect: connection refused
  Normal   Pulled          33m (x2 over 33m)      kubelet  Container image "quay.io/jaegertracing/jaeger-operator:1.44.0" already present on machine
  Normal   Created         33m (x2 over 33m)      kubelet  Created container jaeger-operator
  Warning  Failed          33m                    kubelet  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown
  Warning  BackOff         13m (x100 over 33m)    kubelet  Back-off restarting failed container jaeger-operator in pod jaeger-operator-74d786694f-kksmn_observability(0e91ebea-3dcf-4eba-a7bc-40e85e23a294)
  Warning  FailedMount     8m43s                  kubelet  MountVolume.SetUp failed for volume "cert" : object "observability"/"jaeger-operator-service-cert" not registered
  Warning  FailedMount     8m42s                  kubelet  MountVolume.SetUp failed for volume "kube-api-access-dhjgv" : object "observability"/"kube-root-ca.crt" not registered
  Normal   SandboxChanged  8m42s                  kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Started         8m39s                  kubelet  Started container jaeger-operator
  Normal   Pulled          8m39s                  kubelet  Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0" already present on machine
  Normal   Created         8m38s                  kubelet  Created container kube-rbac-proxy
  Normal   Started         8m38s                  kubelet  Started container kube-rbac-proxy
  Warning  Unhealthy       8m13s (x4 over 8m33s)  kubelet  Readiness probe failed: Get "http://10.42.0.160:8081/readyz": dial tcp 10.42.0.160:8081: connect: connection refused
  Normal   Pulled          7m34s (x3 over 8m39s)  kubelet  Container image "quay.io/jaegertracing/jaeger-operator:1.44.0" already present on machine
  Normal   Created         7m34s (x3 over 8m39s)  kubelet  Created container jaeger-operator
  Warning  Failed          7m33s (x2 over 7m54s)  kubelet  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown
  Warning  BackOff         3m37s (x27 over 8m8s)  kubelet  Back-off restarting failed container jaeger-operator in pod jaeger-operator-74d786694f-kksmn_observability(0e91ebea-3dcf-4eba-a7bc-40e85e23a294)
```

**Comment by brandond** [comment]
Is this node hardened in any way? Selinux, STIG, etc? Do you see any other errors or warnings in the system journal?

fwiw this message is coming from runc when attempting to do a very basic data copy operation, which reinforces my suspicion that something on your host is blocking the write.

https://github.com/opencontainers/runc/blob/v1.1.7/libcontainer/process_linux.go#L419-L421

**Comment by shanduur-dell** [comment]
I disabled the SELinux, no STIG or anything else. There is Trellix installed, I think it is interfering with the K3s, but I can't find ANYTHING in logs (`journalctl -xe` show nothing except k3s unit logs and systems logs).

**Comment by MohamedShaj** [comment]
> Is this node hardened in any way? Selinux, STIG, etc? Do you see any other errors or warnings in the system journal?
> 
> fwiw this message is coming from runc when attempting to do a very basic data copy operation, which reinforces my suspicion that something on your host is blocking the write.
> 
> https://github.com/opencontainers/runc/blob/v1.1.7/libcontainer/process_linux.go#L419-L421

`Warning
FailedCreatePodSandBox
7m46s
kubelet
Failed to create pod sandbox: rpe error: code = Unknown desc = failed to create containerd task: failed to c
reate
shim task: OCI runtime create failed:
runc create
failed: unable to start
container process: error during container init: error mounting "/application-volume/k3s/agent/containerd/i
o.containerd.grpc.vl.cri/sandboxes/1f7451cf2da567f0625c737cbd2fb40e9b6810f1516eb390cccfbac9c6eb8897/resolv.conf" to rootfs at "/etc/resolv.conf": open /run/k3s/containerd/io.containerd.r
untime.v2.task/k8s.io/1f7451cf2da567f0625c737cbd2fb409b6810f1516eb390cccfbac9c6eb8897/rootfs/etc/resolv.conf: operation not permitted: unknown
Warning
FailedCreatePodSandBox
7m33s
kubelet
Failed to create pod sandbox: Ipc error: code = Unknown desc = failed to create containerd task: failed to c
reate shim task: OCI runtime create failed:
runc create
failed: unable to start container process: error during container init: error mounting "/application-volume/k3s/agent/containerd/i
o.containerd.grpc.vl.cri/sandboxes/aTcf501ea2247e9376015b7ea421091364d8c4558ae79bc0db76cf41621fb0bl/resolv.conf" to rootfs at "/etc/resolv.conf"; open /run/k3s/containerd/io.containerd.r
untime.v2.task/k8s.io/a7cf501ea2247e9376015b7ea421091364d8c4558a79bC0db76cf41621fb0bl/rootfs/etc/resolv.conf: operation not permitted: unknown
Warning
FailedCreatePodSandBox
3m41s (x17 over
7ml9s)
kubelet
(combined from similar events): Failed to create pod sandbox: Ipc error: code = Unknown desc = failed to cre
ate containerd task: failed to create shim task: OCI runtime
create failed: runc create failed: unable to start container process: error during container init: error mounting
"/applicati
on-volume/k3s/agent/containerd/jo.containerd.grpc.vl.cri/sandboxes/2eebd341a98802537e8397844842bcf2cdd2a099b6b8109a0601deea7d4237a/resolv.conf" to rootfs at "/etc/resolv.conf";
open /ru
n/k3s/containerd/io.containerd.runtime.2.task/k8s.io/2eebd341a988025378397844842bcf2cdd2a099b6b8109a0601deeaTd4237a/rootfs/etc/resolv.conf: operation not permitted:`

we have faced above operation not permitted logs and checked there were many cni logs which respect stop state

then found the SElinux was enabled , we have disabled now and it is perfectly fine

need to understand if we disabled the SElinux what may be the disadvantage, how we can run the k3s with enabling SElinux

https://docs.k3s.io/advanced#:~:text=Using%20a%20custom%20%2D%2Ddata%2Ddir%20under - As per this custom --data-dir will not work with selinux, we need to create proper policies to achieve 

we are handling custom data dir only...how we can achieve this !!!


[OS: redhat: 7.9 , k3s:1.28]
