### ISSUE TITLE
Unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node

### ISSUE THREAD

**Issue by MartinMessmer** [k3s-io/k3s#8281]
**Environmental Info:**
K3s Version: 
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6

Node(s) CPU architecture, OS, and Version: 
Linux hp-elitedesk 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server (master and agent)

**Describe the bug:**
Suddenly today in the morning i found that all my services hosted on k3s are not available anymore. After checking the pods, i saw that the kube-metrics pod was in failed state, so i decided to restart the whole k3s server. Since then im not able to start k3s anymore. Previously the log `journalctl -u k3s.service` showed me:

```
Aug 31 08:30:52 hp-elitedesk k3s[699]: I0831 08:30:52.096293     699 plugin_manager.go:118] "Starting Kubelet Plugin Manager"
Aug 31 08:30:52 hp-elitedesk k3s[699]: time="2023-08-31T08:30:52Z" level=fatal msg="host IPv4 unknown"
Aug 31 08:30:52 hp-elitedesk systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 08:30:52 hp-elitedesk systemd[1]: k3s.service: Failed with result 'exit-code'.
Aug 31 08:30:52 hp-elitedesk systemd[1]: Failed to start Lightweight Kubernetes.
Aug 31 08:30:52 hp-elitedesk systemd[1]: k3s.service: Consumed 5.138s CPU time.
```

So i decided to upgrade the k3s installation. Now i have some different logs, but i guess it is the same reason as both pointing to problems with IPv4.

```
Aug 31 09:39:13 hp-elitedesk k3s[29458]: I0831 09:39:13.119578   29458 plugin_manager.go:118] "Starting Kubelet Plugin Manager"
Aug 31 09:39:13 hp-elitedesk k3s[29458]: time="2023-08-31T09:39:13Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
Aug 31 09:39:13 hp-elitedesk k3s[29458]: time="2023-08-31T09:39:13Z" level=fatal msg="unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"
Aug 31 09:39:13 hp-elitedesk systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 09:39:13 hp-elitedesk systemd[1]: k3s.service: Failed with result 'exit-code'.
Aug 31 09:39:13 hp-elitedesk systemd[1]: Failed to start Lightweight Kubernetes.
Aug 31 09:39:13 hp-elitedesk systemd[1]: k3s.service: Consumed 5.280s CPU time.
```

**Steps To Reproduce:**
- Restart K3s:
- Standard installation without any environment variables set nor special network configuration

**Expected behavior:**
- Start

**Actual behavior:**
- Startup failes: "unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"

**Additional context / logs:**
```
$ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.178.3  netmask 255.255.255.0  broadcast 192.168.178.255
        inet6 2002:b227:9753:0:ee8e:b5ff:fe##:####  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::ee8e:b5ff:fe##:####  prefixlen 64  scopeid 0x20<link>
        ether ec:8e:b5:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 62248  bytes 64563093 (64.5 MB)
        RX errors 0  dropped 3180  overruns 0  frame 0
        TX packets 37507  bytes 6342747 (6.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xe1100000-e1120000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 778856  bytes 1103553179 (1.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 778856  bytes 1103553179 (1.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by manuelbuil** [comment]
Could you share what config parameters you are using?

**Comment by brandond** [comment]
the output of `ip route` might also be interesting, to see if there's something confusing the primary address auto-detection code.

**Comment by MartinMessmer** [comment]
> the output of `ip route` might also be interesting, to see if there's something confusing the primary address auto-detection code.

```
$ ip route
default via 192.168.178.1 dev eno1 proto dhcp src 192.168.178.3 metric 100
192.168.178.0/24 dev eno1 proto kernel scope link src 192.168.178.3 metric 100
192.168.178.1 dev eno1 proto dhcp scope link src 192.168.178.3 metric 100
```

**Comment by MartinMessmer** [comment]
> Could you share what config parameters you are using?

I have actually no special configuration set. So just the standard installation with the default configuration

**Comment by brandond** [comment]
There are multiple errors here regarding IPv4:
```
Aug 31 08:30:52 hp-elitedesk k3s[699]: time="2023-08-31T08:30:52Z" level=fatal msg="host IPv4 unknown"
Aug 31 09:39:13 hp-elitedesk k3s[29458]: time="2023-08-31T09:39:13Z" level=fatal msg="unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"
```
Did K3s by any chance come up before the interface got an address from your DHCP server? You can try temporarily disabling the npc with `--disable-network-policy` to see if it makes it past that, and then check the output of `kubectl get node -o yaml` to see why this host's Node object doesn't have any ipv4 addresses, or if you perhaps changed the name which caused K3s to create a new node with some addresses missing?

**Comment by brandond** [comment]
Yes, K3s probably started up before the interface got an IPv4 address from your DHCP server, so all you had was an IPv6 address. K3s works best with static IPs. If you're going to use DHCP, you should probably configure the k3s systemd unit to wait to start until well after your network stack has settled.
