### ISSUE TITLE
k3s 1.25.11 cannot init

### ISSUE THREAD

**Issue by clywm520** [k3s-io/k3s#8289]
init commend:

sh k3s-install.sh agent --token K109881aae7f389e0ebc45848e2d36d0b05d97d5fa95bb0950d449cd98c60f01e57::server:be01827eb44f132d18960c6b1c841978 --server https://192.168.8.1:6443  --node-ip 192.168.8.2 --node-external-ip 192.168.8.2

The log is :   **kubelet exited: failed to run Kubelet: mountpoint for cpu not found.**

**Comment by clywm520** [comment]
The  CPU MODEL  IS     12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz

**Comment by brandond** [comment]
Please fill out the issue template. What Linux distribution are you running? The error suggests that some of your cgroups are not available or are incorrectly configured - is this on a VPS or other hosted platform where you do not actually have access to the full hardware?

**Comment by clywm520** [comment]
Operating system: Deepin20.9 Linux kernel 5.15 .  

I'll give it a try. Possible reasons are
12th Gen Intel (R) Core (TM) i5-12400
Performance core count 6
But the number of threads is 12
Linux recognizes a CPU core count of 12

But the docker can run normally ， k3s can not run.

I opened the virtual machine to install deep in and adjusted the CPU core count to 6. K3s can run it.

**Comment by brandond** [comment]
Are you saying that k3s worked after adjusting the virtual CPU configuration for the VM?

**Comment by clywm520** [comment]
CPU Hyperthreading does not support K3S running, but Docker can run

**Comment by clywm520** [comment]
CPU开启超线程后，K3S运行不了。但 docker能运行

**Comment by LarsBingBong** [comment]
v1.25.13 is out ... have you checked whether it's fixed on that version?

**Comment by brandond** [comment]
Closing as a configuration issue. The errors in question are coming from the kubelet due to invalid cpu cgroup configuration.
