### ISSUE TITLE
Does the kubelet/kube-proxy in agent node will use the websocket tunnel to do list-watch?

### ISSUE THREAD

**Issue by kubeeeee** [k3s-io/k3s#832]
As described in the title, if loadbalancer is disabled, will the kubelet/kube-proxy will use the websocket tunnel to list-watch the objects?
And we enable the loadbalancer, will the kubelet/kube-proxy will use the websocket tunnel to list-watch the objects?

**Comment by erikwilson** [comment]
To clarify there are two types of load balancers that k3s can create. There is the service load balancer, which exposes kubernetes services and creates pods like:
```
kube-system   pod/svclb-traefik-zpblf          3/3     Running     0          3d18h
```

That service load balancer can be disabled with the `--no-deploy servicelb` flag when starting the server.

---

There is also a different k8s endpoint load balancer which is meant to provide connectivity for HA scenarios. The k8s endpoint load balancer is built into the agent and can not be disabled at the moment, but this effectively allows rounds robin failover to the master node api-server for kubelet & kube-proxy.

---

Then there is a separate reverse tunnel connection, which also uses the k8s endpoints but creates a tunnel for the master nodes api-servers to communicate to the agent node's kubelet & containerd. This is also built into the agent, is always on & cannot be disabled. 

---

Hopefully that helps, please let me know if I can clarify further!

**Comment by kubeeeee** [comment]
@erikwilson Thanks for your kind reply!! Now I think:
1. The websocket tunnel is used to expose the node to master, then master can connect to node with the `log` and `exec` requests.
2. The loadbalancer(tcpproxy) in agent node is used to provide connectivity for HA scenarios. And it has no relationship with the websocket tunnel.

Right? And I think the architecture diagram is a bit misleading to me.

![image](https://user-images.githubusercontent.com/8960046/65537917-cd7a0780-df38-11e9-8465-0f37f9ea3d83.png)

It shows that kubelet/kube-proxy’s list-watch requests also be sent through the tunnel. :(

**Comment by erikwilson** [comment]
Yes, that is correct. The addition of using k8s endpoints to load-balance and tunnel with are fairly new, previously you might say we created a forward proxy and a reverse proxy, and maybe refer to it in combination as a tunnel proxy. I am not sure if there are any great ways to depict the websocket reverse proxy with arrows or boxes, but we can try to come up with a better graphic.

**Comment by kubeeeee** [comment]
> I am not sure if there are any great ways to depict the websocket reverse proxy with arrows or boxes, but we can try to come up with a better graphic.

Yes, I think we can try to come up with a better graphic :)

**Comment by CamelCaseNotation** [comment]
@erikwilson for the reverse tunnel connection which enables exec and logs commands, could you please provide links to code? I'd like to understand exactly what's going on, thank you!

**Comment by erikwilson** [comment]
For the server side: https://github.com/rancher/k3s/blob/master/pkg/daemons/control/tunnel.go
And the agent side: https://github.com/rancher/k3s/blob/master/pkg/agent/tunnel/tunnel.go
