### ISSUE TITLE
[Epic] Validate newer external database versions

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#8360]
**Is your feature request related to a problem? Please describe.**
Our current list of databases, per https://docs.k3s.io/datastore, are becoming stale again and the latest versions should be validated and documented. This is a followup to the previous work done a year ago in https://github.com/k3s-io/k3s/issues/5859.

**Describe the solution you'd like**
We need to validate K3s against newer versions of these databases:
- MariaDB 10.11
- PostgreSQL 15.3

In addition, we should drop support for some of the older versions of DBs that we have that are EOL. These include:
- PostgreSQL 10.7

**Comment by rancher-max** [comment]
@VestigeJ for Postgre validations

**Comment by VestigeJ** [comment]
Postgresql 15.5 validated 
v1.25 
v1.26
v1.27
v1.28
