### ISSUE TITLE
Pods on different nodes cannot reach each other with Tailscale VPN provider

### ISSUE THREAD

**Issue by ky-bd** [k3s-io/k3s#8372]
I was running another k3s cluster (mostly Debian hosts) over tailscale by adding the `--flannel-iface=tailscale0` option, however it's VXLAN-over-(TS)wireguard double encapsulation, so I hope to reduce some overhead. I started a new k3s cluster in a test environment with Tailscale VPN provider, but the pods cannot ping each other. Am I missing some steps? Any help is appreciated.

**Environmental Info:**
K3s Version v1.27.5+k3s1 (8d074ecb): 

Node(s) CPU architecture, OS, and Version : x86_64, VMware Photon OS 5.0, kernel 6.1.45-5.ph5

Cluster Configuration: 2 servers (I understand that it's not true HA config; it's just for test purpose)

**Describe the bug:**

When using `kubctl exec` to get a shell into a Pod running on node1, and ping the cluster IP of another pod running on node2, it gets no response, indicating that cross-node communication has some problems.

Ping other pods on the same node, or ping node2's pods from node1 directly (outside the pod), both can get response.

**Steps To Reproduce:**

- Installed K3s: edit `/etc/rancher/k3s/config.yaml` on both nodes:

```yaml
cluster-cidr: "10.142.0.0/16"
service-cidr: "10.143.0.0/16"
vpn-auth: "name=tailscale,controlServerURL=CUSTOM_HEADSCALE_URL,joinKey=TS_AUTH_KEY"
```
on node1: `curl -sfL https://get.k3s.io | sh -s - server --cluster-init` and copy node-token
on node2: `curl -sfL https://get.k3s.io | sh -s - server --server https://$NODE1_LAN_IP:6443 --token $TOKEN`

- Approve subnet route advertisements on the headscale server

**Expected behavior:**

Pods on different nodes can ping (communicate) with each other

**Actual behavior:**

As described above.

**Additional context / logs:**

Since there are multiple softwares involved, I'll try to describe the context as precise as I can.

The headscale server is running on a seperate machine, version 0.22.3. Tailscale client version is 1.48.2. ACLs allows nodes reaching both cluster-cidr and service-cidr block.
The nodes are both PVE VMs connecting to the same vmbr (direct L2 connection).

| Node | LAN IP | Tailscale IP | Cluster IP |
| - | - | - |  - |
| 1 | 192.168.18.150/24 | 100.64.0.20 | 10.142.0.1/24 |
| 2 | 192.168.18.102/24 | 100.64.0.19 | 10.142.1.1/24 |

Photon OS has a rather strict default firewall policy, so I add the following `iptables` rules:

```sh
# tailscale
-A INPUT -p udp -m udp --dport 41641 -j ACCEPT
-A INPUT -i tailscale0 -j ACCEPT
# k3s cluster and service IP
-A INPUT -s 10.142.0.0/16 -j ACCEPT
-A INPUT -s 10.143.0.0/16 -j ACCEPT
# 
-A INPUT -s 192.168.18.0/24 -j ACCEPT
# allow icmp
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
```

<details><summary>`ip addr` on node1:</summary>
<p>

```sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 16:d9:2a:f2:9e:b1 brd ff:ff:ff:ff:ff:ff
    altname enp6s18
    inet 192.168.18.150/24 metric 1024 brd 192.168.18.255 scope global dynamic eth0
       valid_lft 36943sec preferred_lft 36943sec
    inet6 fe80::14d9:2aff:fef2:9eb1/64 scope link
       valid_lft forever preferred_lft forever
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 100.64.0.20/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fe80::1621:8801:57ad:85b/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
8: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:fd:de:0e:0f:c8 brd ff:ff:ff:ff:ff:ff
    inet 10.142.0.1/24 brd 10.142.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::7cfd:deff:fe0e:fc8/64 scope link
       valid_lft forever preferred_lft forever
9: veth79d5d1e9@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether f6:9c:66:f4:ce:9c brd ff:ff:ff:ff:ff:ff link-netns cni-3230b24c-347a-f0d8-2641-a55783e56067
    inet6 fe80::f49c:66ff:fef4:ce9c/64 scope link
       valid_lft forever preferred_lft forever
10: vethbdba80e9@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether 0a:c6:42:2c:04:ed brd ff:ff:ff:ff:ff:ff link-netns cni-bfee7c6b-0bad-e17b-5ea8-f8d396f263af
    inet6 fe80::8c6:42ff:fe2c:4ed/64 scope link
       valid_lft forever preferred_lft forever
11: veth270703d4@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether a2:9a:ff:98:ca:7b brd ff:ff:ff:ff:ff:ff link-netns cni-ed1aca6a-208a-236a-27b3-2f51a12906a1
    inet6 fe80::a09a:ffff:fe98:ca7b/64 scope link
       valid_lft forever preferred_lft forever
12: vetha346560b@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether 3a:9b:eb:57:3f:08 brd ff:ff:ff:ff:ff:ff link-netns cni-8100ef71-5e9e-d5c6-9c10-0ad212538ba4
    inet6 fe80::389b:ebff:fe57:3f08/64 scope link
       valid_lft forever preferred_lft forever
13: veth88e9cb8f@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether 1e:1c:63:b4:ed:77 brd ff:ff:ff:ff:ff:ff link-netns cni-3c82d975-ebd8-2174-7552-7be220bc4a55
    inet6 fe80::1c1c:63ff:feb4:ed77/64 scope link
       valid_lft forever preferred_lft forever
```

</p>
</details> 

<details><summary>`ip addr` on node2:</summary>
<p>

```sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 96:9f:67:b1:60:a8 brd ff:ff:ff:ff:ff:ff
    altname enp6s18
    inet 192.168.18.102/24 metric 1024 brd 192.168.18.255 scope global dynamic eth0
       valid_lft 37272sec preferred_lft 37272sec
    inet6 fe80::949f:67ff:feb1:60a8/64 scope link
       valid_lft forever preferred_lft forever
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 100.64.0.19/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fe80::fe30:8e5a:447:4ed1/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
8: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue state UP group default qlen 1000
    link/ether c6:68:1f:68:a4:0a brd ff:ff:ff:ff:ff:ff
    inet 10.142.1.1/24 brd 10.142.1.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::c468:1fff:fe68:a40a/64 scope link
       valid_lft forever preferred_lft forever
9: veth5d4c092c@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc noqueue master cni0 state UP group default
    link/ether 4a:b4:aa:3b:60:15 brd ff:ff:ff:ff:ff:ff link-netns cni-bb84ff9a-5108-f4d4-32d8-ceab44d6a4e8
    inet6 fe80::48b4:aaff:fe3b:6015/64 scope link
       valid_lft forever preferred_lft forever
```

</p>
</details> 

<details><summary>`ip -4 route show table all` on node1:</summary>
<p>

Routes regarding other irrelevant tailscale nodes are removed

```sh
10.142.1.0/24 dev tailscale0 table 52
100.64.0.19 dev tailscale0 table 52
100.100.100.100 dev tailscale0 table 52
default via 192.168.18.1 dev eth0 proto dhcp src 192.168.18.150 metric 1024
10.142.0.0/24 dev cni0 proto kernel scope link src 10.142.0.1
192.168.18.0/24 dev eth0 proto kernel scope link src 192.168.18.150 metric 1024
192.168.18.1 dev eth0 proto dhcp scope link src 192.168.18.150 metric 1024
local 10.142.0.1 dev cni0 table local proto kernel scope host src 10.142.0.1
broadcast 10.142.0.255 dev cni0 table local proto kernel scope link src 10.142.0.1
local 100.64.0.20 dev tailscale0 table local proto kernel scope host src 100.64.0.20
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
local 192.168.18.150 dev eth0 table local proto kernel scope host src 192.168.18.150
broadcast 192.168.18.255 dev eth0 table local proto kernel scope link src 192.168.18.150
```

</p>
</details> 

<details><summary>`ip -4 route show table all` on node2:</summary>
<p>

Routes regarding other irrelevant tailscale nodes are removed

```sh
10.142.0.0/24 dev tailscale0 table 52
100.64.0.20 dev tailscale0 table 52
100.100.100.100 dev tailscale0 table 52
default via 192.168.18.1 dev eth0 proto dhcp src 192.168.18.102 metric 1024
10.142.1.0/24 dev cni0 proto kernel scope link src 10.142.1.1
192.168.18.0/24 dev eth0 proto kernel scope link src 192.168.18.102 metric 1024
192.168.18.1 dev eth0 proto dhcp scope link src 192.168.18.102 metric 1024
local 10.142.1.1 dev cni0 table local proto kernel scope host src 10.142.1.1
broadcast 10.142.1.255 dev cni0 table local proto kernel scope link src 10.142.1.1
local 100.64.0.19 dev tailscale0 table local proto kernel scope host src 100.64.0.19
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
local 192.168.18.102 dev eth0 table local proto kernel scope host src 192.168.18.102
broadcast 192.168.18.255 dev eth0 table local proto kernel scope link src 192.168.18.102
```

</p>
</details> 

`etcdctl` shows that both nodes are started and healthy, so I assume that control-plane traffic has no problem.

When pinging from pod to pod, I use `tcpdump -i any  -XvvennSs 0 net 10.142.1.0/24` on node1 to capture the traffic. The packet is sent out through tailscale0 interface:

<details><summary>Details</summary>
<p>

```sh
16:42:27.058860 veth79d5d1e9 P   ifindex 9 b2:5c:03:da:cb:6f ethertype IPv4 (0x0800), length 104: (tos 0x0, ttl 64, id 46678, offset 0, flags [DF], proto ICMP (1), length 84)
    10.142.0.2 > 10.142.1.2: ICMP echo request, id 30, seq 2, length 64
        0x0000:  4500 0054 b656 4000 4001 6e33 0a8e 0002  E..T.V@.@.n3....
        0x0010:  0a8e 0102 0800 2f1b 001e 0002 a391 2533  ....../.......%3
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0040:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0050:  0000 0000                                ....
16:42:27.058869 cni0  In  ifindex 8 b2:5c:03:da:cb:6f ethertype IPv4 (0x0800), length 104: (tos 0x0, ttl 64, id 46678, offset 0, flags [DF], proto ICMP (1), length 84)
    10.142.0.2 > 10.142.1.2: ICMP echo request, id 30, seq 2, length 64
        0x0000:  4500 0054 b656 4000 4001 6e33 0a8e 0002  E..T.V@.@.n3....
        0x0010:  0a8e 0102 0800 2f1b 001e 0002 a391 2533  ....../.......%3
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0040:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0050:  0000 0000                                ....
16:42:27.058894 tailscale0 Out ifindex 3 ethertype IPv4 (0x0800), length 104: (tos 0x0, ttl 63, id 46678, offset 0, flags [DF], proto ICMP (1), length 84)
    10.142.0.2 > 10.142.1.2: ICMP echo request, id 30, seq 2, length 64
        0x0000:  4500 0054 b656 4000 3f01 6f33 0a8e 0002  E..T.V@.?.o3....
        0x0010:  0a8e 0102 0800 2f1b 001e 0002 a391 2533  ....../.......%3
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0040:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0050:  0000 0000                                ....
```
</p>
</details> 

However, on node2, `tcpdump -i any -XvvennSs 0 not src net 10.142.1.0/24 and dst net 10.142.1.0/24` didn't capture any packets. If ping pod from node1 directly, this can capture packets with source IP 100.64.0.20. So I assume tailscale subnet router is working well.

I guess the cause of the issue might be one of the following:

1. The tailscale dropped `10.142.0.2 > 10.142.1.2` packet, since it's not from a Tailscale IP (maybe similar to the case where two not-L2-connected nodes try to communicate with flannel host-gw backend);
2. iptables on either node drop the packet, because of PhotonOS' strict default.
3. Tailscale don't work with multi-server setup even if they are L2-connected.

**Comment by brandond** [comment]
Have you tried just turning off the host firewall and removing any other iptables rules, just to ensure that's not interfering with things? That's usually the first thing I try, if traffic is disappearing.

**Comment by manuelbuil** [comment]
> > cluster-cidr to cluster-cidr (and service-cidr) traffic
> 
> Yes, pods needs to talk to other pods, and pods need to talk to services.
> 
> @manuelbuil is this a gap in the docs? We only cover autoApprovers, I don't think we have anything about ACLs at all. Are ACLs not enabled by default?

It is a on purpose gap. Note that Tailscale ACLs by default allow all traffic:
```
	"acls": [
		// Match absolutely everything.
		// Comment this section out if you want to define specific restrictions.
		{"action": "accept", "src": ["*"], "dst": ["*:*"]},
	],
```
However, the moment you add a rule, all traffic is blocked unless explicitly allowed. At the beginning I thought about explaining in the docs how to use them but they are tricky, based on tags and can be a mess if you have several clusters.

**Comment by manuelbuil** [comment]
> I figured out this issue by myself - it's Tailscale's ACL problem. Not only node to cluster-cidr and node to service-cidr traffic needs to be allowed, but also cluster-cidr to cluster-cidr (and service-cidr) traffic, otherwise Tailscale would drop them.
> 
> For headscale ACL yaml, it's something like this (you may have different tag/user/group/host names):
> 
> ```yaml
> acls:
>   - action: accept
>     src:
>       - "tag:cluster-nodes"
>       - "10.142.0.0/16"
>       - "10.143.0.0/16"
>     dst:
>       - "tag:cluster-nodes:*"
>       - "10.142.0.0/16:*"
>       - "10.143.0.0/16:*"
> autoApprovers:
>   routes:
>     10.142.0.0/16:
>       - "tag:cluster-nodes"
> ```
> 
> Maybe we should add this to the Tailscale VPN integration section of the doc?
> 
> Another note for other Photon OS users: be careful with the `nftables` package from `tdnf`. It comes with a even strict policy which creates a `firewall` table and blocks inbound and forwarding traffic, and you won't see or edit it with `iptables` command. I accidentally installed it and wasted some time to find out why my nodes couldn't join the cluster.

Thanks for this. I am actually surprised you need the services there. Traffic going to a service gets dnatted before leaving the node, so when it reaches tailscale, the destination-ip should be the pod-IP
