### ISSUE TITLE
Not killing pods by default, system OOM takes over

### ISSUE THREAD

**Issue by andyjeffries** [k3s-io/k3s#838]
We have a customer cluster that is overloaded. However, if we describe one of the nodes with issues, it seems that at no point did Kubernetes [out of resource handling](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/) kick in.

For example the events are:

```
Events:
  Type     Reason                   Age                  From                        Message
  ----     ------                   ----                 ----                        -------
  Normal   NodeNotReady             25m (x3 over 46m)    kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeNotReady
  Normal   NodeHasNoDiskPressure    19m (x7 over 5d1h)   kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     19m (x7 over 5d1h)   kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasSufficientPID
  Normal   NodeReady                19m (x6 over 5d1h)   kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeReady
  Normal   NodeHasSufficientMemory  19m (x7 over 5d1h)   kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasSufficientMemory
  Warning  SystemOOM                12m (x4 over 25m)    kubelet, kube-node-9f4e     System OOM encountered
  Warning  ContainerGCFailed        12m (x4 over 46m)    kubelet, kube-node-9f4e     rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   NodeAllocatableEnforced  9m23s                kubelet, kube-node-9f4e     Updated Node Allocatable limit across pods
  Normal   Starting                 9m23s                kubelet, kube-node-9f4e     Starting kubelet.
  Normal   Starting                 9m23s                kube-proxy, kube-node-9f4e  Starting kube-proxy.
```

The instance felt stuck (`NotReady` node status, couldn't SSH to it) so we rebooted the VM and the events continue with:

```
  Warning  Rebooted                 9m23s                kubelet, kube-node-9f4e     Node kube-node-9f4e has been rebooted, boot id: 362cf7ed-b89b-44d6-accd-6a840bc56bdc
  Warning  InvalidDiskCapacity      9m23s                kubelet, kube-node-9f4e     invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientPID     66s (x4 over 9m23s)  kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasSufficientPID
  Normal   NodeHasNoDiskPressure    66s (x4 over 9m23s)  kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasNoDiskPressure
  Normal   NodeReady                66s (x2 over 9m23s)  kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeReady
  Normal   NodeHasSufficientMemory  66s (x4 over 9m23s)  kubelet, kube-node-9f4e     Node kube-node-9f4e status is now: NodeHasSufficientMemory
  Warning  SystemOOM                15s (x3 over 67s)    kubelet, kube-node-9f4e     System OOM encountered
```

So, am is this correct from a k3s point of view, that the events say `NodeHasSufficientMemory` and then the next thing is `System OOM encountered`? Feels like at some point there should have been a memory pressure event and a pod killed, before it got to the point that the system's OOM killer took over.

Obviously, we've mentioned to the customer about setting [resource limits](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container) for their pods/containers and they will, but they quite rightly say that the cluster should handle this nicely rather than nodes just (effectively) dying completely.

**Comment by planetf1** [comment]
I tried overloading a small node on a regular k8s environment (IBM cloud IKS 1.15, 4GB/single node/2cpu) and got things like
```
  MemoryPressure   True    Wed, 25 Sep 2019 15:43:37 +0100   Wed, 25 Sep 2019 15:38:37 +0100   KubeletHasInsufficientMemory   kubelet has insufficient memory available
  DiskPressure     False   Wed, 25 Sep 2019 15:43:37 +0100   Wed, 25 Sep 2019 14:16:01 +0100   KubeletHasNoDiskPressure       kubelet has no disk pressure
  PIDPressure      False   Wed, 25 Sep 2019 15:43:37 +0100   Wed, 25 Sep 2019 14:16:01 +0100   KubeletHasSufficientPID        kubelet has sufficient PID available
  Ready            True    Wed, 25 Sep 2019 15:43:37 +0100   Wed, 25 Sep 2019 14:16:51 +0100   KubeletReady                   kubelet is posting ready status. AppArmor enabled
```
and
```
  Normal   NodeHasInsufficientMemory  5m18s                  kubelet, 10.72.127.182  Node 10.72.127.182 status is now: NodeHasInsufficientMemory
  Warning  EvictionThresholdMet       2m50s (x3 over 5m19s)  kubelet, 10.72.127.182  Attempting to reclaim memory
```
Whilst pods are in a variety of states including Evicted  (as well as Running/Completed. For example
```
  Normal   Scheduled  12m    default-scheduler       Successfully assigned default/vdc-rangeradmin-558b5fc8d-z6df7 to 10.72.127.182
  Normal   Pulling    12m    kubelet, 10.72.127.182  Pulling image "docker.io/planetf1/egeria-configure:latest"
  Normal   Pulled     11m    kubelet, 10.72.127.182  Successfully pulled image "docker.io/planetf1/egeria-configure:latest"
  Normal   Created    11m    kubelet, 10.72.127.182  Created container wait-for-db
  Normal   Started    11m    kubelet, 10.72.127.182  Started container wait-for-db
  Normal   Pulling    11m    kubelet, 10.72.127.182  Pulling image "docker.io/planetf1/apache-ranger-admin:latest"
  Normal   Pulled     10m    kubelet, 10.72.127.182  Successfully pulled image "docker.io/planetf1/apache-ranger-admin:latest"
  Normal   Created    10m    kubelet, 10.72.127.182  Created container vdc-ranger
  Normal   Started    10m    kubelet, 10.72.127.182  Started container vdc-ranger
  Warning  Evicted    5m42s  kubelet, 10.72.127.182  The node was low on resource: memory. Container vdc-ranger was using 791296Ki, which exceeds its request of 0.
  Normal   Killing    5m42s  kubelet, 10.72.127.182  Stopping container vdc-ranger
```
At all times I was able to interact with the api - though this deployment does keep the master separated from the worker nodes I believe. 

This seems to be how a k8s deployment should behave under pressure?

**Comment by erikwilson** [comment]
Please make sure that swap is disabled on the system, in particular the OOM killer appears to take swap into consideration when it should not.

**Comment by andyjeffries** [comment]
It's definitely disabled on all nodes (or at least we've taken no action to specifically set it up and `htop` reports it as 0/0).

**Comment by erikwilson** [comment]
Thanks for the info, pinging @galal-hussein as I think this was something that was tested successfully recently.

**Comment by vincent99** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#kubelet-may-not-observe-memory-pressure-right-away Could be relevant if the memory usage is fine and then quickly not fine.

**Comment by pecigonzalo** [comment]
I have a similar situation:
```
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo1
spec:
  containers:
    - name: mem
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "2", "--vm-bytes", "250M", "--vm-hang", "0"]
```
should be terminated, but its not.

**Comment by brandond** [comment]
@pecigonzalo can you show pod memory utilization?

**Comment by pecigonzalo** [comment]
@brandond I forgot to mention something quite important, I'm running k3s with k3d on WSL2, so it could be unrelated and ill open a separate issue, but given the description, I thought it could be related to k3s directly.

The pod reaches the limit (100M) and stays there, from the host I can see
```
❯ ps aux | grep stress
root      4022  0.0  0.0    776     0 ?        Ss   21:02   0:00 stress --vm 2 --vm-bytes 250M --vm-hang 0
root      4036  0.2  0.3 256780 57752 ?        S    21:02   0:00 stress --vm 2 --vm-bytes 250M --vm-hang 0
root      4037  0.1  0.2 256780 37900 ?        S    21:02   0:00 stress --vm 2 --vm-bytes 250M --vm-hang 0
```
kubectl shows
```
❯ kubectl top pod memory-demo1
NAME           CPU(cores)   MEMORY(bytes)
memory-demo1   0m           99Mi
```

I tried the same tasks in a GKE and minikube, and both OOM the container and send SIGKILL.

Could this be related to k3s running in WSL2 https://github.com/rancher/k3s/pull/705? As I see the same error in the nodes and Im running in WS2L, which does not have `systemd`.

**Comment by brandond** [comment]
OK so it's not actually violating the limit, which would explain why it's not getting killed. Does it appear to be violating the limit according to any other tools (ps, top, etc)?

**Comment by pecigonzalo** [comment]
I think it is violating it, that is what stress is built for. In PS aux is
showing as using more than the limit and in normal K8s it correctly
displays that. I think k3s or k3d is causing it to not be detected properly.

**Comment by wvxvw** [comment]
I'm seeing a similar problem, however, on a desktop Linux.

Additionally, it seems that k3s never creates "guaranteed" QoS class. All I see in `/sys/fs/cgroup/memory/kubepods` is `burstable` and `besteffort`, even though the request and limit are set to the same value.

**Comment by brandond** [comment]
@wvxvw from [the docs](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed):
> For a Pod to be given a QoS class of Guaranteed:
>
> * Every Container in the Pod must have a memory limit and a memory request.
> * For every Container in the Pod, the memory limit must equal the memory request.
> *Every Container in the Pod must have a CPU limit and a CPU request.
> * For every Container in the Pod, the CPU limit must equal the CPU request.

Can you provide an example of a pod spec meeting these requirements that doesn't go into the Guaranteed class?

**Comment by wvxvw** [comment]
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: conda-${PYTHON_VERSION}
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
  - name: python
    image: continuumio/conda-ci-linux-64-python${PYTHON_VERSION}
    command:
    - /bin/bash
    args:
    - "-c"
    - "sleep 99d"
    workingDir: /home/jenkins/agent
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "2Gi"
        cpu: "2"
```

This is used in the context of Jenkins + Kubernetes plugin, with Jenkins master deployed in the same cluster where it runs slaves.

It's taken from a matrix build. `PYTHON_VERSION` may expand to one of `3.7`, `3.8` or 3.9`. But, all of them result in the same behavior.

**Comment by brandond** [comment]
Seems to work for me?

```console
[root@centos01 ~]# cat qostest.yaml
apiVersion: v1
kind: Pod
metadata:
  name: conda-3.7
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
  - name: python
    image: continuumio/conda-ci-linux-64-python3.7
    command:
    - /bin/bash
    args:
    - "-c"
    - "sleep 99d"
    workingDir: /home/jenkins/agent
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "2Gi"
        cpu: "2"

[root@centos01 ~]# kubectl apply -f qostest.yaml
pod/conda-3.7 created

[root@centos01 ~]# kubectl get pods -o custom-columns=NAMESPACE:metadata.namespace,NAME:metadata.name,QOSCLASS:status.qosClass
NAMESPACE   NAME        QOSCLASS
default     conda-3.7   Guaranteed
```

**Comment by wvxvw** [comment]
Well, that's what I was asking about... why there isn't a "guaranteed" directory.

Anyways, the larger problem is that this pod is killed by the system's OOM killer... which is still not really the main problem. The main problem being the apparent inability of Kubernetes in general to control memory overcommit. I mean, I would like to disable it, but there just is no way to do it.

**Comment by dereknola** [comment]
This appears to no be an issue as of v1.20.15+, spinning up a "guaranteeed" pod
```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
```

This pod appears under `/sys/fs/cgroup/memory/kubepods/pod26f3fe02-9448-4434-8d53-fac22702a5d0/` which is the correct location. There is no "guaranteed" directory, pods with that QOS sit directly in the `/kubepods/` directory
