### ISSUE TITLE
Cherry-pick performance fix in kube-router

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#8380]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

There is a performance issue on the network policy controller which makes pod creation very slow when there are a lot of network policies. More information: https://github.com/k3s-io/k3s/discussions/8321

We must cherry-pick the fix created in the upstream kube-router

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by aganesh-suse** [comment]
Closing this - since the update router issues have been verified/closed.
