### ISSUE TITLE
metadata.name field of HelmChart being added to beginning of "chart" field when installing

### ISSUE THREAD

**Issue by Jordanb716** [k3s-io/k3s#8391]
**Environmental Info:**
K3s Version: 
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7

Node(s) CPU architecture, OS, and Version: 
Linux athena 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single server.

**Describe the bug:**
When I tried to install grafana/loki, using a HelmChart named 'loki', the job tried to install loki/grafana/loki. Looking into it further, it looks like the metadata.name of the HelmChart is being added to beginning of the spec.chart when the helm chart is being installed. This seemed poor, but I was able to get it to work by changing the name to "grafana", but now I'd like to install "grafana/grafana-agent" as well, which would force me to have two HelmCharts with the same name.

The documentation I found (https://docs.k3s.io/helm) states the metadata.name field should only affect the NAME field of the install command. The Helm install documentation (https://helm.sh/docs/helm/helm_install/) lists the syntax as `helm install [NAME] [CHART] [flags]`, however this behavior seems to be `helm install [NAME] [NAME/CHART] [flags]`

**Steps To Reproduce:**
- Install K3s with `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --config=/hypercube/k8s/kubeconfig.yaml --token-file=/hypercube/k8s/token --disable traefik" sh -`

`kubectl -f apply` the HelmChart included in the "Additional context / logs" section below.

**Expected behavior:**
The Helm chart 'grafana/grafana-agent-flow' is installed from the repo `https://grafana.github.io/helm-charts`

**Actual behavior:**
The non-existing Helm chart 'asdf/grafana/grafana-agent-flow' fails to install.

**Additional context / logs:**
My HelmChart:
```
kind: HelmChart
apiVersion: helm.cattle.io/v1
metadata:
  name: asdf
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana/grafana-agent-flow
  targetNamespace: monitor
  createNamespace: true
```
asdf is a deliberately stupid name that is only used once ever for demonstration of the issue.

Relevant part of log:
```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install asdf asdf/grafana/grafana-agent-flow
Error: INSTALLATION FAILED: chart "grafana/grafana-agent-flow" matching  not found in asdf index. (try 'helm repo update'): no chart name found
```

**Comment by brandond** [comment]
The Helm install job adds the configured repo using the HelmChart resource name as the repo name, and then installs the chart as REPO/CHART. Essentially:

```bash
# repo name is asdf
# repo url is https://grafana.github.io/helm-charts
# chart is grafana-agent-flow

helm repo add asdf https://grafana.github.io/helm-charts
helm install asdf/grafana-agent-flow
```

You are unnecessarily including what you assume to be the repo name in the `chart` field. The chart is not stored in the grafana repo as `grafana/grafana-agent-flow`, it is just `grafana-agent-flow`. Remove the repo name and and slash from the chart field, and just specify the chart name.
