### ISSUE TITLE
etcd support to listen on public IPs

### ISSUE THREAD

**Issue by batulziiy** [k3s-io/k3s#8398]
**Is your feature request related to a problem? Please describe.**
Currently, I found that k3s doesn't support etcd to listen on public IPs. When I try to join a new k3s node (a node reside on the cloud) to the existing on-premise cluster through netmaker VPN, a new node tries to connect to the private IP in order to join etcd cluster. ETCD itself has an option to listen on multiple ports, but k3s doesn't support  '--listen-client-urls=https://ip:port' as an etcd-arg.  

**Describe the solution you'd like**
It would be cool if you add support to ETCD listen on public IPs. For instance, we can add more IPs to listen, by adding --etcd-arg as below. 
`--etcd-arg '--listen-client-urls=https://<loopback-ip>:2379,https://<private-ip>:2379,https://<public-ip>:2379'`

**Describe alternatives you've considered**
The goal of this feature request is to make k3s able to add new cloud nodes to the existing on-premise cluster via VPN. 

**Additional context**

**Comment by Amejonah1200** [comment]
An additional use case for that would be if a node has multiple private addresses: e.g. multiple network adapters eth0 and wlan0.

**Comment by brandond** [comment]
definitely wouldn't recommend running etcd over a wireless network.
