### ISSUE TITLE
`k3s check-config` does not respect rootless mode

### ISSUE THREAD

**Issue by ajit3259** [k3s-io/k3s#8403]
**Environmental Info:**
K3s Version: 

$ k3s --version
```
k3s version v1.26.0-rc1+k3s2 (bc6bebc9)
go version go1.19.4
```

Node(s) CPU architecture, OS, and Version: 

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Cluster Configuration:

```
1 server
```

**Describe the bug:**

facing issue with prefer bundled bin 
Wanted to use this as there was issues due to use of host machine ip tables as mentioned here: https://docs.k3s.io/known-issues#iptables

These are documented here: https://docs.k3s.io/known-issues#iptables
And a solution have applied the prefer-bundled-bin to use in config.yaml file passed to k3s server

```
rootless: true
prefer-bundled-bin: true
```

**Steps To Reproduce:**

- Installed K3s: 
Ran the k3s in rootless mode through overriding with flags in config.yaml

**Expected behavior:**

Should have the k3s embedded bin for iptables in k3s check-config
**Actual behavior:**

But is host machine iptables:

k3s check-config is still utilizing host ip tables:

```

$ k3s check-config

Verifying binaries in /var/lib/rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.7 (nf_tables): ok
- swap: disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

...
...

STATUS: pass
```

**Additional context / logs:**

Only after explicitly deleting the iptables through `apt-get remove`
Then k3s check-config uses the embedded iptables bin

```
Verifying binaries in /var/lib/rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin:
- sha256sum: good
- aux/ip6tables: symlink to xtables-legacy-multi
- aux/ip6tables-restore: symlink to xtables-legacy-multi
- aux/ip6tables-save: symlink to xtables-legacy-multi
- aux/iptables: symlink to xtables-legacy-multi
- aux/iptables-restore: symlink to xtables-legacy-multi
- aux/iptables-save: symlink to xtables-legacy-multi
- links: good

System:
- /var/lib/rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin/aux iptables v1.8.8 (legacy): ok
```

**Comment by brandond** [comment]
Check-config does not respect rootless mode, as is shown by the fact that is is checking binaries in the default data-dir `/var/lib/rancher/k3s/` and not your unprivileged user's data-dir.

**Comment by ajit3259** [comment]
Thanks for the reply.

Can you please provide steps how can we identify if k3s when used in rootless mode and prefer-bundled-bin indeed using with the bundled binaries?

**Comment by brandond** [comment]
You could look at the path environment variable for the k3s process:
```bash
cat /proc/$(pgrep --full "k3s server")/environ | xargs -0 -n1 echo | grep PATH
```

**Comment by ajit3259** [comment]
This was the output:

```
ubuntu@ip-172-31-34-14:~$ pgrep --full "k3s server"
7438
7489
7512
```

```
ubuntu@ip-172-31-34-14:~$ sudo cat /proc/7438/environ | xargs -0 -n1 echo | grep PATH
PATH=/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin/aux
ubuntu@ip-172-31-34-14:~$ sudo cat /proc/7489/environ | xargs -0 -n1 echo | grep PATH
PATH=/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin/aux
ubuntu@ip-172-31-34-14:~$ sudo cat /proc/7512/environ | xargs -0 -n1 echo | grep PATH
PATH=/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/k3s/.rancher/k3s/data/42d7f04c5f9849f0016361b8fd9226a044204a3bca9f576ac8aabe93d2560386/bin/aux
```

```
ubuntu@ip-172-31-34-14:~$ ps aux | grep 7438
k3s         7438  0.0  1.0 844840 85464 ?        Ssl  Sep22   0:07 /usr/local/bin/k3s server
ubuntu     75208  0.0  0.0   7004  2292 pts/0    S+   04:14   0:00 grep --color=auto 7438
ubuntu@ip-172-31-34-14:~$ ps aux | grep 7512
k3s         7512  3.3  6.7 1337192 529384 ?      Ssl  Sep22  35:38 k3s server
ubuntu     75212  0.0  0.0   7004  2252 pts/0    S+   04:14   0:00 grep --color=auto 7512
ubuntu@ip-172-31-34-14:~$ ps aux | grep 7489
k3s         7489  0.0  1.0 844960 84892 ?        Sl   Sep22   0:03 k3s server
```

**The reason for using  preferring the bundled iptables bin was to avoid the sync error for network policy which I am seeing constantly through `journalctl -u k3s`**

```
Sep 23 04:07:17 ip-172-31-34-14 k3s[7512]: E0923 04:07:17.787570      33 network_policy_controller.go:284] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 1 (iptables-restore: line 358 failed

```

Due to this pods which have egress disabled are able to communicate to external world.

But if I remove the nftables version available on ubuntu, then these errors are not there.
So I guess it is still using the iptables bin of host machine rather than bundled version.

**Comment by brandond** [comment]
If you run `k3s` as root, it will extract the binaries out to `/var/lib/rancher/k3s/data`, and those files will be used in preference to the files in the user's home directory. This is to avoid having k3s extract out the binaries into the user's home dir every time it is run as an unprivileged user, when it should instead use the system-level binaries.

If you want to avoid this, do not run k3s as root - only run it as the unprivileged user.

I suppose we could have k3s refuse to run as root if `rootless` is set, to better protect against this sort of mistake.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  k3s version v1.28.2+k3s-71f56a72 (71f56a72)


```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"

*Cluster Configuration:*
1 node servers 



## Steps to validate the fix
1. Install k3s supported version but dont start it 
2. Run k3s check config as non root / root / non root user
3. As non root assets shoul be on home directory
4. As root assets should be on /var/lib/rancher/k3s/data/./bin
5. As non root user again should again be at home.



## **Reproduction Issue:**
<details>

```
$ k3s -v
k3s version v1.24.17+k3s1 (026bb0ec)
go version go1.20.7
~$ k3s check-config


Verifying binaries in /home/ubuntu/.rancher/k3s/data/eea1a0df6965b7835a5f29066a70a44cb59d72f8ee85bd0afb72499857fd7d68/bin:




As root :

$ sudo k3s check-config
Verifying binaries in /var/lib/rancher/k3s/data/eea1a0df6965b7835a5f29066a70a44cb59d72f8ee85bd0afb72499857fd7d68/bin:
- sha256sum: good
- links: good




non root user:

k3s check-config
cat: /sys/kernel/security/apparmor/profiles: Permission denied

Verifying binaries in /var/lib/rancher/k3s/data/ead6a1703a6dcb4fa71296173ee208c5b05b95a27574fe74946557324bab2582/bin:
- sha256sum: good
- links: good


```



## **Validation Results:**
<details> 
    
    ```console

```

k3s version v1.28.2+k3s-71f56a72 (71f56a72)
go version go1.20.8


~$ k3s check-config

Verifying binaries in /home/ubuntu/.rancher/k3s/data/da24b9750c9c76b1f00674b8c1e025e7747e4eee77624f423b604f74c1b2284f/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.7 (nf_tables): ok
- swap: disabled
- routes: ok



As root :


Verifying binaries in /var/lib/rancher/k3s/data/da24b9750c9c76b1f00674b8c1e025e7747e4eee77624f423b604f74c1b2284f/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.7 (nf_tables): ok
- swap: disabled
- routes: ok


non root user:

$ k3s check-config

Verifying binaries in /home/ubuntu/.rancher/k3s/data/da24b9750c9c76b1f00674b8c1e025e7747e4eee77624f423b604f74c1b2284f/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.7 (nf_tables): ok
- swap: disabled
- routes: ok




    
```
