### ISSUE TITLE
Disable http/grpc mux for etcd

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8415]
Tracking issue for: 
* https://github.com/etcd-io/etcd/issues/15402

The etcd project has documented issues with watch stream starvation under load when http and grpc are muxed on the same TLS listener.

* For embedded etcd, we need to enable http on a different port, enable to free the main client port for dedicated grpc use
* For kine, we should investigate whether or not this same issue affects unencrypted unix sockets, or if it only applies to TCP/TLS listeners.

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit 00fc5a23
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1031-aws x86_64)
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
token: <token>
node-ip: <public>
node-external-ip: <private>
```

 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Wait for the cluster to be up and running
4. Check the logs using: `$ sudo journalctl -u k3s | grep "Running http"`
5. Ensure no error message is displayed
 
 
**Replication Results:**
- k3s version used for replication:

```
$ k3s -v
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8
```
 

- Observed warn message in logs when searched
```
$ sudo journalctl -u k3s | grep "Running http"
Oct 05 15:43:03 ip-xxx-xx-xx-174 k3s[1670]: {"level":"warn","ts":"2023-10-05T15:43:03.366688Z","caller":"embed/config.go:673","msg":"Running http and grpc server on single port. This is not recommended for production."}
Oct 05 15:43:03 ip-xxx-xx-xx-174 k3s[1670]: {"level":"warn","ts":"2023-10-05T15:43:03.366755Z","caller":"embed/config.go:673","msg":"Running http and grpc server on single port. This is not recommended for production."}
```
 
 
**Validation Results:**
- k3s version used for validation:

```
```
 

```
```
 
**Additional context / logs:**
```
```

**Comment by jaysonsantos** [comment]
Hi there, for those who rely on this feature 🙈 on constrained systems, is there a way to enable it once more? After updating to 1.27.7 a small service stopped working because it uses lua with the http version.
