### ISSUE TITLE
Provide install script checksums

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8447]
@josegomezr would like a checksum of the install script so that they can validate that what's being run is the same as what's in the repo.

I'm not convinced that this actually closes any gaps, since someone with the ability to alter the install script either at rest or on the wire would also be able to alter the checksum file that is stored in the same place... but I don't see that it hurts anything to make it available.

**Comment by brandond** [comment]
No backports since the install script is only served off master.

**Comment by dereknola** [comment]
Ass install script is only pulled from master, no point in back-porting it.

**Comment by aganesh-suse** [comment]
Verified that the sha checksum value is available for download/verification: 

On the node(Ubuntu 22.04): 
1. Download install.sh file: curl -sfL https://get.k3s.io > install.sh
2. Run the sha256 checksum: 
```
$ sha256sum install.sh 
4903337c0ec695a4a1f1a755737a86b985c85dc0e5174f16c971455186e4bf31  install.sh
```
This is the content in file: https://github.com/k3s-io/k3s/blob/master/install.sh.sha256sum
