### ISSUE TITLE
Using `--kubelet-arg='allowed-unsafe-sysctls=...` removes the defaults of `net.ipv4.ip_forward,net.ipv6.conf.all.forwarding`

### ISSUE THREAD

**Issue by woopla** [k3s-io/k3s#8487]
**Environmental Info:**
K3s Version:
```bash
k3s version v1.26.3+k3s1 (01ea3ff2)
go version go1.19.7
```

Node(s) CPU architecture, OS, and Version: `Linux <host> 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: 1 server and 2 agents

**Describe the bug:**
I need to be able to set the `net.core.somaxconn` sysctl inside some pods, so I added `--kubelet-arg='allowed-unsafe-sysctls=net.core.somaxconn` to the server and agent Systemd unit files and restarted them all. After restarting, the Traefik load balancer service pods switched to a status of `SysctlForbidden` and all ingresses stopped working.

The logs for the pods pointed to `net.ipv4.ip_forward` being the culprit. I added this sysctl to the K3s args, restarted the Systemd services and killed the load balancer and Traefik pods, and everything was fine again.

After some looking around in the source code, I found that the issue might be around <https://github.com/k3s-io/k3s/blob/0e5c760625f52145618a6fe74a52c578463861e0/pkg/daemons/agent/agent_linux.go#L173>. Instead of adding these default values to whatever is passed on the command-line, it seems that the command-line values overwrite them.

**Steps To Reproduce:**
Install a single-node K3s with `--kubelet-arg='allowed-unsafe-sysctls=net.core.somaxconn'` and look at the `svclb-traefik` pod status.

**Expected behavior:**
The existing pods should continue working as-is

**Actual behavior:**
Pods that depend on the `net.ipv4.ip_forward,net.ipv6.conf.all.forwarding` sysctls stop working

**Comment by brandond** [comment]
User-provided arguments override the defaults, to allow users to customize the configuration. If we did otherwise, there would be no way for users to override any CLI flag that we set by default.

We could probably document this and/or provide a warning when overriding a default, but the desired behavior here is not to merge the user arguments with the defaults.

**Comment by woopla** [comment]
Yes I'm fine with user-provided args overriding the defaults, but then you need to document all the existing defaults for each option. not only for this one.

**Comment by brandond** [comment]
I don't believe we've any plans to do that. The generated config is variable in places; I think the best recommendation would be to check the logs to see the default arguments that we build for each component, based on your environment and configuration, and take those into consideration when adding your own.

**Comment by woopla** [comment]
Would you consider outputting the defaults for each option when running `--help`? It's already shown for some options in `k3s server --help`.

**Comment by brandond** [comment]
We know the defaults for our CLI flags, but the actual args for the Kubernetes components vary depending on how you actually start k3s - there are not a fixed set of defaults that would be correct to print, since they are determined at runtime.
