### ISSUE TITLE
Error 503 while fetching logs with kubectl

### ISSUE THREAD

**Issue by SimoneLazzaris** [k3s-io/k3s#8495]
**Environmental Info:**
K3s Version: 
```
k3s version v1.26.3+k3s1 (01ea3ff2)
go version go1.19.7
```

Node(s) CPU architecture, OS, and Version: 
```
Linux ktest 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

Cluster Configuration:
Simplest configuration: just one server node.

**Describe the bug:**

After I bind kubelet to the node IP (172.31.255.18) as suggested [here](https://github.com/k3s-io/k3s/issues/2489), I can't get logs with kubectl logs:
```sh
$ kubectl logs -n monitoring prom-grafana-bbc485665-f85gb 
Defaulted container "grafana-sc-dashboard" out of: grafana-sc-dashboard, grafana-sc-datasources, grafana
Error from server: Get "https://172.31.255.18:10250/containerLogs/monitoring/prom-grafana-bbc485665-f85gb/grafana-sc-dashboard": proxy error from 127.0.0.1:6443 while dialing 172.31.255.18:10250, code 503: 503 Service Unavailable
```

To have them back, I have to enable workaround suggested [here](https://github.com/k3s-io/k3s/issues/6698) and add `--egress-selector-mode=disabled` to k3s systemd service.

**Steps To Reproduce:**

- Install k3s without any flags or env variable set.
- I didn't want to have kubelet listening on 0.0.0.0, so I added this `config.yaml` file to `/etc/ranched/k3s`:
```yaml
kubelet-arg:
  - "address=172.31.255.18"
```
- restart k3s.service
- kubectl logs -n kube-system whatever

**Expected behavior:**
I wanted to:
- have logs
- prevent kubelet from binding to the public IP address (this environment is a test environment, in production the node will have also a public IP and I don't want kubelet to bind there).

**Actual behavior:**

For some reasons, if I don't use the `--egress-selector-mode=disabled` trick, I'm not able to exec into pods or extracts logs from there.

**Additional context / logs:**
I've found this in syslog:
```
Sep 28 15:03:23 ktest k3s[23161]: E0928 15:03:23.214587   23161 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://172.31.255.18:10250/containerLogs/monitoring/prom-grafana-bbc485665-f85gb/grafana-sc-dashboard", Err:(*errors.errorString)(0xc0161e1930)}: Get "https://172.31.255.18:10250/containerLogs/monitoring/prom-grafana-bbc485665-f85gb/grafana-sc-dashboard": proxy error from 127.0.0.1:6443 while dialing 172.31.255.18:10250, code 503: 503 Service Unavailable
```

**Comment by SimoneLazzaris** [comment]
I've also tried to set `no_proxy` in `/etc/systemd/system/k3s.service.env` but without success:
```sh
no_proxy=172.31.71.200/24,127.0.0.1,localhost
NO_PROXY=172.31.71.200/24,127.0.0.1,localhost
```

**Comment by brandond** [comment]
If you override the kubelet bind address like that, other components that manage communication within the cluster will not be aware of it, and in particular the agent tunnel will break. In that case, setting `--egress-selector-mode=disabled` is the correct fix - but be aware that you will no longer be able to use the agent tunnel for apiserver->kubelet communication, and will instead need to open port 10250 on your agents to inbound connections from server nodes.
