### ISSUE TITLE
Port 10260 is unaccounted for in k3s v1.27.3+k3s1

### ISSUE THREAD

**Issue by safderali5** [k3s-io/k3s#8508]
**Environmental Info:**
K3s Version: 1.27.3+k3s1

Node(s) CPU architecture, OS, and Version: 
Redhat 8.8, AMD64

Cluster Configuration:
Single node K3s cluster with traefik and helm-controller disabled.

**Describe the bug:**
There is port listening on k3s main process 10260 for which there is no information in documentation or anywhere in the internet. This is has been verified in multiple times. The following command shows.

$ sudo netstat -nlp
tcp6       0      0 :::10260                :::*                    LISTEN      7555/k3s server   

**Steps To Reproduce:**
Install k3s 1.27.3+k3s1 with traefik and helm-controller disabled. check the open ports using
sudo netstat -nlp

**Comment by brandond** [comment]
This is the default port used by the upstream Kubernetes cloud controller manager webhook. Ref: https://github.com/kubernetes/cloud-provider/blob/master/options/webhook.go#L36

```
Webhook serving flags:
      --webhook-bind-address ip
                The IP address on which to listen for the --webhook-secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If set to an unspecified address
                (0.0.0.0 or ::), all interfaces will be used. If unset, defaults to 0.0.0.0. (default 0.0.0.0)
      --webhook-cert-dir string
                The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored.
      --webhook-secure-port int
                Secure port to serve cloud provider webhooks. If unset, defaults to 10260. (default 10260)
      --webhook-tls-cert-file string
                File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided,
                a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --webhook-tls-private-key-file string
                File containing the default x509 private key matching --tls-cert-file.
```

If you want to turn it off, you can start k3s with `--kube-cloud-controller-manager-arg=webhook-secure-port=0`
