### ISSUE TITLE
rootless not considering CONTAINERD_ADDRESS to set containerd.sock

### ISSUE THREAD

**Issue by glaudiston** [k3s-io/k3s#8512]
**Environmental Info:**
K3s Version: 

k3s --version
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 

Linux ca372nt 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single node rootless

**Describe the bug:**

k3s is not taking into account the `CONTAINERD_ADDRESS` environment variable set in the user `systemd` service file to create and manage the `containerd.sock` file. Instead it is always using `/run/k3s/containerd/containerd.sock` that is not writable from non-root user. 
This cause issues with `ctr` commands

**Steps To Reproduce:**

- Download k3s binary
- Create a rootless systemd service file like: https://github.com/k3s-io/k3s/blob/master/k3s-rootless.service
- Set the environment variable on service file like:
```
Environment=CONTAINERD_ADDRESS=~/containerd.sock
```
- reload and restart the user service config file: 
```
systemctl --user daemon-reload
systemctl --user restart k3s-rootless
```

**Expected behavior:**

Expect to create the `${HOME}/containerd.sock` file allowing everything be in a user managed realm;

**Actual behavior:**

```
$ ps -fe | grep containerd.sock
ggs       102868  102068  0 10:57 ?        00:00:00 /home/ggs/.rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin/containerd-shim-runc-v2 -namespace k8s.io -id b0a89e5d9f19affe1616fcf91003fec470aeea046c58d7cb59e1c4f8893384ac -address /run/k3s/containerd/containerd.sock
ggs       102869  102068  0 10:57 ?        00:00:00 /home/ggs/.rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin/containerd-shim-runc-v2 -namespace k8s.io -id 768203e2e0bfc30bf067618bcabde7396ac8ac1c70d045fbf9daeb8821d6778a -address /run/k3s/containerd/containerd.sock
ggs       102881  102068  0 10:57 ?        00:00:00 /home/ggs/.rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin/containerd-shim-runc-v2 -namespace k8s.io -id be6b1069e0a2c8b7a975ab99e77669e64ca114533d8205f30a8009d092ce766a -address /run/k3s/containerd/containerd.sock
```
* All user started process still look at `/run/k3s/containerd/containerd.sock` that is not something a non-privileged user can create or manage.
```
ctr image list
ctr: failed to dial "/run/k3s/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///run/k3s/containerd/containerd.sock: timeout"
```
* ctr can not manage or list images;

**Additional context / logs:**

I made it work by creating a symlink as the root user pointing `/run/k3s` to somewhere where the user can read/write. But this is not optional as we need root for that, and it is not persistent, so after every reboot, we need to recreate that link or set some service to do that, which is not allowed for some restricted environments.

**Comment by brandond** [comment]
> k3s is not taking into account the `CONTAINERD_ADDRESS` environment variable set in the user `systemd` service file to create and manage the `containerd.sock` file. Instead it is always using `/run/k3s/containerd/containerd.sock` that is not writable from non-root user. 

This isn't an environment variable or CLI flag that we support - why were you expecting it to do anything? The only flag that changes the CRI socket path is the --container-runtime-endpoint flag, which disables the built-in containerd.

The problem with accessing the rootless CRI socket is not about permissions. If you have a /run/k3s on your system, it is not coming from rootless k3s, but rather is left over from a previous standard execution of k3s.

The problem you're running into is that rootless k3s runs in a different set of namespaces that are not accessible from the  namespace that your shell is running in. Since it's in a differnent mount namespace, you actually can't even see it from a shell. You must use `nsenter` to join the namespaces that k3s and containerd are running in.

```console
ubuntu@ip-172-31-5-176:~$ journalctl --user -u k3s-rootless | grep "Running containerd"
Sep 30 18:50:59 ip-172-31-5-176 k3s[129728]: time="2023-09-30T18:50:59Z" level=info msg="Running containerd -c /home/ubuntu/.rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /home/ubuntu/.rancher/k3s/agent/containerd"

ubuntu@ip-172-31-5-176:~$ ls -la /run/k3s/containerd
ls: cannot access '/run/k3s/containerd': No such file or directory

ubuntu@ip-172-31-5-176:~$ nsenter --pid --user --mount --target $(pgrep --full "/proc/self/exe init") ls -la /run/k3s/containerd
total 0
drwx--x--x 5 root root 140 Sep 30 18:51 .
drwx--x--x 3 root root  60 Sep 30 18:50 ..
srw-rw---- 1 root root   0 Sep 30 18:50 containerd.sock
srw-rw---- 1 root root   0 Sep 30 18:50 containerd.sock.ttrpc
drwxr-xr-x 4 root root  80 Sep 30 18:51 io.containerd.grpc.v1.cri
drwx--x--x 2 root root  40 Sep 30 18:50 io.containerd.runtime.v1.linux
drwx--x--x 3 root root  60 Sep 30 18:51 io.containerd.runtime.v2.task

lrwxrwxrwx 1 root root 3 Sep 30 18:50 /home/ubuntu/.rancher/k3s/data/current/bin/crictl -> k3s
ubuntu@ip-172-31-5-176:~$ nsenter --pid --user --mount --target $(pgrep --full "/proc/self/exe init") $HOME/.rancher/k3s/data/current/bin/crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                     ATTEMPT             POD ID              POD
6774e6c7d9644       d1e26b5f8193d       About an hour ago   Running             traefik                  0                   1e05f28f174da       traefik-7bf7d7576d-89bqs
9ce559d1d1ae8       af74bd845c4a8       About an hour ago   Running             lb-tcp-443               0                   e12f86bec4030       svclb-traefik-d1b86f7d-rt6hw
18ec51132fcf6       af74bd845c4a8       About an hour ago   Running             lb-tcp-80                0                   e12f86bec4030       svclb-traefik-d1b86f7d-rt6hw
399e1e6ff300b       817bbe3f2e517       About an hour ago   Running             metrics-server           0                   b40984c463efb       metrics-server-67c658944b-5ds4p
b92772fd0030b       b29384aeb4b13       About an hour ago   Running             local-path-provisioner   0                   7b10c6de1ff5f       local-path-provisioner-84db5d44d9-q4qmb
bee30b41830cb       ead0a4a53df89       About an hour ago   Running             coredns                  0                   b5040c5d96075       coredns-6799fbcd5-kv82v

```

**Comment by brandond** [comment]
I'm honestly confused why you're trying to poke at the rootless containerd using crictl though, what is your use case? What is it that you are trying to do that is not possible via the Kubernetes API?
