### ISSUE TITLE
`get.k3s.io` with freebsd-rc?

### ISSUE THREAD

**Issue by Trung0246** [k3s-io/k3s#8513]
**Is your feature request related to a problem? Please describe.**

Currently only systemctl and openrc are supported for the setup script. Adding freebsd-rc is needed for k3s to successfully install on freebsd.

**Describe the solution you'd like**

I guess somehow add support for freebsd-rc.

**Describe alternatives you've considered**

I have tried to modify the script by myself but not sure how to start modify it correctly.

**Additional context**

None

**Comment by cwayne18** [comment]
We will certainly accept and work with anyone in the community adding this functionality, but it's unlikely something we'll be able to prioritize as a team. I say this without any sarcasm, patches are very welcome here 🙂

**Comment by Trung0246** [comment]
> We will certainly accept and work with anyone in the community adding this functionality, but it's unlikely something we'll be able to prioritize as a team. I say this without any sarcasm, patches are very welcome here 🙂

Hm is the currently binary already support freebsd? If so I guess I could somehow makearoung with it

**Comment by brandond** [comment]
We only support Linux, with Windows a work in progress. I'm not aware of kubernetes, containerd, or runc working on freebsd at all, as the kernel cgroup stuff that both depend on do not (to the best of my knowledge) exit at all on bsd.

The control-plane bits would probably work OK, allowing you to run `k3s server --disable-agent`, assuming your system is set up to run Linux executables. K3s is statically linked and actually stands a decent chance of working.

**Comment by Trung0246** [comment]
Ping

**Comment by cwayne18** [comment]
Until someone does the work to make upstream containerd/k8s work properly on freebsd there's not a lot that we can do here. That said, we're open to any PRs that would enable this, but it's not something currently on our roadmap
