### ISSUE TITLE
tool for gathering system logs and configuration information

### ISSUE THREAD

**Issue by cjellick** [k3s-io/k3s#856]
we need a tool that users can run to collect logs and other system configuration information to help us debug problems

**Comment by blaise-sumo** [comment]
Thank you @cjellick ! I was just going to ask about that. Yesterday I noticed this:
```
[INFO]  systemd: Starting k3s-agent
Logs: which: no kubectl in (/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
which: no crictl in (/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
which: no ctr in (/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
Created symlink /etc/systemd/system/multi-user.target.wants/k3s-agent.service → /etc/systemd/system/k3s-agent.service.
```
it looks to me like this may be a mixture of log `INFO` content and `std.err` content? 
So I was going to investigate what was available in terms of observability and how to turn it on.
Disclosure: I'm new to `golang` but I have a great interest in logging and some <cough>resources</cough> that I might be able to contribute towards this problem. Feel free to DM me if you prefer.

**Comment by blaise-sumo** [comment]
I wonder if this would help https://github.com/rancher/k3s/issues/928 ?

**Comment by brandond** [comment]
* We have https://github.com/k3s-io/k3s/blob/master/contrib/util/fetch-diags.sh from https://github.com/k3s-io/k3s/pull/2526 but we don't really make use of it ever. I think we can close this out, and follow up with a docs issue or modification to the bug report issue template if we want to make better use of it.
