### ISSUE TITLE
[Epic] Remove multiclusterCIDR flag

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#8563]
**Is your feature request related to a problem? Please describe.**

The `multiclusterCIDR` alpha feature will be removed https://groups.google.com/g/kubernetes-sig-network/c/nts1xEZ--gQ/m/2aTOUNFFAAAJ so we should remove it also from K3s.

**Describe the solution you'd like**

Remove flag and its support from K3s.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShylajaDevadiga** [comment]
### Validated on k3s version v1.28.4-rc1+k3s1 (3f237230)
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Configuration:*
Single node

*Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
write-kubeconfig-mode: "0644"
multi-cluster-cidr: true
```
## Steps to validate the fix
1. Copy config.yaml
2. Install k3s

**Validation results:**
```
$ k3s -v
k3s version v1.28.4-rc1+k3s1 (3f237230)
go version go1.20.11

$ sudo journalctl -u k3s|grep multiClusterCIDR
Nov 27 22:52:21 ip-172-31-14-46 k3s[5228]: time="2023-11-27T22:52:21Z" level=warning msg="multiClusterCIDR alpha feature will be removed in future releases"
```

**Comment by ShylajaDevadiga** [comment]
Keeping Epic issue open until flag is removed.

**Comment by ShylajaDevadiga** [comment]
PR to remove multiclusterCIDR flag https://github.com/k3s-io/k3s/pull/9075

**Comment by ShylajaDevadiga** [comment]
Validated in the scope of https://github.com/k3s-io/k3s/issues/9074
