### ISSUE TITLE
K3s not building due to wrong install.sh sha

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#8565]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

[install.sh](https://github.com/k3s-io/k3s/blob/master/install.sh) was updated but [install.sh.sha256sum](https://github.com/k3s-io/k3s/blob/master/install.sh.sha256sum) was not. As a consequence, the validation fails and k3s does not build

**Steps To Reproduce:**

- Installed K3s: 

Try to build k3s

**Expected behavior:**

K3s builds correctly

**Actual behavior:**

k3s does not build and fails with:
```
Running: install script signature checks
install.sh: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
FATA[0076] exit status 1
```

**Additional context / logs:**

**Comment by dereknola** [comment]
Nothing to QA, closing issue
