### ISSUE TITLE
k3s check-config fails on MicroOS DVD

### ISSUE THREAD

**Issue by grisu48** [k3s-io/k3s#8585]
By default, the MicroOS DVD installer installs `busybox-gzip` instead of `gzip` and this breaks `k3s check-config`.

Output of k3s there: [k3s.txt](https://github.com/k3s-io/k3s/files/12869261/k3s.txt)

**Environmental Info:**
K3s Version: 
```
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux microos 6.5.6-1-default #1 SMP PREEMPT_DYNAMIC Fri Oct  6 11:20:48 UTC 2023 (c97c2df) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

Single node cluster

**Describe the bug:**

With `busybox-gzip` in place, the `k3s check-config` script appears to be broken. With `gzip` installed instead, it works nicely.

We believe the usage of `zgrep` in https://github.com/k3s-io/k3s/blob/master/contrib/util/check-config.sh#L36 might be the culprit.

**Steps To Reproduce:**

* On MicroOS, check that `busybox-gzip` is installed (this is the default for the MicroOS DVD)
* Install k3s
* Start the node
* Run `k3s check-config`

**Expected behavior:**

`k3s check-config` runs normally

**Actual behavior:**

`k3s check-config` is not able to perform any checks.

**Additional context / logs:**

* See https://bugzilla.opensuse.org/show_bug.cgi?id=1215943
* Failing openQA test runs, e.g. https://openqa.opensuse.org/tests/3636499#step/podman_pods/200

EDIT: It was stated previously that this applies to Tumbleweed. No, it applies to MicroOS (DVD).

**Comment by grisu48** [comment]
Hey @brandond - the full error output is here: https://github.com/k3s-io/k3s/files/12869261/k3s.txt. Let me know if you need something more.

I cannot tell you why the decision for `busybox-gzip` was made, I can only say that on a fresh Tumbleweed host using the DVD installation, `k3s check-config` fails: https://openqa.opensuse.org/tests/3642422#step/podman_pods/203

**Comment by VestigeJ** [comment]
Due to the nature of my installation from the zypper package for busybox utils https://software.opensuse.org/package/busybox I needed to alias gzip="busybox gzip " in order to try and reproduce this on aws the default tumbleweed AMI does not have that version of gzip so I rm'd that sudo rm /usr/bin/gzip before installing the busybox package and creating the alias to attempt to reproduce. 

$ kgn
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1-1-1-158       Ready    control-plane,etcd,master   4m27s   v1.27.6+k3s1
```

$ kgp -A
```
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   coredns-77ccd57875-9dwkl                 1/1     Running     0          4m14s
kube-system   helm-install-traefik-crd-r8bgp           0/1     Completed   0          4m15s
kube-system   helm-install-traefik-h9gs5               0/1     Completed   1          4m15s
kube-system   local-path-provisioner-957fdf8bc-bnwps   1/1     Running     0          4m14s
kube-system   metrics-server-648b5df564-fn2zp          1/1     Running     0          4m14s
kube-system   svclb-traefik-a2bc200f-nbql8             2/2     Running     0          3m57s
kube-system   traefik-64f55bb67d-b9l65                 1/1     Running     0          3m57s
```

$ sudo /usr/local/bin/k3s check-config

```
Verifying binaries in /var/lib/rancher/k3s/data/ab2055bc72380bad965b219e8688ac02b2e1b665cad6bdde1f8f087637aa81df/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.7 (legacy): ok
- swap: disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: cgroups Hybrid mounted, cpuset|memory controllers status: good
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_MULTIPORT: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: pass
```

$ gzip --version //this bundled bin doesn't have help or version flags but it still prints it 

```
BusyBox v1.36.1 () multi-call binary.

Usage: gzip [-cfkdt] [FILE]...

Compress FILEs (or stdin)

	-d	Decompress
	-c	Write to stdout
	-f	Force
	-k	Keep input files
	-t	Test integrity
```



##Environment Details
VERSION=v1.27.6+k3s1

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*
```
Linux 5.14.14-2-default x86_64 GNU/Linux
PRETTY_NAME="openSUSE Tumbleweed"
```

*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1-1-1-158       Ready    control-plane,etcd,master   4m18s   v1.27.6+k3s1
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
profile: cis
selinux: true
protect-kernel-defaults: true
cluster-init: true
```

<details><summmary><h4>Steps</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ which gzip
$ gzip --version
$ sudo zypper update
$ sudo zypper install busybox
$ busybox gzip
$ vim .bashrc.d/glorified-aliases.sh //adding alias gzip="busybox gzip " //attention to the trailing space for additional args
$ gzip --version
$ sudo INSTALL_K3S_VERSION=v1.27.6+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ sudo /usr/local/bin/k3s check-config
$ cat /etc/os-release
```

**Results:**

</details>

**Comment by brandond** [comment]
@grisu48 is `busybox-gzip` a package, or the binary name? What is the output of `ls -la $(which gzip)` and `ls -la $(which zcat)`?

**Comment by grisu48** [comment]
Hey @brandond, sorry for the delay I was busy with other tasks.

I need to correct my initial statement, this is about MicroOS, not Tumbleweed. I updated the title and issue description accordingly.
On MicroOS by default `busybox-gzip` is installed, not `gzip` itself. As for the requested packages, all except `zgrep` are coming from `busybox`:

```
microos:~ # ls -la $(which gzip)
lrwxrwxrwx. 1 root root 7 Oct  9 07:42 /usr/bin/gzip -> busybox
microos:~ # ls -la $(which zcat)
lrwxrwxrwx. 1 root root 7 Oct  9 07:42 /usr/bin/zcat -> busybox
microos:~ # ls -la $(which zgrep)
-rwxr-xr-x. 1 root root 3806 Oct  9 07:42 /usr/bin/zgrep
```

Looks like the issue arises from using `busybox` on MicroOS.

**Comment by ggardet** [comment]
The problem is likely because `grep` from busybox does not support `--label=XYZ` option.

**Comment by dirkmueller** [comment]
> The problem is likely because `grep` from busybox does not support `--label=XYZ` option.

this issue has been resolved.

**Comment by grisu48** [comment]
> > The problem is likely because `grep` from busybox does not support `--label=XYZ` option.
> 
> this issue has been resolved.

https://openqa.opensuse.org/tests/3750096#step/podman_pods/201 shows that it is not, at least not in build 20231122:

```
# wait_serial expected: qr/QVGg3-\d+-/u
...
grep: unrecognized option: label=/proc/config.gz
```

**Comment by DimStar77** [comment]
> > > The problem is likely because `grep` from busybox does not support `--label=XYZ` option.
> > 
> > 
> > this issue has been resolved.
> 
> https://openqa.opensuse.org/tests/3750096#step/podman_pods/201 shows that it is not, at least not in build 20231122:

IMHO, not a k3s issue at all - see: https://bugzilla.opensuse.org/show_bug.cgi?id=1215943

the 'zgrep' shipped as part of busybox-gzip assumes gnu gzip, but does not support busybox-gzip; A proposal fix was submitted, but not yet accepted by the maintainer

**Comment by dirkmueller** [comment]
Agreed, let's not do a workaround in k3s for suse contributing distributions. We're going to fix this in microos
