### ISSUE TITLE
Missing kube-router version

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#8586]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

The string version on the logs for the network policy controller is empty
```
level=info msg="Starting the netpol controller version , built on , go1.20.8"
```
**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

The log should contain the right version

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
The kube-router package has changed to /v2 and needs to be updated in the build script:

https://github.com/k3s-io/k3s/blob/3abc8b82ed0779ebaa5d0ca00165408ad085cc8f/go.mod#L8
https://github.com/k3s-io/k3s/blob/3abc8b82ed0779ebaa5d0ca00165408ad085cc8f/scripts/build#L16

**Comment by VestigeJ** [comment]
Confirmed via go-mod action here - https://github.com/VestigeJ/distros-test-framework/actions/runs/6513776285 - that both kube-router go.mod version bumped and build script https://github.com/k3s-io/k3s/blob/7bb4a826af92c8ad1c1f59ca11792478bd5a72a1/scripts/build#L16C60-L16C60 are up to date for this issue
