### ISSUE TITLE
curl install script should run k3s check-config and warn users of issues

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#866]
It would be nice if the k3s curl install script could run check-config and warn users of issues.

eg: SWAP is not suggested it will break things i.e. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ (search for "swap") (also note there is a discussion here  https://github.com/kubernetes/kubernetes/issues/53533)

**Comment by caroline-suse-rancher** [comment]
Closing due to age
