### ISSUE TITLE
error on parsing registries.yaml

### ISSUE THREAD

**Issue by lauksas** [k3s-io/k3s#8677]
**Environmental Info:**
K3s Version: 
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 
Linux local 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server no agent, standalone

**Describe the bug:**
The configuration I set in my registries.yaml are note taking effect. I see the below error in journalctl:

```
Oct 17 11:01:36 local k3s[19059]: time="2023-10-17T11:01:36-03:00" level=error msg="Failed to process config: failed to process /root/k3s/server/manifests/registries.yaml: Object 'Kind' is missing in '{\"configs\":{\"registry.cube.local:5000\":{\"tls\":{\"insecure_skip_verify\":true}}},\"mirrors\":{\"registry.cube.local:5000\":{\"endpoint\":[\"http://registry.cube.local:5000\"]}}}'"
```
A previous set up with same installation and config steps worked as documented, however due to lack of disk space had to reinstall in a different location where this problem started.

**Steps To Reproduce:**

- issued `export K3S_TOKEN=xxxxxx`
- Installed K3s with `curl -sfL https://get.k3s.io/ | sh -s - --data-dir=/root/k3s/`
- installed private registry helm chart: `helm upgrade --install registry twuni/docker-registry	--namespace container-registry --create-namespace --values=values.yaml`
- pushed an image to the private registry
- configured /root/k3s/server/manifests/registries.yaml as below
```
mirrors:
  "registry.cube.local:5000":
    endpoint:
      - "http://registry.cube.local:5000"
```
- tried to create a pod with same image, pod is in `ImagePullBackOff` state.
- describe pod with error, verify it is trying to pull using https
- issue `journalctl -xn -u k3s.service` and see "Object 'Kind' is missing" error message previously shared.

**Expected behavior:**

k3s should read the registries.yaml file without any issues as documentation says
**Actual behavior:**

k3s complain about an object "kind" in the yaml which is not documented anywhere.
**Additional context / logs:**

This actually happened to any configuration I do to registries.yaml, I even tried configuring another external private registry, no luck.
I uninstalled and downgraded to the version below, which I think it was the one working before, but issue still persists.
k3s version v1.24.16+k3s1 (ccae12ed)
go version go1.20.6

**Comment by brandond** [comment]
> `--data-dir=/root/k3s/`
> `/root/k3s/server/manifests/registries.yaml`

registries.yaml doesn't go in the manifests dir; it is not a Kubernetes manifest to be deployed. Even if you've changed the data-dir to /root/k3s, registries.yaml still goes in /etc/rancher/k3s/registries.yaml. `--data-dir` only relocates /var/lib/rancher/k3s to the specified path.
