### ISSUE TITLE
K3s crashing instantly  building kine: commands out of sync

### ISSUE THREAD

**Issue by KornKalle** [k3s-io/k3s#8716]
**Environmental Info:**
K3s Version: 
k3s version v1.26.8+k3s1 (631bb3f0)
go version go1.20.7

Node(s) CPU architecture, OS, and Version: 
Linux XXXX 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

Cluster Configuration:
5 nodes, all control/master. Every node is configured identically (Cloned from the same template and configured via ansible)
Storage backend is mariaDB.

**Describe the bug:**
On 1 of our nodes k3s stopped working abruptly. A reboot once helped but it started crashing again. I don't get any logs except this: 
```
INFO[0000] Starting k3s v1.26.8+k3s1 (631bb3f0)         
FATA[0000] starting kubernetes: preparing server: creating storage endpoint: building kine: commands out of sync. Did you run multiple statements at once? 
```

**Steps To Reproduce:**
- Installed K3s
- Was running for ~4 weeks
- Started crashing, but I really don't know when and why.

**Expected behavior:**
Either k3s running or a detailed error message.

**Actual behavior:**
k3s just crashes and does not do anything. I could not manage to find any explanation for this error message or getting further information.

**Comment by brandond** [comment]
The error message is coming from the database engine. I would check the mariadb log for errors.

**Comment by KornKalle** [comment]
Sorry for the delay, i had to postpone debugging this cluster.

The MariaDB Server says:
`Aborted connection 10303290 to db: 'unconnected' user: 'unauthenticated' host: '10.XX.XX.XX' (This connection closed normally without authentication)`

Which is strange as the config.yaml of k3s did not change and is identical on all nodes. Today a second node started showing the same behavior.
Do the credentials get los somewhere?

**Comment by KornKalle** [comment]
Nevermind. A simple restart of the mariadb instance solved this issue.
