### ISSUE TITLE
[v1.28.3+k3s1] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

### ISSUE THREAD

**Issue by stefan-lange** [k3s-io/k3s#8754]
**Environmental Info:**
K3s Version: 
v1.28.3+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux docker2 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

Cluster Configuration:
1 server, 1 agent
NVidia GPU installed, working fine before update from v1.28.2+k3s1

**Describe the bug:**
Startup fails
Log from `journalctl -xeu k3s.service`
`Nov 01 10:03:02 docker2 k3s[1314]: time="2023-11-01T10:03:02+01:00" level=fatal msg="template: compiled_template:119:21: executing \"compiled_template\" at <.SystemdCgroup>: can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"`

**Steps To Reproduce:**
- Installed K3s:  v1.28.2+k3s1
- Install NVIDIA GPU
- sudo apt-get update
- sudo apt install nvidia-container-toolkit \
                           nvidia-container-runtime
- upgrade to `v1.28.3+k3s1`

**Expected behavior:**
k3s starts without error

**Actual behavior:**
k3s starts exits with fatal error

**Additional context / logs:**
This commit might be the issue: https://github.com/k3s-io/k3s/pull/8470/files
(`{{ .SystemdCgroup }}` => `{{ $v.SystemdCgroup }}` ?)

**Comment by larivierec** [comment]
can confirm, i'm getting this on my node using an nvidia GPU

**Comment by tete1030** [comment]
Same. Made a PR #8761, should fix the problem

**Comment by elraro** [comment]
can confirm this bug. Waiting for the new release!

**Comment by Tylermarques** [comment]
Same bug here. Node with Nvidia GPU refuses to come back up. 

```
time="2023-11-02T10:41:37-04:00" level=info msg="Found nvidia container runtime at /usr/local/nvidia/toolkit/nvidia-container-runtime"
time="2023-11-02T10:41:37-04:00" level=info msg="Found nvidia-experimental container runtime at /usr/local/nvidia/toolkit/nvidia-container-runtime-experimental"
time="2023-11-02T10:41:37-04:00" level=fatal msg="template: compiled_template:119:21: executing \"compiled_template\" at <.SystemdCgroup>: can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"
systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by dbv** [comment]
I1103 10:50:25.504398   11560 shared_informer.go:318] Caches are synced for configmaps
I1103 10:50:25.504464   11560 shared_informer.go:318] Caches are synced for cluster_authentication_trust_controller
I1103 10:50:25.504478   11560 cache.go:39] Caches are synced for AvailableConditionController controller
I1103 10:50:25.504478   11560 shared_informer.go:318] Caches are synced for crd-autoregister
I1103 10:50:25.504515   11560 aggregator.go:152] initial CRD sync complete...
I1103 10:50:25.504525   11560 autoregister_controller.go:141] Starting autoregister controller
I1103 10:50:25.504571   11560 cache.go:32] Waiting for caches to sync for autoregister controller
I1103 10:50:25.504579   11560 cache.go:39] Caches are synced for autoregister controller
I1103 10:50:25.504529   11560 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1103 10:50:25.504543   11560 apf_controller.go:378] Running API Priority and Fairness config worker
I1103 10:50:25.504830   11560 apf_controller.go:381] Running API Priority and Fairness periodic rebalancing process
INFO[0001] certificate CN=system:node:vm-251-252-tencentos,O=system:nodes signed by CN=k3s-client-ca@1698979431: notBefore=2023-11-03 02:43:51 +0000 UTC notAfter=2024-11-02 02:50:25 +0000 UTC
INFO[0001] Module overlay was already loaded
INFO[0001] Module nf_conntrack was already loaded
INFO[0001] Module iptable_nat was already loaded
INFO[0001] Module iptable_filter was already loaded
INFO[0001] Found nvidia container runtime at /usr/bin/nvidia-container-runtime
FATA[0001] template: compiled_template:119:21: executing "compiled_template" at <.SystemdCgroup>: can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig

**Comment by jaredallard** [comment]
Will a new release go out today? Totally understandable if not. Just trying to figure out if I need to build from the head branch today or not :D

**Comment by VestigeJ** [comment]
@jaredallard I can't make any promises about today - we're building pre-release assets now but if you have a workload you'd like to test you can install with COMMIT_ID this is not for production but just testing though. Use at your own risk. 

CLI flag
```
INSTALL_K3S_COMMIT=1ae053d9447229daf8bbd2cd5adf89234e203bcc
```

**Comment by jaredallard** [comment]
> @jaredallard I can't make any promises about today - we're building pre-release assets now but if you have a workload you'd like to test you can install with COMMIT_ID this is not for production but just testing though. Use at your own risk. If you don't want to run this I understand but if you do have sample workloads that are shareable I'd be happy to test deploying them. Unfortunately a lot of the Nvidia samples are very hardware driver sensitive.
> 
> CLI flag
> 
> ```
> INSTALL_K3S_COMMIT=1ae053d9447229daf8bbd2cd5adf89234e203bcc
> ```

Thank you! I'll give that a shot and keep the thread updated!

**Comment by jaredallard** [comment]
That got the node running at least, but looks like container creation is still borked:

```
  Warning  Failed     4s (x2 over 5s)   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
```

**Driver Information**

* Version: `535.129.03-0ubuntu0.23.04.1`
* OS: `Ubuntu 23.04"`
  
I will keep playing around with it.

**Comment by jaredallard** [comment]
Update on that, seems like it might've been localized to my node. Restarted it and everything seems fine now 🤷

**Comment by VestigeJ** [comment]
Just had a good single node example parallel steps but on rke2 - https://github.com/rancher/rke2/issues/4984#issuecomment-1792932663

**Comment by VestigeJ** [comment]
This commit jump shows the helm chart bump on Traefik which will cause the gpu-operator to restart until Traefik install completes. 



##Environment Details
Reproduced using VERSION=v1.28.2+k3s1
Validated using COMMIT=1ae053d9447229daf8bbd2cd5adf89234e203bcc

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*

```
Linux 5.15.0-1045-aws x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE   VERSION
ip-10-11-16-71     Ready    control-plane,etcd,master   10m   v1.28.3+k3s-1ae053d9
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
node-external-ip: 10.11.16.71
cluster-init: true
```

<details><summmary><h4>Validation, workloads</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.28.2+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgp -A // kubectl get pods -A
$ helm repo add nvidia https://helm.ngc.nvidia.com/nvidia; helm repo update;
$ helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.nvidiaDriverCRD.enabled=true
$ kubectl create -f usually.yaml
$ sudo apt update
$ sudo apt install nvidia-container-toolkit nvidia-container-runtime
$ sudo INSTALL_K3S_COMMIT=1ae053d9447229daf8bbd2cd5adf89234e203bcc INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kubectl create -f cuda-sample-2004.yaml
$ kubectl logs pod/gpu-operator-574bbc7b5c-76zvz -n gpu-operator
```

**Results:**

$ k logs pod/test-cuda-vector-add

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

$ kubectl get pods -A

```
NAMESPACE      NAME                                                                  READY   STATUS      RESTARTS        AGE
default        pod/test-cuda-vector-add                                              0/1     Completed   0               7m23s
default        pod/test2                                                             1/1     Running     0               12m
gpu-operator   pod/gpu-feature-discovery-jwrqw                                       1/1     Running     0               14m
gpu-operator   pod/gpu-operator-1699036389-node-feature-discovery-gc-5c8d5796b7fpv   1/1     Running     0               14m
gpu-operator   pod/gpu-operator-1699036389-node-feature-discovery-master-cd5dw2dtx   1/1     Running     0               14m
gpu-operator   pod/gpu-operator-1699036389-node-feature-discovery-worker-z4dmq       1/1     Running     0               14m
gpu-operator   pod/gpu-operator-574bbc7b5c-76zvz                                     1/1     Running     2 (8m24s ago)   14m
gpu-operator   pod/nvidia-container-toolkit-daemonset-85jvj                          1/1     Running     0               14m
gpu-operator   pod/nvidia-cuda-validator-xmrr8                                       0/1     Completed   0               13m
gpu-operator   pod/nvidia-dcgm-exporter-6vcdx                                        1/1     Running     0               14m
gpu-operator   pod/nvidia-device-plugin-daemonset-vb5wj                              1/1     Running     0               14m
gpu-operator   pod/nvidia-operator-validator-snznl                                   1/1     Running     0               14m
kube-system    pod/coredns-6799fbcd5-k8nxs                                           1/1     Running     0               16m
kube-system    pod/helm-install-traefik-crd-27pz4                                    0/1     Completed   0               8m28s
kube-system    pod/helm-install-traefik-zswz8                                        0/1     Completed   2               8m28s
kube-system    pod/local-path-provisioner-84db5d44d9-zdhtj                           1/1     Running     0               16m
kube-system    pod/metrics-server-67c658944b-lgjcg                                   1/1     Running     0               16m
kube-system    pod/svclb-traefik-5baf08af-t6sx7                                      2/2     Running     0               16m
kube-system    pod/traefik-67b97c588-qtcwb                                           1/1     Running     0               8m8s
```

</details>
