### ISSUE TITLE
Add agent option for generating a kubeconifg

### ISSUE THREAD

**Issue by cornfeedhobo** [k3s-io/k3s#8757]
**Is your feature request related to a problem? Please describe.**

`server`s write a usable config for the root user, but `agent`s don't. sometimes it's useful to be able to login to the agent nodes and still reach the control plane through the builtin proxy

**Describe the solution you'd like**

i want `agent` to write a config as well

**Describe alternatives you've considered**

someone can use `/var/lib/rancher/k3s/agent/k3scontroller.kubeconfig`, but obviously that is for the controller and an abuse of the user.

**Additional context**

Thanks for considering :)

**Comment by brandond** [comment]
Agents are unprivileged, compared to servers. They intentionally do not have access to an admin kubeconfig.
