### ISSUE TITLE
Raspberry Pi 4 Debian GNU/Linux 11 Fails to Install With no Error

### ISSUE THREAD

**Issue by BrockWeekley** [k3s-io/k3s#8796]
**Environmental Info:**
K3s Version: latest - fails on install

Node(s) CPU architecture, OS, and Version: 
Raspberry pi 4 - Linux raspberrypi-worker1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux (bullseye)

Master node (install working) -
Raspberry pi 3 - Linux raspberrypi-master 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux (bullseye)

Cluster Configuration:
1 master, 1 worker

**Describe the bug:**
From the same network, running `curl -sfL https://get.k3s.io | sh - ` works fine on the master node (rpi3), but on the worker node it does nothing::

`[INFO]  Finding release for channel stable`
`curl: (28) Failed to connect to github.com port 443: Connection timed out`
`[INFO]  Using v1.27.7+k3s1 as release`
`[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.7+k3s1/sha256sum-arm64.txt`
`pi@raspberrypi-worker1:~ $`

**Steps To Reproduce:**
From a raspberry pi 4 running bullseye, attempt to run the k3s install command `curl -sfL https://get.k3s.io | sh - `

**Expected behavior:**
The expected behavior would be for the curl to download the proper files and start the service like it does on the pi3

**Actual behavior:**
The system hangs for a long time, then ends with no error message or response

**Additional context / logs:**
I did attempt to curl and install other programs on this pi and they installed fine, leading me to think this is an issue with k3s specifically

**Comment by brandond** [comment]
> `curl: (28) Failed to connect to github.com port 443: Connection timed out`

I'm not sure what you mean by "with no error", that's your error right there. Make sure you can use curl or wget to download content from GitHub.

**Comment by BrockWeekley** [comment]
As I already mentioned in the additional context, I can curl out to other github repos fine. I used curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash as a test earlier, and that ones still works now.
The command you provided results in no message, just the verbose content ending with * Connection #0 to host github.com left intact

**Comment by brandond** [comment]
It sounds like the connectivity on that node is flakey then - I'm not sure what else would cause curl to work when you run it manually, but not when run from the install script.

You can run `curl -sfL https://get.k3s.io | sh -x -` if you want to see what curl commands it's running and try to figure out why it is sometimes not working.
