### ISSUE TITLE
Solution to the problem when deploying k3s nodes in VMware Cloud Director.

### ISSUE THREAD

**Issue by AitorMSuarez** [k3s-io/k3s#8804]
Hello,
I just want to report a problem we've solved when deploying k3s in a VMWARE CLOUD DIRECTOR environment.

We had an issue where when adding nodes, they were successfully added to the master node, but the pods deployed on the nodes were not accessible through the ingress, and when deploying something like Nginx, it would give us a gateway timeout.

In the end, after a month, the solution was to change the network interface when creating the VMs. Instead of choosing the default VMXNET3 network interface, we selected E1000E, and it worked on the first try without any further actions needed.

Best regards, and I hope this helps others.

**Comment by brandond** [comment]
This sounds like a known issue with hardware checksum offload on VMware. It affects all CNIs, not just flannel. See https://github.com/projectcalico/calico/issues/3145#issuecomment-578517597
