### ISSUE TITLE
Image pull from private registry fails because of missing credentials

### ISSUE THREAD

**Issue by danigian** [k3s-io/k3s#8808]
**Environmental Info:**
K3s Version: v1.27.7+k3s2

Node(s) CPU architecture, OS, and Version: 
Linux k3s 6.2.0-1016-azure #16~22.04.1-Ubuntu SMP Tue Oct 10 17:11:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Only 1 server

**Describe the bug:**
When trying to pull a image from a private registry the request is executed without any kind of authorization.

The secret is manually created with
`kubectl create secret generic regcred --from-file=.dockerconfigjson=dc.json --type=kubernetes.io/dockerconfigjson`

`dc.json` is a file like the following:
```json
{
    "auths": {
        "somecontainerregistry.azurecr.io": {
            "auth": "XYZ"
        }
    }
}
```
where XYZ is the base64 encoding of `:refresh_token` (there is no username as I want to dynamically get a token from a OAuth endpoint)

My pod is then specifying the `imagePullSecret` pointing to the `regcred` from above.

When creating the pod, after setting up a mitmproxy, I can see the following requests:
- HEAD to `https://somecontainerregistry.azurecr.io/v2/whateverimage/manifests/latest` which correctly fails with a 401 and returns a `Www-Authenticate` header set to `Bearer realm="https://somecontainerregistry.azurecr.io/oauth2/token",service="somecontainerregistry.azurecr.io",scope="repository:whateverimage:pull"`
- Then the request to the `/oauth2/token` endpoint is executed. The problem here is that it is executed as a GET (opposed to being a POST) and without the expected URLEncoded form including the refresh_token from the imagePullSecret.

Executing a `HTTPS_PROXY="127.0.0.1:8080" crictl pull --auth "XYZ"  somecontainerregistry.azurecr.io/whateverimage` gives me no issues and the image is pulled successfully.

**Steps To Reproduce:**
- Create an Azure Container Registry (or any image registry that is capable of OAuth AuthN)
- Setup a mitmproxy to watch the outgoing requests
- Installed K3s via quick start, then started it with HTTPS_PROXY=127.0.0.1:8080 to make sure to interject the calls with mitmproxy
- `kubectl create secret generic regcred --from-file=.dockerconfigjson=dc.json --type=kubernetes.io/dockerconfigjson` where `dc.json` is a file like the following:  
  ```json
  {
      "auths": {
          "somecontainerregistry.azurecr.io": {
              "auth": "XYZ"
          }
      }
  }
  ```  
  (and XYZ is the base64 encoding of `:refresh_token`)
- Create a Pod referencing the imagePullSecret from above
- Check in mitmproxy there are 2 requests, one of the two should be a HEAD to `/v2/whateverimage/manifests/latest` and the other should be a POST (not a GET as above)

**Expected behavior:**
I expected the kubelet and the container runtime to properly talk to each other, but I am either doing something wrong or there is a bug 😄 

**Actual behavior:**
When trying to pull a image from a private registry the request is executed without any kind of authorization.

**Comment by brandond** [comment]
I don't think it works like that. Can you show me where in the Kubernetes docs it says that you can use refresh tokens as docker creds for image pull secrets?

**Comment by danigian** [comment]
Just double checked documentation and source code.

The k8s documentation states that it is possible to:
- [login via docker login](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#log-in-to-docker-hub) (from the documentation page: "The login process creates or updates a config.json file that holds an authorization token")
- Then you [create a Secret based on the config.json](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials)

When this secret is parsed from K8S and inserted in the "BasicDockerKeyring", it apparently decodes the base64 from Auth field and only keeps its content as Username and Password fields in the keyring itself (see [here](https://github.com/kubernetes/kubernetes/blob/930022cf267c2e0269fbd9be4be3fd83448e6419/pkg/credentialprovider/keyring.go#L82))

My understanding is that the AuthConfig is the object that will be passed via the CRI to containerd.

When containerd [parses such AuthConfig](https://github.com/containerd/containerd/blob/45d7f2324d4ae4fd05e87c59a95181875dcb621b/pkg/cri/server/images/image_pull.go#L281) we are in the scenario where the AuthConfig only contains a password (no username, because I only had a refresh token in my auth). This causes the authentication parsing to return no credentials at all.

Do I understand the flow correctly?

**Comment by brandond** [comment]
That sounds correct. My understanding is that only the credentials, and not the refresh token, are usable via CRI.
