### ISSUE TITLE
K3s Air-Gap install Error "Failed to find the k3s-selinux policy"

### ISSUE THREAD

**Issue by alekseytivonchik** [k3s-io/k3s#8810]
**Environmental Info:**
K3s Version: v1.28.3+k3s2

Node(s) CPU architecture, OS, and Version: 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 12 10:45:03 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux, RHEL 9.2 (Plow)

Cluster Configuration: Single node cluster

**Describe the bug:**
Try to install k3s with Air-Gap Manually Deploy Images Method

**Steps To Reproduce:**
Follow this toturial: https://docs.k3s.io/installation/airgap
Command for install: `INSTALL_K3S_VERSION="v1.28.3+k3s2" INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh --disable=servicelb`

**Expected behavior:**
Successful installation

**Actual behavior:**
`$ INSTALL_K3S_VERSION="v1.28.3+k3s2" INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh --disable=servicelb`
`[INFO]  Skipping k3s download and verify`
`[INFO]  Skipping installation of SELinux RPM`
`[ERROR]  Failed to find the k3s-selinux policy, please install:`
`    dnf install -y container-selinux`
 `   dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/9/noarch/`

Try to follow manual
`dnf install -y container-selinux`
`Last metadata expiration check: 0:33:44 ago on Sat 11 Nov 2023 12:38:48 PM +03.`
`Package container-selinux-3:2.205.0-1.el9_2.noarch is already installed.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

Any ideas how to dix it?

**Comment by alekseytivonchik** [comment]
Fixed! Install package from
https://github.com/k3s-io/k3s-selinux/releases

**Comment by karlkovaciny** [comment]
Could we reopen this issue and ask them to fix the log message that says 

> [ERROR]  Failed to find the k3s-selinux policy, please install:
    dnf install -y container-selinux
   dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/9/noarch/

The latter link is some kind of S3 bucket that doesn't exist or I don't have permission to. Also it is to a folder and not an RPM anyway, so running it gives error `Cannot open /var/cache/dnf/commandline-0548e2de42edbce9/packages/.: Is a directory.` Should it be replaced with the link you provided, which worked for me?
