### ISSUE TITLE
1.28 Enable swap support

### ISSUE THREAD

**Issue by clcc2019** [k3s-io/k3s#8811]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
K3s has always supported swap. Is there anything specific you're asking for, beyond what's already available?

**Comment by clcc2019** [comment]
> K3s has always supported swap. Is there anything specific you're asking for, beyond what's already available?
k3s supports running on a host with swap enabled, but the node cannot allocate swap memory to run the container. The feature needs to be enabled, but --kubelet-arg cannot be set.

<img width="868" alt="image" src="https://github.com/k3s-io/k3s/assets/46099295/b857c9df-dd5a-490d-b8fb-3c4c0ed84c41">
https://kubernetes.io/blog/2023/08/24/swap-linux-beta/

**Comment by brandond** [comment]
> The feature needs to be enabled, but --kubelet-arg cannot be set.

What do you mean by "kubelet-arg cannot be set"?

For as long as `fail-swap-on` has been an available kubelet arg, K3s has set this to false. We still set it to false today. 

https://github.com/k3s-io/k3s/blob/71a3c35fb7077c5a952fbc74a9cd8dee352b1178/pkg/daemons/agent/agent_linux.go#L68

**Comment by clcc2019** [comment]
> > The feature needs to be enabled, but --kubelet-arg cannot be set.
> 
> What do you mean by "kubelet-arg cannot be set"?
> 
> For as long as `fail-swap-on` has been an available kubelet arg, K3s has set this to false. We still set it to false today.
> 
> https://github.com/k3s-io/k3s/blob/71a3c35fb7077c5a952fbc74a9cd8dee352b1178/pkg/daemons/agent/agent_linux.go#L68
> 
> What else are you asking for?

need --feature-gates=NodeSwap=true

**Comment by brandond** [comment]
ok, so use `--kubelet-arg=feature-gates=NodeSwap=true`. Unless necessary to fix an issue, we do not generally enable alpha feature-gates.

If you are using dual-stack node IPs, you'll probably have to use this instead: `--kubelet-arg=feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true"`

**Comment by clcc2019** [comment]
> ok, so use `--kubelet-arg=feature-gates=NodeSwap=true`. Unless necessary to fix an issue, we do not generally enable alpha feature-gates.
> 
> If you are using dual-stack node IPs, you'll probably have to use this instead: `--kubelet-arg=feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true`
> 
> You may also need to enable that feature-gate for other components as well, such as the scheduler and controller-manager. It depends on how support for the feature-gate is implemented.

I know this is set, but it is invalid. arg has been deprecated in 1.28. You need to use --config to specify the configuration file, but this still does not make swap effective.
<img width="779" alt="image" src="https://github.com/k3s-io/k3s/assets/46099295/4080e23a-6e55-4f4f-997f-4c4c4df3c159">

**Comment by brandond** [comment]
Deprecated means nothing. All of the kubelet args have been deprecated for years, they're not going anywhere and they work fine.

**Comment by clcc2019** [comment]
> Deprecated means nothing. All of the kubelet args have been deprecated for years, but they're not going anywhere and they work fine.
> 
> Have you actually tried it?

Yes, I tried multiple configuration methods with no success in k3s. My test on the official version of k8s was successful

**Comment by brandond** [comment]
In what way did it fail? Can you provide examples of what you were doing, and what problems you encountered?

All these things would have been good to put in the original comment when creating the issue.

**Comment by brandond** [comment]
I can confirm that the following works for me:
`curl -ksL get.k3s.io | sh -s - server --kubelet-arg=feature-gates=NodeSwap=true,CloudDualStackNodeIPs=true`

If you are unable to enable the feature-gate for some other reason, please specify EXACTLY how you are installing and configuring K3s, and what specifically is not working.
