### ISSUE TITLE
With VLAN private subnet, server is added to node under rerouted IP, not private subnet IP

### ISSUE THREAD

**Issue by edwardteach42** [k3s-io/k3s#8813]
**Environmental Info:**
K3s Version: v1.27.7+k3s2

Node(s) CPU architecture, OS, and Version: 
Ubuntu 22.04 xeon

Cluster Configuration:
1 Server, 1 Agent (for now)

**Describe the bug:**
When the server address is a VLAN, the load balancer is sending traffic to rerouted IP of the vlan, not the private subnet.  This results in the request for the certificates through the load balancer being rejected.  I cant connect to the server from the node using `curl -vk https://SERVER_IP_HIDDEN:6443/cacerts` but can with `curl -vk https://10.0.0.1:6443/cacerts`.

Interestingly, the node still shows as ready on the server.

**Steps To Reproduce:**
- Installed K3s: 
- Attempt to connect ks3 agent to working server

**Expected behavior:**
load balancer connects to the server through the vlan ip, not the rerouted ip of the vlan.

**Actual behavior:**
CA cert validation fails.

**Additional context / logs:**
Here is the output of: `sudo k3s agent -s https://10.0.0.1:6443 -t K10....3f48`

```
INFO[0000] Starting k3s agent v1.27.7+k3s2 (575bce76)   
INFO[0000] Adding server to load balancer k3s-agent-load-balancer: 10.0.0.1:6443 
INFO[0000] Adding server to load balancer k3s-agent-load-balancer: SERVER_IP_HIDDEN:6443 
INFO[0000] Removing server from load balancer k3s-agent-load-balancer: 10.0.0.1:6443 
INFO[0000] Running load balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [SERVER_IP_HIDDEN:6443] [default: 10.0.0.1:6443] 
ERRO[0020] failed to get CA certs: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
ERRO[0032] CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0044] Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0064] Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0074] Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0084] Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get "https://127.0.0.1:6444/v1-k3s/config": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0094] Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
INFO[0104] Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get "https://127.0.0.1:6444/v1-k3s/config": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Here is my override.conf:

```
[Service]
ExecStart=
ExecStart=/usr/local/bin/k3s agent  -s https://10.0.0.1:6443 -t K...8 --node-ip 10.0.0.2 --node-external-ip NODE_IP_HIDDEN --flannel-iface eno1
```

**Comment by edwardteach42** [comment]
To follow up, I have tried the same configuration on a host that does not use VLAN and everything works as expected.

**Comment by brandond** [comment]
You should configure the server to use the IPs you want agents to connect to. The address specified by  `--server` flag on the agent is only used for the initial connection; agents will discover server addresses and connect to all servers in the cluster using their primary node IP, or at the external IP if `--node-external-ip `is set. This is expected behavior. You can also set `--advertise-ip`.
