### ISSUE TITLE
Coredns many WARNING

### ISSUE THREAD

**Issue by clcc2019** [k3s-io/k3s#8814]
<img width="1217" alt="image" src="https://github.com/k3s-io/k3s/assets/46099295/3b76f98a-ac54-4bec-9e67-2cdf8ffdc473">

**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Duplicate of
* https://github.com/k3s-io/k3s/issues/4919
* https://github.com/coredns/coredns/issues/3600
