### ISSUE TITLE
Remotedialer proxy error when using Google Cloud VM as k3s server

### ISSUE THREAD

**Issue by ashrafgt** [k3s-io/k3s#882]
**k3s version v0.9.1 (755bd1c6)**

After setting up a k3s server in a Google VM and adding a TCP firewall ingress rule for port 6443, m
While attempting to add remote agents to the k3s cluster, I get a connection timeout with the errors:
`Failed to connect to proxy  error="dial tcp 10.156.0.2:6443: connect: connection timed out"`
`Remotedialer proxy error  error="dial tcp 10.156.0.2:6443: connect: connection timed out"`

**Steps to reproduce the behavior:**
1- Create a GCP ubuntu VM, reserve a static external IP
2- Install then start k3s without agent
`
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent --write-kubeconfig-mode 644 --tls-san xxx.xxx.xxx.xxx" sh -
`
2- Add a TCP firewall rule for port 6443
3- Install k3s on a remote machine and connect to the cluster via token
`
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
sudo k3s agent --server https://xxx.xxx.xxx.xxx:6443 --token $NODE_TOKEN
`

What could be causing the timeout and could you please share possible solutions.
Thank you.

**Comment by vishuPPatel** [comment]
same issue i face.

raspberrypi k3s[1727]: time="2020-01-29T11:52:17.306799547Z" level=info msg="Connecting to proxy" url="wss://10.160.0.53:6443/v1-k3s/connect"

raspberrypi k3s[1727]: time="2020-01-29T11:54:30.545897944Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.160.0.53:6443: connect: con

Please fixed it this issues.
Thnaks

**Comment by ndjhartman** [comment]
Facing the same issue, was this ever resolved?

**Comment by nielsole** [comment]
https://github.com/rancher/k3s/issues/214#issuecomment-482388852

**Comment by ashrafgt** [comment]
> Related, but didn't solve all my issues: [#214 (comment)](https://github.com/k3s-io/k3s/issues/214#issuecomment-482388852)
> 
> After setting `--advertise-address x.x.x.x`(public IP) on the server, the node registers and becomes healthy for me

Sorry for not updating the issue in time. That's the solution to the problem. Hope it works for anyone facing it in the future.
