### ISSUE TITLE
Support Azure Blob Storage for ETCD Remote Snapshot/Backups

### ISSUE THREAD

**Issue by mitchellmaler** [k3s-io/k3s#8833]
**Is your feature request related to a problem? Please describe.**
Currently, k3s (and rke2) only support s3 for automated etcd snapshot backups. For those running in Azure, this makes it difficult to use the native remote snapshot support, as s3 is not supported in Azure.

**Describe the solution you'd like**
As part of the snapshot controller, add azure blob storage support, which can be used instead of s3.

**Describe alternatives you've considered**
None

**Additional context**
You used to be able to run Minio using its Gateway feature to proxy s3 calls to other backends, but now that has been removed.

**Comment by brandond** [comment]
We do not currently plan to provide support for any additional blob storage interfaces. S3 has become a de-facto industry standard, with multiple implementations available to chose from.

**Comment by mitchellmaler** [comment]
@brandond What option can I use when running in Azure? Even though you call it de-facto it isn't supported in Azure, which is a major cloud provider, so I am not sure if that is an entirely true statement.

**Comment by brandond** [comment]
It is unfortunate that MS chose not to make their blob storage API compatible with S3. Google Cloud Storage for example is compatible, as are APIs for storage services from other service providers.

At this point we would essentially need to rewrite all of our S3 support using https://github.com/google/go-cloud or another project that abstracts storage on the client side, just to work around Azure's failure to align themselves with prevailing standards.

**Comment by mitchellmaler** [comment]
I entirely agree there, if they would have a compatible s3 API for their storage, it would align with most other providers.

**Comment by dereknola** [comment]
You could look into something like https://github.com/gaul/s3proxy
