### ISSUE TITLE
Running Tailscale inside K3s Docker Container (curl not available)

### ISSUE THREAD

**Issue by proever** [k3s-io/k3s#8864]
I was able to get the instructions at https://docs.k3s.io/installation/network-options?_highlight=tailscale#integration-with-the-tailscale-vpn-provider-experimental to work on a regular node. I'm now trying to achieve something similar with the `rancher/k3s` Docker image, with no luck so far.

The main issue is that `curl` is not available, and I don't see a way of installing it. I'm not even able to get a shell in the container it seems. Would appreciate any help! I'm using `rancher/k3s:v1.27.7-k3s2`. 

For example: 
```bash
$ k3s % docker run -it --rm rancher/k3s:v1.27.7-k3s2 curl --version

Unable to find image 'rancher/k3s:v1.27.7-k3s2' locally
v1.27.7-k3s2: Pulling from rancher/k3s
a1cd439dfa97: Already exists 
03962ff28f66: Already exists 
Digest: sha256:56c2a6885db2c69e002142aea3b80cc54b40459e4685500525aa729e16693fe7
Status: Downloaded newer image for rancher/k3s:v1.27.7-k3s2
No help topic for 'curl'
```

Same thing happens with `sh`.

**Comment by brandond** [comment]
The k3s image doesn't contain curl, and the default entry point runs /bin/k3s so you're essentially running `/bin/k3s curl` which is not a valid command. Why are you trying to run k3s as if it were curl?

**Comment by proever** [comment]
Yeah that's what I figured was happening. The reason I wanted to use `curl` to install Tailscale into the docker image was because the provider I'm using (vast.ai) only supports running docker images, it doesn't give you traditional "bare metal" access. But I suppose I could use a different base image to install K3s and the Tailscale on the host, and proceed from there. 

Thanks for the quick reply!
