### ISSUE TITLE
support cri-o container runtime

### ISSUE THREAD

**Issue by clcc2019** [k3s-io/k3s#8865]
![image](https://github.com/k3s-io/k3s/assets/46099295/233d8fa7-c195-4e51-9ada-5c8546e99d4a)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
We do not plan to bundle any other runtimes, but you can use any container runtime already installed on your host via the `--container-runtime-endpoint` flag.
