### ISSUE TITLE
Dedicated etcd node is scheduling pods - by default

### ISSUE THREAD

**Issue by KarloDerEchte** [k3s-io/k3s#8877]
**Environmental Info:**
K3s Version: 
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10

Node(s) CPU architecture, OS, and Version: 
```
NAME                  STATUS                     ROLES                       AGE   VERSION         OS-IMAGE                      KERNEL-VERSION                 CONTAINER-RUNTIME
k3s1                  NotReady                   control-plane,etcd,master   88m   v1.27.7+k3s2    Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.30.1.el9_2.x86_64   containerd://1.7.7-k3s1.27
k3s2                  Ready                      control-plane,etcd,master   84m   v1.27.7+k3s2    Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.25.1.el9_2.x86_64   containerd://1.7.7-k3s1.27
upsetcd1              Ready                      etcd                        62m   v1.27.7+k3s2    Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.30.1.el9_2.x86_64   containerd://1.7.7-k3s1.27

```
`
upsetcd1 Linux REDACTED 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
Cluster Configuration:
2 Master
1 Etcd Only node

**Describe the bug:**
When we set the Group of the upsetcd1 to etcd only (a dedicated etcd node), the scheduling is still enabled, which shouldn't happen according to the wiki. 

**Steps To Reproduce:**
- Installed K3s: 
`
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644"  K3S_TOKEN=REDACTED sh -s - server --server https://REDACTED:6443 --flannel-iface tailscale0 --advertise-address REDACTED --node-ip REDACTED  --disable-apiserver --disable-controller-manager --disable-scheduler  --etcd-arg ETCD_HEARTBEAT_INTERVAL=500 ETCD_ELECTION_TIMEOUT=500  
`

**Expected behavior:**
The etcd node should have scheduling disabled by default. 

**Actual behavior:**
It is scheduling pods.

**Comment by brandond** [comment]
> scheduling is still enabled, which shouldn't happen according to the wiki.

According to what wiki? We don't have a wiki. We also don't taint any nodes as unschedulable by default; if you want to disable scheduling on your nodes, you must do so manually.
