### ISSUE TITLE
Traefik redeployed and configuration lost

### ISSUE THREAD

**Issue by infroger** [k3s-io/k3s#8883]
**Environmental Info:**
K3s Version: 
$ k3s -v
k3s version v1.26.9+k3s1 (4e217286)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 
$ uname -a
Linux *redacted* 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers running Rancher 2.7.7

**Describe the bug:**
I have a three master K3S 1.26.9 cluster running Rancher 2.7.7. I have external TLS termination (HA Proxy), therefore I installed Rancher with option --set tls=external.

To make this work I had to edit /var/lib/rancher/k3s/server/manifests/traefik.yaml as mentioned in https://github.com/rancher/rancher/issues/42279#issuecomment-1742397915. Otherwise I got "too many redirects" when accessing Rancher UI.

It was all working fine until the file /var/lib/rancher/k3s/server/manifests/traefik.yaml was rewriten in all three masters few weeks later and Rancher UI stopped working again with "too many redirects".

After I edited the file manually in all three nodes again, it started working.

**Steps To Reproduce:**
- Installed K3s: 
- curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.26.9+k3s1 K3S_TOKEN=*REDACTED* sh -s - server --cluster-init --flannel-backend=host-gw
- Install Rancher 2.7.7
- Get "too many redirects"
- Edit /var/lib/rancher/k3s/server/manifests/traefik.yaml, add additionalArguments: "--entryPoints.web.forwardedHeaders.insecure"
- Rancher UI works as expected

**Expected behavior:**
File /var/lib/rancher/k3s/server/manifests/traefik.yaml should persist the modification.

**Actual behavior:**
After few weeks, Traefik was redeployed automatically and the modification in /var/lib/rancher/k3s/server/manifests/traefik.yaml was lost.

**Additional context / logs:**
Two questions:

1. Why did the traefik deployment was restarted and the file returned to the original content before my edition? Does K3S components update themselves automatically? If so, how can I disable this behavior? Or at least control it? It's not ideal in a production environment.

2. How can I make the file /var/lib/rancher/k3s/server/manifests/traefik.yaml persist the edit across updates? Do I have to edit the Helm chart? I would prefer a solution performed in the masters instead of messing around with helm charts. I prefer to download whatever helm chart is the most up to date than downloading and customizing helm charts and end up not able to keep up with newer versions.

Regards,
Roger

**Comment by brandond** [comment]
>  I had to edit /var/lib/rancher/k3s/server/manifests/traefik.yaml

Don't do that. As discussed in the docs, manifests for packaged components should not be directly modifed:
https://docs.k3s.io/installation/packaged-components#packaged-components

If you need to change the configuration of Traefik, use HelmChartConfig as described here: https://docs.k3s.io/helm#customizing-packaged-components-with-helmchartconfig

**Comment by infroger** [comment]
Thanks. That seems to have worked.

`$ sudo cat /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    - "--entryPoints.web.forwardedHeaders.insecure"`

**Comment by josh383451** [comment]
Strangely, I updated my K3s version to the latest version and I'm getting the "Too many redirects" error again even though this additionalArgument is set in the /var/lib/rancher/k3s/server/manifests/traefik-config.yaml file. I, again, had to add it manually into the  /var/lib/rancher/k3s/server/manifests/traefik.yaml file for it to work.
