### ISSUE TITLE
Ingress no longer binds to localhost on port 80

### ISSUE THREAD

**Issue by coopstah13** [k3s-io/k3s#8884]
**Environmental Info:**
K3s Version: 
k3s-v1.23.15+k3s1 previously and moving to v1.25.15+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux cooper-laptop 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Just a single server running on my laptop

**Describe the bug:**
I dropped in the new k3s binary and restarted the service, now my application is no longer accessible on localhost:80

**Steps To Reproduce:**
- Installed K3s: k3s-v1.23.15+k3s1
- Apply a very standard ingress with a number of services
- Replace with v1.25.15+k3s1

**Expected behavior:**
After k3s restarts, my application is still available on localhost:80

**Actual behavior:**
My application is no longer accessible on 80, I must use an IP given to me by my router.

**Additional context / logs:**
I'm told this is different from #7561 but it looks similar to me as far as the resultant behavior

**Comment by coopstah13** [comment]
The only customization is that I am using docker runtime instead of containerd, no customization to traefik either

I don't specifically have a firewall, but it is a company laptop and so the SentinelOne agent is running but I'm not sure what it does in that regard.

When I say not accessible, I mean this:
```
ccooper@cooper-laptop:~$ curl -vs http://localhost:80
*   Trying 127.0.0.1:80...
*   Trying ::1:80...
* connect to ::1 port 80 failed: Connection refused
* connect to 127.0.0.1 port 80 failed: No route to host
* Failed to connect to localhost port 80 after 3084 ms: No route to host
* Closing connection 0
*
```

Also, to be clear, this only started happening after I dropped in the `v1.25.15+k3s1` binary as a replacement to my existing `k3s-v1.23.15+k3s1` (just overwrote it in /usr/local/bin)

Actually, I used to access it over 127.0.1.1, but that no longer works either. It could be a coincidence, though, as I'm unable to get 1.23 to work now either.

**Comment by brandond** [comment]
I suspect this is being actively blocked by something else, as the "no route to host" error isn't something that you'd get if the port just wasn't being forwarded directly by the kubelet.

**Comment by coopstah13** [comment]
I dropped in k3s 1.25.15 again after stopping it and running k3s-killall.sh and it seems to be good now, sorry for the time waster!

**Comment by coopstah13** [comment]
I should have tried k3s-killall.sh before opening this issue, forgot about that handy little script!
