### ISSUE TITLE
Cluster data is not showing <IPv4> IPs in a Dual-Stack setup

### ISSUE THREAD

**Issue by mdrahman-suse** [k3s-io/k3s#8901]
**Environmental Info:**
K3s Version: 

Observed in the latest releases of k3s: v1.28.3+k3s2 and also in latest commit v1.27.7+k3s-fd676a5a

Node(s) CPU architecture, OS, and Version: 

```
Linux ip-xxx-xxx-x-232 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

```
1 server, 1 agent (Dual-Stack config)
```

**Describe the bug:**

External IP shows only `IPv6` IPs even when the cluster is configured to be Dual-Stack

**Steps To Reproduce:**

- Installed K3s, using v1.27.6+k3s2 also using latest commit from release-1.27 branch v1.27.7+k3s-fd676a5a
- Config.yaml 
```
write-kubeconfig-mode: "0644"
tls-san:
  - fake.fqdn.value
cluster-init: true
node-name: ip-xxx-xxx-x-232.us-west-1.compute.internal
cluster-cidr: <IPv4-ClusterCIDR-BLOCK>,<IPv6-ClusterCIDR-BLOCK>
service-cidr: <IPv4-ServiceCIDR-BLOCK>,<IPv6-ServiceCIDR-BLOCK>

node-external-ip: <PUBLIC-IPv4-IP>,<IPv6-IP>
node-ip: <PRIVATE-IPv4-IP>,<IPv6-IP>
```

**Expected behavior:**

Cluster details should show `PUBLIC-IPv4-IP` as External IPs and `PRIVATE-IPv4-IP` as Internal IPs

**Actual behavior:**

Cluster details shows `IPv6-IP` as External IPs and `PRIVATE-IPv4-IP` as Internal IPs
Ingress IPs also show only `IPv6` IPs

**Additional context / logs:**

Cluster details
```
$ kubectl get nodes -A -o wide
NAME                                          STATUS   ROLES                       AGE   VERSION                INTERNAL-IP     EXTERNAL-IP                             OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-xxx-xxx-x-161.us-west-1.compute.internal   Ready    <none>                      19m   v1.27.7+k3s-fd676a5a   xxx.xxx.x.161   2600:xxxx:xxx:xxxx:xxxx:xxxx:xxxx:6d0   Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.7.7-k3s1.27
ip-xxx-xxx-x-232.us-west-1.compute.internal   Ready    control-plane,etcd,master   20m   v1.27.7+k3s-fd676a5a   xxx.xxx.x.232   2600:xxxx:xxx:xxxx:xxxx:xxxx:xxxx:6cc   Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.7.7-k3s1.27
```
```
$ kubectl get svc traefik -n kube-system -o json
...
"status": {
        "loadBalancer": {
            "ingress": [
                {
                    "ip": "2600:xxxx:xxx:xxxx:xxxx:xxxx:xxxx:6cc"
                },
                {
                    "ip": "2600:xxxx:xxx:xxxx:xxxx:xxxx:xxxx:6d0"
                }
            ]
        }
    }
```

Might be related to the changes made in Dual-Stack setup: https://github.com/k3s-io/k3s/issues/8467

CC: @manuelbuil @ShylajaDevadiga

**Comment by mdrahman-suse** [comment]
If there are any additional config needed that I may be missing as part of the latest change, please let me know.

**Comment by brandond** [comment]
@mdrahman-suse can you provide the output of `kubectl get node -o yaml` ?

**Comment by manuelbuil** [comment]
I think @rbrtbnfgl is the best person for this issue :)

**Comment by manuelbuil** [comment]
I'm unable to reproduce it with the latest code using:
```
write-kubeconfig-mode: 644
token: "secret"
cluster-cidr: 10.42.0.0/16,2001:cafe:42::/56
service-cidr: 10.43.0.0/16,2001:cafe:43::/112
node-external-ip: 20.160.218.144,2001:cafe:100::1
node-ip: 10.1.1.11,fd56:5da5:a285:eea0::8
```
I always get the ipv4 address as the externalIP
```
azureuser@terraform-mbuil-vm0:~$ k get nodes -o wide
NAME                  STATUS   ROLES                  AGE   VERSION                      INTERNAL-IP   EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
terraform-mbuil-vm0   Ready    control-plane,master   12s   v1.28.3+k3s-96ebb963-dirty   10.1.1.11     20.160.218.144   Ubuntu 22.04.3 LTS   6.2.0-1016-azure   containerd://1.7.7-k3s1
```
I don't know why in your env cloudprovider forgets about the ipv4 external-ip

**Comment by manuelbuil** [comment]
Same with `v1.28.3+k3s2`, I can see both externalIPs when checking the yaml of the node:
```
    - address: 20.160.218.144
      type: ExternalIP
    - address: 2001:cafe:100::1
      type: ExternalIP
```

**Comment by manuelbuil** [comment]
@mdrahman-suse I think I know what's going on. Does it work for you if you pass the config: `kubelet-arg: "node-ip=0.0.0.0"`? Do you see both external-ips in the node yaml?

**Comment by mdrahman-suse** [comment]
Yes after applying the kubelet-arg I am seeing the all the ips
```
k3s.io/node-args: '["server","--write-kubeconfig-mode","0644","--tls-san","fake.fqdn.value","--cluster-init","true","--node-name","ip-192-168-1-137.us-west-1.compute.internal","--cluster-cidr","10.42.0.0/16,2001:cafe:42:0::/56","--service-cidr","10.43.0.0/16,2001:cafe:43:0::/112","--node-external-ip","18.144.43.96,2600:1f1c:ab4:ee48:493:2a6c:4a63:ae9e","--node-ip","192.168.1.137,2600:1f1c:ab4:ee48:493:2a6c:4a63:ae9e","--kubelet-arg","node-ip=0.0.0.0"]'
```
```
status:
    addresses:
    - address: 192.168.1.137
      type: InternalIP
    - address: 2600:1f1c:ab4:ee48:493:2a6c:4a63:ae9e
      type: InternalIP
    - address: 18.144.43.96
      type: ExternalIP
    - address: 2600:1f1c:ab4:ee48:493:2a6c:4a63:ae9e
      type: ExternalIP
```

**Comment by brandond** [comment]
> I am using AWS, so I have to use the same IPv6 IP address on the config for node-ip and node-external-ip.

To be clear you don't "have to" do this. Normally if you don't have a separate external IP, you wouldn't set it. Setting external and internal IPs to the same value is unnecessary, and as Manuel confirmed this is the expected behavior when you do this.

**Comment by mdrahman-suse** [comment]
Got it, will update our test docs accordingly... Closing this out. Thanks for helping out on this 👍
