### ISSUE TITLE
stop/start k3s systemd service overwrites context name in config file

### ISSUE THREAD

**Issue by Noksa** [k3s-io/k3s#8914]
**Environmental Info:**
K3s Version: 

```shell
➜  ~ k3s -v
k3s version v1.25.8+k3s1 (6c5ac022)
go version go1.19.7
```
Node(s) CPU architecture, OS, and Version: 

```shell
➜  ~ uname -a
Linux alexandrPC 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

```shell
1 node
```
**Describe the bug:**

After installing `k3s` I change `default` context name to something meaningful like `k3s` and it works fine until it is changed by `k3s` to `default` again.

**Steps To Reproduce:**

* Run command
```shell
curl -sfL https://get.k3s.io | CLUSTER_CIDR="192.168.44.0/23" SERVICES_CIDR="192.168.46.0/23" \
INSTALL_K3S_VERSION="v1.25.8+k3s1" INSTALL_K3S_EXEC="server --docker --disable=traefik \
--cluster-cidr=${CLUSTER_CIDR} --service-cidr=${SERVICES_CIDR} --write-kubeconfig-mode 0600 \
--kube-apiserver-arg service-node-port-range=1-65000 -o ~/.kube/k3s_config" sh -
```
* Check context name
```shell
➜  ~ kubectl config get-contexts --kubeconfig ~/.kube/k3s_config
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
*         default   default   default
```
* Change context to `k3s` and check the result
```shell
➜  ~ kubectl config rename-context default k3s --kubeconfig ~/.kube/k3s_config
Context "default" renamed to "k3s".
➜  ~ kubectl config get-contexts --kubeconfig ~/.kube/k3s_config
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE
*         k3s    default   default
```

* Stop and start `k3s` and check context name again
```shell
systemctl stop k3s
systemctl start k3s
➜  ~ kubectl config get-contexts --kubeconfig ~/.kube/k3s_config
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
*         default   default   default
```

It is `default` again

**Expected behavior:**

`k3s` doesn't change `context` name when we run `systemctl start k3s`
**Actual behavior:**

context name is changed to `default` after `systemctl start k3s`

**Additional context / logs:**

Is it possible to avoid such behavior?

**Comment by brandond** [comment]
> `-o ~/.kube/k3s_config`

K3s always overwrites the admin kubeconfig on startup. If you want to modify it, copy /etc/rancher/k3s/k3s.yaml to ~/.kube/k3s_config and make your changes to the copy, instead of having k3s itself write the config file to that location.
