### ISSUE TITLE
nodes not triggering disk pressure

### ISSUE THREAD

**Issue by migs35323** [k3s-io/k3s#8919]
**Environmental Info:**
K3s Version: v1.25.11+k3s1 (it also happens in 1.24)

Node(s) CPU architecture, OS, and Version: ubuntu 22

Cluster Configuration: 3 masters 7 servers

**Describe the bug:**

i got 1 or 2 nodes that are starting to run low on storage, i use longhorn for storage not sure if that matters 
i made a new deployment which i left it overnight today i found it is stuck in container creating,

```
  Warning  FailedCreatePodContainer  2m16s (x340 over 75m)  kubelet  unable to ensure pod container exists: failed to create container for [kubepods burstable podc30b2386-01a4-48a2-9317-97188a7328c4] : unable to start unit "kubepods-burstable-podc30b2386_01a4_48a2_9317_97188a7328c4.slice" (properties [{Name:Description Value:"libcontainer container kubepods-burstable-podc30b2386_01a4_48a2_9317_97188a7328c4.slice"} {Name:Wants Value:["kubepods-burstable.slice"]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): No space left on device
```

my issue is, if there is no space left on device
1, why isn't the node being marked with disk pressure?
2, why is the statefullset/deployment not scheduling into another node if there are no rules to force a specific node

**Comment by brandond** [comment]
Can you show your filesystem layout/utilization and the settings on this node?

* `df -kha`
* `kubectl get node -o yaml | grep arg`

**Comment by migs35323** [comment]
df -kha
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/root                                               201G   85G  116G  43% /
...loads of longhorn volumes

kubectl get node -o yaml | grep arg
k3s.io/node-args: '["agent","--node-external-ip","<node-ip>","--node-ip","<node-ip>","--flannel-iface","network1"]'

ok, there is something weird... i assumed the node was out of storage however there is something else..., i will look into it next week
i believe you can close the issue, there is need to investigate what is going on...
