### ISSUE TITLE
containerd in  containerd not working

### ISSUE THREAD

**Issue by sunnoy** [k3s-io/k3s#8958]
**Environmental Info:**
K3s Version: 

k3s -v
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7
Node(s) CPU architecture, OS, and Version: 

Linux node1 5.10.134-13.an8.x86_64 #1 SMP Mon Jan 9 10:39:46 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

**Describe the bug:**

i run containerd in  containerd 

```bash
nerdctl -a /run/k3s/containerd/containerd.sock  run -it --rm -v /run/k3s/containerd:/run/containerd -v /root/bin:/root/bin --privileged -v /var/lib/rancher/k3s/agent/containerd:/var/lib/containerd  centos:8 bash

/root/bin is containerd-1.6.25-linux-amd64.tar.gz unzip files

```

in container i run ctr run get error **ctr: failed to mount /tmp/containerd-mount3785720253: no such file or directory**

```bash
cd /root/bin
./ctr images pull docker.io/library/redis:alpine
./ctr run --rm docker.io/library/redis:alpine redis

ctr: failed to mount /tmp/containerd-mount3785720253: no such file or directory
```

**Comment by brandond** [comment]
Does this work on standalone versions of containerd, not bundled by k3s? I'm not sure that this is a k3s issue.

**Comment by sunnoy** [comment]
it is not working, I deployed containerd via the containerd installation documentation （https://github.com/containerd/containerd/blob/main/docs/getting-started.md） with the following command, but it doesn't work in the k3s containerd environment

```bash
nerdctl run -it --rm -v /run/containerd:/run/containerd -v /root/bin:/root/bin --privileged -v /var/lib/containerd:/var/lib/containerd  centos:8 bash
```

**Comment by brandond** [comment]
Keep tinkering with it, I bet you can get it to work. The k3s containerd is primarily configured for use by the k3s kubelet, for other more standalone use cases you might have to modify the commands used to configure the container.

**Comment by sunnoy** [comment]
The scenario I'm using is to utilize k3s as a cicd cluster, and the ci process requires the compilation of a docker image, can you provide me with some ideas on this?

**Comment by sunnoy** [comment]
nerdctl -a /run/k3s/containerd/containerd.sock  run -it --rm -v /run/k3s/containerd:/run/k3s/containerd -v /root/bin:/root/bin --privileged -v /var/lib/rancher/k3s/agent/containerd:/var/lib/rancher/k3s/agent/containerd -v /run/containerd:/run/containerd  centos:8 bash 

can work

k3s containerd  use /run/k3s/containerd and /run/containerd

**Comment by brandond** [comment]
Note that this isn't actually containerd in containerd, as you are not actually running a nested instance of containerd. You're just accessing the host containerd socket.
