### ISSUE TITLE
etcd-snapshot fails on k3s server

### ISSUE THREAD

**Issue by MalikaML** [k3s-io/k3s#8960]
**Environmental Info:**
K3s Version: k3s version v1.26.3+k3s1
go version go1.19.7
Operating System: Debian GNU/Linux 12
Cluster configuration: 1 master node and 3 worker nodes

**Current Behavior:**

When executing the `sudo k3s etcd-snapshot save` command, an error message is returned:
`FATA[0000] etcd database not found in /var/lib/rancher/k3s/server
`
**Steps To Reproduce:**

- Installed K3s: 
To install k3sup on my system, I used these commands: (k3s version: v1.27.6+k3s1)
```
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/
```
To add the master node, I used this command : (k3s version: v1.26.3+k3s1)
`k3sup install \ --ip <ipv4-master-1> \ --user root \ --k3s-version <latest-version> \ --local-path config.yaml \ --context <cluster-name> \ --tls-san <ipv4-virtual-ip> \ --k3s-extra-args='--disable servicelb --flannel-backend=none --cluster-cidr=10.45.0.0/16 --service-cidr=10.46.0.0/16 --disable-network-policy --disable traefik --node-ip=<ipv4-master-1>'`

**Expected behavior:**

The k3s etcd-snapshot save command should create an etcd snapshot without encountering errors.

**Additional context / logs:**

If I run the command `ls /var/lib/rancher/k3s/server/db/ `it displays these files:
`etcd   snapshots   state.db   state;db-shm   state.db-wal` (so it means I have an etcd database to snapshot, right?)

And if run the command` ls /var/lib/rancher/k3s/server/` it displays these files:
`agent-token   cred   db   etc   kine.sock   manifests   node-token   static   tls   token`

**Comment by MalikaML** [comment]
Hi @brandond @coutinhop, can you please help me out with this ? thank you

**Comment by brandond** [comment]
I don't see that you're using embedded etcd - you didn't start the server with `--cluster-init`, and the files on disk (state.db and state.db-wal) indicate use of kine+sqlite.

Have you read the documentation at https://docs.k3s.io/datastore/ha-embedded ?

**Comment by MalikaML** [comment]
@brandond this solved my issue! Thank you for your response :)
