### ISSUE TITLE
k3s fails to start due to containerd error

### ISSUE THREAD

**Issue by calcium90** [k3s-io/k3s#8961]
**Environmental Info:**
K3s Version: 
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10

Node(s) CPU architecture, OS, and Version: 

openSUSE MicroOS 20231126
Linux saturn 6.6.2-1-default #1 SMP PREEMPT_DYNAMIC Mon Nov 20 11:22:36 UTC 2023 (263a855) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single node

**Describe the bug:**

k3s fails to start (either via systemd or /usr/local/bin/k3s server --disable=traefik) with error
ERRO[0001] containerd exited: exit status 2

**Steps To Reproduce:**

- Installed K3s: 
curl -sfL https://get.k3s.io | sh -s - --disable=traefik

**Expected behavior:**
k3s should start successfully

**Actual behavior:**
k3s fails to start due to containerd error

**Additional context / logs:**
Full k3s service log:
[k3s.log](https://github.com/k3s-io/k3s/files/13494123/k3s.log)

In containerd log (/var/lib/rancher/k3s/agent/containerd/containerd.log) this is logged (full log to be attached):

[containerd.log](https://github.com/k3s-io/k3s/files/13494065/containerd.log)
```
time="2023-11-28T20:38:22.027016182Z" level=info msg="Connect containerd service"
time="2023-11-28T20:38:22.027030989Z" level=info msg="using legacy CRI server"
time="2023-11-28T20:38:22.027037833Z" level=info msg="using experimental NRI integration - disable nri plugin to prevent this"
time="2023-11-28T20:38:22.027069751Z" level=info msg="Get image filesystem path \"/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs\""
unexpected fault address 0x7f05a8575000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f05a8575000 pc=0x4774a1]
```

**Comment by brandond** [comment]
I can't reproduce this. Is there anything interesting or unusual about this node? What linux distribution is this running on? Do you have any security modules (selinux/apparmor/etc) running?

**Comment by calcium90** [comment]
@brandond In response to your questions:

- OS is OpenSUSE MicroOS (rolling release, current version 20231126).
- /var/lib/rancher/k3s filesystem is btrfs
- SELinux is enabled,  k3s-selinux package is installed.
- I can confirm the same failure when running with `--selinux`

It was working fine a couple of weeks ago, unfortunately as it auto updates the system every couple of days the btrfs snapshot of the last working state has been purged now so I'm not entirely sure which system package update may be associated with it breaking.

I've now installed docker and am additionally running with the `--docker` option to work around it for now.
