### ISSUE TITLE
Bump containerd/runc

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8965]
We are three releases behind on containerd and should update:
* https://github.com/containerd/containerd/releases/tag/v1.7.8
* https://github.com/containerd/containerd/releases/tag/v1.7.9
* https://github.com/containerd/containerd/releases/tag/v1.7.10

Containerd is using a newer release of runc, which should also be updated.

**Comment by ShylajaDevadiga** [comment]
### Validated using latest commit id 71a3c35fb7077c5a952fbc74a9cd8dee352b1178 on master branch 
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
```
cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="9.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Oracle Linux Server 9.3"
```
*Cluster Configuration:*
Single node

*Config.yaml:*
```
cat /etc/rancher/rke2/config,yaml
write-kubeconfig-mode: "0644"
```

 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml
2. Install k3s


**Validation results:**
```
[ec2-user@ip-172-31-4-221 ~]$ k3s -v
k3s version v1.28.4+k3s-71a3c35f (71a3c35f)
go version go1.20.11
[ec2-user@ip-172-31-4-221 ~]$ kubectl get nodes -o wide
NAME                                         STATUS   ROLES                  AGE   VERSION                INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                CONTAINER-RUNTIME
ip-172-31-4-221.us-east-2.compute.internal   Ready    control-plane,master   31s   v1.28.4+k3s-71a3c35f   172.31.4.221   <none>        Oracle Linux Server 9.3   5.14.0-362.8.1.el9_3.x86_64   containerd://1.7.11-k3s2
[ec2-user@ip-172-31-4-221 ~]$ /var/lib/rancher/k3s/data/c6ebdd4685048debba4176de1b22c5240e061853c4f057778866af7a897b4670/bin/runc -v
runc version 1.1.10
```
