### ISSUE TITLE
Update the Code of Conduct

### ISSUE THREAD

**Issue by mattfarina** [k3s-io/k3s#8986]
The current code of conduct notes that it follows the CNCF Code of Conduct and then supplies the text for a Code of Conduct that is different from the current CNCF one.

Can the CoC file be updated to just redirect to the latest from the CNCF. Other projects do that today. For example, https://github.com/helm/helm/blob/main/code-of-conduct.md

**Comment by rancher-max** [comment]
Closing as nothing specifically to test, but verified that we do this now: https://github.com/k3s-io/k3s/blob/master/CODE_OF_CONDUCT.md
