### ISSUE TITLE
Remove s390x support

### ISSUE THREAD

**Issue by mattfarina** [k3s-io/k3s#8987]
Looking at the download information from the GitHub API, it appears that s390x is mostly not downloaded. I think it's just the 1.27 version that has a real number of downloads. Was that just from testing?

Given the limited to no use and the infra/process needed to support it, should s390x build support be dropped?

Note, I look at this as a difference between open build and open source. I'm not suggesting the source restrict from s390x builds elsewhere. Just the open builds provided by the project don't need to invest in s390x support if it's not being used from here.

**Comment by caroline-suse-rancher** [comment]
Circling back - I will close this issue as s390x has been removed from our k3s support matrix and we no longer produce builds.
