### ISSUE TITLE
k3s-upgrade images missing for November 2023 releases

### ISSUE THREAD

**Issue by jidckii** [k3s-io/k3s#8990]
**Environmental Info:**
K3s Version: **v1.28.4-k3s1**

**Describe the bug:**

I have a problem with k3s-upgrade, images after rancher/k3s-upgrade:v1.27.7-k3s1 do not have a common manifesto for different architectures, because of this system-upgrade-controller cannot work correctly and I see an error in jobs

```log
Failed to pull image "rancher/k3s-upgrade:v1.28.4-k3s1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/k3s-upgrade:v1.28.4-k3s1": failed to resolve reference "docker.io/rancher/k3s-upgrade:v1.28.4-k3s1": docker.io/rancher/k3s-upgrade:v1.28.4-k3s1: not found
```

**Steps To Reproduce:**

run  system-upgrade-controller 

**Additional context / logs:**
- https://hub.docker.com/r/rancher/k3s-upgrade/tags?page=1&name=v1.27.7-k3s1
- https://hub.docker.com/r/rancher/k3s-upgrade/tags?page=1&name=v1.28.4-k3s1

![2023-12-05_11-02-54](https://github.com/k3s-io/k3s/assets/6608896/9c39281b-130a-44d3-8cae-2739df4fe559)
![2023-12-05_11-02-11](https://github.com/k3s-io/k3s/assets/6608896/3b09200e-68c8-43c1-bd0e-f55b012cb3cc)

**Comment by brandond** [comment]
We are working through issues with our CI infra. Images will be up when they're ready.

**Comment by brandond** [comment]
Reopening to pin
