### ISSUE TITLE
Support cgroups v2

### ISSUE THREAD

**Issue by nsmith5** [k3s-io/k3s#900]
`k3s-agent` is failing to run on Fedora 31. I suspect this is due to cgroups v2 being the default on Fedora 31, but can't quite figure out how to see which version of runc is shipping with k3s (runc recently landed support for cgroups v2)

**Version:**
`k3s version v0.9.1 (755bd1c6)`

**Describe the bug**
k3s-agent exits 1 and dies repeatedly with the following log output:
```
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403568863-07:00" level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Rasp>
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403559607-07:00" level=error msg="Failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Rasp>
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403539664-07:00" level=warning msg="Failed to find cpuset cgroup, you may need to add \"cgroup_enable=cpuset\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403421758-07:00" level=info msg="Starting k3s agent v0.9.1 (755bd1c6)"
Oct 15 07:41:51 mercury systemd[1]: Started Lightweight Kubernetes.
Oct 15 07:41:51 mercury systemd[1]: Starting Lightweight Kubernetes...
Oct 15 07:41:51 mercury systemd[1]: Stopped Lightweight Kubernetes.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Scheduled restart job, restart counter is at 1076.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Service RestartSec=5s expired, scheduling restart.
.
.
.
```

**To Reproduce**
Start up a k3s agent on Fedora 31 Server

**Expected behavior**
Should start

**Actual behavior**
Doesn't and poops out the logs above

**Additional context**
Again, I think this is related to the cgroups v2 change, but couldn't figure out which version of runc is getting packaged with k3s right now to confirm. The most recent version of runc ([1.0.0-rc9](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc9)) is required for cgroups v2 to function.

**Comment by AkihiroSuda** [comment]
rc9 still doesn't really support cgroup2, especially still lacks support for device controller

**Comment by nsmith5** [comment]
Bummer. Ok well I suppose there is nothing k3s can really do to move that along so feel free to close this issue if you wish.

**Comment by leigh-j** [comment]
https://github.com/containers/crun is a good drop in for runc and has full cgroupv2 support. Not a trivial change but crun seems better than runc in every way.

**Comment by T0MASD** [comment]
I'm hitting the same issue on k3 master on fedora 31. As a workaround I've added `systemd.unified_cgroup_hierarchy=0` to GRUB_CMDLINE_LINUX in /etc/default/grub

As per:
https://fedoraproject.org/wiki/Common_F31_bugs#Docker_package_no_longer_available_and_will_not_run_by_default_.28due_to_switch_to_cgroups_v2.29

**Comment by fire** [comment]
Running this command from the Fedora wiki worked:

> ```sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"```

**Comment by rektide** [comment]
i'm sorry i'm kind of confused. what are the main things k3s depends on that need to gain cgroup v2 support?

here's some tickets for various projects. i'm not sure which of these we are going to need.
* [containerd cgroup v2](https://github.com/containerd/containerd/issues/3726)
* [runc cgroup v2](https://github.com/opencontainers/runc/issues/654)

**Comment by nsmith5** [comment]
Here is my understanding: k3s uses containerd which uses runc which only supports cgroup v1. crun is an alternative to runc that supports cgroup v2. If containerd supports crun then containerd will support cgroup v2 inherently and so too will k3s.

**Comment by AkihiroSuda** [comment]
The biggest missing part is kubelet
https://github.com/kubernetes/enhancements/pull/1370

**Comment by leigh-j** [comment]
crio already supports crun, for a minimalist kubernetes deployment crio would be simpler than containerd, containerd has a lot of baggage and currently the main blocker for 1370.

the work to resolve runc is partly being done by porting across what crun has already done.
https://github.com/opencontainers/runtime-spec/issues/1002#issuecomment-582437368

**Comment by AkihiroSuda** [comment]
>containerd has a lot of baggage and currently the main blocker for 1370.

Wrong. containerd already supports cgroup v2.

**Comment by piahoo** [comment]
is there any plan to support cgroup v2?

**Comment by Nefelim4ag** [comment]
Kubelet now support Cgroup V2

**Comment by juchiast** [comment]
Every linked issues on this thread is closed.

**Comment by AkihiroSuda** [comment]
cgroup2 PR for k3s is here https://github.com/rancher/k3s/pull/2584

**Comment by cablespaghetti** [comment]
Great contribution! 🎉

**Comment by nsmith5** [comment]
❤️ @AkihiroSuda Stunning work. I saw your Kubecon talk and hoped this might be on the horizon. I see rootless is coming up afterwards from the PR description. That is fantastic to hear! 🍻

**Comment by davidnuzik** [comment]
QA to test, see PR https://github.com/k3s-io/k3s/pull/2584

**Comment by rancher-max** [comment]
This does not appear to be fully functional yet. On a Fedora 31 system, which uses Unified cgroups (full fledged cgroups v2), there is still a failure, though it does appear to get farther along in the process. Attached full log:
[fedora31.log](https://github.com/k3s-io/k3s/files/5675856/fedora31.log).
It's a large file, so snippet included:
```
...
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: time="2020-12-10T19:13:37.303510924Z" level=info msg="Handling backend connection request [ip-172-31-25-136.us-east-2.compute.internal]"
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: time="2020-12-10T19:13:37.304100312Z" level=warning msg="Disabling CPU quotas due to missing cpu.cfs_period_us"
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: time="2020-12-10T19:13:37.304125224Z" level=warning msg="Disabling pod PIDs limit feature due to missing cgroup pids support"
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: time="2020-12-10T19:13:37.304169520Z" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --cgroups-per-qos=false --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/0795af50867d0b129de8cb41645adbf3cf16863b8862fae82a9f5f1520a956e4/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=unix:///run/k3s/containerd/containerd.sock --cpu-cfs-quota=false --enforce-node-allocatable= --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=SupportPodPidsLimit=false --healthz-bind-address=127.0.0.1 --hostname-override=ip-172-31-25-136.us-east-2.compute.internal --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-labels= --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: time="2020-12-10T19:13:37.304808500Z" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --healthz-bind-address=127.0.0.1 --hostname-override=ip-172-31-25-136.us-east-2.compute.internal --kubeconfig=/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig --proxy-mode=iptables"
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: F1210 19:13:37.305388    4955 server.go:181] cannot set feature gate SupportPodPidsLimit to false, feature is locked to true
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: goroutine 11893 [running]:
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000122001, 0xc009914280, 0x7d, 0x250)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x70193e0, 0xc000000003, 0x0, 0x0, 0xc00a1f4690, 0x6ccbde2, 0x9, 0xb5, 0x40fb00)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x70193e0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00aa0f250, 0x1, 0x1)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).print(...)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:714
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatal(...)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1482
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc00f2c6580, 0xc007034c00, 0x1f, 0x20)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:181 +0x225
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc00f2c6580, 0xc007034c00, 0x1f, 0x20, 0xc00f2c6580, 0xc007034c00)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00f2c6580, 0xc0090d3c80, 0x352b6cb, 0x472181)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:958 +0x375
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:895
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet.func1(0xc00f2c6580)
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:31 +0x2f
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]: created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet
Dec 10 19:13:37 ip-172-31-25-136.us-east-2.compute.internal k3s[4955]:         /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:30 +0x8d
...
```

The steps I took were:
1. Bring up fedora 31 vm
2. Install k3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" INSTALL_K3S_VERSION=v1.20.0-rc1+k3s1 sh -`. Run the `yum` commands given then rerun this command.

Note this does still work on a hybrid cgroups setup. Following the steps in the PR produced a success on an Ubuntu system with `systemd.unified_cgroup_hierarchy=1` kernel cmdline.

**Comment by brandond** [comment]
Based on that error I think we need some additional changes:
https://github.com/k3s-io/k3s/blob/master/pkg/daemons/agent/agent.go#L133
https://github.com/k3s-io/k3s/blob/master/pkg/daemons/agent/agent.go#L178

**Comment by AkihiroSuda** [comment]
Does it work if you run `echo +pids > /sys/fs/cgroup/cgroup.subtree_control`?

**Comment by rancher-max** [comment]
No it doesn't. I tried it in a fresh setup, running as root, but got the same error.

**Comment by davidnuzik** [comment]
Hi. I don't want to put any pressure on anyone, I just want to set some expectations. We are planning to release v1.20.0+k3s1 not any later than December 16th. Our due date to get things in is pretty much today, Monday the 14th is kind of a stretch. If we can't verify this is working I will need to be moving this to our next milestone, which is slated for a January 13th release (when upstream will deliver next set of patches).

I will be moving this issue to the next Milestone for January next year if it looks like this requires much more effort.

**Comment by zdzichu** [comment]
Just to  note, it was working fine as of fadc5a8057c244df11757cd47cc50cc4a4cf5887 (i.e. before 1.20 landed and before f3de60ff3191dc3a0ae7ce8393e388700f48ed88).

**Comment by davidnuzik** [comment]
We need some more time to resolve the problems Max outlined. I've bumped this to our next planned release in Mid-January.

**Comment by AkihiroSuda** [comment]
> Working in Development 26 days ago

Is anyone working?

**Comment by brandond** [comment]
@AkihiroSuda not at the moment; if you have cycles to dig into this we'd all be very grateful ;)

**Comment by AkihiroSuda** [comment]
PR: https://github.com/k3s-io/k3s/pull/2844

**Comment by davidnuzik** [comment]
PR exists and is in review, so I have set the issue to Peer Review status for you.
![image](https://user-images.githubusercontent.com/45179589/105737944-bf087b00-5ef3-11eb-8080-8f09d68e8288.png)

**Comment by rancher-max** [comment]
This has been validated as working. Validated using commit `f3c41b7650340bddfa44129c72e7f9fb79061b90`. Ensured working on hybrid, unified, and legacy cgroups. Am able to join server and agent nodes, deploy workloads, and do standard operations successfully. Thank you for the fix!

**Comment by brandond** [comment]
I just want to call out that hybrid mode is only supported if the required cgroup controllers are in v1. If v2 has claimed them we will not check there for them in hybrid mode.
