### ISSUE TITLE
v1.27.7+k3s2  agent 指定server URL时无法使用域名

### ISSUE THREAD

**Issue by denwork** [k3s-io/k3s#9010]
**Environmental Info:**
K3s Version: 
v1.27.7+k3s2

Node(s) CPU architecture, OS, and Version: 
 5.14.9-1.el7.elrepo.x86_64

Cluster Configuration:
3 servers 3 agents

**Describe the bug:**
Can not use domain. for example:
agent --server=https://k3s-server.example.com:6443
I need change it to agent --server=https://192.168.125.87:6443. the ip address is my server IP

**Steps To Reproduce:**
- Installed K3s: 
first server:
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_EXEC="server --service-cidr=172.11.0.0/16  --disable-network-policy --disable-kube-proxy --flannel-backend='none' --tls-san=k3s-server.example.com --cluster-init" sh -
other servers:
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_EXEC="server --token=K100e2085c5bcf216777cf7e634fcf45f9bbca4d8483db4c6e8be10381b2521650a::server:54fab353df1ca1b8ab69be76307b678f --service-cidr=172.11.0.0/16  --disable-network-policy --disable-kube-proxy --flannel-backend='none' --tls-san=k3s-server.example.com --server=https://k3s-server.example.com:6443" sh -

**Additional context / logs:**
the agent logs:
  Dec  8 00:23:31 kubenode02 k3s: time="2023-12-08T00:23:31+08:00" level=info msg="Adding server to load balancer k3s-agent-load-balancer: k3s-server.example.com:6443"
Dec  8 00:23:31 kubenode02 k3s: time="2023-12-08T00:23:31+08:00" level=info msg="Running load balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [k3s-server.example.com:6443] [default: k3s-server.example.com:6443]"
Dec  8 00:23:31 kubenode02 k3s: time="2023-12-08T00:23:31+08:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:45546->127.0.0.1:6444: read: connection reset by peer"
Dec  8 00:23:33 kubenode02 k3s: time="2023-12-08T00:23:33+08:00" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:45550->127.0.0.1:6444: read: connection reset by peer"
Dec  8 00:23:35 kubenode02 k3s: time="2023-12-08T00:23:35+08:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:45560->127.0.0.1:6444: read: connection reset by peer"
Dec  8 00:23:40 kubenode02 k3s: time="2023-12-08T00:23:40+08:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to retrieve configuration from server: Get \"https://127.0.0.1:6444/v1-k3s/config\": read tcp 127.0.0.1:45568->127.0.0.1:6444: read: connection reset by peer"
Dec  8 00:23:45 kubenode02 k3s: time="2023-12-08T00:23:45+08:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: CA cert validation failed: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:45572->127.0.0.1:6444: read: connection reset by peer"

The domain resolved：
```
[root@ xxx ~]# nslookup k3s-server.example.com
Server:         192.168.125.8
Address:        192.168.125.8#53

Name:   k3s-server.example.com
Address: 192.168.125.89
Name:   k3s-server.example.com
Address: 192.168.125.88
Name:   k3s-server.example.com
Address: 192.168.125.87
```

改成3个server其中一个server的ip就没问题。

**Comment by brandond** [comment]
If you are going to use a round-robin DNS alias for the server address, you should ensure that ALL addresses are available. K3s does not try all of the addresses returned by the DNS lookup, if it happens to try the address of a server that is not currently available, then it will not be able to join.

Use of DNS RR is best used alongside a DNS server capable of performing health checks and preventing the record from resolving addresses of servers that are not currently healthy.
