### ISSUE TITLE
k3s server fails to start when using postgres datastore with no existing database named postgres

### ISSUE THREAD

**Issue by mortenlj** [k3s-io/k3s#9033]
**Environmental Info:**
K3s Version: v1.28.4+k3s2

Node(s) CPU architecture, OS, and Version: 

Linux rpi4b01 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:

1 server, 5 agents, on various kinds of Raspberry Pi. Using PostgreSQL external datastore, hosted on aiven.io (free tier).

**Describe the bug:**

When starting up, the server attempts to connect to the `postgres` database to check if the wanted database exists.
When there is no database named `postgres` on the server, k3s fails and exits.

**Steps To Reproduce:**

- Installed K3s: Used DietPi installation, but I believe installation method to be irrelevant.
- Configure PostgreSQL external datastore with database named something other than `postgres`
- Ensure no database named `postgres` exists on the database server
- Start k3s server

**Expected behavior:**

I expected k3s to connect to the configured database and start normally

**Actual behavior:**

k3s server attempts to connect to `postgres` database, fails to connect and exits with an error

**Additional context / logs:**

https://rancher-users.slack.com/archives/CGGQEHPPW/p1702161565508369
https://github.com/k3s-io/kine/pull/241
https://www.postgresql.org/docs/9.1/creating-cluster.html

**Comment by Nyctelor** [comment]
I'll add my own config to this issue:
--datastore-endpoint=postgres://[ROLENAME]:[PASSWORD]@[HOST]:5432/k3sdb

starting kubernetes: preparing server: creating storage endpoint: building kine: failed to connect to `host=[HOST] user=[ROLENAME] database=postgres`:

The database name the process is trying to connect to does not match the database name being given by datastore-endpoint

**Comment by brandond** [comment]
The postgres database is expected to exist by default, and is used temporarily while testing to see if the selected database exists or needs to be created. From the docs linked above:

> After initialization, a database cluster will contain a database named postgres, which is meant as a default database for use by utilities, users and third party applications. The database server itself does not require the postgres database to exist, but many external utility programs assume it exists.

**Comment by Nyctelor** [comment]
Ok, thank you for the clarification. I added  a line to pg_hba to let my k3s server reach the postgres DB and it is finally working.

**Comment by brandond** [comment]
We can look at a way to address that, but the current mechanism was supposed to be an improvement over the previous approach, which always tried to create the k3s database, and just handled the failure - but not in a consistently portable way. The new approach connects temporarily to the postgres database, and queries to see if the k3s database exists - and only creates it if it does not.

**Comment by mortenlj** [comment]
I guess an argument to be made here is if k3s/kine really should be responsible for creating the database?

Creating the tables and anything else is normal and fine, but creating the database itself is in my experience often handled outside the application that uses it, because it requires giving quite elevated privileges to the application for something that should only be needed once in the application lifecycle.

**Comment by brandond** [comment]
> I guess an argument to be made here is if k3s/kine really should be responsible for creating the database?

It seems to be the behavior that most users expect, so that's what we've always done. Changing that now is not likely.

**Comment by mortenlj** [comment]
Would it make sense to change it so that any errors inside `createDBIfNotExist` are treated/logged as warnings but doesn't cause the server to exit? 

Then you get the following scenarios:



| Database exists at start | Able to check for existence | Able to create     | Consequence                                                                                                                                 |
|--------------------------|-----------------------------|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------|
| :white_check_mark:       | :white_check_mark:          | :white_check_mark: | Everything works                                                                                                                            |
| :white_check_mark:       | :white_check_mark:          | :x:                | Everything works                                                                                                                            |
| :white_check_mark:       | :x:                         | :white_check_mark: | Warning about not being able to check for existence, but everything works                                                                   |
| :white_check_mark:       | :x:                         | :x:                | Warning about not being able to check for existence, warning about not being able to create database, but everything works                  |
| :x:                      | :white_check_mark:          | :white_check_mark: | Database created, everything works                                                                                                          |
| :x:                      | :white_check_mark:          | :x:                | Warning about not being able to create database, then error because database not found                                                      |
| :x:                      | :x:                         | :white_check_mark: | Warning about not being able to check for existence, database created, then everything works                                                |
| :x:                      | :x:                         | :x:                | Warning about not being able to check for existence, warning about not being able to create database, then error because database not found |

**Comment by brandond** [comment]
Yeah, if you're up for it, a PR to https://github.com/k3s-io/kine would be welcome!

**Comment by ringerc** [comment]
> It seems to be the behavior that most users expect, so that's what we've always done. Changing that now is not likely.

Most users expect insecure, but convenient, defaults.

That doesn't make them a good idea.

I explained here https://github.com/k3s-io/k3s/issues/9111#issuecomment-1906916475 why this is a nice "quickstart setup" style option, but totally unappropriate for production deployments.

**Comment by ringerc** [comment]
> Do note however that we are unlikely to accept any change that suddenly causes k3s to refuse to run if it has "excessive" privilege, as we commonly see users configuring k3s to use the default admin account provided by a managed database service or prepackaged container image.

Right; since that's been historically permitted, it should emit at most a warning. Then add a non default feature flag warning that eventually that capability will go away, etc. Longer term stuff. While ideally it should not have permitted this configuration in the first place, it's a bit late to just turn it off.

As for the rest, I'll have to see how the k3s testing in the org I'm working with goes. Thanks for the pointer on where to start.
