### ISSUE TITLE
New EtcdIsVoter Node condition should update status on a cluster-reset

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#9048]
**Environmental Info:**
K3s Version: 

```
v1.26.11, v1.27.8, v1.28.4
```

Node(s) CPU architecture, OS, and Version: 

```
Rocky 9.3
```

Cluster Configuration:

```
3 servers, 1 agent
```

**Describe the bug:**

We don't revisit the status of the new EtcdIsVoter Node condition during a cluster-reset, where the node communication goes down and the etcd cluster is reset. In this case, we should probably update the status of all nodes with this condition to be "False".

**Steps To Reproduce:**

1. Create 3 server cluster
2. Take a snapshot to s3
3. Terminate all 3 instances and bring up a new fresh instance
4. Restore s3 snapshot to the fresh instance

**Expected behavior:**

The nodes that were terminated and are then in NotReady state after a cluster-reset should not have the EtcdIsVoter status as "True".

**Actual behavior:**

This status does not update. Below was taken from a node that was terminated and in a NotReady state:
```
  - lastHeartbeatTime: "2023-12-11T21:49:41Z"
    lastTransitionTime: "2023-12-11T21:49:41Z"
    message: Node is a voting member of the etcd cluster
    reason: MemberNotLearner
    status: "True"
    type: EtcdIsVoter
```

**Additional context / logs:**

The condition should also be removed entirely if the etcd role is removed from the server in any way, for example being started/restarted with --disable-etcd

I wonder if it's possible to do periodic checking from a healthy node to determine what is the actual state and update based on that.

**Comment by brandond** [comment]
> I wonder if it's possible to do periodic checking from a healthy node to determine what is the actual state and update based on that.

We already do that, we just don't have code to handle the node not being part of the etcd cluster at all.

**Comment by VestigeJ** [comment]
@vitorsavian can you comment and or change the milestone to bring this into scope?

**Comment by vitorsavian** [comment]
@VestigeJ K, I will change the milestone

**Comment by brandond** [comment]
The PR looks good to me, just needs some additional 👀 for approval.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ k3s version v1.29.0+k3s-9a70021a (9a70021a)

```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"


*Cluster Configuration:*
3 node server 
1 agent server 


 

 
## Steps to validate the fix
1. Create a k3s cluster with 3 servers and 1 agent 
2. Snapshot the server and get the token
3. Delete/Terminate all nodes 
4. Restore snapshot on a new fresh node
5. Validate it works
6. Validate Nodes and pods are ok 
7. Validate that conditions field is properly set   

 


 
## **Reproduction Issue:**
<details>

```

$ k3s -v
k3s version v1.29.0+k3s-ac8fe8de (ac8fe8de)
go version go1.21.5



  $ kubectl get node -o yaml


    - lastHeartbeatTime: "2024-01-17T09:52:54Z"
      lastTransitionTime: "2024-01-17T09:46:13Z"
      message: kubelet is posting ready status. AppArmor enabled
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastHeartbeatTime: "2024-01-17T09:46:26Z"
      lastTransitionTime: "2024-01-17T09:46:26Z"
      message: Node is a voting member of the etcd cluster
      reason: MemberNotLearner
      status: "True"
      type: EtcdIsVoter
```



 


## **Validation Results:**
<details>

```

 sudo k3s etcd-snapshot save \
--s3 \
--s3-bucket=" " \
--s3-access-key="   " \
--s3-secret-key="   " \
--s3-region="" \
--s3-timeout=90s
 
---------- New node --------


sudo k3s server \
--cluster-reset \
--etcd-s3 \
--cluster-reset-restore-path="on-demand-ip " \
--etcd-s3-bucket=" " \
--etcd-s3-region="" \
--etcd-s3-access-key=" " \
--etcd-s3-secret-key="" \
--token=" "


~$ k3s -v
k3s version v1.29.0+k3s-9a70021a (9a70021a)
go version go1.21.5


~$ kubectl get node -o yaml

  name: ip-172-31-4-246.us-east-2.compute.internal
    resourceVersion: "3691"
    uid: 7c1d0378-3baf-43ee-9738-df354efb74bc
  spec:
    podCIDR: 10.42.0.0/24
    podCIDRs:
    - 10.42.0.0/24
    providerID: k3s://ip-172-31-4-246.us-east-2.compute.internal
    taints:
    - effect: NoSchedule
      key: node.kubernetes.io/unreachable
      timeAdded: "2024-01-16T22:18:42Z"
  status:
    addresses:
    - address: 172.31.4.246
      type: InternalIP
    - address: 3.129.39.13
      type: ExternalIP
    - address: ip-172-31-4-246.us-east-2.compute.internal
      type: Hostname
    allocatable:
      cpu: "2"
      ephemeral-storage: "39358207765"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 3956684Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 40458684Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 3956684Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2024-01-16T22:19:17Z"
      lastTransitionTime: "2024-01-16T22:19:17Z"
      message: Node is not a member of the etcd cluster
      reason: NotAMember
      status: "False"
      type: EtcdIsVoter
```
