### ISSUE TITLE
`k3s-agent.service` intermittently fails to join server node on first attempt (Dual-Stack config)

### ISSUE THREAD

**Issue by mdrahman-suse** [k3s-io/k3s#9071]
**Environmental Info:**
K3s Version: 

`v1.28.4+k3s2`

Node(s) CPU architecture, OS, and Version: 

`Ubuntu 22.04 / RHEL 9.3 in AWS`

Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

`k3s-agent.service` fails to join server node on a dual stack setup intermittently with an error below:
```
level=fatal msg="unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"
```
but the service automatically restarts and joins successfully
Found using automation testing

**Steps To Reproduce:**
*Since it happens intermittently, it will be hard to replicate* But I have seen it happening several times when i was running automation

- Installed K3s on both server and agent, join the agent node
- Server config
```
write-kubeconfig-mode: "0644"
tls-san:
  - fake.fqdn.value
cluster-init: true
node-name: server-node
cluster-cidr: <cluster-cidr-ipv4,cluster-cidr-ipv6>
service-cidr: <service-cidr-ipv4,service-cidr-ipv6>
kubelet-arg:
 - node-ip=0.0.0.0

node-external-ip: <public-ipv4,ipv6>
node-ip: <private-ipv4,ipv6>
```
- Agent config
```
server: https://<server-public-ipv4>:6443
token:  "<token>"
node-label:
 - role-worker=true
node-name: agent-node
kubelet-arg:
 - node-ip=0.0.0.0

node-external-ip: <public-ipv4,ipv6>
node-ip: <private-ipv4,ipv6>
```
**Expected behavior:**

- Agent node join successfully on first attempt

**Actual behavior:**

- Agent node fails to join on first attempt, console shows error and log shows fatal msg. Although The service restarts and then joins successfully
```
systemd: Starting k3s-agent
Job for k3s-agent.service failed because the control process exited with error code.
See "systemctl status k3s-agent.service" and "journalctl -xeu k3s-agent.service" for details.
```
- Snippet from journal logs
```
Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=info msg="Starting flannel with backend vxlan"
Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=info msg="Flannel found PodCIDR assigned for node agent-node"
Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=info msg="Using dual-stack mode. The interface eth0 with ipv4 address <private-ipv4> and ipv6 address <private-ipv6> will be used by flannel"
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.745029    5836 kube.go:145] Waiting 10m0s for node controller to sync
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.745664    5836 kube.go:489] Starting kube subnet manager
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.747398    5836 kuberuntime_manager.go:1528] "Updating runtime config through cri with podcidr" CIDR="<cluster-cidr,service-cidr>"
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.748179    5836 kubelet_network.go:61] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="<cluster-cidr,service-cidr>"
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.756721    5836 kube.go:510] Creating the node lease for IPv4. This is the n.Spec.PodCIDRs: [<cluster-cidr service-cidr>]
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.756770    5836 kube.go:543] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [<cluster-cidr service-cidr>]
Dec 18 20:55:19 agent-node k3s[5836]: I1218 20:55:19.851954    5836 kubelet_node_status.go:493] "Fast updating node status as it just became ready"
Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=fatal msg="unable to initialize Network Policy Controller: IPv6 was enabled but no IPv6 address was found on node"
Dec 18 20:55:20 agent-node systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 20:55:20 agent-node systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
Dec 18 20:55:20 agent-node systemd[1]: Failed to start Lightweight Kubernetes.
Dec 18 20:55:20 agent-node systemd[1]: k3s-agent.service: Consumed 2.956s CPU time.
Dec 18 20:55:25 agent-node systemd[1]: k3s-agent.service: Scheduled restart job, restart counter is at 1.
Dec 18 20:55:25 agent-node systemd[1]: Stopped Lightweight Kubernetes.
Dec 18 20:55:25 agent-node systemd[1]: k3s-agent.service: Consumed 2.956s CPU time.
Dec 18 20:55:25 agent-node systemd[1]: Starting Lightweight Kubernetes...
Dec 18 20:55:25 agent-node sh[5935]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Dec 18 20:55:25 agent-node k3s[5939]: time="2023-12-18T20:55:25Z" level=info msg="Starting k3s agent v1.28.4+k3s2 (6ba6c1b6)"
```

**Additional context / logs:**

- Log from agent node
[k3s-agent-fail-ds.log](https://github.com/k3s-io/k3s/files/13719126/k3s-agent-fail-ds.log)

CC: @rancher-max @manuelbuil

**Comment by brandond** [comment]
Was there a copy-paste problem, or are you seeing two different errors? In once place I see IPv4, in another I see IPv6.

* `level=fatal msg="unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"`
* `Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=fatal msg="unable to initialize Network Policy Controller: IPv6 was enabled but no IPv6 address was found on node"`

I have seen this in the past, it appears to be caused by the network policy controller starting up before all the addresses have been set on the node object. We might need to add some extra code to delay starting the NPC until after the correct addresses have all been set?

**Comment by mdrahman-suse** [comment]
> Was there a copy-paste problem, or are you seeing two different errors? In once place I see IPv4, in another I see IPv6.
> 
> * `level=fatal msg="unable to initialize Network Policy Controller: IPv4 was enabled but no IPv4 address was found on node"`
> * `Dec 18 20:55:19 agent-node k3s[5836]: time="2023-12-18T20:55:19Z" level=fatal msg="unable to initialize Network Policy Controller: IPv6 was enabled but no IPv6 address was found on node"`
> 
> I have seen this in the past, it appears to be caused by the network policy controller starting up before all the addresses have been set on the node object. We might need to add some extra code to delay starting the NPC until after the correct addresses have all been set?

The copy paste was done from two different versions, ipv4 from `v1.29.0-rc1+k3s1` and ipv6 from `v1.28.4+k3s2 (6ba6c1b6)`
IMHO Adding a check and delay starting would be better option

**Comment by brandond** [comment]
Yeah, flannel tells you it's using both - but the kube-router network policy controller looks at the node object, and not the actual interface, and gets confused.

**Comment by manuelbuil** [comment]
thanks @mdrahman-suse . It never happened to me but we can certainly add a check. Isn't there a node annotation we can query to verify that the cloud provider is ready with the node addresses?

**Comment by brandond** [comment]
the cloudprovider removes the `node.cloudprovider.kubernetes.io/uninitialized` taint when the addresses have been set; that might be good to key off of?

**Comment by manuelbuil** [comment]
I had some time to work on a possible solution. Have a look!
