### ISSUE TITLE
Update flannel to v0.24.0 and remove multiclustercidr flag

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#9074]
multiclustercidr feature gate has been removed in 1.29 as well ass ClusterCidr type in networking group, it requires changes to flannel and k3s to remove the flag and functionality of this feature

**Comment by galal-hussein** [comment]
As per @brandond [review](https://github.com/k3s-io/k3s/pull/9075#discussion_r1431972648), removing the flag can make an issue with HA servers since it was a criticalControlArg, the removal should be validated by testing an upgrade of HA cluster from 1.28 to 1.29

**Comment by rancher-max** [comment]
Validated that both manual and SUC upgrade to v1.29.0-rc2+k3s1 is successful when this flag is present.
```
$ journalctl -eu k3s | grep -i multi
Dec 20 22:05:58 ip-172-31-14-88 k3s[13226]: time="2023-12-20T22:05:58Z" level=warning msg="Unknown flag --multi-cluster-cidr found in config.yaml, skipping\n"
```

Validated that the flag does not exist in v1.29.0-rc2+k3s1.
```
$ k3s server --help | grep -i multi
(no result)
```

Validated that flannel is using v0.24.0 and network checks continue to function as expected.
```
$ /var/lib/rancher/k3s/data/current/bin/flannel
CNI Plugin flannel version v0.24.0 (linux/amd64) commit HEAD built on 2023-12-19T22:57:25Z
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
```
