### ISSUE TITLE
k3s etcd-backup /etc/ranchar/k3s/config.yaml.d/*.yaml  show a weird warning

### ISSUE THREAD

**Issue by xiaomaoaichiyu** [k3s-io/k3s#9085]
**Environmental Info:**
K3s Version:

```
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8
```
Node(s) CPU architecture, OS, and Version: 

```
node1: Linux node1 6.2.0-37-generic 38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
node2: Linux node2 6.2.0-36-generic 37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
node3: Linux node3 5.4.0-155-generic 172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

3 servers
**Describe the bug:**

I want to use k3s etcd-snapshot cron script to upload the snapshots to S3.
config the config.yaml file in /etc/ranchar/k3s/config.yaml.d/s3-backup.yaml with below:
```
etcd-snapshot-schedule-cron: "*/5 * * * *"
etcd-snapshot-retention: 5
etcd-s3-endpoint: minio.com
etcd-s3: true
etcd-s3-access-key: <access-key>
etcd-s3-secret-key: <secret-key>
etcd-s3-bucket: test
etcd-s3-insecure: true
```
It works fine with only one weird problem when I use `k3s etcd-snapshot ls` to list the snapshots:
![image](https://github.com/k3s-io/k3s/assets/40788520/42550dbe-2268-4128-96fb-c9644fbaa3ff)

There are two warning about unknown flag `--etcd-snapshot-schedule-cron` and `--etcd-snapshot-retention`.
I am sure the cron script works fine and s3 get the snapshots automatically generated.
Maybe this is just a bug for some reason?

**Steps To Reproduce:**

- Installed K3s: 
- config the etcd-snapshot s3 upload flag:
  - --etcd-snapshot-schedule-cron
  - --etcd-snapshot-retention 
- use `k3s etcd-snapshot ls`

**Expected behavior:**

only the snapshots and some info of s3 configurations.
**Actual behavior:**

weird warning of unknown flag.

**Additional context / logs:**

**Comment by brandond** [comment]
All CLI commands parse the config file and convert its contents to CLI flags, but not all CLI flags are supported by every CLI subcommand. If the command doesn't support the flags that are present in the config file, you'll see those warnings. This is expected behavior.
