### ISSUE TITLE
K3S endless uploading in flannel when using tailscale nets

### ISSUE THREAD

**Issue by Arc-2023** [k3s-io/k3s#9097]
**Environmental Info:**
K3s Version: 
```
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10
```
Node(s) CPU architecture, OS, and Version: 
```
master: Linux iZ7xv94skt77mf2yvijojdZ 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

```
agent: Linux arc-virtual-machine 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

> 1 master and 1 agent

1. Network Configuration: The master node is on the public network and is a VPS, while the agent is on the local network and is a virtual machine (behind NAT).
2. Cluster Interconnection Solution: Utilizing Tailscale virtual network interfaces for traffic proxying, facilitating information exchange between the public network and the local network.
3. Specific Configuration:
   - Master Node (with a public IP):
     ```bash
     ExecStart=/usr/local/bin/k3s \
         server \
         --node-external-ip=100.xxx (private IP of the master's Tailscale) --flannel-backend=wireguard-native --flannel-external-ip \
         --disable=traefik \
         --secrets-encryption
     ```
   - Agent Node (without a public IP):
     1) service.env:
        ```bash
        K3S_TOKEN=xxx (master's token)
        K3S_URL='https://8.xx (master's public IP):6443'
        ```
     2) service:
        ```bash
        ExecStart=/usr/local/bin/k3s \
            agent \
            '--node-external-ip=tailscale ip(100.xx)' \
            '--with-node-id'
        ```
        
        
1. Expected Results: Successful connection establishment between master and slave devices through the Tailscale channel. The traffic from the main server should be routable to the slave server, and vice versa. No abnormal traffic or errors are expected.

2. Actual Results:
   1) Prolonged and extensive packet transmission between master and slave devices through the Flannel interface (packet transmission speed is CPU bottlenecked, reaching 500Mbps on my server, with successfully transmitted packets being limited by the server's upload bottleneck).
     ![image](https://github.com/k3s-io/k3s/assets/64178177/1664c12e-7d96-46b2-8586-07b3226d9f49)
   2) In the scenario described in 1), devices are unable to communicate, and all requests are blocked. Additionally, the network and CPU are overwhelmed by a large volume of packet transmission, rendering the system completely inoperable.

   
   3) When encountering the aforementioned issues, the K8s dashboard does not show any errors related to "communication issues between servers." Based on my observations, only the metrics server in the kube-system namespace reports errors.
     ![image](https://github.com/k3s-io/k3s/assets/64178177/c53c22c0-65b0-4f2e-80f1-a6edc774201a)

3. My Analysis:
   1) When using Tailscale, the latency is mostly around 50ms. However, every few minutes, there is a fluctuation,
![image](https://github.com/k3s-io/k3s/assets/64178177/0b7b0a4e-935a-41f7-9724-09f1ad0b8482)
（master node ping agent node's private ip allocated by tailscale）
 and after the fluctuation, the issue of extensive packet transmission occurs.

4. Conclusion:
  - K3S or other accompanying tools exhibit problems. When facing network fluctuations, there is an issue of incessant packet transmission, severely impacting system operation.
- However, perhaps this issue is caused by abnormal behavior when k3s exchanges information exceeding the bandwidth bottleneck, and I am currently unable to make a definitive judgment.

**Comment by brandond** [comment]
Have you tried using the K3s native tailscale integration? The way you're doing it, you're running vxlan over tailscale wireguard - so your problems are probably related to MTU mismatch somewhere across your network. You might need to play with the interface MTUs until you stop seeing drops and retransmits.

**Comment by Arc-2023** [comment]
> Have you tried using the K3s native tailscale integration? The way you're doing it, you're running vxlan over tailscale/wireguard - so your problems are probably related to MTU mismatch somewhere across your network. You might need to play with the interface MTUs until you stop seeing drops and retransmits.
> 
> ref: https://docs.k3s.io/installation/network-options#integration-with-the-tailscale-vpn-provider-experimental

Yeah, I've tried using K3s native tailscale integration, it worked fine.
tks for answering

**Comment by cristianrat** [comment]
@Arc-2023 did you change your config to use native tailscale integration or setup a new cluster?
not sure if it's possible to switch? Am having these exact issues

EDIT: yes, it is possible to switch and seems to have fixed my issues. a whole day wasted on debugging crap
