### ISSUE TITLE
Using LoadBalancer type svc will cause the node apiserver to lose contact

### ISSUE THREAD

**Issue by clcc2019** [k3s-io/k3s#9100]
**Environmental Info:**
K3s Version: 
```yaml
k3s version v1.29.0+k3s1 (3190a5fa)
go version go1.21.5

```
Node(s) CPU architecture, OS, and Version: 
```yaml
Linux xx6.5.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.8-1 (2023-10-22) x86_64 GNU/Linux

```
Cluster Configuration:
```yaml
ExecStart=/usr/local/bin/k3s \
    server \
	'--node-external-ip=xxxxxx' \
	'--flannel-backend=wireguard-native' \
        '--kube-proxy-arg=proxy-mode=ipvs' \
	'--flannel-external-ip' \
```
**Describe the bug:**
Modify the svc type to loadbalancing, mark some nodes to use svclb, and then the nodes will be notready

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
> Modify the svc type to loadbalancing, mark some nodes to use svclb, and then the nodes will be notready

Modify which service? Can you provide specific steps to reproduce this?
