### ISSUE TITLE
Validate Redhat 8.9

### ISSUE THREAD

**Issue by harsimranmaan** [k3s-io/k3s#9101]
**K3s Versions to be Validated**
K8s 1.27, 1.28, 1.29

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

**Comment by ShylajaDevadiga** [comment]
RHEL 8.9 is already validated here https://github.com/k3s-io/k3s/issues/9005
