### ISSUE TITLE
The variable "K3S_DATASTORE_ENDPOINT" does not seem to recognize the database name other than "postgres"

### ISSUE THREAD

**Issue by luvres** [k3s-io/k3s#9109]
**In version "v1.28.5+k3s1" the variable "K3S_DATASTORE_ENDPOINT" does not seem to recognize the database name other than "postgres":**

**My configuration:**
```K3S_DATASTORE_ENDPOINT="postgres://user:pass@hostname:5432/k3s```

**The error:**
failed to connect to host=postgres.iazone.lo user=controlplane database=postgres: server error (FATAL: no pg_hba.conf entry for host \"localhost\", user \"user\", database \"postgres\

**Comment by brandond** [comment]
This would appear to be an error from the server - the message is showing what appears to be the correct host, user, and database. It is the server itself that is returning a different message - although you appear to have cut off the end of the message.

`failed to connect to host=postgres.iazone.lo user=controlplane database=postgres: server error`

The **server** is returning the rest of the error message: `FATAL: no pg_hba.conf entry for host "localhost"`

**Comment by luvres** [comment]
The problem is that even if you define the name of the database, k3s v1.28.4+k3s1 onwards only recognizes the "postgres" database. I'm currently using v1.29.0+k3s1 and adjusted it to use the "postgres" database. Even version v1.28.3+k3s1 recognizes the database configuration passed in the K3S_DATASTORE_ENDPOINT variable

**Comment by th0th** [comment]
I am having the same issue with `v1.29.0+k3s1`.

@brandond isn't the database in the message different than the one defined in `K3S_DATASTORE_ENDPOINT`?

Database name in `postgres://user:pass@hostname:5432/k3s` is `k3s`. But the error says it failed connecting to the `postgres` database.

Here is my relevant log line:

```
Jan 20 01:54:55 k3s-master k3s[4264]: time="2024-01-20T01:54:55Z" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: failed to connect to `host=10.0.0.2 user=k3s database=postgres`: server error (FATAL: no pg_hba.conf entry for host \"10.0.0.3\", user \"k3s\", database \"postgres\", SSL encryption (SQLSTATE 28000))"
```

And my `K3S_DATASTORE_ENDPOINT=postgres://k3s:password@10.0.0.2:5432/k3s`.

**Comment by brandond** [comment]
Same issue as https://github.com/k3s-io/k3s/issues/9111#issuecomment-1901744845
