### ISSUE TITLE
The variable "K3S_DATASTORE_ENDPOINT" not resolved yet.

### ISSUE THREAD

**Issue by luvres** [k3s-io/k3s#9111]
The problem is that even if you define the name of the database, k3s v1.28.4+k3s1 onwards only recognizes the "postgres" database. I'm currently using v1.29.0+k3s1 and adjusted it to use the "postgres" database. Even version v1.28.3+k3s1 recognizes the database configuration passed in the K3S_DATASTORE_ENDPOINT variable
```
curl -sfL https://get.k3s.io | \
...
K3S_DATASTORE_ENDPOINT="postgres://USER:PASS@HOSTNAME:5432/db_k3s?sslmode=verify-full" \
...
INSTALL_K3S_VERSION=v1.28.5+k3s1 sh -s - server
```
In this example "db_k3s" is ignored and considers "postgres"

**Comment by brandond** [comment]
That is not what's happening. K3s always connects to the postgres database initially, in order to test for existence of the k3s database. See https://github.com/k3s-io/k3s/issues/9033#issuecomment-1850412488

**Comment by th0th** [comment]
> That is not what's happening. K3s always connects to the postgres database initially, in order to test for existence of the k3s database. See [#9033 (comment)](https://github.com/k3s-io/k3s/issues/9033#issuecomment-1850412488)

Is this new? Because I never had a line allowing k3s to access the database `postgres` in my `pg_hba.conf`, and it was working before?

**Comment by brandond** [comment]
For as long as I can remember.

**Comment by th0th** [comment]
Thanks for the information @brandond, but I didn't fully get it. Should k3s's postgresql user should have access to `postgres` database as well? Or only allowing connection in `pg_hba.conf` but not giving access enough?

**Comment by brandond** [comment]
Not sure, please let us know what you find out!

**Comment by thpham** [comment]
Hello, in my situation, I rely on a managed postgresql instance which doesn't allow access to `postgres` database and this broke my ability to upgrade k3s to a newer version than `v1.28.3-k3s1`. This looks to me like a regression , isn't it ?

**Comment by brandond** [comment]
It doesn't allow access to it, or you haven't granted access to it? As per https://github.com/k3s-io/k3s/issues/9033#issuecomment-1850412488 the upstream postgres docs indicate that access to the postgres database should be safe to assume.

**Comment by ringerc** [comment]
As a postgres contributor, I would never recommend that any application ignore the configured connection string and connect to the `postgres` database.

Yes, it's commonly used by utilities, but apps should accept what they are given; they cannot assume the administrator will grant the user they are connecting as the privileges to connect to DBs other than the one specified to the application.
