### ISSUE TITLE
Print error when downloading file error inside install script

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#9154]
This issue is to track the work done in #6874 by user @if-nil 

> When an error occurs in the download function of the installation script, the program will simply exit due to the effect of 'set -e':
> ```
> ubuntu@test:~$ ./install.sh
> [INFO]  Finding release for channel stable
> [INFO]  Using stable as release
> [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
> ubuntu@test:~$
> 
> ```
> 
> This change can indicate a download error:
> 
> ```
> ubuntu@test:~$ ./install.sh
> [INFO]  Finding release for channel stable
> [INFO]  Using stable as release
> [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
> [ERROR]  Download failed
> ubuntu@test:~$
> ```

**Comment by VestigeJ** [comment]
Confirmed previous behavior 
//previous install.sh missing set values in download() function
$ sudo INSTALL_K3S_VERSION=BAD_VERSION_INTENTIONALLY INSTALL_K3S_EXEC=TRAITOR ./install-k3s.sh
```
[INFO]  Using BAD_VERSION_INTENTIONALLY as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/BAD_VERSION_INTENTIONALLY/sha256sum-amd64.txt
```

novel behavior when passing bogus information to the script 

$ sudo INSTALL_K3S_VERSION=BAD_VERSION_INTENTIONALLY INSTALL_K3S_EXEC=TRAITOR ./install-k3s.sh
```
[INFO]  Using BAD_VERSION_INTENTIONALLY as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/BAD_VERSION_INTENTIONALLY/sha256sum-amd64.txt
[ERROR]  Download failed
```
