### ISSUE TITLE
Register new node not work.

### ISSUE THREAD

**Issue by qq253498229** [k3s-io/k3s#9160]
**Environmental Info:**
K3s Version:  latest

Node(s) CPU architecture, OS, and Version: 

Linux ubuntu-96 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 20.04.6 LTS

Cluster Configuration:

**Describe the bug:**

<img width="1862" alt="image" src="https://github.com/k3s-io/k3s/assets/31200516/6fd95b8e-4f80-4377-93f8-7d49f0193894">

**Steps To Reproduce:**

- Installed K3s: 

run command: 

```
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
```

**Expected behavior:**

Register to the master node.

**Actual behavior:**

Nothing happend

**Additional context / logs:**

I have previously set up a cluster with a total of four servers. 

The main server used the following command:
`curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -`
The other servers used this command:
`curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -`

Now, I want to add four more nodes to the cluster, but I encountered a problem during registration. 

There was no error output in the console, as shown in the screenshot above. 
I don't know what went wrong. Please tell me how I should troubleshoot this error.

**Comment by qq253498229** [comment]
The complete output is as follows:

```
[INFO]  Finding release for channel stable
[INFO]  Using v1.28.5+k3s1 as release
[INFO]  Downloading hash rancher-mirror.rancher.cn/k3s/v1.28.5-k3s1/sha256sum-amd64.txt
```

I tried, but the link `rancher-mirror.rancher.cn/k3s/v1.28.5-k3s1/sha256sum-amd64.txt` cannot be accessed(404), both via HTTP and HTTPS.

I checked, and the version of the nodes in the previous cluster was v1.28.4+k3s2, which is different from the output now. How can I manually specify this version?

**Comment by brandond** [comment]
You can use the INSTALL_K3S_VERSION environment var to select a specific release to install.

We don't have any control over the rancher CN mirror, so I can't help with that.
