### ISSUE TITLE
Share podman images with K3s 

### ISSUE THREAD

**Issue by diegosiao** [k3s-io/k3s#9162]
**Is your feature request related to a problem? Please describe.**
I want to apply manifests deploying images built by podman without having to push/pull from registry.

Example:
localhost/my-keycloak:dev

**Describe the solution you'd like**
The solution would allow something like this on Minikube:
https://podman-desktop.io/blog/sharing-podman-images-with-kubernetes-cluster

**Additional context**
Not having to configure, push, and pull images dealing with local registries, but instead using local images right into the cluster is a big deal on development. Obviously, in development scnearios single nodes are more common but even with more than one node on the same machine images will always be at /var/lib/containers, right ? At least if built with a solution compliant to CRI - Container Runtime Interface like podman.

**Comment by brandond** [comment]
K3s uses containerd. If you'd like containerd to somehow share images with podman, that would need to be implemented in containerd first, before we would be able to take advantage of it here.

Alternately, if you have your own container runtime that you are managing with podman, and it implements the CRI interface, you are welcome to point k3s at it with the --container-runtime-endpoint option.

**Comment by diegosiao** [comment]
So, basically this comparison is wrong https://microk8s.io/compare.

Sorry, I though K3s was using CRI-O as container runtime.

**Comment by brandond** [comment]
Yes, there are multiple things wrong with that comparison table. I'm not sure where they came up with it, but we've never used cri-o.
