### ISSUE TITLE
NetworkPolicy has no effect

### ISSUE THREAD

**Issue by kyrofa** [k3s-io/k3s#9167]
**Environmental Info:**
K3s Version: v1.28.5+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux s1 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

Cluster Configuration:

3 servers

**Describe the bug:**

My cluster is dual stack, and the config for each node looks something like this:

```
--flannel-iface bond0
--node-ip fda5:9812:1b23:310::10,10.3.1.10
--node-external-ip 2605:1234:8978:342e:a9::10,50.100.100.228
--cluster-cidr fda5:1234:c::0/64,10.3.128.0/17
--kube-controller-manager-arg node-cidr-mask-size-ipv4=24
--kube-controller-manager-arg node-cidr-mask-size-ipv6=80
--service-cidr fda5:1234:5::0/112,10.3.64.0/18
--cluster-dns fda5:1234:5::10
--flannel-ipv6-masq
--bind-address fda5:9812:1b23:310::10
--advertise-address fda5:9812:1b23:310::10
--kube-cloud-controller-manager-arg webhook-bind-address=fda5:9812:1b23:310::10
--disable traefik
--disable servicelb
```

I created the following NetworkPolicy:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: mynamespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

However, the pods in mynamespace are still able to reach out to the internet and each other like normal. No other NetworkPolicy exists.

**Expected behavior:**
I expect the result of applying that NetworkPolicy to be no inbound or outbound traffic allowed on any pod in the `mynamespace` namespace.

**Actual behavior:**
The NetworkPolicy appears to do nothing.

I have come across issues like https://github.com/k3s-io/k3s/discussions/5314 that lead me to believe this might have something to do with dual stack, but @brandond's comment there leads me to believe that k3s' network policy controller should be able to handle dual stack now. I'm not sure how to troubleshoot further, any help would be appreciated.

**Comment by brandond** [comment]
Can you attach:
* The complete logs from the `k3s` service on this node: `journald -u k3s --no-pager &> k3s.log`
* The output of `kubectl get networkpolicy -A`
* The output of `iptables-save`
* The output of `ipset save`

cc @manuelbuil

**Comment by kyrofa** [comment]
Okay I created a minimal reproducer and.... it worked :thinking: . Still poking a bit, but this is starting to look like _I_ am the problem.

**Comment by kyrofa** [comment]
Yeah I'm not sure what happened here, but I can't duplicate now. I will re-open if I figure it out. Thanks @brandond!
