### ISSUE TITLE
Please readd s390x support

### ISSUE THREAD

**Issue by azouhr** [k3s-io/k3s#9222]
Hi, 

I am aware that s390x just recently has been removed from the builds (Request #8987). This is kind of unfortunate for me, and I wonder if I can help bringing this forward again. Let me shortly explain the situation.

I just got the permission to deploy Kubernetes on s390x (Mainframe). However, all normal kubernetes distributions with etcd require three (an uneven number of) different sites to run kubernetes in a highly available setup, while all major Mainframe setups use two datacenters for HA setups.

So, my plans were to use k3s with an external database to run a highly available kubernetes environment.

The alternative would be to run two complete standalone k8s environments in each datacenter, and have a cluster manager that coordinates services between the two different k8s deployments. However, there is a lot of overhead with CPU and Memory involved, which both are relatively expensive on that hardware.

I can offer to actively participate in a form that I care for testing and documenting that setup as well as promoting such a setup in Mainframe Linux communities. It would be nice if you reconsider the decision of not providing s390x support. I am just now in the situation that I am allowed to go for that solution.

**Comment by brandond** [comment]
We still do not have access to build hardware for S390x, and do not have a solid timeline for its return. If we do regain access, we question whether or not it is worth supporting it, as it sees even less use than 32-bit arm.

**Comment by azouhr** [comment]
> We still do not have access to build hardware for S390x

What kind of machines would you need to build for s390x? Do you have an idea about CPU/Memory/Access Type? Would some virtual servers be sufficient for you?

> If we do regain access, we question whether or not it is worth supporting it, as it sees even less use than 32-bit arm.

Totally understood. This is something I am going after at the moment, for one, I would be a user for myself, but I am also pushing IBM to give it a try (just did that yesterday, when I heard from some IBMer that you are dropping support for s390x). From a technology perspective, k3s is just a natural fit to Mainframes, from a political perspective this might be more difficult, but I would give it a try.

**Comment by pleia2** [comment]
I use k3s often as a demonstration to potential users of Kubernetes on the mainframe, and I'm sad to see this support dropped.

My team at IBM runs a program provide no-cost, permanent (renewed annually) Virtual Machines to open source communities releasing for s390x. I'd be more than happy to grant one to the k3s community. The application is here: https://www.ibm.com/community/z/open-source/virtual-machines-request/

**Comment by cwayne18** [comment]
oh heya @pleia2, funny seeing you here :)

For the record, we are still planning to support RKE2 on s390 for the longer term (once we get some issues sorted out), so for folks needing kubernetes on s390, SUSE still has a supported distro for you!  That said, we'll certainly take this under advisement and work with our PM team to determine if it's something we'd like to do for k3s

**Comment by NeilHanlon** [comment]
Hi folks,

I'm quite interested also in having k3s available, as we use k3s on s390x as part of building Rocky Linux.

Of note, we also want ppc64le support, and are willing to contribute time and resources to making both of these architectures first-class citizens in k3s. (see #6886).

Best,
Neil

**Comment by azouhr** [comment]
For the time being, and until there is a decision, I just made a submit request with current k3s to OBS. See also https://build.opensuse.org/request/show/1139528 . OBS on s390x is slow at the moment, but since I have a private instance with sufficient resources, I will be able to go forward with this for the time being. 
The builds already were successful on my laptop  for x86_64 and also (via qemu-s390x) for s390x. I think, this takes some time pressure from this issue.

**Comment by grisu48** [comment]
Hey, I'm joining late to the party but we (SUSE QE-C) are depending on k3s as kubernetes platform for testing all kubernetes related SLES packages. While for now we could also rely on older versions, we kinda need a recent testing platform to continue our testing efforts.

**Comment by BbolroC** [comment]
> oh heya @pleia2, funny seeing you here :)
> 
> For the record, we are still planning to support RKE2 on s390 for the longer term (once we get some issues sorted out), so for folks needing kubernetes on s390, SUSE still has a supported distro for you! That said, we'll certainly take this under advisement and work with our PM team to determine if it's something we'd like to do for k3s

No more good news for s390x? With https://github.com/rancher/rke2/issues/5133, I was wondering if the decision is final that there will be no Kubernetes cluster support from SUSE on s390x.

**Comment by brandond** [comment]
As far as we could tell, we had one community user for k3s on s390x, no users for rke2 and no paying customers for either. It just wasn't worth it.

**Comment by Stefan-Raspl** [comment]
Hi - could you please check within SUSE? I did refer a couple of interested clients to SUSE in the previous months, and as far as I know, Rancher is making a comeback on s390x.

**Comment by NeilHanlon** [comment]
Rocky Linux is also deploying our build and test (OpenQA!) infrastructure on k3s, including and especially on alternative architectures like s390x and powerpc. It's frustrating to say the least to have to maintain my own forked builds of k3s because of an (incorrect) assumption that it's not worth Rancher's time.

**Comment by NeilHanlon** [comment]
And, naught for nothing, but "As far as we could tell" reads as "we didn't even bother asking"

**Comment by brandond** [comment]
Your assumption is incorrect, but please continue to air what you perceive to be dirty laundry in public.
