### ISSUE TITLE
CoreDNS override clobbered by reboot

### ISSUE THREAD

**Issue by hlx-a1** [k3s-io/k3s#9223]
**Environmental Info:**
K3s Version: 
```
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8
```

Node(s) CPU architecture, OS, and Version: 
`Linux core-k8s-1 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
3 servers, 1 master, 2 agents

**Describe the bug:**
Our workload requires a custom DNS zone to function. To implement this I do 6 things:
1. `mv /var/lib/rancher/k3s/server/manifests/coredns.yaml /var/lib/rancher/k3s/server/manifests/coredns.yaml.backup`
1. `mv coredns.override.yaml /var/lib/rancher/k3s/server/manifests/`
1. `mv coredns.custom.yaml /var/lib/rancher/k3s/server/manifests/`
1. `k3s kubectl apply -f /var/lib/rancher/k3s/server/manifests/mv coredns.override.yaml`
1. `k3s kubectl apply -f /var/lib/rancher/k3s/server/manifests/mv coredns.custom.yaml`
1. delete the coredns pod so that the new one picks up the custom.yaml

**Steps To Reproduce:**
1. `curl -sfL https://get.k3s.io | sh -`
3. `mv /var/lib/rancher/k3s/server/manifests/coredns.yaml /var/lib/rancher/k3s/server/manifests/coredns.override.yaml`
4. `sed -i 's/cache 30/cache 10/' /var/lib/rancher/k3s/server/manifests/coredns.override.yaml`
5. `reboot`
- Installed K3s: 

**Expected behavior:**
I expected the contents of the `kube-system/coredns` ConfigMap to match `/var/lib/rancher/k3s/server/manifests/coredns.override.yaml`

**Actual behavior:**
1. `/var/lib/rancher/k3s/server/manifests/coredns.yaml` was created despite being removed earlier
2. the contents of `kube-system/coredns` ConfigMap do *not* match `/var/lib/rancher/k3s/server/manifests/coredns.override.yaml`

**Additional context / logs:**
I just want a way to serve a custom CoreDNS zone in a way that persists across reboots.

**Comment by brandond** [comment]
> `mv /var/lib/rancher/k3s/server/manifests/coredns.yaml /var/lib/rancher/k3s/server/manifests/coredns.override.yaml
> `sed -i 's/cache 30/cache 10/' /var/lib/rancher/k3s/server/manifests/coredns.override.yaml`

Putting `.override` in the filename does nothing. K3s will restore the original coredns.yaml when you restart it, and you will then have two copies of the coredns deployment.

You should name the file custom-coredns.yaml or something along those lines (so that it has a unique basename), and start k3s with `--disable=coredns` to prevent it from deploying the default manifest.

See https://docs.k3s.io/installation/packaged-components#packaged-components for more information.
