### ISSUE TITLE
macvlan is not included as cni plugin

### ISSUE THREAD

**Issue by rfx77** [k3s-io/k3s#9224]
the cni binary (/var/lib/rancher/k3s/data/current/bin/cni) of k3s is statically built with plugin-release https://github.com/rancher/plugins/tree/v1.3.0-k3s1

in this release (main_linux.go) the macvlan  plugin is missing. 

is there a reason for that?

this leads to problems when installing multus.

**Comment by brandond** [comment]
K3s only includes  the bits necessary for the bundled components and core Kubernetes functionality.  If you add your own components, or replace the default flannel CNI with something else, you may need to provide additional binaries or packages.

We can leave this open to evaluate adding that plugin to the bundled multicall binary, but I don't believe it is a priority.

**Comment by rfx77** [comment]
The argument for adding this is that its just about one or two lines of code an then multus and kubevirt would run out of the box without overwriting all cni binaries. 

the concept of this reexec binary which you have is very nice and i would like to avoid replacing it on every installation with cni binaries where i cannot be sure if they are as compatible as the ones provided by k3s

**Comment by brandond** [comment]
We're not going to do this at the moment, as this only enables one of many possible multus configurations. We'll keep the CNI plugins bundled by k3s to the bare minimum required for a functional Kubernetes cluster, and work on documenting how to best deploy all the additional plugins that are required to make multus useful.
