### ISSUE TITLE
Improve k3s airgap boot time for large number/size of images

### ISSUE THREAD

**Issue by harsimranmaan** [k3s-io/k3s#9242]
**Is your feature request related to a problem? Please describe.**

K3s loads images from the `agent/images` folder synchronously. As documented in https://github.com/rancher/rke2/issues/773, it can be very slow to reboot/start k3s to get  a functional control plane and data plane. The image load blocks until all img "sources" are loaded

**Describe the solution you'd like**

Provide a way to order the loading of system images(k3s, user provided) followed by other app images. Unblock k3s start and let all other images load in the background with a configurable number of goroutines. While this will not solve the problem when a giant image bundle is used but would help in cases where the bundle can be split and the chunks are loaded in a user-defined order with lazy-loading support. A simpler implementation that allows specifying the parallelization and an order based on file names would suffice to begin with. 

**Describe alternatives you've considered**

**Additional context**

We are loading a 30GB zst compressed image bundle at k3s boot. The start takes >10mins. Splitting into multiple smaller bundles is not very helpful as the loading is not concurrent.

**Comment by brandond** [comment]
My recommendation for this in the past has been as follows:
1. Place only the REQUIRED images in the images dir
2. Manually load the remaining optional images via an `ExecStartPost` script referenced from the systemd unit.

**Comment by brandond** [comment]
I'm not convinced that K3s itself needs to have native support for staged and/or parallel import, given the options described above. Can you make a case for why this needs to be built in to k3s, given that the user has other options for importing images one containerd has been started?

**Comment by harsimranmaan** [comment]
My only arguments would be ease of use for the operator. Also, I am not sure that ctr supports importing `zst` compressed images. k3s provides an edge when it comes to have a simplified airgap experience. The only struggles have been around loading large bundles.

**Comment by brandond** [comment]
Something like this should work, assuming you have the `zstd` package for your distro installed.
```
ExecStartPost=for FILE in /var/lib/rancher/k3s/agent/extra-images/*.zst; do zstdcat $FILE | ctr -n k8s.io image import --all-platforms --no-unpack -; done
```

**Comment by brandond** [comment]
I think I will close this as unplanned at the moment, given the above workaround. but we can reevaluate in the future.

cc @caroline-suse-rancher

**Comment by pkpbynum** [comment]
Could we re-evaluate this now that #9759 is implemented? Specifically, it would it would still be great if at least the required images were imported in parallel. We always use airgap installs--including in our CI/CT--and currently the long tail of our boot time is by far the image import. It takes ~5 seconds for a machine to boot and then ~60 seconds for all the images to be imported. Reducing this could have a significant impact

**Comment by brandond** [comment]
In my experience, the import is IO-bound. Doing more of them at once would make each individual import slower, not faster, due to contention with IO from the other concurrent imports... and take the same net amount of time, if not more. The best way to make it go faster is to run k3s on faster disk.
