### ISSUE TITLE
k3s server issue with Round robin Load Balancer

### ISSUE THREAD

**Issue by framctr** [k3s-io/k3s#9244]
**Environmental Info:**
K3s Version: 
v1.29.0+k3s1

Node(s) CPU architecture, OS, and Version: 
CPU: x86_64
OS: Fedora CoreOS
Version: 39.20231204.3.3
Linux: 6.6.3-200.fc39.x86_64

Cluster Configuration:
3 servers, 2 agents
OpenStack LoadBalancer for the 3 control plane servers exposing kube api (port 6443). Load balancing method is Round Robin.

**Describe the bug:**
The system starts up, servers join the first one with token. When I try to get metrics it seems that because the OpenStack Load balancer round robin cycles through the servers, only the one with the metrics answers correctly.

```
# first time
$ kubectl top no
NAME                       CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
server-00   136m         6%     717Mi           4%        
server-01   86m          4%     553Mi           3%        
server-02   108m         5%     562Mi           3%        
agent-00    31m          1%     370Mi           2%        
agent-01    32m          1%     371Mi           2%        
# second time
$ kubectl top no
error: Metrics API not available
# third time
$ kubectl top no
error: Metrics API not available
# and so on...
$ kubectl top no
NAME                       CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
server-00   136m         6%     717Mi           4%        
server-01   86m          4%     553Mi           3%        
server-02   108m         5%     562Mi           3%        
agent-00    31m          1%     370Mi           2%        
agent-01    32m          1%     371Mi           2%        
```

**Steps To Reproduce:**
- common server args: `--selinux --tls-san loadbalancer-public-ip --disable-cloud-controller --disable=servicelb --kubelet-arg='cloud-provider=external'`
- common agent args: `--kubelet-arg='cloud-provider=external'`
- Installed K3s on first server node: `k3s server --cluster-init`
- Installed K3s on other server nodes: `k3s server --server https://${first-server-node-ip}:6443 --token ${first-server-token}` token taken on first server node at `/var/lib/rancher/k3s/server/token`
- Installed K3s on agent nodes: `k3s agent --server https://${first-server-node-ip}:6443 --token ${first-server-agent-token}` token taken on first server node at `/var/lib/rancher/k3s/server/node-token`
- Result is:
```
$ kubectl get no
NAME                       STATUS   ROLES                       AGE   VERSION
server-00   Ready    control-plane,etcd,master   43m   v1.29.0+k3s1
server-01   Ready    control-plane,etcd,master   42m   v1.29.0+k3s1
server-02   Ready    control-plane,etcd,master   42m   v1.29.0+k3s1
agent-00    Ready    <none>                      41m   v1.29.0+k3s1
agent-01    Ready    <none>                      41m   v1.29.0+k3s1
```
- Install [OCCM](https://github.com/kubernetes/cloud-provider-openstack)
- Wait for all the components to start (e.g., metrics server)
- try `kubectl top no` multiple times like in the previous section.

**Expected behavior:**
Metrics server always answers from any server node.

**Actual behavior:**
See _Describe the bug_ section

**Additional context / logs:**
Tried with no firewall/security groups restrictions. [k3s-selinux](https://github.com/k3s-io/k3s-selinux) installed correctly. Issue not depending on OS.

**Comment by brandond** [comment]
Check the logs on the server nodes, in particular the ones not running metrics-server. The behavior suggests that the apiserver on some of the nodes is unable to reach the pod metrics-server pod if it is not running locally, which would indicate a problem with CNI traffic between your nodes getting dropped. Make sure that you have opened all the correct ports for whatever flannel backend you are using. You may also want to try disabling tcp checksum offload on the flannel interface; this is a common issue on nodes with buggy virtual NIC drivers.

**Comment by framctr** [comment]
Thanks @brandond . I will check it out.

**Comment by framctr** [comment]
@brandond Is there a way to change MTU in k3s at startup? I mean when installed. I see no options for setting flannel config

**Comment by framctr** [comment]
Ok thanks @brandond . After some research, I found it could related to DNS issue. See issue #9281 .

**Comment by brandond** [comment]
I am closing this alongside the other issue, as it appears to be an issue with your environment, and not a problem with k3s.

**Comment by framctr** [comment]
Just to log the solution. I solved this issue by both solving the DNS issue #9281 and setting OpenStack security group for Flannel VXLAN (port 8472) from TCP to UDP.

**Comment by brandond** [comment]
Ah, that would do it. Ports and protocols are listed here: https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-server-nodes
