### ISSUE TITLE
Bump cni-plugins to v1.4.0

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9248]
CNI Plugins v1.4.0 was released in early December, we should update from v1.3.0.

**Comment by rancher-max** [comment]
#### Validated using `master` branch commitid `de825845b2f1eca82c19892c327ed274abfa8901`
 ```
 Command:
 /var/lib/rancher/k3s/data/current/bin/cni 
 ---------------------
 Assertion:
 v1.4.0-k3s2
 ----------------------
 Matched with result:
 CNI plugins plugin v1.4.0-k3s2CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
 ```

Standard network checks continue to function properly
