### ISSUE TITLE
[HA] k3s master nodes should check if the bootstrap data isnt available

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#925]
**Version:**
v0.10.0-rc2

**Describe the bug**
Currently if multiple k3s servers started in HA mode and **without** one of them having --bootstrap-data the whole cluster will fail to start and the following errors will appear:
```
Oct 19 18:16:03 ip-172-31-5-95 k3s[2986]: time="2019-10-19T18:16:03.662147564Z" level=error msg="Update cert unable to convert string to cert: Unable to split cert into two parts"
Oct 19 18:16:03 ip-172-31-5-95 k3s[2986]: time="2019-10-19T18:16:03.945490466Z" level=info msg="Connecting to proxy" url="wss://172.31.15.9:6443/v1-k3s/connect"
Oct 19 18:16:03 ip-172-31-5-95 k3s[2986]: time="2019-10-19T18:16:03.947296126Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
```

**To Reproduce**
- start external database (postgres)
- start 3 k3s servers and connect them to this database

**Expected behavior**
k3s server should fail fail properly if it can't find the bootstrap data, or as an alternative bootstrap the server if it can't find the data.

**Actual behavior**
3 masters will generate different certificates and errors above will be seen

**Comment by dereknola** [comment]
Closing as Out Of Date, HA works fine in current version of K3s (v1.20-v1.23)
