### ISSUE TITLE
k3s does not start

### ISSUE THREAD

**Issue by GhBI07** [k3s-io/k3s#9251]
I try to restart the k3s service but i get this error 

bash[463359]: {"level":"info","ts":"2024-01-17T14:53:45.197+0100","caller":"raft/raft.go:765","msg":"8d74b02af6c5f0b2 became le>
bash[463359]: {"level":"info","ts":"2024-01-17T14:53:45.197+0100","caller":"raft/node.go:325","msg":"raft.node: 8d74b02af6c5f0b>
bash[463359]: {"level":"warn","ts":"2024-01-17T14:53:55.195+0100","caller":"clientv3/retry_interceptor.go:62","msg":"retrying o>
bash[463359]: time="2024-01-17T14:53:55.195246408+01:00" level=info msg="Failed to test data store connection: context deadline>
bash[463359]: {"level":"warn","ts":"2024-01-17T14:53:55.195+0100","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.create>
bash[463359]: {"level":"warn","ts":"2024-01-17T14:53:56.636+0100","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.create>
bash[463359]: {"level":"warn","ts":"2024-01-17T14:54:00.194+0100","caller":"etcdserver/server.go:2068","msg":"failed to publish>
bash[463359]: {"level":"warn","ts":"2024-01-17T14:54:00.637+0100","caller":"clientv3/retry_interceptor.go:62","msg":"retrying o>
bash[463359]: time="2024-01-17T14:54:00.637298258+01:00" level=error msg="Failed to check local etcd status for learner managem>
{"level":"warn","ts":"2024-01-17T14:54:00.637+0100","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.create>

### Adding template for additional context

**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by GhBI07** [comment]
k3s version v1.21.4+k3s1 (3e250fdb)
go version go1.16.6
CPU : 24 
Red Hat Enterprise Linux release 8.6 (Ootpa)
Cluster single node

and this is the logs when i try to start k3s with this command k3s server --debug
INFO[2024-01-17T20:27:00.620074018+01:00] etcd data store connection OK
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
I0117 20:27:00.621256  592566 server.go:656] external host was not specified, using 10.0.0.1
I0117 20:27:00.622095  592566 server.go:195] Version: v1.21.4+k3s1
I0117 20:27:00.624776  592566 shared_informer.go:240] Waiting for caches to sync for node_authorizer
I0117 20:27:00.625709  592566 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I0117 20:27:00.625726  592566 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0117 20:27:00.626688  592566 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I0117 20:27:00.626708  592566 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
{"level":"warn","ts":"2024-01-17T20:27:00.627+0100","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-7c77944d-5205-4585-bb8b-4750d9d85ead/127.0.0.1:2379","attempt":0,"error":"rpc error: code = ResourceExhausted desc = etcdserver: mvcc: database space exceeded"}
panic: etcdserver: mvcc: database space exceeded

goroutine 378 [running]:
github.com/rancher/k3s/pkg/cluster.(*Cluster).Start.func1(0xc012792a20, 0xc00150dc20, 0x547d538, 0xc001894900)
        /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:110 +0x165
created by github.com/rancher/k3s/pkg/cluster.(*Cluster).Start
        /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:105 +0x6b9

**Comment by brandond** [comment]
> `panic: etcdserver: mvcc: database space exceeded`

Your etcd database is too large, see https://etcd.io/docs/v3.3/dev-guide/limit/#storage-size-limit

You can raise the quota by adding `--etcd-arg=quota-backend-bytes=4294967296`. The example provided there is for 4GB; adjust as necessary for your environment.

**Comment by brandond** [comment]
> I don't have etcd command

You need to add the flag to the etcd server args, as I said above. Etcd is embedded in k3s; you will not find a standalone etcd process running to configure.

**Comment by GhBI07** [comment]
Hello @brandond ,
Thank you , the etcd problem is resolved but i still have some issue with the k3s service 

DEBU[2024-01-18T09:41:28.321958114+01:00] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
FATA[2024-01-18T09:41:28.347004746+01:00] flannel exited: failed to run command: export SUBNET_IP=$(echo $SUBNET | cut -d'/' -f 1); ip link del flannel.1 2>/dev/null; echo $PATH >&2; wg-add.sh flannel.1 && wg set flannel.1 listen-port 51820 private-key /var/lib/rancher/k3s/agent/etc/flannel/privatekey && ip addr add $SUBNET_IP/32 dev flannel.1 && ip link set flannel.1 up && ip route add $NETWORK dev flannel.1 Err: exit status 1 Output: /var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/root/bin:/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux
modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-513.9.1.el8_9.x86_64
Error: Unknown device type.
/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 26: boringtun: command not found
/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 29: boringtun: command not found
/var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 32: wireguard-go: command not found

[root@EUEMEATUFN01 ~]# yum install kmod-wireguard
Last metadata expiration check: 1:20:57 ago on Thu 18 Jan 2024 08:25:28 AM CET.
Package kmod-wireguard-6:1.0.20220627-2.el8_6.elrepo.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by brandond** [comment]
> ```
> modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-513.9.1.el8_9.x86_64
> ```

Did you need to trigger a DKMS rebuild or something? I can't really help you if the module isn't available.

> ```
> /var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 26: boringtun: command not found
> /var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 29: boringtun: command not found
> /var/lib/rancher/k3s/data/bc7e12eeb86c005efd104d57a8733f0e9fbf2ede3571bad3da2cd0326b978aed/bin/aux/wg-add.sh: line 32: wireguard-go: command not found
> ```

Also looks like you're missing some binaries. What happened to this host?

**Comment by GhBI07** [comment]
security update , we upgrade the kernel
