### ISSUE TITLE
Install cleanup cronjobs alongside k3s, to manage node disk space.

### ISSUE THREAD

**Issue by issmirnov** [k3s-io/k3s#9276]
**Is your feature request related to a problem? Please describe.**
k3s does not ship with a mechanism to manage node disk space. This can lead to disk overflow when `/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots` fills up.

**Describe the solution you'd like**
Install a root level cron hook when k3s is installed. Something like this would work:
```
# Prune unused disk images weekly
0 5 * * 1 /usr/local/bin/crictl rmi --prune
```

**Describe alternatives you've considered**
Add this as a weekly recurring systemd job, or actively highlight this danger in the documentation.

**Additional context**
See #1905 and https://github.com/k3s-io/k3s/issues/1900#issuecomment-644453072

**Comment by brandond** [comment]
The kubelet automatically cleans up images, using configurable thresholds. This is not something that should need to be done manually. Check the logs for messages from the kubelet that might suggest why this is not working on your node.

https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images

**Comment by issmirnov** [comment]
Sounds good, thank you @brandond for the guidance! Much appreciated, I will do some local digging 🙏🏻
