### ISSUE TITLE
shell installation needs a logfile

### ISSUE THREAD

**Issue by rbucker** [k3s-io/k3s#928]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**

I'm installing k3s on top of PhotonOS 3.0. The install script led me to believe that the installation completed OK.

**Describe the solution you'd like**

when I ```ps ax|grep docker``` I see that there are some resources that do not exist. for example ```registry serve /etc/docker/registry/config.yml```  Neither the path or the folder exists.it was not the only artifact/asset that was missing.

[a] I had no idea

[b] since k3s is supposed to be cut/copy/paste run... I would have expected the basic files would have been supplied.

**Describe alternatives you've considered**

still investigating... k3is not an option until I can get docker-machine or my script to install it with govm.

**Additional context**

none

**Comment by blaise-sumo** [comment]
@rbucker maybe ref this in https://github.com/rancher/k3s/issues/856 ?

**Comment by rbucker** [comment]
interesting but not good enough. Installation support is a different beast and should not be confused with the jounalctl.

**Comment by erikwilson** [comment]
k3s does not install docker, it includes containerd as part of the download.

**Comment by rbucker** [comment]
@erikwilson I never said it did. I happen search for it and tools like the registry seem to use ```docker``` in the path name??? Also docker was **never** part of my ask. It was just that the k3s instaler generate a separate log file.

**Comment by erikwilson** [comment]
Why are you expecting to see docker processes running and mixing that in with a request for installation logs? What are you expecting the installation logs to show you that is not already in the output of the install script?

**Comment by rbucker** [comment]
@erikwilson please reread my request.

**Comment by erikwilson** [comment]
Sorry, I am not understanding @rbucker. The title of the issue indicates you want a log file from install. The body of the issue indicates a misunderstanding on how k3s works by expecting docker processes to be running. They seem to be two separate issues. You seem to think the installation did not complete okay and k3s is not working correctly? Can you please elaborate on what information you are expecting to find in a logfile that would help?
