### ISSUE TITLE
Intermittent DNS resolution

### ISSUE THREAD

**Issue by framctr** [k3s-io/k3s#9281]
**Environmental Info:**
K3s Version: 
v1.29.0+k3s1

Node(s) CPU architecture, OS, and Version: 
CPU: x86_64
OS: Ubuntu
Version: 22.04
Linux: 5.15.0-91-generic x86_64

Cluster Configuration:
Single k3s instance on a OpenStack vm.

**Describe the bug:**
All pods have intermittent DNS resolution. Sometimes the names are correctly resolved, other they are not. Tried with calico and flannel and have the same result.

Example:
```
$ kubectl run curl --image curlimages/curl -ti --rm -- sh

$ # first time
$ curl https://google.it
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.it/">here</A>.
</BODY></HTML>

$ # second time
$ curl https://google.it
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.it/">here</A>.
</BODY></HTML>

$ # third time
$ curl https://google.it
curl: (6) Could not resolve host: google.it

$ # fourth time
$ curl https://google.it
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.it/">here</A>.
</BODY></HTML>

$ # and so on...
```

**Steps To Reproduce:**
With flannel
- start k3s with `--secrets-encryption` (tried also with `--resolv-conf=/run/systemd/resolve/resolv.conf`)
- check with `curl` as in the previous section

With calico
- download calico operator in `/var/lib/rancher/k3s/server/manifests/tigera-operator.yaml`
- create calico install manifest in `/var/lib/rancher/k3s/server/manifests/calico.yaml`. See end of passages for manifest content.
- start k3s with `--secrets-encryption --flannel-backend=none --disable-network-policy --disable=traefik --cluster-cidr=192.168.0.0/16` (tried also with `--resolv-conf=/run/systemd/resolve/resolv.conf`)
- check with `curl` as in the previous section

Content of `calico.yaml`:
```yaml
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          mtu: 1400 # OpenStack network requires this
          bgp: Disabled
          ipPools:
          - blockSize: 26
            cidr: 192.168.0.0/16
            encapsulation: VXLANCrossSubnet
            disableBGPExport: true
            natOutgoing: Enabled
            nodeSelector: all()
      ---
      # This section configures the Calico API server.
      apiVersion: operator.tigera.io/v1
      kind: APIServer
      metadata:
        name: default
      spec: {}
```

> NOTE: In Flannel I can see MTU set by default to 1400. In Calico I have to specify it

CoreDNS log (configuration edited as explained on [k8s official documentation](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed)):
_When it works_:
```
[INFO] 192.168.84.11:42957 - 16758 "AAAA IN google.it.default.svc.cluster.local. udp 64 false 512" NXDOMAIN qr,aa,rd 157 0.000308816s
[INFO] 192.168.84.11:42957 - 16444 "A IN google.it.default.svc.cluster.local. udp 64 false 512" NXDOMAIN qr,aa,rd 157 0.000228169s
[INFO] 192.168.84.11:59985 - 65023 "AAAA IN google.it.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.00016282s
[INFO] 192.168.84.11:59985 - 64539 "A IN google.it.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.000149746s
[INFO] 192.168.84.11:45533 - 36497 "AAAA IN google.it.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000138448s
[INFO] 192.168.84.11:45533 - 36244 "A IN google.it.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000107664s
[INFO] 192.168.84.11:40545 - 21077 "AAAA IN google.it.openstacklocal. udp 53 false 512" NXDOMAIN qr,rd,ra 53 0.001773387s
[INFO] 192.168.84.11:40545 - 20862 "A IN google.it.openstacklocal. udp 53 false 512" NXDOMAIN qr,rd,ra 53 0.002838607s
[INFO] 192.168.84.11:59233 - 6205 "AAAA IN google.it. udp 38 false 512" NOERROR qr,rd,ra 92 0.000587768s
[INFO] 192.168.84.11:59233 - 5995 "A IN google.it. udp 38 false 512" NOERROR qr,aa,rd,ra 668 0.004778262s
```

When it does not work:
```
[INFO] 192.168.84.11:60241 - 31728 "AAAA IN google.it.default.svc.cluster.local. udp 64 false 512" NXDOMAIN qr,aa,rd 157 0.000167273s
[INFO] 192.168.84.11:60241 - 31449 "A IN google.it.default.svc.cluster.local. udp 64 false 512" NXDOMAIN qr,aa,rd 157 0.000099307s
[INFO] 192.168.84.11:49063 - 49659 "AAAA IN google.it.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.000098673s
[INFO] 192.168.84.11:49063 - 49406 "A IN google.it.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.000102226s
[INFO] 192.168.84.11:58077 - 34430 "A IN google.it.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000083266s
[INFO] 192.168.84.11:58077 - 34748 "AAAA IN google.it.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000079379s
[INFO] 192.168.84.11:56590 - 39400 "AAAA IN google.it.openstacklocal. udp 53 false 512" NOERROR qr,aa,rd,ra 53 0.000073581s
[INFO] 192.168.84.11:56590 - 39069 "A IN google.it.openstacklocal. udp 53 false 512" NOERROR qr,rd,ra 53 0.000625974s
```

In the second case it does not reach the `google.it` resolution, but it stops at `google.it.openstacklocal` and it logs also a `coredns plugin/errors read udp i/o timeout`.

**Expected behavior:**
All pods can solve DNS names without any issue.

**Actual behavior:**
Intermittent DNS resolution.

**Additional context / logs:**
Tried with no firewall/security groups restrictions. DNS resolution on host works perfectly and also with docker network bridge.

**Comment by brandond** [comment]
>  in some cases, cannot solve the name before going into timeout. 

Why can't it? Are some of your upstream resolvers timing out?

This appears to be an issue specific to your environment, not an issue with k3s or coredns.
