### ISSUE TITLE
False error "server must run as root, or with --rootless and/or --disable-agent" while K3s runs with root privileges

### ISSUE THREAD

**Issue by prokher** [k3s-io/k3s#9282]
**Environmental Info:**
K3s Version: 
```
k3s version v1.28.5+k3s1 (5b2d1271)
go version go1.20.12
```

Node(s) CPU architecture, OS, and Version: 
```
Linux devenv 6.5.13-orbstack-00121-ge428743e4e98 #1 SMP Wed Dec 27 10:22:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration: single-node cluster.

**Describe the bug:**

K3s fails with the message `server must run as root, or with --rootless and/or --disable-agent` while it is running with root privileges.

```
# journalctl -eu k3s.service
...
uid=11111(coder) gid=11111(coder) euid=0(root) egid=0(root) groups=0(root),11111(coder)
...
Jan 21 15:06:47 devenv k3s[4137]: time="2024-01-21T12:06:47Z" level=fatal msg="server must run as root, or with --rootless and/or --disable-agent"
Jan 21 15:06:47 devenv systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 15:06:47 devenv systemd[1]: k3s.service: Failed with result 'exit-code'.
```

**Steps To Reproduce:**

- Set suid bit to the Systemd binaries: `sudo chmod a+s /lib/systemd/systemd*`.
- Run the container with such Systemd.
- `systemctl start k3s`

**The way to fix:**

It seems that K3s improperly checks ID of the user running K3s. It checks UID while it should check effective UID (EUID) like OS does. I believe replacing the condition `os.Getuid() != 0` with the proper one `os.Geteuid() != 0` in [the `run(...)` function](https://github.com/k3s-io/k3s/blob/6d77b7a9204ebe40c53425ce4bc82c1df456e911/pkg/cli/server/server.go#L77) will fix the problem.

**Comment by brandond** [comment]
> Set suid bit to the Systemd binaries: sudo chmod a+s /lib/systemd/systemd*.

Why would you do this? Is this something the Linux distro you are using does by default, or is this something you've done manually?

**Comment by brandond** [comment]
I am going to go out on a limb here and say that making all the systemd binaries setuid root is a huge privilege escalation risk and not something we're particularly interested in enabling.
