### ISSUE TITLE
Improvement to k3s/k8s data directories locations

### ISSUE THREAD

**Issue by safderali5** [k3s-io/k3s#9284]
The k3s provides a convenient way to specify the k3s data dir using option --data-dir. However the other kubernetes directories that can use a lot of disk are still using default paths e.g.,

Kubelet data dir /var/lib/kubelet. (There is option to specify this as kubelet parameter)
Pods logs dir /var/log/pods.  (No option to change this dir by any means)

The requested improvement is when a user specifies the k3s --data-dir options, all the directories which store significant amount of data shall be under that. This is useful on virtual machines like setups where the root dir is quite small and dedicated only for the linux host and a separate disk is mounted for k3s/k8s storage.

**Comment by galal-hussein** [comment]
I think /var/log/pods is hardcoded in upstream Kubernetes https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L74
as a workaround you may try to symlink or mount these directories separately before starting k3s, however adding this to k3s as an option will require changes in the kubernetes code to make this as an option

**Comment by brandond** [comment]
Both of these paths are standardized as part of Kubernetes itself. As @galal-hussein said, `/var/log/pods` is hardcoded in the kubelet and cannot be changed. `/var/lib/kubelet` is expected by many other projects and tools in the Kubernetes ecosystem; we used a custom path in early releases of K3s and it caused no end of problems. 

Given that, we are not planning on changing these or making them part of the data-dir. If you must store them somewhere else, a symlink is the best option.
