### ISSUE TITLE
K3s with CRI-O: `...can't initialize iptables table filter: Permission denied...` starting ServiceLB — `NET_ADMIN` is not enough, `NET_RAW` needed

### ISSUE THREAD

**Issue by prokher** [k3s-io/k3s#9285]
**Environmental Info:**
K3s Version: 
```
# k3s -v
k3s version v1.29.0+k3s1 (3190a5fa)
go version go1.21.5
```

Node(s) CPU architecture, OS, and Version: `Linux devenv 6.5.13-orbstack-00121-ge428743e4e98 #1 SMP Wed Dec 27 10:22:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: singe-node cluster.

**Describe the bug:**
ServiceLB does not start with error `...can't initialize iptables table filter: Permission denied...` when running K3s with CRI-O by providing `--container-runtime-endpoint /var/run/crio/crio.sock`.

**Steps To Reproduce:**
Set up K3s with CRI-O by manually installing CRI-O, CNI-plugins, and running K3s with `--container-runtime-endpoint /var/run/crio/crio.sock`.

**Fix considerations**
I found that providing `NET_RAW` to the SystemLB DeamonSet among with existing `NET_ADMIN` fixes the issue. Unfortunately I could not find how to configure K3s to do so. Looks like `NET_ADMIN` simply [hardcoded in the K3s source](https://github.com/k3s-io/k3s/blob/6d77b7a9204ebe40c53425ce4bc82c1df456e911/pkg/cloudprovider/servicelb.go#L553) and there is no way to tune ServiceLB deployment, i. e. DaemonSet. So the only way to workaround this for the moment is to `k3s kubectl -n kube-system edit svclb-traefik-...` and manually add `NET_RAW`.

**Comment by brandond** [comment]
Why does cri-o require different capabilities to create iptables rules than other runtimes? This works correctly with both containerd and cri-dockerd. Have you opened an issue with crio-o?

**Comment by prokher** [comment]
@brandond, no, I didn't. Honestly, I am not that expert in the area to properly understand whose issue it is.

**Comment by brandond** [comment]
You might open an issue at https://github.com/cri-o/cri-o/issues/ - although https://github.com/cri-o/cri-o/issues/7657 does mention some changes around CAP_NET_RAW?
