### ISSUE TITLE
DHCP's search domain gets added to FQDN on DNS lookups within K3S containers, making DNS requests fail

### ISSUE THREAD

**Issue by proligde** [k3s-io/k3s#9286]
**Environmental Info:**
K3s Version:  v1.28.4+k3s2

Node(s) CPU architecture, OS, and Version:  1 Node, 13th Gen Intel(R) Core(TM) i7-13700H, Ubuntu 22.04

Linux devbox 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node development machine

**Describe the bug:**
The router provides a search domain `fritz.box` via DHCP which should be perfectly fine. 

While the host system resolves correctly, all DNS resolves within k3s' containers fail, adding the search as a suffix even to FQDNs - even when explicitly requesting external DNS. Example:

```
# host www.spiegel.de 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

Host www.spiegel.de.fritz.box not found: 2(SERVFAIL)
```
So the problem is, that for some reason, search domains are added to FQDN's within K3S containers.

**Steps To Reproduce:**
That's the thing: I had several notebooks from my colleagues here that had that issue. There, the only way of fixing was to turn of DHCP completely, switching to static IP address configuration. However, others don't have this issue, although receiving the same search domain. I could not find a way of reliably reproducing the issue.

However, there is an interesting side effect: When I try to make an `apt get install <something>` in the container, I would expect it to fail completely. However, it just takes several seconds and then eventually starts downloading like some fallback DNS would resolve to the correct address after a while. Very strange - I know :-D

- Installed K3s: v1.28.4+k3s2

**Expected behavior:**
The correct domain gets resolved

**Actual behavior:**
The FQDN domain plus the search domain-as-suffix is being resolved, failing for obvious reasons

**Additional context / logs:**

Maybe connected to https://github.com/k3s-io/k3s/issues/2801 ?

**Comment by jano477** [comment]
I can confirm described behaviour of my k3s-clusters DNS since last night.

**Comment by galal-hussein** [comment]
This seems to be a networking issue because containers fail to resolve names with even external dns like 1.1.1.1, can you provide details/logs on the network availability of pods in the system:
- can pods reach internet?
- also can you provide the /etc/resolv.conf from within one of the pods?

**Comment by jano477** [comment]
> * can pods reach internet?
They can, if you don't need DNS:
```
zabbixproxy-58457dcdd5-9gwqf:/var/lib/zabbix$ ping 142.250.187.99
PING 142.250.187.99 (142.250.187.99) 56(84) bytes of data.
64 bytes from 142.250.187.99: icmp_seq=1 ttl=115 time=40.9 ms
64 bytes from 142.250.187.99: icmp_seq=2 ttl=115 time=39.2 ms
^C
--- 142.250.187.99 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 39.151/40.007/40.864/0.856 ms
```

> * also can you provide the /etc/resolv.conf from within one of the pods?

```
zabbixproxy-58457dcdd5-9gwqf:/var/lib/zabbix$ cat /etc/resolv.conf
search zabbix.svc.cluster.local svc.cluster.local cluster.local fritz.box
nameserver 10.43.0.10
options ndots:5
```

The search domain "fritz.box" is added to every DNS-request:
```
tmp-shell  ~  host google.de
Host google.de.fritz.box not found: 2(SERVFAIL)
```

**Comment by brandond** [comment]
Yes, this is how DNS works. `options ndots:5` says to use the search domain list for every lookup that does not have a terminal period, and has less than 5 periods in the name being resolved (5 dots). Unfortunately the DNS server for one of the domains in your search list is returning a failure response, instead of not found.

If you don't want the search domain from your host included in the resolv.conf generated by the kubelet, you can either remove it from resolv.conf on the host, or create a new resolv.conf specifically for use by k3s, and point at that file with the --resolv-conf option.

**Comment by jano477** [comment]
Yes, I see, but nothing changed in my DNS-Setup explaining this behaviour. It occured in the middle of the night when my monitoring agents on all k3s-nodes became unreachable via DNS.
Same happened last night where everything went back to normal without changing anything in my setup. I would assume a problem in my own DNS-infrastructure but everything also happened to @proligde .
So far there is no real explanation for me.

**Comment by brandond** [comment]
> Same happened last night where everything went back to normal without changing anything in my setup.

That would seem to confirm that there is an issue with the upstream DNS servers for your fritz.box domain, and not anything within your cluster?

**Comment by proligde** [comment]
@jano477 @brandond thank you so much for pointing out the difference in behavior depending on SERVFAIL vs. NXDOMAIN which I'll investigate further.

However, I still don't understand why this is no problem on the host but only within the container. The issue also occurs (within the container) when I use, for example, `curl https://www.google.com` where no terminal period is expected. It just can't resolve the domain there.

**Comment by brandond** [comment]
if you're on the host, you're probably using systemd-resolved as a cache in front of the upstream, instead of coredns?

**Comment by jano477** [comment]
My DNS-requests are directly forwarded to my local DNS-Server which is pihole (dnsmasq), no local cache on the k3s-node-host involved.
But yes, it's not coredns and the option `options ndots:5` is not set in `/etc/resolv.conf`.

I removed the fritz.box search domain from all k3s-hosts and it did the trick. However, I still don't get why this was coming and going out of nowhere.

**Comment by brandond** [comment]
Possibly related: 
* https://www.heise.de/news/Verwirrend-Internet-Domain-fritz-box-zeigt-NFT-Galerie-statt-Router-Verwaltung-9610149.html
* https://www.heise.de/news/Neue-Top-Level-Domain-box-bringt-manche-Netze-durcheinander-3491185.html

> Owners of a router from AVM should be amazed: Anyone who types the Internet address "fritz.box" into a browser will now see an unusual sight outside of their home network. Unknown people have registered the domain for themselves and are currently presenting an NFT advertising page there.

> The popular Fritzbox routers from the Berlin manufacturer AVM use the domain name fritz.box for their internal network by default. This means that the router itself and computers on the (W)LAN can be easily reached via the name (www.)fritz.box instead of the more complicated IP address such as 192.168.178.1. Recently, however, the long-announced [top-level domain .box](https://newgtlds.icann.org/en/program-status/delegated-strings) became active.

> This is now apparently leading to problems for some Fritzbox users: The public domain name system has long been responding to [requests for new, but not yet occupied TLDs with a reserved address](http://www.heise.de/ct/hotline/Seltsame-DNS-Antwort-127-0-53-53-3087461.html) , which indicates that you should change your internal name system. If you use the fritz.box domain occupied by the Fritzbox internally, the IP address of the router or the desired computer is sometimes no longer returned, but 127.0.53.53.

I would probably stop using fritz.box across the board unless you like having your lookups hijacked.

**Comment by utkuozdemir** [comment]
For anyone affected by the `fritz.box` disaster like me, if you use your fritzbox device's DHCP to provide the DNS and use a distro that uses `netplan` (Ubuntu for example), here's how you configure it to deny the search domains from the DHCP:
- Check that you are affected: `sudo resolvectl status | grep -C5 fritz.box`
- Check that you use netplan 0.98 or above: `sudo apt list --installed | grep netplan`
- Edit the files under `/etc/netplan/*.yaml`, for example `sudo nano /etc/netplan/00-config.yaml`:
- Find your link configurations, and set the `dhcp-overrides` on them key to have `use-domains: false`. My config looks like this:

  ```yaml
  network:
    version: 2
    ethernets:
      all-ethernets:
        match:
          name: "en*"
        dhcp4: true
        optional: true
        dhcp4-overrides:
          use-domains: false
  ```
- Apply the config: `sudo netplan try`, press ENTER if all is good
- Check to verify that the search domain is disappeared: `sudo resolvectl status | grep -C5 fritz.box`
