### ISSUE TITLE
ob for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details

### ISSUE THREAD

**Issue by mohamed200211** [k3s-io/k3s#9287]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Please fill out the issue template. The error you've put in the subject tells you specifically what to do to view the logs that may help you understand what has gone wrong. Have you done so?
