### ISSUE TITLE
W0128 messages (Cannot read vendor id correctly, set empty.) logged every 5 mins

### ISSUE THREAD

**Issue by ngrigoriev** [k3s-io/k3s#9310]
**Environmental Info:**

k3s version v1.28.5+k3s1 (5b2d1271)
go version go1.20.12

Node(s) CPU architecture, OS, and Version: 
Linux pineh64-xxxxx 6.1.63-current-sunxi64 #1 SMP Mon Nov 20 10:52:19 UTC 2023 aarch64 GNU/Linux
and 
Linux rpi4b-xxxxx 6.1.68-current-bcm2711 #1 SMP PREEMPT Sun Dec 17 11:40:38 UTC 2023 aarch64 GNU/Linux

$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
...
processor       : 2
...
processor       : 3
...
Revision        : d03115
Serial          : 10000000cfa6eb18
Model           : Raspberry Pi 4 Model B Rev 1.5

Cluster Configuration:
several agent nodes, one master, mix of Pine H64 Model B and Raspberry Pi 4B machines.

**Describe the bug:**
K3S process produces every 5 mintes the messages in the log:

k3s[<pid>]: W0128 <time>    <pid> machine.go:65] Cannot read vendor id correctly, set empty.
k3s[<pid>]: W0128 <time> <pid> sysinfo.go:203] Nodes topology is not available, providing CPU topology

**Steps To Reproduce:**
Install k3s on Raspberry Pi, I guess?

**Expected behavior:**
Log this once at startup and be done with that. CPU rarely changes on the fly ;) Or offer a flag to suppress them.

**Actual behavior:**
Messages are produced every 5 minutes

**Additional context / logs:**
I think it is simply because the vendor info is missing from /proc/cpuinfo?

**Comment by brandond** [comment]
Yep. This comes from the kubelet (cadvisor specifically I believe) trying to poll CPU topology and vendor ID. 

This is part of upstream Kubernetes and not something we can address here in k3s. If you wish to see it addressed, I would open an issue in the Kubernetes repo.
