### ISSUE TITLE
I use an external empty mysql database，Failed， FATA[0000] starting kubernetes: preparing server: creating storage endpoint: starting kine backend: Error 1267 (HY000): Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation 'like'

### ISSUE THREAD

**Issue by ckeyer** [k3s-io/k3s#9320]
**Environmental Info:**
K3s Version: 
k3s version v1.28.6-rc2+k3s1 (39a00015)
go version go1.20.13

and 

k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 

Linux VM-24-14-centos 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 Server

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

```
INFO[0000] Acquiring lock file /data/k3s/data/.lock
INFO[0000] Preparing data dir /data/k3s/data/46057a1eb55d262c2ef9480c0ed431b83123f777044ecff60bae0c2906493fb8
WARN[0000] remove /data/k3s/agent/etc/k3s-agent-load-balancer.json: no such file or directory
WARN[0000] remove /data/k3s/agent/etc/k3s-api-server-agent-load-balancer.json: no such file or directory
INFO[0000] Starting k3s v1.28.6-rc2+k3s1 (39a00015)
INFO[0000] Configuring mysql database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s
INFO[0000] Configuring database table schema and indexes, this may take a moment...
INFO[0000] Database tables and indexes are up to date
FATA[0000] starting kubernetes: preparing server: creating storage endpoint: starting kine backend: Error 1267 (HY000): Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation 'like'
```

**Comment by ckeyer** [comment]
I tried to change the default encoding of the database, but it didn't work.

**Comment by brandond** [comment]
What version of mysql are you using? The kine table uses the ascii character set, if for some reason your server's default character set is set to something else, you may need to change that - rather than trying to change the encoding of the database.

Ref: https://github.com/k3s-io/kine/blob/master/pkg/drivers/mysql/mysql.go#L31C24-L31C42

**Comment by ckeyer** [comment]
@brandond  My mysql version is MySQL8.0 20220831

**Comment by brandond** [comment]
That's not the fix I would recommend, but if it's working for you then great.
