### ISSUE TITLE
Bump helm-controller to v0.15.8

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9325]
Ref: 
* https://github.com/k3s-io/helm-controller/pull/222
* SURE-7467

**Comment by VestigeJ** [comment]
Verified via go.mod 
https://github.com/rancher/distros-test-framework/actions/runs/7759357736/attempts/1#summary-21163223445

**Comment by VestigeJ** [comment]
New change is observable within the description of the helm-install jobs under the mounts. Additionally verified via go.mods 

https://github.com/rancher/distros-test-framework/actions/runs/7761997024/attempts/1#summary-21171615241

Existing state in RCs truncated output --- observe no /tmp directory mount

```
 Mounts:
      /chart from content (rw)
      /config from values (rw)
      /home/klipper-helm/.cache from klipper-cache (rw)
      /home/klipper-helm/.config from klipper-config (rw)
      /home/klipper-helm/.helm from klipper-helm (rw)
```

Latest commit ID based installation truncated for output

```
 Mounts:
      /chart from content (rw)
      /config from values (rw)
      /home/klipper-helm/.cache from klipper-cache (rw)
      /home/klipper-helm/.config from klipper-config (rw)
      /home/klipper-helm/.helm from klipper-helm (rw)
      /tmp from tmp (rw)
```
