### ISSUE TITLE
providerID not present after upgrade to v0.10.0-rc2

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#935]
**Version:**
v0.9.1 to v0.10.0-rc2

**Describe the bug**
Cloud ProviderID was expected to be present after upgrade from v0.9.1 to v0.10.0-rc2 

**To Reproduce**
Install k3s with v0.9.1
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -s - server`

Upgrade to v0.10.0-rc2
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.10.0-rc2 sh -s - server --node-external-ip <external ip>`

Verify providerID is present
`kubectl describe node |grep -i providerID`

**Expected behavior**
ProviderID should be present

**Actual behavior**
ProviderID is not present

**Additional context**
Fresh install contains the providerID with v0.10.0-rc2

**Comment by jackzampolin** [comment]
Running into this too!

**Comment by cjellick** [comment]
what is providerID used for?

**Comment by MonzElmasry** [comment]
Validated on k3s v1.20.6+k3s1
ProviderID is present
```
kubectl describe node |grep -i providerID
ProviderID:                   k3s://ip-172-31-38-104
```
and upgraded to v1.21.0 via  `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.0+k3s1 sh -s - server --node-external-ip  <external ip>`
```
kubectl describe node |grep -i providerID
ProviderID:                   k3s://ip-172-31-38-104
```
ProviderID is still present.

**Comment by ShylajaDevadiga** [comment]
Validated providerID is present  on k3s v1.20.6+k3s1 fresh install
```
ubuntu@ip-172-31-40-17:~$ k3s -v
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10
ubuntu@ip-172-31-40-17:~$ kubectl describe node|grep -i provider
ProviderID:                   k3s://ip-172-31-40-17
ubuntu@ip-172-31-40-17:~$ 
```
and after upgrade to v1.21.0+k3s1
```
ubuntu@ip-172-31-40-17:~$ k3s -v
k3s version v1.21.0+k3s1 (2705431d)
go version go1.16.2
ubuntu@ip-172-31-40-17:~$ kubectl describe node|grep -i provider
ProviderID:                   k3s://ip-172-31-40-17
```
