### ISSUE TITLE
Integrate Envoy Gateway as the Default Gateway API Implementation for k3s

### ISSUE THREAD

**Issue by Xunzhuo** [k3s-io/k3s#9351]
## Integrate Envoy Gateway as the Default Gateway API Implementation for k3s

**Is your feature request related to a problem? Please describe.**
Currently, k3s does not offer a default implementation for the Kubernetes Gateway API, which provides a more expressive and extensible way to handle ingress traffic than the traditional Ingress API. Users who want to utilize the Gateway API within k3s need to manually integrate a compatible controller, which can be a complex and time-consuming process.

**Describe the solution you'd like**
I propose the integration of Envoy Gateway as the default Gateway API implementation for k3s. This would provide users with a modern, powerful, and expressive set of APIs to manage their ingress traffic, backed by the proven performance and flexibility of Envoy Proxy. Envoy Gateway is designed to be lightweight and easy to use, aligning well with the goals of k3s, and it has successfully passed all conformance tests for Gateway API v1.0.0.

The integration should include:
1. Packaging and configuring Envoy Gateway to work out of the box with k3s.
2. Ensuring that the installation and upgrade processes for Envoy Gateway are simple and well-documented.
3. Providing clear documentation and examples on how to leverage Envoy Gateway within k3s, emphasizing its benefits over traditional Ingress controllers.

**Additional context**

+ Project website: https://gateway.envoyproxy.io
+ Project repo: https://github.com/envoyproxy/gateway

Envoy Gateway is built on top of the robust and widely-adopted Envoy Proxy. It is designed to be lightweight, easy to deploy, and ready to use, making it an ideal choice for k3s users who need a more capable and flexible ingress solution than what the standard Ingress API can offer. By integrating Envoy Gateway as the default Gateway API implementation, k3s can better serve a diverse set of user needs and provide a solid platform for future growth and innovation.

**Comment by brandond** [comment]
We bundle Traefik and have not plans to change that. Traefik is working on gateway API support, and we will probably pick that up as our default Gateway API controller sometime soon.

**Comment by mtparet** [comment]
I am confident this decision will change before 2027. Given the currently community traction, envoy could become the default gateway in most Kubernetes stacks.

**Comment by kamikaze** [comment]
who needs bundled ingress at all? I'm disabling it and installing my own, even though it is still Traefik
