### ISSUE TITLE
 Failed to validate golang version

### ISSUE THREAD

**Issue by liangcan1995** [k3s-io/k3s#9352]
FATA[0000] Failed to validate golang version: kubernetes golang build version not set - see 'golang: upstream version' in https://github.com/kubernetes/kubernetes/blob/dev/build/dependencies.yaml

I followed the instructions in the document
1. Pulling code
2. Can run k3s after making
3. "go build - o k3s" can also be successfully built
4. "./k3s server" encountered this exception, my go version is 1.21.6

![image](https://github.com/k3s-io/k3s/assets/157568678/e8e355b8-cb0c-4101-92db-a0e1a2bf5c10)

**Comment by brandond** [comment]
That is not how you build k3s. `make ci` is probably the easiest way to build properly.

**Comment by littesss** [comment]
root@ubuntu:/home/lsh/k3s/k3s-shallow# make ci
while ! docker version 1>/dev/null; do sleep 1; done
./.dapper ci
[+] Building 40.9s (2/2) FINISHED                                                                                         docker:default
 => [internal] load build definition from Dockerfile.dapper781677796                                                                0.1s
 => => transferring dockerfile: 2.40kB                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/golang:1.25.5-alpine3.22                                                  40.5s
------
 > [internal] load metadata for docker.io/library/golang:1.25.5-alpine3.22:
------
Dockerfile.dapper781677796:2
--------------------
   1 |     ARG GOLANG=golang:1.25.5-alpine3.22
   2 | >>> FROM ${GOLANG}
   3 |     
   4 |     # Install necessary packages
--------------------
ERROR: failed to build: failed to solve: golang:1.25.5-alpine3.22: failed to resolve source metadata for docker.io/library/golang:1.25.5-alpine3.22: failed to do request: Head "https://docker.mirrors.ustc.edu.cn/v2/library/golang/manifests/1.25.5-alpine3.22?ns=docker.io": dial tcp: lookup docker.mirrors.ustc.edu.cn on 127.0.0.53:53: read udp 127.0.0.1:42121->127.0.0.53:53: i/o timeout
FATA[0044] exit status 1                                
make: *** [Makefile:18: ci] Error 1

**Comment by brandond** [comment]
You are unable to pull the golang image from your mirror, apparently due to a DNS failure. This is a network issue on your end that we cannot assist with.
