### ISSUE TITLE
Add option to disable colors in `check-config` output.

### ISSUE THREAD

**Issue by rishinair11** [k3s-io/k3s#9355]
**Is your feature request related to a problem? Please describe.**
When using `k3s check-config`, the output has colors in it. Sometimes, for use cases where we have to fetch this info along with other information, package it into a tar file, and send it to a stakeholder, we pipe this output into a text file and the text file shows the ANSI characters for color coding, which decreases the legibility of the text file.

**Describe the solution you'd like**
An environment variable called `RAW_OUTPUT=1` or `NOCOLORS=1` for the [`check-config`](https://github.com/k3s-io/k3s/blob/master/contrib/util/check-config.sh#L83-L104) subcommand, which would not wrap the text in ANSI color characters.

**Describe alternatives you've considered**
We've considered using Regex to remove the color codes, but we are worried it may remove wanted text lines altogether.

_**I have created a [PR](https://github.com/k3s-io/k3s/pull/9357) for this, please let me know if it makes sense. Thanks in advance :)**_

**Comment by endawkins** [comment]
Add option to disable colors in check-config output. #9355


 
### Validated on branch master with commit bba3e3c / version 1.29
 
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-21-141 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
N/A
```
 
*Additional files*

```
N/A
```
 
## Testing Steps

1. Install k3s:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.29.2+k3s1 sh -
$ curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=bba3e3c66b22bbf112dc316a9b5dbd27f68f4ba8 sh -
```
2. Run the following command:
```
$ NO_COLOR=1 k3s check-config
```
 
**Replication Results:**
- k3s version used for replication:

```
$ k3s -v
k3s version v1.29.2+k3s1 (86f10213)
go version go1.21.7
```
 

![v1 29-validation(1)](https://github.com/k3s-io/k3s/assets/126098099/55a90b39-fcb0-4956-b791-95a2109be1eb)

 
![v1 29-validation(2)](https://github.com/k3s-io/k3s/assets/126098099/83a68137-ae4c-4072-ad38-12ac6c177da4)

 
**Validation Results:**
- k3s version used for validation:

```
k3s -v
k3s version v1.29.2+k3s-bba3e3c6 (bba3e3c6)
go version go1.21.7
```
 


![v1 29-validation(3)](https://github.com/k3s-io/k3s/assets/126098099/ac6235cc-2943-4011-8760-e92fecd64af4)


![v1 29-validation(4)](https://github.com/k3s-io/k3s/assets/126098099/cb2b3a96-c862-49f7-bd36-ef97ff86f05b)

 
**Additional context / logs:**
```
N/A
```
