### ISSUE TITLE
Authoritative Documentation for Multus and Flannel Integration in K3s

### ISSUE THREAD

**Issue by auphof** [k3s-io/k3s#9356]
I'm relatively new to K3s and have encountered challenges while trying to integrate Multus with Flannel, it just works in [microk8s enable  multus](https://microk8s.io/docs/addon-multus). 
For K3s this was not easy,  After an exhaustive search through articles, Gists, and other resources—which often seemed outdated—I found a helpful response on [RancherSlack](https://rancher-users.slack.com/archives/CGGQEHPPW/p1699534625062209?thread_ts=1699449593.873059&cid=CGGQEHPPW) that led me to a solution. This experience highlighted a gap in the current K3s documentation regarding the integration of Multus. Ideally It should be as simple as in `microk8s` or some clear documentation

**Describe the solution you'd like**
https://docs.k3s.io/installation/network-options#custom-cni documents other CNI implementations, I would like to see this expanded on how to integrate multus with flannel, or as simple addon implementation as in `microk8s`

**Describe alternatives you've considered**

1. I note that this has come up before #2163 (Now Closed) in response to the 2020 decision,  current docs do show Canal, Callico, Cillum support.

2. There is a ticket https://github.com/k3s-io/docs/issues/194 to better organize content for network config, any created docs for `Flannel with Multus`  would migrate to any proposed enhanced layout.

3. @brandond mentioned in https://rancher-users.slack.com/archives/CGGQEHPPW/p1707194893561179?thread_ts=1707193339.500079&cid=CGGQEHPPW that a flannel maintainer has a simplified solution `deploy multus with the integrated flannel. It can be done without disabling it and installing flannel separately` this would be 🚀

**Additional context**
for the moment i propose adding to [Custom CNI ](https://docs.k3s.io/installation/network-options#custom-cni) inline with this mockup.
![image](https://github.com/k3s-io/k3s/assets/44126722/840c2304-ccf4-40ae-99ed-3e7530bb98b0)
 I a willing to raise a PR in https://github.com/k3s-io/docs to capture this current working method

**Comment by brandond** [comment]
cc @manuelbuil
