### ISSUE TITLE
k3s binary has a wrong context when dropped in /opt/bin/k3s

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#9360]
**Environmental Info:**
K3s Version: 
*

Node(s) CPU architecture, OS, and Version: 
any

Cluster Configuration:
1 server

**Describe the bug:**
Currently k3s binary is being installed in /usr/local/bin/k3s, however if the install script detects that /usr/local/bin is read-only, then k3s binary will be dropped to /opt/bin/k3s instead, this currently doesn't have the right context in selinux.

**Steps To Reproduce:**
- Start any EL or sle server
- `mkdir /opt/bin /testro`
- `mount --bind -o ro /testro /usrl/local/bin`
- run the curl script

You would notice that k3s binary has been dropped in /opt/bin/k3s, but with the wrong selinux context

**Expected behavior:**
for k3s binary to have the right selinux context  `container_runtime_exec_t`

**Actual behavior:**
k3s binary has usr_t context

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
### Validated on k3s version v1.29.1-rc2+k3s2 using channel testing for k3s binary to have the right selinux context container_runtime_exec_t
```
# /opt/bin/k3s -v
k3s version v1.29.1-rc2+k3s2 (57482a1c)
go version go1.21.6

# ls -lZ /opt/bin/k3s
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0 66387968 Feb  6 21:26 /opt/bin/k3s
```
Reproduced issue on k3s version v1.29.1-rc2+k3s2 using channel stable 
```
# /opt/bin/k3s -v
k3s version v1.29.1-rc2+k3s2 (57482a1c)
go version go1.21.6

# ls -lZ /opt/bin/k3s
-rwxr-xr-x. 1 root root unconfined_u:object_r:user_tmp_t:s0 66387968 Feb  6 21:17 /opt/bin/k3s
```
