### ISSUE TITLE
Add support for custom CA.

### ISSUE THREAD

**Issue by rwthompsonii** [k3s-io/k3s#9366]
**Is your feature request related to a problem? Please describe.**

I have a system where I want to build repeatable images with k3s, and give them to downstream developers.  

I want to use certificates signed by a full CA chain that is entirely within my control, to sign into these k3s api servers for auth purposes.

I do not want to check in to source control my entire chain of certs, including the keys.  For either the root or the intermediate.  I do not want private keys involved, or any other secrets.

I just want the ability to specify a trusted CA by the api server, without interfering with k3s's creation of the cert chains that it uses for interoperability internally.

When I give the arg `--k8s-apiserver-arg client-ca-file=/my/root/ca`, it totally ignores the argument and spawns the api server with one in "/etc/rancher/something".  I think that should at least result in a failure to start, not silently drop my argument on the floor.  That would have saved me some debugging, at least.

**Describe the solution you'd like**

I want a flag called "trustThisCA" that will import a root PEM file and trust that root, in addition to any roots that k3s may create.  I do not want to _replace_ k3s root files, I want it to use _both_ when passing them on to the apiserver that k3s is spawning -- I want the convenience of not having to run custom_CA_generate.sh _and_ I want to be able to specify _additional_ root PEMs to trust certs signed by it.

**Describe alternatives you've considered**

N/A
**Additional context**

Most of the input to building a k3s server for me has to be submitted to version control, so putting anything with a secret into it, sucks.  Public keys are great, secrets, not so much.  Being able to say "trust this" without providing a secret is a win, for me.

**Comment by brandond** [comment]
> I do not want to check in to source control my entire chain of certs, including the keys. For either the root or the intermediate. I do not want private keys involved, or any other secrets.

This is not possible. K3s generates a number of certificates for use by internal components. If you want to K3s to sign its internal certs, and validate client certificates, using an existing CA, you MUST provide an intermediate CA certificate that K3s can sign additional certificates with. There is no way around this.

Check the docs at https://docs.k3s.io/cli/certificate#custom-ca-topology for more information on supported CA topologies.
