### ISSUE TITLE
Bump kine and align kine/etcd NotifyInterval with upstream

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9385]
* There have been several fixes to kine around support for watch progress notifications and list pagination, as well as version bumps for go-sqlite3. We should bump the kine version to latest.
   https://github.com/k3s-io/kine/compare/v0.11.0...v0.11.4
* Once kine supports watch progress notifications, we should align the kine/etcd notification interval with what the apiserver expects:
    https://github.com/kubernetes/kubernetes/issues/122805#issuecomment-1898386268

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  k3s version v1.29.1+k3s-de825845 (de825845)


```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
NAME="Oracle Linux Server"
VERSION="8.9"
ID="ol"
ID_LIKE="fedora"


*Cluster Configuration:*
1 node servers 



## Steps to validate the fix
1. Install k3s  
2. Validate  watch progress is enabled and set for 5s
3. Validate nodes and pods are all ok 
 
 

## **Validation Results:**
<details> 


```
 
 k3s -v
k3s version v1.29.1+k3s-de825845 (de825845)
go version go1.21.6


$ sudo cat /var/lib/rancher/k3s/server/db/etcd/config | grep progress
experimental-watch-progress-notify-interval: 5000000000

~$ kgn
NAME               STATUS   ROLES                       AGE     VERSION
ip    Ready    control-plane,etcd,master   5m50s   v1.29.1+k3s-de825845


~$ kgp -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-6799fbcd5-77jlg                   1/1     Running     0          5m49s
kube-system   helm-install-traefik-crd-959nr            0/1     Completed   0          5m49s
kube-system   helm-install-traefik-lj2dc                0/1     Completed   1          5m49s
kube-system   local-path-provisioner-6c86858495-nj455   1/1     Running     0          5m49s
kube-system   metrics-server-67c658944b-tjjdx           1/1     Running     0          5m49s
kube-system   svclb-traefik-a6e5c723-r67pp              2/2     Running     0          5m33s
kube-system   traefik-f4564c4f4-qvg5j                   1/1     Running     0          5m33s


```
