### ISSUE TITLE
codecov/codecov-action@v4 requires a `CODECOV_TOKEN` to work

### ISSUE THREAD

**Issue by aofei** [k3s-io/k3s#9393]
I just noticed #9353 was merged. However, it doesn't address a breaking change introduced by codecov/codecov-action@v4, which is that tokenless uploads are no longer supported (see [release notes](https://github.com/codecov/codecov-action/releases/tag/v4.0.0)).

Steps to fix:

1. Obtain the upload token (`CODECOV_TOKEN`) from https://codecov.io/github/k3s-io/k3s/settings
2. Add `CODECOV_TOKEN` as a repository secret at https://github.com/k3s-io/k3s/settings/secrets/actions
3. Modify workflow configurations. For example `.github/workflows
/unitcoverage.yaml`:

```diff
    - name: Upload Results To Codecov
      uses: codecov/codecov-action@v4
      with:
+       token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        flags: unittests # optional
        verbose: true # optional (default = false)
```

/cc @dereknola who merged #9353.

**Comment by dereknola** [comment]
Our main concern is seeing codcoverage reports on PRs. Per the notes

> However, PRs made from forks to the upstream public repos will support tokenless

So our Push codecov is currently broken, but PRs won't fail

**Comment by caroline-suse-rancher** [comment]
Thank you for bring this up @aofei !

**Comment by dereknola** [comment]
Nothing to QA here, this is an internal CI fix.
