### ISSUE TITLE
v0.10.0 agent cannot connect to v0.9.1 server

### ISSUE THREAD

**Issue by Leen15** [k3s-io/k3s#943]
Hi, I have a cluster with version 0.9.1 for both server and agents.
I just tried today to add a new agent and it used the last 0.10.0 version.

I used this command:
`curl -sfL https://get.k3s.io | K3S_URL=https://192.168.255.1:6443 K3S_TOKEN=XXXX INSTALL_K3S_EXEC="--docker" sh -`

In the log I see this:
```
time="2019-10-23T14:01:14.654887179+02:00" level=info msg="Starting k3s agent v0.10.0 (f9888ca3)"
time="2019-10-23T14:01:14.656547423+02:00" level=info msg="Running load balancer 127.0.0.1:33375 -> [192.168.255.1:6443]"
time="2019-10-23T14:01:17.779480317+02:00" level=fatal msg="Cannot configure unknown flannel backend ''"
```
both server and agents run inside an OpenVPN.
For now I installed the version 0.9.1 on this agent and it works, but I think there is something wrong with the new version.

Thanks

**Comment by erikwilson** [comment]
Thanks for the info @Leen15! When using a v0.10.0 agent it should be connecting to a v0.10.0 server, the issue is with connecting to an older v0.9.1 server. There should probably be some version checking and a better message to enforce this.

**Comment by Leen15** [comment]
Ok, does the opposite work?
I mean, I should update first the server to v.0.10.0 and then every single agent, right?
In the meantime of the upgrade, will agents with v.0.9.1 works with a connection to server with v.0.10.0?

**Comment by erikwilson** [comment]
That is correct, server first then agents, previous version agents will connect to the new server.
