### ISSUE TITLE
Pods stay in Terminating state forever after server crash

### ISSUE THREAD

**Issue by sli720** [k3s-io/k3s#9433]
**Environmental Info:**
K3s Version: 
k3s version v1.29.1+k3s2 (57482a1c)
go version go1.21.6

(also tried latest v1.28.5)

Node(s) CPU architecture, OS, and Version: 
Linux node02 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 servers, 2 agents

**Describe the bug:**
I've simulated the case that a server crashes and the pods started on other nodes after some time but the old ones are staying in Terminating state forever. They only disappear when the crashed host is back online. I've tested it multiple times.

e.g.

`kube-system       metrics-server-67c658944b-bfq2z                     1/1     Terminating   0            8h    10.42.0.5    node01   <none>           <none>`

`kube-system       coredns-6799fbcd5-559s7                             1/1     Terminating   0            8h    10.42.0.4    node01   <none>           <none>`

In some cases it is not a problem but in cases were the pod can only mount the PVC once, the new pod never comes up:

e.g.

`gitea             gitea-7f8bbdd5b7-fmfhh                              1/1     Terminating   0            8h    10.42.0.14   node01   <none>           <none>`

`gitea             gitea-7f8bbdd5b7-kqq7p                              0/1     Init:0/3      0            8h    <none>       node03   <none>           <none>`

**Steps To Reproduce:**
- Installed K3s:  via k3s-ansible latest playbook + installed longhorn through the helm chart v1.5.3 (also tried with v1.6.0) + shutdown of one agent node

**Expected behavior:**
The pods should be destroyed after some time or there should be a setting to configure the time when they are just force deleted, otherwise pods with PVC read/write-once can not start up again.  The setting _terminationGracePeriodSeconds: 60_ does not have any effect on this afaics.

**Actual behavior:**
Pods stay in Terminating state forever after a server crashes.

**Comment by brandond** [comment]
That's correct. Kubernetes cannot reason about nodes that are not online. If the node is not online to provide a list of currently running pods, it cannot confirm if they are running, or stopping, or deleted. The node could be online with running pods, but simply partitioned or otherwise disconnected from the apiserver. It just doesn't know.

If you want them gone, you should force-delete the pods, or delete the node that the pods are running on.
