### ISSUE TITLE
Install script iptables check fails when sbin isn't in user PATH

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9438]
*from @NordMike*

Function has_working_xtables() checks presence of iptables under a regular user and then tries to use it under the root. But there are systems where some tools are excluded from regular user environment. So presence of iptables should be checked under the root user.

**Comment by brandond** [comment]
install script changes do not need backports.

**Comment by aganesh-suse** [comment]
Verified with the latest install.sh from https://get.k3s.io/install.sh(with sbin not in user PATH) that has_working_xtables() checks for presence of iptables using sudo in the command: 

```
+ for XTABLES in iptables ip6tables
+ has_working_xtables iptables
+ sudo sh -c 'command -v "iptables-save"'
+ info 'Host iptables-save/iptables-restore tools not found'
+ echo '[INFO] ' 'Host iptables-save/iptables-restore tools not found'
[INFO]  Host iptables-save/iptables-restore tools not found
+ return 1
+ for XTABLES in iptables ip6tables
+ has_working_xtables ip6tables
+ sudo sh -c 'command -v "ip6tables-save"'
+ info 'Host ip6tables-save/ip6tables-restore tools not found'
+ echo '[INFO] ' 'Host ip6tables-save/ip6tables-restore tools not found'
[INFO]  Host ip6tables-save/ip6tables-restore tools not found
+ return 1
```
