### ISSUE TITLE
"NodePasswordValidationFailed" Event is created on server restart when agent is disabled

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9447]
*From @matskiv*

When the agent is disabled, e.g. when k3s image is used in a [vcluster](https://github.com/loft-sh/vcluster), a "NodePasswordValidationFailed" Event is created on every restart. This results in users questioning the state of their cluster, even though there is no impact on functionality.

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit 1c1746114c94498f8b77e0ba13c43ebe6e0da56a
 
## Environment Details

 
*Infrastructure*
- [x] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
 
*Cluster Configuration:*

```
HA: 3 server/ 1 agent
```
 
*Config.yaml:*

```
token: xxxx
cluster-init: true
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
node-label:
- k3s-upgrade=server
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
```
curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT='1c1746114c94498f8b77e0ba13c43ebe6e0da56a' sh -s - server
```
3. Edit the /etc/rancher/k3s/config.yaml file of server nodes to have extra line: 
```
disable-agent: true
```
Restart the k3s service: `sudo systemctl restart k3s`
4. Search for 'NodePasswordValidationFailed' event from journal logs of all server nodes
```
journalctl -xeu k3s | grep 'Password'
```
 
 
**Replication Results:**
- k3s version used for replication:

```
$ k3s -v
k3s version v1.29.1+k3s2 (57482a1c)
go version go1.21.6
```
 

```
 $ journalctl -xeu k3s | grep 'Password' 
Feb 17 03:50:17 ip-172-31-30-244 k3s[78168]: time="2024-02-17T03:50:17Z" level=info msg="Password verified locally for node ip-172-31-30-244"
Feb 17 03:50:27 ip-172-31-30-244 k3s[78168]: I0217 03:50:27.457822   78168 event.go:376] "Event occurred" object="ip-172-31-30-244" fieldPath="" kind="Node" apiVersion="" type="Normal" reason="NodePasswordValidationComplete" message="Deferred node password secret validation complete"
```
 
 
**Validation Results:**
- k3s version used for validation:

```
$ k3s -v
k3s version v1.29.2-rc1+k3s1 (1c174611)
go version go1.21.7
```
 

```
 $ journalctl -xeu k3s | grep 'Password' 
```
