### ISSUE TITLE
Difficult to `nsenter` rootless k3s to interact with namespaced sockets and filesystems

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9449]
*from @hinshun*

Currently, the ~/.rancher/k3s/rootless directory is created but is unused. The directory is passed to the createParentOpts but the variable is then overrided by a call to os.MkdirTemp. This makes it harder to nsenter via rootlesskit's child_pid or hit the rootlesskit's API socket.

For example, see the complicated command pipeline necessary at https://github.com/k3s-io/k3s/issues/8512#issuecomment-1741850382

**Comment by mdrahman-suse** [comment]
# Validated on RC v1.29.2-rc2+k3s1

## Testing steps:
#### Followed the steps to install k3s-rootless as mentioned here: https://github.com/k3s-io/k3s/issues/3636#issuecomment-1631586671

## Replication result:
```
$ k3s -v
k3s version v1.29.1+k3s2 (57482a1c)
go version go1.21.6

$ ls -la /home/ubuntu/.rancher/k3s/rootless/
total 8
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 21:51 .
drwxr-xr-x 10 ubuntu ubuntu 4096 Feb 20 21:51 ..
```

## Validation result:
```
$ k3s -v
k3s version v1.29.2-rc1+k3s1 (1c174611)
go version go1.21.7

$ ls -la /home/ubuntu/.rancher/k3s/rootless/
total 12
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 22:11 .
drwxr-xr-x 10 ubuntu ubuntu 4096 Feb 20 22:11 ..
prw-------  1 ubuntu ubuntu    0 Feb 20 22:11 .bp-ready.pipe
srwxrwxr-x  1 ubuntu ubuntu    0 Feb 20 22:11 .bp.sock
srwxrwxr-x  1 ubuntu ubuntu    0 Feb 20 22:11 api.sock
-r--r--r--  1 ubuntu ubuntu    4 Feb 20 22:11 child_pid
-rw-------  1 ubuntu ubuntu    0 Feb 20 22:11 lock
```
