### ISSUE TITLE
K3S_DEBUG and --debug do not enable containerd debugging

### ISSUE THREAD

**Issue by roffery** [k3s-io/k3s#9474]
**Environmental Info:**
k3s version v1.28.6+k3s2 (c9f49a3b)
go version go1.20.13

Node(s) CPU architecture, OS, and Version: 
Linux kube-01 5.14.0-362.18.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 3 15:54:45 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 2 agents

**Describe the bug:**
Running k3s with --debug or K3S_DEBUG doesn't enable debugging on containerd

I do get debug-level logging from K3s itself.

**Steps To Reproduce:**
- Installed K3s
- Run k3s with K3S_DEBUG=true or --debug=true

**Expected behavior:**
containerd provides debug logging

**Actual behavior:**
containerd does not provide debug logging

**Additional context / logs:**

**Comment by brandond** [comment]
That is correct. --debug only enables debugging in k3s itself. If you want to enable containerd debugging, you can export `CONTAINERD_LOG_LEVEL=debug`. If you want to enable Kubernetes debug logging, you can set `--v=9` or whatever log level you want.
