### ISSUE TITLE
k3s Pod unable to access internet.

### ISSUE THREAD

**Issue by abhishek-hvt** [k3s-io/k3s#9476]
**Environmental Info:**
K3s Version:  
v1.28.4+k3s2 (6ba6c1b6)

Node(s) CPU architecture, OS, and Version: 
Linux app-instance 5.15.0-1047-oracle #53-Ubuntu SMP Wed Oct 18 09:56:06 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
Single server cluster

**Describe the bug:**
One of our backend service hosted in one of the pod on k3s cluster needs to fetch some backend code data from Gitlab repo, but pod is unable to access Gitlab.
After troubleshooting we found our pod is unable to connect to internet whereas our k3s hosting server is able to connect to internet.

**Steps To Reproduce:**
- Installed K3s:    
 curl -sfL https://get.k3s.io/ | INSTALL_K3S_EXEC="--tls-san=129.159.23.163" sh -s - --docker

we are using dockerd as container runtime as by default it is giving containerd by default so we are using --docker 

**Expected behavior:**
 Expected that our pods can access to the internet and gitlab. 

**Actual behavior:**
Actually our pods is not able to access to the internet and when curl google.com it is not giving us any response.

**Additional context / logs:**
When we exec into pod it is giving following error.

root@configuration-deployment-6494598cd6-9xg8m:/# curl google.com
curl: (6) Could not resolve host: google.com

**Comment by brandond** [comment]
> ```
> root@configuration-deployment-6494598cd6-9xg8m:/# curl google.com
> curl: (6) Could not resolve host: google.com
> ```

This would indicate that the pod cannot reach the coredns service. Is your pod not able to reach the **internet**, or not able to reach its DNS server?

How many nodes do you have in this cluster? Can you confirm that CNI traffic (flannel vxlan, by default) is not being dropped? Have you tested other pod-to-pod or pod-to-service traffic between nodes, and confirmed that it is working properly?

**Comment by abhishek-hvt** [comment]
Hi @brandond , This is a single node cluster. Can you please let me know how can I check that CNI traffic (flannel vxlan, by default) is not being dropped?
And also how can I check that pod-to-pod or pod-to-service traffic between nodes is working properly or not ?

**Comment by brandond** [comment]
If it's a single-node cluster then there would be no traffic between nodes.

Is the coredns pod working? Do you have firewalld or ufw enabled and blocking traffic?

**Comment by abhishek-hvt** [comment]
Hi @brandond thankyou for your quick response, Our Coredns pod is running and ufw is inactive, we are using firewalld and it is in active state and we have allowed port 80/tcp 443/tcp 6443/tcp 53/udp. 
Here is the output from server for all your questions for your reference.

ubuntu@app-instance:~$ kubectl get pods -n kube-system
NAME                                      READY   STATUS      RESTARTS     AGE
helm-install-traefik-crd-2kn55            0/1     Completed   0            62d
helm-install-traefik-dsd6k                0/1     Completed   1            62d
local-path-provisioner-84db5d44d9-m8bq6   1/1     Running     3 (9d ago)   62d
svclb-traefik-64565659-ddnbn              2/2     Running     6 (9d ago)   62d
metrics-server-67c658944b-wqmwr           0/1     Running     3 (9d ago)   62d
coredns-554795b5f9-jt5xr                  1/1     Running     2 (9d ago)   17d
traefik-f4564c4f4-c46h2                   1/1     Running     4 (9d ago)   62d
ubuntu@app-instance:~$ sudo ufw status
Status: inactive
ubuntu@app-instance:~$ sudo firewall-cmd --list-all
You're performing an operation over default zone ('public'),
but your connections/interfaces are in zone 'docker' (see --get-active-zones)
You most likely need to use --zone=docker option.

public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: dhcpv6-client ssh
  ports: 80/tcp 443/tcp 6443/tcp 53/udp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

**Comment by brandond** [comment]
> we are using firewalld and it is in active state and we have allowed port 80/tcp 443/tcp 6443/tcp 53/udp.

We don't technically support use with firewalld. My first suggestion would be to disable and stop it. If you want to **try** keeping it enabled, see https://docs.k3s.io/installation/requirements#operating-systems

**Comment by abhishek-hvt** [comment]
Hi @brandond , we are using firewalld in one of the project in k3s cluster and everything is working fine there. In our k3s cluster our server is giving response is we are using command ( ping google.com ) but our problem is our pod is not giving response when we are using ( ping google.com ).
Can you please provide any reference as you said when we are using docker zone in play we may need to make additional adjustments to the config, beyond what is suggested in the docs. This will be helpful for us.
