### ISSUE TITLE
Update klipper-lb image

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#9487]
**Is your feature request related to a problem? Please describe.**

We want the newer version of klipper-lb image which uses alpine 3.19

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VestigeJ** [comment]
Reproduced using VERSION=v1.29.2+k3s1
Validated using COMMIT=091a5c89653d5ba2ae0e49fa7e2c9f9eb0a328c6

ATTENTION KLIPPER LB v0.4.6 was marked as broken and that is why there is a version skipped during upgrade.

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"

*Cluster Configuration:*

NAME              STATUS   ROLES                       AGE     VERSION
ip-1-1-2-37       Ready    control-plane,etcd,master   9m37s   v1.29.2+k3s-091a5c89

*Config.yaml:*

```
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
profile: cis
protect-kernel-defaults: true
cluster-init: true
```

<details><summmary><h4>Installation Steps</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ VERSION=v1.29.2+k3s1
$ sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh
$ set_kubefig
$ sudo /usr/local/bin/k3s crictl image ps
$ COMMIT=091a5c89653d5ba2ae0e49fa7e2c9f9eb0a328c6
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh
$ sudo systemctl restart k3s
$ sudo /usr/local/bin/k3s crictl image ps
```

**Results:**

Current Release version

$ sudo /usr/local/bin/k3s crictl image ps

```
IMAGE                                        TAG                    IMAGE ID            SIZE
docker.io/rancher/klipper-lb                 v0.4.5                 17066c233afa3       7.82MB
```

New commit-id build version 

$ sudo /usr/local/bin/k3s crictl image ps //note old image hasn't been pruned yet 

```
IMAGE                                        TAG                    IMAGE ID            SIZE
docker.io/rancher/klipper-lb                 v0.4.5                 17066c233afa3       7.82MB
docker.io/rancher/klipper-lb                 v0.4.7                 edc812b8e25d0       4.78MB
```

**Comment by VestigeJ** [comment]
Note other branches are waiting to be merged
