### ISSUE TITLE
[Documentation] Brief section to explain at high level some differences between k3s and k8s

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#950]
Some people have asked for brief info on the differences between k3s and k8s. Not just what we took out of k8s to make k3s lightweight, but any differences in how you may interact with k3s on a daily basis as compared to k8s.

There are few differences but we would like to at a high level explain anything of relevance.

**Comment by dereknola** [comment]
This is fairly well covered in the [landing page](https://docs.k3s.io/) and [Architecture](https://docs.k3s.io/architecture) sections of the docs.
