### ISSUE TITLE
Manifests with the same filename are added to the same Addon

### ISSUE THREAD

**Issue by rafaelgaspar** [k3s-io/k3s#9500]
**Environmental Info:**
K3s Version: `k3s version v1.29.1+k3s2 (57482a1c)`

Node(s) CPU architecture, OS, and Version: `Linux f6a339e937f5 6.6.12-linuxkit #1 SMP Fri Jan 19 08:53:17 UTC 2024 aarch64 GNU/Linux`

Cluster Configuration: Reproducible with just a single server, and no agents.

**Describe the bug:**

If have a nested folder structure for the manifests, and there is two files with the same name, it creates just a single Addon with that filename, since it uses `basename` [here](https://github.com/k3s-io/k3s/blob/de825845b2f1eca82c19892c327ed274abfa8901/pkg/deploy/controller.go#L173).

**Steps To Reproduce:**

- Installed K3s server, no agents are needs, but off-course also happens with agents.
- Inside `/var/lib/rancher/k3s/server/manifests`
  - Create a folder `a` with a single file named `configmap.yaml` that contains a ConfigMap on the namespace `a`.
  - Create a folder `z` with a single file named `configmap.yaml` that contains a ConfigMap on the namespace `z`.

**Expected behavior:**

That both namespace `a` and `z` have their respective ConfigMap applied.

**Actual behavior:**

Only namespace `z` have a ConfigMap. Although for a few ms namespace `z` loses it's ConfigMap and `a` have it, until it re-apply `z` and remove `a`.

**Additional context / logs:**

This was bit tricky to understand, since I was not familiar with the internals of k3s, logs would only say the the resource was successfully applied even though I couldn't find the resource.

After digging a bit more, I that the resources had an Addon custom resource attached to it, and it all made sense.

Looking at the code also confirmed the issue.

**Comment by dereknola** [comment]
The manifest system is designed around individual files, not nested folders. You are welcome to open a PR to expand this functionality.

**Comment by brandond** [comment]
I am going to close this out, as it is covered in the docs
https://docs.k3s.io/installation/packaged-components#file-naming-requirements
> The AddOn name for each file in the manifest directory is derived from the file basename. Ensure that all files within the manifests directory (or within any subdirectories) have names that are unique, and adhere to Kubernetes [object naming restrictions](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/). Care should also be taken not to conflict with names in use by the default K3s packaged components, even if those components are disabled.
