### ISSUE TITLE
IPsec unable to connect master

### ISSUE THREAD

**Issue by johansmitsnl** [k3s-io/k3s#951]
**Version:** k3s version v0.10.0 (f9888ca3)

**Describe the bug**
I have a node that is behind a NAT and I use the new ipsec rancher/k3s#50 feature. The communication works perfectly between the master and workers inside the kubernetes environment. On the master I run a docker private registry and I noticed when the images needs to be pulled it does not succeed. I noticed when the ipsec tunnel is working no communication to the master public ip works. Not even websites that are working from my laptop I can open them from the worker that run on the master.

**To Reproduce**
1. Setup a master with `$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend ipsec" sh -`
2. Setup a worker `$curl -sfL https://get.k3s.io | K3S_URL=https://master:6443 K3S_TOKEN=xxx::node:xxx sh -`
3. on the node open a website that is running on the master: `$ curl -v https://somesite`
  `* Expire in 7 ms for 1 (transfer 0x560d3a466dc0)`

**Expected behavior**
To be able to communicate outside kubernetes to the master public services

**Actual behavior**
Indefinite timeouts

Set is like:
```
Server (Public IP, no NAT)
      |
      |
Router (Public IP, firewall 500 and 4500 udp to server below and behind NAT)
      |
Server behind nat (internal ip)
```

**Comment by johansmitsnl** [comment]
The issue went away, will reopen if it occurs again.

**Comment by johansmitsnl** [comment]
I have this issue again. Please let me know how I can assist in debugging

**Comment by matti** [comment]
https://twitter.com/ibuildthecloud/status/1225793624324988928?s=21
