### ISSUE TITLE
helm-install-traefik stuck in CrashLoopBackoff

### ISSUE THREAD

**Issue by GregSutcliffe** [k3s-io/k3s#9534]
**Environmental Info:**
K3s Version: 
```
k3s version v1.28.6+k3s2 (c9f49a3b)
go version go1.20.13
```

Node(s) CPU architecture, OS, and Version: 
```
Linux knode-rock64 6.1.50-current-rockchip64 #3 SMP PREEMPT Wed Aug 30 14:11:13 UTC 2023 aarch64 GNU/Linux
```

Cluster Configuration:
3 arm64 hosts (one Rock64, one Rpi, one Odroid c2), the Rock64 is the master

**Describe the bug:**
This isn't going to be the best bug report... :/

I'm fairly new to k3s and kubernetes. When I set up the cluster a few months ago (v1.27) I had issues with traefik, and I *think* I tried a few things. In the end, I gave up, and used ClusterIP services, and accessed the containers on `knode-rock64.mydomain:8080` and so on.

Fast forward to a few weeks ago, and I decide to have another go. Clearly, something has improved! I can set up names in Traefik now, and even have Lets Encrypt working to give myself https applications out of the box. Lovely.

However, I can see that when I run `kubectl get pods -o wide -A` one of the traefik pods is stuck:
```
kube-system       helm-install-traefik-rp98j                0/1     CrashLoopBackOff    808 (22s ago)     2d20h   10.42.0.194   knode-rock64     <none>           <none>
kube-system       helm-install-traefik-crd-ht29k            0/1     Terminating         0                 2s      <none>        knode-odroidc2   <none>           <none>
kube-system       helm-install-traefik-crd-f49dz            0/1     ContainerCreating   0                 2s      <none>        knode-odroidc2   <none>           <none>
```

800 restarts is clearly not healthy - but as my https URLs are working, I'm not sure how to proceed. The pod logs for that pod are below

**Steps To Reproduce:**

- Installed K3s: 
I installed k3s a while ago, but I *think* I just used the quick-start with no particular flags (i.e `curl -sfL https://get.k3s.io | sh -`). Happy to dig into more if needed.

I don't expect this to be reproducible, I'm 100% sure I've done something daft - I'm just not sure how to debug (or just cleanup and reinstall Traefik). I suspect I have got some custom drop-ins (there are files in `/var/lib/rancher/k3s/server/manifests/`), but (as I say) it was a while ago and now I'm not sure which ones are defaults and while are not.

**Expected behavior:**
A Traefik resource that doesn't keep restarting.

**Actual behavior:**
CrashLoopBackoff errors in my helm-install-traefik pod

**Additional context / logs:**
`kubectl -n kube-system logs -f helm-install-traefik-rp98j`
```
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
        echo "KUBERNETES_SERVICE_HOST is using IPv6"
        CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
        CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
+ tiller --listen=127.0.0.1:44134 --storage=secret
[main] 2024/02/20 22:46:13 Starting Tiller v2.17.0 (tls=false)
[main] 2024/02/20 22:46:13 GRPC listening on 127.0.0.1:44134
[main] 2024/02/20 22:46:13 Probes listening on :44135
[main] 2024/02/20 22:46:13 Storage driver is Secret
[main] 2024/02/20 22:46:13 Max history per release is 0
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ timeout -s KILL 30 helm_v2 ls --all '^traefik$' --output json
++ jq -r '.Releases | length'
[storage] 2024/02/20 22:46:14 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ shopt -s nullglob
+ [[ -f /config/ca-file.pem ]]
chart path is a url, skipping repo update
+ [[ -f /tmp/ca-file.pem ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=v2.10.5,uninstalling
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ v2.10.5 =~ ^(|null)$ ]]
+ [[ uninstalling =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ uninstalling == \d\e\p\l\o\y\e\d ]]
+ [[ uninstalling =~ ^(deleted|failed|null|unknown)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-25.0.2+up25.0.0.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
```

Any help greatly appreciated - also, I'm loving k3s, so thanks for your work!

**Comment by brandond** [comment]
Why are the CRD install pods stuck terminating/creating?

You might try just starting k3s with `--disable=traefik`, wait for everything to get uninstalled, and then remove that option and restart k3s again.

**Comment by GregSutcliffe** [comment]
Thanks for the quick reply!

> Why are the CRD install pods stuck terminating/creating?

That's what I'm stuck on. The error says it can't re-use a name, but I can't see *which* resource it's trying to duplicate.

> You might try just starting k3s with --disable=traefik, wait for everything to get uninstalled, and then remove that option and restart k3s again.

Sadly, that hasn't helped. I stoped the systemd service, started it locally with `/usr/local/bin/k3s server --disable=traefik` and then watched the output of `kubectl get pods -A`. I could see the problem `helm-install-traefik*` pods were removed, but I notcied the `svclb-traefik*` ones remained. Once it had all settled down, I stopped the foreground server and restarted the systemd service. As expected, the helm pods came back, but they're still failing the same way (`Error: INSTALLATION FAILED: cannot re-use a name that is still in use`).

Any other suggestions? To be honest, I need to move the server process to another host anyway - so I could just start over (I was hoping to avoid having to recreate the containers and migrate their data though). But it would be nice to know what happened!

**Comment by brandond** [comment]
Well, the current state of the chart is `uninstalling`:
> ` LINE=v2.10.5,uninstalling`

So I suspect that it was in the midst of uninstalling and reinstalling the chart for some reason, when the pod running the helm command was killed for some reason. Now it's stuck in that state. Easiest fix on this host is probably to grab the helm CLI tool and use it to force uninstall the chart, and then wait for the job to kick off and finish installing it.

**Comment by GregSutcliffe** [comment]
Thanks! Just running `helm list` didn't get me any results, so (after some searching) I ran:
```
kubectl -n kube-system delete helmcharts.helm.cattle.io traefik
kubectl -n kube-system delete helmcharts.helm.cattle.io traefik-crd
```

I hope that's the right way to go, let me know if there's a better way. Then I confirmed the deletion pods had ran & then restarted k3s via systemctl, and watched the output of `get pods -A`. The CRD chart ran, but the main Traefik one is still errorring out:
```
kube-system       helm-delete-traefik-nx27x                 0/1     Completed          0               6m45s   10.42.1.87    knode-rpi1       <none>           <none>
kube-system       helm-delete-traefik-crd-scf64             0/1     Completed          0               6m22s   10.42.2.155   knode-odroidc2   <none>           <none>
kube-system       traefik-55cf4857d9-6x66h                  1/1     Running            4 (10h ago)     3d10h   10.42.0.141   knode-rock64     <none>           <none>
kube-system       helm-install-traefik-crd-bl99r            0/1     Completed          0               4m4s    10.42.2.156   knode-odroidc2   <none>           <none>
kube-system       helm-install-traefik-mmmzx                0/1     CrashLoopBackOff   5 (55s ago)     4m4s    10.42.2.157   knode-odroidc2   <none>           <none>
```
Looking at the logs for the new helm-install-traefik pod, it's *still* throwing the same error:
```
+ LINE=v2.10.5,uninstalling
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ v2.10.5 =~ ^(|null)$ ]]
+ [[ uninstalling =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ uninstalling == \d\e\p\l\o\y\e\d ]]
+ [[ uninstalling =~ ^(deleted|failed|null|unknown)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-25.0.2+up25.0.0.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
```

So either I did that wrong (apologies if so) or something else is going on. Is there a way to tell *which* name it is complaining about?

**Comment by brandond** [comment]
that's just deleting the HelmChart CRD that is used by the embedded helm controller. You need to go get the actual helm CLI tool from https://github.com/helm/helm/releases and use it to uninstall the chart.

**Comment by GregSutcliffe** [comment]
Ah ok. Now I have broken it :)

So, I have Helm downloaded, and took a look at the output of `list`:
```
root@knode-rock64:~/helm/linux-arm64# ./helm version
version.BuildInfo{Version:"v3.14.1", GitCommit:"e8858f8696b144ee7c533bd9d49a353ee6c4b98d", GitTreeState:"clean", GoVersion:"go1.21.7"}

root@knode-rock64:~/helm/linux-arm64# ./helm list
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

root@knode-rock64:~/helm/linux-arm64# ./helm list -n kube-system
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
traefik-crd     kube-system     1               2024-02-21 20:26:43.948515144 +0000 UTC deployed        traefik-crd-25.0.2+up25.0.0     v2.10.5    
```

I was surprised not to see `traefik` there at first, but I guess that's the point. I wasn't 100% sure of the right invocation for removal, so I took a stab at this:
```
root@knode-rock64:~/helm/linux-arm64# ./helm uninstall -n kube-system traefik
release "traefik" uninstalled
root@knode-rock64:~/helm/linux-arm64# ./helm uninstall -n kube-system traefik-crd
release "traefik-crd" uninstalled
```

The pod is still crashing, but now the error is
```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-25.0.2+up25.0.0.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Error: INSTALLATION FAILED: execution error at (traefik/templates/validate-install-crd.yaml:29:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.
```

Which I guess makes sense because I did also remove the CRD chart. I thought a restart of k3s might bring back both items, but that hasn't helped. Presumably I need to reinstall the traefik-crd chart - but I'm not sure of the URL to the CRD chart. I had a look in the complete `helm-install-traefik-crd` pod, which had these logs:
```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install traefik-crd https://10.43.0.1:443/static/charts/traefik-crd-25.0.2+up25.0.0.tgz
```
So I tried this:
```
root@knode-rock64:~/helm/linux-arm64# ./helm install traefik-crd https://10.43.0.1:443/static/charts/traefik-crd-25.0.2+up25.0.0.tgz 
Error: INSTALLATION FAILED: Get "https://10.43.0.1:443/static/charts/traefik-crd-25.0.2+up25.0.0.tgz": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Assuming I'm right in thinking I need to restore the CRD chart, what's the right way to do that? (And thanks for your patience!)

**Comment by GregSutcliffe** [comment]
Ah, of course, 10.43.0.1 is the cluster master. So, I used `find / ...` to discover it, and then `./helm install traefik-crd /var/lib/rancher/k3s/server/static/charts/traefik-crd-25.0.2+up25.0.0.tgz` to restore it. The helm-install-traefik pod completed successfully after that, and all seems to be working.

Thanks for your help!

**Comment by brandond** [comment]
If you'd let it sit for a bit, it should have retried both the traefik-crd and traefik installs, but it sounds like you're set either way!

**Comment by GregSutcliffe** [comment]
Thanks! As you can tell, I'm still at the start of my k8s journey, so for my own learning... how long is "a bit"? I gave it about an hour, after which I could see the main job failing as described, but no sign of the CRD being re-done. Running one and not the other seemed odd, hence why I starting looking for how to intervene.

**Comment by brandond** [comment]
If you hadn't restarted since deleting the HelmChart custom resources, it might have needed another restart to get those recreated. If the HelmChart custom resources exist, it should retry with a backoff until they eventually get installed.

**Comment by GregSutcliffe** [comment]
Hmm, I thought I had restarted at least once since then, but it's hard to be sure - there's been a lot of tinkering :)

Thanks for the info!
