### ISSUE TITLE
Validate Aurora MySQL 3.x

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#9538]
**Is your feature request related to a problem? Please describe.**
Add AWS Aurora MySQL 3.x for the k3s support matrix

**Describe the solution you'd like**
We need to validate K3s against newer versions of Aurora  MySQL database:
- Version 3.x

We should validate this in versions v1.27 and above

**Comment by caroline-suse-rancher** [comment]
Internal Jira Ref: SURE-7682

**Comment by VestigeJ** [comment]
This validation is stalled pending this bug fix - https://github.com/k3s-io/k3s/issues/10023

**Comment by VestigeJ** [comment]
Confirming good conformance checks from Sonobuoy against all recent RCs using MySQL 8.4 - (mysqld 8.4.0)  MySQL Community Server

Will be re-testing this soon to validate.

**Comment by VestigeJ** [comment]
Closing this as the only tests that failed with this database were resolved in the linked bugs
