### ISSUE TITLE
K3s flannel doesn't work with netscript service in ubuntu

### ISSUE THREAD

**Issue by orangedeng** [k3s-io/k3s#9558]
**Environmental Info:**
K3s Version: v1.21.7+k3s1/v1.28.2+k3s1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 22.04 LTS, amd64

Cluster Configuration:
1 server

**Describe the bug:**
If the `netscript` is installed and enabled in ubuntu, the pods in k3s won't start normally.
The cause of the pods failed is the flannel bridge cni0 got deleted by `netscript` time to time. And it cause the overlay network doesn't work appropriately.

**Steps To Reproduce:**
- `apt install netscript-2.4`
- `systemctl enable netscript && systemctl start netscript` and `reboot`
- Install K3s

**Expected behavior:**
I am not sure k3s should be compatible with netscript or not. If it shouldn't, it might need to be documented.

**Actual behavior:**
- K3s runs well but he pod in the k3s keep failing.
- `ip a show cni0` returns nothing

**Additional context / logs:**
After disable and remove netscript, k3s and the pods of it work fine.

**Comment by brandond** [comment]
I'm not familiar with the netscript service, is it something you installed, or something that recent releases of ubuntu come with by default?

> the flannel bridge cni0 got deleted by netscript time to time. 

Yes, that would be a problem. Why would you install something that randomly deletes interfaces its not familiar with?

**Comment by orangedeng** [comment]
> I'm not familiar with the netscript service, is it something you installed, or something that recent releases of ubuntu come with by default?

Seems like it's a network tools in linux to manage network interfaces but not come with ubuntu LTS by default.
In my case, the operation team installed it to have `ifup` `ifdown` `ifquery` tools to fix the network setting problems of the host. After the configuration fixed, the tools are not longer needed. 

I just want to write this down in case someone encounter the same problem in the future.

**Comment by brandond** [comment]
Was there a specific service that was started that was associated with the interface removal? Or was it just happening whenever someone ran `ifdown` on the node?
