### ISSUE TITLE
k3s v1.29.1 ignores disable-kube-proxy setting from config file

### ISSUE THREAD

**Issue by ston1th** [k3s-io/k3s#9561]
**Environmental Info:**
K3s Version: 
```
k3s version v1.29.1+k3s2 (57482a1c)
go version go1.21.6
```

**Describe the bug:**
Hi K3s team,
it seems that k3s ignores the `disable-kube-proxy: true` setting in the config file. I use the following command:
```
k3s server -c /etc/rancher/k3s/server.yaml
```

Using the commandline flag `--disable-kube-proxy` it works and kube-proxy is not started.

**Comment by brandond** [comment]
Seems to work fine for me. Are you sure you've put that setting in the correct file? Is there other malformed content in that same file that is preventing it from being parsed properly?

```console
systemd-node-1:/ # tail -n 4 /etc/systemd/system/k3s.service
    server \
	'-c' \
	'/etc/rancher/k3s/server.yaml' \

systemd-node-1:/ # tail -n 5 /etc/systemd/system/k3s.service
ExecStart=/usr/local/bin/k3s \
    server \
	'-c' \
	'/etc/rancher/k3s/server.yaml' \

systemd-node-1:/ # cat /etc/rancher/k3s/server.yaml
disable-kube-proxy: true

systemd-node-1:/ # kubectl get node -o yaml | grep node-args
      k3s.io/node-args: '["server","--disable-kube-proxy","true","-c","/etc/rancher/k3s/server.yaml"]'
      
systemd-node-1:/ # journalctl -u k3s | grep -c "Running kube-proxy"
0
```

**Comment by brandond** [comment]
Do you also have the flag specified in the systemd unit, or in another config file somewhere? The fact that you have it as a trailing arg suggests that it's in the systemd unit. Try removing it from there.
