### ISSUE TITLE
Kine TLS support for k3s

### ISSUE THREAD

**Issue by vitorsavian** [k3s-io/k3s#9563]
**Is your feature request related to a problem? Please describe.**

- During the development of support for kine within rke2, we encountered the need for kine to support TLS within k3s.

**Describe the solution you'd like**

- Wire the already generate etcd certs to the kine tls config and set the client to use tls in the `TLSConfig`.

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
Don't add new CLI flags for this. We already generate server certs for etcd, I would recommend just reusing those for kine.

**Comment by vitorsavian** [comment]
@brandond I didn't saw the certs, but you mean wiring up the `ServerETCDCert` `ServerCA` and the `ServerETCDKey` that are in the `runtime` right?
