### ISSUE TITLE
what you mean exactly when you say if data you stored in the Secret resource was inaccessible via the API ?

### ISSUE THREAD

**Issue by VivekSheshadari** [k3s-io/k3s#9564]
what you mean exactly when you say if data you stored in the Secret resource was inaccessible via the API ? 
I have referred the same link and tested the behaviours after encryption is enabled. it is accessible via API and when I call `"kubectl get secret secret1 -n default -o yaml"` i could able to see the secret still in base64 and not encrypted.
Also, If you think there is any other alternate way to achieve this, provide the solution here.

_Originally posted by @VivekSheshadari in https://github.com/k3s-io/k3s/issues/9559#issuecomment-1962253891_

**Comment by brandond** [comment]
Let's keep the conversation on the other issue, which I will convert to a discussion.
