### ISSUE TITLE
Configuration in config.yaml.d is not read if there is no config.yaml

### ISSUE THREAD

**Issue by votdev** [k3s-io/k3s#9567]
**Environmental Info:**
K3s Version: v1.28.6+k3s2

Node(s) CPU architecture, OS, and Version: AMD64, Debian 12

Cluster Configuration: Single-node setup

**Describe the bug:**

To customize the configuration according to the [docs](https://docs.k3s.io/installation/configuration#multiple-config-files) i created a file called `/etc/rancher/k3s/config.yaml.d/95myconfig.yaml` with the content
```
write-kubeconfig-mode: "0644"
cluster-init: true
kube-controller-manager-arg:
  # Removing leader election can reduce CPU usage on a single-node setup.
  - "leader-elect=false"
  - "node-monitor-period=60s"
```
Note, there is NO `/etc/rancher/k3s/config.yaml` file.

After the installation via `wget -O - https://get.k3s.io | sh -` i was wondering why the permissions of the `/etc/rancher/k3s/k3s.yaml` was still `0600`.

The correct file permission was set when i moved the config file from `config.yaml.d/95myconfig.yaml` to `config.yaml`.

**Steps To Reproduce:**

- Installed K3s: See bug description

**Expected behavior:**

The config files from `config.yaml.d/*` are still applied if there is no `config.yaml` file.

**Actual behavior:**

The extra configs from `config.yaml.d/*` are not applied if there is a `config.yaml` file.

**Additional context / logs:**

n/a

**Comment by brandond** [comment]
I can't reproduce this. Are you sure you didn't create the file in config.yaml.d after installing and starting k3s?

```console
/ # ls -la /etc/rancher/k3s/config.yaml /etc/rancher/k3s/config.yaml.d/*
ls: cannot access '/etc/rancher/k3s/config.yaml': No such file or directory
-rw-rw-r-- 1 1001 1001 49 Feb 27 00:12 /etc/rancher/k3s/config.yaml.d/95myconfig.yaml

/ # cat /etc/rancher/k3s/config.yaml /etc/rancher/k3s/config.yaml.d/*
cat: /etc/rancher/k3s/config.yaml: No such file or directory
write-kubeconfig-mode: "0644"
cluster-init: true

/ # kubectl get node -o yaml | grep node-args
      k3s.io/node-args: '["server","--write-kubeconfig-mode","0644","--cluster-init","true"]'
```
