### ISSUE TITLE
K3S Agent not starting when joining Ipv4 only node to a dual stack cluster

### ISSUE THREAD

**Issue by JOUNAIDSoufiane** [k3s-io/k3s#9583]
**Environmental Info:**
K3s Version: 
v1.27.9+k3s1 on the node
v1.27.3+k3s1 on the control plane

Node(s) CPU architecture, OS, and Version: 
Node with no ipv6 address attached to its network interface, only ipv4

Cluster Configuration:
3 identical servers spawned using AWS EC2
1 existing joined node that supports both ip4 and ip6
1 new node that only supports ip4

**Describe the bug:**
K3S Agent will not start and the node join gets rejected by the cluster 

**Steps To Reproduce:**

- Installed K3s: 
```
(
    export INSTALL_K3S_VERSION="v1.27.3+k3s1"
    export K3S_KUBECONFIG_MODE="644"
    export K3S_CLUSTER_INIT="true" #to enable embedded etcd

    ./get_k3s.sh \
	    --node-external-ip="${public_ip},${public_ip6}" \
	    --node-ip="${local_ip},${public_ip6}" \
	    --node-name="${provider_id}" \
	    --tls-san="xxxxxxx" \
	    --flannel-external-ip \
	    --flannel-backend=wireguard-native \
            --flannel-ipv6-masq \
	    --egress-selector-mode=pod \
            --cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 \
            --service-cidr=10.43.0.0/16,2001:cafe:43::/112
)
```
- Attempt to join a node with only ip4 attached to its network interface.

**Expected behavior:**
Not sure, I expected the node to join the cluster with only ip4 capability. Does dual stack support a mix of both ip4 only and ip6 only nodes ?

**Actual behavior:**
```
+ k3s agent --node-name=3ab03aa2bfeaae843a1102e62abdd5b5
[k3s] INFO[0000] Starting k3s agent v1.27.9+k3s1 (2c249a39)   
[k3s] INFO[0000] Adding server to load balancer k3s-agent-load-balancer: server-ip:6443 
[k3s] INFO[0000] Running load balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [server-ip:6443] [default: server-ip:6443] 
[k3s] INFO[0000] Node authorization rejected, retrying without client certificate authentication 
[k3s] INFO[0001] Node authorization rejected, retrying without client certificate authentication 
[k3s] FATA[0001] cluster-cidr: [10.42.0.0/16 2001:cafe:42::/56] and node-ip: [192.168.8.223], must share the same IP version (IPv4, IPv6 or dual-stack) 
```

**Comment by brandond** [comment]
> Does dual stack support a mix of both ip4 only and ip6 only nodes ?

No. All cluster nodes must share the same address family (IPv4, IPv6, IPv4+IPv6).
