### ISSUE TITLE
Can not download the k3s on unbuntu 20.0

### ISSUE THREAD

**Issue by xuhjbj** [k3s-io/k3s#9585]
**Environmental Info:**
K3s Version: all the versions

curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.28.6+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.28.6+k3s2/sha256sum-amd64.txt
[ERROR]  Download failed
Node(s) CPU architecture, OS, and Version: 

root@synsfbd1:~# uname -a
Linux synsfbd1.fyre.ibm.com 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

**Describe the bug:**
1. try to use below command to install k3s:
 curl -sfLv https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik" INSTALL_K3S_VERSION="v1.27.9+k3s1" sh -s - --docker

but there are some error:
[INFO]  Using v1.27.9+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.9+k3s1/sha256sum-amd64.txt
[ERROR]  Download failed

**Steps To Reproduce:**

- Installed K3s: can not installed the k3s

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Something is preventing you from downloading files from github. What do you get if you run `curl -vsL https://github.com/k3s-io/k3s/releases/download/v1.27.9+k3s1/sha256sum-amd64.txt`?
