### ISSUE TITLE
Expose more datastore configuration options

### ISSUE THREAD

**Issue by mortenlj** [k3s-io/k3s#9596]
**Is your feature request related to a problem? Please describe.**

During startup of the k3s server, it some times wants to do lots of database maintenance. If your datastore (Postgres in my case), isn't the biggest of servers, you can run out of available connections, which k3s handles badly, crashing startup. Next startup, same thing happens.

**Describe the solution you'd like**

kine allows configuring both maxIdleConns and maxOpenConns, and it would be useful if those could be adjustable when using k3s, to tune how k3s uses the datastore.

**Describe alternatives you've considered**

None have come to mind, I'm still trying to get my cluster back on its feet.

**Additional context**

My database is running on a 1 CPU, 1GB ram server, and for the most time this works fine. Two days ago, the server node was down for reasons unknown, and when I rebooted it, k3s entered a crashloop where it starts, attempts to do lots of database operations. Eventually the database runs out of connections and rejects new connection attempts, causing k3s to fail. After logging lots of more things for a while, k3s panics in hooks.go with the message:

> PostStartHook "start-service-ip-repair-controllers" failed: unable to perform initial IP and Port allocation check

Rinse, repeat.

**Comment by brandond** [comment]
We evaluated exposing these options, and found that enabling users to tune these actually made things worse in almost all cases, see https://github.com/k3s-io/k3s/issues/1459#issuecomment-1167703296
