### ISSUE TITLE
Incorrect memory usage reported by `kubectl top nodes`

### ISSUE THREAD

**Issue by cs96and** [k3s-io/k3s#9597]
**Environmental Info:**
K3s Version:
```
v1.28.6+k3s2 (c9f49a3b)
go version go1.20.13
```

Node(s) CPU architecture, OS, and Version:
```
CentOS 7.9.2009
Linux [hostname] 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:
1 server, 3 other agents

**Describe the bug:**
The memory usage reported my `kubectl top nodes` does not match the values reported by `top`, `htop` or `free`

**Steps To Reproduce:**
- Run `kubectl top nodes`
- Run `free -m` on the server and nodes
- Compare the values

**Expected behavior:**
- The memory usage reported by `kubectl top nodes` should match (or be very close to) that reported by `free`.

**Actual behavior:**
- The memory usage reported by `kubectl top nodes` is much higher than that reported by `free`.

**Additional context / logs:**
```
jenkins@sw-jenkins1-cam:~> kubectl top nodes
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
server   148m         0%     127220Mi        49%
node1    161m         0%     42768Mi         48%
node2    157m         0%     47582Mi         50%
node3    188m         0%     51611Mi         54%
```
#### Server:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:         257444       32841       12737         114      211865      223625
Swap:        127999         468      127531
```
#### Node1:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          88048       16857       10844          90       60347       70583
Swap:        127999         534      127465
```
#### Node2:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95104       18228         319          98       76557       76233
Swap:        127999         205      127794
```
#### Node3:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95104       18178        6948          98       69977       76283
Swap:        127999          82      127917
```

**Comment by brandond** [comment]
the metrics shown by `kubectl top` come from metrics-server pod. If you have questions about how these figures are calculated compared to other system monitoring tools, you can ask at https://github.com/kubernetes-sigs/metrics-server
