### ISSUE TITLE
Failed to start Lightweight Kubernetes.

### ISSUE THREAD

**Issue by poscergx** [k3s-io/k3s#9598]
I hope to build a k3s master-slave cluster, but there was an error while running the agent. Could you please help me check the logs for any issues?

K3S version:
k3s version v1.28.6+k3s2 (c9f49a3b)
go version go1.20.13

k3s-master install shell:
curl –sfL \
     https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | \
     INSTALL_K3S_MIRROR=cn sh -s - \
     --system-default-registry "registry.cn-hangzhou.aliyuncs.com"

k3s-node install shell:
 curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL=https://172.16.60.224 K3S_TOKEN=K1026b6b4ee5de5c6f03364ea13423cd542ed6b627209491b9fd1f8f98af8bcdd69::server:35e34120787afdfdd31c185ac9f891f5 sh -s - --system-default-registry "registry.cn-hangzhou.aliyuncs.com"

systemctl log:
2月 29 21:02:03 k8s-worker1 systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit k3s-agent.service has begun starting up.
2月 29 21:02:04 k8s-worker1 sh[10280]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
2月 29 21:02:04 k8s-worker1 sh[10280]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
2月 29 21:02:04 k8s-worker1 k3s[10289]: Incorrect Usage: flag provided but not defined: -system-default-registry
2月 29 21:02:04 k8s-worker1 k3s[10289]: NAME:
2月 29 21:02:04 k8s-worker1 k3s[10289]: k3s agent - Run node agent
2月 29 21:02:04 k8s-worker1 k3s[10289]: USAGE:
2月 29 21:02:04 k8s-worker1 k3s[10289]: k3s agent [OPTIONS]
2月 29 21:02:04 k8s-worker1 k3s[10289]: OPTIONS:
2月 29 21:02:04 k8s-worker1 k3s[10289]: --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
2月 29 21:02:04 k8s-worker1 k3s[10289]: -v value                                   (logging) Number for the log level verbosity (default: 0)
2月 29 21:02:04 k8s-worker1 k3s[10289]: --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
2月 29 21:02:04 k8s-worker1 k3s[10289]: --log value, -l value                      (logging) Log to file
2月 29 21:02:04 k8s-worker1 k3s[10289]: --alsologtostderr                          (logging) Log to standard error as well as file (if set)
2月 29 21:02:04 k8s-worker1 k3s[10289]: --token value, -t value                    (cluster) Token to use for authentication [$K3S_TOKEN]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --token-file value                         (cluster) Token file to use for authentication [$K3S_TOKEN_FILE]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --server value, -s value                   (cluster) Server to connect to [$K3S_URL]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --data-dir value, -d value                 (agent/data) Folder to hold state (default: "/var/lib/rancher/k3s")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --with-node-id                             (agent/node) Append id to node name
2月 29 21:02:04 k8s-worker1 k3s[10289]: --node-label value                         (agent/node) Registering and starting kubelet with set of labels
2月 29 21:02:04 k8s-worker1 k3s[10289]: --node-taint value                         (agent/node) Registering kubelet with set of taints
2月 29 21:02:04 k8s-worker1 k3s[10289]: --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
2月 29 21:02:04 k8s-worker1 systemd[1]: k3s-agent.service: main process exited, code=exited, status=1/FAILURE
2月 29 21:02:04 k8s-worker1 k3s[10289]: --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_
2月 29 21:02:04 k8s-worker1 k3s[10289]: --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
2月 29 21:02:04 k8s-worker1 k3s[10289]: --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
2月 29 21:02:04 k8s-worker1 k3s[10289]: --default-runtime value                    (agent/runtime) Set the default runtime in containerd
2月 29 21:02:04 k8s-worker1 k3s[10289]: --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
2月 29 21:02:04 k8s-worker1 k3s[10289]: --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
2月 29 21:02:04 k8s-worker1 k3s[10289]: --disable-default-registry-endpoint        (agent/containerd) Disables containerd's fallback default registry endpoint when a mirror is configured for that registry
2月 29 21:02:04 k8s-worker1 k3s[10289]: --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
2月 29 21:02:04 k8s-worker1 k3s[10289]: --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
2月 29 21:02:04 k8s-worker1 k3s[10289]: --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --flannel-iface value                      (agent/networking) Override default flannel interface
2月 29 21:02:04 k8s-worker1 systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit k3s-agent.service has failed.
-- 
-- The result is failed.
2月 29 21:02:04 k8s-worker1 k3s[10289]: --flannel-conf value                       (agent/networking) Override default flannel config file
2月 29 21:02:04 k8s-worker1 k3s[10289]: --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
2月 29 21:02:04 k8s-worker1 k3s[10289]: --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
2月 29 21:02:04 k8s-worker1 k3s[10289]: --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
2月 29 21:02:04 k8s-worker1 k3s[10289]: --rootless                                 (experimental) Run rootless
2月 29 21:02:04 k8s-worker1 k3s[10289]: --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
2月 29 21:02:04 k8s-worker1 k3s[10289]: --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
2月 29 21:02:04 k8s-worker1 k3s[10289]: --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
2月 29 21:02:04 k8s-worker1 k3s[10289]: --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN
2月 29 21:02:04 k8s-worker1 k3s[10289]: --disable-apiserver-lb                     (agent/networking) (experimental) Disable the agent's client-side load-balancer and connect directly to the configured server address
2月 29 21:02:04 k8s-worker1 k3s[10289]: time="2024-02-29T21:02:04+08:00" level=fatal msg="flag provided but not defined: -system-default-registry"
2月 29 21:02:04 k8s-worker1 systemd[1]: Unit k3s-agent.service entered failed state.
2月 29 21:02:04 k8s-worker1 systemd[1]: k3s-agent.service failed.

**Comment by brandond** [comment]
The error is right at the top of your log:

> `2月 29 21:02:04 k8s-worker1 k3s[10289]: Incorrect Usage: flag provided but not defined: -system-default-registry`

This flag is only for use on servers, you should not use it when installing agents.
