### ISSUE TITLE
Drop flannel/cni-plugin from our fork of containernetworking/plugins

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9636]
The flannel CNI plugin binary itself has been moved out of `containernetworking/plugins` to a separate project at `flannel/cni-plugin`; it is no longer part of the main plugins project. We have kept a copy of it in our fork of the plugins project, alongside other changes to support building a single multicall binary. Unfortunately, this makes it difficult to identify what version of the flannel CNI plugin code is actually being used, as the files checked into git cannot be easily traced back to a specific commit or release from `flannel-io/cni-plugin`.

We should stop copying code from `flannel-io/cni-plugin` into our fork of `containernetworking/plugins`, and instead just check out specific releases of the plugin and build them into our multicall binary. This will allow us to properly expose the plugin version, as well as ensuring that we are using the correct plugin binary for whatever version of flannel we embed.

I suspect that we haven't been very on top of bumping the flannel cni-plugin code, as users are still reporting issues that have long been resolved, for example:
* https://github.com/k3s-io/k3s/issues/6185#issuecomment-1972952955

**Comment by mdrahman-suse** [comment]
## Validated on master with commit 364dfd8b

```
$ k3s -v
k3s version v1.29.2+k3s-364dfd8b (364dfd8b)
go version go1.21.7

$ /var/lib/rancher/k3s/data/current/bin/cni
CNI plugins plugin v1.4.0-k3s2
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0

$ /var/lib/rancher/k3s/data/current/bin/flannel
CNI Plugin flannel version v1.4.0-flannel1+v0.24.2 (linux/amd64) commit HEAD built on 2024-03-08T18:55:12Z
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
```
