### ISSUE TITLE
Executables from k3s get flagged as malware by Antvirus F-Secure and on virustotal.com

### ISSUE THREAD

**Issue by benklett** [k3s-io/k3s#9738]
**Environmental Info:**
K3s Version:
```
$ k3s -v
k3s version v1.29.2+k3s1 (86f10213)
go version go1.21.7
```
affected are the channels from v1.23 until v1.29

Node(s) CPU architecture, OS, and Version: 
```
$ uname -a
Linux ben-Virtual-Machine 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
single node cluster
```

**Describe the bug:**
A lot of files in /var/lib/rancher/k3s/data/current/bin/ get flagged by various Antvirus Software, e. g. ipset:

https://www.virustotal.com/gui/file/b52d5de7999a5b5b08ecc0bad539f99263b00bc6129aeb7327ead0e8f8b98bcd

SHA256: b52d5de7999a5b5b08ecc0bad539f99263b00bc6129aeb7327ead0e8f8b98bcd

This is the same sha for every current version in the channels v1.23 until latest.

The ipset file from version v1.22.17+k3s1:

https://www.virustotal.com/gui/file/618d9c1952ecfc13ce4358afec73e9283b7c24f968208656ad6fe2b3c7b3f8ef
SHA256: 618d9c1952ecfc13ce4358afec73e9283b7c24f968208656ad6fe2b3c7b3f8ef

List of files matched by F-Secure: 
```
blkid
coreutils
aux/ebtablesd
aux/ebtables-legacy
find
fuse-overlayfs
ip
ipset
losetup
nsenter
pigz
slirp4netns
aux/xtables-legacy-multi
aux/xtables-nft-multi
```

**Steps To Reproduce:**

- Installed K3s: sudo INSTALL_K3S_CHANNEL=<channel like v1.27> bash install.sh
- Check sha256: sha256sum /var/lib/rancher/k3s/data/current/bin/ipset
- Copy the sha into https://www.virustotal.com/gui/home/search

**Expected behavior:**
No results on virustotal.com
![image](https://github.com/k3s-io/k3s/assets/1735490/ff552d93-6476-4869-b294-52b7e9c7108f)

**Actual behavior:**
Some Hits on virustotal.com
![image](https://github.com/k3s-io/k3s/assets/1735490/e57ce498-c687-45bb-8e92-cbb7cbf45479)

**Additional context / logs:**

**Comment by thejan2009** [comment]
These packages are sourced from `k3s-root`, the same ipset SHA can be found there in the last two releases https://github.com/k3s-io/k3s-root/releases/download/v0.12.2/k3s-root-amd64.tar and https://github.com/k3s-io/k3s-root/releases/download/v0.13.0/k3s-root-amd64.tar

**Comment by benklett** [comment]
> These packages are sourced from `k3s-root`, the same ipset SHA can be found there in the last two releases https://github.com/k3s-io/k3s-root/releases/download/v0.12.2/k3s-root-amd64.tar and https://github.com/k3s-io/k3s-root/releases/download/v0.13.0/k3s-root-amd64.tar

Thank you for the hint. I have tried to build my own binaries with this repo, but the resulting ipset< binary has the exact same SHA hash.

k3s-root seems to use https://github.com/buildroot/buildroot to build the required binaries.

**Comment by cwayne18** [comment]
This is a false positive, for some reason it happens sometimes on the ML-driven VirusTotal scanners.  We will ensure they are properly marked as safe, thank you for the heads up!

**Comment by cwayne18** [comment]
It seems the false positives have been cleared: https://www.virustotal.com/gui/file/618d9c1952ecfc13ce4358afec73e9283b7c24f968208656ad6fe2b3c7b3f8ef

**Comment by benklett** [comment]
That ist the older file version, which was safe.

The current version is still affected:
https://www.virustotal.com/gui/file/b52d5de7999a5b5b08ecc0bad539f99263b00bc6129aeb7327ead0e8f8b98bcd

**Comment by benklett** [comment]
> blkid
> coreutils
> aux/ebtablesd
> aux/ebtables-legacy
> find
> fuse-overlayfs
> ip
> ipset
> losetup
> nsenter
> pigz
> slirp4netns
> aux/xtables-legacy-multi
> aux/xtables-nft-multi

@cwayne18 Can you tell me if you already submitted the files as false positive or do I have to do that?

**Comment by cwayne18** [comment]
Our security team has already submitted them, thank you for offering!

**Comment by cippaciong** [comment]
Hello @cwayne18, sorry for asking the same question as @benklett, it's just to be 100% sure I understood correctly.

We have a similar report for the `pigz` file included in K3s (https://www.virustotal.com/gui/file/d7ac92d1df715d2cb5ffa7a8a49b12be738e6e5808e2d8bcadadd799aaad2d8e/detection), do you confirm that this and all other files affected have been submitted as false positives to VirusTotal?

Thanks

**Comment by Cory-Christensen** [comment]
We're still getting security alerts for hash collision on `pigz`.

**Comment by rjshrjndrn** [comment]
Can we keep this issue open till the scanners clear the flag? And,  anybody who stumbles upon this issue will have visibility.

**Comment by brandond** [comment]
The false positives have been reported. There is no additional work to be done on our side at this time, and no timeline for when these low-quality scanners will address their issues.

**Comment by mjrist** [comment]
> The false positives have been reported. There is no additional work to be done on our side at this time, and no timeline for when these low-quality scanners will address their issues.

Hey @brandond, many of us have customers who are inquiring into this. So having some visibility on what is happening here would be very helpful.

By the way, if I compile these executables (e.g. pigz) from source the scanners don't complain. My assumption is that they don't like something about the way they are being sourced from buildroot.

Is there an FAQ/known issues documentation that notes on this could be added to? Open to other ideas. In essence just looking for something I can point customers to: "This is not an issue. Here is why."

Thanks.

**Comment by brandond** [comment]
Unfortunately we don't have any visibility into these ML-based scanners either. We report issues when they pop up, they go away after a period of time. It seems to happen about once a year or so they decide some random thing (usually busybox) is a virus, and we have to go through it again.

**Comment by benklett** [comment]
I have just read, that somehow signing could help with the issue. Would it be possible to always sign the released binaries to not let this happen again?

**Comment by cwayne18** [comment]
Signing the binaries wouldn't likely solve this issue, it's a bit out of our hands at the moment but we have reached out to Virustotal

**Comment by maxksec** [comment]
`xtables-nft-multi` is still flaged by virus total :(

```
/var/lib/rancher/k3s/data/3fcd4fcf3ae2ba4d577d4ee08ad7092538cd7a7f0da701efa2a8807d44a25f66/bin/aux$ sha256sum xtables-nft-multi
60efc5a86f68103c5cf263ba61bdd2a468f93685a947e987f018cac8b95497f2  xtables-nft-multi

``` 

https://www.virustotal.com/gui/file/60efc5a86f68103c5cf263ba61bdd2a468f93685a947e987f018cac8b95497f2?nocache=1

<img width="1448" alt="Screenshot 2024-04-04 at 13 26 53" src="https://github.com/k3s-io/k3s/assets/103882360/bbc76688-f9a5-4549-9014-21e9f9cf9889">

**Comment by uniit** [comment]
+ 1

Hi there,

k3s --version
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7

We received a notification from rapid7 about xtables-legacy-multi:

```
  "process": {
...
    "name": "xtables-legacy-multi",
...
    "exe_path": "/var/lib/rancher/k3s/data/b2c9b831d16a6f5e7d0224148df7be9b67491fc0f36e7a9a58e1e5b0c42b7258/bin/aux/xtables-legacy-multi",
    "cmd_line": "/var/lib/rancher/k3s/data/b2c9b831d16a6f5e7d0224148df7be9b67491fc0f36e7a9a58e1e5b0c42b7258/bin/aux/xtables-legacy-multi --help",
...
    "hash_reputation": {
      "reputation": "Malicious",
      "threat_level": "Critical",
      "reliability": "Low",
...
      "classification": {
        "family_name": "LuckyMouse",
        "type": "Trojan",
        "platform": "Linux"
      }
...
```
    

https://www.virustotal.com/gui/file/8cc834717af150b879f9cb9892236fd0fd4695d54bc50fc82a8d31f66a1bfa84

**Comment by brandond** [comment]
Still a false positive. Report it to your AV vendor and get them to fix it.

**Comment by burlyunixguy-bug** [comment]
Regarding: https://www.virustotal.com/gui/file/b52d5de7999a5b5b08ecc0bad539f99263b00bc6129aeb7327ead0e8f8b98bcd/detection

We finally got a response from our vendor that confirmed ipset (b52d5de7999a5b5b08ecc0bad539f99263b00bc6129aeb7327ead0e8f8b98bcd) is a false positive.  VirusTotal still has non-zero community score, but at least we can move on.
