### ISSUE TITLE
System upgrade controller not showing in Rancher after cluster import

### ISSUE THREAD

**Issue by mike12806** [k3s-io/k3s#9749]
**Environmental Info:**
K3s Version: 

K3S 1.27.11

Node(s) CPU architecture, OS, and Version: 

Intel / Ubuntu Linux 

Cluster Configuration:

2 servers, 6 agents. Using MariaDB on a seperate host for HA. 

**Describe the bug:**

I created a cluster from scratch via the K3S install scripts and imported the cluster into a Rancher installation (Rancher running in Docker). While the cluster is healthy and the import went fine, I'm not seeing an option for the system-upgrade-controller in Rancher to manage future upgrades. On my last cluster, I had a sytem-upgrade-controller option in Rancher (with plans attached to the nodes, I assume via the controller....)

The[ documentation for K3S](https://docs.k3s.io/upgrades/automated) indicates that Rancher will take over managing updates upon cluster import, but if so, why isn't the system upgrade controller being installed on cluster import into Rancher? 

Would've expected a system-upgrade-controller option in this menu on the LH side of the Rancher console

![Screenshot 2024-03-16 at 3 05 31 PM](https://github.com/k3s-io/k3s/assets/80599490/f10f5371-5456-4be5-bfa7-faa2392e7d39)

**Steps To Reproduce:**

1. Install K3S via install scripts
2. Import cluster into an existing Rancher setup
3. System-upgrade-controller isn't provisioned into the cluster upon import into Rancher 

**Expected behavior:**

SUC to be installed on cluster import

**Actual behavior:**

SUC not installed 

**Additional context / logs:**

Docs say I can't manually install SUC after Rancher import so now I'm stuck 😣

**Comment by brandond** [comment]
The SUC should be deployed when you edit the cluster and attempt to upgrade to a newer release of k3s. Until you attempt an upgrade, there is no need for a SUC deployment.

I'd transfer this to rancher/rancher as that is a more appropriate place for it, but I cannot as that is in a different org.

**Comment by mike12806** [comment]
How am I able to edit the cluster and attempt an upgrade without a deployed SUC? Is there any documentation on how to do that?

**Comment by mike12806** [comment]
I can raise an issue in rancher/rancher but I don't see an option here to update as the docs suggest should exist: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes#:~:text=On%20the%20Clusters%20page%2C%20go,Click%20Save.

![image](https://github.com/k3s-io/k3s/assets/80599490/0b7252f7-5147-4235-8d3b-91f8d5d9f5a5)

**Comment by brandond** [comment]
Rancher doesn't support anything newer than v1.27.11 at the moment.

**Comment by mike12806** [comment]
Opened an issue here: https://github.com/rancher/rancher/issues/44826
