### ISSUE TITLE
Add E2E Split server test to PR CI

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#9754]
**Is your feature request related to a problem? Please describe.**

We are missing coverage around split server testing in E2E. The test exists, but is only written for nightly E2E and does not run on PRs.
**Describe the solution you'd like**

Rework the https://github.com/k3s-io/k3s/tree/master/tests/e2e/splitserver test to be run on every PR, likely Drone due to VM sizing.
**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
we do test this in PRs. It is fairly recent though:
https://github.com/k3s-io/k3s/blob/8aecc26b0f167d5e9e4e9fbcfd5a471488bf5957/tests/docker/test-run-etcd#L41-L55
