### ISSUE TITLE
k3s tls certificate error

### ISSUE THREAD

**Issue by abstractalchemist** [k3s-io/k3s#9758]
**Environmental Info:**
K3s Version: 

v1.28.7+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux <redacted> 6.7.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 x86_64 GNU/Linux

Cluster Configuration:

Single node, running on a laptop

**Describe the bug:**

I have a k3s installation on a latop as indicated above.  Immediately after install, it works exactly as expected and continues to do so.    The laptop is normally connected to my private network via wired ethernet.  However, after removing it from the network by disconnecting the cable, then reconnecting the cable to connect it back to my private network, the following error shows up whenever I try to get the logs from a pod, the following error appears:

```
jason.hirata@<redacted>:~$ kubectl get po -n kube-system
NAME                                      READY   STATUS      RESTARTS   AGE
helm-delete-traefik-89rdz                 0/1     Completed   0          14m
helm-delete-traefik-crd-6j2tz             0/1     Completed   0          14m
metrics-server-67c658944b-bq8sx           0/1     Running     0          15m
local-path-provisioner-6c86858495-dh6lq   1/1     Running     0          15m
coredns-6799fbcd5-jjq5t                   1/1     Running     0          15m
jason.hirata@<redacted>:~$ kubectl logs -n kube-system coredns-6799fbcd5-jjq5t
Error from server: Get "https://10.42.0.1:10250/containerLogs/kube-system/coredns-6799fbcd5-jjq5t/coredns": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 192.168.86.33, <redacted>, not 10.42.0.1
jason.hirata@<redacted>:~$
```

I can no longer get logs out of my pods via ```kubectl logs```.  I'm not sure where to check or what to fix/delete.  I've tried rotating the certificates, as well as deleting all the pods, restarting k3s several times, and running ```/usr/local/bin/k3s --cluster-reset```.  The only solution that seems to help is completely uninstall k3s using the k3s-uninstall.sh script, then re-installing.

**Steps To Reproduce:**

- Installed K3s: 
- Verify K3s installed correctly and is running
- close latop and disconnect wired ethernet cable
- reconnect it later
- ssh into system, and run ```kubectl log``` command on a pod in the system

**Expected behavior:**

I don't expect to see this error. 

**Actual behavior:**

The error indicated above.
**Additional context / logs:**

Here's also some context log output from journalctl

```
Mar 19 17:36:33 <redacted> k3s[803539]: W0319 17:36:33.393982  803539 reflector.go:535] k8s.io/client-go@v1.28.7-k3s1/tools/cache/reflector.go:229: failed to list *v1.PartialObjectMetadata: the server could not find the requested resource
Mar 19 17:36:33 <redacted> k3s[803539]: E0319 17:36:33.394030  803539 reflector.go:147] k8s.io/client-go@v1.28.7-k3s1/tools/cache/reflector.go:229: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: the server could not find the requested resource
Mar 19 17:36:33 <redacted> k3s[803539]: E0319 17:36:33.572901  803539 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://10.42.0.1:10250/containerLogs/kube-system/metrics-server-67c658944b-bq8sx/metrics-server?follow=true&tailLines=100&timestamps=true", Err:(*tls.CertificateVerificationError)(0xc009bce210)}: Get "https://10.42.0.1:10250/containerLogs/kube-system/metrics-server-67c658944b-bq8sx/metrics-server?follow=true&tailLines=100&timestamps=true": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 192.168.86.33, <redacted>, not 10.42.0.1
Mar 19 17:36:33 <redacted> k3s[803539]: I0319 17:36:33.573089  803539 log.go:245] http: TLS handshake error from 127.0.0.1:34182: remote error: tls: bad certificate
```

**Comment by brandond** [comment]
K3s servers require a stable, static IP address. You might be able to configure a dummy interface, and use that as your --node-ip?

For laptops with changing network, you might look at Rancher Desktop, which includes k3s inside a virtual node with isolated networking.

**Comment by abstractalchemist** [comment]
Honestly I don't think this is an answer;  this seems like a bug to me.  I'm not sure if this will change anything, but I've also pinned the IP of wired NIC on my laptop on my private laptop so it's always the same IP.   I understand if the problem were switching between networks ( such as my private and work networks, for example ),  AND if the error showed any attempt to connect to a different address ( one that was part of the private network I'm a part of ), but this error shows the connect attempt to a IP that is clearly part of the pod CIDR, which never changes ( the IP of the api-server from inside the cluster? ).

Also, I'm not sure if anyone else is having this issue, but I was able to "solve" the problem by running the k3s-killall.sh script.  It seems to kill enough things that seems to erase the problem.  Not sure if I lose configuration or stored state information as a result of doing this, but at least it gets me back to being able to collect the logs of the pods again.

Also I feel that this not working runs counter to the mission of k3s being a small, light weight k8s install you can run in edge environments.  Of course this is my own opinion and I am no expert in k8s nor fully understanding the entire mission of k8s or k3s.

**Comment by davidshen84** [comment]
Got the same error, but `k3s-killall` did not help. My host IP did not change.


```
 stream logs failed Get "https://172.19.0.1:10250/containerLogs/crossplane-system/crossplane-7d7998d7f7-2d92n/crossplane?follow=true&tailLines=100&timestamps=true": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 192.168.86.27, ::ipv6::, not 172.19.0.1 for crossplane-system/crossplane-7d7998d7f7-2d92n (crossplane)
```

Strangely, `172.19.0.1` does not match any network segment in my k3s cluster. However, it is the `docker_gwbridge` IF address.
