### ISSUE TITLE
Use auto find runtime configfile inject in containerd config.toml then containerd startup failed

### ISSUE THREAD

**Issue by Bao0ne** [k3s-io/k3s#9760]
**Environmental Info:**
K3s Version: 
![image](https://github.com/k3s-io/k3s/assets/37828835/ee09a5e0-b94e-4420-b779-0b9fff959d55)

Cluster Configuration:
 1servers

**Describe the bug:**

* use #9431 auto generate and inject runtime class configuration
* Prepare e.g. nvidia operateor related binaries
* start k3s
* containerd startup failed

![image](https://github.com/k3s-io/k3s/assets/37828835/2dd31954-c44c-437a-8892-84e509f77207)

**Expected behavior:**
K3s and containerd normal operation

**Actual behavior:**
Containerd startup failed

**Additional context / logs:**
Generate runtimeclass configuration in config.toml ：
```
...
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."xxx"]
...
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."xxx".options]
...
```

**Comment by brandond** [comment]
what exactly have you blurred out in your screenshot there? Is there some reason you can't include the actual log, instead of a redacted screenshot?

**Comment by brandond** [comment]
Please provide **specific** steps to reproduce your issue.
