### ISSUE TITLE
K3s should not disable etcd and apiserver when used with kine

### ISSUE THREAD

**Issue by vitorsavian** [k3s-io/k3s#9765]
- It should return a error when k3s initiate with `--disable-etcd` or `--disable-apiserver` and `--datastore-endpoint`

**Comment by VestigeJ** [comment]
So this doesn't surface if you use the systemd service it correctly bails out of startup. You can surface this by running the k3s server command specifically. If you run this on the existing release you will see somewhat typical stdout startup but the cluster never comes up and is ready.
```
sudo /usr/local/bin/k3s server --disable-etcd --datastore-endpoint sqlite
```



##Environment Details
Reproduced using VERSION=v1.29.3+k3s1
Validated using COMMIT=0e118fe6d3ded5eff02b8e3acc2664b0ac5364bd

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"

*Cluster Configuration:*



*Config.yaml:*

```
node-external-ip: 18.116.115.150
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
profile: cis
selinux: true
protect-kernel-defaults: true
```

<details><summmary><h4>Steps/Results</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ COMMIT=0e118fe6d3ded5eff02b8e3acc2664b0ac5364bd
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC="server --disable-etcd --datastore-endpoint" ./install-k3s.sh
$ sudo journalctl -xeu k3s //observe error 
$ sudo /usr/local/bin/k3s server --disable-etcd --datastore-endpoint sqlite //observe error
```

</details>
