### ISSUE TITLE
K3S Rootless - IPtables-restore failed

### ISSUE THREAD

**Issue by ballj** [k3s-io/k3s#9769]
**Environmental Info:**
K3s Version: v1.29.1+k3s2

Node(s) CPU architecture, OS, and Version: 

Linux labk3s01 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server - rootless mode

**Describe the bug:**

When using K3S in rootless mode, the iptables-restore command fails to perform the sync . I have tried loading the output into a fresh iptables instance (new vm install) and it seems to load without any issues - suggesting it is syntactically correct. Performing `iptables-save` within the k3s namespace also shows a large number of iptables rules.

**Steps To Reproduce:**

- Fresh ubuntu 22.04 install
- Installed packages: uidmap
- Enable ipv4 forwarding
- Installed K3s: Followed rootless instructions and ran with systemd unit file
- Deployed ~40 pods (1-2 containers per pod)
- Dont think it happened straight away, noticed it after a while.

**Expected behavior:**
The iptabes-restore / sync works as expected.

**Actual behavior:**
Every 5 mins, the network_policy_controller will try to perform a sync. The sync fails and puts the iptables restore content in the logs. on a larger k3s deployment this causes the logs to fill up quickly.

**Additional context / logs:**

Using OS binaries:
```
E0322 17:09:01.292061      57 network_policy_controller.go:311] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 1 (iptables-restore: line 692 failed)
*filter
:INPUT ACCEPT [97993980:121319842986] - [0:0]
:FORWARD ACCEPT [0:0] - [0:0]
:OUTPUT ACCEPT [99048921:106257284251] - [0:0]
:FLANNEL-FWD - [0:0] - [0:0]
:KUBE-EXTERNAL-SERVICES - [0:0] - [0:0]
:KUBE-FIREWALL - [0:0] - [0:0]
:KUBE-FORWARD - [0:0] - [0:0]
:KUBE-KUBELET-CANARY - [0:0] - [0:0]
...
-A KUBE-POD-FW-MUBBVCI2WOFJAJVS -j MARK --set-mark 0/0x10000
-A KUBE-POD-FW-MUBBVCI2WOFJAJVS -m comment --comment "set mark to ACCEPT traffic that comply to network policies" -j MARK --set-mark 0x20000/0x20000
COMMIT
```

With `--prefer-bundled-bin=true` set:
```
E0322 17:06:54.584069      36 network_policy_controller.go:311] Aborting sync. Failed to run iptables-restore: failed to call iptables-restore: exit status 1 (sendmsg() failed: Message too large iptables-restore: line 692 failed)
```

**Comment by brandond** [comment]
The `(sendmsg() failed: Message too large iptables-restore: line 692 failed)` makes me suspect that there is a buffer size sysctl that is too small within your user namespace. Can you provide the output of `sysctl -a` from within the k3s rootless namespace?

**Comment by ballj** [comment]
[sysctl.txt](https://github.com/k3s-io/k3s/files/14726974/sysctl.txt)

Filtered out the veth interfaces using the following: `grep -v 'conf.veth'`.

**Comment by brandond** [comment]
The difference in log message is due to our bundled iptables binary having improved error logging, see this change:

https://git.netfilter.org/iptables/commit/?id=a3e81c62e8c5abb4158f1f66df6bbcffd1b33240

The comment at https://serverfault.com/questions/1143773/lxc-container-fail-to-load-big-iptables-rules#comment1492057_1143773 suggests that this is a kernel limitation that only affects unprivileged use of the nft backend; you might see if using iptables-legacy is not affected by this issue?

You could also disable the network policy controller, to keep the iptables ruleset size under the cap enforced by the kernel.

**Comment by ballj** [comment]
net.core as root:
```
net.core.bpf_jit_enable = 1
net.core.bpf_jit_harden = 0
net.core.bpf_jit_kallsyms = 1
net.core.bpf_jit_limit = 528482304
net.core.busy_poll = 0
net.core.busy_read = 0
net.core.default_qdisc = fq_codel
net.core.dev_weight = 64
net.core.dev_weight_rx_bias = 1
net.core.dev_weight_tx_bias = 1
net.core.devconf_inherit_init_net = 0
net.core.fb_tunnels_only_for_init_net = 0
net.core.flow_limit_cpu_bitmap = 00
net.core.flow_limit_table_len = 4096
net.core.gro_normal_batch = 8
net.core.high_order_alloc_disable = 0
net.core.max_skb_frags = 17
net.core.message_burst = 10
net.core.message_cost = 5
net.core.netdev_budget = 300
net.core.netdev_budget_usecs = 8000
net.core.netdev_max_backlog = 1000
net.core.netdev_tstamp_prequeue = 1
net.core.netdev_unregister_timeout_secs = 10
net.core.optmem_max = 20480
net.core.rmem_default = 212992
net.core.rmem_max = 212992
net.core.rps_sock_flow_entries = 0
net.core.somaxconn = 4096
net.core.tstamp_allow_data = 1
net.core.warnings = 0
net.core.wmem_default = 212992
net.core.wmem_max = 212992
net.core.xfrm_acq_expires = 165
net.core.xfrm_aevent_etime = 10
net.core.xfrm_aevent_rseqth = 2
net.core.xfrm_larval_drop = 1
```

net.core as k3s user:
```
net.core.busy_poll = 0
net.core.busy_read = 0
net.core.default_qdisc = fq_codel
net.core.dev_weight = 64
net.core.dev_weight_rx_bias = 1
net.core.dev_weight_tx_bias = 1
net.core.devconf_inherit_init_net = 0
net.core.fb_tunnels_only_for_init_net = 0
net.core.flow_limit_cpu_bitmap = 00
net.core.flow_limit_table_len = 4096
net.core.gro_normal_batch = 8
net.core.high_order_alloc_disable = 0
net.core.max_skb_frags = 17
net.core.message_burst = 10
net.core.message_cost = 5
net.core.netdev_budget = 300
net.core.netdev_budget_usecs = 8000
net.core.netdev_max_backlog = 1000
net.core.netdev_tstamp_prequeue = 1
net.core.netdev_unregister_timeout_secs = 10
net.core.optmem_max = 20480
net.core.rmem_default = 212992
net.core.rmem_max = 212992
net.core.rps_sock_flow_entries = 0
net.core.somaxconn = 4096
net.core.tstamp_allow_data = 1
net.core.warnings = 0
net.core.wmem_default = 212992
net.core.wmem_max = 212992
net.core.xfrm_acq_expires = 165
net.core.xfrm_aevent_etime = 10
net.core.xfrm_aevent_rseqth = 2
net.core.xfrm_larval_drop = 1
```

I will give it a try with iptables-legacy later today.

**Comment by brandond** [comment]
Closing as limitation of iptables nft backend. This could probably be added to the list of known issues with rootless k3s.
