### ISSUE TITLE
K3s docker image is missing user info for root

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9789]
When execing into the k3s image, the root user (that k3s runs as) has no userinfo (no name, default home dir, groups, so on)

```console
/ # PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

@k3s-server-1:/# id
uid=0 gid=0 groups=0

@k3s-server-1:/# whoami
whoami: cannot find name for user ID 0: No such file or directory

@k3s-server-1:/# groups
groups: cannot find name for group ID 0
0

@k3s-server-1:/# cat /etc/passwd
cat: /etc/passwd: No such file or directory

```

This doesn't necessarily break anything, but it is somewhat irritating if you're trying to interact with the container and expect userinfo to be available.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  k3s version v1.29.3+k3s-06b64449 (06b64449)


```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
SUSE Linux Enterprise Server 15 SP4   


*Cluster Configuration:*
- 1 server 
 
 
## Steps to validate the fix
1.  run k3s on docker and exec into it
2. Validate user infos


 
 
## **Reproduction Issue:**
<details>

``` 

/k3s$ sudo docker exec -it k3s-server sh
/ # id
uid=0 gid=0 groups=0
/ # k3s -v
k3s version v1.28.8+k3s1 (653dd61a)
go version go1.21.8
/ # whoami
whoami: cannot find name for user ID 0: No such file or directory

 
```

 
## **Validation Results:**
<details>


``` 
 

 ~ # whoami
root
 
~ # cat /etc/passwd /etc/group
root:x:0:0:root:/:/bin/sh
root:x:0:

~ # groups
root
```
