### ISSUE TITLE
[Release-1.28] - Unrecoverable error when joining node attempts to retrieve etcd member list from itself

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9790]
Backport fix for Unrecoverable error when joining node attempts to retrieve etcd member list from itself

* #9661

**Comment by mdrahman-suse** [comment]
Unable to replicate / validate in k3s, but was able to replicate with rke2. Validation is done on the rke2 commit with k3s pull through and tracked in here: https://github.com/rancher/rke2/issues/5805#issuecomment-2065377090
