### ISSUE TITLE
Rename master node

### ISSUE THREAD

**Issue by TTAbwill** [k3s-io/k3s#9798]
Hi there,

first of all, thank you for the great project!

I have just changed my home lab cluster from 1 master with sqlite node to 3 masters with etcd and have a comprehension question. 

I would like to install the first (former sqlite) master node nine times and rename it. Does it still have a special role in the cluster, as I used it to join new nodes? Or can I simply delete the node from the cluster, reinstall it and add it back to the cluster with a different hostname?

Thanks in advance.

**Comment by brandond** [comment]
Kubernetes objects, including nodes, cannot be renamed. If you want to rename a node, you should delete it with `kubectl delete node`, and then restart k3s on that node. 

If you are using etcd, be careful to ensure you have quorum in the cluster. For 3 nodes, that would mean having at least 2 nodes running at all atimes.
