### ISSUE TITLE
[Release-1.27] - K3s docker image is missing user info for root

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9813]
Backport fix for K3s docker image is missing user info for root

* #9789

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  k3s version v1.27.12+k3s-2d48b196 (2d48b196)


```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
SUSE Linux Enterprise Server 15 SP4   


*Cluster Configuration:*
- 1 server 
 
 
## Steps to validate the fix
1.  run k3s on docker and exec into it
2. Validate user infos


 
 
## **Reproduction Issue:**
<details>

``` 

/k3s$ sudo docker exec -it k3s-server sh
/ # id
uid=0 gid=0 groups=0
/ # k3s -v
k3s version v1.28.8+k3s1 (653dd61a)
go version go1.21.8
/ # whoami
whoami: cannot find name for user ID 0: No such file or directory

 
```

 
## **Validation Results:**
<details>


``` 
 

 ~ # whoami
root
 
~ # cat /etc/passwd /etc/group
root:x:0:0:root:/:/bin/sh
root:x:0:

~ # groups
root
```
