### ISSUE TITLE
remove k3s node by node annotation?

### ISSUE THREAD

**Issue by mogliang** [k3s-io/k3s#9817]
**Is your feature request related to a problem? Please describe.**
We are developing k3s controlplane/bootstrap provider for ClusterAPI, and we are not sure what's the right way to remove a node from k3s cluster. I know there is a uninstall script on host vm, but there is no way to invoke that script from kubeconfig cluster connection.

ClusterAPI management cluster can only access workload cluster by the kubeconfig, I found out that there is way to add annotation "etcd.k3s.cattle.io/remove" to remove etcd member, i want to know if there is such annotation as well to remove node?

Thanks,

**Comment by brandond** [comment]
That is for removing the node from the etcd cluster without deleting it. If you just want it gone, use `kubectl delete node`.
