### ISSUE TITLE
S3 Snapshot Retention policy is too aggressive

### ISSUE THREAD

**Issue by maggie44** [k3s-io/k3s#9866]
**Describe the bug:**
A PR had been introduced that prunes S3 etcd backups by date: 

* https://github.com/k3s-io/k3s/pull/8124
*https://docs.k3s.io/release-notes/v1.24.X#release-v12417k3s1

The default `etcd-snapshot-retention` is `5`. 

Since this PR, only 5 total snapshots are allowed in S3 buckets, rather than 5 per control plane. This means that for my cluster with three control planes, I only have one backup for one of them, and the backups for the others are only from today (total of 5). As I add more control planes, presumably some are not going to be backed up at all as they will be pruned immediately in favour of the latest by date (one more control plane would push out that top fsn1 backup completely): 

<img width="1182" alt="Screenshot 2024-04-04 at 17 16 40" src="https://github.com/k3s-io/k3s/assets/64841595/be769b74-ff2a-432a-aeb9-f2d46a2910ae">

If my understanding here is correct, this is a significant breaking change in the patch release that has reduced the number of backups available for people's clusters, potentially leading to nasty surprises when they go back to check them.  

A potential solution is to change the `etcd-snapshot-retention` to `number-of-control-planes*5` manually but that is a lot of custom configuration and I'm not sure this need is understood/documented. 

A similar issue is reported here: https://github.com/rancher/rke2/issues/5216

**Expected behavior:**
5 backups per control-plane. 

Perhaps the default of 5 should be raised to at least cover the common scenario of three control planes; or S3 should be `etcd-snapshot-retention x number of control planes`. Or perhaps restoring the original behaviour and implementing a different process for cleaning up orphaned snapshots with `age > n`. Ideally some way to communicate the impact this is having on existing clusters too.

**Comment by brandond** [comment]
This is discussed in some detail at https://github.com/rancher/rke2/issues/5216#issuecomment-1896796970, which I see you already linked. There is also another related issue:
* https://github.com/rancher/rancher/issues/43872

**Comment by horihel** [comment]
hello friendly bot - s3 backup retention policies are still broken, no direct workaround available. Let's hope everyone has soft-delete features in their s3-buckets to make up for it.

**Comment by horihel** [comment]
that said, does anyone know how to make an 'undeleted' backup known to rancher so it can be restored?

**Comment by HoustonDad** [comment]
not stale

**Comment by bwenrich** [comment]
Not stale.

Q: for the use case with multiple control planes, would it be helpful if each cluster used a different path/prefix in the S3 bucket?

That might avoid the issue in the linked RKE issue (about data from deleted nodes never getting pruned), but also prevent clusters from pruning data belonging to each other.

If this cannot be done, I would wonder if it's even safe to have multiple clusters sharing the same S3 bucket, considering that "misconfiguring" the pruning on one of them could have a wide impact to all of their snapshots.

**Comment by brandond** [comment]
No, all the nodes should use the same bucket and prefix. It is assumed (and we should probably document this as a requirement) that all nodes use the same bucket and prefix. If this does not happen nodes will remove snapshot records created by other nodes, thinking that they are "missing" from s3 - since they are all expected to have the same view of what exists on S3.

**Comment by horihel** [comment]
would it make more sense then to disable the built-in retention altogether and instead use retention policies built into the s3 backend? Is k3s/rke2 able to handle that?
