### ISSUE TITLE
bind-address option are not suffisant to make k3s listen on specifique ip address

### ISSUE THREAD

**Issue by mcarbonneaux** [k3s-io/k3s#9873]
**Environmental Info:**
K3s Version: 
lastest : v1.28.8+k3s1 (653dd61a)

Node(s) CPU architecture, OS, and Version: 
ubuntu 22.04 with 4 cores and 32go.

Cluster Configuration:
single server, with one private ip and many public ip.

**Describe the bug:**
i try to configure k3s to listening on specifique ip.
when i configure my cluster to listen on specifique ip ("privateip") with `--bind-address` options they refuse to start, with error : 

```
Apr 07 00:55:10 myhost k3s[1149269]: time="2024-04-07T00:55:10+02:00" level=info msg="Connecting to proxy" url="wss://"publicip":6443/v1-k3s/connect"
Apr 07 00:55:10 myhost k3s[1149269]: time="2024-04-07T00:55:10+02:00" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp "publicip":6443: connect: connection refused"
Apr 07 00:55:10 myhost k3s[1149269]: time="2024-04-07T00:55:10+02:00" level=error msg="Remotedialer proxy error" error="dial tcp "publicip":6443: connect: connection refused"
```

**Steps To Reproduce:**

```
export NODE_IP=192.168.0.1
export HOSTNAME=myhost

export INSTALL_K3S_EXEC="server \
    --bind-address=${NODE_IP} \
    --node-ip=${NODE_IP} \
    --node-external-ip="mypublicip" \
    --server=${NODE_IP} \
    --tls-san=${NODE_IP} \
    --kubelet-arg=address=${NODE_IP} "

export K3S_URL=https://${NODE_IP}:6443
curl -sfL https://get.k3s.io | sh -s - --docker
```

**Expected behavior:**
k3s listening on private ip, up and running without error.

**Actual behavior:**
k3s not start completely.

**Comment by manuelbuil** [comment]
I think you should use `AdvertiseIP` instead of `bind-address`. If you don't mind me asking: why are you using `--node-external-ip` but then require your kube-api to listen in a private address?

**Comment by mcarbonneaux** [comment]
> If you don't mind me asking: why are you using `--node-external-ip` but then require your kube-api to listen in a private address?

i want to expose my kube-api only on private (to avoid security problem if public exposed), and application exposition (ingress and co) to public ip.

**Comment by mcarbonneaux** [comment]
when i use advertise ip in place of bind-address : 
```
# netstat -lnput | grep k3s
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:10258         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 192.168.0.1:10250       0.0.0.0:*               LISTEN      2625498/k3s server
tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      2625498/k3s server
tcp6       0      0 :::6443                 :::*                    LISTEN      2625498/k3s server
tcp6       0      0 :::41373                :::*                    LISTEN      2625498/k3s server
```
i have tcp6 listen on any interface...

**Comment by mcarbonneaux** [comment]
i found the sollution for `::6443` in documentation of k3s [dual stack ipv4 ipv6 networking](https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking) :
```
--kubelet-arg="node-ip=${NODE_IP}" 
```

but i think that is not normal that  `--node-ip` of k3s server not set correctly the value in the kubelet config...

the last think that last problem are : 
```
tcp6       0      0 :::41373                :::*                    LISTEN      2625498/k3s server
```

it's dynamique port and is listening on ipv6....

**Comment by mcarbonneaux** [comment]
there a solution to see who listen in `k3s server`, witch part of k3s is listening on any interface ?

**Comment by manuelbuil** [comment]
> when i use advertise ip in place of bind-address :
> 
> ```
> # netstat -lnput | grep k3s
> tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:10258         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 192.168.0.1:10250       0.0.0.0:*               LISTEN      2625498/k3s server
> tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      2625498/k3s server
> tcp6       0      0 :::6443                 :::*                    LISTEN      2625498/k3s server
> tcp6       0      0 :::41373                :::*                    LISTEN      2625498/k3s server
> ```
> 
> i have tcp6 listen on any interface...

This output is weird, `6443` should be available in all interfaces for ipv4 or ipv6. I recommend you to use `ss` instead of netstat. Netstat is supposed to be deprecated (like ifconfig, route, etc)

**Comment by mcarbonneaux** [comment]
> This output is weird, `6443` should be available in all interfaces for ipv4 or ipv6. I recommend you to use `ss` instead of netstat. Netstat is supposed to be deprecated (like ifconfig, route, etc)

After use node ip option is now listening only on ipv4 I setted but we have dynamique port continuing listening...

Sorry I use netstat by habitude....

**Comment by mcarbonneaux** [comment]
but when try to access to my container with exec command i receive this error:
```
# kubectl run -i -t --image=alpine debug
If you don't see a command prompt, try pressing enter.
warning: couldn't attach to pod/debug, falling back to streaming logs: error dialing backend: proxy error from 192.168.0.1:6443 while dialing 192.168.0.1:10250, code 502: 502 Bad Gateway
Error from server: Get "https://192.168.0.1:10250/containerLogs/ch2o/debug/debug": proxy error from 192.168.0.1:6443 while dialing 192.168.0.1:10250, code 502: 502 Bad Gateway
```
