### ISSUE TITLE
Validate resolv.conf for presence of nameserver entries

### ISSUE THREAD

**Issue by x-coder-L** [k3s-io/k3s#9874]
**Is your feature request related to a problem? Please describe.**
 We are currently using k3s version 1.28.4 and have encountered an issue. If the /etc/resolv.conf file lacks any nameserver entries, the coredns pod fails to run. However, if the /etc/resolv.conf file is absent, coredns operates correctly.
**Describe the solution you'd like**

We suggest that if the /etc/resolv.conf file lacks any nameserver entries, the k3s agent should generate a resolv.conf file. This would allow coredns to run properly.
**Describe alternatives you've considered**

Upon examining the k3s code, we found a section in k3s/pkg/agent/config/config.go that validates the resolv.conf file. We propose adding a check here to validate the presence of nameserver entries in resolv.conf.
https://github.com/k3s-io/k3s/blob/f099bfa508ede0532ede16ec6d4521cb8b144de6/pkg/agent/config/config.go#L301
**Additional context**

**Comment by yashvardhan-kukreja** [comment]
Hi, I would love to contribute to this one if this gets accepted.
Looks like an interesting issue to work on as my first contribution to k3s :)

**Comment by x-coder-L** [comment]
I’m glad you’ve taken notice of this issue. I believe we can enhance it together through discussion.
I think this a small and easy change for this feature.However, I’m uncertain if resolving my problem in the isValidResolvConf function is appropriate.
Additionally, I’m curious as to why k3s generates an agent-resolv.conf under such circumstances. I haven’t found any documentation indicating that k3s will generate a resolv.conf file.

> Hi, I would love to contribute to this one if this gets accepted. Looks like an interesting issue to work on as my first contribution to k3s :)

**Comment by brandond** [comment]
> I’m uncertain if resolving my problem in the isValidResolvConf function is appropriate.

I think that's a fine place to do it. As far as k3s is concerned, not having any upstream is just as invalid as having multicast/loopback upstreams.

> I’m curious as to why k3s generates an agent-resolv.conf under such circumstances. I haven’t found any documentation indicating that k3s will generate a resolv.conf file.

K3s has always done this, but you're correct that we could probably enhance the documentation to cover the behavior.

**Comment by x-coder-L** [comment]
Kindly to ask if there is somebody working for this issue?If not I'm gald to undertake it.

**Comment by yashvardhan-kukreja** [comment]
I see that you have already raised the PR, so yeah I think you can take it over.
Thanks!

**Comment by fmoral2** [comment]
https://github.com/k3s-io/k3s/pull/10302
