### ISSUE TITLE
Etcd load-balancer on control-plane-only server may select removed etcd cluster member as default server

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9882]
K3s tracking issue for:
* https://github.com/rancher/rke2/issues/5646

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ k3s version v1.29.3+k3s-06b64449 (06b64449)



```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu   
AMD64

*Cluster Configuration:*
Split role:
- 3 cp only
- 3 workers
- 3 etcd only
 
 
## Steps to validate the fix
1. start k3s on split role
2. get logs on cp only 
3. Validate that the address of the server specified in the --server address is always reported as the server address in the etcd load-balancer log message


 
 
## **Reproduction Issue:**
<details>

``` 
 
 
 
 
```

 
## **Validation Results:**
<details>


``` 

 
$ cat /etc/rancher/k3s/config.yaml
write-kubeconfig-mode: "0644"
tls-san:
  - 3.147.2.18
server: https://3.147.2.18:6443

ip-172-31-14-164.us-east-2.compute.internal   Ready    etcd                   53m   v1.29.3+k3s-06b64449   172.31.14.164   3.147.2.18   


 :~$ sudo journalctl --no-pager -u k3s | grep "Adding" -A2
Apr 16 22:47:24 ip-172-31-1-64 k3s[2049]: time="2024-04-16T22:47:24Z" level=info msg="Adding server to load balancer k3s-etcd-server-load-balancer: 172.31.14.164:2379"

Apr 16 22:47:24 ip-172-31-1-64 k3s[2049]: time="2024-04-16T22:47:24Z" level=info msg="Running load balancer k3s-etcd-server-load-balancer 127.0.0.1:2379 -> [172.31.14.164:2379] [default: 172.31.14.164:2379]"


```
