### ISSUE TITLE
[Release-1.27] - Etcd load-balancer on control-plane-only server may select removed etcd cluster member as default server

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9892]
Backport fix for Etcd load-balancer on control-plane-only server may select removed etcd cluster member as default server

* #9882

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ k3s version v1.27.13-rc1+k3s1 (33ee1687)



```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu   
AMD64

*Cluster Configuration:*
Split role:
- 3 cp only
- 3 workers
- 3 etcd only
 
 
## Steps to validate the fix
1. start k3s on split role
2. get logs on cp only 
3. Validate that the address of the server specified in the --server address is always reported as the server address in the etcd load-balancer log message


 
 
## **Reproduction Issue:**
<details>

``` 
 
 
 
 
```

 
## **Validation Results:**
<details>


``` 

$ cat /etc/rancher/k3s/config.yaml
write-kubeconfig-mode: "0644"
tls-san:
  - 18.118.33.186
server: https://18.118.33.186:6443


ip-172-31-7-38.us-east-2.compute.internal     Ready    etcd                   8m57s   v1.27.13-rc1+k3s1   172.31.7.38     18.118.33.186


 sudo journalctl --no-pager -u k3s | grep "Adding" -A2
Apr 16 23:35:47 ip-172-31-15-16 k3s[2046]: time="2024-04-16T23:35:47Z" level=info msg="Adding server to load balancer k3s-etcd-server-load-balancer: 172.31.7.38:2379"

Apr 16 23:35:47 ip-172-31-15-16 k3s[2046]: time="2024-04-16T23:35:47Z" level=info msg="Running load balancer k3s-etcd-server-load-balancer 127.0.0.1:2379 -> [172.31.7.38:2379] [default: 172.31.7.38:2379]"

```
