### ISSUE TITLE
Which interface can you use to obtain the certificate expiration time of k3s cluster

### ISSUE THREAD

**Issue by CharesLee** [k3s-io/k3s#9905]
I have a k3s cluster, the version is k3s version v1.23.2+k3s1 (fc8309a4)
The go version is go1.17.5. Now I am configiting Prometheus to monitor the cluster, and I have added a blackbox exporter for site monitoring. Considering that k3s cluster also has certificates, can I use blackbox exporter to monitor the expiration time of certificates? Remind me when the certificate is about to expire, in case I forget to restart k3s and cause the cluster certificate to expire

**Comment by brandond** [comment]
We actually just built this in to k3s. It'll be available in the next release.
* https://github.com/k3s-io/k3s/pull/9772
