### ISSUE TITLE
install failing 0.10.1 on Centos 7.4.1708

### ISSUE THREAD

**Issue by asloan7** [k3s-io/k3s#992]
curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.10.1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.10.1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
which: no kubectl in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
which: no crictl in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
which: no ctr in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink from /etc/systemd/system/multi-user.target.wants/k3s.service to /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details.

k3s -v
k3s version v0.10.1 (7d650d32)

**Comment by bhale** [comment]
Could you post the results of 'journalctl -xe -u k3s.service' ?

**Comment by asloan7** [comment]
journalctl -xe -u k3s.service
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: time="2019-10-30T21:16:54.614666188Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --autho
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.616031   19933 server.go:650] external host was not specified, using 96.113.0.86
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.616418   19933 server.go:162] Version: v1.16.2-k3s.1
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.624514   19933 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.624536   19933 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.625663   19933 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.625682   19933 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.672564   19933 master.go:259] Using reconciler: lease
Oct 30 21:16:54 server-19p.domain123.net k3s[19933]: I1030 21:16:54.701419   19933 rest.go:115] the default service ipfamily for this cluster is: IPv4
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.124833   19933 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.145444   19933 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.166496   19933 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.171111   19933 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.183998   19933 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.219428   19933 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: W1030 21:16:55.219463   19933 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: I1030 21:16:55.233090   19933 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: I1030 21:16:55.233109   19933 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: time="2019-10-30T21:16:55.239798530Z" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader
Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use
Oct 30 21:16:55 server-19p.domain123.net systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Oct 30 21:16:55 server-19p.domain123.net systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has failed.
--
-- The result is failed.
Oct 30 21:16:55 server-19p.domain123.net systemd[1]: Unit k3s.service entered failed state.
Oct 30 21:16:55 server-19p.domain123.net systemd[1]: k3s.service failed.
Oct 30 21:17:00 server-19p.domain123.net systemd[1]: k3s.service holdoff time over, scheduling restart.
Oct 30 21:17:00 server-19p.domain123.net systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has begun starting up.
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: time="2019-10-30T21:17:00.820975092Z" level=info msg="Starting k3s v0.10.1 (7d650d32)"
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: time="2019-10-30T21:17:00.825146600Z" level=info msg="Kine listening on unix://kine.sock"
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: time="2019-10-30T21:17:00.826114059Z" level=info msg="Fetching bootstrap data from etcd"
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: time="2019-10-30T21:17:00.853106036Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --autho
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.854725   20194 server.go:650] external host was not specified, using 96.113.0.86
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.855145   20194 server.go:162] Version: v1.16.2-k3s.1
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.863548   20194 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.863569   20194 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.864715   20194 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.864736   20194 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.900555   20194 master.go:259] Using reconciler: lease
Oct 30 21:17:00 server-19p.domain123.net k3s[20194]: I1030 21:17:00.927480   20194 rest.go:115] the default service ipfamily for this cluster is: IPv4
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.360044   20194 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.382180   20194 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.403360   20194 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.407355   20194 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.421344   20194 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.469516   20194 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: W1030 21:17:01.469542   20194 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: I1030 21:17:01.482102   20194 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeR
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: I1030 21:17:01.482119   20194 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolu
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: time="2019-10-30T21:17:01.490203985Z" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader
Oct 30 21:17:01 server-19p.domain123.net k3s[20194]: failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use
Oct 30 21:17:01 server-19p.domain123.net systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Oct 30 21:17:01 server-19p.domain123.net systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has failed.
--
-- The result is failed.
Oct 30 21:17:01 server-19p.domain123.net systemd[1]: Unit k3s.service entered failed state.
Oct 30 21:17:01 server-19p.domain123.net systemd[1]: k3s.service failed.
lines 1331-1404/1404 (END)

**Comment by erikwilson** [comment]
We should check for free ports earlier in the startup process, but the issue here is `bind: address already in use`. What is the output of `netstat -tlnp | grep 10251`?

**Comment by drbugfinder** [comment]
Same problem here on openSUSE 15.1 (on RPi 3)

**Comment by warmchang** [comment]
`Oct 30 21:16:55 server-19p.domain123.net k3s[19933]: failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use`

10251 alreday in use, try to check `netstat -tlnp | grep 10251` as @erikwilson mentioned: https://github.com/rancher/k3s/issues/992#issuecomment-548179501

**Comment by cjellick** [comment]
@erikwilson is there anything to be done here or can this simply be chalked up to "the ports in use, nothing we can do"?
