### ISSUE TITLE
Option service-node-port-range gets ignored

### ISSUE THREAD

**Issue by salzig** [k3s-io/k3s#9952]
**Environmental Info:**
K3s Version: 
```
k3s version v1.29.3+k3s1 (8aecc26b)
go version go1.21.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux potato 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
```

Cluster Configuration:
Single Node

**Describe the bug:**
According to https://docs.k3s.io/cli/server the cli option `service-node-port-range` can be passed as CLI option or can be configured in `/etc/rancher/k3s/config.yaml`, for me it's configured in file as follows
```
…
service-node-port-range: 1000-32767
```

but in newer version (can't triangulate right now) it fails to apply this configuration, as seen when creating a NodePort:
```
# kubectl create svc nodeport example --node-port=1010 --tcp=1010:1010
error: failed to create NodePort service: Service "example" is invalid: spec.ports[0].nodePort: Invalid value: 1010: provided port is not in the valid range. The range of valid ports is 30000-40000
```

In newer version? Yes, service with that NodePort did already run and was used by other services that now started to complain because the service is not reachable anymore. 

**Steps To Reproduce:**
- Installed K3s: v1.29.3+k3s1 as Systemd Service
- Append ServiceNodePortRange to `/etc/rancher/k3s/config.yaml`: `echo service-node-port-range: 1000-32767 > /etc/rancher/k3s/config.yaml`
- Restart K3s: `systemctl restart k3s`
- Create NodePort: `kubectl create svc nodeport example --node-port=1010 --tcp=1010:1010`

**Expected behavior:**
NodePort Service should be valid and created

**Actual behavior:**
Port Range validation fails.

**Comment by brandond** [comment]
Works fine for me, did you figure out what your problem was?
```console
brandond@dev01:~/$ kubectl get node -o yaml | grep service-node-port-range
      k3s.io/node-args: '["server","--service-node-port-range","1000-32767"]'

brandond@dev01:~$ kubectl create svc nodeport example --node-port=1010 --tcp=1010:1010
service/example created
```

**Comment by salzig** [comment]
yes, was a very big Layer-8 error. Something a long the lines of check who you're talking with. That's why I just closed the issue ;)
