### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by lucas03** [k3s-io/k3s#9954]
**Environmental Info:**
K3s Version: 
k3s version v1.26.3+k3s1 (01ea3ff2)
go version go1.19.7

Node(s) CPU architecture, OS, and Version: 
Linux thor 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

Cluster Configuration:
single server, hobby project

**Describe the bug:**
certificates expired

**Steps To Reproduce:**
- Installed K3s: 
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh`

**Actual behavior:**
Can't connect from local machine to server

**Additional context / logs:**

Hey, so certificates expired 1 year after installing k3s on debian server. I have been using it to host hobby project. To connect with k9s, I used certificate from `/etc/rancher/k3s/k3s.yaml` (I've read somewhere I should not do that now). 
It can't login now.

in syslog I see
```
k3s[561950]: E0416 14:51:35.168336  561950 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate has expired or is not yet valid: current time 2024-04-16T14:51:35Z is after 2024-04-05T15:45:38Z, verifying certificate SN=4060583514705729914, SKID=, AKID=79:E2:... failed: x509: certificate has expired or is not yet valid: current time 2024-04-16T14:51:35Z is after 2024-04-05T15:45:38Z]"
```

I tried to rotate certificates as mentioned [here](https://docs.k3s.io/cli/certificate).:
```
systemctl stop k3s
k3s certificate rotate
systemctl start k3s
```

I also tried [this](https://github.com/k3s-io/k3s/issues/5163#issuecomment-1219668522):
```
kubectl --insecure-skip-tls-verify delete secret -n kube-system k3s-serving
sudo rm -f /var/lib/rancher/k3s/server/tls/dynamic-cert.json
sudo systemctl restart k3s
```

From what amateur me can spot, certificates were renewed, but `/etc/rancher/k3s/k3s.yaml` contains old expired certificates? How do I adjust `~/.kube/config` in my local machine so I can connect to my hobby project k3s server? I wanna keep the setup as simple as possible.

**Comment by brandond** [comment]
> /etc/rancher/k3s/k3s.yaml contains old expired certificates?

No, that file is regenerated every time k3s starts.

> How do I adjust ~/.kube/config in my local machine so I can connect to my hobby project k3s server?

Copy the file over from the k3s server again, same as you did the first time.

**Comment by lucas03** [comment]
right, sorry about that, I guess I thought end of the certificate hash will be different. replaced it and it works now. Thank you!
