### ISSUE TITLE
Add support for SLE Micro 6.0

### ISSUE THREAD

**Issue by caroline-suse-rancher** [k3s-io/k3s#9955]
This should include versions 1.27, 1.28, 1.29, and potentially 1.30

**Comment by endawkins** [comment]
### Testing Validation
#### Versions: v1.27.16, v1.28.12, v1.29.7, and v1.30.4
#### Test Coverage:
- SUC Upgrade
- Cluster-Reset
- Cluster-Reset Retore Path
- Sonobuoy Conformance
