### ISSUE TITLE
Adding incorrect flag during install results in a error which is hard to figure out what is wrong

### ISSUE THREAD

**Issue by ammirator-administrator** [k3s-io/k3s#9978]
Doing a simple install let's say of a server or agent and providing a wrong flag result in systemd not being able to start the server/agent properly
And there is no error message about what is wrong, systemd or hangs or can't start k3s.service

I would expect the flags to be validated before starting the k3s.service

**Comment by brandond** [comment]
The install script doesn't validate the flags, it just writes them to the systemd unit. Having the install script do flag validation would significantly increase the complexity; I don't think it's a big ask to have to look at the logs to see what's wrong. It is not even really possible to validate ALL the flags, some are passed through directly to various Kubernetes components,  which will raise their own errors if the flags are wrong.

**Comment by ammirator-administrator** [comment]
Thanks for your answer
Yes is not hard to validate the flags manually

The problem is mainly that if you pass a wrong flag then you have to uninstall k3s and start from zero
A bit time consuming
Isn't there a way at least when Systemd starts the k3s.service to let k3s to display some message that something is wrong or not

Because the current behaviour is or it hangs or Systemd shows a general error and you have to search thru internet to understand what is wrong, doing systemctl status k3s also doesn't help there is just the exit code 1 or just displays a general text (Failed)

Not a big one, but can be a improvement for future

**Comment by brandond** [comment]
> The problem is mainly that if you pass a wrong flag then you have to uninstall k3s and start from zero

No you don't? You can just re-run the installer with the correct flags, or edit the systemd unit manually anrd reload/restart it.

**Comment by ammirator-administrator** [comment]
ok, Thanks
Didn't know about this possibility
Thanks for your time
