### ISSUE TITLE
K3s fails to start in a multi-network card environment with error "IPv6 was enabled but no IPv6 address was found on node"

### ISSUE THREAD

**Issue by xiaosaxu** [k3s-io/k3s#9979]
**Environmental Info:**
K3s Version: 

![image](https://github.com/k3s-io/k3s/assets/15903488/ab21ae4c-d6f1-4d26-9e59-a923c44f9ad1)

Node(s) CPU architecture, OS, and Version: 

![image](https://github.com/k3s-io/k3s/assets/15903488/a0ccc66d-2274-4431-82a2-b9095f124830)
![image](https://github.com/k3s-io/k3s/assets/15903488/041cf8d4-16d0-4839-96cc-452439617f06)
![image](https://github.com/k3s-io/k3s/assets/15903488/5ab69425-f180-4bb6-a1d0-142dea3cbcd7)
![image](https://github.com/k3s-io/k3s/assets/15903488/12f6d358-f1f4-405c-a644-f90200dbc8d8)

Cluster Configuration:

1 server
![image](https://github.com/k3s-io/k3s/assets/15903488/699dedd8-1b37-4f18-a657-bfea18f9b105)

**Describe the bug:**

In the above node information, there is a network card configuration. In the environment, there are two network cards, ens32 and ens36. Among them, ens32 is the network card used by the default route. If the IPv4 and IPv6 addresses of the ens32 network card are used to configure the node-ip of k3s, the installation can be successful; however, if the IPv4 and IPv6 addresses of the ens36 network card are used to configure the node-ip of k3s, the startup will fail. The error information shows that the IPv4 and IPv6 addresses used by flannel are those of the ens32 network card used by the default route. I took a quick look at the k3s code and found that if flannel is not configured, flannel will get a default external network card, so it uses the information of the ens32 network card. 
![image](https://github.com/k3s-io/k3s/assets/15903488/394fe4ac-b4c9-4ba3-b808-01e9912dd741)

To verify whether the issue is caused by the inconsistency between the network card used by k3s node-ip configuration and flannel, I conducted another experiment. I used --flannel-iface=ens36 in the k3s startup file, and k3s --node-ip use ens36 ipv4 and ipv6 address, so the network configration is consistent. Looking at the k3s log, flannel indeed uses the IPv4 and IPv6 addresses of the ens36 network card, but k3s still fails to start, and the error information still "IPv6 was enabled but no IPv6 address was found on node". Therefore, I speculate that in a multi-network card environment, does k3s not support using the address of a network card that is not used by the default route?

**Steps To Reproduce:**

- Enable system IPv6 feature
- Configure another external network card, and set up IPv4 and IPv6 addresses.
- Use the new network card  IPv4 and IPv6 addresses to config K3s --node-ip
- Use the new network card name to config K3s  --flannel-iface

**Expected behavior:**

k3s start up success
**Actual behavior:**

k3s start failed
**Additional context / logs:**

**Comment by brandond** [comment]
Do I understand correctly that you are changing the node-ip and flannel-iface settings on an existing node? If so, you will likely have to temporarily start k3s with --disable-network-policy so that the node can start up and update the node addresses to add the IPv6 address. Once that is done you can re-enable network policy.

@manuelbuil this seems to come up again from time to time, do you think we could perhaps get the netpol controller startup to retry, or wait until after the node addresses have been synced?

**Comment by xiaosaxu** [comment]
@brandond Thank you for your reply. My scenario is a new installation, not changing the network card for an already installed k3s environment. My problem is, if the Linux system has two network cards A and B, while A is the network card used by the default route, if the ipv4 and ipv6 configurations of A are given to k3s for installation, k3s can be installed successfully. But if the ipv4 and ipv6 addresses of B are configured for k3s installation, the installation will fail, indicating that "IPv6 was enabled but no IPv6 address was found on node".

**Comment by bingfengfeifei** [comment]
There is a configuration parameter flannel-iface, is it helpful to you?

**Comment by xiaosaxu** [comment]
@bingfengfeifei I used this parameter  --flannel-iface  to specify the network card name B, and the --node-ip parameter in k3s is also configured with the ipv4 and ipv6 addresses of this network card B( B is network card which not used by default routing rule) to install k3s, but k3s still reports "IPv6 was enabled but no IPv6 address was found on node". 
It seems that k3s cannot start using a network card that does not used by the default routing rule.

**Comment by brandond** [comment]
Good catch; 1.27.1 is fairly old at this point. Closing this out but can reopen if this can be reproduced on the latest release.

**Comment by xiaosaxu** [comment]
> Could you try with a newer version of k3s? I have just tried K3s with v1.29.3 and it was starting even if flannel was using one interface and I was defining the IPs of another interface in `node-ip`
tks，update k3s version to v1.29.4 can work！
