### ISSUE TITLE
k3s uninstall shouldn't delete k3s config.yaml

### ISSUE THREAD

**Issue by migs35323** [k3s-io/k3s#9981]
**Is your feature request related to a problem? Please describe.**
Sometimes when booting a node there are some initial issues that are easily fixed by uninstalling and reinstall the node, or there are situations when we want to convert a machine from an agent to server etc.

using the uninstall script is very convenient but it has the issue of deleting the k3s config filles that we might want to keep
however it has the drawback of deleting the entire config folder and we need to recreate it.

**Describe the solution you'd like**
i would like that the uninstall script either questioned to include the config files at /etc/rancher/k3s/ or flag that allows to keep theese files

**Comment by brandond** [comment]
Have you tried just doing `chattr +i /etc/rancher/k3s/config.yaml` so that the script can't delete it?
